### DISCUSSION TITLE
Help in an attempt to create a state

### DISCUSSION THREAD

**Discussion by OutofIdeas12345** [saltstack/salt#65602] [Q&A] [answered]
Good Day Salt-Community,

i am currently trying to make a simply salt state that just allows for unattended windows updates.
i wanted it to do more than just that for example i want it to create a log.file just for the state itself and also have a 15 sec delay after each and every machine.

`update_system:
    wua.uptodate`

thats what i understood but how to make it do the other two things, i cant get the hang of it.
Using the `--log-file=/path/to/file` in addition to the state apply command creates the log but is there a way to make it via the state itself?

**Comment by bogdanr** [comment, marked as answer]
Something like this should do what you need
```
install_windows_updates:
  module.run:
    - name: win_update.install
    - categories:
      - Security Updates
      - Critical Updates
    - download: True
    - install: True
    - reboot: True  # Set to False if you do not want the system to reboot automatically

# Optional: Schedule the updates to run at a specific time
schedule_windows_updates:
  schedule.present:
    - function: state.apply
    - job_args:
      - windows_updates
    - minutes: 1440  # Run daily (1440 minutes in a day)
    - splay: 600     # Randomize the run time by up to 10 minutes (600 seconds)
    - persist: True
    - run_on_start: True  # Run the job when the minion starts
    - enabled: True
```
