### DISCUSSION TITLE
salt['network.ip_networks'] always returns master nets, not minion nets, when used in pillar data

### DISCUSSION THREAD

**Discussion by bchill** [saltstack/salt#66064] [Q&A] [answered]
If I set a pillar with salt['network.ip_networks'], the pillar will always contain the master's networks, not the minion's. 

**pillars/top.sls**

```
base:
  '*':
    - init
```

**pillars/init.sls**

```
{%- set mynets = salt['network.ip_networks']() -%}

nets:
  mynets: {{ mynets }}

```

If I call salt['network.ip_networks'] from a state file and pass it to a jinja template or call it from jinja template, I get the minion's networks. This is true with ip_addrs and subnets as well, but grains['ipv4'] always returns the minion's IPs, even when used to set pillars.

All hosts are using 3006.6, and this happens on all minions, all of which are mix of rocky, redhat, ubuntu, etc..

**master version info**

```
Salt Version:
          Salt: 3006.6

Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 8.9 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 4.18.0-513.9.1.el8_9.x86_64
        system: Linux
       version: Rocky Linux 8.9 Green Obsidian
```

Is this a bug, or am I missing something fundamental?

Brian

**Comment by max-arnold** [comment, marked as answer]
This is expected, because states are rendered on a minion, but pillar is rendered on the master. When you call the `network.ip_networks` execution module in a pillar file, it runs on the master and returns master networks.

The `grains` dictionary on the master is different and returns grains for each minion that asked for its pillar data.

**Reply by bchill** [reply]
This could probably be better documented.

Thanks for the reply!

**Comment by bchill** [comment]
my workaround:

**local-grains.sls**

```
{% set local_nets =
{
	'subnets4': salt['network.subnets'](),
	'subnets6': salt['network.subnets6']()
}
%}

grains:
  file.serialize:
    - name: /etc/salt/grains
    - user: root
    - group: root
    - makedirs: yes
    - dataset: {{ local_nets }}

salt_minion_service:
   cmd.wait:
     - name: salt-call --local service.restart salt-minion
     - bg: true
     - order: last
     - watch:
       - file: /etc/salt/grains
```
