### DISCUSSION TITLE
catching typos

### DISCUSSION THREAD

**Discussion by dseomn** [saltstack/salt#66536] [Ideas]
Consider this example:

```
$ cat salt/file/typo_test.sls 
typo_test:
  test.nop:
  - requires:  # should be 'require'
    - does not exist
$ salt-ssh [REDACTED] state.apply typo_test testing=true  # should be test=true
[REDACTED]:

Summary for [REDACTED]
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   0.338 ms
```

There are two typos, and salt seems to completely ignore both of them. Has anybody thought about changing that so that either one of those would cause an error, or at least a warning?

I think this is somewhat complicated by all the usage of `**kwargs` because of all the shared args (like `require`) that can be parsed in different places. It seems like it would be possible to catch those typos though somehow. Maybe add a decorator to functions that records which arguments each function parses as an attribute of the function, then the glue code could check if there are any leftover args that nothing is using?

**Comment by bdrx312** [comment]
I think it would be possible to implement something like this, but would probably require a lot of work and changes based on how the salt code is currently written. A large part of the problem stems from the design decision that the generic state and requisite arguments for the state compiler like `require` are at the same same level of the definition hierarchy as the arguments to the state module functions themselves.  
If instead of states being designed to have a structure like this:
```
state_run_cmd:
  cmd.run:
    - name: "echo test"
    - require:
       - requirement
```
they had a structure that differentiated the arguments to the function from the arguments to the state compiler something like this:
```
state_my_pkgs:
  pkg.installed:
    - pkgs:
      - cowsay
  require:
    - requirement
```
or
```
state_run_cmd:
  cmd.run:
    - name: "echo test"
    - kwargs:
      - pkgs:
        - cowsay  
    - require:
      - requirement
```
The implementation could more easily avoid argument name conflicts as well as more easily do validation on the state compiler specific arguments.

With the current structure the other issue with doing validation that extra arguments are not passed is with the encapsulation and separation of logic.  The state compiler does not know or care about the arguments that are being passed to the state module functions; it just parses all the ones it knows and cares about and then passes the remaining arguments to state module function. Like you said the issue is with `**kwargs` since python does not care if you pass extra kwarg arguments that are not actually used. Each execution module would then either have to be required to not use `**kwargs` in the function signature or do its own validation of the arguments not used if it did.
