### DISCUSSION TITLE
Understanding map files

### DISCUSSION THREAD

**Discussion by bradawk1** [saltstack/salt#66938] [Q&A] [answered]
We have a salt state for tigervnc server on RHEL 8 & 9.  I don't like how it is set up because the vncserver.users and /etc/systemd/system/'vncserver@:2.service' are all explicitly defined in the salt state.  I was thinking we could put the user and port list in a map file and then create from that.  However, I'm not sure I understand the map syntax correctly.

FYI, the vncserver.users file looks like:

`:2=sid1
:3=sid2
:17=sid3`

and for every number in the above file, you create in /etc/systemd/system a systemd start script named:

'vncserver@:2.service'

for example.  I want to remove the association of port numbers and sids from the state file.  If anyone has suggestions, I'd love to hear it

**Comment by bdrx312** [comment, marked as answer]
You can just create a users.yaml file and import it with `import_yaml`

users.yaml:

```yaml
2: sid1
3: sid2
17: sid3
```

```
# import your yaml data ...
{% import_yaml "users.yaml" as users %}

# now you can use it something like...
{%- for port, sid in users.items() %}
"/etc/systemd/system/vncserver@:{{ port }}.service"
  file.managed:
     - user: root
     - group: root
     - mode: '0644'
     - source: "salt://{{ tpldir }}/etc/systemd/system/vncserver.service.j2"
     - template: jinja
     - context:
         sid: "{{ sid }}"  
{% endfor %}
```
