### DISCUSSION TITLE
Use of __env__ in file_roots master configuration declaration

### DISCUSSION THREAD

**Discussion by fs-nicola-worthington** [saltstack/salt#67045] [Q&A] [answered]
Hi everyone. I'm hoping you can offer some guidance regarding the use of `__env__` in the `file_roots:` directive in the Salt master configuration?

I am using Salt 3007.1 on the latest x86_64 Amazon Linux 2023 directly from the new Broadcom RPM repositories:

```
# rpm -qa salt\*
salt-3007.1-0.x86_64
salt-master-3007.1-0.x86_64
salt-cloud-3007.1-0.x86_64
salt-syndic-3007.1-0.x86_64
salt-api-3007.1-0.x86_64
salt-ssh-3007.1-0.x86_64
salt-minion-3007.1-0.x86_64
```

The documentation I have been referring to is:

- https://github.com/saltstack/salt/issues/55747
- https://docs.saltproject.io/en/latest/ref/configuration/master.html#roots-master-s-local-file-server
- https://docs.saltproject.io/en/latest/topics/pillar/index.html#dynamic-pillar-environments

We have a number of different teams and engineering staff who need to be able to test their branches of Salt state and pillar changes prior to merging into our Git SCM that contains all our Salt states. Previously we had uses the Salt native GitFS functionality, but due to the enormous size of our repositories and large number of branches, the performance was unusable (the GitFS implementation was an order of magnitude slower than just pointing to plain directories on the local filesystem). For that reason, we now have a GitLab CI job that just pushes the new branch changes to the Salt master filesystem. This works well, and fast.

In the past we were using Salt 3004, which did not support the use of `__env__` in the `file_roots:` or `pillar_roots:` directives. This means that we has to list every single saltenv and pillarenv combination in our Salt master configuration file, and all the associated different filesystem paths.

We have read that as of Salt 3005, use of `__env__` became supported in these directives.

However, we have found that it only seems to reliably work for the `pillar_roots:` directive.

When we use it in the `file_roots:`, we receive errors complaining of non-existant saltenvs.
For example `salt-call state.apply test=true pillarenv=team-sloth-testing saltenv=team-sloth-testing` would result in an error like `Nonexistent saltenv 'team-sloth-testing' found in include of 'defaults.centos' within SLS 'team-sloth-testing:defaults'`. ...but as soon as we put the hard-coded environment name and path into the `file_roots:` directive like we used to, it starts working fine again.

```
file_roots:
  base:
    - /srv/salt
    - /srv/salt-branches/base/states
  __env__:
    - /srv/salt
    - /srv/salt-branches/__env__/states
# For some reason the above __env__ declaration does not appear to work in the manner described in the documentation. It results in many errors like this:
# Nonexistent saltenv 'team-sloth-testing' found in include of 'defaults.centos' within SLS 'team-sloth-testing:defaults'
#  team-sloth-testing:
#    - /srv/salt
#    - /srv/salt-branches/team-sloth-testing/states

pillar_roots:
  base:
    - /srv/pillar
    - /srv/salt-branches/base/pillar
  __env__:
    - /srv/pillar
    - /srv/salt-branches/__env__/pillar
```

Is there something obviously wrong we are doing here?

Have is misunderstood the documentation?

Very much hoping someone can offer their insight and assit here.

Thanks all!
