### DISCUSSION TITLE
How does "names" work?

### DISCUSSION THREAD

**Discussion by Mogaba** [saltstack/salt#67206] [Q&A] [answered]
Hello,

I don't understand how "names" work. The docs https://docs.saltproject.io/en/latest/ref/states/highstate.html#names-declaration claims that this state:

```
test_files:
  file.managed:
    - names:
        - file1
        - file2
```
will be converted to:
```
file1:
  file.managed

file2:
  file.managed
```
But when I check the lowstate I see states with the same IDs:
`$ salt test-altsp state.show_low_sls test`

```
test-altsp:
    |_
      ----------
      __env__:
          base
      __id__:
          test_files
      __sls__:
          test
      fun:
          managed
      name:
          file1
      order:
          10000.0001
      state:
          file
    |_
      ----------
      __env__:
          base
      __id__:
          test_files
      __sls__:
          test
      fun:
          managed
      name:
          file2
      order:
          10000.0002
      state:
          file
```

But the docs says that you can't have two states with same IDs! So how does this work?

**Comment by lkubb** [comment, marked as answer]
I think you're pointing out an oversimplification in the docs.

In general, duplicate state IDs are disallowed in the highstate data structure because it's a mapping, where duplicate keys would necessarily overwrite each other (and, if defined in the same SLS, be unrepresentable).

The `names` parameter influences the state compiler (which compiles the highstate data structure into lowstate chunks), specifically here:

https://github.com/saltstack/salt/blob/9233e1cc3b6b072a61b445d285ba856fc642ef3b/salt/state.py#L676-L692

A more accurate simplification:

For each `names` item, it copies the corresponding state, sets a new `name` (+ applies overrides if defined) and appends it to the lowstate, which is a list of individual state module calls (chunks). Since state IDs are not used to index these chunks, duplicate IDs are (somewhat) acceptable here.

This cannot be communicated properly using the YAML representation of the highstate because it's invalid:

**Note**: The referenced example state using `pkg.installed` is flawed. You almost never want to use `names` with `pkg.installed` since that causes each package to be installed separately. Use the `pkgs` parameter, unless you need each package to be require-able individually via `- pkg: python-django` etc. I'm using `file.absent` here instead.

```yaml
unwanted-files:
  file.absent:
    - names:
      - /foo
      - /bar
      - /baz
```

=>

(highstate, invalid YAML/data structure)
```yaml
unwanted-files:
  file.absent:
    - name: /foo
unwanted-files:
  file.absent:
    - name: /bar
unwanted-files:
  file.absent:
    - name: /baz
```

(simplified lowstate, valid YAML/data structure)
```yaml
- id: unwanted-files
  name: /foo
  state: file
  fun: absent
- id: unwanted-files
  name: /bar
  state: file
  fun: absent
- id: unwanted-files
  name: /baz
  state: file
  fun: absent
```
