### DISCUSSION TITLE
Feature Request : Add synchronous refreshing methods to saltutil

### DISCUSSION THREAD

**Discussion by JeremieCharest** [saltstack/salt#67240] [Feature Requests]
Is it possible to add a sync method/parameter for ­­­`saltutil:refresh_pillar`, `saltutil:refresh_grains` and all others "refresh_xxx"? Currently the documentation doesn't mention the fact that they are async methods. That create us several mysterious bugs.

salt/saltutil.py

```
def refresh_pillar():
    try:
        ret = __salt__['event.fire']({}, 'pillar_refresh')
    except KeyError:
        log.error('Event module not available. Module refresh failed.')
        ret = False  # Effectively a no-op, since we can't really return without an event system
    return ret
```

We were having a few sls that modified pillars, refreshed them and worked on the "updated" values inside modules :

```
refresh_pillar:
  file.append:
    - name: /srv/salt/base/pillar/dummy.sls
    - text: |
        dummy:
          testProps: {{ [1, 45, 666, 9999, 24234, 45345345] | random }}
    - require:
      - file: write_dummy_pillar
  module.run:
    - name: saltutil.refresh_pillar
    - require:
      - file: refresh_pillar

# this module will print the previous pillar value, not the new one
broken_state_due_to_async_refresh:
  module.run:
    - name: print_pillar.test
    - require:
      - module: refresh_pillar
```

Do you know a workaround that we could use to obtain real updated values?
