### DISCUSSION TITLE
Salt-Cloud libvirt provider lacks cpu, memory and networking options

### DISCUSSION THREAD

**Discussion by f-andriot** [saltstack/salt#67282] [Feature Requests]
### Description of Issue/Question
Hello, I'm using the Salt-Cloud 'libvirt' provider. Compared to the 'vmware' provider, there are missing options that I need.

Taken from https://docs.saltstack.com/en/latest/topics/cloud/vmware.html:
- num_cpus
- memory
- devices / network

Currently, in the libvirt provider, all above options are inherited from the source virtual machine, there is no way to customize them with salt-cloud.

I am currently developing a patch to add these features.

### Setup
CentOS 7.6, basic setup based on the tutorial:
https://docs.saltstack.com/en/latest/topics/cloud/libvirt.html#provider-configuration

Provider:
```
local-kvm:
  driver: libvirt
  url: qemu:///system
  validate_xml: no
```

Profile:
```
centos7:
  provider: local-kvm
  base_domain: base-centos7-64
  ip_source: qemu-agent
  ssh_username: root
  password: my-very-secret-password
  clone_strategy: quick
  minion:
    master: 192.168.0.35
    master_port: 4506
  num_cpus: 2
  memory: 2048MB
  devices:
    network:
      eth0:
        type: bridge
        mac: '52:54:00:00:00:01'
        source: br0
        model: virtio
      eth1:
        type: network
        mac: '52:54:00:00:00:02'
        source: default
        model: virtio
```

### Steps to Reproduce Issue
`# salt-cloud --log-level=debug -p centos7 my-centos7-clone`

Inspect resulting VM using any libvirt client: you will see that options 'num_cpus', 'memory' and everything under 'devices' are ignored.

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
