### DISCUSSION TITLE
pki keys are still created with salt-ssh and ssh_use_home_key

### DISCUSSION THREAD

**Discussion by mitar** [saltstack/salt#67324] [Feature Requests]
When I use `salt-ssh` with `ssh_use_home_key: True` set in `master` configuration, I see that `salt-ssh.rsa` and `salt-ssh.rsa.pub` are still created inside the pki directory, but not really used it seems. This is confusing. I would suggest that files are not created if not needed.

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul 14 2015, 19:46:27)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 14.5.0
         system: Darwin
        version: 10.10.5 x86_64
```
