### DISCUSSION TITLE
salt-cloud should allow use of aws_profile instead of AWS_ID's

### DISCUSSION THREAD

**Discussion by eedgar** [saltstack/salt#67363] [Feature Requests]
### Description of Issue
We use lots of aws accounts and rotate the keys regularly.  We need to use the keys configured in the .aws/credentials file and refer to the AWS_PROFILE.

### Setup
normal salt-cloud config but instead of using AWS_ID and AWS_SECRET use AWS_PROFILE
eg AWS_PROFILE=ProductionAccount

where the .aws/credentials contains something like
[ProductionAccount]
aws_access_key_id = <redacted>
aws_secret_access_key = <redacted>

**Comment by garethgreenaway** [comment]
@eedgar Thanks for the report.  Approving this for a future feature request.
@saltstack/team-cloud FYI.

**Comment by alexz71** [comment]
@garethgreenaway 

Proposing solution: a read-only SDB module which would be reading content of directory used by AWS CLI. Usually, ~/.aws

Assuming a SDB module `awscli` exist then following configuration would be possible:

in master config:
```
awsmanager1:
  driver: awscli
  datadir: /home/awscliuser1/.aws
```

in cloud.providers:
```
production_provider:
  id: sdb://awsmanager1/awsprofile/aws_access_key_id
  key: sdb://awsmanager1/awsprofile/aws_secret_access_key

test_provider:
  id: sdb://awsmanager1/testprofile/aws_access_key_id
  key: sdb://awsmanager1/testprofile/aws_secret_access_key
```

That is, if AWS CLI indeed configured with profiles names `awsprofile` and `testprofile`.
Pulling AWS profile specific default region from .aws files would also be as trivial.
It is also implied that Salt master's user has read access to files in directory specified by `datadir` parameter of proposed awscli SDB module.

Would this work ? Comments ?
