### DISCUSSION TITLE
[FEATURE REQUEST] Allow appending instead of replacing zabbix templates

### DISCUSSION THREAD

**Discussion by colttt** [saltstack/salt#67404] [Feature Requests]
**Is your feature request related to a problem? Please describe.**
It would be very nice if we can add the possibility to just add a new template to zabbix in the module states.zabbix_host. Currently, it is not possible to just add a new template, I must call all templates.

**Describe the solution you'd like**
We've a state that install the zabbix-agent and create this host in zabbix and add a template (mostly the Linux-Template) and if this server also have additional services like apache, we call also the apache-install-state which also add the Zabbix-Template "App Apache", but instead of using just assign the new template like:
```
apache_template_to_host:
  zabbix_host.assign_templates:
    - host: {{ grains['host'] }}
    - templates:
      - "Template App Apache by Zabbix agent"
```
we must call all templates that we want:
```
apache_template_to_host:
  zabbix_host.assign_templates:
    - host: {{ grains['host'] }}
    - templates:
      - "Template App Apache by Zabbix agent"
      - "Template OS Linux"
```
the state could be called the current templates and in the second call it could be add the current templates + new templates
