### DISCUSSION TITLE
pass salt function result to another function

### DISCUSSION THREAD

**Discussion by skob** [saltstack/salt#67441] [Feature Requests]
**Is your feature request related to a problem? Please describe.**
my problem is very similar to #51794 — I need to parse `return` from salt.function and parse it for next states. It's not easy to use reactor , because many states need to be runned in my orch.
How can I achieve this?

**Describe the solution you'd like**
Maybe something like registering variable or ability to pass return to next state

**Describe alternatives you've considered**
Maybe I can identify `return` in reactor , maybe via pillar, like

```
pillar:
  - identifier: myrun

...
salt/job/20200605145050995440/ret/saltbot-01/myrun {

}
```

**Additional context**
```
show {{ role }} revision:
  salt.function:
  - tgt: '{{ compound }}'
  - tgt_type: compound
  - name: git.revision
  - arg:
    - {{ settings.main_path }}/{{ component.get(role) }}/
  - queue: True
  - require_in:
    - salt: parse and report success
  - onfail_in:
    - salt: parse and report failed
```

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.
