### DISCUSSION TITLE
[FEATURE REQUEST] Add banner feature to pkgrepo.managed

### DISCUSSION THREAD

**Discussion by johnnybubonic** [saltstack/salt#67445] [Feature Requests]
**Is your feature request related to a problem? Please describe.**
When using `pkgrepo.managed`, it is very messy to provide an equivalent behavior to `slsutil.banner`.
There is, of course, the `comments:` parameter to `pkgrepo.managed`, but this:

- Places comments *after* the repository
- Automatically prepends a `# `
- Expects a list

In our organization, we use the slsutil banner at the *top of the file* (as one would expect by the name "banner") to indicate that techs should not directly modify the file (or, if they do, they should expect them to be temporary) and should submit a change request instead.

**Describe the solution you'd like**
I propose a new parameter to `pkgrepo.managed`, **`banner`**, a dict that accepts the arguments to `slsutil.banner` as keys:

```yaml
Install Foo Repository:
  pkgrepo.managed:
Ensure MongoDB Repository for UniFi:
  pkgrepo.managed:
    - name: "foobar-10"
    - humanname: "FooBar 10"
    - baseurl: "https://foo.domain.tld/redhat/$releasever/10/"
    - enabled: 1
    - gpgcheck: 1
    - gpgkey: "https://foo.domain.tld/redhat/pkgsig.asc"
    # Example here.
    - banner:
        width: 80
        title: 'AN EXAMPLE BANNER'
        text: 'A CUSTOM WARNING HERE'
        # And so forth.
```

which would then be at the *top* of the file.

**Describe alternatives you've considered**
Unholy atrocities against Jinja via a macro and `.splitlines()`
(Which still doesn't put it at the beginning of the file.)

The closest this gets is the eye-bleeding e.g.:

```
# 
# #
# THIS FILE IS MANAGED BY SALT - DO NOT EDIT              #
# #
# The contents of this file are managed by Salt. Any changes to this   #
# file may be overwritten automatically and without warning.           #
# 
#
```

**Additional context**
N/A
