### DISCUSSION TITLE
[FEATURE REQUEST] Pass custom HTTP header with access token to file.managed

### DISCUSSION THREAD

**Discussion by AshotMA** [saltstack/salt#67459] [Feature Requests]
I want to download files from private repositories using raw.githubusercontent.com API, but to do so, I need to put an authorization header inside the HTTP request. 

I would like to be able to write such state:

```
{% set github_token = salt['pillar.get']('github:token') %}

/usr/local/bin/script.js
  file.managed:
    - source: https://raw.githubusercontent.com/my/private/repo/script.js
    - headers:
        Authorization: 'token {{ github_token }}'
    - user: root
    - group: root
    - mode: 755
    - use_etag: True
```

I tried to use cmd.run with curl or wget, but it will download the file every time to check the hash, and I want to use etag feature, so the file will be downloaded only when changed. 

This is actually a copy of this request:
https://github.com/saltstack/salt/issues/40303
