### DISCUSSION TITLE
[FEATURE REQUEST] Require Relative SLS

### DISCUSSION THREAD

**Discussion by Pheric** [saltstack/salt#67467] [Feature Requests]
Repost of closed issue #10838.

I would like to require a relative SLS, in the same fashion as including a relative sls:
```yaml
include:
  - .anothersls

State Requiring Relative SLS:
  test.nop:
    - require:
      - sls: .anothersls
```

A current alternative way to do the above, [as mentioned by @mallniya](https://github.com/saltstack/salt/issues/10838#issuecomment-391718086) (but updated for modern versions of Salt):
```yaml
include:
  - .anothersls

State Requiring Relative SLS:
  test.nop:
    - require:
      - sls: {{ slsdotpath }}.anothersls
```
