### DISCUSSION TITLE
[FEATURE REQUEST] allow mysql_user.present to specify a comment

### DISCUSSION THREAD

**Discussion by dland** [saltstack/salt#67496] [Feature Requests]
**Description**
For documentation purposes, it is nice to have comment on a mysql user to describe why/where/what it is used for. A similar observation can be made for postgresql.

Creating a user in an .sls file could look like
```
frob:
  mysql_user.present:
    - host: 172.0.0.1
    - password: sekret
    - comment: This account is used by the frobnicator service
```

The end query issued to mysql would be
`CREATE USER IF NOT EXISTS 'frob'@'127.0.0.1' identified by 'sekret' COMMENT 'This account is used by the frobnicator service';`

Unfortunately, [this is not implemented](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.mysql_user.html)
