### DISCUSSION TITLE
Feature request: filesystem label support for blockdev.formatted

### DISCUSSION THREAD

**Discussion by Talkless** [saltstack/salt#67503] [Feature Requests]
### Description of Issue/Question

mkfs.ext4 and mkfs.xfs has -L option to set human readable file system label. Though blockdev.formatted accepts kwargs, blockdev.format execution module does not currently have ability to set label.

**Comment by Ch3LL** [comment]
@Talkless I think this is a sound idea to add this feature. Thanks

**Comment by shallot** [comment]
I seem to have run across this issue - I'm trying to get some file systems formatted with specific labels, but blockdev.formatted provides no apparent option to specify a label that would in turn be passed down to the mkfs function.

**Comment by dhs-rec** [comment]
In addition to this, it would also be great to support passing arbitrary options to the various mkfs tools. For example, I currently need to use a cmd.run to format an XFS filesystem because neither -L nor -f are supported by blockdev.formatted:
```
format_device:
  cmd.run:
    - name: mkfs.xfs -f -LDOCKER /dev/{{ storage_dev }}
    - unless: blkid -p -n xfs /dev/{{ storage_dev }}|grep xfs
```
