### DISCUSSION TITLE
env_vars in pip_state vs. env in cmd

### DISCUSSION THREAD

**Discussion by dhs-rec** [saltstack/salt#67518] [Feature Requests]
### Description of Issue/Question
Why is there a difference in the way environment variables are specified in *pip.installed* and *cmd.run* state methods?

Examples from the documentation:
```
django:
  pip.installed:
    - name: django_app
    - env_vars:
        CUSTOM_PATH: /opt/django_app
        VERBOSE: True
```
vs.
```
script-foo:
  cmd.run:
    - env:
      - BATCH: 'yes'
```
Differences are:
1. env vs. env_vars
2. dict vs. array

Could this be streamlined, please, so that there's only one unique way of specifying environment variables (and everywhere else where I didn't spot it, of course)?

### See also:
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html#salt.states.cmd.run
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pip_state.html#salt.states.pip_state.installed
