### DISCUSSION TITLE
saltclass over git ?

### DISCUSSION THREAD

**Discussion by Poil** [saltstack/salt#67520] [Feature Requests]
### Setup
Hi,

Except the release note of 2018.03 I'm unable to find a documentation about saltclass, is it production ready ? This module have the same approach of what I used previously with Hiera on Puppet and seems to resolved all my issue with Pillar default/override configuration

Also, actually I have 

```
ext_pillar:
  - git:
    - master git@gitlab.xxxx:saltstack-pillars/pillar.git:
      - env: base
      - pubkey: /etc/pki/ssh/id_rsa.pub
      - privkey: /etc/pki/ssh/id_rsa
```

The configuration of saltclass is :

```
ext_pillar:
  - saltclass:
    - path : /srv/saltclass
```

So is it possible to have saltclass over git ?

Best regards,

**Comment by garethgreenaway** [comment]
@Poil Thanks for the report.  Since saltclass is using ext_pillar and ext_pillar is capable of using Git, it should be able to use Git.  Does the above not accomplish what you're trying to accomplish?
@saltstack/team-core Anyone have any thoughts on this one?

**Comment by Poil** [comment]
Have I to add a level like this ?

```
ext_pillar:
  - saltclass:
    - git:
      - master git@gitlab.xxxx:saltstack-pillars/pillar.git:
        - env: base
        - pubkey: /etc/pki/ssh/id_rsa.pub
        - privkey: /etc/pki/ssh/id_rsa
```

Or it's at the same level ?
```
ext_pillar:
  - saltclass
  - git:
    - master git@gitlab.xxxx:saltstack-pillars/pillar.git:
      - env: base
      - pubkey: /etc/pki/ssh/id_rsa.pub
      - privkey: /etc/pki/ssh/id_rsa
```

**Comment by garethgreenaway** [comment]
@Poil I believe it should be the first one.

**Comment by mrichar1** [comment]
Hi - just contemplating how to achieve the same thing, and trying the above doesn't work.

Setting:

```
ext_pillar:
  - saltclass:
    - git:
      - master https://git.example.com/saltclass.git
```

Results in:

```
- Failed to load ext_pillar saltclass: tuple indices must be integers, not dict
```

I'm not sure that even if this worked it would be a full solution, since saltclass also needs `master_tops` defined pointing to a path, and this won't have access to the `ext_pillar` files (and the `saltclass` files can't be on the saltfileserver since they also contain 'secret' pillar info).

My current workaround is to use the API and a `reactor` to orchestrate a `git pull` of the saltclass repo into `/srv/saltclass`, then stick with simple paths in the config.

Can anyone shed any light on the 'correct' way to get saltclass from git, or consider this a feature request if one doesn't exist?
