### DISCUSSION TITLE
[FEATURE] Warn when change of home-dir for existing user would fail

### DISCUSSION THREAD

**Discussion by mirko** [saltstack/salt#67545] [Feature Requests]
**Description**
Within a working sls file for managing users and their home dirs I'm changing the path to a user's homedir to another one.
This fails with:

```
          ID: user1
    Function: user.present
      Result: False
     Comment: These values could not be changed: {'home': '/tmp/user1'}
     Started: 22:55:58.740104
    Duration: 19.577 ms
     Changes:
```

**Setup**

**Steps to Reproduce the behavior**

Managing a user:

```
user1:
  user.present:
    - uid: 501
    - gid: 501
    - password: !
    - home: /home/user1
    - shell: /bin/sh
    - require:
      - group: user1
  group.present:
    - gid: 501
```

Execute sls on host, everything is fine.
Then changing the user's homedir, though, e.g. by changing the whole section from above to (ensuring /tmp/user1 exists and is owned by 'user1'):

```
user1:
  user.present:
    - uid: 501
    - gid: 501
    - password: !
    - home: /tmp/user1 # <<<<----------------
    - shell: /bin/sh
    - require:
      - group: user1
  group.present:
    - gid: 501
 ```

fails with:

```
          ID: user1
    Function: user.present
      Result: False
     Comment: These values could not be changed: {'home': '/tmp/user1'}
     Started: 23:06:12.741230
    Duration: 17.295 ms
     Changes:   
```

**Expected behavior**
Change of home dir successful.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-14-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**
Even though it's considered expected behaviour, I'd really fancy an override as it was implemented for uid/gid changes (`allow_uid_change=True`).
