### DISCUSSION TITLE
[FEATURE REQUEST] Add docker.apply state

### DISCUSSION THREAD

**Discussion by jappi00** [saltstack/salt#67557] [Feature Requests]
Hello together,

**Is your feature request related to a problem? Please describe.**
At the moment I have one problem, I want to run state in docker.

For that, I have followed that guide: https://docs.saltproject.io/en/latest/topics/tutorials/docker_sls.html

Currently my test state looks like this:

```yml
install vim in docker:
  module.run:
      - docker.call:
          - db
          - state.single
          - pkg.installed
          - name=vim
```

This will always be marked as "changed"

**Describe the solution you'd like**
I would like to implement an structure like the following:

```yml
install vim in docker:
      - docker.apply_state_in_container:
          - db
          - state.single
          - pkg.installed
          - name=vim
```

I'am not sure if this would be the best solution.

**Comment by welcome** [comment]
Hi there! Welcome to the Salt Community! Thank you for making your first contribution. We have a lengthy process for issues and PRs. Someone from the Core Team will follow up as soon as possible. In the meantime, here’s some information that may help as you continue your Salt journey.
Please be sure to review our [Code of Conduct](https://github.com/saltstack/salt/blob/master/CODE_OF_CONDUCT.md). Also, check out some of our community resources including:

  - [Community Wiki](https://github.com/saltstack/community/wiki)
  - [Salt’s Contributor Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html)
  - [Join our Community Slack](https://join.slack.com/t/saltstackcommunity/shared_invite/zt-3av8jjyf-oBQ2M0vhXOhJpNpRkPWBvg)
  - [IRC on LiberaChat](https://web.libera.chat/#salt)
  - [Salt Project YouTube channel](https://www.youtube.com/channel/UCpveTIucFx9ljGelW63-BWg)
  - [Salt Project Twitch channel](https://www.twitch.tv/saltprojectoss)

There are lots of ways to get involved in our community. Every month, there are around a dozen opportunities to meet with other contributors and the Salt Core team and collaborate in real time. The best way to keep track is by subscribing to the Salt Community Events Calendar.
If you have additional questions, email us at saltproject@vmware.com. We’re glad you’ve joined our community and look forward to doing awesome things with you!

**Comment by darless** [comment]
@jappi00  I don't see where this could be useful, could you state when this would be something you'd want to implement? Packages that need to be within the container is something that should be done in a Dockerfile. Additionally, if you need a configuration with custom settings in the container, then that is where volume binds come in between the host and the container. I would suggest using salt minions on the host, then provisioning configurations onto the host and binding those to the container, that is how I have done it, I have never seen a use for having salt-minions in containers.

**Comment by jappi00** [comment]
Hello @darless,

I think the example is a little bit missleading. I have found a nicer way to accomplish the running state in docker.

In this example, I have a running postgres container and I need to add a user to it.

Running sls in container
```yml
apply sls in docker container:
  module.run:
    - docker.apply:
      - name: db
      - mods: postgres
 ```

Sls to apply in docker
```yml
frank: postgres_user.present
```

The problem that the state is detected as "changed" persists. Maybe I have overseen something?
