### DISCUSSION TITLE
GlusterFS module/state doesn't support dispersed volumes

### DISCUSSION THREAD

**Discussion by p3lim** [saltstack/salt#67562] [Feature Requests]
### Description of Issue

Dispersed volumes is missing support in the GlusterFS module/state.
<https://docs.gluster.org/en/latest/Administrator%20Guide/Setting%20Up%20Volumes/#creating-dispersed-volumes>

Example implementation would look like this:

```yaml
my volume:
  glusterfs.volume_present:
    - bricks:
      ...
    - disperse: 5
    - redundancy: 1
    - start: true
```
