### DISCUSSION TITLE
file.directory needs a check_cmd

### DISCUSSION THREAD

**Discussion by af85** [saltstack/salt#67586] [Feature Requests]
### Description of Issue/Question

I am trying to manage the permissions and file/dir ownerships of a web server directory. This directory is being constantly updated by the web app (session data, tmp data, etc). When salt runs, and recursively updates the permissions, it complains that some files don't exist, because they were temporary and have been removed in the middle of the salt run. 

Can we get a check_cmd options for file.directory?
I'd like to do something like the following:
```
update-webapp-dir-permissions:
  file.directory:
    - user: {{ myapp.user }}
    - group: {{ myapp.group }}
    - recurse:
      - user
      - group
    - names:
      - {{ myapp.prefix }}/logs
      - {{ myapp.prefix }}/temp
      - {{ myapp.prefix }}/work
      - {{ myapp.datadir }}
    - check_cmd: /bin/true
```
### Setup

See above.

### Steps to Reproduce Issue

1. Create directory /var/myapp/
2. Create some script that will generate/delete mass amounts of files to /var/myapp/
3. Run a file.directory with recurse on the directory while the script (2) is running:
```
update-webapp-dir-permissions:
  file.directory:
    - name: /var/myapp
    - user: root
    - group: root
    - recurse:
      - user
      - group
```

### Versions Report

# salt --versions-report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
