### DISCUSSION TITLE
Pillar Merging Option in git_pillar [FEATURE REQUEST]

### DISCUSSION THREAD

**Discussion by bsoldhogg** [saltstack/salt#67581] [Feature Requests]
**Is your feature request related to a problem? Please describe.**
If a minion doesn't have `pillarenv` set, they qualify for everything defined in every git remote when using wildcards or grain targeting. I want to avoid using nodegroups as that would be another thing to maintain.

**Describe the solution you'd like**
I would like a similar approach to `PILLAR_SOURCE_MERGING_STRATEGY: None` available for git_pillar to prevent all top files from being merged. 

**Additional context**
My config looks like this:

```
ext_pillar:
  - git:
    - master https://token@gitlab.com/project/salt-dev-shared-pillar.git:
      - root: pillar
      - env: __env__
  - git:
    - master https://token@gitlab.com/project/salt-dev-pillar-customer1.git:
      - root: base
      - env: customer1
  - git:
    - master https://token@gitlab.com/project/salt-dev-pillar-customer2.git:
      - root: base
      - env: customer2
```
From this I would expect that everything can access the shared pillar and only the relevant environments can access customer1 and customer2

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.
