### DISCUSSION TITLE
Module service.stop use StopService instead of StopServiceWithDeps

### DISCUSSION THREAD

**Discussion by Denislb** [saltstack/salt#67598] [Feature Requests]
### Description of Issue

Module `service.stop` does not stop recursively services on windows.
We got an error when we try to stop  service with dependencies: `ERROR: Failed To Stop ServiceName: A stop control has been sent to a service that other running services are dependent on.`
The service and his dependencies are not stopped 

### Setup
- Windows 10
- Salt Minion 3000 py2

### Steps to Reproduce Issue
You can run:
`salt 'minion' service.stop "ServiceName"`  where ServiceName has dependencies

**Comment by Ch3LL** [comment]
we could probably add an arg to that state to call `StopServiceWithDeps` if its set. will approve as a feature request thanks.

**Comment by ghost** [comment]
On the [develop](https://github.com/saltstack/salt/blob/develop/salt/modules/win_service.py#L657 ) branch the modules support the requested functionality. I am not sure why this is not present in Salt 3000 (or master branch) as this is not totally new.

**Comment by Ch3LL** [comment]
yeah we recently changed our release and branch strategy detailed here https://github.com/saltstack/salt-enhancement-proposals/pull/20

so yes porting those changes to master would be the right approach. thanks for doing that.

**Comment by richarddbarnett** [comment]
Would this also affect `mod_watch` restarting a service?

I have a state
```
datadog-agent-service:
  service.running:
    - name: datadogagent
    - listen:
      - file: c:/ProgramData/DataDog/datadog.conf
      - file: c:/ProgramData/DataDog/conf.d/process.d/conf.yaml
```
and when one of the listened-to files changes Salt is unable to restart the service because there's a running `datadog-trace-service` that's dependent on `datadogagent`.
