### DISCUSSION TITLE
salt.state.firewalld.present needs updating

### DISCUSSION THREAD

**Discussion by mepreston** [saltstack/salt#67603] [Feature Requests]
**Is your feature request related to a problem? Please describe.**
needs updating to better support firewalld V0.8.6
should be reviewed what needs to be added/changed to 
support this version. For example a zone  has
"Protocols" and salt will give a syntax error if you try
to use it.

Secondly it would be a nice enhancement if there was a new
state to "reload" the running instance instead of restarting the
env.   see firewall-cmd --reload

A example zone listing from from firewalld:
# firewall-cmd --list-all --zone=home
home
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: ipv6-icmp
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

It seems firewalld hasn't been updated in a few years so it is missing
features that exist in the current  version. last update to doc was 2016.

**Describe the solution you'd like**
to support this syntax:
```
home:
  firewalld.present:
    - name: home
    - prune_services: True
    - interfaces:
      - enp1s0
    - protocols:
      - ipv6-icmp
    - services:
      - dhcpv6-client
      - mdns
      - ssh
```

which results in this error:
Passed invalid arguments: 'protocols' is an invalid keyword argument for 'firewalld.present'.

**Describe alternatives you've considered**
n/a

**Additional context**
firewall-cmd -V
0.8.6

Salt Version:
          Salt: 3002.2

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.
