### DISCUSSION TITLE
[FEATURE REQUEST] Linode Instance Networking Interfaces Support During VM Creation in Salt-Cloud

### DISCUSSION THREAD

**Discussion by zliang-akamai** [saltstack/salt#67617] [Feature Requests]
When creating a Linode instance as a VM via `salt-cloud`, it would be much nicer to support specifying network interfaces, like a VPC interface on `eth0`. This can be done by parsing `interfaces` list in a Linode profile and passing it to the Linode APIv4 during creation operation.

Sample profile file:

```yaml
my-linode-profile:
  provider: my-linode-provider
  size: g6-nanode-1
  image: linode/ubuntu22.04
  location: us-mia
  interfaces:
    - purpose: public
    - purpose: vlan
      label: cool-vlan
    - purpose: vpc
      subnet_id: 1234
      ipv4:
        vpc: 10.0.4.10
```
