### DISCUSSION TITLE
Add support for default bucket encryption in S3 buckets

### DISCUSSION THREAD

**Discussion by gabriellhrn** [saltstack/salt#67643] [Feature Requests]
### Description of Issue

This is a feature request.

AWS S3 has the option to enable [default encryption in S3 buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html), but it seems to be missing from the [boto_s3_bucket state](https://github.com/saltstack/salt/blob/develop/salt/states/boto_s3_bucket.py#L337). It would be nice if it was possible to enable encryption during bucket creation. I couldn't find the implementation for this or issues related to this feature; if they're exist, sorry for opening this one.

The configuration could be similar to the other parameters. Something like:

```yaml
boto_s3_bucket.present:
    ...
    - ServerSideEncryptionConfiguration:
        SSEAlgorithm: aws:kms
        KMSMasterKeyID: 000000-11111
```

### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report
N/A
