### DISCUSSION TITLE
selinux.module State Fails to Report Changes

### DISCUSSION THREAD

**Discussion by doc987** [saltstack/salt#67668] [Feature Requests]
SELinux modules appear to successfully install (if not present) or update (if installed, but have changes).  See example below.
```yaml
selinux_module_name:
  selinux.module:
    - name: module_name
    - install: True
    - source: salt://module_name.pp
```

However, ```selinux.module``` doesn't report having changes in the result summary for the minion, and any requisites that are tied to changes don't get triggered.  I imagine a typical requisite might be to run ```restorecon``` when a module changes.
```yaml
selinux_module_name_restorecon:
  cmd.run:
    - name: restorecon -R ... paths specified in module fc file
    - onchanges: [selinux_module_name]
```

What would be really fancy is to have an option to automatically run ```restorecon``` on all file paths with contexts specified in the module fc file.

Salt Version: 2017.7.3
