### DISCUSSION TITLE
Compound command execution doesn't work with salt-ssh

### DISCUSSION THREAD

**Discussion by max-arnold** [saltstack/salt#67670] [Feature Requests]
### Description of Issue

One of the base features ([Compound command execution](https://docs.saltstack.com/en/latest/topics/execution/remote_execution.html#compound-command-execution), #42)  doesn't work with `salt-ssh`:

```
% salt-ssh HOSNAME test.ping,test.version

HOSTNAME:
    ----------
    retcode:
        255
    stderr:
        'test.ping,test.version' is not available.
    stdout:
```

Why this is important: it is much faster to execute multiple commands at once, because a single `salt-ssh` invocation is slow.

### Versions Report

<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Mar 30 2019, 03:37:43)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 18.6.0
         system: Darwin
        version: 10.14.5 x86_64
```
</details>
