### DISCUSSION TITLE
Ability to change existing network adapters MAC-address through salt-cloud profile or map

### DISCUSSION THREAD

**Discussion by Timizki** [saltstack/salt#67701] [Feature Requests]
When cloning new virtual machine from template that have an network adapter configured for it, it is impossible at the moment change the network adapters MAC-address. There should be atleast some force flag that could make overriding the mac possible.

### Setup
Salt-cloud provider driver: vmware

CentOs Linux virtual machine Template in VMWare Vsphere which has a network adapter named ie. Network adapter 1 and with MAC-address 00:50:56:b2:31:a1.

Salt-cloud profile: /etc/salt/cloud.profiles.d/my-profiles.conf
```
Centos7:
  provider: vmware
  clonefrom: CentOs-template
  num_cpus: 4
  memory: 16GB
  dns_servers:
    - 1.1.1.1
  devices:
    network:
      Network adapter 1:
        switch_type: distributed
    disk:
      Hard disk 1:
        size: 120
        thin_provision: True
  datastore: MyDS_01
  folder: DSC_folder
  datacenter: Datacenter
  power_on: True
  template: False
  deploy: True
  wait_for_ip_timeout: 5
  customization: False
```

Salt-cloud map: /etc/salt/cloud.maps.d/my-maps.conf 
```
Centos7:
  my-first-machine:
     folder: my-vms
     devices:
       network:
         Network adapter 1:
           name: 'Public_Network_1'
           mac: '00:50:56:b2:ff:fe'
```

### Steps to Reproduce Issue
run comman salt-cloud -m  /etc/salt/cloud.maps.d/my-maps.conf  -l debug
Salt-cloud will report at the end that virtual machine is created with Network adapter 1 that has MAC-address 00:50:56:b2:31:a1 instead of what we have defined in map (00:50:56:b2:ff:fe).
The wrong MAC-address can be seen also in VMware Vsphere

### Versions Report
```
Salt Version:
            Salt: 3000
Dependency Versions:
    Apache Libcloud: 2.2.1
    cffi: 1.6.0
    cherrypy: Not Installed
    dateutil: Not Installed
    docker-py: Not Installed
    gitdb: Not Installed
    gitpython: Not Installed
    Jinja2: 2.7.2
    libgit2: 0.26.3
    M2Crypto: Not Installed
    Mako: Not Installed
    msgpack-pure: Not Installed
    msgpack-python: 0.6.2
    mysql-python: Not Installed
    pycparser: 2.14
    pycrypto: 2.6.1
    pycryptodome: Not Installed
    pygit2: 0.26.4
    Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
    python-gnupg: Not Installed
    PyYAML: 3.11
    PyZMQ: 15.3.0
    smmap: Not Installed
    timelib: Not Installed
    Tornado: 4.5.3
     ZMQ: 4.1.4

System Versions:
     dist: centos 7.6.1810 Core
     locale: UTF-8
     machine: x86_64
     release: 3.10.0-957.el7.x86_64
     system: Linux
     version: CentOS Linux 7.6.1810 Core

```
