### DISCUSSION TITLE
Specify the returner as a state argument

### DISCUSSION THREAD

**Discussion by terminalmage** [saltstack/salt#67706] [Feature Requests]
This would allow for individual states to use a specific returner without the need to apply that to all states via the `return` minion config option. For example:

```yaml
foo:
  file.managed:
    - name: /etc/foo.conf
    - source: salt://foo.conf
    - returner: slack
```
