### DISCUSSION TITLE
Feature request: allow master_tops to be single source of truth

### DISCUSSION THREAD

**Discussion by kiemlicz** [saltstack/salt#67705] [Feature Requests]
### Description of Issue/Question

Having salt configured with multiple environments (see topfiles in setup section) and
master_tops (ext_nodes) subsystem configured, during _state.apply_ I expect running states designated by master_tops. 
Whereas all states from all environments are run.

In following example I simply expect only the:
- _base_pkgs_
- _hosts_

from _base_ environment to be run.
Function _state.show_top_ also displays all states from all environments.

Is it bug/misconfiguration or my misunderstanding of something in salt?

Initially question was asked [in salt usergroup](https://groups.google.com/forum/#!topic/salt-users/OY8fgct8pAo)
### Setup

Master config file (_master.d/custom_):

```
interface: some_iface

autosign_file: /etc/salt/autosign.conf

external_auth:
  pam:
    saltuser:
      - '@runner'

master_tops:
  ext_nodes: /usr/bin/foreman-node

file_roots:
  base:
    - /srv/salt/base
  gui:
    - /srv/salt/gui
    - /srv/salt/base

ext_pillar:
  - puppet: /usr/bin/foreman-node

pillar_roots:
  base:
    - /srv/pillar/custom
  gui:
    - /srv/pillar/custom
  custom:
    - /srv/pillar/custom

pillar_merge_lists: True

rest_cherrypy:
    port: some_port
    host: some_host
    ssl_key: key_path
    ssl_crt: crt_path
```

`/usr/bin/foreman-node` for my sample node returns following YAML:

```

---
classes:
- base_pkgs
- hosts
parameters:
 puppetmaster: ''
 domainname: domain
 foreman_domain_description: home
 root_pw: "$pass"
 owner_name: Admin User
 owner_email: root@domain
 foreman_subnets:
 - name: domain
   network: xxx
   mask: 255.255.255.0
   gateway: xxx
   dns_primary: ''
   dns_secondary: ''
   from: ''
   to: ''
   boot_mode: DHCP
   ipam: None
   vlanid: ''
   network_type: IPv4
 foreman_interfaces:
 - ip: some_ip
   mac: some_mac
   name: blabla.com
   attrs: {}
   virtual: false
   link: true
   identifier: eth0
   managed: true
   primary: true
   provision: true
   subnet:
     name: domain
     network: xxxx
     mask: 255.255.255.0
     gateway: xxxx
     dns_primary: ''
     dns_secondary: ''
     from: ''
     to: ''
     boot_mode: DHCP
     ipam: None
     vlanid: ''
     network_type: IPv4
   subnet6:  
   tag:  
   attached_to:  
   type: Interface
 install-disk: "/dev/sda"
 salt_master: some_master
environment: base
```

My top files:
_base/top.sls_

```
base:
  '*':
    - hosts
    - repositories
    - base_pkgs
    - mounts
    - samba

  'not G@os:Windows':
    - match: compound
    - users
    - users_dotfiles
```

_gui/top.sls_

```
gui:
  'gpus:vendor:nvidia':
    - match: grain
    - nvidia_driver

  'not G@os:Windows':
    - window_manager

  '*':
    - base_pkgs_gui
    - browsers
```
### Steps to Reproduce Issue

Use master_tops (ext_nodes) with multiple environments configured like in setup section.
This particular example comes from foreman with salt integration.
### Versions Report

**Master**:

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 8.1.2
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.6.0-1-amd64
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Minion**:

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6 
```
