### ISSUE TITLE
Feature Request - Manage Java keystore

### ISSUE THREAD

**Issue by m87carlson** [saltstack/salt#10237]
We currently "manage" java keystores by simply pushing out a cacerts (or trustedcerts) we've created, but this is not really maintainable since we update once and sort of forget about it.

We also have certain java applications that are unable to launch with a separate certificate databases, and will always use the systems default jre/lib/security/certs

It would be really useful if there was a salt module to add CA's and trusted certificates to the keystore files.

Doing this seems relatively simple, since the command can basically shell out the keystore executable (and if not password is specified, use 'changeit'). It should probably check for an alias first, and then add it if it is not in the database, but there is some overhead there as it would have to run two separate commands.

**Comment by verydragon** [comment]
I was researching ways to get the cacert added for JVM, and then I have an alternative method (just cmd.run) ; D
  
cmd.run:
    - name: "sudo pathto/keytool -import -trustcacerts -alias xxx-cacert -keystore pathto/cacerts -file xxx.pem -storepass changeit -noprompt"

**Comment by sastorsl** [comment]
Did anybody get around to look into this?
I'm managing a keystore for an application with both public and private keys and have scripted the part where I'm creating the keystore from the bottom up, but of course should support verifying if a key is allready added, and if so under which alias, and add if it's not in the keystore.
I'll be happy to come up with use-cases and do some testing.

**Comment by jbouse** [comment]
I've ran into the same issue as we have to maintain certificates inside a java keystore for one of our applications. Right now I've simply got a state that reads information from pillar about what certs need to be deployed and executes the keytool calls via cmd.run.

That said I will be working on trying to make a java keystore execute & state module to handle this for me after I finish writing my other 2 I'm currently working on for other applications.

**Comment by sastorsl** [comment]
Cool. I'll keep watching this thread and will be interested in testing - if needed.

**Comment by rterbush** [comment]
Wanted to share the following set of states that I worked up to deal with this keystore task. I'd welcome any input as to how to do this better and would also welcome the addition of keystore state to manage this more directly.

```yaml
set_keystore_passwd:
  cmd.run:
    - name: '
      keytool -storepasswd -storepass changeme -new {{ pillar['keystorepass'] }}'
    - shell: /bin/sh
    - creates: /var/cache/salt/.keystorepass

install_keystore:
  file.managed:
    - name: /tmp/example.com.pkcs12
    - source: s3://bucket/example.com.pkcs12
    - source_hash: s3://bucket/example.com.pkcs12.sha1sum
  cmd.run:
    - name: |
        keytool -importkeystore -srckeystore /tmp/example.com.pkcs12 -srcstoretype PKCS12 -destkeystore keystore -deststorepass {{ pillar['keystorepass'] }} -srcstorepass {{ pillar['keystorepass'] }}
    - shell: /bin/sh
    - creates: /var/cache/salt/.keystoreimport
    - require:
      - cmd: set_keystore_passwd

remove_keystore_input:
  file.absent:
    - name: /tmp/example.com.pkcs12
    - require:
      - cmd: install_keystore
```
