### ISSUE TITLE
ssh_auth.present changes every time even when there are no modifications to .ssh/authorized_keys

### ISSUE THREAD

**Issue by pwaller** [saltstack/salt#10259]
State:

```
munin-ssh-key:
  ssh_auth.present:
    - user: munin
    # Copied in directly otherwise options doesn't work, see saltstack/salt#10258
    # - source: salt://munin/config/id_rsa.pub
    - options:
      - no-agent-forwarding
      - no-port-forwarding
      - no-user-rc
      - no-X11-forwarding
      - no-pty
      - command="echo hi"
    - names:
      - ssh-rsa AAAAB3Nza...
```

Every time I run the state it shows as changes.

```
----------
    State: - ssh_auth
    Name:      ssh-rsa AAAAB3... munin@...
    Function:  present
        Result:    True
        Comment:   The authorized host key AAAAB3.. for user munin was updated
        Changes:   AAAAB3...: Updated
```

Expected behaviour: green.

```
 salt --versions-report
           Salt: 0.17.5
         Python: 2.7.5+ (default, Sep 19 2013, 13:48:49)
         Jinja2: 2.7
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```
