### ISSUE TITLE
Extending profile in EC2 cloud profile with tags does not extend tags

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#10407]
You could argue that this is functioning as designed, but I think it's not very helpful the way it is.

If I have something like:

```
some_profile:
  provider: some_configured_ec2_provider
  image: ami-12345678
  script: my_deploy_script.sh
  tag:
    Management: Salt
    Manager: some_host.somewhere.com

my_special_server.company.com:
  extends: some_profile
  size: m1.small
  location: us-east-1
  availability_zone: us-east-1c
  securitygroup:
    - my_sg
    - my_other_sg
  tag:
    Stack: Production
    Purpose: Whatever
```

What I really want is for the resulting tag setup of `my_special_server.company.com` to look like this:

```
tag:
  Management: Salt
  Manager: some_host.somewhere.com
  Stack: Production
  Purpose: Whatever
```

Same deal with the security groups, for that matter (assuming I was extending something that already had them). Instead of appending to the dictionaries, we're clobbering them. I don't think that's ideal as it leads to a lot of duplication when using the `extend` option a lot.
