### ISSUE TITLE
systemd socket activation support

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#10451]
At the moment salt support systemd service files to start/stop/enable/disable etc,
but it doesn't support systemd socket activation.

example:
```
# systemctl status sshd.service
sshd.service - OpenSSH Daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled)
   Active: inactive (dead)
```
```
# systemctl status sshd.socket                                                       :(
sshd.socket
   Loaded: loaded (/usr/lib/systemd/system/sshd.socket; enabled)
   Active: active (listening) since vr XXXX-XX-XX XX:XX:XX XXX; 27min ago
   Listen: [::]:22 (Stream)
 Accepted: 1; Connected: 0

XXX XX XX:XX:XX salt.example.com systemd[1]: Listening on sshd.socket.
```
This salt state will not fail but it starts only the service and it doesn't check the socket:
```
openssh:
  pkg.installed:
    - name: openssh
  service.running:
    - enable: True
    - name: sshd
    - require:
      - pkg: openssh
```
output:
```
----------
          ID: openssh
    Function: service.running
        Name: sshd
      Result: True
     Comment: Service sshd is already enabled, and is running
     Changes:   
              ----------
              sshd:
                  True
```
What I would like to do is:
```
openssh:
  pkg.installed:
    - name: openssh
  socket.listening:
    - enable: True
    - name: sshd
    - require:
      - pkg: openssh
```
output:
```
----------
          ID: openssh
    Function: socket.listening
        Name: sshd
      Result: True
     Comment: Socket sshd is already enabled, and is in the desired state
     Changes:   
```

More information about socket-activation:
http://0pointer.de/blog/projects/socket-activation.html

WORKAROUND: is using the full name of the systemd unit file.
```
openssh:
  pkg.installed:
    - name: openssh
  service.running:
    - enable: True
    - name: sshd.socket
    - require:
      - pkg: openssh
```
