### ISSUE TITLE
Cannot restart a service based on the watch condition on windows minion (v17.2)

### ISSUE THREAD

**Issue by emmellee** [saltstack/salt#10455]
When a watched file is changed, service.running successfully detects that and stops the service, however, it has never successfully restarted the service. I've tried both "reload: True" and "fully_restart: True".  But, no matter what service I've tried this on, it's never worked - salt-call seems to hang.  I've waited many, many minutes after service is down and must finally use ctrl-c to stop salt-call process.  Here is one of my state files:
```
sshGroup:
  group:
   - present

ssh-pkg-install:
  pkg:
    - installed
    - names:
      - sshClient
      - sshClientPatch
      - sshServer

E:\Attachmate\RSecureServer\Logs:
  file.directory:
    - makedirs: True

C:\ProgramData\Attachmate\RSecureServer\ssh-banner.txt:
  file:
    - managed
    - source: salt://STIG/ssh-banner.txt
    - makedirs: False

C:\ProgramData\Attachmate\RSecureServer\rsshd_config.xml:
  file:
    - managed
    - source: salt://STIG/rsshd_config.xml
    - makedirs: False
 
Attachmate Reflection for Secure IT Server:
  service.running:
    - enable: True
    - full_restart: True
    - watch:
      - file: C:\ProgramData\Attachmate\RSecureServer\rsshd_config.xml
```
