### ISSUE TITLE
[PROPOSAL] docker.highdata state function

### ISSUE THREAD

**Issue by JasonSwindle** [saltstack/salt#10679]
Howdy,

It would be great to have a Dockerfile created dynamically from your high data in your SLS files.  This would allow you to keep using SaltStack and Docker without duplicating work in either.
#### Example

```
my_rocking_dockerfile:
    docker.highdata:
        - path: /opt/docker_files/
        - override: True
```

What do you think?

Thanks!,

Jason Swindle, SSCE
Twitter :: @Human_USB
