### ISSUE TITLE
pkg.installed state not handling errors with test=True

### ISSUE THREAD

**Issue by Tanoti** [saltstack/salt#10728]
The pkg.installed state on version 0.17.5 seems to ignore errors when run with test=True. For example, we were trying to install a package from a custom yum repo that must not be seen by yum under normal circumstance to prevent people using yum to install it outside of our control, thus we used sources:

```
testpackage:
  pkg.installed:
    - sources:
      - testpackage: http://repos.mydomain.com/repo/testpackage-1.0.0-1.el6.noarch.rpm
```

While getting this set up we were using test=True and had made a mistake in the RPM URL so that it was not found. The test mode did not tell us of this error so we assumed all was OK only to have the state fail when we tried it for real.

The test mode should, at least, check that values like the fromrepo, source URL, etc exist and report if it might fail.
