### ISSUE TITLE
Require a relative sls file

### ISSUE THREAD

**Issue by kintel** [saltstack/salt#10838]
Ref. #5098

It looks like the require statement takes an absolute path to the required sls file. It would be cool if it could also support relative sls files, e.g.:

```
include:
  - .local

somename:
  - somemodule:somefunction
      - require:
          sls: .local
```

Today (0.17.5) the last require statement would have to read `sls: path.to.here.local`

**Comment by mbrgm** [comment]
@eliasp Are you sure about the duplicate? Isn't #14497 about a relative include instead of the need for relative require?

**Comment by basepi** [comment]
I think you may be right, thanks @mbrgm

**Comment by ekristen** [comment]
I've recently run into this problem. Big +1 to supporting relative requires for sls files.

**Comment by mallniya** [comment]
As a workaround one can use `slspath` variable:
```
somename:
  - somemodule:somefunction
      - require:
          sls: {{ slspath }}.local
```
