### ISSUE TITLE
requiring sls file containing only includes fail

### ISSUE THREAD

**Issue by kintel** [saltstack/salt#10852]
I have the following file structure:

```
includetest/init.sls
includetest/subtestfile.sls
includetest/testfile.sls
```

init.sls:

```
include:
  - includetest.testfile

/home/deploy/testfile2.txt:
  file.managed:
    - contents: Hello
    - require:
      - sls: includetest.testfile
```

testfile.sls:

```
include:
  - .subtestfile
```

subtestfile.sls:

```
/home/deploy/subtestfile.txt:
  file.managed:
    - contents: Hello
```

When running `salt-call state.sls includetest`, I get:

```
    State: - file
    Name:      /home/deploy/testfile2.txt
    Function:  managed
        Result:    False
        Comment:   The following requisites were not found:
                   require:
                       sls: includetest.testfile
```

Playing around a bit, it appears that this is caused by requiring a file containing _only_ includes. A workaround is to modify testfile.sls to do some arbitrary work.

Is this a bug or by design?
My use-case is to have a file including a bunch of states and requiring that file from various places.
(Tested on 0.17.5)
