### ISSUE TITLE
Suggestion: "once" requisite

### ISSUE THREAD

**Issue by stevage** [saltstack/salt#10850]
Fairly often I find myself wanting a "once" requisite with the following logic:
- if this state has ever run successfully, don't run.
- otherwise, run.

The standard workaround is to use "unless" to try to detect the effects of this state having run:

```
thing:
  cmd.run:
    - name: echo foo > /tmp/bar
    - unless: test -f /tmp/bar
```

But why not simplify:

```
thing:
  cmd.run:
    - name: echo foo > /tmp/bar
    - once
```

In some cases, as I think I mentioned on the mailing list, detecting those effects can be messy, or requires a bit of thought - which seems unnecessary.

Obviously this assumes that Salt is tracking the execution of states at this level, which may not be true.

(I'm not sure if this would have use outside of `cmd`).
