### ISSUE TITLE
fromrepo: repository change does not work

### ISSUE THREAD

**Issue by pille** [saltstack/salt#10965]
when i modified my formula to fetch ffmpeg from a PPA instead of the system repo,
the pkgrepo.managed state correctly adds the PPA.
however - the package is not forced to be reinstalled.

<pre>
{% set ffmpeg_ppa = "jon-severinsson/ffmpeg" %}

ffmpeg:
  pkg:
    - installed
    - fromrepo: {{ ffmpeg_ppa }}
    - require:
      - pkgrepo: {{ ffmpeg_ppa }}

{{ ffmpeg_ppa }}:
  pkgrepo.managed:
    - ppa: {{ ffmpeg_ppa }}
</pre>

<pre>
----------
    State: - pkgrepo
    Name:      jon-severinsson/ffmpeg
    Function:  managed
        Result:    True
        Comment:   Configured package repo 'jon-severinsson/ffmpeg'
        Changes:   repo: ppa:jon-severinsson/ffmpeg
</pre>

the log shows that salt thinks everything's already fine with ffmpeg.
when i manually remove the package, it gets selected for install from repo as expected.

**Comment by oliver-dungey** [comment]
I am experiencing the same problem with `pkg.latest` with yum on CentOS 6.7. An example:

```
salt-minion:
  pkg.latest:
    - fromrepo: "2015.8"
    - refresh: True
    - install_recommends: True
```

Reports that I already have the latest installed for that repo but I actually have `2016.3` installed from the `latest` repo. If I then change my state to:

```
salt-minion:
  pkg.latest:
    - fromrepo: "RUBBISH"
    - refresh: True
    - install_recommends: True
```
It also tells me I have the latest installed but it should really report `RUBBISH is not a valid repo` or something like that.
