### ISSUE TITLE
Unable to template overstate.sls file

### ISSUE THREAD

**Issue by edlane** [saltstack/salt#11313]
Attempting to construct a completely "Pillar Driven Deployment" (PDD) without needing to hard code any machine names into the .sls files themselves. For example, from a single pillar file we create the VMs, install the software packages, interconnect the services, and startup the services, ...**wherever they are deployed!**
There is also a "destroy.sls" which is driven from this same pillar file.

This is why a PDD is more flexible than an SLS approach alone.

This pillar file is processed with a simple (reusable) set of templated .sls files.

All the .sls files (including the "top.sls" file) allow for templating **except for the "overstate.sls" file**

The construction layout for a multi-tiered, multi-cloud, multi-vm, multi-service, can be specified in a single pillar file like this one:

```
# /srv/pillar/layout.sls

layout:
  -
    - name: lane-hp64
      type: igor
      cloud: lane-hp64
      minion: local
      template: ubuntu
      bundle:
        - core
        - database
        - master
  -
    - name: LXC-1
      type: lxc
      cloud: lane-hp64
      minion: lane-hp64
      template: ubuntu
      bundle:
        - testme
        - core
        - keys
        - users
        - master
        - firewall
  -
    - name: LXC-2
      type: lxc
      cloud: lane-hp64
      minion: lane-hp64
      template: ubuntu
      bundle:
        - testme
        - core
        - keys
        - users
        - control
        - database
        - firewall

[... stuff delete....]
```

Because "overstate.sls"  cannot be templated we have to hard code a machine name into that one file -- preventing a completely reuseable solution.

Is there a reason why "overstate.sls" files are not templated?
