### ISSUE TITLE
Add a notifiers system

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#11330]
Salt minions are persistent root level daemons on all systems and can fire events to the master. It would be awesome to have a network-wide inotify like functionality for files, directories, and maybe services. For files and directories, using inotify would be ideal since it would be low-overhead. For services dbus may be the best option.

Basically, the salt-minion could be configured to watch for changes on the filesystem or services and would send events that could be reacted on locally or by the master. I could see a configuration similar to the following:

``` yaml
notifiers:
  files:
    - /var/lib/myapp/file
    - /var/lib/myapp/file2
  directories:
    - /var/lib/myappdir
  services:
    - apache2
```

Maybe even better than setting this in the minion config would be a way for this to be distributed from the master like other components. Then the notifiers modules could register things to be notified on dynamically.
