### ISSUE TITLE
- exclude does not exclude a watch_in

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#11373]
In this example:
cat /srv/salt/test.sls

```
mypkgs:
  pkg.installed:
    - pkgs:
      - erlnode
      - erlang
    - watch_in:
      - service: erlnode

erlnode:
  service.running
```

Then in another sls file we include and exclude:
cat /srv/salt/test2.sls

```
include:
  - test

/etc/foo:
  file.managed:
    - source: salt://foo

exclude:
 - id: mypkgs

extend:
  erlnode:
    service:
      - require:
        - file: /etc/foo
```

If you run

```
salt-call state.sls test2
```

Then you get an error because the watch_in gets converted to a watch before the  mypkgs state gets excluded.
