### ISSUE TITLE
cmd.run cwd should not be checked before preconditions

### ISSUE THREAD

**Issue by eeaston** [saltstack/salt#11497]
Interesting catch-22 issue here. 
Say you have:

    TaskA:
       cmd.run:
        - name: mkdir /tmp/a
        - unless:  which B

    TaskB:
       cmd.run:
       - name: echo "hello" > /bin/B
       - unless: which B
       - cwd: /tmp/a
       - require: 
          - TaskA

The first time this provisions, it works fine. Then the machine reboots and /tmp is gone.  
The next time it provisions, it will fail because the cwd for TaskB no longer exists, and wont be created because the 'unless' precondition of TaskA is now fulfilled. We're stuck. 

I know this seems a silly case, but you can conceivably see a number of chained build steps doing something like this. 

I've had a stab at fixing this here at eeaston/salt@3273ae on the 2014.1 branch, but it's a bit of an API change. The changes were to move the cwd existence checking until after the precondition checking, and also remove the cwd from the context of the 'unless' and 'onlyif' tests.
 
If you'd like me to continue on this I can (I'll write some tests and stuff), but the removal of the cwd from the 'unless' and 'onlyif' checks will need to be documented. 
What say ye?
Cheers,
Ed

**Comment by frumpel** [comment]
I have a real use case for this - and I think the precondition check isn't just wrong for CWD but the whole cmd.run execution:

The example may seem contrived but it's based on Oracle's installer package being dirty and (a) leaving files in places other than the current working directory and (b) using unzip in a way where it tries to ask whether to unzip a file over top of an existing one even it it doesn't have a terminal :(

This fails:

```
# Install jdk 1.6.0_32 from tarball in AWS

{% set major_version = 6 %}
{% set minor_version = 32 %}

/tmp/jdk/:
  file.directory:
    - user: root
    - group: root
    - unless: test -d /usr/java/jdk1.{{major_version}}.0_{{minor_version}}

/tmp/jdk/jdk-{{major_version}}u{{minor_version}}-linux-x64-rpm.bin:
  file.managed:
    - source: https://s3-us-west-2.amazonaws.com/smart-smex-salt-bucket/Linux/CentOS/Binaries/jdk-{{major_version}}u{{minor_version}}-linux-x64-rpm.bin
    - source_hash: md5=b30130fce5769b72608bbfc83ab1de4a
    - user: root
    - group: root
    - unless: test -d /usr/java/jdk1.{{major_version}}.0_{{minor_version}}
    - require:
      - file: /tmp/jdk/

expand_jdk_{{major_version}}_{{minor_version}}:
  cmd.run:
    - name : /bin/sh /tmp/jdk/jdk-{{major_version}}u{{minor_version}}-linux-x64-rpm.bin -noregister
    - cwd: /tmp/jdk
    - unless: test -d /usr/java/jdk1.{{major_version}}.0_{{minor_version}}
    - require:
      - file: /tmp/jdk/jdk-{{major_version}}u{{minor_version}}-linux-x64-rpm.bin

# We need to do this because otherwise the stupid sfx extractor hangs when 
# checking whether we really want to overwrite the already present files
delete_jdk_{{major_version}}_{{minor_version}}:
  cmd.run:
    - name: rm -rf /tmp/jdk /root/jdk-6u32-linux-amd64.rpm
    - unless: test -d /usr/java/jdk1.{{major_version}}.0_{{minor_version}}
    - require: 
      - cmd: expand_jdk_{{major_version}}_{{minor_version}}
```

```
local:
----------
          ID: /tmp/jdk/
    Function: file.directory
      Result: True
     Comment: unless execution succeeded
     Started: 03:36:41.847419
    Duration: 32.95 ms
     Changes:   
----------
          ID: /tmp/jdk/jdk-6u32-linux-x64-rpm.bin
    Function: file.managed
      Result: True
     Comment: unless execution succeeded
     Started: 03:36:41.889589
    Duration: 23.648 ms
     Changes:   
----------
          ID: expand_jdk_6_32
    Function: cmd.run
        Name: /bin/sh /tmp/jdk/jdk-6u32-linux-x64-rpm.bin -noregister
      Result: False
     Comment: Desired working directory "/tmp/jdk" is not available
     Started: 03:36:41.922704
    Duration: 1.255 ms
     Changes:   
----------
          ID: delete_jdk_6_32
    Function: cmd.run
        Name: rm -rf /tmp/jdk /root/jdk-6u32-linux-amd64.rpm
      Result: False
     Comment: One or more requisite failed
     Started: 
    Duration: 
     Changes:   

Summary
------------
Succeeded: 2
Failed:    2
------------
```

Note how the FOURTH stanza also fails. It simply fails on the require line even though it doesn't have a cwd. Without looking at the code I would interpret this as the require being evaluated before the unless.

The following succeeds but it's ugly because on subsequent runs it will create and destroy directories and thus always look like something is changing:

```
# Install jdk 1.6.0_32 from tarball in AWS

{% set major_version = 6 %}
{% set minor_version = 32 %}

/tmp/jdk/:
  file.directory:
    - user: root
    - group: root

/tmp/jdk/jdk-{{major_version}}u{{minor_version}}-linux-x64-rpm.bin:
  file.managed:
    - source: https://s3-us-west-2.amazonaws.com/smart-smex-salt-bucket/Linux/CentOS/Binaries/jdk-{{major_version}}u{{minor_version}}-linux-x64-rpm.bin
    - source_hash: md5=b30130fce5769b72608bbfc83ab1de4a
    - user: root
    - group: root
    - unless: test -d /usr/java/jdk1.{{major_version}}.0_{{minor_version}}
    - require:
      - file: /tmp/jdk/

expand_jdk_{{major_version}}_{{minor_version}}:
  cmd.run:
    - name : /bin/sh /tmp/jdk/jdk-{{major_version}}u{{minor_version}}-linux-x64-rpm.bin -noregister
    - cwd: /tmp/jdk
    - unless: test -d /usr/java/jdk1.{{major_version}}.0_{{minor_version}}
    - require:
      - file: /tmp/jdk/jdk-{{major_version}}u{{minor_version}}-linux-x64-rpm.bin

# We need to do this because otherwise the stupid sfx extractor hangs when 
# checking whether we really want to overwrite the already present files
delete_jdk_{{major_version}}_{{minor_version}}:
  cmd.run:
    - name: rm -rf /tmp/jdk /root/jdk-6u32-linux-amd64.rpm
    - require: 
      - cmd: expand_jdk_{{major_version}}_{{minor_version}}
```

```
local:
----------
          ID: /tmp/jdk/
    Function: file.directory
      Result: True
     Comment: Directory /tmp/jdk updated
     Started: 03:38:40.618939
    Duration: 2.23 ms
     Changes:   
              ----------
              /tmp/jdk:
                  New Dir
----------
          ID: /tmp/jdk/jdk-6u32-linux-x64-rpm.bin
    Function: file.managed
      Result: True
     Comment: unless execution succeeded
     Started: 03:38:40.621698
    Duration: 32.782 ms
     Changes:   
----------
          ID: expand_jdk_6_32
    Function: cmd.run
        Name: /bin/sh /tmp/jdk/jdk-6u32-linux-x64-rpm.bin -noregister
      Result: True
     Comment: unless execution succeeded
     Started: 03:38:40.655846
    Duration: 32.614 ms
     Changes:   
----------
          ID: delete_jdk_6_32
    Function: cmd.run
        Name: rm -rf /tmp/jdk /root/jdk-6u32-linux-amd64.rpm
      Result: True
     Comment: Command "rm -rf /tmp/jdk /root/jdk-6u32-linux-amd64.rpm" run
     Started: 03:38:40.689592
    Duration: 33.351 ms
     Changes:   
              ----------
              pid:
                  3832
              retcode:
                  0
              stderr:
                  
              stdout:
                  

Summary
------------
Succeeded: 4 (changed=2)
Failed:    0
------------
Total states run:     4
```

**Comment by Reiner030** [comment]
Hi, 

Problem is still open... 

```
# salt-call --version
salt-call 2014.7.5 (Helium)
```
The "origin" state i found in a salt-template:
```
unpack-nexus-tarball:
  cmd.run:
    - name: curl -L '{{ nexus.source_url }}' | tar xz
    - user: {{ project_name }}
    - cwd: {{ nexus.download_dir }}
{%-   if pillar['project']['name'] != None %}
    - unless: test -d {{ project_base_path }}/{{ project_name }}/nexus-{{ nexus.version }}
    - require:
        - file: {{ project_base_path }}/{{ project_name }}
{%-   else %}
    - unless: test -d {{ nexus.real_home }}
    - require:
        - file: {{ nexus.prefix }}
{%-   endif %}
        - file: {{ nexus.download_dir }}
{%- endif %}
```

creates in each run a "{{ nexus.download_dir }} not found" error when the folder didn't exists.
I had to fix it to use the cwd in the command itself:

```
unpack-nexus-tarball:
  cmd.run:
    - name: curl -L '{{ nexus.source_url }}' | tar xzC {{ nexus.download_dir }}
    - user: {{ project_name }}
    - onlyif: test -d {{ nexus.download_dir }}
{%- if pillar['project']['name'] != None %}
    - unless: test -d {{ project_base_path }}/{{ project_name }}/nexus-{{ nexus.version }}
    - require:
        - file: {{ project_base_path }}/{{ project_name }}
{%- else %}
    - unless: test -d {{ nexus.real_home }}
    - require:
        - file: {{ nexus.prefix }}
{%- endif %}
```
to get the state work without created tmp_dir / if no updates are available and its not created...
