### ISSUE TITLE
Exception when using Salt mine from pillar

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#11509]
```
$ salt 'apt-mirror' state.highstate
apt-mirror:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'apt-repo.eu-west-1' failed, render error:
Jinja error: 'master_uri'
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/salt/utils/templates.py", line 261, in render_jinja_tmpl
    output = jinja_env.from_string(tmplstr).render(**unicode_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/pymodules/python2.7/salt/modules/mine.py", line 182, in get
    auth = _auth()
  File "/usr/lib/pymodules/python2.7/salt/modules/mine.py", line 24, in _auth
    __context__['auth'] = salt.crypt.SAuth(__opts__)
  File "/usr/lib/pymodules/python2.7/salt/crypt.py", line 502, in __init__
    self.crypticle = self.__authenticate()
  File "/usr/lib/pymodules/python2.7/salt/crypt.py", line 514, in __authenticate
    self.opts.get('_safe_auth', True)
  File "/usr/lib/pymodules/python2.7/salt/crypt.py", line 345, in sign_in
    if self.opts['master_ip'] not in self.opts['master_uri']:
KeyError: 'master_uri'

; line 1

---
{% set ipaddrs = salt['mine.get']('apt-mirror', 'network.ipaddrs')[0] %}    <======================
{% if ipaddrs %}
apt-repo: http://{{ ipaddrs[0] }}
{% else %}
apt-repo: http://packages.somewhere.com
{% endif %}
[...]
---
```

This works:
```
$ salt 'apt-mirror' mine.get apt-mirror network.ipaddrs
apt-mirror:
    ----------
```
(no, I wasn't expecting any data, nor an exception)

**Comment by rikonor** [comment]
Was this fixed at some point? Running into it now and would love to have this functionality.

**Comment by bersace** [comment]
I second using mine in pillars. I tend to use only pillars in formulas. Pillar is easier to document. Using pillar-only formulas is simpler too. Then i put some logic in pillars like picking values from grains, mine, etc.

:+1: for mine in pillars ! :-)

**Comment by llevar** [comment]
+1 for mine in pillars.

**Comment by powellchristoph** [comment]
+1 for mine in pillars. Basically what @bersace said.

**Comment by DanyC97** [comment]
+1

**Comment by AusIV** [comment]
I've added the following to a custom execution module, allowing me to access the mine from pillars:

    def pillar_mine_get(tgt, fun):
        mine_string = __salt__["cmd.run"]("salt-run mine.get '%s' %s --out=json"
            %( tgt, fun))
        return json.loads(mine_string)

This only supports minion_id globbing for lookups, but that could be pretty easily adapted if you need other target types.

In my pillars, I can use:

    salt['my_module.pillar_mine_get']('host_glob', 'network.ip_addrs')

as a drop-in replacement for:

    salt['mine.get']('host_glob', 'network.ip_addrs')

I'm interested to know if anyone has a better work-around - preferably one that doesn't involve forking the salt runner as a separate process.

I'd also warn that you need to be sure you can trust the input for 'tgt' and 'fun', as it's not being sanitized and I suspect someone could convince it to do malicious things. Anything that can invoke pillar_mine_get could also invoke cmd.run, but if you can't trust the inputs, don't use this solution.

**Comment by bersace** [comment]
@AusIV Very nice. Thanks for this workaround !

**Comment by whiteinge** [comment]
@AusIV that is a good workaround.

In answer to your question about avoiding the shell-out process: the following should be possible once #26648 makes it into the next 2015.5 point-release and the impending 2015.8 release:

```jinja
{% set mine_data = salt['saltutil.runner']('mine.get', 'host_glob', 'network.ip_addrs') %}
```

It uses the old-ish but not well-known [saltutil.runner](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.runner) function. Unfortunately, prior to the above pull req, it shadowed the `fun` argument which the mine runner uses.

**Comment by genuss** [comment]
I tried to use something like this:
``__salt__["cmd.run"]("salt-call mine.get %s %s" (tgt, fun))``
but it was very unstable (was version 2014.7)

Does the solution with ``salt-run`` work as expected? I suppose, it must have the same issues like the one with ``salt-call``

**Comment by AusIV** [comment]
@genuss: salt-call is a minion command, salt-run is a master command. Pillars get evaluated on the master, so if your master isn't also a minion salt-call won't work. salt-run, on the other hand, should always be present on the master (but you won't be able to use that module on formulas that run on minions). 

Also, were you accounting for the fact that it's going to hand back a string, but it will be a serialized object? That's why I'm getting the output as json and parsing it.

**Comment by genuss** [comment]
It looks like you workaround works much better than mine! Thanks a lot.
And yes, I see why you getting out as json. But in 2014.7 it's not possible.

**Comment by jgmchan** [comment]
+1 It would be great if it was possible to use `mine.get` in pillars. I have a state which gets all its config data from pillars and one of the bits of data is IP addresses from other servers in my environment.

Without this I think I may need to kludge it so that it gets this particular data from the state and everything else from the pillars.

**Comment by whiteinge** [comment]
[Calling the mine runner as detailed in this comment](https://github.com/saltstack/salt/issues/11509#issuecomment-138980156) should be sufficient to close this issue out. Please test accordingly and update this issue if you encounter trouble.

2015.8 is due out shortly (likely this week) and the fix will be in 2015.5.6 as well.

We can update the docs to direct master-side operations (Pillar & Orchestrate) to the mine runner and minion-side operations to the mine execution module and I think this can finally be closed.

**Comment by JensRantil** [comment]
:clap: Thanks!

**Comment by bentwire** [comment]
@AusIV - I tried using your execution module example, but it isn't working.  When I try to gen the pillar it says it can't find the module.  No idea what I am doing wrong... The module is loaded on the minions fine, I see no errors in the minion logs and it shows it copying and loading the module...

**Comment by AusIV** [comment]
@bentwire: You need to have it set up in the salt master under extension_modules. See [here](https://docs.saltstack.com/en/latest/ref/configuration/master.html#extension-modules). It's different than execution modules that run on minions, and it's an area of documentation that seems pretty lacking. I think one of my co-workers figured it out from a blog post somewhere, and I just know about it from seeing it done in our code base.

I have configured my salt master with:

    extension_modules: /srv/modules

And the execution module is at `/srv/modules/modules/my_utils.py`.

**Comment by bentwire** [comment]
@AusIV - Awesome!  I will try this.  Thank you for the quick reply!

**Comment by babilen** [comment]
I really don't think that this is an acceptable solution as it forces users to fork formulas whenever they need to incorporate data from the mine. It is nice that it is easier to incorporate it this way, but it is far from a solution to the actual problem, namely that one cannot easily include dynamic data in the pillar as we conflate mine configuration and pillar rendering.

A step in the right direction would be the implementation of static pillars as discussed in https://github.com/saltstack/salt/issues/23910

**Comment by whiteinge** [comment]
Totally agree. Arguments to a mine call should not be hard-coded in a publically available formula. But since you cannot reference Pillar from within Pillar, there's no good way to package such a formula other than docs.

**Comment by bersace** [comment]
Here we reuse pillar in pillars with Jinja.

```yaml
{% import_yaml 'other/pillar.sls' as other -%}

formula:
  foo: 0
  bar: {{ other.other.bar }}
  baz: {{ salt['pillarmine.get']('func') }}
```

In order to get full settings out of pillar, we combine `defaults.get`, `load_yaml` and `grains.filter_by` to merge defaults and pillar.

```yaml
{% set defaults = salt['defaults.get']('formula') -%}

{% load_pillar as pillars -%}
foo: 128
baz: {{ salt['pillarmine.get']('func') }}
{% endload -%}
{% set pillars = salt['grains.filter_by']({
    'default': defaults,
}, merge=pillars) -%}

formula:
  {{ pillars|yaml(False)|indent(2) }}
```

See https://github.com/saltstack/salt/pull/26903

**Comment by whiteinge** [comment]
Ooh, nice addition.

**Comment by bogdanr** [comment]
@bersace Can you please explain this a little bit more?
I would like to use network.ip_addrs extracted from a certain minion from mine and I still can figure out how to do that.

**Comment by bersace** [comment]
Here is the `pillarmine` module. I put it on `extmods/modules` and declare `extmods` as `extension_modules` config.

```python
import logging
import yaml


logger = logging.getLogger(__name__)


def get(tgt, fun, tgt_type='glob'):
    cmd_run = __salt__['cmd.run']  # noqa
    cmd = "salt-run mine.get --out yaml '%s' %s tgt_type=%s" % (
        tgt, fun, tgt_type)
    logger.debug("Querying mine with %r", cmd)
    output = cmd_run(cmd)
    logger.debug("Got mine result %s", output)
    return yaml.load(output)
```

**Comment by bersace** [comment]
@bogdanr of course.

The goal is to feed formulas map.jinja with only namespaced pillars with pillar deduplication. No grains, no cross formula pillar reference, no mine.

So we want to have importable pillars containing defaults, regular pillars, mine and even grains logic. For this we use the power of jinja and salt modules to merge values in order and render the final values as yaml.

Note that modules in pillars are executed on master side. So you don't have `_modules` available.

```yaml
# First, loads defaults from formula in jinja. This load `base:formula/defaults.yml` from `file_roots`, not pillar_roots.
{% set defaults = salt['defaults.get']('formula') -%}

# Then, loads regular pillar, namespaceless in jinja
{% load_pillar as pillars -%}
foo: 128
# You can use the hack in pillarmine module to fetch mine values from pillar.
baz: {{ salt['pillarmine.get']('func') }}
{% endload -%}
# Now, merge defaults and pillars to get final pillar
{% set pillars = salt['grains.filter_by']({
    'default': defaults,
}, merge=pillars) -%}

# Finally, render pillar namespaced.
formula:
  {{ pillars|yaml(False)|indent(2) }}
```

You can now reuse pillars in another pillar in these way :

```yaml
# Import the yaml in jinja. You know that with the preceding logic, you have final values, including defaults.
{% import_yaml 'formula.sls' as formulap -%}
{% set formula = formulap.formula -%}

bar:
  # Reuse a value just like you do in a formula
  name: {{ formula.foo }}
```

You can also directly import jinja variables, but that's a new API you have to respect, and it does not work on all pillars.

```yaml
{% from 'formula.sls' import pillars as formula -%}

bar:
  name: {{ formula.foo }}
```
