### ISSUE TITLE
git.latest should set tracking branch in necessary

### ISSUE THREAD

**Issue by herzi** [saltstack/salt#11611]
When migrating a setup from one system to the other, I was gradually building up the salt state for the current system in order to replicate it (using the state) on the other.

When migrating a git repository (manually created), I did not set up a tracking branch, so I got this error:

```
          ID: /path/to/checkout
    Function: git.latest
        Name: git@git.example.com:/path/to/upstream
      Result: False
     Comment: There is no tracking information for the current branch.
              Please specify which branch you want to merge with.
              See git-pull(1) for details
              
                  git pull <remote> <branch>
              
              If you wish to set tracking information for this branch you can do so with:
              
                  git branch --set-upstream master origin/<branch>
     Changes:   
```

As the state.sls looks like this:

```
/path/to/checkout:
  git.latest:
    - name: git@git.example.com:/path/to/upstream
    - rev: master
    - target: /srv/icecast/scripts
    - user: icecast2
```

Salt should have enough information to set up the tracking information on its own (using `<remote-name>/<branch-name>`, which would be `origin/master` here).
