### ISSUE TITLE
Feature request: be able to reuse id

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#11714]
This an annoyance driven issue. :) I have a state like this:

```
/bin/myfile.sh:
  file.managed:
    - source: salt://myfile.sh
  cron.present:
    - hour: 0
    - minute: 0
    - require:
      - file: /bin/myfile.sh
```

Since it's such a common case to have dependencies between states with the same ID (file.managed/cmd.wait, file.managed/service.watch etc.) I hereby propose a shortcut so that I don't have to enter the same ID every time:

```
/bin/myfile.sh:
  file.managed:
    - source: salt://myfile.sh
  cron.present:
    - hour: 0
    - minute: 0
    - require:
      - file
```

I am [by no means a YAML expert](https://github.com/saltstack/salt/issues/11227#issue-29423730). Is this doable?
