### ISSUE TITLE
master config from GitFS

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#11724]
In addition to #570 I'd like to be able to provide the master config via GitFS.

Right now, I configure the master through various files in `/etc/salt/master.d` without touching `/etc/salt/master` itself at all.

The next evolutionary level would be to just keep all files from `master.d` in a git repository instead which is then being constantly refreshed just as `gitfs_remotes` for the fileserver are, so all that would be needed in `/etc/master/master.d` is a single config file with something analogue to the fileserver configuration like this:

``` YAML
config_backend:
  - master.d
  - git
config_gitfs_remotes:
   saltmaster@git-server.domain.tld:repo-001.git: master
   saltmaster@git-server.domain.tld:repo-002.git: integration
```
