### ISSUE TITLE
Add watch to mount state module

### ISSUE THREAD

**Issue by bplotnick** [saltstack/salt#11775]
The mount state module should have a mod_watch method that simply remounts when called.

Typical example would be remounting an nfs mount when the host IP changes:

```
/mnt/foo:
  mount.mounted:
    - device: foohost:/path/to/foo
    - fstype: nfs
    - watch:
      - file: /etc/hosts

/etc/hosts:
  file.managed:
    - source: salt://hosts
```
