### ISSUE TITLE
Nested Grain-Support for grains.present / grains.absent

### ISSUE THREAD

**Issue by gpkvt** [saltstack/salt#11870]
It would be really nice if grains.present (and absent of course) could get support for nested grains.

Example:

```
icinga:
  Apache SSL:
    command: check_https
    params: -H localhost -p 443 -S
```

Thanks to @whiteinge I know that the following workaround is possible but a more native function would be a lot nicer. Just attaching it to give a better understanding of the suggested feature.

```
{% if not 'icinga' in grains %}
set_icinga_grain:
  module:
    - run
    - name: grains.setval
    - key: icinga
    - val:
        Apache SSL:
          command: check_https
          params: -H localhost -p 443 -S
{% endif %} 
```
