### ISSUE TITLE
confusing warning message "'use' is an invalid keyword argument ..." when running state.sls

### ISSUE THREAD

**Issue by ranl** [saltstack/salt#11960]
as a continue to this [thread](https://github.com/saltstack/salt/pull/11958) 

when I"m applying the state below
```
application.wait.4.manager:
  tomcat.wait:
    - timeout: 600
    - url: http://localhost:8080/manager

wait.application.restart.tomcat.after.deploy:
  tomcat.wait:
    - use:
      - tomcat: application.wait.4.manager
```
I'm getting a response back from the minion
```
                  tomcat_|-wait.application.restart.tomcat.after.deploy_|-wait.application.restart.tomcat.after.deploy_|-wait:
                      ----------
                      __run_num__:
                          66
                      changes:
                          ----------
                      comment:
                          tomcat manager is ready
                      name:
                          wait.application.restart.tomcat.after.deploy
                      result:
                          True
                      warnings:
                          - 'use' is an invalid keyword argument for 'tomcat.wait'. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs. Your approach will work until Salt Lithium is out. Please update your state files.
```
`use` indeed is not a valid argument of `tomcat.wait` but it is used as a requisite so the error message here is not relevant...

a similar issue occurs when applying the below state
```
postfix.config:
  file.managed:
    - name: /etc/postfix/master
    - source: salt://somewhere..

postfix:
  service.running:
    - enable: True
    - require:
      - pkg: mailpkgs
    - watch:
      - file: postfix.config
```
when the `postfix.config` changes it triggers the `postfix` `service.mod_watch` function
but the state returns the error message below
```
                  service_|-postfix_|-postfix_|-running:
                      ----------
                      __run_num__:
                          29
                      changes:
                          ----------
                          postfix:
                              True
                      comment:
                          Service restarted
                      name:
                          postfix
                      result:
                          True
                      warnings:
                          - 'enable' is an invalid keyword argument for 'service.mod_watch'. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs. Your approach will work until Salt Lithium is out. Please update your state files.
```

@s0undt3ch, you can now recreate this in a test :smile:
