### ISSUE TITLE
Stage pkgrepo.managed is unavailable on SLES system

### ISSUE THREAD

**Issue by hhenkel** [saltstack/salt#11978]
```
ID: SLE_11_SPx
Function: pkgrepo.managed
Result: False
Comment: State pkgrepo.managed found in sls roles.common.repositories.sles_11 is unavailable
Changes:   
```

```
# salt --version
salt 2014.1.0
```

sles11.sls:

```
SLE_11_SPx:
  pkgrepo.managed:
    - name: SLE_11_SPx
    - humanname: Internal - SP independent packages.
    - enabled: 1
    - autorefresh: 1
    - baseurl: http://rpm.example.com/SLE_11_SPx/
    - type: rpm-md
    - keeppackages: 0
    - gpgcheck: 0
```
