### ISSUE TITLE
[state.dockerio] docker.run TypeError: run() argument after ** must be a mapping, not str

### ISSUE THREAD

**Issue by MarkusMuellerAU** [saltstack/salt#12003]
Getting the following error running state.highstate
```
----------
          ID: /reload.sh
    Function: docker.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1371, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/dockerio.py", line 548, in run
                  return drun(**cmd_kwargs)
              TypeError: run() argument after ** must be a mapping, not str
     Changes:
```
I am trying to run a command inside a container the following way:

```
/reload.sh:
    docker.run:
        - cid: f56154a814f1ecd6961b6314c589a5765e15ed8e85567be399982d1b3efa324c
        - watch:
          - file: /config.cfg
```

The documentation http://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerio.html suggest doing it the following way:
```
/finish-install.sh:
    docker.run:
        - container: mysuperdocker
        - unless: grep -q something /var/log/foo
        - docker_unless: grep -q done /install_log
```
Whereas the syntax at http://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerio.html#salt.states.dockerio.run only mentions a cid, not a container argument.

**Comment by munhitsu** [comment]
@rallytime problem is back

salt 2014.7.2
docker-py 1.0.0
docker 1.4.1

Currently run should have been implemented using docker exec


Plus webpage documentation is misleading saying that one should go for:
```yaml
/finish-install.sh:
  docker.run:
    - container: mysuperdocker
```

while is should have been (cid)
```yaml
/finish-install.sh:
  docker.run:
    - cid: mysuperdocker
```

**Comment by rallytime** [comment]
Thanks for letting us know. I've re-opened the issue. Thanks!

**Comment by tkent-xetus** [comment]
+1 I'm also running into the `NotImplementedError` with 2014.7.4. In case anybody else happens across this issue, a fairly straightforward alternative is something like:

```
mypostsetupcmd:
  require:
    - docker: some-docker-running-state
  cmd.wait:
    - name: >
      docker exec {{ container_name }}
      your commands here…

    - watch: 
      - docker: some-docker-installed-state 
```
