### ISSUE TITLE
Question: Docker and Docker Registries Integration (States and Modules)

### ISSUE THREAD

**Issue by ekristen** [saltstack/salt#12056]
How is the integration with the docker states and the docker registries from pillars suppose to work?

I have a pillar defined for a registry, but when I try and use the docker.pulled state, it gets access denied. 

The documentation is not clear, perhaps they aren't meant to integrate at this point?

**Comment by krak3n** [comment]
IMO the pillar registries declaration is a little broken. Using the registry url as the key means you can't store your credentials in etcd for example, since each `/` in the url would be treated as sub directory in etcd.

Really docker registries should be written like this:

``` yaml
docker-registries:
  a-label:
    url: https://index.docker.io/v1/
    email: foo@bar.com
    username: bar
    password: foo
  b-label:
    url: https://index.foo.com/
    email: foo@bar.com
    username: bar
    password: foo
# old style should also still work to avoid breaking existing configurations
  https://index.bar.com/:
    email: foo@bar.com
    username: bar
    password: foo
```

We could implement some backwards compatibility where is the `url` key is not present we can assume the parent key is the registry url, else we use the `url` key as the registry url and perform the normal login.

This would provide greatest flexibility for everyone and would allow me to store my docker credentials in `etcd` :stuck_out_tongue: 

@basepi if you guys agree I'm happy to make a separate issue for this and contribute the required changes.
