### ISSUE TITLE
ENH: Read Pillar files into OrderedDict to preserve source order

### ISSUE THREAD

**Issue by westurner** [saltstack/salt#12161]
It would be great if .iteritems of pillar data read out in source order.

Example:

**Pillar Input**: https://github.com/saltstack-formulas/openssh-formula/blob/master/pillar.example

```
sshd_config:
  Port: 22
  Protocol: 2
  HostKey:
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_dsa_key
    - /etc/ssh/ssh_host_ecdsa_key
  UsePrivilegeSeparation: yes
  KeyRegenerationInterval: 3600
  ServerKeyBits: 768
  SyslogFacility: AUTH
  LogLevel: INFO
  LoginGraceTime: 120
  PermitRootLogin: yes
  StrictModes: yes
  RSAAuthentication: yes
  PubkeyAuthentication: yes
  IgnoreRhosts: yes
  RhostsRSAAuthentication: no
  HostbasedAuthentication: no
  PermitEmptyPasswords: no
  ChallengeResponseAuthentication: no
  X11Forwarding: yes
  X11DisplayOffset: 10
  PrintMotd: no
  PrintLastLog: yes
  TCPKeepAlive: yes
  AcceptEnv: "LANG LC_*"
  Subsystem: "sftp /usr/lib/openssh/sftp-server"
  UsePAM: yes
```

**Template**: https://github.com/saltstack-formulas/openssh-formula/blob/master/openssh/files/sshd_config

```
{% set sshd_config = pillar.get('sshd_config', {}) %}
# {...}
{% for keyword, argument in sshd_config.iteritems() %}
    {%- if argument is sameas true %}
{{ keyword }} yes
    {%- elif argument is sameas false %}
{{ keyword }} no
    {%- elif argument is string or argument is number %}
{{ keyword }} {{ argument }}
    {%- else %}
        {%- for item in argument %}
{{ keyword }} {{ item }}
        {%- endfor %}
    {%- endif %}
{%- endfor %}
# {...}
```

**Output**: /etc/ssh/sshd_config

```
StrictModes yes
IgnoreRhosts yes
PermitEmptyPasswords no
PermitRootLogin no
UseDNS no
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
LogLevel INFO
X11DisplayOffset 10
AcceptEnv LANG LC_*
TCPKeepAlive yes
X11Forwarding yes
KeyRegenerationInterval 3600
Subsystem sftp /usr/lib/openssh/sftp-server
ServerKeyBits 768
UsePrivilegeSeparation yes
SyslogFacility AUTH
RhostsRSAAuthentication no
PrintLastLog yes
ChallengeResponseAuthentication no
LoginGraceTime 120
PubkeyAuthentication yes
UsePAM yes
Protocol 2
PrintMotd no
HostbasedAuthentication no
RSAAuthentication yes
Port 22
```

**Comment by aboe76** [comment]
I got almost the same kind of issues with my own formula of h2o web server:
where file.serialize is using dataset_pillar which in turn uses pillar.get

init.sls:
```yaml
{% from "h2o/map.jinja" import h2o with context -%}

h2o:
  pkg.installed:
    - name: {{ h2o.pkg }}
  service.running:
    - name: {{ h2o.service }}
  file.serialize:
    - name: /etc/h2o/{{ h2o.config_file }}
    - user: root
    - group: root
    - mode: 644
    - formatter: yaml
    - dataset_pillar: h2o:config
    - watch_in:
      - service: h2o
```
pillar: h2o.sls
```yaml
h2o:
  lookup:
    pkg: h2o-git
  config:
    listen: 8080
    
    user: http
    
    access-log: /var/log/h2o-access.log

    hosts:
      "127.0.0.1.xip.io:8080":
        paths:
          /:
            file.dir: /srv/http
            file.dirlisting: 'ON'
            expires: 1 day
```

rendered config: /etc/h2o/h2o.conf
```yaml
access-log: /var/log/h2o-access.log
hosts:
  127.0.0.1.xip.io:8080:
    paths:
      /:
        expires: 1 day
        file.dir: /srv/http
        file.dirlisting: 'ON'
listen: 8080
user: http
```

but it should be:/etc/h2o/h2o.conf
```yaml
listen: 8080
    
    user: http
    
    access-log: /var/log/h2o-access.log

    hosts:
      "127.0.0.1.xip.io:8080":
        paths:
          /:
            file.dir: /srv/http
            file.dirlisting: 'ON'
            expires: 1 day
```
