### ISSUE TITLE
Formula dependency management

### ISSUE THREAD

**Issue by chrismoos** [saltstack/salt#12179]
I think there should be a standard way to manage formula dependencies. It is very natural for a state to be composed of other states but when using third party formula there is no easy way to manage the dependencies, versions, etc,.

A popular tool for Chef is [Berkshelf](http://berkshelf.com/). You put a file in your cookbook root (or _state tree root_ in Salt's case) like this:

```
source "https://api.berkshelf.com"

metadata

cookbook "mysql"
cookbook "nginx", "~> 2.6"
```

There is a CLI command so you can fetch and install all of the dependencies, for example.

I propose we do the same thing for Salt's formula:

_Saltfile_ - This will contain the dependencies, sources, etc,.
_Saltfile.lock_ - This will contain all of the active/installed dependencies and their versions.

There will be a tool that will fetch and install the dependences, just like the **berkshelf** command.

I think that having this feature is really important especially as your state tree gets more advanced and you start pulling in third party formula.

Example _Saltfile_:

``` yaml
- sources:
    - https://formula.mycompany.com
    - https://formula.saltstack.org
- dependencies:
    nginx:
    redis:
        version: '>= 1.0.5'
    ntp:
        git: 'https://github.com/saltstack-formulas/ntp-formula.git'
```
