### ISSUE TITLE
iptables: Rules being inserted multiple times

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#12455]
The iptables configuration sometimes adds in the same rules multiple times. In one run where 10 unique rules are being added it generally happens that it ends up with 13-14 rules. Re-running highstate sometimes randomly inserts another rule (blue rather than green in highstate result). 

It appears that the comparison existing is not working as it should. Example rule:
```
      iptables_ssh_allow_192.168.0.0/24:
        iptables.append:
          - table: filter
          - chain: INPUT
          - jump: ACCEPT
          - source: 192.168.0.0/24
          - dport: ssh
          - proto: tcp
          - save: True
```
