### ISSUE TITLE
Issue when including sls file as requirement  [BUG, Minor]

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#12476]
I noticed this a few days ago.  If I attempt include anything other than an init sls requirmement in a state, I must put the full path to the sls I'm including.

For example:

supervisor/init.sls:

```
include:
  - supervisor.common
```

supervisor/common.sls

```
supervisor:
  pkg:
    - installed
  service:
    - running
    - require:
      - pkg: supervisor
      - cmd: /etc/init.d/supervisor_absent
      - cmd: /etc/init.d/supervisor_symlink
      - cmd: /tmp/kill_supervisord.sh
      - file: /etc/init/supervisor.conf
    - watch:
      - pkg: supervisor
      - file: /etc/init/supervisor.conf
...
..
more stuff
```

And then if I attempt to include supervisor as an sls requirement:

deploy/my_app.sls

```
include:
    - supervisor
    - rvm.common
    - git.deploy_keys

foo:
  supervisord.running:
    - name: "foo"
    - runas: root
    - update: True
    - restart: True
    - require:
      - sls: supervisor    <---- WONT WORK
       - sls: supervisor.common <--- WILL WORK
```

I should be able to just include `sls: supervisor` and have it follow the includes in my `supervisor/init.sls` file.  Probably a minor bug, but worth bubbling up.
