### ISSUE TITLE
Unable to spin up Windows based image in Azure

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#12487]
First of all, it's a bit unclear if this is a bug or this is a feature request for me, I'm filing it as a bug right now.

I'm trying to spin up a Windows Server 2012 R2 based minion in Azure following these instructions:
http://docs.saltstack.com/en/latest/topics/cloud/azure.html

According to the documentation it should be possible to spin up Windows Images
http://docs.saltstack.com/en/latest/topics/cloud/windows.html

But trying to spin up one in Azure gives the error:
```
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>Disktype Windows cannot be used with LinuxProvisioningConfigurationSet</Message></Error>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/msazure.py", line 472, in create
```
Here is my /etc/salt/cloud.profiles

```
win2012r2:
  provider: andre-azure-config
  image: 'ad072bd3082149369c449ba5832401ae__Windows-Server-RDSHwO13P-on-Windows-Server-2012-R2-20140421-1748'
  size: ExtraSmall
  location: 'North Europe'
  slot: staging
  media_link: 'http://myblob.blob.core.windows.net/vhds'
  win_installer: /root/Salt-Minion-2014.1.3-1-AMD64-Setup.exe
  win_username: Administrator
  win_password: mysecret
```

From what I can see the following line is hardcoded to ```azure.servicemanagement.LinuxConfigurationSet```
https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/msazure.py#L437

Shouldn't this be calling ```azure.servicemanagement.WindowsConfigurationSet``` depending on image type?

My salt --versions-report gives
```
           Salt: 2014.1.3
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
```
