### ISSUE TITLE
require sls fails when required state has single statement that shares state name.

### ISSUE THREAD

**Issue by renecunningham** [saltstack/salt#12480]
Not sure if this has already been reported though could be related to #10852 & #12476.

foo/init.sls
```
include:
  - bar

foo:
  cmd.run:
    - name: echo foo
    - require:
      - sls: bar
```
bar/init.sls
```
bar:
  cmd.run:
    - name: echo bar
```
```
# salt-call state.sls foo
...
----------
          ID: foo
    Function: cmd.run
        Name: echo foo
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     sls: bar
     Changes:
```
updating bar/init.sls
```
bar:
  cmd.run:
    - name: echo bar

/tmp/.bar:
  file.absent
```
```
# salt-call state.sls foo
...
----------
          ID: foo
    Function: cmd.run
        Name: echo foo
      Result: True
     Comment: Command "echo foo" run
     Changes:
              ----------
              pid:
                  20271
              retcode:
                  0
              stderr:

              stdout:
                  foo
```
