### ISSUE TITLE
Salt scheduler via minion config file

### ISSUE THREAD

**Issue by omarmohsen** [saltstack/salt#12630]
I am attempting to use the scheduler via the minion config file, according to /var/log/salt/minion, I was able to execute the last state in the file every 5 minutes and the rest of the states are being ignored. I appreciate your help

```
/etc/salt/minion.d/schedule_minute.conf:
schedule:
  state1:
    function: state.sls
    minutes: 5
    args:
      - state1
    kwargs:
      test: True

schedule:
  state2:
    function: state.sls
    minutes: 5
    args:
      - state2
    kwargs:
      test: True
schedule:
  state3:
    function: state.sls
    minutes: 5
    args:
       - state3
    kwargs:
      test: True
```

Regards
