### ISSUE TITLE
Feature: Allow usergroup matching in client_acl

### ISSUE THREAD

**Issue by TamCore** [saltstack/salt#12652]
Hi,

I think it could be very useful if it would be possible to use usergroups in client_acl.

For example: Instead of

```
client_acl:
  dev1:
    - 'sys.my.net':
      - some.perms
  dev2:
    - 'sys.my.net':
      - some.perms
  dev3:
    - 'sys.my.net':
      - some.perms
```

we could use 

```
client_acl:
  developers%:
    - 'sys.my.net':
      - some.perms
```

Usage of 'groupname%' is already possible in external_auth.

Regards
