### ISSUE TITLE
file.managed doesn't work with ldap users

### ISSUE THREAD

**Issue by samueletonon** [saltstack/salt#12803]
scenario:
user samu comes from an ldap:

```
$id samu
uid=10000(samu) gid=10000(utenti)
```

let's have this testing.sls file:

```
/home/samu/testing:
  file.managed:
    - source: salt://testing
    - mode: 640
    - user: samu
    - group: utenti
```

and let's run it, it will give you the following error:

```
$salt '*' state.highstate testing.sls
----------
    State: - file
    Name:      /home/samu/testing
    Function:  managed
        Result:    False
        Comment:   User samu is not available Group utenti is not available
        Changes:
```
