### ISSUE TITLE
[feature][file.managed] method to verify config files

### ISSUE THREAD

**Issue by mgwilliams** [saltstack/salt#12818]
I propose adding a ``check_cmd`` parameter to file.managed, to run a check on a file before it is moved into place.

E.g.,

```yaml
/etch/ssh/sshd_config
  file:
    - managed
    - template: jinja
    - source: salt://sshd/files/sshd_config.jinja
    - check_cmd: /usr/sbin/sshd -t -f
```
This would only update the file if ``sshd -t -f /path/to/tmp/file`` exits with no error.

Other configs that could benefit from this include visudo (``visudo -c -f``), bind9 (``named-checkconf`` and ``named-checkzone``), etc.
