### ISSUE TITLE
Apache2 reload doesn't seem to work

### ISSUE THREAD

**Issue by stevage** [saltstack/salt#12880]
My state, running on Ubuntu Quantal:

```
apache2:
  service:
    - running
    - reload: True
```

generates this output:

```
          ID: apache2
    Function: service.running
      Result: True
     Comment: The service apache2 is already running
     Changes:   
```

(And fails to reload the server.)

It's not a question of the init script not supporting reload, as this works just fine:

```
reload_apache:
  cmd.run:
    - name: "service apache2 reload"
```
