### ISSUE TITLE
Firewall module not available in windows

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#13044]
I'm trying to open ports in the windows firewall, I've tried both:
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_firewall.html#module-salt.states.win_firewall

with the following config:

```
elasticsearch.install:
  firewall.add_rule:
    - name: "Elasticsearch"
    - localport: '8081,9300-9310' # 10 ports for 10 nodes, use pillar data here later on
    - protocol: 'tcp'
    - action: 'allow'
    - dir: 'in'
```

Result is:
`Comment: State firewall.add_rule found in sls elasticsearch.install is unavailable`

and with the command:
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_firewall.html

```
salt rs-sm1 firewall.add_rule "Elasticsearch" "tcp" "8081,9300-9310"
```

But here I get the error: `'firewall.add_rule' is not available.`

The minion is running Windows 2012 x64 server in Azure and the versions report is:

```
root@saltmaster:/srv# salt --versions-report
           Salt: 2014.1.4
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
root@saltmaster:/srv# salt rs-sm1 test.versions_report
rs-sm1:
               Salt: 2014.1.4
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
             PyYAML: 3.11
              PyZMQ: 14.1.1
                ZMQ: 4.0.4
root@saltmaster:/srv#
```

**Comment by sureshram** [comment]
I am having similar issue on windows running salt in masterless mode.

add_rule works fine for me but the delete_rule doesn't work

C:\salt>salt-call firewall.delete_rule "test" "8080" "tcp"
Function firewall.delete_rule is not available

Here's my version,

           Salt: 2014.7.2
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed

Any suggestions?

**Comment by t0rrant** [comment]
Hi guys,

lately I've noticed that every single custom module/state_module I defined stopped being loaded.

Although the __virtual__ functions from each return a string with the module's name, there seems to be no error report on the "missing" __virtualname__.

After reading this issues' comments I have to ask, @s0undt3ch @basepi  why is this __virtualname__ behaviour required, as it breaks previous working modules?

You can see [here](https://github.com/saltstack/salt/blob/develop/salt/loader.py#L1139-L1173) the code that tries to load the module according to __virtualname__, although it also checks for the return value of the __virtual__ function of the module.

Cheers

**Comment by s0undt3ch** [comment]
We've made `__virtualname__` a requirement in order to proper render doc's using the virtual module name(this is still something to improve on docs).
There was some change on the `__virtual__` handling, but I need to see in which branch that change was made. I'll get back.

**Comment by jfindlay** [comment]
I have successfully used the `win_firewall.py` module many times.  Can anyone confirm that they are still having problems getting the windows firewall module to work with the latest salt release (2015.5.3)?

**Comment by tschaffer-smart** [comment]
As of today, using latest master/minion, I am getting the same error.  If I run salt-call firewall.add_rule directly on the windows box, or directly from the master it works fine.  But it will fail if pushed via the sls with the same error mentioned above.

Here's my snippet:
ssh_firewall:
  firewall.add_rule:
    - name: sshd
    - localport: 22

Resulting error:
Comment: State 'firewall.add_rule' was not found in SLS 'servers.smex-win'
Reason: 'firewall.add_rule' is not available.

**Comment by alkivi-sas** [comment]
Same issue here. Fresh install on 2012r2

```
C:\Windows\system32>c:\salt\salt-call.bat firewall.get_config
'firewall.get_config' is not available.

C:\Windows\system32>c:\salt\salt-call.bat firewall.get_config
'firewall.get_config' is not available.

C:\Windows\system32>c:\salt\salt-call.bat win_firewall.get_config
'win_firewall.get_config' is not available.

```

Minion
```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.150
0 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 2012ServerR2
         system: 2012ServerR2 6.3.9600  Multiprocessor Free
```
```

salt-master --versions-report
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2
```
