### ISSUE TITLE
environ.set is not working on Windows

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#13048]
When calling environ.set on a windows machine (Windows Server 2012 x64)  like this:

```
javasdk.setjavahome:
  # for minion process
  environ.set: 
    - name: JAVA_HOME
    - value: 'C:\Program Files\Java\jdk1.7.0_55'
    - update_minion: True
```

the error 

```
[ERROR   ] State environ.set found in sls java.sdk is unavailable
```

is reported on the minion.

I can set the environment variable for the system using **setx** (see below) and it will persist, but it's not loaded into the current minion process.

```
# set javahome
javasdk.setjavahome:
  cmd.run:
    - name: 'setx JAVA_HOME "C:\Program Files\Java\jdk1.7.0_55" /m'
  require:
    - pkg: javasdk
```

Versions report here:

```
root@saltmaster:/srv# salt --versions-report
           Salt: 2014.1.4
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
root@saltmaster:/srv# salt rs-sm1 test.versions_report
rs-sm1:
               Salt: 2014.1.4
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
             PyYAML: 3.11
              PyZMQ: 14.1.1
                ZMQ: 4.0.4
root@saltmaster:/srv#
```

**Comment by hashtonmartyn** [comment]
I'm seeing something similar to @myg0v with version salt-master 2014.7.5 (Helium) but for me the environ.setenv function doesn't seem to do anything at all. I can't find the key/value it's setting anywhere in the registry.

Command and associated output:
hashtonmartyn@shitserver:~$ sudo salt '*' state.highstate -l all
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: shitserver
[DEBUG   ] Missing configuration file: ~/.saltrc
[TRACE   ] loading log_handlers in ['/var/cache/salt/extmods/log_handlers', '/usr/lib/python2.7/dist-packages/salt/log/handlers']
[TRACE   ] Skipping /var/cache/salt/extmods/log_handlers, it is not a directory
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: shitserver
[DEBUG   ] Missing configuration file: ~/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[TRACE   ] func get_cli_event_returns()
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] get_iter_returns for jid 20150429224225081220 sent to set(['desktop']) will timeout at 22:42:30.084058
[DEBUG   ] jid 20150429224225081220 return from desktop
[TRACE   ] loading output in ['/var/cache/salt/extmods/output', '/usr/lib/python2.7/dist-packages/salt/output']
[TRACE   ] Skipping /var/cache/salt/extmods/output, it is not a directory
[TRACE   ] Loaded no_out as virtual quiet
[TRACE   ] Added quiet.output to output
[TRACE   ] Loaded yaml_out as virtual yaml
[TRACE   ] Added yaml.OrderedDumper to output
[TRACE   ] Added yaml.output to output
[TRACE   ] Added txt.output to output
[TRACE   ] Loaded json_out as virtual json
[TRACE   ] Added json.output to output
[TRACE   ] Added nested.NestDisplay to output
[TRACE   ] Added nested.Number to output
[TRACE   ] Added nested.get_colors to output
[TRACE   ] Added nested.output to output
[TRACE   ] Added nested.sdecode to output
[TRACE   ] Added virt_query.output to output
[TRACE   ] Added raw.output to output
[TRACE   ] Added compact.output to output
[TRACE   ] Added grains.output to output
[TRACE   ] Added highstate.output to output
[TRACE   ] Loaded pprint_out as virtual pprint
[TRACE   ] Added pprint.output to output
[TRACE   ] Added newline_values_only.output to output
[TRACE   ] Added overstatestage.output to output
[TRACE   ] Added key.output to output
[TRACE   ] Added no_return.NestDisplay to output
[TRACE   ] Added no_return.output to output
[TRACE   ] loading output in ['/var/cache/salt/extmods/output', '/usr/lib/python2.7/dist-packages/salt/output']
[TRACE   ] Skipping /var/cache/salt/extmods/output, it is not a directory
[TRACE   ] Loaded no_out as virtual quiet
[TRACE   ] Added quiet.output to output
[TRACE   ] Loaded yaml_out as virtual yaml
[TRACE   ] Added yaml.OrderedDumper to output
[TRACE   ] Added yaml.output to output
[TRACE   ] Added txt.output to output
[TRACE   ] Loaded json_out as virtual json
[TRACE   ] Added json.output to output
[TRACE   ] Added nested.NestDisplay to output
[TRACE   ] Added nested.Number to output
[TRACE   ] Added nested.get_colors to output
[TRACE   ] Added nested.output to output
[TRACE   ] Added nested.sdecode to output
[TRACE   ] Added virt_query.output to output
[TRACE   ] Added raw.output to output
[TRACE   ] Added compact.output to output
[TRACE   ] Added grains.output to output
[TRACE   ] Added highstate.output to output
[TRACE   ] Loaded pprint_out as virtual pprint
[TRACE   ] Added pprint.output to output
[TRACE   ] Added newline_values_only.output to output
[TRACE   ] Added overstatestage.output to output
[TRACE   ] Added key.output to output
[TRACE   ] Added no_return.NestDisplay to output
[TRACE   ] Added no_return.output to output
[TRACE   ] data = {'desktop': {'environ_|-environment_variables_|-foo_|-setenv': {'comment': 'Environ values were set', 'name': 'foo', 'start_time': '22:42:32.194000', 'result': True, 'duration': u'28.0 ms', '__run_num__': 0, 'changes': {'foo': 'bar'}}}}
desktop:
----------
          ID: environment_variables
    Function: environ.setenv
        Name: foo
      Result: True
     Comment: Environ values were set
     Started: 22:42:32.194000
    Duration: 28.0 ms
     Changes:
              ----------
              foo:
                  bar

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
[DEBUG   ] jid 20150429224225081220 found all minions set(['desktop'])


salt-master versions:
Salt: 2014.7.5
Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
Jinja2: 2.7.2
M2Crypto: 0.21.1
msgpack-python: 0.3.0
msgpack-pure: Not Installed
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.0.1
RAET: Not Installed
ZMQ: 4.0.4
Mako: 0.9.1
Debian source package: 2014.7.5+ds-1ubuntu1

salt-minion-versions:
Salt: 2014.7.5
Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
Jinja2: 2.7.3
M2Crypto: 0.21.1
msgpack-python: 0.4.5
msgpack-pure: Not Installed
pycrypto: 2.6
libnacl: Not Installed
PyYAML: 3.11
ioflo: Not Installed
PyZMQ: 14.5.0
RAET: Not Installed
ZMQ: 4.0.5
Mako: Not Installed

**Comment by adamsewell** [comment]
I'm seeing the same thing now, even on 2015.8.3. It appears that Salt thinks it's set but if I test in on the machine, it doesn't sho.

**Comment by rterbush** [comment]
Confirming that this does not work in 2015.8.5 and that the cmd.run is a workaround.

**Comment by porunov** [comment]
It also doesn't work on CentOS 7.3 with salt 2016.11.3

Here is my state:

```
my-env-var:
  environ.setenv:
    - name: MY_ENV_VAR
    - value: bar
    - update_minion: True
```

Here is my output:
```
----------
          ID: my-env-var
    Function: environ.setenv
        Name: MY_ENV_VAR
      Result: True
     Comment: Environ values were set
     Started: 15:38:46.595877
    Duration: 1.202 ms
     Changes:   
              ----------                                                                                                             
              MY_ENV_VAR:
                  bar

```
But `echo $MY_ENV_VAR` shows nothing
