### ISSUE TITLE
Super-targeting

### ISSUE THREAD

**Issue by giannello** [saltstack/salt#13081]
My infrastructure is composed by different environments (production, staging, qa, testing and development), and each application could be deployed more than once in different environments - mostly for testing purposes.
To achieve this, the minion configuration for each machine contains the following grains:

``` yaml
application: shop
application_environment: testing
application_uuid: <random UUID>
roles:
  - frontend
  - backend
  - database
  - queue
```

This allows us to define different "instances" of the same application and keep them separated.

The top.sls file contains the following configuration

``` yaml
base:
  'role:frontend':
    - target: grains
    - application.frontend
    - application.backend
    - application.database
    - application.queue
```

This provides a base configuration for the machines, so that every needed component is installed, configured and ready to be activated.
The final step consists in an orchestrate task:

``` yaml
init_db:
  salt.function:
    - name: cmd.run
    - tgt: 'role:database'
    - tgt_type: grains
    - arg: '/srv/application/init_db.sh'

run_tests:
  salt.function:
    - name: cmd.run
    - tgt: 'role:frontend'
    - tgt_type: grains
    - arg: '/srv/application/run_tests.sh'
```

This allows us to have a "deploy script" that leverages the power of salt to deploy our application to a specific instance.

The biggest problem is that we have to create a new orchestrate sls for each new testing machine, and add the application_uuid grain to the tgt argument of each function, forcing us to have a lot of duplicated code and making the maintenance extremely hard, boring and not scriptable.

It would be nice to have a command line option for salt that accepts a target, like in the current implementation, and merges the target with _every_ other target specified by _any_ formula or sls executed.
This way it could be possible to execute

``` bash
salt-run state.orchestrate orchestration.deploy_application -U 'G@application_uuid:<UUID>'
```

and make sure that all the orchestrate steps will be executed only on the minions matching "role:frontend" AND "application_uuid:<UUID>".

This could make automated tests using any CI system a breeze, without the risk to accidentally execute the tasks on a wrong target environment.

For the original email about this issue, read https://groups.google.com/forum/#!topic/salt-users/RjkEkr3hJbw
