### ISSUE TITLE
npm state module: Support the pkgs pararameter like pkg.install

### ISSUE THREAD

**Issue by diegows** [saltstack/salt#13118]
npm state module should support the pkgs parameter like pkg.install. So we'll be able to do something like:

```
npm-pkgs:
  npm.installed:
    - pkgs:
      - express
      - coffe-script
      - grunt
```
