### ISSUE TITLE
Misleading error message if included state does not exist in multi-env environment

### ISSUE THREAD

**Issue by dansoap** [saltstack/salt#13219]
As the title says: When you try to include a state in another state on a multi-environment setup, the error message displayed is extremely misleading. This error occurs on masterless and masterful setups.
### To reproduce:
1. Set up a minion to work locally, /etc/salt/minion:

```
file_client: local

file_roots:
   base:
     - /srv/salt/base/states
   dev:
     - /srv/salt/dev/states
     - /srv/salt/base/states
```
1. create a state in the base environment e.g. `/srv/salt/base/states/test/init.sls` and include a non-existing state:

```
include:
  - .i-do-not-exist
```
1. Now run the salt-call locally:  `salt-call --local state.sls test`
### Expected output:

```
local:
    Data failed to compile:
----------
    Specified SLS test.i-do-not-exist in environment base is not available on the salt master
```
### Actual output:

```
local:
    Data failed to compile:
----------
    No matching sls found for 'test' in env 'base'
```

This led us to look for the error for some hours before we finally discovered the missing include :-/

If you need any more information, I'm happy to deliver :-).
