### ISSUE TITLE
salt.states.pkg using * in version causes it to fail everytime

### ISSUE THREAD

**Issue by jessecollier** [saltstack/salt#13247]
This actually has the desired outcome with the version I want installed, but the state returns false.

My state:

``` yaml
  pkg.installed:
    - name: salt-minion
    - enabled: False
    - version: '2014.1.*'
    - order: 1
```

Result:

```
          ID: Install Salt
    Function: pkg.installed
        Name: salt-minion
      Result: False
     Comment: The following packages failed to install/update: salt-minion=2014.1.*.
     Changes:
              ----------
              salt-common:
                  ----------
                  new:
                      2014.1.4+ds-2trusty3
                  old:
                      0.17.5+ds-1
              salt-minion:
                  ----------
                  new:
                      2014.1.4+ds-2trusty3
                  old:
                      0.17.5+ds-1
```
