### ISSUE TITLE
feature request: file.recurse: multiple/mixed settings (e.g. perms, templating) for file.recurse based on pattern

### ISSUE THREAD

**Issue by alex-dot** [saltstack/salt#13326]
Currently I am implementing a drop-in installation of a non-repo package. This package has executable files and non-executable files. Naturally both need differing permission settings. 

Currently there does not exist a way to do this. If one would want to copy recursively files with different permissions two separate states need to be called. This is tedious, verbose, and error-prone unless the files are also separated inside files-root. 

My current workaround is issuing a cmd when the files change:

```
cmd.wait:
  - name: find /opt/hadoop -regextype posix-egrep -regex '.*/((libexec)|(s?bin))/.*' -type f -exec chmod 755 {} +
  - watch:
    - file: state
```

However this lets the watched file.recurse state run on the next highstate because the files changed by that command. Therefore all matched files get their permissions changed twice on every highstate. 

An addition to the file module would be preferable. Maybe something like this:

```
- file_modes:
  - default: 0644
  - custom: 
    - pattern: E@(EXEC)|(BIN)
    - mode: 0755
  - custom:
    - pattern: hello*
    - mode: 0000
```
