### ISSUE TITLE
boto_sqs state should accept multiple queue names

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#13409]
It's pretty common to create a large number of queues that only have different names. Make it possible to create multiple via one state:

``` yaml
Ensure sqs queues exists:
  boto_sqs.present:
    - names:
      - queue1
      - queue2
    - attributes:
      ReceiveMessageWaitTimeSeconds: 20
    - profile: myprofile
```
