### ISSUE TITLE
[FR] states.file selinux support

### ISSUE THREAD

**Issue by halberom** [saltstack/salt#1349]
Hello

Not sure where selinux is on the roadmap, but it would useful to have selinux key=value pair options in the states.file.

e.g. from a puppet example:

```
file { "/usr/lib64/nagios/plugins/check_mem.pl":
    owner => "root",
    group => "root",
    mode => "0755" ,
    replace => true,
    source => "puppet:///modules/icinga/check_mem.pl",
    require => Package["nagios-plugins-nrpe"],
    seluser => "system_u",
    selrole => "object_r",
    seltype => "nagios_system_plugin_exec_t",
    selrange => "s0",
}
```

thanks

**Comment by pgporada** [comment]
It would be incredibly nice to be able to do something like this very similarly to the module file.set_selinux_context except in a state file. How would one get started writing/testing this?

```
        /etc/yum.repos.d/epel.repo:
          file.set_selinux_context:
            - path: /etc/yum.repos.d/epel.repo
            - user: system_u
            - role: object_r
            - type: system_conf_t
            - range: s0
```

**Comment by carlwgeorge** [comment]
@pgporada Thanks for your example workaround.  Based on that I wrote a shorter version that only calls `stat` once, instead of four times.  Hopefully it can be of use to you as well.

```yaml
{%- set path = '/etc/yum.repos.d/epel.repo' %}
{%- set context = 'system_u:object_r:system_conf_t:s0' %}
  cmd.run:
    - name: chcon {{ context }} {{ path }}
    - unless: test $(stat -c %C {{ path }}) == {{ context }}
```
