### ISSUE TITLE
ssh_auth.present corrupts SSH1 RSA key type in authorized_keys

### ISSUE THREAD

**Issue by sashadt** [saltstack/salt#13532]
When trying to create authorized_keys file with multiple key types using ssh_auth.present, some key formats are successfully added to authorized_keys and others are corrupted.  Here is an example salt/users.sls file:

```
# Add ssh keys to .ssh/authorized_keys file
ssh_auth.present:
  - user: {{ username }}
  - names:
  {% for pub_ssh_key in details.get('authorized_keys', []) %}
    - {{ pub_ssh_key }}
  {% endfor %}
```

And here is snippet from pillar/users.sls file with user data:

```
users:
  testuser:
    fullname: Test User
    authorized_keys:
      - '1024 33 144422644861843994149619420106137732514008548930774773431048102615325103713228623632622293816792497851685026704241232686514999440638829956630606671633729814637279217493779748030844279649003942654466692515888266764791316825159621676076980607350129143822822848093331893791313143593925530373430183166331165329709 test@test.com'
      - ssh-dss AAAAB3NzaC1kc3MAAACBAKmhDem1AYZXVZH+t3bY9h2xVjoQ0XutRhdZEnbjfy71eTjiPiAnyGuFUIouhSQMapwe6zf7zAYrhOyirr3Aak+wFGavo1+NdkWni7FInrRdN80VXg4JKA+/6c1P9lvn6xyypHcSTJNzTgDEJG5kwu0mSZ/Q5Hbcq3R0Yh+GIevnAAAAFQCCq66LQdNRw/5KeFU0w7DL7NBqBwAAAIA3P+CrSMALHRkeLrQhELxaWj1+VW8PXua61KMJwgc1lgZmlpEpGSXrXCi6HeGRTQTQIwMHx5QesT1/DRhab8lIlZ8+RMMg/kjjGqCYcvtH7unFZsbUBqnzPeuw8jPnJycAes92frY6onrMtrHLxNuOY4jeFhPTy5J9QCihUYbc2AAAAIA2/i1AkMYlazmgbsyGfjWWELhF91LqD0zbsKNDu+7rPBFpB9ucS5ayQRC9q1uh9aGxp95CuxPkVd4Kw44+PQAcNu7606ta1lhFo0EXLopz+C5WbA5or2QhDEdZIRfgwVq1x0su0jZXQ9FgZw+XtCG3O8fklHO+COXvfQEFSsaqKQ== Test User
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOHt6EgWyeKQ3tRUjvQ1LzSmq0on6HVRBC6RxpjRm7qgfGlNlSO5EtHz7kUsjUwdJEdpp7UPzj6jIL2Rvwii00hHdVjy9izESIpprpWZf8ItI0/SMIJz6uRTeupIHnEaNiLp0BNaNAjy7KtwlIg5PN82CSFqzGuuYGTGqrK6DxMYz3mRWNPcrDYH2baHiBtAqhAIt1eu7tG59kKbK2YtROldIj7CHOruhQdR36K6wTc6Jv53wAZGRQP7Hxx9C8TSBxon/hJQ7QTsZCs6CKPW7d55b+/kZxLyla9wPaATjJz8Cp4Ivq3XRVZKWtA13UIF1IUntrsxxMqjqiwWARdtlj test@test.com
```

Running this results in the following ~/.ssh/authorized_keys file:

```
ssh-dss AAAAB3NzaC1kc3MAAACBAKmhDem1AYZXVZH+t3bY9h2xVjoQ0XutRhdZEnbjfy71eTjiPiAnyGuFUIouhSQMapwe6zf7zAYrhOyirr3Aak+wFGavo1+NdkWni7FInrRdN80VXg4JKA+/6c1P9lvn6xyypHcSTJNzTgDEJG5kwu0mSZ/Q5Hbcq3R0Yh+GIevnAAAAFQCCq66LQdNRw/5KeFU0w7DL7NBqBwAAAIA3P+CrSMALHRkeLrQhELxaWj1+VW8PXua61KMJwgc1lgZmlpEpGSXrXCi6HeGRTQTQIwMHx5QesT1/DRhab8lIlZ8+RMMg/kjjGqCYcvtH7unFZsbUBqnzPeuw8jPnJycAes92frY6onrMtrHLxNuOY4jeFhPTy5J9QCihUYbc2AAAAIA2/i1AkMYlazmgbsyGfjWWELhF91LqD0zbsKNDu+7rPBFpB9ucS5ayQRC9q1uh9aGxp95CuxPkVd4Kw44+PQAcNu7606ta1lhFo0EXLopz+C5WbA5or2QhDEdZIRfgwVq1x0su0jZXQ9FgZw+XtCG3O8fklHO+COXvfQEFSsaqKQ== 

ssh-rsa 1024 

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOHt6EgWyeKQ3tRUjvQ1LzSmq0on6HVRBC6RxpjRm7qgfGlNlSO5EtHz7kUsjUwdJEdpp7UPzj6jIL2Rvwii00hHdVjy9izESIpprpWZf8ItI0/SMIJz6uRTeupIHnEaNiLp0BNaNAjy7KtwlIg5PN82CSFqzGuuYGTGqrK6DxMYz3mRWNPcrDYH2baHiBtAqhAIt1eu7tG59kKbK2YtROldIj7CHOruhQdR36K6wTc6Jv53wAZGRQP7Hxx9C8TSBxon/hJQ7QTsZCs6CKPW7d55b+/kZxLyla9wPaATjJz8Cp4Ivq3XRVZKWtA13UIF1IUntrsxxMqjqiwWARdtlj test@test.com
```

As you can see in the resulting authorized_keys file ssh-rsa, and ssh-dss keys are in good format, although ssh-dss is missing the comment string.  The ssh1-rsa type key is invalid, and contains only the first fragment from the original data.  Also, I'm not sure why there are blank lines between the keys in the resulting authorized_keys file.
