### ISSUE TITLE
salt.states.file.append does not append newline correctly

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#13683]
`salt.states.file.append` doesn't not append a newline to file. 

Here's are the different versions i used and its test output:

**VERSION1**

```
testcase:
  file.append:
    - name: /etc/ssh/sshd_config
    - text:   
       - \n     
       - nextline
```

```
----------
          ID: testcase
    Function: file.append
        Name: /etc/ssh/sshd_config
      Result: None
     Comment: File /etc/ssh/sshd_config is set to be updated
     Started: 14:56:20.337832
     Duration: 2 ms
     Changes:   
              ----------
              diff:
                  ---  
                  +++  
                  @@ -138,3 +138,5 @@
                   #    ForceCommand cvs server
                   UseDNS no
                   PermitRootLogin without-password+\n
                  +nextline                  
----------      
```

**VERSION2**

```
testcase:
  file.append:
    - name: /etc/ssh/sshd_config
    - text:   
       - "\n"
       - nextline
```

```
 ----------
          ID: testcase
    Function: file.append
        Name: /etc/ssh/sshd_config
      Result: None
     Comment: File /etc/ssh/sshd_config is set to be updated
     Started: 14:57:15.005112
     Duration: 2 ms
     Changes:   
              ----------
              diff:
                  ---  
                  +++  
                  @@ -138,3 +138,4 @@
                   #    ForceCommand cvs server
                   UseDNS no
                   PermitRootLogin without-password+nextline
----------      
```

**VERSION3**

```
testcase:
  file.append:
    - name: /etc/ssh/sshd_config
    - text:   
       - '\n'
       - nextline
```

```
----------
          ID: testcase
    Function: file.append
        Name: /etc/ssh/sshd_config
      Result: None
     Comment: File /etc/ssh/sshd_config is set to be updated
     Started: 14:58:26.702172
     Duration: 2 ms
     Changes:   
              ----------
              diff:
                  ---  
                  +++  
                  @@ -138,3 +138,5 @@
                   #    ForceCommand cvs server
                   UseDNS no
                   PermitRootLogin without-password+\n
                  +nextline
----------      
```

**VERSION4**

```
testcase:
  file.append:
    - name: /etc/ssh/sshd_config
    - text:   
       - "'\n'"
       - nextline
```

```
----------
          ID: testcase
    Function: file.append
        Name: /etc/ssh/sshd_config
      Result: None
     Comment: File /etc/ssh/sshd_config is set to be updated
     Started: 14:59:38.011591
     Duration: 2 ms
     Changes:   
              ----------
              diff:
                  ---  
                  +++  
                  @@ -138,3 +138,6 @@
                   #    ForceCommand cvs server
                   UseDNS no
                   PermitRootLogin without-password+'
                  +'
                  +nextline
----------      
```

Do note that **VERSION4** does what's required except that it puts the apostrophes `''`

The wanted behavior should be:

```
              diff:
                  ---  
                  +++  
                  @@ -138,3 +138,6 @@
                   #    ForceCommand cvs server
                   UseDNS no
                   PermitRootLogin without-password+
                  +
                  +nextline
```

The following works as a workaround:

```
testcase:
  file.append:
    - name: /etc/ssh/sshd_config
    - text: | 


       nextline
```

```
----------
          ID: testcase
    Function: file.append
        Name: /etc/ssh/sshd_config
      Result: None
     Comment: File /etc/ssh/sshd_config is set to be updated
     Started: 14:59:38.011591
     Duration: 2 ms
     Changes:   
              ----------
              diff:
                  ---  
                  +++  
                  @@ -138,3 +138,6 @@
                   #    ForceCommand cvs server
                   UseDNS no
                   PermitRootLogin without-password+
                  +
                  +nextline
----------      
```
