### ISSUE TITLE
mysql_grant failing check but adding grant

### ISSUE THREAD

**Issue by mzupan** [saltstack/salt#13745]
Using the following salt version

2014.1.1-1precise1

I have the following

```
passport-user:
  mysql_user.present:
    - name: passport
    - password: {{pillar['mysql_passport_pw']}}
    - host: {{pillar['lans']['auth']}}
  mysql_grants.present:
    - user: passport
    - grant: SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES
    - database: passport_{{grains['company_env']}}.*
    - host: '{{pillar['lans']['auth']}}'
    - escape: False
```

I get the following on the minion

```
[DEBUG   ] grants mismatch {'host': '10.88.51.0/255.255.255.0', 'database': '`passport_qa`', 'user': 'passport', 'grant': ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'CREATE', 'DROP', 'INDEX', 'ALTER', 'CREATE TEMPORARY TABLES', 'LOCK TABLES']}<>{'host': '10.88.51.0/255.255.255.0', 'database': 'passport_qa', 'user': 'passport', 'grant': ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'CREATE', 'DROP', 'INDEX', 'ALTER', 'CREATE TEMPORARY TABLES', 'LOCK TABLES']}
[DEBUG   ] Grant does not exist, or is perhaps not ordered properly?
```

The grants are there as

```
mysql> show grants for passport@'10.88.51.0/255.255.255.0';
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Grants for passport@10.88.51.0/255.255.255.0                                                                                                                       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'passport'@'10.88.51.0/255.255.255.0' IDENTIFIED BY PASSWORD '*xxxxx'                                     |
| GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON `passport_qa`.* TO 'passport'@'10.88.51.0/255.255.255.0' |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2 rows in set (0.00 sec)
```

As you can see in the logs.. its pulling the database out as

```
`passport_qa`
```

While in the yaml its

```
passport_qa
```

If i remove the escape: False it created a grant as 

```
passport\_qa
```
