### ISSUE TITLE
Salt returns wrong error message after pkg installed properly.

### ISSUE THREAD

**Issue by Janagaraj** [saltstack/salt#13787]
After installation, salt returns wrong error message. 

```
ID: robot
Function: pkg.installed
Result: False
Comment: The following packages failed to install/update: robotfw
Changes: 
                -------------------
                robotframework:
                         ------------
                         new:
                               2.7.7-1
                         old:
```
-----------------------------------------------------------------------------------------
```
robot.sls
robot:
     pkg.installed:
         - sources:
               - robotfw: salt://robotrpm/robotframework-2.7.7-1.noarch.rpm
```
-------------------------------------------------------------------------------------------
```
Salt master & minion version
Salt: 2014.1.4
```
-------------------------------------------------------------------------------------------
I tried with several other rpms, but salt returns the same wrong error message above.
