### ISSUE TITLE
file.recurse with clean won't  depend on files if they use name

### ISSUE THREAD

**Issue by non7top** [saltstack/salt#13830]
Here is a sample sls file.

``` YAML
/etc/yum.repos.d:
  file.recurse:
    - name: /etc/yum.repos.d
    - clean: True
    - source: salt://baseconfig/files/yum.repos.d

bitrix_repo:
  file.managed:
    - name: /etc/yum.repos.d/bitrix.repo
    - source: salt://webserver/files/bitrix.repo
    - require_in:
      - file: /etc/yum.repos.d

/etc/yum.repos.d/bitrix.repo2:
  file.managed:
    - source: salt://webserver/files/bitrix.repo
    - require_in:
      - file: /etc/yum.repos.d
```

So bitrix.repo2 is correctly handled as managed file, while bitrix.repo is not - it is created and then removed in the next step, though ordering does work.

```
example.com:
----------
          ID: /etc/yum.repos.d/bitrix.repo2
    Function: file.managed
      Result: True
     Comment: File /etc/yum.repos.d/bitrix.repo2 is in the correct state
     Changes:
----------
          ID: bitrix_repo
    Function: file.managed
        Name: /etc/yum.repos.d/bitrix.repo
      Result: True
     Comment: File /etc/yum.repos.d/bitrix.repo updated
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: /etc/yum.repos.d
    Function: file.recurse
      Result: True
     Comment: Recursively updated /etc/yum.repos.d
     Changes:
              ----------
              removed:
                  - /etc/yum.repos.d/bitrix.repo

Summary
------------
Succeeded: 3
Failed:    0
------------
Total:     3
```
