### ISSUE TITLE
Saltify physical windows host

### ISSUE THREAD

**Issue by oldominion** [saltstack/salt#13892]
I understand that it should be possible to bootstrap salt-minion on a windows server (locally, rather than in the cloud), using saltify. I'm struggling to find documentation on how to configure this. Would someone please clarify if this is possible, and if so, how to go about it? Thanks..

I currently have it setup as follows:

```
/etc/salt/cloud.providers.d# cat saltify.conf
saltify_windows:
  provider: saltify
  win_installer: /root/Salt-Minion-2014.1.5-AMD64-Setup.exe
  win_password: ******
  win_username: test\administrator
```

..and I'm running:

```
# salt-cloud -a saltify_windows jouk01cxa01.test.local
 [INFO    ] salt-cloud starting
The following virtual machines are set to be actioned with "saltify_windows":
  jouk01cxa01.test.local
Proceed? [N/y] y
... proceeding
Not Actioned/Not Running:
    - jouk01cxa01.test.local
```
