### ISSUE TITLE
pillar.item/config.option inconsistent after sync_all

### ISSUE THREAD

**Issue by mistigi** [saltstack/salt#13935]
When I update pilar file on the master and do `saltutil.sync_all`, `pillar.item` and `config.option` show different data, e.g.
Initial state:

```
/srv/pillar/web.sls:
mine_functions:
  grains.item:
    - roles

master# salt minion01 config.option mine_functions
minion01:
    ----------
    grains.item:
        - roles

master# salt minion01 config.option mine_functions
minion01:
    ----------
    grains.item:
        - roles
```

Changing pillar data:

```
/srv/pillar/web.sls:
mine_functions:
  grains.item:
    - tier

master# salt minion01 saltutil.sync_all
minion01:
    ----------
    grains:
    modules:
    outputters:
    renderers:
    returners:
    states:
```

This is incorrect, expecting "tier" (or "role" if `sync_all` is not supposed to touch pillar) for both `pillar.item` and `config.option`

```
master# salt minion01 pillar.item mine_functions
minion01:
    ----------
    mine_functions:
        ----------
        grains.item:
            - tier

master# salt minion01 config.option mine_functions
minion01:
    ----------
    grains.item:
        - roles
```

This also causes salt mine to operate on old `mine_functions` value

```
# salt --versions-report
           Salt: 2014.1.5
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4

# uname -a
Linux master 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 
x86_64 x86_64 x86_64 GNU/Linux
```
