### ISSUE TITLE
dockerio state, mount volumes dosn't work

### ISSUE THREAD

**Issue by jacksoncage** [saltstack/salt#14089]
I'm using dockerio salt state to startup docker containers on a salt minion. Trying to mount volumes into my container is failing. Container is starting but volumes are mounted to the right places.

**Aiming for this**

```
sudo docker run \
  --volume=/var/run:/var/run:rw \
  --volume=/sys/fs/cgroup/:/sys/fs/cgroup:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  google/cadvisor
```

**cadvisor sls file**

```
cadvisor-image:
   docker.pulled:
     - name: google/cadvisor
     - tag: latest
     - require_in: cadvisor-container
     - force: True

cadvisor-container:
   docker.installed:
     - name: cadvisor
     - hostname: cadvisor
     - image: google/cadvisor
     - ports:
       - "8080/tcp"
     - volumes:
       - /var/run:/var/run
       - /sys/fs/cgroup:/sys/fs/cgroup
       - /var/lib/docker:/var/lib/docker
     - require_in: cadvisor

cadvisor:
   docker.running:
     - container: cadvisor
     - port_bindings:
            "8080/tcp":
                HostIp: ""
                HostPort: "8080"
     - binds:
       /var/run:
         bind: /var/run
         rw: true
       /sys/fs/cgroup:
         bind: /sys/fs/cgroup
       /var/lib/docker:
         bind: /var/lib/docker
```

According to the [dockerio.py](https://github.com/saltstack/salt/blob/9e0b920cc83352cb9effce6ff01cdff4a250f624/salt/modules/dockerio.py#L568) `/var/run:/var/run` should work.

**docker inspect cadvisor**

```
    "Volumes": {
        "/sys/fs/cgroup": "/data/docker/var/lib/docker/vfs/dir/4b73afb95950512f14b1756234d99301cd1092bab090ed6b8d346a33f07592d4",
        "/var/lib/docker": "/data/docker/var/lib/docker/vfs/dir/d26ca697e1bcc0f33ce2e4da48e7bb063c7820513850aede726e683a6b91cadd",
        "/var/run": "/data/docker/var/lib/docker/vfs/dir/a78769e20861055f0bb3c85b024a325c61b57451520c8c918b9b73b7586c655d"
    },
    "VolumesRW": {
        "/sys/fs/cgroup": true,
        "/var/lib/docker": true,
        "/var/run": true
    }
```

**Should look like this if volumes where right**

```
    "Volumes": {
        "/sys/fs/cgroup": "/sys/fs/cgroup",
        "/var/lib/docker": "/var/lib/docker",
        "/var/run": "/run"
    },
    "VolumesRW": {
        "/sys/fs/cgroup": false,
        "/var/lib/docker": false,
        "/var/run": true
    }
```

**Versions**

```
love@master:~$ cat /etc/issue
Ubuntu 12.04.1 LTS \n \l

love@master:~$ salt server01 cmd.run "docker version"
server01:
    Client version: 1.1.1
    Client API version: 1.13
    Go version (client): go1.2.1
    Git commit (client): bd609d2
    Server version: 1.1.1
    Server API version: 1.13
    Go version (server): go1.2.1
    Git commit (server): bd609d2

love@master:~$ salt server01 cmd.run "salt-minion --version"
server01:
    salt-minion 2014.1.7

love@master:~$ salt --version
salt 2014.1.7
```

**Comment by TTimo** [comment]
+1

I was able to get volumes mounted in my containers after some trial and error. The documentation is inaccurate?

```
root@qlhost /r/q/salt# salt-call --version
salt-call 2014.7.1 (Helium)
root@qlhost /r/q/salt# docker --version
Docker version 1.4.1, build 5bc2ff8
```

http://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerio.html#salt.states.dockerio.running points to using 'volumes'

but the docker-py documentation refers to 'binds': http://docker-py.readthedocs.org/en/latest/volumes/

here's an example of a container installed/running that worked for me:

```
pgsql-container-exists:
  docker.installed:
    - name: pgsql
    - image: "pgsql:latest"
    - hostname: pgsql
    - tty: true
    - command: "/usr/local/sbin/container-start.sh"
    - ports:
      - "5432/tcp"
    - volumes:
      - "/var/lib/postgresql/9.3/main"

pgsql-container-running:
  docker.running:
    - container: pgsql
    - port_bindings:
        "5432/tcp":
          HostIp: "172.17.42.1"
          HostPort: "5432"
    - binds:
        "/root/pgsql-data/":
          bind: "/var/lib/postgresql/9.3/main"
          ro: false
```

**Comment by tkent-xetus** [comment]
_A quick warning to others who stumble across this issue_

As of salt __2015.5.0__ (just released), the `binds` key must be replaced with `volumes`. I had to figure that out trying to understand out why our newly provisioned AWS instances were all failing to start their containers. The reason was that, as of __2015.5.0__ you use `volumes` instead of `binds` in  your docker.running state. The [salt doc's](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerio.html) correctly reflect the usage now, but it's a change from the previous version.

So, to be clear using the example from @TTimo, if you had this before 2015.5.0

```
pgsql-container-running:
  docker.running:
    - container: pgsql
    - port_bindings:
        "5432/tcp":
          HostIp: "172.17.42.1"
          HostPort: "5432"
    - binds:
        "/root/pgsql-data/":
          bind: "/var/lib/postgresql/9.3/main"
          ro: false
```

You need this after upgrading.

```
pgsql-container-running:
  docker.running:
    - container: pgsql
    - port_bindings:
        "5432/tcp":
          HostIp: "172.17.42.1"
          HostPort: "5432"
    - volumes:
        "/root/pgsql-data/":
          bind: "/var/lib/postgresql/9.3/main"
          ro: false
```

 Hope this saves somebody some time. Now to figure out how to control what version of salt gets installed when using salt-cloud...

**Comment by basepi** [comment]
Hint: use `script_args` in your map to pass bootstrap arguments (to control which version is installed)

```
ubuntu-14.04:
  - basepi_minion_master:
      make_master: True
      minion:
        local_master: True
      script_args: git v2015.5.0
  - basepi_minion1:
      minion:
        local_master: True
      script_args: git v2015.5.0
debian-7:
  - basepi_minion2:
      minion:
        local_master: True
      script_args: git v2015.5.0
cent-6.5:
  - basepi_minion3:
      minion:
        local_master: True
      script_args: git v2015.5.0
```

You can also pass in `--script-args='git v2015.5.0'` to the `salt-cloud` command.

**Comment by tkent-xetus** [comment]
@basepi thanks!

I ended up using `script_args: 'stable XXXX'` after checking out the bootstrap-salt.sh source. Since we use ubuntu systems, that made sense to me.

There's no special reason you suggested `git` instead, right? As in, I'm not going to regret using `stable` later, am I :-)

**Comment by basepi** [comment]
Nope, should be fine! I just tend to use git so I can target exact git tags. =)

**Comment by tkent-xetus** [comment]
@basepi  ha! You were wrong, I _do_ regret using `script_args: 'stable XXXX'` :-P.

It turns out that the feature to specify the package version for 'stable' bootstraps is not included with the boostrap-salt script in 2015.5.0. I happened to be testing locally with a newer version and didn't notice. I've swapped to using the git args and it works great.

**Comment by basepi** [comment]
Well, I'm glad you got it figured out! =D

**Comment by discordianfish** [comment]
I'm running 2015.5.2 and using 'volumes' and I tried both:

```
  docker.running:
    - container: prometheus-server
    - image: prom/prometheus:latest
    - volumes:
      - /etc/prometheus:/etc/prometheus
    - ports:
        "9090/tcp":
            HostIp: ""
            HostPort: "9090"
```

as well as:

```
prometheus_server:
  docker.running:
    - container: prometheus-server
    - image: prom/prometheus:latest
    - volumes:
      - /etc/prometheus:
        bind: /etc/prometheus
        ro: True
    - ports:
        "9090/tcp":
            HostIp: ""
            HostPort: "9090"
```

But neither worked. The volume doesn't get bind-mounted.

**Comment by immunda** [comment]
@discordianfish This is from a working state with `docker-py==1.2.2` and Salt `2015.5`, let me know if it helps.

```
{{ name }}-image:
  docker.pulled:
    - name: {{ image }}
    - tag: latest
    - require_in: {{ name }}-container

{{ name }}-container:
  docker.installed:
    - name: {{ name }}
    - hostname: {{ name }}
    - volumes:
      - /projects/: /projects/
    - image: {{ image }}
    - require_in: {{ name }}

{{ name }}:
  docker.running:
    - image: {{ image }}
    - container: {{ name }}
    - volumes:
        /projects/:
          bind: /projects/
    - restart_policy:
        MaximumRetryCount: 0
        Name: always
    - links:
        consul: consul
```
