### ISSUE TITLE
could salt support diff file watcher in state?

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#14387]
As I known, salt has enabled backup option in sls since 0.17.x, but I think it should combine with file module to make it more effective.

For example, I have a nginx.sls:

```
Custom-Nginx:
    pkg.installed:
        - name: Custom-Nginx
    service.running:
        - name: nginx
        - watch:
          - pkg: Custom-Nginx
          {# watch whether the file changed since last backup? #}
```

and I just want to do something when it found the nginx.conf file has changed since last backup, and it should look like:

```
Custom-Nginx:
    pkg.installed:
        - name: Custom-Nginx
    file.get_diff:
        - name: check-diff
        - minionfile: /etc/nginx/nginx.conf
        - masterfile: backup://nginx.conf {# now, it will check out the backup minion file #}
    service.running:
        - name: nginx
        - watch:
          - pkg: Custom-Nginx
          - file: check-diff
```

and this state will restart nginx or do other action when found the nginx.conf has changed since last backup minion.
