### ISSUE TITLE
Interaction between jinja, yaml, and False values not clear

### ISSUE THREAD

**Issue by thenewwazoo** [saltstack/salt#14496]
The "False" value behaves differently when used by default and context when templating a jinja file. This makes "is defined" tests hard to manage in the template. To wit:

``` yaml
### footemplate.sls
/var/tmp/default:
  file.managed:
    - source: salt://foofile.templ
    - template: jinja
    - default:
        fooval: False

/var/tmp/context:
  file.managed:
    - source: salt://foofile.templ
    - template: jinja
    - context:
        fooval: False
```

``` yaml
### foofile.templ
{% if fooval is defined %}{{fooval}}{% endif %}
```

...results `/var/tmp/default` containing no text, but `/var/tmp/context` containing the string "False"
