### ISSUE TITLE
Using YAML anchors/references in Pillars causes conflicting IDs

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#14550]
How to reproduce:

1. Create a Pillar like this:
    ```YAML
    yamltest:
        defaults: &defaults
            group: users
            path: /var/lib/app
            mask: '0644'
    
        definitions:
            main:
                <<: *defaults
            test:
                <<: *defaults
                path: /var/lib/testapp
            staging:
                <<: *defaults
                mask: '0555'
    ```
2. Use it in an SLS like this:
    ```YAML
    {% for definition, data in salt['pillar.get']('yamltest:definitions').iteritems() %}
    yamltest-{{ definition }}:
        test.succeed_without_changes:
            - name: {{ definition }}
    {% endfor %}
    ```

3. Apply it to a Minion:
    ```YAML
    MN1221-C0013:
        Data failed to compile:
    ----------
        Pillar failed to render with the following messages:
    ----------
        Rendering SLS 'pillars.yamltest' failed, render error:
    Conflicting ID 'path'
    ````

The problem seems to be, that the keys duplicated by using the anchor/reference aren't merged before being further evaluated.
