### ISSUE TITLE
[salt.cloud] Maps should check for bad formatting

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#14595]
Ping @prfalken.

When Salt Cloud reads a map, it does not currently check to make sure that map items are in a list format. For instance, this looks correct, but isn't:

```
my-profile-config:
    myvm1:
      minion:
        master: salt
    myvm2:
      minion:
        master: salt
```

This is the correct version:

```
my-profile-config:
    - myvm1:
      minion:
        master: salt
    - myvm2:
      minion:
        master: salt
```
