### ISSUE TITLE
permit file_roots to be defined as a relative path

### ISSUE THREAD

**Issue by khaije1** [saltstack/salt#14613]
Please either 
1) alter file_roots to respect a variable that _can_ be defined locally, such as root_dir or config_dir or using a new variable, (something like), file_roots_rela which would operate similarly to root_dir
-or-
2) add a complimentary means to define relative paths, that either defers entirely to file_roots or appends it's config to it

Example Use Case:
I'm creating a git repo that contains all the settings needed to manage my infrastructure. Using, salt-ssh -c ./etc/salt , I'm part of the way there. This is presently working except that - because file_roots requires an absolute path, it's paths must be altered with each clone or repo move.
This is further desirable because it can be stored, controlled and tracked using gitolite, handed off to junior admins as a decentralized infrastructure control-center kit and subsequently secure-deleted from a machine.

Note to the reader:
Sensitive data will be not stored in plain text. It is encrypted or otherwise obfuscated.
For example, the salt-ssh key and the GPG keys used are defined relative to the userhome, (using tilde, '~'), making the paths and the ensuing capabilities localized according to the "secrets" possessed by the invoking user.

**Comment by pykler** [comment]
+1

@davidjb comment uptop regarding paths relative to salt-call or salt-ssh is being called is correct in most cases except for `extension_modules`. Relative paths just don't seem to work at all for that.

**Comment by 3add3287** [comment]
Related to #7883

**Comment by khaije1** [comment]
Just wanted to bump this. It's still coming up as a hurdle. The latest example is with portable Salt-provisioner configurations in Packer ... a file_roots path in one circumstance is often invalid in another and thus far requires the maintenance and frequent swapping of largely redundant path'ing configuration which often varies only by the path prefix.

This should be considered a significant violation of the principle of least surprise, as a distributed work-flow hurdle, and as a paper-cut for those new to Salt when seeking to create and share examples which allow them to reason about systems at a chosen level of abstraction.

I think allowing/setting root_dir to be prepended to file_roots would be a really lovely and elegant solution to my issue.

I'm ```using root_dir: .``` in some projects for a while now and have found that it works great!

Please consider marking this for the next release?

**Comment by baby-gnu** [comment]
Hello,

I'm configuring salt-ssh to replace dish, clusterssh, pssh or mussh I used before.

This point is really annoying.

I setup `config_dir` in `~/.salt/Saltfile` and then I defined the following in my `~/.salt/master`:


``` yaml
# -*- yaml -*-

root_dir: .salt
pki_dir: pki
cachedir: cache
sock_dir: run
pidfile: pids

log_file: logs/master.log
key_logfile: logs/key.log

extension_modules: extmods

rosters:
  - rosters

file_roots:
  base:
    - states

pillar_roots:
  base:
    - pillars

# Salt-SSH specific
ssh_log_file: logs/ssh.log
ssh_use_home_key: True

# Global level logged in file
log_level_logfile: debug
```

I wanted the `file_roots` to be relative to `root_dir`.

Any news on this issue?

Regards.

**Comment by baby-gnu** [comment]
I was looking at the [source code](https://github.com/saltstack/salt/blob/2017.7.3/salt/config/__init__.py) and here are my thougths:

* we could define utility functions to expand paths in `salt.utils.path`
  * `expand_path` when the caller expect a single file
  * `expand_glob_path` when the caller expect a list
* each one take the optional argument `root_dir` and apply the same logic than [prepend_root_dir](https://github.com/saltstack/salt/blob/2017.7.3/salt/config/__init__.py#L2123) if it's not None (better to delegate to a dedicated function like `prepend_root_dir`)
* use `os.path.expanduser` to expand the user HOME directory
* handle `file://`, for example `file://~user/` should be the same as just `~user/`, `os.path.expanduser` do not handle `file://`

What do you think about this proposal?

**Comment by baby-gnu** [comment]
The non expansion of `~` for `file://` URI is normal according to [RFC8089](https://tools.ietf.org/html/rfc8089#appendix-D.1).

**Comment by khaije1** [comment]
What about the possibility of specifying paths as: `%(root_dir)s/my/relative/path`? It wouldn't solve all the issues/questions raised but would be a nice step in this direction. I'm just not clear on where this type of syntax is supported and where it isn't.

**Comment by damon-atkins** [comment]
Might help the salt team if you provide some examples.  I suspect your all talking about master-less implementations Or your running a master on a local work station for testing before pushing the code up to your git repo?

**Comment by baby-gnu** [comment]
@damon-atkins I have 2 scenarios.

The first is described in [#issuecomment-365304565](https://github.com/saltstack/salt/issues/14613#issuecomment-365304565).

The second is to use salt as a master-less provisionning for cloud images where I can't use `salt-ssh` (in a chroot for example): I would like to be able to mount a directory in my chroot and make the provisionning working with `salt-call`.

For example, I want:

1. a `/home/salt-provisionning` directory with a hierarchy like
```
.salt/
├── cache
├── logs
├── master
├── pillar
│   ├── chroots.sls
│   └── top.sls
├── pki
└── state
    ├── openssh
    │   ├── auth_map.sls
    │   ├── auth.sls
    │   ├── banner.sls
    │   ├── client.sls
    │   ├── config_ini.sls
    │   ├── config.sls
    │   ├── defaults.yaml
    │   ├── files
    │   │   ├── banner
    │   │   ├── fire_banner
    │   │   ├── ssh_config
    │   │   ├── sshd_config
    │   │   └── ssh_known_hosts
    │   ├── init.sls
    │   ├── known_hosts.sls
    │   ├── map.jinja
    │   └── moduli.sls
    ├── ssh_keys
    │   ├── bar.pub
    │   ├── foo.pub
    │   └── quux.pub
    ├── systemd
    │   └── timesyncd
    │       └── files
    │           └── chroots
    │               └── timesyncd.conf
    └── top.sls

```
2. define the following configuration
```
# -*- yaml -*-

root_dir: ~/.salt
pki_dir: pki
cachedir: cache
sock_dir: run
pidfile: pids

log_file: logs/master.log
key_logfile: logs/key.log

# Global level logged in file
log_level_logfile: debug

# Configure formulas
file_roots:
  base:
    - state

pillar_roots:
  base:
    - pillar
```
3. mount that `/home/salt-provisionning` under `/mnt/rootfs/root`
4. run `chroot /mnt/rootfs salt-call --local -c /root/.salt`

This way, everything is self contained in a directory, it's easier to maintain and share.

Regards.
