### ISSUE TITLE
custom grains disappearing on Windows

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt#14691]
On Windows salt-minion does not have the osarch grain so I wrote a custom grain for it, and synced the new grains to the minion

```
salt laracroft grains.get osarch
laracroft:
    32-bit
```

I have a sls file that looks like this

```
general-packages:
  pkg.installed:
    - pkgs:
      - firefox
      - perl-{{ grains['osarch'] }}
      - wireshark-{{ grains['osarch'] }}
```

When I deploy the sls file it complains that the grains isn't there, and it does in fact disappear

```
laracroft:
    Data failed to compile:
----------
    Rendering SLS "base:packages.windows.general" failed: Jinja variable 'dict object' has no attribute 'osarch'; line 9

---
[...]
general-packages:
  pkg.installed:
    - pkgs:
      - firefox
      - perl-{{ grains['osarch'] }}
      - wireshark-{{ grains['osarch'] }}    <======================

---
```

Sure enough, it's not there anymore

```
salt laracroft grains.get osarch
laracroft:
```

Any idea what is going on, and why does the grain disappear?
