### ISSUE TITLE
file.managed does not handle filename with ".override" in it

### ISSUE THREAD

**Issue by giannello** [saltstack/salt#14734]
Due to a bug with PHP-FPM in Ubuntu, I have to create a file that overrides default Upstart configuration.
The file should be called "/etc/init/php5-fpm.override", so I used the following:
```
php-fpm_init_script_reload_fix:
  file.managed:
    - name: /etc/init/php5-fpm.override
    - source: salt://php/files/php5-fpm.override
    - user: root
    - group: root
    - mode: 644
```
after executing salt-call, the file is NOT created.
Any other file name will work, but not if the name ends in ".override".
I tried quoting with single and double quotes, no luck.
At a first glance, the ".override" seems treated like a function call, but other functions like ".join" does not trigger the issue.
