### ISSUE TITLE
Test mode fails for states that depend on previous states

### ISSUE THREAD

**Issue by foxx** [saltstack/salt#14745]
For example:

```
admin:
  user.present:
    - shell: /bin/bash
    - home: /home/admin
    - uid: 999 
    - gid: 999 
    - require:
      - group: admin 

  group.present:
    - gid: 999 

/home/admin/.ssh:
  file.directory:
    - require:
      - user: admin
    - user: admin
    - group: admin
    - dir_mode: 700
    - file_mode: 700
```

Results in the following;

```
$ salt '*' state.highstate test=True

          ID: /home/admin/.ssh
    Function: file.directory
      Result: False
     Comment: User admin is not available
     Changes:   
```

However if I run without `test=True` (which then creates the user), any subsequent calls with `test=True` will work fine (I assume because the user now exists).
