### ISSUE TITLE
What API do I use to get overall job information

### ISSUE THREAD

**Issue by Supermathie** [saltstack/salt#14854]
I'm trying to do the following:
1. from Python (localclient), schedule a number of jobs to run async;
2. get the full status of each job (which nodes are still running, which have finished, returns, etc) every so often
3. Print out the results once all have completed/failed/etc

I'm using `salt.client.LocalClient` to do the scheduling and keep track of the jobs. At the moment I'm relying on get_cache_returns to tell me when a job has completed but this isn't reliable.

What I'm looking for is easy access to the data provided by jobs.active:

```
'20140808115205751151':
  Arguments:
  - //cng/testing/rand/med/rand-2
  - michael@ad2012r2.storagelab.netdirect.ca
  - 1048576
  Function: testcase-read.run
  Returned: []
  Running:
  - win7-client2.storagelab.netdirect.ca: 1536
  Target: win7-client2*
  Target-type: glob
  User: sudo_michael
```

But there's a lot of code in there that seems "internal".

Really I just want to be able to tell "did the job start? is this job still running? is it done? What's the output?"

How should I be approaching this?
