### ISSUE TITLE
The failed restart of a service is not returned

### ISSUE THREAD

**Issue by stlorenz** [saltstack/salt#14862]
I am using a nginx reverse proxy setup that is managed by salt:
i am using the following init.sls:

```
nginx:
  pkg.installed:
    - name: nginx
  service.running:
  - watch:
    - file: /etc/nginx/nginx.conf
    - file: /etc/nginx/sites.d


/etc/nginx/nginx.conf:
  file.managed:
    - source: salt://vm-host/nginx/nginx.conf

/etc/nginx/sites.d:
  file.recurse:
    - source: salt://vm-host/nginx/sites.d
    - clean: True
    - makedirs: True

```

If I add a new config and run state.highstate, the return says `service.restarted`. But if the added config contains an error, preventing nginx from getting restarted it does not return `fail`, just `service.restarted`.

I am not sure if saltstack is to blame here, since `service nginx restart` also just returns nothing. 
`/etc/init.d/nginx restart` instead returns `fail`

But how should i deal with this?

I am on Ubuntu 14.04 with salt  2014.1.7
