### ISSUE TITLE
State inclusion is limited

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#14899]
Currently, in a state I can include other modules:

``` yaml
include:
  - a
  - b
  - c
```

However, I'm doing ordered runs, and want to be able to define some states, then an include, then some more states, then another include:

``` yaml
Ensure myfile is managed:
  file.managed:
    ...

include:
  - a

Ensure myservice is running:
  service.running:
    ...

include:
  - b
```

This isn't possible since include is a yaml key and must be unique. It's possible to include the files explicitly via jinja:

``` yaml
{% include 'a/init.sls' %}
```

But this doesn't allow me to load a module from a different file_root without looping through the file_roots in opt, then checking to see if the file exists, then including it.

It would be nice if include works for multiple calls in a state file.
