### ISSUE TITLE
raid.present fails

### ISSUE THREAD

**Issue by rokka-n** [saltstack/salt#14903]
I'm having issues with raid.present state.

Here is the state file:

```
/dev/md0:
  raid.present:
    - level: 10
    - devices:
      - /dev/xvdf1
      - /dev/xvdf2
      - /dev/xvdf3
      - /dev/xvdf4
    - run: True
    - chunk: 256
```

```
vg0:
  lvm.vg_present:
    - devices: /dev/md0
```

```
lv0:
  lvm.lv_present:
    - vgname: vg0
    - extents: 8187
```

```
/mnt/vg0-lv0:
  mount.mounted:
   - persist: True
   - device: /dev/mapper/vg0-lv0
   - fstype: xfs
   - mkmnt: True
   - opts:
     - _netdev
     - nofail
```

salt -C ' server-blah1' state.sls volumes/assemble_md0_lv0_32g
ip-10-20-4-4:
----------
```
          ID: /dev/md0
    Function: raid.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1379, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/mdadm.py", line 87, in present
                  args.extend(opts)
              TypeError: 'NoneType' object is not iterable
```

Version:
```
$ salt-master --versions-report
           Salt: 2014.1.10
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2 
```
