### ISSUE TITLE
Require an sls file instead of just including it

### ISSUE THREAD

**Issue by JustinCarmony** [saltstack/salt#15026]
Right now I typically have very generic state files which I customize via pillar data, and then I'll have very specific state file that includes all of the different things I need and then add some very specific configs files, etc. Here is an example:

``` yaml
include:
  - common
  - utils
  - apache2
  - php5
  - repo.api
  - repo.ui

/etc/apache2/sites-available/myexample:
  file.managed:
    - source: salt://myproject/files/myexample
    - require:
      - sls: common
      - sls: php5
      - sls: apache2
      - sls: repo.api
      - sls: repo.ui

/etc/apache2/sites-available/anotherexample:
  file.managed:
    - source: salt://myproject/files/anotherexample
    - require:
      - sls: common
      - sls: php5
      - sls: apache2
      - sls: repo.api
      - sls: repo.ui

/etc/apache2/sites-available/example3:
  file.managed:
    - source: salt://myproject/files/example3
    - require:
      - sls: common
      - sls: php5
      - sls: apache2
      - sls: repo.api
      - sls: repo.ui
```

It would be awesome instead of having to require each sls file, I could "require" them instead of just include them:

``` yaml
require:
  - common
  - apache2
  - php5
  - repo.api
  - repo.ui

include:
  - utils
```

What this does is allow me to handle failures that can break my app much easier. If I need to change how we build apache2 under the hood with some additional scripts, etc, I just require the sls file.

Now if I have a simple utility that is nice to have, but not required by the app, I could still include it. If it has a failure inside somewhere, the other things can still run in my state file (unless I specific require them in a state declaration, which is how it works now).

Anyway, I think this would help people logically organize their requirements and dependancies.
