### ISSUE TITLE
Add a slightly more complex example to the states tutorial

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#1504]
Perhaps have an advanced "Tutorial page 4" or something? It should cover a real world use of a jinja template along with running a salt module from within the template and/or the state file.

Something like this perhaps?

``` yaml
/var/www/myip.html:
  file.managed:
    - source: salt://roles/wordpress/files/myip.html.jinja
    - user: root
    - group: root
    - mode: 640
    - template: jinja
    - context:
        hostname: {{ grains['fqdn'] }}
        ip: {{ salt['network.interfaces']()['eth0']['ipaddr'] }}
```
