### ISSUE TITLE
Feature: vpn.master_minion_tunnel (OpenVPN tunnel between master and minion)

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#15115]
I propose to add function to create OpenVPN tunnel between master and minion.

Invocation can look like this:

```
# salt 'MINION_ID' vpn.master_minion_tunnel
Created tunnel between master and minion "MINION_ID".
VPN:
  subnet: 10.8.0.0/24
Master:
  hostname: MASTER_FQDN
  ip: 10.8.0.1
Minion:
  hostname: MINION_ID
  ip: 10.8.0.2
```

After the invocation following happens:
1. OpenVPN tunnel is created.
2. Required certificates are generated and copied.
3. Network interfaces are created and started.
4. MINION_ID is added to the end of `hosts` file of the server.

Of course corresponding state would be helpful.

Why this feature would be great to have:
1. Salt itself is very powerful. But sometimes I need special tools to be able to communicate with minions: SQL clients, SSH (sometimes I need just look around and try something quickly).
2. It uses Salt infrastructure, almost no need to add additional code: master-minion connection, minion_id as a domain name, Salt functions.
3. #8249 becomes easier to implement — no need for reverse ssh tunnel. Just create the VPN tunnel, copy SSH key to the minion, and run `ssh MINION_ID`.
4. OpenVPN is not very easy to setup. You need to understand how networks work, how the routing happens in VPN, etc. With this state/module anybody can make a VPN tunnel in seconds, a whole range of VPN tunnels — in minutes without any knowledge and hours of manuals reading.

Issues:
1. MINION_ID can give name collision with hostnames in a LAN.
2. Should minions see each other? Do we need parameter for this?
3. Should this function install OpenVPN, start a service, enable it?
4. Will it work with OpenVPN only or with some other VPNs, like SoftEther or PPTP?

What do you think?

PS: To be honest, I've used OpenVPN only as a user. So, my knowledge might be inaccurate.
