### ISSUE TITLE
system.join_domain() does not join domain on Windows Server 2012 R2

### ISSUE THREAD

**Issue by baskinomics** [saltstack/salt#15177]
The Salt master is reporting this state having completed successfully, but remoting into the server indicates that it did not join the domain. The relevant contents of my `sls` file:

```yaml
Join Domain:
  module.run:
    - name: system.join_domain
    - domain: mydomain.com
    - username: username
    - passwd: mypass
    - account_ou: 'CN=Computers,DC=blah,DC=com'
    - account_exists: false
```

The output from `highstate`:

```yaml
----------
          ID: Join Domain
    Function: module.run
        Name: system.join_domain
      Result: True
     Comment: Module function system.join_domain executed
     Changes:   
```

I came across this email thread, but an issue does not appear to have been filed.
https://groups.google.com/forum/#!topic/salt-users/T5PPWkXdMkU

Maybe someone needs to open a new issue on the documentation as well. I have to change `password` to `passwd` for this to work.

http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_system.html#salt.modules.win_system.join_domain
