### ISSUE TITLE
boto_secgroup accept a list of ports and ips

### ISSUE THREAD

**Issue by diegows** [saltstack/salt#15196]
I would be great to have something like that in boto config.

```
locust-secgroup-{{ region }}:
  boto_secgroup.present:
    - name: locust
    - description: locust
    - rules:
      - ip_protocol: tcp
        to_port:
          - 80
          - 443
          - 5557
        cidr_ip:
          - 1.2.3.4/32
          - 5.6.7.8/32
    - region: {{ region }}
```
