### ISSUE TITLE
master config: add support for modules, located in repositories in extension_modules 

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#15210]
I propose to add support for a modules, located in separate repositories.

master config would look like this:

```
extension_modules:
  - git@github.com:saltstack/salt.git:
    - modules:
      - vbox_guest
    - states:
      - liquid
      - gaseous
  - /srv/salt-extensions:
    - runners:
      - forrest_gump
    - output:
      - '*'
```

Repositories should have following structure:

```
root:
  - salt:
    - modules
    - runners
    - ...
```

or

```
root:
  - modules
  - runners
  - ...
```

On each `saltutil.sync_what` master will sync extensions with minions.

Why?
1. It will give an opportunity to easily extend Salt by writing modules/runners/etc. and use they in production not waiting until new Salt release.
2. It will give a very easy way to create 3rd party repositories an attach them to a running salt master and minions.
3. No problems with symlinking (especially in repositories) and installing hooks (to update on incoming commits).

I think this isssue correlates with `gitfs` and `hgfs`.
