### ISSUE TITLE
Add support for scope to salt.states.network

### ISSUE THREAD

**Issue by jozefmares** [saltstack/salt#15324]
According to documentation http://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html and my test there is no support for scope parameter.

Desired network configuration should look like this:

``` bash
DEVICE=eth1
TYPE=Ethernet
ONBOOT=yes
BOOTPROTO=none
IPADDR=MY_IP
NETMASK=MY_NETMASK
SCOPE="peer MY_GW"
```

If I use parameter - scope: in salt file Salt silently ignores this parameter (which is better then fail) but since this parameter is used (for example this hoster uses it: http://wiki.hetzner.de/index.php/Netzkonfiguration_CentOS/en) it would be beneficial to enable Salt manage even this rare scenarios.

Including versions report:

``` yaml
Salt: 2014.1.7
Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
Jinja2: unknown
M2Crypto: 0.20.2
msgpack-python: 0.1.13
msgpack-pure: Not Installed
pycrypto: 2.0.1
PyYAML: 3.10
PyZMQ: 2.2.0.1
ZMQ: 3.2.4
```
