### ISSUE TITLE
RFE: Extend LVM module to support resize

### ISSUE THREAD

**Issue by mickep76** [saltstack/salt#15348]
Currently the LVM module doesn't support resize, if you specify a larger size for an existing volume.

``` yaml
lv_opt:
  lvm.lv_resize:
    - name: /dev/vg_root/lv_opt:
    - size: 10G
```

This would also req. support for resize2fs, maybe in the blockdev module.
