### ISSUE TITLE
`onlyif`` has different result for single condition and a list of this condition (only for undefined?)

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#15351]
`onlyif` accecpts a single condition or a list of conditions. (At least the compiler accepts both)

In the first fragment `onlyif` has a list of one condition.
In the second fragment `onlyif` has a single condition.
The condition is undefined.

*DESIRED BEHAVIOUR:* the result of the two fragements is identical.
*ACTUAL BEHAVIOUR:* Saltstack decides that the list is always true, the single condition always false.

Daniel Jagszent suggested that the first fragment uses "wrong syntax"
https://groups.google.com/d/msg/salt-users/7DlOwfQaLcA/WfIWcFpJNSkJ

Should this be actually the case then:
*DESIRED BEHAVIOUR:* Saltstack rejects "wrong syntax"
*ACTUAL BEHAVIOUR:* Saltstack ignores "wrong syntax"

Disclaimer: I have only tested this for an undefined test, and for Windows.  Someone should use a decidable test.

    always_executed:
      cmd:
        - run
        - cwd: /
        - name: notepad
        - onlyif:
          - test -f /plan/salt/YesTrigger.txt

    never_executed:
      cmd:
        - run
        - cwd: /plan/salt/
        - name: notepad YES.txt
        - onlyif: test -f /plan/salt/YesTrigger.txt

**Comment by oliver-dungey** [comment]
@markuskramerIgitt I've also noticed that it's hard to debug onlyif lists as the logging doesn't tell you which condition failed (or I'm a numpty and don't know what I'm doing, quite possible).

**Comment by oliver-dungey** [comment]
I've just tested the logic again to make sure I know whats going on and it's all looking ok on 2016.3.0

```
test1:
  cmd.run:
  - name: echo 'Test 1 - Should pass onlif test'
  - onlyif: test -d /tmp

test2:
  cmd.run:
  - name: echo 'Test 2 - Should pass onlyif test'
  - onlyif:
    - test -d /tmp

test3:
  cmd.run:
  - name: echo 'Test 3 - Should pass onlyif test'
  - onlyif:
    - test -d /tmp
    - test -d /usr

test4:
  cmd.run:
  - name: echo 'Test 4 - Should fail onlyif test'
  - onlyif:
    - test -d /tmp
    - test -d /bogusdirectory

test5:
  cmd.run:
  - name: echo 'Test 5 - Should fail onlyif test'
  - onlyif:
    - test -d /bogusdirectory
    - test -d /tmp
```

And here are the results (that all look good i.e. no bug):
```
local:
----------
          ID: test1
    Function: cmd.run
        Name: echo 'Test 1 - Should pass onlif test'
      Result: True
     Comment: Command "echo 'Test 1 - Should pass onlif test'" run
     Started: 13:30:02.924822
    Duration: 10.505 ms
     Changes:
              ----------
              pid:
                  10586
              retcode:
                  0
              stderr:
              stdout:
                  Test 1 - Should pass onlif test
----------
          ID: test2
    Function: cmd.run
        Name: echo 'Test 2 - Should pass onlyif test'
      Result: True
     Comment: Command "echo 'Test 2 - Should pass onlyif test'" run
     Started: 13:30:02.935586
    Duration: 8.155 ms
     Changes:
              ----------
              pid:
                  10588
              retcode:
                  0
              stderr:
              stdout:
                  Test 2 - Should pass onlyif test
----------
          ID: test3
    Function: cmd.run
        Name: echo 'Test 3 - Should pass onlyif test'
      Result: True
     Comment: Command "echo 'Test 3 - Should pass onlyif test'" run
     Started: 13:30:02.943966
    Duration: 13.3 ms
     Changes:
              ----------
              pid:
                  10591
              retcode:
                  0
              stderr:
              stdout:
                  Test 3 - Should pass onlyif test
----------
          ID: test4
    Function: cmd.run
        Name: echo 'Test 4 - Should fail onlyif test'
      Result: True
     Comment: onlyif execution failed
     Started: 13:30:02.957531
    Duration: 10.82 ms
     Changes:
----------
          ID: test5
    Function: cmd.run
        Name: echo 'Test 5 - Should fail onlyif test'
      Result: True
     Comment: onlyif execution failed
     Started: 13:30:02.968808
    Duration: 4.76 ms
     Changes:

Summary for local
------------
Succeeded: 5 (changed=3)
Failed:    0
------------
```
