### ISSUE TITLE
Declaring a non-existing function is a fatal error and must halt the salt run (Windows?)  

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#15350]
The below fragment must only call `notepad` when file `/plan/salt/yesTrigger.txt` exists.
In Windows, there is no command `test`, therefore the result is undefined.
Deciding an undefined value is an unsolvable task (like calculating 1/0).
_DESIRED BEHAVIOUR:_ Saltstack ends execution with a fatal error.
_ACTUAL BEHAVIOUR:_ Saltstack decides that undefined means yes.
(Saltstack writes an ERROR to the log, but this really does not matter)

Disclaimer: I only tested this for Windows, someone should test it for UNIX.

```
always_Yes2:
  cmd:
    - run
    - cwd: /
    - name: notepad
    - onlyif:
      - test -f /plan/salt/writeYesTrigger.txt
```
