### ISSUE TITLE
Documentation Error yumpkg - 2014.7.0

### ISSUE THREAD

**Issue by Rucknar** [saltstack/salt#15425]
The yumpkg modules documentation suggests it supports 'enablerepo', however the code only supports 'fromrepo' and as such the feature needs adding or the documents adjusting. 

The initial list of supported commands is correct but the options below are wrong.
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.yumpkg.html#module-salt.modules.yumpkg

**Comment by rallytime** [comment]
@Rucknar Sorry we never circled back around to this one. I just tried this again on the latest stable version, 2014.7.5, and I am not able to reproduce that argument error for `pkg.upgrade` that you were seeing. Are you still running into this? Would you be able to try this again on a newer version?
```
# salt nt-cent7 pkg.upgrade enablerepo=epel-testing
nt-cent7:
    ----------
    NetworkManager:
        ----------
        new:
            1.0.0-14.git20150121.b4ea599c.el7
        old:
            0.9.9.1-28.git20140326.4dba720.el7_0.2
    NetworkManager-adsl:
        ----------
        new:
            1.0.0-14.git20150121.b4ea599c.el7
        old:
    NetworkManager-bluetooth:
        ----------
        new:
            1.0.0-14.git20150121.b4ea599c.el7
        old:

<snipped>

    xz-libs:
        ----------
        new:
            5.1.2-9alpha.el7
        old:
            5.1.2-8alpha.el7
    yum-plugin-fastestmirror:
        ----------
        new:
            1.1.31-29.el7
        old:
            1.1.31-25.el7_0
```
Master Version:
```
# salt --versions
           Salt: 2014.7.5-171-gc399b8f
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
Minion Version, running on CentOS 7:
```
# salt nt-cent7 test.versions_report
nt-cent7:
               Salt: 2014.7.5
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: Not Installed
```
