### ISSUE TITLE
Make file removal in file.managed state

### ISSUE THREAD

**Issue by seblu** [saltstack/salt#15437]
Hello,

I'm using `file.managed` with multiple sources to override files on some minions. I can easily drop a file suffixed by minion id and salt will select it automatically. Here is an example with postfix `master.cf`. 

```
/etc/postfix/master.cf:
    file.managed:
        - source:
            - salt://postfix/master.cf.{{ grains['id'] }}
            - salt://postfix/master.cf
        - user: root
        - group: root
        - mode: 444
        - watch_in:
            - service: postfix
```

That make sls syntax easier to read than:

```
{ % if grains['id'] in ('foo', 'bar', 'baz') %}
bla bla bla
{% endif %}
```

That work like a charm except when a minion must not have this file. In other word, when you want a file only on few minion. Using create=False (from #3944) doesn't help, because it's based on the existence on the minion not on the server. Idem for replace=False.

```
/etc/postfix/main.cf:
    file.managed:
        - source:
            - salt://postfix/master.cf.{{ grains['id'] }}
        - user: root
        - group: root
        - mode: 444
        - watch_in:
            - service: postfix
```

A way would be to change the behavior when an empty (None or ~) source is present, the file should  be removed by the minion.

Another way would be to have a removal argument, which remove the file if the content is empty.
