### ISSUE TITLE
yumpkg tries to downgrade when given a version

### ISSUE THREAD

**Issue by nw0428** [saltstack/salt#15482]
The following state:

```
hive:
  pkg.installed:
    - name: hive
    - version: 0.13.0.2.1.0.0
```

causes salt to run the command:

```
yum -y   downgrade "hive-0.13.0.2.1.0.0"
```

Which fails with:

```
Only Upgrade available on package: hive-0.13.0.2.1.0.0-92.el6.noarch
Nothing to do
```
