### ISSUE TITLE
Calling a boto_route53.present state fails if the record is already there

### ISSUE THREAD

**Issue by flyaruu** [saltstack/salt#15514]
I have a state to create a dns record for my minion:

```
dns:
    boto_route53.present:
        - name: {{grains['id']}}.example.com.
        - value: {{grains['ip_interfaces']['eth0']}}
        - zone: example.com.
        - ttl: 300
        - record_type: A
        - region: eu-west-1
        - keyid: {{pillar['route53']['keyid']}}
        - key: {{pillar['route53']['key']}}
```
If the record does not exist, it works fine, the the record gets created.

If I run the same state again, I get the following error:

```
----------
          ID: dns
    Function: boto_route53.present
        Name: minionid.example.com.
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1517, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/boto_route53.py", line 161, in present
                  _values = [x.rstrip('.') for x in value.split(',')]
              AttributeError: 'list' object has no attribute 'split'
     Started: 11:11:17.224762
     Duration: 495 ms
     Changes:   
```

I guess this is a bug?

regards, Frank
