### ISSUE TITLE
When using git.present, salt $host state.highstate output declares a change every time, even if the repository is present already.

### ISSUE THREAD

**Issue by the-l-a-cat** [saltstack/salt#15517]
When using git, I notice state.highstate output always says:

```
          ID: zsh
    Function: git.present
        Name: https://github.com/zsh-users/zsh-syntax-highlighting
      Result: True
     Comment: Initialized repository https://github.com/zsh-users/zsh-syntax-highlighting
     Changes:   
              ----------
              new repository:
                  https://github.com/zsh-users/zsh-syntax-highlighting
```

This is the relevant sls code:
```
 zsh:
    pkg.installed:
        - require:
            - git: zsh 
    git.present:
        - name: https://github.com/zsh-users/zsh-syntax-highlighting
        - target: /usr/share/zsh/plugins/zsh-syntax-highlighting
```

Of course I mean that repository is already cloned into the correct place with the first iteration of state.highstate call. It does not appear to me that any files are actually being overwritten, as one may suggest looking at the output. I believe the correct behaviour to be to make no changes and indicate that no changes were made, and that currently that indication lies.

```
 # salt-call --versions-report
           Salt: 2014.1.10
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
 # uname -a
 Linux host 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
