### ISSUE TITLE
network.managed state does not restart interface when there are changes

### ISSUE THREAD

**Issue by endragor** [saltstack/salt#15544]
**Environment:**
CentOS 6.4

```
# salt-call --versions-report
           Salt: 2014.1.10
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 2.2.0.1
            ZMQ: 3.2.4
```

**Steps to reproduce:**
I assume you can play with `eth1` interface.

Apply this state:

```
Set one address:
  network.managed:
    - name: eth1
    - enabled: True
    - type: eth
    - proto: none
    - ipaddr: 4.5.6.1
    - netmask: 255.255.255.0

Set another address:
  network.managed:
    - name: eth1
    - enabled: True
    - type: eth
    - proto: none
    - ipaddr: 1.2.3.1
    - netmask: 255.255.255.0
```

It will run successfully and the output will have something like this in the end:

```
----------
          ID: Set another address
    Function: network.managed
        Name: eth1
      Result: True
     Comment: Interface eth1 updated.
     Changes:   
              ----------
              interface:
                  ---  
                  +++  
                  @@ -3,5 +3,5 @@
                   USERCTL="no"
                   BOOTPROTO="none"
                   ONBOOT="yes"
                  -IPADDR="4.5.6.1"
                  +IPADDR="1.2.3.1"
                   NETMASK="255.255.255.0"
```

Now run `ifconfig eth1` and observe that you still have the first address applied, or even the one that you had before applying the state.

**Workaround:**
`ifdown eth1 ; ifup eth1` can be run after applying the state to ensure the new configuration is applied.

**Comment by ssgward** [comment]
@endragor - is this still an issue with the latest salt? If not an issue, can this be closed?

**Comment by spoage** [comment]
@ssgward It is. I would also say that this is probably not that high of a severity, since there's a pretty easy work-around:

```
ifdown-on-changes:
  module.run:
    - name: ip.down
    - iface: eth0
    - iface_type: eth
    - onchanges:
      - network: eth0

ifup-after-ifdown-on-changes:
  module.run:
    - name: ip.up
    - iface: eth0
    - iface_type: eth
    - onchanges:
      - module: ifdown-on-changes
```

In fact, I'd imagine that the raw python equivalent of that is essentially the fix for this issue.
