### ISSUE TITLE
file.recuse with -clean:True doesn't clean with a dependency

### ISSUE THREAD

**Issue by MTecknology** [saltstack/salt#15662]
I have a `file.recurse` state that has `- clean: True` but won't actually clean the directory.

```
"/home/0010":
  file.directory:
    - user: root
    - group: "0010"
    - mode: 755

"/home/shared/0010/Templates":
  file.directory:
    - user: root
    - group: root
    - mode: 775
    - require:
      - file: "/home/shared/0010"

"/home/shared/0010/Templates/Corporate Templates":
  file.recurse:
    - user: root
    - group: root
    - clean: True
    - dir_mode: 755
    - file_mode: 664
    - source: "salt://templates/center_templates/SD_0010_foo_bar"
    - require:
      - file: "/home/shared/0010/Templates"
```

The last state in this list is the issue. It won't actually clean the directory. However, if I remove the require, it works fine.

```
    #- require:
    #  - file: "/home/shared/0010/Templates"
```

^- Remove it, and the directory is cleaned as expected.
