### ISSUE TITLE
Use chocolatey to provide Windows packages

### ISSUE THREAD

**Issue by djs52** [saltstack/salt#15709]
The Chocolatey module on Windows is very useful for installing packages. At the moment, I'm writing states based on `module.run`. It would be more useful if a state function were available to use with it -- preferably as a place that `pkg.installed` looks in addition to winrepo.

**Comment by TheBigBear** [comment]
Is there any progress on this? This would be so great and I wouldn't have to put up with the limitations of the built-in windows winrepo installer. @UtahDave or @jfindlay chocolatey would do such a good job of installing and uninstalling packages under windows.

**Comment by jfindlay** [comment]
@TheBigBear, we have not made any progress on this yet.  I think the vision is, and @UtahDave can correct me, to consider winrepo, chocolatey, and whatever MicroSoft calls their new package system as options for package management on windows.  The exec module that gets used will possibly introspect the system for the presence of chocolatey and microsoft package and prefer one over the other, or a minion config will decide.

**Comment by TheBigBear** [comment]
djs52  what do you mean when you say: "At the moment, I'm writing states based on module.run" I would like to understand how or what you do? Could you give me a sample or two of how your states loook like? How do you bootstrap choclatey onto the windows minions, and how do you then use the chocolatey module to work and apply states that you wrote for them?

**Comment by djs52** [comment]
Something like this (I don't have access to my Salt states any longer to check if this is right):
```
chocolatey:
  module.run:
    - name: chocolatey.bootstrap
    
firefox:
  module.run:
    - unless: # command to check if firefox is already installed
    - name: chocolatey.install 
    - m_name: firefox
    - require:
      - module: chocolatey
```
For the unless, I think I ran `clist -l` to get the list of installed packages, piped to `Where` to see if Firefox is present. Sorry I can't provide more details.
