### ISSUE TITLE
pkgrepo.managed should empty file before adding

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#15730]
If you have a repo, say `repo-2.2` and change the state to install `repo-2.4` instead you end up having one `sources.list` file with both 2.2 and 2.4. 

This may not be desirable, so it would be nice to clean it out prior to putting in the repo line. Since it may not be desirable for everyone (e.g. custom additions) it probably should be an option.

**Comment by boltronics** [comment]
I host a repo on my CI server (which builds to be deployed are automatically packaged and dropped into). When the CI server hostname changes (which happens more often than I'd like with the current setup), pkgrepo.managed on clients accessing the repo does not remove the old entry, causing them to take forever to deploy due to trying to download from a repo that no longer exists.

I've tried working around the issue by using prereq_in to call a file.absent statement on the generated .list file so in theory it is nuked when (and only when) changes are required, but then I seem to hit one of the various prereq-related infinite recursion bugs for reasons I have been unable to determine. The only other option I see is to just not use pkgrepo.managed for the time being.

So in short, +1. :)

**Comment by babilen** [comment]
I don't think that implementing this would be a good idea as it means that manually added sources won't be retained. An approach such as the labeling one taken for cron jobs could be an option, but then it is no problem whatsoever to delete the file in question in a `file.absent` state prior to `pkgrepo.managed` one.

If the latter is not an option because bugs then these should be fixed.

**Comment by boltronics** [comment]
This should be implemented as an option.

Typically this state creates a separate file per repo under /etc/apt/sources.list.d/ - as opposed to changing sources.list. So there is no reason you should be modifying the file this manages by hand or anything else anyway. And if you did and you still wrote a state that used this proposed option, you deserve it. :) No difference to file.managed or a bunch of other states in this respect.

**Comment by Reiner030** [comment]
+1 (option to purge / check whole content)

It would be then same behavior as in other modules - I was also very astonished that my line was added instead substituted. Especially because the backports have e.g a ```deb``` and ```deb-src``` line which couldn't be setup (easy) in parallel.

From other sight it could be also a nice behavior:
```
{{ grains['oscodename'] }}-backports-repo:
  pkgrepo.managed:
    - humanname: Debian Backports Repository
    - name: "deb      {{ debian_mirror }}  {{ grains['oscodename'] }}-backports  main contrib non-free"
    - file: /etc/apt/sources.list.d/backports.list
 
{{ grains['oscodename'] }}-backports-repo-src:
  pkgrepo.managed:
    - humanname: Debian Backports Repository - Sources
    - name: "deb-src  {{ debian_mirror }}  {{ grains['oscodename'] }}-backports  main contrib non-free"
    - file: /etc/apt/sources.list.d/backports.list
```
