### ISSUE TITLE
salt.states.mdadm duplicate information in mdadm.conf

### ISSUE THREAD

**Issue by syava** [saltstack/salt#15801]
Hi.

On my server i have raid1 for root. My mdadm.conf

```
cat /etc/mdadm/mdadm.conf 
ARRAY /dev/md0 metadata=1.0 level=raid1 num-devices=2 UUID=a332ff0b:aabc723b:de9412b6:a8f7b797
```

I create a new raid through salt.
salt config

```
/dev/md2:
  raid.present:
    - unless: 'cat /proc/mdstat | grep "md2 : active"'
    - level: 0
    - devices:
      - /dev/sdc
      - /dev/sdd
    - chunk: 256
    - run: True
```

after run this config in my mdadm.conf, i look

```
cat /etc/mdadm/mdadm.conf 
ARRAY /dev/md0 metadata=1.0 level=raid1 num-devices=2 UUID=a332ff0b:aabc723b:de9412b6:a8f7b797
ARRAY /dev/md0 metadata=1.0 name=agave01e-new:0 UUID=a332ff0b:aabc723b:de9412b6:a8f7b797 ARRAY /dev/md2 metadata=1.2 name=agave01e-new.media.yandex.net:2 UUID=38573362:b0b6bfc9:566972f2:e574536b
```

https://github.com/saltstack/salt/blob/2014.7/salt/modules/mdadm.py
function save_config use information about all raid devices. But need use information only about /dev/md2

```
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise
salt-minion 2014.7.0 (Helium)
salt-master 2014.7.0 (Helium)
```
