### ISSUE TITLE
git.latest does not check for HEAD existence

### ISSUE THREAD

**Issue by tomasfejfar** [saltstack/salt#15833]
````
library:
  git:
  - latest
  - name: 'deploy@loadbalancer:/opt/deploy/library'
  - rev: origin/master
  - force_checkout: True
  - target: /srv/library
  - identity: /root/deploy_private_key
  - always_fetch: True
  - require:
    - file: deploy_private_key
````

If there is no repo in `/opt/deploy/library` repository is still created. But it's empty. On the next run salt calls `rev-parse HEAD` and that fails on empty repo. 

````
[INFO    ] Executing state git.latest for deploy@loadbalancer:/opt/deploy/library
[INFO    ] Executing command 'git rev-parse HEAD' in directory '/srv/library'
[ERROR   ] Command 'git rev-parse HEAD' failed with return code: 128
[ERROR   ] stdout: HEAD
[ERROR   ] stderr: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
[ERROR   ] fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
````
This could be fixed by checking that `rev-parse HEAD` does not fail and if it does assume that there is no HEAD and just checkout. IMO the HEAD call is only needed to display the revision in log. 

````
 salt-call --versions-report
           Salt: 0.17.5
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
````

**Comment by anlutro** [comment]
I tried taking a look at this as it affects my workflow (see [this comment](https://github.com/saltstack/salt/issues/13550#issuecomment-91875580)), but can't seem to track down the piece of the code that does the `git rev-parse` in this case.

**Comment by anlutro** [comment]
Another thing that baffles me is that the following state SLS works fine with `salt-call --local`, but not with `salt-ssh` - running `state.sls test`

```yaml
# /srv/salt/test.sls
/tmp/git_bare:
  git.present:
    - bare: true

/tmp/git_cloned:
  git.latest:
    - name: /tmp/git_bare
    - target: /tmp/git_cloned
```

```
----------
          ID: /tmp/git_bare
    Function: git.present
      Result: True
     Comment: Initialized repository /tmp/git_bare
     Started: 17:30:19.170723
    Duration: 45.812 ms
     Changes:   
              ----------
              new repository:
                  /tmp/git_bare
----------
          ID: /tmp/git_cloned
    Function: git.latest
        Name: /tmp/git_bare
      Result: False
     Comment: Command 'git rev-parse HEAD' failed. Stderr: "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'"
     Started: 17:30:19.219353
    Duration: 112.174 ms
     Changes:   

Summary
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
```

**Comment by tomasfejfar** [comment]
@anlutro - I believe that the rev parse is called here https://github.com/saltstack/salt/blob/develop/salt/modules/git.py#L160 that is in turn called in https://github.com/saltstack/salt/blob/develop/salt/states/git.py#L198 ,,,

**Comment by anlutro** [comment]
Since https://github.com/saltstack/salt/pull/22553 has been merged, this issue should be at least halfway fixed. In any case, I'm able to use `git.latest` with an empty target repository now.

A remaining problem is that you can't pass the `rev` argument when cloning an empty repository because the state uses `git clone --branch` - however, you can't `git clone --branch foo` when the foo branch doesn't exist, it'll spit out an error.

Not sure if this is an issue - after all, you would expect the state to fail if it tries cloning a non-empty repository and the branch doesn't exist.

**Comment by mastrolinux** [comment]
Very similar to my issue. I have a repo and a branch named staging.

in this way:
```

clone_webide:
  git.latest:
    - name: git@github.com:something/repo.git
    - target: {{ salt['pillar.get']('webide:web_root', '/vagrant') }}
    - rev: {{ salt['pillar.get']('webide:git_branch', 'master') }}
    - user: {{ salt['pillar.get']('webide:user', 'vagrant') }}
    - force_checkout: True
    - force_reset: False
    - submodules: True
    - depth: 1
```
It does work but if I use force_resete: True and I never cloned the repo the error is similar to what you have:

```
salt fatal: ambiguous argument: 'origin/staging' unknown revision or path not in the working tree.
```

This is failing if `force_reset: True`
