### ISSUE TITLE
Proposal: onfail vs. onfail_of vs. always_after

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#15886]
Some questions regarding the documentation and suggestions:

When looking through the [documentation for requisites](http://docs.saltstack.com/en/latest/ref/states/requisites.html), we were looking for something like the `finally` clause in the python`try` statement, i.e. some states need to be executed after the execution of another states no matter whether those failed or not.

First, we discovered `onfail` and failed to see whether it would need to be used in the "finally" state or in the "try" state. The documentation suggests it to be in the "finally" state whereas the wording `onfail" suggests the execution of another state when the state where the`onfail` clause is specified fails.

That is contrary to the `require` clause that naturally suggests its correct usage. To us, an `onfail_of` or something equivalent would remedy the salt requisite declaration.

The original problem however could not be solved satisfactorily as we would need to repeat the state requisites:

```
try:
  thing.state

finally:
  thing.state:
    - require:
      - thing: try  <<< for the success case of try
    - onfail:
      - thing: try  <<< for the failure case of try
```

We hope we got that right.

We would rather use something like this:

```
try:
  thing.state

finally:
  thing.state:
    - require:
      - thing: try  <<< for the success case of try
    - onfail_of:
      - thing: try  <<< for the failure case of try
```

Or even better because cleaner:

```
try:
  thing.state

finally:
  thing.state:
    - always_after:
      - thing: try
```

Btw. we are no native English speakers. So, the suggestions of `onfail_of` or `always_after` might sound bit strange and we would be glad if you can offer something better. You might even dismiss this suggestion completely. However, I think you got the idea.
