### ISSUE TITLE
Add execution module for managing ssh key pairs

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#15911]
Related to #15910.

Besides functions related with writing ssh keys into files, I would add a function that extracts public (at least) keys.

Jinja allows insert results of salt execution. The problem is that the state can only contain salt invocations bound to the concrete minion. It would be great to have the ability get public keys from other hosts by using:

```
sshkeys:
  ssh_auth:
    - present
    - user: root
    - enc: ssh-rsa
    - names:
      - {{ salt('another_server')['ssh_key.get']('root') }}
```
