### ISSUE TITLE
Add state module for managing ssh key pairs

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#15910]
There is an `salt.states.ssh_auth` module, that manages authorized keys for ssh server.

I want the reverse. I need to provision ssh key pairs (private and public keys) to the minions. I've found a [recipe](http://serverfault.com/a/548227/156421), but it's not idiomatic in some places and managing ssh keys is good to have in the core.

Content can be supplied using pillars.

To follow DRY, I would suggest to generate public key from the private automatically if it's not specified and there is no paraphrase on a private key or it's supplied as an argument.

So, it could look like (of course, in production private key and passphrase should be retrieved from the pillar):

```
user:
  ssh_key:
    - present
    - private: |
    -----BEGIN RSA PRIVATE KEY-----
    ...
    -----END RSA PRIVATE KEY-----
    - public: PUBLIC_KEY_HERE
    - retrieve_public_from_private: False
    - passphrase: PASSPHRASE_HERE
```
