### ISSUE TITLE
git.latest succeed to checkout a git repo with a specific tag but exit in error

### ISSUE THREAD

**Issue by ticosax** [saltstack/salt#15921]
Hi,
With the following sls:

```yaml
checkout_my_repo:
  git.latest:
    - name: git@github.com:org/a_repo.git
    - rev: v1.0.1
    - target: /srv/a_repo/
    - force_checkout: True
```
Here the rev `v1.0.1` is pointing to git tag.

salt-minion fails when running the command
```
Command 'git config branch.v1.0.1.remote' failed with return code: 1
```
He tries to run this command because on this line https://github.com/saltstack/salt/blob/v2014.7.0rc1/salt/states/git.py#L240
```branch == 'master'```
I do not know what this comparison with `HEAD` means, so I do not know how to fix it correctly.
But what I can say is that if we do not call the block between lines 241 and 255 it goes smoothly.

In fact the the checkout to the specific tag is already performed sucessfuly, just the state exit in error when he tries to change the remote. Something the state is not supposed to perform in this specific use-case.

thx.
```
salt --versions-report
           Salt: 2014.7.0rc1-2084-g03e0b02
         Python: 2.7.5 (default, Feb 11 2014, 14:01:17)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 1.0.0
```
