### ISSUE TITLE
salt-cloud windows minion installation fails

### ISSUE THREAD

**Issue by bkeroack** [saltstack/salt#15984]
Using salt-cloud and the openstack provider (not sure if it is specific to OpenStack), Windows minions do not have salt-minion fully installed.

salt 2014.1.10 (master and minion)
salt-cloud 0.8.11
Windows Server 2012 R2 Server Core
winexe 1.1
smbclient 4.1.6-Ubuntu
Ubuntu 14.04 (master)

After salt-cloud returns, when checking the minion I see the following directories:

C:\salt
C:\salttemp

However C:\salt does not contain all the files that would be expected:

![image](https://cloud.githubusercontent.com/assets/1949804/4342317/4131c3ce-4043-11e4-8984-5ace76213490.png)

When testing to reproduce this issue, in once instance everything was missing under C:\salt except for the conf subdirectory.

In all cases there is no "salt-minion" service, so clearly installation did not complete.

Output from salt-cloud:

```
$ sudo salt-cloud -p qual_consumer sctest005
[WARNING ] /usr/local/lib/python2.7/dist-packages/libcloud/httplib_ssl.py:59: UserWarning: SSL certificate verification is disabled, this can pose a security risk. For more information how to enable the SSL certificate verification, please visit the libcloud documentation.
  warnings.warn(libcloud.security.VERIFY_SSL_DISABLED_MSG)

[WARNING ] /usr/local/lib/python2.7/dist-packages/libcloud/httplib_ssl.py:59: UserWarning: SSL certificate verification is disabled, this can pose a security risk. For more information how to enable the SSL certificate verification, please visit the libcloud documentation.
  warnings.warn(libcloud.security.VERIFY_SSL_DISABLED_MSG)

[WARNING ] Private IPs returned, but not public... Checking for misidentified IPs
[WARNING ] 10.19.76.14 is a private IP
Domain=[WIN-SERVER-TEMP] OS=[Windows Server 2012 R2 Datacenter 9600] Server=[Windows Server 2012 R2 Datacenter 6.3]
Domain=[WIN-SERVER-TEMP] OS=[Windows Server 2012 R2 Datacenter 9600] Server=[Windows Server 2012 R2 Datacenter 6.3]
putting file tmpTSHwK0 as \salt\conf\tmpTSHwK0 (686.5 kb/s) (average 686.5 kb/s)
NT_STATUS_NO_SUCH_FILE listing \salt\conf\pki\minion\minion.pub
Domain=[WIN-SERVER-TEMP] OS=[Windows Server 2012 R2 Datacenter 9600] Server=[Windows Server 2012 R2 Datacenter 6.3]
putting file tmp7AANTt as \salt\conf\pki\minion\tmp7AANTt (390.6 kb/s) (average 390.6 kb/s)
Domain=[WIN-SERVER-TEMP] OS=[Windows Server 2012 R2 Datacenter 9600] Server=[Windows Server 2012 R2 Datacenter 6.3]
sctest005:
    ----------
    _uuid:
        None
    driver:
    extra:
        ----------
        access_ip:
            
        availability_zone:
            nova
        created:
            2014-09-19T21:17:32Z
        disk_config:
            MANUAL
        flavorId:
            ceb18052-fb7a-4903-84c7-1f6ee4841790
        hostId:
            
        imageId:
            c43fb8a0-655f-4017-8402-ab436fa79222
        key_name:
            [redacted]
        metadata:
            ----------
        password:
            [redacted]
        tenantId:
            f84584b9c9a541568dd91ed416673b6d
        updated:
            2014-09-19T21:17:32Z
        uri:
            [redacted]
    id:
        69a3f0d6-b05d-408b-873e-c9708a09bb8a
    image:
        None
    name:
        sctest005
    private_ips:
        - 10.19.76.14
    public_ips:
    size:
        None
    state:
        3
$
```

/etc/salt/cloud:
```
minion:
    master: [redacted]

providers:
    nova_scorebiginc:
        identity_url: http://[redacted]/v2.0/tokens
        compute_name: nova
        compute_region: regionOne
        protocol: ipv4
        tenant: [redacted]
        user: [redacted]
        password: [redacted]
        insecure: true
        provider: openstack
        ssh_key_name: [redacted]
        ssh_key_file: [redacted]
        ssh_interface: private_ips
```

/etc/salt/cloud.profiles:
```
qual_consumer:
    provider: nova_scorebiginc
    image: qual_image_v1.0
    size: w1.medium
    win_installer: /srv/salt/files/win/Salt-Minion-2014.1.10-AMD64-Setup.exe
    win_username: [redacted]
    win_password: [redacted]
```
