### ISSUE TITLE
alt.states.mount mount.mounted mount.swap fails to parse current UUID

### ISSUE THREAD

**Issue by adiroiban** [saltstack/salt#16084]
I have the following state

```
# Was /dev/md0
root-partition:
  mount.mounted:
    - name: /
    - device: UUID=139351d3-d69b-42b6-a21e-0edbca4b5bf6
    - fstype: ext4
    - mkmnt: True
    - opts: relatime,errors=remount-ro
    - persist: True
    - dump: 0
    - pass_nume: 1
```

The partition is already mounted with the right UUID

```
$ mount
/dev/md0 on / type ext4 (rw,relatime,errors=remount-ro)

$ ls -al /dev/disk/by-uuid/139351d3-d69b-42b6-a21e-0edbca4b5bf6 
lrwxrwxrwx 1 root root 9 Sep 21 17:29 /dev/disk/by-uuid/139351d3-d69b-42b6-a21e-0edbca4b5bf6 -> ../../md0
```

When I run the state using salt I get this errro

```
          ID: root-partition
    Function: mount.mounted
        Name: /
      Result: None
     Comment: Unable to unmount
     Changes:   
              ----------
              umount:
                  Forced unmount because devices don't match. Wanted: UUID=139351d3-d69b-42b6-a21e-0edbca4b5bf6, current: /dev/disk/by-uuid/139351d3-d69b-42b6-a21e-0edbca4b5bf6, /dev/md0
```

I am using

```
$ salt-master --version
salt-master 2014.1.10 (Hydrogen)

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise
```

---

I guess the problem is that `/dev/disk/by-uuid/139351d3-d69b-42b6-a21e-0edbca4b5bf6, /dev/md0` is not recognized as equivalent to UUID

---

I get a similar error for swap

```
          ID: swap-partitions
    Function: mount.swap
        Name: UUID=399d7eca-4f8e-4e76-8aad-022f0d4b5e15
      Result: False
     Comment: Swap UUID=399d7eca-4f8e-4e76-8aad-022f0d4b5e15 failed to activate. Updated the entry in the fstab.
     Changes:   
              ----------
              persist:
                  update
```

Thanks!

**Comment by lordcirth** [comment]
I am having trouble reproducing this issue in a VM with an ext4 / on /dev/sda1.  Is it specific to mdadm?

**Comment by adiroiban** [comment]
Thanks!
I have retested and it looks like this is now fixed.

**Comment by adiroiban** [comment]
sorry for the noise... the reported issue is fixed, but I now have a different reason for forcing a remount

```
          ID: root mounting
    Function: mount.mounted
        Name: /
      Result: True
     Comment: Target was already mounted. Entry already exists in the fstab.
     Started: 23:52:51.841912
    Duration: 307.52 ms
     Changes:   
              ----------
              umount:
                  Forced remount because options (relatime,errors=remount-ro) changed
```
