### ISSUE TITLE
saltstack returns error: Package pGina not found in the repository.

### ISSUE THREAD

**Issue by rahele** [saltstack/salt#16093]
I am beginner at salt, and I faced this issue. May anyone help me about it?

---------------------------

in /etc/salt/master:
```
       win_repo: /etc/salt/win/repo/
```

--------------------------

and in  /etc/salt/win/repo/pGina/init.sls:
```
pGina:
  3.1.8.0:
    installer: '/etc/salt/win/repo/pgina/pGinaSetup-3.1.8.0.exe'
    full_name: pGina 3.1.8.0
    locale: en_US
    reboot: False
    install_flags: ' -ms'
```

-----------------------------

and pGinaSetup-3.1.8.0.exe exists in /etc/salt/win/repo/pgina

-----------------------------

/etc/salt/pgina.sls:
```
{% if grains['os'] == 'Windows' %}

  pGina:
    pkg.installed
{% endif %}
```

------------------------------------------

```
[root@centosmaster]# salt 'win8_R2' -t 20 state.sls pgina

win8_R2:
----------
          ID: pGina
    Function: pkg.installed
      Result: False
     Comment: Package pGina not found in the repository.
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
------------
Total:     1
```
