### ISSUE TITLE
State: service mysql start hangs salt-minion indefinitely

### ISSUE THREAD

**Issue by hal58th** [saltstack/salt#16153]
With Salt 2014.1.10, on Ubuntu 14.04.1 LTS, I am experiencing a salt-minion hang when it tries to start or restart the mysql server. mysql server does actually start, but salt-minion does not realize this and hangs indefinitely. Also seems to have a problem when installing mysql-server as well (most likely because it is trying to start mysql).

This occurs only on mariadb-server-5.5=5.5.39-0ubuntu0.14.04.1.
This problem did not occur on mariadb-server-5-5=5.5.37-0ubuntu0.14.04.1

It seems to be related to a new init script that uses this line in the new package:
/usr/bin/mysqld_safe "${@:2}" 2>&1 >/dev/null | $ERR_LOGGER &

When I reverted this line to 5.5.37 package, the salt minion was able to start mysql server successfully and not hang:
/usr/bin/mysqld_safe "${@:2}" > /dev/null 2>&1 &

Salt-minion trace log (I had manually stopped mysql before I ran salt-minion):

[INFO    ] Completed state [mariadb_pkg] at time 23:28:24.314029
[INFO    ] Running state [mysql] at time 23:28:24.315703
[INFO    ] Executing state service.running for mysql
[INFO    ] Executing command 'runlevel /run/utmp' in directory '/home/vagrant'
[INFO    ] output: N 2
[INFO    ] Executing command 'service mysql status' in directory '/home/vagrant'
[ERROR   ] Command 'service mysql status' failed with return code: 3
[ERROR   ] output:  \* MariaDB is stopped.
[INFO    ] Executing command 'service mysql start' in directory '/home/vagrant'
***\* Process is hung ****

Results of command ps xa:
6405 pts/2    Sl+    0:02 /usr/bin/python /usr/bin/salt-call state.sls common/mariadb/v5539/init -l trace
 6495 pts/2    Z+     0:00 [mysql] <defunct>
 6524 pts/2    S+     0:00 /bin/bash /usr/bin/mysqld_safe
 6525 pts/2    S+     0:00 logger -p daemon.err -t /etc/init.d/mysql -i
 6884 pts/2    Sl+    0:00 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql/error.log

/var/log/mysql/error.log shows no errors occuring at all and successfully starting mysql.

If I change the line in the init script as mentioned above, here is the salt-minion trace log:
[INFO    ] Completed state [mariadb_pkg] at time 18:01:40.700255
[INFO    ] Running state [mysql] at time 18:01:40.701251
[INFO    ] Executing state service.running for mysql
[INFO    ] Executing command 'runlevel /run/utmp' in directory '/home/vagrant'
[INFO    ] output: N 2
[INFO    ] Executing command 'service mysql status' in directory '/home/vagrant'
[ERROR   ] Command 'service mysql status' failed with return code: 3
[ERROR   ] output:  \* MariaDB is stopped.
[INFO    ] Executing command 'service mysql start' in directory '/home/vagrant'
[INFO    ] output:  \* Starting MariaDB database server mysqld
   ...done.
- Checking for corrupt, not cleanly closed and upgrade needing tables.
  [INFO    ] {'mysql': True}
  [INFO    ] Completed state [mysql] at time 18:01:44.589836

Packages installed:
ii  libmariadbclient18:amd64    5.5.39-0ubuntu0.14.04.1   amd64     MariaDB database client library
ii  mariadb-client-5.5      5.5.39-0ubuntu0.14.04.1    amd64     MariaDB database client binaries
ii  mariadb-client-core-5.5    5.5.39-0ubuntu0.14.04.1     amd64     MariaDB database core client binaries
ii  mariadb-common    5.5.39-0ubuntu0.14.04.1     all       MariaDB common metapackage
ii  mariadb-server-5.5    5.5.39-0ubuntu0.14.04.1    amd64     MariaDB database server binaries
ii  mariadb-server-core-5.5    5.5.39-0ubuntu0.14.04.1     amd64     MariaDB database core server files
ii  libmysqlclient18:amd64     5.5.38-0ubuntu0.14.04.1     amd64    MySQL database client library
ii  mysql-common    5.5.38-0ubuntu0.14.04.1     all    MySQL database common files, e.g. /etc/mysql/my.cnf

Salt-state file:
mariadb_pkg:
   pkg.installed:
     - pkgs:
        - mariadb-server-5.5

mariadb_service:
  service.running:
- name: mysql
- require:
  - pkg: mariadb_pkg

**Comment by syphernl** [comment]
I am seeing the same with `kerio-connect`. 

The restart process for this process normally takes about 15 seconds, but when executed via Salt-minion it seems to never end.

If I then manually restart the process in a separate ssh session the minion catches on and assumes that it successfully restarted the process, resumes the highstate and finishes with a success.

**Comment by syphernl** [comment]
Its pretty odd. It works fine, except when Salt does it. Here is a strace of the Salt-minion process during a hanging `service.restart` (via watch):

```
root@keriomail:~# strace -p 2726
Process 2726 attached - interrupt to quit
read(36, ".", 4)                        = 1
read(36, "\n *", 3)                     = 3
fstat(36, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
lseek(36, 0, SEEK_CUR)                  = -1 ESPIPE (Illegal seek)
read(36, " Stopping K", 11)             = 11
fstat(36, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
lseek(36, 0, SEEK_CUR)                  = -1 ESPIPE (Illegal seek)
read(36, "erio Connect\n", 13)          = 13
fstat(36, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
lseek(36, 0, SEEK_CUR)                  = -1 ESPIPE (Illegal seek)
read(36, " * Starting Ke", 14)          = 14
--- SIGCHLD (Child exited) @ 0 (0) ---
fstat(36, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
lseek(36, 0, SEEK_CUR)                  = -1 ESPIPE (Illegal seek)
read(36, "rio Connect\n", 16)           = 12
read(36, 
```

If I strace the actual `service kerio-connect restart` I do see it ending properly with an exit 0:
```
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 3529
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f75799b49d0) = 3648
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 3648
close(4)                                = 0
read(3, "3516\n", 128)                  = 5
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 3648
stat("/var/run/kms.pid", {st_mode=S_IFREG|0600, st_size=5, ...}) = 0
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f75799b49d0) = 3649
close(4)                                = 0
read(3, "3516\n", 128)                  = 5
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 3649
--- SIGCHLD (Child exited) @ 0 (0) ---
rt_sigreturn(0x11)                      = 3649
write(1, " * Starting Kerio Connect\n", 26) = 26
stat("/var/lock/subsys", 0x7ffcb9a3aa90) = -1 ENOENT (No such file or directory)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f75799b49d0) = 3650
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f75799b49d0) = 3651
exit_group(0)                           = ?
Process 3494 detached
```

I have tried rewriting their (excessively long/complex) init script to something easier. Even tried a second init-script which calls the first one but no luck with that either.

**Comment by luispollo** [comment]
I have the same issue with Salt 2014.7.2 and MySQL 5.6.26 on Debian Wheezy. Restarts were working OK with MySQL 5.5, but after upgrading I started seeing this problem.

Does anybody have a workaround?

**Comment by pidydx** [comment]
@syphernl Were you ever able to find a solution?  I am running into this exact problem with Kerio.

**Comment by pidydx** [comment]
Also, for the record I got around these problems by using /usr/sbin/policy-rc.d to prevent newly installed services from starting and then using cmd.run to use 'at now' to schedule the init script for an immediate run.

**Comment by syphernl** [comment]
@pidydx No I haven't found any workaround that works with Kerio. I had to disable the whole service restarting, which is suboptimal but I rather have that instead of hanging/broken processes..

**Comment by peter-slovak** [comment]
My workaround consists of prefixing every "$ERR_LOGGER" in /etc/init.d/mysql with "tee". This way the error log gets propagated to Salt minion (subprocess doesn't steal its the output) and it is still logged wherever `logger` redirects it. 

Example:
```bash
/usr/bin/mysqld_safe "${@:2}" 2>&1 >/dev/null |  $ERR_LOGGER &
```
becomes
```bash
/usr/bin/mysqld_safe "${@:2}" 2>&1 >/dev/null |  tee $ERR_LOGGER &
```

**Comment by CMeza99** [comment]
If this is helpful for anyone, this is my workaround for right now on Ubuntu 14.04:

`mariadb.sls`:
``` yaml
mariadb_file_policy-rc_create:
  file.managed:
    - name: /usr/sbin/policy-rc.d
    - user: root
    - group: root
    - mode: 555
    - replace: false

mariadb_file_policy-rc_modify:
  file.prepend:
    - name: /usr/sbin/policy-rc.d
    - text: '[ -n "$1" ] && [ "$1" = "mysql" ] && exit 101'
    - require:
      - file: mariadb_file_policy-rc_create

mariadb_debconf_utils:
  pkg.installed:
    - name: debconf-utils

mariadb_debconf:
  debconf.set:
    - name: mariadb-server-5.5
    - data:
        'mysql-server/root_password_again': {'type': 'password', 'value': 'root'}
        'mysql-server/root_password': {'type': 'password', 'value': 'root'}
    - require:
      - pkg: mariadb_debconf_utils

mariadb-packages:
  pkg.installed:
    - name: mariadb-server
    - require:
      - debconf: mysql_debconf
      - file: mariadb_file_policy-rc_modify

mysql-service:
  service.running:
    - name: mysql
    - enable: True
    - require:
      - pkg: mariadb-server
```

**Comment by CMeza99** [comment]
for what it's worth this is my workaround for MariaDB 5.5.49 on Ubuntu 14.04:

Prevent MariaDB from starting automaticly:
```yaml
mysql_file_policy-rc_create:
  file.managed:
    - name: /usr/sbin/policy-rc.d
    - user: root
    - group: root
    - mode: 555
    - replace: false

mysql_file_policy-rc_modify:
  file.prepend:
    - name: /usr/sbin/policy-rc.d
    - text: '[ -n "$1" ] && [ "$1" = "mysql" ] && exit 101'
    - require:
      - file: mysql_file_policy-rc_create
```

Before starting the service, fix `/etc/init.d/mysql`:
```yaml
mysqld_initd:
  file.line:
    - name: /etc/init.d/mysql
    - content: '/usr/bin/mysqld_safe "${@:2}" >/dev/null 2>&1 | $ERR_LOGGER &'
    - match: '/usr/bin/mysqld_safe "${@:2}" 2>&1 >/dev/null | $ERR_LOGGER &'
    - mode: replace
    - indent: true
```
