### ISSUE TITLE
Extend watch to allow for arbitrary restart command and tests

### ISSUE THREAD

**Issue by rysch242** [saltstack/salt#1616]
I'm not sure if it's possible to do this with some sort of a require and a cmd state, but... 

It'd be nice if we could specify an arbitrary command for watch to execute when it detects changes, this is sort of in the same spirit as Issue #1122, but even more open than just a simple reload. I'm thinking something like:

```
named:
  service:
    - running
    - enable: True
    - watch:
      - file: /etc/named.conf
      - cmd: /usr/sbin/rndc reload
```

In addition, it'd be great if the watch functionality could be extended to also include tests. 

The use case I'm looking at is when configuration is being managed by multiple parties through something like a git repo, we'd want to be able to run some tests before kicking off the restart to ensure that the configuration is valid before we try to restart the service.

```
named:
  service:
    - running
    - enable: True
    - watch:
      - file: /var/named/chroot/cf/named.conf
      - cmd: /usr/sbin/rndc reload
      - test: /usr/sbin/named-checkconf -t /var/named/chroot /cf/named.conf
```

Maybe with some fancy config manipulation I could achieve these, but I see a few places where this sort of thing could be handy if it's not already implemented somehow.
