### ISSUE TITLE
Can't find a way to authenticate for pillars in a git over ssh with gitfs

### ISSUE THREAD

**Issue by arthurlutz** [saltstack/salt#16176]
Hi,

Am setting up gitfs with an ssh access. The publickey works fine for gitfs_remotes : 

```
gitfs_remotes:
  - ssh://git@server.local/home/git/states:
    - pubkey: /root/.ssh/id_rsa_gitfs.pub
    - privkey: /root/.ssh/id_rsa_gitfs
```
but the ext_pillar doesn't seem to give the same possibility : 

http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#using-git-as-an-external-pillar-source

I tried using the .ssh/config trick but that doesn't seem to work (using a different name stored in /etc/hosts so as to enable "normal" ssh as usual between the two servers)

```
ext_pillar:
  - git: master ssh://git@gitfs.local/home/git/pillars
```
