### ISSUE TITLE
Support for paths with spaces in fstab.

### ISSUE THREAD

**Issue by dumol** [saltstack/salt#16208]
In Linux, when specifying a path containing spaces in `/etc/fstab`, the convention is to replace the spaces with `\040`. Currently, there doesn't seem to be any support for that in `salt.states.mount` as of version 2014.1.10.

Considering the following on a minion:

```
# cat /etc/fstab | tail -n 1
/home   /tmp/test\040mount  none    bind 0 0
# mount | tail -n 1
/home on /tmp/test mount type none (rw,bind)
```

The state:

```
test-mount:
  mount.mounted:
    - name: /tmp/test\\040mount
    - device: /home
    - fstype: none
    - opts: bind
    - mkmnt: False
    - persist: True
```

returns:

```
          ID: test-mount
    Function: mount.mounted
        Name: /tmp/test\\040mount
      Result: False
     Comment: mount: mount point /tmp/test\040mount does not exist
     Changes:   
```
