### ISSUE TITLE
Add an option for the onfail requisite to not report a failure

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#16291]
If an onfail requisite provides some mitigation for the failure we should have an option to not count the original failure as a fail.

**Comment by arthurlogilab** [comment]
@whiteinge @cachedout this feature would be really nice. Indeed naming is a difficult part of the job. 

@whiteinge I'm not sure what you mean about the reload in mod_watch. 

What about, for ``onfail_in`` : 

```onfail_in_but_report_ok_if : 
    - plan_b_that_succeeds
```

or for ``onfail`` : 

``` 
onfail_but_fails_reports_as_ok:
   - plan_a_that_fails
```

**Comment by whiteinge** [comment]
The [service mod_watch function accepts arguments](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.service.html#salt.states.service.mod_watch). E.g.,

```yaml
restart_stuff:
  service.restart:
    - watch: another_state
    - reload: True  # graceful reload instead of a restart
```

On onfail equivalent could be:

```yaml
recover_after_failure:
  some.recovery-action:
    - onfail: another_state
    - catch_error: True  # set result to True on the watched state because we fixed the error
```

**Comment by vernondcole** [comment]
Me, too!   I was about to write this up as a bug, rather than an enhancement request. Recovered failures are not failures. For example, attempting to stop a service which has never been installed. I wrote several scripts like:...
```
provision_dynamux_a:
  service.dead:
    - name: rabbitmq-server
    - onfail:
      - p_d_a_ignore_failures
p_d_a_ignore_failures:
  test.nop
```
but, of course, that did not work as I had hoped.
For my purposes, something like the following would work, and be simpler to use and to implement:...
```
provision_dynamux_a:
  service.dead:
    - name: rabbitmq-server
    - ignore_failures: true
```

**Comment by whiteinge** [comment]
I vaguely recall this was addressed...in #39874 perhaps? Looks like it wasn't documented/announced, if so. I don't have an env handy to verify -- do you mind trying the following syntax?

```
some_id:
  some.state:
    - onfail_stop: False
    - onfail:
      - other_id
```
