### ISSUE TITLE
Docs: fix ret value in reactor 

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#16348]
See: http://docs.saltstack.com/en/latest/topics/reactor/#a-complete-example

It seems that now returners are specified as:
```
highstate_run:
  cmd.state.highstate:
    - tgt: {{ data['id'] }}
    - ret: smtp
```
but not:
```
highstate_run:
  cmd.state.highstate:
    - tgt: {{ data['id'] }}
    - ret: smtp_return
```
