### ISSUE TITLE
publish.publish completely unreliable in 2014.7 branch

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#16510]
My version info:

```
cass02:
               Salt: 2014.7.0rc3-44-gfecb0df
             Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
             Jinja2: unknown
           M2Crypto: 0.20.2
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.4
               Mako: Not Installed
```

The pertinent part of my master config:

```
peer:
  boucha:
    - test.*
      - network.*
  .*:
    - network.*
```

I'm running commands such as the following:

```
salt-call publish.publish 'cass*' network.ip_addrs eth0
```

and

```
 salt-call publish.publish 'roles:seed' network.ip_addrs eth0 grain
```

Sometimes I get one item in the response, when there should be three. More often than not I get an empty response. It feels like salt-call is returning before the results are available.
