### ISSUE TITLE
NTP service.running returns different results output

### ISSUE THREAD

**Issue by cameronsparr** [saltstack/salt#16626]
Here is the salt state that I'm running:

```
# Turn on the NTP service:
ntp-service:
    service.running:
        - name: ntp
        - enable: True
        - watch:
            - file: /etc/ntp.conf
```

After this has been run once and everything is configured, this state will sometimes return (yaml output):

```
service_|-ntp-service_|-ntp_|-running:
    __run_num__: 16
    changes:
      ntp: true
    comment: Service ntp is already enabled, and is running
    name: ntp
    result: true
```

And sometimes return:

```
service_|-ntp-service_|-ntp_|-running:
    __run_num__: 16
    changes: {}
    comment: Service ntp is already enabled, and is in the desired state
    name: ntp
    result: true
```

Note how sometimes 'changes' is empty, and sometimes it is not. Also the comment field changes.
