### ISSUE TITLE
Local file returner

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#16644]
I am running 

```
salt-call --out highstate_stats_json --out-file=/tmp/stats state.highstate test=True
```
and would like to stick that in a scheduler instead of a cron. 

```
schedule:
    highstate-stats:
        function: state.highstate
        kwargs:
          test: True
        hours: 6
```

is there a way with existing code with args or kwargs ? 

If not am trying to write a file returner but am having trouble re-using the outputter that already works for running the command with the standard returner.
