### ISSUE TITLE
More info for pkg.install (feature request)

### ISSUE THREAD

**Issue by ze42** [saltstack/salt#16650]
Hello,

(based on Debian packages, ideas could probably also be implemented for other systems)
# Current state

How it works actualy, presenting what I miss.
## Upgrade the system:

```
salt xxx pkg.upgrade
```

It directly upgrades the whole system.

```
salt xxx pkg.list_upgrades
```

List all packages that would be installed on upgrade, but without information about which packet would be removed, if the packet is new, or what was the previous version.
## Install a package

```
salt xxx pkg.install mynicepackage
```

Install it. No idea if it would also upgrade other packages, install new ones, or remove some we would like to keep.
# What I made

I started working on it for our purpose. It is on a stand-alone module, and not
completly compatible.
## List upgrades

(output edited for example purpose)

```
salt --out yaml xxx pkgup.list_upgrades
xxx:
  pkgs:
    bind9-host:
      misc: Debian Backports:/wheezy-backports [amd64]
      new: 1:9.9.5.dfsg-4~bpo70+1
      old: 1:9.8.4.dfsg.P1-6+nmu2+deb7u2
    bind9utils:
      misc: Debian Backports:/wheezy-backports [amd64]
      new: 1:9.9.5.dfsg-4~bpo70+1
      old: 1:9.8.4.dfsg.P1-6+nmu2+deb7u2
    libwireshark5:
      misc: Debian Backports:/wheezy-backports [amd64]
      new: 1.12.1+g01b65bf-1~bpo70+1
      old: ''
    qemu-user:
      misc: ''
      new: ''
      old: 1.1.2+dfsg-6a+deb7u4
  summary:
    kept: 2
    new: 1
    remove: 1
    upgrade: 2
```

Full list of packages that would be upgraded/installed/removed. Possibility to parse it and check we would not break anything.
## List changes for install

```
salt --out yaml xxx pkgup.list_install wireshark
xxx:
  pkgs:
    tshark:
      misc: Debian Backports:/wheezy-backports [amd64]
      new: 1.12.1+g01b65bf-1~bpo70+1
      old: 1.8.2-5wheezy11
    wireshark:
      misc: Debian Backports:/wheezy-backports [amd64]
      new: 1.12.1+g01b65bf-1~bpo70+1
      old: 1.8.2-5wheezy11
    wireshark-common:
      misc: Debian Backports:/wheezy-backports [amd64]
      new: 1.12.1+g01b65bf-1~bpo70+1
      old: 1.8.2-5wheezy11
  summary:
    kept: 2
    new: 0
    remove: 0
    upgrade: 3
```

Allows to see what would be taken along if we install/upgrade a package.
# My code

https://github.com/ze42/salt/blob/pkgup/salt/modules/pkgup.py

Of course, to such functions in salt, it would need to be directly included in the aptpkg module. Probably handle more options.

The list_upgrades result changes, changing it directly would break existing programs. Any suggestion on how to include more results without breaking it?
- add an option with a default value to still return the previous status
- add a new function to get the detail

All feedbacks are welcome.
