### ISSUE TITLE
debconf.set hides passwords on a state run but reveals them with test=true

### ISSUE THREAD

**Issue by djs52** [saltstack/salt#16672]
Running Salt 2014.1.11. I have state that sets the MySQL root password using `debconf.set`. When run with `state.highstate`, I see

```
          ID: mysql_debconf
    Function: debconf.set
        Name: mysql-server
      Result: True
     Comment: Unchanged answers: mysql-server/start_on_boot
     Changes:   
              ----------
              mysql-server/root_password:
                  (password hidden)
              mysql-server/root_password_again:
                  (password hidden)
```

but with `state.highstate test=true`:

```
          ID: mysql_debconf
    Function: debconf.set
        Name: mysql-server
      Result: None
     Comment: Unchanged answers: mysql-server/start_on_boot
     Changes:   
              ----------
              mysql-server/root_password:
                  New value: seekritpassword
              mysql-server/root_password_again:
                  New value: seekritpassword
```

It would be nice to hide the password in both cases.
