### ISSUE TITLE
Docker CMD options

### ISSUE THREAD

**Issue by acasanova** [saltstack/salt#16678]
I'm trying to utilize docker's CMD option when running a container. I'm guessing `command` is the field I should utilize for this. I can't find any docs on this. I'm running salt 2014.1.11 on a Centos 6.5 host machine.

The docker image is a golang web server
````
EXPOSE 8000
CMD []
ENTRYPOINT ["/gopath/src/com.me/leoadmin/leoadmin_linux"]
````

Here is my sls file

````
{% set appname  = 'leoadmin' %}
{% set hostport = '8087' %}
{% set privaterepo = '192.168.254.96:5000' %}

mypkgs:
  pkg.installed:
    - pkgs:
      - git
      - docker-io
      - vim-enhanced
      - python-docker-py

docker:
  service:
    - running

{{appname}}-image:
  docker.pulled:
    - name: {{privaterepo}}/{{appname}}
    - tag: latest
    - force: True

{{appname}}-stop:
  docker.absent:
    - name: {{appname}}
    - require:
      - docker: {{appname}}-image

{{appname}}-container:
  docker.installed:
    - name: {{appname}}
    - hostname: {{appname}}
    - image: {{privaterepo}}/{{appname}}
    - require:
      - docker: {{appname}}-image
      - docker: {{appname}}-stop

{{appname}}-running:
  docker.running:
    - container: {{appname}}
    - port_bindings:
        "8087/tcp":
            HostPort: {{hostport}}
    - command:
        - "-APIKey=XYZKEY -apiurl=https://syxty.com/api"

````
