### ISSUE TITLE
service.running says that service is running when it isn't

### ISSUE THREAD

**Issue by johtso** [saltstack/salt#16677]
Hope I'm not doing something really stupid here..

I have a simple nginx state that looks like this:

``` yaml
nginx_server:
  pkg.installed:
    - name: nginx
  service.running:
    - name: nginx
    - enable: True
    - watch:
      - file: /etc/nginx/nginx.conf
      - file: /etc/nginx/conf.d/*
    - require:
      - pkg: nginx
      - file: /etc/nginx/nginx.conf
  file.managed:
    - name: /etc/nginx/nginx.conf
    - source: salt://nginx/files/nginx.conf
```

When I check the status of the service I get this output:

```
sudo salt-call service.status nginx
[INFO    ] Executing command 'service nginx status' in directory '/home/vagrant'
[ERROR   ] Command 'service nginx status' failed with return code: 3
[ERROR   ] output:  * nginx is not running
local:
    False
```

But when I run the state I get this output:

```
          ID: nginx_server
    Function: service.running
        Name: nginx
      Result: True
     Comment: Service nginx is already enabled, and is running
     Started: 14:34:38.720573
    Duration: 80.728 ms
     Changes:
              ----------
              nginx:
                  True
```

Here's a versions report:

```
           Salt: 2014.7.0-n/a-9da5d13
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```
