### ISSUE TITLE
file.managed fails with "Unable to manage file: Objects of type 'int' can not be converted to Unicode."

### ISSUE THREAD

**Issue by breskeby** [saltstack/salt#16707]
I'm unable to get a file.managed state working with salt version _2014.1.7_ for our windows boxes. the sls file looks like this:

```
tcagent3-user:
  user:
    - present
    - name: tcagent3
    - passwd: tcagent3
    - groups:
        # German administrators group are used
        - Administratoren
    - system: True

  file:
    - managed
    - name: C:\tcagent3\gradle\init.gradle
    - source: salt://common/build-agents/init.gradle
    - user: tcagent3
    - makedirs: True
```

The file.managed state fails with comment

```
     Comment: Unable to manage file: Objects of type 'int' can not be converted to Unicode.
```

The init.gradle file looks like this:

```
// The purpose of this script is to error if we are running a “test” build from a Gradle integration test
// These tests should not be using the default ~/.gradle dir
projectsLoaded {
  if (
    parent == null && // ignore child builds, like buildSrc
    rootProject.name != "gradle"
  ) {
    def sentinelFileName = "intTestHomeDir" // the name of a directory that we only expect to exist at the top of the Gradle source tree

    def dir = rootProject.projectDir.parentFile
    while (dir != null) {
      if (new File(dir, sentinelFileName).isDirectory()) {
        throw new Exception("Project $rootProject.projectDir appears to be part of a Gradle integration test and is trying to use '$gradle.gradleUserHomeDir' as the Gradle User Home dir")
      }
      dir = dir.parentFile
    }   
  }
}
```
