### ISSUE TITLE
Files in configured Windows Repository not reachable with salt://win/repo/

### ISSUE THREAD

**Issue by myg0v** [saltstack/salt#16714]
Master OS: CentOS 6
Minion OS: Windows Server 2008R2
Salt version: 2014.1.10

I uncomment the following line in /etc/salt/master and restarted the salt-master
````
win_repo: '/srv/salt/win/repo'
````
I copied my unzip.exe and some other installer .zip files into this repository directory.

If I execute my test.sls file with the following formula I receive an error.
````
prepare-copy_unzipper:
  file.managed:
    - name: C:/tmp/Tools/unzip.exe
    - source: salt://win/repo/unzip.exe
    - makedirs: True
````

If I use the salt://win/repo directory as source for file.managed:
````
         ID: prepare-copy_unzipper
    Function: file.managed
        Name: C:/tmp/Tools/unzip.exe
      Result: False
     Comment: Source file salt://win/repo/unzip.exe not found
     Changes:   
````

Normally the windows repository is only made for for .msi software packages because they are easy to install. But my installers are all in different .zip files and are not in the wonderful easy to use .msi-format.

So I only want to use this /srv/salt/win/repo as software repository for all my .zip software packages. 

Why the files in the /srv/salt/win/repo are not available with salt://win/repo?
 
My workaround is now as follows:
added now win_repo to my file_roots in /etc/salt/master
````
  win_repo:
    - /srv/salt/repo/win
````
and access the files in this directory with:
````
copy_unzipper:
  file.managed:
    - name: C:/tmp/Tools/unzip.exe
    - source: salt://unzip.exe?saltenv=win_repo
    - makedirs: True
````
It's not pretty but functional.
