### ISSUE TITLE
latest windows salt-minion 2014.1.11 reporting jinja error where previous versions did not.

### ISSUE THREAD

**Issue by emmellee** [saltstack/salt#16727]
upgraded to 2014.1.11 from 2014.1.0 and received the following error:

```
[CRITICAL] Rendering SLS "base:slave" failed: Jinja variable 'dict object' has
o attribute 'TSF'; line 89

---
[...]
    - reload: True
    - require:
      - cmd: Create-{{slaveServiceDisplay}}
      - cmd: Change-{{slaveServiceDisplay}}-Startname
    - watch:
      - file: {{slaveBaseDir}}\jenkins-slave.xml    <======================
---
local:
    Data failed to compile:
----------
    Rendering SLS "base:slave" failed: Jinja variable 'dict object' has no attr
bute 'TSF'; line 89
```

reverted to 2014.1.1, no error, same (unchanged) content in state file:
```
{{slaveBaseDir}}\jenkins-slave.xml:
  file:
    - managed
    - template: jinja
    - source: salt://templates/jenkins-slave/jenkins-slave.xml
    - context:
      EXECUTABLE: 'C:\Program Files (x86)\Java\jre7\bin\java.exe'
      BASE: {{slaveBaseDir}}
      SERVICE_NAME: {{slaveServiceName}}
      DISPLAYNAME:  {{slaveServiceDisplay}}
      DESCRIPTION: 'This service runs a slave for Jenkins continuous integration system.'
      TS: {{ pillar['TSF'] }}
      TSPW: {{ pillar['TSP'] }}
      HOSTNAME: {{ pillar['hostname'] }}
      JENKINSURL: {{ pillar['jenkinsurl'] }}
      SLAVESECRET: {{ pillar['slavesecret'] }}
    - require: 
      - file: {{slaveBaseDir}}
```
