### ISSUE TITLE
git.latest and user leads to error

### ISSUE THREAD

**Issue by gpkvt** [saltstack/salt#16927]
When using git.latest together with user:

```
https://github.com/robbyrussell/oh-my-zsh.git:
    git.latest:
        - target: /myuser/.oh-my-zsh
        - rev: master
        - user: myuser
```
you will get an error:

```Environment could not be retrieved for User 'myuser'```

Without user:

```
https://github.com/robbyrussell/oh-my-zsh.git:
    git.latest:
        - target: /myuser/.oh-my-zsh
        - rev: master
```

everything works fine
