### ISSUE TITLE
Salt's Schedule function does not function correctly.

### ISSUE THREAD

**Issue by fractalram** [saltstack/salt#16989]
I am trying to schedule the running of a python script every minute using salt's schedule function.

The version of my salt-master is : salt-master 2014.7.0rc2 (Helium) and I am targeting a single minion running on the same machine with the same version.

My /etc/salt/master config has this :

```
schedule:
  job1:
    function: cmd.run
    args:
      - '/root/generate_status.py'
    seconds: 60
```
After restarting the master, I see this line in the master's log :

```2014-10-28 16:15:11,256 [salt.utils.schedule                         ][INFO    ] Invalid function: cmd.run in job job1. Ignoring.```
