### ISSUE TITLE
memory leak in master schedule

### ISSUE THREAD

**Issue by mgwilliams** [saltstack/salt#17006]
When running the following schedule, memory is leaked at a rate of approximately 200-300k per iteration:

```
$ cat /etc/salt/master.d/schedule.conf 
```
```yaml
schedule:
  test:
    function: test.arg
    seconds: 2
```

This was tested on 2014.7.0rc6-75-g0d0f2dd.
