### ISSUE TITLE
Salt not detecting some KVM VMs properly

### ISSUE THREAD

**Issue by ALinuxNinja** [saltstack/salt#17090]
For some reason, Salt is not detecting that my Vultr VPS is actually a KVM server and detects it as a physical machine.

Output of grains.items
```
Melanie:
  biosreleasedate: 04/01/2014
  biosversion: rel-1.7.5-0-ge51488c-20140602_164612-nilsson.home.kraxel.org
  cpu_flags: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm xsaveopt fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm
  cpu_model: Vultr Virtual CPU 2
  cpuarch: x86_64
  defaultencoding: None
  defaultlanguage: None
  domain: 
  fqdn: Melanie
  fqdn_ip4:
      127.0.0.1
  fqdn_ip6:
  gpus:
      {'model': 'SVGA II Adapter', 'vendor': 'unknown'}
  host: Melanie
  hwaddr_interfaces: {'lo': '00:00:00:00:00:00', 'eth0': '52:54:00:fd:04:dc', 'eth1': '52:54:00:aa:d6:da', 'tap0': '96:8a:52:0a:a9:5a'}
  id: Melanie
  ip_interfaces: <snip>
  ipv4:
<snip>
  ipv6:
<snip>
  kernel: Linux
  kernelrelease: 3.13.0-37-generic
  localhost: Melanie
  lsb_distrib_codename: trusty
  lsb_distrib_description: Ubuntu 14.04.1 LTS
  lsb_distrib_id: Ubuntu
  lsb_distrib_release: 14.04
  manufacturer: QEMU
  master: 167.160.167.225
  mem_total: 741
  nodename: Melanie
  num_cpus: 1
  num_gpus: 1
  os: Ubuntu
  os_family: Debian
  osarch: amd64
  oscodename: trusty
  osfinger: Ubuntu-14.04
  osfullname: Ubuntu
  osrelease: 14.04
  path: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
  productname: Standard PC (i440FX + PIIX, 1996)
  ps: ps -efHww
  pythonpath:
      /usr/bin
      /usr/lib/python2.7
      /usr/lib/python2.7/plat-x86_64-linux-gnu
      /usr/lib/python2.7/lib-tk
      /usr/lib/python2.7/lib-old
      /usr/lib/python2.7/lib-dynload
      /usr/local/lib/python2.7/dist-packages
      /usr/lib/python2.7/dist-packages
  pythonversion: 2.7.6.final.0
  saltpath: /usr/lib/python2.7/dist-packages/salt
  saltversion: 2014.1.13
  saltversioninfo:
      2014
      1
      13
      0
  serialnumber: Not Specified
  server_id: 89861426
  shell: /bin/sh
  virtual: physical
  zmqversion: 4.0.4
```
