### ISSUE TITLE
unless + cmd.wait don't work

### ISSUE THREAD

**Issue by jacksontj** [saltstack/salt#17177]
If you have an SLS like

```
# runs before A and/or B
A:
  cmd.run:
    - name: echo A third

w:
  cmd.wait:
    - name: w if A
    - unless: true
    - watch:
      - cmd: A
```

I would expect w to never run (since unless will always return true), but I actually get output like:

```
local:
----------
          ID: A
    Function: cmd.run
        Name: echo A third
      Result: True
     Comment: Command "echo A third" run
     Started: 16:24:12.966336
    Duration: 55.3 ms
     Changes:   
              ----------
              pid:
                  1299
              retcode:
                  0
              stderr:

              stdout:
                  A third
----------
          ID: w
    Function: cmd.wait
        Name: w if A
      Result: True
     Comment: Command "w if A" run
     Started: 16:24:13.024084
    Duration: 69.095 ms
     Changes:   
              ----------
              pid:
                  1300
              retcode:
                  0
              stderr:

              stdout:
                   16:24:13 up 112 days,  6:09,  1 user,  load average: 2.11, 1.79, 1.68
                  USER     TTY      FROM              LOGIN@   IDLE   JCPU   PCPU WHAT

Summary
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
```

Looks like unless/onlyif aren't run in cmd.wait
