### ISSUE TITLE
salt.state.iptables.append and salt.state.iptables.insert keeps inserting duplicate rules with each state run

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#17217]
I have seen issues regarding this earlier and there has been suggested fixes. I'm still having this problem because of which using these state functions to append or insert an iptable rule seems useless. 

Here's relevant information:

Master:
```
[root@nitin-saltmaster ~]# salt --versions-report
           Salt: 2014.7.0rc6-2571-g0d6e33a
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
[root@nitin-saltmaster ~]# 
```

Minion:
```
[root@nitin-saltmaster ~]# salt '*jenkins' test.versions_report
nitin-jenkins:
               Salt: 2014.1.13
             Python: 2.6.6 (r266:84292, Sep  4 2013, 07:46:00)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
             PyYAML: 3.10
              PyZMQ: 14.3.1
                ZMQ: 3.2.4
[root@nitin-saltmaster ~]# 
```

Both my master and minion are RHEL 6.5
