### ISSUE TITLE
Optionally allow 'watch' to bypass 'onlyif' and 'unless'

### ISSUE THREAD

**Issue by akhayyat** [saltstack/salt#1721]
#### Use case

Run a command only when another command fails/succeeds (`unless`/`onlyif`), **OR** when a watched state triggers it.
Right now, satisfied `unless`/`onlyif` aborts a run triggered by a `watch`.
#### Example

Shorewall, an iptables frontend, cannot be managed as a service, because it does not have a corresponding process, and so the status function of the service state always reports the service down. However, the status of shorewall can be determined by running the command `shorewall status`. Updating any shorewall configuration files requires restarting shorewall for the changes to take effect. This results in the following sls files.

sls 1:

```
shorewall:
  pkg:
    - installed
  cmd.run:
    - name: service shorewall restart
    - unless: shorewall status
```

sls 2:

```
/etc/shorewall/rules.d/some-service.rules:
  file.managed:
    - ...
    - watch_in:
      - cmd: shorewall
```

These sls files currently will not restart shorewall when the watched file changes, because of the `unless`.
It would be useful if the `cmd` had an additional attribute stating whether the `unless` applies to runs triggered by a watched state or not.
