### ISSUE TITLE
top.sls in master branch is not authorative

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#17261]
top.sls in master branch looks:
```
base:
    '* and not I@environment:itg':
        - match: compound
        - httpd-stats
itg:
    'environment:itg':
        - match: pillar
        - httpd-stats
```
top.sls in itg branch looks:
```
base:
    '*':
        - httpd-stats
itg:
    'environment:itg':
        - match: pillar
        - httpd-stats
```
And the highstate result is:

    Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is "httpd_stats" and is found in SLS "itg:httpd-stats" and SLS "base:httpd-stats"

After deleting top.sls from itg branch everything works as expected.

Documentation at http://docs.saltstack.com/en/latest/ref/states/top.html#how-top-files-are-compiled state that env defined in master branch (base env) is authorative.

Is it a bug or i misunderstood something ? Ma salt version is 2014.1.13
