### ISSUE TITLE
Removing a security group from a VPC ELB's list doesn't remove it from the ELB

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#17312]
If you run this:

``` yaml
myelb:
  boto_elb.present:
    - name: myelb
    - security_groups:
      - test
      - test2
```

Then you run this:

``` yaml
myelb:
  boto_elb.present:
    - name: myelb
    - security_groups:
      - test
```

myelb will still have the test2 security group associated with it.
