### ISSUE TITLE
external auth group support not working with pam

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#17380]
I've tested on the very latest in the develop and 2014.7 branches and groups in external_auth do not work.

```yaml
[boucha@dasalt salt (2014.7local u=)]$ sudo salt \* test.versions_report
dasalt:
               Salt: 2014.7.0-150-g3185387
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: 1.1.0
             PyYAML: 3.11
              ioflo: 0.9.35
              PyZMQ: 14.0.1
               RAET: 0.0.29
                ZMQ: 4.0.4
               Mako: Not Installed
```
```
[boucha@dasalt salt (2014.7local u=)]$ salt -a pam \* test.ping
username: boucha
password: 
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```
```yaml
[boucha@dasalt salt (develop u=)]$ sudo salt \* test.versions_report
dasalt:
               Salt: 2014.7.0-1027-g095d9a0
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: 1.1.0
             PyYAML: 3.11
              ioflo: 0.9.35
              PyZMQ: 14.0.1
               RAET: 0.0.29
                ZMQ: 4.0.4
               Mako: Not Installed
[boucha@dasalt salt (develop u=)]$ salt -a pam \* test.ping
username: boucha
password: 
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```

My master config:
```yaml
external_auth:
  pam:
    ops%:
      - 'test.ping'
      - '@runner'
      - '@wheel'
```

My user's groups:
```
[boucha@dasalt salt (develop u=)]$ groups boucha
boucha : boucha adm cdrom sudo dip plugdev lpadmin sambashare ops
```

**Comment by cachedout** [comment]
This works for me. I am going to close this unless we can see a case of it not working.

**Comment by UtahDave** [comment]
I just tested on the latest 2014.7 branch and it worked for me

**Comment by basepi** [comment]
This is broken on the latest `2014.7` branch, but is working on `develop`.

```
[root@li737-184] [~/salt] [2014.7?]
± salt -a pam \* test.ping
username: basepi
password:
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

[root@li737-184] [~/salt] [2014.7?]
± salt -a pam \* test.versions_report
username: basepi
password:
basepi-debian:
               Salt: 2014.7.1-269-g1a0f5e7
             Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
             Jinja2: 2.6
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 13.1.0
               RAET: Not Installed
                ZMQ: 3.2.3
               Mako: Not Installed

[root@li737-184] [~/salt] [2014.7?]
± groups basepi
basepi : basepi ops
```

Here's my config:

```
external_auth:
  pam:
    ops%:
      - 'test.ping'
      - '@runner'
      - '@wheel'
    basepi:
      - 'test.versions_report'
```
