### ISSUE TITLE
ENC parameters - how to access from sls/template

### ISSUE THREAD

**Issue by mclarkson** [saltstack/salt#17944]
Hi,
I have an external node classifier returning data as shown below.
In sls and template files I have tried `{{ vim_new_value }}` and `{{ vim_test_value }}` but for each I get `<variable> is undefined`. I have also tried a suggestion from the salt newsgroup: `{{ salt\['pillar.get'\]('vim_test_value') }}`, also without success.

How do I access vim_new_value and vim_test_value? Is it possible?

ENC return data:

```
classes:
  cron:
  locale:
  logrotate:
  mysql:
  mysql.remove_test_database:
  salt:
  salt.cron:
  snmpd:
  timezone:
  vim:
  vim.vimrc:
    vim_new_value: where am i
parameters:
  vim_test_value: a test value
environment: test_0.1.1
```

Thanks,
Mark.
