### ISSUE TITLE
supervisor state fails if supervisor is not installed in system python

### ISSUE THREAD

**Issue by rvora** [saltstack/salt#18044]
This is new in 2014.7.0 (it was working in 2014.1.13).

I am managing processes with supervisor in a virtualenv where supervisor has been installed.
```
myserver:
  supervisord:
    - running
    - bin_env: /opt/myenv
    - conf_file: /opt/myenv/etc/supervisor/supervisor.conf
```
/opt/myenv does have supervisor installed:
```
# /opt/myenv/bin/pip freeze | grep supervisor
supervisor==3.1.3
```
Following error is shown in state.highstate results:
``Supervisord module not activated. Do you need to install supervisord?``

If I do ``/usr/bin/pip install supervisor`` in the system python and run highstate again, the error goes away and it looks like salt-minon is using supervisor installed in /opt/myenv/ to manage the processes.

I think this is new behavior and salt should not require supervisor installed in the system python (or the virtualenv from where salt is being run) if supervisor state is managing processes in virtual environment.
