### ISSUE TITLE
error in running multi-line file.replace state on windows minion

### ISSUE THREAD

**Issue by soodr** [saltstack/salt#18067]
Comment: An exception occurred in this state: Traceback (most recent call last):
            File "salt/state.py", line 1382, in call
            File "salt/states/file.py", line 2007, in replace
            File "salt/modules/file.py", line 988, in replace
            File "salt/modules/file.py", line 919, in _get_flags
          NameError: global name 'operator' is not defined

Salt Minion :

```
c:\salt>salt-minion --versions-report
               Salt: 2014.1.13
             Python: 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
             PyYAML: 3.11
              PyZMQ: 14.1.1
                ZMQ: 4.0.4
```

Salt Master :

```
(salt)-bash-4.1$ salt --versions-report
           Salt: 2014.7.0rc2
         Python: 2.7.8 (default, Sep 24 2014, 11:50:00)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
          RAET: Not Installed
           ZMQ: 4.0.4
           Mako: 1.0.0
```

Salt state that I am attempting to run :

```
update_datbase_bat:
    file.replace:
       - name: 'D:\SERVER\scripts\mssql_install\create_databases.bat'
       - pattern: 'set CONNECTIDENTIFIER=.*set SERVERDB_PASSWORD=<SERVERDB_PASSWORD>'
       - flags: ['DOTALL']
       - repl: 'set CONNECTIDENTIFIER={{ pillar["DB_IDENTIFIER"] }} \\n set ADMINNAME="sa" \\n set ADMINPASSWORD={{ pillar["ADMIN_PASS"] }} \\n set SERVERDB_NAME="test_server" \\n set SERVERDB_USER="test" \\n  set SERVERDB_PASSWORD="test" '
       - append_if_not_found: True
       - bufsize: 'file'
       - backup: '.bak'
       - show_changes: True
```
