### ISSUE TITLE
salt mine - support for function specific mine interval

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#18098]
There's currently no way to provide a function specific interval for salt mine functions defined in a pillar.

In my case, I want to execute some mine functions only every 60 minutes, while others should be executed every minute.

The extended definition of a mine function could then look like this:

``` YAML
mine_functions:
  network.ip_addrs: [eth0]
  networkplus.internal_ip_addrs: []
  internal_ip_addrs:
    mine_function: network.ip_addrs
    mine_interval: 60
    cidr: 192.168.0.0/16
  loopback_ip_addrs:
    mine_function: network.ip_addrs
    mine_interval: 1
    lo: true
```

**Comment by danlsgiga** [comment]
It would be really useful to have it!

**Comment by DanyC97** [comment]
it would indeed but no progress over a year ;-(

**Comment by boltronics** [comment]
As far as I'm aware, there is still no function specific interval functionality. At least, not anything mentioned in the docs if there is.

https://docs.saltstack.com/en/latest/topics/mine/#mine-interval

**Comment by Oloremo** [comment]
Looking forward for this

**Comment by Oloremo** [comment]
not stale

**Comment by davama** [comment]
This would be very convenient :+1:

**Comment by whytewolf** [comment]
so, while this isn't exactly what you are looking for. it is possible to have the result of this functionality now. without changing mine_interval. all mine_interval does is setup a schedule to run mine.update. 

so you could set `mine_enabled: False`, which turns off the automatic creation of the schedule then setup schedules to run mine.update with named mine functions see https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.mine.html#salt.modules.mine.update

This would allow you to get way more creative with the timing of the mine updates. then any interval would provide.

**Comment by Oloremo** [comment]
> all mine_interval does is setup a schedule to run mine.update.

I think the idea is that some mine functions could be updated in different intervals. Some make sense to update every minute, some on a daily basis, and so on.

**Comment by whytewolf** [comment]
> > all mine_interval does is setup a schedule to run mine.update.
> 
> I think the idea is that some mine functions could be updated in different intervals. Some make sense to update every minute, some on a daily basis, and so on.

again you can do that now. if you read the rest of my post.

**Comment by Oloremo** [comment]
ah sorry, you're right.
I'd argue that `mine_enabled: False` sounds very misleading in that scenario

**Comment by whytewolf** [comment]
agreed, but it wouldn't be the first time that a setting is badly named in salt.

**Comment by davama** [comment]
Just to update here:

Was able to get this FR functionally now by doing as was suggested:

```
schedule:
  mine_test1:
    enabled: true
    function: mine.update
    kwargs:
        mine_functions:
          mine_alias1:
            - mine_function: my_fun.do_something
    jid_include: true
    maxrunning: 1
    minutes: 1
    return_job: true
    run_on_start: true
  mine_test2:
    enabled: true
    function: mine.update
    kwargs:
        mine_functions:
          mine_alias2:
            - mine_function: my_fun.do_something
    maxrunning: 1
    minutes: 2
    return_job: true
    run_on_start: true
```

I think it would be beneficial if a note or some reference to this capability was mentioned under https://docs.saltproject.io/en/latest/topics/mine/

Thanks
