### ISSUE TITLE
Reactor cmd/local infinite recursion

### ISSUE THREAD

**Issue by jacksontj** [saltstack/salt#18256]
If you configure the reactor to run on any event that is generated by firing a job to a minion (job ret, job pub, etc.) then the reactor will infinitely recurse on itself. This is because the cmd_async function (which it uses for firing the job to the minion) has no mechanism to disable firing an event-- meaning the reactor will react on events that originated from the reactor.

**Comment by jtand** [comment]
@jacksontj Are you still working on this or can we close this?

**Comment by jacksontj** [comment]
The specific case of returner in the reactor is fixed, but the other ones (local cmd etc.) are still an issue, which we still need to fix

**Comment by kiemlicz** [comment]
I don't see the rationale for adding 
`"user":"Reactor"` as event field and not gathering reactors for such.

Actually I do want to start e.g. orchestration via `Reactor`
and do some cleanup actions after it completes. 
Aforementioned orchestration completes with **one** clean event
`salt/run/20180104200542718042/ret` that I would like to match on
Unfortunately I cannot because of `"user":"Runner"`

How can I attach reactors for the event of completion of reactor:
```
start_orchestration:
  runner.state.orchestrate:
    - args:
      - mods: _orchestrate.dummy.action
      - pillar:
          targets: {{ data['minions'] }}
      - saltenv: {{ saltenv }}
```
