### ISSUE TITLE
network.managed - link up feature request

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#18319]
On an openstack deployment I need to add the following : 

```
    auto eth1
    iface eth1 inet manual
        up ip link set dev eth1 up
```

Using 

```
eth1:
    network.managed:
        - enabled: True
        - type: eth
```

only generates 

```
auto eth1
iface eth1 inet 
```

Is there an existing way to generate what I'm looking for through configuration or do we need to add code ?
