### ISSUE TITLE
Upgrade to 2014.7.0+ds-2precise3 broke floating-ip detection in salt-cloud

### ISSUE THREAD

**Issue by jfrost** [saltstack/salt#18403]
After upgrading to 2014.7.0+ds-2precise3, I can no longer launch instances from salt-cloud.  

The error:

`Error: There was a profile error: There are no more floating IP addresses available, please create some more`

but I can launch instances just fine from Horizon and using `nova boot`.

We have automatic floating-ip association enabled, so perhaps we need to add something to our salt-cloud provider config?

Couldn't find anything in the release notes though.

Provider config looks like this (with our creds X'd out):

```
private-cloud-rackspace:
  minion:
    master: 10.241.0.14

  identity_url: 'http://10.240.0.253:5000/v2.0/tokens'
  compute_name: nova
  protocol: ipv4

  compute_region: RegionOne

  user: XXXXXXXX
  tenant: XXXXXXXX
  password: XXXXXXX

  provider: openstack

  insecure: True

  ssh_key_name: salt
  ssh_key_file: '/etc/salt/keys/salt.pem'
  ssh_username: ubuntu
```
