### ISSUE TITLE
grains.append module registers a change incorrectly

### ISSUE THREAD

**Issue by WillPlatnick** [saltstack/salt#18480]
In a state run, consider:

```
sensu-all-grain:
  module.run:
    - name: grains.append
    - key: SENSU_CHECKS
    - val: all
```

No matter how many times you run this state, Salt registers it as a change, thus throwing off requisites.

```
          ID: sensu-all-grain
    Function: module.run
        Name: grains.append
      Result: True
     Comment: Module function grains.append executed
     Started: 13:07:50.559221
    Duration: 0.706 ms
     Changes:
              ----------
              ret:
                  The val all was already in the list SENSU_CHECKS
```

```
# salt-minion --versions-report
           Salt: 2014.7.0
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
```
