### ISSUE TITLE
listen_in doesn't work with a file state

### ISSUE THREAD

**Issue by WillPlatnick** [saltstack/salt#18482]
I refactored my code to use listen/listen_in instead of watch now that 2014.7.0 is out. It appears listen_in won't work on a file state, but watch used to work without a problem.

Consider the following state:

```
/etc/willtest:
  file.managed:
    - source: salt://sensu/files/sensu-api.monit

sensu-all-grain:
  module.run:
    - name: grains.append
    - key: SENSU_CHECKS
    - val: all
    - listen_in:
      - file: /etc/willtest
```

Output

```
local:
----------
          ID: /etc/willtest
    Function: file.managed
      Result: True
     Comment: File /etc/willtest updated
     Started: 13:03:29.325420
    Duration: 162.881 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: sensu-all-grain
    Function: module.run
        Name: grains.append
      Result: True
     Comment: Module function grains.append executed
     Started: 13:03:29.488534
    Duration: 0.7 ms
     Changes:
              ----------
              ret:
                  The val all was already in the list SENSU_CHECKS
----------
          ID: listener_/etc/willtest
    Function: file.mod_watch
        Name: /etc/willtest
      Result: False
     Comment: State 'file.mod_watch' found in SLS 'sensu.test' is unavailable
     Started:
    Duration:
     Changes:

Summary
------------
Succeeded: 2 (changed=2)
Failed:    1
------------
```

Version report

```
           Salt: 2014.7.0
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
```
