### ISSUE TITLE
salt.states.grains doesn't allow creation of nested grain structure

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#18506]
Unable to create the following nested grain structure when using `salt.states.grains`:

```
[root@nitin-test ~]# salt-call grains.get custom_grains
local:
    ----------
    autoupdate:
        True
    prodstatus:
        nonprod
    rebootorder:
        0
```

```
# cat /etc/salt/grains
custom_grains:  
  autoupdate: True
  prodstatus: nonprod
  rebootorder: 0
```

Which ever way i use functions from `salt.states.grains`, i cannot get `/etc/salt/grains` to look like the one above. (I manually created that file and there's no way of creating this structure using any of the existing module functions in `salt.states.grains`)
