### ISSUE TITLE
network.managed (windows) cannot set interface without DNS servers

### ISSUE THREAD

**Issue by Supermathie** [saltstack/salt#18513]
I want to use network.managed to set up interfaces *without* specifying DNS servers:

```
"Local Area Connection 2":
  network.managed:
    - dns_proto: static
    - dns_servers: []
    #- enabled: True
    #- gateway:
    - ip_proto: static
    - ip_addrs:
      - 10.10.1.4/16
```

but no variant seems to work - it insists on having DNS servers listed:

```
          ID: Local Area Connection 2
    Function: network.managed
      Result: False
     Comment: The following SLS configuration errors were detected: The dns_servers param is required to set static DNS servers.
     Changes:   
```
