### ISSUE TITLE
Cannot remove GRAIN -  grains.remove

### ISSUE THREAD

**Issue by bigg01** [saltstack/salt#18544]
I can set a grains Key but i cannot remove it.

```
salt-call grains.setval highstate_test True
server1:
    ----------
    highstate_test:
        True
salt-call grains.item highstate_test
server1:
    ----------
    highstate_test:
        True
salt-call grains.remove highstate_test True
server1:
    The key highstate_test is not a valid list
```

version report:
```
           Salt: 2014.7.0
         Python: 2.6.9 (unknown, Mar 31 2014, 22:15:20)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by achernev** [comment]
Are you sure you guys are using the correct functions? Seems to me `grains.remove` is for removing an item from a list grain while `grains.delval` is the one to remove the grain itself. Here's an example:

<pre>
# salt-call grains.append test_list item_one
# salt-call grains.append test_list item_two
# salt-call grains.append test_list item_three
# cat /etc/salt/grains
test_list:
- item_one
- item_two
- item_three
test_val_two: some_value
# salt-call grains.remove test_list item_two
# cat /etc/salt/grains
test_list:
- item_one
- item_three
test_val_two: some_value
# salt-call grains.delval test_list True
# cat /etc/salt/grains
test_val_two: some_value
#
</pre>

Documentation: http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.remove
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.delval

**Comment by rallytime** [comment]
@achernev Thanks for pointing this out. You're absolutely right about the different functions here. I think a misunderstanding of the difference between using `grains.setval` and `grains.append` to get the grain set in the first place. This then determines when to use `grains.delval` vs. `grains.remove`.

@bigg01 I would suggest using `grains.delval` when trying to remove grains that were set using `grains.setval`. 

I have confirmed, as @achernev has, that these functions work as expected on the 2014.7.0 release:
```
salt-call --local grains.append append_test first
local:
    ----------
    append_test:
        - first
# salt-call --local grains.setval setval_test first
local:
    ----------
    setval_test:
        first
# salt-call --local grains.append append_test second
local:
    ----------
    append_test:
        - second

# cat /etc/salt/grains
append_test:
- first
append_test: first
append_test_2: second

# salt-call --local grains.remove append_test first
local:
    ----------
    append_test_2:
# salt-call --local grains.delval setval_test_2
local:
    None
# salt-call --local grains.delval setval_test True
local:
    None

# cat /etc/salt/grains
append_test: []
setval_test_2: null
```
