### ISSUE TITLE
salt-run state.orchestrate fails because it tries to run a second task while a first is ongoing

### ISSUE THREAD

**Issue by bernieke** [saltstack/salt#18564]
To start off with, this problem seems somehow related to disk speed. We can reliably reproduce the problem on sata backed virtual machines, but not on ssd backed virtual machines. (Two different openstack flavors on for the rest the same hardware.)
Probably because it takes longer to execute the task on a sata disk. (There's a lot of deb installing going on, so this would make sense.)

This is the relevant part of the output:

```
# salt-run state.orchestrate orchestration.sls
awingu_master:
----------
          ID: common
    Function: salt.state
      Result: True
     Comment: States ran successfully.
     Started: 12:50:39.093757
    Duration: 63217.649 ms
     Changes:   
----------
          ID: dns_server
    Function: salt.state
      Result: False
     Comment: Run failed on minions: awingu
              Failures:
                  awingu:
                      Data failed to compile:
                  ----------
                      The function "state.sls" is running as PID 6334 and was started at 2014, Nov 28 12:50:39.102732 with jid 20141128125039102732
     Started: 12:51:42.312406
    Duration: 630.701 ms
```

The error doesn't always occur in that part of the orchestration, sometimes it happens in a later task, but always right after a task which takes a long time to run (several minutes.)

When I check right after the error, I can see that the job referenced is in fact still ongoing. Also issueing `salt 'awingu' saltutil.running` confirms this.
The job will, in time, do its thing and finish properly.
This job runs the "common" task preceding the dns_server task. (And which the dns_server task requires!)

So it's pretty clear that the orchestrate deems the "common" task finished, while in truth it has not.

It looks like a salt execution returns prematurely, before the task actually being finished (I've noted this on one or two occasions), but apart from that being a bug, I would expect the salt runner to be smarter and check the job queue?

For us this currently is a major issue, so any recommendations on how to handle this would be extremely welcome. Even a dirty monkeypatch to apply on top of 2014.7.0 would mean the world to us!

**Comment by rallytime** [comment]
Hey @bernieke - sorry we never came back around here. Is this still an issue on the latest release (2014.7.5) for you? Have you had a chance to try this again?

**Comment by bernieke** [comment]
The issue is still there on 2014.7.5

I've just verified it by setting the timeout to 1sec, and executing a salt-run to 15 nodes.

One of the states run by salt-run (the restart state from the above orchestration) only went through on 5 of the 15 nodes, but salt-run happily continued with the next state (populate_frontend), without even so much as a warning printed. (In the output you see the same as you would normally, except it only mentions 5 minion names in the list of updated nodes in the "States ran successfully" comment part of the output instead of the 15 minion names you otherwise see.)

```
----------
          ID: restart
    Function: salt.state
      Result: True
     Comment: States ran successfully. Updating bernie-timeout-node12, bernie-timeout-node1, bernie-timeout-node11, bernie-timeout-node3, bernie-timeout-node4.
     Started: 10:38:15.569083
    Duration: 15929.754 ms
     Changes:   
```

**Comment by anitakrueger** [comment]
@bernieke could you post which property you are setting in the master config to fix this? Is it ```timeout```?
We are running into the exact same problem (running 2015.8.3) with the orchestrate runner when it sometimes things that a state has already returned and hence all the following states fail because they depend on this one. While that state is still running in the background and eventually finishes successfully (just taking a long time because it's installing packages).

We have not set ```timeout``` at all so it should default to 5 seconds. I can't see that during the orchestration, any of the states have ever "timed out" after 5 seconds though.

**Comment by bernieke** [comment]
Yes, I set timeout to 300 to avoid this problem as much as possible.

It still occurs even then though, but only on rare occasions when the host is under extreme heavy loads.

We're currently modifying our deploy process to use salt-run over salt-ssh instead (by adding ssh: True to all blocks in the orchestration sls, and working with the roster instead of daemons and keys.) Apart from simplifying our orchestration process a lot (I no longer need to separately upgrade minions and masters beforehand, check if the minions are all up and sync modules before I can start the actual orchestration), I'm hoping this will finally completely remove this problem as well.

**Comment by dgmorrisjr** [comment]
Our team has been having a similar issue when trying to run orchestration states. Here's what we've discovered... we have a number of scheduled states setup While the schedule is enabled, we see this issue regularly...especially on longer orchestration states. if we disable the schedule using salt \* schedule.disable then run the orchestration state, it runs without failure. Then we have to re-enabled the scheduled state.

While this isn't an ideal behavior, its the work-around we are using until this bug is resolved.

**Comment by yauhen-matsiushonak** [comment]
If the issue is related to timeout on **_'saltutil.find_job'_** it cat be "work-arounded" by creasing **_'gather_job_timeout'_** in master config. We saw the similar issue on virtual environment, when traversing of salt minion cache hangs in 'find_job'.  However, it also looks like defect in client/saltutil/orchestration, because saltstack considers that state.sls execution was succeed, when it failed due to timeout on 'find_job'.

I can reproduce the issue with simple orchestration state:

```yaml
# reproduce.sls
do-sleep-1:
  salt.state:
    - tgt: 'minion01'
    - sls:
      - sleep_120


do-sleep-2:
  salt.state:
    - tgt: 'minion01'
    - sls:
      - sleep_120
    - require:
      - salt: do-sleep-1
```

```yaml
# sleep_120.sls
do sleep 120:
  cmd.run:
    - name: sleep 120s
```
I also hacked 'find_job' in saltutil.py module to emulate slow execution:

```diff
diff --git a/salt/modules/saltutil.py b/salt/modules/saltutil.py
index c0f0f2b..4ba4aa9 100644
--- a/salt/modules/saltutil.py
+++ b/salt/modules/saltutil.py
@@ -814,6 +814,9 @@ def find_job(jid):
     '''
     for data in running():
         if data['jid'] == jid:
+            if data['fun'] == 'state.sls':
+                import time
+                time.sleep(30)
             return data
     return {}
 
@@ -1004,6 +1007,8 @@ def _exec(client, tgt, fun, arg, timeout, expr_form, ret, kwarg, **kwargs):
             # do not wait for timeout when explicit list matching
             # and all results are there
             break
+
+    log.error("_exec(tgt=%s, fun=%s, arg=%s, timeout=%s) ret: %s", tgt, fun, arg, timeout, fcn_ret)
     return fcn_ret
```
Orchestration output:

```
root@salt:/srv/salt# salt-run state.orchestrate reproduce
[ERROR   ] _exec(tgt=minion01, fun=state.sls, arg=['sleep_120'], timeout=None) ret: {}
[ERROR   ] _exec(tgt=minion01, fun=state.sls, arg=['sleep_120'], timeout=None) ret: {'minion01': {'retcode': 1, 'ret': ['The function "state.sls" is running as PID 12453 and was started at 2016, Jun 30 15:51:43.751796 with jid 20160630155143751796'], 'out': 'highstate'}}
[ERROR   ] Run failed on minions: minion01
Failures:
    minion01:
        Data failed to compile:
    ----------
        The function "state.sls" is running as PID 12453 and was started at 2016, Jun 30 15:51:43.751796 with jid 20160630155143751796

salt_master:
----------
          ID: do-sleep-1
    Function: salt.state
      Result: True
     Comment: States ran successfully.
     Started: 15:51:43.688091
    Duration: 15310.313 ms
     Changes:   
----------
          ID: do-sleep-2
    Function: salt.state
      Result: False
     Comment: Run failed on minions: minion01
              Failures:
                  minion01:
                      Data failed to compile:
                  ----------
                      The function "state.sls" is running as PID 12453 and was started at 2016, Jun 30 15:51:43.751796 with jid 20160630155143751796
     Started: 15:51:58.998706
    Duration: 206.86 ms
     Changes:   

Summary for salt_master
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
```
As you can see 'saltutil._exec' returns empty (or incomplete) dictionary in case of 'find_job' timeout.

I does not know is it bug in client code or orchestration incorrectly handles such result, but definitely it does not look like expected behavior. Probably some of you guys can help me to prepare patch to fix for this?

```
root@salt:/srv/salt# salt 'minion01' test.versions_report
minion01:
    Salt Version:
               Salt: 2016.3.1
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: centos 7.2.1511 Core
            machine: x86_64
            release: 3.10.0-327.22.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7.2.1511 Core
```
