### ISSUE TITLE
file.directory clean / require doesn't work correctly if requisite has name option

### ISSUE THREAD

**Issue by spuzirev** [saltstack/salt#18578]
Hi.

I have problem like described here: https://github.com/saltstack/salt/issues/12965 but with a few extensions.

It works correctly if I use simple file names:
```YAML
/tmp/clean_dir:
  file:
    - directory
    - clean: True
    - require:
      - file: /tmp/clean_dir/file

/tmp/clean_dir/file:
  file:
    - managed
    - makedirs: True
```

So I have result:
```
local:
----------
          ID: /tmp/clean_dir/file
    Function: file.managed
      Result: True
     Comment: File /tmp/clean_dir/file exists with proper permissions. No changes made.
     Started: 19:54:08.505742
    Duration: 2.321 ms
     Changes:
----------
          ID: /tmp/clean_dir
    Function: file.directory
      Result: True
     Comment: Directory /tmp/clean_dir is in the correct state
     Started: 19:54:08.508593
    Duration: 1.791 ms
     Changes:
```

But if I use specially named resources:
```YAML
/tmp/clean_dir:
  file:
    - directory
    - clean: True
    - require:
      - file: tmp_clean_file

tmp_clean_file:
  file:
    - managed
    - name: /tmp/clean_dir/clean_file
    - makedirs: True
```
I have wrong results:
```
----------
          ID: tmp_clean_file
    Function: file.managed
        Name: /tmp/clean_dir/clean_file
      Result: True
     Comment: Empty file
     Started: 19:58:32.194060
    Duration: 2.893 ms
     Changes:
              ----------
              new:
                  file /tmp/clean_dir/clean_file created
----------
          ID: /tmp/clean_dir
    Function: file.directory
      Result: True
     Comment: Files cleaned from directory /tmp/clean_dir
     Started: 19:58:32.197491
    Duration: 1.964 ms
     Changes:
              ----------
              removed:
                  - /tmp/clean_dir/clean_file
```
