### ISSUE TITLE
UUID mounts do not detect device from uuid correctly

### ISSUE THREAD

**Issue by kormoc** [saltstack/salt#18613]
```
# ./bin/salt-call --versions-report
           Salt: 2014.7.0-1804-gc3b11c8
         Python: 2.7.8 (default, Sep 24 2014, 18:26:21)
         Jinja2: 2.7.3
       M2Crypto: Not Installed
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: Not Installed
        libnacl: 1.4.0
         PyYAML: 3.11
          ioflo: 1.0.2
          PyZMQ: Not Installed
           RAET: 0.4.0
            ZMQ: Not Installed
           Mako: Not Installed
```

Here's the output

```
----------
          ID: /
    Function: mount.mounted
      Result: None
     Comment: Unable to unmount
     Started: 11:18:12.205187
    Duration: 82.44 ms
     Changes:   
              ----------
              umount:
                  Forced unmount because devices don't match. Wanted: UUID=dd8e82e0-6a81-49e2-8d67-9e828c118c15 (dd8e82e0-6a81-49e2-8d67-9e828c118c15), current: /dev/sdc1, /dev/sdc1
```

As you can see, I use the UUID, but it sees the raw device and tries to remount it. It shouldn't.

```
[root@clamps ~]# grep '/ ' /proc/mounts /etc/fstab 
/proc/mounts:/dev/sdc1 / ext4 rw,noatime,discard,data=ordered 0 0
/etc/fstab:UUID=dd8e82e0-6a81-49e2-8d67-9e828c118c15 / ext4 defaults,rw,noatime,data=ordered,discard 0 1
[root@clamps ~]# 
```
