### ISSUE TITLE
Windows: symlinks always re-created on state runs

### ISSUE THREAD

**Issue by Supermathie** [saltstack/salt#18625]
I have the following example in a state file:

```
c:/Users/Public/Desktop/run_iometer.bat:
  file.symlink:
    - target: c:/iometer/run_iometer.bat
    - makedirs: true
    - user: Administrators
```

which is overwritten on every state run even when no change is necessary:

```
----------
          ID: c:/Users/Public/Desktop/run_iometer.bat
    Function: file.symlink
      Result: True
     Comment: Created new symlink c:/Users/Public/Desktop/run_iometer.bat -> c:/iometer/run_iometer.bat
     Started: 16:01:26.195000
    Duration: 7.0 ms
     Changes:   
              ----------
              new:
                  c:/Users/Public/Desktop/run_iometer.bat
----------
```

The state module should detect the symlink already existing and not report a change.
