### ISSUE TITLE
file.append does not work with templates

### ISSUE THREAD

**Issue by johnswanson** [saltstack/salt#18686]
I set up a quick formula to demonstrate: https://github.com/johnswanson/file-append-test-formula

The following results in an error:

```
    /tmp/testfile:
        file.append:
            - user: root
            - group: root
            - mode: 0666
            - makedirs: True
            - context:
                foo: "bar"
            - template: jinja
            - source: salt://file-append-test/testfile.jinja
```

Result:

```
          SaltRenderError: Jinja variable 'foo' is undefined
```

The following works fine:

```
            /tmp/testfile:
                file.managed:
                    - user: root
                    - group: root
                    - mode: 0666
                    - makedirs: True
                    - context:
                        foo: "bar"
                    - template: jinja
                    - source: salt://file-append-test/testfile.jinja
```
