### ISSUE TITLE
Require sls does not work if required sls only contains includes

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#18718]
When you require a sls if that sls only has includes the state with the require fails.

Example:

core/init.sls

```
include:
  - core.apt

# Install core utils with no configs
core-packages:
  pkg.latest:
    - pkgs:
      - ca-certificates
      - vim
    - refresh: True
    - require:
      - sls: core.apt
```

core/apt/init.sls

```
include:
{% if grains['os'] == 'Ubuntu' -%}
  - core.apt.ubuntu
{% elif grains['os'] == 'Debian' -%}
  - core.apt.debian
{% endif %}
```

This will fail the requisite on "core-packages" even though the core.apt state runs and calls the needed core.apt.os sls.
