### ISSUE TITLE
2014.7 : __opt__['files_root'] overwritten by pillar_roots value

### ISSUE THREAD

**Issue by fvanniere** [saltstack/salt#18719]
I have random faillures with commands like cp.hash_files. eg : 
```
salt-call cp.hash_file salt://proxy/apache_lists/vhosts.map saltenv=mutu
```

In fileservers.root module, find_file it uses the global value  __opt__['files_root']  which points to /srv/salt/mutu, but sometimes it's set to /srv/pillar/mutu

**Comment by fvanniere** [comment]
master:
```
 user: xxxxxxx
 max_open_files: 100000000
 worker_threads: 4
 keep_jobs: 24
 jinja_trim_blocks: True
 jinja_lstrip_blocks: True
 
file_roots:
  base:
    - /srv/salt/base
  mutu:
    - /srv/salt/mutu
  motostat:
    - /srv/salt/motostat
  dserver:
    - /srv/salt/dserver
  virthost:
    - /srv/salt/virthost

pillar_roots:
  base:
    - /srv/pillar/base
  mutu:
    - /srv/pillar/mutu
  motostat:
    - /srv/pillar/motostat

log_level: warning
```

On the minion, it's the default configuration


The bug can be  in modules/saltutil.py :
```
# this is the only way I could figure out how to get the REAL file_roots
# __opt__['file_roots'] is set to  __opt__['pillar_root']
```

if  __opt__ is global to salt process, overwriting a value temporary in a multithread environment will lead to unwanted corruption.


or pillar/__init__.py :
```
class Pillar(object):
    '''
    Read over the pillar top files and render the pillar data
    '''
    def __init__(self, opts, grains, id_, saltenv, ext=None, functions=None):
        # Store the file_roots path so we can restore later. Issue 5449
        self.actual_file_roots = opts['file_roots']
        # use the local file client
        self.opts = self.__gen_opts(opts, grains, id_, saltenv, ext)
        self.client = salt.fileclient.get_file_client(self.opts, True)
```
