### ISSUE TITLE
saltutil.revoke_auth no longer working

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#18737]
This execution function is not working on 2014.7.

It is a tad old (~0.15) and added for a specific purpose, IIRC. Should it be fixed, should it be deprecated in favor of Reactor documentation/examples, or should it be updated to use events + wheel.key modules?

Discuss!

**Comment by rjsm** [comment]
Is there any work around in the meantime?  I definitely rely on this behavior, and would like to see it or another command with similar purpose in the future.

**Comment by whiteinge** [comment]
The easiest workaround for the current Salt version is to use the Salt Reactor with a custom event. You can swap 'delete' with 'reject' here.

Master config:

```yaml
reactor:
  - 'mycustomtag/key/delete':
    - /srv/reactor/key_delete.sls
```

/srv/reactor/key_delete.sls

```yaml
delete_minion_key:
  wheel.key.delete:
    - match: {{ data.id }}
```

Run this on the minion:

```bash
salt-call event.fire_master '{}' mycustomtag/key/delete
```
