### ISSUE TITLE
iptables.set_pocity KeyError: 'table' ubuntu 14.04

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#18745]
running develop
```
root@oat-fe-1:~# salt --version
salt 2014.7.0-1806-gdcdd2ae (Helium)
```

sls file call:
```
{{ sls }} firewall policy DROP:
    iptables.set_policy:
        - chain: INPUT
        - policy: ACCEPT
```

```
          ID: service.oat.fe firewall policy DROP
    Function: iptables.set_policy
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1551, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/iptables.py", line 678, in set_policy
                  kwargs['table'],
              KeyError: 'table'
     Started: 16:02:36.888739
    Duration: 1.261 ms
     Changes:   
```

grains...
```
    osarch:
        amd64
    oscodename:
        trusty
    osfinger:
        Ubuntu-14.04
    osfullname:
        Ubuntu
    osrelease:
        14.04
```
