### ISSUE TITLE
Helium salt-server 100% CPU usage and never recovers

### ISSUE THREAD

**Issue by getabc** [saltstack/salt#18787]
Firstly the ubuntu salt-master environment,

```
root@automate:~# salt-master --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
/etc/salt/master
```
interface: 10.156.47.9
max_open_files: 8192
worker_threads: 20
timeout: 30 
open_mode: True
auto_accept: True

file_roots:                                                                                         
  base:                                                                                             
    - /srv/salt/base 

fileserver_backend:                                                                                 
  - git                                                                                             
  - roots   

pillar_roots:                                                                                       
  base:                                                                                             
    - /srv/pillar
```
The Windows minion are configured with 2014.7.0
```
ipc_mode: tcp
master: automate.gs.au.adshel.net
retry_dns: 30
master_port: 4506

root_dir: c:\salt
pki_dir: /conf/pki/minion

multiprocessing: False
win_repo_cachefile: 'salt://win/repo/winrepo.p'

#Autentication
random_reauth_delay: 270
recon_default: 1000
recon_max: 30000
recon_randomize: True
auth_timeout: 60
```

At this point the salt-master server is running normally with 130 minions connected.

Command issued
```
root@automate:/etc/salt# salt '*st*' test.ping
```

Data returned as normal, but one process is stuck at 100%.
```
root@automate:/etc/salt# ps -aux | grep salt-master
root     13609  0.0  1.2 143532 26504 pts/0    S+   10:12   0:00 /usr/bin/python /usr/bin/salt-master -l debug
root     13616  0.7  2.9 220172 59908 pts/0    S+   10:12   0:06 /usr/bin/python /usr/bin/salt-master -l debug
root     13617  0.0  1.3 225460 27488 pts/0    Sl+  10:12   0:00 /usr/bin/python /usr/bin/salt-master -l debug
root     13620  0.0  1.1 225460 23720 pts/0    Sl+  10:12   0:00 /usr/bin/python /usr/bin/salt-master -l debug
root     13623  0.0  1.1 143532 22568 pts/0    S+   10:12   0:00 /usr/bin/python /usr/bin/salt-master -l debug
root     13624  0.3  2.2 455408 46660 pts/0    Sl+  10:12   0:02 /usr/bin/python /usr/bin/salt-master -l debug
root     13625  0.3  2.2 455408 46668 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13626  0.3  2.2 455404 46668 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13627  0.3  2.2 455412 46600 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13628  0.3  2.2 455408 46676 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13629  0.3  2.2 455412 46680 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13630  0.3  2.2 455420 46688 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13631  0.3  2.2 455420 46688 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13632  0.3  2.2 520948 46736 pts/0    Sl+  10:12   0:02 /usr/bin/python /usr/bin/salt-master -l debug
root     13633  0.3  2.2 455420 46684 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13634  0.3  2.2 455416 46664 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13635  0.3  2.2 455416 46680 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13637  0.3  2.2 455420 46692 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13641  0.3  2.2 455420 46688 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13642  0.3  2.2 455424 46676 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13643  0.3  2.2 455424 46692 pts/0    Sl+  10:12   0:02 /usr/bin/python /usr/bin/salt-master -l debug
root     13646  0.3  2.2 455424 46700 pts/0    Sl+  10:12   0:02 /usr/bin/python /usr/bin/salt-master -l debug
root     13649  0.3  2.2 455424 46688 pts/0    Sl+  10:12   0:02 /usr/bin/python /usr/bin/salt-master -l debug
root     13652  0.3  2.2 455424 46676 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13657  0.3  2.2 455432 46700 pts/0    Sl+  10:12   0:03 /usr/bin/python /usr/bin/salt-master -l debug
root     13666 68.3  7.7 852956 159332 pts/0   Sl+  10:12  10:12 /usr/bin/python /usr/bin/salt-master -l debug
```

No file activity found when I strace the process
```
root@automate:/etc/salt# sudo strace -c -p 13666
Process 13666 attached
<no result>
```

The salt-server does not respond to any requests until I restart the salt-master process.
