### ISSUE TITLE
file.replace result/returne code  has changed between 2014.1.10 and 2014.7.0

### ISSUE THREAD

**Issue by ferreol** [saltstack/salt#18796]
Hi

On two machines, I have two different versions of salt.
Both are debian wheezy installed with bootstrap (version differ because of install date)

I made a rule to update the grub timeout:
```
/etc/default/grub:
  file.replace:
    - name: /etc/default/grub
    - pattern: GRUB_TIMEOUT=.*
    - repl: GRUB_TIMEOUT=30

update-grub:
  cmd.wait:
    - require:
      - file : /etc/default/grub
    - watch:
      - file: /etc/default/grub
```

I have a script that runs highstates with test=True for reporting purposes whithin html dashboards
If no modification has to be made, the behavior differs between two versions
On version 2014.7.0, the test=True reports as 
```
----------
          ID: /etc/default/grub
    Function: file.replace
      Result: None
     Comment: No changes were made
     Changes:
----------
          ID: update-grub
    Function: cmd.wait
      Result: True
     Comment:
     Changes:
```
on version 2014.1.10, the test=True reports as 
```
----------
          ID: /etc/default/grub
    Function: file.replace
      Result: True
     Comment: No changes were made
     Changes:
----------
          ID: update-grub
    Function: cmd.wait
      Result: True
     Comment:
     Changes:
```
I believe that the correct result should be True (because the file is in correct state) but perhaps this behavior was modified on purpose ? Or is this a regression ?

Best regards,

Ferréol
