### ISSUE TITLE
Windows minion fail on "state.highstate" config issue?

### ISSUE THREAD

**Issue by mjm2167** [saltstack/salt#18800]
I'm new to using SALT, but so far have a working environment in Linux, now trying to demo in windows... Here is my scenario, I want to push out our standard software packages, and add certain registry settings... I want to know when they change and have the "auto heal" so to speak. I have this working in Linux, here are my config files and one package for our windows - zabbix agent(s). Im just wondering what i am doing wrong, and if someone can point me in the right direction.

MINION:
```
# salt 'DanTest61814.wsol.dmz' test.versions_report
DanTest61814.wsol.dmz:
Salt: 2014.7.0
Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
Jinja2: 2.7.1
M2Crypto: 0.21.1
msgpack-python: 0.4.2
msgpack-pure: Not Installed
pycrypto: 2.6
libnacl: Not Installed
PyYAML: 3.11
ioflo: Not Installed
PyZMQ: 14.1.1
RAET: Not Installed
ZMQ: 4.0.4
Mako: Not Installed
```
MASTER:
```
root@salt states]# salt-master --versions-report
Salt: 2014.7.0
Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
Jinja2: unknown
M2Crypto: 0.20.2
msgpack-python: 0.1.13
msgpack-pure: Not Installed
pycrypto: 2.0.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.3.1
RAET: Not Installed
ZMQ: 3.2.4
Mako: Not Installed
```
Master Config: All un-commented lines are listed below.

```
interface: 10.16.33.62
file_roots:
  base:
    - /srv/salt
dev:
    - /srv/salt/dev/services
    - /srv/salt/dev/states
prod:
    - /srv/salt/prod/services
    - /srv/salt/prod/states
linux:
    - /srv/salt/linux/services
    - /srv/salt/linux/states
windows:
    - /srv/salt/windows/services
    - /srv/salt/windwos/states

gitfs_remotes:
  - git://github.com/saltstack/salt-states.git

win_repo: '/srv/salt/win/repo'
```

TOP.SLS File:

```
base:
 'os:CentOS':
   - match: grain
   - linux.services.firewall
   - linux.states.basepkg
   - linux.states.ntp
   - linux.states.pw
   - linux.states.sudo
   - linux.states.snmp

 'os:Windows':
   - match: grain
   - windows.states.7zip
   - windows.states.Notepad
   - windows.states.filezilla
   - windows.states.vmwaretools
   - windows.states.zabbix

 'saltminion':
  - linux.states.VMwareagent
```

/srv/salt/win/repo/zabbix/init.sls
```
zabbix:
 2.4.2:
  installer: 'salt://win/repo/zabbix/zabbix_agent-2.4.2_x64.msi'
  full_name: 'Zabbix'
  reboot: False
  install_flags: ' SERVER=10.16.33.60 RMTCMD=1 /qn'
  uninstall_flags: ' /q'
  msiexec: True
  uninstaller: 'salt://win/repo/zabbix/zabbix_agent-2.4.2_x64.msi'
```

/srv/salt/windows/states/zabbix.sls
```
zabbix:
 pkg:
  - installed
```

```
[root@salt states]# salt -G 'os:Windows' pkg.list_pkgs
DanTest61814.wsol.dmz:
    ----------
    7zip:
        9.20.00.0
    FileZilla Server:
        beta 0.9.48
    Salt Minion v2014.7.0:
        v2014.7.0
    VMware Tools:
        9.4.5.1734305
    Zabbix Agent:
        2.4.2.0
    notepad:
        6.6.9
```

some basic commands to let me know things are working to some degree....
```
# salt -G 'os:Windows' pkg.available_version zabbix           
DanTest61814.wsol.dmz:
    2.4.2
```
```
# salt '*' pkg.remove 'zabbix'
saltminion.wsol.local:
    ----------
DanTest61814.wsol.dmz:
    ----------
    Zabbix Agent:
        ----------
        new:
        old:
            2.4.2.0
```
```
[root@salt states]# salt '*' pkg.install 'zabbix'
DanTest61814.wsol.dmz:
    ----------
    Zabbix Agent:
        ----------
        new:
            2.4.2.0
        old:
```
```
# salt '*' pkg.list_pkgs |egrep -a -A1 'zabbix'  (Works on Linux machine)
    zabbix:
        1.8.21-1.el6
```
```
[root@salt states]# salt -G 'os:Windows' pkg.list_pkgs |egrep -a -A1 'zabbix'
```
Re-turns nothing when using –G ‘os:Windows’

Here is where im struggling... I'm not sure if has something to do with the space in the name that gets returned with the "pkg.list_pkgs" command? I have tried calling it out as full names from what gets returned, but not having much luck.
```
# salt -G 'os:Windows' state.highstate
DanTest61814.wsol.dmz:
----------
          ID: 7zip
    Function: pkg.installed
      Result: True
     Comment: Version 9.20.00.0 of package '7zip' is already installed.
     Started: 11:21:13.077000
    Duration: 593.0 ms
     Changes:
----------
          ID: notepad
    Function: pkg.installed
      Result: True
     Comment: Version 6.6.9 of package 'notepad' is already installed.
     Started: 11:21:13.670000
    Duration: 0.0 ms
     Changes:
----------
          ID: filezilla
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: filezilla=0.9.48.
     Started: 11:21:13.670000
    Duration: 3078.0 ms
     Changes:
----------
          ID: zabbix
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: zabbix=2.4.2.
     Started: 11:21:16.748000
    Duration: 2157.0 ms
     Changes:

Summary
------------
Succeeded: 2
Failed:    2
------------
Total states run:     4
```
Any help or guidance is greatly appreciated! i do love the product, and have had great success considering I have never used it and find it much easier than CHEF or Puppet

Thanks,
Mark
