### ISSUE TITLE
"Failed to authenticate message" during minion restart while running highstate with 2014.7.0

### ISSUE THREAD

**Issue by kev009** [saltstack/salt#18835]
I have a minion running directly on the salt-master and it reliably triggers a race during bootstrap when the minion is restarting itself.  There's a watch on the minion.conf that triggers a reload.  After it reloads as part of the initial highstate, I see several of these per second on the master:

2014-12-09 14:10:10,799 [salt.crypt       ][DEBUG   ] Failed to authenticate message
2014-12-09 14:10:10,821 [salt.crypt       ][DEBUG   ] Failed to authenticate message
2014-12-09 14:10:10,843 [salt.crypt       ][DEBUG   ] Failed to authenticate message
2014-12-09 14:10:10,866 [salt.crypt       ][DEBUG   ] Failed to authenticate message
2014-12-09 14:10:10,888 [salt.crypt       ][DEBUG   ] Failed to authenticate message
2014-12-09 14:10:10,910 [salt.crypt       ][DEBUG   ] Failed to authenticate message

There are some other bugs with similar messages but they seem to be doing a key deletion during the run.  This happens for me with auto accepted key and during a normal highstate run.

If I attach a debugger to the stuck process, I see that it's simply waiting for file data (i.e. salt://stuff/files/nsswitch.conf).

It seems to me that the session is not re-authenticating after the minion restart?

If I kill the job and restart the minion, things proceed correctly.

**Comment by rallytime** [comment]
@kev009 We're making rounds on some old issues. It looks like you said you had a fix for this, but I don't see a linked pull request that fixed the issue here. Did you ever submit one? Is this still an issue on newer versions of salt? (We're currently on 2015.5.1.)

**Comment by kev009** [comment]
@rallytime the workaround is the nohup restart with a cmd.run/wait that does not timeout.  Should I submit those changes to the cmdmod?

**Comment by thatch45** [comment]
Please do :)

**Comment by rallytime** [comment]
@kev009 Thanks for submitting that pull request. I've just merged it in. Is this issue good to close now?

**Comment by kev009** [comment]
@rallytime this doesn't actually solve the bug request.  That will need somebody that can dig into an entire salt run life cycle and somehow trigger renegotiation with the master if this happens.

I think at minimum we need to document somewhere the workaround using cmd w/ignore_timeout:

```
salt-minion-reload:
  cmd.wait:
    - name: |
        nohup echo "sleep 10 && salt-call --local service.stop {{ salt_map['minion-service'] }}; pkill -f 'python.*{{ salt_map['minion-process'] }}'; salt-call --local service.restart {{ salt_map['minion-service'] }}" | sh -s
    - ignore_timeout: True
    - python_shell: True
    - timeout: 2
    - order: last
    - watch:
      - pkg: salt-minion-pkg
      - file: salt-minion-conf
```
