### ISSUE TITLE
Impossible to override some specific grains (using salt-cloud)

### ISSUE THREAD

**Issue by zaide** [saltstack/salt#18834]
Hello,
I have a problem with salt-cloud and custom grains. It's like this bug but the solution don't work for me:
https://github.com/saltstack/salt/issues/14863

Here are the informations to reproduce the problem. I use version 2014.07 (Hydrogen):
- I launch an instance on RackSpace with this profile:

``` yaml
MyProject-test_512:
  provider: rackspace-dallas-config
  size: 512MB Standard Instance
  image: Debian 7 (Wheezy) (PVHVM)
  ssh_key_file: /root/.ssh/salt_id_rsa
  ssh_key_name: SaltStack Master
  ssh_interface: private_ips
  script_args: -U -p python-pip
  minion:
    master: XX.XX.XX.XX
    grains:
      role: myproject
      environment: test
```
- I have also a "_grains" directory with a my_grains.py file:

``` python
def zookeeper_role():
    """ Assign Zookeeper role """

    grains = {}
    hostname = socket.gethostname()
    if "zookeeper" in hostname:
        grains['role'] = 'zookeeper'

    return grains
```

After the instance is launched, there is a file "/etc/salt/grains" that contains salt-cloud profile grains:

``` yaml
environment: test
role: myproject
```

 I do a "salt '_zookeeper_' grains.items" and it return for "role" grain:

``` yaml
role:
  myproject
```

When I change my custom grain to create a grain or override other grains(ex: osmajorrelease), it work. Not working on "role".

Tell me if you need more informations.
