### ISSUE TITLE
Feature Request : salt-cloud use only a subset of map file

### ISSUE THREAD

**Issue by MrCitron** [saltstack/salt#18866]
I would like to be able to do something like this :
with a map file like this:
```yaml
myprofile:
  - myinstance1:
       minion:
          grains:
              role: role1
  - myinstance2:
        minion:
           grains:
               role: role2
```
and running commands like these:
```
salt-cloud -m mymap myinstance1
salt-cloud -m mymap [myinstance1, myinstance2]
```
The great thing with map is that you can pass custom grains, and override easily the profile data, where it is complicated using the 2 parameters -p <profile name> <instance name>
