### ISSUE TITLE
file.serialize ignores test=True

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#18966]
AFAIR file.serialize ignores test=True for months.

Salt selfbuilt packages based on 3e2b366cd6f8c8bcb37eb55f59853178a0420072.

```
           Salt: 2014.7.0-2-g956b89a
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: Not Installed
salt -v --versions  0.27s user 0.14s system 69% cpu 0.593 total
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.7 (wheezy)
Release:	7.7
Codename:	wheezy
```

```
id:
 file:
    - serialize
    - name: /etc/salt/master
    - dataset: {"Data": "set"}
    - formatter: JSON
    - mode: 600
    - user: root
    - group: root
```

Example: https://github.com/bechtoldt/saltstack-salt-formula/blob/master/salt/master.sls#L19
