### ISSUE TITLE
salt.states.ssh_auth.present can't update key options

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#18983]
When the user changes an option or simply the list of options in a state definition Salt tells you that it changed the line in the authorized_keys file, but this isn't the case. The line remains unchanged.

Salt selfbuilt packages based on 3e2b366cd6f8c8bcb37eb55f59853178a0420072.

```
           Salt: 2014.7.0-2-g956b89a
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: Not Installed
salt -v --versions  0.27s user 0.14s system 69% cpu 0.593 total
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.7 (wheezy)
Release:    7.7
Codename:   wheezy
```

```
id:
  ssh_auth:
    - ensure
    - name: <key>
    - user: <user>
    - enc: ssh-rsa
    - comment: <comment>
    - options:
      - command="foo bar baz"
```
