### ISSUE TITLE
pip and requests version mismatch breaks installing modules with pip

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#18982]
The following state fails when using `salt-ssh` from Mac OS X to Ubuntu 14.04.1 server with:

```
State 'pip.installed' found in SLS is unavailable
```

```
docker-py:
  pip.installed:
    - require:
    - sls: pip
```

The reason is that I had on my Mac OS X installed requests Python module 2.5.0 (because salt's `_requirements.txt` does not have an upper limit on requests version) which was then pushed to the server. But on the server with Ubuntu 14.04.1 there is a [bug](https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991) which make then pip not work and it fails when imported, which makes salt think that pip is not installed. Forcing Mac OS X to have requests 2.2.1 it works.

Why is salt not using requests available on the system if it is using pip installed on the system? It seems things do not work if there is mismatch between pip and requests versions.

**Comment by kristinn** [comment]
This has nothing to do with Salt.

Requests is required by pip. I learned it the hard way that by installing a different version of requests via pip, than the one that pip requires, will break pip. It happened while I was installing packages without using Salt. The only way for me to fix pip was to remove the requests package manually, the one pip installed, not the one pip is dependant on.

**Comment by mitar** [comment]
Another workaround is to use instead of:

```
python-pip:
  pkg.installed
    - reload_modules: True
```

This:

```
python-setuptools:
  pkg.installed

python-pip:
  cmd.run:
    - name: easy_install pip
    - unless: which pip
    - require:
      - pkg: python-setuptools
    - reload_modules: True
```

It seems this is the necessary way to install pip in Ubuntu 14.04 LTS.

**Comment by mitar** [comment]
Hm, it seems that:

```
python-pip:
  pkg.latest:
    - refresh: True
    - reload_modules: True
```

Might help. So to install the current latest package from Ubuntu. Not sure if this really helps or if I just do not get to the code-path of installing pip for now.
