### ISSUE TITLE
network.managed regression in 2014.7 ?

### ISSUE THREAD

**Issue by bbinet** [saltstack/salt#19078]
To be able to connect a usb network device now and then (which will get its network configuration via dhcp when attached: `hotplug: True`), I have a state that looks like:

```
usb0:
  network.managed:
    - enabled: True
    - hotplug: True
    - type: eth
    - proto: dhcp
```

This was working in 2014.1.13, but does not work anymore in 2014.7:
the usb network device is not attached when the highstate is run, and this cause the state to fail for 2014.7 version.
I think `network.managed` should not check that the interface is up, but only that it is configured properly as stated in the documentation: http://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html#salt.states.network.managed
