### ISSUE TITLE
lxc: salt is erroneously merging lxc config parameters with the same name

### ISSUE THREAD

**Issue by nlm** [saltstack/salt#19081]
LXC config can contain multiple parameters with the same name.
for example when dealing with multi-interface network configuration.
The salt state lxc.edited_conf merges all the lines where the parameter
name is the same, messing the configuration and making it unusable

this is valid:

```
lxc.network.type = veth
lxc.network.name = eth0
lxc.network.flags = up
lxc.network.link = br0
lxc.network.ipv4.ip = 10.0.0.2
lxc.network.ipv4.gateway = 10.0.0.1
lxc.network.type = veth
lxc.network.name = eth1
lxc.network.flags = up
lxc.network.link = br1
lxc.network.ipv4.ip = 10.0.1.2
```

and would be represented in salt config like this:

```
lxctest1-container:
 lxc.created:
    - name: lxctest1
    - template: 'ubuntu'

lxctest1-config:
  lxc.edited_conf:
    - name: lxctest1
    - lxc_conf:
        - lxc.network.type: 'veth'
        - lxc.network.name: 'eth0'
        - lxc.network.flags: 'up'
        - lxc.network.link: 'br0'
        - lxc.network.ipv4.ip: '10.0.0.2'
        - lxc.network.ipv4.gateway: '10.0.0.1'
        - lxc.network.type: 'veth'
        - lxc.network.name: 'eth1'
        - lxc.network.flags: 'up'
        - lxc.network.link: 'br1'
        - lxc.network.ipv4.ip: '10.0.1.2'
    - require:
        - lxc: lxctest1-container
```

but the result is this:

```
# Network configuration
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br1
lxc.network.name = eth1
lxc.network.ipv4.ip = 10.0.1.2
lxc.network.ipv4.gateway = 10.0.0.1
```

I think the whole way of salt dealing with lxc configuration is broken.
We will fix this on our systems by replacing the edited_conf by a
file.managed file templated with jinja
