### ISSUE TITLE
salt-ssh cp.get_file is not using sudo, even if declared in the rooster

### ISSUE THREAD

**Issue by mpasternak** [saltstack/salt#19083]
_The_ _problem_:
salt-ssh cp.get_file will not allow me to upload files into root directory of the server, even if I enabled sudo

Here's the situation:

```
root@master:/srv/salt/django_bpp# uname -a
Linux master 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
root@master:/srv/salt/django_bpp# salt --versions
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
root@master:/srv/salt/django_bpp# cat /etc/salt/roster
my.host.pl:
  host: XXX.XXX.XXX.XXX
  user: username
  sudo: True
```

User "username" exists in sudoers file:

```
username@my.host.pl:~$ sudo cat /etc/sudoers|grep username
username ALL=(ALL) NOPASSWD: ALL
```

What I am trying to do:

```
# I want to upload file to minion root directory using salt-ssh -- this will NOT work
root@master:/srv/salt/django_bpp# salt-ssh my.host.pl cp.get_file salt://files/TESTOWY_PLIK /foobar
my.host.pl:
    False

# I want to upload file to minion user's home directory using salt-ssh -- this will work
root@master:/srv/salt/django_bpp# salt-ssh my.host.pl cp.get_file salt://files/TESTOWY_PLIK into_homedir
my.host.pl:
    True
```

Let's check how does the uploaded file look:

```
username@my.host.pl:~$ ls -las into_homedir 
4 -rw------- 1 username username 3 dec 18 12:58 into_homedir
```

So, it was uploaded as the user that salt-ssh is logged in as... why was I unable to put it into root directory? I enabled sudo in the rooster file.

For comparison, same "cp.get_file" with ZeroMQ will work without problems:

```
root@master:/srv/salt/django_bpp# salt bpplocal.local cp.get_file salt://files/TESTOWY_PLIK /foobar
bpplocal.local:
    /foobar
```

Also, as you can see, you get different return values for the same cp.get_file function, but that's another story.
