### ISSUE TITLE
Multi-environment Pillars

### ISSUE THREAD

**Issue by debian112** [saltstack/salt#19091]
This is more of a question than bug.

We have an multi-environment shared salt-master. Each environment minion is hard coded to there respective environment. (environment: greentoads). I am looking to share my pillar data from base with greentoads. Is there a way to do that? If not, what other approach could I take.

master file:
```
pillar_roots:
  base:
    - /srv/salt/pillar/base
    - /srv/salt/base/pillar
  base_staging:
    - /srv/salt/pillar/base_staing
    - /srv/salt/base_staging/pillar
  greentoads:
    - /srv/salt/greentoads/pillar
    - /srv/salt/base/pillar
  greentoads_staging:
    - /srv/salt/base_staging/pillar
    - /srv/salt/greentoads_staging/pillar
```
base pillar top.sls file:
```
base:
  '*':
    - users.accounts
    - users.ids

```
