### ISSUE TITLE
cron.absent & test=True reports wrong state.

### ISSUE THREAD

**Issue by ferreol** [saltstack/salt#19213]
I create a crontab task

```
root@debian:/srv/salt# cat crontab.sls
crontab_example:
  cron.present:
    - identifier: CRON_FOO
    - name: echo "foo"
    - user: root
    - minute: '00'
    - hour: '20'
    - daymonth: '*'
    - month: '*'
    - dayweek: '1-5'
```

tests reports that it will be added

```
root@debian:/srv/salt# salt 'debian' state.sls crontab test=True
debian:
----------
          ID: crontab_example
    Function: cron.present
        Name: echo "foo"
      Result: None
     Comment: Cron echo "foo" is set to be added
     Started: 10:16:05.065045
    Duration: 13.481 ms
     Changes:

Summary
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
```

It is added when ran

```
root@debian:/srv/salt# salt 'debian' state.sls crontab
debian:
----------
          ID: crontab_example
    Function: cron.present
        Name: echo "foo"
      Result: True
     Comment: Cron echo "foo" added to root's crontab
     Started: 10:16:16.244732
    Duration: 40.378 ms
     Changes:
              ----------
              root:
                  echo "foo"

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

now I want to remove it

```
root@debian:/srv/salt# cat crontab.sls
crontab_example:
  cron.absent:
    - identifier: CRON_FOO
    - name: echo "foo"
    - user: root
    - minute: '00'
    - hour: '20'
    - daymonth: '*'
    - month: '*'
    - dayweek: '1-5'

```

```
root@debian:/srv/salt# salt 'debian' state.sls crontab test=True
debian:
----------
          ID: crontab_example
    Function: cron.absent
        Name: echo "foo"
      Result: True
     Comment: Cron echo "foo" is absent
     Started: 10:17:14.477140
    Duration: 11.452 ms
     Changes:

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

```
root@debian:/srv/salt# crontab -l
# Lines below here are managed by Salt, do not edit/opt/MosaicFinance/oasis/var/log/crontab.log
# SALT_CRON_IDENTIFIER:CRON_FOO
00 20 * * 1-5 echo "foo"

```

When ran, it works as expected

```
root@debian:/srv/salt# salt 'debian' state.sls crontab
debian:
----------
          ID: crontab_example
    Function: cron.absent
        Name: echo "foo"
      Result: True
     Comment: Cron echo "foo" removed from root's crontab
     Started: 10:17:21.860009
    Duration: 28.549 ms
     Changes:
              ----------
              root:
                  echo "foo"

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
