### ISSUE TITLE
salt.states.archive.extracted: archive_user parameter ignored if tar_options is None

### ISSUE THREAD

**Issue by enver** [saltstack/salt#19260]
archive_user parameter ignored if tar_options is None. Check salt/states/archive.py:

```
    if tar_options is None:
        with closing(tarfile.open(filename, 'r')) as tar:
            files = tar.getnames()
            tar.extractall(name)
    else:
        log.debug('Untar {0} in {1}'.format(filename, name))

        results = __salt__['cmd.run_all']('tar x{0} -f {1!r}'.format(
            tar_options, filename), cwd=name, runas=archive_user)
```

**Comment by pitatus** [comment]
Thanks for the info..

**Comment by stas** [comment]
This is a little more complex.

The way archive state works is by using `file.managed` to download the file and `cmd.run` to actually extract it.

If we force the `cmd.run` to run `archive_user`, the file state needs to allow permissions to at least read the downloaded file. Right now, the way `states/archive.py` is doing this, you're better off downloading the file in a separate state with the same `file.managed`, and calling a `cmd.run` in another state.

**Comment by egarbi** [comment]
This is not working for me neither:
```
kibana:
  archive:
    - extracted
    - name: /srv
    - source: https://download.elasticsearch.org/kibana/kibana/kibana-4.0.2-linux-x64.tar.gz
    - source_hash: md5=64d8adf3b25dd382803bc041cca5ea46
    - archive_format: tar
    - tar_options: z
    - archive_user: kibana
    - user: kibana
    - group: kibana
    - if_missing: /srv/kibana-4.0.2-linux-x64
    - require:
      - user: kibana

  group.present:
    - name: kibana

  user.present:
    - name: kibana
    - gid: kibana
    - fullname: Kibana service user
    - shell: /bin/bash
    - require:
      - group: kibana
```
File are extracted fine, but user and group ignored.
