### ISSUE TITLE
AssociatePublicIpAddress doesnt work with salt-cloud 2014.7.0

### ISSUE THREAD

**Issue by oba11** [saltstack/salt#19288]
Hi,

I tried bootstrapping a system with the below cloud profile

```
ubuntu-base-public-ip:
  provider: aws
  size: t2.small
  image: ami-d6e7c084
  ssh_username: ubuntu
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: True
      SubnetId: subnet-1a2b3c4d
      SecurityGroupId:
        - sg-1a2b3c4d
```

But if I try auto assigning elastic IP address, it works using below profile

```
ubuntu-base-public-ip:
  provider: aws
  size: t2.small
  image: ami-d6e7c084
  ssh_username: ubuntu
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      allocate_new_eips: True
      SubnetId: subnet-1a2b3c4d
      SecurityGroupId:
        - sg-1a2b3c4d
```

Notes:
I turned off auto-assigning public IP on my subnet settings

Thanks
