### ISSUE TITLE
Binary files mangled by gitfs

### ISSUE THREAD

**Issue by naemono** [saltstack/salt#19294]
File from gitfs appears to be mangled in file size, and md5 after pulling from salt (syndic backed by gitfs).  If I simply check out the git repo from the minion, the file size, and md5 are correct.

Am I doing something wrong?

Salt State
```
random-app-test-file:
  file.managed:
    - name: /tmp/imagemagick_6.7.7.10-6ubuntu4_amd64.deb
    - source: salt://random-app/custom/webp/imagemagick_6.7.7.10-6ubuntu4_amd64.deb
    - source_hash: md5=70598c9a8dfdcec15d9ef0076b5b069c
```
File Attributes from Git source
```
me@source-system:(master) ~ $ ls -l imagemagick_6.7.7.10-6ubuntu4_amd64.deb && md5 imagemagick_6.7.7.10-6ubuntu4_amd64.deb
-rw-r--r--  1 me  groups  222318 Dec 29 11:18 imagemagick_6.7.7.10-6ubuntu4_amd64.deb
MD5 (imagemagick_6.7.7.10-6ubuntu4_amd64.deb) = 70598c9a8dfdcec15d9ef0076b5b069c
```
File Attributes from minion after state is run
```
root@qa-random-app-121801:/tmp# ls -l imagemagick_6.7.7.10-6ubuntu4_amd64.deb && md5sum imagemagick_6.7.7.10-6ubuntu4_amd64.deb
-rw-r--r-- 1 root root 221818 Dec 30 14:09 imagemagick_6.7.7.10-6ubuntu4_amd64.deb
2d1b13c6cdee479b60d5f9226e3c6bc2  imagemagick_6.7.7.10-6ubuntu4_amd64.deb
```
File for testing:
http://xo-custom-packages.s3-website-us-east-1.amazonaws.com/imagemagick_6.7.7.10-6ubuntu4_amd64.deb

Versions
```
root@syndic01:~# salt-syndic --versions-report
           Salt: 2014.7.0
         Python: 2.7.3 (default, Sep 26 2013, 20:03:06)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.0.0
           RAET: Not Installed
            ZMQ: 3.2.2
           Mako: Not Installed
root@qa-random-app-121801:~# salt-minion --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
