### ISSUE TITLE
cmd.rum failing only on 2014.1.13 (Hydorgen) minion

### ISSUE THREAD

**Issue by skinney6** [saltstack/salt#19333]
Most of my minions have Helium installed and this runs fine, only my Hydrogen minion fails.
```
ln -s /usr/bin/ruby /usr/local/bin/ruby:
  cmd.run:
    - creates: /usr/local/bin/ruby
    - only_if: test -f /usr/bin/ruby && test ! -f /usr/local/bin/ruby
```
Error output:
```
  ID: ln -s /usr/bin/ruby /usr/local/bin/ruby
    Function: cmd.run
      Result: False
     Comment: Command "ln -s /usr/bin/ruby /usr/local/bin/ruby" run
     Started: 
    Duration: 
     Changes:                                                                                                                                                  
              ----------
              pid:
                  19322
              retcode:
                  1
              stderr:
                  ln: creating symbolic link `/usr/local/bin/ruby': File exists
              stdout:
```

Most of my machines have ruby compiled from source installed at /usr/local/bin but a few have it installed via atp in /usr/bin. I want to be able to call ruby from cron with confidence so I want to at least have a symlink at /usr/local/bin. If you have suggestions on better ways to do this please feel free. I'm new at this.

Thank you very much. Keep up the good work. Salt is rad!
