### ISSUE TITLE
pkgrepo.managed has a small URL compare problem after transformation

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#19384]
If the URL has host/path like
`{%-   set debian_mirror = "http://cloudfront.debian.net/debian" %}`
then the snippet works fine:

``` saltstack
{{ grains['oscodename'] }}-repo:
  pkgrepo.managed:
    - humanname: Debian {{ grains['oscodename'] }} Repository
    - name: "deb      {{ debian_mirror }}  {{ grains['oscodename'] }}            main contrib non-free"
    - file: /etc/apt/sources.list
```

Without hostname it transforms the URL correctly to only hostname without trailing slash.
But it "oversees" the already written URL with trailing slash in the file:

``` saltstack
debian-security-repo:
  pkgrepo.managed:
    - humanname: Debian Security Repository
    - name: "deb      http://security.debian.org/   {{ grains['oscodename'] }}/updates    main contrib non-free"
    - file: /etc/apt/sources.list
```

=> output (with above lines only):

```
deb http://cloudfront.debian.net/debian wheezy contrib non-free main
deb http://security.debian.org/ wheezy/updates main
deb http://security.debian.org wheezy/updates contrib non-free main
```

EDIT: tested under actual debian package 2014.7.0

**Comment by Reiner030** [comment]
btw. same behavior in other pkgrepo functions. I tried to remove the old line:
```
debian-security-origin-repo:
  pkgrepo.absent:
    - name: "deb http://security.debian.org {{ grains['oscodename'] }}/updates main"
    - file: /etc/apt/sources.list
```
and it seems to work with notification:
```
----------
          ID: debian-security-origin-repo
    Function: pkgrepo.absent
        Name: deb http://security.debian.org wheezy/updates main
      Result: True
     Comment: Removed package repo deb http://security.debian.org wheezy/updates main
     Started: 15:12:18.956454
    Duration: 9235.859 ms
     Changes:   
              ----------
              repo:
                  deb http://security.debian.org wheezy/updates main
```
and without notification that my long line was (tried to) removed.

But file content is still:
```
deb http://security.debian.org/ wheezy/updates main
deb http://security.debian.org wheezy/updates contrib non-free main
```
