### ISSUE TITLE
feature request for network.managed

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#19413]
So if I run,

```
eth0:
  network.managed:
    - enabled: True
    - type: eth
    - dns:
      - 8.8.8.8
      - 8.8.4.4
```

globally it replaces ifcfg-eth0 with the above content and buggers (technical term) the server(s) as it removes all other lines.

What I need to do is change the DNS1=xxxx and DNS2=yyyyy  only and nothing else.

so add something like 
- modify:

and maybe
- remove:

and
- add:
