### ISSUE TITLE
Forced remount because options changed when no options changed for tmpfs filesystems (2014.7)

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#19451]
salt-minion 2014.7.0 (Helium)

I have the following state
```
tmpfs_filesystem:
  mount.mounted:
    - name: /tmp
    - device: tmpfs
    - fstype: tmpfs
    - mkmnt: True
    - persist: True
    - opts:
      - size=4096m
```
My corresponding fstab looks like this:
```
*tmpfs           /tmp    tmpfs   size=4096m      0 0*

mount -l shows also

*tmpfs on /tmp type tmpfs (rw,size=4096m)*
```
But /cat/proc/mounts shows
```
*tmpfs /tmp tmpfs rw,relatime,size=4194304k 0 0*
```
which is the base for deciding if a mount option changed... The problem is now that the numbers in megabytes are not adapted/recalculated to the kb values to be matched.

I have two ideas how to solve this:

1) Recalculate the numbers and do the matching based on that... 4096m gets to 4194304k

or

2) Merge the options of a specific device of the output of mount -l into the option list received by the proc filesystem and use the resulting list as base for the comparison... In that case you would have two size entries; one with megabytes and one with kilobytes...

Any comments/suggestions?
