### ISSUE TITLE
cmd.run state - quiet / output_loglevel quiet have no affect

### ISSUE THREAD

**Issue by msheiny** [saltstack/salt#19479]
I'm running 2014.7.0 on centos 7, under vagrant, without a master (file_client:local). I'm building a formula where I don't want the cmd to be logged but I continue to see this command listed in the output and logs. My snippet looks like this ( i tried both output_loglevel and quiet ) :

```yml
Command to Run:
  cmd.run:
    - name: /cmd/to/hide/from/logs -U "{{user}}" -P "{{pass}}"
    - output_loglevel: quiet
    - quiet: True
    - creates: /etc/krb5.keytab
```

Is this a bug or is there something I'm missing? Thanks!
