### ISSUE TITLE
user provided i386 deb package on amd64 with multiarch not correctly reported

### ISSUE THREAD

**Issue by ferreol** [saltstack/salt#19512]
Hi
I am using latest salt on debian wheezy amd64.
I am installing a commercial i386 package with multiarch, with following script

it reports is fails install/is not correctly installed, though it installed among with dependencies of package

I have done sucessfully other scenarios : 
- install i386 libc from repo, corretly reported
- install amd64 user provided .deb, installed with source salt://*.deb and correctly reported
```
add_i386_architecture:
  cmd.run:
    - name: dpkg --add-architecture i386
    - unless: dpkg --print-foreign-architectures | grep i386

libc6_i386:
  pkg.installed:
    - name: libc6:i386

bcompare_i386:
  pkg.installed:
    - name: bcompare:i386
    - sources:
      - bcompare: salt://bcompare/bcompare-4.0.3.19420_i386.deb
```
```
root@debian:/srv/salt/bcompare# salt 'debian' state.sls bcompare
debian:
----------
          ID: add_i386_architecture
    Function: cmd.run
        Name: dpkg --add-architecture i386
      Result: True
     Comment: Command "dpkg --add-architecture i386" run
     Started: 10:18:30.328552
    Duration: 78.404 ms
     Changes:
              ----------
              pid:
                  3616
              retcode:
                  0
              stderr:

              stdout:

----------
          ID: libc6_i386
    Function: pkg.installed
        Name: libc6:i386
      Result: True
     Comment: The following packages were installed/updated: libc6:i386.
     Started: 10:18:30.407738
    Duration: 42088.251 ms
     Changes:
              ----------
              gcc-4.7-base:i386:
                  ----------
                  new:
                      4.7.2-5
                  old:

              libc6-i686:i386:
                  ----------
                  new:
                      2.13-38+deb7u6
                  old:

              libc6:i386:
                  ----------
                  new:
                      2.13-38+deb7u6
                  old:

              libgcc1:i386:
                  ----------
                  new:
                      1:4.7.2-5
                  old:

----------
          ID: bcompare_i386
    Function: pkg.installed
        Name: bcompare:i386
      Result: False
     Comment: The following packages failed to install/update: bcompare.
     Started: 10:20:42.937088
    Duration: 40374.03 ms
     Changes:
              ----------
              bcompare:i386:
                  ----------
                  new:
                      4.0.3-19420
                  old:


              libfontconfig1:
                  ----------
                  new:
                      2.9.0-7.1
                  old:

       
              libstdc++6:i386:
                  ----------
                  new:
                      4.7.2-5
                  old:


[dependencies truncated]

              uuid-runtime:
                  ----------
                  new:
                      2.20.1-5.3
                  old:

              zlib1g:i386:
                  ----------
                  new:
                      1:1.2.7.dfsg-13
                  old:

```
```
root@debian:/srv/salt/bcompare# salt 'debian' state.sls bcompare
debian:
----------
          ID: bcompare_i386
    Function: pkg.installed
        Name: bcompare:i386
      Result: False
     Comment: The following packages failed to install/update: bcompare.
     Started: 10:24:42.811137
    Duration: 18146.356 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
root@debian:/srv/salt/bcompare# less /var/log/salt/minion
root@debian:/srv/salt/bcompare# dpkg -l | grep bcompare
ii  bcompare                           4.0.3-19420                   i386         Beyond Compare 4

```

**Comment by pitatus** [comment]
wondering what else may be available as far as error output, try shutting down the minion and execute a local state with salt-call, and include the output (and a --versions-report):
```
bcompare_i386:
  pkg.installed:
    - name: bcompare:i386
    - sources:
      - bcompare: salt://bcompare/bcompare-4.0.3.19420_i386.deb
```

**Comment by rallytime** [comment]
Since we never heard anything back on this one, I am going to close it out. If problems endure, please leave a comment and we will certainly open this issue and address any concerns. Thanks!

**Comment by sash-kan** [comment]
same problem (i386 package, amd64 minion).

sls file:

```
packages_for_class_debs:
  pkg.installed:
    - name: s4a:i386
    - sources:
      # from http://s4a.cat/
      - s4a: salt://files/S4A16.deb
    - require:
      - cmd: add_i386_architecture
add_i386_architecture:
  cmd.run:
    - name: dpkg --add-architecture i386 && apt-get update
    - unless: dpkg --print-foreign-architectures | grep i386
```
salt-call output (foreign architecture i386 has already been added.):

```
$ sudo salt-call --local state.apply
[ERROR   ] Made the following changes:
's4a:i386' changed from 'absent' to '1.6'

local:
----------
          ID: packages_for_class_debs
    Function: pkg.installed
        Name: s4a:i386
      Result: False
     Comment: The following packages failed to install/update: s4a
     Started: 15:29:55.718746
    Duration: 74596.759 ms
     Changes:   
              ----------
              s4a:i386:
                  ----------
                  new:
                      1.6
                  old:

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  74.597 s
```
if i try to remove the architecture from the name (s4a:i386 -> s4a), the error is the same:
```
$ sudo salt-call --local state.apply
[ERROR   ] The following packages failed to install/update: s4a
local:
----------
          ID: packages_for_class_debs
    Function: pkg.installed
        Name: s4a
      Result: False
     Comment: The following packages failed to install/update: s4a
     Started: 15:46:33.506277
    Duration: 79247.147 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  79.247 s
```
versions report:
```
$ sudo salt-call --versions-report  
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
```
