### ISSUE TITLE
salt-ssh running git clone with not root user

### ISSUE THREAD

**Issue by stolendog** [saltstack/salt#19532]
I am using git.latest on my state file with user www-data, it works using vagrant and salt minion, but when I run it using salt-ssh for servers it cannot clone the repo. 

```
Comment: Cloning into '/var/www/repo'...
              fatal: cannot exec '/tmp/.ubuntu_d2fedf__salt/salt/templates/git/ssh-id-wrapper': Permission denied
              fatal: unable to fork
```

```
gitclone:
  git.latest:
    - name: git@url:test.git
    - user: www-data
    - rev: master
    - target: /var/www/repo
    - identity: /var/www/.ssh/id_rsa
    - require:
      - pkg: git
```

but if I use root user for cloning it works using salt-ssh. 

```
gitclone:
  git.latest:
    - name: git@url:test.git
    - rev: master
    - target: /var/www/repo
    - identity: /var/www/.ssh/id_rsa
    - require:
      - pkg: git
```

```
salt-ssh --versions
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: Not Installed
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: Not Installed
           RAET: Not Installed
            ZMQ: Not Installed
           Mako: Not Installed
```

more info in roster file I have sudo enabled:

```
web_dev:
  host: hostname
  user: ubuntu         
  sudo: True
```
