### ISSUE TITLE
Azure: using create_virtual_machine_deployment triggers conflicts when deployment already exists

### ISSUE THREAD

**Issue by traxair** [saltstack/salt#19569]
A fix for this is to separate deployment creation from VM creation.
Use `create_virtual_machine_deployment ` then if a conflict error is thrown use `add_role`. We could create the deployment before but some args are mising (`package_url`?)
```
           Salt: 2015.2.0-75-gea2b826
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.3
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.4.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

**Comment by rallytime** [comment]
Thanks for the request @traxair. Approved as a feature request. Also, we'd gladly accept a pull request if you'd like to submit one with your changes.

**Comment by traxair** [comment]
Well it's supposedly been fixed with commit 0b06808

**Comment by rallytime** [comment]
@traxair Ah sorry, the original reference was just to your fork, so I didn't know it had been merged into salt. If this is working for you, can this issue be closed then?

**Comment by traxair** [comment]
Well there is a strange issue, it used to work now it doesn't. I tested with the following:
**profile**
``` 
azure-medium-service:
  provider: azure
  image: 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20141125-en-us-30GB'
  size: Medium
  location: 'West Europe'
  ssh_username: ****
  ssh_password: ****
  slot: production
  media_link: 'http://****.blob.core.windows.net/vhds'
  service_name: 'mymachine-cluster'
  volumes:
    - { size: 200 }
``` 
**map**
``` 
azure-medium-service:
  - mymachine-1
      port: 22
  - mymachine-2
      port: 23
``` 

Now `mymachine-1` gets created, but `mymachine-2` fails at add_role with a WindowsAzureConflict error.

After that, if I modify the mal file by 
``` 
azure-medium-service:
  - mymachine-2
      port: 23
  - mymachine-3
      port: 24
``` 
`mymachine-2` gets created and `mymachine-3`fails at add_role with a WindowsAzureConflict error.

Can someone reproduce the issue? I really don't see what is happening
