### ISSUE TITLE
Execute a state when any of several other states change

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#19592]
I was trying to use 'onchanges' to execute a state whenever any of several other states change, but it seems the logic currently requires *all* the states to change before an 'onchanges' state will execute.

Basically, I have four states that configure a registry setting (my minions are Windows boxes). If any of those states result in a change, I'd like to execute a cmd.run state. Is 'onchanges' not the right way to do that?

Not sure if this is a feature request, a bug, or a usage question...

**Comment by rallytime** [comment]
Thanks for the report/question @lorengordon. Can you post the output of `salt --versions-report` as well as your states? That will help us either answer your question or reproduce what your seeing if this is indeed a bug.

**Comment by lorengordon** [comment]
Sure, here you go... I kind of worked around the issue using `listen_in`, but that still results in an extra execution of the cmd.run state.

*c:\salt\salt-call --local --versions*:
```
           Salt: 2014.7.0
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 122, in salt_call
  File "salt/cli/__init__.py", line 370, in run
  File "salt/utils/parsers.py", line 126, in parse_args
  File "salt/utils/parsers.py", line 194, in print_versions_report
AttributeError: 'module' object has no attribute 'EX_OK'
```

*init.sls* (in file_roots at `salt://netbanner`):
```
{% from "netbanner/map.jinja" import netbanner with context %}

# This sls file will install Microsoft Netbanner and update the Local Group 
# Policy Editor configuration so that the Netbanner settings can be managed
# via LGPO. The sls will also start|restart the 'Netbanner' process.

#IMPORTANT:
# Microsoft does not distribute the Netbanner package. It is rather difficult
# to come by. Also, the Netbanner license prevents distribution, so we cannot 
# provide it via Github or a CDN. The only known source is below, and it 
# requires a government-provided Common Access Card (CAC) to gain access to the 
# site.
#  - https://software.forge.mil/sf/go/rel3968

#Dependencies:
#  - Microsoft .NET 4 for Netbanner 2.x.
#  - Microsoft .NET 2 for Netbanner 1.x.
#  - Salt 2014.7.0 or greater (required for the 'test' state).
#  - Properly configured salt winrepo package manager, in a master or 
#    masterless configuration.
#  - Package definition for Netbanner must be available in the winrepo 
#    database. The installer can be obtained from the site(s) listed above.

#Get the latest installed version of .NET
{% set dotnet_version = salt['cmd.run'](
    '(Get-ChildItem "HKLM:\\SOFTWARE\\Microsoft\\NET Framework Setup\\NDP" -recurse | \
     Get-ItemProperty -name Version -EA 0 | \
     Where { $_.PSChildName -match "^(?!S)\p{L}"} | \
     Select Version | Sort -Descending Version | Select -First 1).Version', 
    shell='powershell') 
%}

#Check if minimum required .NET version is available
{% if dotnet_version[:1] not in netbanner.dotnet_versions %}
#Fail due to missing .NET prerequisite
prereq_dotnet_{{ netbanner.dotnet_versions | join('_') | string }}:
  test.configurable_test_state:
    - name: '.NET {{ netbanner.dotnet_versions | join(', ') | string }} prerequisite'
    - changes: False
    - result: False
    - comment: 'Netbanner {{ netbanner.version | string }} requires a .NET version in this list: {{ netbanner.dotnet_versions | join(', ') | string }}. Detected .NET version: {{ dotnet_version | string }}'

{% else %}
#Install and Apply Netbanner Settings
netbanner:
  pkg.installed:
    - name: 'Netbanner'
    - version: {{ netbanner.version }}
    - listen_in:
      - cmd: netbanner
  cmd.run:
    - name: 'Get-Process | where {$_.ProcessName -match "NetBanner"} | Stop-Process; Start-Process "{{ netbanner.netbanner_exe }}"'
    - shell: powershell

# The 'listen_in' requisite results in the cmd.run state executing every time,
# rather than only when there are changes. It works, but not ideal.
# 'onchanges' doesn't support execution when *any* state changes, only all of 
# them. When that's supported, 'onchanges_in' will replace the 'listen_in' 
# requisite.

NetBanner.admx:
  file.managed:
    - name: {{ netbanner.admx_name }}
    - source: {{ netbanner.admx_source }}
    - require:
      - pkg: netbanner

NetBanner.adml:
  file.managed:
    - name: {{ netbanner.adml_name }}
    - source: {{ netbanner.adml_source }}
    - require:
      - pkg: netbanner

{% endif %}
```

*netbanner.custom.sls*:
```
{% from "netbanner/map.jinja" import netbanner with context %}

# This sls file will apply a Netbanner configuration to the system. Netbanner
# will be installed if it is not already, via the 'include' statement. The 
# Netbanner configuration is read from map.jinja, which supports customization 
# via pillar. Any configuration that results in a change will also restart the
# 'Netbanner' process to read the change and display the configured banner.

include:
  - netbanner

CustomSettings:
  reg.present:
    - name: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\NetBanner\CustomSettings'
    - value: {{ netbanner.CustomSettings }}
    - vtype: REG_DWORD
    - reflection: True
    - require:
      - pkg: netbanner
    - listen_in:
      - cmd: netbanner

CustomBackgroundColor:
  reg.present:
    - name: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\NetBanner\CustomBackgroundColor'
    - value: {{ netbanner.CustomBackgroundColor }}
    - vtype: REG_DWORD
    - reflection: True
    - require:
      - pkg: netbanner
    - listen_in:
      - cmd: netbanner

CustomForeColor:
  reg.present:
    - name: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\NetBanner\CustomForeColor'
    - value: {{ netbanner.CustomForeColor }}
    - vtype: REG_DWORD
    - reflection: True
    - require:
      - pkg: netbanner
    - listen_in:
      - cmd: netbanner

CustomDisplayText:
  reg.present:
    - name: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\NetBanner\CustomDisplayText'
    - value: '{{ netbanner.CustomDisplayText }}'
    - vtype: REG_SZ
    - reflection: True
    - require:
      - pkg: netbanner
    - listen_in:
      - cmd: netbanner

#'onchanges' doesn't support execution when *any* state changes, only all of them.
#When that's supported, 'onchanges_in' will replace the 'listen_in' requisites.
```

**Comment by basepi** [comment]
Ooh, sounds like we're AND-ing, not OR-ing, and we definitely want to OR.

@thatch45 ping!

**Comment by rallytime** [comment]
We are indeed AND-ing. Here's some simpler steps to reproduce:

changes.sls:
```
state_to_change:
  cmd.run:
    - name: echo "Changed!"

change_1:
  test.succeed_with_changes:
    - name: foo
    - onchanges_in:
      - cmd: state_to_change

change_2:
  test.succeed_with_changes:
    - name: bar
    - onchanges_in:
      - cmd: state_to_change

no_change:
  test.succeed_without_changes:
    - name: baz
    - onchanges_in:
      - cmd: state_to_change
```
And the output. Note: the state that should run after each `onchanges_in` statement only runs once at the end of the state run, which looks to be AND-ing and not OR-ing with `salt-call --local state.sls changes`:
```
local:
----------
          ID: no_change
    Function: test.succeed_without_changes
        Name: baz
      Result: True
     Comment: Success!
     Started: 22:26:53.869047
    Duration: 1.003 ms
     Changes:
----------
          ID: change_1
    Function: test.succeed_with_changes
        Name: foo
      Result: True
     Comment: Success!
     Started: 22:26:53.870273
    Duration: 0.768 ms
     Changes:
              ----------
              testing:
                  ----------
                  new:
                      Something pretended to change
                  old:
                      Unchanged
----------
          ID: change_2
    Function: test.succeed_with_changes
        Name: bar
      Result: True
     Comment: Success!
     Started: 22:26:53.871252
    Duration: 0.777 ms
     Changes:
              ----------
              testing:
                  ----------
                  new:
                      Something pretended to change
                  old:
                      Unchanged
----------
          ID: state_to_change
    Function: cmd.run
        Name: echo "Changed!"
      Result: True
     Comment: State was not run because onchanges req did not change
     Started:
    Duration:
     Changes:

Summary
------------
Succeeded: 4 (changed=2)
Failed:    0
------------
Total states run:     4
```

**Comment by lorengordon** [comment]
Thanks for finding another way to test the issue. fwiw, my preferred behavior would be for the state(s) specified by the 'onchanges_in' requisite to run only once regardless of how many 'changes' triggered the state, and at the end of the run.

**Comment by rallytime** [comment]
@lorengordon Maybe I am misunderstanding what you're trying to do. I was attempting to write something simpler to test with. I interpreted "I was trying to use 'onchanges' to execute a state whenever any of several other states change" to mean that `state_to_change` should execute whenever the other states that had changes. In my testing, I wanted two states to "have changes" and one to not have changes, just to make sure the order was executing as I expected.

The states that I have given the `onchanges_in` requisite will execute only once, but they should trigger the `state_to_change` to execute if there are changes on the states with the requisites.However, after reading your last comment, I am not sure what behavior you're expecting. Can you clarify?

**Comment by lorengordon** [comment]
I'm equating *any* to an *or* condition. I expect the 'onchanges' state to run one time, regardless of how many changes there were. For example, let's reverse the logic from 'onchanges_in' to 'onchanges'. It makes it more evident to me that there is some 'AND' logic requiring all the states to change, versus 'OR' logic that would require only one state to change. My expectation of the sls below would be for the 'state_to_change' to run one time.

*test.sls*:
```
state_to_change:
  cmd.run:
    - name: echo "Changed!"
    - onchanges:
      - test: change_1
      - test: change_2
      - test: no_change

change_1:
  test.succeed_with_changes:
    - name: foo

change_2:
  test.succeed_with_changes:
    - name: bar

no_change:
  test.succeed_without_changes:
    - name: baz
```

*results*:
```
PS C:\Users\Loren\Downloads> C:\salt\salt-call.exe --local state.sls test
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'test/init.sls'
[INFO    ] Running state [foo] at time 18:11:29.428000
[INFO    ] Executing state test.succeed_with_changes for foo
[INFO    ] Installed Packages:
testing changed from Unchanged to Something pretended to change

[INFO    ] Completed state [foo] at time 18:11:29.443000
[INFO    ] Running state [bar] at time 18:11:29.443000
[INFO    ] Executing state test.succeed_with_changes for bar
[INFO    ] Installed Packages:
testing changed from Unchanged to Something pretended to change

[INFO    ] Completed state [bar] at time 18:11:29.459000
[INFO    ] Running state [baz] at time 18:11:29.459000
[INFO    ] Executing state test.succeed_without_changes for baz
[INFO    ] Success!
[INFO    ] Completed state [baz] at time 18:11:29.459000
[INFO    ] Executing command 'attrib -R "c:\\salt\\var\\cache\\salt\\minion\\sls.p"' in directory 'C:\\Users\\Loren'
local:
----------
          ID: change_1
    Function: test.succeed_with_changes
        Name: foo
      Result: True
     Comment: Success!
     Started: 18:11:29.428000
    Duration: 15.0 ms
     Changes:
              ----------
              testing:
                  ----------
                  new:
                      Something pretended to change
                  old:
                      Unchanged
----------
          ID: change_2
    Function: test.succeed_with_changes
        Name: bar
      Result: True
     Comment: Success!
     Started: 18:11:29.443000
    Duration: 16.0 ms
     Changes:
              ----------
              testing:
                  ----------
                  new:
                      Something pretended to change
                  old:
                      Unchanged
----------
          ID: no_change
    Function: test.succeed_without_changes
        Name: baz
      Result: True
     Comment: Success!
     Started: 18:11:29.459000
    Duration: 0.0 ms
     Changes:
----------
          ID: state_to_change
    Function: cmd.run
        Name: echo "Changed!"
      Result: True
     Comment: State was not run because onchanges req did not change
     Started:
    Duration:
     Changes:

Summary
------------
Succeeded: 4 (changed=2)
Failed:    0
------------
Total states run:     4
```

**Comment by basepi** [comment]
Yes, as far as I know, the desired behavior is that it would run exactly once, if one of more of the onchanges states had changes. We just need to change it from AND-ing the results to OR-ing the results.

**Comment by rallytime** [comment]
Yeah I was not reading this closely, which was why I was confused. I didn't actually see the "State was not run because...". We're talking about the same thing, I just wasn't reading the comment in the state_to_change appropriately. My apologies!

**Comment by lorengordon** [comment]
It also does say that 4 states succeeded, even though only 3 actually ran. I was confused by that at first as well. Maybe a secondary issue is that we need a distinct way to categorize requisite states that don't execute. :)

**Comment by basepi** [comment]
A state which doesn't run as a result of an onchanges requisite is considered to be successful. Semantics. *shrugs*

Most other requisites are more cut and dry with regards to success. If a state doesn't run because a require fails, that state is pretty obviously failing. But not running because another state was successful (if not changing) is successful as far as I'm concerned. Mostly because I don't think it's useful to add another whole category which only applies to the onchanges requisite.

**Comment by HerrBerg** [comment]
Has there been any progress on this issue?
I just ran into the same problem using salt v2015.5.0

**Comment by florianb** [comment]
Hi, i probably have a similar problem - i am new to the SaltStack-universe so probably it's just a wrong use of the states-requisites -- i'm using `2015.8.8.2 (Beryllium)`.

I am dynamically generating states based on a pillar - adding a `onchanges_in`-dependency to every generated config-file in order to make the nginx-service reload afterwards:

```yaml
nginx:
  pkg:
    - installed
  service.running:
    - enable: True
    - reload: True

#...

/etc/nginx/nginx.conf:
  file.managed:
    - source:
      - salt://proxy/nginx.conf
    - onchanges_in:
       - service: nginx

{% for name, params in pillar['websites'].iteritems() %}
/etc/nginx/sites-available/{{ name }}:
  file.managed:
    - source: salt://proxy/site-available.templ
    - user: root
    - group: root
    - mode: 644

    - template: jinja
    - defaults:
        name: {{ name }}
        params: {{ params }}

    - onchanges_in:
       - service: nginx
{% endfor %}
```

Changing the templ-file now results in:

```yaml
----------
          ID: /etc/nginx/sites-available/fancy.site
    Function: file.managed
      Result: True
     Comment: File /etc/nginx/sites-available/fancy.site updated
     Started: 11:51:05.707822
    Duration: 15.089 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -2,7 +2,7 @@
                     listen            80 default_server;
                     server_name       fancy.site www.fancy.site *.fancy.site;
                   
                  -  root              /osrv/proxy/sites/fancy.site;
                  +  root              /srv/proxy/sites/fancy.site;
                   }
                   
#...
----------
          ID: nginx
    Function: service.running
      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 
    Duration: 
     Changes: 

Summary for local
-------------
Succeeded: 16 (changed=1)
Failed:     0
-------------
Total states run:     16
```
If i instead use `watch_in`:

```yaml
/etc/nginx/nginx.conf:
  file.managed:
    - source:
      - salt://proxy/nginx.conf
    - watch_in:
       - service: nginx

{% for name, params in pillar['websites'].iteritems() %}
/etc/nginx/sites-available/{{ name }}:
  file.managed:
    - source: salt://proxy/site-available.templ
    - user: root
    - group: root
    - mode: 644

    - template: jinja
    - defaults:
        name: {{ name }}
        params: {{ params }}

    - watch_in:
       - service: nginx
{% endfor %}
```

Nginx gets restarted as expected:

```yaml
----------
          ID: /etc/nginx/sites-available/fancy.site
    Function: file.managed
      Result: True
     Comment: File /etc/nginx/sites-available/fancy.site updated
     Started: 12:04:19.047530
    Duration: 12.886 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -2,7 +2,7 @@
                     listen            80 default_server;
                     server_name       fancy.site www.fancy.site *.fancy.site;
                   
                  -  root              /srv/proxy/sites/fancy.site;
                  +  root              /psrv/proxy/sites/fancy.site;
                   }
                
----------
          ID: nginx
    Function: service.running
      Result: True
     Comment: Service reloaded
     Started: 12:04:19.093889
    Duration: 23.458 ms
     Changes:   
              ----------
              nginx:
                  True

Summary for local
-------------
Succeeded: 16 (changed=2)
Failed:     0
-------------
Total states run:     16
```

It seems like the behaviour is unexpected as soon as **one** `onchanges_in` is involved. I proved that by leaving the site-states at `watch_in` and changing only the nginx.conf to `onchanges_in`,

Probably this issue does not belong here - i just can't make it run and this issue seemed to be somehow similar. I'm sorry if the behavior is caused by a mistake on my side - thanks anyway! :candy:
