### ISSUE TITLE
Feature: enable salt-cloud to run a list of commands defined in a cloud profile

### ISSUE THREAD

**Issue by alex-leonhardt** [saltstack/salt#19608]
The idea: 

I'd like to be able to run arbitrary commands either after salt cloud's bootstrap script has run, or if that was skipped.

I'd like to specify that list of commands as part of the cloud profile for a type of machine instance, in YAML format. Example:
```
custom_profile:
  provider: gce
  location: us
  script: default (or whatever)
  inline_script:
    - "command 1"
    - "command 2"
    - "...."
```

The above would then convert into a bash script and execute the commands in sequence, at first probably regardless of whether the previous command was successful (as one could do that as part of the command for now).

I will be working on this over the next week or two and hope to get this to work, if someone's interested in this, please get in touch.

**Comment by techhat** [comment]
Why not just use a custom script that wraps the bootstrap script, and then runs your custom commands in the order you want?

**Comment by alex-leonhardt** [comment]
Because I don't want to have to place a script (as root) somewhere so that salt-cloud can access it. I did see that you can specify a full path for the script, but if I'd simply like some 2-3 commands run in order (not necessarily same order or commands) on 20 profiles, I'd have to manage another 20 files, instead of 1 file with the 20 profiles. I also find it to be more obvious what instance will do once bootstrapped by just looking at the profile. If it was anything more complex, and across several profiles, I'd agree, a separate bootstrap script would be more useful and have used that previously.

**Comment by techhat** [comment]
Thanks for the clarification, @alex-leonhardt.

**Comment by rallytime** [comment]
Thanks for the request and for starting to tackle this one!

**Comment by mspinassi** [comment]
I'm not sure if it should be placed into another ticket, but wouldn't it be easier to convert the `script` parameter into a list?

For example:

```
custom_profile:
  provider: gce
  location: us
  script:
    - /etc/salt/cloud.deploy.d/my_custom_pre-script.sh
    - /etc/salt/cloud.deploy.d/generate_pranoid_firewall_rules.sh
    - CentOS
```

Under this approach, we can still have the benefits of salt default scripts, but also letting us do some prior stuff, like adding a proxy config.

Does it makes sense?
