### ISSUE TITLE
state process.absent is failing on Ubuntu 14.04 because psutil is not installed

### ISSUE THREAD

**Issue by wonderslug** [saltstack/salt#19659]
Ran into an issue trying to run process.absent state on Ubuntu 14.04 and worked out that there is no dependency on python-psutil package being installed by default.  This is using the standard ppa install.

This appears to be needed for the for the states.process as well as anything using the modules/ps.py

**Comment by rallytime** [comment]
So specific module dependencies are evaluated on the fly -- so if you install the dependency for a module earlier in the state run, salt will automatically reload the modules afterwards and your specific module will be loaded in time for it to run. We work very hard to keep core dependencies for salt to a minimum, so you might just try using a requisite state to make sure psutil is installed on your minion before running the process.absent state:
```
install_psutil:
  pkg.installed:
    - name: python-psutil
    - require_in:
        - process: your_process_state_id
```
