### ISSUE TITLE
file.managed with `contents` and without `contents_newline` seems broken

### ISSUE THREAD

**Issue by MrMarvin** [saltstack/salt#19669]
The following state gave us a headache today:
```
/etc/zookeeper/conf/myid:
  file.managed:
    - contents: {{ "2" }}
    - require:
      - pkg: zookeeper
```

Which resulted in this error:
```
----------
          ID: /etc/zookeeper/conf/myid
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1533, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1276, in managed
                  if contents and not contents.endswith('\n'):
              AttributeError: 'int' object has no attribute 'endswith'
     Started: 23:00:05.381614
    Duration: 8.175 ms
```
Which is weird because the contents is a string. Really.
Workaround is to explicitly disable newline addition:
```
/etc/zookeeper/conf/myid:
  file.managed:
    - contents: {{ "2" }}
    - contents_newline: False
    - require:
      - pkg: zookeeper
``` 

Version in use: v2014.7.0 + some commits, including ea4cf06a78d92e019488c3016318eee207cbbbf2, cherry-picked on top (see https://github.com/sinnerschrader/salt/commits/szops_production).

**Comment by basepi** [comment]
Looking at your example, I could potentially see Jinja dropping the quotes when that is evaluated, and so the file ending up like this after the jinja step:

```
/etc/zookeeper/conf/myid:
  file.managed:
    - contents: 2
    - require:
      - pkg: zookeeper
```

In which case contents will evaluate to an integer in the YAML step.

Regardless, we should be forcing contents to a string, that should solve this nicely. Thanks for the report!
