### ISSUE TITLE
host.present drops last newline

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#19738]
```salt-call 2014.7.0 (Helium)```

e.g. from your docu:
```
server1:
  host.present:
    - ip: 192.168.0.42
    - names:
      - server1
      - florida
```
creates the EOL direct without linebreak so that some services have problem reading this file (sorry forgotten which ones... I had this problem since 2014.1.7). 

My temporary fix for it:
```
/etc/hosts:
  file.append:
    - text: |
        ##
        ## end of hosts
```
