### ISSUE TITLE
pkgrepo.managed could better handle long keyids

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#19737]
```salt-call 2014.7.0 (Helium)```

I got from https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Debian-7
informations howto access their repo:

```
hhvm.com-repo:
  pkgrepo.managed:
    - humanname: HHVM Apt Repository
    - name: "deb http://dl.hhvm.com/debian/ {{ grains['oscodename'] }} main"
    - dist: stable
    - file: /etc/apt/sources.list.d/hhvm.list
    - keyserver: keyserver.ubuntu.com
    - keyid: 0x5a16e7281be7a449
```

but this fails with:
```
Comment: Failed to configure repo 'deb http://dl.hhvm.com/debian/ wheezy main': Error: key retrieval failed: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.W4Pd3bTU9z --trustdb-name /etc/apt//trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-wheezy-stable.gpg --keyserver keyserver.ubuntu.com --logger-fd 1 --recv-keys 6491630072354022473
              gpg: "6491630072354022473" not a key ID: skipping
```
because Salt is converting the KeyID to decimal one.

With quotation mark ```    - keyid: "0x5a16e7281be7a449"```
or shortened KeyID (last 8 chars) ```    - keyid: 1BE7A449```
it works:
```
     Comment: Configured package repo 'deb http://dl.hhvm.com/debian/ wheezy main'
```
