### ISSUE TITLE
`listen` doesn't seem to work with `require`

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#19730]
When using `listen` and `require`, it appears the state added by the `listen` doesn't know about the state specified in the `require` statement. This causes a failure when it seems it should work.

*test.sls*:
```
state_1:
  cmd.run:
    - name: echo "state_1"

state_2:
  cmd.run:
    - name: echo "state_2"

state_3:
  cmd.run:
    - name: echo "state_3"
    - require:
      - cmd: state_1
    - listen:
      - cmd: state_2
```
*results*:
```
local:
----------
          ID: state_1
    Function: cmd.run
        Name: echo "state_1"
      Result: True
     Comment: Command "echo "state_1"" run
     Started: 11:50:18.612000
    Duration: 31.0 ms
     Changes:
              ----------
              pid:
                  4416
              retcode:
                  0
              stderr:

              stdout:
                  "state_1"
----------
          ID: state_2
    Function: cmd.run
        Name: echo "state_2"
      Result: True
     Comment: Command "echo "state_2"" run
     Started: 11:50:18.643000
    Duration: 16.0 ms
     Changes:
              ----------
              pid:
                  3972
              retcode:
                  0
              stderr:

              stdout:
                  "state_2"
----------
          ID: state_3
    Function: cmd.run
        Name: echo "state_3"
      Result: True
     Comment: Command "echo "state_3"" run
     Started: 11:50:18.659000
    Duration: 31.0 ms
     Changes:
              ----------
              pid:
                  3604
              retcode:
                  0
              stderr:

              stdout:
                  "state_3"
----------
          ID: listener_state_3
    Function: cmd.mod_watch
        Name: echo "state_3"
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     cmd: state_1
     Started:
    Duration:
     Changes:

Summary
------------
Succeeded: 3 (changed=3)
Failed:    1
------------
Total states run:     4
```
*versions*:
```
PS C:\Windows\system32> C:\salt\salt-call.exe --local --versions
           Salt: 2014.7.0
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 122, in salt_call
  File "salt/cli/__init__.py", line 370, in run
  File "salt/utils/parsers.py", line 126, in parse_args
  File "salt/utils/parsers.py", line 194, in print_versions_report
AttributeError: 'module' object has no attribute 'EX_OK'
```

**Comment by rallytime** [comment]
@lorengordon I think you actually want to use `watch` instead of `listen` for that second requisite. `listen` was added to exactly mirror the behavior of a `watch` but without modifying the order in which states are run. It's not designed to be used alongside order-modifying requisites like `require`.

**Comment by lorengordon** [comment]
Ahh, ok. I had fiddled with `watch` previously when I was trying to get `onchanges` to work, and I couldn't get `watch` to do what I wanted either. That's how I got onto `listen`. But now that I'm introducing the `require` statement, the combination with `watch` is doing what I want after all and it's `listen` that isn't working. Go figure! :) Thanks for setting me straight!

**Comment by rallytime** [comment]
No problem! I'm going to go ahead and close this one, but if you have more issues, leave a note and I'd be happy to open this back up. Cheers!

**Comment by tbaker57** [comment]
Hi there,
I've come across this too. I always thought listen(_in) was a drop in replacement for watch(_in) for service states. But with a simple sls such as
```
httpd:
  pkg:
    - installed

httpd_service:
  service:
    - running
    - name: httpd
    - enable: True
    - require:
      - pkg: httpd

/etc/httpd/conf/httpd.conf:
  file.managed:
    - source: salt://httpd/files/httpd.conf
    - listen_in:
      - service: httpd_service
```
changing the file /etc/httpd/conf/httpd.conf results in 
```
          ID: listener_httpd_service
    Function: service.mod_watch
        Name: httpd
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     pkg: httpd
     Started: 
    Duration: 
     Changes: 
```
which is an odd error message since the httpd package is already installed. If I use watch_in instead of listen_in, it works as expected (the service is reloaded).

Is it  worth a note in the documentation about when (if ever) 'listen' and 'require' can be used between dependent states ? 

cheers,
Tim
