### ISSUE TITLE
iptables --set-xmark placed too early

### ISSUE THREAD

**Issue by saxonww** [saltstack/salt#19749]
Given the following state:

```
state_name:
  iptables.append:
    - table: mangle
    - chain: PREROUTING
    - jump: MARK
    - source: {{ ip }}
    - proto: {{ proto }}
    - dport: {{ from }}
    - set-xmark: '{{ mark }}/{{ mask }}'
    - save: True
```

The output produced (by 2014.7.0) is this:

```
  /sbin/iptables -t mangle -A PREROUTING -p {{ proto }} --dport {{ from }} \
          --set-xmark {{ mark }}/{{ mask }} --source {{ ip }} --jump MARK
```

The correct output is this:

```
  /sbin/iptables -t mangle -A PREROUTING -p {{ proto }} --dport {{ from }} \
          --source {{ ip }} --jump MARK --set-xmark {{ mark }}/{{ mask }}
```

I'm not sure if I'm writing the state correctly or not, but after checking iptables.py it doesn't look like set-xmark is understood as an after_jump kwarg.
