### ISSUE TITLE
Missing python-dateutil. Ignoring job <jobname>

### ISSUE THREAD

**Issue by mortis1337** [saltstack/salt#19755]
Missing python-dateutil. Ignoring job <jobname>.
You get this error if python-dateutil isnt installed on a minion that has a schedule like this : 
```
schedule:
  restart-minion:
    function: service.restart
    args:
      - salt-minion
    splay: 15
    when:
      - Monday 10:00am
      - Tuesday 10:00am
      - Wednesday 10:00am
      - Thursday 11:51am
```
Maybe python-dateutil should be a dependency somewhere?
