### ISSUE TITLE
pip.installed can't read requirements file from salt:// url when running as an unprivileged user

### ISSUE THREAD

**Issue by eykd** [saltstack/salt#19767]
On 2014.7.0, given something like this:

```
mysite-reqs:
  pip.installed:
    - requirements: salt://mysite/requirements.txt
    - user: mysite
    - bin_env: /opt/env/mysite
    - cwd: /opt/env/mysite
```

I get this error:

```
          ID: mysite-reqs
    Function: pip.installed
      Result: False
     Comment: Unable to process requirements file salt://mysite/requirements.txt. Error: Could not open requirements file: [Errno 13] Permission denied: '/var/cache/salt/minion/files/base/mysite/requirements.txt'
              Storing debug log for failure in /home/mysite/.pip/pip.log
     Started: 14:26:00.517126
    Duration: 490.407 ms
     Changes:
```

Examining the locally cached `requirements.txt`, I see it's accessible only by root:

```
vagrant@vagrant:~$ sudo ls -lh /var/cache/salt/minion/files/base/mysite/requirements.txt
-rw------- 1 root root 36 Jan 15 14:01 /var/cache/salt/minion/files/base/mysite/requirements.txt
```

So of course my `mysite` user won't be able to read it.

**Comment by basepi** [comment]
Ah, good catch, thanks for your detective work.

This bug makes perfect sense, and it's just a use-case we overlooked.

I think the solution here is to cache the file as normal, and then do one of two things:

1. Pipe the contents of the file into the pip command instead of having pip try to read them from a file. Not sure if pip supports this, that's the main question.
2. Create a NamedTemporaryFile using Python's tempfile library and make the contents of the file accessible that way. Need to make sure we carefully clean up the tempfile if we go this path.

The third possible solution would be to try to add the ability to cache files as a specific user. I am not a fan of this method so we're going to try to avoid it.

Thanks for the report!

**Comment by eykd** [comment]
I don't think pip [supports piped requirements](http://pip.readthedocs.org/en/latest/user_guide.html#requirements-files). A tempfile looks like the way to go.

**Comment by basepi** [comment]
Thanks for the link.

**Comment by cachedout** [comment]
It might be worth considering filing piped requirements as a feature request with the pip folks. I'm sure there are others who would find this useful.

**Comment by basepi** [comment]
@eykd Can you show me the output of `salt '*' test.versions_report` for the minion in question? I just want to double check that the version is correct, as I'm already seeing some tempfile code in pip.install for 2014.7.0.

**Comment by eykd** [comment]
@basepi Here you go:

```
               Salt: 2014.7.0
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.0.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed
```

**Comment by basepi** [comment]
Interesting. I guess I'll have to do some testing and see why that code isn't being hit.

**Comment by basepi** [comment]
I have this working perfectly in 2015.5.0.

```
root@saltmaster:~# cat /srv/salt/piptest.sls
mysite-reqs:
  pip.installed:
    - requirements: salt://requirements.txt
    - user: basepi
    - bin_env: /opt/env/mysite
    - cwd: /opt/env/mysite
root@saltmaster:~# cat /srv/salt/requirements.txt
mock
boto>=2.32.1
moto>=0.3.6
SaltTesting==2015.2.16
```

```
basepi@saltmaster:/opt/env/mysite$ find /var/cache/salt/minion/files
/var/cache/salt/minion/files
find: `/var/cache/salt/minion/files': Permission denied
```

```
root@saltmaster:~# salt 'master*' state.sls piptest
master_minion:
----------
          ID: mysite-reqs
    Function: pip.installed
      Result: True
     Comment: Successfully processed requirements file salt://requirements.txt.
     Started: 18:02:55.100429
    Duration: 13466.355 ms
     Changes:
              ----------
              requirements:
                  True

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

I'm going to close this based on my test above. However, if you upgrade to 2015.5 and still have issues, please feel free to comment

**Comment by Tafkas** [comment]
I am getting the same error using 2015.8.8 (Beryllium)

**Comment by dumol** [comment]
This seems to be still an issue in current stable packages… Master and minion are the same host:
```
    Salt Version:
               Salt: 2016.11.4

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
          docker-py: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.1
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-117-generic
             system: Linux
            version: Ubuntu 14.04 trusty
```
Problematic state:
```
pypi-server-package:
  pip.installed:
    - requirements: salt://services/pypi/requirements-server.txt
    - user: pypi
    - cwd: /srv/pypi
    - bin_env: /srv/pypi
    - require:
      - virtualenv: /srv/pypi
```
Error received:
```
Unable to process requirements file "salt://services/pypi/requirements-server.txt". Error:  Could not open requirements file: [Errno 13] Permission denied: '/var/cache/salt/minion/files/base/services/pypi/requirements-server.txt'
```
