### ISSUE TITLE
dockerio links option

### ISSUE THREAD

**Issue by choopooly** [saltstack/salt#19763]
I'm trying to link 2 containers with the following state, using dockerio state module.

```
collector:
  docker:
    - running
    - container: collector
    - links:
      - grafana: grafana
```

This error occurs when the "links" option is there (works fine when commented).
```
[DEBUG   ] "GET /run/docker.sock/v1.16/containers/collector/json HTTP/1.1" 200 None
[DEBUG   ] Docker-io running:{'status': False, 'comment': 'An exception occurred while starting your container collector', 'id': 'collector', 'out': 'Traceback (most recent call last):\n  File "/usr/lib/pymodules/python2.7/salt/modules/dockerio.py", line 915, in start\n    network_mode=network_mode)\n  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 940, in start\n    extra_hosts=extra_hosts\n  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 362, in create_host_config\n    \'{0}:{1}\'.format(k, v) for k, v in sorted(links)\nValueError: need more than 1 value to unpack\n'}
[DEBUG   ] Docker-io running:False
```

Here is my versions report, 
```
           Salt: 2014.1.10
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.11
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```
            
I know it's not the latest version and that dockerio module is still in beta but if you guys have some thoughts that would be great.

**Comment by jfindlay** [comment]
@choopooly, is it possible for you to upgrade to 2014.7.0 and try again?  Thanks.

**Comment by choopooly** [comment]
@jfindlay I confirm the same behavior with 2014.7.0.

```
[DEBUG   ] Docker-io running:{'status': False, 'comment': 'An exception occurred while starting your container collector', 'id': 'collector', 'out': 'Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 907, in start\n    cap_drop=cap_drop)\n  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 940, in start\n    extra_hosts=extra_hosts\n  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 362, in create_host_config\n    \'{0}:{1}\'.format(k, v) for k, v in sorted(links)\nValueError: need more than 1 value to unpack\n'}```

**Comment by musstard** [comment]
I am seeing this behaviour also. I am running 2014.7.0rc6 - I couldn't find clear documentation showing how to link containers, so I wonder if it is a YAML parsing / config format issue?

**Comment by alari** [comment]
is there any known workaround?

**Comment by choopooly** [comment]
@alari you can still use the cmd.run instead

**Comment by munhitsu** [comment]
@choopooly I've been hit with the same issue. Truth is it works.

Linking works just fine. Trouble is in lack of any docs. Stricly speaking you can find one in dockerio.py state file. And they are quite correct.
```
    links
        Link several container together

        .. code-block:: yaml

            - links:
                name_other_container: alias_for_other_container
```

Compared to your example `links` argument needs to be a dictionary. Not a list of dictionaries.
```yaml
opg-core-frontend:
  docker.running:
    - container: opg-core-frontend
    - links:
        opg-core-membrane: membrane.local
        monitoring: monitoring
    - require:
      - docker: opg-core-frontend-container
```
Take a note of extra indention after `links:`. This was my second mistake.
```yaml
    - links:
      opg-core-membrane: membrane.local
      monitoring: monitoring
```
It's a common yaml formatting pitfall. My example is parsed to a list entry with a dictionary in it. Exactly:
```python
[{
    'links': None,
    'monitoring': 'monitoring',
    'opg-core-membrane': 'membrane.local'
}]
```
While yaml:
```yaml
    - links:
        opg-core-membrane: membrane.local
        monitoring: monitoring
```
Parses to:
```python
[{
    'links': {
        'monitoring': 'monitoring',
        'opg-core-membrane': 'membrane.local'
    }
}]
```
And that's what we want.
