### ISSUE TITLE
archive.extracted tar_options can't handle long options properly

### ISSUE THREAD

**Issue by cjbarnes18** [saltstack/salt#19799]
I managed to get it to work bit it's quite obscure.

```yaml
node:
  archive.extracted:
    - name: /usr/local/
    - source: http://nodejs.org/dist/v0.10.35/node-v0.10.35-linux-x64.tar.gz
    - source_hash: sha1=3a202a749492e48542d2c28220e43ef6dae084bc
    - archive_format: tar
    - tar_options: z --strip-components=1 -
    - if_missing: /usr/local/bin/node
```
long options should be possible without this obscurity.
