### ISSUE TITLE
file.managed state introduces variable {{ user }} into context

### ISSUE THREAD

**Issue by pykler** [saltstack/salt#19818]
When using

``` yaml
...:
    file.managed:
        - source: salt://...
        - template: jinja
```

A simple test for `user is defined` in the source file returns `true`.

I added a unit test in `tests/unit/templates/jinja_test.py` to recreate the issue, but at the `jinja_test.py` level, user is truly undefined. I tried creating a states.file test or a modules.file test but was unable to properly setup the SaltFile Cache etc.

I created a test repo that demonstrates the issue https://github.com/pykler/salt-jinja-test

Also here is the unit test that shows that the basic jinja rendering works fine https://github.com/LeadSift/salt/commit/5e32a38100229315f0e1eabfd5fefd441413bb1f
