### ISSUE TITLE
file.recurse on masterless windows minions fails due to path separator issues

### ISSUE THREAD

**Issue by highlyunavailable** [saltstack/salt#19815]
The file.recurse state fails on a masterless windows minion due to how it treats path separators. File.managed works fine with `/` style source paths, but file.recurse fails to find the source unless it's written in the form `salt://x\y\z`.

Error:
```
local:
----------
          ID: Ensure Lua Decoder directory is in the correct state
    Function: file.recurse
        Name: c:\opt\heka-0_8_2-windows-amd64\share\lua_decoders
      Result: False
     Comment: Recurse failed: none of the specified sources were found
     Started: 10:55:39.497000
    Duration: 2.0 ms
     Changes:
```

State file:

```
Ensure Lua Decoder directory is in the correct state:
  file.recurse:
    - name: c:\opt\heka-0_8_2-windows-amd64\share\lua_decoders
    - source: salt://base/heka/lua_decoders
```

Versions report:
```
           Salt: 2014.7.1
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

As stated previously, if I change the state file to use the source in the form `salt://base\heka\lua_decoders` it works correctly, but this form would break on other platforms and/or using it with a master, plus it looks super weird in the "url" style format.
