### ISSUE TITLE
Ability to easily call target interface IP on a pillar

### ISSUE THREAD

**Issue by TaiSHiNet** [saltstack/salt#19828]
This would allow pillars to be more generic.

I haven't found a way to do so, specifically in a redis formula on which I have to specify a bind interface. If I could specify ipaddr['eth1'] (example) it would facilitate things a lot

**Comment by basepi** [comment]
Can you clarify what you're trying to do? Maybe with some example pillar code or something? I'm not sure what you mean by "call target interface IP on a pillar".

**Comment by TaiSHiNet** [comment]
@basepi I'm trying to do something like this:

```
redis:
  home: /var/lib/redis
  user: redis
  port: 6379
  bind: {{ salt['network.interfaces']()['eth1']['inet'][0]['address'] }}
```

That portion is something I dug out of googling around, I'm trying to set up redis servers without needing to make a different pillar for each server. And that the 'bind' parameter is set to eth1's IP
