### ISSUE TITLE
Add support for Windows updates to the winrepo package manager

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#19839]
Windows distinguishes between installed software and installed updates. Currently, `pkg.list_pkgs` seem only to get the list of installed software. And just to keep it interesting, some software actually installs as an update on some versions of Windows and as a regular software package on other versions...

For example, .NET 4.5.2 installs as an update on Windows 8.1 and Windows 2012 R2, but as a software package on Windows 2008 R2. So right now, `pkg.installed` will work for .NET 4.5.2 on ws2008r2, but not win8.1 or ws2012r2. I've written a formula to work around this, but it would be nice if the capability was built into salt.
- https://github.com/lorengordon/dotnet4-formula

I'm not sure how to get the list of installed updates from python, but here are a few ways of getting the list of installed updates using wmic and powershell. I'm not sure what would be best...
- `wmic qfe list`
- `powershell "Get-WmiObject -Class Win32_QuickFixEngineering"`
- `powershell Get-Hotfix`

I might lean towards the first or second options, presuming there is a way to wrap them in python, as the last requires Powershell 4 and that will limit out-of-the-box support for some versions of MS Windows. The second option is nice as it returns objects that can be manipulated or filtered easily, where the first just returns a bunch of text that has to be parsed.

Syntactically, I was thinking that it could be as simple as adding a parameter `hotfix` to the winrepo package defintion. `hotfix` would control the function logic and determine whether the package is _only_ a Windows update, whether it might be an update or a software package, or whether it's only a software package (current functionality). The logic branching might be something like this:
- `if 'hotfix' == True`; then the package is only an update. Use `version` as the hotfix ID.
- `elif 'hotfix'`; then the package may be either an update or a software package. Use `hotfix` as the hotfix ID.
- `else`; package is not an update. Use existing functionality.

Example 1 (package is only an update):

```
.NET:
  KB2934520:
    installer: 'http://download.microsoft.com/download/B/4/1/B4119C11-0423-477B-80EE-7A474314B347/NDP452-KB2901954-Web.exe'
    full_name: 'Microsoft .NET Framework 4.5.2'
    reboot: False
    install_flags: '/q /norestart'
    msiexec: False
    uninstaller: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\SetupCache\v4.5.51209\Setup.exe'
    uninstall_flags: '/uninstall /x86 /x64 /q /norestart'
    hotfix: True
```

Example 2 (package may be either an update or a normal software package):

```
.NET:
  4.5.51209:
    installer: 'http://download.microsoft.com/download/B/4/1/B4119C11-0423-477B-80EE-7A474314B347/NDP452-KB2901954-Web.exe'
    full_name: 'Microsoft .NET Framework 4.5.2'
    reboot: False
    install_flags: '/q /norestart'
    msiexec: False
    uninstaller: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\SetupCache\v4.5.51209\Setup.exe'
    uninstall_flags: '/uninstall /x86 /x64 /q /norestart'
    hotfix: 'KB2934520'
```

Example 3 (package is only a normal software package):

```
.NET:
  4.5.51209:
    installer: 'http://download.microsoft.com/download/B/4/1/B4119C11-0423-477B-80EE-7A474314B347/NDP452-KB2901954-Web.exe'
    full_name: 'Microsoft .NET Framework 4.5.2'
    reboot: False
    install_flags: '/q /norestart'
    msiexec: False
    uninstaller: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\SetupCache\v4.5.51209\Setup.exe'
    uninstall_flags: '/uninstall /x86 /x64 /q /norestart'
```
