### ISSUE TITLE
mount.mounted use wrong option -o instead of -O when -t is provided

### ISSUE THREAD

**Issue by tonthon** [saltstack/salt#19849]
salt minion in standalone mode version 2014.7.0 on a debian box
```
/mnt/nfsmount/:
    mount.mounted:
      - device: "nfs-server:/mnt/testnfsmount"
      - fstype: nfs
      - mkmnt: True
      - opts:
        - defaults,ro
```

generates:

```command
mount -o "defaults, ro,remount" -t nfs nfs-server:/mnt/testnfsmount /mnt/nfsmount/
```

since the -t option is provided, -O should be used:

```command
mount -O "defaults, ro,remount" -t nfs nfs-server:/mnt/testnfsmount /mnt/nfsmount/
```
