### ISSUE TITLE
Error recieved "State 'artifactory.downloaded' found in SLS 'xxxx.pkgs' is unavailable"

### ISSUE THREAD

**Issue by ranavik** [saltstack/salt#19879]
I am trying to use Salt State artifactory.downloaded in my sls file and it is throwing error "State 'artifactory.downloaded' found in SLS 'xxxx.pkgs' is unavailable"
The output of salt <minion id> grains.items |grep os is as follows:

```
$> salt minion-id.com grains.items | grep os
    biosreleasedate:
    biosversion:
    host:
    localhost:
    os:
    os_family:
    osarch:
    oscodename:
    osfinger:
    osfullname:
    osmajorrelease:
    osrelease:
    osrelease_info:
```

**Comment by ranavik** [comment]
Output of the command     $> salt minion-id.com grains.items | grep -A1 os

biosreleasedate:
        04/14/2014
    biosversion:
        6.00
    host:
        minion-3
    localhost:
        minion-3
    os:
        RedHat
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        Santiago
    osfinger:
        Red Hat Enterprise Linux Server-6
    osfullname:
        Red Hat Enterprise Linux Server
    osmajorrelease:
        - 6
    osrelease:
        6.2

**Comment by rallytime** [comment]
Thanks for the question @ranavik. Can you please post the output of `salt --versions-report` as well as the state file(s) you are trying to run?

**Comment by ranavik** [comment]
Hi @rallytime!
Thanks for your response and lookingi into this issue!
Following are the various versions installed on my machine:

Salt: 2014.7.0
Python: 2.6.6 (r266:84292, Sep 12 2011, 14:03:14)
Jinja2: 2.2.1
M2Crypto: 0.20.2
msgpack-python: 0.1.13
msgpack-pure: Not Installed
pycrypto: 2.0.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 2.2.0.1
RAET: Not Installed
ZMQ: 3.2.4
Mako: Not Installed

**Comment by rallytime** [comment]
Thanks! Can you also post the state you are trying to run?

**Comment by ayackel** [comment]
I have the same issue.  This is how the state looks:
```
cas-amq-lib-cp30:
  artifactory.downloaded:
    - artifact:
        artifactory_url: http://10.56.27.19/artifactory
        repository: 'repo1-cache'
        artifact_id: 'c3p0'
        group_id: 'c3p0'
        packaging: 'jar'
        classifier: 'sources'
        version: '0.9.1.2'
    - target_dir: {{ activemq.root }}/current/lib/optional
```
and here is the versions report:
```
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```
