### ISSUE TITLE
salt-ssh test.versions_report isn't the same as what is installed

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#19908]
I installed `2014.7.1` on a minion via salt-ssh. It installed the correct 2014.7.1 packages, but when I do a `salt-ssh -i <minion> test.versions_report` it gives `2014.7.0` as the version of salt. However, if I connect my minion to the salt master via normal salt (not ssh), and do `salt <minion> test.versions_report`, I get the correct version back, which is 2014.7.1. My master is running on the v2014.7.1 tag.

Perhaps _version.py is not being deployed with salt-ssh.

salt-master:
```
salt-ssh --versions
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
salt-ssh versions report on minion:
```
salt-ssh -W nt-cent7 test.versions_report
nt-cent7:
               Salt: 2014.7.0
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.4
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.4
               Mako: Not Installed
```
Versions report via non-salt ssh connection:
```
salt nt-cent7 test.versions_report
nt-cent7:
               Salt: 2014.7.1
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.4
```
