### ISSUE TITLE
Setting a grain via grains.list_present will sometimes disconnect minion

### ISSUE THREAD

**Issue by mshade** [saltstack/salt#19911]
Running 2014.7.0 on master and minions. If I add a new roles: grain via a state, some minions will return, but will not respond to subsequent messages from the salt master. The salt-minion service must be restarted before communication resumes.

Here's the state I'm using to set grain:

```
# Set a role for nginx
set-nginx-role:
  grains.list_present:
    - name: roles
    - value: nginx
```

I will attempt to trigger this on a minion while running it in the foreground with -l debug to see if I can get any more info on what happens - but nothing in the normal logs hints at anything.
