### ISSUE TITLE
Setting user password to ! does not work.

### ISSUE THREAD

**Issue by ralphvanetten** [saltstack/salt#19946]
I am trying to reset the password of an existing user to '!' to disable logging in with a password but it does not see the change:

```
test:
  user:
    - expire: 2000
    - present
    - password: !
    - enforce_password: True
```
The user already exists on the machine with a password :
```
ralph@log02:~$ sudo cat /etc/shadow
....
test:$6$SALTsalt$xxxxxxxxxxxxxxxxxxxxxxx/Vr/:16457:0:99999:7::1000:
```

Then I run 'salt log02 state.highstate' which says:
```
         ID: test
    Function: user.present
      Result: True
     Comment: Updated user test
     Started: 01:26:14.750056
    Duration: 31.375 ms
     Changes:   
              ----------
              expire:
                  2000
```

As you can see there is no reference to a change in the password but it did changed the expire.
I would have expected it changed the password bu it didn't, it only changed the expire field:
```
ralph@log02:~$ sudo cat /etc/shadow
....
test:$6$SALTsalt$xxxxxxxxxxxxxxxxxxxxxxx/Vr/:16457:0:99999:7::2000:
```

If I try to set the password to something else it works:
```
test:
  user:
    - expire: 2000
    - present
    - password: "*"
    - enforce_password: True
```
an then run 'salt log02 state.highstate':

```
          ID: test
    Function: user.present
      Result: True
     Comment: Updated user test
     Started: 01:27:55.695419
    Duration: 4.955 ms
     Changes:   
              ----------
              passwd:
                  "*"
```

it does update the password:

```
ralph@log02:~$ sudo cat /etc/shadow
....
test:*:16457:0:99999:7::2000:
```

```
$ salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
