### ISSUE TITLE
Chocolatey install with version=latest

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#19998]
If version=latest then it should check to see if is installed, if not installed it should call chocolatey install <package>, otherwise run chocolatey update <package>

Thanks

**Comment by jfindlay** [comment]
@damon-atkins, thanks for reporting this.  There should probably be a third case to check if the installed version is already the latest.

**Comment by ssgward** [comment]
Is this still an issue with the latest version of salt you are using? If so, please update bug with current info. If not a but please close.

**Comment by dragon788** [comment]
Currently it appears that `chocolatey.installed` only checks if a package's name is present in the list of installed packages and doesn't check the version even if a version is passed (it returns before running the chocolatey.install with a version).

**Comment by tobias-kuendig** [comment]
This is currently still the case. Are there any plans on changing this behaviour? I'm using a standalone minion to provision a server. I have a fixed version defined:

```yml
install_php:
  chocolatey.installed:
    - name: php
    - version: '7.1.2'
```

Updating this package to a newer version should be as easy as changing the `version` to `7.1.5` and run `state.apply` again. Unfortunately, once installed, this state is ignored since the package is already installed. It would be great if an update was triggered since the versions don't match.

```
C:\WINDOWS\system32>salt --versions-report
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.14393  Multiprocessor Free
```
