### ISSUE TITLE
Restrict which minions mine data can be retrieved from

### ISSUE THREAD

**Issue by dnd** [saltstack/salt#20009]
It is currently possible using `mine_get` in the master config to limit the mine functions a minion can access. It would be good to also be able to restrict which minions a minion can access data from. It would probably require redoing the `mine_get` syntax in a non-backwards compatible manner. Maybe something along the lines of:

``` yaml
mine_get:
  dev-*:  # minions starting with dev-
    dev-*:  # can get any data from other minions starting with dev-
      - .*
    .*:  # and can only get network data from other minions
      - network.*
```

or maybe allow more complex matching:

``` yaml
mine_get:
  'environment:staging':
    match: grain
    ...

```
