### ISSUE TITLE
state.sls_id does not consider watch(_in)?

### ISSUE THREAD

**Issue by jkmw** [saltstack/salt#20049]
Hi there!

If a concrete id of a state is called by "state.sls_id" it does not consider the corresponding watch or watch_in entries of the required states.

Example:

state: test.sls:
```
/tmp/testfile:
  file.managed:
    - watch_in:
      - service: apache2service

apache2service:
  service.running:
    - name: apache2
    - enable: True
    - reload: True
```

`salt-call -l all state.sls_id "/tmp/testfile" test`

results in:
```
[...]
[TRACE   ] data = {'local': {'file_|-/tmp/testfile_|-/tmp/testfile_|-managed': {'comment': 'Empty file', 'name': '/tmp/testfile', 'start_time': '09:26:08.801435', 'result': True, 'duration': u'1.484 ms', '__run_num__': 0, 'changes': {'new': 'file /tmp/testfile created'}}}}
local:
----------
          ID: /tmp/testfile
    Function: file.managed
      Result: True
     Comment: Empty file
     Started: 09:26:08.801435
    Duration: 1.484 ms
     Changes:   
              ----------
              new:
                  file /tmp/testfile created

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

You see the apache2service-state won't be restarted.
It is my fault or it is a bug?

**Comment by basepi** [comment]
So here's the problem. When you do a `watch_in`, you're injecting a `watch` into another state. So your state will just end up resolving to this:

```
/tmp/testfile:
  file.managed: []

apache2service:
  service.running:
    - name: apache2
    - enable: True
    - reload: True
    - watch:
      - file: /tmp/testfile
```

Because the `watch` is not actually a part of the `file.managed` state, `state.sls_id` will not resolve it or act on it in any way.

You could probably get the behavior your want by running the `apache2service` state with `state.sls_id`, because then the watch would be applicable and it should run `/tmp/testfile` first.

Or, even better, don't rely on single IDs, and use `state.sls` to run an entire file instead. (That's my recommended solution)
