### ISSUE TITLE
rbenv ruby install failure and the lack of useful output

### ISSUE THREAD

**Issue by yee379** [saltstack/salt#20040]
so i tried installing 2.2.0 ruby via rbenv using the following sls:

```
rbenv-deps:
  pkg.installed:
    - pkgs:
      - bash
      - git
      - openssl
      - curl

install_rbenv:
  rbenv.install_rbenv:
    - require:
      - pkg: rbenv-deps

install_ruby-2.2.0:
  rbenv.installed:
    - name: 2.2.0
    - default: True
    - require:
      - rbenv: install_rbenv
```

so after a while, the salt master spits out:

```
      ID: install_ruby-2.2.0
Function: rbenv.installed
    Name: 2.2.0
  Result: False
 Comment: Could not install ruby.
 Started: 14:56:19.064192
Duration: 231941.144 ms
 Changes:
```

hmm.. not so useful. running the minion in the foreground shows:

```
[ERROR   ] stderr: Downloading ruby-2.2.0.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/7671e394abfb5d262fbcd3b27a71bf78737c7e9347fa21c39e58b0bb9c4840fc
Installing ruby-2.2.0...

BUILD FAILED (RedHatEnterpriseServer 6.6 using ruby-build 20150116-6-g7f1d8df)

Inspect or clean up the working tree at /tmp/ruby-build.20150124145619.17664
Results logged to /tmp/ruby-build.20150124145619.17664.log

Last 10 log lines:
make[3]: Leaving directory `/tmp/ruby-build.20150124145619.17664/ruby-2.2.0/ext/fiddle/libffi-3.2.1'
linking shared-object fiddle.so
/usr/bin/ld: ./libffi-3.2.1/.libs/libffi.a(raw_api.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
./libffi-3.2.1/.libs/libffi.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[2]: *** [../../.ext/x86_64-linux/fiddle.so] Error 1
make[2]: Leaving directory `/tmp/ruby-build.20150124145619.17664/ruby-2.2.0/ext/fiddle'
make[1]: *** [ext/fiddle/all] Error 2
make[1]: Leaving directory `/tmp/ruby-build.20150124145619.17664/ruby-2.2.0'
make: *** [build-ext] Error 2
```

would it be possible to get this output in the salt state output please?
