### ISSUE TITLE
Adding a pkg repo that is commented out will silently succeed

### ISSUE THREAD

**Issue by jessecollier** [saltstack/salt#20096]
Take this state for example. This should enable multiverse. It will succeed when ran, but actually does not do anything.

```yml
enable multiverse:
  pkgrepo.managed:
    - name: deb http://archive.ubuntu.com/ubuntu trusty multiverse
```

However, if I do an absent prior to the add, it'll actually work. It does not care if it is commented out or not:

```yml
FIX enable multiverse:
  pkgrepo.absent:
    - name: deb http://archive.ubuntu.com/ubuntu trusty multiverse

enable multiverse:
  pkgrepo.managed:
    - name: deb http://archive.ubuntu.com/ubuntu trusty multiverse
    - require:
        - pkgrepo: FIX enable multiverse
```

**Comment by rallytime** [comment]
@jessecollier can you post the output of `salt --versions-output`? This is on a Debian/Ubuntu machine correct? We had a regression with pkgrepo states in 2014.7.0 that has since been fixed, but I am not sure if we addressed the second behavior you are seeing.

**Comment by jessecollier** [comment]
```
vagrant@dev:~$ salt-call  --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by jessecollier** [comment]
Oh yea, it's Ubuntu

**Comment by jessecollier** [comment]
Just to add for clarity, the multiverse line exists in the `/etc/apt/sources.list` file but is commented out. But the absent/present disregard this comment, and still removes/adds it based on finding the string alone. 

Seems like a regex issue with not having `^` for matching beginning of line.

**Comment by rallytime** [comment]
So the 2014.7.1 release has been announced, but I we don't have Debian/Ubuntu packages available yet. I'd be interested to see if this is still a problem when you're able to upgrade. I think the first case will be solved, but we might need to look at this again based on your last comment. 

When 2014.7.1 becomes available, can you give this another try and let us know how it goes?

**Comment by jessecollier** [comment]
Sure. I always update salt to latest :)

-Jesse Collier

**Comment by jessecollier** [comment]
Tested with 2014.7.1 and no luck. Also doesn't mention it in release notes.

However, I have made a short little sls that gives the desired result (ie only change state if not correct state)

```yml
{% set mv = [
  { 'name' : 'multiverse' , 'repo' : 'deb http://archive.ubuntu.com/ubuntu trusty multiverse' },
  { 'name' : 'multiverse-updates' , 'repo' : 'deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse' },
  { 'name' : 'multiverse-security' , 'repo' : 'deb http://security.ubuntu.com/ubuntu trusty-security multiverse' }]
%}

{% for i in mv %}
FIX enable {{ i.name }}:
  pkgrepo.absent:
    - name: {{ i.repo }}
    - unless: rgrep -q "^{{ i.repo }}" /etc/apt/sources.list

{{ i.name }}:
  pkgrepo.managed:
    - name: {{ i.repo }}
    - require:
        - pkgrepo: FIX enable {{ i.name }}
{% endfor %}
```

**Comment by rallytime** [comment]
Thanks for giving that another try, and for posting a handy work-around! We'll have to take a closer look.

**Comment by babilen** [comment]
Any progress on this one? `pkgrepo.{absent,managed}` is quite broken in this regard and having to remove the sources.list prior to highstate runs to ensure that managed repositories are actually added is, well, slightly suboptimal.

To provide a little more information. This can be easily reproduced with the following state:

```
apt_python_module:
  pkg.installed:
    - name: 'python-apt'

repo_wheezy:
  pkgrepo.managed:
    - humanname: Wheezy Repository
    - name: deb http://http.debian.net/debian wheezy main
    - dist: wheezy
    - comps: main,contrib,non-free
    - require:
      - pkg: python-apt
```

which results in the following:

```
# cat /etc/apt/sources.list
# deb http://http.debian.net/debian wheezy main contrib non-free

# salt '*' state.highstate
jid: 20150330114811757620
salttest-debian-wheezy:
----------
          ID: apt_python_module
    Function: pkg.installed
        Name: python-apt
      Result: True
     Comment: Package python-apt is already installed.
     Started: 11:48:12.597041
    Duration: 96.262 ms
     Changes:   
----------
          ID: repo_wheezy
    Function: pkgrepo.managed
        Name: deb http://http.debian.net/debian wheezy main
      Result: True
     Comment: Configured package repo 'deb http://http.debian.net/debian wheezy main'
     Started: 11:48:12.693561
    Duration: 174.561 ms
     Changes:   

Summary
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2

# cat /etc/apt/sources.list
# deb http://http.debian.net/debian wheezy main contrib non-free
```
and even adding `enabled: True` does not change this behaviour. This essentially renders `pkgrepo` states rather useless as you can never be sure that a repository will be added or not.

Even iff `pkgrepo.managed` would work as expected once you set `enabled: True` (which it does not) I'd argue that that should be the default behaviour unless you explicitly set `disabled: True`.
