### ISSUE TITLE
Lustre mount support

### ISSUE THREAD

**Issue by francis2211** [saltstack/salt#20150]
```
/lstr/work:
  mount.mounted:
    - device: nicmds@tcp1:nicadm@tcp1:/lstr
    - fstype: lustre
    - mkmnt: True
    - opts:
      - _netdev
      - rw
      - auto
      - intr
      - timeo=600
      - flock
```

I am getting this error
```
----------
          ID: /lstr/work
    Function: mount.mounted
      Result: False
     Comment: mount: unknown filesystem type 'lustre'
     Started:
    Duration:
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
```

My question is saltstack doesn't support lustre file system? if not are you guys have plans to support lustre?
