### ISSUE TITLE
ramfs mount keeps remounting when it shouldn't

### ISSUE THREAD

**Issue by darkvertex** [saltstack/salt#20164]
I have another mount bug for you. It's a similar situation to issue #19003 but not specific to bind mounts.

So, my salty config has this:
```
/mnt/ramfs:
  mount.mounted:
    - device: ramfs
    - fstype: ramfs
    - mkmnt: True
    - opts: size=1g
    - persist: False
```

It works, it mounts alright. Thing is... it remounts all the time on subsequent runs. Why? Because "_options changed_", apparently:
```
          ID: /mnt/ramfs
    Function: mount.mounted
      Result: True
     Comment: Target was already mounted
     Started: 16:49:06.117171
    Duration: 271.925 ms
     Changes:   
              ----------
              umount:
                  Forced remount because options (size=1048576k) changed
```

I suspect it sees that "1g" != "1048576k".

For the uninformed, **"_ramfs_" mounts can grow to any size.** You mount them with an initial size, but you can write more to it and it will grow automatically as long as there's free RAM for it. By the way there is also a "_tmpfs_" type which is almost the same but does not grow dynamically like ramfs does.

Could someone fix this? It can be a bit dangerous having your ramdisk unmounted. (I guess you could just skip the size check altogether when it's a ramfs mount, maybe.)
