### ISSUE TITLE
pkgrepo - Failed to configure repo "...": 'int' object is not iterable

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#20190]
Hello,

I am adding a repo with salt 2014.1.13:

```
nodesource:
  pkgrepo.managed:
    - humanname: NodeJs Repository
    - name: deb https://deb.nodesource.com/node wheezy main
    - dist: wheezy
    - file: /etc/apt/sources.list.d/nodesource.list
    - keyid: 68576280
    - keyserver: keys.gnupg.net
```

and it is failing with this error:

```
          ID: nodesource
    Function: pkgrepo.managed
        Name: deb https://deb.nodesource.com/node wheezy main
      Result: False
     Comment: Failed to configure repo 'deb https://deb.nodesource.com/node wheezy main': 'int' object is not iterable
```

A few versions ago this used to work just fine but with version 2014.1.13 it stopped working.
