### ISSUE TITLE
Salt ui external_auth  for local user

### ISSUE THREAD

**Issue by subhashchand** [saltstack/salt#20206]
please suggest me how to set salt ui  external_auth  for local user 
my file 

```
external_auth:
  pam:
     testuser:
      - .*
      - '@runner'
      - '@wheel'
```

when i execute this command 

```
salt -a pam '*' test.ping
```

getting this error:

```
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage)
```

suggest me  plz

**Comment by whiteinge** [comment]
Your syntax looks correct. Did you restart the Salt master after changing the config file? Do you see the interactive prompt for 'username' and 'password' ? Do you see any logging messages on the CLI or in the master log file?

**Comment by whiteinge** [comment]
Oh, and what version of Salt are you running?

**Comment by andrejohansson** [comment]
I have this as well, on a clean ubuntu 14.04 lts image. I add the user `saltapiuser` with the command `adduser saltapiuser`. I have the following section in my `/etc/salt/master` config file:

```
external_auth:
  pam:
    andre:
      - .*
      - '@wheel'
      - '@runner'
    saltapiuser:
      - .*
      - '@wheel'
      - '@runner'
```

Then I restart the salt-master using `service salt-master restart` and finally I login as `saltapiuser` with ssh and run the command `salt "*" test.ping` and I still get
```
saltapiuser@dvs-eu-sama:~$ salt '*' test.ping
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```
It feels that there is some step missing regarding the `saltapiuser`. Should I add the user to some specific group or should I add some permissions to specific files?

I made both the `/var/log/salt/master` and `/var/log/salt/minion` log files publicly accessible (`chmod 777`) but that still didn't help.

The salt-master service runns as `root` (default, no changes).
