### ISSUE TITLE
svn module username and password options broken

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#20224]
From https://groups.google.com/forum/#!topic/salt-users/cOpJ7qjD7Gs:

to this point if i had a problem with the svn.latest call, there was always a more or less "clear" error statement, but now i'm stuck with the following:
```
----------
          ID: https://**.**.**.**/svn/System-Shellscripts/trunk/andros/scripts
    Function: svn.latest
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1529, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/svn.py", line 121, in latest
                  out = __salt__[svn_cmd](cwd, basename, user, username, password, *opts)
                File "/usr/lib/python2.7/dist-packages/salt/modules/svn.py", line 248, in update
                  return _run_svn('update', cwd, user, username, password, opts)
                File "/usr/lib/python2.7/dist-packages/salt/modules/svn.py", line 62, in _run_svn
                  opts.extend(['--username', username])
              AttributeError: 'tuple' object has no attribute 'extend'
     Started: 18:25:58.133399
    Duration: 150.401 ms
     Changes:
----------
```

if i call the following on the minion it gets executed without errors:
```
svn up -r HEAD https://**.**.**.**/svn/System-Shellscripts/trunk/andros/scripts /daten/SVN_PROJECTS/scripts
```

the definition looks like this:
```
https://**.**.**.**/svn/System-Shellscripts/trunk/{{ grains['nodename'] }}/scripts:
  svn.latest:
    - trust: True
    - target: /daten/SVN_PROJECTS/scripts
    - user: root
    - username: svn_ro
    - password: *cleartextpwd*
    - require:
      - file: /root/.subversion/auth/svn.ssl.server/e35bcd20f0e2b12bd5b4a701e2f3bc0e
```

could someone please point me in the right direction?

salt versions:
```
salt-master                        2014.7.1+ds-1~bpo70+1
salt-minion                        2014.7.1+ds-1~bpo70+1
```
