### ISSUE TITLE
Using saltstack runners in .sls state modules

### ISSUE THREAD

**Issue by I3olle** [saltstack/salt#20258]
What I want to do: 
I want to use the cached pillars and grains to generate a lot of files on the master. In order to that, I would like to 
either:
execute a python script which returns all the cached pillars/grains of my minions and then use the returned output in my .sls to generate my folderstructure.
or:
call the salt-run cache.grains/pillar functions in my sls directly.

This is an example python script which would produce such data:

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
import salt.config
import salt.runner
opts = salt.config.master_config('/etc/salt/master')
runner = salt.runner.RunnerClient(opts)
grains = runner.cmd('cache.grains', [])
pillar = runner.cmd('cache.pillar', [])
```

I also would like to note, that it is not possible to use this sort of script in a .sls file because yaml only accepts ascii and the output of this function contains non-ascii output

I can't seem to find any examples on how to use runners in .sls files however. All I can find are python scripts. But then again nothing which implements the returned data for generating files.

I have written a simple cached.sls to test this.

```
{% for ip_v4 in salt['publish.runner']('cache.grains','fqdn_ipv4') -%}
{%- set kernel = salt['publish.runner']('cache.grains','kernel') %}

config_{{ kernel }}:
  file.managed:
    - name: 'some_directory{{ kernel }}.conf'
    - user: root
    - group: root
    - mode: '0644'
    - source: salt://my_formula/files/cached.cfg
    - template: jinja
    - defaults:
        ipv4: {{ ip_v4 }}
        kernel: {{ kernel }}

{%- endfor %}
```

So far all I get is this output:

```
[master]# salt-call state.sls my_formula.cached
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'my_formula/cached.sls'
[INFO    ] Publishing runner 'cache.grains' to tcp://ip_of_master:port
local:

Summary
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
```

Executing the runner via 

```
[master]# salt-run cache.grains
```

on the shell produces the correct outcome with all the grains of all the minions and the master. 

Using the publish command

```
[master]# salt '*'  publish.runner cache.pillar
```

however produces only this:

```
minion:
    ----------
master:
    ----------
```

Now either I find a way to use the returned data from a python script, or I find a way to call the runner from within a .sls My idea on how that should look is 

```
{%- for ip_v4 in salt['runners.cache.grains']('fqdn_ipv4', {}) %}
```

But that only returns:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:icinga2.cached' failed: Jinja variable 'dict' object has no attribute 'runners.cache.grains'
```

**Comment by basepi** [comment]
Runners execute on the master, while state files execute on the minion. So calling runners from state files doesn't really make sense.

If all you're trying to do is get the pillars/grains for your minion, why not just use the `pillar` and `grains` dictionaries provided in the jinja already? We make them readily available that way in the jinja, and they're available in custom state modules via the `__pillar__` and `__grains__` dictionaries.

**Comment by basepi** [comment]
I noticed that you mentioned non-ascii -- this seems like the perfect candidate for a custom state module or execution module, depending on how you want to use it.

**Comment by basepi** [comment]
One more thing. If you're just trying to make a grain available from all minions to the minion in question, the Mine would be a really good candidate for that: http://docs.saltstack.com/en/latest/topics/mine/

**Comment by I3olle** [comment]
First of all thank you for taking your time to reply to my question so fast basepi. I really appreciate that.

Runners vs. States
Well I would actually like to execute the runner on the master. And I don't want to just get the pillars and grains of my minion. I want to execute whatever necessary on my master, collect all the pillars and grains from all minions and then generate files by iterating through the pillars and grains. I have written a formula which does this but generates the files on the respective minions. I want all the files to be written on my master.
And how come I am perfectly able to use sls files on my master as well? I am very comfortable with creating files and folder structures using yaml and jinja and so far all my files are created just how I want them to be. Only problem is, that I cannot iterate through the pillars and grains of my minions on my master.

The Mine
I have been redirected to the mine several time already and I know about it but I don't like the idea that by storing data in the mine it would be accessible by all minions. Even though I know that not the minions themselves but only the states on them would have acces and even though I can select what to store in the mine. Not being able to restrict access to the mine actually bothers me.

Dunder Dictionaries
I have read about these and tried using them but again it seems that I can only execute them from within a python file? I probably must have misunderstood this. I am sorry about that.
```
{%- for ip_v4 in __salt__['grains.get']('fqdn_ipv4', {}) %}
```
brings me nowhere. So that would bring me back to the question how to use output from python scripts in state files. (even though I am not supposed to run them on the master)

Maybe my goal becomes clearer when I post my current .sls

```
{% for ip_v4 in salt['grains.get']('fqdn_ip4', '') -%}
{%- set hostname = salt['pillar.get']('master:id', {}) %}
{%- set kernel = salt['grains.get']('kernel', {}) %}


config_{{ hostname }}:
  file.managed:
    - name: '/srv/formulas/icinga2/files/tmp/{{ hostname }}.conf'
    - user: root
    - group: root
    - mode: '0644'
    - source: salt://icinga2/files/hosts.cfg
    - template: jinja
    - defaults:
        hostname: "{{ hostname }}"
        ipv4: {{ ip_v4 }}
        kernel: {{ kernel }}

directory_{{ hostname }}:
  file.directory:
    - name: '/srv/formulas/icinga2/files/tmp/{{ hostname }}'
    - watch_in:
      - service: icinga2
    - user: root
    - group: root
    - dir_mode: 755
    - file_mode: 644
    - makedirs: True



{% for checkname, args in salt['pillar.get']('icinga2:checks', {}).iteritems() %}

icinga2_{{ checkname }}:
  file.managed:
    - name: '/srv/formulas/icinga2/files/tmp/{{ hostname }}/{{ checkname }}.conf'
    - watch_in:
      - service: icinga2
    - require:
      - file: '/srv/formulas/icinga2/files/tmp/{{ hostname }}'
    - user: root
    - group: root
    - mode: '0644'
    - source: salt://icinga2/files/checks.cfg
    - template: jinja
    - defaults:
        checkname: {{ checkname }}
        hostname: {{ hostname }}
        check_command: nrpe
        hook: {}
    - context:
{% if args['check_command'] is defined %}
{%- set check_command = args.get('check_command', []) %}
        check_command: {{ check_command }}
{% endif %}
{% if args['hook'] is defined %}
{%- set hook = args.get('hook', []) %}
        hook: {{ hook }}
{% endif %}

{%- endfor %}

{%- endfor %}


clean_tmp:
  local.cmd.run:
    - tgt: '*icinga*'
    - arg:
      - cp.get_dir salt://icinga2/files/tmp /etc/icinga2/conf.d/hosts
      - rm -rf salt://icinga2/files/tmp*
      - service icinga2 reload
```

As you can see, this is meant to automatically generate config files for all the checks of my minions. And it actually works and creates all the files just how I want them. But they get created on the minions and then can't be moved to my icinga monitoring server.
I am unhappy with the currently available icinga2-formula and this is part of my new formula which (once it works) won't just configure hosts and services only.

I would be super happy if you told me I just have to do a :%s/salt/__salt__/g and be done with it. But that doesn't seem to be the case so I just hope you don't look at my code so far and have to bang your head on the table because I have completely misunderstood salt and done a lot of unnecessary stuff. 

Thanks again for taking your time with me.

**Comment by basepi** [comment]
"dunder dictionaries" are only usable in custom state/execution modules. However, many of the same dictionaries are available in state sls files without the double underscores (you're using them this way in your example state file)

I think what you're probably looking for is a custom runner. You can start off in the runner by using an instance of [the LocalClient](http://docs.saltstack.com/en/latest/ref/clients/#localclient) to call out to the minions for their grains/pillar data.

Now that you have all of the data you need, it becomes trivial to inject it into a state call. It turns out that state runs all provide a `pillar` argument you can use to inject single-use pillar data for that run. So you use an instance of the LocalClient just like above, but you only target this job to the minion which is installed on the master. You pass in all the data you gathered as custom pillar data for the run, and then in the state files (which you'll have to create separately) you use that custom pillar data to create the files in the same way you did above.

Is that making any sense?

**Comment by I3olle** [comment]
That sounds interesting. I think it makes sense to me. Let me try rephrase that to make sure I actually have understood it.
I create a python script on the master which includes the following
```
import salt.client
local = salt.client.LocalClient()
local.cmd('*', 'grains.items', [])
local.cmd('*', 'pillar.items', [])
```

This will return all the pillars and grains from the various minions back to my master. Now in the same python script I would add another line(s) which would parse the output into another external pillar file. Let's call it icinga_pillar. 
Afterwards in my .sls I would have to just add a few lines such as
```
clean_tmp:
  local.cmd.run:
    - arg:
      - python salt://icinga2/script.py
```
and then instead of 
```
salt['grains.get']('fqdn_ip4', '')
```
i would use
```
icinga_pillar.get['fqdn_ip4', '']
```

Sounds like a great idea. I would really like that. So far the remaining questionmarks in my head revolve your term "single-use pillars". I am not sure how to create these within the python script and I am not aware of pillars that remove themselves after they have been called for once. You probably just mean a different set of pillars which I named icinga_pillar in this case. Right? But then I still don't know the bit of pythoncode to parse the output into such a new pillar.

Am I on the right track?
