### ISSUE TITLE
file.replace inserts extra CR+LF on Windows 

### ISSUE THREAD

**Issue by soodr** [saltstack/salt#20297]
The file.replace module ends up inserting an extra blank line in the file. This breaks multi-line content.

State definition: 

```
{% set TSSserviceId = "test300" %}

update_service_id:
      file.replace:
        - name: 'C:\Temp\test.txt'
        - pattern: '@SERVICEID@'
        - count: 1
        - repl: {{ TSSserviceId }}
        - backup: '.bak'
        - show_changes: True
```

Original content of c:\temp\test.txt:

```
echo Configuring the database connection

bootstrap --no-prompt --driver-class="${DB_DRIVER}" --database-url="${DB_URL}" \

  --username="${DB_USER}" --password="${DB_PASSWORD}" --tool-password="${CONFIG_TOOL_PASSWORD}" \

  --server-name="@SERVICEID@" --force

echo
```

Parsed content of c:\temp\test.txt:

```
echo Configuring the database connection


bootstrap --no-prompt --driver-class="${DB_DRIVER}" --database-url="${DB_URL}" \


  --username="${DB_USER}" --password="${DB_PASSWORD}" --tool-password="${CONFIG_TOOL_PASSWORD}" \


  --server-name="test300" --force

```

C:\salt>salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD6
4)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
