### ISSUE TITLE
State parser doesn't pick up bad low chunks

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#20309]
Given an sls formatted like this:

```
{% set haproxy_version = '1.5.11' -%}

/usr/sbin/haproxy:
  file.managed:
    - user: root
    - group: root
    - mode: 0755
    - source: salt://files/haproxy/haproxy-{{ haproxy_version }}/haproxy

haproxy_service:
  service.running:
    - name: haproxy
    - enable: True
    - reload: True
  watch:
    - file: /usr/sbin/haproxy
```

The `watch` doesn't work, as expected, but no error is thrown.

@thatch45 ping
