### ISSUE TITLE
RVM is not a function for gem state

### ISSUE THREAD

**Issue by joshdover** [saltstack/salt#20317]
We've been using the rvm and gem states for quite some time now. I went to spin up a new server with a set of states that have been working fine for us in the past. Now we get errors on any `gem.installed` call. When using debug level logging I see that "RVM is not a function" on all of the gem.installed states.

I can't see any differences in the .bashrc or .bash_profiles for the older servers that still work. Neither have any `source` calls to the `/usr/local/rvm/scripts/rvm` file. They do have different RVM versions (old: 1.25.31, new: 1.26.10). The rvm state doesn't allow you to configure the version, so I couldn't try using an older rvm issue to narrow down the source the problem.

I really am not sure what the issue is here, but I suspect some change in the install script for rvm could have to do with it.

For now I am using custom states to install my gems:
```yaml
install-bundler:
  cmd.run:
    - name: source /usr/local/rvm/scripts/rvm; gem install bundler
    - user: root
    - unless: source /usr/local/rvm/scripts/rvm; gem list god | grep bundler
```

Sorry this isn't of more help, but I can agree with #19105, this rvm module code is whack.
