### ISSUE TITLE
salt with test=True option not working as documented

### ISSUE THREAD

**Issue by john-clarke** [saltstack/salt#20399]
From the docs: http://docs.saltstack.com/en/latest/ref/states/testing.html

> "Salt has a test interface to report on exactly what will be changed"

When I run `salt mytarget state.highstate` with `test=True` it outputs several unchanged items with `Result: Differs`. From that output, it appears if the state will get updated. I'd expect these changes to be applied with `test=False` option. However, when I run the same command with `test=False` none of the expected changes are deemed necessary and I get `Succeeded: 0, Failed: 0`. In my case, the changes are files `file.managed` states.

**Comment by eliasp** [comment]
Fixed in #20024

**Comment by basepi** [comment]
Yep, usually this is caused by a state misbehaving, not the whole state system. So we'll definitely need to see your states and their results to further investigate this.

**Comment by john-clarke** [comment]
salt master is version 2014.7.1 (Helium)
Here are a few examples of the output:
```
Name: /home/ausername/.gitconfig - Function: file.managed - Result: Differs
Name: /etc/hosts - Function: file.managed - Result: Differs
Name: ufw allow 443 - Function: cmd.run - Result: Differs
```
Here is a sample state 
```
ufw:
  pkg.installed

ufw config for cisnet-fi:
  cmd.run:
    - names:
      - "ufw allow 80"
      - "ufw allow 443"
      - "ufw allow from 192.168.100.0/24 to any port 22"
      - "ufw allow from 192.168.100.0/24 to any port 8000"
      - "yes | sudo ufw enable"
    - require:
      - pkg: ufw
```
and another for the hosts file:

```
hosts: |
  # Managed by salt

  127.0.0.1 localhost
   [more hostnames]
```

I can provide further information here, but perhaps this is sufficient?
