### ISSUE TITLE
pkgrepo's 'key_url' parameter documentation is misleading

### ISSUE THREAD

**Issue by falzm** [saltstack/salt#20404]
Hi

I stumbled on a problem when trying to use the `key_url` parameter of the "pkgrepo.managed" state: the [documentation](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkgrepo.html#salt.states.pkgrepo.managed) describes this parameter as "URL to retrieve a GPG key from", although looking at the [actual code](https://github.com/saltstack/salt/blob/cefb78efe93e494087f1eb0ce92e8fc8b7b5ef16/salt/modules/aptpkg.py#L1556) behind the feature it calls the `apt-key add` command and passes the value of the setting – which misleads to think it can be a URL, but `apt-key` only accepts local file paths.

I suggest fixing the documentation to clarify this, as it took me more than a hour trying to find out why I still got invalid signature issues although I've specified the *URL* where the signing public key could be fetched from ;)

**Comment by jfindlay** [comment]
@falzm, I don't have much experience with repo keys on deb systems other than remembering that it was always a two step process, which I've though is kind of silly, but I suppose there might be a reason for it.

**Comment by jfindlay** [comment]
@falzm, if you would like to fix the documentation, you are very welcome to do so.  If you do, be sure to mention this issue in the pull request comment so that github will automatically close it.

**Comment by falzm** [comment]
Hi @jfindlay 

Actually after giving some thinking to this, I think the most appropriate thing to do would be to rename this setting into `key_file` – this way, there would be no ambiguity on the type of the value. WDYT?

**Comment by jfindlay** [comment]
That is a good point, but changing state parameters can break the state for many users.  We can either deprecate `key_url` in favor of `key_file` and create an api change warning or just make `key_file` a synonym for `key_url`.  I'm not favorable to the second approach.  The first approach will cause problems for everyone using it, so we'll have to make sure we're doing the Right Thing.  The Right Thing in this situation is not necessarily clear though as a key file could be provided by `salt://` which is technically a URL.

**Comment by falzm** [comment]
Another way to solve this problem would be to actually implement support for fetching mirror key files via HTTPS – as I thought it did in the first place. Requires more work, but doesn't break anything and makes everybody happy :)

**Comment by jfindlay** [comment]
@falzm, good idea.

**Comment by bebehei** [comment]
Hi guys,

I thought I stumbled over the same "bug" today. After long time fiddling around, I found out  the `key_url` even works with https-links. Is this bug still valid?

Here is the salt-state:
```
chrome-browser:
  pkgrepo.managed:
    - humanname: Google Chrome
    - name: deb http://dl.google.com/linux/chrome/deb/ stable main
    - dist: stable
    - file: /etc/apt/sources.list.d/chrome-browser.list
    - require_in:
      - pkg: google-chrome-stable
    - gpgcheck: 1
    #- key_url: /tmp/linux-signing-key.pub
    #- key_url: salt://desktop/chrome-browser/linux-signing-key.pub
    - key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub

google-chrome-stable:
   pkg.latest
```

Versions:
```
root@eckart:~# salt-minion --versions-report
           Salt: 0.17.5
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
```
on Ubuntu 14.04.1
