### ISSUE TITLE
git.latest returns Clean even it updated the repository

### ISSUE THREAD

**Issue by TaiSHiNet** [saltstack/salt#20411]
sls is: 
```
site.com: 
  git.latest:
    - name: git@github.com:sites/site.git
    - target: /var/www/site.com
    - rev: master
    - always_fetch: True
    - force_reset: True
    - require:
      - pkg: git
      - ssh_known_hosts: github.com
```
