### ISSUE TITLE
Unable to use enviroment variable in file.managed -name on Windows

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#20439]
OS: Windows Server 2012 R2
Salt: 2014.7.1

The state below will result in the error.
"Comment: Specified file %tmp%\file is not an absolute path"

```
file:
  file.managed:
    - name: '%tmp%\file'
    - contents_pillar: mainweb:file
```

Here is my temporary workaround:

```
file:
  file.managed:
    - name: {{ salt['cmd.run']('echo %tmp%') }}\file
    - contents_pillar: mainweb:file
```
