### ISSUE TITLE
develop somthing is wrong with cmd.run

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#20435]
```
[root@salt salt]# salt cloud\* cmd.run 'echo "woot" | grep woot'
cloud.math.xxxx.ca:
    woot | grep woot
```
this should be: "woot" NOT "woot | grep woot"

```
[root@salt salt]# salt cloud\* cmd.run "ls | grep a"
cloud.math.xxx.ca:
    ls: cannot access |: No such file or directory
    ls: cannot access grep: No such file or directory
    ls: cannot access a: No such file or directory
```
just strange.

I guess this will break many modules that use salt['cmd.run']
