### ISSUE TITLE
State module file.managed returns an error on Windows and test=Test

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#20441]
OS: Windows Server 2012 R2
Salt: 2014.7.1

This is a very minor bug.  Only occurs when running test=Test.  No issues when performing a normal state run.
```
ssh-key:
  file.managed:
    - name: {{ salt['cmd.run']('echo %tmp%') }}\id_rsa
    - contents_pillar: mainweb:github_private_key
```
```
          ID: ssh-key
    Function: file.managed
        Name: C:\Windows\TEMP\id_rsa
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "salt/state.py", line 1529, in call
                File "salt/states/file.py", line 1311, in managed
              KeyError: 'file.check_managed_changes'
     Started: 16:02:56.410000
    Duration: 0.0 ms
     Changes:   
```
