### ISSUE TITLE
impossible to link the same docker container to different names

### ISSUE THREAD

**Issue by eburghar** [saltstack/salt#20493]
links parameter should be a list instead of a dictionary, otherwise it's impossible to make several alias of the same container which is perfectly valid from docker command line

``` yaml
web_container:
  container.running:
    links:
      app_container: app
      app_container: ipython
```

should be instead

``` yaml
web_container:
  container.running:
    links:
      - app_container: app
      - app_container: ipython
```
