### ISSUE TITLE
Failhard and OnFail requisite interaction

### ISSUE THREAD

**Issue by highlyunavailable** [saltstack/salt#20496]
This issue is for 3 things:
1. Please clarify in the docs what the expected interaction with failhard and the onfail requisite is (even if it's just "you can't use onfail at all if the failing state is set to failhard or global failhard is set to true")
2. If this isn't by design, I'd like to request a feature in that even if failhard is set to true, Salt allows handling of the failure gracefully with an onfail requisite.
3. A setting of `- failhard: False` doesn't override a global failhard for a single state. Possibly an unintended "does it exist" vs. "read the value" check.

I'm not sure what the expected behavior is for failhard with onfail in the mix - it seems to just fail hard, regardless.

http://docs.saltstack.com/en/latest/ref/states/failhard.html doesn't say anything about the interaction here, nor does http://docs.saltstack.com/en/latest/ref/states/requisites.html#onfail talk about it.

I'm using salt 2014.7.1.

My use case here is as follows:

```
Ensure the InfluxDB admin user is present:
  influxdb_user.present:
    - name: {{ salt['pillar.get']('influxdb:admin_name') }}
    - passwd: {{ salt['pillar.get']('influxdb:admin_password') }}
    - user: root
    - password: root

Ensure the InfluxDB admin user is present using its own credentials:
  influxdb_user.present:
    - name: {{ salt['pillar.get']('influxdb:admin_name') }}
    - passwd: {{ salt['pillar.get']('influxdb:admin_password') }}
    - user: {{ salt['pillar.get']('influxdb:admin_name') }}
    - password: {{ salt['pillar.get']('influxdb:admin_password') }}
    - onfail:
      - influxdb_user: Ensure the InfluxDB admin user is present

Ensure the InfluxDB root user is absent:
  influxdb_user.absent:
    - name: root
    - passwd: root
    - user: {{ salt['pillar.get']('influxdb:admin_name') }}
    - password: {{ salt['pillar.get']('influxdb:admin_password') }}
```

Note that I'm deleting the `root` user using the new user I just created in that state. I have no way of knowing if I've deleted this user before at a machine level since it's a cluster user (grains are out and I'm running masterless so no way to just use a salt mine for this). Another machine could have created it and destroyed the root user before the currently executing machine got to it. The only real way I can test it is try logging in with root:root and if it fails try logging in with the other password. If that one fails, I want the rest of the state to fail since I need a valid login for everything else further down the state. I've got global failhard set to true so I don't leave machines in an inconsistent state in the case of a failure.

I could modify the state to try to log in with the proposed user if it failed, but this seems like it could be used for other things where I very selectively want to ignore a failure.
