### ISSUE TITLE
Custom modules can't be used in the file templates

### ISSUE THREAD

**Issue by diegows** [saltstack/salt#20498]
I hope this is not a duplicate. I can't use custom modules in file templates (file.managed), but it works in sls templates. I'm using jinja.

Example:

```
/etc/salt/minion.d/openstack.conf:
  file.managed:
    - source: salt://openstack/files/openstack.minion.conf
    - template: jinja
```

openstack/files/openstack.minion.conf:

```
keystone.endpoint: http://{{ salt.openstack.get_controller() }}:35357/v2.0
```

I got this running higstate: `Unable to manage file: Jinja variable 'dict object' has no attribute 'openstack'`

But if I do this, it works:

```
/etc/salt/minion.d/openstack.conf:
  file.managed:
    - source: salt://openstack/files/openstack.minion.conf
    - template: jinja
    - context:
      controller: {{  salt.openstack.get_controller() }}
```

openstack/files/openstack.minion.conf:

```
keystone.endpoint: http://{{ controller }}:35357/v2.0
```
