### ISSUE TITLE
Add the ability to exclude salt files in top.sls

### ISSUE THREAD

**Issue by kjkuan** [saltstack/salt#2053]
It would be nice if we could do this in the top file:

<pre>
base:
  '*':
    - packages
    - ssh
    - users
    
  'minionX-*':
    - apache

  'minionY-*':
    - mysql
    - exclude:
      - users
    - users.dba
</pre>

**Comment by blacked** [comment]
Doesn't work now.

**Comment by drawsmcgraw** [comment]
+1 to 'no longer working'.

I have a topfile like this (clipped for brevity):
```
base:
  '*':
    - team.add-team-users

  'G@roles:openstack or *kdc*':
    - match: compound
    - exclude:
      - sls: team.add-team-users
```

I've confirmed that the topfile is rendered with `-l debug` and my exclude statement *is* in there. But when I run a `state.show_highstate` it seems to be ignoring my request to exclude the specified state file.
