### ISSUE TITLE
Augment event.send state function to include data about a watched state into the event

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#20544]
Example:

``` yaml
a_test_file:
  file.managed:
    - name: /tmp/atestfile
    - source: salt://random_tests/file.txt
  event.send:
    # Include the running dictionary entry for any requisites in the event data
    - include_requisites: True
    - data: 
        status: "File has been created. 100% done"
    - onchanges:
      - file: a_test_file
```

Example event:

```
Event fired at Fri Dec 20 10:43:01 2013
*************************
Tag: a_test_file
Data:
{'_stamp': '2013-12-20_10:43:01.638387',
 'data': {
  'status': "File has been created. 100% done",
  'requisites': [
    {'file_|-a_test_file_|-/tmp/atestfile_|-file_managed': {
      'comment': 'File was updated',
      '__run_num__': 0,
      'changes': True,
      'name': '/tmp/atestfile',
      'result': True,
    },
   ],
 },
 'id': 'the_mid',
 'pretag': None,
 'tag': 'a_test_file'}
```

The changes in #15949 were intended to facilitate this. Now to come up with a good interface and write a little glue code...
