### ISSUE TITLE
State 'docker.xxxx' found in sls 'xxxxx' is unavailable

### ISSUE THREAD

**Issue by pgporada** [saltstack/salt#20560]
I am experiencing an issue with docker.pulled and docker.running being unavailable. It may be my own ignorance though, but I'd appreciate a fresh set of eyes.

```
[root@master /srv/salt]$ salt master test.ping
master:
    True
```

/srv/salt/top.sls
```
base:
  '*':
    - common_packages
    - hosts
    - resolv
  'role:master':
    - match: grain
    - docker-py                    # Loads the /srv/salt/docker-py/init.sls
    - docker                         # Loads /srv/salt/docker/init.sls
    - dock_apache              # Loads /srv/salt/dock_apache/init.sls => https://github.com/UtahDave/dock_apache
```

/srv/salt/docker-py/init.sls (installs fine)
```
docker-py: 
  pkg.installed: 
    - name: python-pip 
  pip.installed: 
    - name: docker-py 
    - reload_modules: True 
    - require: 
      - pkg: python-pip 
```
```
[root@master /srv/salt]$ pip list | grep docker
docker-py (0.7.2)
```

/srv/salt/docker/init.sls (installs fine and gives me a newer docker version than cent7 has)
```
docker:
  pkg.installed:
  - sources:
    - docker: http://cbs.centos.org/kojifiles/packages/docker/1.4.1/2.el7/x86_64/docker-1.4.1-2.el7.x86_64.rpm
  service.running:
  - name: docker
  - enable: True
```
```
[root@master /srv/salt]$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8/1.4.1
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8/1.4.1
```

Example that docker is working on my system
```
root@master /srv/salt]$ docker ps
CONTAINER ID        IMAGE                   COMMAND                CREATED             STATUS              PORTS                    NAMES
3a84541c96ff        rancher/server:latest   "/usr/share/cattle/c   24 minutes ago      Up 24 minutes       0.0.0.0:8080->8080/tcp   modest_heisenberg 
```

/srv/salt/dock_apache/init.sls (not working)
```
apache-image:
  docker.pulled:
    - name: utahdave/saltdemo
    - require_in: apache-container

apache-container:
  docker.installed:
    - name: apache
    - hostname: apache
    - image: utahdave/saltdemo
    - require_in: apache

apache:
  docker.running:
    - container: apache
    - ports:
      - "80/tcp":
        HostIp: ""
        HostPort: "80"
```

However, when I try to run the dock_apache container, it fails on the docker-py provided functions
```
          ID: apache-image
    Function: docker.pulled
        Name: utahdave/saltdemo
      Result: False
     Comment: State 'docker.pulled' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes:   
----------
          ID: apache-container
    Function: docker.installed
        Name: apache
      Result: False
     Comment: State 'docker.installed' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes:   
----------
          ID: apache
    Function: docker.running
      Result: False
     Comment: State 'docker.running' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes: 
```
