### ISSUE TITLE
Error adding bridge on Fedora 20: "sysctl net.bridge.bridge-nf-call-iptables does not exist" 

### ISSUE THREAD

**Issue by Symmetric** [saltstack/salt#20570]
Configuring a bridge on Fedora 20, I hit a kernel module loading issue.

When adding a bridge for the first time, `/proc/sys/net/bridge` is not present, and so salt fails when trying to set bridge configuration variables. If I've already added a bridge using brctl, then the `/proc/sys/net/bridge` directory is present and the salt config succeeds.

Here's my sls:

```
calico:
  network.managed:
    - enabled: True
    - type: bridge
    - name: calcio1
    - ipaddr: 1.1.1.1
    - netmask: 255.255.255.0
```

I'm testing this using `sudo salt-call -l debug state.sls calico`. Error output attached in this [gist](https://gist.github.com/Symmetric/c2a7dde89470a9679558).

Inspecting the output, brctl is installed before attempting to set the /proc/sys/net/bridge values ([line 62](https://gist.github.com/Symmetric/c2a7dde89470a9679558#file-gistfile1-sh-L62)), but installing brctl isn't sufficient to load the bridge module; only after running brctl for the first time is the bridge module loaded.

I suspect this means that salt should probably be loading the bridge module before attempting to set the net/bridge config vars.

Version: salt-call 2014.7.1 (Helium)
