### ISSUE TITLE
Please allow file.managed to force download without checking source_hash optionally

### ISSUE THREAD

**Issue by mubiic** [saltstack/salt#20588]
Version: salt 2015.2.0-435-g2936138 (Lithium)
Command: sudo salt-call --local state.highstate
State:
```
/var/cache/docker-install/{{ docker_debname }}:
  file.managed:
    - source: {{ docker_deburl }}{{ docker_debname }}
    {% if pillar['docker_debhash'] is defined and pillar['docker_debhash'] != '' %}
    - source_hash: {{ docker_debhash }}
    {% endif %}
    - user: root
    - group: root
    - mode: 644
    - makedirs: true
```

Failed warning: 
Unable to determine upstream hash of source file https://get.docker.com/ubuntu/pool/main/l/lxc-docker-1.5.0/lxc-docker-1.5.0_1.5.0_amd64.deb

It's ugly to use a cmd state to run wget to get the file. 
Some times the source hash is unknown or temporarily not important [like in development environment].  
Please add a switch to allow 'Force Download'.
