### ISSUE TITLE
file.search always returns True?

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#20603]
This seems broken...file.search always returns True, even if the pattern is not present.

```
# salt-call --local file.search /etc/rsyslog.conf 'foo':
local:
    True
```

```
# grep -c foo /etc/rsyslog.conf
0
```

```
# salt-call --local --versions
           Salt: 2014.7.1
         Python: 2.6.9 (unknown, Sep 13 2014, 00:25:11)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by cachedout** [comment]
Could you try a more confied test? This seems to work for me:

```
mp@silver ...salt/salt/cli % sudo salt-call --local file.search /tmp/foo 'boo'                                                                                                      (git)-[2014.7] 
local:
    False
mp@silver ...salt/salt/cli % sudo salt-call --local file.search /tmp/foo 'baz'                                                                                                      (git)-[2014.7] 
local:
    True
mp@silver ...salt/salt/cli % cat /tmp/foo                                                                                                                                           (git)-[2014.7] 
baz
mp@silver ...salt/salt/cli %      
```

**Comment by lorengordon** [comment]
Ugh, that's just frustrating. I tried with your example and it functions as expected. But anytime I search the file that actually matters, file.search always returns true. Can you try with more complex files?

**Comment by lorengordon** [comment]
@cachedout Any chance you've been able to test on more complex files? I can reproduce this across different systems, over and over. I'm testing on Amazon Linux, in case that makes a difference.

**Comment by lorengordon** [comment]
Just tested on Centos 6.6 and confirmed the problem there as well.

**Comment by lorengordon** [comment]
@cachedout, I figured out a definitive test case. An empty line in the file will cause file.search to always return true.

```
# echo "baz" > ~/foo
# salt-call --local file.search ~/foo 'bar'
local:
    False
# echo "" >> ~/foo
# salt-call --local file.search ~/foo 'bar'
local:
    True
```

**Comment by lorengordon** [comment]
This appears to affect any white space. Blank files (echo "" > foo), files with null lines (echo >> file), null files (echo > file), and even files with lines that contain only spaces (echo " " >> file).

**Comment by ferricoxide** [comment]
There appears to be a few significant regressions in `file.search` since `salt-2014.7.1-1.el6.noarch.rpm` was published to EPEL. Regexes that worked flawlessly in `salt-2014.7.0-3.el6.noarch.rpm` now function completely differently than before (things that previously evaluated to false now evaluate to true).

**Comment by ferricoxide** [comment]
Under 2014-7.0-3:
~~~
# echo "baz" > /tmp/foo
# salt-call --no-color --local file.search /tmp/foo 'bar'
local:
    False
# echo "" >> /tmp/foo
# salt-call --no-color --local file.search /tmp/foo 'bar'
local:
    False
# salt-call --versions-report
           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
~~~
Under 2014-7.1-1:
~~~
# echo "baz" > /tmp/foo
# salt-call --no-color --local file.search /tmp/foo 'ba r'
local:
    False
# echo "" >> /tmp/foo
# salt-call --no-color --local file.search /tmp/foo 'ba r'
local:
    True
[root@ip-172-31-18-194 ~]# salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
~~~
Other regex errors similarly show up after moving from 2014.7.0 to 2014.7.1 - but they probably all stem from similar "True should be False" conditions.

**Comment by lorengordon** [comment]
Just tested with 2014.7.2 and can confirm the issue exists there as well.

```
# echo "baz" > ~/foo
# salt-call --local file.search ~/foo 'bar'
local:
    False
# echo "" >> ~/foo
# salt-call --local file.search ~/foo 'bar'
local:
    True
# salt-call --versions-report
           Salt: 2014.7.2
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```
