### ISSUE TITLE
Set "--out-file" as standard for highstates

### ISSUE THREAD

**Issue by I3olle** [saltstack/salt#20629]
Hi there,

is it possible to somehow set --out-file=OUTPUT_FILE as standard? 
http://docs.saltstack.com/en/latest/ref/cli/salt.html#cmdoption-salt--out-file

I would like to have a file created everytime I call a highstate without having to append the --out-file. Is that possible? 

Thanks in advance

**Comment by rallytime** [comment]
@I3olle I think what you might be looking for is the "output_file" option where you can set a file name for the highstate to like you would on the command line lke so: `output_file: OUTPUT_FILE`. Keep in mind that since the output goes to the same file name each time, you'll likely be overwriting your previous run as I don't think this configuration option appends to the file or anything like that.

Is that what you're looking for?

**Comment by I3olle** [comment]
I don't know if it is what I'm looking for. Am I able to set this option in the master or minion config? Or is it something I would always have to append to a bash command? Because if it is the latter it would not be.
Overwriting the file would actually be fine. It's not meant to be a log but something very simple to grep through for errors and monitor the file age in order to see when the last highstate ran and how successful it was.
Would you like to elaborate on where to use this option?

**Comment by I3olle** [comment]
I tried to at least make the existing reactor, which runs a highstate every 60 minutes, create my file. So I appended some arg and return value but it doesn't create any file. Is my syntax correct?

```
{% set date = salt['cmd.run']('date "+%d-%m-%y %H:%M"') %}

highstate_run:
  cmd.state.highstate:
    - tgt: {{ data['id'] }}
    - arg:
      - "--out-file=/var/log/salt/{{ data['id'] }}-{{ date }}.yaml"
```
