### ISSUE TITLE
Implementing boto rds state

### ISSUE THREAD

**Issue by claudiupopescu** [saltstack/salt#20626]
I'm trying to write the state for boto_rds but I am not sure how to structure things.
And to be clear, writing the boto_rds.py state which is not implemented.

So far I have this options:
* Separating parameter group from rds:
```
create-rds-parameter-group:
  boto_rds.parameter_group:
    - name: myparamgroup
    - db_family: mysql5.6
    - description: "Testing param group state"
    - parameters:
      - back_log: 1
      - binlog_cache_size: 4096

create-rds-instance:
  boto_rds.present:
    - name: mydbinstance
    - allocated_storage: 5
    - db_instance_class: db.t2.micro
    - engine: MySQL
    - master_username: myuser
    - master_user_password: mypassword
    - db_parameter_group_name: myparamgroup
    - region: eu-west-1
    - require:
      - boto_rds: create-rds-parameter-group
```
* Create and update the parameter group from within boto_rds.present:
```
create-rds-instance:
  boto_rds.present:
    - name: mydbinstance
    - allocated_storage: 5
    - db_instance_class: db.t2.micro
    - engine: MySQL
    - master_username: myuser
    - master_user_password: mypassword
    - db_parameter_group_name: myparamgroup
    - pg_options:
      - back_log: 1
      - binlog_cache_size: 4096
    - region: eu-west-1
```
* Or just create a new state called something like ```boto_rds_pg```.

Or maybe there are other better options?
Any suggestions on how this should be implemented?
