### ISSUE TITLE
init_delay is not honouring its parameter for services module

### ISSUE THREAD

**Issue by spareslant** [saltstack/salt#20631]
Hi,
It seems init_delay has no effect. 
consider following state file `random_tests/services_test.sls`
```yaml
service-snmpd:
  service.running:
    - name: snmpd
    - enable: True
    - init_delay: 120
```
Below command was run:
```bash
salt -E 'machine01' state.sls random_tests.services_test  saltenv=mydc  -t 5000 -v
```
And Following is the output:
```yaml
Executing job with jid 20150212152951921367
-------------------------------------------

machine01:
----------
          ID: service-snmpd
    Function: service.running
        Name: snmpd
      Result: True
     Comment: Service snmpd is already enabled, and is running
     Started: 15:29:57.581759
    Duration: 218.68 ms
     Changes:   
              ----------
              snmpd:
                  True

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
Please note "duration" in above output. It is less than 120 seconds. 
Even if snmpd took only 218ms to start, it should have waited for 120 seconds .

```yaml
salt --versions-report
           Salt: 2014.7.0
         Python: 2.6.6 (r266:84292, Jul 10 2013, 22:48:45)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by jfindlay** [comment]
@spareslant, thanks for the detailed report.

**Comment by clinta** [comment]
Based on the results in the report I wouldn't expect a delay in that circumstance. `Comment: Service snmpd is already enabled, and is running` Indicates that the service was not started or restarted, so salt shouldn't be triggering a delay.

However, while investigating this I did notice what looks like a bug in service.py that init_delay is only called during running and not during mod_watch.

**Comment by travishegner** [comment]
I can confirm that this issue also affects us.

```sls
dnsmasq:
  pkg.installed: []
  service.running:
  - enable: true
  - require:
    - pkg: dnsmasq
  - init_delay: 5
```
Because dnsmasq (a local caching dns resolver) rewrites the resolv.conf before actually being ready to accept queries, some random state after this one that may require a dns query will fail. I expected init_delay to solve that problem by giving the service ample time to initialize. However, I am seeing the following output on the server's inital highstate:

```yaml
----------
          ID: dnsmasq
    Function: service.running
      Result: True
     Comment: Service dnsmasq is already enabled, and is in the desired state
     Started: 08:28:17.756719
    Duration: 23.54 ms
     Changes:   
----------
          ID: git
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: git.
     Started: 08:28:17.780367
    Duration: 674.934 ms
     Changes:   
```

The failure to install git is because of a dns resolution error.

As @clinta mentions, we believe that our package manager is actually starting the service, and then by the time salt goes to evaluate it, it is already running, therefore the init_delay doesn't take effect.

```yaml
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

Obviously in our case, the best solution is to get dnsmasq fixed, but that is not an immediate fix for us. I believe I can work around it by making dnsmasq the last state.

**Comment by travishegner** [comment]
So @clinta and I (mostly him) were able to come up with a work-around for this issue.

```sls
dnsmasq:
  pkg.installed: []
  service.running:
    - enable: true
    - require:
      - pkg: dnsmasq
    - init_delay: 5

dnsmasq-wait:
  module.run:
    - name: test.sleep
    - length: 5
    - onchanges:
      - pkg: dnsmasq
```

Results in:
```yaml
----------
          ID: dnsmasq
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: dnsmasq.
     Started: 12:31:30.240034
    Duration: 1858.278 ms
     Changes:   
              ----------
              dnsmasq:
                  ----------
                  new:
                      2.68-1
                  old:
                      
              dnsmasq-base:
                  ----------
                  new:
                      2.68-1
                  old:
                      
              libmnl0:
                  ----------
                  new:
                      1.0.3-3ubuntu1
                  old:
                      
              libnetfilter-conntrack3:
                  ----------
                  new:
                      1.0.4-1
                  old:
                      
----------
          ID: dnsmasq
    Function: service.running
      Result: True
     Comment: Service dnsmasq is already enabled, and is in the desired state
     Started: 12:31:32.099562
    Duration: 24.427 ms
     Changes:   
----------
          ID: dnsmasq-wait
    Function: module.run
        Name: test.sleep
      Result: True
     Comment: Module function test.sleep executed
     Started: 12:31:32.125262
    Duration: 5005.689 ms
     Changes:   
              ----------
              ret:
                  True
----------
          ID: git
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: git.
     Started: 12:31:37.131104
    Duration: 3062.067 ms
     Changes:   
              ----------
              git:
                  ----------
                  new:
                      1:1.9.1-1ubuntu0.1
                  old:
                      
              git-completion:
                  ----------
                  new:
                      1
                  old:
                      
              git-core:
                  ----------
                  new:
                      1
                  old:
                      
              git-man:
                  ----------
                  new:
                      1:1.9.1-1ubuntu0.1
                  old:
                      
              liberror-perl:
                  ----------
                  new:
                      0.17-1.1
                  old:
                      
              patch:
                  ----------
                  new:
                      2.7.1-4ubuntu1
                  old:
                      
```

This causes the dnsmasq-wait state to execute test.sleep for 5 seconds only when the dnsmasq package is installed or updated. Unfortunately, if you have more than one state to 'watch' (read 'onchanges'), you may also be affected by #19592.

I would imagine that if you wanted that delay to happen every time you could change the "onchanges" to simply a "require" and the module.test.sleep would be executed each time.
