### ISSUE TITLE
type:vlan can not bring up interface when doing state checking

### ISSUE THREAD

**Issue by cxfcxf** [saltstack/salt#20650]
the version i use: salt-minion-2014.7.0-3
when i try to configure vlan interface like the example did

```
network/configs.sls
eth2:
  network.managed:
    - type: slave
    - master: bond0

eth3:
  network.managed:
    - type: slave
    - master: bond0

bond0:
  network.managed:
    - type: bond
    - ipaddr: 10.10.88.118
    - netmask: 255.255.255.0
    - enabled: True
    - lacp_rate: fast
    - use_in:
      - network: eth2
      - network: eth3
    - require:
      - network: eth2
      - network: eth3
    - mode: 802.3ad

bond0.1:
  network.managed:
    - type: vlan
    - ipaddr: 10.10.88.120
    - use:
      - network: bond0
    - require:
      - network: bond0
```

the result is something like
```
----------                                                                                                                                                            [3/1945]
          ID: eth2
    Function: network.managed
      Result: True
     Comment: Interface eth2 is up to date.
     Started: 20:09:33.757780
    Duration: 221.664 ms
     Changes:
----------
          ID: eth3
    Function: network.managed
      Result: True
     Comment: Interface eth3 is up to date.
     Started: 20:09:33.979781
    Duration: 170.987 ms
     Changes:
----------
          ID: bond0
    Function: network.managed
      Result: True
     Comment: Interface bond0 is up to date.
     Started: 20:09:34.151029
    Duration: 209.75 ms
     Changes:
----------
          ID: bond0.1
    Function: network.managed
      Result: False
     Comment: 'bond0.1'
     Started: 20:09:34.361038
    Duration: 14.169 ms
     Changes:

Summary
------------
Succeeded: 3
Failed:    1
------------
Total states run:     4
```
i dont know if this is fixed on later version
but if you manually bring it up, the state check will pass.

so i think type:vlan can not bring up vlan interface.
