### ISSUE TITLE
illegal function arg not giving errors

### ISSUE THREAD

**Issue by spareslant** [saltstack/salt#20683]
Hi, 
Consider following state file `random_tests/populate_hosts.sls`
```yaml
populate_file_with_blocks:
  file:
    - blockreplace
    - name: /tmp/testfile
    - marker_start: '#== START ==#'
    - marker_end: '#== END ==#'
    - illegal_function_arg: |
          xx.xx.xx.xx     somerandomhost
    - append_if_not_found: True
    - show_changes: True
```
Above file must produce an error either in logs or in console output. But it does not. It does append markers in file `/tmp/testfile`

Following command was run
```bash
salt -E 'somehost' state.sls random_tests.populate_hosts saltenv=mydc -t 5000
```
Following is the output:
```yaml
somehost:
----------
          ID: populate_file_with_blocks
    Function: file.blockreplace
        Name: /tmp/testfile
      Result: True
     Comment: No changes needed to be made
     Started: 16:45:54.808232
    Duration: 0.814 ms
     Changes:   

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```
Contents of file:
```bash
#== START ==#

#== END ==#
```
I mistakenly typed `content`  as `contents`. (notice s after content) and without any errors , it was difficuilt and time consuming to spot typo.

**Comment by jfindlay** [comment]
@spareslant, thanks for the report.

**Comment by terminalmage** [comment]
@spareslant I see no usage of ``content`` anywhere in your example. Can you clarify?

**Comment by rallytime** [comment]
Closing due to lack of response. We can reopen this in the future, if needed.

**Comment by spareslant** [comment]
Sorry for delayed reply. I guess I was not clear.  
In the beginning of this issue, I mentioned a state file. I am re-iterating same  below:

```yml
populate_file_with_blocks:
  file:
    - blockreplace
    - name: /tmp/testfile
    - marker_start: '#== START ==#'
    - marker_end: '#== END ==#'
    - illegal_function_arg: |
          xx.xx.xx.xx     somerandomhost
    - append_if_not_found: True
    - show_changes: True
```

If you look at above state file carefully,  using "illegal_function_arg" in above formula must give error. But it does not produce any error and appends markers in /tmp/testfile file. This should not happen.
