### ISSUE TITLE
archive.extracted hashes the wrong value

### ISSUE THREAD

**Issue by jasonkeene** [saltstack/salt#20681]
I have this in my states:

```
ioncube_loaders_lin_x86-64.tar.gz:
  archive.extracted:
    - name: /srv/ioncube/
    - source: http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
    - source_hash: sha1=f763ea8f1acfbd27c4fb6e43af3c3748ae6399a8
    - archive_format: tar
    - tar_options: z
```

It gives me this error:

```
          ID: ioncube_loaders_lin_x86-64.tar.gz
    Function: archive.extracted
        Name: /srv/ioncube/
      Result: False
     Comment: File sum set for file /var/cache/salt/minion/files/base/_srv_ioncube_.tar of f763ea8f1acfbd27c4fb6e43af3c3748ae6399a8 does not match real sum of b3efce1a8bf153871f576cecb5c627a827114294
     Started: 11:07:34.778603
    Duration: 1743.854 ms
     Changes:
```

Here are the hash values for the .tar and .tar.gz:

```
$ wget -O- http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz 2> /dev/null | tee >(echo '.tar.gz' $(sha1sum)) >(echo '.tar' $(gunzip -c | sha1sum)) > /dev/null
.tar b3efce1a8bf153871f576cecb5c627a827114294 -
.tar.gz f763ea8f1acfbd27c4fb6e43af3c3748ae6399a8 -
```

So it is checking the hash against the gunziped tar. This is unexpected behavior as the source_hash worked for file.managed.

I am running 2014.7.1 on both minions and master.
