### ISSUE TITLE
Locale broken latest stable 2014.7

### ISSUE THREAD

**Issue by lblasc** [saltstack/salt#20716]
Hello,

Here is my sls which tries to set up locale on latest Debian Jessie build.

```
locales:
  pkg:
    - installed

  cmd.wait:
    - name: /usr/sbin/locale-gen; /usr/sbin/update-locale

en_US.UTF-8:
  file.uncomment:
    - name: /etc/locale.gen
    - regex: en_US.UTF-8 UTF-8
    - char: '# '
    - require:
      - pkg: locales
    - watch_in:
      - cmd: locales

  locale:
    - system
    - require:
      - pkg: locales
```

Version 2014.7.0+ds-2 worked fine, but in 2014.7.1+ds-3 /etc/default/locale is generated:

```
#  File generated by update-locale
"
LANG=en_US.UTF-8"
```

In older version result is:

```
#  File generated by update-locale

LANG=en_US.UTF-8
```

Thanks,
Luka
