### ISSUE TITLE
Add a django state module to interpret results of django.syncdb

### ISSUE THREAD

**Issue by johtso** [saltstack/salt#20724]
```
ID: app_migrate
    Function: module.run
        Name: django.syncdb
      Result: True
     Comment: Module function django.syncdb executed
     Started: 17:15:04.016255
    Duration: 490.249 ms
     Changes:
              ----------
              ret:
                  CommandError: Conflicting migrations detected (0016_auto_20150210_1255, 0017_migration in app).
                  To fix them run 'python manage.py makemigrations --merge'
```
