### ISSUE TITLE
Salt mine returning strange results

### ISSUE THREAD

**Issue by mooperd** [saltstack/salt#20729]
Hello,

So our intention is to use the salt mine to hold the ip addresses of various parts of our infrastructure so we can build configuration files. When we use Jinja to build these config files we see that Jinja is not being faithful and seems to be exhibiting some random behaviour on what it will and will not take from the mine. (or the mine is being funny). 

Here is the file were trying to populate:

```
==> rabbitmq.json <==
{% for server, addrs in salt['mine.get']('*', 'network.ip_addrs', expr_form='glob').items() %}
    master: {{ addrs }}
{% endfor %}
```

The output on the minion

```
    master: ['172.31.2.41']
    master: ['172.31.10.214']
    master: ['172.31.2.58']
    master: ['172.31.11.98']
```

This is all of our minions. How come the file is not being populated with all of these?

```
[root@ip-172-31-11-98 files]# salt '*' grains.item ipv4
sensu-server-2:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.14.41
uchiwa-2:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.15.4
sensu-api-2:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.0.66
sensu-server-1:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.1.142
uchiwa-1:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.7.250
sensu-client-1:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.13.115
redis-1:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.15.113
sensu-client-2:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.10.14
salt-minion-1:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.2.41
sensu-api-1:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.12.186
master:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.11.98
rabbitmq-1:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.7.251
salt-minion-2:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.2.58
salt-minion-3:
    ----------
    ipv4:
        - 127.0.0.1
        - 172.31.10.214
```

```
==> /srv/pillar/top.sls <==
base:
#must find a better way of identifying servers needing sensu stuff.
  'sensu-*':
    - sensu
  '*':
    - ip
```

```
==> /srv/pillar/ip.sls <==
mine_functions:
  network.ip_addrs: [eth0]
```
