### ISSUE TITLE
salt-winrepo factors and features and RFEs for an impoved windows salt installer 

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#20737]
@UtahDave as you probaly noticed I have done a fair few salt-winrepo sls files and have quite a collection of notes, thoughts and ideas, as to what an improved/refactored salt windows installer should try to make easier.

Is there a start of such a list of issues somewhee that are already in your head, so I don't create too many duplicates? 

What's the best way to collect these requirements,issues, improvements, RFEs and wishlist items? 

Is it a top level issue referring to a number of issues or RFEs?

**Comment by rallytime** [comment]
@TheBigBear Thanks for opening this issue/question. I am not sure if there is a more complete list of work to be done that @UtahDave or @shanedlee knows about, but in this issue tracker you should start by looking for issues tagged with the "Windows" label.

**Comment by UtahDave** [comment]
Hey, @TheBigBear. Your work on salt-winrepo has been amazing! Thanks so much.

I'd really like to hear your thoughts and ideas on improvements and refactors you'd like to see. I have a lot of things I'd like to do to improve it as well, but my time has been taken up for the last good while by other responsibilities. We have SaltConf coming up in a few weeks which is taking up all my time right now, but once we get past SaltConf I'd like to start visiting these issues.

Would you mind creating a Google doc and sharing it with me and Shane?  dave@saltstack.com and slee@saltstack.com   Let's take the next few weeks to list and organize what needs to be fixed and updated and start from there.

Once we've got everything documented we should probably create a github issue for each major piece.

**Comment by eliasp** [comment]
Some related thoughts I'd like to drop here:

I'd like to see the winrepo definition structure to be updated a bit to match the following requirements:
* Allow `msiexec` to be specified for installer/uninstaller separately (e.g. Adobe Flash, although installed as MSI can't be properly removed via `msiexec` but needs a [separate uninstaller](http://download.macromedia.com/get/flashplayer/current/support/uninstall_flash_player.exe))
* Allow to set checksums for installers/uninstallers - currently, there's no integrity verification at all
* Allow packages to have multiple full names, as some installers deploy multiple "packages" into the system which means, the reverse mapping of the `full_name` to the winrepo name works only for one of them. I wonder whether we should probably even allow to define a regular expression for full names to be able to map packages, where a dozen of different variants (e.g. MS Language Packs) just differ in something like a locale suffix

To prevent the attribute list from getting more and more prefixed (`install_*`/`uninstall_*`) keys, a nested structure like this would be IMHO better:
```YAML
adobe.flash:
    16.0.0.305:
        full_names:
            - 'Adobe Flash Player 16 NPAPI'
            - 'Adobe Flash Player 16 ActiveX'
        install:
            installer: 'http://download.macromedia.com/get/flashplayer/current/licensing/win/install_flash_player_16_plugin.msi'
            msiexec: true
            checksums:
                md5: 5afa5e8dc63fff6dfee31729d40dee84
                sha256: 678b609ab2f86d3696617d2a42940defca2612a5a4f69803efda994ff7f8ce11
            reboot: false
            flags: ' /q'
        uninstall:
            uninstaller: 'http://download.macromedia.com/get/flashplayer/current/support/uninstall_flash_player.exe'
            msiexec: false
            checksums:
                md5: 9508df302b4c619dcb0c806796cae5ef
                sha256: ca94e32cf0bee56e549185b65612c09781cb37f1c507497bb93fdd00559ba329
            reboot: false
            flags: ' /qn'
```

Although this looks right now quite convoluted, those definitions could be slimmed down dramatically once Salt's YAML anchor/reference rendering is fixed (#14550) and using Jinja in winrepo definitions is possible (#6859).

**Comment by UtahDave** [comment]
@eliasp I really like your ideas. Makes a lot of sense to me.

Are there any lessons we can learn from how chocolatey and others do their packaging metadata?

**Comment by eliasp** [comment]
@UtahDave Can't really tell WRT Chocolatey - haven't looked closely at their packaging yet.

Something else I just came across where I wondered whether we could possibly handle it in the next iteration of win_repo:

Some things are deployed as `*.msu` file, e.g. new PowerShell versions.
`*.msu` packages need to be installed using `wusa.exe Windows6.1-KB2506143-x64.msu /quiet /norestart`.

So I wonder whether this would make sense (unrelated lines left out):
```YAML
microsoft.powershell:
    3.0:
        install:
            method: wusa
```
The `method` would replace `msiexec` and would allow just adding new Python modules for `method` handlers. By default `native` (simply execute the `Installer.exe`), `msiexec` and `wusa` would be supported.
