### ISSUE TITLE
In HG module opts with spaces are wrongly parsed

### ISSUE THREAD

**Issue by gidantribal** [saltstack/salt#20743]
This used to work before:

```
ssh://hg@bitbucket.org/target:
   hg.latest:
     - rev: tip
     - target: /var/www/html/wiki
     - opts: "--ssh 'ssh -i /home/vagrant/.ssh/default.pem'"
     - require:
        - ssh_known_hosts: bitbucket.org
        - file: /home/vagrant/.ssh/default.pem
```

But now I get an error, as if the inner quotes are ignored:

```
[INFO    ] Executing command ['hg', 'clone', 'ssh://hg@bitbucket.org/target', '/target', '--ssh', "'ssh", '-i', "/home/ubuntu/.ssh/default.pem'"] in directory '/root'
[ERROR   ] Command ['hg', 'clone', 'ssh://hg@bitbucket.org/target', '/target', '--ssh', "'ssh", '-i', "/home/ubuntu/.ssh/default.pem'"] failed with return code: 255
[ERROR   ] output: hg clone: option -i not recognized
hg clone [OPTION]... SOURCE [DEST]

make a copy of an existing repository

options:

 -U --noupdate          the clone will include an empty working copy (only a
                        repository)
 -u --updaterev REV     revision, tag or branch to check out
 -r --rev REV [+]       include the specified changeset
 -b --branch BRANCH [+] clone only the specified branch
    --pull              use pull protocol to copy metadata
    --uncompressed      use uncompressed transfer (fast over LAN)
 -e --ssh CMD           specify ssh command to use
    --remotecmd CMD     specify hg command to run on the remote side
    --insecure          do not verify server certificate (ignoring web.cacerts
                        config)

[+] marked option can be specified multiple times
```
