### ISSUE TITLE
file.search appears to be broken, returning True when it should be False

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#20806]
Haven't had time to investigate this thoroughly.

```
root@master:~# salt basepi file.search '/etc/iscsi/iscsid.conf' 'IBM01SU323716-7'
basepi:
    True
root@master:~# salt basepi cmd.run 'grep IBM01SU323716-7 /etc/iscsi/iscsid.conf'
basepi:

root@master:~# salt basepi cmd.retcode 'grep IBM01SU323716-7 /etc/iscsi/iscsid.conf'
basepi:
    1
root@master:~# salt basepi test.versions_report
basepi:
               Salt: 2014.7.2
             Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.4.4
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.4
               Mako: Not Installed
```

**Comment by rallytime** [comment]
I can reproduce this:
```
root@nt-master:~/SaltStack/salt# salt --versions
           Salt: 2014.7.2-65-g078865a
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
root@nt-master:~/SaltStack/salt# salt nt-master file.search '/etc/salt/minion' 'asdfasdf'
nt-master:
    True
root@nt-master:~/SaltStack/salt# salt nt-master cmd.run 'grep asdfasdf /etc/salt/minion'
nt-master:

root@nt-master:~/SaltStack/salt#
```
