### ISSUE TITLE
Loopback filesystems always remount (option=loop) regardless of zero changes (2014.7)

### ISSUE THREAD

**Issue by jrgp** [saltstack/salt#20855]
Hi,

Similar to #20828, I have several mounts defined that are squashfs files which are loop back mounted. Every time I run salt.highstate they're remounted even though nothing changes, regardless of whether loop is specified or not in the mount definition.

Tested and confirmed in Ubuntu and Debian using the official salt repos

Will attach a pull shortly...

Definition:

```yaml
/usr/local/pymaster/templates:
  file.directory:
    - makedirs: True
  mount.mounted:
    - device: /usr/local/pymaster/images/templates.sfs
    - opts: loop,ro
    - mkmnt: False
    - persist: True
    - fstype: squashfs
    - require:
      - file: /usr/local/pymaster/images
```
