### ISSUE TITLE
service.dead tries to start service

### ISSUE THREAD

**Issue by lsh-0** [saltstack/salt#20858]
I have a flag switching services to 'dead' if it looks like it's provisioning a Docker container. The config looks a bit like:

```
    service:
        - {% if salt['grains.get']('dockerized') %}dead{% else %}running{% endif %}
        - require:
            - pkg: syslog-ng
```
However when running for the first time, I get this:
```
    State: - service
    Name:      syslog-ng
    Function:  dead
        Result:    False
        Comment:   Failed to start the service
        Changes:   syslog-ng: False
```
Subsequent runs succeed with:
```
    State: - service
    Name:      syslog-ng
    Function:  dead
        Result:    True
        Comment:   The service syslog-ng is already dead
        Changes:   
```

Is this a bug or expected behaviour?

**Comment by rallytime** [comment]
@lsh-0 Is that first state the entire state that you're running, or just a piece of it? It looks like something isn't quite right there.

Also, can you post the output of `salt --versions-report`?

**Comment by lsh-0** [comment]
That was just a snippet. The full state is/was:
```
syslog-ng:
    pkg.installed:
        - pkgs:
            - syslog-ng
            - syslog-ng-core
    
    file.managed:
        - name: /etc/syslog-ng/syslog-ng.conf
        - source: salt://base/config/etc-syslog-ng-syslog-ng.conf 
        - template: jinja
        - require:
            - pkg: syslog-ng
            
    service:
        {% if salt['grains.get']('dockerized') %}- dead{% else %}- running{% endif %}
        - reload: True
        - require:
            - pkg: syslog-ng
            - file: syslog-ng
        - watch:
            - file: syslog-ng
```
