### ISSUE TITLE
develop: file.managed user and group always shows change when not root.

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#20867]
file.managed user and group always shows change when not using the default root user.

on the develop branch.
```
root@opencs-db:/# salt --version
salt 2015.2.0-530-ga0440c6 (Lithium) 
```

using a sls like:

```
{{ sls }} config:
    file.managed:
        - name: /tmp/file
        - source: {{ vars.config_source }}
        - template: jinja
        - context: { vars: {{ vars|json }} }
        - user: postgres
        - group: postgres
        - mode: 0640
```

then run highstate always shows the user and group as changed.
```
          ID: _sdl.postgresql.server.config config
    Function: file.managed
        Name: /etc/postgresql/9.3/main/postgresql.conf
      Result: True
     Comment: File /etc/postgresql/9.3/main/postgresql.conf updated
     Started: 13:24:59.329736
    Duration: 46.299 ms
     Changes:   
              ----------                                                                                                                                                                                                                                                                                                     
              group:
                  postgres
              user:
                  postgres
```
