### ISSUE TITLE
state file.manage test=True  has a result None when should be True

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#20909]
[root@salt ~]# salt --version
salt 2015.2.0-2929-gcf5157c (Lithium)

when running in test mode... Result is None ... should be True
```
----------
          ID: _sdl.strongswan ipsec_config
    Function: file.managed
        Name: /etc/ipsec.conf
      Result: None
     Comment: The file /etc/ipsec.conf is in the correct state
     Started: 18:07:42.732420
    Duration: 7.967 ms
     Changes:   
----------
```
