### ISSUE TITLE
rest_tornado does not start

### ISSUE THREAD

**Issue by Vehyla** [saltstack/salt#20945]
I have made sure the ssl certs are in the right location.  python-tornado is installed and I am using salt-2014.7.2-.  When I add the following lines to the /etc/salt/master config and restart.  I can not see anything say it's not starting.  But the port is never up.  The debugging logs show it has the configuration.  But I don't see any errors or really anything saying it tried.   I wasn't able to get much help from IRC.  So, I'm hoping someone here can help, or at least show me how to enable more verbose debugging.
```yaml
rest_tornado:
    port: 8000
    ssl_crt: /etc/pki/tls/certs/localhost.crt
    ssl_key: /etc/pki/tls/certs/localhost.key
    debug: True
    disable_ssl: False
    websockets: True
```
