### ISSUE TITLE
Process group support in supervisord state is painful

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#20961]
It's necessary to append : if a process group is used, but if process group is not used, you can't append : or :_. This doesn't match with how supervisorctl can be used from the CLI. From the CLI you can always use : or :_ and it just works. The state module should always manage the process group whether or not : is used, and should manage individual process group members if :number is used.

Here's an example of a hacky workaround I need to use:

``` yaml
 Ensure supervisor service {{ worker }} is running:
   supervisord.running:
    # We must append : if a process group is used, but if process group is not
    # used, we can't append :
    {% if process_group -%}
    - name: "{{ worker }}:"
    {% else %}
    - name: "{{ worker }}"
    {% endif %}
```
