### ISSUE TITLE
Minion key gets regenerated when state process hangs, communication lost with master

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#21017]
This have been a tricky one to find. But we've had problems with minions stopping to work "suddenly" but I think I've got a lead now.

If I do this:
1. Run a state
2. The state runs an process that for some reason fails/hangs/gets corrupted
3. We reboot the machine or restart the minion
4. The minion is unreachable after and starts to send auth requests

When I compare the key of the minion and the one accepted on the master, they differ! so it seems like the key have been regenerated on the minion.

If I delete the key on the master and re-add it then communication starts to work again. 

I think there are two issues here:
1. Why does the key get regenerated? Is this expected behaviour?
2. How can I easily see on the master if there is a minion attempting to connect with an existing id? This is not clear as it is now and gets hard to diagnose.

Environment
Saltmaster runs ubuntu 14.04, minion runs Windows Server 2012 R2.

Master

```
root@saltmaster:/etc/salt# salt-run --versions-report
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

Minion (yes I have different versions of the minion and master but this problems seems related to windows, not the communication between them)

```
root@saltmaster:/etc/salt# salt 'dev-eu-iceb-02' test.versions_report
dev-eu-iceb-02:
               Salt: 2014.1.7
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
             PyYAML: 3.11
              PyZMQ: 14.1.1
                ZMQ: 4.0.4
```
