### ISSUE TITLE
pkg.install failed to install/update: Java 7 Update 9 (64-bit)

### ISSUE THREAD

**Issue by hari316** [saltstack/salt#21054]
# /srv/salt/win/repo/jre/init.sls
```yaml
jre:
  7.0.90:
    installer: salt://win/repo/jre/jre-7u9-windows-x64.exe
    full_name: 'Java Runtime Enviorment x86_64 (7u9-b05)'
    reboot: False
    install_flags: ' /s '
```

# package.sls
```yaml
windows-package-manager:
  pkg.installed:
    - pkgs:
       - jre
```
OUTPUT:
```yaml
----------
          ID: windows-package-manager
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: jre.
     Started: 18:03:27.399000
    Duration: 7909.0 ms
     Changes:
              ----------
              Java 7 Update 9 (64-bit):
                  ----------
                  new:
                      7.0.90
                  old:
Summary
------------
Succeeded: 0 (changed=1)
Failed:    1

Total states run:     1
```

# SALT-SERVER:
```yaml
jenkins@ubuntu-master:/srv/salt/win/repo$ salt --versions-report
           Salt: 2014.7.1
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
#WINDOWS-MINION:
```yaml
win-minion02:
               Salt: 2014.7.1
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.1.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed
```
