### ISSUE TITLE
feature request: salt-cloud pillar config support for extends directive

### ISSUE THREAD

**Issue by gladiatr72** [saltstack/salt#21074]
The salt-cloud configuration supports an 'extends' directive for profiles and providers that greatly enhances the conciseness of the /etc/salt/cloud\* configuration bits.  

To move the configuration to pillar requires the user to manually unwind any defined extensions.

``` yaml
my_provider_label:
   sauce:tomato
   secret: supersecret
   apikey: whee9994428
   location: somewhere

my_provider_label_somewherelse:
   extends: my_provider_label
   location: somewhere_else
```

All of the duplicate material from the first provider my be manually copied.  This is  painful if there is only one level of extension.

As part of this request, I think it is also important to include the cloud config parsing functionality to take care of the form that has arrays of providers under a provider label.  I wouldn't use it, but if the work is to be done, it should probably include that as well.

I have written an external pillar to work with extensions as well as limit which data is sent to my cloud controllers, so this isn't an emergency for me, but I think for the future, someone should be able to take their salt-cloud configs and drop it into pillar with little or no change in the way they are able to interact with that data.
