### ISSUE TITLE
salt-ssh: Password prompt in output when running a command with password authentication

### ISSUE THREAD

**Issue by Supermathie** [saltstack/salt#21117]
The `Password:` prompt is visible in the output when using salt-ssh with password authentication:

```
→ sudo salt-ssh monster -r 'echo I AM ALIVE'
monster:
    ----------
    retcode:
        0
    stderr:
        
    stdout:
        Password: 
        I AM ALIVE
```

Roster file:
```
monster:
    host: monster
    user: admin
    passwd: admin
```

Version:
`salt-ssh                    2014.7.1+ds-3precise1`
