### ISSUE TITLE
file.managed source_hash fails half of the time when using the www.apache.org domain

### ISSUE THREAD

**Issue by mcorsen** [saltstack/salt#21119]
To reproduce, create a state file with the following and run state.sls.

```
{% set tc_version = pillar.get('tc_version', '1.2.40') %}
httpd_download_mod_jk:
  file.managed:
    - name: /root/tomcat-connectors-{{ tc_version }}-src.tar.gz
    - source: http://apache.cs.utah.edu/tomcat/tomcat-connectors/jk/tomcat-connectors-{{ tc_version }}-src.tar.gz
    - source_hash: https://www.apache.org/dist/tomcat/tomcat-connectors/jk/tomcat-connectors-{{ tc_version }}-src.tar.gz.sha1
```

About half of the time, it will fail with this error:

```
Unable to manage file: hostname 'www.apache.org' doesn't match either of '*.openoffice.org', 'openoffice.org'
```

When I use curl on the source_hash URL it works everytime.
