### ISSUE TITLE
iptables issue.

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#21133]
salt release: develop branch

sls
```
{{ sls }} accept loopback:
    iptables.append:
        - name: accept loopback
        - family: ipv4
        - table: filter
        - chain: whitelist
        - in-interface: lo
        - jump: ACCEPT
        - save: True
        - require:
            - iptables: {{ sls }} chain whitelist
```

highstate
```
----------
          ID: _sdl.iptables.whitelist accept loopback
    Function: iptables.append
        Name: accept loopback
      Result: False
     Comment: Failed to set iptables rule for accept loopback.
              Attempted rule was /sbin/iptables --wait -t filter -A whitelist   --in-interface lo  --fun append --jump ACCEPT for ipv4                                               
     Started: 20:32:30.732105
    Duration: 42.135 ms
     Changes:   
----------
```

raw run
```
# /sbin/iptables --wait -t filter -A whitelist   --in-interface lo  --fun append --jump ACCEPT
iptables v1.4.21: unknown option "--fun"
Try `iptables -h' or 'iptables --help' for more information.
```

grains
```
...
    osfinger:
        Ubuntu-14.04
    osfullname:
        Ubuntu
    osrelease:
        14.04
    saltversion:
        2015.2.0-601-g7aa9819
```
