### ISSUE TITLE
dulwich powered gitfs_remotes act funky while being updated

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#21144]
I took a look at using dulwich as my gitfs provider and although initially things seemed to work I ran into a major problem I can consistently reproduce.  My states are backed by a single repo. In the moments after push changes to simple state which is just a single file.recurse block and a directory with a dozen files and with this I can consistently get salt to fail. Running salt-call repeatedly ('state.sls whatever') on a minion I see the following behavior:

0-10 secs: old state applies cleanly with no error (time varies, my loop_interval is 15)
10-30 secs: 
```
local:
    Data failed to compile:
----------
    No matching sls found for 'whatever' in env 'base'
```
30-45 secs:
```
local:
----------
          ID: /srv/whatever
    Function: file.recurse
      Result: False
     Comment: Recurse failed: none of the specified sources were found
     Started: 22:16:37.744695
    Duration: 151.943 ms
     Changes:   
```
And then at some point it actually picks up the change and that state runs fine again.  I do not see the same behavior with "gitfs_provider: gitpython" My git repo is on bitbucket and I'm connecting with a git+ssh://git@bitbucket.org/acct/repo.git url.

My dulwich version is 0.9.4 which (current version in Ubuntu 14.04 package 'python-dulwich'). So perhaps the minimum version of Dulwich specified in the docs needs to be higher than 0.9.4 from in #19875.  Honestly I didn't try 0.9.8 from pip, nor any intermediary release to see whether this issue went away, I just dropped Dulwich altogether.
