### ISSUE TITLE
jinja templates included using imports dont know their path.

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#21198]
sls
```
{%- from slspath + '/woot/vars.jinja' import vars %}
parent:
    sls: {{ sls }}
    slspath: {{ slspath }}
    
parent.woot: {{ vars }}
```

/woot/vars.jinja
```
{% set vars = { 'slspath': slspath, 'sls': sls } %}
```

salt cloud\* pillar.items
```
    parent:
        ----------
        sls:
            mfcf.cloud.test
        slspath:
            mfcf/cloud/test
    parent.woot:
        ----------
        sls:
            u'mfcf.cloud.test'
        slspath:
            u'mfcf/cloud/test'
```

allowing included files to know there 'sls' path can remove static defines of the paths.
