### ISSUE TITLE
User field in wtmp beacon has extraneous binary data

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#21203]
OS:  Ubuntu 14.04

Very new version of 2015.2 branch

```
root@boucha:~# salt boucha test.versions_report
boucha:
               Salt: 2015.2.0rc1-600-g35739ab
             Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
             Jinja2: 2.7.2
           M2Crypto: 0.22
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: 1.4.0
             PyYAML: 3.11
              ioflo: 1.1.4
              PyZMQ: 14.3.1
               RAET: 0.4.3
                ZMQ: 4.0.4
               Mako: Not Installed
```

This is the event I'm seeing when I log into this server which is running the wtmp beacon:

```
Event fired at Sun Mar  1 00:43:33 2015
*************************
Tag: salt/beacon/boucha/wtmp/
Data:
{'_stamp': '2015-03-01T00:43:33.391612',
 'data': {'PID': 7,
          'addr': 1425170612,
          'exit_status': 0,
          'hostname': '<ip address>',
          'id': 'boucha',
          'inittab': '',
          'line': '\x1ab\x00\x00pts/3',
          'session': 0,
          'time': 0,
          'type': 0,
          'user': 'ts/3davetest'},
 'tag': 'salt/beacon/boucha/wtmp/'}
```

The user I logged in with is just `davetest`.  Notice the extra data in there?

@thatch45 is there any other information you'd need to troubleshoot this?
