### ISSUE TITLE
Maybe a bug for jinja render?

### ISSUE THREAD

**Issue by Colstuwjx** [saltstack/salt#21217]
Hi, I met a issue about jinja render problem, just like:

```
# sls content
{% set pool_name = pillar.get('pool') %}

zabbix-agentd_service:
    service.running:
      - name: {{ salt['cmd.run']('ls /etc/init.d/zabbix*agent* |cut -d"/" -f4') }}

#{% set pool_name = "test" %}
serverinfo:
  file.managed:
    - source: salt://basic/{{ pillar['pool'] }}_and_{{ pool_name }}/file/1.sh
    - mkdirs: True
    - name: /opt/1.sh
    - user: root
    - group: root
    - mode: 755
    - watch_in:
      - service: zabbix-agentd_service

```

You see, I just add '#' to the set block, but it still rendered, and finally it throw:

```Comment:   Source file salt://basic/Zabbix_and_test/file/1.sh not found```

Pillar pool definitely is Zabbix, but jinja rendered it as test....
Thanks.
