### ISSUE TITLE
State 'X' found in SLS 'Y' is unavailable

### ISSUE THREAD

**Issue by Dudesons** [saltstack/salt#21221]
Hello,

I'm new salt user, I encounter a problem when I tried to manage files with jinja template, and pillar data management.
The saltstack run indicate me for example : 
> State '/etc/apache2/sites-available/toto.com' found in SLS 'apache.post-conf' is unavailable

I don't understand my error ... If anyone can point me to my mistake or help me find it, I thank in advance.
Below sls states, pillar file & versions-report.

Best regards,
Damien

> vhost sls file
```
apache-vhosts:
{% if pillar["apache"]["vhosts"]["ensure"] == "present" %}
  {% for vhost, args in pillar["apache"]["vhosts"]["conf"].iteritems() %}
  /etc/apache2/sites-available/{{ vhost }}.conf:
    - file.managed:
      - source: salt://apache/templates/vhost.conf.jinja
      - template: jinja
      - user: root
      - group: root
      - mode: 644
      - context:
        - name: {{ args["name"] }}
        - port: {{ args["port"] }}
  {% endfor %}
{% endif %}
```

> pillar sls file
```
apache:
  ensure: present
  {% if grains['os'] == 'Ubuntu' %}
  pkg.name: apache2
  {% endif %}
  vhosts:
    ensure: present
    conf:
      tutu.com:
        name: tutu.com
        port: 80
      toto.com:
        name: toto.com
        port: 80
```

> salt --versions-report
```
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 0.9.1
```
