### ISSUE TITLE
svn pillar: "Working copy locked" error when running across multiple minions

### ISSUE THREAD

**Issue by jvestrum** [saltstack/salt#21225]
I'm using the SVN backend for my states and recently started using the SVN ext_pillar. However, when I try to run a state that uses Pillar data across my 50 nodes, it usually fails with "Salt request timed out. If this error persists, worker_threads may need to be increased". The master log shows that the master is trying to update the same working copy over and over and getting:

> 2015-03-02 09:58:29,639 [salt.loaded.int.pillar.svn_pillar          ][ERROR   ] Unable to fetch the latest changes from remote svn://salt-master/srv/svn/repo/pillar: Working copy '/var/cache/salt/master/pillar_svnfs/91a11d07803eb18b019b92fc79954774' locked
> 2015-03-02 09:58:29,613 [salt.loaded.int.pillar.svn_pillar          ][ERROR   ] Unable to fetch the latest changes from remote svn://salt-master/srv/svn/repo/pillar: Working copy '/var/cache/salt/master/pillar_svnfs/91a11d07803eb18b019b92fc79954774' locked
> 2015-03-02 09:58:29,719 [salt.loaded.int.pillar.svn_pillar          ][ERROR   ] Unable to fetch the latest changes from remote svn://salt-master/srv/svn/repo/pillar: Working copy '/var/cache/salt/master/pillar_svnfs/91a11d07803eb18b019b92fc79954774' locked
> 2015-03-02 09:58:29,861 [salt.loaded.int.pillar.svn_pillar          ][ERROR   ] Unable to fetch the latest changes from remote svn://salt-master/srv/svn/repo/pillar: Working copy '/var/cache/salt/master/pillar_svnfs/91a11d07803eb18b019b92fc79954774' locked
> ...etc etc, until:
> 2015-03-02 09:58:40,987 [salt.client      ][ERROR   ] Salt request timed out. If this error persists, worker_threads may need to be increased.

I gradually increased the worker_threads and found that the state.sls timeouts went away once worker_threads >= minions. But the "working copy locked" errors continue (and having a worker thread for each minion doesn't scale).

``` yaml
Versions:
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```
