### ISSUE TITLE
Pass bulk entries in git.config state

### ISSUE THREAD

**Issue by aspyatkin** [saltstack/salt#21250]
Hello, SaltStack team!
I would like to propose a small enhancement for `git.config` state module, to pass bulk `name=value` pairs to one `git.config` state. For example:

``` yaml
setup_git_config:
    git.config:
        - require:
           - pkg: git
        - entries:
            - core.autocrlf: input
            - user.name: "John Smith"
            - user.email: john@smith.com
            - push.default: simple
        - is_global: True
```

How do you think about it? The same effect can be possibly achieved using `for` with Jinja template, but I think this would be a clearer approach.
