### ISSUE TITLE
Suppress warnings in case of "busy device" for unmounting

### ISSUE THREAD

**Issue by holtgrewe** [saltstack/salt#21276]
I have NFS shares that are managed by salt. On `highstate`, I get red error messages since salt appears to want to remount the NFS share. Can I somehow suppress remounting in case everything is OK or suppress the error message? I'm fine with the share not being unmountable.

Here is my error message:

```
          ID: /media/<UUID>
    Function: mount.mounted
      Result: False
     Comment: Unable to unmount /media/<UUID>: umount.nfs4: /media/<UUID>: device is busy
              umount.nfs4: /media/<UUID>: device is busy.
     Changes:   
```

I'm using the following salt YAML:

```
/media/<UUID>:
  mount.mounted:
    - device: <HOST>:<UUID>
    - fstype: nfs
    - opts: noauto
    - mkmnt: True

```

I'm sorry if this is a duplicate of another issue, but the other issues that I found were bugs while this is more of a feature request.
