### ISSUE TITLE
Include line numbers in jinja/yaml error messages

### ISSUE THREAD

**Issue by viraptor** [saltstack/salt#21298]
Currently (in 2014.7.0), if there's some parameter missing when rendering a template, I get a not very helpful message, like:

```
          ID: /file/path
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'dict object' has no attribute 'user'
     Started: 11:47:12.728811
    Duration: 37.236 ms
     Changes:   
```

It would be great if the line number from the template was also included, if jinja itself gives this information. Otherwise it can be quite hard to find where the issue occurred.
