### ISSUE TITLE
Possible minion enumeration using saltutil.find_job and eauth

### ISSUE THREAD

**Issue by Lothiraldan** [saltstack/salt#21296]
When using eauth, for example with this configuration:
```yaml
external_auth:
  pam:
    vagrant:
    - .*
    - '@runner'
    - '@wheel'
    user_local:
      - '*devl*':
        - test.ping
```

With only one minion local.local, it means that the user_local has no right on the only minion registered:

```
sudo salt -a pam -v -C 'local.local' test.pingusername: user_local
password:
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```

When using eauth with user_local, I'm able to list all minions using this command ```salt -a pam -v -C '*' saltutil.find_job test.ping``` with this output:

```
Executing job with jid 20150304111630664392
-------------------------------------------

local.local:
    ----------
```

By looking at the code, this exception for saltutil.find_job is explicit https://github.com/saltstack/salt/blob/develop/salt/master.py#L2249-L2252 but it means that if someone has access to a token or username/password, he will be able to list all minions registered to the salt master. It may be an issue for some people.
