### ISSUE TITLE
pillar_source_merging_strategy not working?

### ISSUE THREAD

**Issue by schlagify** [saltstack/salt#21313]
Hi,

I have my master configured to use `pillar_source_merging_strategy:  recurse`, however it seems to be behaving as though it is set to `overwrite`.  

/var/salt/pillar/top.sls:

``` yaml
  '^web.*':         {# webs - prod #}
    - match:  pcre
    - environments.prod.web.django.website.testing
```

environments.prod.web.django.website.testing:

``` yaml
include:
  - environments.prod.web.django.common.testing
  - environments.all.web.django.testing

web_stack_pillar:
  packages:
    installed:
      - nginx-extras
```

environments.prod.web.django.common.testing:

``` yaml
web_stack_pillar:
  packages:
    installed:
      - waka-waka
```

environments.all.web.django.testing:

``` yaml
web_stack_pillar:
  packages:
    installed:
      - build-essential
      - curl
```

I am expecting the output of `salt-call pillar.get web_stack_pillar` to result in something like this:

``` yaml
local:
    ----------
    packages:
        ----------
        installed:
            - build-essential
            - curl
            - waka-waka
            - nginx-extras
```

Instead, it is resulting in this:

``` yaml
local:
    ----------
    packages:
        ----------
        installed:
            - build-essential
            - curl
```

This seems to be the `overwrite` behavior, whereby the values in `environments.all.web.django.testing` overwrite everything else.  I have refreshed pillar, deleted /var/cache/salt to no avail.  

``` yaml
salt-master --versions-report
           Salt: 2014.7.1
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.7.0
```

``` yaml
salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.7.0
```
