### ISSUE TITLE
get_full_returns raises KeyError

### ISSUE THREAD

**Issue by thanatos** [saltstack/salt#21318]
I'm seeing the following:

```
In [1]: from salt import client

In [2]: c = client.LocalClient()

In [3]: c.cmd_async('*', 'test.ping')
Out[3]: '20150304200422089836'

In [4]: c.get_full_returns(_3, '*')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-fda1101b82e1> in <module>()
----> 1 c.get_full_returns(_3, '*')

/home/salt/env/local/lib/python2.7/dist-packages/salt/client/__init__.pyc in get_full_returns(self, jid, minions, timeout)
   1061
   1062         # otherwise lets use the listener we created above to get the rest
-> 1063         for event_ret in event_iter:
   1064             # if nothing in the event_ret, skip
   1065             if event_ret == {}:

/home/salt/env/local/lib/python2.7/dist-packages/salt/client/__init__.pyc in get_event_iter_returns(self, jid, minions, timeout)
   1250             if 'minions' in raw.get('data', {}):
   1251                 continue
-> 1252             found.add(raw['id'])
   1253             ret = {raw['id']: {'ret': raw['return']}}
   1254             if 'out' in raw:

KeyError: 'id'
```

```
In [8]: list(salt.version.versions_report())
Out[8]:
['           Salt: 2014.7.0-2-ge512b6d',
 '         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)',
 '         Jinja2: 2.7.2',
 '       M2Crypto: 0.22',
 ' msgpack-python: 0.4.2',
 '   msgpack-pure: Not Installed',
 '       pycrypto: 2.6.1',
 '        libnacl: Not Installed',
 '         PyYAML: 3.11',
 '          ioflo: Not Installed',
 '          PyZMQ: 14.4.1',
 '           RAET: Not Installed',
 '            ZMQ: 4.0.5',
 '           Mako: Not Installed']
```

**Comment by jfindlay** [comment]
@thanatos, thanks for the report.  Here's my confirmation:
```yaml
centos-7-main ~ master # salt --versions
           Salt: 2014.7.2-274-g7a77375
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```
```python
centos-7-main ~ master # python
Python 2.7.5 (default, Jun 17 2014, 18:11:42)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from salt import client
>>> c = client.LocalClient()
>>> c.cmd_async('centos-7-main', 'test.ping')
'20150309125045311684'
>>> c.get_full_returns('20150309125045311684', '*')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/salt/salt/client/__init__.py", line 1063, in get_full_returns
    for event_ret in event_iter:
  File "/root/salt/salt/client/__init__.py", line 1252, in get_event_iter_returns
    found.add(raw['id'])
KeyError: 'id'
>>>
```
