### ISSUE TITLE
2015.2 git shows change in test mode.

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#21333]
sls
```
{{ sls }} oat_sync_photos_git_files:
    git.latest:
        - name: gitlab@git.xxxx.ca:oat/oat_photo_sync.git
        - rev: master
        - target: /srv/oat_photo_sync
        - user: cs-oat
```

salt oat-feed\*-dev.salt\* state.highstate test=true
```
----------
          ID: mfcf.service.oat2.feed.photo_sync oat_sync_photos_git_files
    Function: git.latest
        Name: gitlab@git.xxxxxx.ca:oat/oat_photo_sync.git
      Result: None
     Comment: Repository /srv/oat_photo_sync update is probably required (current revision is 17a9759d9721381fdce9c1b69b4c09a54cac501e)
     Started: 02:16:48.581846
    Duration: 738.275 ms
     Changes:   
              ----------
              new:
                  None
              old:
                  17a9759d9721381fdce9c1b69b4c09a54cac501e
```
should be no change.
