### ISSUE TITLE
file.replace does not allow itself to be watched?

### ISSUE THREAD

**Issue by jhgg** [saltstack/salt#21336]
Noticing this issue where the service wouldn't restart when the file was changed by file.replace. 

Didn't see anything in documentation about this not working - can someone clarify? 

SLS file below:

```yaml
nginx:
  pkg:
    - installed

  service:
    - running
    - enable: True
    - reload: True

/etc/nginx/nginx.conf:
  file:
    - replace
    - pattern: '#? server_names_hash_bucket_size (\d+);'
    - repl: 'server_names_hash_bucket_size 128;'
    - watch_in:
      - service: nginx

```

Putting the `watch:` in `nginx.service` gives same error. 

Error On Salt Master:

```
          ID: listener_nginx
    Function: service.mod_watch
        Name: nginx
      Result: False
     Comment: The following requisites were not found:
                                 watch:
                                     file: /etc/nginx/nginx.conf
     Started:
    Duration:
     Changes:
```

Master/Minion version: salt 2014.7.0 (Helium)
Master/Minion OS:
```
#uname -a
Linux 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
#cat /etc/issue
Ubuntu 14.04.1 LTS \n \l
```
