### ISSUE TITLE
pkgrepo.managed not applying changes

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#21369]
We had the following state:

``` yaml
example_apt_repo:
  pkgrepo.managed:
    - humanname: Example Main Repo
    - name: deb http://apt.example.com/{{grains['os'] | lower}} {{grains['oscodename']}} main
    - dist: {{ grains['oscodename'] }}
    - file: /etc/apt/sources.list.d/example.list
```

This was changed to:

``` yaml
example_apt_repo:
  pkgrepo.managed:
    - humanname: Example Main Repo
    - name: deb [arch=amd64] http://apt.example.com/{{grains['os'] | lower}} {{grains['oscodename']}} main
    - dist: {{ grains['oscodename'] }}
    - file: /etc/apt/sources.list.d/example.list
    - clean_file: True
```

However, executing highstate does not result in the file being modified with the new `[arch=amd64]` entry. If I remove `sources.list.d/example.list` and highstate the minion again, it is added in properly.

Data from the minion debug doesn't help much either:

```
[INFO    ] Executing state pkgrepo.managed for deb [arch=amd64] http://apt.example.com/ubuntu trusty main
[INFO    ] Executing command 'apt-get -q update' in directory '/home/vagrant'
[INFO    ] Configured package repo 'deb [arch=amd64] http://apt.example.com/ubuntu trusty main'
[INFO    ] Completed state [deb [arch=amd64] http://apt.example.com/ubuntu trusty main] at time 06:58:08.159625
```

Version specs:

``` yaml
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
