### ISSUE TITLE
Function file.managed is run everytime on user = number

### ISSUE THREAD

**Issue by roflmao** [saltstack/salt#21423]
When putting number into user in function file.managed, the correct UID is set, but the function is ran on every run:

State of the file before run:
```
-rw------- 1 fcgi root 51K Mar  9 13:44 /var/log/fotball.log
```
 
```
          ID: xxx_logfile_exists
    Function: file.managed
        Name: /var/log/fotball.log
      Result: True
     Comment: 
     Started: 13:44:56.690171
    Duration: 0.988 ms
     Changes:   
              ----------
              user:
                  fcgi
```

sls:
```
xxx_logfile_exists:
  file.managed:
    - name: {{ pillar['xxx']['l4p_filename'] }}
    - replace: false
    {% if pillar['fcgimanager']['uid'] is defined %}
    - user: {{ salt['pillar.get']('fcgimanager:uid', 'root') }}
    {% endif %}
    - mode: 600
{% endif %}
```

```

# salt-minion --versions-report
           Salt: 2014.7.1
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
```
