### ISSUE TITLE
iptables not properly handling multiple matches

### ISSUE THREAD

**Issue by Grejeru** [saltstack/salt#21425]
Hi,

I'm trying to add rule to pass port 5666 with source configured using this:

```
iptables_in_nrpe:
  iptables.append:
    - table: filter
    - chain: INPUT
    - jump: ACCEPT
    - match: state
    - connstate: NEW
    - source: '192.168.168.4/32'
    - dport: 5666
    - proto: tcp
    - save: True
```

but when I'm running highstake I'm getting error:

```
    State: - iptables
    Name:      iptables_in_nrpe
    Function:  append
        Result:    False
        Comment:   Failed to set iptables rule for iptables_in_nrpe
        Changes:
```

It is trying to run

```
[INFO    ] Executing command 'iptables -t filter -A INPUT -m state --dport 5666 --proto tcp --jump ACCEPT --source 192.168.168.4/32 --state NEW ' in directory '/home/vagrant'
```

which is incorrect format, as --dport + --source requires -m tcp
When I've tried to add second match by changing

```
- match: state
```

to

```
-match:
  - state
  - tcp
```

it was trying to pass iptables command:

```
[INFO    ] Executing command "iptables -t filter -A INPUT -m ['state', 'tcp'] --dport 5666 --proto tcp --jump ACCEPT --source 192.168.168.4/32 --state NEW " in directory '/home/vagrant'
```

which is incorrect too.

My salt-minion version:

```
vagrant@wap01:~$ salt-minion --versions-report
           Salt: 0.17.5
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
vagrant@wap01:~$
```

Currently I'm using dirty hack/workaround by setting:

```
- match: state -m tcp
```

but I think it should be corrected.
