### ISSUE TITLE
check for systemd on Oracle Linux

### ISSUE THREAD

**Issue by dpheasant** [saltstack/salt#21446]
Salt is not detecting this as a systemd machine. The start/stop functions work since they're based on the `service` command, however the status (enabled, disabled, running) functions do not.

Output from a salt run:
````yaml
----------
          ID: redis_isRunning
    Function: service.running
        Name: redis
      Result: False
     Comment: The named service redis is not available
     Started: 15:17:26.346919
    Duration: 6.071 ms
     Changes:
----------
````

State definition:
````yaml
redis_isRunning:
  service.running:
    - name  : redis
    - sig   : redis-server
    - enable: true
    - watch :
      - pkg: redis
````

From the minion logs:
````
[salt.loaded.int.module.cmdmod][INFO    ] Executing command '/sbin/chkconfig --list redis' in directory '/root'
2015-03-09 15:17:26,353 [salt.state       ][ERROR   ] The named service redis is not available
````
 Output of grains.items for the OS:
````yaml
    os:
        OEL
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:

    osfinger:
        Oracle Linux Server-7
    osfullname:
        Oracle Linux Server
    osmajorrelease:
        7
    osrelease:
        7.0
    osrelease_info:
        - 7
        - 0
````
