### ISSUE TITLE
salt-run jobs.list_jobs data incomplete

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#21496]
In the latest 2014.7 branch some of the data is not making it into the job cache:

I'm seeing this on Ubuntu Precise 12.04

```yaml
vagrant@saltmaster:~$ sudo salt-run jobs.list_jobs
20150310162647657398:
    ----------
    Arguments:
    Function:
        test.ping
    StartTime:
        2015, Mar 10 16:26:47.657398
    Target:
        unknown-target
    Target-type:
    User:
        root
20150310162652669514:
    ----------
    Arguments:
    Function:
        saltutil.find_job
    StartTime:
        2015, Mar 10 16:26:52.669514
    Target:
        unknown-target
    Target-type:
    User:
        root
20150310162837107945:
    ----------
    Arguments:
    Function:
        test.versions_report
    StartTime:
        2015, Mar 10 16:28:37.107945
    Target:
        unknown-target
    Target-type:
    User:
        root
```

Versions report:
```yaml
minion1:
               Salt: 2014.7.2-282-gf6f6afe
             Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
             Jinja2: 2.6
           M2Crypto: 0.21.1
     msgpack-python: 0.1.10
       msgpack-pure: Not Installed
           pycrypto: 2.4.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 13.0.0
               RAET: Not Installed
                ZMQ: 3.2.2
               Mako: Not Installed
```
master versions_report:
```yaml
vagrant@saltmaster:~$ sudo salt-master --versions-report
           Salt: 2014.7.2-282-gf6f6afe
         Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.0.0
           RAET: Not Installed
            ZMQ: 3.2.2
           Mako: Not Installed
```
