### ISSUE TITLE
Syndic not passing up lower level jobs to the higher master's job cache

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#21495]
Latest 2014.7 branch:
```
test.versions_report

minion1:
               Salt: 2014.7.2-282-gf6f6afe
             Python: 2.7.3 (default, Feb 27 2014, 19:58:35)
             Jinja2: 2.6
           M2Crypto: 0.21.1
     msgpack-python: 0.1.10
       msgpack-pure: Not Installed
           pycrypto: 2.4.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 13.0.0
               RAET: Not Installed
                ZMQ: 3.2.2
               Mako: Not Installed
```
higher_master --> lower_master|syndic|minion --> minion

Jobs run on `lower_master` show up in it's own job cache, but the jobs do not show up in the `higher_master's` job cache.
