### ISSUE TITLE
Check for firewalld on Oracle Linux

### ISSUE THREAD

**Issue by dpheasant** [saltstack/salt#21503]
Salt is not detecting this as a firewalld machine. The firewalld functions do not work.
````
salt 'server01' firewalld.version
server01.fqdn:
    'firewalld.version' is not available.
````

 Output of grains.items for the OS:
````yaml
    os:
        OEL
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:

    osfinger:
        Oracle Linux Server-7
    osfullname:
        Oracle Linux Server
    osmajorrelease:
        7
    osrelease:
        7.0
    osrelease_info:
        - 7
        - 0
````
