### ISSUE TITLE
state change detection for blockdev.tune broken 2014.7.x /develop

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#21546]
Hi,

the state change detection is broken for blockdev.tune on 2014.7 & develop.

Having a state like that,
```yaml
/dev/my_vg/lvroot:
  blockdev.tuned:
   - read-only: True
   - read-ahead: 1024
```

always reports a change, even if there was no change at all...

```yaml
          ID: /dev/my_vg/lvroot
    Function: blockdev.tuned
      Result: True
     Comment: Block device /dev/my_vg/lvroot successfully modified
     Started: 17:36:18.405372
    Duration: 10.731 ms
     Changes:   
              ----------
              getra:
                  1024
              getro:
                  1
```

a fix will follow
