### ISSUE TITLE
docker.latest_running wrongfully assumes there have been configuration changes and will restart the container

### ISSUE THREAD

**Issue by jasonm-makerbot** [saltstack/salt#21580]
salt version 2015.2 built at commit 6ed603c3a48840384063f9863519cd696a8cf308 (Wed Mar 11 17:48:41 2015 -0600)

```yaml
salt --versions-report
           Salt: 2015.2.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.0
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

Every time the state is run, the docker container is restarted.

```yaml
          ID: some_id
    Function: docker.latest_running
        Name: dockerhub_image
      Result: True
     Comment: The container was current, but its configuration changed. It was restarted.
     Started: 01:55:22.666253
    Duration: 15201.804 ms
     Changes:
              ----------
              configuration:
                  ----------
                  Binds:
                      ----------
                      new:
                          None
                      old:
```
