### ISSUE TITLE
file.managed for HTTP source doesn't use the HTTP status code

### ISSUE THREAD

**Issue by SaltwaterC** [saltstack/salt#21625]
If the returned status code is for example 403, then the response body of the error is compared against source_hash and the state fails with a wrong hash error. Yep, I had "fun" debugging that until I realised that the URL is wrong, many hours after checking all the bits and pieces.

I'd say that 4xx and 5xx status codes should be treated as errors and the state output should properly display that instead of reading an useless response body and throwing a bad hash error which doesn't explain the nature of the failure.

```bash
salt --versions-report
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
cat /etc/issue
Ubuntu 14.04.2 LTS \n \l
uname -a
Linux saltmaster01 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rallytime** [comment]
Thanks @SaltwaterC - we should definitely make that response more helpful. Do you have some state output that shows the hash error?

**Comment by SaltwaterC** [comment]
@rallytime I'll give you an example:

```yaml
/path/to/file:
  file.managed:
    - source: https://s3.amazonaws.com/bucket/path/to/file
    - source_hash: https://s3.amazonaws.com/bucket/path/to/sha256
    - user: root
    - group: root
    - mode: 755
```

**Comment by aneeshusa** [comment]
The two PRs should cover 2014.7, 2015.2 and develop, so that should be enough to close this Issue.

**Comment by rallytime** [comment]
Awesome! Thanks very much @aneeshusa.

@SaltwaterC Give one of those pull requests a try and let us know if that resolves the issue for you.

**Comment by aneeshusa** [comment]
FYI @SaltwaterC , the fix for 2014.7 is the first one (#21677).

**Comment by SaltwaterC** [comment]
@rallytime thanks, the patch solves the issue. The fail output actually tells the story now:

```
          ID: /path/to/file
    Function: file.managed
      Result: False
     Comment: Unable to manage file: 403 Client Error: Forbidden
     Started: 19:08:19.236903
    Duration: 52.42 ms
     Changes:
```

@aneeshusa thank you.
