### ISSUE TITLE
Salt-ssh with sudo NOPASSWD required. 

### ISSUE THREAD

**Issue by hari316** [saltstack/salt#21719]
Is it possible to ping remote server, without sudo configuration of the salt-minion machine  'sudo visudo' ??

 /etc/salt/roster:
```
test-ubuntu-minion01:
  host: 127.0.0.1
  user: abc
  passwd: ****
  sudo: True
```
Command:
`sudo salt-ssh -i 'test-ubuntu-minion01' state.sls test.ping`

```
   stderr:
        sudo: no tty present and no askpass program specified
        Sorry, try again.
        sudo: no tty present and no askpass program specified
        Sorry, try again.
        sudo: no tty present and no askpass program specified
        Sorry, try again.
        sudo: 3 incorrect password attempts

    stdout:
        ERROR: sudo expected a password, NOPASSWD required
```
