### ISSUE TITLE
file.manage_file: The following arguments are missing: saltenv?

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt#21758]
salt-call --versions-report

```
           Salt: 2014.1.10
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.11
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
```

The state file:

```
xinetd_fail2ban_test:
  module:
    - run
    - name: file.manage_file
    - m_name: '/etc/fail2ban/jail.d/xinetd.conf'
    - sfn: ''
    - ret: '{}'
    - source: None
    - source_sum: '{}'
    - user: 'root'
    - group: 'root'
    - mode: 440
    - saltenv: 'base'
    - backup: False
    - contents: |
        enabled = true
        port = all
```

and the error:

```
local:
----------
          ID: xinetd_fail2ban_test
    Function: module.run
        Name: file.manage_file
      Result: False
     Comment: The following arguments are missing: saltenv
     Changes:
```

**Comment by rallytime** [comment]
@quantonganh Thanks for this report. Is there any particular reason you're using the `module.run` state with `file.manage_file` instead of the `file.managed` state? The `file.manage_file` module function isn't really designed to be as user-friendly as the `file.managed` state as it mostly serves as a helper function for the state version. 

The state version (file.managed) does not require an `env` or the `saltenv` argument, so your best bet here is to just switch that over.

Also, as an "FYI" 2014.1.10 is an old release and that branch isn't being maintained anymore. We've made numerous fixes on the 2014.7 branch and onwards. I would suggest upgrading to our latest release, 2014.7.2, if you run into other problems.

**Comment by quantonganh** [comment]
> Is there any particular reason you're using the module.run state with file.manage_file instead of the file.managed state?

No, I just tried it to debug something else.

> I would suggest upgrading to our latest release, 2014.7.2

On my local workstation:

```
           Salt: 2015.2.0-85-g9fadb0b
         Python: 2.7.6 (default, Sep  9 2014, 15:04:36)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

still got the same result:

```
local:
----------
          ID: xinetd_fail2ban_test
    Function: module.run
        Name: file.manage_file
      Result: False
     Comment: The following arguments are missing: saltenv
     Started: 09:04:33.136857
    Duration: 3.403 ms
     Changes:
```
