### ISSUE TITLE
Getting state in sls is not formed as a list

### ISSUE THREAD

**Issue by leftyhitchens** [saltstack/salt#21802]
```
kibana:
  /var/www/kibana:
    file.directory:
      - user: www-data
      - group: www-data
      - mode: 755
      - makedirs: True
  archive.extracted:
    - name: {{ salt['pillar.get']('kibana.kibana_wwwroot') }}
    - source_hash: sha1=1b8914c62a606b7103295a4e3ab01ec40c9993ed
    - source: http://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz
    - archive_format: tar
    - tar_options: vxf
```

This is my state file, when I run:

```
state.sls kibana
```
I get the following error:

```
state in sls 'kibana' is not formed as a list
```
 I am on version: 2014.7.0 (helium) 

What am I missing?

**Comment by rallytime** [comment]
@leftyhitchens Give this a try:
```
kibana:
  file.directory:
    - name:   /var/www/kibana
    - user: www-data
    - group: www-data
    - mode: 755
    - makedirs: True
  archive.extracted:
    - name: {{ salt['pillar.get']('kibana.kibana_wwwroot') }}
    - source_hash: sha1=1b8914c62a606b7103295a4e3ab01ec40c9993ed
    - source: http://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz
    - archive_format: tar
    - tar_options: vxf
```

The reason being that your `/var/www/kibana` line, the way you have it, isn't formed as a list like the `archive.extracted` state is. If you move `/var/www/kibana` to the `name` argument, it adds the `file.directory` as the state to run and moves everything back in line to be a list. (`kibana` is the unique id of the entire state, while `archive.extracted` and `file.directory` are the functions to run.)
