### ISSUE TITLE
Performing a check based on runners in a reactor formula?

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt#21835]
We are playing with event and reactor to restart a service when its memory usage goes too high.

Everything at the Shinken side is done:
- when a service goes into HARD state
- fire an event with a specific tag, data that include minion id, ...

On the Salt master side, we have a reactor to run a sls file on that minion:

```
restart_shinken_receiver:
  {% if grains['saltversioninfo'] >= (2015, 2, 0, 0) %}local{% else %}cmd{% endif %}.state.sls:
    - tgt: {% raw %}{{ data['data']['minion_id'] }}{% endraw %}
    - arg:
      - shinken.receiver.reaction.{% raw %}{{ data['data']['service_desc'] }}{% endraw %}
```

The problem is we would like to check if that sls file exists in the Salt master file server first.
Is it possible to call a runner function to perform a check in a reactor formula? Something like this:

```
{% if 'shinken/receiver/reaction/' + data['data']['service_desc'] + '.sls' in salt-run['fileserver.file_list']() %}
```

Sure, it's just a pseudo-code as `salt-run` does not exist at this time.
