### ISSUE TITLE
applying a formula with git.latest states and test=True will rm an existing target path

### ISSUE THREAD

**Issue by ketzacoatl** [saltstack/salt#21864]
Apologies if this is a duplicate, I looked for an existing issue but could not find one specific to this problem.

I am running `Helium`:

```
# salt-call --version
salt-call 2014.7.2 (Helium)
```

I have a formula like:

```
salt-roots:
  git.latest:
    - name: {{ url }}
    - rev: {{ rev }}
    - target: /srv/salt
    - user: {{ user }}
    - force: True
    - force_checkout: True
    - identity: {{ ssh_key_path }}
```

**Note the use of `force`. Commenting this out returns properly, and exposes the bug is related to this conditional. Also note that the bug is seen with `force: True` and `force_checkout: False`, so it is not fully related to `force_checkout`.**

Applying this formula with: `salt-call --local state.sls salt.file_roots.single test=True` yields the following in the state output:

```
          ID: salt-roots
    Function: git.latest
      Result: None
     Comment: Repository salt-roots is about to be cloned to /srv/salt
     Started: 21:04:34.530065
    Duration: 5.38 ms
     Changes:   
```

..and the `/srv/salt/` path (and subdirectories) that were on the filesystem are now gone.

Funny enough, I have a similar formula which uses jinja to generate a `git.latest` state as seen above, but for a group of repos.. and applying that formula (with `test=True) does _not_ step on the git checkout target path:

```
          ID: roots-git-foobar-salt-formula
    Function: git.latest
        Name: git@github.com:foobar/foobar-salt-formula.git
      Result: None
     Comment: Repository /srv/salt/foobar-salt-formula update is probably required (current revision is deadbeef)
     Started: 21:05:29.414910
    Duration: 101.916 ms
     Changes:   
              ----------
              new:
                  None
              old:
                  deadbeef
```

..the path `/srv/salt/foobar-salt-formula` is still on the filesystem and populated.

I've received consistent results in my tests here, salt is definitely losing data on me (likely through mishandling of git).
