### ISSUE TITLE
`salt.states.mount` - using LABEL=foo as 'device' leads to constant remounts

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#21888]
Another item in the long list of `mount.mounted` issues:

**Salt:**
```
               Salt: 2014.7.2
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.4.4
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.4
               Mako: Not Installed
```
**OS:** CentOS 7

When using `LABEL=foo` as `device` param in `mount.mounted`, the device will be constantly remounted as the `LABEL` is translated to the actual blockdevice in `/proc/self/mounts`:
```
          ID: /media/storage
    Function: mount.mounted
      Result: True
     Comment: Target was successfully mounted. Entry already exists in the fstab.
     Started: 02:04:31.571776
    Duration: 1318.71 ms
     Changes:   
              ----------
              mount:
                  True
              umount:
                  Forced unmount because devices don't match. Wanted: LABEL=storage, current: /dev/md127, /dev/md127, 9ddf2e35-09e2-40b5-9acf-acdbe6563c53, storage
```
