### ISSUE TITLE
Change state from service.start ignored if enable is used

### ISSUE THREAD

**Issue by adyxax** [saltstack/salt#21928]
Salt doesn't report starting a service if the enable function is used. This behaviour happens on both Gentoo running salt  2014.7.2 or debian running salt 2014.1.13

The problem is triggered with this state :
```
sshd:
  service.running:
    {% if grains['os'] == 'Debian' %}
    - name: ssh
    {% endif %}
    - sig: /usr/sbin/sshd
    - enable: True
```

Running with salt-call on a server with sshd stopped properly start the service but fails to report it:
```
[INFO    ] Executing command '/etc/init.d/sshd start'
[...]
[INFO    ] Service sshd is already enabled, and is running
          ID: sshd
    Function: service.running
      Result: True
     Comment: Service sshd is already enabled, and is running
     Started: 23:22:52.715354
    Duration: 334.136 ms
     Changes:
```

Removing the enable function fixes that behaviour, which means that the changes from service.start are ignored if salt code branches into the enable function.

Big thanks to phx and BtbN on the irc channel for helping diagnose this issue.
