### ISSUE TITLE
composer.installed sould not run always

### ISSUE THREAD

**Issue by TriAnMan** [saltstack/salt#21929]
I've discovered the way composer.installed satate can be run only if there is something to do. Check out my handmade state for such purpose:

```
  cmd.run:
    - name: composer install --no-interaction
    - cwd: /path/to/project
    - unless: composer install --dry-run 2>&1 | grep "Nothing to install or update"
```
