### ISSUE TITLE
Cherry REST api IOError

### ISSUE THREAD

**Issue by soodr** [saltstack/salt#21982]
Had to restart the salt master and salt-api process to fix the error :

```
new-host-2: rsood$ curl -sSki https://saltmaster:9000/run -H "Accept: application/x-yaml" -d username=jenkins -d password=*** -d eauth='pam' -d client=wheel -d fun='key.list_all'
HTTP/1.1 200 OK
Content-Length: 315
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.2.3
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Wed, 25 Mar 2015 12:10:58 GMT
Access-Control-Allow-Origin: *
Content-Type: application/x-yaml

return:
- data:
    _stamp: '2015-03-25T12:10:58.776826'
    fun: wheel.key.list_all
    jid: '20150325121058584722'
    return: 'Exception occurred in wheel key.list_all: IOError: [Errno 5] Input/output error'
    tag: salt/wheel/20150325121058584722
    user: jenkins  tag: salt/wheel/20150325121058584722
```

REST configuration on master :

```
rest_cherrypy:
  port: 9000
  ssl_crt: /pyvenv/salt/salt-master-root/ssl/private/cert.pem
  ssl_key: /pyvenv/salt/salt-master-root/ssl/private/key.pem
 debug: True

external_auth:
  pam:
    jenkins:
      - .*
      - '@wheel'
      - '@runner'
```

(salt)-bash-4.1$ salt --versions-report

```
           Salt: 2015.2.0rc1
         Python: 2.7.8 (default, Sep 24 2014, 11:50:00)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.2
         PyYAML: 3.11
          ioflo: 1.2.1
          PyZMQ: 14.5.0
           RAET: 0.6.3
            ZMQ: 4.0.5
           Mako: 1.0.0
```
