### ISSUE TITLE
minion daemon fails to install packages when environment requires http proxy

### ISSUE THREAD

**Issue by yannis666** [saltstack/salt#21985]
My environment requires access via http proxy.
I use RHEL 6.4 and run salt-minion as a service.
When I try to use state.sls to install packages, I get failures ("Error Downloading Packages" in log)

I have tried setting htt_proxy, https_proxy in ~root/.profile and also in /etc/environment (and re-starting the minion service) but that does not work.

I found prior issues on this:
https://github.com/saltstack/salt/pull/5937
https://github.com/saltstack/salt/issues/13786
but no indication of what the final resolution is, if any.

**Comment by yannis666** [comment]
I found a solution that worked. Added proxy to /etc/yum.conf
Maybe this needs to be added to salt-minion configuration?

**Comment by tjstansell** [comment]
You can also add it to a `pkgrepo.managed` entry if you want it to only apply to that repo.  For instance:

```
yum.repos.test:
  pkgrepo.managed:
    - proxy: https://{{ proxy_host }}:{{ proxy_port }}/
    - baseurl: https://{{ my_repo_url }}/
    - gpgcheck: 0
    - enabled: 1
```
