### ISSUE TITLE
Cant able to unzip a folder on a minion(windows) from a master(RHEL)

### ISSUE THREAD

**Issue by NancyPaul** [saltstack/salt#21980]
Hi Team,

I am trying to unzip a folder/package from a master which runs on a RHEL to a minion which is of windows using the following code:
```
copy_unzipper:
 archive.unzip:
  - name: C:/newFold/nppcopy/
  - source: salt://win/repo/pingfederate/pingfederate-7.2.1.zip
  -  if_missing: C:/Highroads/pingfederate-7.2.1/ReadMeFirst.pdf
```
But i am not able to run it and get the following error:
```
[saltadmin@bossaltsyn ~]$ salt 'minion1' state.sls pingfederate
minion1:
----------
          ID: copy_unzipper
    Function: archive.unzip
        Name: C:/newFold/nppcopy/
      Result: False
     Comment: State 'archive.unzip' found in SLS 'pingfederate' is unavailable
     Started:
    Duration:
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```
and as well when i try to unzip on a particular minion i get the following :
```
salt 'minion1' archive.unzip template=jinja /repo/pingfederate/pingfederate.7.2.1.zip /newFold/nppcopy/
minion1:
    'archive.unzip' is not available.
```
Can anyone please advise me what do? cause i am really really new to salt

Thanks

**Comment by rallytime** [comment]
Thanks for the question @NancyPaul! I think you're running into #12992 which looks like the `archive.unzip` functionality hasn't been implemented yet.

If you scroll down to the near-bottom of that issue, there is a handy work-around state that can be used in the mean time.

Since this is a duplicate and we like to track issues that were filed earlier, I am going to close this one. Thanks!

**Comment by NancyPaul** [comment]
Hi Rally,

I have a doubt please help me to solve this.

I have ping federate its normally a zipped folder. We will be extracting and run 'run.bat' to work with it. We don't have any 'exe' file for it. If i want to run my ping federate as a service in remote system what should i do???

I don't have an idea about this can you please help me???

**Comment by basepi** [comment]
Hey @NancyPaul. Below are some workaround instructions from that other issue:

> Here is another simple alternative to extract an zip file with salt under windows.

> Put the unzip.exe from http://stahlworks.com/dev/unzip.exe in the storage folder on your master. (You can put the unzip.exe also in a different directory. It is only an example)

```
# Copy unzipper to remote location (C:/tmp/Tools/unzip.exe)
copy_unzipper:
  file.managed:
    - name: C:/tmp/Tools/unzip.exe
    - source: salt://storage/unzip.exe
    - makedirs: True

# Extract the installer.zip only if C:/tmp/build/testfolder/testfile.txt not exist.
extract_archive:
  cmd.run:
    - name: C:/tmp/Tools/unzip.exe -o C:/tmp/installer.zip -d C:/tmp/build/
    - unless: IF NOT EXIST C:/tmp/build/testfolder/testfile.txt EXIT 1
```

Note that you retrieve the exe file from the link above. You can stick it on your master at `/srv/salt/storage/unzip.exe` and then use the state above to push it to your windows minion, and then run it on your zipped folder. Make sure you change `C:/tmp/installer.zip` to your .zip file, and `C:/tmp/build/` to the directory to which you want to unzip it.
