### ISSUE TITLE
mount.mounted of tmpfs bind error

### ISSUE THREAD

**Issue by tlemarchand** [saltstack/salt#21992]
I have this state :

```
/mnt/test/var/run/nscd:
  mount.mounted:
    - device: /var/run/nscd
    - fstype: none
    - opts: bind
    - persist: True
    - mkmnt: True
    - require:
      - pkg: nscd
```

First run of the state seems correct, but second run (and every one after) ends up with : 

```
          ID: /mnt/test/var/run/nscd
    Function: mount.mounted
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1531, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/mount.py", line 117, in mounted
                  opts = list(set(opts + active[_device]['opts'] + active[_device]['superopts']))
              KeyError: '/var/run/nscd'
     Started: 16:42:42.314501
    Duration: 15.749 ms
```

It seems to be because /var/run is tmpfs, and it's not taken into account in the corresponding code : 

```
if active[real_name]['device'].startswith('/'):
[...]
else:
     # Remote file systems act differently.
```
But it's not a remote file system.
I'm running 2014.7.1 on Debian Wheezy.
To test you can install nscd, but it should be reproducible with any /var/run dir.
Thanks for your help !

**Comment by tlemarchand** [comment]
If anyone have the same problem before it's resolved, it can be bypassed with something like that :
 
```
nscd_bind_fstab_blockreplace:
  file.blockreplace:
    - name: /etc/fstab
    - marker_start: "# Salt managed zone, state phpapp, DO NOT EDIT"
    - marker_end: "# End of Salt managed zone"
    - content: /var/run/nscd           /mnt/test/var/run/nscd  none    bind    0 0
    - show_changes: True
    - append_if_not_found: True
    - require:
      - pkg: nscd

mount_nscd_chroot:
  cmd.wait:
    - name: mount /mnt/test/var/run/nscd
    - watch:
      - file: nscd_bind_fstab_blockreplace
    - require:
      - file: nscd_bind_fstab_blockreplace
    - watch_in:
      - service: php_fpm_service
```
Which obviously defeats the purpose of "mount.mounted", but hey, it works =)
