### ISSUE TITLE
pillar.show_top runner function is not filtering by minion

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#22009]
``` yaml
# /srv/pillar/top.sls
base:
  'stewart':
    - foo
test:
  'jerry':
    - foo
```

``` bash
% salt-run pillar.show_top jerry
base:
    ----------
    stewart:
        - foo
test:
    ----------
    jerry:
        - foo
```

The pillar top file compiled for jerry should not match stewart.
