### ISSUE TITLE
supervisord.running doesn't fire prereq states if service is triggered by a watched state

### ISSUE THREAD

**Issue by boboli** [saltstack/salt#22026]
Somewhat real-world example:

``` YAML
stop_gunicorn:
    cmd.run:
        - name: supervisorctl stop gunicorn
        - prereq:
            - supervisord: pgbouncer

pgbouncer:
    supervisord.running:
        - name: pgbouncer
        - watch:
            - file: pgbouncer_config

pgbouncer_config:
    file.managed:
        - name: /path/to/pgbouncer.ini
        - source: salt://path/to/pgbouncer.ini
```

The idea is to run a command to stop gunicorn iff the pgbouncer supervisord service needs to restart. So when I change the file managed by pgbouncer_config, I expect all 3 states to run in this order:
pgbouncer_config, stop_gunicorn, pgbouncer

However, the actual output is:

```
----------
          ID: pgbouncer_config
    Function: file.managed
        Name: /etc/supervisor/conf.d/pgbouncer.conf
      Result: True
     Comment: File /etc/supervisor/conf.d/pgbouncer.conf updated
     Started: 22:40:49.102062
    Duration: 6.29 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -11,3 +11,7 @@
                   stopwaitsecs=10
                  +

----------
          ID: stop_gunicorn
    Function: cmd.run
        Name: supervisorctl stop gunicorn
      Result: True
     Comment: No changes detected
     Started:
    Duration:
     Changes:
----------
          ID: pgbouncer
    Function: supervisord.running
      Result: True
     Comment: Restarting service: pgbouncer
     Started: 22:40:49.430279
    Duration: 11331.116 ms
     Changes:
              ----------
              pgbouncer:
                  Restarting service: pgbouncer
```

`stop_gunicorn` wasn't run at all.

I then read the documentation on how prereq worked, and it says:

> When a prereq requisite is evaluated, the pre-required state reports if it expects to have any changes. It does this by running the pre-required single state as a test-run by enabling `test=True`.

So then I tried a test=True run:

```
----------
          ID: pgbouncer_config
    Function: file.managed
        Name: /etc/supervisor/conf.d/pgbouncer.conf
      Result: None
     Comment: The file /etc/supervisor/conf.d/pgbouncer.conf is set to be changed
     Started: 22:45:33.831858
    Duration: 5.692 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -9,9 +9,3 @@
                   autorestart=true
                   redirect_stderr=true
                   stopwaitsecs=10
                  -

----------
          ID: stop_gunicorn
    Function: cmd.run
        Name: supervisorctl stop gunicorn
      Result: True
     Comment: No changes detected
     Started:
    Duration:
     Changes:
----------
          ID: pgbouncer
    Function: supervisord.running
      Result: True
     Comment: Service pgbouncer is already running
     Started: 22:45:34.060082
    Duration: 102.852 ms
     Changes:
----------
```

So indeed, the pgbouncer supervisord.running state isn't reporting that it needs to restart in test=True mode.

I tested some more and determined that this only happens when the reason that it needs to restart is due to a watched state changing (pgbouncer_config). If I manually stop pgbouncer outside of salt and run test=True again, it correctly detects that pgbouncer needs to start as well as running stop_gunicorn:

```
----------
          ID: stop_gunicorn
    Function: cmd.run
        Name: supervisorctl stop gunicorn
      Result: None
     Comment: Command "supervisorctl stop gunicorn" would have been executed
     Started: 22:48:44.219899
    Duration: 1.432 ms
     Changes:
----------
          ID: pgbouncer
    Function: supervisord.running
      Result: None
     Comment: Service pgbouncer will be started
     Started: 22:48:44.326660
    Duration: 104.086 ms
     Changes:
----------
```

I also investigated whether or not this was a bug across all salt states, by testing with cmd.wait and cmd.run, but that seems to work ok (actually found another bug #22024), so I think this is isolated to supervisord.running.

I tested this on a docker container with Ubuntu 14.04 and salt 2014.7.1.
