### ISSUE TITLE
2015.2 git.latest issue

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#22056]
after changing rev branch from master to beta.. I get this fail.
```
[INFO    ] Executing command 'git rev-parse --abbrev-ref HEAD' as user 'opencs' in directory '/srv/opencs'
[DEBUG   ] stdout: master
[ERROR   ] 'NoneType' object has no attribute 'startswith'
```

```
          ID: mfcf.service.opencs.app.package
    Function: git.latest
        Name: gitlab@git.xxx.ca:opencs/opencs.git
      Result: False
     Comment: 'NoneType' object has no attribute 'startswith'
     Started: 19:56:36.769345
    Duration: 45.329 ms
     Changes:   
```

running the command manually I get
```
opencs@opencs-app-2-prod:/srv/opencs$ git rev-parse --abbrev-ref HEAD
master
```

**Comment by rallytime** [comment]
@steverweber Can you post the state that you're using with `git.latest`? This could be a duplicate of #16927.

**Comment by steverweber** [comment]
16927 looks like a different issue.  the state was simple.
```
{{ sls }}:
   git.latest:
        - name: {{ gitrepo }}
        - target: {{ path }}
        - rev: beta
        - user: {{ user }}
```
to work around the issue i wiped the original repo and rebuilt it.
I did find some issue with the user name so perhaps I preformed the git.latest as root then tried to preform it again as a less privliaged user causing issues.

For-now i'll close this... I should have just debugged it while it was in the error state.

**Comment by sambev** [comment]
I don't know if my problem is the same, but I am seeing the same error: 
```
----------
          ID: git@github.com:xxxx.xxx.git
    Function: git.latest
      Result: False
     Comment: 'NoneType' object has no attribute 'startswith'
     Started: 23:05:27.508273
    Duration: 67.479 ms
     Changes:
----------
```

I noticed this in the code for git.latest: 
```python
            remote_rev, new_rev = None, None
            branch = __salt__['git.current_branch'](target, user=user)
            # We're only interested in the remote branch if a branch
            # (instead of a hash, for example) was provided for rev.
            if (branch != 'HEAD' and branch == rev) or rev is None:
                remote_rev = __salt__['git.ls_remote'](target,
                                                       repository=name,
                                                       branch=branch,
                                                       user=user,
                                                       identity=identity,
                                                       https_user=https_user,
                                                       https_pass=https_pass)

            # only do something, if the specified rev differs from the
            # current_rev and remote_rev
            if current_rev in [rev, remote_rev] or remote_rev.startswith(current_rev): #<----------
                new_rev = current_rev
```
`remote_rev` is initialized as None, and if you don't go through this conditional:
```python
if (branch != 'HEAD' and branch == rev) or rev is None:
```
You will always get this error. I am still looking into why this is happening to me. But either way, we should handle that scenario. Maybe return some sort of warning? It would be better than an Attribute error.
