### ISSUE TITLE
grains.get_or_set_hash render error if hash begins with "%"

### ISSUE THREAD

**Issue by Deshke** [saltstack/salt#22141]
fresh minion, if the return value from grains.get_or_set_hash begins with a %, the yaml renderer crashes. 

```bash
salt-minion --versions-report
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.2+ds-1trusty2
```

```yaml

root@salt-master ~ # salt some.server.tld state.sls install_nginx_php
some.server.tld:
    Data failed to compile:
----------
    Rendering SLS 'base:install_db' failed: Unknown yaml render error; line 26

---
[...]
         - pkg: mysql-server
root:
  mysql_user:
    - present
    - host: localhost
    - password: %h0deqfd    <======================
---
```

after removing the minions grains file and a new generation of the hash it works

**Comment by jfindlay** [comment]
@Deshke, thanks for reporting this.

**Comment by basepi** [comment]
@Deshke Could you please include the state file in question as well? Thanks!

**Comment by Deshke** [comment]
```yaml
mysql-server:
   pkg.installed
mysql-client:
   pkg.installed
python-mysqldb:
  pkg:
    - installed
  require:
    - pkg: mysql-server
python-mysql.connector:
   pkg.installed
/etc/salt/grains:
  file.touch
/etc/salt/minion:
   file.append: 
      - text: "mysql.default_file: '/etc/mysql/debian.cnf'"
service salt-minion restart:
  cmd:
    - run
    - require:
         - pkg: mysql-server
root:
  mysql_user:
    - present
    - host: localhost
    - password: {{ salt['grains.get_or_set_hash']('mysql:root') }}

```
