### ISSUE TITLE
npm state module: packages installed from git always reinstall

### ISSUE THREAD

**Issue by ryanfields** [saltstack/salt#22216]
```
git+https://github.com/Strider-CD/strider.git#1.6.5:
  npm.installed:
    - user: me
    - dir: /home/me/node_modules
```

Fails to see when /home/me/node_modules already contains strider, or lacks a means of comparing what's installed to what's about to be cloned.  The result is that git-sourced packages always reinstall.

```
salt --versions-report
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.2+ds-1trusty2
```
