### ISSUE TITLE
svn.update failing with working copy locked

### ISSUE THREAD

**Issue by sirshurf** [saltstack/salt#22233]
I am sending a command from my master to the minion to update it and it's failing. but when I send the same command directly it works.

```
root@master:/home/sirshurf# salt 's2' svn.update /var/www/website
s2:
    ERROR: svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
    svn: E155004: Working copy '/var/www/website' locked.
    svn: E155004: '/var/www/website' is already locked.

    svn --non-interactive update
root@master:/home/sirshurf#
```

But when I run the same thing on the minion I have this:

```
root@s3:/home/sirshurf# svn up /var/www/website/
Updating '/var/www/website':

Fetching external item into '/var/www/website/public/glot':

Fetching external item into '/var/www/website/public/glot/gp-includes/backpress':

Fetching external item into '/var/www/website/public/glot/gp-includes/backpress/pomo':
External at revision 1026.

At revision 361.
At revision 1026.
At revision 6647.
root@s3:/home/sirshurf# 
```

They all should run under the user ROOT, and the minion is running as root.

**Comment by jfindlay** [comment]
@sirshurf, what is the output of `salt 's2' test.versions_report`?  Also can you paste the associated minion debug log?  Thanks.

**Comment by sirshurf** [comment]
Here:
```
root@master:/home/sirshurf# salt 's2' test.versions_report
s2:
                      Salt: 2014.7.2
                    Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                    Jinja2: 2.7.2
                  M2Crypto: 0.21.1
            msgpack-python: 0.3.0
              msgpack-pure: Not Installed
                  pycrypto: 2.6.1
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: 14.0.1
                      RAET: Not Installed
                       ZMQ: 4.0.4
                      Mako: Not Installed
     Debian source package: 2014.7.2+ds-1trusty2
```
And I do not know how to get minion debug log, can you point me?
