### ISSUE TITLE
salt-cloud ec2: minion_id set to hostname instead of supplied name

### ISSUE THREAD

**Issue by yannick** [saltstack/salt#22294]
when i spin up a machine with salt-cloud -p myprofile host.name on ec2 the minion
tries ends up with the amazon style ipstring (e.g. "ip-10-10-12-110") in /etc/salt/minion_id  instead of host.name

**Comment by yannick** [comment]
i fixed this by using -F in script_args for bootstrap-salt.sh.
before it complained about not overwriting /etc/salt/minion_id

**Comment by rallytime** [comment]
@yannick Can you please post the output of `salt-cloud --versions-report`?

**Comment by yannick** [comment]
sorry. 
```yaml
            Salt: 2014.7.2
          Python: 2.7.9 (default, Dec 11 2014, 04:42:00)
          Jinja2: 2.7.3
        M2Crypto: 0.22
  msgpack-python: 0.4.6
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: 1.4.0
          PyYAML: 3.11
           ioflo: 1.1.5
           PyZMQ: 14.5.0
            RAET: Not Installed
             ZMQ: 4.0.5
            Mako: 1.0.1
 Apache Libcloud: 0.17.0
```

```yaml
small:
  provider: aws-irland
  image:  ami-b7811cc0 #archlinux 
  size: t2.small
  ssh_username: root
  script: bootstrap-salt
  script_args: -D -L -A desired-host-name 
```
this produces a minion_id file and the system package supplied, commented /etc/salt/minion file stays there.
when i add script_args -F everything works as desired, no /etc/salt/minion_id is generated but 
```desired-host-name ``` appears in a /etc/salt/minion stripped version with no comments .

i guess its actually expected behavior as the system has the salt package already installed and then, when checking in movefile it fails. 

another problem might be that i by accident downloaded 
https://github.com/saltstack/salt/blob/develop/salt/cloud/deploy/bootstrap-salt.sh
instead of
https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh
not sure why there are two different ones online (new ticket?)
