### ISSUE TITLE
module.portage_config bug with appending accept_keywords

### ISSUE THREAD

**Issue by batulin-s** [saltstack/salt#22321]
If we run
```yaml
www-servers/apache:
  portage_config.flags:
    - accept_keywords: ['~amd64']
```
then change `~amd64` to `amd64` and run again
then in minion
```
cat portage/package.accept_keywords/www-servers/varnish returns
~amd64 amd64
```
but this two flags couldn't be together - `~amd64` means that we want to install the last unstable version, and `amd64` flags means that we want to install stable version.
I afraid, that this issue could be avoid, but I found one way: I changed function `_merge_flags` into module `portage_config`...
