### ISSUE TITLE
Specify additional disks with GCE provider

### ISSUE THREAD

**Issue by RobertAtomic** [saltstack/salt#22346]
Hi,

Is it possible to create and / or attach multiple disks to an instance at create time when using the GCE provider?  The EC2 provider has this in it's example:

```
volumes:
    - { size: 10, device: /dev/sdf }
    - { size: 10, device: /dev/sdg, type: io1, iops: 1000 }
    - { size: 10, device: /dev/sdh, type: io1, iops: 1000 }
```

but doesn't call it out as provider specific.  My GCE config looks like this:

```
test:
  image: backports-debian-7
  size: f1-micro
  location: us-central1-f
  network: default
  tags: '["test"]'
  use_persistent_disk: True
  delete_boot_pd: True
  deploy: True
  make_master: False
  provider: gce
  ssh_username: salt
  ssh_keyfile: /root/.ssh/id_rsa
  volumes:
    - { size: 100 }
```

When instances are created they always have a single 10G volume.
Thanks for any help or advice.
