### ISSUE TITLE
2014.7: Execution Modules are not available in scheduled Returners 

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#22361]
Could someone please verify that execution modules are not available in returners that will be called by scheduled execution modules?

```
schedule:
  monitor_test_ping:
    function: test.ping
    seconds: 60
    returner: <yourreturner>
```

I get a KeyError, and after inspecting __salt__ I can't find the required execution module. Everything works fine when the returner will be called after an execution module run from salt cli tool (master) or salt-call (local minion).

**Comment by rallytime** [comment]
Thanks for the report @bechtoldt. Can you please post the output of `salt --versions-report`, please?

ping @garethgreenaway

**Comment by bechtoldt** [comment]
@rallytime 

```
salt-call --versions
           Salt: 2014.7.2-441-gba083a6
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
```

**Comment by garethgreenaway** [comment]
The above schedule item should work with the returner.  Looking into why it's failing.

**Comment by garethgreenaway** [comment]
Tested this against the latest 2014.7 release and I am unable to duplicate.
```
schedule:
    foobar:
        function: test.ping
        seconds: 60
        returner: syslog
```
