### ISSUE TITLE
Onfail requisite does not handle multiple requirements

### ISSUE THREAD

**Issue by ealphonse** [saltstack/salt#22370]
Given:
```
a:
  cmd.run:
    - name: exit 0

b:
  cmd.run:
    - name: exit 1

c:
  cmd.run:
    - name: echo failure
    - onfail:
      - cmd: a
      - cmd: b
```

salt 2014.7.2 will not trigger state c. It will if the statements are reversed or if there is only one statement:
```
c:
  cmd.run:
    - name: echo failure
    - onfail:
      - cmd: b
      - cmd: a
```
This is the case with orchestration too.

The 'require' requisite does handle several statements I think. Is this the expected behaviour for Onfail?

Thank you in advance.

```
# salt --versions-report
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.2+ds-1trusty2
```

**Comment by rallytime** [comment]
Thanks for the report @ealphonse. I don't think that is expected behavior. I suspect that when this feature was implemented, we just forgot to extend it's functionality to work with multiple onfail requisites. That being said, I am not sure if the default/expected behavior should be an AND or OR. Should the onfail state trigger if only one requisite fails? Or should it trigger if both requisite states fail?

@basepi Do you know what the expected behavior would be when multiple `onfail` requisites are listed?

**Comment by ealphonse** [comment]
Thank you @rallytime.
> That being said, I am not sure if the default/expected behavior should be an AND or OR

Good point. I was expecting an OR but it could be done by duplicating the state to catch all failures. I don't have a use case for an AND behavior but now I am wondering: is the watch requisite implementing an AND or an OR with mutiple statement like this one?:
```
nginx:
  service.running:
    - watch:
      - file: file1
      - file: file2
``` 
Sorry, I am not able to find the answer in the documentation.

**Comment by rallytime** [comment]
It would be intuitive to me for the default behavior of `onfail` to be an OR, but I wanted to throw it out there that I wasn't sure. 

For watch, that is a good question. It seems to me like `require` behaves as an AND. And since `watch` is basically a require with additional behavior, I would *guess* that `watch` is an AND, but I don't know for certain and I haven't tested this. I bet @basepi has some good thoughts on this.

Also, whatever the expected behavior is here for these scenarios, it would probably be good to get it documented.

**Comment by basepi** [comment]
Huh. I could have sworn we already had an issue for this. In any case, I'm pretty sure that `onfail` is using AND. And I'm with the rest of you, it should use OR. This is something we need to fix, though it won't be super easy since the state compiler works primarily off of AND-like requisites.

As far as `watch` goes, I want to say we fixed it so that it's OR-ing, but I can't remember for sure.

**Comment by ealphonse** [comment]
Thank you @basepi.

I confirm `onfail` is using AND (and not the first statement as I implied earlier) and `watch` is using OR, from the quick tests I ran.

I will duplicate the state for now.

**Comment by SaltDBray** [comment]
The behavior will need to switch to OR.

**Comment by ealphonse** [comment]
Hello, just to add that emulating the OR behavior is not as simple as duplicating the state.
If your inital `onfail` state depends on several states, and they in turn require another state which fails, the duplicates `onfail` states will all be triggered as their respective state fails.

**Comment by anitakrueger** [comment]
+1
I am running multiple orchestration states which desperately need the capability to trigger a state on failure that let's us know if the orchestration went south. I was expecting a list to work, but looking at this the AND behavior prevents my onfail requisite from working correctly.

**Comment by anitakrueger** [comment]
Any idea when this is going to be fixed? Since it has been open for a couple months...

**Comment by basepi** [comment]
I labeled it such that it will get some eyes on it. We just haven't had time yet.

**Comment by drlkf** [comment]
In the meantime if you absolutely need this to work, you can use a dummy passthrough state that uses require, to make sure that all the states you intended to put in the onfail have passed, and put the dummy state in the onfail instead. The dummy state will fail if any of your required states fails, and will trigger the onfail.

```
cmd-ok:
  cmd.run:
    - name: 'true'

cmd-fail:
  cmd.run:
    - name: 'false'

pass-check:
  cmd.run:
    - name: 'true'
    - require:
      - cmd: cmd-ok
      - cmd: cmd-fail

cmd-onfail:
  cmd.run:
    - name: 'echo one or more states failed > /dev/stderr'
    - onfail:
      - cmd: pass-check
```
