### ISSUE TITLE
Require file with '~' (tilde) - file.directory, clean: true

### ISSUE THREAD

**Issue by Anderoo16** [saltstack/salt#22388]
Currently in the process of standardizing the /etc/apt directory on our Ubuntu hosts.  While attempting to require the standard directory structure, I ran into an issue with the two files appended with '~'.  See below.

The stanza:
```
/etc/apt/:
  file.directory:
    - user: root
    - group: root
    - mode: 755
    - clean: true
    - require:
      - file: /etc/apt/apt.conf.d
      - file: /etc/apt/preferences.d
      - file: /etc/apt/sources.list.d
      - file: /etc/apt/trusted.gpg.d
      - file: /etc/apt/sources.list
      - file: /etc/apt/sources.list~
      - file: /etc/apt/trusted.gpg
      - file: /etc/apt/trusted.gpg~
```

Result:
```
----------
          ID: /etc/apt/
    Function: file.directory
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     file: /etc/apt/sources.list~
                                     file: /etc/apt/trusted.gpg~
     Started: 
     Duration: 
     Changes:  
```

Let's try without requiring those files:
```
/etc/apt/:
  file.directory:
    - user: root
    - group: root
    - mode: 755
    - clean: true
    - require:
      - file: /etc/apt/apt.conf.d
      - file: /etc/apt/preferences.d
      - file: /etc/apt/sources.list.d
      - file: /etc/apt/trusted.gpg.d
      - file: /etc/apt/sources.list
      #- file: /etc/apt/sources.list~
      - file: /etc/apt/trusted.gpg
      #- file: /etc/apt/trusted.gpg~
```

Now that's no fun..
```
----------
          ID: /etc/apt/
    Function: file.directory
      Result: None
     Comment: The following files will be changed:
              /etc/apt/sources.list~: removed - Removed due to clean
              /etc/apt/trusted.gpg~: removed - Removed due to clean
     Started: 18:03:24.289944
     Duration: 1.314 ms
     Changes: 
```

Salt appears to pick them up and plans to delete them when they aren't required, yet when they are, it can't seem to find them.  Not sure what funky-ness is going on when defining the file path with the '~', nonetheless, I believe this to be a bug.  Please advise.
