### ISSUE TITLE
Unable to use the "name" variable into the defaults of a file template

### ISSUE THREAD

**Issue by SaltwaterC** [saltstack/salt#22463]
I think this example makes the issue easier to understand:

```yaml
{% macro foo(bar) %}
/foo/{{bar}}:
  file.managed:
    - source: salt://foo/bar
    - template: jinja
    - defaults:
      name: {{bar}}
{% endmacro %}
```

The name variable in the defaults is confused for the name argument of the file.managed function in this particular case. The fail output for something like {{ foo('bar') }} is:

```
          ID: /foo/bar
    Function: file.managed
        Name: bar
      Result: False
     Comment: Specified file bar is not an absolute path
     Started: 14:22:16.872754
    Duration: 0.82 ms
     Changes
```

It fails the same even if I **do** duplicate the name with the same value as the state ID, resulting in something like:

```yaml
{% macro foo(bar) %}
/foo/{{bar}}:
  file.managed:
    - name: /foo/{{bar}}
    - source: salt://foo/bar
    - template: jinja
    - defaults:
      name: {{bar}}
{% endmacro %}
```

If I use something else in defaults (such as "vname") then the state is executed successfully.

Please excuse me if the issue is a duplicate. Due to the generic names of the parameters involved, the search is useless.
