### ISSUE TITLE
Add ability to specify a key prefix for ext_pillar S3

### ISSUE THREAD

**Issue by EliRibble** [saltstack/salt#22472]
It would be useful to avoid the workaround in https://github.com/saltstack/salt/issues/22471 if we could specify a key prefix to use when downloading pillar data from S3. This would effectively allow the pillar data to be in a 'subdirectory' of the S3 bucket.

Essentially you could do this:

```
ext_pillar:
  - s3:
    bucket: my-bucket
    keyid: *redacted*
    key: *redacted*
    multiple_env: False
    verify_ssl: True
    environment: prod
    prefix: pillars/prod
```

And salt would pull the pillar data from `s3://my-bucket/pillars/prod/top.sls`. This could also work in multiple_env mode as

```
ext_pillar:
  - s3:
    bucket: my-bucket
    keyid: *redacted*
    key: *redacted*
    multiple_env: True
    verify_ssl: True
    environment: prod
    prefix: deployment/pillars
```

and would pull from 

```
s3://my-bucket/deployment/pillars/base/*
s3://my-bucket/deployment/pillars/prod/*
```
