### ISSUE TITLE
AWS EC2 Wrong hostname/minion_id?

### ISSUE THREAD

**Issue by ninjada** [saltstack/salt#22494]
Hi guys,

I've setup a pretty basic aws test for salt-cloud. I'm simply deploying single ec2 instances running an amazon linux hvm AMI. My instances are deploying and salt-minion gets installed correctly. However, I'm hitting two issues:

1) the minion attempts to connect to the default 'salt' domain. In my providers config, I am specifying an internal DNS record setup for the master as below. I believe this is the setting to tell the minion who it's master is? Is it wrong?

```
  ec2-southeast:
    minion:
      master: saltmaster.aws
    ssh_interface: private_ips
    private_key: /etc/pki/tls/private/salt-key.pem
    keyname: salt-key
    securitygroup: prod-salt-instance
    location: ap-southeast-2
    availability_zone: ap-southeast-2a
    ssh_username: ec2-user
    del_root_vol_on_destroy: True
    rename_on_destroy: True
    provider: ec2
```

for interest sake, my profile config is:

```
base_ec2:
  provider: ec2-southeast
  image: ami-xxxxxxx
  size: t2.micro
  ssh_username: ec2-user
  script: RHEL6
```

2) the minion_id is defaulting to a default hostname eg.  ip-172-31-7-95.ap-southeast-2.compute.internal (hostname=localhost.localdomain on my AMI) rather than the hostname i am specifying in my salt-cloud cmd which is testX.salt.com

The instance launches ok, but I have to manually ssh in and update /etc/hosts and modify minion_id and accept the key restart etc. to get things talking normally.

I've exhausted troubleshooting options atm and can't find proper documentation detailing those things. How can I ensure those two things are behaving normally?
