### ISSUE TITLE
Orchestration job doesn't report failure

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#22490]
Using salt 2014.7.2 (Helium), I've got an orchestration job like:
```
{% set target = salt['pillar.get']('target') %}
{% set shorttarget = target.split('.')[0] %}

varnish-pull:
  salt.function:
    - tgt: cache1
    - name: cmd.run
    - arg:
      - varnishadm backend.set_health {{ shorttarget }} sick
```

The mentioned varnishadm command requires 3 arguments. If `{{ shorttarget }}` is not defined, the command exits non zero and returns with:
```
Unknown request.
Type 'help' for more info.
Too few parameters
```

But salt reports
```
----------
          ID: varnish-pull
    Function: salt.function
        Name: cmd.run
      Result: True
     Comment: Function ran successfully. Function cmd.run ran on cache1.
     Started: 22:59:53.415799
    Duration: 326.225 ms
     Changes:
              cache1:
                  Command failed with error code 104
              Unknown request.
              Type 'help' for more info.
              Too few parameters
----------
```

This is especially problematic in orchestration since I don't wish to have subsequent jobs continue when a prerequisite fails.

**Comment by rallytime** [comment]
Thanks for this excellent report, @mchugh19!

**Comment by cachedout** [comment]
I believe this issue has been resolved in 2015.2:

```
test_orch:
  salt.function:
    - tgt: silver
    - name: cmd.run
    - arg:
      - 'true'
```

```
suffix:
    progress
silver_master:
    ----------
    salt_|-test_orch_|-cmd.run_|-function:
        ----------
        __run_num__:
            0
        changes:
            ----------
            out:
                highstate
            ret:
                ----------
                silver:
        comment:
            Function ran successfully. Function cmd.run ran on silver.
        duration:
            54.582
        name:
            cmd.run
        result:
            True
        start_time:
            10:54:42.379931
```
--------------

```
test_orch:
  salt.function:
    - tgt: silver
    - name: cmd.run
    - arg:
      - 'false'
```

```
suffix:
    progress
silver_master:
    ----------
    salt_|-test_orch_|-cmd.run_|-function:
        ----------
        __run_num__:
            0
        changes:
            ----------
            out:
                highstate
            ret:
                ----------
                silver:
        comment:
            Running function cmd.run failed on minions: silver Function cmd.run ran on silver.
        duration:
            54.268
        name:
            cmd.run
        result:
            False
        start_time:
            10:56:03.643105
```

**Comment by cachedout** [comment]
Since no reply was received, I am closing this issue.

**Comment by leporid** [comment]
I may have a counter-example.

Here is some `salt-run orchestrate` input:
```yaml
test_orch_function:
  salt.function:
    - name: cmd.run
    - tgt: lb-4
    - arg:
      - 'false'
```

Here is the output:
```
salt-master_master:
    ----------
    salt_|-test_orch_function_|-cmd.run_|-function:
        ----------
        __run_num__:
            0
        changes:
            ----------
            out:
                highstate
            ret:
                ----------
                lb-4:

        comment:
            Function ran successfully. Function cmd.run ran on lb-4.
        duration:
            210.248
        name:
            cmd.run
        result:
            True
        start_time:
            03:46:59.919833
```

Here is the salt-master version info:
```
           Salt: 2015.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

Same for salt-minion:
```
           Salt: 2015.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

Thank you!
