### ISSUE TITLE
state fails when targeting multiple hosts but successful against single host

### ISSUE THREAD

**Issue by pschuermann** [saltstack/salt#22522]
I'm seeing this problem where a state fails when targeting multiple windows minions. The same state works just fine if I only target a single minion.

| Test | Command | result |
| --- | --- | --- |
| regex work with other states | salt  'hostname[03].example.com' state.sls diamond.python | WORKS |
| regex fail with the diamond state | salt  'hostname[03].example.com' state.sls diamond | FAILS |
| globbing fails with the diamond state | salt  'hostname*' state.sls diamond | FAILS |
| Running the same state against a single host with regex works | salt  'hostname[0].example' state.sls diamond | WORKS |
| Running the same state against a single host works | salt  'hostname0.example' state.sls diamond | WORKS |

Error for file.managed:

```
          ID: diamond-conf
    Function: file.managed
        Name: C:\\Program Files (x86)\\diamond\\conf\\diamond.conf
      Result: False
     Comment: Unable to manage file: string indices must be integers, not str
     Started: 11:04:55.952000
    Duration: 15.0 ms
     Changes:
```

Error for file.recurse:

```
          ID: diamond-dir
    Function: file.recurse
        Name: C:/Program Files (x86)/diamond/
      Result: False
     Comment: #### C:/Program Files (x86)/diamond/collectors\ping\ping.py ####
              Source file salt://|diamond/files/diamond-win/collectors/ping/ping.py not found

              #### C:/Program Files (x86)/diamond/collectors\sockstat\sockstat.py ####
              Source file salt://|diamond/files/diamond-win/collectors/sockstat/sockstat.py not found
```

Versions are:

```
C:\salt\salt-call.exe --versions-report
           Salt: 2014.7.2
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by rallytime** [comment]
@pschuermann Thanks for reporting this. Can you also post the state that you're using to test this with so we can try and reproduce?

I also know that some *significant* fixes were made to the windows minion in 2014.7.4. I do not know if this particular bug was fixed or not, but it might be worth testing it out. We haven't announced the release yet, but we do have windows packages available already [here](http://docs.saltstack.com/downloads/) that you could try.

ping @twangboy and @UtahDave

**Comment by pschuermann** [comment]
Sure here's the state:
````
{% from 'global_vars.jinja' import grainget, salt_pkg_repo with context %}
{% from 'global_vars.jinja' import pillarget with context %}

include:
  - diamond.python

diamond-conf:
  file.managed:
    - name: {{ pillarget("diamond.config", '/etc/diamond/diamond.conf') }}
    - source: salt://diamond/templates/diamond.conf
    - makedirs: True
    - template: jinja
    - context:
      hostname: {{ cloud_hostname|default(grainget('host')) }} {# 'host' seems to always be the short hostname #}
      collectors_path: {{ pillarget('diamond.collectors_path', '/usr/local/share/diamond/collectors') }}
      handlers_path: {{ pillarget('diamond.handlers_path', '/usr/share/diamond/handlers/') }}
      collectors_config_path: {{ pillarget('diamond.collectors_config_path', '/etc/diamond/collectors/') }}
      handlers_config_path: {{ pillarget('diamond.handlers_config_path', '/etc/diamond/handlers/') }}
      log_file: {{ pillarget('diamond.log_file', '/var/log/diamond/diamond.log') }}
      archive_log_file: {{ pillarget('diamond.archive_log_file', '/var/log/diamond/archive.log') }}
      graphite_server: {{ pillarget('graphite.server') }}
      cpu_simple : {{ pillarget('diamond.collector.cpu.simple', 'False') }}
      cpu_percore : {{ pillarget('diamond.collector.cpu.percore', 'False') }}
      enable_loadavg : {{ pillarget('diamond.collector.loadavg.enabled', 'True') }}

#diamond is not available as a package. Archive state isn't compatible with windows, hence the recursive directories with individual files
#Collectors, handlers, user_scripts, example conf
diamond-dir:
  file.recurse:
    - name: 'C:/Program Files (x86)/diamond/'
    - source: salt://diamond/files/diamond-win
    - include_empty: True
    - require:
      - pkg: diamond-python

diamond-libs:
  file.recurse:
    - name: 'C:/Python27/Lib/site-packages/diamond/'
    - source: salt://diamond/files/libs
    - include_empty: True
    - require:
      - pkg: diamond-python

diamond-bin:
  file.managed:
    - name: 'C:/Python27/Scripts/diamond'
    - source: salt://diamond/files/diamond.py
    - require:
      - file: diamond-dir
      - file: diamond-conf
      - file: diamond-libs
      - cmd: install_psutil
      - cmd: install_configobj
      - pkg: diamond-python

install-service:
  cmd.run:
    - cwd: C:\salt
    - name: nssm.exe install diamond C:\Python27\python.exe C:\Python27\Scripts\diamond -c "\"C:\Program Files (x86)\diamond\conf\diamond.conf\"" --skip-change-user --skip-fork
    - unless: sc query diamond
    - require:
      - file: diamond-bin

start-service:
  cmd.run:
    - name: 'sc start diamond'
    - unless: sc query diamond |findstr RUNNING
    - require:
      - cmd: install-service
````
