### ISSUE TITLE
Restart/reload service through watch/watch_in

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#22520]
I have a service with `reload: true` specified. However, if one of my states change, I want to completely restart it. I haven't found a way to do this other than having an extra state that restarts the service manually with `onchanges` arguments.

In my case I think I have an easier solution thanks to a systemd/systemctl command, but I'd still like to bring this issue up and see if anyone has any ideas.

```yaml
/path/to/file1:
	file.managed:
		watch_in:
			- service: named-service

/path/to/file2:
	file.managed:
		# can't do this
		watch_in:
			- service: named-service restart=True

# have to do this instead
named-service-restart:
	module.run:
		- name: service.restart
		- onchanges:
			- file: /path/to/file2

named-service:
	service.running:
		- reload: true
```

EDIT: Added a better code example.
