### ISSUE TITLE
Documentation update - salt.states.grains

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#22534]
On the page http://docs.saltstack.com/en/latest/ref/states/all/salt.states.grains.html, the syntax for the grains.list_absent and list_present states should be updated to show, you know, an actual list?  It's not intuitive the proper syntax for setting multiple grain values.  After some experimentation, I found that the proper syntax is:
````
roles:
  grains.list_present:
    - value:
      - webserver
      - configmaster
      - development
````
whereas I first tried setting 
````
roles:
  grains.list_present:
      - value: webserver
      - value: configmaster
      - value: development
````
which only set roles to the last value listed.  The examples only show a single value for the list_* commands which is not all that helpful for a list item.
