### ISSUE TITLE
user/group args not available to archive.extrated

### ISSUE THREAD

**Issue by howardroark** [saltstack/salt#22552]
I'm using the latest release candidate of Salt and getting this following output.  According to the docs these args should be available... http://docs.saltstack.com/en/latest/ref/states/all/salt.states.archive.html

```
local:
----------
          ID: openvbx
    Function: archive.extracted
        Name: /home/twillio/domains/openvbx
      Result: True
     Comment: https://github.com/twilio/OpenVBX/archive/1.2.15.tar.gz extracted in /home/twillio/domains/openvbx/
     Started: 15:50:56.166141
    Duration: 11748.331 ms
     Changes:   
              ----------
              directories_created:
                  - /home/twillio/domains/openvbx/
                  - /home/twillio/domains/openvbx/1.2.15
              extracted_files:
               ...
Warnings: 'group' and 'user' are invalid keyword arguments for
              'archive.extracted'. If you were trying to pass additional data to
              be used in a template context, please populate 'context' with
              'key: value' pairs. Your approach will work until Salt Carbon is
              out. Please update your state files.
```
