### ISSUE TITLE
DigitalOcean cloud.provider returning: 'Response' object has no attribute 'getcode'

### ISSUE THREAD

**Issue by aronysidoro** [saltstack/salt#22564]
I have been following along with the DigitalOcean cloud provider config.  I used the latest `salt` version run earlier today using: `curl -L https://bootstrap.saltstack.com | sudo sh -s -- git develop` 

But, I am getting this error: 

```
root@salt:/etc/salt# salt-cloud --list-sizes my-digitalocean-config
[INFO    ] salt-cloud starting
[INFO    ] Starting new HTTPS connection (1): api.digitalocean.com
[ERROR   ] Failed to get the output of 'digital_ocean.avail_sizes()': 'Response' object has no attribute 'getcode'
my-digitalocean-config:
    ----------
```

My config files are as follows:

```
# /etc/salt/cloud.providers
my-digitalocean-config:
    provider: digital_ocean
    api_key: xxx
    ssh_key_file: /keys/digital-ocean-salt-cloud
    ssh_key_names: digital-ocean-salt-cloud
    location: New York 3

# /etc/salt/cloud.profiles
digitalocean-ubuntu:
    provider: my-digitalocean-config
    image: Ubuntu 14.04 x32
    size: 512MB
    location: New York 1
    private_networking: True
    backups_enabled: True
    ipv6: True
```

Is this a config issue or there has been a change in the DigitalOcean API that is not allowing Salt to connect?

Thank you,
Aaron

**Comment by rallytime** [comment]
I just tried this at the HEAD of develop, and it is working well for me. Can you link with doc you are following? I have both an `api_key` and a `client_key` in my provider config file, but that might be because I set this up with the original digital ocean driver for salt-cloud. I'm not sure what is needed for the "v2" driver offhand.

**Comment by aronysidoro** [comment]
I tried with the latest version and the `api_key` and `client_key` arguments but it is still not working. How can i specify which Driver to use if I want to use the "v1" driver instead?  

Would you have a working Digital Ocean Provider and Profile Config file that I could use as an example?

Thanks

**Comment by aronysidoro** [comment]
@rallytime I got it to work.  These were my settings that allowed it to work with the "v2" driver:

```
# /etc/salt/cloud.providers.d/digital_ocean.conf
do:
    provider: digital_ocean

    minion:
        # salt-master IP address
        master: 192.12.245.21

    # previously called `api_key`
    personal_access_token:  xxx

    # salt-master public key name that is saved to DigitalOcean account under SSH Keys
    ssh_key_name: salt__id_rsa.pub

    # salt-master private key location on DigitalOcean server
    ssh_key_file: /root/.ssh/id_rsa
```
