### ISSUE TITLE
minion runs highstate on start if schedule set in pillar 

### ISSUE THREAD

**Issue by ryanwalder** [saltstack/salt#22580]
This is either a bug with the minion or a bug in the documentation and I wanted to clarify if this expected behaviour.

With a schedule in the pillar it triggers the function on salt-minion start:

````yaml
schedule:                                                                       
  highstate:                                                                    
    function: state.highstate                                                   
    minutes: 60
````

This will trigger a highstate when the minion starts which is (to me) slightly unexpected behaviour, I can understand why it would do it but I can't see it [documented](http://docs.saltstack.com/en/latest/topics/jobs/schedule.html) (which has lead to a few head/table interfaces during state development).
