### ISSUE TITLE
cant run mysql_grants

### ISSUE THREAD

**Issue by leftyhitchens** [saltstack/salt#22653]
I have a mysql state laid out [here](https://github.com/leftyhitchens/mysqlsaltstate). When I run this state I get the following errror:

```
Failed to execute: "GRANT ALL ON *.* to 'root'@'%'" 
```

 you should be able run the following commands after pulling the repo:

```
cd test/sci-linux/development
vagrant up
```

And this will run the state in its entirety and show you the error. 

My grant block looks like this:

```
mysql_user_grants:  
  mysql_grants.present:
    - grant: all
    - database: '*.*'
    - user: "'{{ pillar['mysql']['user'] }}'"
    - password: {{ pillar['mysql']['password'] }}
    - connection_user: {{ pillar['mysql']['user'] }}
    - connection_pass: {{ pillar['mysql']['password'] }}
    - host: "'%'"
    - require:
        - sls: mysql
```

Please advise if I have done something wrong or is this a bug.
