### ISSUE TITLE
pip state doesn't get requirements from salt:// file server

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#22651]
salt state : 

```
bootstrap-vz pip dependencies:
  pip.installed:
    - requirements: salt://bootstap-vz/requirements
    - bin_env: /root/virtualenvs/bootstrap-vz/
```

execution : 

```
----------
          ID: bootstrap-vz pip dependencies
    Function: pip.installed
      Result: False
     Comment: Unable to process requirements file salt://bootstap-vz/requirements. Error: pip requirements file 'salt://bootstap-vz/requirements' not found
     Started: 15:21:04.744443
    Duration: 302.84 ms
     Changes:   
```

version : 

```
# salt-call --versions
                  Salt: 2014.7.2
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2014.7.2+ds-1~bpo70+1
```
