### ISSUE TITLE
salt-ssh does not work with list matcher

### ISSUE THREAD

**Issue by Xiol** [saltstack/salt#22703]
Hi,

```
[root@saltmaster ~]# salt --versions
           Salt: 2015.2.0rc2-272-g34526d5
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

I'm having trouble using the list matcher with salt-ssh. For example, my roster file (we're autogenerating these which is why the hostname is a UUID):

```
8feb256a-c4a4-4879-a814-eb50de700b2c:
  host: 172.16.32.59
  port: 22
  user: root
  passwd: password
  sudo: false
  tty: false
  timeout: 60
  thin_dir: /var/lib/acmecorp/salt/
f828da3e-9bf2-4564-8fa9-d931b2ac0554:
  host: 172.16.32.57
  port: 22
  user: root
  passwd: password
  sudo: false
  tty: false
  timeout: 60
  thin_dir: /var/lib/acmecorp/salt/
```

Then, when trying to perform a list match against them:

```
/usr/bin/salt-ssh --out yaml --no-color --roster-file roster.tmp -L 'f828da3e-9bf2-4564-8fa9-d931b2ac0554,8feb256a-c4a4-4879-a814-eb50de700b2c' state.sls basic_cluster.0_both pillar='{...}'
```

I'm getting this back:

```
No hosts found with target ['f828da3e-9bf2-4564-8fa9-d931b2ac0554', '8feb256a-c4a4-4879-a814-eb50de700b2c'] of type list
```

Changing the UUIDs to friendlier names also results in the same error. The main/normal 'salt' binary has no problem using the list matcher as far as I can tell.
