### ISSUE TITLE
salt.states.file.copy not changing user/group

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#22711]
## Consider the following

I run the following state on a minion

```
yaml
  copy_oracle_jdbc_driver:
    file.copy:
      - name:  {{ jbosseap_settings.jboss_home }}/modules/com/oracle/main/{{ jbosseap_settings.jdbc_driver_oracle }}
      - source: {{ jbosseap_settings.oracle_client_home }}/lib/{{ jbosseap_settings.jdbc_driver_oracle }}
      - preserve: false
      - user: root
      - group: root
      - mode: 644
      - makedirs: True
```

Now, if I change the user: and group: to something other than root (jboss in my case) and then run the state again, the user and group does not change. 
## Expectation:

I would expect the user and/or group to change if they are changed in the state definition.
## Troubleshooting steps:

If I delete the file and then run the state again, the file is copied and the correct user and group values are applied

```
## Versions (master):
salt-run --versions-report
Salt Version:
           Salt: 2015.2.0rc1-5294-gb7362ee

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: 0.3.4
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
           RAET: Not Installed
            ZMQ: 4.0.4
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.4
       pycrypto: 2.0.1

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.12.2.el6.x86_64
         system: CentOS 6.6 Final

## Versions (minion):
salt-run --versions-report
Salt Version:
           Salt: 2015.2.0rc1-5294-gb7362ee

Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: 0.3.4
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
           RAET: Not Installed
            ZMQ: 4.0.4
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.4
       pycrypto: 2.0.1

System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.12.2.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.6 Santiago
```
