### ISSUE TITLE
digital_ocean_v2.py doesn't restore snapshot

### ISSUE THREAD

**Issue by ty2u** [saltstack/salt#22724]
Hey,

I'm wondering if someone can help me figure this out.

I made a snapshot of a server and I am trying to restore it via the digital_ocean_v2.py but it's not working properly.

The name of the snapshot in the example is server.example.com

Debug output of command:
salt-cloud -p server.example.com server.example.com
https://gist.github.com/ty2u/f48557e6c4bd56723f25

server.example.com profile:
```
server.example.com:
    provider: do
    image: server.example.com
    size: 4gb
    location: New York 3
    private_networking: True
    backups_enabled: False
    ipv6: False
    create_dns_record: True
    delete_dns_record: True
```

salt --versions-report
```
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.2+ds-1trusty2
```

If I modify the digital_ocean_v2.py script to use the image id number instead of the name it will actually launch the server but still seems to display errors. I did this by replacing lines 226-229:

```python
        if vm_image in (images[image]['name'], images[image]['slug'], images[image]['id']):
            if images[image]['slug'] is not None:
                return images[image]['slug']
            return int(images[image]['id'])
```

with

```python
        if vm_image in (images[image]['id']):
            return int(images[image]['id'])
```

Furthermore, the ssh key is not valid, I think when the server has a different IP address sometimes.
