### ISSUE TITLE
Iptables broken in 2014.7.4+ds-1trusty1 on Ubuntu 14.04

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#22732]
After updating to `2014.7.4+ds-1trusty1` all iptables related jobs are now failing.

Example state:
```
          ID: iptables_smtp_allow_127.0.0.1
    Function: iptables.append
      Result: False
     Comment: Failed to set iptables rule for iptables_smtp_allow_127.0.0.1.
              Attempted rule was /sbin/iptables -t filter -A INPUT  -p tcp --dport smtp --source 127.0.0.1 --fun append --jump ACCEPT for ipv4
     Started: 09:08:49.260394
    Duration: 35.801 ms
     Changes:   
```
Running the command manually results in:
```
server ~ # /sbin/iptables -t filter -A INPUT  -p tcp --dport smtp --source 127.0.0.1 --fun append --jump ACCEPT 
iptables v1.4.21: unknown option "--fun"
Try `iptables -h' or 'iptables --help' for more information.
```

The `--fun` flag does not exist in iptables v1.4.21 which is the version shipped with Ubuntu 14.04 LTS.

Specs:
``` 
                  Salt: 2014.7.4
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.4+ds-1trusty1
```

Seems like this is going to require a hotfix and new package.
