### ISSUE TITLE
file.absent should have files option to support multiple files

### ISSUE THREAD

**Issue by akaey** [saltstack/salt#22833]
Currently there is no way to delete multiple files with file.absent. It should have an option 'files' like pkg.installed has option pkgs.

This works, should be nicer with 'files' option:

``` yaml
# RPMs are leftover in / directory, cleaning up
rpm-cleanup1:
  file.absent:
    - name: /consul-0.3.0-el6.x86_64.rpm
# Because salt is stupid
rpm-cleanup2:
  file.absent:
    - name: /redis-hyperloglog-initd-1.21-el6.x86_64.rpm
rpm-cleanup3:
  file.absent:
    - name: /confd-0.6.0-CMX.1.x86_64.rpm
```
