### ISSUE TITLE
Make better guidelines for creating state modules

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#22867]
For instance, it's necessary to have a one-to-one relationship between resources and state modules, due to how requisites work:

``` yaml
foo:
  boto_iam.user_present:
    - enabled: True
  boto_iam.group_present:
    - enabled: True

apache2:
  pkg.installed:
    - watch:
      - boto_iam: foo
```

In the above, which state is being watched?

This is an often overlooked issue that people run into during review, or worse after a module has been released.

**Comment by basepi** [comment]
I don't think the above state will work. The high data will be converted to something like this:

```
foo:
  boto_iam:
    - user_present
    - enabled: True
  boto_iam:
    - group_present
    - enabled: True

apache2:
  pkg:
    - installed
    - watch:
      - boto_iam: foo
```

The boto_iam keys will conflict, so I don't think it will even compile.

I also wanted to note that `state modules` usually refers to the python modules that state files use. (`salt/states/file.py` for example). I call .sls files "state files", and individually stanzas within "state declarations" or something similar. We need to nail down that vocabulary.

But yes, we should definitely have some better guidelines in the documentation. I usually recommend that people always explicitly define their `- name:` arguments, and never nest more than one state declaration below the same ID. (Personal preference, but it definitely prevents problems like this)
