### ISSUE TITLE
Include salt formulas from git inside states instead of gitfs_roots

### ISSUE THREAD

**Issue by tony** [saltstack/salt#22943]
Currently the practice for adding formulas is to edit the config: http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html

I think this runs kind of contrary to intuition. I want to include redis-formula.  What does this have to do with adding a root? Adding a file root is a big deal, it requires editing a config. Snapping in a formula via an include makes life so much easier for testing and sharing formulas.

The markup / language I'm not fully looking closely at yet, here's the idea:

```yaml
# pip/gitfs_roots vcs uri style
include:
  - vim
  - https://github.com/saltstack-formulas/redis-formula.git:
    root: redis
    

# golang style
include:
  - vim
  - github.com/saltstack-formulas/redis-formula/redis
```

vcs import / packaging in production is already safe and commonplace. One programming language bakes it into the spec.

- golang vcs imports (https://golang.org/cmd/go/#hdr-Remote_import_paths)
- pip vcs urls (https://packaging.python.org/en/latest/installing.html#installing-from-vcs)
