### ISSUE TITLE
salt-ssh issue

### ISSUE THREAD

**Issue by gekkyy** [saltstack/salt#23014]
Hi,
I'm trying to setup salt-ssh with a regular user which can sudo into root.
But get this error everytime:

```
[DEBUG   ] rm: cannot remove `/root/.33780c6e872c': Permission denied
That file can be found in /home/andvon01/.33780c6e872c 
Not in /root my /etc/salt/roster file looks like this:
fsu666:
  host: fsu666.example.com
  user: andvon01
  sudo: True
  tty: True
```

As far as I can see it creates the job file in the users home directory but fails when it tries to delete the job in /root/

OS Version (on both master and minion):

``` yaml
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.6 (Final)
Release:    6.6
Codename:   Final
```

``` yaml
salt-ssh --versions-report
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

Any thing Im missing? 
Thanks in advance
