### ISSUE TITLE
Recursive requisite found after upgrade from 2014.7.4 to 2014.7.5

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#23051]
```
----------
          ID: syslog-ng_bidder_application_logs
    Function: file.managed
        Name: /etc/syslog-ng/conf.d/bidder_application_logs.conf
      Result: False
     Comment: Recursive requisite found
     Started: 
    Duration: 
     Changes:   
----------
```

What was done is this:

```
# apt-cache policy salt-common salt-minion
salt-common:
  Installed: 2014.7.4+ds-1trusty1
  Candidate: 2014.7.5+ds-1ubuntu1
  Version table:
     2014.7.5+ds-1ubuntu1 0
        500 http://ppa.launchpad.net/saltstack/salt/ubuntu/ trusty/main amd64 Packages
 *** 2014.7.4+ds-1trusty1 0
        100 /var/lib/dpkg/status
     0.17.5+ds-1 0
        500 http://mirror.hetzner.de/ubuntu/packages/ trusty/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
salt-minion:
  Installed: 2014.7.4+ds-1trusty1
  Candidate: 2014.7.5+ds-1ubuntu1
  Version table:
     2014.7.5+ds-1ubuntu1 0
        500 http://ppa.launchpad.net/saltstack/salt/ubuntu/ trusty/main amd64 Packages
 *** 2014.7.4+ds-1trusty1 0
        100 /var/lib/dpkg/status
     0.17.5+ds-1 0
        500 http://mirror.hetzner.de/ubuntu/packages/ trusty/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```
and
```
# apt-get install salt-common salt-minion
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  python-oauthlib
Use 'apt-get autoremove' to remove it.
Suggested packages:
  salt-doc python-augeas
The following packages will be upgraded:
  salt-common salt-minion
2 upgraded, 0 newly installed, 0 to remove and 166 not upgraded.
Need to get 1 968 kB of archives.
After this operation, 18,4 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/saltstack/salt/ubuntu/ trusty/main salt-minion all 2014.7.5+ds-1ubuntu1 [28,3 kB]
Get:2 http://ppa.launchpad.net/saltstack/salt/ubuntu/ trusty/main salt-common all 2014.7.5+ds-1ubuntu1 [1 939 kB]
Fetched 1 968 kB in 0s (2 172 kB/s)     
(Reading database ... 109934 files and directories currently installed.)
Preparing to unpack .../salt-minion_2014.7.5+ds-1ubuntu1_all.deb ...
salt-minion stop/waiting
Unpacking salt-minion (2014.7.5+ds-1ubuntu1) over (2014.7.4+ds-1trusty1) ...
Preparing to unpack .../salt-common_2014.7.5+ds-1ubuntu1_all.deb ...
Unpacking salt-common (2014.7.5+ds-1ubuntu1) over (2014.7.4+ds-1trusty1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for ufw (0.34~rc-0ubuntu2) ...
Setting up salt-common (2014.7.5+ds-1ubuntu1) ...
Setting up salt-minion (2014.7.5+ds-1ubuntu1) ...
salt-minion start/running, process 10528
```

**Comment by rallytime** [comment]
Thanks for the report @zerthimon. Can we see your state files that are involved?

**Comment by zerthimon** [comment]
@rallytime 
This is the state that's causing it:
```
syslog-ng_bidder_application_logs:
  file.managed:
    - name: /etc/syslog-ng/conf.d/bidder_application_logs.conf
    - source: salt://RTB/application_logs.conf
    - template: jinja
    - context:
      service_name: bidder
    - user: root
    - group: root
    - mode: 644
    - require:
      - sls: syslog-ng
    - watch_in:
      - service: syslog-ng_service
```

and syslog_ng state that is included in the state above is:
```
other_log_packages:
  pkg.purged:
    - name: rsyslog 

syslog-ng_package:
  pkg.installed:
    - name: syslog-ng-core
    - require:
      - pkg: other_log_packages

syslog-ng_config:
  file.managed:
    - name: /etc/syslog-ng/syslog-ng.conf
    - source: salt://syslog-ng/syslog-ng.conf
    - user: root
    - group: root
    - mode: 644
    - require: 
      - pkg: syslog-ng_package

syslog-ng_defaults:
  file.managed:
    - name: /etc/default/syslog-ng
    - source: salt://syslog-ng/syslog-ng
    - user: root
    - group: root
    - mode: 644
    - require: 
      - pkg: syslog-ng_package

syslog-ng_conf_dir:
  file.directory:
    - name: /etc/syslog-ng/conf.d
    - user: root
    - group: root
    - mode: 755
    - require:
      - pkg: syslog-ng_package

syslog-ng_network_destination:
  file.managed:
    - name: /etc/syslog-ng/conf.d/network_destination.conf
    - source: salt://syslog-ng/configs/network_destination.conf
    - template: jinja
    - user: root
    - group: root
    - mode: 644
    - require:
      - file: syslog-ng_conf_dir

syslog-ng_client_system_logs:
  file.managed:
    - name: /etc/syslog-ng/conf.d/client_system_logs.conf
    - source: salt://syslog-ng/configs/client_system_logs.conf
    - template: jinja
    - user: root
    - group: root
    - mode: 644
    - require:
      - file: syslog-ng_conf_dir

syslog-ng_service:
  service.running:
    - name: syslog-ng
    - enable: True
    - require:
      - pkg: syslog-ng_package
      - file: syslog-ng_conf_dir
    - watch:
      - file: syslog-ng_config
      - file: syslog-ng_defaults
      - file: syslog-ng_network_destination
      - file: syslog-ng_client_system_logs
```

**Comment by eliasp** [comment]
This could explain the recent issues I've been seeing.

I was working on a (still bit hackish) [patch for saltstack-formulas/mysql-formula](https://github.com/saltstack-formulas/mysql-formula/issues/70) and ran into similar issues using `2014.7.5`.
Can't provide much more details right now, as this was work related - will try to get back with more information on Monday or Tuesday.

**Comment by zerthimon** [comment]
Fixed in my setup by removing: 
```
    - require:
      - sls: syslog-ng
```

From the calling state:
```
syslog-ng_bidder_application_logs:
  file.managed:
    - name: /etc/syslog-ng/conf.d/bidder_application_logs.conf
    - source: salt://RTB/application_logs.conf
    - template: jinja
    - context:
      service_name: bidder
    - user: root
    - group: root
    - mode: 644
    - watch_in:
      - service: syslog-ng_service
```

Perhaps requiring a state and then using watch_in on one of it's components is a wrong thing to do ?
Weird, that it worked in the previous version.

@rallytime Feel free to close this issue.
