### ISSUE TITLE
service.{enabled,disabled,dead,running} broken on ubuntu 15.04+

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#23122]
(Or systemd based ubuntus (for those wich run older versions, but with the systemd packages).

To be exact, the following sls 

```
{% set s = ['rsyslog'] %}
test:
  service.running:
    - names: {{s}}
    - enable: false

test1:
  service.running:
    - names: {{s}}
    - enable: true
    - require:
        - service: test
```

reults to

```
local:
----------
          ID: test
    Function: service.running
        Name: rsyslog
      Result: True
     Comment: Service rsyslog is already disabled, and is in the desired state
     Started: 10:09:19.591035
    Duration: 403.086 ms
     Changes:
----------
          ID: test1
    Function: service.running
        Name: rsyslog
      Result: False
     Comment: Failed when setting service rsyslog to start at boot, but the service was already running
     Started: 10:09:19.995737
    Duration: 743.762 ms
     Changes:

Summary
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
```

because of falling

```
[INFO    ] Executing command 'systemctl status rsyslog.service' in directory '/root'
[DEBUG   ] output: * rsyslog.service - LSB: enhanced syslogd
   Loaded: loaded (/etc/init.d/rsyslog)
   Active: active (running) since Mon 2015-04-27 01:18:51 CEST; 1 day 8h ago
     Docs: man:systemd-sysv-generator(8)
 Main PID: 1071 (rsyslogd)
   CGroup: /system.slice/rsyslog.service
           `-1071 /usr/sbin/rsyslogd -n

Apr 27 01:18:51 forestguard systemd[1]: Starting System Logging Service...
Apr 27 01:18:51 forestguard systemd[1]: Started System Logging Service.
[INFO    ] Executing command 'systemctl enable rsyslog.service' in directory '/root'
[ERROR   ] Command 'systemctl enable rsyslog.service' failed with return code: 1

```

See #23060

**Comment by rallytime** [comment]
Thanks for this report @kiorky.

FYI @joehealy and @s0undt3ch

**Comment by Reiner030** [comment]
Hi, 

same problem for Debian Jessie... 
I had to setup state for postgres for referencing - require: service.postfix
and got in new testsystem every run:

```
local:
----------
          ID: common-explicit-service-postfix
    Function: service.running
        Name: postfix
      Result: True
     Comment: Service postfix has been enabled, and is in the desired state
     Started: 14:53:25.913785
    Duration: 897.382 ms
     Changes:   
              ----------
              postfix:
                  True
```


```
# /etc/init.d/postfix status
● postfix.service - LSB: Postfix Mail Transport Agent
   Loaded: loaded (/etc/init.d/postfix)
  Drop-In: /run/systemd/generator/postfix.service.d
           └─50-postfix-$mail-transport-agent.conf
   Active: active (running) since Thu 2015-04-30 12:20:24 UTC; 2h 28min ago
   CGroup: /system.slice/postfix.service
           ├─12212 pickup -l -t unix -u -c
           ├─17315 /usr/lib/postfix/master
           └─17317 qmgr -l -t unix -u

Apr 30 12:20:24 test-nosql04 postfix[17204]: Starting Postfix Mail Transport Agent: postfix.
Apr 30 12:20:24 test-nosql04 postfix/master[17315]: daemon started -- version 2.11.3, configuration /etc/postfix
```
