### ISSUE TITLE
'unless' is an invalid keyword argument for 'file.replace'

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#23139]
"unless" is supposed to be a global requisite as far as I know.

```
----------
          ID: google-fluentd-config-edit1
    Function: file.uncomment
        Name: /etc/google-fluentd/google-fluentd.conf
      Result: True
     Comment: Pattern already uncommented
     Started: 17:12:42.820923
    Duration: 37.156 ms
     Changes:   
    Warnings: 'unless' is an invalid keyword argument for 'file.uncomment'. If
              you were trying to pass additional data to be used in a template
              context, please populate 'context' with 'key: value' pairs. Your
              approach will work until Salt Carbon is out. Please update your
              state files.
```
```
install-gce-logging-agent:
  cmd.script:
    - source: https://storage.googleapis.com/signals-agents/logging/google-fluentd-install.sh
    - creates: /var/log/google-fluentd/google-fluentd.log

# FIXME once we respin everything with the proper roles, we won't need this any longer
/etc/google-fluentd/keyfile.p12:
  file.managed:
    - source: salt://dist/janus/{{ salt['grains.get']('ocsenv') }}.cloudstoragekey.p12
    - user: root
    - group: root
    - mode: 400
    - unless:
      - /usr/share/google/get_metadata_value service-accounts/default/scopes | grep -q logging.write

google-fluentd-config-edit1:
  file.uncomment:
    - name: /etc/google-fluentd/google-fluentd.conf
    - regex: 'auth_method private_key'
    - unless:
      - /usr/share/google/get_metadata_value service-accounts/default/scopes | grep -q logging.write

google-fluentd-config-edit2:
  file.uncomment:
    - name: /etc/google-fluentd/google-fluentd.conf
    - regex: 'private_key_path /etc/google-fluentd/keyfile.p12'
    - unless:
      - /usr/share/google/get_metadata_value service-accounts/default/scopes | grep -q logging.write

google-fluentd-config-edit3:
  file.replace:
    - name: /etc/google-fluentd/google-fluentd.conf
    - pattern: '(.*)# private_key_email.*'
    - repl: '\1private_key_email {{ salt['pillar.get']('gce:logging:email') }}'
    - unless:
      - /usr/share/google/get_metadata_value service-accounts/default/scopes | grep -q logging.write

google-fluentd:
  service.running:
    - watch:
      - file: google-fluentd-config-edit1
      - file: google-fluentd-config-edit2
      - file: google-fluentd-config-edit3
```
```
           Salt: 2015.2.0rc1-1050-geb0d71d
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: Not Installed
```
