### ISSUE TITLE
client_acl and syndic 

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#23158]
While client_acl works from master where minions actually connected to, client_acl doesn't work from master of master . 

ie : `salt '*' test.ping` works from master that has direct connections from the minions 

`salt '*' test.ping` from master of master shows timeout from the directed minions only, ie syndics of masters. 

Sound very familiar to the issue i am having while using batch mode 
https://github.com/saltstack/salt/issues/22110 thats the ticket i raised about batch mode not working in #20152.

``` yaml
           Salt: 2015.2.0
         Python: 2.7.9 (default, Dec 30 2014, 13:07:54)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
