### ISSUE TITLE
Document that salt://| escapes special characters in filenames

### ISSUE THREAD

**Issue by lloesche** [saltstack/salt#23211]
I'm trying to copy a file called '?checkpoint' from the salt master to  a minion. My SLS file looks like this:

```
/etc/marathon/conf/?checkpoint:
  file.managed:
    - source: salt://hw/config/?checkpoint
    - makedirs: True
```

When running the state I get a

```
----------
          ID: /etc/marathon/conf/?checkpoint
    Function: file.managed
      Result: False
     Comment: Source file salt://hw/config/?checkpoint not found
     Started: 10:27:53.648561
    Duration: 54.034 ms
     Changes:
----------
```
(the file does exist of course)

I've tried all kinds of escaping like
```
    - source: salt://hw/config/\?checkpoint
    - source: "salt://hw/config/?checkpoint"
    - source: 'salt://hw/config/?checkpoint'
```

But none seems to work. What's the correct way to reference this file in my SLS?

**Comment by jfindlay** [comment]
@lloesche, this may be a bug with salt itself or an annoyance with yaml and/or msgpack but with or without a known workaround.

@basepi, do you have any ideas on how to handle this case?

**Comment by basepi** [comment]
The problem here is we support special arguments in `salt://` URLs to define environment and other options for a file. We will need to add functionality to support escaped question marks.

**Comment by jfindlay** [comment]
@lloesche, as @basepi says, the `salt://` url format can potentially contain a query string, `salt://dir/file.txt?saltenv=base`.  The way to prevent the fileclient/fileserver from interpreting `?` as the initial token of a query string is to reference the file with `salt://|` rather than `salt://`.  From my searches, there doesn't seem to be any documentation about this feature.

So to escape the `?`, you can do:
```yaml
/etc/marathon/conf/?checkpoint:
  file.managed:
    - source: salt://|hw/config/?checkpoint
    - makedirs: True
```
