### ISSUE TITLE
iptables.append --log parameters must be after --jump LOG

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#23224]
When using iptables.append with log parameters --log-prefix and --log-level the state fails.  --log options need to be after the --jump LOG in the command.

master:  ubuntu 14.04.2, salt-master 2014.7.5
minion:  ubuntu 14.04.2, salt- minion 2014.7.5

```yaml
  iptables_LOGGING_limit:
  iptables.append:
   - table: filter
    - chain: LOGGING
    - match: limit
    - jump: LOG
    - limit: 2/min
    - log-level: 4
    - log-prefix: "iptables-dropped: "
```

Results
```
  test-bill-api-prod-1:
  ----------
            ID: iptables_LOGGING_limit
      Function: iptables.append
        Result: False
       Comment: Failed to set iptables rule for iptables_LOGGING_limit.
                Attempted rule was /sbin/iptables -t filter -A LOGGING  -m limit --log-prefix iptables-dropped:    --log-level 4 --limit 2/min --jump LOG for ipv4
       Started: 15:43:51.254211
      Duration: 17.047 ms
       Changes:

  Summary
  ------------
  Succeeded: 0
  Failed:    1
  ------------
```

Running the command specified above

```bash
root@test-bill-api-prod-1:~#  /sbin/iptables -t filter -A LOGGING  -m limit --log-prefix iptables-dropped:    --log-level 4 --limit 2/min --jump LOG
iptables v1.4.21: unknown option "--log-prefix"
Try `iptables -h' or 'iptables --help' for more information.
root@test-bill-api-prod-1:~#
```

Moving the --jump LOG before the --log options makes this work
```bash
root@test-bill-api-prod-1:~# /sbin/iptables -t filter -A LOGGING  -m limit --jump LOG --log-prefix iptables-dropped:    --log-level 4 --limit 2/min
root@test-bill-api-prod-1:~#
```
