### ISSUE TITLE
Debian Jessie: locale.present not working again

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#23221]
Hi, 

I think like in https://github.com/saltstack/salt/issues/13295 

the state definition
```
de_DE.UTF-8:
    locale.present

en_GB.UTF-8:
    locale.present

en_US.UTF-8:
    locale.present
```

failed to setup:
```
[INFO    ] Running state [de_DE.UTF-8] at time 14:39:32.920571
[INFO    ] Executing state locale.present for de_DE.UTF-8
[INFO    ] Executing command 'locale -a' in directory '/root'
[DEBUG   ] output: C
C.UTF-8
POSIX
[ERROR   ] The provided locale "de_DE.UTF-8" is not found in /usr/share/i18n/SUPPORTED
[ERROR   ] Failed to generate locale de_DE.UTF-8
[INFO    ] Completed state [de_DE.UTF-8] at time 14:39:32.944612
[INFO    ] Running state [en_GB.UTF-8] at time 14:39:32.944945
[INFO    ] Executing state locale.present for en_GB.UTF-8
[INFO    ] Executing command 'locale -a' in directory '/root'
[DEBUG   ] output: C
C.UTF-8
POSIX
[ERROR   ] The provided locale "en_GB.UTF-8" is not found in /usr/share/i18n/SUPPORTED
[ERROR   ] Failed to generate locale en_GB.UTF-8
[INFO    ] Completed state [en_GB.UTF-8] at time 14:39:34.215649
[INFO    ] Running state [en_US.UTF-8] at time 14:39:34.216000
[INFO    ] Executing state locale.present for en_US.UTF-8
[INFO    ] Executing command 'locale -a' in directory '/root'
[DEBUG   ] output: C
C.UTF-8
POSIX
[ERROR   ] The provided locale "en_US.UTF-8" is not found in /usr/share/i18n/SUPPORTED
[ERROR   ] Failed to generate locale en_US.UTF-8
```

It seems that its not opend in file correctly:

```
# grep -v -e ^# -e ^$ /etc/locale.gen
#
```
When I edit/activate it manually:
```
# grep -v -e ^# -e ^$ /etc/locale.gen 
de_DE.UTF-8 UTF-8
en_GB.UTF-8 UTF-8
en_US.UTF-8 UTF-8
# locale-gen 
Generating locales (this might take a while)...
  de_DE.UTF-8... done
  en_GB.UTF-8... done
  en_US.UTF-8... done
Generation complete.
```

the state is correctly recognized as already setup.

**Comment by jfindlay** [comment]
@Reiner030, what is the output of `salt <minion> test.versions_report`?  Have you verified this on the current salt release (2014.7.5)?  Thanks.

**Comment by Reiner030** [comment]
Hi,

sorry, forgotten to add in this report the version number 2014.7.5 ... 
```
# salt-call test.versions_report
local:
                      Salt: 2014.7.5
                    Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                    Jinja2: 2.7.3
                  M2Crypto: 0.21.1
            msgpack-python: 0.4.2
              msgpack-pure: Not Installed
                  pycrypto: 2.6.1
                   libnacl: Not Installed
                    PyYAML: 3.11
                     ioflo: Not Installed
                     PyZMQ: 14.4.0
                      RAET: Not Installed
                       ZMQ: 4.0.5
                      Mako: 1.0.0
     Debian source package: 2014.7.5+ds-1
# vi /etc/locale.gen    # comment out en_US.UTF-8
# locale-gen 
Generating locales (this might take a while)...
  de_DE.UTF-8... done
  en_GB.UTF-8... done
Generation complete.
# salt-call state.highstate
...
local:
----------
          ID: en_US.UTF-8
    Function: locale.present
      Result: False
     Comment: Failed to generate locale en_US.UTF-8
     Started: 10:45:38.359377
    Duration: 26.933 ms
     Changes:   
...
```

**Comment by diego-XA** [comment]
I am also having this bug since a lot of time ago. This is my minion version:

```
root@backup:~# salt-call --versions-report
                  Salt: 2015.5.0
                Python: 2.7.3 (default, Mar 14 2014, 11:57:14)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: Not Installed
 Debian source package: 2015.5.0+ds-1~bpo70+1
```

In my case I found something interesting. This is the error I have:

```
----------
          ID: gl_ES.UTF-8
    Function: locale.present
      Result: False
     Comment: Failed to generate locale gl_ES.UTF-8
     Started: 07:57:40.855606
    Duration: 39.364 ms
     Changes:   
```

This is the error I see in the trace:

```
[ERROR   ] The provided locale "gl_ES.UTF-8" is not found in /usr/share/i18n/SUPPORTED
[ERROR   ] Failed to generate locale gl_ES.UTF-8
[INFO    ] Completed state [gl_ES.UTF-8] at time 08:08:30.939821
```

In the salt code I saw that this was triggered by:

```
 if on_debian or on_gentoo:  # file-based search
        search = '/usr/share/i18n/SUPPORTED'
        valid = __salt__['file.search'](search, '^{0}$'.format(locale))
    else:  # directory-based search
        if on_suse:
            search = '/usr/share/locale'
        else:
            search = '/usr/share/i18n/locales'
        try:
            valid = "{0}_{1}".format(locale_info['language'],
                                     locale_info['territory']) in os.listdir(search)
        except OSError, ex:
            log.error(ex)
            raise CommandExecutionError("Locale \"{0}\" is not available.".format(locale))

    if not valid:
        log.error('The provided locale "{0}" is not found in {1}'.format(locale, search))
        return False
```

So the function looking for the locale in the SUPPORTED file is the `file.search` function called with the pattern `'^gl_ES.UTF-8$'`.

And funny enough, look at this:

```
root@backup:~# salt-call  file.search  /usr/share/i18n/SUPPORTED "^gl_ES.UTF-8$"                                                                                                                                                                                                 
local:
    False
root@backup:~# salt-call  file.search  /usr/share/i18n/SUPPORTED "gl_ES.UTF-8"                                                                                                                                                                                                   
local:
    True
root@backup:~# egrep "^gl_ES.UTF-8" /usr/share/i18n/SUPPORTED
gl_ES.UTF-8 UTF-8

```

So you can seee that there is an ending " UTF-8" in that line so the pattern for the locale does not match. (The SUPPORTED file format for gentoo is exactly the same).
The same happens for the above locales.

I suggest to change the pattern to:

```
root@backup:~# salt-call  file.search  /usr/share/i18n/SUPPORTED "^gl_ES.UTF-8( UTF-8)?$"
local:
    True
```

Should I make a PR ?

**Comment by diego-XA** [comment]
Actually, a better pattern would be:

```shell
root@backup:~# salt-call  file.search  /usr/share/i18n/SUPPORTED "^gl_ES.UTF-8 (UTF-|ISO-8859-).+$"
local:
    True
```
or simply:

```shell
root@backup:~# salt-call  file.search  /usr/share/i18n/SUPPORTED "^gl_ES.UTF-8.*$"
local:
    True
```

keep in mind this:

```shell
root@backup:~# egrep -o " (UTF-|ISO-....).*$" /usr/share/i18n/SUPPORTED | sort | uniq -c
     83  ISO-8859-1
      1  ISO-8859-10
      3  ISO-8859-13
      1  ISO-8859-14
     35  ISO-8859-15
      9  ISO-8859-2
      2  ISO-8859-3
      2  ISO-8859-5
     17  ISO-8859-6
      2  ISO-8859-7
      2  ISO-8859-8
      3  ISO-8859-9
    256  UTF-8
```

**Comment by diego-XA** [comment]
**WORKAROUND**

Declare the locales like this:

```yaml
gl_ES.UTF-8 UTF-8:
  locale.present

pt_PT.UTF-8 UTF-8:
  locale.present

pt_BR.UTF-8 UTF-8:
  locale.present

en_US.UTF-8 UTF-8:
  locale.present
```
