### ISSUE TITLE
Globally target a subset minions in state.orchestrate

### ISSUE THREAD

**Issue by baconz** [saltstack/salt#23242]
Consider an orchestration state wherein you are targeting a set of minions by role. Take this example:

``` yaml
cmd.run:
  salt.function:
    - tgt: 'role:auth_servers'
    - tgt_type: grain
    - arg:
      - update_auth

cmd.run:
  salt.function:
    - tgt: 'role:web_servers'
    - tgt_type: grain
    - arg:
      - update_web
   - require:
      - cmd: update_auth
```

Now imagine that you run redundant servers across two different data centers, and you don't want to update both data centers at the same time. Maybe you want to be able to fall back to datacenter B, if the update goes awry at datacenter A. It would be great if you could further filter the minions when you are calling orchestrate. Something like:

```
salt-run state.orchestrate orchestration.updater minions=G@roles:datacenterA
```
