### ISSUE TITLE
Salt-cloud: Configuration of IP / box specific settings

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#23313]
A question. The example lists IP configuration in the profile (`cloud.profiles.d`). 
This makes it less flexible as it would require a profile *per server* rather than per server type.

For instance, I'd like to spin up 10 boxes all with Ubuntu 14.04. 
In the current setup I am required to create 10 separate `cloud.profiles.d`-files rather than one "ubuntu-14.04" profile that can be applied to all 10 boxes.

**Comment by techhat** [comment]
Hi @syphernl. Unless I'm missing something here, I think that a cloud map may provide to you what you need, since it allows you to take generic profiles, and add minion-specific information to that.
As for the IP configuration, which example are you referring to? A specific IP address is not usually listed in a profile; if it is listed at all, it is usually in the cloud map.

**Comment by syphernl** [comment]
Hi @techhat. The (example) profile for the [VMware driver](http://docs.saltstack.com/en/latest/topics/cloud/vmware.html#profiles) contains several box-specific parameters (e.g. ip, cpu, memory, disk) which IMHO shouldn't necessarily be in a `cloud.profile` as they are generally "generic" templates (e.g. ubuntu 14.04, Debian8.0 etc)

For the above, how would one specify the box/minion-specific parameters in the cloud map?

**Comment by nmadhok** [comment]
@syphernl Specify the common fields which are going to be common to all VM's and templates in the profile and the VM specific fields in the map. 

Sample profile:
```
vmware-rhel:
  provider: example-vmware
  clonefrom: rhel6.5_template

  ## Optional arguments
  num_cpus: 2
  memory: 1024
  devices:
    disk:
      Hard disk 1:
        size: 15
    network:
      Network adapter 1:
        ip: 10.0.0.10
        gateway: [10.0.0.1]
        subnet_mask: 255.255.0.0
        domain: example.com
        name: VM Network
        switch_type: standard
    scsi:
      SCSI controller 1:
        type: paravirtual

  domain: example.com
  dns_servers:
    - 8.8.8.8
    - 8.8.4.4

  # If cloning from template, either resourcepool or cluster MUST be specified!
  resourcepool: Resources
  cluster: example

  datastore: 'vmexp01:storage1'
  folder: vm
  datacenter: example
  host: vmtest.example.com
  template: False
  power_on: True

  deploy: True
  private_key: /root/.ssh/id_rsa
  ssh_username: example
  password: 'SNIP'
  minion:
    master: SNIP
```

Sample Map:
```
vmware-rhel:
  - salt-rhel-1
  - salt-rhel-2
  - salt-rhel-3:
      num_cpus: 4
      memory: 8192
```

**Comment by philipsd6** [comment]
@nmadhok Your example would still spin up three VMs with the same IP address. I've already tried to override the IP address in a map, but it's not possible unless you override the entire devices key. For example, *this* does not work:
```yaml
vmware-rhel:
  - salt-rhel-1:
      devices:
        network:
          Network adapter 1:
            ip: 10.0.0.10
  - salt-rhel-2:
      devices:
        network:
          Network adapter 1:
            ip: 10.0.0.11
  - salt-rhel-3:
      devices:
        network:
          Network adapter 1:
            ip: 10.0.0.12
```
The resulting dict isn't merged with the profile, it replaces the devices key, so you have to copy the entire devices key, just to override that one item:
```yaml
vmware-rhel:
  - salt-rhel-1:
      devices:
        disk:
          Hard disk 1:
            size: 15
        network:
          Network adapter 1:
            ip: 10.0.0.10
            gateway: [10.0.0.1]
            subnet_mask: 255.255.0.0
            domain: example.com
            name: VM Network
            switch_type: standard
        scsi:
          SCSI controller 1:
            type: paravirtual
  - salt-rhel-2:
      devices:
        disk:
          Hard disk 1:
            size: 15
        network:
          Network adapter 1:
            ip: 10.0.0.10
            gateway: [10.0.0.1]
            subnet_mask: 255.255.0.0
# ... You get the picture.
```

Deep dict merging can have its issues, but it's sure annoying to not be able to abstract the majority of that data up into the profile. You can leverage some jinja templating maybe, but that still makes for a potentially massive map file.

Is there a better way to do this?
