### ISSUE TITLE
salt-ssh 2015.2.0-1187-gb224d82 requires zmq, why?

### ISSUE THREAD

**Issue by philipsd6** [saltstack/salt#23340]
```bash
[root@master salt]# salt-ssh --version
salt-ssh 2015.2.0-1187-gb224d82 (Lithium)
[root@master salt]# salt-ssh -W --list server01 cmd.run hostname
server01:
    ----------
    retcode:
        0
    stderr:
        ...snip...
          File "/tmp/.e3ee77/salt/transport/client.py", line 12, in <module>
            from salt.utils.async import SyncWrapper
          File "/tmp/.e3ee77/salt/utils/async.py", line 10, in <module>
            import zmq.eventloop.ioloop
        ImportError: No module named zmq.eventloop.ioloop
    stdout:
```
I regenerated thin.tgz specifying zmq, but I get a different error, because zmq isn't compiled for the target system.

**Comment by rallytime** [comment]
Thanks for the report @philipsd6. It looks like you're running this off of the develop branch. I am wondering if perhaps the transport changes @jacksontj made somewhat recently are causing things. What do you think, @basepi?

**Comment by basepi** [comment]
ZMQ should definitely not be required for salt-ssh, and this is in fact probably a side effect of the new transport system. We'll get it fixed.

**Comment by basepi** [comment]
Fixed in #23750.

Keep me posted if that doesn't resolve it for you.

**Comment by philipsd6** [comment]
Verified fixed in:
```yaml
root@NCEVC-SALT01057:/etc/salt# salt-ssh --versions-report
Salt Version:
           Salt: 2015.5.0-1331-g3124408

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.3.1
         Python: 2.7.8 (default, Oct 20 2014, 15:05:19)
           RAET: Not Installed
            ZMQ: 4.0.4
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
       pycrypto: 2.6.1

System Versions:
           dist: Ubuntu 14.10 utopic
        machine: x86_64
        release: 3.16.0-29-generic
         system: Ubuntu 14.10 utopic
```
Though I am still plagued by #23342 on the majority of my systems. :(
