### ISSUE TITLE
init.sls parsing issue

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#23359]
Hello

I tried to put some comments into the sls file but the parser failed. That is the output  I got:
```yaml
    Data failed to compile:
----------
    Rendering SLS 'dev:nfs' failed: Jinja syntax error: unexpected token '.'; line 85

---
[...]
      - file: /etc/netconfig
#  iptables.append:
#    - unless:
#      - iptables -nvL |grep "RPC traffic"
#
## the {% if .... %} ..... {% endif %}     <======================
## could be used as well. 
## unless state is available from 2014.7.0 version
#    - table: filter
#    - family: ipv4
#    - chain: INPUT
```
```yaml
 salt-master --versions-report
           Salt: 2014.7.5
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```
