### ISSUE TITLE
state webutil.user_exists - equivalent state/state option for userdel is missing?

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#23361]
Hello,

for modules there are 
- useradd
- useradd_all (=> whats the difference to user_add ? From documentation they are equal?)
- userdel

So it would be nice to have like for account, ssh states an option:
- present: False
- absent: True

It would be also nice to have an explicit "already encrypted" option... which is/can be the same functionality as 
- p Do not encrypt the password (plaintext).

EDIT: 
It would be also nice to be able to update the user password... 
Perhaps there can be the option "u" for it ? Or is it a state bug that updates are not possible ?

Bests

**Comment by Reiner030** [comment]
workaroud:

```
project:
  htpasswd:
    /etc/apache2/htpasswd:
      userone:
        password: $apr1$xAOqDYsi$lIsnUWRGbO/xCI77eJbKL0
        encrypted: True
      usertwo:
        password: tobechanged
      userthree:
        absent: True
```

```
{%- for htauth_file, htauth_content in salt['pillar.get']('project:htpasswd', {}).items() %}
{%-   for htauth_user, htauth_userdata in htauth_content.items() %}
{%-     if htauth_userdata.get ('password') != "None" and
           htauth_userdata.get ('present')  != False  and
           htauth_userdata.get ('absent')   != True       %}
httpasswd-user-{{ htauth_file }}-{{ htauth_user }}:
  webutil.user_exists:
    - name: {{ htauth_user }}
    - password: {{  htauth_userdata.get ('password') }}
    - htpasswd_file: {{ htauth_file }}
{%-       if htauth_userdata.get ('encrypted') == True %}
    - options: p
{%-       endif %}
{%-     else %}
httpasswd-user-{{ htauth_file }}-{{ htauth_user }}-absent:
  cmd.run:
    - name: salt-call webutil.userdel {{ htauth_file }} {{ htauth_user }}
{%-     endif %}
{%    endfor %}
{%- endfor %}
```

The state gave a Warning but it works within Debian without problems to set unencrypted passwords:
```
  Comment: Warning: storing passwords as plain text might just not work on this platform.
              Adding password for user userone
```
