### ISSUE TITLE
salt.runners.cloud.action fun parameter is replaced

### ISSUE THREAD

**Issue by iamfil** [saltstack/salt#23403]
When using salt.runners.cloud.action with Reactor, the fun argument is replaced. For example, the following sls should rename a ec2 instance:
```yaml
rename-ec2-instance:
  runner.cloud.action:
    - fun: rename
    - instances:
      - InstanceName
    - name: InstanceName
    - newname: NewInstanceName
```
but instead it will fail with:

```
'ec2.None' is not available. Not actioning...
```

This occurs because https://github.com/saltstack/salt/blob/develop/salt/state.py#L549 replaces the fun specified in the sls with cloud.action.

Changing the 'fun' parameter in http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.cloud.html#salt.runners.cloud.action to something else such as 'action' and also using 'action' instead of 'fun' in the above sls allows for this to work. Not sure if this the best way to fix this though. If it is, I can submit a patch. I believe other runners that use the fun parameter will run into a similar issue.
