### ISSUE TITLE
Document how to purposefully fail a state run if Pillar requirements are not met

### ISSUE THREAD

**Issue by samart** [saltstack/salt#23402]
If you throw an exception in a custom ext_pillar, highstate still runs.  Is it possible to control this behavior somehow, or by default, fail the state run due to this?

This could lead to data integrity issues?

There are workarounds, but it would be nice if there was some native way to stop on errors.

**Comment by jfindlay** [comment]
@samart, quoting @whiteinge:

You can use jinja to look in the pillar dict for errors and make a deliberate jinja syntax error if so.  You could also wait for this guy's pull req to be sent: https://twitter.com/0xf10e/status/591611597568811008.

**Comment by samart** [comment]
I'm thinking of running a pillar_checker.sls that runs first and fails fast the whole state run if some static pillar data that is only in the ext_pillar data is not present.  (i.e. it would essentially be an assertion that ext_pillar was successfully retrieved)

**Comment by whiteinge** [comment]
The above-mentioned checker was submitted to salt here:

https://github.com/saltstack/salt/pull/23462/files

**Comment by ketzacoatl** [comment]
@jfindlay / @whiteinge - How does this issue related to #31541? are they different, or should one take precedence over the other?

**Comment by whiteinge** [comment]
This is expected behavior and recent versions of Salt now have good ways to check for required values. The SLS author should provide checks for whether the state run should fail or not if required data is missing.

If the check needs to happen at the Jinja step:
```jinja
{% set some_test = salt.pillar.get('some_val') %}
{% do salt.test.assertion(some_test) %}

use_some_val:
  cmd.run:
    - name: |
        echo 'Got some_val: {{ some_val }}'
```

If the check can happen at the state-run step:
```yaml
check_req'd_vals:
  test.check_pillar:
    - present:
      - some_val
    - failhard: True

use_some_val:
  cmd.run:
    - name: |
        echo 'Got some_val: {{ salt.pillar.get('some_val') }}'
```

Or if an implicit check is ok, a direct lookup will fail because it is undefined (usually not a good idea to rely on this):
```yaml
use_some_val:
  cmd.run:
    - name: |
        echo 'Got some_val: {{ pillar.some_val }}'
```

The reason this is expected behavior is because compiling Pillar happens on the Salt Master and executing a State run happens on the Minion -- the two operations are completely decoupled. State runs often use Pillar, of course, but not always and it's not always clear which values from Pillar are required or not. Having the SLS author provide checks is simpler and more explicit.

Relabeling this as a documentation addition.

**Comment by whiteinge** [comment]
@jacobhammons add the above to the state docs, por favor?

**Comment by ketzacoatl** [comment]
@whiteinge, Thanks for the examples and references to the various test and assertion capabilities. The last portion of your comment (about the salt master/minion split) makes me wonder - would you make any additional comments (or changes to your comments above), if the context was just masterless with `salt-call --local`?

**Comment by whiteinge** [comment]
It's a good question because you're right, it doesn't feel like separate steps in masterless mode and there's easier opportunity to add a local, Pillar-specific check. So I _think_ that Salt reuses the same code paths for this workflow in either master/masterless modes (that is often the case for masterless operations). However even if it does not, IMO an SLS file should ideally execute the same way regardless if it is executing in one configuration or the other. An author or user should be able to expect the same behavior regardless.

**Comment by ketzacoatl** [comment]
Right, that makes sense.

Also, I think there is a slight difference between "fail if a pillar key is missing", and "fail if an external pillar provider fails", though I think it's sensible to turn this issue into a doc update for the former, and leave #31541 for the latter.

**Comment by minusf** [comment]
Let's say I have the following pillar:

```
enabled_service:
  param1: p1
  param2: p2

#disabled_service:
#  param3: p3
#  param4: p4

not_enabled_service:
  enabled: False
  param5: p5
```
or even

```
services:
  service1: True
  service2: False

service1:
  param1: p1

service2:
  param2: p2
```

I think what is missing from here is for `test.check_pillar` to check for actual values. Yes, I could check for the existence of the whole dictionary of `enabled_service` or `disabled_service` and `failhard` based on that.  But it's not possible to check for `not_enabled_service:enabled`, because `check_pillar` can check only presence and some types.

While the jinja check can get the pillar item `not_enabled_service:enabled`, the assertion is a big scary red wall of a text that kind of hides the issue, unless one knows more than basic python.

Possible solution no1 is to add more logic to `check_pillar`:

```
some test:
  test.check_pillar:
    - name: name
    - value: True
```

Possible solution no2 is to add custom human friendly exception message to `salt.test.assertion`:

```
{% do salt.test.assertion(some_test, "service not enabled") %}
```

It seems to be surprisingly difficult to make a state fail early with some nice error message about what just happened...  But I am very new to salt and coming from ansible, where this is fairly easy to do.
