### ISSUE TITLE
salt-cloud: Overriding deeply nested profile data in map files

### ISSUE THREAD

**Issue by philipsd6** [saltstack/salt#23416]
Per @nmadhok, continued from #23313:

[Getting Started With VMware](http://docs.saltstack.com/en/latest/topics/cloud/vmware.html#profiles) has an example profile with hardcoded IP addresses in a deeply nested key.

Sample profile:
```yaml
vmware-rhel:
  provider: example-vmware
  clonefrom: rhel6.5_template

  ## Optional arguments
  num_cpus: 2
  memory: 1024
  devices:
    disk:
      Hard disk 1:
        size: 15
    network:
      Network adapter 1:
        ip: 10.0.0.10
        gateway: [10.0.0.1]
        subnet_mask: 255.255.0.0
        domain: example.com
        name: VM Network
        switch_type: standard
    scsi:
      SCSI controller 1:
        type: paravirtual

  domain: example.com
  dns_servers:
    - 8.8.8.8
    - 8.8.4.4

  # If cloning from template, either resourcepool or cluster MUST be specified!
  resourcepool: Resources
  cluster: example

  datastore: 'vmexp01:storage1'
  folder: vm
  datacenter: example
  host: vmtest.example.com
  template: False
  power_on: True

  deploy: True
  private_key: /root/.ssh/id_rsa
  ssh_username: example
  password: 'SNIP'
  minion:
    master: SNIP
```
Obviously, you **must** change the IP address for each new VM, but it's not possible to override *only* the IP address in the map file. This does not work:

Sample map `/etc/salt/cloud.maps.d/fail.map`:
```yaml
vmware-rhel:
  - salt-rhel-1:
      devices:
        network:
          Network adapter 1:
            ip: 10.0.0.10
  - salt-rhel-2:
      devices:
        network:
          Network adapter 1:
            ip: 10.0.0.11
  - salt-rhel-3:
      devices:
        network:
          Network adapter 1:
            ip: 10.0.0.12
```
The resulting dict isn't merged with the profile, it replaces the devices key, so you have to copy the entire devices key, just to override that one item. This does work:

Sample map `/etc/salt/cloud.maps.d/meh.map`:
```yaml
vmware-rhel:
  - salt-rhel-1:
      devices:
        disk:
          Hard disk 1:
            size: 15
        network:
          Network adapter 1:
            ip: 10.0.0.10    # <-- first IP
            gateway: [10.0.0.1]
            subnet_mask: 255.255.0.0
            domain: example.com
            name: VM Network
            switch_type: standard
        scsi:
          SCSI controller 1:
            type: paravirtual
  - salt-rhel-2:
      devices:
        disk:
          Hard disk 1:
            size: 15
        network:
          Network adapter 1:
            ip: 10.0.0.11    # <-- second IP
            gateway: [10.0.0.1]
            subnet_mask: 255.255.0.0
# ... You get the picture.
```

Deep dict merging can have its issues, but it's sure annoying to not be able to abstract the majority of that data up into the profile. You can leverage some jinja templating maybe, but that still makes for a potentially massive map file.

Is there a better way to do this?

**Comment by jfindlay** [comment]
@philipsd6, @nmadhok, I am not familiar with the vmware code, but it does seem that `Network Adapter N: <IP>` could, without namespace or cognitive collision, be made a top level data element in the profile.

**Comment by nmadhok** [comment]
@jfindlay ``Network Adapter N: <IP>`` cannot be made a top level data element in the config since it requires other parameters to be specified such as subnet mask etc and it is something specific to each network adapter. 

@philipsd6 What if the user actually wants to override  ``devices`` completely in their map? If we merge and override only what they specify, they won't be able to completely override/replace the ``devices`` from their map. 

Also, this is something that applies to maps in general and not vmware cloud driver. Maps don't do a nested merge in general after it gets the config fields from the profile which is why you're having this issue.

**Comment by philipsd6** [comment]
I understand your point @nmadhok, but I believe the profile should only include the basic requirements; the fundamental requirements of the system it defines. So I'm thinking about potential use cases with that in mind.

##### Profile is setup without IP address/netmask, which means it'll use DHCP.
Map file wants to use manual IPs, so for obviously must set IP, netmask, and gateway manually. Deep dict merge overrides work perfectly.

##### Profile is setup with sample IP address/netmask and gateway.
Map file must override only the IP address, and maybe the netmask/gateway. Deep dict merge overrides again work perfectly.

##### Profile is setup with 23 Disks defined under devices
Map file only wants 2 Disks. Here's where it falls down. Deep dict merge override fails -- can't remove the extra Disks. 

But this is why I think the profile should be the base requirements for the system. Why would you define more disks or networks than required? It should only define the lowest common set of devices. Maps would only override or add. If you have a different set of base requirements, make a new profile.

Keep in mine, I am not strongly attached to this idea, and it's not a priority, since as demonstrated, you can just define the entire `devices` in the map file. An alternative could be to drop the `devices` and put `disk`, `network`, and `scsi` in the top-level, to minimize the impact of the current behavior.

**Comment by nmadhok** [comment]
@philipsd6 How about this:

Define your devices in the profile in the following way:
```
vmware-rhel:
  provider: example-vmware
  clonefrom: rhel6.5_template

  ## Optional arguments
  num_cpus: 2
  memory: 1024
  devices:
    disk:
      Hard disk 1:
        size: 15
    network:
      Network adapter 1:
        ip: 10.0.0.10
        gateway: [10.0.0.1]
        subnet_mask: 255.255.0.0
        domain: example.com
        name: VM Network
        switch_type: standard
    scsi:
      SCSI controller 1:
        type: paravirtual
```

Define your devices in the map in the following way:
```
vmware-rhel:
  - salt-rhel-1:
      disk:
        Hard disk 1:
          size: 15
      network:
        Network adapter 1:
          ip: 10.0.0.10    # <-- first IP
          gateway: [10.0.0.1]
          subnet_mask: 255.255.0.0
          domain: example.com
          name: VM Network
          switch_type: standard
      scsi:
        SCSI controller 1:
          type: paravirtual
  - salt-rhel-2:
      disk:
        Hard disk 1:
          size: 15
      network:
        Network adapter 1:
          ip: 10.0.0.11    # <-- second IP
          gateway: [10.0.0.1]
          subnet_mask: 255.255.0.0
```

So if you have ``disk``, ``network``, ``scsi``, ``cd`` or other devices specified in the top-level, they will override only that section in ``devices``.

**Comment by nmadhok** [comment]
@philipsd6 I actually tried with the existing code and here's what I noticed:

My profile:
```
vmware-rhel:
  provider: example-vmware
  clonefrom: rhel6.5_template

  ## Optional arguments
  num_cpus: 2
  memory: 1024
  devices:
    disk:
      Hard disk 2:
        size: 30
      Hard disk 3:
        size: 2
      Hard disk 4:
        size: 2
    network:
      Network adapter 1:
        name: 10.20.30-123-Test
        switch_type: distributed
```

My map file:
```
vmware-rhel:
  - salt-rhel-1:
      devices:
        disk:
          Hard disk 2:
            size: 40
```

My template has no NIC attached but it still added the NIC and resized the disks. This means that it did not override ``devices`` completely.

**Comment by philipsd6** [comment]
I tried this:

My profile:
```yaml
myvmware-rhel65:
  provider: myvmware
  clonefrom: rhel6.5_template

  ## Optional arguments
  num_cpus: 2
  memory: 8192
  devices:
    disk:
      Hard disk 1:
        size: 16
    network:
      Network adapter 1:
        name: VLAN0123
        switch_type: distributed
        type: vmxnet3
        ip: 10.10.10.10
        gateway: [10.10.10.1]
        subnet_mask: 255.255.255.0
        domain: muc.msp.amadeus.net
    scsi:
      SCSI controller 1:
        type: paravirtual
```
My map file:
```yaml
myvmware-rhel65:
  - salt-rhel-1:
      network:
        Network adapter 1:
          name: VLAN0123
          switch_type: distributed
          type: vmxnet3
          ip: 10.10.10.15
          gateway: [10.10.10.1]
          subnet_mask: 255.255.255.0
```
And I ended up with a `salt-rhel-1` vm that had an IP address of 10.10.10.10, so this didn't work for me.

**Comment by nmadhok** [comment]
@philipsd6 You did not specify ``network`` under ``devices`` in your map. Try the following map:

```
myvmware-rhel65:
  - salt-rhel-1:
      devices:
        network:
          Network adapter 1:
            name: VLAN0123
            switch_type: distributed
            type: vmxnet3
            ip: 10.10.10.15
            gateway: [10.10.10.1]
            subnet_mask: 255.255.255.0
```
