### ISSUE TITLE
grains.append should work at any level of a grain

### ISSUE THREAD

**Issue by dr4Ke** [saltstack/salt#23411]
I think we should be able to append values to a list at any level of a grain. Don't you?

An example:
Provided this grain:
```yaml
list:
  - val1
  - val2
```
The command `salt-call grains.append 'list' 'val3'` will update the grain to:
```yaml
list:
  - val1
  - val2
  - val3
```

With this grain, however:
```yaml
mygrain:
  var: somevalue
  list:
    - val1
    - val2
```
the command `salt-call grains.append 'mygrain:list' 'val3'` will give that output, which is correct, IMO:
```yaml
mygrain:list:
  - val1
  - val2
  - val3
```
but the grain `mygrain` is still:
```yaml
mygrain:
  var: somevalue
  list:
    - val1
    - val2
```

EDIT: Actually, there is a new grain `mygrain:list`, containing the complete list. This is weird:
```console
$ salt-call grains.get 'mygrain:list'
local:
    - val1
    - val2
$ salt-call grains.item 'mygrain:list'
local:
    - val1
    - val2
    - val3
```

**Comment by dr4Ke** [comment]
As a side question: maybe I shouldn't use nested grains?

**Comment by jfindlay** [comment]
@dr4Ke, nested grains should be supported.  I think you need to do a [module refresh](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.refresh_modules) after updating grains so that `grains.get` will be updated.  I do not know why `grains.item` does not need this or even why both these redundant functions exist. :-)

**Comment by dr4Ke** [comment]
Well, the fact is that the `/etc/salt/grains` file is updated and contains:
```
mygrain:
  list:
  - val1
  - val2
  var: somevalue
mygrain:list:
- val1
- val2
- val3
```

So I don't think it's a matter of a module refresh.
I have to add that I'm using salt 2014.7.5.
