### ISSUE TITLE
service.running

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#23417]
service running returns that state is change although comment says that nothing changed.

```
----------
          ID: postfix
    Function: service.running
      Result: True
     Comment: Service postfix is already enabled, and is running
     Started: 19:12:18.615437
    Duration: 2049.743 ms
     Changes:
              ----------
              postfix:
                  True
```
```
salt --version
salt 2014.7.4 (Helium)
```
```
salt-minion --version
salt-minion 2014.7.4 (Helium)
```
