### ISSUE TITLE
'Module_six_moves_urllib' object has no attribute 'Request'

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#23420]
'Module_six_moves_urllib' object has no attribute 'Request'
when running pkgrepo.managed on ubuntu 14.04.

```
    osfinger:
        Ubuntu-14.04
    osfullname:
        Ubuntu
    osrelease:
        14.04
    saltpath:
        /usr/lib/python2.7/dist-packages/salt
    saltversion:
        2015.2.0rc2-210-gf591a71
```

```
{{ sls }}:
    pkgrepo.managed:
            - humanname: pgdg PPA
            - name: deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main
            - dist: trusty-pgdg
            - file: /etc/apt/sources.list.d/pgdg.list
            - key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
```

```
          ID: mfcf.service.oat.db.postgresql_ha.package_9_4 package repo
    Function: pkgrepo.managed
        Name: deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main
      Result: False
     Comment: Failed to configure repo 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main': 
 >> 'Module_six_moves_urllib' object has no attribute 'Request'                                                                                                     
     Started: 19:50:03.236754
    Duration: 328.726 ms
     Changes:   
```
