### ISSUE TITLE
unless requisite not working correctly

### ISSUE THREAD

**Issue by allanliu** [saltstack/salt#23457]
salt-master: 2014.7.1 (Helium), CentOS 6
salt-minion: 0.17.5, Ubuntu 14.04.2 LTS

In my state file, I have this:

```
install_gvm:
  cmd.script:
    - name: gvm-installer.sh
    - source: salt://role/files/gvm-installer.sh
    - user: some_user
    - cwd: /home/some_user
    - shell: /bin/bash
    - unless:
      - ls /home/some_user/.gvm
    - require:
      - user: some_user

source_gvm:
  cmd.run:
    - name: source $HOME/.gvm/scripts/gvm
    - user: some_user
    - shell: /bin/bash
    - require:
      - cmd: install_gvm
```

However, even when '/home/some_user/.gvm' does not exist (the recode from 'ls /home/some_user/.gvm' is 2), the install_gvm does not execute.

Expected:
install_gvm should execute if /home/some_user/.gvm does not exist.
