### ISSUE TITLE
It would be great to have a file.insert functionality in a file state module

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#23463]
Something that looks similar to following existing methods: file.append and file.prepend, but where one could specify a 'location' as line number: 
A positive integer for line number from the beginning of the file
A negative integer for a line number from the end of the file

Example:

```
fileiwanttoinsertto:
  file.insert:
    - name: /tmp/file
    - source: salt://module/block.jinja
    - template: jinja
    - location: -2
```

This would insert a block at the second line from the end of file.

The method should support other file.append and file.prepend parameters: text, makedirs, source_hash, sources, source_hashes, defaults and context

Similarly to file.append and file.prepend, if a file doesn't exist - it will be created or if the block already exists in the file - it will not be inserted.
If a specified location (line number doesn't exist) - the block will be appended or prepended to a file.

Thoughts ?
