### ISSUE TITLE
import in pillar causes salt-run state.orchestrate to reset base

### ISSUE THREAD

**Issue by vr-jack** [saltstack/salt#23524]
Using an import in pillar, https://gist.github.com/vr-jack/d53733b554fb15b12bfd

Tried to do a salt-run state.orchestrate and received:

```
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://orchestrate/bootstrap.sls'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** u'salt://orchestrate/bootstrap/init.sls'
```

``` yaml
bootstrapper_master:
    Data failed to compile:
----------
    No matching sls found for 'orchestrate.bootstrap' in env 'base'
```

I created orchestrate/bootstrap.sls under the pillar base and it works. If I remove the import jinja, it works.

 It seems to effect the salt-master in a variety of places. salt * state.highstate also had issues finding include files in states.

```
    Specified SLS auth.config in saltenv base is not available on the salt master or through a configured fileserver
----------
    Specified SLS iptables.service in saltenv base is not available on the salt master or through a configured fileserver
```

``` yaml
salt --versions-report
           Salt: 2014.7.5
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```
