### ISSUE TITLE
grains.list_present produces incorrect (?) output

### ISSUE THREAD

**Issue by kkaig** [saltstack/salt#23548]
Assuming an empty grains file on the minion, and a state file on the master that contains the following:
```yaml
roles:
  grains.list_present:
    - value:
      - item1
      - item2
      - item3
```

I would expect it to produce the following output in the minion grain:
```yaml
roles:
  - item1
  - item2
  - item3
```

But instead it produces the following:
```yaml
roles:
- - item1
  - item2
  - item3
```

This has been confirmed by others on IRC. Salt version is 2014.7.5. Feel free to delete this if it's not a bug, or edit it in accordance with guidelines (it's my first report, and it's been a long day...)

Thanks
