### ISSUE TITLE
Salt-cp corrupting the file after transfer to minion

### ISSUE THREAD

**Issue by rks2286** [saltstack/salt#23566]
I was evaluating salt for one of my projects and was testing the salt-cp to send a small exe/msu file to one of the minions.
Though the files sent was successful from master to minion but it seems the file is getting corrupted. If I just do a binary copy of the file to the minion system via winscp tool and run it it works very fine.

Example command which I used:
```
salt-cp -t 200 '*' "/opt/NDP451-KB2858728-x86-x64-AllOS-ENU.exe" "C:\TEMP\NDP451-KB2858728-x86-x64-AllOS-ENU.exe" -l debug
```

Salt version details from Master
```yaml
# salt --versions-report
           Salt: 2014.7.5
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
         Jinja2: 2.5.5
       M2Crypto: 0.21.1
      msgpack-python: 0.4.5
      msgpack-pure: Not Installed
       pycrypto: 2.3
        libnacl: Not Installed
         PyYAML: 3.08
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

Things tried to fix the issue:

Updated below two files to add a binary flag so that the files wont get corrupted but this change also did not help.

/usr/lib/python2.6/site-packages/salt/cli/cp.py
/usr/lib/python2.6/site-packages/salt/modules/cp.py

Link of the salt-users group discussion about the issue.
https://groups.google.com/d/msg/salt-users/g0YMUQjrWkk/ZImAO94CQzEJ
