### ISSUE TITLE
Failed to Deploy Salt-Minion on a Win 2012 R2 using wmware Cloud Driver from Develop branch

### ISSUE THREAD

**Issue by CedNantes** [saltstack/salt#23574]
Hi, i've had the same error as https://github.com/saltstack/salt/issues/20362 :
```
SaltCloudSystemExit: Cannot deploy salt in a VM if the 'ssh_keyfile' setting is not set and there is no password set for the vm. Check your provider for the 'change_password' option.
```
I'm using salt 2014.7.5 but i'm using the dev version of the vmware cloud driver : https://raw.githubusercontent.com/saltstack/salt/develop/salt/cloud/clouds/vmware.py

Here's my provider :
```yaml
Vcenter:
  provider: vmware
  user: myuser
  password: mypassword
  url: "providerIP@dress"
```

here's my profile :
```yaml
Test-Win2K12:
  provider: Vcenter
  clonefrom: winsrv2012template
  resourcepool: myresourcepool
  datastore: mydatastore
  power_on: True

  deploy: True
  use_winrm: True
  win_installer: /tmp/Salt-Minion-2014.7.5-AMD64-Setup.exe
  win_username: user
  win_password: password
  smb_port: 445
```
I tried with the old vmware driver from 2014.7 and it was trying to use winexe and was failing with error "1" on a 2012R2 so i guessed "use_winrm" was only available for the new driver but here i'm stuck... Is there any workaround ? And also i'm new to github (that's my first issue and i've posted a few comment/questions before) so i don't know if creating an issue was ok. Thx in advance for your answers.
