### ISSUE TITLE
As of 2015.5.0, docker 1.5.0 cannot be used with quay.io (and presumably others)

### ISSUE THREAD

**Issue by tkent-xetus** [saltstack/salt#23612]
After upgrading to docker 2015.5.0 the `docker.running` and `docker.installed` states always return an error in the following form for quay.io/\* images, when using docker 1.5.0.

```
image "quay.io/xyz/abc" does not exist
```

It's unlikely this is specific to quay.io, since the images are already locally downloaded on the minions when this error occurs. This appears to be due to the combination to #23610 and #13305.

We were able to work around the issue by upgrading to docker 1.6.1, but that might not be an option for everyone.

In case it's helpful here's the docker and salt information:

``` yaml
salt-call --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1

docker --version
Docker version 1.5.0, build a8a31ef
```
