### ISSUE TITLE
As of 2015.5.0 image is required with docker.running

### ISSUE THREAD

**Issue by tkent-xetus** [saltstack/salt#23610]
Prior to salt 2015.5.0, image was not required for the `docker.running` state. So a state that looked like this worked just fine:

``` yaml
example-container-running:
  require:
    - docker: example-container-installed
  docker.running:
    - container: example-container
```

Now that same state will produce an error that `image` is required missing. This breaks backwards compatibility with the previous versions.

Ideally, if the container being started already exists (created from the docker.installed state, for example), the container's associated image is assumed.

**Comment by jfindlay** [comment]
@tkent-xetus, thanks for the report.

**Comment by immunda** [comment]
@tkent-xetus Do you have a current work around for this? Just provide the image as defined in `example-container`?

**Comment by tkent-xetus** [comment]
@immunda  Correct! If you specify the `image` key your states will work - it's just a pain to update/test all your formulas.

So, to be clear, to work around the problem in the example I posted, one would use something like:

```
example-container-installed:
  docker.installed:
    - name: example-container
    - image: some/image

example-container-running:
  require:
    - docker: example-container-installed
  docker.running:
    - container: example-container
    - image: some/image
```

(A related warning though, if your images use a tag specifier _do not_ use the `tag` key in the docker.installed or the docker.running states. They won't work properly if you do. You have to specify the tag as part of the `image` value in the traditional docker way of 'image/path:TAG'. That's another issue I need to find time to document)
