### ISSUE TITLE
file.managed with proxy broken in 2015.5

### ISSUE THREAD

**Issue by porterjamesj** [saltstack/salt#23617]
Hey all, I have a state that looks something like this:

``` yaml
unzip:
  pkg.installed

http_proxy:
  environ.setenv:
    - value: 'http://proxy-url'

https_proxy:
  environ.setenv:
    - value: 'https://proxy-url'

/usr/local/bin/consul_dir:
  archive.extracted:
    - source: https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip
    - archive_format: zip
    - source_hash: sha256=161f2a8803e31550bd92a00e95a3a517aa949714c19d3124c46e56cfdc97b088
    - require:
        - environ: http_proxy
        - environ: https_proxy
        - pkg: unzip
```

where `proxy-url` is a standin for the actual url of my http proxy. With a 2014.7 minion the archive extracted fine, with a  2015.5 minion, I get:

``` yaml
----------
          ID: /usr/local/bin/consul_dir
    Function: archive.extracted
      Result: False
     Comment: Unable to manage file: [Errno 111] Connection refused
     Started: 17:58:15.121916
    Duration: 420.282 ms
     Changes:
----------
```

Debugging with salt-call, this appears to be happening [here](https://github.com/saltstack/salt/blob/2015.5/salt/utils/http.py#L286), it looks like the new utils.http doesn't use the `http_proxy` and `https_proxy` environment variables, whereas whatever was responsible for the http calls in 2014.7 did.

**Comment by jfindlay** [comment]
@porterjamesj, thanks for the report.

**Comment by garo** [comment]
Noticed the same problem after spending way too many hours wondering why my proxy settings doesn't take any effect.

**Comment by gboddin** [comment]
Same issue here, it's a blocker when you're working in a proxy controlled environment.

**Comment by danielkraemer** [comment]
Same issue with file.managed, but only with https

**Comment by jfindlay** [comment]
I've changed the title of this issue because `archive.extracted` uses `file.managed` and the problem has been confirmed with `file.managed` itself.

**Comment by The-Loeki** [comment]
It used to work if you set `requests_lib: True` in the minion conf, however in Beryllium this seems broken, and Tornado HTTP client won't pick up on it either unless it's switched over to `curl_httpclient`.

**Comment by The-Loeki** [comment]
Related to #8177

**Comment by nlm** [comment]
It would be nice that salt honors properly all the protocol_proxy environment variables in salt-minion with all the backends it uses:
- http_proxy
- https_proxy
- ftp_proxy
and possibly other protocols supported by salt.

It seems that most of this can be fixed in salt.fileclient or salt.utils.{http,s3,...}

**Comment by JensRantil** [comment]
Workaround:

```
download-my-file:
  cmd.run:
    - name: "wget -q -O /srv/my-file.tgz http://somedomain/my-file.tgz"
    - creates: /srv/my-file.tgz
    - env:
      - http_proxy: "my-proxy.domain.com"
```

Clearly, this doesn't add any hashsum, so it's less secure.
