### ISSUE TITLE
salt state 'ssh_known_hosts' doesn't take 'port' into account

### ISSUE THREAD

**Issue by mirko** [saltstack/salt#23626]
content of salt state file:
```yaml
bck:
  ssh_known_hosts:
    - present
    - port: 23425
    - fingerprint: XX:YY:ZZ
    - enc: rsa
    - user: bck
    - hash_hostname: False
    - require:
      - user: bck
```

expected result:
```
[bck]:23425 ssh-rsa AAAA...
```

actual result:
```
bck ssh-rsa AAAA...
```
