### ISSUE TITLE
salt-ssh

### ISSUE THREAD

**Issue by mirko** [saltstack/salt#23628]
What's best practice to define **persistent** grains when using salt-ssh?

The way I used to define them when I was running salt-minion on the minions doesn't work ( /etc/salt/minion / /etc/salt/minion.d/*.conf )

The way of setting them via salt directly - e.g.
```
roles:
  grains.present:
    - value:
      - managed
```
works, however those information then get saved in /tmp/ which is not persistent.
Any way to define them on the minions themselves (except using ```file.managed```)?

Thanks a lot in advance!

**Comment by cachedout** [comment]
This might well be functionality that needs to be added, since I'm not certain there's a way to do this currently.

cc: @basepi Any thoughts here?

**Comment by basepi** [comment]
You can now define minion opts inside of your roster file:

```
myfirstminion:
  host: 127.0.0.1
  user: root
  minion_opts:
    gpg_keydir: 
    grains:
      mypersistentgrain: True
```

However, this functionality didn't make it into the 2015.5.0 release, it will be in 2015.5.1.

**Comment by basepi** [comment]
Note: you can also define minion opts for *all* of your salt-ssh minions with the `ssh_minion_opts` option in the master config.

**Comment by mirko** [comment]
Thanks for the ```ssh_minion_opts```-pointer, however I'm indeed looking for a way to distinguish minions by respective grains

**Comment by mirko** [comment]
Did it already get committed somewhere? I just scrolled through the branches 'develop' and '2015.05' however failed to find anything related..

**Comment by basepi** [comment]
Originated here: https://github.com/saltstack/salt/pull/23272

Has since been merged forward to 2015.5 and develop. Will be in 2015.5.1.

**Comment by basepi** [comment]
To clarify -- does the roster option solve your use case? Or are you looking for something else?

**Comment by mirko** [comment]
As far as I understand how it works it perfectly does. Thanks a lot!

**Comment by basepi** [comment]
Awesome! Comment here if (once released) it doesn't meet your needs! =)

**Comment by pirogoeth** [comment]
@basepi I know this is long, long closed, but `minion_opts` in the roster are not appearing in a `grains.items` call on 2015.8.0 on a FreeBSD host (in case that's somehow relevant). Should I file a new issue for this?

**Comment by basepi** [comment]
@pirogoeth Can you post your rosterfile first so I can just make sure I don't spot any issues before we open a new one?

**Comment by pirogoeth** [comment]
@basepi Sure. 

```
alpha.maio.me:
  host: alpha.maio.me
  user: pirogoeth
  port: 55213
  sudo: True
  minion_opts:
    grains:
      roles:
        - charybdis
      minimal: True
      deployment: digitalocean
beta.maio.me:
  host: beta.maio.me
  user: pirogoeth
  port: 55213
  sudo: True
  minion_opts:
    grains:
      roles:
        - nginx
        - supervisor
      minimal: True
      deployment: digitalocean
omega.maio.me:
  host: omega.maio.me
  user: local
  port: 22
  sudo: True
  minion_opts:
    grains:
      roles:
        - nginx
        - docker
        - dokku
      minimal: True
      deployment: baremetal
```
