### ISSUE TITLE
Obscure error "Invalidly-formatted 'env' parameter" when cmd.script source is invalid

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#23631]
When cmd.script is used with an invalid script source, a obscure error is thrown.

```
          ID: set-environment-tag
    Function: cmd.script
      Result: False
     Comment: Invalidly-formatted 'env' parameter. See documentation.
     Started: 23:07:53.409000
    Duration: 0.0 ms
     Changes:  
```

**Comment by cachedout** [comment]
Could you please clarify what you mean by "invalid"? Do you mean the script can't be parsed, or it doesn't exist, or some other condition?

**Comment by mostafahussein** [comment]
I am facing the same issue with `cmd.run`:

```
Invalidly-formatted 'env' parameter. See documentation.
```

```yaml
start_my_command:
  cmd.run:
    - name: foo
    - env: "PATH=/usr/local/sbin:$PATH"
    - shell: {{ grains.shell if 'shell' in grains else '/bin/bash' }}
```

```
----------
          ID: start_my_command
    Function: cmd.run
        Name: foo
      Result: False
     Comment: Invalidly-formatted 'env' parameter. See documentation.
     Started: 05:01:51.251602
    Duration: 0.553 ms
     Changes: 
```
I see no differences between my example and that one at the docs

```yaml
script-bar:
  cmd.run:
    - env: "PATH=/some/path:$PATH"
```
