### ISSUE TITLE
rabbitmq module functions are not available immediately (requires minion restart) after installing rabbitmq package

### ISSUE THREAD

**Issue by rvora** [saltstack/salt#23630]
After installing rabbitmq-server, use of rabbitmq.add_vhost or other module functions fails with "Module function rabbitmq.add_vhost is not available" error.

```yaml
rabbitmq-server:
  pkg.installed: []

# use rabbitmq module
rabbitmq_add_vhost:
  module.run:
    - name: rabbitmq.add_vhost
    - vhost: '/sensu'

# use rabbitmq_vhost state
rabbitmq_vhost.present:
  - vhost: '/sensu'
```

Both module and state functions fail unless salt-minion is restated after installing rtabbitmq-server.

This can be verified by running "salt-call sys.list_functions | grep rebbitmq" which comes up empty. Once salt-minion is restarted, you can use all the rabbitmq functions.

I believe this bug might be introduced by this commit by @s0undt3ch if I am not mistaken: https://github.com/saltstack/salt/commit/7d114ac4ecb397d641ad4e68975a5f44303d1192

Since rabbitmq-server is not installed on the salt-minion initially, salt.utils.which('rabbitmqctl') will obviously return None thus rabbitmq.py:__virtual__() returning False and preventing rabbitmq.py module from being loaded. A minion restart after installing rabbitmq-server will obviously fix this problem.

What is the harm in loading rabbitmq module when Rabbitmq is not installed?

**Comment by rvora** [comment]
Its easy to reproduce and confirms that you can not install rabbitmq and manage rabbitmq all in one go without restarting salt-minion. Or is there something I am missing.

Create a new instance on AWS/OpenStack with a standard image.

SSH into the instance, Install salt-minion, then run:

# should return no output
salt-call --local sys.list_modules | grep rabbit
salt-call --local sys.list_state_modules | grep rabbit

Create another instance with following Startup script (passed as User-data)
#!/bin/bash
touch /usr/local/bin/rabbitmqctl
chmod 755 /usr/local/bin/rabbitmqctl

Now, SSH into the instance, Install salt-minion, then run:

# should return all the rabbitmq modules
salt-call --local sys.list_modules | grep rabbit
salt-call --local sys.list_state_modules | grep rabbit

**Comment by jfindlay** [comment]
@rvora, thanks for the report.  Something you could try as a workaround is to [reload the salt modules](http://docs.saltstack.com/en/latest/ref/states/index.html#reloading-modules).

```yaml
rabbitmq-server:
  pkg.installed:
    - name: rabbitmq-server
    - reload_modules: True

# use rabbitmq module
rabbitmq_add_vhost:
  module.run:
    - name: rabbitmq.add_vhost
    - vhost: '/sensu'

# use rabbitmq_vhost state
rabbitmq_vhost.present:
  - vhost: '/sensu'
```
