### ISSUE TITLE
Windows: onfail doesn't work on Lithium

### ISSUE THREAD

**Issue by leapyleigh** [saltstack/salt#23646]
onfail is being ignored in salt state files but only on Windows minions. It does work as expected in Helium. Here is an example:

```yaml
ensure agent is running:
    service.running:
        - name: "salt-minion"
        - enable: True

install agent:
    cmd.run: 
        - onfail: 
            - service: ensure agent is running
        - name: hostname
```
