### ISSUE TITLE
salt-cloud puts minion keys on incorrect masters

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#23699]
Given the following configuration:

```
linode_ubuntu14:
  - student01:
      make_master: True
      location: 9
      minion:
        master: localhost
        local_master: True
  - student02:
      make_master: True
      location: 9
      minion:
        master: localhost
        local_master: True
  - student03:
      make_master: True
      location: 9
      minion:
        master: localhost
```

I would expect that each of the three minions would have a master and a minion, which they all do. However, the public keys for `student02` and `student03` are _also_ being placed on `student01`, which I think is incorrect. Here is `salt-key` on `student01`

```
Accepted Keys:
student01
student02
student03
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```
