### ISSUE TITLE
cmdmod: enhancement is really needed for stateful commands

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#23709]
Consider
```

aaa:
  cmd.run:
    - name: 'echo "there was a big problem";/bin/false'
    - stateful: true

```
This actually results in 
```
local:
----------
          ID: aaa
    Function: cmd.run
        Name: echo "there was a big problem";/bin/false
      Result: False
     Comment: Failed parsing script output! Stdout must be JSON or a line of name=value pairs.
     Started: 15:49:30.257597
    Duration: 5.761 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1

```
Which is a bit awful to track down as the only mean is to parse the minion log, and hope that the log level was enougth

We should really grab back all the output from the commands back to the changes dict, like the regular cmdrun, in case of a false return.

Im going to see if i can implement it.

cc @thatch45
