### ISSUE TITLE
service.dead is no more stateful

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#23713]
on a ubuntu/trusty host
```
firewalld-conflicting-services:
  service.dead:
    - names: [iptables, ebtables,
              shorewall, shorewall6]
    - enable: false

```
Where  a shorewall6 upstart job does not exists but where an /etc/init.d/shorewall6 exists

```
----------
          ID: firewalld-conflicting-services
    Function: service.dead
        Name: shorewall
      Result: True
     Comment: Service shorewall is already disabled, and is dead
     Started: 16:34:20.959354
    Duration: 21.164 ms
     Changes:
              ----------
              shorewall:
                  True
```

Even if the service is already dead && disabled.
