### ISSUE TITLE
cache_file not working from the init.sls

### ISSUE THREAD

**Issue by tganzeboom** [saltstack/salt#23768]
Got this in the init.sls:
```yaml
ntp:
  4.2.8:
    installer: 'salt://win/repo/ntp/ntp-4.2.8-win32-setup.exe'
    full_name: Meinberg NTP Windows Client
    locale: en_US
    reboot: False
    cache_file: 'salt://win/repo/ntp/install.ini'
    install_flags: '/USEFILE=C:\salt\var\cache\salt\minion\files\base\win\repo\ntp\install.ini'
    uninstaller: 'NTP/uninst.exe'
```
The directory `C:\salt\var\cache\salt\minion\files\base\win\repo\ntp` is made. The `install.ini` file is not there.

If I however run the command `salt -t 60 'MACHINENAME*' cp.cache_file salt://win/repo/ntp/install.ini -l all` it does work.
```yaml
salt --versions-report
           Salt: 2014.7.5
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```
Client is also 2014.7.5.
