### ISSUE TITLE
log output of salt orchestrate run changed between 2014.7.5 and 2015.5.0 significantly - hard to debug

### ISSUE THREAD

**Issue by hoonetorg** [saltstack/salt#23789]
see difference:
2014.7.5: https://gist.github.com/anonymous/c81f4445c5c94f9ed0f5

2015.5.0: https://gist.github.com/anonymous/41f6b28cecde6cef5129

System CentOS 7.1:
Salt packages from EPEL (2015-05-15)

On master:
```console
[root@hperhlws0802 orchestration]# rpm -qa |grep salt 
salt-2015.5.0-1.el7.noarch
salt-master-2015.5.0-1.el7.noarch
salt-minion-2015.5.0-1.el7.noarch
```
Difficult to debug, because , 
1. Output is not ordered in the order of execution
2. Some information is missing
3. I'm generally missing some output of some orchestration states (probably I oversee because of the reordering)

P.S.: Me feeling they are reordered by name of orchestration state

**Comment by rallytime** [comment]
Thanks for the report @hoonetorg. I am not super familiar with using the orchestrate state, but I bet @whiteinge might have some good input here.

**Comment by whiteinge** [comment]
The orchestrate output is not getting run through the `highstate`
outputter in that gist. That is a definite bug and regression. There
was a similar regression in the jobs runner for
state.highstate/state.sls output in 2015.2. It may be related to the
switch to event-based runners.

**Comment by hoonetorg** [comment]
thanks for the quick answer.
I'm happy to test a patch on my environment, once available.

**Comment by ivan-californias** [comment]
Same problem over here.

To get a work around I am running salt-run command like this:
```
salt-run --out=highstate state.orchestrate
```
but I am getting a little bit different output, I mean in previous version I would gotten the stderr or stdout, but now I am just getting that the state failed and the result, like this:
```
                  ----------
                            ID: apache
                      Function: service.running
                        Result: False
                       Comment: Service apache is already enabled, and is dead
                       Started: 16:54:12.805440
                      Duration: 556.212 ms
                       Changes:   
                  apache:
                      False
                  ----------
```
When state is cmd.run I am getting just the PID, like this
```
                  ----------
                            ID: db-create-testdb
                      Function: cmd.run
                          Name: sudo -u postgres createdb --encoding=LATIN1 testdb
                        Result: False
                       Comment: Command "sudo -u postgres createdb --encoding=LATIN1 testdb" run
                       Started: 16:52:15.816972
                      Duration: 65.04 ms
                       Changes:   
                  pid:
                      8242
                  ----------
```

This makes it hard to debug as the issue tells. I'd also be happy to test a patch. Thanks in advance.
