### ISSUE TITLE
2014.7.5 schedule error

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#23820]
Here's my versions_report:

```
[boucha@elsapo davescripts]$ sudo salt '*' test.versions_report
dasalt:
               Salt: 2014.7.5
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.0.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed
```

I'm getting this error. It seems like the job is getting malformed somehow. Once it gets in this state I have to restart the minion service to get it to work again.

I tested this on the  2015.5.0 and  the following commands did work correctly, so it appears to be contained to the 2014.7 branch.

```
[boucha@elsapo davescripts]$ sudo salt '*' schedule.add test_job function='cmd.run' job_args=['/home/boucha/davescripts/incr.sh'] when='9:20PM'
dasalt:
    ----------
    comment:
        Added job: test_job to schedule.
    result:
        True
[boucha@elsapo davescripts]$ sudo salt '*' schedule.list
dasalt:
    The minion function caused an exception: Traceback (most recent call last):
      File "/home/boucha/salt/salt/minion.py", line 1020, in _thread_return
        return_data = func(*args, **kwargs)
      File "/home/boucha/salt/salt/modules/schedule.py", line 75, in list_
        if schedule[job][item] == 'true':
    KeyError: '_when_run'
[boucha@elsapo davescripts]$ sudo salt '*' schedule.enable
dasalt:
    ----------
    comment:
        Enabled schedule on minion.
    result:
        True
[boucha@elsapo davescripts]$ sudo salt '*' schedule.list
dasalt:
    The minion function caused an exception: Traceback (most recent call last):
      File "/home/boucha/salt/salt/minion.py", line 1020, in _thread_return
        return_data = func(*args, **kwargs)
      File "/home/boucha/salt/salt/modules/schedule.py", line 75, in list_
        if schedule[job][item] == 'true':
    KeyError: '_when_run'
```
