### ISSUE TITLE
Zip file extracted permissions are incorrect

### ISSUE THREAD

**Issue by sidcarter** [saltstack/salt#23822]
I'm using this state to install packer:

```
{% set version = '0.7.5' %}

packer:
  archive:
    - extracted
    - name: /usr/local/bin/
    - source: https://dl.bintray.com/mitchellh/packer/packer_{{version}}_linux_amd64.zip
    - source_hash: sha256=8fab291c8cc988bd0004195677924ab6846aee5800b6c8696d71d33456701ef6
    - archive_format: zip
    - if_missing: /usr/local/bin/packer
```

This state command itself worked fine without any issues, but then I noticed that the permissions were all wrong. 
```
# salt --version
salt 2015.5.0 (Lithium)
```
```
# ls -l
total 318964
-rw-r--r-- 1 root root 10087048 May 17 05:47 packer
-rw-r--r-- 1 root root 10293560 May 17 05:47 packer-builder-amazon-chroot
-rw-r--r-- 1 root root 11110464 May 17 05:47 packer-builder-amazon-ebs
-rw-r--r-- 1 root root 11146448 May 17 05:47 packer-builder-amazon-instance
-rw-r--r-- 1 root root 10437344 May 17 05:47 packer-builder-digitalocean
-rw-r--r-- 1 root root  9394712 May 17 05:47 packer-builder-docker
```

If I extracted the zip directly, I get this:

```
~/test# ls -l
total 318964
-rwxr-xr-x 1 root root 10087048 Dec 10 03:17 packer
-rwxr-xr-x 1 root root 10293560 Dec 10 03:17 packer-builder-amazon-chroot
-rwxr-xr-x 1 root root 11110464 Dec 10 03:17 packer-builder-amazon-ebs
-rwxr-xr-x 1 root root 11146448 Dec 10 03:17 packer-builder-amazon-instance
-rwxr-xr-x 1 root root 10437344 Dec 10 03:17 packer-builder-digitalocean
-rwxr-xr-x 1 root root  9394712 Dec 10 03:17 packer-builder-docker
```
I don't know of any options I can pass to fix this. Is this a bug?
