### ISSUE TITLE
salt-minion multiprocessing seems not working in 2015.5.0

### ISSUE THREAD

**Issue by chhsiao1981** [saltstack/salt#23821]
Hi salt developers,

It seems like I still get 3 salt-minions in starting the salt-minion,
and 2 salt-minions in general.

I am wondering whether the "2-salt-minion" processes are within expectation or not
if I've already setup multiprocessing as False?

os: ubuntu 12.04

The following is what I put in /etc/salt/minion:
```yaml
master: [master_ip]

master_type: str

verify_master_pubkey_sign: True

id: [hostname_as_id]

master_alive_interval: 600

multiprocessing: False

log_level: debug
```
