### ISSUE TITLE
State 'file.sed' was not found in SLS 

### ISSUE THREAD

**Issue by diego-XA** [saltstack/salt#23852]
Today I have upgraded to 2015.5. Everything was working with the previous version 2014.7, but now I have a problem with the 'file.sed' function. I reduced my sls file to a testing one to reproduce it. I am using this SLS (mytest.sls):

```
# vim: set ts=2 sw=2 sts=2 et:

php_ini_tokens-off:
  file.sed:
    - name: /etc/php5/fpm/php.ini
    - before: expose_php\s*=\s*On
    - after: expose_php = Off

php_ini_post-limit:
  file.sed:
    - name: /etc/php5/fpm/php.ini
    - before: post_max_size\s*=.*
    - after: post_max_size = 20M

php_ini_upload-limit:
  file.sed:
    - name: /etc/php5/fpm/php.ini
    - before: upload_max_filesize\s*=.*
    - after: upload_max_filesize = 20M
```

but it does not work. The output of executing this state in a minion (both from master or using salt-call from minion) is:

```
local:
----------
          ID: php_ini_tokens-off
    Function: file.sed
        Name: /etc/php5/fpm/php.ini
      Result: False
     Comment: State 'file.sed' was not found in SLS 'mytest'
     Started: 
    Duration: 
     Changes:   
----------
          ID: php_ini_post-limit
    Function: file.sed
        Name: /etc/php5/fpm/php.ini
      Result: False
     Comment: State 'file.sed' was not found in SLS 'mytest'
     Started: 
    Duration: 
     Changes:   
----------
          ID: php_ini_upload-limit
    Function: file.sed
        Name: /etc/php5/fpm/php.ini
      Result: False
     Comment: State 'file.sed' was not found in SLS 'mytest'
     Started: 
    Duration: 
     Changes:   

Summary
------------
Succeeded: 0
Failed:    3
------------
Total states run:     3
```

The file "/etc/php5/fpm/php.ini" exists and the log file with "trace" verbosity only says:
```
....

[DEBUG   ] Could not LazyLoad file.sed
[ERROR   ] State 'file.sed' was not found in SLS 'mytest'

.....
```

Regarding versions, both master and minions are debian wheezy. This is from the minion:

```
                  Salt: 2015.5.0
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2015.5.0+ds-1~bpo70+1
```
