### ISSUE TITLE
States work in /etc/salt/minion but not /etc/salt/grains due ot 

### ISSUE THREAD

**Issue by bnikolaus** [saltstack/salt#23941]
I use a grain to set an environment on my minions in the /etc/salt/minion but would like to start using /etc/salt/grains as its easier to manage.

I use the following environmental value in many of my states to determine which files to place in which environment like so.
```jinja
{% set environment = salt['grains.get']('env', '') %}
```
If I remove the grains for env from /etc/salt/minion and add it to the /etc/salt/grains it breaks all my file.managed source paths as its expecting a list indicated by the ['sys'] instead of a single value when using the /etc/salt/grains. Perhaps I am setting the value wrong but I would expect the same behavior from both files which is not the case. Let me know if there is a workaround.

Output::
```yaml
Name: /etc/supervisord.conf - Function: file.managed - Result: Clean
----------
          ID: /rtde/cron-runner/config/logback.xml
    Function: file.managed
      Result: False
     Comment: Source file salt://cron-runner/files/['sys']/logback.xml not found
     Started: 17:26:44.861932
    Duration: 3.564 ms
     Changes:  
----------
```
