### ISSUE TITLE
states.user/group unreliable with directory services

### ISSUE THREAD

**Issue by dmaziuk** [saltstack/salt#23947]
On the minion
- nsswitch.conf has "files sss ldap" for both user (passwd/shadow) and group
- user and group are not present in files
- user and group are present in ldap

Salt:

```
[root@nautilus ~]# salt -N condor state.highstate test=True
stingray.bmrb.wisc.edu:
----------
          ID: create_condor_group_please
    Function: group.present
        Name: condor
      Result: True
     Comment: Group condor is present and up to date
     Started: 17:32:39.702288
    Duration: 52.242 ms
     Changes:   
----------
          ID: create_condor_user_please
    Function: user.present
      Result: None
     Comment: User create_condor_user_please set to be added
     Started: 17:32:39.754689
    Duration: 2.371 ms
     Changes:   

Summary
------------
Succeeded: 2 (unchanged=1)
Failed:    0
------------
Total states run:     2
```

Note that user.present returns None. On the minion, from python prompt:

```
[root@stingray etc]# python
Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pwd
>>> print pwd.getpwnam( "condor" )
pwd.struct_passwd(pw_name='condor', pw_passwd='x', pw_uid=501, pw_gid=500, pw_gecos='CONDOR system user', pw_dir='/var/lib/condor', pw_shell='/bin/bash')
>>> print pwd.getpwuid( 501 )
pwd.struct_passwd(pw_name='condor', pw_passwd='x', pw_uid=501, pw_gid=500, pw_gecos='CONDOR system user', pw_dir='/var/lib/condor', pw_shell='/bin/bash')
>>> 
```

So whatever makes salt's user.present return None is not the underlying pwd module. Also note that group.present returns True: the group is in the same openldap database as the user.

Without "test=True":

```
[root@nautilus ~]# salt -N condor state.highstate 
stingray.bmrb.wisc.edu:
----------
          ID: create_condor_group_please
    Function: group.present
        Name: condor
      Result: True
     Comment: Group condor is present and up to date
     Started: 17:42:02.738490
    Duration: 2.36 ms
     Changes:   
----------
          ID: create_condor_user_please
    Function: user.present
      Result: False
     Comment: Failed to create new user create_condor_user_please
     Started: 17:42:02.740915
    Duration: 15.789 ms
     Changes:   

Summary
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
```

So the state system has a third state: user is not present and we can't add him. 

The reason we can't add him is the call to useradd that fails with "3 -- user already present" so this is another potentially broken piece: the check and the update rely on two completely separate code paths whose picture of system's state is not guaranteed to agree.

**Comment by dmaziuk** [comment]
PS. so I'm looking at the code for present() in states/user.py and it has `changes = _changes(...)` then
```
if changes :
    ...
    return ret
```
and next in line 451
```
    if changes is False:
        # The user is not present, make it!
        if __opts__['test']:
            ret['result'] = None
            ret['comment'] = 'User {0} set to be added'.format(name)
            return ret
```
I'm not too sure about use of `is` or the need for the `if` clause (there's `return` above it, you could just fall through), but it seems to me that when `changes` is true, it doesn't mean the user is not present. At a cursory glance, it seems some the user's attributes may have changed, and you can't use `useradd` to change them anyway. ICBW and all that.

**Comment by jfindlay** [comment]
@dmaziuk, thanks for the report.

**Comment by Gillingham** [comment]
I'm somewhat assuming this is directly related to this but all the file.* commands are affected by this as well.

If you try to set the user with any of those commands it will fail saying the user doesn't exist, even though it does exist in the LDAP realm, has a home directory, and can login to the system just fine. Right now I'm having to work-around this by following any file change with a cmd.wait call to chown.

**Comment by ekacnet** [comment]
Similar to this: if the a local user is supposed to be a member of a directory group it's not working

```
    Function: user.present
      Result: False
     Comment: The following group(s) are not present: admin-unix
     Started: 18:40:35.110117
    Duration: 0.618 ms
     Changes:   
```

**Comment by moloney** [comment]
Pretty sure this is a duplicate of #12803

**Comment by dmaziuk** [comment]
Not really: #12803 is about `file.managed` failing to fetch uid/gid from LDAP whereas this is about `user`/`group` not knowing which backend to use when.

**Comment by moloney** [comment]
The `user` and `group` states not recognizing LDAP entries I am pretty sure has the same underlying cause as the issues in the file states. If you restart the salt minion does it start to recognize these users/groups?

There is a separate issue that salt won't be able to add a missing user/group to LDAP for you by just using `user.present` or `group.present` but that feel like more of a documentation issue if anything.

**Comment by dmaziuk** [comment]
Well, I was specifically trying to add a cluster uid/gid to local files because on lennartware-infested systems LDAP is not guaranteed to start before the cluster soft. Or was it "tempfiles" service... Anyway, you can't add them to local files because there's ldap, and you can't add them to ldap -- because ldap.

**Comment by johnkeates** [comment]
I'm using FreeIPA (LDAP, Kerberos, SSSD) and experiencing this issue. Salt-call on the minion works but salt on the salt master reports the users don't exist.

**Comment by Ralle75** [comment]
We're using Win ActiveDirectory and experiencing the same issue linke johnkeates.

**Comment by johnkeates** [comment]
You probably need to restart the minion as well to make it at least read any new users/groups.

**Comment by Ralle75** [comment]
Thats a good idea, and it works. ;) thx

**Comment by vriabyk** [comment]
hi, we use FreeIPA and we are experiencing the same issue. Environment details:

OS version: Ubuntu 16.04
Salt version: 2017.7.8 (Nitrogen)

The following state fails:
```
jenkins:
  user.present:
    - shell: /bin/bash
    - home: {{ jenkins_home }}
    - optional_groups:
      - docker
```
the following error shows:
```
----------
    ID: jenkins
    Function: user.present
      Result: False
     Comment: Failed to create new user jenkins
     Started: 11:17:59.428546
    Duration: 13.056 ms
     Changes:   
----------
```
All related states are getting failed too:
```
----------
   ID: jenkins_home_dir
    Function: file.directory
      Name: /home/jenkins
      Result: False
     Comment: User jenkins is not available Group jenkins is not available
     Started: 11:17:59.441804
    Duration: 0.809 ms
     Changes:   
----------
```
While jenkins user exists on salt-minion (via FreeIPA):
```
# id jenkins
uid=1569400197(jenkins) gid=1569400197(jenkins) groups=1569400197(jenkins)
```

As @johnkeates mentioned, it works when running via salt-call.
