### ISSUE TITLE
iptables state append doesn't honor position -1

### ISSUE THREAD

**Issue by neogenix** [saltstack/salt#23952]
I use an iptables.insert with position -1, and I get this: 
```
root@salt-minion-01:~# iptables -vnL
Chain INPUT (policy ACCEPT 5 packets, 384 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:22
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:4505
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:4506
   18   882 log-and-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW
```

When I update the state to use iptables.append with position -1, I get this: 
```
root@salt-minion-01:~# iptables -vnL
Chain INPUT (policy ACCEPT 2 packets, 223 bytes)
 pkts bytes target     prot opt in     out     source               destination
    2    98 log-and-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:4505
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:4506
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:22
```

In both cases, my log-and-reject policy is required by the accepts, which happens first. Here's the example using insert for port 22:
```
ssh-input:
    iptables.insert:
        - position: -1
        - chain: INPUT
        - proto: tcp
        - connstate: NEW
        - jump: ACCEPT
        - source: 0.0.0.0/0
        - dport: 22
        - table: filter
        - match: state
        - save: True
```

And, here's the example using append:
```
ssh-input:
    iptables.append:
        - position: -1
        - chain: INPUT
        - proto: tcp
        - connstate: NEW
        - jump: ACCEPT
        - source: 0.0.0.0/0
        - dport: 22
        - table: filter
        - match: state
        - save: True
```

Here're my salt versions reports:
```
root@salt-master-01:/srv/salt/formulas/common# salt-minion --versions-report
                  Salt: 2015.5.0
                Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.1
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
 Debian source package: 2015.5.0+ds-1utopic1
root@salt-master-01:/srv/salt/formulas/common# salt-master --versions-report
                  Salt: 2015.5.0
                Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.1
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
 Debian source package: 2015.5.0+ds-1utopic1
```
