### ISSUE TITLE
Setting Created VM Ip Address using Salt-cloud 2014.7.5 and VMWare Dev Driver

### ISSUE THREAD

**Issue by CedNantes** [saltstack/salt#24030]
Hello again,

I want back to a 2014.7.5 installation of salt because 2015.5 wasn't working as i intended it to but now i've got an issue.

I'm using this provider :
```yaml
Vcenter:
  provider: vmware
  user: <edited>
  password: <edited>
  url: <edited>
```
and this profile :
```yaml
WIN-SRV-2012R2:
  provider: Vcenter
  clonefrom: MOD-WIN-SRV-2012R2
  resourcepool: LABO - SALTSTACK
  datastore: ESX01-STOR02
  power_on: True
  deploy: False
```
And i'm trying to use a map file to customize the VM : 
```yaml
WIN-SRV-2012R2:
  - WinMin:
      num_cpus: 1
      memory: 4096
      devices:
        network:
          Network adapter 1:
            name: VLAN-TEST
            switch_type: distributed
            ip: <myip>
            gateway: <gwip>
            subnet_mask: 255.255.255.0
        disk:
          Hard disk 1:
            size: 40
          Hard disk 2:
            size: 80
```
edit : copy paste is not working as intended but original file is yaml-style :p

Since the "Getting started with VMWare" docs are out of the official ones, I don't know all the options but i've been using a similar file and it worked fine with Debian VM. But with MS ones cpus, memory and Hard Disk are taken into account but IP address and HostName aren't. Is it normal ? Am I missing something or is it not supposed to work ? 

actual Salt config :
```yaml
             Salt: 2014.7.5
            Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
            Jinja2: 2.6
          M2Crypto: 0.21.1
    msgpack-python: 0.1.10
      msgpack-pure: Not Installed
          pycrypto: 2.6
           libnacl: Not Installed
            PyYAML: 3.10
             ioflo: Not Installed
             PyZMQ: 13.1.0
              RAET: Not Installed
               ZMQ: 3.2.3
              Mako: 0.7.0
 Debian source package: 2014.7.5+ds-1~bpo70+1
```
and vmware.py driver from here : 
https://raw.githubusercontent.com/saltstack/salt/develop/salt/cloud/clouds/vmware.py
