### ISSUE TITLE
invalid keyword: order for watch state important in 2015.5?

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#24070]
I have this state for the ssh-service:

``` yaml
ssh:
  service.running:
    - require:
      - pkg: openssh-server
    - enable: True
    - reload: True
    - watch:
      - file: /etc/ssh/sshd_config
```

2015.5 gives me the warning:

```
    Warnings: 'enable' is an invalid keyword argument for 'service.mod_watch'.
              If you were trying to pass additional data to be used in a
              template context, please populate 'context' with 'key: value'
              pairs. Your approach will work until Salt Lithium is out. Please
              update your state files.
```

But I don't see how `enable` is a parameter for `mod_watch`, it's a parameter for `service.running`, right?
