### ISSUE TITLE
State.highstate uses stale grain data.

### ISSUE THREAD

**Issue by primechuck** [saltstack/salt#24073]
Using the python API
```yaml
Salt: 2015.5.0
Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
Jinja2: 2.7.2
M2Crypto: 0.21.1
msgpack-python: 0.3.0
msgpack-pure: Not Installed
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.0.1
RAET: Not Installed
ZMQ: 4.0.4
Mako: 0.9.1
```
-- 

Using the python api running.
```python
saltCaller.function('grains.append', 'roles', 'master')
```
then immediately
```python
saltCaller.function('state.highstate')
```
Highstate doesn't see the newly appended grain.  If highstate is run again after a few seconds or after a sync it sees the grain.  The previous behavior in 2014 always grabbed grains when running highstate.
