### ISSUE TITLE
Feature: Add support to file.managed (and others) to preserve the file inode

### ISSUE THREAD

**Issue by tkent-xetus** [saltstack/salt#24099]
When `file.managed` is used, every time the file is updated the inode of the file is changed. This breaks things like hardlinks and file-based docker volume mounts. It's not terribly difficult to work around, but it's awfully hard to figure out what's happening. In our case, files mounted into a docker container, that were managed by salt, were not reflecting changes in the docker container after salt modified them. 

Once you know the cause, the impact is very small. The work around is very easy, just a two step process like so:

```
managed-file-where-inode-changes:
  file.managed:
    - source: salt://some/file.cfg
    - template: jinja

file-where-innod-will-not-change:
  require:
    - file: managed-file-where-inode-changes
  cmd.wait:
    - name: cat managed-file-where-inode-changes > file-where-innod-will-not-change
    - watch:
      - file: managed-file-where-inode-changes
```

However, it looks like this issue was already broached in #20969, so tools exist in salt to handle this scenario. It would be great if there was a property on `file.managed`, and similar states, like `preserve_inode` that had a `True` default.
