### ISSUE TITLE
file.copy with test=True always return pending changes

### ISSUE THREAD

**Issue by sysless** [saltstack/salt#24113]
After upgrading from 2014.7 to 2015.5, all file.copy states return pending changes even if the file hasn't changed and force is set to False.

Is this new behavior normal ?

**Comment by jtand** [comment]
@HiTeN Thank you for this. Would you be able to provide example output for this?

**Comment by HiTeN** [comment]
Here is the state :

```
/var/lib/tftpboot/pxelinux.0:
  file.copy:
    - source: /usr/share/syslinux/pxelinux.0
```
The output :

```
          ID: /var/lib/tftpboot/pxelinux.0
    Function: file.copy
      Result: None
     Comment: File "/usr/share/syslinux/pxelinux.0" is set to be copied to "/var/lib/tftpboot/pxelinux.0"
     Started: 07:07:25.502226
    Duration: 1.95 ms
     Changes:   
```

And my versions report :

```
           Salt: 2015.5.0
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
