### ISSUE TITLE
Option <makedirs: True> not honoured for <file.symlink>

### ISSUE THREAD

**Issue by mirko** [saltstack/salt#24133]
Option `makedirs: True` doesn't seem to be taken into account when using `file.symlink`

salt state file:

```
/var/lib/postgresql/.postgresql/postgresql.crt:
  file.symlink:
    - makedirs: True
    - target: /etc/ssl/certs/X.crt
    - require:
      - file: /etc/ssl/certs/X.crt
```

Expected result: `/var/lib/postgresql/.postgresql/` being created.

Actual result:

```
          ID: /var/lib/postgresql/.postgresql/postgresql.crt
    Function: file.symlink
      Result: False
     Comment: Directory /var/lib/postgresql/.postgresql for symlink is not present
     Started: 12:10:18.155090
    Duration: 0.53 ms
     Changes:
```
