### ISSUE TITLE
jobs.print_job lists target as 'unknown-target' in 2015.5

### ISSUE THREAD

**Issue by trevor-h** [saltstack/salt#24140]
In 2015.5.1 minions are targeted appropriately but the 'Target' and 'Target-type' fields returned via salt-run jobs.print_job <job_id> is 'unknown-target' and empty respectively.

Example:
``` yaml
salt '*' test.ping --async
Executed command with job ID: 20150526155859733467
salt-run jobs.print_job 20150526155859733467

20150526155859733467:
    ----------
    Arguments:
    Function:
        test.ping
    Minions:
        - th-1
        - th-2
        - th-3
    Result:
        ----------
        th-1:
            ----------
            return:
                True
        th-2:
            ----------
            return:
                True
    StartTime:
        2015, May 26 15:58:59.733467
    Target:
        unknown-target
    Target-type:
    User:
        root`
```
