### ISSUE TITLE
Ubuntu service.running enabled broken in latest release 

### ISSUE THREAD

**Issue by joshughes** [saltstack/salt#24177]
v2014.7.5 of salt on Ubuntu 14.04 the following works 

```yaml
elasticsearch:
  service:
    - running
    - enable: True
```

With the latest 'stable' release (`v2015.5.0`) my serverspec tests fail because there is no startup entry created. 

I confirmed the issue by restarting my machine and seeing that the elasticsearch service was not started on boot up. 

After downgrading to `v2014.7.5` the `enabled: True` flag works, the serverspec tests pass and on reboot elasticsearch starts.
