### ISSUE TITLE
setting pillar data on  the  command line error 

### ISSUE THREAD

**Issue by shencan** [saltstack/salt#24171]
saltstack version: salt 2014.7.4 (Helium)
os:    mac

state  files: shencan.sls
```
/tmp/shencan:
  file.managed:
    - source: salt://shencan.txt
    - template: jinja
```
template files:  shencan.txt

``` cat shencan.txt ```
`{{ foo }}`
command:
`salt '*' state.sls shencan pillar='{"foo": "bar"}'`

error messages：

Minion:
----------
          ID: //tmp/shencan
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'foo' is undefined
     Started: 20:10:32.323876
    Duration: 241.814 ms
     Changes:
