### ISSUE TITLE
Exception when using user.present with Windows

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt#24196]
This seems to be a fairly newly introduced bug. Here's an example output:-

```python
          ID: usrGhostFiles
    Function: user.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1563, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\states\user.py", line 375, in present
                  expire)
                File "C:\salt\bin\lib\site-packages\salt\states\user.py", line 114, in _changes
                  if not os.path.isdir(newhome):
              TypeError: coercing to Unicode: need string or buffer, NoneType found
     Started: 19:27:49.649000
    Duration: 3.0 ms
     Changes:   
```
It seems to be because the "home" value for users on Windows is always none, as user.getent shows:-

```yaml
      ----------
      gid:
      groups:
      home:
          None
      name:
          usrGhostFiles
      passwd:
          None
      shell:
      uid:
          S-1-5-21-2033504833-1387376432-1020295716-1002
```

A workaround that I found is to add `createhome: False` to the user state.
