### ISSUE TITLE
Option `test=False` does not work for `orchestrate` runner

### ISSUE THREAD

**Issue by uvsmtid** [saltstack/salt#24209]
Based on [this question](https://groups.google.com/forum/#!topic/salt-users/pKt_1m9Y40Q).

There is no known way to override `test: True` option from Salt minion config file `/etc/salt/minion` on command line using `orchestrate` runner.
## Example

Example `orchestrate` state in `/srv/salt/whatever.sls`:

```
    whatever_example:
        salt.state:
            - tgt: 'minion_id'
            - highstate: True
```
## Failed approach 1

Overriding default on the command line using `test=False` does not work with orchestrate runner (there are many `result: None` in the output due to test mode):

```
salt-run -l all state.orchestrate whatever test=False
```
## Failed approach 2

It is also not possible to override default config `test: True` inside `orchestrate` state above - this won't work:

```
    whatever_example:
        salt.state:
            - tgt: 'minion_id'
            - highstate: True
            - test: False
```
## Versions

Tested on single host with collocated Salt master and minion:

```
salt --versions
           Salt: 2015.5.0
         Python: 2.7.8 (default, Apr 15 2015, 09:26:43)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 1.0.0
```
