### ISSUE TITLE
LDAP users and groups

### ISSUE THREAD

**Issue by xnaveira** [saltstack/salt#24206]
Running a simple state that creates a directory:

```yaml
/home/someuser/dir:
  file.directory:
    - user: someuser
    - group: somegroup
    - makedirs: True
```
The state works fine if invoked locally:

    salt-call sate.highstate

But fails with the following error if invoked from the salt master:

    salt '*' state.highstate

error:

    ID: /home/someuser/dir
    Function: file.managed
    Result: False
    Comment: User someuser is not available Group somegroup is not available

Users and groups are **not** local, they are retrieved using openldap.

salt-call 2015.5.0 (Lithium)
salt 2015.5.0 (Lithium)
