### ISSUE TITLE
iptables state needs to keep ordering of flags

### ISSUE THREAD

**Issue by c4urself** [saltstack/salt#24226]
[Version info]
```
root@ip-10-0-100-130:~# salt-call --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```

The problem I'm having is that ordering is sometimes important for iptables' flags, the following state:
```
{% for route_name, route in pillar['vpn']['snat_routes'].items() %}
route_to_vpn_{{route_name}}:
  iptables.append:
    - table: nat
    - chain: POSTROUTING
    - source: 172.16.0.0/24
    - destination: {{route.addr}}
    - jump: SNAT
    - "to-source": {{ grains['ec2_local-ipv4'] }}
```

Is implemented with this command:

`/sbin/iptables --wait -t nat -A POSTROUTING  --source 172.16.0.0/24 --to-source 10.0.100.130 --destination 1.2.3.4 --jump SNAT`

The problem is that `--to-source` *must* appear after the `--jump` flag. Changing the command makes it work correctly:
` /sbin/iptables --wait -t nat -A POSTROUTING  --source 172.16.0.0/24 --destination 1.2.3.4 --jump SNAT --to-source 10.0.100.130`
