### ISSUE TITLE
Changing a pkgrepo entry does not remove the old entry

### ISSUE THREAD

**Issue by djhaskin987** [saltstack/salt#24227]
This ticket is about an entry in a salt state.

I had this pkgrepo entry:
```
taf_cmake:
  pkgrepo.managed:
    - name: deb https://example.com/foo-1.1.0 ./
    - file: /etc/apt/sources.list.d/foo.list
    - refresh_db: True
```

But when I ran highstate, I found I got the version of the repo wrong, so I changed its location:

```
taf_cmake:
  pkgrepo.managed:
    - name: deb https://example.com/foo-9.9.9 ./
    - file: /etc/apt/sources.list.d/foo.list
    - refresh_db: True
```

I ran hightstate again. I expected that this new entry would tell the machine to overwrite the file to change the location of the repo to the correct place. Instead, **both** entries were found in the file after the highstate, which broke my config. Contents of `/etc/apt/sources.list.d/foo.conf`:

```
deb https://example.com/foo-1.1.0 ./
deb https://example.com/foo-9.9.9 ./
```

Is there any way I can get around this while still maintaining idempotence? Is this a bug or a feature?
