### ISSUE TITLE
augeas issue with apache and recognizing changes that have been already made

### ISSUE THREAD

**Issue by kartiksubbarao** [saltstack/salt#24275]
This is possibly related to #24274, but in case it isn't, I'm reporting it as a separate issue. The following state is always run by salt, even if the change has already been made:
```yaml
/etc/apache2/sites-available/default-ssl.conf:
  augeas.change:
    - context: /files/etc/apache2/sites-available/default-ssl.conf/IfModule/VirtualHost
    - changes:
      - set directive[. = "SSLCertificateFile"]/arg /etc/ssl/certs/cert1.pem
```
I have to include something like `- unless: grep -q cert1.pem /etc/apache2/sites-available/default-ssl.conf` to prevent salt from rerunning the state.

**Comment by kartiksubbarao** [comment]
Found the problem -- `context:` needs to resolve to an actual file (as opposed to an arbitrary augeas path) in order for salt to determine the filename for comparing the old state vs the changed state. The following state works fine:

```yaml
/etc/apache2/sites-available/default-ssl.conf:
  augeas.change:
    - context: /files/etc/apache2/sites-available/default-ssl.conf
    - changes:
      - set IfModule/VirtualHost/directive[. = "SSLCertificateFile"]/arg /etc/ssl/certs/cert1.pem
```
It might be good to mention this more explicitly in the documentation. The current phrasing implies that setting `context` to a file path is just a convenience to avoid redundancy, whereas it is actually required if the desired behavior is not to make changes to a file that has already been changed.
