### ISSUE TITLE
augeas error with apache config files - unable to save to file

### ISSUE THREAD

**Issue by kartiksubbarao** [saltstack/salt#24274]
The following state fails with "Error: unable to save to file!":

``` yaml
/etc/apache2/sites-available/default-ssl.conf:
  augeas.change:
    - lens: httpd.lns
    - context: /files/etc/apache2/sites-available/default-ssl.conf/IfModule/VirtualHost
    - changes:
      - set directive[. = "SSLCertificateFile"]/arg /etc/ssl/certs/cert1.pem
```

If I take out `- lens: httpd.lns`, it works.
