### ISSUE TITLE
mariadb service module not functioning correctly with 'enable: true' (salt 2015.5 on debian8)

### ISSUE THREAD

**Issue by kkaig** [saltstack/salt#24298]
If I have the following in a state file:

``` yaml
mysql:
  service.running:
    - watch:
      - file: /etc/mysql/my.cnf
    - enable: false
```

then a highstate run works correctly - i.e. the minion returns no changes unless the file my.cnf is modified, in which case it restarts the service. 

However, if I have the following

``` yaml
mysql:
  service.running:
    - watch:
      - file: /etc/mysql/my.cnf
    - enable: true
```

then the output of running a highstate will always report a change, every time I run it. If I then change the my.cnf file, it doesn't restart the mysql service.

I'm guessing this is a debian/systemd bug, but I thought I'd report it here anyway. Feel free to delete if not relevant.
