### ISSUE TITLE
[modules] puppet.fact returns somes facts as strings containing a dictionnary

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#24359]
It seems that some facts (seen this on os, system_uptime and partitions) as strings instead of a as dictionnaries : 

```
# salt '*' puppet.fact os
puppetclient1:
    {"name"=>"Debian", "family"=>"Debian", "release"=>{"major"=>"8", "minor"=>"0", "full"=>"8.0"}, "lsb"=>{"distcodename"=>"jessie", "distid"=>"Debian", "distdescription"=>"Debian GNU/Linux 8.0 (jessie)", "distrelease"=>"8.0", "majdistrelease"=>"8", "minordistrelease"=>"0"}}
puppetclient2:
    {"name"=>"Debian", "family"=>"Debian", "release"=>{"major"=>"8", "minor"=>"0", "full"=>"8.0"}, "lsb"=>{"distcodename"=>"jessie", "distid"=>"Debian", "distdescription"=>"Debian GNU/Linux 8.0 (jessie)", "distrelease"=>"8.0", "majdistrelease"=>"8", "minordistrelease"=>"0"}}
```

**Comment by arthurlogilab** [comment]
versions_report : 

```
puppetclient2:
                      Salt: 2015.5.0
                    Python: 2.7.8 (default, Oct 18 2014, 12:50:18)
                    Jinja2: 2.7.3
                  M2Crypto: 0.21.1
            msgpack-python: 0.4.2
              msgpack-pure: Not Installed
                  pycrypto: 2.6.1
                   libnacl: Not Installed
                    PyYAML: 3.11
                     ioflo: Not Installed
                     PyZMQ: 14.4.0
                      RAET: Not Installed
                       ZMQ: 4.0.5
                      Mako: 1.0.0
     Debian source package: 2015.5.0+ds-1~bpo8+1
```
