### ISSUE TITLE
gpg.import_key bad owner for files under ~/.gnupg

### ISSUE THREAD

**Issue by favadi** [saltstack/salt#24389]
Module `gpg.import_key` always generates files with root owner under `~/.gnupg`.
Test states:

``` yaml
debug:
  pkg.installed:
    - pkgs:
      - gnupg
      - python-gnupg
  user.present:
    - name: test-gpg
  module:
    - run
    - name: gpg.import_key
    - user: test-gpg
    - text: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: SKS 1.1.5
        Comment: Hostname: pgp.mit.edu

        mQINBFVZbWsBEADm7tGr2bfeitcMJKMlToi0Ql7pzxex2bY85Cr8K3QDmlE2l0cZD0ovoKlW
        GgZiqNSSyUpRuzjLfHStoqEBHzXonDZs3qhwP9eujeq3qi2y/Kbrt4Oswb+simI9tlN3Mvrg
        VkDJZx0p1KBoODU4ejbyEw3O2pnUS1ibI2+1X0MM4QvkobXyTNaMWjWDoRB5qODajPfy1rzg
        5K6cZzRbKrDBO+0FDH1gs0/VpAC6DIzVFSnfD+nlDbKY8AheZHNs66osqpjR9bbhd47XL6nH
        q/A7kxj99776acXt95c6DZxUj8DF/7KkbFRvKxjSbarZ/8hkfBHOJNFHN0jwW5O8Klx1VpXA
        2MVkXO76m7ou5hS9186K4QLh/HviS6YlVLVU1tq39vAhk1vCkcFKLXY6H/SFrW4RYpJTEG+l
        9vaflfWDgyq9hj5Rp6rK4bg49Q2Gy/aEozP3Bq0SgBKWHof39EeqUFOKJKVAB9CGijQLzGjO
        +0kmFOq6j7YhkkHZSMaqRtGTkRkENEPdP6DsaA+U8TFjGjSdID5JEDgBrRWYh2bTJJBIb7pN
        gok/1K/o3LVKtDe0SuH3lgxNsnTDUVeFHKcoimAZleReuG3buTN6jqQSgZ/5q/d0Z1YSPR6W
        R1qFGiPNz5vnvLO2bnk3rhv9DV/PZBT0coD37LLvFG2r3GBIywARAQABtCFEaWVwIFBoYW0g
        PGZhdmFkaUByb2JvdGluZnJhLmNvbT6JAjgEEwECACIFAlVZbWsCGwMGCwkIBwMCBhUIAgkK
        CwQWAgMBAh4BAheAAAoJEHkHuF493edXKbcQAMQge0EAezPaLans8WjnJ9SO9ZxEeovZXXG/
        f1L5xIwYlQUQPDH6XeYoKY+iD9xrXDNtIhbNzydmxofi01mdaniq0EZxFWulQqeWifOOWo2C
        g+gC6F39GHJWJyjEhGH15J1P0nV3l4oL0Yz+3R6GKBXsN5LbytDkCRa9SWxcwTgQ5IKtXsEE
        aq63kCi3gErKMOEWFVurV4NQFYODXpYvFWYzWSigRwMDLkoT34w3pFHlRmRdujKO2j8ENLF+
        8p0Dmstc0ANMrU5sxic5chJqLTvAJP7GDFRvQnHN5GpGrK/mudV/yUsW9rWOzAdEjejWe2RY
        YFbp+CgptVnyjdMZ8AxPZntjfjEQKD8rIIwePDL1lGffr+RE7tU4EBjUT7l1t+RgtOI/dDS2
        IWvF+chDpv+PjMQhV4RMe7VTSG0VgX00pk7H9PClPy7bx8TFXFqAOgO1FUxKLEkJGM7RYOrQ
        Md+1LsDTM2qxgFjvvQj55oCv9Mo7OvkEeCIcOwzGk1AlnyV+tSMTHOLq7IRFzZSLF67zv4LU
        x3ybh2+IDwxMgCQn0fOsOr+ZvTPrpnCETT6fOoqoUiTerYQn42qIgziCQK6KYvVDK7n2nwL8
        ZCJFYokeaZs3WImC4Z+WvmNyf8+08vkCNlUnrGZY/VVGBe+OXJ9b3mJrIH/wMP66UwwB5EBi
        uQINBFVZbWsBEADQo7L4+WpomljUagJhJLL4th9AbZ0AEEPOsLC4VfQn56IfIK8L2sdRHALf
        wf2iCWZYKUF17ED/MhNkVLi+NBilDjyQWM/VLw7Fyj1RMJJh5QgYCvyR2HjgZqnSoj3VU6BU
        +/ZJQg2NZ+oE8iZj9HpypGQAzENaBHLGTBEyPVT13pkRXuIUEBFoq9+FoD4ZS5mAR0CcOedQ
        KkJNahiaVYhxEIrmRxSkm/ZoVvdoDLFOLxMGLMxggtlFqcU5gsozP3tFFxQ9LloSFS4Zt9Tb
        DTrSQ7Al3yrBYTiFz37iY5oGXfT6C3lKLP5rfrtZnQbkvG0oJaqOHlAK3TmFY3OfwlIBKlNe
        4pPkRwVqxmmQ3kDaY8wXuyBiFZZFsKwu6S4oI/plF2dz7MgP9Hc2njChK14AbJhbFE3OkRUw
        ndYEpY/UA6vGW406nprVvS35MieR4fl5SGd0OyxGfck4cX12I7xNMCWhQpaAtZRO6FkIGw3z
        BtT6053jPMWYeNAMyt33WYjP7YBYIkp30UW+Henk7Ns38BryrdFNyvkUf+noTk155qWaH0L/
        YDmeKvg7zH6chA5qGCHJOHGXOAtXmyugTCLQ/S4jpDPXjPWPqY/HgbKDZgHDYGVnsqibji/z
        HlNbu3BacGzchwBY/qCVCRm40Mx+HblTxbL0cJBre1qLUiqo5wARAQABiQIfBBgBAgAJBQJV
        WW1rAhsMAAoJEHkHuF493edXYUoQAL359PnM3/2odsSRaqFIWaifMd41QXO5Gu9SLu6lM8mv
        fb+2SSDQI9QJO9hsmcnU2BwSofB0ifM9sG3rixqpqHClOkD8wZ4z7/dP1dxFAsHp9jqjXPqq
        xp1T//LUkYAaO8ec0sEszlqglUqbJh22I7v042TdHC73kI1A2Oh/dNL8ubWTqRqYuHfH67BZ
        FECKfdQBl+CE+C+Ymh8/TG7Cs6XuUKxQEdAHEpg5kcgE1RIcG/0Xovq6I3cQM8uEl7E37Rvb
        SE8+kod291oamQo8/5Cw8+RkEgPQc9xnrbDtF8WJgnHKxO8FlKxaCWzP1pR5l1sihyXHnEve
        x9MOrPyVKFBWrF29ZginiQdqWmTVr2rv7mEtGMtYbax4czZFtgWWcNWJpSxt+WXYvxajG4GR
        fcfMtN2G/+q8d6o84F08oqSXW/tDrs6n4l7+MR7esR1nrWVHsn0Ra2+KnJ8upTOWrXvpNMZ1
        k5bbC6NT/jmidh+4jKGhQej5U5t4DDkWa4zjNN86GFrtqkqSe9d4Z/6tX+E0Ke/Zf1p1b7KC
        X8ZZxjoFBFLLHEp+x94Kd41+quQp6oi/bYDgH0c9yYY/soG12Ze9R5odwkziB/ILD/f6O5Wp
        aZvhqSvVfCfLRgtR62thX1j03XTHrCXPx26UiHgcaCVkfRrny4sDLRqRVrnSa9hR
        =3zdr
        -----END PGP PUBLIC KEY BLOCK-----
    - require:
      - user: debug
      - pkg: debug
```

After execute above states:

``` console
(salt-dev)root@salt-dev:~# ls -la ~test-gpg/.gnupg/
total 16
drwx------ 2 root     root     4096 Jun  4 05:10 .
drwxr-xr-x 3 test-gpg test-gpg 4096 Jun  4 05:10 ..
-rw------- 1 root     root     2216 Jun  4 05:10 pubring.gpg
-rw------- 1 root     root        0 Jun  4 05:10 pubring.gpg~
-rw------- 1 root     root        0 Jun  4 05:10 secring.gpg
-rw------- 1 root     root     1200 Jun  4 05:10 trustdb.gpg
```

The owner of those files should be `test-gpg` instead of `root`.

I test with latest version from develop.

``` yaml
(salt-dev)root@salt-dev:~# salt-call --versions-report
Salt Version:
           Salt: 2015.5.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:38)
           RAET: Not Installed
            ZMQ: 4.0.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: i686
        release: 3.13.0-53-generic
         system: Ubuntu 14.04 trusty
```
