### ISSUE TITLE
git.latest force_reset prepending origin/ to commit revs

### ISSUE THREAD

**Issue by nzjay** [saltstack/salt#24386]
The following state
```yaml
    checkout_code:
      git.latest:
        - rev: 769afef22238c92eb707613de8fe0457a4cfd531
        - force_reset: True
        - name: ssh://user@server/repo.git
        - target: /path/to/repo
```
Will try and run `git reset --hard origin/769afef22238c92eb707613de8fe0457a4cfd531`, which fails (This appears to be the code responsible https://github.com/saltstack/salt/commit/769afef22238c92eb707613de8fe0457a4cfd531)

In 2014.7.1 this would `git reset --hard` before checking out the specified commit hash.
