### ISSUE TITLE
Error install app in Windows 

### ISSUE THREAD

**Issue by HabibaAmina** [saltstack/salt#24430]
hello,

I allow myself to write to you following a problem with the installation of an application for windows in salt.

here are my configuration files. unfortunately, I do not know where the problem is.

thank you for your answer.

Im using saltstack Master and windows version 2015.5.1 
```console
root@debian:/srv/salt# ls
win top.sls 
```
nano top.sls
```yaml
base:
  'os:Windows':
    - match: grain
    - win.repo.zabbix
```
```console
root@debian:/srv/salt/win/repo/zabbix# ls
init.sls  zabbix_agent-2.4.2_x64.msi
```
nano init.sls
```yaml
init.sls
zabbix:
  2.4.2:
    installer: 'salt://win/repo/zabbix/zabbix_agent-2.4.2_x64.msi'
    full_name: 'Zabbix'
    reboot: False
    install_flags: ' SERVER=10.16.33.60 RMTCMD=1 /qn'
    uninstall_flags: ' /q'
    msiexec: True
    uninstaller: 'salt://win/repo/zabbix/zabbix_agent-2.4.2_x64.msi'
```
and config master.conf 
```yaml
interface: 10.16.33.62
file_roots:
  base:
    - /srv/salt
win_repo: '/srv/salt/win/repo'
```
Error: 
```console
root@debian:/srv/salt# salt 'win' state.highstate
win:
    Data failed to compile:
----------
    State 'zabbix' in SLS 'win.repo.zabbix' is not formed as a list
```
Where the problem please ?
