### ISSUE TITLE
Salt locale state fails, if locale has not been generated

### ISSUE THREAD

**Issue by chrimi** [saltstack/salt#24433]
Salt's locale state will started everytime, if choosen locale has not been generated via `locale-gen` before

This happens on a ubuntu version, which has been installed via xen debootstrap.
I've tried to set de_DE.UTF-8 as default locale.

This fails, because `locale -a` won't list the locale by default
It has to be set via `locale-gen de_DE.UTF-8`. 

Without this step, salt state locale.present will be fired up every time, but without an error message
```
          ID: de_locale
    Function: locale.present
        Name: de_DE.UTF-8
      Result: True
     Comment: Generated locale de_DE.UTF-8
     Started: 08:04:57.692015
    Duration: 1480.535 ms
     Changes:
              ----------
              locale:
                  de_DE.UTF-8
```

a manual `update-locales` without `locale-gen de_DE.UTF-8` produced this error message, which won't be catched by the salt state

```
update-locale
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "de_DE.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
*** update-locale: Error: invalid locale settings:  LANG="de_DE.UTF-8"
```

version: 
```
salt --versions-report
                  Salt: 2015.5.0
                Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
 Debian source package: 2015.5.0+ds-1precise1
```

It seems, that the fix for #23767 (my other locale based issue) won't fix this too.

**Comment by jfindlay** [comment]
@chrimi, is it possible for you to post the state file you're using?  Thanks.

**Comment by chrimi** [comment]
sorry for delay, here's  my current state file

```
# this must be done, until salt issue #24433 has been fixed
generate_locale:
  cmd.run:
    - name: locale-gen de_DE.UTF-8

de_locale:
  locale.present:
    - name: de_DE.UTF-8

# this must be done, until #23767 has been fixed
create-default-locale:
  cmd.run:
    - name: touch /etc/default/locale
    - unless: test -f /etc/default/locale

default_locale:
  locale.system:
    - name: de_DE.UTF-8
    - require:
      - locale: de_locale
```

**Comment by jfindlay** [comment]
@chrimi, this is probably fixed by #24078, which has been released in 2015.5.1 and 2015.5.2.  Unfortunately, neither of these have been packaged for debian yet.  We are working on automating packages upstream rather than relying on contributors.

As a workaround you can try
```yaml
de_locale:
  locale.present:
    - name: de_DE.UTF-8

# this must be done, until #23767 has been fixed
create-default-locale:
  cmd.run:
    - name: touch /etc/default/locale
    - unless: test -f /etc/default/locale

default_locale:
  locale.system:
    - name: de_DE.UTF-8 UTF-8
    - require:
      - locale: de_locale
```

The problem is that debian expects the locale to include a codeset at the end of the locale specification.  When I refactored the `locale.gen_locale` function, I forgot to copy the codeset from the charmap such that salt would accept either format, `de_DE.UTF-8 UTF-8` and `de_DE.UTF-8`.  This has been fixed in #24078.

**Comment by rallytime** [comment]
This is fixed for me with #25290, which should be available on recent releases of 2015.5 and 2015.8. I'm going to close this. If this pops up again, let us know and we'll gladly reopen!

**Comment by robinpecha** [comment]
Hi, the same issue. What Im doing wrong?
**Debian GNU/Linux 12 (bookworm) + salt-minion 3007.1 (Chlorine)**

```
us_locale:
  locale.present:
    - name: en_US.UTF-8

generate_locale:
  locale.gen_locale:
    - name: en_US.UTF-8

default_locale:
  locale.system:
    - name: en_US.UTF-8
```
**OUTPUT**:
```
----------
          ID: us_locale
    Function: locale.present
        Name: en_US.UTF-8
      Result: True
     Comment: Locale en_US.UTF-8 is already present
     Started: 09:28:20.851316
    Duration: 4.652 ms
     Changes:   
----------
          ID: generate_locale
    Function: locale.gen_locale
        Name: en_US.UTF-8
      Result: False
     Comment: State 'locale.gen_locale' was not found in SLS 'locale'
              Reason: 'locale.gen_locale' is not available.                                                                         "mc [root@zab7test]:/s" 09:24 01-Jul-24root@zab7test]:/m" 09:10 01-"mc [root@zab7test]:/m" 09:03 01-Jul-24
     Changes:   
----------
          ID: default_locale
    Function: locale.system
        Name: en_US.UTF-8
      Result: False
     Comment: Failed to set system locale to en_US.UTF-8
     Started: 09:28:22.258385
    Duration: 112.323 ms
     Changes:   
------------
```
