### ISSUE TITLE
Can't use Umlauts in Pillar

### ISSUE THREAD

**Issue by lloesche** [saltstack/salt#24438]
I have a pillar that looks like this:

```yaml
---
users:
  lukas:
    fullname: Lukas Lösche
    crypt: ''
    uid: 2012
    gid: 2012
...
...
...
```
Note the ö in the fullname field.

Trying to create the user using a formula results in the following error

```
    Data failed to compile:
----------
    Rendering SLS 'base:users' failed: Jinja error: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 280, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 17, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)

; line 17

---
[...]
    - name: {{ username }}
    - shell: /bin/bash
    - home: /home/{{ username }}
    - uid: {{ details.get('uid', '') }}
    - gid: {{ details.get('gid', '') }}
    - password: {{ details.get('crypt','') }}    <======================
    {% if 'groups' in details %}
    - groups:
      {% for group in details.get('groups', []) %}
      - {{ group }}
      {% endfor %}
[...]
---
```

The formula looks like this:
```yaml
{% for username, details in pillar.get('users', {}).items() %}
{{ username }}:
  group:
    - present
    - name: {{ username }}
    - gid: {{ details.get('gid', '') }}

  user:
    - present
    - fullname: {{ details.get('fullname','') }}
    - name: {{ username }}
    - shell: /bin/bash
    - home: /home/{{ username }}
    - uid: {{ details.get('uid', '') }}
    - gid: {{ details.get('gid', '') }}
    - password: {{ details.get('crypt','') }}
    {% if 'groups' in details %}
    - groups:
      {% for group in details.get('groups', []) %}
      - {{ group }}
      {% endfor %}
    {% endif %}
    {% if 'optional_groups' in details %}
    - optional_groups:
      {% for group in details.get('optional_groups', []) %}
      - {{ group }}
      {% endfor %}
    {% endif %}
    - require:
      - group: {{ username }}
  {% if 'pub_ssh_keys' in details %}
  ssh_auth:
    - present
    - user: {{ username }}
    - names:
    {% for pub_ssh_key in details.get('pub_ssh_keys', []) %}
      - {{ pub_ssh_key }}
    {% endfor %}
    - require:
      - user: {{ username }}
  {% endif %}

{% endfor %}
```

If I replace the 'ö' with a 'o' the formula is working fine. Is this a bug or do I have an encoding problem somewhere? I'm on version 2015.5.0.
