### ISSUE TITLE
Add watch support for possibly empty directories

### ISSUE THREAD

**Issue by MoonSweep** [saltstack/salt#24436]
Requisites can use glob for matching (#663, #678), but if a directory is empty, the requisite ends up with an error.

Example:

Debian provides a "sysfsutils" package with a startup script to set sysfs variables. They are stored in both /etc/sysfs.conf and /etc/sysfs.d/*. So I wrote this in an SLS:

``` yaml
sysfsutils:
  service.running:
    - name: sysfsutils
    - watch:
      - file: /etc/sysfs.conf
      {% if grains['osrelease'] >= '8' %}
      - file: /etc/sysfs.d/*
      {% endif %}
```

_Note: support for configuration snippets in /etc/sysfs.d was added in Jessie, hence the check on `grains['osrelease']`._

But on some hosts, the /etc/sysfs.d/ directory is empty, and I have this error:

``` yaml
          ID: sysfsutils
    Function: service.running
      Result: False
     Comment: The following requisites were not found:
                                 watch:
                                     file: /etc/sysfs.d/*
     Started: 
    Duration: 
     Changes:   
```

Please add a way to watch/require files in a directory, even if said directory is empty.

Thanks !
