### ISSUE TITLE
dockerio.installed fails to bind ports and volumes correctly

### ISSUE THREAD

**Issue by thenewwazoo** [saltstack/salt#24455]
When creating a container (say, for use as a volume container), binding host ports and host volumes doesn't work.

When applying the following states:
```yaml
# Install a container with bound ports and bound mounts
installed service:
  docker.installed:
    - name: busybox-created
    - image: busybox
    - volumes:
      - /etc/passwd: /hostpasswd
    - ports:
      - "4505/tcp":
            HostIp: "0.0.0.0"
            HostPort: "4507"

# *Start* the same container (with a different id)
running service:
  docker.running:
    - name: busybox-running
    - image: busybox
    - volumes:
      - /etc/passwd: /hostpasswd
    - ports:
      - "4505/tcp":
            HostIp: "0.0.0.0"
            HostPort: "4505"
```

the expected result appears in the `states.dockerio.running()` container (extraneous lines omitted):
```json
{
    "Config": {
        "ExposedPorts": null,
        "Volumes": null,
    },
    "HostConfig": {
        "Binds": [
            "/etc/passwd:/hostpasswd:rw"
        ],
        "PortBindings": {
            "4505/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "4505"
                } ] 
    },
    "Volumes": {
        "/hostpasswd": "/etc/passwd"
    },
}
```

Results differ in the container created using state.dockerio.installed():
```json
{
    "Config": {
        "ExposedPorts": {
            "OrderedDict([('4505/tcp', OrderedDict([('HostIp', '0.0.0.0'), ('HostPort', '4507')]))])": {}
        },
        "Volumes": {
            "/hostpasswd": {}
        },
    },
    "HostConfig": {
        "Binds": null,
        "PortBindings": null, 
    },
    "Volumes": {
        "/hostpasswd": "/var/lib/docker/vfs/dir/6d66b27aaec480c4311f71d315d5d4d506c5029de22a97b91dac949e9b69f7d2"
    },
}
```

Functioning of each container's bind mount can be shown:
```bash
root@lucid-salt:/srv/salt# docker run --rm --volumes-from=busybox-running busybox ls -ld /hostpasswd
-rw-r--r--    1 root     root          1001 Jun  1 18:19 /hostpasswd
root@lucid-salt:/srv/salt# docker run --rm --volumes-from=busybox-created busybox ls -ld /hostpasswd
drwxr-xr-x    2 root     root          4096 Jun  5 16:57 /hostpasswd
root@lucid-salt:/srv/salt#
```

Expected result is that each /hostpasswd file is a plain file, not a directory.

This is on:
```bash
root@lucid-salt:/srv/salt# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy
root@lucid-salt:/srv/salt# uname -a
Linux lucid-salt 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1~bpo70+1 (2015-04-27) x86_64 GNU/Linux
root@lucid-salt:/srv/salt# salt-call --version
salt-call 2015.5.0 (Lithium)
root@lucid-salt:/srv/salt# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
root@lucid-salt:/srv/salt#
```
