### ISSUE TITLE
Computed comments in jinja states

### ISSUE THREAD

**Issue by arnoutpierre** [saltstack/salt#24494]
I have searched for related issues but found nothing. Not sure if it's an assumed comportment or a bug.
I was playing with Salt when I discovered commented lines in states can be computed by jinja.

Example:

```
# file: /srv/salt/top.sls
base:
  '*':
    - computed_comments
```

```
# file: /srv/salt/computed_comments.sls
do_something:
  cmd.run:
    - name: echo 'Hello world'
    - cwd: /

{# something commented following jinja syntax #}

#
# compute_something_commented:
#   cmd.run:
#     - name: echo {{ this_variable_do_not_exists }}
#     - cwd: {{ but_this_is_commented_and_should_not_crash }}
#
```

```
sudo salt 'minion_name' state.apply
minion_name:
    - Rendering SLS 'base:computed_comments' failed: Jinja variable 'this_variable_do_not_exists' is undefined
```
I think this can be assumed as Salt bug because is the `sls` format (who use jinja) where error append (a commented line is parsed by jinja) and not a jinja issue.

I have found nothing about this and so think this is a bug, but maybe this is voluntary and you can explain it.
