### ISSUE TITLE
cmd.wait ignores watchers if file given in "creates" is present

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt#24491]
This is for 2015.5.0. Given the following state:

``` yaml
mycommand:
  cmd.wait:
    - name: /path/to/mycommand
    - creates: /some/file
    - watch:
      - file: myfile
```

then mycommand is NOT executed if /some/file exists, even if myfile was executed. mycommand should be executed if ANY of the conditions is not fulfilled.
