### ISSUE TITLE
Order in top.sls file is not respected for pillar data in local mode

### ISSUE THREAD

**Issue by astehlik** [saltstack/salt#24501]
My pillar setup looks like this:

In the `minion.conf` the `pillar_roots` config looks like this:

``` yaml
pillar_roots:
  lib:
    - /srv/salt/salt-lib/pillar
  base:
    - /srv/salt/pillar
```

My pillar `top.sls` file in `/srv/salt/pillar/top.sls` looks like this:

``` yaml
lib:
  '*':
    - main

base:
  '*':
    - basic
```

The main.sls file in `/srv/salt/salt-lib/pillar/` contains:

``` yaml
test:
  setting: myvalue-main
```

The `basic.sls` file in `/srv/salt/pillar/` contains:

``` yaml
test:
  setting: myvalue-override
```

When I now run 

``` bash
sudo salt-call --local pillar.get test:setting
```

the output is:

```
local:
    myvalue-main
```

The **expected** output would be:

```
local:
    myvalue-override
```

The salt version is 2014.7.1

Is this related to #1432 ?
