### ISSUE TITLE
modules.artifactory doesn't support username/password.

### ISSUE THREAD

**Issue by dragonpaw** [saltstack/salt#24548]
There's no way to download an artifact from artifactory for password-protected accounts.

We tried things like a artifactory_url of https://user@pass:artifactory.com/widgetcorp/... and that ended up splitting on the : and complaining about the port being invalid (because it was treating the url as if it were a port number.)

Ideally we'd want something like:
```yaml
my_awesome_artifact:
  artifactory.downloaded:
    - artifact:
        artifactory_url: http://1.2.3.4/artifactory
        repository: 'repo1-cache'
        artifact_id: 'c3p0'
        username: {{ pillar['artifactoryUser'] }}
        password: {{ pillar['artifactoryPassword'] }}
    ...
```
