### ISSUE TITLE
salt-cloud - Azure - should be possible to specify virtual network & subnet in profile

### ISSUE THREAD

**Issue by iacopo-papalini** [saltstack/salt#24559]
In the profile file for an Azure provider, it should be possible to optionally specify which Virtual Network and Subnet the VM will belong to.

A resulting profile could look like:
```yaml
test-profile:
  provider: test-azure-config
  image: 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_2-LTS-amd64-server-20150506-en-us-30GB'
  size: ExtraSmall
  location: 'West Europe'
  ssh_username: azureuser
  ssh_password: silly-password
  slot: production
  media_link: 'https://test-media-link.blob.core.windows.net/vhds'
  virtual_network_name: my-virtual-network
  subnet_name: SUBNET1
```
(the last two lines are not currently supported)

Since the 'azure' python library already support this, the change is really trivial:
```diff
diff --git a/salt/cloud/clouds/msazure.py b/salt/cloud/clouds/msazure.py
index 5548854..80d1175 100644
--- a/salt/cloud/clouds/msazure.py
+++ b/salt/cloud/clouds/msazure.py
@@ -487,6 +487,12 @@ def create(vm_):
         'role_size': vm_['size'],
         'network_config': network_config,
     }
+
+    if 'virtual_network_name' in vm_:
+        vm_kwargs['virtual_network_name'] = vm_['virtual_network_name']
+        if 'subnet_name' in vm_:
+            network_config.subnet_names.append(vm_['subnet_name'])
+
```

I tested the code with an Azure account and it seems to work
