### ISSUE TITLE
cron.env_present always reports a change (Lithium)

### ISSUE THREAD

**Issue by murdegern** [saltstack/salt#24567]
Hello all,
I have two cron.env_present states as follows:

```
cron_mail_admin:
  cron.env_present:
    - user: root
    - name: MAILTO
    - value: cron@example.com

cron_char_set:
  cron.env_present:
    - user: root
    - name: CONTENT_TYPE
    - value: "text/plain;charset=utf-8"
```

now, the second one (CONTENT_TYPE) is always reported as changed on highstate:

```
# salt-call state.highstate
[...]
local:
----------
          ID: cron_char_set
    Function: cron.env_present
        Name: CONTENT_TYPE
      Result: True
     Comment: Cron env CONTENT_TYPE updated
     Started: 14:50:00.224036
    Duration: 637.356 ms
     Changes:   
              ----------
              root:
                  CONTENT_TYPE

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

This happens on every run. It doesn't seem to be related to the "strange" value of CONTENT_TYPE, and it has been like this on 2014.7.2, too.

The crontab looks like this:

```
# Lines below here are managed by Salt, do not edit
MAILTO=cron@example.com
CONTENT_TYPE=text/plain;charset=utf-8
# SALT_CRON_IDENTIFIER:cron_run_salt
51 7 * * * /root/bin/run-salt '/bin/true'
```

(before and after running highstate).

Regards,
Torsten

**Comment by basepi** [comment]
Interesting. I'm guessing we're not properly detecting the entry at the beginning of the state if it's already present, and so we're "adding" it every time and reporting changes. Anyway, we'll investigate this.

**Comment by ipmb** [comment]
I'm guessing it has to do with the quotes because I see the same behavior with:

```
cron_mail_admin:
  cron.env_present:
    - user: myuser
    - name: MAILTO
    - value: ""
```

**Comment by thehunmonkgroup** [comment]
Just a note that I'm running Carbon and face basically the same problem, except it's not an empty string that causes it, but an integer value, like so:

```yaml
cron_foo:
  cron.env_present:
    - name: FOO
    - value: 1
```

Forcing the value to a string did solve it for me.
