### ISSUE TITLE
git.latest rev changing from a branch to a detached HEAD fails

### ISSUE THREAD

**Issue by nzjay** [saltstack/salt#24587]
When you set up a git.latest to start from a branch, but want to later move to a detached head, the git.latest state will fail (but it does checkout the new revision anyway, so will be okay next time)

Seems like a minor/pedantic issue but can be frustrating when dependent states don't run (and onchanges/watches won't run subsequently either until moving to a new rev again)

state: `repo.sls`
```
checkout_code:
  git.latest:
    - name: ssh://user@host/path/to/repo
    - target: /opt/repo
    - rev: {{ salt['pillar.get']('checkout_rev', 'master') }}
```

To reproduce
- run `state.sls repo` with no pillar, succeeds
- run `state.sls repo pillar='{"checkout_rev":"COMMIT_HASH"}'` (where commit hash is a hash different from the current master HEAD)
- state fails (`Comment: Command 'git config branch.126581e468db3831c9eef46614e2ab184aa38023.remote' failed. Stderr: ''`) but the repository is on the new detached HEAD

I haven't checked too closely but I have a feeling the check on [this line #L296](https://github.com/saltstack/salt/blob/develop/salt/states/git.py#L296) should match the [earlier check #L217](https://github.com/saltstack/salt/blob/develop/salt/states/git.py#L217)
