### ISSUE TITLE
augeas.change doesn't support setting empty values

### ISSUE THREAD

**Issue by kartiksubbarao** [saltstack/salt#24661]
Currently, augeas.change doesn't work when setting parameters to empty values. For example, this state definition doesn't work:
```yaml
/etc/ntp.conf:
  augeas.change:
    - lens: ntp.lns
    - context: /files/etc/ntp.conf
    - changes:
      - set server[1]/iburst ""
```
The problem is the regexp on line 133 of modules/augeas_cfg.py. I'll submit a pull request that fixes this.
