### ISSUE TITLE
Installing RPM from file_roots always returns FALSE:

### ISSUE THREAD

**Issue by bnikolaus** [saltstack/salt#24693]
I have rabbitmq state which uses deploy rpm inside my file_roots. Due to the fact that this always returns false on node that has rabbitmq already installed I am unable to use requisite logic. If installing a rpm package from the local file system Salt should determine if this is already installed it should return True instead of False.

``` yaml
----------
          ID: rabbitmq-server
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: rabbitmq-server-3.3.5-1.noarch.rpm.
     Started: 16:55:54.883628
    Duration: 6905.395 ms
     Changes:
```

``` yaml
rabbitmq-server:
    pkg.installed:
       - sources:
         - {{version}}: salt://rabbitmq/{{version}}
     service:
       - running
       - enable: True
       - watch:
         - file: /etc/rabbitmq/rabbitmq-env.conf
         - file: /var/lib/rabbitmq/.erlang.cookie
```
