### ISSUE TITLE
Salt-mine & grain.get

### ISSUE THREAD

**Issue by mooperd** [saltstack/salt#24699]
Hello,

I would like to be able to do more complex things with the salt mine in order to do some DNS tricks. Salt-contrib has a great tool to extract metadata information from an AWS instance https://github.com/saltstack/salt-contrib/blob/master/grains/ec2_info.py

#Background

In my pillar I have the following"

```
mine_functions:
  network.ip_addrs: [eth0]
  grains.get: ['ec2']
```

and in my state file

```
{% for server, data in salt['mine.get']('roles:master', 'grains.get', expr_form='grain').items() %}
{{ data }}
{% endfor %}
```
This produces a great chunk of json will all kinds of exciting stuff: https://gist.github.com/mooperd/61c17881306630068dd0

Im able to grab specific fields using the following.

```
{% for server, data in salt['mine.get']('roles:master', 'grains.get', expr_form='grain').items() %}
{{ data['block_device_mapping'] }}
{% endfor %}
```
output: {'ami': '/dev/sda1', 'root': '/dev/sda1'}

```
{% for server, data in salt['mine.get']('roles:master', 'grains.get', expr_form='grain').items() %}
{{ data['block_device_mapping']['ami'] }}
{% endfor %}
```
output:  /dev/sda1

#Actual Problem

I would like to be able to grab several specific grain items in order to generate a CNAME record. I can get the AWS public hostname from ['ec2']['public_hostname'] but I cannot work out how to get other grains.

```
mine_functions:
  network.ip_addrs: [eth0]
  grains.get: ['ec2']
  grains.get: ['localhost']
```
Using this I get the error: Pillar render error: Rendering SLS 'ip' failed.
I guess it is not liking the two "grains.get". 

The question is: How do I grab ALL grains or MULTIPLE grains into the mine?

Cheers,

Andrew

**Comment by mooperd** [comment]
I'm looking at the "Alias" function in salt mine:

```
mine_functions:
  network.ip_addrs: [eth0]
  function_one:
    - mine_function: grains.get
    - localhost
  function_two:
    - mine_function: grains.get
    - ec2
```

But I cannot see how to use this data in my states. Ideas?

**Comment by basepi** [comment]
I'm curious, if you add a function_five does it pick up four but not five? I'm wondering if it's an issue of the last one in the list or if something else is going on.

**Comment by mooperd** [comment]
Hi @basepi,

I am AFK for the next few days so its going to be difficult to test. Ill try and find time on friday.

**Comment by basepi** [comment]
Thanks. No hurry from my end.

**Comment by flowhamster** [comment]
@mooperd Does this solve your issue https://docs.saltstack.com/en/develop/topics/mine/index.html?

You can specify multiple function aliases to get the data you need.

**Comment by pakdel** [comment]
I am using this:
```
mine_functions:
  network.ip_addrs: []
  grains.item:
    - id
    - os
    - fqdn
    - fqdn_ip4
    - ipv4
    - roles
```

And here is my notes about managing a DNS: https://github.com/pakdel/SaltConf16
