### ISSUE TITLE
virtualenv.managed: documentation and error handling for nested requirements failure

### ISSUE THREAD

**Issue by gthb** [saltstack/salt#24716]
Currently this will fail in an unclear way:

```
/some/path/virtualenv:
  virtualenv.managed:
    - requirements: /my/code/requirements.txt
    - user: {{ user }}
```

if `requirements.txt` refers to another requirements file. The state output is:

```
virtualenv exists

Could not open requirements file: [Errno 2] No such file or directory: '/tmp/requirements-common.txt'
```

It took spelunking in github issues to find out that this problem is caused by the default behavior of copying the requirements file away to `/tmp/` to chown it to the given user, and that it can be worked around by setting `no_chown: True`. There is no documentation of this in https://docs.saltstack.com/en/latest/ref/states/all/salt.states.virtualenv_mod.html

This case is quite common and so shouldn't fail in an unclear and undocumented way. Either `no_chown: True` should be the default behavior (perhaps inverted to be `chown: False`), or this should be documented and the error message should help the user towards the workaround.
