### ISSUE TITLE
How does state pkg.installed update the installed pkg with sources?

### ISSUE THREAD

**Issue by abcfy2** [saltstack/salt#24738]
Here is my state:

```
logstash:
  pkg.installed:
    - sources:
      - logstash: http://myserver/logstash_1.5.0-1_all.deb
```

Now I want to update logstash to 1.5.1. So I modify the sources config:

     - logstash: http://myserver/logstash_1.5.1-1_all.deb

But it's not working:

```
----------
          ID: logstash
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed.
     Started: 10:04:07.145625
    Duration: 33240.024 ms
     Changes:   
----------
```

How do I update my pkg with sources?
