### ISSUE TITLE
apache.configfile reports success even when the configFile has not been created

### ISSUE THREAD

**Issue by RobertFach** [saltstack/salt#24781]
```
salt-minion --versions-report
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.5+ds-1ubuntu1
```

Hi, when creating an apache config with apache.configfile, the state seems to succeed even when the configfile has not been created. E.g, in the case that it would be placed in a directory that doesn't exist. This might be a result of a misconfiguration (as in the case below) or on purpose. 

E.g.:

```
/etc/apache2/conf.d/salt-test.conf:
   apache.configfile:
     - config:
       - VirtualHost:
         this: '*:80'
         ServerName:
          - salt-test.com
         ...
```
