### ISSUE TITLE
salt.states.git.latest failure when specifying commit hash

### ISSUE THREAD

**Issue by ipmb** [saltstack/salt#24879]
I typically use a branch for the `rev` kwarg to `git.latest` which works fine, but specifying a commit hash as the `rev` fails in 2015.5.0:

> Comment: Command 'git branch {HASH} --set-upstream origin/{HASH}' failed. Stderr: 'The --set-upstream flag is deprecated and will be removed. Consider using --track or --set-upstream-to\nerror: the requested upstream branch \'origin/{HASH}\' does not exist\nhint: \nhint: If you are planning on basing your work on an upstream\nhint: branch that already exists at the remote, you may need to\nhint: run "git fetch" to retrieve it.\nhint: \nhint: If you are planning to push out a new local branch that\nhint: will track its remote counterpart, you may want to use\nhint: "git push -u" to set the upstream config as you push.'

**Comment by jtand** [comment]
@ipmb I think this may be a duplicate of #24386. Can you provide the state you are using to get this error?

**Comment by ipmb** [comment]
```
{{ repo }}:
    git.latest:
      - rev: {{ branch }}
      - target: {{ src }}
      - user: {{ project }}
      - https_user: {{ pillar.github_token }}
      - https_pass: x-oauth-basic
      - require:
        - pkg: git-core
        - user: {{ project }}
```
