### ISSUE TITLE
Pillar: Specified SLS 'data' in environment 'base' is not available on the salt master

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt#24884]
I get the following message when I start a highstate on a Windows minion using 2015.5.0, getting pillar data and states from a Git repo:
```
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'data' in environment 'base' is not available on the salt master
```
But the file IS there and a state.show_highstate runs without problems and shows the expected result.

When running the highstate with logging set to DEBUG, I also see that the GPG encrypted value in data/init.sls in succesfully decrypted prior to the error message.

I've setup a test repo for reproducing the problem [here](https://github.com/dhs-rec/salt-test) (you may need to replace the GPG encrypted value in pillar/data/init.sls with your own). The top.sls data comes from a MongoDB and looks like this:
```jinja
{ "_id" : "the_minion", "environment" : "base", "states" : [ "data" ] }
```

Relevant master configuration:
```yaml
master_tops:
  mongo:
    collection: tops
fileserver_backend:
  - git
  - roots
gitfs_provider: gitpython
# There's an alias for GitHub in ~/.ssh/config, to shorten the URL and provide the key.
gitfs_remotes:
  - github:dhs-rec/salt-test.git
gitfs_root: salt
ext_pillar:
  - mongo: {}
  - git: master github:dhs-rec/salt-test.git root=pillar
pillar_source_merging_strategy: smart
mongo.host: localhost
```

Some commands and their results:
```console
# salt "the_minion" saltutil.refresh_pillar
the_minion:
    True
# salt "the_minion" state.show_highstate
the_minion:
    ----------
    data:
        ----------
        __env__:
            base
        __sls__:
            data
        test_from_string:
            ----------
            file.managed:
                |_
                  ----------
                  name:
                      D:/test_from_string
                |_
                  ----------
                  content:
                      This is a test
        test_from_template:
            ----------
            file.managed:
                |_
                  ----------
                  name:
                      D:/test_from_template
                |_
                  ----------
                  source:
                      salt://data/the_template
                |_
                  ----------
                  template:
                      jinja
                |_
                  ----------
                  defaults:
                      ----------
                      var1:
                          D:\test_file
                      var2:
                          supersecret
                      var3:
                          foo
                      var4:
                          value
                      var5:
                          bar
                |_
                  ----------
                  require:
                      |_
                        ----------
                        sls:
                            test
    test:
        ----------
        __env__:
            base
        __sls__:
            test
        test_file:
            ----------
            file.managed:
                |_
                  ----------
                  name:
                      D:/test_file
                |_
                  ----------
                  source:
                      salt://test/test_file
# salt "the_minion" state.highstate
the_minion:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'data' in environment 'base' is not available on the salt master
```
