### ISSUE TITLE
Keys in pillar path?

### ISSUE THREAD

**Issue by wmariuss** [saltstack/salt#24888]
It's just a question.

Let's say, we have a pillar `.sls` file:

```
keys:
  repository:
    - private_key: salt://staging/files/.keys/id_rsa.pub
    - public_key: salt://staging/files/.keys/id_rsa
```

And now the keys are in `salt://` path, not pillar, can be those keys in pillar path and then specified in pillar `.sls` file?
It's very important for me to separe all sensible data from `salt://` path.
