### ISSUE TITLE
spurious warning in file.managed using source: ~

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#24895]
when I run this state:

```
save-the-world:
  file.managed:
    - name: "/-@"
    - mode: 000
    - source: ~
```

I see this warning on the minion:

```
[INFO    ] Executing state file.managed for /-@
[WARNING ] Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily
[INFO    ] File /-@ exists with proper permissions. No changes made.
```

I humbly submit that I provided a source so the warning is unexpected. I get this for every state that has an empty source. Documentation [here](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html) suggests the above YAML.

salt 2015.5 all around:

```
root@web-6:/var/www/svn# salt-call --version
salt-call 2015.5.0 (Lithium)
```

**Comment by Mrten** [comment]
obvious fix is obvious: add in the documentation that 'replace' needs to be False if one sets source to ~ :)
`contents: ''` won't work.

**Comment by jtand** [comment]
@Mrten It looks like ~ gets changed to none with pyyaml. If you put ~ in quotes '~' then it will work as intended.

**Comment by Mrten** [comment]
Nah:
```
web-6:
----------
          ID: save-the-world
    Function: file.managed
        Name: /-@
      Result: False
     Comment: Unable to determine upstream hash of source file ~
     Started: 09:16:55.109038
    Duration: 0.84 ms
     Changes:
```
