### ISSUE TITLE
YUM: Version pinning fails if version is already pinned

### ISSUE THREAD

**Issue by AusIV** [saltstack/salt#24901]
When I set a package to be version pinned like so:

```
{% from 'bedrock/salt/map.jinja' import versions with context %}

salt:
  pkg.installed:
    - version: {{versions.salt}}
    - hold: true
```

The first time I run the state, it works fine. But any subsequent runs I get a failed state:

```
          ID: salt
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: salt=2014.7.5-1. Package salt is already set to be held.
     Started: 16:37:47.782414
    Duration: 10469.055 ms
     Changes:   
```

It seems that if the package is already set to be held that should be an unchanged state, not a failed state.

This is my experience with Salt 2014.7.5 on CentOS 7, but I didn't see anything that looked like it would have fixed this issue in later versions.
