### ISSUE TITLE
reload_modules: True does not reload module dependencies

### ISSUE THREAD

**Issue by klyr** [saltstack/salt#24925]
Hi,

I would like to use the `swift`execution module to install an application.
For the `swift` execution module to be enabled, one need to install the `python-swiftclient` library first.

```sh
$ salt --versions-report
           Salt: 2015.5.2-120-g1650233
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
        Tornado: Not Installed
```

Here is a simple SLS file:

```yaml
python-swiftclient:
  pip.installed:
    - reload_modules: True

python-keystoneclient:
  pip.installed:
    - reload_modules: True

python-dev:
  pkg.installed

download_application:
  module.run:
    - name: swift.get
    - cont: test_container
    - path: test_app
    - local_file: /tmp/test_app
    - require:
      - pip: python-keystoneclient
      - pip: python-swiftclient
```

The execution of this SLS file fails at the `download_application` step because it says that the `swift` module is not present:

```
     Changes:
----------
          ID: download_application
    Function: module.run
        Name: swift.get
      Result: False
     Comment: Module function swift.get is not available
     Started: 12:42:28.767301
    Duration: 200.984 ms
     Changes:
````

In order to make it work, I need to restart the minion to be aware of the new `python-swiftclient` library being installed, and re-run the SLS file. 

By looking at the source code, we can see that the python `reload()` function is called for the `modules/swift.py` module, so the module is effectively reloaded.

BUT, its dependencies are not (this is not the behaviour of the `reload()` function)

We can see at https://github.com/saltstack/salt/blob/develop/salt/modules/swift.py#L46 that `swift.py` imports `salt.utils.openstack.swift` that is "evaluated" once, on first import (re-importing a library does not mean the library is re-evaluated)

So at https://github.com/saltstack/salt/blob/develop/salt/utils/openstack/swift.py#L22 the following code is only executed once and the variable `HAS_SWIFT` is still set to False even after the `swift.py` module is reloaded because `reload()`  does not reload python dependencies.

```python
# Import Swift client libs
HAS_SWIFT = False
try:
    from swiftclient import client

    HAS_SWIFT = True
except ImportError:
    pass
```

Other modules like `docker.io` are not affected by this problem because they directly import third-party libraries and upon reloading, they retry to import these libraries. So installing `docker-py` with `reload_modules: True` enables the `docker.io` execution module without restarting the minion.

Adding a `reload(suos)` call in the [\_\_virtual\_\_()](https://github.com/saltstack/salt/blob/develop/salt/modules/swift.py#L52) function fixes the problem but this is not a clean solution.

Questions:
- Do I install the third party library the right way ?
- Should I expect that the installation of a third party library is taken into account without restarting the minion ?

Cheers.

**Comment by arroyoc** [comment]
@klyr Thanks for your report.

**Comment by mitar** [comment]
We have the same problem with pip:

```
python-pip:
  pkg.installed:
    - reload_modules: True
```

So because reload does not work, other states which depend on pip fail with:

```
State 'pip.installed' found in SLS is unavailable
```

cc @kostko

**Comment by ltsampros** [comment]
Is there any update on this?

**Comment by giorgiosironi** [comment]
Run into this error while trying to upgrade Python from 2.7.6 to 2.7.12 with Salt states. Trying to find a workaround too.

**Comment by ninja-** [comment]
After analyzing the problem, I think the best solution would be to adjust the problematic states so that it would avoid this pattern OR make them check every time in __virtual__

**Comment by peterloron** [comment]
Any progress on this? It's really becoming a serious problem for us. Sucks to have to run a manual highstate after the reactor triggered run during salt-cloud.

**Comment by ninja-** [comment]
@peterloron as I said this is more of each module related problem. What module are you using?

**Comment by peterloron** [comment]
I have a state which installs python-pip using the pkg salt module, and then docker-py using the pip salt module. Following that I run a docker image using dockerng. I can see that docker-py gets installed, but the call to run the image fails because it doesn't see that docker-py is available. The pkg and pip calls have 'reload_modules: True'. This state is being triggered via reactor when salt-cloud creates a new machine. I can manually re-run the highstate and the second time everything works because the minion has now picked up the docker-py module.

**Comment by ninja-** [comment]
@peterloron docker-ng no longer exists as a module in salt, it was split to 4 new modules. are you using the latest salt version?

**Comment by boltronics** [comment]
I seem to be hitting the same issue with `mysql_database.present` in my state sls file:

```
{%- set mysql = salt['pillar.get']('mysql', []) %}

Install MySQL server:
  pkg.installed:
    - name: mysql-server

Configure Salt minion for MySQL access:
  file.managed:
    - name: /etc/salt/minion.d/mysql.conf
    - contents: |-
        mysql.default_file: '/etc/mysql/debian.cnf'
    - user: root
    - group: root
    - mode: '0644'
    - reload_modules: True
    - require:
      - pkg: Install MySQL server

{%- for database in mysql.get('databases', {}).get('present', []) %}
Create MySQL database {{ database }}:
  mysql_database.present:
    - name: {{ database }}
    - require:
      - file: Configure Salt minion for MySQL access
{%- endfor %}
```

Results in
```InternalError: (1698, u"Access denied for user 'root'@'localhost'")```
errors for each database. The state must be executed twice to succeed.

**Comment by jnielsendotnet** [comment]
I'm running in to this issue with 2019.2. I have a custom module that uses an etcd-backed sdb to store and distribute some state information. I have a state that installs python-etcd if needed and then calls the module. However if python-etcd is not installed then the state will fail on its first run.

python-etcd:
  pip.installed:
    - require_in:
      - pre_start
    - reload_modules: True

Then later my custom module will fail with:
     Comment: Module function my_custom_module.sync threw an exception. Exception: (unable to import etcd, module most likely not installed)

That error message is from salt.utils.etcd_util. That makes sense; during the state execution Salt loads all of the modules up front, so when "import etcd" is first attempted it fails and sets the HAS_LIBS variable to False. Even though it's and the Python modules are reloaded before it's needed, Salt doesn't know that. There needs to be a way for states/modules like pip with reload_modules=True to tell salt to do all that stuff again partway through an execution. Or at the very least a way to say "something important has changed, start over".

**Comment by ninja-** [comment]
AFAIR this bug was individual to several poorly written state modules which used this pattern; I had an occasion to fix this in some of them

**Comment by crosscodr** [comment]
The same issue is present in the pkgrepo.managed state (salt version 2019.2.0).
When I install the required dependencies (python(3)-pycurl and python(3)-tornado) with modules_reload: True and in a seperate state using pkgrepo.managed, it fails, because the dependent libraries weren't loaded yet. I tried different things, even restarting the salt-minion in the same salt-run before using pkgrepo.managed. Didn't help.
Only executing the salt-state twice, worked so far.

**Comment by darkn3rd** [comment]
I am running into the same problem with `salt-minion 2019.2.3 (Fluorine)`.  

I use something like this:
```yaml
docker-python-modules:
  pip.installed:
    - names: 
      - docker 
      - urllib3 
      - requests
      - requests[security]
    - reload_modules: True
    - upgrade: True
    - require:
      - pkg: python-pip
```

When I run something depended on the docker module, such as `docker_container.running` state, I I get a traceback.
