### ISSUE TITLE
Using pkg.installed with unauthenticated Apt-get repo

### ISSUE THREAD

**Issue by abh23** [saltstack/salt#24924]
I have created a custom repo where only required packages are copied. To install package using apt-get, I use "--allow-unauthenticated" argument so that APT doesn't crib about source being unauthenticated. 

I want to achieve the same using pkg.installed module which uses apt-get -y in background. 

Please let me know how to achieve this.

Regards
AB

**Comment by jtand** [comment]
@abh23 I believe the option `skip_verify: True` will get you the results you are looking for. 

Example:
```yaml
/srv/salt/tmux.sls:
  tmux:
    pkg.installed:
      - name: tmux
      - skip_verify: True
```
