### ISSUE TITLE
Support `test: True` as an argument to state functions

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#24939]
There has been some discussion surrounding the creation of dedicated test states to ensure the application of a given state on a system. In lieu of doing that, we decided instead to extend the `test=True` paradigm and in addition to supporting it on the cmd-line and in a config, we want to allow any state to have this argument passed into it directly. Refs #24919 

An example state:
```
configure_passwd:
  file.managed:
    - name: /etc/passwd
    - mode: '0644'
    - user: root
    - group: root
    - test: True
```
