### ISSUE TITLE
Static grains do not appear to work if added to minion config

### ISSUE THREAD

**Issue by pcn** [saltstack/salt#24943]
When I set /etc/salt/minion to contain static grains as per the comments int he config file, static grains are not set.  Using /etc/salt/grains seems to work.

Example:
```
ubuntu@ip-10-136-113-28:~$ cat /etc/salt/minion.d/custom_grains.conf
grains: 
    node_name: pcn_cass-v1-stg-datanode-01
    cassandra_cluster_name: pcn_cass
```

The above results in nothing matching the key "node_name" or "cassandra_cluster_name" when using ```salt-call grains.items``` on the node or using salt on the master.

Moving the same file into /etc/salt/grains does work.
