### ISSUE TITLE
file.directory with clean-option does not handel requirements with wildcards

### ISSUE THREAD

**Issue by mmoench** [saltstack/salt#24991]
I have an existing directory "/test" which should only contain files provided by various different states. If I write it like this, the files "a" and "b" are placed in the directory and then removed again:

```
/test:
  file.directory:
    - clean: True
    - require:
      - file: /test/*

/test/a:
  file.managed

/test/b:
  file.managed
```

```
----------
          ID: /test/a
    Function: file.managed
      Result: True
     Comment: Empty file
     Started: 14:19:17.315672
    Duration: 1.156 ms
     Changes:   
              ----------
              new:
                  file /test/a created
----------
          ID: /test/b
    Function: file.managed
      Result: True
     Comment: Empty file
     Started: 14:19:17.318950
    Duration: 1.076 ms
     Changes:   
              ----------
              new:
                  file /test/b created
----------
          ID: /test
    Function: file.directory
      Result: True
     Comment: Files cleaned from directory /test
     Started: 14:19:17.322632
    Duration: 0.983 ms
     Changes:   
              ----------
              removed:
                  - /test/a
                  - /test/b
```

However, if I list all files separately without using the wildcard, everything works just fine (same if I use "require_in" for each file):

```
/test:
  file.directory:
    - clean: True
    - require:
      - file: /test/a
      - file: /test/b
…
```

```
----------
          ID: /test/a
    Function: file.managed
      Result: True
     Comment: Empty file
     Started: 14:26:05.327887
    Duration: 1.174 ms
     Changes:   
              ----------
              new:
                  file /test/a created
----------
          ID: /test/b
    Function: file.managed
      Result: True
     Comment: Empty file
     Started: 14:26:05.331270
    Duration: 1.065 ms
     Changes:   
              ----------
              new:
                  file /test/b created
----------
          ID: /test
    Function: file.directory
      Result: True
     Comment: Files cleaned from directory /test
     Started: 14:26:05.335594
    Duration: 1.011 ms
     Changes:   
              ----------
              removed:
                  - /test/junk
```

I am using salt 2015.5.0.
