### ISSUE TITLE
Proposal: Ability to restrict States to Pillar-Envs

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#25025]
Another ([a bit older](https://groups.google.com/forum/?_escaped_fragment_=topic/salt-users/h6ve2dalbII)) idea about pillar-envs but independent from #25024:

Adding an option in the (states') topfile which pillar_env a particular state (or set of states) can see:

``` yaml
base:
    'web*.example.com':
        - match: glob
        - pillar_env: webserver
        - apache
        - memcached
        - ...
```

I finally came up with an use-case but I'm still not sure if there isn't already a better way
to do something like this:

``` yaml
base:
    'webprod*.example.com':
        - match: glob
        - pillar_env: production
        - apache
        - memcached
        - ...
    'webdev*.example.com':
        - match: glob
        - pillar_env: develop
        - apache
        - memcached
        - ...

```
