### ISSUE TITLE
2015.5.2 service.running option full_restart no longer works

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#25073]
Since updating our salt-minion from 2015.5.0 to 2015.5.2 full_restart option no longer restarts services.

minion version

```
           Salt: 2015.5.2
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

state.sls

```
narwhal:
  service.running: 
    - provider: systemd
    - reload: True
    - full_restart: True
    - enable: True
    - watch:
      - cmd: narwhal-extract
      - file: narwhal-config
```

minion log

```
2015-06-29 22:40:37,944 [salt.loaded.int.module.cmdmod][ERROR   ][5250] Command 'systemctl reload narwhal.service' failed with return code: 3
2015-06-29 22:40:37,944 [salt.loaded.int.module.cmdmod][ERROR   ][5250] output: Failed to issue method call: Job type reload is not applicable for unit narwhal.service.
```

**Comment by deuscapturus** [comment]
Here is a state workaround
```
narwhal:
  service.running:
#    - reload: True
#    - full_restart: True
    - enable: True
#    - watch: 
#      - cmd: narwhal-extract
#      - file: narwhal-config

#this restart cmd.wait is a workaround until https://github.com/saltstack/salt/issues/25073 is resolved
narwhal-restart:
  cmd.wait:
    - name: systemctl restart narwhal
    - watch:
      - cmd: narwhal-extract
      - file: narwhal-config
    - order: last
```
