### ISSUE TITLE
context passed inside jinja macro converts pillar values into strings

### ISSUE THREAD

**Issue by mtourne** [saltstack/salt#25098]
My pillar looks like this 

```
foo:
  blah:
```

And the file that uses these values :

```
{% if pillar.foo.blah %}
foo:
  cmd.run:
    - name: echo {{ pillar.foo.blah }}
{% endif %}

{% macro my_mycro(my_foo) %}
my_conf:
  - source: salt://files/template.conf
  - context:
    foo = {{ my_foo }}
{% endmacro %}

{{ my_macro(pillar.foo) }}
```

The foo command doesn't run, since pillar.foo.blah is None.

But inside template.conf : 

```
{% if foo.blah %}
 {{ foo.blah | join('|') }}
{% endif %}
```

This time foo.blah is a string "None", and it gets rendered as 
`N|o|n|e`

**Comment by mtourne** [comment]
Here is a better example of this :
```
/tmp/test.conf:
  file.managed:
    - source: salt://affirm/files/nginx/conf.d/debug.conf
    - template: jinja
    - context:
      module: 'module'
      webserver: {{ pillar[module].webserver }}
```

debug.conf : 

```
    {{ pillar[module].webserver }}

    {{ webserver }}
```

The output : 

```
    { 'block': None, ... }

   { 'block': 'None', ... }
```

In the first case when passing a simple dictionary key I'll get the dictionary properly on the other side, but when passing the whole dictionary everything has been converted into strings.

For reference, this is with Salt 2014.1.10
