### ISSUE TITLE
`file.copy` followed by `file.replace` on the target fails with "file not found"

### ISSUE THREAD

**Issue by cubranic** [saltstack/salt#25138]
I have a pair of states where the first one is supposed to copy a file from a known "source" location, while the second replaces various labels in it. (I could have also use `file.managed`, but since the changes are purely cosmetic, I thought this would save me from having to track changes to this file done by the source project.)

``` yml
message-overlay:
  file.copy:
    - name: {{ source_dir }}/dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
    - source: {{ source_dir }}/dspace-xmlui/src/main/webapp/i18n/messages.xml
    - makedirs: True
    - force: True
    - user: tomcat
    - group: tomcat

message-statspace:
  file.replace:
    - name: {{ source_dir }}/dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
    - pattern: DSpace
    - repl: StatSpace
  require:
    - file: message-overlay
```

However, when I run Saltstack on this formula, either just the SLS or as part of the high state, I get an where the second (replacing) state does not find the copied file. What's strange is that the log shows that the file was copied:

```
[INFO    ] Running state [/var/dspace-src/dspace/modules/xmlui/src/main/webapp/i18n/messages.xml] at time 22:43:45.535955
[INFO    ] Executing state file.copy for /var/dspace-src/dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
[INFO    ] The target file "/var/dspace-src/dspace/modules/xmlui/src/main/webapp/i18n/messages.xml" exists and will not be overwritten
[INFO    ] Completed state [/var/dspace-src/dspace/modules/xmlui/src/main/webapp/i18n/messages.xml] at time 22:43:45.555614
[INFO    ] Running state [/var/dspace-src/dspace/modules/xmlui/src/main/webapp/i18n/messages.xml] at time 22:43:45.557573
[INFO    ] Executing state file.replace for /var/dspace-src/dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
[ERROR   ] /var/dspace-src/dspace/modules/xmlui/src/main/webapp/i18n/messages.xml: file not found
[INFO    ] Completed state [/var/dspace-src/dspace/modules/xmlui/src/main/webapp/i18n/messages.xml] at time 22:43:45.558367
```

Inspecting the file system, the target file doesn't exist, as if the copying didn't suceed. Or maybe it was deleted at some point before the replacing was run? If I run the states one by one explicitly via `state.sls_id`, then everything works fine.

**Comment by jfindlay** [comment]
@cubranic, what is the output of `salt --versions-report` and `salt <minion> test.versions_report`?  I am unable to reproduce this.

```yaml
jmoney-main ~ master # salt --versions
           Salt: 2015.5.2
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 1.0.0
```
```yaml
jmoney-main ~ master # cat /srv/salt/files.sls
message-overlay:
  file.copy:
    - name: /tmp/tomcat/message.xml
    - source: /tmp/message.xml
    - makedirs: True
    - force: True

message-statspace:
  file.replace:
    - name: /tmp/tomcat/message.xml
    - pattern: DSpace
    - repl: StatSpace
  require:
    - file: message-overlay
```
```yaml
jmoney-main ~ master # cat /tmp/message.xml
DSpace
```
```yaml
jmoney-main ~ master # salt jmoney-main state.sls files
jmoney-main:
----------
          ID: message-overlay
    Function: file.copy
        Name: /tmp/tomcat/message.xml
      Result: True
     Comment: Copied "/tmp/message.xml" to "/tmp/tomcat/message.xml"
     Started: 13:31:05.647141
    Duration: 2.395 ms
     Changes:
              ----------
              /tmp/tomcat/message.xml:
                  /tmp/message.xml
----------
          ID: message-statspace
    Function: file.replace
        Name: /tmp/tomcat/message.xml
      Result: True
     Comment: Changes were made
     Started: 13:31:05.651626
    Duration: 2.783 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1 +1 @@
                  -DSpace
                  +StatSpace

Summary
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
```
```yaml
jmoney-main ~ master # cat /tmp/tomcat/message.xml
StatSpace
```
