### ISSUE TITLE
Ability to template files that contain {{ }}, etc as part of the file.

### ISSUE THREAD

**Issue by Cidan** [saltstack/salt#25133]
Right now, it's impossible to use Jinja templates on files that contain the markers that Jinja looks for to template the file. For example, I can't template my logstash config, because it's littered with grok patterns that cause the Jinja renderer to fail due to parsing issues.

It would be helpful to be able to set the code/block start and end strings that Jinja uses, using Salt. This is already possible in Jinja natively during init, however Salt does not expose such a configuration. For example, something like this would suffice:

```
/etc/logstash/conf.d/logstash.conf:
  file.managed:
    - template: jinja
    - start_variable_string: "|%|"
    - end_variable_string: "|%|"
    - source: salt://files/config/logger/logstash.conf
    - mode: 644
    - makedirs: True
```

Thanks.
