### ISSUE TITLE
user.present on Windows fails to add user to groups if group name contains a space

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt#25144]
e.g:

```yaml
johncc:
  user.present:
    - groups:
      - Administrators
      - Backup Operators
```

This fails when salt tries to call:-
```
net localgroup Backup Operators johncc /add
```

I've tried every way I can think of to inject quotes via the state but I can't make it work!

In the end I had to do:-

````yaml
set-group-backup:
  cmd.run:
    - name: 'net localgroup "Backup Operators" johncc /add || ( call )'
    - shell: cmd
````

The `|| ( call )` stops the state showing as failed if the group already exists, at the risk of hiding other errors.
