### ISSUE TITLE
Jinja2 dictsort not working.

### ISSUE THREAD

**Issue by AkhterAli** [saltstack/salt#25177]
Hello, I'm trying to add a list of users from my pillar.  However when I specify the dictionary to be sorted (|dictsort) it's returning the following error.

```
SaltRenderError: Jinja variable dict object has no element ('Username', {'fullname': 'user name', 'shell': '/bin/bash', 'email_address': 'username@company.com', 'homedir': '/home/username', 'uid': 0000})
```

```jinja
{%
for account in pillar.user_accounts|dictsort %}{%
   if pillar.user_accounts[account].has_key('email_address')
%}{{ account }} {{ pillar['user_accounts'][account].email_address }}
{% endif %}{%
endfor %}
```

According to the following document, I should be able to use dictsort and sort by key and case insensitive.

http://jinja.pocoo.org/docs/dev/templates/

Edit:  Removing "|dictsort" works however the order isn't always the same so salt thinks that there are always changes.

**Comment by slimg00dy** [comment]
Here is a sample of my user_accounts pillar.


```
user_accounts:
    user1:
        fullname: user one
        email_address: user1@company.com
        homedir: /home/user1
        shell: /bin/bash
        uid: 10001
    user2:
        fullname: user two
        email_address: user2@company.com
        homedir: /home/user2
        shell: /bin/bash
        uid: 10040
```
