### ISSUE TITLE
fullname issues with user.add state on windows

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#25206]
### versions
```yaml
jmoney-main ~ master # salt jmoney-windows-12 test.versions_report
jmoney-windows-12:
               Salt: 2015.5.3
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.5
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.6.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
            Tornado: Not Installed
```

### configs
```yaml
jmoney-main ~ master # cat salt-manual-tests/windows/user_add.sls 
add_dude:
  user.present:
    - name: saltdude
    - fullname: Salt Dude
```

### actions
```yaml
jmoney-main ~ master # salt jmoney-windows-12 state.sls salt-manual-tests.windows.user_add                                                                                                                                                                                                        
jmoney-windows-12:
----------
          ID: add_dude
    Function: user.present
        Name: saltdude
      Result: True
     Comment: New user saltdude created
     Started: 15:49:16.235000
    Duration: 63.0 ms
     Changes:   
              ----------
              active:
                  True
              comment:
              fullname:
                  "Salt
              gid:
              groups:
                  - Users
              home:
                  None
              logonscript:
              name:
                  saltdude
              passwd:
                  None
              profile:
                  None
              uid:
                  S-1-5-21-1160757986-2943312950-2002998559-1003

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
The fullname of the user is `"Salt` rather than `Salt Dude`.  Quoting `Salt Dude` in the state file doesn't change this result.

#### second run
```yaml
jmoney-main ~ master # salt jmoney-windows-12 state.sls salt-manual-tests.windows.user_add
jmoney-windows-12:
----------
          ID: add_dude
    Function: user.present
        Name: saltdude
      Result: False
     Comment: These values could not be changed: {'fullname': u'Salt Dude'}
     Started: 16:06:52.689000
    Duration: 437.0 ms
     Changes:   
              ----------
              groups:

Summary
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
```
