### ISSUE TITLE
Module git.latest kills target directory when test=True

### ISSUE THREAD

**Issue by rall0r** [saltstack/salt#25229]
Hi,
I have an issue running a single state with test=True not behaving as expected:
The state contains a `git.latest` state with `- force=True`.

While running the state from the commandline with `test=True` the target directory will be deleted! Thats not what I would expect while in testmode.

Statefile

```yaml
salt_master_config:
  git.latest:
    - name: http://gitlab.example.com/saltstack/salt-master-etc-salt.git
    - target: /etc/salt
    - user: root
    - force: True
```
Called like:
```bash
salt 'saltminion*' state.sls saltmaster test=True saltenv=dev
```
We are on 2015.5.2

Kind regards
Ralf
