### ISSUE TITLE
bootstrapping container with lxc.present

### ISSUE THREAD

**Issue by thepauleh** [saltstack/salt#25236]
Hi,

I've been trying to get containers working using lxc.present and also salt cloud. My issue doing this with lxc.present is that theres no minion configured at the end of the process.

```
{{ ROLE }}-lxc:
  lxc.present:
        - name: {{ ROLE }}-lxc
        - running: True
        - template: centos
```

Using this technique, the container can be started - but has no minion.

If i try to use the salt cloud approach, (cloud.profile) then the container fails to start due to bad gateway config (i'm trying to go for a dhcp config inside of vagrant vm) - I have only defined the master ip & port, and I was hoping the rest would be treated the same as the lxc.present for network config & 'just work':

```
my-lxc:
  # the provider to use
  provider: my-lxc
  lxc_profile:
      template: centos
  minion:
     master: 10.0.2.15
     master_port: 4506
```

Specifically:
```
lxc-start: start.c: lxc_spawn: 817 failed to find gateway addresses
lxc-start: start.c: __lxc_start: 1080 failed to spawn 'pauls1-lxc'
lxc-start: lxc_start.c: main: 342 The container failed to start.
lxc-start: lxc_start.c: main: 346 Additional information can be obtained by setting the --logfile and --logpriority options.
```
Has anyone been here before?

Looks like this issue is kinda the same for the 'cheat/lxc.present' approach:
https://github.com/saltstack/salt/issues/24752
