### ISSUE TITLE
user.absent fails in 2015.8 branch when purge=True

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#25275]
Running head of 2015.8 branch (`2015.8.0rc1-10-g9e90603`)

State file:
```
testuser01:
  user.absent:
    - purge: True
    - force: True
```

```
test_dev_32:
----------
          ID: testuser01
    Function: user.absent
      Result: False
     Comment: Failed to remove user testuser01
     Started: 23:07:39.272000
    Duration: 15.0 ms
     Changes:

Summary for test_dev_32
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  15.0 ms
```

It works fine when I remove the purge line
