### ISSUE TITLE
Unless usage in Official Doc syntax error?

### ISSUE THREAD

**Issue by shinshenjs** [saltstack/salt#25281]
http://docs.saltstack.com/en/latest/ref/states/requisites.html#unless

In this section of the document, the sample for the multiple cmd.run is written this way

```
deploy_app:
  cmd.run:
    - names:
      - first_deploy_cmd
      - second_deploy_cmd
  - unless: ls /usr/bin/vim
```

Which is invalid if you try to run it that way. I believe the indent on -unless should tally with -names in this case.
