### ISSUE TITLE
Nodegroup matching in pillars via salt-SSH?

### ISSUE THREAD

**Issue by lichtamberg** [saltstack/salt#25292]
I tried now to move all specified grain.ids from the pillarfile to my master.conf...

In the state-files it works really great.. but not so in the pillars...
The states are filtered quite fine, but the pillars are just empty for my specified nodegroups..

Is it not possible there or do I have a mistake?

```yml
# top.sls - states

base:
  '*':
    - ntp
    - openssl
    - postfix
    - postfix.config

  mytest2:
    - match: nodegroup
    - couchdb
    - unicorn
```
```yml
# master.conf

nodegroups:
  mytest1:      L@myserver1,myserver2
  mytest2: L@myserver2,myserver3

```
```yml
# top.sls - pillars

base:
  '*':
    - base
    - users
    - sudoers
    - openssh

  mytest2:
    - match: nodegroup
    - nginx.certs
```

When I try to match them via 'N@...' i get just an error message:

```yml
# top.sls - pillars

base:
  '*':
    - base
    - users
    - sudoers
    - openssh

  'N@mytest2':
    - nginx.certs
```

```shell
[ERROR   ] Detected nodegroup expansion failure of "N@mytest2"
[ERROR   ] Detected nodegroup expansion failure of "N@mytest2"
```

```shell
# salt-ssh --versions-report
Salt Version:
           Salt: 2015.5.0-1720-gd41068f

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.9 (default, Jan  7 2015, 11:50:42)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 4.0.5
          ioflo: 1.2.1
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
       pycrypto: 2.6.1

System Versions:
           dist:
        machine: x86_64
        release: 13.4.0
         system: 10.9.5 -- x86_64
```

Any hints?

**Comment by basepi** [comment]
Hrm, I'm not sure what's going on here, but everything looks to be in order. We'll investigate this.

**Comment by pklemenkov** [comment]
What's up with this issue?

**Comment by vutny** [comment]
@lichtamberg,  @pklemenkov,

As far as I get it, `N@` classifier is nodegroup nesting feature available only in master config file, it can't be used to target minions in the state or pillar top files.
See the doc: https://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html

`- match: nodegroup` is the only way to match a nodegroup in your top file.

Sounds more like a feature request than a bug to me.

**Comment by basepi** [comment]
I also noticed another error. You must define the match type in your topfile:

```
base:
  '*':
    - base
    - users
    - sudoers
    - openssh

  'mytest2':
    - match: nodegroup
    - nginx.certs
```

I think this may actually not be a bug.

**Comment by lichtamberg** [comment]
Hmm... OK.. I'm not sure if I understood everything correct (please excuse, I'm still learning salt :)), so I will precise what I want to achieve:

```yaml
# Set pillar data for groups of minions
# pillars/top.sls
base:
  '*':
    - basethings
    - openssh

  # Match multiple groups via node-name matcher
  'N@mytest1,mytest2':
    - nginx.certs.{{ grains.id }}
```
and deploy them via salt-ssh like 

```bash
# myserver1 is part of mytest1, so it should get the corresponding pillars
salt-ssh 'myserver1' state.highstate
# And here I get the errors:

[ERROR   ] Detected nodegroup expansion failure of "N@mytest1"
[ERROR   ] Detected nodegroup expansion failure of "N@mytest1"
``` 

When I set in my pillar.top-file the -match: nodegroup, like:

```yaml
# pillars/top.sls

  'N@mytest1':
    - match: nodegroup
    - nginx.certs.{{ grains.id }}

```
then there are no errors, but the pillar-files are not included and all my pillar data will become 'None',...

**Comment by lichtamberg** [comment]
@vutny Ah ok, I think i realized now that the N@...-matcher really works only in the master.conf file.. and not in other state/pilla-top-files... There I only can use one group name and I have to add  the nodegroup matcher:

```
# Works
mygroup1:
    - match: nodegroup

# Not implemented/Not working
N@mygroup1,mygroup2:
    - ...

```
Did I understand this correctly? If yes, are there any plans to integrate the nodegroup matchers (multiple entries) into the top files? Thanks!

**Comment by lichtamberg** [comment]
Yeah... It doesnt work how I expect it...  :(

```yaml
# Works
'L@myserver1,myserver2':
    - nginx.certs

# Doesnt work
  'N@flave':
    - nginx.certs

# Also doesn't work
  'N@flave':
    - match: nodegroup
    - nginx.certs
```
Any hints?

**Comment by basepi** [comment]
Hmmm, it's possible that the pillar files didn't get the same treatment to make the last example work.... Any chance you could test with normal salt instead of salt-ssh to eliminate salt-ssh as the culprit?

**Comment by vutny** [comment]
@lichtamberg Few things to check for you in the pillar file.
* ensure you defined the correct salt 'environment' (I assume you only use 'base')
* check YAML indentation in `top.sls` file carefully, this is important
* restart your `salt-master` after making changes in the config

I'd rewrite your whole example like this:

```
# pillar/top.sls
base:

  # OK - This is Allowed and Correct 
  'L@myserver1,myserver2':
    - nginx.certs

  # NO - will not work because it's not supported
  # See https://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html#targeting-nodegroups
  'N@mygroup1':
    - nginx.certs

  # NO - doesn't work for the same reason as above
  # Additional info: https://docs.saltstack.com/en/latest/topics/targeting/compound.html
  'N@mygroup1':
    - match: nodegroup
    - nginx.certs

  # YES, it should work. But remove previous erroneous entries before you test. 
  'mygroup1':
    - match: nodegroup
    - nginx.certs
```

If I understand it correctly, the main purpose of `N@` classifier is to configure nodegroups which include other nodegroups like this:
```
# /etc/salt/master
nodegroups:
  mygroup1: 'L@myserver1,myserver2'
  mygroup2: 'myserver3'
  mygroup3: 'N@mygroup1 or N@mygroup2'
```

So, `mygroup3` includes minions from `mygroup1` and `mygroup2`.

I hope my explanation was helpful.

**Comment by The-Loeki** [comment]
This is most definitely *not* isolated to Salt-SSH.
We have the same problem here;

```
'example* or N@examplegroup':
  - match:compound
  - bla
```

FWIW it's a git pillar and it hits the error in `compound_match` in `salt/minion.py`, not the utils one.

**Comment by vutny** [comment]
@The-Loeki You're right, that's not limited to `salt-ssh`. But pay attention to the documentation, the `N@` classifier feature is not supported  in compound matches:
https://docs.saltstack.com/en/latest/topics/targeting/compound.html

The only place where it is recognized is master config file, `nodegroups` section.
You could rewrite your example like this:

````
#/etc/salt/master
nodegroups:
  examplegroup: 'L@foo.domain.com,bar.domain.com,baz.domain.com or bl*.domain.com'
  pillargroup: 'example* or N@examplegroup'

#/srv/pillar/top.sls
base:
  'pillargroup':
    - match: nodegroup
    - bla
```

See also: https://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html
