### ISSUE TITLE
Salt mistakenly reports meta package installation as false

### ISSUE THREAD

**Issue by HontoNoRoger** [saltstack/salt#25291]
I'm installing the ownCloud Ubuntu / Debian packages via Salt. Since ownCloud 8, there is a more modular setup and the package owncloud is now split into 3 different packages.
The owncloud package is just a virtual package, directing to these three.

So when installing the virtual package `owncloud` all thee of these packages get installed, which is what I want. But Salt lists the installation as false:

```
----------
          ID: owncloud_packages
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: owncloud 3 targeted packages were installed/updated.
     Started: 13:19:44.576604
    Duration: 65090.76 ms
     Changes:   
              …
----------
```

After another run, it correctly shows the already installed packages.

```
----------
          ID: owncloud_packages
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: owncloud The following packages were already installed: php5-gd, php5-intl, php5-mysql
     Started: 13:59:36.404568
    Duration: 12338.485 ms
     Changes:   
              ----------
              owncloud:
                  ----------
                  new:
                      8.1.0-2
                  old:
              owncloud-config-apache:
                  ----------
                  new:
                      8.1.0-2
                  old:
              owncloud-mysql:
                  ----------
                  new:
                      1
                  old:
              owncloud-pgsql:
                  ----------
                  new:
                      1
                  old:
              owncloud-sqlite:
                  ----------
                  new:
                      1
                  old:
```

So the fix should probably list  "x targeted packages were installed/updated." as successful.

**Comment by jfindlay** [comment]
@HontoNoRoger, what is the output of `salt <minion> test.versions_report`?

**Comment by HontoNoRoger** [comment]
Sorry i forgot that:

```
owncloud:
                      Salt: 2015.5.2
                    Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                    Jinja2: 2.7.2
                  M2Crypto: 0.21.1
            msgpack-python: 0.3.0
              msgpack-pure: Not Installed
                  pycrypto: 2.6.1
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: 14.0.1
                      RAET: Not Installed
                       ZMQ: 4.0.4
                      Mako: 0.9.1
     Debian source package: 2015.5.2+ds-1trusty1
```
