### ISSUE TITLE
Windows Minion Receiving "403 Forbidden" When Downloading New Minion Installer

### ISSUE THREAD

**Issue by MaDaTyGo** [saltstack/salt#25303]
Wireshark shows the attempt:
---
```
GET /downloads/Salt-Minion-2014.7.5-2-AMD64-Setup.exe HTTP/1.1
Host: docs.saltstack.com
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.5.3 CPython/2.7.8 Windows/7
```
---
```
HTTP/1.1 403 Forbidden
Server: nginx
Date: Thu, 09 Jul 2015 21:16:04 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Keep-Alive: timeout=20
```

However, a Windows-based WGET successfully completes:
---
```
GET /downloads/Salt-Minion-2014.7.5-2-AMD64-Setup.exe HTTP/1.0
User-Agent: Wget/1.11.4
Accept: */*
Host: docs.saltstack.com
Connection: Keep-Alive
```
---
```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 09 Jul 2015 21:16:07 GMT
Content-Type: application/octet-stream
Content-Length: 17906149
Last-Modified: Wed, 13 May 2015 22:48:15 GMT
Connection: keep-alive
Keep-Alive: timeout=20
X-Type: static/generic
Cache-Control: public, max-age=2592000
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
```

Windows minion info:
---
```
           Salt: 2014.7.5
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.5
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
Windows repo file:
---
```
salt-minion-AMD64:
  2014.7.5-2:
    full_name: 'Salt Minion 2014.7.5-2'
    installer: http://docs.saltstack.com/downloads/Salt-Minion-2014.7.5-2-AMD64-Setup.exe
    reboot: False
    install_flags: '/S'
    uninstaller: 'C:\salt\uninst.exe'
    uninstall_flags: '/S'
    refresh: True
```

state file:
---
```
salt-minion:
  pkg.installed:
    - name: salt-minion-AMD64
```
