### ISSUE TITLE
test.version reports 2015.5.0 from 2015.5.3 tarball

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#25307]
I grabbed the tarball from https://github.com/saltstack/salt/releases/tag/v2015.5.3 and built it into an rpm. When installed on a minion, the minion reports the following:

```
ahammond@saltm.anchorfree.net[inf-sj-sam-1]:~ $ sudo salt prd-mi-uhs-1052 test.versions_report
prd-mi-uhs-1052:
               Salt: 2015.5.0
             Python: 2.6.6 (r266:84292, Dec  7 2011, 20:48:22)
             Jinja2: 2.7.3
           M2Crypto: 0.20.2
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: 1.4.3
             PyYAML: 3.11
              ioflo: 1.3.2
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed
            Tornado: Not Installed
ahammond@saltm.anchorfree.net[inf-sj-sam-1]:~ $ sudo salt prd-mi-uhs-1052 test.version
prd-mi-uhs-1052:
    2015.5.0
```
