### ISSUE TITLE
[orchestrate] Can't wheel accept keys in orchestrator (saltmod.py)

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#25318]
```
accept_minion_key_{{ host }}:
  salt.wheel:
    - name: key.accept
    - match: {{ host }}
```
does not work (but returns as True). 

I then tried with accept_dict since kwargs is send as a dict: 

```
accept_minion_key_{{ host }}:
  salt.wheel:
    - name: key.accept_dict
    - match: {{ host }}
```

not better. Reading some of the code I tried the minion id a key to the kwargs dict

```
accept_minion_key_{{ host }}:
  salt.wheel:
    - name: key.accept_dict
    - {{ host }} : True
```

not better. 

I give up, it really feels like a bug. 

```
root@ursa:~# salt-run --versions-report
                  Salt: 2015.5.2
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.2+ds-1trusty1

```
