### ISSUE TITLE
Unable to use kwarg in salt.function (modules.saltmod)

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#25317]
I am unable to find a way to feed kwargs through the salt-run state.orchestrate orchestration. 

```
test salt.function:
  salt.function:
    - name: cmd.run
    - tgt: ursa
   - arg:
     - cd /tmp && pwd && whoami
   - kwarg:
       runas: nobody
```

returns 

```
ursa_master:
----------
          ID: test salt.function
    Function: salt.function
        Name: cmd.run
      Result: True
     Comment: Function ran successfully. Function cmd.run ran on ursa.
     Started: 12:36:51.534337
    Duration: 157.066 ms
     Changes:   
              ursa:
                  /tmp
              root
    Warnings: 'runas' is an invalid keyword argument for 'salt.function'. If you
              were trying to pass additional data to be used in a template
              context, please populate 'context' with 'key: value' pairs. Your
              approach will work until Salt Carbon is out. Please update your
              state files.

```

tried a good variation of combinations like 

```
   - kwarg:
      context:
         runas: nobody
```

with no luck. 

Can't find a way to get it to work. Is it broken or is the documentation incomplete ?

**Comment by arthurlogilab** [comment]
I almost forgot 

```
# salt-run --versions-report
                  Salt: 2015.5.2
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.2+ds-1trusty1
```

**Comment by cldmnky** [comment]
Any updates on this, I'm having the same issue, I'm unable to pass kwarg while running an orchestration job:

```
install elasticsearch 1.7 {{h}}
  salt.function:
    - name: pkg.install
    - tgt: '{{h}}'
    - kwarg:
      sources:
      - elasticsearch: ''https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.0.noarch.rpm'''
    - require:
      - salt: stop cluster routing allocation {{h}}
```
```
# salt-run --versions-report
           Salt: 2015.5.2
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
```
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5

**Comment by cldmnky** [comment]
So, it was an indentation issue:
```
test_kwargs:
  salt.function:
    - name: http.query
    - tgt: '*'
    - kwarg:
        method: POST
    - arg:
      - "http://www.sunet.se"
```
The kwarg needs to indented correctly, then it works!
