### ISSUE TITLE
file.uncomment: regex with multiple patterns ignores others if one is already uncommented

### ISSUE THREAD

**Issue by MoonSweep** [saltstack/salt#25345]
Hi,

Sorry if the title isn't clear (english isn't my native language).

Here's the problem: since two states can't have the same name, if I want to uncomment several different lines in the same file, I have to use "|" to create a regexp with multiple patterns, like this:

```
vim:
  file.uncomment:
    - name: /etc/vim/vimrc
    - char: '"'
    - regex: (syntax on|set (background=dark|showcmd|showmatch|ignorecase))
```

The problem with this technique is that if a pattern is already uncommented, others are ignored completely:

```
----------
          ID: vim
    Function: file.uncomment
        Name: /etc/vim/vimrc
      Result: True
     Comment: Pattern already uncommented
     Started: 14:03:52.937717
    Duration: 1.016 ms
     Changes:   
```

This is really annoying. For example, if you already have manually uncommented one line in the file, Salt won't ensure that the other lines are uncommented; or, if you change your regexp over time to include new pattern(s), those additions will be ignored when the state is run after the change.

Please fix this (or allow functions to accept several "regex" lines).
