### ISSUE TITLE
Can not override file_roots and pillar_roots with salt --config-dir option

### ISSUE THREAD

**Issue by MrCitron** [saltstack/salt#25344]
Hi,
here is my use case : our states and pillars comes from a git repo and are cloned in the master filesystem as file_roots and pillar_roots.

/etc/salt/master.d/custom.conf :

```
file_roots:
  base:
    - /app/cd-factory/salt-states

pillar_roots:
  base:
    - /app/cd-factory/salt-pillars
```

But now, we want to control what revision for the states and pillars for every salt command we run (inside jenkins job for example)

I thought I just need to copy the conf file into a per job directory and alter the file_roots and pillar_roots as follows :

$myworkspace/conf/master :

```
file_roots:
  base:
    - $myworkspace_dir/cd-factory/salt-states

pillar_roots:
  base:
    - $myworkspace_dir/cd-factory/salt-pillars
```

and run salt command with _-c $myworkspace/conf_.

This is not working without restarting the master daemon and even then it seems like my specific configuration does not override the general one.

Maybe this is not the right way to achieve my goal and any other solution to handle this use case is welcome.
