### ISSUE TITLE
ssh_auth.present in test=True reports unnecessary changes

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#25364]
If you run `salt-call state.highstate test=True` and the state contains a `ssh_auth.present` it always results in an item marked as "to be changed":

```
----------
          ID: userx
    Function: ssh_auth.present
      Result: None
     Comment: Set to update: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     Started: 10:10:28.674102
    Duration: 15.437 ms
     Changes:   
```

Most likely the `result: None` should be changed to `result: True` in case the user already exists. The same is the case for other states (e.g. `service.running`).
