### ISSUE TITLE
file.replace removes line feed if using YAML's multiline string syntax

### ISSUE THREAD

**Issue by BretFisher** [saltstack/salt#25360]
On Ubuntu 14.04 with Salt `v2015.5.2` if I choose to use the YAML multiline string syntax for `file.replace` (as suggested for complex regex scenarios) the line feed is removed as part of the `pattern`. Is this expected or a bug? 

file before:

```
configuration file example
line 2
line 3
```

``` yaml
test:
  file.replace:
    - name: /root/test.conf
    - pattern: |
        configuration file example
    - repl: configuration x file example
```

file after:

```
configuration x file example line 2
line 3
```
