### ISSUE TITLE
Not able to use static data from pillar in state (salt 2015.5.2 (Lithium))

### ISSUE THREAD

**Issue by mooperd** [saltstack/salt#25481]
Hi, 

I may be being rather stupid here but this is not working for me:

The data is present in the pillar.

```
{%- set s3_aws_access_key_id = "XXX"  %}
{%- set s3_aws_access_key = "XXX" %}
{%- set region = "eu-west-1" %}
aws_access_key_id: {{ s3_aws_access_key_id }}
s3_aws_access_key: {{ s3_aws_access_key }}
region: {{ region }}
```

```
salt '*' pillar.items --out=json
<snip>
{
    "piwik053": {
        "s3_aws_access_key": "XXX", 
        "mine_functions": {
            "network.ip_addrs": [
                "eth0"
            ]
        }, 
        "region": "eu-west-1", 
        "aws_access_key_id": "XXX"
    }
}
```
Im using in the state like this:
```
[root@master salt]# cat set-aws-key/config 
[default]
region = {{ pillar.region }}
aws_access_key_id = {{ pillar.aws_access_key_id }}
aws_secret_access_key = {{ pillar.aws_access_key }}
output = json
[root@master salt]# cat set-aws-key/init.sls 
/home/centos/.aws/config:
  file.managed:
    - source: salt://set-aws-key/config
    - template: jinja
```
But get the following with state.highstate
```
----------
          ID: /home/centos/.aws/config
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'dict object' has no attribute 'aws_access_key'
     Started: 14:08:34.252502
    Duration: 11.202 ms
     Changes:  
```
