### ISSUE TITLE
dockerng: Changes required for docker-py 1.3.0 (API version 1.19)

### ISSUE THREAD

**Issue by shift** [saltstack/salt#25509]
The dockerng documentation states a version of docker-py after 1.0.0 should work but using 1.3.0 fails when using `memory:`.

While running this SLS via salt-ssh:
```
/srv/elasticsearch:
  file.directory:
    - user: root
    - group: root
    - mode: 755
    - makedirs: True

shift/elasticsearch:1.5.2:
  dockerng.image_present

shift/elasticsearch:
  dockerng.running:
    - name: elasticsearch
    - image: shift/elasticsearch:1.5.2
    - domainname: ams2.infra
    - port_bindings:
      - "{{ salt['network.interfaces']()['eth1']['inet'][0]['address'] }}:9200:9200/tcp"
      - "{{ salt['network.interfaces']()['eth1']['inet'][0]['address'] }}:9300:9300/tcp"
    - binds: /data:/srv/elasticsearch:rw
    - restart_policy: always
    - cpu_shares: 2
    - cpuset: '1'
    - memory: 512M
    - memory_swap: 1G
    - require:
      - dockerng: shift/elasticsearch:1.5.2
```
I get:
```
            "dockerng_|-shift/elasticsearch_|-elasticsearch_|-running": {
                "comment": "Failed to create new container: Unable to perform create_container: mem_limit has been moved to host_config in API version 1.19", 
                "name": "elasticsearch", 
                "start_time": "07:42:11.450553", 
                "result": false, 
                "duration": 86.623, 
                "__run_num__": 11, 
                "changes": {}
            }, 
```

```
# pip list | grep docker-py
docker-py (1.3.0)
```

Do the docs need amending to be more precise on the version or is there changes required for the new docker-py?
