### ISSUE TITLE
Setting alternatives to auto doesn't "stick"

### ISSUE THREAD

**Issue by klatiss** [saltstack/salt#25504]
Master and minion: 2015.5.0, minions a mix of CentOS 6 and 7

When using the alternatives system to set a default, for (in my case) java the state applies successfully however if I run another highstate immediately afterwards it applies it again. Example:

``` yaml
$ cat java/openjdk/init.sls 
java:
  pkg:
    - installed
    - name: java-{{ salt['grains.get']('openjdk:version') }}-openjdk

java-alternatives:
  alternatives.auto:
    - name: java

jre_openjdk-alternatives:
  alternatives.auto:
    - name: jre_openjdk

jre_version-alternatives:
  alternatives.auto:
    - name: jre_{{ salt['grains.get']('openjdk:version') }}
```

``` yaml
$ salt -t 60 'hostname' state.sls java.openjdk
hostname:
----------
          ID: java-alternatives
    Function: alternatives.auto
        Name: java
      Result: True
     Comment: 
     Started: 10:15:50.406582
    Duration: 35.774 ms
     Changes:   
              ----------
              result:
----------
          ID: jre_openjdk-alternatives
    Function: alternatives.auto
        Name: jre_openjdk
      Result: True
     Comment: 
     Started: 10:15:50.447919
    Duration: 18.559 ms
     Changes:   
              ----------
              result:
----------
          ID: jre_version-alternatives
    Function: alternatives.auto
        Name: jre_1.7.0
      Result: True
     Comment: 
     Started: 10:15:50.472841
    Duration: 22.742 ms
     Changes:   
              ----------
              result:

Summary
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
```

And then, if I run it again it applies the same 3 states again as if the states need changing.

**Comment by jfindlay** [comment]
@klatiss, thanks for the report.

**Comment by cachedout** [comment]
Could you please give us the output of the following:

`salt <hostname> alternatives.display java`
`salt <hostname> alternatives.display jre_openjdk`

The code in this state [`salt.states.alternatives`] to detect if the change is pretty simple and might just need a small tweak. I've copied it below for reference:

```
def auto(name):
    '''
    .. versionadded:: 0.17.0

    Instruct alternatives to use the highest priority
    path for <name>

    name
        is the master name for this link group
        (e.g. pager)

    '''
    ret = {'name': name,
           'result': True,
           'comment': '',
           'changes': {}}

    display = __salt__['alternatives.display'](name)
    isinstalled = False
    line = display.splitlines()[0]
    if line.endswith(' auto mode'):
        ret['comment'] = '{0} already in auto mode'.format(name)
        return ret

    if __opts__['test']:
        ret['comment'] = '{0} will be put in auto mode'.format(name)
        ret['result'] = None
        return ret
    ret['changes']['resu
```

**Comment by klatiss** [comment]
I'm going to guess that the line doesn't end with "auto mode" any longer but just "auto.".

```
$ salt 'hostname' alternatives.display java
hostname: java - status is auto.
hostname:  link currently points to /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre/bin/java
hostname: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre/bin/java - priority 1700079
hostname:  slave keytool: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre/bin/keytool
hostname:  slave orbd: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre/bin/orbd
hostname:  slave pack200: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre/bin/pack200
hostname:  slave rmid: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre/bin/rmid
hostname:  slave rmiregistry: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre/bin/rmiregistry
hostname:  slave servertool: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre/bin/servertool
hostname:  slave tnameserv: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre/bin/tnameserv
hostname:  slave unpack200: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre/bin/unpack200
hostname:  slave jre_exports: /usr/lib/jvm-exports/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64
hostname:  slave jre: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre
hostname:  slave java.1.gz: /usr/share/man/man1/java-java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64.1.gz
hostname:  slave keytool.1.gz: /usr/share/man/man1/keytool-java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64.1.gz
hostname:  slave orbd.1.gz: /usr/share/man/man1/orbd-java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64.1.gz
hostname:  slave pack200.1.gz: /usr/share/man/man1/pack200-java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64.1.gz
hostname:  slave rmid.1.gz: /usr/share/man/man1/rmid-java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64.1.gz
hostname:  slave rmiregistry.1.gz: /usr/share/man/man1/rmiregistry-java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64.1.gz
hostname:  slave servertool.1.gz: /usr/share/man/man1/servertool-java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64.1.gz
hostname:  slave tnameserv.1.gz: /usr/share/man/man1/tnameserv-java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64.1.gz
hostname:  slave unpack200.1.gz: /usr/share/man/man1/unpack200-java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64.1.gz
hostname: /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/java - priority 16000
hostname:  slave keytool: /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/keytool
hostname:  slave orbd: /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/orbd
hostname:  slave pack200: /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/pack200
hostname:  slave rmid: /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/rmid
hostname:  slave rmiregistry: /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/rmiregistry
hostname:  slave servertool: /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/servertool
hostname:  slave tnameserv: /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/tnameserv
hostname:  slave unpack200: /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/unpack200
hostname:  slave jre_exports: /usr/lib/jvm-exports/jre-1.6.0-openjdk.x86_64
hostname:  slave jre: /usr/lib/jvm/jre-1.6.0-openjdk.x86_64
hostname:  slave java.1.gz: /usr/share/man/man1/java-java-1.6.0-openjdk.1.gz
hostname:  slave keytool.1.gz: /usr/share/man/man1/keytool-java-1.6.0-openjdk.1.gz
hostname:  slave orbd.1.gz: /usr/share/man/man1/orbd-java-1.6.0-openjdk.1.gz
hostname:  slave pack200.1.gz: /usr/share/man/man1/pack200-java-1.6.0-openjdk.1.gz
hostname:  slave rmid.1.gz: /usr/share/man/man1/rmid-java-1.6.0-openjdk.1.gz
hostname:  slave rmiregistry.1.gz: /usr/share/man/man1/rmiregistry-java-1.6.0-openjdk.1.gz
hostname:  slave servertool.1.gz: /usr/share/man/man1/servertool-java-1.6.0-openjdk.1.gz
hostname:  slave tnameserv.1.gz: /usr/share/man/man1/tnameserv-java-1.6.0-openjdk.1.gz
hostname:  slave unpack200.1.gz: /usr/share/man/man1/unpack200-java-1.6.0-openjdk.1.gz
hostname: Current `best' version is /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre/bin/java.
```

```
$ salt 'hostname' alternatives.display jre_openjdk
hostname: jre_openjdk - status is auto.
hostname:  link currently points to /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre
hostname: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre - priority 1700079
hostname:  slave jre_openjdk_exports: /usr/lib/jvm-exports/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64
hostname: /usr/lib/jvm/jre-1.6.0-openjdk.x86_64 - priority 16000
hostname:  slave jre_openjdk_exports: /usr/lib/jvm-exports/jre-1.6.0-openjdk.x86_64
hostname: Current `best' version is /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79-2.5.5.2.el7_1.x86_64/jre.
```

**Comment by klatiss** [comment]
Oops - didn't mean to close.

**Comment by RobotLimeLtd** [comment]
Simple workaround for this:

```
java-alternatives:
  alternatives.auto:
    - name: java
    - unless: alternatives --display java | head -1 | grep 'status is auto' > /dev/null 2>&1
```
