### ISSUE TITLE
salt highstate schedule cannot be removed

### ISSUE THREAD

**Issue by dennisjac** [saltstack/salt#25540]
Hi,
I'm trying to stop a minion from doing a highstate run every 10 minutes via the scheduler but that seems to be impossible:
```
0 root@salt1-cfg2.service ~ # salt 'test1centos7-cfg2.service' schedule.list show_all=True
test1centos7-cfg2.service:
    schedule:
      __mine_interval:
        function: mine.update
        jid_include: true
        maxrunning: 2
        minutes: 60
        name: __mine_interval
      highstate:
        function: state.highstate
        jid_include: true
        maxrunning: 1
        minutes: 10
        name: highstate
0 root@salt1-cfg2.service ~ # salt 'test1centos7-cfg2.service' schedule.delete highstate
test1centos7-cfg2.service:
    ----------
    comment:
        Deleted Job highstate from schedule.
    result:
        True
0 root@salt1-cfg2.service ~ # salt 'test1centos7-cfg2.service' schedule.list show_all=True
test1centos7-cfg2.service:
    schedule:
      __mine_interval:
        function: mine.update
        jid_include: true
        maxrunning: 2
        minutes: 60
        name: __mine_interval
      highstate:
        function: state.highstate
        jid_include: true
        maxrunning: 1
        minutes: 10
        name: highstate
```

As you can see saltstack says it deleted the highstate job from the schedule but that isn't actually the case. How can I make the minion properly stop to run a highstate job every 10 minutes?
