### ISSUE TITLE
Salt Could should have a way to define an entire infrastructure

### ISSUE THREAD

**Issue by ryanwalder** [saltstack/salt#25555]
At present the map file is pretty limited in what it can do in the fact it will only spin up instances not other resources (unless I'm missing something) and overstate seems to be dead, ideally you should be able to define an entire infrastructure (cross provider) through a mapfile/overstate style system.

My thinking is something similar to how you would write states would be a really powerful way of doing things, especially if you have a reasonably static infrastructure:

``` YAML
test-network:
  gce_network.present:
    - name: test
    - addresses: 10.0.0.1/8
    - gateway: 10.0.0.1

office-firewall:
  gce_firewall.present:
    - name: all-from-office
    - network: test
    - source_filter: ip
    - source_range: 123.123.123.123/32
    - rules: "udp:0-65535; icmp; tcp:0-65535"
    - require:
      - gce_network: test-network

web-firewall:
  gce_firewall.present:
      - name: web
      - network: test
      - source_filter: any
      - rules: "tcp:80,443"
      - target_tags: "web"
      - require:
        - gce_network: test-network

web-instance-disk:
    gce_disk.present:
      - name: web-data
      - type: ssd
      - image: None
      - delete_with_instance: False

web-instance-machine:
  gce_instance.present:
    - name: web-01
    - type: n1-standard-1
    - disk_name: web-01
    - delete_disk: True
    - disk_image: ubuntu-1404
    - network: test
    - zone: europe-west1-b
    - tags:
      - web
      - foo
    - require:
      - gce_disk: web-instance-disk
      - gce_firewall: web-firewall
      - gce_network: test-network

aws-web-01-dns:
  aws_route53.present:
    - name: web-01
    - type: A
    - value: <web-01.gce_instance.ip>
```

The main issue I can see here is self referencing things which haven't been created yet (as seen in the DNS block at the bottom) and that rather than defining full instances using a profile may be better (assuming a definition could override things if needed)
