### ISSUE TITLE
AWS Security groups cannot be specified along with network interfaces

### ISSUE THREAD

**Issue by Enquier** [saltstack/salt#25569]
When specifying a new network interface in AWS you cannot specify
```yaml
    securitygroup:
      - mysecuritygroup
    network_interfaces:
      - DeviceIndex: 0
        PrivateIpAddresses:
          - Primary: True
        #auto assign public ip (not EIP)
        AssociatePublicIpAddress: True
        SubnetId: subnet-xxxx
```

Error code:
```
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': 'Network interfaces and an instance-level security groups may not be specified on the same request', 'Code': 'InvalidParameterCombination'}}, 'RequestID': '8f35e3fd-9dfe-49d9-8efd-b4944c2ba9ff'}
```
Might be good to clarify documentation for AWS network interfaces or create a code fix for this to allow specification of groups and interfaces on separate calls

**Comment by jfindlay** [comment]
@Enquier, thanks for the report.  What is the output of `salt --versions-report`?

**Comment by Enquier** [comment]
Salt: 2015.5.2
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

**Comment by Enquier** [comment]
So the workaround that I discovered is to specify the security group by it's id within the network interface:
   ``` 
    network_interfaces:
      - DeviceIndex: 0
        PrivateIpAddresses:
          - Primary: True
        #auto assign public ip (not EIP)
        AssociatePublicIpAddress: True
        SubnetId: subnet-xxxx
        SecurityGroupId: 
          - sg-xxxxxx
   ```
However this limits my use-case where I'd like to specify network connections (specifically subnets) and then extend to change the security groups for various machine types
