### ISSUE TITLE
Salt 2015.5.X - mine.update : Got a bad pillar from master

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#25579]
After update from 2014.7 i found that minions occasionaly sends empty data during mine.update. Problem occurs on minions with 2015.5.0 and 2015.5.2, 2014.7 works well. Only  error message is on minion side:

<pre>
2015-07-20 11:40:00,437 [salt.pillar                              ][ERROR   ][4951] Got a bad pillar from master, type NoneType, expecting dict: None
</pre>

Master version:
<pre>
           Salt: 2015.5.2
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
<pre>

**Comment by jfindlay** [comment]
@msciciel, thanks for the report.

**Comment by msciciel** [comment]
Any chances for quick investigation and fix ? Mine is crucial for us because it's used to configure central system base on data provided from all minions.

**Comment by jfindlay** [comment]
@msciciel, we'll be looking at this soon, although I can't say right now when it will be fixed, thanks.

**Comment by TOoSmOotH** [comment]
I can confirm I am seeing this issue as well. It would be nice if the highstate would cancel itself if it got the following error and let it try again on next highstate:

    2015-07-18 14:10:18,754 [salt.pillar      ][ERROR   ][7653] Got a bad pillar from master, type NoneType, expecting dict: None

Currently to fix this we are running highstate manually by specifying the master in the command since we use pillar data in our minion file. Another thing I should mention is we have close to 500 minions that highstate every 15 minutes and when it happens it will only be a single host that the pillar fails on. The occurrence is very sporadic so it has made troubleshooting it difficult. We had it happen last night to 2 different hosts but it has been weeks since we had this issue so again it is very sparse.

**Comment by msciciel** [comment]
Any chances for fix ?

**Comment by jfindlay** [comment]
@msciciel, this issue has been scheduled to be fixed during the Boron development cycle, so it should be soon.

**Comment by soodr** [comment]
Noticed this error persisting after upgrading the Salt version on master to 2015.5.5.
The output of a Salt api call to execute a high state on the minion \:
```
{u'return': [{u'data': {u'test340-db-1': u'The minion function caused an exception: 
Traceback (most recent call last):
File "c:\\salt\\bin\\lib\\site-packages\\salt\\minion.py", line 1146, in _thread_return
    return_data = func(*args, **kwargs)
File "c:\\salt\\bin\\lib\\site-packages\\salt\\modules\\state.py", line 645, in sls
st_ = salt.state.HighState(opts, pillar, kwargs.get(\'__pub_jid\'))
File "c:\\salt\\bin\\lib\\site-packages\\salt\\state.py", line 3028, in __init__
BaseHighState.__init__(self, opts)
File "c:\\salt\\bin\\lib\\site-packages\\salt\\state.py", line 2208, in __init__
self.avail = self.__gather_avail()
File "c:\\salt\\bin\\lib\\site-packages\\salt\\state.py", line 2217, in __gather_avail
for saltenv in self._get_envs():
File "c:\\salt\\bin\\lib\\site-packages\\salt\\state.py", line 2268, in _get_envs
   return envs.union(set(self.client.envs()))
  File "c:\\salt\\bin\\lib\\site-packages\\salt\\fileclient.py", line 1186, in envs
   return self.channel.send(load)\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\transport\\__init__.py", line 314, in send
    return self._crypted_transfer(load, tries, timeout)\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\transport\\__init__.py", line 305, in _crypted_transfer\n    return _do_transfer()
  File "c:\\salt\\bin\\lib\\site-packages\\salt\\transport\\__init__.py", line 299, in _do_transfer
    data = self.auth.crypticle.loads(data)\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\crypt.py", line 841, in loads
    data = self.decrypt(data)\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\crypt.py", line 818, in decrypt
    raise AuthenticationError(\'message authentication failed\')
AuthenticationError: message authentication failed
'}}]}
```

**Comment by msciciel** [comment]
Any updates ? This bug makes mine subsystem useless.

**Comment by basepi** [comment]
@msciciel Do you see any errors in the master debug log when this happens? I've been told that the pillar system can return None when an error occurs during pillar compilation.

**Comment by msciciel** [comment]
If there is a true error(ie. syntax error) in pillar then this is logged on master. But in this case nothing is logged on master, only on minion side. This bug was introduced in 2015.5.

**Comment by basepi** [comment]
I guess I'm just searching for a consistent way to reproduce this. I have never seen it to date.

**Comment by msciciel** [comment]
In my case mine.update is executed only when specific pillar values are set and they have changed so its weird that mine data which contains few pillar keys of the host is empty.

**Comment by msciciel** [comment]
I was executing pillar.items in loop for a while and its always returns good data. Something is going wrong during mine.update call I think but I have no idea what. I was searching for changes in mine subsytem between 2014.7 and 2015.5 but I didn't find any clues.

**Comment by basepi** [comment]
How often can you get it to fail on mine.update?

**Comment by msciciel** [comment]
20 minions out of 800 with this version of salt. Highstate is executed with 4 hours interval.

**Comment by basepi** [comment]
I have a feeling this one is going to be painful. It's still on my list.

**Comment by msciciel** [comment]
i dont have enough knowledge to find out what have changed between 2014.7 and 2015.5 in code revelant to this issue. After upgrading master to 2015.5.5 problems still exists only on 2015.5 minions so I think its related to minion side but I can be wrong.

**Comment by msciciel** [comment]
I've found that problem occurs on nodes which have file /etc/salt/minion.d/_schedule.conf:
```yaml
schedule:
  __mine_interval: {function: mine.update, jid_include: true, maxrunning: 2, minutes: 60}
```
I didn't create this file and in my case mine.update is only executed during highstate , not from schedule.

**Comment by msciciel** [comment]
Maybe below example will bring some freshness into this problem:

```
# /etc/salt/minion.d # rm _schedule.conf
# service salt-minion restart
# cat _schedule.conf
schedule:
  __mine_interval: {function: mine.update, jid_include: true, maxrunning: 2, minutes: 60}
root@storage2.krk.itg.cloud.iadm /etc/salt/minion.d # salt-call schedule.list
local:
    schedule:
      highstate:
        enabled: true
        function: state.highstate
        minutes: 240
# rm _schedule.conf
# service salt-minion restart
# cat _schedule.conf
schedule:
  __mine_interval: {function: mine.update, jid_include: true, maxrunning: 2, minutes: 60}
```

**Comment by basepi** [comment]
I think that's expected behavior on all minions. We use _schedule.conf for internal scheduling, as well as managing schedules through the schedule module/state. So when you set a mine_interval, I'm pretty sure the minion automatically updates this file to schedule the actual mine.update. I could, however, be wrong. Good info, thank you.

**Comment by msciciel** [comment]
To be more specific. All my minions have below pillar set:
```yaml
mine_functions:
  pillar.item: [db_type,db_master_host,db_slave_host,db_slave_active,httpd_stats,documentation,ip,hostgroup,backup,stats,nagios]

schedule:
  highstate:
    function: state.highstate
    minutes: 240
```

And mine.update is executed only during highstate with below states:
```yaml
{% if salt['pillar.get']('nagios', False) or salt['pillar.get']('stats', False) or salt['pillar.get']('backup', False) %}
mine:
  file.managed:
    - name: /var/cache/salt/minion/pillar.md5
    - mode: 600
    - user: root
    - group: root
    - contents: {{ salt['hashutil.md5_digest'](pillar|json) }}
  module.wait:
    - name: mine.update
    - require:
      - file: mine
    - watch:
      - file: mine
{% endif %}
```

So i have no idea what is the source of _schedule.conf because i have no place with mine.update defined with 1 hour interval. But mine.update is called with 1h interval and is updated even if there is some problems with pillar and empty data is send and my workaround with checking pillar data doesn't work because it's works only on highstate.

Maybe it's builtin into minion to call mine.update every hour which in my opinion could cause a lot of problems like this one.

**Comment by morsik** [comment]
`mine.update` schedule comes from `salt/minion.py` lines `702-713` (tag `v2015.5.1`):
```python
        # add default scheduling jobs to the minions scheduler
        if 'mine.update' in self.functions:
            log.info('Added mine.update to scheduler')
            self.schedule.add_job({
                '__mine_interval':
                {
                    'function': 'mine.update',
                    'minutes': opts['mine_interval'],
                    'jid_include': True,
                    'maxrunning': 2
                }
            })
```

**Comment by morsik** [comment]
Looks like refs #28467

**Comment by basepi** [comment]
This issue predates those changes substantially. But it's possible those changes could have improved the situation.

**Comment by msciciel** [comment]
In my opinion above behaviour to force mine.update from internal schedule is not the most wanted solution. It would be better to have control over this behaviour with possibility to disable it in configuration file.

**Comment by twellspring** [comment]
Just discovered this issue when one of my prod servers received the error `Got a bad pillar from master, type NoneType, expecting dict: None`   and the server's values in salt-mine are gone.   I use the salt-mine data to populate haproxy routing tables, so this error caused a production server to became unavailable meaning a service outage.   Looking a little more I see several other servers with no data in salt-mine and that error in the logs. 

Is there any workaround to prevent this error from removing the salt-mine values?  

```
           Salt: 2015.5.10
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.4.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 2.4.2
```

**Comment by msciciel** [comment]
We have following workaround for this.

1. Add pillar pillar_got_from_master to all hosts
```
pillar_got_from_master: True
```

2. Add state check.sls to all hosts in top.sls
```
{%  if not pillar.get('pillar_got_from_master', False) %}
check:
  test.fail_without_changes:
    - order: 1
    - failhard: True
{%  endif %}
```

It should end execution if pillar is not complete.

**Comment by twellspring** [comment]
Thanks, that's what I needed.

**Comment by twellspring** [comment]
The above workaround appears to work to prevent a highstate or state.sls from running if the pillar data is missing, but does not appear to prevent mine updates from happening.   So server data is still dropping out of the mine due to this error.  5b67cb5 does not appear to help with this.  Any other ideas?

I discovered in this process my salt-master has high memory usage and has some moderate IO Wait due to swapping ... thinking that might be related to the frequency of issue this happening.  Doing a server upgrade to fix that.

**Comment by twellspring** [comment]
Just had another incident of this.  Within about a minute, almost all of my servers had the triple `Got a bad pillar from master` error messages and they all dropped out of the salt mine.

```
    2016-06-17 20:53:37,170 [salt.pillar      ][ERROR   ][28589] Got a bad pillar from master, type NoneType, expecting dict: None
    2016-06-17 20:53:37,172 [salt.pillar      ][ERROR   ][28589] Got a bad pillar from master, type NoneType, expecting dict: None
    2016-06-17 20:53:37,174 [salt.pillar      ][ERROR   ][28589] Got a bad pillar from master, type NoneType, expecting dict: None
```
When I went to correlate with my salt-master log I find it has not updated in almost a day. Since my logging is default that says there have been no errors in the last day.   I just updated to debug so I will have more information from the master when this happens again.

**Comment by twellspring** [comment]
Thought on this.  I found that I have a large pillar being sent to the mine.  Is it possible that a large mine data could be contributing to the `Got a bad pillar from master`?

```
mine_functions:
  server_info:
    - mine_function: pillar.item
    - server_info
  ip_internal:
    mine_function: network.ip_addrs
    cidr: 192.168.0.0/16
  ip_external:
    mine_function: network.ip_addrs
    interface: eth0
```

And when I pull this mine item

```
#salt ord-salt-api-prod-2 mine.get ord-pro-web-stage-1 server_info | wc
     92     110    2518

#salt ord-salt-api-prod-2 mine.get ord-pro-web-stage-1 server_info | head -10
ord-pro-web-stage-1:
        ----------
        server_info:
            ----------
            app_users:
                ----------
                web:
                    absent
                www-data:
                    present
            cpus:
                1
```
