### ISSUE TITLE
Wrong indentation in document

### ISSUE THREAD

**Issue by yellow1912** [saltstack/salt#25577]
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.schedule.html

``` yaml
job1:
  schedule.present:
    - function: state.sls
    - args:
      - httpd
    - kwargs:
      test: True

```

Should be

``` yaml
job1:
  schedule.present:
    - function: state.sls
    - args:
      - httpd
    - kwargs:
        test: True

```

Also, are the kwargs supposed to be interpreted as the arguments of the function? 

I tried this but it doesn't seem to get the correct arguments:

``` yaml
job2:
    schedule.present:
      - function: cmd.run
      - seconds: 120
      - splay: 10
      - job_args:
        - 'composer update -o'
      - job_kwargs:
          cwd: '/project/source/development'
          shell: /bin/sh
          env: '{HOME:"/root"}'
      - return_job: true
```
