### ISSUE TITLE
Running detached processes on windows

### ISSUE THREAD

**Issue by Inveracity** [saltstack/salt#25605]
Applying a state to a windows minion that executes code with an infinite loop, makes the state.apply job hang.

The code I'm running is a simple web server written in python, I have tried forcing the python code to run itself again by detaching a child process with 
`subprocess.Popen(cmd, creationflags="0x00000008")`
 and then doing 
`os._exit(0)` 
on the parent process.

[The python code on Pastebin](http://pastebin.com/ZVBHpD2g)

This did not seem to trick the minion, as it seems the minion still has a hold on that new child process.

Furthermore, wrapping the execution in a .cmd only gave the same result.

_launch.cmd_
```
@ECHO OFF
start C:\salt\bin\python.exe C:\scripts\caustic_windows_v2.py restart
ECHO {"changed": "yes"}
exit
```
I also tried running the state with and without - shell: powershell, and with and without - stateful: True.
With the stateful set to True, I even printed {"changed":"yes"} in both the python code and afterwards in the .cmd script.

_init.sls_
```
C:/scripts/caustic_windows_v2.py:
  file.managed:
    - source: salt://caustic/caustic_windows_v2.py
    - name: C:/scripts/caustic_windows_v2.py

dothis:
  cmd.run:
    - name: c:/scripts/caustic_launch.cmd
```

My instincts are telling me that the minion on windows does not execute child processes in a detached state, and if that's the case, would it be possible to request this as a feature?

_example_
```
dothis:
  cmd.run:
    - name: c:/scripts/caustic_launch.cmd
    - Detached_process: True
```

____________________
_Salt-master_
```
SaltMaster:~ # salt-master --versions-report
           Salt: 2015.5.3
         Python: 2.6.9 (unknown, Apr  7 2015, 08:28:12)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
        Tornado: 4.1

```

_Salt-minion_
```
PS C:\salt> .\salt-minion.bat --versions-report
           Salt: 2015.5.3
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
```

Thanks for your time
