### ISSUE TITLE
a question salt.states.cmd.run for the group.

### ISSUE THREAD

**Issue by anbaoyong** [saltstack/salt#25606]
My English is not good.
my states file like this:
```yaml
touch /tmp/aby:
    cmd.run:
        - user: hadp
        - group: hadoop
```
execute and return :
```
-rw-r--r-- 1 hadp hadp 0 7月  22 17:35 /tmp/aby
```
how to change the group permissions for  hadoop?
thank you for your help!

**Comment by jfindlay** [comment]
You are running the command `touch /tmp/aby` as user `hadp` and group `hadoop`.  This is the user and group of the processes that executes that command, which is not necessarily going to be the user and group the file created by that command will belong to.  To ensure the user and group ownership you want, you may try:
```yaml
create aby file:
  file.managed:
    - name: /tmp/aby
    - user: hadp
    - group: hadoop
```
