### ISSUE TITLE
v2015.5.2 Salt Mine Returning inconsistent results

### ISSUE THREAD

**Issue by joshughes** [saltstack/salt#25613]
After upgrading from 2014.7.5 I am seeing many regressions in salt mine functionality that has put me in a position where I will probably have to figure out a way to downgrade. Here is the situation. 

```
root@inf-use1a-pr-01-salt-salt-0001:~# salt-call mine.get 'G@roles:mariadb and G@mariadb:cluster_name:dev_utopia' network.ip_addrs compound
local:
    ----------
    dev-use1a-pr-01-utopia-madb-0001:
        - 10.10.40.19
    dev-use1b-pr-01-utopia-madb-0001:
        - 10.10.50.250
    dev-use1e-pr-01-utopia-madb-0001:
        - 10.10.60.60
```

This is returning exactly what I expect... What is interesting is when I put a foobar value into the cluster name.

```
root@inf-use1a-pr-01-salt-salt-0001:~# salt-call mine.get 'G@roles:mariadb and G@mariadb:cluster_name:asdfadsfasdad' network.ip_addrs compound
local:
    ----------
    dev-use1b-pr-01-utopia-madb-0001:
        - 10.10.50.250
    dev-use1e-pr-01-utopia-madb-0001:
        - 10.10.60.60
```

And finally when I do a simple grain match... 

```
root@inf-use1a-pr-01-salt-salt-0001:~# salt-call mine.get 'roles:mariadb' network.ip_addrs  grain
local:
    ----------
    dev-use1a-pr-01-utopia-madb-0001:
        - 10.10.40.19
```

So in the first query I get 3 minions that I expect. 

In the second I should get 0 minions

In the last query I should get the 3 minions I got in the first

I have tried clearing the mine cache by doing the following... 

```
 rm /var/cache/salt/master/minions/*/mine.p && \
        salt '*' mine.update
```

```
salt-run cache.clear_mine tgt='*' && \
        salt '*' mine.update
```

It seems like there is some data somewhere that is corrupting my mine, or the functionality is just broken all together.

**Comment by joshughes** [comment]
After doing the following... 

```
rm -rf  /var/cache/salt/master/minions/*
/etc/init.d/salt-master restart
salt-run cache.clear_mine tgt='*'
salt '*' mine.update
```

Any compound query is returning all of my minions. It seems like the and functionality is completely broken.... 

```salt-call mine.get 'G@roles:mariadb and G@mariadb:cluster_name:adfasd_utopia' network.ip_addrs compound
```

The above query is now returning all of my minions

**Comment by jfindlay** [comment]
@joshughes, thanks for the report.

**Comment by joshughes** [comment]
As a side note as I downgraded to v2014.7.5 I see the same behavior... So it seems like my entire salt master might be hosed. 

Can anyone give me any ideas to try to fix this issue? We rely heavily on Salt Mine and our infrastructure can not be provisioned until we get this fixed.

**Comment by joshughes** [comment]
following the docs... it seems like I am now in a state where salt mine is not working at all 

```
mine.get '*' network.interfaces
local:
    ----------
```

So I manually deleted /var/cache/salt/master/minion/* and restarted my salt master... 

Now salt-mine will not return anything.

**Comment by aletourneau** [comment]
In case anyone drops on this page from google, here is a work around that worked for me (on salt 2015.5.2 (Lithium)):

    salt -t600 '*' saltutil.clear_cache; 
    salt -t600 '*' mine.update; 
    salt -t600 '*' saltutil.sync_all 

I run this after any grain updates, or after provisioning a new minion.

**Comment by joshughes** [comment]
One thing I have noticed on my infrastructure is that 

```
salt -t600 '*' mine.update; 
```

Does not update the grains correctly for me... I had to run. 

```
salt '*' cmd.run 'sudo salt-call mine.update' 
```

Then everything seemed to sync up.

**Comment by basepi** [comment]
Have you tried restarting all of your minions? I think there's a bug where the compound matcher will match a minion for a grains match in the absence of that minion's cached grains data. This could explain some of your behavior, because you deleted the cache, and the minions may have never refreshed their cached grains.

Anyway, sounds like there might be some other issues (such as @joshughes' latest comment) that we need to look into as well.

**Comment by joshughes** [comment]
So I did finally solve this by doing the following. 

1. Delete /var/cache/salt/master/minion 
2. service salt-master stop 
3. salt '*' cmd.run 'sudo salt-call mine.update' 

Got everything into a state where I could mine again. Although I was still seeing https://github.com/saltstack/salt/issues/21986 or something similar... except that my minions were not dead.  To resolve that I restarted the minions on those boxes and then followed the 3 steps above. 

Finally after that my salt-mine was returning sane results.

**Comment by deuscapturus** [comment]
Clearing cache and restarting the salt-minions cleared this up for me.  False positive matches from the mine can be very destructive for us.
> "I think there's a bug where the compound matcher will match a minion for a grains match in the absence of that minion's cached grains data"

@basepi is there an issue # I can follow for this?

**Comment by basepi** [comment]
Yep! https://github.com/saltstack/salt/issues/17203

**Comment by ssgward** [comment]
@jacobhammons - please document this for Beryllium.

**Comment by WaitF0r1t** [comment]
I've got the same problem. redis3 and redis4 in the following output are instances that were deleted before.

```
root@api1:~# salt-call mine.get '*redis*' network.ip_addrs
local:
   ----------
   redis1:
       - 10.2.26.65
   redis2:
       - 10.2.30.54
root@api1:~# salt-call mine.get 'roles:redis' network.ip_addrs grain
local:
   ----------
   redis1:
       - 10.2.26.65
   redis2:
       - 10.2.30.54
   redis3:
       - 10.2.25.85
   redis4:
       - 10.2.16.122
```
