### ISSUE TITLE
Add disableexcludes to states.pkg

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#25617]
Per issue #11415, this was added into yumpkg.  If doing any yum exclusion enforcement, states will fail when trying to install anything that was excluded.  It's preferable to add disableexcludes to the states.pkg vs. having no exclusions and then doing holds on most versions of packages on the system or doing something similar to this:

``` yaml
httpd:
  pkg.installed:
    - hold: True
    - version: {{ httpd_version }}
    - cmd.run:
      - name: yum install --disableexcludes=all httpd
```

IMO, disableexcludes should not be set unless specifically included.
