### ISSUE TITLE
grains documentation does not clearly indicate _grains is tied to salt environments roots

### ISSUE THREAD

**Issue by jaybocc2** [saltstack/salt#25646]
http://docs.saltstack.com/en/latest/topics/targeting/grains.html

Example:
```
../srv
└── salt
    ├── _grains
    └── prod
        └── _grains
```
master config:
```
# environment file roots
file_roots:
  base:
    - /srv/salt
  prod:
    - /srv/salt/prod
    - /srv/salt/prod/formula
    - /srv/salt/prod/state
```
If grains are placed /srv/salt/_grains they do not get pickedup, but if they are put in /srv/salt/prod/_grains they are picked up.

```
admin@saltshaker-001:~$ salt --version
salt 2015.5.2 (Lithium)
```
