### ISSUE TITLE
2015.5.2  MySQL Returner: salt-run jobs.lookup_jid doesn't return full result for highstate output

### ISSUE THREAD

**Issue by sdm24** [saltstack/salt#25664]
I set up a MariaDB database to use MySQL returner recently, and it is correctly storing the jobs cache, and "salt-run jobs.list_jobs" correctly lists the jobs in the database. If I run "salt-run jobs.list_job <jid>", it will return all of the job data, including the results for all targeted minions. "salt-run job.print_job <jid>" returns this as well. 

When I run "salt-run jobs.lookup_jid <jid>", I only get the last minion's return data:

``` yaml
minion3:
----------
          ID: test.ping
    Function: module.run
      Result: True
     Comment: Module function test.ping executed
     Started: 09:27:05.619453
    Duration: 0.669 ms
     Changes:
              ----------
              ret:
                  True
```

If I change the outputter to something besides the default highstate, I get the full list of all of my minions.
"salt-run jobs.lookup_jid <jid> --out=pprint":

``` python
{'winminion': {u'module_|-test.ping_|-test.ping_|-run': {u'__run_num__': 0,
                                                             u'changes': {u'ret': True},
                                                             u'comment': u'Module function test.ping executed',
                                                             u'duration': 0.0,
                                                             u'name': u'test.ping',
                                                             u'result': True,
                                                             u'start_time': u'09:23:55.147000'}},
 'minion1': {u'module_|-test.ping_|-test.ping_|-run': {u'__run_num__': 0,
                                                            u'changes': {u'ret': True},
                                                            u'comment': u'Module function test.ping executed',
                                                            u'duration': 6.434,
                                                            u'name': u'test.ping',
                                                            u'result': True,
                                                            u'start_time': u'09:24:45.105072'}},
 'mastermin': {u'module_|-test.ping_|-test.ping_|-run': {u'__run_num__': 0,
                                                              u'changes': {u'ret': True},
                                                              u'comment': u'Module function test.ping executed',
                                                              u'duration': 0.922,
                                                              u'name': u'test.ping',
                                                              u'result': True,
                                                              u'start_time': u'09:23:56.338629'}},
 'minion2': {u'module_|-test.ping_|-test.ping_|-run': {u'__run_num__': 0,
                                                              u'changes': {u'ret': True},
                                                              u'comment': u'Module function test.ping executed',
                                                              u'duration': 0.497,
                                                              u'name': u'test.ping',
                                                              u'result': True,
                                                              u'start_time': u'09:23:54.459396'}},
 'minion3': {u'module_|-test.ping_|-test.ping_|-run': {u'__run_num__': 0,
                                                             u'changes': {u'ret': True},
                                                             u'comment': u'Module function test.ping executed',
                                                             u'duration': 0.669,
                                                             u'name': u'test.ping',
                                                             u'result': True,
                                                             u'start_time': u'09:27:05.619453'}}}
```

The last minion to return with pprint is also the last minion to return with list_job and the only one returned with lookup_jid, which was the last alphabetical minion (I changed the names of my minions because they have some sensitive data). However, if I run a call with errors, the lookup_jid <jid> will only return the FIRST minion that errored. 

salt --versions-report:

``` yaml
                  Salt: 2015.5.2
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2015.5.2+ds-1~bpo70+1
```

I don't think this is an issue with using MariaDB instead of MySQL, since they use the exact same syntax, and the other salt commands work with it
