### ISSUE TITLE
salt-ssh missing custom grains

### ISSUE THREAD

**Issue by Cptn727** [saltstack/salt#25713]
Due to a firewall snafu, some of my minions lost connectivity to the salt-master today, but I could still ssh from the master to the minion. So I tried to use salt-ssh but discovered that custom grains were missing.

To illustrate the problem, I have reproduced it on a minion which is not having the connectivity issue, so I can show the comparison to the output from the regular salt command. Summarily, the issue is that default grains (id, fqdn_ip4, etc.) are present, but custom grains set in /etc/salt/grains are not.

For reference, these are the custom grains:

```
root@CT1-ETSYSADMINPROXY1:~#  salt-ssh -i CT1-ETCASSDEV1 cmd.run 'cat /etc/salt/grains'
CT1-ETCASSDEV1:
    dc: cn1
    dom: ef_com
    env: dev
    et_role:
    - cass
```

Here is what happens with salt-ssh:

```
root@CT1-ETSYSADMINPROXY1:~#  salt-ssh -i CT1-ETCASSDEV1 grains.get dom
[CRITICAL] Pillar render error: Rendering Primary Top file failed, render error:
Jinja variable 'dict object' has no attribute 'dc'
CT1-ETCASSDEV1:
root@CT1-ETSYSADMINPROXY1:~#  salt-ssh -i CT1-ETCASSDEV1 grains.get id
[CRITICAL] Pillar render error: Rendering Primary Top file failed, render error:
Jinja variable 'dict object' has no attribute 'dc'
CT1-ETCASSDEV1:
    CT1-ETCASSDEV1
```

and here is what happens with salt

```
root@CT1-ETSYSADMINPROXY1:~#  salt CT1-ETCASSDEV1 grains.get dom
CT1-ETCASSDEV1:
    ef_com
root@CT1-ETSYSADMINPROXY1:~#  salt CT1-ETCASSDEV1 grains.get id
CT1-ETCASSDEV1:
    CT1-ETCASSDEV1
```

Here is the versions report (identical for minion and master):

``` yaml
                  Salt: 2015.5.2
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.2+ds-1trusty1
```

Not sure if this matters at all, but the master is also a syndic.
