### ISSUE TITLE
Comment about missing requisite adding unnecessary newlines

### ISSUE THREAD

**Issue by ec73zmwq** [saltstack/salt#25735]
This is a small issue but I thought it looks like an error that should be documented.
Version: 2014.7.1 (Helium)
OS: CentOS 6

Note how in the first report of this missing requisite everything is laid out properly.

```
 Comment: The following requisites were not found:
                             require:
                                 file: ambari.properties
```

Then in the second mention of it, it starts to add what appears to be a newline; "\n" and the text isn't laid out properly.

```
 Comment: One or more requisite failed: {'abc.hadoop.abc-hadoop-ambari-server.ambari-setup-script': 'The following requisites were not found:\n                   require:\n                       file: ambari.properties\n'}
```

Then in the third mention of it, it adds a second slash in front of the newline; "\n".

```
 Comment: One or more requisite failed: {'abc.hadoop.abc-hadoop-ambari-server.run-ambari-setup': "One or more requisite failed: {'abc.hadoop.abc-hadoop-ambari-server.ambari-setup-script': 'The following requisites were not found:\\n                   require:\\n                       file: ambari.properties\\n'}"}
```
## Excerpt Below

```
      ID: ambari-setup-script
Function: file.managed
    Name: /usr/local/abc-automation/scripts/ambari-setup.sh
  Result: False
 Comment: The following requisites were not found:
                             require:
                                 file: ambari.properties
 Started:
Duration:
 Changes:
```

---

```
      ID: run-ambari-setup
Function: cmd.run
    Name: /usr/local/abc-automation/scripts/ambari-setup.sh
  Result: False
 Comment: One or more requisite failed: {'abc.hadoop.abc-hadoop-ambari-server.ambari-setup-script': 'The following requisites were not found:\n                   require:\n                       file: ambari.properties\n'}
 Started:
Duration:
 Changes:
```

---

```
      ID: start-ambari-server
Function: service.running
  Result: False
 Comment: One or more requisite failed: {'abc.hadoop.abc-hadoop-ambari-server.run-ambari-setup': "One or more requisite failed: {'abc.hadoop.abc-hadoop-ambari-server.ambari-setup-script': 'The following requisites were not found:\\n                   require:\\n                       file: ambari.properties\\n'}"}
 Started:
Duration:
 Changes:
```
