### ISSUE TITLE
glance.image_create no longer working with copy_from and is_public in 2015.8.0rc2

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#25814]
I was using this in an orchenstrate state. 

```
CentOS 6:
  salt.function:
    - name: glance.image_create
    - tgt: 'roles:glance'
    - tgt_type: grain
    - arg:
      - name=CentOS 6
      - is_public=true
      - disk_format=raw
      - container_format=bare
      - copy_from=http://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.raw


CentOS 7:
  salt.function:
    - name: glance.image_create
    - tgt: 'roles:glance'
    - tgt_type: grain
    - arg:
      - name=CentOS 7
      - is_public=true
      - disk_format=raw
      - container_format=bare
      - copy_from=http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.raw

Ubuntu 14.04:
  salt.function:
    - name: glance.image_create
    - tgt: 'roles:glance'
    - tgt_type: grain
    - arg:
      - name=Ubuntu 14.04
      - is_public=true
      - disk_format=raw
      - container_format=bare
      - copy_from=http://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img

FreeBSD 10.0:
  salt.function:
    - name: glance.image_create
    - tgt: 'roles:glance'
    - tgt_type: grain
    - arg:
      - name=FreeBSD 10.1 20150501
      - is_public=true
      - disk_format=qcow2
      - container_format=bare
      - copy_from=http://images.openstack.nctu.edu.tw/bsd-cloudinit/freebsd-10.1-fls-cloudimage-20150501.qcow2
```

which would tell my kilo openstack install to download and install all 4 of these images. 
this worked in 2015.5.3 however in the RC it is no longer working.

```
salt.wolfcloud.bad4.us_master:
----------
          ID: CentOS 6
    Function: salt.function
        Name: glance.image_create
      Result: True
     Comment: Function ran successfully. Function glance.image_create ran on ctrl.wolfcloud.bad4.us.
     Started: 21:41:57.079791
    Duration: 355.445 ms
     Changes:
              ctrl.wolfcloud.bad4.us:
                  ERROR executing 'glance.image_create': The following keyword arguments are not valid: is_public=True, copy_from=http://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.raw
----------
          ID: CentOS 7
    Function: salt.function
        Name: glance.image_create
      Result: True
     Comment: Function ran successfully. Function glance.image_create ran on ctrl.wolfcloud.bad4.us.
     Started: 21:41:57.435378
    Duration: 341.87 ms
     Changes:
              ctrl.wolfcloud.bad4.us:
                  ERROR executing 'glance.image_create': The following keyword arguments are not valid: is_public=True, copy_from=http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.raw
----------
          ID: Ubuntu 14.04
    Function: salt.function
        Name: glance.image_create
      Result: True
     Comment: Function ran successfully. Function glance.image_create ran on ctrl.wolfcloud.bad4.us.
     Started: 21:41:57.777469
    Duration: 346.498 ms
     Changes:
              ctrl.wolfcloud.bad4.us:
                  ERROR executing 'glance.image_create': The following keyword arguments are not valid: is_public=True, copy_from=http://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img
----------
          ID: FreeBSD 10.0
    Function: salt.function
        Name: glance.image_create
      Result: True
     Comment: Function ran successfully. Function glance.image_create ran on ctrl.wolfcloud.bad4.us.
     Started: 21:41:58.124109
    Duration: 343.397 ms
     Changes:
              ctrl.wolfcloud.bad4.us:
                  ERROR executing 'glance.image_create': The following keyword arguments are not valid: is_public=True, copy_from=http://images.openstack.nctu.edu.tw/bsd-cloudinit/freebsd-10.1-fls-cloudimage-20150501.qcow2
```
