### ISSUE TITLE
user shows 501 and group shows staff for archive.extracted

### ISSUE THREAD

**Issue by abhijo89** [saltstack/salt#25828]
I have a stat state which extractor the file to tmp folder. This is my code.

```
download_yii_framework:
  archive.extracted:
    - name: /tmp/
    - source: /home/test/test.tar
    - source_hash: md5={{ pillar['test_checksum'] }}
    - archive_format: tar
    - keep: False
    - if_missing: /tmp/test_tar/
    - user: root
    - group: root
```

After running this when i check the /tmp folder it shows 

```
drwxr-xr-x 5 501 staff 4096 Jun 30  test_tar
```

Why here user shows 501 and group shows staff ?

I am using salt 2015.5.0
