### ISSUE TITLE
Proxy minion never comes up with message ' I am XXX and I am not supposed to start any proxies.'

### ISSUE THREAD

**Issue by hishailesh77** [saltstack/salt#25908]
I have been trying to explore the proxy minion feature with REST and perform all the configuration for REST as per the instructions give at 'http://docs.saltstack.com/en/latest/topics/topology/proxyminion/index.html' .
But proxy minion never comes up when i start the actual minion, and i always get the message 
"I am XXX and I am not supposed to start any proxies"

And here is my sample pillar configuration for REST_SAMPLE
```yaml
root @ docker: / srv / pillar # cat top.sls
base:
  docker:
    - Proxyminion
```
```yaml
root @ docker: / srv / pillar # cat proxyminion.sls
proxy:
  rest_sample:
    proxytype: rest_sample    
    url: http://127.0.0.1:8080/
    id: proxy_docker
```
