### ISSUE TITLE
hg.latest state raise error 'JSON Render failed'

### ISSUE THREAD

**Issue by slav0nic** [saltstack/salt#25930]
```saltstack
$ salt-ssh --versions-report
                  Salt: 2015.5.3
                Python: 2.7.10 (default, Jul  1 2015, 10:54:53)
                Jinja2: 2.7.3
              M2Crypto: Not Installed
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: Not Installed
                  RAET: Not Installed
                   ZMQ: Not Installed
                  Mako: 1.0.0
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1
```
server hg version:  3.1.2

simple state:
```saltstack
coveragerepo:
    hg.latest:
      - name: ssh://hg@bitbucket.org/ned/coveragepy
      - target: /tmp/coverage
      - user: csgoserver
```
run via `salt-ssh`

```yaml
[ERROR   ] JSON Render failed for: pulling from ssh://hg@bitbucket.org/ned/coveragepy
searching for changes
no changes found
{
    "local": {
        "fun_args": [
            "/tmp/.slav0nic_659579__salt/salt_state.tgz", 
            "test=None", 
            "pkg_sum=9d9cea307ba9d7d0865b180054d49209", 
            "hash_type=md5"
        ], 
        "jid": "20150731204422920134", 
        "return": {
            "hg_|-coveragerepo_|-ssh://hg@bitbucket.org/ned/coveragepy_|-latest": {
                "comment": "", 
                "name": "ssh://hg@bitbucket.org/ned/coveragepy", 
                "start_time": "20:44:23.921949", 
                "result": true, 
                "duration": 4257.733, 
                "__run_num__": 0, 
                "changes": {}
            }
        }, 
        "retcode": 0, 
        "fun": "state.pkg", 
        "id": "gs1", 
        "out": "highstate"
    }
}

[ERROR   ] No JSON object could be decoded
```
