### ISSUE TITLE
Salt minion support for DNS re-evaluation upon reconnect, DNS RR, and DNS SRV

### ISSUE THREAD

**Issue by ayyags** [saltstack/salt#25953]
Currently,  specifying masters in minion config supports simple hostname / IP. 
Eg: 

<pre>
master: 
  - master1.example.com
  - master2.example.com
</pre>

Issue #1:  Salt minion cannot leverage DNS resolvers that gives out result based on client proximity (eg: F5).
The virtual host 'master.ny.example.com' could return list of back-end real-servers. 
Instead of requiring enumeration of each and every back-end real-server in minion config, salt minion should loop through all the back-end real-servers associated firstly with  'master.ny.example.com'. If it fails, it should then repeat for the next entry 'master.global.example.com'.
Eg: 

<pre>
master: 
  - master.ny.example.com
  - master.global.example.com
</pre>

Issue #2: The minion should support SRV records. In this case, srv zones are specified instead of hosts. The list of back-end real-servers will be sent to Salt minion with weight and priority. 
The minion shall then loop through the list in order of  priority and weight !!!. 

Eg:   (in this case, the list will be SRV zones) 
master:
-  ny.example.com
- global.example.com

ISSUE #3: Salt minion does not evaluate DNS record each time minion has to reconnect
It is normal practice to use DNS aliases to avoid dependence on hard-coded. 
The same thing is true for resolving DNS RR and DNS SRV records.  
The back-end real-servers can be changed in DNS instead of a need to update 1000's of minion configs. 
Salt minion must re-evaluate DNS call everytime it reconnects, and not just at startup time !!

Please let me know if the features to support robust DNS aliasing (all 3 above) will be supported and when ?

BTW, below is the version we are on. We might jump onto the latest stable release if it helps fixing this issue.

--- Salt version in use----

``` yaml
$ salt --versions-report
           Salt: 2015.5.0
         Python: 2.7.10 (default, Jun 19 2015, 04:18:28)
         Jinja2: 2.7.2
       M2Crypto: 0.22
 msgpack-python: 0.1.12
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

Thanks
subu.ayyagari@gmail.com
