### ISSUE TITLE
[2015.5.3-2] salt-winrepo.git/salt-minion.sls fails certificate '*.wpengine.com' or 'wpengine.com'

### ISSUE THREAD

**Issue by getabc** [saltstack/salt#25961]
Trying to upgrade my test minion with the following command,

```salt '*.ktm.*' pkg.install 'salt-minion' version=2015.8.0rc2```

and system reported

```MinionError: Error: The certificate was invalid. Error returned was: CertificateError("hostname 'docs.saltstack.com' doesn't match either of '*.wpengine.com', 'wpengine.com'",)```

changed ```salt-winrepo.git/salt-minion.sls``` links from https to http

```
salt-minion:
  2015.8.0rc2:
    installer: 'http://docs.saltstack.com/downloads/Salt-Minion-2015.8.0rc2-AMD64-Setup.exe'
    full_name: 'Salt Minion v2015.8.0rc2'
    reboot: False
    install_flags: '/S'
    uninstaller: 'C:\salt\uninst.exe'
    uninstall_flags: '/S'
    refresh: true
```
and works - any reason https is failing?
-AC
