### ISSUE TITLE
Question about salt-cloud pillar configuration

### ISSUE THREAD

**Issue by alex-solidfire** [saltstack/salt#25972]
I'm able to use the vmware cloud module with success when I configure my provider in /etc/salt/cloud.providers.d.

I would like to use the pillar configuration described here:
http://docs.saltstack.com/en/latest/topics/cloud/config.html

Even though I can see the provider config in my pillar.items output, I'm not able to list any providers when I try to configure through the pillar.

Any help here is appreciated, thank you.

**Comment by techhat** [comment]
Hi @alex-solidfire. What command are you using?

**Comment by alex-solidfire** [comment]
Hi @techhat , I'm using the following:
```
salt-cloud --list-providers
```

**Comment by alex-solidfire** [comment]
My pillar configuration looks like this:
```
cloud:
    providers:
        vmware-esxi-01:
            name: vmware-esxi-01
            provider: vmware
            user: "root"
            password: "secretpassword"
            url: "172.24.254.7"
```
