### ISSUE TITLE
Git-ignored top.sls for local development

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#26025]
I work with locally hosted virtual machines to test my states before using them in production. Currently I have a minion named `vagrant-test` which is a dumping ground for all the pillars/states I want to test. I've had reasonable success using environments, but too many issues have arisen for me to use this anymore.

My goal is to have a pillar + state top.sls that I can add to .gitignore for messing around with in a local environment. I *don't* want:

- to have to copy the "real" top.sls into a dev/local top.sls
- to have to change the VM minion name every time I want to test different states
- to have to specify all the states I want to test with `salt state.sls`
- to have to remember to not `git add` the top.sls when I'm changing what pillars/states the test VM should include
- cross-environment include/extend issues #14733

Are there any ways to achieve what I'm describing?

**Comment by anlutro** [comment]
My suggestion would be to allow the master configurations `state_top` and `pillar_top` to accept a list, so that I can provide two top.sls files: the real one and a gitignored local one, which are merged at runtime. Missing files should be silently ignored. For example:

```yaml
# master config
state_top:
- top.sls
- top.local.sls

pillar_top:
- top.sls
- top.local.sls

# /srv/pillar/top.sls
base:
  '*':
    - common
  'vagrant*'
    - vagrant.common

# /srv/pillar/top.local.sls
base:
  vagrant-test:
  - roles.webserver

# /srv/salt/top.sls
base:
  'os:Debian':
    - match: grain
    - debian
  '*':
    - common

# /srv/salt/top.local.sls
base:
  vagrant-test:
    - web.sites
```
