### ISSUE TITLE
windows user.add problem

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#26053]
```yaml
# salt jmoney-windows-12 test.versions
jmoney-windows-12:
    Salt Version:
               Salt: 2015.8.0rc3
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
           pycrypto: 2.6.1
            timelib: Not Installed
     
    System Versions:
               dist:   
            machine: AMD64
            release: 2012Server
             system: 2012Server 6.2.9200  Multiprocessor Free
```
```saltstack
# cat tests/windows/user_add.sls
add_dude:
  user.present:
    - name: saltdude
    - fullname: "Salt Dude"
```
The result appears to be successful, but there is some interesting info returned.
```yaml
# salt jmoney-windows-12 state.apply tests.windows.user_add
jmoney-windows-12:
----------
          ID: add_dude
    Function: user.present
        Name: saltdude
      Result: True
     Comment: New user saltdude created
     Started: 22:16:06.682000
    Duration: 31.0 ms
     Changes:
              ----------
              active:
                  True
              comment:
              description:
              fullname:
                  Salt Dude
              gid:
              groups:
              home:
                  ----------
                  comment:
                      [Error 2] The system cannot find the file specified
                  hive:
                      HKEY_LOCAL_MACHINE
                  key:
                      SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\S-1-5-21-33450644-2947241028-4020027136-1001
                  success:
                      False
                  vdata:
                      None
                  vname:
                      ProfileImagePath
              homedrive:
              logonscript:
              name:
                  saltdude
              passwd:
                  None
              profile:
                  ----------
                  comment:
                      [Error 2] The system cannot find the file specified
                  hive:
                      HKEY_LOCAL_MACHINE
                  key:
                      SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\S-1-5-21-33450644-2947241028-4020027136-1001
                  success:
                      False
                  vdata:
                      None
                  vname:
                      ProfileImagePath
              uid:
                  S-1-5-21-33450644-2947241028-4020027136-1001

Summary for jmoney-windows-12
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  31.000 ms
```
