### ISSUE TITLE
orchestrate not displaying a Summary when complete

### ISSUE THREAD

**Issue by vr-jack** [saltstack/salt#26077]
In 2014.7.5 orchestrate displayed a summary for each child job as well as the main orchestrate job. Output was almost identical in style to other salt modules. It no longer seems to in 2015.5.3.
```
Results in 2014.7.5:
Summary
-------------
Succeeded: 11 (changed=10)
Failed:     0
-------------
Total states run:     11
```
Summary still appears if you do `salt * state.highstate`, but a highstate directly but will not appear inside the results from orchestrate. This may partially be due to how orchestrate was changed to show a new style of id and reporting results out of order (using `__run_num__` to figure out their real order).
```yaml
 salt --versions-report
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
```
