### ISSUE TITLE
user.present adds None's in GECOS field

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#26076]
The user.present state seems to add literal None's in the GECOS field for the user.

This state:
```yaml
nginx-systemuser:
  user.present:
    - name: nginx
    - fullname: nginx worker
    - system: True
    - createhome: False
    - shell: /usr/sbin/nologin
```
results in `grep nginx /etc/passwd`:
```
nginx:x:998:998:nginx worker,None,None,None:/home/nginx:/usr/sbin/nologin
```
Using `user.add nginx` directly does not seem to make the issue appear, that results in a `nginx worker,,,`, which is fair enough.

Salt version `2015.8.0rc3`.

**Comment by anlutro** [comment]
Just checked /etc/passwd and the same has happened here, running the latest 2015.8 head.

**Comment by anlutro** [comment]
Seems to have been broken here: https://github.com/saltstack/salt/commit/e8792c735cc75b61d759bb8f08a05db341c834f0#diff-6

**Comment by anlutro** [comment]
Correction - everything worked fine at that point, the function `sdecode` didn't coerce the value into a string if it was not a string type. But then this change happened: https://github.com/saltstack/salt/commit/24343645c38d55118dab6b467f2fbdc9c8b60a1e#diff-3348c716754a77076fadc785c4a14569L49

**Comment by anlutro** [comment]
I've submitted a patch, but the only way to fix existing users seems to be to manually specify the GECOS fields as empty strings:

```yaml
myuser:
  user.present:
  - fullname: ""
  - roomnumber: ""
  - homephone: ""
  - workphone: ""
```
