### ISSUE TITLE
Saltstack Error when using eauth

### ISSUE THREAD

**Issue by lukayeh** [saltstack/salt#26091]
When running the below command:
```
 salt -a pam '*' test.ping
```

We get the below message:
```
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```

In /var/log/salt/master we get the following error message:
```
[WARNING ][1508] Authentication failure of type "eauth" occurred.
```

salt --versions-report gives:
```
Salt: 2015.5.0
Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
Jinja2: 2.8
M2Crypto: 0.20.2
msgpack-python: 0.4.6
msgpack-pure: Not Installed
pycrypto: 2.0.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.3.1
RAET: Not Installed
ZMQ: 3.2.5
Mako: Not Installed
```

Our Salt master contains:
```
external_auth:
  pam:
    amonitor:
         - .*
         - '@jobs'
    hbaxter:
         - .*
         - '@wheel'   # to allow access to all wheel modules
         - '@runner'  # to allow access to all runner modules
         - '@jobs'    # to allow access to the jobs runner and/or wheel module
```

We also tried this with tried 2015.5.2 and 2015.5.3

The issue initially occured when trying to log into saltpad (who pointed us in this direction)

Hope you can help.

Thanks,

Luka
