### ISSUE TITLE
documentation around scheduling and orchestration is unclear

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#26108]
Referencing http://docs.saltstack.com/en/latest/topics/jobs/schedule.html#runners

I don't see how to specify _which_ orchestration is being run. For example, I want to run my_orch, do I have to name the schedule my_orch (much like the state system defaults to using state names as targets for the applied state) or do I need to pass my_orch as an arg.

**Comment by ahammond** [comment]
the job name is not relevant, so this example is actually not a working example. It should instead read something like this:

```yaml
schedule:
  run_my_orch:
    function: state.orchestrate
    hours: 6
    splay: 600
    args:
      - orchestration.my_orch
```
