### ISSUE TITLE
Issue targeting nodegroups - Invalid compound target: ( L@ ... )

### ISSUE THREAD

**Issue by thecosmicfrog** [saltstack/salt#26107]
Seeing a strange bug when targeting nodegroups. Some of my minion return fine, whereas others give me either "Minion did not return. [No response]" or "Minion did not return. [Not connected]".

As below:
```yaml
=== /etc/salt/master ===
nodegroups:
   non-critical: 'L@ansible-master,server1,server2,server3,server4,server5,salt-master,server6,server7,server8'
```
```console
=== Targeting from command line ===
root@salt-master:~# salt -N 'non-critical' test.version
server5:
    2015.5.3
salt-master:
    2015.5.3
server4:
    2015.5.2
server1:
    2015.5.3
server7:
    2015.5.2
server2:
    Minion did not return. [No response]
server3:
    Minion did not return. [No response]
ansible-master:
    Minion did not return. [No response]
server6:
    Minion did not return. [Not connected]
server8:
    Minion did not return. [No response]
```
```
=== Minion log from failing server (server2) ===
=== /var/log/salt/minion ===
2015-08-07 13:53:08,938 [salt.minion      ][ERROR   ] Invalid compound target: ( L@ansible-master,server1,server2,server3,server4,server5,salt-master,server6,server7,server8 )
```

Why would this be an "invalid compound target"?

Running `salt '*' <whatever>` works as expected. It's just nodegroups that have the issue.
