### ISSUE TITLE
salt.module.network is mostly broke-ish on SmartOS and possibily SunOS

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#26139]
Lots of things don't work or partially work, traceroute for example errors and arp returns weird data.
```
[root@core ~]# salt-call --local network.traceroute blackdot.be
[INFO    ] Executing command 'traceroute blackdot.be' in directory '/root'
[INFO    ] Executing command 'traceroute --version' in directory '/root'
[ERROR   ] Command 'traceroute --version' failed with return code: 1
[ERROR   ] output: Usage: traceroute [-adFIlnSvx] [-A address_family] [-c traffic_class]
        [-f first_hop] [-g gateway [-g gateway ...]| -r] [-i iface]
        [-L flow_label] [-m max_hop] [-P pause_sec] [-p port] [-Q max_timeout]
        [-q nqueries] [-s src_addr] [-t tos] [-w wait_time] host [packetlen]
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 224, in salt_call
  File "salt/cli/call.py", line 50, in run
  File "salt/cli/caller.py", line 133, in run
  File "salt/cli/caller.py", line 196, in call
  File "salt/modules/network.py", line 563, in traceroute
IndexError: list index out of range
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 224, in salt_call
  File "salt/cli/call.py", line 50, in run
  File "salt/cli/caller.py", line 133, in run
  File "salt/cli/caller.py", line 196, in call
  File "salt/modules/network.py", line 563, in traceroute
IndexError: list index out of range
```

**Comment by jfindlay** [comment]
@sjorge, thanks for the report.  Will you also report the salt version as well for a reference point?  Thanks.

**Comment by sjorge** [comment]
Only tested on 2015.8, since that is what I got working :)

**Comment by sjorge** [comment]
This extends partially to grains as well on SmartOS and probably SunOS in general, ip6 grains are all incorrect.

some info redacted
```
[root@core ~]# salt-call --local grains.items
local:
    ----------
    cpu_flags:
        - rdrand
        - f16c
        - vmx
        - avx
        - xsave
        - pclmulqdq
        - aes
        - sse4.2
        - sse4.1
        - ssse3
        - popcnt
        - tscp
        - cx16
        - sse3
        - sse2
        - sse
        - fxsr
        - mmx
        - cmov
        - amd_sysc
        - cx8
        - tsc
        - fpu
    cpu_model:
        Intel(r) Xeon(r) CPU E5-2620 v2 @ 2.10GHz
    cpuarch:
        i386
    domain:
        acheron.be
    fqdn:
        core.acheron.be
    fqdn_ip4:
        - 172.16.xx.yy
    fqdn_ip6:
    gpus:
    host:
        core
    hwaddr_interfaces:
        ----------
        igb0:
            a0:36:9f:xx:xx:xx
    id:
        core.example.org
    ip4_interfaces:
        ----------
        igb0:
            - 172.16.xx.yy
        lo0:
            - 127.0.0.1
    ip6_interfaces:
        ----------
        igb0:
            - fe80::a236:9fff:fexx:xx6a
        lo0:
            - ::1
    ip_interfaces:
        ----------
        igb0:
            - 172.16.xx.yy
            - fe80::a236:9fff:fexx:xx6a
        lo0:
            - 127.0.0.1
            - ::1
    ipv4:
        - 127.0.0.1
        - 172.16.xx.yy
    ipv6:
        - ::1
        - fe80::a236:9fff:fexx:xx6a
    kernel:
        SunOS
    kernelrelease:
        5.11
    locale_info:
        ----------
        defaultencoding:
            UTF-8
        defaultlanguage:
            en_US
        detectedencoding:
            UTF-8
    localhost:
        core
    master:
        salt
    mem_total:
        131037
    nodename:
        core
    num_cpus:
        24
    num_gpus:
        0
    os:
        SmartOS
    os_family:
        Solaris
    osarch:
        amd64
    osfullname:
        SmartOS
    osrelease:
        20150806T063417Z
    osrelease_info:
        - 20150806T063417Z
    path:
        /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit:/usr/bin:/usr/sbin:/smartdc/bin:/opt/smartdc/bin:/opt/local/bin:/opt/local/sbin:/opt/smartdc/agents/bin:/opt/local/salt/bin
    ps:
        /usr/ucb/ps auxwww
    pythonexecutable:
        /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/salt-call
    pythonpath:
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/library.zip
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/libnacl-1.4.3-py2.7.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/enum34-1.0.4-py2.7.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/yappi-0.94-py2.7-solaris-2.11-i86pc.64bit.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/certifi-2015.4.28-py2.7.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/six-1.9.0-py2.7.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/GitPython-0.3.2c1-py2.7.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/ioflo-1.3.8-py2.7.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/raet-0.6.3-py2.7.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/salt-2015.8.0rc3_18_g4dce1b4-py2.7.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/timelib-0.2.4-py2.7-solaris-2.11-i86pc.64bit.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/gitdb-0.6.4-py2.7-solaris-2.11-i86pc.64bit.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/tornado-4.2.1-py2.7-solaris-2.11-i86pc.64bit.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/smmap-0.9.0-py2.7.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/pyzmq-13.1.0-py2.7-solaris-2.11-i86pc.64bit.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/backports.ssl_match_hostname-3.4.0.2-py2.7.egg
        - /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/esky-0.9.8-py2.7.egg
    pythonversion:
        - 2
        - 7
        - 9
        - final
        - 0
    saltpath:
        /opt/local/salt/bin/appdata/salt-2015.8.0rc3-18-g4dce1b4.solaris-2_11-i86pc_64bit/salt-2015.8.0rc3_18_g4dce1b4-py2.7.egg/salt
    saltversion:
        2015.8.0rc3-18-g4dce1b4
    saltversioninfo:
        - 2015
        - 8
        - 0
        - 0
    server_id:
        488737913
    shell:
        /usr/bin/bash
    virtual:
        physical
    zmqversion:
        4.0.5
```

The following grains are incorrect/complete:
 - fqdn_ip6
 - ip6_interfaces ( ip_interfaces )
 - ipv6

Bellow you find the ifconfig output:
```
[root@core ~]# ifconfig
lo0: flags=2001000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv4,VIRTUAL> mtu 8232 index 1
        inet 127.0.0.1 netmask ff000000
igb0: flags=1000843<UP,BROADCAST,RUNNING,MULTICAST,IPv4> mtu 1500 index 2
        inet 172.16.xx.yy netmask ffffff00 broadcast 172.16.xx.255
        ether a0:36:9f:6e:xx:xx
lo0: flags=2002000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv6,VIRTUAL> mtu 8252 index 1
        inet6 ::1/128
igb0: flags=20002000841<UP,RUNNING,MULTICAST,IPv6> mtu 1500 index 2
        inet6 fe80::a236:9fff:fexx:xx6a/10
        ether a0:36:9f:6e:xx:xx
igb0:1: flags=20002000841<UP,RUNNING,MULTICAST,IPv6> mtu 1500 index 2
        inet6 2001:6f8:1480:xx::120/64
igb0:2: flags=200020a0841<UP,RUNNING,MULTICAST,NOLOCAL,ADDRCONF,IPv6> mtu 1500 index 2
        inet6 subnet 2001:6f8:1480:xx::/64
```

As you can see igb0 has a slaac and a static ipv6 address!

I'm currently updating salt.grains.core to fix a number of issues but this is sadly currently out of my skill set.
