### ISSUE TITLE
Changes under file.recurse id with watch_in not shown in test mode

### ISSUE THREAD

**Issue by non7top** [saltstack/salt#26150]
If something changes in directory managed by file.recurse this is not reflected in watch_in dependencies during test run(i.e. nginx.service should mention that it is scheduled for restart). However, during actual run this works as expected and the service actually gets restarted.

``` yaml
# salt 'example.com' state.sls webserver.test test=True
----------
          ID: nginx
    Function: pkg.installed
      Result: True
     Comment: Package nginx is already installed.
     Started: 02:33:06.851546
    Duration: 458.561 ms
     Changes:
----------
          ID: /etc/nginx/conf.d/
    Function: file.recurse
      Result: None
     Comment: #### removed ####
              /etc/nginx/conf.d/default.conf
              /etc/nginx/conf.d/example_ssl.conf
              /etc/nginx/conf.d/push.conf
     Started: 02:33:07.312692
    Duration: 28.365 ms
     Changes:
----------
          ID: nginx
    Function: service.running
      Result: True
     Comment: Service nginx is already enabled, and is in the desired state
     Started: 02:33:07.341341
    Duration: 49.532 ms
     Changes:

Summary
------------
Succeeded: 3 (unchanged=1)
Failed:    0
------------
Total states run:     3
```

sls file

``` saltstack
nginx:
  pkg:
    - installed
  service:
    - running
    - enable: True
    - require:
      - pkg: nginx


/etc/nginx/conf.d/:
  file.recurse:
    - clean: True
    - source: salt://webserver/files/nginx/conf.d/
    - require:
      - pkg: nginx
    - watch_in:
      - service: nginx
```
