### ISSUE TITLE
Require pkg isn't ordering states properly in 2015.5.3

### ISSUE THREAD

**Issue by ryanwalder** [saltstack/salt#26241]
After updating to 2015.5.3 a lot of our requisites have stopped working as expected which breaks salt in a spectacular way when using git because git doesn't exist yet:

```
deployment-key: 
  file.managed:
    - name: /etc/ssh/deployment-key
    - contents_pillar: deployment-key
    - user: root
    - group: root
    - mode: 600

get-repo:
  git.latest:
    - name: git@git.blah.com:reponame
    - target: /opt/repo
    - identity: /etc/ssh/deployment-key
    - force_checkout: True
    - user: root
    - require:
      - file: deployment-key
      - pkg: install-git

install-git:
  pkg.latest:
      - name: git-core
```

This doesn't re-order the states to make `install-git` come before `get-repo` as you would expect.

```
vagrant@ilikecheese:~$ salt-minion --versions
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: 4.2.1
 Debian source package: 2015.5.3+ds-1trusty1
```
