### ISSUE TITLE
docker.running state fails with Container_id could not be resolved to an existing container

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#26289]
I'm trying to start a container that doesn't exist. It fails to start my container. I believe it's because the container doesn't exist, and so `modules/dockerio._get_container_infos` is raising the exception. The `start` function in the same module is doing this:

```
    try:                                                                           
        dcontainer = _get_container_infos(container)['Id']                         
        if not is_running(container):                                              
            bindings = None          
```

I'm not sure if `_get_container_infos` is suppose to return info even if there is no container, or if start should be capturing the exception and starting the container... or something else.

But as far as I can tell, this won't ever work (though it might be due to a change in the docker-py API?)

Job output:

```
          ID: waynetest
    Function: docker.running
      Result: False
     Comment: Container 'waynetest' cannot be started
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 885, in start
                  dcontainer = _get_container_infos(container)['Id']
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 350, in _get_container_infos
                  container)
              CommandExecutionError: Container_id waynetest could not be resolved to an existing container
     Started: 10:57:46.228763
    Duration: 4373.215 ms
     Changes:  
```

Master:

```
           Salt: 2015.5.3
         Python: 2.7.10 (default, May 26 2015, 04:16:29)
         Jinja2: 2.8
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.2
           Mako: 1.0.1
        Tornado: 4.2.1
```

Minion (with `docker-py==1.3.1`):

```
                      Salt: 2015.5.0
                    Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                    Jinja2: 2.6
                  M2Crypto: 0.21.1
            msgpack-python: 0.1.10
              msgpack-pure: Not Installed
                  pycrypto: 2.4.1
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: 14.0.1
                      RAET: Not Installed
                       ZMQ: 4.0.4
                      Mako: Not Installed
     Debian source package: 2015.5.0+ds-1precise1
```

**Comment by cachedout** [comment]
Hi @waynew. In the current 2015.8 release candidate series, the old `dockerio` module has been superceded by `dockerng`. We'd love to have you give it a try and see if it resolves this issue for you.

**Comment by waynew** [comment]
@cachedout Getting a different problem now:

```
          ID: waynetest
    Function: docker.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/dockerio.py", line 1237, in running
                  out = create(image_name, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 694, in create_container
                  raise e
              InvalidVersion: mem_limit has been moved to host_config in API version 1.19
     Started: 15:52:36.144649
    Duration: 106.935 ms
     Changes: 
```

Here are my versions on the minion:

```
    Salt Version:
               Salt: 2015.8.0rc3-1192-g909556a
     
    Dependency Versions:
             Jinja2: 2.6
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.1
             Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
           pycrypto: 2.6.1
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 12.04 precise
            machine: x86_64
            release: 3.2.0-87-generic
             system: Ubuntu 12.04 precise
```

And master:
```
Salt Version:
           Salt: 2015.8.0-260-g909556a
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, May 26 2015, 04:16:29)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.0.6-1-ARCH
```

**Comment by waynew** [comment]
Got it - had to downgrade docker-py to `1.2.3`

**Comment by waynew** [comment]
Oh wait, I spoke too soon. Apparently while it *did* start my container, but it didn't properly map the ports:

```
waynetest:                                                                                                                                                                                          
    docker.running:                                                                                                                                                                                 
        - container: waynetest                                                                                                                                                                      
        - image: "waynew/py34"                                                                                                                                                                      
        - port_bindings:                                                                                                                                                                            
            - "8000/tcp":                                                                                                                                                                           
                HostIp: ""                                                                                                                                                                          
                HostPort: "5454"                                                                                                                                                                    
        - volumes:                                                                                                                                                                                  
            - /var/www/test:                                                                                                                                                                        
                bind: /www                                                                                                                                                                          
                ro: True                                                                                                                                                                            
        - command: -m www.server  
```

/var/www/test on the server simply contains a blank `__init__.py`, an html file with some stuff in it, and the following `server.py`:

```
import os                                                                                                                                                                                           
import http.server as s                                                                                                                                                                             
                                                                                                                                                                                                    
os.chdir(os.path.dirname(__file__))                                                                                                                                                                 
h = s.HTTPServer(('', 8000), s.SimpleHTTPRequestHandler)                                                                                                                                            
h.serve_forever() 
```

Interestingly enough, I downgraded back to `2015.5` on both master & minion but kept the older docker-py.


So I think *this* issue is resolved - the docker module **requires** `docker-py==1.2.3` (or at least nothing later). That might be something worthwhile to put in the documentation!
