### ISSUE TITLE
Ability to map a shared gitfs_remote branch with multiple environments...

### ISSUE THREAD

**Issue by PredatorVI** [saltstack/salt#26309]
When using file_roots, if I have "shared' states to be included in multiple environments, I can repeat that file root:

```
file_roots:
  base:
    - /srv/salt/base
  dev:
    - /srv/salt/dev
    - /srv/salt/base
...
```

It would be nice to be able to do the same for gitfs_remotes, particularly for things like salt-formulas where they are a shared resource.  An example syntax could be:

```
gitfs_remotes:
  - ssh://git@github.com/me/mystaterepo.git:
    - branch_environment_map:
      - master:  #branch to map
        - base    #List of environments
        - dev
      - production:
        - prd
```
