### ISSUE TITLE
mount.mounted opts incorrect "forced unmount and mount because options (tcp) changed"

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#26327]
This is to track the specific issue with mount.mounted with the 'tcp' opts - reference #18630

If I leave tcp out of opts the problem goes away. Apparently RHEL offers a tcp/udp option. [tcp is the default](http://web.mit.edu/rhel-doc/5/RHEL-5-manual/Deployment_Guide-en-US/s1-nfs-tcp.html) 

```
          ID: mount_mnt_data
    Function: mount.mounted
        Name: /mnt/data
      Result: True
     Comment: Target was already mounted. Updated the entry in the fstab.
     Started: 12:30:09.129106
    Duration: 49.423 ms
     Changes:
              ----------
              persist:
                  update
              umount:
                  Forced unmount and mount because options (tcp) changed
```

```
# salt-minion --versions
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.8
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 0.3.4
        Tornado: Not Installed
```

```
mount_mnt_data:
  mount.mounted:
    - name: /mnt/data
    - device: {{ salt['pillar.get']('mount_device:data') }}/{{ salt['grains.get']('environment') }}
    - fstype: nfs
    - mkmnt: True
    - persist: True
    - opts: {{ salt['pillar.get']('mount_opts', 'vers=3,noatime,rsize=32768,tcp,wsize=32768,hard,intr,timeo=600') }}
```

```
# mount
...
s-corp-nasfs-01:/root_vdm_4/jbapd1_fs/dev-int1 on /mnt/data type nfs (rw,noatime,vers=3,rsize=32768,tcp,wsize=32768,hard,intr,timeo=600,addr=172.21.23.164)
...
```
