### ISSUE TITLE
windows cmd.run state function broken

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#26337]
### configs
```saltstack
# cat > salt-manual-tests/tests/windows/cmd.sls
cmd run:
  module.run:
    - name: cmd.run
    - cmd: type c:\salt\conf\minion > nul
```

### commands

Running the command with the `cmd.run` exec function works:
```console
# salt jmoney-windows-12 cmd.run 'type c:\salt\conf\minion > nul'
jmoney-windows-12:
```
but running it with the `cmd.run` state function fails:
```console
# salt jmoney-windows-12 state.sls tests.windows.cmd
jmoney-windows-12:
----------
          ID: cmd run
    Function: module.run
        Name: cmd.run
      Result: False
     Comment: Module function cmd.run threw an exception. Exception: Unable to run command ['type', 'c:\\salt\\conf\\minion', '>', 'nul'] with the context {'with_communicate': True, 'shell': False, 'env': {'TMP': 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2', 'COMPUTERNAME': 'JMONEY-WINDOWS-', 'USERDOMAIN': 'JMONEY-WINDOWS-', 'PYTHON': 'C:\\salt\\bin\\python.exe', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '0200', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'TEMP': 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2', 'SCRIPT': 'C:\\salt\\bin\\Scripts\\salt-minion', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'SALTDIR': 'C:\\salt', 'LOCALAPPDATA': 'C:\\Users\\Administrator\\AppData\\Local', 'HOMEPATH': '\\Users\\Administrator', 'USERDOMAIN_ROAMINGPROFILE': 'JMONEY-WINDOWS-', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'Administrator', 'LOGONSERVER': '\\\\JMONEY-WINDOWS-', 'PROMPT': '$P$G', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'PROGRAMDATA': 'C:\\ProgramData', 'SESSIONNAME': 'RDP-Tcp#0', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'CLIENTNAME': 'poseidon', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 'HOMEDRIVE': 'C:', 'APPDATA': 'C:\\Users\\Administrator\\AppData\\Roaming', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESSORS': '2', 'PROCESSOR_LEVEL': '21', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\Users\\Administrator'}, 'stdout': -1, 'stdin': None, 'stderr': -2, 'cwd': 'C:\\Users\\Administrator'}, reason: [Error 2] The system cannot find the file specified
     Started: 19:37:04.426000
    Duration: 15.0 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

### versions
```yaml
# salt jmoney-windows-12 test.versions_report
jmoney-windows-12:
               Salt: 2015.5.3-235-g1e3f33a
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.5
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.6.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
            Tornado: Not Installed
            timelib: Not Installed
```

**Comment by twangboy** [comment]
@jfindlay This seems to be a problem with the module.run state, not cmd.run. When I run your state it fails. If I run the following state, it works as expected:
```
cmd_run_test:
  cmd.run:
    - name: type c:\salt\conf\minion > nul
```

**Comment by jfindlay** [comment]
@twangboy, I can change the issue if you want.

**Comment by twangboy** [comment]
@jfindlay I ran your state but changed it from cmd.run to cmd.shell and it worked.

**Comment by twangboy** [comment]
@jfindlay So, that command needs `python_shell=True` to execute properly.

**Comment by twangboy** [comment]
So, running your state again, adding `python_shell=True` ran correctly

**Comment by twangboy** [comment]
I think the preferred method is to use cmd.shell, but understand there are security risks

**Comment by twangboy** [comment]
To fix this problem you need to either add `python_shell=True` to your state like so:
```
cmd_run_test:
  module.run:
    - name: cmd.run
    - cmd: 'dir c:\salt\conf\minion'
    - python_shell: True
```
or use the cmd.run state module:
```
cmd_run_test:
  cmd.run:
    - name: type c:\salt\conf\minion > nul
```
