### ISSUE TITLE
Homebrew provider fails with slash namespaced packages

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt#26407]
If I use `pkg.installed` with a homebrew package manager, it will report a failure on any package named with slashes like `user/cask/mypkg`. The package gets installed correctly, but when salt checks its work using `brew list --versions` it will only see the version of `mypkg` not the fully delimited package.

Code triggering an issue:

``` yaml
caskroom:
  pkg.installed:
    - name: "caskroom/cask/brew-cask"
```

I found a workaround since `brew install brew-cask` also seems to work in this case... but in the case of custom casks, this won't cut it. Please let me know if you need more info or help reproducing the issue.
