### ISSUE TITLE
Lost the ability to target minions by grains

### ISSUE THREAD

**Issue by thenational22** [saltstack/salt#26440]
SO we updated to 2015.1.3, and now all grain matching seems to never fire.

Trying `salt 'G@os:Ubuntu' test.ping`

returns:
```
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```
Same result with `salt -G 'os:Ubuntu'`

And when I do salt 'hostname.company.net' test.ping, works just fine, and grains.items returns all of the items. 

It seems to have just lost the abilty to targey by grain. It appears to not even attempting to try and find them. No wierd firewall rules, and all other traffic seems to be working.

```yaml
root@saltmaster02:/home/admin# salt --versions
           Salt: 2015.5.4
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.8
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: Not Installed
        timelib: Not Installed
```
