### ISSUE TITLE
file.copy: source file is not present.

### ISSUE THREAD

**Issue by typeshige** [saltstack/salt#26450]
According to http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.copy, 

```
If the source file exists on the system, copy it to the named file. 
```

I'm trying to copy a file if the source exists and just do nothing if it doesn't exist.

Why am I getting an error?

Thanks you.

**Comment by terminalmage** [comment]
We'll need some more information to properly assist you. What version of salt are you running? Can you show us an example of the SLS for the state you are trying to run?

Also, you mentioned an error, but did not give any details about the error. Without knowing more about the error, it'll be hard to proceed with troubleshooting.

**Comment by ckoe-bccms** [comment]
Hello,

I think the original reporter was trying to copy a file from the master to the minion with "file.copy". Then you get this error !

The wording in the documentation is extremely poor and misleading. 

"If the source file exists on the system, copy it to the named file. "
using the word "system" (which system, master or minion ? ) instead "minion".

Much better wording would IMO be
"If the source file already exists on the minion, copy it to another location specified by name: on the minion. "

Best Regards

Christof

**Comment by fredrikaverpil** [comment]
Not sure if I'm hitting the exact same use case, as the OP didn't provide much background. But here's my case (with the same error).

This works perfectly fine:

```
copy_script_onto_minion:
  module.run:
    - name: cp.get_file
    - path: salt://windows/installers/AddAccountToLogonAsService.ps1
    - dest: C:\AddAccountToLogonAsService.ps1
```

But this will fail: 

```
copy_script_onto_minion:
   file.copy:
     - source: salt://windows/installers/AddAccountToLogonAsService.ps1
     - name: C:\AddAccountToLogonAsService.ps1
```

...with the following info:

```
          ID: copy_script_onto_minion
    Function: file.copy
        Name: C:\AddAccountToLogonAsService.ps1
      Result: False
     Comment: Source file "salt://windows/installers/AddAccountToLogonAsService.ps1" is not present
     Started: 08:13:23.242000
    Duration: 0.0 ms
     Changes:
```

I'm on 2015.8.5, running on CentOS 7. The minion is a Windows 10 Pro 64-bit box.
