### ISSUE TITLE
Getting [ERROR   ] Missing python-dateutil.Ignoring job 

### ISSUE THREAD

**Issue by davidcop** [saltstack/salt#26462]
```yaml
Using c:\salt\salt-call --versions  on Windows
           Salt: 2015.5.3
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
```
Pillar file includes..
```saltstack
schedule:
  backup:
    function: cmd.run
    args:
      - 'powershell add-backup'
    when: 2:00pm
```

Using C:\salt\salt-minion-debug.bat shows
```
[ERROR   ] Missing python-dateutil.Ignoring job backup
```
Looks like same as described in
https://github.com/saltstack/salt/issues/19755
