### ISSUE TITLE
'salt-run state.orch ...' failure is not indicated in exit status 

### ISSUE THREAD

**Issue by PredatorVI** [saltstack/salt#26499]
Looking to use orchestrations for complex deployments.  My initial implementation installs a 3 node RabbitMQ cluster.

I've included a section that will ping the minions to make sure they are up before running the orchestrations:

#From: /srv/salt/orchestration/myapp.sls
```
ping_minions:
  salt.function:
    - name: test.ping
    - tgt: 'E@{{ pillar.regex_primary }} and E@{{ pillar.regex_secondary }}'
    - tgt_type: compound
```
If I stop the salt-minion service (test.ping should fail) and run:

```
    salt-run state.orchestrate orchestration.myapp pillar='{"regex_primary": "myapp-acc01*", "regex_secondary": "myapp-acc0[2-3]*"}'
```

the exit status is '0' (no error indicated).  If I include the --hard-crash also still returns '0'.  

If the executable doesn't set a non-zero exit code to signal an error occurred, I'd have to manually parse all output each time in an attempt to determine if a failure occurred and stop the process (continuous deployment).  I could be missing something.
