### ISSUE TITLE
pip.installed state not found

### ISSUE THREAD

**Issue by nitay** [saltstack/salt#26493]
salt master:
```
root@salt:/srv# salt-call --versions
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

minion:
```
root@m1:~# salt-call --versions
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: 4.2.1
 Debian source package: 2015.5.3+ds-1trusty1
```

State file (snipped to minimal):
```
util-pkgs:
  pkg.installed:
    - names:
      - python-pip

pip-utils:
  pip.installed:
    - names:
      - awscli
    - require:
      - pkg: python-pip
```

For some reason salt is not able to use pip anymore..

```
KeyError: 'pip.installed'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 523, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2968, in call_highstate
    return self.state.call_high(high)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2067, in call_high
    ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1623, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1769, in call_chunk
    self._mod_init(low)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 612, in _mod_init
    self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
    raise KeyError(key)
KeyError: 'pip.installed'
```

Even though pip seems to be installed:

```
root@m1:~# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip
>>> import pip.req
>>>
```

What's going on here? This is a MAJOR blocker for me b/c it's breaking a bunch of states and making salt unusable.

**Comment by ssgward** [comment]
@nitay - Interesting. I just ran a couple of pip.installed states using v2015.5.4 tag and didn't have any problems. Wonder if something happened after 2015.5.3 to fix the problem you are seeing...?

Here's one of my states:
```
include: 
  - pip

psycopg2:
  pip.installed:
    - name: psycopg2 == 2.6
    - require:
      - sls: pip
```
What does ``pip --version`` show you?

**Comment by nitay** [comment]
master:
```
root@salt:/srv# pip --version
pip 7.1.0 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

minion:
```
root@m1:~# pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Comment by nitay** [comment]
@ssgward do you think it's an issue with the version? I have other minions with that version that *do* work. I can't tell what makes them different...?

**Comment by ssgward** [comment]
@nitay - it maybe the version. It may have been fixed between the versions.

**Comment by nitay** [comment]
@ssgward how does that explain it working on some minions and not on others? All my machines have the same salt version.

**Comment by ssgward** [comment]
@nitay - oh, sorry, didn't read well enough to understand all minions are on the same version. I thought a few were on a newer version.

That is confusing as to why some minions would work and others not. Don't have an immediate answer for that.

**Comment by nitay** [comment]
@ssgward how do I investigate this? I'm at a loss for what to do.

**Comment by ssgward** [comment]
@nitay - I'll add labels to this issue so it will then get picked up by a dev, either internal to salt stack or a contributor in the near future.

Reaching out in forums may shed some light on this for you. Others may have seen the same thing as you are seeing.

**Comment by waynew** [comment]
I'm getting the same result on this minion:
```
                      Salt: 2015.5.3
                    Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                    Jinja2: 2.7.2
                  M2Crypto: 0.21.1
            msgpack-python: 0.3.0
              msgpack-pure: Not Installed
                  pycrypto: 2.6.1
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: 14.0.1
                      RAET: Not Installed
                       ZMQ: 4.0.4
                      Mako: 0.9.1
                   Tornado: Not Installed
     Debian source package: 2015.5.3+ds-1trusty1
```

I'm trying to do this state:
```
docker-py:                                                                                                                                                                                          
    pkg.installed:                                                                                                                                                                                  
        - name: python-pip                                                                                                                                                                          
    pip.installed:                                                                                                                                                                                  
        - name: docker-py                                                                                                                                                                           
        - require:                                                                                                                                                                                  
            - pkg: python-pip   
```

Interesting to note - I *can* do 

```
salt 'thisminion' pip.installed docker-py==1.0.0
```

Just fine
