### ISSUE TITLE
salt-mine grains.items only works when configured on minion

### ISSUE THREAD

**Issue by savamane** [saltstack/salt#26523]
So, I have this mine configured in pillar:

```yaml
mine_functions:
  network.ip_addrs: [eth0]
  grains.item: [host]
```

and when testing from a minion, `network.ip_addrs` works just fine:

```
salt-call mine.get 'G@roles:db' 'network.ip_addrs' 'compound'
local:
    ----------
    db1.fqdn.com:
        - 10.10.10.11
    db2.fqdn.com:
        - 10.10.10.12
```

but the `grains.items` function doesn't and just returns empty:

```
salt-call mine.get 'G@roles:db'  'grains.item' 'compound'
local:
    ----------
```

If I add the `grains.items` function on both minions in `/etc/salt/minion.d/grains.conf`:

```
mine_functions:
  grains.items: [host]
```

I get the expected results:

```
salt-call mine.get 'G@roles:db' 'grains.item' 'compound'
local:
    ----------
    db1.fqdn.com:
        ----------
        host:
            db1
    db2.fqdn.com:
        ----------
        host:
            db2
```

Is that behavior  by design or did I somehow misunderstand how the mine should be set up in pillar. I would vastly prefer to avoid managing yet another file and just drop all mine functions I need in pillar.

Thanks.
