### ISSUE TITLE
salt.states.file.managed generates warning when used in place of salt.states.file.touch

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#26538]
Documentation about salt.states.file.touched state:

Note that if you just want to create a file and don't care about atime or mtime, you should use file.managed instead, as it is more feature-complete. (Just leave out the source/template/contents arguments, and it will just create the file and/or check its permissions, without messing with contents)

So as to "touch" a file and ensure proper permissions and ownership, I opted to use file.managed over file.touch and followed the recommendations.  However, you'll receive the following error in your logs if you don't include source/template/contents:

[WARNING ] Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily

Example:
```saltstack
/etc/neutron/dnsmasq-neutron.conf:
  file.managed:
    - makedirs: True
    - user: root
    - group: neutron
    - mode: 640
    - require_in:
      - service: neutron-l3-agent
      - service: neutron-dhcp-agent
      - service: neutron-metadata-agent
    - requires:
      - group: neutron
```
```yaml
salt --versions-report:
           Salt: 2015.5.3
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 0.8.1
        Tornado: Not Installed
```
