### ISSUE TITLE
postgres_user crashes when trying to add groups formed in a list

### ISSUE THREAD

**Issue by ryanwalder** [saltstack/salt#26632]
Assume postgresql is installed and running (no issues there), and groups are there (also works fine)

```
common-postgresql-user-test:
  postgres_user.present:
    - name: test
    - password: test
    - groups:
      - admins
```
Returns:
```
----------
          ID: common-postgresql-user-test
    Function: postgres_user.present
        Name: test
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/postgres_user.py", line 207, in present
                  **db_args)
                File "/usr/lib/python2.7/dist-packages/salt/modules/postgres.py", line 818, in user_create
                  runas=runas)
                File "/usr/lib/python2.7/dist-packages/salt/modules/postgres.py", line 761, in _role_create
                  rolepassword=rolepassword
                File "/usr/lib/python2.7/dist-packages/salt/modules/postgres.py", line 712, in _role_cmd_args
                  for group in groups.split(','):
              AttributeError: 'list' object has no attribute 'split'
     Started: 15:01:33.051579
    Duration: 230.201 ms
     Changes:   
----------
```

Which is no fun, it works when not formed as a list:

```
common-postgresql-user-test:
  postgres_user.present:
    - name: test
    - password: test
    - groups: admins
```
Returns:
```
----------
          ID: common-postgresql-user-test
    Function: postgres_user.present
        Name: test
      Result: True
     Comment: The user test has been created
     Started: 15:04:01.719624
    Duration: 261.637 ms
     Changes:   
              ----------
              test:
                  Present
```

Tested with v2015.5.0 to v2015.5.5 and 2015.8 (all from git using salt-bootstrap), Ubuntu 14.04 base.
