### ISSUE TITLE
Return data as JSON

### ISSUE THREAD

**Issue by frenkye** [saltstack/salt#26698]
Would be possible to have return data as JSON and not as string, when they are stored in the localcache?

Here a case:
1) Simple state to handle motd just file.manage
2) I will list jobs of operation:

```
20150804101401278855:
    ----------
    Arguments:
        - motd
    Function:
        state.sls
    StartTime:
        2015, Aug 04 10:14:01.278855
    Target:
        some_server
    Target-type:
        glob
    User:
        sudo_some_user
```

3) When I print job operation:

```
20150804101401278855:
    ----------
    Arguments:
        - [
        - "
        - m
        - o
        - t
        - d
        - "
        - ]
    Function:
        state.sls
    Result:
        ----------
        some_server:
            ----------
            return:
                {'file_|-/etc/motd_|-/etc/motd_|-managed': {'comment': 'File /etc/motd is in the correct state', 'name': '/etc/motd', 'start_time': '10:14:02.295386', 'result': True, 'duration': 15.189, '__run_num__': 0, 'changes': {}}}
    StartTime:
        2015, Aug 04 10:14:01.278855
    Target:
        some_server
    Target-type:
        glob
    User:
        sudo_some_user
```

Where the return is:

```
return:
                {'file_|-/etc/motd_|-/etc/motd_|-managed': {'comment': 'File /etc/motd is in the correct state', 'name': '/etc/motd', 'start_time': '10:14:02.295386', 'result': True, 'duration': 15.189, '__run_num__': 0, 'changes': {}}}
```

Which is not valid JSON, so my point is:
1) Could be there an option to specify format of the result which is being stored?
2) Could this be JSON by default.

salt report from master:

``` yaml
                  Salt: 2015.5.3
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed
               Tornado: 4.2
 Debian source package: 2015.5.3+ds-1~bpo8+1
```
