### ISSUE TITLE
salt-cloud adds (for AWS) wrong "nobootwait" option to "automounted" ephemeral devices in Debian instances which causes boot crash

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#26706]
````
root@nu3-salt01:~# salt --version
salt 2015.5.3 (Lithium)
root@nu3-salt01:~# salt-cloud --version
salt-cloud 2015.5.3 (Lithium)
````
````
root@jenkins:~# salt-call --version
salt-call 2015.5.3 (Lithium)
root@jenkins:~# lsb_release -d
Description:	Debian GNU/Linux 8.1 (jessie)
````

````
root@jenkins:~# cat /etc/fstab 
UUID=af868c19-1411-4fb0-91a4-17899429cd79 / ext4 defaults 1 1
/dev/xvdb	/mnt	auto	defaults,nobootwait,comment=cloudconfig	0	2
/dev/xvdd1		/data	ext4	defaults,noatime,nodiratime	0 0
````

Instance is not coming up - in AWS cloud log is written that this option wasn't reginozed and the instance go into emergency mode (sorry, no copy&paste log because I didn't got it from dev).

But when manually fixing it to e.g.:
````
/dev/xvdb	/mnt	auto	defaults,comment=cloudconfig	0	2
````
instance came up fine again.

**Comment by jfindlay** [comment]
@Reiner030, thanks for the report.  Is it possible for you to share the salt-cloud command you are using?

**Comment by rallytime** [comment]
@Reiner030 I am not sure if this is coming from salt. Salt cloud doesn't add any entries to fstab by default. Are you of any of salt's boto modules to do some configuration? Or could it be in the ami you're using?

**Comment by Reiner030** [comment]
Hello @jfindlay and @rallytime,

this is the initate call:
````
# salt-cloud -p jenkins jenkins
````

This is actual state of instance:
````
        jenkins:
            ----------
            id:
                i-a9a6bxxx
            image:
                ami-02b78e1f
            private_ips:
                172.31.18.100
            public_ips:
                52.28.xx.xx
            size:
                m3.large
            state:
                running
````
(running in eu-central-1, https://wiki.debian.org/Cloud/AmazonEC2Image/Jessie )
1. It would be very dump from Debian maintainers to put Ubuntu only supported mount options in their image ;)
2. We run also another instance without salt-cloud deploy (only instance initiating) with this image and there is no such mount option.

````
# cat /etc/salt/cloud.profiles.d/jenkins-master.conf
jenkins:
  provider: aws_eu_central_1
  image: ami-02b78e1f
  size: m3.large
  ssh_username: admin

  securitygroup:
    - localnet
    - "ssh only"
    - "HTTPS_private"

  grains:
    roles: jenkins-master
    filesystems:
      /dev/xvdd:
        filesystem: ext4
        disk: /dev/xvdd
        partition: 1
        mount_point: /data/
        mount_options: defaults,noatime,nodiratime

  minion:
    environment: prod
    mine_functions:
      network.ip_addrs:
        interface: eth0
        cidr: '172.0.0.0/8'

  # additional volumes
  block_device_mappings:

    # /root
    - DeviceName: /dev/xvda
      Ebs.DeleteOnTermination: False

    # ephemeral: instance storage devices
    - DeviceName: /dev/xvdb
      VirtualName: ephemeral0

    # /data
    - DeviceName: /dev/xvdd
      Ebs.VolumeSize: 500
      Ebs.DeleteOnTermination: False

  # this isn't necessary when i set DeleteOnTermination in the block_device_mappings?
  del_root_vol_on_destroy: False
  del_all_vols_on_destroy: False

  start_action: state.highstate
  script: bootstrap-salt
  flush_mine_on_destroy: True
````

I have rechecked for security our salt and pillar repositories... and no match of "nobootwait" found.

Aahh.. But it seems thats more a bug in mount.mounted - we use this function for mounting I just saw (we actually  adopting salt/pillars from another setup / the fine instance was mounted manually):

Our mount state (with above grains data from profile):
````
{% for fs, fs_details in grains.get('filesystems', {}).items() %}
[...]

mount-fs-{{ fs }}:
  mount.mounted:
    - name:   {{ fs_details.mount_point }}
    - device: {{ fs_details.disk }}{{ fs_details.partition }}
    - fstype: {{ fs_details.filesystem }}
    - opts:   {{ fs_details.mount_options }}
    - mkmnt:  True
    - require:
      - cmd: create-fs-{{ fs }}

{% endfor %}
````

Cloning and checking your repo ... 

````
$ grep -r nobootwait salt
salt/salt/states/mount.py:        - opts: nobootwait,noatime,nodiratime,nobarrier,logbufs=8
salt/salt/states/mount.py:                    'nobootwait',
salt/doc/man/salt.7:    \- opts: nobootwait,noatime,nodiratime,nobarrier,logbufs=8
````
mmh, thats only documentation and parameter check (checked in actual HEAD and tags/v2015.5.3)...

Should I check some library packet versions for you (didn't find Perl Like 1:1 mapping of library/file) ?
````
$ grep ^import ./salt/salt/states/mount.py
import os.path
import re
import logging
import salt.ext.six as six
````

**Comment by rallytime** [comment]
@Reiner030 Hrm...this looks more to me like a bug in the mount state. 

@garethgreenaway You've been doing work there a lot somewhat recently. Does this ring any bells to you?

**Comment by garethgreenaway** [comment]
I don't think we specifically add any fstab options but I'll take a look.

**Comment by Reiner030** [comment]
Btw. last seen an issue which was perhaps fixed last months (or it even works now?), because only 1st ephemeral was added: https://github.com/saltstack/salt/issues/8631

I would test the last month anncoued versions 2015.5.5 or 2015.8.0 but they aren't in the public repository available yet...^^

**Comment by rallytime** [comment]
@Reiner030 Yes, packaging in the community repos is a little behind our release schedule. In case you haven't seen any posts about it yet, we've started our own packaging repo (SaltStack repo vs a Community repo) which should have up-to-date packages. There's more information about that in our updated [Installation Docs](https://docs.saltstack.com/en/latest/topics/installation/index.html) or at our [Official Repo Landing Page](http://repo.saltstack.com/).

Thanks for updating the issue. I'd love to see if this is resolved for you once you get a chance to test this again.

**Comment by Reiner030** [comment]
Hi @rallytime ,

ok, what me irritated some weeks ago was the fact that searching in your actual bootstrap script for the right url/repository the facts:
- 8 matches for debian.saltstack.com and 
- 0 matches for repo.saltstack.com

So this assumes for me that I had the right URL and there are no updates ;)

And about your mentioned updated "Installation Docs":
````
QUICK INSTALL
On most distributions, you can set up a Salt Minion with the Salt Bootstrap.
=> https://github.com/saltstack/salt-bootstrap
````
The URL to bootstrap files shows me that the quick way is referencing automatically the community package then (which is still not updated)?
=> would be nice then to have a short hint about this in the documentation. Thx. ;)

**Comment by rallytime** [comment]
@Reiner030 Oh, in terms of updated installation docs, I meant the official Salt Installation Docs for Platform Specific Instructions. I didn't even remember that the Quick Install instructions were there. Sorry for the confusion. The Platform Specific docs have been updated to show how to use the repo.saltstack.com packages. So, for instance if there are packages available on repo.saltstack.com such as for the RHEL-bassed distros and Debian-based distros, there are instructions for installing using repo.saltstack.com AND the original community repos.

Unfortunately we still haven't gotten the bootstrap script updated yet, as you pointed out. I know that is at the top of our list and we are working on it. Hopefully it will be finished and pushed up to stable very soon.

**Comment by jfindlay** [comment]
@Reiner030, bootstrap has been updated to use repo.saltstack.com in https://github.com/saltstack/salt-bootstrap/pull/674.  You can begin to use the new version immediately by referencing https://bootstrap.saltstack.com/develop or doing `salt-cloud -u`.

**Comment by Reiner030** [comment]
Yesterday I tested boto / instance setups in a new region and got again into this problem.
Searching for the error message
````Welcome to emergency mode! After logging in, type "journalctl -xb" to view
system logs, "systemctl reboot" to reboot, "systemctl default" to try again
to boot into default mode.````
let me find this bug notification which looks that the "nobootwait" bug is a cloud-init problem of AWS directly: http://osdir.com/ml/general/2015-06/msg36001.html

So this issue can be closed - I guess it make no sense to build a (temporary) workouround for it in salt ?

**Comment by techhat** [comment]
Thanks @Reiner030.

**Comment by Reiner030** [comment]
temp fix as final info:
````
fix-fstab-noboowait:
  cmd.run:
    - name: sed -e "s/nobootwait/nofail/" -i /etc/fstab
    - onlyif: grep -q nobootwait /etc/fstab

/etc/cloud/cloud.cfg.d/00_debian.cfg:
  file.append:
    - text: |
        mount_default_fields: [~, ~, 'auto', 'defaults,nofail', '0', '2']
````
