### ISSUE TITLE
log-level in mount_invisible_* still triggering remount

### ISSUE THREAD

**Issue by DaveQB** [saltstack/salt#26728]
```
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1precise1
```

Hi,

Using some gluster mount options in a mount.mounted block sees a remount triggered when running a highstate. I found an issue on here that lead me to the 'mount_invisible_options' and 'mount_invisible_keys' lists in the mount.py file. I found that the direct-io-mode has been added since my version of salt (YAY!) but log-level= had not. So I added it to the 'mount_invisible_keys' list in states/mount.py and ran a highstate but no better. Also tried added 'log-level' to 'mount_invisible_options' but difference. Still getting:

```
----------
          ID: mount-homes
    Function: mount.mounted
        Name: /home
      Result: True
     Comment: Target was already mounted. Entry already exists in the fstab.
     Started: 16:45:21.522960
    Duration: 424.497 ms
     Changes:   
              ----------
              umount:
                  Forced remount because options (log-level=WARNING) changed
```

PS I didn't have any mount.pyc files to clean up.

**Comment by jfindlay** [comment]
@DaveQB, thanks for the report.

**Comment by DaveQB** [comment]
I meant to add a little more detail.

Here is my fstab line:

```
filer.think.vpc:/homes          /home   glusterfs       log-file=/var/log/glusterfs/fstab-homes.log,log-level=WARNING,defaults,auto,_netdev,rw  0 0
```

And here is how it looks when mounted and list with the mount -l command:

```
filer.think.vpc:/homes on /home type fuse.glusterfs (rw,default_permissions,allow_other,max_read=131072)
```

**Comment by garethgreenaway** [comment]
IIRC 2014.7 isn't a supported release, are you able to upgrade to 2015.5?  There were quite a few fixes related to the mount modules in that release.

**Comment by Reiner030** [comment]
Hello,

problem still exists:
* with version/on system:
````
root@test-euc1-01:~# salt-call --version
salt-call 2015.8.5 (Beryllium)
root@test-euc1-01:~# lsb_release -d
Description:    Debian GNU/Linux 8.3 (jessie)
````
* with generated states:
````
glusterfs-client:
  pkg.installed

/data/storage:
  mount.mounted:
    - device: gluster-cluster:/gluster
    - fstype: glusterfs
    - opts:
      - defaults
      - backup-volfile-servers=glusterfs-euc1-01:glusterfs-euc1-02
    - persist: True
    - mkmnt: True
````

* log excerpt:
````
....
2016-02-12 12:11:55,268 [salt.loaded.int.module.cmdmod][INFO    ][17007] Executing command 'mount -o defaults,backup-volfile-se
rvers=glusterfs-euc1-01:glusterfs-euc1-02,remount -t glusterfs gluster-cluster:/gluster /data/storage ' in directory '/root'
2016-02-12 12:11:55,281 [salt.loaded.int.module.cmdmod][ERROR   ][17007] Command 'mount -o defaults,backup-volfile-servers=glus
terfs-euc1-01:glusterfs-euc1-02,remount -t glusterfs gluster-cluster:/gluster /data/storage ' failed with return code: 1
2016-02-12 12:11:55,281 [salt.loaded.int.module.cmdmod][ERROR   ][17007] stderr: Invalid option remount
2016-02-12 12:11:55,282 [salt.loaded.int.module.cmdmod][ERROR   ][17007] retcode: 1
2016-02-12 12:11:55,282 [salt.state       ][ERROR   ][17007] {'umount': 'Forced remount because options (backup-volfile-servers
=glusterfs-euc1-01:glusterfs-euc1-02) changed'}
...
----------
          ID: /data/storage
    Function: mount.mounted
      Result: Invalid option remount
     Comment: Target was already mounted. Entry already exists in the fstab.
     Started: 12:11:55.236230
    Duration: 45.959 ms
     Changes:
              ----------
              umount:
                  Forced remount because options (backup-volfile-servers=glusterfs-euc1-01:glusterfs-euc1-02) changed
````

* Additional to the unneded remount try because options didn't change 
* there is logged that glusterfs didn't now the option "remount" 
  So it would be nice if this change can be done by an lazy unmount/mount ?

**Comment by jfindlay** [comment]
@Reiner030, in 2015.8.2 and later, there is a `hidden_opts` option to `mount.mounted`, where you can specify mount options to ignore for deciding whether to remount.

**Comment by DenisBY** [comment]
@jfindlay looks like it doesn't work. I have the following:
```
    - extra_mount_invisible_options:
      - _netdev
      - allow_other
    - extra_mount_invisible_keys:
      - --file-mode
      - --uid
      - --gid
    - opts:
      - _netdev,allow_other,--file-mode=0666,--uid=1004,--gid=33
    - hidden_opts:
      - _netdev
      - allow_other
      - --file-mode
      - --uid
      - --gid
```

But still getting:
```
          ID: /srv/vdf
    Function: mount.mounted
      Result: None
     Comment: Remount would be forced because options (_netdev,allow_other,--file-mode=0666,--uid=1004,--gid=33) changed
     Started: 13:43:33.523591
    Duration: 12.914 ms
     Changes:   
```

Maybe I'm doing something wrong?
