### ISSUE TITLE
MySQLdb-python package should be included with windows minion installer

### ISSUE THREAD

**Issue by jefftucker** [saltstack/salt#26754]
```yaml
Salt: 2015.5.2
Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
Jinja2: 2.7.3
M2Crypto: 0.21.1
msgpack-python: 0.4.5
msgpack-pure: Not Installed
pycrypto: 2.6
libnacl: Not Installed
PyYAML: 3.11
ioflo: Not Installed
PyZMQ: 14.6.0
RAET: Not Installed
ZMQ: 4.0.5
Mako: Not Installed
```
The MySQLdb-python package is a huge pain to install on windows with pip or easy_install since it needs to compile native code and doing that from pip is broken unless you have a magic Visual Studio 2008 setup that I can't seem to replicate.  There is a binary available but it has no .msi so I can't silent install (and therefore can't highstate it onto my own minions).  It would be super convenient if everything could just be included with the windows minion installer.  The mysql module depends on this package.  Without it being bundled, I have to manually run the binary installer .exe and point the GUI at the correct directory which sort of defeats the purpose of being able to highstate my machine into having everything it needs.

Alternatively since it appears MySQLdb-python isn't really being developed anymore you could make the mysql module depend on something like PyMySql instead, which installs just fine on Windows with pip and advertises that it's a drop-in replacement for MySQLdb-python.  It seems like it's under much more active development and is a pure python MySQL client.

If there's some sort of standard way to work around this issue then it's not in any documentation that I can find beyond "install the module somehow"
