### ISSUE TITLE
cur_param referenced before assignment

### ISSUE THREAD

**Issue by joejulian** [saltstack/salt#26805]
https://github.com/saltstack/salt/blob/2015.5/salt/modules/localemod.py#L41

This line can cause an UnboundLocalError if a line is returned without a colon, ie:

    Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 error=n/a

This line will split into only one list entry leaving the len of that entry to = 1 leaving cur_param unset.

**Comment by jfindlay** [comment]
@joejulian, thanks for the report.  I am curious though about how you got that line as a result from `localectl`.  When I run `localectl` I get
```yaml
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us
```
