### ISSUE TITLE
repo.saltstack.com debian 8 package dependency problem

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#26829]
### configs
```console
# cat /etc/sources.list
...    
####################
# Enable SaltStack's package repository
deb http://repo.saltstack.com/apt/deb8 jessie contrib
```

### commands
The following error prevents `salt-{master|syndic|minion|api}` from being installed.  The remainder of the salt packages do install.
```console
# aptitude -y install salt-master salt-minion salt-api salt-cloud salt-ssh salt-syndic
Reading package lists...
Building dependency tree...
Reading state information...
Initializing package states...
Writing extended state information...
Reading task descriptions...
Building tag database...
The following NEW packages will be installed:
  dctrl-tools{a} debconf-utils{a} dmidecode{a} git{a} git-man{a} 
  ieee-data{a} javascript-common{a} liberror-perl{a} libjs-jquery{a} 
  libjs-sphinxdoc{a} libjs-underscore{a} libpgm-5.1-0{a} libsodium13{a} 
  libyaml-0-2{a} libzmq3{ab} python-async{a} 
  python-backports.ssl-match-hostname{a} python-cffi{a} python-cherrypy3{a} 
  python-crypto{a} python-cryptography{a} python-dateutil{a} python-git{a} 
  python-gitdb{a} python-jinja2{a} python-libcloud{a} python-lockfile{a} 
  python-m2crypto{a} python-mako{a} python-markupsafe{a} python-msgpack{a} 
  python-ndg-httpsclient{a} python-netaddr{a} python-openssl{a} 
  python-ply{a} python-pyasn1{a} python-pycparser{a} python-repoze.lru{a} 
  python-requests{a} python-routes{a} python-simplejson{a} python-smmap{a} 
  python-urllib3{a} python-webob{a} python-yaml{a} python-zmq{a} salt-api 
  salt-cloud salt-common{a} salt-master salt-minion salt-ssh salt-syndic 
0 packages upgraded, 53 newly installed, 0 to remove and 0 not upgraded.
Need to get 14.1 MB of archives. After unpacking 85.9 MB will be used.
The following packages have unmet dependencies:
 libzmq3 : Depends: libstdc++6 (>= 5.2) but 4.9.2-10 is installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     libzmq3 [Not Installed]                            
2)     python-zmq [Not Installed]                         
3)     salt-api [Not Installed]                           
4)     salt-master [Not Installed]                        
5)     salt-minion [Not Installed]                        
6)     salt-syndic [Not Installed]                        
```

### versions
```yaml
# salt-call --versions
          Salt: 2015.5.5
        Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
        Jinja2: 2.7.3
      M2Crypto: Not Installed
msgpack-python: 0.4.2
  msgpack-pure: Not Installed
      pycrypto: 2.6.1
       libnacl: Not Installed
        PyYAML: 3.11
         ioflo: Not Installed
         PyZMQ: Not Installed
          RAET: Not Installed
           ZMQ: Not Installed
          Mako: 1.0.0
       Tornado: Not Installed
       timelib: Not Installed
      dateutil: 2.2
```
