### ISSUE TITLE
lvm pv's can show as not belonging to their vg if symlink is used

### ISSUE THREAD

**Issue by joejulian** [saltstack/salt#26867]
With the following sample, the second pass will fail as /dev/disk/by-partlabel/LVM is a symlink to /dev/sda3 (in this case) created by udev but vgdisplay shows the actual device, /dev/sda3. vg_present then tries and fails to pvextend the vg but fails as the device is already part of the vg.

```
sample_vg:
    lvm.vg_present:
        - devices: /dev/disk/by-partlabel/LVM
        - name: vg1
```
