### ISSUE TITLE
webutil.user_exists state does not respect test=true

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#27021]
Given a state like this:

```yaml
someuser-htpasswd:
  webutil.user_exists:
    - name: someuser
    - password: somepasswd
    - options: s
    - force: true
    - htpasswd_file: /etc/httpd/conf.d/someuser.htpasswd
```

When running with test=true, it unexpectedly added the user:
```yaml
----------
          ID: someuser-htpasswd
    Function: webutil.user_exists
        Name: someuser
      Result: True
     Comment: Adding password for user someuser
     Started: 12:26:40.795241
    Duration: 64.764 ms
     Changes:   
              ----------
              someuser:
                  True
```
