### ISSUE TITLE
[FreeBSD] grains return 'proxy' in error

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#27039]
Below is the grains output on my FreeBSD host. You'll notice many of the fields that usually report 'FreeBSD' now return 'proxy'. This is breaking the loading of many core platform modules. Please let me know what additional information I can provide. (v.2015.8.0)

```
emma ~ # salt-call -g
local:
    ----------
    SSDs:
    biosreleasedate:
        04/12/2010
    biosversion:
        A07
    cpuarch:
        amd64
    disks:
        ----------
        ada0:
            ----------
            WWN:
                50014ee1586e4096
            device_model:
                WDC WD5000AAKS-75V0A0
            firmware_revision:
                05.01D05
            protocol:
                ATA/ATAPI-8 SATA 2.x
            sector_size:
                logical 512, physical 512, offset 0
            serial_number:
                WD-WCAWF7581456
    domain:
    fqdn:
        emma
    fqdn_ip4:
    fqdn_ip6:
    gpus:
    host:
        emma
    hwaddr_interfaces:
        ----------
        bge0:
            b8:ac:6f:92:63:da
    id:
        emma
    ip4_interfaces:
        ----------
        bge0:
            - 192.168.1.30
        lo0:
            - 127.0.0.1
        lo1:
            - 10.0.0.1
            - 10.0.0.10
            - 10.0.0.20
            - 10.0.0.30
            - 10.0.0.40
            - 10.0.0.50
            - 10.0.0.60
            - 10.0.0.70
        pflog0:
    ip6_interfaces:
        ----------
        bge0:
        lo0:
            - ::1
            - fe80::1
        lo1:
        pflog0:
    ip_interfaces:
        ----------
        bge0:
            - 192.168.1.30
        lo0:
            - 127.0.0.1
            - ::1
            - fe80::1
        lo1:
            - 10.0.0.1
            - 10.0.0.10
            - 10.0.0.20
            - 10.0.0.30
            - 10.0.0.40
            - 10.0.0.50
            - 10.0.0.60
            - 10.0.0.70
        pflog0:
    ipv4:
        - 10.0.0.1
        - 10.0.0.10
        - 10.0.0.20
        - 10.0.0.30
        - 10.0.0.40
        - 10.0.0.50
        - 10.0.0.60
        - 10.0.0.70
        - 127.0.0.1
        - 192.168.1.30
    ipv6:
        - ::1
        - fe80::1
    kernel:
        proxy
    kernelrelease:
        proxy
    locale_info:
        ----------
        defaultencoding:
            UTF-8
        defaultlanguage:
            en_US
        detectedencoding:
            UTF-8
    localhost:
        emma
    manufacturer:
        Dell Inc.
    master:
        10.0.0.1
    mem_total:
        0
    nodename:
        emma
    num_gpus:
        0
    os:
        proxy
    os_family:
        proxy
    osarch:
        amd64
    osrelease:
        proxy
    osrelease_info:
        - proxy
    path:
        /sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin:/usr/local/bin:/usr/local/sbin
    productname:
        Precision WorkStation T3500
    ps:
        ps -efH
    pythonexecutable:
        /usr/local/bin/python2.7
    pythonpath:
        - /usr/local/bin
        - /usr/local/lib/python27.zip
        - /usr/local/lib/python2.7
        - /usr/local/lib/python2.7/plat-freebsd10
        - /usr/local/lib/python2.7/lib-tk
        - /usr/local/lib/python2.7/lib-old
        - /usr/local/lib/python2.7/lib-dynload
        - /usr/local/lib/python2.7/site-packages
        - /usr/local/lib/python2.7/site-packages/git/ext/gitdb
        - /usr/local/lib/python2.7/site-packages/gitdb/ext/smmap
    pythonversion:
        - 2
        - 7
        - 10
        - final
        - 0
    saltpath:
        /usr/local/lib/python2.7/site-packages/salt
    saltversion:
        2015.8.0
    saltversioninfo:
        - 2015
        - 8
        - 0
        - 0
    serial:
        93Q4KN1
    server_id:
        717889124
    shell:
        /usr/local/bin/zsh
    uuid:
        44454c4c-3300-1051-8034-b9c04f4b4e31
    virtual:
        physical
    zmqversion:
        4.1.3
```
