### ISSUE TITLE
support for file.managed with blockreplace , accumulated text

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#27059]
It would be nice if we had support for managed files with blockreplace.
Currently I have to use accumulated and some jinja...  like: 

`{{ '\n'.join(accumulator.get('accumulator', [])) }}`

with a sls file like this: 

```
{{ sls }} file:
    file.managed:
        - name: /tmp/test
        - contents: '#TEST'
        - replace: True
        - template: jinja

{{ sls }} block:
    file.blockreplace:
        - name: /tmp/test
        - marker_start: "# START: managed ---- {{ sls }} ----"
        - marker_end: "# END: managed ---- {{ sls }} ----"
        - append_if_not_found: True
        - show_changes: True
        - require_in:
            - file: {{ sls }} file

{{ sls }} block accumulated:
    file.accumulated:
        - filename: /tmp/test
        - text: "## TEST"
        - require_in:
            - file: {{ sls }} block
```

expected highstate output

```
          ID: test.sls block accumulated
    Function: file.accumulated
      Result: True
     Comment: Accumulator test.sls block accumulated for file /tmp/test was charged by text
     Started: 12:14:41.390549
    Duration: 1.592 ms
     Changes:   
----------
          ID: test.sls block
    Function: file.blockreplace
        Name: /tmp/test
      Result: True
     Comment: Changes were made
     Started: 12:14:41.399664
    Duration: 4.764 ms
----------
     Changes:
              diff:
                  --- 
                  +# START: managed ---- test.sls ----
                  +## TEST
                  +# END: managed ---- test.sls ----
              or perhaps:
                  create file.
----------
          ID: test.sls file
    Function: file.managed
        Name: /tmp/test
      Result: True
     Comment: File /tmp/test updated
     Started: 12:14:41.370871
    Duration: 3.423 ms
     Changes:   
----------
              diff:
                  --- 
                  +++ 
                  @@ -1 +1,4 @@
                  +#TEST
                  +# START: managed ---- test.sls ----
                  +## TEST
                  +# END: managed ---- test.sls ----
              or perhaps:
                 create file
```

actual highstate output...

```
          ID: test.sls block accumulated
    Function: file.accumulated
      Result: True
     Comment: Accumulator test.sls block accumulated for file /tmp/test was charged by text
     Started: 12:09:32.426200
    Duration: 1.547 ms
     Changes:   
----------
          ID: test.sls block
    Function: file.blockreplace
        Name: /tmp/test
      Result: False
     Comment: /tmp/test: file not found
     Started: 12:09:32.433584
    Duration: 1.512 ms
     Changes:   
----------
          ID: test.sls file
    Function: file.managed
        Name: /tmp/test
      Result: False
     Comment: One or more requisite failed: test.sls.test.sls block
     Started: 
    Duration: 
     Changes:   
```

See block-replace cant append to the file because it does not exist yet.
What would be nice to see happen is this block be held in memory and applied to the managed file after rendering template code.
