### ISSUE TITLE
Recursive directory management doesn't preserve permissions

### ISSUE THREAD

**Issue by andrewclegg** [saltstack/salt#2707]
OS: Centos 6.3

Example usage:

```yaml
/opt/elasticsearch:
    file.recurse:
        - source: salt://dist/elasticsearch/0.19.10
        - user: elasticsearch
        - group: elasticsearch
        - include_empty: True
        - require:
            - user: elasticsearch
```

salt://dist/elasticsearch/0.19.10 just contains an unpacked elasticsearch distribution on the master.

On the minion, everything is set to 644 (files) / 755 (dirs) meaning that scripts are no longer executable, and have to be fixed afterwards.
