### ISSUE TITLE
garns.items fqdn is not correct

### ISSUE THREAD

**Issue by freedba** [saltstack/salt#27079]
Hi,

I want get some minios hostname via granis.items fqdn ,but I got a wrong  hostname , Why?

```yaml
# salt 'cms05*' grains.items
cms05.idc1.fn:
    ----------
    SSDs:
    biosreleasedate:
        06/22/2012
    biosversion:
        6.00
    cpu_flags:
        - fpu
        - vme
        - de
        - pse
        - tsc
        - msr
        - pae
        - mce
        - cx8
        - apic
        - sep
        - mtrr
        - pge
        - mca
        - cmov
        - pat
        - pse36
        - clflush
        - dts
        - mmx
        - fxsr
        - sse
        - sse2
        - ss
        - ht
        - syscall
        - nx
        - rdtscp
        - lm
        - constant_tsc
        - arch_perfmon
        - pebs
        - bts
        - xtopology
        - tsc_reliable
        - nonstop_tsc
        - aperfmperf
        - unfair_spinlock
        - pni
        - pclmulqdq
        - ssse3
        - cx16
        - sse4_1
        - sse4_2
        - popcnt
        - aes
        - xsave
        - avx
        - hypervisor
        - lahf_lm
        - ida
        - arat
        - xsaveopt
        - pln
        - pts
        - dts
    cpu_model:
        Intel(R) Xeon(R) CPU E5-2650L 0 @ 1.80GHz
    cpuarch:
        x86_64
    domain:
        idc1.fn
    fqdn:
        mysql01.idc1.fn
    fqdn_ip4:
        - 10.201.133.23
    fqdn_ip6:
    gpus:
        |_
          ----------
          model:
              SVGA II Adapter
          vendor:
              unknown
    host:
        mysql01
    hwaddr_interfaces:
        ----------
        eth0:
            00:50:56:92:c6:16
        eth1:
            00:50:56:92:32:1e
        lo:
            00:00:00:00:00:00
    id:
        cms05.idc1.fn
    init:
        upstart
    ip4_interfaces:
        ----------
        eth0:
            - 10.201.130.29
        eth1:
            - 10.201.30.29
        lo:
            - 127.0.0.1
    ip6_interfaces:
        ----------
        eth0:
        eth1:
        lo:
    ip_interfaces:
        ----------
        eth0:
            - 10.201.130.29
        eth1:
            - 10.201.30.29
        lo:
            - 127.0.0.1
    ipv4:
        - 10.201.130.29
        - 10.201.30.29
        - 127.0.0.1
    ipv6:
    kernel:
        Linux
    kernelrelease:
        2.6.32-358.el6.x86_64
    locale_info:
        ----------
        defaultencoding:
            UTF8
        defaultlanguage:
            en_US
        detectedencoding:
            UTF8
    localhost:
        cms05.idc1.fn
    lsb_distrib_codename:
        Final
    lsb_distrib_id:
        CentOS
    lsb_distrib_release:
        6.4
    machine_id:
        8b4c6a50c51dc21299c28de500000018
    manufacturer:
        VMware, Inc.
    master:
        10.201.128.248
    mdadm:
    mem_total:
        15947
    nodename:
        cms05.idc1.fn
    num_cpus:
        8
    num_gpus:
        1
    os:
        CentOS
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        Final
    osfinger:
        CentOS-6
    osfullname:
        CentOS
    osmajorrelease:
        6
    osrelease:
        6.4
    osrelease_info:
        - 6
        - 4
    path:
        /sbin:/usr/sbin:/bin:/usr/bin
    productname:
        VMware Virtual Platform
    ps:
        ps -efH
    pythonexecutable:
        /usr/bin/python2.6
    pythonpath:
        - /usr/bin
        - /usr/lib64/python26.zip
        - /usr/lib64/python2.6
        - /usr/lib64/python2.6/plat-linux2
        - /usr/lib64/python2.6/lib-tk
        - /usr/lib64/python2.6/lib-old
        - /usr/lib64/python2.6/lib-dynload
        - /usr/lib64/python2.6/site-packages
        - /usr/lib/python2.6/site-packages
    pythonversion:
        - 2
        - 6
        - 6
        - final
        - 0
    saltpath:
        /usr/lib/python2.6/site-packages/salt
    saltversion:
        2015.5.3
    saltversioninfo:
        - 2015
        - 5
        - 3
        - 0
    selinux:
        ----------
        enabled:
            False
        enforced:
            Disabled
    serialnumber:
        VMware-42 12 fc 51 cc 17 ca 9a-da 4a 2d 34 f6 f1 f4 d0
    server_id:
        1562451402
    shell:
        /bin/bash
    virtual:
        VMware
    zmqversion:
        3.2.4
```
```
# salt 'cms05*' cmd.run "hostname"
cms05.idc1.fn:
    cms05.idc1.fn
```
Thank you!!!
