### ISSUE TITLE
Minion is down on the master, but is still running.

### ISSUE THREAD

**Issue by jcrosby84** [saltstack/salt#27105]
I am having an odd issue with salt. I have 7 minions that just stop responding on the master side somewhere around 24 hours after a restart. This is out of almost 50 minions. I cannot pinpoint when they stop working as I see nothing in the log or the debug output on either the minion or the master. The really odd thing is that the minion service is still running just fine and I can use salt-call locally to run states. All machines are running ubuntu 12.04 and are up to date with the newest version of salt and the version of zeromq from the salt repo. I am not sure what more to do to troubleshoot. I have tried to use debug mode on both the minion and the master and purged and reinstalled the minion on a couple of the machines.

The salt versions report shows these versions and it is the same for both minion and master. They all install and update from the same repo that I have internally set up.
```yaml
                  Salt: 2015.5.3
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.5.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1precise2
```
All of these servers are on different vlans, some are on the same one as the Salt Master, some are not. All of the vlans have minions on them that are working perfectly though.
