### ISSUE TITLE
v2015.8.0 fails ec2 deploy with 401: "AWS was not able to validate the provided access credentials"

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#27121]
A downgrade to 2015.5.5 confirms that this did work in the earlier release.

Profile:
```
haproxy-gateway:
  extends: base-ec2-linux
  private_key: /etc/salt/.ssh/staging-sshkey-proxy.pem
  keyname: staging-sshkey-proxy.pem.pub
  iam_profile: HAProxyRole
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: False
      SubnetId: subnet-xxxxx
      SecurityGroupId: sg-xxxxx
  tag: {'Environment': 'staging', 'Role': 'proxy'}
```

Response:
```
[DEBUG   ] Using EC2 endpoint: ec2.us-west-2.amazonaws.com
[DEBUG   ] EC2 Request: https://ec2.us-west-2.amazonaws.com/
[INFO    ] Starting new HTTPS connection (1): ec2.us-west-2.amazonaws.com
[DEBUG   ] "GET /?Action=ModifyNetworkInterfaceAttribute&NetworkInterfaceId=eni-71970d17&Attachment.DeleteOnTermination=True&Attachment.AttachmentId=eni-attach-6f56f064&Version=2014-10-01 HTTP/1.1" 401 None
[DEBUG   ] EC2 Response Status Code: 401
[ERROR   ] EC2 Response Status Code and Error: [401 401 Client Error: Unauthorized] {'Errors': {'Error': {'Message': 'AWS was not able to validate the provided access credentials', 'Code': 'AuthFailure'}}, 'RequestID': '5ac5b0e1-09f2-4f03-9847-7b4936e77861'}
```

The deploy does continue and does create a running instance, albeit without a network interface.

**Comment by jfindlay** [comment]
@rterbush, thanks for the report.

**Comment by rallytime** [comment]
It looks to me like this was likely broken by the changes in #25319. @ruzarowski Do you think you could take a look at this bug if you get a moment?

**Comment by ruzarowski** [comment]
@rallytime We've been using #25319 as backported patch to 2014.7 since my MR in a production env, but I might take a look at it sometime soon. Though it looks as if another change in 2015.8 might interfere here.

**Comment by rallytime** [comment]
@ruzarowski OK, thanks for confirming. There must be something else causing this error.

**Comment by ruzarowski** [comment]
I'd say it could be something with the IAM Role the reporter specified in
his map, as we do not use it so it might be the cause
(As in :  have never seen it working)

**Comment by rterbush** [comment]
Provider details:
```
aws-us-west-2a-public-ips:
  minion:
    master: hostname

  private_key: /etc/salt/salt-provisioning-key
  keyname: salt-provisioning-key
  ssh_interface: public_ips
  ssh_username: ec2-user
  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'
  location: us-west-2
  availability_zone: us-west-2a
  iam_profile: ManagementServerRole
  driver: ec2
```

Complete profile:
```
haproxy-gateway:
  provider: aws-us-west-2a-public-ips
  image: ami-xxxx
  size: t2.micro
  del_root_vol_on_destroy: True
  rename_on_destroy: True
  private_key: /etc/salt/staging-sshkey-proxy.pem
  keyname: staging-sshkey-proxy.pem.pub
  iam_profile: HAProxyRole
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: False
      SubnetId: subnet-xxxxx
      SecurityGroupId: sg-xxxxx
  tag: {'Environment': 'staging', 'Role': 'proxy'}
```

As I mentioned in the initial report, this works in 2015.5.5. IAM Profiles do work in 2015.5.5 as well.

In the error message I included above, the specific issue it is failing on is changing attribute for the network interface which as I remember, was not the first action the process performed which needed credentials (which it gets in the IAM profile assignment). It seems those credentials may not be getting carried through all required actions.
