### ISSUE TITLE
[Ubuntu] 2015.5.5 and 2015.8.0 installation from PPA

### ISSUE THREAD

**Issue by yermulnik** [saltstack/salt#27159]
Hi there!
How often `ppa:saltstack/salt` gets updated?
Installation doc at https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html recommends to use that PPA, but the most latest version of SaltStach there for `Ubuntu trusty` is 2015.5.3 and seems to a bit outdated.

**Comment by jfindlay** [comment]
@yermulnik, @joehealy is our official debian and ubuntu maintainer, and from 2015.8.0 on we are going to also provide upstream packages at https://repo.saltstack.com/.  This work has been taking longer than we expected, but we should have 2015.8.0 ubuntu packages soon.

**Comment by yermulnik** [comment]
OK, thanx. Will be waiting =)

**Comment by Deshke** [comment]
@jfindlay @joehealy could we try to add ubuntu packages to repo.saltstack.com?

**Comment by jfindlay** [comment]
Related to #26928.

**Comment by jfindlay** [comment]
@Deshke, repo.saltstack.com will be hosting 2015.8.0 and newer packages.  We could add older packages as well if there is demand for it.  Another thing to remember is that the packages on repo.saltstack.com are autogenerated by a salt builder cluster, where each minion builds packages and repos for its OS and version.

**Comment by mpaolini** [comment]
+1 please ;)

**Comment by gadams999** [comment]
Would love to see 2015.8.0 packages also, so double +1 for me!

**Comment by richardhansen** [comment]
All related issues I could find: #26599 #26879 #26928 #27159

**Comment by felippeb** [comment]
so i was searching around and found:

http://repo.saltstack.com/apt/ shows packages. the key posted on the debian section of repo.saltstack.com works. this string works in /etc/apt/sources.list:

deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main

use at your own peril.

**Comment by jfindlay** [comment]
@felippeb, yes, I was going to comment here when the ubuntu packages were moved out of https://repo.saltstack.com/staging/apt, but it seems @dmurphy18 has already done so for ubuntu 14.04.

**Comment by JaseFace** [comment]
So is that the final directory structure?  Normally you'd have them all merged into one meaning Precise and Trusty would converge on a quick Salt addition:

deb http://repo.saltstack.com/apt/ubuntu {{ grains['oscodename'] }} main

The ubuntu14 (and I assume ubuntu12 counterpart) just looks a big odd is all.

At any rate, thanks for getting these repos up!  Already have a few boxes pointed at them running 2015.8.0.

**Comment by jfindlay** [comment]
@JaseFace, we're still getting some things worked out but should have a more canonical repo setup soon.

**Comment by dmurphy18** [comment]
@JaseFace the staging area is for test/development and should not be considered final packages, the correct repo.saltstack.com/apt/debian and repo.saltstack.com/apt/ubuntu are the respective areas for downloading final packages for those platforms.  The Ubuntu 12.04 support is under-going final development as some of the platform dependencies for salt 2015.8.0 are worked out.  FYI - the packages under debian also work with Ubuntu 15.04, that is, work with systemd, which is not supported sufficiently for salt's needs on Ubuntu 12.04 and 14.04.  The aim will be to support Ubuntu 12.04 and 14.04 similar to other Ubuntu repositories when they are ready.

**Comment by richardhansen** [comment]
@jfindlay: I suggest going a step beyond what @JaseFace suggested and eliminate the `debian` and `ubuntu` subdirectories (just put everything under `/apt`).  For example, Debian Jessie users would do the following:

    deb http://repo.saltstack.com/apt jessie main

while Ubuntu Trusty users would do this:

    deb http://repo.saltstack.com/apt trusty main

The `jessie` and `trusty` disambiguate the files, allowing them to peacefully coexist within the same base URL.  For compatibility you can add `debian` and `ubuntu` symlinks that just point to `.`.

Advantages of laying out the repository this way:
  * it's easier to script—just use `$(lsb_release -sc)` or `{{grains.oscodename}}` and it'll work regardless of whether you're using Debian, Ubuntu, or Mint (assuming the repo has packages available for the machine's distribution and release)
  * it avoids duplicate source tarballs and source package data between the repos
  * if a new distribution/release is compatible with another, you can simply drop a symlink in the `dists` subdirectory to support the new distribution/release (e.g., you can instantly support Mint 17.3 users by creating a symlink named `rosa` pointed at `trusty`, assuming the `trusty` packages seamlessly work on Mint 17.3)

Useful links:
  * https://wiki.debian.org/RepositoryFormat 
  * https://www.debian-administration.org/article/286/Setting_up_your_own_APT_repository_with_upload_support

**Comment by jfindlay** [comment]
@richardhansen, thanks for the excellent information.  We're working on getting the repos and packages out at this point and then publishing the state files we use to generate them.  At that point you will be able to read over the states themselves and submit pull requests, not that you'll have to submit feedback that way, but we're hoping that this will ultimately make packaging more transparent and more of a community effort.

**Comment by yermulnik** [comment]
To sum up all the above: from now on Ubuntu users can use `repo.saltstack.com/apt/ubuntu` to install and upgrade SaltStack?

**Comment by richardhansen** [comment]
@yermulnik:

> To sum up all the above: from now on Ubuntu users can use `repo.saltstack.com/apt/ubuntu` to install and upgrade SaltStack?

Sort of.  You can manually browse to that URL and download the appropriate `.deb` files, but if you want to add the apt repository to your system you would currently add:

    deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main

to `/etc/apt/sources.list` (or to a file in `/etc/apt/sources.list.d`).  That URL may change soon.

**Comment by yermulnik** [comment]
I'm trying to add this repo, but it fails with the following error:
```yaml
----------
          ID: salt-minion
    Function: pkgrepo.managed
        Name: deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main
      Result: False
     Comment: Failed to configure repo 'deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main': W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              E: Some index files failed to download. They have been ignored, or old ones used instead.
     Started: 10:27:01.151546
    Duration: 7950.892 ms
     Changes:
----------
```
SSL verification seems to be Ok:
```shell
(jail) [root#jail_salt][w:0][j:0][.../salt/states]> salt jail_ubuntu cmd.run 'openssl s_client -connect repo.saltstack.com:443 -CAfile /etc/ssl/certs/ca-certificates.crt </dev/null 2>/dev/null| fgrep "Verify return code"'
jail_ubuntu:
        Verify return code: 0 (ok)
```
Installed `ca-certificates` package version is 20141019ubuntu0.14.04.1 (latest version for Ubuntu trusty).
Should I add server's certificate manually or there should be some general fix?

**Comment by dmurphy18** [comment]
Please try adding the repositories key manually.

wget -O -
https://repo.saltstack.com/apt/ubuntu/ubuntu14/SALTSTACK-GPG-KEY.pub |
apt-key add -

David Murphy
Unix Engineer
SaltStack

3400 North Ashton Blvd., Suite 110 | Lehi, UT 84043, USA

office 801-207-7440 | mobile 385-333-1060
dmurphy@saltstack.com |  www.saltstack.com
*SaltConf16 - Salt Lake City - April 19-21, 2016​ - www.saltconf.com
<http://www.saltconf.com/>​*

**Comment by yermulnik** [comment]
As I understood error it's not about repo key, but about server's SSL certificate:
```
Failed to fetch https://repo.saltstack.com/[...]  server certificate verification failed.
```
Or am I getting this wrong?

**Comment by jfindlay** [comment]
@richardhansen, we should also have a repo package at some point that installs an /etc/apt/sources.list.d/ file and the certificate, see #27120.

**Comment by jfindlay** [comment]
@yermulnik, that command should work.  What distro are you downloading the key onto?  We had some certificate problems with older distros a few weeks ago.  I don't remember many of the details but I can go searching through the issues.

**Comment by yermulnik** [comment]
@jfindlay , what command? `wget -O - ... | apt-key add -`? The thing is that using `http://` instead of `https://` do the job. Do you mean the problem is related to `GPG-key` and not to server's `SSL certificate`?

> What distro are you downloading the key onto?

trusty (Ubuntu 14.04.2)

**Comment by yermulnik** [comment]
Just in case tried to add repo key manually:
```shell
#> wget -O - https://repo.saltstack.com/apt/ubuntu/ubuntu14/SALTSTACK-GPG-KEY.pub | apt-key add -
--2015-09-29 08:06:21--  https://repo.saltstack.com/apt/ubuntu/ubuntu14/SALTSTACK-GPG-KEY.pub
Resolving repo.saltstack.com (repo.saltstack.com)... 198.199.77.106
Connecting to repo.saltstack.com (repo.saltstack.com)|198.199.77.106|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1744 (1.7K)
Saving to: 'STDOUT'

100%[==========================================================>] 1,744       --.-K/s   in 0s

2015-09-29 08:06:21 (268 MB/s) - written to stdout [1744/1744]

OK
```
SSL error hadn't gone:
```yaml
----------
          ID: salt-minion
    Function: pkg.latest
      Result: False
     Comment: An error was encountered while checking the newest available version of package(s): W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              E: Some index files failed to download. They have been ignored, or old ones used instead.
     Started: 08:06:33.260524
    Duration: 10998.553 ms
     Changes:
----------
```

**Comment by yermulnik** [comment]
Ok, lets move further: I've added `deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main` via `pkgrepo.managed`, but `pkg.latest` won't upgrade `salt-minion` =(
```yaml
#> apt-cache -q policy salt-minion
salt-minion:
  Installed: 2015.5.3+ds-1trusty1
  Candidate: 2015.8.0+ds-1
  Version table:
     2015.8.0+ds-1 0
        500 http://repo.saltstack.com/apt/ubuntu/ubuntu14/ trusty/main amd64 Packages
 *** 2015.5.3+ds-1trusty1 0
        500 http://ppa.launchpad.net/saltstack/salt/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.17.5+ds-1 0
        500 http://mirror.hetzner.de/ubuntu/packages/ trusty/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages

#> salt-call pkg.latest_version salt-minion
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/home/yz'
[INFO    ] Executing command 'apt-get -q update' in directory '/home/yz'
[INFO    ] Executing command ['apt-cache', '-q', 'policy', 'salt-minion'] in directory '/home/yz'
local:
    2015.8.0+ds-1

#> salt-call state.sls _update_pkg test=true
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://_update_pkg.sls'
[INFO    ] Running state [salt-minion] at time 09:23:06.452992
[INFO    ] Executing state pkg.latest for salt-minion
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/home/yz'
[INFO    ] Executing command 'apt-get -q update' in directory '/home/yz'
[INFO    ] Executing command ['apt-cache', '-q', 'policy', 'salt-minion'] in directory '/home/yz'
[INFO    ] Package salt-minion is already up-to-date.
[INFO    ] Completed state [salt-minion] at time 09:23:14.074907
[INFO    ] Running state [service.restart] at time 09:23:14.076699
[INFO    ] Executing state module.wait for service.restart
[INFO    ] No changes made for service.restart
[INFO    ] Completed state [service.restart] at time 09:23:14.077999
local:
----------
          ID: salt-minion
    Function: pkg.latest
      Result: True
     Comment: Package salt-minion is already up-to-date.
     Started: 09:23:06.452992
    Duration: 7621.915 ms
     Changes:
----------
          ID: salt-minion
    Function: module.wait
        Name: service.restart
      Result: True
     Comment:
     Started: 09:23:14.076699
    Duration: 1.3 ms
     Changes:

Summary
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
```

`_update_pkg.sls` contents:
```yaml
salt-minion:
  pkg.latest:
    - refresh: true
    - only_upgrade: true
  module.wait:
    - name: service.restart
    - m_name: salt-minion
    - watch:
      - pkg: salt-minion
```

I've found that it is possible to do the upgrade using builtin execution module `pkg.install` though.

**Comment by jfindlay** [comment]
@yermulnik, there were some issues with the certificate on saltstack.com with older distros.  I am able to successfully download https://repo.saltstack.com/apt/ubuntu/ubuntu14/SALTSTACK-GPG-KEY.pub on ubuntu 14.04.  I wonder if you might have an outdated certificate bundle or ssl library.

That is strange the `pkg.latest` is not the latest version.  Would you mind creating a new issue for the upgrade problem?  Thanks.

**Comment by yermulnik** [comment]
>  I am able to successfully download ...

Can you, please, try to manage repo via `pkgrepo.managed`?
```yaml
pkgrepo:
  pkgrepo.managed:
    - name: 'deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main'
    - file: /etc/apt/sources.list.d/saltstack.list
    - key_url: https://repo.saltstack.com/apt/ubuntu/ubuntu14/SALTSTACK-GPG-KEY.pub
```
> I wonder if you might have an outdated certificate bundle or ssl library.

As mentioned above in https://github.com/saltstack/salt/issues/27159#issuecomment-143709230 installed ca-certificates package version is 20141019ubuntu0.14.04.1 (latest version for Ubuntu trusty).
Below is what I get with `dpkg -l | fgrep -i ssl`:
```
    ii  libgnutls-openssl27:amd64           2.12.23-12ubuntu2.2                 amd64        GNU TLS library - OpenSSL wrapper
    ii  libssl1.0.0:amd64                   1.0.1f-1ubuntu2.15                  amd64        Secure Sockets Layer toolkit - shared libraries
    ii  openssl                             1.0.1f-1ubuntu2.15                  amd64        Secure Sockets Layer toolkit - cryptographic utility
    ii  python-m2crypto                     0.21.1-3ubuntu5                     amd64        a crypto and SSL toolkit for Python
    ii  ssl-cert                            1.0.33                              all          simple debconf wrapper for OpenSSL
```
Should I upgrade any of those packages?

>  Would you mind creating a new issue for the upgrade problem?

No problem: https://github.com/saltstack/salt/issues/27507 =)
