### ISSUE TITLE
pkgrepo.managed gpgkey argument doesn't work with http in openSUSE

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#27155]
Neither:
```
security:
  pkgrepo.managed:
  - url: http://download.opensuse.org/repositories/security/openSUSE_13.1/
  - gpgkey: http://download.opensuse.org/repositories/security/openSUSE_13.1/repodata/repomd.xml.key
```
nor
```
security:
  pkgrepo.managed:
  - url: http://download.opensuse.org/repositories/security/openSUSE_13.1/
  - key_url: http://download.opensuse.org/repositories/security/openSUSE_13.1/repodata/repomd.xml.key
```
work on openSUSE 13.1.

Zypper asks for importing gpg key after the first refresh, that's why `pkg.managed` doesn't work.
