### ISSUE TITLE
[2015.8.0] exporting variables

### ISSUE THREAD

**Issue by yermulnik** [saltstack/salt#27161]
Before the upgrade from 2015.5.5 to 2015.8.0 it was possible to export variables between `sls`'s like that:
`first.sls`:

``` jinja
{% set variable = 'value' %}
```

`second.sls`:

``` jinja
{% from 'first.sls' import variable with context %}
```

`third.sls`:

``` jinja
{% from 'second.sls' import variable with context %}
```

And `variable` was available in the `third.sls` with its value set in `first.sls`.
After the upgrade to 2015.8.0 this schema produces error:

```
    Rendering SLS 'base:third' failed: Jinja variable the template 'second.sls' (imported on line 1) does not export the requested name 'variable'
```

Is that a bug or a feature?

**Comment by basepi** [comment]
This is very strange, I can't think of anything we've changed in our jinja rendering between these releases. But as far as I know this should work, so we'll investigate.

**Comment by yermulnik** [comment]
Just an addition: full content of `third.sls` to test this issue should look like this:
```jinja
{% from 'second.sls' import variable with context %}

{% set newvar = variable %}

test:
  test.configurable_test_state:
    - comment: {{ newvar }}
    - changes: true
```

**Comment by oldskool** [comment]
I am also experiencing this issue on 2016.3.3. Did anybody happen to find a workaround for this?

**Comment by elxwill** [comment]
+1 also seeing this issue on 2016.11.1

Any update?

**Comment by boltronics** [comment]
What if, in `second.sls` you add the following line underneath the import statement:
`{% set variable = variable %}`
?
I don't think this is a Salt-specific issue, because I seem to be able to reproduce this Jinja2 error just by importing the jinja2 Python module directly (ie. not using Salt at all) and creating a similar setup to the original post. The above is what worked around the problem for me.

**Comment by EMGrant** [comment]
I ran into this issue today and it would appear I got around it by adding the state folder.   In OP's case:

    {% from '$State_Folder/first.sls' import variable with context %}

For context and clarity, I have two versions of Zabbix agent floating around for 2 flavors of Debian and Ubuntu.

My repo.sls filters by grain:

```# Zabbix is in ubuntu and debian-backports, but this is the official Zabbix repo
{% set distro_lookup = salt['grains.filter_by']({
    'Debian-7': {
        'pkgrepo': 'zabbix-repo',
        'distro': 'debian',
        'codename': grains['oscodename'],
    },
    'Debian-8': {
        'pkgrepo': 'zabbix-repo-xenial',
        'distro': 'debian',
        'codename': grains['oscodename'],
    },
    'Ubuntu-14.04': {
        'pkgrepo': 'zabbix-repo',
        'distro': 'ubuntu',
        'codename': grains['oscodename'],
    },
    'Ubuntu-16.04': {
        'pkgrepo': 'zabbix-repo-xenial',
        'distro': 'ubuntu',
        'codename': grains['oscodename'],
    },
}, grain='osfinger', merge=salt['pillar.get']('distro_lookup:lookup')) %}

{% if distro_lookup['pkgrepo'] == 'zabbix-repo' %}
zabbix-repo:
  pkgrepo.managed:
    - humanname: Zabbix
    - name: deb http://repo.zabbix.com/zabbix/2.2/{{ distro_lookup['distro'] }} {{ distro_lookup['codename'] }} main contrib non-free
    - dist: {{ distro_lookup['codename'] }}
    - file: /etc/apt/sources.list.d/zabbix.list
    - clean_file: true
    - keyid: D13D58E479EA5ED4
    - keyserver: pgpkeys.mit.edu
    - refresh_db: true

zabbix-repo-package:
  pkg.installed:
    - name: zabbix-release
    - require:
      - pkgrepo: zabbix-repo

{% else %}

zabbix-repo-xenial:
  pkgrepo.managed:
    - humanname: Zabbix Xenial
    - name: deb http://repo.zabbix.com/zabbix/3.0/{{ distro_lookup['distro'] }} {{ distro_lookup['codename'] }} main contrib non-free
    - dist: {{ distro_lookup['codename'] }}
    - file: /etc/apt/sources.list.d/zabbix.list
    - clean_file: true
    - keyid: 082AB56BA14FE591
    - keyserver: keyserver.ubuntu.com
    - refresh_db: true

zabbix-repo-package-xenial:
  pkg.installed:
    - name: zabbix-release
    - require:
      - pkgrepo: zabbix-repo-xenial

{% endif %}
```

    
If you're familiar with Zabbix, you can auto-register the the agent by configuring metadata, but how to do it is different between the Debian 7/Ubuntu 14.04 and Debian8/16.04 versions so I needed to import the distro_lookup variable from the repo.sls so I could filter which metadata state to run.

```
include:
  - zabbix.repo

{% from 'zabbix/repo.sls' import distro_lookup with context %}
zabbix-agent:
  pkg.installed:
    - name: zabbix-agent
  service.running:
    - name: zabbix-agent
    - watch:
      - file: /etc/zabbix/zabbix_agentd.conf

zabbix-agent-config-server:
  file.replace:
    - name: /etc/zabbix/zabbix_agentd.conf
    - pattern: ^Server=.*$
    - repl: Server={{ pillar['zabbix']['servers']|join(',') }}
    - append_if_not_found: True
    - require:
      - pkg: zabbix-agent
    - require_in:
      - service: zabbix-agent

zabbix-agent-config-serveractive:
  file.replace:
    - name: /etc/zabbix/zabbix_agentd.conf
    - pattern: ^ServerActive=.*$
    - repl: ServerActive={{ pillar['zabbix']['servers']|join(',') }}
    - append_if_not_found: True
    - require:
      - pkg: zabbix-agent
    - require_in:
      - service: zabbix-agent

zabbix-agent-config-hostname:
  file.replace:
    - name: /etc/zabbix/zabbix_agentd.conf
    - pattern: ^Hostname=.*$
    - repl: Hostname={{ grains['host'] }}
    - append_if_not_found: True
    - require:
      - pkg: zabbix-agent
    - require_in:
      - service: zabbix-agent

{% if distro_lookup['pkgrepo'] == 'zabbix-repo' %}

zabbix-agent-config-hostmetadata:
  file.replace:
    - name: /etc/zabbix/zabbix_agentd.d/hostmetadata.conf
    - pattern: ^# HostMetadata=.*$
    - repl: |
        HostMetadata={{ grains.get('kernel') }} {{ grains.get('os') }} {{ grains.get('oscodename') }} {{ grains.get('osrelease') }}
    - append_if_not_found: True
    - require:
      - pkg: zabbix-agent
    - require_in:
      - service: zabbix-agent

{% else %}

zabbix-agent-config-hostmetadata:
  file.replace:
    - name: /etc/zabbix/zabbix_agentd.conf
    - pattern: ^# HostMetadata=.*$
    - repl: |
        HostMetadata={{ grains.get('kernel') }} {{ grains.get('os') }} {{ grains.get('oscodename') }} {{ grains.get('osrelease') }}
    - require:
      - pkg: zabbix-agent
    - require_in:
      - service: zabbix-agent

{% endif %}
```
