### ISSUE TITLE
pkgrepo.absent does not work

### ISSUE THREAD

**Issue by pille** [saltstack/salt#27181]
on 2015.05 applying the pkgrepo.absent state shows no errors, but silently fails removing the file with the deb line on ubuntu.

```
----------
          ID: logentries-repo
    Function: pkgrepo.absent
        Name: deb http://rep.logentries.com/ precise main
      Result: True
     Comment: Removed package repo deb http://rep.logentries.com/ precise main
     Started: 07:09:34.239943
    Duration: 122.632 ms
     Changes:   
              ----------
              repo:
                  deb http://rep.logentries.com/ precise main
```

debug log isn't helpful, too:

```
[INFO    ] Running state [deb http://rep.logentries.com/ precise main] at time 07:18:45.521783
[INFO    ] Executing state pkgrepo.absent for deb http://rep.logentries.com/ precise main
[INFO    ] {'repo': 'deb http://rep.logentries.com/ precise main'}
[INFO    ] Completed state [deb http://rep.logentries.com/ precise main] at time 07:18:45.636724
```

i've just changed the whole state from pkgrepo.managed to pkgrepo.absent, so i'm sure there can't be any typo or missing data.

**Comment by jfindlay** [comment]
@pille, thanks for the report.

**Comment by PredatorVI** [comment]
I'm seeing something similar as well.  I am using 2016.3.3.

Minion sources file /etc/apt/sources.list.d/gocd.list:
```
deb https://download.go.cd /
deb http://download.go.cd/gocd-deb /
```


SLS directive:
```
'deb http://download.go.cd/gocd-deb /':
  pkgrepo.absent
```

Error:
```
----------
          ID: deb http://download.go.cd/gocd-deb /
    Function: pkgrepo.absent
      Result: False
     Comment: Repo deb http://download.go.cd/gocd-deb / doesn't exist in the sources.list(s)
     Started: 16:14:55.665334
    Duration: 113.954 ms
     Changes:
----------
```

**Comment by wolfpackmars2** [comment]
> Minion sources file /etc/apt/sources.list.d/gocd.list:
> deb https://download.go.cd /
> deb http://download.go.cd/gocd-deb /

From pkgrepo.py (func managed):
> One of ``baseurl`` or ``mirrorlist`` below is required. Additionally,
> note that this state is not presently capable of managing more than one
> repo in a single repo file, so each instance of this state will manage
> a single repo file containing the configuration for a single repo.

I don't see a similar comment for the absent state, but I wonder if this problem is related to the there being two repos referenced in the repo file.

**Comment by wolfpackmars2** [comment]
@pille Can you provide the relevant state/SLS you are using? Also, does the system have all the required packages, per the Note in docs. [https://docs.saltstack.com/en/2015.5/ref/states/all/salt.states.pkgrepo.html#management-of-apt-yum-package-repos](https://docs.saltstack.com/en/2015.5/ref/states/all/salt.states.pkgrepo.html#management-of-apt-yum-package-repos)

Mostly, it will be helpful to know how you've set up the state in order to assist troubleshooting this. Did you specify a "file" to store the repo?

**Comment by pille** [comment]
```
{% set ubuntu = grains['lsb_distrib_codename'] %}                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                       
logentries-repo:                                                                                                                                                                                                                                                                       
  pkgrepo.absent:                                                                                                                                                                                                                                                                      
    - humanname: Logentries Repo                                                                                                                                                                                                                                                       
    - name: deb http://rep.logentries.com/ {{ ubuntu }} main                                                                                                                                                                                                                           
    - dist: {{ ubuntu }}                                                                                                                                                                                                                                                               
    - file: /etc/apt/sources.list.d/logentries.list                                                                                                                                                                                                                                    
    - keyid: C43C79AD                                                                                                                                                                                                                                                                  
    - keyserver: pgp.mit.edu                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                       
logentries:                                                                                                                                                                                                                                                                            
  pkg:                                                                                                                                                                                                                                                                                 
    - purged                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                       
logentries-daemon:                                                                                                                                                                                                                                                                     
  pkg:                                                                                                                                                                                                                                                                                 
    - purged                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                       
/etc/le/config:                                                                                                                                                                                                                                                                        
  file.absent                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                       
/etc/le:                                                                                                                                                                                                                                                                               
  file.absent                                                                                                                                                                                                                                                                          
```

`python-software-properties`, `python-pycurl` and `python-apt` are installed.

**Comment by timwsuqld** [comment]
I believe we are hitting the same issue.

We had an issue with some mirrors, so wanted to change the mirrors we connected to. Updated our state to add the new mirrors and attempt to delete the old entires. We are using the "file" attribute to pkgrepo.managed, and have attempted to pass it to pkgrepo.absent with no result.

```
  pkgrepo.managed:
    - humanname: Ubuntu
    - name: deb http://mirror.overthewire.com.au/ubuntu/ {{ grains['oscodename'] }} restricted main multiverse universe
    - file: /etc/apt/sources.list.d/ubuntu.list

ubuntu-updates-repo:
  pkgrepo.managed:
    - humanname: Ubuntu Updates
    - name: deb http://mirror.overthewire.com.au/ubuntu/ {{ grains['oscodename'] }}-updates restricted main multiverse universe
    - file: /etc/apt/sources.list.d/ubuntu.list

ubuntu-backports-repo:
  pkgrepo.managed:
    - humanname: Ubuntu Backports
    - name: deb http://mirror.overthewire.com.au/ubuntu/ {{ grains['oscodename'] }}-backports restricted main multiverse universe
    - file: /etc/apt/sources.list.d/ubuntu.list

ubuntu-security-repo:
  pkgrepo.managed:
    - humanname: Ubuntu Backports
    - name: deb http://security.ubuntu.com/ubuntu/ {{ grains['oscodename'] }}-security restricted main multiverse universe
    - file: /etc/apt/sources.list.d/ubuntu.list

'deb http://au.archive.ubuntu.com/ubuntu/ {{ grains['oscodename'] }} restricted main multiverse universe':
  pkgrepo.absent:
    - file: /etc/apt/sources.list.d/ubuntu.list

'deb http://au.archive.ubuntu.com/ubuntu/ {{ grains['oscodename'] }}-updates restricted main multiverse universe':
  pkgrepo.absent:
    - file: /etc/apt/sources.list.d/ubuntu.list

'deb http://au.archive.ubuntu.com/ubuntu/ {{ grains['oscodename'] }}-backports restricted main multiverse universe':
  pkgrepo.absent:
    - file: /etc/apt/sources.list.d/ubuntu.list
```
After running this state, /etc/apt/sources.list.d/ubuntu.list is as follows
```
deb http://security.ubuntu.com/ubuntu xenial-security restricted main multiverse universe
deb http://au.archive.ubuntu.com/ubuntu xenial restricted main multiverse universe
deb http://au.archive.ubuntu.com/ubuntu xenial-updates restricted main multiverse universe
deb http://au.archive.ubuntu.com/ubuntu xenial-backports restricted main multiverse universe
deb http://mirror.overthewire.com.au/ubuntu xenial restricted main multiverse universe
deb http://mirror.overthewire.com.au/ubuntu xenial-updates restricted main multiverse universe
deb http://mirror.overthewire.com.au/ubuntu xenial-backports restricted main multiverse universe
```
Logs (and debug) from salt-call
```
[INFO    ] Running state [deb http://au.archive.ubuntu.com/ubuntu/ xenial restricted main multiverse universe] at time 09:38:51.321654
[INFO    ] Executing state pkgrepo.absent for deb http://au.archive.ubuntu.com/ubuntu/ xenial restricted main multiverse universe
[ERROR   ] Repo deb http://au.archive.ubuntu.com/ubuntu/ xenial restricted main multiverse universe doesn't exist in the sources.list(s)
[INFO    ] Completed state [deb http://au.archive.ubuntu.com/ubuntu/ xenial restricted main multiverse universe] at time 09:38:51.403297 duration_in_ms=81.643
[INFO    ] Running state [deb http://au.archive.ubuntu.com/ubuntu/ xenial-updates restricted main multiverse universe] at time 09:38:51.403591
[INFO    ] Executing state pkgrepo.absent for deb http://au.archive.ubuntu.com/ubuntu/ xenial-updates restricted main multiverse universe
[ERROR   ] Repo deb http://au.archive.ubuntu.com/ubuntu/ xenial-updates restricted main multiverse universe doesn't exist in the sources.list(s)
[INFO    ] Completed state [deb http://au.archive.ubuntu.com/ubuntu/ xenial-updates restricted main multiverse universe] at time 09:38:51.489108 duration_in_ms=85.516
[INFO    ] Running state [deb http://au.archive.ubuntu.com/ubuntu/ xenial-backports restricted main multiverse universe] at time 09:38:51.489356
[INFO    ] Executing state pkgrepo.absent for deb http://au.archive.ubuntu.com/ubuntu/ xenial-backports restricted main multiverse universe
[ERROR   ] Repo deb http://au.archive.ubuntu.com/ubuntu/ xenial-backports restricted main multiverse universe doesn't exist in the sources.list(s)
[INFO    ] Completed state [deb http://au.archive.ubuntu.com/ubuntu/ xenial-backports restricted main multiverse universe] at time 09:38:51.570439 duration_in_ms=81.082

local:
----------
          ID: deb http://au.archive.ubuntu.com/ubuntu/ xenial restricted main multiverse universe
    Function: pkgrepo.absent
      Result: False
     Comment: Repo deb http://au.archive.ubuntu.com/ubuntu/ xenial restricted main multiverse universe doesn't exist in the sources.list(s)
     Started: 09:38:51.321654
    Duration: 81.643 ms
     Changes:   
----------
          ID: deb http://au.archive.ubuntu.com/ubuntu/ xenial-updates restricted main multiverse universe
    Function: pkgrepo.absent
      Result: False
     Comment: Repo deb http://au.archive.ubuntu.com/ubuntu/ xenial-updates restricted main multiverse universe doesn't exist in the sources.list(s)
     Started: 09:38:51.403592
    Duration: 85.516 ms
     Changes:   
----------
          ID: deb http://au.archive.ubuntu.com/ubuntu/ xenial-backports restricted main multiverse universe
    Function: pkgrepo.absent
      Result: False
     Comment: Repo deb http://au.archive.ubuntu.com/ubuntu/ xenial-backports restricted main multiverse universe doesn't exist in the sources.list(s)
     Started: 09:38:51.489357
    Duration: 81.082 ms
     Changes:   

```

Salt version
```
salt-call --versions
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-77-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
