### ISSUE TITLE
[2015.8.0] regression with 'nodegroups' if minion is <2015.8.0

### ISSUE THREAD

**Issue by yermulnik** [saltstack/salt#27219]
I've got a bunch of Ubuntu servers, which still have SaltStack 2015.5.3, which is still the most latest version for Ubuntu (the solution is in progress: #27159 ) and a bunch of CentOS server, which still have SaltStack 2015.5.5 as the latest version. Since I had upgraded my salt-master (FreeBSD) to 2015.8.0 I see regression with `nodegroups` (minions with 2015.8.0 are Ok, only minions <2015.8.0 are affected).
My `etc/master`:
```yaml
nodegroups:
  freebsd: 'G@os:FreeBSD'
  ubuntu:  'G@os:Ubuntu'
  centos:  'G@os:CentOS'
```
Here's the output:
```bash
(jail) [root#jail_salt][w:9][j:1][.../salt/states]> salt -N freebsd grains.get saltversion
jail_salt:
    2015.8.0
(jail) [root#jail_salt][w:9][j:1][.../salt/states]> salt -N ubuntu grains.get saltversion
jail_ubuntu:
    Minion did not return. [No response]
(jail) [root#jail_salt][w:9][j:1][.../salt/states]> salt jail_ubuntu grains.get saltversion
jail_ubuntu:
    2015.5.3
(jail) [root#jail_salt][w:9][j:1][.../salt/states]> salt -G 'os:Ubuntu' grains.get saltversion
jail_ubuntu:
    2015.5.3
(jail) [root#jail_salt][w:9][j:1][.../salt/states]> salt -N centos grains.get saltversion
jail_centos:
    Minion did not return. [No response]
(jail) [root#jail_salt][w:9][j:1][.../salt/states]> salt jail_centos grains.get saltversion
jail_centos:
    2015.5.5
(jail) [root#jail_salt][w:9][j:1][.../salt/states]> salt -G 'os:Centos' grains.get saltversion
jail_centos:
    2015.5.5
```

**Comment by jfindlay** [comment]
@yermulnik, thanks for the report.

**Comment by mrwboilers** [comment]
First time reporting an issue, so not sure of protocol here. Just wanted to add that I'm seeing the same issue.

**Comment by rallytime** [comment]
Hi @yermulnik and @mrwboilers This is fixed in newer releases of the 2015.5 branch.

Here's the reproduction of the breakage on 2015.5.3:
```
root@rallytime:~# salt rallytime test.versions_report
rallytime:
               Salt: 2015.5.3
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
             Jinja2: 2.8
           M2Crypto: 0.21.1
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.5.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
            Tornado: 4.2.1
root@rallytime:~# salt -N ubuntu grains.get saltversion
rallytime:
    Minion did not return. [No response]
```
And here it is working on 2015.5.10:
```
root@rallytime:~# salt -N ubuntu grains.get saltversion
rallytime:
    2015.5.10
```
I'll close this, but if it pops up again, let us know. Thanks!
