### ISSUE TITLE
Feature request: Add a no-op state "dependencies" to make it easy to depend on a group of states

### ISSUE THREAD

**Issue by jdelic** [saltstack/salt#27227]
As a Salt user, in my salt repository I have many services which all have to depend on hashicorp/consul being installed, hasicorp/consul-template being set up as a systemd service, the consul-template templates being moved to the minion's file system etc.

So each of my service states has a dependency list that goes like this:
```yaml
examplestate:
    file.managed:
        [set up some stuff]
        - require:
            # the below requisites are the same in like 8 locations
            - file: consul-template-dir  # resides in /srv/salt/consul/template.sls
            - file: consul-template-servicerenderer # resides in /srv/salt/consul/helpers/smartstack.sls
            - file: haproxy-smartstack-template # resides in /srv/salt/haproxy/init.sls
            - service: consul-template  # resides in /srv/salt/consul/services.sls
``` 

I would like to move this boilerplate into *one state* that every other state which needs to set up a consul-template template can depend on.

Like this:
```yaml
consul-template-setup:
    dependencies.noop:
        - require:
            - file: consul-template-dir
            - file: consul-template-servicerenderer
            - file: haproxy-smartstack-template
            - service: consul-template

examplestate2:
    file.managed:
        [set up some stuff]
        - require:
            - dependencies: consul-template-setup
```

The current "work-around" is to move as many of the dependencies as possible into a single `.sls` file and then require the file using 
```yaml
        - require:
            - sls: consul-template-setup-state
```

But that will require throwing a lot of things together in one file that don't belong there.

Perhaps I'm just wrong and a solution for this problem already exists?
