### ISSUE TITLE
incorrect reporting in pkgrepo.managed state

### ISSUE THREAD

**Issue by skandyla** [saltstack/salt#27257]
I have the similar issue such as  https://github.com/saltstack/salt/issues/5517  but for centos linux.
Running `state.highstate test=True` or individual state execution reports changes 
(`Result: Differs`) when no changes are needed.

The issue appears when  `- comments` section is set in a state file.

state:

```
nginx-repo:                                                                        
  pkgrepo:                                                                           
    - managed                                                                        
    - name: nginx
    - humanname: Nginx.org Repository                                                  
    - baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    - gpgcheck: 0                                                                    
    - comments:                                                                      
      - 'priority=1'                                                                    
```

output of the first run:

```
# salt-ssh -i vbox_srv1c7 state.sls yumrepos.nginx 
vbox_srv1c7:
  Name: nginx - Function: pkgrepo.managed - Result: Changed

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1

```

output of the second run (with wrong behavior):

```
vbox_srv1c7:
  Name: nginx - Function: pkgrepo.managed - Result: Differs

Summary
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1

```

finally just to show that repo-file was deployed successfully :

```
# salt-ssh -i vbox_srv1c7 -r 'cat /etc/yum.repos.d/nginx.repo'
vbox_srv1c7:
    ----------
    retcode:
        0
    stderr:
    stdout:
        root@10.10.10.15's password: 

        [nginx]
        gpgcheck=0
        humanname=Nginx.org Repository
        baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
        name=Nginx.org Repository
        priority=1

```

The issue reproduces on all Salt versions, including latest:

```
# salt --versions-report
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.11.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core

```

**Comment by jfindlay** [comment]
@skandyla, thanks for the report.

**Comment by timwsuqld** [comment]
We are also experiencing this issue with Centos 6 machines.

```
salt --state-output=changes 'tweak' state.sls suqld.salt.repo test=True          
tweak:
----------
          ID: saltstack-rhel6
    Function: pkgrepo.managed
      Result: None
     Comment: Package repo 'saltstack-rhel6' will be configured. This may cause pkg states to behave differently than stated if this action is repeated without test=True, due to the differences in the configured repositories.
     Started: 15:22:11.770604
    Duration: 9.945 ms
     Changes:   
  Name: salt-minion - Function: pkg.installed - Result: Clean
  Name: salt-minion - Function: service.running - Result: Clean

Summary for tweak
------------
Succeeded: 3 (unchanged=1)
Failed:    0
------------
Total states run:     3
```
```
salt --state-output=changes 'tweak' state.sls suqld.salt.repo 
tweak:
  Name: saltstack-rhel6 - Function: pkgrepo.managed - Result: Clean
  Name: salt-minion - Function: pkg.installed - Result: Clean
  Name: salt-minion - Function: service.running - Result: Clean

Summary for tweak
------------
Succeeded: 3
Failed:    0
------------
Total states run:     3
```

Contents of state file

```
{% if grains['os_family'] == 'RedHat' %}
saltstack-rhel{{ grains['osmajorrelease'] }}:
  pkgrepo.managed:
    - humanname: SaltStack repo for RHEL/CentOS {{ grains['osmajorrelease'] }}
    - baseurl: https://repo.saltstack.com/yum/rhel{{ grains['osmajorrelease'] }}
    - gpgcheck: 1
    - gpgkey: https://repo.saltstack.com/yum/rhel{{ grains['osmajorrelease'] }}/SALTSTACK-GPG-KEY.pub
    - enabled: 1

# Install the salt-minion package we want

local_salt-minion:
  pkg.installed:
    - name: salt-minion
    - order: last
  service.running:
    - name: salt-minion
    - require:
      - pkg: salt-minion
{% endif %}    
```

Contents of repo file after deploy
```

[saltstack-rhel6]
name=SaltStack repo for RHEL/CentOS 6
gpgkey=https://repo.saltstack.com/yum/rhel6/SALTSTACK-GPG-KEY.pub
baseurl=https://repo.saltstack.com/yum/rhel6
humanname=SaltStack repo for RHEL/CentOS 6
gpgcheck=1
```

It makes it hard to use test=True to check if anything would be done.
We are not using comments sections in the repos.

I also notice that the timestamp is updated on the saltstack-rhel6.repo file on each application of the state, even if it reports nothing is done.
