### ISSUE TITLE
salt-master fails to communicate with salt-minion after upgrade to 2015.8.0 (until manual salt-minion restart)

### ISSUE THREAD

**Issue by yermulnik** [saltstack/salt#27267]
While upgrading my minions to 2015.8.0 via SaltStack I had encountered a problem that I have to manually restart minions because master fails to communicate with a newly upgraded minion:
```yaml
jail_centos:
----------
          ID: salt-minion
    Function: pkgrepo.managed
        Name: saltstack
      Result: True
     Comment: Configured package repo 'saltstack'
     Started: 10:05:07.325135
    Duration: 14.847 ms
     Changes:
              ----------
              repo:
                  saltstack
----------
          ID: salt-minion
    Function: pkg.latest
      Result: True
     Comment: The following packages were successfully installed/upgraded: salt-minion
     Started: 10:05:07.340079
    Duration: 17572.675 ms
     Changes:
              ----------
              python-futures:
                  ----------
                  new:
                      3.0.3-1.el7
                  old:
              python-tornado:
                  ----------
                  new:
                      4.2.1-1.el7
                  old:
              salt:
                  ----------
                  new:
                      2015.8.0-2.el7
                  old:
                      2015.5.5-1.el7
              salt-minion:
                  ----------
                  new:
                      2015.8.0-2.el7
                  old:
                      2015.5.5-1.el7
----------
          ID: salt-minion
    Function: service.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1561, in call
                  # If the state function accepts an 'env' keyword argument, it
                File "/usr/lib/python2.7/site-packages/salt/states/service.py", line 504, in mod_watch
                  if __salt__['service.status'](name, sig):
                File "/usr/lib/python2.7/site-packages/salt/modules/systemd.py", line 521, in status
                  if _untracked_custom_unit_found(name) or _unit_file_changed(name):
                File "/usr/lib/python2.7/site-packages/salt/modules/systemd.py", line 135, in _untracked_custom_unit_found
                  return name not in get_all() and os.access(unit_path, os.R_OK)
                File "/usr/lib/python2.7/site-packages/salt/modules/systemd.py", line 338, in get_all
                  + list(_get_all_legacy_init_scripts().keys())))
                File "/usr/lib/python2.7/site-packages/salt/modules/systemd.py", line 77, in _get_all_units
                  python_shell=True
                File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 1186, in run_stdout
                  use_vt=use_vt)
                File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 454, in _run
                  out = salt.utils.to_str(out).rstrip()
              AttributeError: 'module' object has no attribute 'to_str'
     Started: 10:05:25.831995
    Duration: 9.401 ms
     Changes:

Summary for jail_centos
------------
Succeeded: 2 (changed=2)
Failed:    1
------------
Total states run:     3
Total run time:  18.480 s
```
It's not very comfortable when one has a lot of minions =(
