### ISSUE TITLE
command line: pillar.get() cannot find reclass defined pillar

### ISSUE THREAD

**Issue by lrhazi** [saltstack/salt#27282]
I have a pillar named foo, defined in reclass node file... I can see it when I call items() : 

```
➜  ~  salt  "aaa-dev*"  pillar.items | grep -A3 foo
    foo:
        defined in node file
    groups:
        |_

```

but not when I call get() : 
```
➜  ~  salt  "aaa-dev*"  pillar.get foo                 
aaa-dev-1.uis.georgetown.edu:
➜  ~  
```

am running latest version of salt, and reclass:
```
➜  ~  salt --versions-report
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Apr  9 2015, 11:03:32)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: redhat 7.1 Maipo
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: Red Hat Enterprise Linux Server 7.1 Maipo
 
➜  ~  sudo pip install -U reclass
Requirement already up-to-date: reclass in /usr/lib/python2.7/site-packages/reclass-1.4.1-py2.7.egg
Requirement already up-to-date: pyyaml in /usr/lib64/python2.7/site-packages (from reclass)
➜  ~  
```

**Comment by jfindlay** [comment]
@lrhazi, thanks for the report.  I am able to reproduce this.

### versions
```yaml
salt jmoney-debian test.versions
jmoney-debian:
    Salt Version:
               Salt: 2015.8.0-24-gb71de75

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed

    System Versions:
               dist: debian 8.1
            machine: x86_64
            release: 3.16.0-4-amd64
             system: debian 8.1
```

### configs
```saltstack
# cat /srv/pillar/top.sls
base:
  '*':
    - test
```
```saltstack
# cat /srv/pillar/test.sls
foo:
    defined in node file
```

### commands
```console
# salt jmoney-debian pillar.items
jmoney-debian:
    ----------
    foo:
        defined in node file
```
```console
# salt jmoney-debian pillar.get foo
jmoney-debian:
```

**Comment by lrhazi** [comment]
Thanks! What's interesting is that pillar.get() from a Jinja file, managed from a state, finds the pillar correctly!

```
#!stateconf yaml . jinja
/tmp/test.out:
  file.managed:
    - source:
        - salt://{{sls_dir}}/files/test.out
    - template: jinja
```

and then in test.out:
```
{{ salt['pillar.get']('foo') }}
```
