### ISSUE TITLE
ZMQ and latency issue?

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#27339]
we have about 13000 minions, and while performing regression testing from a master of master, i noticed high lagging in the event arriving to syndics residing other DC from master of master. As a result, the minions registered to that syndics also receives the event late.  I dont see any latency issue to the syndics in the same DC as master of master, is this caused by ZMQ or salt itself? 

``` yaml
           Salt: 2015.5.0
         Python: 2.7.10 (default, Jun  3 2015, 16:19:05)
         Jinja2: 2.8
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.2
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 2.2
```
