### ISSUE TITLE
boto_route53 state doesn't create a record

### ISSUE THREAD

**Issue by mool** [saltstack/salt#27374]
I have a state to create a DNS record for a minion
```saltstack
dns-record:
  boto_route53.present:
    - name: {{ grains['id'] }}.example.com.
    - value: {{ grains['ip4_interfaces']['eth0'][0] }}
    - zone: example.com.
    - ttl: 60
    - record_type: A
    - region: us-east-1
    - keyid: {{pillar['route53']['keyid']}}
    - key: {{pillar['route53']['key']}}
```

When I run the state, i don't get any error but it doesn't make any changes and the record isn't created.
```yaml
----------
          ID: dns-record
    Function: boto_route53.present
        Name: minion.example.com.
      Result: True
     Comment:
     Started: 17:38:39.910178
    Duration: 0.714 ms
     Changes:
```

I have tried with different IAM permissions and using IAM instance roles, but always is the same.

````
salt-minion --version
salt-minion 2015.5.3 (Lithium)
```
