### ISSUE TITLE
2015.8.0 Pillar lists that are assigned twice in top.sls merged/duplicated

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#27378]
This problem just started just after upgrading the salt-master to 2015.8.0.  Here's what happens.

pillar top.sls
```saltstack
base:
  'roles:teamcity':
    - match: grain
    - example
  'kernel:Linux':
    - match: grain
    - example
```
pillar example.sls
```saltstack
example-list:
  - one
  - two
  - three
```

A minion with kernel:Linux and roles:teamcity will see:
```saltstack
example-list:
  - one
  - one
  - two
  - two
  - three
  - three
```

```yaml
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.3.1
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 3.14.44-32.39.amzn1.x86_64
```
