### ISSUE TITLE
Make VMware driver more consistent with other cloud providers

### ISSUE THREAD

**Issue by alxbse** [saltstack/salt#27381]
A continuation of the discussion in #27324 between me and @nmadhok. Since adding support for creating VMs rather than cloning, the `clonefrom` key is no longer required and as @nmadhok suggested `image` should be required instead.

Since the VMware driver really doesn't work like other cloud providers where `image` refers to a prepared disk image, the `image` key in the VMware driver would map to the guestId value in the VMware API.

A minimal VMware profile would look something like this:

```
my-minimal-profile:
  provider: my-vmware-provider
  # Either specify image in short form...
  image: debian8_64Guest
  # ... or image full name
  image: 'Debian GNU/Linux 8 (64 bit)' 
  clonefrom: my-template
```

Having `image` behave this way would have the positive side effect of making it very clear what OS the new VM will have.

The function `avail_images` in the driver currently lists available templates but this would be modified to return a list of valid images instead, such as:

```
vmware_provider:
-----------------------
  images:
  ----------
    debian8_64Guest:
    -----------------------
      Debian GNU/Linux 8 (64 bit)
    windows7Server64Guest:
    --------------------------------
      Windows Server 2008 R2 (64 bit)
```

This would be the behaviour you meant @nmadhok, right?
