### ISSUE TITLE
Regression in file.managed with source_hash

### ISSUE THREAD

**Issue by mafrosis** [saltstack/salt#27397]
Test case:

```
s3proxy-install:
  file.managed:
    - name: /usr/local/bin/s3proxy
    - source: https://github.com/andrewgaul/s3proxy/releases/download/s3proxy-1.3.0/s3proxy
    - source_hash: sha1=805acf21aa9185e2539f6041ebe24b877f5b4284
```

In `2015.5.5`:

```
[INFO    ] Running state [/usr/local/bin/s3proxy] at time 09:06:11.482699
[INFO    ] Executing state file.managed for /usr/local/bin/s3proxy
[INFO    ] File changed:
New file
[INFO    ] Completed state [/usr/local/bin/s3proxy] at time 09:06:39.897139
local:
----------
          ID: s3proxy-install
    Function: file.managed
        Name: /usr/local/bin/s3proxy
      Result: True
     Comment: File /usr/local/bin/s3proxy updated
     Started: 09:06:11.482699
    Duration: 28414.44 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

In `2015.8.0`:

```
[INFO    ] Running state [/usr/local/bin/s3proxy] at time 09:06:11.482699
[INFO    ] Executing state file.managed for /usr/local/bin/s3proxy
[INFO    ] File changed:
New file
[INFO    ] Completed state [/usr/local/bin/s3proxy] at time 09:06:39.897139
local:
----------
          ID: s3proxy-install
    Function: file.managed
        Name: /usr/local/bin/s3proxy
      Result: False
     Comment: File sum set for file /usr/local/bin/s3proxy of 805acf21aa9185e2539f6041ebe24b877f5b4284 does not match real sum of e76791fc075adf7fd5dfd4a084ef1ccbe8f0fc6a
     Started: 09:20:34.400395
    Duration: 25107.115 ms
     Changes:
              ----------
              diff:
                  New file

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  25.107 s
```
