### ISSUE TITLE
pkg.uptodate should be stateful

### ISSUE THREAD

**Issue by scottleibrand** [saltstack/salt#27414]
Per https://groups.google.com/d/msg/salt-users/RhSjWJYMOOo/33L4TgzLAgAJ, running pkg.uptodate is not stateful (it returns blue output even when nothing is actually upgraded), but it should be comparing before and after state and only reporting changes if something changed.  For example:

```
      Result: True
     Comment: Upgrade successful.
     Changes:
              ----------
              changes:
                  ----------
              comment:
              result:
                  True
```

**Comment by jfindlay** [comment]
@scottleibrand, thanks for the report.

**Comment by eliasp** [comment]
I can confirm this on Ubuntu 14.04, Salt 2015.8.0:
```
          ID: system-updates
    Function: pkg.uptodate
      Result: True
     Comment: Upgrade successful.
     Started: 15:05:27.542816
    Duration: 13095.349 ms
     Changes:   
              ----------
              changes:
                  ----------
              comment:
              result:
                  True
```
```
    Salt Version:
               Salt: 2015.8.0
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: 0.9.1
             PyYAML: 3.10
              PyZMQ: 14.4.0
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-55-generic
             system: Ubuntu 14.04 trusty
```
