### ISSUE TITLE
winrepo - drops "trailing zeroes" from version numbers on un-install?

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#27433]
This is pretty new regression, this used to work, i think. The version number is '5.10' on on install it does get recognized as such, but on un-install it tries un-installing '5.1 instead, which is not installed and version '5.10' stays on the computer.

```
C:\salt>salt-call pkg.install ccleaner
[INFO    ] Executing command ['c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\
base\\download.piriform.com\\ccsetup510.exe', '/S'] in directory 'c:\\salt\\var\
\cache\\salt\\minion\\extrn_files\\base\\download.piriform.com'
local:
    ----------
    ccleaner:
        ----------
        new:
            5.10
        old:
```
```
C:\salt>salt-call pkg.remove ccleaner
[ERROR   ] ccleaner None not installed
local:
    ----------
    ccleaner:
        ----------
        current:
            5.1 not installed
```

**Comment by jfindlay** [comment]
@TheBigBear, thanks for the report.  What version of salt are you using?

**Comment by TheBigBear** [comment]
@jfindlay the latest released windows minion 2015.8-3 and the latest released salt master 2015.8.0 on centos 7

```
C:\salt>salt-call --versions
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD6
4)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 7
         system: 7 6.1.7601 SP1 Multiprocessor Free
```

**Comment by terminalmage** [comment]
@TheBigBear Can you post the corresponding winrepo SLS?

**Comment by TheBigBear** [comment]
@terminalmage, sure, I am using the 'official' one hosted on the saltstack winrepo-ng. 

```
# just 32-bit x86 installer available
{% if grains['cpuarch'] == 'AMD64' %}
    {% set PROGRAM_FILES = "%ProgramFiles(x86)%" %}
{% else %}
    {% set PROGRAM_FILES = "%ProgramFiles%" %}
{% endif %}
ccleaner:
  5.10:
    full_name: 'CCleaner'
    installer: 'http://download.piriform.com/ccsetup510.exe'
    install_flags: '/S'
    uninstaller: '{{ PROGRAM_FILES }}\CCleaner\uninst.exe'
    uninstall_flags: '/S'
    msiexec: False
    locale: en_US
    reboot: False
  5.0.9:
    full_name: 'CCleaner 5.09'
    installer: 'http://download.piriform.com/ccsetup509.exe'
    install_flags: '/S'
    uninstaller: '{{ PROGRAM_FILES }}\CCleaner\uninst.exe'
    uninstall_flags: '/S'
    msiexec: False
    locale: en_US
    reboot: False
```
