### ISSUE TITLE
file.recurse exclude_pat improvements (accept a list)

### ISSUE THREAD

**Issue by josmardias** [saltstack/salt#2747]
I tried to use exclude_pat but it seems not working for folders, only files. 
I think it will be very useful if we can ignore a subtree by matching a folder.
And i believe that exclude_pat can be an array, so we can match more than one file by glob.

So...

``` yaml
/home/josmar/tree:
  file.recurse:
    - source: salt://test/tree
    - include_empty: True
    - clean: True
    # not sure if this regex is right, but my intention here is 
    # to match all files inside these folders.
    - exclude_pat: 'E@(^excluded/*)|(^holder/excluded/*)'
    - user: josmar
    - group: josmar
    - dir_mode: 550
    - file_mode: 440


/home/josmar/tree/holder/excluded/managed:
  file.managed:
    - user: josmar
    - group: josmar
    - require:
      - file: /home/josmar/tree
```

Can be improved like:

``` yaml

/home/josmar/tree:
  file.recurse:
    - source: salt://test/tree
    - include_empty: True
    - clean: True
    - exclude_pat:
      - excluded
      - holder/excluded
    - user: josmar
    - group: josmar
    - dir_mode: 550
    - file_mode: 440
```

And the whole "/home/josmar/tree/excluded" folder will be ignored by recurse. No copying and no cleaning.

**Comment by markuskramerIgitt** [comment]
@basepi as you gave the advise to use the exclude_pat: ``` "*.svn*" ``` in 2013, should it not work in Salt 2014.1.13 (Windows) and  Salt 2014.7.0 (Debian)?

Unfortunately, this expression copies all ``` .svn  ``` folders:
```
/localdir:
  file.recurse:
    - clean: True
    - source: salt://remotedir
    - exclude_pat: "*.svn*"
 ```
