### ISSUE TITLE
"SSL certificate is invalid" despite gitfs_ssl_verify = False

### ISSUE THREAD

**Issue by silenius** [saltstack/salt#27495]
Hello,

I'm trying to setup gitfs with pygit2 provider with the following:

```
gitfs_provider: pygit2
gitfs_remotes:
    - https://xxx/git/bbpf/automation.git:
        - user: git
        - password: somepassword
        - root: salt
gitfs_ssl_verify: False
```

However it constantly fail with:

```
2015-09-29 11:44:24,369 [salt.utils.gitfs][ERROR ][76533] Exception 'The SSL certificate is invalid' caught while fetching gitfs remote 'https://xxx/git/bbpf/automation.git'
```

A quick-and-dirty grep seems to indicate that the "gitfs_ssl_verify" isn't used anywhere:

``` bash
jcigar@dev:/usr/local/lib/python2.7/site-packages/salt/ > grep -ri 'gitfs_ssl_verify' *
config.py:    'gitfs_ssl_verify': bool,
config.py:    'gitfs_ssl_verify': False,
config.py:    'gitfs_ssl_verify': False,
Binary file config.pyc matches
pillar/git_pillar.py:                    if self.opts.get('pillar_gitfs_ssl_verify', True):
Binary file pillar/git_pillar.pyc matches
jcigar@dev:/usr/local/lib/python2.7/site-packages/salt/ >
```

Maybe the problem is in init_repo() function of salt/utils.py for the Pygit2 class ...

**Comment by jfindlay** [comment]
@silenius, thanks for the report.  What version of salt are you using?

**Comment by silenius** [comment]
Here it is :) :

```
jcigar@dev:~/ > salt --versions-report
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Jul 26 2015, 11:57:29)
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.1.3
           cffi: 1.1.1
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.2.4
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.23.0
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: amd64
        release: 10.1-RELEASE-p3
```

I wonder if the problem is not in pygit2 (or one of its dependencies...), the thing is that a simple $> git clone ... with:
```
[http]
	sslverify = false
```
in my ~/.gitconfig works.
