### ISSUE TITLE
salt-ssh 2015.5.3: JSON Render failed for cmd.run

### ISSUE THREAD

**Issue by haarp** [saltstack/salt#27492]
I have the following in a state file:

```
/usr/share/tomcat7/.keystore:
 cmd.run:
    - name: 'echo -e "\n\n\n\n\n\ny\n\n" | /usr/lib/jvm/java-8-oracle-amd64/bin/keytool -genkey -alias tomcat -keyalg RSA -validity 3650 -keystore /usr/share/tomcat7/.keystore -storepass foo'
    - require:
      - pkg: tomcat7
    - unless:
      - '[ -e /usr/share/tomcat7/.keystore ]'
```

When the unless condition succeeds, this is skipped with no problem. When the unless condition fails, the command is successfully run, but salt-ssh returns with only an error:

```
$ salt-ssh 'foo' state.highstate
[ERROR   ] JSON Render failed for: 
Permission denied, no authentication information
[ERROR   ] No JSON object could be decoded
foo:
```

I am using sudo: True to become root, in case that's relevant.
