### ISSUE TITLE
pkgrepo.managed fails if repo address uses https

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#27511]
### version
```yaml
# salt-ssh --version
salt-ssh 2015.8.0-24-gb71de75 (Beryllium)
```
### configs
```saltstack
# cat /srv/salt/repo.sls
pkgrepo:
  pkgrepo.managed:
    - name: 'deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main'
    - file: /etc/apt/sources.list.d/saltstack.list
    - key_url: https://repo.saltstack.com/apt/ubuntu/ubuntu14/SALTSTACK-GPG-KEY.pub
```
### commands
```yaml
# salt-ssh jmoney-ubuntu-14 state.apply repo
jmoney-ubuntu-14:
----------
          ID: pkgrepo
    Function: pkgrepo.managed
        Name: deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main
      Result: False
     Comment: Failed to configure repo 'deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main': W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              E: Some index files failed to download. They have been ignored, or old ones used instead.
     Started: 12:24:15.642031
    Duration: 12693.366 ms
     Changes:

Summary for jmoney-ubuntu-14
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  12.693 s
```
But the repo is there:
```console
# salt-ssh jmoney-ubuntu-14 cmd.run 'cat /etc/apt/sources.list.d/salt*'
jmoney-ubuntu-14:
    deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main
    deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main
```
And the key is not:
```console
# time salt-ssh jmoney-ubuntu-14 cmd.run 'apt-key list'
jmoney-ubuntu-14:
    /etc/apt/trusted.gpg
    --------------------
    pub   1024D/437D05B5 2004-09-12
    uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
    sub   2048g/79164387 2004-09-12

    pub   1024D/FBB75451 2004-12-30
    uid                  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>

    pub   4096R/C0B21F32 2012-05-11
    uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

    pub   4096R/EFE21092 2012-05-11
    uid                  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>
```
If I change the URL for the GPG key in the state file to `http` rather than `https`, the state succeeds: both repo list file and key are installed.
```yaml
# salt-ssh jmoney-ubuntu-14 state.apply repo
jmoney-ubuntu-14:
----------
          ID: pkgrepo
    Function: pkgrepo.managed
        Name: deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main
      Result: True
     Comment: Configured package repo 'deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main'
     Started: 12:34:43.047251
    Duration: 10710.105 ms
     Changes:
              ----------
              repo:
                  deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main

Summary for jmoney-ubuntu-14
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  10.710 s
```

**Comment by yermulnik** [comment]
There's a misspelling in issue description: `pkgrepo.managed` **fails only if repo address uses** `https`. Here's `sls`:
```yaml
pkgrepo:
  pkgrepo.managed:
    - name: 'deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main'
    - file: /etc/apt/sources.list.d/saltstack.list
    - key_url: https://repo.saltstack.com/apt/ubuntu/ubuntu14/SALTSTACK-GPG-KEY.pub
```
If I change repo `name` to plain `http` (`- name: 'deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main'`) `pkgrepo.managed` do the job without errors. No matter if `key_url` uses `http` or `https`.
And error seems to be related to server's `SSL` cetificate:
```
     Comment: Failed to configure repo 'deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main': W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

**Comment by jfindlay** [comment]
@yermulnik, when I ran the state with an https in the repo URL, I got:
```
# cat /etc/apt/sources.list.d/salt.list
deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main
deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main
```
I don't remember if it errored though.

**Comment by yermulnik** [comment]
`https` both in `name` and `key_url`:
```yaml
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> cat _yz_test.sls
pkgrepo:
  pkgrepo.managed:
    - name: 'deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main'
    - file: /etc/apt/sources.list.d/saltstack.list
    - key_url: https://repo.saltstack.com/apt/ubuntu/ubuntu14/SALTSTACK-GPG-KEY.pub
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt dt-grafana state.sls _yz_test
dt-grafana:
----------
          ID: pkgrepo
    Function: pkgrepo.managed
        Name: deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main
      Result: False
     Comment: Failed to configure repo 'deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main': W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              E: Some index files failed to download. They have been ignored, or old ones used instead.
     Started: 07:16:12.070611
    Duration: 36598.096 ms
     Changes:

Summary for dt-grafana
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  36.598 s
ERROR: Minions returned with non-zero exit code
```
`http` in `name` and `https` in `key_url`:
```yaml
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> cat _yz_test.sls
pkgrepo:
  pkgrepo.managed:
    - name: 'deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main'
    - file: /etc/apt/sources.list.d/saltstack.list
    - key_url: https://repo.saltstack.com/apt/ubuntu/ubuntu14/SALTSTACK-GPG-KEY.pub
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt dt-grafana state.sls _yz_test
dt-grafana:
----------
          ID: pkgrepo
    Function: pkgrepo.managed
        Name: deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main
      Result: False
     Comment: Failed to configure repo 'deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main': W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              E: Some index files failed to download. They have been ignored, or old ones used instead.
     Started: 07:18:56.678938
    Duration: 33317.463 ms
     Changes:

Summary for dt-grafana
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  33.317 s
ERROR: Minions returned with non-zero exit code
```
`http` both in `name` and `key_url`:
```yaml
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> cat _yz_test.sls
pkgrepo:
  pkgrepo.managed:
    - name: 'deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main'
    - file: /etc/apt/sources.list.d/saltstack.list
    - key_url: http://repo.saltstack.com/apt/ubuntu/ubuntu14/SALTSTACK-GPG-KEY.pub
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt dt-grafana state.sls _yz_test
dt-grafana:
----------
          ID: pkgrepo
    Function: pkgrepo.managed
        Name: deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main
      Result: True
     Comment: Configured package repo 'deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main'
     Started: 07:22:54.693876
    Duration: 5362.958 ms
     Changes:
              ----------
              repo:
                  deb http://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main

Summary for dt-grafana
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   5.363 s
```
In the `first` and `second` examples, when sates failed, file `/etc/apt/sources.list.d/saltstack.list` had been created and had exactly the same content as in `name` arg of corresponding `sls`. But states **failed**.

**Comment by ryanwalder** [comment]
Does it work if you install `apt-transport-https` before adding the repo? We've been using https for our own apt mirror with no issues for about 3 major salt versions.

**Comment by yermulnik** [comment]
Nope =(
```yaml
pkgrepo:
  pkg.installed:
    - name: apt-transport-https
  pkgrepo.managed:
    - name: 'deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main'
    - file: /etc/apt/sources.list.d/saltstack.list
    - key_url: https://repo.saltstack.com/apt/ubuntu/ubuntu14/SALTSTACK-GPG-KEY.pub
```
```yaml
dt-grafana:
  Name: apt-transport-https - Function: pkg.installed - Result: Clean
----------
          ID: pkgrepo
    Function: pkgrepo.managed
        Name: deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main
      Result: False
     Comment: Failed to configure repo 'deb https://repo.saltstack.com/apt/ubuntu/ubuntu14 trusty main': W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              W: Failed to fetch https://repo.saltstack.com/apt/ubuntu/ubuntu14/dists/trusty/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

              E: Some index files failed to download. They have been ignored, or old ones used instead.
     Started: 10:24:33.643443
    Duration: 8362.138 ms
     Changes:

Summary for dt-grafana
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:   8.801 s
```
```yaml
dt-grafana:
    apt-transport-https:
      Installed: 1.0.1ubuntu2.10
      Candidate: 1.0.1ubuntu2.10
[...]
```
