### ISSUE TITLE
salt-cloud: Could not associate elastic ip address <None> with network interface <eni-xxxxxxxx>

### ISSUE THREAD

**Issue by jgill** [saltstack/salt#27574]
This error occurs when creating a VM with `AssociatePublicIpAddress: true` once you have exhausted  the number of VPC Elastic IPs you can allocate within a region.

Pull request #25315 which was incorporated in version 2015.8.0 changes the semantics of `AssociatePublicIpAddress` in a manner that I believe is incorrect. `AssociatePublicIpAddress` is now equivalent to associating an EIP to a network interface which according to salt-cloud documentation is incorrect:

```
base_ec2_vpc:
  provider: my-ec2-southeast-public-ips
  image: ami-a73264ce
  size: m1.xlarge
  ssh_username: ec2-user
  script:  /etc/salt/cloud.deploy.d/user_data.sh
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      #auto assign public ip (not EIP)
      AssociatePublicIpAddress: True
      SubnetId: subnet-813d4bbf
      SecurityGroupId:
        - sg-750af413
```

There are obviously many use cases where one would like to auto-assign a public IP and not use an EIP which probably means that this change should be reverted.
