### ISSUE TITLE
Salt minion needs to restart after install SSSD to get valid users

### ISSUE THREAD

**Issue by timwsuqld** [saltstack/salt#27586]
As can be seen, others also have this issue. http://grokbase.com/t/gg/salt-users/152hfx8bjm/sssd-and-ssh-keys

The salt-minion caches the users on the system at startup. `salt '*' user.list_users` shows only the local users.
After installing SSSD, `getent passwd` shows all the SSSD users (enumerate = True is set), however  `salt '*' user.list_users` still only shows the local users.
After restarting salt-minion `salt '*' user.list_users` now shows all the users.

Any state that tries to use a username that only comes from SSSD will fail until the salt-minion is restarted.

For example, the following fails until salt-minion is restarted:

```
timw_laptop:
  ssh_auth.present:
    - user: timw
    - source: salt://ssh_auth/timw.id_rsa.pub
```

Ideally there should be a way to force the salt-minion to reload it's users list, ideally as part of the state that sets up SSSD.
