### ISSUE TITLE
Templated files included from states do not render correctly from salt-ssh.

### ISSUE THREAD

**Issue by pirogoeth** [saltstack/salt#27587]
When running a state that includes a managed file (and `map.jinja` in the state module), attempting to import the `map.jinja` from the managed file fails. Untemplated files work, though.

Example:
```
→ root@epsilon | /usr/home/pirogoeth/maiome-saltstates
λ salt-ssh 'ct5001.infra.ramcloud.io' state.apply nginx saltenv=prod

ct5001.infra.ramcloud.io:
       pkg.latest     Clean     Name: nginx
   service.running    Clean     Name: nginx
      file.directory  Changed   Name: /etc/nginx
      file.managed    Clean     Name: /etc/nginx/proxy_params
----------
          ID: /etc/nginx/nginx.conf
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja error: nginx/map.jinja
              Traceback (most recent call last):
                File "/tmp/.root_4f7b34_salt/salt/utils/templates.py", line 368, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/tmp/.root_4f7b34_salt/jinja2/environment.py", line 969, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/tmp/.root_4f7b34_salt/jinja2/environment.py", line 742, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 1, in top-level template code
                File "/tmp/.root_4f7b34_salt/salt/utils/jinja.py", line 144, in get_source
                  raise TemplateNotFound(template)
              TemplateNotFound: nginx/map.jinja

              ; line 1

              ---
              {% from "nginx/map.jinja" import nginx with context %}    <======================
              user {{ nginx.www_user }};
              worker_processes  auto;

              error_log  /var/log/nginx/error.log;

              [...]
              ---
     Started: 22:21:29.792415
    Duration: 15.386 ms
     Changes:
      file.directory  Clean     Name: /etc/nginx/conf.d
      file.directory  Clean     Name: /var/log/nginx
      file.directory  Clean     Name: /etc/nginx/sites.d
      file.directory  Clean     Name: /var/nginx
      file.managed    Changed   Name: /etc/nginx/conf.d/ssl.conf
      file.managed    Changed   Name: /etc/nginx/conf.d/proxy.conf
```

`nginx/init.sls`:
```
### nginx:init.sls ###

{% from "nginx/map.jinja" import nginx with context %}

nginx:
  pkg.latest:
    - name: {{ nginx.package }}
    - refresh: True
  service.running:
    - name: nginx
    - enable: True
    - watch:
      - pkg: nginx

{{ nginx.base_d }}:
  file.directory:
    - user: {{ nginx.www_user }}
    - group: {{ nginx.www_group }}
    - dir_mode: 744
    - file_mode: 740
    - recurse:
      - user
      - group
      - mode
    - requires:
      - pkg: nginx

{{ nginx.base_d }}/proxy_params:
  file.managed:
    - source: salt://etc/nginx/proxy_params
    - mode: 740
    - user: {{ nginx.www_user }}
    - group: {{ nginx.www_group }}
    - clean: False
    - requires:
      - file: {{ nginx.base_d }}

{{ nginx.config_path }}:
  file.managed:
    - source: salt://etc/nginx/nginx.conf
    - mode: 740
    - user: {{ nginx.www_user }}
    - group: {{ nginx.www_group }}
    - backup: minion
    - template: jinja
    - requires:
      - file: {{ nginx.base_d }}

{{ nginx.conf_d }}:
  file.directory:
    - user: {{ nginx.www_user }}
    - group: {{ nginx.www_group }}
    - dir_mode: 744
    - file_mode: 740
    - clean: False
    - recurse:
      - user
      - group
      - mode
    - requires:
      - file: {{ nginx.config_path }}

{{ nginx.log_d }}:
  file.directory:
    - user: {{ nginx.www_user }}
    - group: {{ nginx.www_group }}
    - dir_mode: 740
    - file_mode: 740
    - recurse:
      - user
      - group
      - mode

{{ nginx.sites_d }}:
  file.directory:
    - user: {{ nginx.www_user }}
    - group: {{ nginx.www_group }}
    - dir_mode: 744
    - file_mode: 740
    - clean: False
    - recurse:
      - user
      - group
      - mode
    - requires:
      - file: {{ nginx.config_path }}

{{ nginx.var_d }}:
  file.directory:
    - user: {{ nginx.www_user }}
    - group: {{ nginx.www_group }}
    - dir_mode: 744
    - file_mode: 740
    - recurse:
      - user
      - group
      - mode

{{ nginx.conf_d }}/ssl.conf:
  file.managed:
    - source: salt://etc/nginx/conf.d/ssl.conf
    - mode: 740
    - user: root
    - group: {{ nginx.www_user }}
    - template: jinja
    - requires:
      - file: {{ nginx.config_path }}

{{ nginx.conf_d }}/proxy.conf:
  file.managed:
    - source: salt://etc/nginx/conf.d/proxy.conf
    - mode: 740
    - user: root
    - group: {{ nginx.www_user }}
    - template: jinja
    - requires:
      - file: {{ nginx.config_path }}
```

`nginx.conf`:
```
{% from "nginx/map.jinja" import nginx with context %}
user {{ nginx.www_user }};
worker_processes  auto;

error_log  /var/log/nginx/error.log;

events {
    worker_connections  4096;
    multi_accept on;
}

http {
    ##
    # DEFAULT TYPES
    ##

    include       mime.types;
    default_type  application/octet-stream;

    ##
    # LOGGING OPTIONS
    ##

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    log_format  grokable '$http_host '
                '$remote_addr [$time_local] '
                '"$request" $status $body_bytes_sent '
                '"$http_referer" "$http_user_agent" '
                '$request_time '
                '$upstream_response_time';

    access_log  /var/log/nginx/access.log  grokable;

    ##
    # CONNECTION SETTINGS
    ##

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;

    keepalive_timeout  65;

    ##
    # GZIP SETTINGS
    ##

    gzip  on;
    gzip_disable "msie6";

    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    ##
    # INCLUDES
    ##

    include {{ nginx.conf_d }}/*.conf;
    include {{ nginx.sites_d }}/*.conf;
}
```

`nginx/map.jinja`:
```
### nginx:map.jinja ###

{% set nginx = salt['grains.filter_by']({
    'default' : {
        'package' : 'nginx',
        'base_d' : '/etc/nginx',
        'config_path' : '/etc/nginx/nginx.conf',
        'conf_d' : '/etc/nginx/conf.d',
        'log_d' : '/var/log/nginx',
        'sites_d' : '/etc/nginx/sites.d',
        'var_d' : '/var/nginx',
        'www_user' : 'www-data',
        'www_group' : 'www-data',
    },
    'RedHat' : {
        'package' : 'nginx',
        'base_d' : '/etc/nginx',
        'config_path' : '/etc/nginx/nginx.conf',
        'conf_d' : '/etc/nginx/conf.d',
        'log_d' : '/var/log/nginx',
        'sites_d' : '/etc/nginx/sites.d',
        'var_d' : '/var/nginx',
        'www_user' : 'nginx',
        'www_group' : 'nginx',
    },
    'Debian' : {
        'package' : 'nginx',
        'base_d' : '/etc/nginx',
        'config_path' : '/etc/nginx/nginx.conf',
        'conf_d' : '/etc/nginx/conf.d',
        'log_d' : '/var/log/nginx',
        'sites_d' : '/etc/nginx/sites.d',
        'var_d' : '/var/nginx',
        'www_user' : 'www-data',
        'www_group' : 'www-data',
    },
    'FreeBSD' : {
        'package' : 'nginx',
        'base_d' : '/usr/local/etc/nginx',
        'config_path' : '/usr/local/etc/nginx/nginx.conf',
        'conf_d' : '/usr/local/etc/nginx/conf.d',
        'log_d' : '/var/log/nginx',
        'sites_d' : '/usr/local/etc/nginx/sites.d',
        'var_d' : '/var/nginx',
        'www_user' : 'www',
        'www_group' : 'www',
    },
},
merge = salt['pillar.get']('nginx:lookup'), default = 'default') %}
```

Versions:
```
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Sep 17 2015, 01:17:16)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.3
           cffi: 1.1.1
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: amd64
        release: 10.1-RELEASE-p10
```
