### ISSUE TITLE
Minion dies silently after highstate

### ISSUE THREAD

**Issue by deniswal** [saltstack/salt#27599]
``` yaml
$ salt --versions-report
           Salt: 2015.5.3
         Python: 2.7.5 (default, Apr  9 2015, 11:03:32)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
        Tornado: Not Installed
Red Hat Enterprise Linux Server release 7.1 (Maipo)
```

Salt is installed minions and master with the RedHat distribution.

Salt minions and master are used in user mode (Use of root_dir: <path to user home>/salt/

No log, no trace, no core, even started with -l debug.

No problem reported on the master side.

The highstate is success but the next salt actions timeout on the newly missing minions.

It is random but repeatable, 0 to 5 minions on a set of 45 servers. Not always the same servers.
This appeared this week, having worked without trouble for 1.5 month with this version and before 8 months with the  2014.1.12 version.
