### ISSUE TITLE
Timeout on 2015.8.0 

### ISSUE THREAD

**Issue by valentin2105** [saltstack/salt#27617]
Hi !

I use Salt on Debian 8, **version 2015.8.0** for both minion & master.
I have 16 minions, with max 100 states by servers.
I think I have a problem in my configuration, because I got some ** Timeout problems** :

My **Master version.report** :

```
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.8.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2 
```

My **Master configuration** (/etc/salt/master) :

```
 state_verbose: False
 state_output: mixed

 file_roots:
   base:
     - /srv/salt/

 worker_threads: 8
 interface: 192.168.42.125

 rest_cherrypy:
   port: 8000
   host: 127.0.0.1
   disable_ssl: true

 external_auth:
   pam:
     myuser:
         - .*
         - '@runner'
         - '@wheel'
```
I use default Minion configuration.

When I do, for example this command :
```
salt app1 state.highstate
```
This took 20s, with no error, just perfect !!! :+1: 

But when I do : 
```
salt '*' state.highstate
```
I got this : 
```
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

And if I put a big timeout on Salt/Master config, the highstate work fine but I Got this for some file to deploy :
```
backup1:
----------
          ID: /etc/apt/sources.list.d/salt.list
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Message timed out
     Started: 15:50:23.346388
    Duration: 60065.774 ms
```
(and example for some files)

When I launch **Saltmaster in Debug mode**, I got some errors (+100) : 
```
[DEBUG   ] Fileserver attempted to read incomplete cache file. Retrying.
[DEBUG   ] Fileserver attempted to read incomplete cache file. Retrying.
```
And I got it on **Minion's logs** :
```
2015-10-02 15:29:10,968 [salt.minion      ][WARNING ][700] Unable to send mine data to master.
2015-10-02 15:29:11,522 [salt.utils.schedule][ERROR   ][23534] Unhandled exception running mine.update
```

Before, when I use 2015.5.3, I haven't this problem (and Salt was really reactive).
With 2015.8.0 an '*' state.highstate took 4mn and on 2015.5.3 it took max 1mn30.

Have you an idea about this issue ?

**Thanks a lot !**
