### ISSUE TITLE
service.running doesn't restart manually stopped Upstart services

### ISSUE THREAD

**Issue by ryanwalder** [saltstack/salt#27613]
state:
```
ssh:                                                                       
  pkg.latest:                                                                   
    - name: ssh                                                                 
  service.running:                                                              
    - name: ssh                                                                 
    - sig: sshd                                                                 
    - require:                                                                  
      - pkg: ssh
```

state run:
```
local:
----------
          ID: ssh
    Function: pkg.latest
        Name: ssh
      Result: True
     Comment: Package ssh is already up-to-date.
     Started: 22:52:13.165583
    Duration: 5403.424 ms
     Changes:   
----------
          ID: core-ssh
    Function: service.running
        Name: ssh
      Result: True
     Comment: The service ssh is already running
     Started: 22:52:18.673474
    Duration: 71.665 ms
     Changes:   

Summary
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
```

stop the service:
```
vagrant@test:~$ sudo service ssh stop
ssh stop/waiting
vagrant@test:~$ sudo service ssh status
ssh stop/waitin
```

re-run the state:

```
local:
----------
          ID: ssh
    Function: pkg.latest
        Name: ssh
      Result: True
     Comment: Package ssh is already up-to-date.
     Started: 22:52:13.165583
    Duration: 5403.424 ms
     Changes:   
----------
          ID: ssh
    Function: service.running
        Name: ssh
      Result: True
     Comment: The service ssh is already running
     Started: 22:52:18.673474
    Duration: 71.665 ms
     Changes:   

Summary
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
```

check the service:
```
vagrant@test:~$ ps ax | grep ssh
 9603 ?        Ss     0:00 sshd: vagrant [priv]
 9614 ?        S      0:02 sshd: vagrant@pts/1 
24171 pts/1    S+     0:00 grep --color=auto ssh
```

start the service:
```
vagrant@test:~$ sudo service ssh start
ssh start/running, process 24181
vagrant@test:~$ sudo service ssh status
ssh start/running, process 24181
vagrant@test:~$ ps ax | grep ssh
 9603 ?        Ss     0:00 sshd: vagrant [priv]
 9614 ?        S      0:02 sshd: vagrant@pts/1 
24181 ?        Ss     0:00 /usr/sbin/sshd -D
24191 pts/1    S+     0:00 grep --color=auto ssh
```
