### ISSUE TITLE
A state module for smartos to manage zones/machines

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#27658]
Having a state module to manage machines/zones on smartos would be awesome.

**Comment by sjorge** [comment]
I will look at how state modules work and see what I can do after cleanup 'virt' module for SmartOS. Any recommended state module I can use as a guide?

**Comment by jfindlay** [comment]
@sjorge, thanks for the feature request.  The only other state I can think of is virt.

**Comment by sjorge** [comment]
Alright that gives me something to work from :+1: 
Not sure when I'll get to it though. Work got a lot busier.

**Comment by jfindlay** [comment]
@sjorge, no problem and thanks for your excellent contributions to salt.

**Comment by sjorge** [comment]
Some brainstorming on how to best deal with a state module for a SmartOS compute node:
```
base:
  'cn01.acheron.be':
    admin_nic:
      smartos.config_present:
        - value: 'xx:xx:xx:xx:xx:xx'
    admin_ip:
      smartos.config_present:
        - value: 172.16.x.x
    admin_ip6:
      smartos.config_absent

    c02a2044-c1bd-11e4-bd8c-dfc1db8b0182:
      smartos.image_present
    e69a0918-055d-11e5-8912-e3ceb6df4cf8:
      smartos.image_absent
    430da066-e3a7-11e4-9657-332a2dbdf565:
      smartos.image_vacuum

    nacl.acheron.be:
      smartos.zone_present
        - image_uuid: c02a2044-c1bd-11e4-bd8c-dfc1db8b0182
        - brand: joyent
        - quota: 10
        - nics: [ {nic_tag: trunk, vlan_id: 10}, {nic_tag: trunk, vlan_id: 20} ]
    puppet.acheron.be:
      smartos.zone_absent
    chef.acheron.be:
      smartos.zone_absent
        - archive: True
```

smartos.zone_absent -> destroy the zone if present, do nothing if absent
smartos.zone_present -> create zone if absent, update zone if present and config <> current config
smartos.image_absent -> delete the image if present, do nothing if absent
smartos.image_present -> install image if absent, do nothing if present
smartos.image_vacuum -> delete the image if present and not in use, do nothing if absent or present and in use
smartos.config_present -> ensure config value is present in /usbkey/config, update if value <> current value
smartos.config_absent -> remove config value if present, do nothing if absent

smartos.zone_present will use kwargs to build the configuration for the zone.
It will have a 'allow_kvm_reboot' and a 'allow_reprovision' parameters to dictate if a kvm guest should be rebooted on update (only if needed) and if a zone is allowed to be reprovisioned. (not decided on default for those yet)

@nshalman @papertigers some input welcome if you guys have better ideas

@jfindlay 1) does the above fit the salt stack way (mostly just played with it due to lacking smartos support ;)) 2) I'm unsure if or how to handle some of the nesting.

e.g. smartos.zone_present will consume kwards to pass to the vmadm execution module.
for the nics property I simply pass: nics='[{ "nic_tag": "admin", "ip": "198.51.100.123", ...}, {...}]'

Not sure I can just do the same for a state module value? I assume so though.
