### ISSUE TITLE
LXC init does not pass template param to lxc-create

### ISSUE THREAD

**Issue by martinhoefling** [saltstack/salt#27662]
Creating a new lxc instance via salt-cloud fails, probably because the `-t templatename` parameter is missing.

Output:
```
root@debian-jessie:/home/vagrant# salt-cloud -p ubuntu-lxc test
[INFO    ] salt-cloud starting
themaster:
    True
[INFO    ] Runner completed: 20151004103030737616
themaster:
    True
[INFO    ] Runner completed: 20151004103031273046
themaster:
    ----------
    frozen:
        ----------
    running:
        ----------
    stopped:
        ----------
[INFO    ] Runner completed: 20151004103031983817
[INFO    ] Searching for LXC Hosts
[INFO    ] Creating container(s) '['test']' on host 'themaster'
event:
    ----------
    message:
        ----------
        comment:
        done:
        errors:
            ----------
            themaster:
                ----------
                test:
                    |_
                      ----------
                      changes:
                          ----------
                      comment:
                          Container could not be created with cmd 'lxc-create -n test -f /tmp/tmpxgBXi5 -B dir': lxc_container: Error creating container test
                      name:
                          test
        ping_status:
            False
        result:
            False
        themaster:
suffix:
    progress
comment:
done:
errors:
    ----------
    themaster:
        ----------
        test:
            |_
              ----------
              changes:
                  ----------
              comment:
                  Container could not be created with cmd 'lxc-create -n test -f /tmp/tmpxgBXi5 -B dir': lxc_container: Error creating container test
              name:
                  test
ping_status:
    False
result:
    False
themaster:
[INFO    ] Runner completed: 20151004103032533633
test:
    ----------
    Error:
        Error while creating test,
    changes:
        ----------
    comment:
    name:
        test
    result:
        False
    runner_return:
        ----------
        comment:
        done:
        errors:
            ----------
            themaster:
                ----------
                test:
                    |_
                      ----------
                      changes:
                          ----------
                      comment:
                          Container could not be created with cmd 'lxc-create -n test -f /tmp/tmpxgBXi5 -B dir': lxc_container: Error creating container test
                      name:
                          test
        ping_status:
            False
        result:
            False
        themaster:
```

Configuration and a vagrant setup to reproduce the issue can be found in this repo:
https://github.com/martinhoefling/molten

* The configuration (master / cloud profiles, ...) are in [./vagrant/salt](https://github.com/martinhoefling/molten/tree/master/vagrant/salt)
* Run vagrant up dev-cloud in the repo (this creates a single instance with salt master / minion / lxc installed and configured)
* `vagrant ssh dev-cloud`, `sudo bash`, `salt-cloud -p ubuntu-lxc test`

If I run `lxc-create -t ubuntu -n test -B dir` everything works fine. Without `-t ubuntu`, I get the same output as in the salt init job.

**Comment by jtand** [comment]
@martinhoefling Thanks for the bug report!

**Comment by pass-by-value** [comment]
You are right @martinhoefling we do need the `image` key. There are some other keys required as well

Here's my cloud profile (notice the addition of `image` and `script_args`)

```yaml
ubuntu-lxc:
  provider: dev-lxc
  lxc_profile: lxc-ubuntu-default
  image: ubuntu
  script_args: -P
  network_profile: ubuntu
  minion:
    master: localhost
```

I added the following [network profile](https://docs.saltstack.com/en/latest/topics/tutorials/lxc.html#network-profiles) so the container can resolve addresses

```yaml
lxc.network_profile:
  ubuntu:
    eth0:
      link: virbr0
```

I got the name `vibr0` by doing

```shell
[root@li1258-28 ~]# brctl show
bridge name     bridge id               STP enabled     interfaces
virbr0          8000.525400f732bb       yes             vethFFLHGM
                                                        virbr0-nic
```

fyi: Distribution that I'm using

```shell
[root@li1258-28 ~]# python -c 'import platform; print platform.platform()'
Linux-4.1.5-x86_64-linode61-x86_64-with-centos-7.1.1503-Core
```

I'm on `2015.8`

Once I configure the above cloud profile and the network profile I get `Container 'test1' successfully initialized`.

Could you please try with these settings? Do let me know how it goes!

**Comment by martinhoefling** [comment]
Hmm, my profile now looks like this:

```
debian-lxc:
  provider: lxc-dev
  lxc_profile:
    template: download
    options:
      dist: debian
      release: jessie
      arch: amd64
  image: debian
  script_args: -P
  network_profile:
    eth0:
      link: virbr0
      type: veth
      flags: up
      ipv4: 192.168.122.100/24
      ipv4.gateway: 192.168.122.1
    eth1:
      link: virbr1
      type: veth
      flags: up
      ipv4: 192.168.100.100/24
  minion:
    master: 192.168.50.1
```

Now it seems as if the options are not supported by lxc:

```
muh2:
    ----------
    Error:
        Error while creating muh2,
    changes:
        ----------
    comment:
    name:
        muh2
    result:
        False
    runner_return:
        ----------
        comment:
        debian:
        done:
        errors:
            ----------
            debian:
                ----------
                muh2:
                    |_
                      ----------
                      changes:
                          ----------
                      comment:
                          Container could not be created with cmd 'lxc-create -n muh2 -f /tmp/tmpkgSR26 -t debian -B dir -- --release jessie --arch amd64 --dist debian': getopt: unrecognized option '--dist'
                          lxc_container: container creation template for muh2 failed
                          lxc_container: Error creating container muh2
                      name:
                          muh2
        ping_status:
            False
        result:
            False
```

However, this should be supported by lxc as documented here: https://github.com/lxc/lxc/blob/master/templates/lxc-download.in

Anyhow, this problem probably is not related to salt.

**Comment by pass-by-value** [comment]
@martinhoefling 

I applied the following profile and got `Container 'container27' successfully initialized`

```yaml
debian-lxc:
  provider: dev-lxc
  lxc_profile:
    template: download
    options:
      release: jessie
      arch: amd64
  image: debian
  script_args: -P
  network_profile: mynetwork
  minion:
    master: localhost
```

I'd suggest removing `dist` from under `options`. On my system the following options are supported

```shell
/usr/share/lxc/templates/lxc-debian -h|--help -p|--path=<path> [-a|--arch] [-r|--release=<release>] [-c|--clean]
```

```shell
root@localhost:~/salt# dpkg -l | grep lxc
ii  lxc                            1:1.0.6-6+deb8u1             amd64        Linux Containers userspace tools
```

**Comment by martinhoefling** [comment]
OK, so I got a bit farther with your hints:

```
[INFO    ] Runner completed: 20151031143511471821
[DEBUG   ] LazyLoaded nested.output
muh:
    ----------
    Error:
        Error while creating muh,
    changes:
        ----------
    comment:
    name:
        muh
    result:
        False
    runner_return:
        ----------
        comment:
        done:
        errors:
            ----------
            themaster:
                ----------
                muh:
                    |_
                      ----------
                      changes:
                          ----------
                          init:
                              |_
                                ----------
                                create:
                                    Container created
                              |_
                                ----------
                                config:
                                    Container configuration updated
                      comment:
                          Unable to stop container: Error changing state for container 'muh' using command 'lxc-start -f /var/lib/lxc/muh/config -d -n muh': lxc-start: The container failed to start.
                          lxc-start: To get more details, run the container in foreground mode.
                          lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
                      name:
                          muh
        ping_status:
            False
        result:
            False
        themaster:
```

When I start the created container manually:
```
root@debian-jessie:/home/vagrant# lxc-start --name muh
lxc-start: failed to find gateway addresses
lxc-start: failed to spawn 'muh'
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
```

lxc container config:
```
# Template used to create this container: /usr/share/lxc/templates/lxc-ubuntu
# Parameters passed to the template: --release trusty --arch amd64
# For additional config options, please look at lxc.container.conf(5)

# Common configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf

# Container specific configuration
lxc.rootfs = /var/lib/lxc/muh/rootfs
lxc.mount = /var/lib/lxc/muh/fstab
lxc.utsname = muh
lxc.arch = amd64

# Network configuration
lxc.start.auto = 1
lxc.network.type = veth
lxc.network.name = eth0
lxc.network.flags = up
lxc.network.link = br0
lxc.network.hwaddr = AC:DE:48:26:95:4C
lxc.network.ipv4.gateway = auto
```

My lxc related config in master.conf:
```
lxc.container_profile:
  lxc-ubuntu-default:
    template: ubuntu

lxc.network_profile:
  lxc-default:
    eth0:
      link: virbr0
      type: veth
      flags: up
```

So the virbr0 seems to be ignored during create.

**Comment by pass-by-value** [comment]
Hi @martinhoefling 

Thanks for working with me on this.

My cloud profile looks like

```yaml
ubuntu-lxc:
  provider: dev-lxc
  lxc_profile:
    template: download
    options:
      release: trusty
      arch: amd64
  image: ubuntu
  seed: False
  network_profile: ubuntu
  minion:
    master: localhost
```

And I have the following network profile defined in my minion config

```yaml
lxc.network_profile:
  ubuntu:
    eth0:
      link: virbr0
```

That lets me create a container with the following config

```yaml
# Template used to create this container: /usr/share/lxc/templates/lxc-ubuntu
# Parameters passed to the template: --release trusty --arch amd64
# For additional config options, please look at lxc.container.conf(5)

# Common configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf

# Container specific configuration
lxc.rootfs = /var/lib/lxc/some_new_container27/rootfs
lxc.mount = /var/lib/lxc/some_new_container27/fstab
lxc.utsname = some_new_container27
lxc.arch = amd64

# Network configuration
lxc.start.auto = 1
lxc.network.type = veth
lxc.network.name = eth0
lxc.network.flags = up
lxc.network.link = virbr0
lxc.network.hwaddr = AC:DE:48:47:BB:CF
```

I'm wondering if your network profile gets overridden somewhere?

I checked the profile settings like below

```shell
root@localhost:~/salt# salt localminion lxc.get_network_profile ubuntu
localminion:
    ----------
    eth0:
        ----------
        link:
            virbr0
```
