### ISSUE TITLE
How to format image url of a private registry image?

### ISSUE THREAD

**Issue by beatscode** [saltstack/salt#27674]
I have a private registry that i'd like to pull/run from. How do I format the image url?
The below doesn't work

```
testid:
  dockerng.running:
     - image: registry.domain:5000/alexlaravel
```

I tried dockerng.running and dockering.image_present. They both give the following error.

```
          ID: registry.domain.com/alexlaravel
    Function: dockerng.image_present
      Result: False
     Comment: Encountered error pulling registry.domain.com:5000/alexlaravel: need more than 1 value to unpack
     Started: 19:10:07.647538
    Duration: 185.624 ms
     Changes:
```

I also tried creating a secondary docker-registries pillar entry

```
custom-docker-registries:
  https://registry.domain.com:5000
```
