### ISSUE TITLE
salt-ssh : No Top file or external nodes data matches found

### ISSUE THREAD

**Issue by jerob** [saltstack/salt#27685]
Hi,

Each first `salt-ssh -i '*' state.highstate`, on a fresh install server, i have the error "No Top file or external nodes data matches found" ( host : debian 8, guest : debian 8). This same command run perfectly the second time.

``` yaml
web1:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found
     Started: 
    Duration: 
     Changes:   

Summary for web1
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
```
