### ISSUE TITLE
2015.8 git_pillar merge inconsistency/bug

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#27714]
In the new git pillar config, 2 syntaxes are possible:

```
ext_pillar:
   - git: 
     - ssh://git@git.example.com/example.git:
       - root: example1/pillar
       - name: example1
   - git:
     - ssh://git@git.example.com/example.git: 
       - root: example2/pillar
       - name: example2
```

```
ext_pillar:
   - git: 
     - ssh://git@git.example.com/example.git:
       - root: example1/pillar
       - name: example1
     - ssh://git@git.example.com/example.git: 
       - root: example2/pillar
       - name: example2
```

The documentation now reads
> More than one git section can be used, but it is not necessary. 

Testing on the rpm's and the current 2015.8 branch reveals however one major difference; the bottom syntax will *NOT* merge pillardata; keys will get overwritten without ever calling `utils.dictupdate.merge` on the final two pillars.

I'm not sure whether this was by design or not; if it's not, this is a bug. If it is, documentation should better reflect the difference; the current text suggest there is none.
