### ISSUE TITLE
salt-ssh: require_reboot is ignored for network.system state

### ISSUE THREAD

**Issue by Dravu** [saltstack/salt#27716]
## Problem Description

I'm using salt-ssh against a server running CentOS 7 and have a state file like so:

``` salt
network-config:
  network.system:
    - enabled: True
    - hostname: blargh
    - gateway: 10.76.30.1
    - gatewaydev: eth2
    - require_reboot: True
    - apply_hostname: True

eth4:
  network.managed:
    - enabled: True
    - type: eth
    - proto: none
    - mtu: 1500
    - hwaddr: 00:6b:dd:6b:dd:6b
```

Despite having "require_reboot" set to "True", a reboot is never initiated on the machine. The issue I'm trying to mitigate by rebooting is that I need to change the MAC Address assignments of the network interfaces and trying to restart the network service (or reset the network interfaces) after doing so will result in errors as the OS has already associated certain MAC Addresses with certain device names. It will also cause my machine to lose network connectivity and require manual intervention to resume remote communication.

Is this a salt-ssh specific problem? Does anyone have any experience trying this using a traditional mastion/minion setup? The other parameters in that section work such as the hostname and gateway, so I feel everything else is correct.
## Version Information

``` yaml
[root@englab_bootserver tmp]# salt --versions-report
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.1.2.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```
