### ISSUE TITLE
Pillar show_top not working on ext_pillar git backend

### ISSUE THREAD

**Issue by mpaolini** [saltstack/salt#27730]
`salt-run pillar.show_top` returns nothing

**Comment by Ch3LL** [comment]
@mpaolini thanks for the report. Can you please paste the output of `salt-run --versions-report`

**Comment by eliasp** [comment]
I can confirm this. Neither `pillar.show_pillar` nor `pillar.show_top` returns anything. The pillar are available on the Minions just as expected, it's just the broken `salt-run` functionality.
```


root@master:~# salt-call test.versions_report
local:
    Salt Version:
               Salt: 2015.8.0
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: 0.9.1
             PyYAML: 3.10
              PyZMQ: 14.4.0
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: 0.5.4
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-55-generic
             system: Ubuntu 14.04 trusty
     
root@master:~# salt-run pillar.show_pillar
root@master:~# salt-run pillar.show_top
```
