### ISSUE TITLE
Using saltenv during State Rendering

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27752]
Is there a way to use the given saltenv parameter during the rendering of the sls files? I maybe missed that when reading the docs but I could not find anything related.

I would like to use the kind of information for e.g.

    {% if saltenv == 'releasing' %}
    # add another state here
    {% endfi %}

**Comment by jfindlay** [comment]
@srkunze:
```salt
# cat /srv/salt/test.sls
print:
  cmd.run:
    - name: echo {{ saltenv }}
```
```yaml
# salt jmoney-debian state.apply test
jmoney-debian:
----------
          ID: print
    Function: cmd.run
        Name: echo base
      Result: True
     Comment: Command "echo base" run
     Started: 11:57:16.195167
    Duration: 14.602 ms
     Changes:
              ----------
              pid:
                  9115
              retcode:
                  0
              stderr:
              stdout:
                  base

Summary for jmoney-debian
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  14.602 ms
```
