### ISSUE TITLE
Support names for vpc_subnets in various boto_* modules

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#27769]
Right now it's necessary to provide subnet ids in various boto_\* modules, making the states less declarable. We should support the ability to target a vpc subnet by name, rather than by id.

**Comment by ryan-lane** [comment]
Proposal:

For vpc subnets, my thought is that we can use a list that looks like this:

```
vpc_subnets:
  - myvpc:mysubnet1a
  - myvpc:mysubnet1b
  - myvpc:mysubnet1c
```

Where myvpc is the vpc name, and mysubnet1a is a subnet name. We could lookup the vpc name, then the subnet name on the inside.

**Comment by ryan-lane** [comment]
An issue here, is that myvpc:mysubnet1a looks a lot like: myvpc: mysubnet1a, which is a YAML dict, rather than a string. We could throw a salt exception when this is set to inform people they have bad syntax, or we could come up with another method of setting this.

For instance, we could instead do:

```
vpc_name: myvpc
vpc_subnets:
  - mysubnet1a
  - mysubnet1b
  - mysubnet1c
```

Where we allow either vpc_id or vpc_name, but vpc_subnets can either specify names or ids in the list.

**Comment by scoates** [comment]
For subnets, I'm not sure there's ever a circumstance where we'd need to supply more than one VPC.

For security groups, we probably do need to have multiple VPCs. (Especially with peering; see below.)

Also, I have some not-particularly-well tested code that can manage VPC peering (I'll package it and create a PR at some point). It definitely requires multiple VPCs:

```yaml
vpcpeer-qa-ops:
    boto_fk.peering_connection_exists:
        - local_vpc_name: qa
        - peered_vpc_name: ops
        - local_route_table_name: qavpc-routingtable
        - peered_route_table_name: opsvpc-routingtable
        - local_routes:
            - 10.{{pillar['group_nums']['ops']}}.0.0/16
        - peered_routes:
            - 10.{{pillar['group_nums']['testmaster']}}.0.0/16
        - require:
            - boto_vpc: qa
            - boto_vpc: qavpc-routingtable
            - boto_vpc: ops
            - boto_vpc: opsvpc-routingtable
```
