### ISSUE TITLE
Mount state destroys fstab with btrfs subvolumes

### ISSUE THREAD

**Issue by herbmaster** [saltstack/salt#27767]
Unfortunately the mount state module corrupts the fstab when using btrfs subvolumes
as it replaces all occurrences of the device with the options for the single subvolume.
Probably related to the issues with tmpfs, which are marked as fixed (e.g. #17198)

State file:

```
/.snapshots:
  mount.mounted:
    - device: /dev/sda2
    - fstype: btrfs
    - mkmnt: True
    - opts: rw,relatime,space_cache,compress=lzo,subvol=/arch-root-snapshots
    - persist: True
```

Fstab before state:

```
# /etc/fstab: static file system information
#
# <file system> <dir> <type>  <options> <dump>  <pass>
# UUID=ea58b6a5-f1fa-41a1-b25f-5aa9520a178c
/dev/sda2             /                   btrfs       rw,relatime,space_cache,compress=lzo,subvol=/arch-root    0 0
/dev/sda2             /var/cache          btrfs       rw,relatime,space_cache,compress=lzo,subvol=/arch-var-cache 0 0

# UUID=6EB0-D814
/dev/sda1             /boot             vfat        rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro  0 2
```

Fstab after state file:

```
# /etc/fstab: static file system information
#
# <file system> <dir> <type>  <options> <dump>  <pass>
# UUID=ea58b6a5-f1fa-41a1-b25f-5aa9520a178c
/dev/sda2       /.snapshots btrfs   rw,relatime,space_cache,compress=lzo,subvol=/arch-root-snapshots    0 0
/dev/sda2       /.snapshots btrfs   rw,relatime,space_cache,compress=lzo,subvol=/arch-root-snapshots    0 0

# UUID=6EB0-D814
/dev/sda1             /boot             vfat        rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro  0 2
```

Expected fstab:

```
# /etc/fstab: static file system information
#
# <file system> <dir> <type>  <options> <dump>  <pass>
# UUID=ea58b6a5-f1fa-41a1-b25f-5aa9520a178c
/dev/sda2             /                   btrfs       rw,relatime,space_cache,compress=lzo,subvol=/arch-root    0 0
/dev/sda2             /var/cache          btrfs       rw,relatime,space_cache,compress=lzo,subvol=/arch-var-cache 0 0
/dev/sda2 /.snapshots btrfs rw,relatime,space_cache,compress=lzo,subvol=/arch-root-snapshots 0 0

# UUID=6EB0-D814
/dev/sda1             /boot             vfat        rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro  0 2
```

Versions:

```
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Sep  7 2015, 13:51:49)
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.1.3
           cffi: 1.2.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.9
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.0
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:   
        machine: x86_64
        release: 4.2.2-1-ARCH
```
