### ISSUE TITLE
file.managed backup: minion seems not to work

### ISSUE THREAD

**Issue by m7v8** [saltstack/salt#27787]
After running:
`salt-ssh <host> state.sls database`

With this state defintion (shortened):
database/init.sls:

```
postgresql:                             
  [..]
  file.managed:
    - name: {{ salt['user.info']('postgres').home }}/data/postgresql.conf
    - source: salt://database/files/postgresql.conf
    - backup: minion
    - template: jinja
    - require:
      - pkg: postgresql
```

And of course changes in 'database/files/postgresql.conf' salt will not generate a backup file under: /var/cache/salt/minion/
I currently can not verify if this only happens when used with salt-ssh.

Saltversion:
salt-ssh 2015.8.0 (Beryllium)
OS:
OpenSuSE 12.3
