### ISSUE TITLE
watch_in a non-existent state in extend does not cause an error

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt#27785]
salt-call --versions-report

```
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.5.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1precise1
```

clamav/init.sls:

```
clamav-daemon:
  pkg:
    - latest
    - require:
      - cmd: apt_sources
      - pkg: clamav-freshclam
  file:
    - managed
    - name: /etc/clamav/clamd.conf
    - source: salt://clamav/clamd.jinja2
    - template: jinja
    - mode: 440
    - user: root
    - group: clamav
    - require:
      - pkg: clamav-daemon
```

amavis/clamav/init.sls:

```
include:
  - clamav

extend:
  clamav:
    user:
      - groups:
        - amavis
      - require:
        - pkg: clamav-daemon
        - pkg: amavis
      - watch_in:
        - blah: clamav-daemon
```

Running `state.sls amavis.clamav` still passed although `blah: clamav-daemon` does not exist.
The reason is it just check the ID `clamav-daemon` and only throw an error when that ID does not exist:

```
local:
    Data failed to compile:
----------
    Cannot extend ID 't' in 'base:clamav'. It is not part of the high state.
This is likely due to a missing include statement or an incorrectly typed ID.
Ensure that a state with an ID of 't' is available
in environment 'base' and to SLS 'clamav'
```

You can specify `whatever: clamav-daemon` in this case and it does not failed.

**Comment by jfindlay** [comment]
@quantonganh, thanks for the report.  Do you know if this still happens on 2015.5.5 or later?

**Comment by quantonganh** [comment]
> Do you know if this still happens on 2015.5.5 or later?

Yes.

salt-call --versions-report

```
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.8 (default, Aug 24 2014, 21:26:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.9.2
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.13
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 14.5.0
         system: 10.10.5 -- x86_64
```

slack/init.sls:

```
{%- set user = salt['cmd.run']('stat -f "%Su" /dev/console') %}

include:
  - brew.cask

slack:
  cmd:
    - run
    - name: brew-cask install slack
    - user: {{ user }}
    - unless: brew-cask list | grep slack
    - require:
      - cmd: brew-cask
```

test/init.sls:

```
include:
  - slack

extend:
  slack:
    cmd:
      - require_in:
        - x: slack
```

and the result:

```
----------
          ID: slack
    Function: cmd.run
        Name: brew-cask install slack
      Result: True
     Comment: unless execution succeeded
     Started: 07:06:45.589941
    Duration: 284.947 ms
     Changes:

Summary for local
------------
Succeeded: 3
Failed:    0
------------
Total states run:     3
Total run time: 868.938 ms
```

The reason is requisite_in keywords are not checked at this line: https://github.com/saltstack/salt/blob/develop/salt/state.py#L1932

If I change `require_in` to `require`:

```
----------
          ID: slack
    Function: cmd.run
        Name: brew-cask install slack
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     x: slack
     Started:
    Duration:
     Changes:

Summary for local
------------
Succeeded: 2
Failed:    1
------------
Total states run:     3
Total run time: 586.844 ms
```
