### ISSUE TITLE
[ERROR   ] Got a bad pillar from master, type str, expecting dict:

### ISSUE THREAD

**Issue by tiger-seo** [saltstack/salt#27792]
after upgrading to 2015.5.5 got this error:
`[ERROR   ] Got a bad pillar from master, type str, expecting dict:`
on 2015.5.3 it works as expected

**Comment by jfindlay** [comment]
@tiger-seo, thanks for the report.  Is it possible for you to provide a minimal test case to demonstrate this problem?

**Comment by sjwoodr** [comment]
I see this too in the minion logs but I have no idea when it started or what caused it.... which I realize isn't very useful.  This is with 2015.5.2 minions.

**Comment by sjwoodr** [comment]
@jfindlay -- 

Update:  I figured it out....  I was not out of disk space but the master cache had exhausted 100% of the inodes for the /var filesystem.   Solution:

1) stop the salt master
2) rm -rf /var/cache/salt/master
3) restart the salt master
4) possibly also restart the minion(s)

**Comment by jfindlay** [comment]
Excellent, thanks @sjwoodr.  I have a suspicion this occult error message may be masking more than one problem.  At least in the case you have found, I think we can handle and message a more useful error.

**Comment by tiger-seo** [comment]
@jfindlay i don't have a test case, because in my case on both our environments (stage and prod) the only needed step is to upgrade ti 2015.5.5

**Comment by tiger-seo** [comment]
```
# salt --versions
           Salt: 2015.5.5
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 2.2.0.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

**Comment by jfindlay** [comment]
@tiger-seo, any more information you can provide about your pillar setup or salt setup that you think may be related to this would be helpful, thanks.

**Comment by brucemartins** [comment]
@jfindlay  I see something similar and this is what the masters log outputs 

2015-11-03 12:40:02,229 [salt.master                              ][ERROR   ][10272] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 1460, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 1236, in _pillar
    'pillar': data})
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 122, in dumps
    except (OverflowError, msgpack.exceptions.PackValueError):
AttributeError: 'module' object has no attribute 'exceptions'

**Comment by jfindlay** [comment]
@brucemartins, this is a separate issue that has been fixed in #26714.

**Comment by tiger-seo** [comment]
@jfindlay please help me to provide you more information, because I have no idea

**Comment by tiger-seo** [comment]
Btw, supposedly, this error doesn't appear if I run state without pillar being used

**Comment by jfindlay** [comment]
@tiger-seo, have you investigated @sjwoodr suggestions?

**Comment by tiger-seo** [comment]
@jfindlay as i sad previously, the same problem appeared on both our environments, for sure it was not about disk free space or inodes ;)

**Comment by kevins9** [comment]
I'm seeing this pop up on 2015.5.5 master/2015.5.5 minions if my pillar YAML contains a sequence of mappings.  This is consistent and is affecting pillars that have been in use successfully for some time, which pass YAML lint.  Here's an example:
```
nfsmounts:
- mountpoint: /foo/bar
  server: foobar01
  serverpath: /bar
- mountpoint: /foo/baz
  server: foobar01
  serverpath: /baz
```

**Comment by cachedout** [comment]
@kevins9 Using that pillar on a 2015.5 master/minion combo, I don't see any issues running `salt my_minion pillar.items`. Could you clarify under what conditions you see this?

```mp@silver ...devel/salt/tests % sudo salt silver pillar.items                                              (git)-[v2015.5.5] 
silver:
    ----------
    nfsmounts:
        |_
          ----------
          mountpoint:
              /foo/bar
          server:
              foobar01
          serverpath:
              /bar
        |_
          ----------
          mountpoint:
              /foo/baz
          server:
              foobar01
          serverpath:
              /baz
```

**Comment by kevins9** [comment]
Master:
```
[root@saltmaster ~]# salt --versions
           Salt: 2015.5.5
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 2.2.0.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
        Tornado: 2.2.1
        timelib: Not Installed
       dateutil: 1.4.1
[root@saltmaster pillar]# cat /srv/pillar/top.sls
base:
  'centos*':
    - pillartest


# vim: set ft=yaml ts=2 sw=2 et sts=2:
[root@saltmaster pillar]# cat /srv/pillar/pillartest.sls
nfsmounts:
- mountpoint: /foo/bar
  server: foobar01
  serverpath: /bar
- mountpoint: /foo/baz
  server: foobar01
  serverpath: /baz
```

Minion 1:
```
[root@centos7test-01 ~]# salt-minion --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.8.1
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.11.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core

[root@centos7test-01 ~]# salt-call grains.get id
[ERROR   ] Got a bad pillar from master, type str, expecting dict:
local:
    centos7test-01.foo.example.org

[root@centos7test-01 ~]# salt-call pillar.items
[ERROR   ] Got a bad pillar from master, type str, expecting dict:
[ERROR   ] Got a bad pillar from master, type str, expecting dict:
local:
    ----------
```

Minion 2:
```
[root@centos7test-02 ~]# salt-minion --versions
           Salt: 2015.5.5
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

[root@centos7test-02 ~]# salt-call grains.get id
[ERROR   ] Got a bad pillar from master, type str, expecting dict:
local:
    centos7test-02.foo.example.org

[root@centos7test-02 ~]# salt-call pillar.items
[ERROR   ] Got a bad pillar from master, type str, expecting dict:
[ERROR   ] Got a bad pillar from master, type str, expecting dict:
local:
    ----------
```
