### ISSUE TITLE
mine.get function with additional parameters

### ISSUE THREAD

**Issue by ogabrielsantos** [saltstack/salt#27814]
When I need IPs with and without loopback I should specify 

```
mine_functions:
  network_ips:
    - mine_function: network.ip_addrs
  network_ips_with_loopback:
    - mine_function: network.ip_addrs
    - include_loopback: True

salt '*' mine.get '*' network_ips
salt '*' mine.get '*' network_ips_with_loopback
```

How about pass function parameters from mine?

```
mine_functions:
  network_ips:
    - mine_function: network.ip_addrs

salt '*' mine.get '*' network.ips
salt '*' mine.get '*' network.ips include_loopback=False
```

Is this possible/useful?
