### ISSUE TITLE
Deploy VM on Proxmox requires 'size' configuration setting? Not according the docs!

### ISSUE THREAD

**Issue by leodus** [saltstack/salt#27821]
Hello SaltStack community,

I am running Saltstack (version 2015.8.0) on a FreeBSD 10.1 system:
```
user@tst10 user $ salt --versions-report
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Jul  6 2015, 00:07:15)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.3
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: amd64
        release: 10.1-RELEASE-p19
```
I want to deploy VMs on one of my Proxmox hosts (version 3.4). I can request information from my Proxmox host, but when I want to deploy a VM I get an error about the 'size' configuration setting :
```
user@tst10 user $ sudo salt-cloud -p proxmox-freebsd mytest
[INFO    ] salt-cloud starting
[ERROR   ] The required 'size' configuration setting is missing from the 'proxmox-freebsd' profile, which is configured under the 'mickey' alias.
Error: There was a profile error: Failed to deploy VM
```
My Proxmox cloud provider configuration (cloud.providers file) looks like:
```
mickey:
  minion:
    master: tst10.intra.domain.nu
  user: root@pam
  password: s0m3th!n9$3cr3t
  url: mickey.intra.domain.nu
  driver: proxmox
  verify_ssl: False

My Proxmox profile looks like (cloud.profiles file) looks like:
proxmox-freebsd:
   provider: mickey
   image: local:iso/FreeBSD-10.1-RELEASE-amd64-dvd1.iso
   technology: qemu
   host: mickey.intra.domain.nu
   ip_address: 172.16.1.144
   ssh_username: root
   password: s0m3th!n9$3cr3t
```
According to the SaltStack Proxmox documentation https://docs.saltstack.com/en/latest/topics/cloud/proxmox.html the 'size' parameter should not exist for the Proxmox driver!

Something is not right here I guess?

Thank you in advance.

Regards,
Lars
