### ISSUE TITLE
Master stop responding when I've specifics symlinks

### ISSUE THREAD

**Issue by ogabrielsantos** [saltstack/salt#27856]
I've created a symlink pointing to itself in order to [bypass this hardcoded `salt://` restriction](https://github.com/saltstack-formulas/bind-formula/issues/37):

So [L126](https://github.com/saltstack-formulas/bind-formula/blob/master/bind/config.sls#L126) and [L154](https://github.com/saltstack-formulas/bind-formula/blob/master/bind/config.sls#L154) can point to my custom `salt://bind/zones/file`

````
file_roots:
  production:
    - /srv/salt/production/states/files/var/named
    - /srv/salt/production/states
  development:
    - /srv/salt/development/states
    - /srv/salt/production/states/files/var/named
    - /srv/salt/production/states
````

`tree /srv/salt/production/states/files/`
````
└── var
    └── named
        ├── bind -> .
        ├── foo.com.db
        ├── bar.com.db
        ├── baz.com.db
        └── zones -> .
````

`tree /srv/salt/production/states/files/var/named/bind/zones/`
````
bind/zones/
├── bind -> .
├── foo.com.db
├── bar.com.db
├── baz.com.db
└── zones -> .
````

When I `test.ping` all minions some of then start to be randomly unresponsive. `state.highstate` does not work returning that master is overloaded or unresponsive. `salt-call test-ping` works fine.

Master log shows a lot of `[salt.transport.zeromq][ERROR   ][15192] Bad load from minion`
Minions logs shows a lot of `SaltReqTimeoutError: Message timed out` exception.

I can reproduce this issue using  `salt-ssh`, `salt` and `salt-call`. I have tried versions 2014.7, 2015.5, 2015.8. All go back to be responsive when I remove the hacky symlink.

I've used production and fresh minions with CentOS 6.7 or 7.

Maybe related to issue #27576
