### ISSUE TITLE
Require_in does not work for file.recurse in file.recurse

### ISSUE THREAD

**Issue by non7top** [saltstack/salt#27854]
Basically I would like to combine two file.recurse so that result has contents of both states merged together, but this does not work. It works as expected for require_in and file.managed.

``` salt
/etc/fwgen/rules:
  file.recurse:
    #    - name: /etc/fwgen/rules
    - clean: True
    - source: salt://baseconfig/files/fwgen_rules/default
    - template: jinja

rules_{{ grains['fqdn'] }}:
  file.recurse:
    - name: /etc/fwgen/rules
    - source:
      - salt://baseconfig/files/fwgen_rules/{{ grains['fqdn'] }}
      - salt://baseconfig/files/fwgen_rules/empty
    - template: jinja
    - require_in:
      - file: /etc/fwgen/rules
```

``` yaml
----------
          ID: rules_s4.wr0.ru
    Function: file.recurse
        Name: /etc/fwgen/rules
      Result: True
     Comment: Recursively updated /etc/fwgen/rules
     Started: 19:57:47.761062
    Duration: 583.825 ms
     Changes:
              ----------
              /etc/fwgen/rules/filter/FORWARD/56_vz1:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
              /etc/fwgen/rules/filter/FORWARD/56_vz2:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
----------
          ID: /etc/fwgen/rules
    Function: file.recurse
      Result: True
     Comment: Recursively updated /etc/fwgen/rules
     Started: 19:57:48.346337
    Duration: 2808.614 ms
     Changes:
              ----------
              removed:
                  - /etc/fwgen/rules/filter/FORWARD/56_vz2
                  - /etc/fwgen/rules/filter/FORWARD/56_vz1

Summary
------------
Succeeded: 2 (changed=2)
Failed:    0
```
