### ISSUE TITLE
boto_vpc is not reading availability_zone

### ISSUE THREAD

**Issue by dverbeek84** [saltstack/salt#27855]
Hi All,

I think there is a bug in both_vpc state module.
When i start to create two subnets in two different zones they are ignored.

This is in my state file:

```
test:
  boto_vpc.present:
    - name: test.x.com
    - cidr_block: 172.22.0.0/16
    - dns_hostnames: True
    - require:
      - sls: boto

subnet_a:
  boto_vpc.subnet_present:
      - name: public-a
      - vpc_name: test.x.com
      - cidr_block: 172.22.0.0/24
      - availability_zone: us-west-1a

subnet_b:
  boto_vpc.subnet_present:
      - name: public-b
      - vpc_name: test.x.com
      - cidr_block: 172.22.1.0/24
      - availability_zone: us-west-1b
```

This is the output: 
```
          ID: subnet_a
    Function: boto_vpc.subnet_present
        Name: public-a
      Result: True
     Comment: Subnet public-a created.
     Started: 20:26:47.446559
    Duration: 1591.49 ms
     Changes:
              ----------
              new:
                  ----------
                  subnet:
                      ----------
                      availability_zone:
                          us-west-1a
                      cidr_block:
                          172.22.0.0/24
                      id:
                          subnet-4c32ea15
                      tags:
                          ----------
                          Name:
                              public-a
              old:
                  ----------
                  subnet:
                      None
----------
          ID: subnet_b
    Function: boto_vpc.subnet_present
        Name: public-b
      Result: True
     Comment: Subnet public-b created.
     Started: 20:26:49.038209
    Duration: 1567.235 ms
     Changes:
              ----------
              new:
                  ----------
                  subnet:
                      ----------
                      availability_zone:
                          us-west-1a
                      cidr_block:
                          172.22.1.0/24
                      id:
                          subnet-4f32ea16
                      tags:
                          ----------
                          Name:
                              public-b
              old:
                  ----------
                  subnet:
                      None
```

as you can see, they are both created in us-west-1a. Also if i set both to us-west-1b they are sill created in us-west-1a.

**Comment by dverbeek84** [comment]
The salt.modules.boto_vpc.create_subnet is having the same behaviour

```
subnet_test_a:
  module.run:
    - name: boto_vpc.create_subnet
    - vpc_name: test.x.com
    - subnet_name: public-a-test
    - cidr_block: 172.22.2.0/24
    - region: us-west-1
    - availability_zone: us-west-1a

subnet_test_b:
  module.run:
    - name: boto_vpc.create_subnet
    - vpc_name: test.x.com
    - subnet_name: public-b-test
    - cidr_block: 172.22.3.0/24
    - region: us-west-1
    - availability_zone: us-west-1b
```

I am using both 2.38.0

**Comment by jfindlay** [comment]
@dverbeek84, thanks for the report.  What version of salt are you using?

**Comment by dverbeek84** [comment]
Hi, Have have test it on two different machines.

I have test it on mij Macbook and my virtual machine CentOS 7.1(clean install)
On my Mac it works and on my VM not. The version i am using on my centos machine is the development branch, but is also happend when installing it from the new repo.saltstack.com.

Versions MacOS:
```
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Oct  2 2015, 13:59:58)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 15.0.0
         system: 10.11 -- x86_64
```

CentOS 
```
Salt Version:
           Salt: 2015.8.0-2691-g59e93dd

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

I also created a script in python using boto 2.38.0 and create multiple subnets(create_subnet function) with it and this works on both my Mac an CentOS.

Let me know if i need to test things out.
