### ISSUE TITLE
Problem grain winrepro

### ISSUE THREAD

**Issue by jacky35** [saltstack/salt#27867]
I would use this simple example :

https://github.com/saltstack/salt-winrepo-ng/blob/master/vlc.sls

``` salt
# both 32-bit (x86) AND a 64-bit (AMD64) installer available
{% set PROGRAM_FILES = "%ProgramFiles%" %}
vlc:
  2.2.1:
    full_name: 'VLC media player'
    {% if grains['cpuarch'] == 'AMD64' %}
    installer: 'http://get.videolan.org/vlc/2.2.1/win64/vlc-2.2.1-win64.exe'
    {% elif grains['cpuarch'] == 'x86' %}
    installer: 'http://get.videolan.org/vlc/2.2.1/win32/vlc-2.2.1-win32.exe'
    {% endif %}
    install_flags: '/S'
    uninstaller: '{{ PROGRAM_FILES }}\VideoLAN\VLC\uninstall.exe'
    uninstall_flags: '/S'
    msiexec: False
    locale: en_US
    reboot: False
--------
```

The problem is that I end up with this error

```
2015-09-15 16:45:20,759 [salt.utils.templates][ERROR   ][23649] Rendering exception occurred :Jinja variable 'dict object' has no attribute 'cpuarch'
```

---

if I run `salt '*' grains.get cpuarch` it works perfectly.

---

``` yaml
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2
```

Thanks Jacky
