### ISSUE TITLE
pip.installed doesn't support recursive requirements files

### ISSUE THREAD

**Issue by rbranche** [saltstack/salt#27871]
Given a requirements.txt file that looks like:

```
pycrypto==2.6
ndg-httpsclient==0.4.0
pyOpenSSL==0.15.1
pyasn1==0.1.8

-r requirements-local.txt
```

And a salt config:

```
    pip.installed:
        - bin_env: {{venv_dir}}
        - activate: True
        - requirements: {{src_dir}}/requirements.txt
        - exists_action: w
        - user: {{deploy_user}}
        - cwd: {{src_dir}}
```

pip.installed will fail with:

```
Could not open requirements file: [Errno 2] No such file or directory: '/tmp/requirements-local.txt'
```

It looks like pip.installed needs to search through the requirements.txt and also copy the recursive requirements files.
