### ISSUE TITLE
salt-cloud failing on aws ubuntu trusty

### ISSUE THREAD

**Issue by mpaolini** [saltstack/salt#27880]
I run `salt-cloud -p ubuntu-trusty-micro-64 test-01` with the following conf:

```
# cat /etc/salt/cloud.providers.d/aws.conf 
aws-default:
  minion:
    master: z.z.z.z
    keysize: 1024
    mine_interval: 60
    mine_functions:
      network.ip_addrs:
        - eth0
      disk.usage: []
  grains:
    roles:
      - aws
  id: XXX 
  key: yyy
  keyname: keypair
  securitygroup:
    - default
  private_key: /etc/salt/aws-keypair.pem
  location: eu-west-1
  ssh_interface: private_ips
  driver: ec2
```

```
# cat /etc/salt/cloud.profiles.d/aws_ubuntu.conf 
ubuntu-trusty-base-64:
  provider: aws-default
  image: ami-53714024
  ssh_username: ubuntu
  script_args: -p python-gnupg

ubuntu-trusty-micro-64:
  size: t2.micro
  extends: ubuntu-trusty-base-64
```

and I get this error

[snip]
```
Preparing to unpack .../python-gnupg_0.3.6-1_all.deb ...
Unpacking python-gnupg (0.3.6-1) ...
Setting up python-gnupg (0.3.6-1) ...
gpg: keyring `/tmp/tmp4fc6ar2h/secring.gpg' created
gpg: keyring `/tmp/tmp4fc6ar2h/pubring.gpg' created
gpg: requesting key 0E27C0A6 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp4fc6ar2h/trustdb.gpg: trustdb created
gpg: key 0E27C0A6: public key "Launchpad PPA for Salt Stack" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Connection to t.t.t.t closed.
OK
 * ERROR: You need to allow pip based installations (-P) in order to install the python package 'tornado >= 4.0'

  Usage :  bootstrap-salt.sh [options] <install-type> <install-type-args>

  Installation types:
    - stable (default)
    - stable [version] (ubuntu specific)
    - daily  (ubuntu specific)
    - testing (redhat specific)
    - git

Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /etc/salt/aws-keypair.pem -p 22 ubuntu@t.t.t.t \'sudo /tmp/.saltcloud-85cb440a-e7da-4220-ac94-0c1b8d2a394d/deploy.sh -c \'"\'"\'/tmp/.saltcloud-85cb440a-e7da-4220-ac94-0c1b8d2a394d\'"\'"\' -p python-gnupg\'' failed. Exit code: 1
```
