### ISSUE TITLE
Autogenerated password fails in Windows EC2 instance deploy

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#27921]
salt-cloud deploy process fails with following info:
```
[INFO    ] Running command under pid 25943: 'winexe -U \'Administrator%password\' //10.0.5.202 "hostname"'
[DEBUG   ] Executing command(PID 25943): 'winexe -U \'Administrator%password\' //10.0.5.202 "hostname"'
```

Executing the following at the command line:
```
winexe -U \'Administrator%password\' //10.0.5.202 "hostname"
```

Fails with:
```
ERROR: Failed to open connection - NT_STATUS_LOGON_FAILURE
```

If I execute command without password, i get a prompt for the password. Entering the generated password does not authenticate.

```
$ winexe -U \'Administrator\' //10.0.5.190 "hostname"
Password for [WORKGROUP\'Administrator']:
```

Returns:
```
ERROR: Failed to open connection - NT_STATUS_LOGON_FAILURE
```

salt-version info:
```
root@manage salt]# salt --versions
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 3.14.48-33.39.amzn1.x86_64
```

salt provider/profile:
```
aws-us-west-2a-private-ips:
  minion:
    master: salt.staging.west.lhn
    keysize: 2048
    master_type: standard

  private_key: /etc/salt/.ssh/salt-provisioning
  keyname: salt_provisioning
  ssh_interface: private_ips
  ssh_username: ec2-user

  win_deploy_auth_retries: 10
  win_deploy_auth_retry_delay: 5

  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'
  location: us-west-2
  availability_zone: us-west-2a
  iam_profile: proper_profile
  driver: ec2

base-ec2-winserver-2012-private:
  provider: aws-us-west-2a-private-ips
  win_installer: /etc/salt/Salt-Minion-2015.8.0-AMD64-Setup.exe
  win_username: Administrator
  win_password: auto
  keysize: 2048
  userdata_file: /etc/salt/windows-firewall.ps1
  del_root_vol_on_destroy: True
  rename_on_destroy: True
  image: ami-xxx
  size: t2.micro
  private_key: /etc/salt/.ssh/mykey.pem
  keyname: mykey.pub
  iam_profile: proper_profile
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicAddress: False
      SubnetId: subnet-xxx
      SecurityGroupId: sg-xxx
```
