### ISSUE TITLE
Module dockerng.inspect_image always returns 404

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#27976]
If I use 

``` shell
salt-call dockerng.search 'ubuntu' official=True
```

I get the following results:

``` yaml
local:
    ----------
    neurodebian:
        ----------
        Description:
            NeuroDebian provides neuroscience research software for Debian, Ubuntu, and other derivatives.
        Official:
            True
        Stars:
            13
        Trusted:
            False
        is_automated:
            False
    ubuntu:
        ----------
        Description:
            Ubuntu is a Debian-based Linux operating system based on free software.
        Official:
            True
        Stars:
            2414
        Trusted:
            False
        is_automated:
            False
    ubuntu-debootstrap:
        ----------
        Description:
            debootstrap --variant=minbase --components=main,universe --include=inetutils-ping,iproute2 <suite> /
        Official:
            True
        Stars:
            17
        Trusted:
            False
        is_automated:
            False
    ubuntu-upstart:
        ----------
        Description:
            Upstart is an event-based replacement for the /sbin/init daemon which starts processes at boot
        Official:
            True
        Stars:
            39
        Trusted:
            False
        is_automated:
            False

```

If I then want to inspect one of those images I am getting a 404:

``` shell
salt-call dockerng.inspect_image ubuntu

Error running 'dockerng.inspect_image': Error 404: No such image: ubuntu
```

The docs mention images such as `centos`, `busybox` etc but none of those work. 

Version details:

```
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-65-generic
         system: Ubuntu 14.04 trusty
```
