### ISSUE TITLE
salt-cloud 2015.5.0 azure provider could not be loaded

### ISSUE THREAD

**Issue by rayba** [saltstack/salt#27980]
We have configured both an AWS and Azure provider for a salt-cloud POC. 

The AWS provider works but we receive the below error for Azure when running any command such as: 
```
salt-cloud --list-providers
```
**we receive the error:**
*The cloud driver, 'azure', configured under the 'my-azure-config' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'azure' driver. In rare cases, this could indicate the 'azure.get_configured_provider()' function could not be found. Removing 'azure' from the available providers list*

We are working from the instructions at: https://docs.saltstack.com/en/2015.5/topics/cloud/azure.html and have replaced the subscription_id with our own Azure subscription id. The relevant parts of salt-cloud directory structure under /etc/salt looks like this:

```
.
├── azure.cer
├── azure.pem
├── cloud
    ├── cloud.conf.d
    ├── cloud.deploy.d
├── cloud.maps.d
│   └── cloud.map
├── cloud.profiles.d
│   ├── azure.profile.conf
│   └── ec2.profile.conf
├── cloud.providers.d
│   ├── azure.provider.conf
│   └── ec2.provider.conf
```
our azure.provider.conf is this:
```
my-azure-config:
  provider: azure
  subscription_id: (our subscription id)
  certificate_path: /etc/salt/azure.pem
  requests_lib: True
  minion:
    master: saltmaster.(our domain).net

  management_host: management.core.windows.net
```
our azure.profile.conf is this:
```
azure-ubuntu:
  provider: azure
  image: 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_3-LTS-amd64-server-20131003-en-us-30GB'
  size: Small
  location: 'East US'
  ssh_username: azureuser
  ssh_password: verybadpass
  slot: production
  media_link: 'http://portalvhdabcdefghijklmn.blob.core.windows.net/vhds'
```

We have installed all dependencies (Azure python SDK, OpenSSL) and our python version is 2.7.10.
