### ISSUE TITLE
salt-master should invalidate cached results for pillar's top.sls when nodegroups change

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#28005]
We have a number of nodegroups which are lists. We use these to define attributes for servers. We then use these nodegroups to define access control rules for our pillars top.sls. When we add new minions, we update the nodegroups. We're currently stuck restarting the master to make such pillars visible to new minions. (master and minions running exact same versions)

```
[ahammond@hss849 ~]$ sudo salt-call test.versions_report
local:
               Salt: 2015.5.3
             Python: 2.6.6 (r266:84292, Jun 18 2012, 14:18:47)
             Jinja2: 2.7.3
           M2Crypto: 0.20.2
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: 1.4.3
             PyYAML: 3.11
              ioflo: 1.3.2
              PyZMQ: 14.3.1
               RAET: 0.6.3
                ZMQ: 4.0.4
               Mako: Not Installed
            Tornado: Not Installed
```
