### ISSUE TITLE
Scheduler duplicates args when configured via minion config file.

### ISSUE THREAD

**Issue by hal58th** [saltstack/salt#28051]
There is a problem where the args for a schedule are duplicated every time you restart salt-minion (and maybe master). This problem **ONLY** seems to happen if you configure the schedule via a config file.

This is the test setup and execution:
```
/etc/salt/minion.d# cat highstate2.conf
schedule:
  someSchedule:
    function: cmd.run
    args:
      - "echo hi"
    minutes: 5
    seconds: 0

service salt-minion restart

salt '*' schedule.list show_all=True

      someSchedule:
        args:
        - echo hi
        enabled: true
        function: cmd.run
        jid_include: true
        maxrunning: 1
        minutes: 5
        name: someSchedule
        seconds: 0

service salt-minion restart
salt '*' schedule.list show_all=True

      someSchedule:
        args:
        - echo hi
        - echo hi
        enabled: true
        function: cmd.run
        jid_include: true
        maxrunning: 1
        minutes: 5
        name: someSchedule
        seconds: 0
```

This use to work before 2015.8.1 (unsure when it broke). I am going off of this document.
https://docs.saltstack.com/en/latest/topics/jobs/schedule.html

```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-24-generic
         system: Ubuntu 14.04 trusty
```
