### ISSUE TITLE
salt-ssh grains.ls strange output with tty: True in grains file

### ISSUE THREAD

**Issue by wenxin-wang** [saltstack/salt#28073]
I read [the Roster doc](https://docs.saltstack.com/en/latest/topics/ssh/roster.html), and here's the `roster` file for a host with `requiretty` settings according to it:

``` yaml
device-devel:
  host: device-devel  # The ip is in the hosts file
  user: charlie
  sudo: True
  tty: True
```

However, when I try

``` bash
salt-ssh device-devel grains.ls
```

I got something like:

``` yaml
device-devel:
    ----------
    __master_opts__:
        ----------
        __role:
            master
        _ssh_version:
            6.9p1 Debian-2
        argv:
            - grains.ls
        auth_mode:
            1
...
    retcode:
        0
    stderr:
        Connection to device-devel closed.
    stdout:
        _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
        {
            "local": {
                "fun_args": [], 
                "jid": "20151019142633410600", 
                "return": {
                    "output_file_append": false, 
                    "ioflo_realtime": true, 
...
                "retcode": 0, 
                "fun": "test.opts_pkg", 
                "id": "device-devel"
            }
        }
```

This is really confusing, because when I turned off `requiretty` on that host, and remove `tty: True` in the `roster` file, and tried again, I got:

``` yaml
device-devel:
    - SSDs
    - biosreleasedate
    - biosversion
    - cpu_flags
    - cpu_model
    - cpuarch
    - domain
    - fqdn
    - fqdn_ip4
    - fqdn_ip6
    - gpus
    - host
...
```

which is one would normally get with `grains.ls`.

In fact, some other functions returns more or less the same thing with `tty: True` in the `roster` file.

Am I doing it wrong? My salt-ssh is from the latest repo on `debian jessie`(though my system is actually on `debian unstable`).

``` bash
$ salt-ssh --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.2
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.10+ (default, Oct 10 2015, 09:11:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.4
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 4.2.0-1-amd64
         system: debian stretch/sid 
```

I'm using `salt-ssh` only currently for learning, so I think it's normal to not have `zmq` on master.
