### ISSUE TITLE
Salt minion locale module missing on Archlinux

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#28080]
Hi,

It seems the locale module fails to lazyload on Archlinux, it was working on previous versions, seems like a regression?
```
[DEBUG   ] Could not LazyLoad locale.avail
```
```
[root@skynet ~]# salt-call locale.avail 'en_US.UTF-8'
'locale.avail' is not available.
```
```yaml
[root@skynet ~]# salt-minion --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Sep 17 2015, 18:40:31)
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.1.3
           cffi: 1.2.1
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.7
        libnacl: 1.4.3
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: 0.2.4

System Versions:
           dist:
        machine: armv7l
        release: 4.1.10-2-ARCH
```
