### ISSUE TITLE
Stop service dependency

### ISSUE THREAD

**Issue by sebastian-cb** [saltstack/salt#28086]
I deployed [SNMP formula](https://github.com/saltstack-formulas/snmp-formula) however instead of adding users in normal location I would like to add them in the recommended config file: `/var/lib/net-snmp/snmpd.conf`. This requires to stop SNMP service before and I'm having troubles to do so using code listed below, `require_in` complains about `Recursive requisite found` and `prereq_in` creates a recursion loop. I'm sure there is a way to do this and I'm just simply doing something wrong.

``` salt
    stop_snmp:
      service.dead:
        - name: {{ snmp.service }}
        - onchanges:
          - file: snmp_users
        #- prereq_in:
        - require_in:
          - file: snmp_users

    snmp_users:
      file.append:
        - name: {{ snmp.config_sys }}
        - template: jinja
        - source: {{ snmp.source_sys }}
        - watch_in:
          - service: {{ snmp.service }}
        - order: last
        - unless: grep -qc "usmUser" {{ snmp.service }}
```

``` yaml
# salt --versions-report
           Salt: 2015.5.5
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```
