### ISSUE TITLE
debian_ip: IPv6 only interfaces not possible (again)

### ISSUE THREAD

**Issue by tobbez** [saltstack/salt#28114]
This is the same as issue #14530. It seems to have been re-introduced at some point.

The following state:
```yaml
he6:
  network.managed:
    - enabled: true
    - type: eth
    - enable_ipv6: true
    - ipv6proto: v4tunnel
    - ipv6ipaddr: 2001:470:X:64::2
    - ipv6endpoint: 216.66.80.X
    - ipv6local: X.X.X.X
    - ipv6ttl: 255
    - ipv6gateway: 2001:470:X:64::1
```
Resuts in this in /etc/network/interfaces:
```
auto he6
iface he6 inet static
iface he6 inet6 v4tunnel
    address 2001:470:X:64::2
    netmask 64
    gateway 2001:470:X:64::1
    endpoint 216.66.80.X
    local X.X.X.X
    ttl 255
```
The line `iface he6 inet static` should not be present at all.
```console
# salt --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2
```

**Comment by jfindlay** [comment]
@tobbez, thanks for the report.

**Comment by tobbez** [comment]
In addition, I guess I should mention that salt still thinks that the interface comes up (when it doesn't, since `ifup` yields an error).

**Comment by jbfriedrich** [comment]
I see the same issue with Ubuntu 15.10 and Ubuntu 16.04. This is my state file:

```
system:
  network.system:
    - enabled: True
    - hostname: ns1.probytes.co
    - apply_hostname: True
    - require_reboot: True
    - gateway: {{ pillar['ipv4subnet']['rtr'] }}
    - gatewaydev: eth0
    - nozeroconf: True

eth0:
  network.managed:
    - enabled: True
    - require_reboot: True
    - type: eth
    - proto: none
    - ipaddr: {{ pillar['ipv4subnet']['ip4'] }}
    - netmask: {{ pillar['ipv4subnet']['ntmsk'] }}
    - gateway: {{ pillar['ipv4subnet']['rtr'] }}
    - dns:
      - 8.8.8.8
      - 8.8.4.4

eth1:
  network.managed:
    - enabled: True
    - require_reboot: True
    - type: eth
    - enable_ipv6: True
    - ipv6proto: auto
    - ipv6ipaddr: 2a01:xxx:xxx:xxx::2
    - ipv6netmask: 64
    - ipv6gateway: fe80::1

eth2:
  network.managed:
    - enabled: True
    - require_reboot: True
    - type: eth
    - proto: none
    - ipaddr: 192.168.0.2
    - netmask: 255.255.255.0
    - dns:
      - 8.8.8.8
      - 8.8.4.4
```
This is the output in my interfaces file: 

```
auto eth0
iface eth0 inet static
    address 1xx.xxx.xx.xxx
    netmask 255.255.xxx.xxx
    gateway 1xx.xxx.xx.xxx
    dns-nameservers 8.8.8.8 8.8.4.4 
auto eth1
iface eth1 inet static
iface eth1 inet6 auto
    address 2a01:xxx:xxx:xxx::2
    netmask 64
    gateway fe80::1

auto eth2
iface eth2 inet static
    address 192.168.0.2
    netmask 255.255.255.0
    dns-nameservers 8.8.8.8 8.8.4.4
```

Also Salt is ignoring the `require_reboot: True` option completely. I think this is related to the issues #32983 and #27716.

SaltStack version report:

```
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.4
```
