### ISSUE TITLE
Unable to manage file: SaltReqTimeoutError: after 180 seconds, ran 3 tries

### ISSUE THREAD

**Issue by menglong81** [saltstack/salt#28121]
i got a error when I use minion to run state
Unable to manage file: SaltReqTimeoutError: after 180 seconds, ran 3 tries

``` yaml
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 13.1.0
         Python: 2.7.4 (default, Dec 24 2013, 16:30:42)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.7.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.4b5
      pycparser: Not Installed
       pycrypto: 2.6
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.4 Final
        machine: x86_64
        release: 2.6.32-358.23.2.el6.x86_64
         system: CentOS 6.4 Final
```

``` salt
file_root:
  - /test1
  - /test2
```

I don't know and I configured the two file is there a link between the root
But haven't seen the wrong
