### ISSUE TITLE
Salt Cloud needs to support GCE scopes

### ISSUE THREAD

**Issue by ryanwalder** [saltstack/salt#28132]
Currently the GCE module for salt-cloud doesn't support [scopes](https://cloud.google.com/compute/docs/authentication) which means if you want anything other than the defaults you cannot use salt-cloud.

**Comment by cachedout** [comment]
This seems totally sensible. We'll have @rallytime and @techhat take a look
and see what can be done here. Thanks for bringing this to our attention.
Much appreciated!

**Comment by rallytime** [comment]
Seems like a reasonable feature request to me. Looping in @erjohnson, too.

**Comment by pass-by-value** [comment]
Hi @ryanwalder.
 
This seems to be supported by the gce driver [OOB](https://github.com/saltstack/salt/blob/4ba736d358abb80cfa4a4705fa8e25d39f3f43b7/salt/cloud/clouds/gce.py#L2058),
provided you're using `libcloud > 0.15.1` (`salt-cloud --versions-report`).

Here's an example addition to the cloud profile (that enables bigquery). `ex_service_accounts` is what you're looking for.

```yaml
my-gce-profile:
 image: ubuntu-1404
  ssh_username: salt
  size: f1-micro
  location: us-central1-a
  network: default
  tags: '["one", "two", "three"]'
  metadata: '{"one": "1", "2": "two",
              "sshKeys": ""}'
  use_persistent_disk: True
  delete_boot_pd: False
  deploy: False
  make_master: False
  provider: gce-config
  ex_service_accounts:
    - scopes:
      - bigquery
```

Scopes need to be a [list of dictionaries](http://libcloud.readthedocs.org/en/latest/compute/drivers/gce.html#specifying-service-account-scopes). If you need to specify the optional email key you could do it like follows

```yaml
my-gce-profile:
...snip
  ex_service_accounts:
    - scopes:
      - bigquery
      email: default
```

I found a [list of scopes](https://github.com/apache/libcloud/blob/4fadb5631ee05898452d622f7493fb30a999bee1/libcloud/compute/drivers/gce.py#L973-L991) on Github (there are probably other places that have this too, I didn't search).

After adding the bigquery scope I was able to successfully run the example titled `Authenticating applications with a client library` on the [authentication](https://cloud.google.com/compute/docs/authentication) page.

I'll add an example to the docs about this.

Please let me know how it goes!
