### ISSUE TITLE
minion state filesystem not updating

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#28151]
Not sure if that is an accurate description, but here is what I am seeing:

On master, salt minionname cp.list_master
```
[root@manage salt]# salt minionname cp.list_master
minionname:

    - apiserver/application.sls
    - apiserver/init.sls
[other files removed for clarity]
```

on minion, ls -l /var/cache/salt/files/base/apiserver/
```
[root@ip-10-1-2-15 ~]# ls -l /var/cache/salt/minion/files/base/apiserver/
total 4
-rw------- 1 root root 61 Oct 20 19:26 init.sls
```

This is after running state.highstate targeting this same minion.

on master salt --versions
```
[root@manage salt]# salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.centos.plus.x86_64
         system: CentOS Linux 7.1.1503 Core
```

on minion, salt-call --versions
```
[root@ip-10-1-2-15 ~]# salt-call --versions
           Salt: 2015.5.5
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

**Comment by jfindlay** [comment]
@rterbush, thanks for the report.  The sls files are cached on the minion, meaning that the cached files are not necessary for a successful state run.  Do you know if this happens between the master and minions running another version of salt (something earlier or later than 2015.5.5)?

**Comment by rterbush** [comment]
After working through issues documented in #28229 I can document here that the problem also exists between minion and master v2015.8.1.

minion versions
```
[root@api srv]# salt-call --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

applications.sls file remains invisible to the minion.

Contents of application.sls
```
make_the_directory:
  file.directory:
    - name: /api
    - user: root
    - group: root
    - mode: 755
    - makedirs: True

install_reportserver_app:
  git.latest:
    - name: https://github.com/LHN/instant-pdf.git
    - rev: master
    - target: /api/pdf
    - require:
      - pkg: git
      - ssh_known_hosts: github.com

compile_reportserver_app:
  cmd.run:
    - cwd: /api/pdf
    - name: |
      lein ring uberjar

run_reportserver_app:
  cmd.run:
    - cwd: /api/pdf
    - name: |
      java -jar target/instant-pdf-0.2.3-standalone.jar 3333
```
