### ISSUE TITLE
salt -G 'os:windows' pkg.refresh_db fails to push repofile to windows host

### ISSUE THREAD

**Issue by nimishp** [saltstack/salt#28162]
Hello All,

I just setup salt stack and I'm having issues trying to even get the repo file to the minion.

I'm following this guide from saltstack: https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html

Here is info of my setup. Let me know if you want more and I appreciate you guys helping in advance!

MASTER:
```yaml
Linux Distro: CentOS Linux release 7.1.1503 (Core) 
Salt: 2015.5.5
Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
Jinja2: 2.7.2
M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

Windows Minion:
```yaml
Salt Version:
           Salt: 2015.8.1
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 2012Server
         system: 2012Server 6.2.9200  Multiprocessor Free
```

I've also got the following installed on the master.
```
GitPython                                            noarch                                         0.3.2-0.6.RC1.el7
```

The linux minions work and I can install packages, the windows minion is having trouble even trying to push the repo cache file to it.

Everytime I run: `salt -G 'os:windows' pkg.refresh_db`

The only response I get is the following with nothing after "minion-2:":  minion-2:

I've tried setting the following in the master config file
   Windows Software Repo settings 

 Location of the repo on the master:
```yaml
win_repo: '/srv/salt/win/repo'
```
Location of the master's repo cache file:
```yaml
win_repo_mastercachefile: '/srv/salt/win/repo/winrepo.p'
```
List of git repositories to include with the local repo:
```yaml
win_gitrepos:
  - 'https://github.com/saltstack/salt-winrepo.git'
```
And in the minion config file on the window minion

Windows Software settings 

 Location of the repository cache file on the master
```yaml
win_repo_cachefile: 'salt://win/repo/winrepo.p'
```

I have the logging set to debug.

**Comment by eliasp** [comment]
Could you run `salt-call -l debug pkg.refresh_db` directly on a affected Minion?
You can also do this through Salt's `cmd.run`:

```
salt your-minion cmd.run 'C:\salt\salt-call -c C:\salt\conf -l debug pkg.refresh_db'
```

**Comment by nimishp** [comment]
I figured it out. The master salt version and the minion version were different, not sure if that matters?

salt-master - 2015.5.5

minion: 2015.8.1 

But I installed 2015.5.5 and it work and I can install packages on the windows minion.

**Comment by eliasp** [comment]
There were major changes in `2015.8.0` in the way Salt handles `win_repo`: https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#winrepo-changes

**Comment by jfindlay** [comment]
@nimishp, thanks for the report.  As @eliasp indicates, there have been some major changes to winrepo in recent releases.  We usually try to support newer masters against older minions (rather than older masters against newer minions) so that when there is an incompatibility such as this, it doesn't make everyone crazy trying to support both scenarios.

It seems the issue here has been resolved by a master upgrade, so I am going to close it.

**Comment by nimishp** [comment]
Actually I downgraded the minion version. 

When I ran the following on CentOS 7. It installed salt 2015.5.5 (Lithium)

curl -L https://bootstrap.saltstack.com -o install_salt.sh
sudo sh install_salt.sh -P -M

**Comment by jfindlay** [comment]
@nimishp, yes, that makes sense.  2015.5.5 is not the latest version.  We should have an update to bootstrap soon to fix that.

**Comment by nimishp** [comment]
sweet, thanks!

**Comment by efficks** [comment]
@jfindlay @eliasp , I've got the same problem as @nimishp on Windows XP 32 bit with saltstack 2015.8.1 on the master and the minion.
Could you please reopen this issue?

When running the update : 
```
salt 'hostname' pkg.refresh_db
```

I've got : 
```
hostname:
```
without any other output

Running : 
```
sudo salt 'SR-SIC-GES1A' cmd.run 'C:\salt\salt-call -c C:\salt\conf -l debug pkg.refresh_db'
```

Outputs : 
```
hostname:
    [DEBUG   ] Reading configuration from C:\salt\conf\minion
    [DEBUG   ] Configuration file path: C:\salt\conf\minion
    [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
    [DEBUG   ] Reading configuration from C:\salt\conf\minion
    [DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506')
    [DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5884)
    [DEBUG   ] Setting zmq_reconnect_ivl to '5884ms'
    [DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506', 'aes')
    [DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506')
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506', 'clear')
    [DEBUG   ] Decrypting the current master AES key
    [DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
    [DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
    [DEBUG   ] LazyLoaded jinja.render
    [DEBUG   ] LazyLoaded yaml.render
    [DEBUG   ] LazyLoaded pkg.refresh_db
    [DEBUG   ] LazyLoaded cp.cache_dir
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506', 'aes')
    [DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506')
    [INFO    ] Caching directory 'win/repo-ng/' for environment 'base'
    [DEBUG   ] LazyLoaded jinja.render
    [DEBUG   ] LazyLoaded yaml.render
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506', 'aes')
    [DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506')
    [DEBUG   ] LazyLoaded nested.output
    local:
```

I'm unable to use the win repo since a switch to 2015.5 or 2015.8
I've try to remove completly the minion on the host and reinstall it without success.

Minion version : 
```
    Salt Version:
               Salt: 2015.8.1

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist:
            machine: x86
            release: 2003Server
             system: 2003Server 5.2.3790 SP2 Multiprocessor Free
```

Master version : 
```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.3 (default, Aug  1 2012, 05:14:39)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-29-virtual
         system: Ubuntu 12.04 precise
```
