### ISSUE TITLE
[FEATURE REQUEST] file.managed: add option to show diff without comments

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#28165]
I propose to allow showing diff between files (in such functions as `file.managed`) except comment lines. This is especially useful when config file contains lots of comment lines and some real config lines.

Related to #28006

**Comment by jfindlay** [comment]
Thanks, @rominf.  This is the feature I didn't know I wanted.

**Comment by lordcirth** [comment]
What would be the best way to present this to the user?  Something like an option hide_comment: <string> so you can specify a comment string, eg '#' or '//'?

**Comment by lordcirth** [comment]
I'm going to assume yes and take a look at how hard it would be.

**Comment by lordcirth** [comment]
https://stackoverflow.com/a/2319078

This sort of solution seems perfect, but involves introducing a new dependency on pyparsing or a similar lib.  What is the official stance on dependencies?

**Comment by lordcirth** [comment]
So, there are 2 kinds of comments, line comments //.... \n which needs one string arg, and multiline comments /* ... */ , which requires 2 string args.

I'm thinking:

```
state_name:
  file.managed:
    - name: /etc/foo
    - hide_comments:
      line: '//'
      multiline_begin: '/*'
      multiline_end: '*/'
```
