### ISSUE TITLE
feature: ipset.present to idempotently manage an entire ipset

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#28234]
Currently I need a minimum of 2 formula calls to manage an ipset set. This should be a single formula with an interface like this:

``` yaml
my_set_name:
  ipset.present:
    - set_type: hash:net
    - comment: my_set_name_comment
    - entries:
      - entry1: entry1_comment
      - entry2: entry2_comment
      - entry3
```

This should check to see if there is a my_set_name ipset of type hash:net with the appropriate comment and the appropriate entries (one call to ipset -L my_set_name, cache the output for later)

IF the state is not as expected (wrong type, missing or extra entries), it should
- create a set named temp_XXXX
- set the entries appropriately, with associated comments
- uses ipset -W my_set_name temp_XXXX to idempotently upgrade my_set_name
- call ipset -L my_set_name again and diff it with the cached output for reporting changes
- ipset -X temp_XXXX to get rid of old set data
