### ISSUE TITLE
Orchestrate when a map finished running

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#28246]
I would like to have an orchestrate file called automatically by salt, after I execute a map file:
`salt-cloud -m quartz-prod.map -P -y`

Is this possible right now or is this a feature request?

**Comment by jfindlay** [comment]
@bogdanr, you can do this in a few different ways.  Probably what I would do is run a minion on the master so that I could include the salt-cloud command as a cmd.run on that minion in the orchestrate run, so that the cloud provision would be integrated nicely into the orchestration.  Or even better, you could use the cloud state for this.

Alternatively, you could fire an event when the salt-cloud command finishes and then have the salt reactor start the orchestrate run upon receipt of this event.  I am less familiar with this strategy, but it should also work.

**Comment by bogdanr** [comment]
@jfindlay How would I run an event when the salt-cloud command finishes?
I think this would be the proper way to do it.

**Comment by jfindlay** [comment]
@bogdanr, I am not very familiar with the event system, but [the documentation](https://docs.saltstack.com/en/latest/topics/event/index.html) should help you get started.

**Comment by bogdanr** [comment]
Thanks. So essentially it is not possible to fire orchestrate automatically after a map is executed so that's why I also suggested this might be a feature request.

**Comment by jfindlay** [comment]
@bogdanr, yes I don't think it is possible to fire an event upon the completion of a cloud map unless you write some custom code to fire the event.

**Comment by hristozv** [comment]
What about using the orchestration to run salt cloud? For the above you can use orchestration state like the following:
```
cloud-map-apply:
  salt.runner:
    - name: cloud.map_run
    - path: quartz-prod.map 
    - kwarg:
         parallel: True

cloud-map-applied:
  salt.runner:
    - name: event.send
    - tag: contoso/cloud/map/quartz-prod/completed
```

After that just configure your reactor to watch for event with tag contoso/cloud/map/quartz-prod/completed.
