### ISSUE TITLE
salt-ssh publish.publish: Permission denied on thin_dir

### ISSUE THREAD

**Issue by stieizc** [saltstack/salt#28278]
I'm having problem with ```salt-ssh``` using ```publish.publish```, basically when I run:
```bash
salt-ssh -i 'compute-*' publish.publish 'compute-*' grains.get fqdn_ip4
```
I got:
```bash
compute-1:
    An Exception occurred while executing publish.publish: [Errno 13] Permission denied: '/var/lib/salt-ssh-agent'
compute-2:
    An Exception occurred while executing publish.publish: [Errno 13] Permission denied: '/var/lib/salt-ssh-agent
```
The directory above was the ```thin_dir``` that I set on my ```roster``` file:
```yaml
compute-1:
  host: what.ever
  user: charlie
  sudo: True
  thin_dir: /var/lib/salt-ssh-agent

compute-2:
  host: what.ever
  user: charlie
  sudo: True
  thin_dir: /var/lib/salt-ssh-agent
```
I got ```requiretty``` turned off. And here's my ```master``` file that allows ```grains.get``` on every minion:
```yaml
---
root_dir: .
file_roots:
  base:
    - srv/salt
pillar_roots:
  base:
    - srv/pillar
peer:
  .*:
    - grains.get
```
I use a ```Saltfile``` pointing the config directory to my current directory.

Am I doing it wrong? Does ```salt-ssh``` support the ```publish``` module?
