### ISSUE TITLE
Cabal appears to be broken

### ISSUE THREAD

**Issue by rowillia** [saltstack/salt#28279]
I'm trying to install shellcheck with `cabal.installed`, but it doesn't appear to work.  This is running on Ubuntu 14 with the most recent version of Salt.

```yaml
Ensure shellcheck is installed:
  cabal.installed:
    - name: shellcheck
    - install_global: True
```

Results in
```
           ID: Ensure shellcheck is installed
     Function: cabal.installed
         Name: shellcheck
       Result: False
      Comment: Error installing 'shellcheck': cabal: HOME: does not exist
      Started: 05:04:16.191854
     Duration: 31.749 ms
      Changes:
```

```yaml
Ensure shellcheck is installed:
  cabal.installed:
    - name: shellcheck
    - user: ubuntu
```

Results in:

```
 ----------
           ID: Ensure shellcheck is installed
     Function: cabal.installed
         Name: shellcheck
       Result: False
      Comment: An exception occurred in this state: Traceback (most recent call last):
                 File "/srv/salt/venv/src/salt/salt/state.py", line 1591, in call
                   **cdata['kwargs'])
                 File "/srv/salt/venv/src/salt/salt/states/cabal.py", line 110, in installed
                   if pkg_name not in installed_pkgs:
               UnboundLocalError: local variable 'installed_pkgs' referenced before assignment
      Started: 04:45:25.064965
     Duration: 18.899 ms
```
