### ISSUE TITLE
hash formats required for s3 source conflict with error message and other uses of file hashes

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#28286]
When referencing an s3:// source for file hashes an error message will be emitted stating that the file format should be 'hashtype=hash', even when the file is provided in that format.

The documentation states that it must be 'hash filename' which does seem to work.

Looking through salt/module/file.py, there seems to be some cases that require the previous format still.

Not sure which is correct, but the documented format seems to work for s3:// sources.

salt-master versions:

```
[root@manage ~]# salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.centos.plus.x86_64
         system: CentOS Linux 7.1.1503 Core
```

**Comment by jfindlay** [comment]
@rterbush, thanks for the report.

**Comment by rterbush** [comment]
Just to add a few more notes here.

It seems that and s3:// source_hash can be in a format that provides only the hash. No type= and no filename. 

However, if the source_hash file is unavailable, the same error message is given regarding the bad file format. I would assume that S3 response codes are telling us if it was not able to find the source file, so it seems that the error message could be a bit more informative as to what the problem is.

**Comment by rterbush** [comment]
Just to further confuse this issue, I now have a 2015.8.5 environment running in staging and am executing the same states that are used in production 2015.8.3 environment and the file.managed: state is failing with the following error.

```
              ID: GetZipArchive_server
        Function: file.managed
            Name: C:\temp\filename.zip
          Result: False
         Comment: Source hash s3://bucket/get/filename.zip.sha256sum format is inva
lid. It must be in the format, <hash type>=<hash>, or it must be a supported protocol: salt, http, https, ftp, swift, s
3, file
         Started: 23:26:42.103000
        Duration: 117.0 ms
         Changes:
```

The state is as follows (note that same state is working on 2015.8.3 system)
```
# Get the zip archive
install_fillename_zip:
  file.managed:
    - name: C:\temp\filename.zip
    - source: s3://bucket/filename.zip
    - source_hash:s3://bucket/filename.zip.sha1sum
    - makedirs: True
```

I am able to use AWS command line tools on the target minion to get both the zip file and the hash file.

So prior to 2015.8.5, this worked, but had a confusing error message when the source_hash was unavailable. On 2015.8.5, this does not appear to work at all.
