### ISSUE TITLE
When salt-minion schedule task  exit abnormally, the schedule  task will not start again

### ISSUE THREAD

**Issue by syf-zsxm** [saltstack/salt#28322]
I have one schedule task like this:

``` yaml
schedule:
  test.getinfo:
    function: test.getinfo
    seconds: 10
    returner: local
    maxrunning: 1
```

But test.getinfo may happen coredump sometimes for some unknown reason. Then the task will not start again, because the pid which coredumped was used by another process in 10 seconds.

Details: 
1. salt-minion start this task, It will get a new pid(for example 777) by os.getpid() in salt.utils.schedule.handle_func(), and record task information in "/var/cache/salt/minion/proc/jid" .
2. then coredump happens , salt.utils.schedule.handle_func() will exit abnormally without delete the file "/var/cache/salt/minion/proc/jid".
3. another process started and used this pid 777 in 10 seconds
4. 10 seconds timeout , salt-minion try to start a new task, but 'jobcount' will be 1 under this scenario . because "/var/cache/salt/minion/proc/jid" exist and salt.utils.process.os_is_running(pid) return True.

How to resolve this problem? such as checking the process name ?
