### ISSUE TITLE
file.comment & file.uncomment changes file permissions on edit

### ISSUE THREAD

**Issue by Grokzen** [saltstack/salt#28320]
Hi. Found this bug after we updated from `2015.5.2` to `2015.5.6` and it is still present in `2015.8.1`.

The short description is that whenever salt runs the state `file.comment` or `file.uncomment` it will change the file permission of the file and not preserv the permissions after it has edited the file.

Steps to reproduce the error.

Create, or use a file that has the permissions `440`. I used my sudoers file (/etc/sudoers) that alreay have this permission, but any file should work.

I then added the following 2 lines to the end of the file

```
%wheel ALL=(ALL) ALL
# %wheel ALL=(ALL) NOPASSWD: ALL
```

I then use the following state to change that file to comment the first line and then uncomment the second line.

```yaml
sudo_wheel_comment:
  file:
    - comment
    - name: /etc/sudoers
    - regex: '^%wheel[ ]ALL=\(ALL\) ALL'
    - char: '# '

sudo_wheel_uncomment:
  file:
    - uncomment
    - name: /etc/sudoers
    - regex: '%wheel[ ]ALL=\(ALL\) NOPASSWD: ALL'
    - char: '# '
```

After i run highstate the content of the file have changed as i expect but the file permissions have changed of the file. I suspect that it will set the default permissions that your system currently has. In my case the file would get `644` and that is what my `/etc/sudoers` have after i run the highstate. It only changes the file permission when it performs a edit.
