### ISSUE TITLE
runners when executed in jinja templates should not print out to stdout

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#28354]
I have some jinja templates that run some salt runners like this : 

``` salt
[snip]
{% set known_hosts = salt['saltutil.runner']('manage.status')['up'] %}
{%- for host,status in salt['saltutil.runner']('virt.list').items() %}
[snip]
```

This ends up spewing out a bunch of output when being rendered. It would be nice if was quiet. 

``` yaml
# salt-call --versions-report
                  Salt: 2015.5.3
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1~bpo8+1
```
