### ISSUE TITLE
salt-cloud VMware driver fails with uncustomizable guest when not customizing guest

### ISSUE THREAD

**Issue by cbuechler** [saltstack/salt#28429]
When deploying a guest OS with salt-cloud vmware driver that isn't customizable by VMware and specifying a network adapter configuration in the profile, it's correctly deployed and the network adapter configured fine, but salt-cloud fails with: 

```    Error:
        Error creating freebsd-server1: (vim.fault.UncustomizableGuest) {
           dynamicType = <unset>,
           dynamicProperty = (vmodl.DynamicProperty) [],
           msg = "Customization of the guest operating system 'freebsd64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations.",
           faultCause = <unset>,
           faultMessage = (vmodl.LocalizableMessage) [],
           uncustomizableGuestOS = 'freebsd64Guest'
        }
```

There is no customization of the guest happening, so that shouldn't fail. 

Take the following cloud.profile for instance: 
```freebsd10_2:
  provider: my-vmware
  clonefrom: freebsd-10_2-template
  cluster: MyCluster
  devices:
    network:
      Network adapter 1:
        name: my-vswitch
        switch_type: standard
```

Where freebsd-10_2-template is a vCenter template of FreeBSD 10.2. Same would happen for any template whose GuestOS is set to any OS that doesn't support guest customization. 

The vmware driver is touching something there unnecessarily that makes it fail. 

``` 
# salt --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Oct 27 2015, 01:15:05)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.3
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: amd64
        release: 10.1-RELEASE-p19
```
