### ISSUE TITLE
state boto_secgroup.present fails to find vpc_name

### ISSUE THREAD

**Issue by mlalpho** [saltstack/salt#28469]
I'm getting a error when attempting to use the salt.boto_secgroup state to manage security groups. Am I doing something wrong? (some content redacted)

```yaml
----------
          ID: create_sg
    Function: boto_secgroup.present
        Name: xxxxx
      Result: False
     Comment: Security group xxxxx created. xxxxx security group configuration could not be retrieved.
     Started: 16:10:53.486125
    Duration: 293.442 ms
     Changes:
              ----------
              new:
                  ----------
                  secgroup:
                      None
              old:
                  ----------
                  secgroup:
                      None
    Warnings: 'vpc_name' is an invalid keyword argument for
              'boto_secgroup.present'. If you were trying to pass additional
              data to be used in a template context, please populate 'context'
              with 'key: value' pairs. Your approach will work until Salt Carbon
              is out. Please update your state files.
```

```sls
create_sg:
  boto_secgroup.present:
    - name        : xxxxx
    - description : descr
    - vpc_name    : xxxvpc
    - rules       :
      - ip_protocol: all
        from_port: -1
        to_port: -1
        cidr_ip:
          - 0.0.0.0/0
      - ip_protocol: icmp
        from_port: -1
        to_port: -1
        source_group_name: xxx_sq
    - rules_egress:
      - ip_protocol: all
        from_port: -1
        to_port: -1
        cidr_ip:
          - 0.0.0.0/0
    - region: us-west-2
    - keyid: xxxxxxxxddddd
    - key: xkcdxkcdxkcdxkcd
```

```sh
# salt --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```
`Package python-boto-2.38.0-2.el7.noarch already installed and latest version
Nothing to do`

Changing state to contain a 'context' dict that contains vpc_name also fails with a similar message.

If I change the state to to use the real vpc_id instead of vpc_name:
```yaml
----------
          ID: create_sg
    Function: boto_secgroup.present
        Name: xxxxx
      Result: True
     Comment: Security group xxxxx created.  Created rules on xxxxx security group.
     Started: 16:38:22.252943
    Duration: 831.458 ms
     Changes:
              ----------
              new:
                  ----------
                  rules:
                      |_
                        ----------
                        cidr_ip:
                            0.0.0.0/0
                        from_port:
                            None
                        ip_protocol:
                            -1
                        to_port:
                            None
                      |_
                        ----------
                        from_port:
                            -1
                        ip_protocol:
                            icmp
                        source_group_group_id:
                            sg-1241234
                        source_group_owner_id:
                            123542345
                        to_port:
                            -1
                  rules_egress:
                      |_
                        ----------
                        cidr_ip:
                            0.0.0.0/0
                        from_port:
                            None
                        ip_protocol:
                            -1
                        to_port:
                            None
                  secgroup:
                      ----------
                      description:
                          descr
                      group_id:
                          sg-1241234
                      name:
                          xxxxx
                      owner_id:
                          123542345
                      rules:
                      rules_egress:
                          |_
                            ----------
                            cidr_ip:
                                0.0.0.0/0
                            from_port:
                                None
                            ip_protocol:
                                -1
                            to_port:
                                None
              old:
                  ----------
                  rules:
                  rules_egress:
                      |_
                        ----------
                        cidr_ip:
                            0.0.0.0/0
                        from_port:
                            -1
                        ip_protocol:
                            -1
                        to_port:
                            -1
                  secgroup:
                      None
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 831.458 ms
```
Second run:
```yaml
----------
          ID: create_sg
    Function: boto_secgroup.present
        Name: xxxx
      Result: True
     Comment: Security group xxxxx present.
     Started: 16:34:10.178922
    Duration: 227.62 ms
     Changes:
```

To confirm, everything works as expected if i leave out vpc_name and define vpc_id. I would really like to see vpc_name working, however. Please advise. Thank You.
