### ISSUE TITLE
exceptional execution result of salt state with "archive.extracted"

### ISSUE THREAD

**Issue by mosuowhq** [saltstack/salt#28557]
I want to get the execution result of salt state with `$?`.
If exception occurs, the `$?` is 11, as below:

``` yaml
root@wanghq:/srv/salt/test# salt '*' state.highstate
server01:
----------
          ID: test.sh
    Function: file.managed
        Name: /var/paas/test.sh
      Result: True
     Comment: File /var/paas/test.sh is in the correct state
     Started: 15:21:41.972972
    Duration: 8.793 ms
     Changes:   
----------
          ID: test
    Function: cmd.run
        Name: bin/bash test.sh
      Result: False
     Comment: Command "bin/bash test.sh" run
     Started: 15:21:41.991797
    Duration: 5.955 ms
     Changes:   
              ----------
              pid:
                  26252
              retcode:
                  127
              stderr:
                  /bin/sh: 1: bin/bash: not found
              stdout:

Summary
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
root@wanghq:/srv/salt/test# echo $?
11
```

However, if the state task with "archive.extracted" is included, the execution result became "0" as following:

``` yaml
root@wanghq:/srv/salt/test# salt '*' state.highstate
server01:
----------
          ID: test-package
    Function: archive.extracted
        Name: /var/paas/test
      Result: True
     Comment: salt://test/test.tar.gz extracted in /var/paas/test/
     Started: 15:48:15.797805
    Duration: 215.824 ms
     Changes:   
              ----------
              directories_created:
                  - /var/paas/test/
              extracted_files:
                  test/
----------
          ID: test.sh
    Function: file.managed
        Name: /var/paas/test.sh
      Result: True
     Comment: File /var/paas/test.sh is in the correct state
     Started: 15:48:16.024579
    Duration: 2.172 ms
     Changes:   
----------
          ID: test
    Function: cmd.run
        Name: bin/bash test.sh
      Result: False
     Comment: Command "bin/bash test.sh" run
     Started: 15:48:16.036343
    Duration: 8.708 ms
     Changes:   
              ----------
              pid:
                  22725
              retcode:
                  127
              stderr:
                  /bin/sh: 1: bin/bash: not found
              stdout:

Summary
------------
Succeeded: 2 (changed=2)
Failed:    1
------------
Total states run:     3
root@wanghq:/srv/salt/test# echo $?
0
```

How could I get the right execution result of the state tasks?
