### ISSUE TITLE
kmod state: please allow several modules

### ISSUE THREAD

**Issue by nodens** [saltstack/salt#28568]
Hi,

It would be nice to have a "mods" parameter to pass a list of modules for salt.states.kmod, the same way the pkg module uses the "pkgs" parameter.

It would allow for things like:

```yaml
conntrack modules:
  kmod.present:
    - persist: True
    - mods:
      - nf_conntrack_ftp
      - nf_nat_ftp
```

Cheers !
