### ISSUE TITLE
file.append does not differentiate between tabs and spaces

### ISSUE THREAD

**Issue by zmalone** [saltstack/salt#28586]
given a sls file like:

    test1:
      file.append:
        - name: /tmp/test.txt
        - text: "foo bar"
    test2:
      file.append:
        - name: /tmp/test.txt
        - text: "foo	bar"

you would expect to see results of:

    foo bar
    foo	bar

but instead you get 

    foo bar

as salt does not appear to differentiate between spaces and tabs for file.append.  This is not documented on https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.append , and appears to be unintentional.

This was tested on 2015.8.1 on Ubuntu 14.04.

**Comment by jfindlay** [comment]
@zmalone, thanks for the report.

**Comment by abednarik** [comment]
I just saw [this](https://github.com/saltstack/salt/blob/2015.8/salt/states/file.py#L3279-L3283) which looks like a check that removes any whitespace to compare file content with text content in state. This will probably will make that if you have something like "foo bar" and want to append "foo      bar" call will return True and file will not be updated.
Regarding new content, I don't find where those white spaces are stripped.

**Comment by abednarik** [comment]
Hi 

 Salt ignores white spaces.

```yaml
  file.append:
    - name: /tmp/test1.txt
    - text: "foo                        bar"
```

```yaml
          ID: common_hostsfile
    Function: file.append
        Name: /tmp/test1.txt
      Result: True
     Comment: Appended 1 lines
     Started: 18:08:00.188813
    Duration: 5.978 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -0,0 +1 @@
                  +foo                  bar
```

```
cat /tmp/test1.txt 
foo                     bar
```

```yaml
Salt Version:
           Salt: 2015.8.3-138-g654cab0
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.1.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-68-generic
         system: Ubuntu 14.04 trusty
```

After updating state and remving all tabs whit a single space

```yaml
  file.append:
    - name: /tmp/test1.txt
    - text: "foo bar"
```

No change is applied [this](https://github.com/saltstack/salt/blob/2015.8/salt/states/file.py#L3279-L3283) will return True since all white space is ignored.

I see 2 alternatives: adding a note in the docs just to give advice regarding behavior or add one argument more in that function ignore_whitespace=True by default to not change any bahavior. In case you set ignore_whitespace to False that check will not run.

@jfindlay  / @cachedout  what do you think?
