### ISSUE TITLE
Tutorial: Getting Started - Functions | Invalid Command

### ISSUE THREAD

**Issue by mattisdada** [saltstack/salt#28600]
If following the tutorial exactly, the section with the command to pull a git repo will not work and throw an exception. This is due to the minions not having git installed....

An alternative is to specify that the package git is required. Otherwise maybe do it on the steps previous?
```yaml
Checkout the SaltStack develop branch:
  git.latest:
    - name: https://github.com/saltstack/salt.git
    - rev: develop
    - target: /tmp/salt
    - require:
      - pkg: git
```
