### ISSUE TITLE
pip.installed fails to detect failure

### ISSUE THREAD

**Issue by mathrick** [saltstack/salt#28616]
I mistakenly forgot to remove `bin_env` from my `pip.installed` arguments. The venv is no longer created, thus the pip binary cannot be found:

``` salt
{% for pkg in pillar['pip-packages'] %}
Install pip package {{pkg}}:
  pip.installed:
    - name: {{pkg}}
    - bin_env: /tmp/test_venv
    - require:
      - pkg: python-pip
{% endfor %}
```

However, the result of running this is a success:

```
    docker-image: ID: Install pip package path.py >= 8.1.2
    docker-image: Function: pip.installed
    docker-image: Name: path.py >= 8.1.2
    docker-image: Result: None
    docker-image: Comment: Error installing 'path.py >= 8.1.2': Could not find a `pip` binary
    docker-image: Started: 18:55:36.478390
    docker-image: Duration: 0.661 ms
    docker-image: Changes:
    docker-image:
    docker-image: Summary
    docker-image: ------------
    docker-image: Succeeded: 3 (unchanged=1, changed=1)
    docker-image: Failed:    0
```
