### ISSUE TITLE
Rabbitmq module failing

### ISSUE THREAD

**Issue by ldelossa** [saltstack/salt#28661]
Trying to use rabbitmq_user.present. When including vhosts and permissions I get an error.

http://hastebin.com/diwavezomi.vbs

The same can be seen when all jinja is ripped out and my state file is simply:

```
rabbitmq_user_tmpchq_user:
  rabbitmq_user.present:
    - name: tmpchq_user1
    - password: 'yup'
    - perms:
      - 'tmpchq':
      - ".*"
      - ".*"
      - ".*"
```

Tried with this also:

```
{% for user, items in salt['pillar.get']('rabbitmq:users').items() %}
rabbitmq_user_{{ user }}:
  rabbitmq_user.present:
    - name: {{ user }}
    - password: {{ items['password'] }}
    - perms:
      {% for vhost in items['vhost'] %}
      - {{ vhost }}:
      {% endfor %}
        - {{ items['permission_config'] }}
        - {{ items['permission_write'] }}
        - {{ items['permission_read'] }}
{% endfor %}
```

Ended with this error:

```

----------
          ID: rabbitmq_user_tmpchq_user
    Function: rabbitmq_user.present
        Name: tmpchq_user
      Result: False
     Comment: Error: function_clause
     Started: 15:26:03.140506
    Duration: 1797.582 ms
     Changes:

Summary for client01p
```
