### ISSUE TITLE
Grains caching and Syndic

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#28676]
I have the following structure of salt minions:
```
root:              # salt-master, salt-minion
  stolb-db.orel    # salt-master, salt-minion, salt-syndic
```

Grains caching works fine on `stolb-db.orel`:
```
$ salt stolb-db.orel grains.get os
stolb-db.orel:
    openSUSE
$ salt-run cache.grains stolb-db.orel | grep os:
    location:
```

But not on `root`:
```
$ salt stolb-db.orel grains.get location
stolb-db.orel:
    openSUSE
$ salt-run cache.grains stolb-db.orel
stolb-db.orel:
    ----------
    id:
        stolb-db.orel
```

```
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.6 (default, Nov 21 2013, 15:55:38) [GCC]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: 1.3.8
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
         pygit2: 0.22.0
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: SuSE 13.1 x86_64
        machine: x86_64
        release: 3.11.10-29-default
         system: openSUSE  13.1 x86_64
```

**Comment by jfindlay** [comment]
@rominf, thanks for the report.  I am confused as to what your commands are demonstrating.  I have a system with a master and a minion (similar to your `root` system).
```yaml
# salt jmoney-main grains.set location here
jmoney-main:
    ----------
    changes:
        ----------
        location:
            here
    comment:
    result:
        True
```
```yaml
# salt jmoney-main grains.get location
jmoney-main:
    here
```
```yaml
# salt-run cache.grains location
```
```yaml
# salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2
```
