### ISSUE TITLE
pip module is taking "too long"

### ISSUE THREAD

**Issue by syedaali** [saltstack/salt#28729]
When I use pip.installed, I noticed that a typical minion run takes a "very long" time, compared to doing a cmd.run with pip. Below is an example:

``` yaml
----------
          ID: psycopg2
    Function: pip.installed
      Result: True
     Comment: Python package psycopg2 was already installed
              All packages were successfully installed
     Started: 03:42:29.180285
    Duration: 17150.999 ms
     Changes:
----------
          ID: sqlalchemy
    Function: pip.installed
      Result: True
     Comment: Python package sqlalchemy was already installed
              All packages were successfully installed
     Started: 03:42:46.332172
    Duration: 26716.507 ms
     Changes:
----------
          ID: petl
    Function: pip.installed
      Result: True
     Comment: Python package petl was already installed
              All packages were successfully installed
     Started: 03:43:13.049607
    Duration: 43691.612 ms
     Changes:
----------
          ID: jira
    Function: pip.installed
      Result: True
     Comment: Python package jira was already installed
              All packages were successfully installed
     Started: 03:43:56.742153
    Duration: 29640.447 ms
     Changes:
```

The above is based upon:

``` salt
psycopg2:
  pip.installed:
    - name: psycopg2

sqlalchemy:
  pip.installed:
    - name: sqlalchemy

petl:
  pip.installed:
    - name: petl

jira:
  pip.installed:
    - name: jira
```

Total run time:  456.647 s

On the other hand if I process the above with cmd.run the time taken is much shorted as seen below:

``` salt
pips:
  cmd.run:
  - name: pip install psycopg2 sqlalchemy pets jira
```

Total run time:  145.564 s
