### ISSUE TITLE
pkgrepo returns error that does not accurately describe where an issue is.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#28720]
Today I spent some time troubleshooting this:

``` salt
docker-repo:
  pkgrepo.managed:
    - name: docker
    - hummanname: Docker Repository
    - baseurl: https://yum.dockerproject.org/repo/main/centos/7
    - gpgcheck: 1
    - key_url: https://yum.dockerproject.org/repo/main/centos/7
    - refresh_db: True
    - enabled: True
```

``` yaml
          ID: docker-repo
    Function: pkgrepo.managed
        Name: docker
      Result: False
     Comment: Failed to configure repo 'docker': The repo does not exist and needs to be created, but a name was not given
     Started: 17:55:24.639544
    Duration: 36.736 ms
     Changes: 
```

The issue lines in the fact that `hummanname` has two `M`s but the error isn't very accurate. This  resulted in some wasted time trying to find the problem.
