### ISSUE TITLE
Exception occurred when calling boto_vpc.route_table_present with test=True

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt#28724]
salt-call --versions-report:

```yaml
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.8 (default, Aug 24 2014, 21:26:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.9.2
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.13
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 14.5.0
         system: 10.10.5 -- x86_64
```

Formula:

```salt
aws_vpc_route:
  boto_vpc:
    - route_table_present
    - name: Public
    - vpc_id: {{ vpc_id }}
    - routes:
      - destination_cidr_block: 0.0.0.0/0
        internet_gateway_name: x
    - subnet_names:
      - Public
    - region: ap-southeast-1
    - keyid: {{ key }}
    - key: "{{ secret }}"
    - require:
      - boto_vpc: aws_vpc_Public_subnet
      - boto_vpc: aws_vpc_gateway
```

and the exception:

```yaml
----------
          ID: aws_vpc_route
    Function: boto_vpc.route_table_present
        Name: Public
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/states/boto_vpc.py", line 580, in route_table_present
                  keyid=keyid, profile=profile)
                File "/usr/local/lib/python2.7/site-packages/salt/states/boto_vpc.py", line 646, in _routes_present
                  if 'error' in route_table:
              TypeError: argument of type 'bool' is not iterable
     Started: 07:09:58.730661
    Duration: 227.994 ms
     Changes:
```
