### ISSUE TITLE
grain saltversioninfo not returning values by index

### ISSUE THREAD

**Issue by cybacolt** [saltstack/salt#28763]
to return the first item in a list, add :0, like so:
salt-call grains.get fqdn_ip4:0

when trying to get the first item from saltversioninfo on 2015.8.x:
salt-call grains.get saltversioninfo:0

nothing is returned.

**Comment by jfindlay** [comment]
@cybacolt, thanks for the report.  I'm not sure if it matters, but the `fqdn_ipv4` list is returned in green text and the `saltversioninfo` is bold yellow text.

```yaml
jmoney-main ~ master # salt-call grains.get fqdn_ip4
local:
    - 10.210.201.55
    - 103.269.133.173
```
```yaml
jmoney-main ~ master # salt-call grains.get saltversioninfo
local:
    - 2015
    - 8
    - 1
    - 0
```
```yaml
jmoney-main ~ master # salt-call grains.get fqdn_ip4:1
local:
    103.269.133.173
```
```yaml
jmoney-main ~ master # salt-call grains.get saltversioninfo:1
local:
```
```yaml
jmoney-main ~ master # salt-call --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2
```
