### ISSUE TITLE
salt-cloud ec2 image creates two keys and minion can't connect

### ISSUE THREAD

**Issue by rusvdw** [saltstack/salt#28766]
We've just started out with Salt and have hit a brick wall almost immediately trying to provision an Ubuntu image on ec2. The instance is created, but the minion is unable to connect due to a key issue. There are two keys created in salt-keys: the minion id supplied to salt-cloud and the ec2 hostname provided by AWS. 

My cloud profile:

```
base-ec2-testing:
  provider: ec2-us-east
  image: ami-d05e75b8
  size: t2.small
  ssh_username: ubuntu
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: False
      SubnetId: subnet-xxxxxxx
      SecurityGroupId:
        - sg-xxxxxxxx
  del_root_vol_on_destroy: True
  del_all_vol_on_destroy: True
  script: bootstrap-salt
  script_args: -c /tmp/ -P -F -K -A 10.0.1.10
```

The creation command:

```
salt-cloud -p base-ec2-testing test.example.com
```

The keys afterward:

```
root@ops1:~# salt-key
Accepted Keys:
test.example.com
Denied Keys:
Unaccepted Keys:
ip-10-0-1-187
Rejected Keys:
```

And the output from test.ping:

```
root@ops1:~# salt '*' test.ping
test.example.com:
    Minion did not return. [No response]
```

On the minion:

```
root@ip-10-0-1-187:~# tail /var/log/salt/minion 
2015-11-11 14:12:32,711 [salt.crypt       ][ERROR   ][9379] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-11-11 14:12:42,726 [salt.crypt       ][ERROR   ][9379] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
...
```

Versions for the master:

```
root@ops1:~# salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.3.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.2
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Ubuntu 14.04 trusty
```

And for the minion:

```
root@ip-10-0-1-187:~# salt-minion --versions
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: 4.3
 Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by rusvdw** [comment]
I've managed to get a working installation together by trawling through the github issues. This time I installed salt-master using the Ubuntu package instructions instead of the method described in the getting started guide. Even then, an old version of salt-minion was installed when I tried to use salt-cloud and the whole thing died with "master_type: str causes minion to fail to start" errors on the minion. 

I finally found issue #28629 that recommended running "salt-cloud -u" to update the bootstrap scripts. Doing this finally gave me the ability to provision and communicate with a minion on EC2 using salt-cloud.

**Comment by jfindlay** [comment]
@rusvdw, thanks for the report.  The updated bootstrap script will be included in 2015.8.2, which is coming out in a few days.  Did `salt-cloud -u` fix the issues you were having?

**Comment by rusvdw** [comment]
Yes it did.

**Comment by PKiman** [comment]
Hi, I am experiencing the same problem and 
```
salt-cloud -u
```
didn't fixed the issue.

```
salt-cloud --versions-report
Salt Version:
            Salt: 2015.8.1
 
Dependency Versions:
 Apache Libcloud: 0.18.0
          Jinja2: 2.7.2
        M2Crypto: 0.21.1
            Mako: Not Installed
          PyYAML: 3.10
           PyZMQ: 14.5.0
          Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: Not Installed
         timelib: Not Installed
 
System Versions:
            dist:   
         machine: x86_64
         release: 4.1.10-17.31.amzn1.x86_64
 


salt --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.1.10-17.31.amzn1.x86_64
```

from the cloud profile:
```
db_small_ec2:
  provider: us-west-2a-ec2
  image: ami-xxxxx
  size: t2.small
  ssh_interface: private_ips
  ssh_username: ec2-user
  minion:
    grains:
      role: database
  script: bootstrap-salt.sh
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      #auto assign public ip (not EIP)
      AssociatePublicIpAddress: False
      SubnetId: subnet-xxxxx
      SecurityGroupId:
        - sg-xxxxx
  tag: {'Environment': 'dev', 'Role': 'database'}
```

used command:
```
salt-cloud -p db_small_ec2 db03-dev.local -l debug
```

**Comment by PKiman** [comment]
It works when the vm variable is rendered into the bootstrap-salt.sh script, but this breaks the -i option when it should be null.
from:
```
_SALT_MINION_ID="null"

```
to:
```
_SALT_MINION_ID="{{ vm['name'] }}"
```

**Comment by rallytime** [comment]
@PKiman Can you elaborate on what you're seeing? Are you saying this happens when you pass `-i` to the `script_args`? And you're seeing two minion keys? I haven't seen this before and I am unsure on how to reproduce this.

**Comment by PKiman** [comment]
Thanks for the follow up.
I think the problem appears in conjunction with salt-cloud and the bootstrap script together.

When I create a new EC2 VM and passing the bootstrap parameters like:

salt-cloud -p db_small_ec2 db03-dev.local --script-args="-i db03–dev.local"

then the minion_id is set correctly to db03-dev.local.

But according to the documentation:
https://docs.saltstack.com/en/develop/topics/cloud/index.html

multiple VM’s are created with:
salt-cloud -p micro_ec2 minion1 minion2
where the minion_ids are named to minion1 and minion2

In my case the minion_id’s are set to the internal DNS:
ip-172-31-38-18.us-west-2.compute.internal
ip-172-31-38-20.us-west-2.compute.internal

The salt master expects minion_id’s like minion1 and minion2 but the new VM’s are offering the internal DNS as minion_id instead which results in a duplicate key issue for each VM.

**Comment by PKiman** [comment]
The issue seems to be fixed after upgrading from in salt-could 2015.8.1 to salt-could 2015.8.7.
After spawning a new machine the old minionid is still listed in Unaccepted Keys. web-alpha-03-dev.local and ip-172-31-42-164.us-west-2.compute.internal belongs to the same machine.
This is a minor issue, I just need to delete those manually.

sudo salt-key -L
Accepted Keys:
web-alpha-03-dev.local
Unaccepted Keys:
ip-172-31-42-164.us-west-2.compute.internal

**Comment by rallytime** [comment]
Thanks for the updates @PKiman. I'm glad there is an easier solution after the upgrade. I think we should still look into why two IDs are present, even if one is just in the list of unaccepted keys.

**Comment by nstudach** [comment]
I know this issue is old but I think have the same problem just with a newer salt version and digitalocean instead.
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-29-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
cloud profile (etc/salt/cloud.profile.d/do.config):
```
do-ams3-512:
  provider: do
  image: ubuntu-18-04-x64
  size: 512mb
  location: ams3
  private_networking: False
  backups_enabled: False
  ipv6: True
  create_dns_record: False
  grains:
    location: ams3
```
cloud provider (etc/salt/cloud.providers.d/do.config):
```
do:
  driver: digitalocean
  personal_access_token: 1234
  ssh_key_file: /etc/salt/keys/id_rsa
  ssh_key_names: Salt Master SSH Public Key on Digital Ocean
```
cloud (etc/salt/cloud):
```
minion:
  master: master ip adress
```
minion config (etc/salt/minion):
```
master: master ip adress
```
minion_id (etc/salt/minion_id):
`salt-master-v2`

I start with:
```
Accepted Keys:
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

Then create a minion with `$ salt-cloud -p do-ams3-512 test`:

```
Accepted Keys:
test
```
but as soon as you try: `$ salt '*' test.ping`. You get an unaccepted key with the minion_id name:
```
Accepted Keys:
test
Unaccepted Keys:
salt-master-v2
```
I also think this is the reason the reactor is not triggering even though I get the even on the bus:
```
salt/cloud/test/created	{
    "_stamp": "2018-08-07T18:32:17.581379", 
    "driver": "digitalocean", 
    "event": "created instance", 
    "name": "test", 
    "profile": "do-ams3-512", 
    "provider": "do:digitalocean"
}
```
and /etc/salt/master.d/reactor.conf:
```
reactor:
  - 'salt/cloud/*/created':
    - '/srv/reactor/startup_orchestration.sls'
```

I am new to salt so it could also be a misconfiguration.
The whole configuration however is pretty basic.
