### ISSUE TITLE
pkg.installed fails under 2015.8.1 with "-" in the key name

### ISSUE THREAD

**Issue by bocig** [saltstack/salt#28807]
There seems to be a bug in 2015.8.1 with pkg.installed when there is a "-" in the name of the source package key. For example 

``` salt
aspera-pkg:
  pkg.installed:
    - sources:
      - aspera-scp-p2p: salt://aspera/files/aspera-scp-p2p-3.5-linux-64.rpm
```

``` yaml
----------
ID: aspera-pkg
Function: pkg.installed
Result: False
Comment: Unable to cache salt://aspera/files/aspera-scp-p2p-3.5-linux-64.rpm: file not found
Started: 16:29:40.219177
Duration: 2057.501 ms
Changes:
```

My understanding is that the problem is with this line:

```
      - aspera-scp-p2p: salt://aspera/files/aspera-scp-p2p-3.5-linux-64.rpm
```

because of the '-' in the key.

Thanks!

``` yaml
Salt Version:
  Salt: 2015.8.1

Dependency Versions:
  Jinja2: 2.8
  M2Crypto: Not Installed
  Mako: 1.0.1
  PyYAML: 3.10
  PyZMQ: 14.6.0
  Python: 2.7.10 (default, Oct 26 2015, 11:46:29)
  RAET: Not Installed
  Tornado: 4.2.1
  ZMQ: 4.0.5
  cffi: Not Installed
  cherrypy: Not Installed
  dateutil: Not Installed
  gitdb: Not Installed
  gitpython: Not Installed
  ioflo: 1.2.4
  libnacl: Not Installed
  msgpack-pure: Not Installed
  msgpack-python: 0.4.6
  mysql-python: Not Installed
  pycparser: Not Installed
  pycrypto: 2.6.1
  pygit2: Not Installed
  python-gnupg: Not Installed
  smmap: Not Installed
  timelib: Not Installed

System Versions:
  dist: centos 6.4 Final
  machine: x86_64
  release: 2.6.32-358.23.2.el6.x86_64
  system: CentOS 6.4 Final
```

**Comment by jfindlay** [comment]
@bocig, thanks for the report.  Why are you suspecting `-` characters in the key name?  Have you tried keys without `-` in the name?

**Comment by bocig** [comment]
@jfindlay yes we have. It only failed with '-' in the key name. Thanks!

**Comment by lorengordon** [comment]
@bocig, I think yaml gets a little finicky about hyphens in keys. Try putting quotes around the key?

e.g.:
```
aspera-pkg:
  pkg.installed:
    - sources:
      - 'aspera-scp-p2p': salt://aspera/files/aspera-scp-p2p-3.5-linux-64.rpm
```

**Comment by marnovdm** [comment]
I think I have a related issue. Master running 2015.8.1 and with a minion also running 2015.8.1 I have the same error (Unable to cache salt://elasticsearch/elasticsearch-2.0.0.deb: file not found). The same state works on a minion running 2015.5.3 (even with the master running 2015.8.1).

However, for me adding quotes or renaming so we don't need hyphens does not solve the issue. Odd thing is if I manually remove elasticsearch on the server (or fully redeploy the server so it doesn't have elasticsearch installed anymore) it runs fine on a highstate the first time. However, running a highstate again gives the unable to cache error again so it seems to handle it differently depending on if it's installed already or not. Let me know if I can provide any more information to help troubleshoot this.

**Comment by bocig** [comment]
@marnovdm yep it runs fine the first time. We've tried using the quotes but that didn't help. @jfindlay any ideas? thanks!

**Comment by jfindlay** [comment]
@bocig, I have tried to reproduce this but am unsuccessful:

```console
# tree /srv/salt/
/srv/salt/
├── python-pip_1.5.6-5_all.deb
└── test.sls

0 directories, 2 files
```
```salt
# cat /srv/salt/test.sls
install-pip:
  pkg.installed:
    - sources:
      - 'python-pip': salt://python-pip_1.5.6-5_all.deb
```
```yaml
# salt jmoney-main state.apply test
jmoney-main:
----------
          ID: install-pip
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: python-pip
     Started: 16:53:01.446773
    Duration: 8364.998 ms
     Changes:
              ----------
              python-colorama:
                  ----------
                  new:
                      0.3.2-1
                  old:
              python-distlib:
                  ----------
                  new:
                      0.1.9-1
                  old:
              python-html5lib:
                  ----------
                  new:
                      0.999-3
                  old:
              python-pip:
                  ----------
                  new:
                      1.5.6-5
                  old:

Summary for jmoney-main
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   8.365 s
```
```yaml
# salt jmoney-main test.versions
jmoney-main:
    Salt Version:
               Salt: 2015.8.1

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed

    System Versions:
               dist: debian 8.2
            machine: x86_64
            release: 3.16.0-4-amd64
             system: debian 8.2
```

**Comment by bocig** [comment]
@jfindlay we are running into this issue only on CentOS7, cent6 seems to behave ok. It seems you are running this on debian, so might not be seeing the issue.

**Comment by marnovdm** [comment]
@jfindlay @bocig I'm experiencing this on Debian 8 machines as well so it's not just CentOS.

**Comment by marnovdm** [comment]
@jfindlay any updates? I looked at your testcase and noticed that you only applied it once, does it also apply correctly the 2nd time? For me the states work fine the first time as well.

Another difference in your testcase is that @bocig and me are both serving files from a salt://subdirectory/filename, you are hosting it in the root.

I did some more testing and it seems to be related to environments. I had a file roots like this:

    file_roots:
      prod:
        - /srv/salt/states/prod
      accept:
        - /srv/salt/states/accept
        - /srv/salt/states/prod
      test:
        - /srv/salt/states/test
        - /srv/salt/states/accept
        - /srv/salt/states/prod

Note there is no base environment defined. Setup like this it works on the first highstate but a 2nd highstate fails with unable to cache file error.

When defining file roots with a base: environment and restarting the salt-master, like this: 

    file_roots:
      base:
        - /srv/salt/states/prod
        - /srv/salt/states/accept
        - /srv/salt/states/test
      prod:
        - /srv/salt/states/prod
      accept:
        - /srv/salt/states/accept
        - /srv/salt/states/prod
      test:
        - /srv/salt/states/test
        - /srv/salt/states/accept
        - /srv/salt/states/prod

highstates also work correctly the 2nd time. So it seems to use the base environment when validating a cached entry or something? This is not ideal but at least it's a workaround for now.

**Comment by jfindlay** [comment]
@marnovdm, not yet.  I'll do some more testing as you suggest.

**Comment by marnovdm** [comment]
FYI I was able to reproduce this using 2015.8.3 on Debian 8 as well.

**Comment by marnovdm** [comment]
I've tested this in 2016.3.1 and can still reproduce this issue. Removing the base: environment from the master config like I showed above as a workaround still causes 'unable to cache file, file not found' errors. Minions and master upgraded to 2016.3.1 running on Debian 8.5.

**Comment by pirxthepilot** [comment]
I'm also experiencing the same issue, in CentOS 7 and 2016.3.1. I have a couple of states like this:

```
libmemcached:
  pkg.installed:
    - sources:
      - libmemcached: salt://memcached/files/libmemcached-1.0.rpm
```

I have 3 environments: base, dev and prod. The states are in dev and prod; base is empty. When I run state.highstate or state.apply on a server that is in dev or prod, salt tries to get the rpm file from base. (I know this because copying the rpm to base makes the error disappear.)

Error message is same as above: "Unable to cache salt://memcached/files/libmemcached-1.0.rpm: file not found"
