### ISSUE TITLE
boto_route53.present state should have a way to specify multiple IP for a A record

### ISSUE THREAD

**Issue by multani** [saltstack/salt#28813]
route53 console has a simple way to specify manually a A record towards several IP addresses, although the API seems a bit more complicated as shown here : http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets_Examples.html

I'm willing to make a patch, although I'm not sure how to update the boto_route53 module? I originally wanted to make something simple like this:

```yaml
Example A record:
  boto_route53.present:
    - record_type: A
    - name: something
    - zone: myzone.
    - value:
        - ip1
        - ip2
        - ip3
    - ttl: 60
    - profile: route53-editor
```
but it misses all the weights as shown in the Amazon documentation.

Any idea on how to proceed?
