### ISSUE TITLE
user.present react badly if fullname contain a comma

### ISSUE THREAD

**Issue by mscherer** [saltstack/salt#28835]
I just found out that the following snippet will fail:

```
rsyslogd:
  user.present:
    - fullname: Rsyslogd user, salt created
    - shell: /bin/sh
    - home: /srv/logs/
    - system: True
```

Since the fullname contains a comma, applying this state several time result into this:
```
rsyslogd:x:994:992:Rsyslogd user, salt created, salt created, salt created, salt created, salt created,,,:/srv/logs/:/bin/sh
```
I assume that fullname should be checked for ',' since this is used as a separator.
```
$ salt --versions-report
           Salt: 2015.5.5
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.5
```

I didn't tried on newer version
