### ISSUE TITLE
minions not loading modules from returners_dirs (develop)

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#28845]
I have the following in my minion config:
```yaml
module_dirs: [ '/opt/local/salt_dev/_mod/' ]
states_dirs: [ '/opt/local/salt_dev/_state/' ]
returners_dirs: [ '/opt/local/salt_dev/_ret/' ]
```

Since this is my dev box it is running masterless for easier testing of a lot of stuff, also why I am loading extra modules to improve development speed.

exec modules and state modules are loaded file, returners however are not. I never picks them up at all.
