### ISSUE TITLE
Proposed solution to win_repo package matching

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#28918]
## Problem

The **win_repo** uses a combination of `name + version` in windows add/remove programs registry to determine and list versions installed on a minion. I think all the functions of `pkg.*`depends on this matching. Such as `pkg.install` and `pkg.list_available` and so on...

This is a flawed approach because the underlying available information in Windows is neither consistent nor good:
- Different editions of Windows stores information about installed software in different places (both between Windows editions and 32/64 platforms). Salt have become pretty much better at aggregating the different places (there exists a number of issues and fixes related to this). But I wouldn't bet on that it's possible to catch all different variations of places.
- Not all vendors of software supply the information. Not even Microsoft themselves do it! For example, sql server installs with just information in the "name" part of add/remove programs but omits the version information. There are a number of vendors/installers that ignores the version column.
- The "version" information is a string, and salt assumes that it can be sorted like a string and that the top one is the latest. This is not always true, some people gets creative and have versions like version "Enterprise 4.0.1"  or "RC3-Beta 1.0" etc. ;-)

These are just some of the problems and we are all waiting for some real package manager solution to Windows (like OneGet or whatever it will be). But the fact is that the history with decades of software created without a consistent package managing mechanism, no deprecation policies etc. means that even if OneGet comes around and is flawless, not all vendors of software will update their software and so the problem will remain.
## Proposed solution

Let the end user supply two custom functions **per package**, if no functions are supplied then use the current default behavior. This enables us to work around any software's peculiarity and keep the interface in salt to be consistent.
- `is_installed(pkg): bool` - This function takes the information available in a win_repo version node, executes on the minion and tries to determine if this version is installed. This could be checking add/remove programs, some registry key or a file or whatever else.
- `compare(pkg): int` - This is a standard comparison interface method used when sorting the list of software to get the correct order. It should return negative, zero och positive numbers to help salt determine the order between two packages.

**Example**

```
hmailserver:
  functions:
    is_installed: '<custom python code here>'
    compare: '<custom python code here>'
  versions:
    '5.6.4':
      installer: 'https://www.someplace.com/hMailServer-5.6.4-B2283.exe'
      full_name: 'hMailServer 5.6.4-B2283'
      reboot: False
      install_flags: "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART"
      msiexec: False
      uninstaller: 'https://www.someplace.com/hMailServer-5.6.4-B2283.exe'
      uninstall_flags: ' /VERYSILENT /SUPPRESSMSGBOXES /NORESTART'
```

I think this one is for you @UtahDave ;-)
