### ISSUE TITLE
sdb modules are not synced out

### ISSUE THREAD

**Issue by dmyerscough** [saltstack/salt#28947]
Custom sdb modules are not synced out to minions from the master when using `/srv/salt/_sdb`.

**Comment by dmyerscough** [comment]
@whiteinge

**Comment by whiteinge** [comment]
Doh!

**Comment by dmyerscough** [comment]
:)

**Comment by whiteinge** [comment]
I haven't added a sync function before so I'm not sure if there's any additional machinery required. Any chance you could test this?

https://github.com/saltstack/salt/compare/2015.5...whiteinge:sync-sdb

**Comment by dmyerscough** [comment]
Yeah, testing now

**Comment by dmyerscough** [comment]
You need to update this to

```
+def sync_sdb(saltenv=None, refresh=False):
```

This gives the following

```
root@debian:~# salt '*' saltutil.sync_all
debian:
    ----------
    beacons:
    grains:
    log_handlers:
    modules:
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
      sdb.langley.py
    states:
    utils:
```

```
root@debian:/var/cache/salt# find . -name langley*
./minion/files/base/_sdb/langley.py
./minion/extmods/sdb/langley.py
./master/roots/hash/base/_sdb/langley.py.hash.md5
```
