### ISSUE TITLE
pip.installed with Requirements file is useless when test=True (reports changes would be made)

### ISSUE THREAD

**Issue by timwsuqld** [saltstack/salt#28940]
Trying to use pip.installed with a Requirements file, doesn't check if the contents of that file are installed when doing test=True.

This causes state.highstate test=True to always report that it's going to do something, even if nothing is needed. When trying to detect if a highstate file is going to change anything because it always reports it's going to change something we can't detect if there really are going to be changes.

```
          ID: install_requirements
    Function: pip.installed
      Result: None
     Comment: Requirements file '/usr/local/archiver/Requirements' will be processed.
     Started: 12:45:52.384362
    Duration: 1.809 ms
     Changes:   
-------------
Succeeded: 98 (unchanged=1)


```

```
install_requirements:
  pip.installed:
    - requirements: /usr/local/archiver/Requirements
```
