### ISSUE TITLE
boto_secgroup state docs creation error

### ISSUE THREAD

**Issue by chadhs** [saltstack/salt#28942]
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_secgroup.html

these docs need a minor update in that either vpc_id or vpc_name must be defined or the creation of a secgroup will end in error.

to recreate install salt 2015.8.2, create a simple boto_secgroup definition without defining a vpc_id or vpc_name and run the state.

**Comment by cachedout** [comment]
Thanks for this info, @chadhs 

@quantonganh or @ryan-lane Do either of you have any insight on this one, since I know this is a piece of the code you both know somewhat well. :]

**Comment by quantonganh** [comment]
@chadhs: Please show us the error.

```
aws_ec2_secgroup:
  boto_secgroup:
    - present
    - name: salt
    - description: Gateway VPC security group
    - profile: sg
    - rules:
      - ip_protocol: tcp
        from_port: 22
        to_port: 22
        cidr_ip:
          - 0.0.0.0/0
```

I cannot reproduce with the above example:

```
    Function: boto_secgroup.present
        Name: salt
      Result: True
     Comment: Security group salt created.  Created rules on salt security group.
     Started: 00:15:32.693114
    Duration: 1112.218 ms
     Changes:
              ----------
              new:
                  ----------
                  rules:
                      |_
                        ----------
                        cidr_ip:
                            0.0.0.0/0
                        from_port:
                            22
                        ip_protocol:
                            tcp
                        to_port:
                            22
                  secgroup:
                      ----------
                      description:
                          Gateway VPC security group
                      group_id:
                          sg-380d816d
                      name:
                          salt
                      owner_id:
                          xx
                      rules:
                      rules_egress:
                      tags:
                          ----------
             old:
                  ----------
                  rules:
                  secgroup:
                      None
```
