### ISSUE TITLE
CloudLinux 7 changes

### ISSUE THREAD

**Issue by ClaudiuPID** [saltstack/salt#28951]
Some info about the system I am running first:
```
# salt-call grains.get os
local:
    Cloud

# cat /etc/redhat-release
CloudLinux release 7.1 (Vladimir Komarov)

# salt-call --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 7.1 Vladimir Komarov
        machine: x86_64
        release: 3.10.0-233.1.2.lve1.3.33.4.el7.x86_64
         system: CloudLinux 7.1 Vladimir Komarov
```

Packages install and services restart failed on this system.
I had to edit the minion code in order to get things running.
```
grep -nr CloudLinux * | grep -v softlayer
grains/core.py:846:    'cloudserve': 'CloudLinux',
grains/core.py:862:    'CloudLinux': 'RedHat',
modules/rh_service.py:50:        'CloudLinux',
modules/service.py:31:        'CloudLinux',
```
I replaced all ```CloudLinux``` entries with ```Cloud```, this fixed things for me.
I will not make a pull request with this change since it is a trivial one and I don't think this is the correct fix.

**Comment by cachedout** [comment]
Hi @ClaudiuPID Thanks for this information. Could you please be more specific about how services failed to start and packages failed to install? Did it stacktrace? I'm curious about how you came to discover that these functions would work correctly after making the changes you describe above. I'm sure we can get this fixed, but I'm just looking for a little more background to help understand what's happening here. Thanks!

**Comment by ClaudiuPID** [comment]
Hi, this is pretty simple, if the OS is not found in your list (and Cloud is not in your list), it will use /etc/init.d for service management.
CloudLinux is systemd (RHEL 7) so it fails to start/stop services.

As for packages being installed I guess it is the same issue since it does not detect a supported OS. It returns something about __virtual__, I don't have the exact error right now.

**Comment by mtorromeo** [comment]
@ClaudiuPID there's a much cleaner temporary fix that can be used.

Put the following in `/etc/salt/grains`:
```yaml
os: CloudLinux
os_family: RedHat
osmajorrelease: 7
```

These are the grains the are wrong and should be fixed in salt.
