### ISSUE TITLE
cron.present should support magic string @reboot 

### ISSUE THREAD

**Issue by rhertzog** [saltstack/salt#2896]
cron supports using some special strings replacing the first five time matching fields:

```
       Instead of the first five fields, one of eight special strings may appear:

              string         meaning
              ------         -------
              @reboot        Run once, at startup.
              @yearly        Run once a year, "0 0 1 1 *".
              @annually      (same as @yearly)
              @monthly       Run once a month, "0 0 1 * *".
              @weekly        Run once a week, "0 0 * * 0".
              @daily         Run once a day, "0 0 * * *".
              @midnight      (same as @daily)
              @hourly        Run once an hour, "0 * * * *".
```

The @reboot one is special and can't be emulated with the 5 usual fields thus it would be nice if there was a way for cron.present to use it.

**Comment by cmtonkinson** [comment]
Quick & dirty workaround is to set four of the fields to empty strings or whitespace:

```
    - minute: "@reboot"
    - hour: ""
    - daymonth: ""
    - month: ""
    - dayweek: ""
```

**Comment by sjorge** [comment]
Looks like this has been implemented

**Comment by didip** [comment]
@sjorge Do you happen to have an example snippet on how to use @reboot? I'd appreciate it.

**Comment by sjorge** [comment]
@didip I only have one location where I use it:

```yaml
network.route::lx-helper:
  file.directory:
    - name: /etc/inet
  cron.present:
    - name: /native/usr/bin/awk '!/^($|[:space:]*#)/{ print "/native/usr/sbin/route add "$0 }' /etc/inet/static_routes | sh
    - special: '@reboot'
```

But it's a very specific usage, in my case due to some lacking tooling support when running Ubuntu/CentOS under SmartOS using lxbranded zones... the routes are missing after a reboot. I inject them using a cron that fires on @reboot.
