### ISSUE TITLE
xfs.devices failing on ubuntu 

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#28986]
getting an error when trying to use xfs.devices on an ubuntu system. 

here is the output I am getting
```
salt 'ctrl*' xfs.devices
ctrl.wolfcloud.bad4.us:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1036, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/xfs.py", line 353, in devices
        return _blkid_output(out['stdout'])
      File "/usr/lib/python2.7/dist-packages/salt/modules/xfs.py", line 330, in _blkid_output
        data[dev.pop("devname")] = dev
    KeyError: 'devname'
```

I did notice that it is trying to use blkid -o export as it's input data. 

here is the output i get from that command 
```
UID=wlaQNS-ywx2-UqzM-hw1m-Q9oT-pR0l-YtSzTg
TYPE=LVM2_member

UUID=ea4e76b0-7233-4f4f-a686-393d4aacff6c
TYPE=ext2

UUID=5cccc3cc-30fc-4f0d-8c54-10b9d4319b5f
TYPE=ext3

UUID=09bea5ff-efb1-43c9-9b6e-107d2b2d34cd
TYPE=swap

UUID=5QJflj-QzMq-3NMJ-d3f0-WGPo-loun-zgLxVi
TYPE=LVM2_member

UUID=1UL6ao-H2oY-av1H-5egU-Buw1-nPT5-noD4nx
TYPE=LVM2_member

UUID=620238da-84ff-4f32-8db5-9566a44117c6
TYPE=xfs

UUID=0fb61f15-6068-4443-87b6-718c8cfb66f4
TYPE=xfs
```

and of coarse version info

```
salt 'ctrl*' test.versions
ctrl.wolfcloud.bad4.us:
    Salt Version:
               Salt: 2015.8.1

    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: 0.9.1
             PyYAML: 3.10
              PyZMQ: 14.4.0
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: 1.1.2
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-67-generic
             system: Ubuntu 14.04 trusty
```
