### ISSUE TITLE
Proposal: Add command flags to display all content for roster

### ISSUE THREAD

**Issue by netroby** [saltstack/salt#28993]
Please add command .like 

```
salt roster
```

or

```
salt-ssh roster
```

Read and output content for /etc/salt/roster

```
hk:
    host: hk.example.com
ks:
    host: ks.example.com
hi:
    host:.hi.example.com
hz:
    host: hz.example.com
p2:
    host: p2.example.com
```
