### ISSUE TITLE
debconf.set doesn't support "prereq" in states

### ISSUE THREAD

**Issue by olfway** [saltstack/salt#29001]
```salt
zabbix-server_debconf:
  debconf.set:
    - name: {{ zabbix.server.pkg}}
    - data:
        'zabbix-server-mysql/internal/skip-preseed': {'type': 'boolean', 'value': True}
        'zabbix-server-mysql/dbconfig-install': {'type': 'boolean', 'value': False}
        'zabbix-server-mysql/dbconfig-upgrade': {'type': 'boolean', 'value': False}
    - prereq:
      - pkg: zabbix-server
```
prints warning:
```yaml
----------
          ID: zabbix-server_debconf
    Function: debconf.set
        Name: zabbix-server-mysql
      Result: None
     Comment:
     Started: 14:31:19.554909
    Duration: 291.696 ms
     Changes:
              ----------
              zabbix-server-mysql/dbconfig-install:
                  New value: false
              zabbix-server-mysql/dbconfig-upgrade:
                  New value: false
              zabbix-server-mysql/internal/skip-preseed:
                  New value: true
    Warnings: '__prerequired__' is an invalid keyword argument for
              'debconf.set'. If you were trying to pass additional data to be
              used in a template context, please populate 'context' with 'key:
              value' pairs. Your approach will work until Salt Carbon is out.
              Please update your state files.
```
I'm using salt 2015.8.1 (Beryllium)
