### ISSUE TITLE
sls file interpretation issue.

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#29007]
hello

if you set a variable in sls file and just use the same name without brackets the interpretation will substitute the 'variable' with value.

for example:
```salt
{% set eth1 = salt['grains.get']('eth1', '') %}
system:
    network.system:
      - enabled: true
      - hostname: {{ grains['id'] }}
      - gateway: {{ route_primary }}
      - gatewaydev: eth1
      - nozeroconf: true
      - require_reboot: true
````
the gatewaydev will be IP instead of 'eth1' string.

workaround:
using another variable name.

According to my knowledge if I want to use the variable I should use {{ eth1 }} form which works but not explicitly.
I use salt-2015.8.1

**Comment by jfindlay** [comment]
@BalintSzigeti, thanks for the report.  I cannot reproduce this.  Is there anything else I should try?
```salt
# cat /srv/salt/test.sls
{% set var = 'val'%}

test:
  cmd.run:
    - name: var
```
```yaml
# salt jmoney-main state.apply test
jmoney-main:
----------
          ID: test
    Function: cmd.run
        Name: var
      Result: False
     Comment: Command "var" run
     Started: 10:32:33.819779
    Duration: 16.669 ms
     Changes:
              ----------
              pid:
                  7302
              retcode:
                  127
              stderr:
                  /bin/bash: var: command not found
              stdout:

Summary for jmoney-main
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  16.669 ms
ERROR: Minions returned with non-zero exit code
```
```yaml
# salt jmoney-main test.versions
jmoney-main:
    Salt Version:
               Salt: 2015.8.1

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed

    System Versions:
               dist: debian 8.2
            machine: x86_64
            release: 3.16.0-4-amd64
             system: debian 8.2
```
