### ISSUE TITLE
Error retrieving data['name'] dict from salt/cloud/*/created/

### ISSUE THREAD

**Issue by cgaley** [saltstack/salt#29018]
I have been testing this to no avail. I am attempting to trigger a state that updates some custom modules dependencies. The event has the proper field but I am getting a not found in dict error. I initially thought this might be related to #28877 

Triggering Event:

```
    salt/cloud/<name>/created   {
    "_stamp": "2015-11-18T19:04:22.586022", 
    "event": "created instance", 
    "instance_id": "<instance>", 
    "name": "<name>", 
    "profile": "<profile>", 
    "provider": "<provider>:ec2"
}
```

```
    2015-11-18 19:04:22,590 [salt.utils.templates][ERROR   ][4901] Rendering exception occurred :Jinja variable 'name' is undefined
    2015-11-18 19:04:22,590 [salt.utils.reactor][ERROR   ][4901] Failed to render "/srv/reactor/created.sls": 
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/utils/reactor.py", line 53, in render_reaction
    data=data) 
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 279, in render_template
    template, self.rend, self.opts['renderer'], **kwargs)  
      File "/usr/lib/python2.7/site-packages/salt/template.py", line 94, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
      File "/usr/lib/python2.7/site-packages/salt/renderers/jinja.py", line 333, in render
    **kws) 
       File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 180, in render_tmpl
    output = render_str(tmplstr, context, tmplpath) 
       File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
    buf=tmplstr)
    SaltRenderError: Jinja variable 'name' is undefined
```

.sls:

```
{# When a server finishes deploying, run init #}
init_sls:
  local.state.apply:
    - tgt: {{ data['name'] }}
    - arg:
      - init
```

reactor.conf:

```
reactor:
  - 'salt/cloud/*/created':
    - /srv/reactor/created.sls
```

Salt Report:

```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.20.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

**Comment by jfindlay** [comment]
@cgaley, thanks for the report.

@techhat

**Comment by cgaley** [comment]
I tested this again with just {{ name}} which also doesn't work.

I am attempting to create a test now which will give me the context to see if/how the event data shows up

**Comment by rallytime** [comment]
@cgaley Were you able to get a closer look on the event data? Are you still running into this issue?

**Comment by rallytime** [comment]
@cgaley I am not able to reproduce this error on 2015.8.1, nor the HEAD of the 2015.8 branch. Here's my simple set-up and results:

Relevant master.conf file:
```
reactor:
  - 'salt/cloud/*/created':
    - '/srv/reactor/test.sls'
```
/srv/reactor/test.sls:
```
test reactor:
  cmd.test.ping:
    - tgt: {{ data['name'] }}
```
Master logs showing successful `created` event trigger:
```
[DEBUG   ] Gathering reactors for tag salt/cloud/nt-test-0/created
[DEBUG   ] Compiling reactions for tag salt/cloud/nt-test-0/created
[DEBUG   ] compile template: /srv/reactor/test.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[PROFILE ] Time (in seconds) to render '/srv/reactor/test.sls' using 'jinja' renderer: 0.00215911865234
[DEBUG   ] Rendered data from file: /srv/reactor/test.sls:
test reactor:
  cmd.test.ping:
    - tgt: nt-test-0

<snipped>

[INFO    ] Got return from nt-test-0 for job 20160113010315511881
[DEBUG   ] Sending event - data = {'fun_args': [], 'jid': '20160113010315511881', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2016-01-13T01:03:15.670460', 'fun': 'test.ping', 'id': 'nt-test-0'}
```
Versions Report:
```
# salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.1.5-x86_64-linode61
         system: Ubuntu 14.04 trusty
```
Can you post the contents of your `init` state? Is it possible that something in that state is causing the error you're seeing?

**Comment by rallytime** [comment]
I also just tried with `state.apply` in my reactor file, just to be sure it wasn't that instead and it also worked:
```
[DEBUG   ] Rendered data from file: /srv/reactor/test.sls:
test reactor:
#  cmd.test.ping:
  local.state.apply:
    - tgt: nt-test-2
    - arg:
      - noop
<snipped>
[INFO    ] Got return from nt-test-2 for job 20160113013406257938
[DEBUG   ] Sending event - data = {'fun_args': ['noop'], 'jid': '20160113013406257938', 'return': {'test_|-no-op_|-foo_|-nop': {'comment': 'Success!', 'name': 'foo', 'start_time': '01:34:06.509860', 'result': True, 'duration': 0.954, '__run_num__': 0, 'changes': {}}}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2016-01-13T01:34:06.611472', 'fun': 'state.apply', 'id': 'nt-test-2', 'out': 'highstate'}
```

**Comment by cgaley** [comment]
I'll check again I have reworked a lot of that code so  I will see if I still have an example.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Tue, Jan 12, 2016 at 5:25 PM -0800, "Nicole Thomas" <notifications@github.com<mailto:notifications@github.com>> wrote:


@cgaley<https://github.com/cgaley> I am not able to reproduce this error on 2015.8.1, nor the HEAD of the 2015.8 branch. Here's my simple set-up and results:

Relevant master.conf file:

reactor:
  - 'salt/cloud/*/created':
    - '/srv/reactor/test.sls'


/srv/reactor/test.sls:

test reactor:
  cmd.test.ping:
    - tgt: {{ data['name'] }}


Master logs showing successful created event trigger:

[DEBUG   ] Gathering reactors for tag salt/cloud/nt-test-0/created
[DEBUG   ] Compiling reactions for tag salt/cloud/nt-test-0/created
[DEBUG   ] compile template: /srv/reactor/test.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[PROFILE ] Time (in seconds) to render '/srv/reactor/test.sls' using 'jinja' renderer: 0.00215911865234
[DEBUG   ] Rendered data from file: /srv/reactor/test.sls:
test reactor:
  cmd.test.ping:
    - tgt: nt-test-0

<snipped>

[INFO    ] Got return from nt-test-0 for job 20160113010315511881
[DEBUG   ] Sending event - data = {'fun_args': [], 'jid': '20160113010315511881', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2016-01-13T01:03:15.670460', 'fun': 'test.ping', 'id': 'nt-test-0'}


Versions Report:

# salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.1.5-x86_64-linode61
         system: Ubuntu 14.04 trusty


Can you post the contents of your init state? Is it possible that something in that state is causing the error you're seeing?

-

**Comment by oogali** [comment]
I just pushed my systems up to 2015.8.3, and I'm still facing the same issue.

```
2016-01-13 18:18:40,990 [salt.utils.templates                                      ][ERROR   ][43895] Rendering exception occurred :Jinja variable 'data' is undefined
2016-01-13 18:18:40,992 [salt.state                                                ][CRITICAL][43895] Rendering SLS 'base:orchestration.cloud.created' failed: Jinja variable 'data' is undefined
```

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.11 (default, Jan  9 2016, 01:14:32)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: 1.2.1
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.23.0
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: amd64
        release: 10.1-RELEASE
```

The referenced SLS:
```
saltutil.sync_all:
  salt.function:
    - tgt: {{ data['name'] }}
    - reload_modules: True

saltutil.refresh_pillar:
  salt.function:
    - tgt: {{ data['name'] }}

mine.update:
  salt.function:
    - tgt: {{ data['name'] }}

highstate_run:
  salt.state:
    - tgt: {{ data['name'] }}
    - highstate: True
    - require:
      - salt: saltutil.sync_all
      - salt: saltutil.refresh_pillar
      - salt: mine.update
```

**Comment by rallytime** [comment]
@oogali I think you're seeing a different issue that the one discussed here, as you noted. Would you mind opening a new issue, so we can track the progress of each individually? Also, when you open the new issue, can you also post what you reactor file looks like?

**Comment by oogali** [comment]
This activity got my gears going, and after poking around, I think my issue might be user error (aka me) -- I may have found a bad scope reference in my reactor files.

I'll keep digging, and if it turns out to be upstream, I'll open a new issue.

**Comment by rallytime** [comment]
@oogali Sounds good! :)

**Comment by Athos85** [comment]
I don't know whats the status of this issue. But I am quite interested in it specially because I am affected as well. 

I can complete reproduce the issue posted by @cgaley and I am unable to use the salt event salt/cloud/<name>/created

Maybe it helps if I post my informations:

**Versions Information**
`salt --versions-report
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo
`

**/etc/salt/master.d/reactor.conf**
`reactor:

  - 'salt/cloud/*/created':
    - /srv/salt/reactor/configure_new_cloud_vm.sls
`

**reactor/configure_new_cloud_vm.sls**
`install_emacs_on_new_minion:
  cmd.test.ping:
    - tgt: {{ data['name'] }}
`

**less /var/log/salt/master**

`2018-02-13 14:42:48,185 [salt.utils.reactor:95  ][ERROR   ][10965] Failed to render "/srv/salt/reactor/configure_new_cloud_vm.sls":
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/reactor.py", line 86, in render_reaction
    data=data)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 338, in render_template
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/jinja.py", line 70, in render
    **kws)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 167, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 436, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'name'
`

**Comment by piersf** [comment]
Was this issue ever resolved? I am getting really similar error:

` "Rendering SLS 'base:reactors.startup' failed: Jinja variable 'data' is undefined"`

My SLS reactors/startup.sls file looks like:

```
sync_all:
  salt.function:
    - name: saltutil.sync_all
    - tgt: {{ data['id'] }}
    - reload_modules: True
```

According to the documentation in https://docs.saltstack.com/en/latest/topics/reactor/index.html#wheel-reactions, this should work. Is the documentation wrong or do we have something wrong in our state file?

Thanks,
