### ISSUE TITLE
Windows - Illegal character allowed in file cache

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#29025]
I am trying to use file.managed to download a file from a web API to a Windows 2012 server.  Saltstack is unable to download and cache the file because the URL for the file contains a colon "\id:32035" which is an invalid character for directories in Windows.

Colons should be replaced for the purpose of the file cache with some other valid character.

```
          ID: Learner.Api-download
    Function: file.managed
        Name: D:\data\webs\Learner.Api.nupkg
      Result: False
     Comment: Unable to manage file: [Error 267] The directory name is invalid: u'c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\base\\salt-master_FFFFFFFFFF@teamcity.domain.com\\httpAuth\\app\\rest\\builds\\id:32035'
     Started: 15:12:21.186000
    Duration: 16.0 ms
     Changes:
```

```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 2012Server
         system: 2012Server 6.2.9200  Multiprocessor Free
```
