### ISSUE TITLE
salt-minion reports different version of tornado than the one installed on the system

### ISSUE THREAD

**Issue by syedaali** [saltstack/salt#29033]
I have python tornada 4.2.1-1 on the system, but salt-minion reports Tornado: 3.2, not sure where salt-minion is getting it's tornado version from? (May be related to #29032 )

```
$ sudo  dpkg --list | grep -i tornado
ii  python-tornado                   4.2.1-1                          amd64        scalable, non-blocking web server and tools
```

``` yaml
$ sudo salt-minion --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 3.2
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-40-generic
         system: Ubuntu 14.04 trusty
```
