### ISSUE TITLE
Failed to do pkg.refresh_db on Windows minion on 2015.8.1

### ISSUE THREAD

**Issue by efficks** [saltstack/salt#29046]
@jfindlay @eliasp , I've got the same problem as @nimishp on #28162 on Windows XP 32 bit with saltstack 2015.8.1 on the master and the minion.

When running the update : 
```
salt 'hostname' pkg.refresh_db
```

I've got : 
```
hostname:
```
without any other output

Running : 
```
sudo salt 'SR-SIC-GES1A' cmd.run 'C:\salt\salt-call -c C:\salt\conf -l debug pkg.refresh_db'
```

Outputs : 
```
hostname:
    [DEBUG   ] Reading configuration from C:\salt\conf\minion
    [DEBUG   ] Configuration file path: C:\salt\conf\minion
    [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
    [DEBUG   ] Reading configuration from C:\salt\conf\minion
    [DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506')
    [DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5884)
    [DEBUG   ] Setting zmq_reconnect_ivl to '5884ms'
    [DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506', 'aes')
    [DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506')
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506', 'clear')
    [DEBUG   ] Decrypting the current master AES key
    [DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
    [DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
    [DEBUG   ] LazyLoaded jinja.render
    [DEBUG   ] LazyLoaded yaml.render
    [DEBUG   ] LazyLoaded pkg.refresh_db
    [DEBUG   ] LazyLoaded cp.cache_dir
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506', 'aes')
    [DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506')
    [INFO    ] Caching directory 'win/repo-ng/' for environment 'base'
    [DEBUG   ] LazyLoaded jinja.render
    [DEBUG   ] LazyLoaded yaml.render
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506', 'aes')
    [DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'SR-SIC-GES1A', 'tcp://10.133.32.206:4506')
    [DEBUG   ] LazyLoaded nested.output
    local:
```

I'm unable to use the win repo since a switch to 2015.5 or 2015.8
I've try to remove completly the minion on the host and reinstall it without success.

Minion version : 
```
    Salt Version:
               Salt: 2015.8.1

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist:
            machine: x86
            release: 2003Server
             system: 2003Server 5.2.3790 SP2 Multiprocessor Free
```

Master version : 
```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.3 (default, Aug  1 2012, 05:14:39)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-29-virtual
         system: Ubuntu 12.04 precise
```

After some reading, i've change parameters on the master for the winrepo. I've got exactly the same issue.

```
#####     Windows Software Repo settings #####
##############################################
# Location of the repo on the master:
win_repo_dir: '/srv/salt/win/repo'

#
# Location of the master's repo cache file:
winrepo_cachefile: '/srv/salt/win/repo/winrepo.p'
```

**Comment by jfindlay** [comment]
@efficks, thanks for the report.  Since 2003 and XP are no longer supported by Microsoft, SaltStack has no plans to provide updates for these platforms either.

**Comment by lorengordon** [comment]
@efficks, try setting `winrepo_cachefile: 'winrepo.p'`. In 2015.8, the value of that parameter is appended to `winrepo_dir`.

**Comment by efficks** [comment]
@lorengordon I've try this and it does not works...
Weird thing, all my minion on 2014 version works properly!!!

@jfindlay, I'm pretty sure it's not a Windows XP issue.

**Comment by lorengordon** [comment]
@efficks, it's not weird, the winrepo code went through significant updates for 2015.8 to allow for minion-side rendering. One more thing in your config, `win_repo_dir` is incorrect. The correct parameter is `winrepo_dir`.

Second, you have to generate the repo on the master, then refresh the db on the minion. Here are the commands you'd run on the master to do that:

```
salt-run winrepo.genrepo
salt 'winminion' pkg.refresh_db
```

**Comment by twangboy** [comment]
@efficks Your command also looks a little strange:
```
sudo salt 'SR-SIC-GES1A' cmd.run 'C:\salt\salt-call -c C:\salt\conf -l debug pkg.refresh_db'
```
Might I suggest the following instead:
```
sudo salt 'SR-SIC-GES1A' pkg.refresh_db
```

**Comment by jfindlay** [comment]
ping @twangboy, @TheBigBear

**Comment by twangboy** [comment]
@efficks @lorengordon All right, I think I see the problem here.

The way the pkg repo works with 2015.8.1 is as follows.
Package definition files (.sls) are stored on github. They are pulled down from github by running the following command on the master:
```
salt-run winrepo.update_git_repos
```
This will pull down the software definition files for older minions (salt-winrepo) and for 2015.8 and newer minions (salt-winrepo-ng). They are stored in the `file_roots` under `win/repo` and `win/repo-ng` accordingly.

The next step (if you have older minions) is to create the message pack file for the repo (winrepo.p). This is done by running the following command on the master:
```
salt-run winrepo.genrepo
```
If you have only 2015.8 and new minions, you no longer need to run `salt-run winrepo.genrepo` on the master.

Lastly, you need to refresh the minion database by running the following command on the master:
```
salt '*' pkg.refresh_db
```
On 2015.5 and older minions, this will copy the `winrepo.p` file down to the minion.
On 2015.8 and newer minions, this will copy all the software definition files (.sls) down to the minion and then create a `winrepo.p` file on the minion. The reason this is done there is because we added support for jinja in 2015.8 and in order to process the minion's grains, the `.sls` files needed to be processed on the minion.

NOTE: Every time you run `salt-run winrepo.update_git_repos` or you create your own or edit existing software definition files in the repo, you need to refresh the database on your minions. For 2015.5 minions, that means running `salt-run winrepo.genrepo` and then `salt '*' pkg.refresh_db`. For 2015.8 minions it is just `salt '*' pkg.refresh_db`.

From what I'm seeing here, it looks like your repo folders on your master are empty. You have no software definition files. You either need to create your own or pull down the one's we're maintaining by running `salt-run winrepo.update_git_repos` on your master. Then `pkg.refresh_db` will have something to pull down.

**Comment by twangboy** [comment]
@efficks This would also explain why `pkg.refresh_db` wasn't working in issue https://github.com/saltstack/salt/issues/28162 . A 2015.5 master doesn't know anything about `salt-winrepo-ng`.

**Comment by lorengordon** [comment]
@twangboy, that's a great explanation, thanks for taking the time to write it up! I know the docs have been updated to try to address these changes, but this explanation made much more sense to me than much of what is in the doc pages.

**Comment by nigelsim** [comment]
@twangboy can you please elaborate on how to setup a repo without using git? I used to be able to place the SLS files directly in `win/repo` and running `winrepo.genrepo`, but when I do the same into `win/repo-ng` the SLS files don't get synced to the minion on `pkg.refresh_db`.

**Comment by twangboy** [comment]
@nigelsim 

Assuming your file_roots is the default (`/srv/salt`):

If you have a 2015.5 server or below, all the files go into `/srv/salt/win/repo`

If you have a 2015.8 server or above, you put SLS files in two places.
1. `/srv/salt/win/repo` for 2015.5 and below minions
2. `/srv/salt/win/repo-ng` for 2015.8 and above minions.

**Comment by twangboy** [comment]
@nigelsim What are the salt versions for your master and minions?

**Comment by nigelsim** [comment]
@twangboy Thanks, all working now. So <= 2015.5 synchronises salt://win/repo and >=2015.8 synchronises salt://win/repo-ng? I just got caught up overthinking how this all worked because of the `winrepo_dir` and `winrepo_cachefile` variables. I don't have a `file_roots` value (we structured it 2 years ago so that wasn't in the forefront of my mind), so I created a tree that would expose the correct salt URL.

I am on 2015.8.3 for both the master and the minions.

**Comment by twangboy** [comment]
@nigelsim I'm glad it's working for you.
@effics Is this still a problem for you?

**Comment by droptables** [comment]
I'm having some trouble with this topic as well.

I've got 2015.8.8-2 minion on Windows Server 2012 R2 with a 2015.5.8 master.

The minion uses `C:\salt\var\cache\salt\minion\files\base\win\repo-ng` 

When I run `salt minion pkg.refresh_db` it creates the expected `winrepo.p` file with the correct contents on the minion without running winrepo.genrepo.

If I create `/srv/salt/win/repo-ng/program/init.sls` then do `salt-run winrepo.genrepo` it creates the `winrepo.p` on the mater and has 'program' in the file.  

If i `pkg.refresh_db` on the minion, the winrepo.p file does not get updated with the contents of the winrepo on the master.

The sls files are on the minion as well but the winreop.p cache file does not seem to be getting updates correctly

Am i missing something?  Thanks!

**Comment by twangboy** [comment]
@droptables I would recommend upgrading your master to a 2015.8 version... preferrably the same or newer than your minion. We don't support older masters with newer minions.

The way pkg.refresh_db works in 2015.8 is that it should pull the contents of repo-ng down to the local minion and generate the winrepo.p file locally instead of copying down the winrepo.p from the master. We left the winrepo.genrepo runner on the master so that it can still support 2015.5 and below minions.

**Comment by droptables** [comment]
Updated but it will still not add my custom `/srv/salt/win/repo-ng/program/init.sls` to the winrepo.

Where is decent documentation for making custom windows package installers?

**Comment by twangboy** [comment]
@droptables Here's a link to the documentation:
https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#creating-a-package-definition-sls-file

Also, names are important. If you have duplicate names (full_name, name, etc) it's uncertain which one will win. Could there possibly be a naming conflict with an existing package in winrepo? Can you post the software definition in `../program/init.sls`?

**Comment by droptables** [comment]
@twangboy In `/srv/salt/win/repo-ng/firefox/init.sls` i have the following:

(actually program replaced with 'firefox' for obfuscation. The program name is unique in the repository)

pkg.refresh will update the winrepo.p file but when i open it i see no 'firefox' and it cannot find the package via pkg.install

```
firefox:
  1.2.1370:
    installer: 'salt://win/repo-ng/firefox/firefox.msi'
    full_name:FirefoxBrowser
    reboot: False
    msiexec: True
    install_flags: '/l*v'
    install_flags: 'C:\Install.log'
    install_flags: 'PIDKEY=KEY'
    install_flags: '/quiet'
    uninstaller: 'msiexec.exe'
    uninstall_flags: '/quiet'
```

**Comment by twangboy** [comment]
@droptables Are you opening winrepo.p on the server or on the minion?

**Comment by TheBigBear** [comment]
@droptables as a starter any version numbers NEED to be in single quotes, as per doc. (any that end in zero) are (almost?) guaranteed to fail it they aren't in single quotes.
you have no space between full_name: ^ packagename (but that might not matter for yaml or might just be a result of your obfuscation, just wanted to point it out - just in case)

and as @twangboy said names matter very much to winrepo, make absolutely sure that the windows uninstall registry entries name of the package matches your full_name 100% case and space and all, as per docs.

and I suspect when testing your uninstaller you might also run into surprises. 
I suggest and re-read the docs on uninstallers in the case of msiexec = true. you usually have either the msi itself listed in the uninstaller field (see 7zip as a example), or alternatively the GUID of the installed pkg in the uninstaller filed (again see te 7zip sample in the docs showing both scenarios)

Using msiexec; true and the using msiexec.exe in the uninstaller is not an intended combination. although I suspect you might get away with it, if you then also added the /x {GUID}  to the uninstall_flags: field.

**Comment by twangboy** [comment]
@droptables Also, I'm not sure how having multiple `install_flags` entries is handled by winrepo. I would guess that the last one wins. So, I would suggest something like this for install_flags:

```
install_flags: '/l*v C:\Install.log PIDKEY=KEY /quiet'
```

**Comment by TheBigBear** [comment]
@twangboy, good one 'https://github.com/saltstack/salt/issues/29046#issuecomment-220671634' I missed that one entirely. ;-)

**Comment by droptables** [comment]
Thanks @twangboy and @TheBigBear the following state file worked for me.  It ended up being the `install_flags`  it needs it in one line, i had a few.  I didn't realize my state file was wrong causing it to not get rendered.

Is there logs somewhere that would point towards a failed render of my init.sls when doing `pkg.refresh_db`?

```
program:
  '1.2.1370':
    installer: 'salt://win/repo-ng/program/ProgramProtect_x64.msi'
    full_name: ProgramProtect
    reboot: False
    msiexec: True
    install_flags: '/l*v C:\Install.log PIDKEY=KEY /quiet'
    uninstaller: 'msiexec.exe'
    uninstall_flags: '/quiet'
```

i'll get the uninstaller to work now that i know why my `init.sls` was wrong.

```
minion1:
    ----------
    Program Protect
        ----------
        new:
            1.2.1370.99
        old:
    _comment:
        Registry not updated.
```

:)
