### ISSUE TITLE
incorrect hash reported - file.managed

### ISSUE THREAD

**Issue by AkhterAli** [saltstack/salt#29056]
``` python
Master:
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 4.1.10-17.31.amzn1.x86_64
```

```
[root@artweb01 tmp]# salt-minion --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 4.1.10-17.31.amzn1.x86_64
```

``` python
Tomcat:
    file.managed:
        - source: {{ pillar['modesto_tomcat7']['download_link'] }}
        - source_hash: md5=84cc20cfcecc0a8953f8c5fee4e2d4dd
        - name: {{ pillar['modesto_tomcat7']['download_location'] }}
        - user: root
        - group: root
        - mode: 644
        - unless: ls -lah {{ pillar['modesto_tomcat7']['download_location'] }}
```

Now this is for tomcat7 .tar.gz.  The actual hash is '5e4cb4c1582e73ad10563f26729c39b6' but Salt insists it's 84cc20cfcecc0a8953f8c5fee4e2d4dd

The download link is 'http://www.carfab.com/apachesoftware/tomcat/tomcat-7/v7.0.65/bin/apache-tomcat-7.0.65.tar.gz'

This may be due to the fact that reload_module isn't set to 'True,' but that parameter does not exist in file.managed module and salt may be checking md5 upon file creation rather than download completion.

I did try to capture the md5 when the download is initiated, however I did not see the same hash salt reported.  Also salt reported the same hash three times, so at least it's consistent.

I did solve the issue with a cmd.run which has reload_module parameter but I feel in this case it should also be included in file.managed.
