### ISSUE TITLE
FX2 proxy-minion chassis state configuring wrong enclosure name

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#29061]
I applied a chassis state to my enclosures over the past few days, and while the output suggested it applied the ``chassis_name`` properly, they're all actually now called "CHASSIS-SETUP".

Here is the state:
```
{% set details  = salt['pillar.get']('proxy:chassis', {}) %}
chassis-setup:
  dellchassis.chassis:
    - chassis_name: {{ details['name'] }}
    - datacenter: {{ details['datacenter'] }}
```

Corresponding pillar data:
```
proxy:
  host: cptbc6en1.ut1.cpt.adobe.net
  chassis:
    name: cptbc6en1.ut1.cpt.adobe.net
    datacenter: UT1
```

Looks like the code for setting the name may have the wrong argument position? In any case, I now have 170 chassis enclosures called "CHASSIS-SETUP"

@cro @Ch3LL
