### ISSUE TITLE
Can't define multiple commented cron

### ISSUE THREAD

**Issue by dr4Ke** [saltstack/salt#29082]
I would like to set commented cron jobs. I know it sounds stupid. My use case is that I enable other users to run some cron jobs manually, for whatever reason, via a script that read a given user's crontab and executes the selected command in an environment similar to the crontab one, so that the command has exactly the same behavior whether it's run by crond or by the other user.

Now I want to install some cron jobs that run commands under development. I don't want the cron daemon to run them, so I comment these jobs. The user that develops the command can run it, in the same way as above, then test the result of its command before I can enable it in the crontab.

Say we have these states:
```
cron_1:
  cron.present:
    - name: my_cmd_1
    - identifier: cron_1
    - user: user1
    - minute: '#0'
    - hour: '17'

cron_2:
  cron.present:
    - name: my_cmd_2
    - identifier: cron_2
    - user: user1
    - minute: '#0'
    - hour: '17'
```

The two states are successfully run, but the crontab contains just the last one:
```
# Lines below here are managed by Salt, do not edit
# SALT_CRON_IDENTIFIER:cron_2
#0 17 * * * my_cmd_2
```

The result should be:
```
# Lines below here are managed by Salt, do not edit
# SALT_CRON_IDENTIFIER:cron_1
#0 17 * * * my_cmd_1
# SALT_CRON_IDENTIFIER:cron_2
#0 17 * * * my_cmd_2
```

The issue lies in the `list_tab` function, when it test if the line is a comment. If the job is commented, the cron is totally ignored, thus deleted when the new file is written.

The question is: do we want to manage commented cron jobs? And if so, how do we differentiate, for sure, a comment line from a commented job?
