### ISSUE TITLE
Salt-cloud 2015.8.0 - del_*_vols_on_destroy does not work according to docs

### ISSUE THREAD

**Issue by jessicabreck** [saltstack/salt#29101]
The documentation reads as such(https://docs.saltstack.com/en/latest/topics/cloud/aws.html):

```
  volumes:
    - { size: 100, device: /dev/sde, type: gp2 }
    - { size: 100, device: /dev/sdf, type: gp2 }
  del_root_vol_on_destroy: True
  del_all_vols_on_destroy: True
```

If you write a file as above, it ignores these values, and does not delete the EC2 volumes.

If you write the file as follows:

```
  del_root_vol_on_destroy: True
  del_all_vols_on_destroy: True
  volumes:
    - { size: 100, device: /dev/sde, type: gp2 }
    - { size: 100, device: /dev/sdf, type: gp2 }
```
It appears that del*_on_destroy must be before the volumes, not after.

This is financially dangerous, as the failure is completely silent, and leads to orphaned EBS volumes. In our case, I had to clean up several hundred from salt-stack deploys.

**Comment by rallytime** [comment]
@jessicabreck Sorry for the trouble here. That is interesting that the change in order affects the behavior of those options. Thanks for pointing that out. We'll get this fixed up.

**Comment by rallytime** [comment]
@jessicabreck Can you also post the output of `salt-cloud --versions-report` here?

**Comment by jessicabreck** [comment]
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.3.1
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.20.3
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-85-virtual
         system: Ubuntu 12.04 precise

**Comment by rallytime** [comment]
I've updated the doc example here to hopefully aid others in avoiding this situation. I haven't worked out where the bug is though, yet.

**Comment by pass-by-value** [comment]
@jessicabreck  and @rallytime 

I am wondering if you are able to make use of `block_device_mappings` instead? That creates and deletes volumes as expected. It is specified under [optional settings](https://docs.saltstack.com/en/latest/topics/cloud/aws.html#optional-settings) in the docs.

```yaml
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 100
    - DeviceName: /dev/sdb
      Ebs.VolumeType: gp2
      Ebs.VolumeSize: 10
```

FYI: On the most recent develop volumes specified using `volumes` aren't deleted even if you place `  del_root_vol_on_destroy: True` and `del_all_vols_on_destroy: True` above `volumes`.
