### ISSUE TITLE
debian_ip can't create ipv6 up in /etc/network/interfaces

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#29105]
I want to use state.network on a debian machine but can't create the following line with the module:

```
iface br0 inet6 auto
  up ip -6 addr add 2001:ABCD:EF01:2345::6789/64 dev br0
```

the first part is easy:

```
eth0:
  network.managed:
    - enabled: True
    - type: eth
    - proto: none
    - address: XXX.XXX.XXX.XXX
    - netmask: 255.255.255.0
    - gateway: XXX.XXX.XXX.XXX
    - dns-search: example.org
    - dns:
      - 8.8.8.8
      - 8.8.4.4
      - '2001:4860:4860::8888'
      - '2001:4860:4860::8844'
    - enable_ipv6: True
    - ipv6proto: 'auto' 
```

but how do I add the up line..?
