### ISSUE TITLE
MTU is output twice when used in network.managed

### ISSUE THREAD

**Issue by Dravu** [saltstack/salt#29137]
It appears that two commits got made (https://github.com/saltstack/salt/commit/3d3b219047b236a951b988ddfa1056f627ad3958 and https://github.com/saltstack/salt/commit/029dbe8036df47e89afbd2636bfcd1aa64946136) that handle the output of the MTU for a network interface to its ifcfg file. This duplication is making it so that if you specify a MTU in network.managed, the MTU gets output to the ifcfg file twice.

An example of one of the template files with the duplicate MTU setting can be found at:
https://github.com/saltstack/salt/blob/2015.8/salt/templates/rh_ip/rh7_eth.jinja

```
bond0:
  network.managed:
    - enabled: True
    - type: eth
    - proto: none
    - require:
      - network: eno7
      - network: eno8
    - mtu: 1500
```
would generate:
```
DEVICE="bond0"
USERCTL="no"
BOOTPROTO="none"
ONBOOT="yes"
MTU="1500"
MTU="1500"
```
