### ISSUE TITLE
It should be possible invoke the same function twice per state

### ISSUE THREAD

**Issue by mathrick** [saltstack/salt#29142]
I want to set up and run postfix, which happens to require two files in the setup I'm using. Thus the logical way of describing it would be

``` yaml
Set up postfix:
  pkg.installed: ...
  file.managed:
    - name: /etc/service/postfix/run
    - contents: ...
  file.managed:
    - name: /etc/postfix/main.cf
    - source: ...
  service.running: ...
```

However, due to the syntax chosen for Salt, it's not actually possible, even though I cannot see a logical reason why it shouldn't be. #4508 has touched on that, but no actual explanation has been given for _why_ such a limitation would be desirable. From what I can tell, it's just an unfortunate, and counter-intuitive accident rather than a conscious design decision. As it is, Salt's syntax currently:
- uses a completely unnecessary _list_ of single-key dictionaries for state function parameters, which are already uniquely named, and are indeed dictionaries in Python, and thus require unwrapping from the parsed YAML form of `[{"name": "foo"}, {"bar": 42}]` before they can be passed on to Python functions
- uses a _single_ multi-key dictionary for what is logically a _list_ of state functions that constitute a state, and where using a list would actually make sense

This leads to a situation in which I can say "setting up X requires installing the X package and ensuring the service is running", but I cannot say "setting up X requires installing the package and ensuring two files are as described", instead being required to split that into "setting up X part 1" and "setting up X part 2". This breaks expectations and forces me to split into multiple Salt states what is to me a single logical state.

A syntax that would reflect the logical structure of things I want to communicate to Salt would be instead:

``` yaml
Set up postfix:
  - pkg.installed: ...
  - file.managed:
      name: /etc/service/postfix/run
      contents: ...
  - file.managed:
      name: /etc/postfix/main.cf
      source: ...
  - service.running: ...
```

Is there any reason why this couldn't be accepted by Salt?

**Comment by sjorge** [comment]
I struggle with this a bit too since I am relatively new to states (just started with them a week or so ago)
```yaml
postfix:
  pkg.installed
/etc/service/postfix/run:
  file.managed:
    - content: ...
/etc/postfix/main.cf:
  file.managed:
    - content: ...
```

As I understand it the 'state id' needs to be unique and gets passed as the name parameter. (Someone will probably be along to correct me soon)

**Comment by jfindlay** [comment]
@mathrick, you are correct about this being a restriction on how salt handles state data.  The relevant documentation is here: https://docs.saltstack.com/en/latest/ref/states/highstate.html#id-declaration.  Making the changes to the state compiler to allow this would be very fraught with potential regressions and would need to be carefully tested.

It seems that attempting to override the ID does not work either.
```salt
# cat /srv/salt/test.sls
multi state:
  file.managed:
    - id: first
    - name: /tmp/1
    - contents: one
  file.managed:
    - id: second
    - name: /tmp/2
    - contents: two
```
```yaml
# salt jmoney-main state.show_sls test
jmoney-main:
    - Rendering SLS 'base:test' failed: Conflicting ID 'file.managed'
ERROR: Minions returned with non-zero exit code
```
```yaml
# salt jmoney-main test.versions
jmoney-main:
    Salt Version:
               Salt: 2015.8.1

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed

    System Versions:
               dist: debian 8.2
            machine: x86_64
            release: 3.16.0-4-amd64
             system: debian 8.2
```

**Comment by whiteinge** [comment]
> A syntax that would reflect the logical structure of things I want to communicate to Salt would be instead:
> [...]
> Is there any reason why this couldn't be accepted by Salt?

No reason at all! We would happily accept that addition as a new renderer module if you send in a pull request. You have a simple and logical syntax brewing there. :+1:

The format you are describing is what we call [Highstate](https://docs.saltstack.com/en/latest/ref/states/highstate.html). It is one way (of countless possible ways) to model a data structure that represents ordered functions calls. Highstate is intended to be human-friendly -- easy to read, easy to write. It does have the unfortunate historical caveat that you detailed in your OP (some [historical detail](https://github.com/saltstack/salt/issues/12419) for the interested). That trips up new users on occasion. In practice that means you must separate states out under individual `id` declarations -- but that is a [decent pattern for modularity](https://docs.saltstack.com/en/latest/topics/best_practices.html#modularity-within-states) anyway.

All that said, Salt's [renderer modules](https://docs.saltstack.com/en/latest/ref/renderers/) obviate the need to deal with highstate directly if that's not your cup 'o tea. They are [easy to write](https://github.com/saltstack/salt/tree/develop/salt/renderers) and they allow for wildly different syntaxes. The syntax you proposed above is definitely possible via a new renderer module.

As @jfindlay stated above, changing the default is a non-starter for the many, many thousands of users and companies that depend on Salt. But using something other than the default is just a `#!` away. :smile: 

```yaml
#!mathricks_awesome_renderer
Set up postfix:
  - pkg.installed: ...
  - file.managed:
      name: /etc/service/postfix/run
      contents: ...
  - file.managed:
      name: /etc/postfix/main.cf
      source: ...
  - service.running: ...
```

**Comment by whiteinge** [comment]
@sjorge you're exactly right about the id declaration and the name parameter. You may find [these style recommendations](https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#style) helpful as you're getting up to speed.

**Comment by sjorge** [comment]
@whiteinge thanks for the link, just glanced over it and are some good things in there I will certainly rake into account once I move from my simple test setups (used while developing some more modules I need) to a final setup.

I noticed there is some link hopping I end up here:
https://docs.saltstack.com/en/latest/topics/best_practices.html#storing-secure-data (which peaked my interested a lot.)

Kind of disappointed it does not mention https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.gpg.html (maybe there are others too)

That would seem like something to do to store passwords and perhaps ssl/tls certificates?

**Comment by whiteinge** [comment]
On Wed, Nov 25, 2015 at 3:54 PM, Jorge Schrauwen
<notifications@github.com> wrote:
> That would seem like something to do to store passwords and perhaps ssl/tls certificates?

The gpg renderer is a way to encrypt sls files _at rest_. You can use
that with Pillar sls files to store ssl certs encrypted on-disk.
(Don't put sensitive data in `file_roots`! Only in Pillar.) They are
then decrypted when the daemon starts. Another good option for
handling sensitive data is via sdb modules.

**Comment by firelizzard18** [comment]
This issue is relevant to me. I want to do the following:

```yaml
/etc/my-service:
  file.managed: [ ... ]

my-service:
  - pkg.installed

  # install and start service
  - service.running:
    - enable: true
    - require:
      - pkg: my-service
      - file: /etc/my-service

  # reload service when reconfigured
  - service.running:
    - reload: true
    - watch:
      - file: /etc/my-service
```
