### ISSUE TITLE
Grains set in states should be automatically reloaded, and be processes first not last

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#29168]
I want to set a grain in a state, and have it immediately usable. Grains are the only way to set the equivalent of global variables, because you can't set pillars from within a state. What I want is doable, but only with a hack.

  With the proper way, the current behavior of processing any grains in a state last doesn't work. They need to be first. This in consistent with how grains are processed before the running of states.

The hack:
top.sls:

```
base:
  '*':
    - common_grains
    - common
```

common_grains/init.sls:

```
mirror:
  grains.present:
    - value: True

include:
  - common_grains.files
```

common_grains/files.sls:

```
/tmp/common_grains_placeholder:
  file.absent:
    - reload_grains: True
```

common/init.sls:

```
include:
  - common.files
```

The proper way:

common/init.sls:

```
mirror:
  grains.present:
    - value: True

include:
  - common.files
```
