### ISSUE TITLE
glance is unable to auth when used with profiles in 2015.8.x

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#29177]
if using profiles like this. 
```
openstack1:
  keystone.user: admin
  keystone.password: verybadpass
  keystone.tenant: admin
  keystone.auth_url: 'http://127.0.0.1:5000/v2.0/'

openstack2:
  keystone.user: admin
  keystone.password: verybadpass
  keystone.tenant: admin
  keystone.auth_url: 'http://127.0.0.2:5000/v2.0/'
```
glance does not pass the profile to keystone.endpoint_get causing it to fail loading.
