### ISSUE TITLE
pip.installed with bin_env misses requirements

### ISSUE THREAD

**Issue by bagratte** [saltstack/salt#29246]
sls:

``` saltstate
/tmp/flask:
  virtualenv.managed

flask:
  pip.installed:
    - upgrade: True
    - bin_env: /tmp/flask
    - require:
      - virtualenv: /tmp/flask
```

execution log (partial):

<pre>
2015-11-27 17:48:00,649 [salt.loaded.int.module.cmdmod][DEBUG   ][654] stdout: Collecting flask
Collecting itsdangerous>=0.21 (from flask)
Collecting Werkzeug>=0.7 (from flask)
  Downloading http://10.31.1.5:5010/root/pypi/+f/a21/a2329d977837d/Werkzeug-0.11.2-py2.py3-none-any.whl (304kB)
<b>Requirement already up-to-date: Jinja2>=2.4 in /usr/local/Cellar/saltstack/2015.8.1/libexec/vendor/lib/python2.7/site-packages (from flask)
Requirement already up-to-date: MarkupSafe in /usr/local/Cellar/saltstack/2015.8.1/libexec/vendor/lib/python2.7/site-packages (from Jinja2>=2.4->flask)</b>
Installing collected packages: itsdangerous, Werkzeug, flask
Successfully installed Werkzeug-0.11.2 flask-0.10.1 itsdangerous-0.24
</pre>

the bug:

```
buddy:~ root# cd /tmp/flask/bin
buddy:bin root# ./pip list
Flask (0.10.1)
itsdangerous (0.24)
pip (7.1.2)
setuptools (18.2)
Werkzeug (0.11.2)
wheel (0.24.0)
buddy:bin root# ./python -c "import flask"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/flask/lib/python2.7/site-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: No module named jinja2
```

```
buddy:~ root# salt --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Aug 22 2015, 20:33:39)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.3
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 15.0.0
         system: 10.11.1 -- x86_64
```
