### ISSUE TITLE
status.uptime causes exception on Windows minion 2015.8.1

### ISSUE THREAD

**Issue by adamsewell** [saltstack/salt#29251]
I've been playing around with the status module on some Windows 7 minions and one of the issues I've noticed is the following. If I issue ```salt -N 'win_workstations' status.uptime``` I get the following error.
 ```    
The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1036, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_status.py", line 220, in uptime
        startup_time = time.strptime(startup_time, '%d/%m/%Y %H:%M:%S')
      File "c:\salt\bin\lib\_strptime.py", line 467, in _strptime_time
        return _strptime(data_string, format)[0]
      File "c:\salt\bin\lib\_strptime.py", line 325, in _strptime
        (data_string, format))
    ValueError: time data '11/24/2015 8:10:25 AM' does not match format '%d/%m/%Y %H:%M:%S'
```

Master:
```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 0.8.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-57-generic
         system: Ubuntu 14.04 trusty
```

Minion:
```
    Salt Version:
               Salt: 2015.8.1
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist:   
            machine: AMD64
            release: 7
             system: 7 6.1.7601 SP1 Multiprocessor Free
```
