### ISSUE TITLE
mysql_user.present does not work with MySQL 5.7

### ISSUE THREAD

**Issue by mbochenk** [saltstack/salt#29265]
On CentOS6 mysql user is no longer created correctly, whether password or password_hash is used.
For example:
```salt
mysql-user-add-{{user.user}}-{{host}}:
  mysql_user.present:
    - name: {{user.user}}
    - password_hash: '{{user.password_hash}}'
    - host: '{{host}}'
```
results in:
```yaml
          ID: mysql-user-add-mysql-test-localhost
    Function: mysql_user.present
        Name: mysql-test
      Result: False
     Comment: MySQL Error 1054: Unknown column 'Password' in 'where clause'
     Started: 05:46:35.532327
    Duration: 5.064 ms
```
This is most likely related to changes in MySQL 5.7: https://dev.mysql.com/doc/refman/5.7/en/account-upgrades.html

Salt versions report: 
```yaml
           Salt: 2015.5.6
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: 2.8
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: 0.2.4
       dateutil: Not Installed
```
