### ISSUE TITLE
Feature Request: check for 1st run / "boot time"

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#29309]
as salted state/module to check if we are "fresh" setup / started and want e.g. making system-wide package upgrades to have latest versions and other tasks of interest when initalizing / starting an instance. ;)

There should some states for it because cron can also use `@reboot` instead of normal 5 time fields   ( `man 5 crontab` ) .

**Comment by basepi** [comment]
If you want to check if this is the first time running salt, you should have states which are dependant on a grain. Basically, you have all these states only run if grain `foo` is `True`, and then at the end of the states you set `foo` to `True` because now everything has been set up the first time.

Does that satisfy your need?

**Comment by Reiner030** [comment]
Thats the way I do it for longer times ... But 

1. It seems that people implement it different.
    Already saw that people checkout files/"1st run state done" to /tmp because they didn't aware that tje tmp folders are regulary swept by crons / while booting up.
2. The stop/start of an instance (e.g. in AWS) is not effected in this solution.
    Example: I have set the grain ````foo: True```` but the instance was e.g. one week down and suffers for git checkouts, security updates and so on)... so this grain state is for the birds :)

Thats why I opened this feature request. Perhaps you / other find it also useful.

**Comment by The-Loeki** [comment]
Well it's an interesting feature, but I think it'll be tough to get right. And I don't see *how* to do it without writing data somewhere volatile.

For example, `cron` writes `/var/run/crond.reboot` once it's done doing the `@reboot` stuff.
So first of all `/var/run` is a much more apropriate place to write this kind of data, especially considering the nature of `/tmp`, aforementioned sweepers and sec mechanisms such as AppArmor & SElinux etc.

The `status` or `system` modules might have a function testing for the existence of this file, and the salt minion could touch it after running through `startup_states` et al.

**Comment by Reiner030** [comment]
A thx @The-Loeki  for the hint. 
I have overseen that our "1st highstate run" already done by ````startup_states: highstate```` is not only run 1st time after setup: https://docs.saltstack.com/en/latest/ref/states/startup.html

So this can be then an easy
* modification of the parameter by state after initial highstate to
  ````startup_states: sls```` and 
* setting up the wanted states for every boot time states like:
````
sls_list:
  - hosting.filesystem
  - store.rollout_update
```` 
(for e.g. setup initial folder structure / here swap on AWS SSDs )

Btw. it would be nice if parameters in ````/etc/salt/minion.d/*.conf```` can override the ````/etc/salt/minion```` ones so there is no need to work on the main files directly (tested that it was not working for versions < 2015.5.x). Should I open a new issue for it?

**Comment by The-Loeki** [comment]
@Reiner030 NP :) bear in mind though (I think you got that, but I'm not sure) that 'startup' in this regard is 'salt minion startup'.
Do a `service salt-minion restart` and watch your highstate go again ;) 

I'm not entirely sure about your second remark, but we usually keep `/etc/salt/minion` in completely commented state anyways, utilizing the `conf.d` dir exclusively (and of course pillars can provide config as well)

**Comment by Reiner030** [comment]
yes, @The-Loeki , thats clear. But this I can solve with uptime check in future salt versions: https://github.com/saltstack/salt/issues/29311 

Mmh, perhaps this feature request makes then still sense and can be a ready-to-use combination of startup_states, uptime and perhaps more ;) ... ok, open it again.

**Comment by Danixu** [comment]
Hello,

A little hack to manage this:
reactors/start.sls
```
run_reactors:
  local.state.sls:
    - name: 'Run reactors'
    - tgt: '{{ data['id'] }}'
    - args:
      - mods: reactors
```
states/reactors.sls
```
{%- if 0 == salt['cmd.retcode']('if [ $(cat /proc/uptime|awk \'{printf "%0.f", $1}\') -lt 300 ]; then exit 0; else exit 1; fi', python_shell=True) %}
include:
  - state1
  - state2
{% endif %}
```

If minion uptime is less than 300 seconds then run the states in the include.

Greetings!!

**Comment by Reiner030** [comment]
No, thats problematic/too hacky; if you e.g. have a highstate setup for every minion start it would run initial states every time a server/instance is starting...

I have created a better workaround for this since this seems no "common problem" from sight of saltstack team:

- a reactor state which would deploy a temporary stamp file:
```
base/_reactor/salt/cloud/deploy_script/initial_stampfile.sls:
# create temporary file for e.g. reboot condition if instance is just created.
01-setup_initial_file:
  local.file.touch:
    - arg:
        - /tmp/salt_initial_setup
    - tgt: {{ data['name'] }}
```
- all necessery changes/includes which are needed only for initial highstate are setup in condition:
    - dependend on the needs I put part(s)/whole state(s) into a salt condition:
    {%-  if salt['file.file_exists']('/tmp/salt_initial_setup') %}
         ...
    {%-  endif %}
  - or I set an onlyif condition of the state itself:
```
    - onlyif: test -f /tmp/salt_initial_setup
```
- at last state I cleanup in finalisation sls (after package upgrade to have all Debian backport packages correctly upgraded if not already automatically setup by packages install states) the stamp file or reboot the minion dependend of the :

```
update-packages-if-needed:
  pkg.uptodate:
    - onlyif: test -f /tmp/salt_initial_setup
    - order: last
    - require_in:
      - cmd: reboot-system-if-needed

reboot-system-if-needed:
  cmd.run:
    - name: |
        rm -f /tmp/salt_initial_setup
        needrestart -b | grep -q "^NEEDRESTART-KSTA: [23]$" && shutdown -r +1 || true
    - onlyif: test -f /tmp/salt_initial_setup
    - order: last
    - runas: root
```
