### ISSUE TITLE
Error with `file.search` in 2015.8.1

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#29318]
Seems like there is an error with `file.search` in `2015.8.1`. It is working in `2015.5.6`.

This is part of the file I am searching from, `udms.conf`:
```
installation_directory /opt/universal/udmsrv
nls_directory ../nls
message_level INFO
security NONE
```

When searching for an existing word in `2015.5.6`, it returns `True`.
```
[root@frode-rh7-5 ~]# salt frode-rh7-5.6 file.search '/etc/universal/udms.conf' '^security NONE'
frode-rh7-5.6:
    True
[root@frode-rh7-5 ~]# salt --versions-report
           Salt: 2015.5.6
         Python: 2.7.5 (default, Apr  9 2015, 11:03:32)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.5
```

When searching for an existing word in `2015.8.1` it returns `False`. (Unless the searched word is the first word in the file.)
```
[root@frode-rh7-8 ~]# salt frode-rh7-8.1 file.search '/etc/universal/udms.conf' '^security NONE'
frode-rh7-8.1:
    False
[root@frode-rh7-8 ~]# salt --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Apr  9 2015, 11:03:32)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: redhat 7.1 Maipo
        machine: x86_64
        release: 3.10.0-229.11.1.el7.x86_64
         system: Red Hat Enterprise Linux Server 7.1 Maipo
```
