### ISSUE TITLE
state/host.present and alias-assignment to multiple IPs fails

### ISSUE THREAD

**Issue by rall0r** [saltstack/salt#29313]
## What we try to do:
Assign `localhost` to `127.0.0.1` and `::1` in our `/etc/hosts` file so that it looks something like this:
```
127.0.0.1  localhost localhost.localdomain
::1  localhost
```
That is needed because we have IPv4 and IPv6 both enabled and services like Postfix expect an IPv6 entry in our `hosts` file.

## The problem
`state/hosts.present()` has a kind of "dublicate" checker (if you like to name it like that):
https://github.com/saltstack/salt/blob/develop/salt/states/host.py#L95

That prevents from an assignment of the same alias to multiple IP adresses, including IPv6 entries.

## How to reproduce
`test.sls`
```yaml
assign_ipv4_localhost:
  host:
    - present
    - ip: 127.0.0.1
    - name: localhost

assign_ipv6_localhost:
  host:
    - present
    - ip: ::1
    - name: localhost
```
```sh
cat /etc/hosts
```
As you can see `salt` replies that it will add **both** host entries, but in fact only one will be written into the `/etc/hosts` file.

# Conclusion
This is pretty easy to fix. The question is if this **should** be fixed, and if not, how we report this back to the user calling the host state that something is not working as expected.

Kind regards
Ralf
