### ISSUE TITLE
boto_route53.present state is unavailable 

### ISSUE THREAD

**Issue by mghonaim** [saltstack/salt#29328]
Hi, I have an issue in one of my states

This is my state
```sls
privdns:
  boto_route53.present:
    - name: {{ grains['id'] }}.
    - value: ip
    - zone: yyy.zzz.
    - ttl: 60
    - record_type: A
    - region: us-east-1
```
when I run it i got a error saying that `State boto_route53.present found in sls hostname.sls is unavailable`

Although i see the  boto_route53.py in salt states and modules
```console
$ find /usr/lib/ -name "boto_route53*" -print
/usr/lib/python2.7/dist-packages/salt/modules/boto_route53.pyc
/usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py
/usr/lib/python2.7/dist-packages/salt/states/boto_route53.pyc
/usr/lib/python2.7/dist-packages/salt/states/boto_route53.py
```
I am using ubuntu 14.04.2 LTS, Trusty Tahr, and 
```yaml
$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```
boto is also installed
