### ISSUE TITLE
Can't provision EBS volumes over 1000GB in AWS

### ISSUE THREAD

**Issue by MacTynow** [saltstack/salt#29327]
Hi, 

I am trying to provision 5TB EBS volumes in AWS. Anything over 1TB (1000GB) fails with the following error : 
`Client.InvalidParameterCombination: Could not create volume with size 5000GiB from snapshot 'null'`

Here is the block_device_mapping : 
```sls
block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 100
    - DeviceName: /dev/sdb
      Ebs.VolumeSize: 1000
```

I've been looking for issues related to this but I guess this is not a frequent use case. EBS can be provisioned up to 16TB according to AWS documentation. Starting an instance with more than 1TB through the AWS interface works correctly.

Thanks for your help,

Charles.

**Comment by jfindlay** [comment]
@MacTynow, thanks for the report.  What version of salt are you using?  Are you using the `boto_lc` state or the `ec2` cloud?

**Comment by MacTynow** [comment]
@jfindlay Thanks for the reply, the version is ```Salt Version:
           Salt: 2015.8.1```

We are using the ec2 cloud, not boto_lc.

**Comment by pass-by-value** [comment]
Hi @MacTynow 

Could you please post your cloud profile?

I wasn't able to reproduce this issue.

Here's my cloud profile

```yaml
ec2_testing:
  provider: my-ec2-us-east-public-ips
  image: ami-01c3bc64
  size: d2.xlarge
  ssh_username: root
  deploy: False

  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 100
    - DeviceName: /dev/sdb
      Ebs.VolumeSize: 1001
```

I was able to create an ec2 instance with storage info shown below.

```shell
[root@ip-1-2-3-4 ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
dev              15G     0   15G   0% /dev
run              15G  268K   15G   1% /run
/dev/xvda1       99G  1.2G   93G   2% /
tmpfs            15G     0   15G   0% /dev/shm
tmpfs            15G     0   15G   0% /sys/fs/cgroup
tmpfs            15G     0   15G   0% /tmp
tmpfs           3.0G     0  3.0G   0% /run/user/0
[root@ip-1-2-3-4 ~]#
```

**Comment by MacTynow** [comment]
Maybe it works up to a certain value, but I can tell you I can't make it
work with 2000 GB or more.

In my case the instance starts and stops immediatly.

**Comment by pass-by-value** [comment]
Hi @MacTynow. Are you able to create this using the web interface? If yes, could you please post what steps you took?

I would also like to know what `size` parameter you are using in the cloud profile and what OS you plan to use for the instance.

**Comment by MacTynow** [comment]
Hi, I can create it using the web interface, using AMI ami-5189a661,
m4.2xlarge instance and adding a 2TB EBS volume (not the root volume),
mounted on /dev/sdb.

In the salt configuration, the OS is ubuntu and the size parameter in the
cloud profile is m4.2xlarge. Same AMI.

**Comment by pass-by-value** [comment]
Hi @MacTynow. Thanks for the info.

I updated my cloud profile to have the following block device mappings

```yaml
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 100
    - DeviceName: /dev/sdb
      Ebs.VolumeType: gp2
      Ebs.VolumeSize: 3001
```

And that seems to let me add the additional volume

```shell
[root@ip-1-2-3-4 ~]# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0    0  100G  0 disk
└─xvda1 202:1    0  100G  0 part /
xvdb    202:16   0    3T  0 disk
xvdc    202:32   0  1.8T  0 disk
xvdd    202:48   0  1.8T  0 disk
```

I do get the same erroneous behavior you mentioned if I don't specify the `VolumeType`.

Could you please try this out and let me know how it goes?
