### ISSUE TITLE
adding timeout to ssh_knows_hosts.present state. by default it times out after 5 seconds

### ISSUE THREAD

**Issue by aronneagu** [saltstack/salt#29335]
The state ssh_known_hosts.present fails if the host queried doesn't reply in 5 seconds or less. Is it possible to add a timeout option to ssh_known_state? This state actually invokes ssh-keyscan, which supports timeout option (argument -T).

The state i was trying to run is:
```
bitbucket.org:
  ssh_known_hosts:
    - present
    - user: root
    - enc: ssh-rsa
    - fingerprint: 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40
```

The result running the state is:
```
635e0202-484c-4047-96c8-2fbb5d38b887:
----------
          ID: bitbucket.org
    Function: ssh_known_hosts.present
      Result: False
     Comment: Unable to receive remote host key
     Started: 16:30:02.583761
    Duration: 5142.302 ms
     Changes:   

Summary for 635e0202-484c-4047-96c8-2fbb5d38b887
------------
Succeeded: 0
Failed:    1
```

Thank you
