### ISSUE TITLE
iptables and match-set with two parameters

### ISSUE THREAD

**Issue by l13t** [saltstack/salt#29423]
I have such configuration:
```yaml
iptables_outsideIn_rule11:
  iptables.append:
    - table: filter
    - match:
      - comment
      - set
    - chain: outsideIn
    - jump: ACCEPT
    - proto: 
    - match-set:
      - WWW-VIP dst
      - CL_WWW-DEWLT-STAGING src
    - comment: outsideIn_11 dewlt-staging HTTP/HTTPS access to WWW-VIP
```
When I run salt-call with debug option, i'm getting next output for this rule:
```bash
/sbin/iptables -t filter -C outsideIn -m comment -m set --comment "outsideIn_11 dewlt-staging HTTP/HTTPS access to WWW-VIP" --match-set [\'WWW-VIP dst\', \'CL_WWW-DEWLT-STAGING src\'] --jump ACCEPT
```
As I can see iptables state and module doesn't proceed match-set with multiple parameters. Any ideas or proposals how it can be fixed?

**Comment by l13t** [comment]
Update:
I thought about appending string with variables.
For such configuration:
```yaml
iptables_outsideIn_rule11:
  iptables.append:
    - table: filter
    - match:
      - comment
      - set
    - chain: outsideIn
    - jump: ACCEPT
    - proto: 
    - match-set: WWW-VIP dst
    - match-set: CL_WWW-DEWLT-STAGING src
    - comment: outsideIn_11 dewlt-staging HTTP/HTTPS access to WWW-VIP
```
I got such string generated:
```bash
/sbin/iptables -t filter -C outsideIn -m comment -m set --comment "outsideIn_11 dewlt-staging HTTP/HTTPS access to WWW-VIP" --match-set CL_WWW-DEWLT-STAGING src --jump ACCEPT
```
For some reason it doesn't proceed inserted twice option and gets only last one.

**Comment by l13t** [comment]
One variant:
In  insert into build_rule after proceeding match with if next code:
```python
    if 'match-set' in kwargs:
        if not isinstance(kwargs['match-set'], list):
            kwargs['match-set'] = kwargs['match-set'].split(',')
        for match_s in kwargs['match-set']:
            rule += '-m set --match-set {0} '.format(match_s)
        del kwargs['match-set']
```

**Comment by jfindlay** [comment]
@l13t, thanks for working on this.  You are welcome to submit a pull request for this. @thusoy, please also review.

**Comment by thusoy** [comment]
Some thoughts: 
  - `-m set` only needs to be added to the rule once (right?), thus can be pulled out of the loop
  - `rule` is a list, thus appending needs to be done using `rule.append`.
  - Splitting on comma as a fallback is probably not too wise, as commas can be used in the flag spec to seperate flags (see [docs](http://ipset.netfilter.org/iptables-extensions.man.html))

Put it next to and integrate with the deprecated [set handling](https://github.com/saltstack/salt/blob/2015.8/salt/modules/iptables.py#L273) in `build_rule` and I'm happy.

**Comment by l13t** [comment]
* about -m set you are wrong. look there: https://utcc.utoronto.ca/~cks/space/blog/linux/IptablesIpsetsMultipleMatches
* i can be wrong in understanding of functionality of --set option. As i understand it can work only with source address. And in my formula i need to specify match-set for source and destination ipsets in one rule.

My current formula in result has next code:
```yaml
iptables_outsideIn_rule11:
  iptables.append:
    - table: filter
    - match:
      - comment
      - set
    - chain: outsideIn
    - jump: ACCEPT
    - proto: 
    - match-set: 
      - WWW-VIP dst
      - CL_WWW-DEWLT-STAGING src
    - comment: outsideIn_11 dewlt-staging HTTP/HTTPS access to WWW-VIP
```

But it would be better if match-set in result would have next structure:
```yaml
match-set:
  src:
    - src_set_1
    - src_set_2
  dst:
    - dst_set_1
    - dst_set_2
```
And then result of proceeding such configuration would be:
```bash
iptables -<some option list> -m set --match-set src_set_1,src_set_2 src -m set --match-set dst_set_1,dst_set_2 dst
```
If I clearly understand iptables man pages it should work.

**Comment by thusoy** [comment]
Cool, learned something new today about `-m set`.

Why exactly is the latter example you posted better? I haven't used ipset much myself, but from reading the manpages the format of the argument is `--match-set setname flag[,flag]`, to which I think your first example maps cleaner, and is easier to reason about and implement.

**Comment by l13t** [comment]
About last example.
I think it's better for visual understanding. Cause we can specify several ipset lists per one of directions (src and dst).
I saw your reply to pull request. I agree that my "patch" is not so good and I didn't checked variant with negotiations. I can try to fix this and create new pull request.

**Comment by l13t** [comment]
@thusoy 
I thought about your proposal one more time. I think it would be really better to have next structure for match-set option:
```yaml
    - match-set: 
      - WWW-VIP dst
      - CL_WWW-DEWLT_1-STAGING src
      - CL_WWW-DEWLT_2-STAGING src
```
It would prevent issue with negotiation of all list. Anyway it works if we're specifying set's one-by-one.
And it should be documented as well ((:

**Comment by l13t** [comment]
I updated iptables module. It now includes check for negotiation.
While I was working on my iptables formula for linux firewall I got that we should manually specify next thing:
```yaml
- match:
  -iprange
- dst-range: 10.0.0.2-10.0.0.5
```
But i saw a ticket there with proposal totally rewrite this module. Hope this also would be fiixed in future.
