### ISSUE TITLE
services for older OEL releases.

### ISSUE THREAD

**Issue by paclat** [saltstack/salt#29425]
In trying out 2015.8.3 we are seeing an error running OEL 5 and OEL 6 with...

``` yaml
                   "__run_num__": 31,
                                    "changes": {},
                                    "comment": "State 'service.running' was not found in SLS 'oracle-lcm-bootstrap'\nReason: 'service' __virtual__ returned False\n",
                                    "name": "salt-master",
                                    "result": false
```

Looks like the default service now has...

``` py
# Disable on these platforms, specific service modules exist:
disable = set((
    'RedHat',
    'CentOS',
    'Amazon',
    'ScientificLinux',
    'CloudLinux',
    'Fedora',
    'Gentoo',
    'Ubuntu',
    'Debian',
    'Arch',
    'Arch ARM',
    'ALT',
    'SUSE  Enterprise Server',
    'OEL',
    'Linaro',
    'elementary OS',
    'McAfee  OS Server',
    'Mint'
))
if __grains__.get('os', '') in disable:
    return False
# Disable on all non-Linux OSes as well
```

and the rh_service has...

``` py
# Enable on these platforms only.
enable = set((
    'XenServer',
    'RedHat',
    'CentOS',
    'ScientificLinux',
    'CloudLinux',
    'Amazon',
    'Fedora',
    'ALT',
    'OEL',
    'SUSE  Enterprise Server',
    'SUSE',
    'McAfee  OS Server'
))
if __grains__['os'] in enable:
    if __grains__['os'] == 'XenServer':
        return __virtualname__
    if __grains__['os'] == 'SUSE':
        if str(__grains__['osrelease']).startswith('11'):
            return __virtualname__
        else:
            return False
    try:
        osrelease = float(__grains__.get('osrelease', 0))
    except ValueError:
        return False
    if __grains__['os'] == 'Fedora':
        if osrelease > 15:
            return False
    if __grains__['os'] in ('RedHat', 'CentOS', 'ScientificLinux', 'OEL'):
        if osrelease >= 7:
            return False
    return __virtualname__
return False
```

``` yaml
  os:
        OEL
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
    osfinger:
        Oracle Linux Server-5
    osfullname:
        Oracle Linux Server
    osmajorrelease:
        5
    osrelease:
        5.11
    osrelease_info:
        - 5
        - 11
    path:
```

**Comment by paclat** [comment]
One interesting note is that if I go on to the machine and user service with salt-call directly it seem to work.  It only appear to be when we are using it in the state file.

**Comment by galet** [comment]
I'm running into the same issue with OEL6 using 2015.8.3. The root cause for that seems to be a big regression in grains module for OS version values. Notice the **"** character in values:
```yaml
   oscodename:
        Oracle Linux Server 6.7"
    osfinger:
        Oracle Linux Server"-6
    osfullname:
        Oracle Linux Server"
    osmajorrelease:
        6
    osrelease:
        6.7"
    osrelease_info:
        - 6
        - 7"
```

This is caused by the OEL formatting of `/etc/os-release` which contains space at the end of some lines.
I will attach a merge request with a simple fix in a minute. 

**Workaround:** Edit `/etc/os-release` and remove all space characters at the end of line.
```bash
sed -i 's/\s*$//' /etc/os-release
```
