### ISSUE TITLE
salt.loaded.int.module.nova.__virtual__() is wrongly returning `None`.

### ISSUE THREAD

**Issue by shawnbutts** [saltstack/salt#29445]
Just upgrade to 2015.8.3 and this happens on every state call.

```
[ERROR   ] Exception raised when processing __virtual__ function for nova. Module will not be loaded global name 'novaclient' is not defined
[WARNING ] salt.loaded.int.module.nova.__virtual__() is wrongly returning 'None'. It should either return 'True', 'False' or a new name. If you're the developer of the module 'nova', please fix this.
```

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.2.1
       cherrypy: 3.7.0
       dateutil: 2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 4.1.13-18.26.amzn1.x86_64
```
