### ISSUE TITLE
cmd.wait state watching a cmd.run state with onlyif/unless always runs

### ISSUE THREAD

**Issue by rca** [saltstack/salt#29515]
I'd like to have a `cmd.wait` state `watch` a `cmd.run` state.  For example:

```
do_foo:
  cmd.run:
    - unless: test "0" == "0"

post_foo:
  cmd.wait:
    - watch:
      - cmd: do_foo
```

It appears that `cmd.run` states always return as if they execute despite `onlyif` / `unless` clauses preventing them from doing so.  In the example above, `post_foo` always executes.

Is the above misconfigured and is there a way to achieve what I'm trying to do?

Thanks!

**Comment by jtand** [comment]
@rca that seems like it might be a bug with `unless`. It should only run if unless returns a false.

**Comment by rca** [comment]
@jtand thanks for the update.  I'm using the latest available in the git repos; fresh install about two weeks ago:

```
$ salt-call --versions-report
                  Salt: 2015.5.3
                Python: 2.7.9 (default, Mar  8 2015, 00:52:26)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1~bpo8+1
```

**Comment by jtand** [comment]
@rca Thanks for the versions report. I may have been a little too hasty in my previous  comment. I did a little more testing and it looks like the comment is incorrect. Does this seem to be what you are seeing in your use cases?

This should only work if `unless: False`
```yaml
  do_echo:
    cmd.run:
      - name: echo hello
      - unless: True
  
  post_echo:
    cmd.wait:
      - name: 'echo after do_echo'
      - watch:
        - cmd: do_echo
```

The output shows that the above state didn't work, however, the comment says it succeeded. I think that is the "bug" here, because it appears to be working correctly. 

```bash
 salt localminion state.sls test
localminion:
----------
          ID: do_echo
    Function: cmd.run
        Name: echo hello
      Result: True
     Comment: unless execution succeeded
     Started: 18:40:57.760284
    Duration: 2.839 ms
     Changes:
----------
          ID: post_echo
    Function: cmd.wait
        Name: echo after do_echo
      Result: True
     Comment:
     Started: 18:40:57.765215
    Duration: 2.115 ms
     Changes:

Summary for localminion
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time:   4.954 ms
```

Correct usage of unless with `unless: False` in the state allows it to execute. 
```yaml
  do_echo:
    cmd.run:
      - name: echo hello
      - unless: False
  
  post_echo:
    cmd.wait:
      - name: 'echo after do_echo'
      - watch:
        - cmd: do_echo
```

Output: 
```bash
salt localminion state.sls test
localminion:
----------
          ID: do_echo
    Function: cmd.run
        Name: echo hello
      Result: True
     Comment: Command "echo hello" run
     Started: 18:48:15.550486
    Duration: 38.156 ms
     Changes:
              ----------
              pid:
                  23160
              retcode:
                  0
              stderr:
              stdout:
                  hello
----------
          ID: post_echo
    Function: cmd.wait
        Name: echo after do_echo
      Result: True
     Comment: Command "echo after do_echo" run
     Started: 18:48:15.593777
    Duration: 32.833 ms
     Changes:
              ----------
              pid:
                  23161
              retcode:
                  0
              stderr:
              stdout:
                  after do_echo

Summary for localminion
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:  70.989 ms
```
