### ISSUE TITLE
Unexpected: `pillar` command line argument do not respect `pillar_source_merging_strategy`

### ISSUE THREAD

**Issue by uvsmtid** [saltstack/salt#29516]
### Problem

A number of functions supports `pillar` argument to _override_ configured pillar, for example:
- [`state.sls`](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.sls)
- [`pillar.items`](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.sls)

Overriding provided pillar key may feel natural for flat dictionaries.

However, in large config data structure with nested dictionaries this approach doesn't allow setting specific keys only.

Pillar data:

```
a:                                                                              
  b:                                                                            
    c:                                                                          
      d: 1                                                                      
  e:                                                                            
    f:                                                                          
      g: 2                                                                      
  h: 3                                                                          
  i:                                                                            
    j: 4                                                                        
    k: 5                                                                        
l:                                                                              
  m:                                                                            
    n: 6                                                                        
```

Trying to set new value on `pillar['a']['e']['f']['g]` removes ALL(!) adjacent tree branches for the nested dictionaries (leaving only data which lives under another top-level key):

```
salt-call --out yaml pillar.items pillar="{ a: { e: { f: { g: new_value } } } }"

local:
  a:
    e:
      f:
        g: new_value
  l:
    m:
      n: 6
```
### Proposal

There can be a better behaviour. When data grows large in nested way, _merge_ strategy has obvious advantages. And for the primitive pillars (when all required data fits on command line) _merge_ strategy would still be as practical as current _override_ one.

There is already implementation of [`PILLAR_SOURCE_MERGING_STRATEGY`](https://docs.saltstack.com/en/latest/ref/configuration/master.html#pillar-source-merging-strategy) default to `smart` which perfectly works for "defaults and overrides" pattern with configured pillars. If command line arguments supported the same strategy, this greatly simplifies scripting around Salt when user may specify values for limited set of (nested) keys in pillars.

**Should the default strategy be changed to _merge_ which equally adequate for large pillars as well as tiny ones?**
