### ISSUE TITLE
Incorrect Version Information in Grains

### ISSUE THREAD

**Issue by meggiebot** [saltstack/salt#29552]
ZD-398

**Comment by twangboy** [comment]
##### Bug / Issue:

When pulling grains data from minions on OS X, they do not return the sub version of the installed Salt Minion.

(the following are my grains showing this issue)

Version Information: OS X minions do not return the sub-version number.
```
saltpath:
        /usr/local/Cellar/saltstack/2014.7.1/lib/python2.7/site-packages/salt
    saltversion:
        2014.7.0
    saltversioninfo:
        - 2014
        - 7
        - 0
        - 0
```
In addition, the core grain ‘osfinger’ isn’t supported on OS X.

Looking at https://github.com/saltstack/salt/blob/5727d338a425b214ffd8f4f41290839ceb3ba662/salt/grains/core.py it’s simply not a case which is considered.

This should probably return something like “MacOS-10.10”
