### ISSUE TITLE
[BUG] 3001.x and 3002.x file.recurse: "keep_symlinks: True" not working correctly

### ISSUE THREAD

**Issue by m-bastian** [saltstack/salt#29562]
We have the following issue with 2015.8.1 and 2015.8.3 when using file.recurse with keep_symlinks set to True:

A softlink which name is a subset (Like: ^NAME_SOFTLINK\* ) of other filenames in the same directory will let salt ignore these files by the next update. If "clean: True" is set too, these files would be also deleted from the slave. We discovered this while syncing some custom compiled linux libraries with the typical  libxyz.so.X.0.0 -> libxyz.so.X  -> libxyz.so linking.

 A simple example:

```
   mkdir test; cd test
   touch test1 test2 test3
   ln -s test3 test

  cat << EOF > test.sls
   /tmp/test/:
   file.recurse:
     - source: salt://test/
     - include_empty: True
     - clean: True
     - keep_symlinks: True
  EOF
```

The output:

```
----------
          ID: /tmp/test/
    Function: file.recurse
      Result: True
     Comment: Recursively updated /tmp/test/
     Started: 12:00:59.395207
    Duration: 321.6 ms
     Changes:   
              ----------
              /tmp/test/test:
                  ----------
                  new:
                      /tmp/test/test
```

As you see only the symlink survives. All other matching files are ignored.

**Comment by m-bastian** [comment]
One more thing:

if you delete the softlink on the master in the above example and sync again the symlink will not be deleted (clean: True) on the slave and you get the following error:
```
          ID: /tmp/test/
    Function: file.recurse
      Result: False
     Comment: #### /tmp/test/test ####
              Source file salt://|frontend/test/test not found
     Started: 12:25:00.427336
    Duration: 273.43 ms
     Changes:   
```

Only when you add, modify or delete another file and update again the symlink vanishes from the slave.

**Comment by jfindlay** [comment]
@m-bastian, thanks for reporting.  @lorengordon, do you have any ideas on this one?

**Comment by lorengordon** [comment]
Sorry @jfindlay, haven't touched the file.recurse code, only file.replace...so all new to me.

Did this work in earlier versions?

Looking at the [code in the head of 2015.8](https://github.com/saltstack/salt/blob/2015.8/salt/states/file.py#L2266), the problem could be that the way the files are named in this example are matching the `.startswith()` test, resulting in the path getting removed from the list of filenames...?

**Comment by lorengordon** [comment]
@m-bastian, can you run your test with debug logging and let us know if the output contains a string like `'** skipping file ** {0}, it intersects a symlink'`? That should tell us whether the files are matching that test I mentioned and getting removed from the list of files to copy down to the minion...

**Comment by jfindlay** [comment]
@lorengordon, sorry for pinging you, then, but thanks for looking.

**Comment by m-bastian** [comment]
@lorengordon, yes it does:

```
2015-12-10 08:35:31,689 [salt.loaded.int.states.file][DEBUG   ][24980] ** skipping file ** test/test, it intersects a symlink
2015-12-10 08:35:31,689 [salt.loaded.int.states.file][DEBUG   ][24980] ** skipping file ** test/test1, it intersects a symlink
2015-12-10 08:35:31,689 [salt.loaded.int.states.file][DEBUG   ][24980] ** skipping file ** test/test2, it intersects a symlink
2015-12-10 08:35:31,689 [salt.loaded.int.states.file][DEBUG   ][24980] ** skipping file ** test/test3, it intersects a symlink
2015-12-10 08:35:31,691 [salt.utils.lazy  ][DEBUG   ][24980] LazyLoaded user.info
2015-12-10 08:35:31,708 [salt.state       ][INFO    ][24980] {u'/tmp/test/test': {'new': u'/tmp/test/test'}}
```

**Comment by lorengordon** [comment]
I'm not sure what the reasoning is behind the `startswith()` logic, but I do think that is why this isn't working for you.

I looked back through the history for the file state module and found that logic was introduced [here](https://github.com/saltstack/salt/commit/fc1533906dd5d6e58da059564f50cc1db5a868f5), but there isn't an explanation for the approach. I'm guessing it might be something to do with symlinked directories...? The previous approach used something like `if symlinks.get(filename)` in place of this test, but I think with the refactoring that would be equivalent to `if lname == filename`...

**Comment by m-bastian** [comment]
This seems to be the patch that introduced ```keep_symlinks``` and is explained in issue https://github.com/saltstack/salt/issues/5645

**Comment by m-bastian** [comment]
Any update on this?

**Comment by jfindlay** [comment]
@m-bastian, not that I know of.  No one has been assigned to this issue.

**Comment by m-bastian** [comment]
Sorry to nag but ... any update or at least an estimate on this?

**Comment by jfindlay** [comment]
@m-bastian, unfortunately, not yet.  I think we may be able to add this to the list of bugs to work on for the next sprint though.

**Comment by killer2tester** [comment]
Sorry but still not fixed?

**Comment by jfindlay** [comment]
@killer2tester, not that I know of.  We are trying to work through our bug backlog.

**Comment by tastycheesewhiz** [comment]
Any chance this issue is going to be addressed in the near future?

**Comment by rogeriomm** [comment]
Same issue on salt 2017.7.2!

**Comment by m-bastian** [comment]
Still broken in 2018.3 ...

**Comment by jdshewey** [comment]
Still broken in 2019.2

**Comment by dynek** [comment]
I am also having issues deploying/copying symlinks using `file.recuse` and `keep_symlinks: True`.

```
/etc/nginx:
  file.recurse:
    - source: salt://{{slspath}}/files/nginx
    - user: root
    - group: root
    - file_mode: 644
    - sym_mode: 777
    - dir_mode: 755
    - clean: True
    - include_empty: True
    - keep_symlinks: True
    - force_symlinks: True
```

but it ends up with:
![2019-12-22 at 18 37](https://user-images.githubusercontent.com/591091/71325240-19156080-24ea-11ea-8039-7afada0696eb.png)

**Comment by jdshewey** [comment]
@dynek - this looks to be a separate issue. Make sure that the path `./nodes/ocean-10/files/nginx/modules exists on your salt master at whatever the file root is. This is set in /etc/salt/master or /etc/salt/master.d/f_defaults.conf

```
file_roots:
  base:
```

If this is not set, I believe the default path would be /srv/salt/nodes/ocean-10/files/nginx/modules

If you are expecting salt to use another path or environment, you need to set `saltenv` on you salt minion and set a file root for that environment on the master in `file_roots`

**Comment by dynek** [comment]
@jdshewey other files from this directory are copied without any problem.
`modules` is actually a symlink (`modules -> /usr/lib/nginx/modules`) that I want to copy as-is .
`/usr/lib/nginx/modules` doesn't exist on the master.

**Comment by disaster123** [comment]
@dynek: +1 same issue here

**Comment by murzick** [comment]
I'm having issues with file.recurse: keep_symlinks in 3001.3 / 3002.2 versions:
tmp-test-folder:
  file.recurse:
    - name: /tmp/test
    - source: salt://tmp-test/files/tmp/test
    - keep_symlinks: true

a) If symlink target is missing on the salt master, the error message is returned, as @dynek said earlier and symlink is not created on the minion
Comment: #### /tmp/test/a/none ####
Source file salt://tmp-test/files/tmp/test/a/none?saltenv=base not found in saltenv 'base'

b) If symlink on the salt master has an absolute path target (I've created the target on the master, to overcome the issue a) ), the symlink is copied to minion as folder/file instead of keeping it as symlink.
Salt master:
lrwxrwxrwx 1 root root   14 Dec  9 08:04 file -> /tmp/test/file
lrwxrwxrwx 1 root root   17 Dec  9 08:04 folder -> /tmp/test/folder/
Salt minion:
-rw-r--r-- 1 root root    0 Dec  9 08:05 file
drwxr-xr-x 2 root root 4096 Dec  9 08:05 folder/

If symlink on the salt master has an relative path target, it works as expected.
Salt master:
lrwxrwxrwx 1 root root    7 Dec  9 08:17 file -> ../file
lrwxrwxrwx 1 root root   10 Dec  9 08:17 folder -> ../folder/
Salt minion:
lrwxrwxrwx 1 root root    7 Dec  9 08:18 file -> ../file
lrwxrwxrwx 1 root root   10 Dec  9 08:18 folder -> ../folder/

**Comment by anilsil** [comment]
Can this be tested with 3004, please report if you are still seeing the issue?

**Comment by mdione-cloudian** [comment]
what would be the impact of making this code really abide it's documentation? "`keep_symlinks`: Keep symlinks when copying from the source. This option will cause the copy operation to terminate at the symlink. If desire behavior similar to `rsync`, then set this to True." it definitely doesn't behave like `rsync`; the latter actually recreates the symlink on the destination irrespective of it points in or outside the source, or if it even becomes valid in the destination.

**Comment by mdione-cloudian** [comment]
My use case: we want to sync the salt config to a stand by backup master. for that, we have a state (`salt_master`) that includes a symlink pointing to one directory 'above' the root of the salt config, as:

```
[root@demo3-node1 7.5]# namei -lx /opt/cloudian-salt/7.5/cluster/states/salt_master/files/cloudian-salt
f: /opt/cloudian-salt/7.5/cluster/states/salt_master/files/cloudian-salt
Dr-xr-xr-x root     root     /
drwxr-xr-x root     root     opt
drwxr-xr-x root     root     cloudian-salt         <-- symlink points here
drwxrwxr-x cloudian cloudian 7.5                   <-- salt config starts here
drwxrwxr-x cloudian cloudian cluster
drwxrwxr-x cloudian cloudian states                <-- this one is listed in file_roots.base
drwxr-xr-x cloudian cloudian salt_master
drwxr-xr-x cloudian cloudian files
lrwxrwxrwx cloudian cloudian cloudian-salt -> /opt/cloudian-salt
Dr-xr-xr-x root     root       /
drwxr-xr-x root     root       opt
drwxr-xr-x root     root       cloudian-salt
```

and the state:

```yaml
sync_salt_base:
  file.recurse:
    - name: /opt/cloudian/7.5
    - source: salt://salt_master/files/cloudian-salt/7.5
    - file_mode: keep
    # clean removes everything not sync'ed by Salt. Thus, also sync empty directories,
    # or they'll be removed all the time, and re-created by salt-master.
    - clean: True
    - include_empty: True
    # this makes it stop at symlinks, and for some reason is not True by default
    - keep_symlinks: True
    # just in case there's some garbage there
    - force_symlinks: True
```
