### ISSUE TITLE
Duplicated MTU entry added

### ISSUE THREAD

**Issue by javicacheiro** [saltstack/salt#29598]
Using the mtu option of the network.managed state generates a duplicated "MTU=9000" entry in ifcfg-eno2:

```
eno2:
  network.managed:
    - enabled: True
    - type: slave
    - master: bond0
    - mtu: 9000
```

Results in:

```
[root@c13-2 etc]# cat /etc/sysconfig/network-scripts/ifcfg-eno2
DEVICE="eno2"
USERCTL="no"
MASTER="bond0"
SLAVE="yes"
BOOTPROTO="none"
ONBOOT="yes"
MTU="9000"
MTU="9000"
```

Tested in CentOS 7.
