### ISSUE TITLE
pillars not merging properly with 2015.8.3

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#29601]
I'm using a combination of static pillars and ext_pillars.  Since updating from 2015.8.1 to 2015.8.3, my ext_pillars aren't merging properly.  Here's an example of my pillar.items from 2015.8.1 vs. 2015.8.3:
```diff
diff -Naur 2015.8.1 2015.8.3 
--- 2015.8.1	2015-12-10 11:27:15.540000000 -0700
+++ 2015.8.3	2015-12-10 11:28:19.520000000 -0700
@@ -340,22 +340,6 @@
             when:
                 1:15am
     services:
-        - crond.service
-        - default.target
-        - getty@.service
-        - iscsid.service
-        - microcode.service
-        - multi-user.target
-        - postfix.service
-        - rngd.service
-        - rsyslog.service
-        - salt-minion.service
-        - sshd.service
-        - systemd-readahead-collect.service
-        - systemd-readahead-drop.service
-        - systemd-readahead-replay.service
-        - zabbix-agent.service
-        - acpid.service
         - salt-api.service
         - salt-master.service
     users:
```
It gets worse if I set ext_pillar_first: True:
```diff
diff -Naur 2015.8.1 2015.8.3-ext_pillar_first 
--- 2015.8.1	2015-12-10 11:27:15.540000000 -0700
+++ 2015.8.3-ext_pillar_first	2015-12-10 11:29:55.350000000 -0700
@@ -1,41 +1,9 @@
 local:
     ----------
-    exclude_updates:
-        - MySQL-python
-        - PyYAML
-        - bs-iser-utils
-        - centos-release*
-        - kernel*
-        - python-jinja2
-        - python-tornado
-        - python-zmq
-        - salt*
-        - zabbix*
-        - zeromq
     member_groups:
         ----------
         developer:
         support:
-    metadata:
-        ----------
-        cpus:
-            4
-        hostname:
-            provo-salt-master-0-11.betterservers.com
-        interfaces:
-            ----------
-            0:
-                10.73.0.11
-        memory:
-            4096
-        physical:
-            0
-        secondary_roles:
-            None
-        size:
-            1024000
-        status:
-            ACTIVE
     metadata.db:
         servers
     metadata.host:
@@ -308,9 +276,6 @@
             2.2.11-1.el7
         zeromq:
             4.0.5-4.el7
-    roles:
-        - services.salt-api
-        - services.salt-master
     schedule:
         ----------
         highstate:
@@ -356,8 +321,6 @@
         - systemd-readahead-replay.service
         - zabbix-agent.service
         - acpid.service
-        - salt-api.service
-        - salt-master.service
     users:
         ----------
         blangus:
```
And regardless of what pillar_source_merging_strategy I set, which currently is the default of smart, nothing changes.  For now, I'm sticking with 2015.8.1, where things work.
```yaml
salt --versions
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 4.1.13.bs.ufd
         system: CentOS Linux 7.1.1503 Core
```
