### ISSUE TITLE
What's the best practice for managing multiple projects with a single master?

### ISSUE THREAD

**Issue by matthayes** [saltstack/salt#29614]
I have a couple git projects that I would like to deploy through a single Salt master.  I've been thinking about how to set this up (I'm kind of new to Salt).  

So far what I've come up with is that I have the two projects' code be deployed to two separate directories `projectA_root` and `projectB_root` and have a top.sls that references SLS files within these directories.
- /srv/salt/common/top.sls
- /srv/salt/projectA_root/projectA/...(sls files)
- /srv/salt/projectB_root/projectB/...(sls files)

In my `/etc/salt/master` file:

```
file_roots:
  base:
    - /srv/salt/projectA_root
    - /srv/salt/projectB_root
```

Then in my `/srv/salt/common/top.sls` file:

```
base:
  'roles:service-foo':
    - match: grain
    - projectA.service-foo

  'roles:service-bar':
    - match: grain
    - projectA.service-bar

  'roles:service-baz':
    - match: grain
    - projectB.service-baz
```

You can see in this example I have a couple services defined in projectA and one service in projectB.

So the way deployment would work for projectA is:
1. Sync projectA's files over to /srv/salt/projectA_root
2. Run state.highstate for projectA's services

Initially I was thinking that I could have a `top.sls` defined per project that would only contain the services relevant to it, but then I realized that this won't work because the top files are only merged for environments, not multiple file_roots (correct me if I'm wrong).

What's the best practice for this type of situation where you have separate repos with one or more services defined in each one?  With this setup I described, the projects can deploy code independently.  But, one downside with this approach is that the `top.sls` has to be managed somehow, separately, as it's the source of truth for what services are matched to which roles.
