### ISSUE TITLE
States that require another state with order: last should inherit that order

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#29618]
```
root@orchestration:~# cat /srv/salt/test.sls 
state-a:
  test.nop:
    - order: last

state-b:
  test.nop:
    - require:
      - test: state-a

state-c: test.nop
root@orchestration:~# salt 'dummy*' state.apply test
dummy.test.vagrant.local:
  Name: state-a - Function: test.nop - Result: Clean Started: - 09:21:45.204696 Duration: 0.553 ms
  Name: state-b - Function: test.nop - Result: Clean Started: - 09:21:45.205411 Duration: 0.319 ms
  Name: state-c - Function: test.nop - Result: Clean Started: - 09:21:45.205814 Duration: 0.217 ms
```

I expect state B to "inherit" the `order: last` from state A. The order should be C, A, B.

If I add an `order: last` to state B, the order is as I want it to be.

**Comment by jfindlay** [comment]
@anlutro, thanks for the report.
```yaml
# salt jmoney-main state.show_sls ord
jmoney-main:
    ----------
    state-a:
        ----------
        __env__:
            base
        __sls__:
            ord
        test:
            |_
              ----------
              order:
                  last
            - nop
    state-b:
        ----------
        __env__:
            base
        __sls__:
            ord
        test:
            |_
              ----------
              require:
                  |_
                    ----------
                    test:
                        state-a
            - nop
            |_
              ----------
              order:
                  10000
    state-c:
        ----------
        __env__:
            base
        __sls__:
            ord
        test:
            - nop
            |_
              ----------
              order:
                  10001
```
```yaml
# salt jmoney-main state.apply ord
jmoney-main:
----------
          ID: state-a
    Function: test.nop
      Result: True
     Comment: Success!
     Started: 11:17:35.156076
    Duration: 0.844 ms
     Changes:
----------
          ID: state-b
    Function: test.nop
      Result: True
     Comment: Success!
     Started: 11:17:35.157251
    Duration: 0.861 ms
     Changes:
----------
          ID: state-c
    Function: test.nop
      Result: True
     Comment: Success!
     Started: 11:17:35.158367
    Duration: 0.792 ms
     Changes:

Summary for jmoney-main
------------
Succeeded: 3
Failed:    0
------------
Total states run:     3
Total run time:   2.497 ms
```console
# salt --version
salt 2015.8.3 (Beryllium)
```

**Comment by thusoy** [comment]
I've recently come across this as well, but only when the `order: last` is in a sls that is included from another state.

Thus with a state like this:
```yaml
# ordering.sls
the-file:
    file.managed:
        - name: /tmp/ordering.txt
        - source: salt://ordering.txt
        - template: jinja

last-line:
    file.accumulated:
        - name: lines
        - filename: /tmp/ordering.txt
        - text: last
        - order: last
        - require_in:
            - file: the-file
```
and in another state:
```yaml
# ordering2.sls
include:
    - ordering

somewhere-in-the-midle:
    file.accumulated:
        - name: lines
        - text: anywhere but last
        - filename: /tmp/ordering.txt
        - require_in:
            - file: the-file
```

and the template:
```
{% for line in accumulator['lines'] -%}
{{ line }}
{% endfor %}
```

Now, the results depend on how the state is called. If `ordering2` is added to the topfile the order will be correct when run through a highstate call. However, `state.sls ordering2` will yield the wrong order.
