### ISSUE TITLE
dockerng: docker-py version requirement possibly higher than documented.

### ISSUE THREAD

**Issue by RPDiep** [saltstack/salt#29620]
On CentOS, with python-docker-py installed ( 1.4.0 ), dockerng.running fails with

```
          ID: varnish
    Function: dockerng.running
      Result: False
     Comment: Failed to create new container: 'Client' object has no attribute 'create_host_config'
     Started: 10:03:23.220563
    Duration: 18.268 ms
     Changes:   
```

Only after installing docker-py through pip ( 1.6.0 ), the state succeeds.
