### ISSUE TITLE
user.present does not modify home directory

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#29633]
user.present will not modify the home directory in /etc/passwd unless createhome is set to true.   modification of the home directory should not be dependent on createhome being True.

Appears to be similar to closed case  #15649

**test.sls**
```
testuser_create:
  user.present:
    - name: testuser
    - home: /home/testuser
    - createhome: True

testuser_change_homedir_createTrue:
  user.present:
    - name: testuser
    - home: /home/testuser2
    - createhome: True

testuser_change_homedir_createFalse:
  user.present:
    - name: testuser
    - home: /home/testuser3
    - createhome: False

testuser_show_etc_passwd:
  cmd.run:
    - name: grep testuser /etc/passwd
```

**State run**
```
----------
          ID: testuser_create
    Function: user.present
        Name: testuser
      Result: True
     Comment: Updated user testuser
     Started: 19:39:22.706569
    Duration: 25.191 ms
     Changes:
              ----------
              home:
                  /home/testuser
----------
          ID: testuser_change_homedir_createTrue
    Function: user.present
        Name: testuser
      Result: True
     Comment: Updated user testuser
     Started: 19:39:22.732123
    Duration: 12.238 ms
     Changes:
              ----------
              home:
                  /home/testuser2
----------
          ID: testuser_change_homedir_createFalse
    Function: user.present
        Name: testuser
      Result: True
     Comment: User testuser is present and up to date
     Started: 19:39:22.744655
    Duration: 1.326 ms
     Changes:
----------
          ID: testuser_show_etc_passwd
    Function: cmd.run
        Name: grep testuser /etc/passwd
      Result: True
     Comment: Command "grep testuser /etc/passwd" run
     Started: 19:39:22.746790
    Duration: 4.618 ms
     Changes:
              ----------
              pid:
                  14248
              retcode:
                  0
              stderr:
              stdout:
                  testuser:x:1005:1006::/home/testuser2:

Summary
------------
Succeeded: 4 (changed=3)
Failed:    0
------------
Total states run:     4
```

**versions**
```
# salt --versions-report
           Salt: 2015.5.8
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.4.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 2.4.2
# salt test-server-234 cmd.run "salt-minion --version"
test-server-234:
    salt-minion 2015.5.8 (Lithium)
```
