### ISSUE TITLE
File.managed context from etcd pillar cannot handle unicode. yaml render error

### ISSUE THREAD

**Issue by aalba6675** [saltstack/salt#29652]
test/init.sls:

``` sls
test:
  file.managed:
    - source: salt://test/test.j2
    - name: /var/tmp/test.out
    - template: jinja
    - context: {{ pillar.hello_dir }}
test/test.j2:
{{ hello }}
```

etcd:

```
etcdctl -C 127.0.0.1:2379 set /salt/hello_dir/hello  "hello:world"
```

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:test' failed: Unknown yaml render error; line 6

---
test:
  file.managed:
    - source: salt://test/test.j2
    - name: /var/tmp/test.out
    - template: jinja
    - context: {'hello': u'hello:world'}    <======================
```

pillar.hello_dir is passed as context "yaml" file with unicode, this cause the renderer to break.

If I do not use context but access as
{{ pillar.hello_dir.hello }}
it works
