### ISSUE TITLE
onfail_in not working as expected

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#29665]
Hello,

I create this issue after discussing this in salt-users;

I want to check my minions for a running mysql server on localhost port 3306 using the following test state;

```
port-3306-open:
  module.run:
    - name: network.connect
    - host: localhost
    - port: 3306
    - onfail_in:
      - cmd: no-mysql

no-mysql:
  cmd.run:
    - name: echo mysql not reachable on port 3306
```

For some reason the onfail_in never gets triggered even when the port is unreachable and Result is False. This is the output;

```
          ID: port-3306-open
    Function: module.run
        Name: network.connect
      Result: True
     Comment: Module function network.connect executed
     Started: 16:28:52.871350
    Duration: 2.663 ms
     Changes:
              ----------
              ret:
                  ----------
                  comment:
                      Unable to connect to localhost (127.0.0.1) on tcp port 3306
                  result:
                      False
  Name: echo mysql not reachable on port 3306 - Function: cmd.run - Result: Clean
```

I would expect that the no-mysql: id would get executed but this is not the case.
