### ISSUE TITLE
salt-ssh, tty, sudo: Permission denied: '/tmp/.salt_xxxxxx_salt/running_data/var'

### ISSUE THREAD

**Issue by dr4Ke** [saltstack/salt#29699]
On CentOS 6, versions:
```
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.11.2.el6.x86_64
         system: CentOS 6.5 Final
```

A simple state `common/ntp.sls`:
```
ntp:
  pkg.installed

ntpd:
  service:
    - running
    - watch:
      - file: /etc/ntp.conf

/etc/ntp.conf:
  file.managed:
    - source: salt://common/ntp.conf
    - require:
      - pkg: ntp
```

Execution:
```
$ salt-ssh node state.sls common.ntp
node:
    An Exception occurred while executing state.sls: [Errno 13] Permission denied: '/tmp/.salt_23460e_salt/running_data/var'
```
