### ISSUE TITLE
New URI scheme `minion_script_output://path/to/script`

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#29698]
I would like to have a new URI scheme in salt:

minion_script_output://path/to/script

`minion_script_output` is the scheme: A script on the minion gets called and the stdout gets used as file.

`/path/to/script` is the path to the script.

Would you accept a pull request which does implement this?

Or is this already possible without patching salt?

My use case is explained here: http://stackoverflow.com/questions/34181645/salt-use-script-output-as-source-string

**Comment by basepi** [comment]
I think rather than adding this to the fileserver as a first class URI scheme, maybe we should just add it to the file.managed state....something like `contents_script` and give it the script path.

You can actually probably get this done right now via `contents`, something like this:

```
put_script_output_in_file:
  file.managed:
    - name: /tmp/something
    - contents: |
        {{ salt['cmd.script']('myscript') }}
```

The only question is whether jinja would insert all the contents indented so YAML would take it properly or not.

Thoughts?
