### ISSUE TITLE
cron.present should add a newline at the end of the last job entry

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#29694]
Non working, salt generated example:

```
rsyncuser@hss300[hss300]:~ $ crontab -l
# Lines below here are managed by Salt, do not edit
# SALT_CRON_IDENTIFIER:update_arcontent
2,17,32,47 * * * * /home/rsyncuser/bin/update_arcontent.sh
rsyncuser@hss300[hss300]:~ $ 
```

Fixed manually by adding a newline at the end:

```
rsyncuser@hss148[hss148]:/data/arcontent $ crontab -l
# Lines below here are managed by Salt, do not edit
# SALT_CRON_IDENTIFIER:update_arcontent
2,17,32,47,54 * * * * /home/rsyncuser/bin/update_arcontent.sh

rsyncuser@hss148[hss148]:/data/arcontent $ 
```

Running on CentOS 6.2. Version info follows.

```
root@hss300[hss300]:/data/arcontent # salt-call test.versions_report
local:
               Salt: 2015.5.3
             Python: 2.6.6 (r266:84292, Dec  7 2011, 20:48:22)
             Jinja2: 2.7.3
           M2Crypto: 0.20.2
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: 1.4.3
             PyYAML: 3.11
              ioflo: 1.3.2
              PyZMQ: 14.3.1
               RAET: 0.6.3
                ZMQ: 4.0.4
               Mako: Not Installed
            Tornado: Not Installed
```

**Comment by jfindlay** [comment]
@ahammond, thanks for the report.  Do you know if this happens with more recent versions of salt?  What salt command(s) have you used to generate failing crontabs?

**Comment by ahammond** [comment]
I haven't had time to try upgrading to 2015.8.2 yet and it's unlikely to happen for a few months yet. State follows:

```
/home/rsyncuser/bin/update_arcontent.sh:
  file.managed:
    - source: {{ file_path }}/update_arcontent.sh
    - mode: '0755'
    - makedirs: True
  cron.present:
    - identifier: update_arcontent
    - user: rsyncuser
    - minute: 2,17,32,47
    - require:
      - file: /data
      - file: /home/rsyncuser/bin/update_arcontent.sh
      - file: /home/rsyncuser/rsync_passwords/rsyncuser.txt
```

**Comment by ahammond** [comment]
Workaround addition:

```yaml
# Hack to add newline to end of crontab for rsyncuser.
hack_on_a_newline:
  cmd.run:
    - name: ( crontab -l -u rsyncuser 2>/dev/null; echo "" ) | crontab -u rsyncuser -
    - unless: test "x" == "x$(crontab -l -u rsyncuser 2>/dev/null | tail -1)"
    - require:
      - cron: /home/rsyncuser/bin/update_arcontent.sh
```
