### ISSUE TITLE
[REGRESSION] [MAJOR] [CRITICAL] retrocompat of pkg.latest

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#29735]
```
               ID: makina-nginx-pkgs
         Function: pkg.latest
           Result: False
          Comment: pkg.latest does not work with the watch requisite, please use pkg.wait
          Started: 11:08:08.227955
         Duration: 0.671 ms
         Changes:   

```

Again a retrocompat bug, dying here because we used a watch rather than a require is a total nonsense.
I'm ok that pkg.latest will not react on a watch, i'm not OK for it to die, moreover on states i wrote a LONG while ago...
We should make the state warn (yellow) and put the comment, but dying is too hard...
Watch is "just" a specilized require, afterall.

cc @thatch45 @basepi
