### ISSUE TITLE
Data / Dicts from included pillar files are not directly usable / available in for loops?

### ISSUE THREAD

**Issue by michaelkarrer81** [saltstack/salt#29755]
I import some pillar files in an other pillar file with:
``` yaml
# /srv/pillar/pgsql.sls
{% set instance_files = salt.cmd.run('find /srv/pillar/instances -maxdepth 1 -type f -iname "*.sls" -printf "%f\n"').split() %}
include:
  {% for file in instance_files %}
      - instances.{{ file|replace(".sls", "") }}
  {% endfor %}
```

The importet pillar files all have the same structure:
``` yaml
# /srv/pillar/instances/20000_dadi.sls
instances:
  dadi:
    port: 20000
    online:
      odoo_master_pw: 12345
      odoo_admin_pw: admin#1
      linux_pw: admin#1
      database_pw: admin#1
    studio:
      admin_pw: admin#2
```

Now i want to iterate through the imported and merged dict "instances" but this seems not possible:
``` yaml
# /srv/pillar/pgsql.sls
postgres:
  # Create the database user per instance
  users:
{% for instance in salt.pillar.get('instances') %}
    {{ instance }}:
      ensure: present
      password: {{ instance }}
      createdb: False
      createroles: False
      createuser: False
      inherit: True
      replication: False
{% endfor %}
```

I seems that the dictionary is not yet available? Is this a chicken egg problem or did i simply misunderstand how to correctly use the dict from the imported pillar files?
