### ISSUE TITLE
service.running not found in salt 2015.8.3

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#29768]
I had a salt state that worked fine before I upgraded to the latest open source salt version. 

Here's the state:
```
Install and run service 'at' (job scheduler):
  pkg.installed:
    - name: at
  service.running:
    - name: atd
    - enable: True
    - watch: 
      - pkg: Install and run service 'at' (job scheduler)
```

Here's the error I get:
```
----------
          ID: Install and run service 'at' (job scheduler)
    Function: service.running
        Name: atd
      Result: False
     Comment: State 'service.running' was not found in SLS 'test'
              Reason: 'service' __virtual__ returned False
     Started: 
    Duration: 
     Changes:   
```

Here's versions report:
```
    Salt Version:
               Salt: 2015.8.3
     
    Dependency Versions:
             Jinja2: unknown
           M2Crypto: 0.20.2
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
             Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: oracle 6.7 
            machine: x86_64
            release: 3.8.13-98.4.1.el6uek.x86_64
             system: Oracle Linux Server 6.7 
```

Notice that even the Jinja2 version says unknown even though Jinja is installed on the server.
