### ISSUE TITLE
output_loglevel: quiet in cmd.run not working ?

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#29764]
From documentation I think this should work:

> output_loglevel
> Control the loglevel at which the output from the command is logged. Note that the command
> being run will still be logged (loglevel: DEBUG) regardless, unless quiet is used for this value.

```
root@saltmaster:~# lsb_release -d
Description:    Debian GNU/Linux 8.2 (jessie)
root@saltmaster:~# salt-call --version
salt-call 2015.8.3 (Beryllium)
```

state is defined between ELBs as:

```
throttling-for-ELB-{{ store }}-{{ pool }}-{{ environment }}-{{ aws_region }}:
  cmd.run:
    - name: salt-call test.sleep 2
    - output_loglevel: quiet
```

and gave still this output:

```
          ID: throttling-for-ELB-DE-yves-staging-eu-central-1
    Function: cmd.run
        Name: salt-call test.sleep 2
      Result: True
     Comment: Command "salt-call test.sleep 2" run
     Started: 19:20:18.614555
    Duration: 3040.192 ms
     Changes:
              ----------
              pid:
                  5310
              retcode:
                  0
              stderr:
              stdout:
                  local:
                      True
```

(mmh, and 3 seconds but not 2 ?)

**Comment by jfindlay** [comment]
@Reiner030, the `output_loglevel` controls the logging level at which commands sent through `cmd.run*` are logged.  This log information appears in the log file and on the terminal if you run the minion in the foreground.  To suppress command output, use the `quiet` outputter: `salt --output=quiet minion state.apply elb_throttle`.  Also see `salt --help | grep -E -A5 -- '--output='`.

**Comment by Reiner030** [comment]
Sorry, overseen last days the update of this issue.
The problem is here that I want my states (changed/unchanged) commonly shown. So --output=quiet is not the right choice... 

If the output_loglevel only drops the log output only (checked... yes works nice) it would be then nice/feature request to have same state parameter like ````output_level = quiet````, too?
Didn't know how often this special case could be commonly of interest but normal
````{% salt['cmd.run']('sleep 1') %}```` e.g. would only be executed when parsing the files.

There are also other cases where I miss "runtime" state dependencies especially from cmd.* states. Perhaps the ````- stateful```` parameter is for this case but nowhere helpful documented yet.

**Comment by Reiner030** [comment]
Because of some other debugging:
Here is only the stupid solution missing that the task should finish with "Clean" instead of "Changed"..

This would be nice to documentate how saltstack checks which state an external command has  e.g.
like Nagios services:
exit status 0 => OK
exit status 1 => WARNING
exit status 2 => CRITICAL
exit status 3 => UNKNOWN

**Comment by rallytime** [comment]
@Reiner030 Do the `state_output` options help you here? https://docs.saltstack.com/en/latest/ref/output/all/salt.output.highstate.html

**Comment by azmng** [comment]
'output_loglevel: quiet'  still shows full cmd.run output in version 2016.11.5
Also tried 'quiet: True' with the same result: full cmd.run output shown.

**Comment by peterrus** [comment]
Also seem to be having this issue

```
netdatainstall:
  require:
    - git: netdatarepo
    - pkg: netdatarequisites
  cmd.run:
    - cwd: /root/netdatagit
    - name: ./netdata-installer.sh
    - output_loglevel: quiet <----- this seems ok right?
```
