### ISSUE TITLE
Add Pillar SQLCipher module

### ISSUE THREAD

**Issue by akissa** [saltstack/salt#29781]
SQLCipher is an open source extension to SQLite that provides transparent 256-bit AES encryption of database files.

* https://www.zetetic.net/sqlcipher/
* https://pypi.python.org/pypi/pysqlcipher

It is good to have support for retrieving Pillar data via queries to SQLCipher databases.

```
pillar:
  sqlcipher:
    database: '/var/lib/salt/pillar-sqlcipher.db'
    pass: strong_pass_phrase
    timeout: 5.0

ext_pillar:
  - sqlcipher:
      fromdb:
        query: 'SELECT col1,col2,col3,col4,col5,col6,col7
                  FROM some_random_table
                 WHERE minion_pattern LIKE ?'
        depth: 5
        as_list: True
        with_lists: [1,3]
```
