### ISSUE TITLE
gitfs: No address associated with hostname for https protocol

### ISSUE THREAD

**Issue by liamdawson** [saltstack/salt#29790]
When attempting to use a gitfs remote that's found via https, I get the following error:

```
2015-12-17 14:38:03,280 [salt.utils.gitfs ][ERROR   ][4723] Exception 'Failed to resolve address for https: No address associated with hostname' caught while fetching gitfs remote 'https://git.company.com/salt/salt-states.git'
```

The relevant changes I make to the master config are:

```
gitfs_provider: pygit2
```

and

```
fileserver_backend:
  - git
  - roots

file_roots:
  base:
    - /srv/salt

gitfs_remotes:
  - https://git.company.com/salt/salt-states.git
  - git://github.com/saltstack-formulas/docker-formula.git

pillar_roots:
  base:
    - /srv/pillar
```

From `pip list`:

```
pygit2 (0.23.1)
```

installed on libgit2 v0.23.3.

Changing `https:` to `git:` gives a connection refused error instead. Changing the github remote to `https:` gives the same error.

```
# salt-master --version
salt-master 2015.8.3 (Beryllium)
```
