### ISSUE TITLE
git.latest with depth stopped working in v2015.8.3

### ISSUE THREAD

**Issue by eburghar** [saltstack/salt#29806]
git.latest state stops working on v2015.8.3. It was working perfectly in v2015.8.0.

git version on minion is 1.9.1

With a state like

```yaml
  git.latest:
    - name: ssh://...
    - rev: ...
    - depth: 1
    - target: ...
    - user: ...
```
It gives

```
fatal: Could not parse object $commit_hash
Changes already made: ssh://... cloned to ...
```

adding a branch argument

```yaml
  git.latest:
    - name: ssh://...
    - rev: x
    - branch: x
    - depth: 1
    - target: ...
    - user: ...
```

gives

```
command 'git checkout -b x origin/x' failed
Changes already made: ssh://... cloned to ...
```

In both case I end up with a clone/checkout of depth 1 but from remote/master not branch.

Without depth argument, both examples are working as expected (correct branch)
