### ISSUE TITLE
startup_state not running on masterless minion

### ISSUE THREAD

**Issue by gravitypaint** [saltstack/salt#29835]
Hi,

I am trying to run a highstate at startup on a masterless minion, but have so far been unsuccessful. Running the highstate, or an individual state on the masterless minion works as expected, however it does not run when the minion service is restarted, or the server is rebooted.

In my minion file I have the following settings

``` yaml
startup_states: 'highstate'
file_client: local
```

and I have a `top.sls` file in `/srv/salt/` which calls my state file `start.sls` in the directory `start`.
I have tried moving the `start.sls` out of the directory, and also tried calling that directly from the minion config file using `startup_states: sls` and listing it below.

``` yaml
salt-call --versions-report
           Salt: 2015.5.5
         Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

Thanks

**Comment by jfindlay** [comment]
@gravitypaint, thanks for reporting.  I think a working example should look like this:
```sls
# minion config
startup_states: 'highstate'
file_client: local
```
```console
# tree /srv/salt
/srv/salt
├── top.sls
└── start
    └── init.sls
```
```sls
# cat /srv/salt/top.sls
base:
  '*':
    - start
```
```sls
# cat /srv/salt/start/init.sls
start_things:
  test.succeed_with_changes:
    - name: yes
```
The important detail being that if `start` is a directory in `/srv/salt`, then there needs to be an `init.sls` immediately under that directory.  You could alternatively move `/srv/salt/start/init.sls` to `/srv/salt/start.sls` and `rmdir /srv/salt/start` without needing to modify the top file.  This paradigm imitates python's [packages and modules](https://docs.python.org/3/tutorial/modules.html#packages) as directories and files layout.

**Comment by jfindlay** [comment]
@gravitypaint, also you can install the current release of salt from https://repo.saltstack.com/.

**Comment by gravitypaint** [comment]
Hi @jfindlay I have previously tried moving my start.sls state to the /srv/salt directory, and also having an init.sls in the start directory as you described, neither of which seem to work.
I would prefer not to update salt as we are currently using the epel repo to install on our minions, and 2015.5.5 is the most recent version there.
Is there anything else I can provide to help troubleshoot this?

**Comment by jfindlay** [comment]
@gravitypaint, I doubt that `startup_states` is broken on 2015.5.5 and not on 2015.8, but I could be wrong.  Are you able to run with:
```sls
startup_states: sls
sls_list: start
```

**Comment by gravitypaint** [comment]
@jfindlay I have checked with startup_states and sls_list set, and this does not seem to work either.

**Comment by jfindlay** [comment]
@gravitypaint, I am able to get this to work on 2015.8.3.
```yaml
# cat /etc/salt/minion
log_fmt_console: '%(colorlevel)s %(colormsg)s'
file_client: local
startup_states: sls
sls_list:
  - start
```
```yaml
# cat /srv/salt/start.sls
start_things:
  test.succeed_with_changes:
    - name: yes
```
```console
# salt-minion -l debug
...
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/start.sls' using 'jinja' renderer: 0.00103402137756
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/start.sls:
start_things:
  test.succeed_with_changes:
    - name: yes

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('start_things', OrderedDict([('test.succeed_with_changes', [OrderedDict([('name', True)])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/start.sls' using 'yaml' renderer: 0.00183415412903
[DEBUG   ] LazyLoaded test.succeed_with_changes
[INFO    ] Running state [start_things] at time 11:05:40.057953
[INFO    ] Executing state test.succeed_with_changes for start_things
[INFO    ] Made the following changes:
'testing' changed from 'Unchanged' to 'Something pretended to change'

[INFO    ] Completed state [start_things] at time 11:05:40.058846
```
