### ISSUE TITLE
State 'at.present' was not found in SLS in 2015.8.1

### ISSUE THREAD

**Issue by ch-acctg** [saltstack/salt#29859]
Any idea why salt 2015.8.1 cannot find the at state?

State 'at.present' was not found in SLS 'services.consul.service'
Reason: 'at' __virtual__ returned False

```
run-consul-alerts-setup:
  at.present:
    - job: '/usr/local/bin/consul-alerts-setup.sh'
    - timespec: 'now + 5 minutes'
```
