### ISSUE TITLE
Git state - missing value for rev directive leads to a python error

### ISSUE THREAD

**Issue by mcassuto** [saltstack/salt#29870]
# Versions
- Ubuntu 14.04.3 LTS
- salt-common  2015.8.3+ds-1
- salt-minion 2015.8.3+ds-1
# State detail

```
ssh://gerrit.pp.com/pp-legacy/ppWeb
  git.latest:
    - target: /srv/web
    - rev: v4.1.1
    - force: True}
    - force_checkout: False
    - force_reset: False
    - always_fetch: True
    - require_in:
      - file: /srv/web
```
# Error log

```
ID: ssh://gerrit.pp.com/pp-legacy/ppWeb
    Function: git.latest
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 519, in latest
                  if remote_rev_type == 'sha1':
              UnboundLocalError: local variable 'remote_rev_type' referenced before assignment
     Started: 16:24:11.221248
    Duration: 359.954 ms
     Changes:   
```
