### ISSUE TITLE
Add PostgreSQL Language management functionality

### ISSUE THREAD

**Issue by akissa** [saltstack/salt#29874]
It would be handly for `Salt` to support management of `PostgreSQL` languages for `PostgreSQL` versions < 9.1. `PostgreSQL` versions >= 9.1 languages can be managed using the `postgres_extension` state module.

* http://www.postgresql.org/docs/8.4/interactive/sql-createlanguage.html

Support should be added to the postgres execution module and a new state module.

The `postgres` execution module should be support:

* Listing languages
* Checking for existence
* Creation
* Removal

The `postgres_language` module should support:

* Creation
* Removal

```
plpgsql:
  postgres_language.present:
    - maintenance_db: testdb

plpgsql:
   postgres_language.absent:
      - maintenance_db: testdb
```
