### ISSUE TITLE
Replacing grains list value with a list value causes error.

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#29889]
Hello,
I'm using salt version:
```
~ # salt-call test.version
local:
    2015.8.3
```

I have a minion with a following grains list value:
```
~ # salt-call grains.get redis_instances
local:
    - 10.0.0.10:6929
    - 10.0.0.10:6920
    - 10.0.0.10:6925
```

Which I want to update with this state:
```
redis_instances_grain:
  grains.present:
    - name: redis_instances
    - value: ['10.0.0.10:6929', '10.0.0.10:6924', '10.0.0.10:6920', '10.0.0.10:6925']
```

And I get an error:
```
----------
          ID: redis_instances_grain
    Function: grains.present
        Name: redis_instances
      Result: False
     Comment: The key 'redis_instances' exists but is a dict or a list. Use 'force=True' to overwrite.
     Started: 13:31:38.698805
    Duration: 0.53 ms
     Changes:   
----------
```
