### ISSUE TITLE
Salt pkg.uptodate fails on Arch linux

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#29880]
Hi,

The following state fails on Archlinux

```
uptodate:
  pkg.uptodate: []
```

This triggers following the error;

```
skynet.
----------
          ID: uptodate
    Function: pkg.uptodate
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1594, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1808, in uptodate
                  updated = __salt__['pkg.upgrade'](refresh=refresh, **kwargs)
              TypeError: upgrade() got an unexpected keyword argument '__agg__'
     Started: 20:18:41.390723
    Duration: 1848.303 ms
     Changes:

Summary for skynet
------------
Succeeded: 0
Failed:    1
```

I tried disabling Cython but that didn't help.

```
    Salt Version:
               Salt: 2015.8.3

    Dependency Versions:
             Jinja2: 2.8
           M2Crypto: 0.21.1
               Mako: 1.0.1
             PyYAML: 3.11
              PyZMQ: 15.1.0
             Python: 2.7.11 (default, Dec 11 2015, 05:34:18)
               RAET: 0.6.3
            Tornado: 4.3
                ZMQ: 4.1.3
               cffi: 1.4.1
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: 1.3.7
            libnacl: 1.4.3
       msgpack-pure: 0.1.3
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: 0.2.4

    System Versions:
               dist:
            machine: armv7l
            release: 4.1.13-1-ARCH
```
