### ISSUE TITLE
windows state.service com_error

### ISSUE THREAD

**Issue by deutsche** [saltstack/salt#29891]
I am run simple state for Windows Minion. Minion is throwing a exception from com:
"(-2147221005, '\xcd\xe5\xe4\xee\xef\xf3\xf1\xf2\xe8\xec\xe0\xff \xf1\xf2\xf0\xee\xea\xe0 \xf1 \xf3\xea\xe0\xe7\xe0\xed\xe8\xe5\xec \xea\xeb\xe0\xf1\xf1\xe0', None, None)"

String '\xcd\xe5\xe4\xee\xef\xf3\xf1\xf2\xe8\xec\xe0\xff \xf1\xf2\xf0\xee\xea\xe0 \xf1 \xf3\xea\xe0\xe7\xe0\xed\xe8\xe5\xec \xea\xeb\xe0\xf1\xf1\xe0 is in russian language.
```
Недопустимая строка с указанием класса
```
This is in translate from russian: ``` Invalid class string```

minion.sls 
```
salt-minion:
  service:
    - running
    - enable: True
    - watch:
      - file: 'C:\salt\conf\minion.d\*.conf'

C:\salt\conf\minion.d\test.conf:
  file:
    - managed
    - makedirs: true
    - contents: 'grains: { foo: bar }'
```

```
salt 'terminal' state.sls minion 
terminal:
----------
          ID: C:\salt\conf\minion.d\test.conf
    Function: file.managed
      Result: True
     Comment: File C:\salt\conf\minion.d\test.conf updated
     Started: 16:37:54.406000
    Duration: 203.0 ms
     Changes:   
              ----------
              diff:
                  New file
----------
          ID: salt-minion
    Function: service.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1594, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\service.py", line 535, in mod_watch
                  result = func(name)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 215, in restart
                  create_win_salt_restart_task()
                File "c:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 241, in create_win_salt_restart_task
                  start_time='01:00')
                File "c:\salt\bin\lib\site-packages\salt\modules\win_task.py", line 423, in create_task
                  if name in list_tasks(location) and not force:
                File "c:\salt\bin\lib\site-packages\salt\modules\win_task.py", line 288, in list_tasks
                  task_service = win32com.client.Dispatch("Schedule.Service")
                File "c:\salt\bin\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
                  dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
                File "c:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
                  return (_GetGoodDispatch(IDispatch, clsctx), userName)
                File "c:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
                  IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
              com_error: (-2147221005, '\xcd\xe5\xe4\xee\xef\xf3\xf1\xf2\xe8\xec\xe0\xff \xf1\xf2\xf0\xee\xea\xe0 \xf1 \xf3\xea\xe0\xe7\xe0\xed\xe8\xe5\xec \xea\xeb\xe0\xf1\xf1\xe0', None, None)
     Started: 16:37:55.046000
    Duration: 141.0 ms
     Changes:   

Summary for terminal
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
Total run time: 344.000 ms
ERROR: Minions returned with non-zero exit code
```
As service state  is not triggered, exception is not throwing.
```
salt 'terminal' state.sls minion 
terminal:
----------
          ID: C:\salt\conf\minion.d\test.conf
    Function: file.managed
      Result: True
     Comment: File C:\salt\conf\minion.d\test.conf is in the correct state
     Started: 16:41:56.546000
    Duration: 94.0 ms
     Changes:   
----------
          ID: salt-minion
    Function: service.running
      Result: True
     Comment: The service salt-minion is already running
     Started: 16:41:56.640000
    Duration: 360.0 ms
     Changes:   

Summary for terminal
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time: 454.000 ms
```

```
salt 'terminal' test.versions_report
terminal:
    Salt Version:
               Salt: 2015.8.3
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist:   
            machine: x86
            release: XP
             system: XP 5.1.2600 SP3 Multiprocessor Free
```
