### ISSUE TITLE
pillar referencing for boto profiles seems not completely working right / docu missing

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#29905]
Hello, 

since 2015.5.x and up to 2015.8.3 it is not working as expected (from me ^^) 

When I e.g. use as in documentation written (key is from documentation ;)):
````
myprofile:
    keyid: GKTADJGHEIQSXMKKRBJ08H
    key: askdjghsdfjkghWupUjasdflkdfklgjsdfjajkghs
    region: us-east-1
````
I can reference it as:
````
# Using a profile from pillars
Ensure mysecgroup exists:
    boto_secgroup.present:
        - name: mysecgroup
        - description: My security group
        - region: us-east-1
        - profile: myprofile
````

This is also possible if I put "aws." in front of it:
````
aws.myprofile:
    keyid: GKTADJGHEIQSXMKKRBJ08H
    key: askdjghsdfjkghWupUjasdflkdfklgjsdfjajkghs
    region: us-east-1
````
could be referenced as:
````
# Using a profile from pillars
Ensure mysecgroup exists:
    boto_secgroup.present:
        - name: mysecgroup
        - description: My security group
        - region: us-east-1
        - profile: aws.myprofile
    ....
````

But when I try to put all AWS stuff below pillar tree "aws" like:
````
aws:
  account: 123456789012
  wildcert: 'arn:aws:iam::123456789012:server-certificate/mycertificate'

  myprofile:
    keyid: GKTADJGHEIQSXMKKRBJ08H
    key: askdjghsdfjkghWupUjasdflkdfklgjsdfjajkghs
    region: us-east-1

  rds:
    myblog:
      ...
````
it fails to reference it as:
````
# Using a profile from pillars
Ensure mysecgroup exists:
    boto_secgroup.present:
        - name: mysecgroup
        - description: My security group
        - region: us-east-1
        - profile: aws:myprofile
````
wihle ````aws:myprofile```` should be the right referencing ?
Tests with ````aws.myprofile```` are also failling:
````
# Using a profile from pillars
Ensure mysecgroup exists:
    boto_secgroup.present:
        - name: mysecgroup
        - description: My security group
        - region: us-east-1
        - profile: aws.myprofile
````
