### ISSUE TITLE
Feature request: Requisite to fail the state if command returns 0

### ISSUE THREAD

**Issue by Xiol** [saltstack/salt#29922]
Hi,

I can't find an existing feature like this at present, but I'd like to see a new requisite, something like `failif` or `failwhen`, which when the command specified returns 0, the state fails. This can then be used with the `failhard` option to abort a run at a key point.

An example of where I need this is adding new users to the system. [Insert long story here], but the usernames can be specified by a third-party, and if a user already exists, we don't want to make any changes. So, we can use the `onlyif` or `unless` requisites, but those don't fail the state, so the execution continues. What I want to do instead is abort the run entirely and make no changes to the server. At the moment, I can't find a clean way of doing this (though I'll find a workaround I'm sure, probably using `cmd.run` and `failhard` first).

Thanks

**Comment by lorengordon** [comment]
Another workaround, you could use the `onlyif` or `unless` requisites to execute the test on the `test.fail_without_changes` state... Then chain the rest of the states to the test state with `require` (or `failhard`).

**Comment by Xiol** [comment]
I ended up working around it with:

```yaml
check_user_not_exists:
  cmd.run:
    - name: if [[ $(grep -c "{{ domain_user }}" /etc/passwd) == 1 ]]; then false; else true; fi;
    - failhard: true
    - order: 1
```

Pretty horrible IMO. Seems to do the trick though. (Must stress that input validation is done upstream!)
