### ISSUE TITLE
boto_rds.absent misses pillar variables for final backup

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#29933]
````
root@salt:~# salt-call --version
salt-call 2015.8.3 (Beryllium)
root@salt:~# pip install | grep boto
root@salt:~# pip list | grep boto
boto (2.38.0)
botocore (1.3.9)
````

state:
````
my-blog:
  boto_rds.absent:
    - name: my-blog
    - skip_final_snapshot: False
    - final_db_snapshot_identifier: my-blog-final-dump
    - region: eu-central-1
    - profile: aws.saltmaster-iam-profile-eu-central-1
````

local:
----------
          ID: my-blog
    Function: boto_rds.absent
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_rds.py", line 414, in absent
                  region, key, keyid, profile)
                File "/usr/lib/python2.7/dist-packages/salt/modules/boto_rds.py", line 490, in delete
                  raise SaltInvocationError('At least on of the following must'
              SaltInvocationError: At least on of the following must be specified: skip_final_snapshot final_db_snapshot_identifier
     Started: 14:42:54.723717
    Duration: 120.964 ms
     Changes:
