### ISSUE TITLE
boto_secgroup.present mapping failure

### ISSUE THREAD

**Issue by AkhterAli** [saltstack/salt#29938]
```shell
---
[...]
        - name: PRD_SG-NAT001
        - vpc_name: PROD
        - description: NAT security group
        - rules:
            - ip_protocol: tcp
                from_port: 80    <======================
                to_port: 80
                cidr_ip:
                    - 10.25.33.0/0
                    - 10.25.34.0/0
                    - 10.25.35.0/0
[...]
---
```

```yaml
PRD_SG-NAT001:
    boto_secgroup.present:
        - name: PRD_SG-NAT001
        - vpc_name: PROD
        - description: NAT security group
        - rules:
            - ip_protocol: tcp
                from_port: 80
                to_port: 80
                cidr_ip:
                    - 10.25.33.0/0
                    - 10.25.34.0/0
                    - 10.25.35.0/0
                    - 10.25.36.0/0
        - keyid: {{ salt['pillar.get']('PROD:key',  None) }}
        - key: {{ salt['pillar.get']('PROD:key',  None) }}
        - region: us-east-1
```

**Comment by cachedout** [comment]
Hi @AkhterAli Please forgive me, but I'm not sure I follow what the problem here is. Could you please provide more information about what the issue is here? Thanks.

**Comment by AkhterAli** [comment]
@cachedout Sorry, maybe this will provide more info.

When I ran my saltstate (stated above), this is the error I get.
```shell
failed: mapping values are not allowed here; line 101

---
[...]
        - name: PRD_SG-NAT001
        - vpc_name: PROD
        - description: NAT security group
        - rules:
            - ip_protocol: tcp
                from_port: 80    <======================
                to_port: 80
                cidr_ip:
                    - 10.25.33.0/0
                    - 10.25.34.0/0
                    - 10.25.35.0/0
[...]
```

It doesn't seem to accept from_port at all, although not sure why.

**Comment by Reiner030** [comment]
Hi,

it works normally fine.
I guess you have the problem here that all parameters must be in one row like:

````
        - name: PRD_SG-NAT001
        - vpc_name: PROD
        - description: NAT security group
        - rules:
            - ip_protocol: tcp
              from_port: 80
              to_port: 80
              cidr_ip:
                - 10.25.33.0/0
                - 10.25.34.0/0
                - 10.25.35.0/0
````
?
