### ISSUE TITLE
[salt-cloud][ec2] associate_eip not usable with instances than have multiple security groups

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#29931]
Just like it was mentioned here https://github.com/saltstack/salt/issues/25569 , security groups cannot be specified along with network interfaces so essentially doesn't seem to be a good way of associating elastic IPs to instances which have more than just the default security group.

The profile I tried with looks like this:

```
b-debian-t2.micro-ec2-eu-west-1:
  provider: b-default-ec2
  location: eu-west-1
  image: ami-e31a6594
  size: t2.micro
  ssh_username: admin
  securitygroup:
    - default
    - cloudhero
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      allocate_new_eips: True
      SubnetId: subnet-f891e1a1
```

and the error message I receive is:

```
{'Error': {'Message': 'Network interfaces and an instance-level security groups may not be specified on the same request', 'Code': 'InvalidParameterCombination'}}
```
