### ISSUE TITLE
host.present not adding hostname or fqnd

### ISSUE THREAD

**Issue by bxm156** [saltstack/salt#29959]
I'm new to salt, so I apologize if this is just a mis-understanding. I'm trying to get my minion's id and fqnd in the /etc/hosts file, but salt thinks nothing needs to be done.

I have the following:
a minion on Ubuntu 14.04
/etc/hostname: minion1.example.com
/etc/hosts:

```
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

and the following state:

```
{%- set fqdn = grains['fqdn'] %}
{%- set host = grains['id'] %}
{%- set localip = grains['fqdn_ip4'] %}

{{ fqdn }}-hosts-entry:
  host.present:
    - ip: {{ localip }}
    - names:
      - {{ host }}
      - {{ fqdn }}
```

which results in:

```
minion1.example.com-hosts-entry:
  host.present:
    - ip: 127.0.0.1
    - names:
      - minion1
      - minion1.example.com
```

and I would expect those to get added to the /etc/hosts, but the host file doesn't change. Salt stack seems to think nothing is needed to be done...

```
----------
          ID: minion1.example.com-hosts-entry
    Function: host.present
        Name: minion1.example.com
      Result: None
     Comment:
     Started: 20:17:43.617612
    Duration: 0.795 ms
     Changes:
----------
```

Look at the salt-call on the minion, i see:

```
[INFO    ] Running state [minion1.example.com] at time 20:18:32.486865
[INFO    ] Executing state host.present for minion1.example.com
[INFO    ] No changes made for minion1.example.com
[INFO    ] Completed state [minion1.example.com] at time 20:18:32.487676
```

what I would expect would be a file like:

```
127.0.0.1 localhost minion1 minion1.example.com

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

Note the line above is: **127.0.0.1 localhost minion1 minion1.example.com**

Without those items in the /etc/hosts file, things such as 
- ping minion1
- ping minion1.example.com
  fail to resolve

**Comment by ssgward** [comment]
@bxm156 - thanks for logging this. 

Try just adding one hostname entry for the IP and see if that works for the one host entry. I know you're trying to add multiple. Seems like there is a known issue when trying to add multiple host entries for the same IP (but could be wrong).

**Comment by bxm156** [comment]
I have the same problem, even when specifying only 1 name

**Comment by bxm156** [comment]
This is weird, but I try the following:

```
minion1.example.com-hosts-entry:
  host.present:
    - ip: 10.0.1.123
    - names:
      - minion1
      - minion1.example.com
```

I get:
```
127.0.0.1               localhost
# The following lines are desirable for IPv6 capable hosts
::1             ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
ff02::3         ip6-allhosts
10.0.1.123              minion1.amp.dj
```
(Note the **10.0.1.123              minion1.amp.dj** )

So it seems the ip being not 127.0.0.1 seems to have some effect. But I only get 1 of the names then :/
