### ISSUE TITLE
network.managed type bond does not generate the primary option

### ISSUE THREAD

**Issue by javicacheiro** [saltstack/salt#29971]
It seems the primary option of the network.managed type=bond is not generating the necessary primary option in the BONDING_OPTS variable. I am using a minion with RHEL7 and salt 2015.8.3.

This is the bond definition in the sls file:

```
bond0:
  network.managed:
    - type: bond
    - slaves: ens3f0 eno1 eno2
    - mode: active-backup
    - primary: ens3f0
    - ipaddr: 10.119.13.8
    - netmask: 255.255.0.0
    - require:
      - network: ens3f0
      - network: eno1
      - network: eno2
    - miimon: 100
    - mtu: 9000
```

And these are the BONDING_OPTS generated in /etc/sysconfig/network-scripts/ifcg-bond0:

```
BONDING_OPTS="downdelay=200 miimon=100 use_carrier=on mode=1 updelay=0 "
```

The expected BONDING_OPTS would be:

```
BONDING_OPTS="mode=1 miimon=100 primary=ens3f0"
```

The options downdelay and use_carrier are not requested in the sls but probably are just inserted by default by the module.
