### ISSUE TITLE
moun.mounted state fails to mount too early

### ISSUE THREAD

**Issue by non7top** [saltstack/salt#29972]
This state strangely fails on unmount if nothing is mounted and then stops immediately, without even trying to mount. '/backup does not have anything mounted' should not result in error.

```
server:
----------
          ID: /backup
    Function: mount.mounted
      Result: False
     Comment: Unable to unmount /backup: /backup does not have anything mounted.
     Started: 07:52:15.675763
    Duration: 18072.707 ms
     Changes:
              ----------
              umount:
                  Forced unmount and mount because options (wsize=1048576) changed
```
