### ISSUE TITLE
network.managed changes bridge names to lowercase

### ISSUE THREAD

**Issue by javicacheiro** [saltstack/salt#29973]
When creating a bridge the network.managed state automatically converts the name to lowercase.

 I am using a minion with RHEL7 and salt 2015.8.3.
- sls state:

```
virbrSTORAGE:
  network.managed:
    - bridge: virbrSTORAGE
    - enabled: True
    - type: bridge
    - proto: none
    - ipaddr: 10.117.1.8
    - netmask: 255.255.0.0
    - mtu: 9000
    - delay: 0
    - ports: bond0.117
    - bypassfirewall: True
    - use:
      - network: bond0.117
    - require:
      - network: bond0.117

```
- Generates /etc/sysconfig/network-scripts/ifcfg-virbrstorage with DEVICE name set to virbrstorage:

```
DEVICE="virbrstorage"
...
```

I think the case sensitivity should be maintained at least in the definition of the bridge names, or in other case allow for a switch to turn off the automatic conversion (eg. lowercase: False)
