### ISSUE TITLE
cannot configure  -m recent --name  with iptables.insert

### ISSUE THREAD

**Issue by schaarsc** [saltstack/salt#30013]
a state definition such as 

```
my_rule:
  iptables.insert:
    - chain: INPUT
    - match: recent
    - name: recent_name
```

should create a statement similar to 
`iptables -I Input -m recent --name recent_name`
but name is ignored and I think this is due to 
https://github.com/saltstack/salt/blob/aab929d196f267ff0f4723b8d0918826cfa04d18/salt/modules/iptables.py#L165
or
https://github.com/saltstack/salt/blob/aab929d196f267ff0f4723b8d0918826cfa04d18/salt/states/iptables.py#L500

I suggest to introduce a new keyword 'rname' to workaround the name collision and replace lines 220-221
https://github.com/saltstack/salt/blob/aab929d196f267ff0f4723b8d0918826cfa04d18/salt/modules/iptables.py#L220
with

```
if 'rname' in kwargs and match.strip() in ('pknock', 'quota2', 'recent'):
  rule.append('--name {0}'.format(kwargs['rname']))
  del kwargs['rname']
```

**Comment by cachedout** [comment]
Thanks for the suggestion. I'm curious what @thusoy has to say about this one.

**Comment by thusoy** [comment]
I believe the suggested solution of introducing a new keyword for this is the best option, which is how we've handled similar cases previously, like `connstate` aliasing `state`. However, what the best alias is I don't know. Why `rname`?

There's also a similar  unhandled collision for the `--save` argument to the connsecmark module, which also needs an alias.

**Comment by schaarsc** [comment]
'rname' because I was looking at -m recent.
Problem here is that depending on the module name has different meaning: list, counter, etc.

Maybe some kind of escape character can be introduced for such cases?
Something like _state, _name, _save?

**Comment by thusoy** [comment]
Yes, I think a generic escape character would be best. I'm not sure about the underscore prefix though, since it's already established in python as «internal». Could double dash work? Or underscore as postfix? 

Den 29. desember 2015 12.26.21 CET, skrev schaarsc <notifications@github.com>:

**Comment by schaarsc** [comment]
sls files are configuration files, I'd not use dash-dash, since this is more common for cmd line.

from an end user perspective I think it is more common to have the escape char at the beginning.
looking at an example
```
my_rule:
  iptables.insert:
    - chain: INPUT
    - match: recent
    - name_: recent_name
```
```
my_rule:
  iptables.insert:
    - chain: INPUT
    - match: recent
    - _name: recent_name
```
having the underscore as postfix is "easier" to read
