### ISSUE TITLE
Is local.file.managed possible?

### ISSUE THREAD

**Issue by mmisztal1980** [saltstack/salt#30028]
Hi there,

I've searched both stackoverflow and github issues but I haven't found an answer, so here goes :

Obviously I'm new to salt, I'm attempting to write a reactor .sls file to handle a 'servicedeployment' event. 

In order to execute my scenario successfully, I need to have the target minions execute a file.managed state. (selected minions running some middleware need to download files from the salt-master).

Would something like this be possible?

handle_event.sls
```
/path_to_config_files/config_file.cfg:
    local.file.managed:
        - tgt : ['minion1', 'minion2', 'minion3']
        - file.managed:
            - source: salt://configFiles/configFile.cfg
            (...)
```

If this is not possible (I hope the intent is clear) - then what would be the preferred way to achieve this?

**Comment by cachedout** [comment]
Hi @mmisztal1980 

The general idea is right, but there is one important adjustment.

If you need to execute states on the _minions_ from a reactor SLS, you need to use something like `state.single` and pass in `file.managed` as an argument to it.

**Comment by mmisztal1980** [comment]
Hi @cachedout, thanks for the response, I'll give it a shot tomorrow

**Comment by mmisztal1980** [comment]
@cachedout I've examined the documentation found here, but I haven't been able to find any reference on how to handle this the way you've described :( 

Could you provide me with a short sample please?

**Comment by whiteinge** [comment]
The syntax for `state.single` is not obvious for new Salt users -- or even for not-new salt users. It's confusing to think about since you're creating a data structure that will be used to call a function on the master that ships a subset of that data structure over the wire to a minion that will be used to call a function that kicks off Salt's state system which uses a subset of that data structure to finally invoke `file.managed`. :dizzy_face:

All that said, you're very close. You must use `kwarg` singular because the Reactor is calling [this method](https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd) on the master which will send the execution down to the minion. After that it's a pretty straightforward mapping of keys in `kwarg` to [the raw function signature for state.single](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.single).

Something like this should work (untested). Also note the `expr_form` argument.

```yaml
# The ID for the reactor is better used as documetation
# since it isn't sent to the minion directly.
run_file_managed_on_minions_because_reasons:
  # The command you want the reactor to run. In this case you want
  # to send a command down to minions. This is a direct equivalent
  # to using Salt's CLI to send a command down to minions.
  local.state.single:
    # Must explicitly state you're matching on multiple minions
    # by changing from the default target type of 'glob' to 'list'.
    - tgt: ['minion1', 'minion2', 'minion3']
    - expr_form: list

    # Specify any keyword arguments the minion should use when it executes
    # `state.single`. You can also use `arg` to pass a list of positional args but
    # kwargs are easier to read here and map one-to-one to the function
    # signature in the docs.
    - kwarg:
        fun: file.managed
        name: /path_to_config_files/config_file.cfg
        source: salt://configFiles/configFile.cfg
```
