### ISSUE TITLE
[BUG] listen does not appear to respect the special names directive

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#30115]
### Versions report

I am running from a recent commit on the 2015.8 branch

```
[root@salt ~]# salt --versions-report
Salt Version:
           Salt: 2015.8.3-481-g3652dba

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.11.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```
### Highstate with changes

This is the state, and there should be a bunch of services that get restarted, but only this one is restarted by mod_watch (listen/watch) and onchanges.

This example only shows listen/mod_watch being used.

```
[root@salt ~]# salt novaapi.manfred.io state.highstate
novaapi.manfred.io:
----------
          ID: nova config file
    Function: file.managed
        Name: /etc/nova/nova.conf
      Result: True
     Comment: File /etc/nova/nova.conf updated
     Started: 05:00:40.478104
    Duration: 133.714 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,3 +1,7 @@
                  +
                  +
                  +
                  +
                   [DEFAULT]
                   my_ip = 10.208.164.36
                   rpc_backend = rabbit
----------
          ID: listener_start nova
    Function: service.mod_watch
        Name: openstack-nova-consoleauth.service
      Result: True
     Comment: Service restarted
     Started: 05:00:45.021610
    Duration: 27573.575 ms
     Changes:
              ----------
              openstack-nova-consoleauth.service:
                  True

Summary for novaapi.manfred.io
-------------
Succeeded: 57 (changed=2)
Failed:     0
-------------
Total states run:     57
```
### The state with names

https://github.com/gtmanfred/openstack-salt-states/blob/master/salt/novaapi/service.sls

```

include:
  - .config

start nova:
  service.running:
    - names:
      - openstack-nova-api.service
      - openstack-nova-cert.service
      - openstack-nova-consoleauth.service
      - openstack-nova-scheduler.service
      - openstack-nova-conductor.service
      - openstack-nova-novncproxy.service
    - enable: True
    - listen:
      - file: /etc/nova/nova.conf
```

It only appears to restart one of them at random.

Thanks
Daniel
