### ISSUE TITLE
salt.cloud.CloudClient method create() not working for VMware driver

### ISSUE THREAD

**Issue by anandnevase** [saltstack/salt#30147]
I am trying to run simple python code to Provision VM using salt.cloud.CloudClient create() API (Create the named VMs, without using a profile) using vmware driver, but unable to execute.

Salt-Cloud Version : salt-cloud 2015.8.3 (Beryllium)
Base OS : Centos 6

Sample Code:
```py
import os, json, yaml, collections
from salt.cloud import CloudClient
from salt.exceptions import SaltCloudSystemExit


if __name__ == '__main__':
        client = CloudClient(path='/etc/salt/cloud')
        spec_str='{"provider":"vcenter01","clonefrom":"Win2008R2","num_cpus":4,"memory":"6GB","datastore":"Test-cntr0","cluster":"Test-Cluster","folder":"Test VMs","names":["test_vm_2008"],"devices":{"disk":{"Hard disk 2":{"size":15},"Hard disk 3":{"size":12}},"scsi":{"SCSI controller 1":{"type":"lsilogic"},"SCSI controller 2":{"type":"lsilogic_sas","bus_sharing":"virtual"},"SCSI controller 3":{"type":"paravirtual"}}}}'
        spec=json.loads(spec_str)
        vm_names = spec.get("names")
        ret = client.create(provider='vcenter01', names=vm_names, kwargs=spec)
        print "vm-status: ", ret
```

Here, I am getting empty json without any exception.

**Comment by jfindlay** [comment]
@anandxoriant, thanks for the report.  Can you post your relevant cloud provider and profile configs with the private info removed?  Can you verify that other operations with the provider work as expected using `salt-cloud`?

**Comment by anandxoriant** [comment]
@jfindlay, following are my cloud.provider & profile configs:

/etc/salt/cloud.providers
```
vcenter01:
  driver: vmware
  user: '<vcenter-user>'
  password: '<vcenter-pwd>'
  url: '<vcenter-ip>'
  protocol: 'https'
  port: 443
  esxi_host_user: '<esxi-user>'
  esxi_host_password: '<esxi-pwd>'
  esxi_host_ssl_thumbprint: <ssl-thumbprint>
  minion:
    master: <master-ip>
  win_installer: /root/Salt-Minion-2015.8.3-AMD64-Setup.exe
  win_username: <win-admin-user>
  win_password: <win-admin-password>
  smb_port: 445
```

/etc/salt/cloud.profiles:
```
vm_prof:
  provider: vcenter01
  clonefrom: Win2008R2
  num_cpus: 4
  memory: 8GB
  datastore: Test-cntr0
  cluster: Test-Cluster
  folder: Test-VMs
  domain: test.com
  devices:
    disk:
      Hard disk 1:
        size: 5
      Hard disk 2:
        size: 2
    scsi:
      SCSI controller 1:
        type: lsilogic
      SCSI controller 2:
        type: lsilogic_sas
        bus_sharing: virtual
      SCSI controller 3:
        type: paravirtual
```

I can able to provision vm using salt-cloud cli command as well as salt.cloud.CloudClient profile() api. But not able to create from salt.cloud.CloudClient create() method
