### ISSUE TITLE
file.line reset permissions to 600

### ISSUE THREAD

**Issue by rapenne-s** [saltstack/salt#30150]
Hi,

file.line resets perms to 600 when used. If the line is already there the file is not modified and the permission is not changed.

I am using file.line to add a line to existing file with the following

```
/etc/mail/aliases:
  file.line:
    - content: "root: tech.support@mycompany.com"
    - match: "tech.support"
    - mode: ensure
    - after: "my.domain"
```

The file before applying the state

```
-rw-r--r--  1 root  wheel    1729  5 jan 11:12 aliases
```

The file after applying the state

```
-rw-------  1 root  wheel    1729  5 jan 14:19 aliases
```

I reproduced this issue with 2015.8.1 and 2015.8.3 on FreeBSD 10.2-RELEASE amd64
