### ISSUE TITLE
archive.extracted doesn't accept source; 

### ISSUE THREAD

**Issue by deniswal** [saltstack/salt#30151]
archive.extracted doesn't accept source: attribute as a list.
The try I made was using :
```
source:
  - http://...
  - salt://...
```
The http:// entry is valid and never taken.

```
source: http://...
```
with the same http entry works.
As described by its documentation, source: should behave the same way as in file.managed.

**Comment by jfindlay** [comment]
@deniswal, thanks for the report.  What version of salt are you using?

**Comment by deniswal** [comment]
I am using salt 2015.5.0 (Lithium) on this server.

**Comment by jfindlay** [comment]
@deniswal, thanks.  Here is my test case:
```yaml
jmoney-main salt (v2015.8.3) # cat /srv/salt/source.sls
list:
  archive.extracted:
    - name: /tmp/linux
    - source:
      - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.3.3.tar.xz
    - archive_format: tar
jmoney-main salt (v2015.8.3) # salt jmoney-main state.apply source
jmoney-main:
----------
          ID: list
    Function: archive.extracted
        Name: /tmp/linux
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 12:37:20.401521
    Duration: 112.976 ms
     Changes:

Summary for jmoney-main
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 112.976 ms
jmoney-main salt (v2015.8.3) # salt jmoney-main test.versions
jmoney-main:
    Salt Version:
               Salt: 2015.8.3

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed

    System Versions:
               dist: debian 8.2
            machine: x86_64
            release: 3.16.0-4-amd64
             system: debian 8.2
```
