### ISSUE TITLE
Can't use Subnet/IP Address Matching

### ISSUE THREAD

**Issue by techcook** [saltstack/salt#30169]
version: 2015.8
Descriptions: salt can't use Subnet/IP address matching.
![qq 20160106121830](https://cloud.githubusercontent.com/assets/10361796/12134941/bab8e4a6-b46f-11e5-838d-8e68f215a69e.png)

**Comment by techcook** [comment]
add pic

**Comment by ssgward** [comment]
@techcook - did you try ``S@10.10.10.100`` to see if that was successful, as opposed to ``-S...``?

**Comment by techcook** [comment]
@ssgward  yes, I have try do it . but have same  problem:

**Comment by ssgward** [comment]
OK. Sounds like a bug.

**Comment by whytewolf** [comment]
+1 also having this bug. and finding that it goes a little deeper than just the ip not matching. even some subnets that should match are not. 

for an ip of 10.40.0.2 I can test upto 10.40.0.0/25 

but a submask of /26 or higher does not match. even though that ip should be within range till at least /30 also a subnet mask of /32 for an ip never matches. even though it is technically a valid subnet mask for a single ip.

```
salt --versions
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.4
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-41-generic
         system: Ubuntu 14.04 trusty
```

also this is affecting mine.get

```
salt 'ctrl*' mine.get 'I@roles:ntp-server and not S@10.40.0.3' mgmt_network compound
ctrl01.wolfcloud.bad4.us:
    ----------
    ctrl01.wolfcloud.bad4.us:
        - 10.40.0.2
    ctrl02.wolfcloud.bad4.us:
        - 10.40.0.3
    ctrl03.wolfcloud.bad4.us:
        - 10.40.0.4
ctrl03.wolfcloud.bad4.us:
    ----------
    ctrl01.wolfcloud.bad4.us:
        - 10.40.0.2
    ctrl02.wolfcloud.bad4.us:
        - 10.40.0.3
    ctrl03.wolfcloud.bad4.us:
        - 10.40.0.4
ctrl02.wolfcloud.bad4.us:
    ----------
    ctrl01.wolfcloud.bad4.us:
        - 10.40.0.2
    ctrl02.wolfcloud.bad4.us:
        - 10.40.0.3
    ctrl03.wolfcloud.bad4.us:
        - 10.40.0.4
```

however modules.match.ipcidr does not seem to be affected.
