### ISSUE TITLE
salt-ssh hardcodes SSH port 22 as default

### ISSUE THREAD

**Issue by bebehei** [saltstack/salt#30173]
I'm running my ssh server on my systems on a Port != 22.

So while I configure the system correct in `~/.ssh/config`, I can ssh just by `ssh <host>`.

So the ideal case would be, that I use the salt-roster only for translating the Salt ID to the ssh hostname:

```
saltmaster:
  host: some.host.company.com
```

But the saltroster sets a default of Port 22 if None is given. Therefore I have to give always the port number, too:

```
saltmaster:
  host: some.host.company.com
  port: 6152
```

This leads to doubled information.
Also: The port 22 is default by SSH. Why do we have to set the default Port of salt-ssh to 22, if SSH has it already set?

**Comment by bebehei** [comment]
I believe the fix would be just to change [salt/config/schemas/ssh.py Line 45](https://github.com/saltstack/salt/blob/fcef605a4ac775f8fed64db6333f7c4483ecb3b7/salt/config/schemas/ssh.py#L45) as other parts [just check before using the port if it is available](https://github.com/saltstack/salt/blob/2bc5e01fee9bffee668a1b1e1a9ecf6e1cae0ac4/salt/client/ssh/shell.py#L153).

**Comment by jfindlay** [comment]
@bebehei, thanks for the report.  What version of salt are you using?

**Comment by bebehei** [comment]
```
salt-ssh --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.11 (default, Dec  6 2015, 15:43:46)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: 1.4.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.3.3-2-ARCH
 ```
