### ISSUE TITLE
Setting tz breaks total run time

### ISSUE THREAD

**Issue by frioux** [saltstack/salt#30188]
We set our timezone to Los Angeles time:

(pillar)

```
timezone:
  timezone.system:
    - name: {{ pillar.get('timezone').get('name','Etc/UTC') }}
    - utc:  {{ pillar.get('timezone').get('utc',True)       }}
```

(state)

```
timezone:
  name: America/Los_Angeles
  utc:  False
```

And it seems to take forever!

```
----------
          ID: timezone
    Function: timezone.system
        Name: America/Los_Angeles
      Result: True
     Comment: Set timezone America/Los_Angeles
     Started: 21:37:52.849385
    Duration: 57600001.379 ms
     Changes:   
              ----------
              timezone:
                  America/Los_Angeles

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 57600.001 s

```

But of course it actually takes 2.4s wallclock.  Worst case you should use UTC
for time calculations, but if ntp were to be run that could be confused too.
I'd recommend using monotonic time (http://linux.die.net/man/3/clock_gettime)

Not sure if that exists on windows or other platforms though.
