### ISSUE TITLE
Setting root passwd via user.present gives invalid results

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#30208]
Using a simple state such as:
```sls
root:
  user.present:
    - password: '$6$xcRjzm3.MXHaqzUd$t0sOmNQLuzg0GfLfDE3Sb7XL9vNhdzSFq8L.OtzaIVlcazJUj4D7B3MrDBwqG6aUMbX0SLbYLjYlxEojX2S.K0'
```
Will give the following results:
```yaml
local:
----------
          ID: root
    Function: user.present
      Result: False
     Comment: These values could not be changed: {'passwd': '$6$xcRjzm3.MXHaqzUd$t0sOmNQLuzg0GfLfDE3Sb7XL9vNhdzSFq8L.OtzaIVlcazJUj4D7B3MrDBwqG6aUMbX0SLbYLjYlxEojX2S.K0'}
     Started: 11:16:23.509460
    Duration: 2.775 ms
     Changes:
```
However, checking /etc/shadow, the password was changed.  Subsequent runs keeps throwing the same results even though the password didn't need to change, nor did.  Seems to be a false positive.

Tested on 2015.8.1 and 2015.8.3
