### ISSUE TITLE
For wrong vCenter details, salt-cloud create command get blocked

### ISSUE THREAD

**Issue by anandnevase** [saltstack/salt#30260]
I am trying to run salt-cloud create VM command with wrong VMware vCenter details, salt-cloud sub-process get blocked. 

Following are configuration and command I am running:

/etc/salt/cloud.providers

```
vcenter01:
  driver: vmware
  user: '<vcenter-user>'
  password: '<vcenter-pwd>'
  url: '<wrong-vcenter-ip>'
  protocol: 'https'
  port: 443
  esxi_host_user: '<esxi-user>'
  esxi_host_password: '<esxi-pwd>'
  esxi_host_ssl_thumbprint: <ssl-thumbprint>
  minion:
    master: <master-ip>
  win_installer: /root/Salt-Minion-2015.8.3-AMD64-Setup.exe
  win_username: <win-admin-user>
  win_password: <win-admin-password>
  smb_port: 445
```

/etc/salt/cloud.profiles:

```
vm_prof:
  provider: vcenter01
  clonefrom: Win2008R2
  num_cpus: 4
  memory: 8GB
  datastore: Test-cntr0
  cluster: Test-Cluster
  folder: Test-VMs
  domain: test.com
  devices:
    disk:
      Hard disk 1:
        size: 5
      Hard disk 2:
        size: 2
    scsi:
      SCSI controller 1:
        type: lsilogic
      SCSI controller 2:
        type: lsilogic_sas
        bus_sharing: virtual
      SCSI controller 3:
        type: paravirtual
```

Command: `salt-cloud -p vm_prof test-vm`
