### ISSUE TITLE
TCP Transport fails with multiprocessing on in Windows (develop)

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#30313]
### Master:
```
Salt Version:
           Salt: 2015.8.0-1220-g0b834ec

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: 0.9.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: 0.8.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.13
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-43-generic
         system: Ubuntu 14.04 trusty
```

### Minion
```
Salt Version:
           Salt: 2015.8.0-1220-g0b834ec

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86
        release: 2008Server
         system: 2008Server 6.0.6002 SP2 Multiprocessor Free
```

### Error
Working off the Head of Develop.
With `multiprocessing: True` the minion starts up and seems to connect (no errors). Then I issue a `test.ping` from the master and I get the following stacktrace:
```
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20160112183011253642', '
tgt': '*', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'test.ping'}
Process SignalHandlingMultiprocessingProcess-1:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "c:\salt-dev\salt\salt\minion.py", line 1087, in _target
    with tornado.stack_context.StackContext(minion_instance.ctx):
AttributeError: 'NoneType' object has no attribute 'ctx'
[DEBUG   ] Process manager iteration
```
