### ISSUE TITLE
OEL - State 'service.running' was not found in SLS

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#30386]
hello

this happens only on OEL 6.x

```
          ID: vmware-tools-services
    Function: service.running
      Result: False
     Comment: State 'service.running' was not found in SLS 'vmware-tools'
              Reason: 'service' __virtual__ returned False
     Started:
    Duration:
     Changes:
```

the sls file:

```
vmware-tools-esx-nox:
  pkg:
    - latest

vmware-tools-services:
  service:
    - running
    - enable: true
    - watch:
      - file: /etc/vmware-tools/tools.conf

/etc/vmware-tools/tools.conf:
  file.managed:
    - source:
      - salt://vmware-tools/tools.conf.{{ grains['fqdn'] }}
      - salt://vmware-tools/tools.conf.default
    - user: root
    - group: root
    - mode: 644
```
