### ISSUE TITLE
git pillars not found with multiple repos - pygit2 

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#30407]
With the configuration below all of my pillar repos are successfully cached in /var/cache/salt/, but **_only the last repo in the list actually renders with minions**_.

```
ext_pillar:
  - git:
    - staging git@github.com:ps-ops/saltstack-pillars.git:
      - privkey: /root/.ssh/github-saltstack-pillars-id_rsa
      - pubkey: /root/.ssh/github-saltstack-pillars-id_rsa.pub
      - env: base
    - master git@github.com:ps-ops/saltstack-primedirective.git:
      - privkey: /root/.ssh/ps-ops_saltstack-primedirective-id_rsa
      - pubkey: /root/.ssh/ps-ops_saltstack-primedirective-id_rsa.pub
      - env: base
      - root: pillars
    - master git@github.com:ps-ops/saltstack-paths.git:
      - privkey: /root/.ssh/ps-ops_saltstack-paths-id_rsa
      - pubkey: /root/.ssh/ps-ops_saltstack-paths-id_rsa.pub
      - env: base
      - root: pillars
```

I fixed this by doing this:

```
ext_pillar:
  - git:
    - staging git@github.com:ps-ops/saltstack-pillars.git:
      - privkey: /root/.ssh/github-saltstack-pillars-id_rsa
      - pubkey: /root/.ssh/github-saltstack-pillars-id_rsa.pub
      - env: base
  - git:
    - master git@github.com:ps-ops/saltstack-primedirective.git:
      - privkey: /root/.ssh/ps-ops_saltstack-primedirective-id_rsa
      - pubkey: /root/.ssh/ps-ops_saltstack-primedirective-id_rsa.pub
      - env: base
      - root: pillars
  - git:
    - master git@github.com:ps-ops/saltstack-paths.git:
      - privkey: /root/.ssh/ps-ops_saltstack-paths-id_rsa
      - pubkey: /root/.ssh/ps-ops_saltstack-paths-id_rsa.pub
      - env: base
      - root: pillars
```

weird.
