### ISSUE TITLE
git_pillar mapping problem with multiple branches on single repo

### ISSUE THREAD

**Issue by anonymousobject** [saltstack/salt#30402]
I've got a single Git repo that has two branches for pillar data, one for master and one named staging. I've attempted to configure the Salt master to use master for base env and staging for staging env but staging env minions always get base pillar data. On version 2015.8.3

```
ext_pillar:
  - git:
    - master git@gitlab.com:user123/repo_abc.git:
      - root: pillar
      - env: base
      - pubkey: /root/salt-key.pub
      - privkey: /root/salt-key
    - staging git@gitlab.com:user123/repo_abc.git:
      - root: pillar
      - env: staging
      - pubkey: /root/salt-key.pub
      - privkey: /root/salt-key

```

However when I try to start the master with this config, I get:

```
2016-01-15 20:12:49,799 [salt.utils.gitfs                                    ][CRITICAL][24088] The following git_pillar remotes have conflicting cachedirs: master git@gitlab.com:user123/repo_abc.git, staging git@gitlab.com:user123/repo_abc.git. Resolve this using a per-remote parameter called 'name'.
```

So I update config to:

```
ext_pillar:
  - git:
    - master git@gitlab.com:user123/repo_abc.git:
      - name: base
      - root: pillar
      - env: base
      - pubkey: /root/salt-key.pub
      - privkey: /root/salt-key
    - staging git@gitlab.com:user123/repo_abc.git:
      - name: staging
      - root: pillar
      - env: staging
      - pubkey: /root/salt-key.pub
      - privkey: /root/salt-key
```

Log then shows this:

```
2016-01-15 20:19:16,466 [salt.utils.gitfs                                    ][ERROR   ][27358] Failed to checkout staging from git_pillar remote 'staging git@gitlab.com:user123/repo_abc.git': remote ref does not exist
2016-01-15 20:19:16,575 [salt.utils.gitfs                                    ][ERROR   ][27376] Failed to checkout master from git_pillar remote 'master git@gitlab.com:user123/repo_abc.git': remote ref does not exist
2016-01-15 20:19:16,575 [salt.utils.gitfs                                    ][ERROR   ][27376] Failed to checkout staging from git_pillar remote 'staging git@gitlab.com:user123/repo_abc.git': remote ref does not exist
2016-01-15 20:19:24,511 [salt.utils.gitfs                                    ][ERROR   ][27377] Failed to checkout staging from git_pillar remote 'staging git@gitlab.com:user123/repo_abc.git': remote ref does not exist
2016-01-15 20:19:24,731 [salt.utils.gitfs                                    ][ERROR   ][27358] Failed to checkout staging from git_pillar remote 'staging git@gitlab.com:user123/repo_abc.git': remote ref does not exist
2016-01-15 20:19:25,514 [salt.utils.gitfs                                    ][WARNING ][27254] Update lockfile is present for gitfs remote 'git@gitlab.com:user123/repo_abc.git', skipping. If this warning persists, it is possible that the update process was interrupted. Removing /var/cache/salt/master/gitfs/9a2ac6b7fa8e034a96c16b69afad2bbb/update.lk or running 'salt-run cache.clear_git_lock gitfs' will allow updates to continue for this remote.
2016-01-15 20:20:34,257 [salt.utils.gitfs                                    ][WARNING ][28349] Update lockfile is present for gitfs remote 'git@gitlab.com:user123/repo_abc.git', skipping. If this warning persists, it is possible that the update process was interrupted. Removing /var/cache/salt/master/gitfs/9a2ac6b7fa8e034a96c16b69afad2bbb/update.lk or running 'salt-run cache.clear_git_lock gitfs' will allow updates to continue for this remote.
```

Despite the errors, I see both branches checked correctly out in /var/cache/salt/master/git_pillar/. 
Even Remote_map.txt looks good to me:

```
# git_pillar_remote map as of 15 Jan 2016 20:19:10.986449
base = master git@gitlab.com:user123/repo_abc.git
staging = staging git@gitlab.com:user123/repo_abc.git
```

On my minion, I check pillar data:

`salt-call pillar.items saltenv=staging`

But I always get base pillar data.

Been struggling with this all afternoon... I've gone over the git_pillar documentation and I think my config is correct. Am I missing something here or is this a bug?

**Comment by heini** [comment]
It's a pity that this is still not working properly. I have a simple test setup with two repos, one for the top.sls files only, the other one for states and pillar data. both repos have their files in located in root directories states and pillar. The (pillar|states)/top.sls files in the first repo look like:
```
base:
  '(minion1|minion2).example.de':
    - match: pcre
    - test

development:
  'minion3.example.de':
    - test
```
in the other repo, on branch master, states/test/init.sls looks like:
```
{% set content = salt['pillar.get']('test_content') %}

test_file:
  file.managed:
    - name: /tmp/testfile
    - contents: {{ content }}
```
and pillar/test/init.sls is:
```
test_content: foo
```
From this, I checked out a new branch development and modified pillar/test/init.sls only:
```
test_content: bar
```
Now, running `salt '*' state.highstate` works fine for minion1 and minion2, but for minion3 I get:
```
# salt 'minion3.example.de' state.highstate    
minion3.example.de:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Started: 
    Duration: 
     Changes:   

Summary for minion3.example.de
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
```
When enabling debug logging, the log show this:
```
[salt.pillar      ][DEBUG   ][11339] Specified SLS 'test' in environment 'development' is not found, which might be due to environment 'development' not being present in "pillar_roots" yet!
```
Relevant config options:
```
fileserver_backend:
  - git

gitfs_provider: gitpython
gitfs_root: states

gitfs_remotes:
  - git-salt:salt_top.git
  - git-salt:salt.git

top_file_merging_strategy: same

git_pillar_provider: gitpython
git_pillar_root: pillar

ext_pillar:
  - git:
    - git-salt:salt_top.git:
      - name: top
    - master git-salt:salt.git:
      - name: base
      - env: base
    - development git-salt:salt.git:
      - name: development
      - env: development

ext_pillar_first: True
```

**Comment by javicacheiro** [comment]
Same problem using pygit2.

The first issue that requires adding the name option, this should probably be mentioned in the documentation while this is not solved.

The root cause of second issue actually seems that the saltenv option is not read because even if you give a non-existing branch it will return the base pillar (master):
`
salt 'c13-1.local' pillar.items saltenv=noenv`

**Comment by heini** [comment]
I've meanwhile updated to 2015.8.8 and guess what: Now it doesn't work at all with the unmodified test setup from above. Here's the output I get now:
```
# salt -G 'kernel:Linux' state.highstate
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
minion1.example.de:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'test' in environment 'base' is not available on the salt master
minion2.example.de:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'test' in environment 'base' is not available on the salt master
minion3.example.de:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Started: 
    Duration: 
     Changes:   

Summary for minion3.example.de
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
ERROR: Minions returned with non-zero exit code
```

BTW: What's that warning about? file_ignore_glob is commented out, which means it has it's default value.

**Comment by jnials** [comment]
I'm seeing the same problem.  My config is a bit simpler.  

```
hash_type: sha256
gitfs_provider: pygit2
git_pillar_provider: pygit2

fileserver_backend:
  - git

gitfs_base: master
gitfs_pubkey: /root/.ssh/id_rsa.pub
gitfs_privkey: /root/.ssh/id_rsa


gitfs_remotes:
  - git@github.com:jnials/saltstack.git
  - git@github.com:/jnials/salt-top.git

#pillar_roots:
#  base:
#    - /srv/pillar/base
#  foo:
#   - /srv/pillar/foo

git_pillar_pubkey: /root/.ssh/id_rsa.pub
git_pillar_privkey: /root/.ssh/id_rsa

ext_pillar:
  - git:
    - master git@github.com:jnials/pillar.git:
      - root: base
      - name: base
    - master git@github.com:jnials/pillar.git:
      - root: foo
      - name: foo
```
