### ISSUE TITLE
Feature: dockerng.image_present to remove old version of the image when a new version of the image has been pulled/created

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#30507]
Currently, when the image with newer version get's pulled, the old version is left untagged on the host.
Please add the option to remove it automatically:

Example:

```
my-image:
  dockerng.image_present:
    - name: my.registry/my-image:latest
    - force: True
    - remove_old: True
```
