### ISSUE TITLE
Feature Request(?) - salt:// mount points for s3

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#30504]
Both [gitfs](https://docs.saltstack.com/en/latest/ref/configuration/master.html#gitfs-mountpoint) and  [hgfs](https://docs.saltstack.com/en/latest/ref/configuration/master.html#hgfs-mountpoint) offer mountpoints under `salt://`

I was trying to use a `file.recurse` from my s3 bucket, but no dice because 

```
Invalid source 's3://mybucket' (must be a salt:// URI)
```

I haven't been able to find any documentation for an `s3fs_mountpoint` (indeed, a grep of python site-packages only turns up `gitfs_mountpoint`, `hgfs_mountpoint`, `svnfs_mountpoint`, and `minionfs_mountpoint`).

As it stands, I'll have to do some hacky workarounds with cmd.run and the awscli to get this to work :disappointed: 

It would be pretty awesome to have this feature available! :grinning:

**Comment by lorengordon** [comment]
:+1:

**Comment by jfindlay** [comment]
@waynew, thanks for the feature request.

**Comment by The-Loeki** [comment]
https://docs.saltstack.com/en/latest/ref/file_server/all/salt.fileserver.s3fs.html ?

**Comment by waynew** [comment]
@The-Loeki That only offers the `s3://` URI, which makes it impossible for use in states like `file.recurse`, unfortunately.

My current workaround is to use a state like so:

```
install-awscli:
  pip.installed:
    - name: awscli

copy-my-dir:
  file.directory:
    - name: /path/to/my/dir
    - makedirs: True
  cmd.run:
    - name: "aws s3 sync s3://my-bucket /path/to/my/dir"
    - require:
      - pip: install-awscli
    - onlyif: "aws s3 sync --dryrun s3://my-bucket /path/to/my/dir | grep download"
```


It's much clunkier than something like:

```
copy-my-dir:
  file.recurse:
    - makedirs: True
    - name: /path/to/my/dir
    - source: salt://mys3/my-bucket
```
