### ISSUE TITLE
jboss7.deployed state is too interwined with Artifactory

### ISSUE THREAD

**Issue by kartsm** [saltstack/salt#30515]
The documentation for ``jboss7.deployed`` is dominated by Artifactory-specific information; it should really focus more on JBoss.  Similarly the code has too much Artifactory in it.

Is it really that difficult to write two separate but related states to accomplish the same thing?  This seems like a more [DRY](http://c2.com/cgi/wiki?DontRepeatYourself) implementation strategy.
```yaml
artifact_acquired:
  artifactory.downloaded:
   - artifact:
       artifactory_url: http://artifactory.example.invalid/artifactory
       repository: releases
       artifact_id: webapp
       group_id: invalid.example.webapp
       packaging: war
       version: "3.2.7"
   - target_file: /tmp/webapp.war

application_deployed:
  jboss7.deployed:
    - jboss_config: {{ pillar['jboss'] }}
    - salt_source:
        target_file: /tmp/webapp.war
    - require:
        - artifactory: artifact_acquired
```
Note lack of fetch in ``application_deployed``.  (This might require modification to the Python state code to support.)  That state shouldn't have to care exactly how the deployable artifact arrives, as long as it does arrive.  ``jboss-cli.sh`` doesn't really care either.

Artifactory is a genuinely useful piece of software but there may be other methods of distributing artifacts to one's JBoss nodes.  The ``jboss7.deployed`` state and associated module functions should not be hostile to alternative methods of artifact distribution, nor should they have to be modified every time an alternative is created.
