### ISSUE TITLE
Update jboss7.deployed to use jboss-cli.sh to deploy directly from URL without intermediate fetch

### ISSUE THREAD

**Issue by kartsm** [saltstack/salt#30516]
Blindly deploy from URL as `jboss-cli.sh` will allow.

``` yaml
application_deployed:
  jboss7.deployed:
    - jboss_config: {{ pillar['jboss'] }}
    - url: https://... # or http://... or ftp://...
```

Specifically avoiding use of `salt_source` to make clear that we are not using Salt's `file` module as an intermediary.
