### ISSUE TITLE
Missing Minion notifications missing from job cache

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#30528]
Working with Salt with a syndic the notification that a minion did not return was missing from the job cache in the master of masters, while the same job run from the syndic directly would show up in the job cache on the syndic.

Doing some testing on 2015.8.3 (the versions report is below) I didn't see the missing minion info in either of the job caches. It would be good to make sure that info shows up in the job cache and not just on the cli.

```
local:
    Salt Version:
               Salt: 2015.8.3
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: 0.9.1
             PyYAML: 3.10
              PyZMQ: 14.0.1
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-71-generic
             system: Ubuntu 14.04 trusty
```
