### ISSUE TITLE
salt-ssh state.sls testing Failed

### ISSUE THREAD

**Issue by gotnix** [saltstack/salt#30531]
###### salt-ssh --versions-report

``` console
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.8
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.3.1.el6.x86_64
         system: CentOS 6.7 Final
```
###### The SLS file like this:

``` yaml
  salt_minion:
    cmd.run:
      - name: rpm --import 'https://repo.saltstack.com/yum/redhat/6/x86_64/latest/SALTSTACK-GPG-KEY.pub'
      - unless: rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n' | grep 'SaltStack Packaging Team'

    pkgrepo.managed:
      - name: saltstack
      - require:
        - cmd: salt_minion
      - require_in:
        - pkg: salt_minion
      - humanname: SaltStack repo for RHEL/CentOS $releasever
      - baseurl: https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest
      - gpgcheck: 1
      - gpgkey: https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest/$releaseverSALTSTACK-GPG-KEY.pub
      - skip_if_unavailable: True
      - enabled: 1


    pkg.installed:
      - name: salt-minion
      - fromrepo: saltstack
      - require:
        - pkgrepo: salt_minion
      - unless:
        - test -f /usr/bin/salt-minion
```
###### Command `salt-ssh 'staging-sap-1' state.sls salt-minion test=True`, report is

``` console
----------
          ID: salt_minion
    Function: pkg.installed
        Name: salt-minion
      Result: False
     Comment: The following package(s) were not found, and no possible matches were found in the package db: salt-minion
     Started: 15:52:15.333184
    Duration: 1172.384 ms
     Changes:
----------
```
###### The target server repolist:

``` console
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.btte.net
 * epel: ftp.riken.jp
 * extras: mirrors.yun-idc.com
 * rpmforge: mirror.bjtu.edu.cn
 * updates: mirrors.btte.net
repo id           repo name                                               status
base              CentOS-6 - Base                                          6,575
epel              Extra Packages for Enterprise Linux 6 - x86_64          11,915
extras            CentOS-6 - Extras                                           50
rpmforge          RHEL 6 - RPMforge.net - dag                              4,718
updates           CentOS-6 - Updates                                       1,038
repolist: 24,296
```
###### Question

But when i run `salt-ssh 'staging-sap-1' state.sls salt-minion` with same SLS file, the result is _Succeeded_.
If i remove `- fromrepo: saltstack`, whether `test=`  `True` or `False`, the results are successed.

Here is the complete SLS file and logs: https://gist.github.com/gotnix/5c5422ae3f26ad48a433

Anyone have any insight?
