### ISSUE TITLE
wildcard include pillar data broken?

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30545]
``` bash
salt cronos pillar.items
```

``` yaml
cronos:
    ----------
    _errors:
        - Specified SLS 'accounts.*' in environment 'base' is not available on the salt master
    groups:
        ----------
        sysadmin:
            ----------
            description:
                system administrators
            gid:
                2100
        users:
            ----------
            description:
                users
            gid:
                2000
    salt:
        ----------
        log_level_logfile:
            warning
        master:
            master.example.com
        pkg_provider:
            pkgin
        prefix:
            /srv/salt/config
        schedule_highstate:
            False
        smtp:
            ----------
            server:
                smtp.example.com
            tls:
                True
```

```
accounts/init.sls
```

``` bash
####
## accounts
####
## Template: (required) [optional]
## groups:
##   group_name:
##     gid: (1000)
##     description: (my example group)
##     users:
##       - [user_a]
##       - [user_b]
####

## define users
include:
  - accounts.*

## define groups
groups:
  users:
    gid: 2000
    description: users
  sysadmin:
    gid: 2100
    description: system administrators

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
```

```
accounts/sjorge.sls
```

``` bash
####
## user
####
fullname: Jorge Schrauwen
username: sjorge
uid: 1000
shell:
  - zsh
  - bash
groups:
  - users
  - sysadmin
```

Error in master's log
`Pillar render error: Specified SLS 'accounts.*' in environment 'base' is not available on the salt master`
