### ISSUE TITLE
using salt.states.schedule.present always results in a change

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30563]
using salt.states.schedule.present always results in a change of 'seconds: 0' if seconds parameter is not added!

```yaml
packages_daily_upgrades:  ## keep system up to date
  schedule.present:
    - function: pkg.upgrade
    - days: 1
    - splay: 300
```

```yaml
          ID: packages_daily_upgrades
    Function: schedule.present
      Result: True
     Comment: Modifying job packages_daily_upgrades in schedule
     Started: 20:30:01.332020
    Duration: 240.641 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -4,5 +4,4 @@
                   jid_include:True
                   maxrunning:1
                   name:packages_daily_upgrades
                  -seconds:0
                   splay:300
```
