### ISSUE TITLE
mapping values not allowed in states

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30574]
```yaml
## configure user.name and user.email for git repositorie
salt.master::repo:
  git.config_set:
    - repo: /srv/salt/states
    - value: salt
    - names:
        - user.name
        - user.email
            - value: salt@{{ salt.grains.get('fqdn') }}
```

The above should be allowed according the docs: https://docs.saltstack.com/en/latest/ref/states/highstate.html#names-declaration

```
---
local:
    Data failed to compile:
----------
    Rendering SLS 'base:salt.master' failed: mapping values are not allowed here; line 36

---
[...]
    - repo: /srv/salt/states
    - value: salt
    - names:
        - user.name
        - user.email
            - value: salt@cronos.acheron.be    <======================

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2

---
```

**Comment by sjorge** [comment]
Still using super fresh develop branch, from yesterday evening

**Comment by lorengordon** [comment]
Try with a colon at the end of `user.email`. Looks to be missing based on the example in the doc...

```yaml
## configure user.name and user.email for git repositorie
salt.master::repo:
  git.config_set:
    - repo: /srv/salt/states
    - value: salt
    - names:
        - user.name
        - user.email:                                      # <----------------------- colon
            - value: salt@{{ salt.grains.get('fqdn') }}
```
