### ISSUE TITLE
Persist iptables rules through reboot

### ISSUE THREAD

**Issue by brandonwastaken** [saltstack/salt#30667]
I'm attempting to set iptables rules for a Ubuntu machine using Salt, however the rules do not persist through reboot with the save: True option. Am I missing anything or is this an issue? Any help appreciated!

    docker-aws:
      iptables.insert:
        - position: 1
        - table: filter
        - family: ipv4
        - chain: FORWARD
        - jump: DROP
        - i: docker0
        - destination: '169.254.169.254'
        - save: True  `

Both the master and minion are on version 2015.5.3 (Lithium) on Ubuntu 14.04.

**Comment by jfindlay** [comment]
@brandonwastaken, thanks for the report.  Does this also happen on 2015.5.9 or 2015.8.4?

**Comment by brandonwastaken** [comment]
@jfindlay, only tested on 2015.5.3. Could have possibly been Docker interfering with the rules.

**Comment by L4rS6** [comment]
I had the same problem and solved it by installing the `iptables-persistent` package. This should definitely be a dependency on the iptables state when in use with `save: True`. This is my firewall test-state:
```
fw_pkgs:
  pkg.installed:
    - pkgs:
      - conntrack
      - iptables-persistent

default_input_deny:
  iptables.set_policy:
    - chain: FORWARD
    - policy: DROP

allow_spec:
  iptables.append:
    - chain: INPUT
    - match: conntrack
    - ctstate: 'RELATED,ESTABLISHED'
    - jump: ACCEPT
    - save: True
```

## Version report
```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Ubuntu 14.04 trusty
```
