### ISSUE TITLE
supervisord.running launches supervisord.dead process if autostart=True

### ISSUE THREAD

**Issue by muravitskiy** [saltstack/salt#30664]
I have 2 similar services described as follows - if any config file changed then service should be restarted. If 1st service is disabled and any changes occurs in myservice1.supervisord.conf with autostart=True - myservice1 starting
So if [update](https://github.com/saltstack/salt/blob/v2015.8.3/salt/states/supervisord.py#L172) is called every time, maybe [supervisord.dead](https://github.com/saltstack/salt/blob/v2015.8.3/salt/states/supervisord.py#L259) should use [remove](https://github.com/saltstack/salt/blob/v2015.8.3/salt/modules/supervisord.py#L192) and continue tracking changes in disabled services?

myservice.sls

``` yaml
{% from 'myservice.map.jinja' import myservice_config with context -%}

myservice.supervisor.conf:
  file.managed:
    - name: /etc/supervisor/conf.d/myservice.conf
    - source: salt://myservice.supervisor.conf.jinja
    - template: jinja
    - makedirs: True


myservice.conf:
  file.managed:
    - name: {{ myservice_config.runtime.config }}
    - source: salt://myservice.conf.jinja
    - template: jinja
    - makedirs: True


myservice.supervisor:
{% if myservice_config.enabled %}
  supervisord.running:
    - name: {{ myservice_config.runtime.app_name }}
    - update: True
    - watch:
      - file: myservice.supervisor.conf
      - file: myservice.conf
{% else %}
  supervisord.dead:
    - name: {{ myservice_config.runtime.app_name }}
{% endif %}
    - require:
      - pkg: supervisor
```

myservice.supervisor.conf.jinja

``` yaml
{% from 'myservice.map.jinja' import myservice_config with context %}

[program:{{ myservice_config.runtime.app_name }}]
command={{ myservice_config.runtime.path }} -c {{ myservice_config.runtime.config }}
user={{ myservice_config.runtime.user }}
autostart=true
autorestart=true
redirect_stderr=true
```
