### ISSUE TITLE
cron.present uses "name" as a default identifier, rather than the state id

### ISSUE THREAD

**Issue by zmalone** [saltstack/salt#30685]
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cron.html states that cron.present should use the state id as the identifying tag, but if the state id does not match the name that is defined, and identifier isn't defined, id is set to be equal to name.  The name is frequently unsuitable for this, as it will change more often then the state id, leaving orphaned cron jobs.

I've found this behavior to exist in 2015.8.3.

As an example:

```
foo:
    cron.present:
        - name: /usr/local/bin/bar.sh
        - user: root
        - hour: 0
        - minute: 0
```

will have a crontab identifier of "/usr/local/bin/bar.sh", so if bar.sh later becomes "bar.sh >> bar.log", a second job will be created, while if "foo" had been used as an identifier, the job would have been updated rather than duplicated.
