### ISSUE TITLE
acl.present doesn't show changes when it changes ACLs

### ISSUE THREAD

**Issue by optix2000** [saltstack/salt#30692]
Compare the following excerpt where `A` has acl's preset and `B` does not:

```
A:
  acl.present:
    - name: A
    - acl_type: user
    - acl_name: daemon
    - perms: rx

B:
  acl.present:
    - name: B
    - acl_type: user
    - acl_name: daemon
    - perms: r
```

```
----------
          ID: A
    Function: acl.present
        Name: A
      Result: True
     Comment: Permissions are in the desired state
     Started: 19:14:31.605009
    Duration: 23.19 ms
     Changes:
----------
          ID: B
    Function: acl.present
        Name: B
      Result: True
     Comment: Permissions will be applied
     Started: 19:14:31.631761
    Duration: 36.479 ms
     Changes:
----------
```

When the state is run, both show up as green as if no changes had been done, where instead B should have had changes.
