### ISSUE TITLE
git.latest will not use an identity file that does not end in _rsa

### ISSUE THREAD

**Issue by metalseargolid** [saltstack/salt#30716]
If I have a state as follows:

```
some-repo-clone:
  git.latest:
    - name: git@github.com:myuser/myproject.git
    - target: /home/myname/myworkingcopy
    - user: myname
    - identity: /home/myuser/.ssh/github_ecdsa
```

Salt refuses to use the key, and i get a PublicKey Denied error when trying to clone with salt. I can confirm this by either copying or symlinking github_ecdsa to id_rsa and changing the identity in the state to use this instead, which allows the project to be cloned successfully. I have also tested replacing 'id_rsa' with 'anystring_rsa' to confirm that this pattern still works.

I am currently running on LinuxMint 17.3, and the state is being called in a masterless configuration (e.g. with `salt-call --local`).
