### ISSUE TITLE
The HOME or COMPOSER_HOME environment variable must be set for composer to install correctly

### ISSUE THREAD

**Issue by HeathNaylor** [saltstack/salt#30725]
Getting the following error with `salt '*' state.highstate`

```
----------
          ID: get-composer
    Function: cmd.run
        Name: CURL=`which curl`; $CURL -sS https://getcomposer.org/installer | php
      Result: False
     Comment: Command "CURL=`which curl`; $CURL -sS https://getcomposer.org/installer | php" run
     Started: 00:11:20.795352
    Duration: 677.804 ms
     Changes:
              ----------
              pid:
                  21468
              retcode:
                  255
              stderr:
                  PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'The HOME or COMPOSER_HOME environment variable must be set for composer to install correctly' in -:573
                  Stack trace:
                  #0 -(378): getHomeDir()
                  #1 -(111): installComposer(false, false, 'composer.phar', false, false, false)
                  #2 -(13): process(Array)
                  #3 {main}
                    thrown in - on line 573
              stdout:
                  All settings correct for using Composer
----------

```

init.sls for nginx:

```
/var/www/site/:
  composer.installed:
    - no_dev: true
    - composer_home: /usr/local/bin
    - require:
      - cmd: install-composer
```

init.sls for the composer directory

```
get-composer:
  cmd.run:
    - name: 'CURL=`which curl`; $CURL -sS https://getcomposer.org/installer | php'
    - unless: test -f /usr/local/bin/composer
    - cwd: /home/ubuntu/

install-composer:
  cmd.wait:
    - name: mv /home/ubuntu/composer.phar /usr/local/bin/composer
    - cwd: /home/ubuntu/
    - watch:
      - cmd: get-composer
```

**Comment by HeathNaylor** [comment]
Fixed this for the time being by doing the following:
```
get-composer:
  cmd.run:
    - name: 'export COMPOSER_HOME=/usr/local/bin && CURL=`which curl`; $CURL -sS https://getcomposer.org/installer | php'
    - unless: test -f /usr/local/bin/composer
    - cwd: /home/ubuntu/

```

I don't think this should be considered a long term solution.

**Comment by jfindlay** [comment]
@HeathNaylor, thanks for reporting.

**Comment by abednarik** [comment]
HI @HeathNaylor 

 Looking at the code en develop branch, you can use composer_home so set that env variable.

**Comment by HeathNaylor** [comment]
@abednarik I did that, it had no effect.

**Comment by abednarik** [comment]
@HeathNaylor  can you please run ```salt --versions-report```

I tried witha state like this

```yaml
get-composer:
  cmd.run:
    - name: 'CURL=`which curl`; $CURL -sS https://getcomposer.org/installer | php'
    - unless: test -f /usr/local/bin/composer
    - cwd: /home/vagrant/

install-composer:
  cmd.wait:
    - name: mv /home/vagrant/composer.phar /usr/local/bin/composer
    - cwd: /home/vagrant/
    - watch:
      - cmd: get-composer
```

Without issue

```yaml
salt '*' state.apply source
ubuntu:
----------
          ID: get-composer
    Function: cmd.run
        Name: CURL=`which curl`; $CURL -sS https://getcomposer.org/installer | php
      Result: True
     Comment: Command "CURL=`which curl`; $CURL -sS https://getcomposer.org/installer | php" run
     Started: 19:15:16.523526
    Duration: 6309.387 ms
     Changes:
              ----------
              pid:
                  20452
              retcode:
                  0
              stderr:
              stdout:
                  All settings correct for using Composer
                  Downloading...

                  Composer successfully installed to: /home/vagrant/composer.phar
                  Use it: php composer.phar
----------
          ID: install-composer
    Function: cmd.wait
        Name: mv /home/vagrant/composer.phar /usr/local/bin/composer
      Result: True
     Comment: Command "mv /home/vagrant/composer.phar /usr/local/bin/composer" run
     Started: 19:15:22.833721
    Duration: 5.454 ms
     Changes:
              ----------
              pid:
                  20467
              retcode:
                  0
              stderr:
              stdout:

Summary for ubuntu
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
````
