### ISSUE TITLE
state.orchestrate does not work with the scheduler

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#30727]
Here is my pillar file for the minion to setup the schedule:

```
schedule:
  run_my_orch:
    function: state.orchestrate
    hours: 6
    splay: 600 
    args:
      - orchestration.my_orch
```

This example is directly from the documentation found [here](https://docs.saltstack.com/en/latest/topics/jobs/schedule.html#runners)

Next I refresh the pillars for the minion `salt '*' saltutil.refresh_pillar`

Then in the minion debug log I see this error multiple times:

```
[DEBUG   ] Could not LazyLoad state.orchestrate
[INFO    ] Invalid function: state.orchestrate in job run_my_orch. Ignoring.
[DEBUG   ] Could not LazyLoad state.orchestrate
[INFO    ] Invalid function: state.orchestrate in job run_my_orch. Ignoring.
```

And the schedule never runs. 

Versions report for master and minion:

```
ch3ll@ch3ll-centos:~/salt/salt (tagv2015.8.3)$ salt --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-123.8.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

```
ch3ll@ch3ll-centos:~/salt/salt (tagv2015.8.3)$ salt-minion --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-123.8.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

This has also been tested and confirmed on a windows 2008 R2 server

**Comment by gladiatr72** [comment]
That section is about the _runner_ state module rather than the _execution_ state module.

**Comment by jbouse** [comment]
@gladiatr72 yes it is documenting setting up a schedule to execute an orchestration runner job but it fails to actually work as documented. However change this job to actually be:

```
schedule:
  run_my_orch:
    function: cmd.run
    hours: 6
    splay: 600 
    args:
      - salt-run state.orchestrate orchestration.my_orch
```
and the job is understood and accepted... So you are correct... this is about the _runner_ and the ability to use it in scheduling jobs as is documented.

**Comment by gladiatr72** [comment]
@jbouse I'm confused, then.  I'm seeing

```
Runner executions can also be specified on the master within the master configuration file:

schedule:
  run_my_orch:
    function: state.orchestrate
    hours: 6
    splay: 600
    args:
      - orchestration.my_orch
```

Which does work on the master.
