### ISSUE TITLE
Extended profile overwrites minion config

### ISSUE THREAD

**Issue by HeathNaylor** [saltstack/salt#30745]
I have found that when I specify minion configuration on a profile that extends another profile that the minion configuration is overwritten instead of appended to / overridden.

In the example below I would expect stage-web to have the master address as well as additional grains, instead it only has the grains.

```
base:
  provider: ec2
  size: t2.micro
  image: ami-5c207736
  minion:
    master: my.address.com

stage-web:
  extends: base
  minion:
    grains:
      role: webserver
      env: stage
```
