### ISSUE TITLE
Client ACL and external auth system should have support for limiting functions to certain arguments

### ISSUE THREAD

**Issue by torhve** [saltstack/salt#3077]
My use case is that I want to limit a certain PAM user to control his own virtual machine using the virt module. The virt module often takes the VM name as the argument.
Example:

``salt-call virt.destroy VMName``

But if I give a user access to the virt.destroy function, the user could then destroy all VMs on the host.

What would solve it is support for checking arguments to function, for example like this:
```yaml
external_auth:
  pam:
    vmuser:
     - virt.destroy:
        arg0: VMName
```
I'm not sure how the arg-system should work, but should probably include support for regexes, or at the very least a static list of allowed arguments.

**Comment by meggiebot** [comment]
Committed for Boron

**Comment by meggiebot** [comment]
ZD 411

**Comment by DmitryKuzmenko** [comment]
Here is an example of usage:
```yaml
external_auth:
    pam:
        my_user:
            - '*':
                - 'my_mod.*':
                    args:
                        - 'a.*'
                        - 'b.*'
                    kwargs:
                        'kwa': 'kwa.*'
                        'kwb': 'kwb'
```
