### ISSUE TITLE
pillar.get weirdness on latest develop

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30780]
From on the salt master:
```bash
salt mantle pillar.items
```

```yaml
mantle:
    ----------
    accounts:
        ----------
        groups:
            ----------
            service:
                ----------
                description:
                    services
                gid:
                    15
            sysadmin:
                ----------
                description:
                    system administrators
                gid:
                    14
            user:
                ----------
                description:
                    users
                gid:
                    13
        shells:
            ----------
            bash:
                ----------
                package:
                    bash
                path:
                    /opt/local/bin/bash
            nologin:
                ----------
                path:
                    /usr/bin/false
            zsh:
                ----------
                package:
                    zsh
                path:
                    /opt/local/bin/zsh
        users:
            ----------
            sjorge:
                ----------
                authorized_key:
                    ----------
                    enc:
                        ssh-rsa
                    key:
                        xxx
                email:
                    xxx
                fullname:
                    xxx
                groups:
                    - sysadmin
                    - nacl
                    - media_rw
                    - dlbox_rw
                    - bckup_ro
                password:
                    xxx
                primary_group:
                    user
                shell:
                    zsh
                uid:
                    1000
    locale:
        ----------
        locales:
            - en_US.UTF-8
            - nl_BE.UTF-8
        system:
            en_US.UTF-8
    network:
        ----------
        domain:
            xxx
        search:
            - xxx
        subnet:
            ----------
            client:
                ----------
                inet4:
                    xxx
                inet6:
                    xxx
                mtu:
                    1500
                nameservers:
                    - xxx
                    - xxx
                search:
                    - xxx
                vlan:
                    10
            mgmt:
                ----------
                domain:
                    xxx
                inet4:
                    xxx
                inet6:
                    xxx
                mtu:
                    1500
                nameservers:
                    - xxx
                    - xxx
                vlan:
                    40
            server:
                ----------
                inet4:
                    xxx
                inet6:
                    xxx
                mtu:
                    1500
                nameservers:
                    - xxx
                    - xxx
                vlan:
                    30
            storage:
                ----------
                inet4:
                    xxx
                inet6:
                    xxx
                mtu:
                    9000
                nameservers:
                    - xxx
                    - xxx
                vlan:
                    20
    packages:
        ----------
        baseline:
            - tmux
        bundles:
            - salt
        config:
            ----------
            managed:
                True
            prefix:
                /opt
            update:
                True
    salt:
        ----------
        log_level_logfile:
            warning
        master:
            xxx
        prefix:
            /opt/custom/salt
        schedule_highstate:
            False
        smtp:
            ----------
            server:
                xxx
            tls:
                True
    smartos:
        ----------
        notify:
           xxx
    time:
        ----------
        servers:
            - xxx
        timezone:
            Europe/Brussels
```

```bash
salt mantle pillar.get smartos
```

```yaml
mantle:
```

Why locally on the salt-minion it works:

```bash
salt-call pillar.get smartos
```

```yaml
local:
    ----------
    notify:
       xxx
```
