### ISSUE TITLE
How to implement salt.states.boto_rds

### ISSUE THREAD

**Issue by HeathNaylor** [saltstack/salt#30789]
I am running into issues implementing the boto_rds state. Below is my config files. I am getting the following error:

```
[ERROR   ] 'provider'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 169, in parse_args
    process_option_func()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 451, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 2638, in setup_config
    return config.cloud_config(self.get_config_file_path())
  File "/usr/lib/python2.7/dist-packages/salt/config.py", line 1899, in cloud_config
    providers_config)
  File "/usr/lib/python2.7/dist-packages/salt/config.py", line 2058, in vm_profiles_config
    return apply_vm_profiles_config(providers, overrides, defaults)
  File "/usr/lib/python2.7/dist-packages/salt/config.py", line 2085, in apply_vm_profiles_config
    if ':' in details['provider']:
KeyError: 'provider'
```

cloud.maps.d/stage-environment.map

```
stage-web:
  - Salt-Minion1
  - Salt-Minion2
stage-rds:
  - Salt-Stage-RDS1
```

cloud.profiles.d/servers.conf

```
base:
  provider: ec2
  size: t2.micro
  image: <image_id>
  minion:
    master: my.address.com
    master_port: 4508

stage-web:
  extends: base
  minion:
    master: my.address.com
    master_port: 4508
    grains:
      role: webserver
      env: stage

stage-rds:
    region: us-east-1

prod-web:
  extends: base
  minion:
    master: my.address.com
    master_port: 4508
    grains:
      role: webserver
      env: prod

```

salt/top.sls

```
base:
  '*':
    - requirements
    - users
    - ssh
    - logging
    - php
    - composer
  'Salt-Minion':
    - nginx
  'Salt-Stage-RDS1'
    - rds
```

salt/rds/top.sls

```
Ensure myrds RDS exists:
  boto_rds.present:
    - name: myrds
    - allocated_storage: 5
    - db_instance_class: db.t2.micro
    - engine: MySQL
    - master_username: {{ pillar['rds']['master_username'] }}
    - master_user_password: {{ pillar['rds']['master_user_password'] }}
    - region: us-east-1
    - keyid: {{ pillar['rds']['keyid'] }}
    - key: {{ pillar['rds']['key'] }}
```

pillar/top.sls

```
base:
  '*':
    - users
    - rds
```

pillar/rds.sls

```
rds:
    keyid: <key_id>
    key: <key>
    master_username: <master_username>
    master_user_password: <master_user_password>
```

**Comment by rallytime** [comment]
@HeathNaylor So the tricky thing you're running into here is that there is a difference between using the boto_* states and execution modules and the salt-cloud drivers and related API functions. They weren't designed to work together and were developed independently of each other.

To spin up instances via map files or with the `salt-cloud -p ...` command, and to also use the `salt-cloud -d` command, the [EC2 Salt Cloud driver](https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.ec2.html) should be used. There are some helpful docs on how to set up this driver [here](https://docs.saltstack.com/en/latest/topics/cloud/aws.html). Salt Cloud uses the "profile" and "providers" files in `/etc/salt/cloud.pro*.d/` directories to specify instance configurations and authentication information against EC2, connecting to Amazon's API directly.

The boto_* files are "regular" Salt execution modules and states that use the boto library to connect to Amazon's API in a different way than cloud profile/provider files. (They use pillar or minion configs to store API connection information.) These states and modules are called like any other Salt state/module. So in order to create or delete instances with boto instead of the salt-cloud EC2 driver, you'd need to use the [boto_ec2 module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.boto_ec2.html) The [run](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.boto_ec2.html#salt.modules.boto_ec2.run) and [terminate](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.boto_ec2.html#salt.modules.boto_ec2.terminate) functions would be what you'd need, respectively.

The pro of using the boto_* modules/states, is that you can state your EC2 environment/features really nicely. The con of doing that, is you can't use the map/parallel functionality provided by salt-cloud.

Both the cloud-driver and the boto files contain a lot of functionality for managing instances as well as many other aspects of amazon offerings. Which one you choose to use depends on what functionalities you're looking for.

Does that help clear up your questions? At the very least, this division of use isn't incredibly clear in the docs and we should get something added to help others understand this separation in the future.

**Comment by HeathNaylor** [comment]
I think I understand. The issue here is that I am attempting to bring up an RDS instance and then manage it's state using something like boto+* files.

For example right now salt-cloud will bring up my environment (multiple nodes) and then my salt sls files will target the instances created in the top.sls file. I only need to do salt-cloud operations when I am bringing up or terminating instances. After that point all state is kept in my state files.

If I was able to bring up my RDS instance and manage it's state in my top.sls file as well that would be ideal. Is that currently not possible?

**Comment by rallytime** [comment]
Oh, yes that is possible. Check out the `boto_rds.present` state [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_rds.html#salt.states.boto_rds.present).

**Comment by HeathNaylor** [comment]
@rallytime That is what I was trying to do. Do I need to dedicated the handling of the rds instance to one of my minions? I have attempted that and now I get the following error:

```
          ID: rds-instance
    Function: boto_rds.present
        Name: myrds
      Result: False
     Comment: State 'boto_rds.present' was not found in SLS 'rds'
              Reason: 'boto_rds' __virtual__ returned False
     Started:
    Duration:
     Changes:

```

salt/rds/init.sls
```
rds-instance:
  boto_rds.present:
    - name: myrds
    - allocated_storage: 5
    - db_instance_class: db.t2.micro
    - engine: MySQL
    - master_username: <my_username>
    - master_user_password: <my_user_password>
    - region: us-east-1
    - keyid: <key_id>
    - key: <key>
```

salt/top.sls
```
base:
  '*':
    - requirements
    - users
    - ssh
    - logging
    - php
    - composer
  'Salt-Minion-*':
    - nginx
  'Salt-Minion-1'
    - rds
```

**Comment by rallytime** [comment]
```
Do I need to dedicated the handling of the rds instance to one of my minions?
```
Yes, you do need to run the state against a minion. You can use a dedicated, external minion to run this command against, or you can run the command against a local minion (minion process is running on the master with `master: localhost` set in the minion config) or you can run it with something like `salt-call --local`.

You just need to make sure that the minion you're running the command against has the correct boto dependency installed.

**Comment by HeathNaylor** [comment]
@rallytime I have everything installed and running against a dedicated external minion and yet I still get the `State 'boto_rds.present' was not found in SLS 'rds'` error:

```
          ID: python-pip
    Function: pkg.installed
      Result: True
     Comment: Package python-pip is already installed
     Started: 22:44:16.767559
    Duration: 4.146 ms
     Changes:
----------
          ID: boto
    Function: pip.installed
      Result: True
     Comment: All packages were successfully installed
     Started: 22:44:16.915290
    Duration: 1580.126 ms
     Changes:
              ----------
              boto==2.39.0:
                  Installed
----------
          ID: rds-instance
    Function: boto_rds.present
        Name: myrds
      Result: False
     Comment: State 'boto_rds.present' was not found in SLS 'rds'
              Reason: 'boto_rds' __virtual__ returned False
     Started:
    Duration:
     Changes:
```
