### ISSUE TITLE
file.directory recurse to support dir_mode / file_mode ?

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#30805]
Hello,

I got some weird error messages when running my highstate with test=True:

```
          ID: /var/lib/jenkins
    Function: file.directory
      Result: False
     Comment: Types for "recurse" limited to "user", "group" and "mode"
     Started: 11:51:59.444050
    Duration: 54.78 ms
     Changes:
----------
          ID: /var/cache/jenkins
    Function: file.directory
      Result: False
     Comment: Types for "recurse" limited to "user", "group" and "mode"
     Started: 11:51:59.501917
    Duration: 13.208 ms
     Changes:
----------
          ID: /var/log/jenkins
    Function: file.directory
      Result: False
     Comment: Types for "recurse" limited to "user", "group" and "mode"
     Started: 11:51:59.518077
    Duration: 0.828 ms
     Changes:
```

If the highstate run is active then it runs fine through.
=> seems there was some implementation missing for testmode  in https://github.com/saltstack/salt/issues/13866 ?

Definition of these folders:

```
/var/lib/jenkins:
  file.directory:
    - user: www-data
    - group: jenkins
    - mode: 775
    - recurse:
      - user
      - group
      - ignore_files
    - require:
      - pkg: jenkins

/var/cache/jenkins:
  file.directory:
    - user: www-data
    - group: jenkins
    - mode: 775
    - recurse:
      - user
      - group
      - ignore_files
    - require:
      - pkg: jenkins

/var/log/jenkins:
  file.directory:
    - user: www-data
    - group: jenkins
    - mode: 775
    - recurse:
      - user
      - group
      - ignore_files
    - require:
      - pkg: jenkins
```

```
# salt-call --version
salt-call 2015.8.3 (Beryllium)
# lsb_release -d
Description:    Debian GNU/Linux 8.2 (jessie)
```

**Comment by jfindlay** [comment]
@Reiner030, thanks for the report.  I cannot seem to reproduce this error.  Is there anything else I can try?
```
jmoney-main ~ master # mkdir -p /tmp/test/sub
jmoney-main ~ master # touch /tmp/test/A /tmp/test/sub/B
```
```yaml
jmoney-main ~ master # salt jmoney-main state.apply test
jmoney-main:
----------
          ID: /tmp/test
    Function: file.directory
      Result: True
     Comment: Directory /tmp/test updated
     Started: 18:36:15.812413
    Duration: 40.07 ms
     Changes:
              ----------
              mode:
                  0775

Summary for jmoney-main
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  40.070 ms
```
```yaml
jmoney-main ~ master # cat /srv/salt/test.sls
/tmp/test:
  file.directory:
    - user: root
    - group: root
    - mode: 775
    - recurse:
      - user
      - group
      - ignore_files
```
```yaml
jmoney-main ~ master # salt --versions
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2
```
