### ISSUE TITLE
Pillar include documentation improvement

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#30806]
https://docs.saltstack.com/en/latest/topics/pillar/#including-other-pillars has examples. Great! The problem is that the actual outcome for the examples aren't presented.

Proposal: Include the outcome of the

```
include:
  - users
```

as well as

```
include:
  - users:
      defaults:
          sudo: ['bob', 'paul']
      key: users
```

examples.

**Comment by JensRantil** [comment]
To test if the documentation is clear enough, here's my guess how the include will work:
```
# users.sls
peter:
  fullname: Peter Jacobsson
  strong_man: True
arnold:
  fullname: Arnold Schwarzenegger
  strong_man: True
```

For the first example:
The pillar will be exactly the same as `users.sls`, right?

For the second example, the outcome pillar will be:
```
users:
  peter:
    fullname: Peter Jacobsson
    strong_man: True
  arnold:
    fullname: Arnold Schwarzenegger
    strong_man: True
```

If I am wrong, the documentation text might also need some improvements.
