### ISSUE TITLE
require inside cmd.wait results in a True result every time

### ISSUE THREAD

**Issue by wes-novack** [saltstack/salt#30838]
If you use a require inside of a cmd.wait, the state returns as True every time, even if the exit code of the cmd is 1. This doesn't happen if you use a watch statement instead of a require. 

eg;

```
#check if the new config is valid
config-check:
  cmd.wait:
    - name: haproxy -c -f /etc/haproxy/haproxy.cfg
    - require:
      - file: push-config
    - onfail_in:
      - file: restore-backup
```

Salt Master and minion: 2015.8.3
