### ISSUE TITLE
Feature Request Rename or alias formulas

### ISSUE THREAD

**Issue by ChrisLundquist** [saltstack/salt#30857]
It is currently very difficult to reconcile two formulas using the same name. Many of the formulas in https://github.com/saltstack-formulas use import and source paths such as `nginx/map.jinja` and the like, causing them to break when renamed.

The PR opened against the nginx-formula was directed here by @whiteinge mentioning the possibility of an alias syntax like:

`gitfs_remotes: [{'nginx-two': 'https://github.com/saltstack-formulas/nginx-formula.git'}]`

With more discussion in https://github.com/saltstack-formulas/nginx-formula/pull/104

**Comment by babilen** [comment]
I like this. :)

**Comment by jfindlay** [comment]
@ChrisLundquist, thanks for reporting.

**Comment by whiteinge** [comment]
File server backends would need to be able to rewrite the top-level path name (easy), plus `include` statements and "sls requisites" (less easy). Am I missing anything?

Full config examples:

```yaml
gitfs_remotes:
  - nginx-two: https://github.com/saltstack-formulas/nginx-formula.git

file_roots:
  base:
    - nginx-two: /srv/formulas/nginx-formula
```
