### ISSUE TITLE
ssh_auth.present fails to find public key in salt:// path with "Source file ... is missing"

### ISSUE THREAD

**Issue by jetpak** [saltstack/salt#30851]
after upgrading our salt-minion from 2015.5.5-1.el7 to 2015.8.4-1.el7 one of our old states that used to work started failing

the master is at:  2015.8.4 (Beryllium)

Summary:
  - looks like ssh_auth.present fails to find our ssh public key that is in our file_roots
  - the file url is:  salt://_a_binaries/certs/jenkins/ssh_id_rsa.pub
  - the same file is successfully referenced by file.managed
  - however, ssh_auth.present  (source:) seems to fail to find this file

Here is a snippet of the failing state:
```sls
tomcat_jenkins_ssh_auth_centos:
  ssh_auth.present:
    - user: centos
    - source: salt://_a_binaries/certs/jenkins/ssh_id_rsa.pub
```

Here is the output of the failure:
```yaml
sym-es4-dev-ause1-aha3:
----------
          ID: tomcat_jenkins_ssh_auth_centos
    Function: ssh_auth.present
      Result: False
     Comment: Failed to add the ssh key. Source file salt://_a_binaries/certs/jenkins/ssh_id_rsa.pub is missing
     Started: 05:59:18.113648
    Duration: 6.623 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```
