### ISSUE TITLE
prereq causes other states to run with test=True

### ISSUE THREAD

**Issue by RuriRyan** [saltstack/salt#30892]
We've got a state which should check if nested virtualization via kvm is enabled or not. If not it should set the required setting for it to work. This includes a reload of the kvm_intel module, since we don't want to stop and start libvirtd and remove and load the module everytime the state runs we've added a little check and a `prereq` so the check is only in one place.

This `prereq` however causes 'some' other states to run in test=True mode too. The `stop_libvirt` state is also affected. They never get exectued and cause other states to fail.

I don't know why this is happening but I suspect it has something todo with with how the `prereq` gets executed and the test=True handling of state.py (line: 1643, 1708). And again not all future states are affected only some states like `pkg.installed` even though they should be exectuted normally, without tets=True.

Test state:

With the following state file you can reproduce the bug. You should see, that `qemu-kvm: pkg.installed` will be executed with test=True set.

For that to happen you have to install a package, then have a state with prereq and then install another package, that's why I have arranged the states as they are now.

``` sls
libvirt:
  pkg:
    - installed

libvirt-python:
  pkg:
    - installed

stop_libvirt:
  service.dead:
    - name: libvirtd
    - prereq:
      - kmod: rmmod_kvm_intel

rmmod_kvm_intel:
  kmod.absent:
    - name: kvm_intel
    - onlyif:
      - grep N '/sys/module/kvm_intel/parameters/nested'

/etc/modprobe.d/dist.conf:
  file.managed:
    - contents: |
        options kvm-intel nested=y

insmod_kvm_intel:
  kmod.present:
    - name: kvm_intel

start_libvirtd:
  service.running:
    - name: libvirtd
    - enable: True

qemu-kvm:
  pkg:
    - installed
```

``` yaml
[root@salt-master ~]# salt-call --versions
Salt Version:
           Salt: 2015.8.4

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core

```

**Comment by cachedout** [comment]
@RuriRyan Any way I can get you to test #30912? I will try and build out a test case here as well.

**Comment by cachedout** [comment]
Thus far, I cannot replicate this issue:
```
[root@silver salt]# cat issue_30892.sls 
you-get:
  pkg:
    - installed

do_something:
  test.show_notification:
    - text: do_something executing
    - prereq:
      - test: pre_required_state

do_something_if:
  test.show_notification:
    - text: do_something_if_executing
    - onlyif:
      - 'true'

pre_required_state:
  test.succeed_with_changes

vim-jedi:
  pkg:
    - installed
```

```
mp@silver ...salt/salt/states % salt-call --versions-report                                                                                 (git)-[v2015.8.4] 
Salt Version:
           Salt: 2015.8.4
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Dec  6 2015, 15:43:46)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: 1.5.0
       cherrypy: 4.0.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.0
          ioflo: 1.4.3
        libgit2: Not Installed
        libnacl: 1.4.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: 0.9.0
        timelib: 0.2.4
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.3.3-3-ARCH
```

**Comment by RuriRyan** [comment]
@cachedout I've tested your changes and the issue is still happening. I've even used another machine.

If you want a [trace.log](https://www.hidrive.strato.com/lnk/XBMqiOrI).

```
[root@minion hypervisor]# salt-call --versions
Salt Version:
           Salt: 2015.8.5
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

```
[root@minion hypervisor]# cat issue.sls 
libvirt:
  pkg:
    - installed

stop_libvirt:
  service.dead:
    - name: libvirtd
    - prereq:
      - kmod: rmmod_kvm_intel

rmmod_kvm_intel:
  kmod.absent:
    - name: kvm_intel
    - onlyif:
      - grep N '/sys/module/kvm_intel/parameters/nested'

/etc/modprobe.d/dist.conf:
  file.managed:
    - contents: |
        options kvm-intel nested=y

insmod_kvm_intel:
  kmod.present:
    - name: kvm_intel

start_libvirtd:
  service.running:
    - name: libvirtd
    - enable: True

qemu-kvm:
  pkg:
    - installed
```

```
local:
----------
          ID: libvirt
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: libvirt
     Started: 09:43:46.734976
    Duration: 13212.333 ms
     Changes:   
              ----------
              augeas-libs:
                  ----------
                  new:
                      1.4.0-2.el7
                  old:
              avahi-libs:
                  ----------
                  new:
                      0.6.31-15.el7
                  old:
              bridge-utils:
                  ----------
                  new:
                      1.5-9.el7
                  old:
              bzip2:
                  ----------
                  new:
                      1.0.6-13.el7
                  old:
              cyrus-sasl:
                  ----------
                  new:
                      2.1.26-19.2.el7
                  old:
              cyrus-sasl-md5:
                  ----------
                  new:
                      2.1.26-19.2.el7
                  old:
              dnsmasq:
                  ----------
                  new:
                      2.66-14.el7_1
                  old:
              fuse-libs:
                  ----------
                  new:
                      2.9.2-6.el7
                  old:
              glusterfs:
                  ----------
                  new:
                      3.7.1-16.el7
                  old:
              glusterfs-api:
                  ----------
                  new:
                      3.7.1-16.el7
                  old:
              glusterfs-client-xlators:
                  ----------
                  new:
                      3.7.1-16.el7
                  old:
              glusterfs-libs:
                  ----------
                  new:
                      3.7.1-16.el7
                  old:
              gnutls:
                  ----------
                  new:
                      3.3.8-14.el7_2
                  old:
              gnutls-dane:
                  ----------
                  new:
                      3.3.8-14.el7_2
                  old:
              gnutls-utils:
                  ----------
                  new:
                      3.3.8-14.el7_2
                  old:
              gperftools-libs:
                  ----------
                  new:
                      2.4-7.el7
                  old:
              gssproxy:
                  ----------
                  new:
                      0.4.1-7.el7
                  old:
              iscsi-initiator-utils:
                  ----------
                  new:
                      6.2.0.873-32.el7
                  old:
              iscsi-initiator-utils-iscsiuio:
                  ----------
                  new:
                      6.2.0.873-32.el7
                  old:
              keyutils:
                  ----------
                  new:
                      1.5.8-3.el7
                  old:
              ldns:
                  ----------
                  new:
                      1.6.16-7.el7
                  old:
              libbasicobjects:
                  ----------
                  new:
                      0.1.1-25.el7
                  old:
              libcgroup:
                  ----------
                  new:
                      0.41-8.el7
                  old:
              libcollection:
                  ----------
                  new:
                      0.6.2-25.el7
                  old:
              libevent:
                  ----------
                  new:
                      2.0.21-4.el7
                  old:
              libini_config:
                  ----------
                  new:
                      1.2.0-25.el7
                  old:
              libiscsi:
                  ----------
                  new:
                      1.9.0-6.el7
                  old:
              libnfsidmap:
                  ----------
                  new:
                      0.25-12.el7
                  old:
              libpath_utils:
                  ----------
                  new:
                      0.2.1-25.el7
                  old:
              libref_array:
                  ----------
                  new:
                      0.1.5-25.el7
                  old:
              libtalloc:
                  ----------
                  new:
                      2.1.2-1.el7
                  old:
              libtevent:
                  ----------
                  new:
                      0.9.25-1.el7
                  old:
              libtirpc:
                  ----------
                  new:
                      0.2.4-0.6.el7
                  old:
              libunwind:
                  ----------
                  new:
                      1.1-10.el7
                  old:
              libverto-tevent:
                  ----------
                  new:
                      0.2.5-4.el7
                  old:
              libvirt:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-client:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-daemon:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-daemon-config-network:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-daemon-config-nwfilter:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-daemon-driver-interface:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-daemon-driver-lxc:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-daemon-driver-network:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-daemon-driver-nodedev:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-daemon-driver-nwfilter:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-daemon-driver-qemu:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-daemon-driver-secret:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libvirt-daemon-driver-storage:
                  ----------
                  new:
                      1.2.17-13.el7_2.2
                  old:
              libxslt:
                  ----------
                  new:
                      1.1.28-5.el7
                  old:
              lzop:
                  ----------
                  new:
                      1.03-10.el7
                  old:
              mozjs17:
                  ----------
                  new:
                      17.0.0-12.el7
                  old:
              netcf-libs:
                  ----------
                  new:
                      0.2.8-1.el7
                  old:
              nettle:
                  ----------
                  new:
                      2.7.1-4.el7
                  old:
              nfs-utils:
                  ----------
                  new:
                      1.3.0-0.21.el7
                  old:
              nmap-ncat:
                  ----------
                  new:
                      6.40-7.el7
                  old:
              numad:
                  ----------
                  new:
                      0.5-14.20140620git.el7
                  old:
              polkit:
                  ----------
                  new:
                      0.112-5.el7
                  old:
              polkit-pkla-compat:
                  ----------
                  new:
                      0.1-4.el7
                  old:
              qemu-img:
                  ----------
                  new:
                      1.5.3-105.el7_2.3
                  old:
              quota:
                  ----------
                  new:
                      4.01-11.el7
                  old:
              quota-nls:
                  ----------
                  new:
                      4.01-11.el7
                  old:
              radvd:
                  ----------
                  new:
                      1.9.2-9.el7
                  old:
              rpcbind:
                  ----------
                  new:
                      0.2.0-33.el7_2
                  old:
              rsyslog-mmjsonparse:
                  ----------
                  new:
                      7.4.7-12.el7
                  old:
              tcp_wrappers:
                  ----------
                  new:
                      7.6-77.el7
                  old:
              trousers:
                  ----------
                  new:
                      0.3.13-1.el7
                  old:
              unbound-libs:
                  ----------
                  new:
                      1.4.20-26.el7
                  old:
              yajl:
                  ----------
                  new:
                      2.0.4-4.el7
                  old:
----------
          ID: stop_libvirt
    Function: service.dead
        Name: libvirtd
      Result: True
     Comment: No changes detected
     Started: 
    Duration: 
     Changes:   
----------
          ID: rmmod_kvm_intel
    Function: kmod.absent
        Name: kvm_intel
      Result: True
     Comment: onlyif execution failed
     Started: 09:44:00.225197
    Duration: 8.078 ms
     Changes:   
----------
          ID: /etc/modprobe.d/dist.conf
    Function: file.managed
      Result: True
     Comment: File /etc/modprobe.d/dist.conf is in the correct state
     Started: 09:44:00.233548
    Duration: 1.552 ms
     Changes:   
----------
          ID: insmod_kvm_intel
    Function: kmod.present
        Name: kvm_intel
      Result: True
     Comment: Kernel module kvm_intel is already present
     Started: 09:44:00.235284
    Duration: 6.692 ms
     Changes:   
----------
          ID: start_libvirtd
    Function: service.running
        Name: libvirtd
      Result: True
     Comment: Service libvirtd is already enabled, and is running
     Started: 09:44:00.242187
    Duration: 541.28 ms
     Changes:   
              ----------
              libvirtd:
                  True
----------
          ID: qemu-kvm
    Function: pkg.installed
      Result: None
     Comment: The following packages are set to be installed/updated: qemu-kvm
     Started: 09:44:00.783820
    Duration: 2416.814 ms
     Changes:   

Summary for local
------------
Succeeded: 7 (unchanged=1, changed=2)
Failed:    0
------------
Total states run:     7
```

**Comment by cachedout** [comment]
@RuriRyan Has this worked with you in any Salt release or is this a regression for you?

**Comment by RuriRyan** [comment]
I can't really tell. The state was in our codebase for like 2 - 3 months now. I would say it worked when it was written (I didn't write the state - a colleague did), but I just now discovered the issue and managed to track it down.

**Comment by cachedout** [comment]
@RuriRyan OK. We were concerned that this was a regression in that release but the original PR that I had you test pulled out the changes that we were concerned with, so that suggests that this isn't true.

This is very odd though. I think the next step is probably to spin up a VM and try your exact state file, though it's unclear to me why yours would exhibit the issue while mine does not if this is truly a bug in the state compiler.

**Comment by cachedout** [comment]
We're still working on this. Thus far, this does *not* look like a regression between 2015.8.3 and 2015.8.4.

**Comment by Ch3LL** [comment]
I was able to replicate this issue with the following sls file on 2015.8.3 and 2015.8.4:

```
libvirt-python:
  pkg:
    - installed

stop_libvirt:
  service.dead:
    - name: libvirtd
    - prereq:
      - kmod: rmmod_kvm_intel

rmmod_kvm_intel:
  kmod.absent:
    - name: kvm_intel
    - onlyif:
      - grep N '/sys/module/kvm_intel/parameters/nested'

qemu-kvm:
  pkg:
    - installed
```

When i changed the order of were `qemu-kvm` was located like below it worked:

```
libvirt-python:
  pkg:
    - installed

qemu-kvm:
  pkg:
    - installed

stop_libvirt:
  service.dead:
    - name: libvirtd
    - prereq:
      - kmod: rmmod_kvm_intel

rmmod_kvm_intel:
  kmod.absent:
    - name: kvm_intel
    - onlyif:
      - grep N '/sys/module/kvm_intel/parameters/nested'
```

When i removed `onlyif` it also worked.

I found were the regression was:
1. works in v2015.5.2
2. doesn't work in v2015.5.3

Here is the git blame:

```
git bisect :
be18439736d8c9e247fed3929365ad3d6148d045 is the first bad commit
commit be18439736d8c9e247fed3929365ad3d6148d045
Author: Thomas Jackson <jacksontj.89@gmail.com>
Date:   Fri Jun 19 08:50:32 2015 -0700

    Don't incur a "_load_all" of the lazy_loader while looking for mod_init.
    
    Since we were checking if mod_init is in the loader dict-- and we still allow for module merging (#20540) we will do a load_all for every module without mod_init. This patch makes it so we load w/e module the function is in, then check if we have loaded a mod_init. This cuts out ~600ms on my local simple state.sls runs

:040000 040000 93d63be355d3cc8a90d72d9616131d03139d93d3 df080513276ec20c03485fb5d4e30a6c29112fa0 M	salt
```
