### ISSUE TITLE
Get assigned states inside minions

### ISSUE THREAD

**Issue by pouldenton** [saltstack/salt#30890]
Hello!
### 2. Even better will be the ability to manage states execution based on another assigned states.

1 It looks like one of the best solutions to achieve this is exporting minion actual states into grains.

At the moment there are not so much opportunities to achieve that, for example this ugly construction (i don't even understand why it works in spite of conflicts with hightstate, maybe you know better way ):

```
{% for env, state in salt['state.show_top']('queue=True').iteritems()  %}

state_grains:
  grains.list_present:
    - name: software_flags:assigned_states
    - value: {{ state }}
    - order: 5

{% endfor %}

```

And then we need to inverse this construction to remove obsolete grains...

2 This is based on previous solution, but now we can react on changes in assigned states, for example, we can automatically handle mutually exclusive states without any conflicts:

```
{% if salt['grains.get']('software_flags:software_configured').count('ntp.server.config') == 0 %}

{% from "ntp/map.jinja" import ntp with context %}

ntp_client_config:
  file.managed:
    - name: {{ ntp.config  }}
    - source: {{ ntp.client_config_src  }}
    - backup: minion
    - user: root
    - group: root
    - mode: 644
    - template: jinja
    - watch_in:
        - service: {{ ntp.service  }}

{% endif %}
```

Why we need such options in spite of great Salt targeting system? 
There are some systems (such as Foreman used by me), where states can be assigned to the
minion in one mouse click and we need to solve maximum possible problems and conflicts at the
states design stage. I think the number of such systems will be grow as the Salt grows.

**Comment by jfindlay** [comment]
@pouldenton, thanks for reporting.  I am unsure what you are trying to achieve.  In your example you have predicated the execution of the ntp state on a custom grain.  However, salt states are designed to be idempotent, meaning that running them once should produce the same result as if you had run them multiple times.

**Comment by pouldenton** [comment]
@jfindlay, thanks for response. I'm trying to achieve some more automation with states. If there will be information about assigned states, inside grains system, we will be able to react on this. 
**
Example 1: **

let's imagine that we have several clients and server for them. First of all, if client should be configured against that server, we need to store information about this server (host name, ip address, etc...) somewhere, maybe inside pillars, and vise versa, we need to store some information about client to grant them access inside server. But we already have all this data, we known which host is server and which is client, based on states assigned to them. And we can link them together, based on that information. We just need to find ip address or host name of the suitable server inside client.

Here is some hack to export assigned states into grains, thanks to xenophonf from Salt IRC:

```
assigned_states:
  grains.present:
    - name: software_flags:assigned_states
    - value: {{ salt['state.show_top'](queue=True)|yaml }}
```

Based on this, we can find server from the client. ntpd is not the best example, but very simple, here is the part of ntp.conf for minion that acts as ntpd server :

```
{% for server, addrs in salt['mine.get']('J@hostgroup:dc1 and P@software_flags:assigned_states:*:ntp.client.config', 'network.ip_addrs', expr_form='compound').items() %}                                                                                                                                 
restrict {{ addrs[0] }}                                                                                                                                                                                      
{% endfor %}
```
And here is the part of ntp.conf for minion that acts as client:

```
{% for server, addrs in salt['mine.get']('J@hostgroup:dc1 and P@software_flags:assigned_states:*:ntp.server.config', 'network.ip_addrs', expr_form='compound').items() %}                                                                                                                                 
server {{ addrs[0] }}                                                                                                                                                                                      
{% endfor %}
```
Also, we can merge this data with pillars, like formulas does

**Example 2:**

We can prevent some mistakes on states assigning. If we know that some states are conflicting, we can prevent their execution. In my first post, i prevent execution of state ntp_client_config if state ntp.server.config set on the same minion.
