### ISSUE TITLE
git.latest does not update origin URL unless there are new commits

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#30906]
I switched a repo from bitbucket to github.   The only change in the state was the name line. 

```
my_git_repo:
  git.latest:
    - name: git@github.com:xxxxxx/myrepo.git
    - user: www-data
    - target: /home/www-data/php/myrepo
    - rev: master
    - identity: /home/www-data/.ssh/deployment_key
    - submodules: True
```

old name line 

```
    - name: git@bitbucket.org:xxxxxx/myrepo.git
```

when I ran this state with no new commits on myrepo,  the state showed no changes

```
          ID: my_git_repo
    Function: git.latest
        Name: git@github.com:xxxxxx/myrepo.git
      Result: True
     Comment:
     Started: 20:15:48.769791
    Duration: 537.615 ms
     Changes:
```

and the .git/config did not get changed

```
# grep -A 2 '\[remote' .git/config
[remote "origin"]
    url = git@bitbucket.org:xxxxxx/myrepo.git
    fetch = +refs/heads/*:refs/remotes/origin/*
```

But when there were new commits to apply did the update and also updated .git/config

```
          ID: my_git_repo
    Function: git.latest
        Name: git@github.com:xxxxxx/myrepo.git
      Result: True
     Comment: Repository /home/www-data/php/myrepo updated
     Started: 19:18:44.180815
    Duration: 4012.608 ms
     Changes:
              ----------
              remote/origin:
                  ('git@bitbucket.org:xxxxxx/myrepo.git', 'git@bitbucket.org:xxxxxx/myrepo.git') => git@github.com:xxxxxx/myrepo.git
              remote/origin/master:
                  None => origin
              revision:
                  916fa27040f1c374e680b064cf26f5a50b32a9d6 => 41e132b5d457f4a1195c9772b4f1eb61484c28d4
```

```
# grep -A 2 '\[remote' .git/config
[remote "origin"]
    url = git@github.com:xxxxxx/myrepo.git
    fetch = +refs/heads/*:refs/remotes/origin/*
```
