### ISSUE TITLE
Cyrillic filename creation incorrectly working on windows-minion

### ISSUE THREAD

**Issue by steemandlinux** [saltstack/salt#30982]
yaml_utf8: True on server and minions.

```
# -*- coding: utf-8 -*-
cyrtest:
   file.managed:
    - name: C:\тест.txt
    - source: salt://test.txt
```

```
salt 'test...' state.highstate
test...:
----------
          ID: cyrtest
    Function: file.managed
        Name: C:\тест.txt
      Result: True
     Comment: File C:\тест.txt updated
     Started: 13:45:22.078000
    Duration: 140.0 ms
     Changes:   
              ----------
              diff:
                  New file

Summary for test...
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1

```

result: http://i.imgur.com/sUhRrvK.png
