### ISSUE TITLE
Problem with a file.managed state when running state.highstate

### ISSUE THREAD

**Issue by jrbaskwill** [saltstack/salt#31023]
I'm having a problem with a file.managed state when running state.highstate.

The state works for some minions, but not for others.  The minions that it fails on seem random - it is not always the same minions.

Here is a traceback that shows the error:

``` python-traceback
[INFO    ] Running state [/etc/polkit-1/localauthority/50-local.d/disable-shutdown.pkla] at time 15:59:42.022458
[INFO    ] Executing state file.managed for /etc/polkit-1/localauthority/50-local.d/disable-shutdown.pkla
[DEBUG   ] LazyLoaded file.user_to_uid
[DEBUG   ] LazyLoaded cp.hash_file
[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1581, in managed
    follow_symlinks)
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3992, in manage_file
    name_sum = get_hash(real_name, source_sum['hash_type'])
TypeError: list indices must be integers, not str

[ERROR   ] Unable to manage file: list indices must be integers, not str
[INFO    ] Completed state [/etc/polkit-1/localauthority/50-local.d/disable-shutdown.pkla] at time 15:59:42.153355
```

This is the state:

``` sls
linuxlab-disable-shutdown-file:
  file.managed:
    - name: /etc/polkit-1/localauthority/50-local.d/disable-shutdown.pkla
    - source: salt://files/disable-shutdown.pkla
    - saltenv: linuxlab
    - user: root
    - group: root
    - mode: 644
```

Here are the version reports:

``` yaml
salt-minion --versions-report
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Ubuntu 14.04 trusty
```

``` yaml
salt-master --versions-report
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Ubuntu 14.04 trusty

```

Are you seeing any errors in the master debug log? I wonder if this could be a fileserver error that's giving invalid data to the minions? - Colton Myers
## 

Colton Myers
Core Engineer, SaltStack

I'm haven't found anything in the logs yet, but it does seem to related to the fileserver.  If I move the files off of the master server to a web server, everything works as it should.  Why would the fileserver be causing issues?  Did I do something wrong? - JRB

Actually I saw the word "hash" and assumed the fileserver. It looks like there may be a bug in the file module itself, based on the stacktrace. Would you mind submitting an issue on Github? - Colton Myers
