### ISSUE TITLE
salt.states.rvm.gemset_present not working

### ISSUE THREAD

**Issue by papiveron** [saltstack/salt#31048]
Hi, 

When I use the rvm state provided in the salt documentation it doesn't work, and always raise **RVM is not installed** error, even sourcing rvm, while working when i run **gem install ...** from command line.

Here is my rvm init.sls :

```
# installing rvm with dependency from official salt recommendation:
# https://docs.saltstack.com/en/2015.5/ref/states/all/salt.states.rvm.html

#rvm:
#  group.present: []
#  user.present:
#    - gid: rvm
#    - home: /home/rvm
#    - require:
#      - group: rvm

rvm-deps:
  pkg.installed:
    - pkgs:
      - bash
      - coreutils
      - gzip
      - bzip2
      - gawk
      - sed
      - curl
      - git
      - subversion

mri-deps:
  pkg.installed:
    - pkgs:
      - build-essential
      - openssl
      - libreadline6
      - libreadline6-dev
      - zlib1g
      - zlib1g-dev
      - libssl-dev
      - libyaml-dev
      - libsqlite3-0
      - libsqlite3-dev
      - sqlite3
      - libxml2-dev
      - libxslt1-dev
      - autoconf
      - libc6-dev
      - libncurses5-dev
      - automake
      - libtool
      - bison
      - subversion
      - ruby

install_rvm:
  cmd.run:
    - name: curl -sSL https://get.rvm.io | bash
    - user: root
    - unless: /usr/local/rvm/bin/rvm --version
zsh_configuration:
  file.append:
    - name: /etc/zsh/zshrc
    - require:
      - cmd: install_rvm
    - text: source /usr/local/rvm/scripts/rvm

bash_configuration:
  file.append:
    - name: /etc/bash.bashrc
    - require:
      - cmd: install_rvm
    - text: source /usr/local/rvm/scripts/rvm

source_rvm:
  cmd.run:
    - name: source /usr/local/rvm/scripts/rvm
    - require:
      - cmd: install_rvm
```

And here is the state to install puma gem  for example :

```
include:
  - .ruby

puma:
  rvm.gemset_present:
    - user: root
```

which gives the error 

```
----------
          ID: compass
    Function: rvm.gemset_present
      Result: False
     Comment: RVM is not installed.
     Started: 17:27:10.616814
    Duration: 0.802 ms
     Changes:   
----------
```

But if I change the state to:

```
include:
  - .ruby

puma:
  gem.installed:
    - name: puma
```

It works and gives

```
----------
          ID: puma
    Function: gem.installed
      Result: True
     Comment: Gem is already installed.
     Started: 17:27:10.617764
    Duration: 378.122 ms
     Changes:   
----------
```

Can you tell me what's wrong with **salt.states.rvm.gemset_present** state please?

Thankk you.

Regards.
