### ISSUE TITLE
file.copy reports failed even when file was copied on ZFS

### ISSUE THREAD

**Issue by m-o-n-k** [saltstack/salt#31047]
From the sls file:
```
/etc/pve/pve-root-ca.pem:
  file.copy:
    - source: /etc/ssl/certs/sub.class3.server.ca.pem
    - user: root
    - group: www-data
    - mode: 640
    - require:
      - sls: apps.pki
```
(apps.pki just copies the certificates on the node)

Situation on the node before run (did the run with apps.pki once before):
```
root@proxmox:~# ll /etc/ssl/certs/sub.class3.server.ca.pem 
-rw-r--r-- 1 root root 2212 Feb  9 18:08 /etc/ssl/certs/sub.class3.server.ca.pem
```

```
root@proxmox:~# ll /etc/pve/pve-root-ca.pem
ls: cannot access /etc/pve/pve-root-ca.pem: No such file or directory
```

Situation after the run:
```
root@proxmox:~# ll /etc/pve/pve-root-ca.pem
-rw-r----- 1 root www-data 2212 Feb  9 18:22 /etc/pve/pve-root-ca.pem
```

Everythink has worked out so far but the report from salt:
```
----------
          ID: /etc/pve/pve-root-ca.pem
    Function: file.copy
      Result: False
     Comment: Failed to copy "/etc/ssl/certs/sub.class3.server.ca.pem" to "/etc/pve/pve-root-ca.pem"
     Changes:   
...
Summary
-------------
Succeeded: 13
Failed:     1
-------------
Total:     14
```

This also applies with `force: true` enabled.

On the next run salt reports all states as succeeded so it only behaves faulty when it applies the file.copy change.

This happens with Proxmox 4.1/Debian Jessie on ZFS.
