### ISSUE TITLE
Exception 'pillar' occurred in scheduled job on the master

### ISSUE THREAD

**Issue by danlsgiga** [saltstack/salt#31052]
This exception is happening every loop_interval only when I have a schedule set on the master config using the "- when:" option. If I change that to use "minutes: 300", for example, it works fine. 
The scheduled runner does not execute at all when this exception occurs.

Here is my /etc/salt/master.d/schedule.conf:

```
schedule:
  ssl_session_ticket_deploy:
    enabled: True
    function: ssl_session_ticket.deploy
    args:
      - email@example.com
    maxrunning: 1
    when: 11:35am
```

My versions:

```
Salt Version:
       Salt: 2015.8.5

Dependency Versions:
      Jinja2: 2.7.2
    M2Crypto: 0.21.1
        Mako: Not Installed
      PyYAML: 3.11
       PyZMQ: 14.7.0
      Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
        RAET: Not Installed
     Tornado: 4.2.1
         ZMQ: 4.0.5
        cffi: 0.8.6
    cherrypy: 3.2.2
    dateutil: 1.5
       gitdb: Not Installed
   gitpython: Not Installed
       ioflo: Not Installed
     libgit2: 0.21.0
     libnacl: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.4.6
mysql-python: Not Installed
   pycparser: 2.14
    pycrypto: 2.6.1
      pygit2: 0.21.4
python-gnupg: Not Installed
       smmap: Not Installed
     timelib: Not Installed

System Versions:
       dist: centos 7.2.1511 Core
    machine: x86_64
    release: 3.10.0-327.4.5.el7.x86_64
     system: CentOS Linux 7.2.1511 Core
```
