### ISSUE TITLE
Automatic Invalidation of ThinTGZ

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#31079]
After a lot of successful runs of salt-ssh, the following bug occurs:

```
salt:/srv # salt-ssh minion-server state.sls deploy.install
 	minion-server:
----------
          ID: necessary_packages
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'root'
              Reason: 'pkg.installed' is not available.
     Started:
    Duration:
     Changes:
```

Our dirty solution: removing the thin-tgz on the minion

`minion-server:~ # rm -rf /tmp/.root_dcdf8c_salt`
