### ISSUE TITLE
Cannot specify size in map file in 2015.8

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#31099]
When specifying the size in a map file instead of the profile configuration file I receive and error when trying to create/provision the VM. Here is my test case:

/etc/salt/cloud.providers.d/amazon.conf

```
amazon:                                                                                                                                                                                                                                
  provider: ec2                                                                                                                                                                                                                        
  id: <id>                                                                                                                                                                                                           
  key: <key>                                                                                                                                                                                       
  securitygroup: <security group>                                                                                                                                                                                                              
  private_key: <key>                                                                                                                                                                                      
  keyname: ch3ll-key                                                                                                                                                                                                               
  ssh_interface: public_ips                                                                                                                                                                                                            
  ssh_username: root      
```

/etc/salt/cloud.profiles.d/amazon.conf

```
ec2_centos_6:                                                                                                                                                                                                                          
  image: ami-8997afe0                                                                                                                                                                                                                  
  provider: amazon 
```

map file

```
ec2_centos_6:                                                                                                                                                                                                                          
  - ch3ll_test_support8:                                                                                                                                                                                                               
      size: t1.micro
```

When I run `sudo salt-cloud -m /srv/salt/states/test-map.sls -ldebug` I receive the following error:

```
The following virtual machines are set to be created:
  ch3ll_test_support8

Proceed? [N/y] y
... proceeding
[INFO    ] Calculating dependencies for ch3ll_test_support8
[DEBUG   ] Got execution order 0 for ch3ll_test_support8
[DEBUG   ] No make_master found in map
[WARNING ] There's no master defined on the 'ch3ll_test_support8' VM settings.
[DEBUG   ] Generating minion keys for 'ch3ll_test_support8'
[ERROR   ] The required 'size' configuration setting is missing from the 'ec2_centos_6' profile, which is configured under the 'amazon' alias.
[INFO    ] Complete
[DEBUG   ] LazyLoaded nested.output
ch3ll_test_support8:
    False
```

```
ch3ll@ch3ll-centos:/srv/salt/states$ salt --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-123.8.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

I also tested this in 2015.8.5 and received the same error. This was previously working in the 2015.5 branch. I tested 2015.5.3 and 2015.5.9 tags and it was able to create the VM with no error.
