### ISSUE TITLE
state minion regexp doesn't work - CentOS 6

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#31123]
hello

according to this: https://docs.saltstack.com/en/latest/topics/targeting/globbing.html

this state should work:

```
/etc/ntp.conf:
  file.managed:
    - source:
      {% if grains['id'] == 'host(1|2)c' %}
      - salt://ntp/files/ntp.conf.server
      {% elif grains['id'] != 'host[1|2]c' %}
      - salt://ntp/files/ntp.conf.{{ grains['fqdn'] }}
      - salt://ntp/files/ntp.conf.default
      {% endif %}
    - user: root
    - group: root
    - mode: 644
```

but it return with ntp.conf.default regardless the state was executed on host1c or host2c.

salt version:
salt-2015.8.5-1.el6.noarch

**Comment by tbaker57** [comment]
I think the jinja rendering in your issue is separate from targeting. I don't think jinja2 supports regex matching natively. You'd need to write a custom jinja filter for that (or use another templating engine such as Mako).

cheers,
Tim

**Comment by jfindlay** [comment]
@BalintSzigeti, also your jinja logic tests whether the id grain is literally `host(1|2)c` or `host[1|2]c`.  In order to get pattern matching you will need to look into the options @tbaker57 has mentioned.

**Comment by gladiatr72** [comment]
As my salt mentor (hi, @whiteinge! :beer: :) told me on several occasions, beyond very basic logic, you'll be miles ahead to do the heavy lifting in python.

I have a couple *custom* execution modules that hold nothing but utility functions for use within state files.  So, something along the lines of:

/srv/salt/_modules/tplutils.py
```python

import re

def __virtual__():
  return __name__

def rematch(pattern, target):
  """ 
      (because Jinja makes me want to cut myself)

      args:
          regex pattern (str)
          target text (str)
  """
           
  return True if re.match(r'{}'.format(pattern), target) else False
```

could then be called like

```yaml

/etc/ntp.conf:
  file.managed:
    - source:
      {% if salt.tplutils.rematch(grains['id'], 'host(1|2)c') %}
      - salt://ntp/files/ntp.conf.server
      {% else %}
      - salt://ntp/files/ntp.conf.{{ grains['fqdn'] }}
      - salt://ntp/files/ntp.conf.default
      {% endif %}
    - user: root
    - group: root
    - mode: 644
```
