### ISSUE TITLE
Non-Statefull results with file.replace

### ISSUE THREAD

**Issue by bmgraves** [saltstack/salt#31127]
This is a very specific use case, and Might not be considered a "bug" so much, but still something that causes minor issues.

I'm using salt at the moment to control boot options for my grub menu. To do this I use file.replace, to search for the kernel line pattern, split it into 2 sections: The "static" section, and the "options" section. I then repl with the static section + boot options, the state looks like this:

```
{% set cpu1 = (grains['num_cpus']-1) %}
{% set cpu2 = (grains['num_cpus']-2) %}
{% set cpu3 = (grains['num_cpus']-3) %}
{% set cpu4 = (grains['num_cpus']-4) %}
{% set cpu5 = (grains['num_cpus']-5) %}
{% set cpus = cpu5|string + ',' + cpu4|string + ',' + cpu3|string + ',' + cpu2|string + ',' + cpu1|string %}
{% set bootoptions = 'quiet nosoftlockup isolcpus=' + cpus + ' intel_idle.max_cstate=0 idle=poll processor.max_cstate=0 mce=ignore_ce crashkernel=auto audit=1' %}

insert-options:
  file.replace:
    - name: /home/bmgraves/root/boot/grub/grub.conf
    - pattern: (kernel \/vmlinuz-.* quiet)(.*)
    - repl: '\1 {{ bootoptions }}'
```

This works well as far as modification goes, but it is non-stateful and will run each time the formula is applied. 

Is it possible to have salt expand the "\1" during its evaluation of the pattern to see if the state is correct?

```
Salt: 2015.5.8
Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
Jinja2: unknown
M2Crypto: 0.20.2
msgpack-python: 0.4.6
msgpack-pure: Not Installed
pycrypto: 2.0.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.3.1
RAET: Not Installed
ZMQ: 3.2.5
Mako: 0.3.4
Tornado: Not Installed
timelib: Not Installed
dateutil: Not Installed

```

**Comment by tbaker57** [comment]
How about using onlyif/unless to make it idempotent ? e,g,
```
insert-options:
  file.replace:
    - name: /home/bmgraves/root/boot/grub/grub.conf
    - pattern: (kernel \/vmlinuz-.* quiet)(.*)
    - repl: '\1 {{ bootoptions }}'
    - unless: 'grep bootoptions /home/bmgraves/root/boot/grub/grub.conf'
```

cheers,
Tim
