### ISSUE TITLE
how to prevent removing minions (mines IP) on an HAproxy

### ISSUE THREAD

**Issue by nbari** [saltstack/salt#31141]
I am using mines to keep backends updated on an HAproxy, but for some unknown reasons, when the salt master can't see a minion and when running a ``salt-call state.highstate``  from the HAProxy, it could happen that since the maser it not available to reach the minions, the HAproxy conf becomes empty and therefore takes all the backens out.

How to prevent removing "unreachable" mines (IP's)  from the salt-master in order to avoid a services interruption.

Also wondering if there is a fast way to add new host to the mine group so that they can be added as a part of the backends.

thanks in advance.

**Comment by jfindlay** [comment]
@nbari, what version of salt are you running?  Is there any network complexity between the master and minions that might cause connectivity issues for salt?

**Comment by nbari** [comment]
Hi, I am using:

 ```
Salt Version:
           Salt: 2015.8.5
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.11 (default, Jan 31 2016, 01:17:27)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: amd64
        release: 10.2-STABLE
```

For now via cron every 5 min I am calling: ``salt-call state.highstate -l quiet``

Master and minions all running within a same VPC
