### ISSUE TITLE
salt.states.archive.extacted displays incorrect message:

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#31174]
```yaml
          ID: common.accounts.user::sjorge
    Function: archive.extracted
        Name: /home/sjorge
      Result: True
     Comment: ['salt://common/accounts/files/profile_sjorge.tar.gz', 'salt://common/accounts/files/profile_default.tar.gz'] extracted in /home/sjorge/
     Started: 19:43:27.860772
    Duration: 977.941 ms
     Changes:
              ----------
              directories_created:
                  - /home/sjorge/
                  - /home/sjorge/.vimrc
              extracted_files:
                  - .vimrc
                  - .zshrc
                  - .zlocal
```

```yaml
common.accounts.user::sjorge
  archive.extracted:
    - name: /home/{{ login }}
    - if_missing: /home/{{ login }}/.vimrc
    - archive_format: tar
    - source:
        - salt://common/accounts/files/profile_{{ login }}.tar.gz
        - salt://common/accounts/files/profile_default.tar.gz
    - user: {{ login }}
    - group: {{ salt.pillar.get('common:accounts:users:' ~ login ~ ':primary_group', 'user') }}
```

```bash
[root@cronos /srv/salt/states/common/accounts/files]# tar tvf profile_default.tar.gz
-rw-r--r-- sjorge/user    1354 2016-02-12 19:33 .vimrc
-rw-r--r-- sjorge/user   25382 2016-02-12 19:33 .zshrc
-rw-r--r-- sjorge/user      11 2016-02-12 19:34 .zlocal
```
It correctly checks if /home/sjorge/.vimrc is present or not. But it's not a directory, so the message that it was created as a directory is just wrong.

I'll start squashing some of my issues once I have finished my saltstack rollout, no ETA on that.
