### ISSUE TITLE
Managing salt-minion through formula starts 2 daemons

### ISSUE THREAD

**Issue by sc250024** [saltstack/salt#31202]
Greetings,

This might be a configuration issue, but I believe managing the Salt minion config file, and thus service, results in having two `salt-minion` daemons running, and causes problems when trying to run jobs. The error I believe sources from using the init.d script (and not `service salt-minion start`) to start the salt-minion server. I am running the latest version of Ubuntu 14.04 throughout, and the latest versions of `salt-master` and `salt-minion` found in the official Ubuntu repository.

How to replicate:
- **Start with a machine already connected to a Salt master with `salt-minion` stopped. Start it with `/etc/init.d/salt-minion start`:**

```
[root@my-minion]: ~ # /etc/init.d/salt-minion start
 * Starting salt minion control daemon salt-minion                                                                                                                                [ OK ]
[root@my-minion]: ~ # /etc/init.d/salt-minion status
 * salt-minion is running
[root@my-minion]: ~ # ps -ef | grep -i salt-minion
root      5610     1  6 15:06 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion -d
```
- **Create this test formula on your Salt master, and ensure that your minion node associates with that formula in your `top.sls` file.**

```
{% set package_state = 'installed' %} # Set to 'purged' to remove the package
salt_minion_pkg:
  pkg.{{ package_state }}:
    - pkgs:
      - salt-minion

salt_minion_service:
  service.running:
    - name: salt-minion
    - enable: True
    - watch:
      - pkg: salt_minion_pkg
      - file: salt_minion_file

salt_minion_file:
  file.managed:
    - name: '/etc/salt/minion'
    - source: salt://salt_minion_formula/files/etc/salt/minion
    - user: root
    - group: root
    - mode: 0640
    - template: jinja
```
- **From the Salt master, run `salt my-minion state.highstate`. Notice that the result sees a change in the service and the output (if you have color enabled) is the pale blue indicating that change.**

```
----------
          ID: salt_minion_service
    Function: service.running
        Name: salt-minion
      Result: True
     Comment: Service salt-minion is already enabled, and is running
     Started: 15:15:26.515778
    Duration: 96.605 ms
     Changes:
              ----------
              salt-minion:
                  True
```
- **On the Salt minion, get a new process list. Notice the two new daemons running:**

```
[root@my-minion]: ~ # ps -ef | grep salt-minion
root      5610     1  0 15:06 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion -d
root      6168     1  0 15:15 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
root      6187  6168  0 15:15 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
```
- **Run a `test.ping` on the Salt master to verify the problem.**

```
[root@my-master]: ~ # salt my-minion test.ping
my-minion:
    True
my-minion:
    True
```
- **Having two minions running sometimes results in the following error:**

```
[root@my-master]: ~ # salt my-minion state.highstate
my-minion:
    Data failed to compile:
----------
    The function "state.highstate" is running as PID 3922 and was started at 2016, Feb 13 14:55:49.985050 with jid 20160213145549985050
ERROR: Minions returned with non-zero exit code
```

Again, not sure if this is my configuration, but wanted to raise the issue either way. Below is version information:

```
[root@my-master]: ~ # salt --versions-report
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Ubuntu 14.04 trusty
```

...and the Minion:

```
[root@my-minion]: ~ # salt-minion --versions-report
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Ubuntu 14.04 trusty
```
