### ISSUE TITLE
pkg.installed documentation not consistent with implementation

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#31216]
The documentation for pkg.installed says:

> version (str) --
> Install a specific version of a package. This option is ignored if either "pkgs" or "sources" is used.

I'm running 2015.8.5 on CentOS and the version parameter is not ignored if I use 'pkgs' like this in my formula:
```
common_packages:
  pkg.installed:
    - pkgs:
      - unzip
      - dos2unix
      - salt-minion: 2015.8.5-1.el6
```

Here's the log:
```
 ID: common_packages
    Function: pkg.installed
      Result: True
     Comment: 3 targeted packages were installed/updated. The following packages were already installed: salt-minion=2015.8.5-1.el6
     Started: 11:52:51.306751
    Duration: 27051.788 ms
     Changes:
              ----------
              dos2unix:
                  ----------
                  new:
                      3.1-37.el6
                  old:
              unzip:
                  ----------
                  new:
                      6.0-2.el6_6
                  old:
```
I suspect the documentation needs to be updated.
