### ISSUE TITLE
state.apply error (several environments): No matching sls found for 'state' in env 'base'

### ISSUE THREAD

**Issue by mallniya** [saltstack/salt#31220]
Hello, error reveal itself under following conditions (I use several environments):

``` yaml
# salt --version
salt 2015.8.3 (Beryllium)
# sudo salt-run fileserver.envs
- ivanov
- production
- base
- usermodel
- prod
- stage
# cat /usr/local/etc/salt/master
...
file_roots:
  base:
    - /usr/local/etc/salt/states/base
  production:
    - /usr/local/etc/salt/states/production
    - /usr/local/etc/salt/states/base
  usermodel:
    - /usr/local/etc/salt/states/usermodel
    - /usr/local/etc/salt/states/base
  ivanov:
    - /usr/local/etc/salt/ivanov/states
  stage:
    - /usr/local/etc/salt/stage/states
  prod:
    - /usr/local/etc/salt/prod/states
...
```

If state.apply is running with "env=usermodel" option -- all works as expected:
`sudo salt statlab100.rambler.ru state.apply packages env=usermodel`
But removing "env=usermodel" option leading to the following error:

```
loader.profile.ru:
    Data failed to compile:
----------
    No matching sls found for 'packages' in env 
```

Is it a bug, or there is something I missed?
