### ISSUE TITLE
pkgrepo.managed fails on Fedora 23

### ISSUE THREAD

**Issue by toanju** [saltstack/salt#31240]
adding a new repository using pkgrepo.managed on a salt minion (2015.5.9-2.fc23) fails with this error:

```
        Comment: Failed to configure repo 'toanju-rofl-common': No suitable yum config file found in: ('/etc/yum/yum.conf', '/etc/yum.conf')
```

example repo:

```
toanju-rofl-common:
  pkgrepo.managed:
    - humanname: Copr repo for rofl-common owned by toanju
    - baseurl: https://copr-be.cloud.fedoraproject.org/results/toanju/rofl-common/fedora-$releasever-$basearch/
    - gpgcheck: 0
    - enabled: 1
```

a workaround is using `dnf install yum`.

maybe setting basedir would work too, but i have not tested this, yet.
