### ISSUE TITLE
Using file.managed and file.append in one formula

### ISSUE THREAD

**Issue by mallniya** [saltstack/salt#31247]
Hello, my salt installation:

```
# salt --version
salt 2015.8.3 (Beryllium)
```

and I wonder why just as described [here](http://stevebennett.me/2014/02/17/one-week-of-salt-frustrations-and-reflections/) file.managed and file.append must be used as two separate formulas?
I mean instead that:

```
/var/log/salt/buildlog.html:
 file.managed:
 - source: salt://initlog.html 
 file.append:
 - text: Commencing build...
```

It's necessary use this:

```
/var/log/salt/buildlog.html:
 file.managed:
 - source: salt://initlog.html 

append_to_that_file:
 file.append:
 - name: /var/log/salt/buildlog.html
 - text: Commencing build...
```

In my case first option doesn't do anything, not even output an error. Second option works, but inability to do things in one formula bothers me. Please explain.

**Comment by jfindlay** [comment]
@mallniya, thanks for filing the issue.  The blog post you linked is very interesting, but the basic idea here is a duplicate of #29142.

**Comment by mallniya** [comment]
@jfindlay, thanks for clarification. Somehow it bothers me, that it can look like:
```
/var/log/salt/buildlog.html:
 file:
    managed:
      - source: salt://initlog.html 
     append:
      - text: Commencing build...
```
And there will be no contradiction. But, as I am not a programmer, I guess #29142 will solve it.

One more note: working form of formula will rewrite target file every time highstate is running, which is either unnecessary and potentially harmful for services, that watch this actually unchanged, but as a fact modified file. Is #29142 take this into account?

**Comment by jfindlay** [comment]
@mallniya, yes it is a peculiarity of the [highstate data format](https://docs.saltstack.com/en/latest/ref/states/highstate.html).  I am unclear about your question.  Is it possible for you to post a more specific example?

**Comment by mallniya** [comment]
Example was in the first message:
```
/var/log/salt/buildlog.html:
 file.managed:
 - source: salt://initlog.html 

append_to_that_file:
 file.append:
 - name: /var/log/salt/buildlog.html
 - text: Commencing build...
```
No matter buildlog.html will be changed as a result, intermediate actions will be: populate buildlog.html with `source` requisite of `file.managed` (and delete whatever appendix is in this file), populate it with `text` requisite of `file.append` (adding deleted appendix). This will result as assumption of buildlog.html was changed anyway. Hence services, that watch buildlog.html, will be restarted. Demand behaviour is not to assume, that if file was changed in between, will be changed after applying all requisites. Again, `require` and `require_in` requisites doesn't help.

About given link: strange, that 2 different requisites cannot be used in one formula (though, both starts with file.*):
```
/var/log/salt/buildlog.html:
  file.managed:
      - source: salt://initlog.html 
  file.append:
      - text: Commencing build...
```
This doesn't work (and there is no ID conflict).
But this works:
```
hive:
  pkg.installed:
      - refresh: true
  user.present:
    - fullname: Apache Hive user
    - shell: /usr/sbin/nologin
    - home: /nonexistent
    - uid: 9032
    - gid: 9032
    - require:
      - group: hive
  group.present:
    - gid: 9032
```
So if there are pkg.something and user.something requisites -- formula works, if file.something1 and file.something2 -- doesn't work. Maybe this can be eliminated?

**Comment by mallniya** [comment]
ping, @jfindlay

**Comment by UtahDave** [comment]
Hi @mallniya,

The reason the following example doesn't work is because Salt loads that yaml into a python data structure.  `file.managed` is a shortcut. Here's what your example would look like without using that shortcut:

```
/var/log/salt/buildlog.html:
  file:
    - managed:
    - source: salt://initlog.html 
  file:
    - append:
    - text: Commencing build...
```

Everything under `/var/log/salt/buildlog.html:` becomes a python dictionary. `file:` is a python dictionary key. Python dictionary keys must be unique, hence they must be unique in the yaml representation.

**Comment by mallniya** [comment]
Hey, @UtahDave!
Sounds pretty complete.
Sorry, but just can't get this out of my head. So, taking it to the end -- why logic doesn't look like this (as I mentioned at 20 feb):
```
/var/log/salt/buildlog.html:
  file:
    - managed:
      - source: salt://initlog.html 
    - append:
      - text: Commencing build...
```
All I want to express -- is that I believe saltstack could use no link to the same object in two different formulas -- in this case /var/log/salt/buildlog.html. It's more about not WHY I cannot use it my way, it's about why should it be the way it is and is it a reason to change it?

But, we're going off track here. All I want to know initially -- why file append do the modification anyway (again, as in the question I asked 20 feb)?

**Comment by boltronics** [comment]
I believe this ticket was closed incorrectly due to a misunderstanding. Please re-open!

As I understand it, @mallniya wants to take a file from somewhere (which presumably can change) and append text to the end of it. I'm also in a similar situation, and the bug this was marked a duplicate of is completely unrelated to that goal.

Here's a specific example: `/usr/share/wordpress/robots.txt` might be deployed as part of a package, which prevents various things from being accessed by spiders. But there might be an exception you need to add.

Because it's a package, you don't want to modify that directly. Doing so might prevent dpkg from updating robots.txt when changes are made in newer versions of the wordpress package, and you will surely want to incorporate those updates automatically. Sure, you could `watch` `- pkg: wordpress` for changes and try to handle such problems, but in general I feel it's a bad idea to modify things already managed through the package management system unless absolutely necessary anyway.

This the current option is to do something like:
```
Create /var/www/custom_robots.txt based on /usr/share/wordpress/robots.txt:
  file.copy:
    - name: /var/www/custom_robots.txt
    - source: /usr/share/wordpress/robots.txt
    - force: True
    - preserve: True
    - require:
      - pkg: wordpress
Append my exceptions to /var/www/custom_robots.txt:
  file.append:
    - name: /var/www/custom_robots.txt
    - text: |
        User-agent: Some agent
        Allow: /somedir
    - require:
      - file: Create /var/www/custom_robots.txt based on /usr/share/wordpress/robots.txt
```
(or `file.managed` could be used to pull in contents from somewhere instead of `file.copy`, it doesn't matter). Then the web server would be configured to alias /var/www/custom_robots.txt over the top of the existing robots.txt file so the original file remains completely unchanged.

The problem in doing this (and the point of this bug report) is that both blocks will always execute on every run, which is not what you want in a configuration management system. We want to describe a state, and we want feedback on if that state has changed and corrections were required. Without that, Salt isn't much better than just running a shell script. So we need a solution. This is why @mallniya was asking for a solution in one formula.

How to address this situation? My proposal would be to support the following syntax:
```
Create  /var/www/custom_robots.txt based on /usr/share/wordpress/robots.txt:
  file.append:
    - name: /var/www/custom_robots.txt
    - contents: /usr/share/wordpress/robots.txt
    - text: |
        User-agent: Some agent
        Allow: /somedir
    - require:
      - pkg: wordpress
Validate owner and permissions of /var/www/custom_robots.txt:
  file.managed:
    - name: /var/www/custom_robots.txt
    - user: root
    - group: www-data
    - mode: '0640'
    - require:
      - file: Create  /var/www/custom_robots.txt based on /usr/share/wordpress/robots.txt
```
In this proposal, the new `- contents:` key would point to another file.

How this would work internally would be for the file contents to be copied to a temporary file. Next, the value of `-text:` would be appended to the temporary file. At that point, if the temporary file differs to `/var/www/custom_robots.txt`, we move it and trigger the change output. Otherwise, we delete the temporary file and indicate that the state was unchanged in the output. This should be quite straightforward.

Bonus points for implementing `-preserve:` for the file.append state so the separate `Validate owner and permissions of /var/www/custom_robots.txt` block would no longer be necessary!

**Comment by boltronics** [comment]
I should have mentioned (for anyone currently stuck on this) that currently I would currently work around this limitation using some funky jinja2. eg.

```
{% set robots_orig = '/usr/share/wordpress/robots.txt' %}
Append my exceptions to /var/www/custom_robots.txt:
  file.append:
    - name: /var/www/custom_robots.txt
    - text: |
        User-agent: Some agent
        Allow: /somedir
{% if salt['cmd.run']('test $(diff -q <(md5sum "' + robots_orig + '" | cut -d ' ' -f 1) <(head -n $(wc -l "' + robots_orig + '") "' + robots_orig + '" | md5sum - | cut -d ' ' -f 1) && echo 0) -ne 0') %}
    - require:
      - file: Create /var/www/custom_robots.txt based on /usr/share/wordpress/robots.txt
Create /var/www/custom_robots.txt based on /usr/share/wordpress/robots.txt:
  file.copy:
    - name: /var/www/custom_robots.txt
    - source: /usr/share/wordpress/robots.txt
    - force: True
    - preserve: True
    - require:
      - pkg: wordpress
{% endif %}
```
That's completely untested... but you get the idea. It works (by avoiding the `Create /var/www/custom_robots.txt based on /usr/share/wordpress/robots.txt` block from being pulled in when it's not required, but it's still misleading since more is happening than the output shows. It's also obviously ugly as heck! But this sort of approach does hide invalid change notifications...
