### ISSUE TITLE
network.routes doesn't handle multiple 'routes'

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#31267]
when the network state will be applied on the system only the last '**routes**' entries will be applied:

```
routes:
  network.routes:
    - name: eth0
    - routes:
      - name: internal networks 10
        ipaddr: 1.3.1.0
        netmask: 255.255.255.0
        gateway: {{ route_mgmt }}
      - name: MGMT_network 12.10
        ipaddr: 12.10.0.0
        netmask: 255.255.0.0
        gateway: {{ route_mgmt }}
    - name: eth1
    - routes:
      - name: web1
        ipaddr: 1.4.3.1
        netmask: 255.255.255.255
        gateway: {{ route_primary }}
      - name: web2
        ipaddr: 1.4.3.2
        netmask: 255.255.255.255
        gateway: {{ route_primary }}
      - name: ftp
        ipaddr: 1.4.3.7
        netmask: 255.255.255.255
        gateway: {{ route_primary }}
```

the eth0 routes won't be inserted. 
client CentOS 6.7
salt-2015.8.5-1.el6.noarch

This is critical issue! It breaks the system network connection.
