### ISSUE TITLE
Salt in Docker container cannot run dmidecode

### ISSUE THREAD

**Issue by fredrikaverpil** [saltstack/salt#31266]
When running Salt in a Docker container, I get:

    salt | [WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.

When logged into the salt master running in the container, `dmidecode` returns the following:

    [root@salt /]# dmidecode
    # dmidecode 2.12-dmifs
    /dev/mem: No such file or directory

The container is running CentOS 7. Dockerfile [here](https://github.com/fredrikaverpil/saltstack-docker/blob/master/Dockerfile) and docker-compose.yml [here](https://github.com/fredrikaverpil/saltstack-docker/blob/master/docker-compose.yml).

**Comment by jfindlay** [comment]
@fredrikaverpil, thanks for reporting.  What user does the salt-minion run as?  Grain data is collected by the minion.

**Comment by fredrikaverpil** [comment]
The minions are Windows based, so I'm not sure exactly what user is running them... I've used the Windows installer för Salt 2015.8.5. I'm guessing it's running as some system service with admin rights?

This warning appears in the salt master even if I don't have any minion keys accepted. The salt master is being run by root.

**Comment by jfindlay** [comment]
That makes sense, do you also run a minion on the same system as your master?  I am not aware of the salt master collecting grain info, but I could be wrong.

**Comment by fredrikaverpil** [comment]
No, I am not running a minion on the salt-master. salt-master is running as root.

It seems to me, that the salt-master itself is invoking dmidecode.

**Comment by RichardLaing** [comment]
Hi there I have also run into this bug on the following Dockerfile.

https://github.com/saltstack-formulas/fail2ban-formula

**Comment by cachedout** [comment]
I'm confused about how this can be a Salt bug. We're attempting to run dmidecode and we can't due to an upstream limitation in dmidecode, so we're printing a warning saying that we'll have to fallback to other collection methods.

Can you elaborate on what you believe Salt should be doing here that it isn't?

**Comment by fredrikaverpil** [comment]
@cachedout ah, in that case, if it's not a Salt bug, we should close this issue. I reported it believing it could've been a Salt bug.

**Comment by cachedout** [comment]
@fredrikaverpil Sounds good. I think this is really an upstream bug and so I'll go ahead and close this. I appreciate you reporting it though. :]

**Comment by morsik** [comment]
Hi. I'm writing here cause my problem is related to this.

I understand that it's not Salt's bug that `dmidecode` fails, but… it's Salt but that it sets incorrectly grains.

I see:

```yaml
local: !!python/object/new:salt.utils.context.NamespacedDictWrapper
  dictitems:
    biosreleasedate: '/dev/mem: No such file or directory'
    biosversion: '/dev/mem: No such file or directory'
    manufacturer: '/dev/mem: No such file or directory'
    productname: '/dev/mem: No such file or directory'
    serialnumber: '/dev/mem: No such file or directory'
```

I don't find it correct information. It can be problem when some states or anything would rely on that. Those grains should not exists on such case in my opinion.
