### ISSUE TITLE
acl.present: TypeError on subsequent runs

### ISSUE THREAD

**Issue by svenehret** [saltstack/salt#31270]
# Description
I think I have hit a bug with setting linux file acls:

ACLs are set correctly (albeit a change is not reported), but subsequent runs throw a TypeError.

Example:
```salt
/tmp/testdir/:
  acl.present:
    - acl_type: user
    - acl_name: root
    - perms: r-x
```
When executed, this sets ACLs correctly. Note that no change is being reported (green text):
```salt
          ID: /tmp/testdir/
    Function: acl.present
      Result: True
     Comment: Permissions will be applied
     Started: 14:01:36.454709
    Duration: 71.794 ms
     Changes:   
```

When executed a second time, this error is thrown (red text):
```salt
          ID: /tmp/testdir/
    Function: acl.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/linux_acl.py", line 77, in present
                  if user[acl_name]['octal'] == sum([_octal.get(i, i) for i in perms]):
              TypeError: unsupported operand type(s) for +: 'int' and 'str'
     Started: 14:09:49.598612
    Duration: 37.613 ms
     Changes:   
```

# Versions
## Master
```salt
salt --versions-report
Salt Version:
           Salt: 2015.8.5
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3
```
## Minion
```salt
salt-minion --versions-report
Salt Version:
           Salt: 2015.8.5
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@svenehret, thanks for the report.

**Comment by timwsuqld** [comment]
I'm also hitting this. Any ideas what we need to do to fix it?

**Comment by jfindlay** [comment]
@timwsuqld, you can construct a state with `cmd.run` and call the shell utils directly.  Here is what I get when I run the state:
```sls
# cat /srv/salt/test.sls 
/tmp/testdir/:
  acl.present:
    - acl_type: user
    - acl_name: root
    - perms: r-x
```
```py
# salt jmoney-main state.apply test
jmoney-main:
----------
          ID: /tmp/testdir/
    Function: acl.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/root/salt/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/root/salt/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/root/salt/salt/states/linux_acl.py", line 68, in present
                  _current_perms = __current_perms[name]
              KeyError: '/tmp/testdir/'
     Started: 13:56:15.526489
    Duration: 19.233 ms
     Changes:   

Summary for jmoney-main
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
ERROR: Minions returned with non-zero exit code
```
```yaml
# salt --versions
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.4 
```
