### ISSUE TITLE
passing jinja/python dict with none value through the file.managed context argument converts python/jinja none into string "none"

### ISSUE THREAD

**Issue by abulkavs** [saltstack/salt#31295]
``` sls
{%- set foo={'bar': none} %}

{{foo.bar | default('should be none', True)}} # that will return 'should be none''

some_file:
  file.managed:
    ...
    - context:
    foo: {{foo}}
```

---

in some_file:

``` sls
{{foo.bar | default('should be none'', True)}} # returns 'none' instead of 'should be none'

```

**Comment by jfindlay** [comment]
@abulkavs, thanks for the report.  What version of salt are you using?

**Comment by abulkavs** [comment]
2015.8.1 (Beryllium)

**Comment by jfindlay** [comment]
@abulkavs, I get this when trying your example:
```console
# cat /srv/salt/test.sls
{%- set foo={'bar': none} %}

{{foo.bar | default('should be none', True)}} # that will return 'should be none''

some_file:
  file.managed:
    - name: /tmp/file
    - context:
    foo: {{foo}}
```
```yaml
# salt jmoney-main state.show_sls test
jmoney-main:
    - Rendering SLS test failed, render error: expected '<document start>', but found '<block mapping start>'
    -   in "<unicode string>", line 5, column 1:
    -     some_file:
    -     ^
    - Traceback (most recent call last):
    -   File "/root/salt/salt/state.py", line 2640, in render_state
    -     sls, rendered_sls=mods
    -   File "/root/salt/salt/template.py", line 95, in compile_template
    -     ret = render(input_data, saltenv, sls, **render_kwargs)
    -   File "/root/salt/salt/renderers/yaml.py", line 51, in render
    -     data = load(yaml_data, Loader=get_yaml_loader(argline))
    -   File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    -     return loader.get_single_data()
    -   File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    -     node = self.get_single_node()
    -   File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 39, in get_single_node
    -     if not self.check_event(StreamEndEvent):
    -   File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    -     self.current_event = self.state()
    -   File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 174, in parse_document_start
    -     self.peek_token().start_mark)
    - ParserError: expected '<document start>', but found '<block mapping start>'
    -   in "<unicode string>", line 5, column 1:
    -     some_file:
    -     ^
ERROR: Minions returned with non-zero exit code
```
```yaml
# salt --versions
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.3
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3
```

**Comment by abulkavs** [comment]
{{foo.bar | default('should be none', True)}} 

such jinja template evaluation definitely shouldn't be in sls file. I've put it there just to demonstrate that if that would be there then it is evaluated differently than in /tmp/file from file.managed "context". In sls file it's evaluated properly and "salt-minion -l debug" would show that even though it results in error during further yaml processing (what you've got). But when such jinja piece is moved into /tmp/file then none value literally becomes a "none" string.

Just comment it (#) in sls file and copy it into the /tmp/file. Then check whether evaluation is the same in both sls and /tmp/file. The bug is that it is not but should be

**Comment by alxwr** [comment]
This bug is still present in 2017.7.4:

```
# salt --versions-report
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Mar 26 2018, 19:36:33)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 11.1-RELEASE-p8
         system: FreeBSD
        version: Not Installed
```
