### ISSUE TITLE
Git Pillars lose HEAD reference over time

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#31293]
We have a salt master configured with several git pillar repos.  About once a day we start getting these errors:
```
Error occured fetching git_pillar remote 'staging git@github.com:myorg/saltstack-pillars.git': Reference 'HEAD' not found 
Exception caught while initializing git_pillar remote 'staging git@github.com:myorg/saltstack-pillars.git': tuple index out of range 
```

We resolve the issue each day by deleting /var/cache/salt/master/git_pillar

Looking into /var/cache/salt/master/git_pillar/c245a5b583965a1bc938b8104013601c/.git/  I see that HEAD is actually missing.  What would cause HEAD to be deleted randomly?

master config: (all other gitpillar settings are default)
```
ext_pillar:
  - git:
    - staging git@github.com:myorg/saltstack-pillars.git:
      - privkey: /root/.ssh/id_rsa2
      - pubkey: /root/.ssh/id_rsa2.pub
      - env: base
  - git:
    - master git@github.com:myorg/saltstack-pillars-serverconfig.git:
      - privkey: /root/.ssh/id_rsa3
      - pubkey: /root/.ssh/id_rsa3.pub
      - env: base
  - git:
    - master git@github.com:myorg/saltstack-primedirective.git:
      - privkey: /root/.ssh/id_rsa4
      - pubkey: /root/.ssh/id_rsa4.pub
      - env: base
      - root: pillars
  - git:
    - master git@github.com:myorg/saltstack-paths.git:
      - privkey: /root/.ssh/id_rsa5
      - pubkey: /root/.ssh/id_rsa5.pub
      - env: base
      - root: pillars
```

```
Salt Version:
           Salt: 2015.8.5
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.9 (unknown, Dec 17 2015, 01:08:55)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.1
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: 0.20.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
   python-gnupg: 0.3.7
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.1.13-19.30.amzn1.x86_64
```

The same error appears in https://github.com/saltstack/salt/issues/28298 which should be resolved in 2015.8.5, so I don't think they are the same issue.
