### ISSUE TITLE
file.line not keeping block chomping indentation after changes were made

### ISSUE THREAD

**Issue by plaurin84** [saltstack/salt#31298]
I use a simple file.line to ensure an indented line exists in an xml config ile:

```
sync_configuration:
  file.line:
    - name: /home/{{ user }}/{{ orientdb.version }}/{{ orientdb.config }}
    - content: |4+
            <user name="bob" password="xxx" resources="xxx"/>
    - mode: ensure
    - after: <users>
```

The initial run of highstate seems to works perfectly. The config file looks like this:

```
    <users>
        <user name="bob" password="xxx" resources="xxx"/> # Appened by file.line
        <user name="root" password="yyy" resources="yyy"/> # Appened by database server on first run
        <user name="root" password="zzz" resources="zzz"/> # Appened by database server on first run
    </users>
```

If I run highstate a second time, salt detects that changes were made to the file, which is expected behaviour, since the file was appened by starting the application (orientdb) later in the highstate (see comments in the code above).

But, as the changes are detected after that second highstate, salt removes indentation that was properly set the first time using block chomping, and now looks like this:

```
    <users>
    <user name="bob" password="xxx" resources="xxx"/> # Appened by file.line
        <user name="root" password="yyy" resources="yyy"/> # Appened by database server on first run
        <user name="root" password="zzz" resources="zzz"/> # Appened by database server on first run
    </users>
```

What happened to my indentation?
