### ISSUE TITLE
file.manage with s3 has intermittent failure - Can it support configurable retry amount?

### ISSUE THREAD

**Issue by hubez** [saltstack/salt#31291]
file.manage with an s3 source seems to have intermittent failure, and I would love to have a configurable retry amount (because a subsequent highstate succeeds). 

The frequency is about 1 every few high hundred calls where a single deploy across multiple machines that hits s3 hundreds of times.

The s3 provider seems to have a hard-coded timeout of 10s, and no retry. Is it possible to expose retry to be configurable somewhere?

Here's an example output, where the hash file fails to return. It is not limited to the hash file, it happens to the source_file too randomly.

State file:
```
   file.managed:
      - user: myuser
      - group: mygroup
      - mode: 644
      - source: s3://mybucket/myfile
      - source_hash: s3://mybucket/myfile.sha1
      - makedirs: True
      - dir_mode: 700
```

Output
```
        ID: /myfile
        Function: file.managed
         Result: False
         Comment: Unable to manage file: Could not fetch from s3://mybucket/myfile.sha1
```
