### ISSUE TITLE
rdp.enable cannot use "require"

### ISSUE THREAD

**Issue by fredrikaverpil** [saltstack/salt#31303]
I can't use `require` with `rdp.enable` in Salt 2015.8.5:

```yaml
# /srv/salt/windows/network/remote_desktop.sls
enable_rdp:
  module.run:
    - name: rdp.enable
    - require:
      - sls: windows.network.firewall
```

I get this error when running that state:

```
ws14gen02:
----------
          ID: enable_rdp
    Function: module.run
        Name: rdp.enable
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     sls: windows.network.firewall
     Started:
    Duration:
     Changes:

Summary for ws14gen02
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

I've tried switching out `windows.network.firewall` to other state files and none are working, and it seems `rdp.enable` simply does not support `require`. Could this really be so?
I'm using `require` all over the place, and this is the first time I see this behavior, where it simply won't work.

Here's (part of) my directory tree under `/srv/salt`:

```
windows
|-- network
|   |-- firewall.sls
|   |-- hostname.sls
|   |-- init.sls
|   |-- private.sls
|   `-- remote_desktop.sls
|-- python
|   |-- init.sls
|   |-- packages
|   |   |-- jinja2.sls
|   |   |-- paramiko.sls
|   |   |-- psycopg2.sls
|   |   |-- requests.sls
|   |   |-- sqlalchemy.sls
|   |   `-- wheel.sls
|   `-- packages_workstation.sls
```

The contents of `windows.network.firewall`:

```yaml
# /srv/salt/windows/network/firewall.sls
enable_ping_win10:
  cmd.run:
    - name: netsh advfirewall firewall set rule name="File and Printer Sharing (Echo Request - ICMPv4-In)" new enable=yes

open_ports_rdp:
  win_firewall.add_rule:
    - name: Remote Desktop
    - localport: 3389
    - protocol: tcp
    - action: allow
```
