### ISSUE TITLE
Error when trying to use extend in cloud provider conf

### ISSUE THREAD

**Issue by sunstick** [saltstack/salt#31304]
Hi,

I am trying to use the extend feature documented in https://docs.saltstack.com/en/develop/topics/cloud/config.html#extending-profiles-and-cloud-providers-configuration

My setup is that I have an `aws.conf` in /etc/salt/cloud.providers.d/ and it looks like the following

```
general-ec2:
  driver: ec2
  id: use-instance-role-credentials
  key: use-instance-role-credentials
  private_key: /etc/salt/salt_cloud_key
  keyname: salt_minion_key
  location: us-west-2

my-ec2:
  extends: general-ec2
  image: ami-86e605b5
```

However, when using this I got the following error
```
salt-cloud: error: The '-only-extendable-0' cloud provider entry in 'analytics-ec2' is trying to extend from 'aws-ec2' and no provider was specified. Not extending!
```

Any ideas what's going on here? What did I do wrong?

Thanks in advance for the help.
