### ISSUE TITLE
State git config_unset KeyError exception

### ISSUE THREAD

**Issue by tardypad** [saltstack/salt#31311]
I encounter an exception while using git.config_unset within a state

Here below is the description of what happens when trying to remove a simple value

On the minion, the git user's gitconfig contains

```
[push]
        default = matching
```

Salt template contains

```
user_git_remove_push_default:
  git.config_unset:
    - name: push.default
    - user: git
    - global: True
    - all: True
```

state apply test=True results in

```
      ID: user_git_remove_push_default
Function: git.config_unset
    Name: push.default
  Result: None
 Comment: 1 key(s) would have value(s) unset
 Started: 04:00:13.696517
Duration: 50.744 ms
 Changes:
         ----------
         push.default:
             - matching
```

actual state apply results in

```
      ID: user_git_remove_push_default
Function: git.config_unset
    Name: push.default
  Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
            File "/usr/lib/python2.7/site-packages/salt/state.py", line 1624, in call
              **cdata['kwargs'])
            File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1491, in wrapper
              return f(*args, **kwargs)
            File "/usr/lib/python2.7/site-packages/salt/states/git.py", line 1763, in config_unset
              unset = [x for x in pre[key_name] if x not in post[key_name]]
          KeyError: 'push.default'
 Started: 05:12:14.863225
Duration: 151.093 ms
 Changes:
```

and the value gets removed from the gitconfig

```
[push]
```

Here is the Salt / libraries / system versions used

```
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```
