### ISSUE TITLE
service.running must run twice to start disabled service in windows

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#31323]
Windows 2012R2
Salt 2015.8.5

`service.running` will not start a disabled service on first run. The service is enabled on the first run, but not started. The service starts successfully on the second run because it was enabled in the first run.

To replicate:
Disable and stop the Print Spooler service using the windows service manager `services.msc`.

Create a state file with the following:
```
Spooler:
  service.running:
    - enable: True
````

Apply the state to the minion. It will fail with the following:
```
          ID: Spooler
    Function: service.running
      Result: False
     Comment: Service Spooler has been enabled, and is dead
     Started: 18:14:08.646000
    Duration: 1438.0 ms
     Changes:
              ----------
              Spooler:
                  True
```

Apply the state again. It will succeed with the following:
```
          ID: Spooler
    Function: service.running
      Result: True
     Comment: Service Spooler is already enabled, and is running
     Started: 18:14:59.989000
    Duration: 3437.0 ms
     Changes:
              ----------
              Spooler:
                  True
```
