### ISSUE TITLE
Salt doesn't update file when pillar called

### ISSUE THREAD

**Issue by AcidRobot** [saltstack/salt#31331]
So, if I set a source to call pillar information eg:
```
krb5_conf:
  file.managed:
    - name: {{ auth.krb5 }}
    - source: {{ salt['pillar.get']('auth:lookup:config_krb5:tmpl') }}
    - force: True
```

it won't update the file on the server, it'll give this when running salt-call state.highstate
```
         ID: krb5_conf
    Function: file.managed
        Name: /etc/krb5.conf
      Result: True
     Comment: File /etc/krb5.conf exists with proper permissions. No changes made.
     Started: 15:44:33.260867
    Duration: 1.32 ms

```

after changing this to:
```
krb5_conf:
  file.managed:
    - name: {{ auth.krb5 }}
    - source: salt://auth/files/krb5.conf
    - force: True
```

does it work and update the file

```
ID: krb5_conf
    Function: file.managed
        Name: /etc/krb5.conf
      Result: True
     Comment: File /etc/krb5.conf updated
     Started: 15:47:32.366615
    Duration: 56.735 ms
     Changes:   
              ----------                                                                                                                                                                                                                                                       
              diff:
```

**Comment by jfindlay** [comment]
@AcidRobot, thanks for reporting.  What version of salt are you using?  Do you see anything suspicious in the master or minion debug log?  You can also try:
```sls
krb5_conf:
  file.managed:
    - name: {{ auth.krb5 }}
    - contents_pillar: auth:lookup:config_krb5:tmpl
    - force: True
```

**Comment by AcidRobot** [comment]
```
# salt-minion --version
salt-minion 2015.8.7 (Beryllium)
```
```
# salt-call state.highstate
----------
          ID: krb5_conf
    Function: file.managed
        Name: /etc/krb5.conf
      Result: False
     Comment: Unable to determine upstream hash of source file auth:lookup:config_krb5:tmpl
     Started: 14:43:56.468369
    Duration: 2.442 ms
     Changes:
```
