### ISSUE TITLE
timezone.system is not available for mac

### ISSUE THREAD

**Issue by dvcrn** [saltstack/salt#31345]
Executing with `salt-ssh`

State:

```
Asia/Tokyo:
  timezone.system:
    - utc: True
```

Error:

```
----------
          ID: Asia/Tokyo
    Function: timezone.system
      Result: False
     Comment: State 'timezone.system' was not found in SLS 'timezone'
              Reason: 'timezone.system' is not available.
     Started:
    Duration:
     Changes:
```

Salt version: 2015.8.5

Running this on a cluster with mostly debian machines, but also 1 mac. The debians work fine, the mac fails
