### ISSUE TITLE
Problem with salt-api (rest_cherrypy): token doesn't work

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#31349]
I'm having the following problem with salt-api:

Here is my forkflow:
1. Using curl to authenticate with user and password to receive a token - SUCCESS: I get the token
2. Using curl to place a job (using the token from step 1) - SUCCESS: I get the jid
3. Using curl to check jid status (using the token from step 1 and jid from step 2) - FAILURE: 401 Unauthorized

Here is the query that fails:
```
curl -ik https://infra01:8000/jobs/20160219123952193531 -H 'X-Auth-Token: a54d32db36beaad0720c8491a345d7c4d937d7c7'
```
Error message:
```
401 Unauthorized
No permission -- see authorization schemes
```
In salt master log there is a message:
```
Authentication failure of type "token" occurred for user jenkins.
```
This is weird as the job was placed with the same token.
Also, the user is resolved successfully by the token...

Here is how the auth configured:
```
root@infra01:~# cat /etc/salt/master.d/external_auth.conf 
external_auth:
  pam:
    jenkins:
      - .*
```
salt-api config:
```
root@infra01:~# cat /etc/salt/master.d/rest_cherrypy.conf 
rest_cherrypy:
  host: xxx.xxx.xxx.xxx
  port: 8000
  ssl_crt: /etc/salt/certs/certfile.crt
  ssl_key: /etc/salt/certs/keyfile.key
```
Salt version:
```
root@infra01:~# salt --versions
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-33-generic
         system: Ubuntu 14.04 trusty
 
```
