### ISSUE TITLE
osrelease_info broken for CentOS 7

### ISSUE THREAD

**Issue by cwicklein** [saltstack/salt#31365]
It looks like the osrelease* grains aren't being set on CentOS 7 with 2015.8.5 as they were with 2015.5.x.  The osrelease_info bits mostly fell out.

2015.5.x:

    os:
        CentOS
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        Core
    osfinger:
        CentOS Linux-7
    osfullname:
        CentOS Linux
    osmajorrelease:
        7
    osrelease:
        7.1.1503
    osrelease_info:
        - 7
        - 1
        - 1503

2015.8.5:

    os:
        CentOS
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        CentOS Linux 7 (Core)
    osfinger:
        CentOS Linux-7
    osfullname:
        CentOS Linux
    osmajorrelease:
        7
    osrelease:
        7
    osrelease_info:
        - 7

**Comment by jfindlay** [comment]
@cwicklein, thanks for reporting.

**Comment by jfindlay** [comment]
I can confirm this:

- 2015.5.9
  ```yaml
  os:
      CentOS
  os_family:
      RedHat
  osarch:
      x86_64
  oscodename:
      Core
  osfinger:
      CentOS Linux-7
  osfullname:
      CentOS Linux
  osmajorrelease:
      7
  osrelease:
      7.1.1503
  osrelease_info:
      - 7
      - 1
      - 1503
  ```

- 2015.8.7
  ```yaml
  os:
      CentOS
  os_family:
      RedHat
  osarch:
      x86_64
  oscodename:
      CentOS Linux 7 (Core)
  osfinger:
      CentOS Linux-7
  osfullname:
      CentOS Linux
  osmajorrelease:
      7
  osrelease:
      7
  osrelease_info:
      - 7
  ```
