### ISSUE TITLE
illumos/solaris/smartos display compacted hwaddrs

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#31369]
```
[root@test ~]# salt-call grains.get hwaddr_interfaces
```
```yaml
local:
    ----------
    net0:
        0:22:6:10:0:1
    net1:
        0:22:6:30:0:3
```

These should probably be padded with 0 if length of segment < 2

Not sure how far back this goes but at least develop and 2016.3 show it. I assume 2015.8 and older also.
