### ISSUE TITLE
salt-key returns error when not run as root

### ISSUE THREAD

**Issue by foundatron** [saltstack/salt#31362]
`salt-key` returns error when not run as root

I'm attempting to run as salt as unprivileged user described [here](https://docs.saltstack.com/en/latest/ref/configuration/nonroot.html). Regular `salt` commands run without problem, but running `salt-key` commands returns this error:

```
$ salt-key -L
CRITICAL: Salt configured to run as user "root" but unable to switch.
```

I'm running Centos 7 (using the most recent base Centos AMI on AWS). I experienced this with salt versions 2015.5.8 and 2015.8.7. I initially installed 2015.5.8 using the salt packages in EPEL, and then upgraded to 2015.8.7 using the package in the [repo.saltstack.com](https://docs.saltstack.com/en/latest/topics/installation/rhel.html) after first experiencing the issue.

I can see that the salt master daemon is running as the correct unprivileged user, and regular `salt` commands seemingly work, so it appears that salt is configured correctly

**Comment by jfindlay** [comment]
@foundatron, thanks for reporting.  Will you also post the master config you are using with any private info removed if necessary?

**Comment by foundatron** [comment]
Here you are:

```
user: salt
auto_accept: True
top_file_merging_strategy: same
fileserver_backend:
  - roots
file_roots:
  base:
    - /srv/base/saltstack/salt
pillar_roots:
  base:
    - /srv/base/saltstack/pillar
```

I also just found that someone [mentioned](https://groups.google.com/d/msg/salt-users/phuM1sNzLAE/V_dTU5wsCgAJ) something similar on the google group, but I didn't see any issues in this repo that looked related.
