### ISSUE TITLE
dockerng No such file or directory on initial run

### ISSUE THREAD

**Issue by strocknar** [saltstack/salt#31361]
I'm trying to get dockerng to pull an image and start a container, but it seems that dockerng cannot do anything if a state that also installs docker is run at the same time. However, running a another highstate pulls the image and starts the container correctly. Am I missing something?

-=# docker.sls #=-
```
docker-py-install:
    pip.installed:
        - name: docker-py

docker-repo:
    pkgrepo.managed:
        - humanname: docker-repo
        - baseurl: https://yum.dockerproject.org/repo/main/centos/7
        - gpgcheck: 1
        - gpgkey: https://yum.dockerproject.org/gpg

docker-package:
    pkg.installed:
        - name: docker-engine
        - fromrepo: docker-repo
        - require:
            - pkgrepo: docker-repo
            - pip: docker-py-install

docker-service:
    service.running:
        - name: docker
        - enable: True
        - require:
            - pkg: docker-package
            - group: docker-group
```
-=# ecs.sls #=-
```
ecs_image:
    dockerng.image_present:
        - name: "amazon/amazon-ecs-agent"
        - force: true

ecs_service:
    dockerng.running:
        - name: ecs-agent
        - image: amazon/amazon-ecs-agent:latest
        - restart_policy: always
        - environment:
            - ECS_LOGFILE: /log/ecs-agent.log
            - ECS_LOGLEVEL: info
            - ECS_DATADIR: /data
            - ECS_CLUSTER: {{ cluster }}
            - AWS_DEFAULT_REGION: us-east-1
            - ECS_DOCKER_GRAPHPATH: /run/docker
        - port_bindings:
            - 127.0.0.1:51678:51678
        - binds:
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - /var/log/ecs/:/log:rw
            - /var/lib/ecs/data:/data:rw
            - /sys/fs/cgroup:/sys/fs/cgroup:rw
            - /run/docker/execdriver/native:/run/docker/execdriver/native:rw
        - watch:
            - dockerng: ecs_image

```
-=# error #=-
```
State 'dockerng.image_present' was not found in SLS 'docker.ecs'
              Reason: 'dockerng' __virtual__ returned False: 'dockerng' __virtual__ returned False: Exception raised when processing __virtual__ function for dockerng. Module will not be loaded Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
```
-=# Salt version #=-
```
# salt --versions-report
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by gtmanfred** [comment]
You will need to run `reload_modules` after python-docker is installed.

https://docs.saltstack.com/en/latest/ref/states/#reloading-modules

**Comment by strocknar** [comment]
That did the trick! Many thanks. I have never run into an issue where I needed to reload the modules before.

**Comment by stuartnelson3** [comment]
I'm encountering a similar issue, but when I'm running against a salt-minion that's on a machine that has docker pre-installed. `reload_modules` does not have an effect:

docker.sls
```yaml
python-pip:
  pkg.installed

# https://github.com/saltstack-formulas/docker-formula/issues/49#issuecomment-168906752
sudo pip install --upgrade pip:
  cmd.run

docker-py:
  pip.installed:
    - name: docker-py >= 1.4.0
    - reload_modules: true
    - require:
      - pkg: python-pip

docker:
  service.running:
    - enable: True
    - reload: True

mysql:
  dockerng.running:
    - image: mysql
    - environment:
      - MYSQL_DATABASE: testdatabase
      - MYSQL_USER: testuser_rw
      - MYSQL_PASSWORD: testpassword
      - MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    - port_bindings: 3306:3306
    - restart_policy: always
    - binds: /data:/var/lib/mysql:rw
    - require:
      - service: docker
      - pip: docker-py
```

error
```
----------
          ID: mysql
    Function: dockerng.running
      Result: False
     Comment: State 'dockerng.running' was not found in SLS 'docker'
              Reason: 'dockerng' __virtual__ returned False: 'dockerng' __virtual__ returned False: Docker module could not get imported
     Started: 
    Duration: 
     Changes:
```

salt
```
vagrant@saltmaster:~$ sudo salt --versions-report
Salt Version:
           Salt: 2015.8.10
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-86-generic
         system: Ubuntu 14.04 trusty
```

The workaround at the moment is to restart the `salt-minion` daemon after `docker-py` is installed, and then `dockerng` is available in subsequent runs.

```yaml
salt-minion:
  pkg:
    - installed
    - name: salt-minion
  service.running:
    - enable: True
    - require:
      - pkg: salt-minion
      - service: docker
      - pip: docker-py
    - watch:
      - pip: docker-py
```
