### ISSUE TITLE
Unable to install jre8 from github repository

### ISSUE THREAD

**Issue by travispaul** [saltstack/salt#31408]
As instructed in the [jre8 package definition](https://github.com/saltstack/salt-winrepo-ng/blob/master/jre8.sls#L7), I have downloaded the jre-8u73-windows-x64.exe to `salt://win/repo-ng/jre8/` and executed `pkg.refresh_db`.  I can install other packages ([npp ](https://github.com/saltstack/salt-winrepo-ng/blob/master/npp.sls)for example) but not jre8.  

I receive the following error:

```
----------
          ID: jre8
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: jre8=8.0.730.2
     Started: 08:14:38.034000
    Duration: 189281.0 ms
     Changes:
              ----------
              _comment:
                  Registry not updated.
```

my init.sls:

``` YAML
jre8:
  pkg:
    - installed
```

pkg.available_version:

```
[root@salt salt]# salt MINION pkg.available_version jre8
MINION:
    8.0.730.2
```

version report:

```
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32
         system: CentOS 6.7 Final
```

Minion is 2015.8.5

**Comment by jfindlay** [comment]
@TravisPaul, thanks for reporting.  @thebigbear, do you have any ideas on this one?

**Comment by TheBigBear** [comment]
@jfindlay no, I don't. @TravisPaul  what happens if you do an explicit 

```'salt 'your-minion-id' pkg.install jre8'```, 

instead of doing it via a state? Just trying to narrow it down.

**Comment by TravisPaul** [comment]
@TheBigBear I get the same results with ```salt MINION pkg.install jre8``` and ```salt MINION pkg.install jre8 version=8.0.730.2```

```YAML
windev1.weblinkid.com:
    ----------
    _comment:
        Registry not updated.
```
