### ISSUE TITLE
salt.states.grains.list_present adds duplicates names

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#31427]
Hi,

I noticed that using the 'grains' state multiple times results in duplicate list items. One would expect that the grains state immediately updates the roles grains after modifying it.

For example this state

```
# set roles
roles-nginx:
  grains.list_present:
    - name: roles
    - value:
      - webserver
      - webserver-nginx
    - require:
      - service: nginx-service

roles-nginx-php-fpm:
  grains.list_present:
    - name: roles
    - value:
      - php
      - php-fpm
      - webserver
      - webserver-nginx
      - webserver-nginx-php-fpm
```

yields this result

```
zsh 386 # salt minion grains.item roles
minion:
    ----------
    roles:
        - webserver
        - webserver-nginx
        - php
        - php-fpm
        - webserver
        - webserver-nginx
        - webserver-nginx-php-fpm
```

Is this a bug or a feature? It feels wrong to force a grain update in the state file?

**Comment by jfindlay** [comment]
@githubcdr, thanks for reporting.  What version of salt are you using?

**Comment by githubcdr** [comment]
2015.8.7

**Comment by jfindlay** [comment]
@githubcdr, I get the following results on 2015.8.3 and 2015.8.7.

```yaml
jmoney-main ~ master # cat /srv/salt/test.sls
roles:
  grains.list_present:
    - name: roles
    - value:
      - elliptic
      - parabolic
      - hyperbolic

additional-roles:
  grains.list_present:
    - name: roles
    - value:
      - hyperbolic
      - diabolic
```
```yaml
jmoney-main ~ master # salt jmoney-main state.show_sls test
jmoney-main:
    ----------
    additional-roles:
        ----------
        __env__:
            base
        __sls__:
            test
        grains:
            |_
              ----------
              name:
                  roles
            |_
              ----------
              value:
                  - hyperbolic
                  - diabolic
            - list_present
            |_
              ----------
              order:
                  10001
    roles:
        ----------
        __env__:
            base
        __sls__:
            test
        grains:
            |_
              ----------
              name:
                  roles
            |_
              ----------
              value:
                  - elliptic
                  - parabolic
                  - hyperbolic
            - list_present
            |_
              ----------
              order:
                  10000
```
```yaml
jmoney-main ~ master # salt jmoney-main state.apply test
jmoney-main:
----------
          ID: roles
    Function: grains.list_present
      Result: True
     Comment: Append value ['elliptic', 'parabolic', 'hyperbolic'] to grain roles
     Started: 12:20:47.135999
    Duration: 200.115 ms
     Changes:
              ----------
              new:
                  ----------
                  roles:
                      - elliptic
                      - parabolic
                      - hyperbolic
                      - hyperbolic
                      - diabolic
----------
          ID: additional-roles
    Function: grains.list_present
        Name: roles
      Result: True
     Comment: Append value ['hyperbolic', 'diabolic'] to grain roles
     Started: 12:20:47.336386
    Duration: 83.804 ms
     Changes:
              ----------
              new:
                  ----------
                  roles:
                      - elliptic
                      - parabolic
                      - hyperbolic
                      - hyperbolic
                      - diabolic

Summary for jmoney-main
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time: 283.919 ms
jmoney-main ~ master # salt jmoney-main grains.item roles
jmoney-main:
    ----------
    roles:
        - elliptic
        - parabolic
        - hyperbolic
        - hyperbolic
        - diabolic

```

**Comment by cachedout** [comment]
@githubcdr Please give #31471 a try.

**Comment by githubcdr** [comment]
I will as soon as I know how :)

**Comment by jfindlay** [comment]
@githubcdr, this was committed into the 2015.8 branch, so if you checkout the head of that branch or any later branch (2016.3 or develop), the fix will be included.  If you have salt cloud configured, you can try `curl -L https://bootstrap.saltstack.com | sudo sh -s -- git 2015.8` to provision salt VMs with the latest version of the 2015.8 branch, or you can wait for the next release on that branch.

**Comment by githubcdr** [comment]
@jfindlay thanks for the feedback and the salt-cloud suggestion, that didn't cross my mind :)

Installed via salt-cloud

script: bootstrap-salt
script_args: git v2015.8

```
testgit2:
    Salt Version:
               Salt: 2015.8.0

    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
           pycrypto: 2.6.1

    System Versions:
               dist: centos 7.1.1503 Core
            machine: x86_64
            release: 3.10.0-229.20.1.el7.x86_64
             system: CentOS Linux 7.1.1503 Core
```

It seems this issue is still present as you can see below.

```
    grains_|-roles-nginx-php-fpm_|-roles_|-list_present:
        ----------
        __run_num__:
            38
        changes:
            ----------
            new:
                ----------
                roles:
                    - webserver
                    - webserver-nginx
                    - php
                    - php-fpm
                    - webserver
                    - webserver-nginx
                    - webserver-nginx-php-fpm
        comment:
            Append value ['php', 'php-fpm', 'webserver', 'webserver-nginx', 'webserver-nginx-php-fpm'] to grain roles
        duration:
            160.16
        name:
            roles
        result:
            True
        start_time:
            14:12:26.157217
    grains_|-roles-nginx_|-roles_|-list_present:
        ----------
        __run_num__:
            27
        changes:
            ----------
            new:
                ----------
                roles:
                    - webserver
                    - webserver-nginx
                    - php
                    - php-fpm
                    - webserver
                    - webserver-nginx
                    - webserver-nginx-php-fpm
        comment:
            Append value ['webserver', 'webserver-nginx'] to grain roles
        duration:
            314.479
        name:
            roles
        result:
            True
        start_time:
            14:12:22.959170
```

I got a feeling that the grains are not properly updated after setting, which results in duplicates.

Please let me know if I can help any further.

**Comment by jfindlay** [comment]
@githubcdr, it seems that you've checkout `v2015.8` goes to  `v2015.8.0`.  What happens when you install 74c3053c9134d9168ca2509fdc4cad626a9bb351, `script_args: git 74c3053c9134d9168ca2509fdc4cad626a9bb351`?

**Comment by githubcdr** [comment]
Hi @jfindlay, just tried with this releasem, the results are the same unfortunately.

```
 test.versions
testgit:
    Salt Version:
               Salt: 2015.8.4-550-g74c3053

    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist: centos 7.1.1503 Core
            machine: x86_64
            release: 3.10.0-229.20.1.el7.x86_64
             system: CentOS Linux 7.1.1503 Core
```
