### ISSUE TITLE
Salt Mine memory leak

### ISSUE THREAD

**Issue by johje349** [saltstack/salt#31454]
I have a test state which looks like this:

```sls
{% for host, ip in salt['mine.get']('*', 'network.ip_addrs').iteritems() %} 
test-{{ host }}: 
  cmd.run: 
    - name: "echo {{ host }}" 
{% endfor %}
```

The master has 36 minions. Each time I run the state, memory usage on the master increases with about 100M.

```
# free | grep Mem 
Mem: 4048268 2348116 1700152 396 38760 52368

# salt '*' state.apply test

# free | grep Mem
Mem: 4048268 2438388 1609880 396 38996 52816
```

Running the state enough times the memory gets full and everything stops working.
```
root@asx-salt:~/asx-salt/salt# salt '*' state.apply test 
Segmentation fault (core dumped)
```

**Comment by johje349** [comment]
Salt version is 2015.8.7 running on Ubuntu 14.04.3. 
Number of worker threads is set to 64.

**Comment by jfindlay** [comment]
@johje349, thanks for reporting.  I have tried to reproduce this with a single minion without success.  I will try more minions later.
```sls
jmoney-main ~ master # cat /etc/salt/minion
master: localhost
log_fmt_console: '%(colorlevel)s %(colormsg)s'

mine_functions:
  test.fib:
    - 19
mine_interval: 3
```
```sls
jmoney-main ~ master # cat /srv/salt/test.sls
{% for host, ip in salt['mine.get']('*', 'test.fib').iteritems() %}
test-{{ host }}:
  cmd.run:
    - name: "echo {{ host }}"
{% endfor %}
```
```yaml
jmoney-main ~ master # for i in {1..11} ; do salt jmoney-main state.apply test &> /dev/null ; free -m ; done
             total       used       free     shared    buffers     cached
Mem:          2005       1671        333         40        190        999
-/+ buffers/cache:        480       1524
Swap:            0          0          0
             total       used       free     shared    buffers     cached
Mem:          2005       1671        333         40        190        999
-/+ buffers/cache:        481       1523
Swap:            0          0          0
             total       used       free     shared    buffers     cached
Mem:          2005       1672        332         40        190        999
-/+ buffers/cache:        481       1523
Swap:            0          0          0
             total       used       free     shared    buffers     cached
Mem:          2005       1672        332         40        190        999
-/+ buffers/cache:        482       1522
Swap:            0          0          0
             total       used       free     shared    buffers     cached
Mem:          2005       1672        332         40        190       1000
-/+ buffers/cache:        482       1522
Swap:            0          0          0
             total       used       free     shared    buffers     cached
Mem:          2005       1672        332         40        190       1000
-/+ buffers/cache:        482       1522
Swap:            0          0          0
             total       used       free     shared    buffers     cached
Mem:          2005       1673        331         40        190       1000
-/+ buffers/cache:        482       1522
Swap:            0          0          0
             total       used       free     shared    buffers     cached
Mem:          2005       1673        331         40        190       1000
-/+ buffers/cache:        482       1522
Swap:            0          0          0
             total       used       free     shared    buffers     cached
Mem:          2005       1673        331         40        190       1000
-/+ buffers/cache:        482       1522
Swap:            0          0          0
             total       used       free     shared    buffers     cached
Mem:          2005       1672        332         40        190       1000
-/+ buffers/cache:        482       1522
Swap:            0          0          0
             total       used       free     shared    buffers     cached
Mem:          2005       1673        331         40        190       1000
-/+ buffers/cache:        482       1522
Swap:            0          0          0
```
```yaml
jmoney-main ~ master # salt --versions
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.3
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3
```
