### ISSUE TITLE
dockerng failed on inspection of lxc_conf parameter

### ISSUE THREAD

**Issue by mkuchin** [saltstack/salt#31451]
dockerng.running state started to fail after upgrading to salt 2016.3.0rc1

state file:
```
jenkins:
  dockerng.running:
    - image: jenkins
    - user: 1000
    - binds:
      - jenkins:/var/jenkins_home
    - port_bindings:
      - 8080:8080
    - watch:
      - dockerng: jenkins:latest
```
I'm getting error:
```
----------
          ID: jenkins
    Function: dockerng.running
      Result: False
     Comment: Uncaught exception "Unable to compare configuration for the 'lxc_conf' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. See minion log for exception info.
     Started: 11:01:58.067394
    Duration: 62.514 ms
     Changes:   
```
And minion logs have following stacktrace:
```
2016-02-24 06:10:14,822 [salt.loaded.int.states.dockerng][ERROR   ][24489] Uncaught exception "Unable to compare configuration for the 'lxc_conf' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. Exception info follows:
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 1588, in running
    defaults_from_image)
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 168, in _compare
    _api_mismatch(item)
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 99, in _api_mismatch
    'be due to a change in the Docker API'.format(param)

2016-02-24 06:10:14,822 [salt.state       ][ERROR   ][24489] Uncaught exception "Unable to compare configuration for the 'lxc_conf' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. See minion log for exception info.
```

`docker inspect jenkins`, HostConfig section:

```
"HostConfig": {
            "Binds": [
                "jenkins:/var/jenkins_home:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8080/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8080"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "KernelMemory": 0,
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null
        },
```

Software versions: 

```
Salt Version:
           Salt: 2016.3.0rc1-42-g3b3106c
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-27-generic
         system: Ubuntu 14.04 trusty
```

`Docker version 1.10.2, build c3959b1`

It seems that lxc support had been removed in docker v 1.10: https://github.com/docker/docker/pull/17700

Commenting following lines in `modules/dockerng.py` solves the problem:
 ```
 'lxc_conf': {
        'validator': 'dict',
        'path': 'HostConfig:LxcConf',
        'default': None,
    },
```
