### ISSUE TITLE
git_pillar_provider: pygit2 in masterless mode always returns the error: remote ref does not exist

### ISSUE THREAD

**Issue by thekoehl** [saltstack/salt#31502]
### Expected Behavior

Git Pillars would pull in as expected in masterless mode
### Actual Behavior

When I run:

```
sudo salt-call --local state.highstate -l debug --force-color
```

I receive the errors found in the log snippet below.  Given my conf file no matter what I seem to do I cannot pull down the repository.  If I look in `/var/cache/salt/minion/git_pillars/.git/refs` It appears I am missing the remotes directory.

Whats interesting is the gitfs formulas pull in just fine and if I use the pillar repo strings as gitfs_remotes they will pull in as formulas perfectly fine.  I read in the docs that gitfs and git_pillar were utilizing pygit2 differently, so maybe there is an issue there.
### Steps to Reproduce Issue

/etc/salt/minion.d/local.conf:

```
file_client: local

fileserver_backend:
  - roots
  - git

file_roots:
  base:
    - /vagrant/salt

pillar_roots:
  base:
    - /vagrant/salt/pillars

gitfs_provider: pygit2
gitfs_ssl_verify: False
gitfs_base: master
gitfs_pubkey: /home/vagrant/.ssh/id_rsa.pub
gitfs_privkey: /home/vagrant/.ssh/id_rsa
gitfs_remotes:
  - git@domain.com:reponame-formula1.git
  - git@domain.com:reponame-formula2.git

git_pillar_provider: pygit2
git_pillar_ssl_verify: False
git_pillar_insecure_auth: True
git_pillar_pubkey: /home/vagrant/.ssh/id_rsa.pub
git_pillar_privkey: /home/vagrant/.ssh/id_rsa
ext_pillar:
  - git:
    - master git@domain.com:reponame-pillar1.git
    - master git@domain.com:reponame-pillar2.git
```
### Versions Report

*\* Provided by running `salt --versions-report`**

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: 0.23.4
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.3
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-76-generic
         system: Ubuntu 14.04 trusty
```
### Relevant Logs, Configs, or States

*\* If not already provided above, please post any additional
   information that can help us reproduce your issue such as
   commands run with `-l debug`. Be sure to remove any
   sensitive information. **

```
[DEBUG   ] LazyLoaded git.ext_pillar
[ERROR   ] Failed to checkout master from git_pillar remote 'git@domain.com:salt/reponame-pillar1.git': remote ref does not exist
[ERROR   ] Failed to checkout master from git_pillar remote 'git@domain.com:salt/reponame-pillar2.git': remote ref does not exist
[CRITICAL] Pillar render error: Specified SLS 'pillar1' in environment 'base' is not available on the salt master
[CRITICAL] Pillar render error: Specified SLS 'pillar2' in environment 'base' is not available on the salt master
```
