### ISSUE TITLE
KeyError: 'retcode' in status.master

### ISSUE THREAD

**Issue by onorua** [saltstack/salt#31526]
### Expected Behavior
No errors in logs about status.master

### Actual Behavior
I'm receiving a lot of errors like:
```
Feb 27 15:16:58 ip-172-16-252-20 salt-minion[25364]: [ERROR   ] Unhandled exception running status.master
Feb 27 15:16:58 ip-172-16-252-20 salt-minion[25364]: Traceback (most recent call last):
Feb 27 15:16:58 ip-172-16-252-20 salt-minion[25364]: File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 703, in handle_func
Feb 27 15:16:58 ip-172-16-252-20 salt-minion[25364]: ret['retcode'] = self.functions.pack['__context__']['retcode']
Feb 27 15:16:58 ip-172-16-252-20 salt-minion[25364]: KeyError: 'retcode'
```

### Steps to Reproduce Issue
Have several master servers, and configure minion with following config:
```
master_alive_interval: 30
master_type: failover
master_shuffle: False
random_master: False
retry_dns: 0

master:
  - 172.16.252.10
  - 172.16.252.11
  - 172.16.252.12
```
As a result you will get `/etc/salt/minion.d/_schedule.conf` file with following contents
```
schedule:
  __master_alive:
    function: status.master
    jid_include: true
    kwargs: {connected: true, master: 172.16.252.10}
    maxrunning: 1
    seconds: 30
  __mine_interval: {function: mine.update, jid_include: true, maxrunning: 2, minutes: 60}
```

### Versions Report
```
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 15.04 vivid
        machine: x86_64
        release: 3.19.0-51-generic
         system: Ubuntu 15.04 vivid
```
