### ISSUE TITLE
JSON formatter creates invalid json

### ISSUE THREAD

**Issue by MadsRC** [saltstack/salt#31538]
### Expected Behavior

According to the documentation, a YAML list can be formatted as JSON using Jinja
### Actual Behavior

JSON formatter produces an invalid JSON string by using `'` instead of `"` for lists.
### Steps to Reproduce Issue

Pillar:

```
  client:
    subscriptions:
      - linux
      - test
```

State

```
  file.managed:
    - source: salt://sensu/files/client.json
    - name: /etc/sensu/config.json
    - user: sensu
    - group: sensu
    - mode: 750
    - template: jinja
    - context:
      host: {{ salt['pillar.get']('sensu:rabbitmq:host')  }}
      port: {{ salt['pillar.get']('sensu:rabbitmq:port')  }}
      user: {{ salt['pillar.get']('sensu:rabbitmq:user')  }}
      password: {{ salt['pillar.get']('sensu:rabbitmq:password')  }}
      vhost: {{ salt['pillar.get']('sensu:rabbitmq:vhost')  }}
      clientName: {{ salt['grains.get']('id')  }}
      address: {{ salt['grains.get']('ipv4')[0] }}
      subscriptions: {{ salt['pillar.get']('sensu:client:subscriptions')|json() }}
```

client.json

```
{
  "rabbitmq": {
      "host": "{{ host  }}",
      "port": "{{ port  }}",
      "user": "{{ user }}",
      "password": "{{ password }}",
      "vhost": "{{ vhost }}",
      "ssl": {}
    },
  "handlers": {
      "default": {
            "type": "set",
            "handlers": [
                    "stdout"
                  ]
          },
      "stdout": {
            "type": "pipe",
            "command": "cat"
          }
    },
  "client": {
      "name": "{{ clientName }}",
      "address": "{{ address }}",
      "subscriptions": {{ subscriptions }}
    }
}
```

Output:

```
{
  "rabbitmq": {
      "host": "REDACTED",
      "port": "5671",
      "user": "REDACTED",
      "password": "REDACTED",
      "vhost": "REDACTED",
      "ssl": {}
    },
  "handlers": {
      "default": {
            "type": "set",
            "handlers": [
                    "stdout"
                  ]
          },
      "stdout": {
            "type": "pipe",
            "command": "cat"
          }
    },
  "client": {
      "name": "REDACTED",
      "address": "127.0.0.1",
      "subscriptions": ['linux', 'test']
    }
}
```
### Versions Report

```
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.3
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: debian 8.3

```
