### ISSUE TITLE
hold: True for yum packages

### ISSUE THREAD

**Issue by pirxthepilot** [saltstack/salt#31566]
Not sure if this is intended behavior, but I am having trouble using `pkg` with `hold: True` under CentOS 7. I have this state:

```
openssh-server:
  pkg.installed:
    - version: 6.6.1p1-22.*
    - hold: True
```

This works fine: the correct package version is installed, and yum adds the versionlock entry:

```
# yum versionlock
Loaded plugins: fastestmirror, versionlock
0:openssh-server-6.6.1p1-22.el7.*
versionlock list done
```

The problem happens when I try to increment the version/release number. So after editing the line:

```
    - version: 6.6.1p1-23.*
```

and running a salt highstate, I get this error:

```
----------
          ID: openssh
    Function: pkg.installed
        Name: openssh-server
      Result: False
     Comment: The following packages failed to install/update: openssh-server=6.6.1p1-23.* Package openssh-server is already set to be held.
     Started: 16:56:00.750753
    Duration: 12916.394 ms
     Changes:
----------
```

I was expecting Salt here to remove the old versionlock entry, add the new one, then update accordingly, but apparently that doesn't happen.

### Versions Report
```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```
