### ISSUE TITLE
user.present formula on FreeBSD operates with no gid or group name

### ISSUE THREAD

**Issue by mallniya** [saltstack/salt#31574]
### Description of Issue/Question
Using `user.present` yields the following on applying (though different sets have been tried):

```
----------
          ID: recommender
    Function: user.present
      Result: False
     Comment: These values could not be changed: {'groups': []}
     Started: 13:12:05.454322
    Duration: 1377.926 ms
     Changes:
```

### Setup

I started from this setup:

```
recommender:
    user.present:
        - fullname: recommender
        - gid_from_name: True
```

and this end up exactly like in #23819. So I've tried to change formula a bit:

```
recommender:
  user.present:
    - fullname: recommender
    - gid: recommender
```
or
```
recommender:
  user.present:
    - fullname: recommender
    - gid: 9037
```

But still result is the same:
`These values could not be changed: {'groups': []}`
and entries in `/var/log/salt/minion`:
```
2016-03-01 13:33:42,953 [salt.loaded.int.module.cmdmod                                   ][ERROR   ][22016] Command 'pw usermod -G  -n recommender' failed with return code: 67
2016-03-01 13:33:42,954 [salt.loaded.int.module.cmdmod                                   ][ERROR   ][22016] output: pw: group `-n' does not exist
2016-03-01 13:33:43,498 [salt.state                                                      ][ERROR   ][22016] These values could not be changed: {'groups': []}
```

Also:
```
# id recommender                                                                     
uid=9037(recommender) gid=9037(recommender) groups=9037(recommender),10001(airflow)
```

I suppose it relates to #29099. My only question at the moment: is it a fast workaround to create user with his default group derived from name?

### Versions Report
```
Salt Version:
           Salt: 2015.8.5
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 14.3.1
         Python: 2.7.9 (default, Apr 27 2015, 11:42:05)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.1.1
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: amd64
        release: 10.1-STABLE-r273058
```

**Comment by jfindlay** [comment]
@mallniya, thanks for reporting.  You should be able to create a default group and user in a two step process: create group, create user and add to group.

**Comment by mallniya** [comment]
> You should be able to create a default group and user in a two step process: create group, create user and add to group.

@jfindlay unfortunately not, because even if I use:
```
recommender:
  user.present
```
then
```
----------
          ID: recommender
    Function: user.present
      Result: None
     Comment: The following user attributes are set to be changed:
              groups: []
     Started: 13:47:32.268270
    Duration: 274.807 ms
     Changes:   
```
still pops up. And, as @backerman noted in #23819 -- after some tests I suppose it's really a FreeBSD 10-10.1 bug, because same formula on 10.2 works fine.
