### ISSUE TITLE
requirements requisite makes pip.installed run every time state applies

### ISSUE THREAD

**Issue by mallniya** [saltstack/salt#31580]
### Description of Issue/Question

requirements requisite makes pip.installed run every time state applies, whether pip packages defined in requirements file are installed or not.
### Setup

My airflow state has following formula:

```
celery:
  pip.installed:
    - name: celery == 3.1.18
    - requirements: salt://airflow/etc/requirements.txt
    - require:
      - pkg: py27-pip
```

`airflow/etc/requirements.txt` content:

```
alembic>=0.8.3, <0.9
chartkick>=0.4.2, < 0.5
croniter>=0.3.8, <0.4
flask-admin==1.2.0
flask-cache>=0.13.1, <0.14
flask-login==0.2.11
Flask-WTF==0.12
```
### Steps to Reproduce Issue

And after applying state first time I expect not to get the following message:

```
----------
          ID: celery
    Function: pip.installed
        Name: celery == 3.1.18
      Result: True
     Comment: Successfully processed requirements file salt://airflow/etc/requirements.txt.
     Started: 18:01:38.860175
    Duration: 992.349 ms
     Changes:   
              ----------
              requirements:
                  True
```

But I get. Moreover, if there is no requirements requisite applying state happens silently.
### Versions Report

```
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 14.3.1
         Python: 2.7.9 (default, Apr 27 2015, 11:42:05)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.1.1
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:   
        machine: amd64
        release: 10.1-STABLE-r273058
```
