### ISSUE TITLE
dockerng ports specified in Dockerfile must be in sls file otherwise salt gives an error

### ISSUE THREAD

**Issue by dverbeek84** [saltstack/salt#31595]
After setting up dockerng i am hitting a issue with exposing ports. After some digging i see that you also need to specify ports that are in the dockerfile even if you don't use them in the sls.

For example. If you have a dockerfile that expose port 2375 with `EXPOSE 2375` but you don't use in the  following sls file:

```
swarm-docker:
  dockerng.running:
    - name: swarm-manager
    - image: swarm
    - command: 'manage -H :4000 --advertise {{ swarm.manager.advertise }}:4000 consul://127.0.0.1:8500'
    - ports:
      - "4000/tcp"
    - port_bindings:
      - "4000:4000/tcp"
```

The first run just works fine, but the second run i get the following error: `Failed to apply configuration for the following parameters: Ports`

If i look in the debug log of salt i see the following:
```
[DEBUG   ] dockerng.running: Analysis of container 'swarm-manager' after creation/replacement reveals the following changes still need to be made: {'ports': {'new': ['4000/tcp'], 'old': [u'2375/tcp', u'4000/tcp']}}
[ERROR   ] {'diff': {}, 'removed': [u'c31291be40374702ebb329e4ca1d585252a0cdc60a8acb2af2ac62371c4b0577'], 'added': {'Time_Elapsed': 0.07516789436340332, 'Name': 'swarm-manager', u'Id': u'8b540310611ff029b150f2725dc8e0327d21b0b2c5bca37e3c82249c3d51052d', u'Warnings': None}}
```

Because i have the port 2375 in the dockerfile, docker will add it. But salt want to remove it.
I don't know if it is a bug, because it is logic reaction. If it's not it needs to be added in the docs.

The following state is working:
```
swarm-docker:
  dockerng.running:
    - name: swarm-manager
    - image: swarm
    - command: 'manage -H :4000 --advertise {{ swarm.manager.advertise }}:4000 consul://127.0.0.1:8500'
    - ports:
      - "2375/tcp"
      - "4000/tcp"
    - port_bindings:
      - "4000:4000/tcp"
```

### Versions Report
```
docker: 1.10
doceker-py: 1.7.2
```

```
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by jfindlay** [comment]
@dverbeek84, thanks for reporting.

**Comment by dverbeek84** [comment]
@jfindlay If i need to test things, please let me know.

**Comment by ticosax** [comment]
@dverbeek84 please, can you test with `git branch 2015.8` ?

**Comment by dverbeek84** [comment]
@ticosax Same issue with branch 2015.8 and 2016.3

**Comment by ticosax** [comment]
@dverbeek84 Thanks, I will have a look then.

**Comment by dverbeek84** [comment]
@ticosax I have the same issue with labels.
The CentOS baseimage is coming with 4 default labels.
Without adding them to the state. The second highstate fails.

```
    - labels:
      - build-date: '2016-03-04'
      - license: 'GPLv2'
      - name: 'CentOS Base Image'
      - vendor: 'CentOS'
```

**Comment by ticosax** [comment]
@dverbeek84 please open a new issue for new bugs. Can you confirm your initial bug report is fixed so we can close this one ?

**Comment by dverbeek84** [comment]
Yes, it works in version Salt: 2015.8.8

**Comment by jfindlay** [comment]
Thanks, @dverbeek84, @ticosax.

**Comment by GenaSG** [comment]
Having the same issue on salt 2015.8.8.2 (Beryllium).
I'm trying to start consul container.
If I don't bind the /udp ports everything works just fine. But udp ports aren't accessible.

**Comment by ticosax** [comment]
@GenaSG please give us some details how to reproduce the faulty behavior.

**Comment by GenaSG** [comment]
Sure.
`Create consul container:
  dockerng.running:
    - name: consul
    - image: gliderlabs/consul-server:latest
    - restart_policy: always
    - ports:
      - 8300/tcp
      - 8301/tcp
      - 8301/udp
      - 8302/tcp
      - 8302/udp
      - 8400/tcp
      - 8500/tcp
      - 8600/tcp
      - 8600/udp
    - port_bindings:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    - command: 
      - "-bootstrap" 
      - "-advertise={{ pillar['consul_advertise_ip'] }}"`
This should give the error on second run and redeploy the container.

If udp related port bindings removed then there wouldn't be any error.

Possibly there is a related issue with command if it's presented as a string

` - command: "-bootstrap  -advertise={{ pillar['consul_advertise_ip'] }}" `

it would give ` Uncaught exception "'NoneType' object is not iterable" encountered while comparing existing container against desired configuration. See minion log for exception info.`

And with user.
If there is non-root execution user described in the Dockerfile it should be described in the sls file.
Else there would be `Failed to apply configuration for the following parameters: user`

All those scenarios result in container redeployment even if configuration is the same.

**Comment by jfindlay** [comment]
@GenaSG, I've fixed your formatting.

**Comment by ticosax** [comment]
@jfindlay thank you

**Comment by GenaSG** [comment]
@jfindlay
I've missed your message.
Thanks

**Comment by ticosax** [comment]
@GenaSG [here the how to](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting )

**Comment by GenaSG** [comment]
@ticosax Thanks mate.

**Comment by ticosax** [comment]
Regarding the issue, I can't reproduce it with up to date 2015.8 branch.

@jfindlay or @cachedout or @rallytime: Please can you confirm #32015 is part of `2015.8.8.2` ?
According to [github](https://github.com/saltstack/salt/commit/d117db3efb343143d44329fd49e64c3dff18cacd) it seems not.

**Comment by GenaSG** [comment]
@ticosax Have you try to execute state several times? Because it works ok on the first run.

**Comment by ticosax** [comment]
yes, like you described.

**Comment by GenaSG** [comment]
@ticosax that's odd. Thanks anyway.

**Comment by ticosax** [comment]
```yaml
Create consul container:
  dockerng.running:
    - name: consul
    - image: gliderlabs/consul-server:latest
    - ports:
      - 8300/tcp
      - 8301/tcp
      - 8301/udp
      - 8302/tcp
      - 8302/udp
      - 8400/tcp
      - 8500/tcp
      - 8600/tcp
      - 8600/udp
    - port_bindings:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    - command: 
      - "-bootstrap"
      - "-advertise=127.0.0.1"
```
with salt@35c8af3ece842eda3fde08a3d5a4118d430bb14d

**Comment by ticosax** [comment]
that its. with b9d0336cf8861ff99f2019c46851208b2a393f19 (`v2015.8.8` tag) the state is failing like @GenaSG reported.

So it means that `2015.8.8.2` doesn't contain the fix.

**Comment by rallytime** [comment]
@ticosax You are correct. The commit from your fix in #32015 (which is e511864a553d34d5e7e07a474c2127ca96264e8a) did not make it into the 2015.8.8 or 2015.8.8.2 tags. It will be in the next release of the 2015.8 branch, which will be 2015.8.9.
```
nt:salt pinyon$ salt --version
salt 2015.8.8.2 (Beryllium)
nt:salt pinyon$ git log | grep e511864a553d34d5e7e07a474c2127ca96264e8a
nt:salt pinyon$
```

**Comment by rallytime** [comment]
Since this is fixed at the head of the 2015.8 branch and will be available in the 2015.8.9 release, I'm going to close this again.

**Comment by joshughes** [comment]
I am still seeing this error with 2015.8.10

**Comment by stefanlsd** [comment]
Hi, can confirm im seeing it in 2015.8.10 also

**Comment by ticosax** [comment]
@joshughes , @stefanlsd Please provide a reproducible use case.

**Comment by joshughes** [comment]
```

amazon/amazon-ecs-agent:
  dockerng.image_present:
    - force: True

ecs:
  dockerng.running:
    - image: amazon/amazon-ecs-agent
    - binds:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/ecs/:/log
      - /var/lib/ecs/data:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro
    - environment:
      - ECS_LOGFIEL: /var/log/ecs-agent.log
      - ECS_LOGLEVEL: debug
      - ECS_CLUSTER: foo
      - ECS_DATADIR: /data/
      - ECS_ENGINE_AUTH_TYPE: docker
    - ports:
      - "51678/tcp"
    - port_bindings:
      - "51678:51678/tcp"
```

Every run the container is recreated.
