### ISSUE TITLE
gpg ciphers not recoginized in ext_pillar using consul as a provider

### ISSUE THREAD

**Issue by mmastoras** [saltstack/salt#31605]
### Description of Issue/Question

gpg ciphers are not being recognized and decrypted when pulled from an ext_pillar using consul as a provider. The yaml data stored in the consul value is getting read in as an array of values, which is interfering (assumption) w/ the gpg renderer. Is there a work around in consul_pillar.py for this ? 
### Setup

Running in a vagrant environment with the following salt master file config, encrypted data in a local pillar, connecting to a consul server w/ the same encrypted data stored as a value.

/etc/salt/master file:

``` sls
    renderer: jinja | yaml | gpg

    pillar_roots:
      base:
        - /srv/pillar

    consul_config:
       consul.host: localhost 
       consul.port: 8500
       consul.token: XXXX-XXXX-XXXX-XXXX-XXXXXXX

     ext_pillar:
       - consul: consul_config root=pillars
```

Sample local pillar data in file /srv/pillar/crypted/init.sls:

``` sls
#!yaml|gpg

settings:
    crypted_secret: |
        -----BEGIN PGP MESSAGE-----
        Version: GnuPG v1

        hQEMA50oGf0JEilHAQf/Unbj8VBeTwv4IOUEwfQ0ZqYDDVT9pQ+fk2btw1Knn60+
        N/X+FsztU4HTFopY+hHO09RKHzUpj7aJQqU5gMYK1BRE4pAh7alAbtadkRoWD16a
        HwlAE+uiDNso5w3ORIHrotMDfCtXDFZI6EAYQZ9NHBj+xRgqV1cy4lSKFZpn/2Fq
        UWIIuYIZBzBnaPQc0CiHB1g/xHzKzenxdjQjUMiCbkD7PzoPvq46szhEdd1ZDlTb
        LwxHMicUVRciktl6GhtkfQGKxt+7B/Tt3lw8HpWkVs2IhqwIcFD8EAmVilSX0AnR
        yIi3ajpzQDYNjkKxVOzrMmyyEA+g0rAfdFBI2BFDcNJKAcRCUFk58Ru0AmfsnFEW
        o6GjvCEXMw+n+LaFpCPIeKQJhOIvJY9Hpxzcug96jYz1Kh6gxojXKG9FLiouiKgD
        /LtUKf2rQ/K8k6s=
        =BGRN
        -----END PGP MESSAGE-----
```

Sample External Pillar data in consul:

``` sls
key => pillars/prod/mysql/password
value =>
#!yaml|gpg

password: |
    -----BEGIN PGP MESSAGE-----
    Version: GnuPG v1

    hQEMA50oGf0JEilHAQf/Unbj8VBeTwv4IOUEwfQ0ZqYDDVT9pQ+fk2btw1Knn60+
    N/X+FsztU4HTFopY+hHO09RKHzUpj7aJQqU5gMYK1BRE4pAh7alAbtadkRoWD16a
    HwlAE+uiDNso5w3ORIHrotMDfCtXDFZI6EAYQZ9NHBj+xRgqV1cy4lSKFZpn/2Fq
    UWIIuYIZBzBnaPQc0CiHB1g/xHzKzenxdjQjUMiCbkD7PzoPvq46szhEdd1ZDlTb
    LwxHMicUVRciktl6GhtkfQGKxt+7B/Tt3lw8HpWkVs2IhqwIcFD8EAmVilSX0AnR
    yIi3ajpzQDYNjkKxVOzrMmyyEA+g0rAfdFBI2BFDcNJKAcRCUFk58Ru0AmfsnFEW
    o6GjvCEXMw+n+LaFpCPIeKQJhOIvJY9Hpxzcug96jYz1Kh6gxojXKG9FLiouiKgD
    /LtUKf2rQ/K8k6s=
    =BGRN
    -----END PGP MESSAGE-----
```
### Steps to Reproduce Issue

run `sudo salt '*' pillar.items` to show the secret being properly decrypted from the local pillar file, but not properly decrypted from the external pillar value (in consul).

``` yaml
output: 

minion1:
    ----------
    prod: 
           ----------
           mysql:
                     ----------
                     password:
                      - #!yaml|gpg
                      - password: |
                      -     -----BEGIN PGP MESSAGE-----
                      -    Version: GnuPG v1
                      -    hQEMA50oGf0JEilHAQf/Unbj8VBeTwv4IOUEwfQ0ZqYDDVT9pQ+fk2btw1Knn60+
                      -    N/X+FsztU4HTFopY+hHO09RKHzUpj7aJQqU5gMYK1BRE4pAh7alAbtadkRoWD16a
                      -    HwlAE+uiDNso5w3ORIHrotMDfCtXDFZI6EAYQZ9NHBj+xRgqV1cy4lSKFZpn/2Fq
                      -    UWIIuYIZBzBnaPQc0CiHB1g/xHzKzenxdjQjUMiCbkD7PzoPvq46szhEdd1ZDlTb
                      -    LwxHMicUVRciktl6GhtkfQGKxt+7B/Tt3lw8HpWkVs2IhqwIcFD8EAmVilSX0AnR
                      -    yIi3ajpzQDYNjkKxVOzrMmyyEA+g0rAfdFBI2BFDcNJKAcRCUFk58Ru0AmfsnFEW
                      -    o6GjvCEXMw+n+LaFpCPIeKQJhOIvJY9Hpxzcug96jYz1Kh6gxojXKG9FLiouiKgD
                      -    /LtUKf2rQ/K8k6s=
                      -    =BGRN
                      -   -----END PGP MESSAGE-----
    settings:
        ----------
        crypted_secret:
            ;;;XJSUSSISDjjjj
```
### Versions Report

``` yaml
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.6
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-68-generic
         system: Ubuntu 14.04 trusty
```
