### ISSUE TITLE
Cannot set gid in user.present when user already exists

### ISSUE THREAD

**Issue by fredrikaverpil** [saltstack/salt#31613]
### Description of Issue/Question

When attempting to set gid to `500` via the `user.present` function, I get this:

> These values could not be changed: {'gid': 500}` 

Full output:

```
bs01gen04:
----------
          ID: iruser
    Function: user.present
      Result: False
     Comment: These values could not be changed: {'gid': 500}
     Started: 09:48:00.789856
    Duration: 133.02 ms
     Changes:
              ----------
              uid:
                  500
```
### Setup

The user was created via [kickstart file](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/sect-kickstart-syntax.html), CentOS 7:

```
user --groups=wheel --name=iruser --password=xxx --iscrypted --gecos="Myco user"
```

`users.sls` file contents:

```
iruser:
  user.present:
    - fullname: Myco user
    - home: /home/iruser
    - uid: 500
    - gid: 500
    - groups:
      - wheel
```
### Steps to Reproduce Issue

```
salt 'bs01gen04' state.apply users.sls
```
### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-123.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```
