### ISSUE TITLE
2015.8.7 pkg.installed problem with version parameter

### ISSUE THREAD

**Issue by alexxannar** [saltstack/salt#31619]
### Description of Issue/Question
Since update to 2015.8.7 version parameter in  pkg.installed is not working correctly. I've tryed to set version by many ways ( 2.7.0, 2.7.0-1, 2:2.7.0-1.el6  etc) and everytime i get this:

The following packages failed to install/update: postfix=2.7.0

Before update all was ok.

### Setup
```sls
install_postfix:
  pkg.installed:
    - name: postfix
    {% if grains['os'] == 'CentOS' %}
    - version: 2.7.0-1
    {% endif %}
```
repos:
```yaml
[root@mymaster postfix]# salt 'myminion' pkg.list_repo_pkgs postfix
myminion:
    ----------
    base:
        ----------
        postfix:
            - 2:2.6.6-6.el6_5
    mycustomrepo:
        ----------
        postfix:
            - 2:2.7.0-1.el6
```

### Steps to Reproduce Issue
Just run sls as is.
log has only this:
```
2016-03-02 16:06:05,329 [salt.state                                                ][ERROR   ][30534] The following packages failed to install/update: postfix=2.7.0-1
```
### Versions Report
```yaml
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: unknown
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: CentOS 6.7 Final
```
