### ISSUE TITLE
salt.modules.gpg.create_key sets bogus passphrase

### ISSUE THREAD

**Issue by Ntr0** [saltstack/salt#31645]
### Description of Issue/Question
Due to the fact that gpg.create_key (and other methods) use `__salt__['pillar.item']('gpg_passphrase')` instead of `pillar.get`, created gpg keys will have the passphrase `{'gpg_passphrase': '<intended passphrase>'}`.

### Setup
Just mocking up the sls and pillar:

state:
```sls
user-gpg:
   module.run:
     - name: gpg.create_key
     - key_type: RSA
     - key_length: 2048
     - name_real: Users Autokey
     - name_comment: Generated by Salt
     - name_email: {{ salt['pillar.get']('gpg:email') }}
     - use_passphrase: true
     - user: {{ salt['pillar.get']('gpg:user') }}
```
pillar:
```yaml
gpg_passphrase: password
gpg:
  user: name
  email: mail@domain.com
```
### Steps to Reproduce Issue
*Include debug logs if possible and relevant.*

### Versions Report
*Provided by running* ``salt --versions-report``
```yaml
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
 
```

I have already fixed this locally and will provide the fix asap.

Regards,
Ntr0
