### ISSUE TITLE
Service is not restarting when file changes

### ISSUE THREAD

**Issue by bpatelcs** [saltstack/salt#31669]
### Description of Issue/Question

I want to restart ntp server on minion whenever there is change in ntp.conf file on master at salt://ntp.conf.I have tried many times but it seems not working, although if I do `salt '*' state.highstate` service does restart.Let me know if I am doing something wrong.BTW, Salt is tasty :+1: 
### Setup

```
ntp:
  service.running:
    - watch:
      - file: /etc/ntp.conf

/etc/ntp.conf:
  file:
    - managed
    - source: salt://ntp.conf

```
### Versions Report

```
       Salt: 0.17.5
     Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
     Jinja2: 2.7.2
   M2Crypto: 0.21.1
   msgpack-python: 0.3.0
    msgpack-pure: Not Installed
   pycrypto: 2.6.1
     PyYAML: 3.10
      PyZMQ: 14.0.1
        ZMQ: 4.0.4
```
