### ISSUE TITLE
Unable to load custom module second time around.

### ISSUE THREAD

**Issue by daswathn** [saltstack/salt#31698]
Hello All,

I have written custom module on my salt-master server, it vanishes when I run **salttuil.sync_all** again. 

file_roots under the /etc/salt/master file is as below, 
```
file_roots:
  base:
    - /srv/salt
  windows:
    - /srv/salt/windows
  linux:
    - /srv/salt/linux

```
I have a simple custom module written to get the user info from my minions, below is the code snippet.
```

root@dewd01548:/srv/salt/linux# cat _modules/customuser.py
#Custom Module, details inside the script
#Deepak Aswathnarayan

def user_as_csv():

         '''Retrive users from a minion, formatted as commma-seperated
           values.

           CLI Example:
           .. code-block:: bash
           salt '*' customuser.users_as_csv
        '''

        user_list = __salt__['user.list_users']()
        csv_list  = ','.join(user_list)
        return csv_list

```

The issues seems very strange though, I am able to see the module when I sync the first time around but vanishes second time.

```
root@dewdf0154:/srv/salt/linux# salt 'dewdfgld' saltutil.sync_all
dewdfgld:
    ----------
    beacons:
    grains:
    log_handlers:
    modules:
        - modules.customuser
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
    utils:

root@dewdf01548:/srv/salt/linux# salt 'dewdfgld' saltutil.sync_all
dewdfgld:
    ----------
    beacons:
    grains:
    log_handlers:
    modules:
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
    utils:

```
Here the strange thing is if I move **/srv/salt/linux/_module**  folder to /tmp and re-create the _module folder again and run the syncutil.sync_all I am able to see my module but only once.

My salt Version is as below
```
salt --versions-report
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Feb 11 2014, 07:46:25)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 7.1 Maipo
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: Red Hat Enterprise Linux Server 7.1 Maipo

```
Kindly let me know how I can debug this issues.
