### ISSUE TITLE
while calling file.managed state, I get the error : Unable to manage file: Jinja variable  'java64_home' is undefined

### ISSUE THREAD

**Issue by AliGouta** [saltstack/salt#31701]
### Description of Issue/Question

I am newbie to salt, I am calling this state:

```
blueprint-creation:
file.managed:
    - name: /tmp/blueprint.json
    - source: salt://hadoop/deploy/files/blueprint.json
    - template: jinja
    - mode: 0640
    - user: root
    - group: root
    - makedirs: True
```

The file "blueprint.json" is already a template file (used for other purposes) and contains some fields surrounded with {{ }} pattern which are not intentded to be replaced with pillars. In this file, there is also some templates that are intended to be changed with pillars. 

When applying my state, I want to keep some fields surrounded with {{ }} as they are on my minion, however, changes should be applied on the intended ones. Example:

-JAVA_HOME={{java64_home}}  **=>** On the minion this should remain the unchanged.
-"blueprint_name": "{{ hadoop.blueprint }}" **=>** On the minion, hadoop.blueprint should be replaced with my pillars.

Replacing the template is clear for me, but I don't see how to force salt to not change the reamining fields surrounded with the template: {{  }}.

Any help ? Thank you.

**Comment by duk3luk3** [comment]
Please show your template file - you probably have a jinja syntax problem.

**Comment by AliGouta** [comment]
Here is a snippet of the template (file that should be copied and fulfilled to the minion):

```
salt://hadoop/deploy/files/blueprint-5groups.json:
{
    "configurations": [
        {
            "ams-env": {
                "properties": {
                    "ambari_metrics_user": "ams",
                    "content": "\n# Set environment variables here.\n\n# The java implementation to use. Java 1.6 required.\nexport JAVA_HOME={{java64_home}}\n\n# Collector Log directory for log4j\nexport AMS_COLLECTOR_LOG_DIR={{ams_collector_log_dir}}\n\n# Monitor Log directory for outfile\nexport AMS_MONITOR_LOG_DIR={{ams_monitor_log_dir}}\n\n# Collector pid directory\nexport AMS_COLLECTOR_PID_DIR={{ams_collector_pid_dir}}\n\n# Monitor pid directory\nexport AMS_MONITOR_PID_DIR={{ams_monitor_pid_dir}}\n\n# AMS HBase pid directory\nexport AMS_HBASE_PID_DIR={{hbase_pid_dir}}\n\n# AMS Collector heapsize\nexport AMS_COLLECTOR_HEAPSIZE={{metrics_collector_heapsize}}\n\n# AMS Collector options\nexport AMS_COLLECTOR_OPTS=\"-Djava.library.path=/usr/lib/ams-hbase/lib/hadoop-native -Xmx$AMS_COLLECTOR_HEAPSIZE \"\n{% if security_enabled %}\nexport AMS_COLLECTOR_OPTS=\"$AMS_COLLECTOR_OPTS -Djava.security.auth.login.config={{ams_collector_jaas_config_file}}\"\n{% endif %}",
                    "metrics_collector_heapsize": "512m",
                    "metrics_collector_log_dir": "/var/log/ambari-metrics-collector",
                    "metrics_collector_pid_dir": "/var/run/ambari-metrics-collector",
                    "metrics_monitor_log_dir": "/var/log/ambari-metrics-monitor",
                    "metrics_monitor_pid_dir": "/var/run/ambari-metrics-monitor"
                }
            }
        }
     ],
   "Blueprints": {
        "blueprint_name": "{{ hadoop.blueprint }}",
        "stack_name": "HDP",
        "stack_version": "2.3"
    }
}

```
This file is called using this state declaration:

```
blueprint-creation:
  file.managed:
    - name: /tmp/blueprint-5groups.json
    - source: salt://hadoop/deploy/files/blueprint-5groups.json
    - template: jinja
    - mode: 0640
    - user: root
    - group: root
    - makedirs: True
```
As you can see, this jinja template {{ hadoop.blueprint }} would be filled using pillars. However, the rest of templates such as {{ams_monitor_pid_dir}}, shoud be copied and pasted to the minions without any edition.
