### ISSUE TITLE
mode isn't set right on files/folders (2015.8.7)

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#31721]
state

```
/var/log/newrelic:
  file.directory:
    - mode: '1755'
    - user: newrelic
    - group: newrelic
    - require:
      - pkg: newrelic-sysmond
```

output:

```
----------
          ID: /var/log/newrelic
    Function: file.directory
      Result: True
     Comment: Directory /var/log/newrelic updated
     Started: 16:45:52.474472
    Duration: 0.889 ms
     Changes:
              ----------
              mode:
                  01755
```

=> there is 0 prefixed even I setup it as text with 4 octal numbers.

**Comment by jfindlay** [comment]
@Reiner030, thanks for reporting.  Here is my test case:
```console
jmoney-main ~ master # mkdir /tmp/newrelic ; chmod 700 /tmp/newrelic
```
```sls
jmoney-main ~ master # cat /srv/salt/test.sls
/tmp/newrelic:
  file.directory:
    - mode: '1755'
    - user: root
    - group: root
```
```yaml
jmoney-main ~ master # salt jmoney-main state.apply test
jmoney-main:
----------
          ID: /tmp/newrelic
    Function: file.directory
      Result: True
     Comment: Directory /tmp/newrelic updated
     Started: 16:27:23.925500
    Duration: 8.214 ms
     Changes:
              ----------
              mode:
                  01755

Summary for jmoney-main
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
```yaml
jmoney-main ~ master # salt --versions
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.3
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3
```
