### ISSUE TITLE
pkg.latest fail

### ISSUE THREAD

**Issue by aronneagu** [saltstack/salt#31720]
### Description of Issue/Question
pkg.latest state fails, on several id's with different error messages (3 different error messages)

For package git, the id is
```
git:
  pkg.latest:
    - order: 1
```
returns
```
ID: git
    Function: pkg.latest
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call l
ast):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624
, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 149
1, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pkg.py", line
 1397, in latest
                  cur = __salt__['pkg.version'](*desired_pkgs, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py",
line 317, in version
                  return __salt__['pkg_resource.version'](*names, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/pkg_resource
.py", line 184, in version
                  pkgs = __salt__['pkg.list_pkgs'](versions_as_list=True, **kwar
gs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py",
line 1148, in list_pkgs
                  virtpkgs_all = _get_virtual()
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py",
line 175, in _get_virtual
                  apt_cache = apt.cache.Cache()
                File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 107,
in __init__
                  self.open(progress)
                File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 153,
in open
                  self._records = apt_pkg.PackageRecords(self._cache)
              SystemError: E:Could not open file /var/lib/apt/lists/repo.saltsta
ck.com_apt_ubuntu_ubuntu14_latest_dists_trusty_main_binary-amd64_Packages - open
 (2: No such file or directory), E:Could not open file /var/lib/apt/lists/eu-wes
t-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-backports_universe_i18n_Translati
on-en - open (2: No such file or directory), E:Could not open file /var/lib/apt/
lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-backports_restricted_
i18n_Translation-en - open (2: No such file or directory), E:Could not open file
 /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-backpor
ts_multiverse_i18n_Translation-en - open (2: No such file or directory), E:Could
 not open file /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_
trusty-backports_main_i18n_Translation-en - open (2: No such file or directory),
 E:Could not open file /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubunt
u_dists_trusty-backports_multiverse_binary-amd64_Packages - open (2: No such fil
e or directory), E:Could not open file /var/lib/apt/lists/eu-west-1.ec2.archive.
ubuntu.com_ubuntu_dists_trusty-backports_universe_binary-amd64_Packages - open (
2: No such file or directory), E:Could not open file /var/lib/apt/lists/eu-west-
1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-backports_restricted_binary-amd64_P
ackages - open (2: No such file or directory), E:Could not open file /var/lib/ap
t/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-backports_main_bina
ry-amd64_Packages - open (2: No such file or directory), E:Could not open file /
var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_u
niverse_i18n_Translation-en - open (2: No such file or directory), E:Could not open file /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_restricted_i18n_Translation-en - open (2: No such file or directory), E:Could not open file /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_multiverse_i18n_Translation-en - open (2: No such file or directory), E:Could not open file /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_main_i18n_Translation-en - open (2: No such file or directory), E:Could not open file /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_multiverse_binary-amd64_Packages - open (2: No such file or directory), E:Could not open file /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_universe_binary-amd64_Packages - open (2: No such file or directory), E:Could not open file /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_restricted_binary-amd64_Packages - open (2: No such file or directory), E:Could not open file /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_main_binary-amd64_Packages - open (2: No such file or directory), E:Could not open file /var/lib/apt/lists/eu-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty_main_binary-amd64_Packages - open (2: No such file or directory)
     Started: 14:59:21.552561
    Duration: 1869.942 ms
     Changes:
```

For auditd package
```
auditd:
  pkg.latest
```
returns 
```
ID: auditd
    Function: pkg.latest
      Result: False
     Comment: An error was encountered while checking the newest available version of package(s): E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
              E: Unable to lock directory /var/lib/apt/lists/
     Started: 14:59:24.376809
    Duration: 62.738 ms
     Changes:

```

For package curl the state file is
```
curl:
  pkg.latest
```
returns
```
          ID: curl
    Function: pkg.latest
      Result: False
     Comment: An error was encountered while checking the newest available version of package(s): E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
              E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
     Started: 14:59:31.239322
    Duration: 3305.396 ms
     Changes: 
```

The servers are EC2 instances in Amazon cloud. They are provisioned using salt cloud, and startup_states: highstate is set, so when salt-minion is first installed highstate is ran. If I run highstate manually afterwards, the failed states execute correctly and the packages are installed. Additionally, we have multiple pkg.latests states, and only about half of them fail at the first attempt, but only 2 out every 10 provisioned servers fail.
So, in conclusion:
- about half of pkg.latest states fail (and it's not always for the same packages) for 2 out every 10 servers provisioned, and with 3 different error messages

### Versions Report
*Provided by running* ``salt --versions-report``
```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Ubuntu 14.04 trusty
```

I would like to get to the bottom of this. I can provide more logs if necessary. I would appreciate some directions, where I can look to investigate more. Thank you
Aron
