### ISSUE TITLE
No output for some minions when state run in batch mode

### ISSUE THREAD

**Issue by igorwidlinski** [saltstack/salt#31737]
### Description of Issue/Question
For some reason salt will not output summary for some minions when run in batch mode. Running same state in batch mode but with '--static' flag outputs proper summary. Output is always displayed correctly when not using batch mode.

Here is output for batch mode run against one minion. Note no summary information.
```
salt --output=highstate -b 1  'db1*' state.sls dns-client
/usr/lib64/python2.6/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)

Executing run on ['db1.cluster.aws.example.com']

retcode:
    0
```

And proper summary when static ('-s') added to command:
```
[root@salt-devops salt]# salt --output=highstate -b 1 -s 'db1*' state.sls dns-client
/usr/lib64/python2.6/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
db1.cluster.aws.example.com:

Summary for db1.cluster.aws.example.com
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

This usually happens when retcode is first in the data dict.
```
2016-03-07 18:54:04,288 [salt.output      ][TRACE   ][31512] data = {'retcode': 0, 'db1.cluster.aws.example.com': {'file_|-/etc/resolv.conf_|-/etc/resolv.conf_|-managed': {'comment': 'The file /etc/resolv.conf is in the correct state', 'name': '/etc/resolv.conf', 'start_time': '18:54:04.025972', 'result': True, 'duration': 90.759, '__run_num__': 0, 'changes': {}}}}
```
Here is the data dict when run against other server, this one outputs properly even without strict setting, note retcode is last in the data dict:
```
data = {'node002.cluster.aws.example.com': {'file_|-/etc/resolv.conf_|-/etc/resolv.conf_|-managed': {'comment': 'The file /etc/resolv.conf is in the correct state', 
'name': '/etc/resolv.conf', 'start_time': '18:57:21.303564', 'result': True, 'duration': 21.341000000000001, '__run_num__': 0, 'changes': {}}}, 'retcode': 0}
```

### Versions Report
*Provided by running* ``salt --versions-report``
```
[root@salt-devops ~]# salt --versions-report 
/usr/lib64/python2.6/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 22 2015, 16:47:47)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: redhat 6.3 Carbon
        machine: x86_64
        release: 2.6.32-573.12.1.el6.x86_64
         system: Scientific Linux 6.3 Carbon
```

**Comment by jfindlay** [comment]
@igorwidlinski, thanks for reporting.  I am unable to reproduce this.  Is there anything else I can try?
```yaml
jmoney-main ~ master # salt --batch 1 jmoney-main state.apply test

Executing run on ['jmoney-main']

jmoney-main:
----------
          ID: /tmp/dir
    Function: file.directory
      Result: True
     Comment: Directory /tmp/dir updated
     Started: 10:01:32.783369
    Duration: 10.952 ms
     Changes:
              ----------
              /tmp/dir:
                  New Dir

Summary for jmoney-main
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
```yaml
jmoney-main ~ master # salt --out=highstate --batch=1 jmoney-main state.apply test

Executing run on ['jmoney-main']

jmoney-main:
----------
          ID: /tmp/dir
    Function: file.directory
      Result: True
     Comment: Directory /tmp/dir is in the correct state
     Started: 10:02:25.487474
    Duration: 8.308 ms
     Changes:

Summary for jmoney-main
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```
```yaml
jmoney-main ~ master # salt jmoney-main test.versions
jmoney-main:
    Salt Version:
               Salt: 2015.8.7
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
     
    System Versions:
               dist: debian 8.3 
            machine: x86_64
            release: 3.16.0-4-amd64
             system: debian 8.3 
```
