### ISSUE TITLE
'keep' argument for archive.extracted has no effect

### ISSUE THREAD

**Issue by hexedpackets** [saltstack/salt#31756]
According to the docs, setting `keep: false` for the archive.extracted state should prevent the downloaded files from being cached. However, it doesn't seem to change the behavior of the state at all. Each update causes the new archive to be cached along with the previous files.

## Example state
```yaml
s3_archive:
  archive.extracted:
    - source: s3://{{ bucket }}/{{ key_name }}
    - source_hash: sha256={{ hash }}
    - name: {{ dir }}/{{ release_key }}
    - archive_format: tar
    - keep: false
```

With the above state, I have numerous tarballs hanging around in /var/cache/salt/minion/extrn_files/base/<bucket>/<key>/ that have to be manually deleted.

## Version info
```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-18-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@hexedpackets, thanks for reporting.

**Comment by abednarik** [comment]
HI

 After a few hours tracing this one I found a few things

+ This is the state used for test

```yml
htop:
  archive.extracted:
    - name: /opt/
    - source: http://pkgs.fedoraproject.org/repo/pkgs/htop/htop-1.0.2.tar.gz/md5/0d01cca8df3349c74569cefebbd9919e/htop-1.0.2.tar.gz
    - source_hash: md5=0d01cca8df3349c74569cefebbd9919e
    - archive_format: tar
    - if_missing: /opt/htop-1.0.2
    - keep: True
```

+ After running that state I see 2 files, the actual one defined in the state and another one created internally by salt

```
0d01cca8df3349c74569cefebbd9919e  /var/cache/salt/minion/files/base/_opt_htop-1.0.2.tar
0d01cca8df3349c74569cefebbd9919e  /var/cache/salt/minion/extrn_files/base/pkgs.fedoraproject.org/repo/pkgs/htop/htop-1.0.2.tar.gz/md5/0d01cca8df3349c74569cefebbd9919e/htop-1.0.2.
```

+ When using keep: False salt removes the _internal_ file, but leaves everything inside _/var/cache/salt/minion/extrn_files/_ untouched

+ I don't see how I can get that _internal_ reference inside archive state at this point. 

I will keep searching, but at least this bug is a little bit clearer now I think.
