### ISSUE TITLE
Using git as backend causes top file to not be found

### ISSUE THREAD

**Issue by geraint-jones-nz** [saltstack/salt#31782]
### Description of Issue/Question

I have a salt master using git as its only backend, when highstating the following error is returned. This config previously worked.

```
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Started:
    Duration:
     Changes:
```
### Setup

`/etc/salt/master`

```
fileserver_backend:
  - git

gitfs_provider: gitpython

gitfs_root: states

gitfs_remotes:
  - git@<redacted>.git:
    - root: salt
  - https://github.com/saltstack-formulas/nginx-formula.git
  - https://github.com/saltstack-formulas/jenkins-formula.git
  - https://github.com/saltstack-formulas/php-formula.git
  - https://github.com/saltstack-formulas/sun-java-formula.git
  - https://github.com/saltstack-formulas/newrelic-formula.git

ext_pillar:
  - git:
    # SSH key authentication
    - master git@<redacted>.git:
      - root: pillar

ext_pillar_first: True

rest_cherrypy:
  port: 8000
  disable_ssl: true
  webhook_url: /hook
  webhook_disable_auth: True

external_auth:
  pam:
    salt-api.lumiserv:
      - .*

reactor:
  - 'salt/fileserver/gitfs/update':
    - /srv/reactor/update_fileserver.sls
  - 'salt/netapi/hook/ec2/autoscale':
    - /srv/reactor/ec2-autoscale.sls

ec2.autoscale:
  provider: <redacted>

smtp.from: '<redacted>'
smtp.to: <redacted>
smtp.host: <redacted>
smtp.username: '<redacted>'
smtp.password: '<redacted>'
smtp.tls: True
smtp.subject: 'Salt'

schedule:
  job1:
    function: cloud.full_query
    seconds: 300
```

### Steps to Reproduce Issue

1.) Use gitfs as backend
2.) do `salt '*' state.highstate`

### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 4.0.0
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Ubuntu 14.04 trusty
```
