### ISSUE TITLE
pkg.installed doesn't work on Manjaro.

### ISSUE THREAD

**Issue by crocket** [saltstack/salt#31788]
### Description of Issue/Question

I installed salt-git from AUR. It fetched the latest git commit and built SaltStack and turned it into a package. When I execute `salt-call --local state.highstate`, I see the error message below for many sls files.

```
----------
          ID: zsh
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'pkg.zsh'
              Reason: 'pkg' __virtual__ returned False
     Started: 
    Duration: 
     Changes:
```

All error messages are related to pkg.installed

### Steps to Reproduce Issue

Test pkg.installed on Manjaro.

### Versions Report

`salt-call 2016.3.0-190-g538ec98 (Boron)`
