### ISSUE TITLE
File.managed will not replace a symlink

### ISSUE THREAD

**Issue by JaseFace** [saltstack/salt#31802]
### Description of Issue/Question
Using file.managed to write a file will follow the symlink and write to the sym destination when the default of follow_symlinks is set to true.  When you use follow_symlinks: False, Salt fails to overwrite the symlink and errors with:

```
    Function: file.managed
    Name: /etc/somefile.conf
    Result: False
    Comment: Unable to manage file: 'NoneType' object has no attribute 'startswith'
```

### Setup
Try to overwrite a file that's currently a symlink:
```
somefile:
  file.managed:
    - name: /etc/somefile.conf
    - follow_symlinks: False
```

### Versions Report
```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.10 (default, Jul 21 2015, 21:44:29)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: amd64
        release: 10.1-STABLE-llnw19
```

**Comment by jfindlay** [comment]
@JaseFace, thanks for reporting.

**Comment by bgdnlp** [comment]
Still true for 2016.11.2 running on Ubuntu 16.

To clarify, the expectation is that when `follow_symlinks` is False and a symlink exists in place of the file, the symlink is removed and a new file is created.

Workaround, for anyone stumbling upon this issue:
```
remove /path/somefile symlink:
  file.absent:
    - name: /path/somefile
    - onlyif:
      - test -L /path/somefile

/path/somefile:
  file.managed:
    - contents:
      - 'I am not a symlink'
      - '#someta'
```

**Comment by joshenders** [comment]
Was caught by surprise by this as well. Will the solution above always remove the symlink first or is there a case where the file could be copied first (and clobber whatever the symlink is pointed to)?

**Comment by teran-mckinney** [comment]
Running into this with writing /etc/resolv.conf when it's been set by systemd-resolved as a symlink.

**Comment by teran-mckinney** [comment]
Think this is still active from what I know.

**Comment by birarda** [comment]
Just tested this from a 2018.3.0 salt master to a 2019.2.3 salt minion and the expected behaviour occurred (a file.managed with `follow_symlinks: False` removed the broken symlink)

**Comment by nergdron** [comment]
unfortunately this seems to be broken again as of v3004. I get the following when trying to replace the `systemd-resolvd` symlink for `/etc/resolv.conf`, when using `file.managed` with `follow_symlinks: false`:

```
          ID: resolv_conf
    Function: file.managed
        Name: /etc/resolv.conf
      Result: False
     Comment: Unable to manage file: /etc/resolv.conf: File not found
     Started: 20:26:41.250551
    Duration: 7.712 ms
     Changes:   
    Warnings: Failed to detect changes to file: Failed to read
              /run/systemd/resolve/stub-resolv.conf: No such file or directory
```
from the output, it seems like it's ignoring `follow_symlinks` entirely and just always follows the symlink. which breaks since I've already disabled `systemd-resolved` by this point in the state.

**Comment by nergdron** [comment]
this seems to be broken again, at least in `v3004`. here's the state I'm using to try and configure `/etc/resolv.conf`:

```
resolv_conf:
  file.managed:
    - name: /etc/resolv.conf
    - contents: nameserver 127.0.0.1
    - user: root
    - group: root
    - mode: "0644"
    - follow_symlinks: false
    - require:
      - pkg: dnsmasq
```

and here's the output I get:

```
          ID: resolv_conf
    Function: file.managed
        Name: /etc/resolv.conf
      Result: False
     Comment: Unable to manage file: 'NoneType' object has no attribute 'startswith'
     Started: 20:49:35.841985
    Duration: 8.041 ms
     Changes:   
    Warnings: Failed to detect changes to file: Failed to read /etc/resolv.conf:
              No such file or directory
```

it's doing something very weird, since the file is still symlinked to the `systemd-resolved` file:

```
# ls -l /etc/resolv.conf 
lrwxrwxrwx 1 root root 39 Feb  1 00:14 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf
```

**Comment by Stogas** [comment]
Also affected by this, in 3004.2 - however, it's returning "True" in my case (because the target symlinked file contains the same content as what I want to apply).

```
# ls -lh /etc/mysql/my.cnf
lrwxrwxrwx 1 mysql mysql 24 Aug 25 13:54 /etc/mysql/my.cnf -> /etc/alternatives/my.cnf
```

```yaml
mysql_conf:
  file.managed:
    - name: /etc/mysql/my.cnf
    - source: salt://mysql/files/my.cnf.j2
    - user: mysql
    - group: mysql
    - follow_symlinks: False
    - template: jinja
```

```
          ID: mysql_conf
    Function: file.managed
        Name: /etc/mysql/my.cnf
      Result: True
     Comment: The file /etc/mysql/my.cnf is in the correct state
     Started: 10:11:07.755610
    Duration: 39.127 ms
     Changes:
```

Overall this behavior seems a bit backwards to me - the expected behaviour should be a deletion of the symlink and replacing it with a managed file. If this is not applicable for default behavior - set an option flag for this.

At the very least, Salt should definitely not report that the file is in the correct state, or try to modify the file the symlink points to - it should fail with False.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.27
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-9-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```

</details>
