### ISSUE TITLE
Custom extension module not loaded by orchestrate runner

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#31849]
### Description of Issue

I have a custom execution module in my master's `module_dirs` directory, but that execution module does not appear to be loaded by the orchestrate runner.  This causes `salt-run` to print an error:

```
[ERROR   ] Rendering exception occurred: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'roles'
[ERROR   ] Pillar rendering failed for minion saltmaster_master:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 313, in get_tops
    _pillar_rend=True
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/jinja.py", line 333, in render
    **kws)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 384, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'roles'
[CRITICAL] Pillar render error: Rendering Primary Top file failed, render error:
Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'roles'
```

This issue seems similar to #30296 but I'm not sure.
### Setup

The master is configured as follows:
- `/etc/salt/master`:
  
  ``` yaml
  file_roots:
    base:
      - /salt/base/states
  pillar_roots:
    base:
      - /salt/base/pillar
  module_dirs:
    - salt/modules
  ```
- `/salt/modules/modules/roles.py` is a symlink to `/salt/base/states/_modules/roles.py`
- `/salt/base/states/_modules/roles.py`:
  
  ``` python
  def get(id):
      if id == 'foo':
          return ('webserver',)
      return ()
  ```
- `/salt/base/pillar/top.sls`:
  
  ``` yaml
  base:
    '*':
      - stuff
  {% if 'webserver' in salt.roles.get(grains.id) %}
      - webserver
  {% endif %}
  ```
- `/salt/base/states/orchestrate/init.sls`:
  
  ``` yaml
  highstate_everything:
    salt.state:
      - tgt: '*'
      - highstate: True
  ```
### Steps to Reproduce Issue

Configure as described above and run:

```
sudo salt-run state.orchestrate orchestrate
```
### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-30-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@rhansen, thanks for reporting.

**Comment by AlexanderThaller** [comment]
I have the same issue with using our custom modules in pillar files:

```
2016-07-12 11:45:45,040 [salt.pillar                                                     ][CRITICAL][6864] Rendering SLS 'network.backbone' failed, render error:
Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'trivago_utils.get_ip'
2016-07-12 11:45:45,040 [salt.pillar                                                     ][CRITICAL][6864] Pillar render error: Rendering SLS 'network.backbone' failed. Please see master log for details.
```

```
{% set backbone_ip = salt['trivago_utils.get_ip']('backbone') -%}
{% set backbone_interface = salt['trivago_utils.get_interface_name']('backbone') -%}

network:
  {{ backbone_interface }}:
    ip: '{{ backbone_ip }}'
    netmask: '255.255.240.0'
    gateway: '10.0.0.1'
```

```
root@dco:/appdata/salt/log # salt-master --versions-report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  5 2016, 01:21:33)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
 
System Versions:
           dist:   
        machine: amd64
        release: 10.3-RELEASE-p4
         system: FreeBSD
        version: Not Installed
```

```
root@dco-saltstack-debian-dev:~# salt-minion --versions-report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
```
