### ISSUE TITLE
win_pkg:  pkg.upgrade no error message from master for unsupported feature

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#31889]
### Description of Issue/Question

```
salt -l info server  pkg.upgrade thepackage
server:
    ----------
```

vs

``````
C:\salt>salt-call.bat pkg.upgrade thepackage
[WARNING ] pkg.upgrade not implemented on Windows yet
local
```:
    ----------
``````

The other issue is the doco do not say its not implemented yet.
i.e. I did "salt server  sys.doc pkg"   to make sure I could do it, before I spent time trying to do it.
### Versions Report

_Provided by running_ `salt --versions-report`

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 8.1
         system: 8.1 6.3.9600  Multiprocessor Free
```
