### ISSUE TITLE
boto_route53.present fails when a CNAME has 'identifier'

### ISSUE THREAD

**Issue by saravanakumar-periyasamy** [saltstack/salt#31899]
### Description of Issue/Question
boto_route53.present state fails when a CNAME has 'identifier'

```
----------
          ID: private-dns-name-CNAME-record
    Function: boto_route53.present
        Name: sara-salt.xxxx.com.
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_route53.py", line 197, in present
                  if identifier and identifier != record['identifier']:
              KeyError: 'identifier'
     Started: 16:03:24.972572
    Duration: 86.23 ms
     Changes:
```
### Setup

Hers is the state file that I use

```
private-dns-name-CNAME-record:
  boto_route53.present:
    - name: {{ grains['private_dns_name'] }}.{{ salt['pillar.get']('common:route53:domains:default:name', 'xxxx.com') }}.
    - value: {{ grains['id'] }}.{{ salt['pillar.get']('common:route53:domains:default:name', 'xxxx.com') }}.
    - zone: {{ salt['pillar.get']('common:route53:domains:default:name', 'xxxx.com') }}.
    - ttl: 60
    - record_type: CNAME
    - identifier:
      - {{ grains['ec2']['instance_id'] }}
      - '1'
    - wait_for_sync: {{ salt['pillar.get']('common:route53:wait_for_sync', True) }}
    - split_dns: {{ salt['pillar.get']('common:route53:split_dns', False) }}
    - private_zone: True
```

### Steps to Reproduce Issue

When I run the above state for first time, it works fine, it creates a CNAME with identifier. But when I try to run the state again, it errors out with the above error.

### Versions Report
```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.6
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Ubuntu 14.04 trusty
```
