### ISSUE TITLE
Feature request: support timezones in cron.present

### ISSUE THREAD

**Issue by bagratte** [saltstack/salt#31891]
Example:

``` SaltStack
date > /tmp/crontest:
  cron.present:
    - user: root
    - minute: '*/5'
    - timezone: America/Denver
```

I imagine this would prepend a CRON_TZ='America/Denver' to the crontab entry and append a CRON_TZ="" to it, like so:

```
CRON_TZ='America/Denver'
*/5 * * * * date > /tmp/crontest
CRON_TZ=""
```

Note that this is different from `cron.env_present` which sets environment for the entire crontab. What this request aims to accomplish is having a crontab in multiple timezones, like this one:

```
CRON_TZ='America/Denver'
7 3 * * * date >> /home/bagratte/denver
CRON_TZ='Asia/Yerevan'
8 13 * * * date >> /home/bagratte/yerevan
CRON_TZ='America/Chicago'
9 4 * * * date >> /home/bagratte/chicago
CRON_TZ=""
10 13 * * * date >> /home/bagratte/none
```

I don't know if all variants or versions of cron support this but mine (cronie.x86_64 1.4.11-14.el7 @ base on CentOS Linux release 7.2.1511 (Core)) does.

Thanks.

**Comment by jfindlay** [comment]
@bagratte, thanks for reporting.

**Comment by brettspeaks** [comment]
Is there an eta on when this will be implemented?

**Comment by aboe76** [comment]
wouldn't it be a better idea to have an cron.env_present ability per cron entry,
so not only CRON_TZ but MAILTO is also possbile with multiple entries:
per example:
```
date > /tmp/crontest:
  cron.present:
    - user: root
    - minute: '*/5'
    - env: 
        - CRON_TZ='America/Denver'
        - MAILTO='root@example.com'
```
