### ISSUE TITLE
Package is not assumed as needed to update while revision is incremented

### ISSUE THREAD

**Issue by mallniya** [saltstack/salt#31923]
### Description of Issue/Question
Situation is pretty simple:
on target host loader02 there is following version of package:
```
[root@loader02 ~]# pkg info -E hive
hive-1.2.1_14
```
Version 1.2.1, revision 14. At the same time newer package is available:
```
[root@loader02 ~]# pkg search -x hive-1.2
hive-1.2.1_15
hive-1.2.1_1
```
Version 1.2.1, revision 15, i.e. more recent.
So if I run `sudo salt loader02.profile.rambler.ru state.apply packages saltenv=production test=true` I naturally expect this package to be updated. But it's not and this is a problem. With incrementing package version (instead of revision) there are no problems.

### Versions Report
```
[root@loader02 ~]# salt --versions-report
Salt Version:
           Salt: 2015.8.5
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.7.9 (default, Apr 27 2015, 11:42:05)
           RAET: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.5
           cffi: 1.1.1
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: amd64
        release: 10.0-STABLE-r265437
```
