### ISSUE TITLE
Compile error if trying to match against a non-existing custom grain (list ?)

### ISSUE THREAD

**Issue by MoonSweep** [saltstack/salt#31936]
I have this test in one of my sls file:

````sls
include:
  - recipes.procps
  {% if 'thinkpad' in grains['roles'] and grains['osrelease'] < '8' %}
  - recipes.apt-preferences-backports-kernel
  {% endif %}
  - hooks.update-grub
````

This sls file is triggered by a simple grain match (on os:Debian) in top.sls:

````sls
  # Debian -- Basic config
  'os:Debian':
    - match: grain
    - recipes.apt-sources-debian-official
    - recipes.salt-latest
    - recipes.debian-basic
````

I tried to execute highstate on a new host before setting any roles (so the "roles" grains list doesn't exist yet on this host), and expected my basic Debian highstate to be run (most of the other matches in top.sls are based on roles), but I get this error on the master:

````
    Data failed to compile:
----------
    Rendering SLS 'base:recipes.debian-basic' failed: Jinja error: argument of type 'StrictUndefined' is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 306, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "<template>", line 7, in top-level template code
TypeError: argument of type 'StrictUndefined' is not iterable

; line 7

---
[...]
# Debian basic configuration
#

include:
  - recipes.procps
  {% if 'thinkpad' in grains['roles'] and grains['osrelease'] < '8' %}    <======================
  - recipes.apt-preferences-backports-kernel
  {% endif %}
  - hooks.update-grub


[...]
---
````

Even more disturbing (maybe I should have reported two separate bugs, feel free to duplicate and rename if you think it's necessary) is that **Salt still chokes if those three lines are commented out** !

Only by removing the match on the "roles" grain (or removing the whole test) did the highstate run without error.

Of course, this test works without error on hosts where the "roles" grains list exists.

Salt master version:
````yaml
                   Salt: 2015.5.3
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1~bpo8+1
````

Salt minion version:
````yaml
                  Salt: 2015.5.3
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1~bpo70+2
````
