### ISSUE TITLE
Documentation for salt.states.cron is incorrect

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#31953]
### Description of Issue/Question
https://docs.saltstack.com/en/develop/ref/states/all/salt.states.cron.html
The mentioned examples for special do not work. Resulting in:

```
network.route::lx-helper:
  file.directory:
    - name: /etc/inet
  cron.present:
    - name: /native/usr/bin/awk '!/^($|[:space:]*#)/{ print "/native/usr/sbin/route add "$0 }' /etc/inet/static_routes | sh
    - special: @reboot    <======================
```
**Adding ' around @reboot make it work fine.**

### Setup
n/a

### Steps to Reproduce Issue
```yaml
doc_test_example:
  cron.present:
    - name: echo hello
    - special: @reboot
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.0rc1-1165-g1b65b48

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 13.1.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 3.2.2
           cffi: Not Installed
       cherrypy: 5.1.0
       dateutil: 2.5.0
          gitdb: 0.6.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: 0.9.0
        timelib: 0.2.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
