### ISSUE TITLE
salt.states.cron.present always shows change with test=True

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#31965]
### Description of Issue/Question

``` bash
[root@cronos /salt]# salt 'testc' state.highstate
testc:
  Name: /salt/config/minion - Function: file.managed - Result: Clean
  Name: salt-minion - Function: service.running - Result: Clean
  Name: /usr/local/bin/salt-call - Function: file.symlink - Result: Clean
  Name: salt.minion::schedule-highstate - Function: schedule.present - Result: Clean
  Name: zsh - Function: pkg.installed - Result: Clean
  Name: bash - Function: pkg.installed - Result: Clean
  Name: root - Function: user.present - Result: Clean
  Name: sysadmin - Function: group.present - Result: Clean
  Name: user - Function: group.present - Result: Clean
  Name: service - Function: group.present - Result: Clean
  Name: sudo - Function: pkg.installed - Result: Clean
  Name: sjorge - Function: user.present - Result: Clean
  Name: AAAAB3NzaC1yc2EAAAABIwAAAQEA7st+KRfqBdNGhyEDBxzssIv9xVH7yl5fMOUVHLk1VTmpOyCpYi/+yI2QsMIdndFqWK7rM4xgCK+osKP2kj/edy7FTzi78c6vP3Jli+Dt17ZgC/CxlEReJe+o0/l1tdWbl+kg9nB0DtGMSvntFcIdQmn5ZiPOzGrLKvI9Tngt0BWLrYXlQzBkq65MBbizoxkErR4nHppt9mLeTR9ZY6YsRi2roVVNUJWKat/RvC6ncPs4+Mpy56330MA+40cGlFFlucQnlzIx6ghey13P+RdZYuexJP6JunyZOntCcieahNJ+FklCEeeVChhjO0tFtioz49udCEOxo9kmfDUOiqi61w== - Function: ssh_auth.present - Result: Clean
  Name: /etc/sudoers.d/sjorge - Function: file.managed - Result: Clean
  Name: /home/sjorge - Function: archive.extracted - Result: Clean
  Name: /home/sjorge/.salt/profile-base - Function: file.managed - Result: Clean
  Name: /home/sjorge - Function: archive.extracted - Result: Clean
  Name: /home/sjorge/.salt/profile-shell - Function: file.managed - Result: Clean
  Name: /home/sjorge - Function: archive.extracted - Result: Clean
  Name: /home/sjorge/.salt/profile-user - Function: file.managed - Result: Clean
  Name: nl_BE.UTF-8 - Function: locale.present - Result: Clean
  Name: en_US.UTF-8 - Function: locale.present - Result: Clean
  Name: en_US.UTF-8 - Function: locale.system - Result: Clean
  Name: /etc/resolv.conf - Function: file.managed - Result: Clean
  Name: /etc/hosts - Function: file.managed - Result: Clean
  Name: /etc/inet - Function: file.directory - Result: Clean
  Name: /native/usr/bin/awk '!/^($|[:space:]*#)/{ print "/native/usr/sbin/route add "$0 }' /etc/inet/static_routes | sh - Function: cron.present - Result: Clean
  Name: /native/usr/sbin/route -p add -inet 0.0.0.0/0 172.16.10.1 -ifp eth0 -static - Function: cmd.run - Result: Clean
  Name: /native/usr/sbin/route -p add -inet6 ::/0 2001:6f8:1480:10::1 -ifp eth0 -static - Function: cmd.run - Result: Clean
  Name: tmux - Function: pkg.installed - Result: Clean
  Name: package::schedule-upgrade - Function: schedule.present - Result: Clean
  Name: /etc/motd - Function: file.managed - Result: Clean
  Name: /etc/profile.d/motd.sh - Function: file.managed - Result: Clean
  Name: Europe/Brussels - Function: timezone.system - Result: Clean
  Name: time::ntp_servers - Function: test.show_notification - Result: Clean
  Name: ntpd - Function: service.dead - Result: Clean
  Name: openssh-server - Function: pkg.installed - Result: Clean
  Name: ssh:keys:rsa - Function: grains.present - Result: Clean
  Name: ssh:keys:ecdsa - Function: grains.present - Result: Clean
  Name: ssh:keys:ed25519 - Function: grains.present - Result: Clean
  Name: /etc/ssh/sshd_config - Function: file.managed - Result: Clean
  Name: sshd - Function: service.running - Result: Clean

Summary for testc
-------------
Succeeded: 42
Failed:     0
-------------
Total states run:     42
```

``` bash
[root@cronos /salt]# salt 'testc' state.highstate test=True
testc:
  Name: /salt/config/minion - Function: file.managed - Result: Clean
  Name: salt-minion - Function: service.running - Result: Clean
  Name: /usr/local/bin/salt-call - Function: file.symlink - Result: Clean
  Name: salt.minion::schedule-highstate - Function: schedule.present - Result: Clean
  Name: zsh - Function: pkg.installed - Result: Clean
  Name: bash - Function: pkg.installed - Result: Clean
  Name: root - Function: user.present - Result: Clean
  Name: sysadmin - Function: group.present - Result: Clean
  Name: user - Function: group.present - Result: Clean
  Name: service - Function: group.present - Result: Clean
  Name: sudo - Function: pkg.installed - Result: Clean
  Name: sjorge - Function: user.present - Result: Clean
  Name: AAAAB3NzaC1yc2EAAAABIwAAAQEA7st+KRfqBdNGhyEDBxzssIv9xVH7yl5fMOUVHLk1VTmpOyCpYi/+yI2QsMIdndFqWK7rM4xgCK+osKP2kj/edy7FTzi78c6vP3Jli+Dt17ZgC/CxlEReJe+o0/l1tdWbl+kg9nB0DtGMSvntFcIdQmn5ZiPOzGrLKvI9Tngt0BWLrYXlQzBkq65MBbizoxkErR4nHppt9mLeTR9ZY6YsRi2roVVNUJWKat/RvC6ncPs4+Mpy56330MA+40cGlFFlucQnlzIx6ghey13P+RdZYuexJP6JunyZOntCcieahNJ+FklCEeeVChhjO0tFtioz49udCEOxo9kmfDUOiqi61w== - Function: ssh_auth.present - Result: Clean
  Name: /etc/sudoers.d/sjorge - Function: file.managed - Result: Clean
  Name: /home/sjorge - Function: archive.extracted - Result: Clean
  Name: /home/sjorge/.salt/profile-base - Function: file.managed - Result: Clean
  Name: /home/sjorge - Function: archive.extracted - Result: Clean
  Name: /home/sjorge/.salt/profile-shell - Function: file.managed - Result: Clean
  Name: /home/sjorge - Function: archive.extracted - Result: Clean
  Name: /home/sjorge/.salt/profile-user - Function: file.managed - Result: Clean
  Name: nl_BE.UTF-8 - Function: locale.present - Result: Clean
  Name: en_US.UTF-8 - Function: locale.present - Result: Clean
  Name: en_US.UTF-8 - Function: locale.system - Result: Clean
  Name: /etc/resolv.conf - Function: file.managed - Result: Clean
  Name: /etc/hosts - Function: file.managed - Result: Clean
  Name: /etc/inet - Function: file.directory - Result: Clean
----------
          ID: network.route::lx-helper
    Function: cron.present
        Name: /native/usr/bin/awk '!/^($|[:space:]*#)/{ print "/native/usr/sbin/route add "$0 }' /etc/inet/static_routes | sh
      Result: None
     Comment: Cron /native/usr/bin/awk '!/^($|[:space:]*#)/{ print "/native/usr/sbin/route add "$0 }' /etc/inet/static_routes | sh is set to be added
     Started: 22:13:23.709585
    Duration: 72.045 ms
     Changes:
  Name: /native/usr/sbin/route -p add -inet 0.0.0.0/0 172.16.10.1 -ifp eth0 -static - Function: cmd.run - Result: Clean
  Name: /native/usr/sbin/route -p add -inet6 ::/0 2001:6f8:1480:10::1 -ifp eth0 -static - Function: cmd.run - Result: Clean
  Name: tmux - Function: pkg.installed - Result: Clean
  Name: package::schedule-upgrade - Function: schedule.present - Result: Clean
  Name: /etc/motd - Function: file.managed - Result: Clean
  Name: /etc/profile.d/motd.sh - Function: file.managed - Result: Clean
  Name: Europe/Brussels - Function: timezone.system - Result: Clean
  Name: time::ntp_servers - Function: test.show_notification - Result: Clean
  Name: ntpd - Function: service.dead - Result: Clean
  Name: openssh-server - Function: pkg.installed - Result: Clean
  Name: ssh:keys:rsa - Function: grains.present - Result: Clean
  Name: ssh:keys:ecdsa - Function: grains.present - Result: Clean
  Name: ssh:keys:ed25519 - Function: grains.present - Result: Clean
  Name: /etc/ssh/sshd_config - Function: file.managed - Result: Clean
  Name: sshd - Function: service.running - Result: Clean

Summary for testc
-------------
Succeeded: 42 (unchanged=1)
Failed:     0
-------------
Total states run:     42
```
### Setup

n/a
### Steps to Reproduce Issue

``` yaml
DEBUG:
  cron.present:
    - name: /native/usr/bin/awk '!/^($|[:space:]*#)/{ print "/native/usr/sbin/route add "$0 }' /etc/inet/static_routes | sh
    - special: '@reboot'
```
### Versions Report

``` yaml
Salt Version:
           Salt: 2016.3.0rc1-84-gc28fc6e

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 13.1.0
         Python: 2.7.11 (default, Mar  1 2016, 16:12:00)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 3.2.2
           cffi: Not Installed
       cherrypy: 5.1.0
       dateutil: 2.5.0
          gitdb: 0.6.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: 0.9.0
        timelib: 0.2.4

System Versions:
           dist:
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
