### ISSUE TITLE
SaltStack dockerng.running state ports configuration responding to Docker's injection of UDP params

### ISSUE THREAD

**Issue by timcharper** [saltstack/salt#32013]
### Description of Issue/Question

Applying the following config to state `dockerng.running` never succeeds, because Docker is adding ports.

### Setup

This is the state I'm applying:

```yaml
{% set peers = [{"peer2": "172.168.1.52"}, {"peer3": "172.168.1.53"}, {"peer4": "172.168.1.54"}, {"peer5": "172.168.1.55"}] %}
consul-data:
  dockerng.volume_present:
    - driver: local
consul:
  dockerng.running:
    - image: voxxit/consul:latest
    - port_bindings:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "53:53/udp"
    - command: agent -data-dir /data -server -advertise {{private_ip}} -bootstrap-expect {{"%i" % ((peers | length) / 2 + 1)}} -retry-interval 10s -node consul{{grains.local_idx}} -domain staging -client 0.0.0.0 -bind 0.0.0.0 -ui
        {%- for minion_id, ip in peers.items() | sort %}
        {%- if minion_id != grains.id %} -retry-join {{ip}}
        {%- endif %}
        {%- endfor %}
    - binds:
        - consul-data:/data
```

I've added debug code; the create_container call params are as follows (I did some debug output):

```json
[
  "create_container",
  "consul",
  "voxxit/consul:latest",
  {
    "host_config": {
      "Binds": ["consul-data:/data:rw"],
      "PortBindings": {
        "8301/udp": [{"HostPort": "8301", "HostIp": ""}],
        "8500/tcp": [{"HostPort": "8500", "HostIp": ""}],
        "8301/tcp": [{"HostPort": "8301", "HostIp": ""}],
        "8302/udp": [{"HostPort": "8302", "HostIp": ""}],
        "8302/tcp": [{"HostPort": "8302", "HostIp": ""}],
        "8300/tcp": [{"HostPort": "8300", "HostIp": ""}],
        "8400/tcp": [{"HostPort": "8400", "HostIp": ""}],
        "53/udp":   [{"HostPort": "53",   "HostIp": ""}
        ]
      },
      "NetworkMode": "default"
    },
    "command": ["agent", "-data-dir", "/data", "-server", "-advertise", "172.168.1.51", "-bootstrap-expect", "3", "-retry-interval", "10s", "-node", "consul43", "-domain", "staging", "-client", "0.0.0.0", "-bind", "0.0.0.0", "-ui", "-retry-join", "172.168.1.52", "-retry-join", "172.168.1.53", "-retry-join", "172.168.1.54", "-retry-join", "172.168.1.55"],
    "volumes": ["/data"],
    "ports": ["8301/udp", 8300, 8301, 8302, "8302/udp", 8400, 8500, "53/udp"]
  }
]
```

This succeeds. However, the next time around, when we apply the state again, the inspect docker API call returns:

```
{
  "ExecIDs": null,
  "State": {"Status": "running", "Pid": 95269, "OOMKilled": false, "Dead": false, "Paused": false, "Running": true, "FinishedAt": "0001-01-01T00:00:00Z", "Restarting": false, "Error": "", "StartedAt": "2016-03-21T06:27:56.169581031Z", "ExitCode": 0},
  "Config": {
    "Tty": false,
    "Cmd": ["agent", "-data-dir", "/data", "-server", "-advertise", "172.168.1.51", "-bootstrap-expect", "3", "-retry-interval", "10s", "-node", "consul43", "-domain", "staging", "-client", "0.0.0.0", "-bind", "0.0.0.0", "-ui", "-retry-join", "172.168.1.52", "-retry-join", "172.168.1.53", "-retry-join", "172.168.1.54", "-retry-join", "172.168.1.55"],
    "Volumes": {
      "/data": {}
    },
    "Domainname": "",
    "WorkingDir": "",
    "Image": "voxxit/consul:latest",
    "Hostname": "b4816e144fe5",
    "StdinOnce": false,
    "Labels": {},
    "AttachStdin": false,
    "User": "",
    "Env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "CONSUL_VERSION=0.6.3"
    ],
    "ExposedPorts": {
      "8302/udp/tcp": {},
      "8301/udp": {},
      "8500/tcp": {},
      "8600/udp": {},
      "8301/tcp": {},
      "8600/tcp": {},
      "8302/udp": {},
      "8302/tcp": {},
      "53/udp/tcp": {},
      "8300/tcp": {},
      "8400/tcp": {},
      "8301/udp/tcp": {}
    },
    "OnBuild": null,
    "AttachStderr": true,
    "Entrypoint": [
      "/bin/consul"
    ],
    "AttachStdout": true,
    "OpenStdin": false
  },
  "ResolvConfPath": "/var/lib/docker/containers/b4816e144fe515128ba43a850d29924d1ccc7e4e6da2933eb8bb680af0fdad64/resolv.conf",
  "HostsPath": "/var/lib/docker/containers/b4816e144fe515128ba43a850d29924d1ccc7e4e6da2933eb8bb680af0fdad64/hosts",
  "Args": ["agent", "-data-dir", "/data", "-server", "-advertise", "172.168.1.51", "-bootstrap-expect", "3", "-retry-interval", "10s", "-node", "consul43", "-domain", "staging", "-client", "0.0.0.0", "-bind", "0.0.0.0", "-ui", "-retry-join", "172.168.1.52", "-retry-join", "172.168.1.53", "-retry-join", "172.168.1.54", "-retry-join", "172.168.1.55"],
  "Driver": "devicemapper",
  "Path": "/bin/consul",
  "HostnamePath": "/var/lib/docker/containers/b4816e144fe515128ba43a850d29924d1ccc7e4e6da2933eb8bb680af0fdad64/hostname",
  "RestartCount": 0,
  "Name": "/consul",
  "Created": "2016-03-21T06:27:47.958868571Z",
  "GraphDriver": {
    "Data": {
      "DeviceName": "docker-xxx:redacted",
      "DeviceSize": "42949672960",
      "DeviceId": "117"
    },
    "Name": "devicemapper"
  },
  "Mounts": [
    {
      "RW": true,
      "Name": "consul-data",
      "Propagation": "rprivate",
      "Destination": "/data",
      "Driver": "local",
      "Source": "/var/lib/docker/volumes/consul-data/_data",
      "Mode": "rw"
    }
  ],
  "ProcessLabel": "",
  "NetworkSettings": {
    "Bridge": "",
    "Networks": {
      "bridge": {
        "NetworkID": "redacted",
        "MacAddress": "02:42:ac:11:00:02",
        "GlobalIPv6PrefixLen": 0,
        "Links": null,
        "GlobalIPv6Address": "",
        "IPv6Gateway": "",
        "IPAMConfig": null,
        "EndpointID": "redacted",
        "IPPrefixLen": 16,
        "IPAddress": "172.17.0.2",
        "Gateway": "172.17.0.1",
        "Aliases": null
      }
    },
    "SecondaryIPv6Addresses": null,
    "LinkLocalIPv6Address": "",
    "HairpinMode": false,
    "IPv6Gateway": "",
    "SecondaryIPAddresses": null,
    "SandboxID": "redacted",
    "MacAddress": "redacted",
    "GlobalIPv6Address": "",
    "Gateway": "172.17.0.1",
    "LinkLocalIPv6PrefixLen": 0,
    "EndpointID": "redacted",
    "SandboxKey": "redacted",
    "GlobalIPv6PrefixLen": 0,
    "IPPrefixLen": 16,
    "IPAddress": "172.17.0.2",
    "Ports": {
      "8301/tcp": [{"HostPort": "8301", "HostIp": "0.0.0.0"}],
      "8500/tcp": [{"HostPort": "8500", "HostIp": "0.0.0.0"}],
      "8600/udp": null,
      "8301/udp": [{"HostPort": "8301", "HostIp": "0.0.0.0"}],
      "8600/tcp": null,
      "8302/udp": [{"HostPort": "8302", "HostIp": "0.0.0.0"}],
      "8302/tcp": [{"HostPort": "8302", "HostIp": "0.0.0.0"}],
      "8300/tcp": [{"HostPort": "8300", "HostIp": "0.0.0.0"}],
      "8400/tcp": [{"HostPort": "8400", "HostIp": "0.0.0.0"}],
      "53/udp": null
    }
  },
  "AppArmorProfile": "",
  "Image": "sha256:redacted",
  "LogPath": "/var/lib/docker/containers/redacted.log",
  "HostConfig": {
    "CpuPeriod": 0,
    "MemorySwappiness": -1,
    "ContainerIDFile": "",
    "MemorySwap": 0,
    "BlkioDeviceReadIOps": null,
    "CpuQuota": 0,
    "Dns": null,
    "ExtraHosts": null,
    "PidsLimit": 0,
    "DnsSearch": null,
    "Privileged": false,
    "Ulimits": null,
    "CpusetCpus": "",
    "CgroupParent": "",
    "BlkioWeight": 0,
    "RestartPolicy": {
      "MaximumRetryCount": 0,
      "Name": ""
    },
    "OomScoreAdj": 0,
    "BlkioDeviceReadBps": null,
    "VolumeDriver": "",
    "ReadonlyRootfs": false,
    "CpuShares": 0,
    "PublishAllPorts": false,
    "MemoryReservation": 0,
    "BlkioWeightDevice": null,
    "ConsoleSize": [
      0,
      0
    ],
    "NetworkMode": "default",
    "BlkioDeviceWriteBps": null,
    "Isolation": "",
    "GroupAdd": null,
    "Devices": null,
    "BlkioDeviceWriteIOps": null,
    "Binds": [
      "consul-data:/data:rw"
    ],
    "CpusetMems": "",
    "KernelMemory": 0,
    "UTSMode": "",
    "PidMode": "",
    "VolumesFrom": null,
    "CapDrop": null,
    "DnsOptions": null,
    "ShmSize": 67108864,
    "Links": null,
    "IpcMode": "",
    "PortBindings": {
      "8301/tcp": [{"HostPort": "8301", "HostIp": ""}],
      "8500/tcp": [{"HostPort": "8500", "HostIp": ""}],
      "8301/udp": [{"HostPort": "8301", "HostIp": ""}],
      "8302/udp": [{"HostPort": "8302", "HostIp": ""}],
      "8302/tcp": [{"HostPort": "8302", "HostIp": ""}],
      "8300/tcp": [{"HostPort": "8300", "HostIp": ""}],
      "8400/tcp": [{"HostPort": "8400", "HostIp": ""}],
      "53/udp": [{"HostPort": "53", "HostIp": ""}]
    },
    "SecurityOpt": null,
    "CapAdd": null,
    "Memory": 0,
    "OomKillDisable": false,
    "LogConfig": {
      "Config": {},
      "Type": "json-file"
    }
  },
  "Id": "b4816e144fe515128ba43a850d29924d1ccc7e4e6da2933eb8bb680af0fdad64",
  "MountLabel": ""
}
```

Specifically, note `ExposedPorts` `53/udp/tcp`.

When doing the compare,

```
actual_ports = [u'53/udp/tcp', u'8300/tcp', u'8301/tcp', u'8301/udp', u'8301/udp/tcp', u'8302/tcp', u'8302/udp', u'8302/udp/tcp', u'8400/tcp', u'8500/tcp', u'8600/tcp', u'8600/udp']
desired_ports = ['53/udp', '8300/tcp', '8301/tcp', '8301/udp', '8302/tcp', '8302/udp', '8400/tcp', '8500/tcp', u'8600/tcp', u'8600/udp']
```

The ports match, but the actual ports include more protocols (even though the create call didn't request them) than the desired protocols. This causes the compare config routine to detect that the container needs to be reconfigured. Since, on reconfigure, dockerng checks the configuration again to see if it matches now, the reconfigure fails, detecting the same actual / desired ports discrepancy. 

To work around it, I'm going to modify the port check to accept a subset of protocols. I wanted to post details about what I was experiencing, though, first, before attempting a solution.

### Versions Report
```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.4.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

However, manually patching `modules/dockerng.py` and `states/dockerng.py` from latest `2015.8`, `c72ab6a073bffb22e8f377d7b5faf872bce3d6ee`

Using `docker-py` `1.6.0`

**Comment by timcharper** [comment]
Here's my patch to `states/dockerng.py`, which solves my issue:

```diff
@@ -108,6 +108,31 @@ def _prep_input(kwargs):
             if not isinstance(kwargs[kwarg], dict):
                 raise SaltInvocationError(err)

+def _compare_ports(actual_ports, desired_ports):
+    '''
+    Docker has been observed to add additional protocols to exposed ports than
+    those which were explicitly requested. As a workaround, this check asserts
+    that actual_port protocols are a superset of desired, and that ports bound
+    match exactly.
+    '''
+    def list_to_map(ports):
+        h = {}
+        for p in ports:
+            pieces = p.split("/")
+            port, protos = pieces[0], set(pieces[1:])
+            if not port in h:
+                h[port] = protos
+            else:
+                h[port] = h[port] | protos
+        return h
+    actual_ports_map, desired_ports_map = (
+        list_to_map(actual_ports), list_to_map(desired_ports))
+    if set(actual_ports_map.keys()) != set(desired_ports_map.keys()):
+        return False
+    for key in desired_ports_map.keys():
+        if not actual_ports_map[key] >= desired_ports_map[key]:
+            return False
+    return True

 def _compare(actual, create_kwargs, defaults_from_image):
     '''
@@ -213,7 +238,7 @@ def _compare(actual, create_kwargs, defaults_from_image):
                       .format(item, actual_ports))
             log.trace('dockerng.running ({0}): munged desired value: {1}'
                       .format(item, desired_ports))
-            if actual_ports != desired_ports:
+            if not _compare_ports(actual_ports, desired_ports):
                 ret.update({item: {'old': actual_ports,
                                    'new': desired_ports}})
             continue
```

**Comment by ticosax** [comment]
Hi @timcharper, please can you output the result of `dockerng.inspect_image <your_image> --output=json`

**Comment by timcharper** [comment]
Sure

`salt-call dockerng.inspect_image voxxit/consul --output=json`

```json
{
    "local": {
        "Comment": "",
        "Container": "69cb015a430ce7717560ffdf378631748ad316f88a64b94c5025176cf1ecb011",
        "DockerVersion": "1.10.2",
        "Parent": "",
        "Created": "2016-03-18T20:52:58.201276932Z",
        "Config": {
            "Tty": false,
            "Cmd": [
                "agent",
                "-data-dir",
                "/data"
            ],
            "Volumes": {
                "/data": {}
            },
            "Domainname": "",
            "WorkingDir": "",
            "Image": "sha256:0d8ffd30c8def986840f4a61bca7879f725a5d4926ea46fd3d4b5f5ed6e84b53",
            "Hostname": "1c5d9370391d",
            "StdinOnce": false,
            "ArgsEscaped": true,
            "Labels": {},
            "AttachStdin": false,
            "User": "",
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CONSUL_VERSION=0.6.3"
            ],
            "ExposedPorts": {
                "8301/tcp": {},
                "8500/tcp": {},
                "8600/udp": {},
                "8301/udp": {},
                "8600/tcp": {},
                "8302/udp": {},
                "8302/tcp": {},
                "8300/tcp": {},
                "8400/tcp": {}
            },
            "OnBuild": [],
            "AttachStderr": false,
            "Entrypoint": [
                "/bin/consul"
            ],
            "AttachStdout": false,
            "OpenStdin": false
        },
        "Author": "",
        "VirtualSize_Human": "32.6 MiB",
        "GraphDriver": {
            "Data": {
                "DeviceName": "docker-253:0-449439-5dcbca6e9cb0be3e6de4e18a11405780e16b29f6fb33bb6e05b6cfcfdd4043e7",
                "DeviceSize": "42949672960",
                "DeviceId": "7"
            },
            "Name": "devicemapper"
        },
        "VirtualSize": 34171761,
        "Size_Human": "32.6 MiB",
        "Os": "linux",
        "Architecture": "amd64",
        "ContainerConfig": {
            "Tty": false,
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) CMD [\"agent\" \"-data-dir\" \"/data\"]"
            ],
            "Volumes": {
                "/data": {}
            },
            "Domainname": "",
            "WorkingDir": "",
            "Image": "sha256:0d8ffd30c8def986840f4a61bca7879f725a5d4926ea46fd3d4b5f5ed6e84b53",
            "Hostname": "1c5d9370391d",
            "StdinOnce": false,
            "ArgsEscaped": true,
            "Labels": {},
            "AttachStdin": false,
            "User": "",
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CONSUL_VERSION=0.6.3"
            ],
            "ExposedPorts": {
                "8301/tcp": {},
                "8500/tcp": {},
                "8600/udp": {},
                "8301/udp": {},
                "8600/tcp": {},
                "8302/udp": {},
                "8302/tcp": {},
                "8300/tcp": {},
                "8400/tcp": {}
            },
            "OnBuild": [],
            "AttachStderr": false,
            "Entrypoint": [
                "/bin/consul"
            ],
            "AttachStdout": false,
            "OpenStdin": false
        },
        "Size": 34171761,
        "RepoDigests": [],
        "Id": "sha256:f2822692c7b9353ce7590c29a2cfcdf267afeb86f65380e1963127603185176f",
        "RepoTags": [
            "voxxit/consul:latest"
        ]
    }
}
```

**Comment by ticosax** [comment]
I found the culprit.
docker-py API is not consistent.
While for `port_bindings` you can pass
```python
'53/udp'
```
for `ports` it has to be 

```python
(53, 'udp')
```

[reference](https://docker-py.readthedocs.org/en/latest/port-bindings/)

**Comment by timcharper** [comment]
@ticosax great work! I'll pull your patch and try it out.

**Comment by timcharper** [comment]
@ticosax I've verified that your patch fixes my issue. Wonderful work.

**Comment by timcharper** [comment]
If anyone else would like to patch their minion with @ticosax's change, you can apply this salt formula:

```yaml
{% if grains.saltversion == "2015.8.7" %}
rename-away:
  cmd.run:
    - name: |
        mv /usr/lib/python2.7/site-packages/salt/modules/dockerng.pyc /usr/lib/python2.7/site-packages/salt/modules/dockerng.pyc.bak
        mv /usr/lib/python2.7/site-packages/salt/modules/dockerng.py /usr/lib/python2.7/site-packages/salt/modules/dockerng.py.bak
        mv /usr/lib/python2.7/site-packages/salt/modules/dockerng.pyo /usr/lib/python2.7/site-packages/salt/modules/dockerng.pyo.bak
        mv /usr/lib/python2.7/site-packages/salt/states/dockerng.pyc /usr/lib/python2.7/site-packages/salt/states/dockerng.pyc.bak
        mv /usr/lib/python2.7/site-packages/salt/states/dockerng.py /usr/lib/python2.7/site-packages/salt/states/dockerng.py.bak
        mv /usr/lib/python2.7/site-packages/salt/states/dockerng.pyo /usr/lib/python2.7/site-packages/salt/states/dockerng.pyo.bak
    - unless: "[ -f /usr/lib/python2.7/site-packages/salt/modules/dockerng.py.bak ]"
    - watch_in:
      - cmd: restart-minion

{% for f, md5 in [("modules/dockerng.py", "87ecc7eb1780f10731f88eff9345367f"), ("states/dockerng.py", "08e97a23decfd65eae81bf60e88a3d11")] %}
/usr/lib/python2.7/site-packages/salt/{{f}}:
  file.managed:
    - source: https://raw.githubusercontent.com/ticosax/salt/e511864a553d34d5e7e07a474c2127ca96264e8a/salt/{{f}}
    - source_hash: md5={{md5}}
    - watch_in:
      - cmd: restart-minion
    - require:
      - cmd: rename-away
{% endfor %}

restart-minion:
  cmd.wait_script:
    - name: |
        #!/bin/bash

        # Restarting saltstack on minions is difficult, and sometimes we'll have
        # multiple minions running on the same node, resulting in undefined behavior.
        # This script safetly restarts them in a way that only one minion instance will
        # win, and will kill all salt-minion processes, starting a single one

        # To run:
        # salt 'target' cmd.script source=salt://assets/restart-salt.sh runas=root
        restart() {
          printf "%d" "$$" > /tmp/restart-pid
          sleep 2
          if [ "$(cat /tmp/restart-pid)" == "$$" ]; then
            echo $$ won the race
            ps aux | grep salt-minion | awk '{print $2}' | xargs kill
            service salt-minion restart
          else
            echo $$ lost the race
          fi
        }

        restart 1>> /tmp/restart-output 2>> /tmp/restart-output &
{% endif %}
```
