### ISSUE TITLE
x509.certificate_managed throws exception on 2016.3

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#32032]
### Description of Issue/Question
```yaml
cronos:
  Name: /salt/pki/certificates - Function: file.directory - Result: Clean
  Name: /salt/pki/certificates/issued/ - Function: file.directory - Result: Clean
  Name: /salt/pki/certificates/ca.key - Function: x509.private_key_managed - Result: Clean
----------
          ID: certificate.authority::crt
    Function: x509.certificate_managed
        Name: /salt/pki/certificates/ca.crt
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python2.7/site-packages/salt/state.py", line 1703, in call
                  **cdata['kwargs'])
                File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 1607, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python2.7/site-packages/salt/states/x509.py", line 429, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/opt/salt/lib/python2.7/site-packages/salt/modules/x509.py", line 1150, in create_certificate
                  cert.set_pubkey(get_public_key(kwargs['public_key'], asObj=True))
                File "/opt/salt/lib/python2.7/site-packages/salt/modules/x509.py", line 562, in get_public_key
                  text = get_pem_entry(text)
                File "/opt/salt/lib/python2.7/site-packages/salt/modules/x509.py", line 355, in get_pem_entry
                  raise salt.exceptions.SaltInvocationError('PEM text not valid:\n{0}'.format(text))
              SaltInvocationError: PEM text not valid:
              /etc/pki/ca.key
     Started: 21:59:31.539812
    Duration: 8.169 ms
     Changes:
----------
          ID: mine.send
    Function: module.run
      Result: False
     Comment: One or more requisite failed: role.certificate.authority.certificate.authority::crt
     Started:
    Duration:
     Changes:

Summary for cronos
------------
Succeeded: 3
Failed:    2
------------
Total states run:     5
```

### Setup
```yaml
## manage policies
certificate.authority::policies:
  file.managed:
    - name: {{ saltcfg['prefix'] }}/minion.d/signing_policies.conf
    - template: jinja
    - source: salt://role/certificate/_files/signing_policies.conf
    - context:
        saltcfg: {{ saltcfg }}
        certcfg: {{ certcfg }}

## manage directories
certificate.authority::directories:
  file.directory:
    - names:
        - {{ certcfg['authority_dir'] }}
        - {{ certcfg['authority_dir'] }}/issued/
    - user: root
    - group: nacl
    - dir_mode: 0770

## manage ca key
certificate.authority::key:
  x509.private_key_managed:
    - name: {{ certcfg['authority_dir'] }}/ca.key
    - bits: 4096
    - backup: True
    - require:
      - file: certificate.authority::directories

## manage ca certificate
certificate.authority::crt:
  x509.certificate_managed:
    - name: {{ certcfg['authority_dir'] }}/ca.crt
    - signing_private_key: /etc/pki/ca.key
    - CN: ca.acheron.be
    - C: BE
    - ST: Antwerp
    - L: Kapellen
    - E: certadm@acheron.be
    - basicConstraints: "critical CA:true"
    - keyUsage: "critical cRLSign, keyCertSign"
    - subjectKeyIdentifier: hash
    - authorityKeyIdentifier: keyid,issuer:always
    - days_valid: 3650
    - days_remaining: 0
    - backup: True
    - require:
      - x509: certificate.authority::key
```

### Steps to Reproduce Issue
salt x state.sls ca

### Versions Report
```yaml
Salt Version:
           Salt: 2016.3.0rc1-96-gfe86a3d

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.11 (default, Mar 18 2016, 13:38:08)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: Not Installed
       cherrypy: 3.8.0
       dateutil: 2.4.0
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: 0.9.0
        timelib: 0.2.4

System Versions:
           dist:
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
