### ISSUE TITLE
win_iis.create_site, create_apppool, and remove_apppool are all failing

### ISSUE THREAD

**Issue by m03** [saltstack/salt#32049]
### Description of Issue/Question
Several of the functions for the win_iis module in develop (win_iis.create_site, win_iis.create_apppool, and win_iis.remove_apppool) fail to function correctly.

### Setup
Existing IIS config consisting of no sites, and a few default and test application pools:
```
m03@devmaster01:~$ sudo salt 'win-minion' win_iis.list_sites
win-minion:
m03@devmaster01:~$ sudo salt 'win-minion' win_iis.list_apppools
win-minion:
    .NET v2.0
    .NET v2.0 Classic
    .NET v4.5
    .NET v4.5 Classic
    Classic .NET AppPool
    Test1
m03@devmaster01:~$ sudo salt 'win-minion' file.directory_exists 'C:\\inetpub\\mvcforum'
win-minion:
    True
```
### Steps to Reproduce Issue
win_iis.create_site:
```
m03@devmaster01:~$ sudo salt 'win-minion' win_iis.create_site name='mvcforum' protocol='http' sourcepath='C:\\inetpub\\mvcforum' port='80' apppool='Test1'
win-minion:
    \http\ : The term '\http\' is not recognized as the name of a cmdlet, function, script file, or operable program.
    Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    At line:1 char:103
    + ... ngs @{protocol=\'http\';bindingInformation=\':80:\'}-physicalPath C:\\inetpub\\m ...
    +                    ~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (\http\:String) [], CommandNotFoundException
        + FullyQualifiedErrorId : CommandNotFoundException

    Set-ItemProperty : Cannot find drive. A drive with the name '\iis' does not exist.
    At line:1 char:176
    + ... tpub\\mvcforum;Set-ItemProperty \'iis:\Sites\mvcforum\' -name applicationPool -v ...
    +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (\iis:String) [Set-ItemProperty], DriveNotFoundException
        + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCommand
ERROR: Minions returned with non-zero exit code
```
win_iis.create_apppool:
```
m03@devmaster01:~$ sudo salt 'win-minion' win_iis.create_apppool 'Test2'
win-minion:
    New-Item : Cannot find drive. A drive with the name '\IIS' does not exist.
    At line:1 char:34
    + Import-Module WebAdministration; New-Item \'IIS:\AppPools\Test2\'
    +                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (\IIS:String) [New-Item], DriveNotFoundException
        + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.NewItemCommand
ERROR: Minions returned with non-zero exit code
```
win_iis.remove_apppool:
```
m03@devmaster01:~$ sudo salt 'win-minion' win_iis.remove_apppool 'Test1'
win-minion:
    Remove-Item : Cannot find drive. A drive with the name '\IIS' does not exist.
    At line:1 char:34
    + Import-Module WebAdministration; Remove-Item \'IIS:\AppPools\Test1\' -recurse
    +                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (\IIS:String) [Remove-Item], DriveNotFoundException
        + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
ERROR: Minions returned with non-zero exit code
```

### Versions Report
Ubuntu 14.04 master:
```
m03@devmaster01:~$ sudo salt --versions-report
Salt Version:
           Salt: 2016.3.0-242-g5096d33

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
Windows 2012r2 minion:
```
m03@devmaster01:~$ sudo salt 'win-minion' test.versions_report
win-minion:
    Salt Version:
               Salt: 2016.3.0

    Dependency Versions:
             Jinja2: 2.8
           M2Crypto: 0.21.1
               Mako: 1.0.3
             PyYAML: 3.11
              PyZMQ: 15.2.0
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.3
                ZMQ: 4.1.2
               cffi: 1.5.0
           cherrypy: 5.0.1
           dateutil: 2.4.2
              gitdb: 0.6.4
          gitpython: 1.0.1
              ioflo: 1.5.0
            libgit2: Not Installed
            libnacl: 1.4.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.8
              smmap: 0.9.0
            timelib: Not Installed

    System Versions:
               dist:
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
