### ISSUE TITLE
Multiple masters throwing warnings? "Key master with value [...] has an invalid type of list, a str is required for this value"

### ISSUE THREAD

**Issue by ScoreUnder** [saltstack/salt#32044]
### Description of Issue/Question

Multiple-master support is documented here:
https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html

However, in recent versions of salt, a warning is thrown when multiple masters are used:
```
victory:~ root# salt-call saltutil.sync_all
[WARNING ] Key master with value [ ... (list of masters here) ... ] has an invalid type of list, a str is required for this value
```

I don't know if this is indicative of a complete failure though, because our main master is fairly reliable so it's never had a need to fall back to the backup. It does imply at least that specifying multiple masters is an error, which goes against the documentation.

### Setup

In `/etc/salt/minion.d/masters.conf`:

```yaml
master:
- salt-master
- salt-master-2
```

### Steps to Reproduce Issue

1. Run `salt-call test.ping` or some equally trivial salt call

### Versions Report

```
Salt Version:
           Salt: 2016.3.0rc1-2506-g5096d33
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.5 (default, Mar  9 2014, 22:15:05)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 13.4.0
         system: Darwin
        version: 10.9.5 x86_64
```

This seems to be a regression since `2015.8.7`. Tested on Arch Linux too and experiencing the same.
