### ISSUE TITLE
Output and logging of win_iis module functions need improvement

### ISSUE THREAD

**Issue by m03** [saltstack/salt#32050]
### Description of Issue/Question
The win_iis module lacks debug logging, and the output of win_iis.create_* and win_iis.remove_* functions that currently work is pretty poor, for instance, returning empty results on success, and returning raw PowerShell output on error.

It would be better to return a boolean indicating success/failure of these functions, as well as adding logging to the module in order to log additional information about what is occurring.

### Setup
Created a couple of IIS sites beforehand to use as examples of the output from win_iis.remove_site:
```
m03@devmaster01:~$ sudo salt 'win-minion' win_iis.list_sites
win-minion:
    mvcforum
    site2
```
### Steps to Reproduce Issue
win_iis.remove_site run against an existing site returns empty output when the command is successful:
```
m03@devmaster01:~$ sudo salt 'win-minion' win_iis.remove_site 'mvcforum'
win-minion:
m03@devmaster01:~$ sudo salt 'win-minion' win_iis.list_sites
win-minion:
    site2
```
win_iis.remove_site run against a non-existing site returns the PowerShell output of the command used within the function when the command is unsuccessful:
```
m03@devmaster01:~$ sudo salt 'win-minion' win_iis.remove_site 'nothing-here'
win-minion:
    Remove-WebSite : Cannot find path 'IIS:\Sites\nothing-here\' because it does not exist.
    At line:1 char:49
    + Import-Module WebAdministration; cd IIS:\Sites\;Remove-WebSite -Name \'nothing-h ...
    +                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (IIS:\Sites\nothing-here\:String) [Remove-Website], ItemNotFoundExceptio
       n
        + FullyQualifiedErrorId : PathNotFound,Microsoft.IIs.PowerShell.Provider.RemoveWebsiteCommand
ERROR: Minions returned with non-zero exit code
```
### Versions Report
Ubuntu 14.04 master:
```
m03@devmaster01:~$ sudo salt --versions-report
Salt Version:
           Salt: 2016.3.0-242-g5096d33

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
Windows 2012r2 minion:
```
m03@devmaster01:~$ sudo salt 'win-minion' test.versions_report
win-minion:
    Salt Version:
               Salt: 2016.3.0

    Dependency Versions:
             Jinja2: 2.8
           M2Crypto: 0.21.1
               Mako: 1.0.3
             PyYAML: 3.11
              PyZMQ: 15.2.0
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.3
                ZMQ: 4.1.2
               cffi: 1.5.0
           cherrypy: 5.0.1
           dateutil: 2.4.2
              gitdb: 0.6.4
          gitpython: 1.0.1
              ioflo: 1.5.0
            libgit2: Not Installed
            libnacl: 1.4.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.8
              smmap: 0.9.0
            timelib: Not Installed

    System Versions:
               dist:
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
