### ISSUE TITLE
saltstack and supervisord not restarting my apps.

### ISSUE THREAD

**Issue by esn89** [saltstack/salt#32081]
### Description of Issue/Question

running `salt '*' state.highstate` does not restart my processes.  Every time I run a highstate, my latest code from git gets pulled, built and turned into binaries.  
I have, in my init.sls a command to copy the new super-app.conf (in case anything changes, normally it does not) into my /etc/supervisord/conf.d/ dir.

When I run highstate, I noticed by going "salt '*' supervisord.status" that my app did not get restarted, from looking at the time stamp that it returns.  This is really important to me, as I need the latest binary to be running.

### Setup
```
In my init.sls I have a: 

# Copy supervisor
/etc/supervisor/conf.d/:
  file.copy:
    - source: /home/my-app/super-app/etc/super-app.conf
    - force: True
    - makedirs: True

social-radar:
   supervisord.running:
     - restart: True
     - user: ty-app
     - conf_file: /etc/supervisor/conf.d/super-app-supervisord.conf
```

### Versions Report
```
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.11+ (default, Feb 22 2016, 16:38:42)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: debian stretch/sid 
        machine: x86_64
        release: 4.3.0-1-amd64
         system: debian stretch/sid 
```
