### ISSUE TITLE
salt spm should have an option to list and show info packages in the repo

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#32137]
### Description of Issue/Question

Spm doesn't have an option to list or show info of the packages, reactors and config in it's repo';s
### Setup

see: https://docs.saltstack.com/en/develop/topics/spm/index.html

spm create_repo /srv/spm_build

spm build someformula-formula
spm build somereactor-reactor
spm build someconfig-conf
### Steps to Reproduce Issue

```
spm list

```

```
spm info someformula

package someformula not installed
```
### Desired output:

```
spm list

spm:
  formulas:
    - someformula
    - someotherformula
  reactors:
    - somereactor
  conf:
    - someconfig
```

```
spm info someformula

spm:
  someformula:
      filename: someformula-201506-1.spm
      info:
        depencies: None
        description: SomeFormula
        name: someformula
        os: RedHat, Debian, Suse, Arch
        os_family: RedHat, Debian, Suse, Arch
        release: 1
        summary: SomeFormula
        version: 201506
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.0-266-gc03e875

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.24.0
           Mako: 1.0.4
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Mar  3 2016, 11:00:04)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: 1.5.2
       cherrypy: 4.0.0
       dateutil: 2.5.1
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.1
        libgit2: 0.23.4
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.3
   python-gnupg: 0.3.7
          smmap: 0.9.0
        timelib: 0.2.4

System Versions:
           dist:   
        machine: x86_64
        release: 4.4.5-1-ARCH
         system: Linux
        version: Not Installed
```
