### ISSUE TITLE
master's peer property does not match behavior described in doc (2016.3)

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#32152]
### Description of Issue/Question

https://docs.saltstack.com/en/latest/ref/peer.html

```
peer:
  .*:
    - .*
```

salt testa publish.publish testb test,ping --> success!

```
peer:
  testa:
    - .*
```

salt testa publish.publish testb test,ping --> success!

```
peer:
  testa:
    - test.ping
```

salt testa publish.publish testb test,ping --> success!

```
peer:
  testa:
    testb:
      - test.ping
```

salt testa publish.publish testb test,ping --> **fails**!

```
peer:
  .*:
    testb:
      - test.ping
```

salt testa publish.publish testb test,ping --> **fails**!
### Setup

n/a
### Steps to Reproduce Issue

See above.
### Versions Report

``` yaml
Salt Version:
           Salt: 2016.3.0rc1-112-g1af2e41

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.11 (default, Mar 18 2016, 13:38:08)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: Not Installed
       cherrypy: 3.8.0
       dateutil: 2.4.0
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: 0.9.0
        timelib: 0.2.4

System Versions:
           dist:
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
