### ISSUE TITLE
State 'pkg.installed' was not found in SLS

### ISSUE THREAD

**Issue by goatjam** [saltstack/salt#32198]
Since updating to 2015.8.8 I am unable to process pkg.installed states.

### Setup
```sls
top.sls
base:
  '*':
    - test

test.sls
htop:
  pkg:
    - installed
```
### Steps to Reproduce Issue
highstate on above two sls files
```yaml
OUTPUT:
    ID: htop
    Function: pkg.installed
      Result: False
    Comment: State 'pkg.installed' was not found in SLS 'test'
              Reason: 'pkg' __virtual__ returned False
   ```
### Versions Report
```yaml
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
        dist: LinuxMint 17.2 rafaela
        machine: x86_64
        release: 3.16.0-38-generic
        system: LinuxMint 17.2 rafaela
```
NOTE: LinuxMint uses the stand Ubuntu 14.04 repository for all non-desktop related stuff

# Workaround

I have reverted back to 2015.5.10 and the problem no longer exists.

**Comment by jfindlay** [comment]
@goatjam, thanks for reporting, we should make sure the correct pkg module is loaded on mint.

**Comment by mudfly** [comment]
I can confirm I am also seeing this issue on Linux Mint. I am using a masterless salt setup in a Vagrant environment.

### SLS
```yaml
# cat /srv/salt/internet/pidgin.sls
pidgin_im:
  pkg.installed:
    - name: pidgin 
```
### Run
```bash
salt-call state.sls internet.pidgin -l debug
```
### Output
````yaml
...snip...
[DEBUG   ] Could not LazyLoad pkg.installed
[INFO    ] Running state [pidgin] at time 17:52:51.401648
[DEBUG   ] LazyLoaded pkg.installed
[ERROR   ] State 'pkg.installed' was not found in SLS 'internet.pidgin'
Reason: 'pkg' __virtual__ returned False

[DEBUG   ] File /var/cache/salt/minion/accumulator/140201416113936 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: pidgin_im
    Function: pkg.installed
        Name: pidgin
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'internet.pidgin'
              Reason: 'pkg' __virtual__ returned False
     Started:
    Duration:
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

### Versions Report
```yaml
# salt-call --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: LinuxMint 17.3 rosa
        machine: x86_64
        release: 3.13.0-37-generic
         system: LinuxMint 17.3 rosa
```
