### ISSUE TITLE
dockerng fails because there are default labels in the dockerfile. 

### ISSUE THREAD

**Issue by dverbeek84** [saltstack/salt#32234]
### Description of Issue/Question

When i start a docker with the following config it works. But only the first run. The second run fails.

```
squid-docker:
  dockerng.running:
    - name: squid
    - image: {{ squid.image }}
    - user: squid
    - port_bindings:
      - '3128:3128'
    - restart_policy: always
```

This is because the baseimage `centos:7` contains labels. When i add the following config to the SLS file

```
squid-docker:
  dockerng.running:
    - name: squid
    - image: {{ squid.image }}
    - user: squid
    - labels:
      - build-date: '2016-03-04'
      - license: 'GPLv2'
      - name: 'CentOS Base Image'
      - vendor: 'CentOS'
    - port_bindings:
      - '3128:3128'
    - restart_policy: always
``` 

It works. So i think the defaults must be ignored.

### Versions Report
```
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```
