### ISSUE TITLE
pkgrepo.managed touches all files even if specific sources.list is given

### ISSUE THREAD

**Issue by do3meli** [saltstack/salt#32240]
### Description of Issue/Question

When pkgrepo.managed is used to configure a new apt repository in a specific file it looks to me like it is touching all sources.list files it finds. this should not be the case. I assume that pkgrepo.managed is only opening the specified sources.list file and does not look at any other files.
### Setup

in my sls config i define the one and only file where pkgrepo.managed should look at:

```
pkgsources-ox-appsuite-ui:
  pkgrepo.managed:
    - comments: "my very fancy comment"
    - refresh_db: False
    - name: deb http://i-want-to-have-my-own-pkg-repo.com/packages/
    - file: /etc/apt/sources.list.d/my-own-sources.list
```
### Steps to Reproduce Issue
1. configure sls state like above
2. create some sources.list files in /etc/apt/sources.list.d/
3. run it against a minion
4. check the various sources.list files for its timestamp. they all now have the same timestamp from the time when the salt run occurred.
### Versions Report

salt-minion --version: 

```
salt-minion 2015.8.8 (Beryllium)
```

salt --version-report:

```
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Ubuntu 14.04 trusty

```
