### ISSUE TITLE
Document steps for running salt from individual user repositories

### ISSUE THREAD

**Issue by eradman** [saltstack/salt#32271]
For me most difficult part about getting started with SaltStack was figuring out
how to test changes using a personal repository. The documentation seems to omit
this topic completely. This is what I came up with

master:

```
file_roots: 
  base:
    - /srv/salt
  radman:
    - /u/en/radman/git/salt
```

top.sls:

```
{{saltenv}}:
  '*':
    - defaults
```

Now anyone in my group can run the following command after adding the path to
their checkout to `/etc/salt/master`:

```
sudo salt 'workstation.*' state.highstate test=True env=$USER
```

Is this a good way to approach the problem? Please add the recommended setup to
the documentation!
