### ISSUE TITLE
Support globbing in sources parameter of salt.modules.archive

### ISSUE THREAD

**Issue by mephi42** [saltstack/salt#32356]
### Description of Issue/Question

I would like Salt to be able to include files into archives by mask.
### Setup

```
/tmp/logs.tar.xz:
  module.run:
    - name: archive.tar
    - options: --ignore-failed-read -cJf
    - tarfile: /tmp/logs.tar.xz
    - sources:
      - /var/log/*.log
```
### Steps to Reproduce Issue

When I apply this state, `/var/log/*.log` is interpreted as exact file name.
### Versions Report

2015.8.7
### Discussion

I'm willing to implement this myself, but I would like to make sure I choose the right interface. I see the following options currently:
- Perform globbing for all `sources` entries
- Perform globbing only for `sources` entries that are marked in a special way (e.g. `- glob:/var/log/*.log`)
- Introduce a new list parameter (say, `sources_glob`) and perform globbing only for its items
