### ISSUE TITLE
Use salt.state.event and reactor for ochestration

### ISSUE THREAD

**Issue by commutecat** [saltstack/salt#32355]
(Alternate title :  How to execute/run code in salt master node within highstate. )

In AWS cloud implementation,  I have a EC2 instance that will connect to RDS during deployment. 
I use a salt master server to do the deployment, e.g. to create EC2 instance, RDS instance using saltstack. For security reason, I don't want to give EC2 instance AWS key. Only the salt-master server holding the AWS cloud access key. 

So I build a orchestration step : 
1. put python into EC2  instance
2. use boto_rds.present to enable the RDS instance
3. Get the RDS instance DNS name using python boto3 script ,write the RDS DNS name into my application
4. Now put the custom application into EC2

Because salt "*" highstate are only minion oriented, I cannot execute command in salt-master.  
Because Reactor able to act on "tag", while the states.event.send can give the tag.  Instead of using salt-runner, I find out a alternate way to do stuff  
1. Put salt-minion in the same salt-master
2. Use states.event and Reactor to control the ochestration within the highstate. 

This might not replace the typcial salt-runner orchestration, however, it is lean and clean for anyone that need a simple solution.  

Sample setup
```
salt-master hostname : my-saltmaster

file: /etc/salt/master
file_roots: 
  base:
    - /srv/salt/states

file: /etc/salt/minion
master: my-saltmaster

file:/srv/salt/states/top.sls 
base:
  "myEC2":
    - python-packages/init.sls
    - cloud/create-rds-instances.sls
    - source/custom-app-package.sls
    - trigger/custom-app-package-to-ec2.sls
    
file : /srv/salt/states/top.sls
base:
  "app-server":
   #step1 
    - python-packages
   #step 2 
    - cloud.create-rds-instances 
   # step 3 
    - trigger.custom-app-package-to-rds
   # step 4 
    - source.custom-app-package
 
# used by step 3 to send a tag to reactor
file : /srv/salt/states/trigger/custom-app-package-to-ec2
put-rds-endpoint-to-app: 
  event.send:
    - data: 
       status:  foobar    

# reactor will see the event tag and trigger the reactor highstate
file :  etc/salt/master.d/reactor.conf
reactor:
  - ' put-rds-endpoint-to-app':
    - /srv/salt/reactor/connect-app.sls

file:/srv/salt/reactor/connect-app.sls
highstate_run:
  cmd.run:
    - tgt: my-saltmaster
    - arg:
      - bash connect-app-to-rds2.sh 
```
