### ISSUE TITLE
dockerng.running always restarts images

### ISSUE THREAD

**Issue by dustintenney** [saltstack/salt#32369]
### Description of Issue/Question

dockerng.running restarts my images every time and fails giving this error:

Failed to apply configuration for the following parameters: labels

### Setup
```sls
docker.:443/atomic/pyal:{{ salt['pillar.get']('version') }}:
  dockerng.image_present:
    - force: True

pyal:
  dockerng.running:
    - name: pyal
    - image: docker:443/atomic/pyal:{{ salt['pillar.get']('version') }}
    - user: user
    - network_mode: bridge
    - labels:
      - pyal: latest
    - restart_policy: on-failure:5
    - ports:
      - "8000/tcp"
    - port_bindings:
      - 127.0.0.1:8000:8000
    - detach: true
```
### Steps to Reproduce Issue

I was also getting similar errors for "user" and "network_mode" until I added them to the state.   Adding them fixed those, but adding "labels" did not.

### Versions Report
```yaml
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-504.12.2.el6.x86_64
         system: CentOS 6.7 Final
```
Same versions on minion with: docker-py version: 1.7.2
