### ISSUE TITLE
Support installing package with obsoleted name on RHEL systems family

### ISSUE THREAD

**Issue by vutny** [saltstack/salt#32388]
### Description of Issue/Question

Salt fails to apply `pkg.installed` state with package name which became obsoleted by changes in the distro repository or by adding 3rd-party repos.
### Setup

I have very simple SLS file:

``` yaml
python-boto:
  pkg.installed:
    - name: python-boto
```

Repositories configured:

``` console
# yum repolist
Loaded plugins: fastestmirror, presto
Loading mirror speeds from cached hostfile
 * base: mirror.symnds.com
 * epel: mirror.symnds.com
 * extras: mirror.symnds.com
 * updates: mirror.vcu.edu
repo id          repo name                                                status
base             CentOS-6 - Base                                           6 575
epel             Extra Packages for Enterprise Linux 6 - x86_64           12 132
extras           CentOS-6 - Extras                                            61
mongodb          MongoDB Repository                                          279
salt-latest      SaltStack latest Release Channel for RHEL/CentOS 6          118
updates          CentOS-6 - Updates                                        1 488
repolist: 20 653

```
### Steps to Reproduce Issue

After Applying SLS I got this:

``` yaml
----------
          ID: python-boto
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: python-boto
     Started: 11:17:13.549628
    Duration: 7576.62 ms
     Changes:   
              ----------
              python-pyasn1:
                  ----------
                  new:
                      0.0.12a-1.el6
                  old:
              python2-boto:
                  ----------
                  new:
                      2.39.0-1.el6
                  old:
              python2-rsa:
                  ----------
                  new:
                      3.3-5.el6
                  old:

```

Debug log:

```
[INFO    ] Running state [python-boto] at time 11:17:13.549628
[INFO    ] Executing state pkg.installed for python-boto
[INFO    ] Executing command ['repoquery', '--plugins', '--queryformat', '%{NAME}_|-%{ARCH}', '--pkgnarrow=all', '--all'] in directory '/root'
[INFO    ] Executing command ['yum', '--quiet', 'clean', 'expire-cache'] in directory '/root'
[DEBUG   ] output: 
[INFO    ] Executing command ['yum', '--quiet', 'check-update'] in directory '/root'
[INFO    ] Executing command ['yum', '-y', 'install', 'python-boto'] in directory '/root'
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[INFO    ] Made the following changes:
'python-pyasn1' changed from 'absent' to '0.0.12a-1.el6'
'python2-rsa' changed from 'absent' to '3.3-5.el6'
'python2-boto' changed from 'absent' to '2.39.0-1.el6'

[ERROR   ] The following packages failed to install/update: python-boto
[INFO    ] Completed state [python-boto] at time 11:17:21.126248
```

That's because `python-boto` package was obsoleted by `python2-boto` which came from EPEL. And obviously, `rpm -qa ...` command is no longer able to see the `python-boto` pkg as _installed_, but the newer package `python2-boto` is actually **will be installed** if you execute plain `yum install python-boto` command:

``` console
# repoquery --plugins --queryformat '%{NAME}_|-%{ARCH}' --pkgnarrow=all --whatobsoletes python-boto
python-boto_|-noarch
python2-boto_|-noarch
python2-boto_|-noarch
# rpm -qa | grep python-boto
# rpm -qa | grep python2-boto
python2-boto-2.39.0-1.el6.noarch
```

Without the support of detecting obsoleted packages, the `pkg` states could fail with false positive after arbitrary update of available repositories metadata.
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.8.1.el6.x86_64
         system: CentOS 6.6 Final
```
