### ISSUE TITLE
user.present state includes shadow hash in return when user updated 

### ISSUE THREAD

**Issue by tbaker57** [saltstack/salt#32381]
### Description of Issue/Question
When a user is newly created using the 'user.present' state, the changes entry in the return dict contains the string 'XXX-REDACTED-XXX'  for the 'passwd' attribute. However if the user already exists but the shadow entry is changing, the new shadow entry appears in the return dict unredacted. This happens in both test and non-test mode.

### Setup
Bog standard user.present state for an existing user (but a changing shadow password)

### Steps to Reproduce Issue
Run the user.present state with an existing user (but changing shadow password).

### Fix
There are 2 places which need to be fixed I think:

https://github.com/saltstack/salt/blob/develop/salt/states/user.py#L134
```
                if lshad['passwd'] != password:
                    change['passwd'] = password
```
The value of change['passwd'] needs to be redacted here. This fixes the issue in test mode.

https://github.com/saltstack/salt/blob/develop/salt/states/user.py#L553
```
        if 'shadow.info' in __salt__:
            for key in spost:
                if lshad[key] != spost[key]:
                    ret['changes'][key] = spost[key]
```
Needs to be replaced with something like
```
        if 'shadow.info' in __salt__:
            for key in spost:
                if lshad[key] != spost[key]:
                        ret['changes'][key] = spost[key] if key != 'passwd' else 'XXX-REDACTED-XXX'

```
This seems to fix the issue in non-test mode.

### Versions Report
Running masterless (don't think it makes a difference)
[root@ip-172-31-27-155 ~]# salt-call --versions report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core

**Comment by jfindlay** [comment]
@tbaker57, thanks for reporting.
```sls
jmoney-main ~ master # cat /srv/salt/test.sls 
salt user:
  user.present:
    - name: saltuser
    - password: saltpass
```
```yaml
jmoney-main ~ master # salt jmoney-main state.apply test
jmoney-main:
----------
          ID: salt user
    Function: user.present
        Name: saltuser
      Result: True
     Comment: New user saltuser created
     Started: 11:11:05.833458
    Duration: 54.955 ms
     Changes:
              ----------
              fullname:
              gid:
                  1002
              groups:
                  - saltuser
              home:
                  /home/saltuser
              homephone:
              name:
                  saltuser
              passwd:
                  x
              password:
                  XXX-REDACTED-XXX
              roomnumber:
              shell:
                  /bin/sh
              uid:
                  1002
              workphone:

Summary for jmoney-main
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
```sls
jmoney-main ~ master # cat /srv/salt/test.sls 
salt user:
  user.present:
    - name: saltuser
    - password: newpass
```
```yaml
jmoney-main ~ master # salt jmoney-main state.apply test
jmoney-main:
----------
          ID: salt user
    Function: user.present
        Name: saltuser
      Result: True
     Comment: Updated user saltuser
     Started: 11:11:19.156840
    Duration: 12.28 ms
     Changes:
              ----------
              passwd:
                  newpass

Summary for jmoney-main
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
```yaml
jmoney-main ~ master # salt jmoney-main test.versions
jmoney-main:
    Salt Version:
               Salt: 2015.8.7

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed

    System Versions:
               dist: debian 8.4
            machine: x86_64
            release: 3.16.0-4-amd64
             system: debian 8.4
```
