### ISSUE TITLE
environ.setenv forces masterless minion into looking for master

### ISSUE THREAD

**Issue by msarahan** [saltstack/salt#32390]
### Description of Issue/Question

I have a masterless configuration, running salt with Vagrant, deploying to a Windows server 2012 VM, running salt on a Mac OSX 10.10 host.  When provisioning the VM, the provisioning process hangs when setting an environment variable, at the following output:

```
[INFO    ] Executing state environ.setenv for PATH
[DEBUG   ] SaltEvent PUB socket URI: ipc://c:\salt\var\run\salt\minion\minion_event_d5a4c3858c_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: ipc://c:\salt\var\run\salt\minion\minion_event_d5a4c3858c_pull.ipc
```
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

I followed advice here on how to set environment variables: https://github.com/saltstack/salt/issues/9876#issuecomment-172071745

Additionally, I have vagrant set up for masterless configuration with salt with the following section in Vagrantfile:

```
  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.minion_config = "saltstack/etc/minion"
    salt.run_highstate = true
    salt.verbose = true
  end

```

and my minion config:

```
## Look locally for files
master: localhost
file_client: local

## Where your salt states & files are located
file_roots:
  base:
    - /srv/saltstack/salt

pillar_roots:
  base:
    - /srv/saltstack/pillars
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

I run `vagrant provision` - but salt going to highstate is the same.

I think this might be what causes the search for a master:

https://github.com/saltstack/salt/blob/0ef623f6fae5d624abd5d335ccd0f8b0aab77845/salt/modules/environ.py#L187-L194
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

2015.5.2 on Windows (masterless minion)
