### ISSUE TITLE
network.managed does not support 'team'

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#32391]
using network.managed does not accept team.
Using CentOS 7

```
{{ sls }} network team0:
    network.managed:
        - name: team0
        - enabled: true
        - type: Team
        - ipaddr: x.x.206.13
        - netmask: 255.255.255.0

{{ sls }} network p1p1:
    network.managed:
        - name: p1p1
        - enabled: true
        - type: TeamPort
        - team_master: team0

{{ sls }} network p1p2:
    network.managed:
        - name: p1p2
        - enabled: true
        - type: TeamPort
        - team_master: team0
```

output:

```
ID: mfcf.service.influxdb network team0
    Function: network.managed
        Name: team0
      Result: False
     Comment: Invalid option -- Interface: team0, Option: team, Expected: [eth|bond|alias|clone|ipsec|dialup|bridge|slave|vlan|ipip]
     Started: 12:09:22.998522
    Duration: 0.962 ms
```

latest state module dont seem to be any support yet.
https://github.com/saltstack/salt/blob/develop/salt/states/network.py
