### ISSUE TITLE
IPv6 network.managed bug

### ISSUE THREAD

**Issue by valentin2105** [saltstack/salt#32404]
### Description of Issue/Question

Hi,
I found a bug when I try to appli an IPV6 on eth1 (for example) with or without an IPV4.
### Setup

```
eth1:                                                                                                                  
  network.managed:
    - enabled: True
    - type: eth 
    - proto: none
    - ipaddr: 192.168.33.2
    - netmask: 255.255.255.0
    - enable_ipv6: true
    - ipv6proto: static
    - ipv6addr: a:b:c:d::e
    - ipv6netmask: 64
```

provide this on /etc/network/interface :

```
auto eth1                                                                                                              
iface eth1 inet static
    address 192.168.33.2
    netmask 255.255.255.0
iface eth1 inet6 static
    netmask 64
```

The line "address" for eth1 on IPv6 is missing.
### Steps to Reproduce Issue
- Create an IPv6 apply state
- Try to apply this on a minion
### Versions Report

```
                  Salt: 2015.5.3
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed
               Tornado: 4.2.1
 Debian source package: 2015.5.3+ds-1~bpo8+1
```

I have try on Salt 2015.5.3 and 2015.8.8. 
My connexion Master/Minion only in IPV6 work only with 2015.5.3 and not on 2015.8 (this is another problem).
