### ISSUE TITLE
Salt-API - local and local_batch clients return data in different shapes

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#32459]
### Description of Issue/Question

When using the salt-api, the state return object shape using local client is different than the local_batch client.

I don't know if this is a bug or by design.  But it is making it harder to parse batch returns.

local client returns a list with 1 item.
```
{
  "return": [
    {
      "minion1": {},
      "minion2": {},
      "minion3": {},
      "minion4": {}
    }
  ]
}
```
local_batch client returns a list with multiple items.
```
{
  "return": [
    {
      "minion1": {}
    },
    {
      "minion2": {}
    },
    {
      "minion3": {}
    },
    {
      "minion4": {}
    }
  ]
}
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.9 (unknown, Dec 17 2015, 01:08:55)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.1
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: 0.20.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
   python-gnupg: 0.3.7
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.1.13-19.30.amzn1.x86_64
```
