### ISSUE TITLE
PCS state module: feature set for creating clusters and resources

### ISSUE THREAD

**Issue by hoonetorg** [saltstack/salt#32467]
### Description of Issue/Question
Change PCS modules/state module so, that it is possible to do
- cluster node authorization
- cluster setup
- setting cluster properties, resource defaults and resource op defaults.
- creating fence devices
- creating resources and constraints
- doing multiple modifications to the CIB in a cibfile first and
- pushing all the changes done to a cibfile at once to the live CIB of the cluster

##### Requirements:
PCS is installed, pcs service is started and
the password for the hacluster user is set and known.

##### Remark on the cibname variable used in the examples:
The use of the cibname varible is optional.
Use it only if you want to deploy your changes into a cibfile first and then push it.
This makes only sense if you want to deploy multiple changes (which require each other) at ones to the cluster.

###### At first the cibfile must be created:

```
        mysql_pcs__cib_created_cib_for_galera:
            pcs.cib_created:
                - cibname: cib_for_galera
                - scope: None
                - extra_args: None
```
###### Then the cibfile can be modified by creating resources (creating only 1 resource for demonstration, see also 7.):
```
        mysql_pcs__resource_created_galera:
            pcs.resource_created:
                - resource_id: galera
                - resource_type: "ocf:heartbeat:galera"
                - resource_options:
                    - 'wsrep_cluster_address=gcomm://node1.example.org,node2.example.org,node3.example.org'
                    - '--master'
                - cibname: cib_for_galera
```
###### After modifying the cibfile it can be pushed to the live CIB in the cluster:
```
        mysql_pcs__cib_pushed_cib_for_galera:
            pcs.cib_pushed:
                - cibname: cib_for_galera
                - scope: None
                - extra_args: None
```
###### 1. Authorize nodes to each other:
```
        pcs_auth__auth:
            pcs.auth:
                - nodes:
                    - node1.example.com
                    - node2.example.com
                - pcsuser: hacluster
                - pcspasswd: hoonetorg
                - extra_args: []
```
###### 2. Do the initial cluster setup:
```
        pcs_setup__setup:
            pcs.cluster_setup:
                - nodes:
                    - node1.example.com
                    - node2.example.com
                - pcsclustername: pcscluster
                - extra_args:
                    - '--start'
                    - '--enable'
```
###### 3. Optional: Set cluster properties:
```
        pcs_properties__prop_is_set_no-quorum-policy:
            pcs.prop_is_set:
                - prop: no-quorum-policy
                - value: ignore
                - cibname: cib_for_cluster_settings
```
###### 4. Optional: Set resource defaults:
```
        pcs_properties__resource_defaults_to_resource-stickiness:
            pcs.resource_defaults_to:
                - default: resource-stickiness
                - value: 100
                - cibname: cib_for_cluster_settings
```
###### 5. Optional: Set resource op defaults:
```
        pcs_properties__resource_op_defaults_to_monitor-interval:
            pcs.resource_op_defaults_to:
                - op_default: monitor-interval
                - value: 60s
                - cibname: cib_for_cluster_settings
```
###### 6. Configure Fencing (!is not optional on production ready cluster!):
```
        pcs_stonith__created_eps_fence:
            pcs.stonith_created:
                - stonith_id: eps_fence
                - stonith_device_type: fence_eps
                - stonith_device_options:
                    - 'pcmk_host_map=node1.example.org:01;node2.example.org:02'
                    - 'ipaddr=myepsdevice.example.org'
                    - 'power_wait=5'
                    - 'verbose=1'
                    - 'debug=/var/log/pcsd/eps_fence.log'
                    - 'login=hidden'
                    - 'passwd=hoonetorg'
                - cibname: cib_for_stonith
```
###### 7. Add resources to your cluster:
```
        mysql_pcs__resource_created_galera:
            pcs.resource_created:
                - resource_id: galera
                - resource_type: "ocf:heartbeat:galera"
                - resource_options:
                    - 'wsrep_cluster_address=gcomm://node1.example.org,node2.example.org,node3.example.org'
                    - '--master'
                - cibname: cib_for_galera
```
###### 8. Optional: Add constraints (locations, colocations, orders):
```
        haproxy_pcs__constraint_created_colocation-vip_galera-haproxy-clone-INFINITY:
            pcs.constraint_created:
                - constraint_id: colocation-vip_galera-haproxy-clone-INFINITY
                - constraint_type: colocation
                - constraint_options:
                    - 'add'
                    - 'vip_galera'
                    - 'with'
                    - 'haproxy-clone'
                - cibname: cib_for_haproxy
```
### Steps to Reproduce Issue
Necessary features to create resources and constraints are missing, documentation incomplete.

### Versions Report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
