### ISSUE TITLE
pkgrepo.managed not calling apt-get update despite require_in

### ISSUE THREAD

**Issue by gibsonje** [saltstack/salt#32462]
### Description of Issue/Question

Per https://docs.saltstack.com/en/2015.5/ref/states/all/salt.states.pkgrepo.html#salt.states.pkgrepo.manage

```
pkg.repo.managed
require_in: Set this to a list of pkg.installed or pkg.latest to trigger the running of apt-get update prior to attempting to install these packages. Setting a require in the pkg will not work for this.
```

Despite setting `refresh_db: True` and `require_in` on the pkgs, `apt-get update` is not called. 

```
[INFO    ] Package repo 'deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0 multiverse' already configured
```

is in the output on the first highstate, but the packages fail to install

```
----------
          ID: mongodb-10gen-install
    Function: pkg.installed
        Name: mongodb-org
      Result: False
     Comment: The following packages failed to install/update: mongodb-org=3.0.3, mongodb-org-server=3.0.3 3 targeted packages were installed/updated.
     Started: 22:09:11.862594
    Duration: 158596.806 ms
     Changes:
              ----------
              mongodb-org-mongos:
                  ----------
                  new:
                      3.0.3
                  old:
              mongodb-org-shell:
                  ----------
                  new:
                      3.0.3
                  old:
              mongodb-org-tools:
                  ----------
                  new:
                      3.0.3
                  old:
```
### Setup

In the below state, the commented out `cmd.run` fixes the error (explicitly running an `apt-get update`).

```
mongodb-10gen:
  pkgrepo.managed:
    - humanname: MongoDB 10gen PPA
    - name: deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0 multiverse
    - dist: precise/mongodb-org/3.0
    - file: /etc/apt/sources.list.d/mongodb.list
    - keyid: 7F0CEB10
    - keyserver: keyserver.ubuntu.com
    - refresh_db: True
    - require_in:
      - pkg: mongodb-10gen

  #cmd.run:
  #  - name: 'sudo apt-get update'
  #  - user: root
  #  - group: root
  #  - require_in:
  #    - pkg: mongodb-10gen

  pkg.installed:
    - name: mongodb-org
    - pkgs:
      - mongodb-org: 3.0.3
      - mongodb-org-server: 3.0.3
      - mongodb-org-shell: 3.0.3
      - mongodb-org-mongos: 3.0.3
      - mongodb-org-tools: 3.0.3
```
### Steps to Reproduce Issue

Salt Version: 2015.8.3

```
salt --version
salt 2015.8.3 (Beryllium)
```

Using the states outlined in this ticket, the first highstate should fail with:

```
----------
          ID: mongodb-10gen-install
    Function: pkg.installed
        Name: mongodb-org
      Result: False
     Comment: The following packages failed to install/update: mongodb-org=3.0.3, mongodb-org-server=3.0.3 3 targeted packages were installed/updated.
     Started: 22:09:11.862594
    Duration: 158596.806 ms
     Changes:
              ----------
              mongodb-org-mongos:
                  ----------
                  new:
                      3.0.3
                  old:
              mongodb-org-shell:
                  ----------
                  new:
                      3.0.3
                  old:
              mongodb-org-tools:
                  ----------
                  new:
                      3.0.3
                  old:
```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-71-generic
         system: Ubuntu 14.04 trusty
```
