### ISSUE TITLE
dockerng.running tries recreate container because of poor detection of labels

### ISSUE THREAD

**Issue by alexanderilyin** [saltstack/salt#32495]
Debug from `salt-call`:

```
[DEBUG   ] dockerng.running: Analysis of container 'XXX' reveals the following changes need to be made: {'labels': {'new': {}, 'old': {u'build-date': u'2016-03-31', u'vendor': u'CentOS', u'Description': u'Percona server with handlersocker', u'license': u'GPLv2', u'name': u'CentOS Base Image'}}}
```

Workaround is set labels manually:
```
XXX:
    dockerng.running:
        - image: example/app:latest
        - port_bindings:
             - 3306:3306
             - 9998:9998
             - 9999:9999
        - binds:
            - /data/XXX/:/var/lib/mysql:rw
        - labels:
            build-date: '2016-03-31'
            vendor: 'CentOS'
            Description: 'Percona server with handlersocker'
            license: 'GPLv2'
            name: 'CentOS Base Image'
```

I was expecting that salt could get labels from image by it's own.

```
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```
