### ISSUE TITLE
Add SubnetName to use subnet tag name instead of subnet-id to create EC2 instance  

### ISSUE THREAD

**Issue by commutecat** [saltstack/salt#32511]
### Description of Issue/Question

Currently , to launch a  EC2 instance into subnet other than the your VPC default subnet, the designated VPC subnet-id must be specify inside cloud.profiles.d/some_profile.conf  i.e
### Setup

You create specify subnet for your VPC 

```
salt myminion boto_vpc.create_subnet vpc_id='vpc-xxxxxxx' \
      subnet_name='APP-XYZ-SB-DEV' cidr_block='172.16.10.0/25' \
      tag={"Key":"Name", "Value":"APP-XYZ-SB-DEV"}
# Subnet-id return : subnet-12345600

salt myminion boto_vpc.create_subnet vpc_id='vpc-xxxxxxx' \
      subnet_name='APP-XYZ-SB-PROD' cidr_block='172.16.10.128/25' \
      tag={"Key":"Name", "Value":"APP-XYZ-SB-PROD"}
# Subnet-id return subnet-12345678
```

Then in your cloud.profiles.d/aws_profile.conf  entry, you want to launch your instance into subnet_name APP-XYZ-SB-PROD, but currently you can only use subnet-id  subnet-12345678. 

```
# Put SubnetId under network_interfaces
my-prod-ec2: 
  provider: my-aws
  image: ami-87564feb
  size: t2.micro
  ssh_username: ubuntu
  keyname: my_key_name
  network_interfaces:
    - DeviceIndex: 0
      SubnetId: subnet-12345678
```

```
# Or next to other key
my-prod-ec2: 
  provider: my-aws
  image: ami-87564feb
  size: t2.micro
  ssh_username: ubuntu
  keyname: my_key_name
  SubnetId: subnet-12345678
```

As example shown, the value of subnet-id must be enter manually or using external script to modify the profiles or inject into backend pillar.

Currently the cloud module source code : ec2.py  contains a function that retrieve subnet-id from tag name, which is call get_subnetid() .  
### Patch attempt

If the dictionary can be extended to use one additional key call "SubnetName" and extend the work during creation,  we can have this. 

```
my-prod-ec2: 
  provider: my-aws
  image: ami-87564feb
  size: t2.micro
  ssh_username: ubuntu
  keyname: my_key_name
  # subnetname is your subnet tag name 
  SubnetName: APP-XYZ-SB-PROD
```

patch for cloud.ec2.py

```
### documentation to inform user that SubnetName and Subnet-Id should be mutually exclusive 
# Perhaps inside patching _get_subnet_from_subnet_query

def _get_subnet_from_subnet_query(subnet_query, interface):
    if 'subnetId' in subnet_query: 
        if interface.get('SubnetId'):
            if subnet_query['subnetId'] == interface['SubnetId']:
                return subnet_query['subnetId']
       ##### code that make use of SubnetName  
        elif interface.get('SubnetName'):
          subnet_id=get_subnetid(vm_)
          return subnet_id
       ##### 
        else:
            return subnet_query['subnetId']
```

Correct me if I am wrong.  

p/s: i.  It seems another function securitygroupid(_vm) , also did similar things, which capable to retrieve id from name given, and already under Develop stage.
ii. subnetname  appear in the develop documentation but no example shown yet.
iii. https://github.com/saltstack/salt/issues/27769
