### ISSUE TITLE
problem allow_updates - Salt: 2015.8.7

### ISSUE THREAD

**Issue by jacky35** [saltstack/salt#32535]
### it does not take into account the argument "allow_updates"

```
File: (/srv/salt/windows)
----------------------------
firefox:
  pkg.latest:
    - allow_updates: True
    - pkgs:
       - firefox
-----------------------
```

I also tried other combination but it's the same problem

it replaces firefox by an old version of that found in the repository

```
----------
          ID: firefox
    Function: pkg.latest
      Result: True
     Comment: The following packages were successfully installed/upgraded: firefox
     Started: 16:05:52.156000
    Duration: 9204.0 ms
     Changes:
              ----------
              Mozilla Firefox 45.0.2 ESR (x64 fr):
                  ----------
                  new:
                  old:
                      45.0.2
              Mozilla Maintenance Service:
                  ----------
                  new:
                      45.0.1
                  old:
                      45.0.2
              firefox:
                  ----------
                  new:
                      45.0.1
                  old:
----------------------------------------------------------------------
-----------------------------
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.3
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3
----------
Minion: 2015.8.8-2
```
