### ISSUE TITLE
intermittent issue with cp.get_dir with Windows minion

### ISSUE THREAD

**Issue by jasontrodd** [saltstack/salt#32544]
I'm having a strange issue with sending a folder to a Windows minion.  It works, most of the time.  But sometimes it fails and I can't seem to find any reason why, including any sort of log message to indicate a problem.  In fact, I think the minion is returning success when in fact there has been none.  I have tried to reproduce this manually a number of times with no success.  But in a given day this process using the folder copy will run six times and will fail once.  This command is always run on the same minion, and it can fail on the first attempt and then have five successful runs.  The attempts to move the directories are many minutes apart - this is the first step of an automated product install and a run can take up to 20 minutes to complete.  I've ruled out issues with disk space on the minion.

I'm hoping someone out there can see something I can't.

I'm running the command from a shell script with the following syntax (variables expanded to match run in log files):

```
salt --out txt -t 30 'abc.xyz.net' cp.get_dir salt://18730 c:\\temp\\ajL9Pq6s
```

The addition of the timeout parameter was to try and resolve this - but as the minion is responding with success (or so it seems) this didn't have any impact.

As I was gathering the versions report, I noticed the master is slightly older than the minion - master is 2015.8.7 and minion is 8.8.  This process was originally running on a host with minion 2015.8.7 - it was moved to a new host to isolate this as much as possible for troubleshooting and this new host got the newest minion install.

``` yaml
Master:
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: 0.3.4
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 01:49:05)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.4
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 3.8.13-55.1.5.el6uek.x86_64
         system: Red Hat Enterprise Linux Server 6.6 Santiago

Minion:
    Salt Version:
               Salt: 2015.8.8

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist:
            machine: AMD64
            release: 2008ServerR2
             system: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```

I've attached the relevant snippets from the master and minion logs.  The minion log is wordy - I think I had the minion in plaid log level (or garbage - the absolute highest) in the hopes of getting some indication as to what is going on. 
[MasterLog.txt](https://github.com/saltstack/salt/files/217492/MasterLog.txt)
[MinionLog.txt](https://github.com/saltstack/salt/files/217491/MinionLog.txt)

Any help would be appreciated.  Thanks.
