### ISSUE TITLE
Function to pull interface by regex or network

### ISSUE THREAD

**Issue by seapasulli** [saltstack/salt#32565]
### Description of Issue/Question

I am new to salt so this may already be a thing but I can't find it. 

I have 10 servers of various types. Some with 2 interfaces, some with 6. All of them have an interface on the same 10.1.64 network but the interface that is on that network varies (bond0, eth0, p3p1, p16p1, virbr1,etc)

How can I set up a state that pulls the correct interface? 
I have tried:
```jinja
{%- set interface = salt['cmd.run']('route -n | awk "/10.1.64/ {print \$NF;exit}"') %}
{%- set ip = salt['network.ip_addrs'](interface=interface) %}
{%- set url = 'http://' + ip|string + ':18088/driver' %}
```
which seems to work but it would be nice to have a way to pull an interface by the common network. 

### Setup
http://pastebin.com/BNBGuHj2
```jinja
{%- set interface = salt['cmd.run']('route -n | awk "/10.1.64/ {print \$NF;exit}"') %}
{%- set ip = salt['network.ip_addrs'](interface=interface) %}
{%- set url = 'http://' + ip + ':18088/driver' %}    <======================
{%- set identifier = salt['pillar.get']('cosbench:identifier', grains['host']) %}
{%- set group = salt['pillar.get']('cosbench:group', 'default') %}
```
### Steps to Reproduce Issue
None really. What is the simplest way to set up a sls variable to point to a link that is on the same network? Can this be built into salt somehow or do I need to run salt.cmd to set a variable?

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```yaml
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.10
          PyZMQ: 15.2.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.0
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-83-generic
         system: Ubuntu 14.04 trusty
```
No difference in master/minions. All same version.
