### ISSUE TITLE
No clear way to identify or refer to cache_dir in package specification in winrepo

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#32617]
### Description of Issue/Question

I am trying to create a package specification for windows office 2016 in salt.
Some of the install flags may refer to a file in the installer's directory.
The documents do not mention any way at all of identifying 
or referring to the installer's cache directory in the install_flags and
uninstall_flags in the spec.
### Setup

``` sls
ms-office:
    '16.0.4266.1001':
         installer: salt://win/repo/ms_office/2013_x86/setup.exe
         full_name: Microsoft Office Professional Plus 2016
         reboot: False
         cache_dir: True
         install_flags: '/adminfile [cache_dir]/my_config.msp'
         uninstaller: salt://win/repo/ms_office/2013_x86/setup.exe
         uninstall_flags: '/uninstall ProPlus /adminfile [cache_dir]/my_config.msp '
```

I used [cache_dir] as a placeholder for where we have to refer to the cache dir.

**Comment by jfindlay** [comment]
@hrumph, thanks for reporting.  I am not very familiar with winrepo, but @thebigbear or @twangboy may have a better understanding of your issue.

**Comment by twangboy** [comment]
You may need to specify the full path to the local `cache_dir` until we can work out a solution. Something like this:
```sls
{% set cache_dir = 'C:\salt\var\cache\salt\minion\files\base\win\repo-ng\ms_office' %}
ms-office:
    '16.0.4266.1001':
         installer: salt://win/repo/ms_office/2013_x86/setup.exe
         full_name: Microsoft Office Professional Plus 2016
         reboot: False
         cache_dir: True
         install_flags: '/adminfile {{ cache_dir }}\my_config.msp'
         uninstaller: salt://win/repo/ms_office/2013_x86/setup.exe
         uninstall_flags: '/uninstall ProPlus /adminfile {{ cache_dir }}\my_config.msp '
```

**Comment by hrumph** [comment]
@twangboy, Well I didn't need to do this in fact for windows office. The following formula worked fine

```
ms-office:
    '16.0.4266.1001':
         installer: salt://win/ms-office/2016/setup.exe
         full_name: Microsoft Office Professional Plus 2016
         reboot: False
         cache_dir: True
         install_flags: '/adminfile mike_config.msp'
         uninstaller: 'C:\Program Files\Common Files\Microsoft Shared\OFFICE16\Office Setup Controller\setup.exe'
         uninstall_flags: '/uninstall PROPLUS /dll OSETUP.DLL'
```

Do you think this should temporarily go on the Wiki? Just because as salt is getting more and more featurefull, its making some quite expensive windows tools less and less relevant. The ability to remotely install/deinstall office with such clean elegance (which can be combined any which way with salt's state system) should cause people to take note.
