### ISSUE TITLE
Use client_acl got error.

### ISSUE THREAD

**Issue by ivanwa** [saltstack/salt#32610]
### Description of Issue/Question

```
[root@test-saltstack-10-63 salt]# salt 'test-yum-10-59' test.ping
test-yum-10-59:
    True
[root@test-saltstack-10-63 salt]# su - ivanwa
[ivanwa@test-saltstack-10-63 ~]$ salt 'test-yum-10-59' test.ping
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

I try to increase worker_threads. But there was no effect.
### Setup

```
/etc/salt/master
interface: 172.26.10.63
file_roots:
  base:
    - /srv/salt
pillar_roots:
  base:
    - /srv/pillar
mysql.host: '172.26.10.63'
mysql.user: 'salt'
mysql.pass: 'q1w2e3r4'
mysql.db: 'salt'
mysql.port: 3306
master_job_cache: mysql
client_acl:
  ivanwa:
    - .*
rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/private/localhost_nopass.key
autosign_file: /etc/salt/autosign.conf
worker_threads: 20
nodegroups:
  bpcs: 'bpcs-*'
hash_type: sha256 
max_open_files: 100000
```
### Steps to Reproduce Issue

In debug mode, the master and the minion havn't produced logs
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Red Hat Enterprise Linux Server 7.2 Maipo
```
