### ISSUE TITLE
Bootstrapping "git tag" unnecessarily installs and removes stable from repository

### ISSUE THREAD

**Issue by cconrad** [saltstack/salt#32631]
### Description of Issue
Using salt-cloud profile "script_args" to deploy a git version on a new instance of FreeBSD 10.3 ends up with the correct version installed, but during the bootstrap the stable version is unnecessarily downloaded, installed and then removed before the git version gets installed.

#### /usr/local/etc/salt/cloud.profiles.d/gce-freebsd.conf:
```
gce-freebsd:
  image: "https://www.googleapis.com/compute/v1/projects/freebsd-org-cloud-dev/global/images/freebsd-10-3-release-amd64"
  size: n1-standard-2
  location: europe-west1-b
  network: default
  use_persistent_disk: True
  delete_boot_pd: True
  ssh_interface: public_ips
  provider: gce
  ssh_username: freebsd
  ssh_keyfile: <redacted>
  script_args: git v2016.3.0rc2
```

#### Command
`sudo salt-cloud -l debug -p gce-freebsd test-salt-iocage --keep-tmp`

#### (Partial) output from salt-cloud command
```
[INFO    ] Creating GCE instance test-salt-iocage in europe-west1-b
...
[INFO    ] Rendering deploy script: /usr/local/etc/salt/cloud.deploy.d/bootstrap-salt.sh
...
[DEBUG   ]  *  INFO: - /tmp/.saltcloud-0fe9a4d1-1a9e-4eba-8df5-f9741e30c0f6/deploy.sh -- Version 2015.11.09
...
 *  INFO: Installing minion
...
 *  INFO: Running install_freebsd_git_deps()
...
FreeBSD repository update completed. 25080 packages processed.
...
Installed packages to be UPGRADED:
	pkg: 1.6.2 -> 1.7.2 [FreeBSD]
...
New packages to be INSTALLED:
	swig: 2.0.12_1 [FreeBSD]
	lua51: 5.1.5_9 [FreeBSD]
	libedit: 3.1.20150325_2 [FreeBSD]
	pcre: 8.38_1 [FreeBSD]
...
New packages to be INSTALLED:
	git: 2.8.1 [FreeBSD]
	expat: 2.1.0_3 [SaltStack]
	p5-Error: 0.17024 [FreeBSD]
	perl5: 5.20.3_11 [FreeBSD]
	cvsps: 2.1_1 [FreeBSD]
	p5-Authen-SASL: 2.16_1 [FreeBSD]
	p5-Digest-HMAC: 1.03_1 [FreeBSD]
	p5-GSSAPI: 0.28_1 [FreeBSD]
	p5-Net-SMTP-SSL: 1.03 [FreeBSD]
	p5-IO-Socket-SSL: 2.025 [FreeBSD]
	p5-Net-SSLeay: 1.74 [FreeBSD]
	p5-IO-Socket-IP: 0.37 [FreeBSD]
	p5-Socket: 2.021 [FreeBSD]
	p5-Mozilla-CA: 20160104 [FreeBSD]
...
New packages to be INSTALLED:
	py27-requests: 2.9.1 [SaltStack]
	py27-setuptools27: 20.0 [SaltStack]
...
[DEBUG   ] Note: checking out 'v2016.3.0rc2'.
...
 *  INFO: Cloning Salt's git repository succeeded
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
Updating SaltStack repository catalogue...
SaltStack repository is up-to-date.
All repositories are up-to-date.
[DEBUG   ] SaltStack repository is up-to-date.
All repositories are up-to-date.
The following 5 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	py27-tornado: 4.3 [SaltStack]
	py27-backports_abc: 0.4 [SaltStack]
	py27-singledispatch: 3.4.0.3 [SaltStack]
	py27-certifi: 2016.2.28 [SaltStack]
	py27-futures: 3.0.5 [SaltStack]
...
 *  INFO: Running config_freebsd_salt()
 *  INFO: Running install_freebsd_git()
[DEBUG   ] .... done
 *  INFO: Running config_freebsd_salt()
 *  INFO: Running install_freebsd_git()
Updating SaltStack repository catalogue...
[DEBUG   ] Updating SaltStack repository catalogue...
SaltStack repository is up-to-date.
All repositories are up-to-date.
The following 21 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	py27-salt: 2015.8.8_1 [SaltStack]
	py27-enum34: 1.0.4 [SaltStack]
	py27-yaml: 3.11 [SaltStack]
	py27-progressbar: 2.3 [SaltStack]
	py27-pycrypto: 2.6.1_1 [SaltStack]
	gmp: 5.1.3_3 [SaltStack]
	py27-Jinja2: 2.8 [SaltStack]
	py27-Babel: 2.2.0_1 [SaltStack]
	py27-pytz: 2016.1,1 [SaltStack]
	py27-MarkupSafe: 0.23 [SaltStack]
	py27-botocore: 1.4.5 [SaltStack]
	py27-docutils: 0.12 [SaltStack]
	py27-jmespath: 0.9.0 [SaltStack]
	py27-dateutil: 2.5.0 [SaltStack]
	py27-six: 1.10.0 [SaltStack]
	py27-msgpack-python: 0.4.7 [SaltStack]
	py27-libcloud: 0.20.1 [SaltStack]
	py27-pyzmq: 15.2.0_1 [SaltStack]
	libzmq4: 4.1.4_1 [SaltStack]
	openpgm: 5.2.122_2 [SaltStack]
	libsodium: 1.0.8 [SaltStack]
...
[21/21] Installing py27-salt-2015.8.8_1...
[21/21] Extracting py27-salt-2015.8.8_1: [DEBUG   ] . done
...
Installed packages to be REMOVED:
	py27-salt-2015.8.8_1
...
[1/1] Deinstalling py27-salt-2015.8.8_1...
[1/1] Deleting files for py27-salt-2015.8.8_1: .......... done
2016.3.0rc2
running install
...
Starting salt_minion.
 *  INFO: Running daemons_running()
 *  INFO: Salt installed!
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.0rc2
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Mar 19 2016, 01:13:51)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: amd64
        release: 10.1-RELEASE-p31
         system: FreeBSD
        version: Not Installed
```
