### ISSUE TITLE
salt.states.zpool.present does not support valid vdev types "disk" and "file"

### ISSUE THREAD

**Issue by cconrad** [saltstack/salt#32632]
## Description of Issue
zpool.present does not allow creating a zpool with a vdev type of "disk" or "file", both of which are valid on FreeBSD.

### Setup
```
tank:
  zpool.present:
    - layout:
        disk-0: /dev/da1
```

### Steps to Reproduce Issue
1. Apply the state defined above.

### Actual
State fails with `Comment: {'disk-0': 'not a valid vdev type'}` due to:

```python
if root_dev.split('-')[0] not in ['mirror', 'log', 'cache', 'raidz1', 'raidz2', 'raidz3', 'spare']:
    layout_valid = False
    layout_result[root_dev] = 'not a valid vdev type'
```

### Expected
`zpool create tank /dev/da1` to be run

### Versions
```
Salt Version:
           Salt: 2016.3.0rc2
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Mar 19 2016, 01:13:51)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: amd64
        release: 10.1-RELEASE-p31
         system: FreeBSD
        version: Not Installed
```

**Comment by cconrad** [comment]
Okay, I see it works as follows:

```yaml
tank:
  zpool.present:
    - layout:
        - /dev/da1
```
