### ISSUE TITLE
service.disabled for windows / win_service module in a state file

### ISSUE THREAD

**Issue by jayrehme** [saltstack/salt#32647]
I noticed that services don't get disabled if they are in "manual" state and not running, using, example:
```sls
dmwappushservice:
    service.disabled
```
I had to adjust my state as follows for desired results, which modifies the registry first putting it in disabled state (unless service doesn't exist on system) , then stopping the service if running (because I don't think service.disabled did that as well), and then disabling the service.  I'm ok with this, because it works, but its just not as clean as the above, maybe the module can be modified?  Thanks!
```sls
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dmwappushservice:
  reg.present:
    - vname: Start
    - vdata: 4
    - vtype: REG_DWORD
    - unless:
      - 'sc query dmwappushservice | find "does not exist" >nul'
service_dmwappushservice:
  service.dead:
   - name: dmwappushservice
   - onchanges:
        - reg: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dmwappushservice
dmwappushservice:
    service.disabled:
      - onchanges:
        - reg: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dmwappushservice
```
```yaml
Master (Ubuntu 14.04):
 Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```
```yaml
Minion (Windows 10 Enterprise):
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 10
         system: 10 10.0.10586  Multiprocessor Free
```
