### ISSUE TITLE
boto_vpc.route_table_present fails with KeyError: 'routes'

### ISSUE THREAD

**Issue by piersf** [saltstack/salt#32679]
Hi all
I've got the following state with which i'm trying to create a routing table in AWS:

```
pub_rt_exists:
  boto_vpc.route_table_present:
    - name: my_routing_table
    - vpc_name: my_vpc
    - routes:
      - destination_cidr_block: 10.1.0.0/16
        instance_id: ?????
        interface_id: ?????
        gateway_id: my_internet_gateway
    - subnet_names:
      - my_subnet1
      - my_subnet2
      - my_subnet3
    - region: us-east-1
    - keyid: {{ keyid }}
    - key: {{ key }}
    - require:
      - boto_vpc: my_vpc
```

When i try to execute the above state it fails and the exception i see is the below:

```
An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
                  self.gen.throw(type, value, traceback)
                File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
                  yield
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/boto_vpc.py", line 580, in route_table_present
                  keyid=keyid, profile=profile)
                File "/usr/lib/python2.6/site-packages/salt/states/boto_vpc.py", line 677, in _routes_present
                  if route not in route_table['routes']:
              KeyError: 'routes'
```

As you see above, i've set the **instance_id ** and  **interface_id** to "?"  (just in this post, not in the actual sls file) because i'm not really sure what their values should be. 
I assume that the instance_id is the ID of an EC2 instance, and the interface_id is the id of a network interface. 

1. If so, is the instace_id and interface_id indeed what i am assuming above ? Are those required for the boto_vpc.route_table_present state, considering that i might not have an EC2 instance running at the time of the routing table creation ?
2. Whether or not i provide the instance_id and the interface_id, the state always fails with the above error.

**Do i have any mistakes in my state, or is there a bug in this module ?**

My salt-master has the below info:

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.1.3.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.6 Santiago
```

And the salt-minion executing the state has the below info:

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.1.3.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.6 Santiago
```

Thank you in advance!

**Comment by commutecat** [comment]
Blame the developer ;-) 
According to boto documentation, 
http://boto3.readthedocs.org/en/latest/reference/services/ec2.html#EC2.Client.describe_route_tables

> InstanceId (string) -- The ID of a NAT instance in your VPC. The operation fails if you specify an instance ID unless exactly one network interface is attached.
NetworkInterfaceId (string) -- The ID of a network interface.


1. instance id are optional , needed for NAT
2. Subnet name are not yet inside boto/boto3 implementation. So it is in fact wrapped and used by salt.states.boto_vpc.subnet  , make sure you have that entry to use subnet name
3. You can set multiple destination CIDR.

**Comment by piersf** [comment]
@commutecat thank you for the answer.

Tried your suggestions, but still getting the same error. I ended up modifying my state as below. 
**I do have the boto_vpc.subnet_present state in the same sls file. **
Also, tried removing the interface_id, and have only the destination_cidr_block and gateway_id, but still the same exception is thrown. 


```
pub_rt_exists:
  boto_vpc.route_table_present:
    - name: my_routing_table
    - vpc_name: my_vpc
    - routes:
      - destination_cidr_block: 10.1.0.0/16
        interface_id: some_nic_id
        gateway_id: my_internet_gateway
    - subnet_names:
      - my_subnet1
      - my_subnet2
      - my_subnet3
    - region: us-east-1
    - keyid: {{ keyid }}
    - key: {{ key }}
    - require:
      - boto_vpc: my_vpc
      - boto_vpc: my_subnet1
      - boto_vpc: my_subnet1
      - boto_vpc: my_subnet1

```

**Comment by piersf** [comment]
So, i made some progress on this. While searching, came across this link http://docs.saltstack.cn/ref/states/all/salt.states.boto_vpc.html#salt.states.boto_vpc.route_table_present  which appears to be for version 2016.3.0-182-gbed98d8. It turns out, that i have to use just the  destination_cidr_block and **internet_gateway_name** , without using interface_id, instance_id, or gateway_id. If i use any of these three, it fail with the above exception.
And clearly the documentation here https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_vpc.html at the boto_vpc.route_table_present state needs updating/correcting.

So i ended up modifying my state as below:

```
pub_rt_exists:
  boto_vpc.route_table_present:
    - name: my_routing_table
    - vpc_name: my_vpc
    - routes:
      - destination_cidr_block: 10.1.0.0/16
        internet_gateway_name: local
      - destination_cidr_block: 0.0.0.0/0
        internet_gateway_name: my_internet_gateway
    - subnet_names:
      - my_subnet1
      - my_subnet2
      - my_subnet3
    - region: us-east-1
    - keyid: {{ keyid }}
    - key: {{ key }}
    - require:
      - boto_vpc: my_vpc
      - boto_vpc: my_subnet1
      - boto_vpc: my_subnet1
      - boto_vpc: my_subnet1
```

However, even with the progress made so far, it does not work as expected. If i use the two routes as seen right above, it will partially work. Meaning that it will create the route table, but it won't associate the defined subnets with it, it won't add the rule 0.0.0.0/0 --> IGW,  and it will also throw an error saying:

```
Internet gateway OrderedDict([('destination_cidr_block', '10.1.0.0/16'), ('internet_gateway_n
ame', 'local')]) does not exist
```

Then, if remove the first destination - target  (local), and run the state again, it will work fine. Meaning, that it will associate the define subnets with the routing table, and it will also add the rule 0.0.0.0/0 --> IGW in that table.

Apparently Salt does not understand the 'local' in the route table. 
What is the right way to let Salt know how to understand the 'local' in the routing table ?


Another thing is that when the VPC is created with boto_vpc.present state, it will also create a routing table which will be the default one for that VPC but without a "Name" tag. Is there a way to tell the boto_vpc.present not to create a routing table when creating the VPC ? My boto_vpc.present state is as below:

```
vpc_exists:
  boto_vpc.present:
    - name:  my_vpc
    - cidr_block: 10.1.0.0/16
    - dns_hostnames: True
    - region: us-east-1
    - keyid: {{ keyid }}
    - key: {{ key }}
```

**Comment by commutecat** [comment]
1. you cannot use interface_id AND  instance_id in the route if you don't have NAT. 

2. The problem of the multi route , is the way of how satlstack traverse data, you can't have same element key(e,g, destination_cidr_block and internet_gateway_name)  appear in one definition. I afraid they might need something such as this. Need somebody check this part of code to confirm this. 
```
- routes:
    - destination_cidr_block: 
       - 10.1.0.0/16
       - 10.2.3.0/24
    -  gateway_id
       - gw_id1
       - gw_id2 
```
In addition, this part of code just appear in the  2015.8.8. it will be easier if the developer that push the code explain this. 

3. Please take note that , AWS VPC API will create some default value.  This has nothing to do with boto_vpc.
i.  route table  - route to local  (that's mean you don't need to define local route) 
ii. VPC - default security group . default NACL .

**Comment by rallytime** [comment]
@piersf Thank you for your detailed response and excellent detective work here. That will be helpful in tracking this bug down. At the very least the docs need to be updated and clarified. We also need to clean up those stacktraces and provide some more helpful errors is certain combinations of values are causing issues.

Also thank you to @commutecat for the helpful responses on this issue.

I don't have time to look further into this issue right now, but @claudiupopescu or @tkwilliams might have some more input on this one.

**Comment by piersf** [comment]
@rallytime  thank you for your answer.

I'm seeing something very weird. I managed to create one routing table without issues - seen below:

```
pub_rt_exists:
  boto_vpc.route_table_present:
    - name: my_pub_routing_table
    - vpc_name: my_vpc
    - routes:
      - destination_cidr_block: 0.0.0.0/0
        internet_gateway_name: my_internet_gateway
    - subnet_names:
      - my_subnet1
      - my_subnet2
      - my_subnet3
    - region: us-east-1
    - keyid: {{ keyid }}
    - key: {{ key }}
    - require:
      - boto_vpc: my_vpc
      - boto_vpc: my_subnet1
      - boto_vpc: my_subnet1
      - boto_vpc: my_subnet1
```

The above runs just fine.

Then, i tried to create a second routing table, with a different name and associate with it different subnets - seen below:


```
priv_rt_exists:
  boto_vpc.route_table_present:
    - name: my_priv_routing_table
    - vpc_name: my_vpc
    - routes:
      - destination_cidr_block: 0.0.0.0/0
        internet_gateway_name: my_internet_gateway
    - subnet_names:
      - my_subnet4
      - my_subnet5
      - my_subnet6
    - region: us-east-1
    - keyid: {{ keyid }}
    - key: {{ key }}
    - require:
      - boto_vpc: my_vpc
      - boto_vpc: my_subnet4
      - boto_vpc: my_subnet5
      - boto_vpc: my_subnet6
```

When running state.highstate, the second routing table fails with the same exception again. 
It is really strange - the first routing table gets created fine, but the second fails. 
The only difference between the two states, is their name and subnets that are associated with them. All the rest are the same (routes, destination_cidr_block, internet_gateway_name, region, vpc, keyid, key). 

Nothing explains this behavior.

**Comment by ClaudiuPID** [comment]
@rallytime I stopped using my old account "claudiupopescu" and I am using this one now (long story).
@piersf when I was working with boto and saltstack my best bet was logging. And this is provided directly by AWS API. What you have to do is to set log_level_logfile to debug in your salt minion. After just follow the logs (on minion) and you will see AWS reply with very descriptive error messages.

**Comment by piersf** [comment]
@ClaudiuPID thank you for your time and suggestion.
Unfortunately, setting log_level_logfile to debug did not give any more information from what we already know. This is what i see in the minion's logs:

```
2016-05-02 09:43:32,611 [salt.state                                           ][INFO    ][30388] Running state [my_priv_routing_table] at time 09:43:32.611366 [10/868]
2016-05-02 09:43:32,612 [salt.state                                           ][INFO    ][30388] Executing state boto_vpc.route_table_present for my_priv_routing_table
2016-05-02 09:43:32,896 [salt.state                                           ][ERROR   ][30388] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1626, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1492, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1492, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/states/boto_vpc.py", line 580, in route_table_present
    keyid=keyid, profile=profile)
  File "/usr/lib/python2.6/site-packages/salt/states/boto_vpc.py", line 677, in _routes_present
    if route not in route_table['routes']:
KeyError: 'routes'

2016-05-02 09:43:32,896 [salt.state                                           ][INFO    ][30388] Completed state [my_priv_routing_table] at time 09:43:32.896395
```

I did not see any response coming from AWS, as you suggested above. Am i missing some other kind of debugging that i need to set on ?

By the way, if you have an example with the creation of two routing tables, would be very helpful - I could compare what i have with your example and see if i am missing anything. It should not be the case, as I've already posted above my states and if there was anything wrong, i would have heard by now.

**Comment by ClaudiuPID** [comment]
Did you restart the minion after changing the config file? I am asking because I see only INFO messages and ERROR but no DEBUG ones..
Although the error I see could be related to salt and it might not even reach the AWS API.
As for some examples, I am using a modified state file, older on, did not have time to merge with latest changes from upstream. So this will not help you.

**Comment by piersf** [comment]
Yes, did restart the minion after. I see some debug message where it loads the salt/yaml/jinja configs, the rendering of the init.sls file containing the states. And i see a debug message with the rendering of yaml, where it builds the OrderedDict (not pasting it all as it contains sensitive information):

```
2016-05-02 10:36:53,761 [salt.loaded.int.render.yaml                          ][DEBUG   ][9668] Results of YAML rendering:
OrderedDict([('vpc_exists', OrderedDict([('boto_vpc.present', [OrderedDict([('name', 'my_vpc')]),
.......
......
......  ('priv_rt_exists', OrderedDict([('boto_vpc.route_table_present', [OrderedDict([
('name', 'my_priv_routing_table')]), OrderedDict([('vpc_name', 'my_vpc')]), OrderedDict([('routes', [OrderedDict([('destination_cidr_bloc
k', '0.0.0.0/0'), ('internet_gateway_name', 'my_internet_gateway')])])]), OrderedDict([('subnet_names', ['my_subnet4
', 'my_subnet5', 'my_subnet6'])]), OrderedDict([('region', 'us-east-1')]), OrderedDict([('keyid', 'MYKEYID')]), OrderedDict([('key', 'MYKEY')]), OrderedDict([('require', [OrderedDict([('boto_vpc', 'vpc_exists')]), OrderedDict(
[('boto_vpc', 'igw_exists')]), OrderedDict([('boto_vpc', 'my_subnet4')]), OrderedDict([('boto_vpc', 'my_subnet5')]), OrderedDict([('boto_vpc', 'my_subnet6')])])])])]))])
```


Besides that, i see some other debugging message like:

```
2016-05-02 10:36:53,809 [salt.utils.lazy                                      ][DEBUG   ][9668] LazyLoaded boto.assign_funcs
2016-05-02 10:36:53,810 [salt.utils.lazy                                      ][DEBUG   ][9668] LazyLoaded boto_vpc.exists
2016-05-02 10:36:53,810 [salt.utils.lazy                                      ][DEBUG   ][9668] LazyLoaded boto_vpc.present
```

and like this one below which basically just says that the subnets/vpc's mentioned in the state are already there:

`2016-05-02 10:36:54,364 [salt.loaded.int.module.boto_vpc                      ][DEBUG   ][9668] The filters criteria {'filters': {'tag:Name': 'my_vpc'}} matched the following VPCs:[VPC:vpc-ID]`


What does not make sense to me, is why the first routing table in the init.sls file gets created just fine, but the next routing table has this issue. The only difference between them, is their names and the subnets that are associated with each of them.
If there was a bug in Salt code, then neither the first routing table would be created, logically.

**Comment by rickh563** [comment]
ZD-769

**Comment by piersf** [comment]
Hi,

Thank you for all the support !

Today i had the chance to meet one of the Saltstack engineers that was in our offices this week due to a Saltstack workshop. 
He took a look at the states and confirmed that everything was looking fine. As we were troubleshooting together, we managed to see where the issue was.

It turns out that the exception being thrown was very misleading and making us look for a bug or wrong configuration in the states. 
As i had my "require" prerequisites in the states, and i was running a "**state.highstate test=True**", the routing table that had a prerequisite was simply 
not being created because that prerequisite had not been applied yet. 
And instead of printing a message like Salt usually does with packages, e.g., "_This package failed as a prerequisite was not found_", 
it was printing the stacktrace which was very misleading.
After removing the "**test=True**" part and executing it, the routing tables got created fine.

However,

1. now when i execute the states by running: 

           salt -v 'minion' state.highstate state.sls cloud.aws 

the two routing table states get executed everytime(applies again the same settings), even though the routing tables do exist already in the VPC, and no changes have been made to the states in the sls file since the last run (see routing_table_output.txt).

The below two are more as an observation and general question:
- The second routing table (state ID: priv_rt_exists), is having a route to a NAT Gateway instead of an Internet Gateway. I couldn't find in the documentation a key called something like "nat_gateway_name" in order to add the NAT as a route. 
Using instance_id does not work. The only thing that works, is using "gateway_id". This way will add the NAT gateway as a route to the table,but it doesn't feel like is the right way. What is the right way to add a NAT gateway to a routing table?
   
- Does the boto_vpc support creation of NAT Gateways and Elastic IP's ? Nothing mentioned about this in the doc. Currently i'm doing this two manually.
   
I am attaching to this ticket the sls file and the execution output of the routing tables .


Thanks,
[init.sls.txt](https://github.com/saltstack/salt/files/264207/init.sls.txt)
[routing_table_output.txt](https://github.com/saltstack/salt/files/264209/routing_table_output.txt)

**Comment by pass-by-value** [comment]
Hi @piersf I would specifically like to address the first question

> the two routing table states get executed everytime(applies again the same settings), even though the routing tables do exist already in the VPC, and no changes have been made to the states in the sls file since the last run (see routing_table_output.txt)

I made a small change to your sls file and ran it (I used `state.sls`) multiple times, but the routes only got created the first time. Here's the updated sls (I took out `gateway_id` and added `gateway_name`)

```yaml
priv_rt_exists:
  boto_vpc.route_table_present:
    - name: my_priv_routing_table
    - vpc_name: my_vpc
    - routes:
      - destination_cidr_block: 0.0.0.0/0
        gateway_name: my-internet-gateway
    - subnet_names:
      - my_subnet4
      - my_subnet5
      - my_subnet6
    - region: us-east-1
    - keyid: {{ keyid }}
    - key: {{ key }}
    - require:
      - boto_vpc: vpc_exists
      - boto_vpc: igw_exists
      - boto_vpc: priv_sub_exists_1
      - boto_vpc: priv_sub_exists_3
      - boto_vpc: priv_sub_exists_5
```

I'm wondering where the hardcoded gateway_id `nat-0bf137r68a320a6b2` in the state `priv_rt_exists` (from your original init.sls) comes from?

Sorry if I'm misunderstanding the issue / use case you're trying to address.
