### ISSUE TITLE
git state does not take into account ssh config file

### ISSUE THREAD

**Issue by gidantribal** [saltstack/salt#32685]
Hello,

I want to use port 443 for targeting with ssh over https my repository. If I use ssh command manually I see it correclty uses port 433, but if I use the salt git state I am keeping using port 22.

**Comment by gidantribal** [comment]
```
          ID: git@altssh.bitbucket.org:443/agiambruno/dokuwiki
    Function: git.latest
      Result: False
     Comment: Failed to check remote refs: Unable to authenticate using identity file:

              ssh: connect to host altssh.bitbucket.org port 22: Connection refused
              fatal: Could not read from remote repository.

              Please make sure you have the correct access rights
              and the repository exists.
     Started: 18:37:46.929310
    Duration: 1046.393 ms
     Changes:

```

**Comment by gidantribal** [comment]
As a proof I tried to rungit manually (with state.cmd) and it works flawlessly (the uncommented block):

```
checkout-dokuwiki-repository:
  cmd.run:
    - name: git clone git@bitbucket.org:user/dokuwiki.git /var/www/html/wiki
    - user: root
    - require:
      - /root/.ssh/id_rsa
      - /root/.ssh/id_rsa.pub
      - /root/.ssh/known_hosts
      - /root/.ssh/config
      - cmd: activate-ssh-agent
      - pkg: packages_apache_php

#git@bitbucket.org:user/dokuwiki.git:
#  git.latest:
#    - user: root
#    - identity: "/root/.ssh/id_rsa"
#    - target: /var/www/html/wiki
#     - require:
#        - /root/.ssh/id_rsa
#        - /root/.ssh/id_rsa.pub
#        - /root/.ssh/known_hosts
```
