### ISSUE TITLE
Modify recursive ownership management of file.directory

### ISSUE THREAD

**Issue by mallniya** [saltstack/salt#32707]
### Description of Issue/Question
Hi, I wonder if there is a way to apply mode/user/group attributes in file.directory requisite only to content of directory, but not to directory itself.

### Setup
For example:
```
/usr/local/etc/namedb/:
  file.directory:
    - user: bind
    - group: bind
    - dir_mode: 755
    - file_mode: 644
    - recurse:
      - user
      - group
      - mode
```
will apply mode/user/group for /usr/local/etc/namedb/ and for all it's content as expected. But all directories in /usr/local/etc/ by default owned by root:wheel, which I don't want to change -- I want /usr/local/etc/namedb/ stays owned by root:wheel and it's content by bind:bind. So if there is a workaround to do so?

### Versions Report
```
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.3.1
         Python: 2.7.11 (default, Feb 29 2016, 14:33:19)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: amd64
        release: 10.2-STABLE-r286912
```
