### ISSUE TITLE
win_dacl.present: Specifying propagations for a directory fails 

### ISSUE THREAD

**Issue by joakimkarlsson** [saltstack/salt#32705]
### Description of Issue/Question
When you specify an ACE to be added to the DACL for a directory on windows, the propagation type `this folder, subfolders, and files` doesn't work:

### Setup
```yaml
my-dir:
  - objectType: directory
  - user: domain\user
  - permission: fullcontrol
  - propagation: this folder, subfolders, and files
```

This is caused by the following line https://github.com/saltstack/salt/blob/develop/salt/modules/win_dacl.py#L158

Where the key in `validPropagations[win32security.SE_FILE_OBJECT]` is as follows (note the lowercase 'and'):

```python
'THIS FOLDER, SUBFOLDERS, and FILES': {
    'TEXT': 'this folder, subfolders, and files',
    'BITS': win32security.CONTAINER_INHERIT_ACE | win32security.OBJECT_INHERIT_ACE},
```

Since the propagation string from the sls file is made uppercase and then used as key in `getPropagationBit()` etc., it won't match because of the lower case 'and' in win_dacl.py.
