### ISSUE TITLE
ssh_known_hosts doesn't take into account ssh configuration file

### ISSUE THREAD

**Issue by gidantribal** [saltstack/salt#32711]
When I try to add a host to known hosts with this function and I don't have access to SSH on port 22 I can't do the HTTPS forwarding, because if I modify the ssh/config file before running this state and telling to forward to port 433 the configuration is just ignored.

```
bitbucket.org:
  ssh_known_hosts:
    - present
    - enc: rsa
    - fingerprint: 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40
    - timeout: 60
    - user: root
    - require:
      - file: /etc/ssh/ssh_known_hosts
      - file: /root/.ssh/config
```

The SSH config file:

> Host bitbucket.org
>   IdentityFile /root/.ssh/id_rsa
>   HostName altssh.bitbucket.org
>   Port 443
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
