### ISSUE TITLE
Rosters for 'salt' for targeting systems ( similar to salt-ssh rosters )

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#32723]
I'd like to be able to give my users the ability to create their own inventory/roster files and use those purely for targeting with the salt command.  We don't allow our salt users to modify the master.conf, so they can't add in their own nodegroups for using to target their commands and scripts with.

This is similar to #5787, but may be less functionality than others are looking for, but I'm really just looking for a way for people to create a file with shortcut names that expand into targeting criteria, which functions similarly to how nodegroups do, but our use case is purely for targeting.

In essence:

```
salt -a pam -U webgroup test.ping
```

And in /home/sjmh/.inventory.sls

```
groups:
  webgroup: 'G@os:RedHat and S@192.168.0/24'
  web1: 'U@webgroup and not web2*'
  web2: 'U@webgroup and not web1*'
```

This would be pretty similar to how the Salt Ansible Roster module works.  Perhaps the best approach may be to extend rosters to be usable by the 'salt' command rather than just 'salt-ssh'
