### ISSUE TITLE
pkg.latest does not update from ppa

### ISSUE THREAD

**Issue by duk3luk3** [saltstack/salt#32746]
### pkg.latest does not install newer version from ppa

I am using salt-ssh.

### Setup

Ubuntu 14.04 Server

```
{# Set up software-properties-common so we get add-apt-repository #}
'software-properties-common':
  pkg.installed
{# Install haproxy #}
install_haproxy_ppa:
  pkgrepo.managed:
    - ppa: vbernat/haproxy-1.6
haproxy:
  pkg.latest:
    - refresh: true
    - fromrepo: ppa:vbernat/haproxy-1.6
```

### Steps to Reproduce Issue

* Install works:

On fresh Ubuntu 14.04 server: Executing above formula works and installs newest version of haproxy from ppa.

* Update does not work:

On fresh Ubuntu 14.04 server:
1. `sudo aptitude install haproxy`
2. Execute formula

Result: "haproxy is already the newest version" -> ubuntu version of haproxy is not updated

### Versions Report

```
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: Not Installed
                  RAET: Not Installed
                   ZMQ: Not Installed
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```
