### ISSUE TITLE
salt.states.mount.mounted does not like uid/gid added to mount_invisible_keys

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#32748]
### Description of Issue/Question
When uid and or gid are added to the **extra_mount_invisible_keys** property for mount.mounted there will be an exception:

```yaml
----------
          ID: plex.server::logs
    Function: mount.mounted
        Name: /data/plex/Logs
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python2.7/site-packages/salt/state.py", line 1703, in call
                  **cdata['kwargs'])
                File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 1650, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python2.7/site-packages/salt/states/mount.py", line 333, in mounted
                  _givenid = opt.split('=')[1]
              IndexError: list index out of range
     Started: 16:01:07.188078
    Duration: 127.41 ms
     Changes:   

```

### Setup
n/a

### Steps to Reproduce Issue
Use the mount.mounted state and add uid or gid to extra_mount_invisible_keys

### Versions Report
```yaml
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: 1.5.1
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: 2.0.2
         PyYAML: 3.11
          PyZMQ: 14.0.1
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@sjorge, thanks for reporting.

**Comment by sjorge** [comment]
Adjust were needed but this is a simple state snippet that triggers it for me:
```yaml
lex.server::logs:
  mount.mounted:
    - name: /data/plex/Logs
    - device: tmpfs
    - fstype: tmpfs
    - opts: rw,size=64m,mode=0750,uid=plex,gid=plex
    - dump: 0
    - pass_num: 0
    - persist: True
    - mkmnt: True
    - extra_mount_invisible_keys:
        - size
        - mode
        - uid
        - gid
```
