### ISSUE TITLE
archive.extracted chowns a lot more than it should

### ISSUE THREAD

**Issue by ScoreUnder** [saltstack/salt#32753]
### Description of Issue/Question

`archive.extracted`, when given a `user` or `group`, changes ownership on every file under `name`, rather than just those provided by the archive.

This means that extracting archives into "busy" places like `/etc` or OSX's `/Applications` while supplying a `user`/`group` can have disastrous effects.

https://github.com/saltstack/salt/blob/be136832d59649db3eb140cd0b258c059b79d9bf/salt/states/archive.py#L329

Possible solutions:
- Only chown from `if_missing` and below, if that parameter is passed
- Parse tar's output (`tar tfz file.tar.gz`) to see what files it has extracted, and chown them (being careful to chown symlinks rather than their targets, etc.)
### Setup

``` yaml
my_app:
  archive.extracted:
    - name: /Applications
    - if_missing: /Applications/MyApp.app
    - source: salt://apps/MyApp.tar.gz
    - archive_format: tar
    - user: root
    - group: wheel
    - tar_options: z
```
### Steps to Reproduce Issue

Run the above state on a mac. Make sure you don't mind your permisssions on `/Applications` getting overwritten... Provide any tar.gz file under `salt://apps/MyApp.tar.gz`, in the end it doesn't matter what it contains.
It will probably work on other Linux/Unix systems too, you just need to edit the paths.
### Versions Report

```
bash-3.2$ salt --versions-report
Salt Version:
           Salt: 2016.3.0-242-g5096d33

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.10 (default, Jul 14 2015, 19:46:27)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:   
        machine: x86_64
        release: 14.5.0
         system: Darwin
        version: 10.10.5 x86_64
```
