### ISSUE TITLE
Multiprocessing logging queue exception after minion reconnects

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/salt#32750]
### Description of Issue/Question
If minion is started when master is down it reports about an exception occured in the multiprocessing logging queue and hangs.

### Setup
```yaml
master:
    localhost
master_type: failover
master_alive_interval: 30
```

### Steps to Reproduce Issue
1. Don't start master
2. Start minion and wait 1-3 `** Restarting minion **` messages
3. Result:
```
[WARNING ] ** Restarting minion **
[INFO    ] waiting random_reauth_delay 2s
[WARNING ] An exception occurred in the multiprocessing logging queue thread: [Errno 3] No such process
```
After this minion stays not responsive and if master is back it doesn't connects to.

### Versions Report
Develop branch
```
Salt Version:
           Salt: 2016.3.0-401-g2bf3b7f
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.1.0
       dateutil: 2.5.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Mar 31 2016, 06:18:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.5.1-1-ARCH
         system: Linux
        version: Not Installed
```
