### ISSUE TITLE
pkg.installed bug with Mint LMDE

### ISSUE THREAD

**Issue by lossendae** [saltstack/salt#32764]
### Description of Issue/Question

When I execute salt-call --local state.apply, all my sls files are failing :

```salt
local:
----------
          ID: common-pkgs
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'tools'
              Reason: 'pkg' __virtual__ returned False
     Started: 
    Duration: 
     Changes: 
```

### Setup

```yaml
common-pkgs:
  pkg.installed:
    - pkgs:
      - curl
      - htop
      - iotop
      - rsync
      - tmux
      - chromium
      - gitk
      - tree
      - locate
      - nginx
      - keepass2
      - mono-dmcs
      - libmono-system-management4.0-cil
```

### Steps to Reproduce Issue

`sudo salt-call state.apply -l debug bootstrap`

### Versions Report

```salt
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: LinuxMint 2 betsy
        machine: x86_64
        release: 3.16.0-4-amd64
         system: LinuxMint 2 betsy
```
