### ISSUE TITLE
common.certificate does not detect changes in emailaddress

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#32774]
### Description of Issue/Question
common.certificate does not detect changes in emailaddress

### Setup
pass 1
```yaml
certificate.key::Jorge Schrauwen:
  x509.private_key_managed:
    - name: /opt/local/etc/pki/Jorge Schrauwen.key
    - bits: 2048
    - require:
        - file: certificate::keystore

certificate.crt::Jorge Schrauwen:
  x509.certificate_managed:
    - name: /opt/local/etc/pki/Jorge Schrauwen.crt
    - ca_server: cronos
    - signing_policy: client
    - public_key: /opt/local/etc/pki/Jorge Schrauwen.key
    - CN: Jorge Schrauwen
    - E: sjorge@acheron.be
    - days_valid: 365
    - days_remaining: 7
    - backup: True
    - require:
        - x509: certificate.key::Jorge Schrauwen
```

pass 2
```yaml
certificate.key::Jorge Schrauwen:
  x509.private_key_managed:
    - name: /opt/local/etc/pki/Jorge Schrauwen.key
    - bits: 2048
    - require:
        - file: certificate::keystore

certificate.crt::Jorge Schrauwen:
  x509.certificate_managed:
    - name: /opt/local/etc/pki/Jorge Schrauwen.crt
    - ca_server: cronos
    - signing_policy: client
    - public_key: /opt/local/etc/pki/Jorge Schrauwen.key
    - CN: Jorge Schrauwen
    - E: sjorge@blackdot.be
    - days_valid: 365
    - days_remaining: 7
    - backup: True
    - require:
        - x509: certificate.key::Jorge Schrauwen
```

minion signing policies
```yaml
x509_signing_policies:
  server:
    - minions: '*'
    - signing_private_key: /salt/pki/ca.key
    - signing_cert: /salt/pki/ca.crt
    - O: XXX
    - C: XXX
    - ST: XXX
    - L: XXX
    - Email: certadm@acheron.be
    - basicConstraints: "critical CA:false"
    - keyUsage: "digitalSignature,keyEncipherment"
    - extendedKeyUsage: "critical serverAuth"
    - subjectKeyIdentifier: hash
    - authorityKeyIdentifier: keyid,issuer:always
    - copypath: /salt/pki/issued/
  client:
    - minions: '*'
    - signing_private_key: /salt/pki/ca.key
    - signing_cert: /salt/pki/ca.crt
    - O: XXX
    - C: XXX
    - ST: XXX
    - L: XXX
    - basicConstraints: "critical CA:false"
    - keyUsage: "digitalSignature,keyEncipherment"
    - extendedKeyUsage: "critical clientAuth,emailProtection"
    - subjectKeyIdentifier: hash
    - authorityKeyIdentifier: keyid,issuer:always
    - copypath: /salt/pki/issued/
```

### Steps to Reproduce Issue
generate a certificate, change the emailaddress, run the state again

### Versions Report
```yaml
Salt Version:
           Salt: 2016.3.0rc2-11-gfa8d030

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.11 (default, Mar 18 2016, 13:38:08)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: 1.5.2
       cherrypy: 3.8.0
       dateutil: 2.4.0
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: 0.9.0
        timelib: 0.2.4

System Versions:
           dist:
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
