### ISSUE TITLE
win_pkg: msiexec parameter does not allow MSP patch files to be applied

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#32780]
When creating a package definition, setting "msiexec: True" forces the msiexec option "/i" for installs, or "/x" for uninstalls. This prevents the use of the "/p" which is used to apply a patch to an already installed MSI package. A patch may increase the version number and so is potentially equivalent to a package upgrade. 
- "msiexec /i /p" is not a valid combination of switches so you cannot override "/i" by setting "/p" in the install_flag string
- setting "msiexec: False" and using "msiexec.exe" as the installer will result in cache_path not being set so you cannot reference a cached patch file in the install_flags string. It also means the cache_dir parameter cannot be used (since there is no inferred salt:// installer path)
- setting "msiexec: True" and applying a patch with "/update" or "PATCH=" requires a fully qualified path to the patch files, which isn't available as a core grain or environment variable

As a workaround, without resorting to hard-coding paths or running batch files, you can glue together the fully qualified location of the minion cache and reference that to apply a patch:

```
{% set minion_cache_path = (opts['cachedir'] ~ '\\files\\' ~ saltenv ~ '\\win\\repo-ng\\my_app') | replace('\\','\\\\') %}

my_app:
  '5.5.3':
    full_name: 'My App'
    installer: 'salt://win/repo-ng/my_app/MyApp.msi'
    install_flags: 'ALLUSERS=2 /update {{ minion_cache_path }}\\MyApp553.msp /qn /norestart'
    uninstaller: '{C7AD892D-4D6C-4444-B6D7-30AFA6147466}'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    cache_dir: True
```

...but this doesn't look too pretty when all that was required was to run `msiexec /p MyApp553.msp /qn /norestart`. It also results in the whole directory being re-hashed since both the original installer and the patch file must be referenced.

I would like to suggest the addition of an extra package definition parameter, which when set would imply the msiexec option "/p" in-place of option "/i", e.g. "msiexec_patch: True".

Tested on Salt version 2015.8.8.2

**Comment by jfindlay** [comment]
@morganwillcock, thanks for the report.  Ping @thebigbear, @twangboy.

**Comment by damon-atkins** [comment]
ping me @damon-atkins

**Comment by sbarnden** [comment]
Was encountering this issue but the workaround described of setting a minion_cache_path was not working as it was not picking up the saltenv correctly. 

I was running with a saltenv=test and the msi install files were being cached at: 
`c:\salt\var\cache\salt\minion\files\test\win\repo-ng\
`
However the minion_cache_path being generated was always pointing to:
`c:\salt\var\cache\salt\minion\files\base\win\repo-ng\
`
Which was empty. Could not figure out how to get this path to be generated correctly but did stumble on a different solution that relies on the fact that the msi is run from the cache directory and msiexec is called using cmd. Created a repo definition of:
```
MyApp:
  '1.0':
    installer: 'salt://win/repo-ng/MyApp/MyApp.1.0.msi'
    full_name: MyApp
    install_flags: '/qn '
    uninstaller: 'MsiExec.exe'
    uninstall_flags: '/X{B5B5868F-23BA-297A-917D-0DF345TF5764} /qn'
  '1.1':
    installer: 'salt://win/repo-ng/MyApp/MyApp.1.0.msi'
    full_name: MyApp
    install_flags: '/qn /update "%cd%\\MyApp.1.1.msp" '
    uninstaller: '{B5B5868F-23BA-297A-917D-0DF345TF5764}'
    msiexec: True
    cache_dir: True
    uninstall_flags: '/qn'
```

The `%cd%` will resolve to the current working directory, which according to the minion log file was:
`c:\salt\var\cache\salt\minion\files\test\win\repo-ng\MyApp
`
The installer now seems to work and apply the MSP file correctly in my case. Of course this only works so long as the MSP and MSI files are in the same directory and cached together.
