### ISSUE TITLE
Add stdin support to cmd.run (in cmd state module)

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#32809]
### Description of Feature Request

The `cmd.run` function from the `cmd` execution module has a `stdin` argument that can be used to pass data via the command's standard input.  It would be nice if the `cmd` state module also had a way to pass input to a command.

Examples:

```
foo:
  cmd.run:
    - stdin: |
        this is the first line of data fed to foo's stdin
        second line
        etc.
bar:
  cmd.run:
    - stdin_url: salt://bar.stdin
baz:
  cmd.run:
    - stdin_url: salt://baz.stdin
    - stdin_url_template: jinja
bif:
  cmd.run:
    - stdin_pillar: bif:stdin
asdf:
  cmd.run:
    - stdin_grains: asdf:stdin
```
