### ISSUE TITLE
archive.extracted now has unexpected/wanted behavior after 66ba35261cb4775e196ef738979914f8aaaddf4f

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#32801]
### Description of Issue/Question
This seems to have resulted in 'if_missing' to be creates as a directory if something is provided.

```yaml
account.profile.base::{{ login }}:
  archive.extracted:
    - name: /home/{{ login }}
    - if_missing: /home/{{ login }}/.salt-profile-base
    - archive_format: tar
    - source:
        - salt://common/account/_files/profile-base.tar.gz.{{ salt.grains.get('os')|lower }}
        - salt://common/account/_files/profile-fallback.tar.gz
    - user: {{ login }}
    - group: {{ group }}
    - require:
        - user: account.user::{{ login }}
  file.managed:
    - name: /home/{{ login }}/.salt-profile-base
    - user: {{ login }}
    - group: {{ group }}
    - contents: '## salt marker file ##'
    - watch:
        - archive: account.profile.base::{{ login }}
```

The above snippet extracts the archive and used to create .salt-profile-base as a marker file.
So get a update profile the user just has to remove the marker and it will be updated next profile run.

However after this commit it seems to archive.extracted seems to create the location specified in if_missing as a directory.

Even when removing the file.managed one, a directory with the path of if_missing shows up. (I checked that it was not in the archive. This is also easily verified by changing the if_missing to something else to test.

This new odd behavior seems to come form this commit as my minions running a pure 2016.3rc2 do not suffer from this. Only the ones I updated today tracking the 2016.3 branch.

Also assuming that if_missing is always a directory is probably not desired.

### Setup
See above for an example snippet.

### Steps to Reproduce Issue
Put a random path in if_missing and it will end up as a directory.

### Versions Report
2016.3 as of 2016/04/23 @ ~20:00
```yaml
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.8.0
       dateutil: 2.4.0
          gitdb: 0.6.4
      gitpython: 2.0.0
          ioflo: 1.5.1
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Mar 18 2016, 13:38:08)
   python-gnupg: 2.0.2
         PyYAML: 3.11
          PyZMQ: 14.4.1
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.3

System Versions:
           dist:
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
