### ISSUE TITLE
Issues with Winrepo

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#32831]
### Description of Issue/Question
There are many issues that need to be addressed in winrepo

- [ ] How to handle auto updating software (don't downgrade if a newer version is installed unless you want to force it). It seems to happen when there's a newer version that is not defined in the software definition.
- [ ] Ability to use a `.msp` file when installing an `.msi`

**Comment by morganwillcock** [comment]
I've spent the last couple of weeks packaging software, the biggest problem I've found so far is incorrect detection of state based on name collisions. As an example, Visual C++ 2005 runtime packages will install together, but state checks will fail based on the identical full_name:
```
salt-winrepo-ng$ grep -h full_name ms-vcpp-2005*.sls
    full_name: 'Microsoft Visual C++ 2005 Redistributable (x64)'
    full_name: 'Microsoft Visual C++ 2005 Redistributable'
    full_name: 'Microsoft Visual C++ 2005 Redistributable (x64)'
    full_name: 'Microsoft Visual C++ 2005 Redistributable'
    full_name: 'Microsoft Visual C++ 2005 Redistributable (x64)'
    full_name: 'Microsoft Visual C++ 2005 Redistributable'
    full_name: 'Microsoft Visual C++ 2005 Redistributable (x64)'
    full_name: 'Microsoft Visual C++ 2005 Redistributable'
```
I've found that I can work around the downgrade issue with state dependencies, effectively pinning package versions at a minimum level:
```
adobe_flash_player_plugin:
  pkg.installed:
    - version: '21.0.0.213'
    - watch:
      - module: adobe_flash_player_plugin_upgrade_available

adobe_flash_player_plugin_upgrade_available:
  module.run:
    - name: pkg.upgrade_available
    - m_name: adobe_flash_player_plugin
```
For packages upgrades that use a patch file, perhaps the best option would be to allow the cache path to be set manually (to a file or a directory) rather than always inferred from the installer path. Letting you control the caching yourself would let you do whatever you like for any type of installer and I think this would solve a lot of issues where caching is conflicting with install options (while still retaining backwards compatibility):
```
installer: 'msiexec.exe'
install_flags: '/p MyApp553.msp /qn /norestart'
msiexec: False
cache_dir: True
cache_path: 'salt://win/repo-ng/my_app'
```
```
installer: 'msiexec.exe'
install_flags: '/p MyApp553.msp /qn /norestart'
msiexec: False
cache_dir: False
cache_path: 'salt://win/repo-ng/my_app/MyApp553.msp'
```
Apologies for the lengthy comment...
