### ISSUE TITLE
Memory leak in salt master worker threads

### ISSUE THREAD

**Issue by ywahl** [saltstack/salt#32860]
### Description of Issue/Question

Using a external pillar module following https://docs.saltstack.com/en/latest/topics/development/external_pillars.html

We observe a memory leak that slowly consumes all the memory of the server running the master.

The code of the external pillar module is 

```py
from __future__ import absolute_import
import os
import sys
import logging

log = logging.getLogger(__name__)


pil = {'root_private_pillar' : {'vms':{'master1' : 1}}}

def ext_pillar(minion_id, pillar, command):
    my_pillar = pil
    '''
    minion_id is hostname-xxxxxxxx random string of 33 characters
    '''
    m = minion_id[:len(minion_id) - 33]
    if m in my_pillar['root_private_pillar']['vms']:
        my_pillar['root_private_pillar']['my_self'] = my_pillar['root_private_pillar']['vms'][m]
    else:
        log.critical('%s not present in pillar' % m)
    return my_pillar
```

### Setup
master config:
 ```sls
file_recv: True
interface: 0.0.0.0
interface: '::'
ipv6: True
worker_threads: 10
extension_modules: /srv/private_mods/
auto_accept: True
log_level: info
log_level_logfile: info
master_id: master1
ext_pillar:
  - private_pillar: getPillar.xml
rest_cherrypy:
  port: 8000
  host: '::'
  ssl_crt: /etc/pki/tls/certs/cert.pem
  ssl_key: /etc/pki/tls/certs/key.pem
external_auth:
  pam:
    saltuser:
      - .*
      - '@runner'
file_roots:
   base:
     - /srv/salt/
```
### Steps to Reproduce Issue
To accelerate memory leak consumption run
```
while true; do salt '*' saltutil.refresh_pillar; done
```

### Versions Report
```yaml
salt --versions-report
           Salt: 2015.5.8
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.4.1
```

**Comment by jfindlay** [comment]
@ywahl, thanks for reporting.  I can confirm this with 2015.8.8.

### configs
```yaml
# cat /etc/salt/master
log_fmt_console: '%(colorlevel)s %(colormsg)s'
extension_modules: /srv/ext
ext_pillar:
  - private_pillar: getPillar.xml
```
```yaml
# cat /etc/salt/minion
log_fmt_console: '%(colorlevel)s %(colormsg)s'
master: localhost
```
```console
root@jmoney-debian-8:~# tree /srv
/srv
├── ext
│   └── pillar
│       ├── leak.py
│       └── leak.pyc
└── salt

3 directories, 2 files
```
```py
# cat /srv/ext/pillar/leak.py
from __future__ import absolute_import
import os
import sys
import logging

log = logging.getLogger(__name__)


pil = {'root_private_pillar' : {'vms':{'master1' : 1}}}

def ext_pillar(minion_id, pillar, command):
    my_pillar = pil
    '''
    minion_id is hostname-xxxxxxxx random string of 33 characters
    '''
    m = minion_id[:len(minion_id) - 33]
    if m in my_pillar['root_private_pillar']['vms']:
        my_pillar['root_private_pillar']['my_self'] = my_pillar['root_private_pillar']['vms'][m]
    else:
        log.critical('%s not present in pillar' % m)
    return my_pillar
```

### commands
```sls
# salt jmoney-debian-8 test.ping
jmoney-debian-8:
    True
```
```console
# free -m
             total       used       free     shared    buffers     cached
Mem:          2010        830       1179          5         36        453
-/+ buffers/cache:        340       1670
Swap:            0          0          0
```
```console
# for i in {1..101} ; do salt jmoney-debian-8 saltutil.refresh_pillar &> /dev/null ; done
# free -m
             total       used       free     shared    buffers     cached
Mem:          2010       1436        574          5         38        456
-/+ buffers/cache:        941       1069
Swap:            0          0          0
```
```console
# pkill -9 salt-master
# free -m
             total       used       free     shared    buffers     cached
Mem:          2010        655       1354          5         38        456
-/+ buffers/cache:        160       1849
Swap:            0          0          0
```

### versions
```yaml
# salt --versions
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.3
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3
```
