### ISSUE TITLE
salt-cloud doesn't map new minion to new salt master/syndic

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#32864]
### Description of Issue/Question
In the salt-cloud map docs, there is a section for [setting up new salt masters](https://docs.saltstack.com/en/develop/topics/cloud/map.html#setting-up-new-salt-masters)

In my environment, I am running salt-cloud from a master of masters ("mom") and am trying to use a map file to create a syndic master and its minions by specifying one of the hosts should be the new master via `make_master:True` parameter.

Unfortunately, I am encountering three problems:

(1) On run of the map, salt-cloud creates the syndic, but at the end it errors-out with the following message

```
Error: There was a query error: Host for new master l-syndic-101.mycompany.com was not found, aborting map
```

The host is in DNS, I can ping the host from the "mom", so I'm not sure why salt-cloud doesn't like this host.

I figure at this point, I can just try the map file again. Salt-cloud sees that the syndic exists so goes on to create the minion. The salt-minion service fails to start due to the remaining two problems

(2) The minion's config file is showing `master: salt` instead of the expected `master: l-syndic-101.mycompany.com`

(3) If I do a 'salt-key' on the "mom" I find the minion's key in the accepted key list.

It seems what I am trying to do is not working at all. Is this expected functionality? Is it possible to build a syndic and it's minions from the mom from a salt-cloud map file?

### Setup
map file `lab-generic`
```
lab-generic-syndic:
  - l-syndic-101.mycompany.com:
      make_master: True
      minion:
        master: s-cdc-stmom-01.mycompany.com
        local_master: True
      master:
        syndic_master: s-cdc-stmom-01.mycompany.com
lab-generic-tiny:
  - l-minion-101.mycompany.com
```

profile `lab-generic-syndic`
```
lab-generic-syndic:
  devices:
    network:
      Network adapter 1:
        name: VLAN641
        switch_type: standard
  grains:
    platform:
      name: lab
      ou: kar
      realm: nonprod
    roles:
      - syndic
  memory: 2GB
  num_cpus: 1
  provider: lab
  clonefrom: rhel6xnonprodtemplate.mycompany.com
  datacenter: CARMEL
  datastore: Pure-CDC
  cluster: CVEP-LX
  folder: JBOSS
  ssh_username: REDACTED
  password: REDACTED
  domain: REDACTED
```

profile `lab-generic-tiny`
```
lab-generic-tiny:
  devices:
    network:
      Network adapter 1:
        name: VLAN641
        switch_type: standard
  grains:
    platform:
      name: lab
      ou: kar
      realm: nonprod
  memory: 2GB
  num_cpus: 1
  provider: lab
  clonefrom: rhel6xnonprodtemplate.mycompany.com
  datacenter: CARMEL
  datastore: Pure-CDC
  cluster: CVEP-LX
  folder: JBOSS
  ssh_username: REDACTED
  password: REDACTED
  domain: REDACTED
```

provider `lab`
```
lab:
  driver: vmware
  user: 'REDACTED'
  password: 'REDACTED'
  url: 'REDACTED'
  protocol: 'https'
  port: 443
```

### Steps to Reproduce Issue

salt-cloud -m lab-generic -l debug -P

### Versions Report

salt --versions from the mom. Other hosts should be similar

```
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
           Mako: 0.3.4
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.20.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.20.3
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.7 Santiago
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.7 Santiago
```
