### ISSUE TITLE
boto_vpc execution module--request for comment/guidance

### ISSUE THREAD

**Issue by gladiatr72** [saltstack/salt#32885]
[`modules.vpc_boto._find_vpcs()`](https://github.com/saltstack/salt/blob/develop/salt/modules/boto_vpc.py#L432) takes:
- vpc_id
- vpc_name
- cidr
- tags
- region
- key
- keyid
- profile

My question involves how it applies API filters--It goes through `vpc_id`, `cidr`, `tag:Name` and whatever tags are submitted in the tags dict and applies them serially to the `filter_parameters` dictionary. 

If only one of the search terms is provided, all is well; however, when `modules.vpc_boto.exists()` calls [`_find_vpcs()`](https://github.com/saltstack/salt/blob/develop/salt/modules/boto_vpc.py#L432) with all the bits passed in from [`states.boto_vpc.present()`](https://github.com/saltstack/salt/blob/develop/salt/states/boto_vpc.py#L152) things get kind of screwy.

Given this state definition:

``` yaml
a vpc of some sort exists:
  boto_vpc.present:
     - name: some_vpc
     - region: us-west-2
     - cidr_block: 10.64.32.0/21
     - instance_tenancy: default
     - dns_support: True
     - dns_hostnames: True
     - tags:
         owner: me
         region: us-west-2
         role: public
```

It works great if you don't touch it again.  Ever.  For anyone reading that might not be familiar with the API, once a vpc is created, the assigned subnet and tenancy can't be changed and are left out of the `boto_vpc.exists()` call.  

The problem arises when you add a tag.  There is currently no logic to update any of the mutable vpc attributes, but the tag dict is the only one of those attributes that is submitted for building a search filter.  

The state checks for the [existence of the named vpc](https://github.com/saltstack/salt/blob/develop/salt/states/boto_vpc.py#L152).  If It returns `False`, the assumption is that a new VPC is needed.  Any change to the tag list causes `boto_vpc.exists()` to return `False` causing the code in the state module to happily go about its business of creating another vpc, or, rather, attempting to.

It seems to me that converting:

`_get_vpcs()`

```
    if vpc_id:
        filter_parameters['vpc_ids'] = [vpc_id]

    if cidr:
        filter_parameters['filters']['cidr'] = cidr

    if vpc_name:
        filter_parameters['filters']['tag:Name'] = vpc_name

    if tags:
        for tag_name, tag_value in six.iteritems(tags):
            filter_parameters['filters']['tag:{0}'.format(tag_name)] = tag_value
```

to 

```
    if vpc_id:
        filter_parameters['vpc_ids'] = [vpc_id]
    elif vpc_name:
        filter_parameters['filters']['tag:Name'] = vpc_name
    elif cidr:
        filter_parameters['filters']['cidr'] = cidr
    elif tags:
        for tag_name, tag_value in six.iteritems(tags):
            if tag_name != 'name':
                filter_parameters['filters']['tag:{0}'.format(tag_name)] = tag_value
```

I could also see adding logic that would first look for the `id or ( name or cidr )`. If the resulting dictionary has more than one item, use the tags to fine-tune.

Another angle would be to, at least for now, remove the tag list from the `.exists()` call in the `.present()` state.  

Anyway, yes.  I look forward to reading your response.

**Comment by jfindlay** [comment]
@gladiatr72, thanks for reporting.  I know very little about how boto works, but @thedrow, @mgwilliams, @ClaudiuPID, or @ryan-lane may have better answers than I.

**Comment by ClaudiuPID** [comment]
I wasn't involved in this recently, but what @gladiatr72 proposed makes sense.
There should be one anchor (for identifying the resource) and what was proposed in the past was to use the tag named "name". But in this case it is a bit more complex since one should take into account the region as well.
I think the proposed code change should do the trick, can't test it though..

**Comment by thedrow** [comment]
It's a bit trickier than that.
First of all you can either specify a [vpc_id or a name](https://github.com/saltstack/salt/blob/develop/salt/modules/boto_vpc.py#L439). You can't specify both since it doesn't make sense.
The reason why the tags are constant is because names are not unique
e.g.
```yaml
a vpc of some sort exists:
  boto_vpc.present:
     - name: some_vpc
     - region: us-west-2
     - cidr_block: 10.64.32.0/21
     - instance_tenancy: default
     - dns_support: True
     - dns_hostnames: True
     - tags:
         owner: me
         region: us-west-2
         role: public
another vpc of some sort exists:
  boto_vpc.present:
     - name: some_vpc
     - region: us-west-2
     - cidr_block: 10.64.32.0/21
     - instance_tenancy: default
     - dns_support: True
     - dns_hostnames: True
     - tags:
         owner: me
         region: us-west-2
         role: private
```
Should work and create two VPCs. In order to change an existing VPC you need to specify it's ID.
It might be possible to tell Salt to save the VPC id somewhere and then you'll be able to tell which VPC is each.
Your proposal will make Salt treat VPC names as unique but what will happen if I create another VPC with the same name manually?
