### ISSUE TITLE
state.sls doesn't report failure on failure in mods

### ISSUE THREAD

**Issue by Ashald** [saltstack/salt#32924]
### Description of Issue/Question

When using `state.sls` within a formula via a `module.run` in order to execute other formulas (as part of orchestration) whenever there is a failure within any of modules `state.sls` the result is still true. 

```
Provision:
  module.run:
    - name: state.sls
    - mods:
      - app.{{ type }}.orch.{{ location }}.provision
    - concurrent: True
```

At first I though that `module.run` is to blame but it looks like `state.sls` is the culprit here.

As `state.sls` output [in case of failure] is a dict `module.run` looks for `retcode` within it in order to determine execution status (as per https://github.com/saltstack/salt/blob/2015.8/salt/states/module.py#L262).
OTOH, the `state.sls` output is formatted in a way that's so it's missing the retcode, e.g.:

```
{
    "test_|-An explicit failure message!_|-An explicit failure message!_|-fail_without_changes":{
        'comment':'Failure!',
        'name':"An explicit failure message!",
        'start_time':'20:35:36.668466',
        'result':False,
        'duration':1.093,
        '__run_num__':0,
        'changes':{

        }
    }
}
```

If it will be of any help, that's how the overall output looks like:

```
{
    'outputter':'highstate',
    'data':{
        'salt-master.acme.co_master':{
            'module_|-Provision_|-state.sls_|-run':{
                'comment':'Module function state.sls executed',
                'name':'state.sls',
                'start_time':'13:51:51.268625',
                'result':True,
                'duration':603.109,
                '__run_num__':0,
                'changes':{
                    'ret':{
                        "test_|-An explicit failure message!_|-An explicit failure message!_|-fail_without_changes":{
                            'comment':'Failure!',
                            'name':"An explicit failure message!",
                            'start_time':'13:51:51.868260',
                            'result':False,
                            'duration':1.065,
                            '__run_num__':0,
                            'changes':{

                            }
                        }
                    }
                }
            }
        }
    },
    'retcode':0
}
```
### Setup

Not relevant to the issue.
#### orch/provision.sls

```
Provision:
  module.run:
    - name: state.sls
    - mods:
      - app.provision
    - concurrent: True
```
#### app/provision.sls

```
An explicit failure message!:
  test.fail_without_changes
```
#### shell

```
salt-run state.orchestrate orch.provision
```

(Include debug logs if possible and relevant.)
### Versions Report

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Apr  5 2016, 13:41:50)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 1.5.2
       cherrypy: 5.1.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: 0.2.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by Ashald** [comment]
I had a brief conversation over this issue with @cro at SaltConf16 during SaltSprint where @cro confirmed it being a bug. Although IDK whether @cro remembers it. :)

**Comment by cheuschober** [comment]
That's quite different from when I last discussed the issue and was told it was by-design (eg, orch was able to run the states and didn't care if the states themselves were successful because _orch_ was successful). We wrote an orchestration results parser to find any failure with an orch state for our minor addition to `saltmod.py`

https://gist.github.com/cheuschober/81620e6f65e7df7f0442f5eb2194bf6e

**Comment by Ashald** [comment]
Heh, @cheuschober, that was one of my questions to you after your talk at SaltConf16. :) And this is the very reason for that question. :)

Thanks for the snippet. ;)

Yeah, I wouldn't blame @cro if it's not a bug as he confirmed at the time but rather 'by design' - a lot of things were going on and it was hard to concentrate on anything during the sprint.

OTOH, although I didn't try it, I believe that the same combination of `module.run` + `state.sls` _outside of orchestration runner_ (just within a regular formula executed on a minion) will lead to the same result, i.e. `module.run` reporting success even if any of formulas executed by `state.sls` failed.

Then the question is if it's really a 'by design' behavior since IMHO it looks a bit odd. And if the answer is still *yes* then, I think, we need to update `state.sls` doc to mention it.

**Comment by cheuschober** [comment]
100% agree with you there.

**Comment by UtahDave** [comment]
@Ashald why are you using `state.sls` within `module.run`?

It should work correctly if you just use the `state.sls`.

**Comment by evilNullPointer** [comment]
I had the same issue with the **dockerng** module and state.sls as well.

test/postgres/init.sls
```yaml
test-postgres-version:
  module.run:
    - name: dockerng.retcode
    - m_name: my-container-name
    - exec_driver: docker-exec
    - cmd: 'psql --versionfffffffffffffffffffff '
```

salt-call state.sls test.postgres
```yaml
    ID: test-postgres-version
    Function: module.run
    Name: dockerng.retcode
    Result: True
    Comment: Module function dockerng.retcode executed
    Started: 12:08:57.073653
    Duration: 689.65 ms
    Changes:
              ----------
              ret:
                  1
```

In our case, we are trying to write "functional" test as state. By example, we can add roles to a machine (game server and database). Both need to modify iptables. If we focus only on state idempotence we have no guarantee that the database has not override all the rules and prevented access to the game server at the same time.

**Comment by Ashald** [comment]
@UtahDave `state.sls` is an execution module rather than a state that's so it cannot be used directly [unless I'm missing something essential].

**Comment by UtahDave** [comment]
@Ashald, right, but you're wanting execute a state, right?  Search for `salt.state` here:  https://docs.saltstack.com/en/latest/topics/tutorials/states_pt5.html#orchestrate-runner

**Comment by UtahDave** [comment]
```
Provision:
  salt.state:
    - tgt: 'web*'
    - sls:
      - app.provision
    - concurrent: True
```
