### ISSUE TITLE
salt-cloud vmware: Creating a VM from template does not connect NIC

### ISSUE THREAD

**Issue by jopohl** [saltstack/salt#32946]
### Description of Issue/Question

This is possibly related to https://github.com/saltstack/salt/issues/23270. 

We have the same error, but with a SLES 12 template. Our setup works for a bunch of other VMs including
- Debian 7/8
- Ubuntu 12.04/14.04/16.04
- CentOS 5/6/7
- even SLES 11.4

However, the checkbox "Connect at power on" is not checked in the cloned machine, even if it is checked in the template.

We also already tried to replace vmxnet3 with e1000 network driver.
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-83-generic
         system: Ubuntu 14.04 trusty
```

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by jfindlay** [comment]
@jopohl, thanks for reporting.  Ping @nmadhok.

**Comment by nmadhok** [comment]
@jopohl Can you please post the debug log of the VM build and the map/profile you are using?

**Comment by jopohl** [comment]
@nmadhok here are some debug informations from the build:
```
[DEBUG   ] Rendered data from file: /tmp/salt-vmware-vxfqwqOC0hEtP77YfQvF.map:
saltminion-sles12:
    - sles12-vxfqwqOC0hEtP77YfQvF-vm:
        devices:
            network:
                Netzwerkadapter 1:
                    name: bor-salt
                    adapter_type: vmxnet3
                    switch_type: standard
                    ip: 10.111.80.65
                    gateway: [10.111.80.1]
                    subnet_mask: 255.255.255.0

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('saltminion-sles12', [OrderedDict([('sles12-vxfqwqOC0hEtP77YfQvF-vm', OrderedDict([('devices', OrderedDict([('network', OrderedDict([('Netzwerkadapter 1', OrderedDict([('name', 'bor-salt'), ('adapter_type', 'vmxnet3'), ('switch_type', 'standard'), ('ip', '10.111.80.65'), ('gateway', ['10.111.80.1']), ('subnet_mask', '255.255.255.0')]))]))]))]))])])])
[PROFILE ] Time (in seconds) to render '/tmp/salt-vmware-vxfqwqOC0hEtP77YfQvF.map' using 'yaml' renderer: 0.00311088562012
[INFO    ] Applying map from '/tmp/salt-vmware-vxfqwqOC0hEtP77YfQvF.map'.
```

Furthermore, here's the used map file:
```
saltminion-sles12:
    - sles12-vxfqwqOC0hEtP77YfQvF-vm:
        devices:
            network:
                Netzwerkadapter 1:
                    name: bor-salt
                    adapter_type: vmxnet3
                    switch_type: standard
                    ip: 10.111.80.65
                    gateway: [10.111.80.1]
                    subnet_mask: 255.255.255.0
```

and profile:
```
saltminion-sles12:
  provider: bor-vc1
  clonefrom: saltminion-sles12

  ## Optional arguments
  num_cpus: 2
  memory: 2GB
  devices:
    disk:
      Festplatte 1:
        size: 20

  domain: boreus.de
  dns_servers:
    - 10.111.99.7
    - 10.111.99.8
  dns_search:
    - boreus.de

  cluster: VM-A_Boreus_SaltStack
  datastore: datastore_vm58
  datacenter: Boreus Rechenzentrum GmbH
  host: bor-vm58.boreus.de
  template: False
  power_on: True

  deploy: False
```

* After the VM is build, we need to connect the NIC manually to set up an IP.
* If we do this manual connect fast enough, salt-cloud also can configure the IP.
* After manually connecting the NIC, the IP shows up in Web Client.
