### ISSUE TITLE
Support for Asynchronous Orchestration Event with a "Wait" Requisite 

### ISSUE THREAD

**Issue by grichmond-salt** [saltstack/salt#32956]
### Description of Issue/Question

While asking a question about parallel tasks during an orchestration state, the following ideas were discussed between Tom, Seth, and Mike:

An `async` execute plus a `wait_for_event` would be a simple and killer Orchestrate addition.  It could be implemented as a `requisite` or a `state`.  

The wait requisite would be evaluated when the state gets evaluated, but a wait state would be evaluated when it gets evaluated, which COULD be before it should be evaluated so it could make an earlier lock.  However, having a wait state allows us to be a lot more flexible in what we wait for and how we wait.  It also allows us to define a single wait that many other states can require.

A requisite addition would also be awesome. The ability to extract data from the event and then do something with it (e.g., check success/fail/changes) would be very helpful.

Perhaps we should mandate that it would always be the last evaluated requisite.  This makes sense, because you might not be able to wait for something that you also require.  This is because you would need to require the thing that would eventually trigger the wait state.

It could be hard to chain the waits in a deterministic way without a deep understanding of requisite chain ordering, which is something we cannot expect people to understand.  This, perhaps, is an argument in support of a wait requisite, but requisites are just not made to inherently have arguments and the conditions of the wait are critical to the orchestration.

We could also add a feature to do requisite ordering.  With this in place, one could explicitly say: "evaluate this requisite last".  Since the order of requisite eval is right now hard coded into the state system it is like state ordering used to be; deterministic but non-intuitive.

**Comment by mbakke** [comment]
I have a state that should be applied *only* when `required` by another state (which has appropriate `unless` or `onchanges` requisites).

The use case for me is temporarily overriding another state. In particular, temporarily change permissions on a managed folder for a `cmd.run` that runs as a restricted user.

It looks something like this:
```
dir1:
  file.directory:
    - name: /some/path
    - mode: 555
dir1_override:
  file.directory:
    - name: /some/path
    - mode: 755
    - require:
      - dir1
    - use:
      - dir1
    - wait: # only run when called from one of these requisites
      - cmd: some-cmd
some-cmd:
  cmd.run:
    - runas: nonroot
    - onchanges:
      - file: /some/other/managed/file
    - require:
      - file: dir1_override
```

Not sure if this is helpful, but it's a real use case that doesn't seem to have any good solutions currently. In this case it could implicitly establish a `require_in` dependency and vice versa for the `wait_in` counterpart to aid with ordering.
