### ISSUE TITLE
Problem with winrepo and pkg.installed

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#32962]
### Description of Issue/Question

With winrepo and using the "latest" package version it's hard to come up with a pkg.installed formula that works and I don't know how to come up with one that will allow me to turn off autoupdates

### Setup

First of all I'm using salt 2015.5.9 (both for the master and the minion). Apologies if this is fixed in a later version

Here is chrome.sls (simplified for testing purposes)

```
chrome:
  latest:
    full_name: 'Google Chrome'
    installer: 'https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi'
    install_flags: '/qn /norestart'
    uninstaller: 'https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
```

Here is a state formula for installing chrome.

```
chrome installed:
   pkg.installed:
     - name: chrome
```

If I apply the above formula, I get the following output

```
pkg_|-chrome installed_|-chrome_|-installed:
        ----------
        __run_num__:
            3
        changes:
            ----------
            chrome:
                ----------
                new:
                    66.153.16478
                old:
        comment:
            The following packages failed to install/update: chrome=latest
        duration:
            27298.0
        name:
            chrome
        result:
            False
        start_time:
            01:27:35.964000
```

So it appears to try to install "latest" but then it seems to complain possibly because the version that gets installed does not literally match "latest". For what it's worth the install does in reality succeed.

So far the only formula that works 100% for me is:

```
chrome installed:
   pkg.installed:
     - name: chrome
     - pkgs:
          - chrome
```

I think that this formula may work because it doesn't try any version match test when you do it this way. However with this formula I'm still unable to specifiy a specific version, so I have to use it in conjunction with Chrome auto-updates (not that auto-updates are a bad thing but
I'd like to have the choice). 

Is there a way around this? One way to handle this might be something like:

If the version number you ask for doesn't match anything in the winrepo sls file, then think of "latest" as a wildcard matching all the unmatching version numbers and then run the installer and check that the resulting version matches the asked for version.

I also tried using pkg.latest and couldn't get it to work (I had similar issues).

Thanks
