### ISSUE TITLE
pkgrepo.managed doesn't work if junk data is sent to the minions sources.list first.

### ISSUE THREAD

**Issue by Slimmons** [saltstack/salt#32960]
### Description of Issue/Question
Sorry in advance, this was my first time using pkgrepo.managed, and I'm fairly new to salt, so my terminology might not be great.

pkgrepo.managed will take in garbage data from an incorrect pkgrepo.managed.name, and when the name is corrected, the state still won't work because the new name is just appended to the end of the file.  Only removing the file will allow the state to run correctly.

### Setup
Ubuntu 14.04

salt-master 2015.8.8.2
salt-minion 2015.8.8.2

Single Master, Single Minion, was just trying to test some basic stuff.

**_Config on first try:_**
**init.sls**
```
mongodb-repo:
  pkgrepo.managed:
    - humanname: mongodb
    - name: deb http://repo.mongodb.org/apt/ubuntu INTENTIONAL BREAKAGE trusty/mongodb-org/3.0 multiverse
     - dist: trusty/mongodb-org/3.0
    - file: /etc/apt/sources.list.d/mongodb-org-3.0.list
    - keyid: 7F0CEB10
    - keyserver: hkp://keyserver.ubuntu.com:80
    - require_in:
      - pkg: mongodb-org

mongodb-org:
  pkg.installed
```

**__Output of state.highstate__**
```
MyMinion1:
----------
          ID: mongodb-repo
    Function: pkgrepo.managed
        Name: deb http://repo.mongodb.org/apt/ubuntu INTENTIONAL BREAKAGE trusty/mongodb-org/3.0 multiverse
      Result: False
     Comment: Failed to configure repo 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse': W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/trusty/multiverse/binary-amd64/Packages  404  Not Found

              W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/trusty/multiverse/binary-i386/Packages  404  Not Found

              E: Some index files failed to download. They have been ignored, or old ones used instead.
     Started: 20:20:59.159701
    Duration: 7292.219 ms
     Changes:
----------
          ID: mongodb-org
    Function: pkg.installed
      Result: False
     Comment: One or more requisite failed: dependencies.mongodb-repo
     Started:
    Duration:
     Changes:
```

On the minion, in ```/etc/apt/sources.list.d/mongodb-org-3.0.list``` the broken deb is inserted
**/etc/apt/sources.list.d/mongodb-org-3.0.list**
```deb http://repo.mongodb.org/apt/ubuntu INTENTIONAL BREAKAGE trusty/mongodb-org/3.0 multiverse```

Obviously, this won't work, so if I find the error, and fix it, and run the same thing with the ```pkgrepo.managed.name``` corrected, then it just appends to the end of the file, and still doesn't work.  Example of new file below

**/etc/apt/sources.list.d/mongodb-org-3.0.list**
```deb http://repo.mongodb.org/apt/ubuntu INTENTIONAL BREAKAGE trusty/mongodb-org/3.0 multiverse
deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse```

The only way to fix it (that I know of) is to delete that file on the minion, and run the highstate again.


### Steps to Reproduce Issue
**1.** Create a simple pkgrepo.managed, such as the one shown above.
**2.** Mistype the pkgrepo.managed.name
**3.** Run the state
**4.** Fix the pkgrepo.managed.name
**5.** Try to figure out why it never works, then go to the saltstack IRC for help

### Versions Report

**Master versions report**
```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-25-generic
         system: Ubuntu 14.04 trusty
```

**Minion versions report**
```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-25-generic
         system: Ubuntu 14.04 trusty
```

Mad thanks to kevinquinnyo in the IRC for figuring out what the problem was, and helping me get it resolved.
