### ISSUE TITLE
A failing state with a prerequisite invalidates require

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#32974]
### Setup

``` sls
# test.sls
first:
  test.succeed_with_changes: []

second:
  test.succeed_with_changes:
    - prereq_in:
      - test: first

third:
  test.fail_without_changes:
    - require:
      - test: second
    - prereq_in:
      - test: first
```
### Steps to Reproduce Issue

Run the sls above, see the following result:

```
# salt-call state.sls test
[INFO    ] Determining pillar cache
[INFO    ] Determining pillar cache
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://test-reqs.sls'
[INFO    ] Running state [second] at time 19:30:00.056617
[INFO    ] Running state [third] at time 19:30:00.057494
local:
----------
          ID: first
    Function: test.succeed_with_changes
      Result: False
     Comment: One or more requisite failed: test-reqs.third
     Started: 
    Duration: 
     Changes:   
----------
          ID: second
    Function: test.succeed_with_changes
      Result: None
     Comment: If we weren't testing, this would be successful with changes
     Started: 
    Duration: 
     Changes:   
              ----------
              testing:
                  ----------
                  new:
                      Something pretended to change
                  old:
                      Unchanged
----------
          ID: third
    Function: test.fail_without_changes
      Result: False
     Comment: If we weren't testing, this would be a failure!
     Started: 
    Duration: 
     Changes:   

Summary for local
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    2
------------
Total states run:     3
```

`second` state and it's prereq `first` should succeed. Instead the failure of `third` is causing the prereq to fail and `first` not to run. But `third` shouldn't even try to run until after `second` has succeeded due to the requirement.
### Versions Report

```
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Apr 28 2016, 01:21:00)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:   
        machine: amd64
        release: 10.3-RELEASE
```
