### ISSUE TITLE
virtualenv.managed cwd is ignored

### ISSUE THREAD

**Issue by poelzi** [saltstack/salt#33000]
### Description of Issue/Question

virtualenv.managed does not change directory as specified by cwd
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
/srv/test/virtualenv:
  file.directory:
    - user: vagrant
    - group: vagrant
    - mode: 755
    - makedirs: True
  virtualenv.managed:
    - system_site_packages: False
    - pip_upgrade: True
    - python: python3.5
    - user: vagrant
    - cwd: /vagrant
    - requirements: /vagrant/requirements-dev.txt

```

The requirements file contains following:
`-r requirements.txt`

Which works normally, but salt reports:

```
----------
          ID: /srv/sciencegraph/virtualenv
    Function: virtualenv.managed
      Result: False
     Comment: virtualenv exists
              Could not open requirements file: [Errno 2] No such file or directory: '/tmp/requirements.txt'
              Storing debug log for failure in /home/vagrant/.pip/pip.log
     Started: 03:11:55.808161
    Duration: 828.437 ms
     Changes:   
```

Which is definitely the wrong cwd.
### Steps to Reproduce Issue

Use virtualenv.managed cwd argument
### Versions Report

Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-45-generic
         system: Ubuntu 14.04 trusty
