### ISSUE TITLE
Unable to use extension_modules/custom pillars with gitfs filesystem backend

### ISSUE THREAD

**Issue by davido-bs** [saltstack/salt#33027]
### Description of Issue/Question
It seems that I'm unable to use the ``extension_modules`` setting to specify the path to a custom external pillar under a GitFS setup.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
In our saltmaster:
```
fileserver_backend:
  - git

extension_modules: salt://_modules

top_file_merging_strategy: same
gitfs_base: <branch_name>
gitfs_remotes:
  - ssh://github.com/<path>:
    - root: salt/salt
  - ssh://github.com/<path>:
    - name: scripts_gitfs
    - root: scripts

ext_pillar:
  - git:
    - master ssh://github.com/<path>:
      - root: salt/pillar
      - env: base
  - <custom_pillar>: 'test'
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
We have tried variations of the ``extension_modules`` setting, including ``salt://_modules``, ``/srv/salt/_modules``, and even omitting it entirely. Because of our GitFS setup, there is nothing in ``/srv``.

In our repo's ``salt/salt`` folder, we've tried placing that custom pillar in ``salt/salt/_modules/pillar/custom_pillar.py``, as well as ``salt/salt/_pillar/custom_pillar.py``, also with no success. We have repeatedly tried clearing the cache (``salt-run fileserver clear-cache``), restarting the master, calling ``refresh_pillar``.

The end result is the same - when calling ``pillar.items``, none of those are registering any activity with our custom external pillar. The only logging we ever see is:
```
2016-05-03 19:23:49,910 [salt.pillar      ][CRITICAL][10014] Specified ext_pillar interface <our_custom_pillar> is unavailable
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3 
```
Minion and master are both 8.8.2.
