### ISSUE TITLE
Getting error:  [Object Not Found]: Could not find a VM named 'windows7Server64Guest' Error: There was a profile error: Failed to deploy VM, using salt-cloud command....

### ISSUE THREAD

**Issue by akshya-github** [saltstack/salt#33136]
### Description of Issue/Question

using this command to create VM:

```
salt-cloud -p vmware-Win2K8 vmware-Win2K8
```

 here:  vmware-Win2K8 is profile name.
### Setup

Want to create VM on: VMWARE vSphere ESXi 5.5.

In Provider configuration:

```
Driver: vsphere 
```

Profile configuration:-

```
vmware-Win2K8:
 provider: my-vsphere-config
 num_cpus: 2
 memory: 4GB
  devices:
  cd:
   CD/DVD drive 1:
   device_type: datastore_iso_file
   iso_path: "[DataStore] /ISO/Windows_server_2008_r2.iso"
  disk:
   Hard disk 1:
    size: 30
  network:
   Network adapter 1:
    name: eth007
    switch_type: standard
    ip: 192.168.110.201
    gateway: [192.168.110.211]
    subnet_mask: 255.255.255.0
 dns_servers:
  -8.8.8.8
 resourcepool: MyResources
 datastore: Datastore
 host: 192.168.109.213
 template: False
 power_on: True

 deploy: True
 #private_key: /root/.ssh/mykey.pem
 #ssh_username: cloud-user
 #password: 'Admin@123'
 minion:
  master: 192.168.104.111
 #file_map:
  #/path/to/local/custom/script: /path/to/remote/script
  #/path/to/local/file: /path/to/remote/file
  #/srv/salt/yum/epel.repo: /etc/yum.repos.d/epel.repo
 hardware_version: 8
 image: windows7Server64Guest
 win_username: Admin
 win_password: 'Admin@123'
 win_installer: "[Data store] /ISO/Salt-Minion-2015.8.8-2-AMD64-Setup.exe"
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

```
Salt Version:
            Salt: 2015.8.8.2

Dependency Versions:
 Apache Libcloud: 0.20.0
          Jinja2: 2.7.2
        M2Crypto: Not Installed
            Mako: Not Installed
          PyYAML: 3.11
           PyZMQ: 14.7.0
          Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5
            cffi: 1.6.0
        cherrypy: 3.2.2
        dateutil: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
         libgit2: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: 2.14
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: Not Installed
         timelib: 0.2.4
```

**Comment by jfindlay** [comment]
@akshya-github, thanks for reporting.  Is it possible for you to post the output of `salt-cloud -l debug -p vmware-Win2K8 vmware-Win2K8`?

**Comment by akshya-github** [comment]
@jfindlay, Sure...Please find the [attachment.]
[err.txt](https://github.com/saltstack/salt/files/260718/err.txt)

**Comment by jfindlay** [comment]
@akshya-github, thanks for the extra information.  Ping @nmadhok.

**Comment by nmadhok** [comment]
@akshya-github Change your driver to ``vmware`` instead of ``vsphere`` in your provider configuration. The ``vsphere`` driver is no longer supported and will be removed in Salt Carbon release. Looking at your logs:

```
[WARNING ] /usr/lib/python2.7/site-packages/salt/cloud/clouds/vsphere.py:143: DeprecationWarning: The vsphere driver is deprecated in favor of the vmware driver and will be removed in Salt Carbon. Please convert your vsphere provider configs to use the vmware driver.
```

The traceback confirms that it's trying to use the ``vsphere`` driver instead of the ``vmware`` driver:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vsphere.py", line 311, in create
    template = conn.get_vm_by_name(vm_['image'])
  File "/usr/lib/python2.7/site-packages/pysphere/vi_server.py", line 323, in get_vm_by_name
    FaultTypes.OBJECT_NOT_FOUND)
```

Here's documentation on how to use the ``vmware`` cloud driver:
https://docs.saltstack.com/en/latest/topics/cloud/vmware.html
https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vmware.html

**Comment by akshya-github** [comment]
@nmadhok, I have changed driver to 'vmware', Now I am not able to connect vSphere server.

Provider file looks like:

 my-vsphere-config:
 driver: vmware
 user: 'root'
 password: 'Admin@123'
 url: 'https://192.168.8.28:443/sdk'
 esxi_host_user: 'root'
 esxi_host_password: 'Admin@123'
 esxi_host_ssl_thumbprint: '1E:3D:48:38:C1:FC:1D:9D:2C:B8:A7:08:A7:84:12:F8:59:B4:29:32'

Provider is: VMware vSphere 5 Hypervisor

I have tried with different urls like:

url: 'https://192.168.8.28:443/'
      https://192.168.8.28:9443/admin-app
      https://192.168.8.28:9443/vsphere-client

**Comment by nmadhok** [comment]
@akshya-github The document I listed before clearly lists an example for how providers config file should look like:

```
vcenter01:
  driver: vmware
  user: 'DOMAIN\user'
  password: 'verybadpass'
  url: 'vcenter01.domain.com'
  protocol: 'https'
  port: 443
```

In your case it should be the following:
```
vcenter01:
  driver: vmware
  user: 'root'
  password: 'Admin@123'
  url: '192.168.8.28'
```
