### ISSUE TITLE
How to locate ldap auth problem

### ISSUE THREAD

**Issue by leo108** [saltstack/salt#33165]
### Description of Issue/Question

I'm using ldap as external auth system, but I get error when executing `salt -a ldap 'hostname' test.ping`

> Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

I want to know where the problem is (acl config error? ldap binddn/bindpw error? or just I type the wrong password of ldap user)

I use `-l trace` to see detail log, seems noting valuable

> [DEBUG   ] Reading configuration from /etc/salt/master
> [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: hostname
> [DEBUG   ] Missing configuration file: /root/.saltrc
> [TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
> [DEBUG   ] Configuration file path: /etc/salt/master
> [DEBUG   ] Reading configuration from /etc/salt/master
> [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: hostname
> [DEBUG   ] Missing configuration file: /root/.saltrc
> [DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
> [DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
> [DEBUG   ] Sending event - data = {'_stamp': '2016-05-11T03:14:42.500301'}
> [TRACE   ] get_event() received = {'tag': 'salt/event/new_client', 'data': {'_stamp': '2016-05-11T03:14:42.500301'}}
> [DEBUG   ] LazyLoaded ldap.auth
> username: leo
> password:
> [DEBUG   ] LazyLoaded nested.output
> [TRACE   ] data = Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
> Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
### Setup

```
external_auth:
  ldap:
    leo:
      - test.ping

auth.ldap.server: 'ldapserver'
auth.ldap.port: 389
auth.ldap.scope: 2
auth.ldap.uri: 'ldap://ldapserver:389'
auth.ldap.tls: False
auth.ldap.no_verify: False
auth.ldap.anonymous: False
auth.ldap.groupou: ''
auth.ldap.groupclass: 'person'
auth.ldap.accountattributename: 'uid'
auth.ldap.basedn: 'ou=People,dc=xxxx,dc=com'
auth.ldap.binddn: 'uid=auth,ou=System,dc=xxxx,dc=com'
auth.ldap.bindpw: 'xxxxx'
```
### Steps to Reproduce Issue

1.set the config of /etc/salt/master
2.`service salt-master restart`
3.`salt -a ldap 'hostname' test.ping` and input username/pwd
### Versions Report

> ```
>       Salt: 2015.5.8
>     Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
>     Jinja2: 2.2.1
>   M2Crypto: 0.20.2
> ```
> 
> msgpack-python: 0.4.6
>   msgpack-pure: 0.1.3
>       pycrypto: 2.0.1
>        libnacl: Not Installed
>         PyYAML: 3.10
>          ioflo: 1.5.4
>          PyZMQ: 14.3.1
>           RAET: Not Installed
>            ZMQ: 3.2.5
>           Mako: 1.0.4
>        Tornado: Not Installed
>        timelib: Not Installed
>       dateutil: Not Installed
