### ISSUE TITLE
state.sls_id doesn't manage onchanges or onchanges_in requisite

### ISSUE THREAD

**Issue by adnanJP** [saltstack/salt#33199]
### Setup

git_repo.sls

```
anyrepo:
  git.latest:
    ...
    - require: 
      - pkg: git
    - onchanges_in:
      - file : /path/cache

/path/cache:
  file.directory:
     ... 
     - clean: True
```

(the same is the onchanges is in the /path/cache)
### Steps to Reproduce Issue

When calling state.sls git_repo 
- No issues, /path/cache gets cleared each time there is a new revision (so on git.latest changes)

When calling state.sls_id anyrepo git_repo
- Only the requires are managed, the state doesn't even evaluate /path/cache

In the documentation, it says that state.sls_id manage all requirements, so i am a bit confused here.

```
### Versions Report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: 1.5.2
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-25-generic
         system: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@adnanJP I am able to replicate this behavior only when applying `_in` requisites. Using onchnages works without the in.

1. Example where using onchanges works:

```
➜  salt git:(tagv2015.8.8.2) cat /srv/salt/issues/33199.sls                          
run-cmd:
  cmd.run:
    - name: echo "test"

anyrepo:
  cmd.run:
    - name: touch /tmp/anyrepo
    - require:
      - cmd: run-cmd
    - onchanges:
      - file : /path/cache

/path/cache:
  file.directory:
     - name: /tmp/test
     - clean: True
```

```
➜  salt git:(tagv2015.8.8.2) sudo salt 'ch3ll-mas*' state.sls_id anyrepo issues.33199
ch3ll-master:
----------
          ID: run-cmd
    Function: cmd.run
        Name: echo "test"
      Result: True
     Comment: Command "echo "test"" run
     Started: 15:09:05.165797
    Duration: 14.996 ms
     Changes:   
              ----------
              pid:
                  24967
              retcode:
                  0
              stderr:
              stdout:
                  test
----------
          ID: /path/cache
    Function: file.directory
        Name: /tmp/test
      Result: True
     Comment: Directory /tmp/test updated
     Started: 15:09:05.185563
    Duration: 10.078 ms
     Changes:   
              ----------
              /tmp/test:
                  New Dir
----------
          ID: anyrepo
    Function: cmd.run
        Name: touch /tmp/anyrepo
      Result: True
     Comment: Command "touch /tmp/anyrepo" run
     Started: 15:09:05.196015
    Duration: 11.965 ms
     Changes:   
              ----------
              pid:
                  24968
              retcode:
                  0
              stderr:
              stdout:

Summary for ch3ll-master
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
```

2. Example where onchanges_in does not work:

```
➜  salt git:(tagv2015.8.8.2) cat /srv/salt/issues/33199.sls                                                                                                                                      
run-cmd:
  cmd.run:
    - name: echo "test"

anyrepo:
  cmd.run:
    - name: touch /tmp/anyrepo
    - require:
      - cmd: run-cmd
    - onchanges_in:
      - file : /path/cache

/path/cache:
  file.directory:
     - name: /tmp/test
     - clean: True
```

```
➜  salt git:(tagv2015.8.8.2) sudo salt 'ch3ll-mas*' state.sls_id anyrepo issues.33199
ch3ll-master:
----------
          ID: run-cmd
    Function: cmd.run
        Name: echo "test"
      Result: True
     Comment: Command "echo "test"" run
     Started: 15:10:11.536622
    Duration: 12.56 ms
     Changes:   
              ----------
              pid:
                  25391
              retcode:
                  0
              stderr:
              stdout:
                  test
----------
          ID: anyrepo
    Function: cmd.run
        Name: touch /tmp/anyrepo
      Result: True
     Comment: Command "touch /tmp/anyrepo" run
     Started: 15:10:11.549579
    Duration: 9.906 ms
     Changes:   
              ----------
              pid:
                  25392
              retcode:
                  0
              stderr:
              stdout:

Summary for ch3ll-master
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
```

Also to note I also tried a `require_in` and it seems any `_in` requisites is what is causing the issue. I will label this a bug for the `_in` not being added to the state run, but can you try my simple example above for using only onchanges and see if it works for you?
