### ISSUE TITLE
win_servermanager reporting incorrect/truncated results on minion 2015.8.8-2

### ISSUE THREAD

**Issue by m03** [saltstack/salt#33225]
### Description of Issue/Question

win_servermanager is reporting changes regarding features installed via state module in instances where those features had already previously been installed (and shouldn't be reporting changes), and is displaying truncated feature names from win_servermanager.list_installed. The two issues appear to be related, as the former only appears to occur for features with truncated names. This is occurring on Windows minion version 2015.8.8-2.
### Setup

Test state:

```
root@saltmaster:~# cat /srv/salt/state/windows/test1.sls

install-Web-Request-Monitor:
  win_servermanager.installed:
    - name: Web-Request-Monitor

install-Web-Http-Logging:
  win_servermanager.installed:
    - name: Web-Http-Logging
```

Showing that the feature is already installed:

```
root@saltmaster:~# salt 'win2012r2-1' win_servermanager.install 'Web-Request-Monitor'
win2012r2-1:
    ----------
    ExitCode:
        NoChangeNeeded
    FeatureResult:
        {}
    RestartNeeded:
        No
    Success:
        True
    message:


        Success       : True
        RestartNeeded : No
        FeatureResult : {}
        ExitCode      : NoChangeNeeded
root@saltmaster:~# salt 'win2012r2-1' win_servermanager.install 'Web-Http-Logging'
win2012r2-1:
    ----------
    ExitCode:
        NoChangeNeeded
    FeatureResult:
        {}
    RestartNeeded:
        No
    Success:
        True
    message:


        Success       : True
        RestartNeeded : No
        FeatureResult : {}
        ExitCode      : NoChangeNeeded
```

...and...

```
root@saltmaster:~# salt 'win2012r2-1' cmd.run 'Get-WindowsFeature Web-Request-Monitor, Web-Http-Logging' shell='powershell'
win2012r2-1:

    Display Name                                            Name
    ------------                                            ----
                [X] HTTP Logging                            Web-Http-Logging
                [X] Request Monitor                         Web-Request-Monitor
```
### Steps to Reproduce Issue

Running the test state multiple times:

```
root@saltmaster:~# salt 'win2012r2-1' state.sls windows.test1
win2012r2-1:
  Name: Web-Request-Monitor - Function: win_servermanager.installed - Result: Changed

Summary for win2012r2-1
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
root@saltmaster:~# salt 'win2012r2-1' state.sls windows.test1
win2012r2-1:
  Name: Web-Request-Monitor - Function: win_servermanager.installed - Result: Changed

Summary for win2012r2-1
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
root@saltmaster:~# salt 'win2012r2-1' system.reboot
win2012r2-1:
    True
root@saltmaster:~# salt 'win2012r2-1' state.sls windows.test1
win2012r2-1:
  Name: Web-Request-Monitor - Function: win_servermanager.installed - Result: Changed

Summary for win2012r2-1
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
```

Showing truncated feature names:

```
root@saltmaster:~# salt 'win2012r2-1' win_servermanager.list_installed
win2012r2-1:
    ----------
    AD-Domain-Ser...:
        Active Directory Domain Services
    ADCS-Cert-Aut...:
        Certification Authority
    ADCS-Device-E...:
        Network Device Enrollment Service
    ADCS-Enroll-W...:
        Certificate Enrollment Web Service
    ADCS-Web-Enro...:
        Certification Authority Web Enrollment
    AS-Dist-Trans...:
        Distributed Transactions
    AS-HTTP-Activ...:
        HTTP Activation
    AS-Incoming-T...:
        Incoming Network Transactions
    AS-MSMQ-Activ...:
        Message Queuing Activation
    AS-Outgoing-T...:
        Outgoing Network Transactions
    AS-TCP-Activa...:
        TCP Activation
    AS-TCP-Port-S...:
        TCP Port Sharing
    Application-S...:
        Application Server
    BITS-Compact-...:
        Compact Server
    Biometric-Fra...:
        Windows Biometric Framework
    BitLocker-Net...:
        BitLocker Network Unlock
    Data-Center-B...:
        Data Center Bridging
    Desktop-Exper...:
        Desktop Experience
    FS-DFS-Replic...:
        DFS Replication
    FS-Data-Dedup...:
        Data Deduplication
    FS-Resource-M...:
        File Server Resource Manager
    FS-SMB1:
        SMB 1.0/CIFS File Sharing Support
    FS-SyncShareS...:
        Work Folders
    FS-iSCSITarge...:
        iSCSI Target Server
    Failover-Clus...:
        Failover Clustering
    FileAndStorag...:
        File and Storage Services
    Hyper-V-Power...:
        Hyper-V Module for Windows PowerShell
    IPAM-Client-F...:
        IP Address Management (IPAM) Client
    InkAndHandwri...:
        Ink and Handwriting Services
    Internet-Prin...:
        Internet Printing Client
    MSMQ-HTTP-Sup...:
        HTTP Support
    MSMQ-Multicas...:
        Multicasting Support
    NET-Framework...:
        ASP.NET 4.5
    NET-HTTP-Acti...:
        HTTP Activation
    NET-Non-HTTP-...:
        Non-HTTP Activation
    NET-WCF-HTTP-...:
        HTTP Activation
    NET-WCF-MSMQ-...:
        Message Queuing (MSMQ) Activation
    NET-WCF-Pipe-...:
        Named Pipe Activation
    NET-WCF-Servi...:
        WCF Services
    NET-WCF-TCP-A...:
        TCP Activation
    NET-WCF-TCP-P...:
        TCP Port Sharing
    NPAS-Policy-S...:
        Network Policy Server
    PowerShell:
        Windows PowerShell 4.0
    PowerShell-ISE:
        Windows PowerShell ISE
    PowerShell-V2:
        Windows PowerShell 2.0 Engine
    PowerShellRoot:
        Windows PowerShell
    Print-LPD-Ser...:
        LPD Service
    Print-Scan-Se...:
        Distributed Scan Server
    RDS-Connectio...:
        Remote Desktop Connection Broker
    RDS-Virtualiz...:
        Remote Desktop Virtualization Host
    RPC-over-HTTP...:
        RPC over HTTP Proxy
    RSAT-AD-Admin...:
        Active Directory Administrative Center
    RSAT-AD-Power...:
        Active Directory module for Windows PowerShell
    RSAT-Clusteri...:
        Failover Cluster Command Interface
    RSAT-CoreFile...:
        Share and Storage Management Tool
    RSAT-DFS-Mgmt...:
        DFS Management Tools
    RSAT-Feature-...:
        BitLocker Recovery Password Viewer
    RSAT-File-Ser...:
        File Services Tools
    RSAT-Hyper-V-...:
        Hyper-V Management Tools
    RSAT-Online-R...:
        Online Responder Tools
    RSAT-Print-Se...:
        Print and Document Services Tools
    RSAT-RDS-Lice...:
        Remote Desktop Licensing Diagnoser Tools
    RSAT-RemoteAc...:
        Remote Access module for Windows PowerShell
    Remote-Assist...:
        Remote Assistance
    Remote-Deskto...:
        Remote Desktop Services
    SNMP-WMI-Prov...:
        SNMP WMI Provider
    Server-Gui-Mg...:
        Graphical Management Tools and Infrastructure
    Server-Gui-Shell:
        Server Graphical Shell
    Server-Media-...:
        Media Foundation
    ServerEssenti...:
        Windows Server Essentials Experience
    Storage-Services:
        Storage Services
    Telnet-Client:
        Telnet Client
    UpdateService...:
        User Interface Management Console
    User-Interfac...:
        User Interfaces and Infrastructure
    WAS:
        Windows Process Activation Service
    WAS-Config-APIs:
        Configuration APIs
    WAS-NET-Envir...:
        .NET Environment 3.5
    WAS-Process-M...:
        Process Model
    Web-App-Dev:
        Application Development
    Web-Applicati...:
        Web Application Proxy
    Web-Asp-Net45:
        ASP.NET 4.5
    Web-Common-Http:
        Common HTTP Features
    Web-Custom-Lo...:
        Custom Logging
    Web-DAV-Publi...:
        WebDAV Publishing
    Web-Default-Doc:
        Default Document
    Web-Dir-Browsing:
        Directory Browsing
    Web-Dyn-Compr...:
        Dynamic Content Compression
    Web-Filtering:
        Request Filtering
    Web-Health:
        Health and Diagnostics
    Web-Http-Errors:
        HTTP Errors
    Web-Http-Logging:
        HTTP Logging
    Web-Http-Redi...:
        HTTP Redirection
    Web-Http-Tracing:
        Tracing
    Web-IP-Security:
        IP and Domain Restrictions
    Web-ISAPI-Ext:
        ISAPI Extensions
    Web-ISAPI-Filter:
        ISAPI Filters
    Web-Lgcy-Mgmt...:
        IIS 6 Management Console
    Web-Lgcy-Scri...:
        IIS 6 Scripting Tools
    Web-Log-Libra...:
        Logging Tools
    Web-Mgmt-Console:
        IIS Management Console
    Web-Mgmt-Tools:
        Management Tools
    Web-Net-Ext45:
        .NET Extensibility 4.5
    Web-Performance:
        Performance
    Web-Request-M...:
        Request Monitor
    Web-Scripting...:
        IIS Management Scripts and Tools
    Web-Security:
        Security
    Web-Server:
        Web Server (IIS)
    Web-Stat-Comp...:
        Static Content Compression
    Web-Static-Co...:
        Static Content
    Web-WebServer:
        Web Server
    Windows-Ident...:
        Windows Identity Foundation 3.5
    Windows-Inter...:
        Windows Internal Database
    Windows-Serve...:
        Windows Server Backup
    Windows-TIFF-...:
        Windows TIFF IFilter
    WindowsPowerS...:
        Windows PowerShell Web Access
    WindowsStorag...:
        Windows Standards-Based Storage Management
    Wireless-Netw...:
        Wireless LAN Service
    WoW64-Support:
        WoW64 Support
    iSCSITarget-V...:
        iSCSI Target Storage Provider (VDS and VSS hardware providers)
```
### Versions Report

Minion version report:

```
root@saltmaster:~# salt 'win2012r2-1' test.versions_report
win2012r2-1:
    Salt Version:
               Salt: 2015.8.8

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist:
            machine: AMD64
            release: 2012ServerR2
             system: 2012ServerR2 6.3.9600  Multiprocessor Free

root@saltmaster:~# salt 'win2012r2-1' pkg.version 'Salt Minion 2015.8.8-2'
win2012r2-1:
    2015.8.8-2
```

**Comment by Ch3LL** [comment]
@m03 I am not able to replicate this:

```
➜  salt git:(tagv2015.8.8.2) sudo salt 'win2012' state.sls issues.33225
win2012:
----------
          ID: install-Web-Request-Monitor
    Function: win_servermanager.installed
        Name: Web-Request-Monitor
      Result: True
     Comment: The feature Web-Request-Monitor is already installed
     Started: 15:26:08.697000
    Duration: 1687.0 ms
     Changes:   
----------
          ID: install-Web-Http-Logging
    Function: win_servermanager.installed
        Name: Web-Http-Logging
      Result: True
     Comment: The feature Web-Http-Logging is already installed
     Started: 15:26:10.384000
    Duration: 2545.0 ms
     Changes:   

Summary for win2012
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
```

Correct me if i'm wrong but i dont see any truncated names in the list either:

```
➜  salt git:(tagv2015.8.8.2) sudo salt 'win2012' win_servermanager.list_installed
win2012:
    ----------
    FileAndStorage-Services:
        File And Storage Services
    NET-Framework-45-Core:
        .NET Framework 4.5
    NET-Framework-45-Features:
        .NET Framework 4.5 Features
    NET-WCF-Services45:
        WCF Services
    NET-WCF-TCP-PortSharing45:
        TCP Port Sharing
    PowerShell:
        Windows PowerShell 3.0
    PowerShell-ISE:
        Windows PowerShell ISE
    PowerShellRoot:
        Windows PowerShell
    Server-Gui-Mgmt-Infra:
        Graphical Management Tools and Infra...
    Server-Gui-Shell:
        Server Graphical Shell
    Storage-Services:
        Storage Services
    User-Interfaces-Infra:
        User Interfaces and Infrastructure
    Web-Health:
        Health and Diagnostics
    Web-Http-Logging:
        HTTP Logging
    Web-Request-Monitor:
        Request Monitor
    Web-Server:
        Web Server (IIS)
    Web-WebServer:
        Web Server
    WoW64-Support:
        WoW64 Support
```

```
➜  salt git:(tagv2015.8.8.2) sudo salt 'win2012' test.versions_report
win2012:
    Salt Version:
               Salt: 2015.8.8
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist:   
            machine: AMD64
            release: 2012Server
             system: 2012Server 6.2.9200 SP0 Multiprocessor Free
```

Is there anything in my test case that is different form your use case to help me replicate this?
