### ISSUE TITLE
Running "boto_elb.present" on existing elb failes 

### ISSUE THREAD

**Issue by Suberri** [saltstack/salt#33288]
## When I run the following state twice, the first run create the elb and the second run fails. 

```
Ensure saltstack-test-useast1 elb exists:
  boto_elb.present:
    - name: saltstack-test-useast1
    - availability_zones:
      - us-east-1a
      - us-east-1d
      - us-east-1e
    - listeners:
        - elb_port: 80
          instance_port: 80
          elb_protocol: HTTP
        - elb_port: 443
          instance_port: 80
          elb_protocol: HTTPS
          instance_protocol: HTTP
          certificate: 'arn:aws:iam::841111111:server-certificate/saltstackcert'
    - health_check:
        target: 'HTTP:80/'
    - attributes:
        access_log:
          enabled: true
          s3_bucket_name: 'salt-stack-s3-bucket-test'
          s3_bucket_prefix: 'logs'
          emit_interval: '5'
```

---

error message:

```
local:
----------
          ID: Ensure saltstack-testing-useast1 elb exists
    Function: boto_elb.present
        Name: saltstack-testing-useast1
      Result: False
     Comment: ELB saltstack-testing-useast1 present. Failed to modify security_groups on saltstack-testing-useast1 ELB.
     Started: 21:00:35.420129
    Duration: 354.024 ms
     Changes:
------------------
```
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
salt-call 2015.8.8.2 (Beryllium)
Minion runs in local mode
using salt-call state.apply
WIndows 8.1 Vagrant Ubuntu 14.. in VirtualBox
### Steps to Reproduce Issue
1. Ensure AWS does not have the elb and you have s3 and a certificate configured. 
2. Run the minion in local mode. 
3. Execute salt-call state.apply twice with the following state
4. result - first run: OK, second run: fails
   (Include debug logs if possible and relevant.)
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
