### ISSUE TITLE
Windows: pkg.install returns failed for msiexec/instmsi exit code 3010 (ERROR_SUCCESS_REBOOT_REQUIRED)

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#33298]
### Description of Issue/Question

When using `pkg.install` on Windows with a msiexec or instmsi installer, an [exit code of 3010](https://msdn.microsoft.com/en-us/library/windows/desktop/aa376931(v=vs.85).aspx) (ERROR_SUCCESS_REBOOT_REQUIRED) is technically a successful install, but `pkg.install` returns it as a failure.

```
[ERROR   ] Command ['c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\base\\xxxx\\4.6.01055\\NDP461-KB3102436-x86-x64-AllOS-ENU.exe', '/q', '/norestart'] failed with return code: 3010
```

### Versions Report
```
PS C:\Users\Administrator> C:\salt\salt-call.bat --local --versions-report
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 2012ServerR2
         system: 2012ServerR2 6.3.9600  Multiprocessor Free
```
