### ISSUE TITLE
 boto_asg.present -   launch_config parameters anomliy 

### ISSUE THREAD

**Issue by Suberri** [saltstack/salt#33345]
### Description of Issue/Question
I am creating AWS asg group using two config formats. In concept both of the configs are identical and should to work. However one works and the other fails.

The following state works ok: 
------------------------------- 
```
Ensure saltstack-testing-useast1 asg exists:
  boto_asg.present:
    -  .....
    - launch_config:
      - image_id:   ami-f5f41398
      - key_name: aws-key
      - security_groups:
        - saltstack
        - saltstack-testing
      - instance_type: m3.medium
      - instance_monitoring: true

  - .......
```

---------------------------------------------------------------------

Creating a dict from the above Launch_config params and passing the dict to the state fails.
The following state fails: 
------------------------------- 
```
Ensure saltstack-testing-useast1 asg exists:
  boto_asg.present:
    -  .....
    - launch_config: {'image_id': 'ami-f5f41398', 'instance_monitoring': True, 'instance_type': 'm3.medium', 'security_groups': ['saltstack', 'saltstack-testing'], 'key_name': 'aws-key'}
  - .......
```

The error message: 
args.update(cfg)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
 

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt-call 2015.8.8.2 (Beryllium)
