### ISSUE TITLE
dockerng.copy_to gives wrong number of argument when used from module.run

### ISSUE THREAD

**Issue by bberberov** [saltstack/salt#33342]
### Description of Issue/Question

I am trying to use `dockerng.copy_to` to copy a file from the salt server to a running container.

I keep getting this error:

```
    ----------
              ID: mail.rc configuration
        Function: module.run
            Name: dockerng.copy_to
          Result: False
         Comment: Module function dockerng.copy_to threw an exception. Exception: copy_to() takes at least 3 arguments (1 given)
         Started: 12:59:44.486537
        Duration: 1.813 ms
         Changes:
```

When I tried to do it manually, it works:
```
salt 'boian' dockerng.copy_to container source='salt://templates/mail.rc' dest='/etc/mail.rc' exec_driver='docker-exec' overwrite=True
```

It might be similar to this issue #31486

### Setup

This is a shortened SLS of what I use:
```
'Image':
  dockerng.image_present:
    - name: 'image'

'Container':
  dockerng.running:
    - name:  'container'
    - image: 'image'
    - require:
      - dockerng: 'Image'

'mail.rc configuration':
  module.run:
    - name: dockerng.copy_to
    - m_name: 'container'
    - source: 'salt://templates/mail.rc'
    - dest: '/etc/mail.rc'
    - overwrite: True
    - exec_driver: docker-exec
    - require: 
      - dockerng: 'Container'
```

The mail.rc can be any file; I don't think it matters.

### Steps to Reproduce Issue

1. Set up salt for docker
2. Run the SLS against the host

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-13-generic
         system: Ubuntu 14.04 trusty
```

```
# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

```
# pip show docker-py
---
Name: docker-py
Version: 1.7.2
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests, six, websocket-client
```

**Comment by Ch3LL** [comment]
@bberberov looks like the code is looking for `args`. can you try this and report back whether it works or not:

```
'ubuntu':
  dockerng.image_present:
    - name: 'ubuntu'

'Container':
  dockerng.running:
    - name:  'container'
    - image: 'ubuntu'
    - require:
      - dockerng: 'ubuntu'

'mail.rc configuration':
  module.run:
    - name: dockerng.copy_to
    - m_name: 'container's
    - overwrite: True
    - exec_driver: docker-exec
    - args:
        - salt://templates/mail.rc
        - /etc/mail.rc
    - require: 
      - dockerng: 'Container'
```
