### ISSUE TITLE
Documentation on match: in a top file doesn't match functionality

### ISSUE THREAD

**Issue by chizou** [saltstack/salt#33360]
According to the docs here https://docs.saltstack.com/en/latest/topics/targeting/compound.html, specifying `match: compound` should work

```
base:
    'role:consul_server':
        - match:grain
        - consul_server

    'not G@role:consul_server':
        - match:compound
        - consul_agent
```

However, specifying `match:compound`, I receive the following error:
```
i-0aef9c059616e426e:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'match:compound' in environment 'base' is not available on the salt master
```

If I remove the `match:compound` statement, applying the state works correctly.

**Comment by Ch3LL** [comment]
@chizou if you put a space between `match` and `compound` does it work. Like so:

```
base:
    'role:consul_server':
        - match: grain
        - test

    'not G@role:consul_server':
        - match: compound
        - test-file
```
