### ISSUE TITLE
Behavior of state grains.list_present and concurrency

### ISSUE THREAD

**Issue by max-peroch** [saltstack/salt#33399]
### Description of Issue/Question

Hi,
I am encountering a strange behavior with `grains.list_present`.
Some of my sls triger events from several minions to the reactor, and this works fine.
The reactor then calls a sls on a minion to store data on its grains.
The issue is that a lot of events are send at the same time and I guess `grains.list_present` has some trouble to handle concurrency ? 
A lot of data are lost or erased, somehow they are not stored in the grain at the end.
Probably not related, but my grain structure is 'complex'...

Anyway, I don't know if it is the expected behavior or not, can someone tell me ?

I managed to find a workaround by using the state `cmd.run` and calling the module `grains.append`.
It does the job, but I am not truely happy with that.
### Setup

**reactor.conf**

```
reactor:
  - 'xxxxx/set_grain':
    - /opt/set_grain.sls
```

**set_grain.sls**

```
xxxxxxxxxxxxxxxxxxx:
  local.state.apply:
    - tgt: 'my_minion*'
    - arg:
      - test
    - kwarg:
        queue: True
        pillar:
          id_minion: {{ data['id'] }}
```

**test.sls** on my_minion*

```
{% set id_minion = pillar['id_minion'] %}
create_grain:
  grains.list_present:
    - name: xxx:yyy:zzz:aaa:bbb:ccc:{{ id_minion }}
    - value: {{ something }}
```

Thanks a lot!

Maxime
