### ISSUE TITLE
Orchestrator does not fail on salt.function states with exceptions

### ISSUE THREAD

**Issue by nasenbaer13** [saltstack/salt#33400]
### Description of Issue/Question

When running an orchestration state salt.function that throws an exception, the state itself is considered successful and a requiring state as well.

### Setup

Orchestration state:
```
throw_exception:
  salt.function:
    - name: test.exception
    - tgt: mymaster
    - expect_minions: true

# This works / probably fixed in 29603
#throw_exception:
#  salt.state:
#    - tgt: mymaster
#    - sls: exception

noop:
  salt.function:
    - name: test.ping
    - tgt: mymaster
    - require:
      - salt: throw_exception
```

### Steps to Reproduce Issue

    salt-run state.orch test

Output:
```
com_mymaster:
----------
          ID: throw_exception
    Function: salt.function
        Name: test.exception
      Result: True
     Comment: Function ran successfully. Function test.exception ran on mymaster.
     Started: 15:02:46.867783
    Duration: 353.359 ms
     Changes:
              mymaster:
                  The minion function caused an exception: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1071, in _thread_return
                  return_data = func(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/test.py", line 510, in exception
                  raise Exception(message)
              Exception: Test Exception

----------
          ID: noop
    Function: salt.function
        Name: test.ping
      Result: True
     Comment: Function ran successfully. Function test.ping ran on mymaster.
     Started: 15:02:47.221578
    Duration: 247.784 ms
     Changes:
              mymaster:
                  True

Summary for com_mymaster
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
```

cmd_ret in function / saltmod.py is
```
{'ret': {'mymaster': 'The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1071, in _thread_return\n    return_data = func(*args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/modules/test.py", line 510, in exception\n    raise Exception(message)\nException: Test Exception\n'}, 'out': 'highstate'}
```

### Versions Report

A 2015.8.8. with some custom patches:

```
Salt Version:
           Salt: 2015.8.0-n/a-0f91c72

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-22-generic
         system: Ubuntu 16.04 xenial
```
