### ISSUE TITLE
Does pip.installed support local wheel packages?

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#33410]
Wheel package exists at C:\Program Files (x86)\Python 3.5\Scripts\pygame-1.9.2a0-cp35-none-win32.whl. It fails to install when using pip.installed...

```
install_pygame:
  pip.installed:
    - name: 'pygame-1.9.2a0-cp35-none-win32.whl'
    - cwd: 'C:\Program Files (x86)\Python 3.5\Scripts'
    - bin_env: 'C:\Program Files (x86)\Python 3.5\Scripts\pip.exe'
```

<pre>2016-05-20 18:59:45 [salt.state     ][INFO    ] Executing state pip.installed for pygame-1.9.2a0-cp35-none-win32.whl
2016-05-20 18:59:45 [salt.loaded.int.states.pip_state][DEBUG   ] Installed pip version: 7.1.0
2016-05-20 18:59:45 [pip.req.req_install][WARNING ] Requirement 'pygame-1.9.2a0-cp35-none-win32.whl' looks like a filename, but the file does not exist
2016-05-20 18:59:45 [salt.state     ][ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1624, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1492, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\pip_state.py", line 601, in installed
    out = _check_pkg_version_format(pkg)
  File "C:\salt\bin\lib\site-packages\salt\states\pip_state.py", line 140, in _check_pkg_version_format
    install_req = pip.req.InstallRequirement.from_line(pkg)
  File "C:\salt\bin\lib\site-packages\pip\req\req_install.py", line 197, in from_line
    wheel.filename
UnsupportedWheel: pygame-1.9.2a0-cp35-none-win32.whl is not a supported wheel on this platform.</pre>

...but installs correctly using pip.install...

```
salt salt-test pip.install pygame-1.9.2a0-cp35-none-win32.whl cwd='C:\Program Files (x86)\Python 3.5\Scripts' bin_env='C:\Program Files (x86)\Python 3.5\Scripts\pip.exe'
```

<pre>2016-05-20 19:30:00 [salt.loaded.int.module.cmdmod][INFO    ] Executing command ['C:\\Program Files (x86)\\Python 3.5\\Scripts\\pip.exe', 'install', 'pygame-1.9.2a0-cp35-none-win32.whl'] in directory 'C:\\Program Files (x86)\\Python 3.5\\Scripts'</pre>

Is installation of a local wheel package expected to work with pip.installed?

Tested on 2015.8.8-2 and 2015.8.10

**Comment by Ch3LL** [comment]
@morganwillcock I am not able to replicate this using the 64 bit version of pygame wheel file:

```
install_pygame:
  pip.installed:
    - name: 'pygame-1.9.2a0-cp35-none-win_amd64.whl'
    - cwd: 'C:\Users\ch3ll\AppData\Local\Programs\Python\Python35\Scripts'
    - bin_env: 'C:\Users\ch3ll\AppData\Local\Programs\Python\Python35\Scripts\pip.exe'
```

```
[DEBUG   ] LazyLoaded nested.output
win8:
----------
          ID: install_pygame
    Function: pip.installed
        Name: pygame-1.9.2a0-cp35-none-win_amd64.whl
      Result: True
     Comment: All packages were successfully installed
     Started: 17:47:57.050000
    Duration: 10017.0 ms
     Changes:   
              ----------
              pygame==1.9.2a0:
                  Installed

Summary for win8
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

Can you verify that pip on the local machine does not error? 

1. cd C:\<python35scripts directory>\
2. `./pip.exe install <pygame wheel file>`

Also try the salt python directory:
1. `cd C:\salt\bin\Scripts\`
2. `./pip.exe install <pygame wheel file>`
