### ISSUE TITLE
win_system.set_computer_name returns truncated output for long hostnames

### ISSUE THREAD

**Issue by m03** [saltstack/salt#33422]
### Description of Issue/Question

_win_system.set_computer_name_ and _win_system.get_pending_computer_name_ return truncated results when the new hostname is longer than 15 characters. The hostname change itself works as intended.

### Setup

Example of set_computer_name and get_pending_computer_name working as expected:
```
m03@devmaster01:~$ sudo salt 'win2012r2' system.get_computer_name
win2012r2:
    test-server0001
m03@devmaster01:~$ sudo salt 'win2012r2' system.set_computer_name test-server0002
win2012r2:
    ----------
    Computer Name:
        ----------
        Current:
            test-server0001
        Pending:
            test-server0002
m03@devmaster01:~$ sudo salt 'win2012r2' system.get_pending_computer_name
win2012r2:
    TEST-SERVER0002
m03@devmaster01:~$ sudo salt 'win2012r2' system.reboot
win2012r2:
    True
m03@devmaster01:~$ sudo salt 'win2012r2' system.get_computer_name
win2012r2:
    test-server0002
```

### Steps to Reproduce Issue

Example of set_computer_name and get_pending_computer_name on hostname longer than 15 characters:
```
m03@devmaster01:~$ sudo salt 'win2012r2' system.get_computer_name
win2012r2:
    test-server0002
m03@devmaster01:~$ sudo salt 'win2012r2' system.set_computer_name 'test-server000999'
win2012r2:
    ----------
    Computer Name:
        ----------
        Current:
            test-server0002
        Pending:
            TEST-SERVER0009
m03@devmaster01:~$ sudo salt 'win2012r2' system.get_pending_computer_name
win2012r2:
    TEST-SERVER0009
```

As mentioned above, the name change itself still works as intended.

### Versions Report
Minion:
```
m03@devmaster01:~$ sudo salt 'win2012r2' test.versions_report
win2012r2:
    Salt Version:
               Salt: 2016.3.0

    Dependency Versions:
               cffi: 1.5.0
           cherrypy: 5.0.1
           dateutil: 2.4.2
              gitdb: 0.6.4
          gitpython: 1.0.1
              ioflo: 1.5.0
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: 1.4.4
           M2Crypto: 0.21.1
               Mako: 1.0.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: Not Installed
            Tornado: 4.3
                ZMQ: 4.1.2

    System Versions:
               dist:
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
