### ISSUE TITLE
Number of master processes

### ISSUE THREAD

**Issue by jakehilton** [saltstack/salt#33433]
### Description of Issue/Question

I'm seeing on some masters that I have a single master process running with a good number of subprocesses running under it.. which is to be expected. On other boxes I see multiple master processes running with a few subprocesses.. as well as the larger main master process. This seems to cause some issues with minions running commands against the master. If I restart the salt master service then the smaller master processes go away.

So my question is how many top level master processes should I expect to see?

I have attached a few htop screenshots of what I"m seeing in terms of the processes on a box with more than one master process.

Thanks!
### Setup

Master config

```
hash_type: sha256
keep_jobs: 1
open_mode: True
state_output: mixed
state_verbose: False
timeout: 30
transport: tcp
worker_threads: 10

file_roots:
  base:
    - /etc/salt/git/salt
    - /etc/salt/git/salt/states

pillar_roots:
  base:
    - /etc/salt/git/salt/pillar
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.0rc3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.1
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.22
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: 0.6.5
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

Master process with many subprocesses.
![screen shot 2016-05-23 at 08 50 50](https://cloud.githubusercontent.com/assets/243169/15474777/a7378eb2-20c3-11e6-8fe5-a8f97df2338d.png)

Other Master processes on the same box with a few subprocesses. 
![screen shot 2016-05-23 at 08 50 32](https://cloud.githubusercontent.com/assets/243169/15474784/abae38ce-20c3-11e6-976c-cb7d2178f895.png)
