### ISSUE TITLE
salt-call waits infinitely on apt-get of mysql server community edition

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#33442]
### Description of Issue/Question

salt-call hangs on the following command:

```
[INFO    ] Executing command ['apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'mysql-server'] in directory '/root'
```

in processes:

```
4 S root     30114 16398  0  80   0 - 152946 pipe_w 20:53 pts/1   00:00:01 /usr/bin/python /usr/bin/salt-call state.highstate
4 Z root     30339 30114  0  80   0 -     0 exit   20:53 pts/1    00:00:01 [apt-get] <defunct>
0 S mysql    30808     1  0  80   0 -  1112 wait   20:53 ?        00:00:00 /bin/sh /usr/bin/mysqld_safe
0 S mysql    31598 30808  0  80   0 - 1004891 poll_s 20:53 ?      00:00:00 /usr/sbin/mysqld --basedir=/usr --datadir=/storage/mysql --plugin-dir=/usr/lib/mysql/plugin --log-error=/var/log/mysql/mysqld.log --open-files-limit=10000 --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306

```

in strace:

```
root@db02:/storage# strace -p 28116
Process 28116 attached
read(57,
```

in lsof:

```
salt-call 28116 root   57r  FIFO    0,9      0t0  56123 pipe
```
### Setup

```
root@infra01:/srv/salt/mysql# cat server.sls
{% from 'macros/macros.jinja' import get_local with context -%}
{% set root_password = get_local('mysql:root_creds:password', '') -%}

include:
  - scripts
  - zabbix.agent
  - apparmor

mysql_repo:
  pkgrepo.managed:
    - names:
      - deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7
    - file: /etc/apt/sources.list.d/mysql.list
    - keyserver: pgp.mit.edu
    - keyid: 5072E1F5
    - enabled: True
    - refresh_db: True

mysql_group:
  group.present:
    - name: mysql
    - system: True

mysql_user:
  user.present:
    - name: mysql
    - groups:
      - mysql
    - system: True
    - require:
      - group: mysql

mysql_mount_dir:
  file.directory:
    - name: /storage
    - user: root
    - group: root
    - mode: 755

mysql_data_dir:
  file.directory:
    - name: /storage/mysql
    - user: mysql
    - group: mysql
    - mode: 755
    - require:
      - user: mysql_user

mysql_etc_dir:
  file.directory:
    - name: /etc/mysql
    - user: root
    - group: root
    - mode: 755

mysql_config_file:
  file.managed:
    - name: /etc/mysql/my.cnf
    - source: salt://mysql/server/my.cnf
    - user: root
    - group: root
    - mode: 644
    - require:
      - file: mysql_etc_dir

mysql_conf.d_dir:
  file.directory:
    - name: /etc/mysql/conf.d
    - user: root
    - group: root
    - mode: 755
    - require:
      - file: mysql_etc_dir

mysql_safe_config_file:
  file.managed:
    - name: /etc/mysql/conf.d/mysqld_safe_syslog.cnf
    - source: salt://mysql/server/mysqld_safe_syslog.cnf
    - user: root
    - group: root
    - mode: 644
    - require:
      - file: mysql_conf.d_dir

mysql_tuning_config_file:
  file.managed:
    - name: /etc/mysql/conf.d/mysqld_tuning.cnf
    - source: salt://mysql/server/mysqld_tuning.cnf
    - user: root
    - group: root
    - mode: 644
    - require:
      - file: mysql_conf.d_dir

mysql_repl_config_file:
  file.managed:
    - name: /etc/mysql/conf.d/mysqld_replication.cnf
    - source: salt://mysql/server/mysqld_replication.cnf
    - user: root
    - group: root
    - mode: 644
    - require:
      - file: mysql_conf.d_dir

mysql_apparmor_config:
  file.managed:
    - name: /etc/apparmor.d/usr.sbin.mysqld
    - source: salt://mysql/server/usr.sbin.mysqld.apparmor
    - user: root
    - group: root
    - mode: 644
    - watch_in:
      - service: apparmor_service

mysql_server_debconf:
  debconf.set:
    - name: mysql-community-server
    - data:
        'mysql-community-server/root-pass': {'type': 'password', 'value': '{{ root_password }}'}
        'mysql-community-server/re-root-pass': {'type': 'password', 'value': '{{ root_password }}'}

mysql_server_packages:
  pkg.installed:
    - names:
      - mysql-server
      - python-mysqldb
    - require:
      - debconf: mysql_server_debconf
      - user: mysql_user
      - file: mysql_data_dir
      - file: mysql_config_file
      - file: mysql_safe_config_file
      - file: mysql_tuning_config_file
      - file: mysql_repl_config_file
      - file: mysql_apparmor_config
```
### Steps to Reproduce Issue

```
[INFO    ] Running state [mysql-server] at time 20:53:22.501370
[INFO    ] Executing state pkg.installed for mysql-server
[INFO    ] Executing command 'apt-get -q update' in directory '/root'
[INFO    ] Executing command ['apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'mysql-server'] in directory '/root'
```

Hangs forever, the install of the package is finished in the background, the DB is initialized.
apt-get is a zombie.
### Versions Report

```
root@db02:/storage# salt-call --versions-report
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-59-generic
         system: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@zerthimon I'm not able to replicate this. Here is my test case:

```
root@vagrant-ubuntu-trusty-64:~# cat /srv/salt/test.sls
mysql_server_packages:
  pkg.installed:
    - names:
      - mysql-server
      - python-mysqldb
```

Run salt-call:
`salt-call --local state.sls test -ldebug `

The packages are installed without delay:

```
Summary for local
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
```

```
root@vagrant-ubuntu-trusty-64:~# salt --versions-report
Salt Version:
           Salt: 2015.8.10
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-65-generic
         system: Ubuntu 14.04 trusty
 ```

Is there something in my test case above that is wrong that will help me to replicate this issue?

**Comment by zerthimon** [comment]
Now if the watched config file changes the service restars and the salt-call doesn't finish waiting on:
```
INFO    ] Running state [mysql] at time 12:45:20.220713
[INFO    ] Executing state service.mod_watch for mysql
[INFO    ] Executing command ['service', 'mysql', 'status'] in directory '/root'
[INFO    ] Executing command ['service', 'mysql', 'restart'] in directory '/root'
```

The service is restarted, the init script is a zombie, salt-call never finishes:
```
4 S root      5450  2288  0  80   0 - 162966 pipe_w 12:45 pts/0   00:00:01 /usr/bin/python /usr/bin/salt-call state.highstate
0 Z root      5601  5450  0  80   0 -     0 exit   12:45 pts/0    00:00:00 [mysql] <defunct>
0 S mysql     5683     1  0  80   0 -  1112 wait   12:45 ?        00:00:00 /bin/sh /usr/bin/mysqld_safe
0 S mysql     6477  5683  0  80   0 - 1004890 poll_s 12:45 ?      00:00:00 /usr/sbin/mysqld --basedir=/usr --datadir=/storage/mysql --plugin-dir=/usr/lib/mysql/plugin --log-error=/var/log/mysql/mysqld.log --open-files-limit=10000 --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306
```

salt-call process straced:
```root@db02:~# strace -p 5450
Process 5450 attached
read(57,
```
salt-call process lsof:
```
salt-call 5450 root   57r  FIFO    0,9      0t0  22461 pipe
```

**Comment by zerthimon** [comment]
Same situation when service is stopped and salt-call enforces the start:

```
[INFO    ] Executing command ['service', 'mysql', 'status'] in directory '/root'
[ERROR   ] Command ['service', 'mysql', 'status'] failed with return code: 3
[ERROR   ] output:  * MySQL Community Server 5.7.12 is not running
[INFO    ] Executing command ['service', 'mysql', 'start'] in directory '/root'
```

**Comment by zerthimon** [comment]
@Ch3LL 
To reproduce use the following SLS
```
root@db01:/srv/salt# cat test.sls 
mysql_repo:
  pkgrepo.managed:
    - names:
      - deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7
    - file: /etc/apt/sources.list.d/mysql.list
    - keyserver: pgp.mit.edu
    - keyid: 5072E1F5
    - enabled: True
    - refresh_db: True

mysql_server_debconf:
  debconf.set:
    - name: mysql-community-server
    - data:
        'mysql-community-server/root-pass': {'type': 'password', 'value': 'root'}
        'mysql-community-server/re-root-pass': {'type': 'password', 'value': 'root'}

mysql_server_packages:
  pkg.installed:
    - names:
      - mysql-server
    - require:
      - debconf: mysql_server_debconf
```
