### ISSUE TITLE
pkgrepo broken in 2015.8.10 TypeError: expand_repo_def() got multiple values for keyword argument 'repo'

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#33447]
### Description of Issue/Question

Upgraded to 2015.8.10 and now multiple of my pkgrepo states no longer function.

### State

````
salt_repo:
  pkgrepo.managed:
    - repo: "deb http://repo.saltstack.com/apt/ubuntu/ubuntu14/2015.8 trusty main"
    - file: /etc/apt/sources.list.d/saltstack.list
    - keyid: 754A1A7AE731F165D5E6D4BD0E08A149DE57BFBE # SaltStack Packaging Team
    - keyserver: keyserver.ubuntu.com
````

### Output

````
local:
----------
          ID: salt_repo
    Function: pkgrepo.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pkgrepo.py", line 327, in managed
                  sanitizedkwargs = __salt__['pkg.expand_repo_def'](repo=repo, **kwargs)
              TypeError: expand_repo_def() got multiple values for keyword argument 'repo'
     Started: 19:39:01.326105
    Duration: 31.62 ms
     Changes:   
````

### Versions Report

Works on 2015.8.8.2.  Fails on 2015.8.10.
````
Salt Version:
           Salt: 2015.8.10
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-71-generic
         system: Ubuntu 14.04 trusty
````

**Comment by Ch3LL** [comment]
@notpeter I am able to replicate this same behavior. It works on 2015.8.8.2 but not 2015.8.10:

Here is the git bisect:


```
root@vagrant-ubuntu-trusty-64:~/salt# git bisect bad
709d80bb1bd9d3c53693a2c2a1bb43862d80f6ff is the first bad commit
commit 709d80bb1bd9d3c53693a2c2a1bb43862d80f6ff
Author: Erik Johnson <palehose@gmail.com>
Date:   Fri Mar 25 11:03:27 2016 -0500

    aptpkg: Accept **kwargs instead of a dict for pkg.expand_repo_def

:040000 040000 2d0942141d42e0c784f101333f7686575f45ffd9 0e4aab358c3f719af8f77860d34d43732e775378 M      salt
```

ping @terminalmage

**Comment by Ch3LL** [comment]
Also seeing this in 2016.3.0 and head of 2016.3

**Comment by terminalmage** [comment]
``repo`` has never been a officially-supported argument for the ``pkgrepo.managed`` state, this is just a case of the invalid argument not being caught in the keyword arguments for the state, and that ``repo`` is actually an argument for ``pkg.expand_repo_def``. So, when the keyword arguments are passed through, it still works.

Essentially, we were letting invalid configuration result in a successful state run.

Change ``repo`` to ``name`` and it should work, like below

```yaml
salt_repo:
  pkgrepo.managed:
    - name: "deb http://repo.saltstack.com/apt/ubuntu/ubuntu14/2015.8 trusty main"
    - file: /etc/apt/sources.list.d/saltstack.list
    - keyid: 754A1A7AE731F165D5E6D4BD0E08A149DE57BFBE # SaltStack Packaging Team
    - keyserver: keyserver.ubuntu.com
```

**Comment by terminalmage** [comment]
I've opened https://github.com/saltstack/salt/pull/33477 to gracefully fail this state when the ``repo`` param is used.

**Comment by notpeter** [comment]
I guess I've been relying on undocumented behavior for years.  ;)

I appreciate the quick duplication and patch to make 'repo' an explicitly unsupported key for pkgrepo states.  Thanks all.

**Comment by tomlaredo** [comment]
I'm having the exact same problem but my definition isn't using "repo" at all:

```
----------
          ID: debian-repository-preprod
    Function: pkgrepo.managed
        Name: deb http://preprod-debian.mycompany.com/ jessie main
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python2.7/site-packages/salt/state.py", line 1626, in call
                  if 'check_cmd' in low and '{0[state]}.mod_run_check_cmd'.format(low) not in self.states:
                File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python2.7/site-packages/salt/states/pkgrepo.py", line 327, in managed
                  sanitizedkwargs = __salt__['pkg.expand_repo_def'](repo=repo, **kwargs)
              TypeError: expand_repo_def() got an unexpected keyword argument 'repo'
     Started: 19:32:34.351730
    Duration: 76.344 ms
     Changes:
```

Here is the state definition:
```
debian-repository-preprod:
    pkgrepo.managed:
        - name: deb http://preprod-debian.mycompany.com/ jessie main
        - key_url: http://preprod-debian.mycompany.com/mycompany.gpg
        - file: /etc/apt/sources.list.d/mycompany.list
```

As you can see, I'm using "name" and not "repo".
What am I missing there?
