### ISSUE TITLE
granular @wheel permissions with external_auth

### ISSUE THREAD

**Issue by ssplatt** [saltstack/salt#33479]
### Description of Issue/Question
the external_auth system should be able to granularly limit access to `@wheel` modules instead of 'all or nothing'. In the example on the [rest_cherrypy docs page under keys POST](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Keys.POST), a kickstart user is able to generate and accept the new minion. In this use case, the kickstart user should have no access to any other wheel functions, so a permission similar to `@wheel.key.gen_accept` would be desired.

### Setup
use the example request in the link above:
```
curl -sSk https://localhost:8000/keys \
        -d mid=jerry \
        -d username=kickstart \
        -d password=kickstart \
        -d eauth=pam \
        -o jerry-salt-keys.tar
```
only perms that works currently:
```
external_auth:
  pam:
    kickstart:
      - '@wheel'
```
perms that don't work:
```
external_auth:
  pam:
    kickstart:
      - '@wheel.key'
      - '@wheel.key.gen_accept'
      - '@wheel.key.*'
      - 'key.*'
      - 'key.gen_accept'
      - 'wheel.key'
      - 'wheel.key.gen_accept'
      - 'wheel.key.*'
```

### Steps to Reproduce Issue
try to set any permission other than `-'@wheel'` and fail hard.

### Versions Report
```
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 5.4.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2
```
