### ISSUE TITLE
SPM does not work on amazon linux 2015 in 2016.3.0

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#33517]
### Description of Issue/Question
SPM does not work and stack traces on Amazon 2015 in 2016.3.0:

```
[ec2-user@ip-10-13-173-168 ~]$ spm --help
Traceback (most recent call last):
  File "/usr/bin/spm", line 8, in <module>
    from salt.scripts import salt_spm
ImportError: No module named salt.scripts
```

### Setup
Amazon Linux 2015 with 2016.3.0 minion

### Steps to Reproduce Issue
1. Install salt 2016.3.0
2. `spm --help`

```
[ec2-user@ip-10-13-173-168 ~]$ cat /usr/bin/spm
#!/usr/bin/python
'''
Publish commands to the salt system from the command line on the master.

.. versionadded:: 2015.8.0
'''

from salt.scripts import salt_spm


if __name__ == '__main__':
    salt_spm()
```

```
[ec2-user@ip-10-13-173-168 ~]$ cat /usr/bin/salt-minion
#!/usr/bin/python2.6
'''
This script is used to kick off a salt minion daemon
'''
```

As shown above the python versions are different. The salt-minion script/process does work.

### Versions Report
```
[ec2-user@ip-10-13-173-168 ~]$ salt --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Dec 17 2015, 01:08:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.1.17-22.30.amzn1.x86_64
         system: Linux
        version: Not Installed
```
