### ISSUE TITLE
file.replace broken

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#33523]
### Description of Issue/Question

============
8><---

```
----------
          ID: /etc/rsyslog.conf
    Function: file.replace
      Result: False
     Comment: Missing parameter pattern for state file.replace
              Missing parameter repl for state file.replace
     Started: 
    Duration: 
     Changes:   
----------
```

============

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Code I use,
========

```
#rhel7
{% if grains['oscodename'] == 'Maipo' %}

#replace rsyslog-7:

/etc/rsyslog.conf:
  #file.managed:
  file.replace:
    - source: salt://7-rsyslog.conf
#    - source_hash: md5=257fb2fa730100927df5ee4119996eca
    - user: root
    - group: root
    - mode: 644
    - backup: minion

{% endif %}
```

========

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
happens every time

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

output,
========
salt master

```
-bash-4.1# salt --versions-report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: 0.3.4
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: redhat 6.7 Santiago
        machine: x86_64
        release: 2.6.32-573.18.1.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.7 Santiago
 
-bash-4.1#
```
 
======

Salt-minion
======

```
[root@vuwunicochdnsp1 ~]# rpm -q salt-minion
salt-minion-2016.3.0-1.el7.noarch
[root@vuwunicochdnsp1 ~]#
```

**Comment by gzcwnk** [comment]
I need to upgrade the server?

**Comment by gzcwnk** [comment]
Nope did that still have a failure.

**Comment by Ch3LL** [comment]
@gzcwnk looks like your missing a couple parameters for file.replace to work appropriate. The options are documented [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.replace). It requires teh pattern, repl, and name options. Looks like maybe you are possibly trying do a file.managed.

Can you try adding the required options for `file.replace`? Do you still get the error then?

**Comment by diego-XA** [comment]
Not sure if related but I am having a very odd behaviour with `file.replace`

I have an state with this:

```yaml
write_web_user_name:
  file.replace:
    - name: /var/lib/secret
    - pattern: \s*\*user\*:.*
    - repl: "    *user*: {{ pillar['web_user']['name'] }}"
    - count: 1
    - backup: False
    - require:
      - file: write_main_info

write_web_user_pass:
  file.replace:
    - name: /var/lib/secret
    - pattern: \s*\*pass\*:.*
    - repl: "    *pass*: {{ pillar['web_user']['generated_pw']['text']  }}"
    - count: 1
    - backup: False
    - require:
      - file: write_main_info
```

And it is doing this:

```
          ID: write_web_user_name
    Function: file.replace
        Name: /var/lib/secret
      Result: True
     Comment: Changes were made
     Started: 23:34:39.147061
    Duration: 4.531 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -11,8 +11,7 @@
                   
                   
                   ## developer ##
                  -#
                  -    *user*:
                  +#    *user*: webops
                       *pass*:
                   
              ----------
          ID: write_web_user_pass
    Function: file.replace
        Name: /var/lib/secret
      Result: True
     Comment: Changes were made
     Started: 23:34:39.152245
    Duration: 2.675 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -11,8 +11,7 @@
                   
                   
                   ## developer ##
                  -#    *user*: webops
                  -    *pass*:
                  +#    *user*: webops    *pass*: Kh40RLRFwMHtnFqA
                   
                   #
```

This worked previously (at least in `2015.5.3`) but it is failing in `2016.3.0 `. Anyway I think this is a bug. Do you want me to open a new ticket? This ticket name is generic enough :)
