### ISSUE TITLE
2016.3 breaks existing formulas that work on 2015.8

### ISSUE THREAD

**Issue by Routhinator** [saltstack/salt#33532]
May 26 06:57:29 db.example.com salt-minion[13276]: [CRITICAL] Rendering SLS 'base:firewalld.services' failed: while parsing a flow mapping
May 26 06:57:29 db.example.com salt-minion[13276]: in "<unicode string>", line 43, column 18:
May 26 06:57:29 db.example.com salt-minion[13276]: service: {'short': 'ums-listener', 'descr ...
May 26 06:57:29 db.example.com salt-minion[13276]: ^
May 26 06:57:29 db.example.com salt-minion[13276]: expected ',' or '}', but got '<scalar>'
May 26 06:57:29 db.example.com salt-minion[13276]: in "<unicode string>", line 43, column 83:
May 26 06:57:29 db.example.com salt-minion[13276]: ... ption': 'Universal Media Server's listening port on port 5001/tc ...
May 26 06:57:29 db.example.com salt-minion[13276]: ^

**Comment by Ch3LL** [comment]
@Routhinator just to confirm you are attempting to use this [module](https://github.com/saltstack-formulas/firewalld-formula/blob/master/firewalld/services.sls) ?

Can you share your sanitized pillar data for [here](https://github.com/saltstack-formulas/firewalld-formula/blob/master/firewalld/services.sls#L43)

**Comment by Routhinator** [comment]
I am using the above module, and 'attempting' isn't the correct word. My production environment has used this module for the last few versions of salt. After further inspection it is choking on the **'** in **Server's** in the below pillar.sls. I've tried wrapping the description in single and double quotes, but the only way to get Salt to 2016.3 to read this is to remove the **'**.

```
firewalld:
  enabled: True
  default_zone: public
  services:
    imap:
      short: imap
      description: Insecure mail IMAP port on 143/tcp.
      ports:
        tcp:
          - 143
    kerberos-adm:
      short: kerberos-adm
      description: Kerberos administration and password change port on 749/tcp+udp.
      ports:
        tcp:
          - 749
        udp:
          - 749
    microsoft-ds:
      short: microsoft-ds
      description: Microsoft Domain Services port. Successor to NetBIOS, uses 445/tcp+udp.
      ports:
        tcp:
          - 445
        udp:
          - 445
    netbios-ns:
      short: netbios-ns
      description: NetBIOS name services on ports 137-139/tcp+udp.
      ports:
        tcp:
          - 137
          - 138
          - 139
        udp:
          - 137
          - 138
          - 139
    smtps:
      short: smtps
      description: SMTP on port 587/tcp+udp for secure mail transmission.
      ports:
        udp:
          - 587
    snmp:
      short: snmp
      description: SNMP on port 161/tcp+udp for remote monitoring of the system.
      ports:
        udp:
          - 161
        tcp:
          - 161
    snmptrap:
      short: snmptrap
      description: SNMP Trap port 162/tcp+udp for remote monitoring of the system.
      ports:
        udp:
          - 162
        tcp:
          - 162
    salt-master:
      short: salt-master
      description: Ports for minions to communicate with the Salt Master on 4505-4506/tcp.
      ports:
        tcp:
          - 4505
          - 4506
    upnp-dlna:
      short: upnp-dlna
      description: UPnP/DLNA port 1900/tcp+udp for network discovery of media services. Susceptible to attack, open with caution.
      ports:
        udp:
          - 1900
        tcp:
          - 1900
    ums-listener:
      short: ums-listener
      description: **Universal Media Server's listening port on port 5001/tcp.**
      ports:
        tcp:
          - 5001
  zones:
    public:
      short: Public
      description: 'The default, restrictive firewalld zone.'
    trusted:
      interfaces:
        - lo

```
