### ISSUE TITLE
git.latest not fetching before switching revision

### ISSUE THREAD

**Issue by giorgiosironi** [saltstack/salt#33573]
When switching git.latest to a revision not already present locally, I get

```
[54.209.54.222] out:           ID: install-lax
[54.209.54.222] out:     Function: git.latest
[54.209.54.222] out:         Name: https://github.com/elifesciences/lax
[54.209.54.222] out:       Result: False
[54.209.54.222] out:      Comment: Command 'git checkout --force -b pinned-revision 50561c0fa1378e51c1dc512b92e427b3e03e85c0' failed
[54.209.54.222] out:      Started: 10:26:22.919493
[54.209.54.222] out:     Duration: 465.248 ms
[54.209.54.222] out:      Changes:
```

To make it work, I had to manually perform a `git fetch` and re-run salt.
### Setup

```
    git.latest:
        - name: https://github.com/elifesciences/lax
        - rev: {{ salt['elife.cfg']('project.revision', 'project.branch', 'master') }}
        - branch: pinned-revision
        - target: /srv/lax/
        - force_fetch: True
        - force_checkout: True
        - force_reset: True
```

We had to specify a `branch` here or `revision` was getting ignored, leaving the repository on the previously existing branch.
### Steps to Reproduce Issue

The `git.latest` configuration is provided, and the repository is public. I guess this isn't repository-specific but happens with this configuration when you're requiring a new sha that is present on the remote but not locally.
### Versions Report

```
root@develop--end2end:/srv/lax# salt --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-83-generic
         system: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@giorgiosironi I believe I was able to replicate this with the following state file:

```
➜  git cat /srv/salt/issues/33573.sls
salt-git:
  git.latest:
      - name: https://github.com/saltstack/salt.git
      - rev: 62a6bde0ea517f681cf9a7242f5c1761331411ad
      - branch: v2016.3.0
      - target: /home/ch3ll/git/salt/
      - force_fetch: True
      - force_checkout: True
      - force_reset: True
```

On first run of running state.sls it stated the commit `62a6bde0ea517f681cf9a7242f5c1761331411ad` was not available. I did a manual git fetch then the state ran correctly.

Looks like this might be possibly related to #13317 and #13550
