### ISSUE TITLE
Precedence for mod_watch and onlyif

### ISSUE THREAD

**Issue by tomlaredo** [saltstack/salt#33621]
### Description of Issue/Question

Lets assume that we have a state like this:

```
my-state:
    cmd.wait:
        - name: mycommand
        - watch:
            - git: my-git-state
```

How can we make salt run "my-state" ONLY IF a file exists?
As documentation says that we could use the "onlyif" statement for this, I wrote the state like this:

```
my-state:
    cmd.wait:
        - name: mycommand
        - watch:
            - git: my-git-state
        - onlyif: test -f /path/file_to_test.txt
```

The problem is that, if the "my-git-state" raises, "my-state" will run even if the "onlyif" condition is NOT met.

I also tried to put the onlyif statement under the "- watch" statement but it does'nt work too.

The question is: how can we say "Do NOT run this state if the onlyif condition is not met, even if watch statement raised" ?

**Comment by Ch3LL** [comment]
@tomlaredo reading the following issues: #29492 and #17177 it seems that using cmd.run with onchanges is the preferred method as documented [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html#should-i-use-cmd-run-or-cmd-wait)

Can you try something similar to the following:

```
test:
  cmd.run:
    - name: touch /tmp/testtest

my-state:
    cmd.run:
        - name: touch /tmp/my-state
        - onchanges:
            - cmd: test
        - onlyif: test -f /tmp/testtest2
```

**Comment by tomlaredo** [comment]
Ok, thanks for the help.
Now that I have understood the cmd.wait issue in my state, I have a complementary question (tell me if it is better to ask it in a new ticket).

The current behavior of my states:
- git.latest
- cmd.run (must be run only if git files have changed)

And the corresponding states:
```
checkout-state:
    git.latest:
        - name: git@xxx.net:yyy/zzz.git
        - target: xxx
        - identity: xxx
        - rev: xxx

deploy-state:
    cmd.run:
        - name: /my/path/deploy.sh
        - onchanges:
            - git: checkout-state
```

Let's now assume that cmd.run fails for any reason.
If I run a salt-call state.apply again, nothing will be done because the git repo is already up to date.

So I wanted something like this:
- git.latest
- touch a flag file to say "I'm deploying"
- cmd.run (must be run only if git files have changed OR if the flag file is present)
- file.absent on flag file

Here is my code:
```
checkout-state:
    git.latest:
        - name: git@xxx.net:yyy/zzz.git
        - target: xxx
        - identity: xxx
        - rev: xxx

touch-deploying-flag:
    cmd.run:
        - name: touch {{ deploying_flag }}
        - onchanges:
            - git: checkout-state

deploy-state:
    cmd.run:
        - name: /my/path/deploy.sh
        - onchanges:
            - git: checkout-state
        - onlyif: test -f {{ deploying_flag }}

remove-deploying-flag:
    file.absent:
        - name: {{ deploying_flag }}
        - onchanges:
            - cmd: deploy-state
```

but the deploy-state doesn't fire.
What could I do to achieve this goal?
