### ISSUE TITLE
2016.3.0 __grains__ dictionary empty when calling external pillar

### ISSUE THREAD

**Issue by tjuup** [saltstack/salt#33630]
### Description of Issue/Question

Since upgrading to 2016.3.0 **grains** dictionary is empty in external pillar config
### Setup

We have an external pillar config file that requires the fqdn of the minion making the pillar call.
The fqdn is collected from the  `__grains__` dictonary, but in 2016.3.0 this dictionary seems to be empty.
In the external pillar config this line now fails:
`host: {{ fqdn }}`
### Steps to Reproduce Issue

The _users_ state that uses the external pillar now fails because the fqdn is empty and the state fails with this error:

```
# salt myminion state.sls users
myminion:
Data failed to compile: 
----------
Pillar failed to render with the following messages: 
----------
Failed to load ext_pillar pillar_ldap: cannot concatenate 'str' and 'NoneType' objects
```

Note:
The 'NoneType' is because of the empty host {{ fqdn }}
### Versions Report

```
salt --versions-report                                                                                                                                                                                
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-83-generic
         system: Linux
        version: Ubuntu 14.04 trusty


```

**Comment by babilen** [comment]
Might (!) be related to https://github.com/saltstack/salt/issues/33614

**Comment by tjuup** [comment]
Might well be, because I wondered if no one else has this problem

**Comment by tjuup** [comment]
According to the docs `__grains__` should be availalbe in external pillar
[https://docs.saltstack.com/en/latest/topics/development/dunder_dictionaries.html#grains](https://docs.saltstack.com/en/latest/topics/development/dunder_dictionaries.html#grains)

**Comment by cachedout** [comment]
See if #33651 fixes this up.

**Comment by tjuup** [comment]
Yes, i can confirm the fix.

**Comment by tjuup** [comment]
I have reopened this issue, because after an saltutil.refresh_pillar the issue is still there.

**Comment by cachedout** [comment]
Hi @tjuup 

I'm having a little trouble figuring out your setup here. You're referring to a `external pillar config` that it sounds like you're expecting to have been templated with jinja. Could you provide a minimal test case that shows what you're doing here?

I have verified that external pillars in 2016.3.0 _do_ have grains available to them. Ex:

`master config`
```
ext_pillar:
  - issue_33630: dummy
```

`/srv/ext/pillar/issue_33630`
```
def ext_pillar( minion_id, pillar, *args, **kwargs ):
    my_pillar = {'external_pillar': {}}
    my_pillar['external_pillar_grains'] = __grains__
    return my_pillar
```

Running salt <my_minion> pillar.get external_pillar_grains shows all the grains.

Tested on 2016.3.0

**Comment by tjuup** [comment]
Hi @cachedout,

I tried to reproduce your external pillar in our environment

master config
```
  extension_modules: /opt/salt/modules
ext_pillar:
  - issue_33630: dummy

```
/opt/salt/modules/pillar/issue_33630 
```
def ext_pillar( minion_id, pillar, *args, **kwargs ):
    my_pillar = {'external_pillar': {}}
    my_pillar['external_pillar_grains'] = __grains__
    return my_pillar
```

Salt pillar.get external_pillar_grains doesn't show anything though

I saw that you updated the fix and i applied the new fix in our environment, but that made no difference. I restarted the master and minion, did refresh_pillar and sync_all but that did not help.
We have installed a workaround by not using grains to get the fqdn of the minion but using the miniion_id, which is always the same as the fqdn in our environment.

I can give more detail of the setup but have to filter out the private stuff

**Comment by cachedout** [comment]
Hi @tjuup 

Are you certain that you have the external pillar named with a `.py` extension and that is it in the location on the master specified by `extension_modules` in a sub-directory called `pillar/`?

**Comment by tjuup** [comment]
Yes, I can confirm above assumptions. The external pillar has worked for over 2 years without issues.
It is used to get users and sudousers out of our LDAP system.
It does that via a yaml file that contains the config to access the LDAP. 
The last line is the one failing:
host: {{ fqdn }}

This is later referenced by the external pillar module pillar_ldap.py.
You can find both files here:
https://gist.github.com/tjuup/863b76769502713db3fd76b7b43a591d
I have removed every private/company references in the config file and replaced them between <>.
As I mentioned before we do have a workaround by using the minion_id instead of "config['host']" in the external pillar module.
I won't take the credits for writing the code, it is of someone who left the office a few years ago.
Any help will be appreciated.

**Comment by zygiss** [comment]
I encounter this problem as well with [pepa](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.pepa.html) external pillar following an upgrade from `2015.8.5` to `2016.3.1`.

Here's how I'm able to reproduce it on my end with `pepa`:
`/usr/local/etc/salt/master`

```
file_client: local

file_roots:
  base:
    - /srv/salt/states

pillar_roots:
  base:
    - /srv/salt/pillar

pepa_roots:
  base: /srv/salt

ext_pillar:
  - pepa:
      resource: pepa
      sequence:
        - default:
```
`/srv/salt/pepa/default/default.yaml`
```
hostname: {{ grains.fqdn }}
```

And when I run `salt-call pillar.items`, the rendered `hostname` is `None`, where it should have the value of `{{ grains.fqdn }}`:
```
slave:
    ----------
    default:
        default
    environment:
        base
    hostname:
        None
    pepa_templates:
        - /srv/salt/pepa/default/default.yaml
```

Versions:
```
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  5 2016, 01:21:33)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
 
System Versions:
           dist:   
        machine: amd64
        release: 10.3-RELEASE
         system: FreeBSD
        version: Not Installed
```

The `issue_33630` pillar shared [above](https://github.com/saltstack/salt/issues/33630#issuecomment-224035307) works correctly, I have a complete list of grains in `external_pillar_grains` as expected.

The suggested PR https://github.com/saltstack/salt/pull/33651 is included in 2016.3.1 and doesn't help.

I'm puzzled by this.  Thanks for reading.
