### ISSUE TITLE
salt.states.hipchat.send_message doesn't work without direct access to internet

### ISSUE THREAD

**Issue by sebw** [saltstack/salt#33636]
My minions don't have direct access to the internet, as a result function hipchat.send_message is not possible:

```
----------
          ID: hipchat-message
    Function: hipchat.send_message
      Result: False
     Comment: Failed to send message: hipchat-message
     Started: 15:41:28.782136
    Duration: 35678.253 ms
     Changes:
```

It would be nice to be able to specify a proxy configuration in salt-minion config to allow external API calls.
