### ISSUE TITLE
ini.options_present uses DEFAULT_IMPLICIT as a literal section name

### ISSUE THREAD

**Issue by giannello** [saltstack/salt#33668]
### Description of Issue/Question

With 2016.6.3, ini.options_present doesn't work as expected when DEFAULT_IMPLICIT is used as section name.
### Setup

The following code used to work:

```
test:
  ini.options_present:
    - name: /tmp/test
    - sections:
        DEFAULT_IMPLICIT:
          TEST: 'AAA'
```

and created a file with

```
TEST = AAA
```

Now the file is created as

```
[DEFAULT_IMPLICIT]
TEST = AAA
```

Removing DEFAULT_IMPLICIT as section makes it work again

```
test:
  ini.options_present:
    - name: /tmp/test
    - sections:
        TEST: 'AAA'
```
