### ISSUE TITLE
Runas in Windows

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#33676]
### Description of Issue/Question
Runas seems to work from single commands from the CLI. Need to test using states. cmd.run with a state isn't passing the password for example.

### Setup
```
test_runas:
  file.managed:
    - name: 'C:\Temp\test.ps1'
  cmd.run:
    - name: 'C:\Temp\test.ps1'
    - shell: 'powershell'
    - runas: user
    - password: password
```

### Steps to Reproduce Issue
Apply the above state to get the following error:
```
         ID: test_runas
   Function: cmd.run
       Name: C:\Temp\test.ps1
     Result: False
    Comment: password is a required argument for runas on Windows
    Started: 15:36:13.640000
   Duration: 0.0 ms
    Changes:
```
### Versions Report
2016.3
