### ISSUE TITLE
visudo check command leaves cache file in /tmp

### ISSUE THREAD

**Issue by pepinje** [saltstack/salt#33708]
### Description of Issue/Question

When the check_cmd: /usr/sbin/visudo -c -f <sudo file> is run against a sudoers file being pushed to a system it creates a file in /tmp that starts with "tmp" and leaves it there.  This happens every time a salt-minion checks in.  Is there a way to prevent the "tmp" from being created or cached in /tmp on the clients?
### Setup

```
/etc/sudoers.d/jason:
  file.managed:
    - source: salt://app_customer/jason/files/etc/sudoers.d/jason
    - user: root
    - group: root
    - mode: 440
    - check_cmd: /usr/sbin/visudo -c -f
```
### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Apr  9 2015, 11:03:32)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed

System Versions:
           dist: redhat 7.1 Maipo
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: Red Hat Enterprise Linux Server 7.1 Maipo
```
