### ISSUE TITLE
Salt pillar empty on slave

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#33742]
### Description of Issue/Question

`salt '*' pillar.items` returns no data from the minion

```
salt '*' pillar.items
[hostname]:
    ----------
```

on the minion:

```
salt-call pillar.get 'info'
[INFO    ] Determining pillar cache
local:
```

even after refresh

```
salt '*' saltutil.refresh_pillar 
[hostname]:
    True
```
### Setup

[code escaping does not work here, my files are properly indented with two spaces]

```
pillar/top.sls :

base:
  '*':
    - common
```

```
pillar/common.sls :

  info: some data
```
### Steps to Reproduce Issue

no error in the salt master log

I can push apache config and restart sls files and it works

just this warning all the time
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
### Versions Report

Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2
            ZMQ: 4.1.4
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.3.7
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.4

**Comment by Ch3LL** [comment]
@phil123456 I am not able to replicate this using your common.sls pillar file. The pillar data is not empty:

```
➜  ~ cat /srv/salt/pillar/common.sls
info: some data
```

```
➜  ~ sudo salt 'ch3ll-ma*' pillar.item info
ch3ll-master:
    ----------
    info:
        some data
```

Are you seeing this behavior for other pillar values? Is that the entirety of the common.sls file? Are there more values in there? Any other informatin that would help me to replicate this?

**Comment by cachedout** [comment]
This sounds like you put your pillar files in the wrong location. By default, this is `/srv/pillar` and not `/srv/salt`.

**Comment by phil123456** [comment]
it's is /srv/salt/pillar

**Comment by phil123456** [comment]
did you try on debian 2.4 ? I just updated/upgrated all my machines, still the same issue

**Comment by phil123456** [comment]
salt '*' pillar.item info
host1:
    ----------
    info:
host2:
    ----------
    info:
host3:
    ----------
    info:

**Comment by phil123456** [comment]
/srv/salt$ tree
.
├── pillar
│   ├── common.sls
│   └── top.sls

I dont know what info I can give you, the upgrade just updated python to 2.7.11

the only thing that was weird during install is that I had to install python-pycurl BEFORE installing salt otherwise I had unresolvable python dependencies

dpkg -l  | grep python-pycurl 
ii  python-pycurl                         7.19.5-3                          amd64        Python bindings to libcurl

first salt does not seem to support filenames with dots, so I am going to have to find another solution than salt

**Comment by phil123456** [comment]
ok it is working the bloody config file poiinted pilar in /srv/pillar instead of /srv/salt/pillar ... wtf ???

**Comment by rallytime** [comment]
@phil123456 `/srv/pillar` is the default location for pillar_roots: https://docs.saltstack.com/en/latest/ref/configuration/master.html#pillar-roots

**Comment by baishancloudadmin** [comment]
I have same issue
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: 0.20.0
        libnacl: 1.4.3
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final


/srv/pillar# tree
.
├── dgroup-3
│   └── init.sls
├── dgroup-3lo.sls
├── test.sls
├── top.sls
├── group-6
│   └── init.sls
└── ygroup-3
    └── init.sls

#more top.sls 
base: 
  '*':
    - test
  'group-6*':
    - group-6
  'ygroup-3*':
    - ygroup-3
  'dgroup-3*':
    - dgroup-3lo

#more 
#####         Pillar settings        #####
##########################################
# Salt Pillars allow for the building of global data that can be made selectively
# available to different minions based on minion grain filtering. The Salt
# Pillar is laid out in the same fashion as the file server, with environments,
# a top file and sls files. However, pillar data does not need to be in the
# highstate format, and is generally just key/value pairs.
# pillar_roots:
#   base:
#     - /srv/pillar
#
#ext_pillar:
#  - hiera: /etc/hiera.yaml
#  - cmd_yaml: cat /etc/salt/yaml
#ext_pillar:
#  - cmd_yaml: bash  /srv/get-pillar.sh

# The ext_pillar_first option allows for external pillar sources to populate
# before file system pillar. This allows for targeting file system pillar from
# ext_pillar.
#ext_pillar_first: False
#ext_pillar_first: True

# The pillar_gitfs_ssl_verify option specifies whether to ignore ssl certificate
# errors when contacting the pillar gitfs backend. You might want to set this to
# false if you're using a git backend that uses a self-signed certificate but
# keep in mind that setting this flag to anything other than the default of True
# is a security concern, you may want to try using the ssh transport.
#pillar_gitfs_ssl_verify: True
# The pillar_opts option adds the master configuration file data to a dict in
# the pillar called "master". This is used to set simple configurations in the
# master config file that can then be used on minions.
#pillar_opts: False

# The pillar_safe_render_error option prevents the master from passing pillar
# render errors to the minion. This is set on by default because the error could
# contain templating data which would give that minion information it shouldn't
# have, like a password! When set true the error message will only show:
#   Rendering SLS 'my.sls' failed. Please see master log for details.
#pillar_safe_render_error: True

# The pillar_source_merging_strategy option allows you to configure merging strategy
# between different sources. It accepts four values: recurse, aggregate, overwrite,
# or smart. Recurse will merge recursively mapping of data. Aggregate instructs
# aggregation of elements between sources that use the #!yamlex renderer. Overwrite
# will verwrite elements according the order in which they are processed. This is
# behavior of the 2014.1 branch and earlier. Smart guesses the best strategy based
# on the "renderer" setting and is the default value.
#pillar_source_merging_strategy: smart

```
