### ISSUE TITLE
caller.cmd('event.send') not working with ipc_mode: tcp when specifying pull and pub ports in minion 2016.3.0

### ISSUE THREAD

**Issue by Inveracity** [saltstack/salt#33740]
### Description of Issue/Question

sending events using the python client api does not seem to work when the minion is in tcp mode instead of ipc.
### Setup

code:

``` python
import salt.client
caller = salt.client.Caller(c_path='/etc/salt/minion')
caller.cmd('event.send', 'testing/custom/tag', data={'foo': 'Foo'})
```

minion config:

``` yaml
id: testing
master: ['192.168.56.102']
tcp_pub_port: [4514]
tcp_pull_port: [4515]
ipc_mode: tcp
master_alive_interval: 59
acceptance_wait_time: 10
random_reauth_delay: 60
multiprocessing: true
hash_type: sha256
```
### Steps to Reproduce Issue
1. start the minion with tcp mode
2. run the python code.
3. view state.event on the master.
4. no custom event displayed :boom: 
5. change minion to ipc mode
6. run the python code
7. view state.event on the master
8. custom event displayed :white_check_mark: 
### Further investigation

It appears that setting:

``` yaml
tcp_pub_port: [4514]
tcp_pull_port: [4515]
```

causes the problem with ipc_mode set to tcp

commenting those out and it starts working again, though this is still an issue as we specifically want to set our pub and pull ports for multiple reasons.

Finally, no errors or stacktraces seem to be outputted to logs anywhere when the event is not sent.
### Versions Report

**Master**

``` yaml
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Minion**

``` yaml
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

Thanks for your time :heart: 

cc:
@ldmichelsen
@b3hni4
@tn8or

**Comment by Ch3LL** [comment]
hmmm i am not able to replicate this. Here are my steps:

```
master: localhost
tcp_pub_port: 4514
tcp_pull_port: 4515
ipc_mode: tcp
master_alive_interval: 59
acceptance_wait_time: 10
random_reauth_delay: 60
multiprocessing: true
hash_type: sha256
```

```
>>> import salt.client
>>> caller = salt.client.Caller(c_path='/etc/salt/minion')
>>> caller.cmd('event.send', 'testing/custom/tag', data={'TEST': 'Foo'})                                                   
True
```

And i can see it in the events running `sudo salt-run state.event pretty=True -ldebug`:

```
testing/custom/tag      {
    "_stamp": "2016-06-03T22:12:34.416610", 
    "cmd": "_minion_event", 
    "data": {
        "TEST": "Foo"
    }, 
    "id": "ch3ll-master", 
    "pretag": null, 
    "tag": "testing/custom/tag"
}
```

Is there anything to help me replicate this with my test case? Any luck if you remove the list type for the following:

```
tcp_pub_port: 4514
tcp_pull_port: 4515
```

**Comment by Ch3LL** [comment]
Also I opened this issue: #33769 because tcp_pub_port and tcp_pull_port cannot be a list. The reason for the issue is to handle the error better.

**Comment by Inveracity** [comment]
Thanks for the quick response!

Removing the list type does make it work again as suggested :white_check_mark: 

Maybe I should explain why we set the pull and pub ports as lists in the first place; We run 2 minions on every server we deploy. The default minion installation is left for the actual users of the system to use. The secondary minion is used by my team.
In order for both minions not to throw an error about ports already being in use I followed the [documentation](https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html#configure-minions) for multimaster setup that explains that the pull and pub ports need to be set as a list. 


#### More testing
Deployed 2 completely fresh ubuntu 14 machines using vagrant and virtualbox on my home pc. 
No use of multiple minions, just the default installations of master and minion.
This time with a yaml formatted list for a multimaster setup and still no event comes through.

```yaml
id: testing
master:
  - 192.168.56.102
  - 192.168.56.103
tcp_pub_port:
  - 4514
  - 4516
tcp_pull_port:
  - 4515
  - 4517
ipc_mode: tcp
master_alive_interval: 59
acceptance_wait_time: 10
random_reauth_delay: 60
multiprocessing: true
hash_type: sha256
```

Furthermore, changing the script to output the return from the caller yields `False`
```python
import salt.client
caller = salt.client.Caller(c_path='/etc/salt/minion')
ret = caller.cmd('event.send', 'testing/custom/tag', data={'foo': 'Foo'})
print ret
>>> False
```
where removing any sort of lists (python or yaml formatted), yields `True` and the event is shown not even in debug mode.

The only thing I do see on the master debug output is the auth below which appears consistently with the execution of the script, and that is all.
```text
[INFO    ] Authentication request from testing
[INFO    ] Authentication accepted from testing
[DEBUG   ] Sending event - data = {'id': 'testing', '_stamp': '2016-06-05T16:38:22.683460', 'result': True, 'pub': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgk<...shortened output...>\n-----END PUBLIC KEY-----', 'act': 'accept'}
[DEBUG   ] Gathering reactors for tag salt/auth
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
```

I tried spinning up a ubuntu 16 minion, maybe python 2.7.11 would be the trick,  but  same result, no event. I'm not sure what else to try at the moment to debug this.
