### ISSUE TITLE
Unable to pass pillar data as part of "source" path in file.managed

### ISSUE THREAD

**Issue by avekrivoy** [saltstack/salt#33746]
### Description of Issue/Question
Unable to pass pillar data as part of "source" path in file.managed
### my salt state /srv/salt/ftp/init.sls
```
create_config_for_virt_user:
  file.managed:
    - source: salt://ftp/config/{{ salt['pillar.get']('ftp:username') }}
    - name: /etc/vsftpd/users/{{ salt['pillar.get']('ftp:username') }}
    - template: jinja
    - defaults: {
      user_local_root: {{ salt['pillar.get']('ftp:user_local_root') }}
      }
```
 

### my pillar /srv/pillar/ftp/init.sls 
```
ftp:
  local_root: /var/www
  guest_username: www-data
  user_config_dir: /etc/vsftpd/users
  pasv_address: 151.80.46.138
  pasv_min_port: 32000
  pasv_max_port: 32100
  user_local_root: /var/www/html
  username: dev
  password: asd24k35ktk5

```
The result is:
```
ID: create_config_for_virt_user
    Function: file.managed
        Name: /etc/vsftpd/users/
      Result: False
     Comment: Specified target /etc/vsftpd/users/ is a directory
     Started: 04:34:45.018639
    Duration: 0.329 ms
     Changes:   
```
However, I can pass pillar data in variables such as ```user_local_root: {{ salt['pillar.get']('ftp:user_local_root') }}``` to my config files. 

### Versions Report
Master version report:
```
                  Salt: 2015.5.3
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1~bpo70+2
```
minion version:
```
salt-minion 2015.5.3 (Lithium)
```
