### ISSUE TITLE
cmd.script fails with runas in Windows

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#33761]
### Description of Issue/Question
cmd.script fails when using the runas parameter in Windows. The problem is that the script gets copied to the temp directory under the account of the user that is running salt. Then the runas portion is applied and unless the runas user has access to the temp directory where the script was saved, it will fail with an `Access is denied` error.

### Setup
Create a simple batch file named `/srv/salt/scripts/runas.bat` that has the following:
```
whoami > C:\temp\test.txt
```

### Steps to Reproduce Issue
This command will work just fine: `salt '*' cmd.script salt://scripts/runas.bat`
Result:
```
minion_name:
    ----------
    pid:
        2476
    retcode:
        0
    stderr:
    stdout:

        C:\Users\Administrator>whoami  1>C:\Temp\runas.txt
```

This command will fail: `salt '*' cmd.script salt://scripts/runas.bat runas=<username> password=<password>`
Result:
```
slee_dsc_2012:
    ----------
    pid:
        1240
    retcode:
        1
    stderr:
        Access is denied.
    stdout:
```

### Versions Report
Head of 2016.3 (and all previous)
```
    Salt Version:
               Salt: 2016.3.0-31-g56eab36

    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.3.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.2
              ioflo: 1.5.3
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: 1.4.4
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: 0.7.2.None
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.3
                ZMQ: 4.1.2

    System Versions:
               dist:
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
