### ISSUE TITLE
boto routing table broken - boto_vpc.route_table_present not working outside Virginia

### ISSUE THREAD

**Issue by damaex17** [saltstack/salt#33822]
### 

to reproduce, please run the following sls  for example on your master:

salt-call --local state.sls name_of_sls -l debug 

the routing table will be created but without a Name tag

```
{% for aws_reg,region in ('us-east-1','virginia'), ('eu-west-1','ireland'), ('eu-central-1','frankfurt') %}

something-dev-{{ region }}-vpc:
  boto_vpc.present:
    - name: something-dev-{{ region }}-vpc
    - cidr_block: 10.0.0.0/16
    - dns_hostnames: True
    - region: {{ aws_reg }}

something-dev-{{ region }}-subnet:
  boto_vpc.subnet_present:
    - name: something-dev-{{ region }}-subnet
    - cidr_block: 10.0.0.0/16
    - vpc_name: something-dev-{{ region }}-vpc
    - region: {{ aws_reg }}

something-dev-{{ region }}-gateway:
  boto_vpc.internet_gateway_present:
    - name: something-dev-{{ region }}-gateway
    - vpc_name: something-dev-{{ region }}-vpc
    - region: {{ aws_reg }}

something-dev-{{ region }}-ssh:
  boto_secgroup.present:
    - vpc_name: something-dev-{{ region }}-vpc
    - name: something-dev-ssh
    - region: {{ aws_reg }}
    - description: ssh access for the world
    - rules:
      - ip_protocol: tcp
        from_port: 22
        to_port: 22
        cidr_ip:
          - 0.0.0.0/0

something-dev-{{ region }}-routingtable:
  boto_vpc.route_table_present:
    - name: something-dev-{{ region }}-routingtable
    - vpc_name: something-dev-{{ region }}-vpc
    - routes:
      - destination_cidr_block: 0.0.0.0/0
        internet_gateway_name: something-dev-{{ region }}-gateway
    - subnet_names:
      - something-dev-{{ region }}-subnet

{% endfor %}
```

### Versions Report

```
Salt Version:
           Salt: 2015.8.10
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-66-generic
         system: Ubuntu 14.04 trusty
```
