### ISSUE TITLE
Salt pillar returning multiple namespace from pillar while using git

### ISSUE THREAD

**Issue by abhi2207** [saltstack/salt#33820]
### Description of Issue/Question
We have setup salt to pull pillar and state data from git as below

```
git_pillar_provider: pygit2
git_pillar_pubkey: /root/.ssh/id_rsa.pub
git_pillar_privkey: /root/.ssh/id_rsa

ext_pillar:
  - git: master git@GitLab02.source.com:BigData/salt_pillars.git
  - git: prod git@GitLab02.source.com:BigData/salt_pillars.git
  - git: integration git@GitLab02.source.com:BigData/salt_pillars.git
  - git: dev git@GitLab02.source.com:BigData/salt_pillars.git
```

Our salt pillar for valid groups is as below:

```
valid_groups.sls
valid_groups: 
  - prod
  - qa 
  - hdpdev
  - business
```

And we are calling this pillar in master branch only -> 

```
master:  top.sls
  'hdp01.dev.hadoop.com':
    - valid_groups
```

When we run salt pillar.items we receive the below output

```
valid_groups:
        - prod
        - qa
        - hdpdev
        - business
        - prod
        - qa
        - hdpdev
        - business
        - prod
        - qa
        - hdpdev
        - business
        - prod
        - qa
        - hdpdev
        - business
```

This issue gets repeated for all other pillars as well where we put list in pillar.
Since we have multiple items listed above it results in same namespace issue in salt state.
Below is salt state we were planning to run to create the groups mentioned in pillar.
Is this something wrong in setup or definition of pillar?

```
{% for group_name in pillar['valid_groups'] %}

create_group_{{ group_name }}:
  group.present:
    - name: {{ group_name }}

{% endfor %}
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
Nothing in logs which stands out.

### Versions Report

```
[root@salt master]# salt --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```
