### ISSUE TITLE
user.present does not report expiration changes

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#33845]
### Description of Issue

If I change the value of the `expire` parameter, `user.present` does not report any changes even though it successfully updates the value of the `expire` field in the shadow database.

### Setup

File `users.sls`:
```
foo:
  user.present:
    - password: '$6$o1LtwaH.ofLR8eat$p8qISh4/KfEGb5/iK2VoTkaVLMP16YzjjMyYbxo5z.gjRrPenHjgREM3oweSybnl7PR7Tc6LvUI.ySosI2yKn.'
    - fullname: Firstname Lastname
    - shell: /bin/bash
    - expire: -1
    - home: /home/foo
    - uid: 1234
    - gid: 1234
```

### Steps to Reproduce Issue

  1. copy the above `users.sls` state file to the `file_roots` directory
  2. run `salt minion state.apply users` to create the `foo` user
  3. run `salt minion shadow.info foo` and verify that `expire` is `-1`
  4. edit `users.sls` and change `expire: -1` to `expire: 1`
  5. run `salt minion state.apply users` to update the expiration for the `foo` account
  6. notice that `salt` doesn't report any changes
  7. run `salt minion shadow.info foo` and verify that `expire` was indeed changed to `1` despite `state.apply` not reporting any changes

### Versions Report

```
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.22.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.22.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-22-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

Minion is the same system as the master.
