### ISSUE TITLE
salt-cloud should auto-detect and set the transport

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#33842]
### Description of Issue/Question

When using a non-default transport (tcp in our case), salt-cloud's minions fail to connect. This is because salt-cloud has not configured the transport.
### Setup

Configure salt-master with tcp or raet transport.
### Steps to Reproduce Issue

salt-cloud -p my_profile my_minion_id

Note they fail to connect.
### Workaround

Manually configure the transport by adding:

``` yaml
minion:
  transport: tcp
```

To your cloud config.
### Versions Report

```
ahammond@salt:~ $ sudo salt-call --local test.versions_report
local:
    Salt Version:
               Salt: 2016.3.0

    Dependency Versions:
               cffi: 1.2.1
           cherrypy: 3.2.2
           dateutil: 1.4.1
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: 1.3.8
             Jinja2: 2.2.1
            libgit2: Not Installed
            libnacl: 1.4.3
           M2Crypto: 0.20.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
               RAET: 0.6.3
              smmap: 0.8.1
            timelib: 0.2.4
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: centos 6.7 Final
            machine: x86_64
            release: 2.6.32-573.3.1.el6.x86_64
             system: Linux
            version: CentOS 6.7 Final
```

**Comment by Ch3LL** [comment]
@ahammond I am not able to replicate this. If I have a master that is using `transport: tcp` in its configuration and the following cloud profile:

```
[root@ip-10-81-165-250 ~]# cat /etc/salt/cloud.profiles.d/linode.conf 
linode_cent6:
  provider: linode
  size: Linode 2048
  image: CentOS 6.5
  minion:
    master: mastername
    transport: tcp
```

When running `salt-cloud -p linode_cent6 test_cent6` it installs salt and i am able to run a test.ping from the master once completed. Am I misunderstanding? Any other information to help me replicate?
