### ISSUE TITLE
Two level watch dependencies absent in test=true output

### ISSUE THREAD

**Issue by mallniya** [saltstack/salt#33856]
### Description of Issue/Question

Assume we have 2 services and 1 config file for the first service. Also imagine, that second service must be restarted after first services has been restarted. And also suppose we testing `state.apply` with `test=true` option before we actually `state.apply`. In the first case there will be no output about second service at all (which is not nice, because I want to see any changes when running `state.apply` with `test=true`). Second case will bring us output about (surprise-surprise) restarted second service alongside restarting first service and changed config. I assume it's not suppose to happen.
### Setup

```
rsyslogd-running:
  service.running:
    - watch:
      - file: /etc/syslog.conf

/etc/syslog.conf:
  file.managed:
    - source: /etc/syslog.conf

uwsgi-predictor:
  service.running:
    - watch:
      - service: rsyslogd-running
```
### Steps to Reproduce Issue

Change /etc/syslog.conf and naturally we can see, that rsyslogd will be restarted after we run `state.apply test=true`, but there is no info, that uwsgi-predictor will be restarted. Run `state.apply` alone -- and besides changes of /etc/syslog.conf and restarting rsyslogd we suddenly see restarting of uwsgi-predictor.
### Versions Report

```
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.7.9 (default, Apr 27 2015, 11:42:05)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:   
        machine: amd64
        release: 10.2-STABLE-r286912
```
