### ISSUE TITLE
Fix creation of docker data containers in dockerng

### ISSUE THREAD

**Issue by mikee** [saltstack/salt#33885]
### Setup

This is the closest you can get right now - but it still starts the container on first create (even though start is set to false).  

```
redisdata:
  dockerng.running:
    - image: redis
    - start: False
    - volumes:
      - /data
```

If create was updated from `if new_container or (pre_state != 'running' and start):` 
to `if (new_container and start) or (pre_state != 'running' and start):`
then the container would be created, but not started - then you have a data container create option.
