### ISSUE TITLE
sls step does not wait for file to be created

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#33894]
### Description of Issue/Question

I need a deamon to be started so it creates its config file, then modify the file

but the file seem not to be created on time for the next file.replace step

I tried onchanges, I tried running the service with the service module but still the same problem
I am not sure it's a bug or something I do wrong
### Setup

```
false_start_to_create_config:
  module.run:
    - name: service.start 
    - m_name: syncthing
{#  cmd.run:
    - name: /etc/init.d/syncthing start #}

/home/synchronizer/.config/syncthing/config.xml:
  file.replace:
    - onchanges:
      - false_start_to_create_config
    - name: /home/synchronizer/.config/syncthing/config.xml
    - pattern: '<address>127.0.0.1:8384</address>' 
    - repl: '<address>0.0.0.0:8384</address>' 
    - count: 1
    - backup: False
    - show_changes: True
    - require: 
      - false_start_to_create_config
```
### Steps to Reproduce Issue

```
salt host state.apply

....
----------
          ID: /home/synchronizer/.config/syncthing/config.xml
    Function: file.replace
      Result: False
     Comment: /home/synchronizer/.config/syncthing/config.xml: file not found
     Started: 09:33:27.829046
    Duration: 1.165 ms
     Changes:   
----------
          ID: real_start_to_create_config
    Function: cmd.run
        Name: /etc/init.d/syncthing restart
      Result: False
     Comment: One or more requisite failed: syncthing./home/synchronizer/.config/syncthing/config.xml
     Started: 
    Duration: 
     Changes:   
```
### Versions Report

```
Salt Version:
Salt: 2016.3.0

Dependency Versions:
cffi: 0.8.6
cherrypy: Not Installed
dateutil: 2.4.2
gitdb: 0.6.4
gitpython: 2.0.2
ioflo: Not Installed
Jinja2: 2.8
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.4.7
mysql-python: 1.3.7
pycparser: 2.14
pycrypto: 2.6.1
pygit2: Not Installed
Python: 2.7.11+ (default, Jun 2 2016, 19:34:15)
python-gnupg: Not Installed
PyYAML: 3.11
PyZMQ: 15.2.0
RAET: Not Installed
smmap: 0.9.0
timelib: Not Installed
Tornado: 4.2
ZMQ: 4.1.4

System Versions:
dist: debian stretch/sid
machine: x86_64
release: 3.16.0-4-amd64
system: Linux
version: debian stretch/sid
```

**Comment by Ch3LL** [comment]
@phil123456 is there a reason why you are calling the service execution module instead of the state module. What happens if you try this:

```
false_start_to_create_config:
  service.running:
    - name: syncthing
{#  cmd.run:
    - name: /etc/init.d/syncthing start #}

/tmp/test-33894:
  file.replace:
    - name: /tmp/test-33894
    - pattern: '<address>127.0.0.1:8384</address>'
    - repl: '<address>0.0.0.0:8384</address>'
    - count: 1
    - backup: False
    - show_changes: True
    - require:
      - false_start_to_create_config
    - onchanges:
      - false_start_to_create_config
```

If that still does not work it might mean that the service just takes a while to create a file on startup and salt returns true once the service is restarted I dont believe it waits for post startup tasks.  One way you could work around this is just to call a sleep command in between the two states. I'm sure there are other ways to approach this but i'm can't think of a more elegant approach right now.
