### ISSUE TITLE
Provide command parameter to cron state module

### ISSUE THREAD

**Issue by madduck** [saltstack/salt#3393]
Currently, if I instruct cron to run a command, the name of the state function becomes the full command, e.g.

```
update-stuff:
  cron.present:
    name: 'ENV=VARIABLE command/I/want/to/run --with-long-options | and shell-escapes && potentially very long'
    […]
```

which would yield in e.g. highstate output:

```
Name: ENV=VARIABLE command/I/want/to/run --with-long-options | and shell-escapes && potentially very long — Function: present — Result: True
```

I would appreciate if instead I could say:

```
update-stuff:
  cron.present:
    command: 'ENV=VARIABLE command/I/want/to/run --with-long-options | and shell-escapes && potentially very long'
    […]
```

and get

```
Name: update-stuff — Function: present — Result: True
```
