### ISSUE TITLE
FreeBSD 2016.3.0 - SaltInvocationError: No authentication credentials found when attempting to make boto asg connection to region "us-east-1".

### ISSUE THREAD

**Issue by nbari** [saltstack/salt#33931]
### Description of Issue/Question

While using salt to manage autoscaling groups or launch configurations, is now returning this error:

```
SaltInvocationError: No authentication credentials found when attempting to make boto asg connection to region "us-east-1".
```

```

----------
          ID: Autoscaling for buildbot_master
    Function: boto_asg.present
        Name: buildbot_master
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1703, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1649, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/states/boto_asg.py", line 461, in present
                  lc_ret = __states__['boto_lc.present'](**args)
                File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1649, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/states/boto_lc.py", line 247, in present
                  region, key, keyid, profile)
                File "/usr/local/lib/python2.7/site-packages/salt/modules/boto_asg.py", line 506, in create_launch_configuration
                  conn = _get_conn(region=region, key=key, keyid=keyid, profile=profile)
                File "/usr/local/lib/python2.7/site-packages/salt/utils/boto.py", line 193, in get_connection
                  'region "{1}".'.format(service, region))
              SaltInvocationError: No authentication credentials found when attempting to make boto asg connection to region "us-east-1".
     Started: 12:05:43.216611
    Duration: 114.889 ms
     Changes:   

```

Issue happening only in FreeBSD, in Linux seems to be working.
### Setup

Working on version < `2016.3.0` but not in `2016.3.0`

```
LC-buildbot_master:
  boto_lc.present:
    - profile: aws_vpc_profile
    - region: eu-west-1
    - security_groups:
      - sg-0ee65c69
    - instance_type: t2.micro
    - image_id: ami-c434a9b7
    - block_device_mappings:
        - '/dev/sda1':
            size: 10
            delete_on_termination: true
```
### Steps to Reproduce Issue

Update to `2016.3.0`
### Versions Report

```
> salt --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Jun  5 2016, 01:18:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:   
        machine: amd64
        release: 10.3-STABLE
         system: FreeBSD
```

**Comment by Ch3LL** [comment]
@nbari would you  mind sharing your sanitized version of your configuration file?

**Comment by nbari** [comment]
This is the pillar:

    aws_vpc_profile:
        keyid: ABC
        key: ABC
        region: eu-west-1 


The state I am trying is something like:

```
Autoscaling for buildbot_master:
  boto_asg.present:
    - name: buildbot_master
    - profile: aws_vpc_profile
    - launch_config_name: buildbot_master
    - launch_config:
      - key_name: VPC
      - region: eu-west-1
      - security_groups:
        - sg-0ee65c79
      - instance_type: t2.micro
      - image_id: ami-6dc9561e
      - block_device_mappings:
          - '/dev/sda1':
              size: 10
              delete_on_termination: true
    - availability_zones:
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
    - min_size: 1
    - max_size: 1
    - vpc_zone_identifier:
        - subnet-fb64ce9f
        - subnet-0e449b78
        - subnet-c909e291
    - health_check_period: 60
    - termination_policies:
      - NewestInstance
    - tags:
      - key: 'Name'
        value: 'Test'
        propagate_at_launch: true
      - key: 'Salt'
        value: 'buildbot_master'
        propagate_at_launch: true
```

What I have notice is that If I create an  ``/root/.aws/credentials`` file, **boto** reads the file and use does credentials, but doesn't get the region.

For an unknown reason the pillar data or even when passing directly the the``key``,``keyid``, ``region`` keys/values on the state, they are simple ignored.

Maybe this can help to reproduce the issue:

Starting with a clean new FreeBSD 10.3 instance, and install salt using the saltstack repo: https://docs.saltstack.com/en/latest/topics/installation/freebsd.html

pkg install python  py27-salt py27-boto ca_root_nss

The config of my salt master:

```
worker_threads: 10

keep_jobs: 1

file_roots:
  base:
    - /salt/states

pillar_roots:
  base:
    - /salt/pillars

fileserver_backend:
  - roots

hash_type: sha256

file_ignore_glob:
  - '*.pyc'
  - '*.bak'
  - '*.swp'
  - '*.txt'

auto_accept: True

log_level: info
```

Any ideas ?

**Comment by nbari** [comment]
I have found that adding the **region** and the **key** in the minion config ``/usr/local/etc/minion`` helps:

    asg.keyid: GKTADJGHEIQSXMKKRBJ08H
    asg.key: askdjghsdfjkghWupUjasdflkdfklgjsdfjajkghs
    asg.region: eu-west-1

Doing so the ``LC``, is created but later the pillar is used to create the Autoscaling group, so for now I am duplicating  the keys in the minion config file and in the pillar as a workaround.

**Comment by robruma** [comment]
Thanks @nbari I'm experiencing nearly the same situation although with Amazon Linux AMI 2016.03. The same workaround is in place and working.

```
# salt --versions-report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Dec 17 2015, 01:08:55)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.4.11-23.53.amzn1.x86_64
         system: Linux
        version: Not Installed
```
