### ISSUE TITLE
zypper.py refresh_db() IndexError

### ISSUE THREAD

**Issue by llua** [saltstack/salt#33963]
### Description of Issue/Question
When you have an repository that has a gpg key near it's expiration date, zypper prints a warning like the following
```
The gpg key signing file 'repomd.xml' will expire in 13 days.
 Repository:       monitoring
 Key Name:         server:monitoring OBS Project <server:monitoring@build.opensuse.org>
 Key Fingerprint:  8F3BC8EF F549CDCD A918D981 A5C23697 EE454F98
 Key Created:      Fri 18 Apr 2014 12:35:12 PM EDT
 Key Expires:      Sun 26 Jun 2016 12:35:12 PM EDT (expires in 13 days)
 Rpm Name:         gpg-pubkey-ee454f98-53515440

```

Line 702 in zypper.py notices the word Repository and tries to split based on a character that isn't in the line.

### Setup
On the minion:
```
zypper ar 'http://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_42.1/server:monitoring.repo'
```

### Steps to Reproduce Issue
salt minion pkg.upgrade
```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1071, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/zypper.py", line 893, in upgrade
        refresh_db()
      File "/usr/lib/python2.7/site-packages/salt/modules/zypper.py", line 703, in refresh_db
        key = line.split('\'')[1].strip()
    IndexError: list index out of range

```
### Versions Report
master:
```
# salt --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Apr 30 2016, 01:24:26)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: amd64
        release: 10.2-RELEASE-p9
```
minion
```
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: 2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.22.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.22.0
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: SuSE 42.1 x86_64
        machine: x86_64
        release: 4.1.13-5-default
         system: openSUSE  42.1 x86_64
```
