### ISSUE TITLE
rsync module support for --files-from option

### ISSUE THREAD

**Issue by do3meli** [saltstack/salt#33967]
### Description of Feature Request

we would love to see support for the `--files-from` option in the rsync salt module/state. this would allow us to easily upgrade certain software that runs in a FreeBSD jail once the software has been installed on the FreeBSD base.

the `--files-from` option has the following short rsync man page entry:

```
            --files-from=FILE       read list of source-file names from FILE
```

a longer man page description is also available. you can found it here for example: http://linuxcommand.org/man_pages/rsync1.html
### Setup Idea

a possible sls file for such a feature could may look like this:

```
my_special_rsync_copy:
  rsync.synchronized:
    - name: /opt/user-backups
    - source: /home
    - sourcelistfile: salt://{{ slspath }}/a_file_with_a_list_of_files_to_copy.jinja
```
