### ISSUE TITLE
Salt minion polling master

### ISSUE THREAD

**Issue by davidpsv17** [saltstack/salt#33974]
Hi!
I'm trying to execute the scheduler from the minion to execute a state in the master. I added in /etc/salt/minion.d/schedule.conf this config:

```
job1:
  schedule.present:
    - function: state.sls
    - job_args:
      - update2
      - 'env=nacl'
    - seconds: 60
```

This is the via to do this?  Can anyone help me please?

Thanks!!
