### ISSUE TITLE
file.append failure with file containing some type of unicode characters

### ISSUE THREAD

**Issue by seamus-45** [saltstack/salt#34001]
### Description of Issue/Question
I'm not sure if I correctly determined the cause, but when I run `file.append` on a particular file then I get the following output:
```yaml
ID: /tmp/mate-screenshot.desktop
Function: file.append
Result: False
Comment: No text found to append. Nothing appended
```
Nothing interesting in debug logs.
May be duplicated #24820

### Setup
/srv/salt/test.sls:
```yaml
/tmp/mate-screenshot.desktop:
  file.append:
    - text: Test
```

[Paste of /tmp/mate-screenshot.desktop](http://pastebin.calculate-linux.ru/en/show/12385)

##### Salt Version:
Name | Version
------ | -------
Salt | 2015.8.8

##### Dependency Versions:
Name | Version
--- | ---
         Jinja2| 2.8
       M2Crypto| 0.21.1
           Mako| Not Installed
         PyYAML| 3.11
          PyZMQ| 15.2.0
         Python| 2.7.11+ (default, Apr 17 2016, 14:00:29)
           RAET| Not Installed
        Tornado| 4.3
            ZMQ| 4.1.4
           cffi| Not Installed
       cherrypy| 5.4.0
       dateutil| 2.4.2
          gitdb| 0.6.4
      gitpython| 1.0.1
          ioflo| Not Installed
        libgit2| Not Installed
        libnacl| Not Installed
   msgpack-pure| Not Installed
 msgpack-python| 0.4.6
   mysql-python| Not Installed
      pycparser| Not Installed
       pycrypto| 2.6.1
         pygit2| Not Installed
   python-gnupg| Not Installed
          smmap| 0.9.0
        timelib| Not Installed

##### System Versions:
Name | Version
--- | ---
           dist| Ubuntu 16.04 xenial
        machine| x86_64
        release| 4.4.0-22-generic
         system| Ubuntu 16.04 xenial
