### ISSUE TITLE
test=True reports failure when using file.append or similar functions

### ISSUE THREAD

**Issue by rmohta** [saltstack/salt#34019]
### Description of Issue/Question

Handling of file.append and required can be improved when using 'test=True' mode. When executing the state file with test=True, there are numerous errors compared to zero error for an actual execution.
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Gist of a State file:

```
md5check_create:
  file.touch:
    - name: /home/{{ grains['id'] }}/jars.md5check

{% for key,jar in pillar['jars'].iteritems() %}
/home/{{ grains['id'] }}/{{ jar['directory'] }}/{{ jar['name'] }}-{{ jar['version'] }}.jar:
  cmd.run:
    - name: curl https://somestite/nexus/content/groups/prod/{{ jar['group']|replace('.', '/') }}/{{ jar['name'] }}/{{ jar['version'] }}/{{ jar['name'] }}-{{ jar['version'] }}.jar -H 'Authorization:Basic base64encoded' -o {{ jar['name'] }}-{{ jar['version'] }}.jar && echo {{ jar['md5'] }}
    - timeout: 30
    - cwd: /home/{{ grains['id'] }}/{{ jar['directory'] }}
    - runas: {{ grains['id'] }}
    - umask: 027

/home/{{ grains['id'] }}/{{ jar['directory'] }}/{{ jar['name'] }}-{{ jar['version'] }}.jar.md5:
  file.append:
    - name: /home/{{ grains['id'] }}/jars.md5check
    - require:
      - file: md5check_create
    - text: {{ jar['md5'] }}  /home/{{ grains['id'] }}/{{ jar['directory'] }}/{{ jar['name'] }}-{{ jar['version'] }}.jar

{% endfor %}

```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

**salt-ssh '_server_' --priv ~/.ssh/id_rsa state.sls somestate.withappend test=True**

Logs for test=True

```
----------
          ID: md5check_create
    Function: file.touch
        Name: /home/logged_user/jars.md5check
      Result: None
     Comment: File /home/logged_user/jars.md5check is set to be created
     Started: 21:37:57.324200
    Duration: 0.365 ms
     Changes:
----------
          ID: /home/logged_user/runtime/lib/artifact-1.0.10.1.jar
    Function: cmd.run
        Name: curl https://somesite/nexus/content/groups/prod/group/artifact/1.0.10.1/artifact-1.0.10.1.jar -H 'Authorization:Basic base64encoded' -o artifact-1.0.10.1.jar && echo md5checksumvalue
      Result: None
     Comment: Command "curl https://somesite/nexus/content/groups/prod/group/artifact/1.0.10.1/artifact-1.0.10.1.jar -H 'Authorization:Basic base64encoded' -o artifact-1.0.10.1.jar && echo md5checksumvalue" would have been executed
     Started: 21:37:57.326817
    Duration: 0.452 ms
     Changes:
----------
          ID: /home/logged_user/runtime/lib/artifact-1.0.10.1.jar.md5
    Function: file.append
        Name: /home/logged_user/jars.md5check
      Result: False
     Comment: /home/logged_user/jars.md5check: file not found
     Started: 21:37:57.331353
    Duration: 0.468 ms
     Changes:
----------

```

I would hope if we could give a bit more clear error message to user.  For example, the above comment could say: as executing in test mode, /home/logged_user/jars.md5check: file was not actually created.

And then in future versions, if we could mock the output of supported commands. Or atleast mention, command will not show accurate result when running in test mode.
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
         Salt: 2015.5.2
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
         Jinja2: unknown
       M2Crypto: 0.21.1
 msgpack-python: 0.1.12
   msgpack-pure: Not Installed
       pycrypto: 2.3
        libnacl: Not Installed
         PyYAML: 3.08
          ioflo: Not Installed
          PyZMQ: 2.1.9
           RAET: Not Installed
            ZMQ: 2.1.9
           Mako: Not Installed

```

We **use salt-ssh** to execute commands.
