### ISSUE TITLE
states.cmd command "run" does not accept password parameter

### ISSUE THREAD

**Issue by Akvalangs** [saltstack/salt#34029]
### Description of Issue/Question

Executing powershell command using state "cmd" does not accept parameter "password". Error message: "password is a required argument for runas on Windows".
### Setup

```
Blablabla:
  cmd.run:
    - name: Clear-Host
    - shell: powershell
    - runas: [domain]\[user]
    - password: [password]
```
### Steps to Reproduce Issue

Excute state on Windows Server (standalone minion) by command: C:\salt>salt-call.bat --local state.apply
### Versions Report

```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```

**Comment by Ch3LL** [comment]
@Akvalangs looks like this is a duplicate of #33676 and it also looks like it has been fixed and is included in 2016.3.1. Can you upgrade to 2016.3.1 and give that a try and report back whether you are still seeing the behavior? Thanks!

**Comment by lew-huiying** [comment]
I'm having the same problem with cmd.run. I've tried it both as a custom module that calls cmd.run and using the cmd.run state. 

### Error message:
```
    Function: cmd.run
      Result: False
     Comment: password is a required argument for runas on Windows
     Started: 03:14:31.279000
    Duration: 0.0 ms
     Changes:
```

### product.sls:
```
AddLink:
  module.run:
    - name: cmd.run
    - cmd: 'cp //server10/c$/www/AddLinkData/AddLinkCleaner.exe C:/www/AddLinkData/'
    - runas: 'WEB\\
    - password: '{{ salt['pillar.get']('blah:blah') }}'
    

'cp //server10/c$/www/AddLinkData/AddLinkCleaner.exe C:/www/AddLinkData/':
  cmd.run:
    - runas: 'WEB\\phoebe'
    - kwargs: {
      password: '{{ salt['pillar.get']('passwords:phoebe') }}'
    }
```

### Reproduce issue:
Execute state on windows minion: salt 'winServer' state.apply product

### Version
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-21-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```
