### ISSUE TITLE
nodegroup issue between slaves v 2015.5.10 and master > 2015.8.0

### ISSUE THREAD

**Issue by DeanScothern** [saltstack/salt#34034]
Hi,

I'm trying to update salt in stages, first the master and then minions in blocks

The problem I'm getting is similar to issue #27219

With a minion running 2015.5.10 and master running > 2015.8.0 
If I specify a compound target in nodegroups the minion doesn't reply.

Example config:

```
nodegroups:
 group1: 'L@node1'
 group3: 'G@os:Centos and N@group1'
```

I also tried an or with two nodegroups.

Example test:

```
salt -N group3   test.ping
jid: 20160615145657757972
node1:
    Minion did not return. [No response]
```

minion debug log:
`2016-06-15 15:04:06,735 [salt.minion      ][DEBUG   ][19681] Compound target received that is not a string`

Versions:

```
master:
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core

minion:
salt -N group1 grains.get saltversion
jid: 20160615151152681591
node1:
    2015.5.10
```
