### ISSUE TITLE
states.cmd command "run" with multiline "name" + parameters "runas" and "password" does not allow double quotes in powershell command

### ISSUE THREAD

**Issue by Akvalangs** [saltstack/salt#34054]
### Description of Issue/Question
Executing powershell command with double quotes in combination with state "cmd" multiline "name" + parameters "runas" and "password" gives an error:

          ID: Clear-Host
    Function: cmd.run
        Name: Clear-Host; Write-Host "hello salt"

      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1723, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1650, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\cmd.py", line 841, in run
                  name, timeout=timeout, python_shell=True, **cmd_kwargs
                File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 1611, in run_all
                  password=kwargs.get('password', None))
                File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 316, in _run
                  cmd = salt.utils.shlex_split(cmd, posix=False)
                File "C:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 2925, in shlex_split
                  return shlex.split(s, **kwargs)
                File "C:\salt\bin\lib\shlex.py", line 279, in split
                  return list(lex)
                File "C:\salt\bin\lib\shlex.py", line 269, in next
                  token = self.get_token()
                File "C:\salt\bin\lib\shlex.py", line 96, in get_token
                  raw = self.read_token()
                File "C:\salt\bin\lib\shlex.py", line 172, in read_token
                  raise ValueError, "No closing quotation"
              ValueError: No closing quotation
     Started: 08:34:08.608000
    Duration: 56.0 ms
     Changes:
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue

```
Working-Example:
  cmd.run:
    - name: >
        Clear-Host;
        Write-Host "hello salt"
```

```
Buggy-Example-Watchout-Double-Quotes-In-Powershell-Command:
  cmd.run:
    - name: >
        Clear-Host;
        Write-Host "hello salt"
    - shell: powershell
    - runas: [domain]\[user]
    - password: [password]
```

```
Working-Example-Single-Quotes-In-Powershell-Command:
  cmd.run:
    - name: >
        Clear-Host;
        Write-Host 'hello salt'
    - shell: powershell
    - runas: [domain]\[user]
    - password: [password]
```

### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```
