### ISSUE TITLE
Issues with docker-py and Ubuntu 14.04

### ISSUE THREAD

**Issue by sdemura** [saltstack/salt#34065]
### Description of Issue/Question

I have been trying to get `docker-py` in order to use `dockerng` modules and states, but I have run into many issues. This is a summary of what I have found.
### Setup
1. Salt 2015.8.10, 2016.3.0, 2016.3.1
2. Ubuntu 14.04
3. Docker-py 1.7.2/1.8.1
4. Docker 1.11.2
### Steps to Reproduce Issue

The salt minion requires `docker-py` python module in order to manage docker containers. This should be as simple as running:

```
python-pip:
  pkg.installed: []

docker-py: 
  pip.installed:    
    - name: docker-py>=1.4.0 # installs 1.8.1 by default
    - reload_modules: True
    - require:
      - pkg: python-pip
```

This works on CentOS 7 and Debian Jessie without problem. On Ubuntu 14.04, the state is successful, but once I go to spin up a container with `dockerng`, I get module import errors. 

Based on suggetion here: https://github.com/saltstack/salt/issues/28036 and https://github.com/saltstack/salt/issues/26115#issuecomment-143920045

I have created a workaround for Ubuntu 14.04 like so:

```
python-pip:
  pkg.purged: []

python-setuptools:
  pkg.installed: []
  - require:
    - pkg: python-pip

pip-install:
  cmd.run:
    - name: easy_install pip
    - require:
      - pkg: python-setuptools

docker-py:
  cmd.run:
    - name: pip install docker-py==1.7.2
    - reload_modules: True
    - require:
      - cmd: pip-install
```

It is also worth noting that docker-py **1.8.1 does not work on** Ubuntu 14.04 using my workaround:

Using 1.8.1:

```
----------
          ID: registry
    Function: dockerng.running
      Result: False
     Comment: State 'dockerng.running' was not found in SLS 'docker.registry'
              Reason: 'dockerng' __virtual__ returned False: 'dockerng' __virtual__ returned False: Docker module could not get imported
     Started:
    Duration:
     Changes:
```
### Versions Report

Minions + master:

```
root@saltminion1:~# salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-87-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@sdemura I believe the pip issue is an upstream issue. 

For the docker 1.8.1 issue I am able to replicate this issue and I'm seeing this error in the minion debug logs:

`AttributeError: 'module' object has no attribute 'connection'`

Are you seeing the same error?

**Comment by Deshke** [comment]
docker-py is more or less always out of date and half the time not working, i switched to docker-compose as a wrapper and that's working

**Comment by adilr00t** [comment]
I confirm, having the same issue on ubuntu 14.04

But on debian 8 is working without any problem.

I have two minions, one Debian8 and one Ubntu 14.04, the same sls is working fine on Debian but it failed on Ubuntu

**Comment by omegarus** [comment]
Updating python-urllib3 package to 1.15.1 on Ubuntu 14.04 helped me to overcome this issue.

**Comment by adilr00t** [comment]
I have updated python-urllib3 package to 1.15.1 but unfortunately couldn't fix the issue, I'm still getting the following error:

```
----------
          ID: redis:3.2-alpine
    Function: dockerng.image_present
      Result: False
     Comment: State 'dockerng.image_present' was not found in SLS 'sentry-v88'
              Reason: 'dockerng' __virtual__ returned False: 'dockerng' __virtual__ returned False: Docker module could not get imported
     Started: 
    Duration: 
     Changes:   
```

**Comment by adilr00t** [comment]
it's working for me after using this formula https://github.com/saltstack-formulas/docker-formula to install docker.

but I'm not sure what is the root cause of the issue

**Comment by omegarus** [comment]
@adilr00t I did deb package update not npm.

**Comment by fxdgear** [comment]
+1 to this issue. 

I have docker-py installed. 

ssh-ing into the minion I can run the following:
```
$ sudo python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from docker import Client
>>> cli = Client(base_url='unix://var/run/docker.sock')
>>> cli.images()
[{u'Created': 1474642111, u'Labels': 
```

versions:
```
$ pip freeze | grep docker
docker-py==1.10.3
docker-pycreds==0.2.1
```

versions-report
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-96-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

and I am using Docker CS engine 1.12

```
Client:
 Version:      1.12.1-cs1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   e7f4338
 Built:        Wed Sep 21 21:05:28 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1-cs1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   e7f4338
 Built:        Wed Sep 21 21:05:28 2016
 OS/Arch:      linux/amd64
```

**Comment by fxdgear** [comment]
Note: when i manually ran `sudo pip install --upgrade pip` then ran `sudo salt-call state.highstate` things ran fine. 

SO to clarify using 
```
python-pip:
  pkg.installed
```
is not sufficent. 

it MUST be the pip installed version of pip, not the apt version

Also the error message coming back to the master when running `salt '*' state.highstate` is different than the message coming from the minion when running `salt-call state.highstate`

**Comment by fxdgear** [comment]
Also note that running, from the minion, `salt-call state.highstate` works.

when running `salt '*' state.highstate` still does not work.

**Comment by fxdgear** [comment]
*update*: restarting the salt-minion is also required. 

After installing pip from pip and installing docker-py the minion needs to be restarted then my salt-states work as expected. 

this seems like broken behavior.

**Comment by sdemura** [comment]
Agree with @fxdgear.  Having to restart the salt-minion is required, and that's definitely not desirable.

**Comment by alem0lars-yoroi** [comment]
Are there any news on that ?

**Comment by Jenpatrick** [comment]
Also would like some news.  Running Ubuntu 16.04.2 and Salt 2016.11.3 and still getting this error when trying to run:

```
 sudo salt MYMINION  dockercompose.up /data/dockerfiles/
MUMINION:
    'dockercompose' __virtual__ returned False: The dockercompose execution module not loaded: compose python library not available.
```

And yet...
```
root@MYMINION:/data/dockerfiles# pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
backports.ssl-match-hostname (3.5.0.1)
cached-property (1.3.0)
chardet (2.3.0)
colorama (0.3.7)
cryptography (1.2.3)
docker (2.2.0)
docker-compose (1.11.2)
docker-pycreds (0.2.1)
dockerpty (0.4.1)
```

**Comment by konstest** [comment]
+1 
```
knikolaev@kos ~/PT/Docker/postgres $ pip freeze | grep docker
Could not parse requirement: -lxc
docker==2.5.1
docker-compose==1.16.1
docker-pycreds==0.2.1
dockerpty==0.4.1
knikolaev@kos ~/PT/Docker/postgres $ sudo salt-call dockercompose.get /home/knikolaev/PT/Docker/postgres
[ERROR   ] Failed to import module testinframod, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1333, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/testinframod.py", line 297, in <module>
    _register_functions()
  File "/usr/lib/python2.7/dist-packages/salt/modules/testinframod.py", line 288, in _register_functions
    for module_ in modules.__all__:
AttributeError: 'module' object has no attribute '__all__'
'dockercompose' __virtual__ returned False: The dockercompose execution module not loaded: compose python library not available.
knikolaev@kos ~/PT/Docker/postgres $ 
```
Debian jessie

**Comment by Ch3LL** [comment]
Has anyone tired the most recent salt version?

**Comment by jessebye** [comment]
@Ch3LL just ran into this. Latest Salt (2017.7.2) on master and minion. Minion is Ubuntu 14.04. Here is the output:
```
ID: opsgenie_pip_module
    Function: pip.installed
        Name: opsgenie-sdk
      Result: False
     Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
     Started: 22:22:51.609574
    Duration: 0.609 ms
     Changes:
```

On the minion:
```
jbye@xxxxxxx:~$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg (python 2.7)
```

**Comment by hemebond** [comment]
I'm able to reproduce this error reliably with the following:
```
# salt-call test.versions
local:
    Salt Version:
               Salt: 2017.7.7
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.2
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: debian 8.7 
             locale: UTF-8
            machine: x86_64
            release: 3.16.0-4-amd64
             system: Linux
            version: debian 8.7 

# salt-call pip.freeze
local:
    - backports.ssl-match-hostname==3.5.0.1
    - boto==2.34.0
    - chardet==3.0.4
    - colorama==0.3.2
    - croniter==0.3.4
    - docker-pycreds==0.3.0
    - futures==3.0.3
    - html5lib==0.999
    - idna==2.7
    - ipaddress==1.0.22
    - Jinja2==2.9.4
    - MarkupSafe==0.23
    - msgpack-python==0.4.2
    - MySQL-python==1.2.3
    - pip==18.0
    - psutil==2.1.1
    - pycrypto==2.6.1
    - pycurl==7.19.5
    - python-apt==0.9.3.12
    - python-dateutil==2.2
    - python-systemd==231
    - pytz==2012rc0
    - PyYAML==3.11
    - pyzmq==14.4.0
    - requests==2.19.1
    - salt==2017.7.7
    - setuptools==40.4.3
    - six==1.11.0
    - tornado==4.2.1
    - urllib3==1.23
    - websocket-client==0.53.0
    - wheel==0.24.0
```

## States
```
docker-repo:
  pkgrepo.managed:
    - name: deb https://apt.dockerproject.org/repo {{ grains["os"]|lower }}-{{ grains["oscodename"] }} main
    - humanname: {{ grains["os"] }} {{ grains["oscodename"]|capitalize }} Docker Package Repository
    - keyid: 58118E89F3A912897C070ADBF76221572C52609D
    - keyserver: hkp://p80.pool.sks-keyservers.net:80
    - refresh_db: True

docker-engine:
  pkg.installed:
    - require:
      - pkgrepo: docker-repo

docker:
  pip.installed:
    - reload_modules: True
    - force_reinstall: True
    - upgrade: True
    - require:
      - pkg: docker-engine

nginx:
  docker_container.running:
    - image: nginx:latest
    - require:
      - pip: docker
```

## Result
```
# salt-call state.apply testminion
[ERROR   ] Failed to import module dockermod, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1438, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 219, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 8, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 34, in <module>
    class APIError(requests.exceptions.HTTPError, DockerException):
AttributeError: 'module' object has no attribute 'exceptions'
[ERROR   ] State 'docker_container.running' was not found in SLS 'testminion'
Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.

local:
----------
          ID: docker-repo
    Function: pkgrepo.managed
        Name: deb https://apt.dockerproject.org/repo debian-jessie main
      Result: True
     Comment: Package repo 'deb https://apt.dockerproject.org/repo debian-jessie main' already configured
     Started: 21:41:48.441692
    Duration: 43.306 ms
     Changes:   
----------
          ID: docker-engine
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: docker-engine
     Started: 21:41:48.864323
    Duration: 8002.486 ms
     Changes:   
              ----------
              docker-engine:
                  ----------
                  new:
                      17.05.0~ce-0~debian-jessie
                  old:
----------
          ID: docker
    Function: pip.installed
      Result: True
     Comment: All packages were successfully installed
     Started: 21:41:57.524563
    Duration: 2198.257 ms
     Changes:   
              ----------
              docker==3.5.0:
                  Installed
----------
          ID: nginx
    Function: docker_container.running
      Result: False
     Comment: State 'docker_container.running' was not found in SLS 'testminion'
              Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.
     Changes:   
```

## Reset With
Removing `docker` and either `certifi` _or_ `idna` will cause the state to fail:
```
salt-call pip.uninstall certifi,docker && salt-call pkg.purge docker-engine && systemctl restart salt-minion
```
