### ISSUE TITLE
iptables.state doesn't handle mutliple match statements

### ISSUE THREAD

**Issue by Rumbles** [saltstack/salt#34060]
### Description of Issue/Question
When setting up an iptables rule you often need multiple match statements, and the order they appear in the resultant command is important.

### Setup
I have the following rule in salt, this has a match statement for connstate and a second for iprange, this produces the below command in which the order is incorrect (the resultant command shows a simple range which I could achieve with a source using CIDR notation, but in production I have a range which cannot easily be achieved with CIDR and would require 4 different rules to achieve, so range is important for me):
```
ssh input local:
    iptables.append:
        - table: filter
        - chain: INPUT
        - match: state
        - connstate: NEW
        - jump: ACCEPT
        - dport: 2219
        - proto: tcp
        - match: iprange
        - src-range: {{ pillar['iptables']['local'] }}
        - save: True
```
This gives:
```
/sbin/iptables --wait -t filter -A INPUT  -p tcp -m iprange -m state --state NEW --dport 2219 --src-range 10.10.10.1-10.10.11.254 --jump ACCEPT
```
The problem here is that -m iprange should be before --src-range not where it is.
I checked this by taking a similar rule which had the same issue and removed the first match/connstate part:
```
icmp input local:
    iptables.append:
        - table: filter
        - chain: INPUT
        - jump: ACCEPT
        - proto: icmp
        - match: iprange
        - src-range: {{ pillar['iptables']['local'] }}
        - save: True
```
This produces:
```
/sbin/iptables --wait -t filter -A INPUT  -p icmp -m iprange --src-range 10.10.10.1-10.10.11.254 --jump ACCEPT
```
This works as expected, I believe that using a single match will work fine, but when you have a second match it seems to go awry.

### Steps to Reproduce Issue
I believe this issue is known as when I mentioned it in the IRC channel I was told this was due to the way the iptables.module handles the request using build_rule

### Versions Report
```
$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```
```
$ salt-minion --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```
### Further query
In the mean time, is there any way to work around this issue? I was considering manually creating a rules.v4 file and applying that file with iptables-persistent, but if there is a way to make this work using the iptables.state method shown above I would appreciate someone letting me know!

Thanks

**Comment by lorengordon** [comment]
According to the docs and the code, `match` should accept a list. Rather than using multiple `match` keys (which doesn't work for any state), try it as a comma-separated string or as a yaml list.

```
ssh input local:
    iptables.append:
        - table: filter
        - chain: INPUT
        - match: state,iprange
        - connstate: NEW
        - jump: ACCEPT
        - dport: 2219
        - proto: tcp
        - src-range: {{ pillar['iptables']['local'] }}
        - save: True
```

OR

```
ssh input local:
    iptables.append:
        - table: filter
        - chain: INPUT
        - match: 
          - state
          - iprange
        - connstate: NEW
        - jump: ACCEPT
        - dport: 2219
        - proto: tcp
        - src-range: {{ pillar['iptables']['local'] }}
        - save: True
```

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.iptables.html
