### ISSUE TITLE
reactors with expr_form: list requires tgt to be an actual list, not a string,of,comma,separated,hosts

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#34070]
### Description of Issue/Question

Prior to 2016.3, we had a reactor which looked like this:

``` yaml
cloud_ipset_add_{{ minion_ip }}:
  local.ipset.add:
    - tgt: salt,depot
    - expr_form: list
    - arg:
      - our_servers
      - {{ minion_ip }}
```

Now, we need to do this:

``` yaml
cloud_ipset_add_{{ minion_ip }}:
  local.ipset.add:
    - tgt: 
        - salt
        - depot
    - expr_form: list
    - arg:
      - our_servers
      - {{ minion_ip }}
```

Note the change in tgt's datatype from string to list. Which is a minor change (and the new format is superior, IMHO), but breaks backwards compatibility.

I don't know if this is limited to reactors or also affects orchestrations, etc.
### Versions Report

``` bash
[root@salt ~]# salt-call --local test.versions
local:
    Salt Version:
               Salt: 2016.3.1

    Dependency Versions:
               cffi: 1.6.0
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.20.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
               RAET: Not Installed
              smmap: 0.8.1
            timelib: 0.2.4
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: centos 6.6 Final
            machine: x86_64
            release: 2.6.32-504.30.3.el6.x86_64
             system: Linux
            version: CentOS 6.6 Final
```

**Comment by Ch3LL** [comment]
@ahammond when you see this behavior are you seeing an error?

I am able to run this successfully:

```
➜  salt cat issues/34070.sls 
cloud_ipset_add_test:
  local.cmd.run:
    - tgt: ch3ll-minion01,ch3ll-master
    - expr_form: list
    - arg:
      - echo "test"
```

Can you try the simple test above and see if it works in your environment?
