### ISSUE TITLE
saltutil.sync_all fails when building AMI with packer, but works with manual tests

### ISSUE THREAD

**Issue by ketzacoatl** [saltstack/salt#34080]
### Description of Issue/Question

I have a bit of a heisenbug that is driving me bonkers, and I'm running out of ideas. I'd appreciate a review of the details and any insights you might have that could lead to the behavior I am seeing.

**this is on masterless** - I am running these operations with `salt-call --local ...`

### Setup

I am building AMIs for AWS with packer. I have a set of scripts which install and configure salt, then use `salt-call --local` to apply a bunch of formula. In the middle of these scripts, I run `salt-call --local saltutil.sync_all` to ensure later `state.sls` and `state.highstate` can use the custom modules/states included in the file_roots setup during bootstrap.

When that `sync_all` runs in the scripts, it fails to find and sync those custom modules/states:

```
...
    amazon-ebs: local:
    amazon-ebs: ----------
    amazon-ebs: beacons:
    amazon-ebs: grains:
    amazon-ebs: modules:
    amazon-ebs: output:
    amazon-ebs: renderers:
    amazon-ebs: returners:
    amazon-ebs: sdb:
    amazon-ebs: states:
    amazon-ebs: utils:
```

But when I run a simple script manually, it works fine:

```
root@ip-10-72-1-250:~# vim /tmp/scripts/test-sync-all.sh
root@ip-10-72-1-250:~# chmod +x !$
chmod +x /tmp/scripts/test-sync-all.sh
root@ip-10-72-1-250:~# cat !$
cat /tmp/scripts/test-sync-all.sh
#!/bin/sh

salt-call --local saltutil.sync_all
root@ip-10-72-1-250:~# !$
/tmp/scripts/test-sync-all.sh
...
local:
    ----------
    beacons:
    grains:
    modules:
        - modules.pip
    output:
    renderers:
    returners:
    sdb:
    states:
        - states.archive
        - states.pip_state
    utils:
```

Now, when on auto-pilot, Packer is actually running these scripts as `ubuntu` through `sudo`, so I wanted to be sure I did the exact same in my tests:

```
ubuntu@ip-10-72-1-250:~$ sudo -H -S sh '/tmp/scripts/test-sync-all.sh'
sudo: unable to resolve host ip-10-72-1-250
...
local:
    ----------
    beacons:
    grains:
    modules:
        - modules.pip
    output:
    renderers:
    returners:
    sdb:
    states:
        - states.archive
        - states.pip_state
    utils:
```

Taking that one step further, I ran that in the same way, but over SSH, and it still works. While I have packer in debug mode, I can even run the script that packer uploads, and see it work as expected.

Only when running the script with packer, `saltutil.sync_all` fails to find the custom modules and states to sync. I'm unable to find the difference between my successful tests and the way this fails, and I'd be grateful for any insights you may have.

### Versions Report

```
root@ip-10-72-1-250:~# salt-call --local --versions
           Salt: 2015.5.10
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.5
```
