### ISSUE TITLE
State 'schedule' in SLS 'kubernetes.common.schedule' is not formed as a list

### ISSUE THREAD

**Issue by developerinlondon** [saltstack/salt#34125]
When I try: 

``` schedule:
  highstate:
    function: state.highstate
    run_on_start: True
    minutes: 60
```

also when I add multiple schedule blocks it complains about conflicting ids. I am copying the exact same examples on the documentation above.

**Comment by Ch3LL** [comment]
@developerinlondon Can you try this sls file:

```
add_schedule:
  schedule.present:
    - function: state.highstate
    - run_on_start: True
    - minutes: 60
```

As shown above you need ot include `schedule.present` (i'm assuming thats the state module you are attempting to use), and you need to form the arguments as a list. There is some examples [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.schedule.html) 

Concerning the conflicting IDs you will need to make sure you name each schedule something else for example:

```
job1:
  schedule.present:
    - function: state.highstate
    - run_on_start: True
    - minutes: 60
job2:
  schedule.present:
    - function: test.ping
    - seconds: 15
    - splay:
        - start: 10
        - end: 20
```

As shown above the IDS are `job1` and `job2` although these are arbitrary and you can name them whichever is useful in your situation. Does this help to clarify the issue you are running into?
