### ISSUE TITLE
ext_pillar using consul as a provider return error log

### ISSUE THREAD

**Issue by ThomasPaq** [saltstack/salt#34158]
### Description of Issue
I used following setup on my saltmaster
```
my_consul_config:
  consul.host: 127.0.0.1
  consul.port: 8500

ext_pillar:
  - consul: my_consul_config root=salt-shared
```
but when I run pillar.items i get this in the log file
> Specified ext_pillar interface consul is unavailable

Can someone please advise?

### Versions Report
```
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Dec 17 2015, 01:08:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.4.11-23.53.amzn1.x86_64
         system: Linux
        version: Not Installed
```

I also installed the last version of python-consul on saltmaster and I have keys in salt-shared folder
