### ISSUE TITLE
Manage a file that is a template which comes from the minion

### ISSUE THREAD

**Issue by ajfisher** [saltstack/salt#34193]
### Description of Issue/Question

My situation is that I have several python (django) applications that will be managed by salt. There are some common config that exists across all of them however there are some project specific configs also.

What I would like to do is include a settings file in the project repository which is retrieved and installed by salt (I have this part working fine with various states). I should then be able to use the settings file as a jinja template which can then have the appropriate pillar data inserted into it.

Obviously I could put the settings file on the salt master and push it to the minion - that's what I'm currently doing - however I'd prefer to keep files for my projects resident in their own repos in this case and use this as a source for the master to populate.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Salt master (2015.5.3)

State pulls a private git repo to a folder eg: /var/www/project

Which has:

/var/www/project/settings.template

settings.template would be something like:

```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '{{ django.app_db_name }}',
        'USER': '{{ django.app_db_username }}',
        'PASSWORD': '{{ django.app_db_password }}',
    }
}
```

So I know this doesn't work but what I'd like to be able to do is something like this in a state file:

```yaml
django-settings:
   file.managed:
     - name: /var/www/{{project}}/{{ pillar["django"]["settings_file"] }}
     - source: [FILE REF ON MINION]/var/www/{{project}}/settings.template
     - user: www-data
     - group: www-data
     - template: jinja
     - context:
       django: {{ pillar["django"] }}
```

Obviously file.managed doesn't support this but I'm wondering if anyone has achieved something similar or what would be an appropriate way to get the outcome I'm after (which to reiterate is to have a file on the minion be interpreted as a template with data from the appropriate pillar).
