### ISSUE TITLE
ext_pillar doesn't support 'mountpoint' option

### ISSUE THREAD

**Issue by mrichar1** [saltstack/salt#34210]
With the `fileserver_backend` it is possible using gitfs (pygit2) to specify the mountpoint of a git repo so that repos can be nested  - e.g.:

```
gitfs_remotes:
  - https://git.example.com/root
  - https://git.example.com/alice:
    - mountpoint: salt://alice
```

This allows delegation of a part of the tree, so that in sls files you can do e.g.

```
include:
  - alice.foo
```

However setting mountpoint with ext_pillar complains that this option isn't available:

```
ext_pillar:
  - git:
    - master https://git.example.com/pillar-root
    - master https://git.example.com/pillar-alice:
      - mountpoint: salt://alice
```

The logs show:

```
Invalid git_pillar configuration parameter 'mountpoint' in remote https://git.example.com/pillar-alice. 
Valid parameters are: env, root, ssl_verify, user, password, pubkey, privkey, passphrase, insecure_auth, name.
```

(This is salt 2016.03.01)

Is there a different way to achieve this? If not, could this feature be added?

**Comment by Ch3LL** [comment]
@mrichar1 i'm not seeing the mountpoint option being available in git pillar.

ping @terminalmage what do you think about possibly adding this to feature to external git pillars?

**Comment by terminalmage** [comment]
I'm not sure what the point of this is, git_pillar doesn't work that way. git_pillar files are _never_ addressed using a ``salt://`` URI.

Maybe this is just a confusion of terms. What is it that you are trying to do?

**Comment by terminalmage** [comment]
It looks like maybe you want one git_pillar repo to be available in a sub-folder of another? That would not be easy to do, since git_pillar repos are managed separately. The ext_pillar system is just designed in a fundamentally different way from the fileserver. Each git_pillar repo is handled separately, and the repo is actually checked out, unlike in gitfs where the files are never checked out and are assembled from the blob data, and all gitfs repos are part of the same namespace addressable using ``salt://`` URIs.

**Comment by mrichar1** [comment]
I'm trying to nest the contents of one git repo inside another, so that a 'sub-directory' of pillar config can be in a repo managed by someone else.

This works fine for state SLS files (following https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html) but not for pillars.

**Comment by mrichar1** [comment]
To give a real-world example:

Lets assume I have 3 git repos, each managed by different teams:

`core` contains `top.sls`, `web` and `db` each contain a `server.sls`

On the filesystem, these would look like:

```
/srv/pillar/top.sls
/srv/pillar/web/server.sls
/srv/pillar/db/server.sls
```
Which would be achieved by checking our `core` into /srv/pillar and `web` and `db` into the sub-directories.

This can be achieved for states using the gitfs_remotes option:

```
gitfs_remotes:
  - https://git.example.com/core
  - https://git.example.com/web
    - mountpoint: salt://web
  - https://git.example.com/db
    - mountpoint: salt://db
```

But this doesn't work for git_pillar...
