### ISSUE TITLE
ssh_auth: accept keys from contents_pillar

### ISSUE THREAD

**Issue by pirxthepilot** [saltstack/salt#34231]
I tried using the `ssh_auth` state with `contents_pillar` instead of `source`, like so:

``` yaml
user1-sshkey:
  ssh_auth.present:
    - user: user1
    - contents_pillar: 'ssh_keys:user1.pub'
```

The state runs without errors, but the contents of `user1.pub` does not go into user1's authorized_keys file. Instead, it contains something like `ssh-dsa user1-sshkey`.

I was hoping it would behave like `file.managed`. Would support for this feature be possible in the near future?

**Comment by Ch3LL** [comment]
@pirxthepilot yeah i'm not seeing that argument in that module. I think adding this is plausible and will add as a feature request. 

As a workaround you can call the pillar like so:

```
sshkeys:
  ssh_auth.present:
    - user: root
    - enc: ssh-rsa
    - options:
      - option1="value1"
      - option2="value2 flag2"
    - comment: myuser
    - name: {{ pillar['ssh_key'] }}
```
