### ISSUE TITLE
mysql.query - multiple queries - Commands out of sync

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#34243]
### Description of Issue/Question

mysql.query with multiple lines (or ; separated multiple queries) returns command out of sync

I also tried to run it on the minion , isolating the state

still the same

If I run the same query in the mysql client, no problem appears

[edit : I worked around this by using jinja macros, creating a separate mysql.query for each query but this s@#s, it creates a way bigger state file, I should be able to do multiple queries in one shot ]
### Setup

```
mysql-create-remote-users:
  module.run:
    - name: mysql.query
    - database: mysql
    - password: ************
    - query: |
{% for ip in [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24] %}
             CREATE USER IF NOT EXISTS 'root'@'192.168.2.{{ ip }}' IDENTIFIED BY '************';
             SET PASSWORD FOR 'root'@'192.168.2.{{ ip }}' = PASSWORD('*****************');
             GRANT ALL PRIVILEGES ON *.* TO 'root'@'192.168.2.{{ ip }}' WITH GRANT OPTION;
{% endfor %}       
```

this one causes the same problem too

```
mysql-master-create-replicator:
  module.run:
    - name: mysql.query
    - database: mysql
    - password: **************
    - query: "GRANT REPLICATION SLAVE ON *.* TO 'replicator'@'*********' IDENTIFIED BY     '***********';FLUSH PRIVILEGES;"
```

works perfectly fine in mysql client , but not via mysql.query module

```
      ID: mysql-master-create-replicator
Function: module.run
    Name: mysql.query
  Result: False
 Comment: Module function mysql.query threw an exception. Exception: (2014, "Commands out of sync; you can't run this command now")
 Started: 15:26:28.771667
Duration: 23.047 ms
 Changes:   
```
