### ISSUE TITLE
KeyError: 'ssh.key_is_encrypted' Exception in git.latest when running remotely

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#34269]
### Description of Issue/Question

When running remotely from salt master (salt minion_name state.highstate) there is an exception for every git.latest state:

```
----------
          ID: bitbucket_team_repo
    Function: git.latest
        Name: git@bitbucket:team/repo.git
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1723, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1650, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 587, in latest
                  ignore_retcode=False)
                File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 2842, in remote_refs
                  ignore_retcode=ignore_retcode)['stdout']
                File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 218, in _git_run
                  and __salt__['ssh.key_is_encrypted'](id_file):
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1053, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 93, in __getitem__
                  raise KeyError(key)
              KeyError: 'ssh.key_is_encrypted'
     Started: 13:14:10.777107
    Duration: 21.994 ms
     Changes:
```

Doesn't happen when running locally (salt-call state.highstate):

```
          ID: bitbucket_team_repo
    Function: git.latest
        Name: git@bitbucket:team/repo.git
      Result: True
     Comment: Repository /opt/projects/repo is up-to-date
     Started: 13:19:45.720147
    Duration: 1775.731 ms
     Changes:
```
### Setup

SLS:

```
bitbucket_team_repo:
  git.latest:
    - name: git@bitbucket:team/repo.git
    - target: /opt/projects/repo
    - rev: master
    - identity: /root/.ssh/bitbucket.pkey
    - user: root
    - require:
      - pkg: git_package
      - ssh_known_hosts: bitbucket_known_hosts
      - file: repo_directory
      - file: bitbucket_keyfile
      - file: bitbucket_ssh_config
```
### Steps to Reproduce Issue

run SLS
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-61-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by zerthimon** [comment]
May be related (windows)
https://github.com/saltstack/salt/issues/34237

**Comment by zerthimon** [comment]
This is a regression (appeared apeared after upgraing from 2015.8.5)

**Comment by Ch3LL** [comment]
@zerthimon I think you are right in the issues this is related to. Unfortunately i'm having a hard time replicating this on linux. Can you try this file and see if you are seeing the same behavior:

```
bitbucket_team_repo:
  git.latest:
    - name: git@github.com:saltstack/salt.git
    - target: /tmp/test/
    - rev: 2015.8
    - identity: /root/int-ssh
    - user: root
```

Or any other useful info on how to replicate this

**Comment by zerthimon** [comment]
Will test it later, I've reverted to 2015.8.5 temporarily.

**Comment by daveneeley** [comment]
@Ch3LL we can reproduce this on 2016.3.3, but only on windows. I thought perhaps it was putty key format vs openssh for the identity file, but changing that had no effect.

Our state looks similar to your example.

```
windows_machine:
    Salt Version:
               Salt: 2016.3.3

    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.3.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.2
              ioflo: 1.5.3
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: 0.7.2.None
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.3
                ZMQ: 4.1.2

    System Versions:
               dist:
            machine: AMD64
            release: 7
             system: Windows
            version: 7 6.1.7601 SP1 Multiprocessor Free

linux_machine:
    Salt Version:
               Salt: 2016.3.4

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.4.1
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.20.2
               Mako: 0.3.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.5.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: redhat 6.8 Santiago
            machine: x86_64
            release: 2.6.32-642.6.2.el6.x86_64
             system: Linux
            version: Red Hat Enterprise Linux Server 6.8 Santiago

aix_machine:
    Salt Version:
               Salt: 2015.8.0

    Dependency Versions:
             Jinja2: 2.8
           M2Crypto: 0.22
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.5 (default, Sep  4 2015, 09:20:12)
               RAET: Not Installed
            Tornado: 4.3
                ZMQ: 3.2.3
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed

salt -L linux_machine,windows_machine,aix_machine cmd.run 'git --version'
windows_machine:
    git version 2.10.0.windows.1
linux_machine:
    git version 1.7.1
aix_machine:
    git version 2.2.0

```

#32553 mentions 'the ssh module will return False in virtual if salt.utils.is_windows(), thus it does not exist'. Here's output showing ssh is not in the path on windows, if that helps.

```
salt -L linux_machine,windows_machine,aix_machine cmd.run 'ssh -v'
windows_machine:
    'ssh' is not recognized as an internal or external command,
    operable program or batch file.
linux_machine:
    OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013
aix_machine:
    OpenSSH_5.8p1, OpenSSL 0.9.8r 8 Feb 2011
```

**Comment by daveneeley** [comment]
Here's a better error message from a different windows minion, claims to also be 2016.3.3, :

```
  Function: git.latest
      Result: False
     Comment: Failed to check remote refs: Failed to find ssh.exe, unable to use identity file
     Started: 12:18:34.403000
    Duration: 0.0 ms
     Changes:

windows_machine2:
    Salt Version:
               Salt: 2016.3.3

    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.3.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.2
              ioflo: 1.5.3
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: 0.7.2.None
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.3
                ZMQ: 4.1.2

    System Versions:
               dist:
            machine: AMD64
            release: 7
             system: Windows
            version: 7 6.1.7601 SP1 Multiprocessor Free

salt windows_machine2 'git --version'
windows_machine2:
    git version 2.9.3.windows.1
```

The git distribution is [git for windows](https://git-scm.com/download/win).
