### ISSUE TITLE
Orchestrate runner doesn't obey requisites for other runners and execution modules

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#34278]
### Description of Issue/Question

When using the state.orch runner, it won't obey requisites for other runners or execution modules
### Setup

For instance, if you have the following:

/srv/salt/test/myorch.sls

```
{% set rid = pillar.get('rid') %}

test.echo:
  salt.function:
    - tgt: localhost
    - arg:
      - {{ rid }}

script_test2:
  salt.runner:
    - name: sjmh.test2
    - require:
      - salt: script_test1

script_test1:
   salt.runner:
     - name: sjmh.test1
```

/srv/modules/runners/sjmh.py

```
import sys

def test1():
  sys.exit(1)

def test2():
  print 'hi'
  return 0
```

The orchestrate runner will still execute test2, even though test1 fails.  There is no way to return or exit from the test1 runner function that will notify the test2 runner to not run.  The biggest issue here is that there's no good way to define 'failure' other than 'non-zero exit code'.  But that won't cover cases for when a runner or module runs successfully, but doesn't actually complete what you wanted it to.

It'd be useful if runners and execution modules could return the same dictionary that is required by states and have that obeyed by the state.orch runner.

What would be even nicer is if the state.orch runner was able to set a flag that runners or execution modules could look for to realize they are running in an orchestration context.  Then they could return the dictionary if they were in that context.  Otherwise, they could just return as they normally do.  This would also allow existing runners to keep working with the state.orch and authors could decide whether or not they want to support the state dict.
### Versions Report

Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.el6.x86_64
         system: CentOS 6.8 Final

**Comment by Ch3LL** [comment]
@sjmh I believe this to be related to issue #26499 which looks like it has been fixed in 2016.3 branch with PR #27175 . Looking at this does this resolve what you are attempting to do?

**Comment by sjmh** [comment]
Hey Meggie,

Unfortunately it doesn't seem to work with runners based on other runners.

For example, this works:

```
run_test1:
  salt.function:
    - name: test.retcode

run_test2:
  salt.runner:
    - name: sjmh.test2
    - require:
      - salt: run_test1
```

But this doesn't:

```
run_test1:
  salt.runner:
    - name: sjmh.test1

run_test2:
  salt.runner:
    - name: sjmh.test2
    - require:
      - salt: run_test1
```

Here's the runner:

```
def test1():
  print 'sjmh.test1 ran'
  return {'data': {'retcode': 1}}

def test2():
  print 'sjmh.test2 ran'
  return True
```

If I run the orchestrate with a runner depending on a runner, I get this:

```
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://prov/myorch.sls'
[INFO    ] Running state [sjmh.test1] at time 09:22:29.646275
[INFO    ] Executing state salt.runner for sjmh.test1
sjmh.test1 ran
data:
    ----------
    retcode:
        1
[INFO    ] Runner completed: 20160627092230099703
[INFO    ] {'data': {'retcode': 1}}
[INFO    ] Completed state [sjmh.test1] at time 09:22:30.137492 duration_in_ms=491.217
[INFO    ] Running state [sjmh.test2] at time 09:22:30.138399
[INFO    ] Executing state salt.runner for sjmh.test2
sjmh.test2 ran
True
[INFO    ] Runner completed: 20160627092230599750
[INFO    ] True
[INFO    ] Completed state [sjmh.test2] at time 09:22:30.635887 duration_in_ms=497.488
retcode:
    0
[INFO    ] Runner completed: 20160627092222081352
```

To verify that I was returning correctly from the first runner to indicate a failure, I ran the runner by itself:

```
[root@itmlabsaltdev00 salt]# salt-run sjmh.test1
sjmh.test1 ran
data:
    ----------
    retcode:
        1
[INFO    ] Runner completed: 20160627092426587753
[root@itmlabsaltdev00 salt]# echo $?
1
```

So, unless I'm doing something wrong, it doesn't appear to work on runners requiring other runners.
