### ISSUE TITLE
Pillar passed to orchestrator messed up

### ISSUE THREAD

**Issue by danlsgiga** [saltstack/salt#34315]
### Description of Issue/Question

When passing a pillar dict to an orchestrator via reactor and the dict has a key: value where the value is a list / array, the list gets messed in a way the value content is duplicated 4x inside the same list.
### Setup

/srv/reactor/glusterfs.sls:

```
glusterfs.server-orchestrate:
  runner.state.orchestrate:
    - mods: glusterfs.server.orchestrate.{{ component }}.{{ action }}
    - kwarg:
        queue: True
    - pillar:
        node: {{ data.id }}
        {%- for key, value in data.data.items() %}
        {{ key }}: {{ value }}
        {%- endfor %}
```

is being correctly rendered as:

```
glusterfs.server-orchestrate:
  runner.state.orchestrate:
    - mods: glusterfs.server.orchestrate.volume.create
    - kwarg:
        queue: True
    - pillar:
        node: aws-node1.internal
        bricks: ['aws-node1.internal', 'aws-node2.internal']
        volume: test
        replica: 2
        stripe: False
        path: /volumes
        pool: test

```

/srv/salt/glusterfs/server/volume/create.sls

```
{%- set volume = salt['pillar.get']('volume') %}
{%- set pool = salt['pillar.get']('pool') %}
{%- set bricks = pillar['bricks'] %}
{%- set path = salt['pillar.get']('path') ~ '/' ~ volume %}
{%- set replica = salt['pillar.get']('replica') %}
{%- set stripe = salt['pillar.get']('stripe') %}

glusterfs.server.orchestrate-create-volume-dir:
  salt.function:
    - name: file.mkdir
    - arg:
      - {{ path }}
    - kwarg:
        user: root
        group: root
        mode: 755
    - tgt: {{ bricks | join(',') }}
    - expr_form: list
    - expect_minions: True
    - failhard: True


```

Is messing the array, so when the orchestrate formula is rendered it comes like this:

```
glusterfs.server.orchestrate-create-volume-dir:
  salt.function:
    - name: file.mkdir
    - arg:
      - /volumes
    - kwarg:
        user: root
        group: root
        mode: 755
    - tgt: aws-node1.internal,aws-node2.internal,aws-node1.internal,aws-node2.internal,aws-node1.internal,aws-node2.internal,aws-node1.internal,aws-node2.internal
    - expr_form: list
    - expect_minions: True
    - failhard: True
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

```

So, from all the tests I've made the dict seems to be ok, but when there is a list as a value of a key, it pass 4x the list content to the orchestrator. Totally weird.

This seems to be a huge issue.

**Comment by Ch3LL** [comment]
@danlsgiga i'm having a hard time replicating this. I added your already rendered reactor file to my system: 

```
glusterfs.server-orchestrate:
  runner.state.orchestrate:
    - mods: glusterfs.server.orchestrate.volume.create
    - kwarg:
        queue: True
    - pillar:
        node: aws-node1.internal
        bricks: ['aws-node1.internal', 'aws-node2.internal']
        volume: test
        replica: 2
        stripe: False
        path: /volumes
        pool: test
```

And when it reacts to an event it is correclty rendering the data as such in the logs:

```
glusterfs.server.orchestrate-create-volume-dir:
  salt.function:
    - name: file.mkdir
    - arg:
      - /volumes/test
    - kwarg:
        user: root
        group: root
        mode: 755
    - tgt: aws-node1.internal,aws-node2.internal
    - expr_form: list
    - expect_minions: True
    - failhard: True
```

Do you see this behavior if you add the reactor post-rendered reactor file instead of the jinja file?

**Comment by danlsgiga** [comment]
Hi @Ch3LL, thanks for looking into this.

I did a test with the reactor file fully rendered and the behaviour is the same:

> \# cat /srv/reactor/orchestrator/glusterfs_test.sls


```
glusterfs.server-orchestrate:
  runner.state.orchestrate:
    - mods: glusterfs.server.orchestrate.volume.create_test
    - kwarg:
        queue: True
    - pillar:
        node: aws-node1.internal
        bricks: ['aws-node1.internal', 'aws-node2.internal']
        volume: dev
        replica: 2
        stripe: False
        path: /volumes
        pool: dev
```

Here what I get in the logs:

```
2016-06-29 12:03:28,344 [salt.template    ][DEBUG   ][23168] Rendered data from file: /srv/reactor/orchestrator/glusterfs_test.sls:
glusterfs.server-orchestrate:
  runner.state.orchestrate:
    - mods: glusterfs.server.orchestrate.volume.create_test
    - kwarg:
        queue: True
    - pillar:
        node: aws-node1.internal
        bricks: ['aws-node1.internal', 'aws-node2.internal']
        volume: dev
        replica: 2
        stripe: False
        path: /volumes
        pool: dev

2016-06-29 12:03:37,922 [salt.template    ][DEBUG   ][23168] Rendered data from file: /var/cache/salt/master/files/base/glusterfs/server/orchestrate/volume/create_test.sls:
# vim: sts=2 ts=2 sw=2 et ai

glusterfs.server.orchestrate-create_test-volume-dir:
  salt.function:
    - name: file.mkdir
    - arg:
      - /volumes/dev
    - kwarg:
        user: root
        group: root
        mode: 755
    - tgt: aws-node1.internal,aws-node2.internal,aws-node1.internal,aws-node2.internal,aws-node1.internal,aws-node2.internal,aws-node1.internal,aws-node2.internal
    - expr_form: list
    - expect_minions: True
    - failhard: True
```

**Comment by danlsgiga** [comment]
@Ch3LL, here is another snippet of the log output when I removed the join(',') from the jinja just to validate it is not causing the issue:

```
2016-06-29 12:19:43,338 [salt.template    ][DEBUG   ][23168] Rendered data from file: /var/cache/salt/master/files/base/glusterfs/server/orchestrate/volume/create_test.sls:
# vim: sts=2 ts=2 sw=2 et ai

glusterfs.server.orchestrate-create_test-volume-dir:
  salt.function:
    - name: file.mkdir
    - arg:
      - /volume/dev_123
    - kwarg:
        user: root
        group: root
        mode: 755
    - tgt: ['aws-node1.internal', 'aws-node2.internal', 'aws-node1.internal', 'aws-node2.internal', 'aws-node1.internal', 'aws-node2.internal', 'aws-node1.internal', 'aws-node2.internal']
    - expr_form: list
    - expect_minions: True
    - failhard: True
```

Note that now I'm using the raw pillar got from the reactor but it still has a messy array.

**Comment by danlsgiga** [comment]
@Ch3LL, sorry being a spammer here.

So, I tracked it down and it seems that when the array is not in double quotes it gets messy, when I changed my reactor and set the array on "" then it worked.

> \# cat /srv/reactor/orchestrator/glusterfs_test.sls 
```
glusterfs.server-orchestrate:
  runner.state.orchestrate:
    - mods: glusterfs.server.orchestrate.volume.create_test
    - kwarg:
        queue: True
    - pillar:
        node: aws-node1.internal
        bricks: "['aws-node1.internal', 'aws-node2.internal']"
        volume: dev
        replica: 2
        stripe: False
        path: /volumes
        pool: dev
```

Here the log output:

```
2016-06-29 12:26:27,485 [salt.template    ][DEBUG   ][23168] Rendered data from file: /var/cache/salt/master/files/base/glusterfs/server/orchestrate/volume/create_test.sls:
# vim: sts=2 ts=2 sw=2 et ai

glusterfs.server.orchestrate-create_test-volume-dir:
  salt.function:
    - name: file.mkdir
    - arg:
      - /volume/dev_123
    - kwarg:
        user: root
        group: root
        mode: 755
    - tgt: ['aws-node1.internal', 'aws-node2.internal']
    - expr_form: list
    - expect_minions: True
    - failhard: True
```
