### ISSUE TITLE
Huge confusion reading states requirements doc

### ISSUE THREAD

**Issue by tomlaredo** [saltstack/salt#34331]
### Description of Issue/Question

As I'm currently banging my head against the wall reading and trying to understand the "Requisites" doc, I'm there to ask some help :)

Reading [this doc](https://docs.saltstack.com/en/latest/ref/states/requisites.html), Salt currently provides 13 different requirement/altering directives that sounds very similar:
- require
- require_in
- watch
- watch_in
- prereq
- prereq_in
- use
- use_in
- onchanges
- onchanses_in
- listen
- listen_in
- check_cmd

After having read (and re-read, and re-re-re-re-read) the doc, I'm still lost between those directives. Some of them seems to be covering others (but not sure of this)... Also, some parts of the doc are repeating and some are just unclear (see [the "onchanges" section](https://docs.saltstack.com/en/latest/ref/states/requisites.html#onchanges)).

In my case, I simply wanted to say:
```
# changes += 1 if git repo is not up-do-date
checkout-state:
    - git.latest: ...

# Must only be run if git repo was not up-do-date
deploy-state:
    - cmd.wait: ...
    - watch:
        - git: checkout-state
```

But [the doc says](https://docs.saltstack.com/en/latest/ref/states/requisites.html#watch) "_If a state should only execute when another state has changes, and otherwise do nothing, the new onchanges requisite should be used instead of watch_".

MMmmm... Ok, so it sounds like "do this state ONLY IF this other state ran" but we must use "onchanges" and not "onlyif"... Why not!

So I wrote this code:
```
# changes += 1 if git repo is not up-do-date
checkout-state:
    - git.latest: ...

# Must only be run if git repo was not up-do-date
deploy-state:
    - cmd.wait: ...
    - onchanges:
        - git: checkout-state
```

and ran a salt-call state.apply. The result is that checkout-state ran but deploy-state didn't fire.

As you can see, I'm a bit lost with those directives. As I'm fairly new to Salt (started to use it some months ago), I'm surely going wrong by doing bad things but I still think that the doc could be better written.

Thanks for reading (and don't stop making Salt amazing as it already is) :+1:
