### ISSUE TITLE
pkgrepo does not support http_proxy when its an apt repository

### ISSUE THREAD

**Issue by mrproper** [saltstack/salt#34360]
### Description of Issue/Question
Now that we have http proxy support in tornado (via minion config see: https://github.com/saltstack/salt/pull/29322) when apt-key does not have proxy support built in, apt-key does not support proxies via environment variables by default

### Setup

State file:
```
docker-repo:
  pkgrepo.managed:
    - humanname: Docker
    - name: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    - dist: ubuntu-trusty
    - file: /etc/apt/sources.list.d/docker.list
    - keyid: 2C52609D
    - keyserver: p80.pool.sks-keyservers.net
```

### Steps to Reproduce Issue
Use the above statefile in a machine that requires http_proxy set

Results in a timeout trying apt-key adv

### Versions Report
salt-minion 2016.3.1+ds-1 (ubuntu 16.04)

Though this bug is also present on the 2015 series as well

Im currently writing a patch to support this.. essentially its modifying:
salt/modules/aptpkg.py

adding:
--keyserver-options http-proxy=http://proxy_username:proxy_password@proxy_host:proxy_port
to the appropriate apt-key add commands
