### ISSUE TITLE
State skips notifications when on changed and multiple actions requested

### ISSUE THREAD

**Issue by rafaltrojniak** [saltstack/salt#34363]
### Description of Issue
In situation when:
- state has multiple actions (service.running and enable:true)
- State is modified during run (service is turned off in init script)
- State is notified  during run ( config file is modified => expects to trigger service restart)

The result is :
- Service is enabled in init scripts
- Template is replaced => triggers notification to service
- Service Should be restarted, but is NOT !

Expected resolution:
- Service should be enabled AND restarted

### Steps to Reproduce Issue
Example state:
```yaml
haproxy:
  pkg.installed: []
  service.running:
    - enable: true
    - requires:
      - pkg: haproxy

haroxy-config:
  file.managed:
    - name: /etc/haproxy/haproxy.cfg
    - source: salt://haproxy.cfg.jinja
    - requires:
        pkg: haproxy
    - watch_in:
      - service: haproxy
```
### Steps to Reproduce Issue
- Apply the config, so the destination system is in desired state (nothing changes)
- Disable service 
```bash
salt 'lb*' cmd.run 'chkconfig haproxy off'
```
- Change template
```bash
echo >> /srv/salt/haproxy.cfg.jinja
```
- Run highstate

```
----------
          ID: haroxy-config
    Function: file.managed
        Name: /etc/haproxy/haproxy.cfg
      Result: True
     Comment: File /etc/haproxy/haproxy.cfg updated
     Started: 11:39:13.654215
    Duration: 9.21 ms
     Changes:   
              ----------
              diff:
                  ---  
                  +++  
                  @@ -85,3 +85,4 @@
                   
                   
                   
                  +
----------
          ID: haproxy
    Function: service.running
      Result: True
     Comment: Service haproxy has been enabled, and is in the desired state
     Started: 11:39:13.663604
    Duration: 1270.104 ms
     Changes:   
              ----------
              haproxy:
                  True
```
### Versions Report
salt 2015.5.10 (Lithium)
(have seen it on version 2016 too)
