### ISSUE TITLE
filesystem vs pygit2 salt path in source behavior difference.

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#34374]
### Description of Issue/Question

  In salt-ssh mode a // in a salt:// path used in a source works, but in salt-master mode it does not.

datadog.config.dir = /etc/dd-agent

Works in salt-ssh:

```
datadog_config_file:
  file.managed:
    - name: {{ datadog.config.dir }}/{{ datadog.config.file }}
    - source: salt://datadog/files/{{ datadog.config.dir }}/{{ datadog.config.file }}
    - template: jinja
```

Works in salt-master:

```
datadog_config_file:
  file.managed:
    - name: {{ datadog.config.dir }}/{{ datadog.config.file }}
    - source: salt://datadog/files{{ datadog.config.dir }}/{{ datadog.config.file }}
    - template: jinja
```
### Versions Report

2016.3.1+ds-1

**Comment by edgan** [comment]
I think this might have changed with the 2016.3.0 release. I had previously seen this happen with file.recurse in master mode, but file.managed used to allow //.

**Comment by Ch3LL** [comment]
@edgan I think I might be misunderstanding the test case so if you could help clarify for me:

1. are you receiving an error when it does not work and if so what is the error?
2. Looking at those two files it seems the only difference is between `files/{{ datadog.config.dir }}` and `files{{ datadog.config.dir }}`. 

So I attempted to setup a test case as follows:

```
{% set folder = 'folder' %}
{% set file = 'file' %}
datadog_config_file:
  file.managed:
    - name: /etc/dd-agent
    - source: salt://datadog/{{ folder }}/{{ file }}
    - template: jinja
```

And this seems to be parsing correctly as shown when i run `salt 'ch3ll-ma*' state.show_sls issues.34374`:

```
 ch3ll@localhost  /srv/salt  sudo salt 'ch3ll-ma*' state.show_sls issues.34374 -lwarning
ch3ll-master:
    ----------
    datadog_config_file:
        ----------
        __env__:
            base
        __sls__:
            issues.34374
        file:
            |_
              ----------
              name:
                  /etc/dd-agent
            |_
              ----------
              source:
                  salt://datadog/folder/file
            |_
              ----------
              template:
                  jinja
            - managed
            |_
              ----------
              order:
                  10000
```

As shown above that sems to be working correctly and I am able to run `state.sls` and it adds the file. 

I'm guessing I'm just not understanding the issue entirely. Any clarifications would be appreciated. Thanks!
