### ISSUE TITLE
ProgrammingError: (2014, "Commands out of sync; you can't run this command now")

### ISSUE THREAD

**Issue by tuxick** [saltstack/salt#34421]
### Description of Issue/Question
when running mysql_query.run CREATE TABLE IF NOT EXISTS i get this error:
ProgrammingError: (2014, "Commands out of sync; you can't run this command now")

### Setup
version 2016.3.1

### Steps to Reproduce Issue
run that query

         ID: mysql-init
    Function: mysql_query.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1723, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1650, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/mysql_query.py", line 151, in run
                  query_result = __salt__['mysql.query'](database, query, **connection_args)
                File "/usr/lib/python2.7/site-packages/salt/modules/mysql.py", line 645, in query
                  affected = _execute(cur, query)
                File "/usr/lib/python2.7/site-packages/salt/modules/mysql.py", line 544, in _execute
                  return cur.execute(qry)
                File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 176, in execute
                  if not self._defer_warnings: self._warning_check()
                File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 85, in _warning_check
                  warnings = self._get_db().show_warnings()
                File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 317, in show_warnings
                  self.query("SHOW WARNINGS")
              ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
     Started: 15:34:33.581702
    Duration: 3.888 ms
     Changes:   

### Versions Report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-573.18.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

**Comment by Inveracity** [comment]
I believe this is a [mysql error](http://dev.mysql.com/doc/refman/5.5/en/commands-out-of-sync.html) and not a saltstack error

tested with 
```yaml
testing sql query:
  mysql_query.run:
    - database: mydb
    - query: "CREATE TABLE IF NOT EXISTS testing (test varchar(50))"
```
salt output:
```yaml
test-database:
----------
          ID: lala
    Function: mysql_query.run
      Result: True
     Comment: {'rows affected': 0L, 'query time': {'raw': '0.00192', 'human': '1.9ms'}}
     Started: 13:18:10.187481
    Duration: 5.355 ms
     Changes:
              ----------
              query:
                  Executed

Summary for test-database
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

result on db:
```
mysql> show tables;        
+-------------------------+
| Tables_in_mydb          |
+-------------------------+
| testing                 |
+-------------------------+
```
