### ISSUE TITLE
Windows minion command fails where there is a"-" in a argument

### ISSUE THREAD

**Issue by Trouble123** [saltstack/salt#34448]
Hi

I have been trying to restart the salt-minion service using the service.restart function and it kept failing. Originally i thought it was an issue with the service, but i found if tried to restart saltminion (one word), the request worked, and came back with a false for the result - as expected.

salt-winrepo-ng# salt bugs.XXX.local service.restart 'saltminion'
bugs.XXX.local:
    False

If i put the correct name it fails to run

salt bugs.XXX.local service.restart 'salt-minion'  
bugs.XXX.local:
    The minion function caused an exception: Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1318, in _thread_return
        return_data = executor.execute()
      File "C:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(_self.args, *_self.kwargs)
      File "C:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 214, in restart
        create_win_salt_restart_task()
      File "C:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 240, in create_win_salt_restart_task
        start_time='01:00')
      File "C:\salt\bin\lib\site-packages\salt\modules\win_task.py", line 423, in create_task
        if name in list_tasks(location) and not force:
      File "C:\salt\bin\lib\site-packages\salt\modules\win_task.py", line 288, in list_tasks
        task_service = win32com.client.Dispatch("Schedule.Service")
      File "C:\salt\bin\lib\site-packages\win32com\client__init__.py", line 95, in Dispatch
        dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
      File "C:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
        return (_GetGoodDispatch(IDispatch, clsctx), userName)
      File "C:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
        IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
    com_error: (-2147221005, 'Invalid class string', None, None)

I get the same error if i run it locally on the minion with salt-call. 

I also noticed i was getting the same type of error when running other salt commands on the windows devices yesterday too. 

Salt master is 2016.3.1, and the minions are both 2015.8.3 and 2016.3.1 - both having the issue

**Comment by Ch3LL** [comment]
@Trouble123 I'm having a hard time replicating this as shown below:

```
 ch3ll@localhost  ~  sudo salt 'win2012*' service.restart 'salt-minion'
win2012_issues:
    True
```

This is on a 2012 windows server:

```
 ch3ll@localhost  ~  sudo salt 'win2012*' test.versions_report
win2012_issues:
    Salt Version:
               Salt: 2016.3.1
     
    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.3.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.2
              ioflo: 1.5.3
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.3
                ZMQ: 4.1.2
     
    System Versions:
               dist:   
            machine: AMD64
            release: 2012Server
             system: Windows
            version: 2012Server 6.2.9200 SP0 Multiprocessor Free
```

What window OS are you seeing this behavior? 
How did you install salt?
