### ISSUE TITLE
Salt consul pillar list of dicts

### ISSUE THREAD

**Issue by grobinson-blockchain** [saltstack/salt#34458]
It's unclear from the docs how to create a pillar in Consul that features a list of dicts (or whether this is even possible).

For example, in an SLS file I could write:

```
parent1:
  - key1: value1
  - key2: value2
  - key3: value3
```

but in the Consul K/V store newlines represent list items and the tree represents nested keys. Therefore, it's unclear how `/parent1` could contain a list of key/value pairs.

For example: the following does not work because each line is interpreted as a string:

```
 key1: value1
 key2: value2
 key3: value3
```
