### ISSUE TITLE
No error output for failed deb install in pkg.installed

### ISSUE THREAD

**Issue by dgorissen** [saltstack/salt#34508]
### Description of Issue/Question

On Ubuntu 14.04. My YAML is as follows. Given a directory with (in this case 2) deb files, install each of them in turn.

```
{% for lib in salt['file.find'](debdir) %}
install_{{ lib }}:
  pkg.installed:
    - sources:
      - {{ lib }}: {{ lib }}
{% endfor %}
```

Executing the state with debug shows the following for each package.

```
[INFO    ] Running state [install_/home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb] at time 10:50:29.070330
[INFO    ] Executing state pkg.installed for install_/home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb
[DEBUG   ] Could not LazyLoad pkg.normalize_name
[DEBUG   ] Could not LazyLoad pkg.normalize_name
[INFO    ] Executing command ['dpkg', '-I', '/home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb'] in directory '/root'
[INFO    ] Executing command ['dpkg', '-i', '--force-confold', '/home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb'] in directory '/root'
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/root'
[ERROR   ] The following packages failed to install/update: /home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb
[INFO    ] Completed state [install_/home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb] at time 10:50:35.524311 duration_in_ms=6453.981
```

Running this manually on the same machine.

```
sudo dpkg -i /home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb
```

Works fine without a hitch. Im trying to understand why salt fails to do the same. It would help if there was some error information as to why it failed.
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-91-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by dgorissen** [comment]
Mmm, Im suspecting a bug. The above output is from one of the runs after I had installed it manually. I rebuilt the VM from scratch (im using vagrant) and re-ran salt. I now get this output:]

```
[INFO    ] Running state [install_/home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb] at time 16:16:08.403818
[INFO    ] Executing state pkg.installed for install_/home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb
[DEBUG   ] Could not LazyLoad pkg.normalize_name
[DEBUG   ] Could not LazyLoad pkg.normalize_name
[INFO    ] Executing command ['dpkg', '-I', '/home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb'] in directory '/root'
[INFO    ] Executing command ['dpkg', '-i', '--force-confold', '/home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb'] in directory '/root'
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/root'
[ERROR   ] Made the following changes:
'boost-1-60-0' changed from 'absent' to '20160415-1'

[DEBUG   ] Refreshing modules...
 ...
          ID: install_/home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: /home/foobar/debs/boost-1-60-0_20160415-1_amd64.deb
     Started: 16:16:08.403818
    Duration: 6364.068 ms
     Changes:   
              ----------
              boost-1-60-0:
                  ----------
                  new:
                      20160415-1
                  old:

```

So while it thinks there was an error, it actually did install properly.

**Comment by Ch3LL** [comment]
@dgorissen yeah it looks like its not determining correctly the output of it being installed. I was able to replicate it with this small test case on ubuntu14:

1. `cd /srv/salt`
2. `wget http://archive.ubuntu.com/ubuntu/pool/main/a/alien/alien_8.93_all.deb`
3. /srv/salt/test.sls:

```
install_pkg:
  pkg.installed:
    - sources:
      - alien_8.93_all.deb: salt://alien_8.93_all.deb
```

4. `salt-call --local state.sls test`

```
local:
----------
          ID: install_pkg
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: alien_8.93_all.deb
     Started: 18:05:09.914505
    Duration: 47046.15 ms
     Changes:   
              ----------
              alien:
                  ----------
                  new:
                      8.93
                  old:
```

Says it failed but it did indeed install correctly. We will need to get this fixed up. Thanks

**Comment by BretFisher** [comment]
I've had this issue with a non-repo package above and resolved this issue with proper `- sources` key naming.

I'm on `2015.8.12`

In [Salt documentation](https://docs.saltstack.com/en/2015.8/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed) for `pkg.installed` `sources:` it says:

> A list of packages to install, along with the source URI or local path from which to install each package. In the example below, foo, bar, baz, etc. refer to the name of the package, **as it would appear in the output of the pkg.version or pkg.list_pkgs salt CLI commands.**

So to figure that out I installed my nodejs .deb manually (from nodesource) and ran `pkg.version`:

```
# salt 'client*' pkg.version nodejs
client-1:
    6.9.5-1nodesource1~trusty1
```

So then I apply state with this state file:
```
nodejs:
  pkg.installed:
    - sources:
      - 6.9.5-1nodesource1~trusty1: http://deb.nodesource.com/node_6.x/pool/main/n/nodejs/nodejs_6.9.5-1nodesource1~trusty1_amd64.deb
```

And get the same as @dgorissen above with node properly installed but salt returns on master with false:
```
# salt 'client*' state.apply libs/nodejs
client-1:
----------
          ID: nodejs
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: 6.9.5-1
     Started: 20:29:37.722709
    Duration: 7146.075 ms
     Changes:
              ----------
              nodejs:
                  ----------
                  new:
                      6.9.5-1nodesource1~trusty1
                  old:
              nodejs-dev:
                  ----------
                  new:
                      1
                  old:
              nodejs-legacy:
                  ----------
                  new:
                      1
                  old:
              npm:
                  ----------
                  new:
                      1
                  old:

Summary for client-portal-devops-test-1
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
```

I noticed the app names in the output so changed `sources:` to just `nodejs` and it worked (after removing nodejs to retest):
```
nodejs:
  pkg.installed:
    - sources:
      - nodejs: http://deb.nodesource.com/node_6.x/pool/main/n/nodejs/nodejs_6.9.5-1nodesource1~trusty1_amd64.deb
```
output:
```
# salt 'client*' state.apply libs/nodejs
client-portal-devops-test-1:
----------
          ID: nodejs
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: nodejs
     Started: 20:31:46.215275
    Duration: 7441.49 ms
     Changes:
              ----------
              nodejs:
                  ----------
                  new:
                      6.9.5-1nodesource1~trusty1
                  old:
              nodejs-dev:
                  ----------
                  new:
                      1
                  old:
              nodejs-legacy:
                  ----------
                  new:
                      1
                  old:
              npm:
                  ----------
                  new:
                      1
                  old:

Summary for client-portal-devops-test-1
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

So if that's the proper `sources` standard, I'd recommend chaging the documentation. Hope this helps.

**Comment by amontalban** [comment]
@Ch3LL can we have documentation add an example like @BretFisher showed?

I was having same issue and thanks to above comment it allowed me to use custom sources.

In your report test the fix would be:

```
install_pkg:
  pkg.installed:
    - sources:
      - alien: salt://alien_8.93_all.deb
```

The first parameter is the `Source` value in: `dpkg -I <package.deb>`, if you use anything else it will fail or it will try to install package using `apt-get` instead of custom `deb`.
