### ISSUE TITLE
Allow Thorium to make existing reactor like calls

### ISSUE THREAD

**Issue by thatch45** [saltstack/salt#34516]
This means that we need a thorium state that checks for a specific matched event:

```
salt/foo/*/bar:
  check.event

run_thing:
  local.cmd:
    - tgt: '*'
    - func: test.ping
```
