### ISSUE TITLE
The templated file on `file.managed` is evaluated twice

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#34562]
### Description of Issue/Question

(More specific follow-up to #34433.) The templated file when using `file.managed` is run through the Jinja engine twice.
### Steps to Reproduce Issue

``` yaml
# /srv/salt/tmpltest.sls
templated_file:
  file.managed:
    - name: /tmp/templated_file
    - source: salt://templated_file.tmpl
    - template: jinja
```

``` jinja
{# /srv/salt/templated_file.tmpl #}
{{ salt.cmd.run('touch /tmp/gotfoo && echo foo >> /tmp/gotfoo') }}
```

Run the state: `salt '<mid>' state.sls tmpltest`

Then check the result:

```
% cat /tmp/gotfoo
foo
foo
```

There should only be one `foo` in the resulting file.
### Versions Report

Tested on 2016.3 and develop (9d998ce).
