### ISSUE TITLE
State definitions in SLS files

### ISSUE THREAD

**Issue by madduck** [saltstack/salt#3460]
Would you consider providing a way by which I can define new states in SLS files, based on other states?

Let me elaborate, using the following example. Let's say you have to create three (hypothetical) files on the target system. The files are identical except for two "parameters", which differ between those files (e.g. "red"/1, "blue"/2 and "green"/3).

One way to achieve this is to create three `file.managed` stanzas using the same template, but providing different context.

If you do this, you'll quickly note the duplication, and you'll want to do something about it. You could define a sequence of parameters and loop over that sequence e.g. with mako, effectively instantiating the three `file.managed` stanzas with different parameters, e.g.

```
% for i in [('red',1),('blue',2),('green',3)]
/my/file/for/${i[0]}:
  file.managed:
    user: root
    template: myfile.j2
    context:
      - colour: ${i[0]}
      - number: ${i[1]}
% endfor
```

Alternatively, you'd wish to be able to define a macro, e.g.

```
define:
  mymacro:
    parameters:
      - colour
      - number
    body:
      /my/file/for/%colour%:
        file.managed:
          …
          context:
            …
```

The parameters could even be made available as context by default.

And now the above could be handled as follows:

```
mymacro:
  - colour: red
  - number: 1

mymacro:
  - colour: blue
  - number: 2

mymacro:
  - colour: green
  - number: 3
```

which would expand internally to three `file.managed` stanzas.

This is surely possible with templating, but the functionality is useful
enough to be integrated into Salt proper.

Maybe there is a better syntax for this. Does it have to be YAML?
