### ISSUE TITLE
Ubuntu Xenial, state network.managed and files in /etc/network/interfaces.d/*

### ISSUE THREAD

**Issue by pcdummy** [saltstack/salt#34635]
network.managed produces my eth0 interface with the wrong proto **dhcp**, but i gave
**static** explicitly.
### Setup

I have the following ([generated](https://rene.jochums.at/having-fun-with-saltstack-and-ext_pillar-mongo)) state:

```
  network_eth0_192.168.158.19:
    network:
    - managed
    - name: eth0
    - enabled: true
    - type: eth
    - proto: static
    - ipaddr: 192.168.158.19
    - gateway: 192.168.158.1
    - netmask: 255.255.255.0
    - dns-nameservers:
      - fd57:1:see:bad:c0de::19
    - dns-search:
      - pcdummy.lan
    - enable_ipv6: true
    - ipv6proto: static
    - ipv6ipaddr: 2001:1:see:bad:c0de::19
    - ipv6netmask: 80
    - ipv6gateway: fe80::1
    - noifupdown: true
    - order: 10001
  network_eth1_10.128.2.19:
    network:
    - managed
    - name: eth1
    - enabled: true
    - type: eth
    - proto: static
    - ipaddr: 10.128.2.19
    - netmask: 255.255.255.0
    - up_cmds:
      - /sbin/ip -4 route add 10.0.0.0/8 via 10.128.2.1 dev $IFACE
      - /sbin/ip -6 route add fd57:1:see:bad::/48 via fe80::1 dev $IFACE
    - dns-nameservers:
      - fd57:1:see:bad:c0de::19
    - dns-search:
      - pcdummy.lan
    - enable_ipv6: true
    - ipv6proto: static
    - ipv6ipaddr: fd57:1:see:bad:c0de::19
    - ipv6netmask: 64
    - noifupdown: true
    - order: 10002
  network_lo:
    network:
    - managed
    - name: lo
    - enabled: true
    - type: eth
    - proto: loopback
    - order: 10000
```

Cloud-init file in **/etc/network/interfaces.d/50-cloud-init.cfg**:

```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
```

No include in **/etc/network/interfaces**
### Steps to Reproduce Issue

When i run the above state i don't get eth0 with the proto static but **dhcp**.
### Versions Report

```
$ salt-call --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.2.0-41-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
