### ISSUE TITLE
utils.shlex_split removing quotes which are required for augeas

### ISSUE THREAD

**Issue by nevins-b** [saltstack/salt#34640]
When using aegus.change it appears that the utils.shlex_split function is stripping quotes from the command which make augeas fail.

### Setup
```yml
shm-mount-options:
  augeas.change:
    - lens: Fstab.lns
    - changes:
      - ins opt after /files/etc/fstab/*[spec="tmpfs"]/opt[last()]
      - set /files/etc/fstab/*[spec="tmpfs"]/opt[last()] nodev
    - unless: 'grep -e "^tmpfs.*defaults,nodev" /etc/fstab'
```

### Steps to Reproduce Issue
With some additional logging added the issue is apparent that the double quotes have been stripped from the path.
```{'path': '/files/etc/fstab/*[file=/tmp]/opt[last()]', 'before': False, 'label': 'opt'}```
