### ISSUE TITLE
Can not use file.line on Windows

### ISSUE THREAD

**Issue by andras-tim** [saltstack/salt#34665]
### Description of Issue/Question
Can not use `file.line` on Windows, because it is not passed through in `win_file.py`

### Steps to Reproduce Issue
1. use `file.line` in a state file what will be evaluated on a Windows host
2. run a `state.apply`

### Versions Report
```
    Salt Version:
               Salt: 2016.3.1
     
    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.3.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.2
              ioflo: 1.5.3
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.3
                ZMQ: 4.1.2
     
    System Versions:
               dist:   
            machine: x86
            release: 2003Server
             system: Windows
            version: 2003Server 5.2.3790 SP2 Uniprocessor Free
```
