### ISSUE TITLE
PagerDuty states don't show changes

### ISSUE THREAD

**Issue by cmclaughlin** [saltstack/salt#34706]
### Description of Issue/Question

Expected highstate to show changes.  salt/modules/pagerduty_util.py doesn't set it.
### Setup

```
test:
  pagerduty_escalation_policy.present:
    - description: Managed by Salt
    - profile: False
    - api_key: ...
    - subdomain: ...
    - escalation_rules: ...
```
### Steps to Reproduce Issue

Change the escalation_rules, re-apply the state.
### Versions Report

```
# salt --versions-report
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.6
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Ubuntu 14.04 trusty
```
