### ISSUE TITLE
`git.latest` with `force_reset` set to `True` does not reset local changes, causing it to fail.

### ISSUE THREAD

**Issue by akoumjian** [saltstack/salt#34725]
### Description of Issue/Question

`git.latest` with `force_reset` set to `True` does not reset local changes, causing it to fail.

### Setup
Two states, one to clone a git repo, another that templates a config file after cloning. It will work the first time, but the second time it will fail. 

```yaml
webapp:
  git.latest:
    - name: [redacted]
    - rev: {{ git_rev }}
    - target: /var/www/
    - force_reset: True

settings:
  file.managed:
    - name: /var/www/appname/settings.py
    - source: salt://app/settings.py
    - template: jinja
    - watch:
      - git: webapp
```

### Steps to Reproduce Issue

My relevant real logs can be found here: https://gist.github.com/akoumjian/d464a69fa3b3cce8f0d5ad27a8e6f42c

You will notice the absence of reset ever being issued. I suspect this is the problem.

### Versions Report

```
(env)130 ubuntu@ip-10-0-0-201:/srv⟫ sudo salt-call --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-91-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
