### ISSUE TITLE
Cachedir is ignored

### ISSUE THREAD

**Issue by Someguy123** [saltstack/salt#34766]
Latest Salt, 2016.3.1 running on OSX 10.10 (Yosemite)

Here's my Saltfile:

```
salt-ssh:
  roster_file: /Users/chris/salt-ssh/roster
  config_dir: /Users/chris/salt-ssh
  cachedir: /Users/chris/salt-ssh/cache
  log_file: /Users/chris/salt-ssh/log.txt
```

The cache dir exists with 777 permissions, no problem for it. However, it refuses to use it, and tries to use /var/cache, resulting in a permission error as non-root.

Attempting to pass the cachedir manually results in:

   salt-ssh: error: no such option: --cachedir
