### ISSUE TITLE
zpool state module needs support for disk vdev

### ISSUE THREAD

**Issue by aphor** [saltstack/salt#34762]
salt.modules.zpool does not support explicit (the second simplest example) "disk" type zpool vdev

Since the salt.states.zpool requires a vdev in layout kwarg in state.sls files, it is impossible to use this state module to create a simple single disk vdev zpool.

This should be a valid state
```
newpool:
  zpool.present:
    - config:
        import: false
        force: true
    - properties:
        comment: salty storage pool
    - layout:
        disk-0:
          /dev/disk0
          /dev/disk1
```
but produces an ambiguous error, assuming that the "disk" vdev is supposed to be interpreted by the salt.modules.zpool.create() as a device node on the filesystem
```
             if not os.path.exists(vdev):
                 ret[zpool][vdev] = 'not present on filesystem'
```

salt.states.zpool also does a similar (broken) check (DRY?) to validate the state layout.
