### ISSUE TITLE
Unable to Pass Arguments to Windows Minion Installer

### ISSUE THREAD

**Issue by yamamushi** [saltstack/salt#34785]
### Description of Issue/Question

This is more of a question than an issue at this point, as I'm presuming the capability exists I'm just not seeing documentation for it, and another issue is preventing me from moving forward with testing it extensively.

I am trying to create windows instances in EC2 using Salt in a private VPC.

However this VPC does not have internet access, and all internet connectivity is being routed through a proxy server.

This workaround has been successful for Linux minions, as there is a documented option for passing flags to the bootstrap installer script.

However I have not found a documented workaround for the Windows installer executable, or at least a way to pass options to it. 

This is somewhat related to another issue I've opened #34783
### Setup

I've tried the following , but the previously mentioned ticket describes an issue that has prevented me from getting much further:

```
base_teamcityserver:
  provider: redacted-ec2
  image: ami-fdf77aea
  size: t2.micro
  use_winrm: True
  userdata_file: /etc/salt/windows-firewall.ps1
  win_installer: /etc/salt/Salt-Minion-2016.3.1-AMD64-Setup.exe
  win_installer_args: -G -H "http://172.30.0.143:3128"
  win_username: Administrator
  win_password: 'redacted'
  win_interface: private_ips
  smb_port: 445
  script: bootstrap-salt
  script_args: -G -H "http://172.30.0.143:3128"
  subnetid: subnet-redacted
  securitygroupid:
    - sg-redacted
```
### Steps to Reproduce Issue

`salt-cloud -p base_teamcityserver teamcitytest1 -l debug`
### Versions Report

```

Salt Version:
           Salt: 2016.3.0-n/a-764f56f

Dependency Versions:
           cffi: Not Installed
       cherrypy: 6.1.0
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```
