### ISSUE TITLE
dockerng is not available

### ISSUE THREAD

**Issue by m0stwanted** [saltstack/salt#34782]
Hello!
I'm trying to load docker images (tar files exported by `docker save` command)  from salt master to salt minions local docker registry via `dockerng.load`.  I installed `docker-py` on master and minions, so when I run `salt '*' dockerng.version` I receive correct output:
```
minion1:                                                                                                              
    ----------                                                                                                        
    ApiVersion:                                                                                                       
        1.23                                                                                                          
    ApiVersionInfo:                                                                                                   
        - 1                                                                                                           
        - 23                                                                                                          
    Arch:                                                                                                             
        amd64                                                                                                         
    BuildTime:                                                                                                        
        2016-06-01T21:23:11.279703501+00:00                                                                           
    GitCommit:                                                                                                        
        b9f10c9                                                                                                       
    GoVersion:                                                                                                        
        go1.5.4                                                                                                       
    KernelVersion:                                                                                                    
        3.10.0-327.13.1.el7.x86_64                                                                                    
    Os:                                                                                                               
        linux                                                                                                         
    Version:                                                                                                          
        1.11.2                                                                                                        
    VersionInfo:                                                                                                      
        - 1                                                                                                           
        - 11                                                                                                          
        - 2
minion2:
 ...
```

When I run command directly form CLI: 
`salt '*' dockerng.load salt://docker/files/images/kafka.tar`
everything just fine - minions import images and they available in registry. 

But I have a problem with state:
```
docker-load-image-kafka:
  dockerng.load:
    - path: salt://docker/files/images/kafka.tar
```

After running it fails with exception:
```
    ID: docker-load-image-docker-nc/files/images/kafka.tar                                                      
    Function: dockerng.load                                                                                           
      Result: False                                                                                                   
     Comment: State 'dockerng.load' was not found in SLS 'docker-nc'                                                  
              Reason: 'dockerng.load' is not available.                                                               
     Started:                                                                                                         
    Duration:                                                                                                         
     Changes:                                                                                                         
```

### Versions Report
```
Salt Version:                                                                                                         
           Salt: 2016.3.1                                                                                             
                                                                                                                      
Dependency Versions:                                                                                                  
           cffi: Not Installed                                                                                        
       cherrypy: Not Installed                                                                                        
       dateutil: Not Installed                                                                                        
          gitdb: Not Installed                                                                                        
      gitpython: Not Installed                                                                                        
          ioflo: Not Installed                                                                                        
         Jinja2: 2.7.2                                                                                                
        libgit2: Not Installed                                                                                        
        libnacl: Not Installed                                                                                        
       M2Crypto: 0.21.1                                                                                               
           Mako: Not Installed                                                                                        
   msgpack-pure: Not Installed                                                                                        
 msgpack-python: 0.4.7                                                                                                
   mysql-python: Not Installed                                                                                        
      pycparser: Not Installed                                                                                        
       pycrypto: 2.6.1                                                                                                
         pygit2: Not Installed                                                                                        
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)                                                               
   python-gnupg: Not Installed                                                                                        
         PyYAML: 3.11                                                                                                 
          PyZMQ: 14.7.0
          RAET: Not Installed                                                                                        
          smmap: Not Installed                                                                                        
        timelib: Not Installed                                                                                        
        Tornado: 4.2.1                                                                                                
            ZMQ: 4.0.5                                                                                                
                                                                                                                      
System Versions:                                                                                                      
           dist: centos 7.2.1511 Core                                                                                 
        machine: x86_64                                                                                               
        release: 3.10.0-327.13.1.el7.x86_64                                                                           
         system: Linux                                                                                                
        version: CentOS Linux 7.2.1511 Core
```

Any ideas about this behaviour?
