### ISSUE TITLE
postgres_schema.present with Amazon RDS::POSTGRES database fails when schema already exists

### ISSUE THREAD

**Issue by wblair** [saltstack/salt#34802]
### Description of Issue/Question

postgres_schema.present fails when schema already exists
in an AWS::RDS::POSTGRES database

This is the same behavior seen in issue #32256 regarding
postgres_user.present in an AWS::RDS::POSTGRES database
### Setup

```
create_schema:
  postgres_schema.present:
    - name: schemaExample
    - dbname: search
    - owner: web
    - db_user: centos
    - db_password: myPassword
    - db_host: dbServer.example.com
    - db_port: 5432
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

Debug log attached.

[debug.txt](https://github.com/saltstack/salt/files/372717/debug.txt)

Apply the above state and it successfully creates the schema.
Re-apply the above state and it fails because the schema already exists.

For example: `salt-call -l debug state.sls example.schema-failure`
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```
