### ISSUE TITLE
Better Error Reporting with ip.set_dhcp_ip on windows

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#34836]
### Description of Issue/Question

When attempting to run `salt 'win2*' ip.set_dhcp_ip 'Local Area Connection'` it returns the following:

```
win2012:
    ----------
    DHCP enabled:
        Yes
    Interface:
        Local Area Connection
ERROR: Minions returned with non-zero exit code
```

This message was confusing because it states that DHCP enabled is yes for the Local Areas connection interface, when actually I do not have a Local Area Connection interface. As shown in the code [here](https://github.com/saltstack/salt/blob/develop/salt/modules/win_ip.py#L325) it always report back yes. I think some logic added to here would be useful to check to ensure an interface exists and return an a better error message.
### Setup
1. windows minion
2. run the module:

```
 ✘ ch3ll@localhost  ~  sudo salt 'win2*' ip.set_dhcp_ip 'Local Area Connection'
win2012:
    ----------
    DHCP enabled:
        Yes
    Interface:
        Local Area Connection
ERROR: Minions returned with non-zero exit code
```
### Versions Report

```
win2012:
    Salt Version:
               Salt: 2015.8.11

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist:   
            machine: AMD64
            release: 8
             system: 8 6.2.9200 SP0 Multiprocessor Free
```
