### ISSUE TITLE
Wrong return when using `user.chgroups` on windows

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#34841]
### Description of Issue/Question

When running `salt '*' user.chgroups dude 'groupy,groupz'` I get return True, even though it exists with return code 11 because the group does not exist. I am expecting this to return false.
### Setup
1. windows salt-minion
### Steps to Reproduce Issue
1. 

```
 ✘ ch3ll@localhost  ~  sudo salt 'win2*' user.chgroups dude 'groupy,groupz'
win2012:
    True
ERROR: Minions returned with non-zero exit code
 ✘ ch3ll@localhost  ~  echo $?
11
```

As shown below salt-call provides more information and tells us this is because groupy does not exist:

```
 ch3ll@localhost  ~  sudo salt 'win2*' cmd.run "C:\salt\salt-call.bat --local user.chgroups dude 'groupy,groupz'" 
win2012:
    [INFO    ] Executing command 'net localgroup "groupz" dude /add' in directory 'C:\\Windows\\system32\\config\\systemprofile'
    [ERROR   ] Command 'net localgroup "groupz" dude /add' failed with return code: 2
    [ERROR   ] stderr: System error 1376 has occurred.



    The specified local group does not exist.
    [ERROR   ] retcode: 2
    local:
        True
```

I would expect to see a False above instead of True since their is a fail in the command.
### Versions Report

```
win2012:
    Salt Version:
               Salt: 2015.8.11

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist:   
            machine: AMD64
            release: 8
             system: 8 6.2.9200 SP0 Multiprocessor Free
```
