### ISSUE TITLE
pkg.installed always fails for custom package

### ISSUE THREAD

**Issue by mirko** [saltstack/salt#34867]
I'm experiencing the issue, that ensuring a pkg-state for a custom deb file always fails.
The package gets installed fine and the dpkg call succeeds. Even if the package is already installed (state being pushed before or package installed manually) ensuring the state fails.

relevant content of sls file:
```
grafana-data:
  pkg.installed:
    - sources:
      - salt-repo: salt://mon-master/grafana-data_2.6.0+dfsg-3_all.deb
```

Output:
```
          ID: grafana-data
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: salt-repo
     Started: 23:44:16.500298
    Duration: 10845.388 ms
     Changes:
```

Observed call on minion:
```
\_ /usr/bin/python2.7 /var/tmp/.conf_7c7bca_salt/salt-call --local --metadata --out json -l quiet -c /var/tmp/.conf_7c7bca_salt -- state.pkg /var/tmp/.conf_7c7bca_salt/salt_state.tgz test=None pkg_sum=e954a4212dc0658cdd4a252a079c32fb hash_type=md5
    \_ dpkg -i --force-confold /var/tmp/.conf_7c7bca_salt/running_data/var/cache/salt/minion/files/base/mon-master/grafana-data_2.6.0+dfsg-3_all.deb
```

Call executed manually (*just for reference, since even if package is installed enforcing state fails!*):
```
# dpkg -i --force-confold /var/tmp/.conf_7c7bca_salt/running_data/var/cache/salt/minion/files/base/mon-master/grafana-data_2.6.0+dfsg-3_all.deb ; echo $?
(Reading database ... 52147 files and directories currently installed.)
Preparing to unpack .../grafana-data_2.6.0+dfsg-3_all.deb ...
Unpacking grafana-data (2.6.0+dfsg-3) over (2.6.0+dfsg-3) ...
Setting up grafana-data (2.6.0+dfsg-3) ...
0
```
