### ISSUE TITLE
Sequence vs Mapping YAML Usage

### ISSUE THREAD

**Issue by pstengel** [saltstack/salt#34881]
Why are Salt states formed as a sequence instead of a mapping? To illustrate:

``` yaml
# Sequence-style
some-file:
  file.managed:
    - name: /tmp/some-file
    - user: nobody

# Mapping-style
some-file:
  file.managed:
    name: /tmp/some-file
    user: nobody
```

The "sequence-style" above is how Salt currently expects you to declare a state, but it seems like it adds complication to parsing and doesn't really make sense given that each sequence item is a single mapping. The mapping-style seems more straight-forward given the type of data we're dealing with (keys and values describing properties of the state).

The Python object we get from the current style:

``` python
{'some-file': {'file.managed': [{'name': '/tmp/some-file'}, {'user': 'nobody'}]}}
```

From the mapping style, we'd get:

``` python
{'some-file': {'file.managed': {'name': '/tmp/some-file', 'user': 'nobody'}}}
```

Not only is the mapping-style more intuitive for those who know YAML considering the data type, isn't the latter easier to parse in code? Instead of having to iterate through a list to construct the map of properties for the state, you already have the map.

As I ask at the beginning, why is it like this?
