### ISSUE TITLE
[QUESTION] Is salt-cloud always supposed to create a network interface in EC2 if specified?

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#34888]
I am trying to launch an EC2 instance via salt cloud into a vpc. I am trying to specify a static private IP address through a network interface defined in my profile. It works just fine and create the network interface with the correct IP if it does not exist and attaches. 

Here is the relevant section of salt profile definition:
```
network_interfaces:
    - DeviceIndex: 0
      SubnetId: subnet-xxxxxxxx
      SecurityGroupId:
        - sg-xxxxxxxx
        - sg-xxxxxxxx
        - sg-xxxxxxxx
        - sg-xxxxxxxx
      PrivateIpAddress: 10.0.0.123

```

However when I delete the instance via salt-cloud -d, then try and recreate the instance is errors out claiming the IP address specified is already in use. 

Is there a way to make salt-cloud either delete the network interface it creates and associates with the instance when deleting the instance, or to look for the already existing network interface with the specified IP and attach it if it is available?
