### ISSUE TITLE
timeout issue when running the `win_wua` execution module

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#34903]
### Description of Issue/Question

I am receiving a minion timeout error when using the `win_wua` execution module when the job takes a long time to complete. The command completes, as I tested it using `salt-call --local` and eventually increasing my timeout to `1000`, but I would expect to not have to increase my timeout this high to see the results. This is related to #34868 
### Setup
1. (1) windows minion and linux master
### Steps to Reproduce Issue
1. `salt 'win*' win_wua.install_update ff0aeb4c-337a-467d-bcd5-02840076f371` or `salt win* win_wua.list_updates`

```
 ✘ ch3ll@localhost  /etc/salt  sudo salt 'win*' win_wua.install_update ff0aeb4c-337a-467d-bcd5-02840076f371
win2012:
    Minion did not return. [Not connected]
```
### Versions Report

```
win2012:
    Salt Version:
               Salt: 2015.8.11

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist:   
            machine: AMD64
            release: 8
             system: 8 6.2.9200 SP0 Multiprocessor Free
```
