### ISSUE TITLE
Module 'service' is not available.

### ISSUE THREAD

**Issue by sincilite** [saltstack/salt#34928]
### Description of Issue/Question
Running service.X for a package results in Module 'service' is not available response.

### Setup

```
 sudo salt <minion-id> grains.items | grep os
    biosreleasedate:
    biosversion:
    ec2_hostname:
    ec2_local-hostname:
    ec2_metrics_vhostmd:
    ec2_network_interfaces_macs_06:2c:65:0c:f0:d7_local-hostname:
    host:
    localhost:
    os:
    os_family:
    osarch:
    oscodename:
    osfinger:
        CentOS-Sophos
    osfullname:
    osmajorrelease:
        Sophos
    osrelease:
        Sophos
    osrelease_info:
        - Sophos
```

```
$ cat /etc/lsb-release
$ LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
```

### Versions Report
**Salt Minion**

```
salt-minion --versions-report
           Salt: 2015.5.10
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 2.5.3
```

**Salt Master**

```
$ salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Dec 17 2015, 01:08:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 4.4.14-24.50.amzn1.x86_64
         system: Linux
        version: Not Installed
```
