### ISSUE TITLE
Much apprecited for your help with LDAP AUTH

### ISSUE THREAD

**Issue by pingangit** [saltstack/salt#34952]
### Description of Issue/Question

I'm using ldap as external auth system.  There is one master node.  It manages 4 syndic nodes.  For each syndic, we install one minion.  These 4 minions on syndic nodes ID are beginning with 'SYNDIC'.  The other 200+ minions IDs are not beginning with 'SYNDIC'.
I have targeting in the file eauth.conf.  When I use 'salt' with targeting '*', it should have prompted error that the LDAP auth failed.  However, the test result is that it can excute on all the 200+ minions.

---

```
             master
             /          \
SYNDIC-SHA   SYNDIC-LFA ...(4 syndic nodes)
           /                     \
CNSH031461 ...         CNLF032315 ...(200+minions)
```

---

test result/log:

```
[kangxiaoning495@xxxx ~] salt -a ldap -T 'SYNDIC-SZB' test.ping
SYNDIC-SZB:
    True
[kangxiaoning495@xxxx ~] salt -a ldap -T '*' test.ping | grep True | wc -l
257
[kangxiaoning495@xxxx ~]

kangxiaoning495@xxxx ~]$ salt -a ldap -T '*' test.ping                   
SYNDIC-SZC:
    True
SYNDIC-SHA:
    True
SYNDIC-LFA:
    True
SYNDIC-SZB:
    True
CNLF031461:
    True
CNLF031460:
    True
CNLF031462:
    True
CNLF031465:
    True
CNLF031464:
    True
CNLF031467:
......
```

......

---
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
more /etc/salt/master.d/eauth.conf | egrep -v '^#|'
external_auth:
  ldap:
    kangxiaoning495:
      - 'SYNDIC*':
        - .*
        - '@wheel'
        - '@runner'
        - '@jobs'       
auth.ldap.server: ldap.xxxx.xxxx
auth.ldap.port: 389
auth.ldap.basedn: cn=users,cn=accounts,dc=xxxx,dc=xxxx
auth.ldap.binddn: uid=admin,cn=users,cn=accounts,dc=xxxx,dc=xxxx
auth.ldap.bindpw: xxxx
auth.ldap.filter: uid={{ username }}
```

more /etc/salt/master | egrep -v '^#|'

```
interface: 0.0.0.0
publish_port: 4505
ret_port: 4506
gather_job_timeout: 15
timeout: 5
worker_threads: 5
file_roots:
  base:
    - /srv/salt
hash_type: sha256
pillar_roots:
  base:
    - /srv/pillar
order_masters: True
syndic_wait: 20
master_job_cache: mysql
mysql.host: 'xxxx'
mysql.user: 'salt'
mysql.pass: 'salt'
mysql.db: 'salt'
mysql.port: 3306
mysql.ssl_ca: None
mysql.ssl_cert: None
mysql.ssl_key: None
```

```
[root@xxxx ~]# salt-key
Accepted Keys:
SYNDIC-LFA
SYNDIC-SHA
SYNDIC-SZB
SYNDIC-SZC
Denied Keys:
Unaccepted Keys:
Rejected Keys:
[root@xxxx ~]#
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

```
[kangxiaoning495@xxxx ~] salt -a ldap -T 'SYNDIC-SZB' test.ping
SYNDIC-SZB:
    True
[kangxiaoning495@xxxx ~] salt -a ldap -T '*' test.ping | grep True | wc -l
257
[kangxiaoning495@xxxx ~]
```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.3.0
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
System Versions:
           dist: oracle 6.7
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: Oracle Linux Server 6.7
```
