### ISSUE TITLE
top_file_merging_strategy does not work as documented

### ISSUE THREAD

**Issue by GarthSnyder** [saltstack/salt#34975]
top_file_merging_strategy is documented as a minion-side configuration option. But if you set it to 'same' on the minion side, you'll see that it has no actual effect. 

There's a warning message generated whenever multiple top files are merged. In the current version of 2016.3, the message is "top_file_merging_strategy is set to 'merge' and multiple top files were found. Merging order is not deterministic, it may be desirable to either set top_file_merging_strategy to 'same' or use the 'env_order' configuration parameter to specify the merging order." Older versions have a slightly different message.

Anyway, this warning is always printed whenever you go down the "merge" path in salt/state.py with multiple top files, so it's an easy way to verify that get_tops() is seeing a top_files_merging_strategy of "merge" despite this option being set to 'same' in /etc/salt/minion.

I believe the underlying issue is that __gen_opts() in salt/state.py copies over some option values from the master and does not successfully allow the minion settings to override the master. The code looks roughly like this:

```
def __gen_opts(self, opts):
    ...
    mopts = self.client.master_opts()
    ...
    opts['state_auto_order'] = mopts.get('state_auto_order', opts['state_auto_order'])
    opts['top_file_merging_strategy'] = mopts.get('top_file_merging_strategy', opts.get('top_file_merging_strategy'))
    opts['env_order'] = mopts.get('env_order', opts.get('env_order', []))
    opts['default_top'] = mopts.get('default_top', opts.get('default_top'))
    opts['state_aggregate'] = mopts.get('state_aggregate', opts.get('state_aggregate', False))
    return opts
```

The issue seems to be that any option with a default value will show up in the mopts hash. So whether you set top_file_merging_strategy explicitly or not on the master, it does have a value there, and so the minion's local value always gets clobbered.

I would hazard a guess that some of the other copied options are in this same boat, too.

**Comment by GarthSnyder** [comment]
```
Salt Version:
           Salt: 2016.3.1-147-gf23e8c5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  5 2016, 01:21:33)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
 
System Versions:
           dist:   
        machine: amd64
        release: 10.2-RELEASE-p18
         system: FreeBSD
        version: Not Installed

```
