### ISSUE TITLE
Windows cpu_model grain is incorrect

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#35027]
### Description of Issue/Question
Currently the Windows version of the salt-minion provides the wrong type of information for the `cpu_model` grain. I'm pretty sure this has been the case since the earliest versions of Salt on Windows, but I think this should be changed on develop and include a large notice in the release notes.

### Steps to Reproduce Issue

```
root@bouchamaster:~# salt \* grains.item cpu_model
bouchamaster:
    ----------
    cpu_model:
        Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
testwin01:
    ----------
    cpu_model:
        Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
```

bouchamaster is a linux vm
testwin01 is a windows vm

### Versions Report
```
root@bouchamaster:~# salt testwin01 test.versions_report
testwin01:
    Salt Version:
               Salt: 2015.8.8
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist:   
            machine: AMD64
            release: 8
             system: 8 6.2.9200 SP0 Multiprocessor Free
```
