### ISSUE TITLE
postgres_user.present makes excessive SQL queries (regression)

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#35070]
### Description of Issue/Question

The changes made to modules.postgres.user_list() in saltstack/salt#20980 cause postgres_user.present states to issue many times more SQL queries (each in distinct psql subprocess).   This number of queries is directly proportional to the number roles present in your postgresql server. So in our case, our 30-odd server-side roles result in 30+ queries for a single postgres_user.present state.
### Steps to Reproduce Issue

On a box with a local copy of postgres create a handful of roles:

```
psql postgres -c "CREATE ROLE poop1; CREATE ROLE poop2; CREATE ROLE poop3;"
```

Then run a simple postgres_user.present state.

```
super_pete:
  postgres_user.present:
    - password: yumfudge
    - encrypted: True
    - user: postgres
    - superuser: True
```

Run salt-call with --log-level=INFO and notice there's a queries issued for each poop1-poop3 (and any other roles you might happen to have present). 

Reproduced with 2016.3.1.
