### ISSUE TITLE
salt develop: Mode management cannot be used in combination with 'contents', 'contents_pillar', or 'contents_grains'

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#35080]
### Question is this ok?

Latest salt from git has the following issue:
```
Mode management cannot be used in combination with 'contents', 'contents_pillar', or 'contents_grains'
```

tracked the issue to this commit: https://github.com/saltstack/salt/commit/44d60a3252cbeefa1defd102cd0c452776aea400

### Setup
salt running git version: 2016.3.0-1006-gec82151
added salt-formula users to config

### Steps to Reproduce Issue
run salt-call state.apply users

```
local:
----------
          ID: users_authorized_keys_root
    Function: file.managed
        Name: /root/.ssh/authorized_keys
      Result: False
     Comment: Mode management cannot be used in combination with 'contents', 'contents_pillar', or 'contents_grains'
     Started: 22:39:58.617532
    Duration: 0.521 ms
     Changes:
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.0-1006-gec82151
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: 6.0.2.post20160705
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.6
          ioflo: 1.6.0
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.4.5
       M2Crypto: 0.24.0
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: 0.3.7
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.6.4-1-ARCH
         system: Linux
        version: Not Installed
```
