### ISSUE TITLE
ssh_auth source fails with s3 source

### ISSUE THREAD

**Issue by ariscn** [saltstack/salt#35107]
Running latest 2016.3.1 on master and minion, Ubuntu 14.04.

```
test:
  ssh_auth.present:
    - user: test
    - source: s3://bucket/folder/key.pub
```

This fails with an error about being unable to get the file from s3. `s3.key` and `s3.keyid` are set, and other states are able to fetch files from the same bucket and folder. As a sanity check, I swapped this for:

```
/home/test/.ssh/authorized_keys:
  file.managed:
    - source: s3://bucket/folder/key.pub
    - source_hash: sha256=thehash
    - user: test
    - group: test
```

This worked. So, the issue is in ssh_auth's interaction with s3 sources.

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this behavior:

```
DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: test
    Function: ssh_auth.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/home/ch3ll/git/salt/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/home/ch3ll/git/salt/salt/loader.py", line 1651, in wrapper
                  return f(*args, **kwargs)
                File "/home/ch3ll/git/salt/salt/states/ssh_auth.py", line 290, in present
                  saltenv=__env__)
                File "/home/ch3ll/git/salt/salt/modules/cp.py", line 336, in get_url
                  return _client().get_url(path, None, False, saltenv, no_cache=True)
                File "/home/ch3ll/git/salt/salt/fileclient.py", line 613, in get_url
                  'Could not fetch from {0}. Exception: {1}'.format(url, exc)
              MinionError: Could not fetch from s3://test/test.pub. Exception: syntax error: line 1, column 0
     Started: 14:31:00.905611
    Duration: 336.265 ms
     Changes:   
----------
          ID: /tmp/authorized_keys
    Function: file.managed
      Result: True
     Comment: File /tmp/authorized_keys is in the correct state
     Started: 14:31:01.245826
    Duration: 10.304 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
```

using the following sls file:

```
test:
  ssh_auth.present:
    - user: test
    - source: s3://test/test.pub

/tmp/authorized_keys:
  file.managed:
    - source: s3://test/test.pub
    - user: ch3ll
    - group: ch3ll
    - skip_verify: True
```

I tested this on 2016.3.2 as well.
