### ISSUE TITLE
Salt reactor unable to use route53 state

### ISSUE THREAD

**Issue by alexshemesh** [saltstack/salt#35126]
### Description of Issue/Question

I'm trying to create DNS record in AWS Route 53 for instance that ive created using Salt Cloud.
Im unable to use  boto_route53.present state. 
### Setup

This is in my master file.

```
reactor:
    - 'salt/cloud/*/deploy_script':
        - '/etc/salt/master.d/reactor/route53.sls'
```

This is the content of my route53.sls file

```
mycnamerecord:
  boto_route53.present:
    - name: {{ data['name'] }}.
    - value: {{ data['host'] }}
    - zone: mydns.com.
    - ttl: 60
    - record_type: A
    - region: us-west-2
    - keyid: <AWSID>
    - key: <AWSKEY>
```

In the log of master i can see following error
### Steps to Reproduce Issue

I deploy instance using map with single instance (this is for testing only)
This how my map looks

```
ec2_west_small_prod:
    - testdocker1.dev.il.algopix.com
```

Traceback (most recent call last):

```
 File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 613, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 241, in run
    self.call_reactions(chunks)
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 198, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 269, in run
    l_fun = getattr(self, low['state'])
AttributeError: 'ReactWrap' object has no attribute 'boto_route53'
```
### Versions Report

Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by UtahDave** [comment]
Hi Alex,

The reactor sls files need to be formatted differently than regular state files. You need a minion to execute the state. For this example I'm going to assume you have a minion running on the same VM as your master and that the minion's name is 'masterminion'.

```
mycnamerecord:
  local.state.apply:
    - tgt: masterminion
    - arg:
      - boto_route53.present:
    - kwarg:
      - name: {{ data['name'] }}.
      - value: {{ data['host'] }}
      - zone: mydns.com.
      - ttl: 60
      - record_type: A
      - region: us-west-2
      - keyid: <AWSID>
      - key: <AWSKEY>
```

I haven't tested this, but your reactor sls file should look something like the above. What are your results with that?

**Comment by peterclearmetal** [comment]
@UtahDave your example got me close enough to actually get a working salt-cloud reactor going to auto-manage route53 dns entries for minions spun with salt-cloud.

route53_present.sls
````
create_A_record:
  local.state.single:
    - tgt: masterminion
    - arg:
      - boto_route53.present
      - name={{ data['name'] }}.
      - value={{ data['host'] }}
      - record_type=A
      - zone=mydns.com.
      - ttl=300
````

route53_absent.sls
````
remove_A_record:
  local.state.single:
    - tgt: masterminion
    - arg:
      - boto_route53.absent
      - name={{ data['name'] }}.
      - record_type=A
      - zone=mydns.com.
````

master.conf
````
reactor:
  - 'salt/cloud/*/deploy_script':
    - /srv/reactor/route53_present.sls
  - 'salt/cloud/*/destroyed':
    - /srv/reactor/route53_absent.sls
````

I couldn't ever get kwargs to work, even when executing `salt-call state.single` but that may actually be #35251.  I use IAM roles so I don't need the hard coded keys.

Btw, is there some location for salt reactor examples like this? The [reactor documentation](https://docs.saltstack.com/en/latest/topics/reactor/) includes a couple simple ones, but I spent an inappropriate quantity of time getting this working because I couldn't really find any reactor examples.

I think this issue is likely OK to close.

**Comment by notpeter** [comment]
@UtahDave your example got me close enough to actually get a working salt-cloud reactor going to auto-manage route53 dns entries for minions spun with salt-cloud.

route53_present.sls
````
create_A_record:
  local.state.single:
    - tgt: masterminion
    - arg:
      - boto_route53.present
      - name={{ data['name'] }}.
      - value={{ data['host'] }}
      - record_type=A
      - zone=mydns.com.
      - ttl=300
````

route53_absent.sls
````
remove_A_record:
  local.state.single:
    - tgt: masterminion
    - arg:
      - boto_route53.absent
      - name={{ data['name'] }}.
      - record_type=A
      - zone=mydns.com.
````

master.conf
````
reactor:
  - 'salt/cloud/*/deploy_script':
    - /srv/reactor/route53_present.sls
  - 'salt/cloud/*/destroyed':
    - /srv/reactor/route53_absent.sls
````

I couldn't ever get kwargs to work, even when executing `salt-call state.single` but that may actually be #35251.  I use IAM roles so I don't need the hard coded keys.

Btw, is there some location for salt reactor examples like this? The [reactor documentation](https://docs.saltstack.com/en/latest/topics/reactor/) includes a couple simple ones, but I spent an inappropriate quantity of time getting this working because I couldn't really find any reactor examples.

I think this issue is likely OK to close.
