### ISSUE TITLE
file.append always results in change

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#35121]
### Description of Issue/Question
While testing the 2016.3.2 package I noticed my file.append always triggers a change on my minions running 2016.3.2, not on those still running 2016.3.1!

### Setup
```yaml
######
## common.package.repo.pbd state
## -----------------------------------
## setup pkg.blackdot.be on SmartOS
######

## blackdot repository
{% if salt.grains.get('os', 'posix') == 'SmartOS' and salt.grains.get('virtual', 'physical') == 'zone' %}
package.repo.key::pkg.blackdot.be:
  file.managed:
    - name: /opt/local/etc/gnupg/keys/pbd.key
    - makedirs: true
    - source: salt://common/package/repo/_files/pbd-signature.key
  cmd.wait:
    - name: gpg --no-default-keyring --keyring /opt/local/etc/gnupg/pkgsrc.gpg --import /opt/local/etc/gnupg/keys/pbd.key
    - watch:
        - file: package.repo.key::pkg.blackdot.be

package.repo::pkg.blackdot.be:
  file.append:
    - name: /opt/local/etc/pkgin/repositories.conf
    - text: http://pkg.blackdot.be/packages/{{ salt.grains.get('pkgsrcversion') }}/x86_64/All
    - require:
        - cmd: package.repo.key::pkg.blackdot.be
  cmd.wait:
    - name: pkgin -fy up
    - watch:
        - file: package.repo::pkg.blackdot.be
{% endif %}

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
```

```yaml
          ID: package.repo::pkg.blackdot.be
    Function: file.append
        Name: /opt/local/etc/pkgin/repositories.conf
      Result: True
     Comment: File /opt/local/etc/pkgin/repositories.conf is in correct state
     Started: 08:44:04.391620
    Duration: 2.74 ms
     Changes:   
              ----------
              diff:
                  --- 
                  
                  +++ 
                  
                  @@ -5,7 +5,7 @@
                  
                   # Simply add repositories URIs one below the other
                   #
                   # WARNING: order matters, duplicates will not be added, if two
                  -# repositories hold the same package, it will be fetched from
                  +# repositories hold the same package, it will be fetched from 
                   # the first one listed in this file.
                   #
                   # This file format supports the following macros:
```
### Steps to Reproduce Issue
Snippet above, this one always triggers it.

### Versions Report
```yaml
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 6.0.1
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.5
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: 0.22
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, May  4 2016, 11:21:53)
   python-gnupg: 2.0.2
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.3
 
System Versions:
           dist:   
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed

```
