### ISSUE TITLE
dockerng: RepoTags not iterable with docker 1.12 on ubuntu 14.04

### ISSUE THREAD

**Issue by epelc** [saltstack/salt#35139]
### Description of Issue/Question
This line causes `docker.running` to fail when using docker 1.12
https://github.com/saltstack/salt/blob/485dd07fe9b6d32cf0e9f284a71fa512d7508a6b/salt/modules/dockerng.py#L2352

Minion error log
http://pastebin.com/mKivKRLa

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
run:
  dockerng.running:
# the tag is important. It may not be triggered if you use the default latest. The error is in the tag lookup code.
    - image: me/my-image:my-tag
    - command: some-command
    - detach: True
    - restart_policy: always
    - environment:
      {% for key, value in pillar['config'].iteritems() %}
      - '{{ key }}': '{{ value }}'
      {% endfor %}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Run a state using `docker.running` with an image that has a specific tag.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-86-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by mikesager** [comment]
I've just run into this same issue and found this issue during my search.  I've been at it for a few minutes and I think I have info to help.  Run `docker images` and see if there are any entries with `<none>` in the `TAG` column.  That seems to be why it's choking.  I suppose there just needs to be a test for this condition, but I'm not familiar with the codebase nor am I grokking Python beyond a basic level, so this is the extent of my contribution.  As a temporary workaround, you can delete the non-tagged image with `docker rmi <image ID>`.  Hope that helps!

**Comment by Ch3LL** [comment]
@epelc can you check if you indeed are running into the same behavior as @mikesager ? do you have any images with none in the tag column. I'm not able to replicate this behavior on a clean setup using this state file:

```
run:
  dockerng.running:
    - image: ubuntu:12.04
    - command: echo "hello"
    - detach: True
    - restart_policy: always
```

So it seems that might be the key factor into why you are running into that issue.
