### ISSUE TITLE
Specified sha512 checksum does not match after upgrade to 2016.3.2

### ISSUE THREAD

**Issue by mikemcrill** [saltstack/salt#35168]
### Description of Issue/Question
SHA512 checksums are not working for file.managed in S3 buckets as of 2016.3.2.  Complains about the checksum not matching, but it does match and was working prior to the upgrade.

### Setup
Have a state which has a file.managed from S3:
```
my_download:
  file.managed:
    - name: /tmp/file
    - source: s3://bucket/file
    - source_hash: sha512=s3://bucket/file.sha512
```

### Steps to Reproduce Issue
Use the above state, will receive this error:

` Comment: Specified sha512 checksum for s3://bucket/file (s3://bucket/file.sha512) does not match actual checksum (checksum)`

### Versions Report
```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@mikemcrill i am able to replicate this behavior:

```
my_download:
  file.managed:
    - name: /tmp/file
    - source: s3://ch3lltest/file
    - source_hash: md5=s3://ch3lltest/file.md5
```

2016.3.1:

```
[ch3ll@thecakeisalie salt]$ salt --version
salt 2016.3.1 (Boron)
[ch3ll@thecakeisalie salt]$ sudo salt-call --local state.sls issues.35168
local:
----------
          ID: my_download
    Function: file.managed
        Name: /tmp/file
      Result: True
     Comment: File /tmp/file is in the correct state
     Started: 11:12:45.222591
    Duration: 686.124 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

2016.3.2:

```
[ch3ll@thecakeisalie salt]$ salt --version
salt 2016.3.2 (Boron)
[ch3ll@thecakeisalie salt]$ sudo salt-call --local state.sls issues.35168
[ERROR   ] Specified md5 checksum for s3://ch3lltest/file (s3://ch3lltest/file.md5) does not match actual checksum (d8e8fca2dc0f896fd7cb4cb0031ba249)
local:
----------
          ID: my_download
    Function: file.managed
        Name: /tmp/file
      Result: False
     Comment: Specified md5 checksum for s3://ch3lltest/file (s3://ch3lltest/file.md5) does not match actual checksum (d8e8fca2dc0f896fd7cb4cb0031ba249)
     Started: 11:13:09.275591
    Duration: 613.051 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

For some reason I'm having a hard time runing a git bisect and trying to find the exact commit that broke this. But another thing to note is that i tested this in 2015.8. I tested from 2015.8.10-2015.8.5 and it wasn't working there either. Do you know if this was working for you in 2015.8?

**Comment by mikemcrill** [comment]
No, I couldn't tell you--I didn't have this state setup back then.

**Comment by cachedout** [comment]
I have this breaking here: 636d081ae07bd22e8b71a06743b8ab4fe87e8520

**Comment by terminalmage** [comment]
Looking.

**Comment by terminalmage** [comment]
According to the [documentation](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed), this is not the correct usage. When using a remote file source as the ``source_hash``, the hash_type isn't present.

Can you try without the ``sha512=`` in your SLS? It is possible that this was supported (but undocumented) usage in prior releases, and I unknowingly removed support for this syntax, not realizing it was supported.

**Comment by Ch3LL** [comment]
ahhh gotchya. Thanks for clarifying the usage. I was definitely confused because it was working on 2016.3.1. I went ahead and tested the following:

```
my_download:
  file.managed:
    - name: /tmp/file
    - source: s3://ch3lltest/file
    - source_hash: s3://ch3lltest/file.md5
```

Instead of 

```
    - source_hash: md5=s3://ch3lltest/file.md5
```

and its workign correctly. Also verified it works in 2015.8.11

@mikemcrill any luck for you?

**Comment by terminalmage** [comment]
@Ch3LL Did you make sure to test with a sha512 hash instead of md5? Your hash URL suggests an md5 hash.

So when source_hash is a file, we use the checksum length to determine the hash type. This is why the hash type shouldn't be needed. What it looks like is happening here is that my modifications assume that when you have ``- source_hash: sha512=<something>``, the part after the ``=`` is a hash, not necessarily a hash file. Hence the following error:

``Specified md5 checksum for s3://ch3lltest/file (s3://ch3lltest/file.md5) does not match actual checksum (d8e8fca2dc0f896fd7cb4cb0031ba249)``.

``s3://ch3lltest/file.md5`` is being identified as a hash and not a URL point to a hash file.

**Comment by Ch3LL** [comment]
just tested with sha512 as well shown here:

```
my_download:
  file.managed:
    - name: /tmp/file
    - source: s3://ch3lltest/file
    - source_hash: s3://ch3lltest/file.md5
my_download2:
  file.managed:
    - name: /tmp/file2
    - source: s3://ch3lltest/shafile
    - source_hash: s3://ch3lltest/shafile.sha512
```

which is working correctly :)

```
local:
----------
          ID: my_download
    Function: file.managed
        Name: /tmp/file
      Result: True
     Comment: File /tmp/file is in the correct state
     Started: 16:13:33.401173
    Duration: 880.478 ms
     Changes:   
----------
          ID: my_download2
    Function: file.managed
        Name: /tmp/file2
      Result: True
     Comment: File /tmp/file2 is in the correct state
     Started: 16:13:34.281870
    Duration: 856.783 ms
     Changes:   

Summary for local
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
```
