### ISSUE TITLE
`service.running` with enable & watch does not enable

### ISSUE THREAD

**Issue by mweinelt** [saltstack/salt#35220]
### Description of Issue/Question

The `service.running` state does ensure that the service is running, but not that its systemd units are being enabled. 
After commenting the `watch` statement the systemd unit enables properly. Is my logic flawed or salts?

Before highstate
```
    * bird.service - BIRD Internet Routing Daemon (IPv4)
       Loaded: loaded (/lib/systemd/system/bird.service; disabled)
       Active: active (running) since Thu 2016-08-04 20:47:00 CEST; 5h 30min ago
     Main PID: 2971 (bird)
       CGroup: /system.slice/bird.service
               `-2971 /usr/sbin/bird -f -u bird -g bird
```

Highstate
```
          ID: bird
    Function: service.running
      Result: True
     Comment: The service bird is already running
     Started: 02:17:55.580654
    Duration: 176.214 ms
     Changes:   
```

After highstate
```
    * bird.service - BIRD Internet Routing Daemon (IPv4)
       Loaded: loaded (/lib/systemd/system/bird.service; disabled)
       Active: active (running) since Thu 2016-08-04 20:47:00 CEST; 5h 32min ago
     Main PID: 2971 (bird)
       CGroup: /system.slice/bird.service
               `-2971 /usr/sbin/bird -f -u bird -g bird
```

### Setup
```
bird:
  pkgrepo.managed:
    - humanname: bird
    - name: deb http://bird.network.cz/debian/ jessie main
    - key_url: salt://bird/files/apt.key
    - require_in:
      - pkg: bird
  pkg.latest:
    - pkgs:
      - bird
  service.running:
    - enable: True
    - reload: True
    - watch:
      - file: /etc/bird/bird.conf
      - file: /etc/bird/bird.d/*
```

### Steps to Reproduce Issue
-

### Versions Report
```
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 4.6.0-0.bpo.1-amd64
         system: Linux
        version: debian 8.5 
```
