### ISSUE TITLE
Display meaningful error when attempting to use undefined pillar data

### ISSUE THREAD

**Issue by derekmaciel** [saltstack/salt#35242]
### Description of Issue/Question

Apply the following state to a minion on 2016.3:

```
{% set pkgname = pillar['dfgjkhdfgdfgdfg']['pkgname'] %}

install-my-pkg:
    pkg.installed:
        - name: {{ pkgname }}
```

And you will receive the cryptic error

```
my-salt-minion:
    Data failed to compile:
----------
    Rendering SLS 'base:myteststate' failed: Jinja variable 'salt.utils.context.NamespacedDictWrapper object' has no attribute 'dfgjkhdfgdfgdfg'
```

In this example it is obvious, but oftentimes our pillar ID is a name often used in our states, such as the name of the service we are provisioning, in which case this error does not make much sense at first. It could be improved to something like `Rendering SLS 'base:myteststate failed: Jinja variable 'pillar' has no attribute 'dfgjkhdfgdfgdfg'`
