### ISSUE TITLE
When I execute a state, failed, Reason: 'git.checkout' is not available

### ISSUE THREAD

**Issue by JerrySLau** [saltstack/salt#35252]
### Description of Issue/Question
When I test my state 
```
test:
  pkg.installed:
     - pkgs:
       - curl
 test2:
   git.checkout:
     - cwd: /home/liushipu/tengyue
     - rev: master
     - user: liushipu
```
salt returns:

```
          ID: test
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 15:57:00.434196
    Duration: 721.431 ms
     Changes:
----------
          ID: test2
    Function: git.checkout
      Result: False
     Comment: State 'git.checkout' was not found in SLS 'folder1/test'
              Reason: 'git.checkout' is not available.
     Started:
    Duration:
     Changes:
```
I run salt directly from cmd, it works

```
salt '*' git.checkout /home/liushipu/tengyue rev=master  user=liushipu
dev1.office.tengyue360.com:
    Already on 'master'
```
### Setup
here's minon's grains

```
2-    ----------
3-    SSDs:
4:    biosreleasedate:
5-        11/19/2015
6:    biosversion:
7-        0503
8-    cab_u:
157-    groupname:
158-        root
159:    host:
160-        dev1
161-    hwaddr_interfaces:
213-        detectedencoding:
214-            UTF-8
215:    localhost:
216-        dev1.office.tengyue360.com
217-    lsb_distrib_codename:
234-    num_gpus:
235-        1
236:    os:
237-        CentOS
238:    os_family:
239-        RedHat
240:    osarch:
241-        x86_64
242:    oscodename:
243-        CentOS Linux 7 (Core)
244:    osfinger:
245-        CentOS Linux-7
246:    osfullname:
247-        CentOS Linux
248:    osmajorrelease:
249-        7
250:    osrelease:
251-        7.2.1511
252:    osrelease_info:
253-        - 7
254-        - 2
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

#### master versions:
```
Salt Version:
           Salt: 2016.3.2
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 3.2.5
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
#### minion versions:
```
Salt Version:
           Salt: 2016.3.2
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 3.2.5
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
