### ISSUE TITLE
ssh_known_hosts.present is not idempotent in test=true with port

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#35264]
### Description of Issue/Question

Salt doesn't check for ssh key existence properly in test mode when port is set. The reason for this is that when port is specified, `known_hosts` file has entries formatted as `[host]:port`, not as `host`. It works ok outside of test mode.

I can fix it myself if this makes sense.

### Setup

```yaml
/some/path/know_hosts-foo:
  ssh_known_hosts.present:
    - name: foo.example.com
    - port: 7999
    - user: root
    - config: /some/path/know_hosts
    - enc: ssh-rsa
    - fingerprint: de:ad:be:ef
    - hash_known_hosts: false
```

### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed

System Versions:
           dist: debian 8.5
        machine: x86_64
        release: 4.4.14-cloudflare
         system: Linux
        version: debian 8.5
```
