### ISSUE TITLE
boto_elb state not updating health_check for TCP/SSL targets

### ISSUE THREAD

**Issue by Lomexian** [saltstack/salt#35272]
### Description of Issue/Question
When setting Health_check target to 'TCP:xxxx' or 'SSL:xxxx', load balancer will be created but healthcheck is incorrect.  It creates a TCP healthcheck with default settings and the first listener port.

errors during highstate with:
`Comment: ELB devlogstash created. Set attributes on ELB devlogstash. Failed to set health check on ELB devlogstash.`

Error in minion log file is:
```
[DEBUG   ] BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>
    <Message>HealthCheck Target must specify a port number</Message>
  </Error>
  <RequestId>3dea3be6-5d70-11e6-8138-2f3cab421899</RequestId>
</ErrorResponse>
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
testelb:
  boto_elb.present:
    - name: test
    - region: eu-west-1
    - scheme: internet-facing
    - availability_zones:
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
    - listeners:
      - elb_port: 1234
        instance_port: 1234
        elb_protocol: SSL
        instance_protocol: SSL
        certificate: '<cert>'
      - elb_port: 1235
        instance_port: 1235
        elb_protocol: SSL
        instance_protocol: SSL
        certificate: '<cert>'
    - health_check:
        target: 'SSL:1254/'
        healthy_threshold: 5
        unhealthy_threshold: 2
        interval: 30
        timeout: 5
    - attributes:
        cross_zone_load_balancing:
          enabled: true
        connecting_settings:
          idle_timeout: 60
    - security_groups:
      - sg-abcdefg
    - profile: fred
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
Boto is 2.42
