### ISSUE TITLE
Yum pkg command now fails

### ISSUE THREAD

**Issue by z900collector** [saltstack/salt#35291]
Just found: Add VirtuozzoLinux is yumpkg enable list. #34878 so this may be fixed?

```
salt 'hw38.*' pkg.list_pkgs
hw38.conetix.com.au:
    Module 'pkg' is not available.
ERROR: Minions returned with non-zero exit code
```

Previously worked fine for 2 years and now returns this error on 7 nodes out of 8. Config file on minion is default with master: line set accordingly. Server is CloudLinux running Virtuozzo Containers. salt-minion service restarted several times. 

The only issue I can find is that on the **working** node the line:

```
            Salt: 2015.5.10
             Python: 2.6.6 (r266:84292, Jul 29 2015, 18:30:53)
             **Jinja2: unknown**
           M2Crypto: 0.20.2
  ....
```
 
```
uname -a
Linux hw38 2.6.32-042stab111.12 #1 SMP Thu Sep 17 11:38:20 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
yum list all | wc -l
23741
```

```
salt 'hw38.*' test.versions_report
hw38.conetix.com.au:
               Salt: 2015.5.10
             Python: 2.6.6 (r266:84292, Feb  4 2016, 23:36:41)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: Not Installed
            Tornado: Not Installed
            timelib: Not Installed
           dateutil: Not Installed
root@salt:~# 
```
