### ISSUE TITLE
pkgin not detected as pkg provider on SmartOS

### ISSUE THREAD

**Issue by nigelsnapsecurity** [saltstack/salt#35330]
### pkgin is not detected as pkg provider on SmartOS

After forcing the selection in the minion configuration as described ([here](https://docs.saltstack.com/en/latest/ref/modules/index.html#module-provider-override)) the pkg installation (squid using the [squid formula](https://github.com/saltstack-formulas/squid-formula/blob/master/squid/init.sls)) worked fine.

Salt master and minion were installed using pkgin to install python modules that were available and then using pip to install salt.
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Using the salt-formula for squid with the following added to the map.jinja

```
    'SmartOS': {
        'pkgs': ['squid'],
        'service': ['squid'],
        'conf_dir': '/opt/local/etc/squid',
        'conf_file': 'squid.conf',
        'cache': '/var/squid/cache',
     },
```

`uname -a` is `SunOS configmaster0 5.11 joyent_20160616T055400Z i86pc i386 i86pc Solaris`

base image is _SmartOS base-multiarch 16.2.0_.  Image uuid is `9fb3cf88-49a0-11e6-8407-0be269553017` from images.joyent.com.

```
[root@configmaster0 /data/salt]# salt 'a46af0c8-2c46-c493-a8f2-f14a27492279' grains.items
a46af0c8-2c46-c493-a8f2-f14a27492279:
    ----------
    cpu_flags:
        - rdseed
        - adx
        - avx2
        - fma
        - bmi2
        - bmi1
        - rdrand
        - f16c
        - vmx
        - avx
        - xsave
        - pclmulqdq
        - aes
        - movbe
        - sse4.2
        - sse4.1
        - ssse3
        - popcnt
        - tscp
        - cx16
        - sse3
        - sse2
        - sse
        - fxsr
        - mmx
        - cmov
        - amd_sysc
        - cx8
        - tsc
        - fpu
    cpu_model:
        Intel(r) Xeon(r) CPU D-1540 @ 2.00GHz
    cpuarch:
        amd64
    datacenter:
        ca-east-3
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 8.8.8.8
            - 8.8.4.4
            - 172.28.0.5
        ip6_nameservers:
        nameservers:
            - 8.8.8.8
            - 8.8.4.4
            - 172.28.0.5
        search:
            - local
    domain:
    fqdn:
        configmaster0
    fqdn_ip4:
    fqdn_ip6:
    gid:
        0
    gpus:
    groupname:
        root
    host:
        configmaster0
    hwaddr_interfaces:
        ----------
        net0:
            02:00:00:45:92:8e
        net1:
            90:b8:d0:51:58:3d
        net2:
            90:b8:d0:1d:fc:7b
    hypervisor_uuid:
        00000000-0000-0000-0000-0cc47a7b58f8
    id:
        a46af0c8-2c46-c493-a8f2-f14a27492279
    imageversion:
        base-multiarch 16.2.0
    ip4_interfaces:
        ----------
        lo0:
            - 127.0.0.1
        net0:
            - 172.28.206.23
        net1:
            - 172.28.2.4
        net2:
            - 172.28.0.60
    ip6_interfaces:
        ----------
        lo0:
            - ::1
        net0:
        net1:
        net2:
    ip_interfaces:
        ----------
        lo0:
            - 127.0.0.1
            - ::1
        net0:
            - 172.28.206.23
        net1:
            - 172.28.2.4
        net2:
            - 172.28.0.60
    ipv4:
        - 127.0.0.1
        - 172.28.206.23
        - 172.28.0.60
        - 172.28.2.4
    ipv6:
        - ::1
    kernel:
        SunOS
    kernelrelease:
        5.11
    locale_info:
        ----------
        defaultencoding:
            None
        defaultlanguage:
            None
        detectedencoding:
            ascii
    localhost:
        configmaster0
    master:
        172.28.2.4
    mdata:
        ----------
        test:
            123
    mem_total:
        512
    nodename:
        configmaster0
    num_cpus:
        16
    num_gpus:
        0
    os:
        SmartOS
    os_family:
        Solaris
    osarch:
        amd64
    osfinger:
        SmartOS-20160616T055400Z
    osfullname:
        SmartOS
    osmajorrelease:
        20160616T055400Z
    osrelease:
        20160616T055400Z
    osrelease_info:
        - 20160616T055400Z
    path:
        /usr/sbin:/usr/bin:/bin:/sbin:/usr/local/bin
    pid:
        27149
    pkgsrcpath:
        http://pkgsrc.joyent.com/packages/SmartOS/2016Q2/multiarch/All
    pkgsrcversion:
        2016Q2
    ps:
        /usr/ucb/ps auxwww
    pythonexecutable:
        /opt/local/bin/python2.7
    pythonpath:
        - /opt/local/bin
        - /opt/local/lib/python27.zip
        - /opt/local/lib/python2.7
        - /opt/local/lib/python2.7/plat-sunos5
        - /opt/local/lib/python2.7/lib-tk
        - /opt/local/lib/python2.7/lib-old
        - /opt/local/lib/python2.7/lib-dynload
        - /opt/local/lib/python2.7/site-packages
    pythonversion:
        - 2
        - 7
        - 11
        - final
        - 0
    saltpath:
        /opt/local/lib/python2.7/site-packages/salt
    saltversion:
        2016.3.2
    saltversioninfo:
        - 2016
        - 3
        - 2
        - 0
    server_id:
        1478084492
    shell:
        /bin/sh
    uid:
        0
    username:
        root
    virtual:
        zone
    zmqversion:
        4.1.4
    zoneid:
        4063
    zonename:
        a46af0c8-2c46-c493-a8f2-f14a27492279
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
The output of the failure to the console on highstate.  I do not currently have debug logs showing this.  I will post these tomorrow if required.

```
          ID: squid_pkgs
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'squid'
              Reason: 'pkg' __virtual__ returned False
     Started:
    Duration:
     Changes:
```
### Versions Report

Master and Minion are the same vm and are using the same pip installed salt as described above.

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Jul  2 2016, 00:22:45)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.4

System Versions:
           dist:
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
