### ISSUE TITLE
DDNS update existing record even if record exists

### ISSUE THREAD

**Issue by deniszh** [saltstack/salt#35350]
### Description of Issue/Question
In latest stable and develop Salt ddns state module is broken - it updates DNS record every time, even if record exists.

### Setup
```
ensure-a-record:
  ddns.present:
    - name: {{ grains['host'] }}
    - zone: {{ grains['domain'] }}
    - ttl: 600
    - data: {{ grains['ipv4'][0] }}
    - rdtype: A
    - nameserver: {{ local_ns }}
    - keyfile: /etc/ddns/key.json
    - require:
      - file: /etc/ddns/key.json
      - pkg: python-dnspython
```
Running state above updates dns record every time, despite TTL 600

### Versions Report
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-71-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
