### ISSUE TITLE
aggregate: True overrides aggregate: False

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#35426]
### Description of Issue/Question

We have a pretty complicated series of includes to implement a set of inter-related formulae. All but one of these includes specifies aggregate: False in the pkg.installed states. The one which includes an aggregate: True causes all the other aggregate: False entries to be ignored.

I think this is the wrong order of operations. An explicit aggregate: False should _always_ be respected.
### Versions Report

2016.3.2

**Comment by Ch3LL** [comment]
I believe I am able to replicate this. Can you please confirm my test case:

pkg1.sls:

```
include:
  - pkg2

pkg1:
  pkg.installed:
    - aggregate: False

pkg1_a:
  pkg.installed:
    - aggregate: False
```

pkg2.sls:

```
pkg2:
  pkg.installed:
    - aggregate: True
pkg2_a:
  pkg.installed:
    - aggregate: True
```

And in the logs I see the following:

```
2016-08-15 12:25:45,669 [salt.loaded.int.module.cmdmod][ERROR   ][18181] Command '['dnf', '-y', '--best', '--allowerasing', 'install', 'pkg2_a', 'pkg2', 'pkg1_a', 'pkg1']' failed with return code: 1
```
