### ISSUE TITLE
200 processes of salt-master (2016.3.2)

### ISSUE THREAD

**Issue by jelenak** [saltstack/salt#35480]
### Description of Issue/Question

```
$ salt-master --version
salt-master 2016.3.2 (Boron)
$ ps aux | grep salt-master | wc -l
200
```
### Steps to Reproduce Issue
1. Install salt-master 2016.3.2
2. Salt master config:

```
worker_threads: 96

cachedir: /tmp/salt/master
timeout: 45
minion_data_cache: True
file_roots:
  base:
    - /salt/states

pillar_roots:
  base:
    - /salt/pillars

```
### Versions Report

```
root@b621993b659e:/# salt-master --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-32-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
