### ISSUE TITLE
HipChat returner configuration doesn't work as documented

### ISSUE THREAD

**Issue by jbouse** [saltstack/salt#35506]
### Description of Issue/Question

Following the [HipChat Returner](https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.hipchat_return.html) documentation it doesn't match up with reality apparently.
### Setup

Setup the following /etc/salt/minion.d/returners.conf:

``` YAML
hipchat:
  color: random
  notify: true
  profile: hipchat_profile
  room_id: 12345
hipchat_profile:
  api_key: XXX-REDACTED-XXX
  api_version: v2
  from_name: SaltStack
```

I also tried with my older v1 API:

``` YAML
hipchat:
  color: random
  notify: true
  profile: hipchat_profile
  room_id: 12345
hipchat_profile:
  api_key: XXX-REDACTED-XXX
  api_version: v1
  from_name: SaltStack
```
### Steps to Reproduce Issue

Attempt to perform:

salt-call test.ping --return hipchat

Both return:

```
[ERROR   ] hipchat.from_name not defined in salt config
local:
    True
```

Now if I change the returners.conf to be as follows:

``` YAML
hipchat.color: random
hipchat.notify: true
hipchat.room_id: 12345
hipchat.api_key: XXX-REDACTED-XXX
hipchat.api_version: v2
hipchat.from_name: SaltStack
```

Then re-execute the same command it works successfully.
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
```

**Comment by jbouse** [comment]
Of note it also fails in the same fashion for the Slack returner as well and the only commonality I can find seems to be in the _get_options() function where it calls out to salt.returners.get_returner_options() in both cases.

**Comment by Ch3LL** [comment]
@jbouse looks like we need to get this fixed up. Was this working previously in 2015.8? Also just curious would you mind trying to setup the configuration without the `hipchat_profile`. Jsut trying to see if maybe the issues lies pointing to a profile or not? Thanks

**Comment by jbouse** [comment]
@Ch3LL It has never worked without prefixing each variable with "hipchat." and not using the "Alternative" configuration method as described for either Slack or HipChat. I even removed the use of the profile and simply put it all under "hipchat:" and it didn't work.

I suspect the issue lies within [```salt.returners.__init__```](https://github.com/saltstack/salt/blob/develop/salt/returners/__init__.py) but I can't isolate the exact reason but this was the only commonality between both Slack and HipChat returners that both behave the same way.

**Comment by jbouse** [comment]
@Ch3LL I stand corrected... I went back and changed one of my minions to the following:

```
hipchat:
  api_key: XXX-REDACTED-XXX
  api_version: v2
  color: random
  from_name: SaltStack
  notify: true
  room_id: 12345
slack:
  api_key: XXX-REDACTED-XXX
  as_user: true
  channel: '#saltstack'
  username: saltstack
  yaml_format: true
```

It does in fact work with that configuration option, so it does look like the issue is in pointing to the profile
