### ISSUE TITLE
Salt state schedule.present does not fail with invalid date in "when"

### ISSUE THREAD

**Issue by sastorsl** [saltstack/salt#35558]
### Description of Issue/Question

Salt state schedule.present with the "when" keyword and an invalid time/date does not abort the state.
The state finishes with success, but the minion logs fills up with error messages and the scheduled job will not run.

```
2016-08-18 13:24:30,507 [salt.utils.schedule][ERROR   ][29146] Invalid date string garbage. Ignoring job job2
```
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

```
job2:
  schedule.present:
    - function: cmd.run
    - job_args:
      - 'date >> /tmp/date.log'
    - when:
        - 01:00am
        - 12:00am
        - garbage
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by Ch3LL** [comment]
@sastorsl I was able to replicate this behavior on 2016.3.2 with the following state:

```
job2:
  schedule.present:
    - function: cmd.run
    - job_args:
      - 'date >> /tmp/date.log'
    - argumentdoesnotexist: nopeitdoesnt
```

I would expect it to error out especially with the  `argumentdoesnotexist` set. But I get clean results back:
