### ISSUE TITLE
pkg.install state not working in reactor with parameters != name

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#35556]
Running latest Debian/Saltstack:

```
root@salt-euc1-01:~# lsb_release -d
Description:    Debian GNU/Linux 8.5 (jessie)
root@salt-euc1-01:~# salt-call --version
salt-call 2016.3.2 (Boron)
```

When I try to setup the latest working boto package by salt filehandler for Debjan Jessie which isn't anymore in the repositories:

```
05-python-boto:
  local.pkg.install:
    - name: setup required python-boto package
    - arg:
      - sources:
          - python-boto: salt://system/files/python-boto_2.38.0-1_all.deb
      - allow_updates: True
      - reload_modules: True
    - tgt: {{ data['id'] }}
    - queue: True
  #local.saltutil.refresh_modules:
  #  - async: True
  #  - tgt: {{ data['id'] }}
  #  - queue: True
```

I run into a salt error:

```
root@salt-euc1-01:~# salt-run jobs.list_job 20160818103139875633
Arguments:
    |_
      ----------
      sources:
          |_
            ----------
            python-boto:
                salt://system/files/python-boto_2.38.0-1_all.deb
    |_
      ----------
      allow_updates:
          True
    |_
      ----------
      reload_modules:
          True
Function:
    pkg.install
Minions:
    - test-euc1-01
Result:
    ----------
    test-euc1-01:
        ----------
        out:
            nested
        return:
            The minion function caused an exception: Traceback (most recent call last):
              File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1320, in _thread_return
                return_data = executor.execute()
              File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
                return self.func(*self.args, **self.kwargs)
              File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 525, in install
                name, pkgs, sources, **kwargs
              File "/usr/lib/python2.7/dist-packages/salt/modules/pkg_resource.py", line 157, in parse_targets
                packed = dict([(_normalize_name(x), None) for x in name.split(',')])
            AttributeError: 'dict' object has no attribute 'split'
...
```

When I was searching for already opened issues/hints what parameters to set I found this snippet:
https://docs.saltstack.com/en/getstarted/event/reactor.html

```
install cowsay on myminion:
  local.pkg.install:
    - tgt: 'myminion'
    - arg:
      - cowsay
```

with optional hint written below of it:

```
Additionally, arguments to be passed to the module are also passed using the arg or kwarg (not kwargs) parameter.
```

which could explain also the error... the function seems to put all arguments as name option and didn't switch when other parameters are given.

Idea was that I have to use e.g. optional parameters like kwarg like also found  in above documentation snippet but I didn't see such parameter in the event messages?

```
salt/job/20160818103139875633/new       {
    "_stamp": "2016-08-18T10:31:39.876155",
    "arg": [
        {
            "sources": [
                {
                    "python-boto": "salt://system/files/python-boto_2.38.0-1_all.deb"
                }
            ]
        },
        {
            "allow_updates": true
        },
        {
            "reload_modules": true
        }
    ],
    "fun": "pkg.install",
    "jid": "20160818103139875633",
    "minions": [
        "test-euc1-01"
    ],
    "tgt": "test-euc1-01",
    "tgt_type": "glob",
    "user": "root"
}
salt/job/20160818103139875633/ret/test-euc1-01        {
    "_stamp": "2016-08-18T10:31:40.220880",
    "cmd": "_return",
    "fun": "pkg.install",
    "fun_args": [
        {
            "sources": [
                {
                    "python-boto": "salt://system/files/python-boto_2.38.0-1_all.deb"
                }
            ]
        },
        {
            "allow_updates": true
        },
        {
            "reload_modules": true
        }
    ],
    "id": "test-euc1-01",
    "jid": "20160818103139875633",
    "out": "nested",
    "return": "The minion function caused an exception: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/salt/minion.py\", line 1320, in _thread_return\n    return_data = executor.execute()\n  File \"/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py\", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File \"/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py\", line 525, in install\n    name, pkgs, sources, **kwargs\n  File \"/usr/lib/python2.7/dist-packages/salt/modules/pkg_resource.py\", line 157, in parse_targets\n    packed = dict([(_normalize_name(x), None) for x in name.split(',')])\nAttributeError: 'dict' object has no attribute 'split'\n",
    "success": false
}
_salt_error     {
    "_stamp": "2016-08-18T10:31:40.223396",
    "cmd": "_minion_event",
    "data": {
        "_stamp": "2016-08-18T10:31:40.209747",
        "args": [
            "The minion function caused an exception"
        ],
        "message": "The minion function caused an exception"
    },
    "id": "test-euc1-01",
    "pretag": null,
    "tag": "_salt_error"
}
```

and that didn't change if I setup state to:

```
05-python-boto:
  local.pkg.install:
    - kwarg:
        - sources:
            - python-boto: salt://system/files/python-boto_2.38.0-1_all.deb
        - allow_updates: True
        - reload_modules: True
    - tgt: {{ data['id'] }}
    - queue: True
```

```
salt/job/20160818110316137820/new       {
    "_stamp": "2016-08-18T11:03:16.138324",
    "arg": [],
    "fun": "pkg.install",
    "jid": "20160818110316137820",
    "minions": [
        "test-euc1-01"
    ],
    "tgt": "test-euc1-01",
    "tgt_type": "glob",
    "user": "root"
}
salt/job/20160818110316137820/ret/test-euc1-01        {
    "_stamp": "2016-08-18T11:03:16.181811",
    "cmd": "_return",
    "fun": "pkg.install",
    "fun_args": [],
    "id": "test-euc1-01",
    "jid": "20160818110316137820",
    "retcode": 0,
    "return": {},
    "success": true
}
```

```
2016-08-18 11:03:16,145 [salt.minion      ][INFO    ][11252] User root Executing command pkg.install with jid 20160818110316137820
2016-08-18 11:03:16,145 [salt.minion      ][DEBUG   ][11252] Command details {'tgt_type': 'glob', 'jid': '20160818110316137820', 'tgt': 'test-euc1-01', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'pkg.install'}
2016-08-18 11:03:16,155 [salt.minion      ][INFO    ][11324] Starting a new job with PID 11324
2016-08-18 11:03:16,171 [salt.utils.lazy  ][DEBUG   ][11324] LazyLoaded pkg.install
2016-08-18 11:03:16,172 [salt.utils.lazy  ][DEBUG   ][11324] LazyLoaded direct_call.get
2016-08-18 11:03:16,172 [salt.loaded.int.module.pkg_resource][ERROR   ][11324] No package sources provided
2016-08-18 11:03:16,173 [salt.minion      ][DEBUG   ][11324] Minion return retry timer set to 6 seconds (randomized)
2016-08-18 11:03:16,173 [salt.minion      ][INFO    ][11324] Returning information for job: 20160818110316137820
```

**Comment by Reiner030** [comment]
perhaps it's related somehow to https://github.com/saltstack/salt/issues/20841 but before above states/errors I had tried it also with

```
05-python-boto:
  local.pkg.install:
    - sources:
        - python-boto: salt://system/files/python-boto_2.38.0-1_all.deb
    - allow_updates: True
    - reload_modules: True
    - tgt: {{ data['id'] }}
    - queue: True4
```
with result ```No package sources provided``` so the solution mentioned in other issue didn't fit here.

**Comment by Ch3LL** [comment]
@Reiner030 it looks to me that you are trying to run a state here because it looks like things like allow_updates and reload_moduels are state module specific. or are you actually trying to run the execution module pkg.install, because I'm not seeing teh allow_updates option. If you just want to run the pkg state module you could just use 

```
highstate_run:
  local.state.apply:
    - tgt: installpkg
```

And have installpkg.sls include your pkg state.

**Comment by Reiner030** [comment]
Hello @Ch3LL  I try here to install the "latest" working python-boto package *before* I let run the highstate. This is needed because instance uses boto function from Route53 in my case and the already setup state

```
python-boto:
  pkg.installed:
    - sources:
      - python-boto: salt://system/files/python-boto_2.38.0-1_all.deb
      #- python-boto: http://cloudfront.debian.net/debian/pool/main/p/python-boto/python-boto_2.38.0-1_all.deb
    - reload_modules: true
```
which has a "nice" bug in the reload_modules function which has celebrated its first anniversary 2 months ago in: https://github.com/saltstack/salt/issues/24925

Only a manual reload of salt-minion / manual call of salt-call would load the updated package.
Checking logfile show many errors because of the outdated python-boto package:
```
root@test-euc1-01:~$ sudo grep boto /var/log/salt/minion | grep require | grep -v OrderedDict | cut -d " " -f 3- | sort | uniq -c
     26 [salt.loaded.int.module.boto_kms][DEBUG   ][14423] boto_kms requires boto 2.38.0.
     26 [salt.loaded.int.module.boto_route53][ERROR   ][14423] boto_route53 requires at least boto 2.35.0.
```

I tested optionally these parameters:
```
        - allow_updates: True
        - reload_modules: True
```
to see if this helps to install package with reload. If not I was thinking about an event based salt-minion restart in creation phase.

Independent of my personal "interests" the reactor state for package installation is documented as written before on: https://docs.saltstack.com/en/getstarted/event/reactor.html as:
```
install cowsay on myminion:
  local.pkg.install:
    - tgt: 'myminion'
    - arg:
      - cowsay
```
so there is no reason why the arg &lt;package-name&gt; is working and the arg &lt;sources&gt; not...

When testing other event/states today and some month before also several boto functions I think I knew what the problem is... 
- Saltstack has common outputters which are designed equally for input but
- Saltstack is still missing a common "input" routine which can interpret *all* 
   states the same way for direct or also stacked module calls (stacked problems e.g.: Cloudwatch alarms and Route53 setups in ELB definitions)
