### ISSUE TITLE
Support for multiple SQS queues in sqs_events engine

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#35562]
Currently, [`sqs_events` engine](https://docs.saltstack.com/en/latest/ref/engines/all/salt.engines.sqs_events.html) only supports listening to a single queue. Workaround can be found [here](https://groups.google.com/d/msg/salt-users/KUsLVLp5O9g/78V4Y8rGAgAJ). This is a feature request to support multiple queues without doing the workaround of duplicating an engine.

See also https://groups.google.com/d/msg/salt-users/KUsLVLp5O9g/lOB3FDWeAgAJ.

**Comment by Ch3LL** [comment]
@JensRantil nice idea. Will approve as a feature request. Thanks

**Comment by JensRantil** [comment]
@Ch3LL Awesome! What does `RIoT` label mean?

**Comment by Ch3LL** [comment]
If you ever have any questions about how we choose our labels its all documented [here](https://docs.saltstack.com/en/latest/topics/development/labels.html#functional-group) 

But to answer your question specifically  we have separate teams that tackle different components on salt. The Riot team usually handles things like aws, salt-cloud, and api's. So riot team would be the one to most likely handle this feature request unless a community member were to fix it. Does that clear it up?

**Comment by JensRantil** [comment]
@ch3ll Perfectly, thanks!

**Comment by l2ol33rt** [comment]
@JensRantil you can define multiple `sqs_events` engines in your salt config:
```
engines:
  - sqs_events:
      queue: saltqueue
  - sqs_events:
      queue: newqueue
```
This works just fine for me on the `2016.3` branch. Hope that helps!

**Comment by JensRantil** [comment]
@l2ol33rt Didn't know! That solves my issue. Closing this.

**Comment by ugurengin** [comment]
is it possible to define multiple aws profile under the same config ?

I tried to apply it like below, but seems that couldn't work! 

engines:
  sqs_events:
    queue: saltstack
    profile: a-sqs-profile
  sqs_events:
    queue: saltstack
    profile: b-sqs-profile

**Comment by l2ol33rt** [comment]
@ugurengin `engines` entries need to be in a list, so something like:

```
engines:
  - sqs_events:
      queue: saltstack
      profile: a-sqs-profile
  - sqs_events:
      queue: saltstack
      profile: b-sqs-profile
```
