### ISSUE TITLE
file.copy makedirs creates root dirs

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#35595]
Given the following, we get a directory with root-only permission.

```
my_file:
  file.copy:
    - name: /not-there/my_file
    - source: /exists/my_file
    - user: me        # that's the relevant user
    - makedirs: True
```

Creates the following:

`/not-there` with root permissions
`/not-there/my_file` with user permissions

We need `/not-there` to be with user-permissions.
