### ISSUE TITLE
expand ~ to user home directory

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#35594]
For example:

```
my_file:
  file.managed:
    - name: ~/my_file
    - source: salt://my_file
    - user: {{ user }}
```

Would be great if '~' always expands to the desired home's directory (during the execution of the state). Same for file.copy etc.

Right now, it expands to '/root'.

This would also be great for 'cmd.run'.
