### ISSUE TITLE
Allow "multiple state declarations of the same type" when function is different

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#35592]
It would be great if one could do the following:

```
apache_sites:
  apache_site.enabled:
    - names:
      - my-server
      - your-server
  apache_site.disabled:
    - names:
      - 000-default
```

Right now, we circumvent the error by introducting another state such as:

```
apache_sites_enabled:
  apache_site.enabled:
    - names:
      - my-server
      - your-server

apache_sites_disabled:
  apache_site.disabled:
    - names:
      - 000-default
```

**Comment by Ch3LL** [comment]
@srkunze I believe this is a duplicate of #29142 . If you agree please feel free to close this issue and comment on #29142 and we will track this feature request there. Thanks

**Comment by srkunze** [comment]
@Ch3LL I looked that issue up already but it's not 100% the same I think.

They need 2x "apache_site.enabled". I need "apache_site.enabled" + "apache_site.disabled" which is different.

So, I let you the choice to close the issue if you think the internal implementation would be the same. :)

**Comment by Ch3LL** [comment]
Thanks for clarifying . Will add this as a feature request instead of treat as a duplciate thanks.

**Comment by wayne-weibel** [comment]
Glad to see that this is already in the queue.  Just wanted to add another (probably more common) example ... `file.managed` and `file.symlink`

**Comment by jktr** [comment]
I ran into this exact issue today, with the following use case:  `locale.present` and `locale.system`

**Comment by btorch** [comment]
same here trying to do:
```
diamond:
   file.directory: 
    .....
   file.managed:
   ....
```

**Comment by stduolc** [comment]
```
kafka-config-dir:
  file.absent:
    - name: /not/useful/dir
  file.directory:
    - name: /some/useful/dir
```

**Comment by jmcdaniel-z** [comment]
Ran into this as well using: 

```
lvm.pv_present:
  - name: /dev/xvdd
lvm.vg_present:
  - name: vol_grp1
lvm.lv_present:
  - name: logical_vol1
```

**Comment by tbennett6421** [comment]
I'd like this feature as well
```
/etc/ssh/sshd_config:
  file.uncomment:
    - regex: '.*AuthorizedKeysFile.*'

  file.replace:
    - pattern: '(.*LoginGraceTime.*)'
    - repl: 'LoginGraceTime 120'
    - show_changes: true 
```

**Comment by madfordmac** [comment]
Another use case:
```
Configure network time service:
  pkg.purged:
    - pkgs:
      - ntp
      - ntp-doc
      - ntpdate

  pkg.installed:
    - name: chrony
```

**Comment by naveen-rasiah** [comment]
One of the most 'in your face' features that should be added...but I'm guessing backwards compatibility limits this.

**Comment by faelin** [comment]
And another, possibly quite common use case!
```
edit some file two ways when needed:
  file.replace:
    - name: '/some/file/path'
    - pattern: 'replace_me'
    - repl: 'better_string'
  file.line:
    - name: '/same/file/path'
    - match: 'delete_this_string'
    - mode: delete
```

**Comment by benfiedler** [comment]
I would have liked to setup passwordless ssh keys to a repo host (without using 'id-rsa' for the keyfile) in one state

ssh_repo_passwordless:
  file.copy:
    - name: /root/.ssh/your_repo_rsa_priv
    - source: salt://sshkeys/your_repo_rsa_priv
    - user: root
    - group: root
    - mode: 0600
  file.append:
    - name: /root/.ssh/config
    - text: |
         Host your_repo your_repoIP
           HostName your_repoIP
           User repo_user
           IdentityFile /root/.ssh/your_repo_rsa_priv

**Comment by ssoto2** [comment]
additional case: 

the alternatives system: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.alternatives.html

```yaml
openjdk.set.java:
  alternatives.install:
    - name: java
    - link: /usr/bin/java
    - path: /usr/lib/jvm/java-1.7.0-openjdk.x86_64/bin/java
    - priority: 5
    - require:
      - pkg: openjdk.install
  alternatives.set:
    - name: java
    - path: /usr/lib/jvm/java-1.7.0-openjdk.x86_64/bin/java
```

**Comment by dsaard** [comment]
👍

**Comment by pbusquemdf** [comment]
Another use case:

```
/home/{{ user }}/.ssh/config:
  file.managed:
    - user: {{ user }}
    - mode: '0644'
    - makedirs: True
    - dir_mode: '0766'
    - source:

  file.append:
   - name: /home/{{ user }}/.ssh/config
   - text:
     - "Host: git.example.org"
     - "  IdentityFile /etc/salt/rsa.id"

```

file.append would create file with the wrong permission (aka root) if the files doesn't exist and you can't define that info. So you must run an empty manage that will create an empty file if absent with the proper permissions, then append logically follow.

**Comment by dsaard** [comment]
not stale

**Comment by cdalvaro** [comment]
👍

**Comment by Mukrosz** [comment]
Hello,

Is this still in the pipeline? Similar requirement:

```
install.salt.agent:
    pkg.refresh_db: []
    pkg.installed:
        - name: salt-minion
        - version: latest

```

Thanks,

**Comment by srkunze** [comment]
To us this is no longer a pressing issue as it is just a convenience feature is is actually not needed in more complex scenarios (which evolve when using salt a lot).

We also experienced confusion -- when reusing a state id -- among those who are not so experienced with salt but still need to write salt-sls-code. So, we would rather go the other way, removing reusing state names completely.

**Comment by srkunze** [comment]
I created a another issue: #57150 an let the community decide which way to go. :-)

**Comment by bsoldhogg** [comment]
Also run in to this with `locale.present` and `locale.system` and a few others.

**Comment by mariusvw** [comment]
Another use case where this might become handy:
```
/etc/rc.local:
  file.managed:
    - create: True
    - mode: 755
  file.prepend:
    - text: "#!/bin/sh -e"
  file.append:
    - name: /etc/rc.local
    - text: "exit 0"
  file.line:
    - name: /etc/rc.local
    - mode: ensure
    - before: "exit 0"
    - content: "/etc/init.d/somefancystuff restart"
```

**Comment by NotAProfessionalDeveloper** [comment]
Yep, I was trying to use file.keyvalue to update one of the config files of a service and file.append (which is in another format) to update another. Not possible :(

**Comment by faelin** [comment]
@NotAProfessionalDeveloper although there aren't many "hard and fast" rules for organizing your SLS scripts, the situation you have described might be more easily handled by two different State IDs:
```
file-to-update.conf:
  file.keyvalue
    - key: ...
    - value: ...

file-to-append.conf:
  file.append:
    - text: ...
```
Because these are two different files, the Salt standard would be to handle them as separate "steps" in your SLS file. This issue (#35592) was opened to address situations in which the changes enforced by a particular State would be considered one single operation on your local machine (for example, prepending and appending text to one file via a text-editor). Hypothetically, these changes could be managed by two states: `prepend-file` and `append-file`... but because states can reuse the State ID as the source-file/name/etc., and Salt won't let you _reuse_ a State ID, it becomes inconvenient to separate these two steps that should both be performed on a single file.

**Comment by NotAProfessionalDeveloper** [comment]
> @NotAProfessionalDeveloper although there aren't many "hard and fast" rules for organizing your SLS scripts, the situation you have described might be more easily handled by two different State IDs:
> 
> ```
> file-to-update.conf:
>   file.keyvalue
>     - key: ...
>     - value: ...
> 
> file-to-append.conf:
>   file.append:
>     - text: ...
> ```
> 
> Because these are two different files

Still, editing both files is part of the deployment of the same service: install the package, configure, start the service.

**Comment by faelin** [comment]
> Still, editing both files is part of the deployment of the same service: install the package, configure, start the service.

For the use case you describe, you should be using separate salt states with `require` keys:

```
some-package:
  pkg.installed

file-to-update.conf:
  file.keyvalue
    - key: ...
    - value: ...
    - require:
      - pkg: some-package

file-to-append.conf:
  file.append:
    - text: ...
    - require:
      - pkg: some-package

some-package-service:
  service.running:
    - enable: True
    - require:
      - file: /.../file-to-update.conf
      - file: /.../file-to-append.conf
```
This is the way Salt is expected to be used per the official documentation.

**Comment by srkunze** [comment]
> then the entire state is marked as failed

That's actually a very good reason not to do it.

Also from a long-term user's perspective, I would recommend to avoid shared state ids altogether. They look nice in the beginning but later on it's easier when you setup grows.

**Comment by whytewolf** [comment]
So, I'm going to close this. there are some very big reasons this has not been considered yet. 

first the way states actually work in the lower end data this actually can't work. 

```
state_id:
  file.managed:
    - name: /tmp/test
    - source: salt://files/source
  file.append:
    - name: /tmp/test
    - text: "this change"
```

the above gets rendered down to this internally

```
{
"state_id": {
  "file": 
    [ "managed", 
      {"name":"/tmp/test"}, 
      {"source": "salt://files/source"}]
  }, { 
  "file":
    [ "append", 
      {"name": "/tmp/test"},
      {"text": "this change"}]
  }
}
```

if you know anything about python you know you can't have 2 labels with the same key in a python dict. 

and if we tried merging them to get around this we end up with options without knowing which item goes to with function. 

to change the way this functions is a huge change. and would take a complete rewrite of the way states work.

we just don't have the staff for a rewrite for only this functionality. I'm going to close this ticket with the above information.

the information about using 1 function per state id is a better work around and makes more sense in the overall state definition.

**Comment by henri9813** [comment]
Hello,

Thanks for your proposition, but what about:
```
state_id:
  file:
    managed:
      - name: /tmp/test
      - source: salt://files/source
    append:
      - name: /tmp/test
      - text: "this change"
 ```

Could this be a good "deal" ? 
?
