### ISSUE TITLE
[request][salt-ssh] add ssh-config roster module

### ISSUE THREAD

**Issue by mavlyutov** [saltstack/salt#35727]
it would be a great feature to add support of standard .ssh/config file as roster file.
now I simply have to duplicate metadata of all my nodes to  two files: /etc/salt/roster and ~/.ssh/config which are pretty similar:

~/.ssh/config

```
Host camon-man1
  Hostname camon-man1.mysuperdomain.com
  User root
  IdentityFile ~/.ssh/id_rsa
```

/etc/salt/roster

```
camon-man1:
  host: camon-man1.mysuperdomain.com
  user: root
  priv: ~/.ssh/id_rsa
```
