### ISSUE TITLE
Failed to retrieve health_check for ELB myelb

### ISSUE THREAD

**Issue by szwed** [saltstack/salt#35730]
### Description of Issue/Question

When using example ELB **_Ensure myelb ELB exists_** state defined here:
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_elb.html

I get the following error message:

```
----------
          ID: Ensure myelb ELB exists
    Function: boto_elb.present
        Name: myelb
      Result: False
     Comment: ELB myelb is set to be created. Failed to retrieve attributes for ELB myelb. Failed to retrieve health_check for ELB myelb.  myelb ELB configuration could not be retrieved.
     Started: 14:10:00.695920
    Duration: 863.888 ms
```

The entire ELB definition is copied directly from the example, including **_health_check_** definition but Salt doesn't recognise it for some reason.
### Steps to Reproduce Issue

Try tu run the example from:
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_elb.html

...for the  **_Ensure myelb ELB exists_** state
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-79-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@szwed just to clarify are you refrering to this example:

```
Ensure myelb ELB exists:
    boto_elb.present:
        - name: myelb
        - region: us-east-1
        - availability_zones:
            - us-east-1a
            - us-east-1c
            - us-east-1d
        - keyid: GKTADJGHEIQSXMKKRBJ08H
        - key: askdjghsdfjkghWupUjasdflkdfklgjsdfjajkghs
        - listeners:
            - elb_port: 443
              instance_port: 80
              elb_protocol: HTTPS
              instance_protocol: HTTP
              certificate: 'arn:aws:iam::1111111:server-certificate/mycert'
              policies:
                  - my-ssl-policy
                  - cookie-policy
            - elb_port: 8210
              instance_port: 8210
              elb_protocol: TCP
        - backends:
            - instance_port: 80
              policies:
                  - enable-proxy-protocol
        - health_check:
            target: 'HTTP:80/'
        - attributes:
            cross_zone_load_balancing:
              enabled: true
            access_log:
              enabled: true
              s3_bucket_name: 'mybucket'
              s3_bucket_prefix: 'my-logs'
              emit_interval: 5
            connecting_settings:
              idle_timeout: 60
        - cnames:
            - name: mycname.example.com.
              zone: example.com.
              ttl: 60
            - name: myothercname.example.com.
              zone: example.com.
        - security_groups:
            - my-security-group
        - policies:
            - policy_name: my-ssl-policy
              policy_type: SSLNegotiationPolicyType
              policy:
                Protocol-TLSv1.2: true
                Protocol-SSLv3: false
                Server-Defined-Cipher-Order: true
                ECDHE-ECDSA-AES128-GCM-SHA256: true
            - policy_name: cookie-policy
              policy_type: LBCookieStickinessPolicyType
              policy: {}  # no policy means this is a session cookie
            - policy_name: enable-proxy-protocol
              policy_type: ProxyProtocolPolicyType
              policy:
                ProxyProtocol: true
```

Just clarifying because there are multiple examples on that site. From my understanding you would not be able to exactly just copy and paste that example, because you would need to change the values specific to your environment. Apologies if you already did this jsut want to make sure you changed environment specific values such as `keyid`, `key`, `availability_zones`, 

Also is there any relevant information in the debug logs that you could also share if you did indeed already change these values? Just a reminder to make sure to sanitize the output if pasting it here.
