### ISSUE TITLE
[salt-ssh] dockercompose module not loaded

### ISSUE THREAD

**Issue by mavlyutov** [saltstack/salt#35731]
### Description of Issue/Question

Cannot get dockercompose module to work via salt-ssh.
docker-compose and docker packages installed on target system as docs required.
### Steps to Reproduce Issue

```
mavlyutov@95:~/workspace/salt (git::canvas_app)$ salt-ssh --refresh --refresh-cache --wipe "canvas-man1" dockercompose.up /root/ololo.yml
canvas-man1:
    ----------
    retcode:
        0
    stderr:
        'dockercompose' __virtual__ returned False: The dockercompose execution module not loaded: compose python library not available.
    stdout:
```

```
mavlyutov@95:~/workspace/salt (git::canvas_app)$ salt-ssh "canvas-man1" cmd.run "pip freeze | grep docker"
canvas-man1:
    docker-compose==1.8.0
    docker-py==1.9.0
    dockerpty==0.4.1
```
### Versions Report

```
mavlyutov@95:~/workspace/salt (git::canvas_app)$ salt --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Dec  5 2015, 14:44:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64
```
