### ISSUE TITLE
pkgrepo.managed salt state does not update repo when proxy is deleted

### ISSUE THREAD

**Issue by LuboVarga** [saltstack/salt#35760]
### Description of Issue/Question

Having this state:

```
saltstack:
  pkgrepo.managed:
    - humanname: SaltStack repo for RHEL/CentOS $releasever
    - baseurl: https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest
    - gpgcheck: 1
    - gpgkey: https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest/SALTSTACK-EL5-GPG-KEY.pub
    - proxy: _none_
```

After removal of proxy attribute, highstate does not change provisioned repo file.
### Steps to Reproduce Issue

When I add proxy: _none_ attribute to state, it will be reflected. When I remove it (I expect that proxy config will be removed from repo file), it does not trigger any change on minion.
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)

salt-call --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
