### ISSUE TITLE
saltutil.wheel broken

### ISSUE THREAD

**Issue by ze42** [saltstack/salt#35761]
### Description of Issue/Question

saltutil.wheel seems broken. Can't manage to run it, even the doc example.

### Setup

A simple host with master & minion.

### Steps to Reproduce Issue

```
# salt $(hostname) -d saltutil.wheel
saltutil.wheel:

    Execute a wheel module (this function must be run on the master)

    New in version 2014.7.0

    name
        The name of the function to run
    kwargs
        Any keyword arguments to pass to the wheel function

    CLI Example:

        salt '*' saltutil.wheel key.accept match=jerry
    

# salt $(hostname)  saltutil.wheel key.accept match=jerry
chch-salt-master:
    ERROR executing 'saltutil.wheel': The following keyword arguments are not valid: __pub_user=sudo_ze, __pub_arg=['key.accept', {'match': 'jerry'}], __pub_fun=saltutil.wheel, __pub_jid=20160825140244073292, __pub_ret=, __pub_tgt=chch-salt-master, __pub_tgt_type=glob
```

As I've seen this before with function taking `**kwargs`, and trying to call further method, I tried to add `**kwargs` to a function like `key.list_all`.

```
# salt $(hostname) saltutil.wheel key.list_all
chch-salt-master:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1317, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 1067, in wheel
        return wclient.cmd(_fun, kwarg=kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/wheel/__init__.py", line 124, in cmd
        return super(WheelClient, self).cmd(fun, arg, pub_data, kwarg)
      File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 231, in cmd
        return self.low(fun, low)
      File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 369, in low
        mminion=self.mminion,
      File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 31, in store_job
        job_cache = opts['master_job_cache']
    KeyError: 'master_job_cache'
```

### Versions Report

```
# salt --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.14.43-cerberhost-0.10.5-grsec
         system: Linux
        version: debian 8.5 
```

Note: Yeah, I could just call salt-key, but that's not the point, as it will have to run as a syndic later, and be called from the master...

**Comment by rallytime** [comment]
Hi @ze42 - This is a know issue with 2016.3.0 and has been fixed in 2016.3.2 by #33414:
```
root@rallytime:~# salt rallytime saltutil.wheel key.list_all
rallytime:
    ----------
    local:
        - master.pem
        - master.pub
    minions:
        - rallytime
        - ubuntu.members.linode.com
    minions_denied:
    minions_pre:
    minions_rejected:
root@rallytime:~# salt rallytime test.versions_report
rallytime:
    Salt Version:
               Salt: 2016.3.2

    Dependency Versions:
               cffi: 0.8.6
           cherrypy: 5.0.1
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 1.0.1
              ioflo: 1.5.5
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: 1.2.3
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
       python-gnupg: 0.3.8
             PyYAML: 3.10
              PyZMQ: 14.5.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 4.6.3-x86_64-linode70
             system: Linux
            version: Ubuntu 14.04 trusty
```
