### ISSUE TITLE
salt.cloud cloud.profile cannot be made zero-to-hero

### ISSUE THREAD

**Issue by haraldrudell** [saltstack/salt#35782]
One can by using salt state cloud.profile instantiate ec2 instances in loop or direct constructs.

This cannot be done from scratch with only input pillar salt.cloud.aws_key, salt.cloud.aws_secret and a region/image because:

In cloud profile:
- elastic ips (ie. static public ipv4) cannot be managed, that has to be done using aws
  - either should be able to instantiate and refer to elastic ips by name with some undetermined ip value
  - or the ip value needs to be fetched to a jinja variable somehow
- SubnetId cannot be instantiated, that has to be done using aws
  - similar troubles as for elastic ip
- default or custom SecurityGroupId cannot be managed, it has be manually entered by using aws
  - this also involves vpc and determining the default vpc

It seems the architecture is lacking somewhat as of 2015.8.8

**Comment by Ch3LL** [comment]
@haraldrudell I have personally never used the `cloud.profile` state but looking at the code it looks like you can add any configurations you normally could using salt-cloud like so:

```
my-ec2-instance:
  cloud.profile:
    - profile: my-ec2-config
    - securitygroup: default
    - subnetid: subnet-097b6a21
    - associate_eip: eipalloc-XXXXXXXX
```

It uses the `vm_overrides` kwargs in the code which looks like it should be able to overwrite configurations such as above. Does the above work for you?
