### ISSUE TITLE
python syntax in pillars

### ISSUE THREAD

**Issue by KralMar** [saltstack/salt#35794]
## python script in pillars

Hi,

is there any way  to store a python-script / a config file in python syntax in the pillars?
With my setup below, it seems like salt doesn't take the data part of the pillar-file as it is, but instead tries to render it.

The setup below works with pure Text as pillar-content.

### .sls:
```

/etc/test.conf:
  file.managed:
    - contents: {{ pillar['sensitive']['data'] | indent(6) }}
    - user: test
    - group: test
    - mode: 600
```

### Pillar-File:

```
sensitive:
  data: |
    import sys
    data = [test = 'bla']
    data= 'test'
    data2 = 'bla'
```
.............

### Master:

```
  Rendering SLS 'base:watchdog.config' failed: could not found expected ':'; line 5
 
 ---
 /etc/test.conf:
   file.managed:
     - contents: import sys
       data = [test = 'bla']
       data= 'test'    <======================
       data = bla
       data = 'bla'
     - user: test
     - group: test
     - mode: 600
 [...]
```

### Minion:

```
 [DEBUG   ] Rendered data from file ...:
 /etc/test.conf:
   file.managed:
     - contents: import sys
       data = [test = 'bla']
       data= 'test'
       data = bla
       data = 'bla'
     - user: test
     - group: test
     - mode: 600
 
 [CRITICAL] Rendering SLS 'base:test.config' failed: could not found expected ':'; line 5
 
 ---
 /etc/test.conf:
   file.managed:
     - contents: import sys
       data = [test = 'bla']
       data= 'test'    <======================
       data = bla
       data = 'bla'
     - user: test
     - group: test
     - mode: 600
 [...]
 ---
 [DEBUG   ] Minion return retry timer set to 9 seconds (randomized)
```

### Versions Report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.4

**Comment by lorengordon** [comment]
Try it like this:

```yaml
/etc/test.conf:
  file.managed:
    - contents: |
        {{ pillar['sensitive']['data'] | indent(8) }}
    - user: test
    - group: test
    - mode: 600
```
