### ISSUE TITLE
Incorrect SQS engine config

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#35834]
On https://docs.saltstack.com/en/latest/ref/engines/all/salt.engines.sqs_events.html#configuration it says

```yaml
engines:
  - sqs_events:
    queue: test
    profile: my-sqs-profile #optional
```

but I'm pretty sure it should be

```yaml
engines:
  - sqs_events:
      queue: test
      profile: my-sqs-profile #optional
```
