### ISSUE TITLE
Troubles running multiple salt-master on single host

### ISSUE THREAD

**Issue by resolutecake** [saltstack/salt#35843]
### Description of Issue/Question
1. I want to run multiple masters to serve different file sets due to security concerns.
2. I am trying to run one regular salt-master, and then a master2 and a master3 serving lower security zones on the same host, different ports and directories.

**How can I make it work?**

I created this salt state launching a number of secondary salt-masters which appears to be working. Until they launch. Then zeroMQ exits with code None about 3 per second. Lots of Log output of the following:

```
2016-08-25 23:23:02,461 [salt.transport.zeromq][INFO ][12120] Worker binding to socket ipc:///var/run/salt3/master/workers.ipc
2016-08-25 23:23:02,475 [salt.utils.process][INFO ][12116] Process <bound method ZeroMQReqServerChannel.zmq_device of <salt.transport.zeromq.ZeroMQReqServerChannel object at 0xb3ddae0c>> (12553) died with exit status None, restarting...
```

### Setup

conf file for one of the new secondary masters

```
publish_port: 502
ret_port: 503
pidfile: "/var/run/salt-master2.pid"
pki_dir: "/etc/salt2/pki/master"
cachedir: "/var/cache/salt2/master"
sock_dir: "/var/run/salt2/master"
roster_file: "/etc/salt2/roster"
worker_threads: "3"
file_roots:
  base:
    - /home/data/salt/file2
fileserver_backend:
  - roots
  - git
gitfs_remotes:
    - file:///home/data/salt/saltgit/salt-formula
pillar_roots:
  base:
    - /home/data/salt/pillar
ext_pillar:
  - file_tree:
      root_dir: /home/data/salt/filepillar
      follow_dir_links: True
log_level: "info"
```
### Versions Report

> salt --versions-report 
> Salt Version:
>            Salt: 2015.8.8
> 
> Dependency Versions:
>          Jinja2: 2.8
>        M2Crypto: 0.21.1
>            Mako: 1.0.3
>          PyYAML: 3.11
>           PyZMQ: 15.2.0
>          Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
>            RAET: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.1.4
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: 2.4.2
>           gitdb: 0.6.4
>       gitpython: 1.0.1
>           ioflo: Not Installed
>         libgit2: Not Installed
>         libnacl: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.6
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>    python-gnupg: Not Installed
>           smmap: 0.9.0
>         timelib: Not Installed
> 
> System Versions:
>            dist: Ubuntu 16.04 xenial
>         machine: i686
>         release: 4.4.0-31-generic
>          system: Ubuntu 16.04 xenial
