### ISSUE TITLE
preserve_minion_cache is broken in 2016.3+

### ISSUE THREAD

**Issue by junovitch** [saltstack/salt#35840]
### Description of Issue/Question

I use 'preserve_minion_cache: True' to maintain some files between builds.  The funtionality is broken in 2016.3.2.
### Setup

Set 'preserve_minion_cache: True'
### Steps to Reproduce Issue

Run salt-key -d <host> with 'preserve_minion_cache: True'
### Versions Report

I'm also running on CentOS.

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  3 2016, 19:48:26)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5

System Versions:
           dist:   
        machine: amd64
        release: 11.0-RC1
         system: FreeBSD
        version: Not Installed
```
