### ISSUE TITLE
file.managed contents_pillar silently returns "" if pillar key not found

### ISSUE THREAD

**Issue by minaguib** [saltstack/salt#35841]
### Setup
Given a state SLS node like this where there's no pillar variable with that name:
```
ssl_certificate:
  file.managed:
    - name: /etc/nginx/ssl/theserver.crt
    - contents_pillar: ZZZZZZZZZ
```

### Steps to Reproduce Issue
Invoking the above will create the managed file with empty contents.  Pillar not-found/typos are silently discarded.

### Versions Report

```
           Salt: 2015.5.5
         Python: 2.7.10 (default, Nov  9 2015, 19:32:36)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.1
           RAET: Not Installed
            ZMQ: 4.1.1
           Mako: Not Installed
        Tornado: 4.0.1
        timelib: Not Installed
       dateutil: Not Installed
```
