### ISSUE TITLE
keystone.endpoint_present deletes RegionOne endpoints

### ISSUE THREAD

**Issue by epcim** [saltstack/salt#35874]
### Description of Issue/Question

for setup with two regions with shared keystone db, the endpoint list is being improperly updated when second region tries to setup it's endpoints (identity service endpoint)

https://github.com/saltstack/salt/blob/2016.3/salt/states/keystone.py#L548
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
{{{

keystone_{{ service_name }}_endpoint:
  keystone.endpoint_present:
  - name: {{ service.get('service', service_name) }}
  - publicurl: '{{ service.bind.get('public_protocol', 'http') }}://{{ service.bind.public_address }}:{{ service.bind.public_port }}{{ service.bind.public_path }}'
  - internalurl: '{{ service.bind.get('internal_protocol', 'http') }}://{{ service.bind.internal_address }}:{{ service.bind.internal_port }}{{ service.bind.internal_path }}'
  - adminurl: '{{ service.bind.get('admin_protocol', 'http') }}://{{ service.bind.admin_address }}:{{ service.bind.admin_port }}{{ service.bind.admin_path }}'
  - region: {{ service.get('region', 'RegionOne') }}
  - require:
    - keystone: keystone_{{ service_name }}_service
    - file: keystone_salt_config


}}}
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

https://github.com/saltstack/salt/blob/2016.3/salt/states/keystone.py#L548

as `endpoint_get` is missing region, the `endpoint != cur_endpoint` and thus the delete call later is invoked which effectively deletes configuration for first region.
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
@epcim this is definitely not good. We will need to get this fixed and add the region to make sure this indeed not occurring. Thanks so much for the heads up.

**Comment by gtmanfred** [comment]
I am unable to see this problem, am I doing something wrong?

Here is my state that I am using.

```
[root@salt ~]# cat /srv/salt/test.sls
glance services:
  keystone.service_present:
    - name: glance
    - description: OpenStack Image
    - service_type: image

keystone_glance_region1_endpoint:
  keystone.endpoint_present:
    - name: glance
    - publicurl: http://localhost:9292
    - internalurl: http://localhost:9292
    - adminurl: http://localhost:9292
    - region: RegionOne

keystone_glance_region2_endpoint:
  keystone.endpoint_present:
    - name: glance
    - publicurl: http://localhost:9292
    - internalurl: http://localhost:9292
    - adminurl: http://localhost:9292
    - region: RegionTwo
```

And here is the output of the state.apply

```
root@salt ~]# salt-call state.apply test
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
----------
          ID: glance services
    Function: keystone.service_present
        Name: glance
      Result: True
     Comment: Service "glance" has been added
     Started: 18:56:17.337019
    Duration: 73.096 ms
     Changes:
              ----------
              Service:
                  Created
----------
          ID: keystone_glance_region1_endpoint
    Function: keystone.endpoint_present
        Name: glance
      Result: True
     Comment: Endpoint for service "glance" has been added
     Started: 18:56:17.410276
    Duration: 172.404 ms
     Changes:
              ----------
              adminurl:
                  http://localhost:9292
              id:
                  612ad0e827014ad6b54388e4eccfc694
              internalurl:
                  http://localhost:9292
              publicurl:
                  http://localhost:9292
              region:
                  RegionOne
              service_id:
                  b9d09a9726c84857bac3cc32e9cf4410
----------
          ID: keystone_glance_region2_endpoint
    Function: keystone.endpoint_present
        Name: glance
      Result: True
     Comment: Endpoint for service "glance" has been updated
     Started: 18:56:17.582908
    Duration: 257.14 ms
     Changes:
              ----------
              adminurl:
                  http://localhost:9292
              id:
                  061b63b70da84c1e8afed89b15b440e5
              internalurl:
                  http://localhost:9292
              publicurl:
                  http://localhost:9292
              region:
                  RegionTwo
              service_id:
                  b9d09a9726c84857bac3cc32e9cf4410

Summary for local
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total run time: 502.640 ms
```

and then the endpoint_list afterwards shows both endpoints.

```
[root@salt ~]# salt-call keystone.endpoint_list
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
    ----------
    061b63b70da84c1e8afed89b15b440e5:
        ----------
        adminurl:
            http://localhost:9292
        id:
            061b63b70da84c1e8afed89b15b440e5
        internalurl:
            http://localhost:9292
        publicurl:
            http://localhost:9292
        region:
            RegionTwo
        service_id:
            b9d09a9726c84857bac3cc32e9cf4410
    e5e34a67387b479e82d9ad95a2649b8e:
        ----------
        adminurl:
            http://localhost:35357/v2.0
        id:
            e5e34a67387b479e82d9ad95a2649b8e
        internalurl:
            http://localhost:5000/v2.0
        publicurl:
            http://localhost:5000/v2.0
        region:
            RegionOne
        service_id:
            a489e8f578a946c484298e21083b28a1
```

**Comment by gtmanfred** [comment]
@epcim can you review my comment above?

Thanks!
Daniel

**Comment by meggiebot** [comment]
Removing from 2016.3.4 since we are unable to reproduce. We will add to a future release once we have more information.

**Comment by kaszuba** [comment]
@gtmanfred I have the same issue, please change your test to v3 API, your example use v2 which works.

Example pillar:
```
keystone.auth_url: http://localhost:35357/v3
keystone.user: admin
keystone.password: pass
```

Example endpoint:
```
glance-endpoint-public:
  keystone.endpoint_present:
    - name: glance
    - region: RegionOne
    - url: http://controller:9292
    - interface: public
```

This happened because endpoint is deleted when it already exists, but not created again. Here are problematic lines:
https://github.com/saltstack/salt/blob/develop/salt/states/keystone.py#L731-L738

And better if it could be updated only, not deleted/created.
