### ISSUE TITLE
#34869 prevent updating the repository only when the remote changed with local changes

### ISSUE THREAD

**Issue by the-glu** [saltstack/salt#35888]
### Description of Issue/Question

I have a git repository updated with `git.latest`, and I do local changes.

Before that, my state was like this:

```
git:
  git.latest:
    - rev: master
    - branch: master
    - force_fetch: True
    - force_checkout: True
    - target: /git/
```

Everything was ok, and the repository was updated when the remote repository changed.
Now with 2016.3.3 (and dues to #34869 I think), if I do local change to the project, he complains he can't do a fast-forward and I must use `force_reset`. 

But if I use `force_reset`, my local changes are erased each time the state is applied, and I don't want this, I want to erase them only when the remote changed.

To fix this I added this

```
    - force_reset: True
    - unless: "cd /git/ && git remote update && git status -uno | grep 'Your branch is up-to-date with'"
```

but it feel hackish and bad.

Is it possible to have an intermediate `force_reset` option who will reset the repository only when the remote changed ?

Thanks !
### Versions Report

Salt 2016.3.3. Was ok in Salt 2016.3.2.
