### ISSUE TITLE
/var/cache/salt/master/gitfs grows very large

### ISSUE THREAD

**Issue by stephane-martin** [saltstack/salt#35920]
Hello,
### Description of Issue

On the salt master i have configured a gitfs. The "remote" git repository is located on the same server and is not very large (roughly 160MB). Today i had an alert about low free space for partition /.

Indeed the salt cache for the gitfs has grown very large (more than 6 GB). Inside the cache the directory `/var/cache/salt/master/gitfs/LONGID/.git/objects/pack` represents itself 6GB.

It seems that salt keeps a full copy of the git repository _for each commit_ that was made to the git repository. Inside `pack` I found 52 .idx files and 52 .pack files. The .pack files generally have a size > 150M. Looking at the git repository there is 55 commits so far.

So to check I commited a dummy change to git repo, then I pushed to change. Bingo, 1 minute after there is a new .pack file of 160MB...
- Is it the expected behaviour ?!
- How can i clean the gitfs cache so that it does not grow unboundly ?
### Setup

Master runs on an Ubuntu Trusty server. salt-master has been installed with the deb repo (`deb http://repo.saltstack.com/apt/ubuntu/ubuntu14/latest trusty main`).

In master config:

```
fileserver_backend:
  - git
  - roots

gitfs_provider: pygit2
gitfs_base: master

gitfs_remotes:
  - file:///srv/saltrepo
```

```
$ du -sh /srv/saltrepo
163M    /srv/saltrepo

$ du -sh /var/cache/salt/master/gitfs
6.2G    /var/cache/salt/master/gitfs
```
### Steps to Reproduce Issue

Not sure so far.
### Versions Report

```
$ salt --versions-report | less
Salt Version:
Salt: 2016.3.2

Dependency Versions:
cffi: 1.7.0
cherrypy: 3.2.2
dateutil: 1.5
gitdb: 0.5.4
gitpython: 0.3.2 RC1
ioflo: Not Installed
Jinja2: 2.7.2
libgit2: 0.24.0
libnacl: Not Installed
M2Crypto: Not Installed
Mako: 0.9.1
msgpack-pure: Not Installed
msgpack-python: 0.4.6
mysql-python: 1.2.3
pycparser: 2.14
pycrypto: 2.6.1
pygit2: 0.24.1
Python: 2.7.6
PyYAML: 3.11
PyZMQ: 14.0.1
RAET: Not Installed
smmap: 0.8.2
timelib: Not Installed
Tornado: 4.2.1
ZMQ: 4.0.5

System Versions:
dist: Ubuntu 14.04 trusty
machine: x86_64
release: 4.4.19
system: Linux
version: Ubuntu 14.04 trusty
```

**Comment by stephane-martin** [comment]
`sudo git gc --auto` inside `/var/cache/salt/master/gitfs/LONGID` did reduce the 6GB to 161MB... So it looks like we have to schedule a regular git gc operation on the salt gitfs cache, right ?

**Comment by Ch3LL** [comment]
ping @terminalmage i'm a little fuzzy on how this works in terms of updating the cache and gitfs. Can you answer @stephane-martin 's questions concerning whether this is expected behavior and if so is there an option to ensure the cache does not grow?

**Comment by terminalmage** [comment]
Yeah, we may have to run a gc if that's happening. We don't do anything manually with the cache, this is all happening through fetching the remote URL using pygit2, so this may be an upstream bug in pygit2. I'd like to gather more information and try to reproduce so that I can (if necessary) have the proper information to file a bug report upstream with pygit2.

**Comment by terminalmage** [comment]
@stephane-martin Does this only happen with local repos, or can you reproduce this with a remote (https/ssh) repo as well?

**Comment by stephane-martin** [comment]
- I added a HTTPS repo to gitfs_remotes
- Then i added a 17MB file to that repo
- `/var/cache/salt/master/gitfs` has increased by 17MB
- Then i added a 60kb file to the repo
- `/var/cache/salt/master/gitfs` has increased by 64kb

So it looks like it does not happen for HTTPS git repos.

**Comment by stephane-martin** [comment]
Same test with a SSH repo. I can only see normal size increase.

So it seems the strange behaviour only happens with local repos.

**Comment by terminalmage** [comment]
Thanks, this should help narrow down my troubleshooting considerably.

**Comment by driskell** [comment]
This is happening a lot for me too with local repos.

I have tried manually running a GC on the repositories but it seems salt-master has handles to all the pack files still open.

Furthermore, salt-run fileserver.update seems to take a long time as it appears to recreate an entirely brand new pack file every time, even if there's only one tiny commit to download.

**Comment by driskell** [comment]
Switched away from pygit2 to GitPython and now salt-run fileserver.update finishes in milliseconds and the disk usage does not grow anymore when I run it. So seems to be an issue within pygit2 on CentOS 7

**Comment by Darkentik** [comment]
@terminalmage this problem is still there with salt-master version 3005.1+ds-1 on Debian Bullseye.
This issue was closed by being stale and not done.
Our workaround is now to give more disk space. :(
We are using python3-pygit2 1.4.0+dfsg1-1.
Here are our gitfs config on our salt-master:
```
ext_pillar:
- git:
  - staging https://git.mycompany.local:443/team-devops/saltstack/salt-common.git:
    - name: salt-common
    - ssl_verify: false
    - user: oauth2
    - password: supersecret
    - root: pillar
    - env: common
fileserver_backend:
- git
gitfs_base: staging
gitfs_provider: pygit2
gitfs_ref_types:
- branch
gitfs_remotes:
- https://git.mycompany.local:443/team-devops/saltstack/salt-common.git:
  - name: salt-common
  - ssl_verify: false
  - user: oauth2
  - password: supersecret
  - root: states
  - saltenv:
    - common:
      - ref: staging
- https://git.mycompany.local:443/team-devops/saltstack/salt-common.git:
  - name: salt-common-reactor
  - ssl_verify: false
  - user: oauth2
  - password: supersecret
  - root: reactor
  - mountpoint: salt://reactor
  - saltenv:
    - common:
      - ref: staging
- https://git.mycompany.local:443/team-devops/saltstack/salt-common.git:
  - name: salt-common-orchestrate
  - ssl_verify: false
  - user: oauth2
  - password: supersecret
  - root: orchestrate
  - mountpoint: salt://orchestrate
  - saltenv:
    - common:
      - ref: staging
gitfs_saltenv_blacklist:
- feature-.*
gitfs_saltenv_whitelist:
- common
state_top: top_staging.sls
top_file_merging_strategy: same
```

Thanks.
