### ISSUE TITLE
sha1 checksum broken after salt minion update

### ISSUE THREAD

**Issue by Garont** [saltstack/salt#35932]
I'm using nginx to generate firewall rules for my servers and saltstack to distribute them. After last minion update sha1 checksum has become broken

```
salt "server" state.highstate

...
          ID: /etc/iptables/rules.v6
    Function: file.managed
      Result: False
     Comment: Specified sha1 checksum for http://salt.master.com/fw?env=prod&ipv=6&fwrules=1&server=salt.minion.com (http://salt.master/fw?env=prod&ipv=6&hash=1&server=salt.minion.com) does not match actual checksum (cacc374cd446cb08d296f860f4ed45e5f0a5f472)
...
wget 'http://salt.master.com/fw?env=prod&ipv=6&fwrules=1&server=salt.minion.com' -O - 2> /dev/null | sha1sum
cacc374cd446cb08d296f860f4ed45e5f0a5f472  -
```

```
salt --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5
        machine: x86_64
        release: 2.6.32-042stab113.17
         system: Linux
        version: debian 8.5


salt-minion --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5
        machine: x86_64
        release: 2.6.32-042stab116.2
         system: Linux
        version: debian 8.5
```

**Comment by Ch3LL** [comment]
@Garont I cannot reproduce this. Here is my test case:
sls file:

```
test:
  file.managed:
    - name: /tmp/test-issue
    - source: http://localhost:9988/test1
    - source_hash: sha1=4e1243bd22c66e76c2ba9eddc1f91394e57f9f83
```

```
[ch3ll@thecakeisalie files]$ sudo salt-call --local state.sls issues.35932
local:
----------
          ID: test
    Function: file.managed
        Name: /tmp/test-issue
      Result: True
     Comment: File /tmp/test-issue updated
     Started: 13:14:15.663312
    Duration: 24.729 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

```
[ch3ll@thecakeisalie files]$ salt --version
salt 2016.3.2 (Boron)
```

Can you please share your sls file to help reproduce this issue?

**Comment by Garont** [comment]
@Ch3LL 

```
{% if grains['os'] == 'Debian' %}
netfilter-persistent:
  pkg:
    - installed
iptables-persistent:
  pkg:
    - installed
{% endif %}

createRulesDir:
  cmd.run:
    - name: mkdir /etc/iptables/
    - unless: ls /etc/iptables/

/etc/iptables/rules.v4:
  file.managed:
    - source: http://salt.server.com/fw?env=prod&ipv=4&fwrules=1&server={{ grains.s_hostname }}
    - source_hash: sha1=http://salt.server.com/fw?env=prod&ipv=4&hash=1&server={{ grains.s_hostname }}
    - user: root
    - group: root
    - mode: 644
    - backup: minion
  cmd.run:
    - name: service netfilter-persistent reload
    - onchanges:
      - file: /etc/iptables/rules.v4


/etc/iptables/rules.v6:
  file.managed:
    - source: http://salt.server.com/fw?env=prod&ipv=6&fwrules=1&server={{ grains.s_hostname }}
    - source_hash: sha1=http://salt.server.com/fw?env=prod&ipv=6&hash=1&server={{ grains.s_hostname }}
    - user: root
    - group: root
    - mode: 644
    - backup: minion
  cmd.run:
    - name: service netfilter-persistent reload
    - onchanges:
      - file: /etc/iptables/rules.v6
```

**Comment by Ch3LL** [comment]
@Garont okay I believe this is related to #35168 . In the documentation it states "When using a remote file source as the source_hash, the hash type isn't present." So if you change your source_hash to remove `sha1=` does it then work?

**Comment by Garont** [comment]
@Ch3LL When I'm removing sha1= I've got error message like 

```
          ID: /etc/iptables/rules.v6
    Function: file.managed
      Result: False
     Comment: Source hash http://salt.server.com/fw?env=prod&ipv=6&hash=1&server=salt.minion.com format is invalid. It must be in the format <hash type>=<hash>, or it must be a supported protocol: salt, file, http, https, ftp, swift, s3

```

part of sls:
```
    - source: http://salt.server.com/fw?env=prod&ipv=6&fwrules=1&server={{ grains.s_hostname }}
    - source_hash: http://salt.server.com/fw?env=prod&ipv=6&hash=1&server={{ grains.s_hostname }}
```

**Comment by Ch3LL** [comment]
@Garont looks like this is related to how you are calling the sha1 sum then probably related to using `?` in the url, because it works for me using the direct call to the sum like so:

```
salt-repo-pkg:
  file.managed:
    - name: /tmp/test.exe
    - source: http://repo.saltstack.com/windows/Salt-Minion-2015.5.0-2-AMD64-Setup.exe
    - source_hash: http://repo.saltstack.com/windows/Salt-Minion-2015.5.0-2-AMD64-Setup.exe.md5
```

Thanks for trying that. Looks like we need to get this fixed up. It seems its related to the question mark.
