### ISSUE TITLE
Highstate with test=True fails when an white line exists before service.running

### ISSUE THREAD

**Issue by amontalban** [saltstack/salt#35971]
### Setup
```yaml
importantservice:
  file.managed:
    - name: /some/where
    - source: salt://service/files/somefile
    - user: root
    - group: root
    - mode: 0755
    - template: jinja
    - context:
        some_variable: some_value
        {% if grains['deployment'] == 'development_box' %}
        environment: development
        {% else %}
        environment: production
        {% endif %}
  service.running:
    - enable: True
    - watch:
      - file: importantservice
    - watch_in:
      - service: otherservice
```

### Steps to Reproduce Issue
The generated state for the above SLS is:

```yaml
importantservice:
  file.managed:
    - name: /some/where
    - source: salt://service/files/somefile
    - user: root
    - group: root
    - mode: 0755
    - template: jinja
    - context:
        some_variable: some_value
        environment: development
        
  service.running:
    - enable: True
    - watch:
      - file: importantservice
    - watch_in:
      - service: otherservice
```

**And generates the following output:**

```bash
          ID: importantservice
    Function: file.managed
        Name: /some/where
      Result: None
     Comment: The file /some/where is set to be changed
     Started: 15:38:13.745518
    Duration: 13.757 ms
     Changes:   
----------
          ID: importantservice
    Function: service.running
      Result: False
     Comment: The named service importantservice is not available
     Started: 15:38:13.769738
    Duration: 41.11 ms
     Changes:   
```

However if I trim the white line it does not fail when running `state.highstate` with `test=True`.

### Versions Report
```bash
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul 28 2016, 01:47:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
 
System Versions:
           dist:   
        machine: amd64
        release: 10.3-RELEASE-p4
         system: FreeBSD
        version: Not Installed
```
