### ISSUE TITLE
Salt merge pillars of all environments. saltenv ignored

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#36027]
### Description of Issue/Question
Salt merge pillars of all environments. environment/saltenv ignored. If i have 3 environments, a pillar.items xxx returns the aggregation of the pillar from each environment. 

When i set the  pillarenv in the  configuration file on the minion , salt-call get the goot envionment pillars:
`salt-call pillar.items rsyslog pillarenv=develop`

But "salt" command  from the master, don't (aggregations of envs):

`salt 'myminion' pillar.items rsyslog saltenv=develop pillarenv=develop`

### Setup

```
/etc/salt/master.d/pillars.conf:
pillar_merge_lists: True
pillar_source_merging_strategy: recurse

pillar_roots:
   xxx:
    - /data/salt//BRANCH/xxx/PILLARS
   develop:
    - /data/salt//BRANCH/develop/PILLARS
   base:
    - /data/salt//BRANCH/master/PILLARS
```

In each branch  PILLARS directory  like develop one:

```
/data/salt//BRANCH/develop/PILLARS/top.sls:
develop:
  '*':
    - commun.rsyslog
```

```
/data/salt//BRANCH/master/PILLARS/top.sls:
base:
  '*':
    - commun.rsyslog
```

```
in branch/*/PILLARS/commun.rsyslog.sls:
rsyslog:
  settings:
    modules:
      - imklog
      - imuxsock
```

### Steps to Reproduce Issue

```
salt-call pillar.items rsyslog saltenv=develop

    rsyslog:
        ----------
        settings:
            modules:
                - imklog
                - imuxsock
                - imklog
                - imuxsock
                - imklog
                - imuxsock
```

salt state.aplly do the same.

in Logs of salt master i see jinja looking into every branch:

```
 [salt.utils.jinja ][DEBUG   ][8389] Jinja search path ['/data/salt//BRANCH/xxx/PILLARS']
 [salt.utils.jinja ][DEBUG   ][8389] Jinja search path ['/data/salt//BRANCH/develop/PILLARS']
 [salt.utils.jinja ][DEBUG   ][8389] Jinja search path ['/data/salt//BRANCH/master/PILLARS']
```

### Versions Report

```
master : 
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial

minion:
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: CentOS 6.8 Final
```

NB: same thing with 2015.08.12
