### ISSUE TITLE
[ERROR   ] Command '['runlevel', '/run/utmp']' failed with return code: 1

### ISSUE THREAD

**Issue by lioramilbaum** [saltstack/salt#36059]
### Description of Issue/Question

While bootstrapping hit the error:

[INFO    ] Running state [salt-minion] at time 13:43:20.215675
[INFO    ] Executing state service.dead for salt-minion
[INFO    ] Executing command ['runlevel', '/run/utmp'] in directory '/root'
[ERROR   ] Command '['runlevel', '/run/utmp']' failed with return code: 1
[ERROR   ] output: Too many arguments.
### Setup

Bootstrapping while building docker image based on Ubuntu 16.04
runlevel command should be used as it works with systemd instead of Upstart
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.15-moby
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by jtand** [comment]
Hi @lioramilbaum, Can you get me the bootstrap version you are using as well?

**Comment by lioramilbaum** [comment]
@jtand, I am new to salt. Could you explain how do I find the bootstrap version.

**Comment by lioramilbaum** [comment]
@jtand  If you meant the salt-bootstrap.sh script than we don't use the one provided by salt. We have our own custom salt-bootstrap.sh script.

**Comment by jtand** [comment]
@lioramilbaum I see. Can you post the command you are using when you get this error?

**Comment by lioramilbaum** [comment]
salt-call --local --config-dir ${PWD}/etc --pillar-root ${PWD}/pillars --file-root ${PWD}/states state.sls bootstrap,salt.standalone,salt.formulas pillar='{"sparkbeyond": {"salt_root":"'"$PWD"'/.."}}'

**Comment by jtand** [comment]
@lioramilbaum Thanks for posting that. This sounds like something that might be in your bootstrap state. If you can, would you mind posting a sanitized version of that state?

**Comment by lioramilbaum** [comment]
This is my bootstrap.sls file:

{% set file_roots = salt['pillar.get']('salt:master:file_roots:'+env)[0] %}
{% set pillar_roots = salt['pillar.get']('salt:master:pillar_roots:'+env)[0] %}
{% set sp_salt_root = salt['pillar.get']('sparkbeyond:salt_root') %}

roots:
  file.symlink:
    - names:
      - {{ file_roots }}:
        - target: {{ salt['file.join'](sp_salt_root, 'states') }}
      - {{ pillar_roots }}:
        - target: {{ salt['file.join'](sp_salt_root, 'pillars') }}
    - makedirs: True

**Comment by jtand** [comment]
@lioramilbaum Hmmm, I guess I assumed that was where you had a `service.dead` block. That's the state I want to look at as it may have clues as to why upstart.py is being used instead of systemd.py.

The only place the `runlevel /run/utmp` will get run is in [upstart.py](https://github.com/saltstack/salt/blob/60ef970ce49fa81a17245410ca1214fcd8707a40/salt/modules/upstart.py#L151). The way the service modules works is it determines which OS the module is being run on, then if that OS uses systemd or upstart. If you are using a systemd OS, then the upstart module should not get used with the service module.

**Comment by lioramilbaum** [comment]
Attached the only source which includes service.dead block.

[init.txt](https://github.com/saltstack/salt/files/471338/init.txt)

**Comment by jtand** [comment]
@lioramilbaum Thank you for that init file. I'm not able to reproduce that error your seeing with all this information. Can you provide some debug logs from when that error comes up? 

You can get those by adding `-l debug` on the salt-call command, or whatever command that generates that error.

**Comment by samos123** [comment]
Weird it seems I have the same issue. There is a simple service.enable True which causes it to run runlevel command, but runlevel command does not exist.

```
lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

No runlevel command available..
```
whereis runlevel
runlevel:
```

```
runlevel
The program 'runlevel' is currently not installed. You can install it by typing:
apt-get install upstart
```

BUT I already have upstart installed, though it doesn't provide the runlevel command for me.
```
dpkg -l | grep upstart
ii  upstart                          1.13.2-0ubuntu21.1                  amd64        event-based init daemon - essential binaries
```

Actual error I see:
```
ID: salt_minion_service
    Function: service.running
        Name: salt-minion
      Result: False
     Comment: Unable to run command '['runlevel', '/run/utmp']' with the context '{'timeout': None, 'with_communicate': True, 'shell': False, 'bg': False, 'stderr': -2, 'env
': {'LC_NUMERIC': 'C', 'TERM': 'linux', 'LC_MESSAGES': 'C', 'LC_IDENTIFICATION': 'C', 'LC_MONETARY': 'C', 'DEBIAN_FRONTEND': 'noninteractive', 'LC_COLLATE': 'C', 'LC_MEASURE
MENT': 'C', 'PWD': '/', 'LC_ADDRESS': 'C', 'LC_CTYPE': 'C', 'UPSTART_INSTANCE': '', 'UPSTART_JOB': 'salt-minion', 'LC_TELEPHONE': 'C', 'LC_PAPER': 'C', 'LC_NAME': 'C', 'PATH
': '/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin', 'LC_TIME': 'C', 'UCF_FORCE_CONFFOLD': '1', 'APT_LISTBUGS_FRONTEND': 'none', 'APT_LISTCHANGES_FRONTEND': 'n
one'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'cwd': '/root'}', reason: [Errno 2] No such file or directory
     Started: 13:51:50.210427
    Duration: 7.122 ms
     Changes:   
```
