### ISSUE TITLE
salt-cloud - Windows minion bootstrap on vmware fails (Max retries exceeded with url: /wsman)

### ISSUE THREAD

**Issue by onlyPropertyDefendLiberty** [saltstack/salt#36056]
### Hello!
Ive been unable to get the Windows salt-minion to install when launching windows vmware (private cloud) instances via salt-cloud.

Issue appears to be that salt-cloud is trying to 'Attempting WinRM connection to host 10.30.17.88 on port 5986', here are the log entries showing this:
```
[INFO    ] [ Sep5PM5-winexe-dns-smb-wincufe-2 ] IPv4 is: 10.30.17.88
[INFO    ] Rendering deploy script: /etc/salt/cloud.deploy.d/bootstrap-salt.sh
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master/master_event_pull.ipc
[DEBUG   ] Deploying 10.30.17.88 at 1473067045.0 (Windows)
[DEBUG   ] Attempting connection to host 10.30.17.88 on port 445
[DEBUG   ] Attempting WinRM connection to host 10.30.17.88 on port 5986
[ERROR   ] There was a profile error: HTTPSConnectionPool(host='10.30.17.88', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2a66ed0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last): ...
```
I follow the https://docs.saltstack.com/en/latest/topics/cloud/windows.html
All the requirements are success installed.

### profile configs
```
[root@salt-master~]# cat /etc/salt/cloud.profiles.d/winexe-dns.conf
winexe-dns:
  provider: win-cufe
  clonefrom: bootstrap-firewall

  devices:
    network:
      Network adapter 1:
        name: 10Gb VM Network 317
        adapter_type: vmxnet3
        switch_type: distributed

  domain: test.etsc
  dns_servers:
    - 192.168.111.60
    - 10.30.11.2
    - 202.106.0.20

  resourcepool: poolname
  cluster: CL
  datacenter: Datacenter
  datastore: storename
  folder: foldername

  template: False
  power_on: True
  deploy: True

  minion:
    master_type: standard
    master: mastername
    id: Sep5PM5-winexe-dns-smb-wincufe-02

  use_winrm: True
  userdata_file: /etc/salt/windows-firewall.ps1
  win_installer: /root/Salt-Minion-2016.3.3-AMD64-Setup.exe
  win_username: cufe-PC
  win_password: auto
  smb_port: 445

  set_timeout: 900
```
BTW, I copy the PowerShell code in saltstack doc here. 
The /etc/salt/windows-firewall.ps1 is same as https://docs.saltstack.com/en/latest/topics/cloud/windows.html
### provider configs
```
[root@salt-master~]# cat /etc/salt/cloud.providers.d/win-cufe.conf
win-cufe:
  driver: vmware
  user: '2010110110@test'
  password: 'test@2015'
  url: '192.168.111.30'
  protocol: 'https'
  port: 443
```

### Versions Report
```
[root@salt-master~]# salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-123.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
`
Package winexe-1.1-b787d2.el7.x86_64 already installed and latest version
`
```
Requirement already satisfied (use --upgrade to upgrade): pyWinrm in /usr/lib64/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): xmltodict in /usr/lib/python2.7/site-packages (from pyWinrm)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.9.1 in /usr/lib/python2.7/site-packages (from pyWinrm)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages (from pyWinrm)
Requirement already satisfied (use --upgrade to upgrade): requests-ntlm>=0.3.0 in /usr/lib/python2.7/site-packages (from pyWinrm)
Requirement already satisfied (use --upgrade to upgrade): python-ntlm3 in /usr/lib/python2.7/site-packages (from requests-ntlm>=0.3.0->pyWinrm)
```
I also install the pyVmomi 2014.1.1 for python2.7.5
thankyou for your help.
