### ISSUE TITLE
Scheduled highstate reports success when highstate failed.

### ISSUE THREAD

**Issue by scubahub** [saltstack/salt#36114]
### Description of Issue/Question

I am using a custom returner so that I can generate events that get sent to the master when a job is run from the salt scheduler.  The reactor on the master triggers a runner that sends alerts when scheduled jobs fail.  Jobs, such as highstate, where the "return" data provided to the returner is a dict always report "success" as True even though individual states return values in the "return" dict fail.
### Setup

Schedule pillar shared by all minions:

```
schedule:
  highstate-before-midnight-pst:
    name: highstate
    function: state.apply
    run_on_start: False
    kwargs:
      test: False
    seconds: 1800 {#- 30 minutes #}
    splay: 1200
    range:
      start: 9:00pm
      end: 11:59pm
    returner: schedule-returner
    maxrunning: 3
```

On one minion there is a persistent failure regarding one ssh key that shows up in the "return" dict:

```
{
    ...
    "ssh_known_hosts_|-add-known-host-foo_|-present": {
        "__run_num__": 164,
        "changes": {},
        "comment": "Remote host public key found but its fingerprint does not match one you have provided",
        "duration": 215.297,
        "name": "<REDACTED>",
        "result": false,
        "start_time": "15:31:09.962431"
    },
    ...
```

yet the "success" value reported to the returner is True.
### Versions Report

```
Salt Version:
           Salt: 2015.8.11

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```
