### ISSUE TITLE
bsd_shadow module : Python's pwd module doesn't retrieve the password hash anymore

### ISSUE THREAD

**Issue by mguegan** [saltstack/salt#36112]
### Description of Issue/Question
Since Python 2.7.12 (not sure : I haven't found the bug report), it seems that `pwd.getpwnam` doesn't read the `/etc/master.passwd` file anymore on OpenBSD 6.0. Which is the correct behavior I think : `pwd` module for `/etc/passwd` and `spwd` module for `/etc/master.passwd`.

As a result, the `shadow` module password test fails and Salt tries to update the passwd at each runs. The side-effect is the state 'user.present' always returns a `False`.

### Setup
 - OpenBSD 6.0
 - salt-2016.3.1p1 (OpenBSD package)

### Steps to Reproduce Issue
```
# salt-call shadow.info username
local:
    ----------
    change:
        0
    expire:
        0
    name:
        username
    passwd:
        * <--- THIS IS THE PROBLEM
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul 25 2016, 16:14:54)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:
        machine: amd64
        release: 6.0
         system: OpenBSD
        version: Not Installed
```
