### ISSUE TITLE
Authorization support required in ext_pillar http_json modules.

### ISSUE THREAD

**Issue by zhujinhe** [saltstack/salt#36138]
**salt**['http.query'] function support lots of parameters via utils/http.py.
However, only 'url' parameter supported in salt/salt/pillar/http_json.py now.
Could we add support for other parameters such as header_dict so that we can do some authorization stuff by:

```
  ext_pillar:
    - http_json:
        url: http://example.com/api/minion_id
        header_dict: {foo: bar}
        key_foo: value_bar
```
