### ISSUE TITLE
file.managed source_hash fails with 'invalid format' for a SHA1 and MD5 hash in a file hosted over HTTP

### ISSUE THREAD

**Issue by adammichalik** [saltstack/salt#36140]
This is regression between 2015.8.12 and 2016.3.3

My SLS:

```
/opt/myfile:
  file.managed:
    - source: http://1.2.3.4:8081/service/local/artifact/maven/content?g=com.example&a=myartifact&v=1.0&c=exec&r=releases
    - source_hash: http://1.2.3.4:8081/service/local/artifact/maven/content?g=com.example&a=myartifact&v=1.0&c=exec&r=releases&e=jar.sha1
```

This is a Maven repository of Java JAR artifacts. Each JAR file is accompanied by a SHA1 file that can be retrieved by adding `&e=jar.sha1` to the JAR URL as seen above. The hash file contains just the hash.

Curl retrieves the file without issues:
```
$ curl  'http://1.2.3.4:8081/service/local/artifact/maven/content?g=com.example&a=myartifact&v=1.0&c=exec&r=releases&e=jar.sha1'
1c127f2f38c8412cafcc14c9aa8de83c18ecdf60
```
But salt fails with an error:

```
Source hash http://1.2.3.4:8081/service/local/artifact/maven/content?g=com.example&a=myartifact&v=1.0&c=exec&r=releases&e=jar.sha1 format is invalid. It must be in the format <hash type>=<hash>, or it must be a supported protocol: salt, file, http, https, ftp, swift, s3
```

The same failures occur for an MD5 hash which can be used alternatively.

I'm not sure if this is related to/duplicate of #25691 since that issue refers to older Salt versions and 2015.8.12 works fine in my case.
Perhaps related to/duplicate of #35932.

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
