### ISSUE TITLE
FreeBSD fails to start daemons with salt-cloud

### ISSUE THREAD

**Issue by jtand** [saltstack/salt#36197]
### Description of Issue/Question
When provisioning a freebsd vm with salt-cloud and bootstrap-salt.sh the preseeded key gets put into /etc/salt, when it should be put into /usr/local/etc/salt/. When using just bootstrap and starting the minion service by hand key's are populated appropriately.

### Setup
`salt-cloud -p <cloud-provider>-freebsd10 test-freebsd10`

If you're using rackspace it looks like, `salt-cloud -p rs-freebsd10 test-freebsd10`

### Steps to Reproduce Issue
Wait for the salt-cloud provision to finish and fail.

On the new freebsd minion check both /etc/salt/pki/ and /usr/local/etc/salt/pki/. Both directories will have the key placed in them. 

### Versions Report
```yaml
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 3.8.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: 0.3.7
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: x86_64
        release: 4.1.3
         system: Linux
        version: Not Installed
```
