### ISSUE TITLE
Question: How does pillar merge values from included sls files ?

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#36206]
I'm trying to define three levels of parameters for an application:
The idea I'm trying to implemnet is installing application that has global default, regional default and local parameters.
So I've put up a follwing definitions:

Local is assigned to minion
top.sls:

```
...
- match: grain
- applications.local
```

Local includes regional:
/applications/local.sls

```
include:
  - applications.regional

applications:
  params:
    param1: local
```

Regional includes default:
/applications/regional.sls

```
include:
  - applications

applications:
  params:
    param1: regional
```

Default params:
applications/init.sls

```
applications:
  params:
    param1: global
```

The minion then has the following pillar:

```
   params:
        ----------
        param1:
            global
```

So what is the rule pillar uses when including values from sls files ?
