### ISSUE TITLE
system.set_computer_name not working

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#36243]
When trying to set the computer name on the Windows Machine using `system.set_computer_name`, it returns false

### Setup
Linux Master and Windows Minion

### Steps to Reproduce Issue
```
salt \* system.set_computer_name win-test
win:
    False
```
```
salt \* system.get_pending_computer_name
win:
    ????
```
### Versions Report
```
Master

Salt Version:
           Salt: 2016.9.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 4.6.5-x86_64-linode71
         system: Linux
        version: CentOS Linux 7.0.1406 Core
```

```
Minion

win:
    Salt Version:
               Salt: 2016.9.0
     
    Dependency Versions:
               cffi: 1.7.0
           cherrypy: 7.1.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.8
              ioflo: 1.5.5
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.4.1
                ZMQ: 4.1.5
     
    System Versions:
               dist:   
            machine: AMD64
            release: 7
             system: Windows
            version: 7 6.1.7601 SP1 Multiprocessor Free
```
