### ISSUE TITLE
salt-ssh: grains set in the roster not working in all contexts

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#36313]
### Description of Issue/Question

  I set a grain in the salt-ssh roster, and then use it in the code. It is used in a map.jinja file, and references to variables in the map.jinja work in sls files, but throw an error in the jinja template for a config file.
### Setup

```
roster:
op-test-01.dev.us-west-1.aws.acme.com:
  host: op-test-01.dev.us-west-1.aws.acme.com
  sudo: True
  grains:
    is_ssh: 2
    op_env: staging
```

```
defaults/map.jinja:
{% import '_grains/map.jinja' as grain %}

{% load_yaml as defaults %}
  dir: /etc/default
  state:
    name: default
{% endload %}

{% set default = salt['pillar.get'](defaults.state.name, default=defaults, merge=True) %}
```

```
op/map.jinja:
{% import '_grains/map.jinja' as grain %}
{% from 'default/map.jinja' import default with context %}

{% load_yaml as defaults %}
  account:
    fullname: op
    group: op
    shell: /bin/bash
    user: op
    uid: 11005
  celery:
    init:
      file: celeryd
  config:
    dir: /data/op-{{ grains['op_env'] }}/configs
  data:
    dir: /data/op-{{ grains['op_env'] }}
  default:
    dir: {{ default.dir }}
    env:
      file: op-{{ grains['op_env'] }}
    file: op
  state:
    name: op
{% endload %}

{% set toplevel = salt['pillar.get'](defaults.state.name, default=defaults, merge=True) %}
{% set region_env_cluster = salt['pillar.get'](defaults.state.name ~ ':' ~ grain.region ~ ':' ~ grain.env ~ ':' ~ grain.cluster, default=toplevel, merge=True) %}

{% set op = region_env_cluster %}

```

```
op/files.sls:
{% from 'op/map.jinja' import op with context %}

op_data_dir:
  file.directory:
    - name: {{ op.data.dir }}
    - user: {{ op.account.user }}
    - group: {{ op.account.group }}
    - mode: 0755

op_tar_file:
  file.managed:
    - name: {{ op.data.dir }}/{{ op.tar.file }}
    - source: salt://op/files/artifacts/{{ op.tar.file }}
    - user: root
    - group: root
    - mode: 0644

op_extract_tar:
  cmd.run:
    - cwd: {{ op.data.dir }}
    - name: "tar xf {{ op.tar.file }}"

op_remove_tar:
  file.absent:
    - name: {{ op.data.dir }}/{{ op.tar.file }}


op_log_dir:
  file.directory:
    - name: {{ op.log.dir }}
    - user: {{ op.account.user }}
    - group: {{ op.account.group }}
    - mode: 0755

op_pid_dir:
  file.directory:
    - name: {{ op.pid.dir }}
    - user: {{ op.account.user }}
    - group: {{ op.account.group }}
    - mode: 0755

op_celery_init_file:
  file.managed:
    - name: {{ op.init.dir }}/{{ op.celery.init.file }}
    - user: root
    - group: root
    - mode: 0755

op_default_file:
  file.managed:
    - name: {{ op.default.dir }}/{{ op.default.env.file }}
    - source: salt://op/files{{ op.default.dir }}/{{ op.default.file }}
    - user: root
    - group: root
    - mode: 0644
    - template: jinja
```

```
ops/files/etc/default/op:
{%- from 'op/map.jinja' import op with context -%}
BASEDIR="{{ op.data.dir }}"

CELERYD_NODES="op"

CELERYD_CHDIR="${BASEDIR}"

CELERYD_OPTS='--executable={{ op.data.dir }}/venv/bin/python'

CELERY_CONFIG_MODULE="celery_config"
export CELERY_CONFIG_MODULE

CELERYD_LOG_LEVEL="{{ op.log.level }}"

CELERYD_LOG_FILE="{{ op.log.dir }}/{{ op.log.file }}"
CELERYD_PID_FILE="{{ op.pid.dir }}/{{ op.pid.file }}"

CELERYD_USER="{{ op.account.user }}"
CELERYD_GROUP="{{ op.account.group }}"

```

```
salt-ssh -i 'op-test-01.dev.us-west-1.aws.acme.com' state.highstate
op-test-01.dev.us-west-1.aws.acme.com:
  Name: bob_pkgs - Function: pkg.installed - Result: Clean Started: - 14:28:27.803959 Duration: 260.411 ms
  Name: /etc/profile.d - Function: file.recurse - Result: Clean Started: - 14:28:28.079977 Duration: 83.055 ms
  Name: /etc/ld.so.conf.d - Function: file.recurse - Result: Clean Started: - 14:28:28.163137 Duration: 61.642 ms
  Name: alice_pkgs - Function: pkg.installed - Result: Clean Started: - 14:28:28.224883 Duration: 2.636 ms
  Name: op_mongodb_us-west-1_dev_test_common_app_password - Function: test.check_pillar - Result: Clean Started: - 14:28:28.229105 Duration: 0.306 ms
  Name: op_rabbitmq_us-west-1_dbusers_user_password - Function: test.check_pillar - Result: Clean Started: - 14:28:28.229486 Duration: 0.247 ms
  Name: op - Function: group.present - Result: Clean Started: - 14:28:28.230760 Duration: 0.283 ms
  Name: op - Function: user.present - Result: Clean Started: - 14:28:28.233989 Duration: 0.795 ms
  Name: /data/op-staging - Function: file.directory - Result: Changed Started: - 14:28:28.234860 Duration: 0.656 ms
  Name: /data/op-staging/op_20160914-1-0.5.0-d9f0d06-1.tar.gz - Function: file.managed - Result: Changed Started: - 14:28:28.235599 Duration: 349.235 ms
  Name: tar xf op_20160914-1-0.5.0-d9f0d06-1.tar.gz - Function: cmd.run - Result: Changed Started: - 14:28:28.588578 Duration: 995.392 ms
  Name: /data/op-staging/op_20160914-1-0.5.0-d9f0d06-1.tar.gz - Function: file.absent - Result: Changed Started: - 14:28:29.584133 Duration: 4.184 ms
  Name: /var/log/op-staging - Function: file.directory - Result: Clean Started: - 14:28:29.588436 Duration: 0.672 ms
  Name: /var/run/op-staging - Function: file.directory - Result: Clean Started: - 14:28:29.589191 Duration: 0.554 ms
  Name: /data/op-staging/scripts/etc/init.d/celeryd - Function: file.managed - Result: Changed Started: - 14:28:29.589824 Duration: 0.69 ms
----------
          ID: op_default_file
    Function: file.managed
        Name: /etc/default/op-staging
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/var/tmp/.edgan_62a99a_salt/py2/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/var/tmp/.edgan_62a99a_salt/py2/salt/loader.py", line 1652, in wrapper
                  return f(*args, **kwargs)
                File "/var/tmp/.edgan_62a99a_salt/py2/salt/states/file.py", line 1644, in managed
                  **kwargs
                File "/var/tmp/.edgan_62a99a_salt/py2/salt/modules/file.py", line 3953, in check_managed_changes
                  **kwargs)
                File "/var/tmp/.edgan_62a99a_salt/py2/salt/modules/file.py", line 3623, in get_managed
                  **kwargs)
                File "/var/tmp/.edgan_62a99a_salt/py2/salt/utils/templates.py", line 178, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/var/tmp/.edgan_62a99a_salt/py2/salt/utils/templates.py", line 386, in render_jinja_tmpl
                  buf=tmplstr)
              SaltRenderError: Jinja variable 'salt.utils.context.NamespacedDictWrapper object' has no attribute 'op_env'
              /var/tmp/.edgan_62a99a_salt/running_data/var/cache/salt/minion/files/base/op/map.jinja(17):
              ---
              [...]
                  uid: 11005
                celery:
                  init:
                    file: celeryd
                config:
                  dir: /data/op-{{ grains['op_env'] }}/configs    <======================
                data:
                  dir: /data/op-{{ grains['op_env'] }}
                default:
                  dir: {{ default.dir }}
                  env:
              [...]
              ---
     Started: 14:28:29.590598
    Duration: 101.294 ms
     Changes:   

Summary for op-test-01.dev.us-west-1.aws.acme.com
-------------
Succeeded: 15 (changed=5)
Failed:     1
-------------
Total states run:     16
Total run time:    1.862 s
```
### Versions Report

2016.3.3

```
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.12 (default, Sep  2 2016, 14:46:00)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist: fedora 24 Twenty Four
        machine: x86_64
        release: 4.7.3-200.fc24.x86_64
         system: Linux
        version: Fedora 24 Twenty Four
```

**Comment by edgan** [comment]
Working around this by using a pillar instead of a grain.

**Comment by Ch3LL** [comment]
i'm runnign into some errors with the current test case you provided. 

```
[CRITICAL] Rendering SLS 'base:op.files' failed: Jinja variable 'jinja2.environment.TemplateModule object' has no attribute 'region'
/var/tmp/.root_402379_salt/running_data/var/cache/salt/minion/files/base/op/map.jinja(28):
---
[...]
  state:
    name: op
{% endload %}

{% set toplevel = salt['pillar.get'](defaults.state.name, default=defaults, merge=True) %}
{% set region_env_cluster = salt['pillar.get'](defaults.state.name ~ ':' ~ grain.region ~ ':' ~ grain.env ~ ':' ~ grain.cluster, default=toplevel, merge=True) %}    <======================
```
I believe I would need your pillar data for the region_env_cluster. Or maybe could you provide a simpler test c ase to help replicate this issue? Thanks

**Comment by edgan** [comment]
I don't think the pillars are needed.

Remove:
```{% set toplevel = salt['pillar.get'](defaults.state.name, default=defaults, merge=True) %}
{% set region_env_cluster = salt['pillar.get'](defaults.state.name ~ ':' ~ grain.region ~ ':' ~ grain.env ~ ':' ~ grain.cluster, default=toplevel, merge=True) %}

{% set op = region_env_cluster %}```

Change:
```
{% load_yaml as defaults %}
```
to
```
{% load_yaml as op %}
```

**Comment by Ch3LL** [comment]
Okay I had to simplify the example because I was still getting even more errors about _grains/map.jinj not existing and etc. but i'm not able to replicate the behavior it seems to be working for me. Here is my test case:

op/files.sls:

```
[root@cdf0b28f79c5 salt]# cat op/files.sls 
{% from 'op/map.jinja' import op with context %}

test:
  cmd.run:
    - name: echo {{ op.config.dir }}
```

```
[root@cdf0b28f79c5 salt]# cat op/map.jinja 
{% from 'default/map.jinja' import default with context %}

{% load_yaml as op %}
  account:
    fullname: op
    group: op
    shell: /bin/bash
    user: op
    uid: 11005
  celery:
    init:
      file: celeryd
  config:
    dir: /data/op-{{ grains['op_env'] }}/configs
  data:
    dir: /data/op-{{ grains['op_env'] }}
  default:
    dir: {{ default.dir }}
    env:
      file: op-{{ grains['op_env'] }}
    file: op
  state:
    name: op
{% endload %}
```

```
[root@cdf0b28f79c5 salt]# cat default/map.jinja 

{% load_yaml as defaults %}
  dir: /etc/default
  state:
    name: default
{% endload %}

{% set default = salt['pillar.get'](defaults.state.name, default=defaults, merge=True) %}
```

roster file:

```
[root@cdf0b28f79c5 salt]# cat /etc/salt/roster 
# Sample salt-ssh config file
web1:
  host: <ip>
  user: ec2-user # Remote executions will be executed as user fred
  priv: /root/.ssh/sshkey # The password to use for login, if omitted, keys are used
  grains:
    is_ssh: 2
    op_env: staging
```


```
[root@cdf0b28f79c5 salt]# salt-ssh '*' state.sls op.files
web1:
----------
          ID: test
    Function: cmd.run
        Name: echo /data/op-staging/configs
      Result: True
     Comment: Command "echo /data/op-staging/configs" run
     Started: 21:32:34.192688
    Duration: 23.802 ms
     Changes:   
              ----------
              pid:
                  8784
              retcode:
                  0
              stderr:
              stdout:
                  /data/op-staging/configs

Summary for web1
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
```

Does this smaller examplework in your instance? maybe there is something i'm missing from my simplified test case?

**Comment by manjiki** [comment]
I think I am having a similar salt-ssh issue with `salt['grains.get']` and `salt['pillar.get']` when running highstate.

I have the following .sls: 

```
{%- for app, data in salt['pillar.get']('apps').items() %}
{{data.user}}:
  user.present: 
    - home: {{data.root_dir}}
{%- endfor %}
```
It runs fine when I run the individual state:
```
# salt-ssh 'test1' state.sls apps
```
But fails when I run highstate:
```
# salt-ssh 'test1' state.highstate

[ERROR   ] Rendering exception occurred: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pillar.get'
[CRITICAL] Rendering SLS 'base:apps' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pillar.get'

test1:
    - Rendering SLS 'base:apps' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pillar.get'
```

If I substitute `salt['pillar.get']('apps')` with `pillar.get('applications')`, highstate runs properly.  I have the exact same issue when using `salt['grains.get']` to pull grains from the roster file.

**Comment by edgan** [comment]
Here is a much simpler example.

```
Saltfile:
salt-ssh:
  config_dir: .
  max_procs: 1
  ssh_wipe: True
  extra_filerefs:
    - salt://testing/map.jinja

roster:
server.acme.com:
  host: server.acme.com
  sudo: True
  grains:
    ops:
      cluster: foo

testing/map.jinja:

{% load_yaml as testing %}
  filename: testing_{{ salt['grains.get']('ops:cluster') }}
{% endload %}
```

Success:
"testing_foo" in /tmp/test_file
```
{% from 'testing/map.jinja' import testing with context %}

testing_test_file:
  file.managed:
    - name: /tmp/test_file
    - user: root
    - group: root
    - mode: 0644
    - contents: {{ testing.filename }}
```
Failure:
"testing_" in /tmp/test_file
```
{% from 'testing/map.jinja' import testing with context %}
testing_test_file:
  file.managed:
    - name: /tmp/test_file
    - source: salt://testing/files/test_file
    - user: root
    - group: root
    - mode: 0644
    - template: jinja

files/test_file:
{%- from 'testing/map.jinja' import testing with context -%}
{{ testing.filename }}```
