### ISSUE TITLE
Invalid warnings regarding cmd.run python_shell

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#36320]
### Setup

I have a simple state file called resolvconf.sls with the following contents:

```
resolvconf:
  pkg:
    - installed

/etc/resolvconf/resolv.conf.d/base:
  file.append:
    - text: search {{ salt['cmd.run'](cmd='/bin/dnsdomainname', python_shell=False) }}
    - require:
      - pkg: resolvconf
```

That should not produce any warnings, and yet I get the following each time the state is executed:

`[WARNING ] /usr/lib/python2.7/dist-packages/salt/utils/templates.py:73: DeprecationWarning: Starting in 2015.5, cmd.run uses python_shell=False by default, which doesn't support shellisms (pipes, env variables, etc). cmd.run is currently aliased to cmd.shell to prevent breakage. Please switch to cmd.shell or set python_shell=True to avoid breakage in the future, when this aliasing is removed.`

I should not receive a warning because I have explicitly set the value of python_shell, and I am not using any shellisms in my command.
### Steps to Reproduce Issue

Just run the above state file and watch the warnings appear.
### Versions Report

```
# apt-cache policy salt-minion | head -n 3
salt-minion:
  Installed: 2016.3.3-1
  Candidate: 2016.3.3-1
# salt-call --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
```

This is on an upgraded minion, but the warning is still there. BTW, this happens a lot - the git tagged release does not report the correct version. Really, the tagged commit should be the one where the version is bumped. I believe that's what's normally done, and it would make things less confusing.
