### ISSUE TITLE
Feature request: add thin-provisioning for LXC containers

### ISSUE THREAD

**Issue by jandd** [saltstack/salt#36327]
### Feature description

salt.modules.lxc and salt.states.lxc do already support containers on LVM volumes which is great. LXC allows to use LVM thin pools which are not supported in the current saltstack code.

I would like to introduce a new parameter thinpool in addition to the existing vgname and lvname parameters. A new salt state declaration in an sls file using this feature could look like this:

```yaml
/dev/sdb:
  lvm.pv_present

my_vg:
  lvm.vg_present:
    - devices: /dev/sdb

lxcpool:
  lvm.lv_present:
    - vgname: my_vg
    - size: 5G
    - kwargs:
      - discards: passdown
      - thinpool: True

firstlxc:
  lxc.present:
    - running: True
    - template: debian
    - backing: lvm
    - vgname: my_vg
    - lvname: lxc_first
    - thinpool: lxcpool
    - require:
      - lvm: lxcpool
```

The development branch already has code to create LVM thinpool support since 35dc150a0088d12cbbe1e04b8cdaf1eecc14df9a which is a good base for this new feature.

### Versions Report

github development branch at dedfd828947a96b1b999db242282e54dd4d7f605
