### ISSUE TITLE
mysql_grants.present doesn't support SUPER

### ISSUE THREAD

**Issue by dkinon** [saltstack/salt#36385]
### Description of Issue/Question

Trying to apply special permissions grants like "SUPER" to a mysql user fails via salt but succeeds if run directly in mysql.
### Setup

Create mysql user with super grant:

```
salttest mysql account localhost:
  mysql_user.present:
    - name: salttest
    - host: 'localhost'
    - password: <#################>
  mysql_grants.present:
    - grant: super
    - database: '*.*'
    - user: salttest
    - host: 'localhost'
```
### Steps to Reproduce Issue

run salt state and get the following output:

```
----------
          ID: salttest mysql account localhost
    Function: mysql_grants.present
      Result: False
     Comment: Failed to execute: "GRANT super ON *.* TO salttest@localhost"
     Started: 15:49:49.320044
    Duration: 6.63 ms
     Changes:
```

run resulting query from failure above directly in mysql:

```
mysql> GRANT super ON *.* TO salttest@localhost;
Query OK, 0 rows affected (0.00 sec)
```
### Versions Report

Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
   python-gnupg: 0.3.7
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.12.2.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final

Tested this with older minion and 2016.3.1 minion with same results
