### ISSUE TITLE
pkg.list_upgrades return debug information rather than packages list

### ISSUE THREAD

**Issue by qurczak** [saltstack/salt#36388]
### Description of Issue/Question

list_packages display "downloading": "community.db...", should be "package": "version" 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
salt '*' pkg.list_upgrades refresh=True --out=json

{
    "asus-p7f-x": {
        "python2-msgpack": "0.4.8-1",
        "pango": "1.40.3-1",
        "downloading": "community.db...",
        "flashplugin": "11.2.202.635-1"
    }
}
{
    "cube.lan": {
        "pango": "1.40.3-1",
        "downloading": "aur.db..."
    }
}
```
Additional info 

```
[TRACE   ] data = {'cube.lan': {'pango': '1.40.3-1', 'downloading': 'aur.db...'}}
cube.lan:
    ----------
    downloading:
        aur.db...
    pango:
        1.40.3-1
```
/etc/pacman.conf

```
[options]
HoldPkg     = pacman glibc
Architecture = armv7h
Color
CheckSpace
VerbosePkgLists
SigLevel = Optional TrustAll
SigLevel = Never
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[community]
Include = /etc/pacman.d/mirrorlist
[alarm]
Include = /etc/pacman.d/mirrorlist
[aur]
Include = /etc/pacman.d/mirrorlist
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: 6.2.0.post20160805
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.0
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.4.5
       M2Crypto: 0.24.0
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.4.20-1-lts
         system: Linux
        version: Not Installed
```
