### ISSUE TITLE
salt-ssh minion_opts not applied for managed files

### ISSUE THREAD

**Issue by rmohta** [saltstack/salt#36390]
### Description of Issue/Question

minion_opts defined for a minion within roster is not applied, when using jinja template for a managed file. 
Please note, they work well for a SLS file
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
#### config/roster

Typically grains['id'] would have  returned the name -in this case db_env35_E0. But as I have minion_opts, and within that I override grains['id'] as 'rmohta'

```
db_env35_E0:
  host: xxx.com
  user: rmohta
  minion_opts:
    grains:
      ORASID: "xx"
      env_leasedto: "xx"
      id: rmohta
      type: xx

```
#### drop.sls

```
/home/{{ grains['id'] }}/.setup/db/remove/schema:
  file.absent

/home/{{ grains['id'] }}/.setup/db/remove/schema/00_lock_spoolgenerator.sql:
  file.managed:
    - source: salt://db/schema/deploy/destroy_schema/00_lock_spoolgenerator.sql
    - source_hash: md5=xxxxxxxx
    - makedirs: True
    - dir_mode: 750
    - mode: 540
    - user: {{ grains['id'] }}
    - group: {{ pillar['env_data']['app_group'] }}
    - template: jinja
    - context:
        type: {{ grains['type'] }}
        db_data: {{ pillar['db_data'] }}

```
#### Relevant piece of 00_lock_spoolgenerator.sql

```
[master]$ cat states/db/schema/deploy/destroy_schema/00_lock_spoolgenerator.sql
set serveroutput ON;
spool off

spool /home/{{ grains['id'] }}/.setup/db/{{ type }}/01_lock_users.sq

```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

   For the first part of drop.sls, grains['id'] evaluate to the override value of 'rmohta'. 
   This is what I would have expected, and that's good.

```
----------
          ID: /home/rmohta/.setup/db/remove/schema
    Function: file.absent
      Result: True
     Comment: Removed directory /home/rmohta/.setup/db/remove/schema
     Started: 18:32:14.206523
    Duration: 0.698 ms
     Changes:
              ----------
              removed:
                  /home/rmohta/.setup/db/remove/schema

```

  The managed file _00_lock_spoolgenerator.sql_ **does not use** the override value. It uses the actual id.

```
[minion]$ cat 00_lock_spoolgenerator.sql
set serveroutput ON;
spool off

spool /home/db_env35_E0/.setup/db/db_env35_E0_test/01_lock_users.sq
```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
[master]$ salt-ssh --versions-report
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.5.5
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.08
          PyZMQ: 14.5.0
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 5.9 Tikanga
        machine: x86_64
        release: 2.6.18-308.el5
         system: Red Hat Enterprise Linux Server 5.9 Tikanga
```
