### ISSUE TITLE
Cannot pass pillar data to state when running orchestrate

### ISSUE THREAD

**Issue by giany** [saltstack/salt#36401]
My orchestrate looks like : 
```generate_cert:
  salt.state:
    - name: cmd.run
    - tgt: 'salt'
    - sls:
      - general.tls
```

In init.sls from general.tls I have:

```
{% set cluster = pillar.get('server', {}) -%}
sudo:
  pkg.installed

salt://general/tls/create-tls.sh:
  cmd.script:
    - args: {{ cluster }}.domain.io
```
Running this using: 
```
salt-run -l debug state.orchestrate orch.nginx pillar='{"server": "boo"}'
```
returns this error:

```
ID: generate_cert
    Function: salt.state
        Name: cmd.run
      Result: False
     Comment: Run failed on minions: web
              Failures:
                  domain.io:
                      - Rendering SLS 'base:general.tls' failed: while parsing a block mapping
                          in "<unicode string>", line 6, column 7:
                                - args: {}.domain.io
                                  ^
                        expected <block end>, but found '<scalar>'
                          in "<unicode string>", line 6, column 15:
                                - args: {}.domain.io
                                          ^
     Started: 08:27:30.520802
    Duration: 298.221 ms
     Changes:
```

From what I understand..the pillar data from orchestrate does not reach state file..

**Comment by gtmanfred** [comment]
The pillars from the command line are not passed through to the state from salt-run, you will need to pass them through to the salt.state again.

should be able to just use
```
  salt.state:
    - name: cmd.run
    - tgt: 'salt'
    - sls:
      - general.tls
    - pillar: {{pillar}}
```
