### ISSUE TITLE
salt.states.boto_ec2.instance_present: don't recreate instance if tags list changes

### ISSUE THREAD

**Issue by kakwa** [saltstack/salt#36400]
### Description of Issue/Question

The boto_ec2.instance_present recreate a whole instance if the tags are modified, It would be nicier if it could only update the tags of the existing instance if it exists already.
### Setup

declaration step 1:

``` yaml
boto_ec2.instance_present:
  - name: my instance
  - image_id: ami-e079f893
  - tags:
      tag_old: value
```

declaration step 2

``` yaml
boto_ec2.instance_present:
  - name: my instance
  - image_id: ami-e079f893
  - tags:
      tag_old: value
      tag_new: value
```
### Steps to Reproduce Issue

Apply the state step 1 then state step 2. A new instance is created.
### Versions Report

Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.4
