### ISSUE TITLE
salt-cloud hangs indefinitely during provision if one or more vmware providers are broken

### ISSUE THREAD

**Issue by cetanu** [saltstack/salt#36430]
### Setup

Provider setup:

```
good:
  driver: vmware
  username: <username>
  password: <password>
  url: good.domain.com

bad:
  driver: vmware
  username: <username>
  password: <password>
  url: other.domain.com
  port: 999  # Broken
```

Profile setup:

```
good_profile:
  minion: {master: none}
  provider: good
  datacenter: <dc>
  cluster: <cluster>
  domain: wherever.com
  dns_servers:
    - 10.10.10.10
    - 10.10.10.11

  clonefrom: <template>
  template: False
  ssh_username: root
  password: <template_password>

  power_on: True
  customization: True
  deploy: True
  delete_sshkeys: True

  devices:
    network:
      Network adapter 1:
        name: mynet
        switch_type: standard
        ip: 10.10.10.100
        subnet_mask: 255.255.255.0
        gateway: 10.10.10.1
```
### Steps to Reproduce Issue

```
myserver:/ # salt-cloud --profile=good_profile <hostname>
[INFO    ] salt-cloud starting
Could not connect to host 'bad'. Please check the debug log for more information.
```

As far as I understand, this is a super generic error message, from here: https://github.com/saltstack/salt/blob/develop/salt/utils/vmware.py#L216

Trying to understand why it would even check the provider that doesn't work, when I am explicitly telling it which provider to use (via the profile configuration)

Is this intended?
### Versions Report

```
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 3.12.62-60.62-default
         system: SUSE Linux Enterprise Server  12 x86_64
```
