### ISSUE TITLE
The service.running and service.enable states do not add services to chkconfig

### ISSUE THREAD

**Issue by tristianc** [saltstack/salt#36470]
### Description of Issue/Question

The service.running and service.enable states do not add scripts to chkconfig in RHEL6. I expected them to, since they both call the service.enable module, which does add init scripts to chkconfig.

### Setup

This ...

```
copy_jboss-as_init_script:
  file.managed:
    - name: /etc/init.d/jboss-as
    - source: {{ jboss_home }}/bin/init.d/jboss-as-standalone.sh
    - user: root
    - group: root
    - mode: 655

jboss-as:
  service.running:
    - name: jboss-as
    - init_delay: 60
    - require:
      - file: copy_jboss-as_init_script
```
 
 produces this ...
 
```
 ----------
          ID: copy_jboss-as_init_script
    Function: file.managed
        Name: /etc/init.d/jboss-as
      Result: True
     Comment: File /etc/init.d/jboss-as is in the correct state
     Started: 13:41:48.118335
    Duration: 3.116 ms
     Changes:
----------
          ID: jboss-as
    Function: service.running
      Result: False
     Comment: The named service jboss-as is not available
     Started: 13:41:48.131657
    Duration: 14.914 ms
     Changes:
```
 
 when I put the former in a state called `jboss.sls` and run it with `salt-call state.sls jboss.sls`.
 
 When I run `chkconfig --list` to confirm that the RHEL6.8 is aware of the service, `jboss-as` is absent from the list. However, when I run `salt-call service.enable jboss-as`, I get:
 
 ```
 local:
    True
 ```
 
 Running `chkconfig --list` at this point shows that `chkconfig` is aware of the `jboss-as` service.
 
 Both the [`service.enable`](https://github.com/saltstack/salt/blob/develop/salt/states/service.py#L105) and [`service.running`](https://github.com/saltstack/salt/blob/develop/salt/states/service.py#L332) states perform an availability check first . However, both states subsequently call the salt module `service.enable`, [which will check if the init script exists and add said script to `chkconfig`](https://github.com/saltstack/salt/blob/develop/salt/modules/rh_service.py#L206). Depending on the states to add scripts to `chkconfig` puts me in a catch-22.
 
I know I can circumvent this problem by calling the `service.enable` module inside a state. Is this intended?

### Steps to Reproduce Issue

1. Create a state file called /srv/salt/hello.sls with the following code:
 
	```
	copy_hello_init_script:
	  file.managed:
	    - name: /etc/init.d/hello
	    - contents:
	    	- '#!/bin/sh'
	    	- echo 'Hello, World!'
	    - user: root
	    - group: root
	    - mode: 655
	
	hello:
	  service.running:
	    - name: hello
	    - enable: True
	    - require:
	      - file: copy_hello_init_script
	```

2. Run `salt-call state.sls hello`

#### Expected results:

All states are reported successful

#### Received results:

```
----------
          ID: copy_hello_init_script
    Function: file.managed
        Name: /etc/init.d/hello
      Result: True
     Comment: File /etc/init.d/hello updated
     Started: 15:42:06.389882
    Duration: 15.365 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,2 +1,2 @@
                  -None
                  +#!/bin/sh
                   echo 'Hello, World!'
----------
          ID: hello
    Function: service.running
      Result: False
     Comment: The named service hello is not available
     Started: 15:42:06.419124
    Duration: 17.818 ms
     Changes:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
```

### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.3.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago
```
