### ISSUE TITLE
Salt-cloud issue deploying VM to vcenter

### ISSUE THREAD

**Issue by jcherndon** [saltstack/salt#36527]
### Description of Issue/Question

I was using 2015.5 salt/salt-cloud to deploy vms on a vcenter.
I updated to 2016.3.2 and now I can't deploy vms anymore.
ran: salt-cloud -p Base test01
get: vim.fault.InvalidLogin
"Cannon complete login due to an incorrect user name or password"

I verified the providers.conf by running 
salt-cloud -f list_nodes vcenter
I then get a list of all the vms running on my vcenter

vmware.conf (sanitized):

```
vcenter:
  driver: vmware
  user: 'user'
  password: 'password'
  url: 'vcenter'
```
### Setup

salt/salt-cloud 2016.3.2
Centos 7.2
### Steps to Reproduce Issue

just did a yum update,
ran both salt-cloud -p Base test01 and salt-cloud -f list_nodes vcenter. The list_nodes returns correctly, salt-cloud -p doesn't
