### ISSUE TITLE
openstack auth with nova driver

### ISSUE THREAD

**Issue by abonillasuse** [saltstack/salt#36548]
### Description of Issue/Question

I'm unable to connect to my openstack setup, there might be a config line missing.
### Setup

```
geeko-land:
  identity_url: http://$IPofKeystone:5000/v3/auth/tokens
  auth_version: 3
  tenant: admin
  user: admin
  compute_region: RegionOne
  compute_name: nova
  password: MyPassWord
  ssh_key_name: abonilla
  ssh_key_file: /etc/salt/abonilla.pem
  driver: nova
```

I tried following
https://docs.saltstack.com/en/2015.8/ref/clouds/all/salt.cloud.clouds.nova.html
but using the keystone.user config fails 

```
[WARNING ] The required 'user' configuration setting is missing from the 'openstack-key:nova' driver, which is configured under the 'openstack-key' alias.
```

because it wants the older settings as documented on the openstack driver

https://docs.saltstack.com/en/latest/topics/cloud/config.html#openstack

(I know nova and openstack are separate drivers)
### Steps to Reproduce Issue

```
bash-4.2# salt-cloud --list-images=geeko-land
[INFO    ] salt-cloud starting
[ERROR   ] Failed to get the output of 'nova.avail_images()': The request you have made requires authentication. (HTTP 401)
geeko-land:
    ----------
```
### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.12 (default, Jul 01 2016, 15:34:22) [GCC]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: SuSE 42.1 x86_64
        machine: x86_64
        release: 4.4.19-moby
         system: openSUSE  42.1 x86_64
```
