### ISSUE TITLE
InfluxDB Database Present State not working

### ISSUE THREAD

**Issue by FabianEnvoy** [saltstack/salt#36556]
### Description of Issue/Question

Internal State "salt.states.influxdb_database.present" not working in sls File.
InfluxDB Installation successful and service is running and reachable. 
### State-File

```
influx-db-test:
  influxdb_database.present:
    - name: test
    - user: influxdb-user
    - password: ....
    - host: ....
    - port: ... 
    - require:
      - service: influxdb_start
```
### Error-Report

```
----------
          ID: influx-db-synthetic
    Function: influxdb_database.present
        Name: synthetic_profiles
      Result: False
     Comment: State 'influxdb_database.present' was not found in SLS 'influxdb.config'
              Reason: 'influxdb_database' __virtual__ returned False
     Started: 
    Duration: 
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5
```

**Comment by nilliams** [comment]
I noticed this as I just hit this recently so might be able to help ... do you have the `influxdb` Python package installed? The docs do state that you need it, though they only say so in the [module docs](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.influx.html) (see top), not the [state docs](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.influxdb_database.html).

Try adding this before your above state:
```
influxdb:
   pip.installed
```
**If you don't have `pip` installed you'll need to install that too!**

(And obvs you can use `require` etc to setup requisites if you want to make it more sound).

I do think the error you're getting (I saw the same) is not very useful though and could use improvement.

**Comment by babilen** [comment]
Do you have influxdb-python installed?

**Comment by babilen** [comment]
Oh, and I made extensive changes to the influxdb modules and states to support versions >= 0.9, but they haven't made it into a release. You might want to grab them from develop.

**Comment by nilliams** [comment]
Okay I do think my previous comment was correct, the Python `influxdb` package needs to be installed (as @babilen says), else I consistently get the reported error, however I'm still struggling to get things to work first time I apply states.

(Also I do think the error you're getting - I saw the same - could use improvement).

However, I still can't seem to get this to work first time. Seems to be a race condition despite my attempts to setup requisites

My `influxdb.sls` looks like:

```
influxdb_ppa:
  pkgrepo.managed:
    - humanname: InfluxDB PPA
    - name: deb https://repos.influxdata.com/ubuntu precise stable
    - file: /etc/apt/sources.list.d/influxdb.list
    - key_url: https://repos.influxdata.com/influxdb.key
    - require_in:
      - pkg: influxdb

install_influxdb:
  pkg.installed:
    - name: influxdb

run_influxdb:
  service.running:
    - name: influxdb
    - enable: True
    - require:
      - pkg: install_influxdb

# (in order for the `influxdb_database` salt states to work).
install_influxdb-python:
  pip.installed:
    - name: influxdb
    - require:
      - pkg: python-pip

playground_dev:
  influxdb_database.present:
    - port: 8086
    - require:
      - pip: install_influxdb-python
      - service: run_influxdb
```

Here's what I get first run:
```
           ID: install_influxdb
     Function: pkg.installed
         Name: influxdb
       Result: True
      Comment: The following packages were installed/updated: influxdb
      Started: 13:28:30.284701
     Duration: 67935.014 ms
      Changes:
               ----------
               influxdb:
                   ----------
                   new:
                       1.0.0-1
                   old:
 ----------
           ID: run_influxdb
     Function: service.running
         Name: influxdb
       Result: True
      Comment: Service influxdb is already enabled, and is running
      Started: 13:29:39.685798
     Duration: 1675.647 ms
      Changes:
               ----------
               influxdb:
                   True
 ----------
           ID: install_influxdb-python
     Function: pip.installed
         Name: influxdb
       Result: True
      Comment: All packages were successfully installed
      Started: 13:29:41.750791
     Duration: 7366.946 ms
      Changes:
               ----------
               influxdb==3.0.0:
                   Installed
 ----------
           ID: playground_dev
     Function: influxdb_database.present
       Result: False
      Comment: State 'influxdb_database.present' was not found in SLS 'influxdb'
               Reason: 'influxdb_database' __virtual__ returned False
      Started:
     Duration:
      Changes:
```

Second time, it works:
```
...
          ID: run_influxdb
    Function: service.running
        Name: influxdb
      Result: True
     Comment: The service influxdb is already running
     Started: 13:50:09.861124
    Duration: 326.979 ms
     Changes:
----------
          ID: install_influxdb-python
    Function: pip.installed
        Name: influxdb
      Result: True
     Comment: Python package influxdb was already installed
              All packages were successfully installed
     Started: 13:50:10.407386
    Duration: 925.715 ms
     Changes:
----------
          ID: playground_dev
    Function: influxdb_database.present
      Result: True
     Comment: Database playground_dev has been created
     Started: 13:50:11.356304
    Duration: 884.224 ms
     Changes:
              ----------
              playground_dev:
                  Present
```

@babilen, do you think this is something your latest changes are likely to solve?
