### ISSUE TITLE
dockerng.running downloads images in test=true

### ISSUE THREAD

**Issue by p-thurner** [saltstack/salt#36587]
### Description of Issue/Question

When I run dockerng.running in test=true it does things instead of saying that it would do things - it seems to download docker images for instead of just saying that it would do so.
Btw why does it download at all? I thought dockerng.image_present does this? Shouldnt dockerng.running fail if the image isnt present?

First run:

```
          ID: rancher_server_container
    Function: dockerng.running
        Name: rancher-server
      Result: None
     Comment: Container 'rancher-server' will be created
     Started: 00:45:26.067037
    Duration: 39270.397 ms
     Changes:   
              ----------
              image:
                  ----------
                  Layers:
                      ----------
                      Pulled:
                          - b171f9dbc13b
                          - ed40d4bcb313
                          - 96c6a1f3c3b0
                          - ccfc4df4fbba
                          - 9e4d5a1238bb
                          - f986ba0d224d
                          - 303d9649bb89
                          - 86a35696481e
                          - 56825bfb5bb7
                          - fabbcc718243
                          - eb2848176ff4
                          - 35489637da84
                          - 5c005e2df0e8
                          - 64ba16c4c9f4
                  Status:
                      Downloaded newer image for rancher/server:stable
                  Time_Elapsed:
                      39.2294640541
```

Second run:

```
          ID: rancher_server_container
    Function: dockerng.running
        Name: rancher-server
      Result: None
     Comment: Container 'rancher-server' will be created
     Started: 00:47:27.581069
    Duration: 10.533 ms
     Changes:  
```
### Setup

I used this state:

/srv/salt/test-container-running-issue.sls:

```
rancher_server_container:
  dockerng.running:
    - name: rancher-server
    - image: rancher/server:stable
    - environment:
      - CATTLE_DB_CATTLE_MYSQL_HOST: test
      - CATTLE_DB_CATTLE_MYSQL_PORT: test
      - CATTLE_DB_CATTLE_MYSQL_NAME: test
      - CATTLE_DB_CATTLE_USERNAME: test
      - CATTLE_DB_CATTLE_PASSWORD: test
    - port_bindings:
      - http://127.0.0.1:8080
    - restart_policy: always
#    - require:
#      - dockerng: rancher_server_image
```
### Steps to Reproduce Issue

salt 'testserver' state.sls 
### Versions Report

Both master and minion are  2016.3.3 (Boron) on Debian 8.
