### ISSUE TITLE
salt/cloud/*/created not being registered on the event bus

### ISSUE THREAD

**Issue by aronneagu** [saltstack/salt#36600]
### Description of Issue/Question
I would like to use `salt/cloud/*/created` tag with salt reactor to trigger a highstate on the minion (as per the documentation at http://salt-cloud.readthedocs.io/en/latest/topics/deploy.html) but I don't see this tag on the event bus.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Profile file:
```
eu-ireland-app-api-a:
  provider: eu-ireland-app-api
  image: ami-f0b11187
  size: t2.micro
  ssh_username: ubuntu
  subnetid: subnet-***
  securitygroupid:
    - sg-***
```

Provider file:
```
eu-ireland-app-api:
  minion:
    master: saltstack.optimy.net
    startup_state: highstate
  ssh_interface:
    private_ips
  id: ***
  key: ***
  private_key: /etc/salt/pki/salt-cloud.pem
  keyname: salt-cloud
  location: eu-west-1
  ssh_username: ubuntu
  provider: ec2
  grains:
    role: app-api
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
I created the minion using: `salt-cloud -p eu-ireland-app-api-a test` then ran `salt-run state.event pretty=true` on the master to see the tags on the event bus.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
