### ISSUE TITLE
user on bower.bootstrap doesn't seem to work

### ISSUE THREAD

**Issue by mtourne** [saltstack/salt#36652]
### Description of Issue/Question

user doesn't seem to fully work, the directory gets created with root and then the privilege drop down but the directory is not writable
### Setup

``` yaml
website_bower:
  bower.bootstrap:
    - user: ubuntu
    - name: {{ pillar['website_build_dir'] }}
    - require:
        - npm: bower
```
### Output

```
          ID: website_bower
    Function: bower.bootstrap
        Name: /home/ubuntu/site/web/
      Result: False
     Comment: Error bootstrapping '/home/ubuntu/site/web/':
              Error: EACCES, permission denied '/home/ubuntu/.config/configstore/bower-github.json'
              You don't have access to this file.

                  at Object.fs.openSync (fs.js:432:18)
                  at Object.fs.readFileSync (fs.js:286:15)
                  at Object.create.all.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
                  at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
                  at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
                  at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
                  at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
                  at Module._compile (module.js:456:26)
                  at Object.Module._extensions..js (module.js:474:10)
                  at Module.load (module.js:356:32)
     Started: 22:11:32.834335
    Duration: 622.122 ms
```
### Versions Report

Version is 2016.3.3 (Boron)
### Bad bower doc

Also the bower example in the doc is invalid :

``` yaml
npm:
  pkg.installed
git:
  pkg.installed
bower:
  npm.installed
  require:
    - pkg: npm
    - pkg: git
```

when it should be 

``` yaml
npm:
  pkg.installed

git:
  pkg.installed

bower:
  npm.installed:
    - require:
        - pkg: npm
        - pkg: git
```
