### ISSUE TITLE
cmd.run unless and onlyif do not work with pipes and python_shell=True does not help

### ISSUE THREAD

**Issue by rajivkukreja** [saltstack/salt#36734]
### Description of Issue/Question

I have tried every combination possible to make unless and onlyif clauses evaluate correctly when using pipes. Based on the documentation, the python_shell argument needs to be set to True (for saltstack to use the native shell and therefore honor pipes). This leads to a cryptic error. I am attaching an example of a state with the associated failure.
### Setup

Here's an example of the SLS 

```
stackdriver-agent-is-installed:
  cmd.run:
    - name: |
        sudo curl -O "https://repo.stackdriver.com/stack-install.sh"
        sudo bash stack-install.sh --write-gcm
    - python_shell: True
    - unless: ls -la /etc/default | grep "stackdriver-agent"
    - require:
      - cmd: license-is-applied
```
### Steps to Reproduce Issue

Leads to this error:

```
          ID: stackdriver-agent-is-installed
    Function: cmd.run
        Name: sudo curl -O "https://repo.stackdriver.com/stack-install.sh"
sudo bash stack-install.sh --write-gcm
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/cmd.py", line 821, in run
                  cret = mod_run_check(cmd_kwargs, onlyif, unless, creates)
                File "/usr/lib/python2.7/dist-packages/salt/states/cmd.py", line 347, in mod_run_check
                  cmd = __salt__['cmd.retcode'](unless, ignore_retcode=True, python_shell=True, **cmd_kwargs)
              TypeError: retcode() got multiple values for keyword argument 'python_shell'
     Started: 20:36:58.421144
    Duration: 17.375 ms
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
```

**Comment by cro** [comment]
@rajivkukreja Do you mind editing your comment and enclosing the YAML in triple-backticks?  That way we'll be able to see your indentation.

Also, does your minion run as root or as another user?

**Comment by rajivkukreja** [comment]
@cro - Missed your other question. It does run as root... triggered by 

```sudo salt 'search*' state.apply```

**Comment by cro** [comment]
If the minions run as root, why do you use `sudo` to call curl and run the resulting script?

Also, if you are not going to validate the install script, why not just pipe it directly to bash?

In any case, if you change the `name` key in the state to the following, does it work or still throw the stacktrace?

```
name: curl -O "https://repo.stackdriver.com/stack-install.sh" && bash stack-install.sh --write-gcm
```

**Comment by rajivkukreja** [comment]
@cro - I'm using ```sudo``` to make sure that the SLS files can withstand a change to the salt-minion process identity (if at a later point in time, we needed to switch that process to run as a more targeted user).

This SLS is just one of the 88 I picked because it had minimal dependencies - so easy to reproduce and test independently. But your point is well taken regarding the risk of running scripts from the internet without validation. We have since made local copies and validated the scripts logic.

That said, I did inline the 2 commands as you suggested above but that didn't change the behavior. The exception still persists...
```
          ID: stackdriver-agent-is-installed
    Function: cmd.run
        Name: sudo curl -O "https://repo.stackdriver.com/stack-install.sh" && bash stack-install.sh --write-gcm
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/cmd.py", line 821, in run
                  cret = mod_run_check(cmd_kwargs, onlyif, unless, creates)
                File "/usr/lib/python2.7/dist-packages/salt/states/cmd.py", line 347, in mod_run_check
                  cmd = __salt__['cmd.retcode'](unless, ignore_retcode=True, python_shell=True, **cmd_kwargs)
              TypeError: retcode() got multiple values for keyword argument 'python_shell'
     Started: 15:25:18.978965
    Duration: 44.231 ms
     Changes:   
```

And without ```python_shell: True```, the pipe in ```unless: ls -la /etc/default | grep "stackdriver-agent"``` is not honored.

I came up with an alternative to get around this issue. The following bash script called ```bool.sh```:
```
#!/bin/bash
echo $@ >> /tmp/bool.out
eval $@ &> /dev/null
echo $? >> /tmp/bool.out
exit $?
```
can be used as follows:
```
    - unless: sudo bool.sh 'ls -la /etc/default | grep "stackdriver-agent"'
```

Not as elegant as being able to rely on a native salt function but seems to work as a temporary work-around.

**Comment by rajivkukreja** [comment]
@cro / @SaltStackSupport - were you able to reproduce this?

I've effectively moved away from cmd.run entirely and using cmd.script instead. Pipes in unless and onlyif conditions for cmd.script are being honored (even without the python_shell) but as a defensive move, I am adding the same checks in the scripts themselves.

Its far from ideal to need a bash script for running single commands. I'd prefer to move back to cmd.run - so, quite interested in any your findings / updates.

Thanks very much

**Comment by alexkolomolo** [comment]
Any fix?

**Comment by BrianSidebotham** [comment]
This is still true in `3001.1`. When installing an MSI, I used this powershell command to test if it had already been installed. The command definitely works as I tested it in another cmd.run state. However, in unless this doesn't work.

```
- unless:
  - fun: cmd.run
    args:
      - '$install = Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -eq "{{ msi_name }}"}; if( $install -eq $null ) { Exit 1 } else { Exit 0 }'
    shell: powershell
```

I tried it with `python_shell: true` as well, but still doesn't work.

I put the same into a script and used `cmd.script` in the unless requisite and everything works as expected.

**Comment by triplepoint** [comment]
Ran across this ourselves, can confirm in salt 3002.2, an onlyif with pipes in it is ignored.
```
cmd.run:
    - name: "dropdb some_db"
    - onlyif: psql -lqt | cut -d \| -f 1 | grep -qw some_db
```

**Comment by alexkolomolo** [comment]
Maybe it can be escaped in someway?

*Alex Wheeler*
CEO Kolomolo AB
ORG #:  5592055619

Mobile: +46 721 698 242
www.kolomolo.com




On Fri, Dec 4, 2020, at 8:35 PM, Jonathan Hanson wrote:
> 

> Ran across this ourselves, can confirm in salt 3002.2, an onlyif with pipes in it is ignored.

> `cmd.run:
    - name: "dropdb some_db"
    - onlyif: psql -lqt | cut -d \| -f 1 | grep -qw some_db
`

**Comment by rolszewo** [comment]
somehow i have the same problem.

```bash
# searching root
test_onlyif_exit_0:
  cmd.run:
    - name: |
        echo "missing user root" && exit 1
    - onlyif:
      - fun: cmd.run
        cmd: if test $(cat /etc/passwd | grep root); then exit 0; else exit 1;fi
        python_shell: true
        shell: /bin/bash

# searching toor
test_onlyif_exit_1:
  cmd.run:
    - name: |
        echo "missing user toor" && exit 1
    - onlyif:
      - fun: cmd.run
        cmd: if test $(cat /etc/passwd | grep toor); then exit 0; else exit 1;fi
        python_shell: true
        shell: /bin/bash
```

results in

```bash
salt-call state.sls_id test_onlyif_exit_0 test -l info
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'test.sls'
[INFO    ] Running state [echo "missing user root" && exit 1] at time 11:51:47.875537
[INFO    ] Executing state cmd.run for [echo "missing user root" && exit 1]
[INFO    ] Executing command git in directory '/root'
[INFO    ] Executing command 'if' in directory '/root'
[INFO    ] ['onlyif condition is false']
[INFO    ] Completed state [echo "missing user root" && exit 1] at time 11:51:49.037899 (duration_in_ms=1162.36)
local:
----------
          ID: test_onlyif_exit_0
    Function: cmd.run
        Name: echo "missing user root" && exit 1

      Result: True
     Comment: onlyif condition is false
     Started: 11:51:47.875539
    Duration: 1162.36 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   1.162 s


salt-call state.sls_id test_onlyif_exit_1 test -l info

[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [echo "missing user toor" && exit 1] at time 11:51:55.507806
[INFO    ] Executing state cmd.run for [echo "missing user toor" && exit 1]
[INFO    ] Executing command git in directory '/root'
[INFO    ] Executing command 'if' in directory '/root'
[ERROR   ] Command 'if' failed with return code: 1
[ERROR   ] retcode: 1
[ERROR   ] Command 'if' failed with return code: 1
[ERROR   ] output: 
[INFO    ] ['onlyif condition is false']
[INFO    ] Completed state [echo "missing user toor" && exit 1] at time 11:51:56.639537 (duration_in_ms=1131.73)
local:
----------
          ID: test_onlyif_exit_1
    Function: cmd.run
        Name: echo "missing user toor" && exit 1

      Result: True
     Comment: onlyif condition is false
     Started: 11:51:55.507807
    Duration: 1131.73 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   1.132 s
```
Only the second state has an ERROR

```bash
[ERROR   ] Command 'if' failed with return code: 1
[ERROR   ] retcode: 1
```

But BOTH `onlyif` are resulting in `Comment: onlyif condition is false`!

```bash
Salt Version:
          Salt: 3003.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-80-generic
        system: Linux
       version: Ubuntu 20.04 focal
```

And with `- fun: cmd.retcode` instead of `- fun: cmd.run` inside onlyif it is not working at all.

**Comment by rsutton1** [comment]
The issue appears to be more than just pipes. Even when replacing the pipe with `&&` it is still ignored.

```
    - onlyif:
      - /opt/neovim/bin/nvim --version > /tmp/nv && grep 0.7.0 /tmp/nv
      # onlyif w/ pipes broken from https://github.com/saltstack/salt/issues/36734
      # # - /opt/neovim/bin/nvim --version | grep 0.7.0
```

Run with debug, no onlyif being logged:

```
rpsuttondev@penguin:~/salt$ sudo salt-call state.sls packages test=true -l debug |& grep onlyif
    - onlyif:
      # onlyif w/ pipes broken from https://github.com/saltstack/salt/issues/36734
OrderedDict([('neovim_deps', OrderedDict([('pkg.installed', [OrderedDict([('pkgs', ['ninja-build', 'gettext', 'libtool', 'libtool-bin', 'autoconf', 'automake', 'cmake', 'g++', 'pkg-config', 'unzip', 'curl', 'doxygen'])]), OrderedDict([('prereq', [OrderedDict([('archive', 'neovim_downloaded')])])])])])), ('neovim_downloaded', OrderedDict([('archive.extracted', [OrderedDict([('name', '/tmp/')]), OrderedDict([('trim_output', 0)]), OrderedDict([('source', 'https://github.com/neovim/neovim/archive/refs/tags/v0.7.0.tar.gz')]), OrderedDict([('skip_verify', True)]), OrderedDict([('prereq', [OrderedDict([('cmd', 'neovim_installed')])])])])])), ('neovim_installed', OrderedDict([('cmd.run', [OrderedDict([('name', 'make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/opt/neovim"\nmake install\n')]), OrderedDict([('cwd', '/tmp/neovim-0.7.0')]), OrderedDict([('hide_output', True)]), OrderedDict([('onlyif', ['/opt/neovim/bin/nvim --version > /tmp/nv && grep 0.7.0 /tmp/nv'])])])])), ('deps', OrderedDict([('pkg.installed', [OrderedDict([('pkgs', ['tmux', 'silversearcher-ag'])])])]))])
rpsuttondev@penguin:~/salt$ 
```

Just FYI this command works fine in the terminal.
```
rpsuttondev@penguin:~/salt$ ls /tmp/nv
ls: cannot access '/tmp/nv': No such file or directory
rpsuttondev@penguin:~/salt$ /opt/neovim/bin/nvim --version > /tmp/nv && grep -q 0.7.0 /tmp/nv
rpsuttondev@penguin:~/salt$ echo $?
0
```



```
rpsuttondev@penguin:~/salt$ salt-call --versions
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 21.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 5.4.119-14940-g3f09d7690fd7
        system: Linux
       version: Debian GNU/Linux 10 buster
```

**Comment by Darkentik** [comment]
Why was this cloesed here?
What is the solution?
I have the same problem encountered with salt 3006.6 when coding a git+gitolite3 state for initializing a salt-master from scratch fully automated.
Code:
```
Commit and push changes on gitolite.conf or user ssh key files:
  cmd.run:
    - name: git commit -am "updated gitolite.conf" && git push
    - cwd: /srv/gitolite/GIT/gitolite-admin
    - runas: git
    - require:
      - file: Manage gitolite.conf file with data from pillar
    - watch:
      - file: Manage gitolite.conf file with data from pillar
    #- onlyif:
    #  - test $(cd /srv/gitolite/GIT/gitolite-admin/ && git status | grep -E "(Zum Commit vorgemerkte Änderungen|Änderungen, die nicht zum Commit vorgemerkt sind)" | wc -l) -gt 0
    - unless:
      - test $(cd /srv/gitolite/GIT/gitolite-admin/ && git status | grep -E "(Zum Commit vorgemerkte Änderungen|Änderungen, die nicht zum Commit vorgemerkt sind)" | wc -l) -le 0
```

Both onlyif and unless are not working 100%.

The check with the git user says that there are definitely are changes which must be committed:

```
git@salt01-a:~/GIT/gitolite-admin$ git status
Auf Branch master
Ihr Branch ist auf demselben Stand wie 'origin/master'.

Zum Commit vorgemerkte Änderungen:
  (benutzen Sie "git restore --staged <Datei>..." zum Entfernen aus der Staging-Area)
        neue Datei:     keydir/laptop_relaxdays/david_fritsch.pub
        neue Datei:     keydir/pve01-a/david_fritsch.pub
        neue Datei:     keydir/root@salt01-a.mgmt.teu01.de.frzn.internal/root@salt01-a.mgmt.teu01.de.frzn.internal.pub

Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git restore <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)
        geändert:       conf/gitolite.conf

git@salt01-a:~/GIT/gitolite-admin$ [ $(git status | grep -E "(Zum Commit vorgemerkte Änderungen|Änderungen, die nicht zum Commit vorgemerkt sind)" | wc -l) -le 0 ] && echo "true" || echo "false"
false

git@salt01-a:~/GIT/gitolite-admin$ git status | grep -E "(Zum Commit vorgemerkte Änderungen|Änderungen, die nicht zum Commit vorgemerkt sind)" | wc -l
2

```

Any ideas?

**Comment by Darkentik** [comment]
For me i have add a workaround to avoid pipe in the unless/onlyif with using a tmp file.
Maybe it helps someone.

My States:

```
write gitolite-admin repo status to tmp file:
  cmd.run:
    - name: git status > /tmp/gitolite_admin_repo_status.log
    - cwd: /srv/gitolite/GIT/gitolite-admin
    - runas: git
    - require:
      - file: Manage gitolite.conf file with data from pillar
    - watch:
      - file: Manage gitolite.conf file with data from pillar

Commit and push changes on gitolite.conf or user ssh key files:
  cmd.run:
    - name: git commit -am "updated gitolite.conf" && git push
    - cwd: /srv/gitolite/GIT/gitolite-admin
    - runas: git
    - require:
      - file: Manage gitolite.conf file with data from pillar
    - watch:
      - file: Manage gitolite.conf file with data from pillar
      - cmd: write gitolite-admin repo status to tmp file
    #- onlyif:
    #  - test $(cd /srv/gitolite/GIT/gitolite-admin/ && git status | grep -E "(Zum Commit vorgemerkte Änderungen|Änderungen, die nicht zum Commit vorgemerkt sind)" | wc -l) -gt 0
    - unless:
      #- test $(cd /srv/gitolite/GIT/gitolite-admin/ && git status | grep -E "(Zum Commit vorgemerkte Änderungen|Änderungen, die nicht zum Commit vorgemerkt sind)" | wc -l) -le 0
      - test "$(grep -E "(Zum Commit vorgemerkte Änderungen|Änderungen, die nicht zum Commit vorgemerkt sind)" /tmp/gitolite_admin_status.log)" == ""

delete gitolite-admin repo status tmp file after doing git push:
  file.absent:
    - name: /tmp/gitolite_admin_repo_status.log
    - runas: git
```
