### ISSUE TITLE
salt.auth.pam does not work on SmartOS

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#36737]
### Description of Issue/Question
salt.auth.pam fails on SmartOS,
pam_authenticate call always returns 3 (If I get got it right, service errror?)

### Setup
Fragment from master configuration:
```
####
## SaltStack Master Configuration
####
##########################################
## external_auth
external_auth:
  pam:
    sysadmin%:
      - .*

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
```

I added some more logging to salt/auth/pam.py#L177,
The return value is always 3, running a simple master setup on linux with simular config returns 0 and everything works.

### Steps to Reproduce Issue
```bash
salt -a pam '*' test.ping
```
```
username: xxx
password: xxx
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

### Versions Report
```yaml
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.4.2
       cherrypy: 3.8.0
       dateutil: 2.4.0
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.6.1
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul 20 2016, 14:22:30)
   python-gnupg: 0.3.9
         PyYAML: 3.11
          PyZMQ: 14.4.1
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.3

System Versions:
           dist:
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```

**Comment by sjorge** [comment]
Switched to debug logging and PAM spews out:
```
2016-10-02T15:59:46+02:00 cronos salt-master[77810]: [ID 427199 user.error] pam_dial_auth: terminal-device not specifiedby login, returning Error in underlying service module.
```

**Comment by sjorge** [comment]
Solution is to switch to ```other``` service, it is the same as ```login``` minus the dialup bits.

```yaml
####
## SaltStack Master Configuration
####
##########################################
## external_auth
auth.pam.service: other
external_auth:
  pam:
    sysadmin%:
      - .*

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
```
```bash
[root@cronos ~]# salt -a pam cronos test.ping
username: user
password: secret
cronos:
    True
```

@rallytime seems more like a documentation issue instead of a coding issue.
I take it a PR against the docs to add a note about solaris with the above workaround/configure should be acceptable?
