### ISSUE TITLE
Jinja templating in salt-cloud profiles

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#36769]
Wanted to know why jinja templating can only be used in cloud map files and hasn't been implemented yet in cloud profile files? Is there a reason this hasn't been implemented yet or just that there wasn't any use case? @techhat @thatch45 

It has been brought up before: https://github.com/saltstack/salt/issues/8403#issuecomment-31940600

**Comment by gtmanfred** [comment]
Are there any other configuration files in /etc/salt that are templated?

You can use yaml anchors in order to template a little bit that way.

Otherwise, I think this would be a better solution https://github.com/saltstack/salt/issues/36772

Here is my example of using yaml anchors to only have defaults set.

```
[root@salt ~]# cat /etc/salt/cloud.providers.d/mynova.conf
dfw: &configs
  identity_url: https://identity.api.rackspacecloud.com/v2.0/
  user: <tenantname>
  cloud: rack
  tenant: <tenant_id>
  driver: nova
  #ssh_interface: public_ips
  ssh_key_name: gtmanfred
  ssh_key_file: /root/.ssh/saltstack
  api_key: <key>
  os_auth_plugin: rackspace
  compute_region: DFW
  networks:
    - net-id: 00000000-0000-0000-0000-000000000000
    - net-id: 11111111-1111-1111-1111-111111111111

iad:
  <<: *configs
  compute_region: IAD
  networks:
    - net-id: 00000000-0000-0000-0000-000000000000
    - net-id: 11111111-1111-1111-1111-111111111111

ord:
  <<: *configs
  compute_region: ORD
  networks:
    - net-id: 00000000-0000-0000-0000-000000000000
    - net-id: 11111111-1111-1111-1111-111111111111

syd:
  <<: *configs
  compute_region: SYD
  networks:
    - net-id: 00000000-0000-0000-0000-000000000000
    - net-id: 11111111-1111-1111-1111-111111111111

hkg:
  <<: *configs
  compute_region: HKG
  networks:
    - net-id: 00000000-0000-0000-0000-000000000000
    - net-id: 11111111-1111-1111-1111-111111111111
```
