### ISSUE TITLE
sysctl.present - adding a comment field would be very useful

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#36761]
A few lines from a the standard `/etc/sysctl.conf` file:

```
# Controls IP packet forwarding
net.ipv4.ip_forward = 0

# Controls source route verification
net.ipv4.conf.default.rp_filter = 1

# Do not accept source routing
net.ipv4.conf.default.accept_source_route = 0
```

So the convention is a property name, value and a comment on the line above. The `sysctl.present` state (https://docs.saltstack.com/en/latest/ref/states/all/salt.states.sysctl.html) is great but it would even better if it provided a comment field to allow maintaining the same format as the standard values. This is relevant when you are adding a value to sysctl that is not already in the file, or where you want to change the comment i.e.

```
net.ipv6.conf.all.disable_ipv6:
  sysctl.present:
    - value: 1
```

So ideally I would like to see:

```
net.ipv6.conf.all.disable_ipv6:
  sysctl.present:
    - value: 1
    - comment: Controls IPV6 on/off state
```
