### ISSUE TITLE
Copy remote directory with file module

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#36762]
I'm trying to recursively copy a directory on the minion to another directory on the same minion, but it's not clear from the documentation for the file module (https://docs.saltstack.com/en/develop/ref/states/all/salt.states.file.html#salt.states.file.copy) whether this is possible.

The command I want to execute on the minion is:

```
cp -r /tmp/jre1.8.0_102 /usr/share/java/java-1.8.0-102
```

but unfortunately this state fails:

```
java_install:
  file.copy:
    - name: /usr/share/java/java-1.{{ java.version }}.0-{{ java['update'] }}
    - source: /tmp/jre1.{{ java.version }}.0_{{ java['update'] }}
    - recurse: True
```

with:

```
      ID: java_install
Function: file.copy
    Name: /usr/share/java/java-1.8.0-102
  Result: False
 Comment: Failed to copy "/tmp/jre1.8.0_102" to "/usr/share/java/java-1.8.0-102"
 Started: 10:30:36.660158
Duration: 1.656 ms
 Changes:
```

Can this be done with the file module or do I need to use `cmd.run`?
