### ISSUE TITLE
pillar.has_key no longer available in 2016.3.3?

### ISSUE THREAD

**Issue by DaveQB** [saltstack/salt#36763]
### We use pillar.has_key as a logical statement to select which content goes into which file.

Using salt 2015.8.8 and previous we had no issues. Now on 2016.3.3 this is not working.
### Setup

We have this block in our base/soe/init.sls

```
rc.local:
  file.managed:
    - name: /etc/rc.local
    {% if 'ops-master' == grains['localhost']  %}
    - source: salt://master/rc.local
    {% else %}
    - source: salt://soe/etc/rc.local
    {% endif %}
    - mode: 755
    - user: root
    - template: jinja
```

Then in:

```
base/soe/etc/rc.local
```

We have some logic based around a pillar being set:

```
{% if pillar.has_key('cas-bb') %}
nohup /usr/bin/nodejs &
{% endif %}
```

We have 2 servers, one on 2015.8.8 and one on 2016.3.3

```
prd-cas-bb-delete02:
    2015.8.8.2
prd-cas-bb-delete0901:
    2016.3.3
```

Both have the pillar set:

```
prd-cas-bb-delete02:
    ----------
    cas-bb:
        True
prd-cas-bb-delete0901:
    ----------
    cas-bb:
        True
```

Yet only the 2015.8.8 minion applies the line of text to the target file:

```
prd-cas-bb-delete0901:
prd-cas-bb-delete02:
    nohup /usr/bin/nodejs &
```

So the issue is, even though we have the pillar set, pillar.has_key is not working as expected in 2016.3.3. Should I be doing this logic a different way in 2016.3.3?

Thanks.
### Steps to Reproduce Issue

Running a state.apply with the setup above will reproduce this.
### Versions Report

```
prd-cas-bb-delete02:
    2015.8.8.2
prd-cas-bb-delete0901:
    2016.3.3
```

MASTER

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-63-virtual
         system: Linux
        version: Ubuntu 12.04 precise
```

**Comment by gtmanfred** [comment]
That shouldn't be a salt specific thing.  The `pillar` object in the state files is a dictionary used in ninja, so it shouldn't be changed by a salt specific thing.  It could be a difference in the jinja version.

**Comment by DaveQB** [comment]
@gtmanfred 

Good thinking.


```
prd-cas-bb-delete0901:
    Salt Version:
               Salt: 2016.3.3
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.1
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: Ubuntu 12.04 precise
            machine: x86_64
            release: 3.2.0-84-virtual
             system: Linux
            version: Ubuntu 12.04 precise
```

```
prd-cas-bb-delete02:
    Salt Version:
               Salt: 2015.8.8.2
     
    Dependency Versions:
             Jinja2: 2.6
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.1
             Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 12.04 precise
            machine: x86_64
            release: 3.2.0-84-virtual
             system: Ubuntu 12.04 precise
```
