### ISSUE TITLE
gpg.receive_keys with usernames >8 chars and nonlocal usernames

### ISSUE THREAD

**Issue by stickmanxa** [saltstack/salt#36771]
I'm having issues with the GPG module in 2016.3.3. I'm trying to use gpg.receive_keys to pull keys from a SKS key server. Two classes of accounts are not able to pull keys - usernames >8 characters and non-local AD accounts. There are no entries in /etc/passwd for the AD accounts.

These fail:
salt 'hostname_' gpg.receive_keys keyserver=keyhost keys='AAAAAAAA' user='local1234'
salt 'hostname_' gpg.receive_keys keyserver=keyhost keys='AAAAAAAA' user='aduser'

These work:
salt 'hostname_' gpg.receive_keys keyserver=keyhost keys='AAAAAAAA' user='root'
salt 'hostname_' gpg.receive_keys keyserver=keyhost keys='AAAAAAAA' user='local123'

I'm also having similar issues with the gpg state. It works with root but not local1234.  In addition, the state even claims success for retrieving the key with a completely bogus key server hostname.

```
AAAAAAAA:
  gpg.present:
    - keyserver: keyhost.example.com
    - keys: AAAAAAAA
    - user: root
    - trust: ultimately
```

Am I missing something?
