### ISSUE TITLE
Cloud 'created' event does not contain minion ID

### ISSUE THREAD

**Issue by jerrykan** [saltstack/salt#36779]
### Description of Issue/Question

With the vmware driver (it may affect other drivers as well) the `created` event only includes the name of the VM not the ID of the minion, so I am unable to trigger a `state.highstate` once a new minion has been created.

There may be valid reasons for the VM name to be different from the minion ID, so the `created` event should contain the ID of newly deployed/created minion.
#### cloud.profile.d/vmware.conf

```
debian8:
  provider: esxhost
  ...
  minion:
    append_domain: example.com
```
#### salt/maps/saltminion.conf

```
debian8:
  - saltminion:
      num_cpus: 2
      memory: 2GB
```
#### reactor/cloud_created.sls

```
reactor_highstate:
    cmd.state.highstate:
        - tgt: {{ data['name'] }}
```

Using the above config example the name of the VM will be `saltminion` but the ID will be `saltminion.example.com`. The resulting `created` event would look something like:

```
    salt/cloud/saltminion/created       {
    "_stamp": "2016-10-05T00:52:38.755151", 
    "event": "created instance", 
    "name": "saltminion", 
    "profile": "debian8", 
    "provider": "esxhost:vmware"
    }
```

The reactor won't fire because the name does not match any minion IDs.

This would also be a problem with the following setup
#### cloud.profile.d/vmware.conf

```
debian8:
  provider: esxhost
  ...
```
#### salt/maps/saltminion.conf

```
debian8:
  - saltminion.example.com:
      name: saltminion

      num_cpus: 2
      memory: 2GB
```
