### ISSUE TITLE
salt.states.file.line (and salt.modules.file.line) problem

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [saltstack/salt#36818]
Seems `mode=ensure` ignores `location` parameter. Trying to make sure that specified line exists, otherwise want to add it at the end of file:

``` yaml
screen-conf:
  file.line:
    - name: /etc/screenrc
    - content: 'caption always " %w --- HOST: %H"'
    - mode: ensure
    - location: end
```

returns error:
**CommandExecutionError: Wrong conditions? Unable to ensure line without knowing where to put it before and/or after.**

Documentation says nothing about mandatory parameters for `mode=ensure`.

Also inspecting code of /usr/lib/python2.7/site-packages/salt/modules/file.py I have found suspicious moment:

``` python
    if before is None and after is None and not match:
        match = content
```

I am not sure how value of `content` will be treated in `match` variable, but in my opinion it must be used as a plain text for whole string match, not regexp and not substring match. Can you clarify this ?
