### ISSUE TITLE
--no-compress does not exist on (most?) Mac installs, makes macpackage.install fail

### ISSUE THREAD

**Issue by c4urself** [saltstack/salt#36829]
### Description of Issue/Question

On my Mac the rsync utility does not include the `--no-compress` flag and that makes the macpackage.install function fail here: https://github.com/saltstack/salt/blob/develop/salt/modules/mac_package.py#L113
### Setup

```
$ rsync --version
rsync  version 2.6.9  protocol version 29
$ salt-call grains.get osfullname
local:
    Mac OS X 10.10.5
```
### Steps to Reproduce Issue

```
$ salt-call macpackage.install Docker.dmg
```
### Versions Report

NOTE: This module is not available yet on my Salt version, but I've been testing it out as an added module.

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jun 29 2016, 14:04:44)
   python-gnupg: 0.3.9
         PyYAML: 3.11
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: x86_64
        release: 14.5.0
         system: Darwin
        version: 10.10.5 x86_64
```
