### ISSUE TITLE
dockerng.image_present fails to pull image from docker.io/ when it can't login into locally defined registry

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#36872]
When a registry is defined in pillar:

```
docker-registries:
  https://xxx.xxx.com/v2/:
  ...
  ...
```

and for some reason it's unaccessible, and you try to pull image from docker.io:

```
some_image:
  dockerng.image_present:
    - name: docker.io/image:tag
```

you get error, 'cause salt tries to login to the 'bad' registry:

```
----------
          ID: some_image
    Function: dockerng.image_present
        Name: docker.io/image:tag
      Result: False
     Comment: Encountered error pulling docker.io/image:tag: 500 Server Error: Internal Server Error ("{"message":"login attempt to https://xxx.xxx.com/v2/ failed with status: 502 Bad Gateway"}")
     Started: 13:27:25.961308
    Duration: 1416.496 ms
     Changes:   
----------
```

**Comment by gtmanfred** [comment]
Unfortunately I am unable to replicate this.

I have set it up like the following

```
docker-registries:
  https://xxx.xxx/v1/:
    email: foo@foo.com
    password: s3cr3t
    username: foo
  https://hub.docker.com:
    email: <email>
    password: <password>
    username: <username>
```

with the following state

```
[root@docker ~]# cat /srv/salt/test.sls
some_image:
  dockerng.image_present:
    - name: postgres:latest
```

And I successfully am able to get the image from docker hub.

```
[root@docker ~]# salt-call state.apply test
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

local:
----------
          ID: some_image
    Function: dockerng.image_present
        Name: postgres:latest
      Result: True
     Comment: Image 'postgres:latest' was pulled
     Started: 14:51:23.118606
    Duration: 17947.574 ms
     Changes:
              ----------
              Layers:
                  ----------
                  Pulled:
                      - 193f770cec44
                      - 33647077f2ee
                      - 6a5a5368e0c2
                      - 53bc65f84840
                      - a4d3b0f1c16a
                      - bdbe3c2ddbbd
                      - 8f08971388d1
                      - 7e724cee4193
                      - f80ab5df227d
                      - fb0a1ee64973
                      - 484ac0d6f901
              Status:
                  Downloaded newer image for postgres:latest
              Time_Elapsed:
                  17.9367620945

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  17.948 s
```

Can you provide me more steps to replicate what you are getting?

**Comment by zerthimon** [comment]
@gtmanfred Try this:
Make user you have a local registry defined in pillar.
Verify that it's not accessible.
Remove ~/.docker
Don't login to any registry.
Run a state that pulls image from docker.io

**Comment by gtmanfred** [comment]
From reading the documentation about dockerng, to push or pull any images, authentication is required.  So not logging into any registry won't succeed in pulling images.

**Comment by zerthimon** [comment]
So, how do I go about pulling from public docker library ?

**Comment by gtmanfred** [comment]
You need to make a hub.docker.com account, and plug it into the docker_registries config

**Comment by zerthimon** [comment]
Well, that's a weird requirement, for someone that all he needs is just to pull images from a public library.

**Comment by gtmanfred** [comment]
@terminalmage can you comment on this?

**Comment by terminalmage** [comment]
@gtmanfred In the ``pull`` func we are setting a kwarg to call the ``_image_wrapper()`` function with auth enabled, which is why this is being required to pull images. We could alter the ``_image_wrapper()`` to only attempt a login when the necessary auth params are configured for a given registry. To be honest though, I'm not a regular Docker user and don't know how using a mixture of authenticated and unauthenticated registries would work, nor a multitude of docker registries period, for that matter. For instance, does the ``Client`` only consider the most recent login if multiple logins are executed (as we do when more than one registry entry is present in the configuration)?

@ticosax has contributed a considerable amount of code to this state/module, is well acquainted with docker-py, and I would like to get his input if possible on this.

**Comment by ticosax** [comment]
This behavior (of attempting to authenticate against all registries docker-py asked to) is in the hand of docker daemon itself, `docker-py` is just transmitting credentials. `dockerd` is the one performing authentication. I'm afraid there is not much we can do at salt level. You will have to address this issue to docker itself.

**Comment by terminalmage** [comment]
@ticosax Interesting... so if we were to leave out auth info for a public registry, docker-py would fail to pull?

**Comment by zerthimon** [comment]
What happens if no registries defined in pillar and no ~/.docker exists, I won't be able to pull from docker.io with salt ?

**Comment by ticosax** [comment]
> so if we were to leave out auth info for a public registry, docker-py would fail to pull?

public registries doesn't require authentication to pull.

> What happens if no registries defined in pillar and no ~/.docker exists, I won't be able to pull from docker.io with salt ?

I believe you should be able to pull from any public registries. I just tried and it worked.

**Comment by terminalmage** [comment]
@ticosax So if we were to just remove the auth requirement from the ``pull`` function, and then don't process a ``Client.login()`` when auth is not present in the configuration for a public registry, it'll download from a public registry without issue? I guess I'm wondering what the implications are if you have two registries and you login to one, you don't login to another, and then you pull. What I would expect is that docker would try to pull from each registry in turn until one succeeded, returning an error if nothing matching the desired image could be pulled.

**Comment by terminalmage** [comment]
The idea would be to have something like this in pillar:

```
docker-registries:
  https://index.foo.io/v1/:
    email: foo@foo.com
    password: s3cr3t
    username: foo
  https://index.bar.io/v1/:
    public: True
```
