### ISSUE TITLE
Reserved keywords need to be listed in docs.

### ISSUE THREAD

**Issue by ryanwalder** [saltstack/salt#36903]
### Description of Issue/Question

Reserved keywords are not listed anywhere (that I can find!) which can lead to extremely unhelpful failure messages leading down a rabbit hole of debugging.
### Steps to Reproduce Issue

Use a reserved keyword in a state and bask in the meaningless errors

```
{%- set opts = ['one', 'two', 'three'] %}                                       

foo:                                                                            
  file.managed:                                                                 
    - name: /tmp/foo                                                            
    - context:                                                                  
        opts: {{ opts }} 
```

Which will return:

```
ID: foo
    Function: file.managed
        Name: /tmp/foo
      Result: False
     Comment: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 317, in render_jinja_tmpl
                  loader = salt.utils.jinja.SaltCacheLoader(opts, saltenv, pillar_rend=context.get('_pillar_rend', False))
                File "/usr/lib/python2.7/dist-packages/salt/utils/jinja.py", line 71, in __init__
                  if self.opts['file_roots'] is self.opts['pillar_roots']:
              KeyError: 'file_roots'
     Started: 15:51:26.521940
    Duration: 46.251 ms
     Changes: 
```

Edit: Referenced in #5456
