### ISSUE TITLE
missing /dev/mem results in incorrect grains

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#36907]
### Description of Issue/Question
```yaml
    productname:
        /dev/mem: No such file or directory
    biosreleasedate:
        /dev/mem: No such file or directory
    biosversion:
        /dev/mem: No such file or directory
    manufacturer:
        /dev/mem: No such file or directory
```

Probably better to have the grain emtpy... or not exist when /dev/mem is not present.

### Setup
Ubuntu under SmartOS as a LX zone
