### ISSUE TITLE
Managing ext_pillar password in /etc/salt/master

### ISSUE THREAD

**Issue by hoitsang** [saltstack/salt#36953]
### Description of Issue/Question

Howdy, what would be the best way to encrypt data (namely password) in /etc/salt/master with ext_pillar configuration? 
### Setup

```
ext_pillar:
  — redis_pillar:
      port: 6379
      host: localhost
      password: superSecretTacos
```

Instead of saving it as plain text password, can that be stored as gpg encrypted, and have salt to decrypt just like encrypted data from the pillar?
