### ISSUE TITLE
[doc] dockerng option cpu_shares should be an integer

### ISSUE THREAD

**Issue by Arabus** [saltstack/salt#36951]
The examples in the saltstack [state](https://docs.saltstack.com/en/2015.8/ref/states/all/salt.states.dockerng.html#salt.states.dockerng.running) and [module](https://docs.saltstack.com/en/2015.8/ref/modules/all/salt.modules.dockerng.html#salt.modules.dockerng.create) documentation for dockerng suggest that the option `cpu_shares` can be set to a float value whereas the [official docker documentation](https://docs.docker.com/engine/reference/run/) states, that this must be an integer > 2.

##### Example statefile that produces an error
```
foobar:
  dockerng.running:
    image: ubuntu:latest
    cpu_shares: 0.5
```
##### Example statefile that works
```
foobar:
  dockerng.running:
    image: ubuntu:latest
    cpu_shares: 2
```
