### ISSUE TITLE
No option to provide proxy parameters for dockerng.image_present

### ISSUE THREAD

**Issue by dmelnicz** [saltstack/salt#36969]
### Description of Issue/Question

There is no option to provide proxy parameters for dockerng.image_present. 
### Setup

```
elasticsearch-image:
  dockerng.image_present:
    - name: elasticsearch:5

elasticsearch-service:
  docker.running:
    - image: elasticsearch

```
### Steps to Reproduce Issue

```
----------
          ID: elasticsearch-image
    Function: dockerng.image_present
        Name: elasticsearch:5
      Result: False
     Comment: Encountered error pulling elasticsearch:5: Pull failed for elasticsearch:5. Error(s) follow:

              Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/elasticsearch/images. You may want to check your internet connection or if you are behind a proxy.
     Started: 14:52:48.554614
    Duration: 45019.128 ms
     Changes:
----------
          ID: elasticsearch-service
    Function: docker.running
      Result: False
     Comment: image "elasticsearch:latest" does not exists
     Started: 14:53:33.574781
    Duration: 4.967 ms
     Changes:

```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-21-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```
### Additional comment

There seems to be workaround by providing custom configuration file for docker: http://stackoverflow.com/a/28093517/993324
