### ISSUE TITLE
URGENT : archive.extracted does not work anymore

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#37001]
### Description of Issue/Question

first it says the checksum cannot verified, does not correspond
(it was working before for many machines and I did not change my script)

I tried source_hash_update=True, but it gives me an error

skip_verify: true gives an error saying it's an invalid option but this would really be usefull

I am supposed to add a machine to my prod today and now I am stuck, so it's quiet an urgent issue
worst case I could install the whole thing manualy, but then what's the point of relying on SALT ???

is there no way to install salt from the bootstrap script without regression ?

thanks
### Setup

```
syncthing_download:
  archive.extracted:
    - name: /home/*******/
    - source: https://github.com/syncthing/syncthing/releases/download/v0.13.4/syncthing-linux-amd64-v0.13.4.tar.gz
    - source_hash: https://github.com/syncthing/syncthing/releases/download/v0.13.5/sha256sum.txt.asc
    - source_hash_update: true
    - skip_verify: true
    - tar_options: v
    - user: ******
    - group: ******
    - archive_format: tar
    - if_missing: /home/******/syncthing-linux-amd64-v0.13.4/
```

An exception occurred in this state:

```
Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/archive.py", line 279, in extracted
                  if compareChecksum(hash_fname, name, hash[1]):
              IndexError: list index out of range
     Started: 11:25:54.606397
    Duration: 0.756 ms
     Changes:   
    Warnings: 'skip_verify' is an invalid keyword argument for
              'archive.extracted'. If you were trying to pass additional data to
              be used in a template context, please populate 'context' with
              'key: value' pairs. Your approach will work until Salt Carbon is
              out. Please update your state files.
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

```
sudo salt-minion --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6 


Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
```

**Comment by gtmanfred** [comment]
Hello, I have confirmed this bug on centos 7.2 and salt 2013.3.3

**Comment by gtmanfred** [comment]
So, I am not actually sure that this is a bug, because the source_hash has to be in the format

`<type>=<hash`

and the asc file that you are including does not match that?

If you use the following state, it works

```
syncthing_download:
  archive.extracted:
    - name: /home/daniel/
    - source: https://github.com/syncthing/syncthing/releases/download/v0.13.4/syncthing-linux-amd64-v0.13.4.tar.gz
    - source_hash: sha512=8d1e47378dd2f510d8af877df52753ab8553a2ab389d37086426c902e4aa9371a9c2a9085ca41f0dafdd8b0b2a07e5710db53ad3fb76b699fede5fd0b470237b
    - source_hash_update: true
    - skip_verify: true
    - tar_options: v
    - user: daniel
    - group: daniel
    - archive_format: tar
    - if_missing: /home/daniel/syncthing-linux-amd64-v0.13.4/
```

Specifically with the following source_hash set
`    - source_hash: sha512=8d1e47378dd2f510d8af877df52753ab8553a2ab389d37086426c902e4aa9371a9c2a9085ca41f0dafdd8b0b2a07e5710db53ad3fb76b699fede5fd0b470237b`
