### ISSUE TITLE
[Dockerng] Warning : Host path in bind is not absolute, assuming it is a docker volume

### ISSUE THREAD

**Issue by Plup-io** [saltstack/salt#37029]
### Description of Issue/Question

I don't know if I am doing things well in my configuration. (see config state below)
Everything works fine but I see this warning in minion logs : 

> Warning Host path in bind is not absolute, assuming it is a docker volume

And I have to say that it's a good guess from salt. I'm actually using a named volume in a bind directive. I looked deep in the documentation but there is nothing written about docker named volumes. So, I tried this and it works. But, as I'm seeing warning, I prefer asking if there is a cleaner way to do that : 
### Config in a state.sls

```
create {{app_name}} specific volumes:
  dockerng.volume_present:
    - name: {{app_name}}-vl
    - driver: local

start web container {{app_name}}-web:
  dockerng.running:
    - name: {{app_name}}-web
    - image: meteo/nginx:v1
    - network_mode: {{ pillar['proxy']['network'] }}
    - binds:
      - {{app_name}}-vl:/data/web/:rw
```
### Steps to Reproduce Issue

```
# salt '*' state.apply
```
### Versions Report

```
# salt --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 4.5.1-std-1
         system: Linux
        version: debian 8.4 
```
