### ISSUE TITLE
listen_in/watch_in and AttributeError: 'str' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [saltstack/salt#37034]
Tried to test/apply following scenario:

``` yaml
crontab-env:
  file.replace:
    - name: /etc/crontab
    - pattern: '^MAILTO=.*$'
    - repl: 'MAILTO=""'
    - prepend_if_not_found: True
    - listen_in:
      - cron-service

cron-service:
  service.running:
    - name: crond
    - enable: True
```

and got an error:

```
# salt 'minion1' state.highstate

minion1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 722, in highstate
        whitelist=kwargs.get('whitelist')
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 3274, in call_highstate
        return self.state.call_high(high)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2280, in call_high
        ret = self.call_listen(chunks, ret)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2182, in call_listen
        for key, val in six.iteritems(l_in):
      File "/usr/lib/python2.7/site-packages/salt/ext/six.py", line 583, in iteritems
        return iter(d.iteritems(**kw))
    AttributeError: 'str' object has no attribute 'iteritems'
```

Also it does not restart the service when I replace `listen_in` with `watch_in`, but the error disappears:

```
# salt 'minion1' state.highstate

minion1:
----------
          ID: crontab-env
    Function: file.replace
        Name: /etc/crontab
      Result: True
     Comment: Changes were made
     Started: 01:26:43.944672
    Duration: 38.07 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,6 +1,6 @@
                   SHELL=/bin/bash
                   PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
                  -MAILTO="root"
                  +MAILTO=""

                   # For details see man 4 crontabs
----------
          ID: cron-service
    Function: service.running
        Name: crond
      Result: True
     Comment: The service crond is already running
     Started: 01:26:44.652253
    Duration: 104.541 ms
     Changes:   

Summary for minion1
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time: 142.611 ms
```

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
Master and minion versions:
```
master# salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-88-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

```
minion1# salt-call --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
Seems only `watch` works properly - restarts service when changes in another state present.
`watch_in` and `listen` change file but do not restart service.
`listen_in` raises an error.

**Comment by gtmanfred** [comment]
Is it documented somewhere that you don't have to use the module type in front of the name?

I was under the impression that you always had to give a type.

This should work.

```
crontab-env:
  file.replace:
    - name: /etc/crontab
    - pattern: '^MAILTO=.*$'
    - repl: 'MAILTO=""'
    - prepend_if_not_found: True
    - listen_in:
      - service: cron-service

cron-service:
  service.running:
    - name: crond
    - enable: True
```

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
Yes, it is documented here:
https://docs.saltstack.com/en/latest/ref/states/requisites.html#omitting-state-module-in-requisites

### **Omitting state module in requisites**

*New in version 2016.3.0.*

In version 2016.3.0, the state module name was made optional. If the state module is omitted, all states matching the ID will be required, regardless of which module they are using.
```yaml
- require:
  - vim
```

**Comment by gtmanfred** [comment]
Interesting, thanks.  Let me try and replicate this.

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
But nevertheless thanks a lot for the solution ! I'll pay attention on this moment.

**Comment by gtmanfred** [comment]
It looks like this works if you use listen instead of listen_in, so the following state.

```
crontab-env:
  file.replace:
    - name: /etc/crontab
    - pattern: '^MAILTO=.*$'
    - repl: 'MAILTO=""'
    - prepend_if_not_found: True


cron-service:
  service.running:
    - name: crond
    - enable: True
    - listen:
      - crontab-env
```

But is should be made to work with listen_in and watch_in.  I am going to tag this as a bug and for our core team to look at.
