### ISSUE TITLE
There was no error installing package, although it does not show in pip freeze

### ISSUE THREAD

**Issue by vodik** [saltstack/salt#37038]
### Description of Issue/Question

I installed two packages with `pip.installed`. It succeeds, no problem, installed correctly, but I get the following message when doing `state.apply`:

```
----------
          ID: synapse
    Function: pip.installed
      Result: True
     Comment: There was no error installing package 'systemd-python' although it does not show when calling 'pip.freeze'.
     Started: 00:37:13.344863
    Duration: 16562.359 ms
     Changes:   
              ----------
              systemd-python==232:
                  Installed
----------
```

However, its there, and it _does_ show up with pip.freeze:

```
$ salt pearson pip.freeze bin_env=/var/lib/synapse
peason:
    - ...
    - systemd-python==232
    - ...
```
### Setup

Here are the relevant states I use:

``` yaml
synapse:
  pkg.installed:
    - pkgs:
      - python2-virtualenv
      - python2-pip
  group.present:
    - system: true
  user.present:
    - home: /var/lib/synapse
    - system: true
    - shell: /sbin/nologin
    - groups:
      - synapse
    - require:
      - group: synapse
  virtualenv.managed:
    - name: /var/lib/synapse
    - user: synapse
    - system_site_packages: false
    - require:
      - group: synapse
  pip.installed:
    - pkgs:
      - git+https://github.com/matrix-org/synapse.git@v0.18.1#egg=synapse
      - systemd-python
    - user: synapse
    - bin_env: /var/lib/synapse
    - upgrade: true
  file.managed:
    - name: /etc/systemd/system/synapse.service
    - source: salt://synapse/synapse.service
    - makedirs: true
  module.wait:
    - name: service.systemctl_reload
    - watch:
      - file: synapse
    - require:
      - pkg: synapse
  service.running:
    - enable: true
    - watch:
      - pip: synapse
      - file: synapse
```
### Versions Report

Running on Arch Linux:

```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:   
        machine: x86_64
        release: 4.7.4.201609152234-1-grsec
         system: Linux
        version: Not Installed
```

**Comment by gladiatr72** [comment]
Hey there.  I think that you might be running into a disconnect on how python packages are built and installed/maintained and how pip works.  I haven't taken a deep-dive through the guts of pip. On Debian + derivatives  the packaged pip actually refuses to overwrite a package-installed module.  

Another side-effect on Arch might be that it only reports packages that are actually installed _by_ pip.

**Comment by gtmanfred** [comment]
This appears to just be a small cosmetic bug with the way that the installs from git in pip are handled with pkgs.  If you switch pkgs to names: and have it resolve to multiple different stateids, you will see that the actual response is with the git+https.

```
local:
----------
          ID: synapse
    Function: pkg.installed
      Result: True
     Comment: 2 targeted packages were installed/updated.
     Started: 10:20:59.104284
    Duration: 3736.2 ms
     Changes:
              ----------
              python2-pip:
                  ----------
                  new:
                      8.1.2-1
                  old:
              python2-virtualenv:
                  ----------
                  new:
                      15.0.3-1
                  old:
----------
          ID: synapse
    Function: group.present
      Result: True
     Comment: New group synapse created
     Started: 10:21:02.842740
    Duration: 77.914 ms
     Changes:
              ----------
              gid:
                  995
              members:
              name:
                  synapse
              passwd:
                  x
----------
          ID: synapse
    Function: user.present
      Result: True
     Comment: New user synapse created
     Started: 10:21:02.924886
    Duration: 79.86 ms
     Changes:
              ----------
              fullname:
              gid:
                  995
              groups:
                  - synapse
              home:
                  /var/lib/synapse
              homephone:
              name:
                  synapse
              passwd:
                  x
              roomnumber:
              shell:
                  /bin/bash
              uid:
                  995
              workphone:
----------
          ID: synapse
    Function: virtualenv.managed
        Name: /var/lib/synapse
      Result: True
     Comment: Created new virtualenv
     Started: 10:21:03.006750
    Duration: 3797.149 ms
     Changes:
              ----------
              new:
                  Python 2.7.12
----------
          ID: synapse
    Function: pip.installed
        Name: git+https://github.com/matrix-org/synapse.git@v0.18.1#egg=synapse
      Result: True
     Comment: There was no error installing package 'git+https://github.com/matrix-org/synapse.git@v0.18.1#egg=synapse' although it does not show when calling 'pip.freeze'.
     Started: 10:21:06.989834
    Duration: 186481.6 ms
     Changes:
----------
          ID: synapse
    Function: pip.installed
        Name: systemd-python
      Result: True
     Comment: All packages were successfully installed
     Started: 10:24:13.471980
    Duration: 4238.054 ms
     Changes:
              ----------
              systemd-python==233:
                  Installed

Summary for local
------------
Succeeded: 6 (changed=5)
Failed:    0
------------
Total states run:     6
Total run time: 198.411 s
```

And it looks like it is the fact that it can't find the git+https link in the pip freeze.

I am going to mark this as a cosmetic error that can be fixed at some point.

Thanks reporting this,
Daniel

**Comment by boltronics** [comment]
It looks like this may never have been resolved. I'm encountering it when deploying a custom package hosted on a private server, served to internal hosts via a dumb-pypi repo.

Based on the colour of the output, and the lack of anything under `Changes:`, it appears that a change is not being recognised. As such, this may have now regressed into something more than a cosmetic error.

```
# salt-call state.sls sitemap_generator
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'sitemap_generator/init.sls'
[INFO    ] Running state [sitemap_generator] at time 20:44:45.833827
[INFO    ] Executing state pip.installed for [sitemap_generator]
[INFO    ] Executing command /usr/bin/pip3 in directory '/root'
[INFO    ] Executing command /usr/bin/pip3 in directory '/root'
[INFO    ] Executing command /usr/bin/pip3 in directory '/root'
[INFO    ] Executing command /usr/bin/pip3 in directory '/root'
[INFO    ] Executing command /usr/bin/pip3 in directory '/root'
[INFO    ] There was no error installing package 'sitemap_generator' although it does not show when calling 'pip.freeze'.
[INFO    ] Completed state [sitemap_generator] at time 20:44:49.755767 (duration_in_ms=3921.941)
local:
----------
          ID: Install sitemap_generator using pip
    Function: pip.installed
        Name: sitemap_generator
      Result: True
     Comment: There was no error installing package 'sitemap_generator' although it does not show when calling 'pip.freeze'.
     Started: 20:44:45.833826
    Duration: 3921.941 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   3.922 s
# /usr/bin/pip3 freeze | grep sitemap_generator
sitemap_generator==0.30.0
# /usr/bin/pip3 uninstall --break-system-packages sitemap_generator
Found existing installation: sitemap_generator 0.30.0
Uninstalling sitemap_generator-0.30.0:
  Would remove:
    /usr/local/bin/sitemap-generator
    /usr/local/lib/python3.11/dist-packages/sitemap_generator-0.30.0.dist-info/*
    /usr/local/lib/python3.11/dist-packages/sitemap_generator/*
Proceed (Y/n)? y
  Successfully uninstalled sitemap_generator-0.30.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
# /usr/bin/pip3 freeze | grep sitemap_generator
# salt-call state.sls sitemap_generator
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [sitemap_generator] at time 20:45:45.526440
[INFO    ] Executing state pip.installed for [sitemap_generator]
[INFO    ] Executing command /usr/bin/pip3 in directory '/root'
[INFO    ] Executing command /usr/bin/pip3 in directory '/root'
[INFO    ] Executing command /usr/bin/pip3 in directory '/root'
[INFO    ] Executing command /usr/bin/pip3 in directory '/root'
[INFO    ] Executing command /usr/bin/pip3 in directory '/root'
[INFO    ] There was no error installing package 'sitemap_generator' although it does not show when calling 'pip.freeze'.
[INFO    ] Completed state [sitemap_generator] at time 20:45:49.203432 (duration_in_ms=3676.991)
local:
----------
          ID: Install sitemap_generator using pip
    Function: pip.installed
        Name: sitemap_generator
      Result: True
     Comment: There was no error installing package 'sitemap_generator' although it does not show when calling 'pip.freeze'.
     Started: 20:45:45.526441
    Duration: 3676.991 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   3.677 s
# /usr/bin/pip3 freeze | grep sitemap_generator
sitemap_generator==0.30.0
# salt-call state.show_sls sitemap_generator
[INFO    ] Loading fresh modules for state activity
local:
    ----------
    Install sitemap_generator using pip:
        ----------
        pip:
            |_
              ----------
              name:
                  sitemap_generator
            |_
              ----------
              extra_args:
                  - --break-system-packages
            |_
              ----------
              index_url:
                  http://my-host/pypi/simple/
            |_
              ----------
              trusted_host:
                  my-host
            |_
              ----------
              extra_index_url:
                  https://pypi.org/simple
            |_
              ----------
              pre_releases:
                  True
            |_
              ----------
              upgrade:
                  True
            |_
              ----------
              bin_env:
                  /usr/bin/pip3
            - installed
            |_
              ----------
              order:
                  10000
        __sls__:
            sitemap_generator
        __env__:
            base
# 
```

Here's that state again:
```
Install sitemap_generator using pip:
  pip.installed:
    - name: sitemap_generator
    - extra_args:
      - --break-system-packages
    - index_url: 'http://my-host/pypi/simple/'
    - trusted_host: my-host
    - extra_index_url: 'https://pypi.org/simple'
    - pre_releases: True
    - upgrade: True
    - bin_env: /usr/bin/pip3
```

Running 3006.8:
```
Salt Version:
          Salt: 3006.8
 
Python Version:
        Python: 3.10.14 (main, Apr  3 2024, 21:33:04) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.16.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: aarch64
       release: 6.1.0-23-cloud-arm64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```

Please re-open when you see this, thanks.
