### ISSUE TITLE
Vultr module barfs with `global name '__opts__' is not defined`

### ISSUE THREAD

**Issue by fake-name** [saltstack/salt#37040]
### Description of Issue/Question
I'm trying to create a VPS using the vultr interface.

### Setup
```
client@rabbit:/etc/salt⟫ cat cloud.providers
do:
  driver: digital_ocean
  personal_access_token: <snip>
  ssh_key_file: /etc/salt/pki/cloud/id_rsa
  ssh_key_names: DesktopKey,SaltKey,HerpKey
  script: bootstrap-salt
  #location: New York 1
  create_dns_record: False
  minion:
    master: <snip>

vultr:
  # Vultr account api key
  api_key: <snip>
  driver: vultr
  ssh_key_file: /etc/salt/pki/cloud/id_rsa
  ssh_key_names: DesktopKey,SaltKey,HerpKey
  script: bootstrap-salt

  minion:
    master: <snip>

```

### Steps to Reproduce Issue

Minimal test-script:

```

import salt.cloud

def testf():

	cc = salt.cloud.CloudClient('/etc/salt/cloud')
	cc.create(names        = ['test-1'],
		provider           ='vultr',
		private_networking = False,
		image              = 'Ubuntu 16.04 x64',
		location           = 40,
		size               = u'29'
		)

if __name__ == '__main__':

	testf()


```

Note that I'm not totally sure the image, size, and location parameters are correct, because what they're /supposed/ to be is not documented anywhere. I'm going based on guesswork from looking at the `vultrpy.py` file, though I don't know if the arguments to CloudClient.create are passed through to the `create()` call in `vultrpy.py`, or if/how they're mangled.

#### Expected behaviour:
 - Vultr VPS is created. 

#### Actual behaviour:

VPS creation fails with error:

```
1 client@rabbit:~/AutoTriever/marshaller⟫ sudo python salt_runner_test.py
Traceback (most recent call last):
  File "salt_runner_test.py", line 19, in <module>
    testf()
  File "salt_runner_test.py", line 12, in testf
    size               = u'29'
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 408, in create
    mapper.create(vm_))
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1281, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vultrpy.py", line 224, in create
    transport=__opts__['transport']
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1721, in fire_event
    sock_dir = os.path.join(__opts__['sock_dir'], 'master')
NameError: global name '__opts__' is not defined

```

### Versions Report
Test system 1:
```
130 client@rabbit:/etc/salt⟫ salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.14.32-xxxx-grs-ipv6-64
         system: Linux
        version: Ubuntu 14.04 trusty
```

Test system 2 (note: does not have salt-master installed, just salt-cloud):
```
127 durr@rwpscrape:/media/Storage/Scripts/AutoTriever/marshaller⟫ salt-cloud --versions-report
Salt Version:
            Salt: 2016.3.3

Dependency Versions:
 Apache Libcloud: 0.20.0
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 2.4.2
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: 1.0.3
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: Not Installed
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: Not Installed

System Versions:
            dist: Ubuntu 16.04 xenial
         machine: x86_64
         release: 4.4.0-38-generic
          system: Linux
         version: Ubuntu 16.04 xenial

```

This behaviour is consistent across two systems I have to test on.
