### ISSUE TITLE
pkg module and state not working in Arch Linux

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#37044]
### Description of Issue/Question

The pkg state and module won't work on latest Arch Linux. This might be related to an Arch upgrade, since it was working before in current version.
### Setup

Latest Arch Linux x64, running salt-zmq 2016.3.3
### Steps to Reproduce Issue

```
salt-call pkg.version bash
'pkg.version' is not available.

and

     Comment: State 'pkg.uptodate' was not found in SLS 'maintenance.linux.arch'
              Reason: 'pkg' __virtual__ returned False
```

The module is loaded and the docs confirm this.

```
salt-call sys.doc pkg 
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.8.3
       cherrypy: 8.1.0
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.5
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.5.0
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: x86_64
        release: 4.7.6-1-ARCH
         system: Linux
        version: Not Installed
```
