### ISSUE TITLE
saltenv option does not work for state.apply

### ISSUE THREAD

**Issue by rehmanzile** [saltstack/salt#37075]
### Setup
I have the following environment defined in /etc/salt/master:

```
file_roots:
  base:
    - /srv/salt/nyansa/base
  staging:
    - /srv/salt/nyansa/staging
  staging2:
    - /srv/salt/nyansa/staging2
  staging3:
    - /srv/salt/nyansa/staging3
  staging4:
    - /srv/salt/nyansa/staging4
  staging5:
    - /srv/salt/nyansa/staging5
  prod:
    - /srv/salt/nyansa/prod

```

And when I execute ```sudo salt 'staging3-manager01-ui' state.apply saltenv=staging3```, it picks up the pillar files from prod environment.

Here is the pillar file structure:

```
pillar/
├── prod
│   ├── common
│   │   └── init.sls
│   ├── manager
│   │   └── init.sls
│   ├── top.sls
│   └── ui
│       └── init.sls
└── staging3
    ├── common
    │   └── init.sls
    ├── manager
    │   └── init.sls
    ├── top.sls
    └── ui
        └── init.sls

```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-43-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```
