### ISSUE TITLE
salt remount device every time

### ISSUE THREAD

**Issue by basic-system** [saltstack/salt#37093]
### Description of Issue/Question
if we have state with mount
```
/hugetlbfs:
  mount.mounted:
    - device: hugetlbfs
    - fstype: hugetlbfs
    - opts: size=110g,mode=0777
```
and already mount it with options size=110g,mode=0777 salt start remount this device every time.

### Setup
```
/hugetlbfs:
  mount.mounted:
    - device: hugetlbfs
    - fstype: hugetlbfs
    - opts: size=110g,mode=0777

# cat /proc/mounts  | grep huge
hugetlbfs /hugetlbfs hugetlbfs rw,relatime,size=110g,mode=0777 0 0
```
### Versions Report
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 3.2.2

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.18.35-35
         system: Linux
        version: Ubuntu 12.04 precise
```
