### ISSUE TITLE
content parameter in file.line should be optional with delete mode

### ISSUE THREAD

**Issue by efficks** [saltstack/salt#37092]
### Description of Issue/Question

When using file.line with the delete mode, the content parameter is still mandatory. It should be set optional with a default value of 'None'.
### Setup

```
filename:
  file.line:
    - match: myline
    - mode: delete
```
### Steps to Reproduce Issue

This failed with " Missing parameter content for state file.line"
If I added an empty string, it works.
### Versions Report

salt-minion 2016.3.3 (Boron)
