### ISSUE TITLE
virtualenv.managed doesn't makes changes according to user argument

### ISSUE THREAD

**Issue by dtkerr** [saltstack/salt#37168]
### Description + Reproduction

Much like changing the `user` value in a `file.managed` state, the `user` in the virutalenv.managed` would presumably do the same and ensure the virtualenv is owned by the user.

In fact it does do this the first time it makes changes

```
virtualenv.managed:
  - user: foo
  etc...
```

will correctly effect a virtualenv owned by the user `foo` if the virtualenv doesn't yet exist, however if you change it

```
virtualenv.managed:
  - user: bar
  etc...
```

and re-run salt it'll report no changes and that the virtualenv is already present, rather than the more expected outcome of attempting to switch its ownership, or at least reporting the chown as skipped as the virtualenv already exists.

If you manually remove the virtualenv and run the same state again, though, you'll find that user `bar` now does own it.

I don't know if it's relevant, but: this was done using salt locally in masterless mode.
### Versions Report

```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: Not Installed
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 4.8.3-1-ARCH
         system: Linux
        version: Not Installed
```
