### ISSUE TITLE
states.pkg.mod_watch doco missing (all versions)

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#37172]
### Description of Issue/Question

Try to work out if this will only be true in a state when a package is installed.  Found out their needs to be some more doco for this.

```
    Function: pkg.mod_watch
      Result: False
     Comment: pkg.None does not work with the watch requisite
     Started: 01:21:31.690929
    Duration: 0.332 ms
     Changes:
```
