### ISSUE TITLE
The State execution failed to record the order in which all states were executed spam while running pkg.upgrade from orchestration runner

### ISSUE THREAD

**Issue by mikeadamz** [saltstack/salt#37174]
### Description of Issue/Question

The State execution failed to record the order in which all states were executed spam while running pkg.upgrade from orchestration runner

``` yaml
ansible.unix-security.net_master:
----------
          ID: patch_warn
    Function: salt.function
        Name: cmd.run
      Result: True
     Comment: Function ran successfully. Function cmd.run ran on redhat7.unix-security.net.
     Started: 19:29:31.925204
    Duration: 207.083 ms
     Changes:  
              redhat7.unix-security.net:

----------
          ID: pkg.upgrade
    Function: salt.function
      Result: True
     Comment: Function ran successfully. Function pkg.upgrade ran on redhat7.unix-security.net.
     Started: 19:29:32.132511
    Duration: 51251.277 ms
     Changes:  
              redhat7.unix-security.net:
              The State execution failed to record the order in which all states were executed. The state return missing data is:
              {'new': '2016h-1.el7', 'old': '2016g-2.el7'}

              Summary for redhat7.unix-security.net
              -----------
              Succeeded: 0
              Failed:  0
              -----------
              Total states run:   0
              Total run time: 0.000 ms
----------
          ID: reboot_warn
    Function: salt.function
        Name: cmd.run
      Result: True
     Comment: Function ran successfully. Function cmd.run ran on redhat7.unix-security.net.
     Started: 19:30:23.384135
    Duration: 245.779 ms
     Changes:  
              redhat7.unix-security.net:

----------
          ID: system.reboot
    Function: salt.function
      Result: True
     Comment: Function ran successfully. Function system.reboot ran on redhat7.unix-security.net.
     Started: 19:30:23.630271
    Duration: 212.411 ms
     Changes:  
              redhat7.unix-security.net:
                 Shutdown scheduled for Sun 2016-10-23 19:31:23 PDT, use 'shutdown -c' to cancel.

Summary for ansible.unix-security.net_master
------------
Succeeded: 4 (changed=3)
Failed:   0
------------
Total states run:    4
Total run time: 51.917 s
```
### Setup

Orestration State

``` yaml
pkg.upgrade:
  salt.function:
    - tgt: redhat7.unix-security.net

reboot_warn:
  salt.function:
   - name: cmd.run
   - tgt: redhat7.unix-security.net
   - arg:
    - echo Patching complete rebooting in 60 seconds |wall

system.reboot:
  salt.function:
    - tgt: redhat7.unix-security.net
    - arg:
     - 1
```
### Steps to Reproduce Issue

Run above orchestration state on a host
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Master:

```
alt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

```

Minion:

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 29 2016, 10:12:21)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.36.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

```
