### ISSUE TITLE
opennebula driver returns 0.0.0.0 for VM IP addr

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#37236]
### Description of Issue/Question

The `opennebula` driver returns 0.0.0.0 for VM IP address.
#### master config

``` sls
# cat /etc/salt/master
log_fmt_console: '%(colorlevel)s %(colormsg)s'
hash_type: sha256

fileserver_backend:
  - git
  - roots

gitfs_provider: gitpython
gitfs_remotes:
  - git://github.com/jfindlay/salt-jenkins.git:
    - base: salttesting_namespec
```
#### provider config

``` sls
# cat /etc/salt/cloud.providers.d/open_nebula.conf
open_nebula:
  driver: opennebula
  fqdn_base: <fqdn-base>
  xml_rpc: http://<xml-rpc address>
  user: opennebula-user
  password: <password>
  private_key: /root/.ssh/id_opennebula
```
#### profile config

``` sls
one_centos7:
  image: centos7-jenkins-template
  template: centos7-jenkins-template
  provider: open_nebula
```
### Steps to Reproduce Issue

``` console
# salt-cloud --no-deploy -p one_centos7 jmoney-centos7
jmoney-centos7:
    ----------
    Error:
        ----------
        No Deploy:
            'deploy' is not enabled. Not deploying.
    id:
        1905
    image:
        centos7-jenkins-template
    name:
        jmoney-centos7
    private_ips:
        0.0.0.0
    public_ips:
    size:
        2048
    state:
        3
```
### Versions Report

``` yaml
# salt-cloud --versions
Salt Version:
            Salt: 2016.3.2

Dependency Versions:
 Apache Libcloud: 0.20.1
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: Not Installed
           gitdb: 0.6.4
       gitpython: 2.0.8
           ioflo: Not Installed
          Jinja2: 2.7.2
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: 0.21.1
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.7
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.3.0
            RAET: Not Installed
           smmap: 0.9.0
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4

System Versions:
            dist: centos 7.2.1511 Core
         machine: x86_64
         release: 3.10.0-327.4.5.el7.x86_64
          system: Linux
         version: CentOS Linux 7.2.1511 Core
```

``` console
# rpm -q one-context
one-context-4.14.4-1.noarch
```
