### ISSUE TITLE
saltapi with tornado > @wheel = 400 Invalid Client: Client not found in salt clients

### ISSUE THREAD

**Issue by hoitsang** [saltstack/salt#37240]
It looks like salt-api tornado doesn't support client=wheel call. 
Is that true?

/etc/salt/master.d/salt-api.conf
```
external_auth:
  pam:
    saltapi:
      - '@wheel'
      - '@runner'
      - '@jobs'
      - cmd.*
      - test.*
```

```
[vagrant@workbench ~] token=`source /vagrant/vagrant/proxy.sh && curl -sSk https://saltmaster/tornado/login -d username=saltapi -d password=password -d eauth=pam -c cookies.txt | python -c "import json,sys;obj=json.load(sys.stdin);print obj['return'][0]['token'];"`
[vagrant@workbench ~]$ curl -ski https://saltmaster/tornado -H "Accept: application/json" -H "X-Auth-Token: $token" -d client='wheel' -d tgt='*' -d fun='key.accept' -d arg='minion2'
HTTP/1.1 400 Bad Request
Date: Wed, 26 Oct 2016 00:02:02 GMT
Server: TornadoServer/4.2.1
Content-Length: 52
Content-Type: text/html; charset=UTF-8
Connection: close

400 Invalid Client: Client not found in salt clients
```
salt 2015.8.8.2 (Beryllium)
