### ISSUE TITLE
Implement template state entries?

### ISSUE THREAD

**Issue by jbremer** [saltstack/salt#37295]
### Description of Issue/Question

Assuming I'm having some sort of complex state entry (I'm not sure what the correct term is), e.g., a `cmd.run` entry that requires a `user`, `name`, and at least a couple of `require` statements. Now because I need to run multiple commands with this same setup, I have to copy and paste these attributes etc multiple times.
Would it be possible to somehow inherit a state entry?
### Setup

E.g., something like the following would be great.

```
newcommand:
  cmd.run:
    - user: {{ salt['pillar.get']('some:config:variable', 'test') }}
    - require:
      - pkg: somepackage
      - cmd: somecommand

actualcommand:
  newcommand:
    - name: do something
    # Automatically inherits `user` and `require` from `newcommand`.
```

**Comment by lorengordon** [comment]
Jinja to the rescue? Writing this without testing, so probably the reference to `{{ cmd_defaults }}` isn't quite right, but maybe with a bit of testing it could work...

```
{%- load_yaml as cmd_defaults %}
- user: salt.pillar.get('some:config:variable', 'test')
- require:
  - pkg: somepackage
  - cmd: somecommand
{% endload %}

newcommand:
  cmd.run:
    - name: newcommand
    {{ cmd_defaults | indent(4) }}

othercommand:
  cmd.run:
    - name: othercommand
    {{ cmd_defaults | indent(4) }}
```

**Comment by gtmanfred** [comment]
yaml can do this as well

```
newcommand:
  cmd.run:
    - user: {{ salt['pillar.get']('some:config:variable', 'test') }}
    - require: &requires
      - pkg: somepackage
      - cmd: somecommand

actualcommand:
  newcommand:
    - name: do something
    - require: <<: *requires
```

I don't think that we are going to change this behavior since the templating languages allow for this behavior.
