### ISSUE TITLE
Properly evaluate $HOME in file.recurse with specified user

### ISSUE THREAD

**Issue by jbremer** [saltstack/salt#37294]
### Description of Issue/Question

Wouldn't it make sense that `~/hello` evaluates to whatever `$HOME` points to for a specified user, i.e., if the `user` attribute was provided? Currently it seems to evaluate `~/hello` to the `$HOME` of the user that started `salt-minion`.
### Setup

```
hello:
  file.recurse:
    - name: ~/hello
    - source: salt://hello
    - user: nothello
```
### Versions Report

Salt `2016.3.3`.
