### ISSUE TITLE
Type checking in templates?

### ISSUE THREAD

**Issue by jbremer** [saltstack/salt#37300]
### Description of Issue/Question

It would make sense to me to provide better type checking in certain state attributes.
### Setup

Let's assume the following typo in a state:

```
something:
  cmd.run:
    - name: >
        VBoxManage setextradata global "HostOnly/vboxnet0/IPAddress"
        {{ salt['pillar.get']('vmcloak:ipprefix'), 'hehe' }}1 && true
    - user: {{ salt['pillar.get']('cuckoo:user', 'cuckoo') }}
    - require:
      - cmd: vboxnet0_create
```

Here I accidentally typed `), 'hehe'` instead of `, 'hehe')`. This actually happened to me earlier while failing to copy and paste. Now because it's evaluating a tuple as string, you end up trying to execute some messed up command. Wouldn't it make sense to only allow `jinja2` expressions for certain fields to return certain types (i.e., in this case, either a string or an integer)?

Yes, I'm aware that in this template the Jinja2 expression is embedded in the value, but still this should be somehow possible while evaluating the expression.
### Versions Report

Salt `2016.3.3`.
