### ISSUE TITLE
modules/aptpkg.py calling os.environ.update() has unintended side effects on Debian systems

### ISSUE THREAD

**Issue by mrpouit** [saltstack/salt#37332]
Hi,

The aptpkg module contains the following code:

```
[...]
DPKG_ENV_VARS = {
    'APT_LISTBUGS_FRONTEND': 'none',
    'APT_LISTCHANGES_FRONTEND': 'none',
    'DEBIAN_FRONTEND': 'noninteractive',
    'UCF_FORCE_CONFFOLD': '1',
}
[...]
def __init__(opts):
    '''
    For Debian and derivative systems, set up
    a few env variables to keep apt happy and
    non-interactive.
    '''
    if __virtual__():
        # Export these puppies so they persist
        os.environ.update(DPKG_ENV_VARS)
```

AIUI, this means that the four variables listed above will be present in the environment of all commands launched by salt after that.

This is more or less harmless to most commands, unless one wants to reconfigure a package that uses ucf, for example `apt-listchanges`:

```
debconf-utils:
  pkg:
    - installed

apt-listchanges:
  debconf.set:
    - data:
        'apt-listchanges/save-seen': {'type': 'boolean', 'value': True}
        'apt-listchanges/confirm': {'type': 'boolean', 'value': False}
        'apt-listchanges/email-address': {'type': 'string', 'value': 'root'}
        'apt-listchanges/which': {'type': 'select', 'value': 'both'}
        'apt-listchanges/frontend': {'type': 'select', 'value': 'mail'}
    - require:
      - pkg: debconf-utils
  pkg:
    - installed
    - require:
      - debconf: apt-listchanges
  cmd.wait:
    - name: /usr/sbin/dpkg-reconfigure -fnoninteractive apt-listchanges
    - watch:
      - debconf: apt-listchanges
    - env:
      - DEBCONF_NONINTERACTIVE_SEEN: "true"
      - DEBIAN_FRONTEND: "noninteractive"
```

Since UCF_FORCE_CONFFOLD is already present in the environment because of the aptpkg module, the `dpkg-reconfigure` command will basically be a noop, as UCF_FORCE_CONFFOLD=1 tells ucf to never replace the conffile.

As a workaround one can pass:

```
    - env:
      - UCF_FORCE_CONFFNEW: "1"
      - UCF_FORCE_CONFFOLD: ""
```

to each dpkg-reconfigure cmd, but it's easy to forget about it...

It would be best if these environment variables would not leak outside of apt/dpkg calls, because of the possible side-effects, or at least could you put a warning in the documentation please?

Thanks!

Tested on 2015.8.12, but the code is the same in git master, so the issue should still be present.
