### ISSUE TITLE
LXC cloud interface doesn't allow to configure DNS servers from DHCP

### ISSUE THREAD

**Issue by multani** [saltstack/salt#37381]
### Description of Issue/Question
Creating a new LXC container via the Salt Cloud interface using an automatic configured network forces the use of the 8.8.8.8 and 4.4.4.4 DNS servers, unless you specifically specifies the servers to use instead of those.

See: https://github.com/saltstack/salt/blob/develop/salt/modules/lxc.py#L402

### Setup
Current LXC profiles defined:
```
lxc.container_profile:
  debian-ct-lxc:
    template: debian
    backing: lvm
    vgname: main
    size: 8G
    fstype: ext4

lxc.network_profile:
  debian-net-lxc:
    eth0:
      type: veth
      link: br0
      flags: up
```
with the following Salt Cloud profile:
```
host1-lxc:
  lxc_profile: debian-ct-lxc
  minion:
    master: salt-master.mydomain
    master_port: 4506
  network_profile: debian-net-lxc
  provider: host1-lxc
```

### Steps to Reproduce Issue
Creating a new container:
```
salt-master:~$ sudo salt-cloud --profile host1-lxc testxxx
```
The new container never connects back to the Salt master:
```
salt-master:~$ salt 'host1*' lxc.run testxxx "cat /etc/resolv.conf"
host1.mydomain:
    nameserver 8.8.8.8
    nameserver 4.4.4.4
salt-master:~$ salt 'host1*' lxc.restart testxxx
host1.mydomain:
    ----------
    restarted:
        True
    result:
        True
    state:
        ----------
        new:
            running
        old:
            running
salt-master:~$ salt 'host1*' lxc.run testxxx "cat /etc/resolv.conf"
host1.mydomain:
    domain mydomain
    search mydomain
    nameserver 10.40.0.2
```

### Versions Report
```
Salt Version:
           Salt: 2015.8.12
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.5 
```
