### ISSUE TITLE
Orchestration arguments (kwarg) not being interperted / How I learned to stop worrying about documentation and love experimenting

### ISSUE THREAD

**Issue by edwardsdanielj** [saltstack/salt#37383]
Hello again python addicts, have an interesting little issue with an orchestration state when I try to use salt.function.  I'm not sure if this is a bug or a documentation issue so here we go.
So when I look at the [orchestration doc page](https://docs.saltstack.com/en/latest/topics/orchestrate/orchestrate_runner.html#examples) I see the example given for file.copy includes arguments like so:
```
- kwarg:
      - remove_existing: true
```
However, when I run my orchestration state:
**`salt-run state.orch orchestration.backup_local_cache`**
I get the result:
```
<salt_master_node>:
----------
          ID: backup_local_cache
    Function: salt.function
        Name: file.copy
      Result: True
     Comment: Function ran successfully. Function file.copy ran on <foo node>, <bar node>.
     Started: 11:46:04.415475
    Duration: 505.07 ms
     Changes:
              <bar node>:
                  ERROR executing 'file.copy': Cannot copy overwriting a directory without recurse flag set to true!
              <foo node>:
                  ERROR executing 'file.copy': Cannot copy overwriting a directory without recurse flag set to true!
              
Summary for <salt_master_node>
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
I looked at the [file.copy module doc](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.copy) for reference and my orchestration state looked like this at first:
```
#Not working state
backup_local_cache:
  salt.function:
    - name: file.copy
    - tgt: '<node id>'
    - arg:
      - /path/to/directory
      - /path/to/directory/backup
    - kwarg:
      - recurse: true
      - remove_existing: true
```
then after I saw the errors listed above, I changed it to:
```
#Working state
backup_local_cache:
  salt.function:
    - name: file.copy
    - tgt: '<node id>'
    - arg:
      - /path/to/directory
      - /path/to/directory/backup
      - recurse: true
      - remove_existing: true
```
and then everything ran fine.

### Steps to Reproduce Issue
All I had to do was make my orchestration state look like the documentation.

### Versions Report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
   python-gnupg: 0.3.7
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.3.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago

**Comment by gtmanfred** [comment]
So, kwarg needs to be a dictionary, but i believe it is interpreting as a list of dictionaries (an Ordered Dict).  But if you use the following, it also works.

```
[root@salt ~]# cat /srv/salt/base/orch.sls
#Not working state
backup_local_cache:
  salt.function:
    - name: file.copy
    - tgt: 'salt*'
    - arg:
      - /tmp/test.txt
      - /tmp/backup.txt
    - kwarg:
        recurse: true
        remove_existing: true
```
