### ISSUE TITLE
Some core grains are inaccurate or incomplete for Solaris

### ISSUE THREAD

**Issue by d101nelson** [saltstack/salt#37389]
### Description of Issue/Question

The 'kernelrelease'  and some 'os*' grains on Solaris SPARC are inaccurate or incomplete.  

Take, for example, Solaris 10 SPARC:
```
kernelrelease:
    5.10
os:
    Solaris
os_family:
    Solaris
osarch:
    sparcv9
osfinger:
    Solaris-10 9/10
osfullname:
    Solaris
osmajorrelease:
    10
osrelease:
    5.10
osrelease_info:
    - 5
    - 10
```

I think that 'kernelrelease' should read something like 'Generic_150400-17' as reported by 'uname -v'.  I'm not sure of the original intentions of 'osfinger', however; should it be 'Solaris-10' or 'Solaris-10 9/10'?  Perhaps 'osfinger' should be 'Solaris-10' and a new grain named 'osreleasedate' should be '9/10' - thoughts?

Solaris 11 SPARC:
```
kernelrelease:
    5.11
os:
    Solaris
os_family:
    Solaris
osarch:
    sparcv9
osfullname:
    Solaris
osrelease:
    None
```
I think that 'kernelrelease' should be '11.3' as reported by 'uname -v'.  Note the missing/incorrect 'osfinger', 'osmajorrelease', 'osrelease', and 'osrelease_info' which should be 'Solaris-11', '11', '5.11' and '[5, 11]', respectively.

I'd like to add 'os_sru' (or a similar name) to capture the SRU version of the Solaris 11 OS.

Not being familiar w/ x86 versions of Solaris, some of these issues may be a mute.  If you've data, I'd be interested in seeing it.
 
I'm certainly aware that mucking around w/ core grains could be disruptive to established Solaris Salt users.  However, I'd be willing to contribute fixes in this area if a consensus could be reached on what the proper values should be (some are obvious while others are open to discussion/interpretation) and how to go about integrating them into Salt.

The author this section of code attempted to parse /etc/release which has changed formats over the years.  While I can guess on some of their original intentions, I'm not sure why they didn't use 'os.uname()' for some of the data.  If you've info that could enlighten me in this area, I'd appreciate that, too.

### Versions Report
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 8.0.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Oct 10 2016, 09:35:50)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: sun4u
        release: 5.11
         system: SunOS
        version: Not Installed
```
