### ISSUE TITLE
win_wua.list_updates expects argument

### ISSUE THREAD

**Issue by Cashwini** [saltstack/salt#37394]
### Description of Issue/Question
I get the error, `Passed invalid arguments to win_wua.list_updates: The Python instance can not be converted to a COM object` upon executing the command, `sudo salt '*' win_wua.list_updates` 

### Setup
Minion is windows 2012 VM with 2016.3.1 salt version and master is Ubuntu VM with 2016.3.3 salt version

### Steps to Reproduce Issue
Run, `sudo salt '*' win_wua.list_updates` 

### Versions Report
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-32-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
Unfortunately I am unable to replicate this.

```
[root@salt ~]# salt windows\* win_wua.list_updates
windows:
    ----------
    0025cccd-6122-483a-a646-dd3ea3ff861f:
        ----------
        Categories:
            - Updates
            - Windows Server 2012 R2
        Description:
            Install this update to resolve issues in Windows. For a complete listing of the issues that are included in this update, see the associated Microsoft Knowledge Base article for more information. After you install this item, you may have to restart your computer.
        Downloaded:
            False
        EULAAccepted:
            True
        Installed:
            False
        KB:
            KB3179574
        Mandatory:
            False
        NeedsReboot:
            False
        RebootBehavior:
            Can Require Reboot
        Severity:
        Title:
            Update for Windows Server 2012 R2 (KB3179574)
        UserInput:
            False
        guid:
            0025cccd-6122-483a-a646-dd3ea3ff861f
```

It is working here on a windows 2012 Standard server VM

```
[root@salt ~]# salt windows\* grains.get osfullname
windows:
    Microsoft Windows Server 2012 R2 Standard
```

With 2016.3.1 installed

```
[root@salt ~]# salt windows\* test.versions_report
windows:
    Salt Version:
               Salt: 2016.3.1

    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.3.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.2
              ioflo: 1.5.3
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.3
                ZMQ: 4.1.2

    System Versions:
               dist:
            machine: AMD64
            release: 8.1
             system: Windows
            version: 8.1 6.3.9600  Multiprocessor Free
```

Can you provide me with any more information about this?

**Comment by Cashwini** [comment]
@gtmanfred I have no problem using this on windows 8.1. It is only on windows 2012 that I am getting this error.

**Comment by gtmanfred** [comment]
Can you provide me with the `salt "minion" test.versions_report` from that windows minion please?

I booted a windows server 2012 image on the rackspace cloud to test this.

**Comment by Cashwini** [comment]
```

**Comment by Cashwini** [comment]
```
    Salt Version:
               Salt: 2016.3.1
     
    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.3.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.2
              ioflo: 1.5.3
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.3
                ZMQ: 4.1.2
     
    System Versions:
               dist:   
            machine: AMD64
            release: 8.1
             system: Windows
            version: 8.1 6.3.9600  Multiprocessor Free
```
