### ISSUE TITLE
In 'salt/key' events there are acts that never happen

### ISSUE THREAD

**Issue by alisson276** [saltstack/salt#37448]
The documentation about Salt Master Events (https://docs.saltstack.com/en/latest/topics/event/master_events.html#key-events) says: "act -- The new status of the minion key: accept, pend, reject" in KEY EVENTS (salt/key). Anyway, that event never happens.

When using the reactor:
```
reactor:
  - 'salt/key':
    - /srv/salt/_reactors/email-on-register.sls
```

And email-on-register.sls:
```
email-on-register:
  runner.process_minion_data.sendmail:
    - fromaddr: noreply@domain.com
    - toaddrs: 'anyone@domain.com'
    - subject: "[Salt] Host {{ data['id'] }}"
    - data_str: "Minion id {{ data['id'] }}:\nState: {{ data['act'] }}"
    - smtp_server: 'smtp.domain.com'
    - username: 'noreply@domain.com'
    - password: 'password'
```

The emails is only sent in accept and delete (not documented!), but not in pend or reject events.
