### ISSUE TITLE
zfs.volume_present state always updates state and fails if volblocksize property set (besides first run)

### ISSUE THREAD

**Issue by elyulka** [saltstack/salt#37507]
### Description of Issue/Question
If zfs.volume_present has defined property `volblocksize` then module tries to update it but volblocksize can be specified only at creation time.

Why it tries to update it if `zfs get all zroot2/swap` returns:
```
root@nas:/var/log/salt# 
NAME         PROPERTY               VALUE                  SOURCE
zroot2/swap  volblocksize           4K                     -
```

### Steps to Reproduce Issue

Define state:
```
zroot2/swap:
  zfs.volume_present:
    - name: "zroot2/swap"
    - volume_size: "4G"
    - properties:
        "org.freebsd:swap": "on"
        "checksum": "off"
        "compression": "off"
        "dedup": "off"
        "sync": "disabled"
        "primarycache": "none"
        "com.sun:auto-snapshot": "false"
        "volblocksize": 4096
```
Apply first time (create volume): `$ salt  '*' state.highstate`
Apply next time: `$ salt  '*' state.highstate`

Result of next state.highstate:
```
          ID: zroot2/swap
    Function: zfs.volume_present
      Result: False
     Comment: volume zroot2/swap failed to be updated
     Started: 12:00:25.438612
    Duration: 57.436 ms
     Changes:
```
/var/log/salt/minon:
```
2016-11-07 12:00:25,495 [salt.loaded.int.module.cmdmod                                   ][ERROR   ][50819] Command '/sbin/zfs set volblocksize=4096 zroot2/swap' failed with return code: 1
2016-11-07 12:00:25,495 [salt.loaded.int.module.cmdmod                                   ][ERROR   ][50819] stderr: cannot set property for 'zroot2/swap': 'volblocksize' is readonly
2016-11-07 12:00:25,496 [salt.loaded.int.module.cmdmod                                   ][ERROR   ][50819] retcode: 1
2016-11-07 12:00:25,496 [salt.state                                                      ][ERROR   ][50819] volume zroot2/swap failed to be updated
```

#### Master
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.27-moby
         system: Linux
        version: Ubuntu 16.04 xenial
```
#### Minion
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct 27 2016, 01:17:05)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 11.0-RELEASE-p2
         system: FreeBSD
        version: Not Installed
```
