### ISSUE TITLE
Feature: dockerng state module to run an image (container) as a command

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#37522]
It'd be nice to have a method in dockerng state module which runs an image as a command (Similarly to run method of cmd state module)

ex:
```
run_migration:
  dockerng.cmd_run:
    - name: python migrate.py db
    - image: registry.com/my_uber_project_image
    - environment:
      - ...
    - binds:
      - ...
    - timeout: ..
    - onlyif: ...
    - unless: ...
    - creates: ...
```

**Comment by Ch3LL** [comment]
@zerthimon hmm interestingly enough there was a run command for dockerio but not dockerng. Looks like we shuld add this to dockerng as well. thanks

As a workaround you could probably use the `module.run` state and call the dockerng run command as documented [here](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockerng.html#salt.modules.dockerng.run)

**Comment by terminalmage** [comment]
Can you elaborate on your use case? I'm not sure I understand.

**Comment by zerthimon** [comment]
@terminalmage 

I'd like to compile assets and upload them to CDN before I run web app container, so I work around this problem with just `cmd.run` like this:

```
sync_assets_command:
  cmd.run:
    - name: docker run --rm --link fluentd-logger:fluentd-logger -e RAILS_ENV={{ env }} -e RACK_ENV={{ env }} -e ASSETS_BUILD=true {{ app_image_name }} bundle exec rake assets:sync
    - require:
      - dockerng: app_image
      - dockerng: fluentd-logger_container
```

This command just exits when finished.

Then I just depend my web app container on this command with `- require sync_assets_command`.
