### ISSUE TITLE
SaltStack warns about python-software-properies on Xenial (ubuntu) - still ...

### ISSUE THREAD

**Issue by ekristen** [saltstack/salt#37525]
### Description of Issue/Question

`python-software-properties` is no longer valid on Xenial (16.04), it is now `sofware-properties-common`, salt should understand the difference.

### Setup
```
someppa:
  pkgrepo.managed:
    - name: someppa
    - ppa: someppa
```

### Steps to Reproduce Issue
By adding any ppa, saltstack warns that things aren't going to work properly, the package name has changed.

### Versions Report
```
2016.3.4
```
