### ISSUE TITLE
 file.recurse with empty directory: Recurse failed: none of the specified sources were found

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#37539]
### Description of Issue/Question
I follow the advice, which I got on StackOverflow: http://stackoverflow.com/questions/39764078/saltstack-file-recurse-per-minion

I get this error message:

> Recurse failed: none of the specified sources were found

### Setup

monitoring__files_per_minion:
```
  file.recurse:
    - source: 
      - salt://monitoring/files/per_minion/{{ grains.id }}
      - salt://monitoring/files/per_minion/_default
    - name: /
    - template: jinja

```

In my case the directory `_default` is empty and should be empty.

I think it is a valid use case to do `file.recurse` with an empty directory.

Is the current behaviour a bug or a feature?

### Versions Report
```
salt:/srv # salt --versions-report
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: 2.1
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.22.0
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
         pygit2: 0.22.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.2
 
System Versions:
           dist: SuSE 12.3 x86_64
        machine: x86_64
        release: 3.7.10-1.45-default
         system: Linux
        version: openSUSE  12.3 x86_64
```

### Other solutions welcome

If there is a better solution (than two provide two sources for file.recurse) to solve my use case, please let me know.

**Comment by gtmanfred** [comment]
what is happening is that you are overwritting the source variable.

Can you try to set it like the following.  Which is closer to http://stackoverflow.com/a/39764583  It is also worth noting that you are using file.recurse and not file.managed.  And file.recurse does not have the same note as file.managed for [source being a list](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.recurse)

```
file_to_recurse:
  file.recurse:
    - source: 
      - salt://monitoring/files/per_minion/{{ grains.id }}
      - salt://monitoring/files/per_minion/_default
    - name: /
    - template: jinja
```

This makes source a list instead of two individual strings.
