### ISSUE TITLE
2016.11.0rc2 archive.extracted always 

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#37577]
### Description of Issue/Question
if_missing does not seem to be honnered for archive.extracted

### Setup
```
syncthing::binary:
  archive.extracted:
    - name: /opt/syncthing
    - if_missing: /opt/syncthing/syncthing
    - archive_format: tar
    - options: --strip-components=1
    - source: https://github.com/syncthing/syncthing/releases/download/v0.14.10/syncthing-solaris-amd64-v0.14.10.tar.gz
    - skip_verify: True
    - enforce_ownership_on: /opt/syncthing
    - user: syncthing
    - group: syncthing
````

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
