### ISSUE TITLE
dockerng.running fails on memory: 256M

### ISSUE THREAD

**Issue by p-thurner** [saltstack/salt#37582]
### Description of Issue/Question

Using memory: 256M in dockerng.running triggers an error with and without test=true

### Setup
```
bloonix_satellite_docker_foobar_running:
  dockerng.running:
    - name: BloonixSatellite_foobar
    - image: 'satellitesharing/bloonix-satellite'
    - detach: True
    - memory: 256M
    - memory_swap: '-1'
    - cpu_shares: '0.5'
    - restart_policy: 'on-failure:2'
    - environment:
      - AUTHKEY: sadfdsafdsafdsfdsafsafsfsafsadfdsafds
    - port_bindings:
      - '1234:5646'
```

### Steps to Reproduce Issue
run the state above with and without true gives me:

```
          ID: bloonix_satellite_docker_Example_GmbH_running
    Function: dockerng.running
        Name: BloonixSatellite_Example_GmbH
      Result: False
     Comment: memory must be an integer, or an integer followed by K, M, G, T, or P (example: 512M)
     Started: 17:22:17.945845
    Duration: 14.606 ms
     Changes:   
```

### Versions Report
salt-master --version
salt-master 2016.3.4 (Boron)

salt-minion --version
salt-minion 2016.3.4 (Boron)

running debian 8
