### ISSUE TITLE
dockerng.running + cpu_shares: 0,5 -> Invalid type: expected int but found <type 'float'>

### ISSUE THREAD

**Issue by p-thurner** [saltstack/salt#37622]
cpu_shares should accept a float but complains about not being an integer.

### Setup
```
docker_container_docker_example_running:
  dockerng.running:
    - name: BloonixSatellite_example
    - image: 'satellitesharing/bloonix-satellite'
    - detach: True
    - cpu_shares: 0.5
```

### Steps to Reproduce Issue
Running the state above results in:

```
          ID: docker_container_docker_example_running
    Function: dockerng.running
        Name: BloonixSatellite_example
      Result: False
     Comment: Failed to create new container: Invalid type for cpu_shares param: expected int but found <type 'float'>
     Started: 00:29:08.660383
    Duration: 23.167 ms
     Changes:   
```

### Versions Report
Debian 8 Master:
```
salt-master --version
salt-master 2016.3.4 (Boron)
```
Debian 8 Minion:
```
salt-minion --version
salt-minion 2016.3.4 (Boron)
```
