### ISSUE TITLE
2016.11.0rc2: Windows test.versions_report reporting wrong release number

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#37620]
### Description of Issue/Question
When attempting to run `test.versions_report` against a windows 2012 VM the release number is wrong and the dist is missing. 

### Setup
Windows 2012 minion

### Steps to Reproduce Issue

```
 ch3ll@thecakeisalie  /etc/salt  sudo salt 'win*' test.versions_report
win20122:
    Salt Version:
               Salt: 2016.11.0rc2
     
    Dependency Versions:
               cffi: 1.7.0
           cherrypy: 7.1.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.8
              ioflo: 1.5.5
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.4.1
                ZMQ: 4.1.5
     
    System Versions:
               dist:   
            machine: AMD64
            release: 8
             system: Windows
            version: 8 6.2.9200 SP0 Multiprocessor Free
```

As you can see its reporting `release: 8` and I would expect that to be 2012. And dist is blank.
