### ISSUE TITLE
git clone identity file SaltStack fileserver URL template

### ISSUE THREAD

**Issue by Dabuti** [saltstack/salt#37660]
### Description of Issue/Question
Hello,
I am trying to run a state with git.latest using a fileserver URL in the identity parameter e.g.: salt://files/id_rsa.

If that file uses jinja templating to get the value of the id_rsa key it does not work.

### Setup

files/id_rsa:
```
{% salt['pillar.get']('keys.my_id_rsa') %}
```

pillars/keys.sls:
```
keys.my_id_rsa:
  value: |
     -----BEGIN RSA PRIVATE KEY-----
     uq45cJAYszYix4CoznmFEkx3mtYh4E1rF...
     -----END RSA PRIVATE KEY-----
```
### Steps to Reproduce Issue
Try to clone a repository using identity a fileserver file that uses jinja templating.
### Versions Report
``` 
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 1.2.1
       cherrypy: Not Installed
       dateutil: 2.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.23.4
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.23.2
         Python: 2.7.10 (default, Nov  6 2015, 11:00:50)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.3
 
System Versions:
           dist:   
        machine: amd64
        release: 10.1-RELEASE-p24
         system: FreeBSD
        version: Not Installed
```
