### ISSUE TITLE
dns-search is not created during ubuntu vm creation

### ISSUE THREAD

**Issue by ralphsc** [saltstack/salt#37709]
### Description of Issue/Question
When creating an Ubuntu VM on Vmware, the "dns-search" is not added to the /etc/network/interfaces.

### Setup
Here is the profile:

```
lab_template:
   provider: vsphere
   clonefrom: lab_template
   host: esx03.lab01.com
   datacenter: DCA
   datastore: datastore
   power_on: True
   hostname: newvm001
   devices:
    network:
      Network adapter 1:
        name: lab-VLAN01
        adapter_type: e1000
        switch_type: standard
        ip: 192.168.0.5
        gateway: [192.168.0.1]
        subnet_mask: 255.255.255.0
        domain: lab01.com

   domain: lab01.com
   dns_servers:
       - 192.168.0.2
   dns_search:
       - lab01.com

   deploy: True
   ssh_username: user
   password: pass
   minion:
    master: 192.168.0.5
```

### Steps to Reproduce Issue
I don't see any errors, it's simply not created in /etc/networking/interfaces.
However I do see in the output and in the log after creation, "'dns_search': [‘lab01.com’], so it doesn't choke on it, just doesn't do anything.

### Versions Report

```
salt --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Ubuntu 14.04 trusty
```
