### ISSUE TITLE
rsync.synchronized returns a changes dictionary when no changes are done

### ISSUE THREAD

**Issue by p-thurner** [saltstack/salt#37714]
### Description of Issue/Question

The state `rsync.synchronized`:

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rsync.html

returns a non empty `changes` dictionary when it has nothing to do. It seems to me that the programmer of the state was about to give some additional information - if that information would be moved to the `comment` dictionary, everything would be ok. The state would then only show one line of output when executed with `--state-output=changes`.

### Setup
```
/srv/salt/test.sls:

saltstack_git_formulas_rsync-pillar.example_foo_bar:
  rsync.synchronized:
    - name: /srv/pillar/foo
    - source: /srv/git/formulas/bar/pillar.example/
    - prepare: True
    - delete: True
    - force: True
    - update: True
```

### Steps to Reproduce Issue

Run the state above several times. If there is nothing to do, salt still shows the following output even when executed with `--state-output=changes`:

```
ID: saltstack_git_formulas_rsync-pillar.example_foo_bar
    Function: rsync.synchronized
        Name: /srv/pillar/foo
      Result: True
     Comment: - sent 322 bytes
              - received 15 bytes
              - 674.00 bytes/sec
              - total size is 6,904
              - speedup is 20.49
     Started: 22:33:22.998636
    Duration: 50.042 ms
     Changes:   
              ----------
              copied:
                  N/A
              deleted:
                  N/A
```

### Versions Report
both master and minion salt-minion 2016.3.4 (Boron) on Debian 8.
