### ISSUE TITLE
Failed to import module dockerio due to 'urllib3' object has no attribute 'connection'.

### ISSUE THREAD

**Issue by mat-green** [saltstack/salt#37727]
### Description of Issue/Question
Failed to import module dockerio due to 'urllib3' object has no attribute 'connection'.
### Setup
Using https://github.com/saltstack-formulas/docker-formula to provision some docker images.

### Steps to Reproduce Issue
Executed and state.highstate and observed:
[ERROR   ] Failed to import module dockerio, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1299, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 181, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 6, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 11, in <module>
    from . import api
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 2, in <module>
    from .utils import (
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 19, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .ssladapter import ssladapter
  File "/usr/local/lib/python2.7/dist-packages/docker/ssladapter/__init__.py", line 1, in <module>
    from .ssladapter import SSLAdapter # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/docker/ssladapter/ssladapter.py", line 22, in <module>
    urllib3.connection.match_hostname = match_hostname
AttributeError: 'module' object has no attribute 'connection'

When I try and use the compose(-ng) of the formula it fails as dockerio is not installed. If I manually upgrade urllib3 to 1.14 it work okay.
### Versions Report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-96-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
That docker formula needs to be updated.

the `dockerio` module/state are deprecated and no longer supported since 2015.8.  I would highly recommend moving to using the `dockerng` module.

**Comment by terminalmage** [comment]
Both the unsupported ``dockerio`` and the newer ``dockerng`` modules use ``docker-py`` which imports as ``docker``. So switching to ``dockerng`` likely won't solve this.

Which version of docker-py do you have installed. You can get this information either by running ``pip freeze | grep docker-py==`` or ``python -c 'import docker; print(docker.__version__)'``. It might be that newer docker-py requires newer urllib3.

**Comment by terminalmage** [comment]
Also, what version of ``requests`` do you have. Digging into the docker-py source code, it uses a bundled distribution of urllib3 included with requests, but falls back to urllib3 if that bundled urllib3 is not present in requests.

This smells an awful lot like an upstream bug with docker-py.

**Comment by mat-green** [comment]
`pip freeze | grep docker-py` results in:
```
docker-py==1.10.6
docker-pycreds==0.2.1
```
`pip freeze | grep requests` results in:
```
requests==2.12.1
```

**Comment by terminalmage** [comment]
Thanks. When you run ``python -c 'import requests.packages.urllib3 as urllib3'``, does it output a traceback, or is there no output?

**Comment by terminalmage** [comment]
If there is a traceback, please post it.

**Comment by mat-green** [comment]
executing `python -c 'import requests.packages.urllib3 as urllib3'` produces no traceback.

**Comment by terminalmage** [comment]
OK, then something weird is going on with your python environment. As you can see if you view ``/usr/local/lib/python2.7/dist-packages/docker/ssladapter/ssladapter.py``, the only way that the system's version of urllib3 comes into play here is if the one bundled with requests is not able to be imported.

**Comment by terminalmage** [comment]
How are you installing Salt?

**Comment by mat-green** [comment]
My understanding is that Salt is installed via the bootstrap with `-D -F -c /tmp/` options. `docker-py` is being installed as part of the docker salt-formula vi pip.

**Comment by terminalmage** [comment]
OK, can you do one of the following?

1. Post the exact steps that you took so that I can attempt to construct an environment to reproduce.
2. If you have the means and know-how, post a Vagrantfile/Dockerfile which I can use to build a VM/container that can reproduce.

**Comment by vorobievalex** [comment]
Could it be caused by https://github.com/docker/docker-py/issues/1179 ?

**Comment by boltronics** [comment]
I just noticed this stack trace as well on a Ubuntu Trusty while provisioning using Vagrant.

```
[ERROR   ] Failed to import module dockercompose, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1411, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockercompose.py", line 114, in <module>
    from compose.cli.command import get_project
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 10, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/errors.py", line 11, in <module>
    from docker.errors import APIError
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 11, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 2, in <module>
    from .build import tar, exclude_paths
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/build.py", line 5, in <module>
    from .utils import create_archive
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 18, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 22, in <module>
    urllib3.connection.match_hostname = match_hostname
AttributeError: 'module' object has no attribute 'connection'
```

I believe I've stripped out the relevant sls data we use for provisioning:

```
python-all-dev:                                                                                                                                                                                                                                                                                                              
  pkg.installed: []

/usr/local/sbin/get-pip.py:
  file.managed:
    - source: salt://pip/files/get-pip.py
    - user: root
    - group: root
    - mode: '0755'
    - require:
      - pkg: python-all-dev
  cmd.run:
    - onchanges:
      - file: /usr/local/sbin/get-pip.py

Add docker repository:
  pkgrepo.managed:
    - humanname: Docker PPA
    - name: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    - dist: ubuntu-trusty
    - comps: main
    - file: /etc/apt/sources.list.d/docker.list
    - keyid: 58118E89F3A912897C070ADBF76221572C52609D
    - keyserver: hkp://p80.pool.sks-keyservers.net:80

Add docker helper packages:
  pkg.installed:
    - pkgs:
      - apparmor
      - ca-certificates

docker-engine:
  pkg.installed:
    - require:
      - pkgrepo: Add docker repository
      - pkg: Add docker helper packages

# https://docs.docker.com/compose/install/#install-compose                                                                                                                                                                                                                                                                   
docker-compose:
  pip.installed:
    - user: root
    - upgrade: True
    - require:
      - pkg: docker-engine
      - cmd: /usr/local/sbin/get-pip.py

```

```
vagrant@vagrant-base-trusty-amd64:~$ salt-call --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.12.0-2-amd64
         system: Linux
        version: Ubuntu 14.04 trusty
 
vagrant@vagrant-base-trusty-amd64:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
vagrant@vagrant-base-trusty-amd64:~$ 
```

Also:
```
root@vagrant-base-trusty-amd64:~# pip freeze
backports.ssl-match-hostname==3.5.0.1
cached-property==1.3.1
chardet==2.0.1
docker==2.5.1
docker-compose==1.16.1
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
enum34==1.1.6
functools32==3.2.3.post2
futures==3.0.3
ipaddress==1.0.18
Jinja2==2.7.2
jsonschema==2.6.0
M2Crypto==0.21.1
Mako==0.9.1
MarkupSafe==0.18
msgpack-python==0.4.6
MySQL-python==1.2.3
psutil==1.2.1
pycrypto==2.6.1
pycurl==7.19.3
python-apt===0.9.3.5ubuntu2
python-dateutil==1.5
python-debian===0.1.21-nmu2ubuntu2
PyYAML==3.12
pyzmq==14.0.1
requests==2.11.1
salt==2017.7.1
six==1.11.0
texttable==0.9.1
tornado==4.2.1
urllib3==1.7.1
websocket-client==0.44.0
root@vagrant-base-trusty-amd64:~# 

```

Unfortunately I just retried with this setup, and I was unable to reproduce! I've provisioned multiple times, but only saw the stack trace the one time.

Also note that I'm not using any of the dockercompose modules. I haven't checked, but I'm assuming Salt is reloading modules automatically after calling `pip.installed`.


https://github.com/docker/docker-py/issues/1054 suggests this is an issue with docker-compose sometimes requiring but not pulling in an updated `urllib3` package, and the version in trusty being too old. But it's strange it cannot always be reproduced.
