### ISSUE TITLE
Question: get user executing command

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#37836]
### Description of Issue/Question

Inside an execution module how would be possible to get the name of the user executing commands?

In the ```__opts__``` we have this:

```yaml
    sudo_user:
    syndic_finger:
    tcp_keepalive:
        True
    tcp_keepalive_cnt:
        -1
    tcp_keepalive_idle:
        300
    tcp_keepalive_intvl:
        -1
    tcp_pub_port:
        4510
    tcp_pull_port:
        4511
    test:
        False
    thorium_interval:
        0.5
    thorium_roots:
        ----------
        base:
            - /srv/thorium
    top_file:
    top_file_merging_strategy:
        merge
    transport:
        zeromq
    update_restart_services:
    update_url:
        False
    use_master_when_local:
        False
    user:
        root
    username:
        None
```

where ```user``` is root and ```sudo_user``` is not set at all, although the commands was executed by user ```mircea``` using ```sudo salt ...```.

Version:

```
$ sudo salt --versions-report
Salt Version:
           Salt: 2016.11.0rc1-76-ge08290e

Dependency Versions:
           cffi: 1.8.3
       cherrypy: 8.1.2
       dateutil: 2.2
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.4
```
