### ISSUE TITLE
Add yum exclude/failovermethod settings to pkrepo.managed

### ISSUE THREAD

**Issue by dkinon** [saltstack/salt#37846]
### Description of Issue/Question
According to the current documentation for [salt.states.pkgrepo](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkgrepo.html) there is no support for many less common yum repo settings, including (for my use case) **exclude** and **failovermethod**, in *pkgrepo.managed*.  Individual support for the named settings would be great.  It would probably be most useful across the board if there is a way, similar to the *comments* attribute, to provide an array of yum repo settings to *pkgrepo.managed*.

**Example State 1**:
```
 epel-repo:
  pkgrepo.managed:
    - name: epel
    - humanname: Extra Packages for Enterprise Linux $releasever - $basearch
    - mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-{{ grains['osmajorrelease'] }}&arch=$basearch
    - failovermethod: priority
    - exclude: nginx*,php*
    - gpgcheck: 1
    - gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ grains['osmajorrelease'] }}
    - disabled: 0
```

**Example State 2**:
```
 epel-repo:
  pkgrepo.managed:
    - name: epel
    - humanname: Extra Packages for Enterprise Linux $releasever - $basearch
    - mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-{{ grains['osmajorrelease'] }}&arch=$basearch
    - extra-settings:
      - failovermethod: priority
      - exclude: nginx*,php*
    - gpgcheck: 1
    - gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ grains['osmajorrelease'] }}
    - disabled: 0
```

### Setup
NA

### Steps to Reproduce Issue
NA

### Versions Report
NA
