### ISSUE TITLE
List not rendered correctly

### ISSUE THREAD

**Issue by peter-held** [saltstack/salt#37855]
### Description of Issue/Question
The attached state files are not rendered correctly.

/srv/base/states/apt-listchanges/map.jinja
```sls
{% set files_dir = 'salt://' + slspath + '/files' %}            # directory where file templates are stored
{% set formula_name = sls.split ('.')[0] %}                     # formula name (same as directory name)

{% set settings = salt.grains.filter_by ({
    'Ubuntu': {
        'pkgs':         [ formula_name ],
        'service':      formula_name,
        'conf_dir':     '/etc/' + formula_name,
        'conf_file':    formula_name + '.conf',

        'test_key':     salt.grains.filter_by ({
                            'trusty':   'test_value_trusty',
                            'xenial':   'test_value_xenial',
                            'default':  'test_value_default',
                        }, grain='oscodename'),
    },

    'Debian': {
    },
}, grain='os', merge=salt.pillar.get (formula_name)) %}
 ```

/srv/base/states/apt-listchanges/init.sls
```sls
include:
  - .pkg
 ```

/srv/base/states/apt-listchanges/pkg.sls
```sls
{% import sls.split('.')[0] + '/map.jinja' as this %}


{{ this.formula_name }}_pkg:
  pkg.latest:
    - pkgs: {{ this.settings.pkgs }}
    #- install_recommends: false
```

```python
local:
----------
          ID: apt-listchanges_pkg
    Function: pkg.latest
      Result: False
     Comment: No information found for 'u'apt-listchanges''.
     Started: 10:06:33.966789
    Duration: 5944.592 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   5.945 s
```

### Setup
NA

### Steps to Reproduce Issue
Use attached state files.

### Versions Report
```yaml    
    Salt Version:
               Salt: 2016.3.4
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist: Ubuntu 16.04 xenial
            machine: x86_64
            release: 4.4.0-47-generic
             system: Linux
            version: Ubuntu 16.04 xenial
```
