### ISSUE TITLE
Windows multiprocessing dilemma

### ISSUE THREAD

**Issue by rmarcinik** [saltstack/salt#37865]
# Description of Issue/Question
I think it may be a known issue of a memory leak #33890, but I wanted to provide more details for the Windows salt-minion

We turned off multiprocessing after noticing commands taking much longer and after seeing this issue #27866
Unfortunately the python process grows about 5MB after every highstate without multiprocessing on the salt-minion.  Turning multiprocessing on stops the python process from growing but running commands takes much much longer

### multiprocessing: False

I used procexp.exe to look into the python process.  After running a test highstate there were leftover threads with a Start Address of `MSVCR90.dll!endthreadex+0x64`

Diving into one of these threads showed this stack:
```
ntoskrnl.exe!KeSynchronizeExecution+0x2246
ntoskrnl.exe!ExAcquireCacheAwarePushLockExclusive+0x51a
ntoskrnl.exe!KeSynchronizeExecution+0x5f12
ntoskrnl.exe!PoStartNextPowerIrp+0x1356
ntoskrnl.exe!KeWaitForMultipleObjects+0x152f
ntoskrnl.exe!KeWaitForMultipleObjects+0xdd9
ntoskrnl.exe!KeWaitForMutexObject+0x373
ntoskrnl.exe!NtWaitForSingleObject+0xb2
ntoskrnl.exe!setjmpex+0x34a3
ntdll.dll!ZwWaitForSingleObject+0xa
MSWSOCK.dll!Tcpip6_WSHGetSockaddrType+0xb0b
MSWSOCK.dll!Tcpip6_WSHAddressToString+0x265
WS2_32.dll!select+0x1b3
libzmq.pyd!initlibzmq+0x21898
libzmq.pyd!initlibzmq+0x33aed
MSVCR90.dll!endthreadex+0x47
MSVCR90.dll!endthreadex+0xe8
KERNEL32.DLL!BaseThreadInitThunk+0x22
ntdll.dll!RtlUserThreadStart+0x34
```
These threads would get created when salt ran, but not all of them would get removed after salt finished, and the list would grow by 1-2 each time.  The highest observed memory usage of the python process was almost 650MB.

### multiprocessing: True
With multiprocessing turned on the memory stays constant at 40-50MB, but running interactive commands shows a significant increase in exeuction time (#31029).  The performance hit is not a big deal for most use cases, because the highstates run automatically on a schedule and no user is going to be left waiting.  

multiprocessing                    | True      | False 
-----------------------------------|-----------|----------
state.apply test=true              | 0m41.988s | 0m11.953s 
status.saltmem human_readable=true | 0m24.715s | 0m1.043s  

# Setup
`multiprocessing: True/False` in the salt-minion config
`status.saltmem human_readable=true` to check memory usage
highstate:
```
salt-minion-config:
  file.recurse:
    - name: C:/salt/conf/minion.d
    - source: salt://salt-minion-config/minion.d
    - defaults: 
        multiprocessing: False
    - template: jinja

salt-minion:
  service.running:
    - watch: 
      - file: salt-minion-config
```

# Steps to Reproduce Issue
Set `multiprocessing: False` on a Windows salt-minion, monitor memory usage after each highstate.
Repeat with `multiprocessing: True`

# Versions Report
```
    Salt Version:
               Salt: 2016.3.0

    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.3.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.2
              ioflo: 1.5.3
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: 0.7.2.None
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.3
                ZMQ: 4.1.2

    System Versions:
               dist:
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
