### ISSUE TITLE
cmd.run fails when not running as Admin on Windows 7

### ISSUE THREAD

**Issue by CapBananoid** [saltstack/salt#37881]
### Description of Issue/Question
Using cmd.run on Windows 7 fails with "The current directory is invalid." when a non admin user is used in runas.
Probably due to the user not having read access to salt install directory
Note that using cwd doesn't work

### Setup
Create a test user and launch the following state
```
test.vbs:
  cmd.run:
    - name: cscript.exe C:/tmp/test.vbs
    - runas: test
    - password: test

```
with test.vbs
`Wscript.echo "coin"`

### Steps to Reproduce Issue
```
sudo salt '*' state.apply test
worker_7:
----------
          ID: test.vbs
    Function: cmd.run
        Name: cscript.exe C:/tmp/test.vbs
      Result: False
     Comment: Command "cscript.exe C:/tmp/test.vbs" run
     Started: 11:00:44.736000
    Duration: 23.0 ms
     Changes:
              ----------
              pid:
                  5160
              retcode:
                  1
              stderr:
                  The current directory is invalid.
              stdout:

Summary for worker_7
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  23.000 ms
ERROR: Minions returned with non-zero exit code

```
### Versions Report
```
[vagrant@saltmaster ~]$ salt --versions-report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

```

On minion
```
C:\salt>salt-call.bat --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```

**Comment by CapBananoid** [comment]
Workaround:
```
test.vbs:
  cmd.run:
    - name: cd C:/ && cscript.exe C:/tmp/test.vbs
    - runas: test
    - password: test

```
