### ISSUE TITLE
saltstack masterless windows win_pkg

### ISSUE THREAD

**Issue by gudipudipradeep** [saltstack/salt#37900]
I am getting following issue while installing software in window  saltstack masterless mode. Please help me any thing wrong with my configuration.
```
C:\salt>salt-call --local state.highstate
local:
    Data failed to compile:
----------
    State 'firefox' in SLS 'firefox' is not formed as a list
```

# firefox.sls file
```
firefox:
  '39.0':
    full_name: 'Mozilla Firefox 39.0 (x86 en-US)'
    installer: 'https://download-installer.cdn.mozilla.net/pub/firefox/releases/39.0/win32/en-US/Firefox%20Setup%2039.0.exe'
    install_flags: '/s'
    uninstaller: '%ProgramFiles%\Mozilla Firefox\uninstall\helper.exe'
    uninstall_flags: '/S'
    msiexec: False
    locale: en_US
    reboot: False
```

# top.sls file
```
base:
  '*':
    - firefox
```
# minion config file
```
state_top: top.sls
file_client: local
base:
  - C:/salt/srv/salt
win_repo_cachefile: 'c:/salt/srv/salt/win/repo/winrepo.p'
winrepo_dir: c:\salt\file_roots\winrepo
```
