### ISSUE TITLE
file.managed: none of the specified sources were found

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#37937]
### Description of Issue/Question
Upgrading from 2016.3.x to 2016.11.0 causes issues with states that use `file.managed` (which we use a lot)

Running the highstate by hand shows the following error being output prior to any states:
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1744, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1702, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/file.py", line 1638, in managed
    **kwargs
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 4262, in check_managed_changes
    saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3554, in source_list
    'none of the specified sources were found'
CommandExecutionError: none of the specified sources were found
```

Then it sometimes shows this particular error for states. Running with `test=True` results in Salt claiming a lot of files will be changed to contain `False` but the actual run luckily(!) fails with an error and doesn't put `False` into the file (that would have been catastrophic):
```
          ID: /etc/sudoers
    Function: file.managed
      Result: False
     Comment: Source file salt://sudoers/files/sudoers not found
     Started: 08:52:56.082723
    Duration: 3.966 ms
     Changes:  
```

However, `cp.get_file` works just fine:
```
salt-call cp.get_file salt://sudoers/files/sudoers /tmp/sudoers

local:
    /tmp/sudoers
```

And produces the requested file in `/tmp/sudoers`

### States
For instance this one: https://github.com/saltstack-formulas/sudoers-formula/blob/master/sudoers/init.sls#L7

### Setup
Our file roots are configured as:
```
file_roots:
    base:
        - /data/salt/environments/prod/states
        - /data/salt/environments/prod/templates
        - /data/salt/environments/prod/files
        - /data/salt/environments/prod/formulas
```

Files exist and it has been working fine in the previous stable version, but started breaking right after updating to the newest version.

### Steps to Reproduce Issue
See above.

### Versions Report

```
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-100-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@syphernl i'm having a hard time replciate this even with the file_roots set as:

```
file_roots:
  base:
    - /data/salt/environments/prod/states
```

And the directory structure looks like the following:

```
[root@47f79b9dff2f testing]# ll /data/salt/environments/prod/states/*
-rw-r--r--. 1 root root 589 Nov 29 16:43 /data/salt/environments/prod/states/map.jinja
-rw-r--r--. 1 root root  86 Nov 29 16:41 /data/salt/environments/prod/states/test.sls
-rw-r--r--. 1 root root 465 Nov 29 16:44 /data/salt/environments/prod/states/test2.sls

/data/salt/environments/prod/states/sudoers:
total 0
drwxr-xr-x. 2 root root 21 Nov 29 16:45 files

/data/salt/environments/prod/states/test:
total 4
-rw-r--r--. 1 root root 5 Nov 29 16:42 test.txt
```

And when I run the state:

```
salt-call --local state.sls test2
local:
----------
          ID: sudo
    Function: pkg.installed
      Result: True
     Comment: Package sudo is already installed
     Started: 16:49:33.720038
    Duration: 260.933 ms
     Changes:   
----------
          ID: /etc/sudoers
    Function: file.managed
      Result: True
     Comment: File /etc/sudoers updated
     Started: 16:49:33.982828
    Duration: 23.926 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0440

Summary for local
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time: 284.859 ms
```

It works and i do not see the file not found error

Here is test2.sls:

```
{% from "map.jinja" import sudoers with context %}
sudo:
  pkg.installed:
    - name: {{ sudoers.pkg }}

{{ sudoers.get('config-path', '/etc') }}/sudoers:
  file.managed:
    - user: root
    - group: {{ sudoers.get('group', 'root') }}
    - mode: 440
    - template: jinja
    - source: salt://sudoers/files/sudoers
    - check_cmd: {{ sudoers.get('exec-prefix', '/usr/sbin') }}/visudo -c -f
    - context:
        included: False
    - require:
      - pkg: sudo
```

```
[root@47f79b9dff2f testing]# salt --version
salt 2016.11.0 (Carbon)
```

Any help to try to replicate this? Am I missing something from my test case?
