### ISSUE TITLE
Salt 2016.11.0 does not accept link-local IPv6 address in resolv.conf

### ISSUE THREAD

**Issue by Deewiant** [saltstack/salt#37949]
### Description of Issue/Question

Some servers of mine have link-local IPv6 addresses in `resolv.conf`, i.e. lines like `nameserver fe80::1234:5678:9abc:def0%eth0`. As of 2016.11.0 both master and minion log complaints like the following:

```
[ERROR   ] /etc/resolv.conf: 'fe80::21b:21ff:fe34:d66a%bond0' does not appear to be an IPv4 or IPv6 address
```

It doesn't seem to be breaking anything so far, though — just spamming logs. (Perhaps such nameserver addresses were never supported, but now it's more visible?)

### Setup
See description

### Steps to Reproduce Issue
See description

### Versions Report

```
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 8.1.2
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov  7 2016, 11:55:55)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: x86_64
        release: 4.8.6-1-ARCH
         system: Linux
        version: Not Installed
```
