### ISSUE TITLE
Archive.extracted fails if -user: root is specified

### ISSUE THREAD

**Issue by lordcirth** [saltstack/salt#37969]
### Description of Issue/Question

archive.extracted fails with the confusing error: "User root does not exist" if - user: root is specified.
The bug appears to have been introduced in https://github.com/saltstack/salt/commit/3014afd51700e336b74bd4a73f2f1f1b36f95e0b , in archive.py .  if the uid is 0, the state reports that user doesn't exist.

Looking at the code, the same problem will happen if the group 'root' is specified.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
The failing state:

```
nextcloud_extract:
  archive.extracted:
    - name: /var/www
    - source: https://download.nextcloud.com/server/releases/nextcloud-{{ pillar['nextcloud']['version'] }}.tar.bz2
    - source_hash: https://download.nextcloud.com/server/releases/nextcloud-{{ pillar['nextcloud']['version'] }}.tar.bz2.sha256
    # 755/644 therefore read only by default
    - user:   root
    - group:  www-data
    - if_missing: /var/www/nextcloud
    - archive_format: tar
    - require:
      - pkg: nextcloud_packages
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Create a archive.extracted state.   Specify "- user: root ".  state.apply. State run fails with "User root does not exist".  /etc/passwd is intact, su and sudo work, etc.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
salt --versions-report:

Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial

salt-minion --version:
salt-minion 2016.11.0 (Carbon)
```

Boron does not appear to have this problem, it appeared after I updated salt-minion from a mirror of repo.saltstack.com/ .
