### ISSUE TITLE
Salt-cloud ec2 vpc securitygroupid always returning default

### ISSUE THREAD

**Issue by tazaki** [saltstack/salt#37981]
### Description of Issue/Question

When creating vms into a vpc using ec2 in salt-cloud, the new vm will always have the default security group.

### Setup

/etc/salt/cloud.providers.d/provider.conf

```
aws_provider:
    id: XX
    key: 'XX'
    driver: ec2
    keyname: admin
    private_key: /etc/salt/admin.pem
    ssh_username: ubuntu
    ssh_interface: private_ips
```

/etc/salt/cloud.profiles.d/profiles.conf

```
generic:
  provider: aws_provider
  location: us-east-1
  size: m4.xlarge
  image: ami-xxxxx
  del_root_vol_on_destroy: True
  minion:
    master: 1.1.1.1
  securitygroupid:
    - sg-1111111
  subnetid: subnet-dd999999
```

### Steps to Reproduce Issue

`salt-cloud -p generic test1 -l trace`

This will always set to the 'default' security group. I added some prints to try and debug ec2.py. When salt-cloud queries for the group name it always gets back an empty set. 

This worked on the previous version of salt I was using: 2016.3.4. 

I also had to add the fix from here: https://github.com/saltstack/salt/issues/37966 to even get this far.

### Versions Report

Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-77-generic
         system: Linux
        version: Ubuntu 14.04 trusty
