### ISSUE TITLE
file.recurse tree redistributed every highstate

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#37992]
I've got a tree that I'm distrubuting via salt and it makes a highstate run very slow.

```
static-web:
  file.recurse:
    - name: /var/www/static/
    - source: salt://static_web/ # staat in /home/salt/files
#    - clean: true   # eens per zoveel tijd runnen want het scheelt een boel
    - group: www-data
    - dir_mode: 755
    - file_mode: 644
    - include_empty: true
```
when I up the log_level to profile:
```
2016-11-30 14:39:30,662 [salt.state       ][INFO    ][12520] Completed state [/var/www/static/] at time 14:39:30.662156 duration_in_ms=54343.841
```
When run over a slow line (4mbit) it is totally unacceptible, highstate times up to 1800 secs.

If I look at the logs it seems that all files are redistributed all the time. This seems to be a regression in 2016.3.4 (my current version), didn't happen before.
