### ISSUE TITLE
Error when trying to run orch command if another orch is running by scheduler.

### ISSUE THREAD

**Issue by gummeah** [saltstack/salt#37994]
### Description of Issue/Question
I have two orchestration state files. First one is running every 15 minutes by scheduler:
```
schedule:
  http_frontend_haproxy:
    function: state.orchestrate
    minutes: 15
    args:
      - orch.http_frontend.haproxy
```

/srv/salt/orch/http_frontend/haproxy.sls:
```
orch_haproxy_conf_generate:
  salt.state:
    - tgt: 'config_server'
    - sls: 
      - orch.http_frontend.haproxy_conf_generate
   
orch_haproxy_conf_update:
  salt.state:
    - tgt: 'role:http_frontend'
    - tgt_type: 'grain'
    - sls: 
      - orch.http_frontend.haproxy_conf_update
   ```

And second one I'm running manually with command:

> salt-run state.orch orch.http_frontend.bird

/srv/salt/orch/http_frontend/bird.sls:

```
refresh_pillar:
  salt.function:
   - name: saltutil.refresh_pillar
   - tgt: 'role:http_frontend'
   - tgt_type: 'grain'

update_bird_config:
  salt.state:
    - tgt: 'role:http_frontend'
    - tgt_type: 'grain'
    - sls: 
      - http_frontend.bird_config
```

If first orchestration is already running by scheduler and I'm trying to run second one with salt-run state.orch  - I'm getting error:
```
master:
    Data failed to compile:
----------
    The function "state.orchestrate" is running as PID 16907 and was started at 2016, Nov 30 18:18:56.071485 with jid 20161130181856071485
```
But everything is fine if I'm running both of them manually with commands:
```
salt-run state.orch orch.http_frontend.haproxy
salt-run state.orch orch.http_frontend.bird

```

What am I doing wrong?

### Versions Report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
