### ISSUE TITLE
[2016.11.0] dockerng.sls and map.jinja not mapping to correct os_family grain

### ISSUE THREAD

**Issue by alex-zel** [saltstack/salt#38017]
### Description of Issue/Question
When applying a state to a docker container with dockerng.sls, is said state is using a map.jinja with grains.filter_by to match os_family grain, the state will match to docker host os_family and not the container.

Using `salt['grains.get']('some_grain')` in sls files does work correctly and matches the grains of the container.

One workaround is to replace the docker host os_family grain to match to container one, but then I'll have to change osmajorrelease grain (and prehaps more grains, depending on map.jinja), as you can see this can get tedious and prone to mistakes (since you need to change it back to the original value for states to work on the host itself).

### Setup
Docker host: Ubuntu16.04
Containers: Ubuntu16/14, Centos7/6

map.jinja:
```
{% set base = salt['grains.filter_by'](
  {
    'Debian': {
        'salt_version': '2016.11.0+ds-1',
        'sudo_group': 'sudo',
        'ntp_service': 'ntp',
        'salt_repo': '/etc/apt/sources.list.d/saltstack.list',
        'repo': 'list',
        'sudo_package': salt['grains.filter_by']({
            '16': 'salt://base/sudo/sudo_1.8.18-2_ubuntu16_amd64.deb',
            '14': 'salt://base/sudo/sudo_1.8.18-2_ubuntu14_amd64.deb'
        }, grain='osmajorrelease'),
        'bashrc': '/etc/bash.bashrc',
        'fortune_pkg': 'fortune'
    },
    'RedHat': {
        'salt_version': '2016.11.0',
        'sudo_group': 'wheel',
        'ntp_service': 'ntpd',
        'salt_repo': '/etc/yum.repos.d/saltstack.repo',
        'repo': 'repo',
        'sudo_package': salt['grains.filter_by']({
            '7': 'salt://base/sudo/sudo_1.8.18-2_el7_x86_64.rpm',
            '6': 'salt://base/sudo/sudo_1.8.18-2_el6_x86_64.rpm'
        }, grain='osmajorrelease'),
        'bashrc': '/etc/bashrc',
        'fortune_pkg': 'fortune-mod'
    },
  }, grain='os_family')
%}
```
ntp.sls (one of many):
{% from 'base/map.jinja' import base with context %}

```
# Set timezone
ntp.timezone:
  pkg.installed:
    - name: 'dbus'
  timezone.system:
    - name: 'Asia/Jerusalem'
    - require:
      - pkg: ntp.timezone

# Configure ntp
ntp.config:
  pkg.installed:
    - name: 'ntp'
  service.running:
    - name: {{ base.ntp_service }}
    - enable: True
    - require:
      - pkg: ntp.config
    - watch:
      - file: ntp.config
  file.append:
    - name: '/etc/ntp.conf'
    - text: 'server X.X.X.X'
```

### Steps to Reproduce Issue
`salt DOCKERHOST dockerng.sls centos6_container mods=ntp`
Above command will run but will map the wring values from map.jinja

```
salt DOCKERHOST grains.set os_family RedHat
salt DOCKERHOST dockerng.sls centos6_container mods=ntp
```
Above command will run but again it'll fail in mapping values the depend on OS versions.
### Versions Report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 8.1.2
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.9.dev
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial
