### ISSUE TITLE
file.managed with template does not clean temp file

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt#38020]
### Description of Issue/Question
I've noticed that `/tmp` directory contains lot's of `tmp*` files that contains various jinja-rendered configuration files generated with `file.managed` state.

I do not know if this is regression or it actually worked like this forewer, but it would be nice for `file.managed` to cleanup. Every new state execution creates yet another temp file with same contents.

### Setup
Some minimal template:
```
foo
{{ value }}
bar
```
Some minimal state:
```
template_test:
    file.managed:
        - name: /tmp/templated_file
        - source: salt://{{ slspath }}/template.jinja
        - template: jinja
        - context:
            value: 1
```

After state execution `/tmp` directory contains rendered file:
```
# ls -la /tmp/tmp*
-rw------- 1 root root 9 Dec  1 15:18 /tmp/tmp38mera
# cat /tmp/tmp38mera 
foo
1
bar
```

### Versions Report

Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
