### ISSUE TITLE
debconf.set always changes setting

### ISSUE THREAD

**Issue by wichert** [saltstack/salt#3802]
I have a very simple config to enable unattended upgrades for Debian/Ubuntu machines:

``` yaml
security: 
  debconf.set: 
  - name: unattended-upgrades 
  - data: 
        'unattended-upgrades/enable_auto_updates': {'type': ' boolean', 'value':  True} 
  cmd.run: 
  - name: dpkg-reconfigure -fnoninteractive unattended-upgrades 
  - watch: 
    - debconf: unattended-upgrades 
  pkg.installed: 
  - name: unattended-upgrades 
```

When I run salt the state is applied correctly:

```
    State: - debconf
    Name:      unattended-upgrades
    Function:  set
        Result:    True
        Comment:   
        Changes:   unattended-upgrades/enable_auto_updates: True
```

However when I run highstate a second (or third, fourth, etc.) time it keeps changing the state every time. Checking the current setting manually shows it being set correctly:

```
root@services:~# debconf-get-selections | grep unattended-upgrades
unattended-upgrades unattended-upgrades/enable_auto_updates boolean True
```

Not having looked at the source I can think of two possible problems:
- the spelling of the boolean value is incorrect: debconf uses the lowercase `true` and `false` instead of `True` and `False`. Perhaps that is causing confusion.
- the state does not correctly test the current setting.

**Comment by MoonSweep** [comment]
I have a very similar problem, in the way that it's also with debconf.set tryng to set values for unattended-upgrades (and yes, I already checked for extra spaces, and the values are quoted).

Extract of the sls:
````
unattended-upgrades:
  debconf.set:
    - name: unattended-upgrades
    - data:
        {% if grains['oscodename'] == 'sid' %}
        'unattended-upgrades/enable_auto_updates': {'type': 'boolean', 'value': 'false' }
        {% else %}
        'unattended-upgrades/enable_auto_updates': {'type': 'boolean', 'value': 'true' }
        {% endif %}
````

On the master (minion is a sid):
````
root@master:/srv/salt# salt minion.domain debconf.show unattended-upgrades
minion.domain:
    |_
      - unattended-upgrades/enable_auto_updates
      - boolean
      - true
````

Now, if I run the sls:
````
root@master:/srv/salt# salt minion.domain state.sls recipes.debian-basic test=True
minion.domain:
[...]
----------
          ID: unattended-upgrades
    Function: debconf.set
      Result: True
     Comment: All specified answers are already set
     Started: 01:01:55.802277
    Duration: 269.003 ms
     Changes:   
````

After manually reconfiguring the package on the minion:
````
root@master:/srv/salt# salt minion.domain debconf.show unattended-upgrades
minion.domain:
    |_
      - unattended-upgrades/enable_auto_updates
      - boolean
      - false
````
````
root@master:/srv/salt# salt minion.domain state.sls recipes.debian-basic test=True
minion.domain:
[...]
----------
          ID: unattended-upgrades
    Function: debconf.set
      Result: None
     Comment: Unchanged answers: unattended-upgrades/origins_pattern
     Started: 01:10:38.241019
    Duration: 264.096 ms
     Changes:   
              ----------
              unattended-upgrades/enable_auto_updates:
                  New value: true
````
At first I thought that the test "oscodename == sid" may be misinterpreted, but it's not:

````
root@minion:~# salt-call -l debug state.sls recipes.debian-basic test=True
[...]
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/recipes/debian-basic.sls:
[...]
unattended-upgrades:
  debconf.set:
    - name: unattended-upgrades
    - data:
        
        'unattended-upgrades/enable_auto_updates': {'type': 'boolean', 'value': 'false' }
````

I can't see what's wrong, it's driving me crazy.
