### ISSUE TITLE
x509.crl_managed uses md5 while other function uses sha256

### ISSUE THREAD

**Issue by haraldrudell** [saltstack/salt#38029]
### Description of Issue/Question
The certificate revocation list is signed using md5. This is not safe, it should be sha256

### Setup
generate a certificate revocation list using

```
id:
  x509.crl_managed:
    - name: filename
    - signing_private_key: filename
    - signing_cert: filename
    - revoked:
      - commonName:
        - serial_number: 40:e6:ec:ad:e3:88:fb:d5
        - revocation_date: '2016-01-01 00:00:00'
        - reason: superseded
    - days_valid: 3650
    - days_remaining: 0
```

### Steps to Reproduce Issue
check the resulting output:
```openssl crl -noout -text -in file_crl.pem | less```
…
Signature Algorithm: md5WithRSAEncryption

should be:
sha256WithRSAEncryption

### Versions Report

```
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: i686
        release: 4.4.0-43-generic
         system: Ubuntu 16.04 xenial
```
