### ISSUE TITLE
Salt fails to fetch from a git remote in VSTS

### ISSUE THREAD

**Issue by mmisztal1980** [saltstack/salt#38066]
### Description of Issue/Question
Salt fails to fetch from a git remote using ssh auth. The following logentries appear:
Interestingly It's possible to ```git clone``` manually using ssh auth. ```ssh -T``` also works.

```
[DEBUG   ] Set update lock for gitfs remote 'ssh://{path-to-repo-in-vsts}'
[DEBUG   ] Fetching gitfs remote 'ssh://ssh://{path-to-repo-in-vsts}'
[ERROR   ] Error occured fetching gitfs remote 'ssh://ssh://{path-to-repo-in-vsts}': Failed to start SSH session: Unable to exchange encryption keys
[DEBUG   ] Removed update lock for gitfs remote 'ssh://ssh://{path-to-repo-in-vsts}'
```
### Setup
- In general, follow this [video](https://www.youtube.com/watch?v=RaeKLKaqPoo)
- Install a vanilla salt-master and salt-minion on Ubuntu 16.04
- Create a VSTS (visualstudio.com) git repository
- Create a SSH keypair and [upload the public key to VSTS](https://www.visualstudio.com/en-us/docs/git/use-ssh-keys-to-authenticate) 
- Copy the keypair to /etc/salt/master.d
- Apply the following settings to ```/etc/salt/master```

```
fileserver_backend:
  - git

gitfs_remotes:
  - ssh://{Your Repo}
gitfs-pubkey: /etc/salt/master.d/{pubkey}
gitfs_privkey: /etc/salt/master.d/{privkey}
gitfs_base: master
gitffs_env_whitelist:
  - base

pillar_roots:
  base:
    - /srv/pillar
file_roots:
  base:
    - /srv/salt

```

### Steps to Reproduce Issue
Start the salt-master as a process with ```--log-level=debug```

### Versions Report
```
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.6
         PyYAML: 3.12
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: 2.0.0
      gitpython: 2.1.0
          ioflo: Not Installed
        libgit2: 0.24.0
        libnacl: 1.5.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.0
   python-gnupg: Not Installed
          smmap: 2.0.1
        timelib: Not Installed

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Ubuntu 16.04 xenial
```
