### ISSUE TITLE
Broken configuration files due to Augeas change

### ISSUE THREAD

**Issue by pkruithof** [saltstack/salt#38078]
In PR #34643, a change was made to support quotes in arguments. However this change results in every augeas value being inserted with quotes.

The previous state works in 2016.3.4, but not in 2016.11.0:

```yaml
sshd_config:
  augeas.change:
    - lens: sshd.lns
    - context: /files/etc/ssh/sshd_config
    - changes:
      - set PasswordAuthentication 'no'
```

The problem is that the configuration file ends up with `PasswordAuthentication 'no'` instead of `PasswordAuthentication no`, which breaks SSH logins in this case due to the configuration file being invalid.
