### ISSUE TITLE
Problem with win_lgpo.py in salt 2016.11.0

### ISSUE THREAD

**Issue by skjaro** [saltstack/salt#38100]
### Description of Issue/Question
Hello,

I have problem with module win_lgpo.py introduced in version 2016.11.0.
I test it with simple politics with login script, but ended with error.
I debbug it - problem is with parsing admx template in PolicyDefinitions in Windows dir.
I have politic which statring with line:
`<?xml version='1.0' encoding='unicode' standalone='yes'?>`

and problem is endcoding='unicode' where:
`xmltree = lxml.etree.parse(admfile, parser=parser) `
fail with:
`XMLSyntaxError: Unsupported encoding unicode, line 1, column 37`

### Setup
```
login_lgpo:
  lgpo.set:
    - name: Startup Scripts
    - setting:
      - C:/install/login.cmd
    - policy_class: User
```
### Versions Report

```
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```

**Comment by Ch3LL** [comment]
@skjaro i'm having a hard time replicating this. I am returing true. Would you mind sharing sanitized version of `C:/install/login.cmd` if that is causing the issue.

Also can you paste hte error your running into? thanks

**Comment by skjaro** [comment]
I have this problem with unicode policy file "c:\Windows\PolicyDefinitions\Search.admx". I can upload in somewhere. I try parse this file on linux machine with lxml library and there is no problem with it. When I try parse file with python distributed with salt 2016.11.0 then I have trouble with it.
```
import lxml
import lxml.etree

parser = lxml.etree.XMLParser(remove_comments=True)
xmltree = lxml.etree.parse('Search.admx', parser=parser)
```
On windows machine with salt it gives error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src\lxml\lxml.etree.c:79801)
  File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src\lxml\lxml.etree.c:115995)
  File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src\lxml\lxml.etree.c:116345)
  File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src\lxml\lxml.etree.c:115233)
  File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFrom
File (src\lxml\lxml.etree.c:109930)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:103404)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:105058)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:103967)
lxml.etree.XMLSyntaxError: Unsupported encoding unicode, line 1, column 37
```

**Comment by skjaro** [comment]
Link for a policy file: [https://file.io/ZkbFO5](url)

**Comment by skjaro** [comment]
I tested this file with windows python 2.7.12 and pip installed lxml and this gives same error. Maybe report this issue in [lxml bugs page](https://bugs.launchpad.net/lxml)

**Comment by skjaro** [comment]
Hi Megan,

I want to ask regarding to issue what I submited on github.
I tested this issue on linux box as I write on issue #38100. Problem is
with parsing
file with politics in Windows\PolicyDefinitions which is processed when
politics appy
or is get by module. I tested problematic file which I upload on server and
added link in
comment to issue. With this file is no problem linux machine when I parse
it with
lxml library. Problem is only on windows machines.
I have to report this on lxml mailing list or what is next step.

 ~ salt 'TTXX*' lgpo.get return_full_policy_names=True
TTXXYY:
    The minion function caused an exception: Traceback (most recent call
last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1412, in
_thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py",
line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line
3974, in get
        admxPolicyDefinitions, admlPolicyResources =
_processPolicyDefinitions(display_language=adml_language)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line
2056, in _processPolicyDefinitions
        xmltree = lxml.etree.parse(admfile, parser=parser)
      File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse
(src\lxml\lxml.etree.c:79801)
      File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument
(src\lxml\lxml.etree.c:115995)
      File "src/lxml/parser.pxi", line 1808, in
lxml.etree._parseDocumentFromURL (src\lxml\lxml.etree.c:116345)
      File "src/lxml/parser.pxi", line 1712, in
lxml.etree._parseDocFromFile (src\lxml\lxml.etree.c:115233)
      File "src/lxml/parser.pxi", line 1115, in
lxml.etree._BaseParser._parseDocFromFile (src\lxml\lxml.etree.c:109930)
      File "src/lxml/parser.pxi", line 573, in
lxml.etree._ParserContext._handleParseResultDoc
(src\lxml\lxml.etree.c:103404)
      File "src/lxml/parser.pxi", line 683, in
lxml.etree._handleParseResult (src\lxml\lxml.etree.c:105058)
      File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError
(src\lxml\lxml.etree.c:103967)
    XMLSyntaxError: Unsupported encoding unicode, line 1, column 37


Thanks.

2016-12-07 17:34 GMT+01:00 Megan Wilhite <notifications@github.com>:

**Comment by skjaro** [comment]
Ok, I submmited it to lxml bug system [here](https://bugs.launchpad.net/lxml/+bug/1651149).

**Comment by Ch3LL** [comment]
@skjaro if you are receiving the same error outside of salt I would assume that would mean its not an issue with salt, but sometimes we have to workaround upstream bugs within salt. Let me get some others input on this.

ping @twangboy do you see a way we can work around this Unicode error?

**Comment by skjaro** [comment]
@twangboy I think there is way in lxml to force encoding to utf16 when we got some error, maybe this is the way. If we catch error then try force encoding - but I don't know if this is right way.

**Comment by skjaro** [comment]
@Ch3LL I look at lxml and didn't find simple way to parse this file on windows maybe if we catch error simply ignore this file and continue parsing another one with windows admx policies.
I have another issues with win_lgpo module which crashed when I ignore this file. 
I have fix for it, but maybe this is for author of module. 
If I have questions about using this module who can I contact?

**Comment by twangboy** [comment]
@skjaro I believe @lomeroe is the original author.

**Comment by arthur-kiwi** [comment]
@lomeroe @skjaro I get the same error message when testing a simple state with salt-master on 2016.11.1 and minion on 2016.11.1. Here is my state:

```
DisableOneDrive:
    lgpo.set:
      - name: Prevent the usage of OneDrive for file storage
      - setting: Enabled
      - policy_class: Machine
      - adml_language: en-US
```
The error message is: "XMLSyntaxError: Unsupported encoding unicode, line 1, column 37" and I've taken a look into the Windows\PolicyDefinitions\Skydrive.admx where this policy exists and the file starts with 
```
<?xml version="1.0" encoding="utf-8"?>
```
I have a German version of windows 8.1 and windows 10 installed and the error is the same on both.

**Comment by lomeroe** [comment]
@arthur-kiwi  I expect you have another XML, unrelated to the policy you are attempting to set, with the encoding="unicode" attribute.  The module attempts to load all the ADMX files in the PolicyDefinitions folder in order to find the policy you are requesting to manage, so an issue in any of those files could cause an error (admittedly an oversight -- a better option may be to ignore that particular ADMX and move on).

Try running the following powershell snippet, and see if it returns any files.
```
get-childitem -path "c:\windows\policydefinitions" -recurse | select-string 'encoding="unicode"'
```

**Comment by arthur-kiwi** [comment]
@lomeroe It is the same file skjaro has an issue with, "C:\Windows\policydefinitions\search.admx" that contains the " encoding='unicode' " string.

**Comment by lomeroe** [comment]
@arthur-kiwi ok, my bad, I didn't make the connection that it was the same file.  Are you using Windows 7 too?  I also unfortunately only tested with Server 2008 and 2012 (which doesn't seem to have search.admx)...

**Comment by arthur-kiwi** [comment]
@lomeroe I have tested on both Windows 8.1 and Windows 10 and they have the search.admx. Don't have any windows 7 machines to test on. I didn't realize it was the same file as skjaro had issues with until I ran the ps command you suggested.

**Comment by lomeroe** [comment]
@arthur-kiwi @skjaro 

I played around and it seems removing the "encoding='unicode'" from the xml lets it parse okay (from my very basic tests)

Here's a version that will try to do that if an XMLSyntaxError is thrown when attempting to parse:

https://raw.githubusercontent.com/lomeroe/salt/win_lgpo_ignore_badxml_admx_files/salt/modules/win_lgpo.py

If it tests out okay, I can do a PR to merge the changes...

**Comment by arthur-kiwi** [comment]
@lomeroe The state now returns true but I cant see that the policy is set in gpedit.msc nor does the setting seem to apply. I still see the first sign-in animation when i log onto the machine with a new user account.

```
          ID: DisableFirstSignIn:
    Function: lgpo.set
        Name: Show first sign-in animation
      Result: True
     Comment: 
     Started: 12:25:51.869000
    Duration: 1401.0 ms
     Changes:   
----------
          ID: DisableOneDrive
    Function: lgpo.set
        Name: Prevent the usage of OneDrive for file storage
      Result: True
     Comment: 
     Started: 12:25:53.270000
    Duration: 1454.0 ms
     Changes:
```

**Comment by lomeroe** [comment]
@arthur-kiwi the "set" command doesn't run a gpupdate, so the data in the regpol file won't get written to the registry (for admin templates) until the next run (though it *should* show as configured by lgpo.get and gpedit.msc)

Here is how we do our states, we have a simple "gpupdate" state that looks like this:
```
run_gpupdate:
  cmd.run:
    - name: 'gpupdate /force'
```

Then on any policy that uses the lgpo state, we include that state and use an onchanges_in:
```
include:
  - .gpupdate

set_banner_policy:
  lgpo.set:
    - computer_policy:
        'Interactive logon: Message text for users attempting to log on': |-
            {{ banner_settings['text']|indent(12) }}
        'Interactive logon: Message title for users attempting to log on': |-
            {{ banner_settings['header']|indent(12) }}
    - onchanges_in:
      - cmd: run_gpupdate
```

Since I was patterning lgpo after gpedit.msc, I didn't make the module run the gpupdate automatically, as I don't believe gpedit.msc performs a gpupdate on exit...

I see your update that lgpo.get shows the policy configured, but can you confirm whether gpedit.msc shows the policies you have set as Enabled (or with the proper setting)?  I want to make sure that works too.  If it did, then it is looking like there is an issue with setting a single policy (I almost exclusively use the computer_policy/user_policy dict method, as it is more efficient [due to the way the module is written], so all of my tests use that method of applying the policy.  A quick glance at the state code seems good, but if it is not working, I'll dig in further.

Thanks for your help in making the module better...

**Comment by lomeroe** [comment]
I found the issue on the single policy (case sensitive comparison of the policy_class parameter).  Issue #38689 and PR #38690  submitted to resolve that.

**Comment by arthur-kiwi** [comment]
@lomeroe After a reboot of my test machine I can see the changes in gpedit.msc and most of my policies are set, but unfortunately it seems the module is unable to set some of the policies because it returns an error that it can't find them. Do you want me to open a new issue for this? And also thanks for the help so far.

```
          ID: W10 Client Computer Policy
    Function: lgpo.set
      Result: False
     Comment: Unable to find Machine policy Show first sign-in animation Unable to find Machine policy Don't search the web or display web results in Search
     Started: 12:40:57.193000
    Duration: 16438.0 ms
     Changes:
```
