### ISSUE TITLE
Question, is thorium ready for masterless minions?

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#38110]
### Description of Issue/Question
I have tried to test thorium on a masterless minion but it fails...

is it maybe because of:
https://github.com/saltstack/salt/blob/develop/salt/thorium/__init__.py#L61

### Setup
salt-minion is running in daemon mode with the following config:
```
master: "salt"
master_type: "disable"
failhard: true
file_client: local
file_roots:
  base:
    - {redacted....}
fileserver_backend:
  - roots
gitfs_provider: "pygit2"
pillar_roots:
  base:
    - /srv/pillar
    - /srv/spm/pillar
ext_pillar:
  - stack: /srv/pillar/stack/stack.cfg
pillar_opts: false
pillar_merge_lists: true
state_verbose: false
state_output: "changes"
state_output_diff: true
log_level: "critical"
```
engines.conf:
```
engines:
  - thorium: {}
```

thorium top.sls
```
base:
  '*':
    - thorium_test
```

thorium_test.sls
```
checker:
  check.event:
    - value: trigger
    - name: salt/thorium/*/test

shell_test:
  local.cmd:
    - tgt: '*'
    - func: cmd.run
    - arg:
      - echo 'thorium success' > /tmp/thorium.txt
    - require:
      - check: checker 
```

### Steps to Reproduce Issue
```
salt-call event.send 'salt/thorium/test/test' '{checker: trigger}'
```
output:
```
local:
    True
```

But no file was created!!!!

debug information:
```
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_e4b6799b8a_pull.ipc
[DEBUG   ] Sending event: tag = salt/thorium/test/test; data = {'_stamp': '2016-12-06T20:44:42.296066', '__pub_pid': 13945, 'checker': 'trigger', '__pub_fun': 'event.send', '__pub_jid': '20161206214442291851', '__pub_tgt': 'salt-call'}
```
### Versions Report
```
Salt Version:
           Salt: 2016.11.0-461-g723699f
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 8.1.2
       dateutil: 2.6.0
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: 1.6.6
         Jinja2: 2.8
        libgit2: 0.24.2
        libnacl: 1.5.0
       M2Crypto: 0.24.0
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.12 (default, Nov  7 2016, 11:55:55)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.8.11-1-ARCH
         system: Linux
        version: Not Installed
```
