### ISSUE TITLE
minions losing connection, not reconnecting without restart of service

### ISSUE THREAD

**Issue by harmv** [saltstack/salt#38157]
### Description of Issue/Question
We have minions that are connected over 3G. Thus the connection is often offline.
The minions are connected over openvpn.

What we found if that whenever openvpn restarts the tunnel, and we get a new `tun0`  ip address, then the salt-minion  _never_ detects that this happened, and the salt-minion will never reconnect to the master.  Only a `systemctl restart salt-minion` recovers this.

### Setup
~100 minions connected over an openvpn tunnel over 3G.

### Steps to Reproduce Issue
1. Have a working minion connection.
2. We then issue a `systemctl restart openvpn@client`   this causes the `tun0` ip address to change on the minion.
3. then the minion does not contact the master anymore,  only a `systemctl restart salt-minion` helps.

This seems similar to #6231 en  #15442

When looking into the `tcp_keepalive_*` options, that looked just like the thing I needed to fix this problem. (as mentioned in #6231)
Unfortunately the `tcp_keepalive` feature  does _not_ seem to be working, not at all.
I added the following to `/etc/salt/minion`
```
tcp_keepalive: 1
tcp_keepalive_idle: 10
tcp_keepalive_cnt: 2
tcp_keepalive_intvl: 10
```
I sniffed the network traffic using tcpdump, and _no_  keepalive messages are ever sent.

I straced  the salt-minion, and no `setsockopt(... SO_KEEPALIVE,)` calls are _ever_ done to the OS. When adding some prints, I do see salt calling `self.socket.setsockopt(zmq.TCP_KEEPALIVE...)` in s`alt/transport/zeromq.py` ... but those tcp_keepalive options _never_ land in the OS sockets. It seems they are somewhere swallowed in zmq.

### Versions Report
```
salt-minion --versions-report

Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun  4 2016, 23:51:38)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 3.2.4
 
System Versions:
           dist:   
        machine: armv7l
        release: 3.1.10-T30A1102v2.3.1
         system: Linux
        version: Not Installed
```
