### ISSUE TITLE
Performance problem in ini_manage module

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [saltstack/salt#38152]
Try to edit default php.ini in CentOS 7 and see strange delay in test mode - 37 seconds with **99% CPU consumption** by salt-minion. In real work mode job finishes fast enough - just 7 seconds. But, as for me, 7 seconds is too much too. Tried to remove all empty lines and comments (1626 lines were deleted) - result became 176.434 ms in test mode. Is there any possibility to improve `ini_manage` module performance ?
I use the latest version - 2016.11.0 (both master and minion).

P.S. In previous release (2016.3.4) test mode lasted 158 seconds, it was awesome.

php-ini.sls:
```yaml
php-ini:
  ini.options_present:
    - name: /etc/php.ini
    - sections:
        PHP:
          short_open_tag:                      On
          expose_php:                          Off
          max_execution_time:                  30
          memory_limit:                        700M
          error_reporting:                     E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
          display_errors:                      Off
          log_errors:                          On
          post_max_size:                       8M
          cgi.fix_pathinfo:                    0
          fastcgi.logging:                     1
          upload_max_filesize:                 2M
          allow_url_fopen:                     On
          allow_url_include:                   Off
        Date:
          date.timezone:                       Europe/Kiev
        mail function:
          mail.add_x_header:                   Off
        Session:
          session.use_strict_mode:             1
          session.gc_probability:              1
          session.gc_divisor:                  100
        opcache:
          opcache.enable:                      0
          opcache.enable_cli:                  0
```

Test mode command:
```
# time salt --state-verbose=true --state-output=full 'minion' state.sls php-ini test=true
minion:
----------
          ID: php-ini
    Function: ini.options_present
        Name: /etc/php.ini
      Result: None
     Comment: Key short_open_tag in section PHP unchanged.
              Key expose_php in section PHP unchanged.
              Key max_execution_time in section PHP unchanged.
              Key memory_limit in section PHP unchanged.
              Key error_reporting in section PHP unchanged.
              Key display_errors in section PHP unchanged.
              Key log_errors in section PHP unchanged.
              Key post_max_size in section PHP unchanged.
              Key cgi.fix_pathinfo in section PHP unchanged.
              Key fastcgi.logging in section PHP unchanged.
              Key upload_max_filesize in section PHP unchanged.
              Key allow_url_fopen in section PHP unchanged.
              Key allow_url_include in section PHP unchanged.
              Changed key date.timezone in section Date.
              Key mail.add_x_header in section mail function unchanged.
              Key session.use_strict_mode in section Session unchanged.
              Key session.gc_probability in section Session unchanged.
              Key session.gc_divisor in section Session unchanged.
              Key opcache.enable in section opcache unchanged.
              Key opcache.enable_cli in section opcache unchanged.
     Started: 13:41:24.908048
    Duration: 36837.488 ms
     Changes:   

Summary for minion
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:  36.837 s

real    0m40.082s
user    0m1.341s
sys     0m0.201s
```

Editing mode:
```
# time salt --state-verbose=true --state-output=full 'minion' state.sls php-ini
minion:
----------
          ID: php-ini
    Function: ini.options_present
        Name: /etc/php.ini
      Result: True
     Comment: Changes take effect
     Started: 13:51:26.311462
    Duration: 7648.754 ms
     Changes:   
              ----------
              Date:
                  ----------
                  date.timezone:
                      ----------
                      after:
                          Europe/Kiev
                      before:
                          None

Summary for minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   7.649 s

real    0m11.664s
user    0m0.922s
sys     0m0.150s
```

**Comment by Ch3LL** [comment]
@Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk I'm able to replicate this but am seeing a 12-13 second delay.but my test case is using salt-call localling on the minion. So we definitely need to improve the performance here. 

Here is a docker container for anyone that wants to replicate this:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:38152`
2. `time salt-call --local state.sls test test=True`

**Comment by aTastyCookie** [comment]
Meanwhile, the problem persists and causes pain :(

**Comment by Foorack** [comment]
Yes, updating a few variables in the `php.ini` file takes consistently 13 seconds, even when nothing has changed.

```# salt-call -V
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Nov 26 2021, 20:14:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.13.19-2-pve
        system: Linux
       version: Ubuntu 20.04 focal
```

**Comment by Foorack** [comment]
Reproducibility steps:

Install php7.4-cgi and make a copy of `cp /etc/php/7.4/cgi/php.ini /tmp/test-php.ini`.
Next run the following state:

```yaml
test ini.options_present speed:
  ini.options_present:
    - name: /tmp/test-php.ini
    - sections:
        PHP:
          max_execution_time: 999999999 # Orig 30
          max_input_time: 999999999 # Orig 60
          upload_max_filesize: 2G # Orig 2M
          post_max_size: 2G # Orig 8M
```

This produces the following output:
```
root@saltstack:~# salt sqlserver state.apply testini
sqlserver:
----------
          ID: test ini.options_present speed
    Function: ini.options_present
        Name: /tmp/test-php.ini
      Result: True
     Comment: No anomaly detected
     Started: 13:11:53.567670
    Duration: 13385.766 ms
     Changes:

Summary for sqlserver
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  13.386 s
root@saltstack:~#
```

As is visible from this simple test, modifying **a single ini** file takes more than **13 seconds**, and this timing is very consistent through multiple runs.

The file has 1943 lines, but 1808 of them are comments or empty lines.
Removing all comments and empty lines reduces it to **13 milliseconds**.
