### ISSUE TITLE
file.line mode=ensure state issues

### ISSUE THREAD

**Issue by haeac** [saltstack/salt#38171]
### Description of Issue/Question
Hello,

The file.line with mode=ensure doesn't seem to be working as it should. I'm trying to ensure that a line is present in a file after another line. However, the regex for after or before don't seem to be working and also using location=end doesn't work as documented.

Thanks in advance.

### Setup
Configuration file:
```
key1=value1
key2=value2
.
key4=value4,key=value, paramx
.
key=value    # This is the line after which I want my new line added
.
.
.
keyn=valuen

```

### Steps to Reproduce Issue
Running the following on the master:

```bash
salt 'minion' file.line /path/to/configfile mode="ensure" content="mykey=myval" after="^key=value$"
```
Gives the following result:

```
ERROR: Found less than expected occurrences in "after" expression
```
On removing the end of line character ```$```, I can get matches but salt complains about having more than expected number of matches. I can work around the ```$``` by using ```key=value(\n|\r|\\r\n)``` but it will still match lines which don't start with key. 

Also, as per the documentation, location takes precedence over before and after. So, if I use the following:

```bash
salt 'minion' file.line /path/to/configfile mode="ensure" content="mykey=myval" location="end"
```
I get the following error:

```
ERROR: Wrong conditions? Unable to ensure line without knowing where to put it before and/or after.
```
I can't use file.manged because files like the grub menu usually get updated when new kernels are installed. 

### Versions Report
Master version report:

```yaml
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.3.8
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: 0.6.3
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

Minion version report:

```yaml
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.6.2.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```
