### ISSUE TITLE
state.rsync isn't working 

### ISSUE THREAD

**Issue by sqrteh** [saltstack/salt#38176]
### Description of Issue/Question
I have created some simply state for synchronise directory between salt-master and salt-minion, but it is not working properly. 

I made it by use this doc: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rsync.html

How to fix this problem ? When i use shell command like this:

> rsync -r backups/ f1:/opt/backups/

It works well , but by state.sls it isn't. 

### my test_rsync.sls
```
/opt/backups/:
   rsync.synchronized:
     - source: salt://packages/fx/configs/backups/
     - force: True
     - delete: True
     - prepare: True
```

### Output of usage state:

salt f1 state.sls test_rsync
```
f1:
----------
          ID: /opt/backups/
    Function: rsync.synchronized
      Result: False
     Comment: Host key verification failed.
              rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
              rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.0]
     Started: 01:26:00.619976
    Duration: 28.266 ms
     Changes:   

Summary for f1
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  28.266 ms
ERROR: Minions returned with non-zero exit code
```

### Versions Report
salt-master has version 2016.11.0+ds-1.
salt-minion has version 2016.11.0+ds-1

Thx for help.
