### ISSUE TITLE
create user fail when specified home is not exists

### ISSUE THREAD

**Issue by qianlnk** [saltstack/salt#38196]
### my sls
```
kafka:
  group.present:
    - name: kafka
    - system: True
  user.present:
    - name: kafka
    - fullname: kafka service
    - shell: /usr/sbin/nologin
    - home: /data/kafka/data
    - system: True
    - gid_from_name: True
    - groups:
      - kafka
```
### Resault
----------
          ID: kafka
    Function: group.present
      Result: True
     Comment: Group kafka is present and up to date
     Started: 02:35:24.107914
    Duration: 2.349 ms
     Changes:   
----------
          ID: kafka
    Function: user.present
      Result: False
     Comment: Failed to create new user kafka
     Started: 02:35:24.110669
    Duration: 26.607 ms
     Changes:
