### ISSUE TITLE
Wrong and incomplete query result for Azure VMs

### ISSUE THREAD

**Issue by sidx** [saltstack/salt#38227]
### When running -Q on master and querying the minions, the information returned is wrong and incomplete(information verified from azure portal).

###Provider:

```
my-azure-config:
  driver: azure
  subscription_id: <my id>
  certificate_path: /etc/salt/saltkey.pem
  minion:
    master: <my_ip>
###Profile:
stdA1VM1:
  provider: my-azure-config
  image: 'minionimage'
  size: Small
  location: 'East US'
  ssh_username: azureuser
  ssh_password: badpass
  slot: production
  media_link: 'https://portal.blob.core.windows.net/vhds/'
```

### Steps to Reproduce Issue
Minion Provisioned as : `salt-cloud --map=/etc/salt/cloud.conf.d/maps.conf --parallel -y`
Queried as : `salt-cloud --map=/etc/salt/cloud.conf.d/maps.conf --query`
`my-azure-config:
    ----------
    azure:
        ----------
        stdA1VM1:
            ----------
            id:
                stdA1VM1
            image:
                minionimage
            name:
                stdA1VM1
            private_ips:
            public_ips:
                - <returned private ip here>
            size:
                Small
            state:
                running
        stdA1VM2:
            ----------
            id:
                stdA1VM2
            image:
                minionimage
            name:
                stdA1VM2
            private_ips:
                - <returned public ip here>
            public_ips:
            size:
                Small
            state:
                running`

As you can see the ips returned were **wrong** and the other ip info is **missing**
### Versions Report

```
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-53-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
