### ISSUE TITLE
BUG git_pillar denial of service remote server when access is denied

### ISSUE THREAD

**Issue by 4s1** [saltstack/salt#38230]
### Description of Issue
I configured salt master to get pillar data from a git repository over HTTP(S).
When the git remote gives a HTTP/401 Unauthorized, the git_pillar client immediately tries again (and again and again ...). So a request hit my server every 20ms (seems to be a performance cap on my hardware) until I stop the salt-master.

I expected 
- a reasonable holdoff time on any git error and 
- especially any feedback in salt-master logs/stdout 

### Setup
````
# temporary allow http while pki/https is not yet set up
git_pillar_insecure_auth: True

ext_pillar:
  - git:
    - http://git.DOMAIN.TLD/git/salt-pillar-data.git:
      - user: 'svc_saltmaster'
      - password: 'xxxxxxxxxx
````

### Steps to Reproduce Issue
- configure git_pillar remote over http(s)
- remove any existing lock: `salt-run cache.clear_git_lock git_pillar type=update`
- start `salt-master -l all`
- tcpdump host <salt-master-ip> and host <git_pillar-remote-server-ip>

### Versions Report
````
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.2
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.12 (default, Nov  7 2016, 11:55:55)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.7.4-1-ARCH
         system: Linux
        version: Not Installed
````
