### ISSUE TITLE
mine.get and salt-ssh gives error message

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#38241]
In 2016.11.1, when running mine.get with salt-ssh, I get this error message 
```
[ERROR   ] Encountered OSError while evaluating  minions in PKI dir: [Errno 2] No such file or directory: '/var/tmp/.root_c561f7_salt/running_data/etc/salt/pki/minion/minions' 
```

### Setup
Put in minion config file
```
mine_functions:
  network.ip_addrs: [eth0]
  networkplus.internal_ip_addrs: []
  internal_ip_addrs:
    mine_function: network.ip_addrs
    cidr: 192.168.0.0/16
  ip_list:
    - mine_function: grains.get
    - ip_interfaces
```
Modify `/etc/salt/roster`
```
ssh:
  host: 173.230.148.210
  user: root
  passwd: xxxxxx
```

### Steps to Reproduce Issue
Run salt-ssh \* mine.get \* network.ip_addrs` to see the error message

```
salt-ssh \* mine.get \* network.ip_addrs
[ERROR   ] Encountered OSError while evaluating  minions in PKI dir: [Errno 2] No such file or directory: '/var/tmp/.root_c561f7_salt/running_data/etc/salt/pki/minion/minions'
ssh:
    ----------
    ssh:
        - 173.230.148.210
```

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 4.8.6-x86_64-linode78
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
