### ISSUE TITLE
Inconsistent results using cmd.run

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt#38252]
### Description of Issue/Question
I'm trying to test detection of cryptolocker by logging file writes in Samba to syslog.
While testing, I used cmd.run to grep syslog for a particular string that didn't exist in syslog yet.

I ran the same command a few seconds apart and got different results.

```
root@salt:~# salt '*nas*' cmd.run 'grep -i HELP_DECRYPT /var/log/syslog'
uslog00nas03:
uslog00nas01:
uslogdcnas04:
usrbgofnas01:
uslogccnas01:
usvansdnas01:
uslogdcnas03:
uslogsdnas01:
uspdxhwnas01:
uspdxsdnas01:
uslmtsdnas01:
uscmsprnas01:
usslesdnas01:
ushqzofnas01:
usloginnas01:


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 15
# of minions returned: 15
# of minions that did not return: 0
# of minions with errors: 15
-------------------------------------------
ERROR: Minions returned with non-zero exit code
root@salt:~# salt '*nas*' cmd.run 'grep -i HELP_DECRYPT /var/log/syslog'
usrbgofnas01:
    Dec 14 08:59:19 usrbgofnas01 salt-minion[8759]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
uslogccnas01:
    Dec 14 08:59:19 uslogccnas01 salt-minion[15513]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
uslog00nas01:
    Dec 14 08:59:19 uslog00nas01 salt-minion[11657]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
uslogdcnas04:
    Dec 14 08:59:19 uslogdcnas04 salt-minion[16112]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
uscmsprnas01:
    Dec 14 08:59:19 uscmsprnas01 salt-minion[9163]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
uslogsdnas01:
    Dec 14 08:59:19 uslogsdnas01 salt-minion[26055]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
uspdxsdnas01:
    Dec 14 08:59:19 uspdxsdnas01 salt-minion[2227]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
uslog00nas03:
    Dec 14 08:59:19 uslog00nas03 salt-minion[20273]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
usvansdnas01:
    Dec 14 08:59:19 usvansdnas01 salt-minion[25016]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
uspdxhwnas01:
    Dec 14 08:59:19 uspdxhwnas01 salt-minion[26855]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
ushqzofnas01:
    Dec 14 08:59:20 ushqzofnas01 salt-minion[28674]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
usloginnas01:
    Dec 14 08:59:20 usloginnas01 salt-minion[17152]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
usslesdnas01:
    Dec 14 08:59:19 usslesdnas01 salt-minion[19029]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
uslogdcnas03:
    Dec 14 08:59:19 uslogdcnas03 salt-minion[30093]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1
uslmtsdnas01:
    Dec 14 08:59:19 uslmtsdnas01 salt-minion[18590]: [ERROR   ] Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 15
# of minions returned: 15
# of minions that did not return: 0
# of minions with errors: 0
-------------------------------------------
root@salt:~# 
```

I manually verified on all those machines that there is no 'HELP_DECRYPT' string in /var/log/syslog.

According to the grep man page: ```The exit status is 0 if selected lines are found, and 1 if not found.  If an error occurred the exit status is 2.```

So grep was returning an exit code of 1 both times I ran the command.

After testing over a few days, the first time I run it in the morning I get the 'blank' output.  Subsequent calls to the command return the ```Command 'grep -i HELP_DECRYPT /var/log/syslog' failed with return code: 1``` message.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
root@salt:~# salt --versions-report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6 
 
root@salt:~# salt '*nas*' test.version

usrbgofnas01:
    2016.11.0
uslogdcnas04:
    2016.11.0
uslogccnas01:
    2016.11.0
usloginnas01:
    2016.11.0
uslog00nas01:
    2016.11.0
uscmsprnas01:
    2016.11.0
usslesdnas01:
    2016.11.0
uslogsdnas01:
    2016.11.0
uspdxsdnas01:
    2016.11.0
uslogdcnas03:
    2016.11.0-461-g723699f
usvansdnas01:
    2016.11.0
ushqzofnas01:
    2016.11.0
uslmtsdnas01:
    2016.11.0
uslog00nas03:
    2016.11.0
uspdxhwnas01:
    2016.11.0


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 15
# of minions returned: 15
# of minions that did not return: 0
# of minions with errors: 0
-------------------------------------------
root@salt:~# 
```
