### ISSUE TITLE
ldap external_auth groups broken and auth.ldap.groupclass expects a userclass

### ISSUE THREAD

**Issue by stephentrooly** [saltstack/salt#38259]
### Description of Issue/Question
it appears that https://github.com/saltstack/salt/commit/8957631c3d72e65091b70681966cbc7f195c204d changes the assumption that configuration option: `auth.ldap.groupclass` should be a groupclass, and has set that option to be a user class.  
```            
           for user, entry in search_results:
                if username == user.split(',')[0].split('=')[-1]:
```
search_results used to return `for group, entry` but..
this change only works because the commit author has set auth.ldap.groupclass to return users, and then filters for 'memberOf' attribute.
`auth.ldap.groupclass: 'person'` <-- this 
`auth.ldap.groupattribute: 'memberOf'` <-- and this

Not all openldap servers have 'memberOf' overlay enabled, and previously that list would be a list of groups, and members of those groups.

### Setup
using standard config values there is no way for this to work:
`auth.ldap.groupclass: posixGroup`

### Steps to Reproduce Issue
added debug logging to show that `for user, entry in search_results` user is a groupname when actually setting this to a group class.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 5.1.0
       dateutil: 2.5.0
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.20.0
        libnacl: 1.4.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.7.10 (default, Dec  8 2015, 18:25:23)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.1.17-22.30.amzn1.x86_64
         system: Linux
        version: Not Installed
```
