### ISSUE TITLE
Workflows system proposal

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38299]
### Description of Issue/Question

Hello,

It's me again 🗡 

The reactor system is already something extremely useful and cool. Sometimes I feel the need for something more enhanced, when a sequence os states is required, e.g.: run state1, if OK run state2. If state2 fails, stop or revert state1 and so forth.

Sure, this can be achieved with a couple of reactors matching the right state tags. But I was wondering if it wouldn't be very complicated to introduce a new system that does that via a config file rather than a couple.

Not sure if the best example, but I hope it's enough to expose the idea:

```yaml
event1:
  fun: state.sls
  args:
    - file.managed
  success: event2
  fail: event3
event2:
  fun: state.sls
  args:
    - users.managed
  success: event4
  fail: event5
```

etc.

```success``` and ```fail``` would be based on the ```result``` flag.
  
I imagine this will involve quite a few work around and I would be happy to help, but first: what do you think?

**Comment by whiteinge** [comment]
The Reactor is best-suited for simple event -> action pairs. But the action that the Reactor kicks off can be plenty complicated and long-running. Have you seen Salt's Orchestrate system yet? It allows for the workflow you are describing and it's a wonderful thing to pair with the Reactor:

https://docs.saltstack.com/en/latest/topics/orchestrate/index.html

**Comment by mirceaulinic** [comment]
Hi @whiteinge! Thanks for explanation! I haven't looked at orch before - looks really awesome!

I've got a question tho: it's not quite useful for me from the examples how'd be the a sequences of states linked together?

```yaml
storage_setup:
  salt.state:
    - tgt: 'role:storage'
    - tgt_type: grain
    - sls: ceph
    - require:
      - salt: webserver_setup

webserver_setup:
  salt.state:
    - tgt: 'web*'
    - highstate: True
```

From the explanation in the bottom of the docs, ```storage_setup``` is executed only if ```webserver_setup``` succeeded. But what happens if ```webserver_setup``` fails? Is there a similar option or so?

Thanks!
