### ISSUE TITLE
The `apache.configfile` state does not allow multiple same sections

### ISSUE THREAD

**Issue by vutny** [saltstack/salt#38306]
### Description of Issue/Question
Looks like the `apache.configfile` state function has limited capabilities in setting multiple sections of the same type at a single level of config hierarchy. 

### Setup
Taking the example from the docs:
```yaml
/etc/httpd/conf.d/website.com.conf:
  apache.configfile:
    - config:
      - VirtualHost:
          this: '*:80'
          ServerName:
            - website.com
          ServerAlias:
            - www.website.com
            - dev.website.com
          ErrorLog: logs/website.com-error_log
          CustomLog: logs/website.com-access_log combined
          DocumentRoot: /var/www/vhosts/website.com
          Directory:
            this: /var/www/vhosts/website.com
            ...
```

It is unclear how to add additional config options for other sub-directories to this virtual host.
To achive resulting config look like this:

```xml
<VirtualHost *:80>
ServerName website.com
ServerAlias www.website.com dev.website.com
ErrorLog logs/website.com-error_log
CustomLog logs/website.com-access_log combined
DocumentRoot /var/www/vhosts/website.com
<Directory /var/www/vhosts/website.com>
Require all granted
Options Indexes
</Directory>
<Directory /var/www/vhosts/website.com/admin>
AllowOverride None
Order Deny,Allow
Allow from 192.168.100.0/24
</Directory>
</VirtualHost>
```

**Comment by Ch3LL** [comment]
@vutny i am able to replicate this behavior And when adding another `Directory` like below:

```
          Directory:
            this: /var/www/vhosts/website.com
          Directory:
            this: /var/www/vhosts/website2.com
```
or this:

```
          Directory:
            this: /var/www/vhosts/website.com
            this: /var/www/vhosts/website2.com
```

I receive a conflicting id error. Looks like we need to add the ability to add more then one directory. Thanks

Also here is a docker container for anyone that wants to quickly replicate this:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing ch3ll/issues:38306 salt-call --local state.sls apache`
