### ISSUE TITLE
Pillar is not overwriting lists, with pillar_merge_lists: False

### ISSUE THREAD

**Issue by pcdummy** [saltstack/salt#38440]
### Description of Issue/Question

I tested a setup where i want to overwrite particular packages that get purged by default
and on some hosts i want an exception of these.

But my Setup below doesn't seem to work:

#### container.sls

    packages:
      purged:
        lxd:
          - lxd
          - lxd-client
          - lxc-common
        container:
          - mdadm
          - sosreport
          - parted
          - lvm2
          - hdparm
          - gdisk
          - btrfs-tools
    # We don't need dhcp for our containers.
        dhcp:
          - isc-dhcp-common
          - isc-dhcp-client
        iscsi:
          - open-iscsi
      installed:
        lxd:
          - lxcfs

#### host.sls

    packages:
      purged:
        container:
          - mdadm

#### top.sls

    base:
      'G@container_variant:lxd':
        - match: compound
        - container

      'host.mynetwork.lan':
        - host

#### output

    packages:
        installed:
            lxd:
                - lxcfs
            unattended-upgrades:
                - unattended-upgrades
        purged:
            common:
                - ufw
                - snapd
                - cloud-init
            container:
                - mdadm
                - sosreport
                - parted
                - lvm2
                - hdparm
                - gdisk
                - btrfs-tools
            dhcp:
                - isc-dhcp-common
                - isc-dhcp-client
            iscsi:
                - open-iscsi
            lxd:
                - lxd
                - lxd-client
                - lxc-common

### Steps to Reproduce Issue

- Create the pillar above.
- run "salt host pillar.items"

### Versions Report

    root@saltmaster:/srv/salt/base# salt --versions-report
    Salt Version:
               Salt: 2016.11.1
     
    Dependency Versions:
               cffi: 1.9.1
           cherrypy: 3.8.0
           dateutil: 2.4.2
              gitdb: 0.6.4
          gitpython: 1.0.1
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: 0.24.0
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
             pygit2: 0.24.0
             Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist: Ubuntu 16.04 xenial
            machine: x86_64
            release: 4.4.0-57-generic
             system: Linux
            version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
Unfortunately I am unable to replicate this with a masterless minion in a docker container.

```
 ~github salt ➤ docker run --rm -ti gtmanfred/issues:38440 salt-call pillar.items
local:
    ----------
    packages:
        ----------
        installed:
            ----------
            lxd:
                - lxcfs
        purged:
            ----------
            container:
                - mdadm
            dhcp:
                - isc-dhcp-common
                - isc-dhcp-client
            iscsi:
                - open-iscsi
            lxd:
                - lxd
                - lxd-client
                - lxc-common
```

` gtmanfred/issues:38440` this is the image name on hub.docker.com

Thanks,
Daniel

**Comment by gtmanfred** [comment]
I have also double checked this with a master and minion, and am still not able to reproduce what you are experiencing.  The default behavior is for this to be set to false, so can you double check that the grain is actually applied to that minion so that it matches it? (you can test by calling grains.get container_variant and making sure it returns lxd)  Also, make sure that you don't have pillar_merge_lists: True in any other configuration files.

Thanks,
Daniel

**Comment by whytewolf** [comment]
i can confirm this happens in git_pillar.

**Comment by gtmanfred** [comment]
@terminalmage can you take a look at this when you get back?

I have confirmed the same thing they are seeing with git_pillar, but I don't see any reason that this would be the case since it is using salt.utils.dictupdate.merge just like the regular pillars.

Thanks,
Daniel

**Comment by terminalmage** [comment]
I think that this is just the intended behavior. The merging happens _between_ individual git_pillar remotes, not _during_, if I understand correctly. But, we may also not be properly passing through the ``pillar_merge_lists`` option when git_pillar is evaluated. I'll do some testing here on my end.

**Comment by terminalmage** [comment]
I checked and we're handling ``pillar_merge_lists`` correctly. And I'm unable to reproduce this both in normal pillar and git_pillar. I've pushed a Docker image of my own (``~/git/salt/main`` is a path to my git clone of salt, with HEAD detached and pointed at the v2016.11.1 tag):

```
% docker run --rm -it -v ~/git/salt/main:/testing terminalmage/issues:38440
[root@e0d612edda33 ~]# cat /etc/salt/minion
id: test
file_client: local
#pillar_merge_lists: True

ext_pillar:
  - git:
    - issue38440 https://github.com/terminalmage/git_pillar:
    #- issue38440-reverse https://github.com/terminalmage/git_pillar:
      - env: base

pillar_roots:
  base:
    - /srv/pillar
[root@e0d612edda33 ~]# for path in /srv/pillar/*.sls; do echo $path; echo --------------------; cat $path; echo; done
/srv/pillar/host.sls
--------------------
roots:
  purged:
    container:
      - mdadm

/srv/pillar/linux.sls
--------------------
roots:
  purged:
    container:
      - not_mdadm
      - sosreport
      - parted
      - lvm2
      - hdparm
      - gdisk
      - btrfs-tools

/srv/pillar/top.sls
--------------------
base:
  'G@kernel:Linux':
    - linux
  'test':
    - host

[root@e0d612edda33 ~]# salt-call --local pillar.items
local:
    ----------
    git_pillar:
        ----------
        purged:
            ----------
            container:
                - mdadm
    roots:
        ----------
        purged:
            ----------
            container:
                - mdadm
[root@e0d612edda33 ~]# vim /etc/salt/minion
[root@e0d612edda33 ~]# cat /etc/salt/minion
id: test
file_client: local
#pillar_merge_lists: True

ext_pillar:
  - git:
    #- issue38440 https://github.com/terminalmage/git_pillar:
    - issue38440-reverse https://github.com/terminalmage/git_pillar:
      - env: base

pillar_roots:
  base:
    - /srv/pillar
[root@e0d612edda33 ~]# vim /srv/pillar/top.sls
[root@e0d612edda33 ~]# cat /srv/pillar/top.sls
base:
  'test':
    - host
  'G@kernel:Linux':
    - linux
[root@e0d612edda33 ~]# salt-call --local pillar.items
local:
    ----------
    git_pillar:
        ----------
        purged:
            ----------
            container:
                - not_mdadm
                - sosreport
                - parted
                - lvm2
                - hdparm
                - gdisk
                - btrfs-tools
    roots:
        ----------
        purged:
            ----------
            container:
                - not_mdadm
                - sosreport
                - parted
                - lvm2
                - hdparm
                - gdisk
                - btrfs-tools
```

I've reproduced the exact same setup in git_pillar as in pillar_roots, with differing top-level pillar keys to distinguish them in the output. As you can see, there is no merging going on, I've changed the ``linux.sls`` file to not contain ``mdadm`` (replacing it with ``not_mdadm``) to illustrate this. There's no mystery as to why both the pillar_roots and ext_pillar give the same result when the same top file and pillar SLS are used; they both use the same exact code to evaluate pillar SLS files.
