### ISSUE TITLE
Reactor sls files does not respect a compound targeting scheme

### ISSUE THREAD

**Issue by netvisao** [saltstack/salt#38453]
``` yaml
configure_x:
  local.state.sls:
    - tgt: 'roles:role1'
    - expr_form: grain
    - arg:
      - node.doSomething
    - kwarg:
        pillar:
          some_key: {{ data['data']['someKey'] }}

configure_y:
  local.state.sls:
    - tgt: 'roles:role2'
    - expr_form: grain
    - arg:
      - node.doSomething
    - kwarg:
        pillar:
          some_key: {{ data['data']['someKey'] }}
```
This code is repetitive and does not follow the DRY principle. Trying this does not work where it should:
``` yaml
configure_x_and_y:
  local.state.sls:
    - tgt: 'G@roles:role1 or G@roles:role2'
    - expr_form: compound
    - arg:
      - node.doSomething
    - kwarg:
        pillar:
          some_key: {{ data['data']['someKey'] }}
```
