### ISSUE TITLE
file.line with mode=delete does not preserve ownership of a file

### ISSUE THREAD

**Issue by jf** [saltstack/salt#38452]
### Description of Issue/Question

If you use `file.line` with `mode: delete`, if a successful deletion occurs, the ownership of the file is not preserved (but changes to root:root)

### Steps to Reproduce Issue

Use `file.line` with `mode: delete` in a state file, and set it up to successfully delete at least one line in a file on the minion that is not owned by root. After the state has run, you will see that the file is now chowned root:root.

### Versions Report

2016.11.1 on both master and minion.

**Comment by gtmanfred** [comment]
Thanks for reporting this.

I have confirmed the problem, and it looks like we just don't maintain the ownership in the file.line execution function.

I have tagged this as a bug for our platform team to take a look.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Can you verify if this is fixed in 2016.11.4?

Thanks,
Daniel

**Comment by hatifnatt** [comment]
No it's still not fixed. file.line still change ownership to root:root
Debian 7
`dpkg -l "salt*"`
```
ii  salt-common      2016.11.5+ds
ii  salt-master      2016.11.5+ds
ii  salt-minion      2016.11.5+ds
ii  salt-syndic      2016.11.5+ds
```

**Comment by gtmanfred** [comment]
Are you using the file.line execution module, or the state module?

This should work in a state now, after this https://github.com/saltstack/salt/issues/39592

**Comment by hatifnatt** [comment]
I'm using state module. There is the code:
```
create_file:
  file.managed:
    - name: /tmp/38452.tmp
    - source: salt://{{ slspath }}/38452.tmp
    - user: hatifnatt
    - group: hatifnatt
    - mode: 644
    - skip_verify: True
    - require_in:
      - file: delete_line

delete_line:
  file.line:
    - name: /tmp/38452.tmp
    - mode: delete
    - content: "22222"
```
38452.tmp
```
11111
22222
33333
```
Run it:
`salt 'vds01*' state.sls issue.38452`
```
          ID: create_file
    Function: file.managed
        Name: /tmp/38452.tmp
      Result: True
     Comment: File /tmp/38452.tmp updated
     Started: 19:04:47.749496
    Duration: 812.315 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,3 +1,3 @@
                   11111
                  -44444
                  +22222
                   33333
              group:
                  hatifnatt
              user:
                  hatifnatt
----------
          ID: delete_line
    Function: file.line
        Name: /tmp/38452.tmp
      Result: True
     Comment: Changes were made
     Started: 19:04:48.562007
    Duration: 29.581 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,4 +1,3 @@
                   11111-22222 33333
```
After execution:
```
ls -la /tmp/38452.tmp
-rw-r--r-- 1 root root 12 Июл 10 19:04 /tmp/38452.tmp

cat /tmp/38452.tmp
11111
33333
```
