### ISSUE TITLE
Unable to schedule runners

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#38514]
### Description

The following schedule on the master won't work as expected.

```
schedule:
  # update winrepo
  updatewinrepo:
    function: winrepo.update_git_repos
    when: 11:55am

  # generate winrepo after refresh
  generatewinrepo:
    function: winrepo.genrepo
    when: 2:30am
```

### Setup
Latest Salt running on Arch

### Steps to Reproduce Issue

Error in logs

```
2017-01-01 02:32:04,970 [salt.utils.schedule][ERROR   ][28394] Unhandled exception running runner.winrepo.genrepo
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 826, in handle_func
    message=self.functions.missing_fun_string(func))
  File "/usr/lib/python2.7/site-packages/salt/utils/error.py", line 36, in raise_error
    raise ex(message)
Exception: 'runner.winrepo.genrepo' is not available.
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 8.5.0
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.6
         Jinja2: 2.8
        libgit2: 0.24.2
        libnacl: 1.5.0
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.13 (default, Dec 21 2016, 07:16:46)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.2
            ZMQ: 4.2.0

System Versions:
           dist:
        machine: x86_64
        release: 4.8.13-1-ARCH
         system: Linux
        version: Not Installed
```

Anything I'm missing or is this a bug?
