### ISSUE TITLE
schedule not changed on pillar update after minion restart

### ISSUE THREAD

**Issue by MorphBonehunter** [saltstack/salt#38523]
### Description of Issue/Question
If you define an schedule in pillar data the schedule is implemented.
If you then try to change the schedule interval, the schedule is updated but fails to
update the "_schedule.conf" File.

### Setup
Defined an schedule in "pillars/pandora/init.sls":
```
schedule:
    underworld_pki_run_state:
        function: state.apply
        minutes: 1
        args:
            - underworld-pki
```
So the Schedule is implemented:
```
# salt 'pandora*' schedule.list
pandora.underworld.lan:
    schedule:
      underworld_pki_run_state:
        args:
        - underworld-pki
        enabled: true
        function: state.apply
        minutes: 1
```
and is running:
```
# tail -f /var/log/salt/minion | grep "Running scheduled job: underworld_pki_run_state"
2017-01-03 10:03:37,611 [salt.utils.schedule][INFO    ][23384] Running scheduled job: underworld_pki_run_state
2017-01-03 10:04:37,611 [salt.utils.schedule][INFO    ][23384] Running scheduled job: underworld_pki_run_state
2017-01-03 10:05:37,611 [salt.utils.schedule][INFO    ][23384] Running scheduled job: underworld_pki_run_state
```
The "_schedule.conf" shows:
```
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false}
  underworld_pki_run_state:
    args: [underworld-pki]
    function: state.apply
    minutes: 1
```

### Steps to Reproduce Issue
So now try to alter the timeframe in "pillars/pandora/init.sls":
```
schedule:
    underworld_pki_run_state:
        function: state.apply
        minutes: 2
        args:
            - underworld-pki
```
Update pillars:
```
# salt 'pandora*' saltutil.refresh_pillar && date
pandora.underworld.lan:
    True
Di 3. Jan 10:06:50 CET 2017
```
So the Schedule shows the right values:
```
# salt 'pandora*' schedule.list
pandora.underworld.lan:
    schedule:
      underworld_pki_run_state:
        args:
        - underworld-pki
        enabled: true
        function: state.apply
        minutes: 2
```
and the schedule is running as expected:
```
# tail -f /var/log/salt/minion | grep "Running scheduled job: underworld_pki_run_state"
2017-01-03 10:08:37,610 [salt.utils.schedule][INFO    ][23384] Running scheduled job: underworld_pki_run_state
2017-01-03 10:10:37,610 [salt.utils.schedule][INFO    ][23384] Running scheduled job: underworld_pki_run_state
2017-01-03 10:12:37,611 [salt.utils.schedule][INFO    ][23384] Running scheduled job: underworld_pki_run_state
```
But the "_schedule.conf" shows still:
```
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false}
  underworld_pki_run_state:
    args: [underworld-pki]
    function: state.apply
    minutes: 1
```
So, now restart the minion:
```
# systemctl restart salt-minion && date
Di 3. Jan 10:16:39 CET 2017
```
and look at the logs:
```
# tail -f /var/log/salt/minion | grep "Running scheduled job: underworld_pki_run_state"
2017-01-03 10:16:43,950 [salt.utils.schedule][INFO    ][24129] Running scheduled job: underworld_pki_run_state
2017-01-03 10:17:43,768 [salt.utils.schedule][INFO    ][24129] Running scheduled job: underworld_pki_run_state
2017-01-03 10:18:43,768 [salt.utils.schedule][INFO    ][24129] Running scheduled job: underworld_pki_run_state
```
The schedule falls back to the 1-Minute intervall, the "schedule.list" shows the right stuff:
```
pandora.underworld.lan:
    schedule:
      underworld_pki_run_state:
        args:
        - underworld-pki
        enabled: true
        function: state.apply
        minutes: 2
```
Also an pillar refresh does not work:
```
# salt 'pandora*' saltutil.refresh_pillar && date
pandora.underworld.lan:
    True
Di 3. Jan 10:20:13 CET 2017

# tail -f /var/log/salt/minion | grep "Running scheduled job: underworld_pki_run_state"
2017-01-03 10:20:43,768 [salt.utils.schedule][INFO    ][24129] Running scheduled job: underworld_pki_run_state
2017-01-03 10:21:43,768 [salt.utils.schedule][INFO    ][24129] Running scheduled job: underworld_pki_run_state
2017-01-03 10:22:43,767 [salt.utils.schedule][INFO    ][24129] Running scheduled job: underworld_pki_run_state
```
Bigger Problem is, that also an change of the timeframe in "pillars/pandora/init.sls" does not do anything now:
```
schedule:
    underworld_pki_run_state:
        function: state.apply
        minutes: 5
        args:
            - underworld-pki
```
looks good:
```
# salt 'pandora*' saltutil.refresh_pillar && date
pandora.underworld.lan:
    True
Di 3. Jan 10:23:38 CET 2017

# salt 'pandora*' schedule.list
pandora.underworld.lan:
    schedule:
      underworld_pki_run_state:
        args:
        - underworld-pki
        enabled: true
        function: state.apply
        minutes: 5
```
But doesn't work:
```
2017-01-03 10:23:43,767 [salt.utils.schedule][INFO    ][24129] Running scheduled job: underworld_pki_run_state
2017-01-03 10:24:43,767 [salt.utils.schedule][INFO    ][24129] Running scheduled job: underworld_pki_run_state
2017-01-03 10:25:43,767 [salt.utils.schedule][INFO    ][24129] Running scheduled job: underworld_pki_run_state
```
Content of "_schedule.conf" is still:
```
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false}
  underworld_pki_run_state:
    args: [underworld-pki]
    function: state.apply
    minutes: 1
```

### Versions Report
Installed Salt in Arch Linux.
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 8.5.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Dec 21 2016, 07:16:46)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.0
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.8.13-1-ARCH
         system: Linux
        version: Not Installed
```

### Workaround
Only thing to get this "reset":
```
systemctl stop salt-minion && rm /etc/salt/minion.d/_schedule.conf && systemctl start salt-minion
```

**Comment by gtmanfred** [comment]
Setting the schedule in the pillar does not change the /etc/salt/minion.d/_schedule.conf file, it just operates as a different place to store the schedule options.

You would need to use a schedule.absent or schedule.disabled to change that.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.schedule.html#salt.states.schedule.absent

The _schedule.conf file is really only there to make sure that the mine gets updated periodically.  Nothing else in salt knows about it unless you use the schedule.present/absent states.

**Comment by MorphBonehunter** [comment]
@gtmanfred so if
> The _schedule.conf file is really only there to make sure that the mine gets updated periodically. Nothing else in salt knows about it unless you use the schedule.present/absent states.

why is then the "_schedule.conf" updated with:
```
  underworld_pki_run_state:
    args: [underworld-pki]
    function: state.apply
    minutes: 1
```
another question is then, when i do not need an "schedule.present" for implementing the Schedule (as you can see, i only change the pillar data and run saltutil.refresh_pillar) why must i use schedule.absent to get rid of it?
so the original question persists; why is the schedule cycle not updated when i change the timeframe?

**Comment by MorphBonehunter** [comment]
Actually the schedule can be removed but reapear after minion restart.
When i delete the schedule entry in the pillar data, i got the following after an "saltutil.refresh_pillar":
```
# salt 'pandora*' schedule.list && date
pandora.underworld.lan:
    ----------
    schedule:
        ----------
Di 3. Jan 18:48:37 CET 2017
```
The schedule is not executed anymore.
But after restart of the salt-minion the schedule reapeared (not the data is NOT in the pillar):
```
# salt 'pandora*' schedule.list
pandora.underworld.lan:
    schedule:
      underworld_pki_run_state:
        args:
        - underworld-pki
        enabled: true
        function: state.apply
        jid_include: true
        maxrunning: 1
        minutes: 1
        name: underworld_pki_run_state
```
and got executed:
```
2017-01-03 18:51:53,980 [salt.utils.schedule][INFO    ][12830] Running scheduled job: underworld_pki_run_state
2017-01-03 18:52:53,980 [salt.utils.schedule][INFO    ][12830] Running scheduled job: underworld_pki_run_state
2017-01-03 18:53:53,980 [salt.utils.schedule][INFO    ][12830] Running scheduled job: underworld_pki_run_state
```
But if i now delete the "_schedule.conf" the schedule disapear (there are still NO changes in the pillar data).

**Comment by gtmanfred** [comment]
Hrm, i was unaware of this capability.

Can you provide the output of running pillar.items?

**Comment by MorphBonehunter** [comment]
Yes, sure (i reduce the output to the relevant sections because of sensitive data).
With the following in the pillar file "pillars/pandora/init.sls":
```
schedule:
    underworld_pki_run_state:
        function: state.apply
        minutes: 1
        args:
            - underworld-pki
```
I get the following pillar item:
```
# salt 'pandora*' pillar.item schedule
pandora.underworld.lan:
    ----------
    schedule:
        ----------
        __update_grains:
            ----------
            args:
                |_
                  ----------
                - grains_refresh
            function:
                event.fire
            minutes:
                60
            name:
                __update_grains
        underworld_pki_run_state:
            ----------
            args:
                - underworld-pki
            function:
                state.apply
            minutes:
                1
            name:
                underworld_pki_run_state
```
After the deletion of the entry in the Pillar File i get:
```
daniel@pandora ~/repos/underworld/saltstack [master *] $ salt 'pandora*' pillar.item schedule
pandora.underworld.lan:
    ----------
    schedule:
```
Mhh...i wonder where the "__update_grains" entry comes from...
