### ISSUE TITLE
[2016.11.2] x509.certificate_managed / x509.create_certificate fails on first certificate.

### ISSUE THREAD

**Issue by alxwr** [saltstack/salt#38594]
### Description of Issue/Question

The creation of the first certificate of a host fails.
I'm following the example of https://docs.saltstack.com/en/latest/ref/states/all/salt.states.x509.html.

It's 100% reproducible on the CA itself, but happens on other hosts too. When I rerun `state.highstate` on the affected non-CA host, everything just works. (Smells like race condition.)

### Setup

```
# states/top.sls
base:
  '*':
    - x509.certs
  'ca.my.tld':
    - x509.ca
    - x509.minionless_certs
  'some_host':
    - x509.www  # from the linked example
```

```
# states/x509/ca.sls 
salt_minion:
  service.running:
    - enable: True
    - listen:
      - file: {{ pillar['userland_etc'] }}/salt/minion.d/signing_policies.conf

{{ pillar['userland_etc'] }}/salt/minion.d/signing_policies.conf:
  file.managed:
    - source: salt://x509/signing_policies.conf
    - template: jinja

{{ pillar['userland_etc'] }}/pki:
  file.directory: []

{{ pillar['userland_etc'] }}/pki/issued_certs:
  file.directory: []

{{ pillar['userland_etc'] }}/pki/ca.key:
  x509.private_key_managed:
    - bits: 4096
    - backup: True
    - require:
      - file: {{ pillar['userland_etc'] }}/pki
      - sls: x509.certs

{{ pillar['userland_etc'] }}/pki/ca.crt:
  x509.certificate_managed:
    - signing_private_key: {{ pillar['userland_etc'] }}/pki/ca.key
    - CN: ca.example.com
    - C: **
    - ST: '-'
    - L: '-'
    - basicConstraints: "critical CA:true"
    - keyUsage: "critical cRLSign, keyCertSign"
    - subjectKeyIdentifier: hash
    - authorityKeyIdentifier: keyid,issuer:always
    - days_valid: 3650
    - days_remaining: 0
    - backup: True
    - require:
      - x509: {{ pillar['userland_etc'] }}/pki/ca.key
      - sls: x509.certs

mine.send:
  module.run:
    - func: x509.get_pem_entries
    - kwargs:
        glob_path: {{ pillar['userland_etc'] }}/pki/ca.crt
    - onchanges:
      - x509: {{ pillar['userland_etc'] }}/pki/ca.crt
```

```
# states/x509/certs.sls 
{{ pillar['x509']['ca_dir'] }}:
  file.directory: []

{% set mined = salt['mine.get']('ca.my.tld', 'x509.get_pem_entries') %}
{% if mined %}
{{ pillar['x509']['ca_dir'] }}/my.tld-ca.crt:
  x509.pem_managed:
    - text: {{ mined['ca.my.tld'][pillar['userland_etc']+'/pki/ca.crt']|replace('\n', '') }}
{% endif %}

{{ pillar['x509']['cert_dir'] }}:
  file.directory: []

{{ pillar['x509']['key_dir'] }}:
  file.directory: []
```

```
# states/x509/minionless_certs.sls 
/opt/pki:
  file.directory:
    - mode: 700
    - user: root

/opt/pki/test.key:
  x509.private_key_managed:
    - bits: 4096

/opt/pki/test.crt:
  x509.certificate_managed:
    - ca_server: ca.my.tld
    - signing_policy: long
    - public_key: /opt/pki/test.key
    - CN: test
    - days_remaining: 30
    - backup: False

{% for fqdn in pillar['x509']['minionless_certs'] %}
/opt/pki/{{ fqdn }}.key:
  x509.private_key_managed:
    - bits: 4096

/opt/pki/{{ fqdn }}.crt:
  x509.certificate_managed:
    - ca_server: ca.my.tld
    - signing_policy: long
    - public_key: /opt/pki/{{ fqdn }}.key
    - CN: {{ fqdn }}
    - days_remaining: 30
    - backup: True
{% endfor %}
```

```
# pillar/x509.sls 
x509:
  minionless_certs:
    - one.my.tld
    - two.my.tld
    - three.my.tld
{% if grains['os'] == 'FreeBSD' %}
  ca_dir: /etc/ssl/certs
  cert_dir: /usr/local/etc/ssl/certs
  key_dir: /usr/local/etc/ssl/private
{% else %}
  ca_dir: /usr/local/share/ca-certificates
  cert_dir: /etc/ssl/certs
  key_dir: /etc/ssl/private
{% endif %}
```

### Steps to Reproduce Issue

```
salt 'host' state.highstate
```

results in

```
[…]
  Name: /opt/pki/test.key - Function: x509.private_key_managed - Result: Clean Started: - 18:30:
46.751098 Duration: 0.809 ms
----------
          ID: /opt/pki/test.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrap
per
                  return f(*args, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/states/x509.py", line 442, in 
certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/modules/x509.py", line 1324, i
n create_certificate
                  arg=str(kwargs))[ca_server]
              KeyError: 'ca.my.tld'
     Started: 18:30:46.752011
    Duration: 6013.73 ms
     Changes:
[…]
```

It's always the first `x509.certificate_managed` which fails. If I remove `test(.crt)`, `one.my.tld` fails. If `one.my.tld` and `three.my.tld` are interchanged, `three.my.tld` fails.

There may be a connection to #32075.

### Versions Report

```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan  3 2017, 01:35:50)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: amd64
        release: 10.3-RELEASE-p11
         system: FreeBSD
        version: Not Installed
```
