### ISSUE TITLE
In Orchestration, kwargs are not passed to state.sls in masterless mode

### ISSUE THREAD

**Issue by doitian** [saltstack/salt#38631]
### Setup

https://gist.github.com/doitian/edc9fa7e0e0dcca21f722a3d2e024296

### Steps to Reproduce Issue

```
salt-call -c ./ state.orchestrate orch_test
```

In masterless mode, `state.sls` is called directly, but kwargs is nested in `kwarg` so all arguments are not passed to the underlying function.

see https://github.com/saltstack/salt/blob/develop/salt/states/saltmod.py#L259

### Versions Report
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul 30 2016, 19:40:32)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.0
 
System Versions:
           dist:   
        machine: x86_64
        release: 16.3.0
         system: Darwin
        version: 10.12.2 x86_64
```
