### ISSUE TITLE
No release file error from PPA on Ubuntu

### ISSUE THREAD

**Issue by ericuldall** [saltstack/salt#38648]
I went through the installation steps for Ubuntu and I'm unable to get the apt-get update to work.

```
Hit:1 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                                              
Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                                            
Hit:4 http://archive.canonical.com/ubuntu xenial InRelease                                                                                                                             
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Ign:6 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial InRelease    
Ign:7 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial Release      
Ign:8 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main all Packages
Ign:10 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en_US
Ign:11 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en
Ign:8 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main all Packages
Ign:10 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en_US
Ign:11 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en
Ign:8 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main all Packages
Ign:10 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en_US
Ign:11 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en
Ign:8 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main all Packages
Ign:10 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en_US
Ign:11 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en
Ign:8 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main all Packages
Ign:10 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en_US
Ign:11 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en
Err:8 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:9 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main all Packages
Ign:10 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en_US
Ign:11 http://ppa.launchpad.net/saltstack/salt/ubuntu xenial/main Translation-en
Fetched 102 kB in 2s (35.8 kB/s)
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/saltstack/salt/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/saltstack/salt/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Currently running Ubuntu 16.04 and salt 2015.8.8 (Beryllium)

I'm trying to get the updated version of salt that doesn't have the `Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value` Warning.

TY

**Comment by ericuldall** [comment]
This seems to be causing issues when installing packages from the master:

```
salt-minion2.c.rm-dash-001.internal:
----------
          ID: nginx
    Function: pkg.installed
      Result: False
     Comment: An error was encountered while installing package(s): W: The repository 'http://ppa.launchpad.net/saltstack/salt/ubuntu xenial Release' does not have a Release file.
              E: Failed to fetch http://ppa.launchpad.net/saltstack/salt/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
              E: Some index files failed to download. They have been ignored, or old ones used instead.
     Started: 23:15:08.121110
    Duration: 5060.513 ms
     Changes:   
----------
          ID: nginx
    Function: service.running
      Result: False
     Comment: One or more requisite failed: nginx.nginx
     Started: 
    Duration: 
     Changes: 
```
