### ISSUE TITLE
support for Amazon s3:// URL in salt.fileclient

### ISSUE THREAD

**Issue by bclermont** [saltstack/salt#3864]
Now that botocore is a dependency else, it can be used to add Amazon S3 support.

**OR**

instead of using URL to detect the protocol, just add a new argument and give the ability to have pluggable file downloader.

```
/etc/somewhere:
  - file.managed:
    - source: /path/in/my/bucket/file
    - type: s3
    - s3_auth: xxx
    - s3_key: yyy
```

and I get drop a ``s3.py`` in my ``_sources/`` folder.
