### ISSUE TITLE
Comparing file with uploaded one

### ISSUE THREAD

**Issue by tuner23** [saltstack/salt#38656]
Hi,

i want to upload a ssh key, only if changed, what i do:

```
{%- set git_key = salt['cmd.run']('cat /data/repos/.ssh/id_rsa.pub') -%}
{%- set git_key_uploaded = salt['cp.get_file_str']('salt://priv.arx/common/keys/git.key') -%}

  {% if git_key != git_key_uploaded %}
  upload_git_key:
    module.run:
      - name: cp.push
      - path: /data/repos/.ssh/id_rsa.pub
      - upload_path: /common/keys/git.key
      - require:
        - cmd: generate_ssh_key_git
  {% endif %}
```

But the command gets always executed. What am i doing wrong here?

Thanks,
Toni.

**Comment by gtmanfred** [comment]
Could you do the following?

```
{% if salt['file.get_diff']('/data/repos/.ssh/id_rsa.pub', 'salt://priv.arx/common/keys/git.key') %}
upload_git_key:
  module.run:
    - name: cp.push
    - path: /data/repos/.ssh/id_rsa.pub
    - upload_path: /common/keys/git.key
    - require:
      - cmd: generate_ssh_key_git
{% endif %}
```

And use the built in diff module?

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.get_diff
