### ISSUE TITLE
state.apply test=True issue with pip packages

### ISSUE THREAD

**Issue by Ge0** [saltstack/salt#38688]
### Description of Issue/Question

Hey.

When I want to test the correctness of my salt states with the `test=True` extra param of my `state.apply` command, I get several issues which don't rise upon normal state application.

### Setup

Take this simple salt collection of states:

```
python-pip:
  pkg.installed:
    - pkgs:
      - python-pip

awscli:
  pip.installed:
    - name: awscli
    - require:
      - pkg: python-pip
```

### Steps to Reproduce Issue

```
$ salt-ssh -i --config-dir=path/to/salt/conf '*' state.apply test=True
[...]
----------
          ID: python-pip
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: python-pip
     Started: 14:49:34.166273
    Duration: 15.143 ms
     Changes:   
----------
          ID: awscli
    Function: pip.installed
      Result: False
     Comment: An importable pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
     Started: 14:49:34.234303
    Duration: 0.796 ms
     Changes:   
----------
```

As you can see, the state *awscli* fails whereas it normally should succeed since pip is meant to be installed.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Dec 21 2016, 07:16:46)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.8.13-1-ARCH
         system: Linux
        version: Not Installed
```
