### ISSUE TITLE
win_lgpo state fails to set single policy due to case sensitive check

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#38689]
### Description of Issue/Question
Attempting to use the win_lgpo state to set a single policy (as described in the documentation of the state) fails due to a case sensitive check of the policy_class paramter.

### Setup
A state such as will return with no changes made due to policy_class being checked against the string "machine" in the win_lgpo.py file
```
DisableOneDrive:
    lgpo.set:
      - name: Prevent the usage of OneDrive for file storage
      - setting: Enabled
      - policy_class: Machine
      - adml_language: en-US
```

### Steps to Reproduce Issue
Execute a lgpo.set state with policy_class in title case.

### Versions Report
2016.11.1
