### ISSUE TITLE
service.dead fails when service is not installed.

### ISSUE THREAD

**Issue by sketch242** [saltstack/salt#38696]
service.dead fails when the service is not installed.  I have the following state:

```
postfix:
  service.dead:
    - enable: False
  pkg.removed:
    - pkgs:
        - postfix
```

The first time I run it, it is clean, but the second time around, it fails because the postfix service has been uninstalled.  If I replace service.dead with service.disabled, it does not return an error when the service is not installed, so this seems like a bug in service.dead.

testhost:
----------
          ID: postfix
    Function: service.dead
      Result: False
     Comment: The named service postfix is not available
     Started: 18:47:24.563870
    Duration: 19.276 ms
     Changes:   
  Name: postfix - Function: pkg.removed - Result: Clean Started: - 18:48:56.432033 Duration: 2369.843 ms

This is on CentOS 7, master and minion are both 2016.3.4.
