### ISSUE TITLE
file.managed evaluates salt:// sources out of turn, resulting in "Unable to manage file: none of the specified sources were found"

### ISSUE THREAD

**Issue by sivann** [saltstack/salt#38706]
### Description of Issue/Question
Consider having a file.managed, which just transfers the salt://dir/myfile to the minion. The problem occurs when  the source is created by (another) required state. When this happens, the state fails with "Unable to manage file: none of the specified sources were found", regardless of the fact that when it's the file.managed state turn to run, the file actually has been successfully created by another state.

The source: salt://dir/myfile should be checked for existence only when it's the state's turn to run, not before. 

### Setup
Check state 2 below. 
```

{% set cid=grains['id'].split('.')[0].split('-c')[-1] %}
# 1. This creates the source of the 2nd file managed, salt://svntemp/{{ grains['id'] }}-xxx_{{ cid }}_id.json 
# This runs first, triggers a web call which creates the file. This runs fine.

ctrlid-savetomaster:
  file:
    - managed
    - name: /dev/null
    - source:
      - http://saltmaster.xxx.com/svn/createfile.php?hostname={{ grains['id'] }}
    - skip_verify: True
    - mode: 644


# 2. fetch the file created above via file.managed
# Always fails on 1st run with "Unable to manage file: none of the specified sources were found"
# seems to check for salt://.. existence before the required state (1) has run.

/etc/xxx/identity.json:
  file:
    - managed
    - source:
      - salt://tel3/files/svntemp/{{ grains['id'] }}-xxx_{{ cid }}_id.json
    - mode: 644
    - dir_mode: 755
    - makedirs: True
    - require:
      - file: ctrlid-savetomaster

```

### Versions Report
```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.3.0
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.5
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-101-generic
         system: Linux
        version: Ubuntu 14.04 trusty

Salt-minion: salt-minion-2016.11.1-1.el7

```

**Comment by Ch3LL** [comment]
@sivann if you add `- reload_modules: true` to the initial state that adds teh files to salts file server does that work. I was able to get it to work with this example:

```
create_file:
  file.managed:
    - name: /srv/salt/test-file
    - reload_modules: true
    - contents: |
        test

/tmp/ctrlid-savetomaster:
  file.managed:
    - source:
      - salt://test-file
```

**Comment by sivann** [comment]
Sorry that didn't help. 1) where is that documented? 2) maybe those states run in parallel and the salt:// doesn't wait for the first to complete?

**Comment by Ch3LL** [comment]
@sivann its documented here: https://docs.saltstack.com/en/latest/ref/states/#reloading-modules

My understanding is this is normally used to reload python modules that are installed during the state run so i thought it might work in this instance. You state its not working. 

Can you post your state with the new argument? just want to see how you have added it. Thanks!

**Comment by sivann** [comment]
@Ch3LL I wrote it like so:
```
#state below fetches file to saltmaster
foo-savetomaster:
  file:
    - managed
    - reload_modules: true
    - name: /dev/null
    - source:
      - http://saltmaster.inaccess.com/svn/save_impl_file_byhost.php?hostname=crookedstone-c0.insolar-plants.net&filename=controller_x_it.json&smartcx=1
    - skip_verify: True
    - mode: 644
```
