### ISSUE TITLE
No Top file or external nodes data matches found

### ISSUE THREAD

**Issue by ccrivelli** [saltstack/salt#38719]
### Description of Issue/Question
Top file not found:
```
minion.internal:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Changes:   

Summary for minion.internal
------------
Succeeded: 0
Failed:    1
------------
```

### Setup
```
# cat /etc/salt/master.d/file_roots.conf 
file_roots:
  mgmt:
    - /srv/salt/mgmt/states/
  dev:
    - /srv/salt/dev/states/
  stage:
    - /srv/salt/stage/states/
  prod:
    - /srv/salt/prod/states/
```
-- only 1 top file in 'mgmt' env:
```
# ls /srv/salt/mgmt/states/top.sls 
/srv/salt/mgmt/states/top.sls
```

### Steps to Reproduce Issue
-- upgrade the saltstack components from 2016.3.1-1 to 2016.11.1 (same behaviour with 2016.11.0) and run:
```
# salt '*' state.highstate
```

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
 
```
-- all saltstack components running with the same version
```
# rpm -qa | grep salt
salt-master-2016.11.1-1.el7.noarch
salt-2016.11.1-1.el7.noarch
salt-minion-2016.11.1-1.el7.noarch
salt-cloud-2016.11.1-1.el7.noarch
```

**Comment by ccrivelli** [comment]
I guess it's related in some way with this: https://github.com/saltstack/salt/pull/36922

Do you have any idea/suggestion how to fix it?
I was wondering if there's a workaround in terms of salt-minion config.

Thanks

**Comment by gtmanfred** [comment]
That pr is in 2016.11, so you shouldn't have a problem with it since you are on 2016.11.1.

Can you provide your top file?  and anything that is not the default in the master and minion configs?

**Comment by ccrivelli** [comment]
The topfile.sls is like:
```
mgmt:
  '^(a|b|c|d|e|f).domain.internal$':
    - match: pcre
    - state1
    - state2
    - state3
  'b.domain.internal':
    - state4
    - state5

prod:
  'prod*.domain.internal':
    - stateA
    - stateB

etc..
```

Yesterday I downgraded back to 2016.3.1-1  (master, minions) and everything is working again.
I kept only one minion with 2016.11.1 (so *only for this minion* the version of salt-master salt-minion  is different) and I'm having the same error here.

My current salt-master config differs from the default one only for these files (added):

```
# tree master.d/
master.d/
├── file_roots.conf
├── pillar_roots.conf
└── reactor.conf
```

Details:
```
# cat master.d/file_roots.conf 
file_roots:
  mgmt:
    - /srv/salt/mgmt/states/
  dev:
    - /srv/salt/dev/states/
  stage:
    - /srv/salt/stage/states/
  prod:
    - /srv/salt/prod/states/

--

# cat master.d/pillar_roots.conf 
pillar_roots:
  mgmt:
    - /srv/salt/mgmt/pillar/
  dev:
    - /srv/salt/dev/pillar/
  stage:
    - /srv/salt/stage/pillar/
  prod:
    - /srv/salt/prod/pillar/

--

# cat master.d/reactor.conf 

state_output: changes

reactor:
   - 'salt/beacon/*/inotify/something':        
      - /srv/salt/dev/reactors/alert.sls
  
```

Salt minions config is exactly like default (only changed the name of saltmaster host).
