### ISSUE TITLE
Specify more than one version of a package

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#3872]
This depends on #2783 being implemented.

Once multiple versions of packages are properly tracked by list_pkgs, you should be able to do the following in SLS:

```
somepkg:
  pkg:
    - installed
    - version:
      - 1.2.3-4
      - 1.2.3-5

mypkgs:
  pkg:
    - installed
    - pkgs:
      - somepkg:
        - 1.2.3-4
        - 1.2.3-5
      - some_other_pkg
```
