### ISSUE TITLE
Existing minion's key is rejected when salt-cloud cannot connect to Proxmox API

### ISSUE THREAD

**Issue by dylwhich** [saltstack/salt#38737]
### Description of Issue/Question
When salt-cloud is unable to connect to the proxmox API, it behaves as though proxmox reported that no containers existed. It continues to attempt to provision all proxmox containers, by first generating a new minion key and accepting it (and rejecting the existing one for that minion). The provisioning process then fails, but the keys remain and must be manually replaced.

### Setup
**/etc/salt/cloud.providers.d/proxmox.conf**:

    proxmox:
      minion:
        master: salt.example.net
      user: root@pam
      password: password
      driver: proxmox
      verify_ssl: False

**cloud.sls**:

    cloud-instance-box.example.net:
      cloud.present:
        - name: box.example.net
        - cloud_provider: proxmox
        - image: data:vztmpl/template-centos.tar.gz
        - technology: lxc
        - host: pve-01
        - storage: data
        - password: changeme-xxx
        - use_dns: True
        - start_action: state.highstate
        - gw: 10.101.22.1
        - bridge: vmbr0
        - ip: 10.101.22.4

### Steps to Reproduce Issue
1. Set up a salt-cloud configuration using proxmox and provision a minion (or just use the name of an existing minion; doesn't matter)
2. Run highstate; existing keys should be unaffected.
3. Prevent the salt master from communicating to the proxmox API in some way (e.g. disconnect either host from the internet)
4. Run highstate; provisioning will fail and the minion's current key will be rejected, with a new key put in place and accepted for the new host that was never provisioned.

### Versions Report
(This issue is also occurring on another environment with a more recent salt version, I think 2016.11, but I cannot currently access it to generate a version report)
````
Salt Version:
           Salt: 2016.3.0-606-g2bd1ac6
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.4.21-1-pve
         system: Linux
        version: Not Installed
````
