### ISSUE TITLE
"del_root_vol_on_destroy: True" causes Error: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by pepoluan** [saltstack/salt#38748]
### Description of Issue/Question
Whenever I add the line `del_root_vol_on_destroy: True` according to [the guide](https://docs.saltstack.com/en/latest/topics/cloud/aws.html#del-root-vol-on-destroy), I get the following error:

    [ERROR   ] There was a profile error: 'NoneType' object has no attribute '__getitem__'

**_Without_** that line (that is, the line commented), instance creation always run successfully.

### Setup

The profile file used:

```yaml
staging_medium_a_pub:
  provider: aws-sg-a

  image: ami-a1288ec2   # Ubuntu 16.04 LTS (mode: HVM)
  ssh_username: ubuntu  # Because Ubuntu
  size: t2.medium

  sync_after_install: all

  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: True
      SubnetId: subnet-aaaaaaaa
      SecurityGroupId:
        - sg-44444444
        - sg-66666666

  del_root_vol_on_destroy: True
```

### Steps to Reproduce Issue

    salt-cloud -p staging_medium_a_pub Test-Server-01

### Versions Report

```
# salt-cloud --version
salt-cloud 2016.11.1 (Carbon)

# salt --version
salt 2016.11.1 (Carbon)
```
