### ISSUE TITLE
file.symlink ignores "mode"

### ISSUE THREAD

**Issue by danel1** [saltstack/salt#38765]
### Description of Issue/Question
As documented it is allowed to set the mode for a file.symlink. There is no problem to set the mode and the state is rendered and applied sucessfully, but somehow the mode get's ignored in any case.
The user:group works how it should.

Saltstack doc's: [https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.symlink](url)
> mode
    The permissions to set on this file, aka 644, 0775, 4664. Not supported on Windows

### Setup
example_symlink:
  file.symlink:
    - name: /root/example/file.txt
    - target: /root/src.txt
    - mode: 0444

OR

example_symlink:
  file.symlink:
    - name: /root/example/file.txt
    - target: /root/src.txt
    - user: root
    - group: wheel
    - mode: 0444

### Steps to Reproduce Issue
As far as i can see the mode is set to "None" in "salt/states/file.py" and is not used/set anymore after.
So it results in beeing ignored.

### Versions Report
**Minion**
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Dec 27 2016, 16:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: amd64
        release: 10.3-RELEASE-p14
         system: FreeBSD
        version: Not Installed
```
**Master**
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-106-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
