### ISSUE TITLE
dockerng: allow restart watch action

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#38773]
Currently, when watching another container, the only watch actions available are to recreate them (using force) or send them a signal. I would love if there would be an option to restart the container. So if watched container does not change (and does not need to be recreated), a restart could be enough.

This is useful when one container (like database) changes and is recreated, then sometimes is needed that containers which are connecting to this database are restarted to reconnect. They do not have to be recreated.

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul 14 2015, 19:46:27)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 14.5.0
         system: Darwin
        version: 10.10.5 x86_64
```
