### ISSUE TITLE
dockerng: unable to use links with custom network

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#38771]
If I use links and a custom network, Salt throws a failure applying links. Interestingly, diff is empty.

So something like:

```
foo:
  dockerng.running:
    - image: bar/baz:latest
    - hostname: web1
    - network_mode: my.network.com
    - links:
      - foo_mongodb:mongodb
```

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul 14 2015, 19:46:27)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 14.5.0
         system: Darwin
        version: 10.10.5 x86_64
```

```
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 31.41 GiB
Name: intel2
ID: JBXO:FLAI:HV2W:3XOP:FOYA:A6OP:GANE:X3EN:AMFH:LWSC:5PPW:RO4H
Docker Root Dir: /srv/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by Ch3LL** [comment]
@mitar what error are you seeing? Ibelieve i am reproducing what you are seeing but want to confirm the same error below:

```
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'issues/38771.sls'
[INFO    ] Running state [foo] at time 15:17:30.113244
[INFO    ] Executing state dockerng.running for foo
[INFO    ] Assuming network_mode 'my.network.com' is a network.
[ERROR   ] {'diff': {}, 'state': {'new': 'running', 'old': 'stopped'}, 'removed': [u'61b8d625a8ae38699e93d8cfb278f24b5c2656caa64ae43a79ad6b42e4dafc22'], 'added': {'Time_Elapsed': 0.3598759174346924, 'Name': 'foo', u'Id': u'1e26ca3d807dce599a329be18826830d61f2ddaabcb74b3d00ea4bcd11d84330', u'Warnings': None}}
[INFO    ] Completed state [foo] at time 15:17:31.781737 duration_in_ms=1668.493
local:
----------
          ID: foo
    Function: dockerng.running
      Result: False
     Comment: Container 'foo' changed state.. Failed to apply configuration for the following parameters: links.
     Started: 15:17:30.113244
    Duration: 1668.493 ms
     Changes:   
              ----------
              added:
                  ----------
                  Id:
                      1e26ca3d807dce599a329be18826830d61f2ddaabcb74b3d00ea4bcd11d84330
                  Name:
                      foo
                  Time_Elapsed:
                      0.359875917435
                  Warnings:
                      None
              diff:
                  ----------
              removed:
                  - 61b8d625a8ae38699e93d8cfb278f24b5c2656caa64ae43a79ad6b42e4dafc22
              state:
                  ----------
                  new:
                      running
                  old:
                      stopped

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:   1.668 s
```

Here were the steps i took:
1. `sudo docker network create my.network.com`
2. `docker run -d --name test-ch3ll ubuntu:latest sleep 3000000`
3. sls file:

```
foo:
  dockerng.running:
    - image: centos:latest
    - hostname: web1
    - network_mode: my.network.com
    - links:
      - test-ch3ll:test-alias-blah
```
