### ISSUE TITLE
State unable to handle data containing unicode

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38776]
### Description of Issue/Question

I have a very simple state:

```yaml
/home/mircea/unicode.sls:
  file.managed:
    - contents: {{ salt.my_module.my_fun() }}
```

Where `my_module.my_fun` returns when executed from the CLI:

```yaml
      ----------
      group_id:
          y57gv9h0y3my
      name:
          ZRH - Zürich, Switzerland
```

OR raw output: `{'group_id': 'y57gv9h0y3my', 'name': 'ZRH - Z\xc3\xbcrich, Switzerland'}`

But when I look into the file managed by the state,

```
OrderedDict([('group_id', 'y57gv9h0y3my'), ('name', 'ZRH - Z\\xc3\\xbcrich, Switzerland')])
```

The content should be `Z\xc3\xbcrich` instead of `Z\\xc3\\xbcrich`.

It looks like it's escapes the unicode characters.

I have the option `yaml_utf8: True` in the master config. Do I need to specify anything else in the state SLS?

Thanks!
Mircea
