### ISSUE TITLE
win_lgpo unable to find some Administrative Template policies

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#38782]
### Description of Issue/Question
the win_lgpo module is unable to "find" some administrative template policies by their "long name" (i.e. how they appear in the gpedit.msc gui).  The issue occurs b/c the text field in the ADML xml file has trailing spaces, which keeps xpath searches for the name from matching properly.  (see #38100 for additional details)

An example policy of this is the "Show first sign-in animation", whose ADML text entry looks like:
```
<string id="EnableFirstLogonAnimation">Show first sign-in animation </string>
```

### Setup
```
DisableSignInAnimation:
    lgpo.set:
      - name: Show first sign-in animation
      - setting: Disabled
      - policy_class: machine
      - adml_language: en-US
```

### Steps to Reproduce Issue
Attempt setting a policy that has a trailing space in the full text name (for example the policy "Show first sign-in animation")

State will return an error similar to:
```
          ID: DisableSignInAnimation
    Function: lgpo.set
      Result: False
     Comment: Unable to find Machine policy Show first sign-in animation
     Started: 12:40:57.193000
    Duration: 16438.0 ms
     Changes:
```

### Versions Report
salt-stack 2016.11
