### ISSUE TITLE
How to set the mine data ID when using module.run mine.send in a state

### ISSUE THREAD

**Issue by p-thurner** [saltstack/salt#38800]
### Description of Issue/Question

When setting up mine data via `mine_functions` in pillars like so:

/srv/pillar/test.sls
```
mine_functions:
  foobar:
    mine_function: cmd.run
    cmd: 'echo teststring'
    python_shell: True
```

This will run `echo teststring` via cmd.run. I am then able to retreive it using (depending on mine / pillar setup)

```
salt 'master' mine.get 'minion' foobar
```

Now the key here is that I say `salt 'master' mine.get 'minion' foobar` and not `salt 'master' mine.get 'minion' cmd.run`. I want to do that too in a state.

### Setup
/srv/salt/test.sls
```
state_mine_test:
 module.run:
    - name: mine.send
    - func: cmd.run
    - kwargs:
        cmd: echo foobar
```

The docs don't specify what to use here. I read through modules/mine.py - it seems to me that in the code https://github.com/saltstack/salt/blob/develop/salt/modules/mine.py#L201 there is no option given for what I'm looking for, it will always take the `__opts__['id']`, which seems to resolve back to `cmd.run` from above.

Is this feature missing or did I missunderstand something?

### Steps to Reproduce Issue
Setup pillar and state files as above.

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6 
```
