### ISSUE TITLE
Could not LazyLoad slack.start: 'slack' __virtual__ returned False

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#38818]
### Description of Issue/Question
Hi,
I would configure slack engine, but I did not understand the steps. I've only added config lines to master config file.
Can someone help me?

### Setup

```
engines:
  - slack:
      token: 'xoxb-xxxxxxxxxx-xxxxxxxxxxxxxxxxxx'
      control: True
      valid_users:
        - blablabla
      valid_commands:
        - test.ping
        - cmd.run
        - list_jobs
        - list_commands
```

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.14.32-xxxx-grs-ipv6-64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

Thanks
