### ISSUE TITLE
file.managed with S3 Source errors out with obscure message

### ISSUE THREAD

**Issue by toanctruong** [saltstack/salt#38836]
### Description of Issue/Question

I have a simple state to download a binary file into my home directory from S3. I have an IAM role for my EC2 instance that provides full access to the S3 bucket. Manually running `salt-call s3.get mys3bucket /infrastructure/atlassian/atlassian-servicedesk-3.2.6-x64.bin` works just fine. Tried Googling for `Exception: 'FSClient' object has no attribute 'utils'` and I couldn't find anything useful.

### Setup

Currently running masterless with GitFS Backend 
```
[root@amznlinux gitfs]# cat /etc/salt/minion.d/0.conf
master: localhost
file_client: local
fileserver_backend:
  - git
gitfs_provider: gitpython
gitfs_remotes:
  - git@github.com:myprivaterepo/repo.git
gitfs_root: srv/salt
pillar_roots:
  base:
    - /srv/pillars/dev
minion_data_cache: False
```
```
jira_sd_binary:
  file.managed:
    - source: s3://mys3bucket/infrastructure/atlassian/atlassian-servicedesk-3.2.6-x64.bin
    - name: /home/ec2-user/atlassian-servicedesk-3.2.6-x64.bin
    - skip_verify: true
    - unless: ls /home/ec2-user/atlassian-servicedesk-3.2.6-x64.bin
    - order: 1
```

### Steps to Reproduce Issue
```
[root@amznlinux gitfs]# salt-call state.highstate
[ERROR   ] Failed to cache s3://mys3bucket/infrastructure/atlassian/atlassian-servicedesk-3.2.6-x64.bin: Could not fetch from s3://mys3bucket/infrastructure/atlassian/atlassian-servicedesk-3.2.6-x64.bin. Exception: 'FSClient' object has no attribute 'utils'

local:
----------
          ID: jira_sd_binary
    Function: file.managed
        Name: /home/ec2-user/atlassian-servicedesk-3.2.6-x64.bin
      Result: False
     Comment: Failed to cache s3://mys3bucket/infrastructure/atlassian/atlassian-servicedesk-3.2.6-x64.bin: Could not fetch from s3://mys3bucket/infrastructure/atlassian/atlassian-servicedesk-3.2.6-x64.bin. Exception: 'FSClient' object has no attribute 'utils'
     Started: 00:34:33.112108
    Duration: 10.059 ms
     Changes:
```
### Versions Report
```
[root@amznlinux tmp]# salt-call --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Sep  1 2016, 22:14:00)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 4.4.30-32.54.amzn1.x86_64
         system: Linux
        version: Not Installed

```
