### ISSUE TITLE
Failing to remove nginx

### ISSUE THREAD

**Issue by Zorlin** [saltstack/salt#38838]
### Description of Issue/Question
Hi there,

I am playing with SaltStack, trying to get a feel for everything. I've ran into what I think could possibly be a bug - removing nginx does not work correctly. All involved machines are running fully updated Ubuntu 16.04 and all packages are current. For what it's worth, the salt minions are all running as VMware virtual machines with 4GB of RAM each. None of the minions have any extra apt repos besides SaltStack (no DotDeb or anything like that).

### Setup
This is my top.sls file:
```
base:
  '*':
    - core
```

This is my core/init.sls file:
```
remove-things:
  pkg.removed:
    - name: nginx
```

### Steps to Reproduce Issue
- Install nginx on minion
- On master, run sudo salt 'vm1' state.apply core
- First result:
```
vm1:
----------
          ID: remove-things
    Function: pkg.removed
        Name: nginx
      Result: False
     Comment: The following packages failed to remove: nginx.
     Started: 21:21:08.401320
    Duration: 1315.336 ms
     Changes:
              ----------
              nginx:
                  ----------
                  new:
                      1
                  old:
                      1.10.0-0ubuntu0.16.04.4

```

It does succeed at removing the nginx package, but claims to have failed.

Now, run it again:
- On master, run sudo salt 'vm1' state.apply core
```

vm1:
----------
          ID: remove-things
    Function: pkg.removed
        Name: nginx
      Result: False
     Comment: The following packages failed to remove: nginx.
     Started: 21:22:14.792268
    Duration: 977.843 ms
     Changes:

```

The exact same process does NOT fail with simple packages like "sl" and "cowsay".

### Versions Report
```
root@nebula:/srv/salt# salt --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-59-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
