### ISSUE TITLE
tarfile library fails to list/extract some tar files

### ISSUE THREAD

**Issue by robthralls** [saltstack/salt#38837]
### Description of Issue/Question
The tarfile library used in the archive state/module fails in unexpected ways on some tar archives, but they extract just fine using system commands. In at least one case, some files/directories were extracted but not others, even though the archive.extracted state returned success.

I've run into this repeatedly over the last year or so, but unfortunately haven't kept any real notes about it because I don't actually use the archive state/module directly. I keep finding reasons to use system commands instead.

This might also be a Red Hat issue. I only have EL6 systems available at the moment to play with.

From my limited perspective, it seems like tarfile should only be used as a fall-back option for systems without a native tar, but judging from the existence of archive.zip and archive.cmd_zip, there's probably been some debate about that already. If this is confirmed as an issue, though, I think it would be good to at least trigger a warning of some sort. Perhaps a new use_cmd_tar option on the archive.extracted state, moving archive.tar to archive.cmd_tar, and creating a new archive.tar that uses tarfile might make sense?

### Setup
I ran into the issue again today after updating to the latest salt packages. I think an archive.list call was added to the archive.extracted state at some point, which causes my usual workaround (an "ugly hack" custom renderer) to fail.

Specifically, I was provisioning a new Atlassian Crowd server (v2.11.0, [download page](https://www.atlassian.com/software/crowd/download), [direct download](https://www.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.11.0.tar.gz)). Atlassian sticks out in my mind as being a repeat offender on these "broken" tar files, in fact I think the incomplete extraction example was actually one of their JIRA tar files, but I don't think they're alone, either.

```
#!jinja|yaml

crowd_tmpdir:
  file.directory:
    - name: /tmp/crowd

crowd_extract:
  archive.extracted:
    - name: /tmp/crowd
    - source: /tmp/atlassian-crowd-2.11.0.tar.gz
    - source_hash: 'sha256=2829546939aa6772dab65958d518a64631f4ec1ad8d4d9eda39c11e3ab12e35f'
    - archive_format: tar
    - require:
      - file: crowd_tmpdir
```

### Steps to Reproduce Issue
```
$ sudo salt-call state.sls test
[ERROR   ] Unable to list contents of /var/cache/salt/minion/files/base/_tmp_atlassian-crowd-2.11.0.tar.gz. If this is an XZ-compressed tar archive, install XZ Utils to enable listing its contents. If it is compressed using something other than XZ, it may be necessary to specify CLI options to decompress the archive. See the documentation for details. Additional info follows:

archive location:
    /var/cache/salt/minion/files/base/_tmp_atlassian-crowd-2.11.0.tar.gz

If the source archive is a tar archive compressed using a compression type not natively supported by the tar command, then setting the 'list_options' argument may allow the contents to be listed. Otherwise, if Salt is unable to determine the files/directories in the archive, the following workaround(s) would need to be used for this state to proceed (assuming the source file is a valid tar archive):

- 'if_missing' must be set
local:
----------
          ID: crowd_tmpdir
    Function: file.directory
        Name: /tmp/crowd
      Result: True
     Comment: Directory /tmp/crowd is in the correct state
     Started: 22:57:30.580238
    Duration: 11.392 ms
     Changes:   
----------
          ID: crowd_extract
    Function: archive.extracted
        Name: /tmp/crowd
      Result: False
     Comment: Unable to list contents of /var/cache/salt/minion/files/base/_tmp_atlassian-crowd-2.11.0.tar.gz. If this is an XZ-compressed tar archive, install XZ Utils to enable listing its contents. If it is compressed using something other than XZ, it may be necessary to specify CLI options to decompress the archive. See the documentation for details. Additional info follows:
              
              archive location:
                  /var/cache/salt/minion/files/base/_tmp_atlassian-crowd-2.11.0.tar.gz
              
              If the source archive is a tar archive compressed using a compression type not natively supported by the tar command, then setting the 'list_options' argument may allow the contents to be listed. Otherwise, if Salt is unable to determine the files/directories in the archive, the following workaround(s) would need to be used for this state to proceed (assuming the source file is a valid tar archive):
              
              - 'if_missing' must be set
     Started: 22:57:30.592976
    Duration: 109.716 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time: 121.108 ms
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.13.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by gtmanfred** [comment]
Thanks for reporting this, I believe that this is a known issue.

If you pass the options: argument, it will use the tar command on the archive, instead of tarfile.

I was able to get the tarball to extract by setting the `list_options: zcat` so that the gzip portion is removed and then passed to the `tar tf -` command for listing.

Once that is done, it is able to extract the tarball.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
This state works.

```
#!jinja|yaml

crowd_tmpdir:
  file.directory:
    - name: /tmp/crowd

crowd_extract:
  archive.extracted:
    - name: /tmp/crowd
    - source: https://www.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.11.0.tar.gz
    - source_hash: 'sha256=2829546939aa6772dab65958d518a64631f4ec1ad8d4d9eda39c11e3ab12e35f'
    - list_options: zcat
    - options: xz
    - require:
      - file: crowd_tmpdi
```

**Comment by gtmanfred** [comment]
@terminalmage do you have anything to add to this, or is this the suggested use case?

Thanks,
Daniel

**Comment by terminalmage** [comment]
@gtmanfred Yes, your solution is the intended use case. I downloaded the tar archive and attempted to open it using the ``tarfile`` module, and it failed to do so, complaining of an invalid header. This is actually the first time I have ever seen this, so in my opinion this should be considered an edge case (or even a corner case). Especially so since the error message given by the state tells you _exactly_ what needs to be done to rectify the issue.

**Comment by terminalmage** [comment]
I see no reason to alter the default behavior of using ``tarfile`` as a first-resort.

**Comment by gtmanfred** [comment]
Sounds good, thanks for the input @terminalmage

**Comment by EvaSDK** [comment]
Having the same problem with Atlassian Confluence archive. Thanks very much for the workaround.
Note that for some reason the Atlassian Jira Software archive does not suffer this problem.

**Comment by EvaSDK** [comment]
Actually for some reason, the fix working for 2016.3 but I cannot get it to work with 2016.11 using `list_options: zcat` and `options: xz`, I'm just doing to redo the archive for now.

**Comment by eshcheglov** [comment]
Same issue using 2017.7.2 (Nitrogen).

```
activemq-download:
  archive.extracted:
    - name: /opt/
    - source: http://archive.apache.org/dist/activemq/5.15.2/apache-activemq-5.15.2-bin.tar.gz
    - source_hash: a8ba99124df7bbd22b22d568d2cfbe4fb3feb310bd81a282dea0aa9d141c9548
    - if_missing: /opt/activemq
    - trim_output: True
    - options: xz
    - list_options: zcat
```

```
          ID: activemq-download
    Function: archive.extracted
        Name: /opt/
      Result: False
     Comment: Unable to list contents of /var/cache/salt/minion/files/base/_dist_activemq_5.15.2_apache-activemq-5.15.2-bin.tar.gz. If this is an XZ-compressed tar archive, install XZ Utils to enable listing its contents. If it is compressed using something other than XZ, it may be necessary to specify CLI options to decompress the archive. See the documentation for details. Additional info follows:
              
              archive location:
                  /var/cache/salt/minion/files/base/_dist_activemq_5.15.2_apache-activemq-5.15.2-bin.tar.gz
     Started: 16:40:53.147850
    Duration: 2544.387 ms
```

I've tried the "list_options: tar -ztvf" also, it works from CLI, but produce the same error in Salt. It's really weird
