### ISSUE TITLE
pkgin disallowed on MacOS but is supported by pkgsrc

### ISSUE THREAD

**Issue by mattwillsher** [saltstack/salt#38896]
### Description of Issue/Question

pkgin is use by pkgsrc to installed packages on a variety of operations systems. In the pkgin module a check is hardcoded that stops the module loading if it doesn't match one of the listed items

https://github.com/saltstack/salt/blob/2016.11/salt/modules/pkgin.py#L89

MacOS can run pkgin (https://pkgsrc.joyent.com) and is very close to the SmartOS version.

### Setup

/etc/salt/minion:
```yaml
providers:
  pkg: pkgin
```

state file:

```yaml
utility_packages:
  pkg.installed:
    - pkgs: {{ salt['pillar.get']('utility_packages') }}
```

where utility_packages is a simple list of pkgsrc packages.

running salt-call still tries to use the homebrew module to install packages.

### Steps to Reproduce Issue
Log outout to:

salt-call state.apply
```
[ERROR   ] Command 'brew install git fish gpg ncdu py27-boto keybase htop-osx zsh apg' failed with return code: 1
[ERROR   ] stdout: ==> Searching for similarly named formulae...
...
 [TRACE   ] Error loading module.pkgin: The pkgin execution module cannot be loaded: only available on NetBSD, SunOS, DragonFly, Minix, Darwin, SmartOS systems.
```

### Versions Report
```
 salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 17 2017, 20:03:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
 
System Versions:
           dist:   
        machine: x86_64
        release: 16.3.0
         system: Darwin
        version: 10.12.2 x86_64
 
```
