### ISSUE TITLE
Can't use pip.installed in a virtualenv: Could not find a `pip` binary

### ISSUE THREAD

**Issue by daks** [saltstack/salt#38915]
### Description of Issue/Question

With a simple state which installs (with pkg.installed) python-pip, python-virtualenv, and then creates a virtualenv, I can't install with pip.installed in the virtualenv. I always got this error "Could not find a `pip` binary"

### Setup
Running on Debian Wheezy 64, with salt-minion version 2016.11.1+ds-1

Testing on a Vagrant box with Salt masterless.

My state is
```
python-pip_pkg:
  pkg.installed:
    - name: python-pip

virtualenv_pkg:
  pkg.installed:
    - name: python-virtualenv

pip_pkg:
  pkg.installed:
    - name: python-pip

spotter_virtualenv:
  virtualenv.managed:
    - name: /opt/spotter/.venv
    - system_site_packages: False
    - require:
      - pkg: virtualenv_pkg

spotter_pip:
  pip.installed:
    - name: spotter
    - bin_env: spotter_virtualenv
    - require:
      - virtualenv: spotter_virtualenv
      - pkg: pip_pkg
```

### Steps to Reproduce Issue

```
# salt-call state.highstate
[ERROR   ] Error installing 'spotter': Could not find a `pip` binary
local:
----------
          ID: python-pip_pkg
    Function: pkg.installed
        Name: python-pip
      Result: True
     Comment: Package python-pip is already installed
     Started: 14:58:47.782399
    Duration: 220.502 ms
     Changes:   
----------
          ID: virtualenv_pkg
    Function: pkg.installed
        Name: python-virtualenv
      Result: True
     Comment: Package python-virtualenv is already installed
     Started: 14:58:48.003034
    Duration: 4.112 ms
     Changes:   
----------
          ID: pip_pkg
    Function: pkg.installed
        Name: python-pip
      Result: True
     Comment: Package python-pip is already installed
     Started: 14:58:48.007238
    Duration: 3.748 ms
     Changes:   
----------
          ID: spotter_virtualenv
    Function: virtualenv.managed
        Name: /opt/spotter/.venv
      Result: True
     Comment: virtualenv exists
     Started: 14:58:48.012039
    Duration: 0.365 ms
     Changes:   
----------
          ID: spotter_pip
    Function: pip.installed
        Name: spotter
      Result: False
     Comment: Error installing 'spotter': Could not find a `pip` binary
     Started: 14:58:48.244130
    Duration: 3.711 ms
     Changes:   

Summary for local
------------
Succeeded: 4
Failed:    1
------------
Total states run:     5
Total run time: 232.438 ms
```

If I remove
```
- bin_env: spotter_virtualenv
```

It works

### Versions Report
```
# salt-call --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 21 2016, 18:38:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 7.11
        machine: x86_64
        release: 3.2.0-4-amd64
         system: Linux
        version: debian 7.11

```
