### ISSUE TITLE
ssh_auth.present returns True and does nothing

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#38930]
### Description of Issue/Question

When I run the state below, the specified SSH key is not set up for the `root` user, while the state returns a `True` status.

### Setup
`/srv/salt/test.sls`
```
{% set user = 'root' %}
{% set user_home = salt['user.info'](user).get('home', '/home/' + user) %}

ssh_authorized_keys_test:
  ssh_auth.present:
    - name: 'command="/usr/bin/echo foobar" ssh-rsa ABCDEFG peter@example.com'
    - user: {{ user }}
    - config: {{ user_home }}/.ssh/authorized_keys

ssh_test_show_home:
  cmd.run:
    - name: echo {{ user_home }}
```

### Steps to Reproduce Issue
```
# salt 'minion' state.sls test

minion:
----------
          ID: ssh_authorized_keys_test
    Function: ssh_auth.present
        Name: command="/usr/bin/echo foobar" ssh-rsa ABCDEFG peter@example.com
      Result: True
     Comment: 
     Started: 06:37:29.122566
    Duration: 1.836 ms
     Changes:   
----------
          ID: ssh_test_show_home
    Function: cmd.run
        Name: echo /root
      Result: True
     Comment: Command "echo /root" run
     Started: 06:37:29.124914
    Duration: 6.266 ms
     Changes:   
              ----------
              pid:
                  10937
              retcode:
                  0
              stderr:
              stdout:
                  /root

# grep peter /root/.ssh/authorized_keys 
#
```

The public key should be set up in `/root/.ssh/authorized_keys`, but it is not present.

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```

**Comment by p-thurner** [comment]
Using this also doesn't work for me:
```
ssh_authorized_keys_test:
  ssh_auth.present:
    - names:
      - 'ssh-rsa asdfdsafdsafsafsafdsf foo@bar.com'
    - user: {{ user }}
    - config: {{ user_home }}/.ssh/authorized_keys
```

**Comment by gtmanfred** [comment]
Hrm, I am not sure why that is returning a True, it should definitely return a false, but I have been able to get a fake ssh_auth added using a state that looks like the following.

```
root:
  ssh_auth.present:
    - user: root
    - config: '%h/.ssh/authorized_keys'
    - names:
      - AAAAB3NzaC1kc3MAAACBAL0sQ9fJ5bYTEyY==
    - enc: ssh-rsa
    - comment: peter@example.com
    - options:
      - command="/usr/bin/echo foobar"
```

I am tagging this as a bug.

Thanks,
Daniel

**Comment by mchugh19** [comment]
Is this resolved? I'm unable to replicate:
```
{% set user = "vagrant" %}
{% set user_home = salt['user.info'](user).get("home") %}

ssh_authorized_keys_test:
  ssh_auth.present:
    - names:
      - 'command="/usr/bin/echo foobar" ssh-rsa MIIEpAIBAAKCAQEAyexKBZe2FKooe8FX8JHsOCD2i+SP1wt6UhBU/wM0FpGyXFVuUeJmJezjLPWgjyDGmB1B1vsx1i38c67Y95TaeiiY5YtebdnTDPmxD+V5k8Zw3zWOYZ39XjgFZqTE07dDJBIGIYXpCm6DZXW3DC3UPbQrrqpp2bGCtVQaEXbtf5zOoRyNF0RSDNGwEM3gNunx8LBb+rVvB5mI66JeajjJnULQBgVWDJvzOMwXEz8Nx4sv4I8lxNze47C3Q2BocVkdhQOT9JNqvxQxdrZzbbxUIa/8wNIilHVlduA6++lX0y30lMEdVG3bQRQtIJi5EPttRTfoN5egxLo2w0bQQaQZOQIDAQABAoIBAQCzH4qWpXufn0bkaaJyRXBwZkVv2eUD1im/jL9prVTSxJKduCdyOk11TUxFwOuarG+f1yxl4lXWctrlYHEWSBT7kvH3hwfQmQ/RDdtVh7KvNbVBPQg+bmGp6DZaVMZKLeNAp0CLEniliV3EboVgJ3OE/URW4NOfiwmxg5bQcVjD/yhJU/Jy1LR3SU39ZnEJ3VpFfe2dd1vn8wca8B7pF2MfA66efs08P3cbybgdVvEpcGXEV2r/JwVru4/irrLed3E6ghthkXTyOozyNbyqGBHqb2GGwiYmj8lmUk/7hAotI1jiX4JoAoIj0bmwFDrF54VoeKUMlZvBrMJTDJ80gMaBAoGBAPpWdo9ebCGXC4TIl0EHxRDU2nrFGNBEr3miMU7eMWcjctowzmi9ROJnR3lsERUZodo1ly4DgccVGmNtPv1qz9nSq8sA+0CpfDeAKZo6D3ZgGala4wdy2WJiaw2/KKtlpLJ2pPCybdnxgOk0nB1r2SfqExaH2WEa+Td7W3ud1EqpAoGBAM59fSsRtEqiRFjYZEh2YEIrQnnH42Bqs5FHkbeKNFwnusXUqYtICUPW5BPQO24sYhsGTY83XLzCVklGqltSgs013KhmENCoQVfjdD4rAHJs+qhAPO1yhsQNvmq/wgJWV1iBdSi4ZoPzANrODqh8GOzwuzFQXyEnuC59lEiDLIQRAoGBAOR8Fio03CysV+8Rxjusg8kg/WggjM1KY3548tgxJJYmXKWY9kvStBSQf0PrxoujoX4we5Obz8+NC1DEXUGfQ6ZkCjh25NvX1XAyocYKSCKbA9D3C0+5G4AYo+0gFFabpv7cGx81O9439pjjU7nmvYUYt+NQiq9+lwh0psLlAuZBAoGANu4XEBADoB8Og3v9IXGsJa4QXwkXqZx47FrXnrW7PBCtlNb/yzd8j3lo7wRj6ukPqBTDKSgXGXexMIkF5IlMln6PlpSgQIGh8FlnoOobklT/USbVjmz7AMiPMSKV371MOxUlL5HuY4ePYKWULKnmj5FymqnAxLcmPefWPHv4qaECgYA8arMHDtkQT0aqC5wXAglPPczKMg5PDRP2nbSCb1aKN0lhx42Sj7TSJlm/+ssmkz/NHgtSKx0LgbQTeXNvtEWJQetF0JBaHG+Xw7pHv0LXW0y+RCm+NgUw+cpWi1dYPWEYgCwEAj2aG4IOVXbjq1WTE80X3vo8Pn/x9QiG1TcnTQ== foo@bar.com'
    - user: {{ user }}
    - config: {{ user_home }}/.ssh/authorized_keys
```

results in:
```
# grep foo ~vagrant/.ssh/authorized_keys
command="/usr/bin/echo foobar" ssh-rsa MIIEpAIBAAKCAQEAyexKBZe2FKooe8FX8JHsOCD2i+SP1wt6UhBU/wM0FpGyXFVuUeJmJezjLPWgjyDGmB1B1vsx1i38c67Y95TaeiiY5YtebdnTDPmxD+V5k8Zw3zWOYZ39XjgFZqTE07dDJBIGIYXpCm6DZXW3DC3UPbQrrqpp2bGCtVQaEXbtf5zOoRyNF0RSDNGwEM3gNunx8LBb+rVvB5mI66JeajjJnULQBgVWDJvzOMwXEz8Nx4sv4I8lxNze47C3Q2BocVkdhQOT9JNqvxQxdrZzbbxUIa/8wNIilHVlduA6++lX0y30lMEdVG3bQRQtIJi5EPttRTfoN5egxLo2w0bQQaQZOQIDAQABAoIBAQCzH4qWpXufn0bkaaJyRXBwZkVv2eUD1im/jL9prVTSxJKduCdyOk11TUxFwOuarG+f1yxl4lXWctrlYHEWSBT7kvH3hwfQmQ/RDdtVh7KvNbVBPQg+bmGp6DZaVMZKLeNAp0CLEniliV3EboVgJ3OE/URW4NOfiwmxg5bQcVjD/yhJU/Jy1LR3SU39ZnEJ3VpFfe2dd1vn8wca8B7pF2MfA66efs08P3cbybgdVvEpcGXEV2r/JwVru4/irrLed3E6ghthkXTyOozyNbyqGBHqb2GGwiYmj8lmUk/7hAotI1jiX4JoAoIj0bmwFDrF54VoeKUMlZvBrMJTDJ80gMaBAoGBAPpWdo9ebCGXC4TIl0EHxRDU2nrFGNBEr3miMU7eMWcjctowzmi9ROJnR3lsERUZodo1ly4DgccVGmNtPv1qz9nSq8sA+0CpfDeAKZo6D3ZgGala4wdy2WJiaw2/KKtlpLJ2pPCybdnxgOk0nB1r2SfqExaH2WEa+Td7W3ud1EqpAoGBAM59fSsRtEqiRFjYZEh2YEIrQnnH42Bqs5FHkbeKNFwnusXUqYtICUPW5BPQO24sYhsGTY83XLzCVklGqltSgs013KhmENCoQVfjdD4rAHJs+qhAPO1yhsQNvmq/wgJWV1iBdSi4ZoPzANrODqh8GOzwuzFQXyEnuC59lEiDLIQRAoGBAOR8Fio03CysV+8Rxjusg8kg/WggjM1KY3548tgxJJYmXKWY9kvStBSQf0PrxoujoX4we5Obz8+NC1DEXUGfQ6ZkCjh25NvX1XAyocYKSCKbA9D3C0+5G4AYo+0gFFabpv7cGx81O9439pjjU7nmvYUYt+NQiq9+lwh0psLlAuZBAoGANu4XEBADoB8Og3v9IXGsJa4QXwkXqZx47FrXnrW7PBCtlNb/yzd8j3lo7wRj6ukPqBTDKSgXGXexMIkF5IlMln6PlpSgQIGh8FlnoOobklT/USbVjmz7AMiPMSKV371MOxUlL5HuY4ePYKWULKnmj5FymqnAxLcmPefWPHv4qaECgYA8arMHDtkQT0aqC5wXAglPPczKMg5PDRP2nbSCb1aKN0lhx42Sj7TSJlm/+ssmkz/NHgtSKx0LgbQTeXNvtEWJQetF0JBaHG+Xw7pHv0LXW0y+RCm+NgUw+cpWi1dYPWEYgCwEAj2aG4IOVXbjq1WTE80X3vo8Pn/x9QiG1TcnTQ== foo@bar.com
```
