### ISSUE TITLE
Requisites were not found... but are being set on the minion.

### ISSUE THREAD

**Issue by unassassinable** [saltstack/salt#38954]
My init.sls looks like so:
```
{% set location = grains['office'] %}
{% if 'Draper' in location %}
{% set cluster = 'es_cluster_draper_ut' %}
{% endif %}

# Install the core elastic stack component depending on the role
java-1.8.0-openjdk:
  pkg.installed

elasticsearch:
  pkg.installed:
    - name: elasticsearch
    - require:
      - pkg: java-1.8.0-openjdk
  service:
    - running
    - enable: True
    - restart: True
    - watch:
      - file: /etc/elasticsearch/elasticsearch.yml
      - file: /etc/systemd/system/elasticsearch.services.d/elasticsearch.conf

# elasticsearch configuration file
/etc/elasticsearch/elasticsearch.yml:
  file.managed:
    - context:
      cluster: {{ cluster }}
    - user: root
    - group: root
    - mode: 644
    - template: jinja
    - source: salt://configure-elasticsearch/elasticsearch.yml.jinja

# Add ES_HEAP_SIZE to top of /usr/share/elasticsearch/bin/elasticsearch.in.sh to increase java heap
# Rule of thumb - Half of total memory if node is only running elasticsearch
/usr/share/elasticsearch/bin/elasticsearch.in.sh:
  file.managed:
    - source: salt://configure-elasticsearch/elasticsearch.in.sh.jinja
    - template: jinja

# This file allows us to disable swapping, speeding things up
/etc/systemd/system/elasticsearch.service.d/elasticsearch.conf:
  file.managed:
    - makedirs: True
    - source: salt://configure-elasticsearch/systemd/elasticsearch.conf
```

When I salt the minion:
`salt 'servername' state.sls configure-elasticsearch test=true`

I get the following error:
```
----------
          ID: elasticsearch
    Function: service.running
      Result: False
     Comment: The following requisites were not found:
                                 watch:
                                     file: /etc/systemd/system/elasticsearch.services.d/elasticsearch.conf
     Changes:
```

However, the file /etc/systemd/system/elasticsearch.services.d/elasticsearch.conf does correctly get copied over to the minion, and if I manually start the service, I get the expected results.
