### ISSUE TITLE
`mine.get` runner does not work when `tgt_type` is `nodegroup`

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38963]
### Description of Issue/Question

This might be related to proxy minions only - didn't check yet on straight minions.

```bash
$ sudo salt-run mine.get 'arista-edges' 'bgp.neighbors' tgt_type='nodegroup'
```
But it does work with `glob`, `compound` or `list`.

### Setup

A proxy minion, having `mine_functions` enabled. In this example `bgp.neighbors` was cached, but can be anything else.

### Steps to Reproduce Issue

In the proxy minion config, append:

```yaml
mine_functions:
  bgp.neighbors: []
mine_interval: 5
```

Or any other function.

In the master config, configure a nodegroup. I have the following hierarchy:

```yaml
nodegroups:
   eos: 'G@os:eos'
   eos-edges: 'edge* and N@eos'
   arista-edges: 'N@eos-edges'
```

With `eos-edges` does not work either, but calling:

```bash
$ sudo salt-run mine.get 'edge* and G@os:eos' 'bgp.neighbors' tgt_type='compound'
```

It works fine.

### Traceback

```python
[ERROR   ] Failed matching available minions with nodegroup pattern: arista-edges
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 639, in check_minions
    minions = check_func(expr, greedy)
TypeError: 'NoneType' object is not callable
```

### Versions Report

```yaml
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 10.0.0
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.4
```
