### ISSUE TITLE
pillar list includes a unicode character in strings

### ISSUE THREAD

**Issue by porunov** [saltstack/salt#38983]
### Description of Issue/Question

Hello,

I found out that when we get a pillar list in a state file and import the list it will include unicode character (i.e. `u` and quotes). I will be happy if you can fix it.

Best regards,
Alexandr

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Pillar data:
```
zookeper:
  nodes:
    - 192.168.0.101
    - 192.168.0.102
    - 192.168.0.103
```

settings.sls file:
```
{%- do zk.update( { 'zookeeper_nodes_after_loop':  salt['pillar.get']('zookeeper:nodes', []) } ) %}
```

server.sls file:
```
{%- from 'zookeeper/settings.sls' import zk with context -%}
zoo-cfg:
  file.managed:
    - name: /path/to/zoo.cfg
    - source: salt://zookeeper/conf/zoo.cfg
    - template: jinja
    - context:
      zookeeper_nodes: {{ zk.zookeeper_nodes_after_loop }}

```

zookeeper/conf/zoo.cfg file:
```
{{ zookeeper_nodes }}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Run server.sls state and you will get a file `/path/to/zoo.cfg` with the next content:
```
["u'192.168.0.101'", "u'192.168.0.102'", "u'192.168.0.103'"]
```

Expected behavior to have next content:
```
["192.168.0.101", "192.168.0.102", "192.168.0.103"]
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.5
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
