### ISSUE TITLE
`saltutil.sync_all`: ERROR: Path 'top.sls' is not absolute

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38988]
### Description of Issue/Question

As modules keep disappearing as discussed in https://github.com/saltstack/salt/issues/35443, when it happens, there's a runner executing `saltutil.sync_all`.

However, today it failed and I did it manually.
Having the same configuration as always, I got the errors below:

```bash
$ sudo salt 'edge*' saltutil.sync_all
edge01.yvr01:
    ERROR: Path 'top.sls' is not absolute
edge01.bjm01:
    ERROR: Path 'top.sls' is not absolute
edge01.per01:
    ERROR: Path 'top.sls' is not absolute
edge01.flw01:
    ERROR: Path 'top.sls' is not absolute
```

As this was a production environment, I had to remediate the problem quickly and restart the proxy processes. After the restart, I run again `saltutil.sync_all` and the error did not appear anymore, everything came back to normal.

The `top.sls` file is under `/etc/salt/pillar/top.sls`.
In the master:

```yaml
pillar_roots:
  base:
    - /etc/salt/pillar
    - /etc/salt/proxy-master/pillar
```

The log level on the master was set to `warning` and I did not see anything related.
Same level on the proxy, all I was able to see:

```
2017-01-27 09:51:59,394 [salt.minion      ][ERROR   ][29299] A command in 'saltutil.sync_all' had a problem: Path 'top.sls' is not absolute
2017-01-27 09:52:00,090 [salt.minion      ][ERROR   ][29483] A command in 'saltutil.sync_all' had a problem: Path 'top.sls' is not absolute
```

I'm wondering how this and https://github.com/saltstack/salt/issues/35443 are related and why after the restart did not complain anymore about `Path 'top.sls' is not absolute`? 

### Salt Version

```yaml
$ sudo salt --versions-report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 10.0.0
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.4
```

Thanks,
Mircea

**Comment by gtmanfred** [comment]
Thanks for reporting this Mircea,  Unfortunately I am unable to reproduce it.  I am using the rest_sample proxy, and have made a custom module, but no dice.

I am going to leave it open because i think that you might be right that it is related to the other issue.  I am going to leave my proxy minion running over the weekend and see if something like this shows up as well.

If you come across a way to reliably replicate this, we would love to get it fixed.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
I did find this really old issue that we were also never able to replicate https://github.com/saltstack/salt/issues/17286 that seems like it might have been similar.

**Comment by mirceaulinic** [comment]
Hi @gtmanfred - yes, that's an obscure bug and I saw it for the very first time after running proxy minions for one year.

It is also problematic that I didn't have much logs. I apologise, but I really had to fix the environment as soon as possible.
At the same time, do you have any idea where it could this error come from? The error message seems to be raised in: https://github.com/saltstack/salt/blob/2016.11/salt/fileclient.py#L476-L478
My understanding is that `url_path` should have been expanded in https://github.com/saltstack/salt/blob/2016.11/salt/fileclient.py#L466-L467 as `/etc/salt/pillar/top.sls` but instead it was just `top.sls`. Does this sound sane?

I will try to replicate it in the lab, but I guess it's not quite trivial.
 I'd keep this issue open and I'll update it in case I hit this error again.

**Comment by gtmanfred** [comment]
Yup, you are correct somewhere it is not expanding that top.sls to be the full path of /etc/salt/pillar/top.sls, we will just need to track it down.  If you run across it in your testing environment, with the log level set to debug it should give a stacktrace which would show us the path that the config traveled thru and was not expanded.

Thanks for you help!
Daniel

**Comment by mirceaulinic** [comment]
It happened today to see it again, whilst debugging a different problem. This is the traceback I caught:

```python
[ERROR   ] Unhandled exception running saltutil.sync_all
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 844, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 656, in sync_all
    ret['beacons'] = sync_beacons(saltenv, False)
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 206, in sync_beacons
    ret = _sync('beacons', saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 98, in _sync
    saltenv = _get_top_file_envs()
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 80, in _get_top_file_envs
    top = st_.get_top()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2870, in get_top
    tops = self.get_tops()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2570, in get_tops
    saltenv
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 189, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 485, in get_url
    'Path \'{0}\' is not absolute'.format(url_path)
CommandExecutionError: Path 'top.sls' is not absolute
```

This is on 2016.11.4.

**Comment by mirceaulinic** [comment]
Another note that might help: this is not during the init, this is after the minion has been successfully  started and executed commands etc.
Looking more into the error, `top = st_.get_top()`, while the `st` object is built as `st_ = salt.state.HighState(__opts__, minitial_pillar=__pillar__)` sot it relies on the opts and pillar.

With proxy minions there's another problem, as some modules disappear -- see https://github.com/saltstack/salt/issues/35443#issuecomment-274974181, which can be because of two reason:

- the underlying third party library becomes suddenly unavailable to be imported (I believe this is a very small chance)
- the `proxy` key no longer available in the `__opts__` (the `proxy` key is defined in the pillar.).

Given the situation above, I'm questioning whether there's a slight possibility that the opts or the pillar data are lost somehow.
At the same time, when the modules disappeared, I checked the what's inside the `__opts__` using the `test.get_opts` function, but it looked fine. It is true that I didn't check immediately when the modules disappeared.

So perhaps there's a problem when pillar/opts data is lost, the top is unreachable the modules then disappear, but when the data is refreshed the modules are not refreshed anymore

In the other thread, @cro stated:

> Since all the module execution on the minion occurs in the same process and it never forks like minions with multiprocessing: True there is much more of a chance that the proxy will step on itself. I need to think about this some more and devise a better way of ferreting out what exactly is going on.

*Maybe* the proxy steps on itself in terms of pillar / opts?

Any input would be greatly appreciated, thanks!

**Comment by gtmanfred** [comment]
Thanks for the analysis @mirceaulinic 

@saltstack/team-core does anyone have any idea what is going on here?  It looks like this may have also been hit at some point in the past here #17286

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
I created an attempt for an instrumentation execution module, called `instrumentation`, that has a small function:

```python
def get_top_url(saltenv='base'):
    '''
    Return the top file using the Salt fileserver.
    '''
    client = salt.fileclient.get_file_client(__opts__)
    if __opts__['environment']:
        log.debug('environment set in the opts')
        return client.cache_file(__opts__['state_top'],
                                 __opts__['environment'] )
    return client.cache_file(__opts__['state_top'], saltenv)
```

Executing `instrumentation.get_top_url`, I get the same, with the traceback:

```python
[ERROR   ] A command in 'instrumentation.get_top_url' had a problem: Path 'top.sls' is not absolute
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1445, in _thread_return
    return_data = executor.execute()
  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
    return self.func(*self.args, **self.kwargs)
  File "/var/cache/salt/minion/extmods/modules/instrumentation.py", line 59, in get_top_url
    return client.cache_file(__opts__['state_top'], saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 189, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 485, in get_url
    'Path \'{0}\' is not absolute'.format(url_path)
CommandExecutionError: Path 'top.sls' is not absolute
```

Wondering if the same happens on regular minions, or only on proxy minions?

**Comment by gtmanfred** [comment]
Ok, so I am not sure why the `state_top` option is losing the salt:// header.

If you set state_top to `salt://top.sls` instead of just `top.sls`, this should never be overwritten and just work.

I am not quite sure where this might be overwritten somewhere.

Also, to fix your command, internally for salt, we attach salt:// to the front of __opts__ for the state.HighState object.

For the _get_top_file_env() we initiate the HighState object, and then pull tops from that.

https://github.com/saltstack/salt/blob/2017.7/salt/modules/saltutil.py#L79

Then in the `__gen_opts` we fix it to be an absolute path if it is not referencing the salt fileserver.

https://github.com/saltstack/salt/blob/2017.7/salt/state.py#L2704

Which should then be what is referenced here.

https://github.com/saltstack/salt/blob/2017.7/salt/state.py#L2795

The quick solution would be to just copy the state_top logic into the get_tops function, but I think it would be good to figure out why state_top is getting overwritten... probably somewhere that self.opts is getting updated that I am just not seeing.

**Comment by terminalmage** [comment]
You're asking the fileclient to return `top.sls`, not `salt://top.sls`. When there is no protocol, the fileclient doesn't know whether it needs to make a request to the salt fileserver, a webserver, or whatever, so it assumes the path is a local file on the minion. Only absolute paths are supported when "caching" local files (the minion doesn't actually cache them, just returns back the specified path if it exists), hence the error.

**Comment by mirceaulinic** [comment]
Hey @terminalmage - thanks for this explanation. It certainly makes sense, and I confirm that using `salt://top.sls` works fine.
From your explanation however, I understand that it not having that option configured like that means that `saltutil.sync_all` should always fail. But that's not the case - on the opposite actually: it is something I have noticed _very rarely_, as you can see: I opened this issue in January (when I firstly noticed this), and then several months later, in August. Trying to reproduce this meanwhile wasn't successful although I run `saltutil.sync_all` many other times without failure. What would be explanation?

**Comment by terminalmage** [comment]
@mirceaulinic my guess would be that this is a bug that has since been fixed. As @gtmanfred noted, `__gen_opts()` is where we set the effective `state_top` for the state run.

**Comment by mirceaulinic** [comment]
Fair enough. Thanks @terminalmage.

**Comment by terminalmage** [comment]
@mirceaulinic No problem! I can't _completely_ rule out something else in state.py overwriting it in some way, but from what I can see nothing is doing so. If you see this with newer releases, let me know and we can re-evaluate this.

**Comment by Dejv56** [comment]
I am still experiencing this issue with Salt v3002.2 with Windows minions (about ~500 minions, most of them Win10, about 1/5 of Windows Server 2016 and 2019).

I noticed this error while creating custom grains module for first time and syncing them on minions. The error occurs totally randomly, i run `saltutil.sync_grains` on 10 minions and minion A and B returns this error. When i rerun the same function again, minion C and D return this error.

Salt Master
``` yaml
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.13.2
      cherrypy: 18.3.0
      dateutil: 2.8.2
     docker-py: 4.2.0
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: 0.28.4
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: 1.4.6
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.14.1
        pygit2: 0.28.2
        Python: 3.6.10 (default, Dec 19 2019, 15:48:40) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.1.2
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: sled 15.2
        locale: UTF-8
       machine: x86_64
       release: 5.3.18-24.15-default
        system: Linux
       version: SLED 15.2
```
Salt Minion:
``` yaml
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.12.2
      cherrypy: 17.4.1
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.7
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.4
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 2.0.5
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2019
        system: Windows
       version: 2019 10.0.17763 SP0
```
