### ISSUE TITLE
Regarding Proxy process memory and CPU usage

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38990]
### Description of Issue/Question

I'm afraid the proxy process consumes more than expected (I recall @cro said they would need ~40M of memory), but this is what I constantly see (in the `top`):

```yaml
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20134 root      20   0 1189492  85628  13764 S   0.3  0.1   2:03.23 salt-proxy
20224 root      20   0 1119728  89104  14256 S   0.3  0.1   2:15.44 salt-proxy
20241 root      20   0 1261148 103232  14044 S   0.3  0.1   2:25.58 salt-proxy
20413 root      20   0 1203788 111008  13676 S   0.3  0.1   2:36.26 salt-proxy
20419 root      20   0 1126996  83564  14108 S   0.3  0.1   2:10.13 salt-proxy
20434 root      20   0 1475828 142124  13676 S   0.3  0.1   4:21.18 salt-proxy
20479 root      20   0 1258680  92728  13980 S   0.3  0.1   2:13.64 salt-proxy
20480 root      20   0 1127228  85156  13812 S   0.3  0.1   2:03.96 salt-proxy
20523 root      20   0 1393708  95884  13932 S   0.3  0.1   2:48.58 salt-proxy
```

When doing a `sync_all`, the CPU usage spikes:

```yaml
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20704 root      20   0 1275184 102724  13848 S 108.3  0.1   4:29.43 salt-proxy
20950 root      20   0 1602884 216072  13888 S 105.7  0.2   8:01.68 salt-proxy
21039 root      20   0 1198564 149368  13956 S 103.7  0.1   9:59.86 salt-proxy
20954 root      20   0 1421144 132168  13968 S 103.1  0.1   5:53.28 salt-proxy
21044 root      20   0 1532552 169760  14052 S 103.1  0.1   7:46.55 salt-proxy
21648 root      20   0 1635956 154768  13924 S 103.1  0.1   7:05.68 salt-proxy
20643 root      20   0 1418324 154004  13812 S 102.7  0.1   5:20.54 salt-proxy
```

And the master:

```yaml
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
31491 root      20   0  430928  85244   8976 R  99.7  0.1   0:30.05 salt-master
 9231 root      20   0  431676  86072   8976 R  99.4  0.1   1:00.48 salt-master
```

I'm wondering if this could be a cause of https://github.com/saltstack/salt/issues/35443.

In a separate lab environment having 50 proxy processes started, I managed to replicate the modules disappearing:

```
[DEBUG   ] LazyLoaded localfs.contains
[DEBUG   ] LazyLoaded no_return.output
animal21:
    Minion did not return. [No response]
```

And the proxy is unable to start:

```python
2017-01-27 12:54:30,691 [salt.scripts     ][ERROR   ][7293] Proxy Minion failed to start:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 249, in proxy_minion_process
    proxyminion.start()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 515, in start
    super(ProxyMinion, self).start()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 948, in start
    self.prepare()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 481, in prepare
    if self.check_running():
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 925, in check_running
    pid = self.get_pidfile()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 897, in get_pidfile
    return get_pidfile(self.config['pidfile'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 134, in get_pidfile
    return int(pid)
ValueError: invalid literal for int() with base 10: ''
2017-01-27 12:54:30,692 [salt.scripts     ][WARNING ][7293] ** Restarting proxy minion **
```

Although there's still enough memory:

```yaml
top - 12:55:21 up  2:05,  2 users,  load average: 0.63, 0.78, 3.82
Tasks: 184 total,   1 running, 183 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.9 us,  0.5 sy,  0.0 ni, 95.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.2 st
KiB Mem:   4057568 total,  3022492 used,  1035076 free,    16348 buffers
KiB Swap:        0 total,        0 used,        0 free.   148144 cached Mem
```

Also, the `sync_all` in 2016.11 is much slower than in 2016.3.

### Salt Version

- production:

```yaml
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 10.0.0
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.4
```

- lab:

```yaml
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Dec 18 2016, 20:19:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```
