### ISSUE TITLE
file.patch state fails needlessly on patched files

### ISSUE THREAD

**Issue by MikeH-Halo** [saltstack/salt#39053]
### Description of Issue/Question

The file.patch state fails on already patched files, unless a hash is given. In some situations giving a hash is impractical (for example when the patch-file is generated using template variables) and patch will return 1 (which is greater than zero). For the case that there is no hash and patch returns 1, we think that letting the file.patch state succeed is reasonable. 
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Standard salt installation on RHEL7.
For example, consider the (templated) patch sitting on the Salt file-server:
```
--- /etc/shells 2016-03-21 12:48:24.199158134 +0100
+++ /tmp/test-{{ index }}.txt 2017-01-31 12:58:27.408669282 +0100
@@ -1,3 +1,4 @@
+## These are {{ name }} shells:
 /bin/sh
 /bin/bash
 /sbin/nologin
```
And the SLS:
```
{% for i,n in [(1,'my'),(2,'your'),(3,'his'),(4,'her'),(5,'its')] %}
/tmp/test-{{i}}.patch:
  file.managed:
    - source: salt://test.patch
    - template: jinja
    - defaults:
        index: {{i}}
        name: {{n}}

Copy /tmp/test-{{i}}.txt:
  file.copy:
    - name: /tmp/test-{{i}}.txt
    - source: /etc/shells

/tmp/test-{{i}}.txt:
  file.patch:
    - source: /tmp/test-{{i}}.patch
    - require:
        - file: Copy /tmp/test-{{i}}.txt
        - file: /tmp/test-{{i}}.patch
{% endfor %}
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

1. Run state.apply to once to generate the target files (/tmp/test-{{i}}.txt) using the templated patch.
1. Run state.apply again. Patch will now fail even though the files have the desired contents.

Error message will look similar to this:
```
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored
```

Exit code will be 1 and state will fail.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
$ salt --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
