### ISSUE TITLE
modules.linux_lvm.fullversion provides incomplete info

### ISSUE THREAD

**Issue by sergeizv** [saltstack/salt#39057]
### Description of Issue/Question

modules.linux_lvm.fullversion doesn't retrieve all the data provided by 'lvm version'

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
```
(salt-test-env) salt-test@tommynaut:~/salt> salt-ssh foo cmd.run 'lvm version'
foo:
      LVM version:     2.02.133(2) (2015-10-30)
      Library version: 1.02.110 (2015-10-30)
      Driver version:  4.34.0
(salt-test-env) salt-test@tommynaut:~/salt> salt-ssh foo lvm.fullversion
foo:
    ----------
    Driver version:
        4.34.0

```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.11.2-32-g92a542f

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: x86_64
        release: 4.9.3-1-default
         system: Linux
        version: Not Installed
```
