### ISSUE TITLE
modules.linux_lvm.pvcreate misbehaves if all submitted devices are already LVM PVs

### ISSUE THREAD

**Issue by sergeizv** [saltstack/salt#39070]
### Description of Issue/Question

If all the devices submitted to modules.linux_lvm.pvcreate are already initialized for use by LVM, the module executes the pvcreate command with no specified devices. On systems with lvm2 package versions prior to 2.02.144 (Ubuntu 16.04, Debian Jessie etc), pvcreate returns non-success return code in such a case and the module fails.

### Steps to Reproduce Issue

Given an Ubuntu 16.04 host (foo)

```
(salt-test-env) salt-test@tommynaut:~/salt> salt-ssh foo cmd.run 'dd if=/dev/zero of=/pvfile bs=1M count=100 && losetup --show --find /pvfile'         
foo:
    100+0 records in
    100+0 records out
    104857600 bytes (105 MB, 100 MiB) copied, 0.626853 s, 167 MB/s
    /dev/loop2
(salt-test-env) salt-test@tommynaut:~/salt> salt-ssh foo lvm.pvcreate /dev/loop2
foo:
    True
(salt-test-env) salt-test@tommynaut:~/salt> salt-ssh foo lvm.pvcreate /dev/loop2
foo:
    ----------
    retcode:
        0
    stderr:
        Error running 'lvm.pvcreate':   Please enter a physical volume path.
          Run `pvcreate --help' for more information.
    stdout:
(salt-test-env) salt-test@tommynaut:~/salt>
```

P.S. 'retcode' in the output of salt-ssh isn't true; the real exit code of pvcreate is 3. But that's another story :)

### Versions Report

```
Salt Version:
           Salt: 2016.11.2-33-g88b171f
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.9.3-1-default
         system: Linux
        version: Not Installed
```
