### ISSUE TITLE
CVMFS fuse mount gets remounted every time

### ISSUE THREAD

**Issue by carsten-AEI** [saltstack/salt#39106]
### Description of Issue/Question
When mounting a cvmfs fuse mount via `mount.mounted` it works fine the first time, but afterwards it gets umounted every time:

```
cvmfs-dir-cms.cern.ch:
  mount.mounted:
    - name: /cvmfs/cms.cern.ch
    - device: cms.cern.ch
    - fstype: cvmfs
    - dump: 0
    - pass_num: 2
    - persist: True
    - opts:
      - noauto
      - x-systemd.automount
```

results in this `/etc/fstab` line
```
cms.cern.ch             /cvmfs/cms.cern.ch      cvmfs   noauto,x-systemd.automount      0 2
```
which is nice and correct, but re-applying this state yields:
```
          ID: cvmfs-dir-cms.cern.ch
    Function: mount.mounted
        Name: /cvmfs/cms.cern.ch
      Result: True
     Comment: Target was successfully mounted. Entry already exists in the fstab.
     Started: 10:48:14.903659
    Duration: 14896.75 ms
     Changes:   
              ----------
              mount:
                  True
              umount:
                  Forced unmount because devices don't match. Wanted: cms.cern.ch, current: cvmfs2, /cvmfs2
```

so far, I have not been able to mitigate this via the invisible/hidden or other knobs of the mounted state - but possibly did not use them correctly. I almost fear that this edge case may need another exceptional handling in `salt/states/mount.py`.

### Versions Report
master/minion:
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
