### ISSUE TITLE
Salt Cloud does not auto-assign IPv6 address in EC2

### ISSUE THREAD

**Issue by sc250024** [saltstack/salt#39117]
### Description of Issue/Question

Greetings,

There are many factors that could influence this, and I'm totally hoping this is an error on my part. Based on some testing, I believe that Salt Cloud as of the latest version (2016.11.2) does not set/enable the "Auto-assign IPv6 IP" flag in Amazon AWS for new EC2 instances placed in an IPv6-enabled subnet.

### Setup

For testing, I decided to use Amazon Linux. The reason is because Amazon has configured that AMI automatically to be IPv6-enabled. You can do so with other AMIs of other OS distributions as Amazon's documentation lists here: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-migrate-ipv6.html#vpc-migrate-ipv6-dhcpv6. However, I wanted to avoid the chances of misconfiguration.

### Steps to Reproduce Issue

1. Create a new VPC, or use an existing one. In the VPC console, go to `Your VPCs` on the left, right click on the VPC you want to use, and select `Edit CIDRs`. One the window pops up, click `Add IPv6 CIDR` to assign an IPv6 range to your VPC.

2. In the new / current VPC, go to the `Subnets` menu on the left, and create a new subnet. In the `IPv6 CIDR block` dropdown, select `Specify a custom IPv6 CIDR` and let Amazon automatically select the next /64 IPv6 block for you (default is fine). Add a corresponding IPv4 subnet block as well, and save it.

3. When the subnet is created, right click on the new subnet, and select `Modify auto-assign IP settings`. Select both `Enable auto-assign public IPv4 address` and `Enable auto-assign IPv6 address`. At this point, newly launched AMIs into this subnet should be IPv6 enabled.

4. I launched an Amazon Linux t2.micro instance (which is flagged as supporting IPv6) using the AWS Launch Wizard into a subnet that's configured to auto assign a public IPv4 address, and an IPv6 address. Both are showing up in the OS, and in the console, so we know it's not a misconfiguration of the subnet settings.

```
[root@ip-10-XX-XX-XX ~]# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:E8:04:07:17:01
          inet addr:10.XX.XX.XX  Bcast:10.XX.XX.127  Mask:255.255.255.192
          inet6 addr: 2600:1XXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX/64 Scope:Global
          inet6 addr: fe80::e8:4ff:fe07:1701/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:3926 errors:0 dropped:0 overruns:0 frame:0
          TX packets:714 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4866363 (4.6 MiB)  TX bytes:69911 (68.2 KiB)
```

5. Using the same AMI, subnet, and instance size, I used SaltCloud to provision an Amazon Linux instance.

Here's the Salt Cloud profile (/etc/salt/cloud.profiles.d/testipv6.conf)
```
amazonlinux_ipv6_test:
  allocate_new_eip: True
  block_device_mappings:
    - DeviceName: /dev/xvda
      Ebs.VolumeType: gp2
      Ebs.VolumeSize: 12
  del_all_vols_on_destroy: True
  del_root_vols_on_destroy: True
  delete_sshkeys: True
  ebs_optimized: False
  image: ami-f173cc91       # Amazon Linux AMI 2016.09.1 (HVM), SSD Volume Type
  provider: <my-saltcloud-aws-provider>
  securitygroupid:
    - sg-b3XXXXXX           # Default security group for IPv6 subnet
  size: t2.micro
  SourceDestCheck: True
  ssh_username: ec2-user
  subnetid: subnet-7cXXXXXX # IPv6 enabled subnet
  sync_after_install: all
```

My provider config file (/etc/salt/cloud.providers.d/amazon-aws.conf)
```
<my-saltcloud-aws-provider>:
  minion:
    master: <salt-master-dns>
  ssh_interface: private_ips
  id: '<ID>'
  key: '<KEY>'
  private_key: /path/to/ssh/private/sshuser-key.pem
  location: us-west-2
  keyname: sshuser-key
  rename_on_destroy: True
  ssh_username:
    - ubuntu
    - ec2-user
    - centos
    - admin
  driver: ec2
```

Default Cloud file (/etc/salt/cloud)
```
delete_sshkeys: True
keysize: 2048
log_datefmt: '%Y-%m-%d %H:%M:%S'
log_file: /var/log/salt/cloud
log_level: info
log_level_logfile: debug
```

### Versions Report

Versions report on Salt master server.
```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-59-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
