### ISSUE TITLE
Can't set user password in OpenBSD through the user state.

### ISSUE THREAD

**Issue by dumol** [saltstack/salt#39113]
### Description of Issue/Question

We create users and set passwords for them in a similar way in Linux, MacOS and FreeBSD (with adjusted `$HOME` dirs and `bash` paths), but all our user states fail to set a password on the OpenBSD minion. 

The docs mention setting a password for a user should work in OpenBSD too: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.user.html

### Setup
The following state fails in OpenBSD:
```
dev-account:
  user.present:
    - name: 'dev'
    - fullname: 'Developer Account'
    - shell: '/usr/local/bin/bash'
    - home: '/home/dev/'
    - password: '$1$yKL7JOOJ$cKD684neV2MTj6MZ1mdI70'
```

### Steps to Reproduce Issue
Apply the above state to an OpenBSD minion. On the first run, you get:
```
          ID: dev-account                                                                                                                                   
    Function: user.present                                             
        Name: dev                                                               
      Result: False                                                                  
     Comment: User dev created but failed to set password to XXX-REDACTED-XXX                                                     
     Started: 18:25:46.740541         
    Duration: 570.716 ms                                                                                                              
     Changes:                                                                                                    
              ----------                                                                                                                  
              fullname:                                                                               
                  Developer Account                                                                                                       
              gid:                                            
                  1000                                                                                                                             
              groups:                                                                           
                  - dev                                                                         
              home:                                                              
                  /home/dev/                                                     
              homephone:                                
              name:                                                       
                  dev                                                                                
              passwd:                                                                                                               
                  *                                                                                                                 
              password:                                                            
                  XXX-REDACTED-XXX                                                                                                   
              roomnumber:                                                                                                            
              shell:                                                                                                         
                  /usr/local/bin/bash                              
              uid:                                                               
                  1000                                                                  
              workphone: 
```
On subsequent runs you get:
```
          ID: dev-account
    Function: user.present
        Name: dev
      Result: False
     Comment: These values could not be changed: {'passwd': '$1$yKL7JOOJ$cKD684neV2MTj6MZ1mdI70'}
     Started: 18:27:33.402799
    Duration: 255.711 ms
     Changes:  
```
The minion debug/trace/garbage logs show this line:

```
2017-02-01 18:28:18,826 [salt.state][ERROR   ][45907] These values could not be changed: {'passwd': '$1$yKL7JOOJ$cKD684neV2MTj6MZ1mdI70'} 
```

### Versions Report
The master runs the latest upstream version for Ubuntu 14.04: 2016.11.1 (Carbon).
```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-107-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
The minions are:
  * OpenBSD 6.0 release with salt 2016.3.1 (Boron)
```
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul 25 2016, 16:14:54)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:
        machine: amd64
        release: 6.0
         system: OpenBSD
        version: Not Installed
```
  * OpenBSD current (as of January 30) with salt 2016.11.1 (Carbon)
```
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 28 2017, 11:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist:
        machine: amd64
        release: 6.0
         system: OpenBSD
        version: Not Installed
```
I think this failed in 5.8 and 5.9 too, judging by how old our workaround  for OpenBSD in our state is. But I don't have an installation to re-test.

**Comment by eradman** [comment]
I tested the salt develop branch, and changing the password does work on OpenBSD 6.0

﻿I provided a fix for this on May 16, 2016 in commit d7bd667f

@ajacoutot updated the OpenBSD `sysutils/salt` port to 2016.11.2. You may want to try backporting his work to the 6.0 ports tree.

**Comment by Ch3LL** [comment]
@dumol can you test @eradman 's fix from the pr: https://github.com/saltstack/salt/pull/33227

We can see about possibly getting it backported to 2016.11 if this works for ya. Thanks @eradman for catching this and pointing towards hte pr :)

**Comment by dumol** [comment]
I've back-ported the https://github.com/saltstack/salt/commit/d7bd667f793baf12f259bb08e6ea62322da8a470 fix to our 6.0 minion running 2016.3.1, but it doesn't seem to make any difference in this regard. I've also updated my OpenBSD-current install over the week-end to test 2016.11.2, I can attest it comes with the fix, but I get the same error. Sorry…

**Comment by Ch3LL** [comment]
@dumol thanks for trying that. @eradman when you tested this and it did work what did your state look like?

**Comment by eradman** [comment]
This is the test I ran:

    $ doas salt workstation state.sls common.openbsd
    ...
    
              ID: laura
        Function: testuser.present
          Result: True
         Comment: Updated testuser laura
         Started: 20:06:15.354695
        Duration: 44.89 ms
         Changes:
                  ----------
                  passwd:
                      XXX-REDACTED-XXX
    
    Summary for workstation
    ------------
    Succeeded: 4 (changed=1)


Where `common/openbsd.sls` contains:

    laura:
      user.present:
        - shell: /bin/ksh
        - home: /home/laura
        - uid: 1004
        - gid: 10
        - password: '$2b$08$v...'

Here the master an minion are both running from a recent Salt -develop checkout on OpenBSD. I suppose a different result is possible running the master on Ubuntu, but I would be surprised.

**Comment by eradman** [comment]
One possibly relevant observation: on OpenBSD the password cipher is configurable in `/etc/login.conf`; the default is`:localcipher=blowfish,a:`, so passwords lifted from `/etc/shadow` on a Linux system will probably not work

    $ encrypt -c default ABC123
    $2b$08$gP7hQX893l3Z0/MB9ChJzuvBALD4TO9SuiaFBGuZ3/8wESC4sxFyK

Through trial and error I discovered that Salt will fail to set some valid values. This is valid, but fails:

    dev:
      user.present:
        - password: '*'

But this succeeds!

    dev:
      user.present:
        - password: '*************'

**Comment by Ch3LL** [comment]
@eradman thank you so much for posting that use case! @dumol does his test case help you at all? If you use this test case do you see success?

**Comment by dumol** [comment]
Thank you @eradman for your suggestions… I've tried your hash too and another one generated in OpenBSD, the error is still present:
```
These values could not be changed: {'passwd': '$2b$08$gP7hQX893l3Z0/MB9ChJzuvBALD4TO9SuiaFBGuZ3/8wESC4sxFyK'}
```
I get different results for the two additional test cases in your last post too, the first one succeeds to set password as `'*`', while setting the `'*************'` password fails with:
```
These values could not be changed: {'passwd': '*************'}
```

**Comment by dumol** [comment]
Retested in OpenBSD 6.1 and got the same results as in my previous post. The version report:
```
# salt-minion --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Apr  1 2017, 14:51:20)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist:
        machine: amd64
        release: 6.1
         system: OpenBSD
        version: Not Installed
```
