### ISSUE TITLE
salt-cloud fails to respect multiple profiles in one launch command

### ISSUE THREAD

**Issue by wes-novack** [saltstack/salt#39120]
### Description of Issue/Question
When attempting to launch multiple hosts simultaneously using disparate profiles, salt-cloud launches all instances using the final trailing profile in the list, not respecting the previous profiles that were specified earlier in the command.

### Setup
Cloud profiles configuration example:
```
aza:
  provider: 2a
  image: ami-9de15afd
  size: t2.micro
  network_interfaces:
    - DeviceIndex: 0
      SubnetId: subnet-id-in-zone-a
      SecurityGroupId:
        - sg-yourgroupid

azb:
  provider: 2b
  image: ami-9de15afd
  size: t2.micro
  network_interfaces:
    - DeviceIndex: 0
      SubnetId: subnet-id-in-zone-b
      SecurityGroupId:
        - sg-yourgroupid

azc:
  provider: 2c
  image: ami-9de15afd
  size: t2.micro
  network_interfaces:
    - DeviceIndex: 0
      SubnetId: subnet-id-in-zone-c
      SecurityGroupId:
        - sg-yourgroupid
```

Happy to provide a more comprehensive provider conf file with redacted secrets as well, if that will help, but the pertinent part of that config is:
```
2a:
  location: us-west-2
  availability_zone: us-west-2a
2b:
  location: us-west-2
  availability_zone: us-west-2b
2c:
  location: us-west-2
  availability_zone: us-west-2c
```

### Steps to Reproduce Issue
Command example
```
salt-cloud -P -p aza HOST1 -p azb HOST2 -p azc HOST3
```
When this command is run, all hosts are launched with the `azc` profile. They get launched in the us-west-2c availability zone, inside the subnet specified in the `azc` profile configuration.

### Versions Report
salt-master/salt-cloud host:
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
