### ISSUE TITLE
when I set a variable 'true' and pass as context via a state, it gets set to 'True' with capitol T.

### ISSUE THREAD

**Issue by unassassinable** [saltstack/salt#39132]
my init.sls file:
```
{% if 'kibana' in grains['office'] %}
{% set value = 'false' %}
{% else %}
{% set value = 'true' %}
{% endif %}

<redacted for easier reading>

# elasticsearch configuration file
elasticsearch.yml:
  file.managed:
    - name: /etc/elasticsearch/elasticsearch.yml
    - makedirs: True
    - context:
      value: {{ value }}
    - user: root
    - group: root
    - mode: 644
    - template: jinja
    - source: salt://configure-elasticsearch/elasticsearch.yml.jinja

<redacted for easier reading>
```
my elasticsearch.yml.jinja file:
```
<redacted for easier reading>
bootstrap.memory_lock: {{ value }}
<redacted for easier reading>
```
When I apply the state to a minion, it converts 'true' to 'True'.  If I do cat /etc/elasticsearch/elasticsearch.yml on the minion after applying the state, I see:
```
bootstrap.memory_lock: True
```
which causes the service to fail to start.

If I change it to truE, then it passes 'truE'.  It is only on the word 'true' that it capitalizes the T.

**Comment by gtmanfred** [comment]
If you want it to be `true` you will need to quote it.

https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#true-false-yes-no-on-off

```
elasticsearch.yml:
  file.managed:
    - name: /etc/elasticsearch/elasticsearch.yml
    - makedirs: True
    - context:
      value: "{{ value }}"
    - user: root
    - group: root
    - mode: 644
    - template: jinja
    - source: salt://configure-elasticsearch/elasticsearch.yml.jinja
```
