### ISSUE TITLE
Extends dose not verify the target state module name if it has a "."

### ISSUE THREAD

**Issue by rlguarino** [saltstack/salt#39175]
### Setup

top.sls
```                                                                                                          
base:
  '*':
    - mia
    - test
```

mia.sls:
```
mia:
  cmd.run:
    - name: echo "Something"
```

test.sls:
```
include:
 - mia

extend:
  mia   :
    service.running:
      - watch:
	- cmd: something

something:
  cmd.run:
    - name : echo "something else"

```

**Expected Behavior**: An error similar to the output when you instead use:

```
extend:
  mia:
    service:
      - watch:
        - cmd: something
```

Error:

```
local:
- No function declared in state 'service' in SLS 'mia'
```

**Actual Behavior**: Nothing happens, the watch isn't applied to anything, it shows up in `salt-call state.show_highstate --output yaml`:

```
...
  __extend__:
  - mia:
      __sls__: !!python/unicode test
      __env__: base
      service:
      - watch:
        - cmd: something
      - running
...
```

But nothing in the `salt-call state.show_lowstate --output yaml`

```
- __env__: base
  __id__: mia
  __sls__: !!python/unicode mia
  fun: run
  name: echo "Something"
  order: 10000
  state: cmd
```

### Versions Report
```
 salt-call --versions-report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12+ (default, Sep 17 2016, 12:08:02)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.0
 
System Versions:
           dist: Ubuntu 16.10 yakkety
        machine: x86_64
        release: 4.8.0-34-generic
         system: Linux
        version: Ubuntu 16.10 yakkety
```
