### ISSUE TITLE
file.comment ^$ unanchoring is naieve

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#39188]
I want to do this:

```
ca-certificates-no-wosign:
  file.comment:
    - name: /etc/ca-certificates.conf
    - regex: (?i)^[^!].*(wosign|startcom)
    - char: '!'
    - backup: False
```
because 'WoSign' is written inconsistently in my ca-certificates.conf file and I'd prefer not to enumerate all possibilities.

However, the `(?i)` at the beginning throws off the unanchoring in the state:
```
    unanchor_regex = regex.lstrip('^').rstrip('$')
```

Flags needs to be at the beginning according to the [python docs](https://docs.python.org/2/library/re.html): 
```
Note that the (?x) flag changes how the expression is parsed. It should be used first in the expression string, or after one or more whitespace characters. If there are non-whitespace characters before the flag, the results are undefined.
```

So we can replace the lstrip/rstrip combo with this beauty:

```
# remove (?i)-like flags, ^ and $
unanchor_regex = re.sub(r'^(\(\?[iLmsux]\))?\^?(.*?)\$?$',r'\2',regex)
```
