### ISSUE TITLE
file.managed with follow_symlinks=true reports change when test=true on symlinks

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#39195]
### Description of Issue/Question

salt git development has issues when test=true for file.managed when target is symlink.

### Setup

```
apt-get install nginx

state something like.
mfcf.research.rshiny.p01.fe:
  state.managed:
   - name: /etc/nginx/sites-enabled/default
   - contents: '# blank'
   - mode: 0644
   #(default)- follow_symlinks: true
# /etc/nginx/sites-enabled/default is a link to default -> /etc/nginx/sites-available/default
```

salt-call state.highstate test=true
```
----------
          ID: mfcf.research.rshiny.p01.fe
    Function: file.managed
        Name: /etc/nginx/sites-enabled/default
      Result: None
     Comment: The file /etc/nginx/sites-enabled/default is set to be changed
     Started: 12:56:51.262818
    Duration: 33.565 ms
     Changes: 
```

also a small bug, says there is a change but not what that change is....

salt-call state.highstate
```
          ID: mfcf.research.rshiny.p01.fe
    Function: file.managed
        Name: /etc/nginx/sites-enabled/default
      Result: True
     Comment: File /etc/nginx/sites-enabled/default is in the correct state
     Started: 13:06:12.474311
    Duration: 34.817 ms
     Changes:   
----------
```

normal highstate without test shows no change.

issue might be around: https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L2118
because file.check_managed_changes does not know to follow_symlinks

### Versions Report

development
