### ISSUE TITLE
FreeBSD 2016.11.1  Reason: 'boto_asg' __virtual__ returned False

### ISSUE THREAD

**Issue by nbari** [saltstack/salt#39249]
### Description of Issue/Question

Upgrading salt to 2016.11.1 brakes the recipes using  boto, returning:

----------                       
          ID: Autoscaling for bastion-vpn-sandbox
    Function: boto_asg.present
        Name: bastion-vpn-sandbox      
      Result: False               
     Comment: State 'boto_asg.present' was not found in SLS 'AUTOSCALE.bastion-vpn'
              Reason: 'boto_asg' __virtual__ returned False
     Changes:                 
----------  

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
Ensure myasg exists:
  boto_asg.present:
    - name: myasg
    - launch_config_name: mylc
    - availability_zones:
      - us-east-1a
      - us-east-1b
    - min_size: 1
    - max_size: 1
    - desired_capacity: 1
    - load_balancers:
      - myelb
    - suspended_processes:
        - AddToLoadBalancer
        - AlarmNotification
    - scaling_policies
        - adjustment_type: ChangeInCapacity
        - as_name: api-production-iad
        - cooldown: 1800
        - min_adjustment_step: None
        - name: ScaleDown
        - scaling_adjustment: -1
    - region: us-east-1
    - keyid: GKTADJGHEIQSXMKKRBJ08H
    - key: askdjghsdfjkghWupUjasdflkdfklgjsdfjajkghs
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

salt minion state.highstate

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```text
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 12 2017, 01:14:20)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 10.3-STABLE
         system: FreeBSD
        version: Not Installed
```
