### ISSUE TITLE
Remount forced with lizardfs fuse filesystem due to device missmatch

### ISSUE THREAD

**Issue by alexharrington** [saltstack/salt#39269]
### Description of Issue/Question
I'm in the process of upgrading to 2016.11.2 (master and minion in question are upgraded to these versions) from 2015.8 but I have an issue where my lizardfs fuse mounts are always remounted. 2015.8 did this historically, but I was hoping I'd be able to stop that with the newer salt version.

When I run my mount.mounted state, I get:

> Forced unmount because devices don't match. Wanted: mfsmount, current: mfs#mfsmaster:9421, /mfs#mfsmaster:9421

### Setup
My mount SLS looks like this:

```
lizardfs-example-mount:
  mount.mounted:
    - fstype: fuse
    - mkmnt: True
    - opts: mfsdelayedinit,mfssubfolder=/path/to/directory,mfswritecachesize=5000,mfsioretries=20,_netdev
    - hidden_opts: mfsdelayedinit,mfssubfolder,mfsioretries
    - persist: False
    - device: mfsmount
    - name: /mnt/example
    - require:
      - pkg: lizardfs-client
    - device_name_regex:
      - mfs#mfsmaster:.*
```

I've tried various things in the device_name_regex field to try and persuade it that it is correct. I've tried directly putting what it says it's expecting - ie `mfs#mfsmaster:9421, /mfs#mfsmaster:9421`, and I've also tried things like just `mfs.*` since I think that should match anything starting mfs?

### Versions Report
Master
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-107-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
My guess is that the : on the line is causing yaml to freak out.

Can you quote the string?

```
lizardfs-example-mount:
  mount.mounted:
    - fstype: fuse
    - mkmnt: True
    - opts: mfsdelayedinit,mfssubfolder=/path/to/directory,mfswritecachesize=5000,mfsioretries=20,_netdev
    - hidden_opts: mfsdelayedinit,mfssubfolder,mfsioretries
    - persist: False
    - device: mfsmount
    - name: /mnt/example
    - require:
      - pkg: lizardfs-client
    - device_name_regex:
      - "mfs#mfsmaster:.*"
```
