### ISSUE TITLE
GitFS providers do not use git credential helper in .gitconfig file

### ISSUE THREAD

**Issue by foundatron** [saltstack/salt#39284]
### Description of Issue/Question

As far as I can tell,  none of the three gitfs providers are able to use [credential helpers ](https://git-scm.com/docs/gitcredentials) in .gitconfig files.  In my case I'm trying to use AWS CodeCommit and the AWS CodeCommit credential-helper: 

```
git config --global credential.helper '!aws codecommit credential-helper $@'
git config --global credential.UseHttpPath true
```

My repo address is using https: `https://git-codecommit.us-east-1.amazonaws.com/v1/repos/my-salt-repo`

Each provider acts differently:
- GitPython: Nothing happens (probably because it's https)
- Pygit: It tries and gets interrupted...I imagine it's asking for the user name and password:
    
    ```
    [DEBUG   ] Updating git fileserver cache
   [WARNING ] gitfs_global_lock is enabled and update lockfile    /var/cache/salt/master/gitfs/1234567890asdfghj/.git/update.lk is present for gitfs remote    'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/my-cool-salt-repo'. Process 12345   obtained the lock but this process is not running. The update may have been interrupted. If using multi-master with shared gitfs cache, the lock may have been obtained by another master.
    ```
- Dulwich returns a 401 error, which makes sense if it isn't using the credential helper.
    

### Setup
I'm trying to use a private AWS CodeCommit repo as my gitfs remote. My hope was that I could use CodeCommit along with AWS IAM instance profiles for permissions rather than putting any private keys or credentials on the salt master. Rather than putting credentials in the salt master conf, temporary credentials should be provided by the AWS CodeCommit credential-helper specified in the .gitconfig file.

Using git clone outside of git uses the credential helper defined in the .gitconfig successfully.

Documentation for configuring the git credential helper for CodeCommit can be read here: [See step 3](http://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-unixes.html).

### Steps to Reproduce Issue

1. [Follow the directions here to create a private git repo in AWS CodeCommit]( https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-unixes.html#setting-up-https-unixes-account)
2. In you `/etc/salt/master` config define your gitfs provider and remote: 
    ```
    fileserver_backend:
      - git

    gitfs_provider: pygit2
    gitfs_remotes:
       - https://git-codecommit.us-east-1.amazonaws.com/v1/repos/my-cool-salt-repo:
    ```
3. Run salt-master in foreground with logging set to debug: `salt-master -l debug`

### Versions Report
```
Salt --versions-report
Salt Version:
           Salt: 2016.3.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 4.4.41-36.55.amzn1.x86_64
         system: Linux
        version: Not Installed
```
