### ISSUE TITLE
an already mounted bind mount get wrong opts in fstab

### ISSUE THREAD

**Issue by disaster123** [saltstack/salt#39292]
Hi,

if a bind mount is already mounted it get's the wrong options in fstab.

### Description of Issue/Question

state file:

```
mount /home/tmp:
  mount.mounted:
    - name: /home/tmp
    - device: /home/tmp
    - fstype: none
    - opts:
      - bind
      - nodev
      - noexec
      - nosuid
      - rw
    - persist: True
```

resulting fstab entry:
grep home/tmp /etc/fstab

```
/home/tmp               /home/tmp       none    noexec,rw,inode64,bind,swidth=9216,logbsize=256k,attr2,nodiratime,usrquota,sunit=512,nosuid,noatime,nodev   0 0
```

expected entry would be:
`/home/tmp               /home/tmp       none    bind,nodev,noexec,nosuid,rw   0 0`

this only happens if i did
`mount -o bind,nodev,noexec,nosuid,rw /home/tmp /home/tmp`

before running salt. The other options i see are options "copied" from the root fs.

### Versions Report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 4.4.26+76-ph
         system: Linux
        version: debian 8.6
