### ISSUE TITLE
Cron change with identifier results in multiple entries

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#39309]
### Description of Issue/Question

Switching a cron from a a set hour (`*`) to `@hourly` with an identifier results in ending up with two cron entries instead of the expected one.

### Setup
Initially my state was:
```
script_name:
  cron.present:
    - name: script_name
    - identifier: script_name
    - user: username
    - hour: '*'
```

Which resulted in a cronjob being added. However, I then decided to use the `special` argument to set it to `@hourly` like so:

```
script_name:
  cron.present:
    - name: script_name
    - identifier: script_name
    - user: username
    - special: '@hourly'
```

This resulted in one identifier with two entries: the old one and the new one. Expected behavior would be that the line with the identifier was fully replaced with the new one.

### Steps to Reproduce Issue
See above

### Versions Report

```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
