### ISSUE TITLE
"Failed to set supplemental groups" on macOS as unprivileged

### ISSUE THREAD

**Issue by bricewge** [saltstack/salt#39318]
### Description of Issue/Question
When using `salt-call` on macOS as an unprivilged user, if the state contain a parameter `user` or `runas` which is set to the name of the current user it fail. This is because salt use `os.setgroups` which is "[...] typically available only to the superuser."

### Setup
```
test:
  git.latest:
    - name: https://github.com/saltstack/salt.git
    - target: ~/salt
    - user: $USER
    - rev: develop
```
Where `$USER` is your current user
### Steps to Reproduce Issue
`salt-call --local state.highstate`
Return a comment like: Failed to check remote refs: Failed to set supplemental groups to [4234]. Error: [Errno 1] Operation not permitted

### Versions Report
```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb 10 2017, 16:03:43)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64
```
