### ISSUE TITLE
boto_iam: Short named vs ARN in managed_policies

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#39310]
### Description of Issue/Question

The `boto_iam` module  sees changes where there are none when the short name is being used.

### Setup
When doing `user_present` and setting `managed_policies` like so:

```
testuser:
   boto_iam.user_present:
      - managed_policies:
         - 'CloudWatchReadOnlyAccess'
```

It results in a wrongly flagged change every highstate:

```
    Changes:   
              ----------
              new:
                  ----------
                  manged_policies:
                      - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
              old:
                  ----------
                  managed_policies:
                      - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
```

The ARN is the same. Somehow when resolving the name to the ARN the comparison seems to be failing to discover the values are actually the same.

### Steps to Reproduce Issue
See above

### Versions Report
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
