### ISSUE TITLE
Implement spaly with 'cron' and 'when' criteria and don't download files when cache=true used with highstate

### ISSUE THREAD

**Issue by YuriGrigorov** [saltstack/salt#39322]
This is feature request.

Imagine infrastructure with thousands of servers and hundreds of services.

Salt warranties us that all servers are in correct state. To achieve that we periodically (for example every 10 minutes) call `highstate`. Main question how safely edit sates or implement new states and slowly move changes to production.

Theoretically environments can help us because we can test changes but it's not enough.

What if servers are located in two data centers. We can use three environments: testing, staging and production. In testing we put few servers where we can test new states. In staging we put one server from each service. All other in production.

Now we update `sudoers` template and move it to the testing. In 10 minutes it's applied on all testing servers. But in testing too small amount of servers and there are no target server for whom we made changes. We move changes to the staging and in 10 minutes we lost `sudo` on all staging servers (about hundred). Much worse if changes goes to production. Then we loose `sudo` on all servers :) in 10 minutes.

To prevent such situations we need `spaly` work with `when` and `cron` in `schedule`. Second thing we need ability to apply `highstate` without updating pillar data and files from master (`state.apply cache=true`, but extended).

Then:
- In testing we call 
  - highstate every 10 minutes with splaytime 9 minutes.
- In staging: 
  - highstate every hour with splaytime 59 minutes (randomly once per hour)
  - highstate cache=true every 10 minutes with splaytime 9 minutes.
- In production data center 1:
  - highstate every **odd** hour with splaytime 59 minutes (randomly once per hour)
  - highstate cache=true every 10 minutes with splaytime 9 minutes.
- In production data center 2:
  - highstate every **even** hour with splaytime 59 minutes (randomly once per hour)
  - highstate cache=true every 10 minutes with splaytime 9 minutes.

Because staging servers receives updated sudoers only once per hour and do this randomly we will notice problem without loosing all staging servers. In case problem goes in to production then only one data center will be affected in first hour and you will have time to stop expansion.

So please:
- implement `spaly` with `cron` and `when`
- use files from local cache and don't trigger master at all when `cache=true` used with `highstate`

Configuration example:

testing:
```
schedule:
  highstate:
    function: state.highstate
    cron: '*/10 * * * *'
    splay: 9
```

staging
```
schedule:
  highstate:
    function: state.highstate
    cron: '0 * * * *'
    splay: 59
  highstate_local:
    function: state.highstate
    kwargs:
      cache=true
    cron: '*/10 * * * *'
    splay: 9
```

production DC1:
```
schedule:
  highstate:
    function: state.highstate
    when:
      - 9:00am
      - 11:00am
      - 1:00pm
      - 3:00pm
      - 5:00pm
      - 7:00pm
    splay: 59
  highstate_local:
    function: state.highstate
    kwargs:
      cache=true
    cron: '*/10 * * * *'
    splay: 9
```

production DC2:
```
schedule:
  highstate:
    function: state.highstate
    when:
      - 8:00am
      - 10:00am
      - 12:00pm
      - 2:00pm
      - 4:00pm
      - 6:00pm
    splay: 59
  highstate_local:
    function: state.highstate
    kwargs:
      cache=true
    cron: '*/10 * * * *'
    splay: 9
```
