### ISSUE TITLE
Feature Request: feature to print any string to STDOUT

### ISSUE THREAD

**Issue by pepoluan** [saltstack/salt#39386]
### Description of Issue/Question

Some Orchestration jobs take a long time to complete, involving a whole lot of states. Many (nearly all) of these states are 'silent'. So, when the Orchestration job is invoked, the sysadmin can only wonder how far into the job has everything progressed.

I noticed that `salt.runners.test` already can emit any string to STDOUT. Notably, `test.sleep` emits the number of seconds of sleep, and `test.stdout_print` emits a string `"foo"`

`test.stdout_print` should be able to do more than just printing "foo", though. Add a kwarg, say `message`, with default value of `'foo'`, and print that kwarg instead.

### Setup

This is a hypothetical part of an Orchestration job:

```
state-X:
  salt.state:
    # Loooooong processing time here

state-X done:
  salt.run:
    - name: test.stdout_print
    - kwarg:
      - message: State X is done. Continuing with State Y...
    - require:
      - salt: state-X

state-Y:
  salt.state:
    # More long processing
    - require:
      - salt: state-X done
```

We might even do it like this:

```
wait event msg:
  salt.run:
    - name: test.stdout_print
    - kwarg:
      - message: Waiting for event...

wait event:
  salt.wait_for_events:
    # Event description here
    - require:
      - salt: wait event msg

wait event done msg:
  salt.run:
    - name: test.stdout_print
    - kwarg:
      - message: All events received. Continuing.
    - require:
      - salt: wait event
```

### Alternative implementation

We can simplify the job even more by adding `stdout_print` to `salt.states.saltmod`. The last job above will then become:

```
wait event msg:
  salt.stdout_print:
    - name: Waiting for event...

wait event:
  salt.wait_for_events:
    # Event description here
    - require:
      - salt: wait event msg

# Or implementing the common convention of having 'name' = 'ID'
All events received - continuing:
  salt.stdout_print:
    - require:
      - salt: wait event
```
