### ISSUE TITLE
salt-minion RPM missing dependency on policycoreutils-python

### ISSUE THREAD

**Issue by xenophonf** [saltstack/salt#39408]
### Description of Issue/Question

Because the salt-minion RPM doesn't depend on policycoreutils-python (which provides /usr/sbin/semanage), the [selinux execution module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.selinux.html) does not work without further configuration.  This can prevent highstate jobs from working when configuring a minion for the first time, e.g., highstate data compilation errors due to invalid references to the selinux module's functions.

### Setup

Relevant parts of the top file:
https://github.com/irtnog/salt-states/blob/master/top.sls#L180
https://github.com/irtnog/salt-states/blob/master/top.sls#L442

The state that installs policycoreutils-python:
https://github.com/irtnog/salt-states/blob/production/selinux/init.sls#L1

The state file that relies on the selinux execution module at render time:
https://github.com/irtnog/comanage-formula/blob/master/comanage/registry/init.sls#L153

### Steps to Reproduce Issue

1. Perform a minimal install of CentOS 7 build 1611 (I used CentOS-7-x86_64-Minimal-1611.iso).

2. Install the salt-minion RPM as described by the [SaltStack Package Repo installation instructions for Red Hat Enterprise Linux 7 and CentOS 7](http://repo.saltstack.com/#rhel).

3. Run a highstate job using the SLS assignments shown above.

salt.utils.template will log the following error: `Rendering exception occurred: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'selinux.getenforce'`.

4. Alternatively, run the command `salt-call selinux.getenforce`, which will exit with an error status and print the following message to standard error: `'selinux' __virtual__ returned False: semanage is not in the path`.

After manually installing policycoreutils-python, the above actions work as expected.

### Versions Report

On the master (one minor rev behind the minion):
```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 5.4.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb  4 2017, 17:32:56)
   python-gnupg: 0.3.9
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 10.3-RELEASE-p11
         system: FreeBSD
        version: Not Installed
```

On the minion:

```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
