### ISSUE TITLE
`file.get_managed` does not update the cached template after update

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#39422]
### Description of Issue/Question

I am using `file.get_managed` in order to render a template, physically stored under `/etc/salt/templates/ntp.jinja`.
Under `file_roots` I have appended `/etc/salt/templates`.
When specifying the `source` argument using the absolute path (i.e.: `/etc/salt/templates/ntp.jinja`), I don't see any issues.
But when specifying the source as `salt://ntp.jinja`, it caches the template after the first run and it does not update it. So if the template is updated and `file.get_managed` is executed again, it is going to use the old version.

Because of this, I need to go under the cache dir and remove the files:

```bash
root@ip-172-31-13-136:/var/cache/salt# rm ./master/roots/hash/base/ntp.jinja.hash.sha256
root@ip-172-31-13-136:/var/cache/salt# rm ./proxy/device1/files/base/ntp.jinja
```

After removing the files above, it caches the newest version and so on.

This happens in both Carbon and develop branch:

```yaml
Salt Version:
           Salt: 2016.11.0-787-gfc59d5e

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Dec 18 2016, 20:19:42)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```
