### ISSUE TITLE
Additional redundant space in grain osfullname

### ISSUE THREAD

**Issue by modrym** [saltstack/salt#39441]
### Description of Issue/Question
After upgrading salt minion to 2016.11.2 it stopped working properly on Windows 7 Proffessional N.
Running salt-call kept giving error that windows_license_key is not available.

We found out that salt in that version adds a space at the end of os name.

So instead 
```
'Microsoft Windows 7 Professional N'
```
(as it has been so far) we have:
```
'Microsoft Windows 7 Professional N '
```

### Setup
Script contains such lines:
```
{% if grains['osfullname'] == 'Microsoft Windows 7 Professional N' %}
windows_license_key: PUT_HERE_VALID_VOLUME_LICENSE_KEY_WIN7PRON
{% elif grains['osfullname'] == 'Microsoft Windows 7 Professional' %}
windows_license_key: PUT_HERE_VALID_VOLUME_LICENSE_KEY_WIN7PRO
{% endif %}
```
### Versions Report
```
Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6
 
System Versions:
           dist:
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```
