### ISSUE TITLE
Salt stack does not detect fqdn_ip4 correctly

### ISSUE THREAD

**Issue by tamalsaha** [saltstack/salt#39450]
I am trying to configure a server in Packet.net using salt stack. `salt['grains.get']('fqdn_ip4')[0]` is failing with `Jinja variable list object has no element 0`

If I run `salt-call grains.items`, this is what I see: 
```yaml
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 147.75.207.207
            - 147.75.207.208
        ip6_nameservers:
        nameservers:
            - 147.75.207.207
            - 147.75.207.208
        options:
        search:
        sortlist:
    domain:
    fqdn:
        localhost
    fqdn_ip4:
        - 127.0.0.1
    fqdn_ip6:
        - ::1
    gid:
        0
    gpus:
    groupname:
        root
    host:
        localhost
    hwaddr_interfaces:
        ----------
        bond0:
            0c:c4:7a:b5:88:2a
        eth0:
            0c:c4:7a:b5:88:2a
        eth1:
            0c:c4:7a:b5:88:2b
        lo:
            00:00:00:00:00:00
    id:
        k-160823-master
    init:
        systemd
    internal_ip:
        10.100.30.131
    ip4_interfaces:
        ----------
        bond0:
            - 147.75.97.127
            - 10.100.30.131
        eth0:
        eth1:
        lo:
            - 127.0.0.1
    ip6_interfaces:
        ----------
        bond0:
            - 2604:1380:0:2c00::3
            - fe80::ec4:7aff:feb5:882a
        eth0:
        eth1:
        lo:
            - ::1
    ip_interfaces:
        ----------
        bond0:
            - 147.75.97.127
            - 10.100.30.131
            - 2604:1380:0:2c00::3
            - fe80::ec4:7aff:feb5:882a
        eth0:
        eth1:
        lo:
            - 127.0.0.1
            - ::1
    ipv4:
        - 10.100.30.131
        - 127.0.0.1
        - 147.75.97.127
    ipv6:
        - ::1
        - 2604:1380:0:2c00::3
        - fe80::ec4:7aff:feb5:882a
```

```sh
# salt-call --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7 
```
