### ISSUE TITLE
Inability to cleanly call runner functions in reactor SLS'/reaction's jinja

### ISSUE THREAD

**Issue by zer0def** [saltstack/salt#39454]
After consulting with @gtmanfred over IRC, we've noticed that the documentation specifies one could call execution and runner modules from within reactions: https://docs.saltstack.com/en/latest/topics/reactor/#jinja-context
However, the `salt` jinja context variable seems to be using only execution modules with no context var for calling runners, outside of a workaround of `{{ salt['saltutil.runner'](<runner_func>)(<runner_kwargs>) }}`, which has it's own limitations, like inability to pass an arglist.

Current SLS:
```
test:
  local.cmd.run:
    - tgt: '*'
    - arg:
        - "sleep 60 && echo '{{ salt['saltutil.runner']('jobs.list_jobs')() }}'"
```
Presumed intended SLS:
```
test:
  local.cmd.run:
    - tgt: '*'
    - arg:
        - "sleep 60 && echo '{{ runner['jobs.list_jobs']() }}'"
```

`salt --versions-report`:
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.0
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
