### ISSUE TITLE
kwargs not passed properly to state.sls via reactor

### ISSUE THREAD

**Issue by jpunzel** [saltstack/salt#39471]
### Description
I have a reactor set up to respond to an event that triggers a state I wrote called `salt_git_update`. I pass pillar data to it using the `pillar` kwarg.

When the reactor is run, it appears that my kwargs dictionary is passed as a single string in `fun_args` which is (wrongly?) interpreted by state.sls as a comma-separated list of states to run.

(I have also tried providing `state.sls` arguments directly to the `arg` list corresponding to the function signature, which appears to work, but there's no way to supply additional pillar data this way.)

#### Reactor file
```
salt_push:
  local.state.sls:
    - tgt: 'G@groups:salt_master_prod'
    - expr_form: compound
    - kwarg:
        mods: salt_git_update
        pillar:
          salt_git_branches:
            - master
        queue: True
```

#### `salt-run state.event pretty=True`
```
salt/job/20170217002240377557/ret/myhostname.example.com       {
    "_stamp": "2017-02-17T00:22:41.707313", 
    "cmd": "_return", 
    "fun": "state.sls", 
    "fun_args": [
        "{'queue': True, 'pillar': {'salt_git_branches': ['master']}, 'mods': 'salt_git_update', '__kwarg__': True}"
    ], 
    "id": "myhostname.example.com", 
    "jid": "20170217002240377557", 
    "out": "highstate", 
    "retcode": 1, 
    "return": [
        "No matching sls found for '{'queue': True' in env 'base'", 
        "No matching sls found for ' 'pillar': {'salt_git_branches': ['master']}' in env 'base'", 
        "No matching sls found for ' 'mods': 'salt_git_update'' in env 'base'", 
        "No matching sls found for ' '__kwarg__': True}' in env 'base'"
    ], 
    "success": true
}
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
```

**Comment by gtmanfred** [comment]
If instead of using mods: to specify the sls, you put that under args like this 

```
salt_push:
  local.state.sls:
    - tgt: 'G@groups:salt_master_prod'
    - expr_form: compound
    - arg:
      - salt_git_update
    - kwarg:
        pillar:
          salt_git_branches:
            - master
        queue: True
```

Does this work?

Thanks,
Daniel
