### ISSUE TITLE
external pillar with cmd.run

### ISSUE THREAD

**Issue by silenius** [saltstack/salt#39533]
Hello,

I'm busy to template the installation of Icinga2 clients. Each client has a `icinga:client:master` pillar key which indicate which host is the master Icinga node. Without going into too much details, each client needs to get a "ticket" from the Icinga master node for the initial installation. This ticket is generated on the master node with the `icinga2 pki ticket --cn "..."`, for example:
```
root@icinga:/usr/local/etc/icinga2/pki # icinga2 pki ticket --cn "backup.lan"
79e20325e9406372518d411fa5712a51a3586ef4
```
As I have many clients I'd like to automate this, and I planned to use external pillars for this. After some reading I ended with the following script:

```python
/usr/local/etc/salt/modules/pillar/ cat icinga_ticket_pillar.py
# -*- coding: utf-8 -*-

def ext_pillar(minion_id, pillar, *args, **kwargs):

    icinga_master = pillar['icinga']['client']['master']

    fqdn = __salt__['saltutil.cmd'](
        minion_id, 
        'grains.get', 
        arg=('fqdn',)
    )[minion_id]['ret']

    ret = __salt__['saltutil.cmd'](
        icinga_master, 
        'cmd.run',
        arg=('icinga2 pki ticket --cn {}'.format(fqdn),)
    )[minion_id]['ret']

    pillar['icinga']['client']['token'] = ret

    return {}
```

After that I'm refreshing the pillar:
```
~/ salt backup.lan saltutil.refresh_pillar
backup.lan:
    True
```
But after that it doesn't work, I'm getting a: 

`2017-02-21 18:49:37,041 [salt.pillar                                                ][CRITICAL][69986] Pillar render error: Failed to load ext_pillar icinga_ticket_pillar: 'backup.lan'`, error and a `salt backup.lan pillar.items` hangs ..

This is with:
```
~/ salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  5 2016, 09:28:23)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: amd64
        release: 10.3-RELEASE
         system: FreeBSD
        version: Not Installed
```

is it a bug or did I missed something?

Thanks!
