### ISSUE TITLE
Add a loop mechanism to salt state files

### ISSUE THREAD

**Issue by onlyanegg** [saltstack/salt#39548]
### Description of Issue/Question
It would cool to have a way to loop over execution modules at run time until a condition is met. This could be implemented by a loop state that takes as arguments the name of the execution module, a condition, a timeout, and the arguments of the execution module. 

It could look something like this: 

```yaml
wait_for_service_to_be_healthy:
  loop.until:
    - name: boto_elb.get_instance_health
    - condition: m_ret[0]['state'] == 'InService'
    - period: 5
    - timeout: 20
    - m_args:
      - {{ elb }}
    - m_kwargs:
        keyid: {{ access_key }}
        key: {{ secret_key }}
        instances: "{{ instance }}"
```
