### ISSUE TITLE
duplicated content existed in a single file while execute state.highstate 

### ISSUE THREAD

**Issue by wujiandong** [saltstack/salt#39547]
the file content as follow：
Cmnd_Alias WC_CMND = /usr/bin/wc
Cmnd_Alias WC_CMND = /usr/bin/wc

however, the correct should be only one, please take notice of this issue. 

another issue:
saltstacks change the owner permission of the directory "/data"  from 755 to 750 

thanks !

Pls:  3 parts of related as follow:

##1
---------------------------------------------------------------------------------------

```
sudoers_dir:
  file.recurse:
    - name: /etc/sudoers.d
    - source: salt://sudoers/files/sudoers.d
    - user: root
    - group: root
    - makedirs: True
    - backup: minion
    - file_mode: 640
    - dir_mode: 750
    - include_empty: True
    - recurse:
      - user
      - group
      - mode
```

##2
---------------------------------------------------------------------------------------
Salt Version[master]:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

 
##3
---------------------------------------------------------------------------------------
Salt Version[minion]:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
