### ISSUE TITLE
win_pkg.remove doesn't respect custom saltenv option when copying an uninstaller

### ISSUE THREAD

**Issue by andrii-rymar** [saltstack/salt#39607]
### Description of Issue/Question
win_pkg.remove doesn't respect custom saltenv option when copying an uninstaller

### Setup
Linux master and Windows 7 minion

Package description:
```
TestApp:
  latest:
    full_name: TestApp v1
    installer: salt://win/repo-ng/test_app/test_app.msi
    reboot: False
    install_flags: '/qn /norestart'
    msiexec: True
    uninstaller: salt://win/repo-ng/test_app/test_app.msi
    uninstall_flags: '/qn /norestart'
```
top file:
```
customenv:
  'windows_minion':
    - test.state1
    - test.state2
```
customenv/test/state1.sls:
```
install_test_app:
  pkg.installed:
    - name: TestApp
```
customenv/test/state2.sls:
```
uninstall_test_app:
  pkg.removed:
    - name: TestApp
```
### Steps to Reproduce Issue
1. Configure additional saltenv 'customenv'
2. Point 'win_repo_ng' to '/$salt_dir$/customenv/win/repo-ng'
3. Run 'pkg.refresh_db'
4. Apply State1
5. Apply State2

State1 completes with success and installs the TestApp but State2 fails with:
"Unable to cache file 'salt://win/repo-ng/test_app/test_app.msi' from saltenv 'base'" in minion logs.

So it seems that win_pkg.remove uses default saltenv value when trying to copy the uninstaller.

### Versions Report
Master: Salt: 2015.5.10 on Linux
Minion: Salt: 2016.11.2 on Windows 7
