### ISSUE TITLE
Master scheduled job not recorded on the event bus

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#39668]
### Description of Issue/Question

I have just note that a scheduled runner on the master, when executed, does not fire events on the bus.

To reproduce, one can add the following lines in the master config:

```yaml
schedule:
  schedule_my_runner:
    function: salt.cmd
    args:
      - test.ping
    minutes: 1
```

Which should execute the equivalent of `salt-run salt.cmd test.ping` (returning `True`) every minute.
Looking into the salt bus (using the `state.event` runner), this event is not recorded, although it is executed.
