### ISSUE TITLE
iptables.insert cannot set flags for after_jump_argument

### ISSUE THREAD

**Issue by schaarsc** [saltstack/salt#39661]
after_jump_argument for the jump target SET requires a flag. 
for example: `iptables -I INPUT -j SET --add-set setname flag`
```
iptables.insert:
  - table: filter
  - chain: INPUT
  - jump: SET
  - add-set: setname flag
```

salt stack is adding quotes if a whitespace is found in value
https://github.com/saltstack/salt/blob/v2016.11.3/salt/modules/iptables.py#L411
this generates `iptables -I INPUT -j SET --add-set "setname flag"`
and fails with "--add-set requires two args."
