### ISSUE TITLE
cmd.run(runas) results in "csh: Permission denied" (FreeBSD)

### ISSUE THREAD

**Issue by bgdnlp** [saltstack/salt#39673]
### Description of Issue/Question
Attempting to run a command as a different user on csh fails with "permission denied". FreeBSD uses csh as the root shell by default, so this is an issue on a fresh FreeBSD install. I didn't test on another OS, but I suspect it has something to do with csh, rather than FreeBSD.

This affects a number of states, like git for example, which fails if it uses the "user" parameter.

The only previous report I found is #9657, 3 years ago. Understandably closed, but note that I am reproducing this on a new FreeBSD 11 install, having almost nothing else installed and no changes to csh profile.

### Setup
Easy to reproduce on a masterless setup, but it behaves the same either way. Smallest SLS file:
```
# cat /usr/local/etc/salt/states/runas_bug.sls
test "1" = "1":
  cmd.run:
    - runas: bgdnlp
```

### Steps to Reproduce Issue
With root's default shell, /bin/csh:
```
# salt-call -l info state.sls runas_bug
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://runas_bug
.sls', mode up-to-date
[INFO    ] Running state [test "1" = "1"] at time 16:33:36.160958
[INFO    ] Executing state cmd.run for test "1" = "1"
[INFO    ] Executing command 'test "1" = "1"' as user 'bgdnlp' in directory '/home/bgdnlp'
[ERROR   ] Command 'test "1" = "1"' failed with return code: 1
[ERROR   ] stderr: csh: Permission denied.
[ERROR   ] retcode: 1
[ERROR   ] {'pid': 1279, 'retcode': 1, 'stderr': 'csh: Permission denied.', 'stdout': ''}
[INFO    ] Completed state [test "1" = "1"] at time 16:33:36.218481 duration_in_ms=57.523
local:
----------
          ID: test "1" = "1"
    Function: cmd.run
      Result: False
     Comment: Command "test "1" = "1"" run
     Started: 16:33:36.160958
    Duration: 57.523 ms
     Changes:
              ----------
              pid:
                  1279
              retcode:
                  1
              stderr:
                  csh: Permission denied.
              stdout:

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  57.523 ms
```
After changing shell to /bin/sh and logging in again:
```
# salt-call -l info state.sls runas_bug
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://runas_bug
.sls', mode up-to-date
[INFO    ] Running state [test "1" = "1"] at time 16:40:16.738548
[INFO    ] Executing state cmd.run for test "1" = "1"
[INFO    ] Executing command 'test "1" = "1"' as user 'bgdnlp' in directory '/home/bgdnlp'
[INFO    ] {'pid': 1326, 'retcode': 0, 'stderr': '', 'stdout': ''}
[INFO    ] Completed state [test "1" = "1"] at time 16:40:16.789120 duration_in_ms=50.572
local:
----------
          ID: test "1" = "1"
    Function: cmd.run
      Result: True
     Comment: Command "test "1" = "1"" run
     Started: 16:40:16.738548
    Duration: 50.572 ms
     Changes:
              ----------
              pid:
                  1326
              retcode:
                  0
              stderr:
              stdout:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  50.572 ms
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 12 2017, 01:19:30)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 11.0-RELEASE-p8
         system: FreeBSD
        version: Not Installed
```

**Comment by brd** [comment]
It looks like test is not a builtin with csh, so to use csh you'll need to specify ```/bin/test```.

**Comment by brd** [comment]
Or define the path to include /bin.  i.e.:

``` - env: "PATH=/bin"```

**Comment by niheconomoum** [comment]
I get similarly broken behavior if I use *salt-call(1)*:
 
```csh
xenophon@uxeprdbsdsalt01:~>sudo salt-call state.single cmd.run name='test "1" = "1"' runas=critical
Password:
critical@IRTNOG.NET's Password:
su: krb5_verify_user: Client (critical@IRTNOG.NET) unknown
[ERROR   ] Command 'test "1" = "1"' failed with return code: 1
[ERROR   ] stderr: csh: Permission denied.
[ERROR   ] retcode: 1
[ERROR   ] {'pid': 49955, 'retcode': 1, 'stderr': 'csh: Permission denied.', 'stdout': ''}
local:
----------
          ID: test "1" = "1"
    Function: cmd.run
      Result: False
     Comment: Command "test "1" = "1"" run
     Started: 21:28:41.699715
    Duration: 10035.98 ms
     Changes:   
              ----------
              pid:
                  49955
              retcode:
                  1
              stderr:
                  csh: Permission denied.
              stdout:

Summary for local
------------ 
Succeeded: 0 (changed=1)   
Failed:    1
------------
Total states run:     1
Total run time:  10.036 s
```

If I run the same test state via *salt(1)* (i.e., have it run by the salt-minion daemon), the test state works:

```csh
xenophon@uxeprdbsdsalt01:~>sudo salt uxeprdbsdsalt01\* state.single cmd.run name='test "1" = "1"' runas=critical
uxeprdbsdsalt01.irtnog.net:
----------
          ID: test "1" = "1"
    Function: cmd.run
      Result: True
     Comment: Command "test "1" = "1"" run
     Started: 21:29:44.841151
    Duration: 315.365 ms
     Changes:   
              ----------
              pid:
                  50067
              retcode:
                  0
              stderr:
              stdout:

Summary for uxeprdbsdsalt01.irtnog.net
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 315.365 ms
```

If I had to guess, it's likely related to the fact that *salt-call* runs interactively while connected to a TTY.  I've noticed other cases where sub-processes of *salt-call* think they're connected to a TTY.  For example, the mail/postfix package's post-install script will prompt the user interactively if connected to a TTY, which causes package installation to hang when run via *salt-call*.  (One has to type blindly in order to answer the unseen post-install prompt.)

I'm running close to the same versions of everything as @bgdnlp:

```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 5.4.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb  4 2017, 17:32:56)
   python-gnupg: 0.3.9
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 10.3-RELEASE-p11
         system: FreeBSD
        version: Not Installed
```

**Comment by xenophonf** [comment]
I get similarly broken behavior if I use *salt-call(1)*:
 
```csh
xenophon@uxeprdbsdsalt01:~>sudo salt-call state.single cmd.run name='test "1" = "1"' runas=critical
Password:
critical@IRTNOG.NET's Password:
su: krb5_verify_user: Client (critical@IRTNOG.NET) unknown
[ERROR   ] Command 'test "1" = "1"' failed with return code: 1
[ERROR   ] stderr: csh: Permission denied.
[ERROR   ] retcode: 1
[ERROR   ] {'pid': 49955, 'retcode': 1, 'stderr': 'csh: Permission denied.', 'stdout': ''}
local:
----------
          ID: test "1" = "1"
    Function: cmd.run
      Result: False
     Comment: Command "test "1" = "1"" run
     Started: 21:28:41.699715
    Duration: 10035.98 ms
     Changes:   
              ----------
              pid:
                  49955
              retcode:
                  1
              stderr:
                  csh: Permission denied.
              stdout:

Summary for local
------------ 
Succeeded: 0 (changed=1)   
Failed:    1
------------
Total states run:     1
Total run time:  10.036 s
```

If I run the same test state via *salt(1)* (i.e., have it run by the salt-minion daemon), the test state works:

```csh
xenophon@uxeprdbsdsalt01:~>sudo salt uxeprdbsdsalt01\* state.single cmd.run name='test "1" = "1"' runas=critical
uxeprdbsdsalt01.irtnog.net:
----------
          ID: test "1" = "1"
    Function: cmd.run
      Result: True
     Comment: Command "test "1" = "1"" run
     Started: 21:29:44.841151
    Duration: 315.365 ms
     Changes:   
              ----------
              pid:
                  50067
              retcode:
                  0
              stderr:
              stdout:

Summary for uxeprdbsdsalt01.irtnog.net
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 315.365 ms
```

If I had to guess, it's likely related to the fact that *salt-call* runs interactively while connected to a TTY.  I've noticed other cases where sub-processes of *salt-call* think they're connected to a TTY.  For example, the mail/postfix package's post-install script will prompt the user interactively if connected to a TTY, which causes package installation to hang when run via *salt-call*.  (One has to type blindly in order to answer the unseen post-install prompt.)

I'm running close to the same versions of everything as @bgdnlp:

```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 5.4.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb  4 2017, 17:32:56)
   python-gnupg: 0.3.9
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 10.3-RELEASE-p11
         system: FreeBSD
        version: Not Installed
```

**Comment by brd** [comment]
@xenophonf I use this to get around the prompt:

```  environ.setenv:
    - name: POSTFIX_DEFAULT_MTA
    - value: 'yes'
    - update_minion: True```

Though I am not sure if that is a salt but or a pkg bug.. I kinda lean toward that being a salt bug, since it doesn't show you the prompt.

**Comment by xenophonf** [comment]
My point is that I expect *salt-call* to run sub-processes in an environment substantially similar to that of *salt-minion*.  Postfix installs just fine in the latter case because its post-install script checks for an interactive terminal.

**Comment by brd** [comment]
Right, I agree, but in my case I want the ```/etc/mail/mailer.conf``` to be tweaked to used postfix, so I use the code above to make that happen either way.

**Comment by bgdnlp** [comment]
It's not the PATH and it's not that test isn't built into csh. Changing the command to /bin/test has the same result. My initial use case was running `find` to check if a file is older than a week in order to make Salt only check for updates in a git repo weekly. It failed on every run. Basically any kind of `unless` or `onlyif` that runs as a different user returns false always.

Calling the state from master isn't desirable and it doesn't work in a masterless setup.

**Comment by Ch3LL** [comment]
I'm not able to replicate this as shown below:

```
root@ch3ll-free:~ # freebsd-version -k
11.0-RELEASE-p2
root@ch3ll-free:~ # salt --version
salt 2016.11.1 (Carbon)
root@ch3ll-free:~ # salt-call --local state.single cmd.run name='test "1" = "1"' runas=ch3ll
local:
----------
          ID: test "1" = "1"
    Function: cmd.run
      Result: True
     Comment: Command "test "1" = "1"" run
     Started: 18:25:23.426082
    Duration: 67.771 ms
     Changes:   
              ----------
              pid:
                  3469
              retcode:
                  0
              stderr:
              stdout:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  67.771 ms
root@ch3ll-free:~ # echo $SHELL
/bin/csh
```

as you can see csh is shell of root i'm on version 2016.11.1 of salt and command runs fine. Any help trying to replicate this? Is there something wrong with my test case, etc?

**Comment by bgdnlp** [comment]
Ok, weird. Try this. Add a new user by running `adduser` command. Use the defaults, except when you get to "Login group is newuser. Invite newuser into other groups? []:", type wheel. Now try to execute as that user.

Even weirder is that if I try to add a new user to wheel AFTER it was created (`pw usermod user -G wheel`), Salt doesn't fail.

I'm really curious if it an be reproduced that way. I added a new user to my system without adding 'wheel' to its groups, Salt ran fine. I added the user to wheel, Salt still ran fine. Added another new user and made it part of wheel during adduser's questions, Salt returned "Permission denied". If you can reproduce it, it must be something that `adduser` does. `adduser` is just a shell script.

**Comment by Ch3LL** [comment]
Okay i'm able to replicate. I created a new clean box and ran adduser while adding the user to the wheel group.

```
root@ch3ll-freebsd:~ # id ch3ll
uid=1001(ch3ll) gid=1001(ch3ll) groups=1001(ch3ll),0(wheel)
```

```
local:
----------
          ID: test "1" = "1"
    Function: cmd.run
      Result: False
     Comment: Command "test "1" = "1"" run
     Started: 22:38:44.328078
    Duration: 83.082 ms
     Changes:   
              ----------
              pid:
                  3163
              retcode:
                  1
              stderr:
                  csh: Permission denied.
              stdout:

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  83.082 ms
```

So it seems this is an issue with how adduser is working. did everyone else in this issue have the same setup with having used adduser?

**Comment by MEschenbacher** [comment]
I am running into the same issue now with
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 10 2019, 08:04:55)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE-p10
         system: FreeBSD
        version: Not Installed
```
