### ISSUE TITLE
Error in Saltstack's rest auth "Authentication module threw 'status' "

### ISSUE THREAD

**Issue by alankrita** [saltstack/salt#39683]
### Salt's rest auth is giving 401 error with exception _Authentication module threw 'status'_ . I am using rest_cherrypy module.
While debugging I found that [rest.auth](https://github.com/saltstack/salt/blob/2016.11/salt/auth/rest.py#L50) method requires 'status' in the http.query result. The method works if I pass 'status=True' in this function https://github.com/saltstack/salt/blob/2016.11/salt/auth/rest.py#L61  

### Setup

Master's configuration - 
```
interface: 0.0.0.0

rest_cherrypy:
  port: 8001
  host: 0.0.0.0
  disable_ssl: true

external_auth:
      rest:
        ^url: http://172.17.0.1:5000/api/login
        saltdev:
            - .*
            - '@wheel'
            - '@runner'
            - '@jobs'

ping_on_rotate: True
file_recv: True
runner_dirs: ['/srv/salt/_runners',]
```
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue

1. Use external auth as described in https://docs.saltstack.com/en/latest/ref/auth/all/salt.auth.rest.html 
2. Try salt's rest login api
3. See master and salt-api logs

### Versions Report
`Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty
`
