### ISSUE TITLE
iptables save: False ignored

### ISSUE THREAD

**Issue by schaarsc** [saltstack/salt#39695]
```
ipt_chain_present:
  iptables.chain_present:
    - name: TEST

ipt_save_true:
  iptables.append:
    - chain: TEST
    - protocol: tcp
    - dport: http
    - jump: ACCEPT
    - save: True

ipt_save_false:
  iptables.append:
    - chain: TEST
    - protocol: tcp
    - dport: https
    - jump: ACCEPT
    - save: False

ipt_save_true_2:
  iptables.append:
    - chain: TEST
    - protocol: tcp
    - dport: ftp
    - jump: ACCEPT
    - save: True

```
generates
```
:TEST - [0:0]
-A TEST -p tcp -m tcp --dport 80 -j ACCEPT
-A TEST -p tcp -m tcp --dport 443 -j ACCEPT
-A TEST -p tcp -m tcp --dport 21 -j ACCEPT
```

because of save:False I'd expect only two entries in the rules file.
if ipt_save_false is moved to the end of the file I find only two entries in the rules file.

### Versions Report
master: 2016.11.1
minion: 2016.11.1
