### ISSUE TITLE
Feature-Request: Allow multiple modules specified for salt.states.apache_module.enabled

### ISSUE THREAD

**Issue by pepoluan** [saltstack/salt#39706]
### Description of Issue/Question

Sometimes we need to enable several Apache modules. The current implementation of `salt.states.apache_module.enabled` allows only exactly one module to be enabled in a state, which means we are forced to create multiple states to enable multiple modules.

I suggest adding a feature, similar to `salt.states.pkg.installed`, that enables specifying multiple modules to enable. To make it simlar to `salt.states.pkg.installed`, let's call the new parameter `modules`

### Setup/Example

Currently we have to do the following:

```
proxy:
  apache_module.enabled: []

proxy_ajp:
  apache_module.enabled: []

proxy_http:
  apache_module.enabled: []

rewrite:
  apache_module.enabled: []

ssl:
  apache_module.enabled: []

macro:
  apache_module.enabled: []
```

By implementing my suggestion, we can specify it more succinctly as such:

```
required apache modules:
  apache_module.enabled:
    - modules:
      - proxy
      - proxy_ajp
      - proxy_html
      - rewrite
      - ssl
      - macro
```

Cleaner and easier to maintain.

And more importantly: **Allows specification of modules to be declared in pillars**
