### ISSUE TITLE
mount.mounted remounts already correctly mounted mountpoint if option 'size' is set

### ISSUE THREAD

**Issue by Rabattkarte** [saltstack/salt#39716]
### Description of Issue/Question
Everytime I run a `mount.mounted` state with the option `size=150M`, the state will force a remount, because mount options "changed". This seems like a bug to me.

### Setup
My sls-file:
```
/var/spool/clamav:
  file.directory:
    - user: clamav
    - group: clamav
    - dir_mode: 750
    - require:
      - pkg: install clamav

tmpfs for clamav /var/spool/clamav mounted:
  mount.mounted:
    - name: /var/spool/clamav
    - device: tmpfs
    - fstype: tmpfs
    - opts:
      - nosuid
      - noexec
      - nodev
      - rw
      - size=150M
    - persist: True
    - require:
      - file: /var/spool/clamav
```

### Steps to Reproduce Issue
```
[testminion ~]# salt-call state.apply
local:
----------
          ID: mount
    Function: 244./var/spool/clamav
        Name: tmpfs for clamav /var/spool/clamav mounted
      Result: True
     Comment: Target was already mounted. Entry already exists in the fstab.
     Started: 13:59:11.519588
    Duration: 79.052 ms
     Changes:   
              ----------
              umount:
                  Forced remount because options (size=150M) changed

Summary for local
--------------
Succeeded: 260 (changed=1)
Failed:      0
--------------
Total states run:     260
Total run time:     5.390 s
```
The mount options do not change:
```
[testminion ~]# mount | grep clamav
tmpfs on /var/spool/clamav type tmpfs (rw,nosuid,nodev,noexec,relatime,size=153600k)
[testminion ~]# grep clamav /etc/fstab 
tmpfs		/var/spool/clamav	tmpfs	nosuid,noexec,nodev,rw,size=150M	0 0
```
This state will always have changes. This is because salt does not convert between units. In this case Mebibyte (150M) gets converted to Kibibyte (153600k).
### Versions Report
```
[testminion ~]# salt-call --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 4.4.35+90-ph
         system: Linux
        version: debian 8.6
```

**Comment by The-Loeki** [comment]
They went bonkers with a plethora of options in state `mount.mounted` for this very reason; check
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.mount.html#salt.states.mount.mounted
* extra_mount_invisible_keys
* extra_ignore_fs_keys
* extra_mount_translate_options
* hidden_opts

You should be able to do what you want to achieve with these options

**Comment by gtmanfred** [comment]
@Rabattkarte can you review the comment from @The-Loeki 

Thanks!
Daniel

**Comment by sebw** [comment]
I was facing the same issue with this bit of state:

```
squid-tmpfs-mount-cache:
  mount.mounted:
    - name: /mnt/tmpfs/squid_cache
    - device: tmpfs
    - fstype: tmpfs
    - mkmnt: True
    - mount: True
    - opts: "rw,size=2G,uid=squid,gid=squid,mode=0750"
    - require:
      - pkg: squid-pkg
      - file: squid-tmpfs-cache
      - file: squid-tmpfs-logs

squid-tmpfs-mount-logs:
  mount.mounted:
    - name: /mnt/tmpfs/squid_logs
    - device: tmpfs
    - fstype: tmpfs
    - mkmnt: True
    - mount: True
    - opts: "rw,size=5G,uid=squid,gid=squid,mode=0750"
    - require:
      - pkg: squid-pkg
      - file: squid-tmpfs-cache
      - file: squid-tmpfs-logs
```

Following @The-Loeki comment, I checked the output of `cat /proc/self/mountinfo` and found:

```
45 61 0:39 / /mnt/tmpfs/squid_cache rw,relatime shared:95 - tmpfs tmpfs rw,seclabel,size=2097152k,mode=750,uid=23,gid=23
149 61 0:40 / /mnt/tmpfs/squid_logs rw,relatime shared:98 - tmpfs tmpfs rw,seclabel,size=5242880k,mode=750,uid=23,gid=23
```

I updated my state like this (udpated size in kB and mode) and now it doesn't remount:

```
squid-tmpfs-mount-cache:
  mount.mounted:
    - name: /mnt/tmpfs/squid_cache
    - device: tmpfs
    - fstype: tmpfs
    - mkmnt: True
    - mount: True
    - opts: "rw,size=2097152k,uid=squid,gid=squid,mode=750"
    - require:
      - pkg: squid-pkg
      - file: squid-tmpfs-cache
      - file: squid-tmpfs-logs

squid-tmpfs-mount-logs:
  mount.mounted:
    - name: /mnt/tmpfs/squid_logs
    - device: tmpfs
    - fstype: tmpfs
    - mkmnt: True
    - mount: True
    - opts: "rw,size=5242880k,uid=squid,gid=squid,mode=750"
    - require:
      - pkg: squid-pkg
      - file: squid-tmpfs-cache
      - file: squid-tmpfs-logs
```
