### ISSUE TITLE
Passing password AND empty_password=True to states.user.present causes KeyError

### ISSUE THREAD

**Issue by tgoodlet** [saltstack/salt#39741]
### Description of Issue/Question
Passing a `password` and `empty_password=True` to `states.user.present` causes a `KeyError` due to a lookup for `user.chpasswd` module func which doesn't exist.

### Setup
Even though it was a mistake on my part a simple state file which pushes a single user like so,
```yaml
saltvirt:                    
  user.present:              
    - fullname: saltvirt user
    - shell: /bin/bash       
    - home: /home/saltvirt   
    - empty_password: True   
    - password: virty        
    - groups:                
      - wheel                
```
causes a `KeyError`:

### Steps to Reproduce Issue
```bash
salt-call --local state.sls salt_virt/users -l debug
local:
----------
          ID: saltvirt
    Function: user.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/home/tyler/repos/salt/salt/state.py", line 1812, in call
                  **cdata['kwargs'])
                File "/home/tyler/repos/salt/salt/loader.py", line 1725, in wrapper
                  return f(*args, **kwargs)
                File "/home/tyler/repos/salt/salt/states/user.py", line 553, in present
                  __salt__['user.ch{0}'.format(key)](name, val)
                File "/home/tyler/repos/salt/salt/loader.py", line 1096, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/home/tyler/repos/salt/salt/utils/lazy.py", line 101, in __getitem__
                  raise KeyError(key)
              KeyError: 'user.chpasswd'
     Started: 17:36:56.348537
    Duration: 391.795 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 391.795 ms
```
I'm running off the `develop` branch : `Salt: 2016.11.0-890-g98b648d`
I have a simple fix I'll put up a PR shortly.
