### ISSUE TITLE
archive.extracted is broken for HTTP sources

### ISSUE THREAD

**Issue by Magomogo** [saltstack/salt#39751]
### Description of Issue/Question

Starting from release 2016.11.3 I cannot use `archive.extracted`. Instead of extracting archive I got an exception. In 2016.11.2 all works fine.

### Setup

archive-extracted-case.sls:
```
/tmp/archive-extracted-case:
  archive.extracted:
    - source: https://github.com/Magomogo/days-interval/archive/v0.1.0.tar.gz
    - skip_verify: true
```

### Steps to Reproduce Issue

First execution went fine:

```
$ sudo salt-call --local state.apply archive-extracted-case
local:
----------
          ID: /tmp/archive-extracted-case
    Function: archive.extracted
      Result: True
     Comment: https://github.com/Magomogo/days-interval/archive/v0.1.0.tar.gz extracted to /tmp/archive-extracted-case/
     Started: 11:03:51.861965
    Duration: 47.838 ms
     Changes:
              ----------
              directories_created:
                  - /tmp/archive-extracted-case/
              extracted_files:
                  - days-interval-0.1.0
                  - days-interval-0.1.0/.gitignore
                  - days-interval-0.1.0/.jscsrc
                  - days-interval-0.1.0/.jshintrc
                  - days-interval-0.1.0/.travis.yml
                  - days-interval-0.1.0/LICENSE
                  - days-interval-0.1.0/README.md
                  - days-interval-0.1.0/index.js
                  - days-interval-0.1.0/package.json
                  - days-interval-0.1.0/tests
                  - days-interval-0.1.0/tests/interval.test.js

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  47.838 ms
```

Second run causes the error:

```
local:
----------
          ID: /tmp/archive-extracted-case
    Function: archive.extracted
      Result: False
     Comment: Failed to list contents of /var/cache/salt/minion/files/project/_Magomogo_days-interval_archive_v0.1.0.tar.gz: [Errno 2] No such file or directory: '/var/cache/salt/minion/files/project/_Magomogo_days-interval_archive_v0.1.0.tar.gz'. Additional info follows:

              archive location:
                  /var/cache/salt/minion/files/project/_Magomogo_days-interval_archive_v0.1.0.tar.gz

              If the source archive is a tar archive compressed using a compression type not natively supported by the tar command, then setting the 'list_options' argument may allow the contents to be listed. Otherwise, if Salt is unable to determine the files/directories in the archive, the following workaround(s) would need to be used for this state to proceed (assuming the source file is a valid tar archive):

              - 'if_missing' must be set
     Started: 11:05:06.703406
    Duration: 56.711 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  56.711 ms
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
```

**Comment by gtmanfred** [comment]
I have replicated this issue.

@terminalmage could you take a look when you get a minute?

Thanks,
Daniel

**Comment by terminalmage** [comment]
This regressed in ``file.get_managed`` in https://github.com/saltstack/salt/pull/39438. I opened https://github.com/saltstack/salt/pull/39762 just now to fix this and add integration tests to prevent future regression.

**Comment by Reiner030** [comment]
Additional info to in 2016.1.3 introduced bug - is related to this issue and I hope same cause with state definition:
````
{% set nr_gearman_plugin_chgr_main = 'https://github.com/channelgrabber/newrelic-gearman-plugin' %}
{% set nr_gearman_plugin_chgr      = nr_gearman_plugin_chgr_main ~ '/releases/latest' %}
{% set nr_gearman_plugin_version   = salt['cmd.shell']('curl -sI ' ~ nr_gearman_plugin_chgr ~ '| sed -ne "s#^Location: .*tag/##p"') %}
{% set nr_gearman_plugin_md5sum    = salt['cmd.shell']('curl -sL ' ~ nr_gearman_plugin_chgr_main ~ '/archive/' ~ nr_gearman_plugin_version ~ '.tar.gz | md5sum | sed -e "s/ *-.*//"') %}

newrelic-gearman-plugin-extract:
  archive.extracted:
    - name: /opt
    - source: {{ nr_gearman_plugin_chgr_main }}/archive/{{ nr_gearman_plugin_version }}.tar.gz
    - source_hash: md5={{ nr_gearman_plugin_md5sum }}
    - archive_format: tar
    - options: z
    - user: newrelic
    - group: newrelic
    - if_missing: /opt/newrelic-gearman-plugin-{{ nr_gearman_plugin_version }}/Gemfile
    - watch_in:
        - cmd: newrelic-gearman-plugin-run-bundler
````

which gaves finally:

````
newrelic-gearman-plugin-extract:
  archive.extracted:
    - name: /opt
    - source: https://github.com/channelgrabber/newrelic-gearman-plugin/archive/0.2.0.tar.gz
    - source_hash: md5=6dfe6200cc15bd5315e8dad4a3e1dc0c
    - archive_format: tar
    - options: z
    - user: newrelic
    - group: newrelic
    - if_missing: /opt/newrelic-gearman-plugin-0.2.0/Gemfile
    - watch_in:
        - cmd: newrelic-gearman-plugin-run-bundler
````

I got also since update
* testing errors:
````
test-offv-03:
----------
          ID: newrelic-gearman-plugin-extract
    Function: archive.extracted
        Name: /opt
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/archive.py", line 1354, in extracted
                  if dir_result.get('pchanges'):
              AttributeError: 'str' object has no attribute 'get'
     Started: 07:03:56.518144
    Duration: 8.295 ms
     Changes:
````
* non-test mode:
````
[WARNING ] Bad state return Directory /opt/newrelic-gearman-plugin-0.2.0 is in the correct state for file.directory state on newrelic-gearman-plugin-0.2.0/
````


The interesting part is that similar state below still works fine - only user/group parameters are different:
````
# https://github.com/newrelic-platform/newrelic_mysql_java_plugin/archive/2.0.0.tar.gz

{%- set nr_mysql_java_plugin_main    = 'https://github.com/newrelic-platform/newrelic_mysql_java_plugin' %}
{%- set nr_mysql_java_plugin_latest  = nr_mysql_java_plugin_main ~ '/releases/latest' %}
{%- set nr_mysql_java_plugin_version = salt['cmd.shell']('curl -sL ' ~ nr_mysql_java_plugin_latest ~ "| sed -ne 's#^.*tag/\([0-9.]\+\)\">.*#\\1#p' | head -n 1 | tr -d '\n'") %}
{%- set nr_mysql_java_plugin_md5sum  = salt['cmd.shell']('curl -sL ' ~ nr_mysql_java_plugin_main ~ '/archive/' ~ nr_mysql_java_plugin_version ~ '.tar.gz | md5sum | sed -e "s/ *-.*//"') %}

newrelic_mysql_java_plugin-fetch-and-extract:
  archive.extracted:
    - name: /opt/
    - source: {{ nr_mysql_java_plugin_main }}/archive/{{ nr_mysql_java_plugin_version }}.tar.gz
    - source_hash: md5={{ nr_mysql_java_plugin_md5sum }}
    - archive_format: tar
    - options: z
    - if_missing: /opt/newrelic_mysql_java_plugin-{{ nr_mysql_java_plugin_version }}
````
which gaves finally:
````
newrelic_mysql_java_plugin-fetch-and-extract:
  archive.extracted:
    - name: /opt/
    - source: https://github.com/newrelic-platform/newrelic_mysql_java_plugin/archive/2.0.0.tar.gz
    - source_hash: md5=d90b2227727bf59417cc49c8309e1bb6
    - archive_format: tar
    - options: z
    - if_missing: /opt/newrelic_mysql_java_plugin-2.0.0
````
