### ISSUE TITLE
pkgrepo.managed state always report changes with test=True on APT system

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt#39778]
### Description of Issue/Question
This bug is similar to  #31963. Apparently it was fixed for RPM (though I personally haven't tried it), but it seems that APT still has the same problem.
### Setup
Master and minion are Debian 8 amd64, my test case:
```
{% set codename = grains['oscodename'] %}

repository_pgdg:
  pkgrepo.managed:
    - file: /etc/apt/sources.list.d/pgdg.list
    - clean_file: True
    - name: deb http://apt.postgresql.org/pub/repos/apt/ {{ codename }}-pgdg main
    - comments: 
        - 'THIS FILE IS MANAGED BY SALT! DO NOT EDIT MANUALLY!'
    - key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

```

### Steps to Reproduce Issue
I've applied stated and got successfull changes (that's OK):
```
root@vostro:~# salt test state.apply repository_test
test:
----------
          ID: repository_pgdg
    Function: pkgrepo.managed
        Name: deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main
      Result: True
     Comment: Configured package repo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main'
     Started: 08:54:51.749785
    Duration: 7235.159 ms
     Changes: 
```

But after that, if I apply with `test=True`, I get changes again (shouldn't be), that "will be configured":
```
root@vostro:~# salt test state.apply repository_test test=True
test:
----------
          ID: repository_pgdg
    Function: pkgrepo.managed
        Name: deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main
      Result: None
     Comment: Package repo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' will be configured. This may cause pkg states to behave differently than stated if this action is repeated without test=True, due to the differences in the configured repositories.
     Started: 08:57:21.943266
    Duration: 52.8 ms
     Changes:   
```
Though if I again execute without `test=True`, I get no actual changes applied.

### Versions Report
Salt Version:
           Salt: 2016.3.5
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7

**Comment by vieira** [comment]
We have some minions running an older version of salt (2015.5.3 Lithium) that don't have this problem, seems to be a regression in 2016.x.

**Comment by Ch3LL** [comment]
@vieira I'm able to replicate this on 2015.5.3 as shown below:

```
local:
----------
          ID: repository_pgdg
    Function: pkgrepo.managed
        Name: deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main
      Result: None
     Comment: Package repo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' will be configured. This may cause pkg states to behave differently than stated if this action is repeated without test=True, due to the differences in the configured repositories.
     Started: 20:34:02.687895
    Duration: 24.776 ms
     Changes:   

Summary
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
root@e7def454278d:/testing# salt --version
salt 2015.5.3 (Lithium)
```

@vieira  Can you share your state?

It seems to not be hitting this else statement [here](https://github.com/saltstack/salt/blob/v2016.11.3/salt/states/pkgrepo.py#L408)


Here is a docker container to quickly replicate the issue:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:39778 salt-call --local state.sls test test=True` ( where /home/ch3ll/git/salt is alocal cloned git repo of salt)

**Comment by vieira** [comment]
Hello @Ch3LL 

Oops, sorry. You are right, it does not appear to be related only with 2016.x. I updated some more minions in the last few days and now have some in 2016.11.3 where this happens and some where it does not. 

So here are some where it does not happen (running version 2016.11.3+ds-1):
(also tested without humanname, dist and key_url and with clean_file: True. No problems.)

```
gitlab:
  pkgrepo.managed:
    - humanname: GitLab PPA
    - name: deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu xenial main
    - dist: xenial
    - file: /etc/apt/sources.list.d/gitlab.list
    - key_url: https://packages.gitlab.com/gpg.key
    - require_in:
      - pkg: gitlab
  pkg.installed:
    - pkgs:
      - ca-certificates
      - gitlab-ce
      - nfs-common
  service.running:
    - enable: True
    - name: gitlab-runsvdir
```

```
docker:
  pkgrepo.managed:
    - humanname: Docker PPA
    - name: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    - dist: ubuntu-xenial
    - file: /etc/apt/sources.list.d/docker.list
    - keyserver: hkp://ha.pool.sks-keyservers.net:80
    - keyid: 58118E89F3A912897C070ADBF76221572C52609D
    - require_in:
      - pkg: docker
  pkg.installed:
    - pkgs:
      - ca-certificates
      - docker-engine
      - python3-yaml
      - python3-jinja2
      - zfs
      - iptables
  service.running:
    - enable: True
```

However the one below has the problem reported, also on 2016.11.3+ds-1:

```
oracle-java8-installer:
  pkgrepo.managed:
    - ppa: webupd8team/java
  pkg.installed:
    - require:
      - pkgrepo: oracle-java8-installer
  debconf.set:
    - data:
        'shared/accepted-oracle-license-v1-1': {'type': 'boolean', 'value': True}
    - require_in:
      - pkg: oracle-java8-installer
```

with test=true:
```
jupiter1:
----------
          ID: oracle-java8-installer
    Function: pkgrepo.managed
      Result: None
     Comment: Package repo 'oracle-java8-installer' will be configured. This may cause pkg states to behave differently than stated if this action is repeated without test=True, due to the differences in the configured repositories.
     Started: 00:45:21.939951
    Duration: 113.217 ms
     Changes:   

Summary for jupiter1
-------------
Succeeded: 78 (unchanged=1)
Failed:     0
-------------
Total states run:     78
Total run time:    8.915 s
```

and without test=true:
```
jupiter1:

Summary for jupiter1
-------------
Succeeded: 78
Failed:     0
-------------
Total states run:     78
Total run time:   21.395 s
```
