### ISSUE TITLE
Scheduled master job says that function is not available, although the runner exists

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#39774]
### Description of Issue/Question

Executing a runner such as `salt.execute` (https://github.com/saltstack/salt/blob/develop/salt/runners/salt.py#L72) from the CLI, it woks fine:

```
root@ip-172-31-6-12:/etc/salt# salt-run salt.execute device1 test.ping
device1:
    True
```

The runner was configured as external module using the `runner_dirs` option on the master.

Scheduling a job on the master that uses this runner, it complains that the runner is not available:

```
2017-03-02 01:16:52,426 [salt.utils.schedule][ERROR   ][2795] Unhandled exception running salt.execute
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 826, in handle_func
    message=self.functions.missing_fun_string(func))
  File "/usr/lib/python2.7/dist-packages/salt/utils/error.py", line 36, in raise_error
    raise ex(message)
Exception: 'salt.execute' is not available.
```

And throws all the errors from #39667.

Schedule config:

```yaml
schedule:
  proxy_keepalive:
    function: salt.execute
    args:
      - 'I@proxy:proxytype:napalm'
      - 'napalm_proxy.reconnect'
    kwargs:
      tgt_type: compound
    minutes: 1
```

This is on 2016.11.2:

```yaml
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.1.0
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```
