### ISSUE TITLE
Proxy `mine_interval` config ignored

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#39775]
### Description of Issue/Question

Having the following configuration in the pillar of a proxy minion:

```yaml
mine_functions:
  net.interfaces: []
  net.lldp: []
  net.arp: []
mine_interval: 5
```

It will schedule the mine update to the default value:

```
root@ip-172-31-6-12:# cat /etc/salt/proxy.d/_schedule.conf
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false}
```

If the `mine_interval` is specified in the proxy config file, it will schedule it correctly, but it will be the same value for all proxies:

```
root@ip-172-31-6-12:# cat /etc/salt/proxy.d/_schedule.conf
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 5, return_job: false}
```

I have tested on both 2016.11.2 and 2016.11.3.

Anyway, I think that if we want more granular mine update, per proxy, we'd need to have a put the `_schedule.conf` under `/etc/salt/proxy.d/<minion ID>/_schedule.conf` or so.

**Comment by mirceaulinic** [comment]
I think we can extend this to many other use cases when some scheduled jobs are different and/or their timing depends on the minion. 

For example, if we have the scheduling for a proxy as:

```
schedule:
  napalm_keepalive:
    function: napalm_proxy.reconnect
    minutes: 1
```

Specified in the pillar.

We are able to reload:

```
root@ip-172-31-6-12:~# salt device1 schedule.reload
device1:
    ----------
    comment:
        - Reloaded schedule from pillar on minion.
    result:
        True
root@ip-172-31-6-12:~# salt device1 schedule.list
device1:
    schedule:
      napalm_keepalive:
        enabled: true
        function: napalm_proxy.reconnect
        minutes: 10
```

But the `_schedule.conf` file remains unchanged:

```
root@ip-172-31-6-12:~# cat /etc/salt/proxy.d/_schedule.conf
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 5, return_job: false}
  napalm_keepalive: {function: napalm_proxy.reconnect, minutes: 1}
```

So I think there's yet another reason to have a separate `_schedule.conf` per proxy.

**Comment by Ch3LL** [comment]
Seems from your comment that this is not completely fixed with #39776 . Am i interpreting that correctly that you also need to find how to load the schedule.conf alongside saving it?

**Comment by mirceaulinic** [comment]
You are correct @Ch3LL: #39776 does not entirely fix this. There are few more changes required, but I would need some help to identify where's the right place.

**Comment by cro** [comment]
Copying this comment over from #39776:

Oh, I remember now. When we persist the data to the _schedule.conf file, it's in the same format as the regular minion configuration file, and it resides in /etc/salt/proxy.d/. Thus, it gets loaded as part of the regular configuration file processing when the minion starts up.

I think that means that it might be a little harder to handle this since ALL files in /etc/salt/proxy.d get parsed by all proxy processes that start up. I wonder if a better solution is to modify the config parser so that append_minionid_config_dirs includes /etc/salt/proxy.d by default. Then we would have paths like /etc/salt/proxy.d/proxy01/_scheduler.conf. What do you think?

**Comment by mirceaulinic** [comment]
@cachedout @Ch3LL - can we reopen this please? I'm not sure https://github.com/saltstack/salt/pull/40291 is enough or the right way to fix it.

**Comment by cachedout** [comment]
Certainly. Re-opened.

**Comment by mirceaulinic** [comment]
Is there any chance at all we could fix this in Nitrogen? Unfortunately this seems over my head, I don't have further ideas. Some pointers would be greatly appreciated. Thanks!

**Comment by mirceaulinic** [comment]
Ping @cro - would you be able to provide any suggestion?

**Comment by cro** [comment]
@mirceaulinic Looking at this now

**Comment by mirceaulinic** [comment]
Thank you @cro. I have tested a few days ago the Nitrogen branch a few days ago and the scheduling looked fine. However, I didn't check the `mine_interval` option specifically, against multiple proxy minions.

**Comment by mirceaulinic** [comment]
Hi @cro I tested on the Nitrogen branch.
The scheduling works good now, in general: we have a separate `_schedule.confg` directory per proxy minion and the jobs are executed fine.
However, this problem specifically hasn't been solved.
I have this in my device pillar:

```yaml
mine_functions:
  net.arp: []
mine_interval: 1
```

But when starting the process, I can see:

```
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_list_complete; data = {'_stamp': '2017-06-01T12:07:05.331806', 'complete': True, 'schedule': {'__proxy_keepalive': {'function': 'status.proxy_reconnect', 'name': '__proxy_keepalive', 'enabled': True, '_splay': None, 'return_job': False, '_seconds': 60, 'jid_include': True, 'maxrunning': 1, '_next_fire_time': 1496318856, 'kwargs': {'proxy_name': 'napalm'}, 'minutes': 1}, 'enabled': True, '__mine_interval': {'function': 'mine.update', 'name': '__mine_interval', 'enabled': True, '_splay': None, 'return_job': False, '_seconds': 3600, 'jid_include': True, 'maxrunning': 2, '_next_fire_time': 1496322396, 'minutes': 60}}}
```

Which schedules the mine update every 60 minutes (default), not every minute as instructed.

Moreover, it seems like it doesn't fetch any data on start:

```bash
root@ip-172-31-11-15:/etc/salt# salt device2 mine.get device2 net.arp
device2:
    ----------
root@ip-172-31-11-15:/etc/salt# salt device2 mine.get device2 net.lldp
device2:
    ----------
root@ip-172-31-11-15:/etc/salt# salt device2 mine.update
device2:
    True
root@ip-172-31-11-15:/etc/salt# salt device2 mine.get device2 net.arp
device2:
    ----------
    device2:
        ----------
        comment:
        out:
            |_
              ----------
              age:
                  0.0
              interface:
                  GigabitEthernet1
              ip:
                  172.31.32.1
              mac:
                  0A:9A:D7:4C:26:95
            |_
              ----------
              age:
                  0.0
              interface:
                  GigabitEthernet1
              ip:
                  172.31.46.249
              mac:
                  0A:11:AA:BE:C1:0F
        result:
            True
```

So it fetched the mines only after executing manually `mine.update`.

Ping @garethgreenaway: do you have any opinion on this?

Thanks!

**Comment by mirceaulinic** [comment]
Actually, I think I have identified the cause:

I have the following bits in the opts (displayed using test.get_opts):

```yaml
    pillar:
        ----------
        mine_functions:
            ----------
            net.arp:
        mine_interval:
            1
        proxy:
            ----------
            driver:
                ios
```

and

```yaml
    mine_interval:
        60
```

Looks like the values from the pillar are not merged with the values in the opts. I had the feeling they should. Could you please confirm, or correct me?
