### ISSUE TITLE
State function boto_s3_bucket.present problem

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#39817]
### Description of Issue/Question
Trying to create an s3 bucket with Lifecycle Configuration fails:
```
----------
          ID: backup_bucket
    Function: boto_s3_bucket.present
        Name: mybucket
      Result: False
     Comment: Failed to update bucket: An error occurred (MalformedXML) when calling the PutBucketLifecycleConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema.
     Started: 12:37:41.360690
    Duration: 691.869 ms
     Changes:   
----------

```

### Setup
```
backup_bucket:
  boto_s3_bucket.present:
    - name: mybucket
    - Bucket: mybucket
    - LifecycleConfiguration:
        - Expiration:
            Days: 123
          ID: "idstring"
          Prefix: "prefixstring"
          Status: "enabled"
          Transitions:
            - Days: 123
              StorageClass: "GLACIER"
          NoncurrentVersionTransitions:
            - NoncurrentDays: 123
              StorageClass: "GLACIER"
          NoncurrentVersionExpiration:
            NoncurrentDays: 123
```
LifecycleConfiguration is copy/pasted from doc: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_s3_bucket.html#salt.states.boto_s3_bucket.present

### Steps to Reproduce Issue
run the SLS

### Versions Report
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-34-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@zerthimon looks like in your copy/paste there is a difference in the spaces as show below:

```
    - LifecycleConfiguration:
        - Expiration:
            Days: 123
          ID: "idstring"
          Prefix: "prefixstring"
          Status: "enabled"
          Transitions:
            - Days: 123
              StorageClass: "GLACIER"
          NoncurrentVersionTransitions:
            - NoncurrentDays: 123
              StorageClass: "GLACIER"
          NoncurrentVersionExpiration:
            NoncurrentDays: 123
```

vs docs:

```
        - LifecycleConfiguration:
          - Expiration:
              Days: 123
            ID: "idstring"
            Prefix: "prefixstring"
            Status: "enabled",
            ID: "lc1"
            Transitions:
              - Days: 123
                StorageClass: "GLACIER"
            NoncurrentVersionTransitions:
              - NoncurrentDays: 123
                StorageClass: "GLACIER"
            NoncurrentVersionExpiration:
              NoncurrentDays: 123
```

Do you still get the same error if you re copy/paste with the same spacing?

**Comment by zerthimon** [comment]
@Ch3LL Do you mean I'm missing a redundant ID as in the docs ?
` ID: "lc1"` 
It's a mistake that produces YAML dulicate key error (that's why I removed it)

**Comment by zerthimon** [comment]
@Ch3LL 
Yep I've used a correct state (not sure why it got extra indent in issue description)
```
backup_bucket:
  boto_s3_bucket.present:
    - name: a-unique-name-mybucket
    - Bucket: a-unique-name-mybucket
    - LifecycleConfiguration:
      - Expiration:
          Days: 123
        ID: "idstring"
        Prefix: "prefixstring"
        Status: "enabled"
        Transitions:
          - Days: 123
            StorageClass: "GLACIER"
        NoncurrentVersionTransitions:
          - NoncurrentDays: 123
            StorageClass: "GLACIER"
        NoncurrentVersionExpiration:
          NoncurrentDays: 123
```
gives:
```
Failed to update bucket: An error occurred (MalformedXML) when calling the PutBucketLifecycleConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema.
```

**Comment by edgan** [comment]
I am trying to do the same thing, and seeing the same error.

**Comment by edgan** [comment]
The issue in my case is I was doing everything but setting a prefix. The AWS api requires it, but boto3 does not. If I set it empty, like Prefix: '', it worked.

**Comment by mcarlton00** [comment]
Just to chime in: I'm seeing this as well.  The relevant code block:
```
test-s3:
  boto_s3_bucket.present:
    - name: test-s3
    - Bucket: test-s3.saltstack.example
    - LifecycleConfiguration:
      - Expiration:
          Days: 7
        ID: "expire storage"
        Status: "enabled"
    - profile: {{ profile }}
```
and the response when running:
```
[ERROR   ] Failed to create bucket: An error occurred (MalformedXML) when calling the PutBucketLifecycleConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema.
local:
----------
          ID: test-s3
    Function: boto_s3_bucket.present
      Result: False
     Comment: Failed to create bucket: An error occurred (MalformedXML) when calling the PutBucketLifecycleConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema.
     Started: 15:08:06.275110
    Duration: 746.378 ms
     Changes:
```

This happens whether I have a true prefix present, an empty prefix like @edgan, or no prefix defined at all.

**Comment by mcarlton00** [comment]
Update: I found the solution.
```
test-s3:
  boto_s3_bucket.present:
    - name: test-s3
    - Bucket: test-s3.saltstack.example
    - LifecycleConfiguration:
      - Expiration:
          Days: 7
        ID: "expire storage"
        Prefix: ""
        Status: "Enabled"
    - profile: {{ profile }}
```
The "Status" argument MUST be capitalized, otherwise you'll get the MalformedXML error

ie: `Status: "enabled"` will fail, but `Status: "Enabled"` works.
