### ISSUE TITLE
artifactory.downloaded lacks user, group and mode options

### ISSUE THREAD

**Issue by sebw** [saltstack/salt#39818]
I'm using the following state:

```
sosip-war:
  artifactory.downloaded:
   - artifact:
       artifactory_url: {{ maps_artifactory['artifactory-url'] }}
       repository: 'saltstack'
       artifact_id: 'web'
       group_id: 'be.just.fgov.sosip'
       packaging: 'war'
       version: '1.0'
   - target_file: '/var/lib/tomcat/webapps/sosip.war'
```

The file gets downloaded properly, but with that metadata:

```
  File: ‘sosip.war’
  Size: 9899811   	Blocks: 19336      IO Block: 4096   regular file
Device: 801h/2049d	Inode: 50781288    Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Context: unconfined_u:object_r:tomcat_var_lib_t:s0
Access: 2017-03-03 16:02:19.806812644 +0100
Modify: 2017-03-03 16:02:17.180735969 +0100
Change: 2017-03-03 16:02:17.180735969 +0100
 Birth: -
```

This is not a problem in the project I'm working on, as 644 is sufficient to see the WAR getting deployed, but we might want to restrict the mode, user or group in other projects and specific environments.

target_file should take such options like file.managed.

Thoughts?
