### ISSUE TITLE
Salt cloud error : Salt minion gets installed , but minion config file that master writes is missing

### ISSUE THREAD

**Issue by schoudhary-matterport** [saltstack/salt#39824]
### Description of Issue/Question

salt-coud -l debug -p <profile_name> <instance_name>

2017-03-03 19:09:04,255 [salt.utils.cloud ][DEBUG   ][12726] Retrying connection to host 10.230.143.40 on port 22 (try 12)
2017-03-03 19:09:07,254 [salt.utils.cloud ][DEBUG   ][12726] Caught exception in wait_for_port: [Errno 113] No route to host
2017-03-03 19:09:08,255 [salt.utils.cloud ][DEBUG   ][12726] Retrying connection to host 10.230.143.40 on port 22 (try 13)
2017-03-03 19:09:09,265 [salt.utils.cloud ][DEBUG   ][12726] Caught exception in wait_for_port: [Errno 111] Connection refused
2017-03-03 19:09:10,266 [salt.utils.cloud ][DEBUG   ][12726] Retrying connection to host 10.230.143.40 on port 22 (try 14)
2017-03-03 19:09:10,267 [salt.utils.cloud ][DEBUG   ][12726] Caught exception in wait_for_port: [Errno 111] Connection refused
2017-03-03 19:09:11,268 [salt.utils.cloud ][DEBUG   ][12726] Retrying connection to host 10.230.143.40 on port 22 (try 15)
2017-03-03 19:09:11,269 [salt.utils.cloud ][DEBUG   ][12726] Caught exception in wait_for_port: [Errno 111] Connection refused
2017-03-03 19:09:12,270 [salt.utils.cloud ][DEBUG   ][12726] Retrying connection to host 10.230.143.40 on port 22 (try 16)
2017-03-03 19:09:12,271 [salt.utils.cloud ][DEBUG   ][12726] Caught exception in wait_for_port: [Errno 111] Connection refused
2017-03-03 19:09:13,272 [salt.utils.cloud ][DEBUG   ][12726] Retrying connection to host 10.230.143.40 on port 22 (try 17)
2017-03-03 19:09:13,273 [salt.utils.cloud ][DEBUG   ][12726] Caught exception in wait_for_port: [Errno 111] Connection refused
2017-03-03 19:09:14,274 [salt.utils.cloud ][DEBUG   ][12726] Retrying connection to host 10.230.143.40 on port 22 (try 18)
2017-03-03 19:09:14,275 [salt.utils.cloud ][DEBUG   ][12726] Using /etc/salt/ssh.keys.d/mp_env_st6.pem as the key_filename
2017-03-03 19:09:14,275 [salt.utils.cloud ][DEBUG   ][12726] Attempting to authenticate as ubuntu (try 1 of 15)
2017-03-03 19:09:14,276 [salt.utils.cloud ][DEBUG   ][12726] SSH command: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /etc/salt/ssh.keys.d/mp_env_st6.pem -p 22 ubuntu@10.230.143.40 date'
2017-03-03 19:09:14,297 [salt.utils.vt    ][DEBUG   ][12726] Child Forked! PID: 12893  STDOUT_FD: 4  STDERR_FD: 7

after this the salt cloud process completes 

### Setup
/etc/salt/cloud.profiles.d/st6.conf
```
st6_circle:
  sync_after_install: all
  script: matterport
  delvol_on_destroy: True
  key_name: st6_admin
  ssh_username: ubuntu
  rename_on_destroy: True
  image: ami-e68f89f1
  provider: st6
  size: c3.2xlarge
```
```
st6:
  minion:
    master: ip-10-147-221-38.ec2.internal
  grains:
    mp_env: st6
    bootstrap_clean: False
  ssh_interface: private_ips
  # Set the EC2 access credentials (see below)
  id: XXXXXXXXXXXXXX
  key: XXXXXXXXXXXXXX
  private_key:<path to pen file>
  keyname: XXXXXXXX
  securitygroup: st1-dev
  location: us-east-1
  ssh_username: ubuntu
  iam_profile: 'circle-role'
  provider: ec2
```
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
             Salt: 2015.5.11
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.12
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 2.6.0
```
