### ISSUE TITLE
Difference between config.option and config.merge

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#39827]
### Description of Issue/Question

Looking at the doc: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.config.html#salt.modules.config.option, it's not obvious to me what's the difference between `config.option` and `config.merge`?

`Same as option() except that it merges all matches, rather than taking the first match.` what's that first match (i.e. what's the order)?
Also: how's the merging? e.g.:

having in the pillar:

```yaml
option:
  sub-option:
    sub-sub-option: 5
  another-sub-option: foo
```

merged with the minion opt:

```yaml
option:
  sub-option:
    sub-sub-option: 100
```

Would the result be:

```yaml
option:
  sub-option:
    sub-sub-option: 100
  another-sub-option: foo
```

Again, I guess this depends on the order they are considered.

I feel like this topic needs to be augmented a bit.

Thanks!
