### ISSUE TITLE
x509 signing policy restrict CN based on pillar or grains

### ISSUE THREAD

**Issue by nvx** [saltstack/salt#39845]
The x509 state seems like quite a versatile module, although one area that it seems to be lacking is if you want to securely issue a certificate for every node while enforcing the certificate CN to be something controlled (eg, pillar or grain data). At the moment as far as I can tell the options are either force a signing policy to always force a specific CN, or allow the minion to use any CN. The former might work where you have a cluster of web servers that all need the same certificate, but it doesn't really work for issuing unique per-host certificates.

The most obvious usecase is where you wish to force the CN to be the minion id ("id" grain), although I can see it being useful being able to reference pillar data as well.

**Comment by Ch3LL** [comment]
maybe i'm not quit following but couldn't you just add something like the following to your state:

```
/etc/pki/ca.crt:
  x509.certificate_managed:
    - signing_private_key: /etc/pki/ca.key
    - CN: {{ pillar['cn_name'] }} 
```

or a grain value there? Can you clarify what you are requesting a little more thanks.
