### ISSUE TITLE
MySQL lower_case_table_names results in grant failure

### ISSUE THREAD

**Issue by ScoreUnder** [saltstack/salt#39847]
### Description of Issue/Question

If mysql's `lower_case_table_names` variable is `1` or `2`, then the `mysql_grants.present` state will fail for any table containing a capital letter.

To everyone else reading, please remember never to use camel-cased database or table names in MySQL. It will lead you down a path of endless pain and misery. Keep it all lowercase. Salt is not the first program to trip up on this, and probably won't be the last.

### Setup

```yaml
mysql_perms_SomeDB:
  mysql_grants.present:
    - grant: 'ALL PRIVILEGES'
    - database: 'SomeDB.*'
    - user: myuser
    - host: localhost
```

Run `mysqld` with `--lower-case-table-names=1`, then create a `SomeDB` database and a `myuser` user. If you're on a case-insensitive filesystem, it may also be worth testing with `--lower-case-table-names=2`.

### Steps to Reproduce Issue

1. Set up as described above
2. After creating the new database on the newly configured `mysqld`, run the salt state
3. Observe reported failure, while the grant in fact succeeded

### Versions Report

```
Salt Version:
           Salt: 2016.11.0-260-g1e1ea18
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul 14 2015, 19:46:27)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 14.5.0
         system: Darwin
        version: 10.10.5 x86_64
```
