### ISSUE TITLE
correctly handled onfail requisites should have returncode==0

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#39873]
### Description of Issue/Question

Returncode  (eg via state.sls) of state executions where onfail requisites are used is currently non null, even if states are handled via onfail, and those onfail states suceed

### Steps to Reproduce Issue
```yaml
will_fail:
  cmd.run:
    - name: /bin/false

will_fail_i:
  cmd.run:
    - name: /bin/false
    - onfail_in:
      - cmd: handler_i

handler:
  cmd.run:
    - name: /bin/true
    - onfail:
      - cmd: will_fail

handler_i:
  cmd.run:
    - name: /bin/true
```

here RC==2 .

(Include debug logs if possible and relevant.)

### Versions Report
2016.11
