### ISSUE TITLE
Salt-SSH reflects certain minion's opts as master opts for rendering

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#39892]
### Description of Issue/Question
Salt-SSH reflects the minion options back to the Pillar code when it wants a rendered pillar.
This leads to unexpected and possibly dangerous behaviour.

### Setup / Steps to Reproduce Issue
Salt SSH config:
```yaml
git_pillar_provider: gitpython
gitfs_provider: gitpython

fileserver_backend:
  - git

ext_pillar:
  - git:
    - ssh://git@git.example.com/salt-example.git:
      - root: pillar

ssh_minion_opts:
  git_pillar_provider: imateapot
  gitfs_provider: imateapot
```

```
(...)
[DEBUG   ] gitpython gitfs_provider enabled
(...)
[CRITICAL] Invalid git_pillar_provider 'imateapot'. Valid choices are: gitpython, pygit2
```
### Versions report
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.24.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.13 (default, Jan 12 2017, 17:59:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: fedora 25 Twenty Five
        machine: x86_64
        release: 4.9.13-200.fc25.x86_64
         system: Linux
        version: Fedora 25 Twenty Five
```
