### ISSUE TITLE
"salt-run state.orchestrate" always return True

### ISSUE THREAD

**Issue by rmjstn** [saltstack/salt#39917]
### Description of Issue/Question

"salt-run state.orchestrate" always return true.

### Setup

I wrote this state (which failed) :

```
step-1:
  salt.function:
    - name: file.touch
    - arg:
      - /tmp/toto
    - tgt: 'perle-minion'
    - require:
      - salt: step-2

step-2:
  salt.function:
    - name: file.touch
    - arg:
      - /toto/titi                <<<<<<<<<<< folder doesn't exist
    - tgt: 'perle-minion'
```

### Steps to Reproduce Issue
This command always return success, but "Changes" indicate ERROR :

```
salt-run state.orchestrate myFile

retcode:
    0
perle-minion_master:

          ID: step-2
    Function: salt.function
        Name: file.touch
      Result: True
     Comment: Function ran successfully. Function file.touch ran on perle-minion.
     Started: 10:01:02.074058
    Duration: 267.896 ms
     Changes:
              perle-minion:
                  ERROR: No such file or directory

          ID: step-1
    Function: salt.function
        Name: file.touch
      Result: True
     Comment: Function ran successfully. Function file.touch ran on perle-minion.
     Started: 10:01:02.342185
    Duration: 264.263 ms
     Changes:
              perle-minion:
                  True

Summary for perle-minion_master

Succeeded: 2 (changed=2)
Failed:    0

Total states run:     2
Total run time: 532.159 ms
```

### Versions Report

Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.4
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

Is it a bug ?

Thanks,

Rémy
