### ISSUE TITLE
Relative symlinks are changed with file.recurse 2016.11.3

### ISSUE THREAD

**Issue by martinschipper** [saltstack/salt#39939]
### Description of Issue/Question
A relative link-target is changed when symlinks are managed with file.recurse
The link-target is "prefixed" with the salt:// path.

I.e. a relative link:
00non-https -> ../sites-available/non-https

Is changed to:
00non-https -> webserver24/etc/apache2-prod/sites-enabled/sites-available/non-https

when using the SLS snippet below. So the "../" is replaced by "webserver24/etc/apache2-prod/".
**The problem is absent in salt-master 2016.11.2 (and prior)**
Changing salt-minion versions is not affecting the problem.

### Setup
The codesnippet from the SLS is:

```
/etc/apache2-prod-sites:
  file.recurse:
    - name: /etc/apache2/sites-available
    - source: salt://webserver24/etc/apache2-prod/sites-available
    - include_empty: True
    - keep_symlinks: True
    - clean: True
```

### Steps to Reproduce Issue
Just file.recurse a folder with relative symlinks with salt-master 2016.11.2 (and prior) and 2016.11.3. Symlink target changes with 2016.11.3

### Versions Report
salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
