### ISSUE TITLE
"salt --versions-report" doesn't show correct version of salt

### ISSUE THREAD

**Issue by porunov** [saltstack/salt#39947]
### Description of Issue/Question
When I call `salt --versions-report` or `salt-run manage.versions` it shows that my master have version 2016.11.1 but I upgraded it to the newest version 2016.11.3. When I call `yum install salt-master` I get a message: `Package salt-master-2016.11.3-1.el7.noarch already installed and latest version`

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

1. Intall version 2016.11.1 via bootstrup on CentOS 7.3
2. Upgrade salt master via `yum update`
3. Update salt minions via `yum update`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.7
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.6
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

```

**Comment by Poogles** [comment]
Restart the salt master process?

**Comment by porunov** [comment]
Tried. Reboot the whole machine doesn't work too.

**Comment by Ch3LL** [comment]
are you installing the git version of boostrap? Maybe you have some pyc files.

for debugging purposes that call is made here: https://github.com/saltstack/salt/blob/develop/salt/utils/parsers.py#L245

**Comment by porunov** [comment]
Here are files which I have changed manually:
```
/usr/lib/python2.7/site-packages/salt/pillar/s3.py
/usr/lib/python2.7/site-packages/salt/modules/s3.py
/usr/lib/python2.7/site-packages/salt/fileserver/s3fs.py
/usr/lib/python2.7/site-packages/salt/utils/s3.py
/usr/lib/python2.7/site-packages/salt/fileclient.py
```

Can this cause problems with an update?

**Comment by Ch3LL** [comment]
I'm not aware of a situation that would cause this with those files. Didn't hear an answer from the previous question do you have any pyc files laying around? particular for the salt.version file?

**Comment by porunov** [comment]
I did have version.pyc file but I deleted it. After salt-master had been restarted a new version.pyc file has been generated.

**Comment by Ch3LL** [comment]
How did you install and upgrade salt?

**Comment by porunov** [comment]
I don't remember the installation but it seems that I was following this tutorial:
https://docs.saltstack.com/en/latest/topics/installation/rhel.html

Upgrade was simple:
`yum update salt*`

After that I have tried to restart salt-master and salt-minion. Also I tried to reboot the machine.

**Comment by rosscdh** [comment]
+1 still happening

```
    Salt Version:
              Salt: 3003.2

    Dependency Versions:
              cffi: 1.14.5
          cherrypy: 18.6.0
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.5
         gitpython: Not Installed
            Jinja2: 2.11.3
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.4
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.20
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
      python-gnupg: 0.4.6
            PyYAML: 5.4.1
             PyZMQ: 18.0.1
             smmap: 3.0.4
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.1

    System Versions:
              dist:
            locale: cp1252
           machine: AMD64
           release: 2019Server
            system: Windows
           version: 2019Server 10.0.17763 SP0
```
