### ISSUE TITLE
salt-cloud not passing master info to minion on bootstrap

### ISSUE THREAD

**Issue by haelyn** [saltstack/salt#39965]
### Description of Issue/Question

salt-cloud doesn't write the salt master information on /etc/salt/minion on bootstrap

### Setup

sanitized/minimized `/etc/salt/cloud.profiles.d/vmware.conf`

````yaml
test-clone:
  provider: vmware
  clonefrom: 'template-centos7'
  devices:
    network:
      Network adapter 1:
        name: 'QA-6'
        switch_type: standard
        ip: <elided>
        gateway: [elided]
        subnet_mask: 255.255.255.0
        adapter_type: vmxnet3
        connected: true
  ssh_username: root
  password: <elided>
  minion:
    master: <master_ip>
````

map.sls
````yaml
test-clone:
  - asd-clone-test:
     extends: test-clone
     domain: <test domain>
     dns_servers:
       - 10.100.2.13
     minion:
       master: <salt master IP>
````

/etc/salt/cloud
````yaml
start_action: state.highstate
````

### Steps to Reproduce Issue
- Run `$ salt-cloud -m test.sls -l debug`
- wait for the bootstrap process to finish deleting the temporary files (`/tmp/.saltcloud-<uuid>/minion`)
- bootstrap process hangs
- After this step, minion is reachable via ssh, and `/var/log/salt/minion` shows 
`tail /var/log/salt/minion
2017-03-10 12:58:47,263 [salt.utils       ][ERROR   ][2987] DNS lookup of 'salt' failed.
2017-03-10 12:58:47,263 [salt.minion      ][ERROR   ][2987] Master hostname: 'salt' not found. Retrying in 30 seconds
2017-03-10 12:59:17,281 [salt.utils       ][ERROR   ][2987] DNS lookup of 'salt' failed.
2017-03-10 12:59:17,281 [salt.minion      ][ERROR   ][2987] Master hostname: 'salt' not found. Retrying in 30 seconds
2017-03-10 12:59:47,309 [salt.utils       ][ERROR   ][2987] DNS lookup of 'salt' failed.
2017-03-10 12:59:47,309 [salt.minion      ][ERROR   ][2987] Master hostname: 'salt' not found. Retrying in 30 seconds
2017-03-10 13:00:17,340 [salt.utils       ][ERROR   ][2987] DNS lookup of 'salt' failed.
2017-03-10 13:00:17,341 [salt.minion      ][ERROR   ][2987] Master hostname: 'salt' not found. Retrying in 30 seconds
2017-03-10 13:00:47,368 [salt.utils       ][ERROR   ][2987] DNS lookup of 'salt' failed.
2017-03-10 13:00:47,369 [salt.minion      ][ERROR   ][2987] Master hostname: 'salt' not found. Retrying in 30 seconds
`

On the minion, `/etc/salt/minion` shows
````bash
[root@asd-clone-test ~]# grep master /etc/salt/minion
(...)
#master: salt
````

The minion is successfully provisioned. If I take out the start_action from /etc/salt/cloud the process ends OK. In all cases the networking configuration is correctly applied and the salt minion is left working(unconfigured)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
`$ salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: 0.25.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.25.0
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core`

minion version:
`[root@asd-clone-test ~]# salt-minion --version
salt-minion 2016.11.3 (Carbon)`

**Comment by haelyn** [comment]
Addendum: if I add grains info to the minion: stanza on map.sls it gets correctly rendered.
Thus
````yaml
minion:
  grains:
    - lvalue: rvalue
    - foo: bar
````
renders /etc/salt/grains on the minion with the correct values. The master configuration doesn't get passed
