### ISSUE TITLE
svn changes report

### ISSUE THREAD

**Issue by te-af-github** [saltstack/salt#40004]
### Description of Issue/Question

svn.export returns invalid change data. This happens on first and all following runs.

### Setup

mailbackup/aftools-svn/init.sls:

```
https://***/AF/:
  svn.export:
    - target: /usr/local/lib/site-perl/
    - username: ***
    - password: ***
    - overwrite: True
    - force: True
```

### Steps to Reproduce Issue

`salt * state.apply mailbackup.aftools-svn`

```
----------
          ID: https://***/AF/
    Function: svn.export
      Result: True
     Comment:
     Started: 04:00:05.418768
    Duration: 80.257 ms
     Changes:   Invalid Changes data: https://***/AF/ was Exported to /usr/local/lib/site-perl/
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
```
