### ISSUE TITLE
Salt-SSH git_pillar rendering fails w/root param set

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#40007]
### Description of Issue/Question
When defining a git_pillar with a `root` stanza, Salt-SSH will bork out: 
```
[ERROR   ] Root path '<bound method GitPython._getconf of <salt.utils.gitfs.GitPython object at 0x7f47df385b50>>' not present in git_pillar remote 'ssh://git@git.example.com/salt/salt-pillar.git', skipping.
```

This seems similar to #39720

### Setup
```
git_pillar_provider: gitpython    # BEWARE: https://github.com/saltstack/salt/issues/39892
git_pillar_ssl_verify: True
gitfs_global_lock: False
gitfs_provider: gitpython
gitfs_ssl_verify: True
ext_pillar:
  - git:
    - ssh://git@git.example.com/example/salt-example.git:
      - root: pillar

# (https://github.com/saltstack/salt/issues/39892)
ssh_minion_opts:
  failhard: True
  git_pillar_provider: gitpython
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.11.3-60-g53d14d8
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.24.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.13 (default, Jan 12 2017, 17:59:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: fedora 25 Twenty Five
        machine: x86_64
        release: 4.9.13-200.fc25.x86_64
         system: Linux
        version: Fedora 25 Twenty Five
```

**Comment by Ch3LL** [comment]
I'm not able to replicate this with the following settings in master config:

```
 ch3ll@thecakeisalie  ~/git/salt  ➦ 53d14d8 <B>  grep -E -v '^$|#' /etc/salt/master
git_pillar_ssl_verify: True
gitfs_global_lock: False
gitfs_provider: gitpython
gitfs_ssl_verify: True
ext_pillar:
  - git:
    - master https://github.com/Ch3LL/Ch3LLScripts.git:
      - root: salt/pillars
ssh_minion_opts:
  failhard: True
  git_pillar_provider: gitpython
```

And when i run the following it works:

```
 ch3ll@thecakeisalie  ~/git/salt  ➦ 53d14d8 <B>  sudo salt-ssh 'test' pillar.items
test:
    ----------
    ch3ll:
        yep
    ch3ll2:
        yep2
    test:
        gitfs
    test2:
        two
    test3:
        three
    test4:
        four
    test5:
        five
    update:
        True
    update2:
        test_test
```

Can you try those settings? that repo is open to the public? I want to see if only your repo is failing.

**Comment by hgfischer** [comment]
Hello,

I am also having this error with the following setup:

```
git_pillar_includes: true
gitfs_provider: pygit2

ext_pillar:
  - git:
    - master git@bitbucket.org:xxxxxxxxxxx/yyyyyyyyyyyy.git:
      - environment: vagrant
      - root: vagrant
      - privkey: /etc/salt/pki/master/ext_pillar/vagrant
      - pubkey: /etc/salt/pki/master/ext_pillar/vagrant.pub
```
