### ISSUE TITLE
The `pip.installed` state is unable to use `pip3` when no `pip` for python2 installed

### ISSUE THREAD

**Issue by vutny** [saltstack/salt#40048]
### Description of Issue/Question
I'm trying to install `aiohttp` module for Python 3.5 with `pip3` using Salt. I don't have `pip` version for Python 2 installed at all.

### Setup
```yaml
# python3/aiohttp.sls

Install Python 3.5 and pip:
  pkg.installed:
    - pkgs:
      - python3
      - python3-pip
    - reload_modules: true

Install aiohttp:
  pip.installed:
    - name: aiohttp
    - require:
      - pkg: Install Python 3.5 and pip
```

### Steps to Reproduce Issue

What I've got is this:

```yaml
# salt-call state.apply python3.aiohttp
local:
----------
          ID: Install Python 3.5 and pip
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 14:53:38.014280
    Duration: 30.274 ms
     Changes:   
----------
          ID: Install aiohttp
    Function: pip.installed
        Name: aiohttp
      Result: False
     Comment: An importable pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
     Started: 14:53:38.408579
    Duration: 0.582 ms
     Changes:   

```

It seems that the `pip` state module is depending on `pip` for Python 2 module availability, because Salt Minion is running againts Python 2.

The workaround for this which I came with so far:

```yaml
Install Python 3.5 and pip:
  pkg.installed:
    - pkgs:
      # Python 2 ``pip`` is required for ``pip.installed`` state to work
      - python-pip
      - python3
      - python3-pip
    - reload_modules: true

Install aiohttp:
  pip.installed:
    - name: aiohttp
    - bin_env: /usr/bin/pip3
    - require:
      - pkg: Install Python 3.5 and pip
```
### Versions Report
```yaml
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
```

**Comment by gtmanfred** [comment]
I consider this the expected behavior.

The module defaults to using pip, if it is not available, the correct pip to be used will need to be specified.

Thanks,
Daniel

**Comment by vutny** [comment]
@gtmanfred Sorry, I think I missed the important point: if I *do not have* `pip` installed and trying to use available `pip3` binary explicitly:
```yaml
Install aiohttp:
  pip.installed:
    - name: aiohttp
    - bin_env: /usr/bin/pip3
```
It gives me the same error:
```
An importable pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
```
It starts working only then the `pip` got installed.
Does that still looks like the expected behavior?

**Comment by nbirnel** [comment]
@gtmanfred I agree with @vutny that this is at best confusing behavior, and should be documented if it can't be changed. If I am using python3, and thus pip3, I don't really want to have pip2 be a dependancy. Currently this doesn't work:

```yaml
python34_pip_package:
  pkg:
    - installed
    - name: python34-pip

boto3_package:
  pip.installed:
    - require:
      - pkg: python34_pip_package
    - bin_env: '/bin/pip3'
    - name: boto3 == 1.4.4
```

while this does:
```yaml
python2_pip_package:
  pkg:
    - installed
    - name: python2-pip

python34_pip_package:
  pkg:
    - installed
    - name: python34-pip

boto3_package:
  pip.installed:
    - require:
      - pkg: python34_pip_package
    - bin_env: '/bin/pip3'
    - name: boto3 == 1.4.4
```

It is not the need for the `bin_env` line that is the problem; it is the requirement for pip2 to be installed when it is explicitly not what I want to use.
