### ISSUE TITLE
salt-cloud fails operating with GCE nodes on 2015.8

### ISSUE THREAD

**Issue by sergeizv** [saltstack/salt#40050]
### Description of Issue/Question

After creating a GCE instance salt-cloud fails on querying, destroying, performing actions on it, etc.

The issue appears only on 2015.8 and is fixed in be41a400fa8c which were committed into 2016.3.

### Steps to Reproduce Issue

Create a node on GCE and try to do anything with it.

    (py2-env) salt-test@tommynaut:~> salt-cloud -Q -l debug
     ...
     [DEBUG   ] Failed to execute 'gce.list_nodes()' while querying for running nodes: 'running'
     Traceback (most recent call last):
       File "/home/salt-test/salt/salt/cloud/__init__.py", line 2370, in run_parallel_map_providers_query
         cloud.clouds[data['fun']]()
       File "/home/salt-test/salt/salt/cloud/libcloudfuncs.py", line 443, in list_nodes
         'state': node_state(node.state)
       File "/home/salt-test/salt/salt/cloud/libcloudfuncs.py", line 67, in node_state
         return states[id_]
     KeyError: 'running'

### Versions Report

```
Salt Version:
           Salt: 2015.8.12-130-gfc551bc
 
Dependency Versions:
         Jinja2: 2.9.5
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
         Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
           RAET: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.9.11-1-default
```
