### ISSUE TITLE
dockerng login attempts all registries unnecessarily

### ISSUE THREAD

**Issue by LrsK** [saltstack/salt#40086]
### Description of Issue/Question
Using dockerng, say you have several docker repositories set up in Pillar as described here: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockerng.html 

Then you make a dockerng-state where you attempt to pull from any of them. If only one of the logins specified in Pillar fails, the pull will fail. Even if you did not attempt to pull from the repo that is misconfigured. 

Here are lines 1051 - 1065 in the dockerng.py module:
```
try:
    for registry, creds in six.iteritems(registry_auth_config):
        __context__['docker.client'].login(
            creds['username'],
            password=creds['password'],
            email=creds.get('email'),
            registry=registry,
            reauth=creds.get('reauth', False))
except KeyError:
    raise SaltInvocationError(
        err.format('Incomplete', ' for registry {0}'.format(registry))
    )
client_timeout = kwargs.pop('client_timeout', None)
if client_timeout is not None:
    __context__['docker.client'].timeout = client_timeout
```

It looks like dockerng will iterate through all the items in pillar ending with "-docker-repositories", regardless of which repository was invoked by the state. Instead, dockerng should only attempt to login to the repository that was parsed from the image-option. 

One case where this is a problem is when you either don't have a registry set up yet, and you want salt to set it up for you, or you are about to add a new registry. You will not point at the non-existing registry, but another one that is working, or Docker's own registry at docker.io.  Also, if you enter the wrong password into pillar as shown below, all docker authentications made by dockerng may fail. This appears to be a bit random since `registry_auth_config` is a dictionary and not a list.

### Setup
```
# Pillar
one-docker-registries:
  https://example.com/v2/:
    username: docker
    password: abc123
    email: myaddr@example.com

two-docker-registries:
  https://example.net/v2/:
    username: docker
    password: wrong_password
    email: myaddr@example.net

dockerio-docker-registries:
  https://index.docker.io/v1/:
    email: myaddr@example.com
``` 
```
# State in services/docker/registry/init.sls :
registry:
  dockerng.running:
    - name: registry
    - image: https://index.docker.io/v1/registry:2
    - port_bindings:
      - 443:5000
    - restart_policy: always
    - environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE: /etc/ssl/private/servercert.pem
      - REGISTRY_HTTP_TLS_KEY: /etc/ssl/certs/serverkey.pem
      - REGISTRY_AUTH: htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH: /store/config/registry/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    - binds:
      - /store/docker/images:/var/lib/registry
      - /etc/ssl:/etc/ssl
      - /store/config/registry:/store/config/registry
      - /etc/pki:/etc/pki
    - require:
      - pkg: python-docker-py
```

### Steps to Reproduce Issue
If you run `salt-call state.apply services.docker.registry` the running-option above will fail, saying that login to example.net failed.

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
