### ISSUE TITLE
Need to provide way to signal dpkg-reconfigure when debconf preseed changes

### ISSUE THREAD

**Issue by eugenea** [saltstack/salt#4010]
Problem: if package is already installed and debconf selection for it got changed via debconf.set - the selections will not affect current package state.

Need to provide mechanism to detect changes in debconf selections and signal
dpkg-reconfigure for particular package to enable changes.

**Comment by grinapo** [comment]
So far so good... 😞

**Comment by grinapo** [comment]
A HighSeverity bug autoclosed, mmh. Stoopid bot! Sit! STAY!

**Comment by waynew** [comment]
I know that the `debconf.set` state fires changes - is there any reason that this won't work for you?

```
somestate:
  debconf.set:
    - name: whatever-thing
    - data:
              'whatever-thing': {'type': 'boolean', 'value': True}

reconfigurething:
  cmd.run:
    - name: dpkg-reconfigure -f noninteractive <your thing>
    - onchanges:
      - debconf: somestate
```

**Comment by boltronics** [comment]
@waynew I haven't tested it, but that looks good to me. Thanks for the suggestion! I used a different approach by making sure debconf.set was executed before installing the package, but your suggestion is nicer in some ways.

It would be ideal if Salt provided a more direct and intuitive way to execute that command on changes when the package is already installed. eg.
```
somestate:
  debconf.set:
    - name: whatever-thing
    - data:
        'whatever-thing':
          'type': 'boolean'
          'value': 'true'
    - reconfigure: True
```
