### ISSUE TITLE
Defining dedicated CPUs in Salt Cloud profile

### ISSUE THREAD

**Issue by rehmanzile** [saltstack/salt#40125]
### Description of Issue/Question
Is there a way to define dedicated CPUs in [salt cloud profile](https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vmware.html)?

Currently you only define number of CPUs via `num_cpus` option. This number is for shared CPUs only.

```
vmware-centos6.5:
    provider: vcenter01
    clonefrom: test-vm

    num_cpus: 4
    memory: 8GB
```

### Setup
Here is a sample configuration as described on [Salt Getting Started with VMWare Guide](https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vmware.html)
```
vmware-centos6.5:
    provider: vcenter01
    clonefrom: test-vm

    num_cpus: 4
    memory: 8GB
```

### Steps to Reproduce Issue
Not Applicable.

### Versions Report
Not Applicable.
