### ISSUE TITLE
Use current user's username when connecting with salt-ssh

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#40133]
### Description of Issue/Question

I would like to have a `roster` file where I can specify that for username, salt-ssh should use local user's username. So that `roster` file can be shared across team members. And we have the same username on our local machines than on servers.

### Setup

I have a `config/roster` file for salt-ssh which has entries like:

```
server1:
  host: server1.example.com
  port: 22
  user: mitar
  sudo: True
```

Ideally, I could do something like:

```
server1:
  host: server1.example.com
  port: 22
  user: $USER
  sudo: True
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul 14 2015, 19:46:27)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 14.5.0
         system: Darwin
        version: 10.10.5 x86_64
```

**Comment by sergeizv** [comment]
A roster file may be templated with Jinja2, but I see no way accessing environment variables from it. However, it might be useful to specify a user via a variable:

```
{% set username = 'foobar' %}
```

or get it from the master's config

```
{% set username = opts['user'] %}
```

and then

```
server1:
  host: server1.example.com
  port: 22
  user: {{ username }}
  sudo: True
```

If modules were available when templating a roster file, it could be

```
{% set username = salt['environ.get']('USER') %}
```

**Comment by Ch3LL** [comment]
@mitar does the jinja that @sergeizv posted work for you use case?

**Comment by mitar** [comment]
No, because it seems there is no way to access to the environment variable? I would like to have both `roster` and `master` files fixed for people deploying things. The only thing which is different is their username with which they can SSH into the system.

**Comment by The-Loeki** [comment]
FWIW your issue inspired me to add environment support to the new cache roster I wrote (#40284).

Without knowing too much of your details I will strongly and warmly suggest deploying regular salt minions. Salt-SSH has it's many uses, but for regular & teambased usage you're going to have so much more fun doing a real salt master setup, I promise you.

**Comment by mitar** [comment]
Ooo, great. In our case we prefer this setup because then we as an open source project can have a repository with all salt data and configuration, so that contributors can contribute. And then we can keep the same roster and everything, and just add people's SSH key on the server if we want them to be able to deploy.

**Comment by The-Loeki** [comment]
https://gist.github.com/The-Loeki/d87ca35d52326c71ac0eec0726e55d7c

**Comment by jknightstreamme** [comment]
👍

**Comment by Ch3LL** [comment]
Does this new roster work for your use case? Are we okay to close this now or are there any other concerns? It seems that roster makes use of the sdb env module.

**Comment by mitar** [comment]
I have not yet tested this, but if one can access environment that this does satisfy our needs.

**Comment by Ch3LL** [comment]
Okay I will go ahead and close and please create a new issue if it does not work with teh details as to why its not working. Thanks

**Comment by mitar** [comment]
Hm, looking into this, but I am not sure how exactly is this used? @The-Loeki 

So if I currently have this entry in my roster file:

```
foobar:
  host: foorbar.example.com
  port: 22
  user: mitar
  sudo: True
```

How do I convert it so that `mitar` is read from the environment?

**Comment by The-Loeki** [comment]
@mitar I had some discussion in my PR regarding that environment support, and eventually the Salt powers decided against directly supporting it.

I've modified the roster and docs to boot; it should now be done through sdb:
https://docs.saltstack.com/en/develop/ref/roster/all/salt.roster.cache.html#module-salt.roster.cache

Bear in mind this is only in upcoming Nitrogen release

**Comment by mitar** [comment]
Not sure how this would then be used. Would this work?

```
foobar:
  host: foorbar.example.com
  port: 22
  user: sdb://osenv/USER
  sudo: True
```

If this is not implemented, maybe the issue should be reopened?
