### ISSUE TITLE
schedule with pillar kwarg has error when schedule executes

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#40144]
### Description of Issue/Question
I am trying to schedule a job with a pillar kwarg.  But when I include the pillar kwarg the scheduled job gets an unhandled exception.   What is the appropriate way to include a pillar in a scheduled task?

### Setup
State:
```
myschedule_5:
  schedule.present:
    - function: state.sls
    - job_args:
      - tasks/rds/user
    - once: "{{ (None|strftime("%s")|int + 2)|strftime("%Y-%m-%dT%H:%M:%S") }}"
    - once_fmt: "%Y-%m-%dT%H:%M:%S"
    - job_kwargs:
          pillar: '{"dbrole":"adam","grant_list":{"riskalyze_adam":"select"},"role":"dev","status":"absent","username":"dgetz"}'
```

State run:
```
east-salt-api-prod-1a:
----------
          ID: myschedule_5
    Function: schedule.present
      Result: True
     Comment: Adding new job myschedule_5 to schedule
     Started: 00:03:39.902486
    Duration: 408.81 ms
     Changes:

Summary for east-salt-api-prod-1a
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 408.810 ms
```

And the scheduled job looks like this
```
#salt-call schedule.list
local:
    schedule:
      myschedule_5:
        args:
        - tasks/rds/user
        enabled: true
        function: state.sls
        jid_include: true
        kwargs:
          pillar: '{"dbrole":"adam","grant_list":{"riskalyze_adam":"select"},"role":"dev","status":"absent","username":"dgetz"}'
        maxrunning: 1
        name: myschedule_5
        once: '2017-03-19T23:59:24'
        once_fmt: '%Y-%m-%dT%H:%M:%S'
```
### Steps to Reproduce Issue
Logs show the following when the scheduled job runs

```
2017-03-19 23:59:24,802 [salt.utils.schedule][ERROR   ][29082] Unhandled exception running state.sls
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 836, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 986, in sls
    'Pillar data must be formatted as a dictionary, unless pillar_enc '
SaltInvocationError: Pillar data must be formatted as a dictionary, unless pillar_enc is specified.
```

### Versions Report
```
#salt --versions-report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
I was able to get it to work using the followign:

```
myschedule_7:
  schedule.present:
    - function: state.sls
    - job_args:
      - testarg
    - seconds: 10
    - job_kwargs:
        pillar: {"dbrole":"adam","grant_list":{"riskalyze_adam":"select"},"role":"dev","status":"absent","username":"dgetz"}
```
