### ISSUE TITLE
State module boto_vpc not working with boto 2

### ISSUE THREAD

**Issue by grichmond-salt** [saltstack/salt#40155]
### Description of Issue/Question
The boto_vpc state is not working with boto 2.

The module state that boto version > 2.8.0 is required, even though, a more recent version is installed.

This module worked in 2016.3.x, but is not working in 2016.11.x.

Installation of boto3 allows the module to work.

### Setup
The pillar data being used for testing is:
```
# VPC Settings
aws.vpc.keyid: 'REDACTED'
aws.vpc.key: 'REDACTED'
aws.vpc.region: us-west-2

# VPC Defaults
aws.vpc.name: SaltTestDeployment_VPC
aws.vpc.cidr_block: 192.168.128.0/24

# VPC Subnet Defaults
aws.vpc.subnet.name: SaltTestDeployment_Subnet

# VPC Internet Gateway Defaults
aws.vpc.internet_gateway.name: SaltTestDeployment_Internet_Gateway

# VPC Route Table Defaults
aws.vpc.route_table.name: SaltTestDeployment_Route
```

The state being used for testing is:
```
{% set vpc_keyid = salt['pillar.get']('aws.vpc.keyid') %}
{% set vpc_key = salt['pillar.get']('aws.vpc.key') %}
{% set vpc_region = salt['pillar.get']('aws.vpc.region') %}

{% set vpc_name = salt['pillar.get']('aws.vpc.name') %}
{% set vpc_cidr_block = salt['pillar.get']('aws.vpc.cidr_block') %}
{% set vpc_subnet_name = salt['pillar.get']('aws.vpc.subnet.name') %}
{% set vpc_internet_gateway_name = salt['pillar.get']('aws.vpc.internet_gateway.name') %}
{% set vpc_route_table_name = salt['pillar.get']('aws.vpc.route_table.name') %}

ensure_vpc_exists:
  boto_vpc.present:
    - name: {{ vpc_name }}
    - cidr_block: {{ vpc_cidr_block }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
        region: {{ vpc_region }}

ensure_subnet_exists:
  boto_vpc.subnet_present:
    - name: {{ vpc_subnet_name }}
    - vpc_name: {{ vpc_name }}
    - cidr_block: {{ vpc_cidr_block }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
        region: {{ vpc_region }}

ensure_internet_gateway_exists:
  boto_vpc.internet_gateway_present:
    - name: {{ vpc_internet_gateway_name }}
    - vpc_name: {{ vpc_name }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
        region: {{ vpc_region }}

ensure_route_table_exists:
  boto_vpc.route_table_present:
    - name: {{ vpc_route_table_name }}
    - vpc_name: {{ vpc_name }}
    - subnet_names:
      - {{ vpc_subnet_name }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
```

### Steps to Reproduce Issue
1. Execute the state above with a current version of boto 2 installed
2. Execute the state after installing boto3

_Note: After installing boto3, it may be observed that the boto_vpc.route_table_present state module is not working properly.  A separate issue will be created for that._

### Versions Report
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
```
