### ISSUE TITLE
orchestrate runner output unreadable

### ISSUE THREAD

**Issue by milan-milo** [saltstack/salt#40151]
### Description of Issue/Question
Hi, we're using salt's orchestrate module (state.orch) and the outputted information is unreadable making it unusable. Is there any way we can get the normal formatting as we see when we run salt states individually.

Have also tried with different output:
e.g. --out yaml

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
```
Output:

pkg_|-gd_install_|-gd_|-installed:
            __id__: gd_install
            __run_num__: 2
            changes: {}
            comment: Package gd is already installed
            duration: 0.524
            name: gd
            result: true
            start_time: '23:30:20.696395'
          pkg_|-geoip_install_|-GeoIP_|-installed:
            __id__: geoip_install
            __run_num__: 4
            changes: {}
            comment: Package GeoIP is already installed
            duration: 0.495
            name: GeoIP
            result: true
            start_time: '23:30:20.697700'
          pkg_|-gperf_install_|-gperftools-libs_|-installed:
            __id__: gperf_install
            __run_num__: 3
            changes: {}
            comment: Package gperftools-libs is already installed
            duration: 0.512
            name: gperftools-libs
            result: true
            start_time: '23:30:20.697053'
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 3.10.0-123.8.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.0.1406 Core
```
