### ISSUE TITLE
State module boto_vpc.route_table_present fails to create route table based on VPC Name

### ISSUE THREAD

**Issue by grichmond-salt** [saltstack/salt#40157]
### Description of Issue/Question
The boto_vpc.route_table_present state module is not able to create a route table based on the VPC Name.

_Note: Similarly, `boto_vpc.route_table_absent` fails to remove a route table._

The following output for the configuration described below is observed:
```
        Name: SaltTestDeployment_VPC
      Result: True
     Comment: VPC present.
     Started: 12:38:06.881091
    Duration: 67.997 ms
     Changes:
----------
          ID: ensure_subnet_exists
    Function: boto_vpc.subnet_present
        Name: SaltTestDeployment_Subnet
      Result: True
     Comment: Subnet present.
     Started: 12:38:06.949281
    Duration: 52.758 ms
     Changes:
----------
          ID: ensure_internet_gateway_exists
    Function: boto_vpc.internet_gateway_present
        Name: SaltTestDeployment_Internet_Gateway
      Result: True
     Comment: Internet gateway SaltTestDeployment_Internet_Gateway present.
     Started: 12:38:07.002201
    Duration: 33.252 ms
     Changes:
----------
          ID: ensure_route_table_exists
    Function: boto_vpc.route_table_present
        Name: SaltTestDeployment_Route
      Result: False
     Comment: Failed to create route table: VPC SaltTestDeployment_VPC does not exist..
     Started: 12:38:07.035600
    Duration: 2761.67 ms
     Changes:

Summary for saltmaster
------------
Succeeded: 3
Failed:    1
------------
Total states run:     4
Total run time:   2.916 s
```

### Setup
The pillar data being used for testing is:
```
# VPC Settings
aws.vpc.keyid: 'REDACTED'
aws.vpc.key: 'REDACTED'
aws.vpc.region: us-west-2

# VPC Defaults
aws.vpc.name: SaltTestDeployment_VPC
aws.vpc.cidr_block: 192.168.128.0/24

# VPC Subnet Defaults
aws.vpc.subnet.name: SaltTestDeployment_Subnet

# VPC Internet Gateway Defaults
aws.vpc.internet_gateway.name: SaltTestDeployment_Internet_Gateway

# VPC Route Table Defaults
aws.vpc.route_table.name: SaltTestDeployment_Route
```

The state being used for testing is:
```
{% set vpc_keyid = salt['pillar.get']('aws.vpc.keyid') %}
{% set vpc_key = salt['pillar.get']('aws.vpc.key') %}
{% set vpc_region = salt['pillar.get']('aws.vpc.region') %}

{% set vpc_name = salt['pillar.get']('aws.vpc.name') %}
{% set vpc_cidr_block = salt['pillar.get']('aws.vpc.cidr_block') %}
{% set vpc_subnet_name = salt['pillar.get']('aws.vpc.subnet.name') %}
{% set vpc_internet_gateway_name = salt['pillar.get']('aws.vpc.internet_gateway.name') %}
{% set vpc_route_table_name = salt['pillar.get']('aws.vpc.route_table.name') %}

ensure_vpc_exists:
  boto_vpc.present:
    - name: {{ vpc_name }}
    - cidr_block: {{ vpc_cidr_block }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
        region: {{ vpc_region }}

ensure_subnet_exists:
  boto_vpc.subnet_present:
    - name: {{ vpc_subnet_name }}
    - vpc_name: {{ vpc_name }}
    - cidr_block: {{ vpc_cidr_block }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
        region: {{ vpc_region }}

ensure_internet_gateway_exists:
  boto_vpc.internet_gateway_present:
    - name: {{ vpc_internet_gateway_name }}
    - vpc_name: {{ vpc_name }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
        region: {{ vpc_region }}

ensure_route_table_exists:
  boto_vpc.route_table_present:
    - name: {{ vpc_route_table_name }}
    - vpc_name: {{ vpc_name }}
    - subnet_names:
      - {{ vpc_subnet_name }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
```

### Steps to Reproduce Issue
1. Execute the state above

### Versions Report
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
```

**Comment by gtmanfred** [comment]
What is the error that you are seeing?

I am unable to replicate this, it is working here.

```
[root@ip-10-0-0-120 salt]# tail -c +0 /srv/salt/test*.sls
==> /srv/salt/test2.sls <==
delete_internet_gateway_exists:
  boto_vpc.internet_gateway_absent:
    - name: gtinternet
    - detach: True

delete_subnet_exists:
  boto_vpc.subnet_absent:
    - name: gttest-sub

delete_route_table_exists:
  boto_vpc.route_table_absent:
    - name: gtroute

delete_vpc_exists:
  boto_vpc.absent:
    - name: gttest

==> /srv/salt/test.sls <==
ensure_vpc_exists:
  boto_vpc.present:
    - name: gttest
    - cidr_block: 10.0.0.0/16

ensure_subnet_exists:
  boto_vpc.subnet_present:
    - name: gttest-sub
    - vpc_name: gttest
    - cidr_block: 10.0.69.0/24

ensure_internet_gateway_exists:
  boto_vpc.internet_gateway_present:
    - name: gtinternet
    - vpc_name: gttest

ensure_route_table_exists:
  boto_vpc.route_table_present:
    - name: gtroute
    - vpc_name: gttest
    - subnet_names:
      - gttest-sub
[root@ip-10-0-0-120 salt]# salt-call state.apply --local test
[WARNING ] /root/src/salt/salt/modules/boto_vpc.py:2457: DeprecationWarning: The 'describe_route_table' method has been deprecated and replaced by 'describe_route_tables'.

local:
----------
          ID: ensure_vpc_exists
    Function: boto_vpc.present
        Name: gttest
      Result: True
     Comment: VPC gttest created.
     Started: 16:10:59.334313
    Duration: 722.962 ms
     Changes:
              ----------
              new:
                  ----------
                  vpc:
                      ----------
                      cidr_block:
                          10.0.0.0/16
                      dhcp_options_id:
                          dopt-b4454cd6
                      id:
                          vpc-2d540c4b
                      instance_tenancy:
                          default
                      is_default:
                          False
                      region:
                          us-east-1
                      state:
                          available
                      tags:
                          ----------
                          Name:
                              gttest
              old:
                  ----------
                  vpc:
                      None
----------
          ID: ensure_subnet_exists
    Function: boto_vpc.subnet_present
        Name: gttest-sub
      Result: True
     Comment: Subnet gttest-sub created.
     Started: 16:11:00.057426
    Duration: 799.758 ms
     Changes:
              ----------
              new:
                  ----------
                  subnet:
                      ----------
                      availability_zone:
                          us-east-1a
                      cidr_block:
                          10.0.69.0/24
                      id:
                          subnet-23522e46
                      tags:
                          ----------
                          Name:
                              gttest-sub
                      vpc_id:
                          vpc-2d540c4b
              old:
                  ----------
                  subnet:
                      None
----------
          ID: ensure_internet_gateway_exists
    Function: boto_vpc.internet_gateway_present
        Name: gtinternet
      Result: True
     Comment: Internet gateway gtinternet created.
     Started: 16:11:00.857341
    Duration: 387.944 ms
     Changes:
              ----------
              new:
                  ----------
                  internet_gateway:
                      igw-38716c5f
              old:
                  ----------
                  internet_gateway:
                      None
----------
          ID: ensure_route_table_exists
    Function: boto_vpc.route_table_present
        Name: gtroute
      Result: True
     Comment: Route table gtroute created.  Associated subnet subnet-23522e46 with route table gtroute.
     Started: 16:11:01.245439
    Duration: 933.821 ms
     Changes:
              ----------
              new:
                  ----------
                  route_table:
                      rtb-68026a11
                  subnets_associations:
                      |_
                        ----------
                        id:
                            rtbassoc-6bc0c013
                        main:
                            False
                        route_table_id:
                            rtb-68026a11
                        subnet_id:
                            subnet-23522e46
              old:
                  ----------
                  route_table:
                      None
                  subnets_associations:

Summary for local
------------
Succeeded: 4 (changed=4)
Failed:    0
------------
Total states run:     4
Total run time:   2.844 s
[root@ip-10-0-0-120 salt]# salt-call state.apply --local test2
local:
----------
          ID: delete_internet_gateway_exists
    Function: boto_vpc.internet_gateway_absent
        Name: gtinternet
      Result: True
     Comment: Internet gateway gtinternet deleted.
     Started: 16:11:17.284543
    Duration: 332.486 ms
     Changes:
              ----------
              new:
                  ----------
                  internet_gateway:
                      None
              old:
                  ----------
                  internet_gateway:
                      igw-38716c5f
----------
          ID: delete_subnet_exists
    Function: boto_vpc.subnet_absent
        Name: gttest-sub
      Result: True
     Comment: Subnet gttest-sub deleted.
     Started: 16:11:17.617178
    Duration: 463.824 ms
     Changes:
              ----------
              new:
                  ----------
                  subnet:
                      None
              old:
                  ----------
                  subnet:
                      subnet-23522e46
----------
          ID: delete_route_table_exists
    Function: boto_vpc.route_table_absent
        Name: gtroute
      Result: True
     Comment: Route table gtroute deleted.
     Started: 16:11:18.081148
    Duration: 181.562 ms
     Changes:
              ----------
              new:
                  ----------
                  route_table:
                      None
              old:
                  ----------
                  route_table:
                      rtb-68026a11
----------
          ID: delete_vpc_exists
    Function: boto_vpc.absent
        Name: gttest
      Result: True
     Comment: VPC gttest deleted.
     Started: 16:11:18.262856
    Duration: 333.315 ms
     Changes:
              ----------
              new:
                  ----------
                  vpc:
                      None
              old:
                  ----------
                  vpc:
                      vpc-2d540c4b

Summary for local
------------
Succeeded: 4 (changed=4)
Failed:    0
------------
Total states run:     4
Total run time:   1.311 s
```

**Comment by grichmond-salt** [comment]
The error message is:
  `Failed to create route table: VPC SaltTestDeployment_VPC does not exist..`

Thanks!

**Comment by gtmanfred** [comment]
Looks like you do not have region defined for your route_table_present, so it is using the default of us-east-1, instead of the us-west-2 that you have defined for the other states.

```
ensure_route_table_exists:
  boto_vpc.route_table_present:
    - name: {{ vpc_route_table_name }}
    - vpc_name: {{ vpc_name }}
    - subnet_names:
      - {{ vpc_subnet_name }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
```

Daniel
