### ISSUE TITLE
file.replace diff results output showing additional characters

### ISSUE THREAD

**Issue by alias454** [saltstack/salt#40167]
This doesn't appear to be a big issue but the results of a highstate display additional diff characters.

Example states that are run
```
ssh-config-set-banner:
  file.replace:
    - name: /etc/ssh/sshd_config
    - pattern: "#Banner none"
    - repl: "Banner /etc/issue.net"

ssh-config-set-ciphers:
  file.replace:
    - name: /etc/ssh/sshd_config
    - pattern: |
        # Ciphers and keying
        #RekeyLimit default none
    - repl: |
        # Ciphers and keying
        #RekeyLimit default none
        Ciphers aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc
        MACs hmac-sha1,umac-64@openssh.com,hmac-ripemd160
    - unless: grep 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc' /etc/ssh/sshd_config
```

Results are okay. File contents after highstate.
```
# Ciphers and keying
#RekeyLimit default none
Ciphers aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc
MACs hmac-sha1,umac-64@openssh.com,hmac-ripemd160
```

This is the display output after running the states
```
----------
          ID: ssh-config-set-banner
    Function: file.replace
        Name: /etc/ssh/sshd_config
      Result: True
     Comment: Changes were made
     Started: 14:49:02.124810
    Duration: 14.964 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -3845,7 +3845,6 @@
                   t h
                  -# B a n@@ -3853,10 +3852,20 @@
                   e r  -n-o-n-e+/+e+t+c+/+i+s+s+u+e+.+n+e+t

                   #
----------
          ID: ssh-config-set-ciphers
    Function: file.replace
        Name: /etc/ssh/sshd_config
      Result: True
     Comment: Changes were made
     Started: 14:49:02.139917
    Duration: 167.803 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1132,6 +1132,139 @@
                   o n e+
                  +C+i+p+h+e+r+s+ +a+e+s+2+5+6+-+c+t+r+,+a+e+s+1+9+2+-+c+t+r+,+a+e+s+1+2+8+-+c+t+r+,+a+e+s+2+5+6+-+c+b+c+,+a+e+s+1+9+2+-+c+b+c+,+a+e+s+1+2+8+-+c+b+c+,+3+d+e+s+-+c+b+c+
                  +M+A+C+s+ +h+m+a+c+-+s+h+a+1+,+u+m+a+c+-+6+4+@+o+p+e+n+s+s+h+.+c+o+m+,+h+m+a+c+-+r+i+p+e+m+d+1+6+0

                   #
```

### Versions Report
master
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

Minions only difference is the OS
System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
