### ISSUE TITLE
Testing pillars

### ISSUE THREAD

**Issue by Inveracity** [saltstack/salt#40176]
### Description of Issue/Question
I'm attempting to write some testing for Continuous Integration of pillars.
I want to test that pillar files can be rendered and confirm that they follow a certain structure we've agreed on in our team.

However I've gotten stuck on providing the grains to pillar files containing conditions that use grains - as in, I have no idea how to do it.

Any help would be appreciated

### Setup

The code that runs the pillar rendering:
/srv/pillar/_tests/test_render_pillar.py
```python
import os
import salt.config
import salt.loader
import salt.template
import salt.exceptions


__opts__ = salt.config.minion_config('/etc/salt/minion')
__opts__['master_uri'] = ''
__utils__ = salt.loader.utils(__opts__)
__salt__ = salt.loader.minion_mods(__opts__, utils=__utils__)

def renderer(path):
    ''' attempt to render jinja and yaml '''
    renderers = salt.loader.render(__opts__, __salt__)
    default_renderer = 'jinja|yaml'

    try:
        salt.template.compile_template(
                path,
                renderers,
                default_renderer,
                __opts__['renderer_blacklist'],
                __opts__['renderer_whitelist'],
        )

    except salt.exceptions.SaltRenderError as e:
        print e
        exit(1)

    else:
        print path + " OK"


# Find all pillar files and attempt to render each one
for root,dirs,files in os.walk("../"):
    for name in files:
        if 'top.sls' not in name \
        and '_tests' not in root:
            file_to_render = os.path.join(root, name)
            renderer(file_to_render)
```

The test pillar file
/srv/pillar/services/prod/apache.sls
```yaml
{% if "xyz" in grains["id"] %}

test: True

{% endif %}

roles:
  - apache
```

The command being run on the CI server:
```
/srv/pillar/_tests/# python test_render_pillar.py
```

The error:
```
root@salttest:/vagrant/pillar/_tests# python test_pillar_render.py
Jinja error: argument of type 'StrictUndefined' is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
TypeError: argument of type 'StrictUndefined' is not iterable

; line 1

---
{% if "xyz" in grains["id"] %}    <======================

test: True

{% endif %}

[...]
---
```

the folder structure looks like this:
```
/srv/pillar/
    _tests/test_render_pillar.py
    services/buildpipe/prod/apache.sls
    top.sls
```

### Versions Report
```yaml
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-112-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
