### ISSUE TITLE
Overriding profile provider in map file

### ISSUE THREAD

**Issue by jbfriedrich** [saltstack/salt#40183]
### Description of Issue/Question

I currently have an environment specified in several profile configuration files. A map file is using these profiles to deploy a "pod" with several components for a certain product. This works fine and as expected, as long as I am deploying it with "provider-a", the provider that is specified in the profiles.

Now I need to spin up the same components in a different data center, for which I have to use a different provider. In my example "provider-b". The deployed instances will be exactly the same, only the names, the IP addresses, and certain values connected to VMware (cluster name, data center name etc) are changing. 

To avoid cluttering my profile directory with identical files that only differ in 2 or 3 places, I am trying to override certain settings from the profile in my map. That works great, with only one exception: _the provider_.

When I am trying to override the provider I receive the following error:

```
[DEBUG   ] Generating minion keys for 'customer.dcB.product.net'
[ERROR   ] Failed to create VM customer.dcB.product.net. Configuration value 'product' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/dev_vmware.py", line 2277, in create
    vm_=vm_) is False:
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2935, in is_profile_configured
    profile_key = opts['providers'][alias][driver]['profiles'][profile_name]
KeyError: 'product'
```

Is there a way to override the provider of a certain profile, so that it can be used with different providers? Should it be possible and I hit a bug? I am not sure if this is intended to work or not. If it is not supposed to work right now, I think it would be a great addition to avoid cluttering the profile directory: 

### Setup
```
---
-- provider-a.conf:
---
  driver: vmware
  user: 'myuser'
  password: 'mysecretpw'
  url: 'vcenter.dcA.domain.com'
  port: 443

---
-- provider-b.conf:
---
  driver: vmware
  user: 'myotheruser'
  password: 'myothersecretpw'
  url: 'vcenter.dcB.domain.com'
  port: 443
```

```
---
-- productA-in-environmentB-map.conf
---
product:
  - customer.dcB.product.net:
      provider: provider-b:vmware
      resourcepool: Resources
      cluster: vmw-cluster05
      datastore: nls-dstore-cluster03
      datacenter: Data-CenterB
      folder:  fluxcapacitor-pod02
      devices:
        network:
          Network adapter 1:
            name: dmz-switch-123
            adapter_type: vmxnet3
            switch_type: distributed
            ip: 10.0.2.12
            gateway: [10.0.2.1]
            subnet_mask: 255.255.254.0
            domain: dcB.product.net
      domain: dcB.product.net
      dns_servers:
        - 10.0.2.2
```

```
---
-- productA-environmentA-profile.conf
---
product:
  provider: provider-a
  clonefrom: product-centos7-base

  devices:
    cd:
      CD/DVD drive 1:
        device_type: client_device
        mode: passthrough
    disk:
      Hard disk 1:
        size: 25
        thin_provision: True
    network:
      Network adapter 1:
        name: Orchestration-123
        adapter_type: vmxnet3
        switch_type: distributed
        domain: dcA.product.net
  domain: dcA.product.net
  dns_servers:
    - 10.0.0.1
    - 10.0.0.2

  template: False
  power_on: True
  resourcepool: Resources
  cluster: vmw-cluster
  datastore: nls-dstore-cluster
  datacenter: Data-CenterA
  folder: fluxcapacitor-pod01
  hardware_version: 10
```

### Steps to Reproduce Issue
1. Create a profile with 'provider a' in it
2. Create a map file that tries to overrides the provider set in the profile configuration with 'provider b'

### Versions Report

```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
