### ISSUE TITLE
pkg.refresh_db does not update packages on Windows minion

### ISSUE THREAD

**Issue by cheribral** [saltstack/salt#40214]
### Description of Issue/Question
I was following the intructions here: https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html in the hopes of using salt to manage some packages in windows.  When I come to updating the package database on the minion, nothing happens.  I've tried running in various level of debug mode to see what the problem might be, but there is really nothing on the master or the minion which signify that they've tried or failed to do anything.

### Setup
In the salt master, the relevant lines I have are:
file_roots:
  base:
    - /opt/salt/srv/
winrepo_dir_ng: '/opt/salt/srv/win/salt-winrepo-ng'
winrepo_dir: '/opt/salt/srv/win/salt-winrepo'

### Steps to Reproduce Issue
On master:
salt-run winrepo.update_git_repos
https://github.com/saltstack/salt-winrepo-ng.git:
    /opt/salt/srv/win/salt-winrepo-ng/salt-winrepo-ng
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/salt-winrepo

On Minion:
C:\salt> .\salt-call.bat pkg.refresh_db 
local:
    ----------
    failed:
        0
    success:
        0
    total:
        0

### Versions Report
Master: salt-master-2016.11.3-1.el7.noarch
Minion: 2016.11.3.0

MASTER
------
...
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pull.ipc
[TRACE   ] IPCServer: Handling connection to address:
[DEBUG   ] Sending event: tag = salt/job/20170322024950063725/ret/app2-win.XXX.local; data = {'tgt_type': 'glob', 'fun_args': [], 'jid': '20170322024950063725', 'return': {'failed': 0, 'total': 0, 'success': 0}, 'retcode': 0, 'tgt': 'app2-win.XXX.local', 'cmd': '_return', '_stamp': '2017-03-22T02:49:50.066771', 'arg': [], 'fun': 'pkg.refresh_db', 'id': 'app2-win.XXX.local'}
[TRACE   ] Master function call _return took 0.00434684753418 seconds
[TRACE   ] get_event() received = {'tag': 'salt/job/20170322024950063725/ret/app2-win.XXX.local', 'data': {'tgt_type': 'glob', 'fun_args': [], 'jid': '20170322024950063725', 'return': {'failed': 0, 'total': 0, 'success': 0}, 'retcode': 0, 'tgt': 'app2-win.XXX.local', 'cmd': '_return', '_stamp': '2017-03-22T02:49:50.066771', 'arg': [], 'fun': 'pkg.refresh_db', 'id': 'app2-win.XXX.local'}}
[DEBUG   ] Gathering reactors for tag salt/job/20170322024950063725/ret/app2-win.XXX.local

MINION
------
...
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.local', 'tcp://1
92.168.106.215:4506', 'clear')
[TRACE   ] Inserted key into loop_instance_map id 76305096 for key ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.loc
al', 'tcp://xxx.xxx.xxx.215:4506', 'clear') and process 6900
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[DEBUG   ] Initializing new IPCClient for path: 4511
[TRACE   ] IPCClient: Connecting to socket: 4511
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-03-22T02:41:16.728000', 'creds': {'publish_port
': 4505, 'aes': 'u37uDbXs7I/4jQu1i7wU/D0qvdOlN8aUsZQAeV1oqk2JK6mpXAWi5PxwUH9utp+Sq53xw18mkRk=', 'master_uri': 'tcp://192
.168.106.215:4506'}, 'key': ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.local', 'tcp://xxx.xxx.xxx.215:4506')}
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.local', 'tcp://1
92.168.106.215:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.local', 'tcp://xxx.xxx.xxx.2
15:4506')
[TRACE   ] Inserted key into loop_instance_map id 76439816 for key ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.loc
al', 'tcp://xxx.xxx.xxx.215:4506', 'aes') and process 6900
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[TRACE   ] Loaded win_pkg as virtual pkg
[DEBUG   ] LazyLoaded pkg.refresh_db
[DEBUG   ] Refreshing pkg metadata db for saltenv 'base' (age of existing metadata is 0:14:16.059156)
[INFO    ] Removing all *.sls files under 'c:\salt\var\cache\salt\minion\files\base\win\repo-ng'
[DEBUG   ] LazyLoaded cp.cache_dir
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.local', 'tcp://1
92.168.106.215:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.local', 'tcp://xxx.xxx.xxx.2
15:4506')
[TRACE   ] Inserted key into loop_instance_map id 91031880 for key ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.loc
al', 'tcp://xxx.xxx.xxx.215:4506', 'aes') and process 6900
[INFO    ] Caching directory 'win/repo-ng/' for environment 'base'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.local', 'tcp://1
92.168.106.215:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.local', 'tcp://xxx.xxx.xxx.2
15:4506')
[TRACE   ] Inserted key into loop_instance_map id 76522184 for key ('c:\\salt\\conf\\pki\\minion', 'app2-win.XXX.loc
al', 'tcp://xxx.xxx.xxx.215:4506', 'aes') and process 6900
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'local': {u'failed': 0, u'total': 0, u'success': 0}}

**Comment by damon-atkins** [comment]
You only need to care about winrepo ng minion uses salt://win/repo-ng/

You also need to run cmd.exe with "Run as Administrator"

```
file_roots:
   base:
     - /srv/salt/base/state
ls -ld /srv/salt/base/win/repo-ng/salt-winrepo-ng/  
drwxr-xr-x. 6 root root 8192 Sep  8  2016 /srv/salt/base/win/repo-ng/salt-winrepo-ng/
ls -l /srv/salt/base/win
lrwxrwxrwx. 1 root root 13 Mar  7  2016 /srv/salt/base/win -> /srv/salt/win
ls -l /srv/salt/win/repo-ng/salt-winrepo-ng | wc -l
230
```

I have done it this way so environments can share the win. Which I may not continue to do.

```
With the defaults
#####  Windows Software Repo settings #####
###########################################
# Location of the repo on the master:
#winrepo_dir_ng: '/srv/salt/win/repo-ng'
#
# List of git repositories to include with the local repo:
#winrepo_remotes_ng:
#  - 'https://github.com/saltstack/salt-winrepo-ng.git'
```


C:\salt>salt-minion.bat --version
salt-minion 2016.11.3 (Carbon)

C:\salt>salt-call.bat pkg.refresh_db
[ERROR   ] win_pkg._repo_process_pkg_sls package 'dvschedulerX' within 'dvscheduler2.sls', version number 1 is not a string
[ERROR   ] win_pkg._repo_process_pkg_sls package 'dvschedulerX' within 'dvscheduler2.sls', version number 2 is not a string
[ERROR   ] win_pkg._failed_compile Failed to compile 'salt-winrepo-ng\check-mk-agent.sls': Conflicting ID 'Not Found'
[ERROR   ] win_pkg._repo_process_pkg_sls package 'duplicati' within 'salt-winrepo-ng\duplicati.sls', repo data for version number skip_urltest is not defined as a dictionary
[ERROR   ] win_pkg._failed_compile Failed to compile 'salt-winrepo-ng\intellij.sls': Conflicting ID '1'
Error running 'pkg.refresh_db': Error occurred while generating repo db. Additional info follows:

Here is an example output.  The errors are deliberate as I code up the new version of refresh_db, its just part of me testing it picks up issues.  Although the ones in salt-winrepo-ng will be gone now.

failed:
    4
failed_list:
    ----------
    dvscheduler2.sls:
        - package 'dvschedulerX', version number 1 is not a string
        - package 'dvschedulerX', version number 2 is not a string
    salt-winrepo-ng\check-mk-agent.sls:
        - Failed to compile 'salt-winrepo-ng\check-mk-agent.sls': Conflicting ID 'Not Found'
    salt-winrepo-ng\duplicati.sls:
        - package 'duplicati', repo data for version number skip_urltest is not defined as a dictionary
    salt-winrepo-ng\intellij.sls:
        - Failed to compile 'salt-winrepo-ng\intellij.sls': Conflicting ID '1'
success:
    228
total:
    232

**Comment by gtmanfred** [comment]
Thanks for the assist @damon-atkins!

Daniel

**Comment by cheribral** [comment]
Ok, thanks, I managed to get it working now.

I was running as Administrator already, so I could scratch that one off the list.

I was trying to get the old version and the new version working, hence both of those winrepo settings being set. 
It looks like I was confused by not grasping that this sentence in the documentation referred to what the minion would do by default by downloading everything under  salt://win/repo-ng/:
> They are stored in the file_roots under win/repo/salt-winrepo and win/repo-ng/salt-winrepo-ng respectively.

As I understand it now, the  `winrepo_dir_ng` setting on the master simply tells the runner where to put the git files, but does not affect the minion in any way.  If this is correct, perhaps it might be worth highlighting that sentence above in the config comments for  winrepo_dir_ng and winrepo_dir, namely that wherever they are, they must be a `file_root + 'win/repo-ng'` and `file_root + 'win/repo'` ? 

@damon-atkins in your example, the minion was able to pull from /srv/salt/base/ although your file root is deeper at /srv/salt/base/state.  Is that a typo, or am I still not understanding something?

**Comment by damon-atkins** [comment]
Leave this open until the doco are improved.  I remember have trouble getting this right the first time I did it.   I don't think you can change salt://win/repo-ng/

Could you change the title to
win_pkg doco requires improvement for masters location of the repo
https://github.com/saltstack/salt/blob/2016.11/doc/topics/windows/windows-package-manager.rst

**Comment by rosscdh** [comment]
+1 still happens in 2020

exact same issue and setup

```
file_roots:
  base:
    - /srv/salt/base
    - /srv/salt/win/
  dev:
    - /srv/salt/dev
  qa:
    - /srv/salt/qa
  prod:
    - /srv/salt/prod

winrepo_remotes_ng:
  - 'https://github.com/xxx/bit-win-repo'
  - "https://github.com/saltstack/salt-winrepo-ng"
```

```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 4.0.5
      gitpython: 3.1.2
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.7 (default, May 20 2020, 21:33:25)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: 3.0.4
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-9-amd64
         system: Linux
        version: Not Installed
```
