### ISSUE TITLE
Salt Cloud EC2 Not Using "securitygroupname" and "subnetname" when defined under "network_interfaces"

### ISSUE THREAD

**Issue by grichmond-salt** [saltstack/salt#40211]
### Description of Issue/Question
When provisioning an instance via an orchestration state, the "securitygroupname" and "subnetname" values are not working when defined under "network_interfaces" #40211.  However, the corresponding calls with "SecurityGroupId" and "SubnetId" are successful.

The steps followed were documented here:
https://docs.saltstack.com/en/latest/topics/cloud/aws.html#specifying-interface-properties

Calls using "subnetname" generate a response of:
```
AWS Response Status Code and Error: [400 400 Client Error: Bad Request for url: https://ec2.us-west-2.amazonaws.com/?Action=CreateNetworkInterface&PrivateIpAddress=192.168.128.11&SubnetId=subnet-7f06a108&Version=2014-10-01] {'Errors': {'Error': {'Message': "Address does not fall within the subnet's address range", 'Code': 'InvalidParameterValue'}}, 'RequestID': 'f7489415-b7ab-433d-b329-f208e82a7a59'}
```

Calls using "securitygroupname" create a vm that is assigned to the "default" security, instead of the one specified.

I would like to determine if this is a configuration issue, a documentation issue, or a issue with the name lookups for "securitygroupname" and "subnetname" in the ec2 module.

### Setup

Please create the following files...

/srv/pillar/top.sls
```
base:

  '*':
    - master

  'saltmaster*':
    - aws
    - cloud
```

/srv/pillar/master.conf
```
master: [ADDRESS OF MASTER HERE]
```

/srv/pillar/aws.conf
```
{# AWS Default Settings  #}
{% set keyid = 'REDACTED' %}
{% set key = 'REDACTED' %}
{% set region = 'us-west-2' %}
{% set az = 'us-west-2a' %}
{% set cidr = '192.168.128.0/24' %}

# VPC Settings
aws.vpc.keyid: {{ keyid }}
aws.vpc.key: {{ key }}
aws.vpc.region: {{ region }}

# VPC Defaults
aws.vpc.name: SaltTestDeployment_VPC
aws.vpc.cidr: {{ cidr }}

# VPC Subnet Defaults
aws.vpc.subnet.name: SaltTestDeployment_Subnet
aws.vpc.subnet.az: {{ az }}
aws.vpc.subnet.cidr: {{ cidr }}

# VPC Internet Gateway Defaults
aws.vpc.internet_gateway.name: SaltTestDeployment_Internet_Gateway

# VPC Route Table Defaults
aws.vpc.route_table.name: SaltTestDeployment_VPC-default-table

# Security Group Settings
aws.secgroup.keyid: {{ keyid }}
aws.secgroup.key: {{ key }}
aws.secgroup.region: {{ region }}

# Security Group Defaults
aws.secgroup.name: SaltTestDeployment_Security_Group
aws.secgroup.description: "Salt Test Deployment Security Group"
aws.secgroup.rules:
  - ip_protocol: tcp
    from_port: 22
    to_port: 22
    cidr_ips:
      - 0.0.0.0/0
      - {{ cidr }}
  - ip_protocol: tcp
    from_port: 80
    to_port: 80
    cidr_ips:
      - 0.0.0.0/0
      - {{ cidr }}
  - ip_protocol: tcp
    from_port: 443
    to_port: 443
    cidr_ips:
      - 0.0.0.0/0
      - {{ cidr }}
  - ip_protocol: tcp
    from_port: 4505
    to_port: 4506
    cidr_ips:
      - 0.0.0.0/0
      - {{ cidr }}
  - ip_protocol: tcp
    from_port: 5432
    to_port: 5432
    cidr_ips:
      - 0.0.0.0/0
      - {{ cidr }}
  - ip_protocol: icmp
    from_port: -1
    to_port: -1
    source_group_name: SaltTestDeployment_Security_Group
```

/srv/pillar/cloud.conf
```
cloud:
  provider: ec2_us_west_2
  az: us-west-2a

  az_instances:
    SaltTestDeployment-sseha-eapi1: 192.168.128.11
#    SaltTestDeployment-sseha-pgsql1: 192.168.128.12
#    SaltTestDeployment-sseha-eapi2: 192.168.128.21
#    SaltTestDeployment-sseha-pgsql2: 192.168.128.22
```

/srv/salt/aws/vpc-create.sls
```
{% set vpc_keyid = salt['pillar.get']('aws.vpc.keyid') %}
{% set vpc_key = salt['pillar.get']('aws.vpc.key') %}
{% set vpc_region = salt['pillar.get']('aws.vpc.region') %}

{% set vpc_name = salt['pillar.get']('aws.vpc.name') %}
{% set vpc_cidr = salt['pillar.get']('aws.vpc.cidr') %}

{% set vpc_subnet_name = salt['pillar.get']('aws.vpc.subnet.name') %}
{% set vpc_subnet_az = salt['pillar.get']('aws.vpc.subnet.az') %}
{% set vpc_subnet_cidr = salt['pillar.get']('aws.vpc.subnet.cidr') %}

{% set vpc_internet_gateway_name = salt['pillar.get']('aws.vpc.internet_gateway.name') %}
{% set vpc_route_table_name = salt['pillar.get']('aws.vpc.route_table.name') %}

ensure_vpc_exists:
  boto_vpc.present:
    - name: {{ vpc_name }}
    - cidr_block: {{ vpc_cidr }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
        region: {{ vpc_region }}

ensure_subnet_exists:
  boto_vpc.subnet_present:
    - name: {{ vpc_subnet_name }}
    - vpc_name: {{ vpc_name }}
    - cidr_block: {{ vpc_subnet_cidr }}
    - availability_zone: {{ vpc_subnet_az }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
        region: {{ vpc_region }}

ensure_internet_gateway_exists:
  boto_vpc.internet_gateway_present:
    - name: {{ vpc_internet_gateway_name }}
    - vpc_name: {{ vpc_name }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
        region: {{ vpc_region }}

ensure_route_table_exists:
  boto_vpc.route_table_present:
    - name: {{ vpc_route_table_name }}
    - vpc_name: {{ vpc_name }}
    - routes:
      - destination_cidr_block: 0.0.0.0/0
        internet_gateway_name: {{ vpc_internet_gateway_name }}
    - subnet_names:
      - {{ vpc_subnet_name }}
    - profile:
        keyid: {{ vpc_keyid }}
        key: {{ vpc_key }}
        region: {{ vpc_region }}
```

/srv/salt/aws/secgroup-create.sls
```
{% set secgroup_keyid = salt['pillar.get']('aws.secgroup.keyid') %}
{% set secgroup_key = salt['pillar.get']('aws.secgroup.key') %}
{% set secgroup_region = salt['pillar.get']('aws.secgroup.region') %}

{% set secgroup_name = salt['pillar.get']('aws.secgroup.name') %}
{% set secgroup_description = salt['pillar.get']('aws.secgroup.description') %}
{% set secgroup_rules = salt['pillar.get']('aws.secgroup.rules') %}

{% set vpc_name = salt['pillar.get']('aws.vpc.name') %}

ensure_secgroup_exists:
  boto_secgroup.present:
    - name: {{ secgroup_name }}
    - description: {{ secgroup_description }}
    - rules:
      {% for rule in secgroup_rules %}
      - ip_protocol: {{ rule.ip_protocol }}
        from_port: {{ rule.from_port }}
        to_port: {{ rule.to_port }}

        {% if rule.cidr_ips is defined %}
        cidr_ip:
        {% for cidr_ip in rule.cidr_ips %}
         - {{ cidr_ip }}
        {% endfor %}
        {% endif %}

        {% if rule.source_group_name is defined %}
        source_group_name: {{ rule.source_group_name }}
        {% endif %}

      {% endfor %}
    - tags:
        Name: {{ secgroup_name }}
    - vpc_name: {{ vpc_name }}
    - region: {{ secgroup_region }}
    - keyid: {{ secgroup_keyid }}
    - key: {{ secgroup_key }}
```

/srv/salt/create-test.sls
```
{% set master = salt['pillar.get']('master') %}
{% set provider = salt['pillar.get']('cloud:provider') %}
{% set az = salt['pillar.get']('cloud:az') %}
{% set az_instances = salt['pillar.get']('cloud:az_instances') %}
{% set secgroup = salt['pillar.get']('aws.secgroup.name') %}
{% set subnet = salt['pillar.get']('aws.vpc.subnet.name') %}

provision_vm
  salt.runner:
    - name: cloud.create
    - provider: {{ provider }}
    - instances:
      - {{ instance }}
    - image: ami-6f68cf0f
    - size: t2.micro
    - ssh_interface: public_ips
    - ssh_username: ec2-user
    - availability_zone: {{ az }}
    - minion:
        master: {{ master }}
    - network_interfaces:
      - DeviceIndex: 0
        allocate_new_eip: True
        PrivateIpAddress: {{ ip_address }}

        # Works
        #SubnetId: "subnet-e9c271a0"

        # Fails
        subnetname: "{{ subnet }}"

        # Works
        #SecurityGroupId:
        #  - "sg-2c5a4654"

        # Fails
        securitygroupname:
          - "{{ secgroup }}"
```

### Steps to Reproduce Issue

After creating the files listed above, please run the following:
```
salt-run state.orch aws.vpc-create
salt-run state.orch aws.secgroup-create
salt-run state.orch create-test
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
```

**Comment by gtmanfred** [comment]
From the documentation https://docs.saltstack.com/en/latest/topics/cloud/aws.html#specifying-interface-properties

It looks like you can only use SubnetId and SecurityGroupId

```
  # Do not include either 'subnetid', 'subnetname', 'securitygroupid' or
  # 'securitygroupname' here if you are going to manually specify
  # interface configuration
  #
  network_interfaces:
    - DeviceIndex: 0
      SubnetId: subnet-XXXXXXXX
      SecurityGroupId:
        - sg-XXXXXXXX
```
