### ISSUE TITLE
Salt Windows saltutil.regen_keys doesn't function as expected

### ISSUE THREAD

**Issue by joshland** [saltstack/salt#40320]
### Description of Issue/Question
Key regen's leave windows minions unable to connect to master. This appears to be because read-only file attributes are set on the minion.pem file.

### Setup
Windows 7, Professional, no domain
Local users only.
local install of salt 2016.11.3

### Steps to Reproduce Issue
Install Salt 2016.11.3 from binary packages.
Approve key on master.  
 c:\salt\conf\pki\minion\minion.pem
 c:\salt\conf\pki\minion\minion.pub
 c:\salt\conf\pki\minion\minion_master.pub

issue "saltutil.regen_keys" from mastr

One file remains:
 c:\salt\conf\pki\minion\minion.pem 

Minion cannot contact master.  I was not able to coax the regen into completion.  I did

`del minion.pem`  -- Permission denied

`attrib -r -h -s minion.pem`
`del minion.pem`
'net stop salt-minion`
`net start salt-minion1

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free

**Comment by gtmanfred** [comment]
Can you provide me the minion config you are using?

I am not able to replicate this.

```
[root@ip-10-0-0-120 ~]# salt \* test.ping
windows.gtmanfred.com:
    True
[root@ip-10-0-0-120 ~]# salt \* saltutil.regen_keys
windows.gtmanfred.com:
    None
[root@ip-10-0-0-120 ~]# salt \* test.ping
windows.gtmanfred.com:
    True
[root@ip-10-0-0-120 ~]# salt \* test.versions_report
windows.gtmanfred.com:
    Salt Version:
               Salt: 2016.11.3

    Dependency Versions:
               cffi: 1.7.0
           cherrypy: 7.1.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.8
              ioflo: 1.5.5
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: 0.7.6.None
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 16.0.1
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.4.1
                ZMQ: 4.1.6

    System Versions:
               dist:
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
```

Unfortunately I am not able to test this on windows 7.

Thanks,
Daniel
