### ISSUE TITLE
`temp.file` does not close the file handle

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#40417]
### Description of Issue/Question

I'm using `temp.file()` to get a temporary file(name) in jinja. I then reference the filename in a state and do some stuff. After the state completes, I want to remove the temporary file, preferably using `file.absent`.

On linux, no problem, it's perfectly happy removing the file with the open file handle.

On windows, not so much. Because the file handle is open, it errors when attempting to remove the file. Once the python process exits, the file is released, and then I can remove it.

### Setup
test.sls:
```
{%- set temp = salt.temp.file() %}

touch it:
  file.touch:
    - name: {{ temp }}
    
remove it:
  file.absent:
    - name: {{ temp }}
    - require:
      - file: touch it
```

### Steps to Reproduce Issue
`c:\salt\salt-call.bat --local state.sls test`

### Versions Report
```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
