### ISSUE TITLE
Pillar in state.sls not work from command line when an archive.extracted is before the jinja

### ISSUE THREAD

**Issue by rrfeng** [saltstack/salt#40444]
### Description of Issue/Question
I think something is wrong with the cache.

### Steps to Reproduce Issue
sls:
```
/tmp/codis:
  archive.extracted:
    - source: salt://package/test/t.tgz
    - tar_options: z
    - archive_format: tar

/tmp/salt-test:
  file.managed:
    - source: salt://package/test/f.jinja
    - template: jinja
    - require:
      - archive: /tmp/codis
```

f.jinja:
```
{{ pillar['content'] }}
```

run first time:
```
salt-call state.sls package.test pillar='{"content": "testcontent"}'
or
salt 'host' state.sls package.test pillar='{"content": "testcontent"}'

got:
----------
          ID: /tmp/codis
    Function: archive.extracted
      Result: True
     Comment: salt://package/test/t.tgz extracted in /tmp/codis/
     Started: 11:24:13.428823
    Duration: 818.893 ms
     Changes:
              ----------
              directories_created:
                  - /tmp/codis/
              extracted_files:
                  no tar output so far
----------
          ID: /tmp/salt-test
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'dict' object has no attribute 'role'
     Started: 11:24:14.250532
    Duration: 52.354 ms
     Changes:

Summary
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
```

run second time using same command:
```
----------
          ID: /tmp/codis
    Function: archive.extracted
      Result: True
     Comment: /tmp/codis/ already exists
     Started: 11:23:35.107878
    Duration: 0.47 ms
     Changes:
----------
          ID: /tmp/salt-test
    Function: file.managed
      Result: True
     Comment: File /tmp/salt-test updated
     Started: 11:23:35.109973
    Duration: 10.854 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644

Summary
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
```

change the order of sls:
```
/tmp/salt-test:
  file.managed:
    - source: salt://package/test/f.jinja
    - template: jinja

/tmp/codis:
  archive.extracted:
    - source: salt://package/test/t.tgz
    - tar_options: z
    - archive_format: tar
```

run on a fresh host(no the previous one):
```
salt-call state.sls package.test pillar='{"content": "testcontent"}'
```

everything going to be ok, no need to run second time

### Versions Report
salt-minion:
```
           Salt: 2015.5.5
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```
salt-master:
```
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```
