### ISSUE TITLE
mac address assignment for clone from feature

### ISSUE THREAD

**Issue by azerioglan** [saltstack/salt#40460]
HI all,

I am using salt-cloud for VMs deployment in vmware. I opened an issue #34035 regarding mac address assignment. I have couple additional bugs regarding to mac address assignment.
1.  issue #34035 doesn't reflect in current salt release for Ubuntu 14. Actually you guys provide  me vmwary.py with fixed code and I am using it, but i could not use new features
2. Mac address assignment doesn't work if we using "clone from". I tested it in Centos 7 and Ubuntu 14

Here is my config:

```
ubuntu:
  provider: vcenter
  clonefrom: ubuntu14
  datastore: server13-datastore2
  
  devices:
    network:
      Network adapter 1:
        mac: '00:05:56:a5:ab:cd'
        name: 192.168.1.0
        adapter_type: vmxnet3
        switch_type: standard

  domain: example.com
  dns_servers:
    - 10.9.1.1
    - 10.9.1.2

  cluster: management

  datacenter: home-dc
  template: False
  power_on: True
 
  customization: False
  
  ssh_username: user
  password: 12345678
  minion:
    master: 10.9.1.3

  hardware_version: 10
```

Here is version report

```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul 18 2016, 15:02:52)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
