### ISSUE TITLE
archive.extracted does not extract archives if file list has not changed but contents have

### ISSUE THREAD

**Issue by jerrykan** [saltstack/salt#40484]
### Description of Issue/Question
The `archive.extracted` state does not extract the contents of an archive if the file list has not changed (even if the contents of the files has changed). The file list in the archive needs to change before salt will decide to extract the archive.

### Setup
Create 3 archives as follows:

```
$ mkdir files
$ echo "This is file1" > files/file1.txt
$ echo "This is file2" > files/file2.txt
$ tar -zvcf files-v1.tar.gz files/
files/
files/file1.txt
files/file2.txt
```

```
$ echo "This is and updated file1" > files/file1.txt
$ echo "This is and updated file2" > files/file2.txt
$ tar -zvcf files-v2.tar.gz files/
files/
files/file1.txt
files/file2.txt
```

```
$ echo "This is and updated file1" > files/file1.txt
$ echo "This is and updated file2" > files/file2.txt
$ echo "This is file3" > files/file3.txt
$ tar -zvcf files-v3.tar.gz files/
files/
files/file1.txt
files/file2.txt
files/file3.txt
```

```
$ sha256sum files-v*.tar.gz
12f347ab2b9e661ec96b6805cfed34598e2df138af35c91852c3c46ade10a8e7  files-v1.tar.gz
d7aea33efe98e9662c135af6e5730e978423740a8eb971b072d88a3f74f9897a  files-v2.tar.gz
ee22eecd4fe6c8d6daf012eb08d1ada4c94abd0614f6444826118ede3644053e  files-v3.tar.gz
```

### Steps to Reproduce Issue
Start with a state `usecase/test.sls` and run it:

```
files-archive:
  archive.extracted:
    - name: /opt/
    - source: http://fileserver/files-v1.tar.gz
    - source_hash: sha256=12f347ab2b9e661ec96b6805cfed34598e2df138af35c91852c3c46ade10a8e7
    - source_hash_update: True
    - archive_format: tar
```

```
$ salt-call state.apply usecase.test

local:
----------
          ID: files-archive
    Function: archive.extracted
        Name: /opt/
      Result: True
     Comment: http://fileserver/files-v1.tar.gz extracted to /opt/
     Started: 15:36:43.820642
    Duration: 210.415 ms
     Changes:   
              ----------
              extracted_files:
                  - files
                  - files/file2.txt
                  - files/file1.txt

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 210.415 ms
```

Update the state and run again:

```
files-archive:
  archive.extracted:
    - name: /opt/
    - source: http://fileserver/files-v2.tar.gz
    - source_hash: sha256=d7aea33efe98e9662c135af6e5730e978423740a8eb971b072d88a3f74f9897a
    - source_hash_update: True
    - archive_format: tar
```

```
$ salt-call state.apply usecase.test

local:
----------
          ID: files-archive
    Function: archive.extracted
        Name: /opt/
      Result: True
     Comment: All files in archive are already present
     Started: 15:39:07.857590
    Duration: 203.386 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 203.386 ms
```

Note that no changes are made even thought the `source_hash` is different and the contents of the files in the archive are different.

Update the state one more time and run again:

```
files-archive:
  archive.extracted:
    - name: /opt/
    - source: http://fileserver/files-v3.tar.gz
    - source_hash: sha256=ee22eecd4fe6c8d6daf012eb08d1ada4c94abd0614f6444826118ede3644053e
    - source_hash_update: True
    - archive_format: tar
```

```
$ salt-call state.apply usecase.test

local:
----------
          ID: files-archive
    Function: archive.extracted
        Name: /opt/
      Result: True
     Comment: http://fileserver/files-v3.tar.gz extracted to /opt/
     Started: 15:42:09.392288
    Duration: 205.973 ms
     Changes:   
              ----------
              extracted_files:
                  - files
                  - files/file2.txt
                  - files/file3.txt
                  - files/file1.txt

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 205.973 ms
```

Note how this time the archive is extracted because a new files has been added to the archive.

### Versions Report
```
Salt Version:
           Salt: 2016.11.0-1129-g058dcbf
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this. I believe `archive.list` which does a check to see if it needs to be re-extracted only checks if there are files changes and doesn't check the contents of the files. Although we should be checking on the hash as well.

ping @terminalmage I am not sure if this is considered a duplicate of https://github.com/saltstack/salt/issues/39868 but might be a side case. Will label as a bug for now unless you tell me this will be fixed by that issue as well.

**Comment by terminalmage** [comment]
``source_hash_update`` is working exactly as it's supposed to. You're changing the name of archive each time, so _of course_ we don't detect a change to the hash.

**Comment by jerrykan** [comment]
@terminalmage this raises a new question then, what is the correct way to push out a new version of an archive (assuming the versions are contained in the archive name)? Based on the documentation I assumed that if the `source_hash` changed and `source_hash_update` was set to `True` then it would trigger an extract. Does the documentation need to be updated to reflect that this is not always the case?

I ran the original tests again against devel without changing the archive name, and changing only the contents and hashes, but only the initial run triggered an extract. I'll test again once the problems with pull request saltstack/salt#40551 mentioned in #40482 are resolved

**Comment by terminalmage** [comment]
The way to do this would be to use the ``overwrite`` argument. If you don't wish to update your SLS file for this just to overwrite, then have to change it back after deploying the new version, then you could manage it using pillar data and pass in a pillar key on the CLI. For example:

```
deploy_tarball:
  archive.extracted:
    - name: /path/to/destination
    - source: salt://my-archive-v1.2.3.tar.gz
    - overwrite: {{ salt['pilllar.get']('force_deploy', False) }}
```

Assuming this is salt://foo.sls, you could then do the following:

```
salt myminion state.apply foo pillar='{force_deploy: True}'
```  

The documentation could be updated to be more clear on this, as well as the behavior of ``source_hash_update``. I'll see what I can do.
