### ISSUE TITLE
Problems with encoding, UTF-8 or Unicode

### ISSUE THREAD

**Issue by tkaehn** [saltstack/salt#40486]
### Description of Issue/Question

Especially with pillar data it doesn't seem to be possible to use UTF-8 encoded characters.
Please see output below - most of the test cases do not work. Is there any possibility or workaround to use UTF-8 in pillar data?

### Setup
```
master# salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7 
 
master# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
master# grep yaml_utf8 /etc/salt/master
yaml_utf8: True
master# cat /srv/pillar/example_data.sls 
test: täst

master# tail -n +1 /srv/salt/test*
==> /srv/salt/test1.sls <==
# master# salt \* state.apply test1           => works
# master# salt-call state.apply test1         => works
# master# salt-call --local state.apply test1 => works
# minion# salt-call state.apply test1         => works
test:
  user.present:
    - fullname: täst


==> /srv/salt/test2.sls <==
# master# salt \* state.apply test2           => not OK
# master# salt-call state.apply test2         => not OK
# master# salt-call --local state.apply test2 => works
# minion# salt-call state.apply test2         => not OK
test2:
  user.present:
    - fullname: {{ pillar['test'] }}
    

==> /srv/salt/test3.jinja <==
{{ pillar['test'] }}


==> /srv/salt/test3.sls <==
# master# salt \* state.apply test3           => not OK
# master# salt-call state.apply test3         => not OK
# master# salt-call --local state.apply test3 => works
# minion# salt-call state.apply test3         => not OK
/tmp/test3.txt:
  file.managed:
    - source: salt://test3.jinja
    - template: jinja


==> /srv/salt/test4.sls <==
# master# salt \* state.apply test4           => not OK
# master# salt-call state.apply test4         => not OK
# master# salt-call --local state.apply test4 => not OK
# minion# salt-call state.apply test4         => not OK
/tmp/test4.txt:
  file.managed:
    - contents: {{ pillar['test'] }}


==> /srv/salt/test5.sls <==
# master# salt \* state.apply test5           => not OK
# master# salt-call state.apply test5         => not OK
# master# salt-call --local state.apply test5 => not OK
# minion# salt-call state.apply test5         => not OK
/tmp/test5.txt:
  file.managed:
    - contents: täst
```

### Steps to Reproduce Issue
Please see comments in files above.

### Versions Report
Please see above.

**Comment by tkaehn** [comment]
Using `.decode('utf-8')` as suggested in some other comments solves some of the problems or test cases but prevents `--local` from working.

```
master# cat test2.sls 
# master# salt \* state.apply test2           => works
# master# salt-call state.apply test2         => works
# master# salt-call --local state.apply test2 => not OK
# minion# salt-call state.apply test2         => works
test2:
  user.present:
    - fullname: {{ pillar['test'].decode('utf-8') }}
    
master# cat test3.jinja test3.sls 
{{ pillar['test'].decode('utf-8') }}

# master# salt \* state.apply test3           => works
# master# salt-call state.apply test3         => works
# master# salt-call --local state.apply test3 => not OK
# minion# salt-call state.apply test3         => works
/tmp/test3.txt:
  file.managed:
    - source: salt://test3.jinja
    - template: jinja
```

**Comment by Ch3LL** [comment]
Can you explain where you are adding `.decode('utf-8')` when it works?

**Comment by tkaehn** [comment]
Hi Megan,

please see my previous comment. In case of test2 I added `.decode('utf-8')` to the sls file and in  test3 I added it to the template:

```
master# cat test2.sls 
# master# salt \* state.apply test2           => works
# master# salt-call state.apply test2         => works
# master# salt-call --local state.apply test2 => not OK
# minion# salt-call state.apply test2         => works
test2:
  user.present:
    - fullname: {{ pillar['test'].decode('utf-8') }}
```

```
master# tail -n +1 test3.*
==> test3.jinja <==
{{ pillar['test'].decode('utf-8') }}


==> test3.sls <==
# master# salt \* state.apply test3           => works
# master# salt-call state.apply test3         => works
# master# salt-call --local state.apply test3 => not OK
# minion# salt-call state.apply test3         => works
/tmp/test3.txt:
  file.managed:
    - source: salt://test3.jinja
    - template: jinja
```

For the other test cases adding `.decode('utf-8')` wasn't applicable or not working.

Best regards
Thomas

**Comment by alexwbaule** [comment]
I Got the same Issue, with Salt 2016.11.5, in a CentOS 7.
Basically, i try to create a file with file.serialize:

```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

```

My Pillar has:
```
  sensu:
    config:
      host: 0.0.0.0
      ldap:
        bindUser: "CN=Autenticação,CN=Users,DC=example,DC=com"
```

and my state has:

```
{% from "recipes/sensu/maps/uchiwa.jinja" import sensu with context -%}

uchiwa:
  file.serialize:
    - name: /etc/sensu/uchiwa.json
    - formatter: json
    - mode: 644
    - user: uchiwa
    - group: sensu
    - require:
      - pkg: pkg-uchiwa
    - dataset:
        sensu:
          {{ sensu.uchiwa.sites }}
        uchiwa:
          {{ sensu.uchiwa.config }}
```

My jinja template:

```
{% set sensu = salt['grains.filter_by']({
    'default': {
        'uchiwa': {
            'host': '0.0.0.0',
            'port': 3000,
            'refresh': 10
        },
        'sites': [
            {
                'name': 'Sensu',
                'host': '127.0.0.1',
                'port': 4567,
                'ssl': False,
                'insecure': False,
                'path': '',
                'user': 'admin',
                'password': '',
                'timeout': 5
            }
        ],
    },
}, merge=salt['pillar.get']('sensu'), default='default') %}
```

There is no error in the execution, but the file has a wrong string:
```
[root@salt-test ~]# cat /etc/sensu/uchiwa.json |grep bindUser
      "bindUser": "CN=Autentica\\xc3\\xa7\\xc3\\xa3o,CN=Users,DC=example,DC=com",
```

There is some workaround for this ?

**Comment by Paraomao** [comment]
I got the same issue using the state file.serialize with Salt 2018.3.3.

```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

Trying to serialize (file.serialize) a pillar on file, I get a wrong result:

Test state:

```
/testfile.yml: 
  file.serialize:
    - mode: 640
    - user: root
    - group: tomcat
    - makedirs: True
    - formatter: yaml
    - dataset_pillar: testdata:config
```

Test pillar:

```
testdata:
    config:
        test: '123èéà456'
```


Expected file content:

`test: 123èéà456`

Got file content:

`test: 123\xc3\xa8\xc3\xa9\xc3\xa0456`

Best regards
