### ISSUE TITLE
trim_output ignored by archive.extracted

### ISSUE THREAD

**Issue by cavepopo** [saltstack/salt#40491]
### Description of Issue/Question
According to [documentation](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.archive.html) _trim_output_ param should prevent _archive.extracted_ from listing ALL extracted files.
I can't get this one to work using the following example : 
```
extract_tomcat:
  archive.extracted:
    - name: /******/
    - source: salt://resource/files/tomcat_8.0.35.tgz
    - user: *******
    - group: *******
    - trim_output: True
    - require:
      - archive: extract_java
```

I also tried to use a integer (10 for example), but this doesn't have any effect on the output which show ALL files being extracted.

### Steps to Reproduce Issue
Try the _trim_output_ in any context ....

### Versions Report
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.25.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.25.0
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 4.4.35-1-pve
         system: Linux
        version: debian 8.7 
```

Not a big deal I agree but still ....

**Comment by Ch3LL** [comment]
@cavepopo looks like i'm able to replicate this. I also tried `trim_output: 10` and it output all the files. Looks like we need to get this fixed up thanks

**Comment by Ch3LL** [comment]
Also here is the state file i used:

```
extract_tomcat:
  archive.extracted:
    - name: /tmp/test/
    - source: https://github.com/saltstack/salt/archive/v2016.3.6.tar.gz
    - source_hash: md5=d11d318a2527e7943d3824b629955270
    - trim_output: 10
    - if_missing: /tmp/test/v2016.3.6/
```
