### ISSUE TITLE
salt-cloud not respecting subnetId

### ISSUE THREAD

**Issue by abonillasuse** [saltstack/salt#40499]
### Description of Issue/Question

While deploying to aws and specifying a SubnetId, the image is not placed in the correct subnet/VPC

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
aws-ses-mutiple:
  provider: aws
  # SLE 12-SP2 
  image: ami-fde4ebea
  deploy: False
  SubnetId: subnet-f8f55f8f
  SecurityGroupId: sg-0f6da719
  size: m3.medium
  ssh_username: ec2-user
  del_root_vol_on_destroy: True
  del_all_vol_on_destroy: True
  volumes:
    - { size: 20, device: /dev/sdb, type: gp2, tags: {"Environment": "xyzzy"} }
    - { size: 20, device: /dev/sdc, type: gp2, tags: {"Environment": "xyzzy "} }
    - { size: 20, device: /dev/sdd, type: gp2, tags: {"Environment": "xyzzy"} }
    - { size: 20, device: /dev/sde, type: gp2, tags: {"Environment": "xyzzy"} }
  #network_interfaces:
  #  - DeviceIndex: 0
  #    PrivateIpAddresses:
  #      - Primary: True
  #    AssociatePublicIpAddress: True
      #SubnetId: subnet-f8f55f8f
      #SecurityGroupId: sg-0f6da719

```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

salt-cloud -m /etc/salt/cloud.maps.d/aws-ses.map

If I leave the commented fields above, the deployment takes place but they don't appear in the correct VPC, they don't even get a SubnetId assigned as per the Dashboard,  therefore the wrong IP, etc.

If I uncomment those fields, I get:
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request for url: https://ec2.us-east-1.amazonaws.com/?.....n=2014-10-01] {'Errors': {'Error': {'Message': 'Network interfaces and an instance-level security groups may not be specified on the same request', 'Code': 'InvalidParameterCombination'}}, 'RequestID': 'b18583cd-fbb0-4232-b1fc-.....'}

Although that is how is documented here:
https://docs.saltstack.com/en/latest/topics/cloud/aws.html

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 12
        machine: ppc64le
        release: 4.4.49-92.11-default
         system: Linux
        version: SUSE Linux Enterprise Server  12
