### ISSUE TITLE
salt chedule - redis returner - Traceback

### ISSUE THREAD

**Issue by sznmaran** [saltstack/salt#40492]
### Description of Issue/Question
Can't get working setup with redis returner.

### Setup
**.../pillar/schedule/job.sls**  
schedule:
  keep-motd:
    maxrunning: 1
    function: state.sls
    hours: 20
    splay: 600
    returner: redis
    args:
      - test-dir.test-state
    kwargs:
      saltenv: base

**.../state/test-dir/test-state.sls**
/tmp/test_file:
  file.append:
    - name: /tmp/test_file
    - text:
      - hallo world

### Steps to Reproduce Issue
The fastest way to reproduce the issue is to use returner directly(without waiting for the schedule..)
salt '*' test.ping --return redis --return_kwargs '{"db": "redisserverhost"}'

# Minion log
2017-04-03 16:13:32,976 [salt.minion                                          ][INFO    ][8220] User root Executing command test.ping with jid 20170403161332473482
2017-04-03 16:13:32,995 [salt.minion                                          ][INFO    ][9114] Starting a new job with PID 9114
2017-04-03 16:13:33,050 [salt.minion                                          ][INFO    ][9114] Returning information for job: 20170403161332473482
2017-04-03 16:13:33,192 [salt.minion                                          ][ERROR   ][9114] The return failed for job 20170403161332473482 'keep_jobs'
2017-04-03 16:13:33,192 [salt.minion                                          ][ERROR   ][9114] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1530, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python2.7/dist-packages/salt/returners/redis_return.py", line 127, in returner
    pipeline.expire('ret:{0}'.format(jid), _get_ttl())
  File "/usr/lib/python2.7/dist-packages/salt/returners/redis_return.py", line 116, in _get_ttl
    return __opts__['keep_jobs'] * 3600
KeyError: 'keep_jobs'

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 3.18.48-zen
         system: Linux
        version: debian 8.7

**Comment by Ch3LL** [comment]
If you specifyin in your master config do you still see this error: `keep_jobs: 24`

**Comment by sznmaran** [comment]
Hello, 
  there is `keep_jobs: 48` allready.

**salt master.cfg:**
```
worker_threads: 10
keep_jobs: 48
timeout: 60
gather_job_timeout: 30

log_level: info
log_level_logfile: debug
state_output: changes

file_ignore_regex:
    - '/\.svn($|/)'
    - '/\.git($|/)'

file_ignore_glob:
    - '*.pyc'
    - '*.swp'
    - '*.class'
    - '*.o'

fileserver_backend:
    - roots
    - git

file_roots:
   base:
     - /opt/salt/env/base

pillar_roots:
    base:
        - /opt/salt/env/pillar
    dev:
        - /opt/salt/env/pillar-dev

ext_pillar:
    - git:
        - dev git@gitlab.local:admins/dev-salt-pillar.git

gitfs_provider: gitpython
gitfs_remotes:
    - git@gitlab.local:salt/dev-formulas.git
    - git@gitlab.local:admins/dev-salt-state.git

ext_pillar_first: True
```

**Comment by Ch3LL** [comment]
K can you add it to minion config?That should work. I think this is due to it not being able to access master opts. You might have to enable pillar_opts if you want to enable master_opts to show up on minion side. (although note this will show any sensitive information you might have in the master config on the minion) Let me ask internally if this is expected behavior.

**Comment by sznmaran** [comment]
**Hi,  Well it's much better.** 
If I put "keep_jobs:" option to minion config then the test cmd work! And the result is in redis DB..
```
salt 'salt-test-minion1*' cmd.run 'cat /etc/issue' --return redis --return_kwargs '{"host": "salt.dev", "db": 0}' test=false
```

**But i can't get working setup for scheduler**


Schedule pillar:
```
schedule:
  keep-motd:
    maxrunning: 1
    function: state.sls
    hours: 20
    splay: 600
    args:
      - dev-test.keep-motd
    kwargs:
      saltenv: base
      test: false
    returner: redis
    return_kwargs:
      host: 'a3salt-redis'
```

Error:
```
2017-04-07 14:53:19,327 [salt.utils.schedule                                  ][ERROR   ][29223] Unhandled exception running state.sls
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 855, in handle_func
    self.returners[ret_str](ret)
  File "/usr/lib/python2.7/dist-packages/salt/returners/redis_return.py", line 127, in returner
    pipeline.hset('ret:{0}'.format(jid), minion, json.dumps(ret))
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
ValueError: Circular referenc
```

It doesn't matter if i add redis options to minion config or not..

```
# minion config file
test: True
log_level: error
log_level_logfile: debug
grains_refresh_every: 15
keep_jobs: 24
redis.db: '0'
redis.host: 'salt.dev'
redis.port: 6379
```
