### ISSUE TITLE
Issue while executing windows sls file

### ISSUE THREAD

**Issue by bhanukumar22** [saltstack/salt#40514]
I'm trying to execute the below code in my test machine to install mysql on windows machine. Code is available in https://github.com/saltstack/salt-winrepo-ng. 

server5:/srv/salt/mysql_windows# more init.sls
```
mysql-essential:
  '5.1.73':
    full_name: 'MySQL Server 5.1'
    {% if grains['cpuarch'] == 'AMD64' %}
    installer: 'http://cdn.mysql.com/Downloads/MySQL-5.1/mysql-essential-5.1.73-winx64.msi'
    uninstaller: 'http://cdn.mysql.com/Downloads/MySQL-5.1/mysql-essential-5.1.73-winx64.msi'
    {% elif grains['cpuarch'] == 'x86' %}
    installer: 'http://cdn.mysql.com/Downloads/MySQL-5.1/mysql-essential-5.1.73-win32.msi'
    uninstaller: 'http://cdn.mysql.com/Downloads/MySQL-5.1/mysql-essential-5.1.73-win32.msi'
    {% endif %}
    install_flags: '/qn /norestart'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
```
Getting below error: 
---------------------------------------------------------------------------------------
/srv/salt/mysql_windows# salt vmware-win-2008 state.apply mysql_windows
vmware-win-2008:
    Data failed to compile:
----------
    State 'mysql-essential' in SLS 'mysql_windows' is not formed as a list
ERROR: Minions returned with non-zero exit code
-----------------------------------------------------------------------------------------

Am I missing something here?
Your quick help would be much appreciated.
