### ISSUE TITLE
Proposal: Special flag for gitfs remote to merge it into all environments

### ISSUE THREAD

**Issue by ekristen** [saltstack/salt#40527]
I've recently wanted to start separating out some of my states, including my dynamic execution modules into their own repos because I'm finding I'm not making many changes to them but keeping them in sync across multiple branches in a single git repo is difficult.

I'm proposing that salt has a way to identify a specific remote as a "global" one and merges it in.

For example, if I have my main `salt-states` repo with 12 different branches, corresponding to different environments, and then 2 other repos that container dynamic execution modules/states or just state files, I'd have to branch the other 2 repos 12 times each to match their branch names up. It becomes problematic if I need to make one change, I then have to update 12 branches.

If my 2 formula repos can be marked as "global" then anything in the master branch will be merged into any environment.

**Comment by gtmanfred** [comment]
@terminalmage do you have any opinions about this?

Thanks
Daniel

**Comment by ekristen** [comment]
To further elaborate, something like this ...

```
gitfs_remotes:
  - git+ssh://git@github.com/ekristen/salt-states.git
  - git+ssh://git@github.com/ekristen/salt-formula-one.git:
    - formula/global: true
    - branch: master
```

If the `saltenv` is `prod` I believe that branch `prod` from `git+ssh://git@github.com/ekristen/salt-states.git` will be used and have priority over `git+ssh://git@github.com/ekristen/salt-formula-one.git`, the branch by default should be master, but can be changed if necessary. 

On formula/global remote, only a single branch can be used and should get lowest priority when it comes to merge.

**Comment by terminalmage** [comment]
``branch`` would be a bad idea for the name since tags are also used as environments. I also don't understand the thinking behind using ``formula/global``. A better schema, IMO, would be something like this:

```yaml
gitfs_remotes:
  - git+ssh://git@github.com/ekristen/salt-states.git
  - git+ssh://git@github.com/ekristen/salt-formula-one.git:
    - global: master
```

@gtmanfred what do you think?
