### ISSUE TITLE
file.managed with http client certificate

### ISSUE THREAD

**Issue by LrsK** [saltstack/salt#40537]
I have a webserver that I want to use as a source in file.managed states. The webserver requires a client certificate for authentication. 

I have tried the following after inspecting the state-code:
```
/opt/my_file:
    file.managed:
        - source: https://myserver.com/my_file
        - source_hash: abc123
        - cert: /etc/my_cert
```

This does not seem to use the certificate. How can I specify which client certificate to use?

**Comment by Ch3LL** [comment]
@LrsK i'm not quit seeing this functionality. Where are you seeing that argument? can you point me to the code?

**Comment by LrsK** [comment]
The file.managed state has a source parameter, that can be set to an http-url. When this is used, the query-function in the utils.http package is called. Here is the code for the query-function:
 https://github.com/saltstack/salt/blob/3b81c37a531c48ff54a2332c4ea9c0d108ce0e74/salt/utils/http.py#L91

In this function, the client certificate can be set in the cert-parameter, or read from the master or minion config. 

 My question is: how can I set the cert parameter in the file.managed state, and have it appear in the query-function?

**Comment by Ch3LL** [comment]
Thanks for clarifying that. From what I can see this does not exist and would need to be added. I started up a pdb debugger and saw this is the stack trace from the file.managed file in the state module to the query call in salt/utils/https.py:

```
  /testing/salt/states/file.py(1836)managed()
-> **kwargs
  /testing/salt/modules/file.py(3760)get_managed()
-> sfn = __salt__['cp.cache_file'](source, saltenv)
  /testing/salt/modules/cp.py(405)cache_file()
-> result = _client().cache_file(path, saltenv)
  /testing/salt/fileclient.py(178)cache_file()
-> return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  /testing/salt/fileclient.py(625)get_url()
-> **get_kwargs
> /testing/salt/utils/http.py(145)query()
-> if opts is None:
```

We will need to get this added. Feel free to take a stab at adding this functionality  if interested

**Comment by LrsK** [comment]
Just to add to the discussion: It seems like this functionality would be useful in all places where the http(s) scheme is used in the source. Another example is the pkg.installed state, and I believe there are other places as well. In fact, it would be nice if other options could be set as well, such as headers, or whether to check the server certificate.

As far as implementing this, I'm not sure what the best way would be. It seems like options that apply to the source-parameter get their own fields, like source_hash. This would become messy after a while, as more options are added. Would it be better if the concept of a "source" was fleshed out more, and could accept it's own options e.g. like this:

```
/opt/my_file:
    file.managed:
        - source: https://myserver.com/my_file
            hash: abc123
            cert: /etc/my_cert
            verify_ssl: True
            headers:
                - X-Forward-This: ok
                - X-MyHeader: fun_thing
```

Please correct me if I am wrong in my assessment. as I'm not very familiar with the salt code base.
