### ISSUE TITLE
Could pkg module install package updates for base versions only?

### ISSUE THREAD

**Issue by mamunga** [saltstack/salt#40556]
### Description of Issue/Question
We have a release pipeline for some application modules which are generating RPMs for each build.
We would like to automatically upgrade to the newest release in the same RPM version, for example:
Base version: 1.1.0.SNAPSHOT
Currently installed: 1.1.0.SNAPSHOT-40
Latest version: 1.1.0.SNAPSHOT-43

We would like salt to always install the latest package with a "1.1.0.SNAPSHOT" version string, but the current version comparison logic denies this.

We had a workaround for the issue: yum does exactly what we want - if we append the base version string to the package name (package-name-1.1.0.SNAPSHOT) instead of using the version parameter, 
yum recognizes that there is an update for the currenlty installed package and updates it.

This, however, is problematic, because the salt state is marked as "failed" (the provided package name is not found in the installed packages).

My question is, is there a "correct" way to achieve the functionality we want, or we have to use a workaround/implement it ourselves?

I feel this logic should go to pkg.latest, but it does not support a base version as far as I know, and we have multiple base versions to support (so a simple latest without version checking would not be enough). Besides, it would have the same problem as pkg.installed if we put the version string in the package name.

### Setup
The used state file:
```
Install package-name:
  pkg.installed:
    - name: package-name
    - version: 1.1.0.SNAPSHOT
    - target: /opt/package_name
    - hold: True
    - update_holds: True
    - ignore_epoch: true
```
Proof, that there is an available update
```
[root@host01 ~]# yum info package-name
Installed Packages
Name        : package-name
Arch        : noarch
Version     : 1.0.10.SNAPSHOT
Release     : 40
Size        : 204 M
Repo        : installed
From repo   : my-repo
Summary     : no description given
URL         : http://nourlgiven.example.com/
Licence     : unknown
Description : no description given

Available Packages
Name        : package-name
Arch        : noarch
Version     : 1.0.10.SNAPSHOT
Release     : 43
Size        : 91 M
Repo        : my-repo
Summary     : no description given
URL         : http://nourlgiven.example.com/
Licence     : unknown
Description : no description given
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep  5 2016, 02:30:38)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: oracle 7.3 
        machine: x86_64
        release: 4.1.12-61.1.19.el7uek.x86_64
         system: Linux
        version: Oracle Linux Server 7.3
```

**Comment by damon-atkins** [comment]
Try execution module pkg.install() with reinstall=True    Sounds like you don't care about the state.

```
Install package-name:
  module.run:
    - name: pkg.install
    - m_name: package-name
    - reinstall: True
    - version: 1.1.0.SNAPSHOT
    - target: /opt/package_name
    - hold: True
    - update_holds: True
    - ignore_epoch: true
    - etc
```

**Comment by Ch3LL** [comment]
@mamunga does @damon-atkins solution work for you?

**Comment by TewWe** [comment]
Thanks @damon-atkins for the idea, we have managed (I work with @mamunga) to get it done with the following config:

```
install-package-name:
  module.run:
    - name: pkg.install
    - m_name: package-name
    - version: 1.1.0.SNAPSHOT
    - target: /opt/package_name
    - update_holds: True
    - ignore_epoch: True
    - refresh: True

install-package-name-hold:
  module.run:
    - name: pkg.hold
    - m_name: package-name
    - require:
      - module: install-package-name
```

- `module.run + pkg.install` won't use the problematic version check, that `pkg.installed` does, so it will try to install the new version with yum
- we have to specify a `pkg.hold` state separately, to achieve the hold functionality, as `pkg.install `does not have it as a parameter
- `reinstall: True` is only reinstalls the currently installed package, won't upgrade
