### ISSUE TITLE
startup_states highstate wont run with gitfs

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#40580]
### Description of Issue/Question
I have a kickstart file for Centos7 that will setup master and minion, and preseed keys.
I've setup the minion with `startup_states` to run highstate on first boot. 

The problem is that hightstate doesn't run, saying `No Top file or external nodes data matches found.`

If I login and run `salt-call state.apply`, everything works as expected.

### Setup
Kickstart installs all necessary salt bits, setups salt configs, enables services and reboots.

/etc/salt/minion

```yaml
master: 127.0.0.1
startup_states: highstate
```

/etc/salt/master

```yaml
fileserver_backend:
  - git

gitfs_remotes:
  - git@example.com:ABC/abc.git:
    - base: master
    - root: salt_files/salt
    - privkey: /etc/salt/git_deploy_key
    - pubkey: /etc/salt/git_deploy_key.pub
  - git@example.com:ZXC/zxc.git::
    - base: master
    - root: salt
    - privkey: /etc/salt/git_deploy_key
    - pubkey: /etc/salt/git_deploy_key.pub

ext_pillar:
  - git:
    - master git@example.com:ABC/abc.git::
      - env: base
      - root: salt_files/pillar
      - privkey: /etc/salt/git_deploy_key
      - pubkey: /etc/salt/git_deploy_key.pub
```

### Steps to Reproduce Issue
`[salt.state       ][ERROR   ][2955] No contents found in top file. Please verify that the 'file_roots' specified in 'etc/master' are accessible: {}
`

### Versions Report
```
salt-call --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.4
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
```
