### ISSUE TITLE
Slack Engine specific users with specific commands

### ISSUE THREAD

**Issue by nomeelnoj** [saltstack/salt#40593]
Currently the slack engine allows for valid_users and valid_commands, which is a list of users who can all run the list of commands.

It would be great if there were a way to make it so that certain users could only run certain commands.  Maybe something like:

```      
      valid_users:
        - johnsmith
        - jane
      valid_commands:
        - test.ping
        - list_jobs
        - cmd.run
      command_restrictions:
          johnsmith:
              - test.ping
          jane:
              - list_jobs
              - cmd.run
```

This way it would allow, say, help desk to run a test.ping, but more dev-type employees to have more control.
