### ISSUE TITLE
[Feature] support gpg verification of state file.managed

### ISSUE THREAD

**Issue by Artanicus** [saltstack/salt#40596]
### Description of Issue/Question
Some publishers provide .asc PGP signature files for releases, even substituting that for releasing hashes. Similar to source_hash there could be an option source_signature for similarly verifying the managed file. Alternatively source_hash could be extended to recognize pgp signatures.

### Setup
Example state:
```
/usr/bin/borg:
  file.managed
    - source: https://github.com/borgbackup/borg/releases/download/1.0.10/borg-linux64
    - source_signature: https://github.com/borgbackup/borg/releases/download/1.0.10/borg-linux64.asc
```

**Comment by gtmanfred** [comment]
This would be awesome to have.  If you wanted to take a shot at implementing it, we would greatly appreciate a pull request.

Thanks for the feature request.
Daniel

**Comment by Artanicus** [comment]
I'll definately attempt implementing this. Any preference for creating a new source_signature or extending source_hash to support signatures?

**Comment by Artanicus** [comment]
Making some notes for myself what needs to be done:
  * the more I think about this it makes sense to implement as a new variable source_signature instead of extending source_hash
  * modules/gpg has basic support for file verify but only for embedded type signatures
    * task 1 is thus: add support to modules/gpg.verify for passing the signature file which is supported by python-gnupg
    * when modules/gpg.verify supports detached signatures it should be fairly easy to use that in a new parameter for file.managed
    * It's still a bit unclear to me if embedded signatures even apply to this use-case, need to find examples to test against.
  * reading RFC 48880 it seems detached keys are expected as separate files, still need to research if it even makes sense to accept one as a string instead of a URI. Even if accepting as string it would be very messy since it's a forced multiline format.

At current an example state would look something like this:
```
/usr/bin/borg:
  file.managed:
    - source: https://github.com/borgbackup/borg/releases/download/1.0.10/borg-linux64
    - source_signature: https://github.com/borgbackup/borg/releases/download/1.0.10/borg-linux64.asc
    - mode: 755
    - require:
      - gpg: borg-public

python-gnupg:
  pkg.installed

borg-public:
  gpg.present:
    - name: 6D5B EF9A DD20 7580 5747 B70F 9F88 FB52 FAF7 B393
    - require:
      - pkg: python-gnupg 
```
