### ISSUE TITLE
[salt-ssh] Pillar data empty when using archive.download state

### ISSUE THREAD

**Issue by dzolnierz** [saltstack/salt#40604]
### Description of Issue/Question

Pillar data is empty if one of previous states was archive.extracted.

### Setup
Here is my SLS files:

*  salt/test/init.sls
```
create-dir:
  file.directory:
    - name: /tmp/tmp.IQjcWDrRkT

download-binary:
  archive.extracted:
    - name: /tmp/tmp.IQjcWDrRkT
    - source: https://github.com/dzolnierz/mkchroot/raw/master/example/mysql-5.1.73-r1-gentoo-glibc-2.19-r1.tgz
    - source_hash: sha1=670e0fbb919c6bd142c7c2cabdc97fe23b1c16a8
    - archive_format: tar 
    - options: v

dump-pillar:
  file.managed:
    - name: /tmp/test
    - source: salt://test/files/test.j2
    - template: jinja
```

* salt/test/files/test.j2

```
{% from "test/map.jinja" import test with context %}

Test is: {{ test|pprint }}
```

* salt/test/map.jinja

```
{% set test = salt['grains.filter_by']({
  'Debian': {
  },
}, merge=salt['pillar.get']('test:lookup')) %}
```

* pillar/test.sls

```
test:
  lookup:
    foo: bar
```

### Steps to Reproduce Issue

When I run states over SSH:

```
salt-ssh '*' state.sls test
```
it produces /tmp/test file with contents:

```
Test is: {}
```

The same SLS running with salt cmd:

```
Test is: {'foo': 'bar'}
```

When I tried to output all variables present in the current Jinja context with ssh transport, I've found out that 'pillar' dict is empty:

```
(...)
'pillar': {}, 'source': u'salt://test/files/test.j2', 'range': <type 'xrange'>, 'dict': <function <lambda> at 0x7fb003d03500>,
```

Moving download-binary after dump-pillar causes 'pillar' dict filled with defined data as I'd expected:

```
(...)
'pillar': {u'test': {u'lookup': {u'foo': u'bar'}}}, 'source': u'salt://test/files/test.j2'
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.7
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: 0.6.7
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 4.4.49-1-pve
         system: Linux
        version: debian 8.7
```
