### ISSUE TITLE
Pkgrepo.managed always returns a change during test=True when multiple GPG keys are configured

### ISSUE THREAD

**Issue by pgporada** [saltstack/salt#40612]
### Description of Issue/Question
When testing a state that uses the pkgrepo.managed function, a test=True will always return that the file is changing even though no change happens. Additionally, the modified timestamp on the server will change with every state apply, but the contents and sha256sum of the file DO NOT change.

```
$ salt 'testbox' state.apply my_atomic_repository test=True

  Name: /etc/pki/rpm-gpg/RPM-GPG-KEY-art - Function: file.managed - Result: Clean Started: - 19:07:09.703184 Duration: 29.09 ms
  Name: /etc/pki/rpm-gpg/RPM-GPG-KEY-atomicorp - Function: file.managed - Result: Clean Started: - 19:07:09.732422 Duration: 18.464 ms
----------
          ID: atomic-repo-7
    Function: pkgrepo.managed
        Name: atomic
      Result: None
     Comment: Package repo 'atomic' will be configured. This may cause pkg states to behave differently than stated if this action is repeated without test=True, due to the differences in the configured repositories.
     Started: 19:07:09.798220
    Duration: 377.757 ms
     Changes:   

```

You can see an example of multiple GPG keys in use over at http://projects.theforeman.org/issues/11966 too.

### Setup
```
atomic-repo-{{ grains['osmajorrelease'] }}:
  pkgrepo.managed:
    - name: atomic
    - humanname: "Atomic Linux Repository"
    - baseurl: {{ yum_repo }}/atomic-{{ grains['osmajorrelease'] }}/
    - gpgkey: |
        file:///etc/pki/rpm-gpg/RPM-GPG-KEY-art
               file:///etc/pki/rpm-gpg/RPM-GPG-KEY-atomicorp
    - gpgcheck: 1
    - enabled: 1
```

### Steps to Reproduce Issue
```
salt 'testbox' state.apply my_atomic_repository
salt 'testbox' state.apply my_atomic_repository test=True
```

### Versions Report
```Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core```
