### ISSUE TITLE
Issue - grains.append

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40624]
### Description of Issue/Question

Hi,

I tried grains.append in 2 ways, states and modules,

As module,
```
@***:/srv/salt# salt aws-sumeet grains.append package mongodb
aws-sumeet:
----------
package:
  - mongodb
```
Which seems to be working fine.

As State,

I have put the following in my state,
```
update_grains:
  grains.append:
    - name: package
    - value: mongodb
    - convert: True
```
Which give the following output,
```
ID: update_grains
Function: grains.append
Name: package
Result: False
Comment: Grain package does not exist
Started: 10:52:13.677000
Duration: 3.0 ms
Changes:
```
Which is not working. Am i missing something here?

I do have the grain defined :)
