### ISSUE TITLE
Alternative fails on real path changement

### ISSUE THREAD

**Issue by porunov** [saltstack/salt#40622]
### Description of Issue/Question

Hello,

I try to change a real path of an alternative but it shows:
`Alternative for my-link not installed:`

### Setup

1) Create next folders:
```
mkdir -p /tmp/alt/a1
mkdir -p /tmp/alt/a2
mkdir -p /tmp/alt/r1
mkdir -p /tmp/alt/r2
```

2) Here is the initial state to execute:
```
my-link:
  alternatives.install:
    - link: /tmp/alt/a1
    - path: /tmp/alt/r1
    - priority: 30

```

3) After state is successfully executed, change the above state to the next:
```
 my-link:
  alternatives.install:
    - link: /tmp/alt/a1
    - path: /tmp/alt/r2
    - priority: 30

```

4) Execute a state (`salt '*' state.apply`) and you will get an error.

### Steps to Reproduce Issue

An error:
```
          ID: my-link
    Function: alternatives.install
      Result: False
     Comment: Alternative for my-link not installed:
     Started: 11:11:30.943652
    Duration: 19.804 ms
     Changes:
```

Minion log:
```

017-04-11 11:11:30,943 [salt.state       ][INFO    ][12406] Running state [my-link] at time 11:11:30.943652
2017-04-11 11:11:30,943 [salt.state       ][INFO    ][12406] Executing state alternatives.install for my-link
2017-04-11 11:11:30,954 [salt.loaded.int.module.cmdmod][INFO    ][12406] Executing command ['alternatives', '--install', '/tmp/alt/a1', 'my-link', '/tmp/alt/r2', '30'] in directory '/root'
2017-04-11 11:11:30,963 [salt.state       ][ERROR   ][12406] Alternative for my-link not installed: 
2017-04-11 11:11:30,963 [salt.state       ][INFO    ][12406] Completed state [my-link] at time 11:11:30.963456 duration_in_ms=19.804
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.7
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.6
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
So, this is working as expected in this case? because /tmp/alt/a1 and /tmp/alt/a2 are not symlinks to /etc/alternatives/my-link.

To test this, the way it should be setup.

```
rm -rf /tmp/alt
mkdir -p /tmp/alt/r1
mkdir -p /tmp/alt/r2
```

Then use the following states.

test.sls
```
my-link:
  alternatives.install:
    - link: /tmp/alt/a1
    - path: /tmp/alt/r1
    - priority: 30
```

test2.sls (this one needs a different priority, you cannot overload priority)
```
 my-link:
  alternatives.install:
    - link: /tmp/alt/a1
    - path: /tmp/alt/r2
    - priority: 31
```

Once this is done, you will see that /tmp/alt/a1 has been created and symlinked to /etc/alternatives/my-link, and that /etc/alternatives/my-link is symlinked /tmp/alt/r1

But in alternatives --display my-link, it will list all installed alternatives and the different priorities.

```
[root@0a23e7322b9c /]# ls -l /tmp/alt/
total 8
lrwxrwxrwx 1 root root   25 Apr 11 16:27 a1 -> /etc/alternatives/my-link
drwxr-xr-x 2 root root 4096 Apr 11 16:25 r1
drwxr-xr-x 2 root root 4096 Apr 11 16:25 r2
[root@0a23e7322b9c /]# ls -ld /etc/alternatives/my-link
lrwxrwxrwx 1 root root 11 Apr 11 16:27 /etc/alternatives/my-link -> /tmp/alt/r1
[root@0a23e7322b9c /]# alternatives --display my-link
my-link - status is manual.
 link currently points to /tmp/alt/r1
/tmp/alt/r1 - priority 30
/tmp/alt/r2 - priority 31
Current `best' version is /tmp/alt/r2.
[root@0a23e7322b9c /]# alternatives --auto my-link
[root@0a23e7322b9c /]# ls -ld /etc/alternatives/my-link
lrwxrwxrwx 1 root root 11 Apr 11 16:31 /etc/alternatives/my-link -> /tmp/alt/r2
```

Thanks,
Daniel

**Comment by porunov** [comment]
@gtmanfred thank you for your explanation!

Just to make sure, I noticed that some saltstack formulas (`zookeeper`, `hadoop`, `sun-java`) uses the next technique to link default directory of some program to the installed version of the program:
```
someprogram-home-link:
  alternatives.install:
    - link: {{ someprogram.alt_home }}
    - path: {{ someprogram.real_home }}
    - priority: 30
```

But really none of the formula works when we update the version of the program. For example, if we update `zookeeper` from 3.4.9 to 3.4.10 the alternative state will fail (because priority is the same).

Do we need to change this state in all those formulas or I miss something?

Regards,
Alexandr
