### ISSUE TITLE
pkg.installed latest version doesn't work for pkg attributes

### ISSUE THREAD

**Issue by ferringb** [saltstack/salt#40652]
### Description of Issue/Question
While pkg.installed honors version=latest when a single package is given via name, it does not honor it for the pkgs list attribute.

### Setup
Given the following state:
```
base:
  pkg.installed:
    pkgs:
      - atop
      - bash: latest
```

This results in- at least for debian systems tested- a dpkg invocation of bash=latest, which isn't correct.

### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt-call 2016.3.5 (Boron)

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this, although I had to edit your state since its not a list, which might have just happened during copy/paste to issue.

Here is my state ( i also added a atop version)

```
root@64a012717875:/# cat /srv/salt/test.sls 
base:
  pkg.installed:
    - pkgs:
      - atop: 1.26-2
      - bash: latest
```

And I get this error:

```
local:
----------
          ID: base
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - E: Version 'latest' for 'bash' was not found
     Started: 16:03:08.229033
    Duration: 17429.265 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  17.429 s
```

Here is a docker container to quickly replicate this issue:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:40652 salt-call --local state.sls test -ldebug` (where /home/ch3ll/git/salt is a local cloned git repo of salt)
