### ISSUE TITLE
State tomcat.war_deployed regression when WAR filename contains version

### ISSUE THREAD

**Issue by sebw** [saltstack/salt#40658]
It seems a regression has been introduced between at least 2016.3.6 and 2016.11.3 regarding WAR versions.

This is the state:

```
  xwiki_deploy:
    tomcat.war_deployed:
      - name: /xwiki
      - war: /tmp/temp-xwiki-9.2.war
      - force: False
```
Result under 2016.3.6:

```
----------
          ID: xwiki_deploy
    Function: tomcat.war_deployed
        Name: /xwiki
      Result: True
     Comment: {'fullname': 'xwiki##9.2', 'version': '9.2', 'mode': 'running', 'sessions': '0'}
     Started: 17:51:30.715550
    Duration: 47460.72 ms
     Changes:   
              ----------
              deploy:
                  deployed /xwiki in version 9.2
```

Result under 2016.11.1:

```
----------
          ID: xwiki_deploy
    Function: tomcat.war_deployed
        Name: /xwiki
      Result: True
     Comment: {'fullname': 'xwiki', 'version': '', 'mode': 'running', 'sessions': '0'}
     Started: 17:36:02.918658
    Duration: 59976.604 ms
     Changes:   
              ----------
              deploy:
                  deployed /xwiki with version 9.2
              undeploy:
                  undeployed /xwiki with no version
```

@jfindlay it looks like you have been working on this state, could you try to reproduce?
