### ISSUE TITLE
Error when running 'salt <id> net.connected' or any other command

### ISSUE THREAD

**Issue by lcabdalla** [saltstack/salt#40676]
### Description of Issue/Question

When running `sudo r1 net.connected` I get the following error:

```
cisco@cisco:/etc/salt$ sudo salt r1 net.connected
r1:
    Minion did not return. [No response]
```

### Setup

r1.sls under /etc/salt/pillar:

```
cisco@cisco:/etc/salt/pillar$ cat r1.sls
proxy:
  proxytype: napalm
  driver: ios
  host: 123.123.123.11
  username: cisco
  passwd: cisco
```

top.sls under /etc/salt/pillar:

```
cisco@cisco:/etc/salt/pillar$ cat top.sls
base:
  r1:
    - r1
```

master config:

```
file_roots:
  base:
    - /etc/salt/pillar
    - /etc/salt/states
    - /etc/salt/reactors
    - /etc/salt/templates
    - /etc/salt/extmods

pillar_roots:
  base:
    - /etc/salt/pillar
```

proxy config:

```
cisco@cisco:/etc/salt$ cat proxy
master: localhost
pki_dir: /etc/salt/pki/proxy
cachedir: /var/cache/salt/proxy
multiprocessing: False
mine_enabled: True
```

### Steps to Reproduce Issue
The pillar was wrong and after correction it works when starting the process directly (with debug option on), while through systemctl it doesn't.

With `sudo salt-proxy --proxyid r1 -l debug`:

```
cisco@cisco:/etc/salt$ sudo salt r1 net.connected
r1:
    ----------
    out:
        True
```

With `sudo systemctl start salt-proxy@r1`:

```
cisco@cisco:/etc/salt$ sudo salt r1 net.connected
r1:
    Minion did not return. [No response]
```

### Versions Report
```
cisco@cisco:/etc/salt$ salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-72-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```
