### ISSUE TITLE
 boto_vpc.route_table_present always reporting changes

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#40670]
### Description of Issue/Question
boto_vpc.route_table_present is always reporting changes.  The state output shows the old and new are the same.

### Setup
```
aws_vpc_vpcProdEast_create_routing_table_publicB:
  boto_vpc.route_table_present:
    - name: publicB-vpcProdEast
    - vpc_name: vpcProdEast
    - profile: {'region': 'us-east-2', 'keyid': 'XXXXXXXXXX', 'key': 'XXXXXXXXXXXXXXXXXXX'}
    - routes:
      - destination_cidr_block: '0.0.0.0/0'
        internet_gateway_name: 'internet_gateway-vpcProdEast'
      - instance_id: 'i-xxxxxxxxxxxxxxxxxxxx'
        destination_cidr_block: '10.10.0.0/16'
      - instance_id: 'i-xxxxxxxxxxxxxxxxxxxx'
        destination_cidr_block: '172.16.0.0/16'
      - instance_id: 'i-xxxxxxxxxxxxxxxxxxxx'
        destination_cidr_block: '192.168.3.0/24'
      - instance_id: 'i-xxxxxxxxxxxxxxxxxxx'
        destination_cidr_block: '10.40.0.0/16'
    - subnet_names:
      - subGatewayB-vpcProdEast
      - subWebB-vpcProdEast
```

### Steps to Reproduce Issue
Running the state multiple times always returns the same results.

```
east-salt-api-prod-1a:
----------
          ID: aws_vpc_vpcProdEast_create_routing_table_publicB
    Function: boto_vpc.route_table_present
        Name: publicB-vpcProdEast
      Result: True
     Comment: Route table publicB-vpcProdEast (rtb-94399bfd) present. Created route 10.40.0.0/16 in route table publicB-vpcProdEast.
     Started: 21:40:08.714282
    Duration: 1167.243 ms
     Changes:
              ----------
              new:
                  ----------
                  routes:
                      |_
                        ----------
                        destination_cidr_block:
                            192.168.3.0/24
                        interface_id:
                            eni-XXXXXX
                      |_
                        ----------
                        destination_cidr_block:
                            172.16.0.0/16
                        interface_id:
                            eni-XXXXXX
                      |_
                        ----------
                        destination_cidr_block:
                            10.10.0.0/16
                        interface_id:
                            eni-XXXXXX
                      |_
                        ----------
                        destination_cidr_block:
                            10.30.0.0/16
                        gateway_id:
                            local
                      |_
                        ----------
                        destination_cidr_block:
                            10.40.0.0/16
                        interface_id:
                            eni-XXXXXX
                      |_
                        ----------
                        destination_cidr_block:
                            0.0.0.0/0
                        gateway_id:
                            igw-XXXXXX
              old:
                  ----------
                  routes:
                      |_
                        ----------
                        destination_cidr_block:
                            192.168.3.0/24
                        interface_id:
                            eni-XXXXXX
                      |_
                        ----------
                        destination_cidr_block:
                            172.16.0.0/16
                        interface_id:
                            eni-XXXXXX
                      |_
                        ----------
                        destination_cidr_block:
                            10.10.0.0/16
                        interface_id:
                            eni-XXXXXX
                      |_
                        ----------
                        destination_cidr_block:
                            10.30.0.0/16
                        gateway_id:
                            local
                      |_
                        ----------
                        destination_cidr_block:
                            10.40.0.0/16
                        interface_id:
                            eni-XXXXXX
                      |_
                        ----------
                        destination_cidr_block:
                            0.0.0.0/0
                        gateway_id:
                            igw-XXXXXX
Summary for east-salt-api-prod-1a
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.167 s
```

### Versions Report
master
```
# salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
And the minion
```
# salt-minion --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
