### ISSUE TITLE
salt.states.sysctl.present not working for net.ipv4.route.flush

### ISSUE THREAD

**Issue by leonkatz** [saltstack/salt#40709]
```
route_flush:
  sysctl.present:
    - name: net.ipv4.route.flush
    - value: 1
```
Does not work because it is not stored but used to flush cache, Probably need a state to handle send the sysctl request without checking if its already present.

```
    Function: sysctl.present
        Name: net.ipv4.route.flush
      Result: False
     Comment: Failed to set net.ipv4.route.flush to 1: sysctl net.ipv4.route.flush does not exist
     Started: 01:22:20.666190
    Duration: 16.61 ms
     Changes:

```
