### ISSUE TITLE
States should support file.set_selinux_context for ease of use

### ISSUE THREAD

**Issue by pgporada** [saltstack/salt#40703]
It would be incredibly nice to be able to do something like this very similarly to the module file.set_selinux_context except in a state file. How would one get started writing/testing this? 

```
set /etc/yum.repos.d/epel.repo selinux context:
  file.set_selinux_context:
    - path: /etc/yum.repos.d/epel.repo
    - user: system_u
    - role: object_r
    - type: system_conf_t
    - range: s0
```

The module is used as follows
```
salt '*' file.set_selinux_context /etc/yum.repos.d/epel.repo system_u object_r system_conf_t s0
```

Right now my code is littered with snippets like this and is a burden to maintain. I would like my state declared once and not have to rely on independent module calls or the following
```
set /etc/yum.repos.d/epel.repo user context:
  cmd.run:
    - name: 'chcon -u system_u /etc/yum.repos.d/epel.repo'
    - unless: 'stat -c %C {{ conf.path }} | grep system_u'

set /etc/yum.repos.d/epel.repo role context:
  cmd.run:
    - name: 'chcon -r object_r /etc/yum.repos.d/epel.repo'
    - unless: 'stat -c %C {{ conf.path }} | grep object_r'

set /etc/yum.repos.d/epel.repo type context:
  cmd.run:
    - name: 'chcon -t system_conf_t /etc/yum.repos.d/epel.repo'
    - unless: 'stat -c %C {{ conf.path }} | grep system_conf_t'

set /etc/yum.repos.d/epel.repo level context:
  cmd.run:
    - name: 'chcon -l s0 /etc/yum.repos.d/epel.repo'
    - unless: 'stat -c %C {{ conf.path }} | grep s0'
```

Not to toot it's horn so to speak, but Ansible has a nice interface with their file and template modules. It allow you to set the selinux context when creating the file in the first place.
```
- name: set /etc/yum.repos.d/epel.repo selinux context
  file:
    path: /etc/yum.repos.d/epel.repo
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: system_conf_t
    selevel: s0

- name: copy in some template to /etc/yum.repos.d/epel.repo
  copy:
    source: etc/yum.repos.d/epel.repo.j2
    dest: /etc/yum.repos.d/epel.repo
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: system_conf_t
    selevel: s0
```

I wish that Salt had the same capabilities because the Ansible version was really user friendly to me and helped bake in security during server development.

This is a duplicate from a comment in a 5 year old ticket at https://github.com/saltstack/salt/issues/1349

**Comment by gtmanfred** [comment]
This is a duplicate of https://github.com/saltstack/salt/issues/1349 , so I am going to mark this as a duplicate and a question.

If I was going to do this, what I would do is to add a dictionary block to the file.managed state, which just included the user, the role, type and level.

so

```
/etc/yum.repos.d/epel.repo:
  file.managed:
    - source: salt://epel.repo
    - user: root
    - group: root
    - mode: 0644
    - selinux:
      user: system_u
      role: object_r
      type: system_conf_t
      level: s0
```

You should take a look at `salt/states/file.py`, if you want to tackle this, this is where you would add your code.

Thanks,
Daniel
