### ISSUE TITLE
Always run expanduser on paths

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#40710]
### Description of Issue/Question

Currently the `file.*` states seems to be consistent in always running paths through `os.path.expanduser` to enable managing files like `~{{ user }}/.bashrc` and the likes, but I just noticed that f. ex `git.latest` does not to the same thing, which means I have to resort to not-that-elegant `salt['user.info'](user)['home']`. I'm assuming the git state is not the only offender, is there any hope to have expanduser applied consistently to paths across salt?

### Setup
```yaml
# testexpand.sls
{% set user = 'vagrant' %}
test:
    file.managed:
        - name: ~{{ user }}/test
        - contents: foo

    git.latest:
        name: https://github.com/pyenv/pyenv
        target: ~{{ user }}/.pyenv
```
Both of these should succeed.

### Steps to Reproduce Issue
`sudo salt-call state.sls testexpand`

### Versions Report
All versions.
