### ISSUE TITLE
TypeError when removing a group on Windows

### ISSUE THREAD

**Issue by mtkennerly** [saltstack/salt#40711]
### Description of Issue/Question
I'm trying to use the group.absent state on a Windows Server 2012 R2 VM, and I'm getting a TypeError when it tries to output the results. I did notice that [the documentation for the group state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.group.html) specifically mentions Unix, but the group is still successfully removed, and the salt/modules/win_groupadd.py module makes it seem like this ought to work on Windows. It seems like it's just a problem in the results output.

```
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\output\__init__.py", line 38, in try_printout
    printout = get_printout(out, opts)(data, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\output\highstate.py", line 146, in output
    for host, hostdata in six.iteritems(data)
  File "C:\salt\bin\lib\site-packages\salt\output\highstate.py", line 208, in _format_host
    rcounts.setdefault(ret['result'], 0)
TypeError: unhashable type: 'dict'
```

### Setup / Steps to Reproduce Issue
[See this gist](https://gist.github.com/mtkennerly/a5d823b9c742cee30cfc332b685ce138) for state files, highstate log, and a Vagrantfile. Given this file structure:

* Vagrantfile
* salt_srv/
  * minion
  * salt/
    * top.sls
    * demo.sls

Then do:

* `vagrant up` (I'm using Vagrant 1.9.2)
* Manually download and install Salt-Minion-2016.11.3-x86-Setup.exe (since Vagrant currently has a bug and can't install it through the Salt plugin).
* Go to Computer Management and create a "foo" group with no members. Adding members still leads to the same behavior.
* Run `salt-call state.highstate --log-level debug`.

If you run highstate again, it will work fine since the group is already absent.

### Versions Report
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
