### ISSUE TITLE
npm.installed: Can't install from master with error: Error looking up 'state-name'

### ISSUE THREAD

**Issue by gabriel-sevecek** [saltstack/salt#40787]
### Description of Issue/Question
Running 2016.11.3 salt on freebsd11@p9 (both master and minion), I have a sls file containing this:
```
node.packages:
  pkg.installed:
    - pkgs:
      - node
      - npm

npm-global-packages:
  npm.installed:
    - pkgs:
      - pm2
```

Calling `salt -t 1200 node2 state.apply` returns error for npm-global-packages state:

```
          ID: npm-global-packages
    Function: npm.installed
      Result: False
     Comment: Error looking up 'npm-global-packages':  1: node::Abort(void) [/usr/local/bin/node]
               2: node::PlatformInit(void) [/usr/local/bin/node]
               3: node::Start(int, char**) [/usr/local/bin/node]
               4: _start [/usr/local/bin/node]
     Started: 11:48:07.729821
    Duration: 280.086 ms
     Changes:
```

However, calling `salt-call -l debug state.apply` on node2 minion installs pm2 just fine:

```
          ID: npm-global-packages
    Function: npm.installed
      Result: True
     Comment: Package(s) 'pm2' successfully installed
     Started: 11:54:54.579151
    Duration: 12784.979 ms
     Changes:
              ----------
              new:
                  - pm2
              old:
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 12 2017, 01:19:30)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 11.0-RELEASE-p1
         system: FreeBSD
        version: Not Installed
```
