### ISSUE TITLE
timezone.get_offset fails on AIX

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#40831]
### Description of Issue/Question
`timezone.get_offset` fails on AIX

### Steps to Reproduce Issue
Running `salt '*' timezone.get_offset` gives:
```
salt '*' timezone.get_offset
AIX:
    date in salt binaries does not exist: /opt/salt/bin/date
```

### Versions Report
```
Salt Version:
               Salt: 2016.11.4
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: 3.2.3
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.5
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.5 (default, Apr 20 2017, 13:11:32)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: Not Installed
            timelib: 0.2.4
            Tornado: 4.2.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
            machine: 00F62A684C00
            release: 1
             system: AIX
            version: Not Installed
```
