### ISSUE TITLE
file.managed change file but there is nothing to change

### ISSUE THREAD

**Issue by colttt** [saltstack/salt#40873]
### Description of Issue/Question
regarding to this post: https://groups.google.com/forum/#!topic/salt-users/UsJ9ZPo-w8c , I create a bug report here.
I would like to manage my sources.list, that works fine, but he said he changed everytime something, but in real nothing changed, here is the output 
```
----------
          ID: sources_file
    Function: file.managed
        Name: /etc/apt/sources.list
      Result: True
     Comment: File /etc/apt/sources.list updated
     Started: 11:18:24.595244
    Duration: 77.02 ms
     Changes:   
              ----------                                                                                                                                                                                                                                                                                                     
              diff:
                  --- 
                  +++ 
                  @@ -1,7 +1,7 @@
                   
                  -deb http://debian-repo.example.org/debian/ jessie main contrib non-free
                  +deb http://debian-repo.example.org/debian/ jessie main contrib non-free      
                   deb http://debian-repo.example.org/debian/ jessie-updates main contrib non-free
                   deb http://debian-repo.example.org/debian/ jessie-backports main contrib non-free
                  -deb http://debian-repo.example.org/security/ jessie/updates main contrib non-free
                  +deb http://debian-repo.example.org/security/ jessie/updates main contrib non-free      
                   
                   
----------
```

### Setup
my sources_list/init.sls
```
sources_file:
  file.managed:
    - name: /etc/apt/sources.list
    - source: salt://linux/sources_list/sources
    - template: jinja
    - user: root
    - group: root

{% if grains['os'] == 'Debian' %}
saltstack.repo:
  pkgrepo.managed:
    - name: deb http://repo.saltstack.com/apt/{{ salt['grains.get']('os')|lower }}/{{ salt['grains.get']('osmajorrelease')}}/amd64/2016.11 {{ salt['grains.get']('oscodename') }} main
    - file: /etc/apt/sources.list.d/staltstack.list
    - key_url: https://repo.saltstack.com/apt/{{ salt['grains.get']('os')|lower }}/{{ salt['grains.get']('osmajorrelease')}}/amd64/latest/SALTSTACK-GPG-KEY.pub
    - dist: {{ grains['oscodename']|lower }}
    - failhard: true

{% elif grains['os'] == 'Ubuntu' %}
saltstack.repo:
  pkgrepo.managed:
    - name: deb http://repo.saltstack.com/apt/{{ salt['grains.get']('os')|lower }}/{{ salt['grains.get']('osrelease')}}/amd64/2016.11 {{ salt['grains.get']('oscodename') }} main
    - file: /etc/apt/sources.list.d/staltstack.list
    - key_url: https://repo.saltstack.com/apt/{{ salt['grains.get']('os')|lower }}/{{ salt['grains.get']('osrelease')}}/amd64/latest/SALTSTACK-GPG-KEY.pub
    - dist: {{ grains['oscodename']|lower }}
    - failhard: true
{% endif %}

apt-update:
  cmd.run:
    - name: apt-get update >/dev/null
    - onlyif:
      - pkg: saltstack_repo
      - pkg: sources_file
```
my sources file:
```
{% if grains['os'] == 'Debian' %}
deb http://debian-repo.example.org/{{ salt['grains.get']('os')|lower }}/ {{ salt['grains.get']('oscodename') }} main contrib non-free      
deb http://debian-repo.example.org/{{ salt['grains.get']('os')|lower }}/ {{ salt['grains.get']('oscodename') }}-updates main contrib non-free
deb http://debian-repo.example.org/{{ salt['grains.get']('os')|lower }}/ {{ salt['grains.get']('oscodename') }}-backports main contrib non-free
deb http://debian-repo.example.org/security/ {{ salt['grains.get']('oscodename') }}/updates main contrib non-free 
```

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7

**Comment by gtmanfred** [comment]
First off, you cannot use onlyif like this

```
apt-update:
  cmd.run:
    - name: apt-get update >/dev/null
    - onlyif:
      - pkg: saltstack_repo
      - pkg: sources_file
```

Onlyif is supposed to be a list of commands to run on the commandline.  What you want is [onchanges]()

Now for the actual issue, can you provide me with the full sources file because it looks like you are missing at least the `{%- endif %}`

It might also be worth trying to remove the newline at the top of the file by using `{%-` as the opening for the if statement.

```
root@salt:~# salt-call state.apply test
local:
----------
          ID: sources_file
    Function: file.managed
        Name: /etc/apt/sources.list
      Result: True
     Comment: File /etc/apt/sources.list updated
     Started: 16:12:43.196600
    Duration: 21.13 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,6 +1,5 @@
                  -deb http://deb.debian.org/debian/ jessie main
                  -deb-src http://deb.debian.org/debian/ jessie main
                  -deb http://security.debian.org/ jessie/updates main
                  -deb-src http://security.debian.org/ jessie/updates main
                  -deb http://deb.debian.org/debian/ jessie-updates main
                  -deb-src http://deb.debian.org/debian/ jessie-updates main
                  +
                  +deb http://debian-repo.example.org/debian/ jessie main contrib non-free
                  +deb http://debian-repo.example.org/debian/ jessie-updates main contrib non-free
                  +deb http://debian-repo.example.org/debian/ jessie-backports main contrib non-free
                  +deb http://debian-repo.example.org/security/ jessie/updates main contrib non-free
----------
          ID: saltstack.repo
    Function: pkgrepo.managed
        Name: deb http://repo.saltstack.com/apt/debian/8/amd64/2016.11 jessie main
      Result: True
     Comment: Package repo 'deb http://repo.saltstack.com/apt/debian/8/amd64/2016.11 jessie main' already configured
     Started: 16:12:43.230701
    Duration: 34.401 ms
     Changes:
----------
          ID: apt-update
    Function: cmd.run
        Name: apt-get update >/dev/null
      Result: True
     Comment: onlyif execution failed: OrderedDict([('pkg', 'saltstack_repo')])
     Started: 16:12:43.265813
    Duration: 9.249 ms
     Changes:

Summary for local
------------
Succeeded: 3 (changed=1)
Failed:    0
------------
Total states run:     3
Total run time:  64.780 ms
root@salt:~# salt-call state.apply test
local:
----------
          ID: sources_file
    Function: file.managed
        Name: /etc/apt/sources.list
      Result: True
     Comment: File /etc/apt/sources.list is in the correct state
     Started: 16:12:47.041434
    Duration: 19.288 ms
     Changes:
----------
          ID: saltstack.repo
    Function: pkgrepo.managed
        Name: deb http://repo.saltstack.com/apt/debian/8/amd64/2016.11 jessie main
      Result: True
     Comment: Package repo 'deb http://repo.saltstack.com/apt/debian/8/amd64/2016.11 jessie main' already configured
     Started: 16:12:47.073488
    Duration: 35.655 ms
     Changes:
----------
          ID: apt-update
    Function: cmd.run
        Name: apt-get update >/dev/null
      Result: True
     Comment: onlyif execution failed: OrderedDict([('pkg', 'saltstack_repo')])
     Started: 16:12:47.109882
    Duration: 8.318 ms
     Changes:

Summary for local
------------
Succeeded: 3
Failed:    0
------------
Total states run:     3
Total run time:  63.261 ms
```

I am unable to reproduce the issue using what has been provided.

Thanks,
Daniel
