### ISSUE TITLE
2016.11 SoftLayer salt-cloud driver connects on private IP instead of public IP

### ISSUE THREAD

**Issue by stamak** [saltstack/salt#40881]
### Description of Issue/Question

We migrated from 2015.8 to 2016.11 and found an backward incompatible problem
caused by this condition https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/softlayer.py#L403

With 2015.8 we did not use **public_vlan** parameter at all but 2016.11 *requires* it.
So we have a lot of nodes in different locations and collecting all public vlan ids across all location is time consuming and as for me useless because softlayer itself does not require it!

Workaround for now - remove public_vlan from condition.

### Setup
provider
```
#SoftLayer
sl:
  user: SLXXXXX
  apikey: ertrskjdfsldkfsdnf,smdf,.smdf.,smd.,fms.,dmfksjdlkflsdm
  driver: softlayer
```

profile
```
sl-CENTOS_7_64-dal09-2core-4096MB-RAM-100GB-DISK:
  provider: sl
  image: CENTOS_7_64 #CentOS 7 64bit
  cpu_number: 2
  ram: 4096
  disk_size: 100
  location: dal09
  local_disk: True
  hourly_billing: True
  domain: example.com
  max_net_speed: 1000
```

### Steps to Reproduce Issue
```
sudo salt-cloud -p sl-CENTOS_7_64-dal09-2core-4096MB-RAM-100GB-DISK stats-sl-test.example.com
```

Logs
```
[DEBUG   ] Retrying connection to host 10.98.19.9 on port 22 (try 11)
[DEBUG   ] Caught exception in wait_for_port: [Errno 101] Network is unreachable
[DEBUG   ] Retrying connection to host 10.98.19.9 on port 22 (try 12)
```

### Versions Report
```
[smakar@NEWsaltmaster:2 stas]$ salt-cloud --versions-report
Salt Version:
            Salt: 2016.11.3

Dependency Versions:
 Apache Libcloud: 0.20.1
            cffi: 1.10.0
        cherrypy: 4.0.0
        dateutil: 2.6.0
           gitdb: 0.6.4
       gitpython: 1.0.1
           ioflo: Not Installed
          Jinja2: 2.9.6
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.8
    mysql-python: 1.2.3
       pycparser: 2.17
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.3.0
            RAET: Not Installed
           smmap: 0.9.0
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4

System Versions:
            dist: centos 7.2.1511 Core
         machine: x86_64
         release: 3.10.0-327.28.3.el7.x86_64
          system: Linux
         version: CentOS Linux 7.2.1511 Core
```
