### ISSUE TITLE
Can't use parameters in salt states beacon

### ISSUE THREAD

**Issue by wq9** [saltstack/salt#40883]
### Description of Issue/Question
The salt.beacons.service has parameters such as `onchangeonly` and it cannot be set using `salt.states.beacon.present`.

### Setup
Putting 
```
beacons:
  service:
    mysql:
      onchangeonly: True
    ssh:
      onchangeonly: True
```
in `/etc/salt/minion.d/beacons.conf` directly works.

Hovewever, when using `beacons.sls`
```
service:
  beacon.present:
    - mysql:
      onchangeonly: True
    - ssh:
      onchangeonly: True
```
and running it, I get the following:

```
# salt '*' beacons.list
minion1.local:
    beacons:
      service:
        mysql: null
        onchangeonly: true
        ssh: null
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-24-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
It looks like it needs to be an ordered dictionary all the way down.

This works for me
```
service:
  beacon.present:
    - sshd:
      - onchangeonly: True
```
