### ISSUE TITLE
please make it clear that module.run ignores exit status by default

### ISSUE THREAD

**Issue by shallot** [saltstack/salt#40907]
Hi,

This came up in https://github.com/saltstack/salt/issues/40871#issuecomment-296854212
but is not specifically related to that issue, so I'm splitting it out into its own issue.

In the 2016.11.3 source, apparently there's a bunch of modules that fork external programs but then fail to check their exit status, which means users can get glaring errors in the output without it being properly handled. Non-zero exit status indicating failure is a long-established industry standard; side-stepping that by default without explanation seems like a recipe for a lot of unneeded pain.

The popular module function `cmd.run` seems to be generally in the wrong, as it disposes of the return code variable by default. There is an explicit `ignore_retcode` parameter, but its sane default of False doesn't actually mean retcode isn't ignored.

There should be safeguards / sanity checks wherever is appropriate in order to make sure that failures don't pass undetected. It's possible that it's a good idea to always escalate such errors into exceptions (unless ignore_retcode is True obviously), or perhaps it's sufficient to go through the codebase and just change all the code that fails to pass the return code along to use something other than `cmd.run` (thereby setting a better example for the future but leaving the old API available for the poor people who may have use for it), or something third.

TIA.

**Comment by lorengordon** [comment]
I checked the other issue, but it doesn't demonstrate a problem with `cmd.run` ignoring an exit code. I've never seen `cmd.run` do that. If the cmd exits non-zero, it always fails the state. Can you provide a reproducible state using `cmd.run`?

For `module.run`, yes, this is the (expected) behavior I've always seen as well. `module.run` isn't really stateful, intentionally. It's just a way to run an execution module directly during a state run (without using jinja).

**Comment by gtmanfred** [comment]
As @lorengordon said, the cmd.run state does not ignore retcodes.

The cmd.run module does, but that is why cmd.retcode exists.

As for module.run it is just a way to run modules and if the module runs, then it is considered successful.  It is not meant to be used to be stateful.

I am marking this as Won't Fix for now.

**Comment by damon-atkins** [comment]
Is it worth adding a warning or note to states.module.run i.e. runs it every time state is applied and does/does not report success or failure.

Notice develop doco salt.states.module is a bit odd its missing the index entry for module.run.
https://docs.saltstack.com/en/develop/ref/states/all/salt.states.module.html#execution-of-salt-modules-from-within-states
vs what it should be
https://docs.saltstack.com/en/develop/ref/states/all/salt.states.module.html#salt.states.module.run

**Comment by gtmanfred** [comment]
Yeah we can do that, I am going to re open this as a documentation issue.

Thanks,
Daniel

**Comment by shallot** [comment]
Ah, so you're saying all those cmd.run will croak properly? For example, if modules/apache.py version() runs `apachectl -v` which returns an exit status of 1, it won't be misreported as success?

**Comment by gtmanfred** [comment]
Correct.

https://github.com/saltstack/salt/blob/2016.11/salt/states/cmd.py#L858

**Comment by damon-atkins** [comment]
.

**Comment by jtraub91** [comment]
FYI [module.run](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.module.html#salt.states.module.run) seems to "fail" and work with requisites if the module in question raises an exception or returns `False`.

Consider the following examples demonstrating this

```yaml
run_exception_command:
  module.run:
    - cmd.run:
      - dkjskdjskdj

run_dependent_command:
  cmd.run:
    - name: "echo hello world"
    - require:
      - run_exception_command
```
```yaml
run_return_False_command:
  module.run:
    - config.get:
      - pillar_cache

run_dependent_command:
  cmd.run:
    - name: "echo hello world"
    - require:
      - run_return_False_command
```
```yaml
run_successful_command:
  module.run:
    - test.version

run_dependent_command:
  cmd.run:
    - name: "echo hello world"
    - require:
      - run_successful_command
```
