### ISSUE TITLE
Error destroying VM with salt-cloud on Azure provider

### ISSUE THREAD

**Issue by shengis** [saltstack/salt#40924]
### Description of Issue/Question
I get an error when I destroy a VM previously created with salt-cloud : 
```
root@master:/etc/salt# salt-cloud -d testnode2
The following virtual machines are set to be destroyed:
  azure:
    azurearm:
      testnode2

Proceed? [N/y] y
... proceeding
[ERROR   ] There was an error destroying machines: 'CloudStorageAccount' object has no attribute 'create_block_blob_service'
```

### Setup
provider : 
```
azure:
  driver: azurearm
  master: master
  subscription_id: ***

  tenant: ***
  client_id: ***
  secret: ***
  location: northeurope
  resource_group: myresource-group

  cleanup_disks: True
  cleanup_vhds: True
  cleanup_data_disks: True
  cleanup_interfaces: True
```

profiles : 
```
azure-ubuntu:
  provider: azure
  image: Canonical|UbuntuServer|16.10|latest
  size: Standard_DS2_v2
  location: northeurope
  ssh_username: myuser
  ssh_password: mypassword
  storage_account: myaccount
  resource_group: myresource-group
  network_resource_group: mynetwork-resource-group
  security_group: TestNSG
  network: DefaultVNET
  subnet: DefaultSubnet
  public_ip: True
  script: bootstrap-salt.sh
  script_args: -U
  sync_after_install: grains

azure-test:
  extends: azure-ubuntu
  volumes:
    - {disk_size_gb: 128, name: 'datadisk1'}
  minion:
    grains:
      region: northeurope
      roles: test
```

### Steps to Reproduce Issue
```
root@master:/etc/salt# salt-cloud -p azure-test testnode2
[WARNING ] There's no master defined on the 'testnode2' VM settings.
Warning: Permanently added '52.164.229.84' (ECDSA) to the list of known hosts.
myuser@52.164.229.84's password: [ERROR   ] Failed to start Salt on host testnode2

root@master:/etc/salt# salt-cloud -d testnode2
The following virtual machines are set to be destroyed:
  azure:
    azurearm:
      testnode2

Proceed? [N/y] y
... proceeding
[ERROR   ] There was an error destroying machines: 'CloudStorageAccount' object has no attribute 'create_block_blob_service'
```

### Versions Report

```
root@master:/etc/salt/cloud.providers.d# salt --versions-report
Salt Version:
           Salt: 2017.5.0-76-g7a63e3c
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

```
root@master:/etc/salt/cloud.providers.d# salt-cloud --versions-report
Salt Version:
            Salt: 2017.5.0-76-g7a63e3c
 
Dependency Versions:
 Apache Libcloud: 0.20.0
            cffi: 1.10.0
        cherrypy: Not Installed
        dateutil: 2.6.0
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: 2.17
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.2.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4
 
System Versions:
            dist: Ubuntu 16.04 xenial
         machine: x86_64
         release: 4.4.0-47-generic
          system: Linux
         version: Ubuntu 16.04 xenial
```
