### ISSUE TITLE
When `state_aggregate` is set to `True`, the `latest` keyword doesn't work with pkg.installed

### ISSUE THREAD

**Issue by djhaskin987** [saltstack/salt#40940]
### Steps to Reproduce Issue

On a masterless setup:
1. Set `file_client: local` in `/etc/salt/minion`
2. Set `state_aggregate: True` in `/etc/salt/minion`
3. Put this in `/srv/salt/example.sls`:
   ```
   example:
     pkg.installed:
       - name: mutt
       - version: latest
    ```

4. Running `salt-call --local state.apply example` will try to install the `latest` version of `mutt`; that is, it looks for the literal string `latest` when looking for mutt.

When I added a `log.debug("Package: {0}@{1}")` line at the top of the `installed(` function inside the file `salt/states/pkg.py`, the output I got in the logs was `Package: mutt@None`

Running out of the box on 2016.11.4 .
