### ISSUE TITLE
salt-cloud -d xxx does not clean up saltify instance (or do anything at all)

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#40962]
### The saltify provider for salt-cloud does not remove its settings.

* Attempting to re-use a hardware machine from a different salt-cloud master fails, because the /etc/salt/minion file remains and points to the former master.

* Attempting to clean up after a saltify use fails, because saltify.destroy is not implemented. This gives the very confusing result `No machines were found to be destroyed` when fed an instance that clearly does exist.

#### Feature request:

Implement `salt-call -d xxx` for saltify minions.

It should:
- disable the salt-minion service
- delete -r /etc/salt
- stop the salt-minion service
- remove the key for xxx

##### Query:

Would you consider a pull request if I implement this?

### Setup

The entire system (of which I will send only a clip) is complex.  It will, when complete, build a group of 15 servers (we call it a "bevy") to replicate our backend system for testing.  Some of those machines must run on hardware (they are connected to real-time data feeds.)  The hardware machines will be re-used for later instances of a "bevy". A different salt-cloud master will control the new "bevy".

The bevy master configures itself using salt-call...
```
$ tree /bevy_srv  
/bevy_srv
├── pillar
│   ├── bevy_settings.sls
│   ├── bitbucket_settings.sls
│   ├── common.sls
│   ├── my_user_settings.sls
│   ├── top.sls
│   └── vbox_settings.sls
└── salt
    ├── administrator_user.sls
    ├── bevy_master
    │   ├── cloud.conf
    │   ├── cloud.profiles.d
    │   │   ├── saltify_profiles.conf
    │   │   ├── salt_managed.notice
    │   │   └── virtualbox_profiles.conf
    │   ├── cloud.providers.d
    │   │   ├── saltify_provider.conf
    │   │   ├── salt_managed.notice
    │   │   └── virtualbox_provider.conf
    │   ├── cloud.template
    │   ├── init.sls
    │   ├── master.conf
    │   ├── minion_01.conf
    │   └── README.notice.jinja
    ├── cleanup_vagrant.sls
    ├── clone_my_ssh.sls
    ├── common.sls
    ├── helper_scripts.sls
    ├── interactive_user.sls
    ├── run_command_later.py
    ├── saltmine-dump.jinja
    ├── saltmine-dump.sls
    └── top.sls
```

After self-configuration, and connecting two minions, the bevy master's setup looks like this:
```
/etc/salt
├── cloud
├── cloud.conf.d
│   └── 01_from_bootstrap.conf
├── cloud.profiles.d
│   ├── saltify_profiles.conf
│   ├── salt_managed.notice
│   └── virtualbox_profiles.conf
├── cloud.providers.d
│   ├── saltify_provider.conf
│   ├── salt_managed.notice
│   └── virtualbox_provider.conf
├── master
├── master.d
│   └── 01_from_bootstrap.conf
├── minion
├── minion.d
│   ├── 01_from_bootstrap.conf
│   └── _schedule.conf
├── minion.dpkg-dist
├── pki
│   ├── master
│   │   ├── master.pem
│   │   ├── master.pub
│   │   ├── minions
│   │   │   ├── admindb
│   │   │   ├── bevymaster
│   │   │   └── rabbit
│   │   ├── minions_autosign
│   │   ├── minions_denied
│   │   ├── minions_pre
│   │   └── minions_rejected
│   └── minion
│       ├── minion_master.pub
│       ├── minion.pem
│       └── minion.pub
├── proxy
└── proxy.d
```

The saltify configuration files are a model of simplicity (after the bevy master's IP address is inserted in the provider configuration by salt/jinja.)

```
vernoncole@bevymaster:~$ cat /etc/salt/cloud.providers.d/saltify_provider.conf 
saltify-config-1:  # vagrant private network
  minion:
    master: 10.100.10.4
  driver: saltify

saltify-config-2:  # sling 10 network
  minion:
    master: 10.100.10.4
  driver: saltify
```
```
vernoncole@bevymaster:~$ cat /etc/salt/cloud.profiles.d/saltify_profiles.conf 
# /etc/salt/cloud.profiles.d/saltify.conf

quail1:   # example machine created by "vagrant up quail1"
  ssh_host: 192.168.8.3
  ssh_username: vagrant
  password: vagrant
  provider: saltify-config-1

hpltx2:   # hardware machine
  ssh_host: 10.100.9.41
  ssh_username: vagrant
  password: vagrant
  provider: saltify-config-2
```
[Vagrantfile.zip](https://github.com/saltstack/salt/files/965271/Vagrantfile.zip)

### Steps to Reproduce Issue
```
$ vagrant up bevymaster  # ** NOTE: will use VirtualBox by default **
$ vagrant up quail1
$ vagrant ssh bevymaster
bvm $ sudo salt-cloud -p quail1 rabbit
[...clip...]
bvm $ sudo salt-cloud -p hpltx2 admindb
[...clip...]
Connection to 10.100.9.41 closed.
 *  INFO: Salt installed!
[...clip...]
bvm $ sudo salt-call -d admindb
No machines were found to be destroyed   # ** Really??? I just connected it! **
bvm $ exit
$ vagrant destroy -f bevymaster
$ vagrant destroy -f quail1
$ vagrant up bevymaster --provider=vmware_fusion  # ** NOTE: will be at a different IP **
$ vagrant up quail1 --provider=vmware_fusion
$ vagrant ssh bevymaster
bvm $ sudo salt-cloud -p quail1 rabbit
[...clip...]
bvm $ sudo salt-cloud -p hpltx2 admindb
[...clip...]
Connection to 10.100.9.41 closed.
 *  INFO: Salt installed!
bvm $ sudo salt \* test.ping
bevymaster:
    True
rabbit:
    True
admindb:
    Minion did not return. [No response]
```

### Versions Report

```
vernoncole@bevymaster:/vagrant$ sudo salt \* test.version
rabbit:
    2016.11.4
bevymaster:
    2016.11.4
admindb:
    2016.11.4

vernoncole@bevymaster:/vagrant$ sudo salt \* grains.get osfinger
rabbit:
    Ubuntu-16.04
bevymaster:
    Ubuntu-16.04
admindb:
    Ubuntu-16.04

vernoncole@bevymaster:/vagrant$ sudo salt --versions-report
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-21-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 ```
