### ISSUE TITLE
file_tree templating in develop breaks existing usage

### ISSUE THREAD

**Issue by Shados** [saltstack/salt#40978]
### Description of Issue/Question

In the `develop` branch templating/renderer functionality has been added to the `file_tree` external pillar. Unfortunately, this breaks the existing behaviour, where file contents are just read in to the pillar dict as strings.

Currently, if `render_default` and `renderer_blacklist/whitelist` aren't specified in the master configuration file for the `file_tree`, they're just left as `None` internally. As a result, the `salt.template.compile_template_str` function that is called to template each file thus attempts to pass it through an empty renderer pipeline and just returns an empty dictionary instead of a templated string.

I am not familiar enough with the codebase to know what the preferred change would be to solve the problem... on that note, in the mean-time is there an e.g. 'plaintext' renderer I can specify to get the old behaviour?

### Setup
`/etc/salt/master`:
```
file_roots:
  base:
    - /srv/salt/tree

pillar_roots:
  base:
    - /srv/salt/pillar

ext_pillar:
  - file_tree:
      root_dir: /srv/salt/pillar_file_tree
      follow_dir_links: True
      keep_newline: True
```

### Steps to Reproduce Issue
Have a minion called `test`. Do:
```
mkdir -p /srv/salt/pillar_file_tree/hosts/test/files/
echo "Hello world" > /srv/salt/pillar_file_tree/hosts/test/files/testfile
salt 'test' pillar.data
```

Expected output:
```
test:
    ----------
    files:
        ----------
        testfile:
            Hello world
```

Actual output:
```
test:
    ----------
    files:
        ----------
        testfile:
            ----------
```

### Versions Report
`salt 2017.5.0-85-g8f7e8e4`
