### ISSUE TITLE
smtp.send_msg state oddities

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#40976]
### Description of Issue/Question
smtp.send_msg's profile is kind of useless.

### Setup
```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: 1.6.7
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec 31 2016, 10:50:46)
   python-gnupg: 2.2.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.6
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```

### Steps to Reproduce Issue
```
test:
  smtp.send_msg:
    - profile: smtp-default
    - recipient: "sjorge@example.org"
    - subject: "hello"
    - name: "hello, i'm your friendly local salt minion"
```
Results in

```
local:
----------
          ID: test
    Function: smtp.send_msg
        Name: more text
      Result: False
     Comment: Missing parameter sender for state smtp.send_msg
     Changes:
```

sender is already defined in the smtp profile (minion.d/smtp.conf)
```
smtp-default:
  smtp.sender: salt@example.org
  smtp.server: server.example.org
  smtp.tls: false
```

I would expect the state to try and fill in the blanks from the profile before complaining first.

e.g. ```salt-call smtp.send_msg 'sjorge@example.org' 'hello'  profile='smtp-default'```

Works like that.
