### ISSUE TITLE
Module 'service' is not available on CentOS 7.3.1611

### ISSUE THREAD

**Issue by LaurensBosscher** [saltstack/salt#40983]
### Description of Issue/Question
It seems that the module 'service' is not available for my CentOS 7.3.1611 minion when running with 2015.5.11

### Setup
Vanilla expect for auto-accept, please see /etc/master config in attached file.

### Steps to Reproduce Issue
I've attached a minimal version as a docker-compose file that reproduces the problem, steps to reproduce:
1. Download: [salt-docker_bug_report.zip](https://github.com/saltstack/salt/files/967628/salt-docker_bug_report.zip)
2. Unzip file
3. Run docker-compose up inside the unzipped directory
4. Open a terminal to the master: docker exec -it saltdockerbugreport_master_1 /bin/bash
5. Run:
```
[root@master /]# salt '*' service.available nginx
minion1:
    Module 'service' is not available.
ERROR: Minions returned with non-zero exit code
```

Applying salt states and other modules seems to work, I've stripped those from the attached file but that would be easy to test. 

### Versions Report
```
[root@master /]# salt --versions-report
           Salt: 2015.5.11
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 15.3.0
           RAET: Not Installed
            ZMQ: 4.1.4
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

```

```
salt '*' test.versions_report
minion:
               Salt: 2015.5.11
             Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 15.3.0
               RAET: Not Installed
                ZMQ: 4.1.4
               Mako: Not Installed
            Tornado: Not Installed
            timelib: Not Installed
           dateutil: Not Installed
```

```
[root@master /]# salt '*' grains.get os
minion:
    CentOS

[root@master /]# salt '*' grains.get osrelease
minion:
    7.3.1611
```
