### ISSUE TITLE
State svn always test against latest revision with test=True

### ISSUE THREAD

**Issue by sebw** [saltstack/salt#41022]
Let's say I have this state:
```
hubsession-zope-{{ instance }}-appy:
  svn.latest:
    - name: https://svn.forge.pallavi.be/appy
    - target: /mnt/data/{{ instance }}/lib/python/appy
    - rev: 34
```
If I run the highstate with test=True, it will test against the latest revision available.
