### ISSUE TITLE
Extension modules not available through the salt.cmd runner

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#41024]
### Description of Issue/Question

Using the `salt.cmd` runner, one is able to execute commands that do not depend necessarily on a certain minion, e.g. `http.query` etc.:

```bash
$ sudo salt-run salt.cmd test.ping
True
```

But with an extension module, it doesn't:

```python
$ sudo salt-run salt.cmd transit.ping
Exception occurred in runner salt.cmd: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/salt.py", line 67, in cmd
    utils=utils(__opts__)).get(fun)(*args, **kws)
TypeError: 'NoneType' object is not callable
```
Although the execution module is available:

```bash
$ sudo salt edge01.bjm01 transit.test
edge01.bjm01:
    True
```

(edge01.bjm01 is a proxy minion).

I am running 2016.11.4:

```yaml
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.4
```
