### ISSUE TITLE
salt.states.firewalld does not support modular firewall configurations

### ISSUE THREAD

**Issue by craigafinch** [saltstack/salt#41075]
### Description of Issue/Question

In my experiments, every state declaration that uses the ```salt.states.firewalld``` function will set the global configuration of firewalld, over-writing any configuration created by any previous state declarations. This behavior makes it impossible to write modular states that make atomic modifications to firewalld.

1. Am I misunderstanding ```salt.states.firewalld```? The documentation is very sparse.
2. Is there a workaround, or a completely different way to manage my firewalls in a "atomic" way so that each state can allow the ports/services it needs without affecting ports or services allowed by other states?

### Setup

I have two modular states: one that makes sure that a host is correctly configured for Salt, and another that configures an Icinga2 client for monitoring. These states contain the following declarations:

```
salt-firewall:
  firewalld.present:
    - name: trusted
    - ports:
      - 4505-4506/tcp
```

```
icinga2-firewall:
  firewalld.present:
    - name: trusted
    - ports:
      - 5665/tcp
```

I want to have other modular states that will modify the firewall in an atomic way, such as opening ports 80 and 443 on web servers, without blocking the ports or services managed by other states that are applied to that host.

### Steps to Reproduce Issue

```salt 'myhostname' state.apply```

Expected behavior: when I apply both both states to the same host, firewalld zone "trusted" would have 3 ports opened: 4505, 4506, and 5665. 

Actual behavior: whichever state is applied last over-writes the configuration performed by previous states. As shown below, port 5665 gets closed, and 4505-4506 are open.

```
----------
          ID: salt-firewall
    Function: firewalld.present
        Name: trusted
      Result: True
     Comment: 'trusted' is already in the desired state.
     Started: 16:59:20.658765
    Duration: 3742.542 ms
     Changes:   
----------
          ID: icinga2-firewall
    Function: firewalld.present
        Name: trusted
      Result: True
     Comment: 'trusted' was configured.
     Started: 16:59:24.467702
    Duration: 5436.083 ms
     Changes:   
              ----------
              ports:
                  ----------
                  new:   
                      - 5665/tcp
                  old:   
                      - 4505-4506/tcp
----------
```

```
# firewall-cmd --list-all
trusted (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: 
  ports: 5665/tcp
  protocols: 
  masquerade: yes
  forward-ports: 
  sourceports: 
  icmp-blocks: 
  rich rules:
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
This appears to be a duplicate of #38855

And I agree the firewalld should be documented much better.

There is an option mentioned in the other issue to not prune services, `prune_services: False` but it still prunes ports, so you would need to set every port up to be a service to use this.

**Comment by damon-atkins** [comment]
`prune_services: False` should be the default.   You only need to leave it off once and everything is clobbered.  It works for services not sure about individual ports.

But also is missing is absent
```
block-firewall:
  firewalld.absent:
    - name: trusted
    - services:
      - something
```

**Comment by craigafinch** [comment]
@gtmanfred Thank you for letting me know about the prune_services option; I can use that as a workaround. A related issue is that the output is deceptive when using ```prune_services: False``` Based on this output, it appears that services are being removed, when in fact, the icinga2 service has been added:

```
          ID: icinga2-firewall
    Function: firewalld.present
        Name: trusted
      Result: True
     Comment: 'trusted' was configured.
     Started: 20:21:41.894777
    Duration: 3928.364 ms
     Changes:   
              ----------
              services:
                  ----------
                  new:
                      - icinga2
                  old:
                      - dhcpv6-client
                      - salt
                      - ssh
```

```
# firewall-cmd --list-all
trusted (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: dhcpv6-client icinga2 salt ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  sourceports: 
  icmp-blocks: 
  rich rules: 
```

**Comment by gtmanfred** [comment]
I would love to see this fixed, and also have the whole states behavior cleaned up.  Ever since i actually tried firewalld and gave it a chance I have been using it exclusively.  It makes applying firewall rules in salt significantly easier on linux.

I have tagged this as a feature request for the platform team, but would appreciate any help yall could provide.

Thanks,
Daniel

**Comment by craigafinch** [comment]
@gtmanfred I would really like to see the firewalld state work in a way that mimics the command-line interface of firewall-cmd, which is based on adding and removing ports and services. Here is a use case: If I have a state that enables SSL on a web server, I may want this state to disable port 80 (HTTP) on the web server. It would be great if firewalld.present worked like this:

```
https-firewall:
  firewalld.present:
    - name: public
    - active-zone: public
    - add-services:
      - https
    - remove-services:
      - http
``` 

If I don't list something explicitly in the state (like masquerade) then the state should not affect it. I would prefer not to use the "prune*" terms. I think it would make more sense to have a single option like ```reset-state: True``` that you can use if you want to start from the default configuration for the zone in question and wipe out any previously applied states.

I'm posting this to start a discussion, so please reply with your thoughts!

**Comment by gtmanfred** [comment]
I disagree with that format, because .present signifies what should be
present.

You should use firewalld.absent to remove the http service.

**Comment by craigafinch** [comment]
@gtmanfred I was confused about the term ```.present``` in the function name (I was thinking it referred to firewalld being active and a particular zone being present). If we are thinking of the states that way, then we should add another state to manage zones. Since zones are present but not necessarily active, I don't think the present/absent paradigm really works for zone management.

```
https-firewall:
  firewalld.active:
    - default-zone: public
    - masquerade: True

  firewalld.present:
    - name: public
    - services:
      - https

http-disabled:
  firewalld.absent:
    - name: public
    - services:
      - http
```
