### ISSUE TITLE
environ.setenv is missing from 2016.11.4

### ISSUE THREAD

**Issue by gpkvt** [saltstack/salt#41089]
environ.setenv is unavailable on 2016.11.4. It was working before, but I don't remember which version I was using.

It is an important feature for me, as I'm behind a proxy and I use environment variables to make the proxy settings available for any kind of tools (like git):

```
----------
          ID: set_proxy_https1
    Function: environ.setenv
        Name: HTTPS_PROXY
      Result: False
     Comment: State environ.setenv found in sls oh-my-zsh is unavailable
     Changes:   
----------
          ID: set_proxy_https2
    Function: environ.setenv
        Name: https_proxy
      Result: False
     Comment: State environ.setenv found in sls oh-my-zsh is unavailable
     Changes:   
----------
          ID: debug_proxy
    Function: cmd.run
        Name: export
      Result: True
     Comment: Command "export" run
     Changes:   
              ----------
              pid:
                  5974
              retcode:
                  0
              stderr:
              stdout:
                  export APT_LISTBUGS_FRONTEND='none'
                  export APT_LISTCHANGES_FRONTEND='none'
                  export DEBIAN_FRONTEND='noninteractive'
                  export LANG='C'
                  export LC_ALL='C'
                  export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
                  export PWD='/root'
                  export UCF_FORCE_CONFFOLD='1'
----------
          ID: https://github.com/robbyrussell/oh-my-zsh.git
    Function: git.latest
      Result: False
     Comment: fatal: unable to access 'https://github.com/robbyrussell/oh-my-zsh.git/': Could not resolve host: github.com
     Changes:   
```

In https://github.com/saltstack/salt/issues/13048 someone states that using `cmd.run` is a workaround. That might be true for Windows but isn't for Linux:

```
----------
          ID: set_proxy_https1
    Function: cmd.run
        Name: export HTTPS_PROXY=http://10.0.1.7:3128
      Result: True
     Comment: Command "export HTTPS_PROXY=http://10.0.1.7:3128" run
     Changes:   
              ----------
                  5789
     Changes:                                                                                                                                                                                                                       [25/13819]
----------
          ID: set_proxy_https1
    Function: cmd.run
        Name: export HTTPS_PROXY=http://10.0.1.7:3128
      Result: True
     Comment: Command "export HTTPS_PROXY=http://10.0.1.7:3128" run
     Changes:   
              ----------
              pid:
                  5788
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: set_proxy_https2
    Function: cmd.run
        Name: export https_proxy=http://10.0.1.7:3128
      Result: True
     Comment: Command "export https_proxy=http://10.0.1.7:3128" run
     Changes:   
              ----------
              pid:
                  5789
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: debug_proxy
    Function: cmd.run
        Name: export
      Result: True
     Comment: Command "export" run
     Changes:   
              ----------
              pid:
                  5790
              retcode:
                  0
              stderr:
              stdout:
                  export APT_LISTBUGS_FRONTEND='none'
                  export APT_LISTCHANGES_FRONTEND='none'
                  export DEBIAN_FRONTEND='noninteractive'
                  export LANG='C'
                  export LC_ALL='C'
                  export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
                  export PWD='/root'
                  export UCF_FORCE_CONFFOLD='1'
----------
          ID: https://github.com/robbyrussell/oh-my-zsh.git
    Function: git.latest
      Result: False
     Comment: fatal: unable to access 'https://github.com/robbyrussell/oh-my-zsh.git/': Could not resolve host: github.com
     Changes:   
```

So at the moment all my states are broken when I try to download things, making this a major issue.

**Comment by gtmanfred** [comment]
I am unable to replicate this.  Can you try restarting the minion, and checking that there aren't 2 versions of the minion running?

```
[root@salt salt]# salt-call state.apply test --local
local:
----------
          ID: a_string_env
    Function: environ.setenv
        Name: foo
      Result: True
     Comment: Environ values were set
     Started: 14:52:14.628972
    Duration: 1005.784 ms
     Changes:
              ----------
              foo:
                  bar

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.006 s
```

Also, as another work around, you could use the `git.config_set` to set up the http.proxy configuration in git instead of using environment variables.

If the restart doesn't work, please provide the output of `salt-call` applying that state on the minion.

Thanks,
Daniel

**Comment by jan-gazda** [comment]
I have the same problem:
state
```
environment_variables:
  environ.setenv:
    - name: does_not_matter
    - update_minion: True
    - value:
        CATALINA_OPTS: "-Dcrowd.home={{ crowd.dirs.home }} {{ crowd.catalina_opts }} ${CATALINA_OPTS}"
        CATALINA_PID: {{ crowd.pid }}
```
result
```
          ID: environment_variables
    Function: environ.setenv
        Name: does_not_matter
      Result: True
     Comment: Environ values were set
     Started: 18:22:59.789578
    Duration: 3.416 ms
     Changes:
              ----------
              CATALINA_OPTS:
                  -Dcrowd.home=/opt/crowd/home -Xmx768m ${CATALINA_OPTS}
              CATALINA_PID:
                  /opt/crowd/home/crowd.pid
```

```
root@minion2:/home/vagrant# echo $CATALINA_PID
```
