### ISSUE TITLE
Salt SSH: Specifying a configuration directory in a local Saltfile fails.

### ISSUE THREAD

**Issue by razed11** [saltstack/salt#41080]
### Description of Issue/Question

Specifying a configuration directory in a local Saltfile does not appear to be honored.

### Setup

I have a directory with the following files.

```
./Saltfile
./etc
./etc/salt
./etc/salt/master
./etc/salt/roster
```

Saltfile:

```
salt-ssh:
  config_dir: ./etc/salt # If I rename this to something that doesn't exist I get an error.
```

./etc/salt/master (Deltas from default file):

```
pki_dir: ./etc/salt/pki/master
cachedir: ./etc/salt/cache/salt/master
ssh_log_file: ./var/log/salt/ssh
```

### Steps to Reproduce Issue

```
$ salt-ssh b0d5cc0d894a test.ping
No permissions to access "/var/log/salt/ssh", are you running as the correct user?
```

```
$ salt-ssh b0d5cc0d894a test.ping --log-file ./junk.log
.
.
.
IOError: [Errno 13] Permission denied: '/etc/salt/cache/salt/master/roots/mtime_map'
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: x86_64
        release: 16.5.0
         system: Darwin
        version: 10.12.4 x86_64
```
