### ISSUE TITLE
i386 deb package on amd64 with multiarch not correctly reported

### ISSUE THREAD

**Issue by sash-kan** [saltstack/salt#41096]
same problem (i386 package, amd64 minion) as in #19512:
package with "foreign" architecture is normally installed, but an error is reported.

sls file:

```
packages_for_class_debs:
  pkg.installed:
    - name: s4a:i386
    - sources:
      # from http://s4a.cat/
      - s4a: salt://files/S4A16.deb
    - require:
      - cmd: add_i386_architecture
add_i386_architecture:
  cmd.run:
    - name: dpkg --add-architecture i386 && apt-get update
    - unless: dpkg --print-foreign-architectures | grep -q i386
```
salt-call output (foreign architecture i386 has already been added):

```
$ sudo salt-call --local state.apply
[ERROR   ] Made the following changes:
's4a:i386' changed from 'absent' to '1.6'

local:
----------
          ID: packages_for_class_debs
    Function: pkg.installed
        Name: s4a:i386
      Result: False
     Comment: The following packages failed to install/update: s4a
     Started: 15:29:55.718746
    Duration: 74596.759 ms
     Changes:   
              ----------
              s4a:i386:
                  ----------
                  new:
                      1.6
                  old:

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  74.597 s
```
if i try to remove the architecture from the name (s4a:i386 -> s4a), the error is the same:
```
$ sudo salt-call --local state.apply
[ERROR   ] The following packages failed to install/update: s4a
local:
----------
          ID: packages_for_class_debs
    Function: pkg.installed
        Name: s4a
      Result: False
     Comment: The following packages failed to install/update: s4a
     Started: 15:46:33.506277
    Duration: 79247.147 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  79.247 s
```
versions report:
```
$ sudo salt-call --versions-report  
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
```
