### ISSUE TITLE
Merge/overlay $HOME/.salt/Saltfile and one defined in a local directory.

### ISSUE THREAD

**Issue by razed11** [saltstack/salt#41107]
### Description of Issue/Question

It seems, as of 2016.11.4, that if $HOME/.salt/Saltfile is defined, definitions in a Saltfile in the local directory are ignored.

This is a request for a feature to merge the two in this case. Or at least use any values not yet defined by the HOME version. Or perhaps override. Not sure what the exact behavior should be.

My specific case is I wanted to define the following in $HOME/.salt/Salfile:

```
salt-ssh:
  ssh_priv: ../.ssh/rti.key
```

And have this in the Saltfile from which I am operating:

```
salt-ssh:
  config_dir: ./etc/salt
```
### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report

```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: x86_64
        release: 16.5.0
         system: Darwin
        version: 10.12.4 x86_64
```
