### ISSUE TITLE
FAQ has wrong instructions for upgrading Windows minion.

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#41116]
### Description of Issue/Question
FAQ has wrong instructions for upgrading Windows minion.

In the FAQ it says as follows

> However, it requires more advanced tricks to upgrade from legacy version of Salt (before 2016.3.0), where executing commands in the background is not supported:

```
Restart Salt Minion:
  cmd.run:
{%- if grains['kernel'] == 'Windows' %}
    - name: 'C:\salt\salt-call.bat --local service.restart salt-minion'
{%- else %}
    - name: 'salt-call --local service.restart salt-minion'
{%- endif %}
    - bg: True
    - onchanges:
      - pkg: Upgrade Salt Minion
```
My present understanding is that a windows minion will not require a restart because when the upgrade occurs the old minion will get killed by the installer. Therefore the FAQ should indicated that Windows minions should not be restarted and the suggested Jinja code should look something like:

```
{%- if grains['kernel'] != 'Windows' %}
Restart Salt Minion:
  cmd.run:
    - name: 'salt-call --local service.restart salt-minion'
    - bg: True
    - onchanges:
      - pkg: Upgrade Salt Minion
{%- endif %}
```
