### ISSUE TITLE
service.running returns True if enable=None and init script returns 0

### ISSUE THREAD

**Issue by tmeneau** [saltstack/salt#41125]
### Description of Issue/Question

The `service.running` state will incorrectly indicate success if:

1. the init script returns 0; and
2. the "enable" flag is not specified (None).

Note that in the above situation, [the returned comment indicates Salt is aware the service failed to start](https://github.com/saltstack/salt/commit/c4f899b3b321822f9404e5c0b5d4c411cfd9a03f#diff-51f5a9819bcf2919b421cb7fccd2c42bR391). Please also note that it's possible I'm missing something here, since the associated unit test seems to indicate that this is the expected behavior.

### Steps to Reproduce Issue

Add a `service.running` state for a service who's init script will return 0, and ensure the service fails to start:

```
lsyncd:
  service.running
```

with the following result:

```
----------
          ID: lsyncd
    Function: service.running
      Result: True
     Comment: Service lsyncd failed to start
     Started: 15:55:22.584900
    Duration: 48.378 ms
     Changes:   
```

(I would expect the result to be False)

### Affected Versions

I believe this issue is relevant since [this commit](https://github.com/saltstack/salt/commit/c4f899b3b321822f9404e5c0b5d4c411cfd9a03f#diff-51f5a9819bcf2919b421cb7fccd2c42bR391), and is reproducible in both the current release branch and the develop branch.

_edit: fix formatting of Salt result_
