### ISSUE TITLE
Salt-Cloud fails to bootstrap Windows 2016 on EC2

### ISSUE THREAD

**Issue by rgcosma** [saltstack/salt#41169]
### Description of Issue/Question
VM does boot up, in the correct VPC/Subnet/SecGroup, port 445 is open (I turned the firewall off in the AMI), I can RDP to it using the auto-generated pass, but salt-cloud though gets stuck at
```
[DEBUG   ] Using AWS endpoint: ec2.us-west-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-1.amazonaws.com/?Action=GetPasswordData&InstanceId=i-03e3b91353eda1944&Version=2014-10-01
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] {'instanceId': 'i-03e3b91353eda1944', 'timestamp': '2017-05-10T13:49:22.000Z', 'requestId': 'ceb31e30-68cc-4967-963c-289a489929b5', 'passwordData': None}
```
The 'passwordData': None part is the most obvious difference from other Windows minions. 2008 and 2012r2 work fine, and for them the debug log shows 'passwordData': 'XXX-REDACTED-XXX' then minion installations succeeds.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
base:
  provider: myec2
  size: m4.large
  ebs_optimized: True
  network_interfaces:
    - DeviceIndex: 0
      AssociatePublicIpAddress: False
      SubnetId: subnet-bla
      SecurityGroupId:
        - sg-bla
winwork:
  extends: base
  image: ami-bla
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 64
  win_installer: /srv/misc/Salt-Minion-2016.11.4-AMD64-Setup.exe
  keyname: my-key
  private_key: my-key.pem
  win_username: Administrator
  win_password: auto
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Pick any of the publicly available Windows Server 2016 AMIs
my.map:
```
winwork:
  - bla-www1
  - bla-www2
```
salt-cloud -m my.map

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

Everything installed from the CentOS and Salt repos
