### ISSUE TITLE
Elasticsearch module functions should pass hosts and profile to index_exists()

### ISSUE THREAD

**Issue by onlyanegg** [saltstack/salt#41162]
The Elasticsearch index_delete execution module is broken when passing a profile in through the arguments. It fails with `Exception: Could not connect to Elasticsearch host/ cluster ['127.0.0.1:9200'], is it unhealthy?`. 
The `index_delete()` method calls the `index_exists()` method without passing `hosts` and `profile` causing `_get_instance()` to fail when attempting to ping the ES node.

### Setup
```
delete__index:
   module.run:
     - name: elasticsearch.index_delete
     - index: index_name
     - profile:
         hosts:
           - 'https://{{ user }}:{{ passwd}}@{{ host }}:9243'
```
