### ISSUE TITLE
mocking - 'webutil.user_exists' is not available 

### ISSUE THREAD

**Issue by stamak** [saltstack/salt#41312]
### Steps to Reproduce Issue
I see problem when ‘mocking’ my states
the problem is the following:
state:
```
create_a_new_artifactory_pip_user_{{user}}:
   webutil.user_exists:
    - name: {{user}}
    - password: {{password}}
    - htpasswd_file: {{server.config.passwords.file}}
    - require:
      - pkg: install_{{server.service.name}}_packages
      - pip: install_{{server.package.name}}_pip_packages
      - file: {{server.config.passwords.file}}
    - watch_in:
      - supervisord: pypi-artifactory-server-pypi-artifactory-server-supervisord-conf
```

and result is next

```
ID: create_a_new_artifactory_pip_user_udnuser
    Function: webutil.user_exists
        Name: udnuser
      Result: False
     Comment: State 'webutil.user_exists' was not found in SLS 'artifactory.pip.server.pypi'
              Reason: 'webutil.user_exists' is not available.
     Started: 
    Duration: 
     Changes:  
```

### Versions Report

```
salt --versions-report                                                                     [9/19422]
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 4.0.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
``
