### ISSUE TITLE
Azure provisioning 

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41315]
### Description of Issue/Question
Following is the provider file content,
```
azure-test:
  driver: azurearm
  subscription_id: 
  username: 
  password: 
  location: eastus
  cleanup_disks: True
  cleanup_vhds: True
  cleanup_data_disks: True
  cleanup_interfaces: True
  network_resource_group: 
  slot: staging
  network: 
  resource_group: 
  public_ip: False
  master: 
  ssh_interface: private_ips
```

Following is the profile file content,

```
azure-rhel:
  provider: azure-test
  image: azure-CRI-linux-20170402-72892-os-2017-04-02-6C929262
  size: Standard_D1_v2
  location: eastus
  deploy: true
  ssh_username: 
  ssh_password: 
```
I have kept public_ip: false still it is looking for public ip address
```
[DEBUG   ] {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Network/publicIPAddresses/azure-test5-iface0-ip' under resource group '**********' was not found."}}
[DEBUG   ] The Resource 'Microsoft.Network/publicIPAddresses/azure-test5-iface0-ip' under resource group '**********' was not found.
```

Am i missing some parameter here?

**Comment by gtmanfred** [comment]
@techhat can you take a look at this?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Thanks for the PR to fix this issue.
Daniel

**Comment by sumeetisp** [comment]
I have made the change in the file mentioned in the PR, but then i get the following,
[DEBUG   ] Failed to import utils psutil_compat:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1333, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/utils/psutil_compat.py", line 20, in <module>
    import psutil
ImportError: No module named psutil
[ERROR   ] Failed to import utils saltminionservice, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1333, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/utils/saltminionservice.py", line 34, in <module>
    class MinionService(service(False)):
TypeError: Error when calling the metaclass bases
    cannot create 'NoneType' instances
[DEBUG   ] Failed to import utils vt_helper:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1333, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/utils/vt_helper.py", line 20, in <module>
    from .vt import Terminal, TerminalException
ImportError: No module named vt
[DEBUG   ] Failed to import utils raetlane:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1333, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/utils/raetlane.py", line 62, in <module>
    from raet import raeting, nacling
ImportError: No module named raet
[DEBUG   ] Failed to import utils raetevent:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1333, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/utils/raetevent.py", line 23, in <module>
    from raet import raeting, nacling
ImportError: No module named raet
[DEBUG   ] Could not LazyLoad cloud.filter_event: 'cloud.filter_event' is not available.
[ERROR   ] Failed to create VM azure-test6. Configuration value 'cloud.filter_event' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1291, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1181, in create
    args=__utils__['cloud.filter_event']('creating', vm_, ['name', 'profile', 'provider', 'driver']),
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1087, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 101, in __getitem__
    raise KeyError(key)
KeyError: 'cloud.filter_event'
Error: There was a profile error: Failed to deploy VM

**Comment by sumeetisp** [comment]
Upgraded to 2016.11.5. Still facing public IP error,
[DEBUG   ] {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Network/publicIPAddresses/azure-test6-iface0-ip' under resource group 'CRI-Master' was not found."}}
[DEBUG   ] The Resource 'Microsoft.Network/publicIPAddresses/azure-test6-iface0-ip' under resource group 'CRI-Master' was not found.
[WARNING ] There was a cloud error: Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Network/publicIPAddresses/azure-test6-iface0-ip' under resource group 'CRI-Master' was not found.
[WARNING ] <class 'msrestazure.azure_exceptions.CloudError'>
[ERROR   ] There was a profile error: need more than 1 value to unpack
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1461, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1291, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1117, in create
    'wait_for_ip_interval_multiplier', vm_, __opts__, default=1),
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2376, in wait_for_ip
    data = update_callback(*update_args, **update_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1092, in _query_ip_address
    data = request_instance(kwargs=vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 990, in request_instance
    img_pub, img_off, img_sku, img_ver = vm_['image'].split('|')
ValueError: need more than 1 value to unpack

**Comment by shengis** [comment]
@sumeetisp, you have an error in your profile
```
  image: azure-CRI-linux-20170402-72892-os-2017-04-02-6C929262
```
the image option must have this syntax : `MicrosoftRServer|RServer-Linux|Enterprise|8.0.500003`
you can find a list of images with `salt-cloud --list-images PROVIDER_NAME`

**Comment by sumeetisp** [comment]
Yes I fixed that but still provisioning is not working. It is not able to
find the created resources. Trying to debug, will update

**Comment by sumeetisp** [comment]
[ERROR   ] Failed to create VM azure-cri3. Configuration value 'network_profile' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1291, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1117, in create
    'wait_for_ip_interval_multiplier', vm_, __opts__, default=1),
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2376, in wait_for_ip
    data = update_callback(*update_args, **update_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1093, in _query_ip_address
    ifaces = data['network_profile']['network_interfaces']
KeyError: 'network_profile'
Error: There was a profile error: Failed to deploy VM

**Comment by sumeetisp** [comment]
network_profile is not mentioned in the docs. I have placed the key network_profile in the provider with value same as network and facing above error

**Comment by shengis** [comment]
@sumeetisp in your provider **network:** must contain the name of the existing Virtual Network of your resource group.

here is my provider:
```
azure-us1:
  driver: azurearm
  subscription_id: MY_SUBSCRIPTION_ID

  tenant: MY_TENANT
  client_id: MY_CLIENT_ID
  secret: MY_SECRET_KEY

  location: westus
  resource_group: infra-us1
  network_resource_group: infra-us1
  storage_account: MY_STORAGE_ACCOUNT
  storage_key: MY_STORAGE_KEY

  cleanup_disks: True
  cleanup_vhds: True
  cleanup_data_disks: True
  cleanup_interfaces: True

  minion:
    master: 10.1.1.4
    hash_type: sha256

  grains:
    provider: azure
    region: westus
```
here is my profile:
```
azure-us1:
  provider: azure-us1
  image: Canonical|UbuntuServer|16.04-LTS|latest
  size: Standard_DS2_v2
  ssh_username: MY_SSH_ACCOUNT
  ssh_password: MY_SSH_PASSWORD
  network: infraus1VNET
  subnet: infraus1Subnet
  public_ip: False
  script: bootstrap-salt.sh
  script_args: git v2017.5
  sync_after_install: grains

azure-us1-test:
  extends: azure-us1
  volumes:
    - {disk_size_gb: 128, name: 'datadisk1'}
  minion:
    master: 10.1.1.4
    grains:
      region: westus
      roles: test
```
with salt version git v2017.5
and so, calling `salt-cloud -p azure-us1-test us1-testnode01` is creating the VM us1-testnode01
