### ISSUE TITLE
beacons.state does not save as list

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#41342]
### Description of Issue/Question

The following state file does not produce a working setup.

```
beacon-diskusage:
  beacon.present:
    - name: diskusage
    - interval: 123
    - /: 83%
 ```

The beacon config that gets applied is wrong and the beacon itself fails because a list is expected.

```
minion:
    beacons:
      diskusage:
        /: 83%
        interval: 123
```

It should have been a list.

```
minion:
  beacons:
    diskusage:
      - /: 83%
      - interval: 123
```

### Setup

Latest Saltstack 2016.11.5 on CentOS 7

### Steps to Reproduce Issue

See above

### Versions Report

```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.3.8
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 1.0.1
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: 0.6.3
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
