### ISSUE TITLE
Orchestrate runner needs saltenv on 2016.11.5

### ISSUE THREAD

**Issue by rmarchei** [saltstack/salt#41353]
### Description of Issue/Question

Running states from state.orchestration fails on 2016.11.5 if saltenv is not specified:

`No matching salt environment for environment 'None' found`

Issue seems to be related with https://github.com/saltstack/salt/pull/41036

### Setup
not working `orch/helper.sls`:
```
create_data_snapshot:
  salt.state:
    - tgt: 'repl*'
    - ssh: true
    - sls:
      - helper.data_snapshot
```

Setting `saltenv: base` in each state makes it work again as expected: 
```
create_data_snapshot:
  salt.state:
    - tgt: 'repl*'
    - ssh: true
    - sls:
      - helper.data_snapshot
    - saltenv: base
```
### Steps to Reproduce Issue

run `orch/helper.sls` without setting `saltenv`:
```
# /usr/bin/salt-run state.orchestrate orch.helper
[ERROR   ] Template was specified incorrectly: False
[WARNING ] Output from salt state not highstate
[ERROR   ] Run failed on minions: repl01.xxx.xxx
Failures:
    repl01.xxx.xxx:
        Data failed to compile:
    ----------
        No matching salt environment for environment 'None' found
    ----------
        No matching sls found for 'helper.data_snapshot' in env 'None'
```

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-72-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
