### ISSUE TITLE
file.managed chokes on windows paths when source_hash is set to the URI of a file that contains source hash strings

### ISSUE THREAD

**Issue by lubyou** [saltstack/salt#41365]
### Description of Issue/Question
Hi,

I tried to use file.managed on windows with source_hash pointing to an md5 file on a http server.
The error I am getting is
```

----------
          ID: C:\Program Files (x86)\Common Files\PC SOFT\17.0\Framework\wd170xls.dll
    Function: file.managed
      Result: False
     Comment: Unable to manage file: bogus escape: '\\17'
     Started: 13:21:16.777000
    Duration: 1.0 ms
     Changes:
----------
```

In my case I am hitting https://github.com/saltstack/salt/blob/2016.11/salt/modules/file.py#L4026.
If I replace `file_name.replace('.', r'\.')` with `re.escape(file_name)` things are working as expected.

### Setup
```
# windev.sls

{% set framework_path = 'C:\\Program Files\\Common Files\\PC SOFT\\17.0\\Framework' %}
{% if grains['cpuarch'] ==  'AMD64' %}
{% set framework_path = 'C:\\Program Files (x86)\\Common Files\\PC SOFT\\17.0\\Framework' %}
{% endif %}

{% set framework_dlls = (
  "wd170action.dll",
  "wd170barc.dll",
  "wd170ce.dll",
  "wd170cod.dll",
  "wd170com.dll",
  "wd170cpl.dll",
  "wd170db.dll",
  "wd170device.dll",
  "wd170etat.dll",
  "wd170ggl.dll",
  "wd170gpu.dll",
  "wd170grf.dll",
  "wd170grv.dll",
  "wd170hf.dll",
  "wd170html.dll",
  "wd170img.dll",
  "wd170jav.dll",
  "wd170mat.dll",
  "wd170mdl.dll",
  "wd170mess.dll",
  "wd170net1.dll",
  "wd170net2.dll",
  "wd170net4.dll",
  "wd170nxml.dll",
  "wd170obj.dll",
  "wd170oldb.dll",
  "wd170ole.dll",
  "wd170page.dll",
  "wd170pcl.dll",
  "wd170pdf.dll",
  "wd170pnt.dll",
  "wd170prn.dll",
  "wd170rpl.dll",
  "wd170rtf.dll",
  "wd170sql.dll",
  "wd170sqlite.dll",
  "wd170std.dll",
  "wd170test.dll",
  "wd170trs.dll",
  "wd170uni.dll",
  "wd170vm.dll",
  "wd170xaml.dll",
  "wd170xls.dll",
  "wd170xml.dll",
  "wd170zip.dll")
%}


{% for file in framework_dlls %}
{{framework_path}}\{{file}}:
  file.managed:
    - source: https://repo.someurl.tld/incidents/inc00XXXXX/{{file}}
    - source_hash: https://repo.someurl.tld/incidents/inc00XXXXX/framework.md5
{% endfor %}
```

```
# framework.md5

c753b9d99bfdefcdf0a8eb46467682d3  wd170action.dll
32850ff73aa2a43eb00fc975b12676c3  wd170barc.dll
22295bc2e1c0856aade93096d282935f  wd170ce.dll
8440aa1546010ed7b9114d3f63331c0d  wd170cod.dll
82880cc0bc97f67af2031bc1d1d4a100  wd170com.dll
43ef1e5fecc8157623c1eff4e0fd4b61  wd170cpl.dll
78dfb5209830f31a27f3c45820575158  wd170db.dll
efeb3a1f5a57bdd1de802100b6f5bcf8  wd170device.dll
036029704c564e90c6e1afa898d09201  wd170etat.dll
b835112ee0af5cd6c9df6d2fe9e47d2c  wd170ggl.dll
2076ef3470a9f191532eed3ef59e3973  wd170gpu.dll
0fcf38287f512255fd5b6c67be4967b4  wd170grf.dll
9ee0f913609e6057e6a0c136858fa081  wd170grv.dll
d91a4a98e55adebfe708a73c22397e27  wd170hf.dll
8ac0fd88d76da3a0a878525d16790ebd  wd170html.dll
b9e3365885d1eeb2c396dc2be879023d  wd170img.dll
6b478e0e5724921d60b39e94eb452546  wd170jav.dll
3faa97b7a093295332fc46caf2d96513  wd170mat.dll
d46ab0e82480f031da63aedc9a01c883  wd170mdl.dll
913c251e532dbff6a539a824e8df9513  wd170mess.dll
3984da0e4d4161d003e91e01dc843351  wd170net1.dll
113b007884e052c206808ee014fddbb0  wd170net2.dll
2c1a09e672f65699f4b2d0bc90966272  wd170net4.dll
3d3baaf40354c0bd7228ae3b30a0d362  wd170nxml.dll
2e9c767d1957c42466fb892e816fc6bc  wd170obj.dll
ca540ab9e51ec469693d947fbe93901a  wd170oldb.dll
26b3c68aee1d29904fc65184b2b2b5bb  wd170ole.dll
9ad72162e30e9ab0876387ca5308cd26  wd170page.dll
f92a31a2c0c263f78f9518e000abcb94  wd170pcl.dll
7e2ba7d63f49e8f23f8977b1dee0a836  wd170pdf.dll
56e7cc9b25ca7d3d293e3a648e1f0c55  wd170pnt.dll
b156dfec877d17cc75687db51677f652  wd170prn.dll
642350b14c8bcb75eb69ade218538c05  wd170rpl.dll
d14199836c113a48f40bd72421c6a4e0  wd170rtf.dll
ec9b7a01c789a8ab2829f4f1da98c516  wd170sql.dll
1748b5f78e5db073fee80cb0f441fb45  wd170sqlite.dll
97d4b79d45a70f4695f1049ac24c64f0  wd170std.dll
b2f2a880ea8f5c1c39555d711711d502  wd170test.dll
c202389e8a864fd9cbecd83d1a324d79  wd170trs.dll
ad314d09164827010e1d37cd136f5a73  wd170uni.dll
b28f5430529b067ae3f28f2d0f41a0f0  wd170vm.dll
a46a0f866a826865f420effcc2480eb7  wd170xaml.dll
34e09942335abe81f41fb22b18d2e7f1  wd170xls.dll
69926bfc3acb18f72859159b34ac7bb8  wd170xml.dll
8ebe66207f61b79d6402c3698f502ec8  wd170zip.dll
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```
