### ISSUE TITLE
Schedule job replacing variables but not deleting old

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#41375]
### Description of Issue/Question
```
schedule:
  test_job:
    enabled: true
    function: test.ping
    jid_include: false
    return_job: false
    seconds: 10
```
job added 
```
  test_job: {enabled: true, function: test.ping, jid_include: false, minutes: 60,
    return_job: false, seconds: 10}
```

edit job to

```
schedule:
  test_job:
    enabled: true
    function: test.ping
    jid_include: false
    minutes: 10
```
job added 
```
  test_job: {enabled: true, function: test.ping, jid_include: false, minutes: 60,
    return_job: false, seconds: 10}
```

I dunno if this is the desired behaviour. Imo the new job should replace all variables of the old if it has the same job name. In case this is the desired behaviour I think it should be documented.

### Versions Report
latest version
