### ISSUE TITLE
archive module can't untar some tar files

### ISSUE THREAD

**Issue by sebw** [saltstack/salt#41385]
Module archive.list or state archive.extracted fail to untar some tar.gz files.

Happens on 2016.11.3 to the best of my knowledge.

How to reproduce the problem:

1. download activeMQ package

```
# cd /tmp
# wget https://archive.apache.org/dist/activemq/5.13.2/apache-activemq-5.13.2-bin.tar.gz
```

2. try to list content of archive (xz is installed on the system)

```
# file /tmp/apache-activemq-5.13.2-bin.tar.gz 
/tmp/apache-activemq-5.13.2-bin.tar.gz: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT)

# salt-call archive.list /tmp/apache-activemq-5.13.2-bin.tar.gz 
Error running 'archive.list': Unable to list contents of /tmp/apache-activemq-5.13.2-bin.tar.gz. If this is an XZ-compressed tar archive, install XZ Utils to enable listing its contents. If it is compressed using something other than XZ, it may be necessary to specify CLI options to decompress the archive. See the documentation for details. Additional info follows:

archive location:
    /tmp/apache-activemq-5.13.2-bin.tar.gz
```

3. untar manually and recreate the tar.gz from the command line

```
# tar xvzf /tmp/apache-activemq-5.13.2-bin.tar.gz 
apache-activemq-5.13.2/
apache-activemq-5.13.2/docs/
apache-activemq-5.13.2/data/
[...]

# tar cpzf activemq.tar.gz apache-activemq-5.13.2

# file activemq.tar.gz 
activemq.tar.gz: gzip compressed data, from Unix, last modified: Tue May 23 14:44:24 2017
```

4. Now it works:

```
# salt-call archive.list /tmp/activemq.tar.gz 
local:
    - apache-activemq-5.13.2/
    - apache-activemq-5.13.2/LICENSE
    - apache-activemq-5.13.2/NOTICE
    - apache-activemq-5.13.2/README.txt
    - apache-activemq-5.13.2/activemq-all-5.13.2.jar
```

Discussion initiated here:
https://groups.google.com/forum/#!topic/salt-users/QayX-EzUxKs

**Comment by gtmanfred** [comment]
I have replicated this error with just 

```
activemq_install_files:
  archive.extracted:
    - name: /opt/
    - source: https://archive.apache.org/dist/activemq/5.13.2/apache-activemq-5.13.2-bin.tar.gz
    - source_hash: 970bdf5fcb111161d2d79cbc3a73bd6c701560a8
    - if_missing: /opt/apache-activemq-5.13.2
```

In the logs, it look like it is trying to use `xz` on the archive instead of gunzip.

@terminalmage when you get a chance if you could take a look at this.

Thanks for the report @sebw 

Daniel

**Comment by terminalmage** [comment]
No, it's not. It's using ``xz -l`` to check if the file is xz-compressed, which it does when tarfile fails to read from the archive. This is how we tell whether or not we need to fall back to attempting to use XZ-utils to decompress the archive.

This seems to be either a problem with how the archive was created, or an upstream bug in Python 2.7:

```
[root@418bb4148089 ~]# curl -O https://archive.apache.org/dist/activemq/5.13.2/apache-activemq-5.13.2-bin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 51.1M  100 51.1M    0     0  1940k      0  0:00:27  0:00:27 --:--:-- 2154k
[root@418bb4148089 ~]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tarfile
>>> import contextlib
>>> with contextlib.closing(tarfile.open('apache-activemq-5.13.2-bin.tar.gz')) as tar_archive:
...     print(len([x.name for x in tar_archive.getmembers()]))
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
>>>
```

``tarfile`` is failing to open the archive. There's not much we can do about that, since it's not a Salt bug.

This seems to be a bug in the Python stdlib, since the same exact code works fine for the same archive in Python 3.4:

```
[root@a8e0c78ae84d ~]# python3
Python 3.4.5 (default, Nov  9 2016, 16:24:59)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tarfile
>>> import contextlib
>>>
[root@a8e0c78ae84d ~]# curl -O https://archive.apache.org/dist/activemq/5.13.2/apache-activemq-5.13.2-bin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 51.1M  100 51.1M    0     0  1947k      0  0:00:26  0:00:26 --:--:-- 2135k
[root@a8e0c78ae84d ~]# python3
Python 3.4.5 (default, Nov  9 2016, 16:24:59)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tarfile
>>> import contextlib
>>> with contextlib.closing(tarfile.open('apache-activemq-5.13.2-bin.tar.gz')) as tar_archive:
...     print(len([x.name for x in tar_archive.getmembers()]))
...
749
```

After dropping into a Python debugger, the error comes when trying to get the numeric value of the uid field in one of the file's headers (Line 1208 of tarfile.py in Python 2.7.5). So indeed, this looks like a bug in the stdlib, [issue 24514](https://bugs.python.org/issue24514) to be precise. I tried the same thing on Python 2.7.13 and it works as expected, which is even further evidence that this is the same bug.

**Comment by terminalmage** [comment]
@sebw You should be able to work around this pretty easily, the fix is a one-liner:

```
[root@856525855dec ~]# cat >foo.patch
diff -ur a/Lib/tarfile.py b/Lib/tarfile.py
--- a/Lib/tarfile.py    2013-05-11 22:32:45.000000000 -0500
+++ b/Lib/tarfile.py    2017-05-24 10:48:23.979694656 -0500
@@ -186,7 +186,7 @@
     # itn() below.
     if s[0] != chr(0200):
         try:
-            n = int(nts(s) or "0", 8)
+            n = int(nts(s).strip() or "0", 8)
         except ValueError:
             raise InvalidHeaderError("invalid header")
     else:
[root@856525855dec ~]# patch -d /usr/lib64/python2.7 -Np2 -i /root/foo.patch
patching file tarfile.py
[root@856525855dec ~]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tarfile
>>> import contextlib
>>> with contextlib.closing(tarfile.open('apache-activemq-5.13.2-bin.tar.gz')) as tar_archive:
...     print(len(tar_archive.getmembers()))
...
749
```

**Comment by sebw** [comment]
Thanks for the investigations! I worked around the problem by recreating the tar file from my Linux workstation.

**Comment by terminalmage** [comment]
@sebw ok cool. You can future-proof it by applying the patch in my earlier comment.

**Comment by Skyneo** [comment]
I made simple workaround in my formula:

```
activemq_copy_files:
  file.managed:
    - name: /tmp/{{ activemq_env.activemq_tarball_name }}
    - source: {{ activemq_env.activemq_tarball_source }}
    - onfail:
      - activemq_install_files

activemq_create_dest_dir:
  file.directory:
    - name: {{ activemq_env.activemq_root }}/{{ activemq_env.activemq_version }}
    - require:
      - activemq_copy_files

activemq_extract_files:
  cmd.run:
    - name: tar xzf /tmp/{{ activemq_env.activemq_tarball_name }} -C {{ activemq_env.activemq_root }}/{{ activemq_env.activemq_version }} --strip 1 && rm -f /tmp/{{ activemq_env.activemq_tarball_name }}
    - require:
      - activemq_create_dest_dir
```
Might help someone.

I will test workaround from @terminalmage on my lab enviroment for future projects. 
Thanks
