### ISSUE TITLE
salt.states.npm.installed does not seem to work with `@angular/cli`

### ISSUE THREAD

**Issue by terlar** [saltstack/salt#41396]
### Description of Issue/Question

If I have defined a state that installes the `@angular/cli` it installs but outputs some error and reinstalls every time as it cannot detect it being installed. I am not sure if the issue is quoting or not, because values are not allowed to start with `@` so I have to quote it.

I get the following output:

```
[ERROR   ] ['/usr/bin/ng -> /usr/lib/node_modules/@angular/cli/bin/ng', '{', '  "dependencies": {', '    "@angular/cli": {', '      "version": "1.0.4",', '      "from": "@angular/cli@1.0.4",', '      "resolved": "https://registry.npmjs.org/@angular/cli/-/cli-1.0.4.tgz"', '    }', '  }', '}']
local:
----------
          ID: angular_cli
    Function: npm.installed
        Name: @angular/cli@1.0.4
      Result: True
     Comment: Package(s) '@angular/cli@1.0.4' successfully installed
     Started: 22:38:35.386168
    Duration: 32300.493 ms
     Changes:
              ----------
              new:
                  - @angular/cli@1.0.4
              old:
```

But next time it installs again and acts as if it was not installed.

### Setup

Install through, either of these, result is the same:

```sts
"@angular/cli":
  npm.installed: []
```

```sts
angular_cli:
  npm.installed:
    - name: "@angular/cli"
```

```sts
angular_cli:
  npm.installed:
    - pkgs:
      - "@angular/cli"
```

### Steps to Reproduce Issue

Install through the previous instructions and observe the behaviour mentioned in the first section.

### Versions Report

```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb 11 2017, 12:22:40)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.1

System Versions:
           dist:
        machine: x86_64
        release: 4.11.2-1-ARCH
         system: Linux
        version: Not Installed
```

**Comment by gtmanfred** [comment]
Yup, it looks like this isn't checking the existing package correctly.

Thanks for reporting, if you wanted to submit a PR, we would greatly appreciate it, otherwise I have tagged this as a bug.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Also, I just want to make sure, you are running into this issue on Arch Linux right?

**Comment by terlar** [comment]
Yes, this is on Arch Linux, haven't tried any other dists.

**Comment by amalleo25** [comment]
I see the same issue on ubuntu 16.04.4 lts. The npm package reinstalls each time the state is run.

Version report:
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.3.0
         system: Linux
        version: Ubuntu 16.04 xenial
```

Node version:
```
v10.5.0
```

Salt state:
```
nelson-npm:
  npm.installed:
    - name: "@semkodev/nelson.cli"
    - dir: /usr/local/lib
```

State.apply output:
```
----------
          ID: nelson-npm
    Function: npm.installed
        Name: @semkodev/nelson.cli
      Result: True
     Comment: Package(s) '@semkodev/nelson.cli' successfully installed
     Started: 10:51:02.368299
    Duration: 7524.494 ms
     Changes:   
              ----------
              new:
                  - @semkodev/nelson.cli
              old:
```

Debug output:
```
[DEBUG   ] LazyLoaded npm.installed
[INFO    ] Running state [@semkodev/nelson.cli] at time 10:51:02.368299
[INFO    ] Executing state npm.installed for [@semkodev/nelson.cli]
[INFO    ] Executing command 'npm list --json --silent --depth=0' in directory '/usr/local/lib'
[DEBUG   ] stdout: {
  "dependencies": {
    "@semkodev/nelson.cli": {
      "version": "0.4.5",
      "from": "@semkodev/nelson.cli",
      "resolved": "https://registry.npmjs.org/@semkodev/nelson.cli/-/nelson.cli-0.4.5.tgz"
    },
    "nelson.cli": {
      "version": "0.4.0",
      "from": "nelson.cli",
      "resolved": "https://registry.npmjs.org/nelson.cli/-/nelson.cli-0.4.0.tgz"
    },
    "npm": {
      "version": "6.1.0"
    }
  }
}
[INFO    ] Executing command 'npm install --json --silent @semkodev/nelson.cli' in directory '/usr/local/lib'
[DEBUG   ] stdout: {
  "added": [],
  "removed": [],
  "updated": [
    {
      "action": "update",
      "name": "@semkodev/nelson.cli",
      "version": "0.4.5",
      "path": "/usr/local/lib/node_modules/@semkodev/nelson.cli",
      "previousVersion": "0.4.5"
    }
  ],
  "moved": [],
  "failed": [],
  "warnings": [],
  "elapsed": 5154
}
[INFO    ] {u'new': [u'@semkodev/nelson.cli'], u'old': []}
[INFO    ] Completed state [@semkodev/nelson.cli] at time 10:51:09.892793 (duration_in_ms=7524.494)
```
