### ISSUE TITLE
requisite evaluation affects sorting in ways both state.show_sls and state.apply fail to explain

### ISSUE THREAD

**Issue by shallot** [saltstack/salt#41406]
First of all, https://docs.saltstack.com/en/latest/ref/states/requisites.html#prereq is probably phrased in a manner more complicated than necessary. This is my use case where I thought I needed `prereq`:

I need to stop a running postfix service, move its directories around, leave in a symlink in the original location, and then start the service again. (Seems like a job for a very small shell script, right?) I wanted to do it with states, where one set of states would do the move if necessary, another state would be the prerequisite of those states (killing the service if there's anything to move), and a final state in turn would depend on those states (starting the service again if there was anything moved).

Turns out, `state.show_sls` says things are going to be done in the right order, but `state.apply` fumbles, runs the `service.dead` out of order and consequently breaks it.

This is the state file:

```
% cat salt/states/move-postfix.sls
stop postfix while we mess with its directories:
  service.dead:
    - name: postfix
    - prereq:
      - file: postfix system spool link
      - file: /opt/system/postfix/spool

/opt/system/postfix:
  file.directory:
    - user: root
    - group: root
    - mode: 0755

postfix system spool link:
  cmd.run:
    - name: 'test -e /var/spool/postfix && mv /var/spool/postfix /opt/system/postfix/spool'
    - unless: 'test -L /var/spool/postfix'
    - require:
      - file: /opt/system/postfix
  file.symlink:
    - name: /var/spool/postfix
    - target: /opt/system/postfix/spool
    - require:
      - file: /opt/system/postfix
      - cmd: postfix system spool link

/opt/system/postfix/spool:
  file.directory:
    - user: root
    - group: root
    - mode: 0755
    - require:
      - file: /opt/system/postfix
      - postfix system spool link

reload postfix with new config:
  service.running:
    - name: postfix
    - listen:
      - file: postfix system spool link
      - file: /opt/system/postfix/spool
```

`salt-ssh minion-name state.show_sls move-postfix` says `stop postfix while we mess with its directories` will have order 10000. That seems good, meaning it will evaluate that part first, i.e. test those two prerequisites, and then if any of them announce any changes, execute the service.dead... but on runtime, it explodes like this:

```
minion-name:
----------
          ID: /opt/system/postfix
    Function: file.directory
      Result: True
     Comment: Directory /opt/system/postfix is in the correct state
     Started: 12:27:28.282618
    Duration: 0.56 ms
     Changes:
----------
          ID: postfix system spool link
    Function: cmd.run
        Name: test -e /var/spool/postfix && mv /var/spool/postfix /opt/system/postfix/spool
      Result: True
     Comment: Command "test -e /var/spool/postfix && mv /var/spool/postfix /opt/system/postfix/spool" run
     Started: 12:27:28.283623
    Duration: 10.87 ms
     Changes:
              ----------
              pid:
                  6694
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: stop postfix while we mess with its directories
    Function: service.dead
        Name: postfix
      Result: True
     Comment: The service postfix is already dead
     Started: 12:27:28.296218
    Duration: 28.365 ms
     Changes:
----------
          ID: postfix system spool link
    Function: file.symlink
        Name: /var/spool/postfix
      Result: True
     Comment: Created new symlink /var/spool/postfix -> /opt/system/postfix/spool
     Started: 12:27:28.324792
    Duration: 0.956 ms
     Changes:
              ----------
              new:
                  /var/spool/postfix
----------
          ID: /opt/system/postfix/spool
    Function: file.directory
      Result: True
     Comment: Directory /opt/system/postfix/spool is in the correct state
     Started: 12:27:28.325904
    Duration: 0.499 ms
     Changes:
----------
          ID: reload postfix with new config
    Function: service.running
        Name: postfix
      Result: True
     Comment: The service postfix is already running
     Started: 12:27:28.326485
    Duration: 22.559 ms
     Changes:

Summary for minion-name
------------
Succeeded: 6 (changed=2)
Failed:    0
------------
Total states run:     6
Total run time:  63.809 ms
```

I'm guessing I probably did something wrong but does this really have to be so complicated...

I should mention that originally I did this with more directories, but even with reduced complexity it still fails the same way.

This is with Salt 2016.11.4

Also tried patch by Neighbour @ #salt IRC channel: https://pastebin.com/twBNA2wL ...to no avail.
