### ISSUE TITLE
[Feature request] Batch wait for orchestrate runner

### ISSUE THREAD

**Issue by kamsz** [saltstack/salt#41432]
I'd like to be able to do a batch orchestration with some pause between each batch e.g.:

```
install_web:
    salt.state:
        - tgt: 'roles:web'
        - tgt_type: grain
        - sls: web
        - batch: 1
        - batch_wait: 60
```
