### ISSUE TITLE
cmd.script on windows minion: requires undocumented parameter

### ISSUE THREAD

**Issue by howardjones** [saltstack/salt#41452]
salt 2016.11.4 (Carbon)

While trying to get an MSI to actually install properly (different story, still not working though), I tried to use 'runas' on states.cmd.script and got `Comment: password is a required argument for runas on Windows` as a response. `password` is not mentioned in the states reference at all, let alone as a required argument. 

```
psc1_install:
  cmd.script:
  - template: jinja
  - source: salt://utils/scripts/psc1-install.ps1
  - shell: "powershell"
  - runas: administrator
  - requires:
    - file: psc1_config
```
