### ISSUE TITLE
Salt and Salt-ssh return values when using Rest api

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41454]
### Description of Issue/Question

When i use local client and run grains.items i get the output in the following format,

```
some-name:
    ----------
    SSDs:
        - xvda
    biosreleasedate:
        02/16/2017
    biosversion:
```

But when i use ssh client to run grains.items i get the following output,

```
return:
  -----------
    aws-tags-test:
    ----------
    SSDs:
        - xvda
```

This difference is seen only while using salt resp api. When running from cli the outputs are same for both the clients

**Comment by Ch3LL** [comment]
Looks like I can replicate this:

SSH Client:
`curl -sS http://localhost:8000/run -H 'Accept: application/x-yaml' -d client='ssh' -d tgt='*' -d fun='grains.items' -d username='saltdev' -d password='saltdev' -d eauth='pam'`

```
- test:
    return:
      SSDs: []
      biosreleasedate: 04/01/2014
      biosversion: Ubuntu-1.8.2-1ubuntu2
```

Local Client:
`curl -sS http://localhost:8000/run -H 'Accept: application/x-yaml' -d client='local' -d tgt='*' -d fun='grains.items' -d username='saltdev' -d password='saltdev' -d eauth='pam'`

```
- c6c2e89d6b0b:
    SSDs:
    - sda
    - dm-0
    - dm-1
    - dm-2
    - dm-3
```

@whiteinge is there purpose behind having the different return structure?
