### ISSUE TITLE
Regression in 2016.11.5: augeas.change is broken

### ISSUE THREAD

**Issue by Cybso** [saltstack/salt#41484]
### Description of Issue/Question

augeas.change is broken since 2016.11.5. It fails with "unable to save file".

### Steps to Reproduce Issue

Worked before 2016.11.5:

```
  /etc/default/grub:
      augeas.change:
          - context: /files/etc/default/grub
          - lens: shellvars.lns
          - changes:
              - set GRUB_CMDLINE_LINUX_DEFAULT "console=ttyS0 elevator=noop quiet"
```

Works since 2016.11.5 (but **not** in earlier versions - beware, it fails silently by putting the wrong value into the configuration files):

```
  /etc/default/grub:
      augeas.change:
          - context: /files/etc/default/grub
          - lens: shellvars.lns
          - changes:
              - set GRUB_CMDLINE_LINUX_DEFAULT '"console=ttyS0 elevator=noop quiet"'
```

(note the additional single quotes in the setter's value).

### Versions Report

Salt Version:
```
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.8 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.8 

```
