### ISSUE TITLE
cron.present - No line breaks after comments and SALT_CRON_IDENTIFIER

### ISSUE THREAD

**Issue by hostedvideorn** [saltstack/salt#41508]
### Description of Issue/Question
When using comments on a 'cron.present' state it does not add a line break at the end of the last line of the comment

### Setup
```
test:
    cron.present:
        - identifier: test-01
        - comment: |
            This is line 1 of my comment
            This is line 2 of my comment
            .
        - name: COMMAND_GOES_HERE >/dev/null 2>&1
        - user: root
        - hour: 1
        - minute: 2
```
### Steps to Reproduce Issue
After running the state against a minion this is how it looks. The last comment (just a '.') is at the same line and together with SALT_CRON_IDENTIFIER. There should be a line break after it

    # Lines below here are managed by Salt, do not edit
    # This is line 1 of my comment
    # This is line 2 of my comment
    # . SALT_CRON_IDENTIFIER:test-01
    2 1 * * * COMMAND_GOES_HERE >/dev/null 2>&1

Maybe /usr/lib/python2.6/site-packages/salt/states/cron.py should be edited so a line break is added after the last comment line
(
if comment:
    ret['comment'] = comment
)

### Versions Report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 1.1.2
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
        machine: x86_64
        release: 2.6.32-504.23.4.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
