### ISSUE TITLE
mount.mounted doesn't remount when removing noexec option.

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#41510]
### Description of Issue/Question
When removing the `noexec` option the mount isn't remounted.

### Setup
Create an XFS mount
```
sudo apt-get install xfsprogs
sudo dd if=/dev/zero of=/virtualfs bs=1024 count=30720
sudo losetup /dev/loop0 /virtualfs
sudo mkfs -t xfs /dev/loop0
sudo mkdir /mnt/vfs
```
### Steps to Reproduce Issue
cat /srv/salt/testmount.sls
```
/mnt/vfs:
  mount.mounted:
    - device: /dev/loop0
    - fstype: xfs
    - mkmnt: True
    - opts: defaults,nodev,nosuid,noexec
```
```
salt '<minion id>' state.sls testmount
```
```
[boucha@elsapo ~]$ mount
<-- snip -->
/dev/loop0 on /mnt/vfs type xfs (rw,noexec,nosuid,nodev)
```
Change the sls file to:

```
/mnt/vfs:
  mount.mounted:
    - device: /dev/loop0
    - fstype: xfs
    - mkmnt: True
    - opts: defaults,nodev,nosuid
```
```
salt '<minion id>' state.sls testmount
```
```
[boucha@elsapo ~]$ mount
<-- snip -->
/dev/loop0 on /mnt/vfs type xfs (rw,noexec,nosuid,nodev)
```
The above didn't cause a remount, so let's do that below.
```
sudo umount /mnt/vfs
sudo mount -t xfs /dev/loop0 /mnt/vfs
```
```
[boucha@elsapo ~]$ mount
<-- snip -->
/dev/loop0 on /mnt/vfs type xfs (rw)
```

### Versions Report
```
[boucha@elsapo mnt]$ salt --versions-report
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: 0.3.7
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-119-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
