### ISSUE TITLE
Need guidance in salt cloud provisioning using salt-ssh

### ISSUE THREAD

**Issue by Set4now** [saltstack/salt#41518]
We had client-agent infra, but recently we are trying to move into salt-ssh.
earlier provisioning plan:-
1. while provisioning with map file . we had entries like this.

```
profilename:
   vmname:
      minion: 
        startup_states: sls
        sls_list:
           - app.sls
```

As you see this will create the vm under this profile, install the minion, as soon as the minion starts,app.sls will apply.we had the ssh_user,pass mentioned in cloud providers file.

The same we want to achieve by salt-ssh without installing salt-minion.
will it apply the states without having its entry in salt roster.
