### ISSUE TITLE
winrepo-ng not updating on Minions

### ISSUE THREAD

**Issue by sstodd7532** [saltstack/salt#41511]
### Description of Issue/Question
I was followed the instructions here: https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html cause we were getting `Package salt-minion not found in the repository.` after trying to run `.\salt-call.bat state.apply salt.minion.configure.mine test=false`. Looking in the debug output there does not seem to be anything helpful in there. I will attach the output that I have from `.\salt-call.bat pkg.refresh_db`. 

### Setup
On the salt master, the relevant lines I have are:
file_roots:
base:
- /srv/salt
winrepo_dir_ng: '/srv/salt/win/repo-ng/salt-winrepo-ng'

### Steps to Reproduce Issue
On master:
```
salt-run winrepo.update_git_repos
https://github.com/saltstack/salt-winrepo-ng.git:
    /srv/salt/win/repo-ng - 'https:/github.com/saltstack/salt-winrepo-ng.git'/salt-winrepo-ng
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/salt-winrepo

salt SERVER pkg.refresh_db
```
On Client
```
.\salt-call.bat pkg.refresh_db

```

### Versions Report
On Master:
```
Salt Version:
           Salt: 2016.11.5
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: 0.3.9
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
On Client:
```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
```

[MASTER - salt-run winrepo.update_git_repos -l debug.txt](https://github.com/saltstack/salt/files/1039721/MASTER.-.salt-run.winrepo.update_git_repos.-l.debug.txt)
[MASTER - salt server2 pkg.refresh_db -l debug.txt](https://github.com/saltstack/salt/files/1039723/MASTER.-.salt.server2.pkg.refresh_db.-l.debug.txt)
[CLIENT - salt-call.bat pkg.refresh_db -l debug.txt](https://github.com/saltstack/salt/files/1039722/CLIENT.-.salt-call.bat.pkg.refresh_db.-l.debug.txt)
