### ISSUE TITLE
cmd.run - PowerShell - 'Missing closing brace' parsing issue

### ISSUE THREAD

**Issue by absolutejam** [saltstack/salt#41567]
### Description of Issue/Question

I'm trying to parse the output of a Powershell command as a prerequisite for some other states, by utilising `stateful` and `watch`. (First time using Salt, so please educate me if I'm doing this wrong!).

When running my multi-line, Powershell `cmd.run`, I'm getting the following error from Powershell -  `Missing closing '}' in statement block.`. If I run the command directly in Powershell that's produced from the Salt state, it works just fine (See below).

### Setup

Run `salt 'testvm' state.apply updates.wmf5_1`

`/srv/salt/updates/wmf5_1.sls`
```yaml
Check if WMF 5.1 is installed:
  cmd.run:
    - name: |
          try {
            get-hotfix -id {{ hotfix_id }} -Ea Stop | Out-Null
            return [psobject]@{ 'changed' = $True }
          } catch {
            return
          }
    - shell: powershell
    - stateful: True
```
Output:
```
          ID: Check if WMF 5.1 is installed
    Function: cmd.run
        Name: try {
  get-hotfix -id KB3191564 -Ea Stop | Out-Null
  return [psobject]@{ 'changed' = $True }
} catch {
  return 
}

      Result: True
     Comment: Missing closing '}' in statement block.
                  + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx 
                 ception
                  + FullyQualifiedErrorId : MissingEndCurlyBrace
     Started: 20:24:23.935000
    Duration: 339.0 ms
     Changes:   
```

### Steps to Reproduce Issue

Apply state on test 2012 R2 host.

### Versions Report

Master
```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.8 
        machine: x86_64
        release: 4.4.0-78-generic
         system: Linux
        version: debian 8.8 
```

Minion:
```
Salt Version:
           Salt: 2016.3.6
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free

```
