### ISSUE TITLE
No match in the top.sls yet configured correctly

### ISSUE THREAD

**Issue by jv2222** [saltstack/salt#41570]
### Description of Issue/Question

No match in the top.sls yet it is configured correctly.

### Setup

For some reason salt says there is no match in the top.sls for both pla-stage-web 
and pla-live-web but pla-live-salt works fine (pla-live-salt is the same machine as salt master, so that may be worth noting)

Here is the results of highstating pla-stage-web:

```
root@pla-live-salt:/srv/salt/stage/web# salt 'pla-stage-web' state.highstate
pla-stage-web:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found
     Changes:   

Summary for pla-stage-web
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
```

But, salt Master can talk to minions just fine:

```
root@pla-live-salt:/etc/salt# salt '*' cmd.run 'cat /etc/hostname'
pla-stage-web:
    pla-stage-web
pla-live-web:
    pla-live-web
pla-live-salt:
    pla-live-salt
```

And, Salt Master conf looks good:

```
root@pla-live-salt:/etc/salt# cat /etc/salt/master
user: root
publish_port: 80
ret_port: 443
file_roots:
  base:
    - /srv/salt
pillar_roots:
  base:
    - /var/salt/stack/pillar
hash_type: sha256
log_level: info
```

And, file roots are there:

```
root@pla-live-salt:/etc/salt# ls -l /srv/salt
live  
stage  
states  
top.sls
```

And, top sls has good stuff in it:

```
root@pla-live-salt:/srv/salt# cat top.sls
base:
  pla-live-salt:
    - live.salt-master
  pla-live-web:
    - live.web
  pla-stage-web:
    - stage.web
```

And, highstating  pla-live-salt works fine:

```
root@pla-live-salt:/srv/salt/stage/web# salt 'pla-live-salt' state.highstate
pla-live-salt:
----------
          ID: python-software-properties
    Function: pkg.installed
      Result: True
     Comment: Package python-software-properties is already installed
     Started: 07:12:08.036477
    Duration: 333.213 ms
     Changes:   
    ...etc ....
```

And, pla-stage-web -> stage.web is good:

```
root@pla-live-salt:/srv/salt/stage/web# ls -l
init.sls  
states
```

And, /srv/salt/stage/web/init.sls looks good:

```
root@pla-live-salt:/srv/salt/stage/web# cat init.sls 
include:
  - states.base-machine
  - states.mysql
  - states.mysql.db
  - states.beanstalkd
  - states.nginx
  - states.php5-fpm
  - states.git
  - states.composer
  - states.codebase
  - states.codebase.env
  - states.jobs
  - .states.scripts
```

And, top pillar_roots are there:

```
root@pla-live-salt:/srv/salt# ls /var/salt/stack/pillar
config  top.sls
```

And, top pillar_roots have good stuff in them:

```
root@pla-live-salt:/srv/salt# cat /var/salt/stack/pillar/top.sls
base:
  pla-live-*:
    - order: 1
    - config.live
  pla-stage-*:
    - config.stage

```

And, minions are configured well:

```
root@pla-stage-web:/etc/salt# cat minion
hash_type: sha256
id: pla-stage-web
log_level: info
master: ~redacted~
master_port: 443
user: root
```

And, it's is the same setup I use on a number of other servers/systems.

### Steps to Reproduce Issue

`salt 'pla-stage-web' state.highstate`

### Versions Report

salt master version info:

```
root@pla-live-salt:/srv/salt# salt --versions
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-29-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

salt minion version info:

```
root@pla-stage-web:/etc/salt# salt-call --versions
           Salt: 0.17.5
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
```

Minions grains for pla-stage-web:

```
root@pla-stage-web:/etc/salt# salt-call -g
local:
  biosreleasedate: 02/16/2017
  biosversion: ~redacted~
  cpu_flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm xsaveopt fsgsbase bmi1 avx2 smep bmi2 erms invpcid
  cpu_model: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
  cpuarch: x86_64
  defaultencoding: UTF-8
  defaultlanguage: en_US
  domain: 
  fqdn: pla-stage-web
  fqdn_ip4:
      127.0.0.1
  fqdn_ip6:
  gpus:
      {'model': 'GD 5446', 'vendor': 'unknown'}
  host: pla-stage-web
  id: pla-stage-web
  ip_interfaces: {'lo': ['127.0.0.1'], 'eth0': [~redacted~]}
  ipv4:
      127.0.0.1
      ~redacted~
  ipv6:
      ::1
      ~redacted~
  kernel: Linux
  kernelrelease: 3.13.0-29-generic
  localhost: pla-stage-web
  lsb_distrib_codename: trusty
  lsb_distrib_description: Ubuntu 14.04.5 LTS
  lsb_distrib_id: Ubuntu
  lsb_distrib_release: 14.04
  manufacturer: ~redacted~
  master: ~redacted~
  mem_total: 992
  nodename: pla-stage-web
  num_cpus: 1
  num_gpus: 1
  os: Ubuntu
  os_family: Debian
  osarch: amd64
  oscodename: trusty
  osfinger: Ubuntu-14.04
  osfullname: Ubuntu
  osrelease: 14.04
  path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
  productname: HVM domU
  ps: ps -efHww
  pythonpath:
      /usr/bin
      /usr/lib/python2.7
      /usr/lib/python2.7/plat-x86_64-linux-gnu
      /usr/lib/python2.7/lib-tk
      /usr/lib/python2.7/lib-old
      /usr/lib/python2.7/lib-dynload
      /usr/local/lib/python2.7/dist-packages
      /usr/lib/python2.7/dist-packages
  pythonversion: 2.7.6.final.0
  saltpath: /usr/lib/python2.7/dist-packages/salt
  saltversion: 0.17.5
  saltversioninfo: (0, 17, 5)
  serialnumber: ~redacted~
  server_id: ~redacted~
  shell: /bin/bash
  virtual: xen
  virtual_subtype: Xen PV DomU
```

Anyone got any ideas? Thanks in advance!
