### ISSUE TITLE
Unable to use pkg.installed on Manjaro (Arch) minion

### ISSUE THREAD

**Issue by sazaro** [saltstack/salt#41579]
### Description of Issue/Question
I am trying to run a state.apply to install some packages on a minion running Manjaro Linux (Arch based) but it errors out when I run things that contain pkg.installed in the state.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

 I setup a simple state as an example:
```
tools:
  pkg.installed:
    - pkgs:
      - tmux
      - git
      - vagrant
```
But I receive this error when applying the state

```
vmbox:
----------
          ID: tools
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'pkg.meta.vmbox'
              Reason: 'pkg' __virtual__ returned False
     Changes:   
```
My guess is that since it is being detected a Manjaro and not Arch, it does not know to use pacman. I tried to use this page https://docs.saltstack.com/en/latest/ref/states/providers.html to force it to use pacman but I had no luck.

```
tools:
  pkg.installed:
    - pkgs:
      - tmux
      - git
      - vagrant
  provider: pacman
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb 11 2017, 12:22:40)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.1
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.9.30-1-MANJARO
         system: Linux
        version: Not Installed

```
