### ISSUE TITLE
service will not reload by watching file.recurse

### ISSUE THREAD

**Issue by hiscal2015** [saltstack/salt#41715]
Hi, all

I'm using file.recurse but find service won't reload if I change files in the directory. Here's my code:

saltstack version: 2016.11.1

```
nginx:
  service.running:
    - enable: True
    - reload: True
    - require:
        - pkg: nginx

/etc/nginx/ssl:
  file.recurse:
    {% if 'devops' in grains['role'] %}
    {% if grains['environment'] == 'dev' %}
    - source: salt://appin/files/certs/devserver1
    {% endif %}
    {% if grains['environment'] == 'prod' %}
    - source: salt://appin/files/certs/prdserver1
    {% endif %}
    {% endif %}
    - include_empty: True
    - file_mode: keep
    - watch_in:
        - service: nginx

```

dry-run:
```
----------
          ID: /etc/nginx/ssl
    Function: file.recurse
      Result: None
     Comment: #### /etc/nginx/ssl/dev.server1.demo.com/1_dev.server1.demo.com_bundle.crt ####
              The file /etc/nginx/ssl/dev.server1.demo.com/1_dev.server1.demo.com_bundle.crt is set to be changed
     Started: 16:42:26.434263
    Duration: 20.758 ms
     Changes:   
----------
          ID: nginx
    Function: service.running
      Result: True
     Comment: The service nginx is already running
     Started: 16:42:26.455205
    Duration: 35.429 ms
     Changes:  
```

**Comment by Ch3LL** [comment]
Are you stating the issue is only when you run test=True? Because when I don't pass test=True the state works as expected.

**Comment by hiscal2015** [comment]
@Ch3LL Thank you. It works after removed test=true. But is this the expected behavior that service not showing reload during dry run?

```
----------
          ID: nginx
    Function: service.running
      Result: True
     Comment: Service reloaded
     Started: 09:14:42.077474
    Duration: 74.781 ms
     Changes:   
              ----------
              nginx:
                  True

```
