### ISSUE TITLE
Running salt-ssh for x509.certificate_managed breaks the returned value

### ISSUE THREAD

**Issue by farcaller** [saltstack/salt#41769]
### Description of Issue/Question
If a new certificate/key is generated, openssl (I assume) spams into stderr, breaking the returned JSON.

### Setup
```
{{pki}}/ca.key:
  x509.private_key_managed:
    - bits: 4096
    - backup: true
    - mode: 600
    - require: [file: {{pki}}-dir]

{{pki}}/ca.crt:
  x509.certificate_managed:
    - signing_private_key: {{pki}}/ca.key
    - CN: CA
    - basicConstraints: "critical CA:true"
    - keyUsage: "critical cRLSign, keyCertSign"
    - subjectKeyIdentifier: hash
    - authorityKeyIdentifier: keyid,issuer:always
    - days_valid: 10
    - days_remaining: 10
    - backup: true
    - require:
      - file: {{pki}}
      - x509: {{pki}}/ca.key
```

### Steps to Reproduce Issue
Run the state over salt-ssh

### Versions Report
```
❯ salt --versions-report
Salt Version:
           Salt: 2017.7.0-267-gcc72f1a

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Feb  7 2017, 00:08:15)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.2

System Versions:
           dist:
        machine: x86_64
        release: 16.6.0
         system: Darwin
        version: 10.12.5 x86_64
```

### Failing log

```
[ERROR   ] JSON Render failed for: ..........................................++
...........................................................................................................................................++
{
    "local": {
        "fun_args": [
            "/var/tmp/.root_0615df_salt/salt_state.tgz",
...
```
