### ISSUE TITLE
Failed to apply configuration for the following parameters: network_mode

### ISSUE THREAD

**Issue by gildor7** [saltstack/salt#41765]
### Description of Issue/Question
dockerng.running restarts my images every time (as expected) but fails giving this error:

Failed to apply configuration for the following parameters: network_mode

### Setup
```
{% set appname = pillar['appname'] %}
{% set version = pillar['version'] %}

build_image:
  dockerng.image_present:
    - name: {{ appname }}:{{ version }}
    - build: /data/dockerfile/{{ appname }}

stop_container:
  dockerng.stopped:
    - names:
      - {{ appname }}
    - require:
      - dockerng: build_image

run_app:
  dockerng.running:
    - name: {{ appname }}
    - image: {{ appname }}:{{ version }}
    - port_bindings: 9000:9000
    - require:
      - dockerng: stop_container
```

### Steps to Reproduce Issue
The first run just works fine, but the second run i get the following error:

```
----------
          ID: run_app
    Function: dockerng.running
        Name: rt-auth
      Result: False
     Comment: Container 'application' changed state.. Failed to apply configuration for the following parameters: network_mode.
     Started: 13:49:18.480531
    Duration: 9652.4 ms
     Changes:
              ----------
              added:
                  ----------
                  Id:
                      5a69709cc7e49a961032a58268d25d67d663ffe263f7341a4637a43ee487ae57
                  Name:
                      application
                  Time_Elapsed:
                      0.292793989182
                  Warnings:
                      None
              diff:
                  ----------
              removed:
                  - c9eb5b927976c5d594f46d64a83ee2c38f49672555a37bd846f7f8ee468b710e
              state:
                  ----------
                  new:
                      running
                  old:
                      stopped
```

I added "- network_mode: bridge", but adding it fixed the error label but not start the container.

If i look in the debug log of salt i see the following:

`2017-06-15 13:49:28,130 [salt.state                                           ][ERROR   ][14120] {'diff': {}, 'state': {'new': 'running', 'old': 'stopped'}, 'removed': [u'c9eb5b927976c5d594f46d64a83ee2c38f49672555a37bd846f7f8ee468b710e'], 'added': {'Time_Elapsed': 0.29279398918151855, 'Name': 'application', u'Id': u'5a69709cc7e49a961032a58268d25d67d663ffe263f7341a4637a43ee487ae57', u'Warnings': None}}`

### Versions Report
```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.4.1
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 0.3.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.0.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.9 Santiago
        machine: x86_64
        release: 2.6.32-696.3.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago
```
