### ISSUE TITLE
NPM v5 incompatible with salt.modules.cache_list

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#41770]
### Description of Issue/Question
According to [this](https://github.com/npm/npm/pull/15666#issuecomment-305202975) npm issue `npm cache ls` was removed in v5.0, which means our current `salt.modules.cache_list` does not work in salt and it does not look like there is an alternative to list cache in npm.

If you run the following: `salt-call --local state.single npm.cache_cleaned force=True name=None ` you will see this error:

```
local:
----------
          ID: None
    Function: npm.cache_cleaned
      Result: False
     Comment: Error looking up cached packages: npm ERR! Usage: npm cache add <tarball file>
              npm ERR! npm cache add <folder>
              npm ERR! npm cache add <tarball url>
              npm ERR! npm cache add <git url>
              npm ERR! npm cache add <name>@<version>
              npm ERR! npm cache clean
              npm ERR! npm cache verify
     Started: 10:21:59.763936
    Duration: 3298.134 ms
     Changes:   
```
which is just npm's usage so the command `npm cache ls` does not exist anymore and there is not currently an alternative.

fyi @dschaller

### Versions Report
Found this on MacOSX:

```
jk-el-capitan-base:~ root# salt --versions-report
Salt Version:
           Salt: 2016.11.5-112-g36cb223
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.0
          ioflo: 1.6.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Oct 23 2015, 19:19:21)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: 0.2.4
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: x86_64
        release: 15.6.0
         system: Darwin

```
