### ISSUE TITLE
docker propagates name to hostname, breaking support for named containers with network_mode: host

### ISSUE THREAD

**Issue by farcaller** [saltstack/salt#41781]
### Description of Issue/Question

It's impossible to run a docker container with `network_mode: host` now that hostname is propagated automatically.

### Setup
```
mycontainer:
  docker_container.running:
    - network_mode: host
    ...
```

### Steps to Reproduce Issue

It's not possible to force unset `hostname`, and it makes no sense to unset `name` (not possible either, though): [dockermod.py:L2484](https://github.com/saltstack/salt/blob/develop/salt/modules/dockermod.py#L2484). Salt shouldn't second-guess and apply defaults where none needed and there's no way to revert them.

### Versions Report
```
Salt Version:
           Salt: 2017.7.0-267-gcc72f1a

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Feb  7 2017, 00:08:15)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.2

System Versions:
           dist:
        machine: x86_64
        release: 16.6.0
         system: Darwin
        version: 10.12.5 x86_64
```
