### ISSUE TITLE
develop branch on windows minion fails to fully start. 100% CPU

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#41790]
### Description of Issue/Question
develop branch hits 100% CPU,  2017.7 branch is fine.

### Steps to Reproduce Issue
C:\Salt-Dev>set PYTHONPATH=c:\Salt-Dev\salt;c:\Python27\Lib

C:\Salt-Dev>"c:\Python27\python.exe" -B C:\Salt-Dev\salt\scripts\salt-minion --version
salt-minion 2016.11.0-1436-g9c45fa0 (Carbon)  # Should this not say develop 

C:\Salt-Dev>"c:\Python27\python.exe" -B C:\Salt-Dev\salt\scripts\salt-minion -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: win10test
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 4432
[DEBUG   ] Marking "is_ip" as a jinja filter
[DEBUG   ] Marking "is_ipv4" as a jinja filter
[DEBUG   ] Marking "is_ipv6" as a jinja filter
[DEBUG   ] Marking "ipv4" as a jinja filter
[DEBUG   ] Marking "ipv6" as a jinja filter
[DEBUG   ] Marking "ipaddr" as a jinja filter
[DEBUG   ] Marking "ip_host" as a jinja filter
[DEBUG   ] Marking "network_hosts" as a jinja filter
[DEBUG   ] Marking "network_size" as a jinja filter
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 4432
[DEBUG   ] Configuration file path: c:\salt\conf\minion
Goes 100% CPU Usage, no further output (let it run for an hour)

### Versions Report
```
C:\Salt-Dev>"c:\Python27\python.exe" -B C:\Salt-Dev\salt\scripts\salt-minion --versions-report
Salt Version:
           Salt: 2016.11.0-1436-g9c45fa0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.15063  Multiprocessor Free
```

It could be develop still pulls in win-unicode-console however py3 has the same issue
```
C:\Salt-Dev>more "C:\Salt-Dev\salt\pkg\windows\req_2.txt"
-r req_base.txt
lxml==3.6.0
pypiwin32==219
win-unicode-console==0.5
```
