### ISSUE TITLE
{{salt.pillar.get()}} / {{salt.grains.get()}} shorthand is broken

### ISSUE THREAD

**Issue by farcaller** [saltstack/salt#41794]
### Description of Issue/Question
It's not possible to use `salt.pillar.get('something')` in state file.

### Setup
Add a call to `salt.pillar.get` to sls.

### Steps to Reproduce Issue
Run the state (in here I can only reproducer with salt-ssh so far). The error is

```
Rendering exception occurred: Jinja error: get() takes exactly 3 arguments (2 given)
```

(same for pillar and grains)

`salt['pillar.get']()` works as expected. I was able to workaround the issue with the following renderer prepended to jinja|yaml:

```
def render(data, saltenv='base', sls='', argline='', **kwargs):
  data_str = data.read()
  data_str = (data_str
    .replace('salt.pillar.get(', 'salt["pillar.get"](')
    .replace('salt.grains.get(', 'salt["grains.get"]('))
  return StringIO(data_str)
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.0-267-gcc72f1a

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Feb  7 2017, 00:08:15)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.2

System Versions:
           dist:
        machine: x86_64
        release: 16.6.0
         system: Darwin
        version: 10.12.5 x86_64
```
