### ISSUE TITLE
Seems that skip_verify parameter not detected in pkg.installed

### ISSUE THREAD

**Issue by meons** [saltstack/salt#41799]
### Description of Issue/Question
When I'm trying to install a package with Salt, I get the following error message even if I have set skip_verify param to True in my sls file:

```
----------
          ID: filebeat
    Function: pkg.installed
      Result: False
     Comment: An error was encountered while installing package(s): Zypper command failure: filebeat-5.4.1-1.x86_64 (Elastic 5.x): Signature verification failed [4-Signatures public
key is not available]
              Problem occurred during or after installation or removal of packages:
              Installation aborted by user

              Please see the above error message for a hint.
     Started: 16:18:48.023797
    Duration: 4615.123 ms
     Changes:
----------
```
My sls config:
```yaml
/srv/salt/filebeat/init.sls

filebeat:
  pkg.installed:
    - skip_verify: True
    - version: 5.4.1-1
  file.managed:
    - name: /etc/filebeat/filebeat.yml
    - source: salt://filebeat/filebeat.yml
    - require:
      - pkg: filebeat
  service.running:
    - enable: True
    - watch:
      - file: /etc/filebeat/filebeat.yml
    - require:
      - pkg: filebeat
```
### Steps to Reproduce Issue
Install a package with Salt wihtout GPG key imported on target machine.

### Versions Report
```
Salt Version:
           Salt: 2015.8.12

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.0
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 4.4.59-92.17-default
         system: SUSE Linux Enterprise Server  12 x86_64
```
