### ISSUE TITLE
Salt pkg.installed false error.

### ISSUE THREAD

**Issue by AkhterAli** [saltstack/salt#41819]
### Description of Issue/Question

Salt pkg.installed (on rhel based machine) thinks packages that are already installed is an error.
This **only** occurs in **2016.11.5** and **not** **2016.11.2**

### Setup
```
yum_deps:
  pkg.installed:
    - pkgs:
      - python-setuptools
      - python-pip
```

### Steps to Reproduce Issue
Run the state above twice and you are returned with
```
[INFO    ] Executing command ['yum', '-y', 'install', 'python-pip', 'python-setuptools'] in directory '/root'
[TRACE   ] stdout: Loaded plugins: priorities, update-motd, upgrade-helper
Package python26-pip-6.1.1-1.23.amzn1.noarch already installed and latest version
Package python26-setuptools-12.2-1.32.amzn1.noarch already installed and latest version
Nothing to do
[ERROR   ] The following packages failed to install/update: python-pip, python-setuptools
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Sep  1 2016, 22:14:00)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: x86_64
        release: 4.4.35-33.55.amzn1.x86_64
         system: Linux
        version: Not Installed
```
