### ISSUE TITLE
Discussion: Salt can configure itself using external services

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#41879]
### Description of Issue/Question

We all know that we are able to migrate different entities (pillars, top files, states etc.) into external services. At some point we could end up having our entire environment elsewhere, but with some exceptions: master, minion (and proxy) configuration files.

What if we move them too? Then we could endup having a dummy configuration file, such as:

```/etc/salt/master```
```yaml
master_config_service: mongodb
mongo.host: localhost
mongo.port: 1234
```

And the rest of options (such as ```cachedir```, etc.) can be nicer and easier managed through a GUI etc.

Looking forward to your thoughts :-)
