### ISSUE TITLE
boto_vpc will not work as a required state to uninstalled boto3

### ISSUE THREAD

**Issue by AlecHansen** [saltstack/salt#41909]
### Description of Issue/Question
I'm using the boto_vpc state to set up a peering connection, but the first time I ran a highstate which needed to install boto3, the boto_vpc state failed with the comment
"State 'boto_vpc.request_vpc_peering_conection' was not found in SLS 'rds-vpc-peering'
              Reason: 'boto_vpc' __virtual__ returned False"
Judging from the source code this happens if Boto3 wasn't found when the states are being compiled/made available. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
A state like this should reproduce the issue, make sure Boto3 is uninstalled first with
pip uninstall -y boto3

Even though boto3 installs successfully, the boto_vpc states will all fail. The second time the state is run it will succeed.

```
python-pip:
  pkg.installed

boto3:
  pip.installed:
    - require:
      - pkg: python-pip

request-rds-vpc-peering:
  boto_vpc.request_vpc_peering_connection:
    - require:
      - pip: boto3
    - requester_vpc_id: test
    - peer_vpc_id: test
    - conn_name: test

```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Same version of master and minion. 

Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Linux
