### ISSUE TITLE
Documentation out of sync for `priv` vs `ssh_priv` option in roster

### ISSUE THREAD

**Issue by alexhrescale** [saltstack/salt#41910]
**Assuming documentation is going to change `priv:` to `ssh_priv:` (or, the for `parsers.SaltSSHOptionParser` to use `dest` of `priv` instead of `ssh_priv`), this issue is trivial**, but to help others googling:

### Description of Issue/Question
[SALT ROSTERS](https://docs.saltstack.com/en/latest/topics/ssh/roster.html) documentation page is out of date with respect to version `2016.11.5`, at latest

### Setup
```sh
$ salt-ssh --version
# salt-ssh 2016.11.5 (Carbon)
```

##### Saltfile
```yaml
---
salt-ssh:
  priv: path-to-your-private-key
  roster_file: ./roster-file.yml
  ssh_log_file: ./log/salt/ssh
```

##### roster-file.yml

```yaml
testhost:
  host: ip-to-testhost
  user: user-on-testhost
```

obviously, we assume you have access to `testhost`.

### Steps to Reproduce Issue

```
$ salt-ssh -i '*' test.ping

# WARNING: CONFIG '/etc/salt' directory does not exist.
# salt-ssh could not be run because it could not generate keys.
# 
# You can probably resolve this by executing this script with increased permissions via sudo or by running as root.
# You could also use the '-c' option to supply a configuration directory that you have permissions to read and write to.
```

### Workaround

in `Saltfile` change `priv` to `ssh_priv`:
```yaml
---
salt-ssh:
  ssh_priv: path-to-your-private-key
  roster_file: ./roster-file.yml
  ssh_log_file: ./log/salt/ssh
```

and run the same command
```
$ salt-ssh -i '*' test.ping

# WARNING: CONFIG '/etc/salt' directory does not exist.
# testhost:
#     True
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 15 2017, 13:09:40)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: x86_64
        release: 16.4.0
         system: Darwin
        version: 10.12.3 x86_64
```

**Comment by Ch3LL** [comment]
My understanding is that `priv` is the default configuration. I was able to replicate your behavior, but only when priv is set in the Saltfile. When i add `priv:` to the roster yaml file it then works. So i think the issue is not a documentation issue but an issue with the code to use global paramters in the saltfile

**Comment by alexhrescale** [comment]
Thanks for the quick reply. I can confirm that in my setup, it **only** works with the `Saltfile` + `ssh_priv` combination. i.e.

```
#+BEGIN_SRC sh :results output
head Saltfile roster-file.yml
salt-ssh -i '*' test.ping | grep True
#+END_SRC

#+RESULTS:
#+begin_example
==> Saltfile <==
---
salt-ssh:
  ssh_priv: path-to-key
  roster_file: ./roster-file.yml
  ssh_log_file: ./log/salt/ssh

==> roster-file.yml <==
devbox:
  host: ip-of-box
  user: username
  
devbox:
    True
#+end_example
```

changing `ssh_priv` to `priv` in `Saltfile`, or moving that directive entirely to `roster-file.yml`, regardless of `ssh_priv` or `priv`, all fail with the `salt-ssh could not be run because it could not generate keys.` response

**Comment by Ch3LL** [comment]
Wait so are you saying changing your settings to this:

```
➜  saltfile cat Saltfile
salt-ssh:
  roster_file: ./roster-file.yml
  ssh_log_file: ./log/salt/ssh
➜  saltfile cat roster-file.yml 
testhost:
  host: localhost
  user: ch3ll
  priv: /home/ch3ll/.ssh/remove
```

Is not working for you either?

I can confirm it works for me on 2016.11.5

```
➜  saltfile sudo salt-ssh '*' test.ping
testhost:
    True
```
