### ISSUE TITLE
Can generate multiple files based on pillar data?

### ISSUE THREAD

**Issue by wmariuss** [saltstack/salt#41923]
### Description of Issue/Question
So, there is a way to do that?

### Setup
I have  pillar data:
```
{
  "deploy": {
    "data1": {
      "replica_no": 1,
      "version": "2.2.0",
      "image_url": "data",
      "branch": "data",
      "port_in": number,
      "port_out": number,
      "app_name": "data",
      "domain": "data",
      "nginx_port": number
    },
     "data2": {
      "replica_no": 1,
      "version": "2.2.0",
      "image_url": "data",
      "branch": "data",
      "port_in": number,
      "port_out": number,
      "app_name": "data",
      "domain": "data",
      "nginx_port": number
    }
  }
}
```
Based on pillar data, I do a loop and I want to generate for every loop a file with data content.
For e.g.
`file1` all data from `data1` and so on.

### Versions Report
```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
```

**Comment by terminalmage** [comment]
It's not clear what you're asking. What do you want the actual contents of the file to be? How do you want the file to look?

**Comment by wmariuss** [comment]
So, I have the pillar specified before.
And this code
```
import salt

def run():

  deploy = {}

  user = 'admin'
  listContainers = __grains__['kubectl_deployments']

  deploy['deploy_dir'] = {
    'file.directory': [
      {'name': '/opt/deployment'},
      {'user': user}
    ]
  }

  for app, info in __pillar__['deploy'].iteritems():

    if app not in listContainers:
      cmd = 'kubectl create -f /opt/deployment/' + app + '.yaml'
    else:
      cmd = 'kubectl apply -f /opt/deployment/' + app + '.yaml'

    if app:
      deploy[app] = {
        'file.managed': [
          {'name': '/opt/deployment/' + app + '.yaml'},
          {'user': user},
          {'source': 'salt://deploy/files/deployment.yaml'},
          {'template': 'jinja'},
          {'require': [{
            'file': 'deploy_dir'
            }]
          }
        ]
      }

    deploy['deploy_' + app] = {
      'cmd.run': [
        {'name': cmd},
        {'uer': 'root'},
        {'onchanges': [{
          'file': app
          }]
        }
      ]
    }

  return deploy
```
`deployment.yaml` has a kubernetes config, using pillar to populate data in few rows (which I think must be in pillar).
Let's put `deployment.yaml` file config here too
```
{% if pillar['deploy'] is defined %}
{%- for app, info in pillar['deploy'].iteritems() %}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ app }}
spec:
  replicas: {{ info.get('replica_no', '') }}
  template:
    metadata:
      labels:
        app: {{ app }}
    spec:
      containers:
      - name: {{ app }}
        image: {{ info.get('image_url', '') }}/{{ info.get('app_name', '') }}:{{ info.get('version', '') }}-{{ info.get('branch', '') }}
        {% if pillar['env_variables'][app] is defined -%}
        env:
        {% for env_var in pillar['env_variables'][app] -%}
        {% for name, value in env_var.items() -%}
        - name: {{ name }}
          value: {{ value }}
        {% endfor -%}
        {% endfor -%}
        {%- endif -%}
        ports:
        - containerPort: {{ info.get('port_in', '') }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ app }}
  labels:
    app: {{ app }}
spec:
  type: NodePort
  #type: LoadBalancer
  ports:
    - name: ext
      port: {{ info.get('port_in', '') }}
      #targetPort: 30101
      nodePort: {{ info.get('port_out', '') }}
  selector:
    app: {{ app }}
{%- endfor -%}
{%- endif -%}
```
So, based on data from pillar, I want to generate every file with own config.
`file1` to has data from `data1 `
...

`file1` == `pillar['deploy'][data1]`
...

So, there is a way to specify, hey config file, please put only data from pillar['deploy'][data1], not all as it's doing now.
