### ISSUE TITLE
Process for executing .bin/.sh files on Solaris using similar methods to pkg.install/win_repo

### ISSUE THREAD

**Issue by Amacelia** [saltstack/salt#41950]
### Description of Issue/Question
On Solaris, is there a way to cause .bin/.sh install and uninstall files to execute similarly to the way .pkg files are handled with pkg.install? Or, similarly to the way packages (.exe, .msi) are handled via win_repo?
Is there an alternative way to handle these types of installations/uninstallations (.bin, .sh) due to their differing file types?
### Setup

For Solaris, you can see commands like the following used to install software using .pkg file types:
`salt '*' pkg.install sources='[{"SMClgcc346": "salt://pkgs/gcc-3.4.6-sol10-sparc-local.pkg"}]'
`
But, we do not have .pkg files, instead we have .bin/.sh.

For windows, you can see win_pkg/a winrepo definition sls file being used to install an .exe file:
```
ntp:
  4.2.8:
    installer: 'salt://win/repo/ntp/ntp-4.2.8-win32-setup.exe'
    full_name: Meinberg NTP Windows Client
    locale: en_US
    reboot: False
    cache_file: 'salt://win/repo/ntp/install.ini'
    install_flags: '/USEFILE=C:\salt\var\cache\salt\minion\files\base\win\repo\ntp\install.ini'
    uninstaller: 'NTP/uninst.exe'
```
But, there is not a similar concept of winrepo available for use on Solaris?

### Versions Report
CentOS 7 - Master Version: 2016.11.0
Windows XP - Minion Version: 2016.3.4
Solaris 10 - Minion Version: 2016.11.1
