### ISSUE TITLE
reg.present error with REG_DWORD long type number

### ISSUE THREAD

**Issue by skjaro** [saltstack/salt#41975]
### Description of Issue/Question
Hi,

There is problem with windows reg module in salt 2016.5 and possibly lower versions.
When number is not int but long reg.present throws errror. I have simple one liner fix.

### Setup
```
numlock_enable_default:
  reg.present:
    - name: HKEY_USERS\.Default\Control Panel\Keyboard
    - vname: InitialKeyboardIndicators
    - vdata: 0x80000002
    - vtype: REG_DWORD
```
### Steps to Reproduce Issue
```
2017-06-12 16:14:15,924 [salt.loaded.int.module.reg][ERROR   ][4368] coercing to Unicode: need string or buffer, long found
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\modules\reg.py", line 565, in set_value
    local_vdata = _mbcs_to_unicode_wrap(vdata, local_vtype)
  File "c:\salt\bin\lib\site-packages\salt\modules\reg.py", line 120, in _mbcs_to_unicode_wrap
    return _mbcs_to_unicode(obj)
  File "c:\salt\bin\lib\site-packages\salt\modules\reg.py", line 103, in _mbcs_to_unicode
    return six.text_type(instr, 'mbcs')
TypeError: coercing to Unicode: need string or buffer, long found 
```

### Versions Report
```
    Salt Version:
               Salt: 2016.11.5

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: unknown
           dateutil: 2.5.3
          docker-py: Not Installed
              gitdb: 0.6.4
          gitpython: 2.0.8
              ioflo: 1.5.5
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 16.0.1
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.4.1
                ZMQ: 4.1.6

    System Versions:
               dist:
            machine: AMD64
            release: 7
             system: Windows
            version: 7 6.1.7601 SP1 Multiprocessor Free
```
### Fix
```
    if isinstance(obj, list):
        return [_mbcs_to_unicode(x) for x in obj]
    elif isinstance(obj, int):
        return obj
    else:
        return _mbcs_to_unicode(obj)
```

Change to:

```
    if isinstance(obj, list):
        return [_mbcs_to_unicode(x) for x in obj]
    elif isinstance(obj, int) or isinstance(obj,long):
        return obj
    else:
        return _mbcs_to_unicode(obj)
```
