### ISSUE TITLE
sdb.get returns None as string instead of object

### ISSUE THREAD

**Issue by epcim** [saltstack/salt#41984]
### Description of Issue/Question
sdb.get for non existing object doesnt allow to use default values

### Setup

`sdb://mysqlite/test_user` is set while test_group not.

```
/tmp/xxx:
  file.managed:
    - user: {{ salt['sdb.get']('sdb://mysqlite/test_user') }}
    - group: {{ salt['sdb.get']('sdb://mysqlite/test_group') | default('groupxyz') }}
    - contents: xyz
```

### How it should work

when sdb.get will not find key, it should return an None/False object, so the value will be 'groupxyz'

### Question

documentation many times says use

/tmp/xxx:
  file.managed:
    - user: sdb://mysqlite/test_user

which I haven't found to be correct sytnax, as it always returns the `sdb://mysqlite/test_user` instead of it;s value.
