### ISSUE TITLE
virtualenv and pip env_vars don't get unset

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#42042]
### Description of Issue/Question
If a managed virtualenv sets env_vars those variables are hold in the salt-minion process. The problem is if those env_vars aren't cleaned up, they remain in the process and affect further highstate execution.

E.g. after `virtualenv.managed`  execution with setting env_vars http_proxy & https_proxy other states fail because those try to download packages through proxy (but os package repository is accessible directly and not accessible through proxy).

Those env_vars must be set too because the `- proxy` option is only passed to pip install and not passed to easy_install.

Same problem with `pip.installed`

### Steps to Reproduce Issue
Use this state to verify the problem:

```
### env variables are unset
envvars:
  cmd.run:
    - name: echo $http_proxy

envvars2:
  cmd.run:
    - name: echo $https_proxy

### install virtualenv
test_venv:
  virtualenv.managed:
    - name: /usr/local/test-env
    - system_site_packages: False
    - pip_upgrade: True
    - proxy: http://myproxy.internal:3128
    - env_vars:
        http_proxy: 'http://myproxy.internal:3128'
        https_proxy: 'https://myproxy.internal:3128'
    - requirements: salt://{{ slspath }}/files/requirements.txt


### env variables are set
envvars3:
  cmd.run:
    - name: echo $http_proxy

envvars4:
  cmd.run:
    - name: echo $https_proxy
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jun 26 2017, 07:28:21)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 10.3-RELEASE-p18
         system: FreeBSD
        version: Not Installed

```
