### ISSUE TITLE
[salt.utils.gitfs ][CRITICAL] Invalid gitfs configuration parameter 'saltenv' in remote git+ssh://git@ourgitserver/ourgitrepo.git.

### ISSUE THREAD

**Issue by stamak** [saltstack/salt#42082]
### Description of Issue/Question
From time to time saltmaster raises an interesting critical error in logs:

2017-07-03 13:23:11,091 [salt.utils.gitfs ][CRITICAL][16966] **Invalid gitfs configuration parameter 'saltenv' in remote** git+ssh://git@ourgitserver/ourgitrepo.git. Valid parameters are: **base, mountpoint, root, ssl_verify, name.** See the GitFS Walkthrough in the Salt documentation for further information.

### Setup

saltmaster config
```
fileserver_backend:
  - git
gather_job_timeout: 11
gitfs_provider: gitpython
gitfs_remotes:
  - git+ssh://git@ourgitserver/ourgitrepo.git:
    - saltenv:
      - our-dev:
        - ref: 'our-dev'
gitfs_root: states
gitfs_saltenv_whitelist:
  - 'our-dev'
```

### Steps to Reproduce Issue

Logs
```
2017-07-03 13:23:11,091 [salt.utils.gitfs ][CRITICAL][16966] Invalid gitfs configuration parameter 'saltenv' in remote git+ssh://git@ourgitserver/ourgitrepo.git. Valid parameters are: base, mountpoint, root, ssl_verify, name. See the GitFS Walkthrough in the Salt documentation for further information.
```

### Versions Report
```
salt-master --versions-report                                                                      
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 4.0.0
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4


System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
