### ISSUE TITLE
Nitrogen, if modifying the file_roots path in the master config file, winrepo will not be updated on the minions.

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#42093]
### Description of Issue/Question
Nitrogen, if modifying the file_roots path in the master config file, winrepo will not be updated on the minions.

```
PS C:\salt\pillar> salt-run winrepo.update_git_repos
https://github.com/saltstack/salt-winrepo-ng.git:
    c:\salt\srv\salt\win\repo-ng\salt-winrepo-ng
https://github.com/saltstack/salt-winrepo.git:
    c:\salt\srv\salt\win\repo\salt-winrepo
PS C:\salt\pillar> salt winpy3 pkg.refresh_db
winpy3:
    ----------
    failed:
        0
    success:
        0
    total:
        0
```

It is working correctly if don't modify file_roots path in master config file.

### Setup
Windows master/minion
Modify file_roots path in master config file.

### Steps to Reproduce Issue
salt-run winrepo.update_git_repos
salt * pkg.refresh_db

### Versions Report
```
Salt Version:
           Salt: 2017.7.0rc1

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```
