### ISSUE TITLE
OpenBSD minion. salt.modules.openbsdpkg.install is not able to handle 'flavored' packages

### ISSUE THREAD

**Issue by kirill-aga** [saltstack/salt#42112]
### Description of Issue/Question
OpenBSD ported packages are named according to the following pattern (see 'man packages-specs'):

`<stem>-<version>-<flavors>.tgz`

So, for example, postfix with optional mysql functionality looks like:

`postfix-3.3.20170218-mysql.tgz`

So, 'postfix' is the name, '3.3.20170218' is the version and 'mysql' is the flavor.

Stem part can, however, contain dashes, so some package maintainers added even more mess to already existing one and created something like:

`dovecot-mysql-2.2.28.tgz`
 
Here 'dovecot-mysql' is **the name**, version is '2.2.28' and there is no flavor!

Salt can perfectly cope with packages without flavor but unable to work with flavored ones.

### Setup
Clean install OpenBSD (any supported version). Create the global variable PKG_PATH pointing to one of the official OpenBSD package mirror sites. Use salt bootstrap.sh with option -P to download and install salt via pip. Check the minion status and accept the newly created minion on the master.

### Steps to Reproduce Issue

Login to the master and check the OpenBSD minion connectivity. Proceed if it responding to test.ping command.

1. Check if the installation is working for 'wrongly named' packages, where actual flavor mecame part of the name before the version:

```
root@salt-master-new:~# salt 'obsd*' pkg.latest_version dovecot-mysql
obsd01:
    2.2.28
root@salt-master-new:~# salt 'obsd*' pkg.install dovecot-mysql
obsd01:
    ----------
    dovecot:
        ----------
        new:
            2.2.28p0
        old:
    dovecot-mysql:
        ----------
        new:
            2.2.28
        old:
root@salt-master-new:~# 
```

2. Try to install postfix (flavored), salt will fail:

```
root@salt-master-new:~# salt 'obsd*' pkg.latest_version postfix--mysql
obsd01:
    3.3.20170218
root@salt-master-new:~# salt 'obsd*' pkg.install postfix--mysql
obsd01:
    ----------
root@salt-master-new:~# 
```

Note the double dash notation, that's actually the correct way to request 'flavored' package info in OpenBSD, omitting the version number:

```
# pkg_info -I postfix--mysql 
postfix-3.2.0-mysql fast, secure sendmail replacement
postfix-3.3.20170218-mysql fast, secure sendmail replacement
# 
```

3. If we try to specify version number, it doesn't work either:
```
root@salt-master-new:~# salt 'obsd*' pkg.install postfix-3.3.20170218-mysql
obsd01:
    ERROR: Problem encountered installing package(s). Additional info follows:
    
    changes:
        ----------
    errors:
        - ftp://ftp.eu.openbsd.org/pub/OpenBSD/6.1/packages/amd64/postfix-3.3.20170218-mysql--.tgz: 550 Failed to open file.
          signify: gzheader truncated
```

### Versions Report

```
# salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Apr  1 2017, 14:51:20)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist:   
        machine: amd64
        release: 6.1
         system: OpenBSD
        version: Not Installed

```

**Comment by eradman** [comment]
OpenBSD package flavor and branch support was added in commit 16e46e (Sep 8,
2016). I don't know if this made it into the 2016.11.3 release, but the
the OpenBSD pkg_add(1) syntax does work when running the Salt `develop` branch

  (saltenv) $ sudo -E salt-call --local --file-root=$PWD pkg.install 'jed--no_x11'
  local:
      ----------
      jed--no_x11:
          ----------
          new:
              0.99.19p1
          old:
      libslang:
          ----------
          new:
              2.2.4p2
          old:
      oniguruma:
          ----------
          new:
              5.9.6
          old:

But this still doesn't work with the mysql flavor of postfix

  $ sudo pkg_add -x -I postfix--mysql
  quirks-2.304 signed on 2017-04-02T15:01:33Z
  Ambiguous: postfix--mysql% could be postfix-3.2.0-mysql postfix-3.3.20170218-mysql

What is the right syntax for adding this package?

  $ sudo pkg_add -x -I postfix--mysql%3.2.0
  quirks-2.304 signed on 2017-04-02T15:01:33Z
  Can't find postfix--mysql%3.2.0

**Comment by kirill-aga** [comment]
Right syntax would be exactly as they listed: <stem>-<version>-<flavor>

```
# pkg_add postfix-3.3.20170218-mysql   
quirks-2.304 signed on 2017-04-02T15:01:33Z
-> Creating /etc/mailer.conf.postfix
-> Creating Postfix spool directory and chroot area under /var/spool/postfix
-> Creating Postfix data directory under /var/postfix
+---------------
| Configuration files have been installed in /etc/postfix.
| Please update these files to meet your needs.
+---------------
postfix-3.3.20170218-mysql: ok
The following new rcscripts were installed: /etc/rc.d/postfix
See rcctl(8) for details.
--- +postfix-3.3.20170218-mysql -------------------
Postfix can be set up to replace sendmail entirely. Please read the
documentation at file:///usr/local/share/doc/postfix/html/index.html or
http://www.postfix.org/ carefully before you decide to do this!

To replace sendmail with Postfix you have to install a new mailer.conf
using the following command:

    /usr/local/sbin/postfix-enable

If you want to restore sendmail, this is done using the following command:

    /usr/local/sbin/postfix-disable
# 

```

**Comment by Ch3LL** [comment]
@eradman does @kirill-aga 's latest comments help for a possible fix.

Also i can confirm that the fix mentioned would not be in 11.3 but will be in the 2017.7.0 nitrogen release that is currently in its first release candidate.

**Comment by eradman** [comment]
@Ch3LL yes this helps. The problem seems to be simple to fix. The package formatting was too aggressive, and would append `--` (default flavor) and `%` (default branch) to package names.

**Comment by kirill-aga** [comment]
Actually, if you look to the state files syntax, it should be taken into consideration. For example, this SLS is legit and should work (but does not work in the current stable salt version):

```
postfix-mysql-pkg:
  pkg.installed:
    - name: postfix--mysql
    - version: 3.3.20170218

```

Full package name is OK for command line, but for SLS, "classic" syntax should work as well.
