### ISSUE TITLE
[2017.7.0rc1] schedule.present always triggers a change

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#42127]
### Description of Issue/Question
This may be related to #42125 

Every highstate run triggers a change for a job.

```
----------
          ID: salt.minion::schedule-apply
    Function: schedule.present
      Result: True
     Comment: Modifying job salt.minion::schedule-apply in schedule
     Started: 15:17:44.096627
    Duration: 79.356 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -4,5 +4,4 @@
                   maxrunning:1
                   minutes:20
                   name:salt.minion::schedule-apply
                  -seconds:1200
                   splay:300
```
### Setup
The fragment the state sls
```yaml
salt.minion::schedule-apply:  ## schedule apply
{% if saltcfg['schedule_apply'] > 0 %}
  schedule.present:
    - function: state.apply
    - maxrunning: 1
    - minutes: {{ saltcfg['schedule_apply'] }}
    - splay: {{ (saltcfg['schedule_apply'] * 60 / 100 * 25)|round|int }}  ## 25% spread
{% else %}
  schedule.absent
{% endif %}
````

### Steps to Reproduce Issue
This job always triggers for me, but only on one minion.
A 2nd nearly identical minion does not trigger is :-1: 

### Versions Report
```
[root@mantle ~]# salt-call --versions-report
Salt Version:
           Salt: 2017.7.0rc1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 8.8.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: 1.6.7
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec 30 2016, 13:53:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.6
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
 
System Versions:
           dist:   
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
