### ISSUE TITLE
network.system disables interfaces

### ISSUE THREAD

**Issue by astronouth7303** [saltstack/salt#42145]
### Description of Issue/Question

Spinning up a new minion and applying this state, the network interface is left in a disabled state (as reported by `ip addr`).

```yaml
system:
  network.system:
    - enabled: True
    - hostname: {{ grains['id'] }}
    - nozeroconf: True
    - apply_hostname: True
```

This, of course, makes the rest of the highstate process extremely difficult.

### Setup

Minion: Debian Stretch, Salt 2016.11.2, running on VMware ESXi/vSphere, created by salt-cloud (via clone from template)
Master: Debian Jessie, 2016.11.5

(No, I'm not sure why the version discrepancy, since the `salt-cloud` is invoked on the master.)

### Steps to Reproduce Issue

```
$ salt-cloud -p myprofile myinstance
$ salt myinstance state.apply hostname
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.0 
        machine: x86_64
        release: 4.9.0-3-amd64
         system: Linux
        version: debian 9.0 
```

**Comment by Ch3LL** [comment]
@astronouth7303 can you paste sanitized version of minion debug logs and paste here to determine why its in a disabled stated? Thanks

**Comment by astronouth7303** [comment]
[minion log](https://github.com/saltstack/salt/files/1128185/minion.txt)

**Comment by astronouth7303** [comment]
Excuse me, I misread. I posted the existing minion log. This is the actual DEBUG log.

[salt-debug.txt](https://github.com/saltstack/salt/files/1131426/salt-debug.txt)

**Comment by astronouth7303** [comment]
Adjusting my process so that the the minion is 2016.11.6 does not fix this.

**Comment by astronouth7303** [comment]
Is there further information needed?

**Comment by lorengordon** [comment]
Might be related, https://github.com/saltstack/salt/issues/42013. Which [was fixed](https://github.com/saltstack/salt/pull/42017) in the 2016.11 branch, but hasn't yet made it to a release.

**Comment by astronouth7303** [comment]
@lorengordon I don't think so? I'm on debian, so I don't think a fix in `rh_ip.py` would apply?

**Comment by lorengordon** [comment]
@astronouth7303 Oh you're probably right, sorry. I just keyed on the `nozeroconf` in your sls.

**Comment by astronouth7303** [comment]
I should confirm if this still exists...

**Comment by astronouth7303** [comment]
Is this still a thing?

**Comment by Ch3LL** [comment]
looks like im able to replicate this on 2019.2.3 as well. will need to get this fixed up.

**Comment by jleroy** [comment]
This issue is still present in 3000.3.
It seems to happens only when `network.system` and `network.managed` are used together.
I see no error related to networking in minion log or syslog but the main interface (eno1 in my case) is in state `DOWN` after the state has been applied.  

```
system:
  network.system:
    - enabled: True
    - hostname: lb2-l
    - apply_hostname: True

# Network.
eno1:
  network.managed:
    - enabled: True
    - type: eth
    - proto: static
    - noifupdown: True
    - ipaddr: 10.0.0.234
    - netmask: 255.255.255.0
    - gateway: 10.0.0.254
    - enable_ipv6: True
    - ipv6proto: static
    - ipv6ipaddr: 2001:41d0:2000:3000::1
    - ipv6netmask: 64
```
