### ISSUE TITLE
include/import is non-idempotent, leading to incorrect state validation

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#42167]
### Description of Issue/Question
It would appear that each time a state file is included or imported by another file, it is "run" again.
1. For users familiar with Python, this creates unexpected behavior. 
2. In some cases, Saltstack itself is spuriously giving state success when it should not.

### Setup

```
# A.sls
{% set tmpdir = salt.temp.dir() %}

state_a:
  file.directory:
    - name: {{ tmpdir }}
```

```
# B.sls
{% from "A.sls" import tmpdir %}

include:
  - A

state_b:
  file.managed:
    - require:
      - state_a
    - name: {{ tmpdir }}/foo.txt
    - makedirs: False
```

Result of calling B:

```
local:
----------
          ID: state_a
    Function: file.directory
        Name: /tmp/tmpi318bt1e
      Result: True
     Comment: Directory /tmp/tmpi318bt1e is in the correct state
     Started: 09:59:05.301815
    Duration: 3.645 ms
     Changes:   
----------
          ID: state_b
    Function: file.managed
        Name: /tmp/tmp79zm1wmk/foo.txt
      Result: True
     Comment: Empty file
     Started: 09:59:05.305650
    Duration: 0.713 ms
     Changes:   
              ----------
              new:
                  file /tmp/tmp79zm1wmk/foo.txt created

Summary for local
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time:   4.358 ms
```

Note the different directory names:
* state_a:  /tmp/tmpi318bt1e
* state_b: /tmp/tmp79zm1wmk

Sate success here would appear to be spurious.

### Steps to Reproduce Issue
Run "B" above.

### Versions Report
```
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jan 19 2017, 14:11:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 17.04 zesty
        machine: x86_64
        release: 4.12.0-041200rc6-generic
         system: Linux
        version: Ubuntu 17.04 zesty
```

**Comment by gtmanfred** [comment]
You would need to open this with jinja.

It isn't running the salt state again, just the jinja that is setting the tmpdir is being set again.

Also, the salt.temp.dir does create the directory, so makedirs wouldn't be needed, because the module is making the directory.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.temp.html#salt.modules.temp.dir

**Comment by brianthelion** [comment]
@gtmanfred Thanks! Retracted the "makedirs" comment before seeing your response.

What is the appropriate Salt idiom for this use-case?

**Comment by gtmanfred** [comment]
require only needs the `result` of the other state to be True.  If that state executed successfully, then b can be successful.

Is there a reason to not just use this all in one state, since temp.dir creates the tmpdir?

What is the purpose of not just doing

```
{%- set tmpdir = '/tmp/' ~ salt.random.get_str(length=10) %}
state_b:
  file.managed:
    - require:
      - state_a
    - name: {{ tmpdir }}/foo.txt
    - makedirs: True
```
