### ISSUE TITLE
Route53 boto module should retry on PriorRequestNotComplete

### ISSUE THREAD

**Issue by fpires82** [saltstack/salt#42162]
### Description of Issue/Question
Route53 zones sometimes won't allow a change in records while there's another change ongoing, and will return a PriorRequestNotComplete error code. Salt boto module is only retrying on Throttling error, but not on PriorRequestNotComplete, resulting in records not being created / updated if you have multiple operations ongoing.

The module should also retry on such error, and maybe it could be possible to pass a retry interval as an option, or just define an interval that will increment with each additional retry until the set retry is reached.

From AWS docs:
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html

> If Amazon Route 53 can't process a request before the next request arrives, it will reject subsequent requests for the same hosted zone and return an HTTP 400 error (Bad request). The response header also includes a Code element with a value of PriorRequestNotComplete and a Message element with a value of The request was rejected because Route 53 was still processing a prior request.

Here's a similar issue in terraform:
https://github.com/hashicorp/terraform/issues/183

And Ansible:
https://github.com/ansible/ansible/issues/4085

### Setup
This is an example of an add record we are using:

```
create_A_record:
  local.boto_route53.add_record:
    - tgt: salt
    - arg:
      - name={{ event_data.get('kwargs',{}).get('name') }}
      - value={{ event_data.get('kwargs',{}).get('host') }}
      - zone=mydomain.com
      - record_type=A
      - wait_for_sync=True
      - rate_limit_retries=5
      - ttl=60
```

### Steps to Reproduce Issue
Try to create multiple records. Sometimes if the timing is right, some will not get created.

### Versions Report
```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.8.1
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Dec 19 2015, 08:44:39)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

We are using python boto 2.47.0.
