### ISSUE TITLE
How to requite id from another state file with or without the function of the id?

### ISSUE THREAD

**Issue by G-Geary** [saltstack/salt#42187]
### Description of Issue/Question

i have two state files for example one.sls and two.sls
################
one.sls:
```
id_one:
  service.running:
    - name: One
```
###############

###############
two.sls:
```
id_two:
  file.append:
    - name: Two
    - require:
      - id_one:
        - running
```
################

According to this link https://docs.saltstack.com/en/getstarted/config/requisites.html it is possible to require an id from another state file using the id and then the function. I cannot however get it to work and receive the following message:

"    Data failed to compile:
----------
    Illegal requisite "['running']", please check your syntax. "

I also tried "running" and service.running and also "service.running" but no success.

Could you advise if this is possible and if so, where abouts I am going wrong?

### Versions Report
Salt-Master version: salt-master 2016.11.5 (Carbon)
Salt-Minion: 2016.11.3

#####
Thanks in advance!

**Comment by G-Geary** [comment]
the indentation of the arguments was removed from my question, but the are indented with two spaces after "-require" and then another two after "id_one".

**Comment by G-Geary** [comment]
like this:

![image](https://user-images.githubusercontent.com/29755594/27934258-35d5ca52-62a5-11e7-99a9-c55e6394b264.png)

**Comment by gtmanfred** [comment]
```
id_two:
  file.append:
    - name: 'Two'
    - require:
      - service: id_one
```

Use the module name, not the function name.
