### ISSUE TITLE
salt.states.win_iis.container_setting failures when changing identity

### ISSUE THREAD

**Issue by gaizeror** [saltstack/salt#42196]
### Description of Issue/Question
Hey.
I try to configure iis app pool.
I need the identity of the app pool to be a specific user.
When I try to add it as a container setting, I get output that it changed, but nothing is being changed.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
root@salt-host1:/srv/salt# cat iis.sls
ISWebserverRole:
  win_servermanager.installed:
    - force: True
    - recurse: True
    - name: Web-Server

site0-apppool:
    win_iis.create_apppool:
        - name: site0
site0-apppool-setting:
    win_iis.container_setting:
        - name: site0
        - container: AppPools
        - settings:
            managedPipelineMode: Integrated
            processModel.maxProcesses: 1
            processModel.userName: test
            processModel.password: 123456
```
The out put is:
```
root@salt-host1:/srv/salt# salt '*' state.apply iis
minion:
----------
          ID: ISWebserverRole
    Function: win_servermanager.installed
        Name: Web-Server
      Result: True
     Comment: Web-Server already installed but might install sub-features
     Started: 13:22:08.044000
    Duration: 2250.0 ms
     Changes:
----------
          ID: site0-apppool
    Function: win_iis.create_apppool
        Name: site0
      Result: True
     Comment: Created application pool: site0
     Started: 13:22:10.294000
    Duration: 3078.0 ms
     Changes:
              ----------
              new:
                  site0
              old:
                  None
----------
          ID: site0-apppool-setting
    Function: win_iis.container_setting
        Name: site0
      Result: True
     Comment: Set settings to contain the provided values.
     Started: 13:22:13.372000
    Duration: 6465.0 ms
     Changes:
              ----------
              processModel.password:
                  ----------
                  new:
                      123456
                  old:
              processModel.userName:
                  ----------
                  new:
                      test
                  old:

Summary for minion
------------
Succeeded: 3 (changed=2)
Failed:    0
------------
Total states run:     3
Total run time:  11.793 s
```
And nothing being changed on the app pool identity at the iis "Advanced Configuration" panel.
[Result Picture](http://imgur.com/YQVhuWh)

When I try to collect the info from salt, this is the result:

```
root@salt-host1:/srv/salt# salt '*' win_iis.get_container_setting name='site0' container='AppPools' settings="['processModel.*']"
minion:
    ----------
    processModel.*:
        @{identityType=4; userName=test; password=123456; loadUserProfile=False; setProfileEnvironment=True; logonType=0; manualGroupMembership=False; idleTimeout=00:20:00; idleTimeoutAction=0; maxProcesses=1; shutdownTimeLimit=00:01:30; startupTimeLimit=00:01:30; pingingEnabled=True; pingInterval=00:00:30; pingResponseTime=00:01:30; logEventOnProcessModel=1; PSPath=WebAdministration::\\minion\AppPools\site0; PSParentPath=WebAdministration::\\minion\AppPools; PSChildName=site0; PSDrive=IIS; PSProvider=WebAdministration}
```

So I found out that the problem is that the state sets the user and password, but doesnt change the identityTpe to 3 (specific user). So i added that to the state:

```
site0-apppool-setting:
    win_iis.container_setting:
        - name: site0
        - container: AppPools
        - settings:
            managedPipelineMode: Integrated
            processModel.maxProcesses: 1
            processModel.identityType: 3
            processModel.userName: test
            processModel.password: 123456
```

And the result is:
```
root@salt-host1:/srv/salt# salt '*' state.apply iis
minion:
----------
          ID: ISWebserverRole
    Function: win_servermanager.installed
        Name: Web-Server
      Result: True
     Comment: Web-Server already installed but might install sub-features
     Started: 13:31:08.650000
    Duration: 2358.0 ms
     Changes:
----------
          ID: site0-apppool
    Function: win_iis.create_apppool
        Name: site0
      Result: True
     Comment: Application pool already present: site0
     Started: 13:31:11.010000
    Duration: 508.0 ms
     Changes:
----------
          ID: site0-apppool-setting
    Function: win_iis.container_setting
        Name: site0
      Result: False
     Comment: Some settings failed to change.
     Started: 13:31:11.518000
    Duration: 11502.0 ms
     Changes:
              ----------
              changes:
                  ----------
              failures:
                  ----------
                  processModel.identityType:
                      ----------
                      new:
                          SpecificUser
                      old:
                          ApplicationPoolIdentity

Summary for minion
------------
Succeeded: 2 (changed=1)
Failed:    1
------------
Total states run:     3
Total run time:  14.368 s
```
How ever, the identity is being changed as i wanted, but the result is Failed.
[Result Picture](http://imgur.com/9uFZKZ6)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Install IIS
Create App pool
Change the identity user&password of the app pool
run and check if changed

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
root@salt-host1:/srv/salt# salt --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-81-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```
