### ISSUE TITLE
[2017.7.0rc1] file.line triggers warning that seems wrong.

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#42190]
### Description of Issue/Question

As mentioned https://docs.saltstack.com/en/develop/ref/states/all/salt.states.file.html#salt.states.file.line file.line takes the 'content' parameter.

```
isotope.pkgsrc.sandbox::hook:
  file.line:
    - name: /data/pkgbuild/scripts/run-sandbox
    - mode: ensure
    - before: "/usr/sbin/chroot ${chrootdir} /bin/bash --login"
    - content: "/data/keys/setup-env ${chrootdir}"
```

Now generates a warning:
```
    2017-07-07 01:02:15,901 [salt.loaded.int.states.file                                            ][WARNING ][25062] State for file: /data/pkgbuild/scripts/run-sandbox - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
```

It as the file was already in the good state, I am not 100% the state still works.

### Versions Report
```yaml
Salt Version:
           Salt: 2017.7.0rc1

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 8.1.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: 1.6.7
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec 31 2016, 10:50:46)
   python-gnupg: 2.2.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.6
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
