### ISSUE TITLE
state sqlite3.row_absent fail with "parameters are of unsupported type"

### ISSUE THREAD

**Issue by shengis** [saltstack/salt#42198]
### Description of Issue/Question
The state **sqlite3.row_absent** is failing with : 
```
master:
----------
          ID: vm-del-dns-us1-dns-node02
    Function: sqlite3.row_absent
      Result: False
     Comment: parameters are of unsupported type
     Started: 15:32:34.795869
    Duration: 1.662 ms
     Changes:  
```
Seems like, while the **where_args** parameter is optional, if absent the state is failing.

### Setup

```
vm-del-dns-{{ name }}:
  sqlite3.row_absent:
    - db: /var/lib/powerdns/pdns.sqlite3
    - table: records
    - where_sql: "name='{{ name }}' and type='A'"
```

### Steps to Reproduce Issue
**I have a fix that I will post as a PR.**

The steps to reproduce are pretty straight forwards.
1. having a sqlite3 db with a table
2. trying this state : 
```
test:
  sqlite3.row_absent:
    - db: /path/mydb.sqlite3
    - table: mytable
    - where_sql: "mycolumn='whatever'"
```

### Versions Report

```
Salt Version:
           Salt: 2017.5.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-78-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
