### ISSUE TITLE
Service beacon needs a delay option

### ISSUE THREAD

**Issue by jlayze** [saltstack/salt#42205]
### Description of Issue/Question
Currently the `service` beacon will fire an event as soon as the status changes if `onchangeonly` is `True`.  Reactors are then fired immediately following the event.  This presents a problem when a service is trying to stop/start itself as part of an update, and your reactor is to start the service if down.
### Setup
```
beacons:
  service:
    "Patch Agent":
      onchangeonly: True
```

### Steps to Reproduce Issue
Update an application which stops/starts its own service while using the `service` beacon and a reactor to start the service when it's stopped.

### Versions Report
```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
