### ISSUE TITLE
Parameter gitfs_root does not work correctly

### ISSUE THREAD

**Issue by Rodrigocg** [saltstack/salt#42239]
Hi,

I've the following conf file master:

```
interface: 0.0.0.0
ipv6: False
publish_port: xxxxx5
ret_port: xxxxx6

pki_dir: /etc/salt/pki/master
cachedir: /var/cache/salt/master

verify_env: True
keep_jobs: 24
gather_job_timeout: 10
timeout: 10
loop_interval: 60

show_timeout: True
color: True
strip_colors: False
cli_summary: True

enable_gpu_grains: False

max_open_files: 100000
pub_hwm: 1000

open_mode: False
auto_accept: False

hash_type: sha256

fileserver_backend:
  - git

gitfs_remotes:
  - ssh://git@github.com/xxxx/xxxx.git:
    - pubkey: /root/.ssh/id_rsa.pub
    - privkey: /root/.ssh/id_rsa

gitfs_ssl_verify: True
gitfs_root: base

ext_pillar:
  - git: master ssh://git@github.com/xxxx/xxxx.git root=pillar

log_file: /var/log/salt/master
log_level: info
log_level_logfile: info

```

In my repository exists 4 brachs, but I set  of the parameter gitfs_root with the branch name any parameter that is not master its not work.

Also, Sometimes when seted with master, its aply rules others branchs. I've delete all branchs Leaving only master branch for to work.

Is this a bug or are my configs?

version: salt-master 2016.11.6 (Carbon)
version: salt-minion 2015.8.8 (Beryllium)
