### ISSUE TITLE
Enable gpg.verify to support detached signatures

### ISSUE THREAD

**Issue by lucendio** [saltstack/salt#42237]
### Description of Issue/Question
This is just a friendly request to put the already-merged [effort from @Artanicus](https://github.com/saltstack/salt/commits/develop/salt/modules/gpg.py) into the 2017.7 release, because it already makes the verification a lot nicer, even though the work for #40596 is not completed yet.

rather than:
```
cmd.run:
    - name: gpg --verify /path/to archive.tar.gz.sig /path/to archive.tar.gz
```

we could do:
```
module.run:
    - name: gpg.verify
    - signature: /path/to archive.tar.gz.sig
    - filename: /path/to archive.tar.gz
```
