### ISSUE TITLE
salt.states.postgres_extension.present repeats to create extension

### ISSUE THREAD

**Issue by hiscal2015** [saltstack/salt#42241]
salt version: 2016.11.6

When use state postgres_extension.present, although required extension has been created for the first time, but it will still try to install the extension by re-run state file.

list extension for database ota:
```
ota=> \dx
                  List of installed extensions
   Name   | Version |   Schema   |         Description          
----------+---------+------------+------------------------------
 pgcrypto | 1.3     | public     | cryptographic functions
 plpgsql  | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

```

state file:
```
test:
  postgres_extension.present:
    - schema: public
    - name: pgcrypto
    - maintenance_db: ota
    - user: postgres
``` 

dry run:
```
----------
          ID: test
    Function: postgres_extension.present
        Name: pgcrypto
      Result: None
     Comment: Extension pgcrypto is set to be created
     Started: 15:38:54.432549
    Duration: 72.535 ms
     Changes:   
```
