### ISSUE TITLE
system.reboot

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#42243]
### Description of Issue/Question

When i run system.reboot it returns " Minion did not return. [Not connected]"

I understand that minion has went down because of reboot and did not return but shouldn't this cmd  return true/false?

**Comment by gtmanfred** [comment]
It depends on how quickly the minion shuts down.

If it shuts down really fast before the salt minion can return True or False, you will get that response.  There isn't a lot that we can do about that, because the shutdown process kills the running salt-minion daemon which kills the salt-minion process which is running the shutdown.

Thanks,
Daniel

**Comment by benner** [comment]
You can do delayed reboot like `shutdown -r +1` instead instant.

**Comment by gtmanfred** [comment]
Ahh yeah, you could run `system.reboot 1`  but your true or false would not
be related to if the system actually rebooted.

The best way to probably do that is this

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.saltmod.html#salt.states.saltmod.wait_for_event

/srv/salt/reboot.sls
```
reboot_minions:
  salt.function:
    - name: system.reboot
    - at_time: 1
    - tgt: {{pillar['match']|join(',')}}
    - tgt_type: list

wait_for_reboots:
  salt.wait_for_event:
    - name: salt/minion/*/start
    - id_list: {{pillar['match']}}
    - require:
      - salt: reboot_minions
```

Then you could run
`salt-run state.orchestrate reboot pillar='{"match": ["minion1",
"minion2"]}'`

And this will return back when the minions start up again.
