### ISSUE TITLE
Minion hangs while failing to mount over NFS

### ISSUE THREAD

**Issue by mikemartino** [saltstack/salt#42259]
### Description of Issue/Question
This is a general question. I noticed that some of my jobs (ie. `salt state.apply` calls) are hanging infinitely. I've determined that it's related to a specific mount state which is attempting to mount over NFS when that host is shut off.

When I run a `mount -a` on the hanging hosts, the mounting process gets backgrounded as I would expect. Does Salt require additional configuration to similarly background the mount process and return from the `state.apply`?

### Setup

```
some_mount:
    mount.mounted:
        - device: 123.45.67.8
        - fstype: nfs
        - mkmnt: true
        - opts: ro,vers=3,hard,bg,intr,mountproto=tcp,nofail
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
Salt: 2016.11.5

**Comment by The-Loeki** [comment]
You're trying a `hard` mount; that'll induce that behaviour methinks. Try mounting softly, it should fail more gracefully (I'm not sure what `nofail` does though)

**Comment by The-Loeki** [comment]
`mount -a`  is basically a simple loop which async starts mounting stuff... If you really want that behaviour you might try something like

```
some_mount:
  cmd.run:
    - name: mount -t nfs -o etc /bla /bla
    - bg: True
```

You'll lose the ability to check what it did though
