### ISSUE TITLE
win_lgpo matches multiple policies due to startswith()

### ISSUE THREAD

**Issue by dafyddj** [saltstack/salt#42279]
### Description of Issue/Question
I'm working with the Administrative Templates for Office 2016 (available [here](https://www.microsoft.com/en-us/download/details.aspx?id=49030)) and I'm unable to set a particular policy and receive what I believe is an erroneous message.
```
----------
          ID: lgpo_macros
    Function: lgpo.set
      Result: False
     Comment: ADML policy name "Trusted Location #1" is used as the display name for multiple policies.  These policies
matched: Microsoft Office 2016\Security Settings\Trust Center\Trusted Location #1, Microsoft Word 2016\Word Options\Secu
rity\Trust Center\Trusted Locations\Trusted Location #1, Microsoft Office 2016\Security Settings\Trust Center\Trusted Lo
cation #1, Microsoft Word 2016\Word Options\Security\Trust Center\Trusted Locations\Trusted Location #1, Microsoft Offic
e 2016\Security Settings\Trust Center\Trusted Location #1, Microsoft Word 2016\Word Options\Security\Trust Center\Truste
d Locations\Trusted Location #1, Microsoft Office 2016\Security Settings\Trust Center\Trusted Location #1, Microsoft Wor
d 2016\Word Options\Security\Trust Center\Trusted Locations\Trusted Location #1, Microsoft Office 2016\Security Settings
\Trust Center\Trusted Location #1, Microsoft Word 2016\Word Options\Security\Trust Center\Trusted Locations\Trusted Loca
tion #1, Microsoft Office 2016\Security Settings\Trust Center\Trusted Location #1, Microsoft Word 2016\Word Options\Secu
rity\Trust Center\Trusted Locations\Trusted Location #1, Microsoft Office 2016\Security Settings\Trust Center\Trusted Lo
cation #1, Microsoft Word 2016\Word Options\Security\Trust Center\Trusted Locations\Trusted Location #1, Microsoft Offic
e 2016\Security Settings\Trust Center\Trusted Location #1, Microsoft Word 2016\Word Options\Security\Trust Center\Truste
d Locations\Trusted Location #1, Microsoft Office 2016\Security Settings\Trust Center\Trusted Location #1, Microsoft Wor
d 2016\Word Options\Security\Trust Center\Trusted Locations\Trusted Location #1, Microsoft Office 2016\Security Settings
\Trust Center\Trusted Location #1, Microsoft Word 2016\Word Options\Security\Trust Center\Trusted Locations\Trusted Loca
tion #1, Microsoft Office 2016\Security Settings\Trust Center\Trusted Location #1, Microsoft Word 2016\Word Options\Secu
rity\Trust Center\Trusted Locations\Trusted Location #1, Microsoft Office 2016\Security Settings\Trust Center\Trusted Lo
cation #1, Microsoft Word 2016\Word Options\Security\Trust Center\Trusted Locations\Trusted Location #1.  You can utiliz
e these long names to specify the correct policy
```
The bottom of the message says `You can utilize these long names to specify the correct policy` but I already am using a long name, as can be seen from my sls file.

The debug log shows more detail about the multiple matches:
```
[DEBUG   ] found an ADML entry matching the string! {word16.Office.Microsoft.Policies.Windows}string -- {'id': 'L_Truste
dLoc01'}
[DEBUG   ] searching for displayName == $(string.L_TrustedLoc01)
[DEBUG   ] found an ADML entry matching the string! {word16.Office.Microsoft.Policies.Windows}string -- {'id': 'L_Truste
dLoc11'}
[DEBUG   ] searching for displayName == $(string.L_TrustedLoc11)
[DEBUG   ] found an ADML entry matching the string! {word16.Office.Microsoft.Policies.Windows}string -- {'id': 'L_Truste
dLoc13'}
[DEBUG   ] searching for displayName == $(string.L_TrustedLoc13)
[DEBUG   ] found an ADML entry matching the string! {word16.Office.Microsoft.Policies.Windows}string -- {'id': 'L_Truste
dLoc15'}
[DEBUG   ] searching for displayName == $(string.L_TrustedLoc15)
[DEBUG   ] found an ADML entry matching the string! {word16.Office.Microsoft.Policies.Windows}string -- {'id': 'L_Truste
dLoc17'}
[DEBUG   ] searching for displayName == $(string.L_TrustedLoc17)
[DEBUG   ] found an ADML entry matching the string! {word16.Office.Microsoft.Policies.Windows}string -- {'id': 'L_Truste
dLoc19'}
[DEBUG   ] searching for displayName == $(string.L_TrustedLoc19)
```
It appears to be matching "`Trusted Location #11`" and others (no idea why only odd numbers) the same as "`Trusted Location #1`" i.e. matching the start of the string. 
On further investigation, this behaviour was introduced in #38783.

### Setup
```
# policy.sls
lgpo_macros:                                                                                                                                                                     
  lgpo.set:
    - user_policy:
        "Microsoft Word 2016\\Word Options\\Security\\Trust Center\\Trusted Locations\\Trusted Location #1":                                                                     
          L_Pathcolon: C:\Program Files (x86)\                                                                                             
          L_Descriptioncolon: Allow something
          L_Allowsubfolders: False
```

### Steps to Reproduce Issue

1. Copy word16.admx and word16.adml from the downloaded administrative templates to **C:\Windows\PolicyDefinitions** and **C:\Windows\PolicyDefinitions\en-US** respectively
2. Run `salt-call.bat -l debug state.apply policy`

It's also possible to demonstrate the problem from a Linux/Mac command line:
```
$ xmllint --xpath '//*[starts-with(text(), "Trusted Location #1") and @*[local-name() = "id"]]' word16.adml 
<string id="L_TrustedLoc01">Trusted Location #1</string><string id="L_TrustedLoc10">Trusted Location #10</string><string id="L_TrustedLoc11">Trusted Location #11</string><string id="L_TrustedLoc12">Trusted Location #12</string><string id="L_TrustedLoc13">Trusted Location #13</string><string id="L_TrustedLoc14">Trusted Location #14</string><string id="L_TrustedLoc15">Trusted Location #15</string><string id="L_TrustedLoc16">Trusted Location #16</string><string id="L_TrustedLoc17">Trusted Location #17</string><string id="L_TrustedLoc18">Trusted Location #18</string><string id="L_TrustedLoc19">Trusted Location #19</string>
$ xmllint --xpath '//*[starts-with(text(), "Trusted Location #3") and @*[local-name() = "id"]]' word16.adml 
<string id="L_TrustedLoc03">Trusted Location #3</string>
```

### Versions Report
```
PS C:\Users\vagrant> C:\salt\salt.bat --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 8.1
         system: Windows
        version: 8.1 6.3.9600  Multiprocessor Free
```

**Comment by Ch3LL** [comment]
@dafyddj the PR you refered to as adding this behavior is not in the 2016.11 code. It will be in hte new nitrogen code though. If you add that PR to your minion does it work?

**Comment by lomeroe** [comment]
@dafyddj 
A quick glance at the admx/adml files makes me believe it is b/c the policy IDs are the same across the different admx files (for example, L_TrustedLoc01 exists in multiple admx files [word16.admx, proj16.admx, etc]), so even though you are using the "long name", it can't resolve it back to a unique policy (so the error is slightly misleading).  It was something I thought may happen, but I had no duplicate IDs across any admx files, so it isn't accounted for.

I would anticipate if you used this sls, it would return an error "ADMX policy name/id ... is used in multiple ADMX files":
```
# policy.sls
lgpo_macros:                                                                                                                                                                     
  lgpo.set:
    - user_policy:
        L_TrustedLoc01:                                                                     
          L_Pathcolon: C:\Program Files (x86)\                                                                                             
          L_Descriptioncolon: Allow something
          L_Allowsubfolders: False
```

@Ch3LL #39090 is the back port to 2016.11 for the PR referenced.

**Comment by dafyddj** [comment]
@lomeroe you're right, if I use the single admx, word16.admx, the short policy ID works. However, if I add in another, e.g. office16.admx, it fails with:
`[ERROR   ]  ADMX policy name/id "{0}" is used in multiple ADMX files`

So, given these Office templates are meant to be used together, is there any intention in getting this to work?

**Comment by lomeroe** [comment]
Almost (or possibly all) of the xpath searches use searches that ignore the namespace.  Modifying the search to consider the namespace *should* get it working (since the namespaces are kept intact when consuming all the xml data).  I'll try to get you something to test in the near future.

**Comment by lomeroe** [comment]
@dafyddj Try out this: https://github.com/lomeroe/salt/blob/fix_42279/salt/modules/win_lgpo.py

Let me know how it works for you.  My tests all came back good...

**Comment by dafyddj** [comment]
Hi @lomeroe, thanks for this.

Although the error message is no longer triggered, there is a problem.
The following policy is placed in the wrong location:
```
lgpo_macros:
  lgpo.set:
    - adml_language: en-GB
    - user_policy:
        "Microsoft Word 2016\\Word Options\\Security\\Trust Center\\Trusted Locations\\Trusted Location #1":
          L_Pathcolon: C:\Program Files (x86)\
          L_Descriptioncolon: Allow something
          L_Allowsubfolders: False
          L_Datecolon: 01/01/2017
```
It's written to the registry here:

```
HKCU\software\policies\microsoft\office\16.0\common\security\trusted locations\all applications\location1
```
and can be seen in gpedit under 
```
User Configuration\Administrative Templates\Microsoft Office 2016\Security Settings\Trust Center
``` 
rather than 
```
User Configuration\Administrative Templates\Microsoft Word 2016\Word Options\Security\Trust Center\Trusted Locations"
```
