### ISSUE TITLE
Multiple gitfs repositories from different config files are not working together

### ISSUE THREAD

**Issue by jdonofrio728** [saltstack/salt#42338]
### Description of Issue/Question
This may be a misunderstanding on my part but I am seeing inconsistent behaviors when I setup multiple gitfs repositories in separate files versus a single config file.

I would expect that salt would function the same regardless if I have the configuration all in 1 file, or in multiple files.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

There are two git repositories referenced here. The "salt-top" contains only a top.sls file in the root of the respository as recommended in documentation. The "rhel7-base" repository contains some states that I am referencing from the top.sls file in the first repository.

salt-top git:
```
.
└── top.sls
```

rhel7-base:
```
.
├── rhel7-base.json
├── salt
│   ├── cis
│   │       └── init.sls
│   ├── logrotate
│   │   └── init.sls
│   └── ntpd
│       └── init.sls
└── saltstack.repo
```

Working test 1:
/etc/salt/minion:
```
fileserver_backend:
  - git
gitfs_provider: pygit2
gitfs_remotes:
  - http://ngp-bitbucket/scm/~jdonofrio/salt-top.git:
    - insecure_auth: True
    - base: master
  - http://ngp-bitbucket/scm/~jdonofrio/rhel7-base.git:
    - root: salt
    - insecure_auth: True
    - base: master
```
Then run: 
```salt-call --local -l debug state.highstate test=True```
This works as expected.

Broken test:
/etc/salt/minion:
```
fileserver_backend:
  - git
gitfs_provider: pygit2
```
/etc/salt/minion.d/salt-top.conf
```
gitfs_remotes:
  - http://ngp-bitbucket/scm/~jdonofrio/salt-top.git:
    - insecure_auth: True
    - base: master
```
/etc/salt/minion.d/rhel7-base.conf
```
gitfs_remotes:
  - http://ngp-bitbucket/scm/~jdonofrio/rhel7-base.git:
    - root: salt
    - insecure_auth: True
    - base: master
```
Then run:
```
salt-call --local -l debug state.highstate test=True
```
This will fail with output:
```
local:
    Data failed to compile:
----------
    No matching sls found for 'cis' in env 'base'
----------
    No matching sls found for 'logrotate' in env 'base'
----------
    No matching sls found for 'ntpd' in env 'base'
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

See above section

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
[root@test salt]# salt-call --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
