### ISSUE TITLE
Windows minion - Wrong release number

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#42342]
### Description of Issue/Question
Checking for correct release number in 2017.7.0 Windows packages it shows wrong release number for Windows 2008 and 2012. It shows `release: UNKServer`.
The other Windows OS's shows correct release, only 2008 and 20012 that shows the wrong one.

### Setup
Set up Windows Environment.

### Steps to Reproduce Issue
Run `test.versions_report` and look under `System Version`.
```
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: UNKServer
             system: Windows
            version: UNKServer 6.2.9200 SP0 Multiprocessor Free
```
### Versions Report
```
    Salt Version:
               Salt: 2017.7.0
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.2
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: UNKServer
             system: Windows
            version: UNKServer 6.2.9200 SP0 Multiprocessor Free
```
