### ISSUE TITLE
Salt pillarenv problem with slack engine

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#42357]
### Description of Issue/Question
In multi-pillar environment when I try to call a state from slack, pillarenv is resolved always with the same environment.
### Setup
/etc/salt/master:
```
pillar_roots:
  base:
    - /srv/pillar
  prod1:
    - /srv/pillar/prod1
  prod2:
    - /srv/pillar/prod2

```
Pillar in /srv/pillar/prod1
```
test: prod1
```
Pillar in /srv/pillar/prod2
```
test: prod2
```
Engine
```
engines:
  - slack:
      token: 'xx-xx-xx'
      control: True
      valid_commands:
          - testing
      aliases:
          testing:
             cmd: state.apply test.test pillarenv=prod1 target=linux
```
test.sls:
```
#!pyobjects

Cmd.run('echo env: '+pillar('test'))
```
Result when I try to call state from slack:
```
{
 "linux_server": {
  "cmd_|-echo env: prod2_|-echo env: prod2_|-run": {
   "__id__": "echo env: prod2", 
   "__run_num__": 0, 
   "changes": {
    "pid": 19053, 
    "retcode": 0, 
    "stderr": "", 
    "stdout": "env: prod2"
   }, 
   "comment": "Command \"echo env: prod2\" run", 
   "duration": 14.912, 
   "name": "echo env: prod2", 
   "result": true, 
   "start_time": "14:52:07.703039"
  }
 }
}
```

The result is the same for all pillar environment used in slack aliases. When I try to list pillar items from shell, the result, for different environment, is correct.

Any advices?

Thanks
### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
