### ISSUE TITLE
Discrepancy between running (custom) module on CLI vs. in SLS file.

### ISSUE THREAD

**Issue by absolutejam** [saltstack/salt#42385]
### Description of Issue/Question

I'm having a really weird issue, where I am getting different results between running a (custom) module manually, via. the CLI, vs. in a .sls file.

So, the custom module is here https://hastebin.com/gidexarupi.py. It's not perfect, but it works for its intended purpose and I've tidied it up somewhat since I posted it.

Basically, I use it to acquire a list of folders in a path, then match the folders up with a pillar entry (The main focus being the 'nodegroups' pillar value). This allows me to get a list of folders that are  relevant to a minion and then copy the contents to the minion. 

My CLI example is  
`salt 'minion' utils.match_config_to_dir 'nodegroups' 'sensu/_check_scripts'`

This looks in the folder `salt://sensu/_check_scripts` and a subsection of the subfolders inside are **winservers**, **domaincontrollers**, **fileservers**, (etc.)

And my example minion only returns a list containing **winservers** (As that's the only nodegroup it is a member of at the moment).

However, if I include this in a state, such as https://hastebin.com/pobifebiki.bash, it correctly identifies **winservers** but also identifies **domaincontrollers** - But I can't for the life of me figure out why!

I've also checked the pillar with:
`{{ salt['pillar.get']('nodegroups') }}`
and it only returns **winservers** - So I'm not sure how it's picking up the **domaincontrollers** folder too.

Obviously my first stop was in believing my custom module was shoddy, but I'm mostly confused at the discrepancy between CLI and SLS file output.

### Versions Report

Master:
```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.25.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.25.1
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-78-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Minion (Windows 2012 R2):
```
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
 ```

**Comment by garethgreenaway** [comment]
Looking at your custom module and the state file, is the expectation that ` sensu.check_scripts_root` is a pillar value?

**Comment by absolutejam** [comment]
Yeah, sorry. I've posted this in the IRC, on Salt-users and now here so I'm not sure which bits of info are missing!

The `sensu.check_scripts_root` exists for the minion. The custom module actually allows either grains or pillars, but the default (and what i'm using in this example) is a Pillar -`nodegroups` to be precise.

And an excerpt from my `/etc/salt/master.d/nodegroups.conf`
```
extension_modules: /srv/salt/ext
ext_pillar:
  - nodegroups:
      pillar_name: 'nodegroups'

nodegroups:
  winservers:
    - 'G@os_family:Windows'
```
