### ISSUE TITLE
salt-minion restart   top.sls  stop working  2017.7

### ISSUE THREAD

**Issue by ywgx** [saltstack/salt#42410]
### Description of Issue/Question

when  salt-minion restart  ,   the  master  top.sls  run ; but  when update to salt 2017.7 , stop working

**Comment by do3meli** [comment]
we also experience top.sls problems with 2017.7 release. when we accepted new minion keys and did a `state.highstate test=true` we usually got the bellow message with 2016.11 release
```
brand-new-test-minion:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No states found for this minion
     Changes:   
```
that then allowed us to let the host create in foreman. now with the 2017.7 release a `state.highstate test=true` on a brand new minion returns the below:
```
brand-new-test-minion:
    Minion did not return. [No response]
```
this unfortunately does then not allow us to upload a report to foreman which in the end triggers a host creation in foreman.
