### ISSUE TITLE
OrderedDict pillar data on master becomes unordered dict data on minion - have cause and solution

### ISSUE THREAD

**Issue by wilminator** [saltstack/salt#42440]
## Description of Issue/Question
Pillar data is ordered on master, but becomes unordered on minion.  This is seen by users when Jinja templates render dictionary based data out of the expected order on minions.  This was present in 2016.11.5 and is present in 2017.07.0

This example uses a modified version of formula-salt by blunix [https://github.com/blunix/formula-ssh](https://github.com/blunix/formula-ssh)

### /srv/salt/top.sls:
```
base:
  "*":
    - ssh.server
```

### /srv/salt/ssh/server/__init__.sls:
```
{% from "ssh/server/map.jinja" import ssh_info with context %}
{% from "ssh/server/map.jinja" import ssh_config with context %}

ssh_server_package:
  pkg.installed:
    - name: {{ ssh_info.server.package }}

ssh_server_sshd_config:
  file.managed:
    - name: /etc/ssh/sshd_config
    - source: salt://ssh/server/files/sshd_config.jinja2
    - template: jinja
    - context:
        config: {{ ssh_config.server.config }}
    - user: root
    - group: root
    - mode: 600

ssh_server_service:
  service.running:
    - name: {{ ssh_info.server.service }}
    - watch:
      - file: ssh_server_sshd_config
      - pkg: ssh_server_package
```

### /srv/salt/ssh/server/map.jinja:
```
{% set ssh_info = salt['grains.filter_by'] ({
    'Debian': {
        'server': {
            'package': 'openssh-server',
            'service': 'sshd',
            },
        },
    'RedHat': {
        'server': {
            'package': 'openssh-server',
            'service': 'sshd',
            },
        },
    })
%}
{% set ssh_config = salt['pillar.get']('ssh') %}
```

### /srv/salt/ssh/server/files/sshd_config.jinja2:
```
# This file is managed by Saltstack at {{ source }}
# DO NOT EDIT

{% for key, value  in config.items() %}
{%- if value is list %}
{%- for item in value %}
{{ key }} {{ item }}
{%- endfor %}
{%- else %}
{{ key }} {{ value }}
{%- endif %}
{%- endfor %}
```

### /srv/pillar/top.sls:
```
base:
  "*":
    - ssh
```

### /srv/pillar/ssh.sls:
```
ssh:
  server:
    config:
      Port: 22
      AddressFamily: any
      ListenAddress:
        - 0.0.0.0
        - "::"
      Protocol: 2

      HostKey:
        - /etc/ssh/ssh_host_rsa_key
        - /etc/ssh/ssh_host_ecdsa_key
        - /etc/ssh/ssh_host_ed25519_key

      KeyRegenerationInterval: 1h
      ServerKeyBits: 1024

      RekeyLimit: default none

      SyslogFacility: AUTHPRIV
      LogLevel: INFO

      LoginGraceTime: 2m
      PermitRootLogin: 'no'
      StrictModes: 'yes'
      MaxAuthTries: 6
      MaxSessions: 10

      RSAAuthentication: 'yes'
      PubkeyAuthentication: 'yes'

      AuthorizedKeysFile: .ssh/authorized_keys

      AuthorizedPrincipalsFile: none

      AuthorizedKeysCommand: none
      AuthorizedKeysCommandUser: nobody

      RhostsRSAAuthentication: 'no'
      HostbasedAuthentication: 'no'
      IgnoreUserKnownHosts: 'no'
      IgnoreRhosts: 'yes'

      PermitEmptyPasswords: 'no'
      PasswordAuthentication: 'yes'

      ChallengeResponseAuthentication: 'no'

      KerberosAuthentication: 'no'
      KerberosOrLocalPasswd: 'yes'
      KerberosTicketCleanup: 'yes'
#      KerberosGetAFSToken: 'no'
      KerberosUseKuserok: 'yes'

      GSSAPIAuthentication: 'no'
      GSSAPICleanupCredentials: 'no'
      GSSAPIStrictAcceptorCheck: 'yes'
      GSSAPIKeyExchange: 'no'
      GSSAPIEnablek5users: 'no'

      UsePAM: 'yes'

      AllowAgentForwarding: 'yes'
      AllowTcpForwarding: 'no'
      GatewayPorts: 'no'
      X11Forwarding: 'no'
      X11DisplayOffset: 10
      X11UseLocalhost: 'yes'
      PermitTTY: 'yes'
      PrintMotd: 'yes'
      PrintLastLog: 'yes'
      TCPKeepAlive: 'yes'
      UseLogin: 'no'
      UsePrivilegeSeparation: sandbox
      PermitUserEnvironment: 'no'
      Compression: delayed
      ClientAliveInterval: 0
      ClientAliveCountMax: 3
      ShowPatchLevel: 'no'
      UseDNS: 'yes'
      PidFile: /var/run/sshd.pid
      MaxStartups: 10:30:100
      PermitTunnel: 'no'
      ChrootDirectory: none
      VersionAddendum: none

      Banner: none

      AcceptEnv:
        - "LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES"
        - "LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT"
        - "LC_IDENTIFICATION LC_ALL LANGUAGE"
        - "XMODIFIERS"

      Subsystem:
        - "sftp /usr/libexec/openssh/sftp-server"

    default:
      SSHD_OPTS: ''
```

## Steps used to reproduce Issue
1. Install salt-master and salt minion on CentOS7 computer named "salt" using directions located at [https://repo.saltstack.com/#rhel](https://repo.saltstack.com/#rhel).
2. Create above configuration files.
3. Start the salt-master and salt-minion services then add the minion's key.
4. Run ```salt-call state.apply test=True``` to gauge new sshd_config file.  Note that the first items in the pillar are Port, AddressFamily, and ListenAddress, but the generated file would not match the order listed in the pillar.

## Root cause analysis
I dug through and confirmed that at least on the master that OrderedDicts were being passed internally.  I discovered that once the data structure hit the Serial.dumps method on the master and was transmitted to the minion's Serial.loads method, the mapping was switched to a standard dict object.

Rooting through the msgpack library, I found that it was encoding the OrderedDict on the master as a mapping, then decoding the mapping on the minion as a dict.  The library (at least msgpack-python) was not keeping the actual object type through the encoding and decoding process.

To fix this, I made the following changes in payload.py:
- Imported the OrderedDict object from salt.utils.odict 
- Edited the two msgpack.loads calls in Serial.loads to pass object_pairs_hook=OrderedDict so that the dictionary used when decoded would always be ordered.

This will have the side effect of always retaining dictionary order and the extra overhead associated with OrderedDict over dict, but this will cause pillar data rendering to work as expected.

### odict.patch
```
diff --git "a/C:\\Users\\mwilmes\\AppData\\Local\\Temp\\TortoiseGit\\payload-2fb986f.000.py" "b/C:\\Scripts\\salt\\salt\\payload.py"
index 1235a2e8b5..99446ace32 100644
--- "a/C:\\Users\\mwilmes\\AppData\\Local\\Temp\\TortoiseGit\\payload-2fb986f.000.py"
+++ "b/C:\\Scripts\\salt\\salt\\payload.py"
@@ -18,6 +18,7 @@ import salt.crypt
 import salt.transport.frame
 from salt.exceptions import SaltReqTimeoutError
 from salt.utils import immutabletypes
+from salt.utils.odict import OrderedDict
 
 # Import third party libs
 import salt.ext.six as six
@@ -134,9 +135,9 @@ class Serial(object):
                 # Due to this, if we don't need it, don't pass it at all so
                 # that under Python 2 we can still work with older versions
                 # of msgpack.
-                ret = msgpack.loads(msg, use_list=True, encoding=encoding)
+                ret = msgpack.loads(msg, use_list=True, encoding=encoding, object_pairs_hook=OrderedDict)
             else:
-                ret = msgpack.loads(msg, use_list=True)
+                ret = msgpack.loads(msg, use_list=True, object_pairs_hook=OrderedDict)
             if six.PY3 and encoding is None and not raw:
                 ret = salt.transport.frame.decode_embedded_strs(ret)
         except Exception as exc:
```

## Versions Report
[root@salttest srv]# salt --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
