### ISSUE TITLE
file.symlink copy a file instead of creating a symlink

### ISSUE THREAD

**Issue by Tamaradmin** [saltstack/salt#42446]
I'm using the following code to create a sym link:
```
bamboo-create-init-file{{ agent_id }}:
  file.symlink:
    - name: /etc/init.d/{{ bamboo_agent }}
    - target: {{ bamboo_home }}/bin/bamboo-agent.sh
    - force: True
    - require:
      - file: bamboo-jar{{ agent_id }}
```

When high-stating the server, it shows that it's working correctly
[user@saltserver bamboo]$ salt 'MyServer' state.highstate --state_verbose=false

----------
          ID: bamboo-create-init-file1
    Function: file.symlink
        Name: /etc/init.d/bamboo-agent1
      Result: True
     Comment: Created new symlink /etc/init.d/bamboo-agent1 -> /opt/bamboo-agent-home1/bin/bamboo-agent.sh
     Started: 08:46:14.989621
    Duration: 2.229 ms
     Changes:   
              ----------
              new:
                  /etc/init.d/bamboo-agent1

but what I got is a copy of the file instead of a symlink
[root@<myServer> init.d]# ll bamboo-agent1
-rw-r--r-- 1 <Myuser> <MyGroup> 15175 21. Jul 08:56 bamboo-agent1

Is there a known issue regarding that in centos7
[root@MyServer init.d]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)
