### ISSUE TITLE
allow pillar files to 'include'/load other pillar files.

### ISSUE THREAD

**Issue by inthecloud247** [saltstack/salt#4244]
A few times in the last few months I've wanted to have pillar values that I could 'include' or load into my pillar files. The problem is that the pillar dict doesn't seem to be available at all until the pillar has completely finished loading, and pillar files don't seem to be able to include others.

One example: I have a live_instances.sls yaml file that contains a list of all my servers. I need to load this live_instances.sls file and only add to the pillar the servers that match a regex on their fqdn.

live_instances.sls:

``` yaml
aws:
  zebra-staging.test.net:
    id: i-3e95670c
    image: null
    private_ips:
    - 10.252.178.30
    public_ips:
    - 54.243.237.177
    size: null
    state: RUNNING
  yak-staging.test.net:
    id: i-2382ba10
    image: null
    private_ips:
    - 10.248.46.125
    public_ips:
    - 54.245.99.206
    size: null
    state: STOPPED
```

server_status.sls:

``` mako|yaml

include:
  - live_instances.sls

servers:
% for server in pillar['aws']:
  % if pillar['aws']['server']['state'] == 'RUNNING':
  ${server}:
    state: ${pillar['aws']['server']['state']}
  % endif  
% endfor
```

I guess this can be accomplished currently by natively including the pillar files by using your templating language such as mako or jinja, but that seems like a hack and salt should be able to handle this natively.

I thought that maybe instad of allowing 'includes', it might be a better idea to create a 'high pillar' or some kind of pillar that is loaded before the main pillar begins to load so that the dict is available. Either way would work.
