### ISSUE TITLE
pip_state cannot find system pip on Windows

### ISSUE THREAD

**Issue by carlpett** [saltstack/salt#42488]
### Description of Issue
`pip_state` cannot find or use the pip binary that is bundled with Salt on Windows. Even pointing it out with  the `bin_env` parameter does not work.

### Setup
Without specifying pip path:
```sls
install-python-package:
  pip.installed:
    - name: package-name

=>

Error installing 'package-name': Could not find a `pip` binary
```

Pointing out the bundled pip:
```sls
install-python-package:
  pip.installed:
    - name: package-name
    - bin_env: C:/salt/bin/Scripts/pip.exe

=>

Error installing 'package-name': 
```

Note that no error is actually returned here

### Versions Report
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
```

**Comment by phsteve** [comment]
Looks like it's a path issue and is present on both 2016.11 and 2017.7. I've done some poking around and this section of code: https://github.com/saltstack/salt/blob/2fb986f5ca8aaeb7930096d2d087ee022eb1e831/salt/modules/pip.py#L122-L131 can't find `pip` on the path and so `which_result` winds up being `None`. Here's a demonstration that adding `c:\salt\bin\Scripts` to the path allows `cmd.which_bin` to find the correct `pip`:

```
C:\windows\system32>salt-call cmd.which_bin ['pip'] --local
local:
    None

C:\windows\system32>set PATH=%PATH%;c:\salt\bin\Scripts

C:\windows\system32>salt-call cmd.which_bin ['pip'] --local
local:
    c:\salt\bin\Scripts\pip.EXE
```

Looks like the only directory the exe installer adds to the path is `c:\salt`. Does it also need to add the `Scripts` dir?

**Comment by phsteve** [comment]
@carlpett I figured out how to get this to work without modifying the path. Try adding `- cwd: 'C:\salt\bin\Scripts'` to your state, like this:

```
install-python-package:
  pip.installed:
    - name: package-name
    - bin_env: C:\salt\bin\Scripts\pip.exe
    - cwd: 'C:\salt\bin\Scripts'
```

The [docs also mention this behavior](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pip.html#windows-support), so it may not be a bug at all, though the missing error probably is.

>"If [bin_env or cwd] are omitted, it will default to the local installation of python. If python is not installed locally it will fail saying it couldn't find pip."

Having the installer add the `Scripts` dir to the path could be a bad idea since a user may expect `pip.installed` to modify a local python install rather than the one bundled with Salt, in addition to muddying the path with another `pip.exe`. In any case, having to add both non-obvious parameters every time we want to install a pip package to Salt's python is clunky.

Instead, perhaps adding a parameter like `use_salt_pip` that defaults to `False` would make the distinction clearer?
