### ISSUE TITLE
Solution/Documentation for different python versions?

### ISSUE THREAD

**Issue by bradpoulton** [saltstack/salt#42525]
### Description of Issue/Question
I was setting up gitfs backend server on two salt masters installed on Amazon Linux and CentOS 6. Both of these OSes have python 2.6 installed by default. I installed the salt master software from the respective official saltstack repos using yum install. Because the OSes had python 2.6 and the salt master used python 2.7 I ran into the issue of installing pygit2 with yum install and the salt master not able to see the newly installed package. Yum installed the package to the python2.6 installation so salt was not able to see the package. After searching the saltstack documentation, I was not able to find a solution from saltstack. The gitfs page (https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html) did not cover multiple python versions being present on the OS. My suggestion is for documentation on how to install new python modules into saltstack when the OS has a different python version. After some help from @basepi I was able to install GitPython via python27 setup.py install. I even tried to use pip, but that also installed the module to python 2.6. I would have preferred to install pygit2, but i was not able to find a tar.gz download of the source to get a setup.py file. 

### Steps to Reproduce Issue
install salt master via saltstack repo on centos 6 (or any linux distro with python 2.6 installed by default)
install pygit2 via yum 
run versions report and pygit2 does not show up as installed. 

### Versions Report

```
python --version
Python 2.6.9


salt --versions
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Sep  1 2016, 22:14:00)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.4.44-39.55.amzn1.x86_64
         system: Linux
        version: Not Installed
```
