### ISSUE TITLE
Reactor launching orchestration job is broken in 2017.7.0

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#42632]
### Description of Issue/Question
A simple reactor which launches an orchestration job to tell a minion to run highstate on connect, fails with 2017.7.0. 

### Setup
Master reactor
```
reactor:
  - 'salt/minion/*/start':
    - /srv/salt/reactor/minion_highstate.sls
```

Reactor file
```
sync_and_highstate:
  runner.state.orchestrate:
    - mods: orchestrations/new_minion
    - pillar:
        event_data: {{ data | json() }}
```

Orchestrate job
```
{% set data = salt.pillar.get('event_data') %}

sync_all:
  salt.function:
    - tgt: {{ data.id }}
    - name: saltutil.sync_all
    - kwarg:
        refresh: True

minion_highstate:
  salt.state:
    - tgt: {{ data.id }}
    - highstate: True
```

### Steps to Reproduce Issue
Results in a failure message on the event bus
```
salt/run/20170729070251023130/ret       {
    "_stamp": "2017-07-29T07:02:52.274140",
    "fun": "runner.state.orchestrate",
    "fun_args": [
        "orchestrations/new_minion"
    ],
    "jid": "20170729070251023130",
    "return": {
        "data": {
            "ip-10-241-208-27.ec2.internal_master": [
                "Rendering SLS 'base:orchestrations/new_minion' failed: Jinja variable 'str object' has no attribute 'id'"
            ]
        },
        "outputter": "highstate",
        "retcode": 1
    },
    "success": false,
    "user": "Reactor"
}
```

### Versions Report
```
# salt --versions-report
/usr/lib64/python2.7/site-packages/cffi/model.py:526: UserWarning: 'git_checkout_notify_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
/usr/lib64/python2.7/site-packages/cffi/model.py:526: UserWarning: 'git_merge_tree_flag_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.4
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by maennlse** [comment]
looks like the reactors slightly changed from 2016 to 2017 version...
https://docs.saltstack.com/en/latest/topics/reactor/#advanced-state-system-capabilities

Your Reactor file
```
sync_and_highstate:
  runner.state.orchestrate:
    - mods: orchestrations/new_minion
    - pillar:
        event_data: {{ data | json() }}
```
should be changed to
```
sync_and_highstate:
  runner.state.orchestrate:
    - mods: orchestrations/new_minion
    - kwarg:
      pillar:
        event_data: {{ data | json() }}
```

we also ran into the following problem, after upgrading: https://github.com/saltstack/salt/issues/42403

this bug is already fixed, but not packaged, yet.
we manually patched the file on the salt-master: https://github.com/saltstack/salt/pull/42433/commits/17f347123a5bf2c2e183ec1664d6bb16784c5f69


hope that helps.

greetings,
Sebastian

**Comment by mchugh19** [comment]
Woah! Thanks for the update! You are correct that the latest reactor docs do show the new kwarg key, but this is a major change that is not backward compatible, and isn't mentioned in the release notes. Can we please get this called out in the release notes?

**Comment by gtmanfred** [comment]
Not using kwarg was deprecated in nitrogen, in earlier versions there was a deprecation message if it was not used.

https://github.com/saltstack/salt/blob/2016.11/salt/client/mixins.py#L384

and now it logs a critical message that all of them should be put under kwarg.
https://github.com/saltstack/salt/blob/2017.7/salt/client/mixins.py#L375

I do not see a reason that it couldn't also be added to the release docs.

Daniel

**Comment by mchugh19** [comment]
Am I doing something crazy. After adding in the newly documented kwargs, I'm seeing errors on the event bus and it seems to be missing the mods key

```
salt/run/20170801123757624163/new       {
    "_stamp": "2017-08-01T12:37:57.626095",
    "fun": "runner.state.orchestrate",
    "fun_args": [
        {
            "pillar": {
                "event_data": {
                    "_stamp": "2017-08-01T12:37:56.857272",
                    "cmd": "_minion_event",
                    "data": "Minion minionid started at Tue Aug  1 13:38:01 2017",
                    "id": "minionid",
                    "pretag": null,
                    "tag": "salt/minion/minionid/start"
                }
            }
        }
    ],
    "jid": "20170801123757624163",
    "user": "Reactor"
}
salt/run/20170801123757624163/ret       {
    "_stamp": "2017-08-01T12:37:57.627903",
    "fun": "runner.state.orchestrate",
    "fun_args": [
        {
            "pillar": {
                "event_data": {
                    "_stamp": "2017-08-01T12:37:56.857272",
                    "cmd": "_minion_event",
                    "data": "Minion minionid started at Tue Aug  1 13:38:01 2017",
                    "id": "minionid",
                    "pretag": null,
                    "tag": "salt/minion/minionid/start"
                }
            }
        }
    ],
    "jid": "20170801123757624163",
    "return": "Exception occurred in runner state.orchestrate: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 392, in _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: orchestrate() takes at least 1 argument (1 given)\n",
    "success": false,
    "user": "Reactor"
}
```

This is with a reactor file:
```
sync_and_highstate:
  runner.state.orchestrate:
    - mods: orchestrations.new_minion
    - kwarg:
        pillar:
          event_data: {{ data | json() }}
```
and orch file
```
{% set data = salt.pillar.get('event_data') %}

sync_all:
  salt.function:
    - tgt: {{ data.id }}
    - name: saltutil.sync_all
    - kwarg:
        refresh: True

minion_highstate:
  salt.state:
    - tgt: {{ data.id }}
    - highstate: True
```

**Comment by gtmanfred** [comment]
Hrm, yeah that looks weird.
Can you check the reactor like this?

```
sync_and_highstate:
  runner.state.orchestrate:
    - arg:
        - orchestrations.new_minion
    - kwarg:
        pillar:
          event_data: {{ data | json() }}
```


```
sync_and_highstate:
  runner.state.orchestrate:orchestrations.new_minion
    - kwarg:
        mods: orchestrations.new_minion
        pillar:
          event_data: {{ data | json() }}
```

Thanks for testing,
Daniel

**Comment by mchugh19** [comment]
Fantastic! Progress!

Both
```
sync_and_highstate:
  runner.state.orchestrate:
    - arg:
      - orchestrations.new_minion
    - kwarg:
        pillar:
          event_data: {{ data | json() }}
```
and
```
sync_and_highstate:
  runner.state.orchestrate:
    - kwarg:
        mods: orchestrations.new_minion
        pillar:
          event_data: {{ data | json() }}
```
worked! If this is the new format, this should very much be added to the release notes, documentation pages, and some unit tests ;)

Thanks all!
