### ISSUE TITLE
Salt getting killed on OpenBSD for calling pthread_join() in the child after fork()

### ISSUE THREAD

**Issue by viq** [saltstack/salt#42634]
### Description of Issue/Question
Recently OpenBSD in it's rthread library [added checking for pthread_join() in the child after fork()](https://github.com/openbsd/src/commit/a9128774a26980a02b10602a2f3fcb3c5930abee). This makes salt-minion crash.
Currently this check was disabled, but it will come back soon.

### Setup
Install salt on recent OpenBSD snapshot, connect to master.

### Steps to Reproduce Issue
Try to start salt-minion.

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.26.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 28 2017, 14:42:33)
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 6.1
         system: OpenBSD
        version: Not Installed
```
