### ISSUE TITLE
state.augeas

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#42642]
### Description of Issue/Question

It seems that the augeas state does not work in following example. The state does not seem to actually perform the operation.

```
salt minion state.apply kernel.linux.fstab
```

The augeas module works as expected.

```
salt -N linux augeas.remove '/files/etc/fstab/*[file="/tmp"]/opt[.="noexec"]'
```

### Setup

Running on CentOS 7

### Steps to Reproduce Issue

fstab.sls

```
remove-noexec-tmp:
  augeas.change:
    - lens: fstab
    - context: /files/etc/fstab
    - changes:
      - rm /files/etc/fstab/*[file="/tmp"]/opt[.="noexec"]
```

/etc/fstab

```
/dev/mapper/VolGroup00-tmp      /tmp        ext4    defaults,noexec,nosuid,nodev        1 1
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.3.8
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 1.0.1
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: 0.6.3
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by garethgreenaway** [comment]
Looking at the debugging information it looks like the issue is that the quotes are being stripped out of the command being sent along to the augeas module.  The example you have above works, but if you remove all the double quotes then it fails.  Looking more into this and hopefully adding a fix.

**Comment by githubcdr** [comment]
Thanks for the quick reply and fix @garethgreenaway!

**Comment by garethgreenaway** [comment]
@githubcdr The PR has been merged and the fix will be available in the next 2016.11 release as well as future releases.  I'm going to close out this issue, if the problem persists or if you find that the PR doesn't solve the problem please feel free to reopen this issue or a new one.  Thanks!

**Comment by amontalban** [comment]
Hey guys,

I'm having the following problem when using branch `2016.11` (Was working fine in `2016.11.6`):

```
                 ID: mysqlchk-service
           Function: augeas.change
             Result: False
            Comment: Error: Unable to save to file!
            Started: 11:34:27.961789
           Duration: 855.326 ms
            Changes:
 ```

This is my state:

```
mysqlchk-service:
  augeas.change:
    - lens: services.lns
    - context: /files/etc/services
    - changes:
      - ins service-name after service-name[last()]
      - set service-name[last()] "mysqlchk"
      - set "service-name[. = 'mysqlchk']/port" 9200
      - set "service-name[. = 'mysqlchk']/protocol" tcp
      - set "service-name[. = 'mysqlchk']/#comment" "MySQL HAProxy health check"
```

Any idea of how can I fix this up?

Thanks!

**Comment by rickh563** [comment]
ZD-1703

**Comment by cachedout** [comment]
@garethgreenaway Please see ZD-1703 for additional info on what still needs to be done.

**Comment by garethgreenaway** [comment]
PR submitted to revert changes.  Upon further investigation the original state file should be:
```
remove-noexec-tmp:
  augeas.change:
    - lens: fstab
    - context: /files/etc/fstab
    - changes:
      - rm '/files/etc/fstab/*[file="/tmp"]/opt[.="noexec"]'
```
For the augeas state to function correctly.  The one reported by @amontalban  should also include an unless conditional to avoid multiple attempts to add the line.  The python-augeas library doesn't handle this well.
