### ISSUE TITLE
Pkg.install reports failure despite succeeding

### ISSUE THREAD

**Issue by calebwoofenden** [saltstack/salt#42653]
### Description of Issue/Question
With some packages using the pkg.install module reports failure and returns an error code when the package actually successfully installed.

### Setup
I have noticed this happening with rubyinstaller_64 and chocolatey, as well as install packages I have written myself.

Here's an example, the output is fairly self-contradictory:

![capture28](https://user-images.githubusercontent.com/26581635/28796736-b0f310ee-760c-11e7-8102-1d97768735c6.PNG)

**Comment by gtmanfred** [comment]
@twangboy have you seen this before?

Thanks,
Daniel

**Comment by twangboy** [comment]
@calebwoofenden Things like this can happen when the software definition entries for `full_name` and `version` are not exactly as displayed by Add/Remove Programs. I'll take a deeper look later in the week. Could post the Software definitions for those packages? along with the state you're using to install them.

The software definition file is found (usually) in `/srv/salt/win/repo-ng/`. It might be under a git repo in that directory.

Also, what version of salt is this happening on?

**Comment by calebwoofenden** [comment]
@twangboy Thanks, I had the `full_name` and `version` fields slightly incorrect and it was causing that problem for the ones I wrote myself.

The above two packages are ones I wrote and we have in our repo, but we are making use of the ones that have already been written as much as possible. We ran into this issue with rubyinstaller_x64 and chocolatey packages found in the winrepo-ng:

![capture32](https://user-images.githubusercontent.com/26581635/28826287-927031f2-7697-11e7-8151-ce84c16799be.PNG)

This is running a pkg.install state with a bunch of other packages as well. Here's that state file:

```
install devworkstation packages:
  pkg.installed:
    - pkgs:
      - chocolatey
      - svn
      - git
      - rubyinstaller_x64
      - firefox
      - chrome
      - node.js
      - tortoise-git
      - tortoise-svn
```

Both of those install packages are kind of complicated and it seems like the name/version fields aren't being determined correctly.
