### ISSUE TITLE
docker_container.running network alias and link support

### ISSUE THREAD

**Issue by abulford** [saltstack/salt#42665]
### Description of Issue/Question
Currently there's limited support for network aliases and links when using the `docker_container.running` state.  The documentation says you can use the `links` property to "Link this container to another", but when inspecting the container which is created, only the `HostConfig.Links` property is populated.  When using user defined networks, I'm not sure what this actually does, in order to get the behaviour I needed (aliasing a container name for another container to use) I needed to set the `network_config` property, which isn't documented and doesn't seem to be fully supported by the state.

I was able to get what I needed with the following (stripped down) configuration:
```
container-which-requires-alias:
  docker_container.running:
    - name: container-which-requires-alias
    - image: an-image
    - network_mode: a-user-defined-network
    - links:
      - container-to-be-aliased: the-alias
    - networking_config:
        EndpointsConfig:
          a-user-defined-network:
            Links:
              - "container-to-be-aliased:the-alias"
```

I'm not sure if the first `links` property is actually doing anything useful for me, I suspect I could just remove it.

Alternatively, the container to be aliased can have the `Aliases` property set:
```
container-to-be-aliased:
  docker_container.running:
    - name: container-to-be-aliased
    - image: an-image
    - network_mode: a-user-defined-network
    - networking_config:
        EndpointsConfig:
          a-user-defined-network:
            Aliases:
              - "the-alias"
```

With both of these configurations, however, Salt doesn't pick up any changes in config, so won't re-create the container if this config is added, changed or removed.  This appears to be because the `compare_container` function in `dockermod.py` only compares the `Config` and `HostConfig` properties, not `NetworkConfig`, I guess because the network config gets set by Docker with IP addresses etc which aren't necessarily known before the container is started.

There are a few improvements which ideally would be made to help with these use cases:
* Document the `network_config` property, even if only in its current state, to make it easier for people to figure this stuff out without needing to delve into the code
* Improve the usage of the `links` attribute to cover also adding the `NetworkConfig` version of this variable to Docker, in the same way that using `--links` with the Docker CLI does
* Add an `aliases` attribute which adds aliases to the `NetworkConfig` option passed to Docker
* Modify the `compare_container` function so it also compares those elements of `NetworkConfig` which wouldn't cause problems, e.g. different IPs or hashes which could change between container creations

I'm creating this ticket rather than just trying to fix it myself and submit a PR because 1) I'm not sure I have the Python/Salt skill to do it effectively in any reasonable amount of time and 2) to get some feedback about it, to see whether I'm totally trying to do this the wrong way, if it's already been thought about, etc.

### Versions Report
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by garethgreenaway** [comment]
Pinging @terminalmage who has done a written a majority of the code in the latest docker module and state module.

**Comment by terminalmage** [comment]
To be honest, I am not familiar with advanced networking configuration in Docker, which may explain some of the shortcomings of the existing support. You're right about the container comparison stuff not being able to know the IP configuration ahead of time, though.

However, as I understand it, the current way of managing docker networks with Salt is to use the `docker_network.present` state, and assign it to the container from that state via the `containers` argument to that state. Indeed, if you look at the [docker-py docs](http://docker-py.readthedocs.io/en/stable/api.html#networks), the `connect_container_to_network` API function is used to attach a network to a container, and this is how the `docker_network.present` state handles attaching the network to the container. So, it seems to me that the correct way forward for this would be to add `links` and `aliases` to the `docker_network.present` state, and then pass them through when that state invokes `connect_container_to_network`. Doing it this way allows us to continue to manage networks and containers distinctly from one another.

**Comment by abulford** [comment]
Is that the standard way to join containers to a network, to specify the containers from the network state?  I hadn't realised, and have just been specifying the network from the container state, which is also possible.  It makes a lot more sense to me to do it this way because my containers rely on the network existing before they can do anything, so I need to have that network configured before I run any containers - I use a `require` requisite to ensure this is the case.

To me, it feels as though aliases and links are the concern of the container rather than the network, so would best be specified here.  This would also be more in-line with the way they're defined in Docker Compose files (see the [links](https://docs.docker.com/compose/compose-file/compose-file-v2/#links) and [aliases](https://docs.docker.com/compose/compose-file/compose-file-v2/#aliases) documentation).

**Comment by terminalmage** [comment]
@abulford I've implemented your use case as part of https://github.com/saltstack/salt/pull/44638, which will be part of the Oxygen release of Salt, due in January. You'll be able to do something like this:

```yaml
mycontainer:
  docker_container.running:
    - image: foo/bar:baz
    - networks:
      - mynet:
        - aliases:
          - alias1
          - alias2
        - links:
          - link1
          - link2
    - require:
      - docker_network: mynet
```

I'm going to go ahead and close this. Thanks for giving me a different perspective on this. To be honest, I had not been involved in developing the docker networking support, so I was not all that familiar with how it worked.
