### ISSUE TITLE
Can I do a global DNS change with salt?

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#42671]
### Description of Issue/Question

 I can see this module,

eth0:
  network.managed:
    - enabled: True
    - type: eth
    - proto: none
    - ipaddr: 10.1.0.1
    - netmask: 255.255.255.0
    - dns:
      - 8.8.8.8
      - 8.8.4.4
8><----

However I want to change the DNS settings only across 160servers.  Running the above minimalised as,

eth0:
  network.managed:
    - enabled: True
    - type: eth
    - dns:
      - 8.8.8.8
      - 8.8.4.4

and I end up with all the other unique settings removed, oopsie.

is there anyway inside of salt to only change the DNS lines? or do I just write a bash script to do it?

**Comment by gzcwnk** [comment]
Also can I set salt not to restart the network?  as I'd like to alter the machines, check the settings and reboot in the change window.

**Comment by gtmanfred** [comment]
unfortunately i do believe that you would need to provide the entire interface setup.

```
- noifupdown: True
```

You could try adding the above and I don't think it will restart the network.

It should be fairly easy to just grab the ip address from the eth0 interface and plug it into the state.
```
eth0:
  network.managed:
    - enabled: True
    - type: eth
    - noifupdown: True
    - proto: none
    - ipaddr: {{salt.network.ip_addrs(interface='eth0')|first}}
    - netmask: 255.255.255.0
    - dns:
      - 8.8.8.8
      - 8.8.4.4
```

I think this should work for you.

Thanks,
Daniel
