### ISSUE TITLE
Feature: support inline profile specification in etcd_mod state/module

### ISSUE THREAD

**Issue by wojciechwroblewski** [saltstack/salt#42677]
### Description of Feature request

Currently, `etcd_mod` requires profile specification in either master, minion configuration or via pillar. Mentioned objects have common issue - are meant to be used for static data. Unlike for example `redis_mod` state, there is no possibility to provide the configuration directly in state/module call.

In my scenario, I'm getting etcd endpoint addresses via salt mine, then save it as a minion configuration file containing etcd profile information. As https://github.com/saltstack/salt/issues/570 is not yet there, to apply new configuration a minion restart is required, which is quite troublesome - it forces applying highstate in two steps: setup minion configuration, then configure etcd. It would be way more convenient to pass that information as state parameter like that:

```
test-etcd:
  etcd.set:
    - name: /path/to/key
    - value: val
    - profile_inline:
        etcd.host: 127.0.0.1
        etcd.port: 2379
```

What do you think?

**Comment by gtmanfred** [comment]
I would like to see this work like the other modules, which you pass `connection_host` `connection_port` and it can be passed.

```
frank:
  mysql_user.present:
    - host: localhost
    - password: "bob@cat"
    - connection_user: someuser
    - connection_pass: somepass
    - connection_charset: utf8
```

https://github.com/saltstack/salt/blob/2017.7/salt/modules/mysql.py#L307

But i like the idea and am marking this as a feature request.  Would you mind submitting a PR?

Thanks!
Daniel
