### ISSUE TITLE
Service module and state fails on FreeBSD

### ISSUE THREAD

**Issue by cro** [saltstack/salt#42707]
### Description of Issue/Question

FreeBSD 11.1-RELEASE

```
root@fbsdssc:/usr/local/lib/python2.7/site-packages/salt/modules # salt-call --local service.start postfix
[ERROR   ] Command '/usr/sbin/jexec None /usr/sbin/service postfix onestart' failed with return code: 1
[ERROR   ] output: jexec: jail "None" not found
local:
    False
```

This machine has no jails at all--why would Salt try to execute the command in a jail named `"None"`?

### Versions Report

```
root@fbsdssc:/usr/local/lib/python2.7/site-packages/salt/modules # salt --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: 0.25.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.25.1
         Python: 2.7.13 (default, Jul 13 2017, 01:17:52)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.5

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 11.1-RELEASE
         system: FreeBSD
        version: Not Installed
```

**Comment by rallytime** [comment]
Closed via #42708

**Comment by dneades** [comment]
I ran into a similar problem as well, applying states to FreeBSD 11.1-RELEASE hosts via `salt-ssh` from both macOS and Linux clients. In my case, `service.running` states for various services all failed with errors along these lines:

```
----------
          ID: sshd
    Function: service.running
      Result: False
     Comment: The named service sshd is not available
     Started: 11:01:48.530488
    Duration: 10.552 ms
     Changes:
```

These states worked perfectly before upgrading to Salt 2017.7.0, were consistently broken with 2017.7.0, and worked perfectly again after I downgraded to Salt 2016.11.6.

With Salt 2017.7.0 installed, I tried applying the change in #42708 to my local Salt installation (from where I was running `salt-ssh`), but that seemed to have no effect and did not correct the problem. @rallytime: Would you have expected my locally applying #42708 to have fixed the problem? My only reason for asking is to make sure that this problem will definitely be fixed in the next Salt 2017.7.x release. Thanks in advance!
