### ISSUE TITLE
allow to manage remotes via git state functions

### ISSUE THREAD

**Issue by ChristianBeer** [saltstack/salt#42701]
### Description of Issue/Question
I have a use case where I want to make sure that a specific remote is present in a cloned git repo without making the remote the default or causing unnecessary changes. Currently this is not possible. I can add a second remote by doing something like this:
```
repository-create:
  git.latest:
    - name: "https://github.com/octocat/Spoon-Knife.git"
    - target: "/srv/test/repository/."
    - rev: master
    - branch: master

repository-add-remote:
  git.latest:
    - name: "https://github.com/ChristianBeer/Spoon-Knife.git"
    - target: "/srv/test/repository/."
    - remote: downstream
    - rev: master
    - branch: master
    - require:
      - git: repository-create
```
but this will make the last added remote the default remote and it will create two changes with every highstate because every `git.latest` state changes the remote.

I would like to have a way to ensure that a properly named remote exists without making it default. Of course one should also be able to delete remotes in such a way.

This is what it may look like (minimum signature):
```
def manage_remote(name,
           target=None,
           present=True,
           default=False,
           remote='origin',
**kwargs):
```
where if `present=True` it makes sure that `remote` exists in the repo and the URL is `name`, otherwise it deletes `remote` if it is not the last remote. `default` can be used to ensure that this remote always is the default without using `git.latest`.

**Comment by ChristianBeer** [comment]
Nevermind. I was using `git.latest` wrong. Here is a setup that actually works:
```
repository-create:
  git.latest:
    - name: "https://github.com/octocat/Spoon-Knife.git"
    - target: "/srv/test/repository/."
    - rev: master
    - branch: master

repository-add-remote:
  git.latest:
    - name: "https://github.com/ChristianBeer/Spoon-Knife.git"
    - target: "/srv/test/repository/."
    - remote: downstream
    - require:
      - git: repository-create
```
You need to omit the `rev` and `branch` argument in case you don't want to have the remote as default. Sorry for the noise.
