### ISSUE TITLE
Python on windows server 2012 r2 crashes when using archive.extracted

### ISSUE THREAD

**Issue by Jamie-BitFlight** [saltstack/salt#42726]
### Description of Issue/Question
The first time this gets run, it transfers the file and then python crashes.
The second time it runs, it extracts the file since the transfer has already completed and it has cached the zip file.

If i delete the cached file, it downloads it then crashes again.

the pillar value InstallDownload is `C:\installer\download`

my sls file
```
{% set version = "4.5.5.20" %}

unzip_application_{{ version }}:
  archive.extracted:
    - name: '{{pillar['InstallDownload']}}'
    - source: 'salt://formulas/apps/application_{{ version }}.zip'
    - keep: true
    - archive_format: zip
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.8.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.25.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.25.1
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-79-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
