### ISSUE TITLE
Ambiguity in using grains in pillar

### ISSUE THREAD

**Issue by rmarcinik** [saltstack/salt#42724]
### Description of Issue/Question
I am a bit confused with some behaviors of using jinja in pillar files, and trying to use a grains value.
Calling grains.get returns values from the master's minion's grains, whereas trying to get values from the grains dictionary correctly returns the targeted minion's values.
Custom grains also have some problems here, when used in jinja they do not show up, but when called from the commandline we can see they are present.

pillar file
```
testing:
  salt.grains.get: {{ salt.grains.get('host') }} {{ salt.grains.get('custom') }}
  salt['grains.get']: {{ salt['grains.get']('host') }} {{ salt['grains.get']('custom') }}
  grains[]: {{ grains['host'] }} {{ grains['custom'] }}
```
results from `salt minion pillar.get testing`, notice the custom grains are absent
```
minion:
    ----------
    grains[]:
        minion custom_value
    salt.grains.get:
        master
    salt['grains.get']:
        master
```
using salt-call on the master shows that the values do exist
```
salt-call grains.get custom
local:
  custom_value

```
### Versions Report
```
master:
    Salt Version:
               Salt: 2016.11.3

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.3.1611 Core
            machine: x86_64
            release: 3.10.0-327.22.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
So, for pillar data, you have to use {{grains['whatever']}} because what happens is we inject the minions grains values in the grains value when rendering pillar data, but the salt.grains.get actually calls the module with the master_minion which will return back the masters grains.

**Comment by garethgreenaway** [comment]
@rmarcinik To clarify, when you're seeing the results above you're setting the grains values for a separate minion that the one that is running on the master?

**Comment by rmarcinik** [comment]
I have updated the example to show that I am indeed running pillar.get against a minion that is separate from the master, and has a separate hostname. 

So as I understand there is a master_minion that returns the grains data for salt.pillar.get, but I am curious why those values dont show up in the pillar results.  Maybe this is two separate issues?
- salt.pillar.get does not query the minion grains data like I thought it would (and has in the past).
- the master_minion does not use the custom grains of a minion installed on the master

**Comment by rmarcinik** [comment]
Another strange thing I just noticed, because we have been using salt.pillar.get for a long time now, when I am on another master and do this same test I get:
```
-> salt lab_minion* pillar.get testing
lab_minion:
    ----------
    grains[]:
        lab_minion custom_value
    salt.grains.get:
        lab_minion custom_value
    salt['grains.get']:
        lab_minion custom_value
```
master version:
```
local:
    Salt Version:
               Salt: 2016.11.3

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.3.1611 Core
            machine: x86_64
            release: 3.10.0-514.10.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7.3.1611 Core
```
