### ISSUE TITLE
support for AIX chdev

### ISSUE THREAD

**Issue by bfilipek** [saltstack/salt#42740]
chdev can be used for setting system variables, for example increase the maximum number of processes allowed per user.
I think the some similar state for linux is sysctl.present.

Something information which parameter can be set by chdev:
https://www.ibm.com/support/knowledgecenter/en/ssw_aix_61/com.ibm.aix.cmds1/chdev.htm
https://abcofaix.wordpress.com/tag/chdev/

Example: increase the maximum number of processes allowed per user, need to be run:
```
chdev -l sys0 -a maxuproc=1000
```
it clould be:
```
chdev.present:
  - device: sys0
  - attribute: maxuproc
  - value: 1000
```
