### ISSUE TITLE
file.recurse exclude_pat doesn't work with "clean: true" anymore

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#42758]
### Setup

This is what we have in state:

```
{%- for dictionary in config.get('dictionaries', []) %}
/etc/clickhouse/{{ cluster }}/dictionaries/{{ dictionary }}:
  file.recurse:
    - source: salt://clickhouse/dictionaries/{{ dictionary }}
    - makedirs: true
    - clean: true
    - exclude_pat: config.xml
    - require_in:
      - file: /etc/clickhouse/{{ cluster }}/dictionaries
      - service: clickhouse.{{ cluster }}

/etc/clickhouse/{{ cluster }}/dictionaries/{{ dictionary }}/config.xml:
  file.managed:
    - source: salt://clickhouse/dictionaries/{{ dictionary }}/config.xml
    - makedirs: true
    - require_in:
      - file: /etc/clickhouse/{{ cluster }}/dictionaries/{{ dictionary }}
    - watch_in:
      - service: clickhouse.{{ cluster }}
{%- endfor %}
```

In 2016.11.4 this worked as expected: files are copied, then `config.xml` was copied. Then everything not mentioned is removed.

In 2017.7.0 this doesn't work as expected anymore: files are copied, then config.xml is copied. Then `config.xml` is removed.

### Steps to Reproduce Issue

1. Upgrade salt to 2017.7.0.
2. Run the state.
2. Where did all the configs go?

### Versions Report

Broken:

```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.1
         locale: UTF-8
        machine: x86_64
        release: 4.9.34-cloudflare-2017.6.5
         system: Linux
        version: debian 9.1
```

Working:

```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.8
        machine: x86_64
        release: 4.9.34-cloudflare-2017.6.5
         system: Linux
        version: debian 8.8
```

**Comment by bobrik** [comment]
Salt 2016.11.6 works as expected too.

**Comment by Ch3LL** [comment]
I'm having a hard time replicating this. What does your `dictionaries` data look like?

**Comment by bobrik** [comment]
My bad, here's a simpler test case to reproduce:

```
$ tree states/test
states/test
├── files
│   ├── config.xml
│   └── data.csv
└── init.sls

1 directory, 3 files
```

```yaml
/tmp/issue-42758:
  file.directory:
    - clean: true

/tmp/issue-42758/foo:
  file.recurse:
    - source: salt://test/files
    - makedirs: true
    - clean: true
    - exclude_pat: config.xml
    - require_in:
      - file: /tmp/issue-42758

/tmp/issue-42758/foo/config.xml:
  file.managed:
    - source: salt://test/files/config.xml
    - makedirs: true
    - require_in:
      - file: /tmp/issue-42758/foo
```

On 2017.7.0 each run produces:

```
local:
----------
          ID: /tmp/issue-42758/foo/config.xml
    Function: file.managed
      Result: True
     Comment: File /tmp/issue-42758/foo/config.xml updated
     Started: 04:19:15.303749
    Duration: 27.989 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: /tmp/issue-42758/foo
    Function: file.recurse
      Result: True
     Comment: The directory /tmp/issue-42758/foo is in the correct state
     Started: 04:19:15.333106
    Duration: 70.006 ms
     Changes:
----------
          ID: /tmp/issue-42758
    Function: file.directory
      Result: True
     Comment: Files cleaned from directory /tmp/issue-42758
     Started: 04:19:15.403932
    Duration: 27.589 ms
     Changes:
              ----------
              removed:
                  - /tmp/issue-42758/foo/config.xml

Summary for local
------------
Succeeded: 3 (changed=2)
Failed:    0
------------
Total states run:     3
Total run time: 125.584 ms
```

On 2016.11.6 there are no changes:

```
local:
----------
          ID: /tmp/issue-42758/foo/config.xml
    Function: file.managed
      Result: True
     Comment: File /tmp/issue-42758/foo/config.xml is in the correct state
     Started: 04:20:37.930878
    Duration: 26.597 ms
     Changes:
----------
          ID: /tmp/issue-42758/foo
    Function: file.recurse
      Result: True
     Comment: The directory /tmp/issue-42758/foo is in the correct state
     Started: 04:20:37.958327
    Duration: 50.476 ms
     Changes:
----------
          ID: /tmp/issue-42758
    Function: file.directory
      Result: True
     Comment: Directory /tmp/issue-42758 is in the correct state
     Started: 04:20:38.009578
    Duration: 2.603 ms
     Changes:

Summary for local
------------
Succeeded: 3
Failed:    0
------------
Total states run:     3
Total run time:  79.676 ms
```

It seems like `exclude_pat` may be unrelated, it's `/tmp/issue-42758` that removed the file, not `/tmp/issue-42758/foo`. It works if I add require for `file: /tmp/issue-42758` in `config.xml`.

The actual behavior change then is that `clean` started working recursively and you now need to put reverse requisites for each level that is getting cleaned up instead of just one parent level. Is that expected change? It doesn't seem intuitive.
