### ISSUE TITLE
win_pkg not parsing the pkgs style info if there is only one package listed?

### ISSUE THREAD

**Issue by danbryan** [saltstack/salt#42757]
salt-minion: 2017.7.0(py3)
When calling the pkg.installed state as defined using these two methods:

https://gist.github.com/whytewolf/427c4d477333da77c2fe7f367c3fb7cc

The first method worked as intended, the second method returned the following error:

----------
          ID: update-winzip
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1837, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\pkg.py", line 1621, in installed
                  **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1098, in install
                  if options.get('version') is not None:
              AttributeError: 'str' object has no attribute 'get'
     Started: 18:05:39.651288
    Duration: 1210.014 ms
     Changes:

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this. It fails on this state:

```
update-winzip2:
  pkg.installed:
    - pkgs:
      - firefox: 29.0.1
      - gedit: 2.30.1-1
```

But works with this state:

```
update-winzip:
  pkg.installed:
    - name: git
    - version: 2.12.2
```
