### ISSUE TITLE
State 'git.latest' was not found in SLS 'foobar'

### ISSUE THREAD

**Issue by mooperd** [saltstack/salt#42846]
### Description of Issue/Question

I have found this error since the Saltstack RPMs which are install by salt-bootstrap were updated. I guess they come from the salt repo https://repo.saltstack.com/yum/redhat/7.

```
[root@ip-172-31-28-194 salt]# salt-call --local state.apply foobar
[ERROR   ] State 'git.latest' was not found in SLS 'foobar'
Reason: 'git' __virtual__ returned False

local:
----------
          ID: git.key
    Function: file.managed
        Name: /tmp/id_rsa
      Result: True
     Comment: File /tmp/id_rsa is in the correct state
     Started: 14:52:06.717942
    Duration: 16.246 ms
     Changes:   
----------
          ID: git@bitbucket.org:foo/bar.git
    Function: git.latest
      Result: False
     Comment: State 'git.latest' was not found in SLS 'foobar'
              Reason: 'git' __virtual__ returned False
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:  16.246 ms
```

### Setup
```
git.key:
  file.managed:
    - name: /tmp/id_rsa
    - source: salt://git-ssh-keys/id_rsa
    - mode: 400

# Clone the Repo
git@bitbucket.org:foo/bar.git:
  git.latest:
    - target: /opt/bar
    - user: root
    - identity: /tmp/id_rsa
    - require:
      - file: git.key
```

### Steps to Reproduce Issue
salt-call --local state.apply fe-core-code-clone

### Versions Report
salt-call 2017.7.0 (Nitrogen)
Centos 7
