### ISSUE TITLE
[FEATURE] Allow source parameter to specify a location on the minion in file.* state modules

### ISSUE THREAD

**Issue by czee** [saltstack/salt#4292]
Currently the source parameter allows 'salt://', 'http://' and 'ftp://'. This issue requests the ability to simply use 'file://' such as:

```
/etc/pkg/pkg.conf:
  file.managed:
    - source: file///etc/pkg/pkg.conf.orig
    - user: root
    - group: root
    - mode: 0660
```
