### ISSUE TITLE
`extension_modules` defaulting to `/var/cache/minion` although running under proxy minion

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#42943]
### Description of Issue/Question

The `extension_modules` option defaults to `/var/cache/minion/extmods` when it should default to `/var/cache/proxy/extmods`.
Additionally, this option should probably be appended to the `append_minionid_config_dirs` list of directories that should have the minion ID appended, hence each proxy minion caches its modules separately.
Without these, when running on a box managed by a regular minion with extension modules, creates overlaps.

### Setup

Any proxy type should be affected.

### Steps to Reproduce Issue

Startup a proxy minion and execute `test.get_opts`.

### Versions Report

```yaml
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.8
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.8
```
