### ISSUE TITLE
 Saltstack supervisord execution module fails to reread changes in application configuration file

### ISSUE THREAD

**Issue by anuja12415** [saltstack/salt#43044]
### Description of Issue

```
supervisor_reread:
  module.run:
    - name:  supervisord.reread
    - conf_file: /etc/supervisor/conf.d/abc.conf
    - bin_env: /usr/bin/supervisorctl
supervisor_update:
  module.run:
    - name:  supervisord.update
    - conf_file: /etc/supervisor/conf.d/abc.conf
    - bin_env: /usr/bin/supervisorctl
  ```

I am using the above mentioned modules to reread and update any changes made to supervisor configuration file for my application running on minion. When I run state.apply in master, changes in the supervisor conf file  are not getting reflected in the minion.

### Versions Report
Version of Salt for Master and Minion : 2017.7.0 (Nitrogen)
