### ISSUE TITLE
salt-cloud AWS server can not set a recover alarm

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#43069]
### Description of Issue/Question
Trying to create a cloudwatch alarm to recover a server if it fails. For an hvm image of ubuntu a salt-cloud created server the recover option is disabled.  The same option is available if I spin up an hvm ubuntu server via the GUI.   Per AWS Support the servers spun up by salt-cloud have some portions of the instance store setup and that is what is preventing this option from working.

### Setup
cloud provider
```
aws_us-east-2:
  # ip address salt-cloud should connect to
  ssh_interface: private_ips
  # aws credentials
  id:  'xxxxxxxxxx'
  key: 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'
  # ssh key
  keyname: xxxxxxxxxx
  private_key: /data/credentials/ssh/XXXXXXXXXXXXX
  # aws location
  location: us-east-2
  # aws ami
  size: t2.small
  # delete aws root volume when minion is destroyed
  del_root_vol_on_destroy: True
  # local user
  ssh_username: root
  # rename on destroy
  rename_on_destroy: True
  driver: ec2
  minion:
    master: 10.30.20.31
    grains:
     server_init: saltcloud
     server_provider: aws

  script: bootstrap-salt.sh
  script_args: stable 2017.7
```

cloud profile
```
us-east-2b_subAppB-vpcProdEast_ubuntu_m4.xlarge:
  provider: aws_us-east-2
  image: ami-1aa98c7f
  availability_zone: us-east-2b
  ssh_username: ubuntu
  size: m4.xlarge
  display_ssh_output: False
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: False
      SubnetId: subnet-4c35ce37
      SecurityGroupId:
        - sg-f778f89e
        - sg-fc78f895


  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 12
      Ebs.VolumeType: gp2
```

### Steps to Reproduce Issue
works for every server spun up via salt-cloud.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
```
# salt-cloud --version
salt-cloud 2017.7.0 (Nitrogen)
```
