### ISSUE TITLE
Improvement is documentation - examples please

### ISSUE THREAD

**Issue by gzcwnk** [saltstack/salt#43075]
### Description of Issue/Question

Unable to figure out how to restart a service in a sls file

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

###
So I am trying to restart a service after I have changed its config file,

```
#rhel5
{% if grains['oscodename'] == 'Tikanga' %}
sudo_ipa_setup:
  cmd.script:
    - source: salt://sudo-sssd-sh
    - user: root
    - shell: /bin/bash

/etc/ldap.conf:
  file.managed:
    - source: salt://ldap-post-post-ipa4-001.conf
    - user: root
    - group: root
    - mode: 440
    - backup: minion

nis_ipa_setup:
  cmd.script:
    - source: salt://sudo-nis-sh
    - user: root
    - shell: /bin/bash
{% endif %}

#restart a service
sssd:
  service.restart
```
###

Which doesnt work.

It would be really nice if there are examples on how to do this, cant find any via googling.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
