### ISSUE TITLE
How to obtain more details of error message?

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#43079]
### Description of Issue/Question
I run `salt-ssh` and receive this error message.

```
          ID: necessary_packages
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit run-r3338b54eff4140afad9df7dc73c05c93.scope.
                    No apport report written because the error message indicates its a followup error from a previous failure.
                    E: Sub-process /usr/bin/dpkg returned an error code (1)
     Started: 09:15:32.101015
    Duration: 5534.169 ms
     Changes:   


```

How to obtain more details? I think some heavily needed stdout/stderr gets lost.

### Versions Report

```
salt:/srv # salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: 2.1
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: 0.22.0
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
         pygit2: 0.22.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: SuSE 12.3 x86_64
        machine: x86_64
        release: 3.7.10-1.45-default
         system: Linux
        version: openSUSE  12.3 x86_64

```
