### ISSUE TITLE
Yum pkg.installed false error

### ISSUE THREAD

**Issue by moali87** [saltstack/salt#43076]
### Setup
salt with kitchen-salt running 2017.7.1
### Steps to Reproduce Issue
Run a state like the following:
```yaml
download_java8:
  cmd.run:
    - name: 'wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm'
    - cwd: /tmp
    - unless: java -version

install_java8:
  pkg.installed:
    - name: /tmp/jdk-8u131-linux-x64.rpm
    - unless: java -version
```
### Versions Report
```yaml
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

### Log from minion
```shell
2017-08-21 03:14:08,716 [salt.state       ][ERROR   ][3696] Made the following changes:
'jdk1.8.0_131' changed from 'absent' to '2000:1.8.0_131-fcs'
```

### Log from salt run
```yaml
       ----------
                 ID: install_java8
           Function: pkg.installed
               Name: /tmp/jdk-8u131-linux-x64.rpm
             Result: False
            Comment: The following packages failed to install/update: /tmp/jdk-8u131-linux-x64.rpm
            Started: 03:13:45.461228
           Duration: 23416.124 ms
            Changes:
              ----------
              jdk1.8.0_131:
                  ----------
                  new:
                      2000:1.8.0_131-fcs
                  old:

       Summary for local
       -------------
       Succeeded: 10 (changed=11)
       Failed:     1
       -------------
       Total states run:     11
       Total run time:  144.193 s

```
