### ISSUE TITLE
ldap.managed error: exception in ldap backend: LDAPError(0, 'Error')

### ISSUE THREAD

**Issue by danhawkes** [saltstack/salt#43083]
### Description of Issue/Question

Attempting to run a state with `ldap.managed' , I'm seeing the following error:

```
          ID: ldap_config
    Function: ldap.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1750, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1705, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/ldap.py", line 256, in managed
                  with connect(connect_spec) as l:
                File "/usr/lib/python2.7/site-packages/salt/modules/ldap3.py", line 289, in connect
                  _convert_exception(e)
                File "/usr/lib/python2.7/site-packages/salt/modules/ldap3.py", line 55, in _convert_exception
                  six.reraise(LDAPError, args, sys.exc_info()[2])
                File "/usr/lib/python2.7/site-packages/salt/modules/ldap3.py", line 257, in connect
                  l = ldap.initialize(url)
                File "/usr/lib64/python2.7/site-packages/ldap/functions.py", line 91, in initialize
                  return LDAPObject(uri,trace_level,trace_file,trace_stack_limit)
                File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 70, in __init__
                  self._l = ldap.functions._ldap_function_call(ldap._ldap_module_lock,_ldap.initialize,uri)
                File "/usr/lib64/python2.7/site-packages/ldap/functions.py", line 63, in _ldap_function_call
                  result = func(*args,**kwargs)
              LDAPError: exception in ldap backend: LDAPError(0, 'Error')
```

However, I can't find any info on the error in the [python-ldap docs](https://www.python-ldap.org/doc/html/ldap.html#exceptions). 

What does the error mean / how can I go about debugging it?

### Setup
`ldap.sls`
```
ldap_installed:
  pkg.installed:
    - name: openldap
    - pkgs:
      - openldap-servers: 2.4.40
      - python-ldap
      - openldap-clients

ldap_service:
  service.running:
    - name: slapd
    - enable: True

ldap_config:
  ldap.managed:
    - connect_spec:
        bind:
          method: sasl
    - entries:
      - ou=customers,dc=example,dc=com:
        - replace:
          ou: customers
          objectclass:
            - top
            - organizationalUnit
```

### Steps to Reproduce Issue
salt '*' state.apply ldap

### Versions Report

master:
```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.0
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: debian 9.0
```
minion:
```
Salt Version:
           Salt: 2016.11.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by garethgreenaway** [comment]
@danhawkes Thanks for the report.  I'm wondering if your seeing that error because Salt isn't able to connect to the LDAP instance.  You may have need to configure salt to be able to talk to LDAP per this page:
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.ldapmod.html

**Comment by danhawkes** [comment]
@garethgreenaway Hi, thanks for the response. 

Yes - connectivity was my first thought also. However, I think the stack trace shows it's using  `ldap3` rather than `ldapmod` underneath, which doesn't mention any config requirements in the [docs](https://docs.saltstack.com/en/2016.11/ref/modules/all/salt.modules.ldap3.html) (presumably they're set via the `connect_spec` parameter). 

Also I can run run `salt '*' ldap3.search "{}" "base='dc=example,dc=com'"` apparently successfully. 

Will have a go setting those config values tomorrow anyway, see what happens.

**Comment by garethgreenaway** [comment]
@danhawkes You're right.  I missed the call to the ldap3 module.  Looking closer, it makes sense that the search works but the call to managed is failing because it's expecting some bind credentials with the rights to be able to make modifications.  You might need to pass along some credentials:
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.ldap3.html#salt.modules.ldap3.connect

**Comment by danhawkes** [comment]
Right, so I've added credentials as below, and am still getting the same error.

```
ldap.managed:
- connect_spec:
    bind:
        method: simple
        dn: cn=admin,dc=example,dc=com
        password: password
- entries:
    - ou=testorg,dc=example,dc=com:
    - add:
        ou: testorg
        objectclass:
        - top
        - organizationalUnit
```

However, using those same credentials with `ldap3.add` appears to be connecting successfully:

```
> salt -I 'env:configtest' ldap3.add  
"{'bind': {'method': 'simple', 'dn':'cn=admin,dc=example,dc=com', 'password': 'password'}}"
"dn='ou=testorg,dc=example,dc=com'"
"attributes={'example': 'values'}"

...

LDAPError: exception in ldap backend: UNDEFINED_TYPE({'info': 'example: attribute type undefined', 'desc': 'Undefined attribute type'},)
```

**Comment by WarrenWilkinson** [comment]
I've had a very similar error to you, but have resolved it.  I thought I'd post a possible solution in case any others arrive at this problem.

The problem (I think) is that because you have not specified a URL to connect too, it's taking the rules name (in your case "ldap_config") as the URL.

You'll notice in the example in the documentation (https://docs.saltstack.com/en/latest/ref/states/all/salt.states.ldap.html) they call their rule "ldapi:///".

Try adding a url to your bind statement, like this:

```
ldap_config:
  ldap.managed:
    - connect_spec:
        url: ldapi:///
        bind:
          method: sasl
    - entries:
      - ou=customers,dc=example,dc=com:
        - replace:
          ou: customers
          objectclass:
            - top
            - organizationalUnit
```
