### ISSUE TITLE
salt-ssh 2017.7.1 + vault = token in git

### ISSUE THREAD

**Issue by danielmotaleite** [saltstack/salt#43094]
with the salt-ssh 2017.7.1, the vault config changed and now we have to put the token in the master.

the problem is that this collides with version control systems (like git) , we have to push the token to git (and later to github, gitlab, etc), manually remove it before commits, or blacklist the master from commits (and if we need to add something, we need to whitelist it, remove the token, change what is needed, commit, put back the token, blacklist again)

In the past, the vault token could be read from the environment, making it perfect solution to avoid committing the token.

Please allow again the token to be read from the environment or allow one to read the token from a file (that we can safely .gitignore)

**Comment by gtmanfred** [comment]
What version of salt were you using when this was possible?

Also, how exactly are you using the vault? are you using sdb or the vault.get execution modules or runner modules?

I am not aware of any changes that would have made this so it wouldn't work, but you might be able to use the environment sdb backend to store stuff in the environment.

https://docs.saltstack.com/en/latest/ref/sdb/all/salt.sdb.env.html

**Comment by danielmotaleite** [comment]
the best way to give you that info is to refer to my original ticket when i had problems (due to a bug) setting it up

https://github.com/saltstack/salt/issues/38830

looking to the /usr/lib/python2.7/dist-packages/salt/utils/vault.py, i see this:

```
def make_request_with_profile(method, resource, profile, **args):
    '''
    DEPRECATED! Make a request to Vault, with a profile including connection
    details.
    '''
```
and in that profile config, we have:

```
    token = os.environ.get('VAULT_TOKEN', profile.get('vault.token'))
```

**Comment by gtmanfred** [comment]
Ok, you should be able to add the following to your master config?  The master config gets run through salt.config.apply_sdb, and should inject the environment variable into the config when salt-ssh starts up.

```
myvault:
  vault.host: 127.0.0.1
  vault.port: 8200
  vault.scheme: http  # Optional; default is https
  vault.token: sdb://osenv/VAULT_TOKEN  # Required, unless set in environment
osenv:
  driver: env
```

If that doesn't work, I will work on getting a fix to add the environment variable back into the new make_request function.

Thanks,
Daniel

**Comment by danielmotaleite** [comment]
That was the old config, that do not work anymore, but porting your changes to the new config layout, it works... from my conf/master, for the salt-ssh i have:

```
# https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.vault.html
vault:
    url: https://vault.example.com:8200
    auth:
        method: token
        token: sdb://osenv/VAULT_TOKEN
osenv:
  driver: env
```
Exporting the VAULT_TOKEN, it works!

Thanks!

Can you please add this example to the vault documentation, i suspect this is useful for other too
