### ISSUE TITLE
[WARNING ] Cannot resolve address None info via socket: <class 'socket.gaierror'>

### ISSUE THREAD

**Issue by ravi45722** [saltstack/salt#43099]
### Description of Issue/Question
Master: salt 2016.11.4 (Carbon)
Minions: salt-minion 2016.11.0 (Carbon) && salt-minion 2017.7.1 (Nitrogen)

### Setup
Minions:
master: 10.xx.xx.133
id: 10.xx.xx.132

Master:
```
interface: 10.xx.xx.133
external_auth:
  pam:
    salt:
      - '@wheel'
      - .*

rest_cherrypy:
  port: 8686
  host: 10.xx.xx.133
  ssl_crt: /etc/ssl/private/cert.pem
  ssl_key: /etc/ssl/private/key.pem
  webhook_disable_auth: True
  webhook_url: /hook
```

### Steps to Reproduce Issue
I have a setup of 1 master and 9 minions. When ever I run any command on any minion I am getting this WARNING. What it mean? How to resolve it??

### Logs
[root@localhost minions]# salt '10.xx.xx.132' test.ping
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[WARNING ] Cannot resolve address None info via socket: <class 'socket.gaierror'>
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', '10.225.253.133_master', 'tcp://10.225.253.133:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/92/983197b21f1e3f9934ba32ac7bce4598a3fbd92c747380482622d723b09835/.minions.p
[DEBUG   ] get_iter_returns for jid 20170822104617369935 sent to set(['10.xx.xx.132']) will timeout at 10:46:22.491816
[DEBUG   ] jid 20170822104617369935 return from 10.xx.xx.132
[DEBUG   ] LazyLoaded nested.output
10.xx.xx.132:
    True
[DEBUG   ] jid 20170822104617369935 found all minions set(['10.xx.xx.132'])
