### ISSUE TITLE
lgpo.set state does not validate possible element alias names when comparing requested policy to existing policy

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#43120]
### Description of Issue/Question
lgpo.set does not validate all possible policy element names when comparing a previous policy to a requested policy to determine if changes should be made

If "full" policy/element names are used (those seen in the GUI), then lgpo.set will only update the policy when changes need to be made.  If the "id" string from the ADMX file is used, the policy will be re-applied regardless.

### Setup
using the following state, the 'Configure Windows NTP Client' policy will be set on initial state run and subsequent state runs (or test=True) will properly show that no changes are needed:
```
lgpo_test:
  lgpo.set:
    - computer_policy:
        'System\Windows Time Service\Time Providers\Configure Windows NTP Client':
            NtpServer: time.windows.com,0x9
            Type: NT5DS
            CrossSiteSyncFlags: 2
            ResolvePeerBackoffMinutes: 15
            ResolvePeerBackoffMaxTimes: 7
            SpecialPollInterval: 3600
            EventLogFlags: 0
    - onchanges_in:
      - cmd: run_gpupdate

run_gpupdate:
  cmd.run:
    - name: 'gpupdate /force'
```

In comparison, this version of the state (which accomplishes the exact same policy settings), would reapply the policy every time the state is run (test=True would show the policy is set to change).  (To note: the "changes" key returned by the state is correctly empty):
```
lgpo_test:
  lgpo.set:
    - computer_policy:
        'System\Windows Time Service\Time Providers\Configure Windows NTP Client':
            NtpServer: time.windows.com,0x9
            Type: NT5DS
            CrossSiteSyncFlags: 2
            ResolvePeerBackoffMinutes: 15
            ResolvePeerBackoffMaxTimes: 7
            W32TIME_SpecialPollInterval: 3600
            W32TIME_NtpClientEventLogFlags: 0
    - onchanges_in:
      - cmd: run_gpupdate

run_gpupdate:
  cmd.run:
    - name: 'gpupdate /force'
```

### Steps to Reproduce Issue
Execute a lgpo.set with a policy that applies elements using the IDs from the ADMX files as opposed to the names seen in the GUI (possible element aliases can be seen through the lgpo.show_policy_info execution function).

### Versions Report
Occurs on 2016.11 and 2017.7
