### ISSUE TITLE
`pkg.installed` failed when specifying packages version

### ISSUE THREAD

**Issue by SuperPommeDeTerre** [saltstack/salt#43133]
### Description of Issue/Question
When installing multiple package at once with `pkgs` option of state `pkg.installed`, weird things are occuring...
If using wildcards (`*` characters), packages are not installed, and when not using wildcards, packages are installed, but state fails.

### Setup
Make a state like this:
```yaml
httpd_installed:
  pkg.installed:
    - pkgs:
      - httpd: '2.4.6*'
      - httpd-tools: '2.4.6*'
```

Or, for second case:
```yaml
httpd_installed:
  pkg.installed:
    - pkgs:
      - httpd: '2.4.6'
      - httpd-tools: '2.4.6'
```

### Steps to Reproduce Issue
When using such state:
```yaml
httpd_installed:
  pkg.installed:
    - pkgs:
      - httpd: '2.4.6*'
      - httpd-tools: '2.4.6*'
```
The execution failed and the packages are not installed:
```yaml
minion2:
----------
          ID: httpd_installed
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:

              errors:
                  - No version matching '2.4.6*' found for package 'httpd' (available: none)
                  - No version matching '2.4.6*' found for package 'httpd-tools' (available: none)
     Started: 09:34:54.677273
    Duration: 5276.231 ms
     Changes:

Summary for minion2
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   5.276 s
```

If I use no wildcard in versions, it fails equally, but packages are installed:
```yaml
minion2:
----------
          ID: httpd_installed
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: httpd=2.4.6, httpd-tools=2.4.6
     Started: 09:37:47.396552
    Duration: 15053.908 ms
     Changes:
              ----------
              httpd:
                  ----------
                  new:
                      2.4.6-45.el7.centos.4
                  old:
              httpd-tools:
                  ----------
                  new:
                      2.4.6-45.el7.centos.4
                  old:

Summary for minion2
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  15.054 s
```

But if the packages are installed on the minion, the state failed when not using wildcards and succeed when using them.

### Versions Report
Master:
```yaml
Salt Version:                                          
           Salt: 2017.7.1                              
                                                       
Dependency Versions:                                   
           cffi: Not Installed                         
       cherrypy: Not Installed                         
       dateutil: Not Installed                         
      docker-py: Not Installed                         
          gitdb: Not Installed                         
      gitpython: Not Installed                         
          ioflo: Not Installed                         
         Jinja2: 2.7.2                                 
        libgit2: Not Installed                         
        libnacl: Not Installed                         
       M2Crypto: Not Installed                         
           Mako: Not Installed                         
   msgpack-pure: Not Installed                         
 msgpack-python: 0.4.8                                 
   mysql-python: Not Installed                         
      pycparser: Not Installed                         
       pycrypto: 2.6.1                                 
   pycryptodome: Not Installed                         
         pygit2: Not Installed                         
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed                         
         PyYAML: 3.11                                  
          PyZMQ: 15.3.0                                
           RAET: Not Installed                         
          smmap: Not Installed                         
        timelib: Not Installed                         
        Tornado: 4.2.1                                 
            ZMQ: 4.1.4                                 
                                                       
System Versions:                                       
           dist: centos 7.3.1611 Core                  
         locale: UTF-8                                 
        machine: x86_64                                
        release: 3.10.0-514.26.2.el7.x86_64            
         system: Linux                                 
        version: CentOS Linux 7.3.1611 Core            
```

Minion:
```yaml
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment]
@SuperPommeDeTerre this might be a duplciate of https://github.com/saltstack/salt/issues/42774

Can you try the fix in https://github.com/saltstack/salt/pull/42808

**Comment by SuperPommeDeTerre** [comment]
@Ch3LL I'm currently giving this a try. I'll keep you informed.

**Comment by SuperPommeDeTerre** [comment]
@Ch3LL It's better, It works when omitting wildcards, but installation still fails when using them:
```yaml
minion2:
----------
          ID: httpd_installed
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:

              errors:
                  - No version matching '2.4.6*' found for package 'httpd' (available: none)
                  - No version matching '2.4.6*' found for package 'httpd-tools' (available: none)
     Started: 08:10:57.172464
    Duration: 5480.593 ms
     Changes:

Summary for minion2
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   5.481 s
```
