### ISSUE TITLE
Unable to install DLP application in windows minion

### ISSUE THREAD

**Issue by nkrishnakishor** [saltstack/salt#43132]
I'm trying to install DLP application in a Windows minion but unable to install and below is the error message. I have the installation setup file locally in the server under the directory **/srv/salt/win/repo**.

```
salt-minion1:
    ----------
    DLP_x64:
        Unable to locate package DLP_x64
```

Below is the init file

```
DLP_x64:
 8.2.2324:
  installer: 'salt://win/repo/dlp/x64/DLP.msi'
  full_name: 'DLP 64bit Version'
  reboot: False
  uninstall_flags: '/q'
  msiexec: True
  uninstaller: 'salt://win/repo/dlp/x64/DLP.msi'
```

Below is the Salt version details and Windows minion is also running the same version

```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

Please help me in installing the application.
