### ISSUE TITLE
pkg.latest and rpm version numbers - what are the requirements?

### ISSUE THREAD

**Issue by mwtzzz** [saltstack/salt#43157]
We have a custom rpm package where an older version looks like 
nagios-client-1.1.03-0.1500498524.x86_64
and the latest version looks like
nagios-client-1.1.03.07-0.1503344684.x86_64

You see the difference is that the latest has an additional version number appended.

pkg.latest refuses to update it, saying that the host, which has the older package installed, is "already on the latest version".

It appears salt only looks at the first three digits x.x.x. Is that true? Is that the expected behavior?

**Comment by Ch3LL** [comment]
can you paste the output of `salt --versions-report`?

**Comment by mwtzzz** [comment]
Here you go Megan:
```
Salt Version:                                                                                   [4/1842]
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.4.41-35.53.amzn1.x86_64
         system: Linux
        version: Not Installed
```
