### ISSUE TITLE
need to add a string after matching word  Xfer to conf file 

### ISSUE THREAD

**Issue by awssalt01** [saltstack/salt#43158]
need to add a string after matching word  Xfer to conf file 

```
{% if grains['env'] == 'dev' %}
file.line:
   - name: path/to/file
   - mode: replace
   - match: 'Xfer'
   - content: "Xfercontent"

 file.line:
   - name: path/to/file
   - mode: ensure
   - content: "contenfile"
{% endif %}
```

salt --version
salt 2017.7.1 (Nitrogen)

I got no errors and no changes applied to conf file
