### ISSUE TITLE
chocolatey.installed ignores version definition

### ISSUE THREAD

**Issue by tobias-kuendig** [saltstack/salt#43175]
### Description of Issue/Question

When using `chocolatey.installed` [the docs](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.chocolatey.html) state:

> Install a specific version of the package. Defaults to latest version. **If the version is different to the one installed then the specified version will be installed.** Default is None.

This seems not to be the case. When I install the `php` package in version `7.1.5`, then update my sls file to install `7.1.7` salt prints `The Package php is already installed` and does not touch it.

### Setup

```
install_php_package:
  chocolatey.installed:
    - name: php
    - version: '7.1.5' 
```

### Steps to Reproduce Issue

Run the above sls file and check your php version with `php -v`. Then change the version in the sls file to `7.1.7` and run salt again. If you check your php version again it's still `7.1.5`

### Versions Report

I have also tested this on `2016.11.7` with the same result.

```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.14393  Multiprocessor Free
```

**Comment by gtmanfred** [comment]
What version of salt are you running on the minion?

`salt minionid test.versions_report`

Because this should be broken on 2017.7.0 and 2017.7.1 right now.

https://github.com/saltstack/salt/pull/42534

```
[root@salt ~]# salt windows\* state.apply test
windows.c.gtmanfred-1263.internal:
----------
          ID: install_php_package
    Function: chocolatey.installed
        Name: php
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1837, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\chocolatey.py", line 95, in installed
                  if name not in [package.split('|')[0].lower() for package in pre_install.splitlines()]:
              AttributeError: 'dict' object has no attribute 'splitlines'
     Started: 19:45:12.329000
    Duration: 1038.0 ms
     Changes:
```

That will be fixed in 2017.7.2

Thanks,
Daniel

**Comment by tobias-kuendig** [comment]
Yes, it actually was broken. I manually applied [this patch](https://github.com/saltstack/salt/pull/42534/files) to make it work.

I initially tested it on `2016.11.7` where the specified `version` was ignored. Then I upgraded to `2017.7.1` in hope that it has been fixed in this new release. After finding out about the broken chocolatey support I applied the patch but the `version` setting is still being ignored.

I run masterless locally on Windows. I execute `salt-call state.apply --local` to apply the sls files.

I have downgraded to `2016.11.7` again. Like I mentioned before the `version` settings seems to be ignored in both versions.

```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.14393  Multiprocessor Free
```

**Comment by tobias-kuendig** [comment]
I just noticed by looking at [the code](https://github.com/saltstack/salt/blob/d6ebd7a52f9f3c1852f67d6a1316ae6419f7e2bf/salt/states/chocolatey.py#L114) that unless you specify `force: true` it'll always jump over already intalled packages.

This means that

* [ ] The documentation for `version` needs to state that `force` is currently required
* [ ] There is no possibility to `upgrade` a package via the `version` flag but ignore it if the required version is already installed.

If I set `force: true` the new version will be installed but this will happen every time I run salt. 

To me it looks like as long as a `version` is specified this version should be installed without using `force`. If the specific version already exists nothing should happen.

**Comment by damon-atkins** [comment]
The state 'installed' should
- determine if the software is installed 
-- and if not installer the version specified or no version specified the latest is installed
-- and if is already installed, ensure the version specified is installed. (no version specified should be any version is acceptable)

The state 'latest' is different in that the effective version specified is always the latest.

Sounds like the state not comparing existing installed version.   Keep in mind that if you upgrade the software by hand chocolatey still things the version has not changed. i.e.  chocolatey has its own private way of tracking versions.

**Comment by gtmanfred** [comment]
It works correctly when you don't have the package installed yet, and when you pass `force: true`

```
[root@salt ~]# salt windows\* chocolatey.version php
windows.c.gtmanfred-1263.internal:
    ----------
    php:
        - 7.1.4
[root@salt ~]# cat /srv/salt/test.sls
install_php_package:
  chocolatey.installed:
    - name: php
    - version: '7.1.5'
ERROR: No return received
[root@salt ~]# salt windows\* state.apply test
windows.c.gtmanfred-1263.internal:
----------
          ID: install_php_package
    Function: chocolatey.installed
        Name: php
      Result: True
     Comment: The Package php is already installed
     Started: 16:26:20.443000
    Duration: 4153.0 ms
     Changes:

Summary for windows.c.gtmanfred-1263.internal
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   4.153 s
[root@salt ~]# cat !$
cat /srv/salt/test.sls
install_php_package:
  chocolatey.installed:
    - name: php
    - version: '7.1.5'
    - force: true
[root@salt ~]# salt windows\* state.apply test
windows.c.gtmanfred-1263.internal:
----------
          ID: install_php_package
    Function: chocolatey.installed
        Name: php
      Result: True
     Comment:
     Started: 16:26:40.511000
    Duration: 45093.0 ms
     Changes:
              ----------
              php:
                  ----------
                  new:
                      - 7.1.5
                  old:
                      - 7.1.4

Summary for windows.c.gtmanfred-1263.internal
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  45.093 s
```

You can also pass `allow_multiple: True` which would allow multiple versions to be installed.

@twangboy or @rdutch do either of you have a problem with adding an `update: True` argument to this or should we just change the wording around `force: True`?

Thanks,
Daniel.

**Comment by twangboy** [comment]
@gtmanfred I think the problem is that the docs state that `If the version is different to the one installed then the specified version will be installed.` but says nothing about requiring `force=True`.

So, we need to either make the state do what the docs say it does, or change the docs. I think `force=True` should only be used to reinstall. As @tobias-kuendig said adding `force=True` to the state will cause the software to be reinstalled every time the state is run. I think the solution proposed by @damon-atkins is correct. We should see what's installed and only force if the versions don't match.

**Comment by gtmanfred** [comment]
Ok, sounds good.  I am going to mark this as a code bug.

Thanks,
Daniel

**Comment by JoshYaxley** [comment]
For anyone who wants substitute behaviour while waiting for the next release, I created this PowerShell script in `salt/scripts/chocolatey/installed.ps1`:

```powershell
Param([Parameter(Mandatory=$True)] [string]$name,
      [Parameter(Mandatory=$True)] [string]$version,
      [Parameter(Mandatory=$True)] [string]$source)


$packages = choco list -l;
$exists = $packages -contains "$name $version";

if ($exists)
{
  echo "changed=no comment='Already installed'";
  return;
}

echo "Installing $name $version from $source";
choco upgrade $name --version $version --source $source --allow-downgrade -y;

if ($LastExitCode -ne 0)
{
  Write-Error "Failed to install";
  echo "changed=yes comment='Failed to install'";
  exit $LastExitCode;
}

echo "changed=yes comment='Installed'";
```

And I'm calling it like this in my state file:

```YAML
package-installed:
  cmd.script:
    - name: salt://scripts/chocolatey/installed.ps1
    - args: "-name PACKAGE-NAME --version PACKAGE-VERSION --source PACKAGE-URL"
    - shell: powershell
    - stateful: True
```

This means you can watch the state with the "onchanges" requisite, and the watching state will only trigger if the package gets installed/updated. Further changes could be done, but this is working for us (we always specify source, for example).

It might be safer to avoid the "--allow-downgrade" flag by introducing version comparison logic (probably using [PowerShell's "version" type](https://www.cupfighter.net/2009/06/powershell-comparing-version-numbers) and doing an uninstall followed by an install if the package version is lower than the currently installed version).
