### ISSUE TITLE
state repoerting named service reported as unavailable but module says it is available

### ISSUE THREAD

**Issue by mwtzzz** [saltstack/salt#43197]
This is on salt-2016.11.1-1.el6 on amzn linux. 

My state file:
```
collectd-service:
  service.running:
    - name: collectd
    - enable: True
    - reload: True
    - watch:
      - pkg: collectd
```
Running the state results in:
```
[ERROR   ] The named service collectd is not available
local:
----------
          ID: collectd-service
    Function: service.running
        Name: collectd
      Result: False
     Comment: The named service collectd is not available
```
But salt-call module and the system itself both see the service:
```
[root@ec2- ~]$ service collectd status
collectdmon (pid  29740) is running...
[root@ec2- ~]$ salt-call service.available collectd
local:
    True
```
