### ISSUE TITLE
Weak require: Allow one state to check if another state is available

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#43231]
### Description of Issue/Question

I would like to be able to test if another state is being applied for a given minion. For example, I have a state which moves `/home` directories to `/srv/home` for some minions. And I would like that another state which is adding users can based on existence of that state determine where to put home directories for users.

This could be something like "weak require":
 * if state to move home directory exist, do it before this state
 * and a check if state to move home directory exist, so that I can modify behavior of current state

### Versions Report

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul 14 2015, 19:46:27)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 14.5.0
         system: Darwin
        version: 10.10.5 x86_64
```

**Comment by MTecknology** [comment]
This seems like a partial duplicate of #43233, which is a misuse of states. Why would you have a state to create a user and then a state to move the user instead of a state to create the user where you expect the user to be? Check out the documentation for user.present and notice the -home: option.

Also, the existing requisites (-watch) cover your request for "weak dependencies."

**Comment by gtmanfred** [comment]
Have you checked out the `prereq` state req?

https://docs.saltstack.com/en/latest/ref/states/requisites.html#prereq

Daniel

**Comment by mitar** [comment]
@gtmanfred, I didn't know about this, but I do not think it works.

So if I have `top.sls` like this:

```yaml
base:
  server1:
    - srv-home
    - add-users

  server2:
    - add-users
```

`srv-home.sls` can be something like:

```yaml
useradd-srv-home:
  file.blockreplace:
    - name: /etc/default/useradd
    - marker_start: "# START srv_home_config GENERATED BY SALT. DO NOT EDIT."
    - marker_end: "# END srv_home_config"
    - content: |
        HOME=/srv/home
    - append_if_not_found: True
```

And `add-users.sls`:

```yaml
user-mitar:
  user.present:
    - name: mitar
    - uid: 2000
    - gid: users
    - empty_password: True
    - remove_groups: True
```

Now if I add to `user-mitar`:

```yaml
    - prereq:
      - file: useradd-srv-home
```

I do not think this will work for `server2`.

**Comment by gtmanfred** [comment]
Then use prereq_in

https://docs.saltstack.com/en/latest/ref/states/requisites.html#direct-requisite-and-requisite-in-types

```
useradd-srv-home:
  file.blockreplace:
    - name: /etc/default/useradd
    - marker_start: "# START srv_home_config GENERATED BY SALT. DO NOT EDIT."
    - marker_end: "# END srv_home_config"
    - content: |
        HOME=/srv/home
    - append_if_not_found: True
    - prereq_in:
      - user: mitar
```

If you do a forloop to create the user.present states, you will need to do the same forloop for prereq_in.
