### ISSUE TITLE
Data loss in HA failover environment if 1 master goes down data is not sent to other master/external system by the minions

### ISSUE THREAD

**Issue by varun292006** [saltstack/salt#43262]
### Description of Issue/Question
In a high available, failover environment if a command is issued from 1 master and while the minion is performing an operation, the first master goes down then minion doesn't send the return data to another master and the information is lost, which should be possible if the environment is high available and configured for failover.

### Setup
salt-2017.7.1 installation with high availability and failover setup managing 2 windows minions.
Configured external mysql log system (as per the instructions) for storing the cache data and returners.

**_master configuraiton:_**
```
ext_job_cache: mysql
job_cache: True
state_events: True
log_level_logfile: debug
return: mysql

**rest all are default settings
```

**_minion configuration:_**
```
master:
  - 192.168.133.178
  - 192.168.133.179
master_type: failover
master_alive_interval: 1
master_failback: True

id: 192.168.133.188

mysql.host: 'salt'
mysql.user: 'salt'
mysql.pass: 'salt'
mysql.db: 'salt'
mysql.port: 3306
mysql.charset: 'utf8'

**rest all are default settings
```

### Steps to Reproduce Issue

1. Issue any saltstack command like copying files or creating directories from 1 master
2. As soon as the command is received by minions poweroff the master
3. Minions will switch over to another master configured in the list
4. Data is not returned at all and gets lost
5. Nothing is returned via returner to the external system as well 

### Versions Report

_**Master report:**_
```
root@masterA:/srv/salt# salt --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-32-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**_Minion report:_**
```
C:\Windows\system32>salt-call --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```
