### ISSUE TITLE
Add an `apply all updates` type option to the win_wua state

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#43272]
### Description of Issue/Question
Add the ability to just apply all updates via a state
As of now, the only option is to use something like this (new behavior of `module.run`):
```
apply_all_updates:
  module.run:
    win_wua.list_updates:
      - install: True
```

This is a feature request:
