### ISSUE TITLE
config files with jinja template special characters will fail

### ISSUE THREAD

**Issue by jeffdyke** [saltstack/salt#43275]
### Description of Issue/Question
I'm not positive if much can be done about this or if something is already in place, but i am building a state to install suricata for my environment and their yaml config has examples that use the syntax `{%` for format variables, but i'm also trying to configure this using jinja templating, but only using `{{` syntax, no control flow statements. Luckily there are only 2 places and they are commented, so i can remove them, but if i wanted to use their custom log formatting, i would run into this problem. 

Ultimately just a question, is there a way around using jinja against a file that already has jinja like syntax, like `//jinja don't parse` kind of like pylint directives?  I could also ask this on a jinja board, but am not sure that i'd run into this like i would using salt.
### Setup
The offending line is `#customformat: "%{%D-%H:%M:%S}t.%z %{X-Forwarded-For}i %H %m %h %u %s %B %a:%p -> %A:%P"`
### Steps to Reproduce Issue

- create a file to be managed
```
/etc/suricata/suricata.yaml:
  file.managed:
    - source: salt://suricata/etc/suricata/suricata.yaml
    - user: root
    - group: root
    - mode: 644
    - template: jinja
    - require:
      - pkg: suricata
```
- create a template that does some replacement:
```
vars:
  # more specifc is better for alert accuracy and performance
  address-groups:
    HOME_NET: "[{{pillar['network-configuration'][grains['environment']]['cidr']}}]"
 logging:
   #customformat: "%{%D-%H:%M:%S}t.%z %{X-Forwarded-For}i %H %m %h %u %s %B %a:%p -> %A:%P"
```
Error:
```
----------
          ID: /etc/suricata/suricata.yaml
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2306, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 4390, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3884, in get_managed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 164, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 418, in render_jinja_tmpl
                  tmplstr)
              SaltRenderError: Jinja syntax error: Encountered unknown tag 'D'.; line 321

              ---
              [...]
                #    enabled: no
                #    filename: http.log
                #    append: yes
                    #extended: yes     # enable this for extended logging information
                    #custom: yes       # enabled the custom logging format (defined by customformat)
                    #customformat: "%{%D-%H:%M:%S}t.%z %{X-Forwarded-For}i %H %m %h %u %s %B %a:%p -> %A:%P"    <======================
                    #filetype: regular # 'regular', 'unix_stream' or 'unix_dgram'

                # a line based log of TLS handshake parameters (no alerts)
                #- tls-log:
                #    enabled: yes  # Log TLS connections.
              [...]
              ---
     Started: 19:09:16.827975
    Duration: 32.431 ms
     Changes:
```
### Versions Report
I don't think the salt/jinja version will matter much, but am running on both master and minion:
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-93-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
