### ISSUE TITLE
Unable to connect to multiple database servers in-order to fetch the data

### ISSUE THREAD

**Issue by varun292006** [saltstack/salt#43305]
### Description of Issue/Question
Unable to connect to multiple database servers in-order to fetch the data as host, user, password and port number should already be defined in minion configuration file.

### Setup
Salt-2017.7.1 installation with multiple masters, HA setup, 2 minions and 1 external system to store logs using mysql returner.

**_master configuration:_**
`ext_job_cache: mysql`

**_minion configuration:_**
```
master:
  - 192.168.133.178
  - 192.168.133.179
master_type: failover
master_alive_interval: 1
master_failback: True
id: 192.168.133.188
mysql.host: 'salt'
mysql.user: 'salt'
mysql.pass: 'salt'
mysql.db: 'salt'
mysql.port: 3306
mysql.charset: 'utf8'
```

### Steps to Reproduce Issue
In order to connect to MySQL returner from minion side I have the below entry in minion configuration file:
```
mysql.host: 'salt'
mysql.user: 'salt'
mysql.pass: 'salt'
mysql.db: 'salt'
mysql.port: 3306
mysql.charset: 'utf8'
```

I also have 4 different database servers and I want to fetch some data from each of them. How can I make that happen?

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-32-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@varun292006 can you clarify your question for me a little? are you stating you want to be able to send the minion return event data to multiple mysql databases?

**Comment by varun292006** [comment]
No.
Let me elaborate a bit more.
I have 4 MySQL servers which are already having my application data let's call them `sql_server1, sql_server2, sql_server3, sql_server4`
So I would like to interact with these, fetch some data and perform some operation.

I also have configured a separate log server let's call it` log_server`. Right now minion data is returned to this server and at the moment my minion configuration has the host, port, database, user and password of this server.

Now I am little bit confused as to how can I access my 4 database servers and fetch the data from them and also return the minion data back to log_server.

**Comment by Ch3LL** [comment]
If you are attempting to fetch this data via state/execution modules you should be able to pass seperate mysql credentials as kwargs to the state like so

```
frank:
  mysql_query.run:
    - host: localhost
    - password: "bob@cat"
    - connection_user: someuser
    - connection_pass: somepass
```

does that help your use case?

**Comment by varun292006** [comment]
Hello Megan,

Thanks for the suggestion.
I am a bit confused with the  `password `and `connection_pass` option that you have mentioned above. Are they both required?
Although, with few hit and trials the below snippet worked for me :)

```
get_data:
  mysql_query.run:
    - name: test1
    - database: mysql
    - connection_db: mysql
    - query: "SELECT * FROM customers;"
    - connection_host: '192.168.133.180'
    - connection_user: 'root'
    - connection_pass: 'rootroot'
    - connection_port: 3306
    - connection_db: mysql
```

I had to mention both `database `(if this is removed then it complains about having atleast one database parameter) and `connection_db `(if this is not mentioned then it goes and connects to default database which is `salt` as per configuration file)
