### ISSUE TITLE
Thorium unable to grab custom grain/pillar data without using a /srv/salt/ state

### ISSUE THREAD

**Issue by pgporada** [saltstack/salt#43313]
### Description of Issue/Question
One should expect that custom grains and pillar data is accessible in Thorium.

My output currently looks like
```
Thorium was located on saltmaster01. in  at Fri Sep  1 17:15:52 UTC 2017
```
instead of looking like
```
Thorium was located on saltmaster01.SALT in DEV at Fri Sep  1 17:15:52 UTC 2017
```

### Setup
/etc/salt/minion
```
grains:
  roles:
    - SALT
```

/etc/salt/master
```
file_roots:
  base:
    - /srv/salt/base
pillar_roots:
  base:
    - /srv/pillar/base
engines:
  - thorium: {}
thorium_roots:
  base:
    - /srv/thorium/base
```

/srv/pillar/base/top.sls
```
base:
  '*':
    - custom_pillar
```

/srv/pillar/base/custom_pillar.sls
```
environment: "DEV"
```

/srv/thorium/base
```
base:
  '*':
    - do_the_thing
```

/srv/thorium/base/do_the_thing.sls
```
shell_test:
  local.cmd:
    - tgt: '*'
    - func: cmd.run
    - arg:
      - echo "Thorium was located on {{ salt['grains.get']('host') }}.{{ salt['grains.get']('roles') }} in {{ salt['pillar.get']('environment') }} at $(date)" >> /tmp/thorium.log
```

### Steps to Reproduce Issue
Restart the salt-master
Restart the salt-minion that lives on the saltmaster node

### Versions Report
```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
This also happens on 2016.11.7.

**Comment by pgporada** [comment]
If I create a state.apply state file for thorium to run, rather than a cmd.run, thorium will be able to use the custom grain/pillar data. 

/srv/thorium/base/do_the_thing.sls
```
shell_test:
  local.cmd:
    - tgt: '*'
    - func: state.apply
    - arg:
      - phil
      - saltenv=base
```

/srv/salt/base/phil/init.sls
```
{% set datacenter = salt['grains.get']('datacenter') -%}
echo into a file:
  cmd.run:
    - name: echo "Thorium was located on {{ salt['grains.get']('host') }}.{{ salt['grains.get']('roles') }} in {{ salt['pillar.get']('environment') }} at $(date)" >> /tmp/thorium.log
```

/tmp/thorium.log
```
Thorium was located on saltmaster01.SALT in DEV at Fri Sep  1 18:14:50 UTC 2017
Thorium was located on saltmaster01.SALT in DEV at Fri Sep  1 18:14:52 UTC 2017
Thorium was located on saltmaster01.SALT in DEV at Fri Sep  1 18:14:55 UTC 2017
```
