### ISSUE TITLE
salt-cloud 2017.7.x broken saltitfy/ec2

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#43311]
### Description of Issue/Question
Didn't recognize setup "master" in provider section in latest python3-based setup without changing anything in my profiles :fire:... (in 2016.x it was working fine):
````
2017-09-01 16:34:27,691 [salt.utils       ][ERROR   ][31905] DNS lookup or connection check of 'salt' failed.
2017-09-01 16:34:27,692 [salt.minion      ][ERROR   ][31905] Master hostname: 'salt' not found or not responsive. Retrying in 30 seconds
````

### Setup
Setup different master as documented in: https://docs.saltstack.com/en/latest/topics/cloud/saltify.html#getting-started-with-saltify

### Steps to Reproduce Issue
run salt-cloud -m \<mapfile\> \<instance\>

### Versions Report
````
# salt-cloud --version
salt-cloud 2017.7.1 (Nitrogen)
````
... not special problems by distro/packages possible... (here latest Debian Jessie)

EDIT: Whole content (minion, grains ...) of providers content is now ignored/overwritten by profile content...

**Comment by Ch3LL** [comment]
@Reiner030 I am having a hard time replicating this with either a python2 install or python3 install of 2017.7.1.

Can you share a snaitized version of your provider/profile/map configs?

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud

**Comment by Reiner030** [comment]
I have the problem on other instances, too - I added temporary the needed data by copying it from provider to profile file.

with <= salt-2016.x this setup was working fine.
Actual setup is "default" installed by salt except the cherrypy version which needs to be the wheezy package to get SSL/TLS activated for salt-api; but this shouldn't be used for salt-cloud.
````
# salt-cloud --versions-report
Salt Version:
            Salt: 2017.7.1

Dependency Versions:
 Apache Libcloud: 1.5.0
            cffi: 0.8.6
        cherrypy: 3.2.2
        dateutil: 2.4.2
       docker-py: Not Installed
           gitdb: 2.0.0
       gitpython: 2.1.1
           ioflo: Not Installed
          Jinja2: 2.9.4
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: 1.3.7
       pycparser: 2.17
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 14.4.0
            RAET: Not Installed
           smmap: 2.0.1
         timelib: Not Installed
         Tornado: 4.4.3
             ZMQ: 4.0.5

System Versions:
            dist: debian 8.9
          locale: UTF-8
         machine: x86_64
         release: 4.9.0-0.bpo.3-amd64
          system: Linux
         version: debian 8.9
````


cloud.providers.d/my-saltify.conf:
````
my_saltify:
  driver: saltify
  ssh_keyfile: '/srv/pillar/salt-cloud/salt_cloud.pem'
  ssh_username: root
  display_ssh_output: True
  master: 'salt-production.mydomain.net'
  script_args: -U -p curl -p patch -p virt-what -p libxml2-utils
  minion:
    master: 'salt-production.mydomain.net'
    environment: aws
    state_output: changes
    state_events: False
    log_level: warning
    log_level_logfile: debug
    job_cache: True
    file_roots:
      base:
        - /srv/salt/base
      aws:
        - /srv/salt/aws
        - /srv/salt/base
      dev:
        - /srv/salt/dev
        - /srv/salt/base
      hetzner:
        - /srv/salt/hetzner
        - /srv/salt/base
      office:
        - /srv/salt/office
        - /srv/salt/base
    pillar_roots:
      base:
        - /srv/pillar/base
      aws:
        - /srv/pillar/aws
        - /srv/pillar/base
      dev:
        - /srv/pillar/dev
        - /srv/pillar/base
      hetzner:
        - /srv/pillar/hetzner
        - /srv/pillar/base
      office:
        - /srv/pillar/office
        - /srv/pillar/base
  grains:
    provider: saltify
    location: hetzner
    loc: hets
    zone: hetzner
````
cloud.profiles.d/elk.conf:
````
elk-saltify:
  grains:
    deployment: prod
    location: hetzner
    loc: hets
    newrelic_account: free
    LVMfilesystems:
      VGcrypt:
        devices:
          - /dev/mapper/md1_crypt
        volumes:
          data:
            size: '2000G'
            mount:
              filesystem: 'ext4'
              mount_point: '/data'
              mount_options: 'defaults,noatime,nodiratime'
    roles:
      - elk
      - nginx
      - nginx-ssl
  minion:
    environment: aws
    state_output: changes
    state_verbose: False
    log_level: warning
    mine_functions:
      network.ip_addrs:
        interface: eth0
        cidr: '0.0.0.0/0'
  provider: my_saltify
  flush_mine_on_destroy: True
````
map-saltify.yaml:
````
elk-saltify:
  - elk-hetz10-01:
      ssh_host: 1.2.3.4
````
