### ISSUE TITLE
salt-ssh  execute a nohup process was hang

### ISSUE THREAD

**Issue by kira8565** [saltstack/salt#43335]
### Description of Issue/Question
the startup shell is 
```
nohup java -jar /opt/CEP1_1/CEPService-1.0-SNAPSHOT.jar --spring.config.location=/opt/CEP1_1/application.properties &
```
when i run this shell via salt-ssh the terminal hang  ,the process was startup but the salt run the command but can not exit ,
I use  `cmd.run` is the same result

### Setup

```
CEP1_1|stop-CEP:
  process.absent:
    - name: CEPService
    - signal:  9

CEP1_1|extracted-CEP:
  file.absent:
    - name: /opt/CEP1_1

  archive.extracted:
    - name: /opt/CEP1_1
    - source: salt://CEP1_1.zip
    - use_cmd_unzip: True
    - enforce_toplevel: False
    - overwrite: True

CEP1_1|fileacl-CEP:
  file.directory:
    - name: /opt/CEP1_1/
    - mode: 777

CEP1_1|start-CEP:
  cmd.script:
    - name: salt://CEP1_1/startup.sh
    - require:
          - archive: CEP1_1|extracted-CEP

```
### Steps to Reproduce Issue

run salt-ssh '*' state.apply CEP1_1

### Versions Report

```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1
 
System Versions:
           dist: Ubuntu 17.04 zesty
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-32-generic
         system: Linux
        version: Ubuntu 17.04 zesty

```
