### ISSUE TITLE
Thorium state with requisite never gets triggered

### ISSUE THREAD

**Issue by pgporada** [saltstack/salt#43358]
### Description of Issue/Question
For me, all of the examples at https://docs.saltstack.com/en/latest/ref/thorium/all/salt.thorium.check.html using a requisite fail and never trigger a state. I could be sending events wrong though and this is entirely my own fault.

I should expect to see the following instead of an empty log file
```
Thorium ran at Tue Sep  5 17:15:52 UTC 2017
Thorium ran at Tue Sep  5 17:15:55 UTC 2017
Thorium ran at Tue Sep  5 17:15:59 UTC 2017
```

### Setup
/etc/salt/master
```
file_roots:
  base:
    - /srv/salt/base
pillar_roots:
  base:
    - /srv/pillar/base
engines:
  - thorium: {}
thorium_roots:
  base:
    - /srv/thorium/base
```

/srv/thorium/base/top.sls
```
base:
  '*':
    - do_the_thing
```

/srv/thorium/base/do_the_thing.sls
```
foo:
  check.contains:
    - value: 42

shell_test:
  local.cmd:
    - tgt: '*'
    - func: cmd.run
    - arg:
      - echo "Thorium ran at $(date)" >> /tmp/thorium.log
    - require:
      - check: foo
```

### Steps to Reproduce Issue
Restart the salt-master
Restart the salt-minion that lives on the saltmaster node
```
salt-call event.send '{"value": "42"}' 'phil/was/here'
salt-call event.fire '{"value": "42"}' 'phil/was/here'
tailf /tmp/thorium.log
# wait...
```
You will notice that no log gets written

### Versions Report
```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
This also happens on 2016.11.7.

**Comment by gtmanfred** [comment]
What does your register assignment look like?

https://docs.saltstack.com/en/latest/topics/thorium/index.html#using-register-data

You have to put the data in the register to use the `check` module against the register.

Thanks,
Daniel

**Comment by pgporada** [comment]
@gtmanfred 
Following the example from your link, I get the following when I restart my salt-master.
```
2017-09-06 02:07:49,864 [salt.template                                        ][PROFILE ][17940] Time (in seconds) to render '/var/cache/salt/master/files/base/phil.sls' using 'jinja' renderer: 0.000811100006104
2017-09-06 02:07:49,864 [salt.template                                        ][DEBUG   ][17940] Rendered data from file: /var/cache/salt/master/files/base/phil.sls:
foo:
  reg.list:
    - add: bar
    - match: my/custom/event
    - stamp: True
  check.contains:
    - value: data

shell_test:
  local.cmd:
    - tgt: '*'
    - func: cmd.run
    - arg:
      - echo "Thorium ran at $(date)" >> /tmp/thorium.log
    - require:
      - check: foo

myregister:
  file.save

2017-09-06 02:07:49,868 [salt.loaded.int.render.yaml                          ][DEBUG   ][17940] Results of YAML rendering: 
OrderedDict([('foo', OrderedDict([('reg.list', [OrderedDict([('add', 'bar')]), OrderedDict([('match', 'my/custom/event')]), OrderedDict([('stamp', True)])]), ('check.contains', [OrderedDict([('value', 'data')])]
)])), ('shell_test', OrderedDict([('local.cmd', [OrderedDict([('tgt', '*')]), OrderedDict([('func', 'cmd.run')]), OrderedDict([('arg', ['echo "Thorium ran at $(date)" >> /tmp/thorium.log'])]), OrderedDict([('req
uire', [OrderedDict([('check', 'foo')])])])])])), ('myregister', 'file.save')])
```

When I dump the contents of `myregister` from `/var/cache/salt/master/thorium/saves/myregister`
```
{"foo": {"val": []}}
```

**Comment by gtmanfred** [comment]
So, you have to put the value in the list.

```
foo:
  reg.list:
    - add: val  # this is the key from the payload to add to the register
    - match: my/custom/event

  check.contains:
    - value:
        val: data

my/custom/event:
  check.event

myregister:
  file.save

shell_test:
  local.cmd:
    - tgt: '*'
    - func: cmd.run
    - arg:
      - echo "Thorium ran at $(date)" >> /tmp/thorium.log
    - require:
      - check: foo
      - check: my/custom/event
```

And then you need to call the event.send in the correct order.

`salt-call event.send 'my/custom/event' '{"val": "data"}'`

or with the keyword arguments

`salt-call event.send data='{"val": "data"}' tag='my/custom/event'`
