### ISSUE TITLE
[salt-cloud] nova driver allocates new floating ip instead of taking free available in project pool

### ISSUE THREAD

**Issue by stamak** [saltstack/salt#43351]
### Setup
provider config

```
os-project-provider:
  driver: nova
  insecure: True
  use_keystoneauth: False
  auth_version: 2
  identity_url: https://127.0.0.1:5000/v2.0
  compute_region: RegionOne
  compute_name: nova
  tenant: os-project
  user: os-project-admin
  password: XXXXXXXX
  ssh_key_name: os-project-ssh-key
  ssh_key_file: /etc/salt/pki/os-project-ssh-key.pem
  ssh_connect_timeout: 120
  wait_for_passwd_timeout: 200
  wait_for_passwd_maxtries: 500
```

profile config
```
os-project-ubuntu-16.04-m1-32_16_160:
  provider: os-project-provider
  size: m1.32_16_160
  image: ubuntu-16.04
  ssh_username: ubuntu
  networks:
    - net-id: 9ceae134-30e2-4979-9b88-c56613804abc
  floating_ip:
    auto_assign: True
    pool: floating_net
```
### Steps to Reproduce Issue
Spin up VMs using nova salt-cloud driver

### Versions Report
```
salt-cloud --versions-report                                                                    
Salt Version:
            Salt: 2016.11.7

Dependency Versions:
 Apache Libcloud: 1.5.0
            cffi: 1.10.0
        cherrypy: 8.9.1
        dateutil: 2.4.2
       docker-py: Not Installed
           gitdb: 0.6.4
       gitpython: 1.0.1
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: 1.0.3
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: 2.18
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.2.0
            RAET: Not Installed
           smmap: 0.9.0
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4

System Versions:
            dist: Ubuntu 16.04 xenial
         machine: x86_64
         release: 4.4.0-87-generic
          system: Linux
         version: Ubuntu 16.04 xenial
```
