### ISSUE TITLE
use keyword breaks sls_id

### ISSUE THREAD

**Issue by rgcosma** [saltstack/salt#43373]
### Description of Issue/Question
When one state has a 'use' clause, sls_id does not read it and fails. I find sls_id very useful for debugging, and while state.highstate does work as expected, this would be much appreciated.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Single SLS file, in this example related to MySQL:

```
le-db:
  mysql_database.present:
    - name: ledb
    - connection_host: {{ db_host }}
    - connection_user: root
    - connection_pass: {{ passwords.root }}
le-user:
  mysql_user.present:
    - name: leuser
    - password: {{ passwords.leuser }}
    - host: '%'
    - use:
      - mysql_database: le-db
```

The state checks for existence of a database and user.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
If the use: part is not present but rather connection credentials are copied, all is fine. With use, I get
salt 'minion' state.sls_id le-user lesls
'MySQL Error 2002: Can't connect to local MySQL server through socket'
which clearly shows the above setting was not read
salt 'minion' state.sls_id le-db lesls
works, as that one doesn't have a use, and it will report correctly if the DB exists

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Both are
Name        : salt-master
Version     : 2017.7.1
Release     : 1.el7
Architecture: noarch
Install Date: Tue 22 Aug 2017 04:39:41 PM UTC
From the saltstack.org repo
