### ISSUE TITLE
Scheduler's job_kwargs not working as expected.

### ISSUE THREAD

**Issue by rajvidhimar** [saltstack/salt#43386]
### Description of Issue/Question
I am adding a scheduler job on my junos proxy minion. I add a job giving certain job_kwargs.
After a while when I list the job I observe bogus data (most probably salt job information) is added to the job_kwargs of my job. These bogus values mess up the module execution.

### Setup
No extra setup. Just a salt master and a junos proxy minion (the issue would mostly be reproducible on a normal salt minion as well)

### Steps to Reproduce Issue
1) Start the salt master
2) Start salt minion
3) Add a scheduler job giving job_kwargs
``` 
salt 'dev' schedule.add rpc_job function='junos.rpc' job_args="[get-interface-information]" job_kwargs="{'interface_name':'lo0'}" seconds=10

dev:
    ----------
    comment:
        Added job: rpc_job to schedule.
    result:
        True
```
4) Check the schedule jobs
```
salt 'dev' schedule.list show_all=True

dev:
    schedule:
      __mine_interval:
        enabled: true
        function: mine.update
        jid_include: true
        maxrunning: 2
        minutes: 60
        name: __mine_interval
        return_job: false
      __proxy_keepalive:
        enabled: true
        function: status.proxy_reconnect
        jid_include: true
        kwargs:
          proxy_name: junos
        maxrunning: 1
        minutes: 2
        name: __proxy_keepalive
        return_job: false
      enabled: true
      rpc_job:
        args:
        - get-interface-information
        enabled: true
        function: junos.rpc
        jid_include: true
        kwargs:
          interface_name: lo0
        maxrunning: 1
        name: rpc_job
        seconds: 10
```
5) After 10-20 secs, check the jobs again
```
salt 'dev' schedule.list show_all=True

dev:
    schedule:
      __mine_interval:
        enabled: true
        function: mine.update
        jid_include: true
        maxrunning: 2
        minutes: 60
        name: __mine_interval
        return_job: false
      __proxy_keepalive:
        enabled: true
        function: status.proxy_reconnect
        jid_include: true
        kwargs:
          proxy_name: junos
        maxrunning: 1
        minutes: 2
        name: __proxy_keepalive
        return_job: false
      enabled: true
      rpc_job:
        args:
        - get-interface-information
        enabled: true
        function: junos.rpc
        jid_include: true
        kwargs:
          __pub_fun: junos.rpc
          __pub_fun_args:
          - get-interface-information
          - interface_name: lo0
          __pub_id: dev
          __pub_jid: '20170907160311714851'
          __pub_pid: 89695
          __pub_schedule: rpc_job
          interface_name: lo0
        maxrunning: 1
        name: rpc_job
        seconds: 10
```

### Versions Report
Salt Version:
           Salt: 2016.11.0-1635-g1f78c08

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Oct 23 2015, 19:19:21)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64

**Comment by vnitinv** [comment]
Also it salt keeps appending items into job_kwargs after certain interval hence it keeps growing over the time.

**Comment by vnitinv** [comment]
@mirceaulinic @cachedout Can you please help us with this issue.

**Comment by garethgreenaway** [comment]
@vnitinv Thanks for the report.  Will take a look at why this is happening.

**Comment by garethgreenaway** [comment]
@vnitinv Looks like this is the expected behavior, those values should be in kwargs and it's related to publishing data back to the Salt master.  But you should not be seeing multiple nested kwargs dictionaries if that is what you are seeing.

**Comment by vnitinv** [comment]
"But you should not be seeing multiple nested kwargs dictionaries if that is what you are seeing."

@garethgreenaway Yes, this is our concern and it keeps growing.

**Comment by garethgreenaway** [comment]
Can you paste a copy of what the schedule list looks like with the nested kwargs?

**Comment by rajvidhimar** [comment]
@garethgreenaway This is what the list looks like: (I fire the schedule.list after every 20-30 secs)

```
(func_env) drajvi-mba:salt drajvi$ sudo salt 'dev' schedule.list show_all=True
dev:
    schedule:
      __mine_interval:
        enabled: true
        function: mine.update
        jid_include: true
        maxrunning: 2
        minutes: 60
        name: __mine_interval
        return_job: false
      __proxy_keepalive:
        enabled: true
        function: status.proxy_reconnect
        jid_include: true
        kwargs:
          proxy_name: junos
        maxrunning: 1
        minutes: 2
        name: __proxy_keepalive
        return_job: false
      enabled: true
      rpc_job:
        args:
        - get-interface-information
        enabled: true
        function: junos.rpc
        jid_include: true
        kwargs:
          interface_name: lo0
        maxrunning: 1
        name: rpc_job
        seconds: 10
(func_env) drajvi-mba:salt drajvi$
(func_env) drajvi-mba:salt drajvi$
(func_env) drajvi-mba:salt drajvi$
(func_env) drajvi-mba:salt drajvi$ sudo salt 'dev' schedule.list show_all=True
dev:
    schedule:
      __mine_interval:
        enabled: true
        function: mine.update
        jid_include: true
        maxrunning: 2
        minutes: 60
        name: __mine_interval
        return_job: false
      __proxy_keepalive:
        enabled: true
        function: status.proxy_reconnect
        jid_include: true
        kwargs:
          proxy_name: junos
        maxrunning: 1
        minutes: 2
        name: __proxy_keepalive
        return_job: false
      enabled: true
      rpc_job:
        args:
        - get-interface-information
        enabled: true
        function: junos.rpc
        jid_include: true
        kwargs:
          __pub_fun: junos.rpc
          __pub_fun_args:
          - get-interface-information
          - interface_name: lo0
          __pub_id: dev
          __pub_jid: '20170907160311714851'
          __pub_pid: 89695
          __pub_schedule: rpc_job
          interface_name: lo0
        maxrunning: 1
        name: rpc_job
        seconds: 10
(func_env) drajvi-mba:salt drajvi$ sudo salt 'dev' saltutil.sync_modules
dev:
(func_env) drajvi-mba:salt drajvi$ sudo salt 'dev' schedule.list show_all=True
dev:
    schedule:
      __mine_interval:
        enabled: true
        function: mine.update
        jid_include: true
        maxrunning: 2
        minutes: 60
        name: __mine_interval
        return_job: false
      __proxy_keepalive:
        enabled: true
        function: status.proxy_reconnect
        jid_include: true
        kwargs:
          proxy_name: junos
        maxrunning: 1
        minutes: 2
        name: __proxy_keepalive
        return_job: false
      enabled: true
      rpc_job:
        args:
        - get-interface-information
        enabled: true
        function: junos.rpc
        jid_include: true
        kwargs:
          __pub_fun: junos.rpc
          __pub_fun_args:
          - get-interface-information
          - __pub_fun: junos.rpc
            __pub_fun_args:
            - get-interface-information
            - __pub_fun: junos.rpc
              __pub_fun_args:
              - get-interface-information
              - interface_name: lo0
              __pub_id: dev
              __pub_jid: '20170907160311714851'
              __pub_pid: 89695
              __pub_schedule: rpc_job
              interface_name: lo0
            __pub_id: dev
            __pub_jid: '20170907160321712995'
            __pub_pid: 89695
            __pub_schedule: rpc_job
            interface_name: lo0
          __pub_id: dev
          __pub_jid: '20170907160331712639'
          __pub_pid: 89695
          __pub_schedule: rpc_job
          interface_name: lo0
        maxrunning: 1
        name: rpc_job
        seconds: 10
(func_env) drajvi-mba:salt drajvi$ sudo salt 'dev' schedule.list show_all=True
dev:
    schedule:
      __mine_interval:
        enabled: true
        function: mine.update
        jid_include: true
        maxrunning: 2
        minutes: 60
        name: __mine_interval
        return_job: false
      __proxy_keepalive:
        enabled: true
        function: status.proxy_reconnect
        jid_include: true
        kwargs:
          proxy_name: junos
        maxrunning: 1
        minutes: 2
        name: __proxy_keepalive
        return_job: false
      enabled: true
      rpc_job:
        args:
        - get-interface-information
        enabled: true
        function: junos.rpc
        jid_include: true
        kwargs:
          __pub_fun: junos.rpc
          __pub_fun_args:
          - get-interface-information
          - __pub_fun: junos.rpc
            __pub_fun_args:
            - get-interface-information
            - __pub_fun: junos.rpc
              __pub_fun_args:
              - get-interface-information
              - __pub_fun: junos.rpc
                __pub_fun_args:
                - get-interface-information
                - __pub_fun: junos.rpc
                  __pub_fun_args:
                  - get-interface-information
                  - __pub_fun: junos.rpc
                    __pub_fun_args:
                    - get-interface-information
                    - __pub_fun: junos.rpc
                      __pub_fun_args:
                      - get-interface-information
                      - __pub_fun: junos.rpc
                        __pub_fun_args:
                        - get-interface-information
                        - interface_name: lo0
                        __pub_id: dev
                        __pub_jid: '20170907160311714851'
                        __pub_pid: 89695
                        __pub_schedule: rpc_job
                        interface_name: lo0
                      __pub_id: dev
                      __pub_jid: '20170907160321712995'
                      __pub_pid: 89695
                      __pub_schedule: rpc_job
                      interface_name: lo0
                    __pub_id: dev
                    __pub_jid: '20170907160331712639'
                    __pub_pid: 89695
                    __pub_schedule: rpc_job
                    interface_name: lo0
                  __pub_id: dev
                  __pub_jid: '20170907160341710315'
                  __pub_pid: 89695
                  __pub_schedule: rpc_job
                  interface_name: lo0
                __pub_id: dev
                __pub_jid: '20170907160351717323'
                __pub_pid: 89695
                __pub_schedule: rpc_job
                interface_name: lo0
              __pub_id: dev
              __pub_jid: '20170907160401711114'
              __pub_pid: 89695
              __pub_schedule: rpc_job
              interface_name: lo0
            __pub_id: dev
            __pub_jid: '20170907160411710944'
            __pub_pid: 89695
            __pub_schedule: rpc_job
            interface_name: lo0
          __pub_id: dev
          __pub_jid: '20170907160421710805'
          __pub_pid: 89695
          __pub_schedule: rpc_job
          interface_name: lo0
        maxrunning: 1
        name: rpc_job
        seconds: 10
```
