### ISSUE TITLE
Salt state for service.available

### ISSUE THREAD

**Issue by pgporada** [saltstack/salt#43418]
It would be useful if `service.available` existed for salt states and not just a salt module. I have a use case where I create systemd timers, but sometimes have to change the service file that the timer triggers. The timer is unable to trigger the service file after a change because the service file has changed on disk and requires a `systemctl daemon-reload`. I can easily add in a `cmd.run "systemctl daemon-reload"`, but having feature parity would be useful too.

Per https://docs.saltstack.com/en/develop/ref/states/all/salt.states.service.html , it does not yet exist.

It would look something like
```
my-process-daemon-reload:
  service.available:
    - name: my-process.service
```

https://github.com/saltstack/salt/pull/36538 was merged that provides the functionality to the salt module.

**Comment by gtmanfred** [comment]
That sounds great, if you wouldn't mind submitting a PR, we would greatly appreciate it.

Thanks,
Daniel

**Comment by garethgreenaway** [comment]
I started looking at this but I'm not entirely sure it's something we should add to the service state as it's not inline with the usual use for states as it wouldn't be defining the state of a service but rather reporting the state.  Maybe the use of module.run inside a state file would be a better approach?

**Comment by gtmanfred** [comment]
I think it might already exist, but I couldn't find it.  If we can add a way to make sure that `systemctl daemon-reload` gets run on the service.running, i think that would solve this problem.

**Comment by babilen** [comment]
Allowing users to provide, say, `reload_services: True` in `service.{dead,disables,running,…}` would indeed solve this problem.

**Comment by mchugh19** [comment]
Would the desired behavior of `reload_service: True` be to always run `systemctl --system daemon-reload`? 

If there isn't a good way of detecting that a reload is necessary, it might be better to handle this in your state which modifies service files. Something like https://serverfault.com/questions/895839/saltstack-execute-systemctl-system-daemon-reload-if-service-file-was-change

```
systemd-reload:
  cmd.run:
   - name: systemctl --system daemon-reload
   - onchanges:  
     - file: superbar.service

superbar.service:
  file.managed:
    - name: /etc/systemd/system/superbar.service

superfoo.service:
  file.managed:
    - name: /etc/systemd/system/superfoo.service
    - onchanges_in:
       - cmd: systemd-reload
```

That way only changes to service files actually trigger the daemon-reload action.
