### ISSUE TITLE
ssh_list_nodegroups and match: nodegroup

### ISSUE THREAD

**Issue by ecgg** [saltstack/salt#43448]
### Description of Issue/Question

When using salt-ssh and ssh_list_nodegroups in etc/master, the match: nodegroup parameter in both pillar/top.sls and salt/top.sls doesn't seem to be taken into account. I'm not sure if this was even intended.

### Setup
```
# etc/master
ssh_list_nodegroups:
    syslog:
        - syslog101

# etc/roster
syslog101:
    host:   syslog101.example.com

# srv/salt/top.sls 
base:
    '*':
        - common
    syslog:
        - match: nodegroup
        - filesystems
        - files
        - services
# srv/pillar/top.sls 
base:
    '*':
        - common
    syslog':
        - match: nodegroup
        - filesystems.syslog
        - files.syslog
        - services.syslog
```

### Steps to Reproduce Issue
Configure as shown above
Run with salt-ssh -N syslog state.apply

```
[me@workstation salt]$ salt-ssh -lprofile  -N syslog state.apply 
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[PROFILE ] Time (in seconds) to render '/home/me/salt/etc/roster' using 'jinja' renderer: 0.00398278236389
[PROFILE ] Time (in seconds) to render '/home/me/salt/etc/roster' using 'yaml' renderer: 0.00501298904419
[PROFILE ] Time (in seconds) to render '/home/me/salt/srv/pillar/top.sls' using 'jinja' renderer: 0.00184082984924
[PROFILE ] Time (in seconds) to render '/home/me/salt/srv/pillar/top.sls' using 'yaml' renderer: 0.00846695899963
[PROFILE ] Time (in seconds) to render '/home/me/salt/srv/pillar/top.sls' using 'jinja' renderer: 0.00147795677185
[PROFILE ] Time (in seconds) to render '/home/me/salt/srv/pillar/top.sls' using 'yaml' renderer: 0.0063648223877
[PROFILE ] Time (in seconds) to render '/home/me/salt/cache/master/files/base/top.sls' using 'jinja' renderer: 0.00123691558838
[PROFILE ] Time (in seconds) to render '/home/me/salt/cache/master/files/base/top.sls' using 'yaml' renderer: 0.00399303436279
[PROFILE ] Time (in seconds) to render '/home/me/salt/cache/master/files/base/common.sls' using 'jinja' renderer: 0.00113797187805
[PROFILE ] Time (in seconds) to render '/home/me/salt/cache/master/files/base/common.sls' using 'yaml' renderer: 0.00209498405457
```

### Versions Report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jun 26 2017, 10:20:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 26 Twenty Six
         locale: UTF-8
        machine: x86_64
        release: 4.12.9-300.fc26.x86_64
         system: Linux
        version: Fedora 26 Twenty Six
