### ISSUE TITLE
Windows Minion - Installation of Chrome fails

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#43487]
Trying to install Chrome on a Windows Minion on 2016.11.8 fails:
```
    The minion function caused an exception: Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1482, in _thread_return
        return_data = executor.execute()
      File "C:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1219, in install
        if pkginfo['version_num'].get('allusers', True):
    KeyError: u'version_num'
```

### Setup
Linux Master and Windows Minion.

### Steps to Reproduce Issue
salt-run winrepo.update_git_repos
salt \* pkg.refresh_db
salt \* pkg.install chrome

```
[root@li457-183 ~]# salt-run winrepo.update_git_repos
https://github.com/saltstack/salt-winrepo-ng.git:
    /srv/salt/win/repo-ng/salt-winrepo-ng
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/salt-winrepo
[root@li457-183 ~]# salt \* pkg.refresh_db
win2016new:
    ----------
    failed:
        0
    success:
        237
    total:
        237
[root@li457-183 ~]# salt \* pkg.install chrome
win2016new:
    The minion function caused an exception: Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1482, in _thread_return
        return_data = executor.execute()
      File "C:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1219, in install
        if pkginfo['version_num'].get('allusers', True):
    KeyError: u'version_num'
[root@li457-183 ~]# 
```

### Versions Report
Windows minion:
```
    Salt Version:
               Salt: 2016.11.8
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 7.1.0
           dateutil: 2.5.3
          docker-py: Not Installed
              gitdb: 0.6.4
          gitpython: 2.0.8
              ioflo: 1.5.5
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 16.0.1
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.4.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393  Multiprocessor Free
```

Linux Master:
```
Salt Version:
           Salt: 2016.11.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.9.36-x86_64-linode85
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
