### ISSUE TITLE
feature request: relative salt:// paths

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#4348]
I find myself repeatedly typing the same salt:// path:
```
munin-mysql-plugin:
  file.managed:
    - name: /usr/share/munin/plugins/mysql
    - source: salt://machine/database/munin-mysql/mysql

munin-mysql-config:
  file.managed:
    - name: /etc/munin/plugin-conf.d/mysql.conf
    - source: salt://machine/database/munin-mysql/mysql
```
Wouldn't it be useful to have a relative salt:// specifier like @ or $ that would be replaced with the 'current path' or the path of the .sls file file within the file_root?

salt://@/mysql would then be the mysql file in the same dir as the .sls is. Saves a lot of typing and makes re-using a state easier.

**Comment by v6** [comment]
Why not just use Jinja2?

**Comment by lorengordon** [comment]
@clinta, nice! If you need to get the path for an sls other than init.sls, try this:

```yaml
    - source: salt://{{ sls.split('.')[:-1] | join('/') }}/files/foo
```

That will take {{ sls }}, cut off the item following the last '.', and then join them with '/' to construct a path.

This one should work for any sls that is *not* init.sls. :/

**Comment by VynceMontgomery** [comment]
relative paths for the destination would also be potentially useful, especially to deal with things like different OSs putting home directories in different places (and some special users having homedirs in arbitrary places).

**Comment by v6** [comment]
// , This is one of my favorite feature requests. 

I can't help but think that there must be some sort of way to script this myself.

**Comment by aboe76** [comment]
If salt is reading the sls file in question there should also be a path about this file known,
otherwise how is salt reading this file.
this information should be made available as a {{ pwd }} 
and if you want to use it just use salt://{{ pwd }}/files

Why use {{ pwd }} anybody that has done something on a linux box should know about pwd, and what it stands for. this way the formula creator can always deduct where its working directory.

**Comment by aneeshusa** [comment]
Just looked into this, apparently @steverweber fixed this a year ago in #14535 :+1: . Also see #815, which is a partial dupe of this.

Motion to close with the ability to use {{ slspath }}.

**Comment by Mrten** [comment]
I'd like to test before closing but some minions are still on 2014.1 which does not have {{slspath}}. Also, I'm wondering whether mako got the slspath var?

**Comment by lorengordon** [comment]
@aneeshusa, I didn't realize that made it into 2015.5. I'll test it this week.

**Comment by aneeshusa** [comment]
As far as I can tell, the slspath context variable should be available for mako as well as for the other renderers that are wrapped in salt/utils/template.py, although you should try it out to make sure.

And yes, this got merged in August 2014 so I believe it should be available in 2015.5 and up.

Also out of curiosity, is 2014.1 still supported/how many versions does Salt support at a time?

**Comment by steverweber** [comment]
Use tplpath and tpldir.  I'll give a good example in a few hour

**Comment by steverweber** [comment]
here is a pillar dir:
 - vars.jinja
 - db.sls
 - app.sls
 - fe.sls

vars.jinja
```
{% load_yaml as vars %}
    database:
        host: oat-db.private.uwaterloo.ca
        port: 5432
        name: odyssey
        user: _oat_ui
        password: {{ salt['nacl.dec']('ur5MzPTVwdU/pUs0XMUGHBe3GjbbCuzSaWQ5KlKLFcESlhU8EuOTOOc42dFWrMinVgszswlPXf8P3OF9Po=') }}

    server:
        dns:
            oat-app-1.math.private.uwaterloo.ca:
            oat-app-2.math.private.uwaterloo.ca:
            oat-db-1.private.uwaterloo.ca:
            oat-db-2.private.uwaterloo.ca:
            oat-db.private.uwaterloo.ca:
            oat-fe-1.math.uwaterloo.ca:
            oat-feed-1.private.uwaterloo.ca:
        ha:
            fe: oat-fe-1.math.uwaterloo.ca
            db: oat-db.private.uwaterloo.ca
            feed: oat-feed-1.private.uwaterloo.ca
        lb:
            fe:
                oat-fe-1.math.uwaterloo.ca:
            app:
                oat-app-1.math.private.uwaterloo.ca:
                oat-app-2.math.private.uwaterloo.ca:
            db:
                oat-db-1.private.uwaterloo.ca:
                oat-db-2.private.uwaterloo.ca:
            feed:
                oat-feed-1.private.uwaterloo.ca:
{% endload %}
{# RENDER IP ADDRESSES FOR SERVERS.DNS #}
{%- for s in vars.server.dns %}
{%- do vars.server.dns.update({s: {'ip': salt['dnsutil.A'](s)[0]}}) %}
{%- endfor %}
```


db.sls
```
{%- from tpldir + '/vars.jinja' import vars %}

{{ sls }}.postgresql_ha:
    replica_user: _replication
    replica_password: {{ vars.database._replication }}
    # primary_host: {{ vars.server.ha.db }}
    primary_ipaddress: {{ vars.server.db_replication_link[grains['id']] }}
    primary_port: {{ vars.database.port }}
```

**Comment by steverweber** [comment]
here is a state dir:
 - _sdl/postgres/package:
    - init.sls
    - vars.jinja

vars.jinja
```
{%- from salt['file.normpath'](tpldir + '/../vars.jinja') import vars as _parent %}


{% load_yaml as _vars %}
    Default:
        _sls: {{ tpldot }}
        _parent: {{ _parent }}
    Debian:
        pkgs: ['postgresql']
    RedHat:
        pkgs: ['postgresql-server']
{% endload %}


{%- set vars = _vars.get('Default', {}) %}
{%- do vars.update(_vars.get(grains.get('os_family'), {})) %}
{%- do vars.update(_vars.get(grains.get('os'), {})) %}
{%- do vars.update(_vars.get(grains.get('osfinger'), {})) %}
{%- set vars = salt['pillar.get'](tpldot, default=vars, merge=True) %}
```

init.sls
```
{%- from tpldir + '/vars.jinja' import vars %}


{{ sls }}:
    pkg.installed:
        - pkgs: {{ vars.pkgs }}
        - reload_modules: true
        - watch_in:
            - service: {{ vars._parent._sls }}.service


    {%- if grains.get('osfinger') == 'CentOS Linux-7' %}
    # Cent OS does not initdb after install unlike Debian. so we preform it.
    cmd.wait:
        - name: 'postgresql-setup initdb'
        ## old way: - name: 'service postgresql initdb'
        - watch:
            - pkg: {{ sls }}
        - watch_in:
            - service: {{ vars._parent._sls }}.service
    {%- endif %}
```
