### ISSUE TITLE
git_pillar doesn't like "top" for the "name" option.

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#43496]
The following git_pillar config fails on 2017.7.1 and my minion doesn't get the pillar data from the git repo:

```
git_pillar_pubkey: /root/.ssh/id_rsa.pub                                        
git_pillar_privkey: /root/.ssh/id_rsa
git_pillar_provider: pygit2

ext_pillar:                                                                     
  - git:                                                                        
    - master git@github.com:UtahDave/test_pillar.git:
      - root: /                                                                 
      - mountpoint: /                                                           
      - name: top
```

I get the following error in the debug output:

```
[DEBUG   ] Set update lock for git_pillar remote 'master git@github.com:UtahDave/test_pillar.git'
[DEBUG   ] Fetching git_pillar remote 'master git@github.com:UtahDave/test_pillar.git'
[ERROR   ] Error occurred fetching git_pillar remote 'master git@github.com:UtahDave/test_pillar.git': Failed to authenticate SSH session: Callback returned error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1546, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygit2/remote.py", line 378, in fetch
    check_error(err)
  File "/usr/local/lib/python2.7/dist-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
GitError: Failed to authenticate SSH session: Callback returned error
[DEBUG   ] Removed update lock for git_pillar remote 'master git@github.com:UtahDave/test_pillar.git'
```

But if I change the config file to the following my minion gets the proper pillar data:

```
git_pillar_pubkey: /root/.ssh/id_rsa.pub                                        
git_pillar_privkey: /root/.ssh/id_rsa
git_pillar_provider: pygit2

ext_pillar:                                                                     
  - git:                                                                        
    - master git@github.com:UtahDave/test_pillar.git:
      - root: /                                                                 
      - mountpoint: /                                                           
      - name: top2
```

It appears that `top` is reserved or conflicts somehow.

Salt Versions Report:

```
root@issue1738:~# salt-master --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-128-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Is this a bug, or is `top` reserved somehow? If not a bug, then this should probably be documented along with any other reserved/problematic words.
