### ISSUE TITLE
Unable to manage file: 'ascii' codec can't decode - using file.managed for binary files

### ISSUE THREAD

**Issue by daveneeley** [saltstack/salt#43516]
### Description of Issue/Question
`file.managed` is a great state! I've used it for a lot of text files. In the past I've also used it for binary files that just need to get on disk and stay there. But now in 2017.7 it doesn't like my binary file so much. 

### Setup
Stick this in an sls file:
```
tomcat-server-database-jdbc-drivers-for-sql-server:
  file.managed:
    - name: {{ tomcat-home }}/lib/sqljdbc42.jar
    - source: https://some/server/microsoft/sqljdbc/6.0.8112.100/sqljdbc-6.0.8112.100-42jre8.jar
    - source_hash: https://some/server/microsoft/sqljdbc/6.0.8112.100/sqljdbc-6.0.8112.100-42jre8.jar
    - user: {{ tomcat.owner }}
    - group: {{ tomcat.group }}
    - makedirs: true
```
I doubt the jar itself is the problem because it opens fine with 7zip. But if you want to be specific you can grab it out of the tgz download from here: https://www.microsoft.com/en-us/download/details.aspx?id=11774

### Steps to Reproduce Issue
Run it.
```
----------
          ID: tomcat-server-database-jdbc-drivers-for-sql-server
    Function: file.managed
        Name: /opt/tomcat/lib/sqljdbc42.jar
      Result: False
     Comment: Unable to manage file: 'ascii' codec can't decode byte 0xb0 in position 10: ordinal not in range(128)
     Started: 17:33:32.466829
    Duration: 242.087 ms
     Changes:
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.7.0
       dateutil: Not Installed
      docker-py: 1.3.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
