### ISSUE TITLE
Add Orchestration Test to Auto Test Suite

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#43546]
This task is to monitor the addition of two tests to the auto test suite:

- [ ] T136969: Orchestration when target exists

PRECONDITIONS

In your env have a machine with a host name that starts with app, another machine and a foo folder in tmp /tmp/foo.

```
htop:
  salt.state:
    - tgt: 'app*'
    - sls:
      - htop

install_vim:
  salt.state:
    - tgt: '*'
    - sls:
      - vim

cmd.run:
  salt.function:
    - tgt: '*'
    - arg:
      - rm -rf /tmp/foo   
```

STEPS

1. `salt-run state.orchestrate <path to orchestrate file in file_roots>`

EXPECTED RESULTS

1. Machine with hostname app will get htop installed
2. All machines will get vim installed
3. All machines will get /tmp/foo removed

- [ ] T137089: Orchestration when target does not exist 

In your env DO NOT have a machine with a host name that starts with app, another machine and a foo folder in tmp /tmp/foo.

htop:
salt.state:
- tgt: 'app*'
- sls:
- htop

install_vim:
salt.state:
- tgt: '*'
- sls:
- vim

cmd.run:
salt.function:
- tgt: '*'
- arg:
- rm -rf /tmp/foo

STEPS

1. `salt-run state.orchestrate <path to orchestrate file in file_roots>`

EXPECTED RESULTS
Machine with hostname app will NOT get htop installed. No exceptions thrown.
All machines in the env will get vim installed
All machines in the env will get /tmp/foo removed
