### ISSUE TITLE
Error in documentation example for salt.state.module.run

### ISSUE THREAD

**Issue by cruscio** [saltstack/salt#43547]
### Description of Issue/Question
The example provided on https://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html#execution-of-salt-modules-from-within-states causes an error. 
 
### Setup
Copied the example for eventsviewer from https://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html#execution-of-salt-modules-from-within-states into a state file

### Steps to Reproduce Issue
Apply the state

#### First run 
State file is an exact copy from documentation. 

State file contents (/srv/salt/telegraf/init.sls):
```
eventsviewer:
  module.run:
    task.create_task:
      - name: events-viewer
      - user_name: System
      - action_type: Execute
      - cmd: 'c:\netops\scripts\events_viewer.bat'
      - trigger_type: 'Daily'
      - start_date: '2017-1-20'
      - start_time: '11:59PM'
```

State.apply Output:
```
root@saltstack:/srv# salt 'SUP00000290' state.apply telegraf
SUP00000290:
    Data failed to compile:
----------
    State 'eventsviewer' in SLS 'telegraf' is not formed as a list
ERROR: Minions returned with non-zero exit code
```	  
 
#### Second run 

Modified "task.create_task:" to "- task.create_task:"

State file contents (/srv/salt/telegraf/init.sls):
```
eventsviewer:
  module.run:
    - task.create_task:
      - name: events-viewer
      - user_name: System
      - action_type: Execute
      - cmd: 'c:\netops\scripts\events_viewer.bat'
      - trigger_type: 'Daily'
      - start_date: '2017-1-20'
      - start_time: '11:59PM'
```

State.apply Output:
```
root@saltstack:/srv# salt 'SUP00000290' state.apply telegraf
SUP00000290:
----------
          ID: eventsviewer
    Function: module.run
      Result: False
     Comment: Module function eventsviewer is not available
     Started: 14:43:47.837914
    Duration: 0.0 ms
     Changes:

Summary for SUP00000290
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
```

#### Master:
``` 
root@saltstack:/srv# salt -V
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-91-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

#### Minion:
```
C:\Users\cruscio>salt-call -V
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900
64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600 SP0 Multiprocessor Free

```
