### ISSUE TITLE
Add mine.get_docker Test to Auto Test Suite

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#43592]
This task is to monitor the addition of one test to the auto test suite:

- [ ] T136914: salt '*' mine.get_docker

PRECONDITIONS

insert salt.mine setup in minion config file

```
mine_functions:
  network.ip_addrs: [eth0]
  networkplus.internal_ip_addrs: []
  internal_ip_addrs:
    mine_function: network.ip_addrs
    cidr: 192.168.0.0/16
  ip_list:
    - mine_function: grains.get
    - ip_interfaces
```

Restart the salt-minion

STEPS:
Install docker:

`yum install docker`
Make a sls file:

```
docker-python-apt:
  pkg.installed:
    - name: python

docker-dependencies:
  pkg.installed:
    - pkgs:
      - iptables
      - ca-certificates
      - lxc
      - python-pip

docker-py:
  pip.installed:
    - require:
      - pkg: docker-dependencies

docker:
  service.running
```

Run the sls file

run:
`docker run -d -p 80:80 --name webserver nginx`
`docker ps` (to get the ID)

`salt \* dockerng.run_all <docker id> 'ls -l /etc'`
`salt '*' mine.get_docker`

EXPECTED RESULTS

```
minion:
    ----------
    nginx:
        ----------
        ipv4:
            ----------
            80:
                - 55.55.55.55:80
                - 127.0.0.1:80
```
