### ISSUE TITLE
 salt-ssh pillar top.sls merging

### ISSUE THREAD

**Issue by viktordaniel** [saltstack/salt#43660]
### salt-ssh does not merge pillar top files
When salt-ssh is configured with multiple pillar roots in same environment(base), the top.sls files will not be merged. The directory structure of pillars will be merged. 

The same configuration using master/minion with gitfs as a backend works and merges the top.sls as expected. 

### Setup
master:
```
log_file: var/log/salt/master
root_dir: .
file_roots:
    base:
        - /home/user/testenv/saltstates

pillar_roots:
    base: 
        -  /home/user/testenv/pillarsA
        -  /home/user/testenv/pillarsB
```
 /home/user/testenv/pillarsA/top.sls
```
base:
  'all':
    - match: nodegroup
    - access.all
```
 /home/user/testenv/pillarsB/top.sls
```
base:
  'restricted':
    - match: nodegroup
    - access.restricted
```

Both /home/user/testenv/pillarsA and /home/user/testenv/pillarsB contain **top.sls** file.

### Steps to Reproduce Issue
Following shows only pillars from the pillarsA above (always the first item of a pillar_roots/base list:
```
salt-ssh server1 pillar.items
````
If the content of the second top.sls file will be moved to the first top.sls file, it works

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 1.9.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.11.0-14-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
IIRC, salt will never see the top.sls in the pillarB environment.

The way the files are traversed, it looks for the file in the first root, if it is there, it stops looking.

So you will need to put the following in the top.sls file of the first one.

```
base:
  'all':
    - match: nodegroup
    - access.all
  'restricted':
    - match: nodegroup
    - access.restricted
```

Or have a separate top.sls pillar git repo to pull from.

The only time you can have more than one top.sls file is if they are in different environments.

Thanks,
Daniel
