### ISSUE TITLE
States and modules are missing in cache when using GitFS and GitPython

### ISSUE THREAD

**Issue by al31n** [saltstack/salt#43736]
### Description of Issue
After installing GitPython, I'm able to see the files from my repository when I run `salt-run fileserver.file_list`. However, I am not able to perform any sort of sync to my minions (ie. sync grains or modules, etc). I looked at the cache at /var/cache/salt/master/gitfs and I found two empty git repositories.

#### My git repository layout is
|->modules (where _modules, _grains lives)
|--> base
    |--> top.sls
    |--> ... states

#### /etc/salt/master
```
gitfs_provider: gitpython
gitfs_base: master
gitfs_remotes:
  - <git repo>:
    - name: base
    - root: base
    - mountpoint: salt://
  - <git repo>:
    - name: modules
    - root: modules
    - mountpoint: salt://modules
file_roots:
  base:
    - /srv/salt/base
    - /srv/salt/modules
extension_modules: salt://modules
```

### Versions Report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
