### ISSUE TITLE
salt-ssh: config.options not returning correct value in custom execution module

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#43743]
### Description of Issue/Question

Unable use `config.option` in custom execution module

### Setup
/srv/salt/_modules/mymod.py
```python
def __virtual__():
    return "mymod"

def test():
    return __salt__['config.option']('myoption') or "NOT AVAILABLE"
```

In master config have:
```python
myoption: "hey this works!"
```

### Steps to Reproduce Issue
```bash
root@master:~# salt-ssh -i centos7-2 mymod.test
centos7-2:
    NOT AVAILABLE
root@master:~# salt-ssh -i centos7-2 config.option myoption
centos7-2:
    hey this works!
```

### Versions Report
```yaml
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-92-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
