### ISSUE TITLE
archive.extracted throws an error for Windows minion

### ISSUE THREAD

**Issue by varun292006** [saltstack/salt#43741]
### Description of Issue/Question
archive.extracted throws an error for Windows minion

### Setup
Installation: Salt-2017.7.1
Master: Ubuntu
Minion: Windows 7

### Steps to Reproduce Issue
Create the state file as below:
```
  Extract the downloaded package:
    archive.extracted:
      - name: 'C:\\Users\\test_user\\Desktop\\my_dir\\tmp\\extracted\\my_pkg'
      - source: 'C:\\Users\\test_user\\Desktop\\my_dir\\tmp\\downloaded\\my_pkg.zip'
      - archive_format: zip
      - enforce_toplevel: False
      - use_cmd_unzip: True
```
Execute the state file using the below command from master:
```
# salt -t 60 'finance' state.apply update_agents.download_agent
jid: 20170926134114759266
finance:
----------
          ID: Extract the downloaded package  Function: archive.extracted
        Name: C:\Users\test_user\Desktop\my_dir\tmp\downloaded\my_pkg
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1837, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\archive.py", line 1224, in extracted
                  __salt__['file.makedirs'](name, user=user)
              TypeError: makedirs_() got an unexpected keyword argument 'user'
     Started: 13:41:27.655000
    Duration: 5195.0 ms
     Changes:  
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free

```
