### ISSUE TITLE
Jinja parsing error with minion version 2017.7.1

### ISSUE THREAD

**Issue by soodr** [saltstack/salt#43787]
### Description of Issue/Question
Error in parsing  state file  after upgrading the Salt minion version from **2016.3.3** to **2017.7.1**

Minion output log
```
2017-09-27 23:03:36,349 [salt.state       ][CRITICAL][1424] Rendering SLS 'base:tssa' failed: expected alphabetic or numeric character, but found ' '; line 22

---
[...]
    set_grain:
      grains.present:
        - name: 'awsTags'
        - value:
          - rohit-test
          - & {Invoke-RestMethod 'http://169.254.169.254/latest/meta-data/local-ipv4'}    <======================
          - rohit-test-tssa-1
        - require_in:
          - module: update_mine
[...]
```
### Setup

Snippet of the state file

```
 {% set OrderedDict = salt['cmd.script']('salt://getServiceId.ps1', shell='powershell', output_loglevel='quiet') %}
  {% set serviceId = OrderedDict['stdout'] %}
  {% set privateIp = salt['cmd.run']("powershell -Command \"& {Invoke-RestMethod 'http://169.254.169.254/latest/meta-data/local-ipv4'}\"") %}

    set_grain:
      grains.present:
        - name: 'awsTags'
        - value:
          - {{ serviceId }}
          - {{ privateIp }}
          - {{ instanceName }}
        - require_in:
          - module: update_mine
```
### Steps to Reproduce Issue
On the minion : 
```
salt-call state.show_sls <state_file>
```
### Versions Report

Minion:

```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
```

Master:

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.1.2
       cherrypy: unknown
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 0.3.0-beta2
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: 0.22
           Mako: 1.0.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.7.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.1.1503 Core
```
