### ISSUE TITLE
salt.pillar.file_tree not merging nested nodegroups data

### ISSUE THREAD

**Issue by 3add3287** [saltstack/salt#43788]
### Description of Issue/Question
Pillar data using file_tree's nodegroups is not properly merged if these conditions are met:

- a minion belongs to more than one nodegroup
- there is pillar data placed in more than one nodegroup directory
- the data in the nodegroup directory is strutted in some hierarchical way with same keys at the top of the tree

This either makes proper structuring of nodegroup based pillar data in file_tree impossible.

Considering files placed in "/file_tree/hosts/<minion id>/..." are merged while files put into different nodegroups are this seems like a bug to me.

### Setup
- master.conf:
```
ext_pillar:
  - file_tree:
    root_dir: /file_tree
```
- /filetree/nodegroups/onegroup/SomethingHighlevel/Anything/foobar/FirstData.suffix
```
some textual content
```
- /filetree/nodegroups/anothergroup/SomethingHighlevel/Anything/foobar/SecondData.suffix
```
some textual content
```

### Steps to Reproduce Issue
Setup file_tree pillar as described above and run pillar.items. Only pillar data from one of the files above ("FirstData.suffix" or "SecondData.suffix") is shown, not both. What is shown depends on the order of the nodegroups.

### Versions Report
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep  2 2017, 15:19:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE
         system: FreeBSD
        version: Not Installed
```
