### ISSUE TITLE
salt.states.file.line ignoring the create parameter

### ISSUE THREAD

**Issue by jorgelbg** [saltstack/salt#43826]
### Description of Issue/Question

When trying to use the `create: True` parameter for the `salt.states.file.line` in a custom state the file is not created, failing with the error: `/usr/local/etc/php/ext-90-blackfire.ini: file not found`. The [related documentation](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.line) shows that the `create` parameter is available.

### Setup

Example state:

```yaml
create-extension-config:
  file.line:
    - name: /usr/local/etc/php/ext-90-blackfire.ini
    - content: 'extension=blackfire.so'
    - match: '^extension=blackfire\.so$'
    - mode: 'insert'
    - location: 'end'
    - create: True
```

### Versions Report

So far we've seen this behaviour with:

```
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Aug 14 2017, 14:07:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 10.3-RELEASE
         system: FreeBSD
        version: Not Installed
```

and

```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: 5.4.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Aug  7 2017, 14:19:48)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: US-ASCII
        machine: amd64
        release: 10.3-RELEASE-p18
         system: FreeBSD
        version: Not Installed
```

**Comment by gtmanfred** [comment]
Can you test this?

```
/usr/local/etc/php:
  file.directory:
    - makedirs: True
create-extension-config:
  file.line:
    - name: /usr/local/etc/php/ext-90-blackfire.ini
    - content: 'extension=blackfire.so'
    - match: '^extension=blackfire\.so$'
    - mode: 'insert'
    - location: 'end'
    - create: True
```

It looks like the directory path might not be there for the file to be created in.

I got the same error before the directory was created, once I add the file.directory state, it all works.

**Comment by jorgelbg** [comment]
I've double checked that the path `/usr/local/etc/php/` exists:

```
root@vm-test:~ # ll -l /usr/local/etc/php/
total 16
-rw-r--r--  1 root  wheel  26 Dec 14  2016 ext-10-opcache.ini
-rw-r--r--  1 root  wheel  21 Dec 14  2016 ext-18-session.ini
-rw-r--r--  1 root  wheel  18 Jan  4  2017 ext-20-amqp.ini
-rw-r--r--  1 root  wheel  18 Aug 14 14:14 ext-20-apcu.ini
-rw-r--r--  1 root  wheel  19 Dec 14  2016 ext-20-ctype.ini
-rw-r--r--  1 root  wheel  18 Jan  4  2017 ext-20-curl.ini
-rw-r--r--  1 root  wheel  17 Dec 14  2016 ext-20-dom.ini
...
```

When running the original state I'm still able to reproduce the error (and the directory exists):

```
----------
          ID: create-extension-config
    Function: file.line
        Name: /usr/local/etc/php/ext-90-blackfire.ini
      Result: False
     Comment: /usr/local/etc/php/ext-90-blackfire.ini: file not found
     Started: 14:35:00.427378
    Duration: 1.339 ms
     Changes:
```

Even with the new `file.directory` I still got the same output: 

```
----------
          ID: /usr/local/etc/php
    Function: file.directory
      Result: True
     Comment: The directory /usr/local/etc/php is in the correct state
     Started: 14:36:35.082866
    Duration: 0.813 ms
     Changes:
----------
          ID: create-extension-config
    Function: file.line
        Name: /usr/local/etc/php/ext-90-blackfire.ini
      Result: False
     Comment: /usr/local/etc/php/ext-90-blackfire.ini: file not found
     Started: 14:36:35.083844
    Duration: 1.358 ms
     Changes:
```

**Comment by gtmanfred** [comment]
Just to double check, I installed 2017.7 on a freebsd box, but I am still seeing it work.

```
[root@freebsd-2gb-sfo1-01 /usr/local/etc/salt/states]# salt-call --local state.apply test
[WARNING ] State for file: /usr/local/etc/php/ext-90-blackfire.ini - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
local:
----------
          ID: create-extension-config
    Function: file.line
        Name: /usr/local/etc/php/ext-90-blackfire.ini
      Result: True
     Comment: Changes were made
     Started: 15:32:14.759838
    Duration: 23.879 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -0,0 +1 @@
                  +extension=blackfire.so

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  23.879 ms
```

Can you try upgrading to 2017.7?  Or how can I install the 2016.11 version on freebsd (sorry, I am not super familiar with how freebsd packages work)

Thanks,
Daniel

**Comment by jorgelbg** [comment]
I've updated to v2017.1, checked with the latest version and running the state seems to work fine, but on test mode (`test=True`) seems to fail with the previous error (even with the `file.directory` entry). 

Will downgrade and test on the old version as well to double check if is only happening while testing our highstate.

**Comment by jorgelbg** [comment]
Ok, so took a closer look and if I actually execute the state works as expected, the file gets created. But if I try to only test the state with `test=True` then it fails, even with the `file.directory` added before the `file.line`:

```
root@cd3f8d61db7c:/# salt-call state.sls blackfire-probe.config test=True
[WARNING ] State for file: /usr/local/etc/php/ext-90-blackfire.ini - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
[ERROR   ] /usr/local/etc/php/ext-90-blackfire.ini: file not found
local:
----------
          ID: /usr/local/etc/php
    Function: file.directory
      Result: None
     Comment: The following files will be changed:
              /usr/local/etc/php: directory - new
     Started: 14:36:35.696212
    Duration: 4.158 ms
     Changes:
----------
          ID: create-extension-config
    Function: file.line
        Name: /usr/local/etc/php/ext-90-blackfire.ini
      Result: False
     Comment: /usr/local/etc/php/ext-90-blackfire.ini: file not found
     Started: 14:36:35.700486
    Duration: 2.287 ms
     Changes:

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    1
------------
Total states run:     2
Total run time:   6.445 ms
```
Seems like the issue only happens if we're testing the state and the file haven't been created yet. Even if I manually create the `path` and then try to test, the state keeps failing:

The `path` exists:
```
----------
          ID: /usr/local/etc/php
    Function: file.directory
      Result: True
     Comment: The directory /usr/local/etc/php is in the correct state
     Started: 14:49:09.960468
    Duration: 3.739 ms
     Changes:
```
But still the state fails
```
----------
          ID: create-extension-config
    Function: file.line
        Name: /usr/local/etc/php/ext-90-blackfire.ini
      Result: False
     Comment: /usr/local/etc/php/ext-90-blackfire.ini: file not found
     Started: 14:49:09.964296
    Duration: 1.545 ms
     Changes:
```
