### ISSUE TITLE
E: Version 'latest' for 'package' was not found

### ISSUE THREAD

**Issue by patryk** [saltstack/salt#43824]
### Description of Issue/Question
Salt (at least salt-ssh) started giving errors on installing latest versions of packages. It's happening for me for Ubuntu minions installing:
- unattended-upgrades
- plexmediaserver

### Setup
state file:
```
python-apt:
  pkg.installed:
    - version: latest

apt-transport-https:
  pkg.installed:
    - refresh: False

plex.repo:
  pkgrepo.managed:
    - name: deb https://downloads.plex.tv/repo/deb/ public main
    - file: /etc/apt/sources.list.d/plexmediaserver.list
    - key_url: https://downloads.plex.tv/plex-keys/PlexSign.key
    - require:
      - pkg: python-apt
      - pkg: apt-transport-https

plexmediaserver:
  pkg.installed:
    - version: latest
```

### Steps to Reproduce Issue
```
$ salt-ssh '*' state.apply
[...]
  Name: python-apt - Function: pkg.installed - Result: Clean Started: - 08:43:08.551818 Duration: 155.466 ms
  Name: apt-transport-https - Function: pkg.installed - Result: Clean Started: - 08:43:08.707516 Duration: 30.209 ms
  Name: deb https://downloads.plex.tv/repo/deb/ public main - Function: pkgrepo.managed - Result: Clean Started: - 08:43:08.750541 Duration: 99.047 ms
----------
          ID: plexmediaserver
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:

              errors:
                  - Running scope as unit run-rd9834bc3e8214e21a91c9983749d31ef.scope.
                    E: Version 'latest' for 'plexmediaserver' was not found
     Started: 08:43:08.849787
    Duration: 848.275 ms
     Changes:
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Feb  7 2017, 00:08:15)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 16.7.0
         system: Darwin
        version: 10.12.6 x86_64
```
