### ISSUE TITLE
state.apply tries to install packages before repository

### ISSUE THREAD

**Issue by kirillvelikov** [saltstack/salt#43833]
### Description of Issue/Question
Calling each state individually works. Like:
``salt app1 state.sls common``
``salt app1 state.sls php``
Applying both state using ``state.apply`` - doesnt work. For some reason salt is trying everything at once skipping the php repo. At the end fails with:
```
app1:
----------
          ID: common_install_repo_epel
    Function: pkg.installed
        Name: epel-release
      Result: False
     Comment: The following packages failed to install/update: php71
              6 targeted packages were installed/updated.
              The following packages were already installed: tar, salt-minion, curl
     Started: 17:11:19.222387
    Duration: 103005.922 ms
     Changes:  
```
### Setup
Here is my config:
top.sls
``` yaml
base:
  '*':
    - common
    - php
```

commo/init.sls
``` yaml
include:
  - common.pkgs
  - common.config
```

common.pkgs.sls
``` yaml
common_install_repo_epel:
  pkg.installed:
    - name: epel-release

common_install_packages:
  pkg.installed:
    - pkgs:
      - curl
      - psutils
      - psmisc
      - screen
    - require:
      - pkg: common_install_repo_epel
```

php/init.sls
``` yaml
include:
  - php.pkgs
  - php.config
```

php/pkgs.sls
``` yaml
php_install_remi_repo:
  pkg.installed:
    - sources:
      - remi-release: http://rpms.remirepo.net/enterprise/remi-release-7.rpm

php_install_php7:
  pkg.installed:
    - pkgs:
      - php71
    - require:
      - pkg: php_install_remi_repo
```

### Steps to Reproduce Issue
```salt app1 state.apply```

### Versions Report
There is no difference between master and minion in this case.
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 4.10.17-2-pve
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

Please correct me if there is a misconfiguration!
