### ISSUE TITLE
states.sysrc.managed: state always flagged as having changed if value not enclosed in double quotes

### ISSUE THREAD

**Issue by 3add3287** [saltstack/salt#43879]
### Description of Issue/Question
If values for a  sysrc.managed state isn't enclosed in double quotes, the id is flagged as having changed sysrc on the minion, which causes problems for watch_in for example

### Setup

random.sls:
```
ntpd_enable:
  sysrc.managed:
    - value: "YES"

ntpd_sync_on_start:
  sysrc.managed:
    - value: YES

```

### Steps to Reproduce Issue
Take the .sls above and run it. Once completed, run it again. "ntpd_enable" and "ntpd_sync_on_start" should not be flagged as having changed in the 2nd run. However, "ntpd_sync_on_start" will be reported as having changed while "ntpd_enable" isn't.

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Sep 26 2017, 01:13:44)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: US-ASCII
        machine: amd64
        release: 11.1-RELEASE-p1
         system: FreeBSD
        version: Not Installed
```
