### ISSUE TITLE
[salt-ssh] PasswordAuthentication=no when using --askpass

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#43906]
### Description of Issue/Question
salt-ssh fails while trying to run ssh with `PasswordAuthentication=no` when `--askpass` is specified.

### Setup
Ubuntu 16.04 with salt-ssh `2016.11.7`.

### Steps to Reproduce Issue
```bash
# salt-ssh -l debug -i --askpass --user=vagrant --roster-file=myroster 'ubuntu12*' -r 'id'
...
[DEBUG   ] Executing command: ssh 192.168.11.22 -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o Con
nectTimeout=65 -o StrictHostKeyChecking=no -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=vagrant  id
[DEBUG   ] Child Forked! PID: 15225  STDOUT_FD: 10  STDERR_FD: 13
[DEBUG   ] Terminal Command: /bin/sh -c ssh 192.168.11.22 -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication
=no -o ConnectTimeout=65 -o StrictHostKeyChecking=no -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=vagrant  id
Permission denied for host ubuntu12.local, do you want to deploy the salt-ssh key? (password required):
[Y/n] n
[DEBUG   ] LazyLoaded nested.output
ubuntu12.local:
    ----------
    retcode:
        255
    stderr:
        Permission denied (publickey,password).
    stdout:
```

### Versions Report
```yaml
Salt Version:
           Salt: 2016.11.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-92-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
