### ISSUE TITLE
event.send not marked as changed

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#43914]
### Description of Issue/Question
I have multiple event.sends being executed on every highstate.  Every time a highstate happens, every event.send shows as a change.  

Is there a way to mark these `result=true, Changes= empty` so they do not show up in the highstate results?

My goal here is to get a cleaner highstate results to it is easier to see the real changes.

### Setup
```
security_groups_enabled:
  event.send:
    - name: mycompany/security_groups
    - data:
        security_groups: {{ salt['pillar.get']('server_info:security_groups', []) }}
        hostname: {{ salt['grains.get']('id') }}
        instance_id: {{ salt['grains.get']('instance-id')}}
```
results in 
```
          ID: security_groups_enabled
    Function: event.send
        Name: riskalyze/security_groups
      Result: True
     Comment: Event fired
     Started: 21:59:13.443210
    Duration: 1.675 ms
     Changes:
              ----------
              data:
                  ----------
                  hostname:
                      xxxxxxxxxxxxx
                  instance_id:
                      i-xxxxxxxxxxxxx
                  security_groups:
                      - sgBase
                      - sgApp
              tag:
                  riskalyze/security_groups
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
