### ISSUE TITLE
kmod.present doesn't work with compiled-in modules

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#43945]
### Description of Issue/Question

If module is compiled in the kernel, `kmod.present` fails:

```
          ID: nf_conntrack
    Function: kmod.present
      Result: False
     Comment: Kernel module nf_conntrack is unavailable
     Started: 00:45:19.472246
    Duration: 29.44 ms
     Changes:
```

### Setup

```yaml
nf_conntrack:
  kmod.present: []
```

```
$ zcat /proc/config.gz | grep ^CONFIG_NF_CONNTRACK=
CONFIG_NF_CONNTRACK=y
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.9
        machine: x86_64
        release: 4.9.41-cloudflare-2017.8.2
         system: Linux
        version: debian 8.9
```
