### ISSUE TITLE
state.sls_id should take the pillar argument

### ISSUE THREAD

**Issue by calvinhp** [saltstack/salt#43961]
### Description of Issue/Question

Given a state file that uses `pillar.get` for one of its values, you should be able to pass in from the command line a `pillar` argument just like you can for `state.apply` and have the state use the values given on the CLI.
### Setup

Given a state that contains an ID that uses a Pillar to grab a value

```yaml
/etc/varnish/default.vcl:¬
    file.managed:¬
      - makedirs: true¬
      - source: salt://varnish/files/default.jinja¬
      - template: jinja¬
      - replace: {{ salt['pillar.get']('varnish:replaceconf', False) }}¬
      - require_in:¬
        - file: {{ varnish.unit }}¬
```

### Steps to Reproduce Issue

Running the following should replace the value used in the state file based on the pillar passed in

```console
$ sudo salt-call --local --file-root /srv/formulas/varnish-formula state.apply varnish.conf pillar='{"varnish":{"replaceconf":True}}'
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
