### ISSUE TITLE
Multiple mounts with same device name create/update single fstab entry [salt.states.mount]

### ISSUE THREAD

**Issue by michailsideris-gvf** [saltstack/salt#43964]
### Description of Issue/Question
In our company we use [MooseFS](https://moosefs.com/) in order order to store a variety of data. From the [manual](https://moosefs.com/Content/Downloads/moosefs-3-0-users-manual.pdf)

> To enable MooseFS Client automount during boot, first of all check if the fuse and fuse-libs
> packages are installed. If fuse and fuse-libs packages are installed, add similar entry to the
> following one in /etc/fstab:
> 
> ```
> mfsmount /mnt/mfs fuse defaults,mfsmaster=mfsmaster.example.lan,mfsport=9421 0 0
> ```

I defined two MooseFS mounts using salt states and I ended up with one fstab entry instead of two. Manually adding the following fstab entries provides the desired result:

```
mfsmount    /mnt/kvm   fuse    defaults,_netdev,mfsmaster=mfs-master,mfsport=9421,mfssubfolder=/kvm   0 0
mfsmount    /mnt/sw    fuse    defaults,_netdev,mfsmaster=mfs-master,mfsport=9421,mfssubfolder=/sw    0 0
```

### Setup
```
/mnt/kvm:
  file.directory: []
  mount.mounted:
    - device: mfsmount
    - fstype: fuse
    - mount: False
    - opts: defaults,_netdev,mfsmaster=mfs-master,mfsport=9421,mfssubfolder=/kvm
    - require:
      - file: /mnt/kvm

/mnt/sw:
  file.directory: []
  mount.mounted:
    - device: mfsmount
    - fstype: fuse
    - mount: False
    - opts: defaults,_netdev,mfsmaster=mfs-master=9421,mfssubfolder=/sw
    - require:
      - file: /mnt/sw
```

### Steps to Reproduce Issue
1. Setup MooseFS cluster
2. Create two MooseFS shares and export them
3. Define two MooseFS mounts via salt states as indicated above.
4. Running highstate leaves only one entry in /etc/fstab

### Versions Report
salt master:

```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

salt minion:

```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
