### ISSUE TITLE
Templating pillar top.sls with pillar.get

### ISSUE THREAD

**Issue by absolutejam** [saltstack/salt#43972]
### Setup

The following works to provide minion-specific pillar data at the path `/srv/pillar/minion/<host name>.sls`. This uses grains.
```yaml
/srv/pillar/top.sls

base:
  '*':
     - minion.{{ salt.grains.get('host') }}
     - ignore_missing: true
```

I tried something similar with pillar data, but I'm not having any joy. I'm not sure if this is because Pillar data cannot reference other pillar data?

```yaml
/srv/pillar/top.sls

base:
{% for nodegroup in salt.pillar.get('nodegroups') %}
  {{ nodegroup }}:
    - match: nodegroup
    - nodegroup.{{ nodegroup }}
    - ignore_missing: true
{% endfor %}
```

Is this currently possible?

### Versions Report

2017.7.1 everywhere.
