### ISSUE TITLE
Queue argument passed to state.apply is ignored

### ISSUE THREAD

**Issue by jessebye** [saltstack/salt#43984]
### Description of Issue/Question
The `queue: True` argument we are trying to pass to a state.apply seems to get ignored, as the minion doesn't run the state saying "The function "state.apply" is running as PID xxxxxx and was started at xxxxxx with jid xxxxxxx". 

### Setup
```
{% set data = data.get('data', {}) %}

security_groups_enabled:
  local.state.apply:
    - tgt: '*salt*'
    - queue: True
    - arg:
      - states/aws/security_groups
    - kwarg:
        pillar:
          security_groups_data: {{ data }}
```

### Steps to Reproduce Issue
Run above state and observe the minion output; restart master and minion and re-run... no change.

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by max-arnold** [comment]
@jessebye `queue` is a kwarg for the `state.apply` function and should be placed on the same level as the `pillar` kwarg:

```
{% set data = data.get('data', {}) %}

security_groups_enabled:
  local.state.apply:
    - tgt: '*salt*'
    - arg:
      - states/aws/security_groups
    - kwarg:
        queue: True
        pillar:
          security_groups_data: {{ data }}
```
