### ISSUE TITLE
Error while executing mysql_query.run_file

### ISSUE THREAD

**Issue by varun292006** [saltstack/salt#44004]
### Description of Issue/Question
Error while executing mysql_query.run_file state.

### Setup
Salt version - 2017.7.2
1 Master
3 Windows minions

### Steps to Reproduce Issue
Create SLS file with below content
```
Executing file query:
  mysql_query.run_file:
    - name: test1
    - database: mysql
    - connection_db: mysql
    - query_file: 'C:\Users\test_user\Desktop\tmp.sql'
    - connection_host: '192.168.133.180'
    - connection_user: 'root'
    - connection_pass: 'rootroot'
    - connection_port: 3306
```
Create a query file on the database host for eg. tmp.sql with below content:
SELECT * FROM customers;

Execute the state file

The execution will fail with below error
```
          ID: Executing file query
    Function: mysql_query.run_file
        Name: test1
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1843, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\mysql_query.py", line 159, in run_file
                  query_result = __salt__['mysql.file_query'](database, query_file, **connection_args)
                File "c:\salt\bin\lib\site-packages\salt\modules\mysql.py", line 731, in file_query
                  ret['columns'] += query_result['columns']
              TypeError: unsupported operand type(s) for +=: 'int' and 'tuple'
     Started: 13:09:31.283000
    Duration: 15.0 ms
     Changes:   
```

### Versions Report
Master
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-35-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Minion
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor
```
