### ISSUE TITLE
salt-ssh '*' vault.list_secrets doesn't work

### ISSUE THREAD

**Issue by danbst** [saltstack/salt#44036]
### Description of Issue/Question
`salt-ssh '*' vault.list_secrets "secrets"` doesn't work

### Setup
master
```
root_dir: ./.

vault:
    url: https://vault-01:8200
    auth:
        method: token
        token: <<snip>>
```
Saltfile
```
salt-ssh:
  config_dir: .
  ssh_max_procs: 30
  ssh_wipe: True
```
roster
```
danbst-test-08:
    host: 10.0.5.184
    user: ubuntu
    sudo: True
```

### Steps to Reproduce Issue
```
$ salt-ssh '*' vault.list_secrets "secrets"
danbst-test-08:
    ----------
    retcode:
        0
    stderr:
        Error running 'vault.list_secrets': 'vault.make_request'
    stdout:
```
In my debugging session I found that in this piece of code (`vault.list_secrets()` function)
```
    try:
        url = 'v1/{0}'.format(path)
        dir(__utils__['vault'])
        response = __utils__['vault.make_request']('LIST', url)
        if response.status_code != 200:
```
the `__utils__['vault.make_request']` isn't available, like Vault utils is not loaded.

Perhaps this is a limitation of `salt-ssh`, but is there any way to run these function without proper master-minion setup?

### Versions Report
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Sep 16 2017, 17:49:51)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 3.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.9.53
         system: Linux
        version: Not Installed
```
