### ISSUE TITLE
pkg.version not available on windows minion version 2017.7.2

### ISSUE THREAD

**Issue by airstream** [saltstack/salt#44105]
### Description of Issue/Question
When I run command on Windows minion version **2017.7.2** (Windows 10 Salt-Minion-2017.7.2-Py2-AMD64-Setup.exe)
`salt-call pkg.version "Adobe Acrobat Reader DC"`

Output shows the following error: 
```
local:
    ----------
    Adobe Acrobat Reader DC:
        not available
```

When I run command on Windows minion version **2016.11.8** (Windows 10 Salt-Minion-2016.11.8-AMD64-Setup.exe)
`salt-call pkg.version "Adobe Acrobat Reader DC"`

Output shows the correct version of Adobe Acrobat Reader DC software installed:
```
local:
    17.012.20098
```

### Setup
Issue from the command line

### Steps to Reproduce Issue
Run `salt-call pkg.version "Adobe Acrobat Reader DC"` command or 
`salt-call pkg.version "other software"` on Windows minion version **2017.7.2** (Windows 10)

Command `salt-call pkg.list_pkgs"` is helping to find any software installed on Windows computer.

### Versions Report
Windows minion version **2017.7.2**
```
salt-minion --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1257
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.14393  Multiprocessor Free
```

Windows minion version **2016.11.8**
```
salt-minion --versions-report
Salt Version:
           Salt: 2016.11.8

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.14393  Multiprocessor Free
```

Salt Master **2017.7.2** 
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-97-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
