### ISSUE TITLE
Have mod_watch in pkg state module support cache_valid_time bypass

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#44115]
### Description of Issue/Question
I like `pkg.uptodate` for our dev VMs, however it should be possible to override that value when changes to `sources.list` have been made so such changes will be reflected immediately within the package index. I feel that adding this functionality to `mod_watch` would be the way to go.

### Setup
Example state sls file:
```
{%- for repo, settings in salt['pillar.get']('repositories', {}).items() %}
{{ repo }}:
  pkgrepo.managed:
{%- for setting, value in settings.items() %}
    - {{ setting }}: {{ value }}
    - refresh_db: False
{%- endfor %}
    - require_in:
      - pkg: Perform updates
{%- endfor %}

# Depending on the changes required, Salt may sometimes get confused
# and execute 'apt-get update' multiple times unnecessarily. In theory
# the _context_ dunder dictionary should prevent this if the state
# module is coded correctly, so there must be a bug somewhere
# (although I have yet to investigate).
#
# In the meantime, the simple work-around is to take care of the
# refresh manually.
Perform updates:
  pkg.uptodate:
    # Run 'apt-get update' if the index is at least 12 hours old.
    - cache_valid_time: 43200
```

And associated pillar file (for an Ubuntu 14.04 trusty machine):
```
# Valid repository settings are documented here:
# https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkgrepo.html#salt.states.pkgrepo.managed

repositories:
{%- for component in ('main', 'restricted', 'universe') %}
{%- for dist in ('trusty', 'trusty-updates') %}
  deb http://archive.ubuntu.com/ubuntu {{ dist }} {{ component }}:
    enabled: True
    dist: {{ dist }}
    comps: {{ component }}
    file: /etc/apt/sources.list
{%- endfor %}

  deb http://security.ubuntu.com/ubuntu trusty-security {{ component }}:
    enabled: True
    dist: trusty-security
    comps: {{ component }}
    file: /etc/apt/sources.list
{%- endfor %}
```

### Steps to Reproduce Issue
```
$ sudo salt-call state.sls repositories
...
local:
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty main
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty main' already configured
     Started: 05:54:54.183645
    Duration: 38.061 ms
     Changes:   
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty-updates main
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty-updates main' already configured
     Started: 05:54:54.221974
    Duration: 27.434 ms
     Changes:   
----------
          ID: deb http://security.ubuntu.com/ubuntu trusty-security main
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://security.ubuntu.com/ubuntu trusty-security main' already configured
     Started: 05:54:54.249626
    Duration: 27.657 ms
     Changes:   
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty restricted
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty restricted' already configured
     Started: 05:54:54.277494
    Duration: 27.649 ms
     Changes:   
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty-updates restricted
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty-updates restricted' already configured
     Started: 05:54:54.305360
    Duration: 26.927 ms
     Changes:   
----------
          ID: deb http://security.ubuntu.com/ubuntu trusty-security restricted
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://security.ubuntu.com/ubuntu trusty-security restricted' already configured
     Started: 05:54:54.332495
    Duration: 27.285 ms
     Changes:   
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty universe
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty universe' already configured
     Started: 05:54:54.360014
    Duration: 27.34 ms
     Changes:   
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty-updates universe
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty-updates universe' already configured
     Started: 05:54:54.387562
    Duration: 27.41 ms
     Changes:   
----------
          ID: deb http://security.ubuntu.com/ubuntu trusty-security universe
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://security.ubuntu.com/ubuntu trusty-security universe' already configured
     Started: 05:54:54.416370
    Duration: 28.85 ms
     Changes:   
----------
          ID: Perform updates
    Function: pkg.uptodate
      Result: True
     Comment: Upgrade ran successfully
     Started: 05:54:55.194368
    Duration: 635.263 ms
     Changes:   

Summary for local
-------------
Succeeded: 10
Failed:     0
-------------
Total states run:     10
Total run time:  893.876 ms
$
```
All looks good... except ops I forgot to add the `multiverse` component. Hence I now adjust line 4 of the pillar to look as follows:
```
{%- for component in ('main', 'restricted', 'universe', 'multiverse') %}
```
And re-running:
```
$ sudo salt-call state.sls repositories
local:
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty main
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty main' already configured
     Started: 05:55:07.877510
    Duration: 38.524 ms
     Changes:   
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty-updates main
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty-updates main' already configured
     Started: 05:55:07.916248
    Duration: 28.444 ms
     Changes:   
----------
          ID: deb http://security.ubuntu.com/ubuntu trusty-security main
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://security.ubuntu.com/ubuntu trusty-security main' already configured
     Started: 05:55:07.944895
    Duration: 28.624 ms
     Changes:   
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty restricted
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty restricted' already configured
     Started: 05:55:07.973716
    Duration: 28.559 ms
     Changes:   
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty-updates restricted
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty-updates restricted' already configured
     Started: 05:55:08.002474
    Duration: 29.53 ms
     Changes:   
----------
          ID: deb http://security.ubuntu.com/ubuntu trusty-security restricted
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://security.ubuntu.com/ubuntu trusty-security restricted' already configured
     Started: 05:55:08.032202
    Duration: 32.351 ms
     Changes:   
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty universe
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty universe' already configured
     Started: 05:55:08.064754
    Duration: 28.798 ms
     Changes:   
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty-updates universe
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://archive.ubuntu.com/ubuntu trusty-updates universe' already configured
     Started: 05:55:08.093765
    Duration: 28.974 ms
     Changes:   
----------
          ID: deb http://security.ubuntu.com/ubuntu trusty-security universe
    Function: pkgrepo.managed
      Result: True
     Comment: Package repo 'deb http://security.ubuntu.com/ubuntu trusty-security universe' already configured
     Started: 05:55:08.122962
    Duration: 28.925 ms
     Changes:   
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty multiverse
    Function: pkgrepo.managed
      Result: True
     Comment: Configured package repo 'deb http://archive.ubuntu.com/ubuntu trusty multiverse'
     Started: 05:55:08.152112
    Duration: 118.931 ms
     Changes:   
              ----------
              repo:
                  deb http://archive.ubuntu.com/ubuntu trusty multiverse
----------
          ID: deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse
    Function: pkgrepo.managed
      Result: True
     Comment: Configured package repo 'deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse'
     Started: 05:55:08.271239
    Duration: 84.922 ms
     Changes:   
              ----------
              repo:
                  deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse
----------
          ID: deb http://security.ubuntu.com/ubuntu trusty-security multiverse
    Function: pkgrepo.managed
      Result: True
     Comment: Configured package repo 'deb http://security.ubuntu.com/ubuntu trusty-security multiverse'
     Started: 05:55:08.356363
    Duration: 87.261 ms
     Changes:   
              ----------
              repo:
                  deb http://security.ubuntu.com/ubuntu trusty-security multiverse
----------
          ID: Perform updates
    Function: pkg.uptodate
      Result: True
     Comment: Upgrade ran successfully
     Started: 05:55:09.181975
    Duration: 687.119 ms
     Changes:   

Summary for local
-------------
Succeeded: 13 (changed=3)
Failed:     0
-------------
Total states run:     13
Total run time:    1.251 s
$
```
Note the text in the final `Perform updates` block "Upgrade ran successfully", however it appears on my screen as green text and there is nothing under `Changes:`. And if we inspect something from the `multiverse` component::
```
$ apt-cache policy ttf-mscorefonts-installer
ttf-mscorefonts-installer:
  Installed: 3.4+nmu1ubuntu1
  Candidate: 3.4+nmu1ubuntu1
  Version table:
 *** 3.4+nmu1ubuntu1 0
        100 /var/lib/dpkg/status
$
```
There is no repository associated with this package. If that package wasn't already installed, attempts to install it would have failed.

What I would actually like to see is something like the following (note this is the same as the above only I have changed the `require_in` line to `watch_in` and added the `refresh_on_watch` option):
```
{%- for repo, settings in salt['pillar.get']('repositories', {}).items() %}
{{ repo }}:
  pkgrepo.managed:
{%- for setting, value in settings.items() %}
    - {{ setting }}: {{ value }}
    - refresh_db: False
{%- endfor %}
    - watch_in:
      - pkg: Perform updates
{%- endfor %}

# Depending on the changes required, Salt may sometimes get confused
# and execute 'apt-get update' multiple times unnecessarily. In theory
# the _context_ dunder dictionary should prevent this if the state
# module is coded correctly, so there must be a bug somewhere
# (although I have yet to investigate).
#
# In the meantime, the simple work-around is to take care of the
# refresh manually.
Perform updates:
  pkg.uptodate:
    # Run 'apt-get update' if the index is at least 12 hours old.
    - cache_valid_time: 43200
    - refresh_on_watch: True
```

In this way, `apt-get update` will only run under two conditions - if the index is at least 12 hours old, or if we made changes to `sources.list` (or whatever else somebody feels like triggering such a change on). I feel this is a very useful use-case that deserves some consideration, as one cannot reliably use the `cache_valid_time` option in `pkg` state modules as things stand - assuming Salt is used to manage `sources.list` and related files.

### Versions Report
Observed on a masterless host running Ubuntu 14.04 trusty.
```
$ sudo salt-call --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-1-amd64
         system: Linux
        version: Ubuntu 14.04 trusty
$
```
