### ISSUE TITLE
2017.7.2 seems to have broken runner reactors. Expects keyword arguments

### ISSUE THREAD

**Issue by jonans** [saltstack/salt#44139]
### Description of Issue/Question

Previously working reactor + runner (2017.7.1) now fails on version 2017.7.2. 

- Using the old syntax fails unless you add some unneeded keyword arguments.
- Changing to unified syntax also fails. Was only able to get working by changing runner function to use keyword instead of positional arguments.

What is the expected behavior ? Do runners/reactor have an expected function signature ?

### Setup

**Runner function**
```python
def verify(host):
    # DO STUFF
    return
```
**Previously working Reactor**
```yaml
handle_event:
   runner.mon.verify:
       - arg:
           - {{ data['id'] }}
```
**Fails with**
```
[ERROR   ] Reactor 'do_event' failed to execute runner 'mon.verify'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 407, in run
    expected_extra_kws=REACTOR_INTERNAL_KEYWORDS
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1120, in format_call
    used_args_count
SaltInvocationError: verify takes at least 1 argument (0 given)
```
**Switching to new unified syntax**
```yaml
handle_event:
   runner.mon.verify:
       - args:
           - {{ data['id'] }}
```
**Fails with**
```
Exception occurred in runner mon.verify: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 382, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
TypeError: verify() got an unexpected keyword argument 'test-host'
```
**This works**
```yaml
handle_event:
   runner.mon.verify:
       - arg:
           - {{ data['id'] }}
       - kwarg:
           useless: arg          
```

### Steps to Reproduce Issue

Upgrade from 2017.7.1 to 2017.7.2 with above runner + reactor

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-93-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
