### ISSUE TITLE
salt.iptables rewriting custom chain after reboot.

### ISSUE THREAD

**Issue by Robert-Grundstrom** [saltstack/salt#44147]
### Description of Issue/Question
When using `salt.iptables` to write the rules it seems that something goes wrong after a reboot.

In this case the custom chain `SSHSCAN` gets rewritten after the reboot.
I've provided a `iptables-save -c` below to show that there are no changes to the rules after the reboot

Its a bit odd tho cause its only this chain that gets rewritten, could it be cause the `SSHSCAN` gets
set in a diffrent state?

I've tested to use `iptables.append` instead of `iptables.insert` and there is no diffrence in the problem.

The rest of the rules are set by another state that can be found here:
https://github.com/Robert-Grundstrom/salt-config/blob/master/salt-config/salt/services/firewall/init.sls

### Pillar
```
server:
  settings:
    network:
      ens3:
        set_type: single
        set_ipaddr: '172.18.0.50'
        set_netmask: '255.255.255.0'
        set_gateway: '172.18.0.254'

    set_dns:
      - set_search: blacknet.lan
      - set_server:
        - 172.18.0.254

    set_ntp:
      - ntp1.sth.netnod.se
      - ntp2.sth.netnod.se

    ssh_config:
      - source: '172.18.0.0/24'
      - interface: 'ens3'

    firewall:
      - enable: False
      - rules:
        - 'TCP,4505,172.18.0.0/24'
        - 'TCP,4506,172.18.0.0/24'

    set_snmp:
      - snmp_usr: rouser
      - snmp_sha: monkeylikebanana
      - snmp_aes: monkeyhasbanana
      - snmp_ip: 172.18.0.50

    set_default_packets:
      - vim
      - network-manager
      - sudo

monitor:
  servers:
    - '172.18.0.60'
```

### State
```
# SSHD configuration.

# Intalling and keeping service up to date.
install_sshd_pkgs:
  pkg.latest:
    - pkgs:
      - openssh-server
      - rsyslog

# Set up a iptables chain for the service.
set_sshd_fwchains:
  iptables.chain_present:
  - names:
    - 'SSHSCAN'
  - family: 'ipv4'

# Set up the iptable rules.
set_sshd_chainrule:
  iptables.append:
  - name: 'SSH Connections'
  - chain: 'INPUT'
  - jump: 'SSHSCAN'
  - i: '!lo'
  - dport: '22'
  - connstate: 'NEW'
  - match: 'state'
  - proto: 'tcp'
  - table: filter
  - save: True

set_sshd_fwrules:
  iptables.insert:
  - names:
    - 'SSHD Set':
      - position: '1'
      - match: 'recent --set --name SSH --rsource'
      - connstate: 'NEW'

    - 'SSHD Log':
      - position: '2'
      - match: 'recent --update --seconds 120 --hitcount 10 --name SSH --rsource'
      - jump: 'LOG'
      - log-prefix: '[SSH Brute-Force attempt:] '
      - log-level: '7'

    - 'SSHD Drop':
      - position: '3' 
      - jump: 'REJECT'
      - match: 'recent --update --seconds 120 --hitcount 10 --name SSH --rsource'
      - connstate: 'NEW'

    - 'SSHD Accept':
      - position: '4'
      - jump: 'ACCEPT'
      - source: {{salt['pillar.get']('server:settings:ssh_config:source')}}
 
  - chain: 'SSHSCAN'
  - proto: 'tcp'
  - table: filter
  - save: True

apply_sshd_config:
  file.managed:
    - names:
      - '/etc/ssh/sshd_config':
        - source: salt://{{slspath}}/files/sshd_config

      - '/etc/rsyslog.d/30-iptables.conf':
        - contents: ':msg,contains,"[SSH Brute-Force attempt:] " /var/log/iptables.log'

      - '/var/log/iptables.log':
        - create: True
        - mode: 640
        - user: syslog
        - group: adm
        - replace: False
    - mode: 644
    - user: root
    - group: root
    - template: jinja

# Make sure services are running.
sshd_services_running:
  service.running:
    - names: 
      - 'sshd'
      - 'rsyslog'
    - enable: True
    - watch:
      - file: apply_sshd_config
      - pkg: install_sshd_pkgs
```
### Before reboot
```
# Generated by iptables-save v1.6.0 on Wed Oct 18 08:19:14 2017
*filter
:INPUT ACCEPT [14:1398]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [613:83058]
:CUSTOM - [0:0]
:SSHSCAN - [0:0]
[656:165743] -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
[13:805] -A INPUT -i lo -m comment --comment "Accept lo traffic" -j ACCEPT
[17:1578] -A INPUT -m comment --comment "Jump to Salt Custom rules." -j CUSTOM
[3:180] -A INPUT ! -i lo -p tcp -m state --state NEW -m tcp --dport 22 -j SSHSCAN
[0:0] -A INPUT -s 172.18.0.60/32 -d 172.18.0.50/32 -p udp -m udp --dport 161 -j ACCEPT
[0:0] -A CUSTOM -s 172.18.0.0/24 -p tcp -m tcp --dport 4505
[0:0] -A CUSTOM -s 172.18.0.0/24 -p tcp -m tcp --dport 4506
[3:180] -A SSHSCAN -p tcp -m recent --set --name SSH --mask 255.255.255.255 --rsource -m state --state NEW
[0:0] -A SSHSCAN -p tcp -m recent --update --seconds 120 --hitcount 10 --name SSH --mask 255.255.255.255 --rsource -j LOG --log-prefix "[SSH Brute-Force attempt:] " --log-level 7
[0:0] -A SSHSCAN -p tcp -m recent --update --seconds 120 --hitcount 10 --name SSH --mask 255.255.255.255 --rsource -m state --state NEW -j REJECT --reject-with icmp-port-unreachable
[3:180] -A SSHSCAN -s 172.18.0.0/24 -p tcp -j ACCEPT
COMMIT
# Completed on Wed Oct 18 08:20:19 2017
```
### After reboot
```
# Generated by iptables-save v1.6.0 on Wed Oct 18 08:22:09 2017
*filter
:INPUT ACCEPT [14:1398]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [613:83058]
:CUSTOM - [0:0]
:SSHSCAN - [0:0]
[656:165743] -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
[13:805] -A INPUT -i lo -m comment --comment "Accept lo traffic" -j ACCEPT
[17:1578] -A INPUT -m comment --comment "Jump to Salt Custom rules." -j CUSTOM
[3:180] -A INPUT ! -i lo -p tcp -m state --state NEW -m tcp --dport 22 -j SSHSCAN
[0:0] -A INPUT -s 172.18.0.60/32 -d 172.18.0.50/32 -p udp -m udp --dport 161 -j ACCEPT
[0:0] -A CUSTOM -s 172.18.0.0/24 -p tcp -m tcp --dport 4505
[0:0] -A CUSTOM -s 172.18.0.0/24 -p tcp -m tcp --dport 4506
[3:180] -A SSHSCAN -p tcp -m recent --set --name SSH --mask 255.255.255.255 --rsource -m state --state NEW
[0:0] -A SSHSCAN -p tcp -m recent --update --seconds 120 --hitcount 10 --name SSH --mask 255.255.255.255 --rsource -j LOG --log-prefix "[SSH Brute-Force attempt:] " --log-level 7
[0:0] -A SSHSCAN -p tcp -m recent --update --seconds 120 --hitcount 10 --name SSH --mask 255.255.255.255 --rsource -m state --state NEW -j REJECT --reject-with icmp-port-unreachable
[3:180] -A SSHSCAN -s 172.18.0.0/24 -p tcp -j ACCEPT
COMMIT
# Completed on Wed Oct 18 08:22:09 2017
```
### After state is run
```
# Generated by iptables-save v1.6.0 on Wed Oct 18 08:55:38 2017
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [107:19401]
:CUSTOM - [0:0]
:SSHSCAN - [0:0]
[2162:479188] -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
[25:1525] -A INPUT -i lo -m comment --comment "Accept lo traffic" -j ACCEPT
[156:17424] -A INPUT -m comment --comment "Jump to Salt Custom rules." -j CUSTOM
[3:180] -A INPUT ! -i lo -p tcp -m state --state NEW -m tcp --dport 22 -j SSHSCAN
[0:0] -A INPUT -s 172.18.0.60/32 -d 172.18.0.50/32 -p udp -m udp --dport 161 -j ACCEPT
[0:0] -A CUSTOM -s 172.18.0.0/24 -p tcp -m tcp --dport 4505
[0:0] -A CUSTOM -s 172.18.0.0/24 -p tcp -m tcp --dport 4506
[0:0] -A SSHSCAN -p tcp -m recent --set --name SSH --mask 255.255.255.255 --rsource -m state --state NEW
[0:0] -A SSHSCAN -p tcp -m recent --update --seconds 120 --hitcount 10 --name SSH --mask 255.255.255.255 --rsource -j LOG --log-prefix "[SSH Brute-Force attempt:] " --log-level 7
[0:0] -A SSHSCAN -p tcp -m recent --update --seconds 120 --hitcount 10 --name SSH --mask 255.255.255.255 --rsource -m state --state NEW -j REJECT --reject-with icmp-port-unreachable
[3:180] -A SSHSCAN -p tcp -m recent --set --name SSH --mask 255.255.255.255 --rsource -m state --state NEW
[0:0] -A SSHSCAN -p tcp -m recent --update --seconds 120 --hitcount 10 --name SSH --mask 255.255.255.255 --rsource -j LOG --log-prefix "[SSH Brute-Force attempt:] " --log-level 7
[0:0] -A SSHSCAN -p tcp -m recent --update --seconds 120 --hitcount 10 --name SSH --mask 255.255.255.255 --rsource -m state --state NEW -j REJECT --reject-with icmp-port-unreachable
[3:180] -A SSHSCAN -s 172.18.0.0/24 -p tcp -j ACCEPT
COMMIT
# Completed on Wed Oct 18 08:55:38 2017
```
### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1
 
System Versions:
           dist: Ubuntu 17.04 zesty
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-37-generic
         system: Linux
        version: Ubuntu 17.04 zesty
```
