### ISSUE TITLE
2017.7.2 win_file.py: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by dafyddj** [saltstack/salt#44142]
### Description of Issue/Question

A simple file.copy state results in an exception, although the file is actually copied.
Looks to be related to checking permissions.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
my-test:              
  file.copy:          
    - name: C:\notepad.exe                   
    - source: C:\Windows\notepad.exe
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
```
PS C:\Users\vagrant> salt-call.bat state.apply file-test
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1843, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1795, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 5336, in copy
    __salt__['file.check_perms'](name, ret, user, group, mode)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1712, in check_perms
    if 'applies_to' in grant_perms[user]:
TypeError: string indices must be integers

local:
----------
          ID: my-test
    Function: file.copy
        Name: C:\notepad.exe
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1843, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 5336, in copy
                  __salt__['file.check_perms'](name, ret, user, group, mode)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1712, in check_perms
                  if 'applies_to' in grant_perms[user]:
              TypeError: string indices must be integers
     Started: 15:27:14.712000
    Duration: 406.0 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 406.000 ms
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 8.1
         system: Windows
        version: 8.1 6.3.9600  Multiprocessor Free
```

**Comment by dave92082** [comment]
Is there a timeline for this fix?

**Comment by ben-reilly** [comment]
I encountered this issue as well and was able to get around it by adding
```
  - preserve: True
```
to keep the existing file permissions. I'm guessing that when salt tries to pick the user/group info of my user, it's tripping on some Windows-y things.

**Comment by tobias-kuendig** [comment]
I'm experiencing the same problem. `Preserve: True` unfortunately doesn't change anything.


```yaml
copy_file_from_source_to_destination:
  file.copy:
    - name: C:/destination/file.txt
    - source: C:/source/file.txt
    - force: true
    - makedirs: true
    - preserve: true
```

```
> salt-call --versions-report
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.14393  Multiprocessor Free
```

**Comment by chokkoretto** [comment]
Any update?
Also got the same issue using the 2019.02 version on my minion

copy_dir:
  file.copy:
    - name: 'C:\dir2'
    - source: 'C:\dir1'
    - force: True
    - makedirs: True

Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by twangboy** [comment]
I just tested this on the head of master (3007):
salt://file/copy.sls
```
test_file_copy:
  file.copy:
    - name: C:\notepad.exe
    - source: C:\windows\notepad.exe
```

The state applied successfully:
```
PS C:\src\salt> salt-call.exe --local state.apply file.copy
local:
----------
          ID: test_file_copy
    Function: file.copy
        Name: C:\notepad.exe
      Result: True
     Comment: Copied "C:\windows\notepad.exe" to "C:\notepad.exe"
     Started: 14:52:43.607217
    Duration: 195.285 ms
     Changes:
              ----------
              C:\notepad.exe:
                  C:\windows\notepad.exe
              owner:
                  leesh

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 195.285 ms
```

If you believe this is still an issue, please open a new issue with detailed steps on how to reproduce.
