### ISSUE TITLE
incorrect network interfaces settings with network.managed under debian jessie

### ISSUE THREAD

**Issue by vtolstov** [saltstack/salt#44140]
rendered sls file looks like:
```
                                         etc_network_interfaces_d:
                                           file.absent:
                                             - name: /etc/network/interfaces.d

                                         eth0:
                                           network.managed:
                                             - enabled: True
                                             - type: slave
                                             - master: bond0
                                             - pre_up_cmds:
                                               - ip a flush dev eth0
                                               - killall -9 dhclient || true
                                             - mtu: 8500

                                         eth1:
                                           network.managed:
                                             - enabled: True
                                             - type: slave
                                             - master: bond0
                                             - pre_up_cmds:
                                               - ip a flush dev eth1
                                               - killall -9 dhclient || true
                                             - mtu: 8500
                                         bond0:
                                           network.managed:
                                             - enabled: True
                                             - enable_ipv6: True
                                             - type: bond
                                             - ipaddr: 'fd3d:99a2:96e3:a1a4:0ec4:7aff:fe8a:6acc'
                                             - netmask: 64
                                             - proto: static
                                             - mode: balance-alb
                                             - miimon: 100
                                             - arp_interval: 250
                                             - downdelay: 200
                                             - updelay: 100
                                             - slaves: eth0 eth1
                                             - mtu: 8500
                                             - up_cmds:
                                               - ip link set up dev eth0
                                               - ip link set up dev eth1
                                               - sysctl -w net.ipv6.conf.bond0.accept_ra=0
                                               - sysctl -w net.ipv6.conf.bond0.accept_dad=0
                                               - 'ip a add 2a04:ac00:4:10:0ec4:7aff:fe81:1cda'
                                             - down_cmds:
                                               - 'ip a del fd3d:99a2:96e3:a1a4:0ec4:7aff:fe81:1cda'
                                               - ip link set down dev eth0
                                               - ip link set down dev eth1
                                             - require:
                                               - network: eth0
                                               - network: eth1
                                         vlan1001:
                                           network.managed:
                                             - enabled: True
                                             - type: vlan
                                             - netmask: 24
                                             - ipaddr: 192.168.241.134
                                             - proto: static
                                             - vlan-raw-device: bond0
                                             - vlan: True
                                             - mtu: 1500
                                             - up_cmds:
                                               - sysctl -w net.ipv6.conf.all.forwarding=1
                                               - sysctl -w net.ipv4.ip_forward=1
                                             - require:
                                               - network: bond0

                                         vlan4094:
                                           network.managed:
                                             - enabled: True
                                             - type: vlan
                                             - netmask: 24
                                             - ipaddr: 192.168.237.134
                                             - proto: static
                                             - vlan-raw-device: bond0
                                             - vlan: True
                                             - mtu: 8500
                                             - require:
                                               - network: bond0
```

file looks like:
```
auto eth0
iface eth0 inet manual
    mtu 8500
    bond-master bond0
    pre-up ip a flush dev eth0
    pre-up killall -9 dhclient || true
auto eth1
iface eth1 inet manual
    mtu 8500
    bond-master bond0
    pre-up ip a flush dev eth1
    pre-up killall -9 dhclient || true
auto bond0
iface bond0 inet6 static
    address fd3d:99a2:96e3:a1a4:0ec4:7aff:fe8a:6acc
    netmask 64
    mtu 8500
auto vlan1001
iface vlan1001 inet static
    vlan-raw-device bond0
    address 192.168.241.134
    netmask 24
    mtu 1500
    up sysctl -w net.ipv6.conf.all.forwarding=1
    up sysctl -w net.ipv4.ip_forward=1
auto vlan4094
iface vlan4094 inet static
    vlan-raw-device bond0
    address 192.168.237.134
    netmask 24
    mtu 8500
```
