### ISSUE TITLE
feature request: file.recurse could copy file permissions if not explicitly set with file_mode

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#4423]
After a rather unsuccessfull poll on the mailinglist, I'll leave this here:

If I have

```
/usr/share/munin/plugins:
  file.recurse:
    - source: salt://all-munin-node/plugins
    - clean: false  # just in case, anders zijn alle plugins weg
    - require:
      - pkg: munin-node-pkgs
```

and the plugins/ directory looks like this:

```
root@salt-master:/home/salt/conf/all-munin-node/plugins# ls -aslF
total 16
0 drwxr-xr-x 2 root root   61 Apr  6 10:49 ./
0 drwxr-xr-x 4 root root   92 Apr  6 10:52 ../
4 -rwxr-xr-x 1 root root 2966 Apr  6 10:48 kvm_cpu*
4 -rwxr-xr-x 1 root root 3307 Apr  6 10:48 kvm_io*
4 -rwxr-xr-x 1 root root 3201 Apr  6 10:48 kvm_mem*
4 -rwxr-xr-x 1 root root 4004 Apr  6 10:49 kvm_net*
```

wouldn't it be reasonable to expect that the files are created 755 on
the minion?

Because they aren't:

```
root@0010:/usr/share/munin/plugins# ls -aslF | grep kvm
 4 -rw-r--r-- 1 root  root   2966 Apr  6 10:52 kvm_cpu
 4 -rw-r--r-- 1 root  root   3307 Apr  6 10:52 kvm_io
 4 -rw-r--r-- 1 root  root   3201 Apr  6 10:52 kvm_mem
 4 -rw-r--r-- 1 root  root   4004 Apr  6 10:52 kvm_net
```

I know I can set `file_mode`, but that sets the mode of _all_ files to
something, while it could be beneficial to have some files 644, other
400 and some 755.

Perhaps a new setting is in order: "copy_permissions"

M.
