### ISSUE TITLE
mysql_grants with any host causes error

### ISSUE THREAD

**Issue by dwickwire** [saltstack/salt#44240]
### Description of Issue/Question

Any time I try to use any host `'%'` or even if I try and get clever `"'%'"` when the state runs it always renders an error of `Can't find any matching row in the user table`.

Yet, if I run the SQL directly on my server, it runs fine.  This is specific to the `%` anyhost.  If I use localhost, the state passes successfully.

Perhaps I'm doing something wrong, but this feels like a salt bug.  Sorry, if I'm missing something obvious!

### Setup
```yaml
grant-myuser-access-to-mydb-table:
  mysql_grants.present:
    - user: {{ secrets.mydb.myuser.user }}
    - database: 'mydb.mytable'
    - host: '%'
    - grant: SELECT
    - connection_pass: {{ root_mysql_password }}
    - require:
      - mysql_database: mydb
      - mysql_user: myuser
```

### Steps to Reproduce Issue
- running the state produces this error:

```error
----------
          ID: grant-user-access-to-mydb-on-table
    Function: mysql_grants.present
      Result: False
     Comment: Failed to execute: "GRANT SELECT ON mydb.mytable TO myuser@%" (MySQL Error 1133: Can't find any matching row in the user table)
     Started: 03:20:46.483794
    Duration: 4.541 ms
     Changes:
```

### Versions Report
- 2016.11.5
