### ISSUE TITLE
Scheduler adds job, but job never executes!

### ISSUE THREAD

**Issue by SaltMPA** [saltstack/salt#44241]
### Description of Issue/Question
When I use 
salt -G 'os:windows' schedule.add myjob function="cmd.run 'get-date >> c:\tmp\nowdate.txt' shell=powershell" seconds=5

to test the scheduler, the job gets successfully added to the schedule, but it never runs. Am I missing something?

Here's how my schedule looks after adding the job:
```
[root@cloud-salt02 mpa]# salt -G 'os:windows' schedule.list
test-salt01.cloudstack.dk:
    schedule:
      keepalivejob:
        enabled: true
        function: test.ping
        jid_include: true
        maxrunning: 1
        name: keepalivejob
        seconds: 60
      myjob:
        enabled: true
        function: cmd.run 'get-date >> c:\tmp\nowdate.txt' shell=powershell
        jid_include: true
        maxrunning: 1
        name: myjob
        seconds: 5
```

I am trying to schedule calling highstate in a scheduled way. So far I have only tested states by manually executing them like:

[root@cloud-salt02 mpa]# salt -G 'os:windows' state.sls mpa.services

I want to do that using the builtin scheduler in SaltStack, but I can't get it to work. Should I use cron instead?

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

[root@cloud-salt02 mpa]#
[root@cloud-salt02 salt-winrepo-ng]# salt-run manage.versions
Master:
    2017.7.1
Up to date:
    ----------
    test-mpa01.cloudstack.dk:
        2017.7.1
    test-salt01.cloudstack.dk:
        2017.7.1

**Comment by gtmanfred** [comment]
first, since you are using redirects, you will probably want to use `cmd.shell` instead of `cmd.run`

Second, you need to pass get-data and shell=powershell to the correct variables, otherwise they get tacked onto the function.

`salt -G 'os:windows' schedule.add myjob function=cmd.shell job_args='["get-date >> c:\tmp\nowdate.txt"]' job_kwargs='{"shell": "powershell"}' -l debug`

This will result in a scheduled job that looks like this.

```
[root@salt ~]# salt-call schedule.list
local:
    schedule:
      myjob:
        args:
        - "get-date >> c:\tmp\nowdate.txt"
        enabled: true
        function: cmd.shell
        jid_include: true
        kwargs:
          shell: powershell
        maxrunning: 1
        name: myjob
```

And will be able to run.
