### ISSUE TITLE
Output of file.serialize to ignore null

### ISSUE THREAD

**Issue by hibbert** [saltstack/salt#44261]
### Description of Issue/Question

Would like to be able to have the following in yaml in pillar or similar

```
init_config:
instances:
  - server: servername
     user: root
     pass: pass
     port: 3306
```

And get this to show, how it is above. Instead with my state:-

```
/tmp/datadog.yaml:
  file.serialize:
    - dataset:
        init_config:
        instances:
          - server: servername
            user: root
            pass: pass
            port: 3306
    - formatter: yaml
```

I get the following:-

```
init_config: null
instances:
- pass: pass
   port: 3306
   server: servername
   user: root
```

I don't want the null bit. I think ansible has something similar called to_nice_yaml which might not put in the null (untested)

### Setup
See above

### Steps to Reproduce Issue
See above

### Versions Report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
