### ISSUE TITLE
Salt-Cloud EC2 fails when profile contains subnetname

### ISSUE THREAD

**Issue by jsandas** [saltstack/salt#44289]
I am setting up a cloud profile for using EC2.   If I specify the subnetid, it works as expected.  However, if I trying using the subnetname it returns a key error.

Looking at the trace logs, it looks like it is always querying the us-east-1 region for the list of subnets available rather than the us-west-2 region which I am specifying.

### Setup
Profile settings (sanitized):
```
aws-us-west-2-profile:
  provider: aws
  image: ami-e535c59d
  size: t2.medium
  location: us-west-2
  availability_zone: us-west-2a
  del_all_vols_on_destroy: True
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 30
      Ebs.VolumeType: gp2
  minion:
    master: salt.***********
  subnetname: ctlog_uswest2_app_net_a
  #subnetid: subnet-*****
  securitygroupid:
    - sg-******
```

### Steps to Reproduce Issue
Running this:
```
sudo salt-cloud -p aws-us-west-2-profile testing
```
Returns this:
```
[ERROR   ] Failed to create VM testing. Configuration value 'key' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1278, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2617, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1855, in request_instance
    subnetid_ = get_subnetid(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1234, in get_subnetid
    return _get_subnetname_id(subnetname)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1211, in _get_subnetname_id
    if tag['key'] == 'Name' and tag['value'] == subnetname:
KeyError: 'key'
```
Running the same command with "--log-level=trace" returns this information (sanitized) which is what led me to my earlier mentions theory.
```
[INFO    ] Creating Cloud VM testing in us-west-2
[DEBUG   ] Using AWS endpoint: ec2.us-west-2.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-2.amazonaws.com/?Action=DescribeAvailabilityZones&Filter.0.Name=region-name&Filter.0.Value.0=us-west-2&Version=2014-10-01
[TRACE   ] AWS Request Parameters: {}
[DEBUG   ] AWS Response Status Code: 200
[TRACE   ] AWS Response Text: <?xml version="1.0" encoding="UTF-8"?>
<DescribeAvailabilityZonesResponse xmlns="http://ec2.amazonaws.com/doc/2014-10-01/">
    <requestId>3bc7e929-8cb6-4549-912a-ba5fec443c19</requestId>
    <availabilityZoneInfo>
        <item>
            <zoneName>us-west-2a</zoneName>
            <zoneState>available</zoneState>
            <regionName>us-west-2</regionName>
            <messageSet/>
        </item>
        <item>
            <zoneName>us-west-2b</zoneName>
            <zoneState>available</zoneState>
            <regionName>us-west-2</regionName>
            <messageSet/>
        </item>
        <item>
            <zoneName>us-west-2c</zoneName>
            <zoneState>available</zoneState>
            <regionName>us-west-2</regionName>
            <messageSet/>
        </item>
    </availabilityZoneInfo>
</DescribeAvailabilityZonesResponse>
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeSubnets&Version=2014-10-01
[TRACE   ] AWS Request Parameters: {}
[DEBUG   ] AWS Response Status Code: 200
[TRACE   ] AWS Response Text: <?xml version="1.0" encoding="UTF-8"?>
<DescribeSubnetsResponse xmlns="http://ec2.amazonaws.com/doc/2014-10-01/">
    <requestId>24a08166-0e85-4822-86ea-5bbfb7bc39cf</requestId>
    <subnetSet>
        <item>
            <subnetId>subnet-********</subnetId>
            <state>available</state>
            <vpcId>vpc-*******</vpcId>
            <cidrBlock>172.31.16.0/20</cidrBlock>
            <availableIpAddressCount>4091</availableIpAddressCount>
            <availabilityZone>us-east-1b</availabilityZone>
            <defaultForAz>true</defaultForAz>
            <mapPublicIpOnLaunch>true</mapPublicIpOnLaunch>
        </item>
        <item>
            <subnetId>subnet-*******</subnetId>
            <state>available</state>
            <vpcId>vpc-*******</vpcId>
            <cidrBlock>172.31.0.0/20</cidrBlock>
            <availableIpAddressCount>4091</availableIpAddressCount>
            <availabilityZone>us-east-1d</availabilityZone>
            <defaultForAz>true</defaultForAz>
            <mapPublicIpOnLaunch>true</mapPublicIpOnLaunch>
        </item>
        <item>
            <subnetId>subnet-*******</subnetId>
            <state>available</state>
            <vpcId>vpc-*******</vpcId>
            <cidrBlock>172.31.48.0/20</cidrBlock>
            <availableIpAddressCount>4091</availableIpAddressCount>
            <availabilityZone>us-east-1e</availabilityZone>
            <defaultForAz>true</defaultForAz>
            <mapPublicIpOnLaunch>true</mapPublicIpOnLaunch>
        </item>
        <item>
            <subnetId>subnet-*******</subnetId>
            <state>available</state>
            <vpcId>vpc-*******</vpcId>
            <cidrBlock>172.31.80.0/20</cidrBlock>
            <availableIpAddressCount>4091</availableIpAddressCount>
            <availabilityZone>us-east-1f</availabilityZone>
            <defaultForAz>true</defaultForAz>
            <mapPublicIpOnLaunch>true</mapPublicIpOnLaunch>
        </item>
        <item>
            <subnetId>subnet-******</subnetId>
            <state>available</state>
            <vpcId>vpc-*******</vpcId>
            <cidrBlock>172.31.32.0/20</cidrBlock>
            <availableIpAddressCount>4091</availableIpAddressCount>
            <availabilityZone>us-east-1c</availabilityZone>
            <defaultForAz>true</defaultForAz>
            <mapPublicIpOnLaunch>true</mapPublicIpOnLaunch>
        </item>
        <item>
            <subnetId>subnet-*******</subnetId>
            <state>available</state>
            <vpcId>vpc-*******</vpcId>
            <cidrBlock>172.31.64.0/20</cidrBlock>
            <availableIpAddressCount>4091</availableIpAddressCount>
            <availabilityZone>us-east-1a</availabilityZone>
            <defaultForAz>true</defaultForAz>
            <mapPublicIpOnLaunch>true</mapPublicIpOnLaunch>
        </item>
    </subnetSet>
</DescribeSubnetsResponse>
```

### Versions Report
```
Salt Version:
            Salt: 2017.7.2

Dependency Versions:
 Apache Libcloud: 2.0.0rc2
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: Not Installed
       docker-py: 2.5.1
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.7.2
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.8
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.3.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4

System Versions:
            dist: centos 7.4.1708 Core
          locale: UTF-8
         machine: x86_64
         release: 3.10.0-693.2.2.el7.x86_64
          system: Linux
         version: CentOS Linux 7.4.1708 Core
```
```
salt-cloud 2017.7.2 (Nitrogen)
```

**Comment by jsandas** [comment]
It looks like other things are doing the same some.  Upon completing the creation of the VM in EC2, I am given this error message:
```
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': "The instance ID 'i-0a3cf8bbd12951962' does not exist", 'Code': 'InvalidInstanceID.NotFound'}}, 'RequestID': '55a5f5f7-b4ac-445d-b27a-472bf5f01981'}
```
Looking at the debug logs, it tries to run the describeinstances function, but it is looking in the wrong region so therefore it gets an error back.
```
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&InstanceId.1=i-0a3cf8bbd12951962&Version=2014-10-01
[DEBUG   ] AWS Response Status Code: 400
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': "The instance ID 'i-************' does not exist", 'Code': 'InvalidInstanceID.NotFound'}}, 'RequestID': '55a5f5f7-b4ac-445d-b27a-472bf5f01981'}
```

**Comment by gtmanfred** [comment]
I am unable to replicate this.

```
[root@ip-10-0-0-24 ~]# tail -c +0 /etc/salt/cloud*/*.conf
==> /etc/salt/cloud.profiles.d/centos.conf <==
centos:
  provider: aws
  image: ami-db48ada1
  securitygroupname:
    - gtmanfred
  subnetname: pubgt
  size: t2.micro
  ssh_username: centos

==> /etc/salt/cloud.providers.d/ec2.conf <==
aws:
  minion:
    master: 10.0.0.24
  ssh_interface: private_ips
  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'
  private_key: /root/.ssh/id_rsa
  keyname: gtmanfred
  location: us-east-1
  driver: ec2
```

It builds correctly for me.

Can you put some logging around this line and see if you can find something that may be missing?
```
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1211, in _get_subnetname_id
    if tag['key'] == 'Name' and tag['value'] == subnetname:
KeyError: 'key'
```

Also, if you move the location to the `provider` instead of in the profile, does this go away?  Some of these commands only use the provider settings, and not the stuff from the profile, so it may be what is happening is that those commands are using the default us-east-1, instead of your us-west-2

Thanks,
Daniel

**Comment by jsandas** [comment]
I figured out what the issue was.  I did not specify the location in the provider configuration.  The documentation wasn't quite clear that unless you want to use the default region (ie us-east-1) you have to specify the location in the provider configuration and not in the profile configuration.

**Comment by gtmanfred** [comment]
Would you mind submitting a PR to that doc to help us make it more clear?

Thanks,
Daniel

**Comment by nkv16786** [comment]
Jsandas, Does that mean we need different provider for each location??

**Comment by lloesche** [comment]
I just ran into the very same issue. salt-cloud-2017.7.3-1.fc26.noarch on FC26.

```
[ERROR   ] Failed to create VM a6.c1.dcos.mesosphere.com. Configuration value 'key' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1278, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2617, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1855, in request_instance
    subnetid_ = get_subnetid(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1234, in get_subnetid
    return _get_subnetname_id(subnetname)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1211, in _get_subnetname_id
    if tag['key'] == 'Name' and tag['value'] == subnetname:
KeyError: 'key'
```

I do have `location: us-west-2` in my provider file.

```
dcos-ec2:
  driver: ec2
  id: 'xxxx'
  key: 'xxxx'
  private_key: /etc/salt/ssh/dcos.pem
  keyname: dcos
  ssh_interface: public_ips
  location: us-west-2
  ssh_username: centos
```

This works (explicitly configuring subnet and sg IDs):
```
prod1-master:
  provider: dcos-ec2
  image: ami-0ebdd976
  size: m5.xlarge
  sync_after_install: grains
  del_root_vol_on_destroy: True
  del_all_vols_on_destroy: True
  rename_on_destroy: True
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 40
      Ebs.VolumeType: gp2
  volumes:
    - { size: 20, device: /dev/xvdf, type: gp2 }
    - { size: 20, device: /dev/xvdh, type: gp2 }
  script_args: stable 2017.7.3
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: True
      SubnetId: subnet-1574d35e
      SecurityGroupId:
        - sg-5c204022
  iam_profile: 'prod1-master-role'
```

This doesn't work (names on the top level):
```
prod1-master:
  provider: dcos-ec2
  image: ami-0ebdd976
  size: m5.xlarge
  sync_after_install: grains
  del_root_vol_on_destroy: True
  del_all_vols_on_destroy: True
  rename_on_destroy: True
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 40
      Ebs.VolumeType: gp2
  volumes:
    - { size: 20, device: /dev/xvdf, type: gp2 }
    - { size: 20, device: /dev/xvdh, type: gp2 }
  script_args: stable 2017.7.3
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: True
  iam_profile: 'prod1-master-role'
  subnetname: sn-prod1-a
  securitygroupname:
    - prod1-master
```
and neither does this (names on the network_interfaces device level):
```
prod1-master:
  provider: dcos-ec2
  image: ami-0ebdd976
  size: m5.xlarge
  sync_after_install: grains
  del_root_vol_on_destroy: True
  del_all_vols_on_destroy: True
  rename_on_destroy: True
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 40
      Ebs.VolumeType: gp2
  volumes:
    - { size: 20, device: /dev/xvdf, type: gp2 }
    - { size: 20, device: /dev/xvdh, type: gp2 }
  script_args: stable 2017.7.3
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      AssociatePublicIpAddress: True
      subnetname: sn-prod1-a
      securitygroupname:
        - prod1-master
  iam_profile: 'prod1-master-role'
```
