### ISSUE TITLE
salt-ssh: cli options should take priority over options set in Saltfile

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#44310]
### Description of Issue/Question
Any option set in Saltfile cannot be overriden on the command line.

### Setup
./Saltfile
```yaml
salt-ssh:
  roster_file: ./roster
```
./roster
```yaml
myhost:
  host: 127.0.0.1
  user: vagrant
  passwd: vagrant
```
### Steps to Reproduce Issue
```bash
root@master:/vagrant# salt-ssh -i '*' test.ping
myhost:
    True
root@master:/vagrant# salt-ssh -i --roster-file=fdfdgdfsg '*' test.ping
myhost:
    True
root@master:/vagrant# rm Saltfile
root@master:/vagrant# salt-ssh -i --roster-file=fdfdgdfsg '*' test.ping
[ERROR   ] No matching targets found in roster.
```
Notice how specifying the a different roster file has no effect. 

### Versions Report
```yaml
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core

```
