### ISSUE TITLE
[2017.7] Prereq and onchanges on same target causes error

### ISSUE THREAD

**Issue by hcsaustrup** [saltstack/salt#44333]
### Description of Issue/Question

I'm trying to install an executable on a Windows minion, and I want to handle some stuff before and after writing the binary. For this, I use *prereq* and *onchanges*, but I get this error if the file doesn't already exist:

```
          ID: components.common.metrics.telegraf.windows.binary
    Function: file.managed
        Name: D:/APP/Infrastructure/Telegraf/telegraf.exe
      Result: False
     Comment: Unable to manage file: Path not found: D:/APP/Infrastructure/Telegraf/telegraf.exe
```

If I comment out either *prereq* or *onchanges*, **the binary file is written without issues**.

The target path already exists, and permissions are fine.

The problem seems to be the simultaneous existence of both *prereq* and *onchanges*.

### Configuration

```
{{ slsdotpath }}.binary:
  file.managed:
    - name: '{{ _binary }}'
    - source: salt://{{ tpldir }}/files/{{ _binarySource }}

{{ slsdotpath }}.pre_binary:
  cmd.run:
    - name: echo pre_binary
    - prereq:
      - file: {{ slsdotpath }}.binary

{{ slsdotpath }}.post_binary:
  cmd.run:
    - name: echo post_binary
    - onchanges:
      - file: {{ slsdotpath }}.binary
```

### Versions Report

Windows minion:
```
[root@***]# salt '***' grains.get saltversion
***:
    2017.7.1
```

Master:
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo
```
