### ISSUE TITLE
"file.accumulated" does not support state module omission

### ISSUE THREAD

**Issue by curiositycasualty** [saltstack/salt#44354]
### Description of Issue/Question

`file.accumulated` doesn't work unless you specifically use the old-style, explicit, state module name within its `require_in` / `watch_in` arg. Using just the state name per https://docs.saltstack.com/en/latest/ref/states/requisites.html#omitting-state-module-in-requisites results in:
```
Comment: Orphaned accumulator handler-accumulator in <state>
```

### Versions Report
This is as of `2016.11.7`. Sorry, I'm unable to test any different versions at the moment.

**Comment by Ch3LL** [comment]
would you mind sharing your state when running into this issue? Also, was this working previously?

**Comment by fpicot** [comment]
I've just ran in the same issue : 

With the following SLS, I get the error 'Orphaned accumulator':
```
my_accumulator:
  file.accumulated:
     - name: my_accumulator
     - filename: /tmp/test_file
     - text: test
     - require_in:
        - my_file

my_file:
  file.managed:
    - name: /tmp/test_file
    - source: salt://test_file
```

Replacing the requisite by 'file: my_file' fixes the issue. 

Both master and minion are running salt 2019.2.2.
