### ISSUE TITLE
[salt-ssh] will fail when targeting Ubuntu<15 from CentOS

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#44387]
### Description of Issue/Question
The thin shipped to the target will contain the `python-tornado=4.2.1` module, however the source code differs between Ubuntu and CentOS. This results in `salt-call` from the thin failing completely on the target machine.

```python
root@ubuntu:/var/tmp/.vagrant_5c782e_salt# python salt-call
Traceback (most recent call last):
  File "salt-call", line 15, in <module>
    salt_call()
  File "py2/salt/scripts.py", line 374, in salt_call
    import salt.cli.call
  File "py2/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "py2/salt/cli/caller.py", line 18, in <module>
    import salt.loader
  File "py2/salt/loader.py", line 29, in <module>
    import salt.utils.event
  File "py2/salt/utils/event.py", line 68, in <module>
    import tornado.iostream
  File "py2/tornado/iostream.py", line 39, in <module>
    from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
  File "py2/tornado/netutil.py", line 38, in <module>
    import certifi
ImportError: No module named certifi

```
I was confused to why I didn't catch that earlier on since I tested it, but was using Ubuntu. Eventually, I compared the source code for `python-tornado` between the RPM and DEB packages here is the diff:
```diff
# diff tornado_netutil_ubuntu16.py tornado_netutil_centos7.py
1d0
< #!/usr/bin/env python
38a38,46
>     import certifi
> except ImportError:
>     # certifi is optional as long as we have ssl.create_default_context.
>     if ssl is None or hasattr(ssl, 'create_default_context'):
>         certifi = None
>     else:
>         raise
>
> try:
66c74
<         _client_ssl_defaults.load_verify_locations('/etc/ssl/certs/ca-certificates.crt')
---
>         _client_ssl_defaults.load_verify_locations(certifi.where())
77c85
<                                 ca_certs='/etc/ssl/certs/ca-certificates.crt')
---
>                                 ca_certs=certifi.where())
158,162c166
<             try:
<                 sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
<             except socket.error as e:
<                 if e.args[0] != errno.ENOPROTOOPT:
<                     raise
---
>             sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
```

`ssl.create_default_context` is not available until `python 2.7.9`, which means it doesn't exist until Ubuntu15. So the above code will raise on anything below that.

### Setup
Centos7 latest salt-ssh targeting `Ubuntu <= v14`

### Workaround

Target Ubuntu, from Ubuntu.

### Versions Report

```yaml
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment]
i'm having a hard time replicating this when targeting an ubuntu14 machine using salt-ssh version 2017.7.2 .

When checking the netutil.py on in the tmp directory it does have the try/except catch for the certifi import. Any other ideas on how your environment might be unique to help replicate this?

**Comment by rossengeorgiev** [comment]
It is CentOS targeting Ubuntu14. Yes, import is in a `try` block, but the condition in the `except` block will evaluate to false - ssl exists, but no create_default_context - reraising of the import exception. 

```bash
[root@centos7-2 ~]$ cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@centos7-2 ~]$ salt-ssh --version
salt-ssh 2017.7.2 (Nitrogen)
[root@centos7-2 ~]$ salt-ssh --user=vagrant --passwd=vagrant -i 'ubuntu14' test.ping
ubuntu14:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.vagrant_017c38_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/scripts.py", line 386, in salt_call
            import salt.cli.call
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/utils/parsers.py", line 28, in <module>
            import salt.config as config
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/config/__init__.py", line 100, in <module>
            _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/config/__init__.py", line 90, in _gather_buffer_space
            import salt.grains.core
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/grains/core.py", line 47, in <module>
            import salt.utils.dns
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/utils/dns.py", line 28, in <module>
            import salt.modules.cmdmod
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/modules/cmdmod.py", line 34, in <module>
            import salt.utils.templates
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/utils/templates.py", line 31, in <module>
            import salt.utils.http
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/utils/http.py", line 41, in <module>
            import salt.loader
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/loader.py", line 26, in <module>
            import salt.utils.event
          File "/var/tmp/.vagrant_017c38_salt/py2/salt/utils/event.py", line 70, in <module>
            import tornado.iostream
          File "/var/tmp/.vagrant_017c38_salt/py2/tornado/iostream.py", line 39, in <module>
            from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
          File "/var/tmp/.vagrant_017c38_salt/py2/tornado/netutil.py", line 38, in <module>
            import certifi
        ImportError: No module named certifi
    stdout:

**Comment by Ch3LL** [comment]
Cool I was finally able to replicate it by useing a completely clean cent7 box targeting ubuntu14. I verified this issue occurs in previous salt versions.

As a workaround you can install certifi

ping @saltstack/team-ssh any ideas on the solution here? should we be requiring certifi as a package dependency?  Seems its an upstream issue ultimately so not sure how to best handle this one?

**Comment by edgan** [comment]
I am seeing this problem with Fedora 28 and python 2.7.15 locally, and Ubuntu 14.04 remotely with python 2.7.6. Both have python-certifi installed. I just started seeing this have upgrading to 2018.3.1 from 2018.3.0.

```
    ----------
    _error:
        Failed to return clean data
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.ngrennan_e1f3ee_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.ngrennan_e1f3ee_salt/py2/salt/scripts.py", line 395, in salt_call
            import salt.cli.call
          File "/var/tmp/.ngrennan_e1f3ee_salt/py2/salt/cli/call.py", line 8, in <module>
            import salt.cli.caller
          File "/var/tmp/.ngrennan_e1f3ee_salt/py2/salt/cli/caller.py", line 18, in <module>
            import salt.loader
          File "/var/tmp/.ngrennan_e1f3ee_salt/py2/salt/loader.py", line 28, in <module>
            import salt.utils.event
          File "/var/tmp/.ngrennan_e1f3ee_salt/py2/salt/utils/event.py", line 70, in <module>
            import tornado.iostream
          File "/var/tmp/.ngrennan_e1f3ee_salt/py2/tornado/iostream.py", line 40, in <module>
            from tornado.netutil import ssl_wrap_socket, _client_ssl_defaults, _server_ssl_defaults
          File "/var/tmp/.ngrennan_e1f3ee_salt/py2/tornado/netutil.py", line 44, in <module>
            _client_ssl_defaults = ssl.create_default_context(
        AttributeError: 'module' object has no attribute 'create_default_context'
    stdout:
```

**Comment by edgan** [comment]
Downgrading from python2-tornado-5.0.2-2.fc28.x86_64 to python-tornado-4.2.1-4.fc28.x86_64(built from the fc24 src.rpm) fixes it.

**Comment by Ch3LL** [comment]
this looks like a seperate traceback can you open a new issue @edgan 

ping @rossengeorgiev you seeing this on 2018.3 still?

**Comment by rossengeorgiev** [comment]
@Ch3LL yes, still seeing this

```yaml
[root@centos7-5 ~]# salt-ssh --version
salt-ssh 2018.3.2 (Oxygen)
[root@centos7-5 ~]# salt-ssh -i --user=vagrant --passwd=vagrant --sudo --roster-file=a 'ubuntu14' -r 'cat /etc/lsb-release'
ubuntu14:
    ----------
    retcode:
        0
    stderr:
    stdout:
        vagrant@192.168.22.131's password:
        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=14.04
        DISTRIB_CODENAME=trusty
        DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
[root@centos7-5 ~]# salt-ssh -i --user=vagrant --passwd=vagrant --sudo --roster-file=a 'ubuntu14' test.ping
ubuntu14:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.vagrant_c36ad5_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.vagrant_c36ad5_salt/py2/salt/scripts.py", line 395, in salt_call
            import salt.cli.call
          File "/var/tmp/.vagrant_c36ad5_salt/py2/salt/cli/call.py", line 8, in <module>
            import salt.cli.caller
          File "/var/tmp/.vagrant_c36ad5_salt/py2/salt/cli/caller.py", line 18, in <module>
            import salt.loader
          File "/var/tmp/.vagrant_c36ad5_salt/py2/salt/loader.py", line 28, in <module>
            import salt.utils.event
          File "/var/tmp/.vagrant_c36ad5_salt/py2/salt/utils/event.py", line 70, in <module>
            import tornado.iostream
          File "/var/tmp/.vagrant_c36ad5_salt/py2/tornado/iostream.py", line 39, in <module>
            from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
          File "/var/tmp/.vagrant_c36ad5_salt/py2/tornado/netutil.py", line 38, in <module>
            import certifi
        ImportError: No module named certifi
    stdout:
```

**Comment by Ch3LL** [comment]
and just to clarify does installing certifi resolve the issue? Or is it directly related to your explanation in the first post:

>ssl.create_default_context is not available until python 2.7.9, which means it doesn't exist until Ubuntu15. So the above code will raise on anything below that.

**Comment by rossengeorgiev** [comment]
Hi @Ch3LL, yes installing certifi via pip makes the issue go away. 

It is wierd that tornado for ubuntu uses certifi, instead of just hardcoding the location like centos does.

**Comment by Ch3LL** [comment]
installing certifi on the minion or the master?

**Comment by rossengeorgiev** [comment]
On the minion

**Comment by Ch3LL** [comment]
k thanks for clarifying

**Comment by maltris** [comment]
> > ssl.create_default_context is not available until python 2.7.9, which means it doesn't exist until Ubuntu15. So the above code will raise on anything below that.

Are there any plans to fix this for Ubuntu 14.04 LTS?

**Comment by Ch3LL** [comment]
ping @thatch45 any ideas how we can handle this in salt-ssh?

**Comment by thatch45** [comment]
Can we add certifi to the thin if it is present? Then this could be solved by installing certifi

**Comment by Ch3LL** [comment]
looks like we already are here: https://github.com/saltstack/salt/blob/v2018.3.3/salt/utils/thin.py#L119

can anyone confirm if they have certifi installed on the salt-ssh master if it works for them?

**Comment by rossengeorgiev** [comment]
Hi @Ch3LL, this issue still exists on v2019. I can confirm that installing `certifi` on the host running `salt-ssh` resolves it.  See below:

```yaml
# salt-ssh --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

# salt-ssh -t --user=vagrant --passwd=vagrant --sudo 192.168.22.131 test.ping
[ERROR   ] Failed collecting tops for Python binary python3.
ubuntu14.local:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.vagrant_c36ad5_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.vagrant_c36ad5_salt/pyall/salt/scripts.py", line 426, in salt_call
            import salt.cli.call
          File "/var/tmp/.vagrant_c36ad5_salt/pyall/salt/cli/call.py", line 8, in <module>
            import salt.cli.caller
          File "/var/tmp/.vagrant_c36ad5_salt/pyall/salt/cli/caller.py", line 18, in <module>
            import salt.loader
          File "/var/tmp/.vagrant_c36ad5_salt/pyall/salt/loader.py", line 31, in <module>
            import salt.utils.event
          File "/var/tmp/.vagrant_c36ad5_salt/pyall/salt/utils/event.py", line 75, in <module>
            import tornado.iostream
          File "/var/tmp/.vagrant_c36ad5_salt/py2/tornado/iostream.py", line 39, in <module>
            from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
          File "/var/tmp/.vagrant_c36ad5_salt/py2/tornado/netutil.py", line 38, in <module>
            import certifi
        ImportError: No module named certifi
    stdout:
# pip install certifi
Collecting certifi
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Installing collected packages: certifi
Successfully installed certifi-2019.6.16
# salt-ssh -t --user=vagrant --passwd=vagrant --sudo 192.168.22.131 test.ping
[ERROR   ] Failed collecting tops for Python binary python3.
ubuntu14.local:
    True
```
