### ISSUE TITLE
msiexec return code 1641 is not an "error"

### ISSUE THREAD

**Issue by rhavenn** [saltstack/salt#44389]
### Description of Issue/Question

I'm building some Windows installers and one of them is for VMware View Agent. The install works fine, but the uninstall throws an error on the salt side. However, it is actually uninstalled cleanly.

The MSI initiates a reboot and the return code is: 1641 

A MSI 1641 is ERROR_SUCCESS_REBOOT_INITIATED . So, it's successfully removed the package, but is issuing a reboot. I would think that provision should be added to salt so that a 1641 is considered successful.

### Setup
```
vmware_view-agent:
  '7.3.1':
    full_name: 'VMware Horizon Agent'
    installer: '//server.local/Installers/VMware/View/Agent/VMware-viewagent-x86_64-7.3.1-6761322.exe'
    uninstaller: 'msiexec.exe'

    install_flags: '/s /v "/qn VDM_VC_MANAGED_AGENT=1 RDP_CHOICE=1"'
    uninstall_flags: "/x '{3B6E5C86-8884-4938-BBE4-E540F0D590D0}' /qn"
    msiexec: False
    reboot: True
```

### Steps to Reproduce Issue
Have a windows MSI uninstall that returns a 1641

### Versions Report
salt 2017.7.1 and minion is 2017.7.2
