### ISSUE TITLE
salt-ssh in versions from 2017 has problems with grains

### ISSUE THREAD

**Issue by inf0rmix** [saltstack/salt#44394]
### Description of Issue/Question
salt-ssh does not handle grains correctly. It outputs the first grain faound for each consecutive grain.

### Setup
Kubuntu 17.04 with default salt version 2016.11.2 is working without problems, salt version 2017.1 and 2017.2 have the issue

### Steps to Reproduce Issue
---- kubuntu 17.04 with default salt installation

inf0rmix@tardis:~/salt$ salt-ssh --version
salt-ssh 2016.11.2 (Carbon)

```
inf0rmix@tardis:~/salt$ salt-ssh '*' grains.get loc
tardis:
    Various
web:
    Berlin
nx:
    Todendorf
```

---- Update to to salt 2017 on kubuntu 17.04

curl -L https://bootstrap.saltstack.com -o install_salt.sh
sudo sh install_salt.sh -P -M

----

inf0rmix@tardis:~$ salt-ssh --version
salt-ssh 2017.7.2 (Nitrogen)

----

```
inf0rmix@tardis:~$ salt-ssh '*' grains.get loc
web:
    Various
tardis:
    Various
nx:
    Various
```

**Comment by Ch3LL** [comment]
how did you set those grains? Is it a custom grain? Did you use an execution module to set those grains?

**Comment by austinpapp** [comment]
i can't get any grains from `salt-ssh <minion> grains.get inf` which is defined in `/etc/salt/grains`

**Comment by Ch3LL** [comment]
With salt-ssh I don't believe it would read from /etc/salt/grains, although i have not tested this. That would be for an installed minion.

You would need to set them in your roster like so:

```
  grains:
    is_ssh: 2
    op_env: staging
```

How do you have the grain `loc` set? Is it also in /etc/salt/grains on the salt-ssh minion?

**Comment by inf0rmix** [comment]
Here is my rooster

```
web:
  host: fenner.info
  user: inf0rmix
  sudo: True
  grains:
    hoster: strato
    provider: starto
    loc: Berlin

tardis:
  host: localhost
  user: saltadm
  sudo: True
  grains:
    loc: Various

```
