### ISSUE TITLE
fqdn_ip6 empty in 2017.7.2

### ISSUE THREAD

**Issue by AJK9** [saltstack/salt#44399]
### Description of Issue/Question
After upgrading to 2017.7.2 fqdn_ip6 is not populated after applying a network state file.
The fdqn_ip4 grain is populated but fqdn_ip6 is not even though an IPv6 address is applied to the network interface.  This was working in previous versions.

### Setup
Deploy a host using salt-cloud.  As part of the salt build I have a network.sls on the master which is applied to the host once testing has been completed.  It applies public IP addresses, including a floating address to be used across hosts for anycast

network.sls on master (note using example addresses in below example)
```
system:
  network.system:
    - enabled: True
    - hostname: {{ grains['id'] }} 
    - gateway: 192.168.0.1
    - ipv6gateway: 2001:db8::1
    - gatewaydev: {{ salt['network.default_route']('inet')[0]['interface'] }}
    - nozeroconf: True

{{ salt['network.default_route']('inet')[0]['interface'] }}:
  network.managed:
    - enabled: True
    - type: eth
    - proto: none
    - ipaddr: 192.168.0.74
    - netmask: 255.255.255.0
    - ipv6_autoconf: no
    - enable_ipv6: true
    - ipv6addr: 2001:db8:6:101::74/64  
    - dns:
      - 192.168.6.2
      - 192.168.6.5

lo:0:
  network.managed:
    - enabled: True
    - type: eth
    - proto: none
    - ipaddr: 192.168.253.73
    - netmask: 255.255.255.0
    - ipv6_autoconf: no
    - enable_ipv6: false


lo:
  network.managed:
    - enabled: True
    - type: eth
    - proto: none
    - ipaddr: 127.0.0.1
    - netmask: 255.0.0.0
    - ipv6_autoconf: no
    - enable_ipv6: true
    - ipv6addr: 2001:db8:253:106::73/48 


'restart.network.service':
  cmd.run:
    - name: systemctl restart network

'restart.salt-minion.service':
  cmd.run:
    - name: systemctl restart salt-minion 
```

### Steps to Reproduce Issue
salt "*" state.apply network.sls

**On master:**
salt "host1.example.com" grains.get domain
host1.example.com:
    example.com

salt "host1.example.com" grains.get fqdn_ip4
host1.example.com:
    - 192.168.0.74

salt "host1.example.com" grains.get ip4_interfaces
host1.example.com:
    ----------
    eth0:
        - 192.168.0.74
    lo:
        - 127.0.0.1
        - 192.168.253.73

salt "host1.example.com" grains.get ip6_interfaces
host1.example.com:
    ----------
    eth0:
        - 2001:db8:6:101:250:56ff:fea5:70d7
        - 2001:db8:6:101::74
        - fe80::250:56ff:fea5:70d7
    lo:
        - 2001:db8:253:106::73
        - ::1

salt "host1.example.com" grains.get fqdn_ip6
host1.example.com

**On minion:**
salt-call grains.get domain
local:
    example.com

salt-call grains.get ip4_interfaces
local:
    ----------
    eth0:
        - 192.168.0.74
    lo:
        - 127.0.0.1
        - 192.168.253.73

salt-call grains.get fqdn_ip4
local:
    - 192.168.0.74

salt-call grains.get ip6_interfaces
local:
    ----------
    eth0:
        - 2001:db8:6:101:250:56ff:fea5:70d7
        - 2001:db8:6:101::74
        - fe80::250:56ff:fea5:70d7
    lo:
        - 2001:db8:253:106::73
        - ::1

salt-call grains.get fqdn_ip6
local:

### Versions Report
Master 
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

Minion
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

My configuration has not changed between versions or builds.  Hosts built using the last version of salt all report the fqdn_ip6 address ok.

Assuming this is a bug but not ruling out my configuration being to blame.
