### ISSUE TITLE
win_perms doesn't seem to work correctly

### ISSUE THREAD

**Issue by rhavenn** [saltstack/salt#44397]
### Description of Issue/Question

Using the example, almost verbatim, from the [win_perms section](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.directory)

It doesn't apply the win_perms to the directory I'm creating. I don't know if the documentation is wrong or I'm doing something wrong.

### Setup
```
 c_dbg:
  file.directory:
    - name: C:/DBG/
    - win_owner: AdminGroup@domain.local
    - win_inheritance: False
    - win_perms:
      AdminGroup@domain.local:
        perms: full_control
```
minion debug shows this as being processed as:

OrderedDict([('c_dbg', OrderedDict([('file.directory', [OrderedDict([('name', 'C:/DBG/')]), OrderedDict([('win_owner', 'AdminGroup@domain.local')]), OrderedDict([('win_inheritance', False)]), OrderedDict([('win_perms', None), ('AdminGroup@domain.local', OrderedDict([('perms', 'full_control')]))])])]))])

### Steps to Reproduce Issue
Setup the SLS as above.

If I change my SLS to be this:
```
c_dbg:
  file.directory:
    - name: C:/DBG/
    - win_owner: AdminGroup@domain.local
    - win_inheritance: False
    - win_perms: { AdminGroup@domain.local: { perms: full_control} }
```

It works fine. Minion debug shows:

OrderedDict([('c_dbg', OrderedDict([('file.directory', [OrderedDict([('name', 'C:/DBG/')]), OrderedDict([('win_owner', 'AdminGroup@domain.local')]), OrderedDict([('win_inheritance', False)]), OrderedDict([('win_perms', OrderedDict([('AdminGroup@domain.local', OrderedDict([('perms', 'full_control')]))]))])])]))])

### Versions Report
salt 2017.7.1 master and 2017.7.2 minion
