### ISSUE TITLE
modules/zfs not able to handle dataset names or mount points with space or other characters

### ISSUE THREAD

**Issue by 3add3287** [saltstack/salt#44401]
### Description of Issue/Question
It's not possible to create/delete/change zfs filesystems if the filesystem name or the mount point include spaces.

### Setup

```
something:
  zfs.filesystem_present:
    - name: pool/Foo Bar
    - properties:
        mountpoint: /Foo Bar
```

### Steps to Reproduce Issue
Setup state as outline above for a minion supporting zfs. The state will fail: 
`stderr:` cannot open 'pool/Foo Bar': dataset does not exist

### Versions Report
```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep  2 2017, 15:19:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE
         system: FreeBSD
        version: Not Installed
```
