### ISSUE TITLE
The win_path.exists state cannot prepend to the very start of the PATH

### ISSUE THREAD

**Issue by mtkennerly** [saltstack/salt#44423]
### Description of Issue/Question
The win_path.exists documentation has an example with `index=0`, which presumably should append at the very start of the PATH, like the underlying win_path.add function. However, the state has this condition:

[`if index:`](https://github.com/saltstack/salt/blob/b6079e2b71a2f0fb508c0d8459dad35fe9fdd329/salt/states/win_path.py#L99)

So `index=0` is always handled the same as the default `index=None`, so it will always append instead of prepend.

### Setup / Steps to Reproduce Issue
You can use this state from the documentation, then verify that it has been added at the end:
```
'C:\\sysinternals':
  win_path.exists:
    - index: 0
```

### Versions Report
This is the version I'm using, but the issue still exists in the latest code

```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: x86
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```
