### ISSUE TITLE
Misleading output when doing a test run on a fresh host

### ISSUE THREAD

**Issue by michailsideris-gvf** [saltstack/salt#44431]
### Description of Issue/Question
When trying to setup a new host with salt, I usually do a test run (test=True) before I execute a real highstate. In that case, services that are marked as running in my SLSs give misleading, error-like output due to the absence of the required package.

### Setup
```
monit:
  pkg.installed: []
  service.running:
    - enable: True
    - require:
      - pkg: monit
```

### Steps to Reproduce Issue
Try doing `salt '*' state.highstate test=True` on a brand new host using the SLS provided above. You should get the following output (in red, nonetheless):

```
----------
          ID: monit
    Function: service.running
      Result: False
     Comment: The named service monit is not available
     Started: 20:47:36.983004
    Duration: 48.256 ms
     Changes:
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
