### ISSUE TITLE
jinja for loop not iterating over pillar dictionary

### ISSUE THREAD

**Issue by ferreol** [saltstack/salt#44456]
### Description of Issue/Question
No matter how, I cannot seem to have jinja macro iterate over a pillar dictionary.
it 'works' as expected if I do not do `for` loop but just use some explicit key to access pillar data.
### Setup
sls receipe contains
```
{% for application_family_name in pillar['applications_map'] %} <- does not loop, just jumps to endfor
{% for application_family_name,args in pillar.get('applications_map',{}).items() %} <- this alternate syntax does not work either
  {% if application in pillar['applications_map'][application_family_name]['applications'] %} <- works as expected
    {% if pillar['applications_map'][application_family_name]['applications'][application]['primary'] == grains['host'] %}
      {% set role = pillar[application+'_properties']['start_mode']['primary_machine'] %}
    {% endif %}
  {% endif %}
{% endfor %}
```
the pillar data looks like
```
applications_map:
  family_type_one:
    applications:
      application_name_1:
        primary: machine1
        standby: machine2

  family_type_two:
    applications:
      application_name_2:
        primary: machine1
        standby: machine2
```

### Versions Report
$ salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.9
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9
