### ISSUE TITLE
Support assertEmpty

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#44474]
### Description of Issue/Question
Some salt modules such as pkg.latest_version (yum) produce no output. For that module, it will output either the latest version number of the available package, or no output if the package is up to date. 
Thus the saltcheck test to verify if a package is at the latest version could read as:
```
openssh-server-latest:
  module_and_function: pkg.latest_version
  args:
    - openssh-server
  kwargs:
  assertion: assertEqual
  expected-return: ""
```
But when running this test, it fails due to the lack of an expected return. 

So perhaps the expected return check could be disabled as sometimes this is expected, or an assertEmpty assertion could be introduced which would selectively disable the expected-return check.

@wcannon
