### ISSUE TITLE
The file.line execution function seems to fail

### ISSUE THREAD

**Issue by UtahCampusD** [saltstack/salt#44509]
### Description of Issue/Question

When trying to replace a single line on a file by matching part of the current content, it fails. The debugging run doesn't seem to show errors and the return seems to indicate what will updated. When checking the file afterwards no change seems to be seen.

### Setup
Small lab with a single master and a couple of minions.

### Steps to Reproduce Issue

```
[root as root@minion1:~ ]$ cat test_file.txt 
minion_id:6244676289953792
minion_name:minion1
minion_token:FPDqiPzweC74lyN
[root as root@minion1:~ ]$ salt-call -l debug file.line /root/test_file.txt "minion_token:KHwqrehwadK34jakdh" match="minion_token" mode="replace" backup=True
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.5.100:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8533)
[DEBUG   ] Setting zmq_reconnect_ivl to '8533ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.5.100:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_738faf60a7_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_738faf60a7_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_738faf60a7_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-11-13T16:09:06.785173', 'creds': {'publish_port': 4505, 'aes': 'nK0kRjrxBh7FuQV6EL84Ewm1ISj6X0/hLskr48GUOR/Ds9RH9ePgIPbXcshKq91I1FlzvUOTYtY=', 'master_uri': 'tcp://192.168.5.100:4506'}, 'key': ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.5.100:4506')}
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.5.100:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.5.100:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded file.line
[DEBUG   ] LazyLoaded local_cache.returner
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.5.100:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.5.100:4506')
[DEBUG   ] LazyLoaded nested.output
local:
    --- 
    +++ 
    @@ -1,4 +1,4 @@
     minion_id:6244676289953792 minion_name:minion1-minion_token:FPDqiPzweC74lyN+minion_token:KHwqrehwadK34jakdh 
[root as root@minion1:~ ]$ cat test_file.txt 
minion_id:6244676289953792
minion_name:minion1
minion_token:FPDqiPzweC74lyN
[root as root@minion1:~ ]$ 
```

### Versions Report
[root as root@minion1:~ ]$ salt-call --versions
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
 
[root as root@minion1:~ ]$

**Comment by gtmanfred** [comment]
Last Friday, there were some fixes in file.line that were merged into the salt develop branch, would you be able to check these changes and see if it fixes your problems?

https://github.com/saltstack/salt/pull/44361

Thanks,
Daniel

**Comment by UtahCampusD** [comment]
I tried with 2017.7.1-5244-gdd2844a. Seem to be getting the same results.

`[root@minion2 ~]# cat test_file.txt 
minion_id:6244676289953792
minion_name:minion1
minion_token:FPDqiPzweC74lyN


[root@minion2 ~]# salt-call -l debug file.line /root/test_file.txt "minion_token:KHwqrehwadK34jakdh" match="minion_token" mode="replace" backup=True

[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', 'minion2', u'tcp://10.0.2.30:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9114)
[DEBUG   ] Setting zmq_reconnect_ivl to '9114ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', 'minion2', u'tcp://10.0.2.30:4506', u'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_59fbbd3c10_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_59fbbd3c10_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_59fbbd3c10_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-11-13T19:06:42.762507', u'creds': {u'publish_port': 4505, u'aes': 'fOO1Ud6Rze5MwtvlNkr5wI+PrcU4tUH0daGyBeCENz/V8ID/BjoUZhzIesyx9cWzVeFIAoqg2rI=', u'master_uri': u'tcp://10.0.2.30:4506'}, u'key': (u'/etc/salt/pki/minion', 'minion2', u'tcp://10.0.2.30:4506')}
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', 'minion2', u'tcp://10.0.2.30:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', 'minion2', u'tcp://10.0.2.30:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded file.line
[DEBUG   ] LazyLoaded local_cache.returner
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', 'minion2', u'tcp://10.0.2.30:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', 'minion2', u'tcp://10.0.2.30:4506')
[DEBUG   ] LazyLoaded nested.output
local:
    --- 
    +++ 
    @@ -1,4 +1,4 @@
     minion_id:6244676289953792 minion_name:minion1-minion_token:FPDqiPzweC74lyN+minion_token:KHwqrehwadK34jakdh 

[root@minion2 ~]# cat test_file.txt 
minion_id:6244676289953792
minion_name:minion1
minion_token:FPDqiPzweC74lyN
[root@minion2 ~]#`

[root@minion2 ~]# salt-call --versions
Salt Version:
           Salt: 2017.7.1-5244-gdd2844a
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
 
[root@minion2 ~]#

**Comment by gtmanfred** [comment]
Thanks, I will look into replicating this in a bit.

Daniel

**Comment by gtmanfred** [comment]
I am unable to replicate this with 2017.7.2

```
[root@1c30836f3912 ~]# cat /tmp/test
minion_id:6244676289953792
minion_name:minion1
minion_token:FPDqiPzweC74lyN
[root@1c30836f3912 ~]# salt-call --local file.line /tmp/test "minion_token:KHwqrehwadK34jakdh" match="minion_token" mode="replace" backup=True
local:
    ---
    +++
    @@ -1,4 +1,4 @@
     minion_id:6244676289953792 minion_name:minion1-minion_token:FPDqiPzweC74lyN+minion_token:KHwqrehwadK34jakdh
[root@1c30836f3912 ~]# cat /tmp/test
minion_id:6244676289953792
minion_name:minion1
minion_token:KHwqrehwadK34jakdh
```

**Comment by UtahCampusD** [comment]
This is so strange. Tried again with 2017.7.2 but still the same results. I removed the file extensions from the file, the underscores on the name and moved it to the /tmp dir like your sample but still it doesn't get updated. I also updated SELINUX to setenforce 0 for testing but not difference. Where you using CentOS 7.4? I guess I have some other different OS versions that I could try (Ubuntu, Windows)

**Comment by gtmanfred** [comment]
```
[root@3c1fc9bc7475 ~]# cat /tmp/test
minion_id:6244676289953792
minion_name:minion1
minion_token:FPDqiPzweC74lyN
[root@3c1fc9bc7475 ~]# salt-call file.line /tmp/test "minion_token:KHwqrehwadK34jakdh" match="minion_token" mode="replace" backup=True --local
local:
    ---
    +++
    @@ -1,4 +1,4 @@
     minion_id:6244676289953792 minion_name:minion1-minion_token:FPDqiPzweC74lyN+minion_token:KHwqrehwadK34jakdh
[root@3c1fc9bc7475 ~]# cat /tmp/test
minion_id:6244676289953792
minion_name:minion1
minion_token:KHwqrehwadK34jakdh
[root@3c1fc9bc7475 ~]# salt-call --versions-report --local
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.93-boot2docker
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

I was on arch on the last one, but on centos 7.4 it still works :/ it might be worth while to delete the pyc files on the minion and just see if that is causing it?

`find /usr/lib/python2.7/site-packages/salt -name \*.pyc -delete`

But unfortunately I am unable to replicate this issue.
