### ISSUE TITLE
git pillar does not behave

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#44539]
### Description of Issue/Question
Salt claims that a Pillar SLS is not available despite the fact that the SLS in question is super available. Any help would be greatly appreciated. I may have done something wrong in the config, but if so I have no idea what that would be.

### Setup
```
### /etc/salt/master ###
ext_pillar:
  - git:
    - develop git@dev.gitlab.cloud.company.com:salt/pegs-ossec.git:
      - root: pillar
      - env: base

### repo structure ###
#  /
#    pillar/
#      ossec/
#        agent_keys.sls
#

### pillar.get_items ###
# local:
#     ----------
#     _errors:
#         - Specified SLS 'ossec.agent_keys' in environment 'base' is not available on the salt master
```

### Steps to Reproduce Issue
run `salt-call saltutil.refresh_pillar` on the minion, receive `True`
run `salt-call pillar.items` on the minion, receive `Specified SLS in environment is not available blah blah` rather than useful information.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
