### ISSUE TITLE
Jinja formatting inconsistency

### ISSUE THREAD

**Issue by absolutejam** [saltstack/salt#44562]
### Description of Issue/Question

Bit of a weird one, but I have some data in Pillar that I'm altering before putting it into a config file. When I output the final variable `{{ vars_listified }}` (Wonderful name, I know) with `cmd.run` using `echo`,  or `file.managed` `contents: {{ vars_listified }}` it formats correctly.

However, if I use this within a yaml template, with `file.serialized`, it doesn't format the data correctly.

### Setup

My pillar:
```
sensu:
  vars:
    services:
      critical:
        'ReportServer$OLIVER':
        'MSSQL$OLIVER':
        'SoftlinkOliver':
```

Which also gets merged with:
```
sensu:
  vars:
    services:
      important:
        'salt-minion':
        'telegraf':
```
As you can see, I'm using empty dicts as a way to merge data between different Pillars.

jinja
```
{%- set vars = salt['pillar.get']('sensu:vars', {}) -%}
{%- set vars_listified = {} -%}
{%- for service, values in vars.iteritems() -%}
  {# Create the service entry #}
  {%- do vars_listified.update({ service: {} }) -%}
  {%- if values is mapping -%}
    {%- for importance, items in values.items() -%}
      {%- set items_list = items.keys() | join(',') -%}
      {%- do vars_listified[service].update({ importance: items_list }) -%}
    {%- endfor -%}
  {%- else -%}
      {%- do vars_listified.update({ service: values }) -%}
  {%- endif -%}
{%- endfor -%}
{%- set client_vars = {} -%}
{%- do client_vars.update({ 'client': vars_listified }) -%}
```

This basically looks under `sensu:vars:services:critical` (And any other keys at this level) and merges all keys that are empty dicts into a single string, with the end result of `{{ vars_listified }}` producing the following dict:

```
{'services': {'important': u'salt-minion,telegraf', 'critical': u'SoftlinkOliver,MSSQL$OLIVER,ReportServer$OLIVER'}}
```

Again, this works fine if I use the above jinja and include the contents in a `cmd.run echo` or `file.managed contents`.

However, my original aim was to embed it within an existing config file that gets rendered to minions:

template.yml (A cut down version)
```
client:
  name: 'somehost'
  os: {{ salt['grains.get']('os') }}
  vars: {{ vars_listified }}
```

Which renders to:
```
    "vars": {
      "services": {
        "MSSQL$OLIVER": "None",
        "ReportServer$OLIVER'": "None",
        "critical": "u'SoftlinkOliver",
        "important": "u'salt-minion",
        "telegraf'": "None"
      }
    },
```

I had previously just used a list in my Pillar (Before realising the issue with lists being overwritten, not merged like dicts) and used `vars: {{ salt['pillar.get']('sensu:vars') }}` in my template with no issues, so I'm not sure why I'm hitting the issue now.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.5.2
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-97-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Minion also on same version.

**Comment by lorengordon** [comment]
A key with no value is not an empty dict, but a key with a value of `None`. If you want it to be an empty dict, you need to assign it an empty dict:

```
sensu:
  vars:
    services:
      critical:
        'ReportServer$OLIVER': {}
        'MSSQL$OLIVER': {}
        'SoftlinkOliver': {}
```
