### ISSUE TITLE
Add system objects under security security settings

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#44635]
### Description of Issue/Question
"Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\Security Options\System objects: ******" is not available to be configured in the module.

### Setup

Add the following state:

```
configure_system_objects: 
  lgpo.set: 
    - computer_policy: 
        "System objects: Require case insensitivity for non-Windows subsystems": Enabled 
        "System objects: Strengthen default permissions of internal system objects (e.g. Symbolic Links)": Enabled
```
The following error should be returned

```
          ID: router_computer_gpo
    Function: lgpo.set
      Result: False
     Comment: Unable to find Machine policy System objects: Require case insensitivity for non-Windows subsystems Unable to find Machine policy System objects: Strengthen default permissions of internal system objects (e.g. Symbolic Links)
     Started: 15:20:07.447000
    Duration: 1031.0 ms
     Changes:   
```

Checking the code for the `win_lgpo.py` module in commit `55913a51cec944952c8a68e7424f2407c1a73c29` these settings do not appear to be added in the _policy_info class.

### Versions Report
    Salt Version:
               Salt: 2017.7.1
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.2
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
