### ISSUE TITLE
Typo in win_lgpo.py

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#44633]
### Description of Issue/Question
There is a typo in `win_lgpo.py` in the word _applications_  causing the following error:

```
          ID: configure_ui_access
    Function: lgpo.set
      Result: False
     Comment: Unable to find Machine policy User Account Control: Only elevate UIAccess applications that are installed in secure locations
     Started: 11:51:09.997000
    Duration: 1219.0 ms
     Changes:  

```

If you use `applicaitons` instead of `applications` the state works as expected.

### Setup
Run a salt-minion on Windows 2012 R2 using PY2. 

Configure this state:

```
configure_ui_access: 
  lgpo.set: 
    - computer_policy: 
        "User Account Control: Only elevate UIAccess applications that are installed in secure locations": Enabled
```

### Steps to Reproduce Issue
Check line 1080 in `win_lgpo.py` as of commit 3c24edd6a5f9ec11530843c704df316b59dc5365.

### Versions Report
Minion Versions is:
    Salt Version:
               Salt: 2017.7.1
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.2
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
