### ISSUE TITLE
Merge grains dict from /etc/salt/minion with /etc/salt/grains

### ISSUE THREAD

**Issue by chs-bnet** [saltstack/salt#44636]
### Description of Issue/Question
I'm appending to a grain in a state file using `grains.append`  with `reload_grains` set to `True`. I'm also calling a `saltutil.sync_grains` using `module.run` just to be certain.

When I run this state file, the output shows no errors and shows that the grain has been correctly appended to. When I look at the contents on the minion of `/etc/salt/grains`, the new grain is there. When I do a `grains.get` from the master, it does not show up.

State file:
```
roles:
  grains.append:
    - convert: True
    - value: elasticsearch
    - reload_grains: True

sync_custom_grain:
  module.run:
    - name: saltutil.sync_grains
```

Output:
```
local:
----------
          ID: roles
    Function: grains.append
      Result: True
     Comment: Value elasticsearch was added to grain roles
     Started: 00:25:58.633167
    Duration: 304.825 ms
     Changes:   
              ----------
              added:
                  elasticsearch
----------
          ID: sync_custom_grain
    Function: module.run
        Name: saltutil.sync_grains
      Result: True
     Comment: Module function saltutil.sync_grains executed
     Started: 00:25:58.938818
    Duration: 92.162 ms
     Changes:   
              ----------
              ret:

Summary for local
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time: 396.987 ms
```

minion:
```
es-master:~# cat /etc/salt/grains
roles:
- es-master
- elasticsearch
```

master:
```
# salt es-master grains.get roles
es-master:
    - es-master
```

### Versions Report
Salt Minion:
```
~# salt-minion -V
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1035-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

Salt Master:
```
# salt -V
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1020-aws
         system: Linux
        version: Ubuntu 16.04 xenial
 
```

**Comment by gtmanfred** [comment]
sync_grains syncs custom grains from `salt://_grains` you want `saltutils.refresh_grains` which will also refresh the grains.  or use the `refresh_grains` like you are using in your first state.

```
root@salt:~# tail -c +0 /srv/salt/*.sls
==> /srv/salt/create.sls <==
create:
  grains.present:
    - name: roles
    - value: role1
    - reload_grains: True

==> /srv/salt/update.sls <==
update:
  grains.append:
    - name: roles
    - convert: True
    - value: role2
    - reload_grains: True
root@salt:~# salt \* grains.get roles
salt.c.gtmanfred-1263.internal:
    None
root@salt:~# salt \* state.apply create
salt.c.gtmanfred-1263.internal:
----------
          ID: create
    Function: grains.present
        Name: roles
      Result: True
     Comment: Set grain roles to role1
     Started: 01:52:38.207314
    Duration: 589.874 ms
     Changes:
              ----------
              roles:
                  role1

Summary for salt.c.gtmanfred-1263.internal
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 589.874 ms
root@salt:~# salt \* grains.get roles
salt.c.gtmanfred-1263.internal:
    role1
root@salt:~# salt \* state.apply update
salt.c.gtmanfred-1263.internal:
----------
          ID: update
    Function: grains.append
        Name: roles
      Result: True
     Comment: Value role2 was added to grain roles
     Started: 01:52:44.495340
    Duration: 505.654 ms
     Changes:
              ----------
              added:
                  role2

Summary for salt.c.gtmanfred-1263.internal
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 505.654 ms
root@salt:~# salt \* grains.get roles
salt.c.gtmanfred-1263.internal:
    - role1
    - role2
root@salt:~#
```

**Comment by chs-bnet** [comment]
Updated state (changed to `refresh_grains`):
```
roles:
  grains.append:
    - convert: True
    - value: elasticsearch
    - reload_grains: True

sync_custom_grain:
  module.run:
    - name: saltutil.refresh_grains
```

Slightly new/different output:
```
local:
----------
          ID: roles
    Function: grains.append
      Result: True
     Comment: Value elasticsearch was added to grain roles
     Started: 16:39:57.129667
    Duration: 290.318 ms
     Changes:   
              ----------
              added:
                  elasticsearch
----------
          ID: sync_custom_grain
    Function: module.run
        Name: saltutil.refresh_grains
      Result: True
     Comment: Module function saltutil.refresh_grains executed
     Started: 16:39:57.420773
    Duration: 2.392 ms
     Changes:   
              ----------
              ret:
                  True

Summary for local
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time: 292.710 ms
```

`saltutil.refresh_grains` is now returning `True`, but the results are unchanged:

```
# salt es-master cmd.run 'cat /etc/salt/grains'
es-master:
    roles:
    - es-master
    - elasticsearch

# salt es-master grains.get roles
es-master:
    - es-master
```

**Comment by chs-bnet** [comment]
I did some digging and found some new info. I restarted the minion, and the grain was still not refreshed.

We are deploying these minions to AWS and injecting the initial role into the salt config:
```
root@es-master:~# cat /etc/salt/minion
---
grains:
    region: us-XXXX-Y
    roles:
    - es-master
    vpc_id: vpc-XXXXXXX
master: salt
metadata_server_grains: true
mine_functions:
    network.ip_addrs: []
...
```

And of course the contents of `/etc/salt/grains` that gets updated via my state:
```
root@es-master:~# cat /etc/salt/grains 
roles:
- es-master
- elasticsearch
```

My guess is that the `refresh_grains` is not merging the grains from the two files.

Thoughts?

**Comment by fouts-bnet** [comment]
FWIW this is how we're setting up the minion config:

```
#cloud-config
<snip>
salt_minion:
  conf:
    master: salt.us-east-1.local
    mine_functions:
      network.ip_addrs: []
    metadata_server_grains: true
    grains:
      roles:
        - the_role
      region: us-east-1
      vpc_id: vpc-xxx
<snip>
```
