### ISSUE TITLE
Add Shutdown options under Security Settings

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#44652]
### Description of Issue/Question
It would be great to have these settings for CIS compliance.

```
Shutdown: Allow system to be shut down without having to log on
Shutdown: Clear virtual memory pagefile
``` 

These settings can be found under:
Computer->Windows Settings->Security Settings->Local Policies->Security Options

### Setup
Configure and run a state like this:
```
configure_shutdown_options:
  lgpo.set:
    - computer_policy:
        "Shutdown: Allow system to be shut down without having to log on": Disabled
        "Shutdown: Clear virtual memory pagefile": Disabled
```

This should return stating the policy is not found. Checking the code the policies do not appear to configurable in the module.

### Versions Report
    Salt Version:
               Salt: 2017.7.1
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.2
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
