### ISSUE TITLE
Traversing salt tree structure woes. 

### ISSUE THREAD

**Issue by hunkeelin** [saltstack/salt#44684]
Assume I have the below pillar. 

```
    sambafs:
         - test1:
            path: /data/testdir1
         - test2:
            path: /data/testdir2
```

In  jinja template in order to get to `/data/testdir1` I have to do the following. {{ pillar['sambafs'][0]['test1']['path'] }} wheredoes logic would seem to be.  {{ pillar['sambafs'][0]['path'] } this is troublesome because it will hinder the ability to loop through the tree structure.  See below. 

```
{{%- for dir in pillar['sambafs'] %}
path = {{ dir['path'] }} <-- this will result in an error in order to get to bath I will have to do {{dir['test1']['path'] }} but then it will defeat the purpose of looping because I am predefining the variable(test1) that I am trying to loop. 
{%- endfor -%}
```

I tried an alternate work around to no aval. 

```
{{%- for dir in pillar['sambafs'] %}
path = {{ dir['{{dir}}']['path'] }}  <-- it seems jinja doesn't parse it properly to get this to work. 
{%- endfor -%}
```

**Comment by Ch3LL** [comment]
This worked for me:

```
{%- for list in pillar['sambafs'] %}
  {% for dir,path in list.items() %}

echo {{ path['path'] }}:
  cmd.run

  {%- endfor -%}
{%- endfor -%}

```

does that work for your use case?

**Comment by sflttc** [comment]
Yes it does but it's kind of convoluted. I end up changing it to. 

```
  sambafs:
         test1:
            path: /data/testdir1
         test2:
            path: /data/testdir2
```

Then use the following loop:

```
{%- for dir in pillar['sambafs'].values() %}
[{{dir["name"]}}]
path = {{dir["path"]}}
{%- endfor -%}

```

**Comment by hunkeelin** [comment]
Yes it does but it's kind of convoluted. I end up changing it to.

```
  sambafs:
         test1:
            path: /data/testdir1
         test2:
            path: /data/testdir2
```
Then use the following loop:

```
{%- for dir in pillar['sambafs'].values() %}
[{{dir["name"]}}]
path = {{dir["path"]}}
{%- endfor -%}
```
