### ISSUE TITLE
Overriding state/pillar values.

### ISSUE THREAD

**Issue by llevar** [saltstack/salt#44683]
I'm trying to use Saltstack in a scenario where there is a base product with some states/pillar defined in a git repo, and then there are custom applications of that base product with augmented/overridden states/pillar as necessary in a separate git repo. For each custom application, the user copies the top file from the base product and customizes it as necessary. 

I have gitfs set up with the two repos and states seem to function reasonably well this way, but I am running into an issue with pillar, where if I list the customization first in the master file and then the base product:
```
  - git:
    - master git://github.com/llevar/custom.git:
      - root: configuration/salt/pillar
      - env: base
    - master git://github.com/llevar/base_product.git:
      - root: configuration/salt/pillar
      - env: base
```

...then the custom top file is picked up, but overridden pillar keys are not, i.e. pillar values from the base product are used. When I list the repos in reverse order:

```
  - git:
   - master git://github.com/llevar/base_product.git:
      - root: configuration/salt/pillar
      - env: base
   - master git://github.com/llevar/custom.git:
      - root: configuration/salt/pillar
      - env: base
    
```
... then pillar values are overridden as desired, but the base product top file is used, thus new sls files, and new keys, are not picked up.

Is something wrong in this setup? What is the right way to get the desired behaviour, i.e.:

Base product states/pillar by default, and custom states/pillar with overridden values if desired.

Thanks.

**Comment by Ch3LL** [comment]
Do you have any pillar specific master settings setup?

**Comment by llevar** [comment]
What do you mean by this? The code excerpts above are from my master file.

Below is pretty much the entire master configuration, with a bit of redaction:

```

# set output to detailed on failure
state_output: mixed

#set remote states and pillars
fileserver_backend:
  - git

gitfs_provider: gitpython

gitfs_remotes:
  - git://github.com/llevar/custom.git:
    - root: configuration/salt/state
    - base: master
  - git://github.com/llevar/base_product.git:
    - root: configuration/salt/state
    - base: master

#
pillar_roots:
  base:
    - /srv/pillar

top_file_merging_strategy: same
default_top: base

ext_pillar:
#Pillar overrides are in reverse order in order to work as expected
  - git:
    - master git://github.com/llevar/custom.git:
      - root: configuration/salt/pillar
      - env: base
    - master git://github.com/llevar/base_product.git:
      - root: configuration/salt/pillar
      - env: base
    
rest_cherrypy:
  port: 8000
  host: 0.0.0.0
  disable_ssl: True
```
