### ISSUE TITLE
cloud maps and overwrite providers: ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by PabloLemos** [saltstack/salt#44692]
### Description of Issue/Question
I have two differents sites: siteA and siteB with the same templates. SiteA is my production site and siteB is the backup site both sites with VMware.

I am building machines both on the production site and on the backup site for this I generate a cloud file from a profile that I use as a template. In the profile is specified the provider that, by default, is siteA but when creating machines in siteB I overwrite this value to indicate that the virtual machine must be created in siteB, but salt returns the following error:

`
[ERROR   ] Exception occurred in runner cloud.map_run: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 392, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/cloud.py", line 126, in map_run
    info = client.map_run(path, **_filter_kwargs(kwargs))
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 360, in map_run
    dmap = mapper.map_data()
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1988, in map_data
    alias, driver = nodedata['provider'].split(':')
ValueError: need more than 1 value to unpack
`

According to the documentation (https://docs.saltstack.com/en/latest/topics/cloud/map.html) 
Any top level data element from your profile may be overridden in the map file.

Can I overwrite the provider section of a profile in the cloud map file through orchestrate state?

### Setup

```
 create_instance:
  salt.runner:
    - name: cloud.map_run
    - kwarg:
        # Lanzamos la creacion de las maquinas en paralelo
        parallel: True
        # Construimos el fichero mapa
        map_data:
              # Invocamos a la funcion que generara el fichero cloud mapa
              redhat_7_x64_7-4_django:
                  # Definicion de la maquina a desplegar en ca90
                  prueba.srv.gva.es:
                      # Establecemos el proveedor donde crear la vm
                      provider: siteB

                      ## Definicion de los dispositivos de la maquina virtual
                      devices:
                        network:
                            Network adapter 1:
                              name: 413_LAB_TEST
                              # Establecemos el tipo de vswitch
                              switch_type: standard
                              # Establecemos la configuracion ip
                              ip: 10.10.10.10
                              gateway: [10.10.10.1]
                              subnet_mask: 255.255.255.0

                      ## Recursos de la maquina virtual
                      cluster: CL1_PLATA
                      datastore: dsv_pre_lin_02
                      extra_config:
                          guestinfo.hostname: prueba.localhost

```

```
# Profile: redhat_7_x64_7-4_django
# Perfil para la definicion de maquinas con el framework de aplicaciones
# python Django
redhat_7_x64_7-4_django:
    ## Parametros para desplegar una maquina virtual a partir de la
    ## plantilla
    provider: siteA
    clonefrom: redhat_7_x64_7-4_django

    ## Definicion de dispositivos: discos, tarjetas de red, etc.
    ## vCPUS & Memoria
    num_cpus: 4
    memory: 2GB

    ## Recursos de la maquina virtual
    hardware_version: 10
    extra_config:
        mem.hotadd: 'yes'
        cpu.hotadd: 'yes'

    ## Despliegue de agente salt-minion
    deploy: True
```

### Steps to Reproduce Issue
 
```
master:
----------
          ID: create_instance
    Function: salt.runner
        Name: cloud.map_run
      Result: False
     Comment: Exception occurred in runner cloud.map_run: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 392, in _low
                  data['return'] = self.functions[fun](*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/runners/cloud.py", line 126, in map_run
                  info = client.map_run(path, **_filter_kwargs(kwargs))
                File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 360, in map_run
                  dmap = mapper.map_data()
                File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1988, in map_data
                  alias, driver = nodedata['provider'].split(':')
              ValueError: need more than 1 value to unpack
     Started: 11:13:01.557621
    Duration: 2775.481 ms
     Changes:

Summary for master
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   2.775 s
```

### Versions Report

```
master ~> sudo salt --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-642.15.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago
```
