### ISSUE TITLE
Enabling the auto login on MacOS 10.12 doesn't work.

### ISSUE THREAD

**Issue by maxime-viargues-serato** [saltstack/salt#44721]
### Description of Issue/Question
Enabling the auto login on MacOS doesn't have any effect.
I tired on both El Capitan and Sierra.

### Setup
This is my state file

```
Auto login:
  module.run:
    - name: user.enable_auto_login
    - m_name: {{ user }}
    - unless: sudo salt-call user.get_auto_login | grep {{ user }}
    - require:
      - sudoers
```
`sudoers` just allows current user to use sudo without password.

### Steps to Reproduce Issue
On a clean machine I do a `sudo salt-call state.apply`
The state is correctly applied, and the `user.get_auto_login` returns the right user, however, in the user preferences > Login options, the automatic login is still set to Off.
Restarting the machine doesn't fix the problem, and obviously the user login is still prompted.

### Versions Report

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Oct  3 2017, 17:12:24)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 16.7.0
         system: Darwin
        version: 10.12.6 x86_64
```
