### ISSUE TITLE
rsync.synchronized state in dry-run / test=True does not return changes

### ISSUE THREAD

**Issue by ferreol** [saltstack/salt#44729]
I was pleased to discover the rsync state because it is an order of magnitude faster that file.recurse

rsync.synchronized state ran in dry mode returns the following output

```
----------
          ID: /sync-dir
    Function: rsync.synchronized
      Result: None
     Comment: - sent 260 bytes
              - received 2,437 bytes
              - 1,798.00 bytes/sec
              - total size is 72,321,289
              - speedup is 26,815.46 (DRY RUN)
     Started: 10:43:32.912365
    Duration: 229.755 ms
     Changes:
----------
```
The behavious seems to be done on purpose (with the "summary" terms)

however I believe it should be more relevant to have the local file modifications announced like other salt states.

https://github.com/saltstack/salt/blob/061ac1b3ab8eb1175dd1eb5429594366710ce303/salt/states/rsync.py#L50
)
updating
`
 return "- " + "\n- ".join([elm for elm in rsync_out.split("\n\n")[0].replace("  ", "\n").split("\n")[1:] if elm])
`
to have usable output

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.9
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9
```
