### ISSUE TITLE
State network.routes could not add route without gateway on centos7

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#44730]
### Description of Issue/Question
If we define route without gateway then route-eth0 looks like:
```
# cat /etc/sysconfig/network-scripts/route-eth0
8.8.8.0/255.255.255.0
```
If NetworkManager is enabled and working on system then route is added successfully but if NetworkManager is not enabled, which can happen on many systems, then route is not added. After adding `dev` to the route it works correctly.
```
# cat /etc/sysconfig/network-scripts/route-eth0
8.8.8.0/255.255.255.0 dev eth0
```
Behaviour has changed in salt 2015.8 when new template was introduced:
https://github.com/saltstack/salt/blob/develop/salt/templates/rh_ip/rh6_route_eth.jinja

Maybe it is possible to extend template to add `dev` declaration when route has no gateway ? Or add possibility to specify device to network.routes states and append `dev` when it set ?

### Setup
Example network.routes state configuration:
```
routes_eth0:
  network.routes:
    - name: eth0
    - routes:
      - name: external
        ipaddr: 8.8.8.0
        netmask: 255.255.255.0
      - name: internal
        ipaddr: 10.10.100.0
        netmask: 255.255.255.0
        gateway: 172.17.0.1
```

### Steps to Reproduce Issue
Add route configuration without gateway using state network.routes and disable NetworkManager on CentOS 7:
```
systemctl disable NetworkManager
systemctl enable network
reboot
```
