### ISSUE TITLE
htpasswd fails on FreeBSD with htpasswd.py replacement

### ISSUE THREAD

**Issue by campbellmc** [saltstack/salt#44749]
### Description of Issue/Question
webutil http password functions fail on FreeBSD
It's due to htpasswd being replaced by a python version htpasswd.py
This means the test for htpasswd in the path fails in `def __virtual__()` in module `htpasswd.py`:

https://github.com/saltstack/salt/blob/db32d81d8a694d5f08103dbe0af6306a3d8f4bf9/salt/modules/htpasswd.py#L28

htpasswd.py is functionally equivalent to htpasswd.

What is the best solution?  Test for the binary or python version when returning `__virtualname__` and then have a private method which returns the correct name to call when executing htpasswd?

### Setup
On FreeBSD:

```
 # pkg search py27-htpasswd
py27-htpasswd-2008.03.05_2     Replacement for htpasswd

 # pkg install py27-htpasswd
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
Updating SaltStack repository catalogue...
SaltStack repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        py27-htpasswd: 2008.03.05_2 [FreeBSD]

Number of packages to be installed: 1

Proceed with this action? [y/N]: y
[1/1] Installing py27-htpasswd-2008.03.05_2...
[1/1] Extracting py27-htpasswd-2008.03.05_2: 100%

 # which htpasswd.py
/usr/local/bin/htpasswd.py

 # which htpasswd
htpasswd: Command not found.

 # htpasswd.py -c -b .htpasswd bob bobspassword

 # grep bob .htpasswd
bob:VnaVmPRprLh4k
```

### Steps to Reproduce Issue

In some state file:

```
htpasswd_user_restricted_locations_{{htpasswd_user}}:
  webutil.user_exists:
    - name: {{htpasswd_user}}
    - password: {{args['password']}}
    - htpasswd_file: {{nginx.nginx_directory}}/{{nginx.webserver.restricted_locations.htpasswd_file}}
    - force: true
```
Yields:

```
----------
          ID: htpasswd_user_restricted_locations_someuser
    Function: webutil.user_exists
        Name: someuser
      Result: False
     Comment: State 'webutil.user_exists' was not found in SLS 'nginx.config'
              Reason: 'webutil.user_exists' is not available.
     Changes:
----------
```

### Versions Report
Master
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

Minion
```
 # salt --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.26.4
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 13 2017, 01:17:52)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE
         system: FreeBSD
        version: Not Installed
```
