### ISSUE TITLE
close_fds=True causes cmd.run very slow

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#44758]
### Description of Issue/Question
salt is running very slow on my system.
It takes 25 seconds to run a test.ping.
after some cleanup on the system, I reduced it to 12 seconds, which, is still quite slow.
So I start tracking down the code.
And I found the the following code in /usr/local/lib/python2.7/site-packages/salt/utils/timed_subprocess.py is causing the problem.

```
if self.timeout and not isinstance(self.timeout, (int, float)):
            raise salt.exceptions.TimedProcTimeoutError('Error: timeout {0} must be a number'.format(self.timeout))

        try:
            self.process = subprocess.Popen(args, **kwargs)
        except TypeError:
```
It takes half a second to run subprocess.Popen, which is insane.
But when I run subprocess.Popen in a separate test script, it takes only 70ms

```
time python -c "import subprocess;subprocess.Popen(['/sbin/sysctl', '-n', 'hw.ncpu'])"
24

real	0m0.072s
user	0m0.040s
sys	0m0.039s

```
By adding some debug and tracing code finally I found that it was 'close_fds' in **kargs that caused it to run slow. If I changed close_fds to False, it will run very fast.
```
14:33:11,616 [TRACE   ] ++++ timed_proc 0 ['/bin/kenv', 'smbios.system.product'] kwargs: {'shell': False, 'env': {'LC_NUMERIC': 'C', 'LC_MEASUREMENT': 'C', 'LC_CTYPE': 'C', 'LOGNAME': 'root', 'USER': 'root', 'PROMPT_COMMAND': '__bp_precmd_invoke_cmd; echo -ne "\\033]0;[delish]\\007"; __bp_interactive_mode', 'PATH': '/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin', 'LC_PAPER': 'C', 'HOME': '/root', 'PS1': '\\[\\033[1;5;31m\\]\\u@\\[\\033[1;0;31m\\]\\h\\[\\033[0;0;32m\\] \\w #\\[\\033[0m\\] ', 'PORTSDIR': '/var/poudriere/ports/default', 'LANG': 'en_AU.UTF-8', 'TERM': 'xterm-256color', 'SHELL': '/usr/local/bin/bash', 'TZ': 'Australia/Sydney', 'SHLVL': '1', 'EDITOR': 'nano', 'ITERM_ORIG_PS1': '\\[\\033[1;5;31m\\]\\u@\\[\\033[1;0;31m\\]\\h\\[\\033[0;0;32m\\] \\w #\\[\\033[0m\\] ', 'SUDO_USER': 'tao', 'USERNAME': 'root', 'LC_IDENTIFICATION': 'C', 'LC_ADDRESS': 'C', 'SUDO_UID': '1051', '_': '/usr/local/bin/salt-call', 'SUDO_COMMAND': '/usr/local/bin/bash', 'SUDO_GID': '20', 'LC_MESSAGES': 'C', 'OLDPWD': '/usr/local/lib/python2.7/site-packages/salt', 'LC_TELEPHONE': 'C', 'HISTCONTROL': '', 'LC_MONETARY': 'C', 'PWD': '/usr/local/lib/python2.7/site-packages/salt/utils', 'LC_NAME': 'C', 'MAIL': '/var/mail/root', 'LC_TIME': 'C', 'PAGER': 'more', 'LC_COLLATE': 'C', 'ITERM_PREV_PS1': '\\[\x1b]133;D;$?\x07\x1b]133;A\x07\\]\\[\\033[1;5;31m\\]\\u@\\[\\033[1;0;31m\\]\\h\\[\\033[0;0;32m\\] \\w #\\[\\033[0m\\] \\[\x1b]133;B\x07\\]'}, 'close_fds': True, 'stdout': -1, 'stderr': -2, 'cwd': '/root'}
14:33:12,091 [TRACE   ] ++++ timed_proc 1
```
My question is:
Why would we need to set close_fds to True?
If I set it to False, will it cause any problems?
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.7.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Oct 20 2017, 17:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p1
         system: FreeBSD
        version: Not Installed

**Comment by Ch3LL** [comment]
I'm having a hard time replicating this:

```
root@freebsd11:~ # freebsd-version -u
11.1-RELEASE
root@freebsd11:~ # time salt '*' test.ping
freebsd11:
    True
0.519u 0.324s 0:01.06 78.3%     5+165k 0+0io 0pf+0w
```

```
root@freebsd11:~ # salt --versions-report
Salt Version:                            
           Salt: 2017.7.2                
                                         
Dependency Versions:                     
           cffi: 1.7.0                   
       cherrypy: Not Installed           
       dateutil: 2.6.1                   
      docker-py: Not Installed           
          gitdb: Not Installed           
      gitpython: Not Installed           
          ioflo: Not Installed           
         Jinja2: 2.9.5                   
        libgit2: Not Installed           
        libnacl: Not Installed           
       M2Crypto: Not Installed           
           Mako: Not Installed           
   msgpack-pure: Not Installed           
 msgpack-python: 0.4.7                   
   mysql-python: Not Installed           
      pycparser: 2.10                    
       pycrypto: 2.6.1                   
   pycryptodome: Not Installed           
         pygit2: Not Installed           
         Python: 2.7.14 (default, Nov 16 2017, 01:15:40)                          
   python-gnupg: Not Installed           
         PyYAML: 3.11                    
          PyZMQ: 16.0.2                  
           RAET: Not Installed           
          smmap: Not Installed           
        timelib: Not Installed           
        Tornado: 4.5.2                   
            ZMQ: 4.2.2                   
                                         
System Versions:                         
           dist:                         
         locale: US-ASCII                
        machine: amd64                   
        release: 11.1-RELEASE            
         system: FreeBSD                 
        version: Not Installed           
```

I'm just using the local minion installed on the freebsd master to test. Can you share a sanitized version of your configs? Or anything you see different from my test environment from yours?
