### ISSUE TITLE
external git pillar terrible performance. 

### ISSUE THREAD

**Issue by hunkeelin** [saltstack/salt#44791]
### Description of Issue/Question
Simple changes in pillar structure takes up to 2 minutes to update using pillar.ext_pillar. Where does, simply specifying file_roots with a desinate pillar directory is instant. 
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
external pillar setup in /etc/salt/master

```
fingerprint_hash_type: sha512
worker_threads: 15
auto_accept: False
autosign_timeout: 120
autosign_file: /etc/salt/autosign.conf
file_roots:
    base:
        - /srv/salt/
fileserver_backend:
    - roots
    - git

gitfs_provider: gitpython
gitfs_remotes:
    - root@git:/data/salt-formula.git
gitfs_env_whitelist:
    - base
ext_pillar:
    - git:
        - master root@git:/data/salt-pillar.git
pillar_merge_lists: True
reactor:
    - 'salt/fileserver/gitfs/update':
        - /srv/reactor/update_fileserver.sls
state_verbose: False

```
Inside git:/data/salt-pillar.git/hooks/post-receive
```
#!/bin/bash
# hook trigger
sudo salt-call event.fire_master update salt/fileserver/gitfs/update
```
 
cat /srv/reactor/update_fileserver.sls
```
update_fileserver:
    runner.fileserver.update
```
Simple pillar changes like changing a name or correcting a typo then `git push` will take up to 2 minutes to generate. Where does if I replace:
```
ext_pillar:
    - git:
        - master root@git:/data/salt-pillar.git
```
with 
```
pillar_roots:
    base:
        - /data/pillar
```

and simply do pillar in the traditional way, changes are instant. 

### Versions Report
salt 2017.7.2 (Nitrogen)
