### ISSUE TITLE
salt hangs indefinitely when trying to restart a service

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#44848]
### Description of Issue/Question
When I run 
`salt-call service.restart filebeat`
if hangs forever.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
`FreeBSD 11.1`
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

install filebeat on FreeBSD 11.1
then run
`salt-call service.restart filebeat`
or 
`salt-call service.start filebeat`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Oct 20 2017, 17:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 11.1-RELEASE
         system: FreeBSD
        version: Not Installed
```
