### ISSUE TITLE
mine function network.ip_addrs argument cidr not working

### ISSUE THREAD

**Issue by gurubert** [saltstack/salt#44884]
### Description of Issue/Question

When network.ip_addrs is used as a mine function with an argument cidr to filter for specific IP addresses nothing is returned. Without argument network.ip_addrs returns all IPs for the minions as expected.

### Setup
```
mine_functions:
  office_ip:
    - mine_function: network.ip_addrs
    - cidr: 192.168.48.0/20
```

### Steps to Reproduce Issue
A mine.get does not return anything:

```
# salt files05 mine.get 'files0*' office_ip
files05:
    ----------
```

Calling network.ip_addrs directly works:

```
# salt files0* network.ip_addrs cidr=192.168.48.0/20
files06:
    - 192.168.48.116
files02:
    - 192.168.48.37
files05:
    - 192.168.48.115
files01:
    - 192.168.48.7
files07:
    - 192.168.48.117
files04:
    - 192.168.48.104
files03:
    - 192.168.48.103
```

The mine function without the cidr filter also returns addresses, but too much in my case:

```
mine_functions:
  office_ip:
    - mine_function: network.ip_addrs
```
results in
```
# salt files05 mine.get 'files0*' office_ip
files05:
    ----------
    files01:
        - 192.168.48.7
    files02:
        - 192.168.48.37
    files03:
        - 192.168.48.103
    files04:
        - 192.168.48.104
    files05:
        - 192.168.45.115
        - 192.168.48.115
    files06:
        - 192.168.45.116
        - 192.168.48.116
    files07:
        - 192.168.45.117
        - 192.168.48.117
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-40-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
It should look like this:

```
mine_functions:
  office_ip:
    mine_function: network.ip_addrs
    cidr: 192.168.0.0/24
```

I tested that and it works can you give it a try?

**Comment by gurubert** [comment]
Hi,
it looks like it's working:
```
# salt files05 pillar.items
files05:
    ----------
    mine_functions:
        ----------
        office_ip:
            ----------
            cidr:
                192.168.48.0/20
            mine_function:
                network.ip_addrs
```
but the CIDR filter does not apply:
```
# salt files05 mine.get 'files0*' office_ip
files05:
    ----------
    files01:
        - 192.168.48.7
    files02:
        - 192.168.48.37
    files03:
        - 192.168.48.103
    files04:
        - 192.168.48.104
    files05:
        - 192.168.45.115
        - 192.168.48.115
    files06:
        - 192.168.45.116
        - 192.168.48.116
    files07:
        - 192.168.45.117
        - 192.168.48.117
```
