### ISSUE TITLE
Window's salt-minion crashes when using libcurl and proxy settings.

### ISSUE THREAD

**Issue by badcure** [saltstack/salt#44929]
### Description of Issue/Question
Windows salt-minion crashes with a proxy defined.

Note: I found this issue which MAY be the cause: https://github.com/pycurl/pycurl/issues/395
The version installed is
```
# From Python.exe
>>> print pycurl.version
PycURL/7.43.0 libcurl/7.47.0 OpenSSL/1.0.2e zlib/1.2.8 c-ares/1.10.0 libssh2/1.6.0
```
Note2: https://github.com/saltstack/salt/issues/44924 actually fixed the issue for me, moving to requests.

### Setup
With winrepo configured, add the proxy settings to the Window's salt minion config file
```
proxy_host: proxy.server.example.com
proxy_port: 3128
```
### Steps to Reproduce Issue
Attempting to install a package, the minion dies:
```
# salt 'windows_server' pkg.install urlrewrite
windows_server:
    Minion did not return. [No response]
# salt -C '*' test.ping
windows_server:
    True
```
In the events viewer, it shows the following:
```
Faulting application name: python.exe, version: 0.0.0.0, time stamp: 0x5855a624
Faulting module name: pycurl.pyd, version: 0.0.0.0, time stamp: 0x56b36320
Exception code: 0xc0000005
Fault offset: 0x000000000003ccbc
Faulting process id: 0x16c8
Faulting application start time: 0x01d372a640282936
Faulting application path: c:\salt\bin\python.exe
Faulting module path: c:\salt\bin\lib\site-packages\pycurl.pyd
```
#### Master
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
 ```
#### Windows Minion
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
