### ISSUE TITLE
file.managed doesn't report changes even if there are changes when using file:// as source

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#44936]
### Description of Issue/Question
file.managed doesn't report changes even if there are changes when using local:// as source.  It does do the correct thing on the filesystem, but it reports no changes, even if there are changes.  The source is on nfs if that makes a difference.

### Setup

/users/network/animation/tractorbashUbuntu.sh is on a mounted nfs share.
/opt/pixar/custom/ already exists as a directory

Salt State:
```
move_tractorbashUbuntu.sh:
  file.managed:
    - name: /opt/pixar/custom/tractorbashUbuntu.sh
    - source: file:///users/network/animation/tractorbashUbuntu.sh
```

### Steps to Reproduce Issue

Make A change to the local destination file, or delete it.
Run state.apply <state above>
The destination file is changed appropriately, but salt reports that there were no changes

#### Output
```
----------
          ID: move_tractorbashUbuntu.sh
    Function: file.managed
        Name: /opt/pixar/custom/tractorbashUbuntu.sh
      Result: True
     Comment: File /opt/pixar/custom/tractorbashUbuntu.sh is in the correct state
     Started: 16:49:50.308230
    Duration: 2.255 ms
     Changes:   
----------
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-40-generic
         system: Linux
        version: Ubuntu 16.04 xenial
