### ISSUE TITLE
Windows Registry module/state hangs forever.

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#44967]
### Description of Issue/Question
When setting some values in the Windows registry on Windows 10, both the CLI and State modules hang forever with no return. When using a state, this prevents future states from running on the minion unless the original state is forcibly killed or `concurrent` is set to true.

### Setup
screensaver.sls:
```
salt MINION reg.set_value HKEY_LOCAL_MACHINE 'SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System' 'InactivityTimeoutSecs' vdata=0 vtype=REG_DWORD
```
or
```
set_inactivity_limit:
  lgpo.set:
     - computer_policy:
         "Interactive logon: Machine inactivity limit": {{ sstimeout }}
```
or
```
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System:
  reg.present:
    - vname: 'InactivityTimeoutSecs'
    - vtype: REG_DWORD
    - vdata: {{ sstimeout }}
```
All of these set the same registry key (this key is present only on Windows 10). The execution actually succeeds -- the key is set correctly -- but salt never returns. On the CLI, it just hangs there forever. In a state execution, the entire state execution waits indefinitely, never moving on to other instructions and never returning a result.

### Steps to Reproduce Issue
Run any of the operations above, then go make coffee, wait for the kids to graduate university, grow old with your spouse, die peacefully in bed at the age of 90, and leave a secret organization of warrior monks behind you to wait out the centuries, hoping to one day see the result. Ultimately, fail.

### Versions Report
minion:
```
    Salt Version:
               Salt: 2017.7.1
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.2
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.16299  Multiprocessor Free
```

master:
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
