### ISSUE TITLE
Firewalld state cause horrid performance during saltrun. 

### ISSUE THREAD

**Issue by hunkeelin** [saltstack/salt#44979]
Some of my formula will have firewalld rules in it like the following:

```
dokuwiki_fw:
    firewalld.service:
        - name: dokuwiki
        - ports:
            - 8002/tcp

dokuwiki_fw_rule:
    firewalld.present:
        - name: public
        - prune_services: False
        - services:
            - dokuwiki
```

Some subset of my nodes will have serveral firewalld states to run during an highstate run. Upon inspecting `debug` I realize the firewalld module is consuming a lot of time. It is inefficient. 

E.G

consider the following formula `test`

```
doku_default_pw:
    file.managed:
        - name: /tmp/test
        - source: salt://test/testfile

test_fw:
    firewalld.service:
        - name: test
        - ports:
            - 8002/tcp

dokuwiki_fw_rule:
    firewalld.present:
        - name: public
        - prune_services: False
        - services:
            - test
```

When I run `salt-call state.apply test` on the minion it takes an average of 10s for a no change occurrence. 

```
local:

Summary for local
------------
Succeeded: 9
Failed:    0
------------
Total states run:     9
Total run time:  12.718 s

```

When I commented out the firewall lines. it takes significantly less time to run the state. 

```
local:

Summary for local
------------
Succeeded: 7
Failed:    0
------------
Total states run:     7
Total run time:   1.577 s

```
