### ISSUE TITLE
Handling state failure programmatically?

### ISSUE THREAD

**Issue by abh23** [saltstack/salt#45035]
### Description of Issue/Question
I have few salt-states in which multiple things are handled like **pkg.installed, file.managed, cmd.run**, etc. 
These salt-states are executed using command: `salt '<name>' state.apply <state-name>`

I have a requirement where I want to take actions based on salt ret-code or some mechanism which is error proof and for that I need to detect failures from salt master on intended minion. 
Also, if a particular salt-state is taking a lot of time, what are the options that I have to either kill or restart or check existing salt-state.

Need to do it using salt client and runner python module. Any ideas are highly appreciated.

### Setup
```
nginx:
    pkg.installed: 
        - skip_verify: True
    service.running:
        - require:
            - pkg: nginx

sysstat:
    pkg.installed:
        - skip_verify: True
    cmd.run:
        - name: |
            sed -i -e 's/^ENABLED.*$/ENABLED="true"/g' /etc/default/sysstat
            service systat restart

lxml:
  archive.extracted:
    - name: /opt/
    - source: http://xyz.com/lxml-3.3.1.tar.gz
    - source_hash: md5=LXML_HASH
    - options: x
    - archive_format: tar
    - if_missing: /opt/lxml-3.3.1
  cmd.wait:
    - name: |
        cd /opt/lxml-3.3.1
        python setup.py install
    - watch:
       - archive : lxml

/etc/nginx/nginx.conf:
  file.managed:
    - source: salt://nginx/nginx.conf
    - user: root
    - group: root
    - mode: 755
net.core.rmem_default:
  sysctl.present:
    - value: 4194304
```
Till now I have explored this approach:
1) I can check currently running state on minion and decide to kill or restart it based on time it has already taken. But depending on time calls for its own set of problems. What if the minion is over-loaded or binary transfers are slow, etc. ?
