### ISSUE TITLE
There was an error destroying machines: The specified resource does not exist.

### ISSUE THREAD

**Issue by SJern** [saltstack/salt#45053]
Hello, I'm encountering an issue with destroying Azure VMs. Any help would be greatly appreciated!

### Description of Issue/Question
```
foo@master:/$ sudo salt-cloud -d testnode
......
......
[ERROR   ] There was an error destroying machines: The specified resource does not exist.
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:3uf64ke6-001e-0087-4e11-945b48593000
Time:2017-12-16T02:01:56.7557926Z</Message></Error>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 214, in run
    ret = mapper.destroy(names, cached=True)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1033, in destroy
    ret = self.clouds[fun](name)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1322, in destroy
    call='function'
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1747, in delete_blob
    storageservice.delete_blob(kwargs['container'], kwargs['blob'])
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blob/baseblobservice.py", line 3118, in delete_blob
    self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 266, in _perform_request
    raise ex
AzureMissingResourceHttpError: The specified resource does not exist.
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:3uf64ke6-001e-0087-4e11-945b48593000
Time:2017-12-16T02:01:56.7557926Z</Message></Error>
```
### Setup
provider:
```
azurearm-us:
  - driver: azurearm
    subscription_id: ********************************
    tenant: ****************************************
    client_id: ***************************************
    secret: ***********
    ssh_username: ********
    ssh_password: *******************

    location: northeurope
    resource_group: myresource-group
    network_resource_group: myresource-group
    network: DefaultVnet
    subnet: DefaultSubnet
    public_ip: True

    storage_account: defaultstdsa
    cleanup_disks: True
    cleanup_vhds: True
    cleanup_data_disks: True
    cleanup_interfaces: True

    grains:
      region: test
```
profile:
```
test_azurearm:
  provider: azurearm-us
  image: Canonical|UbuntuServer|16.04-LTS|latest
  size: Standard_DS2_v2
  os_disk_size_gb: 38
  minion:
    master: 47.0.0.0
    grains:
      role: test
```
### Steps to Reproduce Issue
```
foo@master:/$ sudo salt-cloud -d testnode
```
### Versions Report
```
Salt Version:
           Salt: 2017.7.0-n/a-c2c3048

Dependency Versions:
           cffi: 1.11.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.11.0-1014-azure
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
Could possibly be a duplicate of https://github.com/saltstack/salt/issues/41299

Which has a fix here: https://github.com/saltstack/salt/pull/41346

If you try the fix does it resolve the issue?

**Comment by SJern** [comment]
Hmmm, the fix doesn't resolve my issue. I'm getting the same error.

**Comment by SJern** [comment]
Just to follow up. @shengis in [#41299](https://github.com/saltstack/salt/issues/41299) was **not** getting the good `storageaccount` in the function **delete_blob** of **/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py**.

However, I'm getting the correct `storageaccount` and correct `container` and correct `blob`.

So our issues seem to be different.

**Comment by shengis** [comment]
Do you have more than one salt-cloud **provider** set for the same **resource group** ?

**Comment by SJern** [comment]
Hey @shengis, yes, there are 2, but one just extends the other. They both use the exact same `storageaccount`, so it doesn't smell like a multi-provider issue. Your issue was a wrong `storageaccount`, was it? Thanks =)

**Comment by shengis** [comment]
Azure is organized by resource group, if you ask the list of VMs to the **azurearm** driver (list_nodes), he will return them associated with each providers corresponding to the resource group of the VM.

in **salt/cloud/__init__.py**

```
  985         parallel_data = []
  986         for alias, drivers in six.iteritems(matching):
  987             for driver, vms in six.iteritems(drivers):
  988                 for name in vms:
  989                     if name in names:
  990                         vms_to_destroy.add((alias, driver, name))
  991                         if self.opts['parallel']:
  992                             parallel_data.append({
  993                                 'opts': self.opts,
  994                                 'name': name,
  995                                 'alias': alias,
  996                                 'driver': driver,
  997                             })
```

**vms_to_destroy** is a liste of 3-tuple (alias, driver, name) that is built to contains the VMs to destroy.

If you have two **providers** with the same **resource group**, the list will contains two tuples instead of one, one for each provider.

```
1036             for alias, driver, name in vms_to_destroy:
1037                 fun = '{0}.destroy'.format(driver)
1038                 with context.func_globals_inject(
1039                     self.clouds[fun],
1040                     __active_provider_name__=':'.join([alias, driver])
1041                 ):
1042                     ret = self.clouds[fun](name)
```

The VM will be delete at the first pass, but the second pass will raise an error as the VM (and storage) doesn't exists anymore.

It's not easy for azurearm driver to know the "good" provider the VM was created with, as it's not an information stored.

As a solution, it's better to move the parameters to profiles, leaving the bare minimum to providers, and use only one provider by resource group. The profiles can also be extended.

in providers

```
azure-us1:
  driver: azurearm
  subscription_id: ***
  tenant: ***
  client_id: ***
  secret: ***
  location: westus
  resource_group: infra-us1
  network_resource_group: infra-us1
  storage_account: ***
  storage_key: ***

  cleanup_disks: True
  cleanup_vhds: True
  cleanup_data_disks: True
  cleanup_interfaces: True

  minion:
    master: 10.1.1.4
    hash_type: sha256

  grains:
    provider: azure
    region: westus
```

in profiles :

```
azure-us1:
  provider: azure-us1
  image: Canonical|UbuntuServer|16.04-LTS|latest
  ssh_username: ***
  ssh_password: ***
  network: infraus1VNET
  dns_servers:
    - 10.1.1.4
  public_ip: True
  script: bootstrap-salt.sh
  script_args: stable latest
  sync_after_install: grains

azure-us1-controller:
  extends: azure-us1
  availability_set: ManagersAS
  load_balancer: ManagersLB
  backend_pool: ManagersLBBAPool
  size: Standard_DS1_v2
  subnet: infraus1Managers
  minion:
    master: 10.1.1.4
    grains:
      region: westus
      roles: k8s-controller
```
