### ISSUE TITLE
salt.states.firewalld - Support for icmp-block-inversion zone configuration element

### ISSUE THREAD

**Issue by ThomasSullivanSubscribe** [saltstack/salt#45084]
### Description of Issue/Question
firewalld has the firewall zone configuration element "icmp-block-inversion" that inverts the icmp block handling.  Currently one cannot set this configuration element in salt.states.firewalld

### Setup
Generic Setup.  This is to support a feature within the firewalld environment.  An example firewalld output where this configuration element has been enabled:

```
myZone (active)
  target: DROP
  icmp-block-inversion: yes
  interfaces: 
  sources: 1.1.1.1/32 2.2.2.2/32
  services: https ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  sourceports: 
  icmp-blocks: echo-request
  rich rules: 
```

### Steps to Reproduce Issue
Feature request.  When added, I would imagine it would be very similar to how one can enable masquerade.  The above example would need the following configuration line once this feature is implemented:

```
myZone:
  firewalld.present:
    - name: myZone
    - icmp_block_inversion: True
```

### Versions Report
No difference between minion and master versions:
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.8 (default, Jun  6 2017, 13:22:42)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
