### ISSUE TITLE
iptables question

### ISSUE THREAD

**Issue by itskenny0** [saltstack/salt#45109]
Hello!

I'm deploying the following iptables state via salt:
```
masquerade:
   iptables.append:
     - table: nat
     - chain: POSTROUTING
     - j: MASQUERADE
```

This works great, but I would like to remove the loopback interface from this rule.
Normally, I would use:
`iptables -A POSTROUTING ! -o lo -j MASQUERADE`

Could you point me to how I can implement this in a state?
Thank you!

**Comment by Ch3LL** [comment]
just glancing at the code I think you should be able to do it by adding `- of: ! lo`. I can track it down more if that doesn't work.

**Comment by itskenny0** [comment]
Thank you, that got me in the right direction!
This is what I ended up with:
```
masquerade:
   iptables.append:
     - table: nat
     - chain: POSTROUTING
     - o: '! lo'
     - j: MASQUERADE
```
