### ISSUE TITLE
salt-cloud no longer picking up master setting from provider file

### ISSUE THREAD

**Issue by wes-novack** [saltstack/salt#45125]
### Description of Issue/Question
With salt-master and salt-cloud 2017.7.2, salt-cloud is no longer picking up the config for minion:master:dns  defined in a salt-cloud provider file. This previously worked in salt 2016.11.X

### Setup
provider.conf file
```
myprovider:
  minion:
    master: mymaster.dns.com
  ssh_interface: private_ips
  id: 'redacted'
  key: 'redacted'
  private_key: /etc/salt/mykey.pem
  keyname: mykey
  location: us-west-2
  availability_zone: us-west-2a
  ssh_username:
    - ubuntu
  driver: ec2
```
profile.conf file
```
myprofile:
  ssh_interface: private_ips
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 30
      Ebs.VolumeType: gp2
  provider: myprovider
  image: ami-myamiid
  script_args: stable 2017.7.2
  size: t2.micro
  ssh_username: ubuntu
  network_interfaces:
    - DeviceIndex: 0
      SubnetId: subnet-mysubnetid
      SecurityGroupId:
        - sg-mysgid
  minion:
    grains:
      env: myenv
      roles:
        - myrole
      team: myteam
  tag:
    env: myenv
    org: myorg
    roles: myrole
    team: myteam
```

### Steps to Reproduce Issue
salt-cloud -P myprofile myprofile-host-1
`[WARNING ] There's no master defined on the 'myprofile-host-1' VM settings. `

Minion does not connect to master or receive the appropriate master setting after salt-cloud spins it up and bootstraps it.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1041-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```
### Workaround
If I use the salt-cloud root config file located at `/etc/salt/cloud` instead of the provider file, then it works fine.
```
minion:
  master: mymaster.dns.com

```
