### ISSUE TITLE
Python crashes when Salt commands are run in a directory other than C:\salt\bin on some Windows servers

### ISSUE THREAD

**Issue by phsteve** [saltstack/salt#45138]
### Description of Issue/Question

Note: see my comment below about what directory you have to be in (`C:\salt\bin`) when you execute `salt-call` or `salt-minion` (and possibly other Salt commands). That might be the root cause instead of a problem with the `file.managed` state as I originally thought, but I'm not certain.

When I execute `salt-call.bat state.highstate` in Powershell, Python crashes during a `file.managed` state. Curiously the highstate succeeds when run via `salt minion_name state.highstate` on the master.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
C:\salt\conf\minion:
  file.managed:
    - source: salt://salt-minion/files/minion
    - user: Administrators
    - template: jinja
    - onchanges_in:
      - cmd: Restart Salt minion
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

I can also trigger the crash directly in the Python interpreter:

```
>>> import salt.modules.win_file
>>> salt.modules.win_file.user_to_uid('Administrators')
```

No traceback is printed in the interpreter (or in the logs for the above mentioned highstate), but the following dialog box pops up:

![image](https://user-images.githubusercontent.com/1628311/34284893-45066c7a-e6a3-11e7-88bd-def7772a5c74.png)

The debug-level logs have `[DEBUG   ] LazyLoaded file.user_to_uid` as the last line before the crash.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

The master is running 2017.7.2.

Here's the output on the minion:
```
PS C:\Users\skatz> salt-call --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600 SP0 Multiprocessor Free
```
