### ISSUE TITLE
salt state mount.mounted remounts cephfs every time when setting secretfile=path/to/secretfile option

### ISSUE THREAD

**Issue by etfeet** [saltstack/salt#45136]
### Description of Issue/Question
I'm using salt to mount a ceph luminous cephfs mount point and whenever I use the secretfile=my_ceph_auth_secret_file the mount state thinks the secret file option is changing every time the state runs.

### Setup
```
#mount_cephfs.sls:

...
/etc/ceph/cephfs.secret:
  file.managed:
  - user: root
  - group: root
  - mode: 644
  - contents: |
      {{ keyring.key  }}
  - require:
    - file: /etc/ceph/ceph.conf

...
mount_cephfs:
  mount.mounted:
  - mount: True
  - mkmnt: True
  - persist: True
  - name: /mnt/cephfs
  - device: "{%- for member in common.members %}{{ member.host }}{% if not loop.last %},{% endif %}{%- endfor %}:/"
  - fstype: ceph
  - opts:
      - name=cephfs
      - secretfile=/etc/ceph/cephfs.secret
      - _netdev
  - require:
    - /etc/ceph/cephfs.secret
```

### Steps to Reproduce Issue
use the secretfile= option with a cephfs mount.
```
fstab entry:
192.168.1.10,192.168.1.11,192.168.1.12:/		/mnt/cephfs	ceph	name=cephfs,secretfile=/etc/ceph/cephfs.secret,_netdev	0 0
mtab entry:
192.168.1.10,192.168.1.11,192.168.1.12:/	/mnt/cephfs ceph rw,relatime,name=cephfs,secret=<hidden>,acl 0 0
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.10.0-42-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by gtmanfred** [comment]
File systems like ceph and gluster and nfs are the reason that the 

`device_name_regex` option and a couple of the other ones were added. 

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.mount.html#salt.states.mount.mounted

If you set it to this does it work?

```
mount_cephfs:
  mount.mounted:
  - mount: True
  - mkmnt: True
  - persist: True
  - name: /mnt/cephfs
  - device: "{{common.members|join(',')}}:/"
  - device_name_regex:
    - "{{common.memebers|join(',')}}:/"
  - fstype: ceph
  - opts:
      - name=cephfs
      - secretfile=/etc/ceph/cephfs.secret
      - _netdev
  - require:
    - /etc/ceph/cephfs.secret
```
