### ISSUE TITLE
winrepo: broken idempotency

### ISSUE THREAD

**Issue by guskovd** [saltstack/salt#45157]
init.sls:
```yaml
update_git_repos:
  module.run:
    - name: winrepo.update_git_repos

winrepo:
  winrepo.genrepo

refresh:
  module.run:
    - name: pkg.refresh_db

7zip:
  pkg.installed:
  - name: 7zip
```

after the first call of
```powershell
salt-call.bat --local state.highstate 
```
I receive:
```powershell
Unable to locate package 7zip
```
--
after the second call - everything is fine.
