### ISSUE TITLE
featurerequest: sdb module sqlcipher

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#45156]
### Description of Issue/Question
Storing secrets within salt pillar with gpg keys is hard, while using the sdb should make it easier.
Preferable something that should be secure. 

Could it be possible to add sdb module that uses pysqlcipher to create an sqlcipher.db

pypi: https://pypi.python.org/pypi/pysqlcipher
documentation: https://github.com/leapcode/pysqlcipher/
examples: http://charlesleifer.com/blog/encrypted-sqlite-databases-with-python-and-sqlcipher/

### Setup/configuration:
```
mysqlcipher:
  driver: pysqlcipher
  database: /tmp/sdb.db
  table: sdb
  create_table: True
```
