### ISSUE TITLE
GitFS backend does not work as documented with per-remote environments

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#45197]
### Description of Issue/Question

Examples in "[Git Fileserver Backend Walkthrough](https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#per-saltenv-configuration-parameters)" seems to hint at that multiple environments should be possible.

However, defining multiple environments with _saltenv_ in _gitfs_remotes_ fails to produce any other environment except 'base'.

### Setup

```
gitfs_provider: pygit2
gitfs_remotes:
  - file:///some/directory/with/a/git/repository/in/it:
    - mountpoint: salt://
    - name: 'root'
  - file:///some/directory/with/a/git/repository/in/it:
    - saltenv:
      - foo:
        - mountpoint: salt://foo
        - name: 'foo'
```

### Steps to Reproduce Issue
1. Clone a git repository to /some/directory/with/a/git/repository/in/it.
2. Put the above configuration into a suitable file (e.g. /etc/salt/master.d/files.conf).
3. Start SaltStack master.
4. Run `salt-run fileserver.envs`.

I'd expect `salt-run fileserver.envs` to produce a list of two environments, namely 'base' and 'foo'. But, that is not the case: only 'base' is returned.

Running `salt-call cp.list_master` produces a list of files (assuming the git repository contains any), yet `salt call cp.list_master saltenv=foo` yields nothing; so, it seems that the 'foo' environment in the example configuration snippet above doesn't work as documentation states it should.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: 1.9.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-103-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I think the problem is that since it is an ordered *Dictionary*, when the lookup for the file:// git repository happens, it finds the first one and exits.

```
gitfs_provider: pygit2
gitfs_remotes:
  - file:///some/directory/with/a/git/repository/in/it:
    - saltenv:
      - foo:
        - mountpoint: salt://foo
        - name: 'foo'
      - base:
        - mountpoint: salt://
        - name: 'root'
```

You can either do something like this, so that all the configuration is on the first directory, or you can separate them out into different git repositories.

Thanks,
Daniel

**Comment by samilaine** [comment]
The results are, unfortunately, exactly same when specified like that. Only the base environment is being taken in from:

```
gitfs_provider: pygit2
gitfs_remotes:
  - file:///opt/kola/salt:
    - saltenv:
      - base:
        - mountpoint: salt://
        - name: 'root'
      - foo:
        - mountpoint: salt://foo
        - name: 'foo'
```

Again in this case too I'd expect to see a list of *two* results from `salt-run fileserver.envs` plus `salt-call cp.list_master` and `salt-call cp.list_master saltenv=foo` to return the same list of files (with the exception of the prefix, of course).

**Comment by gtmanfred** [comment]
Does your git repository have a second branch for the second environment?

GitFS uses branches to define environments, and it looks like you can only have one environment per branch.

All that this `saltenv` stuff does is allow you to rename environments and add extra configurations for them.  If you don't have a branch called `foo` then the foo environment won't exist.  Alternatively, you could tell `foo` to reference the `master` branch, but then your `base` branch will disappear because it has been renamed to `foo`.

**Comment by samilaine** [comment]
No, in this particular case there were was a single branch in a single repository.

Creating separate branches for each environment does the trick as explained, thanks for that.

However, I think that the documentation could benefit from some rewriting. Currently it leads quite easily a reader to make a few false assumptions, I think.

**Comment by gtmanfred** [comment]
If you wouldn't mind submitting a PR for the documentation that makes it more understandable.

As you can see, it is can be difficult to write documentation that everyone can understand when you are so familiar with the underlying code.

Thanks,
Daniel

**Comment by gfyrag** [comment]
@gtmanfred This behavior is recent?
I have a configuration with this kind of config (same branch map on differents env) and until today (upgrade from debian jessie to stretch), it was working as expected.

**Comment by terminalmage** [comment]
@samilaine Your example configuration above is not using the documented syntax. You did not specify a `ref` for it to point to, so it is likely just being ignored (hence only `base` showing up when listing the envs).

The `name` line is being ignored because it is not a recognized parameter for per-saltenv configuration.

This would be the correct usage, based on your example (and assuming the default base branch of `master`):

```yaml
gitfs_provider: pygit2
gitfs_remotes:
  - file:///some/directory/with/a/git/repository/in/it:
    - mountpoint: salt://
    - name: 'root'
  - file:///some/directory/with/a/git/repository/in/it:
    - saltenv:
      - foo:
        - mountpoint: salt://foo
        - ref: master
```
