### ISSUE TITLE
Requisite matching not matching state based on -name

### ISSUE THREAD

**Issue by alext9** [saltstack/salt#45283]
### Description of Issue/Question
I am trying to restart a service when a file changes. I am using watch_in on a file.managed state and am expecting to match the `- name: nginx` of my `service.running` state. This behavior is mentioned in the [requisite matching](https://docs.saltstack.com/en/latest/ref/states/requisites.html#requisite-matching) section of the documentation.

### Setup
```
nginx:
  pkg.installed

nginx_service:
  service.running:
    - name: nginx
    - enable: True
    - watch:
      - pkg: nginx

/etc/nginx/sites-available/saltstack_managed_sites:
  file.managed:
    - context:
        sites: {{ salt['pillar.get']('nginx:sites') }}
    - source: salt://nginx/site_template
    - template: jinja
    - require:
      - pkg: 'nginx'
    - watch_in:
      - service: nginx
```
When the `saltstack_managed_sites` file is changed, the nginx service is not restarted.

Changing the watch_in to use the state identifier fixes the issue and causes nginx to be restarted when `saltstack_managed_sites` changes:
```
    - watch_in:
      - service: nginx_service
```

### Versions Report

minion version report:
```Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 2.7.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

master version report:
```Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.23.4
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.23.3
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.10
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.10```

**Comment by garethgreenaway** [comment]
@alext9 Thanks for the report.  The reason the first example does not work but the second example does work is because the requisite is looking for the name of the state, not the name of the service.
If you update the state and combine the `pkg` and `service` pieces:
```
nginx:
  pkg.installed: []
  service.running:
    - enable: True
    - watch:
      - pkg: nginx
```

Then you'll be able to reference the service with just `nginx`.
