### ISSUE TITLE
unable to pass "-l debug" to job_args

### ISSUE THREAD

**Issue by mwtzzz** [saltstack/salt#45286]
I'm trying to turn on debugging in a scheduled state.sls function, but I keep getting an error:

>salt.template [ERROR   ][21530] Template was specified incorrectly: False

My basic config (which works) looks like this:
```
git-pull-master:
  schedule.present:
    - function: state.sls
    - job_args:
       - cluster.salt-master.sre-salt-git-repo
    - seconds: 20
    - maxrunning: 1
    - persist: true
    - return_job: true
    - enabled: true
```
I've tried the following different ways to pass `-l debug` to job_args, none of them worked, they all throw that template error:
```
    - job_args:
       - -l debug cluster.salt-master.sre-salt-git-repo

    - job_args:
       - "-l debug cluster.salt-master.sre-salt-git-repo"

    - job_args:
       - "-l debug"
       - cluster.salt-master.sre-salt-git-repo
```

I'm running salt-2017.7.0 on linux.
