### ISSUE TITLE
RFE: master file server addition information e.g. ETag

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#45314]
### Description of Issue/Question
Can the backed be updated so instead of just returning simple information i.e. filename it always returns a dict
Now looks like
```
cp.list_master
- file1
- file2
- dir1\file3
```

Future look, however every command should receive a dict for each file name, may not use the info
```
cp.list_master detail=True
'file1':
   Time: seconds since 1970
   ETag: string
   Size: 
   Type: f(ile) or d(irectory)
'file2':
   Time: 7483278389
   ETag: jfds8jlfsjd8ereteghyrbvvdffeeejfljdl
   Size: 7184
   Type: f
'dir':
   Time: seconds since 1970
   ETag: <Maybe a checksum of all the filenames and modification str times>
   Size: <items in directory> or None
   Type: d
'dir1\file3':
   Time: 6367
   ETag: rfejlwjkldggdgfddgthdvhyhyytrfwe
   Size: 9373
   Type: f 
``` 

ETag its up to the client to record it so it knows if the file has change or not. The client does not care how it was generated and does not need to generate/calculate it itself. However the server must change it if the file changes on the server. ETag could be a commit tag or something else from git.

It's important all masters give out the same ETag for the same file. An Etag which uses inode number would fail as this would be different on different masters.

+1 if you like the idea.

The next stage would be for the clients to use this information as part of caching.
