### ISSUE TITLE
Windows Master - Oxygen Branch -  Conflicting ID Error

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#45328]
Running `pkg.latest_version` command on windows master gives `Conflicting ID Error` on Oxygen branch.
See this on both py2 and py3.

```
[ERROR   ] Failed to compile 'salt-winrepo-ng\salt-minion-py2.sls': Conflicting ID 'install_flags'
[ERROR   ] Failed to compile 'salt-winrepo-ng\salt-minion-py3.sls': Conflicting ID 'install_flags'
```

### Setup
Install WIndows Master and run command.

### Steps to Reproduce Issue
```
PS C:\> salt-call --local pkg.latest_version chrome
[ERROR   ] Failed to compile 'salt-winrepo-ng\salt-minion-py2.sls': Conflicting ID 'install_flags'
[ERROR   ] Failed to compile 'salt-winrepo-ng\salt-minion-py3.sls': Conflicting ID 'install_flags'
```

### Versions Report
```
    Salt Version:
               Salt: 2018.2.0-79-g0343728

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: Not Installed
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.7
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```
