### ISSUE TITLE
Windows Master - Oxygen branch py3 - file.comment error.

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#45329]
On Windows Master on oxygen branch, py3 setup, trying to comment out a line using `file.comment` fails with this error:
```
    Comment: An exception occurred in this state: Traceback (most recent call last):
               File "c:\salt\bin\lib\site-packages\salt\state.py", line 1934, in call
                 **cdata['kwargs'])
               File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1822, in wrapper
                 return f(*args, **kwargs)
               File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 4477, in comment
                 __salt__['file.comment_line'](name, regex, char, True, backup)
               File "c:\salt\bin\lib\site-packages\salt\modules\file.py", line 1530, in comment_line
                 w_file.write(wline)
             TypeError: write() argument must be str, not bytes
```

### Setup
Set up Windows Master with py3.

Have a file with the text `Only a test`
Havs a state file with:
```
file_comment:
  file.comment:
    - name: c:/test/test
    - regex: '^Only'
```

### Steps to Reproduce Issue
```
PS C:\> salt * state.sls files
winpy3:
----------
          ID: file_comment
    Function: file.comment
        Name: c:/test/test
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1934, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1822, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 4477, in comment
                  __salt__['file.comment_line'](name, regex, char, True, backup)
                File "c:\salt\bin\lib\site-packages\salt\modules\file.py", line 1530, in comment_line
                  w_file.write(wline)
              TypeError: write() argument must be str, not bytes
     Started: 11:38:39.110452
    Duration: 77.764 ms
     Changes:

Summary for winpy3
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  77.764 ms
ERROR: Minions returned with non-zero exit code
PS C:\>
```

### Versions Report
```
    Salt Version:
               Salt: 2018.2.0-79-g0343728

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: Not Installed
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.7
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```
