### ISSUE TITLE
freebsd minion crash with latest py-cffi

### ISSUE THREAD

**Issue by rhavenn** [saltstack/salt#45341]
FreeBSD upgraded the py-cffi port from 1.7.0 to 1.11.2 and now my minions are crashing. I don't know if this is a bug in cffi or if something changed in what salt is expecting / pushing to cffi.

I manually rolled my package building machine's py-cffi port back to py-cffi 1.10.0 and now my minion works fine with 0 other changes.

There is a reference to an issue on Windows minions here: https://github.com/saltstack/salt/pull/45245

with cffi, but wanted to let you know it happens elsewhere as well.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.4 (default, Dec 23 2017, 09:14:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p4
         system: FreeBSD
        version: Not Installed
```

trace log shows:
```
2018-01-09 01:11:49,293 [salt.minion                                                     ][DEBUG   ][45058] minion return: {'success': False, 'return': 'The minion function caused an exception: AttributeError: cffi library \'_constant_time\' has no function, constant or global variable named \'__loader__\'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/salt/minion.py", line 1470, in _thread_return\n    return_data = executor.execute()\n  File "/usr/local/lib/python3.6/site-packages/salt/executors/direct_call.py", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File "/usr/local/lib/python3.6/site-packages/salt/modules/state.py", line 593, in apply_\n    return highstate(**kwargs)\n  File "/usr/local/lib/python3.6/site-packages/salt/modules/state.py", line 892, in highstate\n    orchestration_jid=orchestration_jid)\n  File "/usr/local/lib/python3.6/site-packages/salt/state.py", line 3661, in call_highstate\n    self.load_dynamic(matches)\n  File "/usr/local/lib/python3.6/site-packages/salt/state.py", line 3181, in load_dynamic\n    self.state.module_refresh()\n  File "/usr/local/lib/python3.6/site-packages/salt/state.py", line 918, in module_refresh\n    reload_module(site)\n  File "/usr/local/lib/python3.6/importlib/__init__.py", line 166, in reload\n    _bootstrap._exec(spec, module)\n  File "<frozen importlib._bootstrap>", line 618, in _exec\n  File "<frozen importlib._bootstrap_external>", line 678, in exec_module\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n  File "/usr/local/lib/python3.6/site.py", line 544, in <module>\n    main()\n  File "/usr/local/lib/python3.6/site.py", line 525, in main\n    abs_paths()\n  File "/usr/local/lib/python3.6/site.py", line 102, in abs_paths\n    if (getattr(getattr(m, \'__loader__\', None), \'__module__\', None) not in\nSystemError: <built-in function getattr> returned a result with an error set\n', 'out': 'nested', 'jid': '20180109011148773780', 'fun': 'state.apply', 'fun_args': []}

```
