### ISSUE TITLE
Missing documentation for module.run

### ISSUE THREAD

**Issue by rhoths** [saltstack/salt#45360]
The documentation for the [module state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html) appears to be at least partially broken. The entire function documentation for the `module.run` function is missing. There are some examples and basic info for the function in the module documentation, but the function signature and function documentation is absent.

**Comment by V3XATI0N** [comment]
Ran into this earlier. The documentation is sparse, and what little there is is apparently wrong.

Trying to run a `win_wua.get` call, the documentation would lead you to believe you should put
```
awesome_state_id:
  module.run:
    win_wua.get:
      - name: KB12345678
```
but doing it that way causes it to spew out `awesome_state_id is not formed as a list`. Huh?

Actually, you have to do this:
```
awesome_state_id:
  module.run:
    - name: win_wua.get
    - m_names:
      - KB12345678
```

which doesn't look anything like the documentation. so... yeah.

**Comment by rhoths** [comment]
@V3XATI0N The module usage (and deprecation warnings I was getting) is largely what drove me to asking about the documentation in the IRC channel. @gtmanfred helpfully pointed out that the [2017.7.0 release notes](https://docs.saltstack.com/en/latest/topics/releases/2017.7.0.html) contain information on the "new" `module.run` syntax and how to enable it. It looks like your first example would run if you enabled the new behavior with the following in your minion config:

    use_superseded:
      - module.run

**Comment by gtmanfred** [comment]
It should also be updated it is this

```
awesome_state_id:
  module.run:
    - win_wua.get:
      - name: KB12345678
```
