### ISSUE TITLE
block.replace should have an option to remove the whole block

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#45370]
### Description of Issue/Question

In my use case (one year ago) a part in /etc/sudoers was added.

Time has passed and this part should get removed in the future.

I found this way to remove the block in my case:

```
remove_django__etc_sudoers_{{ system_name }}:
  file.replace:
    - name: /etc/sudoers
    - pattern: "# START etc_sudoers_{{ system_name }} -DO-NOT-EDIT-.*?# END etc_sudoers_{{ system_name }} --"
    - flags: ['MULTILINE', 'DOTALL']
    - repl: ''
    - ignore_if_missing: True

```
See: https://serverfault.com/a/891222/90324

I think above solution is way to complicated.

It would be very nice if the blockreplace state had a way to remove itself.

### Versions Report
Current - AFAIK this is a feature request.
