### ISSUE TITLE
Installing variant of mac port fails if no version is provided

### ISSUE THREAD

**Issue by KaiSzuttor** [saltstack/salt#45413]
### Description of Issue/Question
Calling ``sudo salt-call pkg.install boost variant='+openmpi'``
ends up with
```
Error running 'pkg.install': Problem encountered installing package(s). Additional info follows:

changes:
    ----------
errors:
    Command Failed: ['port', 'install', 'boost+openmpi']
    Return Code: 1
    Output:
    Error: Error: Port boost+openmpi not found
```
while running ``sudo salt-call pkg.install boost version='1.65.1_1' variant='+openmpi'``
ends up with
```
local:
    ----------
    boost:
        ----------
        new:
            1.65.1_1+no_single+no_static+openmpi+python27
        old:
            1.65.1_1+no_single+no_static+python27
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
See above.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Sep 27 2017, 12:15:00)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 17.3.0
         system: Darwin
        version: 10.13.2 x86_64
```
