### ISSUE TITLE
command line state-output options has no affect

### ISSUE THREAD

**Issue by rhavenn** [saltstack/salt#45418]
I found a few references that this has been fixed over the years, but perhaps the issue got re-introduced. When I add `--state-output=full` to the `salt` command it doesn't seem to do anything. My `master` config file has `state_output: changes` . I've run the following commands:
```
salt '*' state.highstate --state-output=full
salt '*' state.apply --state-output=full
```
and both just list my 3 minions and the summary info. `full` output works fine when I have it set explicitly in the master or let it be the default.

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.3
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.4 (default, Dec 23 2017, 09:14:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p4
         system: FreeBSD
        version: Not Installed

```
