### ISSUE TITLE
changing git_pillar with -name and using same -name not updating repo.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#45422]
### Description of Issue/Question
Starting with a git_pillar repo with one - name setting and then changing the repo but not the - name can cause different erroneous situations.  

### Setup
```
ext_pillar:
  - git:
    - master https://github.com/whytewolf/test_repo1.git:
      - root: pillar/base
      - name: base
      - env: base
    - master https://github.com/whytewolf/test_repo1.git:
      - root: pillar/env1
      - name: env1
      - env: env1
```
push those pillars live to the minions.

then move to a new repo but keep the same name
```
ext_pillar:
  - git:
    - master https://github.com/whytewolf/test_repo2.git:
      - root: pillar/subbase
      - name: base
      - env: base
    - master https://github.com/whytewolf/test_repo2.git:
      - root: pillar/env1
      - name: env1
      - env: env1
```
in this example. the error `2018-01-12 19:28:02,242 [salt.utils.gitfs ][ERROR   ][11438] Root path '<bound method Pygit2._getconf of <salt.utils.gitfs.Pygit2 object at 0x2e3f090>>' not present in git_pillar remote 'master https://github.com/whytewolf/test_repo2.git', skipping.` will happen for the first repo. 

For the second repo. The test pillar will not change from env1 to env2. 

* both repos listed here are public so can be used for testing.

running `salt-run pillar.update` does not update the repo. 

so far only clearing out the git_pillar cache seems to fix the issue. 

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
