### ISSUE TITLE
salt-ssh grains.item overwrites grain values

### ISSUE THREAD

**Issue by mirkokeiner** [saltstack/salt#45460]
Hi everyone,

we are dealing with a major issue whilst setting up salt-ssh in our test environment.

We configured the following roster:
```
centos71:
  host: centos71
  grains:
    wb_side: a
    wb_os: centos7

centos72:
  host: centos72
  grains:
    wb_side: b
    wb_os: centos7
```

Now I would like to print the grain "wb_side" for each host and this is the result:
```
salt-ssh '*' grains.item wb_side
centos71:
    ----------
    wb_side:
        b
centos72:
    ----------
    wb_side:
        b
```

It somehow print the wrong value for the first Host.

Our Saltversion:
```
salt-ssh --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.18.7.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

This is a very critical issue for us, because we can not use salt like that.

Thanks and best regards!

**Comment by mirkokeiner** [comment]
Update:

When using:
```
salt-ssh '*' grains.items
```
all grain values are the same as the one of the last host.

**Comment by gtmanfred** [comment]
I am unable to replicate this behavior.

```
[root@salt ~]# cat /etc/salt/roster
minion1:
  host: minion1
  user: daniel
  passwd: braves
  tty: true
  sudo: true
  grains:
    foo: bar
minion2:
  host: minion2
  user: daniel
  passwd: braves
  tty: true
  sudo: true
  grains:
    foo: baz
[root@salt ~]# salt-ssh -i \* grains.item foo
minion2:
    ----------
    foo:
        baz
minion1:
    ----------
    foo:
        bar
[root@salt ~]# salt-ssh --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

```

It does look like this has been referenced before, https://github.com/saltstack/salt/issues/44394 , but we were also unable to replicate it there.

Can you provide me any more information to replicate this issue?

Thanks,
Daniel

**Comment by mirkokeiner** [comment]
Hi Daniel,

thank you for the quick answer. I would love to provide more Information, but which one could be helpful to replicate this Issue?

This is my roster file:
```
fktest:
  host: fktest
  grains:
    wb_rack: 5
    wb_side: a

mktest2:
  host: mktest2
  grains:
    wb_os: centos6
    wb_a: hallo

wbcentos71:
  host: wbcentos71
  grains:
    wb_side: b
    wb_os: centos7

wbcentos72:
  host: wbcentos72
  grains:
    wb_side: z
    wb_os: centos7

wbjp5:
  host: wbjp5

wbjp3:
  host: wbjp3

jztest:
  host: jztest
  grains:
    wb_side: z
```

Here you can see how everything gets overwritten by the values of wbjp5:
```
salt-ssh '*' grains.item host
wbjp3:
    ----------
    host:
        wbjp5
mktest2:
    ----------
    host:
        wbjp5
fktest:
    ----------
    host:
        wbjp5
wbjp5:
    ----------
    host:
        wbjp5
wbcentos71:
    ----------
    host:
        wbjp5
wbcentos72:
    ----------
    host:
        wbjp5
jztest:
    ----------
    host:
        wbjp5
```

The only possible reason I see is the roster. But I can't find anything wrong with it.

For testing purpose I deleted "wbjp5" from the roster. Now it will use the values of wbcentos72 to overwrite everything:
```
fktest:
    ----------
    host:
        wbcentos72
jztest:
    ----------
    host:
        wbcentos72
wbcentos72:
    ----------
    host:
        wbcentos72
mktest2:
    ----------
    host:
        wbcentos72
wbjp3:
    ----------
    host:
        wbcentos72
wbcentos71:
    ----------
    host:
        wbcentos72
```

Thanks,
Mirko

**Comment by gtmanfred** [comment]
ok, let me double check with cento 6 as my salt-ssh master.

**Comment by gtmanfred** [comment]
I am still unable to replicate this unfortunately

Can you try adding `--wipe --thin` to the salt-ssh command and see if that helps?

This will wipe the thin tarball directory on the minion, and will also regenerate a new thin tarball and transfer it over.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
yeah, hrm, yeah unforuntately without being able to reproduce this, there isn't a lot that we can do.

If you can setup a docker container image or a vagrant setup that has the roster file in it, that this happens with, and we can just update the roster to point to our own servers, maybe that will help.

**Comment by inf0rmix** [comment]
I had the same in my ubuntu  environment. Rooster looks equal. Salt-Version is the same 17.02 . I was able to reproduce it also on 17.01 . salt-ssh versions of 16.* worked as expected.

**Comment by inf0rmix** [comment]
Me did a rollback to distrib release of salt in ubuntu artful and the grains are working again:

inf0rmix@tardis:~/salt$ salt-ssh '*' grains.item loc 
tardis:
    ----------
    loc:
        Various
web:
    ----------
    loc:
        Berlin
inf0rmix@tardis:~/salt$ salt-ssh --versions-report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.14 (default, Sep 23 2017, 22:06:14)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.1
 
System Versions:
           dist: Ubuntu 17.10 artful
        machine: x86_64
        release: 4.13.0-31-generic
         system: Linux
        version: Ubuntu 17.10 artful

**Comment by inf0rmix** [comment]
After this, I purge salt from 2016 and use "pip install salt-ssh" to get version 2017.7.2 .

After this, the problem occures:

`inf0rmix@tardis:~/salt$ 
inf0rmix@tardis:~/salt$ salt-ssh '*' grains.item loc 
tardis:
    ----------
    loc:
        Various
web:
    ----------
    loc:
        Various
inf0rmix@tardis:~/salt$ salt-ssh --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.14 (default, Sep 23 2017, 22:06:14)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.1
 
System Versions:
           dist: Ubuntu 17.10 artful
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-31-generic
         system: Linux
        version: Ubuntu 17.10 artful
`

**Comment by mirkokeiner** [comment]
Just noticed, that this doesn't only happen with grains. I shut down one of our "clients" and tired a test.ping:

```
[wbadmin@wbsalt1 salt]$ ping mktest2
PING mktest2(10.168.89.154) 56(84) bytes of data.
From wbsalt1(10.168.89.228) icmp_seq=2 Destination Host Unreachable
From wbsalt1(10.168.89.228) icmp_seq=3 Destination Host Unreachable
From wbsalt1(10.168.89.228) icmp_seq=4 Destination Host Unreachable
^C
--- mktest2 ping statistics ---
5 packets transmitted, 0 received, +3 errors, 100% packet loss, time 4818ms
pipe 3
[wbadmin@wbsalt1 salt]$ salt-ssh '*' test.ping
fktest:
    True
wbcentos71:
    True
jztest:
    True
mktest2:
    True
wbcentos72:
    True
```

See how I shouldn't be able to ping the machine, but salt still returns with "true"? 

Now I removed every machine from the roster, except the shutdown mktest2. Now the ping returns the correct value:
```
mktest2:
    ssh: connect to host mktest2 port 22: No route to host
```


Last but not least I put back one more machine into the roster:
```
wbcentos72:
    ssh: connect to host mktest2 port 22: No route to host
mktest2:
    ssh: connect to host mktest2 port 22: No route to host
```

So it seems like it has nothing to do with grains. Salt will just always overwrite return values.
