### ISSUE TITLE
all service.running fails

### ISSUE THREAD

**Issue by histamineblkr** [saltstack/salt#45510]
### Description of Issue/Question
This _may_ be due to running both the salt-master and salt-minion on the same machine, but I'm not sure.

I wrote some basic salt states that install a package and check the service running for firewalld, fail2ban, and crond. However, they all fail on the service running portion with "Comment: The named service <name> is not available". I can run systemctl with <name> and all names exist and work as expected. I also tried changing each to <name>.service, but it fails with the exact same error.

If I put a garbage name in like, "laljkdlajf" it will error with "Comment: The named service laljkdlajf is not available" so it seems as though when running the salt state the name string is not found.

### Setup
I have written and created three separate salt states.

firewalld.sls
```
# Begin firewall
firewalld_package:
  pkg.installed:
    - name: firewalld
  service.running:
    - name: firewalld
    - enable: true
    - watch:
      - firewalld: public

saltmaster:
  firewalld.service:
    - name: saltmaster
    - ports:
      - 4505/tcp
      - 4506/tcp

public_firewall:
  firewalld.present:
    - name: public
    - services:
      - saltmaster
      - ssh
      - dhcpv6-client
    - sources:
      - x.x.x.x
      - x.x.x.x
      - x.x.x.x
      - x.x.x.x
```
Firewalld output when run:
```
host:
----------
          ID: firewalld_package
    Function: pkg.installed
        Name: firewalld
      Result: True
     Comment: Package firewalld is already installed
     Started: 12:21:35.788974
    Duration: 1851.729 ms
     Changes:   
----------
          ID: public_firewall
    Function: firewalld.present
        Name: public
      Result: True
     Comment: 'public' is already in the desired state.
     Started: 12:21:37.641807
    Duration: 3437.902 ms
     Changes:   
----------
          ID: firewalld_package
    Function: service.running
        Name: firewalld
      Result: False
     Comment: The named service firewalld is not available
     Started: 12:21:41.079927
    Duration: 0.612 ms
     Changes:   
----------
          ID: saltmaster
    Function: firewalld.service
      Result: True
     Comment: 'saltmaster' is already in the desired state.
     Started: 12:21:41.080675
    Duration: 934.332 ms
     Changes:   

Summary for zblkr
------------
Succeeded: 3
Failed:    1
------------
```
fail2ban.sls
```
# Install fail2ban
fail2ban_package:
  pkg.installed:
    - name: fail2ban

fail2ban_service:
  service.running:
    - name: fail2ban
    - enable: true
    - watch:
      - pkg: fail2ban_package
    - require:
      - pkg: fail2ban_package

# Manage Config for Local Settings
jail_config:
  file.managed:
    - name: /etc/fail2ban/jail.local
    - source: salt://files/jail.local
```
Fail2ban output:
```
host:
----------
          ID: fail2ban_package
    Function: pkg.installed
        Name: fail2ban
      Result: True
     Comment: Package fail2ban is already installed
     Started: 12:26:12.359870
    Duration: 1863.999 ms
     Changes:   
----------
          ID: fail2ban_service
    Function: service.running
        Name: fail2ban
      Result: False
     Comment: The named service fail2ban is not available
     Started: 12:26:14.224477
    Duration: 0.451 ms
     Changes:   
----------
          ID: jail_config
    Function: file.managed
        Name: /etc/fail2ban/jail.local
      Result: True
     Comment: File /etc/fail2ban/jail.local is in the correct state
     Started: 12:26:14.226029
    Duration: 16.15 ms
     Changes:   

Summary for zblkr
------------
Succeeded: 2
Failed:    1
------------
```
crond.sls
```
# Crond service running
crond_service:
  service.running:
    - name: crond
```
Crond output:
```
host:
----------
          ID: crond_service
    Function: service.running
        Name: crond
      Result: False
     Comment: The named service crond is not available
     Started: 12:27:56.008235
    Duration: 0.484 ms
     Changes:   

Summary for zblkr
------------
Succeeded: 0
Failed:    1
------------
```
crond.sls (modified with "lakdjfla")
```
# Crond service running
crond_service:
  service.running:
    - name: lakdjfla
```
Crond output:
```
host:
----------
          ID: crond_service
    Function: service.running
        Name: lakdjfla
      Result: False
     Comment: The named service lakdjfla is not available
     Started: 12:28:36.868774
    Duration: 0.654 ms
     Changes:   

Summary for zblkr
------------
Succeeded: 0
Failed:    1
------------
```

### Steps to Reproduce Issue
This happened from the first service salt state I wrote and has been persistent since. I can not reproduce it on any other machines. I have two vagrant boxes with the same salt states, one a salt-master and the other the salt-minion, and it works fine. This makes me think it's something small I am overlooking or maybe due to the fact that I am running the master and minion on the same box.

### Versions Report
Version is identical on master and minion since they are the same machine.

salt --versions-report:
```
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, May 10 2017, 20:04:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: fedora 24 Cancellara
        machine: x86_64
        release: 4.11.12-100.fc24.x86_64
         system: Linux
        version: Chapeau 24 Cancellara
```
