### ISSUE TITLE
Revisiting the minion restart issue

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#45513]
### Description of Issue/Question
I am upgrading from ubuntu 14.04 to ubuntu 16.04.  Under ubuntu 14.04 I could use a state to do this

```
  service.running:
    - name: salt-minion
    - enable: True
    - watch:
      - file: salt-minion_settings
```
and the minion would restart and continue the state with no problem.   That does not work in ubuntu 16.04.   

As I research I see that this problem has been discussed a lot.    There is the [minion.restart](**https://github.com/saltstack/salt/pull/32593**) module which appeared from discussion to be the true solution for how to restart a minion.  But after it was merged there was no state created and no references to it in FAQ.   Per the [FAQ](https://docs.saltstack.com/en/develop/faq.html#what-is-the-best-way-to-restart-a-salt-minion-daemon-using-salt-after-upgrade) does not recommend this but says to use a salt-call ( and from other discussion to set the order to last )

```
  cmd.run:
    - name: 'salt-call --local service.restart salt-minion'
    - bg: True
    - order: last
    - onchanges:
      - pkg: Upgrade Salt Minion
```

After reading up on the issue it still seems we don't have a good solution for this problem.    Is there more work planned on this issue? Is the current FAQ really the correct decision or should it be updated to use the minion.restart?

### Versions Report

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-108-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
