### ISSUE TITLE
Import jinja template in py renderer

### ISSUE THREAD

**Issue by kiemlicz** [saltstack/salt#45521]
### Description of question
Typically using salt, we define `map.jinja` file that defines some defaults (e.g. per OS basis)  
Such file can easily be used in `*.sls` files like so:

```
{% from "some/state/map.jinja" import state_data with context %}
some_state:
  x.y:
    - name: {{ state_data.something_fancy }}
```

How to achieve the same using `py` renderer?

```
#!py


def run():
  # how to import some/state/map.jinja ???
```
