### ISSUE TITLE
Salt CLI is rounding floats to 2 decimal places

### ISSUE THREAD

**Issue by jmarinaro** [saltstack/salt#45620]
### Description of Issue/Question
When passing arguments via the command line, salt is rounding floats to 2 decimal places. I have verified this behavior exists in develop, 2017.7, and 2016.11. If I pass an argument I expect it to remain as is.

### Steps to Reproduce Issue
```
root@a0e930608610:/# salt-call test.arg_clean dec2='1516645352.09' dec3='1516645352.009' dec4='1516645352.0009'
local:
    ----------
    args:
    kwargs:
        ----------
        dec2:
            1516645352.09
        dec3:
            1516645352.01
        dec4:
            1516645352.0
```

### Versions Report
```
root@a0e930608610:/# salt-call --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.10.0-42-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by jmarinaro** [comment]
Looks like it must be something with python2.7, I still see the issue with 2018.3.2
```
root@74ba8eb94a45:/# salt-call --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.0-32-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 
root@74ba8eb94a45:/# salt-call test.arg_clean dec2='1516645352.09' dec3='1516645352.009' dec4='1516645352.0009'
local:
    ----------
    args:
    kwargs:
        ----------
        dec2:
            1516645352.09
        dec3:
            1516645352.01
        dec4:
            1516645352.0
```
