### ISSUE TITLE
salt-cloud userdata_file fails under python 3

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#45624]
### Description of Issue/Question

Salt cloud fails to byte encode the userdata_file is defined from a provider or profile.

### Setup

```
default-c:
  id: <AwsKeyId>
  key: <AwsSecretKey>
  securitygroup: default
  location: us-west-2
  availability_zone: us-west-2a
  driver: ec2
  update_cachedir: True
  keyname: salt
  private_key: salt-cloud.pem
  userdata_file: etc/salt/windows-firewall.ps1
  win_installer: etc/salt/windows/Salt-Minion-2015.8.3-x86-Setup.exe
  win_username: Administrator
  win_password: auto
  use_winrm: True
```

### Steps to Reproduce Issue

Spin up an ec2 node with a custom userdata file under python 3

### Versions Report
```
Salt Version:
           Salt: 2018.2.0-46-ge0434bb

Dependency Versions:
           cffi: 1.11.4
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.0
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.3 (default, Nov 15 2017, 00:46:54)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
         dist:
         locale: UTF-8
        machine: x86_64
        release: 17.3.0
         system: Darwin
        version: 10.13.2 x86_64
```
