### ISSUE TITLE
state.win_path with index 0 add the path at the end

### ISSUE THREAD

**Issue by maxime-viargues-serato** [saltstack/salt#45622]
### Description of Issue/Question
Using win_path.exists with index 0 adds the path at the end instead of at the beginning. The index is just ignored.
Index 1 adds it at the second position (as expected) so it's impossible to add a path at the beginning.

### Setup
```
test path:
  win_path.exists:
    - name: 'C:\Program Files\test\'
    - index: 0
```
Applied on Windows 10.0.16299

### Steps to Reproduce Issue
Apply the state above:
Result:
```        
   ID: test path
    Function: win_path.exists
     Name: C:\Program Files\test\
      Result: True
     Comment:
     Started: 15:43:49.850000
    Duration: 423.0 ms
     Changes:
              ----------
              added:
                  C:\Program Files\test\ was added at index 25
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-97-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
