### ISSUE TITLE
Windows cmd doesn't execute as defined user

### ISSUE THREAD

**Issue by maxime-viargues-serato** [saltstack/salt#45643]
### Description of Issue/Question
I am trying to execute this command to add a credential on Windows 10.

```
cmdkey /generic:git:https://tfs.domain.net /user:DOMAIN\{{ pillar['user'] }} /pass:{{ pillar['password'] }}
```
The command succeeds but the credential is not added to the given 'user'

### Setup
State pplied
```
  cmd.run:
    - runas: {{ user }}
    - password: {{ pillar['password'] }}
    - name: 'cmdkey /generic:git:https://tfs.domain.net /user:DOMAIN\{{ pillar['user'] }} /pass:{{ pillar['password'] }}'
    - unless: 'cmdkey /list | findstr tfs.domain.net'
```

### Steps to Reproduce Issue
Apply the state from the master
- output says the "CMDKEY: Credential added successfully."
- Open the credential Manager on the user account: The credential is not there.

However, if the state is applied from the machine itself, i.e. open PowerShell, call "salt-call state.apply" it works. Same if the salt-minion service on the machine is logged on as the current user.
It doesn't seem to use the "user" field properly.
Using Windows 10.0.16299.

Also running the command ''cmdkey /list'' which lists the credentials, doesn't show the new one added, confirming it didn't work.

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-97-generic
         system: Linux
        version: Ubuntu 16.04 xenial
