### ISSUE TITLE
service.running reload: True does not seem to do a full daemon-reload

### ISSUE THREAD

**Issue by jessebye** [saltstack/salt#45655]
### Description of Issue/Question
We are still using some legacy upstart services on our Ubuntu 16.04 servers. On 14.04, we didn't need to do anything else as the state worked fine. In 16.04, we have `reload: True` but the state fails with `Unit analytics.80.service not found.` (for example).

As a workaround, I added this above the `service.running` state:
```
Run daemon reload:  
  module.run:
    - name: service.systemctl_reload
```

However, it does not seem to be doing a full `systemctl daemon-reload` since we get the same failure (unit not found). If we manually run `systemctl daemon-reload` on the server, then the state works fine and starts up the service.

So there appear to be two problems:
1. `reload: True` doesn't actually run a `daemon-reload`
2. `service.systemctl_reload` doesn't seem to do a `daemon-reload` either.

### Setup
```
app-service-file:
  file.managed:
    - name: /etc/init.d/analytics
    - source: salt://analytics.initd
app-service-start:
  service.running:
    - name: analytics
    - enable: True
    - reload: True
    - require:
      - file: app-service-file
```

### Steps to Reproduce Issue
Set up a valid upstart service file for the source. 
Then run the state above on an Ubuntu 16.04 VM.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-108-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
