### ISSUE TITLE
x509 signing client cert - denied by signing policy when targeting minion with pcre

### ISSUE THREAD

**Issue by campbellmc** [saltstack/salt#45671]
### Description of Issue/Question
Trying to get compound matching using E@ (pcre match) on minion ID working in signing policy - however - it is denied:

```
SaltInvocationError: PEM does not contain a single entry of type CERTIFICATE:
abc-wp-031 not permitted to use signing policy www
```
Previously using glob match means the cert is signed just fine.

If I use the the same PCRE match with the CLI to match a minion, it's all fine.

```
# salt -C 'E@abc-wp-\d+' test.ping
abc-wp-031:
    True
```

minions key in signing_policy.conf is written using an sls which takes the signing_policy pillar values.

Is this an issue with re escaping?

I tried using L@ as well but it doesn't work either.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
x509 pillar used to generate signing policy:
```
x509: 
  signing_policies: 
    www: 
      minions: "E@abc-dj-"
      basicConstraints: "CA:false"
      keyUsage: "Digital Signature, Key Encipherment"
      extendedKeyUsage: "clientAuth"
      subjectKeyIdentifier: hash
      authorityKeyIdentifier: keyid,issuer:always
      days_valid: 365
```

signing_policy.sls - used to generate and push signing policy to all minions:
```
salt_minion_service:
  service.running:
    - name: {{x509.salt_minion_service}}
    - enable: True
    - listen:
      - file: signing_policies_configuration

signing_policies_configuration:
  file.managed:
    - name: {{x509.signing_policies_conf}}
    - source: salt://{{slspath}}/files/signing_policies.conf.jinja
    - template: jinja
    - user: {{x509.user}}
    - group: {{x509.group}}
    - mode: {{x509.mode}}
    - context:
        signing_policies: {{x509.signing_policies}}
        ca_cert: {{x509.ca_cert}}
        ca_key: {{x509.ca_key}}
        default_signing_policy: {{x509.default_signing_policy}}
        copypath: {{x509.copypath}}
```

### Versions Report
Minion & Master versions the same.

Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
