### ISSUE TITLE
Avoid execution of included sls files?

### ISSUE THREAD

**Issue by jochenschreiber** [saltstack/salt#45699]
### Description of Issue/Question
This is more a question then a issue. In our setup (you can see a example in the setup section) we are requiring sls files in salt states. Under some circumstances we don't execute the salt states that is requiring a sls files but because of the the include (which is necessary for the execution if the salt states is executed) the function in the sls files will be executed. 

How can we avoid the execution of the function in sls files if the state that is requiring that file is not being executed?

### Setup
```
include:
  - foo
  - bar
  
{% set example = False %}
{% if example %}
test1:
  cmd.run:
    - name: test1.bat
    - require:
      - sls: foo
{% endif %}

test2:
  cmd.run:
    - name: test2.bat
    - require:
      - sls: bar
```

### Steps to Reproduce Issue
See the example in the setup section

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-109-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
