### ISSUE TITLE
aliases module doesn't follow symlinks

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#45796]
### Description of Issue/Question
On FreeBSD the default aliases file (`/etc/aliases`) is symlinked to `/etc/mail/aliases`. The aliases module removes the existing alias file (`/etc/aliases`) and replaces it with a new copy. So if the alias file is a symlink, it gets replaced.

### Setup
```
aliases_root:
  alias.present:
    - name: root
    - target: myuser@testdomain.com

aliases_symlink:
  file.symlink:
    - name: /etc/aliases
    - target: /etc/mail/aliases
    - force: True
    - require_in:
      - alias: aliases_root
```

### Steps to Reproduce Issue
Make sure `/etc/aliases` is a symlink and then run the states above. You will see that the aliases file isn't any longer a symlink.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Dec 11 2017, 18:38:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 10.3-RELEASE-p26
         system: FreeBSD
        version: Not Installed

```
