### ISSUE TITLE
mac py3 gives DeprecationWarning

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#45804]
### Description of Issue/Question
On mac py3 I see this when running salt-call sys.doc.
It does not show up on other salt-call commands.

```
jk-sierra-py3-base:~ jenkins$ sudo salt-call --local test.version
local:
    2017.7.3
jk-sierra-py3-base:~ jenkins$ sudo salt-call --local grains.item pythonversion
local:
    ----------
    pythonversion:
        - 3
        - 5
        - 3
        - final
        - 0
jk-sierra-py3-base:~ jenkins$ sudo salt-call --local sys.doc none
[WARNING ] /opt/salt/lib/python3.5/site-packages/salt/modules/mac_service.py:91: DeprecationWarning: The readPlist function is deprecated, use load() instead
  plist = plistlib.readPlist(true_path)

[WARNING ] /opt/salt/lib/python3.5/site-packages/salt/modules/mac_service.py:109: DeprecationWarning: Attribute access from plist dicts is deprecated, use d[key] notation instead
  'plist': plist}

local:
    ----------
jk-sierra-py3-base:~ jenkins$ sudo salt-call --local sys.doc aliases.list_aliases
[WARNING ] /opt/salt/lib/python3.5/site-packages/salt/modules/mac_service.py:91: DeprecationWarning: The readPlist function is deprecated, use load() instead
  plist = plistlib.readPlist(true_path)

[WARNING ] /opt/salt/lib/python3.5/site-packages/salt/modules/mac_service.py:109: DeprecationWarning: Attribute access from plist dicts is deprecated, use d[key] notation instead
  'plist': plist}

local:
    ----------
    aliases.list_aliases:
        
            Return the aliases found in the aliases file in this format::
        
                {'alias': 'target'}
        
            CLI Example:
        
                salt '*' aliases.list_aliases
            
jk-sierra-py3-base:~ jenkins$
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jan 29 2018, 15:56:45)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 16.1.0
         system: Darwin
        version: 10.12.1 x86_64
 ```
