### ISSUE TITLE
fileserver.update doesn't update, firing the event does update gitfs_backend

### ISSUE THREAD

**Issue by FireDrunk** [saltstack/salt#45846]
### Description of Issue/Question
Using ```salt-run fileserver.update```, the gitfs_backend doesn't get updated (although the event is received).

```
salt/run/20180202210808403735/new       {           
    "_stamp": "2018-02-02T20:08:08.877264",         
    "fun": "runner.fileserver.update",              
    "fun_args": [],                                 
    "jid": "20180202210808403735",                  
    "user": "root"                                  
}                                                   
salt/run/20180202210808403735/ret       {           
    "_stamp": "2018-02-02T20:08:09.088748",         
    "fun": "runner.fileserver.update",              
    "fun_args": [],                                 
    "jid": "20180202210808403735",                  
    "return": true,                                 
    "success": true,                                
    "user": "root"                                  
} 
```                                             
Firing the the event manually with:
```salt-call event.fire_master update salt/fileserver/gitfs/update```

Results in the following event(s):
```
salt/fileserver/gitfs/update    {                                                   
    "_stamp": "2018-02-02T20:08:57.670208",                                         
    "cmd": "_minion_event",                                                         
    "data": "update",                                                               
    "id": "devops-saltmaster-001.infra.prov.io",                                    
    "tag": "salt/fileserver/gitfs/update"                                           
}                                                                                   
salt/job/20180202210857675304/ret/devops-saltmaster-001.infra.prov.io   {           
    "_stamp": "2018-02-02T20:08:57.676640",                                         
    "arg": [                                                                        
        "update",                                                                   
        "salt/fileserver/gitfs/update"                                              
    ],                                                                              
    "cmd": "_return",                                                               
    "fun": "event.fire_master",                                                     
    "fun_args": [                                                                   
        "update",                                                                   
        "salt/fileserver/gitfs/update"                                              
    ],                                                                              
    "id": "devops-saltmaster-001.infra.prov.io",                                    
    "jid": "20180202210857675304",                                                  
    "retcode": 0,                                                                   
    "return": true,                                                                 
    "tgt": "devops-saltmaster-001.infra.prov.io",                                   
    "tgt_type": "glob"                                                              
}
```
The last one does forcefully update the gitfs_backends

### Setup
Nothing special, fresh install done with bootstrap.sh

### Steps to Reproduce Issue
See description.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
Config:

```
[root@devops-saltmaster-001 ~]# cat /etc/salt/master.d/*
##########
# States #
##########

gitfs_provider: pygit2

fileserver_backend:
  - git

gitfs_remotes:
  - ssh://git@devops-git-001.infra.prov.io/salt-org/salt-states.git:
    - pubkey: /root/.ssh/id_rsa.pub
    - privkey: /root/.ssh/id_rsa


##########
# Pillar #
##########

git_pillar_provider: pygit2
git_pillar_user: git
ext_pillar:
  - git:
    - ssh://git@devops-git-001.infra.prov.io/salt-org/salt-pillar.git:
      - pubkey: /root/.ssh/id_rsa.pub
      - privkey: /root/.ssh/id_rsa
external_auth:
  pam:
    salt-api:
      - .*
      - '@runner'
rest_cherrypy:
  port: 8000
  disable_ssl: True
```
