### ISSUE TITLE
Unable to download package from Nexus repository

### ISSUE THREAD

**Issue by varun292006** [saltstack/salt#45858]
### Description of Issue/Question
Unable to download package from Nexus repository

### Setup
Small stage environment with 1 master running salt-2017.7.2 and 4 windows minions

### Steps to Reproduce Issue

- Write a state as below:

```
Package download:
  artifactory.downloaded:
    - artifact:
        artifactory_url: {{ pillar['repository_url'] }}
        repository: '{{ repo_name }}'
        group_id: ''
        artifact_id: {{ pkg_name }}
        packaging: 'zip'
        classifier: 'winx64'
        version: '{{ pkg_version }}'
        username: {{ pillar['repo_username'] }}
        password: {{ pillar['repo_password'] }}
    - target_dir: '{{ config_agents.download_loc }}\{{ pkg_version }}'
    - failhard: True
```

- Execute the state file. This state gets executed fine on 3 minions but on fourth minion it gives the below error message:
```
          ID: Package download
    Function: artifactory.downloaded
      Result: False
     Comment: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
     Started: 11:54:50.967000
    Duration: 1030.0 ms
     Changes:
```

- I am able to download the packages manually as well as through a powershell script but not using saltstack. 

### Versions Report

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-93-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
