### ISSUE TITLE
Import map.jinja from gitfs_remotes (TemplateNotFound: salt://nginx/conf/map.jinja)

### ISSUE THREAD

**Issue by kislik** [saltstack/salt#45901]
### Description of Issue/Question
Can i import variable inside state from map.jinja? If it store map.jinja in "salt://" path?
**BUT**:

> I use gitfs_remotes

```
gitfs_remotes:
    - ssh://git@git.my-domain.com:8080/my-project/nginx.git:
      - base: master
      - mountpoint: salt://nginx

```
### Setup
> and i try execute in init.sls

`{% from "salt://nginx/conf/map.jinja" import nginx %}
`

### And i get
```
  File "/usr/lib/python2.7/dist-packages/salt/utils/jinja.py", line 135, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: salt://nginxi/conf/map.jinja
```

### Versions Report
2016.11.3+ds-1
