### ISSUE TITLE
sentry_return in orchestrate runner

### ISSUE THREAD

**Issue by max-l-weaver** [saltstack/salt#45946]
### Description of Issue/Question
I've set up an orchestrate runner that applies a highstate when a new minion is detected.
This works fine, but lately I have attempted to add a sentry returner that only returns errors to the state module but it isn't working as I'd hoped

### Setup
salt/pillar/raven.sls:
```
raven:
  dsn: https://xxxx@sentry.corp.net/12
  tags:
    - dc
    - fqdn
    - role
  hide_pillar: true
  report_errors_only: true
```

salt/orch/apply_highstate.sls:
```
{% set tag = salt.pillar.get('event_tag') %}
{% set data = salt.pillar.get('event_data') %}

sync_all:
  salt.function:
    - name: saltutil.sync_all
    - tgt: {{ data.id }}

sync_pillars:
  salt.function:
    - name: saltutil.refresh_pillar
    - tgt: {{ data.id }}
    - require:
      - salt: sync_all

update_mine:
  salt.function:
    - name: mine.update
    - tgt: {{ data.id }}
    - require:
      - salt: sync_pillars

highstate_run:
  salt.state:
    - tgt: {{ data.id }}
    - ret: sentry_return
    - highstate: True
    - require:
      - salt: update_mine
```

/etc/salt/master:
```
# ... snipped
reactor:
  - 'minion_start':
    - 'salt/reactor/run_orchestrator.sls'
```

salt/reactor/run_orcherstrator.sls:
```
invoke_orchestrate_file:
  runner.state.orchestrate:
    - mods: orch.do_highstate
    - pillar:
        event_tag: {{ tag }}
        event_data: {{ data | json() }}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
nothing is reported to Sentry when highstate fails
nothing reported in `/var/log/salt/master`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt-version: `salt 2017.7.3 (Nitrogen)`
raven-version: `raven==6.5.0`

Perhaps I'm missing a step or doing something wrong but from what I've pieced together this seems to be how this should be set up
