### ISSUE TITLE
Require by id/label

### ISSUE THREAD

**Issue by backhand** [saltstack/salt#4597]
As discussed with UtahDave on IRC:

Functionality for require'ing an id and whatever commands it may contain, regardless of the specific commands.

Example sls:

```

---
some_command:
  file.managed:
    - name: /root/x
    - source: salt://test/x

some_other_command:
  cmd.run:
    - name: echo "ho"
    - require:
      - id: some_command <-- This would simply require all tasks in some_command:
```

**Comment by JustinCarmony** [comment]
lol, do I dare ask if this has ever made it into a release @basepi ? :P

**Comment by howardroark** [comment]
I would likely use this for every require if it existed.  Would be a really great way to "genetalize" things.

**Comment by howardroark** [comment]
I'm on a phone and there is no edit option. I meant "generalize"... Haha.

**Comment by basepi** [comment]
I don't think anyone's been on this one..... :cry:

**Comment by anlutro** [comment]
I never understood why you have to specify the state module in the requirement in the first place. If state A requires state B, it shouldn't care whether state B is achieved via a file.managed, cmd.run or pkg.install.

**Comment by anlutro** [comment]
Also, if this were to be implemented, I don't see why the `id:` should be required. Salt could check if the list item is a string or a dict, and if it's a string, and if it's a string, require the state(s) with that ID.

**Comment by basepi** [comment]
The reason you have to specify is because of nesting:

```
my_awesome_states:
  pkg.installed:
    - name: apache2
  service.running:
    - name: apache2
```

How do you make the distinction between these two states? But yes, I do agree that we probably don't need `id:`.
