### ISSUE TITLE
[2017.7.3] grains.has_value behavior changed, returns True on grain containing empty list

### ISSUE THREAD

**Issue by Herugrim** [saltstack/salt#45986]
### Description of Issue/Question

In 2017.7.2 and before the function `grains.has_value `returns `False` if a grain contains an empty list. When i upgraded to 2017.7.3 it started to return `True`. I am not sure if this is intended but it broke my configuration so i just want to make sure it is not a bug as the documentation is a bit unclear on this specific usage.

### Setup

For the proof of concept of this 'bug' i have two minions, one with 2017.7.2 and one with 2017.7.3, master is running 2017.7.3 but i do not think that is an issue here. Version reports:
```

  10vm:
    Salt Version:
               Salt: 2017.7.2
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.5.3
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: 1.3.7
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.3
                ZMQ: 4.2.1
    System Versions:
               dist: debian 9.3 
             locale: ANSI_X3.4-1968
            machine: x86_64
            release: 4.9.0-5-amd64
             system: Linux
            version: debian 9.3
```

```
11vm:
    Salt Version:
               Salt: 2017.7.3
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.5.3
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.3
                ZMQ: 4.2.1](url)
     
    System Versions:
               dist: debian 9.3 
             locale: ANSI_X3.4-1968
            machine: x86_64
            release: 4.9.0-5-amd64
             system: Linux
            version: debian 9.3
```

### Steps to Reproduce Issue

Use test grain and sync it to the minions:

```
def test_grain():

    grains = {}
    grains['test-grain'] = []
    grains['test-grain-bla'] = ['bla']

    return grains
```

Subsequently read the grains:

```
$ salt -N dev grains.get test-grain
10vm:
11vm:
$ salt -N dev grains.get test-grain-bla
10vm:
    - bla
11vm:
    - bla
```

So this is as expected, test-grain is empty. However if i use `grains.has_value` it starts to deviate:

```
$ salt -N dev grains.has_value test-grain
10vm:
    False
11vm:
    True
$ salt -N dev grains.has_value test-grain-bla
10vm:
    True
11vm:
    True
```

As you can see the 2017.7.3 minion no longer returns `False` on the empty list while the 2017.7.2 does.

As i used `{% if salt['grains.has_value']('test-grain') %}` in my Jinja template this gave unintended behavior.

I managed to fix this behavior for myself by no longer returning any empty lists in my custom grain but maybe you can have a look if this change is intended.
