### ISSUE TITLE
states/boto3_route53.hosted_zone_present bad comparison when Comment is blank

### ISSUE THREAD

**Issue by nullify005** [saltstack/salt#45995]
### Description of Issue

If you leave Comment out of your state it's being interpreted as an empty string `''` whereas the upstream field is actually `None` not `''`

This means that the state is always making changes unnecessarily based on the Comment.

If the incoming Comment is set to `None` when empty not `''` then the comparison works properly and the state doesn't make any changes.

### Setup

Nada

### Steps to Reproduce Issue

Nada

### Versions Report
```
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul 15 2017, 17:16:57)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 17.4.0
         system: Darwin
        version: 10.13.3 x86_64
```
