### ISSUE TITLE
marathon_app.config failing after upgrade of marathon from 1.4 to 1.5

### ISSUE THREAD

**Issue by hibbert** [saltstack/salt#46037]
### Steps to Reproduce Issue
Using the same sls files as before I know get the following error

----------
          ID: datadog-agent-public
    Function: marathon_app.config
      Result: False
     Comment: Failed to update app config for datadog-agent-public: {'message': 'No JSON object could be decoded'}
     Started: 18:27:52.662164
    Duration: 80.19 ms

### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment]
Can you provide the sls file that you are using so that this can be replicated?

**Comment by hibbert** [comment]
Okay. Here's a simple sls file to replicate:-

```
nginx_test:
  marathon_app.config:
    - config:
        id: /nginx
        backoffFactor: 1.15
        backoffSeconds: 1
        container:
          type: DOCKER
          volumes: []
          docker:
            image: 'bitnami/nginx:latest'
            forcePullImage: false
            privileged: false
            parameters: []
        cpus: 0.3
        disk: 0
        instances: 1
        maxLaunchDelaySeconds: 3600
        mem: 128
        gpus: 0
        networks:
          - mode: host
        portDefinitions:
          - name: default
            protocol: tcp
            port: 10000
        requirePorts: false
        upgradeStrategy:
          maximumOverCapacity: 1
          minimumHealthCapacity: 1
        killSelection: YOUNGEST_FIRST
        unreachableStrategy:
          inactiveAfterSeconds: 300
          expungeAfterSeconds: 600
        healthChecks: []
        fetch: []
        constraints: []
```

This gets the error message

```
          ID: nginx_test
    Function: marathon_app.config
      Result: False
     Comment: Failed to update app config for nginx_test: {'message': 'No JSON object could be decoded'}
     Started: 19:50:45.441219
    Duration: 43.288 ms
```

The json itself works okay, when inserting an app via marathon ui

```
{
  "id": "/nginx",
  "backoffFactor": 1.15,
  "backoffSeconds": 1,
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "bitnami/nginx:latest",
      "forcePullImage": false,
      "privileged": false,
      "parameters": []
    }
  },
  "cpus": 0.3,
  "disk": 0,
  "instances": 1,
  "maxLaunchDelaySeconds": 3600,
  "mem": 128,
  "gpus": 0,
  "networks": [
    {
      "mode": "host"
    }
  ],
  "portDefinitions": [
    {
      "name": "default",
      "protocol": "tcp",
      "port": 10000
    }
  ],
  "requirePorts": false,
  "upgradeStrategy": {
    "maximumOverCapacity": 1,
    "minimumHealthCapacity": 1
  },
  "killSelection": "YOUNGEST_FIRST",
  "unreachableStrategy": {
    "inactiveAfterSeconds": 300,
    "expungeAfterSeconds": 600
  },
  "healthChecks": [],
  "fetch": [],
  "constraints": []
}
```
