### ISSUE TITLE
[oxygen] mac_assistive module not loading

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#46055]
### Description of Issue/Question
Since we are importing unicode_literals now we are getting the following error when trying to load mac_assistive in oxygen:

```
jk-el-capitan-py3:testing root# salt-call --local assistive.enable /usr/bin/osascript
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.mac_assistive. Module will not be loaded: 'unicode' object has no attribute 'version'
```
PR Incoming

### Versions Report

```
jk-el-capitan-py3:testing root# salt-call --versions-report
Salt Version:
           Salt: 2018.2.0-225-gd4377d4

Dependency Versions:
           cffi: 1.5.0
       cherrypy: 4.0.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Aug 24 2016, 14:05:14)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64
```
