### ISSUE TITLE
archive.extracted is not supporting exclude and change ownership together

### ISSUE THREAD

**Issue by gaizeror** [saltstack/salt#46092]
### Description of Issue/Question
The archive.extracted state is not supporting exclude option.
when I try to exclude file, I recieve an error:
"While trying to enforce user/group ownership, the following paths were missing:
  - /etc/filebeat/filebeat.yml

The states fails and not extracting the files
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
filebeat_extract:
  archive.extracted
    - name: /etc/filebeat
    - source: <HTTP URL>
    - skip_verify: True
    - enforce_toplevel: False
    - options: --strip-components=1 --exclude='filebeat.yml'
    - user: root
    - group: root
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

copy the state and run it on Ubuntu 16.04 server, url must be specified

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Cant copy that because I am working on an offline network.
salt version is 2017.7.2 (both master and minion)
