### ISSUE TITLE
archive.extracted takes a long time (> 4 minutes) even though directory exists

### ISSUE THREAD

**Issue by rombert** [saltstack/salt#46109]
### Description of Issue/Question

When using `archive.extracted` with a remote HTTP source, the task execution takes a long time, even if the target directory exists and `if_missing` is set.

```
          ID: unpack_firefox_45
    Function: archive.extracted
        Name: /opt/firefox-45
      Result: True
     Comment: /opt/firefox-45 exists
     Started: 14:00:22.040664
    Duration: 258347.027 ms
     Changes: 
```

I am not sure whether the time is spent downloading or checking the archive - the archive is both large and contains many entries.

### Setup

The state file contains:

```
unpack_firefox_45:
    archive.extracted:
        - name: /opt/firefox-45
        - source: https://ftp.mozilla.org/pub/firefox/releases/45.5.1esr/firefox-45.5.1esr.linux-x86_64.sdk.tar.bz2
        - source_hash: 'sha512=5f1df9cd989ab326075cb657eaed9354b010ee6304c512f1e47dc6ec9347808a16c2c9dad2555918254fd362bab250eb498d5e7e994227f19d17e6783cae7c86'
        - options: --strip-components=1 # dir name is firefox_sdk
        - if_missing: /opt/firefox-45
        - enforce_toplevel: false #incorrect behaviour from archive.extracted
```

### Steps to Reproduce Issue

Apply the above state

### Versions Report
```
/usr/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.16) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.4 (default, Jan 03 2018, 13:52:55) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-0-default
         system: Linux
        version: Not Installed
```
