### ISSUE TITLE
GitFS  saltenv ref won't pick up multiple of the same ref

### ISSUE THREAD

**Issue by moremo** [saltstack/salt#46124]
### Description of Issue/Question
Using GitPython with gitfs  ssh to repo with multiple saltenv on the same branch fails to retrieve for one saltenv.

### Setup
master config 
```

gitfs_remotes:
  - ssh://bestrepotever.fake.com/fakerepo:
    - saltenv:
      - base:
        - root: dev/srv/salt
        - ref: master
      - bob:
        - root: bob
        - ref: master
```

### Steps to Reproduce Issue
Running
`salt-run fileserver.dir_list saltenv=bob` 
will output directory list
running 
`salt-run fileserver.dir_list ` 
or
`salt-run fileserver.dir_list saltenv=base` 
outputs nothing, with no error in log.

changing the ref to a different branch such as 
```
gitfs_remotes:
  - ssh://bestrepotever.fake.com/fakerepo:
    - saltenv:
      - base:
        - root: dev/srv/salt
        - ref: master
      - bob:
        - root: bob
        - ref: bob

```
does allow both listings to go.

### Versions Report
Have two servers one running 2016.11.0. This one does not show the issue with the above steps/config and will show the directory listing for both saltenvs.

2nd server updated to latest build shows issue.
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this with these configurations:

```
gitfs_remotes:
  - https://github.com/Ch3LL/Ch3LLScripts.git:
    - saltenv:
      - base:
        - root: salt/states
        - ref: master
      - bob:
        - root: salt/states
        - ref: master
```

```
➜  salt git:(1439da8d76) sudo salt-run fileserver.dir_list saltenv=base
➜  salt git:(1439da8d76) sudo salt-run fileserver.dir_list saltenv=bob 
- _grains
- files
```

ping @terminalmage mind taking a look here?
