### ISSUE TITLE
With chocolately.version some packages don't work with check_remote=True

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#46150]
### Description of Issue/Question

Looking into this issue it looks like some packages have different capitalization when checking the remote version. so when used with `check_remote=True` the package is not matching any of the contents of the available dict. Which results in the following error. 

```
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 391, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\chocolatey.py", line 889, in version
    'available': available[pkg]}
KeyError: 'freesshd'
```
I have only tested with `freesshd` which to the remote system shows up as `freeSSHD`. 

This issue also stops `salt.state.chocolatey.installed` from testing already installed programs that this issue affects.  

### Setup
Install chocolatey on a windows machine. install freesshd then check it's version with `salt-call chocolatey.version freesshd check_remote=True` 

### Steps to Reproduce Issue
install freesshd then check it's version with `salt-call chocolatey.version freesshd check_remote=True`

### Versions Report
```
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7600 SP0 Multiprocessor Free
```
