### ISSUE TITLE
salt-cloud 2017.7.3 API: AttributeError: 'list' object has no attribute 'copy'

### ISSUE THREAD

**Issue by DR3EVR8u8c** [saltstack/salt#46156]
### Description of Issue/Question
Hello all,
failed to utilise cloud API to provision a new ec2 instance with the salt-cloud version 2017.7.3. But same config succeed with salt-cloud command or with version 2017.7.2. any help would be appreciated.

**Error message returned from the script:**
```
Traceback (most recent call last):
  File "/root/bin/salt_cloud.py", line 112, in <module>
    process()
  File "/root/bin/salt_cloud.py", line 84, in process
    ret = cloudwork(args)
  File "/root/bin/salt_cloud.py", line 59, in cloudwork
    result = cloud.profile(profilename, names=args.instance_name)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 344, in profile
    mapper = salt.cloud.Map(self._opts_defaults(**kwargs))
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 237, in _opts_defaults
    for provider in list(_providers).copy():
AttributeError: 'list' object has no attribute 'copy'
```
**compare \_\_init\_\_.py in between version 2017.7.2 and 2017.7.3 and found:**
```
237c237
<                 for provider in list(_providers).copy():
---
>                 for provider in list(_providers):
```

if I remove the ".copy()" in the sentence, my script will be successfully running.

### Setup
** Cloud profile:**
```
#Centos OS 7
lpr_micro_centos7:
  provider: lpr-ec2
  # custom Centos 7 enhanced network
  image: ami-xxxxxxx
  size: t2.micro
  ssh_username: ec2-user
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 10
      Ebs.VolumeType: standard
  del_root_vol_on_destroy: True
  script: memjet-bootstrap.sh
```
**cloud provider:**
```
lpr-ec2:
  driver: ec2
  id: id-of-aws-access
  key: key-of-aws-access

  private_key: /etc/salt/key.pem
  keyname: keyname
  location: ap-southeast-2

  subnetid: subnet-xxxxxxxx
  securitygroupid:
    - sg-xxxxxxx
  ssh_interface: private_ips
  minion:
    master: ip-of-master
    grains:
      cloud: aws
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
