### ISSUE TITLE
influxdb_retention_policy does not manage state of retention period, replication or default

### ISSUE THREAD

**Issue by OrlandoArcapix** [saltstack/salt#46180]
### Setup

influxdb (1.4) active and configured

### Steps to Reproduce Issue

* apply state to create retention policy:

```
{%- set influxdb = 'test' %}
set the influxdb retention policy on {{ influxdb }}:
    influxdb_retention_policy.present:
        - name: {{influxdb}}_retention
        - database: {{ influxdb }}
        - duration: 93d
        - replication: 1
        - default: True
```

* change configured retention period, default, or replication

* re-apply state - nothing changes

### Versions Report

```
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
