### ISSUE TITLE
salt-cloud will only intermittently build rackspace cloud instances with purely private networks

### ISSUE THREAD

**Issue by racker-markh** [saltstack/salt#46215]
### Description of Issue/Question
Issue: salt-cloud will only intermittently build rackspace cloud instances with purely private networks.

### Setup

You will need:
- Rackspace cloud user and api key
- (I've been testing in HKG region)
- Create a cloud network 'private_salt_net' (172.17.117.0/24)
- Create a centos6 salt-cloud-master node with PublicNet,ServiceNet,private_salt_net
  - (private_salt_net IP of master is 172.17.117.X - adjust config as needed)
- install latest 2017.7 versions of salt, salt-cloud, salt-master on salt-cloud-master
- instances will be built with only the ServiceNet,private_salt_net networks
- salt-cloud will interact with instances over the private_salt_net network

/etc/salt/cloud.providers.d/rackspace.conf
```
rshkg:
  minion:
    master: 172.17.117.X
  identity_url: 'https://identity.api.rackspacecloud.com/v2.0/tokens'
  compute_name: cloudServersOpenStack
  compute_region: HKG
  driver: openstack
  protocol: ipv4
  user: XXXXXXX
  ssh_key_name: salt-cloud-master
  tenant: NNNNNN
  apikey: XXXXXXXXXXXXXXXXXXXXX
  ssh_interface: private_ips
  ignore_cidr: 10.0.0.0/8
  managedcloud: True
  networks:
  - fixed:
    # This is RS PublicNet
    #- 00000000-0000-0000-0000-000000000000
    # This is private network : private_salt_net
    - d8f04574-4db7-41ba-xxxx-xxxxxxxxxxxx
    # This is RS servicenet
    - 11111111-1111-1111-1111-111111111111
```

/etc/salt/cloud.profiles.d/profiles.conf
```
small:
 provider: rshkg
 size: 1 GB General Purpose v1
 image: CentOS 6 (PVHVM)
 com.rackspace__1__build_config_options: backup_defaults,monitoring_defaults,updates
```

`# salt-cloud -p small rsmhs_19 -l debug`

- The purpose here is to simulate a rackconnect v3 environment where the external IPs are allocated on the loadbalancer, but the salt-cloud-master only interacts with the cloud instances via the private network
- We set 'managedcloud: True' to ensure that 'rax_service_level_automation' is complete before trying to connect.

### Steps to Reproduce Issue
* salt cloud starts:
  - during which it sets 'data' 
    - https://github.com/saltstack/salt/blob/v2017.7.4/salt/cloud/clouds/openstack.py#L778
        `data, vm_ = request_instance(vm_):`
  - This sometimes sets:  
    `data.private_ips=[]`
  - and sometimes: 
    `data.private_ips=[u'172.17.117.8', u'10.176.67.188']`
* server build completes - setting  'state': 'running'
* rax_service_level_automation completes
* output with debug enabled looks like:
```
[DEBUG   ] Waiting for managed cloud automation to complete
[DEBUG   ] Waiting for VM IP. Giving up in 00:09:10.
[DEBUG   ] OpenStack authenticating using apikey
[DEBUG   ] Loaded node data for rsmhs_19:
{'_uuid': None,
 'created_at': datetime.datetime(2018, 2, 27, 15, 3, 57, tzinfo=<libcloud.utils.iso8601.Utc object at 0x7f32f4f5ac90>),
 'extra': {'access_ip': u'',
           'access_ipv6': u'',
           'addresses': {u'private': [{u'addr': u'10.176.67.188',
                                       u'version': 4}],
                         u'private_salt_net': [{u'addr': u'172.17.117.8',
                                                u'version': 4}]},
           'availability_zone': None,
           'config_drive': u'',
           'created': u'2018-02-27T15:03:57Z',
           'disk_config': u'MANUAL',
           'fault': None,
           'flavorId': u'general1-1',
           'hostId': u'df67b98160a2a01f91b45fe57e1d35808f719b14625axxxxxxxxxxxx',
           'imageId': u'0c675e8d-41f8-4d1f-97fc-196a3c6f16ff',
           'key_name': u'salt-cloud-master',
           'metadata': {u'profile': u'small',
                        u'rax_service_level_automation': u'Complete'},
           'password': None,
           'power_state': 1,
           'progress': 90,
           'service_name': 'cloudServersOpenStack',
           'task_state': None,
           'tenantId': u'NNNNNN',
           'updated': u'2018-02-27T15:05:25Z',
           'uri': u'https://hkg.servers.api.rackspacecloud.com/v2/670517/servers/9e92932b-c5e9-4779-9428-XXXXXXXXXXXX',
           'userId': u'NNNNNN',
           'vm_state': u'active',
           'volumes_attached': None},
 'id': '9e92932b-c5e9-4779-9428-XXXXXXXXXXXXX',
 'image': None,
 'name': u'rsmhs_19',
 'private_ips': [u'172.17.117.8', u'10.176.67.188'],
 'public_ips': [],
 'size': None,
 'state': 'running'}
[WARNING ] Private IPs returned, but not public... Checking for misidentified IPs
[WARNING ] 172.17.117.8 is a private IP
[WARNING ] 10.176.67.188 is a private IP
[WARNING ] IP '10.176.67.188' found within '10.0.0.0/8'; ignoring it.
```
- however if 'data.private_ips' has been set, then we hit this bit of code:
https://github.com/saltstack/salt/blob/v2017.7.4/salt/cloud/clouds/openstack.py#L669-L715

which contains the snippet:
```
    if not result and ssh_interface(vm_) == 'private_ips':
        for private_ip in private:
            ignore_ip = ignore_cidr(vm_, private_ip)
            if private_ip not in data.private_ips and not ignore_ip:
                result.append(private_ip)
```
i.e. only append the private IP to the result list if the private_ip is not in the list of private_ips from the 'data' structure

- since data.private_ips is often populated in line 778 the IP does not get appended to the result, and salt-cloud loops around again with the same result...
```
[DEBUG   ] Waiting for VM IP. Giving up in 00:09:00.
...
...
```
Until the timer runs out and it deletes the instance.

THOUGHTS:
- 'private_ips' in the 'data' structure (populated in line 778) is sometimes empty, and sometimes contains the servicenet and private_salt_net IPS.
- if it contains IPs then salt-cloud fails to get an IP address and deletes the instance after 10 minutes even though an IP is available
- I have confirmed that during the salt-cloud run I am able to connect from salt-cloud-master to the new node over ssh - so connectivity is not an issue
- I don't understand the reasoning behind the logic (to expect that the private IPs not be in a list of private IPs??) 

BUT I suspect a race condition:
- If salt-cloud is very fast at requesting information from 'request_instance(_vm)' immediately after the node has been initiated, then it may get this info BEFORE rackspace_cloud has assigned the IP adresses.
- If the infrastructure is faster than this, then 'data' will contain the private ip addresses, and salt-cloud will fail to determine the correct IP.

### Versions Report
```
[root@salt-cloud-master salt]# salt --versions-report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.18.7.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

**Comment by garethgreenaway** [comment]
@gtmanfred Thoughts on this one?

**Comment by gtmanfred** [comment]
If you want to submit a fix for this driver, I am all for it.  But I am done with it, it has been almost entirely rewritten in Oxygen to use openstack-infra/shade modules, and will be moving to use openstackclient at some point.

Can you try using this new driver?  It moves all the logic over to the openstack-infra teams project, and we don't really do anything.

https://github.com/saltstack/salt/blob/2018.3/salt/cloud/clouds/openstack.py

If you want to use the apikey you will need to use 

```
    myrackspace:
      driver: openstack
      profile: rackspace
      auth:
        username: rackusername
        api_key: myapikey
      region_name: ORD
      auth_type: rackspace_apikey
```
And install `rackspaceauth` for a plugin to keystoneauth1.

The docs are also located in the top or here https://docs.saltstack.com/en/develop/topics/cloud/config.html#module-salt.cloud.clouds.openstack
