### ISSUE TITLE
AzureARM Documentation out-of-date or inaccurate

### ISSUE THREAD

**Issue by edlane** [saltstack/salt#46220]
### Description of Issue/Question
The URL of this [document](https://docs.saltstack.com/en/latest/topics/cloud/azurearm.html) https://docs.saltstack.com/en/latest/topics/cloud/azurearm.html is the first result for Google search "salt-cloud azurearm" but it appears to be out-of-date or just plain wrong.
In particular, most of the named config parameters in this document are invalid and the error messages generated when this tutorial is followed are not prescriptive.

**HOWEVER:** Another saltstack document appears to be mostly correct and up-to-date: https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.azurearm.html

I suggest eliminating the incorrect doc alltogether or revising it by incorporating the information from the "working" version.

### Setup
salt-cloud 2017.7.3 or later with azure dependancies installed

### Steps to Reproduce Issue
Following the directions provided here: https://docs.saltstack.com/en/latest/topics/cloud/azure.html leads to numerous failures and a non-working azure salt-cloud deployment on salt 2017.7.3 and also on "develop"

### Versions Report
```
lane@suse-ed:~> salt --versions-report
Salt Version:
           Salt: 2018.2.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.4 (default, Jan 03 2018, 13:52:55) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.15.4-1-default
         system: Linux
        version: Not Installed
 
```
