### ISSUE TITLE
WIN_LGPO requires unsetting certain policies before configuring new policies

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#46236]
### Description of Issue/Question
When trying to use the `lgpo.set` state I get the following error if some Group Policies are set (listed in Steps to Produce):
```
# sudo salt 'minion1' state.apply config_win_updates
minion1:
----------
          ID: My Local Group Policy
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1851, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 301, in set_
                  adml_language=adml_language)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 5525, in set_
                  raise CommandExecutionError(msg)
              CommandExecutionError: Error while attempting to write Administrative Template Policy data.  Some changes may not be applied as expected
     Started: 10:30:07.663000
    Duration: 93120.0 ms
     Changes:   

Summary for minion1
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  93.120 s
```

The request is for the module to not fail when these settings are pre-configured. I thought of just adding these settings to my state to have the state set them, but they are not available for configuration in the `win_lgpo.py` module. 

### Setup
Configure a master on 2017.7.3 (Any Linux OS)
Configure a 2017.7.3 Python 2 AMD64 minion on Windows 10/2016

### Steps to Reproduce Issue
Manually configure any of the settings in this list to anything but "Not Configured". From what I can tell it can be any mix of these, but as long as at least one of them is configured the error will occur:
```
Prevent installation of devices using drivers 
Prevent installation of devices that match any of these device IDs 
Join Microsoft MAPS
Send file samples when further analysis is required
Let Windows apps access trusted devices
Let Windows apps access location
Let Windows apps access messaging
Let Windows apps access account information
Let Windows apps access calendar
Let Windows apps access motion
Let Windows apps access contacts
Let Windows apps access email
Let Windows apps access camera
Boot-Start Driver Initialization Policy
Configure Windows Defender Smartscreen
Prevent bypassing Windows Defender SmartScreen prompts for sites
Enable/Disable PerfTrack
Turn off the Windows Messenger Customer Experience Improvement Program
Turn off Windows Error Reporting
Configure Offer Remote Assistance
```

Then run this state:
```
Company Local Group Policy:
    lgpo.set:
        - computer_policy:
            Configure Automatic Updates:
                Configure automatic updating: 4 - Auto download and schedule the install
                Scheduled install day: 0 - Every day
                Scheduled install time: "14:00"
                Install during automatic maintenance: True
                Install updates for other Microsoft products: True
                'If you have selected “4 – Auto download and schedule the install” for your scheduled install day and specified a schedule, you also have the option to limit updating to a weekly, bi-weekly or monthly occurrence, using the options below: Every week': True
                First week of the month: False
                Second week of the month: False
                Third week of the month: False
                Fourth week of the month: False
```
### Versions Report
```
    Salt Version:
               Salt: 2017.7.3
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: unknown
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.16299  Multiprocessor Free
```
