### ISSUE TITLE
Azure Windows VM provisioning failing when using Custom VHD

### ISSUE THREAD

**Issue by nkv16786** [saltstack/salt#46246]
### Description of Issue/Question
I am using salt cloud profile for azurearm to provision vm using custom VHD.
It is taking around 40 min to execute then timing out ,
when i am looking on portal i see the error as 

`Provisioning failed. OS Provisioning for VM 'customnkv' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later.. OSProvisioningTimedOut`

**Note:-** Same vhd is running fine when used from Portal and Powershell.

### Setup
profile used:-

```
azure-win:
  deploy: False
  image: https://abc.blob.core.windows.net/winserver/QEServer12R2.vhd
  location: eastus
  network: AzureARM-SanRamon-New
  network_resource_group: AzureARM-SanRamon-New-ResGrp
  os_disk_size_gb: 150
  provider: P_Azure
  resource_group: AzureARM-SanRamon-New-ResGrp
  security_group: cri-azure
  size: Basic_A1
  win_password: ******
  win_username: azureuser
  storage_account: sanramonarm
  subnet: ARM-Subnet1

```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt: 2017.7.1
