### ISSUE TITLE
salt.states.http.query converts JSON data_file to invalid JSON body

### ISSUE THREAD

**Issue by jessebye** [saltstack/salt#46273]
### Description of Issue/Question
Using the `data_file` option with `salt.states.http.query` results in a query with a form-encoded body, even if the data file is `json`.

From what I can tell, `salt.utils.http.query` is using `requests.request`, which sends up `data` as [form-encoded body](http://docs.python-requests.org/en/master/_modules/requests/api/#request). However, `requests.request` supports a `json` parameter which would pass the body as JSON.

### Setup
On minion, create a `/tmp/webhook_template.json`:
```
{
  "server": "{{ server }}",
  "action": "{{ action }}",
  "status": "{{ status }}",
}
```
On master, create a state like this:
```
send_webhook:
  http.query:
    - name: https://webhook.site/4ac4e88e-94fd-4a02-8ca7-d565e445a1e5/202
    - method: POST
    - status: 202
    - data_file: /tmp/webhook_template.json
    - data_render: True
    - template_dict:
        server: 'foo'
        action: 'bar'
        status: 'baz'
```

### Steps to Reproduce Issue
1. Run the state above.
2. Go to https://webhook.site/#/4ac4e88e-94fd-4a02-8ca7-d565e445a1e5
3. The body appears as `server=foo&action=bar&status=baz`

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 17 2018, 14:28:32)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 27 Twenty Seven
         locale: UTF-8
        machine: x86_64
        release: 4.14.16-300.fc27.x86_64
         system: Linux
        version: Fedora 27 Twenty Seven
```
