### ISSUE TITLE
salt-api w/CherryPy is broken on develop

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#46274]
### Description of Issue/Question
salt-api gives a 500 Internal Server Error on develop when trying to serve
a hosted html page.

Git bisect traced the breakage to here: 3f42a5836385dfed9cda22a19d324a6bbed1f50b

```
boucha@elsapo salt ((3f42a58...)|BISECTING)]$ git bisect bad
3f42a5836385dfed9cda22a19d324a6bbed1f50b is the first bad commit
commit 3f42a5836385dfed9cda22a19d324a6bbed1f50b
Author: Erik Johnson <palehose@gmail.com>
Date:   Fri Dec 8 15:49:21 2017 -0600

    Force Salt's YAML loader to load all strings as unicode types
    
    This reduces the likelihood that non-unicode strings make their way into
    Salt and cause str/unicode mismatches resulting in UnicodeDecodeErrors.

:040000 040000 8a96b299f0742794bf6eb3d60378746522c5b351 e00e04ce6a860c3929cae1c7470f7a19cc071e85 M	salt
:040000 040000 28029bd547e9e61cd2ebb0d6fd4b6f683689a3ba 479589b4418dfd1193a56ca3f3ab5236cde0b5a0 M	tests
```

### Setup

cat /etc/salt/master.d/cherrypy.conf
```
rest_cherrypy:                                                                  
  port: 8000                                                                    
  disable_ssl: True                                                             
  app_path: /beacon_demo                                                        
  app: /srv/web/html/index.html                                                 
  static: /srv/web/static                                                       
                                                                                
                                                                                
                                                                                
external_auth:                                                                  
  pam:                                                                          
    demouser:                                                                   
      - .*
```
Then restart salt-master and start salt-api

### Steps to Reproduce Issue
When I browse to `http://localhost:8000` I get the following output:

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 642, in respond
    self.get_resource(path_info)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 760, in get_resource
    dispatch(path)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 468, in __call__
    resource, vpath = self.find_handler(path_info)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 337, in find_handler
    objname = name.translate(self.translate)
TypeError: character mapping must return integer, None or unicode
Powered by CherryPy 6.0.1
```

### Versions Report
```
root@elsapo:/etc/salt/master.d# salt --versions-report
Salt Version:
           Salt: 2018.3.0-234-g3f42a58
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: 0.3.7
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

I've tested on Salt version `2017.7.4` and salt-api worked as expected.
