### ISSUE TITLE
Unable to run multiple orchestrations simultaneously

### ISSUE THREAD

**Issue by jessebye** [saltstack/salt#46301]
### Description of Issue/Question
We have been testing an orchestration which runs highstate on our servers. The orchestration is triggered by a reactor for `salt/cloud/*/created`.

When we spin up one server at a time, it works fine. But when we spin up 2+ servers at once, it only runs on one server.

### Setup
`reactor.conf`:
```
reactor:
  - 'salt/cloud/*/created':
    - salt://reactor/server_created.sls
```
`reactor/server_created.sls`:
```
invoke_server_created_orchestration_{{ data['name'] }}:
  runner.state.orchestrate:
    - args:
        - mods: orch.server_created
        - pillar:
            event_data: {{ data|json }}
```
`orch/server_created.sls`:
```
{% set data = salt.pillar.get('event_data') %}

highstate_run_{{ data['name'] }}:
  salt.state:
    - tgt: {{ data['name'] }}
    - highstate: True
    - saltenv: dev
    - ret: highstate
    - queue: True

```
### Steps to Reproduce Issue
1. Set up reactor and orchestration state shown above.
2. Create multiple servers simultaneously via `salt-cloud`.
3. When the servers come up, observe that only one has highstated. The others do not highstate at all.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
