### ISSUE TITLE
how to get pillars for targeted minion when orchestration is executed by a reactor.

### ISSUE THREAD

**Issue by vencrena** [saltstack/salt#46387]
### Description of Issue/Question
Hey, this is a question not an issue. basically I want to have specific workflow, and can not figure out by myself how to obtain pillars that are needed in orchestration which is executed by a reactor. 

### Setup and Steps to Reproduce Issue

To simplify workflow let say I have 1 salt-minion and 1 salt-master. 
1. On a master I issue a command 
` salt-call event.send 'salt/renatas/test' `
2. Rreactor catches that message in message bus and executes reactor state. 
file: `/srv/reactor/testing.sls`

```
{# When found salt/renatas/test #}

sync_and_highstate:
  runner.state.orchestrate:
    - mods: orch.testing
    - kwarg:
        pillar:
          event_tag: 'console11.aai'
```

3. Orchestration kicks in and executes: 
```
{% set data = salt.pillar.get('event_tag')  %}

cmd.run:
  salt.function:
    - tgt: 'xadconsole11.aai'
    - arg:
      - echo "{{data}}" >> test.txt
```
4. And that and it is working.  I know that if I pass additional parameters in pillars with event call also will work. but trying to achieve different thing. dont want to send pillars at all for minions that are started by orchestration. 

I also have pillars that looks like this: 
`/srv/pillar/top.sls`
``` ...
base:
  '*':
     - global.mining

# --------------------- LAB01 -----------------
  console11.aai:
     - appdir.csp-console.consoleui
... 
```

and of course pillars in `appdir/csp-console/consoleui.sls` file

HOW SHOULD I ACHIEVE THAT ORCHESTRATION TAKE PILLARS FOR SPECIFIC TARGET MINION IN THIS CASE console11.aai ( DESCRIBED IN PILLARS/TOP.SLS FILE) WHEN TRYING APPLY STATES FOR THAT MINION. WHAT I AM MISSING OR EVEN THIS IS POSSIBLE? MAYBE MORE STEPS SHOULD BE INVOLVED.... 

EXAMPLE for minion "console11.aai" when I run `salt console11.aai state.apply` it would take pillars, I what the same when it is executed from orchestration. 

```
### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.13.2.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final```
