### ISSUE TITLE
Duplicated CRON entries when script rerun multiple times or when crontab re-ordered by PLESK

### ISSUE THREAD

**Issue by offgridengineering** [saltstack/salt#46406]
When a salt script is run to create a crontab entry on a minion (Centos 6/7), the script creates a new entry and if already present due to previous running, the entry is duplicated.

Also, if crontab is reordered by Plesk, identifiers and crontab line can get separated so running same salt script will add an additional/duplicated entry.

The REAL un-edited crontab file below has 3 copies of "build-cms-report-data.sh", this is from a live Plesk instance.

```
#crontab -l

MAILTO=""
0	0	*	*	0	/usr/local/psa/admin/bin/php -dauto_prepend_file=sdk.php '/usr/local/psa/admin/plib/modules/servershield/scripts/update-servershield.php'
0	0,4,8,12,16,20	*	*	*	/usr/local/psa/admin/bin/php -dauto_prepend_file=sdk.php '/usr/local/psa/admin/plib/modules/wp-toolkit/scripts/maintenance.php'
0	0	*	*	*	/usr/local/psa/admin/bin/php -dauto_prepend_file=sdk.php '/usr/local/psa/admin/plib/modules/wp-toolkit/scripts/instances-auto-update.php'
0	0	*	*	*	/usr/local/psa/admin/bin/php -dauto_prepend_file=sdk.php '/usr/local/psa/admin/plib/modules/servershield/scripts/servershield-version-check.php'
55	23	*	*	*	/usr/local/bin/cleanup-directories.sh -r 21 -d /logs/cron > /dev/null 2>&1
50	23	*	*	*	/usr/local/bin/cleanup-directories.sh -r 30 -d /logs > /dev/null 2>&1
**#Lines below here are managed by Salt, do not edit
#Build CMS Report Script SALT_CRON_IDENTIFIER:id-build-cms-report
25	5	*	*	*	/usr/local/bin/build-cms-report-data.sh > /dev/null 2>&1**
#Find Wordpress Plugins and Versions SALT_CRON_IDENTIFIER:id-plugin-find
45	5	*	*	*	/root/find-plugins.sh > /dev/null 2>&1
#Scan for sus files in web root SALT_CRON_IDENTIFIER:id-scan-for-globals-cron-root
30	2	*	*	*	/usr/local/bin/scan-for-globals.sh > /dev/null 2>&1
#Scan for sus files in web root SALT_CRON_IDENTIFIER:id-scan-for-encryptedpayload-cron-root
45	2	*	*	*	/usr/local/bin/scan-for-encrypted.sh > /dev/null 2>&1
#Scan for sus files in web root SALT_CRON_IDENTIFIER:id-scan-for-x-cron-root
53	3	*	*	*	/usr/local/bin/scan-for-x.sh > /dev/null 2>&1
**#Lines below here are managed by Salt, do not edit
#Build CMS Report Script SALT_CRON_IDENTIFIER:id-build-cms-report
25	5	*	*	*	/usr/local/bin/build-cms-report-data.sh > /dev/null 2>&1
#Lines below here are managed by Salt, do not edit
#Build CMS Report Script SALT_CRON_IDENTIFIER:id-build-cms-report
25	5	*	*	*	/usr/local/bin/build-cms-report-data.sh > /dev/null 2>&1**
59	*	*	*	*	/usr/local/psa/admin/bin/php -dauto_prepend_file=sdk.php '/usr/local/psa/admin/plib/modules/letsencrypt/scripts/keep-secured.php'
[root@hw34 ~]# 
```

Salt script cron portion shown.
```
#
# 5 25 * * 0 /root/build-cms-report-data.sh > /dev/null 2>&1
#
cron-for-wp-check:
  cron.present:
    - user: root
    - name: '/usr/local/bin/build-cms-report-data.sh > /dev/null 2>&1'
    - minute: '25'
    - hour: '5'
    - daymonth: '*'
    - month: '*'
    - dayweek: '*'
    - identifier: 'id-build-cms-report'
    - comment: 'Build CMS Report Script'





# salt --versions-report
Salt Version:
           Salt: 2015.8.0
 
```
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.3.0
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-042stab120.19
         system: Ubuntu 14.04 trusty
 
```
root@salt:~# 
```

Suggestion - To handle crontab entries, ditch the idea of using an identifier and instead, recreate the cron line, then search the crontab for a matching line (ignore spaces/tabs) if present dont duplicate OR add line but comment out?
