### ISSUE TITLE
Data returned from network module has 2x double quotes 

### ISSUE THREAD

**Issue by Trouble123** [saltstack/salt#46405]
When sending data via http.query to a RESTful server, data sent from the network module is not JSON compliant.

Here is the state file:
network.sls

```
{% set newSubnet = salt['network.subnets']()[0] %}
{% set newIP = salt['network.ipaddrs']()[0] %}
{% set newGateway = salt['ip.get_default_gateway']() %}

update_network:
  event:
    - send
    - name: trigger/network/update
    - data:
        fqdn: {{ grains['fqdn'] }}
        id: {{ grains['id'] }}
        network_subnet: {{ newSubnet }}
        network_ip: {{ newIP }}
        network_gateway: {{ newGateway }}
```
I then have a reactor that sends that to our server, but the data is invalid. I had the data go through Fiddler on my laptop and found the issue is that the value has double double quotes, ie ""value"" instead of "value"
Here is the actual data sent:
```
{ "network_subnet": ""192.168.10.0/24"", "network_gateway": ""192.168.10.1"", "network_ip": ""192.168.10.140""}
```
I use the same state file (except pulling grains data) and it works - values are in single double quotes.

### Versions Report
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.3 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-111-generic
         system: Linux
        version: debian 9.3
