### ISSUE TITLE
salt-ssh: cmd.run runas do not work.

### ISSUE THREAD

**Issue by liborw** [saltstack/salt#46417]
### Description of Issue

The cmd.run with runas still runs as root

### Setup
```
test_runas:
  cmd.run:
    - runas: salt
    - name: 'echo "$USER"'
```
the output is:

```
----------
          ID: test_runas
    Function: cmd.run
        Name: echo "$USER"
      Result: True
     Comment: Command "echo "$USER"" run
     Started: 11:36:02.557477
    Duration: 5.057 ms
     Changes:   
              ----------
              pid:
                  16218
              retcode:
                  0
              stderr:
              stdout:
                  root

```

### Versions Report
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-112-generic
         system: Ubuntu 16.04 xenial

Target system of salt-ssh is also Ubuntu 16.04.

**Comment by zhulh200868** [comment]
I would highly recommend updating to a newer version of salt.

**Comment by garethgreenaway** [comment]
@liborw  The $USER variable is coming from the environment variables which are being inherited so this isn't a true representation of who the command is running as.  If you swap out `echo $USER` for `whoami` I think you'll see that the command is running as the salt user.

**Comment by liborw** [comment]
@garethgreenaway tried with `whoami` same as with `$USER`

testrunas.sls:
```
test_runas:
  cmd.run:
    - runas: salt
    - name: whoami
```

`salt-ssh '*' state.apply testrunas`:
```
          ID: test_runas
    Function: cmd.run
        Name: whoami
      Result: True
     Comment: Command "whoami" run
     Started: 13:34:56.649750
    Duration: 5.048 ms
     Changes:   
              ----------
              pid:
                  10170
              retcode:
                  0
              stderr:
              stdout:
                  root
```

Updating salt to latest version works.
