### ISSUE TITLE
Possibility to avoid failing entire apply due to `onfail_in` states failing

### ISSUE THREAD

**Issue by kojiromike** [saltstack/salt#46419]
### Description of Issue/Question

We are looking for ways to work around a minor issue in `postgres_user.present` (it fails instead of returning `clean` when the account is already set up, but nevermind that). To work around that, we implemented a state to simply try to connect to the postgres server. If it passes, we don't bother with the `postgres_user` state at all. (You might rightly point out that we could used `unless` instead of a whole `cmd.run` here, but I wanted to mask the postgres password from the system's audit log.)

```
Test DB Admin Account:
  cmd.run:
    - name: 'psql -c "SELECT 1;"'
    - env:
      - PGHOST: "{{ db_host }}"
      - PGSSLMODE: "require"
      - PGPORT: "{{ db_port }}"
      - PGDATABASE: "postgres"
      - PGUSER: "{{ db_user }}"
      - PGPASSWORD: "{{ db_pass }}"
    - output_loglevel: quiet
    - quiet: true
    - require:
      - sls: postgres.client
```

This works fine if the account does indeed already exist, but if it fails, the entire apply run fails. What I want to happen is it just fails over to the `postgres_user.present` state. By "fails" I mean the `retcode` value is nonzero in the below:

```
opts = salt.config.master_config('config/master')
runner = salt.runner.RunnerClient(opts)
ret = runner.cmd('state.orch', [orch_string], kwarg={'pillar':pillar_dict})
return ret["retcode"]
```

A state _did_ fail, but this makes using `onfail` somewhat less useful from a preemptive-testing point of view. From my point of view, if there's any way to programmatically detect variations in the "failureness" of the `state.apply` run besides parsing the entire output (such as using a different `retcode` value if all the failures were in `onfail_in` states) it would be very helpful.

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan  5 2018, 10:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: Not Installed
 
System Versions:
           dist: gentoo 2.4.1 
         locale: UTF-8
        machine: x86_64
        release: 4.14.12-gentoo.efi
         system: Linux
        version: Gentoo Base System 2.4.1 
```
