### ISSUE TITLE
Add LocalClient calls to the master scheduler

### ISSUE THREAD

**Issue by Mrono** [saltstack/salt#4643]
I have highstate scheduled in the master config file with a mysql returner, it all runs when done with CLI.  I get this error when running it in debug every time the schedule fires
'[INFO    ] Invalid function: highstate in job state.highstate. Ignoring.'

config:
```
schedule:
  highstate:
    function: state.highstate
    minutes: 30
    returner: mysql
```
