### ISSUE TITLE
Install multiple requirements files via pip and virtualenv states

### ISSUE THREAD

**Issue by OddBloke** [saltstack/salt#4648]
We have some projects where we have more than one requirements file (a core one which everywhere should install, and a site-specific one). At the moment, we have to write out a full state for each file:

```
main_requirements:
  pip.installed:
    - name:
    - requirements: ...

other_requirements:
  pip.installed:
    - name:
    - requirements: ...
```

It is also painful in a virtualenv definition:

```
my_virtualenv:
  virtualenv.managed:
    - name: ...
    - requirements: ...

extra_requirements:
  pip.installed:
    - name:
    - requirements: ...
```

And, of course, we then either have to introduce dependencies between the requirements states or depend on all of the requirements states where we need them.

Preferable would be a list of requirements files:

```
main_requirements:
  pip.installed:
    - name:
    - requirements:
      - main_requirements
      - other_requirements
```

This would boil down to `pip install -r main_requirements -r other_requirements`.
