### ISSUE TITLE
using user.info of new user

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#46509]
## How can this be done in 1 state.sls call?

```
tunnel_user:
  user.present:
    - name: tunnel

{{ salt['user.info']('tunnel').home }}/.ssh/authorized_keys:
  file.managed:
    - source: salt://tunnel/files/.ssh/authorized_keys
    - makedirs: True
    - user: tunnel
```

When the user does not exist, user.info('tunnel') returns nothing and **the rendering fails**.
