### ISSUE TITLE
[Feature Request] using user.info of new user

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#46516]
It'd be great if salt could handle this type of sls files (in case the user does not exist yet). It's a common theme when setting up a new server.

```
tunnel_user:
  user.present:
    - name: tunnel

{{ salt['user.info']('tunnel').home }}/.ssh/authorized_keys:
  file.managed:
    - source: salt://tunnel/files/.ssh/authorized_keys
    - makedirs: True
    - user: tunnel
```

Also #46509

**Comment by gtmanfred** [comment]
This is the thing that you are going to need to use, possibly.

https://docs.saltstack.com/en/develop/topics/slots/index.html

We are adding runtime evaluation to the salt states in 2018.3, but you will need to write a custom salt modules that does this.

`/srv/salt/_modules/custom.py`
```
def get_user_home(username):
    return '{0}/.ssh/authorized_keys'.format(__salt__['user.info'](username))
```

and then reference it using slots.

```
__slot__:salt:custom.get_user_home(tunnel):
  file.managed:
    - source: salt://tunnel/files/.ssh/authorized_keys
    - makedirs: True
    - user: tunnel
```

**Comment by srkunze** [comment]
I see. Well that's cool as it enables the usecase. Great! 

Next question: would it possible to re-use **user.info** for this?

```
__slot__:user.info(tunnel).home/.ssh/authorized_keys:
  file.managed:
    - source: salt://tunnel/files/.ssh/authorized_keys
    - makedirs: True
    - user: tunnel
```

My issue here is: it's already there, so why writing a new function? Salt already provides 1000s of such useful functions and modules. I actually would want to reuse all of them.
