### ISSUE TITLE
State with require requisite executes despite onfail requisite on another state.  

### ISSUE THREAD

**Issue by JeffLee123** [saltstack/salt#46552]
### Description of Issue/Question
A state with onfail requisite results in True if onfail target is successful and does not need to run. 
This would cause another state with a require requisite on the first state to always run regardless if the onfail target succeeds or not. 

Here, if pip is already installed, I do not want to run ensure_dir, source_download, or install_from_source.
However, if pip_installed is successful, ensure_dir would also result in True because it does not have to run because onfail req did not change. 
source_download has a require requisite on ensure_dir, so  it would run despite having a onfail requisite on pip_installed and pip_install is successful.   

Is there a way to have ensure_dir, source_download, and install_from_source to have depencies on each other, while at the same time, only execute if pip_installed fails? 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
pip_installed:
  pip.installed:
    - name: pip

ensure_dir:
  file.directory:
    - name: /tmp/tmp_dir
    - onfail:
      - pip_installed

source_download:
  cmd.run:
    - name: download from source to dir
    - onfail:
      - pip_installed
    - require:
      - ensure_dir

install_from_source:
  cmd.run:
    - name: install from source
    - require: 
      - source_download
    - onfail:
      - pip_installed
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
pip_installed results in True
ensure_dir does not run due to onfail requisite. Results in True.
source_download runs because it has require requisite on ensure_dir, despite having a onfail requite on pip_installled. 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.6
