### ISSUE TITLE
saltstack server_id changes with each run on python3

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#46595]
### Description of Issue/Question
saltstack server_id changes with each run

### Setup
Opensuse Tumbleweed 20180314
### Steps to Reproduce Issue
install tumbleweed, install salt-master, salt-minion, exchange keys,
run salt-call grains.item server_id multiple times
```
[root@spectre stack (master)]# salt-call grains.item server_id && date
local:
    ----------
    server_id:
        812924806
Sat Mar 17 14:05:41 CET 2018

[root@spectre stack (master)]# salt-call grains.item server_id && date
local:
    ----------
    server_id:
        533218382
Sat Mar 17 14:05:55 CET 2018

```

### Versions Report
```
Salt Version:
           Salt: 2018.1.99
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.4 (default, Jan 03 2018, 13:52:55) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.15.8-1-default
         system: Linux
        version: Not Installed
```
