### ISSUE TITLE
how post pillar data to salt-api, I had try many, but fail

### ISSUE THREAD

**Issue by khywolf** [saltstack/salt#46592]
[root@test salt]# salt-api --version
salt-api 2016.11.4 (Carbon)

CLI command:

```
[root@khy_vm01 salt]# salt '10.10.63.8' state.sls test pillar='{"getkey":"asdasdweefwd"}'
10.10.63.8:
----------
          ID: /tmp/test.txt
    Function: file.managed
      Result: True
     Comment: File /tmp/test.txt updated
     Started: 11:12:28.474736
    Duration: 49.829 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1 +1 @@
                  -2233232
                  +asdasdweefwd

Summary for 10.10.63.8
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  49.829 ms
```

Then, I try use curl post data to salt-api:
1) `curl -k https://10.10.45.236:8000/ -H 'Accept: application/json' -H 'X-Auth-Token: 97eaee0d319d1564d533c9ceffb9244ce0299c2f' -d fun='state.sls' -d arg='test' -d arg='pillar: {"getkey":"66666"}'`

2)

```curl -k https://10.10.45.236:8000/ -H 'Accept: application/json' -H 'X-Auth-Token: 97eaee0d319d1564d533c9ceffb9244ce0299c2f' -d '
[
  {
    "client": "local",
    "tgt": "10.10.63.8",
    "fun": "state.sls",
    "arg": ["test"],
    "kwarg": {
        pillar: {"getkey":"6666666"}
    }
  }
]'
```

###

```
[root@test salt]# cat test.sls 
{% set app_key = pillar.get('getkey') %}

/tmp/test.txt:
  file.managed:
    - name: /tmp/test.txt
    - source: salt://files/test.txt
    - user: xl_dev
    - group: xl_dev
    - mode: 755
    - template: jinja
    - defaults:
        TESTKEY: {{ app_key }}
```

```
[root@test salt]# cat files/test.txt 
{{ TESTKEY }}
```

Above was wrong, How post pillar data is right？
