### ISSUE TITLE
[2018.3.0rc1] jinja indent filter now returns invalid output

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#46594]
### Description of Issue/Question

(This worked fine on 2017.x, as far back as 2016.x)
Some of my more complex states are now broken if they use the ```yaml(False)```

Some pillar data i fetched from a database/files.
```
[root@cronos /salt/states/smartos]# salt carbon pillar.get smartos:zones:isotope
carbon:
    ----------
    alias:
        isotope
    brand:
        joyent
    cpu_cap:
        800
    cpu_shares:
        50
    customer_metadata:
        ----------
        minion_key:
            -----BEGIN RSA PRIVATE KEY-----
            data here
            -----END RSA PRIVATE KEY-----
        minion_pub:
            -----BEGIN PUBLIC KEY-----
            data here
            -----END PUBLIC KEY-----
        primary_mac:
            aa:bb:cc:dd:ee:ff
    dns_domain:
        vlan10.example.org
    filesystems:
        ----------
        /workspace:
            ----------
            options:
                - nodevice
            source:
                /zdata/isotope
            type:
                lofs
    hostname:
        isotope
    image_uuid:
        a0dd9320-674b-11e7-9483-2ff90b43b416
    max_physical_memory:
        16384
    nics:
        ----------
        aa:bb:cc:dd:ee:ff:
            ----------
            gateways:
                - xx.xx.xx.1
            ips:
                - xx.xx.xx.yyy/24
                - xx:xx:xx:xx::yyy/64
            mtu:
                1500
            nic_tag:
                trunk
            primary:
                True
            vlan_id:
                10
    quota:
        10
    resolvers:
        - xx.xx.xx.1
        - xx:xx:xx:xx::1
    tags:
        ----------
        description:
            saltstack development workstation
        storage_data_path:
            /workspace
    zfs_io_priority:
        50
    zfs_root_compression:
        lz4
```

The following macro is used to generate the actual state SLS
```
{% macro add_zone(zone, zonecfg) %}
smartos.zone::{{ zone }}:
  smartos.vm_present:
    - name: {{ zone }}
    - config:
        reprovision: true
        auto_import: false
    - vmconfig:
        {{ zonecfg|yaml(False)|indent(8) }}
        {{- _create_check(zonecfg) -}}
        {{- _lx_check(zonecfg) -}}
{% endmacro %}
```

The state fails on:
```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:smartos' failed: expected alphabetic or numeric character, but found '#'; line 555

---
[...]
        alias: isotope
        brand: joyent
        cpu_cap: 800
        cpu_shares: 50
        customer_metadata:
          minion_key: &#39;-----BEGIN RSA PRIVATE KEY-----    <======================

            data here

            more data here

[...]
---
```

On previous versions of salt the ```&#39;``` is not there, it seems to chocke on these.

### Steps to Reproduce Issue
See above.

### Versions Report
```
[root@carbon ~]# salt-call --versions-report
Salt Version:
           Salt: 2018.3.0rc1
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: 8.8.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: 1.6.7
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Dec 30 2017, 15:38:16)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: 0.6.6
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: 646
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed

```

This does have the x509 and nacl fixes applied on top of rc1, but those should not effect this.

**Comment by sjorge** [comment]
I've narrowed it down to issues with ```-``` if I don't have any of those in the output it works fine.

**Comment by sjorge** [comment]
I think I've narrowed some characters that are used in yaml, like '-' at the beginning of a line.

```hello``` -> OK
```hello-world``` -> OK
```-hello-world-``` -> NOT OK

**Comment by sjorge** [comment]
It looks like once the yaml filter needs to quote the string it goes south.

E.g. a simpler string holding a mac-address has the same issue that it gets ```&#39;``` which is probably ' or " encoded in some way.

**Comment by sjorge** [comment]
Took me a while to find out where the filter came from ... https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.jinja.html#salt.renderers.jinja.render

**Comment by sjorge** [comment]
It a unicode thing, revering the change from https://github.com/saltstack/salt/commit/c65d4714e52000260512286d8d33ab40b5161975#diff-ba5eb26a99dc1516dc97de22dbcbeea4 in salt.renderer.jinja fixes the problem.

**Comment by rallytime** [comment]
@terminalmage Can you look into this one?

**Comment by terminalmage** [comment]
@sjorge I can't reproduce this. Can you provide a more concise example that I could use to troubleshoot this? Preferably one that doesn't involve using a smartos-specific state, but I can deal with if you can't. So far, I've been troubleshooting by stepping through the jinja renderer in a debugger and checking the rendered output before Salt tries to run the state. This is what I get:

```yaml

smartos.zone::foo:
  smartos.vm_present:
    - name: foo
    - config:
        reprovision: true
        auto_import: false
    - vmconfig:
        minion_key: '-----BEGIN RSA PRIVATE KEY-----

          data here

          -----END RSA PRIVATE KEY-----

        '
        minion_pub: '-----BEGIN PUBLIC KEY-----

          data here

          -----END PUBLIC KEY-----

        '
        primary_mac: aa:bb:cc:dd:ee:ff
```
