### ISSUE TITLE
iptables jump target whitelist is outdated

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#46616]
### Description of Issue/Question

All `SYNPROXY` jump arguments are not whitelisted in the iptables module (namely `--mss`, `--wscale`, `--sack-perm`, `--timestamps`).

Some `CT` jump arguments are not whitelisted, including `--zone-orig` and `--zone-reply`.

The SET `--map-set` jump target argument also seems unsupported.

The SNAT `--random-fully` is likewise missing.

I'll submit a PR for the above shortly.

Also, can we get a `jump_args:`-type state sls argument (where anything goes without modification, which can also accept a list or arguments) for when such cases arise, so we don't need to upgrade Salt or override the execution module just to use new features in iptables and extensions going forward?

It's also very confusing from a user point of view when the list is outdated - until you venture into the source code, and I have to question the approach of having a whitelist for this task at all. From my perspective, I'd like `jump_args:` to be the future and the current whitelist to be deprecated and kept alive until compatibility is no longer a concern. Unless I'm overlooking something? What do you guys think?

### Setup
N/A.

### Steps to Reproduce Issue
```
filter_input_lan_http_synproxy_rule:
  iptables.append:
    - table: filter
    - chain: INPUT
    - in-interface: eth0
    - proto: tcp
    - match: state
    - dport: 80
    - connstate: INVALID,UNTRACKED
    - jump: SYNPROXY
    - sack-perm: ''
    - timestamp: ''
    - wscale: 7
    - mss: 1460
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.3 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.3 
 ```

**Comment by garethgreenaway** [comment]
@boltronics Are these new options to iptables?  The issue I see with moving away from the whitelist to allowing anything to be passed to iptables is how iptables is going to react to that.  If we're to control what is passed along and avoid errors.  @saltstack/team-core any other opinions on this?

**Comment by boltronics** [comment]
@garethgreenaway Not exactly new. SYNPROXY has been around since at least 2014. Not sure when the other options were added.

As for validating how iptables will react to invalid jump targets, a simple command exit status check should suffice:
```
$ sudo iptables -A INPUT -ieth1 -p tcp -m tcp --dport 81 -m state --state INVALID,UNTRACKED -j SYNPROXY --sack-perm --timestamp --wscale 7 --mssz 1460
iptables v1.6.0: unknown option "--mssz"
Try `iptables -h' or 'iptables --help' for more information.
$ echo $?
2
$ sudo iptables -A INPUT -ieth1 -p tcp -m tcp --dport 81 -m state --state INVALID,UNTRACKED -j SYNPROXY --sack-perm --timestamp --wscale 7 --mss 1460
$ echo $?
0
```

**Comment by boltronics** [comment]
Unfortunately I have learned `mss` causes problems if I simply add it to the jump list in the iptables module, because it is also a module option to `tcpmss` and not a jump target.

Thus:
```
Block uncommon MSS values:
  iptables.append:
    - table: mangle
    - chain: PREROUTING
    - proto: tcp
    - match:
      - conntrack
      - tcpmss
    - ctstate: NEW
    - mss: ! 536:65535
    - jump: DROP
```
would produce:
```
iptables -t mangle -A PREROUTING -p tcp -m conntrack -m tcpmss \
    --ctstate NEW --jump DROP --mss 536:65535
```
instead of:
```
iptables -t mangle -A PREROUTING -p tcp -m conntrack -m tcpmss \
    --mss 536:65535 --ctstate NEW --jump DROP
```
(which it currently does).

If it is determined that the jump keywords need to be maintained in the iptables execution module, we'll probably need to do something like have a dict of modes, and list each jump target associated against each one. Then the above would know that `--mss` wouldn't be jump target option since `tcpmss` is used.

However even that is problematic because somebody might want to use a block that both tcpmss and synproxy modules under the `modes:` YAML key that also uses the `--mss` option. In fact, I'm reasonably sure it currently wouldn't even be possible to support such a scenario YAML with the current setup since there would need to be two `mss:` keys in the same YAML block!

**Comment by boltronics** [comment]
Another conflict I encountered was when trying to add iptables rules to run fail2ban as an unprivileged user, which (from the docs included with the Debian package) requires something like this:
`iptables -I INPUT -m recent --update --seconds 3600 --name fail2ban-<name> -j DROP`

The `--name` argument conflicts with Salt's use of the `name` key. This was my ugly work-around:
```
Add fail2ban-ssh iptables rule:
  iptables.append:
    - name: fail2ban-ssh
    - table: filter
    - chain: INPUT
    - jump: DROP
    - match: recent
    - update: --name fail2ban-ssh
    - seconds: 3600
```

I really think the only practical way forward is to have the match block contain a list of dictionaries, where the key of each dict is the module, and the value is another list of module-specific arguments (or just an empty list if N/A).

eg.
```
Add fail2ban-ssh iptables rule:
  iptables.append:
    - name: fail2ban-ssh
    - table: filter
    - chain: INPUT
    - jump: DROP
    - match:
      - recent
        - update: ''
        - seconds: 3600
        - name: fail2ban-ssh
```
