### ISSUE TITLE
salt state order issue with cmd and service

### ISSUE THREAD

**Issue by qli-aa** [saltstack/salt#46637]
### Description of Issue/Question
salt-2017.7.4
```
I write a state file include file, service , cmd like below:
x.json:
  file.managed:
    - source: 
    ...

service_a:
  service.running:
    - name: xxx
    - enable: True
    - reload: True
    - watch:
      - file: x.json

some_cmd:
  cmd.script:
    - name: salt://xxx.sh
```
service should be reload or restart before cmd, but I found cmd always block service, service will run after cmd finished, is this a issue ?

**Comment by vangourd** [comment]
Not an expert so I can't tell you whether this is a bug or normal functionality but are you able to accomplish this with this as a workaround? 
```
some_cmd:
    cmd.script:
        - name: salt://xxx.sh
        - require:
            - service: service_a
```
I typically use this to ensure state is running in a specified order. As some states can be asynchronously executed while others must followed a specified order.

https://docs.saltstack.com/en/latest/ref/states/ordering.html
