### ISSUE TITLE
top file merging same does produce conflicting ids with gitfs

### ISSUE THREAD

**Issue by mruepp** [saltstack/salt#46660]
### Description of Issue/Question
We use gitfs as backend. We have three environments: dev-qa-staging
We use top file merging strategy same. Our Top files for every environment contains {{ saltenv }}:

We want to create and test states by branching away for instance from dev -> feature/branch, add changes, test them by using salt .. state.apply saltenv=feature/branch and after successfully highstating the changes, Pull Request and Merge.

So everything is fine except, as long as the feature branch exists, we are no longer able to highstate ALL environments at the same time without using saltenv. This will result in conflicting ids.

Also we are not able to move states from dev to qa for instance by checking out specific states or cherrypicking them from e.g. dev to qa to stage to prod because we will always having conflicting ids.

So I would expect with top file merging "same" for the environments to only account for the own files.

Do I miss something?

### Setup
Our gitfs config: 

```
fileserver_backend:
  - git

gitfs_provider: pygit2

gitfs_user: salt
gitfs_password: password

top_file_merging_strategy: same

default_top: base

gitfs_remotes:
  - https:/gitrepo/scm/devops/salt.git:
      - refspecs:
          - '+refs/heads/*:refs/remotes/origin/*'
          - '+refs/tags/*:refs/tags/*'
          - '+refs/pull/*/head:refs/remotes/origin/pr/*'
          - '+refs/pull/*/merge:refs/remotes/origin/merge/*'
      - root: states
      - base: master
      - saltenv:
          - dev:
              - ref: dev
          - qa:     
              - ref: qa
          - stage:
              - ref: stage

  #List the formula repos with respective base
  - https://gitrepo/scm/devops/salt-formulas.git:
      - name: vault-formula
      - root: vault-formula
      - saltenv:
          - dev:
              - ref: master

  - https://gitrepo/scm/devops/salt-formulas.git:
      - name: consul-formula
      - root: consul-formula
      - saltenv:
          - dev:
              - ref: master
```

### Steps to Reproduce Issue
Using Salt config as posted and try to create a feature branch to implement a change

### Versions Report
`Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
`
