### ISSUE TITLE
Configure Windows Service in state file

### ISSUE THREAD

**Issue by maxnh** [saltstack/salt#46671]
Is it somehow possible to configure the start type of Windows services inside a state file? I would like specify for a given service either 'disabled', 'automatic' or 'manual' inside my SLS file.

Thank you for your reply!

Max

**Comment by dwoz** [comment]
Yes, you can call the win_service module in your state. It will look something like this:
```
win32-service:
  module.run:
    - win_service.config:
      - service: MyService
      - start_type: auto
```
The '[win_service](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_service.html)' and '[execution of salt modules from within states](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html#execution-of-salt-modules-from-within-states)' docs will provide you with more details.
