### ISSUE TITLE
network.managed crashes on Windows, also ignores netmask sometimes

### ISSUE THREAD

**Issue by asymetrixs** [saltstack/salt#46680]
### Description of Issue/Question
There are two problems with `network.managed` on Windows.

1. `network.managed` crashes because of `ipaddress.ip_address(ip_string.decode())`

2. `network.managed` ignores the mask when the IP is specified in quotation marks, like `- '192.168.0.3/19'` and uses `/24` instead

### Setup

1)
```
System Network:
  network.managed:
    - name: Local Area Connection
    - dns_proto: static
    - dns_servers:
      - 192.168.0.1
      - 192.168.0.2
    - ip_proto: static
    - ip_addrs:
      - 192.168.0.3/19
```

2)
```
System Network:
  network.managed:
    - name: Local Area Connection
    - dns_proto: static
    - dns_servers:
      - 192.168.0.1
      - 192.168.0.2
    - ip_proto: static
    - ip_addrs:
      - '192.168.0.3/19'
```

### Steps to Reproduce Issue
See configuration above, 2) does not throw any error. The error message for 1) is
```
File: "c:\salt\bin\lib\site-packages\salt\ext\win_inet_pton.py", line 39, in inet_pton
  ipaddress.ip_address(ip_string.decode())
AttributeError: 'str' object has no attribute 'decode'
```

Removing the `.decode()` in that line seems to solve the issue.

### Versions Report

```
Salt Version:
    Salt: 2017.7.2
  
Dependency Versions:
    cffi:             1.10.0
    cherrypi:         10.2.1
    dateutil:         2.6.0
    docker-py:        not installed
    gitdb:            2.0.3
    gitpython:        2.1.3
    ioflo:            not installed
    Jinja2:           2.9.6
    libgit2:          not installed
    libnacl:          not installed
    M2Crypto:         not installed
    Mako:             1.0.6
    msgpack-pure:     not installed
    msgpack-python:   0.4.8
    mysql-python:     not installed
    pycparser:        2.17
    pycrypto:         2.6.1
    pycryptodome:     not installed
    pygit2:           not installed
    Python:           3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
    python-gnupg:     0.4.0
    PyYAML:           3.12
    PyZMQ:            16.0.2
    RAET:             not installed
    smmap:            2.0.3
    timelib:          0.2.4
    Tornado:          4.5.1
    ZMQ:              4.1.6

System Versions:
    dist:
    locale:           cp1252
    machine:          AMD64
    release:          7
    system:           Windows
    version:          7 6.1.7601 SP1 Multiprocessor Free
```

**Comment by Ch3LL** [comment]
should be fixed by this: https://github.com/saltstack/salt/pull/44754

which is in 2017.7.3 and 2017.7.4. Can you verify?

**Comment by asymetrixs** [comment]
``

**Comment by asymetrixs** [comment]
Tested using 2017.7.4

First config
```
System Network:
  network.managed:
    - name: Local Area Connection
    - dns_proto: static
    - dns_servers:
      - 192.168.0.1
      - 192.168.0.2
    - ip_proto: static
    - ip_addrs:
      - '192.168.0.3/21'
```
then and 
```
System Network:
  network.managed:
    - name: Local Area Connection
    - dns_proto: static
    - dns_servers:
      - 192.168.0.1
      - 192.168.0.2
    - ip_proto: static
    - ip_addrs:
      - 192.168.0.3/20
```
Network is configured correctly, no exceptions thrown.
