### ISSUE TITLE
`pkg.installed`: `hold: True` not applied to a package which is already installed.

### ISSUE THREAD

**Issue by mxork** [saltstack/salt#46689]
### Description of Issue/Question

`hold: True` is not applied to a package which is already installed. (may be specific to compound `pkg.installed`)

### Setup

```
some-packages-please:
  pkg.installed:
      - pkgs:
          - "git": "1.8.3.1"
          - "glusterfs-fuse": "3.8.4"
          - "socat": "1.7.3.2-2.el7"
          - "ceph-common": "1:0.94.5"
          - "nfs-utils": "1:1.3.0"
          - "iscsi-initiator-utils": "6.2.0.874"
          - "cifs-utils": "6.2"
      - hold: true
      - update_holds: true
```

### Steps to Reproduce Issue

Applying the above (`some-packages-please`) gives:

```
----------
          ID: some-packages-please
    Function: pkg.installed
      Result: True
     Comment: 5 targeted packages were installed/updated.
              Package glusterfs-fuse is now being held.
              Package socat is now being held.
              Package ceph-common is now being held.
              Package iscsi-initiator-utils is now being held.
              Package cifs-utils is now being held.
              The following packages were already installed: git=1.8.3.1, nfs-utils=1:1.3.0
```

and `nfs-utils`, `git` are indeed missing the version lock:

```
$ yum versionlock
Loaded plugins: fastestmirror, versionlock
0:telegraf-1.4.1-1.*
1:ceph-common-0.94.5-2.el7.*
0:cifs-utils-6.2-10.el7.*
0:glusterfs-fuse-3.8.4-18.4.el7.centos.*
0:iscsi-initiator-utils-6.2.0.874-4.el7.*
0:socat-1.7.3.2-2.el7.*
versionlock list done
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 1.10.6
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

```
$ yum --version
3.4.3
  Installed: rpm-4.11.3-25.el7.x86_64 at 2018-01-08 16:27
  Built    : CentOS BuildSystem <http://bugs.centos.org> at 2017-08-03 03:48
  Committed: Panu Matilainen <pmatilai@redhat.com> at 2017-03-17

  Installed: yum-3.4.3-154.el7.centos.noarch at 2018-01-08 16:27
  Built    : CentOS BuildSystem <http://bugs.centos.org> at 2017-08-05 19:13
  Committed: CentOS Sources <bugs@centos.org> at 2017-08-01

  Installed: yum-plugin-fastestmirror-1.1.31-42.el7.noarch at 2018-01-08 16:27
  Built    : CentOS BuildSystem <http://bugs.centos.org> at 2017-08-11 10:23
  Committed: Valentina Mukhamedzhanova <vmukhame@redhat.com> at 2017-03-21
```
