### ISSUE TITLE
Pillar data in feature branch environment does not apply

### ISSUE THREAD

**Issue by mruepp** [saltstack/salt#46681]
### Description of Issue/Question
We use a git branching strategy to implement states.
For example we use the dev environment and branch away to feature/teststate
Our top.sls is configured with {{ saltenv }}: and merging strategy "same"
Our pillar top.sls is also configured with {{ saltenv }}:

We pull refspecs from git to use feature branches to test states:
```
default_top: base
gitfs_remotes:
  - `https://gitrepo/scm/devops/salt.git:`
    - refspecs:
      - '+refs/heads/*:refs/remotes/origin/*'
      - '+refs/tags/*:refs/tags/*'
      - '+refs/pull/*/head:refs/remotes/origin/pr/*'
      - '+refs/pull/*/merge:refs/remotes/origin/merge/*'
    - root: states
    - base: master
    - saltenv:
      - dev:
        - ref: dev
``` 

So we can run: `
`salt '*' state.apply saltenv=feature/teststate`

If successful we PR and merge the feature back to dev (or qa or staging). We also aim to do CI by automate testing of states with jenkins and docker/salt-cloud

Our Pillars are configured like this:
```
git_pillar_base: master
git_pillar_root: pillar

ext_pillar:
  - git:
    - __env__ https://gitrepo/scm/devops/salt.git
```

So if we want to write a pillar in the feature/testbranch and add it to the top.sls of the testbranch, the git featurebranch never draws. We have to write the pillars directly in the dev environment to apply.
Its like the refspecs are not applied in the pillar conf only in the gitfs conf.
Are we able to use this in the ext_pillar conf:
```
    - refspecs:
      - '+refs/heads/*:refs/remotes/origin/*'
```
So behaviour of gitfs fileserver backend and pillar git backend differs.

### Steps to Reproduce Issue
Configure gitfs backend to enable environments based on branches. Configure ext_pillar with __env__ variable. Pillar and states are in the same repo and branch. Branch away from a defined environment, for example dev -> feature/teststate
Write states, write pillars and change top files filters accordingly. 
Try to highstate with your environment/branch:
`salt '*' state.apply saltenv=feature/teststate`
Try to get pillar items with 
`salt '*' pillar.items pillarenv=feature/teststate`
The pillars will be empty. Only pillars from defined environments apply

### Versions Report
```
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
