### ISSUE TITLE
Salt communication broken after network reconfigure.

### ISSUE THREAD

**Issue by danny-smit** [saltstack/salt#46712]
### Description of Issue/Question
I'm trying to provision and configure CentOS based machines using the salt state network.managed. This salt state changes the network configuration from dhcp to a static configuration, meaning that the IP address of the node is changed by it. The state itself works perfectly and an implicit ifdown/ifup is triggered by the network.managed, because of which the new static address is activated on the fly. Also communication between the master machine and minion machine with the new IP address immediately works as expected on a network level (ping and ssh back and forth works immediately).

However communication between the salt master and minion seems to stall. After the network state is done, other state files will be executed that require files or data from the salt master (using states like file.managed). The very first state that does so, stalls for about 4 minutes and finally results in a SaltReqTimeoutError in the salt minion log file. After that the salt run continues and all other state files that use states like file.managed, are able to communicate with the master just fine.

In the meantime, while the minion stalled, the salt master already report "Minion did not return. [No response]". Even when the minion continued and finished processing all of the states (communication with the master seems to be restored), the master still fails to communicate with minion, as the following call keeps failing with the "Minion did not return. [No response]" as reply: 

  `salt 'minion.test.local' test.ping`

The interesting thing is that a restart of the salt minion restored the communication between master and minion again. After a restart the a test.ping from master to minion is successful again.

I understood it is to be expected that the minion will attempt to reconnect to the master, however it does cause one salt state to be unsuccessful. So there is some collateral damage in the process. Additionally the master stays confused, as it never seems to recover from the situation. 
Is that expected behavior? 

And if so, is there a way speed up the process in such a way the salt recovers without one salt state failing? Or at least make sure that other salt states do not fail because of it?

### Setup

```
# /srv/salt/network/interfaces.sls

{{ interface }}:
  network.managed:
    - enabled: True
    - type: eth
    - proto: none
    - ipaddr: {{ ip_addr }}
    - netmask: {{ netmask }}
    - gateway: 192.168.0.1
```
   
```   
# /srv/salt/network/hosts.sls

hosts_file:                                                                     
  file.blockreplace:                                                            
    - name: /etc/hosts                                                           
    - source: salt://{{ slspath }}/templates/hosts                   
    - append_if_not_found: True
```

### Steps to Reproduce Issue

`salt 'minion' state.highstate`

The call above results in the following response:

`Minion did not return. [No response]`

The following is shown in the minion log:

```
    2018-03-22 17:09:35,981 [salt.state       ][INFO    ][32590] Executing state file.blockreplace for [/etc/hosts]
    2018-03-22 17:10:35,983 [salt.transport.zeromq][DEBUG   ][32590] SaltReqTimeoutError, retrying. (1/3)
    2018-03-22 17:11:36,042 [salt.transport.zeromq][DEBUG   ][32590] SaltReqTimeoutError, retrying. (2/3)
    2018-03-22 17:12:36,102 [salt.transport.zeromq][DEBUG   ][32590] SaltReqTimeoutError, retrying. (3/3)
    2018-03-22 17:13:36,166 [salt.state       ][ERROR   ][32590] An exception occurred in this state: Traceback (most recent call last):
    <stacktrace>
    SaltReqTimeoutError: Message timed out
```

See the attached log for all of the details: [salt_minion.log](https://github.com/saltstack/salt/files/1848322/salt_minion.log)

Note that in this example case the order of the two states can easily be switched as a work-around. However then there are other states that start to fail and those states require the network to be setup properly before they can succeed.

### Versions Report

I tried the scenario with both versions 2016-11-6, 2017.7.1 and 2017.7.4 of both the salt-master and salt-minion. See attached version reports:
[version_report_salt_master.txt](https://github.com/saltstack/salt/files/1848323/version_report_salt_master.txt)
[version_report_salt_minion.txt](https://github.com/saltstack/salt/files/1848324/version_report_salt_minion.txt)
