### ISSUE TITLE
make 'unless'  a state object feature request

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack/salt#46745]
### Description of Issue/Question

I want to use `cmd.run` to execute a sensitive command as unprivileged user (`runas`), but allow  stateful `onlyif`/`unless` checks to run under elevated privilege.  This is not possible in one state.

```
postgresql-cluster-prepared-example:
  cmd.run:
    - name: {{ postgres.prepare_cluster.command }}    <-- 'initdb'
    - runas: {{ postgres.prepare_cluster.user }}     <--  'postgres'
    - unless: test -f {{ postgres.data_dir }}/PG_VERSION    <-- dir permissions locked down

```

In certain postgres scenarios, `unless` needs elevated privilege to avoid permission denied failure. It will be possible to workaround the issue (more states) but just flagging the use case.

**cmd.run** 
> salt.states.cmd.run(name, onlyif=None, unless=None, creates=None, cwd=None, runas=None, shell=None, env=None, stateful=False, umask=None, output_loglevel='debug', quiet=False, timeout=None, ignore_timeout=False, use_vt=False, **kwargs)
> 
> Run a command if certain circumstances are met. Use cmd.wait if you want to use the watch requisite.
> 
> name
> The command to execute, remember that the command will execute with the path and permissions of the salt-minion.
> 
> onlyif
> A command to run as a check, run the named command only if the command passed to the onlyif option returns true
> 
> unless
> A command to run as a check, only run the named command if the command passed to the unless option returns false
> 
> cwd
> The current working directory to execute the command in, defaults to /root
> 
> runas
> The user name to run the command as

> The state altering system is used to make sure that states are evaluated exactly as the user expects. It can be used to double check that a state preformed exactly how it was expected to, or to make 100% sure that a state only runs under certain conditions

> The unless requisite specifies that a state should only run when any of the specified commands return False. The unless requisite operates as NAND and is useful in giving more granular control over when a state should execute.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
