### ISSUE TITLE
Timezone State Issue

### ISSUE THREAD

**Issue by EMGrant** [saltstack/salt#46753]
Saltstack Version:

```Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.2
      docker-py: 3.1.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.10
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-5-amd64
         system: Linux
        version: debian 8.10
```

I have the following states that apply to a group of Ubuntu 16.04 LTS servers:

```
timey-wimey:
  pkg.latest:
    - pkgs:
      - ntp
      - tzdata
  service.running:
    - name: ntp
    - require:
      - pkg: timey-wimey


system_timezone:
  timezone.system:
    - name: {{ pillar['time']['timezone'] }}
    - utc: True
```

When the state is applied to those servers, it says it ran successfully and I can verify with timezone.get_zone.  However, whenever I run the highstate, it says that it still needs to be set.  After doing some digging with the help from someone on Freenode, I noticed that the /etc/adjtime file had 'LOCAL' set instead of 'UTC'.  After sed'ing the file, the highstate output displays correctly the server is already set to UTC time.

@babilen tracked it down to this:

https://github.com/saltstack/salt/blob/7874c908ac8da63e7c3bec7a17a95d8fc5cc6a9d/salt/modules/timezone.py#L540-L544
