### ISSUE TITLE
gem.list_upgrades: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by alxwr** [saltstack/salt#46759]
### Description of Issue/Question

`gem.list_upgrades` appears to be broken.

### Setup

Just a salt master and its minion.

### Steps to Reproduce Issue

```
% salt myhost.example.com gem.list_upgrades
myhost.example.com:
    Passed invalid arguments to gem.list_upgrades: object of type 'bool' has no len()
    
        .. versionadded:: 2015.8.0
    
        Check if an upgrade is available for installed gems
    
        gem_bin : None
            Full path to ``gem`` binary to use.
        ruby : None
            If RVM or rbenv are installed, the ruby version and gemset to use.
            Ignored if ``gem_bin`` is specified.
        runas : None
            The user to run gem as.
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' gem.list_upgrades
        
```

According to the error message I need no arguments.

### Versions Report

From the salt master:

```
% salt --versions-report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Mar 26 2018, 19:36:33)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE
         system: FreeBSD
        version: Not Installed
```
from the affected machine:

```
# salt --versions-report
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Mar 26 2018, 19:36:33)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 11.1-RELEASE
         system: FreeBSD
        version: Not Installed
```
