### ISSUE TITLE
Enhancement: file.tidy to remove unwanted files from a directory tree

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt#46752]
I'm in a situation where I need to remove some unwanted files from a directory tree, without knowing at which level they are stored (could also be multiple files matching a glob pattern at different levels in the tree). So it would be nice to have something similar to [Puppet's tidy resource](https://puppet.com/docs/puppet/4.10/type.html#tidy).

For example:
```
remove_foo:
  file.tidy:
    - name: /path/to/directory
    - recurse: True
    - matches: foo
```
This would remove all files named foo at any level below /path/to/directory.
