### ISSUE TITLE
2016.3.8: prereq stack overflow

### ISSUE THREAD

**Issue by ScoreUnder** [saltstack/salt#46762]
### Description of Issue/Question

Stack overflows when a state `prereqs` on a state with unfulfilled requirements.

### Setup

```yaml
a: test.fail_without_changes

b:
  test.nop:
    - prereq:
      - c

c:
  test.nop:
    - require:
      - a
```

### Steps to Reproduce Issue

Execute the above SLS in salt-call.

This segment should repeat in the stack trace of the resulting `RuntimeError: maximum recursion depth exceeded` error:
```
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2089, in call_chunk
    running = self.call_chunk(low, running, chunks)
```

### Versions Report

```
Salt Version:
           Salt: 2016.3.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.7.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

**Comment by ScoreUnder** [comment]
Tested on **2017.7.4** too:
```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.27.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan  5 2018, 10:41:29)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.15.4-1-hardened
         system: Linux
        version: Not Installed
 
```

This version is **also affected**.
