### ISSUE TITLE
salt-cloud digital ocean does not add specified tags

### ISSUE THREAD

**Issue by adminfromhell** [saltstack/salt#46822]
### Description of Issue/Question
tags that are specified in the profile config are not added to the created host

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
do-2g-nyc3-centos:
  provider: do
  image: 7.4 x64
  size: s-1vcpu-2gb
  location: New York 3
  private_networking: True
  ssh_interface: private
  backups_enabled: False
  ipv6: True
  tags:
    - internal
 
do-docker:
  extends: do-2g-nyc3-centos
  minion:
    grains:
      role: docker
```

`salt-cloud -p do-docker some.host.name`

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Add tags to profile and then create a host with that profile

salt-cloud output: https://pastebin.com/uHhsLcf9

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
 ```
