### ISSUE TITLE
file.recurse fail with "needs to be formed as a list"

### ISSUE THREAD

**Issue by little7777** [saltstack/salt#46835]
### Setup
```
common_packages:
  pkg.installed:
    - pkgs:
      - telnet
      - bind-utils
      - lrzsz
      - mlocate
      - iftop
      - openssl
      - rsync

aide:
  pkg.installed

aide_files:
  file.recurse:
    - name: /tmp/security
    - source: salt://ids/security
    - require: aide
```

### Steps to Reproduce Issue
    Data failed to compile:
----------
    The require statement in state 'aide_files' in SLS 'common' needs to be formed as a list

### Versions Report
```
salt-master: 
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-642.6.2.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

minion:
   salt-minion 2017.7.3 (Nitrogen)
```

**Comment by gtmanfred** [comment]
You require statement is not a list, it is a string.

```
aide_files:
  file.recurse:
    - name: /tmp/security
    - source: salt://ids/security
    - require:
      - pkg: aide
```

```
aide_files:
  file.recurse:
    - name: /tmp/security
    - source: salt://ids/security
    - require:
      - aide
```

You want one of the above options.
