### ISSUE TITLE
dynamically generated pillar data is not read by minion during the  run 

### ISSUE THREAD

**Issue by chetanpjain** [saltstack/salt#46830]
### Description of Issue/Question
dynamic pillar data generated is not available to minion even after pillar refresh
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
##
generate_pillar.sls
#### Generate yml
```
/srv/pillar/replicasetdata.sls:
  file.managed:
    - source: salt://test/replicasetdata.yml
    - user: root
    - group: root
    - mode: 644
    - template: jinja
```
---------------------------------------------
create_json.sls

## I am refreshing pillar data here, so that newly created sls is read here
```
refresh_pillar:
  module.run:
    - name: saltutil.refresh_pillar
    - refresh: True

/srv/salt/mmsagent/automatic_configuration.json:
  file.serialize:
    - dataset: {{ salt['pillar.get']('auto_config') }}
    - formatter: json
```
### Steps to Reproduce Issue
run a state that creates a yaml file which is used as a pillar data, and that data need to be converted to json, but newly created yaml dataset is not loaded, it still reads older dataset (older content of yaml)

### Versions Report
```
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo
```

**Comment by gtmanfred** [comment]
So, the 

```
refresh_pillar:
  module.run:
    - name: saltutil.refresh_pillar
    - refresh: True
```

Will refresh the pillar data in a different thread.

I think you will want to use the `reload_pillar` global to get what you want.
https://docs.saltstack.com/en/latest/ref/states/requisites.html#reload

**Comment by chetanpjain** [comment]
Thanks for reply.
you mean to setup reoad_pillar in the previous state which is creating yaml
which i need to use as pillar data.

I am not getting any example to use reload_pillar though, I tried to run it
as a module but it fails with error :
One or more requisite failed: create_json.reload_pillar

how do i set it global?

tried adding as this too :

#### Generate yml
/srv/pillar/replicasetdata.sls:
  file.managed:
    - source: salt://test/replicasetdata.yml
    - user: root
    - group: root
    - mode: 644
    - template: jinja
    - reload_pillar: true
but it still does not loads the new data.

--Chetan

**Comment by gtmanfred** [comment]
Oh, i see the problem.

So, jinja is all rendered at compile time.  So no states run before the jinja is rendered.  This is causing the `pillar.get` to be run before the new file is layed down on the system.

What you will need to do is update to 2018.3.0 which was just released today, and use slots.

```
[root@21aa2746ae36 ~]# tail -c +0 /srv/pillar/*.sls /srv/salt/*.sls
==> /srv/pillar/test.sls <==


==> /srv/pillar/top.sls <==
base:
  '*':
    - test

==> /srv/salt/test.sls <==
/srv/pillar/test.sls:
  file.managed:
    - contents: |
        foo: bar
    - reload_pillar: true

test:
  module.run:
    - name: test.echo
    - text: __slot__:salt:pillar.get(foo)

[root@21aa2746ae36 ~]# salt \* pillar.get foo
21aa2746ae36:
[root@21aa2746ae36 ~]# salt \* state.apply test
21aa2746ae36:
----------
          ID: /srv/pillar/test.sls
    Function: file.managed
      Result: True
     Comment: File /srv/pillar/test.sls updated
     Started: 18:36:25.858819
    Duration: 146.771 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1 +1 @@
                  -
                  +foo: bar
----------
          ID: test
    Function: module.run
        Name: test.echo
      Result: True
     Comment: Module function test.echo executed
     Started: 18:36:26.006895
    Duration: 13.771 ms
     Changes:
              ----------
              ret:
                  bar

Summary for 21aa2746ae36
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time: 160.542 ms
```

Slots render at runtime, just before.

```
/srv/pillar/replicasetdata.sls:
  file.managed:
    - source: salt://test/replicasetdata.yml
    - user: root
    - group: root
    - mode: 644
    - template: jinja
    - reload_pillar: true

/srv/salt/mmsagent/automatic_configuration.json:
  file.serialize:
    - dataset: __slot__:salt:pillar.get(auto_config)
    - formatter: json
```
