### ISSUE TITLE
Unable to apply GPO (Windows 2016)

### ISSUE THREAD

**Issue by trudesea** [saltstack/salt#46877]
### Description of Issue/Question
Trying to setup group policy on a Windows 2016 VM and the state is failing to apply
### Setup
/srv/salt/windows/gpo.sls
```
Company Local Group Policy:
    lgpo.set:
        - computer_policy:
            Windows Components\Windows Update\Configure Automatic Updates: Disabled
            Passwords must meet complexity requirements: Disabled
            Minimum password length: 10
```
### Steps to Reproduce Issue
```
salt 'os:windows' state.apply windows.gpo
Following error:
----------
          ID: Minimum password length
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1851, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 244, in set_
                  hierarchical_return=False)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 5070, in get
                  class_vals[policy_name] = _getScriptSettingsFromIniFile(_pol)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4632, in _getScriptSettingsFromIniFile
                  _existingData = _existingData.split('\r\n')
              TypeError: a bytes-like object is required, not 'str'
     Started: 19:33:15.467512
    Duration: 1817.378 ms
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

### Versions Report
Minion:
```
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free`

Server:
`Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.9
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

I also seem to not be able to retrieve a list of the policy names :
```
salt '*' lgpo.get return_full_policy_names=True
<hostname redacted>:
    Passed invalid arguments to lgpo.get: a bytes-like object is required, not 'str'
    
        Get a policy value
    
        Args:
    
            policy_class (str):
                Some policies are both user and computer, by default all policies
                will be pulled, but this can be used to retrieve only a specific
                policy class User/USER/user = retrieve user policies
                Machine/MACHINE/machine/Computer/COMPUTER/computer = retrieve
                machine/computer policies
    
            return_full_policy_names (bool):
                True/False to return the policy name as it is seen in the
                ``gpedit.msc`` GUI or to only return the policy key/id.
    
            hierarchical_return (bool):
                True/False to return the policy data in the hierarchy as seen in the
                ``gpedit.msc`` GUI. The default of False will return data split only
                into User/Computer configuration sections
    
            adml_language (str):
                The ADML language to use for processing display/descriptive names
                and enumeration values of ADMX template data, defaults to en-US
    
            return_not_configured (bool):
                Include Administrative Template policies that are 'Not Configured'
                in the return data
    
        Returns:
            dict: A dictionary containing the policy values for the specified class
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' lgpo.get machine return_full_policy_names=True
```

But it does work when I do this:
`salt '*' lgpo.set computer_policy="{'Minimum password length':10}"
<Name Redacted>:
    True`
Am I doing something wrong here?  This works just fine on my other salt master which is 2017.7.2

**Comment by lomeroe** [comment]
Do you have startup/shutdown scripts defined on this minion that you might not have on other minions?

The whole startup/shutdown script part needs some attention (all it *did* was return the data from the ini file), but this looks to be a regression from #44944 as the _read_regpol_file function doesn't return a string (as the _getScriptSettingsFromIniFile is expecting) like it used to...

**Comment by trudesea** [comment]
Hi lomeroe,

The only difference between this minion and the other is that it is deployed in the Google Cloud vs Internal VMWare Cloud.  The only difference in startup would be the Google Agent and not VMWare Tools.  Everything else is bare bones Google Cloud Windows 2016 DataCenter.  Apologies, should have noted that in the issue. I've also just replicated the issue with a fresh 2016 VM and latest Salt Minion 2018.3.0

```
salt-call --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```
Same error here as well

```
salt-call lgpo.get return_full_policy_names=True

Passed invalid arguments: a bytes-like object is required, not 'str'.

Usage:

    Get a policy value

    Args:

        policy_class (str):
            Some policies are both user and computer, by default all policies
            will be pulled, but this can be used to retrieve only a specific
            policy class User/USER/user = retrieve user policies
            Machine/MACHINE/machine/Computer/COMPUTER/computer = retrieve
            machine/computer policies

        return_full_policy_names (bool):
            True/False to return the policy name as it is seen in the
            ``gpedit.msc`` GUI or to only return the policy key/id.

        hierarchical_return (bool):
            True/False to return the policy data in the hierarchy as seen in the
            ``gpedit.msc`` GUI. The default of False will return data split only
            into User/Computer configuration sections

        adml_language (str):
            The ADML language to use for processing display/descriptive names
            and enumeration values of ADMX template data, defaults to en-US

        return_not_configured (bool):
            Include Administrative Template policies that are 'Not Configured'
            in the return data

    Returns:
        dict: A dictionary containing the policy values for the specified class

    CLI Example:

    .. code-block:: bash

        salt '*' lgpo.get machine return_full_policy_names=True
```
