### ISSUE TITLE
2018.3.0 utils do not seem to get synced properly

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#46911]
### Description of Issue/Question
I dropped all the new zfs/zpool stuff that missed the boat for 2018.3 into the dirs to have them synced:
```
[.]$ find ../
../
../_states
../_states/README
../_states/zfs.py
../_states/zpool.py
../_modules
../_modules/README
../_modules/zfs.py
../_modules/zpool.py
../_runners
../_runners/README
../_grains
../_grains/README
../_grains/zfs.py
../_utils
../_utils/README
../_utils/zfs.py
```

They all showed succesfully synced after running ```salt '*' saltutil.sync_all```, however the grains module fails to load properly because it cannot find the salt.utils.zfs.

I assume this might be because grains are a bit tricky and do not get a lot of the stuff loaded into it. So the sycned utils may be missing.

### Setup
N/A

### Steps to Reproduce Issue
Add a grains that uses something form a custom utils module.
Sync both to other minions, the new grains module will not find the newly synced utils module.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: 1.6.7
         Jinja2: 2.9
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Dec 30 2017, 15:38:16)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: 0.6.6
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
