### ISSUE TITLE
2018.3 regression file.managed.context parsing

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack/salt#46929]
### Description of Issue/Question

With 2018.3 release, there is regression in file.managed states WRT  [found unexpected ':'](http://pyyaml.org/wiki/YAMLColonInFlowContext) issue.  
Sorry I have no logs available.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

These values have embedded Colon" and file.managed context parsing fails.
```
etcd:
  service:
    initial_cluster: etcd0=https://127.0.0.1:2380
    initial_cluster_state: new
    initial_cluster_token: etcd-cluster-1
    initial_advertise_peer_urls: https://127.0.0.1:2380
    listen_peer_urls: https://127.0.0.1:2380
    listen_client_urls: https://127.0.0.1:2379
    advertise_client_urls: https://127.0.0.1:2379


..

  file.managed:
    - template: jinja
    - context:
      etcd: {{ etcd }}
```

**Workaround:**

```
    - context:
      etcd: {{ etcd|json }}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

A colleague verbally reported same issue with **different formula** so looks like regression.

Reverting to 2017.7 stable resolved any problems.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

2018.3  (not available, I have downgraded to 2017.7).

**Comment by Ch3LL** [comment]
can you include how you are setting: `{{ etcd }}` and the info for it, its not clear to me how that is set in this example.

**Comment by noelmcloughlin** [comment]
Hi @Ch3LL   See `defaults.yaml` below where the `context dict` data originated.

**defaults.yaml**
```
etcd:
  a: b
  c: d
  
  lookup:
     e: f
     g: h

  service:
    initial_cluster: etcd0=https://127.0.0.1:2380
    initial_cluster_state: new
    initial_cluster_token: etcd-cluster-1
    initial_advertise_peer_urls: https://127.0.0.1:2380
    listen_peer_urls: https://127.0.0.1:2380
    listen_client_urls: https://127.0.0.1:2379
    advertise_client_urls: https://127.0.0.1:2379
```

With 2018.3 the following values were tested.
- `https://127.0.0.1:2380` failed
- `https{{ ':' }}127.0.0.1{{ ':' }}2380` failed
- `https//127.0.0.12380` worked

 I can try to replicate next week if necessary.

**Comment by Ch3LL** [comment]
apologies i should have been more clear. Are you importing that etcd data from yaml file like so ? `{% import "test.yaml" as blah %}` or pillar data, etc?

**Comment by noelmcloughlin** [comment]
NP, I checked the  [etcd PR code](https://github.com/saltstack-formulas/etcd-formula/pull/7/files).

- The `install.sls` has `{% from "etcd/map.jinja" import etcd with context -%}`.
-  The `map.jinja` has `{% import_yaml 'etcd/defaults.yaml' as defaults %}` before merging
-  No pillar data is needed/involved.

**Comment by pgporada** [comment]
I'm seeing this even with quotes around the value.
```
etcd:
  service:
    initial_cluster: 'etcd0=https://127.0.0.1:2380'
```

The workaround solution was to change from this
```
etcd_config:
  file.managed:
          - name: {{ etcd.config_path }}
          - template: jinja
          - mode: 644
          - user: root
          - group: root
          - defaults:
              etcd: {{ etcd }}
```

to putting the pillar values directly into the template instead which works
`/etc/etcd/etcd.conf.yml`
```
 {%- from "etcd/map.jinja" import etcd with context %}
# This is the configuration file for the etcd server.

# Human-readable name for this member.
name: '{{ etcd.name }}'
```
