### ISSUE TITLE
Verbosity flag for djangomod's collectstatic

### ISSUE THREAD

**Issue by 0xCMP** [saltstack/salt#46940]
### Description of Issue/Question
I'd like to add a verbosity option so in my state result collectstatic doesn't print out so much information unless it failed.

### Setup
```
project-collectstatic:
  module.run:
    - name: django.collectstatic
    - settings_module: Project.settings
    - bin_env: {{ pg('home') }}
    - pythonpath: {{ pg('home') }}/project
    - onchanges:
      - git: project-git
      - virtualenv: project-virtualenv

    - require:
      - git: project-git
      - virtualenv: project-virtualenv
      - file: {{ pg('home') }}/static
      - file: project-django-config
```

I'm willing to put together a PR which lets you add `--verbosity 0` as specified in this django doc: https://docs.djangoproject.com/en/1.7/ref/contrib/staticfiles/

I linked to the old version of django (1.7) to show how this has been around and should be supported for many versions of django. Although it doesn't say on that page you can use `verbosity` with `./manage.py collectstatic`, I have tested it and it works.
