### ISSUE TITLE
Slack engine groups error

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#46947]
### Description of Issue/Question
Default groups is always used instead of my custom group. So the command fail due to permissions issue:

```
2018-04-08 12:31:07,974 [salt.loaded.int.engines.slack:224 ][DEBUG   ][22582] Got the groups: {u'default': {u'targets': {}, u'commands': set([]), u'default_target': {}, u'users': set([]), u'aliases': {}}}
```

Any advices? Is wrong my configuration?

Thanks
### Setup
```
engines:
  - slack:
      token: 'xoxb-xxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx'
      control: True
      fire_all: False
      groups_pillar_name: 'slack_engine:groups_pillar'
      groups:
        my_custom_group:
          users:
            - my_user
        commands:
          - test.ping
          - cmd.run
          - list_jobs
          - list_commands
        aliases:
          list_jobs:
            cmd: jobs.list_jobs
          list_commands:
            cmd: pillar.get salt:engines:slack:valid_commands target=saltmaster tgt_type=list
        default_target:
          target: saltmaster
          tgt_type: glob
        targets:
          test.ping:
            target: '*'
            tgt_type: glob
          cmd.run:
            target: saltmaster
            tgt_type: list
```
### Steps to Reproduce Issue
Configure the slack engine and try to run some commands from slack

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by Giandom** [comment]
Solved. Indentation of the first configuration in the documentation is not well indented:

From doc:
```
engines:
  - slack:
      token: 'xoxb-xxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx'
      control: True
      fire_all: False
      groups_pillar_name: 'slack_engine:groups_pillar'
      groups:
        default:
          users:
            - *
        commands:
          - test.ping
          - cmd.run
          - list_jobs
          - list_commands
        aliases:
          list_jobs:
            cmd: jobs.list_jobs
          list_commands:
            cmd: pillar.get salt:engines:slack:valid_commands target=saltmaster tgt_type=list
        default_target:
          target: saltmaster
          tgt_type: glob
        targets:
          test.ping:
            target: '*'
            tgt_type: glob
          cmd.run:
            target: saltmaster
            tgt_type: list
```
Working config:
```
engines:
  - slack:
      token: 'xoxb-xxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx'
      control: True
      fire_all: False
      groups_pillar_name: 'slack_engine:groups_pillar'
      groups:
        default:
          users:
            - *
          commands:
            - test.ping
            - cmd.run
            - list_jobs
            - list_commands
          aliases:
            list_jobs:
              cmd: jobs.list_jobs
            list_commands:
              cmd: pillar.get salt:engines:slack:valid_commands target=saltmaster tgt_type=list
          default_target:
            target: saltmaster
            tgt_type: glob
          targets:
            test.ping:
              target: '*'
              tgt_type: glob
            cmd.run:
              target: saltmaster
              tgt_type: list
```
