### ISSUE TITLE
win_snmp module bypasses group policy settings

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#46981]
### Description of Issue/Question
When retrieving values from the SNMP configuration `win_snmp` always retrieves values from the registry which is not correct. Windows allows configuring the daemon through the service agent and through group policy, in my case local group policy. 

The problem comes when you configure the agent as above and then query the settings with `salt '<target minion>' win_snmp.get_community_names`. Even though the agent settings have been overwritten by the group policy Salt still returns the original configured community name pulling it directly from a registry setting. 

### Setup

1. Enable the SNMP service in Windows Server manager [Instructions here](https://support.microsoft.com/en-us/help/324263/how-to-configure-the-simple-network-management-protocol-snmp-service-i)
2. Follow above instructions to configure a community string
3. Configure a new community string through group policy 
4. Check the agent settings through the windows service manager
  * These should now read the new community string set through group policy
  * May require a `gpupdate /force` from powershell to update immediately
5. Query the community name with the command provided above
  * This will return the originally configured community string set manually through the agent configuration

### Versions Report
```
    Salt Version:
               Salt: 2017.7.2
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
