### ISSUE TITLE
Setting numerical uid:gid on symlink fails is uid is not from local user

### ISSUE THREAD

**Issue by RealMurphy** [saltstack/salt#47032]
### Description of Issue/Question

We are running a couple of NFS file servers serving user specific directories to "external" users, i.e. these directories and objects there-in have UID:GID of that user, but this particular user does not necessarily exist on the file server.

With this state (from `state.show_sls`):
```
zfs-user.name-/public_html-WWW:
    file:
    - name: /srv/user.name/public_html
    - target: WWW
    - user: 43098
    - group: 5100
    - symlink
    - order: 10032
    __sls__: atlas.server.work
    __env__: base
```

it will create the symlink correctly, but this state will consistently fail due to [uid to user mapping](https://github.com/saltstack/salt/blob/17e5a568bcd13d2b866f86512f9a4aa519392bd5/salt/modules/file.py#L3607).

Obviously, one can work around with a shell command performing this action or add custom checks, but I think it ought to be possible to specify a numeric UID/GID, don't you think?

### Versions Report
```
salt-call --versions-report
Salt Version:
           Salt: 2017.7.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4 
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-core any opinions here?

**Comment by RealMurphy** [comment]
Yeah, I think something like `remote_user` with default of `False` or the inverse `local_user` with a default if `True` would be a nice addition.

As I'm not really fluent with Python (reading is usually fine), do you want me to tinker a patch together or shall I wait for a proposed patch for testing?

**Comment by gtmanfred** [comment]
I have marked it as a feature request, but usually the fastest way to get stuff like this into salt is to contribute it yourself.

If you would try and make a PR against the develop branch as it is a feature, and we will review it and make any suggestions there.

If you need any help, there is a #develop channel on the Community Slack https://github.com/saltstack/salt#get-saltstack-support-and-help

Thanks,
Daniel

**Comment by RealMurphy** [comment]
Hi again,

I've tried to come up with a minimal state file to check if my messing with the code actually does the right thing(TM) and I found this peculiar behavior. State file (group named lvc gid 5100 exists locally for other reasons):

```
---
test-symlink:
  file.symlink:
    - name: /tmp/salt-test
    - target: /tmp/salt-target
    - user: 26322
    - group: lvc

test-symlink2:
  file.symlink:
    - name: /tmp/salt-test2
    - target: salt-target2
    - user: 21666
    - group: 5100
```


result:
```salt HOST state.apply link              
HOST:
----------
          ID: test-symlink
    Function: file.symlink
        Name: /tmp/salt-test
      Result: True
     Comment: Created new symlink /tmp/salt-test -> /tmp/salt-target
     Started: 12:33:48.536723
    Duration: 38.752 ms
     Changes:   
              ----------
              new:
                  /tmp/salt-test
----------
          ID: test-symlink2
    Function: file.symlink
        Name: /tmp/salt-test2
      Result: False
     Comment: Created new symlink /tmp/salt-test2 -> salt-target2, but was unable to set ownership to 21666:5100
     Started: 12:33:48.575582
    Duration: 17.939 ms
     Changes:   
              ----------
              new:
                  /tmp/salt-test2

Summary for HOST
------------
Succeeded: 1 (changed=2)
Failed:    1
------------
Total states run:     2
Total run time:  56.691 ms
ERROR: Minions returned with non-zero exit code
```

It does work, if I specify a gid which does not belong to a group on the minion. Therefore, will try to understand why *only* the case fails where gid is given in the state file and local group with that gid is already defined.
