### ISSUE TITLE
Pillars aren't evaluated when alias is passed in Slack Engine

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#47047]
### Description of Issue/Question
Pillars aren't evaluated when alias is passed in Slack Engine.

As workaround I've added these lines of code where @garethgreenaway done the last commit at line 354:

```
args, kwargs = self.parse_args_and_kwargs(cmdline)
use_cmdline = self.commandline_to_list(permitted_group[1]['aliases'][cmdline[0]].get('cmd', ''), '')
            if 'pillar' in kwargs:
                use_cmdline.append("pillar="+kwargs['pillar'])
```

But I think there is a best way to do it.
Advices?

### Setup
Slack Engine Conf:
```
    engines:
      - slack:
          token: 'xoxb-xxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx'
          control: True
          fire_all: False
          groups_pillar_name: 'slack_engine:groups_pillar'
          groups:
            default:
              users:
                - *
              commands:
                - test.ping
                - cmd.run
                - test
              aliases:
                test:
                  cmd: state.apply test target=master
```

Test state:
```
#!pyobjects
my_pillar = pillar('my_pillar')
Cmd.run("echo " + my_pillar)
```
### Steps to Reproduce Issue
From slack:
```
!test pillar='{"my_pillar": "test"}'
```
### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
