### ISSUE TITLE
Preserve color output in cmd.run

### ISSUE THREAD

**Issue by silenius** [saltstack/salt#47050]
Hello,

I'm busy to integrate Saltstack with Gitlab CI/CD and I wondered if there was a way to preserve color codes in a cmd.run state ?

Currently it outputs the following:

![firefox_screenshot_2018-04-13t12-34-35 905z](https://user-images.githubusercontent.com/1225348/38736581-c7dc6898-3f2c-11e8-80c5-1a21e47d5fe3.png)

which is ugly :(

### Setup
```sls
{{ cfg.name }}_list_pylint:
  cmd.run:
    - name: find {{ cfg.repo.clone_dir }} -type f -name "*.py" -print0|xargs -0 {{ cfg.venv.python }} -m pylint -f colorized || exit 0
    - cwd: {{ cfg.repo.clone_dir }}
    - runas: {{ cfg.user }}
    - use_vt: True
    - require:
      - pip: {{ cfg.name }}_lint_pkg
```
### Versions Report

```
salt% salt --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.5.2
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan  8 2018, 23:05:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.3
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 10.3-RELEASE
         system: FreeBSD
        version: Not Installed
```
