### ISSUE TITLE
Issue with cron.file

### ISSUE THREAD

**Issue by skob** [saltstack/salt#47063]
### Description of Issue/Question
Getting errors when running cron.file based state file in 2018.3.0
It was working without issue in 2017.7.3
The file is present in the location specified - `base/files/cron.tpl`

### Setup
```
cat ./roles/cron/init.sls
crontab:
  cron.file:
    - name: salt://files/cron.tpl
    - user: www-data
    - template: jinja
```
```
cat ./files/cron.tpl
*/15 *	* * *		script
```

### Steps to Reproduce Issue
```
salt-run manage.versions
Master:
    2018.3.0
Up to date:
    ----------
    backend:
        2018.3.0
```

```
salt backend state.apply roles.cron test=True
backend:
----------
          ID: crontab
    Function: cron.file
        Name: salt://files/cron
      Result: None
     Comment: The following values are set to be changed:
              diff: ---
              +++
              @@ -1,6 +1 @@
              -*/15 *	* * *	script
     Started: 14:15:38.870340
    Duration: 100.314 ms
     Changes:
```

```
salt backend state.apply roles.cron
backend:
----------
          ID: crontab
    Function: cron.file
        Name: salt://files/cron
      Result: False
     Comment: Source file salt://files/cron not found
     Started: 14:02:40.721816
    Duration: 1108.664 ms
     Changes:
```

```
salt-run fileserver.file_list | grep files/cron
- files/cron
```
```
salt backend cp.list_master | grep files/cron.tpl
    - files/cron.tpl
```

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-38-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

related to #38372
