### ISSUE TITLE
pip 10.0.0 can not import pip.req

### ISSUE THREAD

**Issue by pcjeff** [saltstack/salt#47116]
### Description of Issue/Question

reference: https://github.com/saltstack/salt/blob/develop/salt/states/pip_state.py
In pip_state.py line 44, salt seems to import pip.req.
However, in pip latest version 10.0.0, there is no req module.
```
$ pip --version
pip 10.0.0 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
$ python -c "import pip.req" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named req
```
Most states requiring pip and automatically install the latest pip (10.0.0).
This caused all states which require pip failed. 
I ran into one of them when I tried to run highstate to install docker on my minions.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
In top.sls
```
 'minion':
  - docker
```
I use docker-formula from https://github.com/saltstack-formulas/docker-formula.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
$ salt '*' state.highstate saltenv=base -l debug

```
----------
          ID: compose-pip
    Function: pip.installed
        Name: pip
      Result: False
     Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
     Started: 09:07:54.195138
    Duration: 1.124 ms
     Changes:
----------
          ID: compose
    Function: pip.installed
        Name: docker-compose
      Result: False
     Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
     Started: 09:07:54.196514
    Duration: 1.293 ms
     Changes:
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
On salt master:
Salt Version:
           Salt: 2018.3.0
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.13.0-135-generic
         system: Linux
        version: Ubuntu 14.04 trusty

On salt minion:
ubuntu@my-intstance:~$ salt-minion --versions-report
Salt Version:
           Salt: 2018.3.0
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-1052-aws
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by JackyTung** [comment]
I encounter the same issue.
my salt-master & salt-minion version is also 2018.3.0

but I cannot install pip successfully,
my .sls is

```
python-pip:                                                                                                        
  pkg.installed:                                                                                              
    - reload_modules: true

upgrade-pip:                                                                                                      
  pip.installed:                                                                                        
    - name: "pip"                                                                                      
    - upgrade: True
```

and the error msg is:

```
----------                                                                                                         
          ID: upgrade-pip                                                                                         
    Function: pip.installed                                                                                        
        Name: pip                                                                                             
      Result: False                                                                                              
     Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.                                                        
     Started: 03:38:15.537782                                                                                     
    Duration: 0.746 ms                                                                                           
     Changes
```
