### ISSUE TITLE
Vault module problem in 2018.3.0

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#47124]
### Description of Issue/Question
vault.read_secret fails when 2017 minion runs against a 2018.3 salt-master. 

Minion:
```
[ERROR   ] Failed to get token from master! Response is not a dict: Exception occurred in runner vault.generate_token: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
        data['return'] = self.functions[fun](*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 46, in generate_token
        _validate_signature(minion_id, signature, impersonated_by_master)
      File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 129, in _validate_signature
        'Could not validate token request from {0}'.format(minion_id)
    AuthenticationError: Could not validate token request from **MINION-ID**
```

And master logs sometimes show 
```
2018-04-17 16:17:45,168 [salt.loaded.ext.utils.vault:45  ][ERROR   ][9979] Failed to get token from master! An error was returned: list indices must be integers, not unicode
2018-04-17 16:17:45,169 [salt.loaded.ext.module.vault:47  ][ERROR   ][9979] Failed to read secret! CommandExecutionError: {u'error': u'list indices must be integers, not unicode'}
```

In trying to troubleshoot the _validate_signature function, I added debug lines to print out the minion signature and got:
```
2018-04-17 16:26:06,114 [salt.loaded.int.runners.vault:126 ][ERROR   ][9990] Validating signature for **MINION-ID**
2018-04-17 16:26:06,115 [salt.loaded.int.runners.vault:128 ][ERROR   ][9990] Got signature q����r�"w��|��A����f�x�RO-����kc6�   ݨS6]c�֯�q�ӑ�70�@%5�"�\�=gE̓�/�fEp�?JI*����nݶQ";�߭��dU�9�#��C�[$� ���7�~(j�S�4#�4�M|L���?�u�.uT�T�~Y�~�
�4�ňʅhkH���E�          ,�j�`=   � b�!d$�t�O�.)sΩ,��H
```

At this stage I'm guessing there is an issue with the strings being passed, and the recent unicode updates from 2018. 

<del>Additionally, to get this far, I had to correct some typos in the vault runner code for which I'll submit a PR. </del>
Corrected recently in https://github.com/saltstack/salt/commit/01a5b88e7b71b109b4708f74e1796e88eea67bf7

**Comment by Ch3LL** [comment]
ping @terminalmage any ideas here when working with new salt-master and lower version of salt-minion?

**Comment by mchugh19** [comment]
More investigation has narrowed the issue to the validate_signature call itself. Not sure why it works for 2018 minions but not 2017 ones.

**Comment by terminalmage** [comment]
Duplicate of https://github.com/saltstack/salt/issues/46864, already fixed in 01a5b88.

**Comment by mchugh19** [comment]
That wasn't the issue. After correcting the log.debug line, we are unable to perform vault lookups on 2017 minions due to not being able to validate signatures.

**Comment by terminalmage** [comment]
OK, I've reopened it. Can someone who is familiar with vault take another look? @dmurphy18 @gtmanfred

**Comment by mchugh19** [comment]
Seeing the related ticket #47135, we tried removing the m2crypto package, and now vault.read_secret commands work properly from our minion. 

```
salt **MINION-ID** pkg.remove m2crypto
**MINION-ID**:
    ----------
    m2crypto:
        ----------
        new:
        old:
            0.21.1-17.amzn2.0.2

# salt-call --versions
**MINION-ID**:
    Salt Version:
               Salt: 2018.3.0

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (default, Mar 16 2018, 18:20:07)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist:
             locale: ascii
            machine: x86_64
            release: 4.9.76-38.79.amzn2.x86_64
             system: Linux
            version: Not Installed
```
