### ISSUE TITLE
pip.install broken on Windows minions with Python3 in path.

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#47146]
### Description of Issue/Question

Windows minions which have python3 installed as the default Python cannot install packages using the pip.install module or pip.installed state.

### Setup

The `win16` Vagrant box on [learn-salt](https://github.com/vernondcole/learn-salt) will show the error.
```
git clone https://github.com/vernondcole/learn-salt
cd learn-salt
join-bevy.bat
[ ... you will be asked to elevate privileges ... ]
This program can make this machine a simple workstation to join the bevy
or a Vagrant host, possibly hosting a bevy master.
Will the Bevy Master be a VM guest of this machine? [y/N]:y
#  ... (answer other prompts as appropriate) ...
vagrant up bevymaster
vagrant up win16
vagrant ssh bevymaster
```

Install Python3 for all users as the system default Python on a Windows machine
with the Python3 `pip.exe` in the search path.

### Steps to Reproduce Issue

Log in to the win16 VM. The `Administrator` user has password "vagrant".

Install Python 3.6 from [official source](http://python.org).

Select Install launcher for all users,
Select Add Python 3.6 to PATH.
Select Customize installation.
On the "Advanced Options" page, select "Install for all users".
Select the "Disable path length limit" option.

Shut down and restart the Salt Minion, or reboot the VM.
```
# (typing on the bevymaster machine)...
sudo salt win16 system.reboot 5 True

# (and after the minion is rebooted)...
sudo salt win16 pip.install romanclass
$ sudo salt win16 pip.install romanclass
win16:
    Passed invalid arguments to pip.install: escape_encode() argument 1 must be string, not unicode

        Install packages with pip
[... clip ...]
```

### Versions Report
````
sudo salt win16 cmd.run 'salt-call --versions-report'
win16:
    Salt Version:
               Salt: 2018.3.0

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.7
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393  Multiprocessor Free
```
