### ISSUE TITLE
TypeError: makedirs_() [...] for file.symlink and file.shortcut

### ISSUE THREAD

**Issue by asymetrixs** [saltstack/salt#47178]
Dear All,

I have a problem with file.symlink and file.shortcut:
```
file.symlink:
  - name: 'C:\ProgramData\Microsoft\Windows\Start Menu\test\link.lnk'
  - target: '{{ salt['environ.get']('PROGRAMFILES') }}\test\app.exe'
  - makedirs: True
```
Same happens for `file.shortcut`
```
Returns
TypeError: makedirs_() got an unexpected keyword argument 'user'
```
Running salt `2017.7.4` on Windows 7

Also referencing #42421
