### ISSUE TITLE
Running file.replace from scheduled job fails

### ISSUE THREAD

**Issue by soostdijck** [saltstack/salt#47180]
### Description of Issue/Question
I've got my scheduled jobs configured via the pillar, which seems to work fine for highstate runs. However I want to add a scheduled job so that I can edit the minion's motd file to clearly indicate that the minion is in blackout mode.
To get this working I white listed 'file.replace' inside the 'minion_blackout_whitelist' grain. The I've added a scheduled job in the pillar to edit the motd, that will be added when the minion_blackout grain is found (with a jinja if). However I'm getting a python error, pasted below.

#### /etc/salt/minion
```master: 192.168.50.10```

#### /etc/salt/master
```
state_events: True
presence_events: True
log_level: info
fileserver_events: False
pillar_merge_lists: True

# in the order they are searched:
fileserver_backend:
  - roots
  - git

file_roots:
  base:
    - /vagrant/salt/salt # this contains the vagrant specific top.sls pushed by vagrant
    - /export/formula-core
    - /export/formula-access
    - /export/formula-services

pillar_roots:
  base:
    - /export/pillar

decrypt_pillar_default: pgp
decrypt_pillar_delimiter: '|'

gitfs_provider: gitpython

extension_modules: /export/salt/extmods

state_output: changes
```

#### /export/pillar/top.sls
```
base:
  '*':
    - schedule
    - server_vars.{{ grains['id']|replace('.', '_') }} # translate the "." in the id to "_"
```

#### /export/pillar/schedule.sls
```
schedule:
  highstate:                    # Name of scheduled job
    function: state.highstate   # What funtion to run
    #state-verbose: False
    #cron: '*/4 * * * *'
    minutes: 30
    splay: 15
    maxrunning: 50              # only run one of this job at any time

  # This is "probably needed" because;
  # when in blackout mode highstate does not run, a highstate implies
  # a pillar_refresh. If you set the minion_blackout grain for blackout mode
  # we still need the pillar to be automatically updated.
  refresh_pillar:
    function: saltutil.refresh_pillar
    minutes: 10
    splay: 4
    maxrunning: 50

{%- if grains['minion_blackout'] is defined and grains['minion_blackout'] == True %}
  motd:
    function: file.replace # this function needs whitelisting in grain minion_blackout_whitelist
    minutes: 5
    splay: 4
    maxrunning: 50
    args:
      - '/etc/motd'
    kwargs:
      pattern: "foobar"
      repl: "!! SALT IS IN BLACKOUT MODE - This minion is currently not managed!"
      append_if_not_found: True
{%- endif %}
```

#### /etc/salt/grains
```
minion_blackout: true
minion_blackout_whitelist:
- grains.item
- grains.setval
- test.ping
- file.replace
- schedule.list
- schedule.run_job
```

### Steps to Reproduce Issue
master: `salt 'minion1*' schedule.run_job motd`
minion: `/var/log/salt/minion`
```
2018-04-19 14:04:38,912 [salt.utils.schedule:737 ][ERROR   ][22963] Unhandled exception running file.replace
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 704, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 2199, in replace
    if not __utils__['files.is_text'](path):
  File "/usr/lib/python2.7/site-packages/salt/utils/context.py", line 228, in __getitem__
    return self._dict()[key]
KeyError: u'files.is_text'
```

#### master
```Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

#### minion
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by gtmanfred** [comment]
This is fixed here.

https://github.com/saltstack/salt/pull/46520

It will be in the next releases.

**Comment by gtmanfred** [comment]
Same issue as #46512

**Comment by piersf** [comment]
Hi,

I have the below state:

```
/etc/sysconfig/jenkins:
  file.managed:
    - source: salt://path/to/state/file/jenkins
    - user: root
    - group: root
    - mode: 600
    - template: jinja
    - require:
      - pkg: jenkins
      - user: root
```

And when pushing to the minion, it fails with the below error:

```
----------
          ID: /etc/sysconfig/jenkins
    Function: file.managed
      Result: False
     Comment: Unable to manage file: u'files.is_text'
     Started: 17:28:12.303840
    Duration: 19.328 ms
     Changes:
----------
```

Master and Minion version: salt-minion 2018.3.0 (Oxygen)
OS: Amazon Linux AMI release 2018.03

Is this the same issue described above which is fixed by #46520 ?
