### ISSUE TITLE
boto_secgroup.present intermittently when run as part of an Orchestration state

### ISSUE THREAD

**Issue by MDPolaris** [saltstack/salt#47190]
### Description of Issue/Question
I have a state to create a security group as part of a larger orchestration state. The state fails fairly regularly during the orch run. I have tried to reproduce the issue while running the state manually with state.apply however it has not failed when executed as a standalone state. The result is a security group with the name specified, however the Security Group does not getted tagged with Name: <SG_NAME>. No rules are added to the group either. I reviewed this briefly with @gtmanfred in the slack channel and nothing jumped out as bad with the states. Here is the error produced:

>     nv-salt-syndic:
>     ----------
>               ID: cad_worker_sg
>         Function: boto_secgroup.present
>             Name: nv-wc-creo-stage-syndic-cli-test1-sg
>           Result: False
>          Comment: Attempt 1: Returned a result of "False", with the following comment: " Security group nv-wc-creo-stage-syndic-cli-test1-sg created. nv-wc-creo-stage-syndic-cli-test1-sg security group configuration could not be retrieved. nv-wc-creo-stage-syndic-cli-test1-sg security group configuration could not be retrieved. nv-wc-creo-stage-syndic-cli-test1-sg security group configuration could not be retrieved."
>                   Attempt 2: Returned a result of "False", with the following comment: "An exception occurred in this state: Traceback (most recent call last):
>                     File "/usr/lib/python2.7/site-packages/salt/state.py", line 1837, in call
>                       **cdata['kwargs'])
>                     File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1794, in wrapper
>                       return f(*args, **kwargs)
>                     File "/usr/lib/python2.7/site-packages/salt/states/boto_secgroup.py", line 184, in present
>                       key=key, keyid=keyid, profile=profile)
>                     File "/usr/lib/python2.7/site-packages/salt/states/boto_secgroup.py", line 240, in _security_group_present
>                       profile=profile)
>                     File "/usr/lib/python2.7/site-packages/salt/modules/boto_secgroup.py", line 398, in create
>                       created = conn.create_security_group(name, description, vpc_id)
>                     File "/usr/lib/python2.7/site-packages/boto/ec2/connection.py", line 3019, in create_security_group
>                       SecurityGroup, verb='POST')
>                     File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
>                       raise self.ResponseError(response.status, response.reason, body)
>                   EC2ResponseError: EC2ResponseError: 400 Bad Request
>                   <?xml version="1.0" encoding="UTF-8"?>
>                   <Response><Errors><Error><Code>InvalidGroup.Duplicate</Code><Message>The security group 'nv-wc-creo-stage-syndic-cli-test1-sg' already exists for VPC 'vpc-ID'</Message></Error></Errors><RequestID>83ff2c4b-8cda-4ab4-aae2-c3215ef3bce5</RequestID></Response>
>                   "
>                   An exception occurred in this state: Traceback (most recent call last):
>                     File "/usr/lib/python2.7/site-packages/salt/state.py", line 1837, in call
>                       **cdata['kwargs'])
>                     File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1794, in wrapper
>                       return f(*args, **kwargs)
>                     File "/usr/lib/python2.7/site-packages/salt/states/boto_secgroup.py", line 184, in present
>                       key=key, keyid=keyid, profile=profile)
>                     File "/usr/lib/python2.7/site-packages/salt/states/boto_secgroup.py", line 240, in _security_group_present
>                       profile=profile)
>                     File "/usr/lib/python2.7/site-packages/salt/modules/boto_secgroup.py", line 398, in create
>                       created = conn.create_security_group(name, description, vpc_id)
>                     File "/usr/lib/python2.7/site-packages/boto/ec2/connection.py", line 3019, in create_security_group
>                       SecurityGroup, verb='POST')
>                     File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
>                       raise self.ResponseError(response.status, response.reason, body)
>                   EC2ResponseError: EC2ResponseError: 400 Bad Request
>                   <?xml version="1.0" encoding="UTF-8"?>
>                   <Response><Errors><Error><Code>InvalidGroup.Duplicate</Code><Message>The security group 'nv-wc-creo-stage-syndic-cli-test1-sg' already exists for VPC 'vpc-ID'</Message></Error></Errors><RequestID>fd47a316-0a5e-479e-a131-1a39022b9ef4</RequestID></Response>
>          Started: 17:09:24.567103
>         Duration: 31451.466 ms
>          Changes:
> 
>     Summary for nv-salt-syndic
>     ------------
>     Succeeded: 0
>     Failed:    1
>     ------------
>     Total states run:     1
>     Total run time:  31.451 s

### Setup
Here is the rendered section of the Orch state that calls this state:
```
create_cadworker_sg:
  salt.state:
    - tgt: nv-salt-syndic
    - sls:
      - plm.cad_worker_sg
    - concurrent: True
    - pillar:
        sg_name: nv-wc-creo-stage-syndic-cli-test1-sg
        cad_worker_type: creo
        new_environment_id: SVC0002373
    - require:
      - salt: creo_cadworker_start_notify
```

Here is the rendered plm.cad_worker_sg state:
```
cad_worker_sg:
  boto_secgroup.present:
    - name: nv-wc-creo-ptcstg1-sg
    - description: nv-wc-creo-ptcstg1-sg
    - vpc_id: vpc-ID
    - rules:
      - ip_protocol: tcp
        from_port: 20
        to_port: 21
        cidr_ip:
          - 10.20.2.33/32
      - ip_protocol: tcp
        from_port: 601
        to_port: 601
        cidr_ip:
          - 10.20.2.33/32
      - ip_protocol: tcp
        from_port: 990
        to_port: 990
        cidr_ip:
          - 10.20.2.33/32
      - ip_protocol: tcp
        from_port: 5600
        to_port: 5600
        cidr_ip:
          - 10.20.2.33/32
      - ip_protocol: tcp
        from_port: 50000
        to_port: 50100
        cidr_ip:
          - 10.20.2.33/32
    - rules_egress:
      - ip_protocol: all
        from_port: -1
        to_port: -1
        cidr_ip:
          - 0.0.0.0/0
    - tags:
        Name: nv-wc-creo-ptcstg1-sg
        Owner: 'EMAIL'
        Customer: 'Mike Freitas'
    - region: us-east-1
    - retry:
        attempts: 3
        interval: 15
        until: True
```

### Steps to Reproduce Issue
salt-run state.orch orch_new_plm_environment 'pillar={KEY: VALUE}' -l debug

### Versions Report
I have tested on 2 versions with the same results (2017.7.1 and 2017.7.5):

Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
