### ISSUE TITLE
x509.private_key_managed broken after upgrade to 2018.3.0

### ISSUE THREAD

**Issue by MorphBonehunter** [saltstack/salt#47236]
### Setup
Testcase:
```
test_key:
    x509.private_key_managed:
        - name: /tmp/test.key
        - bits: 4096
        - passphrase: 'testpass'
        - cipher: aes_256_cbc

test_cert:
    x509.certificate_managed:
        - name: /tmp/test.crt
        - signing_private_key: /tmp/test.key
        - signing_private_key_passphrase: 'testpass'
        - CN: test.example.com
        - basicConstraints: "critical CA:true"
        - keyUsage: "critical cRLSign, keyCertSign"
        - subjectKeyIdentifier: hash
        - authorityKeyIdentifier: keyid,issuer:always
        - days_valid: 3650
        - days_remaining: 0
        - backup: True
        - require:
            - x509: test_key
```

### Steps to Reproduce Issue
1. run the testcase with 2017.7.5.
```
salt-call state.apply testcase 
local:
----------
          ID: test_key
    Function: x509.private_key_managed
        Name: /tmp/test.key
      Result: True
     Comment: File /tmp/test.key is in the correct state
     Started: 09:10:55.673916
    Duration: 33.431 ms
     Changes:   
----------
          ID: test_cert
    Function: x509.certificate_managed
        Name: /tmp/test.crt
      Result: True
     Comment: File /tmp/test.crt is in the correct state
     Started: 09:10:55.708052
    Duration: 19.844 ms
     Changes:   

Summary for local
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time:  53.275 ms
```
2. upgrade to 2018.3.0
3. re-run testcase with 2018.3.0.
```
salt-call state.apply testcase 
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1878, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1823, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 303, in private_key_managed
    name, bits=bits, passphrase=passphrase, new=new, overwrite=overwrite):
  File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 240, in _check_private_key
    'The provided passphrase cannot decrypt the private key.')
CommandExecutionError: The provided passphrase cannot decrypt the private key.

local:
----------
          ID: test_key
    Function: x509.private_key_managed
        Name: /tmp/test.key
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1878, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 303, in private_key_managed
                  name, bits=bits, passphrase=passphrase, new=new, overwrite=overwrite):
                File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 240, in _check_private_key
                  'The provided passphrase cannot decrypt the private key.')
              CommandExecutionError: The provided passphrase cannot decrypt the private key.
     Started: 09:13:58.553635
    Duration: 10.903 ms
     Changes:   
----------
          ID: test_cert
    Function: x509.certificate_managed
        Name: /tmp/test.crt
      Result: False
     Comment: One or more requisite failed: testcase.test_key
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    2
------------
Total states run:     2
Total run time:  10.903 ms
```

The error disappears if i downgrade back to 2017.7.5.

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 3.2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan  5 2018, 10:41:29)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.14.35-1-lts
         system: Linux
        version: Not Installed
```
