### ISSUE TITLE
inconsistent/broken diff output in testmode

### ISSUE THREAD

**Issue by MorphBonehunter** [saltstack/salt#47237]
### Description of Issue/Question
After upgrade to 2018.3.0 the diff output is interchanged in testmode.

### Setup
Testcase:
```
cat testcase/diff.sls:
test_config:
    file.managed:
        - name: /tmp/test.conf
        - source: salt://testcase/test.source

cat test.source:
test=false
```
### Steps to Reproduce Issue
1. prepare a ` /tmp/test.conf` with `test=true`
2. run `salt-call state.apply testcase.diff test=1`:
```
local:
----------
          ID: test_config
    Function: file.managed
        Name: /tmp/test.conf
      Result: None
     Comment: The file /tmp/test.conf is set to be changed
     Started: 09:44:01.780377
    Duration: 71.618 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1 +1 @@
                  -test=false
                  +test=true

Summary for local
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  71.618 ms
```
So it "seems" that the `test=false` line is removed and `test=true` gets inserted but as the actual content is `test=true` this is false...so the diff is in the wrong order.
The wrong diff isn't shown if you run it in "normal" mode `salt-call state.apply testcase.diff`:
```
local:
----------
          ID: test_config
    Function: file.managed
        Name: /tmp/test.conf
      Result: True
     Comment: File /tmp/test.conf updated
     Started: 09:47:05.254714
    Duration: 89.497 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1 +1 @@
                  -test=true
                  +test=false

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  89.497 ms
```
Here the diff shows that `test=true` is removed and `test=false` gets inserted.
Finaly the file is in the right condition:
```
cat /tmp/test.conf
test=false
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 3.2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan  5 2018, 10:41:29)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.14.35-1-lts
         system: Linux
        version: Not Installed
```
