### ISSUE TITLE
pkg.install fail with windows package

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#47247]
### Description of Issue/Question
Hi,
I'm trying to install a custom windows package but I get this error:
```
my minion:
    ----------
    my_exe:
        ----------
        install status:
            failed
```
That is strange because if I try to run the installer from a cmd it works.
Looking at Minion log I found that the command is failed with retcode: 1619.

Any advices?

### Setup
SLS:
```
my_exe:
  '7.11':
    installer: 'C:\my\path\setup-win64.exe'
    full_name: 'My Software'
    reboot: False
    install_flags: '/s /v"/qn /l*vx install.log DOWNLOAD_THIRD_PARTY=Yes INSTALLDIR=C:\my\path SPOTFIRE_WINDOWS_SERVICE=Create SERVER_FRONTEND_PORT=9090 SERVER_BACKEND_REGISTRATION_PORT=9080 SERVER_BACKEND_COMMUNICATION_PORT=9443'
    uninstaller: 'C:\my\path\setup-win64.exe'
    uninstall_flags: '/x /s /v/qn'
    locale: en_US
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.9
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
