### ISSUE TITLE
Hosts File - Windows - "Cannot perform string replacements on a binary file"

### ISSUE THREAD

**Issue by Silvenga** [saltstack/salt#47274]
### Description of Issue/Question

When attempting to modify the Window host file as a work-around for bug #47215, `file.blockreplace` fails with the following error:

```
          ID: Ensure host entries exists
    Function: file.blockreplace
        Name: C:\Windows\System32\drivers\etc\hosts
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1878, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 4378, in blockreplace
                  show_changes=show_changes
                File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 2518, in blockreplace
                  .format(path)
              SaltInvocationError: Cannot perform string replacements on a binary file: C:\Windows\System32\drivers\etc\hosts
     Started: 08:22:54.611000
    Duration: 16.0 ms
     Changes:
```

### Setup

```
Ensure host entries exists:
  file.blockreplace:
    - name: C:\Windows\System32\drivers\etc\hosts
    - content: "127.0.0.1 example.com"
    - marker_start: "# Start host entries - managed by Salt."
    - marker_end: "# End host entries."
    - append_if_not_found: True
```

### Steps to Reproduce Issue

Run the above state on a Windows minion.

### Versions Report

```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```
