### ISSUE TITLE
unless option not working the same way between file.managed and git.latest

### ISSUE THREAD

**Issue by amontalban** [saltstack/salt#47289]
### Setup
```sls
git_directory:
  file.directory:
    - name: /usr/local/www/directory
    - user: git
    - unless: test -d /usr/local/www/directory
```

```sls
source_code:
  git.latest:
    - name: git@github.com:user/repository.git
    - target: /usr/local/www/directory
    - user: git
    - unless: test -d /usr/local/www/directory/.git
```

The former generates the following output:
```
[INFO    ] Executing command ‘test -d /usr/local/www/directory' in directory ‘/root’
```
While the last one generates the following output:
```
[INFO    ] Executing command ‘test -d /usr/local/www/directory/.git’ as user ‘git’ in directory ‘/home/git’
```

So it seems that in the former it runs the `unless` command using *root* user while in the last one uses *git* user.
### Steps to Reproduce Issue
Explained above with simple states.

### Versions Report
```
Salt Version:
           Salt: 2017.7.5
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Apr  5 2018, 01:14:40)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: US-ASCII
        machine: amd64
        release: 10.4-RELEASE-p8
         system: FreeBSD
        version: Not Installed
```

**Comment by Ch3LL** [comment]
looks like the git state module has code that specifically checks for the `unless` option and the file state is relying on the salt/state.py which checks if a state includes an unless statement. 

ping @saltstack/team-core what is the behavior we would want to push towards here? Do we want to add more logic in the state module or the state.py where the logic of unless is handled as well. Also do we want this cmd runing as the user specified in the state?

**Comment by gtmanfred** [comment]
This is the expected behavior.

Back when state wide unless and onlyif were implemented, instead of changing the behavior of modules that already handled unless and onlyif, there was a function that was added called `mod_run_check`

https://github.com/saltstack/salt/blob/2017.7/salt/states/git.py#L3004

If a state module has one of those, then the check is assumed to be handled by the module itself, and the state level variable is not used.

This is documented here in the state requisites

https://docs.saltstack.com/en/latest/ref/states/requisites.html#overriding-checks

If you want to have the cmd.retcode run the unless command as the specified user, you can use the state level variable `runas` which puts the `runas` user into the `__context__` and then will be used for the `cmd.retcode` for the state level unless check.

```
git_directory:
  file.directory:
    - name: /usr/local/www/directory
    - user: git
    - runas: git
    - unless: test -d /usr/local/www/directory
```
