### ISSUE TITLE
salt-cloud freebsd minion install halts

### ISSUE THREAD

**Issue by dawidpogorzelski** [saltstack/salt#47300]
### Description of Issue/Question
When deploying a new freebsd instance in google cloud through salt-cloud the minion installation step halts waiting for confirmation input.

### Setup
```
some_gce_profile:
  provider: gce-config
  image: https://www.googleapis.com/compute/v1/projects/freebsd-org-cloud-dev/global/images/freebsd-11-2-prerelease-amd64-2018-04-20
  size: n1-standard-1
  network: somenetwork
  subnetwork: somesubnet
  tags: '["sometag"]'
  deploy: True
  location: europe-west1-c
  external_ip: "ephemeral"
  delete_boot_pd: True
  use_persistent_disk: True
  delete_sshkeys: True
```

### Steps to Reproduce Issue
`salt-cloud -l all -p some_gce_profile somename`

```[DEBUG   ] Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    940 B   0.9kB/s    00:01    
Fetching meta.txz: 100%    940 B   0.9kB/s    00:01    txz:   0%
Fetching packagesite.txz:   0%
Fetching packagesite.txz: 100%    6 MiB   6.5MB/s    00:01    
Fetching packagesite.txz: 100%    6 MiB   6.5MB/s    00:01
Processing entries:   7%[DEBUG   ] Processing entries:   0%
Processing entries:  16%[DEBUG   ] 
Processing entries:  26%[DEBUG   ] 
Processing entries:  35%[DEBUG   ] 
Processing entries:  42%[DEBUG   ] 
Processing entries:  51%[DEBUG   ] 
Processing entries:  60%[DEBUG   ] 
Processing entries:  69%[DEBUG   ] 
Processing entries:  77%[DEBUG   ] 
Processing entries:  85%[DEBUG   ] 
Processing entries:  94%[DEBUG   ] 
Processing entries: 100%
FreeBSD repository update completed. 31537 packages processed.
Processing entries: 100%
FreeBSD repository update completed. 31537 packages processed.
All repositories are up to date.
[DEBUG   ] All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	py27-msgpack: 0.5.6

Number of packages to be installed: 1

71 KiB to be downloaded.

Proceed with this action? [y/N]: [DEBUG   ] The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	py27-msgpack: 0.5.6

Number of packages to be installed: 1

71 KiB to be downloaded.

Proceed with this action? [y/N]:
```

### Versions Report
```Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.5.2
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan  2 2018, 01:25:01)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p8
         system: FreeBSD
        version: Not Installed
