### ISSUE TITLE
Specify the returner as a state argument

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#47330]
This would allow for individual states to use a specific returner without the need to apply that to all states via the `return` minion config option. For example:

```yaml
foo:
  file.managed:
    - name: /etc/foo.conf
    - source: salt://foo.conf
    - returner: slack
```
