### ISSUE TITLE
__slots__ not passing parameter checks (like "... is not an absolute path")

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#47352]
Based on #46516 and #47351

We tried to use the "- name" parameter instead of the state id such as:

```yaml
tunnel_authorized_keys:
  file.managed:
    - name: __slot__:salt:tbz.get_authorized_keys_path(tunnel)
    - source: salt://tunnel/files/.ssh/authorized_keys
    - makedirs: True
    - user: tunnel
```

Now, we get the following error:
```yaml
salt:/srv # salt-ssh minion state.sls tunnel.service
minion:
----------
          ID: tunnel_authorized_keys
    Function: file.managed
        Name: __slot__:tbz:get_authorized_keys_path(tunnel)
      Result: False
     Comment: Specified file __slot__:tbz:get_authorized_keys_path(tunnel) is not an absolute path
     Started: 10:48:35.852204
    Duration: 1.417 ms
     Changes:   
```

That's the content of /srv/salt/_modules/tbz.py
```python
def get_authorized_keys_path(username):
    return '{0}/.ssh/authorized_keys'.format(__salt__['user.info'](username).home)
```

We use salt-ssh.
