### ISSUE TITLE
Document how to avoid re-downloading large files

### ISSUE THREAD

**Issue by hathawsh** [saltstack/salt#47373]
I'm using `salt.states.file.managed` to download ISO files from the Internet (to create a PXE boot server). I noticed today that Salt re-downloads the ISO files every time I run `state.highstate` for hash verification. I want to avoid re-downloading to save time and not waste mirror bandwidth. I thought about using skip_verify, patching Salt, or writing my own module, but then I realized there's a clean solution that I thought should be documented for everyone: instead of enabling skip_verify, the user should list the target file as the first source file.

For example, this is bad because it re-downloads on every `state.highstate` run:

```
  /var/www/html/centos7.iso:
    file.managed:
      - source: http://mirror.example.com/centos7.iso
      - source_hash: sha256=abcd1234
```

A clean solution is to add the target as the first source:

```
  /var/www/html/centos7.iso:
    file.managed:
      - source:
        - file:/var/www/html/centos7.iso
        - http://mirror.example.com/centos7.iso
      - source_hash: sha256=abcd1234
```

This way, if the file already exists and is correct, Salt won't try to download it again, even for hash verification. This solution is an alternative to `skip_verify`, so I think it should be spelled out in the documentation of the `skip_verify` option of `salt.state.file.managed`. This solution is also preferred over using `file.cached` instead of `file.managed` because it lets me continue to check the file hash on the filesystem. The only possible downside is that I suspect Salt computes the hash twice, once when evaluating the source, and once when evaluating the target. That's OK for now.

I would be happy to provide a documentation patch.
