### ISSUE TITLE
Error in module/file.py's get_diff function

### ISSUE THREAD

**Issue by mcd1992** [saltstack/salt#47376]
### Description of Issue/Question
The get_diff function in module/file.py is throwing an error when it hits the default return with a out of scope variable.

```
[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 2598, in managed
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 5256, in manage_file
    show_changes=show_changes, template=True)
  File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 5015, in get_diff
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
```

### Setup
```
# Copy our global CA certs from the pillar
{% for certname in pillar.cacerts %}
{{nsprefix}}_filemanaged_cacert_{{certname}}:
  file.managed:
    - name: {{ pillar.logstack.cacerts_store_path }}/{{ certname }}.crt
    - user: root
    - group: root
    - mode: 664
    - allow_empty: False
    - makedirs: True
    - dir_mode: 775
    - contents_pillar: cacerts:{{ certname }}
{% endfor %}
```

### Steps to Reproduce Issue
Use file.managed with a file that has no changes (may be limited to contents_pillar use case)

### Versions Report

Running masterless, untested with master<->client setup

```
Salt Version:
           Salt: 2018.3.0-2661-g24c5764
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 3.3.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
