### ISSUE TITLE
file.directory recurse extremely slow

### ISSUE THREAD

**Issue by ClaudiuLSH** [saltstack/salt#47393]
### Description of Issue/Question
After a recent update I noticed extremely long times when applying states and the culprit is file.directory.
An example output:
```
          ID: /home/user
    Function: file.directory
      Result: True
     Comment: Directory /home/user updated
     Started: 10:27:45.460493
    Duration: 87577.055 ms
     Changes:   
              ----------
              group:
                  user
              user:
                  user
```

### Setup
Part of sls file causing this problem:
```
/home/user:
  file.directory:
    - user: user
    - group: user
    - recurse:
      - user
      - group
```

### Steps to Reproduce Issue
Apply a state with file.directory recurse on a directory containing ~10.000 files.

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-4-amd64
         system: Linux
        version: debian 9.4 
```

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this. Here are my times when running at state file against a directory with 10,000 empty files(note: i created the files like so: `for i in {1..10000}; do echo $i; touch /home/tmp/tmp-${i}; done`):

```
2018.3.0:

real    0m10.283s
user    0m6.594s
sys     0m3.670s


 2017.7.4
 
real    0m5.684s
user    0m2.806s
sys     0m2.865s
```

Here is my state:

```
/home/tmp:
  file.directory:
    - user: saltdev
    - group: saltdev
    - recurse:
      - user
      - group
```

I have created a docker container for anyone to easily replicate this:

1. `docker run -it -v ~/git/salt/:/testing/ ch3ll/issues:47393 bash -c "bash -x ~/blah.sh"` (where git/salt is a local cloned git repo of satl)
