### ISSUE TITLE
Localized version of yum breaks pkg.install

### ISSUE THREAD

**Issue by shengis** [saltstack/salt#47404]
### Description of Issue/Question

I have a state to install erlang with a fixed version and that version have a wildcard "20.3*"
```
erlang-package-{{ package }}:
  pkg.installed:
    - name: {{ package }}
    - version: '{{ erlang.version }}*'
```

The minion fail with this error

```
----------
          ID: erlang-package-erlang
    Function: pkg.installed
        Name: erlang
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:
              errors:
                  - No version matching '20.3*' found for package 'erlang' (available: erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64, erlang.x86_64)
     Started: 16:10:17.682038
    Duration: 1613290.152 ms
     Changes:
```

As we can see in the error logs, package names are displayed instead of versions.

In **modules/yumpkg.py**, the function **_strip_headers()**, strip only english headers :

```
def _strip_headers(output, *args):
    if not args:
        args_lc = ('installed packages',
                   'available packages',
                   'updated packages',
                   'upgraded packages')
    else:
        args_lc = [x.lower() for x in args]
    ret = ''
    for line in salt.utils.itertools.split(output, '\n'):
        if line.lower() not in args_lc:
            ret += line + '\n'
return ret
```

But on my system, yum is in french : 

```
Executing command [u'yum', u'--quiet', u'--showduplicates', u'repository-packages', u'erlang', u'list', u'erlang'] in directory '/root'
(Pdb) print(out['stdout'])
Paquets install?s
erlang.x86_64                    20.2-1.el7.centos                       @erlang
Paquets disponibles
erlang.x86_64                    17.1-1.1.el7.centos                     erlang
erlang.x86_64                    17.1-3.el7.centos                       erlang
erlang.x86_64                    17.3-1.el7.centos                       erlang
erlang.x86_64                    17.4-1.el7.centos                       erlang
erlang.x86_64                    17.5-1.el7.centos                       erlang
erlang.x86_64                    17.5.3-1.el7.centos                     erlang
erlang.x86_64                    18.0-1.el7.centos                       erlang
erlang.x86_64                    18.1-1.el7.centos                       erlang
erlang.x86_64                    18.2-1.el7.centos                       erlang
erlang.x86_64                    18.3-1.el7.centos                       erlang
erlang.x86_64                    19.0-1.el7.centos                       erlang
erlang.x86_64                    19.1-1.el7.centos                       erlang
erlang.x86_64                    19.2-1.el7.centos                       erlang
erlang.x86_64                    19.3-1.el7.centos                       erlang
erlang.x86_64                    20.0-1.el7.centos                       erlang
erlang.x86_64                    20.1-1.el7.centos                       erlang
erlang.x86_64                    20.2-1.el7.centos                       erlang
erlang.x86_64                    20.3-1.el7.centos                       erlang
```

### Steps to Reproduce Issue

1. Use a localized version of yum on Centos 7.4
2. Install a package with a wildcard version

### Versions Report

yum: 3.4.3

```
Salt Version:
           Salt: 2018.3.0
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
