### ISSUE TITLE
Some Administrative Template policies are not properly set by lgpo

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#47436]
### Description of Issue/Question
Some administrative template policies are not properly set by the lgpo policy.  Requesting to "Disable" the policy results in the policy being "Enabled"

### Setup
2017.7

A state such as:
```
set_ie_proxy_per_user:
  lgpo.set:
    - computer_policy:
        "Windows Components\\Internet Explorer\\Make proxy settings per-machine (rather than per-user)": "Disabled"
```
Would result in the policy being "Enabled"

### Steps to Reproduce Issue
using 2017.7 apply the state above, the policy will be "Enabled" instead of "Disabled"

### Versions Report
issue exists in both 2017.7 and 2018.3
