### ISSUE TITLE
restarting filebeat hangs indefinitely

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#47445]
### Description of Issue/Question
When I run salt-call service.restart filebeat or salt minion_id service.restart filebeat, salt just hangs indefinitely.
I turned on the trace and found that it was 'subprocess.Popen' that hung.
So I tested it the following code from command line.
```
python3 -c 'import subprocess;subprocess.Popen(["/usr/sbin/service", "filebeat", "onerestart"])'
```

and it also hangs until you hit 'Enter' key.

### Setup
FreeBSD 11.1

### Steps to Reproduce Issue
Install beats-6.2.3 on FreeBSD 11.1 and run salt-call filebeat restart

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.3.12
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.5 (default, Apr  5 2018, 13:37:49)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p9
         system: FreeBSD
        version: Not Installed
```
