### ISSUE TITLE
Incorrect example of cloud.present

### ISSUE THREAD

**Issue by jryberg** [saltstack/salt#47450]
### Description of Issue/Question
I have been using salt-cloud without any states but I was just about to building states for salt cloud and found some inconsistency in the documentation.

According to this page: https://docs.saltstack.com/en/latest/topics/cloud/salt.html#cloud-present
> my-instance-name:
>   cloud.present:
>     - provider: my-ec2-config
>     - image: ami-1624987f
>     - size: 't1.micro'
>     - ssh_username: ec2-user
>     - securitygroup: default
>     - delvol_on_destroy: True

The provider should be referenced as " - provider: <name of the provider>" but according to state documentation found here: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cloud.html

>  salt.states.cloud.present(name, cloud_provider, onlyif=None, unless=None, opts=None, **kwargs)

It should be referred as cloud_provider

I tried to execute the state with "provider" and I got this error message:
`Missing parameter cloud_provider for state cloud.present`

If I replaced provider with cloud_provider it works perfectly fine. 

It seems the example found in https://docs.saltstack.com/en/latest/topics/cloud/salt.html#cloud-present should be updated to:
```
my-instance-name:
  cloud.present:
    - cloud_provider: my-ec2-config
    - image: ami-1624987f
    - size: 't1.micro'
    - ssh_username: ec2-user
    - securitygroup: default
    - delvol_on_destroy: True
```
