### ISSUE TITLE
file.managed source not found if in git submodule

### ISSUE THREAD

**Issue by tjgruber** [saltstack/salt#47463]
### Description of Issue/Question
When I run a state on a minion that uses file.managed, I get an error saying the following:
```
          ID: name1
    Function: file.managed
        Name: C:\ProgramData\path\to\filename1.ps1
      Result: False
     Comment: Source file salt://statename/files/submoduleFolder/filename1.ps1 not found
     Started: 12:07:16.872000
    Duration: 78.0 ms
     Changes:   
----------
          ID: name2
    Function: file.managed
        Name: C:\ProgramData\path\to\filename2.ps1
      Result: False
     Comment: Source file salt://statename/files/submoduleFolder/filename2.ps1 not found
     Started: 12:07:16.950000
    Duration: 16.0 ms
     Changes:   
```

### Setup
SLS File:
```
name1:
  file.managed:
    - name: C:\ProgramData\path\to\filename1.ps1
    - source: salt://statename/files/submoduleFolder/filename1.ps1
    - win_inheritance: True

name2:
  file.managed:
    - name: C:\ProgramData\path\to\filename2.ps1
    - source: salt://statename/files/submoduleFolder/filename2.ps1
    - win_inheritance: True
```
### Versions Report
Both the master and minion are running 2018.3.0
