### ISSUE TITLE
win_task.info on py3 throwing error, but works in py2

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#47479]
### Description of Issue/Question

Running salt <minion> task.info <task>` on a windows minion with the py3 version of salt.

In the following tests, `winion-0` is identical to `winion-1` except is running py3 instead of py2
```
[root@master ~]# salt winion-0 task.list_tasks
winion-0:
    - packer-595cd9b8-4c62-a317-dfa7-5f3c087bee3a
    - packer-595cdc83-7d48-44c8-43a8-24c67691a908
    - packer-595ce728-459d-9772-fed8-df9e784275ea
    - packer-595ce7d2-c982-62b5-6099-60c0baef9eb2
    - packer-595cf366-d7b4-c860-0626-d1860e2991cc
    - packer-595cf3de-d21d-2428-cb70-9ddc05a9ca2e
    - test-task
[root@master ~]# salt winion-0 task.info test-task
winion-0:
    Passed invalid arguments to task.info: 'dict_keys' object does not support indexing
```

```
[root@master ~]# salt winion-1 task.info test-task
winion-1:
    ----------
    actions:
        |_
          ----------
          action_type:
              Execute
          cmd:
              ping 127.0.0.1
    conditions:
        ----------
        ac_only:
            True
        run_if_idle:
            False
        run_if_network:
            False
        start_when_available:
            False
    enabled:
        True
    last_run:
        11/30/99 00:00:00
    last_run_result:
        Task has not yet run
    missed_runs:
        0
    next_run:
        Never
    settings:
        ----------
        allow_demand_start:
            True
        delete_after:
            False
        execution_time_limit:
            3 days
        force_stop:
            True
        multiple_instances:
            No New Instance
        restart_interval:
            False
        stop_if_on_batteries:
            True
        wake_to_run:
            False
    status:
        Ready
    triggers:
```

### Setup
Use Windows py3 version of 2018.3 and try to get info on task.

### Steps to Reproduce Issue
Use Windows py3 version of salt and try to get task info

### Versions Report
```
[root@master ~]# salt winion-0 test.versions
winion-0:
    Salt Version:
               Salt: 2018.3.0

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

```
[root@master ~]# salt winion-1 test.versions
winion-1:
    Salt Version:
               Salt: 2018.3.0

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393  Multiprocessor Free
```
