### ISSUE TITLE
Windows: pkg.latest state not updating packages.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#47484]
### Description of Issue/Question
This affects both py2 and py3

Installed Firefox 42.0, and used a state with pkg.latest to attempt to upgrade to the latest release. 

state returns 

```
winion-1:
----------
          ID: update-firefox
    Function: pkg.latest
        Name: firefox
      Result: False
     Comment: Package firefox failed to update.
     Started: 21:17:51.152000
    Duration: 19071.0 ms
     Changes:

Summary for winion-1
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  19.071 s
```

### Setup

Windows minion running 2018.3.0 with a state with pkg.latest and a package that needs updating. 

```
[root@master salt-winrepo-ng]# salt -G 'os:windows' pkg.list_pkgs
winion-1:
    ----------
    Microsoft Silverlight:
        5.1.50907.0
    Mozilla Maintenance Service:
        42.0
    Oracle VM VirtualBox Guest Additions 5.1.22:
        5.1.22.0
    firefox:
        42.0
    npp:
        7.5.6
    salt-minion:
        2018.3.0
```

```
[root@master salt-winrepo-ng]# salt -G 'os:windows' pkg.latest_version firefox
winion-1:
    59.0.3
```

```
[root@master salt-winrepo-ng]# cat /srv/salt/update.sls
update-firefox:
  pkg.latest:
    - name: firefox
```

### Steps to Reproduce Issue
See section above for setup. 

in the debug log line was all the rendering of the win_repo pacakges
afterwords was this 

```
[DEBUG   ] Latest installed version of firefox is 42.0
[DEBUG   ] Latest available version of package firefox is 59.0.3
[DEBUG   ] Upgrade of firefox from 42.0 to 59.0.3 is available
[DEBUG   ] Using existing pkg metadata db for saltenv 'base' (age is 0:00:00.047126)
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[DEBUG   ] Using existing pkg metadata db for saltenv 'base' (age is 0:00:00.062777)
[DEBUG   ] A version (None) already installed for package firefox
[DEBUG   ] Using existing pkg metadata db for saltenv 'base' (age is 0:00:00.078435)
[ERROR   ] Package firefox failed to update.
[INFO    ] Completed state [firefox] at time 21:10:23.051718 (duration_in_ms=16382.652)
```

After attempting:
```
winion-1:
    ----------
    Microsoft Silverlight:
        5.1.50907.0
    Mozilla Maintenance Service:
        42.0
    Oracle VM VirtualBox Guest Additions 5.1.22:
        5.1.22.0
    firefox:
        42.0
    npp:
        7.5.6
    salt-minion:
        2018.3.0
```

### Versions Report

```
winion-0:
    Salt Version:
               Salt: 2018.3.0

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

```
winion-1:
    Salt Version:
               Salt: 2018.3.0

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393  Multiprocessor Free
```
