### ISSUE TITLE
salt-ssh --extra-filerefs doesn't include any files if no refs in state files

### ISSUE THREAD

**Issue by mateiw** [saltstack/salt#47496]
### Description of Issue/Question

`--extra-filerefs` doesn't include any files if no `salt://` references are found in the state files to be applied.

### Setup
`/etc/salt/master`:
```yaml
file_roots:
  base:
    - /srv/salt
```
`/tmp/roster`:
```yaml
dev-minsles12sp2-1.tf.local:
    host: dev-minsles12sp2-1.tf.local
    user: root
    port: 22
    timeout: 180
```

### Steps to Reproduce Issue
`/srv/salt/testapply.sls`:
```yaml
call_apply:
  module.run:
    - name: state.apply
    - mods:
      - echo
```
`/srv/salt/echo.sls`:
```yaml
echo:
  module.run:
    - name: test.echo
    - text: "foo bar"
```
Include `echo.sls` using `--extra-filerefs`:
```bash
salt-ssh --roster-file=/tmp/roster --extra-filerefs="salt://echo.sls" dev-minsles12sp2-1.tf.local state.apply testapply
```
Result:
```
dev-minsles12sp2-1.tf.local:
----------
          ID: call_apply
    Function: module.run
        Name: state.apply
      Result: True
     Comment: Module function state.apply executed
     Started: 10:44:59.886226
    Duration: 39.912 ms
     Changes:   
              ----------
              ret:
                  - No matching sls found for 'echo' in env 'base'

Summary for dev-minsles12sp2-1.tf.local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  39.912 ms
```
State tarball content:
```bash
dev-minsles12sp2-1:/var/tmp/.root_2d8c28_salt # tar tzvf salt_state.tgz 
-rw-r--r-- salt/salt      3532 2018-05-06 11:05 roster_grains.json
-rw-r--r-- salt/salt       695 2018-05-06 11:05 pillar.json
-rw-r--r-- salt/salt       159 2018-05-06 11:05 lowstate.json
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.21-69-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

```
