### ISSUE TITLE
Using salt.loader to load custom state module

### ISSUE THREAD

**Issue by bartelsb** [saltstack/salt#47528]
### Description of Issue/Question
I'm attempting to write unit tests for a custom state module that I've written. The states do check for the existence of `__opts__['test']`, as described in the [salt instructions for custom states](https://docs.saltstack.com/en/develop/ref/states/writing.html#test-state). However, when I run my tests, I'm getting errors back saying that `__opts__` isn't defined. That makes sense because `__opts__` is injected by salt and never defined in my state module.

I've tried following the instructions for using the [salt loader interface](https://docs.saltstack.com/en/2017.7/ref/clients/index.html#salt-s-loader-interface) to load my module in a way that injects the `__opts__` object, but it's not working. My code for loading the module looks like this:
```
__opts__ = {'test': True, 'extension_modules': ''}
test_my_module = salt.loader.raw_mod(__opts__, 'my_module', None)
print(str(test_my_module))
```

I've tried replacing 'my_module' with 'test', and that works just fine. The issue seems to be that salt doesn't know where to find my module. Is there a recommended way of doing this? If there's an easier way to inject the `__opts__` object, please feel free to suggest that instead.

### Setup
I'm using the unittest library in Python, and simply calling `python -m unittest discover` to run my tests.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
I'm not sure if this is actually relevant or not since I'm running this outside of salt, but here's my output:
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.4 (default, Mar  9 2018, 23:15:03)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 17.5.0
         system: Darwin
        version: 10.13.4 x86_64
```

Any help is greatly appreciated! Thanks!
