### ISSUE TITLE
mac_service.disabled not correctly querying status

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#47577]
### Description of Issue/Question
When calling `salt-call --local status.disabled org.ntp.ntpd` if the service is loaded and running it returns false even though the service is disabled on mac.

To show an example:

Make sure the service is loaded:

```
jk-sierra-py3:testing root# launchctl load /System/Library/LaunchDaemons/org.ntp.ntpd.plist
```

Disable the service:

```
jk-sierra-py3:testing root# salt-call --local service.disable org.ntp.ntpd
local:
    True
jk-sierra-py3:testing root# 
```

But when we run `service.disabled` to check if its disabled it returns false:

```
jk-sierra-py3:testing root# salt-call --local service.disabled org.ntp.ntpd
local:
    False
jk-sierra-py3:testing root#
```

This is because we are using the command: `launchctl list org.ntp.ntp` to determine if the service has been disabled or not. The problem is just because you disabled a service does not necessarily mean it will be unloaded/stopped as well. 

This disabled function needs to use a different call such as `print-disabled` to determine if the service is actually disabled. 

From the launchctl manual:

```
     list [-x] [label]
              With no arguments, list all of the jobs loaded into launchd in three columns. The first column
              displays the PID of the job if it is running.  The second column displays the last exit status
              of the job. If the number in this column is negative, it represents the negative of the signal
              which stopped the job. Thus, "-15" would indicate that the job was terminated with SIGTERM.
              The third column is the job's label. If [label] is specified, prints information about the
              requested job.
```

```
     print-disabled domain-target
              Prints the list of disabled services in the specified domain.
```

So as you can from those definitions list will just show you which services are loaded not disabled. 

To show my point further that you can indeed have a service loaded on your system but disabled:

service is loaded:

```
jk-sierra-py3:testing root# launchctl list org.ntp.ntpd
{
        "EnableTransactions" = true;
        "LimitLoadToSessionType" = "System";
        "Label" = "org.ntp.ntpd";
        "TimeOut" = 30;
        "OnDemand" = true;
        "LastExitStatus" = 0;
        "PID" = 57105;
        "Program" = "/usr/libexec/ntpd-wrapper";
        "ProgramArguments" = (
                "/usr/libexec/ntpd-wrapper";
        );
};
```

check that it is enabled:

```
jk-sierra-py3:testing root# launchctl print-disabled system/org.ntp.ntpd | grep -i ntpd\"
        "org.ntp.ntpd" => false
```

(note: false means it is enabled)

disable the service:

```
jk-sierra-py3:testing root# launchctl disable system/org.ntp.ntpd
jk-sierra-py3:testing root# 
```

check if its disabled with launchctl list and it will still return information about the service even though its been disabled:

```
jk-sierra-py3:testing root# launchctl list org.ntp.ntpd
{
        "EnableTransactions" = true;
        "LimitLoadToSessionType" = "System";
        "Label" = "org.ntp.ntpd";
        "TimeOut" = 30;
        "OnDemand" = true;
        "LastExitStatus" = 0;
        "PID" = 57105;
        "Program" = "/usr/libexec/ntpd-wrapper";
        "ProgramArguments" = (
                "/usr/libexec/ntpd-wrapper";
        );
};
```

Now check the proper way with print-disabled adn we see its indeed been disabled:

```
jk-sierra-py3:testing root# launchctl print-disabled system/org.ntp.ntpd | grep -i ntpd\"
        "org.ntp.ntpd" => true
```

To further elaborate if you unload the service then launchctl list will not retunr anything:

```
jk-sierra-py3:testing root# launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist
jk-sierra-py3:testing root# 
```

```
jk-sierra-py3:testing root# launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist
jk-sierra-py3:testing root# launchctl list org.ntp.ntpd
Could not find service "org.ntp.ntpd" in domain for system
```

### Versions Report
should affect all versions

```
Salt Version:
           Salt: 2017.7.0-837-g98bd598

Dependency Versions:
           cffi: 1.5.0
       cherrypy: 4.0.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Aug 24 2016, 14:05:14)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 16.1.0
         system: Darwin
        version: 10.12.1 x86_64
```
