### ISSUE TITLE
Documentation error in description of watch_any

### ISSUE THREAD

**Issue by cfxegbert** [saltstack/salt#47574]
https://docs.saltstack.com/en/latest/ref/states/requisites.html

The example yaml for watch_any is:
````
apache2:
  service.running:
    - watch_any:
      - file: /etc/apache2/sites-available/site1.conf
      - file: /etc/apache2/sites-available/site2.conf
  file.managed:
    - name: /etc/apache2/sites-available/site1.conf
    - source: salt://apache2/files/site1.conf
  file.managed:
    - name: /etc/apache2/sites-available/site2.conf
    - source: salt://apache2/files/site2.conf
````

This yaml has a dictionary "apache2" with the key "file.managed" listed twice.
