### ISSUE TITLE
ext_pillar mysql problem

### ISSUE THREAD

**Issue by jpvis** [saltstack/salt#47585]
I'm trying to start ext_pillar with mysql module.
salt master config:

```
mysql:
  user: 'user'
  pass: 'pass'
  db: 'salt_pillars'
  host: '127.0.0.1'
  port: 3306

ext_pillar:
  - mysql:
      fromdb:
        query: 'SELECT proxytype, driver, host, username, password FROM devices WHERE device_name = %s'
        depth: 2
        as_list: True

ext_pillar_first: True
```

When I'm trying to check what data returned:

```
[root@saltmaster srv]# salt-run pillar.show_pillar
fromdb:
    ----------
```

Or  salt-proxy --proxyid=csr01 -l debug

In master debug I see:
```[INFO    ] Querying MySQL for information for csr01
[DEBUG   ] Using default for MySQL ssl
[DEBUG   ] ext_pillar MySQL: Return data: <salt.loaded.int.pillar.mysql.MySQLExtPillar object at 0x2f365d0>
```

Is anybody knows what is wrong ?

Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
