### ISSUE TITLE
x509.certificate_managed M2Crypto - Exception RSAError(bad password read)

### ISSUE THREAD

**Issue by dgengtek** [saltstack/salt#47591]
### Description of Issue/Question
My states are failing since updating my environment. I am clueless why they are failing now. I checked my git history of my states and did not change them since the last successfull state run(since my certificates are only 90 days valid). I would be glad if someone can help me out or point me the way to debug this.

The following exception is occuring.

```
ID: /etc/pki/vault.<snip>.cert.pem
Function: x509.certificate_managed
Result: False
Comment: An exception occurred in this state: Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/salt/state.py", line 1878, in call
    **cdata['kwargs'])
    File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1823, in wrapper
    return f(*args, **kwargs)
    File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 570, in
    certificate_managed
    'New': __salt__['x509.read_certificate'](certificate=certificate)}
    File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 544, in
    read_certificate
    cert = _get_certificate_obj(certificate)
    File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 357, in
    _get_certificate_obj
    text = get_pem_entry(text, pem_type='CERTIFICATE')
    File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 480, in
    get_pem_entry
    raise salt.exceptions.SaltInvocationError(errmsg)
    SaltInvocationError: PEM does not contain a single entry of type CERTIFICATE:
    bad password read
Started: 16:02:33.408143
Duration: 967.035 ms
Changes:
```

The exception is coming from these calls in that order if I trace it on my minion:
https://github.com/saltstack/salt/blob/v2018.3.0/salt/states/x509.py#L532
https://github.com/saltstack/salt/blob/v2018.3.0/salt/modules/x509.py#L1524
https://github.com/saltstack/salt/blob/v2018.3.0/salt/modules/x509.py#L1710
https://github.com/saltstack/salt/blob/v2018.3.0/salt/modules/x509.py#L707

Exception is an `RSAError(bad password read)` from M2Crypto. Tried following `m2.rsa.read_key `which is nowhere defined in M2Crypto(is this a C binding?).

### Setup
```
#/etc/minion.d/signing_policies.conf
x509_signing_policies:
  vault:                                                                                                                                                                                      
    - minions: <vault fqdn>                                                                                                                                                     
    - signing_private_key: /etc/pki/intermediate.key.pem                                                                                                                                      
    - signing_private_key_passphrase: <intermediate key passphrase>                                                                                                                               
    - signing_cert: /etc/pki/ca-chain.cert.pem                                                                                                                         
    - C: <snip>                                                                                                                                                                                   
    - ST: <snip>                                                                                                                                                                 
    - L: <snip>                                                                                                                                                                              
    - CN: vault.<snip>                                                                                                                                                    
    - basicConstraints: CA:false                                                                                                                                                              
    - keyUsage: keyEncipherment,digitalSignature,keyAgreement                                                                                                                                 
    - subjectKeyIdentifier: hash                                                                                                                                                              
    - authorityKeyIdentifier: keyid,issuer:always                                                                                                                                             
    - days_valid: 90                                                                                                                                                                          
    - copypath: /etc/pki/issued_certs/                                                                                                                                                        
    - extendedKeyUsage: serverAuth                                                                                                                                                            
    - nameConstraints: permitted                                                                                                                        
    - subjectAltName: DNS:<vault fqdn>
```

### Steps to Reproduce Issue
My minion 'vault' is getting the new certificate signed which is also ca server which signs the certificates in my environment.
[debug.txt](https://github.com/saltstack/salt/files/1991938/debug.txt)

I did already print the private key text and the passphrase which is being passed to M2Crypto `M2Crypto.RSA.load_key_string(text, callback=_passphrase_callback(passphrase))` and was able to successfully output the key by decrypting it with the given passphrase via openssl rsa.

### Versions Report
master:
previous salt version: 2017.7.4
```
Salt Version:                                                                                                                                                                                 
           Salt: 2018.3.0                                                                                                                                                                     
                                                                                                                                                                                              
Dependency Versions:                                                                                                                                                                          
           cffi: 1.6.0                                                                                                                                                                        
       cherrypy: unknown                                                                                                                                                                      
       dateutil: Not Installed                                                                                                                                                                
      docker-py: Not Installed                                                                                                                                                                
          gitdb: Not Installed                                                                                                                                                                
      gitpython: Not Installed                                                                                                                                                                
          ioflo: Not Installed                                                                                                                                                                
         Jinja2: 2.7.2                                                                                                                                                                        
        libgit2: 0.24.6                                                                                                                                                                       
        libnacl: Not Installed                                                                                                                                                                
       M2Crypto: 0.28.2                                                                                                                                                                       
           Mako: Not Installed                                                                                                                                                                
   msgpack-pure: Not Installed                                                                                                                                                                
 msgpack-python: 0.5.1                                                                                                                                                                        
   mysql-python: Not Installed                                                                                                                                                                
      pycparser: 2.14                                                                                                                                                                         
       pycrypto: 2.6.1                                                                                                                                                                        
   pycryptodome: 3.4.3                                                                                                                                                                        
         pygit2: 0.24.2                                                                                                                                                                       
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)                                                                                                                                       
   python-gnupg: 0.3.8                                                                                                                                                                        
         PyYAML: 3.11                                                                                                                                                                         
          PyZMQ: 15.3.0                                                                                                                                                                       
           RAET: Not Installed                                                                                                                                                                
          smmap: Not Installed                                                                                                                                                                
        timelib: Not Installed                                                                                                                                                                
        Tornado: 4.2.1                                                                                                                                                                        
            ZMQ: 4.1.4                
                                                                                                                                                  
                                                                                                                                                                                             
System Versions:                                                                                                                                                                              
           dist: centos 7.4.1708 Core                                                                                                                                                         
         locale: UTF-8                                                                                                                                                                        
        machine: x86_64                                                                                                                                                                       
        release: 3.10.0-693.21.1.el7.x86_64                                                                                                                                                   
         system: Linux                                                                                                                                                                        
        version: CentOS Linux 7.4.1708 Core
```      

minion:
previous salt version: 2017.7.4
previous m2crypto version: 0.27.0
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, May  4 2018, 19:54:23)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: armv7l
        release: 4.14.39-1-ARCH
         system: Linux
        version: Not Installed
```

**Comment by Ch3LL** [comment]
i'm wondering if this was related to the unicode work we did in the 2018.3 release. can you share the  sanitized version of your `x509.certificate_managed` state so i can try to replicate?

**Comment by dgengtek** [comment]
You can see the sanitized version in my attached file [debug.txt](https://github.com/saltstack/salt/files/1991938/debug.txt)
```

/etc/pki/vault.<snipped>.cert.pem:
  x509.certificate_managed:
    - ca_server: '<vault fqdn>'
    - signing_policy: 'vault'
    - public_key: '/etc/pki/vault.<snipped>.key.pem'
    - cn: vault.<snipped>
    - days_remaining: 30
    - days_valid: 90
    - backup: True
    - managed_private_key:
        name: /etc/pki/vault.<snipped>.key.pem
        bits: 2048
        backup: True

```

I just now did a rollback of salt to my previous version I used 2017.7.4 on the minion and the state ran successfully.

Here is the version report with the working minion now
```

Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, May  4 2018, 19:54:23)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: armv7l
        release: 4.14.39-1-ARCH
         system: Linux
        version: Not Installed

```
