### ISSUE TITLE
Critical bug - enable function in service.running mangles rc.conf for FreeBSD

### ISSUE THREAD

**Issue by sazaro** [saltstack/salt#47616]
### Description of Issue/Question

Version: Salt 2018.3.0 for both the Master and Minion.

Issue: The enable function of service.running is supposed to make sure a service is enabled in rc.conf. It edits the rc.conf file but completely mangles it and makes everything above the new edit into a single line of jumbled text. If the rc.conf has any syntax errors, **the FreeBSD system will not boot properly.** 

**Example of what rc.conf looks like before**

hostname="myhost.example.com"
defaultrouter="192.168.0.1"
sshd_enable="YES"
ntpd_enable="YES"
vboxnet_enable="YES"
snmpd_enable="YES"
salt_minion_enable="YES"

**Example of what it looks like after it enables nrpe3_enable="YES"**

hostname="myhost.example.com" defaultrouter="192.168.0.1" sshd_enable="YES" ntpd_enable="YES" vboxnet_enable="YES" snmpd_enable="YES"salt_minion_enable="YES"
nrpe3_enable="YES"

### Setup

A very simple state file which installs a package and attempts to add it to rc.conf using enable:True in service.running.

```
Install nrpe:
  pkg.installed:
    - name: nrpe3

Enable nrpe:
  service.running:
    - name: nrpe3
    - enable: True
```

### Steps to Reproduce Issue

1. Check your rc.conf first with cat to make sure it has some lines in it and it is properly formatted
2. Apply the above state - salt 'minion' state.apply nrpestate
2. Check your rc.conf again and it should be mangled. 

### Versions Report

Master

```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Apr  5 2018, 05:19:57)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 10.3-RELEASE
         system: FreeBSD
        version: Not Installed

```

Minion

```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Dec  5 2017, 20:43:15)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 10.3-RELEASE-p17
         system: FreeBSD
        version: Not Installed

```
