### ISSUE TITLE
Encrypted AWS root volumes

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#47623]
### Description of Issue/Question
Is it possible to specify an encypted root volume with Salt Cloud on AWS?

### Setup
for an AWS cloud profile I have the block_device_mappings:

```
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 12
      Ebs.VolumeType: gp2
```
Are these Ebs values passed through to AWS and adding something like Ebs.VolumeEncrypted: True 
will allow this to work, or does this require a code change
