### ISSUE TITLE
State Aggregate Breaks Requisites

### ISSUE THREAD

**Issue by doc987** [saltstack/salt#47628]
Setting ```aggregate: True``` (https://docs.saltstack.com/en/latest/ref/states/aggregate.html) for ```pkg``` can significantly reduce run time.  However, any requisites attached to pkg states seem to be lost.

**Package Repositories:** If, for example, a package requires a repository to be installed first, the package install can fail because it can get moved ahead of the repository install.  Neither setting the package install to ```require``` the repository install, nor setting the repository install to ```require_in``` the package install seems to help.  A workaround that does appear to succeed is setting ```order: 1``` on the repository install.

**Services:** Another example of an issue is when a package install requires a service restart.  The service won't get restarted because any requisite ties between the package install and the service are lost when ```aggregate``` is used.

This is related to #21312, which has been marked as stale, but the issue appears to persist.

**Comment by Ch3LL** [comment]
thanks for bringing this to our attention. Seems we still need to fix this. Also please feel free to submit a PR if you feel so inclined. 

Can you include a state example to help easily replicate this issue?

**Comment by doc987** [comment]
See below for an example of the repository issue.  Everything is shown together here, but the ```other_pkgs``` section may be in a different file from the other two.
```
other_pkgs:
  pkg.installed:
    - pkgs:
      - aaa
      - bbb
    - aggregate: True

zzz_repo:
  pkgrepo.managed:
    - name: zzz
    - humanname: ZZZ
    - baseurl: https://zzz.com/basepath
    - enabled: 1
    - gpgpcheck: 1
    - gpgkey: https://zzz.com/gpgkeyfile.gpg

zzz_pkg:
  pkg.installed:
    - name: zzz
```

The issue with services is another case where a problem can occur, but the source of the problem is the same.

**Comment by Ch3LL** [comment]
thanks for the example and re-opening this issue. ping @terminalmage might have some ideas here.

**Comment by terminalmage** [comment]
I see no requisites in the example provided.

**Comment by wildk1wi** [comment]
The aggregate also fails to manage the holds option correctly.
Test case:
```
linux_extra_package_bc:
    pkg.installed:
        - name: bc
        - hold: True
linux_extra_packages_installed:
    pkg.installed:
        - pkgs:
            - sendmail-cf
            - python-elasticsearch
            - mailx
linux_extra_packages_latest:
    pkg.latest:
        - pkgs:
            - kernel
            - salt-minion
```
Result when aggregate pkg is set in salt master.
```
[firewall1 ~]# salt-call state.apply testing.packages-test test=true
local:
----------
          ID: linux_extra_package_bc
    Function: pkg.installed
        Name: bc
      Result: None
     Comment: All specified packages are already installed.
              Package python-elasticsearch is set to be held..
              Package mailx is set to be held..
              Package sendmail-cf is set to be held..
              Package bc is set to be held.
     Started: 22:01:55.508198
    Duration: 741.996 ms
     Changes:   
----------
          ID: linux_extra_packages_installed
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 22:01:56.250410
    Duration: 16.955 ms
     Changes:   
----------
          ID: linux_extra_packages_latest
    Function: pkg.latest
      Result: True
     Comment: All packages are up-to-date (kernel, salt-minion).
     Started: 22:01:56.267535
    Duration: 10529.749 ms
     Changes:   

Summary for local
------------
Succeeded: 3 (unchanged=1)
Failed:    0
------------
Total states run:     3
Total run time:  11.289 s
```
Results when aggregate is not set in master
```
[firewall1 ~]# salt-call state.apply testing.packages-test test=true
local:
----------
          ID: linux_extra_package_bc
    Function: pkg.installed
        Name: bc
      Result: None
     Comment: All specified packages are already installed.
              Package bc is set to be held.
     Started: 22:07:26.236249
    Duration: 724.213 ms
     Changes:   
----------
          ID: linux_extra_packages_installed
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 22:07:26.960674
    Duration: 16.791 ms
     Changes:   
----------
          ID: linux_extra_packages_latest
    Function: pkg.latest
      Result: True
     Comment: All packages are up-to-date (kernel, salt-minion).
     Started: 22:07:26.977616
    Duration: 12189.18 ms
     Changes:   

Summary for local
------------
Succeeded: 3 (unchanged=1)
Failed:    0
------------
Total states run:     3
Total run time:  12.930 s
```

**Comment by jfoboss** [comment]
Will this issue be resolved?

**Comment by Ch3LL** [comment]
im not seeing any examples shared here with a require in them? can your states you are seeing this in when requisites aren't handled if aggregate is set?

**Comment by doc987** [comment]
The "requires" are described in the my first comment on this page (https://github.com/saltstack/salt/issues/47628#issue-322563536).  The example is in my second comment (https://github.com/saltstack/salt/issues/47628#issuecomment-388976808).  Having both `require` and `require_in` in the example wouldn't make sense.  If one were to insert either `require` *or* `require_in` into the example as described, then the issue can be seen.

**Comment by timwsuqld** [comment]
@Ch3LL Here is a test case I threw together (I run it in a clean docker container).
`google-cloud-sdk` isn't available until the repo is added. It causes the `other_pkgs` state to fail because it's not installable at that stage. Interesting enough the `google-cloud-sdk` state does end up running after the repo state, which isn't expected `aggregate` behaviour from my reading of the docs (unless there is something about running the individual states on failure?)

SLS
```
other_pkgs:
  pkg.installed:
    - pkgs:
      - byobu
    - aggregate: True

# Google Cloud SDK tools (Useful both on server and client)
google-cloud-repo:
  pkgrepo.managed:
    - humanname: Google Cloud SDK
    - name: deb https://packages.cloud.google.com/apt cloud-sdk main
    - file: /etc/apt/sources.list.d/google-cloud-sdk.list
    - key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg


google-cloud-sdk:
  pkg.installed:
    - require:
      - google-cloud-repo
```


```
RUN salt-call -V; apt-cache policy google-cloud-sdk; salt-call --local state.apply test-1; apt-cache policy google-cloud-sdk
 ---> Running in 76bde1865fba
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Apr 15 2020, 17:20:14)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ascii
        machine: x86_64
        release: 5.3.0-59-generic
         system: Linux
        version: Ubuntu 18.04 bionic
 
[ERROR   ] Command '[u'apt-get', u'-q', u'-y', u'-o', u'DPkg::Options::=--force-confold', u'-o', u'DPkg::Options::=--force-confdef', u'install', u'byobu', u'google-cloud-sdk']' failed with return code: 100
[ERROR   ] stdout: Reading package lists...
Building dependency tree...
Reading state information...
[ERROR   ] stderr: E: Unable to locate package google-cloud-sdk
[ERROR   ] retcode: 100
[ERROR   ] Problem encountered installing package(s). Additional info follows:

errors:
    - E: Unable to locate package google-cloud-sdk
local:
----------
          ID: other_pkgs
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - E: Unable to locate package google-cloud-sdk
     Started: 03:23:27.421034
    Duration: 25545.589 ms
     Changes:   
----------
          ID: google-cloud-repo
    Function: pkgrepo.managed
        Name: deb https://packages.cloud.google.com/apt cloud-sdk main
      Result: True
     Comment: Configured package repo 'deb https://packages.cloud.google.com/apt cloud-sdk main'
     Started: 03:23:52.969199
    Duration: 17268.011 ms
     Changes:   
              ----------
              repo:
                  deb https://packages.cloud.google.com/apt cloud-sdk main
----------
          ID: google-cloud-sdk
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: google-cloud-sdk
     Started: 03:24:10.238420
    Duration: 70484.675 ms
     Changes:   
              ----------
              google-cloud-sdk:
                  ----------
                  new:
                      298.0.0-0
                  old:
              python-crcmod:
                  ----------
                  new:
                      1.7-2build4
                  old:

Summary for local
------------
Succeeded: 2 (changed=2)
Failed:    1
------------
Total states run:     3
Total run time: 113.298 s
google-cloud-sdk:
  Installed: 298.0.0-0
  Candidate: 298.0.0-0
  Version table:
 *** 298.0.0-0 500
        500 https://packages.cloud.google.com/apt cloud-sdk/main amd64 Packages
        100 /var/lib/dpkg/status
     297.0.1-0 500
        500 https://packages.cloud.google.com/apt cloud-sdk/main amd64 Packages
     297.0.0-0 500
```
