### ISSUE TITLE
Unable to manage file: u'files.is_text'

### ISSUE THREAD

**Issue by piersf** [saltstack/salt#47636]
Hi,

I have the below state:

```
/etc/sysconfig/jenkins:
  file.managed:
    - source: salt://path/to/state/file/jenkins
    - user: root
    - group: root
    - mode: 600
    - template: jinja
    - require:
      - pkg: jenkins
      - user: root
```

And when pushing to the minion, it fails with the below error:

```
----------
          ID: /etc/sysconfig/jenkins
    Function: file.managed
      Result: False
     Comment: Unable to manage file: u'files.is_text'
     Started: 17:28:12.303840
    Duration: 19.328 ms
     Changes:
----------
```

Master and Minion version: salt-minion 2018.3.0 (Oxygen)
OS: Amazon Linux AMI release 2018.03

Is this the same issue described above which is fixed by #47248 ?
Is there a workaround for this currently?

Thanks,
