### ISSUE TITLE
saltclass fails to expand all variables

### ISSUE THREAD

**Issue by WackyOne** [saltstack/salt#47634]
Saltclass variable expansion does not work if the variable is in a list, such as if you have a list of dictionaries in the pillar. This functionality worked in reclass.

Make a pillar with a list of dictionaries and put a variable that you want expanded in the list
<pre>
pillars:
  substitute:
    key: value
  list_of_dicts:
    - id: dict1
      a: ${substitute:key}
    - id: dict2
      b: ${substitute:key}
</pre>

Run a pillar.get on list_of_dicts and the variable ${substitute:key} will not be expanded.
<pre>
# salt 'minion' pillar.get list_of_dicts
minion:
    |_
      ----------
      a:
          ${substitute:key}
      id:
          dict1
    |_
      ----------
      b:
          ${substitute:key}
      id:
          dict2
</pre>

<pre>
# salt-call --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
   python-gnupg: 0.3.7
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.2
 
System Versions:
           dist: SuSE 42.3 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.114-42-default
         system: Linux
        version: openSUSE  42.3 x86_64
</pre>

**Comment by Ch3LL** [comment]
can you include how you have reclass setup with information sanitized?

Also was this working previously with your current setup and if so what version?

**Comment by Ch3LL** [comment]
i'm actually running into this: https://github.com/saltstack/salt/issues/47126

did you happen to run into this issue before running into the issue you reported?

**Comment by WackyOne** [comment]
Yes after updating to 2018.3.0 I had that problem and so that's why I was trying saltclass. I am now back at 2017.7.2 until I can get saltclass or reclass working with the newer version.

**Comment by Ch3LL** [comment]
oh gotchya i was trying reclass thanks for clarifying. ping @olivier-mauras looks like you added this feature. any chance you are seeing the same behavior in saltclass in 2018.3.0 or any ideas here as well?

**Comment by olivier-mauras** [comment]
I completely overlooked that case - all lists actually :(
Seems to work after modification in my tests and your example:
``` yaml
classes:
  - default.users
  - default.motd

states:
  - openssh

pillars:
  default:
    network:
      dns:
        srv1: 192.168.0.1
        srv2: 192.168.0.2
        domain: example.com
      ntp:
        srv1: 192.168.10.10
        srv2: 192.168.10.20
    test_on_list:
      - a: ${default:network:dns:srv1}
      - b: ${default:network:dns:srv2}
      - ${default:network:dns:domain}
  list_of_dicts:
    - id: dict1
      a: ${default:network:ntp:srv1}
    - id: dict2
      a: ${default:network:ntp:srv2}
```

Now gives
```
(...)
  test_on_list:
  - a: 192.168.0.1
  - b: 192.168.0.2
  - zrh.example.com
(...)
list_of_dicts:
- a: 192.168.10.10
  id: dict1
- a: 192.168.10.20
  id: dict2
```

Can you please test this attached patched and confirm this is correctly working for you before I send the patch in?
https://gist.github.com/olivier-mauras/248c02615e12fea687ee4b7929946d46

**Comment by WackyOne** [comment]
I am off until Monday and will test it then. I appreciate the speedy response!

**Comment by olivier-mauras** [comment]
Ah indeed using only `str` for type checking was a bit naive and Python3 centric.
Salt normally handles 2 and 3 support with only basestring through the internal six librairy.
Let me give a couple more testing under Python3 and I'll push a PR with `basestring`

**Comment by olivier-mauras** [comment]
@WackyOne I've updated the patch on https://gist.github.com/olivier-mauras/248c02615e12fea687ee4b7929946d46 
I've tested it on both python 2.7 and 3.6 with the same result. Let me know how this works for you.

**Comment by olivier-mauras** [comment]
Perfect I'll send a PR with a list expansion test included

**Comment by WackyOne** [comment]
I might have spoken too soon. I see some additional behavior around expansion of variables. If I take my example pillar and add text or other variables like this:
<pre>
pillar:
  substitute:
    key: value
  substitute2:
    key: value2
  list_of_dicts:
    - id: dict1
      a: ${substitute:key} Only stuff after ${substitute2:key}
    - id: dict2
      b: stuff before <${substitute2:key}> and some more stuff.
</pre>
I get this result:
<pre>
master:~ # salt minion pillar.get list_of_dicts
minion:
    |_
      ----------
      a:
          value
      id:
          dict1
    |_
      ----------
      b:
          stuff before &ltvalue2&gt and some more stuff.
      id:
          dict2
</pre>
In "a" I don't get the second variable expanded and in fact all text after the first variable is dropped. In "b", the presence of the text before the variable causes the text after the variable to show up. If I remove "stuff before <", then "> and some more stuff." will also be dropped.

**Comment by olivier-mauras** [comment]
This is a known limitation multiple variables on the same line can't be expanded - it shouldn't trim stuff though .... - this will have to wait for another time...

**Comment by olivier-mauras** [comment]
OK I joined a fix for the incorrect truncation when line starts with a variable.
Multiple variables will require some more work. Can you open another tracking issue for it please?

**Comment by olivier-mauras** [comment]
Ok so I refactored the variable expansions and supporting expansion of multiple variables on the same line went better than expected.

``` yaml
pillars:
  default:
    network:
      dns:
{% if __grains__['os'] == 'should_never_match' %}
        srv1: 192.168.0.1
        srv2: 192.168.0.2
        domain: example.com
{% endif %}
      ntp:
        srv1: 192.168.10.10
        srv2: 192.168.10.20
  test_list:
    - a: ${default:network:ntp:srv1}
    - ${default:network:ntp:srv2}
  test_str: ${motd:text}
  test_str_var_first: ${default:network:ntp:srv2} is the second ntp srv
  test_str_var_not_first: The second ntp server is ${default:network:ntp:srv2}
  test_str_var_middle: The second ntp server - ${default:network:ntp:srv2} - is broken
  test_str_multiple_var: 'There is 2 NTP server: ${default:network:ntp:srv1} and ${default:network:ntp:srv2}'
```
Will give:
``` text
default:
  network:
    dns: null
    ntp:
      srv1: 192.168.10.10
      srv2: 192.168.10.20
  users:
    adm1:
      gecos: Super user admin1
      gid: 1201
      homedir: /home/adm1
      uid: 1201
    adm2:
      gecos: Super user admin2
      gid: 1202
      homedir: /home/adm2
      uid: 1202
motd:
  text: Welcome to  system located in ${default:network:sub}
test_list:
- a: 192.168.10.10
- 192.168.10.20
test_str: Welcome to  system located in ${default:network:sub}
test_str_multiple_var: 'There is 2 NTP server: 192.168.10.10 and 192.168.10.20'
test_str_var_first: 192.168.10.20 is the second ntp srv
test_str_var_middle: The second ntp server - 192.168.10.20 - is broken
test_str_var_not_first: The second ntp server is 192.168.10.20
```
I've update the PR with latest refactored code, both py27 and py36 tests are successful.
Let me know how this goes for you.
