### ISSUE TITLE
Windows minions stopped running some _grains.

### ISSUE THREAD

**Issue by wildk1wi** [saltstack/salt#47671]
I have a number of windows minions that have stopped executing some, but not all of the files in the _grains folder. Other windows minions are running the grains without problems.

The grain in the example below is a small python file that returns true or false based on the existence of a file.

In the trace output on the minion it states that the grain is included but it never executes or returns data.

I have managed to get other grains to come live again by touching the file on the master and doing a saultutil.sync_grains on the minion.  but it does not always work. 

Is there some way to force a complete re-sync of all _grains without changeing the timestamps on the source files in the master?

```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2008Server
         system: Windows
        version: 2008Server 6.0.6002 SP2 Multiprocessor Free

```

salt-call.bat grains.get has_winlogbeat -l trace
....
[TRACE   ] Loading stale_blacklist.blacklist_current grain
[TRACE   ] Loading telegraf_installed.has_telegraf grain
[TRACE   ] Loading telegrafwin_installed.has_wintelegraf grain
[TRACE   ] Loading vpn_router.is_vpn_router grain
**[TRACE   ] Loading winlogbeat_installed.has_winlogbeat grain**
[TRACE   ] Loading disks.disks grain
[TRACE   ] Disk grain does not support OS
[TRACE   ] Loading extra.config grain
[TRACE   ] Loading extra.shell grain
[TRACE   ] Loading mdadm.mdadm grain
[TRACE   ] Loading minion_process.grains grain
[TRACE   ] Loading opts.opts grain
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'my-minion-VM', 'tcp://x.x.x.x:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (4611)
[DEBUG   ] Setting zmq_reconnect_ivl to '4611ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'my-minion-VM', 'tcp://x.x.x.x:4506', 'clear')
[TRACE   ] Inserted key into loop_instance_map id 116353224 for key ('c:\\salt\\conf\\pki\\minion', 'my-minion-VM', 'tcp://x.x.x.x:4506', 'clear') and process 4504
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[DEBUG   ] Initializing new IPCClient for path: 4511
[TRACE   ] IPCClient: Connecting to socket: 4511
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2018-05-16T01:27:11.803000', 'creds': {'publish_port': 4505, 'aes': 'mQOq4sq2nCE4Ny00yKPE0RaGOZKO7cx+tncB5wrLq0W8VcDmXYn3o2XsmlKFlGeHjnOSxQcR04Y=', 'master_uri': 'tcp://x.x.x.x:4506'},
 'key': ('c:\\salt\\conf\\pki\\minion', 'my-minion-VM', 'tcp://x.x.x.x:4506')}
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'my-minion-VM', 'tcp://x.x.x.x:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'my-minion-VM', 'tcp://x.x.x.x:4506')
[TRACE   ] Inserted key into loop_instance_map id 118053896 for key ('c:\\salt\\conf\\pki\\minion', 'my-minion-VM', 'tcp://x.x.x.x:4506', 'aes') and process 4504
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'my-minion-VM', 'tcp://x.x.x.x:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'my-minion-VM', 'tcp://x.x.x.x:4506')
[TRACE   ] Inserted key into loop_instance_map id 119442760 for key ('c:\\salt\\conf\\pki\\minion', 'my-minion-VM', 'tcp://x.x.x.x:4506', 'aes') and process 4504
[DEBUG   ] LazyLoaded nested.output
**[TRACE   ] data = {'local': ''}**
**local:**
