### ISSUE TITLE
File missing on minion but present on master

### ISSUE THREAD

**Issue by tsenay** [saltstack/salt#47704]
### Description of Issue
Files are reported missing on minion but available on master

Error:
```
----------
          ID: JMXTrans tomcat configuration
    Function: file.managed
        Name: /etc/jmxtrans/json/tomcat.json
      Result: False
     Comment: Source file salt://jmxtrans/files/tomcat.template not found
     Started: 16:39:26.947342
    Duration: 5.856 ms
     Changes:

```

### Setup

salt master config
```
publish_port: 4505
user: xxxxx
ret_port: 4506
root_dir: /sg/salt/master-ops
extension_modules: /opt/salt/files
timeout: 300
log_file: /sg/salt/master-ops/var/log/salt/master
log_level_logfile: debug
log_level: info
roots_update_interval: 60
```

state to be applied on minion
tomcat.sls
```
{%- set jmxtrans = pillar['jmxtrans'] %} 
JMXTrans tomcat configuration:
  file.managed:
    - name: /etc/jmxtrans/json/tomcat.json
    - user: jmxtrans
    - source: salt://jmxtrans/files/tomcat.template
    - template: jinja
    - mode: 644
    - context:
      env: "{{ jmxtrans['environment'] }}"
      component: "{{ jmxtrans['component'] }}"
      host: "{{ grains['host'] }}"
      application: "{{ jmxtrans['application'] }}"
```

get list of files on master
```
> salt-run fileserver.file_list|grep jmxtrans
[INFO    ] Runner completed: 20180517163626082729
- jmxtrans/catalog/tomcat.sls
- jmxtrans/files/tomcat.template
- jmxtrans/init.sls
- jmxtrans/settings.sls
- jmxtrans/tomcat.sls
```
content of cache on minion
```
/sg/salt/minion-ops/var/cache/salt/minion/files/base/jmxtrans/
/sg/salt/minion-ops/var/cache/salt/minion/files/base/jmxtrans/init.sls
/sg/salt/minion-ops/var/cache/salt/minion/files/base/jmxtrans/tomcat.sls
/sg/salt/minion-ops/var/cache/salt/minion/files/base/jmxtrans/catalog
/sg/salt/minion-ops/var/cache/salt/minion/files/base/jmxtrans/catalog/tomcat.sls
```
### Steps to Reproduce Issue
I've tried several operations with no success

```
salt-call  saltutil.clear_cache
salt-call saltutil.sync_all
```

- restart salt-master

### Versions Report
master:
```
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo
```

`salt-minion 2017.7.3 (Nitrogen)`

Am I missing something ??

**Comment by gtmanfred** [comment]
Is that file a symlink to something else?

if you run 

```
salt-call cp.list_master | grep jmxtrans
salt-call cp.list_master_symlinks | grep jmxtrans
```

Also run 

```
salt-call cp.get_file_str salt://jmxtrans/files/tomcat.template
```

Checking the master log in debug mode would be helpful

Also, on the master, can you try opening the file? and just making sure it is actually there?

Thanks,
Daniel

**Comment by tsenay** [comment]
sorry for delay, I wasn't working on that project for a while.

I finally found by accident the real issue. The problem is not on file sync but elsewhere

The context contain the 'env' item. I saw in logs a deprecation message about about the env variable.
I've renammed the 'env' item to 'environment' and the issue disapears

change block 
```
{%- set jmxtrans = pillar['jmxtrans'] %} 
JMXTrans tomcat configuration:
  file.managed:
    - name: /etc/jmxtrans/json/tomcat.json
    - user: jmxtrans
    - source: salt://jmxtrans/files/tomcat.template
    - template: jinja
    - mode: 644
    - context:
      env: "{{ jmxtrans['environment'] }}"
      component: "{{ jmxtrans['component'] }}"
      host: "{{ grains['host'] }}"
      application: "{{ jmxtrans['application'] }}"
```
to
```
/etc/jmxtrans/json/tomcat.json:
  file.managed:
    - user: jmxtrans
    - source: salt://jmxtrans/catalog/files/tomcat.jinja
    - template: jinja
    - mode: 644
    - context:
      environment: {{ jmxtrans.environment }}
      component: {{ jmxtrans.component }}
      host: {{ grains['host'] }}
      application: {{ jmxtrans
```

makes everything work again.

**Comment by gtmanfred** [comment]
Well, first, your are not passing anything to the context dictionary, context in this case is null.

```
/etc/jmxtrans/json/tomcat.json:
  file.managed:
    - user: jmxtrans
    - source: salt://jmxtrans/catalog/files/tomcat.jinja
    - template: jinja
    - mode: 644
    - environment: {{ jmxtrans.environment }}
    - context:
        component: {{ jmxtrans.component }}
        host: {{ grains['host'] }}
        application: {{ jmxtrans
```

But that is just a problem with yaml.

@terminalmage were you the one that deprecated env for environment? it seems like it might not be working with the deprecation.

Thanks!
Daniel
