### ISSUE TITLE
Unable to write multiple key-value pairs to registry node

### ISSUE THREAD

**Issue by mbulmer** [saltstack/salt#47735]
### Description of Issue/Question
Hello! I'm still a novice when it comes to salt, so if this is simply a syntax error, a misunderstanding of this policy, or something else entirely, then I would greatly appreciate a nudge in the right direction...

Anyways, I'm trying to write several key-value pairs to a Registry node that sets the default actions for how Windows Defender handles the various levels of severity for detected malware.

Value names represent the severity level:
1 - Low
2- Medium
4 - High
5 - Severe

Value data represents the action to take:
2 - Quarantine

The expected result should be four entries under this node with names of 1, 2, 4, and 5, all with values of 2.

When using the below code, only the last entry is written to the Registry. Any help would be appreciated!

### Setup
Here is the relevant portion of the salt state:
```# --- Threat: Low - Action: Quarantine
'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows Defender\Threats\ThreatSeverityDefaultAction':
  reg.present:
    - vname: '1'
    - vdata: '2'
    - vtype: REG_SZ

# --- Threat: Medium - Action: Quarantine
    - vname: '2'
    - vdata: '2'
    - vtype: REG_SZ

# --- Threat: High - Action: Quarantine
    - vname: '4'
    - vdata: '2'
    - vtype: REG_SZ

# --- Threat: Severe - Action: Quarantine
    - vname: '5'
    - vdata: '2'
    - vtype: REG_SZ
```

Here is what the Registry looks like after applying the state:
<img width="1138" alt="2018-05-18 13_32_43-registry editor" src="https://user-images.githubusercontent.com/8107004/40256638-fa3ce4a0-5a9f-11e8-9b01-a3367e52ffdc.png">

### Steps to Reproduce Issue
Relevant output:
```
          ID: HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows Defender\Threats\ThreatSeverityDefaultAction
    Function: reg.present
      Result: True
     Comment: 5 in HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows Defender\Threats\ThreatSeverityDefaultAction is already configured
     Started: 13:33:40.233000
    Duration: 2.0 ms
     Changes:
```

```
[INFO    ] Running state [HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows Defender\Threats\ThreatSeverityDefaultAction] at time 13:33:40.233000
[INFO    ] Executing state reg.present for [HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows Defender\Threats\ThreatSeverityDefaultAction]
[INFO    ] 5 in HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows Defender\Threats\ThreatSeverityDefaultAction is already configured
[INFO    ] Completed state [HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows Defender\Threats\ThreatSeverityDefaultAction] at time 13:33:40.235000 (duration_in_ms=2.0)
```

### Versions Report
```Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.7
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.17134  Multiprocessor Free
```

**Comment by twangboy** [comment]
You want something like this:
```
set_key_1:
  reg.present:
    - name: 'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows Defender\Threats\ThreatSeverityDefaultAction'
    - vname: '1'
    - vdata: '2'
    - vtype: REG_SZ

# --- Threat: Medium - Action: Quarantine
set_key_2:
    - name: 'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows Defender\Threats\ThreatSeverityDefaultAction'
    - vname: '2'
    - vdata: '2'
    - vtype: REG_SZ

# --- Threat: High - Action: Quarantine
set_key_4:
    - name: 'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows Defender\Threats\ThreatSeverityDefaultAction'
    - vname: '4'
    - vdata: '2'
    - vtype: REG_SZ

# --- Threat: Severe - Action: Quarantine
set_key_5:
    - name: 'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows Defender\Threats\ThreatSeverityDefaultAction'
    - vname: '5'
    - vdata: '2'
    - vtype: REG_SZ
```
Something like that
