### ISSUE TITLE
accessing pillar data from jinja template

### ISSUE THREAD

**Issue by pasanmdev** [saltstack/salt#47745]
Hi Guys,

I'm trying to use pillars for accessing my config data. But I'm getting a jinja error when accessing pillar data as below.

Rendering SLS 'base:rtpengine' failed: Jinja variable list object has no element 0

However I can access the variable from minion using salt-call command as below,

salt-call pillar.get rtpengine:config:MEDIA_IPv4
local:
    10.3.1.138

### Setup
Command that I'm running to install config on the minion
salt 'voip2-rtp*' state.apply rtpengine

### state file ###
srv/salt/rtpengine.sls
```
rtpengine:

/etc/rtpengine/rtpengine.conf:
  file.managed:
    - source:
      - salt://configs/voip/mediagws/etc/rtpengine/rtpengine.conf
    - context:
         MEDIA_IPv4: {{ salt['pillar.get']('rtpengine:config:MEDIA_IPv4') }}
    - template: jinja

```
### pillar file ###
srv/pillar/top.sls
```
base:
   '*':
     - firewalls
     - rtpengine


rtpengine:
{% if grains['nodename'] ==  'voip2-rtpeng' %}
     config:
        MEDIA_IPv4: 10.3.1.138
{% elif grains['nodename'] == 'voip2-rtpeng2' %}
     config:
        MEDIA_IPv4: 10.3.1.139
{% endif %}

```

### Versions Report

on master

Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
        machine: x86_64
        release: 4.9.76-local.20180111-152449
         system: Linux
        version: debian 9.4 

##on minion##
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
        machine: x86_64
        release: 4.9.78-local.20180131-124246
         system: Linux
        version: debian 9.4

**Comment by mirceaulinic** [comment]
You probably only need to move the following block from `top.sls` into `/srv/pillar/rtpengine.sls`:

```sls
rtpengine:
{% if grains['nodename'] ==  'voip2-rtpeng' %}
     config:
        MEDIA_IPv4: 10.3.1.138
{% elif grains['nodename'] == 'voip2-rtpeng2' %}
     config:
        MEDIA_IPv4: 10.3.1.139
{% endif %}
```

To check, execute `salt 'voip2-rtp*' pillar.get 'rtpengine:config:MEDIA_IPv4'` where you should see your data.

**Comment by pasanmdev** [comment]
@mirceaulinic sorry I forgot to mention. rtpengine section was in a different .sls as you suggest. I figured how to get it working and it appears error was pointing towards CONTEXT list variable rather than my pillar data. Following is the working config. Thanks for your reply

srv/pillar/rtpengine.sls 
```
{% if grains['nodename'] ==  'voip2-rtpeng' %}
rtpengine:
  config:
    MEDIA_IPv4: 10.3.1.138
    MEDIA_IPv6: x:x:1d:f2::1:x
{% elif grains['nodename'] == 'voip2-rtpeng2' %}
  config:
    MEDIA_IPv4: 10.3.1.139
    MEDIA_IPv6: x:x:1d:f2::1:x
{% endif %}

```

srv/salt/rtpengine.sls 
```
rtpengine:
  pkg.installed:
   - pkgs:
     - ngcp-rtpengine
     - ngcp-rtpengine-iptables
     - ngcp-rtpengine-kernel-dkms
     - ngcp-rtpengine-utils
  service.running:
   - name: ngcp-rtpengine-daemon
   - enable: True
   - watch:
     - file: /etc/rtpengine/rtpengine.conf

/etc/rtpengine/rtpengine.conf:
  file.managed:
    - source:
      - salt://configs/voip/mediagws/etc/rtpengine/rtpengine.conf
    - context:
         MEDIA_IPv4: {{ pillar['rtpengine']['config']['MEDIA_IPv4'] }}
         MEDIA_IPv6:  {{ pillar['rtpengine']['config']['MEDIA_IPv6'] }}
    - template: jinja



```
