### ISSUE TITLE
salt-cloud always return error with Proxmox provider even when VM successfully created

### ISSUE THREAD

**Issue by hatifnatt** [saltstack/salt#47771]
### Description of Issue/Question
After creation of VM salt-cloud always returns an error.
I will check is this issue still preset in Salt 2018+ as soon as I will update to it.

### Setup
Proxmox provider config
```yaml
pve:
  minion:
    master: salt
  driver: proxmox
  url: pve.host.tld
  user: saltcloud@pve
  password: somepassword
```
Profile
```yaml
pve-kvm-debian9:
  provider: pve
  technology: qemu
  memory: 512
  host: pvenode
  size: ''
  ostype: l26
  image: image.iso
  scsi0: local:4,format=qcow2,size=4G
  cdrom: iso-storage:iso/debian-9.0.0-amd64-netinst.iso
  net0: virtio,bridge=vmbr1
  name: salt-provisioned-vm
```
Mapfile
```yaml
pve-kvm-debian9:
  - saltvm
```
### Steps to Reproduce Issue
Create VM from commandline without map file:
```bash
salt-cloud -p pve-kvm-debian9 saltvm
```
VM successfully created, but still useless error is returned:
```
Usage: salt-cloud [options] <-m MAP | -p PROFILE> <NAME> [NAME2 ...]
salt-cloud: error: There was a profile error:
```
Create VM from mapfile:
```bash
salt-cloud -m salvm.map
```
VM successfully created, but although error is returned:
```
The following virtual machines are set to be created:
  saltvm

Proceed? [N/y] y
... proceeding
[ERROR   ] Failed to deploy 'saltvm'. Error:
saltvm:
    ----------
    Error:
```
### Versions Report
```
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.3
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.3
```
