### ISSUE TITLE
pkg.installed with versions containing colons have inconsistent behavior

### ISSUE THREAD

**Issue by NewEvolution** [saltstack/salt#47785]
### Description of Issue/Question
When installing packages with `pkg.installed` version strings containing the `:` character behave inconsistently.

### Setup
```sls
erlang-mode:
  pkg.installed:
    - version: 1:20.3-1

esl-erlang:
  pkg.installed:
    - version: 1:20.3    # format 1
    - version: '1:20.3'  # format 2

erlang-repo:
  pkgrepo.managed:
    - name: deb http://binaries.erlang-solutions.com/debian xenial contrib
    - file: /etc/apt/sources.list.d/erlang-solutions.list
    - key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    - require_in:
      - pkg: erlang-mode
      - pkg: esl-erlang
```

### Steps to Reproduce Issue
Attempt to apply the state to a minion with `test=True`.  With format 1:
```
----------
          ID: erlang-mode
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: erlang-mode=1:20.3-1
     Started: 21:41:57.873465
    Duration: 42.784 ms
     Changes:
----------
          ID: esl-erlang
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: esl-erlang=80.3
     Started: 21:53:13.887892
    Duration: 43.915 ms
     Changes:
```

With format 2:
```
----------
          ID: erlang-mode
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: erlang-mode=1:20.3-1
     Started: 21:41:57.873465
    Duration: 42.784 ms
     Changes:
----------
          ID: esl-erlang
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: esl-erlang=1:20.3
     Started: 21:53:34.070360
    Duration: 42.982 ms
     Changes:
```

Of note - the syntax for `erlang-mode` works properly without the version being quoted while the version for `esl-erlang` only parses properly when quoted.

### Versions Report
master:
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-112-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Minion:
```
Salt Version:
               Salt: 2018.3.0

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: Ubuntu 16.04 xenial
             locale: ascii
            machine: x86_64
            release: 4.4.0-116-generic
             system: Linux
            version: Ubuntu 16.04 xenial
```
