### ISSUE TITLE
win_lgpo.py line 5368; AttributeError: 'OrderedDict' object has no attribute 'lower'

### ISSUE THREAD

**Issue by jpsv** [saltstack/salt#47784]
### Description of Issue/Question
When using SaltStack to configure local group policy, I run into the same error on multiple machines and any SLS file that specifies a GPO element:

          ID: active_hours_policy
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1878, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 306, in set_
                  adml_language=adml_language)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 5368, in set_
                  log.debug('setting == %s', _admTemplateData[policy_namespace][policy_name].lower())
              AttributeError: 'OrderedDict' object has no attribute 'lower'
     Started: 17:31:24.824000
    Duration: 9370.0 ms
     Changes:

### Setup
```
# activehours.sls
active_hours_policy:
  lgpo.set:
    - computer_policy:
        'ActiveHours':
            'ActiveHoursEndtime': 8
            'ActiveHoursEndTime': 19
    - adml_language: en-US
    - onchanges_in:
      - cmd: run_gpupdate

run_gpupdate:
  cmd.run:
    - name: 'gpupdate.exe /force'
```
```
# screensaver.sls
Password Protect Idle Workstation:
  lgpo.set:
    - user_policy:
        "Enable screen saver": Enabled
        "Password protect the screen saver": Enabled
        "Screen saver timeout":
            "ScreenSaverTimeOutFreqSpin": "720"

Run myscript:
  cmd.run:
    - name: 'gpupdate.exe /force'
```

This SLS file WORKS:
```
# unset-wallpaper.sls
Wallpaper Policy:
  lgpo.set:
    - user_policy:
        Desktop Wallpaper: Not Configured

Run myscript:
  cmd.run:
    - name: gpupdate.exe /force
```

### Steps to Reproduce Issue
Happens on every Windows 10 machine I try to configure, starting with a fresh install of Windows 10 and updating it to 1803, then installing SaltStack 2018.3.0 Python2.

To reproduce, configure a group policy that has required elements.

### Versions Report
Minion:
* Windows 10 1803
* Saltstack Py2 2018.3.0

Master:
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.13.13-2-pve
         system: Linux
        version: debian 9.4
```
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
@twangboy i know you have been doing a lot of work around this module. Any ideas here?

**Comment by lomeroe** [comment]
@jpsv The values for ActiveHoursStartTime and ActiveHoursEndTime must be entered as they appear in the gpedit.msc gui

In other words:
```
# activehours.sls
active_hours_policy:
  lgpo.set:
    - computer_policy:
        'ActiveHours':
            'ActiveHoursStartTime': '8 AM'
            'ActiveHoursEndTime': '7 PM'
    - adml_language: en-US
    - onchanges_in:
      - cmd: run_gpupdate
```

However, in PY3 2018.3.2, this policy will fail to apply in some circumstances (PR #48587 I believe).  However, it does appear that the fix for the issue *should* be in the PY3 2018.3.3 version, when it is released.  PY2 versions do not have that particular issue.
