### ISSUE TITLE
napalm_yang does not work with freshly installed Salt 2018.3

### ISSUE THREAD

**Issue by ajschroeder** [saltstack/salt#47867]
### Description of Issue/Question
I have a lab configured using vagrant consisting of a saltmaster/proxy minion (ubuntu/xenial64) and three other VMs (vSRX, vEOS, and IOS-XE). I am trying to use SALT to manage the configurations of each device using NetYANG. napalm-yang is installed via pip:

```
vagrant@saltmaster:~$ sudo pip list | grep napalm-yang
napalm-yang (0.1.0)
```

### Setup
Here are the relevant configs:

pillar top file:

```base:
  '*':
    - default
    - ntp_servers
  'vsrx1':
    - vsrx1
  'veos*':
    - veos
  'vsrx*':
    - vsrx
  'iosxe*':
    - iosxe
```

vsrx1 interfaces from pillar file:

```
openconfig-interfaces:
  interfaces:
    interface:
      ge-0/0/2:
        config:
          enabled: true
          description: "Customer A"
        subinterfaces:
          subinterface:
            0:
              config:
                description: "Customer A - IPv4"
              ipv4:
                addresses:
                  address:
                    1.2.3.4:
                      config:
                        ip: "1.2.3.4"
                        prefix-length: 24
```

the state file:

```
interfaces_oc_config:
  napalm_yang.configured:
    - data: {{ salt.pillar.get('openconfig-interfaces') | json }}
    - models:
      - models.openconfig_interfaces
```

### Steps to Reproduce Issue
To reproduce the issue I have been executing the state file on the vsrx1 VM. Here is the console output:

```
vagrant@saltmaster:~$ sudo salt 'vsrx1' state.sls oc_interfaces
vsrx1:
----------
          ID: interfaces_oc_config
    Function: napalm_yang.configured
      Result: False
     Comment: State 'napalm_yang.configured' was not found in SLS 'oc_interfaces'
              Reason: 'napalm_yang.configured' is not available.
     Changes:

Summary for vsrx1
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
vagrant@saltmaster:~$
```

Attached is the proxy log in debug mode.
[proxy.zip](https://github.com/saltstack/salt/files/2048696/proxy.zip)

### Versions Report
```
vagrant@saltmaster:~$ sudo salt --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-124-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by ajschroeder** [comment]
@garethgreenaway I had not checked before, but here is the output from the saltmaster/proxy minion:
```
vagrant@saltmaster:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import napalm_yang
>>> config = napalm_yang.base.Root()
>>>
```
That looks correct. As far as the pillar file for `vsrx1`, here it is:
```
{% set hostname = salt['grains.get']('id', '') %}
proxy:
  proxytype: napalm
  driver: junos
  host: {{ hostname }}
  username: root
  passwd: blah
  optional_args:
    config_lock:
      - False
```
