### ISSUE TITLE
salt.schedule.present state in test=True mode return changes

### ISSUE THREAD

**Issue by dev58** [saltstack/salt#47890]
### Description of Issue/Question
This sate which is included in my orchestration is returning True in test mode (test =True)
According documentation https://docs.saltstack.com/en/latest/ref/states/writing.html
this shouldn't be happening. It should return no changes if test=True.

Here is a part of orchestration output:

`sudo salt-run state.orch orch.sdc pillar='{"region": "eu-de-1", "project": "develop01"}' saltenv=ok pillarenv=ok -l debug test=True`
.
.

> ----------
>                         ID: commons_schedule_bkp_job_definition
>                   Function: schedule.present
>                       Name: backup
>                     Result: True
>                    Comment: Job: backup would be modified in schedule.
>                    Started: 11:08:44.694000
>                   Duration: 27.0 ms
>                    **Changes:
>                             ----------
>                             diff:
>                                 ---
>                                 +++
>                                 @@ -1,9 +1,8 @@
>                                  args:['commons.windows.bkp']
>                                 -enabled:False
>                                 +enabled:True
>                                  function:state.sls
>                                  jid_include:True
>                                 -kwargs:{'saltenv': 'ok', 'pillar': {'swift': True}}
>                                 +kwargs:OrderedDict([('test', True), ('saltenv', 'ok'), ('pillar', OrderedDict([('swift', True)]))])
>                                  maxrunning:1
>                                  name:backup
>                                 -return_job:True
>                                  when:['Sunday 1:00am', 'Monday 1:00am', 'Tuesday 1:00am', 'Wednesday 1:00am', 'Thursday 1:00am', 'Friday 1:00am', 'Saturday 1:00am']**
>                 Name: backup - Function: schedule.enabled - Result: Clean Started: - 11:08:44.722000 Duration: 15.0 ms
> 
>               Summary for sdc.develop01.eu-de-1
>               -------------
>               Succeeded: 23 (unchanged=10, changed=1)
>               Failed:     0
>               -------------
>               Total states run:     23
>               Total run time:   49.038 s
>               Name: orch_sdc_roles_sdc_dc_finish2_sdc.develop01.eu-de-1 - Function: salt.state - Result: Clean

### Setup
```
commons_schedule_bkp_job_definition:
  schedule.present:
    - name: backup
    - function: state.sls
    - job_args:
    {% if settings.role == 'pdc' or settings.role == 'sdc' %}
        - commons.windows.bkp
    {% elif settings.role == 'sld_hana' or settings.role == 'hana' %}
        - formulas.hana.backup
    {% elif settings.role == 'ls' %}
        - roles.ls.backup
    {% elif settings.role == 'sld_share' %}
        - roles.sld_share.backup
    {% endif %}
    - job_kwargs:
        saltenv: {{ saltenv }}
        pillar: {"swift": True}
    - when:
        - Sunday {{ backup_utc_time }}
        - Monday {{ backup_utc_time }}
        - Tuesday {{ backup_utc_time }}
        - Wednesday {{ backup_utc_time }}
        - Thursday {{ backup_utc_time }}
        - Friday {{ backup_utc_time }}
        - Saturday {{ backup_utc_time }}
    - return_job: True
```

### Steps to Reproduce Issue
To reproduce this issue just create and run orchestration which will call state that executes schedule.present. which will set some job. Run orchestration in test=True.

### Versions Report
salt-master 2017.7.2 (Nitrogen)
