### ISSUE TITLE
require is ingored in state 

### ISSUE THREAD

**Issue by knfoo** [saltstack/salt#47906]
### require ignored in state file
I have made a custom module + state to handle multicluster k8s setup but the `require` in my state file is ignored and the state run fails do to that.

### Setup
Nothing special.

The part of the state that fails.
```
watcher sa:
  k8s.serviceaccount:
    - ns: usearch
    - filepath: /var/tmp/usearchdb/es
    - filename: rbac/es-watcher-sa.yaml
    - label_selector: component=elasticsearch
    - serviceaccount: es-watcher

watcher role:
  k8s.rbac_role:
    - ns: usearch
    - filepath: /var/tmp/usearchdb/es
    - filename: rbac/role-es-watcher.yaml
    - label_selector: component=elasticsearch
    - role: es-watcher

watcher rolebinding:
  k8s.rbac_rolebinding:
    - ns: usearch
    - filepath: /var/tmp/usearchdb/es
    - filename: rbac/rolebining-es-watcher.yaml
    - label_selector: component=elasticsearch
    - rolebinding: es-watcher

watcher secrets:
  file.managed:
    - name: /var/tmp/usearchdb/es/common/es-networkpolicy-watcher-secret.yaml
    - source: salt://{{ slspath }}/files/es/common/es-networkpolicy-watcher-secret.yaml
    - template: jinja
      context:
        c0_token: {{ salt['k8s.read_sa_secret_token']('usearch','es-watcher','c0') }}
        c0_api_endpoint: {{ salt['hashutil.base64_b64encode']('https://192.168.61.11:6443') }}
        c1_token: {{ salt['k8s.read_sa_secret_token']('usearch','es-watcher','c1') }}
        c1_api_endpoint: {{ salt['hashutil.base64_b64encode']('https://192.168.61.140:6443') }}
        ca_crt: {{ salt['k8s.read_sa_secret_token']('usearch','es-watcher','c1',False,True) }}
    - require:
      - k8s: watcher sa
```
The calls to k8s.read_sa_secret_token executed before the service account is present even I have the require flag set.
The result is that the secret cannot be applied to the clusters.

### Steps to Reproduce Issue
apply the state

### Versions Report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4

**Comment by Ch3LL** [comment]
The reason `k8s.read_sa_secret_token` is run before the state is because it is inside jinja. Jinja is rendered before the yaml and before the state runs. We added a new feature named slots that should be perfect for this use case. The documentation is here: https://docs.saltstack.com/en/latest/topics/slots/index.html  It will run these execution modules right before the state module runs.

**Comment by knfoo** [comment]
Thank you for pointing to the slots feature.
I tried that.

```
watcher secrets:
  file.managed:
    - name: /var/tmp/usearchdb/es/common/es-networkpolicy-watcher-secret.yaml
    - source: salt://{{ slspath }}/files/es/common/es-networkpolicy-watcher-secret.yaml
    - template: jinja
      context:
        c0_token: __slot__:salt:k8s.read_sa_secret_token('usearch','es-watcher','c0')
        c0_api_endpoint: __slot__:salt:hashutil.base64_b64encode('https://192.168.61.11:6443')
        c1_token: __slot__:salt:k8s.read_sa_secret_token('usearch','es-watcher','c1')
        c1_api_endpoint: __slot__:salt:hashutil.base64_b64encode('https://192.168.61.140:6443')
        ca_crt: __slot__:salt:k8s.read_sa_secret_token('usearch','es-watcher','c1',False,True)
    - require:
      - k8s: watcher sa

watcher secrets apply:
  k8s.secret:
    - ns: usearch
    - filepath: /var/tmp/usearchdb/es
    - filename: es-networkpolicy-watcher-secret.yaml
    - label_selector: component=elasticsearch
    - secret: es-watcher-tokens
    - require:
      - file: watcher secrets
```

but it fails with this error:

```
          ID: watcher secrets
    Function: file.managed
        Name: /var/tmp/usearchdb/es/common/es-networkpolicy-watcher-secret.yaml
      Result: True
     Comment: File /var/tmp/usearchdb/es/common/es-networkpolicy-watcher-secret.yaml updated
     Started: 08:37:58.484318
    Duration: 28.869 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -10,8 +10,8 @@
                       component: elasticsearch
                       role: es-networkpolicy-updater
                   data:
                  -  c0_token: {{ c0_token }}
                  -  c0_api_endpoint: {{ c0_api_endpoint }}
                  -  c1_token: {{ c1_token }}
                  -  c1_api_endpoint: {{ c1_api_endpoint }}
                  -  ca.crt: {{ ca_crt }}
                  +  c0_token: __slot__:salt:k8s.read_sa_secret_token('usearch','es-watcher','c0')
                  +  c0_api_endpoint: __slot__:salt:hashutil.base64_b64encode('https://192.168.61.11:6443')
                  +  c1_token: __slot__:salt:k8s.read_sa_secret_token('usearch','es-watcher','c1')
                  +  c1_api_endpoint: __slot__:salt:hashutil.base64_b64encode('https://192.168.61.140:6443')
                  +  ca.crt: __slot__:salt:k8s.read_sa_secret_token('usearch','es-watcher','c1',False,True)
----------
          ID: watcher secrets apply
    Function: k8s.secret
      Result: False
     Comment: Exception: (400)
              Reason: Bad Request
              HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 01 Jun 2018 08:37:58 GMT', 'Audit-Id': 'a67a6d75-c04e-4ec4-bb5b-4bc2d7b1d527', 'Content-Length': '426', 'Content-Type': 'application/json'})                                                                            
              HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Secret in version \"v1\" cannot be handled as a Secret: v1.Secret: Data: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...|lse,True)\", \"
c0_toke|..., bigger context ...|ret_token('usearch','es-watcher','c1',False,True)\", \"c0_token\": \"__slot__:salt:k8s.read_sa_secret_to|...","reason":"BadRequest","code":400}                                                                                                            
     Started: 08:37:58.514169
    Duration: 136.524 ms
     Changes:   
```

It seems that slots are not executed before it is run
