### ISSUE TITLE
Requisites in reactor is not working

### ISSUE THREAD

**Issue by romcab** [saltstack/salt#47918]
### Description of Issue/Question
I've created a simple reactor that does the following when a particular event occurs.
- copy an existing file in the salt-master with a new file name
- replace a value in the new file
- read the file, updated value should change.
I've used requisite(require) and expects the order to be as is. however, running the script returns different ordering.

### Setup
/srv/reactor/test.sls
```
copy_config_file_with_name:
  runner.salt.cmd:
    - args:
      - fun: 'file.copy'
      - src: '{{postdata.template_name}}'
      - dst: '{{postdata.config_name}}'

replace_config_file_instance_name:
  runner.salt.cmd:
    - args:
      - fun: 'file.replace'
      - path: '{{postdata.config_name}}'
      - pattern: '{{ postdata.pattern }}'
      - repl: '{{ postdata.repl }}'
      - count: 1
      - backup: False
    - require:
      - cmd: copy_config_file_with_name

read_content_of_copied_file:
  runner.salt.cmd:
    - args:
      - fun: 'file.read'
      - path: '{{postdata.config_name}}'
    - require:
      - cmd: replace_config_file_instance_name
```

### Steps to Reproduce Issue
```
salt/run/20180601071046998651/new	{
    "_stamp": "2018-06-01T07:10:47.001310",
    "fun": "runner.salt.cmd",
    "fun_args": [
        {
            "fun": "file.read",
            "path": "/etc/salt/cloud.maps.d/test-env.d/aiws-1.conf"
        }
    ],
    "jid": "20180601071046998651",
    "user": "Reactor"
}
salt/run/20180601071047323545/new	{
    "_stamp": "2018-06-01T07:10:47.325767",
    "fun": "runner.salt.cmd",
    "fun_args": [
        {
            "backup": false,
            "count": 1,
            "fun": "file.replace",
            "path": "/etc/salt/cloud.maps.d/test-env.d/aiws-1.conf",
            "pattern": "NAME",
            "repl": "aiws-1"
        }
    ],
    "jid": "20180601071047323545",
    "user": "Reactor"
}
salt/run/20180601071047348101/new	{
    "_stamp": "2018-06-01T07:10:47.349985",
    "fun": "runner.salt.cmd",
    "fun_args": [
        {
            "dst": "/etc/salt/cloud.maps.d/test-env.d/aiws-1.conf",
            "fun": "file.copy",
            "src": "/etc/salt/cloud.maps.d/test-env.d/aiws.conf"
        }
    ],
    "jid": "20180601071047348101",
    "user": "Reactor"
}
salt/run/20180601071046998651/ret	{
    "_stamp": "2018-06-01T07:10:48.272098",
    "fun": "runner.salt.cmd",
    "fun_args": [
        {
            "fun": "file.read",
            "path": "/etc/salt/cloud.maps.d/test-env.d/aiws-1.conf"
        }
    ],
    "jid": "20180601071046998651",
    "return": "centos-micro-profile:\n- NAME:\n    grains:\n      environment: staging\n      node: 0\n      services:\n        aiws:\n          port: 8080\n          check: http\n      multi_node: false\n      roles:\n      - tomcat\n      - aiws\n      - serverkey\n      service: aiws\n",
    "success": true,
    "user": "Reactor"
}
salt/run/20180601071047323545/ret	{
    "_stamp": "2018-06-01T07:10:48.545898",
    "fun": "runner.salt.cmd",
    "fun_args": [
        {
            "backup": false,
            "count": 1,
            "fun": "file.replace",
            "path": "/etc/salt/cloud.maps.d/test-env.d/aiws-1.conf",
            "pattern": "NAME",
            "repl": "aiws-1"
        }
    ],
    "jid": "20180601071047323545",
    "return": "--- \n+++ \n@@ -1,5 +1,5 @@\n centos-micro-profile:\n-- NAME:\n+- aiws-1:\n     grains:\n       environment: staging\n       node: 0\n",
    "success": true,
    "user": "Reactor"
}
salt/run/20180601071047348101/ret	{
    "_stamp": "2018-06-01T07:10:48.551352",
    "fun": "runner.salt.cmd",
    "fun_args": [
        {
            "dst": "/etc/salt/cloud.maps.d/test-env.d/aiws-1.conf",
            "fun": "file.copy",
            "src": "/etc/salt/cloud.maps.d/test-env.d/aiws.conf"
        }
    ],
    "jid": "20180601071047348101",
    "return": true,
    "success": true,
    "user": "Reactor"
}
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
