### ISSUE TITLE
SLS file could use a type check to prevent weird errors

### ISSUE THREAD

**Issue by viraptor** [saltstack/salt#47938]
### Description of Issue/Question

If you make a mistake and don't use a list in the top sls file for a single entry, it results in a weird error.

### Setup

`pillar/top.sls`:
```
base:
  '*':
    nginx
```

### Steps to Reproduce Issue

```
$ salt-call .... state.apply ...

local:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'n' in environment 'base' is not available on the salt master
----------
    Specified SLS 'g' in environment 'base' is not available on the salt master
----------
    Specified SLS 'i' in environment 'base' is not available on the salt master
----------
    Specified SLS 'x' in environment 'base' is not available on the salt master
```

Instead of saying something like "host expects a list of SLSs rather than a string `nginx`", salt tries to iterate what it's got, resulting in checking state for each letter of the name.
Since this is unlikely to ever be the expected behaviour, salt should reject simple strings in that location.

### Versions Report

```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.0
         Python: 2.7.15 (default, May  1 2018, 16:44:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 17.5.0
         system: Darwin
        version: 10.13.4 x86_64
```
