### ISSUE TITLE
Add a git.cloned state for cases where updating is unnecessary after cloning

### ISSUE THREAD

**Issue by viraptor** [saltstack/salt#47937]
### Description of Issue/Question

In some configurations of `git.latest`, there's no point in running `ls-remote` to find what HEAD (or other `rev`) is pointing at.

This matters for large repos, because running `git ls-remote` against them can take minutes on a slow connection.
It also prevents offline runs when the local state is sufficient.

### Setup

```
some_repo:
  git.latest:
    - name: git@github.com:....
    - target: /some/local/path
    - update_head: false
```

In this case, if the repo is already cloned and checked out (HEAD exists locally), there's no point running anything against the remote repository.

### Versions Report
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.0
         Python: 2.7.15 (default, May  1 2018, 16:44:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 17.5.0
         system: Darwin
        version: 10.13.4 x86_64
```

**Comment by terminalmage** [comment]
I disagree, given the following from the documentation:

```
    update_head : True
        If set to ``False``, then the remote repository will be fetched (if
        necessary) to ensure that the commit to which ``rev`` points exists in
        the local checkout, but no changes will be made to the local HEAD.

        .. versionadded:: 2015.8.3
```

The `ls-remote` is needed to determine whether the local checkout has the commit to which the current remote points.

I tried running a `git ls-remote https://github.com/saltstack/salt` (our repo is pretty large), and it took 1.2 seconds. I was able to get it down to about 1 second by also specifying a revision (using `git ls-remote https://github.com/saltstack/salt develop`). Can you test on your large repo and see if there is a measurable benefit? Either way, this looks like a good optimization we can make.

**Comment by viraptor** [comment]
I'm looking at a private repo, with lots of heads (36187 and counting...). On a good connection it takes 30s without specifying the head and 16s when I specify it, so that's definitely an improvement, but still a significant time.

I understand the case where a specific branch like `develop` has to be verified, but I meant the specific case of HEAD:
```
some_repo:
  git.latest:
    - rev: HEAD   # default
    - name: git@github.com:....
    - target: /some/local/path
    - update_head: false
```
in this case, I don't care about the remote branch. The only thing I want to achieve is having the repository cloned - but not in any specific state otherwise.

I think that `update_head: false, rev: HEAD` could be treated specially and skip the check altogether.
