### ISSUE TITLE
file.recurse removes the target file on case-insensitive file systems

### ISSUE THREAD

**Issue by RomanSaveljev** [saltstack/salt#47969]
### Description of Issue/Question

The `file.recurse` will remove the target file after synchronizing it, if the casing of some letters in the file name was changed (e.g. from `A.txt` to `a.txt`). This was observed on Windows.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

init.sls:

```
'C:\\test-case':
  file.recurse:
    - source: salt://test-case/x
    - clean: True
    - include_empty: True
```

In the `x` sub-folder I have a single text file called `A.txt`

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

1. Apply the state: `sudo salt windows-minion state.apply test-case`

```
windows-minion:
----------
          ID: C:\\test-case
    Function: file.recurse
      Result: True
     Comment: Recursively updated C:\\test-case
     Started: 17:18:23.625000
    Duration: 3693.0 ms
     Changes:   
              ----------
              C:\\test-case\A.txt:
                  ----------
                  diff:
                      New file

Summary for windows-minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   3.693 s
```

2. Rename `x/A.txt` to `x/a.txt`
3. Apply the state: `sudo salt windows-minion state.apply test-case`

```
windows-minion:
----------
          ID: C:\\test-case
    Function: file.recurse
      Result: True
     Comment: Recursively updated C:\\test-case
     Started: 17:20:24.661000
    Duration: 3617.0 ms
     Changes:   
              ----------
              removed:
                  - C:\\test-case\A.txt

Summary for windows-minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   3.617 s
```

After step 3 the `C:\test-case\` folder will be left empty.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Master:

```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Minion:

```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.7
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.16299  Multiprocessor Free
```
