### ISSUE TITLE
orch of win_wua error

### ISSUE THREAD

**Issue by prog-dale** [saltstack/salt#48016]
### Description of Issue/Question
Running win_wua.list in an orchestration comes with an error and does not show the results
              The State execution failed to record the order in which all states were executed. The state return missing data is:
              {'Success': False, 'Updates': 'Nothing to install'}

### Setup
```
{% set nodegroups = ['dmz_patch_01','dmz_patch_02','dmz_patch_03','dmz_patch_04','dmz_patch_05','dmz_patch_06'] %}

{% for nodegroup in nodegroups %}

patch_{{ nodegroup }}:
  salt.function:
    - name: win_wua.list
    - tgt: {{ nodegroup }}
    - tgt_type: nodegroup
    - kwarg:
        summary: True
        install: True
        categories: ['Update Rollups,Updates']

reboot_{{ nodegroup }}:
  salt.function:
    - name: system.reboot
    - tgt: {{ nodegroup }}
    - tgt_type: nodegroup
    - kwarg:
        only_on_pending_reboot: False
        timeout: 2
        in_seconds: True
        wait_for_reboot: False
    - require:
      - salt: patch_{{ nodegroup }}

wait_reboot_{{ nodegroup }}:
  salt.wait_for_event:
    - name: salt/minion/*/start
    - id_list: {{ salt.saltutil.runner('cache.grains', tgt=nodegroup,tgt_type='nodegroup').keys() }}
    - require:
      - salt: reboot_{{ nodegroup }}

{% endfor %}
```

### Steps to Reproduce Issue
salt-run state.orchestrate orch.tst_patch
```
### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.7
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
