### ISSUE TITLE
Salt 2018.3.0 service.enable mangles /etc/rc.conf, rendering system unbootable

### ISSUE THREAD

**Issue by JamesSnow** [saltstack/salt#48036]
### Description of Issue/Question
Tagging @cedwards at his request.

Tested on both FreeBSD 11.1 and 10.4:
```
root@salt6:~ # cat /etc/rc.conf
ec2_configinit_enable=YES
ec2_fetchkey_enable=YES
ec2_ephemeralswap_enable=YES
ec2_loghostkey_enable=YES
firstboot_freebsd_update_enable=YES
firstboot_pkgs_enable=YES
growfs_enable="YES"
ifconfig_DEFAULT="SYNCDHCP accept_rtadv"
sshd_enable="YES"
firstboot_pkgs_list="awscli"
ipv6_activate_all_interfaces="YES"
dhclient_program="/usr/local/sbin/dual-dhclient"
hostname="salt6"

root@salt6:~ # salt-call service.enable salt_master
local:
    True

root@salt6:~ # cat /etc/rc.conf
ec2_configinit_enable=YESec2_fetchkey_enable=YESec2_ephemeralswap_enable=YESec2_loghostkey_enable=YESfirstboot_freebsd_update_enable=YESfirstboot_pkgs_enable=YESgrowfs_enable="YES"ifconfig_DEFAULT="SYNCDHCPaccept_rtadv"sshd_enable="YES"firstboot_pkgs_list="awscli"ipv6_activate_all_interfaces="YES"dhclient_program="/usr/local/sbin/dual-dhclient"hostname="salt6"
salt_master_enable="YES"

root@salt6:~ # pkg info | grep salt
py27-salt-2018.3.0_1           Distributed remote execution and configuration management system
root@salt6:~ #
```
### Setup
None. This is a vanilla install, fresh out of the box.

### Steps to Reproduce Issue
```
pkg install py-salt
salt-call service.enable salt_master
```
### Versions Report
```
root@salt6:~ # salt --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Jun  1 2018, 20:05:17)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 11.1-RELEASE-p10
         system: FreeBSD
        version: Not Installed

root@salt6:~ #
```
