### ISSUE TITLE
ext_pillar env specific git branch problem

### ISSUE THREAD

**Issue by jyurdal** [saltstack/salt#48083]
I have a problem with defining different branches for minions with different env. I am using salt-master and salt-minion 2018.3.0

The salt-master config:
```
ext_pillar:
  - git:
    - salttestjyu ssh://repo:
      - env: dev
      - root: /src/srv/pillar
      - pubkey: /root/.ssh/id_rsa.pub
      - privkey: /root/.ssh/id_rsa
   - qa ssh://repo:
      - env: qa
      - root: /src/srv/pillar
      - pubkey: /root/.ssh/id_rsa.pub
      - privkey: /root/.ssh/id_rsa
salt minion config:
environment: dev
pillarenv: dev
pillarenv_from_saltenv: True
saltenv: dev
```
When I issue
**# salt 'myminion' pillar.item dhcpd**

I do get only the data from salttestjyu. However when I do

**# salt-run pillar.show_pillar 'myminion'**

or

**# salt 'myminion' state.apply dhcpd.config**

returned pillar data/dhcpd.config file contains mixed data from both qa(or maybe master) and salttestjyu branch.

Is the git config correct? Do you have any suggestions how I can get **only** the pillar data from salttestjyu branch for specific env? Thanks for all suggestions.

Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-112-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this and it is working in 2017.7.4


on 2018.3.0 (and head of 2018.3):

```
+ salt '*' state.apply test
799d2431c6e9:
    Data failed to compile:
----------
    Rendering SLS 'dev:test' failed: while parsing a block mapping
  in "<unicode string>", line 1, column 1:
    echo "{'pillar': 'megangotit'}":
    ^
expected <block end>, but found '}'
  in "<unicode string>", line 1, column 30:
    echo "{'pillar': 'megangotit'}":
                                 ^
```

note this is failing because the pillar data structure is different between the environments. but what is important is that you are seeing `megangotit` which is in environment qa and not dev.

on 2017.7.4:

```
+ salt '*' state.apply test
799d2431c6e9:
----------
          ID: echo "gitfs"
    Function: cmd.run
      Result: True
     Comment: Command "echo "gitfs"" run
     Started: 19:58:56.776340
    Duration: 133.494 ms
     Changes:   
              ----------
              pid:
                  1510
              retcode:
                  0
              stderr:
              stdout:
                  gitfs

Summary for 799d2431c6e9
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 133.494 ms
```


Here is my configurations:

```
[root@2bfc542d1133 /]# grep -E -v '^$|#' /etc/salt//master
file_roots:
  dev:
     - /srv/salt/
ext_pillar:
  - git:
    - master https://github.com/ch3ll/ch3llscripts.git:
       - env: dev
       - root: salt/pillars
    - test https://github.com/ch3ll/ch3llscripts.git:
       - env: qa
       - root: salt/pillars
```

```
[root@2bfc542d1133 /]# grep -E -v '^$|#' /etc/salt/minion
master: localhost
environment: dev
pillarenv: dev
pillarenv_from_saltenv: True
saltenv: dev
```

ping @terminalmage any ideas here.
