### ISSUE TITLE
Multiple environments with single top file throws "No Top file or master_tops data matches found."

### ISSUE THREAD

**Issue by GitHubAre** [saltstack/salt#48082]
### Description of Issue/Question
Hello,

I am just starting with Salt and I am trying to use multiple environments (base, dev and prod).
My goal would be to have **one top.sls** file inside **base file_roots**. From the docs: https://docs.saltstack.com/en/latest/ref/states/top.html it should be possible as it says:
`When using multiple environments, it is not necessary to create a top file for each environment. The easiest-to-maintain approach is to use a single top file placed in the base environment. `

When I put top.sls into each file root it works fine, but when I have just one inside base (which is what I would like to have), I get this error:

```
computername:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or master_tops data matches found.
     Changes:
```
I am invoking it as :
`salt 'computerid' state.apply saltenv=dev`

### Setup
Master config:

```
file_roots:
  base:
    - /srv/tips/salt/base
  dev:
    - /srv/tips/salt/dev
  prod:
    - /srv/tips/salt/prod


pillar_roots:
  base:
    - /srv/tips/pillar/base
  dev:
    - /srv/tips/pillar/dev
  prod:
    - /srv/tips/pillar/prod

default_top: base
top_file_merging_strategy: same
```
Note: I have also tried with `state_top_saltenv: base`

Folder structure under /srv/tips:

```
├── autosign_grains
│   └── tips_minion_secret
├── pillar
│   ├── base
│   │   ├── tips_azure.sls
│   │   └── top.sls
│   ├── dev
│   │   └── tips_azure.sls
│   └── prod
│       └── tips_azure.sls
└── salt
    ├── base
    │   ├── ad_join.sls
    │   └── top.sls
    ├── dev
    │   └── test.sls
    └── prod
        └── test2.sls
```

### Steps to Reproduce Issue
With above configuration to reproduce:
salt 'computerid' state.apply saltenv=dev

### Versions Report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1012-azure
         system: Linux
        version: Ubuntu 18.04 bionic
