### ISSUE TITLE
file.line on windows not treating unix line endings correctly.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#48110]
### Description of Issue/Question
On windows when using `file.line` state module. If the file being changed has unix style line endings instead of dos line endings. The entire file can be changed. 

### Setup

A simple file to change
```
test1
test2
test3
```

a simple state.
```
remove_test2:
 file.line:
  - name: 'c:\test\test.txt'
  - mode: 'delete'
  - match: 'test2'
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
if the file c:\test\test.txt uses dos line endings it only removes test2 from the file. 
however if the c:\test\test.txt files is using Unix line endings the entire file is reduced to a blank file.

Unix line ending version
```
winion-0:
----------
          ID: remove_conf_line
    Function: file.line
        Name: C:/test/test.txt
      Result: True
     Comment: Changes were made
     Started: 20:02:27.416000
    Duration: 15.0 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,3 +0,0 @@
                  -test1
                  -test2
                  -test3

Summary for winion-0
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  15.000 ms
```
Dos line endings in c:\test\test.txt
```
winion-0:
----------
          ID: remove_conf_line
    Function: file.line
        Name: C:/test/test.txt
      Result: True
     Comment: Changes were made
     Started: 20:04:08.523000
    Duration: 21.0 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,3 +1,2 @@
                   test1
                  -test2
                   test3

Summary for winion-0
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  21.000 ms
```

This only affects windows minions. Linux minions can handle the file with either line ending. 

### Versions Report

```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```
