### ISSUE TITLE
logrotate.set fails on CentOS 7's /etc/logrotate.d/syslog

### ISSUE THREAD

**Issue by mephi42** [saltstack/salt#48125]
Here is the content of my `/etc/logrotate.d/syslog` (it was this way out of the box):
```
/var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
{
    missingok
    sharedscripts
    postrotate
	/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
    endscript
}
```

Here is my SLS file:

```
logrotate-messages-rotate:
  logrotate.set:
    - key: /var/log/messages
    - value: maxsize
    - setting: 100M
```

First, a minor issue: if I ask Salt to edit `/etc/logrotate.d/syslog` directly using `conf_file` directive, it will fail with `KeyError: include files`. The following patch helped:

```
--- a/salt/modules/logrotate.py
+++ b/salt/modules/logrotate.py
@@ -209,8 +209,9 @@ def set_(key, value, setting=None, conf_file=_DEFAULT_CONF):
     and make changes in the appropriate file.
     '''
     conf = _parse_conf(conf_file)
-    for include in conf['include files']:
-        if key in conf['include files'][include]:
+    includes = conf.get('include files', {})
+    for include in includes:
+        if key in includes[include]:
             conf_file = os.path.join(conf['include'], include)

     new_line = six.text_type()
```

Now, the main issue: ```Error: A setting for a dict was declared, but the configuration line given is not a dict```. I dumped the parsed conf, and apparently the parser did not process multiple file syntax correctly:

```
{
   '/var/log/secure':True,
   '/var/log/messages':True,
   '/var/log/cron':True,
   '/var/log/maillog':True,
   '/var/log/spooler':{
      'postrotate':True,
      'sharedscripts':True,
      'missingok':True,
      '/bin/kill':'-HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true',
      'endscript':True
   },
}
```

(Edit) Ugly workaround for now:
```
/etc/logrotate.d/syslog:
  file.line:
    - content: maxsize 100M
    - mode: ensure
    - after: "{"
```

### Versions Report
v2017.7.3
