### ISSUE TITLE
Dynamic File Roots

### ISSUE THREAD

**Issue by BenjaminSchiborr** [saltstack/salt#48132]
### Description of Issue/Question
In our current environment we are using a mixture of information coming out of a git repository and from a local salt file server. Historically all information was always taken from the saltenv base environment (as in the master branch of the git repository and files that were locally on disk configured as the base saltenv)

However, we are moving forward to a new versioning model for git - requiring us to pull information from specific tags/branches. Thus, e.g. we call a salt runner providing a saltenv as a parameter. We have adapted our master configuration to then pull only from a git branch/tag that is equal to the saltenv. 

This, however, does not seem to work with the local file server. It seems that you are required to always specify specific saltenvs for file_roots in the master config.

Example:
Imagine having a branch X in git. You are calling salt via "salt-run [...] saltenv=X". In that case anything in the local salt file server would not be found, unless you also specifically mentioned X in the master config. 

### Question
The question is if something like *__env__* also exists for file_roots - enabling you to specify one path on a local file server for *all* saltenvs?

### Setup
Please find below a sanitized master configuration showing the issue:
```
state_top: salt://top.sls

fileserver_backend:
  - git
  - roots
file_roots:
  base:
    - /srv/salt
    - /srv/tops
pillar_roots:
  base:
    - /srv/pillar
  __env__:
    - /srv/pillar
pillarenv_from_saltenv: True

ext_pillar_first: True
ext_pillar:
  - git:
    - __env__ gitlab:Automation/salt:
      - root: pillar

gitfs_remotes:
  - gitlab:Automation/salt:
    - root: states

# Merge strategies
pillar_source_merging_strategy: recurse
top_file_merging_strategy: same
pillar_merge_lists: True
```

### Steps to Reproduce Issue
1. Have local file server with an sls for a runner
2. Have a git repository with a branch X. Ensure that the runner requires something that is on branch X
3. Ensure master config allows for dynamic usage of git branches via saltenv, but only specify base for file_roots
4. Call salt-run with the runner against a saltenv X
5. Salt-run will fail, because it cannot find the runner

### Versions Report
Salt Version:
           Salt: 2017.7.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-119-generic
         system: Linux
        version: Ubuntu 16.04 xenial
