### ISSUE TITLE
How to check which are the Salt capabilities available on the minion?

### ISSUE THREAD

**Issue by meaksh** [saltstack/salt#48153]
### Description of Issue/Question
When writing SLS files for states, it would be really useful to know if the Salt version installed on the minion is providing certain feature/capability.

I would really like a mechanism that allows something like this in an SLS state file:

```yaml
apply_SUSE-SLE-SERVER-12-SP3-2018-964_patch:
{% if "ZYPPER_PATCH_INSTALLATION" in grains.get('salt_capabilities', []) %}
  pkg.patch_installed:
    - advisory_ids:
      - SUSE-SLE-SERVER-12-SP3-2018-964
{% else %}
  pkg.installed:
    - pkgs:
      - libpython2_7-1_0: 2.7.13-28.3.2
      - python: 2.7.13-28.3.2
      - python-base: 2.7.13-28.3.2
      - python-curses: 2.7.13-28.3.2
      - python-xml: 2.7.13-28.3.2
{% endif %}
```

So it's easy to establish a workaround in case the needed Salt capability is not available.

I've created a PR to introduce an RFC where we can discuss about ideas and different approach to achieve this: https://github.com/saltstack/salt/pull/48152

Thanks!
