### ISSUE TITLE
virtualenv pip.freeze error

### ISSUE THREAD

**Issue by amuhametov** [saltstack/salt#48200]
### Description of Issue/Question
Getting error after update 2016.11.6->2017.7.6

      Name: /usr/local/python36/venv
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1879, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1826, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/virtualenv_mod.py", line 277, in managed
                  before = set(__salt__['pip.freeze'](bin_env=name, user=user, use_vt=use_vt))
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1119, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 98, in __getitem__
                  return self._dict[key]
              KeyError: 'pip.freeze'

Seems like to be related to #46242

### Setup
```
python36-venv:
  virtualenv.managed:
    - name: /usr/local/python36/venv
    - venv_bin: '/opt/rh/rh-python36/root/usr/bin/virtualenv'
    - python: 'python3.6'
    - system_site_packages: False
    - requirements: salt://{{ tpldir }}/files/requirements.txt
```
### Versions Report
```
Salt Version:
           Salt: 2017.7.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
