### ISSUE TITLE
runner cannot import modules after upgrading to 2018.3.1

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#48221]
I have some custom runners located at ` /usr/local/etc/salt/runner`.
And I also have a lib folder `/usr/local/etc/salt/runner/lib`
Some of my runners need to import modules from this `lib` folder and they all have lines like `from lib import something`

This has stopped working since I upgraded salt to 2018.3.1
The error I got is ` __virtual__ returned False: No module named 'lib'`

However, if I deleted `__pycache__` directory from `/usr/local/etc/salt/runner`, my runners can successfully run and will stop to run for a second time because the `__pycache__` was recreated and I have to remove `__pycache__` again to get the runners to run.

Is this related to some environment configuration or something wrong with salt loader?

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.12
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.5 (default, Apr  5 2018, 13:37:49)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p9
         system: FreeBSD
        version: Not Installed

```
