### ISSUE TITLE
Windows 2012r2 unable to use proxy module, or state.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#48276]
### Description of Issue/Question

Current when trying to use the proxy state the proxy module will throw an error if the proxy has not been previously setup on windows 2012r2. 

```
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1905, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1830, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\proxy.py", line 114, in managed
    current_settings = __salt__['proxy.get_proxy_win']()
  File "C:\salt\bin\lib\site-packages\salt\modules\proxy.py", line 386, in get_proxy_win
    return _get_proxy_windows()
  File "C:\salt\bin\lib\site-packages\salt\modules\proxy.py", line 66, in _get_proxy_windows
    if "=" in servers:
TypeError: argument of type 'NoneType' is not iterable
```

This looks to be because 

`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\`
`ProxyServer` 

This doesn't exist by default only after it is set.

### Setup

```
cat /srv/salt/proxy-test.sls
192.168.70.11:
  proxy.managed:
    - port: 8080
    - bypass_domains:
      - localhost
      - 127.0.0.1
```

```
local:
    ----------
    comment:
        Cannot find ProxyServer in HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings
    hive:
        HKEY_CURRENT_USER
    key:
        SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings
    success:
        False
    vdata:
        None
    vname:
        ProxyServer
```

This happens if using salt-call with a logged in user so this isn't a missing hive issue.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Run the above windows state on a fresh windows 2012 r2 image.

### Versions Report
```
winion-0:
    Salt Version:
               Salt: 2018.3.1

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
```

Looking at the history on the proxy module This is not a regression. Older versions will still have the same issue.
