### ISSUE TITLE
Mount.mounted is incompatible with devices that can be mounted multiple times

### ISSUE THREAD

**Issue by dpedu** [saltstack/salt#48280]
### Description of Issue/Question

I use glusterfs, which is a network filesystem. Sometimes I mount a glusterfs volume read/write at one mountpoint, and read-only at another mountpoint. But the `mount.mounted` state doesn't let me do this.

When this state is used, the application of the second mountpoint removes the first one. I can't find a way through the other options of `mount.mounted` to have both coexist. 

### Setup

Sls state file:

```
/mnt/realm:
  mount.mounted:
    - device: core00:/realm2
    - fstype: glusterfs
    - mkmnt: True
    - require:
      - pkg: glusterfs-client

/mnt/realmro:
  mount.mounted:
    - device: core00:/realm2
    - fstype: glusterfs
    - mkmnt: True
    - opts: ro
    - require:
      - pkg: glusterfs-client
```

### Steps to Reproduce Issue

1) Apply the above state
2) Observe that only one mount is created, and each time they overwrite eachother

### Versions Report

```Salt Version:
           Salt: 2018.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ISO-8859-1
        machine: x86_64
        release: 4.15.0-23-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

No difference in master/minion version.
