### ISSUE TITLE
[BUG] retry clause doesn't clean up in pkgrepo

### ISSUE THREAD

**Issue by kiemlicz** [saltstack/salt#48285]
### Description of Issue/Question
`retry` logic doesn't retry dependent states upon each failure.  
It is sort-of documented behavior but this is very limited and doesn't take cache into account.
It should be possible to perform retry with dependent states

### Setup
e.g. have some state that writes something to cache (like downloaded repo key)
```
some_repo_to_configure:
  pkgrepo.managed:
    - names: {{ some_repo.repo_entries|json_decode_list }}
    - keyid: {{ some_repo.keyid }}
    - keyserver: {{ some_repo.keyserver }}
    - file: {{ some_repo.file }}
    - retry:
      - until: True
      - attempts: 3
      - interval: 10
...
```
imagine that the key itself was broken during download (e.g. somehow zero-length key got saved).
Now every `retry` attempt the key is not downloaded again because it is found in cache and state fails every time.
For pkgrepo, trying to workaround this by having something like:
```
rescue_repo:
  pkgrepo.absent:
    - names: {{ some_repo.repo_entries|json_decode_list }}
    - keyid: {{ some_repo.keyid }}
some_repo_to_configure:
  pkgrepo.managed:
    - names: {{ some_repo.repo_entries|json_decode_list }}
    - keyid: {{ some_repo.keyid }}
    - keyserver: {{ some_repo.keyserver }}
    - file: {{ some_repo.file }}
    - require:
      - pkgrepo: rescue_repo
    - retry:
      - until: True
      - attempts: 3
      - interval: 10
...
```
doesn't help as dependent state is not retried (`retry` only refers to current function)
Is it possible to extend saltstack behavior to mark that dependent states should be retried as well?
Or is it bug in `pkgrepo.managed` state?
Either way `retry` is perfect fit for pkgrepo states as often configuring external repo fails due to some external slow server and retry is a life saver.

### Steps to Reproduce Issue
Already stated

### Versions Report
```
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: 1.10.6
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.1
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
         locale: UTF-8
        machine: x86_64
        release: 4.11.8-no5kill
         system: Linux
        version: debian 9.4

```

**Comment by gtmanfred** [comment]
That is not how require + retry work together, The required state has already succeeded, so the pkgrepo.managed state just needs to run.

If you know that a key to download because a remote server is under heavy load, maybe use a file.managed to directly get the key first, and put your retry on that state, to get the correct file (with a source_hash), so that you know for sure that the file actually gets downloaded.

**Comment by kiemlicz** [comment]
Thank you for response, please let me present my point of view.

I agree about `require` relation however it is not that clear with `onfail`
Currently retries are part of the single state execution and can cause **only one** `onfail` execution.
However I think that more natural would be having as many `onfail` executions as failures within retries

Example (I would expect three different temp files created under `/tmp`) :
```
always-fails:
  test.fail_without_changes:
    - name: foo
    - retry:
      until: True
      attempts: 3
      interval: 2
      splay: 15

rescue:
  module.run:
    - name: temp.file
    - prefix: res
    - parent: /tmp
    - onfail:
      - test: always-fails
```
As of aforementioned `pkgrepo` - somehow I don't like the proposed solution  
After all the `pkgrepo.managed` failed in one of its steps, the retry should retry all of them just the way first run did, what do you think?
