### ISSUE TITLE
Requisite - executing cmd when watched state has not changed

### ISSUE THREAD

**Issue by GitHubAre** [saltstack/salt#48338]
### Description of Issue/Question
Hello,

I have ran into a strange scenario, where I would like to execute a powershell script when a state that this script depends on does not perform any changes.

Right now there is a **Watch** or **Onchanges** requisite that is executing state (script) when the watched state has changed.

I am using this "weird" behavior in startup sls file.

### Setup
I have this in my sls:

```
manage_pagefile:
  cmd.run:
    - name: '{{ pillar['pagefile_powershell_script_fullname'] }} -DriveLetter {{ pillar['virtual_memory_drive_letter'] }}'
    - shell: powershell
    - stateful: True

reboot if needed:
  system.reboot:
    - only_on_pending_reboot: True
    - in_seconds: True
    - timeout: 5
    - onchanges:
      - cmd: manage_pagefile

copy_disk_init_script:
  file.managed:
    - name: {{ pillar['init_disks_script_fullname'] }}
    - source: salt://scripts/{{ pillar['init_disks_script_name'] }}
    - require:
      - cmd: manage_pagefile

init_disks:
  cmd.run:
    - name: '{{ pillar['init_disks_script_fullname'] }} -DriveLettersToExclude {{ pillar['virtual_memory_drive_letter'] }} -DvdDriveLetter {{ pillar['dvd_drive_letter'] }}'
    - shell: powershell
    - stateful: True
    - require:
      - file: copy_disk_init_script
```

I am struggling with the

```
copy_disk_init_script:
  file.managed:
    - name: {{ pillar['init_disks_script_fullname'] }}
    - source: salt://scripts/{{ pillar['init_disks_script_name'] }}
    - require:
      - cmd: manage_pagefile
```

As I would like to execute it only when `cmd: manage_pagefile` didnt change the system (it is stateful script).

**Comment by Ch3LL** [comment]
hmmm interesting I don't think we have a requisite that will run only if there are no changes. Can you just use an onlyif instead?

For example in your powershell script make sure you add a file or something like that 
adn then in the `file.managed` state you can add an onlyif logic to check for that file

**Comment by GitHubAre** [comment]
Can I execute inline PowerShell inside the onlyif?
I think by default it will be cmd.exe on Windows.

I tried this:
```
init_disks2:
  cmd.run:
    - name: '{{ pillar['init_disks_script_fullname'] }} -DriveLettersToExclude {{ pillar['virtual_memory_drive_letter'] }} -DvdDriveLetter {{ pillar['dvd_drive_letter'] }}'
    - shell: powershell
    - onlyif:
      - if %is_pagefile_setup_finished% == true (echo true)else (echo false)
```

and this:
```
init_disks2:
  cmd.run:
    - name: '{{ pillar['init_disks_script_fullname'] }} -DriveLettersToExclude {{ pillar['virtual_memory_drive_letter'] }} -DvdDriveLetter {{ pillar['dvd_drive_letter'] }}'
    - shell: powershell
    - onlyif:
      - if %is_pagefile_setup_finished% == true (exit /b 0)else (exit /b 1)
```

But result was always:
```
----------
          ID: init_disks2
    Function: cmd.run
        Name: c:\salt_workspace\Init-Disks.ps1 -DriveLettersToExclude s -DvdDriveLetter w
      Result: True
     Comment: onlyif condition is false: if %is_pagefile_setup_finished% == true (echo true)else (echo false)
     Started: 10:52:27.399148
    Duration: 360.221 ms
     Changes:
```

Even when environment variable is_pagefile_setup_finished is existing and has value of true

**Comment by Ch3LL** [comment]
windows is not my strong area but can't you called powershell from cmd.exe? 

ping @saltstack/team-windows will probably have better ideas here

**Comment by morganwillcock** [comment]
@GitHubAre I think there are various ways to do this, but it does depend on what is in the scripts if you are using `stateful: True`. Are you returning JSON or some variation of key=value?

If you were able to the post the scripts, I'm happy to try them out and try to give you a working state file back. It'll probably be a lot easier to change the logic slightly and use `OnlyIf` to check an exit code, or use templating to remove tasks already done (if you are setting an environment variable the process would need to restart anyway to be able to see the change).

Using Powershell should be fine, as long as the exit code is getting set (if relying on the exit code), or you are outputting something (to use with `stateful: True`).

**Comment by GitHubAre** [comment]
@morganwillcock this is simplified powershell script that is invoked from the sls file (ps file is named Set-VirtualMemoryForAzureVms.ps1):

```
function Set-StatefulNoChange()
{
    Write-Host "";
    Write-Host "changed=Yes comment='No change required'"
    exit 0;
}

function Set-StatefulChanged()
{
    Write-Host "";
    Write-Host "changed=No comment='Virtual memory settings changed - reboot will be required'"
    exit 0;
}

if($currentOption -eq 'SystemManagedSize' -and $isUsingDesiredDriveLetter)
{
    Write-Host "Virtual Memory is already at desired state."
    Set-StatefulNoChange
}

if($isUsingDesiredDriveLetter)
{
    write-host "drive letter is already used, but with wrong options."
    SetPageFileSize -DL $DriveLetterWithColon -InitialSize $initialSize -MaximumSize $maximumSize
    Set-StatefulChanged;
}

if(![string]::IsNullOrEmpty($currentDriveLetter) -and $currentDriveLetter -ne $DriveLetter -and $currentDriveLetter -ne 'c')
{
    Write-Host "Setting PagingFile to C: drive";
    SetPageFileSize -DL "C:" -InitialSize $initialSize -MaximumSize $maximumSize
    Write-Host "Setting PagingFile to None on $currentDriveLetter";
    $PageSetting.Delete()
    Set-StatefulChanged;
}


if($azureTempDriveLetter -eq $DriveLetter)
{
    if($currentDriveLetter -eq "c")
    {
        Write-Host "Removing pagefile from C: drive";
        $PageSetting.Delete();
    }
    Write-Host "Setting PagingFile to $DriveLetter";
    SetPageFileSize -DL $DriveLetterWithColon -InitialSize $initialSize -MaximumSize $maximumSize;
    Set-StatefulChanged;
}
```

Sls file :

```
manage_pagefile:
  cmd.run:
    - name: 'c:\Set-VirtualMemoryForAzureVms.ps1 -DriveLetter S'
    - shell: powershell
    - stateful: True
    - require:
      - file: copy virtual memory script to minion
      - system: join_pe_active_directory

reboot if needed:
  system.reboot:
    - only_on_pending_reboot: True
    - in_seconds: True
    - timeout: 5
    - require:
      - cmd: manage_pagefile

copy_disk_init_script:
  file.managed:
    - name: {{ pillar['init_disks_script_fullname'] }}
    - source: salt://scripts/{{ pillar['init_disks_script_name'] }}
    - onchanges:
      - cmd: manage_pagefile

init_disks:
  cmd.run:
    - name: '{{ pillar['init_disks_script_fullname'] }} -DriveLettersToExclude {{ pillar['virtual_memory_drive_letter'] }} -DvdDriveLetter {{ pillar['dvd_drive_letter'] }}'
    - shell: powershell
    - watch:
      - file: copy_disk_init_script
```

The uncool solution was that I am having inverted logic in functions that are terminating script:
```
function Set-StatefulNoChange()
{
    Write-Host "";
    Write-Host "changed=Yes comment='No change required'"
    exit 0;
}
```

And then when nothing has changed I am triggering **copy_disk_init_script** state using the **onchanges** requisite.

**Comment by morganwillcock** [comment]
@GitHubAre I think you can probably use `wmic` to avoid the need to return the state as text, and also use it to apply the settings. Something like this should work, but it depends on whether you need to still run the scripts to set something else:

<pre>set_pagefile_to_manual:
  cmd.run:
    - name: wmic computersystem set AutomaticManagedPagefile=False
    - onlyif: wmic computersystem where AutomaticManagedPagefile=True | findstr /r .

configure_page_file:
  cmd.run:
    - name: wmic pagefileset where name="{{ pillar['virtual_memory_drive_letter'] }}:\\pagefile.sys" set InitialSize={{ pillar['virtual_memory_initial'] }},MaximumSize={{ pillar['virtual_memory_max'] }}
    - onlyif: wmic pagefileset where 'name="{{ pillar['virtual_memory_drive_letter'] }}:\\pagefile.sys" and not (InitialSize={{ pillar['virtual_memory_initial'] }} and MaximumSize={{ pillar['virtual_memory_max'] }})' | findstr /r .
    - require:
      - cmd: set_pagefile_to_manual

reboot_for_page_file_changes:
  system.reboot:
    - timeout: 10
    - in_seconds: True
    - only_on_pending_reboot: False
    - onchanges:
      - cmd: set_pagefile_to_manual
      - cmd: configure_page_file

failhard_for_reboot:
  test.fail_without_changes:
    - failhard: True
    - onchanges:
      - system: reboot_for_page_file_changes</pre>

The last state makes sure that anything after the reboot won't run, and the master actually gets some data back before the reboot happens, so potentially you may not need this if the reboot state is always your final state. If you do need to optionally do something, as long as the pre-requisite states always returns the changes correctly, you can generally just use `onchanges` to make something only run when needed. In this case the return code from `findstr` can be used for a negative check, since `wmic` writes to stderr when no instance is matched.

**Comment by GitHubAre** [comment]
@morganwillcock Thanks for the nice point out!
The final solution which I am using is still through PowerShell (I have more logic in that script than I pasted here and I cannot replace it by single command line).
What I did is that I have created macro as this:
```
{%- macro reboot_with_failhard(reboot_id, onchanges_state, force = True, requsite_type = 'onchanges') %}
{{ reboot_id }}:
  system.reboot:
    - only_on_pending_reboot: {{ not force }}
    - in_seconds: True
    - timeout: 5
    - {{ requsite_type }}:
      - {{ onchanges_state }}

fail_after_{{ reboot_id }}:
  test.fail_without_changes:
    - failhard: True
    - onchanges:
      - system: {{ reboot_id }}
{%- endmacro %}
```

Inside my .sls file I am using it as follows (on multiple places):
```
manage_pagefile:
  cmd.run:
    - name: '{{ pillar['pagefile_powershell_script_fullname'] }} -DriveLetter {{ pillar['virtual_memory_drive_letter'] }}'
    - shell: powershell
    - stateful: True
    - win_inheritance: True
    - require:
      - file: copy windows scripts
      - system: join_pe_active_directory

{{ reboot_with_failhard('reboot_pagefile_changed', 'cmd: manage_pagefile') }}
```
I have also set global setting to **failhard** on first error.
The reason why I am doing it like this, is because I am using startup states (https://docs.saltstack.com/en/latest/ref/states/startup.html) and I am counting on that after the reboot the machine will run through the same state again (but will not reboot at the step where it rebooted the first time, because the particular setting is already altered and does not require reboot).
