### ISSUE TITLE
cmd.script and creates as dependancy

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#48335]
Hi,

When declaring a cmd.run or cmd.script that "creates" a file, this file cannot be use as a dependency.
I come from Puppet and this seems to be unnatural, is this the expected behavior ?

Best regards

**Comment by Ch3LL** [comment]
can you elaborate on what you mean by "cannot be used as a dependency"? Not quit sure what you are trying to do

**Comment by Poil** [comment]
If I do this

```
myapp_openssl:
  cmd.script:
    - name: "openssl_{{ myapp.pkg.openssl.version }}_{{ myapp.pkg.openssl.patch }}.x86_64 --clean install"
    - source: "http://repo/salt-files/el7/ORANGE_openssl_{{ myapp.pkg.openssl.version }}_{{ myapp.pkg.openss
    - creates: "/opt/openssl_{{ myapp.pkg.openssl.version }}/bin/openssl"
```

When I use a require I can do `require: myapp_openssl`, but the resource have created  "/opt/openssl_{{ myapp.pkg.openssl.version }}/bin/openssl", so the first time I wrote : `require:  "/opt/openssl_{{ myapp.pkg.openssl.version }}/bin/openssl"` but this resource does not exist.

Best regards,
