### ISSUE TITLE
[Need Info] GitFS multiple remotes as file://...

### ISSUE THREAD

**Issue by importepeu** [saltstack/salt#48444]
### Description of Issue/Question
Hi, I would be pleased to have any help to understand a weird situation. I have two git repositories, one for states/formulas and one for minions grains that I want to manage in centralized manner. Both repositories use only the master branch but are referenced as "dev" as environnement.

I've ran "a salt-run fileserver.file_list" and effectively saw states and minions files from my repos. But when I try to reference my minion file in state using salt://<path_to_minion_file> it is written that my file isn't found in debug logs.

Regarding the Git FS backend doc, it is written that salt searchs files in the ordered list of repositories so I don't understand why my file is "not found". In the "multiple remotes" section of the GitFS backend doc, it is written something about "local refs" : 

> This means that any refs you want accessible must exist as local refs in the specified repo.

 But I don't really get what "local refs" means as my files are already in local filesystem...

### Setup
Here is my gitfs configuration installed in masters/syndics
```
# cat /etc/salt/master.d/gitfs.conf
fileserver_backend:
  - git

gitfs_remotes:
  - file:///srv/salt/repositories/saltTrees/dev/states.git:
    - disable_saltenv_mapping: True
    - saltenv:
      - dev:
        - ref: master
  - file:///srv/salt/repositories/saltTrees/dev/grains.git:
    - disable_saltenv_mapping: True
    - saltenv:
      - dev:
        - ref: master
  - file:///srv/salt/repositories/saltTrees/prod/states.git:
    - disable_saltenv_mapping: True
    - saltenv:
      - prod:
        - ref: master
```

The "file:///srv/salt/repositories/saltTrees/dev/states.git" repo contains for example :
```
README.md
lib/init.sls
orch/applyConf.sls
react/event.sls
salt/masters/config.sls
salt/masters/init.sls
```

The "file:///srv/salt/repositories/saltTrees/dev/grains.git" repository contains for example one grain file for minion "ulgcysui50":
`minions/ulgcysui50`

Here is the fileserver.list which displays both "dev" repositories in the tree :
```
# salt-run fileserver.file_list saltenv=dev
- README.md
- lib/init.sls
- minions/ulgcysui50
- orch/applyConf.sls
- react/event.sls
- salt/masters/config.sls
- salt/masters/init.sls
```

When I try this command, it doesn't work (file not found in debug logs):
```
# salt 'ulgcysui50' cp.get_file salt://minions/ulgcysui50 /tmp/test saltenv=dev
ulgcysui50:
#
```

But when I add a '/minions/ulgcysui50' file in the states.git repository, it works :
```
# salt 'ulgcysui50' cp.get_file salt://minions/ulgcysui50 /tmp/test saltenv=dev
ulgcysui50:
    /tmp/test
#
```

Same thing when referencing the minion file in states... Why salt is not finding my minion file in the grains.git repo ?
Any help would be very appreciated. Best regards,
Guillaume.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
# salt --versions-report
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: 1.5.2
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-128-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
