### ISSUE TITLE
pkgrepo.managed should support proxy option

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#48451]
Hi,

With yum it's sometime useful to configure the proxy in the repo configuration to overload the yum.conf configuration

Example I have some local repository that does not use the proxy.
```
[standard-rhel7-extras]
name=YUM $releasever - $basearch
baseurl=http://myrepo.local/rhel7/standard-rhel7-extras/
enabled=1
proxy=_none_
```

Best regards,

**Comment by Ch3LL** [comment]
If you add `-proxy: <proxy options>` to the state module it does not set the proxy still? It looks like kwargs is passed to the module so I think this should work.

**Comment by Poil** [comment]
Yes that is what I've seen when I would like to patch the code.
Perhaps we should add a notes in the documentation about that ?

**Comment by Ch3LL** [comment]
ya i can label as a documentation bug for sure

**Comment by xenadmin** [comment]
I would love to see this documentation updated, as I have constantly the following error, when Debian apt only works with a proxy:
```
----------
          ID: zabbix_proxy_repo
    Function: pkgrepo.managed
        Name: deb https://repo.zabbix.com/zabbix/5.0/debian stretch main
      Result: False
     Comment: Failed to configure repo 'deb https://repo.zabbix.com/zabbix/5.0/debian stretch main': Error: HTTP 599: Timeout while connecting reading https://repo.zabbix.com/zabbix-official-repo.key
     Started: 16:40:22.032928
    Duration: 20072.86 ms
     Changes:   
----------
```
It works every time I do it on the command line, as I set the proxy in the apt.conf.

**Comment by xenadmin** [comment]
How can we re-open this issue?

**Comment by fdamstra** [comment]
+1 for this issue. Proxy is still ignored when adding with a key.

```
teleport:
  pkgrepo.managed:
    - humanname: Teleport
    - name: deb https://deb.releases.teleport.dev/ stable main
    - dist: stable
    - file: /etc/apt/sources.list.d/teleport.list
    - gpgcheck: 1
    - key_url: https://deb.releases.teleport.dev/teleport-pubkey.asc
```

The proxy is configured throughout the system: in /etc/environment and in /etc/apt/apt.conf.d (among other unrelated places), but applying the state gives the same error:
```
Failed to configure repo 'deb https://deb.releases.teleport.dev/ stable main': Error: HTTP 599: Timeout while connecting reading https://deb.releases.teleport.dev/teleport-pubkey.asc
```

**Comment by Arnieh** [comment]
I agree the proxy issue should be solved when downloading the gpg-key for repo's to be added.

For now I downloaded the key to the salt-master and set that file as key_url. Below the updated .sls for @fdamstra:
```
teleport:
  pkgrepo.managed:
    - humanname: Teleport
    - name: deb https://deb.releases.teleport.dev/ stable main
    - dist: stable
    - file: /etc/apt/sources.list.d/teleport.list
    - gpgcheck: 1
    - key_url: salt://teleport/teleport-pubkey.asc
```
