### ISSUE TITLE
Help needed: unicode' object has no attribute

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack/salt#48504]
### Description of Issue/Question
I'm having great difficultly getting dict passed into a jinja2 macro in a pull request (https://github.com/saltstack-formulas/iscsi-formula/pull/2). I'd appreciate any advice of help...
```
          ID: iscsi_target_service_config
    Function: file.managed
        Name: /etc/tgt/conf.d/targets.conf
      Result: False
     Comment: Unable to manage file: Jinja error: 'unicode' object has no attribute 'items'
              /var/cache/salt/minion/files/base/iscsi/files/macros.jinja(2):
              ---
              {%- macro makeoutput(outdict, spaces=0, mapdiv='', kvdiv='', end='', quote='', comma='') -%}
              {%- for key, value in outdict|dictsort -%}    <======================
              {{ output(key, value, spaces, mapdiv, kvdiv, end, quote, comma,) }}
              {%- endfor -%}
              {%- endmacro -%}
              
              {%- macro output(key, value, spaces, mapdiv, kvdiv, end, quote, comma) -%}
              [...]
              ---
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 389, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 20, in top-level template code
                File "/var/cache/salt/minion/files/base/iscsi/files/macros.jinja", line 2, in template
                  {%- for key, value in outdict|dictsort -%}
                File "/usr/lib/python2.7/dist-packages/jinja2/filters.py", line 223, in do_dictsort
                  return sorted(value.items(), key=sort_func)
              AttributeError: 'unicode' object has no attribute 'items'
     Started: 22:26:58.454215
    Duration: 80.555 ms
     Changes:  
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

I wiped the instance. Versions were vagrant-Ubuntu 14/Trusty and Salt 2018.3.2

**Comment by Ch3LL** [comment]
can you share sanitized version of the pillar you are using. I saw there was multiple examples of pillar in `pillar.example`.

**Comment by noelmcloughlin** [comment]
Hi @Ch3LL I'm used this stanza from `pillar.example` during testing on Ubuntu 14.04.

#Create some targets on Linux (targets.conf)
```
iscsi:
  targetd:
    tgt:
      globals:
        iSNSServerIP: 127.0.0.1
        iSNSAccessControl: 'On'
        iSNS: 'On'
      targets:
        'iqn.2018-07.com.example.iscsi:example01':
          globals:
            initiator_address:
              - 127.0.0.1
              - 127.0.0.2
          backing_stores:
            /dev/vg00/example01:
              vendor_id: Example, Inc.
              scsi_id: targetdisk
          direct_stores:
            /dev/sdb:
            initiator_address:
              - 127.0.0.3
              - 127.0.0.4
        'iqn.2018-07.com.example.iscsi:example02':
          direct_stores:
            /dev/sdd:
```
