### ISSUE TITLE
Feature: grain ip4_routes

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#48500]
### Description of Issue/Question
It would be nice to have grain containing entries from routing table.  There are sometimes situation when configuration must depends on entries in routing table.

Proposed example output:
```
ip4_routes:
  - dst: 172.20.0.0/16
    dev: br-b472ad8a72d1
    proto: kernel
    scope: link
    src: 172.20.0.1
  - dst: default
    via: 172.27.100.126
    dev: enp0s31f6
    proto: static
    metric: 100
```

Maybe it would be better to always provide unused keys ?
```
ip4_routes:
  - dst: 172.20.0.0/16
    dev: br-b472ad8a72d1
    proto: kernel
    scope: link
    src: 172.20.0.1
    via:
    metric:
```

I could try to provide such grain if approved.
