### ISSUE TITLE
Feature: grains kernelparams

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#48501]
### Description of Issue/Question
It would be nice to have grain containing kernel boot parameters. We are using it to plug in some configuration when kernel has some specific parameter.

Example output:
```
kernelparams:
  KEYTABLE: us
  LANG: en_US.UTF-8
  SYSFONT: latarcyrheb-sun16
  quiet: null
  rd_LVM_LV: VolGroup/lv_root
  rd_NO_DM: null
  rd_NO_LUKS: null
  rd_NO_MD: null
  rhgb: null
  ro: null
  root: /dev/mapper/VolGroup-lv_root
```

I could try to provide such grain if approved.
