### ISSUE TITLE
mysql_grants.present escape option incorrectly reports failure

### ISSUE THREAD

**Issue by emersonveenstra** [saltstack/salt#48507]
### Description of Issue/Question

Setting the `escape: False` for `mysql_grants.present` returns a failure, but the grant is applied correctly

### Setup

```yaml
check test mysql grant:
  mysql_grants.present:
    - grant: all privileges
    - database: "test.*"
    - user: test
    - host: '%'
    - escape: False
```

### Steps to Reproduce Issue
Run the above SLS file. The output on the salt master is:
```
----------
ID: check test mysql grant
    Function: mysql_grants.present
      Result: False
     Comment: Failed to execute: "GRANT all privileges ON test.* TO test@%"
     Started: 17:06:10.161363
    Duration: 45.931 ms
     Changes:   
```

however, looking at the mysql grants, the check test mysql grant actually succeeded correctly

```
+-------------------------------------------------------------------------------------------------------------+
| Grants for test@%                                                                                   |
+-------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'test'@'%' IDENTIFIED BY PASSWORD '*[censored]' |
| GRANT ALL PRIVILEGES ON `test`.* TO 'test'@'%'                                              |
+-------------------------------------------------------------------------------------------------------------+

```

### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
Both master and minion are the same version
