### ISSUE TITLE
Documentation of artifactory.downloaded does not agree with operation

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#48515]
### Description of Issue/Question

Calling artifactory.downloaded using code like the documentation produces an error response. 

The arguments show in the example are rejected as "invalid keyword arguments".  Since Salt Fluorine will be out soon (and since there is no documentation of what the keywords are supposed to do) the documentation needs to be updated to provide a call that actually works.  We are told to update our state files, but have no idea how.

### Setup

I have stored ("deployed") a file to a generic artifactory repo, such that the artifactory web interface says that the "full file path" is `http://p-artifactory.imovetv.com/artifactory/dyna-windows-local/bcertdump.exe`.

The "imovetv.com" domain is only accessible from our intranet. If I paste the above URL into FireFox, it offers to download the file.

The documentation has the example:
```
jboss_module_downloaded:
  artifactory.downloaded:
   - artifact:
       artifactory_url: http://artifactory.intranet.example.com/artifactory
       repository: 'libs-release-local'
       artifact_id: 'module'
       group_id: 'com.company.module'
       packaging: 'jar'
       classifier: 'sources'
       version: '1.0'
   - target_file: /opt/jboss7/modules/com/company/lib/module.jar
```

### Steps to Reproduce Issue
 
Cut the above into a state file, and edit it to contain...
```
bcertdump:
  artifactory.downloaded:
    - artifact:
      artifactory_url: http://p-artifactory.imovetv.com/artifactory
      repository: 'dyna-windows-local'
      artifact_id: 'bcertdump.exe'
    - target_file: C:/Users/dynamux/bcertdump.exe
```
Executing the above state gives:
```
----------
          ID: bcertdump
    Function: artifactory.downloaded
      Result: False
     Comment: argument of type 'NoneType' is not iterable
     Started: 21:08:56.213000
    Duration: 0.0 ms
     Changes:
    Warnings: 'artifact_id', 'repository' and 'artifactory_url' are invalid
              keyword arguments for 'artifactory.downloaded'. If you were trying
              to pass additional data to be used in a template context, please
              populate 'context' with 'key: value' pairs. Your approach will
              work until Salt Fluorine is out. Please update your state files.
```

### Versions Report
```
vernoncole@bevymaster:~$ sudo salt win16 test.versions_report
win16:
    Salt Version:
               Salt: 2018.3.0

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.7
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: 0.27.1
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: 0.27.1
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393  Multiprocessor Free
```
```
vernoncole@bevymaster:~$ sudo salt --versions-report
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
