### ISSUE TITLE
Is it possible to have a requisite based on grain, pillar or jinja boolean response ?

### ISSUE THREAD

**Issue by thechile** [saltstack/salt#48540]
Hi, is it possible to use a `true|false` type return value as requisite control  ? Same as you can do in chef basically.

The current requisites all seem to shell out. I would like **not** to check the success or failure of a defined state but just determine if the state should be included in the highstate run based on the value of one or more grains or pillars. 

e.g. 

```
file.managed:
    - name: /etc/ntp.conf
    - source: salt://ntp/files/ntp.conf
    - only_if: salt['grains.get']('someGrain', False) 
    - not_if: salt['pillar.get']('somePillar', False) 
    - only_if: {{ some inline jinja here... must resolve to true|1 or false|0 }}
```
I know i could wrap this in a {% if ... %} block but it seems messy compared to the above.

Does this functionality exist ? 

Many thanks
