### ISSUE TITLE
sdb rest - header dict as jinja ?

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#48568]
Hi,

I have a REST API, that's first need to authenticate via a basic auth, it returns a temporary token that I must pass in the next query.

I'm able to authenticate and I'm able to get the token but, I'm unable to pass this token, via header_dict because it doesn't support Jinja.

I think I could use a temporary file for this header but for something some simple, I would like to patch sdb/rest.py to allow the use of a jinja variable in header_dict.

Does it makes sense ?

**Comment by Poil** [comment]
FYI, my current configuration

```
phpipam-api:
  driver: rest
  urls:
    url: http://ipam.xxx/api/
  auth:
    url: https://ipam.xxx/api/flexssl/user/
    backend: requests
    method: POST
    username:user_api
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  get-free-ip:
    url: https://ipam.xxx/api/flexssl/addresses/first_free/{{ subnet_id }}/
    backend: requests
    header_dict:
      token: "{{ token }}"
```
