### ISSUE TITLE
Env for npm when Salt runs via sudo 

### ISSUE THREAD

**Issue by wyardley** [saltstack/salt#48589]
### Description of Issue/Question
When installing packages from a private repo in test kitchen (using sudo), root's `.npmrc` is not read (for the token) unless env => `HOME` is explicitly set.
Also, it's not clear if env can be set for bootstrap?
 
### Setup
Test kitchen, with the default sudo command (`sudo -E`, though I think running without `-E` surprisingly didn't help).

```yaml
npm_/root/.npmrc_file:
  file.managed:
    - name: /root/.npmrc
    - show_changes: False
    - source: salt://{{ slspath }}/files/root/dot_npmrc
    - template: jinja
    - mode: '0600'
    - user: root
    - group: root

npm-packages-foo:
  npm.installed:
    - pkgs:
      - '@myorg/foobar-widget@^0.0.1'
```

### Steps to Reproduce Issue
See above.

Adding
```yaml
  npm.installed:
    - env:
      - HOME: /root
      - cwd: /root
```
seems to fix (I think only `HOME` is needed).

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
In test kitchen instance (but doesn't seem to matter, I think)

```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.87-linuxkit-aufs
         system: Linux
        version: Ubuntu 16.04 xenial
```
