### ISSUE TITLE
 2018.3.2 salt doesn't support multi file.managed

### ISSUE THREAD

**Issue by like-inspur** [saltstack/salt#48618]
I use salt master and salt minion that version is 2018.3.2 (Oxygen). I want to install service which need mutil config file and watch multi config file change according to https://docs.saltstack.com/en/latest/ref/states/requisites.html. So I create install script like this:
```
node-exporter-script:
  file.managed:
    - name: /opt/node_exporter
    - source: salt://node-exporter-script/node_exporter
    - mode: 755
  file.managed:
    - name: /opt/node_exporter_start.sh
    - source: salt://node-exporter-script/node_exporter_start.sh
    - mode: 755
  cmd.run:
    - name: /opt/node_exporter_start.sh
    - onchanges_any:
      - file: /opt/node_exporter_start.sh
      - file: /opt/node_exporter
```
But the output of salt command is like this, something like don't support multi file.managed
root@manage01:~# salt 'centos*' state.apply node-exporter-script
centos.iop.com:
    Data failed to compile:
----------
    Rendering SLS 'base:node-exporter-script' failed: while constructing a mapping
  in "<unicode string>", line 2, column 3:
      file.managed:
      ^
found conflicting ID 'file.managed'
  in "<unicode string>", line 6, column 3:
      file.managed:
      ^
ERROR: Minions returned with non-zero exit code

**Comment by markuskramerIgitt** [comment]
Hi @lifeisstillgood 
`conflicting ID` means that the first line of a state needs to be unique because it is an identifier.

You can either add a comment...
```
keep node_exporter in sync:
  file.managed:
    - name: /opt/node_exporter
    - source: salt://node-exporter-script/node_exporter
    - mode: 755
keep node_exporter_start.sh in sync:
  file.managed:
    - name: /opt/node_exporter_start.sh
    - source: salt://node-exporter-script/node_exporter_start.sh
    - mode: 755
```

...or cannibalize the file name as identifier:
```
/opt/node_exporter:
  file.managed:
    - source: salt://node-exporter-script/node_exporter
    - mode: 755
/opt/node_exporter_start.sh:
  file.managed:
    - source: salt://node-exporter-script/node_exporter_start.sh
    - mode: 755
```

I prefer to add comments.

**Comment by gtmanfred** [comment]
Correct, think about the yaml structure here, this is a dictionary, you can only have one dictionary entry for each key.

```
node-exporter-script:
  file.managed:
    - name: /opt/node_exporter
    - source: salt://node-exporter-script/node_exporter
    - mode: 755
  file.managed:
    - name: /opt/node_exporter_start.sh
    - source: salt://node-exporter-script/node_exporter_start.sh
    - mode: 755
```

Would convert to 

```
{
  "node-exporter-script": {
    "file.managed": [
      {
        "name": "/opt/node_exporter_start.sh"
      },
      {
        "source": "salt://node-exporter-script/node_exporter_start.sh"
      },
      {
        "mode": 755
      }
    ],
    "file.managed": [
      {
        "name": "/opt/node_exporter"
      },
      {
        "source": "salt://node-exporter-script/node_exporter"
      },
      {
        "mode": 755
      }
    ]
  }
}
```

But the second one would always overwrite the first one, so you need to have a different stateid to be able to have two file.managed states.

(and because the old format used to be this...

```
node-exporter-script:
  file:
    - managed
    - name: /opt/node_exporter
    - source: salt://node-exporter-script/node_exporter
    - mode: 755
  file:
    - managed:
    - name: /opt/node_exporter_start.sh
    - source: salt://node-exporter-script/node_exporter_start.sh
    - mode: 755
```

And we still support that, you can only have one `file` state module call per state id.

so you cannot use file.managed and file.append in the same state id.

You can however use `names`.

```
node-exporter-script:
  file.managed:
    - mode: 755
    - names:
      - /opt/node_exporter:
        - source: salt://node-exporter-script/node_exporter
      - /opt/node_exporter_start.sh
        - source: salt://node-exporter-script/node_exporter_start.sh
  cmd.run:
    - name: /opt/node_exporter_start.sh
    - onchanges_any:
      - file: /opt/node_exporter_start.sh
      - file: /opt/node_exporter
```

https://docs.saltstack.com/en/latest/ref/states/highstate.html#names-declaration
