### ISSUE TITLE
.exe installation from source file fails

### ISSUE THREAD

**Issue by Annnetta** [saltstack/salt#48646]
Hi all,

I would like to install a package to the Minion from a source on my Master.  
When I execute salt ‘*’ pkg.install 7zip_my_install  I have this error.

----------
              7zip_my_install:
                  Unable to locate package 7zip_my_install

my state sls is in /srv/salt/:
```

Zzip:
  '18.05.00.0':
    full_name: '7-Zip 18.05 (x64 edition)'
    installer: salt://7z1805-x64.msi
    install_flags: '/qn /norestart'
    uninstaller: salt://7z1805-x64.msi
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
```

top.sls is in /srv/salt/:

```
base:
 '*':
    - 7zip_my_install
```

.msi installer – 7z1805-x64.msi-  is in /srv/salt/

Salt Version:
           Salt: 2018.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4 

I think that there is a problem in the location of my files..

Do you see the problem?

Thank you in advance,
Hanna

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any ideas here?

**Comment by morganwillcock** [comment]
It looks like the package installation is using a state name instead of the package name. The terminology has been muddled, so not exactly sure what is configured, but `pkg.install 7zip` would install what is defined for the 7zip package (and when installing directly like this there is no requirement to use a state or top file, i.e. you are using `pkg.install` not `pkg.installed`).

**Comment by damon-atkins** [comment]
Pls read https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html
Also search for win_pkg issues, you will find other people requesting help.

This is not an sls in the same sense of the rest of salt.  Call it a package definition. And it needs to be in /srv/salt/win/repo-ng Your example below defines a package called `Zzip` (note your typo) with a single version of `18.05.00.0`.  It should not be listed top.sls as its not a state file.
```
Zzip:
  '18.05.00.0':
    full_name: '7-Zip 18.05 (x64 edition)'
    installer: salt://7z1805-x64.msi
    install_flags: '/qn /norestart'
    uninstaller: salt://7z1805-x64.msi
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
```

You also need a state (note the typo):
```
7zip_install:
   pkg.installed:
    - name: Zzip
```


Once you have everything in place you should get a result from
`salt -G os:Windows pkg.refresh_db`
