### ISSUE TITLE
salt.states.file.line match regex support broken

### ISSUE THREAD

**Issue by Artanicus** [saltstack/salt#48645]
### Description of Issue/Question
When using a regex with salt.states.file.line match, results seems to indicate at least the caret is ignored and the rest is treated as a text fragment. This results in the content value getting replaced on every line where the supposed text fragment occurs.
### Setup
These are some of the states is in use:
```
# this one breaks:
upstype: 
  file.line:
    - name: /etc/apcupsd/apcupsd.conf
    - content: UPSTYPE usb
    - match: ^UPSTYPE
    - mode: replace

# A similar edit with salt.states.file.comment, this one does not break:
nodevice:
  file.comment:
    - name: /etc/apcupsd/apcupsd.conf
    - regex: ^DEVICE
```

### Steps to Reproduce Issue
Actual output of state.highstate:
```
          ID: upstype
    Function: file.line
        Name: /etc/apcupsd/apcupsd.conf
      Result: True
     Comment: Changes were made
     Started: 12:38:24.789487
    Duration: 25.067 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -29,13 +29,13 @@
                   UPSCABLE usb

                   # To get apcupsd to work, in addition to defining the cable
                  -# above, you must also define a UPSTYPE, which corresponds to
                  +UPSTYPE usb
                   # the type of UPS you have (see the Description for more details).
                   # You must also specify a DEVICE, sometimes referred to as a port.
                   # For USB UPSes, please leave the DEVICE directive blank. For
                   # other UPS types, you must specify an appropriate port or address.
                   #
                  -# UPSTYPE   DEVICE           Description
                  +UPSTYPE usb
                   # apcsmart  /dev/tty**       Newer serial character device, appropriate for
                   #                            SmartUPS models using a serial cable (not USB).
                   #
                  @@ -79,13 +79,13 @@
                   # modbus    /dev/tty**       Serial device for use with newest SmartUPS models
                   #                            supporting the MODBUS protocol.
                   #
                  -UPSTYPE apcsmart
                  +UPSTYPE usb
                   DEVICE /dev/ttyS0

                   # POLLTIME <int>
                   #   Interval (in seconds) at which apcupsd polls the UPS for status. This
                  -#   setting applies both to directly-attached UPSes (UPSTYPE apcsmart, usb,
                  -#   dumb) and networked UPSes (UPSTYPE net, snmp). Lowering this setting
                  +UPSTYPE usb
                  +UPSTYPE usb
                   #   will improve apcupsd's responsiveness to certain events at the cost of
                   #   higher CPU utilization. The default of 60 is appropriate for most
                   #   situations.

```

Expected output:
```
... no changes snip ...

-UPSTYPE apcsmart
+UPSTYPE usb

... no changes snip ...
```

### Versions Report
```
%> salt-call --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: utf-8
        machine: x86_64
        release: 4.4.0-128-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by Ch3LL** [comment]
i'm able to replicate your issue. fortunately i tried on the head of 2018.3 as well and it is working there now. So this will be included in the next 2018.3.3 release :)

as shown below on the head of 2018.3:

```
local:                                                                                                                                                                             
----------                                                                                                                                                                         
          ID: upstype                                                                                                                                                              
    Function: file.line                                                                                                                                                            
        Name: /etc/test                                                                                                                                                            
      Result: True                                                                                                                                                                 
     Comment: Changes were made                                                                                                                                                    
     Started: 15:57:55.089024                                                                                                                                                      
    Duration: 43.01 ms                                                                                                                                                             
     Changes:                                                                                                                                                                      
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -12,7 +12,7 @@
                   # modbus    /dev/tty**       Serial device for use with newest SmartUPS models
                   #                            supporting the MODBUS protocol.
                   #
                  -UPSTYPE apcsmart
                  +UPSTYPE usb
                   DEVICE /dev/ttyS0
                   
                   # POLLTIME <int>
```

**Comment by grinapo** [comment]
sidenoting: salt 2018.3.2 (Oxygen)

**works:** 
    match: "^#*Timeout"
**doesn't work:**
    match: "^[#]*Timeout"

**Comment by OrangeDog** [comment]
Doesn't look like it was fixed, or at least not completely: #54260

**Comment by Ch3LL** [comment]
@grinapo any chance you can verify its working in 2018.3.3/4? If so we can close this issue.

**Comment by grinapo** [comment]
I am officially confused: **salt 2019.2.2 (Fluorine)**

In the following, **all** tests should be successful. Only 7 does (and the last for control), which suggest that match is only done for the **first** line of the file; as if the match would match *by file* and not *by line*.


```yaml
## try https://github.com/saltstack/salt/issues/48645#issuecomment-561216059
create testfile:
  file.managed:
    - name: /tmp/test01.txt
    - contents: 
       - Lorem Timeout Ipsum
       - "Torem #Timeout Upsim"
       - "###Timeout vobiscum"
       - Benedicam hypotense
       - "#Timeout borbellum"
       - Timeout veritas vobus

test line 1:
  file.line:
    - name: /tmp/test01.txt
    - match: "^[#]*Timeout.*"
    - content: XXX
    - mode: replace

test line 2:
  file.line:
    - name: /tmp/test01.txt
    - match: "^(#)*Timeout.*"
    - content: YYY
    - mode: replace

test line 3:
  file.line:
    - name: /tmp/test01.txt
    - match: ^(#)*Timeout.*
    - content: ZZZ
    - mode: replace

test line 4:
  file.line:
    - name: /tmp/test01.txt
    - match: "^#*Timeout.*"
    - content: QQQ
    - mode: replace

test line 5:
  file.line:
    - name: /tmp/test01.txt
    - match: ^#Timeout.*
    - content: PPP
    - mode: replace
test line 6:
  file.line:
    - name: /tmp/test01.txt
    - match: "^Bene"
    - content: RRR
    - mode: replace

test line 7:
  file.line:
    - name: /tmp/test01.txt
    - match: "^Lore"
    - content: WWW
    - mode: replace

test line final:
  file.line:
    - name: /tmp/test01.txt
    - match: Lorem
    - content: LOREM
    - mode: replace
```

```
salt --state-verbose=True  --state-output=full 'tester' state.apply test.test_match
...
----------
          ID: test line 6
    Function: file.line
        Name: /tmp/test01.txt
      Result: True
     Comment: No changes needed to be made
     Started: 20:59:03.526806
    Duration: 0.331 ms
     Changes:   
----------
          ID: test line 7
    Function: file.line
        Name: /tmp/test01.txt
      Result: True
     Comment: Changes were made
     Started: 20:59:03.527192
    Duration: 0.772 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,4 +1,4 @@
                  -Lorem Timeout Ipsum+WWW Torem #Timeout Upsim ###Timeout vobiscum Benedicam hypotense
----------
          ID: test line final
    Function: file.line
        Name: /tmp/test01.txt
      Result: True
     Comment: No changes needed to be made
     Started: 20:59:03.528035
    Duration: 0.361 ms
     Changes:   


Succeeded: 9 (changed=2)
Failed:    0
------------
Total states run:     9
```
