### ISSUE TITLE
sls call jinja variable error

### ISSUE THREAD

**Issue by like-inspur** [saltstack/salt#48668]
I define the number of server according to salt minion hostname in map.jinja:
```
{% set prometheus = salt['grains.filter_by']({
    'swarm-212': {
        'server': '1',
    },
    'swarm-213': {
        'server': '2',
    },
    'swarm-214': {
        'server': '3',
    },
}) %}
```
And init.sls call variable prometheus.server from this file:
```
{% from "prometheus/map.jinja" import prometheus with context %}
prometheus:
  cmd.wait:
    - name: docker service update monitor_prometheus{{ prometheus.server }} --force
    - watch:
      - file: /etc/prometheus/prometheus.yml
      - file: /etc/prometheus/rules
```
But when I execute state.apply prometheus, the error of output is like this:
```
swarm-214.inspur.com:
    Data failed to compile:
----------
    Rendering SLS 'base:prometheus' failed: Jinja variable 'None' has no attribute 'server'
swarm-213.inspur.com:
    Data failed to compile:
----------
    Rendering SLS 'base:prometheus' failed: Jinja variable 'None' has no attribute 'server'
swarm-212.inspur.com:
    Data failed to compile:
----------
    Rendering SLS 'base:prometheus' failed: Jinja variable 'None' has no attribute 'server'
```
