### ISSUE TITLE
Saltify ignoring master config when executing from newly created master

### ISSUE THREAD

**Issue by akbhat** [saltstack/salt#48696]
### Description of Issue/Question
Used Saltify to successfully salt a cluster including master and syndic via a bootstrapping master. Then attempted to run it off the local_master (manually installed salt-master before saltify) using the conf files listed below. The install proceeds without error except that the master config options mentioned for local master are ignored. It seems removing the make_master: True option from local master causes Saltify to ignore master config. Shouldn't it check to see if etc/salt/master exists even if Saltify itself did not install salt-master on that host? 
    
### Setup
```
vim /etc/salt/cloud.providers.d/saltify.conf
saltify-config:
  driver: saltify

vim /etc/salt/cloud.profiles.d/saltify.conf
make_salty:
  provider: saltify-config
  ssh_username: root
  password: xxxxxxx

vim /etc/salt/edi-map

make_salty:
  - master1:
      ssh_host: 100.123.35.0
      master:
        order_masters: True
      minion:
        master: 100.123.35.0
        local_master: True
  - master2:
      make_master: True
      ssh_host: 100.123.35.1
      master:
        syndic_master: 100.123.35.0
      minion:
        id: master2
        master: 100.123.35.0
        local_master: True
      grains:
        role: syndic 
  - minion1:
      ssh_host: 100.123.35.2
      minion:
        id: minion1
        master: 100.123.35.0
        local_master: True
      grains:
        role: minion
````
### Steps to Reproduce Issue
salt-cloud -m /etc/salt/edi-map -P

### Versions Report
root@ubuntu:~# salt --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial
