### ISSUE TITLE
git_pillar: Tags cannot start with a number

### ISSUE THREAD

**Issue by BenjaminSchiborr** [saltstack/salt#48717]
### Description of Issue
When using git_pillar, any tag you use cannot start with a number. An error show when executing a state that uses pillar information. This error does *not* show when directly accessing the pillar via e.g. pillar.get.

### Setup
Snippet for Master Config:
```
pillarenv_from_saltenv: True
ext_pillar_first: True
ext_pillar:
  - git:
    - __env__ codecommit:/v1/repos/my_pillars
gitfs_remotes:
  - codecommit:/v1/repos/my_states:
    - name: states
top_file_merging_strategy: same
pillar_merge_lists: True
pillar_source_merging_strategy: recurse
```

Example State on a git tag "1.0":
```
{% set foo= pillar['foo'] %}
{{ foo }}:
  test.succeed_without_changes
```

Example pillar on a git tag "1.0":
```
foo: bar
```

### Steps to Reproduce Issue
1. Call the aforementioned state ```salt 'myserver' state.apply mystate pillarenv=1.0 saltenv=1.0```
2. Observer the following error:
```
myserver:
    Data failed to compile:
----------
    Rendering SLS '1.0:mystate' failed: Jinja variable 'salt.pillar object' has no attribute 'foo'
```
3. Change the tag in git to e.g. "v1.0", call the state again and see that it works.

### Versions Report
```
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-79-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
