### ISSUE TITLE
Switch easily between gitfs_remotes for salt runs

### ISSUE THREAD

**Issue by eguven** [saltstack/salt#48766]
### Description of Issue/Question
I'm trying to figure out a configuration where I can easily switch between gitfs_remotes and pillar(s) between salt runs. I mainly want this for hands-on testing between forks. For example I have salt and pillar repos for the organisation and users as below:

```yaml
gitfs_provider: gitpython
fileserver_backend:
  - git
gitfs_remotes:
  - ssh://git@github.com/Org/my-salt.git
  - ssh://git@github.com/User/my-salt.git

git_pillar_provider: gitpython
ext_pillar:
  - git:
    - master ssh://git@github.com/Org/my-pillar.git
    - master ssh://git@github.com/User/my-pillar.git
```

I want to be able to do salt runs with a particular remote, eg. Org one or the User one. Is there any way I can configure this? I don't think saltenv helps since all remotes are more or less the same with a single env, base.

If possible I'd like to avoid managing repos on master and stick with gitfs. Any help is appreciated.

### Versions Report
Salt 2018.3.2
Dist: Ubuntu 18.04 bionic
