### ISSUE TITLE
Schedule ``once`` doesn't work when the job is added via ``schedule.add``

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#48767]
### Description of Issue/Question

I've noticed today that trying to dynamically add a job to the schedule doesn't work as expected (or what I understand it should work, at least):

I'm trying to add a new job:

```bash
root@salt-master:/# salt dummy schedule.add log_err function='log.error' job_args="['hello there']" once='2018-07-25T12:05:00' once_fmt='%Y-%m-%dT%H:%M:%S'
dummy:
    ----------
    comment:
        Added job: log_err to schedule.
    result:
        True
root@salt-master:/# salt dummy schedule.list
dummy:
    schedule:
      log_err:
        args:
        - hello there
        enabled: true
        function: log.error
        jid_include: true
        maxrunning: 1
        name: log_err
        once: '2018-07-25T12:05:00'
        once_fmt: '%Y-%m-%dT%H:%M:%S'
root@salt-master:/# salt dummy file.read /etc/salt/proxy.d/dummy/_schedule.conf
dummy:
    schedule:
      __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
        minutes: 60, name: __mine_interval, return_job: false}
      log_err:
        args: [hello there]
        enabled: true
        function: log.error
        jid_include: true
        maxrunning: 1
        name: log_err
        once: '2018-07-25T12:05:00'
        once_fmt: '%Y-%m-%dT%H:%M:%S'
root@salt-master:/# salt dummy schedule.list
dummy:
    schedule:
      log_err:
        args:
        - hello there
        enabled: true
        function: log.error
        jid_include: true
        maxrunning: 1
        name: log_err
        once: '2018-07-25T12:05:00'
        once_fmt: '%Y-%m-%dT%H:%M:%S'
root@salt-master:/#
```

However, although I would expect to see the `log` module logging my message, unfortunately it doesn't seem to execute the scheduled job.

Please note that this is not specific to Proxy Minions only, but also to regular Minion:

```
root@salt-master:/# salt srv schedule.add log_err function='log.error' job_args="['hello there']" once='2018-07-25T13:46:00' once_fmt='%Y-%m-%dT%H:%M:%S'
srv:
    ----------
    comment:
        Added job: log_err to schedule.
    result:
        True
root@salt-master:/# salt srv schedule.list
srv:
    schedule:
      log_err:
        args:
        - hello there
        enabled: true
        function: log.error
        jid_include: true
        maxrunning: 1
        name: log_err
        once: '2018-07-25T13:46:00'
        once_fmt: '%Y-%m-%dT%H:%M:%S'
root@salt-master:/# salt srv file.read /etc/salt/minion.d/_schedule.conf
srv:
    schedule:
      __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
        minutes: 60, name: __mine_interval, return_job: false}
      log_err:
        args: [hello there]
        enabled: true
        function: log.error
        jid_include: true
        maxrunning: 1
        name: log_err
        once: '2018-07-25T13:46:00'
        once_fmt: '%Y-%m-%dT%H:%M:%S'
```

Versions report:

```
root@salt-master:/# salt --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.3
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.41-moby
         system: Linux
        version: debian 9.3
```
