### ISSUE TITLE
RFE: Add on-demand snapshot to states.lvm.lv_present  

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack/salt#48808]
### Description of Issue/Question

The  [salt.states.lvm.lv_present](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.lvm.html#salt.states.lvm.lv_present) API does not support creation of snapshot-LV on-demand.  It seems an LV and corresponding snapshotLV can only be created at same time via confusing pillar data:
```
      lv1:
        vgname: vg00
        size: '20%VG'
        snapshot: lv1_snap
        options:
          addtag: 'Coolvolume'
          contiguous: y
          monitor: y
          mirrors: 0
```

`lvcreate(8)` stipulates a second invocation form for creating LV of type snapshot:
```
       lvcreate {-l|--extents LogicalExtentsNumber[%{VG|FREE|ORIGIN}] |
        -L|--size     LogicalVolumeSize[bBsSkKmMgGtTpPeE]}     [-c|--chunksize
       ChunkSize]  [--noudevsync]   [--ignoremonitoring]   [--monitor   {y|n}]
       -n|--name           SnapshotLogicalVolumeName          {{-s|--snapshot}
       OriginalLogicalVolumePath     |     [-s|--snapshot]     VolumeGroupName
       --virtualsize VirtualSize}
```
Please add this to `salt.states.lvm.lv_present` so pillars like this are supported:
```
      lv1:
        vgname: vg00
        size: '20%VG' 
      lv1_snap:
        vgname: vg00
        size: '10%VG'
        snapshot: True      #per lvcreate(8)b
        sourcelv: lv1    #per lvcreate(8)b
```

Otherwise `lv_present` does not support create LV snapshot use case.
