### ISSUE TITLE
win_service removing qoutes from bin_path

### ISSUE THREAD

**Issue by josemine** [saltstack/salt#48828]
### Description of Issue/Question
The win_service module is removing quotes from bin_path for both the create and modify function. If one goes to add a service in windows that has spaces using this module their system will be vulnerable. 
For more information you can take a look at
https://www.commonexploits.com/unquoted-service-paths/ and
http://cwe.mitre.org/data/definitions/428.html

I suggest line numbers 716 and 1027 should be deleted in salt/modules/win_service.py. Another options is to quote bin_path no matter what.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
### Master
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
### Minion
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed

           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.17134 SP0 Multiprocessor Free
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any opinions here on suggested fix?

**Comment by josemine** [comment]
At first I tried the following
```
winlogbeat:
  module.run:
    - name: service.modify
    - m_name: winlogbeat
    - display: winlogbeat
    - description: "Forwards Windows event logs on the local system to a remote elasticsearch server"
    - bin_path: "c:\\Program Files (x86)\\winlogbeat\\winlogbeat.exe"
    - exe_args:  -c "c:\\Program Files (x86)\\winlogbeat\\winlogbeat.yml" -path.home "c:\\Program Files (x86)\\winlogbeat\\" -path.data "C:\\ProgramData\\winlogbeat"
    - start_type: auto
```
I have also tried with single quotes and escaping them without luck because of service.modify striping quotes.

**Comment by josemine** [comment]
@twangboy exe_args is not the problem, since quotes are not get striped for it. The issue is that the service module is removing quotes from bin_path.
If I replace bin_path with ```'"c:\\Program Files (x86)\\winlogbeat\\winlogbeat.exe"'``` then I get the following result      
```
----------
          ID: winlogbeat
    Function: module.run
        Name: service.modify
      Result: True
     Comment: Module function service.modify executed
     Started: 14:24:36.761749
    Duration: 10.086 ms
     Changes:   
              ----------
              ret:
                  ----------
                  BinaryPath:
                      c:\\Program Files (x86)\\winlogbeat\\winlogbeat.exe -c "c:\\Program Files (x86)\\winlogbeat\\winlogbeat.yml" -path.home "c:\\Program Files (x86)\\winlogbeat\\" -path.data "C:\\ProgramData\\winlogbeat"
                  Description:
                      Fowards Windows event logs on the local system to a remote elasticsearch/graylog server
                  StartType:
                      Auto
  Name: winlogbeat - Function: service.running - Result: Clean Started: - 14:24:36.773789 Duration: 7.059 ms
```

**Comment by twangboy** [comment]
The above PR has the fix in it. Here are the state files that I was using. I had to modify them from the ones you had. I'm not sure if it was the `\\` or the trailing `\` at the end of the `-path.home`:
```
# cat run_service_create.sls
winlogbeat:
  module.run:
    - name: service.create
    - m_name: winlogbeat
    - display_name: Win Log Beat
    - description: Forwards Windows event logs on the local system to a remote elasticsearch server
    - bin_path: c:\Program Files\winlogbeat\winlogbeat.exe
    - exe_args:  -c "c:\Program Files\winlogbeat\winlogbeat.yml" -path.home "c:\Program Files\winlogbeat" -path.data "C:\ProgramData\winlogbeat"
    - start_type: auto
```
```
# cat run_service_modify.sls
winlogbeat:
  module.run:
    - name: service.modify
    - m_name: winlogbeat
    - display_name: WinLogBeat
    - description: Forwards Windows event logs on the local system to a remote elasticsearch server and stuff
    - bin_path: c:\Program Files\winlogbeat\winlogbeat.exe
    - exe_args:  -c "c:\Program Files\winlogbeat\winlogbeat.yml" -path.home "c:\Program Files\winlogbeat" -path.data "C:\ProgramData\winlogbeat"
    - start_type: manual
```
```
# cat run_service_delete.sls
winlogbeat:
  module.run:
    - name: service.delete
    - m_name: winlogbeat
```
