### ISSUE TITLE
salt-cloud is not working with 2018.3.2 and openstack

### ISSUE THREAD

**Issue by MedourMehdi** [saltstack/salt#48858]
### Description of Issue/Question
Get the following error message:

salt-cloud -m /etc/salt/cloud.conf.d/ppd_storage_test.conf
The following virtual machines are set to be created:
  storage1.companeo.local

Proceed? [N/y] y
... proceeding
**[ERROR   ] There was a query error: Entry in network list is missing required field "name"**.

Tried with Private Newton openstack and with OVH public cloud (Newton release).

Working with salt 2017.7.7

### Setup
cat /etc/openstack/clouds.yml
```
clouds:
  ovhppd:
    region_name: GRA1
    auth:
      username: 'XXX'
      password: XXX
      project_name: 'XXX'
      auth_url: 'https://auth.cloud.ovh.net/'

```
cat /etc/salt/cloud.providers.d/ppd_ovh_gra1.conf
```
ovh_ppd_gra1:
  cloud: ovhppd
  region_name: GRA1
  minion:
    master: 10.20.21.1
  identity_url: 'https://auth.cloud.ovh.net/v2.0/tokens'
  compute_name: nova
  protocol: ipv4
  compute_region: GRA1
  user: xxx
  password: xxx
  tenant: "xxx"
  driver: openstack
  securitygroup: default
  insecure: true
  ssh_interface: private_ips
  networks:
    - fixed:
      - d71a79ff-26b1-4dc7-baf8-7b7e17751f39
```

cat /etc/salt/cloud.profiles.d/storage_gra1.conf
```
glusterserver_ppd:
  provider: ovh_ppd_gra1
  image: "Ubuntu 18.04"
  size: eg-15-ssd
  script: bootstrap-salt
  ssh_key_name: "infra_key"
  ssh_key_file: /root/.ssh/infra_key.pem
  ssh_username: ubuntu
  security_groups: Suresnes_All
  minion:
    master: 10.20.21.1
    master_finger: xxx
    metadata_server_grains: True
    include: minion.d/*.conf
    mine_interval: 5
    grains:
      role:
        - storage
```
cat /etc/salt/cloud.conf.d/ppd_storage.conf
```
glusterserver_ppd:
  - storage1:
      grains:
        role:
          - storage
  - storage2:
      grains:
        role:
          - storage
  - storage3:
      grains:
        role:
          - storage
```
### Steps to Reproduce Issue
Install salt components 2018.3.2

dpkg -l | grep salt
ii  salt-api                        2017.7.7+ds-1                     all          Generic, modular network access system
ii  salt-cloud                      2018.3.2+ds-1                     all          public cloud VM management system
ii  salt-common                     2018.3.2+ds-1                     all          shared libraries that salt requires for all packages
ii  salt-master                     2018.3.2+ds-1                     all          remote manager to administer servers via salt
ii  salt-minion                     2018.3.2+ds-1                     all          client package for salt, the distributed remote execution system
ii  salt-ssh                        2018.3.2+ds-1                     all          remote manager to administer servers via salt
ii  salt-syndic                     2018.3.2+ds-1                     all          master-of-masters for salt, the distributed remote execution system

install pip install os-client-config and pip install shade

Try to start an instance on openstack with 
 salt-cloud -m /etc/salt/cloud.conf.d/ppd_storage.conf
(Include debug logs if possible and relevant.)

### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-29-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

Thanks.
