### ISSUE TITLE
Windows packages are included in pkg.list_pkgs that don't appear in Add/Remove programs

### ISSUE THREAD

**Issue by mts-avco** [saltstack/salt#48925]
### Description of Issue/Question
Some uninstall entries in the registry have SystemComponent (DWORD) set to 1 and these are hidden in Add/Remove programs but not by `pkg.list_pkgs`

### Setup
First noticed with VC2015 redist which adds 3 entries to the registry, of which 2 are marked as SystemComponent and are not displayed by Windows but are included by salt.

### Steps to Reproduce Issue
Install something that creates a system component, like VS2015 redist, and run `pkg.list_pkgs`

### Versions Report
```
    Salt: 2018.3.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```
