### ISSUE TITLE
Salt-Cloud: Creating a VM creates two keys

### ISSUE THREAD

**Issue by nstudach** [saltstack/salt#48986]
### Description of Issue/Question
Creating VM on Digital Ocean. The instance is created, but there are potentially two keys created in salt-keys: the minion id supplied to salt-cloud and the name of the master server (also Digital Ocean VM).

Similar to old issue [#28766] just with a newer salt version and digital ocean as provider. Opening new issue as recommended by @rallytime.

I am new to salt so it could also be a misconfiguration.
The whole configuration however is pretty basic.

### Setup
cloud profile (etc/salt/cloud.profile.d/do.config):
```
do-ams3-512:
  provider: do
  image: ubuntu-18-04-x64
  size: 512mb
  location: ams3
  private_networking: False
  backups_enabled: False
  ipv6: True
  create_dns_record: False
  grains:
    location: ams3
```
cloud provider (etc/salt/cloud.providers.d/do.config):
```
do:
  driver: digitalocean
  personal_access_token: 1234
  ssh_key_file: /etc/salt/keys/id_rsa
  ssh_key_names: Salt Master SSH Public Key on Digital Ocean
```
cloud (etc/salt/cloud):
```
minion:
  master: master ip adress
```
minion config (etc/salt/minion):
```
master: master ip adress
```
minion_id (etc/salt/minion_id):
```
salt-master-v2
```

### Steps to Reproduce Issue
I start with:
```
Accepted Keys:
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

Then create a minion with `$ salt-cloud -p do-ams3-512 test`:

```
Accepted Keys:
test
```
but as soon as you try: `$ salt '*' test.ping`, you will get an unaccepted key with the minion_id name:
```
Accepted Keys:
test
Unaccepted Keys:
salt-master-v2
```
I also think this is the reason the reactor is not triggering even though I get the even on the bus:
```
salt/cloud/test/created	{
    "_stamp": "2018-08-07T18:32:17.581379", 
    "driver": "digitalocean", 
    "event": "created instance", 
    "name": "test", 
    "profile": "do-ams3-512", 
    "provider": "do:digitalocean"
}
```
and /etc/salt/master.d/reactor.conf:
```
reactor:
  - 'salt/cloud/*/created':
    - '/srv/reactor/startup_orchestration.sls'
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-29-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
