### ISSUE TITLE
x509.certificate_managed state fails under py3 m2crypto with "int too large"

### ISSUE THREAD

**Issue by lachlanmunro** [saltstack/salt#49008]
### Description of Issue/Question
x509 certificate_managed fails on generated key length.

We have something like this working under py2, this change took place after an upgrade to py3 and compiling/adding m2crypto to it on windows.

### Setup
```
c:/test/test-ca.crt:
  x509.certificate_managed:
    - signing_private_key: c:/test/test-ca.key
    - CN: testy-mctest
    - basicConstraints: "critical CA:true"
    - keyUsage: "critical cRLSign, keyCertSign"
    - subjectKeyIdentifier: hash
    - authorityKeyIdentifier: keyid,issuer:always
    - days_valid: 1460
    - days_remaining: 0
    - backup: True
    - watch:
      - x509: c:/test/test-ca.key

c:/test/test-ca.key:
  x509.private_key_managed:
    - bits: 4096
    - backup: True
```

### Steps to Reproduce Issue
Running the above state results in:

```
local:
----------
          ID: c:/restic/test-ca.key
    Function: x509.private_key_managed
      Result: True
     Comment: File c:/restic/test-ca.key updated
     Started: 16:32:14.495656
    Duration: 1886.762 ms
     Changes:
              ----------
              new:
                  New private key generated
----------
          ID: c:/restic/test-ca.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1905, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\x509.py", line 496, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\modules\x509.py", line 1440, in create_certificate
                  cert.set_serial_number(serial_number)
                File "C:\salt\bin\lib\site-packages\M2Crypto\X509.py", line 593, in set_serial_number
                  return m2.asn1_integer_set(asn1_integer, serial)
              OverflowError: Python int too large to convert to C long
     Started: 16:32:16.383417
    Duration: 5.005 ms
     Changes:
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.17134 SP0 Multiprocessor Free
```
