### ISSUE TITLE
Issue with Compound Requisites

### ISSUE THREAD

**Issue by grichmond-salt** [saltstack/salt#49120]
### Description of Issue/Question
Compound requisites in states are supported, however, the following use case shows unexpected behavior.

Per @gtmanfred :
"It goes through the for loop, sees that the state has an `onfail` check, and then does a `continue` which then jumps back to the next item in the for loop, and never runs that if check for `onchanges`."

Reference:
https://github.com/saltstack/salt/blob/2018.3/salt/state.py#L2342

### Setup and Steps to Reproduce Issue
Run this state and observe the behavior when changes should occur.  The observer will note that the onchanges requisite is ignored, in favor of onfail not having been triggered.
```
update_file:
  file.managed:
    - name: /tmp/foo
    - contents:
      - 'Test'

test_state:
  test.configurable_test_state:
    - name: Compound requisite test
    - changes: True
    - result: False
    - comment: Something changed or failed on {{ grains.id }}
    - onfail:
      - file: update_file
    - onchanges:
      - file: update_file
```

### Versions Report
Issue observed on 2017.7.7
