### ISSUE TITLE
win_iis.create_app fails if IIS web app is already exists

### ISSUE THREAD

**Issue by sbrakl** [saltstack/salt#49153]
### Description of Issue/Question
I am using win_iis.create_app state to create nested webapps on IIS
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_iis.html#salt.states.win_iis.create_app

IIS Structure is all follows

>Default Web Site 
>>          / SubApp1
>>>             / SubSubApp1

If SubSubApp1 exists, it fails with following error

```
----------
          ID: create_subsite
    Function: win_iis.create_app
        Name: subapp1/subsubapp1
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1905, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_iis.py", line 627, in create_app
                  apppool)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_iis.py", line 1433, in create_app
                  raise CommandExecutionError(msg)
              salt.exceptions.CommandExecutionError: Unable to create application: subapp1/subsubapp1
              Error: New-WebApplication : Destination element already exists, please use "force" 
              parameter to override.
              At line:1 char:34
              + Import-Module WebAdministration; New-WebApplication -Name 
              'kiwiservices/stockser ...
              + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              ~~~
                  + CategoryInfo          : InvalidArgument: (:) [New-WebApplication], Argum 
                 entException
                  + FullyQualifiedErrorId : Destination element already exists, please use " 
                 force" parameter to override.,Microsoft.IIs.PowerShell.Provider.NewWebAppl  
                icationCommand
     Started: 09:49:54.431144
    Duration: 1560.01 ms
     Changes:   
```

It seems, it calling 'New-WebApplication' powershell, before checking if the subsubapp1 exists.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
create_subsite:
    win_iis.create_app:
        - name: subapp1/subsubapp1
        - site: Default Web Site
        - sourcepath: C:\subapp1\subsubapp1
        - apppool: SubAppPool
        - require:
            - file: create_sub_directory
```

### Steps to Reproduce Issue
When creating nested webapp (i.e. webapp inside other webapp). It would fail if the subsubapp exists.
Create subsubapp

### Versions Report
Salt master version report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1065-aws
         system: Linux
        version: Ubuntu 16.04 xenial

Salt Minion version report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free

**Comment by twangboy** [comment]
@sbrakl I haven't been able to replicate this issue. I've tried on Py2 and Py3 versions of salt on Windows Server 2016 and 2008r2 boxes. Here's the state file I've been using.

```
deploy_source:
  file.managed:
    - name: C:\inetpub\ACON_WS_FCI\index.html
    - content:
      - <html>
      - <h1>Hello World</h1>
      - </html>
    - makedirs: True

deploy_site:
  win_iis.deployed:
    - name: site1
    - sourcepath: C:\inetpub\site1

deploy_app_pool:
  win_iis.create_apppool:
    - name: SubAppPool

create_sub_directory:
  file.directory:
    - name: C:\inetpub\site1\subapp1
    - makedirs: True

deploy_subapp:
  win_iis.create_app:
    - name: site1/subapp1
    - site: site1
    - sourcepath: C:\inetpub\site1\subapp1
    - apppool: SubAppPool
    - require:
      - file: create_sub_directory

create_sub_sub_directory:
  file.directory:
    - name: C:\inetpub\site1\subapp1\subsubapp1
    - makedirs: True

deploy_subsubapp:
  win_iis.create_app:
    - name: site1/subapp1/subsubapp1
    - site: site1
    - sourcepath: C:\inetpub\site1\subapp1\subsubapp1
    - apppool: SubAppPool
    - require:
      - file: create_sub_directory
```

Am I doing something different? Could you post your entire state file? (sanitized)
