### ISSUE TITLE
managed - keep_source option, not clean cached file.

### ISSUE THREAD

**Issue by CutePotatoDev** [saltstack/salt#49154]
### Description of Issue/Question
Hello.
salt.states.file.managed have option - keep_source. It description say:
Set to False to **discard the cached copy of the source file** once the state completes. This can be useful for larger files to keep them from taking up space **in minion cache**.  ...

Problem is that after managed command state execution. Cached file is still in minion cache. 
### Setup
my .sls file (./states/copy.sls):
```
 DIST:
      file.managed:
        - name: /xxxx/dpldev/packages/rel_xxxx_xxxx.tar.gz
        - source: salt://packages//rel_xxxx_xxxx.tar.gz
        - user: 16379
        - group: 200
        - mode: 744
        - keep_source: False
```
### Steps to Reproduce Issue
sudo salt  '*myserver*' state.apply states.copy 

### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
