### ISSUE TITLE
hosts.rm_host changes /etc/hosts file with odd characters

### ISSUE THREAD

**Issue by sunyq** [saltstack/salt#49150]
Dear all:
  I am using Saltstack to modify /etc/hosts file.
  Sometimes I just found salt-minion modified my /etc/hosts with odd characters.
  Here is some minion log(I obscured some IP&username info):
![image](https://user-images.githubusercontent.com/2890053/44200669-bb486a00-a179-11e8-88ee-c8726b2b49c6.png)
And sometimes the same command can run correctly on the same machine:
![image](https://user-images.githubusercontent.com/2890053/44200877-4fb2cc80-a17a-11e8-9ba3-f1fb196317de.png)

So does anybody give me some tips about this?
Thanks a lot!

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 30 2018, 15:31:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.4 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-504.12.2.02.qiyi.el6.x86_64
         system: Linux
        version: CentOS 6.4 Final
```

**Comment by Ch3LL** [comment]
can you paste the command you are running?

**Comment by sunyq** [comment]
@Ch3LL  Hi, I used curl as the http client and call salt-api to modify /etc/hosts.
Here is my command:
```
curl  http://salt-api:8000 -H 'Accept: application/jsonl' -H 'X-Auth-Token: x-auth-token' -d client=local -d tgt='target_ip' -d fun=hosts.rm_host -d arg='ip=10.10.10.10' -d arg='alias=test_host_1'
```
Thank you.

**Comment by Ch3LL** [comment]
i'm having a hard time replicating this:

```
[root@d0f76961c2f7 /]# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      d0f76961c2f7
10.10.10.10    t_host_2 t_host_3 t_host_4
```

```
[root@d0f76961c2f7 /]# curl -sS localhost:8000/run -H 'Accept: application/x-yaml' -d client='local' -d tgt='*' -d username='saltdev' -d password='saltdev' -d eauth='pam' -d fun=hosts.rm_host -d arg='ip=10.10.10.10' -d arg='alias=t_host_2'
return:
- c6c2e89d6b0b: true
```

```
[root@d0f76961c2f7 /]# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      d0f76961c2f7
10.10.10.10              t_host_3 t_host_4
```

how often does this occur?

**Comment by sunyq** [comment]
```
[root@devsrv-sunyq:~]# curl -Ss http://salt-api-server:8000/run -H 'Accept: application/x-yaml' -d client='local' -d tgt='10.10.11.11' -d username='devuser' -d password='devpass' -d eauth='pam' -d fun=hosts.list_hosts
return:
- 10.10.11.11:
    10.10.10.10:
    - test_host_1
    - test_host_2
    127.0.0.1:
    - localhost
    - localhost.localdomain
    - localhost4
    - localhost4.localdomain4
    ::1:
    - localhost
    - localhost.localdomain
    - localhost6
    - localhost6.localdomain6
[root@devsrv-sunyq:~]# curl -Ss http://salt-api-server:8000/run -H 'Accept: application/x-yaml' -d client='local' -d tgt='10.10.11.11' -d username='devuser' -d password='devpass' -d eauth='pam' -d fun=hosts.rm_host -d arg='10.10.10.10' -d arg='test_host_1'
return:
- 10.10.11.11: true
[root@devsrv-sunyq:~]# curl -Ss http://salt-api-server:8000/run -H 'Accept: application/x-yaml' -d client='local' -d tgt='10.10.11.11' -d username='devuser' -d password='devpass' -d eauth='pam' -d fun=hosts.list_hosts
return:
- 10.10.11.11:
    "\0\0\0": []
    "1\0\0\00\0\0\0.\0\0\01\0\0\00\0\0\0.\0\0\01\0\0\00\0\0\0.\0\0\01\0\0\00\0\0\0":
    - "\0\0\0"
    - "\0\0\0"
    - "\0\0\0t\0\0\0e\0\0\0s\0\0\0t\0\0\0_\0\0\0h\0\0\0o\0\0\0s\0\0\0t\0\0\0_\0\0\02\0\0\0"
    127.0.0.1:
    - localhost
    - localhost.localdomain
    - localhost4
    - localhost4.localdomain4
    ::1:
    - localhost
    - localhost.localdomain
    - localhost6
    - localhost6.localdomain6
```
Very strange, nearly almost in my case .
I am not using Docker, and I am using virtual machines(CentOS 6) for this test.
