### ISSUE TITLE
The `onchanges` requisite requires the use of module names

### ISSUE THREAD

**Issue by englishm-llnw** [saltstack/salt#49161]
### Description of Issue/Question

The `onchanges` / `onchanges_in` requisite requires the use of module names to differentiate between similarly named states.

Slack discussion:
https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1534431715000100

### Setup

`testcase.sls`:

```sls
state-0:
  file.managed:
    - name: /script.sh
    - contents: cp /foo /bar
    - mode: 0755

state-1:
  cmd.run:
    - name: touch /foo
    - creates: /foo
    - onchanges_in:
        - state-2

state-2:
  cmd.run:
    - name: /script.sh
    - onchanges:
        - state-0
```

`testcase2.sls`:

```sls
state-0:
  file.managed:
    - name: /script.sh
    - contents: cp /foo /bar
    - mode: 0755

state-1:
  cmd.run:
    - name: touch /foo
    - creates: /foo
    - onchanges_in:
        - cmd: state-2

state-2:
  cmd.run:
    - name: /script.sh
    - onchanges:
        - file: state-0
```

https://gist.github.com/englishm-llnw/ffac82a1b66f7fc56a2a5cb9c1f0f587

### Steps to Reproduce Issue

If I run `testcase.sls` once, I see the results of `run1.txt` - all three states fire.

If I run it again, I see `run2.txt` - nothing fires because everything is up to date.

If I `rm /foo` and run it a third time, I see `run3.txt` - `state-1` fires to re-create `/foo`, but `state-2` doesn't fire to "update" `/bar`.

If I `rm /foo` again, and instead run `testcase2.sls`, `state-2` fires as expected.

### Versions Report

```
# salt-call --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-21-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I am unable to replicate this with your first state setup.

```
[root@salt ~]# cat /srv/salt/test.sls
state-0:
  file.managed:
    - name: /script.sh
    - contents: cp /foo /bar
    - mode: 0755

state-1:
  cmd.run:
    - name: touch /foo
    - creates: /foo
    - onchanges_in:
        - state-2

state-2:
  cmd.run:
    - name: /script.sh
    - onchanges:
        - state-0
```

https://gist.github.com/gtmanfred/278904a75f9c6f6df0298e5598dfbf87

It looks like this has been fixed in a newer salt versions.  Can you update and see if it fixes it for you as well?

Thanks,
Daniel
