### ISSUE TITLE
Limited EAuth users are basically useless

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#49177]
### Description of Issue/Question

I have used the external auth system for Salt-API access for a long time, but have never needed to restrict permissions until now. But the way the Eauth system works, limiting permissions seriously restricts the usefulness and convenience of Salt, both on the CLI and via Salt-API.

If a user defined in the Eauth configuration has access to only a subset of minions, even if they have full access to all modules on those minions, the user loses the ability to use Salt matchers freely from the CLI or the API. This results in a need to perform every operation in series, rather than orchestrating anything simultaneously across more than one minion, which defeats the purpose of using a tool like Salt.

### Setup
Eauth configuration 1, showing the an eauth user configured with permissions for multiple minions separately:
```yaml
external_auth:
  pam:
    saltapi2:
      - 'minion-web*':
        - .*
      - 'minion-db*':
        - .*
      - '@runner':
        - 'cache.*'
```
This works fine if you only ever request a `minion-web*` or `minion-db*` match individually, but you can't use compound matchers like `salt -C 'minion-web* or minion-db*' test.ping`, because then you get an authorization error or a "no such minion" response.

Master configuration 2 showing a "compound" match:
```yaml
external_auth:
  pam:
    saltapi2:
      - 'minion-web* or minion-db*':
        - .*
      - '@runner':
        - 'cache.*'
```

In this case, nothing works at all ever. Like... nothing. I can't ping anything directly, I can't use the entire compound match, nothing. If you try `salt minion-db\* test.ping`, you get `Authorization error occurred.`. If you try `salt '*' test.ping`, same thing. The documentation says that minion matching in external auth works like compound matchers, but apparently that isn't really true.

Similarly, doing a more complex Compound match like `G@os_family:RedHat or G@id:minion-web*` results in the same inability to use Salt.

### Versions Report

`2018.3.2` on everything
