### ISSUE TITLE
Support `opkg` on OpenWRT/LEDE

### ISSUE THREAD

**Issue by rysiekpl** [saltstack/salt#49181]
### Description of Issue/Question

[OpenWRT/LEDE](https://openwrt.org/) uses `opkg` as a package manager. However, trying to use the `opkg` module on an OpenWRT/LEDE minion fails with:

```
opkg' __virtual__ returned False: Module opkg only works on nilrt based systems
```

It would be great if `opkg` was supported also on OpenWRT/LEDE.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
zabbix-agentd:
    pkg.installed:
        - name: zabbix-agentd
        - provider: opkg
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
# salt-ssh '*' state.sls zabbix 
lede-tester:
----------
          ID: zabbix-agentd
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'zabbix'
              Reason: 'pkg' __virtual__ returned False
     Changes:   
```

```
# salt-ssh '*' opkg.install zabbix-agentd
lede-tester:
    ----------
    retcode:
        0
    stderr:
        'opkg' __virtual__ returned False: Module opkg only works on nilrt based systems
    stdout:
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
# salt --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.5 
        machine: x86_64
        release: 4.9.0-7-amd64
         system: Linux
        version: debian 9.5 
```
