### ISSUE TITLE
FreeBSD sysrc module broken in 2018.3 when setting a value to 'YES'

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt#49198]
### Description of Issue/Question

When a value of 'YES' is specified, salt will set it properly in /etc/rc.conf, but subsequent highstates show it repeatedly changing it to 'YES'.

### Setup
```
enable_suricata:
  sysrc.managed:
    - name: suricata_enable
    - value: YES
    - watch_in:
      - service: suricata
```

### Steps to Reproduce Issue
Go highstate a few times.
The first time it will create an entry in /etc/rc.conf
```
suricata_enable="YES"
```
On subsequent highstates it will continue say it changed it from:
```
suricata_enable="YES"
```
to
```
suricata_enable="YES"
```
...and in my example the service will be restarted every time.

Changing the state to:
```
enable_suricata:
  sysrc.managed:
    - name: suricata_enable
    - value: 1
    - watch_in:
      - service: suricata
```
...('YES' to 1) fixes it.

### Versions Report
2018.3.1 on both the master and minion.  Both are FreeBSD.
