### ISSUE TITLE
vmware: can't serialize VM when using an esxi proxy

### ISSUE THREAD

**Issue by ptitdoc** [saltstack/salt#49206]
### Description of Issue/Question
For some reason, pyvmomi creates unserializable vim.VirtualMachine objects which causes a crash when calling vsphere.get_vm.

This issue is documented in the following pyvmomi issue:
https://github.com/vmware/pyvmomi/issues/21

### Setup
For the context, I use call vsphere.get_vm with a vcenter proxy minion.

### Steps to Reproduce Issue
1/ Creates a vcenter proxy minion using pyvmomi 6.0.0 (because vcenter is running version 6.0.0)
2/ Call from the master vsphere.get_vm with an existing vm name on the vcenter proxy minion
3/ The master timeouts because the proxy minion thread crash with a TypeError related to vim.VirtualMachine:vm-name234

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.1
         Python: 2.7.15 (default, Jun 27 2018, 13:05:28)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1
            ZMQ: 4.2.5
 
System Versions:
           dist:   
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.14.57-1.pvops.qubes.x86_64
         system: Linux
        version: Not Installed
```
