### ISSUE TITLE
Mining doesn't work

### ISSUE THREAD

**Issue by gf-orgx** [saltstack/salt#49210]
### Description of Issue/Question
E. g., I can issue `salt "*" net.interfaces`, but despite `mine_interval` and `mine_functions` variables set in the proxy config, I can't use `salt-run` to query on this data.

### Setup
I have previously used these configs with packaged releases for Ubuntu and mining seemed to work, however I had to update to trunk due to #47695 and this functionality is now seemingly broken.

Master config (/etc/salt/master):
```
file_roots:
  base:
    - /opt/noc/etc/salt/pillar
    - /opt/noc/etc/salt/states
    - /opt/noc/etc/salt/reactors
    - /opt/noc/etc/salt/templates
pillar_roots:
  base:
    - /opt/noc/etc/salt/pillar
```

Proxy config (/etc/salt/proxy):
```
master: ...
mine_functions:
  net.ipaddrs: []
  net.lldp: []
  net.mac: []
  net.arp: []
  net.interfaces: []
mine_interval: 3
multiprocessing: False
```

### Steps to Reproduce Issue

Running `salt` on a particular minion, querying `net.interfaces`:

```
# salt dc-sw1.site net.interfaces --out=pprint | grep dc-site-sw
                           u'Vlan3201': {u'description': u'dc-site-sw',
```

At the same time:

```
# salt-run net.interfaces pattern=dc-site-sw    
Pattern "dc-site-sw" found in the description of the following interfaces
None
```
I'm not sure how to debug this (what to look at, etc.) and will be glad to hear your advises. One thing is proxy logs are clean (no errors, etc.). 

### Versions Report
```
Salt Version:
           Salt: 2018.11.0-32-g904faf7
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.13.16-2-pve
         system: Linux
        version: Ubuntu 16.04 xenial

```
