### ISSUE TITLE
mount.mounted false positives when template renders empty

### ISSUE THREAD

**Issue by minusf** [saltstack/salt#49230]
### Description of Issue/Question

`mount.mounted` would report success for empty `name`/`device`/`fstype`.

### Setup

`mount.sls`:

```
check-nfs-mount:
  mount.mounted:
    - name: {{ pillar.get('some:non:existent:pillar') }}  # resolving to None
    - fstype: ''
    - device: ''
    - mount: False
    - persist: False
    - failhard: True
```

```
13:59:12.120458 [ 26.423 ms]      mount.mounted    Clean     Name: check-nfs-mount
```

### Steps to Reproduce Issue

```
# salt-call state.apply mount
```

### Versions Report

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.2.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
