### ISSUE TITLE
sysctl tcp_timestamps modification fails docker container start

### ISSUE THREAD

**Issue by BruXy** [saltstack/salt#49233]
### Description of Issue

I have some generic docker_container.running state. I have disabled sysctl with net.ipv4.tcp_timestamps set to 0:

```yaml
{{ container }}_run:
  docker_container.running:
    - name: {{ container }}
    - image: {{ image }}
    - hostname: {{ container_hostname }}
    - sysctls:
      - net.ipv4.tcp_timestamps: 0
    - detach: True
    - network_mode: {{ name }}
    - restart_policy: always
    - port_bindings:
    - require:
      - docker_image: {{ image }}_pull
```
The container is not started and I am getting this docker related error:

```
 Comment: Failed to start container 'container_name': 'Error 500: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"open /
proc/sys/net/ipv4/tcp_timestamps: no such file or directory\"": unknown'
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1057-aws
         system: Linux
        version: Ubuntu 16.04 xenial
 
```
