### ISSUE TITLE
makedirs=True not working as expected

### ISSUE THREAD

**Issue by nkv16786** [saltstack/salt#49274]
### Description of Issue/Question
makedirs=True not working in file.managed

I am running the following command on windows minion,

`salt svr-123123 state.sls template pillar='{"name":"C:\\ProgramData\\pip\\pip.ini","source":"salt://conf.jinja","makedirs":True,"show_changes":"True","url":"http://10.xxx.xxx.xxx:8081/repository/AEPIP/pypi","win_owner":"salttest","win_perms":"full_control"}' -l debug`

but it is failing, getting the following error ,
```
svr-1534756760705:
----------
          ID: create_config_file
    Function: file.managed
        Name: C:\ProgramData\pip\pip.ini
      Result: False
     Comment: Parent directory not present
     Started: 04:51:29.738000
    Duration: 703.0 ms
     Changes:
```
Summary for svr-1534756760705
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 703.000 ms

### Setup
```
create_config_file:
  file.managed:
    - name: {{ pillar['name'] }}
    - source: {{ pillar['source'] }}
    - template:  jinja
    - makdirs: {{ pillar['makedirs'] }}
    - show_changes: {{ pillar['show_changes'] }}
    - mode: {{ pillar['mode'] }}
```

### Versions Report
salt 2017.7.7 (Nitrogen)
