### ISSUE TITLE
execution module cp.cache_file fails with error 'invalid arguments to setopt'

### ISSUE THREAD

**Issue by dgengtek** [saltstack/salt#49275]
### Description of Issue/Question
cp.cache_file fails on CentOS 7 python2 installation with Tornado 4.2.1 with the error "Passed invalid arguments to cp.cache_file: invalid arguments to setopt" when running the execution module from the shell. Anything which obviously is using cp.cache_file to download something is failing.

cp.cache_file works on CentOS 7 python34 installation with Tornado 4.4.2

### Setup
CentOS 7 with salt python2 from repo https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm 

### Steps to Reproduce Issue
```
$ salt "<CentOS 7 minion with python2>" cp.cache_file <any external url>
Passed invalid arguments to cp.cache_file: invalid arguments to setopt
...
<output of documention for cp.cache_file>
...
```

### Versions Report
CentOS 7 with python2 which fails
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 4.17.13-arch1-1-ARCH
         system: Linux
        version: CentOS Linux 7.5.1804 Core
 
```
Centos 7 with python34 which works
```
    Salt Version:
               Salt: 2018.3.2
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.4.8 (default, Jul 25 2018, 22:08:49)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.2
                ZMQ: 4.1.4
     
    System Versions:
               dist: centos 7.5.1804 Core
             locale: UTF-8
            machine: x86_64
            release: 3.18.25-19.el7.x86_64
             system: Linux
            version: CentOS Linux 7.5.1804 Core
```

**Comment by gtmanfred** [comment]
```
[root@salt ~]# salt --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

[root@salt ~]# salt \* test.ping
salt.c.gtmanfred-1263.internal:
    True
[root@salt ~]# salt \* cp.cache_file https://raw.githubusercontent.com/saltstack/salt/develop/README.rst
salt.c.gtmanfred-1263.internal:
    /var/cache/salt/minion/extrn_files/base/raw.githubusercontent.com/saltstack/salt/develop/README.rst
[root@salt ~]# head -n10 /var/cache/salt/minion/extrn_files/base/raw.githubusercontent.com/saltstack/salt/develop/README.rst
==================
What is SaltStack?
==================

SaltStack makes software for complex systems management at scale.
SaltStack is the company that created and maintains the Salt Open
project and develops and sells SaltStack Enterprise software, services
and support. Easy enough to get running in minutes, scalable enough to
manage tens of thousands of servers, and fast enough to communicate with
them in *seconds*.
```

I am unable to replicate this issue, can you provide me with more information?
