### ISSUE TITLE
git.latest not pulling

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#49307]
Hi,

I've got this code
```
my_app_deploy:
  git.latest:
    - name: git@gitlab.xxxx:sav/my_app.git
    - target: /opt/my_app
    - rev: {{ my_app.git.rev }}
    - branch: {{ my_app.git.branch }}
    - force_checkout: True
    - force_reset: True
    - force_clone: True
```

* my_app.git.rev is : HEAD
* When I switch the branch, it switch locally but it's no pulling the remote origin

What I understand of the documentation, update_head: True (default value) should have done this pull (sync remote Head with local one)

I am right ? Is it a bug ?

Best regards
