### ISSUE TITLE
salt-minion $PATH has changed in 2018.3.2 on macOS breaking Homebrew

### ISSUE THREAD

**Issue by petrhosek** [saltstack/salt#49348]
### Description of Issue/Question

We're using Salt on macOS, installed from the [official package](https://docs.saltstack.com/en/latest/topics/installation/osx.html#installation-from-the-official-saltstack-repository). We're also using Homebrew for managing packages on these machines. After upgrading to 2018.3.2, we noticed that Homebrew stopped working with the following error messages:

```
nodename:
    /bin/sh: brew: command not found
```

After some debugging, we've noticed that the content of `$PATH` has changed between 2017.7.2 and 2018.3.2 as visible by salt-minion.

On a machine running 2017.7.2, we get the following:

```
salt 'node1' cmd.run 'echo $PATH'
node1:
    /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
```

On a machine running 2018.3.2, we get the following:

```
salt 'node2' cmd.run 'echo $PATH'
node1:
    /usr/bin:/bin:/usr/sbin:/sbin
```

Notice the missing `/usr/local/bin` at the end. Since that's where `brew` is located, this is what's causing the Homebrew breakage we've observed. 

### Setup

All our machines are running macOS High Sierra 10.13.4 with the latest version of Homebrew installed.

### Steps to Reproduce Issue

Update a macOS machine running Salt and Homebrew from 2017.7.2 to 2018.3.2.

### Versions Report

```
    Salt Version:
               Salt: 2018.3.2
    Dependency Versions:
               cffi: 1.11.2
           cherrypy: 13.0.0
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.7
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (default, Jun 18 2018, 15:52:11)
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 17.0.0
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6
    System Versions:
               dist:
             locale: ascii
            machine: x86_64
            release: 17.5.0
             system: Darwin
            version: 10.13.4 x86_64
```
