### ISSUE TITLE
Infinite recursion when prerequiring state also prerequires other state which indirectly requires applied state

### ISSUE THREAD

**Issue by leromarinvit** [saltstack/salt#49358]
### Description of Issue/Question
When applying (or testing) a state which is prerequired by a state which also prerequires another state which indirectly requires the state being applied, salt-call exits with an exception indicating infinite recursion.

### Setup
salt_test.sls:
```
do_nothing:
    test.nop

prerequiring:
    test.nop:
        - prereq:
            - test: do_nothing
            - test: other_prerequired   # The error doesn't occur if this line is removed

other_prerequired:
    test.nop:
        - require:
            - test: required_by_prerequired

required_by_prerequired:
    test.nop:
        - require:
            - test: required_by_required

required_by_required:
    test.nop:
        - require:
            - test: do_nothing
```

The error doesn't occur if `other_prerequired` isn't prerequired in `prerequiring`. It also doesn't occur if the intermediate `required_by_prerequired` is removed and `other_prerequired` directly requires `do_nothing`.

### Steps to Reproduce Issue
`salt-call state.apply salt_test # optionally "test=True", doesn't matter`
or
`salt-call state.sls_id do_nothing salt_test # optionally "test=True", doesn't matter`

Stack trace from Linux minion (the same error also occurs on the Windows minion):
```
[...]
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2555, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2544, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2435, in call_chunk
    low = self._mod_aggregate(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 814, in _mod_aggregate
    agg_opt = self.functions['config.option']('state_aggregate')
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1143, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 97, in __getitem__
    if key not in self._dict and not self.loaded:
RuntimeError: maximum recursion depth exceeded in cmp
```

### Versions Report
master:
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.4
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.20.3
         Python: 2.7.13 (default, Mar 30 2018, 15:31:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 2.0.4
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.6 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final
```

Linux minion:
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.2.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

Windows minion:
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

**Comment by leromarinvit** [comment]
This simplified version shows the same behavior:
```
do_nothing:
    test.nop

prerequiring:
    test.nop:
        - prereq:
            - test: do_nothing
            - test: other_prerequired

other_prerequired:
    test.nop:
        - require:
            - test: required_by_prerequired

required_by_prerequired:
    test.nop:
        - require:
            - test: do_nothing
```

**Comment by gtmanfred** [comment]
This appears to be a duplicate of https://github.com/saltstack/salt/issues/20143

**Comment by leromarinvit** [comment]
That's certainly possible (I don't know anything about salt's internals), but there are no failing states involved in my case.

**Comment by gtmanfred** [comment]
Sure, there are also these other times this same issue has been reported, could you take a look at them? because some of them look like they are fixed.

https://github.com/saltstack/salt/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+recursion+prereq

**Comment by leromarinvit** [comment]
I've looked at these now (I found some even before opening this issue), but I don't think any of them is the same problem (of course the root cause might still be the same or related). Most seem to involve failing states (e.g. #46762,  #38879) or explicitly defined recursion (e.g. #44323), and those that don't should be fixed in 2018.3.2 (#14190, #14190, #11717).

**Comment by leromarinvit** [comment]
While searching for workarounds for this issue, I discovered that the following also crashes with the same stack trace. This looks like it could be related to #15171, but again, that should already be fixed. Should I open another issue or is this related?

salt_test/onfail.sls:
```
something:
    test.nop

something_else:
    test.nop:
        - onfail:
            - test: something

before_something_else:
    test.nop:
        - prereq:
            - test: something_else
```
Run with `salt-call state.sls_id something_else salt_test.onfail` or `salt-call state.sls salt_test.onfail`.
