### ISSUE TITLE
wait_for_event fails to match custom ids formatted like jids

### ISSUE THREAD

**Issue by shware100** [saltstack/salt#49381]
### Description of Issue/Question
When using jid-like identifiers as the for the "id_list" of a wait_for_event the events never match.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
simple_wait_for_event.sls:
```
wait_for_some_event:
    salt.wait_for_event:
        - name: test/resume_simple_event
        - timeout: 120
        - id_list:
            - 20180828195351562601

simple_wait_for_event_resume.sls
send_event_to_resume_simple_wait_for_event:
  salt.runner:
    - name: event.send
    - tag: test/resume_simple_event
    - data:
        id:   20180828195351562601
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Run the simple_wait_for_event:
salt-run state.orch simple_wait_for_event

In another window run the event resume:
salt-run state.orch simple_wait_for_event_resume

The output on the wait_for_event side looks like:
[DEBUG   ] LazyLoaded salt.wait_for_event
[INFO    ] Running state [test/resume_simple_event] at time 16:33:38.502986
[INFO    ] Executing state salt.wait_for_event for [test/resume_simple_event]
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] wait_for_event: Skipping unmatched event 'salt/run/20180828163341615882/new'
[DEBUG   ] wait_for_event: Skipping unmatched event 'salt/run/20180828163341615882/args'
[DEBUG   ] wait_for_event: Skipping unmatched event 'salt/run/20180828163342924181/new'
[DEBUG   ] wait_for_event: Skipping unmatched event 'salt/run/20180828163342924181/ret'
[DEBUG   ] wait_for_event: Skipping unmatched event 'salt/run/20180828163341615882/ret'
[ERROR   ] Timeout value reached.
[INFO    ] Completed state [test/resume_simple_event] at time 16:35:43.091807 (duration_in_ms=124588.821)

NOTE: the actual event fired in the resume orchestration doesn't appear in the skipped list; however, the wait_for_event eventually times out.  This is probably another bug :)

WORKAROUND: added _resume string to end of the id in wait_for_event and id_list in resume event orch so new id looks like: 20180828195351562601_resume.  When the extra string is added the wait_for_event / resume combo works.

### Versions Report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial

Thanks, hope this helps.

Shawn

**Comment by gtmanfred** [comment]
This is probably yaml idiosyncrasies, you have a number, so it is converted to an integer, try quoting it.

```
wait_for_some_event:
    salt.wait_for_event:
        - name: test/resume_simple_event
        - timeout: 120
        - id_list:
            - '20180828195351562601'

simple_wait_for_event_resume.sls
send_event_to_resume_simple_wait_for_event:
  salt.runner:
    - name: event.send
    - tag: test/resume_simple_event
    - data:
        id:   '20180828195351562601'
```
