### ISSUE TITLE
Defer execution of (some) templated salt commands until the state containing the template is needed

### ISSUE THREAD

**Issue by OddBloke** [saltstack/salt#4945]
Consider the following state file:

```
git:
  - pkg.installed

my_git_repo:
  git.latest:
    - name: /path/to/my/git/repos/{{ salt['git.something']('blah') }}
    - require:
      - pkg: git
```

Assuming that `git.something` requires git to be installed, this state file can never be applied (because it won't compile, because git isn't installed).

Having some way of deferring the execution of `git.something` until the `my_git_repo` is actually being applied (i.e. after git is installed) would solve this problem.
