### ISSUE TITLE
[Feature Request] Saltclass node groups

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#49493]
### Description of Issue/Question
If I understand it correctly, right now if I have 2 groups of servers, let's say it's a WEB and DB servers with 1000 nodes in each and I want to use a Saltclass to manage them and looks like I have to create a 2000 yaml file for all nodes and this files will be absolutely the same for a group.

This sounds like a duplication to me, it doesn't scale and requires some kind of separate generation automation.

### Proposal
My proposal is to add some kind of a **top** definition to Saltclass. Like top.sls for Pillar, which will describe a nodes groups. So it will be something like:

```
group_name:
  nodes:
    - nodesA*
    - nodesB*
    - '^regexp.*$' 
   classes:
     - classA
     - classB
``` 
And we could keep the specific per node definition and make them to be the last override target, so:

**host1** is in a **groupA** which inherits **ClassA**
additionally, we have a **host1.yml** with defined **ClassB**

the result will be **ClassA and ClassB** applied to **host1**.

Does that make sense?
