### ISSUE TITLE
Salt started in custom directory can't execute maintains commands

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#49491]
Hi,

I'm trying to run a Salt in non-standard directories (/opt/salt) due to env restrictions and I have a configured master key rotation after which it should send a `ping` to all minions and this maintenance job failing with the exception since my `run` directory with sockets and my configs are in non-standard path.

### Setup
```
root_dir: /
default_include: /opt/salt/master.d/*.conf
interface: 0.0.0.0
publish_port: 4505
ret_port: 4506
pidfile: /opt/salt/run/salt-master.pid
conf_file: /opt/salt/master
pki_dir: /opt/salt/pki/master
cachedir: /opt/salt/cache/master
cli_summary: True
sock_dir: /opt/salt/run
enable_gpu_grains: False
ping_on_rotate: True
state_top: top.sls
master_tops:
  saltclass:
    path: /opt/salt/saltclass
renderer: yaml_jinja
failhard: True
state_output: changes
state_output_diff: False
```

### Steps to Reproduce Issue
Deploy salt in the non-standard directory and configure the `ping_on_rotate` option.

### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.5

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

### Possible solution
Error happens in `salt/utils/master.py` at line `679` in fuction `ping_all_connected_minions`.
There is a line:
```
    client = salt.client.LocalClient()
```
So it doesn't pass the `c_path` arg and it should, imo.

The possible fix will be:
```
    if opts['conf_file']:
        client = salt.client.LocalClient(c_path=opts['conf_file'])
    else:
        client = salt.client.LocalClient()
```
