### ISSUE TITLE
Salt minion needs to be restarted after starting firewalld

### ISSUE THREAD

**Issue by golmaal** [saltstack/salt#49519]
### Description of Issue/Question
If firewalld on a centos 7 minion is down, if a state is run in this case to start the firewall and add services to public zone, master is now unable to talk to minion until minion is restarted.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Salt master - 2017.7.7 on Cent OS 7 (Machine 1)
Salt minion - 2017.7.7 on Cent OS 7 (Machine 2)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

State file (firewall-test.sls)
```
firewalld-service:
   service.running:
     - name: firewalld
     - enable: True

firewall-rule:
  firewalld.present:
    - name: public
    - prune_services: False
    - services:
      - http
      - https
    - require:
      - service: firewalld-service
```

Run the following from master (make sure firewalld is down on minion on machine 2) - 

salt <minion-id> state.sls firewall-test

In 3+ times out of 5, salt-minion will get into a state where it'd not respond to commands (such as salt <minion-id> test.version) unless it's restarted first.

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.6
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.5

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
