### ISSUE TITLE
[salt-cloud] Proxmox provider incorrectly supports rootfs

### ISSUE THREAD

**Issue by MTecknology** [saltstack/salt#49530]
### Description of Issue/Question

The proxmox salt-cloud provider supports reading the option for rootfs, but the rootfs option needs to include the vmid, which is not available until during creation. I suspect there are other considerations that need to be made to support the [api structure](https://pve.proxmox.com/pve-docs/api-viewer/index.html) somewhere close to [this section](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/proxmox.py#L813) in the proxmox cloud code.

### Steps to Reproduce Issue

Use the following profile:
```
proxint_dev-test-02.core.lustfield.net:
  cpus: 2
  memory: 512
  net0: name=eth0,bridge=vmbr0,ip=10.0.0.27/24,gw=10.0.0.1,ip6=20:40:fe:4::27/64,gw6=20:40:fe:4::1
  onboot: 1
  provider: proxint
  rootfs: volume=fastdisk,size=8
  swap: 0
  technology: lxc
```

### Versions Report

```
Salt Version:
           Salt: 2018.3.2

System Versions:
           dist: debian 9.5 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.18-4-pve
         system: Linux
        version: debian 9.5 
```
