### ISSUE TITLE
file.managed deploys file without EOL

### ISSUE THREAD

**Issue by saltstack-admin** [saltstack/salt#49556]
### Description of Issue/Question
A sudoers file shall be deployed into /etc/sudoers.d. The file itself works if we copy it manually with scp/rsync to the salt-minion, but if we deploy it with file.managed, visudo -c -f tells us that this file has an syntax error.
Opening the file with vim showed in the bottom status bar, that the file has [noeol], so a transfer through file.managed deletes the last empty line and makes the file unusable for sudo.
Fix needed or wrong configuration of salt state?

### Setup
salt state:
```
/etc/sudoers.d/custom_user:
    file.managed:
       - name: /etc/sudoers.d/custom_user
       - source: salt://configs/sudoers.d/custom_user
       - user: root
       - group: root
       - mode: 440
       - replace: true
       - backup: minion
       - show_changes: true
       - create: true
       - encoding: ascii
```

Output after applying the state:
```
          ID: /etc/sudoers.d/custom_user
    Function: file.managed
        Name: /etc/sudoers.d/custom_user
      Result: false
     Comment: check_cmd execution failed
parse error in /tmp/__salt.tmp.WV3dvp near line 4
>>> /tmp/__salt.tmp.WV3dvp: syntax error near line 4 <<<
     Started: 16:12:53.012223
    Duration: 47.835
         SLS: manager_org_1.deploy_suoders_custom_user
     Changed: {}
```
Content of custom_user with Linux line endings:
```
custom_user ALL=NOPASSWD:/opt/check_iptables.sh

```
### Steps to Reproduce Issue
- create text file with sudoers content
- deploy file with file.managed to salt minion
- let visudo -c -f check syntax of file

### Versions Report
Salt Master:
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.143-94.47-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

Our Salt-Minion have the same version.
