### ISSUE TITLE
lgpo doesn't seem to allow for unsetting a gpo setting

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#49582]
### Description of Issue/Question
The gpo setting `SeTrustedCredManAccessPrivilege` accepts a list valid users. I can successfully add a list of users to the setting, but I can't find a way to remove all users from the list.

### Setup
The following does work:
```
set_trusted_caller:                                                              
  lgpo.set:                                                                     
    - computer_policy:                                                          
        SeTrustedCredManAccessPrivilege:                                        
          - 'vagrant'                                                           
          - 'administrator'
```

I want to remove all users from this list. I've tried the following, but nothing seems to work.

```
no_trusted_caller:                                                              
  lgpo.set:                                                                     
    - computer_policy:                                                          
        SeTrustedCredManAccessPrivilege: []
```
I'm not sure if this needs some documentation on how to do this or if this is a feature request.

Here's my versions report:

```
vagrant-2016.lehi.saltstack.net:
    Salt Version:
               Salt: 2018.3.2
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393  Multiprocessor Free
```

**Comment by twangboy** [comment]
Sometimes you can pass `Not Configured` or None. Depending on the policy you're setting.

**Comment by UtahDave** [comment]
@twangboy I tried `None` without success. I'll try `Not Configured`. I've tried several variations of these both and I kept getting an error because it failed to convert the name to the SID.

**Comment by lomeroe** [comment]
If I remember right, cumulative_rights_assignments is set to true by default, so it defaults to adding to what is there (so the state is adding no one to the list when an empty list is passed).  To remove all users (i.e. set it to an explicit list), pass cumulative_rights_assignments=False to set it to exactly what you are passing.

**Comment by lomeroe** [comment]
to expand on my previous comment, this *should* work to remove all users:

```
no_trusted_caller:                                                              
  lgpo.set:
    - cumulative_rights_assignments: False                                                  
    - computer_policy:                                                          
        SeTrustedCredManAccessPrivilege: []
```

The cumulative_rights_assignments argument is intended to determine if lgpo will make sure the listed users have the right (True) or that the right matches the list exactly (False).
