### ISSUE TITLE
[2017.7.7] salt-master with gitfs fails to start on centos7.5 with latest pygit2

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#49591]
### Description of Issue/Question
salt-master with gitfs fails to start on centos7.5 with latest pygit2

### Setup
CentOS 7.5
Salt-Master 2017.7.7
python-pygit2.x86_64 0:0.26.4-1.el7

### Steps to Reproduce Issue

```
$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
$ rpm -qa | grep git2
libgit2-0.26.6-1.el7.x86_64
python-pygit2-0.26.4-1.el7.x86_64
$ cat /var/log/salt/master
2018-09-10 11:41:39,111 [salt.utils.gitfs :359 ][CRITICAL][27230] Exception caught while initializing gitfs remote 'git@mygitlab.example.com:user/repo.git': global name 'git' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 353, in __init__
    self.new = self.init_remote()
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 1474, in init_remote
    self.configure_refspecs()
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 529, in configure_refspecs
    except (git.exc.GitCommandError, GitRemoteError) as exc:
NameError: global name 'git' is not defined
2018-09-10 11:41:39,112 [salt.master      :496 ][CRITICAL][27230] Failed to load gitfs
2018-09-10 11:41:39,112 [salt.master      :497 ][CRITICAL][27230] Master failed pre flight checks, exiting
```

### Versions Report
```yaml
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by garethgreenaway** [comment]
@rossengeorgiev Thanks for the report.  Unfortunately I have been unable to reproduce this particular issue.

**Comment by Poil** [comment]
No problem here but I'm on 2018.3.2

```
# salt --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.4.9 (default, Aug 14 2018, 21:28:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by rossengeorgiev** [comment]
Hi @garethgreenaway,

I've looked into this further and it seems to happen when `/var/cache/salt/master/` is empty. Clearing that directory is a prerequisite for the issue. After that salt-master fails to start on the first 2 tries, but on the 3rd is fine. My master config looks like so:

```yaml
auto_accept: True
open_mode: True

fileserver_backend:
  - roots
  - git

gitfs_provider: pygit2
gitfs_privkey: /etc/salt/git_deploy_key
gitfs_pubkey: /etc/salt/git_deploy_key.pub

gitfs_remotes:
  - git@gitlab.example.com:mygroup/myrepo.git:
    - name: my-modules
    - base: develop
    - root: modules
  - git@gitlab.example.com:mygroup/myrepo.git:
    - name: my-states
    - base: develop
    - root: states
    - mountpoint: salt://mymount
```
