### ISSUE TITLE
[bug] salt.util.http implementations should all provide the same behavior

### ISSUE THREAD

**Issue by jdelic** [saltstack/salt#49602]
Salt states and modules that need to make HTTP queries go through the `salt.modules.http` execution module, which itself delegates to `salt.util.http`. `salt.util.http.query` consists of three different implementations depending on what libraries are available, selected by the `backend` keyword parameter. The available backends are:

* `tornado` using tornado's HTTPClient (the default)
* `requests` using the requests Python library
* `urllib2` using the Python built-in urllib2 library

Unfortunately `tornado` subtly behaves differently from the other two. Among other things it's the only backend that supports the `raise_error` parameter and is therefor the only backend that allows a query to actually return any status code that is not `2xx`, since every other backend will throw an exception on any status code that might indicate an error.

An example usage might look like this:
```yaml
    http.wait_for_successful_query:
        - name: https://vault.service.consul:8200/v1/sys/health
        - match: "initialized": false
        - wait_for: 10
        - request_interval: 1
        - raise_error: False  # only exists in 'tornado' backend
        - backend: tornado
        - watch:
            - service: vault-service
        - require_in:
            - cmd: vault-sync
```

[Hashicorp Vault will return status code 501](https://www.vaultproject.io/api/system/health.html#read-health-information) when Vault is running but is not initialized. The above state will wait for Vault to be up, before Salt can then move on to initialize it. With any other backend it will fail, since they will raise exceptions on status code 501 regardless of the `match`.
