### ISSUE TITLE
macOS: Custom grains in file_roots/_grains do not get executed

### ISSUE THREAD

**Issue by sheagcraig** [saltstack/salt#49631]
### Description of Issue/Question
Following the documentation regarding custom grains modules:
> Custom grains modules should be placed in a subdirectory named _grains located under the file_roots specified by the master config file.
results in the minion not seeing the modules contained within.

Specifying the path to the same directory with the minion config option grains_dirs allows salt to see the custom grains.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
For what it's worth, this is the current python3 salt installer for macOS.

minion config
```
master_type: disable
file_client: local

file_roots:
  base:
    - /opt/something

# grains_dirs:
#   - /opt/something/_grains

multiprocessing: False
```

Then run with the grains_dirs commented and uncommented:
`sudo salt-call config.get grains_dir`
The _grains folder shows up when grains_dir is specified.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
As per above section should be adequate.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
sh-3.2# salt --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.7
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jun 18 2018, 16:05:29)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 18.0.0
         system: Darwin
        version: 10.14 x86_64
```
