### ISSUE TITLE
pkg.installed not working correctly on ppc64le architecture

### ISSUE THREAD

**Issue by sjtbham** [saltstack/salt#49672]
### Description of Issue/Question
When running on `ppc64le` systems, with architecture based packages, salt is trying to repeatedly install the package when it is already installed. For example we want to ensure the `iptables` package is installed on the system via salt. This works as expected on `x86_64` arch systems, but doesn't work properly on `ppc64le` systems.

### Setup
Example state for package installation
```
iptables-pkg:
  pkg:
    - installed
    - name: {{ pillar.packages.names.iptables | default('iptables') }}
```

### Steps to Reproduce Issue
```# salt-call state.highstate
[ERROR   ] The following packages failed to install/update: iptables
```

On ppc64le salt client (trimmed to relevant output):
```
# salt-call state.highstate test=true
----------
          ID: iptables-pkg
    Function: pkg.installed
        Name: iptables
      Result: None
     Comment: The following packages would be installed/updated: iptables
     Started: 15:40:47.161451
    Duration: 91.094 ms
     Changes:
```

Listing the versions of the packages installed:
```
# salt-call pkg.list_pkgs
local:
    ----------
    iptables.ppc64le:
        1.4.21-24.1.el7_5
```

Whilst salt is running in non test mode, you can see it running processes like `yum -y install iptables` (in output from `ps -ef`) which salt things has failed (though the package is actually installed) I assume due to some architecture mismatching?

Checking what yum thinks is installed:
```
# yum list iptables
Loaded plugins: product-id, search-disabled-repos, subscription-manager, versionlock
Installed Packages
iptables.ppc64le                                                 1.4.21-24.1.el7_5                                                  @pkg1/7.5
```

### Versions Report
```
# salt-call --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.8
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May 31 2018, 09:45:54)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: ppc64le
        release: 4.14.0-49.10.1.el7a.ppc64le
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```

```
# uname -p
ppc64le
```

Note the master is also running 2018.3 but is running on x86_64 architecture.
