### ISSUE TITLE
Beacon Interval not being applied correctly when using the beacon state module

### ISSUE THREAD

**Issue by travispaul** [saltstack/salt#49683]
### Description of Issue/Question
When adding a beacon interval using the beacon state module, the interval is not added to the minion correctly.

### Setup

```
[root@salt salt]# cat /srv/salt/beacons/init.sls
diskusage:
  beacon.present:
    - save: True
    - interval: 10
    - /: 25%


[root@salt salt]# cat /srv/salt/top.sls
base:
  'minion*':
    - beacons
```

### Steps to Reproduce Issue

```
[root@salt salt]# salt minion\* state.highstate
minion1.localdomain:
----------
          ID: diskusage
    Function: beacon.present
      Result: True
     Comment: Job diskusage in correct state
              Beacon diskusage saved
     Started: 16:34:15.183814
    Duration: 629.876 ms
     Changes:

Summary for minion1.localdomain
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 629.876 ms


[root@salt salt]# salt minion\* beacons.list
minion1.localdomain:
    beacons:
      diskusage:
      - /: 25%
        interval: 10
```

beacons.conf on the minion:

```
[root@minion1 ~]# cat /etc/salt/minion.d/beacons.conf
beacons:
  diskusage:
  - /: 25%
    interval: 10
```

### Versions Report
```
[root@salt salt]# salt --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
