### ISSUE TITLE
Missing Minions - strange behaviour after enabling auto_accept and refresh_modules

### ISSUE THREAD

**Issue by morsik** [saltstack/salt#49681]
### Description of Issue/Question
Doing `saltutil.refresh_modules` after setting `auto_accept: true` have some strange behaviour.

### Setup
Setup some minions.

### Steps to Reproduce Issue
1. 
```
[root@salt ~]# salt-key -L
Accepted Keys:
salt
srv1
srv2
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```
2. Edit `/etc/salt/master` and set `auto_accept: true`.
3. Refresh modules using `salt-call saltutil.refresh_modules`.
4. Remove keys using `salt-key -D`.
5. Confirm:
```
[root@salt ~]# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```
6. Try to ping Minions... they should be inaccessible (as they were removed from known keys) or should be auto accepted:
```
[root@salt ~]# salt '*' test.ping
srv1:
    True
salt:
    True
srv2:
    True
```
6. Thanks Salt, it looks like you auto accepted minions? Oh wait... not really...
```
[root@salt ~]# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

### Versions Report
All 3 nodes installed at the same time using `salt-cloud`, and this map (masterofmasters was unavailable when doing this test and/or creating hosts, but was in configuration):
```
do-el7-1:
- salt:
    make_master: yes
    master:
      syndic_master: masterofmasters
      pillarenv: base
      order_masters: True
    minion:
      ping_interval: 1
{%- for srv_id in range(1, 3) %}
- srv{{ srv_id }}:
    minion:
      master: salt
      ping_interval: 1
{%- endfor %}
```

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-862.2.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
