### ISSUE TITLE
Jinja error: Unable to parse now. Consider installing timelib

### ISSUE THREAD

**Issue by grandmasterv** [saltstack/salt#49686]
### Description of Issue/Question
I'm having an issue with [timelib](https://pypi.org/project/timelib/) in states using Jinja.  The statement `{{ 'now' | strftime('%Y-%m-%d_%H-%M') }}` works fine on my minion when I apply the state using a local `salt-call` but when I try to apply the state from my master I get `Jinja error: Unable to parse now. Consider installing timelib`.  timelib is installed on both the minion and master.  

This works on the master as well:
```
Python 2.7.5 (default, Jul 13 2018, 13:06:57)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import time, timelib
>>> time.ctime(timelib.strtotime("now"))
'Mon Sep 17 14:30:20 2018'
```

### Setup
Here is the state I'm running:
```
dev wordpress backup {{ site }}:
  module.run:
    - name: archive.tar
    - options: czf
    - tarfile: "{{ site_info.backup }}/{{ site }}_backup_{{ 'now' | strftime('%Y-%m-%d_%H-%M') }}.tar.gz"
    - sources: '{{ site_info.document_root }}'
```

### Versions Report
**MASTER**
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.9.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

---------------------------------------------------------

**MINION**
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by grandmasterv** [comment]
Ok I found a work around.  I still believe my first jinja statement should of worked on the master though.

`{{ None | strftime('%Y-%m-%d_%H-%M') }}`

**Comment by grandmasterv** [comment]
Ok found that this also works.  Guess it was an issue with me putting the path in quotes.  Although I still find it strange that it worked with salt-call and not from salt master.  I'll close the issue.
```
#
# Backup the dev website folder before we clear it out.
#
dev wordpress backup {{ site }}:
  module.run:
    - archive.tar:
      - options: czf
      - tarfile: {{ site_info.backup }}/{{ site }}_backup_{{ "now" | strftime('%Y-%m-%d_%H-%M') }}.tar.gz
      - sources: '{{ site_info.document_root }}'
```
