### ISSUE TITLE
elasticsearch.index_template_present check_definition doesn't work

### ISSUE THREAD

**Issue by PauloGDPeixoto** [saltstack/salt#49700]
I'm trying to use the elasticsearch.index_template_present check_definition state to modify the default template, so I have the following in my sls file:
```
 default_template:  
   elasticsearch.index_template_present:  
     - definition:  
         index_patterns: "*"  
         order: 0  
         settings:  
           number_of_replicas: 5  
     - check_definition: True
```

Which gives the following output:
> ----------
>           ID: default_template
>     Function: elasticsearch.index_template_present
>       Result: False
>      Comment: expected string or buffer
>      Started: 16:36:13.310927
>     Duration: 53.124 ms
>      Changes:   

Whereas running without "- check_definition: True" gives correct output, but doesn't update an existing template.

I'm running salt-ssh 2018.3.2.
