### ISSUE TITLE
boto_route53: state based on record with multiple values always dirty

### ISSUE THREAD

**Issue by jodok** [saltstack/salt#49713]
### Description of Issue/Question

setting a boto_route53 state with multiple values is always dirty:

```
dev-3.mydomain.com:
----------
          ID: _dev._srv.mydomain.com
    Function: boto_route53.present
      Result: True
     Comment: Updated _dev._srv.mydomain.com Route53 record.
     Started: 19:29:30.309420
    Duration: 61471.669 ms
     Changes:
              ----------
              new:
                  ----------
                  identifier:
                      None
                  name:
                      _dev._srv.mydomain.com
                  record_type:
                      SRV
                  ttl:
                      None
                  value:
                      1 10 4300 dev-1.mydomain.com,2 10 4300 dev-2.mydomain.com,3 10 4300 dev-3.mydomain.com,4 10 4300 dev-4.mydomain.com,5 10 4300 dev-5.mydomain.com
              old:
                  ----------
                  name:
                      _dev._srv.mydomain.com.
                  record_type:
                      SRV
                  ttl:
                      60
                  value:
                      1 10 4300 dev-1.mydomain.com
```

it seems the value the state is checked against only returns the first item.

### Setup

```
_dev._srv.mydomain.com:
  boto_route53.present:
    - value:
      - "1 10 4300 dev-1.mydomain.com"
      - "2 10 4300 dev-2.mydomain.com"
      - "3 10 4300 dev-3.mydomain.com"
      - "4 10 4300 dev-4.mydomain.com"
      - "5 10 4300 dev-5.mydomain.com"
    - zone: mydomain.com
    - record_type: SRV
```

### Steps to Reproduce Issue
see above

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.11.4
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.26.4
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.2.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
