### ISSUE TITLE
salt-call over TLS/TCP results in AttributeError: 'NoneType' object has no attribute 'StreamClosedError'

### ISSUE THREAD

**Issue by cruscio** [saltstack/salt#49723]
### Description of Issue/Question

`salt-call` when connected to a master over TCP/TLS results in the following error. This only seems to happen with salt-call on the minion; there's nothing in the minion or master logs when posting a job from the master.

    Exception ignored in: <generator object _stream_return at 0x7f9c36573678>
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 1013, in _stream_return
    AttributeError: 'NoneType' object has no attribute 'StreamClosedError'
    Exception ignored in: <generator object _stream_return at 0x7f9c34cdb150>
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 1013, in _stream_return
    AttributeError: 'NoneType' object has no attribute 'StreamClosedError'

The master shows a `salt/auth` event and a `salt/job/[...]` event despite the minion-side error
 
### Setup

    minion:~$ cat /etc/salt/minion.d/*
    schedule:
      __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
        minutes: 60, return_job: false}
    publish_port: 4000
    master_port: 4001
    master: {master_fqdn}
    transport: tcp
    ssl: {}

    master:/ $ cat /etc/salt/master.d/*
    log_level: warning
    log_level_logfile: warning
    ext_pillar:
      - file_tree:
          root_dir: /srv/pillar/cmdb_tree
          follow_dir_links: False
          keep_newline: True
    publish_port: 4000
    ret_port: 4001
    transport: tcp
    ssl:
      keyfile: /etc/tls/privkey.pem
      certfile: /etc/tls/fullchain.pem
      ssl_version: PROTOCOL_TLSv1_2

The master is running in a docker container as a non-root user.
 
### Steps to Reproduce Issue

    minion:~$ sudo salt-call -l debug test.ping
    [DEBUG   ] Reading configuration from /etc/salt/minion
    [DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
    [DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
    [DEBUG   ] Including configuration from '/etc/salt/minion.d/ports.conf'
    [DEBUG   ] Reading configuration from /etc/salt/minion.d/ports.conf
    [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: {minion_id}
    [DEBUG   ] Configuration file path: /etc/salt/minion
    [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
    [DEBUG   ] Grains refresh requested. Refreshing grains.
    [DEBUG   ] Reading configuration from /etc/salt/minion
    [DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
    [DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
    [DEBUG   ] Including configuration from '/etc/salt/minion.d/ports.conf'
    [DEBUG   ] Reading configuration from /etc/salt/minion.d/ports.conf
    [DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
    [DEBUG   ] Connecting to master. Attempt 1 of 1
    [DEBUG   ] Master URI: tcp://{master_ip}:4001
    [DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6c4b5487de_pub.ipc
    [DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6c4b5487de_pull.ipc
    [DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', '{minion_id}', 'tcp://{master_ip}:4001')
    [DEBUG   ] salt.crypt.get_rsa_key: Loading private key
    [DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    [DEBUG   ] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', '{minion_id}', 'tcp://{master_ip}:4001', 'clear')
    [DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
    [DEBUG   ] Decrypting the current master AES key
    [DEBUG   ] salt.crypt.get_rsa_key: Loading private key
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    [DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
    [DEBUG   ] tcp stream to {master_ip}:4001 closed, unable to recv
    [DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6c4b5487de_pull.ipc
    [DEBUG   ] Sending event: tag = __master_connected; data = {'master': '{master_fqdn}', '_stamp': '2018-09-20T12:59:04.428817'}
    [DEBUG   ] salt.crypt.get_rsa_key: Loading private key
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    [DEBUG   ] Determining pillar cache
    [DEBUG   ] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', '{minion_id}', 'tcp://{master_ip}:4001', 'aes')
    [DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', '{minion_id}', 'tcp://{master_ip}:4001')
    [DEBUG   ] salt.crypt.get_rsa_key: Loading private key
    [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
    [DEBUG   ] LazyLoaded jinja.render
    [DEBUG   ] LazyLoaded yaml.render
    [DEBUG   ] LazyLoaded test.ping
    [DEBUG   ] test.ping received for minion '{minion_id}'
    [DEBUG   ] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', '{minion_id}', 'tcp://{master_ip}:4001', 'aes')
    [DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', '{minion_id}', 'tcp://{master_ip}:4001')
    [DEBUG   ] LazyLoaded nested.output
    local:
        True
    Exception ignored in: <generator object _stream_return at 0x7f9c36573678>
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 1013, in _stream_return
    AttributeError: 'NoneType' object has no attribute 'StreamClosedError'
    Exception ignored in: <generator object _stream_return at 0x7f9c34cdb150>
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 1013, in _stream_return
    AttributeError: 'NoneType' object has no attribute 'StreamClosedError'

### Versions Report

    minion-001:~$ salt-call -V
    Salt Version:
               Salt: 2018.3.2
    
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.6.5 (default, Apr  1 2018, 05:46:30)
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.2.5
    
    System Versions:
               dist: Ubuntu 18.04 bionic
             locale: UTF-8
            machine: x86_64
            release: 4.15.0-1023-azure
             system: Linux
            version: Ubuntu 18.04 bionic

--

    master:/ $ salt -V
    Salt Version:
               Salt: 2018.3.1
    
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: Not Installed
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: 0.27.2
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: 0.27.1
             Python: 3.6.6 (default, Aug 24 2018, 05:04:18)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 17.0.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.2
                ZMQ: 4.2.3
    
    System Versions:
               dist:
             locale: UTF-8
            machine: x86_64
            release: 4.15.0-1023-azure
             system: Linux
            version: Not Installed

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this only when running python3 and using tcp transport. I tested on 2018.3/develop/fluorine and am seeing the same thing also tried tornado 5.0.2 and saw the same error.

**Comment by cruscio** [comment]
Switched back to python2 (master and minion) and it's happening with a Windows minions.

#### Minion Versions Report

```
C:\Windows\system32>c:\salt\salt-call --local test.versions_report
local:
    Salt Version:
               Salt: 2018.3.2

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
```

#### Master Versions Report

```
salt@66536cfa194e:/$ salt --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.0-1023-azure
         system: Linux
        version: Ubuntu 18.04 bionic
```

``` 
salt@66536cfa194e:/$ salt '*' test.ping       
{{MINION}}:
    True
Exception AttributeError: "'NoneType' object has no attribute 'StreamClosedError'" in <generator object _stream_return at 0x7f386b54f370> ignored
```

Worth noting the Salt Master is running in Azure in a docker container and the Salt Minion is in another data center, connecting over the internet via TCP/TLS transport.
