### ISSUE TITLE
Documentation should say that raid.present and related states need "mdadm" to be installed

### ISSUE THREAD

**Issue by rsuarezsoto** [saltstack/salt#49740]
The state `raid.present` and related need the program `mdadm` to be installed, but no mention of it appears in the docs. I was trying to test the `raid.present` state with this SLS (`mdadm/test.sls`):

```
/dev/md0:
  raid.present:
    - level: 0
    - devices:
      - /dev/xvdc
      - /dev/xvde
    - run: True
```

But it always came up with this error:

```
local:
----------
          ID: /dev/md0
    Function: raid.present
      Result: False
     Comment: State 'raid.present' was not found in SLS 'mdadm.test'
              Reason: 'raid.present' is not available.
     Changes:   
```

And after installing `mdadm`:

```
local:
----------
          ID: /dev/md0
    Function: raid.present
      Result: None
     Comment: Raid will be created with: mdadm -C /dev/md0 -R -v --run -l 0 -e default -n 2 /dev/xvdc /dev/xvde
     Started: 12:01:00.043877
    Duration: 33.045 ms
     Changes:   
```
It seems obvious afterwards, but somehow I thought that Salt would magically install it. A quick note in the docs should be enough to avoid other people stumbling like I did.
