### ISSUE TITLE
when using 'prereq' in orchestration pre-requiring state does not run

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#49753]
### Description of Issue/Question
When using 'prepreq' in orchestration, I can see that the pre-required state first runs with `test=True` and then runs in real, but the pre-requiring state did not run at all.
### Setup
```
orchestration/test.sls

test3:
  salt.state:
    - tgt: 'region1.freebsd1'
    - sls:
        - myapp.test

test2:
  cmd.run:
    - name: "echo test2"
    - prereq:
      - test3
```
```
myapp/test.sls

/tmp/testfile:
  file.managed:
    - contents: 'abcd'

```

### Steps to Reproduce Issue
```
salt-run state.orch orchestration.test -l trace
```
test3 will run twice, first time in test mode, second time in real, but test2 never run.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.12
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Jul 27 2018, 19:19:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE
         system: FreeBSD
        version: Not Installed

```
