### ISSUE TITLE
jinja raw: Jinja syntax error: unexpected char u'$' 

### ISSUE THREAD

**Issue by knfoo** [saltstack/salt#49768]
I have a yaml file that I am putting together based on a number of things.
I am using jinja templating and using raw to tell jinja that it should not try to pass text between the `raw` and `endraw` blocks

### Setup
the setup is this:
init.sls
```
configure files for prometheus:
  file.recurse:
    - name: /tmp/prometheus
    - source: salt://{{ slspath }}/files
    - user: admin
    - file_mode: 644
    - dir_mode: 755
    - template: jinja
    - context:
      etcd0IP: {{ etcd0IP.value }}
      etcd1IP: {{ etcd1IP.value }}
      etcd2IP: {{ etcd2IP.value }}
      etcdca: {{ etcdca }}
      etcdclient: {{ etcdclient }}
      etcdclientkey: {{ etcdclientkey }}
      clustername: {{ clustername }}
      internal_clustername: {{ internal_clustername }}
      search: "k8s:clustername:{{ clustername }}"
```

in my files directory there are a bunch of files one of which is a `prometheus-k8s-rules.yaml`
This file is a rules file for prometheus and contains a lot of alerting rules.
This file is encaplulated in {% raw %} and {% endraw %}

```
{%- set prometheus = pillar['prometheus'] -%}
{%- raw %}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-k8s-rules
  labels:
    role: prometheus-rulefiles
    prometheus: k8s
data:
  alertmanager.rules.yaml: |+
    groups:
    - name: alertmanager.rules
      rules:
      - alert: AlertmanagerConfigInconsistent
        expr: count_values("config_hash", alertmanager_config_hash) BY (service) / ON(service)
          GROUP_LEFT() label_replace(prometheus_operator_alertmanager_spec_replicas, "service",
          "alertmanager-$1", "alertmanager", "(.*)") != 1
        for: 5m
        labels:
          severity: critical
        annotations:
          description: The configuration of the instances of the Alertmanager cluster
            `{{$labels.service}}` are out of sync.
          summary: Configuration out of sync
      - alert: AlertmanagerDownOrMissing
        expr: label_replace(prometheus_operator_alertmanager_spec_replicas, "job", "alertmanager-$1",
          "alertmanager", "(.*)") / ON(job) GROUP_RIGHT() sum(up) BY (job) != 1
        for: 5m
        labels:
          severity: warningJinja syntax error: unexpected char u'$' 
        annotations:
          description: An unexpected number of Alertmanagers are scraped or Alertmanagers
            disappeared from discovery.
          summary: Alertmanager down or missing
      - alert: AlertmanagerFailedReload
        expr: alertmanager_config_last_reload_successful == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          description: Reloading Alertmanager's configuration has failed for {{ $labels.namespace
            }}/{{ $labels.pod}}.
          summary: Alertmanager's configuration reload failed
{% endraw %}
```

But it gives me this error non the less.
```
          ID: prometheus files                                  
    Function: file.recurse                                                            
        Name: /tmp/prometheus                                                       
      Result: False                                                                    
     Comment: #### /tmp/prometheus/manifests/prometheus-k8s/prometheus-k8s-rules.yaml ####
              Unable to manage file: Jinja syntax error: unexpected char u'$' at 584; line 16
                                                        
              ---                                                             
              [...]                              
                      for: 5m                                                               
                      labels:                                                        
                        severity: critical                          
                      annotations:                                                  
                        description: The configuration of the instances of the Alertmanager cluster
                          `{{$labels.service}}` are out of sync.    <======================
                        summary: Configuration out of sync                         
                    - alert: AlertmanagerDownOrMissing                            
                      expr: label_replace(prometheus_operator_alertmanager_spec_replicas, "job", "alertmanager-$1",
                        "alertmanager", "(.*)") / ON(job) GROUP_RIGHT() sum(up) BY (job) != 1
                      for: 5m                                        
              [...]                                      
              ---                                        
     Started: 13:09:24.518995                            
    Duration: 4408.064 ms 
```

I have also tried to escape ``` `{{$labels.service}}` ``` like this ```{{ '`{{$labels.service}}`' }}``` with same result

### Versions Report
```
 salt --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: 3.3.0
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4 
```
