### ISSUE TITLE
Delay/timer/sleep function to wait between state declarations

### ISSUE THREAD

**Issue by mallniya** [saltstack/salt#49787]
### Description of Issue/Question
Hello, I wonder if there is a tool in saltstack to delay separate state declarations except simple `cmd.run sleep`, like this (specific function here is just random and is not important):
```
function-with-long-lasting-post-actions:
  cmd.run

sleep 10:
  cmd.run:
     - require:
      cmd: function-with-long-lasting-post-actions

package-name:
  pkg.install:
    - require:
      cmd: sleep 10
```
What is to stress here -- `function-with-long-lasting-post-actions` is not necessarily cmd.run (because with cmd.run we always have sleep command of the shell -- but this way is not what I expect to see when using salt). All I really want -- is a salt sleep function not relying on the shell and cmd.run. I've found service.running specific init_delay option in https://github.com/saltstack/salt/issues/19084, but not generic delay/timer/sleep tool to wait between state declarations.
Please advise or consider this as feature request.
