### ISSUE TITLE
no merge option in match.filter_by

### ISSUE THREAD

**Issue by drel4o** [saltstack/salt#49845]
Hello there,

I was playing around with map jinjas and I figured out that the function filter_by in the match module does not support merge option. It would be quite useful to have it available as in grains.filter_by for example.

I apologize if that has been requested before or if there is a good reason for merge to be missing.

Salt Version:
           Salt: 2018.3.2

Thanks in advance.
d

**Comment by gtmanfred** [comment]
Can you provide some more information about what you mean by "merge"?  Are you just wanting to merge lists or something elses?

**Comment by drel4o** [comment]
Hello,

For example I can do the following:

test.yml

```
os:
  CentOS:
    somekey: somevalue

osmajorrelease:
  7:
    otherkey: othervalue
```

and in map.jinja

```
{% import_yaml 'test.yaml' as test %}
{% set result = salt.grains.filter_by(test.os, grain = 'os', merge = 
                salt.grains.filter_by(test.osmajorrelease, grain = 'osmajorrelease')) %}
```
However if I use match.filter_by e.g.:

test.yml:

```
pcre_match:
  .*dev.*:
    somekey: somevalue

os:
  CentOS:
    otherkey: othervalue
```

```
{% set result = salt.match.filter_by(test.pcre_match, tgt_type = 'pcre', merge = 
                salt.grains.filter_by(test.os grain = 'os')) %}
```
I get an error:
`TypeError: filter_by() got an unexpected keyword argument 'merge'`

This is expected as this is not implemented in the function.

Thanks.
D
