### ISSUE TITLE
Windows directory permission enforcement failure

### ISSUE THREAD

**Issue by lachlanmunro** [saltstack/salt#49861]
### Description of Issue/Question
Salt `file.directory` state fails with the following when enforcing permissions:

```
----------
          ID: c:/directory
    Function: file.directory
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1905, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 2954, in directory
                  win_perms_reset=win_perms_reset)
                File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 898, in _check_directory_win
                  if user_name not in win_deny_perms:
              TypeError: argument of type 'NoneType' is not iterable
     Started: 13:49:10.877067
    Duration: 33.999 ms
     Changes:
----------
```

### Setup
Assuming an existing user called usernamehere, the below state fails for me as above.

### Steps to Reproduce Issue
```
c:/directory:
  file.directory:
    - makedirs: True
    - user: Administrators
    - win_perms_reset: True
    - win_inheritance: False
    - win_perms:
        Administrators:
          perms: full_control
        usernamehere:
          perms: read_execute
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.17134 SP0 Multiprocessor Free
```
