### ISSUE TITLE
Retry for module.run is not working

### ISSUE THREAD

**Issue by mescanef** [saltstack/salt#49895]
### Description of Issue/Question
Hello!

For salt 2017.7 is there an option to do a retry for a module.run within sls? Ive created a very simple 
sls which uses such approach and during the salt run Im getting the following python trace:
```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1476, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1139, in sls
        ret = st_.state.call_high(high_, orchestration_jid)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2590, in call_high
        ret = self.call_chunks(chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2051, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2404, in call_chunk
        running[tag] = self.call(low, chunks, running)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1946, in call
        if not sys.modules[self.states[cdata['full']].__module__].__opts__['test']:
    AttributeError: 'module' object has no attribute '__opts__'
```
### Setup

```
# elasticsearch/client $ cat init.sls
elasticsearch_check_cluster_status_before_creating_index:
  module.run:
    - name: elasticsearch.cluster_health
    - retry:
        attempts: 5
        until: True
        interval: 10
        splay: 5
```
### Steps to Reproduce Issue

```
salt 'node_name*' elasticsearch.client
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.1.0
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
Is there a bug or issue in my sls and a way to workaround/fix it? Thanks in advance.

**Comment by gtmanfred** [comment]
I have replicated this issue, it appears to be a bug in the logic for retry and module.run

A simple test to show what is happening, this state can be used.

```
test:
  module.run:
    - name: test.ping
    - retry:
        attempts: 5
        until: True
        interval: 10
        splay: 5
```

Thanks for reporting, we will get it fixed.

@saltstack/team-core does anyone know anything about the retry logic? it looks like for some reason the `module` state does not have `__opts__` in it?

@lomeroe can you also take a look since you implemented the retry logic?

Thanks,
Daniel

**Comment by lomeroe** [comment]
"prereq" uses the __opts__ in the same manner, looks like #44639 has a little more info (as prereq with module.run fails too, for the same reason)

**Comment by network-shark** [comment]
Anyone working on this ?

**Comment by Oloremo** [comment]
Stale bot go away, this is an issue

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!

**Comment by network-shark** [comment]
Looks ok for me .
```
sharky@salt dev % cat retry.sls
test:
  module.run:
    - name: test.ping
    - retry:
        attempts: 5
        until: True
        interval: 10
        splay: 5
sencond_test:
  module.run:
    - name: test.echo
    - text: "hi"
    - retry:
        attempts: 5
        until: True
        interval: 3
sharky@salt dev %
```
```
root@salt:~# salt box state.apply retry  saltenv=dev
jid: 20230926114154802239
seedbox:
----------
          ID: test
    Function: module.run
        Name: test.ping
      Result: True
     Comment: Module function test.ping executed
     Started: 13:41:56.075034
    Duration: 8.879 ms
     Changes:
              ----------
              ret:
                  True
----------
          ID: sencond_test
    Function: module.run
        Name: test.echo
      Result: True
     Comment: Module function test.echo executed
     Started: 13:41:56.084820
    Duration: 3.963 ms
     Changes:
              ----------
              ret:
                  hi

Summary for seedbox
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:  12.842 ms

```
