### ISSUE TITLE
pkgrepo not correctly recognize architecture for apt in test=true

### ISSUE THREAD

**Issue by do3meli** [saltstack/salt#49894]
### Description of Issue/Question

pkgrepo.managed is not correctly recognizing the architecture for apt based systems when running with test=true. with below scenario test=true always return a change even the repository is correctly setup.

it does not work with the following variations:
* having `[arch=amd64]` in the name attribute of the pkgrepo.managed state
* having `architecture: amd64` as attribute of the pkgrepo.managed state

### Setup
sls
```
salt_minion_repo:
  pkgrepo.managed:
    - name: deb [arch=amd64] http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic main
    - file: /etc/apt/sources.list.d/saltstack.list
    - key_url: salt://{{ slspath }}/files/SALTSTACK-GPG-KEY.pub
```

### Steps to Reproduce Issue
1. create file `/etc/apt/sources.list.d/saltstack.list` on salt minion containing the repository with `[arch=amd64]`
2. run highstate against the minion with `test=true` => should show a change (NOT OK)
3. run highstate against the minion with `test=false` => not showing a change (OK)

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-36-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
