### ISSUE TITLE
Pillar merging strategy

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#49910]
Hi,

I'm reading this documentation http://docs.saltstack.cn/ref/pillar/all/salt.pillar.stack.html
In my top.sls pillar file I have

```
base:
  '*':
    - application.sudoers
  'myminion':
    - fqdn.myminion
```

In application/sudoers/init.sls I have

```
sudoers:
  groups:
    users_l3:
      - 'ALL=(ALL) ALL'
  users:
    ansible:
      - 'ALL=(ALL) NOPASSWD: ALL'
    root:
      - 'ALL=(ALL) NOPASSWD: ALL'
  defaults:
    user_list:
      ansible: '!requiretty'
```

In fqdn/myminion.sls I try to add "poil" but remove the group "user_l3" (remove all the groups key)

```
sudoers:
  __: overwrite
  users:
    ansible:
      - 'ALL=(ALL) NOPASSWD: ALL'
    root:
      - 'ALL=(ALL) NOPASSWD: ALL'
    poil:
      - 'ALL=(ALL) NOPASSWD: ALL'
  defaults:
    user_list:
      ansible: '!requiretty'
```

But when I dump the pillar data for my node "myminion" via `salt 'myminion' pillar.data` I still have my "groups" key.

```
    sudoers:
        ----------
        __:
            overwrite
        defaults:
            ----------
            user_list:
                ----------
                ansible:
                    !requiretty
        groups:
            ----------
            users_l3:
                - ALL=(ALL) ALL
        users:
            ----------
            ansible:
                - ALL=(ALL) NOPASSWD: ALL
            poil:
                - ALL=(ALL) NOPASSWD: ALL
            root:
                - ALL=(ALL) NOPASSWD: ALL

```

I have also tried with "remove" and to overwrite with a "groups" set to none but in all saltstack formula there is no check like "if key exist in the dict and is not none"

Any idea ?

Best regards,
