### ISSUE TITLE
value Disabled is not acceptable for policy

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#49915]
### Description of Issue/Question
 if you try to disable a policy, the word “Disabled” won’t work (as shown in the module doc). I had to use “This policy is disabled”. It’s possible to set the policy as Not Defined, setting the value to “Not Defined”.
```
block_microsoft_accounts_bad:
  lgpo.set:
    - computer_policy:
#        "Accounts: Block Microsoft accounts": "Not Defined"   # WORKS FINE
#        "Accounts: Block Microsoft accounts": "This policy is disabled" # WORKS FINE
      "Accounts: Block Microsoft accounts": Disabled # DOES NOT WORK
```

It returns SaltInvocationError: The specified value Disabled is not an acceptable setting for policy Accounts: Block Microsoft accounts.

### Setup
```
block_microsoft_accounts_OK:
  lgpo.set:
    - computer_policy:
        "Accounts: Block Microsoft accounts": "Not Defined"
```

```
block_microsoft_accounts_BAD:
  lgpo.set:
    - computer_policy:
        "Accounts: Block Microsoft accounts": Disabled
```
