### ISSUE TITLE
2018.3.2, failed: could not determine a constructor for the tag

### ISSUE THREAD

**Issue by nicholashoule** [saltstack/salt#49921]
### Description of Issue/Question

I've configured my salt server to look to GitHub for the pillar, states, and reactor data, but I can't seem to get past two errors when restarting my targeted minion. Additionally, for the life of me, I cannot set the root users or any other users password to either '*' or '!' using my reactor file (start.sls).

**Error 1**
```
2018-10-06 16:16:07,795 [salt.state           :3454][CRITICAL][4921] Rendering SLS 'base:users' failed: could not determine a constructor for the tag '!$6$./xyz'
  in "<unicode string>", line 7, column 17:
        - password: !$6$./xyz ... 
```

**Error 2**
Fails silently and the minion doesn't update the users.
Running `state.apply users` works.

### Setup

Getting pillar and states from GitHub.

**master:**

/etc/salt/master
```
gitfs_remotes:
   # HTTPS authentication
   - https://github.com/[user]/salt-states.git:
     - user: user
     - password: password


ext_pillar:
   - git:
     # HTTPS authentication
     - master https://github.com/[user]/salt-pillar.git:
       - user: user
       - password: password

reactor:
   - 'salt/minion/*/start':
    - salt://reactor/start.sls
```

**pillar:**

/pillar/top.sls
```
base:
  '*':
    - users
    - pkg
```

/pillar/users/init.sls
```
 users:
  {% if grains['os_family'] == 'RedHat' %}
  # Not supported
  
  {% elif grains['os_family'] == 'Debian' %}
    
  {% if grains['os'] == 'Ubuntu' %}
  # Users for Ubuntu
  root:
    fullname: root
    password: '"!"'
    shell: /bin/bash

  user1:
    fullname: User 1
    password: '"*"'
    shell: /bin/bash
 
  user2:
    fullname: User 2
    password: '"!$6$./xyz ..."'
    shell: /bin/bash
    ssh-keys:
      - ssh-ed25519 AAAAXYZ devops@saltstack.com
  {% endif %}
    
  {% elif grains['os'] == 'Arch' %}
  # Not supported
  {% endif %}
```

**states:**

/srv/salt/users/init.sls
```
# Add users
{% for user, args in pillar['users'].iteritems() %}
{{ user }}:
  group.present:
    - system: True
  user.present:
    - fullname: {{ args['fullname'] }}
    - password: {{ args['password'] }}
    - shell: {{ args['shell'] }}
    {% if not user == 'root' %}
    - groups:
      - {{ user }}
      - adm
      - sudo
    {% endif %}
    
{% if 'ssh-keys' in args %}
# User has ssh-keys
{{ user }}-sshkey:
  ssh_auth.present:
    - user: {{ user }}
    - config: '%h/.ssh/authorized_keys'
    - names:
      {% for key in args['ssh-keys'] %}
      - {{ key }}
      {% endfor %}
      
{% endif %}
{% endfor %}
```

**reactor:**

/srv/reactor/start.sls
```
highstate_run_packages:
  local.state.apply:
    - tgt: 'os:Ubuntu'
    - tgt_type: grain
    - arg:
      - packages
      
highstate_run_users:
  local.state.apply:
    - tgt: 'os:Ubuntu'
    - tgt_type: grain
    - arg:
      - users
```

### Steps to Reproduce Issue
Follow the pillar doc specifically to add users and packages.
https://docs.saltstack.com/en/latest/topics/tutorials/pillar.html

Use a git-backed salt server for:
- pillar
- states
- reactor

Modify the pillar users file to resemble mine.
Modify the state users file to resemble mine.
Add the reactor start.sls file targeting at least one minion.
Change the passwords for the targeted users.
Restart the minion targeted in the reactor start.sls file.

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-36-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
