### ISSUE TITLE
lgpo state module Unable to find machine policy "Devices: Prevent users from installing printer drivers"

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#49971]
### Description of Issue/Question
state module lgpo.set Unable to find machine policy "Devices: Prevent users from installing printer drivers"

### Setup
```
set_policy_enable:
  lgpo.set:
    - computer_policy:
      "Devices: Prevent users from installing printer drivers": 'Enabled'
```
```
local:
----------
          ID: prevent_users_installing_printer_drivers
    Function: lgpo.set
      Result: False
     Comment: Unable to find Machine policy Devices: Prevent users from installing printer drivers
     Started: 12:56:38.350000
    Duration: 2968.0 ms
     Changes:
```

### Steps to Reproduce Issue
(windows): salt-call state.sls "state"

### Versions Report
salt 2018.3.2
Windows 2016 Server
