### ISSUE TITLE
support FreeBSD md devices in mount.mounted state

### ISSUE THREAD

**Issue by do3meli** [saltstack/salt#49970]
### Description of Issue/Question
Currently it is not possible to create a mount.mounted state for an MD device in FreeBSD. The problem most likely is due to a different fstype in /etc/fstab (mfs) compared to the `mount -p` (ufs):

output of `mount -p`:
```
/dev/md0		/var/cache/test ufs	rw		2 0
```
content in `/etc/fstab`:
```
md      /var/cache/test        mfs     rw,-s20G,late,-p755 2 0
```

### Setup
the following SLS has been used to test this on a FreeBSD 11.2 Minion:
```
test_md_device_state:
  mount.mounted:
    - name: /var/cache/test
    - device: md
    - fstype: mfs
    - opts:
      - rw
      - -s20G
      - late
      - -p755
    - hidden_opts:
      - -s20G
      - late
      - -p755
    - dump: 2
    - device_name_regex:
      - /dev/md0
```

### Steps to Reproduce Issue

- create an fstab entry like mentioned above
- create an sls file with above state
- run state against FreeBSD minion currently give following error/output:
```
----------
          ID: test_md_device_state
    Function: mount.mounted
        Name: /var/cache/test
      Result: None
     Comment: An umount would have been forced because devices do not match.  Watched: md. Entry already exists in the fstab.
     Started: 14:00:28.201156
    Duration: 141.49 ms
     Changes: 
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Sep 21 2018, 13:07:25)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE-p4
         system: FreeBSD
        version: Not Installed
```
