### ISSUE TITLE
Windows: reg.set_value of type REG_QWORD causes traceback

### ISSUE THREAD

**Issue by dafyddj** [saltstack/salt#50039]
### Description of Issue/Question

Trying to set a Windows registry item of type REQ_QWORD causes traceback.

### Setup

Tried with Windows 8.1, Windows 10 1803. 
Salt 2018.3.2, develop branch

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
```
PS C:\Python27\Scripts> ..\python.exe .\salt-call --local reg.set_value hive=HKLM key=SOFTWARE vname=test vdata=175 vtyp
e=REG_QWORD
[ERROR   ] Encountered error setting registry value
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\salt\utils\win_reg.py", line 708, in set_value
    win32api.RegSetValueEx(handle, local_vname, 0, vtype_value, local_vdata)
SystemError: ..\Objects\longobject.c:998: bad argument to internal function
local:
    False
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
PS C:\Python27\Scripts> ..\python.exe .\salt-call --versions-report
Salt Version:
           Salt: 2018.11.0-234-ge57a110

Dependency Versions:
           cffi: 1.5.0
       cherrypy: 5.0.1
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 8.1
         system: Windows
        version: 8.1 6.3.9600  Multiprocessor Free
```
