### ISSUE TITLE
State file.file_missing in /dev does not work (always false) but module works as expected

### ISSUE THREAD

**Issue by mruepp** [saltstack/salt#50042]
### Description of Issue/Question
Running 
`salt '*' file.file_exists '/dev/sdb' `
or on other files in /dev returns always "false"

Using: 
`{%- if salt['file.file_exists']('/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0') %}`

to detect if device exists, returns always false.

The state module however does work:
```
firstDisk:
  file.missing:
    - name: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0

/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0:
    blockdev.formatted:
      - fs_type: xfs
      - unless: file -sL /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0 | grep filesystem
      - onfail:
        - file: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:                                           
           Salt: 2018.3.2                               
                                                        
Dependency Versions:                                    
           cffi: 1.6.0                                  
       cherrypy: Not Installed                          
       dateutil: Not Installed                          
      docker-py: Not Installed                          
          gitdb: Not Installed                          
      gitpython: Not Installed                          
          ioflo: Not Installed                          
         Jinja2: 2.7.2                                  
        libgit2: 0.26.3                                 
        libnacl: Not Installed                          
       M2Crypto: Not Installed                          
           Mako: Not Installed                          
   msgpack-pure: Not Installed                          
 msgpack-python: 0.5.6                                  
   mysql-python: Not Installed                          
      pycparser: 2.14                                   
       pycrypto: 2.6.1                                  
   pycryptodome: Not Installed                          
         pygit2: 0.26.4                                 
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57) 
   python-gnupg: Not Installed                          
         PyYAML: 3.11                                   
          PyZMQ: 15.3.0                                 
           RAET: Not Installed                          
          smmap: Not Installed                          
        timelib: Not Installed                          
        Tornado: 4.2.1                                  
            ZMQ: 4.1.4                                  
                                                        
System Versions:                                        
           dist: centos 7.5.1804 Core                   
         locale: UTF-8                                  
        machine: x86_64                                 
        release: 3.10.0-862.14.4.el7.x86_64             
         system: Linux                                  
        version: CentOS Linux 7.5.1804 Core
