### ISSUE TITLE
Checking for multiple status with http.query state

### ISSUE THREAD

**Issue by DrPyser** [saltstack/salt#50067]
### Description of Issue/Question
When using the `http.query` state, I would need for the state to match multiple status. That is, I expect a successful response to be either a status 201 or 200. Is there a way to do that currently? If not, there are multiple ways to add support for this use case:
* Allow `status` to be a list of accepted values
* Make `match_type` also apply to the status matching, so that one could use a regular expression to match the status.

I prefer the second option, more flexible. 
 
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
{% set my_cert = salt['cmd.shell']('cat '+ pillar['my_cert_path']) %}
{% set my_cert_key = salt['cmd.shell']('cat '+ pillar['my_cert_key_path']) %}


kong_admin_api_available:
  http.query:
    - name: {{ pillar.get("kong_admin_url", "https://example.domain.com:8444")}}/
    - method: OPTIONS
    - status: 204

upload_certificate:
  http.query:
    - name: {{ pillar.get("kong_admin_url", "https://example.domain.com:8444")}}/certificates/{{ pillar["kong_certificate_hostname"] }}
    - method: PUT
    - data: |
        { "key": {{ my_cert_key|json }}, "cert": {{ my_cert|json }}}
    - header_dict:
        Content-Type: application/json
    - match_type: pcre
    - status: "(200)|(201)"
    - require:
        - kong_admin_api_available
```
Since the semantics of the `PUT` call is "create or update", the call might return a 201 on a first request and 200 on the nexts.

### Versions Report
<details><p>
```
Salt Version:                                                                                                                                              
           Salt: 2018.3.2                                                                                                                                  
                                                                                                                                                           
Dependency Versions:                                                                                                                                       
           cffi: Not Installed                                                                                                                             
       cherrypy: Not Installed                                                                                                                             
       dateutil: 2.6.1                                                                                                                                     
      docker-py: 2.5.1                                                                                                                                     
          gitdb: 2.0.3                                                                                                                                     
      gitpython: 2.1.8                                                                                                                                     
          ioflo: Not Installed                                                                                                                             
         Jinja2: 2.10                                                                                                                                      
        libgit2: Not Installed                                                                                                                             
        libnacl: Not Installed                                                                                                                             
       M2Crypto: Not Installed                                                                                                                             
           Mako: 1.0.7                                                                                                                                     
   msgpack-pure: Not Installed                                                                                                                             
 msgpack-python: 0.5.6                                                                                                                                     
   mysql-python: Not Installed                                                                                                                             
      pycparser: Not Installed                                                                                                                             
       pycrypto: 2.6.1                                                                                                                                     
   pycryptodome: Not Installed                                                                                                                             
         pygit2: Not Installed                                                                                                                             
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)                                                                                                
   python-gnupg: 0.4.1                                                                                                                                     
         PyYAML: 3.12                                                                                                                                      
          PyZMQ: 16.0.2                                                                                                                                    
           RAET: Not Installed                                                                                                                             
          smmap: 2.0.3                                                                                                                                     
        timelib: Not Installed                                                                                                                             
        Tornado: 4.5.3                                                                                                                                     
            ZMQ: 4.2.5                                                                                                                                     
                                                                                                                                                           
System Versions:                                                                                                                                           
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-46-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</p></details>
