### ISSUE TITLE
Errors in syslog shows secrets

### ISSUE THREAD

**Issue by jeffdyke** [saltstack/salt#50123]
### Description of Issue/Question
Tangentially related to #39314, i have a compound match error, which i can and will fix, and i use git-crypt for all secret pillar data, but `ALL` of my pillar data is dumped to syslog on salt-master when this error occurs, which means passwords, private keys for certs etc etc.  
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
all configs are default overrides in master.d are
```
worker_threads: 3
salt_event_pub_hwm: 2000
event_publisher_pub_hwm: 1000
hash_type: sha256
file_roots:
  base:
    - /srv/salt

pillar_roots:
  base:
    - /srv/pillar/base
  dev:
    - /srv/pillar/dev
  staging:
    - /srv/pillar/staging
  prod:
    - /srv/pillar/prod
  devbuilds:
    - /srv/pillar/devbuilds
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
add the following as a compound match `G@environment:prod && G@region:us-west-2` to top.sls pillar file. 
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1023-aws
         system: Linux
        version: Ubuntu 18.04 bionic
```
There is no difference between master and its minions.

Thanks
