### ISSUE TITLE
Failed to create temp network for comparison: Unable to perform create_network: create_network() got an unexpected keyword argument 'enable_ipv6'

### ISSUE THREAD

**Issue by mattiasr** [saltstack/salt#50194]
### Description of Issue/Question
Try to create docker network via salt on Ubuntu 16.04.
```
----------
          ID: create_docker_network
    Function: docker_network.present
        Name: my_cool_network
      Result: False
     Comment: Failed to create network 'my_cool_network': Unable to perform create_network: create_network() got an unexpected keyword argument 'enable_ipv6'
     Started: 09:57:59.004184
    Duration: 4.453 ms
     Changes:   
----------
```

### Workaround
Update python-docker to newer version.
* `pip install docker`
* Upgrade to Ubuntu 18.04

### Setup
Ubuntu 16.04
salt-master 2018.3.2 (Oxygen)
salt-minion 2018.3.2 (Oxygen)
OS Package: docker-ce Version: `18.06.1~ce~3-0~ubuntu`
OS Package: python-docker Version: `1.9.0-1~16.04.1`
```
SLS config:
create_docker_network:                                           
  docker_network.present:                                                       
    - name: my_cool_network
```
After upgrade:
Ubuntu 18.04
Package: docker-ce Version: `18.06.1~ce~3-0~ubuntu`
Package: python-docker Version: `2.5.1-1`

### Steps to Reproduce Issue
Apply state with `create_docker_network`.
```
----------
          ID: create_docker_network
    Function: docker_network.present
        Name: my_cool_network
      Result: False
     Comment: Failed to create network 'my_cool_network': Unable to perform create_network: create_network() got an unexpected keyword argument 'enable_ipv6'
     Started: 09:57:59.004184
    Duration: 4.453 ms
     Changes:   
----------
```

Create network manually
`docker create network my_cool_network`

Then try to apply state again.
```
----------
          ID: create_docker_network
    Function: docker_network.present
        Name: my_cool_network
      Result: False
     Comment: Failed to create temp network for comparison: Unable to perform create_network: create_network() got an unexpected keyword argument 'enable_ipv6'
     Started: 10:00:23.768451
    Duration: 4.553 ms
     Changes:   
----------

```
Upgrade to `Ubuntu 18.04` and `python-docker` package (by default)
Apply state with `create_docker_network`.
```
----------
          ID: create_docker_network
    Function: docker_network.present
        Name: my_cool_network
      Result: True
     Comment: Network 'my_cool_network' already exists, and is configured as specified
     Started: 11:30:51.288322
    Duration: 381.094 ms
     Changes:   
----------
```
### Versions Report
Master:
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-137-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
Minion before upgrade:
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 1.9.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-137-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
Minion after upgrade:
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-38-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
