### ISSUE TITLE
salt.states.reg: HKEY_CURRENT_USER keeps adding items in HKEY_USERS

### ISSUE THREAD

**Issue by Local9** [saltstack/salt#50223]
### Description of Issue/Question
salt.stats.reg HKEY_CURRENT_USER keeps adding to HKEY_USERS

When using the following in a .reg file it works as intended.

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Classes\Typelib\{8cec5860-07a1-11d9-b15e-000d56bfe6ee}\1.0\0\win32]
@=""

[HKEY_CURRENT_USER\SOFTWARE\Classes\Typelib\{8cec5860-07a1-11d9-b15e-000d56bfe6ee}\1.0\0\win64]
@=""
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

disable-f1.sls
```
remove-f1-32bit-HKEY_CURRENT_USER:
  reg.present:
    - name: 'HKEY_CURRENT_USER\SOFTWARE\Classes\Typelib\{8cec5860-07a1-11d9-b15e-000d56bfe6ee}\1.0\0\win32'
    - vdata: ''

remove-f1-64bit-HKEY_CURRENT_USER:
  reg.present:
    - name: 'HKEY_CURRENT_USER\SOFTWARE\Classes\Typelib\{8cec5860-07a1-11d9-b15e-000d56bfe6ee}\1.0\0\win64'
    - vdata: ''
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Run the sls file above on Windows 7

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 25 2018, 20:42:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.11
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-6-amd64
         system: Linux
        version: debian 8.11
