### ISSUE TITLE
state cron.absent failes if cron module isn't loaded (not installed)

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#50320]
### Description of Issue/Question
I have a state file in which I want a cron entry absent, but I have a minion without cron
so the whole module cron isn't loaded and this fails the state

### Setup
archlinux setup without cron only systemd.

### Steps to Reproduce Issue
state:
```
cron.absent:
  - name: /usr/bin/certbot renew example.com
  - month: '*"
  - minute: '1'
  - hour: '1'
  - dayweek: '1'
  - identifier: letsencrypt-example.com
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
          ioflo: 1.7.1
         Jinja2: 2.10
        libgit2: 0.27.4
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.19
       pycrypto: 3.7.0
   pycryptodome: 3.6.6
         pygit2: 0.27.2
         Python: 2.7.15 (default, Jun 27 2018, 13:05:28)
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 5.1.1
            ZMQ: 4.2.5
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.14.78-1-lts
         system: Linux
        version: Not Installed
```
