### ISSUE TITLE
non-lowercase files never being kept with clean: True in file.py

### ISSUE THREAD

**Issue by basseed** [saltstack/salt#50331]
### Description of Issue/Question
Hi there, I was trying to use the "clean" option with file.recurse and it would always remove the files in the source after copying them. In the end i found that it has to do with how the list of files to keep is handled in the states/files.py code, specifically in the function **_find_keep_files**:

```       
        for fn_ in keep:
            if not os.path.isabs(fn_):
                continue
            fn_ = os.path.normcase(os.path.abspath(fn_))
```
not sure if os.normcase is being used to convert backslashes to forward slashes, but it's turning the path to lowercase, this is a problem when the function is used in **_clean_dir** calling **_delete_not_kept**:

```
real_keep = _find_keep_files(root, keep)

    for roots, dirs, files in os.walk(root):
        for name in itertools.chain(dirs, files):
            _delete_not_kept(os.path.join(roots, name))
    return list(removed)

```
as the files returned by os.walk that have uppercase characters are never going to match here:

```
        if nfn not in real_keep:
```
and will be deleted every time.

A possible solution would be in **_find_keep_files** to use normpath rather than normcase, as it will achieve the same without converting the case, although it also will collapse redundant separators, don't think that should be a problem?:

```
def _find_keep_files(root, keep):
    '''
    Compile a list of valid keep files (and directories).
    '''
    real_keep = set()
    real_keep.add(root)
    if isinstance(keep, list):
        for fn_ in keep:
            if not os.path.isabs(fn_):
                continue
            # fn_ = os.path.normcase(os.path.abspath(fn_))
            fn_ = os.path.normpath(os.path.abspath(fn_))
            real_keep.add(fn_)
            while True:
                fn_ = os.path.abspath(os.path.dirname(fn_))
                real_keep.add(fn_)
                drive, path = os.path.splitdrive(fn_)
                if not path.lstrip(os.sep):
                    break
    return real_keep


```

This is on version 2017.7.7 but I checked the code in the latest 2018 and looks the same.

**Comment by garethgreenaway** [comment]
@basseed Thanks for the report.  Can you provide the output from `salt --versions-report`.

**Comment by basseed** [comment]
```
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```
