### ISSUE TITLE
New use_superseded option needs added to configuration documentation

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#50348]
### Description of Issue/Question
The newish `use_superseded` option is not mentioned in either the [master config documentation](https://docs.saltstack.com/en/latest/ref/configuration/master.html) or the [minion config documentation](https://docs.saltstack.com/en/latest/ref/configuration/master.html].

### Versions Report
This is in the latest version of the docs.

**Comment by doesitblend** [comment]
This issue may be related to #44882

**Comment by doesitblend** [comment]
ZD-2936

**Comment by rallytime** [comment]
@isbm I think `use_superseded` was your addition. Would you be willing to add documentation for this?

**Comment by devurandom** [comment]
While you are at it, could you please also add documentation on how to set `use_superseded` for `salt-ssh`?

**Comment by mattayes** [comment]
_bump_

**Comment by cr1st1p** [comment]
See also #53504 : Keeping old behavior always on needs to happen, or somehow solve situation with mixed style (think 3rd party saltstack formulas)
And when that kind of situation is solved, document it.

**Comment by max-arnold** [comment]
For `salt-ssh` the trick is to use the following config option:

```yaml
# /etc/salt/master.d/ssh.conf
ssh_minion_opts:
  use_superseded:
    - module.run
```

The same can be done in a roster file through the `minion_opts` option:

```yaml
MINION:
  host: minion.example.com
  minion_opts:
    use_superseded:
      - module.run
```
