### ISSUE TITLE
git_pillar mountpoint ignores the root parameter

### ISSUE THREAD

**Issue by sathieu** [saltstack/salt#50364]
### Setup
Consider the following master config:
```yaml
ext_pillar:
  - git:
    - master https://mydomain.tld/top.git:
      - root: pillar
      - mountpoint: ''
    - master https://mydomain.tld/myapp1.git:
      - root: pillar/myapp1
      - mountpoint: myapp1
    - master https://mydomain.tld/myapp2.git:
      - root: pillar/myapp2
      - mountpoint: myapp2
```

### Steps to Reproduce Issue
The `root` parameter is ignored.

Longer story: I want all my git repos to be virtually relative to `/srv`. The `top.git` repo only contains `pillar/top.sls` which loads the proper "app" pillar corresponding to the minion id. This prevents an app repo to inject pillar data to minions of another app (each app repo can have different commiters).

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
