### ISSUE TITLE
Configuration for external_auth malformed for eauth 'pam', and user 'salt'

### ISSUE THREAD

**Issue by bjorntheart** [saltstack/salt#50391]
### Description of Issue/Question

Two things that is really odd to me:

1. The following message in the salt-api debug logs `Configuration for external_auth malformed for eauth 'pam'`
2. `perms: {}` is always returns with no permissions in the `/login` response

### Setup
**restcherry_py.conf**
```
rest_cherrypy:
  debug: True
  port: 5555
  disable_ssl: True
  webhook_disable_auth: True
  webhook_url: /hook
```

**Salt master `external_auth` config**
```
external_auth:
  pam:
    salt:
      - *
      - '@runner'
      - '@wheel'
      - '@jobs'
```

```
curl -sSi http://localhost:5555/login \
    -c ~/cookies.txt \
    -H 'Accept: application/x-yaml' \
    -d username=salt \
    -d password=secret \
    -d eauth=pam
```

**Curl command output**
```
HTTP/1.1 200 OK
Content-Length: 151
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.5.0
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Tue, 06 Nov 2018 12:40:35 GMT
Access-Control-Allow-Origin: *
X-Auth-Token: 519d34d223b39bf2015a478e8ee9cc3072e64c30
Content-Type: application/x-yaml
Set-Cookie: session_id=519d34d223b39bf2015a478e8ee9cc3072e64c30; expires=Tue, 06 Nov 2018 22:40:35 GMT; Path=/

return:
- eauth: pam
  expire: 1541551237.458198
  perms: {}
  start: 1541508037.458196
  token: 519d34d223b39bf2015a478e8ee9cc3072e64c30
  user: salt
```

### Steps to Reproduce Issue

`salt-master --log-level=debug`
`salt-api --log-level=debug`

**salt-api Debug log**
```
[INFO    ] [api_acl] Authentication not checked for user salt from IP 127.0.0.1
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'saltmaster.local_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[06/Nov/2018:12:35:09] ENGINE Started monitor thread 'Session cleanup'.
[INFO    ] [06/Nov/2018:12:35:09] ENGINE Started monitor thread 'Session cleanup'.
[DEBUG   ] Configuration for external_auth malformed for eauth 'pam', and user 'salt'.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1885, in POST
    perms.extend(eauth.get('*', []))
AttributeError: 'unicode' object has no attribute 'extend'
127.0.0.1 - - [06/Nov/2018:12:35:09] "POST /login HTTP/1.1" 200 151 "" "curl/7.47.0"
[INFO    ] 127.0.0.1 - - [06/Nov/2018:12:35:09] "POST /login HTTP/1.1" 200 151 "" "curl/7.47.0"
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by garethgreenaway** [comment]
@bjorntheart Thanks for the report.  If you update your external_auth configuration to the following that should take care of one of the issues:
```
external_auth:
  pam:
    salt:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'
```
As far as the `perms` value always being blank, your configuration is allowing access to all functions in all modules.  The runner and wheel functions don't show up in `perms` because they are handled differently.
