### ISSUE TITLE
boto_vpc, unable to create inter-region peering

### ISSUE THREAD

**Issue by julientravelaer** [saltstack/salt#50394]
### Description of Issue/Question
Hi all,

It's not possible to create an AWS peering connection between different region under the same account.

I looked at the code of **salt-2018.3.3/salt/modules/boto_vpc.py** and the region can't be passed to the **request_vpc_peering_connection** method, which call the **conn.create_vpc_peering_connection** method of boto3.

Is it possible to add the parameter to all peering methods on module and state ?
Thx ! =)

### Setup
- Create a VPC under region us-east-1
- Create a VPC under region us-east-2

### Steps to Reproduce Issue
- Try to peer them:

```
vpc_peering_{{name}}:
  boto_vpc.vpc_peering_connection_present:
    - requester_vpc_name: {{vpc_name_east_1}}
    - peer_vpc_id: {{vpc_id_east_2}}
    - conn_name: {{peering_name}}
    - profile: {{peering_profile}}
```
It will end with this error message in AWS console: "Failed due to incorrect VPC-ID, Account ID, or overlapping CIDR range"

### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: 1.10.6-a1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.2.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
