### ISSUE TITLE
Enable DigitalOcean Monitoring

### ISSUE THREAD

**Issue by gazzer82** [saltstack/salt#50430]
### Description of Issue/Question
I would like to enable DigitalOcean Monitoring during droplet creation, but it doesn't seem the option "monitoring" is supported at the moment, or it never gets passed to DigitalOcean.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Currently my profile looks like this.

```
base-dev:
  provider: do
  image: ubuntu-16-04-x64
  size: 1gb
  location: lon1
  private_networking: True
  ipv6: True
  monitoring: True

dev-docker:
  extends: base-dev
  minion:
    grains:
      role: docker
      env: dev
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Create a new droplet using the above setup, no monitoring agent will be installed

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-138-generic
         system: Linux
        version: Ubuntu 16.04 xenial
