### ISSUE TITLE
Use State Staza kwarg '_stanza_meta' for storing info like: docstring, et al

### ISSUE THREAD

**Issue by nickgarber** [saltstack/salt#50458]
### Description of Issue/Question
This is a discussion/consensus request to identify a means to safely add additional info to a state stanza.

My immediate use-case is to make my stanzas more self-documenting, more context-rich, and ideally easier to follow and improve by other state authors. 

Supplemental to that I'd like to use this embedded information in downstream tooling to automatically produce visualizations and documentation as part of a CI workflow.

The argument I'm using now is '_stanza_meta', for example:
```
# install the vendor repo
"setup_pkgrepo_for_upstream_mariadb":
  pkgrepo.managed:
    - name: MariaDB
    - humanname: MariaDB {{ var_dct.db_version }} for CentOS v7
    - gpgcheck: 1
    - baseurl: http://yum.mariadb.org/{{ var_dct.db_version }}/centos7-amd64
    - gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    - _stanza_meta:
        docstring: |-
            Ensure the MariaDB project's upstream software repo is available on this system.
        design_docs:
          - https://wiki.some-wiki.com/rule-4080
        related_req_uris:
          - req1004: https://jira.myorg.org/browse/req-1004
        origination: https://jira.myorg.org/browse/sr-101
        applicability:
          tgtspec: G@os_family:RedHat and G@osmajorrelease:7*
        assumptions:
          - <document assumptions>
        test_suite: None
        warnings:
          idempotent: true
          cancellable: true
          todo: []
```

This example is intentionally verbose to demonstrate a range of usefulness.

The `_stanza_meta` kwarg seems very unlikely to be used anywhere else, and as a dictionary type, it'll be safe and easy to use for a variety of purposes.

OK to reserve the `_stanza_meta` kwarg for this sort of use?

Cheers!
