### ISSUE TITLE
How to append string with the new __slot__ syntax?

### ISSUE THREAD

**Issue by UniIsland** [saltstack/salt#50462]
### Description of Issue/Question

The `__slot__` syntax #44866 is great. But can we manipulate the string returned, or append another string to it?

I tried the following states syntax. Neither of them works.

```
tmpfile:
  file.managed:
    - name: __slot__:salt:cmd.run('gem env gemdir') ~ `/cache/tmp`
    - contents: example content
```

```
tmpfile:
  file.managed:
    - name: __slot__:salt:cmd.run('gem env gemdir')/cache/tmp
    - contents: example content
```

After reading the source code [salt/state.py#2054](https://github.com/saltstack/salt/pull/44866/files#diff-e5cf22153489a6c40864babf3ca18002R2054), I guess anything after the `)` is ignored.

Is there a way to append sth to the `__slot__` part and use the result in the states file? 

### Versions Report
salt-minion 2018.3.3 (Oxygen)
