### ISSUE TITLE
reg.present does not return changes with new and old and should use comments

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#50465]
### Setup
Use reg.present state.
Returns non-standard `changes`.  Should put feed back in `comments` instead of changes.

### Steps to Reproduce Issue
Change a registry value using reg.present

e.g.
```
          ID: HKEY_USERS\\.DEFAULT\\SOFTWARE\\Clients\\mail
    Function: reg.present
      Result: None
     Comment:
     Started: 00:11:09.029338
    Duration: 0.999 ms
     Changes:
              ----------
              reg:
                  ----------
                  Will add:
                      ----------
                      Entry:
                          (Default)
                      Key:
                          HKEY_USERS\\.DEFAULT\\SOFTWARE\\Clients\\mail
                      Value:
                          A Mail Client
```
should look like this as a module output
```
    HKEY_USERS\\.DEFAULT\\SOFTWARE\\Clients\\mail:
        ----------
        new:
            vname:
                 (Default)
            vtype: 
                 REG_SZ
            vdata:
                 A Mail Client
        old:
```
Then the reg.present should look like this with the use of `comment`
```
          ID: HKEY_USERS\\.DEFAULT\\SOFTWARE\\Clients\\mail
    Function: reg.present
      Result: None
     Comment: add missing values
     Started: 00:11:09.029338
    Duration: 0.999 ms
     Changes:
              ----------
              new:
                  vname:
                       (Default)
                  vtype: 
                       REG_SZ
                  vdata:
                       A Mail Client
              old:
```

### Versions Report
All recent versions
