### ISSUE TITLE
What does state selinux.fcontext_policy_applied actually do?

### ISSUE THREAD

**Issue by craigafinch** [saltstack/salt#50488]
### Description of Issue/Question

I am using states `selinux.fcontext_policy_present` and `selinux.fcontext_policy_applied` to set a custom context for files. The purpose of `selinux.fcontext_policy_present` is clear; this state:

```
ossec-logrotate-selinux-policy:
  selinux.fcontext_policy_present:
    - name: "/var/ossec/logs(/.*)?"
    - sel_type: "var_log_t"
```

is equivalent to this command:

```
semanage fcontext -a -t var_log_t "/var/ossec/logs(/.*)?"
```

However, the documentation does not clearly explain what `selinux.fcontext_policy_applied` does.  I expected that this state:

```
ossec-logrotate-selinux:
  selinux.fcontext_policy_applied:
    - name: "^/var/ossec/logs(/.*)?"
    - require:
      - ossec-logrotate-selinux-policy
```
when used in conjunction with the previous state, would be equivalent to running:

```
restorecon -R /var/ossec/logs/
```
However, that's not the case. The context was not changed when I ran that state, and I had to run `restorecon` for the custom context to be applied. Am I misunderstanding the function of `selinux.fcontext_policy_applied` or is it not working correctly? I am not sure if this is a state bug or a documentation bug.

### Setup

```
ossec-logrotate-selinux-policy:
  selinux.fcontext_policy_present:
    - name: "/var/ossec/logs(/.*)?"
    - sel_type: "var_log_t"

ossec-logrotate-selinux:
  selinux.fcontext_policy_applied:
    - name: "/var/ossec/logs(/.*)?"
    - recursive: True
    - require:
      - ossec-logrotate-selinux-policy
```

### Steps to Reproduce Issue

1. Apply states to server with default file contexts
2. States apply successfully:
```
----------
          ID: ossec-logrotate-selinux-policy
    Function: selinux.fcontext_policy_present
        Name: /var/ossec/logs(/.*)?
      Result: True
     Comment:
     Started: 03:23:34.894581
    Duration: 3476.284 ms
     Changes:
              ----------
              new:
                  ----------
                  /var/ossec/logs(/.*)?:
                      ----------
                      filetype:
                          all files
                      sel_type:
                          var_log_t
              old:
                  ----------
----------
          ID: ossec-logrotate-selinux
    Function: selinux.fcontext_policy_applied
        Name: /var/ossec/logs(/.*)?
      Result: True
     Comment: SElinux policies are already applied for filespec "/var/ossec/logs(/.*)?"
     Started: 03:23:38.373019
    Duration: 33.37 ms
     Changes:
----------
```
3. Check applied file contexts:
```
# ls -lZ /var/ossec/logs/
-rw-rw-r--. ossec ossec system_u:object_r:var_t:s0       ossec.log
```
4. Run restorecon manually (or with state cmd.run)
```
# restorecon -R /var/ossec/logs/
```
5. Check contexts:
```
ls -lZ /var/ossec/logs/
-rw-rw-r--. ossec ossec system_u:object_r:var_log_t:s0   ossec.log
```

### Versions Report

```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
