### ISSUE TITLE
False negative error when install .net sdk

### ISSUE THREAD

**Issue by damianw2** [saltstack/salt#50490]
### Description of Issue/Question
When apply salt state file to install .net core sdk, package is intall properly but error output appear.

### Setup
**pkg file:**
----------

```
dotnet-sdk:
  '2.1.403':
    full_name: 'Microsoft .NET core SDK - 2.1.403'
    installer: 'https://download.visualstudio.microsoft.com/download/pr/7010cdb4-ae43-408b-8c9f-5f94101a1c70/3e1ae56a072c7c397f10278d7643b3e9/dotnet-sdk-2.1.403-win-gs-x64.exe'
    install_flags: '/quiet /norestart'
    uninstaller: 'https://download.visualstudio.microsoft.com/download/pr/7010cdb4-ae43-408b-8c9f-5f94101a1c70/3e1ae56a072c7c397f10278d7643b3e9/dotnet-sdk-2.1.403-win-gs-x64.exe'
    uninstall_flags: '/uninstall /quiet /norestart'
    msiexec: False
    locale: en_US
    reboot: False
```

**state file:**
----------

```
install_prerequisites:
  pkg.installed:
    -
      pkgs:
        - dotnet-sdk
```

**output:**
----------

```
          ID: install_prerequisites
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: dotnet-sdk
     Started: 10:29:07.390412
    Duration: 139652.537 ms
     Changes:
              ----------
              dotnet-sdk:
                  ----------
                  install status:
                      success
```

### Versions Report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1030-azure
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any ideas here?

**Comment by twangboy** [comment]
@damianw2 There were a couple things wrong
- The `full_name` must match exactly what appears in the `add/remove programs`, including capitalization. Here are the two items side by side:
```
Microsoft .NET core SDK - 2.1.403 (wrong)
Microsoft .NET Core SDK 2.1.403 (x64) (correct)
```
- This particular installer puts 2 different versions in different parts of the registry. In the 64 bit area the display version is `2.1.403`.  In the wow6432 area the version is `8.116.58436`. I noticed this when I fixed the `full_name` parameter. Salt was returning a comma-delimited list with 2 versions instead of the single version I was expecting. So, to fix this I added a second identical entry, only changing the new version. This may be something we need to account for in Salt.

Here is the complete .sls file that is working for me:
```
dotnet-sdk:
  '2.1.403':
    full_name: 'Microsoft .NET Core SDK 2.1.403 (x64)'
    installer: 'https://download.visualstudio.microsoft.com/download/pr/7010cdb4-ae43-408b-8c9f-5f94101a1c70/3e1ae56a072c7c397f10278d7643b3e9/dotnet-sdk-2.1.403-win-gs-x64.exe'
    install_flags: '/quiet /norestart'
    uninstaller: 'https://download.visualstudio.microsoft.com/download/pr/7010cdb4-ae43-408b-8c9f-5f94101a1c70/3e1ae56a072c7c397f10278d7643b3e9/dotnet-sdk-2.1.403-win-gs-x64.exe'
    uninstall_flags: '/uninstall /quiet /norestart'
    msiexec: False
    locale: en_US
    reboot: False
  '8.116.58436':
    full_name: 'Microsoft .NET Core SDK 2.1.403 (x64)'
    installer: 'https://download.visualstudio.microsoft.com/download/pr/7010cdb4-ae43-408b-8c9f-5f94101a1c70/3e1ae56a072c7c397f10278d7643b3e9/dotnet-sdk-2.1.403-win-gs-x64.exe'
    install_flags: '/quiet /norestart'
    uninstaller: 'https://download.visualstudio.microsoft.com/download/pr/7010cdb4-ae43-408b-8c9f-5f94101a1c70/3e1ae56a072c7c397f10278d7643b3e9/dotnet-sdk-2.1.403-win-gs-x64.exe'
    uninstall_flags: '/uninstall /quiet /norestart'
    msiexec: False
    locale: en_US
    reboot: False
```
