### ISSUE TITLE
Add unless/ifonly params to module.run/wait + more granular unless/ifonly result evluation

### ISSUE THREAD

**Issue by ryba-xek** [saltstack/salt#5050]
> NOTE (added by @basepi): All states now support `unless` and `onlyif`, this issue is still open for the additional request for more power in these statements than just `cmd.retcode`.

Salt state scripting will be _much_ more useful if one can use `module.run/wait` states with `unless` and `ifonly` params.

The whole idea of salt is the aim _not_ to use console commands in state.
So, the whole internal command stack was developed — called modules.
But why `cmd.run/wait` have `unless/ifonly` and `module.run/wait` doesn't?..

The second idea is to somehow to be able to control what `unless/ifonly` module commands are considered having positive result.

I mean for example I want smth like this:

```
debconf.set:
    module.run:
    - package: mysql-server-5.5
    - question: 'mysql-server/root_password'
    - type: 'password'
    - value: {{pillar['mysql.pass']}}
    - unless:
        command: pkg.version   
            - names:
                - mysql-server-5.5
```

Here `pkg.version` command returns empty string if not installed, this should be considered `False`. Any non-empty result should be string.

I will be happy if I will be ablo to use more complex logic like
`- unless: pkg.available_version mysql-server < 5.5`
