### ISSUE TITLE
ini.options_present separator add extra whitespaces (and pkgrepo is not viable to manage yum)

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#50536]
Hi,

When using ini.options_present with a defined separator, salt add extra whitespace around the separator.

If I apply this code, all the parameters of the file are converted from `key=value` to `key = value`
Also I do this because, it is not possible with pkgrepo to only disable an existant repo, you have to set all the parameters and you can't manage a yum repo configuration file with multiple entries (one file, one entry); so when the centos-release package is updated all the entries are recreated; so the only way I've found to have something not dirty when using a local YUM mirror, is to disable all the default repository and to manage each entry of the local mirror via pkgrepo.

```
yum_disable_centos_base_repo:
  ini.options_present:
    - name: /etc/yum.repos.d/CentOS-Base.repo
    - separator: '='
    - sections:
        base:
          enabled: 0
        updates:
          enabled: 0
        extras:
          enabled: 0
        centosplus:
          enabled: 0

CentOS-Base:
  pkgrepo.managed:
    - humanname: 'CentOS-$releasever - Base'
    - name: local-base
    - baseurl: 'https://repos.local/pulp/repos/centos/7/os/$basearch/'
    - enabled: 1
    - proxy: _none_

CentOS-Updates:
  pkgrepo.managed:
    - humanname: 'CentOS-$releasever - Updates'
    - name: local-updates
    - baseurl: 'https://repos.local/pulp/repos/centos/7/updates/$basearch/'
    - enabled: 1
    - proxy: _none_

CentOS-Extras:
  pkgrepo.managed:
    - humanname: 'CentOS-$releasever - Extras'
    - name: local-extras
    - baseurl: 'https://repos.local/pulp/repos/centos/7/extras/$basearch/'
    - enabled: 1
    - proxy: _none_
```
