### ISSUE TITLE
Can salttutil.sync_grains have an effect in the same sls file? 

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#50533]
### Description

I would like to refresh a grain and read the refreshed value in the same sls file.

### Setup
Given custom grain /srv/salt/_grain/mygrain.py:

```
def go():
    g = {}
    g['mygrain'] = 'old'
    return g
  
```
and state /srv/salt/mystate.sls: 

```
try_to_get_new_grains:
  module.run:
    - name: saltutil.sync_grains
    - refresh: True  

this_is_my_state:
  cmd.run:
    - name: echo mygrain is {{grains['mygrain']}}
 
```
On the minion execute:
```
salt-call state.sls mystate
```
which returns

```
local:
----------
          ID: try_to_get_new_grains
    Function: module.run
        Name: saltutil.sync_grains
      Result: True
     Comment: Module function saltutil.sync_grains executed
     Started: 18:37:15.151000
    Duration: 429.0 ms
     Changes:
              ----------
              ret:
----------
          ID: this_is_my_state
    Function: cmd.run
        Name: echo mygrain is old
      Result: True
     Comment: Command "echo mygrain is old" run
     Started: 18:37:15.581000
    Duration: 25.0 ms
     Changes:
              ----------
              pid:
                  7688
              retcode:
                  0
              stderr:
              stdout:
                  mygrain is old

Summary for local
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time: 454.000 ms


```

When you change the value of mygrain to "new" on the Master and repeat the command twice on the minion, you first get "old", and then "new". 

This means, the sls file continues with the old grain values. 

Only if the state is called again, the new grain values are read.

### Question

Is it possible (or intended) to refresh grains and read them in the same sls file?

### Versions Report 

Salt Master: 2018.3.2

Salt Minion: 2018.3.2

**Comment by markuskramerIgitt** [comment]
I see no effect of `reload_grains: True`

I understand the second issue of asynchronous operation.

How can I force `sync_grains` to be synchronous?

Edited /srv/salt/mystate.sls: 

```
try_to_get_new_grains:
  module.run:
    - name: saltutil.sync_grains
    - reload_grains: True  
    - async: False

this_is_my_state:
  cmd.run:
    - name: echo mygrain is {{grains['mygrain']}}
 
```

Same (unsatisfactory) behaviour as above.

I also get `[WARNING] The function "module.run" is using its deprecated version and will expire in version "Sodium". `


How can I force the two states into order?

Edited /srv/salt/mystate.sls: 

```
try_to_get_new_grains:
  module.run:
    - name: saltutil.sync_grains
    - reload_grains: True  

this_is_my_state:
  cmd.wait:
    - name: echo mygrain is {{grains['mygrain']}}
    - watch:
      - module:  try_to_get_new_grains
 
```
Same (unsatisfactory) behaviour and warning as above

**Comment by markuskramerIgitt** [comment]
Let me repeat: Jinja renders the sls file, therefore, {{grains['mygrain']}} is the grain value at rendering time, which comes before execution of the rendered sls state file.

How can I read a grain (without Jinja) at execution time?
I have the impression that Jinja is the only way to access a grain.

Only if I can read a grain at execution time, I could make use of refresh: True and reload_grains: True,

**Comment by Ch3LL** [comment]
can you explain your use case a bit more. One thing I would recommend is using  salts orchestration. you can have one state run the sync_grains and then the next call a state file which has the grains call there, since this state will be rendered after syncing the grains:


```
saltutil.sync_grains:
  salt.function:
    - tgt: '*'

run-state:
  salt.state:
    - tgt: 'web*'
    - sls:
      - state
```

to note i have not tested the above state. If you explain what exactly you are trying to accomplish with grains I might be able to recommend a better approach.

**Comment by markuskramerIgitt** [comment]
If Jinja is the only way to read variables, variables are immutable in an sls file and, by design, a changed variable value cannot be used in the same sls file.
What is the purpose of the sync_grain refresh option then? 

Our use case is to compare a 'version' grain with its pillar counterpart.
The salt-master updates the 'version' pillar.

The Minions must regularly
 - sync (retrieve the latest 'version' pillar  and compile their local 'version' grain).
 - if 'version' grain and pillar differ:
    - make a system call, which ends with the input for the 'version' grain equal to the pillar.

I was hoping that I could do sync and system call in a single sls file.
I tried orchestration years ago without success and need to read the basics again (on Thursday)
Is there no "easier" (TM) way?

As an alternative, I could stop using grain and pillar and instead use managed files, though this is not a finished concept.

**Comment by markuskramerIgitt** [comment]
I read in [the Orchestration docs](https://docs.saltstack.com/en/latest/topics/orchestrate/index.html):
 - An Orchestration is running on the Master
 - is intended to  "configure a set of minions all at once", 

So an Orchestrator runner can first fire a sync_all state on a Minion and then fire any other state., .

This is good to know, but this means network traffic only to bring two minion states in order and network bandwidth is my most valuable resource. 

Is there an alternative to call two states on a minion, the second after the first finished, without traveling to the master?

Or, is there an option to sync_all before a state is rendered by Jinja?

**Comment by markuskramerIgitt** [comment]
I made another attempt to sync_grain and read the value.

```
try_to_get_new_grains:
  module.run:
    - name: saltutil.sync_grains
    - reload_grains: True  
    - refresh: True  
    - async: False

{% set mygrain2 = grains['mygrain'] %}

read_the_grain:
  cmd.run:
    - name: echo mygrain2 is {{  mygrain2 }}
 
```
Same (unsatisfactory) behaviour and warning as above (I get the synced grain only the **second** time).

How, please, do I use refresh and reload_grains in saltutil.sync_grains?

**Comment by markuskramerIgitt** [comment]
A minion performs sync_all and sends an event to the master, which should trigger another state back on the minion.


```
load_my_custom_module_grains_and_pillars:
  module.run:
    - name: saltutil.sync_all

minion_is_ready_to_start_the_comment_line:
  event.send:
    - name: minion_is_ready_to_start
    - data:
        id: {{grains['localhost']}}

```

Why do the id is undefined?

```

 [salt.utils.reactor:101 ][ERROR   ][5843] Failed to render "/srv/salt/reactor/minion_is_ready_to_start_reactor.sls":
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/reactor.py", line 92, in render_reaction
    data=data)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 383, in render_template
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 93, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/jinja.py", line 70, in render
    **kws)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 170, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 403, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'id' is undefined

```


When I do


salt-run state.event pretty=True

I can see the id (even 2)
```

minion_is_ready_to_start        {
    "_stamp": "2018-11-22T17:34:33.366113",
    "cmd": "_minion_event",
    "data": {
        "id": "DEBONWN5676992"
    },
    "id": "DEBONWN5676992",
    "pretag": null,
    "tag": "minion_is_ready_to_start"
}

```

**Comment by markuskramerIgitt** [comment]
I use an a workaround with two sls files.


Sls file 1:
Refreshes the grains with saltutil.sync_all
Sends an event with the name "call sls file 2"


Sls file 2:

Reads the grains


Is there in interest in the question?

**Comment by Ch3LL** [comment]
other solutions would be to use a different renderer, such as the py renderer. And then you can just use python to call the refresh of the grains and then get the grains.item call on the next call. 

another possible solution would be to somehow implement slots: https://docs.saltstack.com/en/latest/topics/slots/index.html

this is a new feature addd in 2018.3. It allows  "you to do things right before the state function is executed" so its rendered right before the state function is run. 

But the solution i think is **best** and most simple for your use case is to just use the grains  module to check if it equals what you are expecting it to be like so:

```
[root@6e0f33fdd95b /]# cat /srv/salt/mystate.sls
try_to_get_new_grains:
  module.run:
    - name: saltutil.sync_grains
    - refresh: True  
    - reload_grains: True

fetch_grain:
  module.run:
    - name: grains.equals
    - key: mygrain
    - value: new
```

I tested this and it works. can you verify? and also verify this works for your use case

**Comment by markuskramerIgitt** [comment]
`grains.equals` -- wonderful!

I will test earliest tomorrow.

**Comment by markuskramerIgitt** [comment]
The code of your works.
This proves that the grain is updated in the sls file.

I cannot use `grains.equals` because I need to read the value, but I use the workaround  described above and therefore close this question.

**Comment by jakehilton** [comment]
> I use a workaround with two sls files.
> 
> Sls file 1:
> 
> * Refreshes the grains with saltutil.sync_all
> * Sends an event with the name "call sls file 2"
> 
> Sls file 2:
> 
> * Reads the grains
> 
> Is there a public interest in this question?

@markuskramerIgitt 
I'd be interested in knowing what your solution. Do you have some code snippets. The saltstack proper documentation is lacking when trying to do a simple event send and running an operation based off of that event.

Thanks!

**Comment by markuskramerIgitt** [comment]
@jakehilton, I still work on my solution. 
I no longer use grains or sls files, instead I use a runner (a Python script that runs on the master).
You can configure a runner  to react to an event like this.

In reactor.conf:
```
reactor:
  - `salt/job/*/ret/*`:
    - /srv/salt/reactor/jobs_reactor.sls
```

in jobs_reactor.sls
```
jobs_reaction:
  runner.jobs_runner.main:
    - arg:
      - {{ data }}
```
in  jobs_runner.py:
```
def main(*event_data):
    try:
        minion = event_data[0][`id`]
        fun_name = event_data[0][`fun`]
        fun_return = event_data[0][`return`]
```
