### ISSUE TITLE
Slot is not expanded in module.run and scheduled job

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#50596]
### Description of Issue/Question

It looks like slots are not expanded consistently across all the cases where a state could be applied by Salt.

### Steps to Reproduce Issue

This state:

```
test_run:
  module.run:
    - test.arg:
        - message: __slot__:salt:cmd.run('echo "blah"')
```

results in the following output (note that slot is not expanded):

```
local:
----------
          ID: test_run
    Function: module.run
      Result: True
     Comment: test.arg: Success
     Started: 18:24:03.703510
    Duration: 27.757 ms
     Changes:
              ----------
              test.arg:
                  ----------
                  args:
                  kwargs:
                      ----------
                      message:
                          __slot__:salt:cmd.run('echo "blah"')
```

Also slots do not work as scheduler arguments:

```
scheduled_slot:
  schedule.present:
    - function: test.arg
    - job_args:
        - __slot__:salt:cmd.run('echo "blah"')
    - cron: '* * * * *'
```

```
scheduled_slot:
  schedule.present:
    - function: test.arg
    - job_kwargs:
        - message: __slot__:salt:cmd.run('echo "blah"')
    - cron: '* * * * *'
```

(the last one fails with `UnboundLocalError: local variable 'data_returner' referenced before assignment`) 

The only case where slots did work for me is this:

```
test_state:
  test.configurable_test_state:
    - comment: __slot__:salt:cmd.run('echo "blah"')
```

```
local:
----------
          ID: test_state
    Function: test.configurable_test_state
      Result: True
     Comment: blah
     Started: 18:23:44.081436
    Duration: 8.481 ms
     Changes:
              ----------
              testing:
                  ----------
                  new:
                      Something pretended to change
                  old:
                      Unchanged
```

### Versions Report

2018.3.3

**Comment by Ch3LL** [comment]
ping @DmitryKuzmenko can you comment here? Would you expect these use cases to work with the current implementation of slots or does it simply need to be added?

**Comment by max-arnold** [comment]
I just discovered that #52351 is merged, thanks @mchugh19!  Below are quick tests to confirm the fix:

#### 1. Slots in `module.run`

```
test_run:
  module.run:
    - test.arg:
        - message: __slot__:salt:cmd.run('echo "blah"')
```

Works as expected:

```
----------
          ID: test_run
    Function: module.run
      Result: True
     Comment: test.arg: Success
     Started: 15:36:26.468761
    Duration: 30.0000000061 ms
     Changes:
              ----------
              test.arg:
                  ----------
                  args:
                      - blah
                  kwargs:
                      ----------
----------
```


#### 2. Slots in scheduled jobs

```
scheduled_slot:
  schedule.present:
    - function: test.arg
    - job_args:
        - __slot__:salt:cmd.run('echo "blah"')
    - cron: '* * * * *'
```

Strictly speaking, slot does work here but not as expected:

```
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false, run_on_start: true}
  scheduled_slot:
    args: [blah]
    cron: '* * * * *'
    enabled: true
    function: test.arg
    jid_include: true
    maxrunning: 1
    name: scheduled_slot
```

The expectation was that the schedule should look like this:

```
  scheduled_slot:
    args:
      - __slot__:salt:cmd.run('echo "blah"')
    cron: '* * * * *'
```

and the slot should be evaluated when the scheduled function is being run.

Now I understand why it works this way and I think this behavior is also useful.

It is probably possible to invent a way to prevent the scheduled slot from being evaluated at state compilation time, pass it as is to the scheduler and then teach the scheduler to expand it at run time. But I think it is better to create a separate issue for this use-case.
