### ISSUE TITLE
supervisord.dead is not idempotent

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#50601]
### Description of Issue/Question
I noticed that supervisord.dead is not idempotent and will produce change on each run.

### Steps to Reproduce Issue
```
test.supervisord.dead:
  supervisord.dead:
    - name: literally-anything
```

Will produce this on each run:
```
          ID: test.supervisord.dead
    Function: supervisord.dead
        Name: literally-anything
      Result: True
     Comment: Stopping service: literally-anything
     Started: 14:03:04.320585
    Duration: 430.436 ms
     Changes:
              ----------
              literally-anything:
                  Stopping service: literally-anything
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
