### ISSUE TITLE
Pass serializer options through file.serialize

### ISSUE THREAD

**Issue by onlyanegg** [saltstack/salt#50609]
### Description of Issue/Question

It would be nice if `file.serialize` supported passing kwargs through to the serializer modules in case they support them.

For example:
```
some_file_serialized:
  file.serialize:
    - name: /path/to/file
    - dataset: {{ dataset }}
    - formatter: yaml
    - formatter_kwargs:
        arg1: val1
        arg2: val2
```
