### ISSUE TITLE
Salt request timed out. The master is not responding. While running orchestrate only

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#50621]
### Description of Issue/Question
I have few formulas which run just fine using the state.apply on 31 minions but fails to run in the orchestrate runner with 31 minions, yet works fine with 5 minions via orchestrate. 

So I assume the number of minions is affecting the result.

### Setup
**cat states/orch/hadoop.sls**
```
---
include:
  - .sync

install.java:
  salt.state:
    - tgt: '*'
    - sls:
      - formula.java

install.zookeeper:
  salt.state:
    - tgt: 'roles:zookeeper'
    - tgt_type: 'grain'
    - sls:
      - formula.zookeeper
    - require:
      - salt: install.java
```
**cat states/orch/sync.sls**
```
salt.mine.update:
  salt.function:
    - tgt: "*"
    - name: mine.update
    - order: 1

salt.sync.all:
  salt.function:
    - tgt: "*"
    - name: saltutil.sync_all
    - order: 1
```

**cat states/formula/java/install.sls**
```
{% from tpldir +"/map.jinja" import java %}
{% set common_user = pillar.get('common_user') %}
{% set archive_urls = pillar.get('archive_urls') %}

{% set release_dir = java.dirs.releases_root + "/" + java.version %}
{% do java.dirs.update({'release_dir': release_dir}) %}

{% for dir_name, dir_path in java.dirs.items() %}
formula.java.dir.{{ dir_name }}:
  file.directory:
    - name: {{ dir_path }}
    - user: {{ common_user.name }}
    - group: {{ common_user.group }}
    - mode: 775
    - makedirs: True
{% endfor %}

formula.java.extract_java:
  archive.extracted:
    - name: {{ java.dirs.release_dir }}
    - user: {{ common_user.name }}
    - group: {{ common_user.group }}
    - source: {{ archive_urls['java']['path'] }}/{{ archive_urls['java']['file'] }}
    - source_hash: {{ archive_urls['java']['path'] }}/{{ archive_urls['java']['file'] }}.md5
    - options: "--strip-components=1"
    - enforce_toplevel: False
    - trim_output: True
    - if_missing: {{ java.dirs.release_dir }}/bin/java
    - require:
        - file: formula.java.dir.release_dir

formula.java.create_symlink:
  file.symlink:
    - name: {{ java.app_current }}
    - target: {{ java.dirs.release_dir }}
    - require:
      - archive: formula.java.extract_java

formula.java.profile:
  file.managed:
    - name: "{{ java.dirs.home }}/.profile"
    - source: salt://{{ tpldir }}/templates/profile.j2
    - user: {{ common_user.name }}
    - group: {{ common_user.group }}
    - mode: 644
    - template: jinja
    - context:
        java: {{ java }}
```

`salt '*' state.apply formula.java` work just fine yet `salt-run state.orchestrate orch.hadoop` fails with the following error:

```
  Name: saltutil.sync_all - Function: salt.function - Result: Changed Started: - 11:57:21.709636 Duration: 1228.042 ms
----------
          ID: install.java
    Function: salt.state
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1913, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1898, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/saltmod.py", line 333, in state
                  cmd_ret = __salt__['saltutil.cmd'](tgt, fun, **cmd_kw)
                File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 1399, in cmd
                  client, tgt, fun, arg, timeout, tgt_type, ret, kwarg, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 1363, in _exec
                  for ret_comp in _cmd(**cmd_kwargs):
                File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 615, in cmd_batch
                  batch = salt.cli.batch.Batch(opts, eauth=eauth, quiet=True)
                File "/usr/lib/python2.7/site-packages/salt/cli/batch.py", line 39, in __init__
                  self.minions, self.ping_gen, self.down_minions = self.__gather_minions()
                File "/usr/lib/python2.7/site-packages/salt/cli/batch.py", line 66, in __gather_minions
                  for ret in ping_gen:
                File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 910, in cmd_iter
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 358, in run_job
                  raise SaltClientError(general_exception)
              SaltClientError: Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.
     Started: 11:57:22.938030
    Duration: 20685.77 ms
     Changes:
----------
          ID: install.zookeeper
    Function: salt.state
      Result: False
     Comment: One or more requisite failed: orch.hadoop.install.java
     Started: 11:57:43.625152
    Duration: 0.023 ms
     Changes:

Summary for delme-salt-rm.aws.internal_master
------------
Succeeded: 2 (changed=1)
Failed:    2
------------
Total states run:     4
Total run time:  22.798 s
```

### Steps to Reproduce Issue
I think it will be hard to reproduce but here is my state:
https://gist.github.com/Oloremo/c67d9fd877c55ff3b362936d09b1f050

I think it's somehow related to the `formula.java.extract_java` state which uses `archive.extract` to download and extract java from our storage. This operation could take some time, especially with big concurrency.

Please guide me how to provide needed details for this issue.

### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
