### ISSUE TITLE
Salt REST salt-ssh and orchestration

### ISSUE THREAD

**Issue by ClaudiuPID** [saltstack/salt#50636]
### Description of Issue/Question

Body used for REST call:
```
{
  "fun": "state.orchestrate",
  "kwarg": {
    "pillar": {
     Some pillar data here.
    }
  },
  "arg": "orch.test",
  "eauth": "pam",
  "tgt": "odakibd-61.apps",
  "username": "salt",
  "client": "ssh",
  "password": "***"
}
```
Response from salt api:
```
                "return": {
                    "outputter": "highstate",
                    "data": {
                        "odakibd-61.apps": [
                            "No matching sls found for 'orch.test' in env 'base'"
                        ]
                    },
                    "retcode": 1
                },
                "retcode": 1,
                "_stamp": "2018-11-26T12:48:04.191053",
                "fun": "state.orchestrate",
                "id": "odakibd-61.apps"
```

My orch.test looks like this:
```
{%- from 'settings/postgresql.jinja' import postgresql_target with context %}

update_roster:
  salt.state:
    - tgt: localhost
    - sls:
      - roster

deploy_postgresql:
  salt.state:
    - tgt: {{ postgresql_target }}
    - sls:
      - postgresql

```
Is it even possible to call the orchestrator through REST on a salt-ssh minion?
If so, what am I missing?

Calling the states through REST directly without orchestrator works without issues.
So this is clearly due to a wrong call or maybe wrong orchestrator.

### Steps to Reproduce Issue
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.6 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.6 
```
