### ISSUE TITLE
x509 module returns error on FIPS compliant server

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#50662]
### Description of Issue/Question
The x509 state module will return as follows when running on a FIPS compliant Ubuntu server:

```
          ID: request-default-cert
    Function: x509.certificate_managed
        Name: /etc/ssl/certs/default.crt
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1889, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1839, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/x509.py", line 500, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 1376, in create_certificate
                  'ca_server did not respond'
              SaltInvocationError: ca_server did not respond salt master must permit peers to call the sign_remote_certificate function.
     Started: 22:26:52.958575
    Duration: 12636.865 ms
     Changes: 
```

### Setup
Follow documentation on https://docs.saltstack.com/en/latest/ref/states/all/salt.states.x509.html#module-salt.states.x509 to setup the peer and run the state.

### Versions Report
Master versions
```
The salt-master version info: salt -V

Salt Version:
           Salt: 2017.7.8

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1006-fips
         system: Linux
        version: Ubuntu 16.04 xenial
```
Minion Versions
```
The salt minion: salt-minion --versions-report
Salt Version:
           Salt: 2017.7.8

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
  msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1006-fips
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by dwoz** [comment]
@doesitblend Thank you for reporting the issue. What does your peers config look like?

**Comment by doesitblend** [comment]
@dwoz Thanks for the update.

My peers are as follows:

```
peer:
  .*:
    - x509.sign_remote_certificate
```

**Comment by starlton-eb** [comment]
I'd like to provide some additional context related to this issue, which was generated on our behalf from an enterprise support ticket and much appreciated. We are using release 2017.7.8 and addressed this internally by applying essentially a configuration patch using salt states, which we bake into an AWS AMI:
```
base.security.cert.remove-md5-from-x509-module:
  file.replace:
    - name: /usr/lib/python2.7/dist-packages/salt/modules/x509.py
    - pattern: .*MD5 Finger Print.*
    - repl: '# removed MD5 line'
    - backup: .bak
 
base.security.cert.remove-md5-from-x509-state:
  file.replace:
    - name: /usr/lib/python2.7/dist-packages/salt/states/x509.py
    - pattern: .*MD5 Finger Print.*
    - repl: '# removed MD5 line'
    - backup: .bak
```
This removed the attempt to create MD5 finger print, which a FIPS server will not allow. Also, we had to adjust pattern lookup for generated keys to look for both PKCS1 and PKCS8 RSA formats when looking at generated keys because FIPS will use PKCS8 not PKCS1:
```
base.security.cert.remove-rca-from-block-pattern-from-x509-state:
  file.replace:
    - name: /usr/lib/python2.7/dist-packages/salt/states/x509.py
    - pattern: RSA PRIVATE KEY
    - repl: (?:RSA )?PRIVATE KEY
    - backup: .bak
```
Sorry for taking so long to update... been extremely busy and we were able to work past this but ideally this is something we can remove when upgrading to a future release.
