### ISSUE TITLE
salt doesn't support LXC 3.0+

### ISSUE THREAD

**Issue by mced** [saltstack/salt#50679]
### Description of Issue/Question
Creation of LXC with network_profile with LXC 3.0+ results to unusable containers.

_The problem is that salt doesn't support the new config keys supporting nic settings_: 
```
lxc.net.[i].type
lxc.net.[i].flags 
lxc.net.[i].link 
lxc.net.[i].mtu 
lxc.net.[i].name 
lxc.net.[i].hwaddr 
lxc.net.[i].ipv4.address 
lxc.net.[i].ipv4.gateway 
lxc.net.[i].ipv6.address 
lxc.net.[i].ipv6.gateway 
lxc.net.[i].script.up 
lxc.net.[i].script.down 
```

### Setup
salt/lxc.sls
```yaml
create-lxc-foo:
  lxc.present:
    - name:  foo
    - profile: ubuntu1804
    - network_profile: foo_network
```
pillar/profile.sls
```yaml
lxc.container_profile:
  ubuntu1804:
    template: download
    options:
      dist: ubuntu
      release: bionic
      arch: amd64
```
pillar/network.sls
```yaml
lxc.network_profile:
  foo_network:
    eth1:
      link: lxcbr0
      type: veth
      flags: up
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-139-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
After reading lxc module in `2018.3.3` and `develop` branches, I see that module only supports old keys.

**Comment by Ch3LL** [comment]
looks like we will need to get this added. Did you want to try to give it a go at a PR?

**Comment by lordcirth** [comment]
Do both syntaxes need to be supported for now? The new way was only introduced in LXC 2.1, in Sep 2017: https://discuss.linuxcontainers.org/t/lxc-2-1-has-been-released/487

**Comment by Ch3LL** [comment]
yeah i think it would be good to add some detection to see which version you are on

**Comment by skob** [comment]
as temporary workaround you can set empty network profile:
```
lxc.network_profile:
  default:
    eth0:
      disable: true
```
and use `/etc/lxc/default.conf` as network configurator

**Comment by lordcirth** [comment]
> as temporary workaround you can set empty network profile:
> 
> ```
> lxc.network_profile:
>   default:
>     eth0:
>       disable: true
> ```
> 
> and use `/etc/lxc/default.conf` as network configurator

Thanks skob! I will try that today.

**Comment by tech-ch1** [comment]
As a temporary workaround, you could also (but probably shouldn't) do:
`sed -i 's/lxc.network/lxc.net.0/g' /usr/lib/python*/dist-packages/salt/modules/lxc.py`

**Comment by lordcirth** [comment]
> as temporary workaround you can set empty network profile:
> 
> ```
> lxc.network_profile:
>   default:
>     eth0:
>       disable: true
> ```
> 
> and use `/etc/lxc/default.conf` as network configurator

So I finally got around to trying this, and it doesn't seem to work for me?
I have this .sls file in pillar, assigned to the lxc hosts:

```
# Work around Salt's lack of LXC 3.0+ support
# https://github.com/saltstack/salt/issues/50679#issuecomment-458072894
lxc.network_profile:
  default:
    eth0:
      disable: true
```

And 
`salt-run lxc.init mc-3015-nfsgateway-1804 host=mc-3015-201 template=salt-image` returns the same errors, most relevantly:

`parse.c: lxc_file_for_each_line_mmap: 142 Failed to parse config file "/tmp/tmppNKAFW" at line "lxc.network.type = veth"`

Am I missing something?

**Comment by lordcirth** [comment]
Ok, if I use network_profile=default, the container is created, but it has no eth0, even though /etc/lxc/default.conf does define net.0:

```
lxc.net.0.type = veth
lxc.net.0.link = lxcbr0
lxc.net.0.flags = up
lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx
```

@skob, what are you doing differently?

**Comment by skob** [comment]
```
 testzone-03:~# cat /etc/lxc/default.conf
lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx
lxc.start.auto = 1
lxc.net.0.type = veth
# lxc.net.0.link = lxcbr0
lxc.net.0.flags = up
```
```
saltstack-01:~# salt testzone-03 lxc.create container1 profile=default network_profile=default template=download options='{dist: ubuntu, release: xenial, arch: amd64}'
testzone-03:
    ----------
    result:
        True
    state:
        ----------
        new:
            stopped
        old:
            None
```
```
salt testzone-03 pillar.get lxc.network_profile
testzone-03:
    ----------
    default:
        ----------
        eth0:
            ----------
            disable:
                True
```
testzone-03:~# cat /var/lib/lxc/container1/config
...
lxc.uts.name = container1

# Network configuration
lxc.net.0.hwaddr = 00:16:3e:e4:6a:d5
lxc.net.0.type = veth
# lxc.net.0.link = lxcbr0
lxc.net.0.flags = up
```
```
container1:/# ip a sh  dev eth0
103: eth0@if104: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:e4:6a:d5 brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

**Comment by Dr-Bone** [comment]
Hi
The workaround is fine as long as there is only one bridge on the host (vlans) and every container has the same network interface and corresponding bridge.
As soon as you want to specify different bridges for different containers things get ugly as you have to create a file state to modify the container config that way. Or is there a better way?

Is there any information on when this will be fixed/enhanced?

**Comment by captnfab** [comment]
Still there in 2019.2.1.

**Comment by AdrienR** [comment]
I tried to make it work tonight, quick and dirty. I got something working for my needs, here is the gist of modules/lxc.py https://gist.github.com/AdrienR/9ec35a4275d458db8ac43bf2f93ddb10 This is from salt 2019.2.2

I would like to make it clean and try to get it merged in salt. Here is my proposed changes :
replace all 'lxc.network...' string with a function returning either lxc.network.. or lxc.net.x... checking the lxc version. Look not so complicated for an eventual first contribution. Any advice ?

Also, if i want to try : is this a bug because lxc3 is breaking the lxc module of salt, or is this a feature because the lxc module will support lxc3 ?

I don't have any others issues using the current module with lxc3.

**Comment by adam-codeberg** [comment]
> I tried to make it work tonight, quick and dirty. I got something working for my needs, here is the gist of modules/lxc.py https://gist.github.com/AdrienR/9ec35a4275d458db8ac43bf2f93ddb10 This is from salt 2019.2.2
> 
> I would like to make it clean and try to get it merged in salt. Here is my proposed changes :
> replace all 'lxc.network...' string with a function returning either lxc.network.. or lxc.net.x... checking the lxc version. Look not so complicated for an eventual first contribution. Any advice ?
> 
> Also, if i want to try : is this a bug because lxc3 is breaking the lxc module of salt, or is this a feature because the lxc module will support lxc3 ?
> 
> I don't have any others issues using the current module with lxc3.

We could change _network_profile_ from a dict, to a list of dicts, and the index of each item is the virtualized network index to satisfy the lxc.net.[virtualised_network_index].* requirement.

Example;

  ```
network_profile:
    - lxcbr:
        eth0:
          flags: up
          link: virbr0
          type: veth
          ipv4: 192.168.112.2/24
```

**Comment by captnfab** [comment]
> Or a dict of dicts with integers as the key.
Or a list?

**Comment by AdrienR** [comment]
> Or a dict of dicts with integers as the key.

The key would be redundant with the interface name ? Dunno if it's an issue or not.
I would vote for the list of dict instead.

**Comment by adam-codeberg** [comment]
> > Or a dict of dicts with integers as the key.
> 
> The key would be redundant with the interface name ? Dunno if it's an issue or not.
> I would vote for the list of dict instead.

Yeah. I gave it some thought and think the dict approach is required.
Ability to target the vnet arbitrarily is important to many orchestration use cases.

**Comment by captnfab** [comment]
@adam-codeberg: since you are working on the modules/lxc.py, here is a "quick fix" I personnaly had to do:  https://github.com/saltstack/salt/issues/52219#issuecomment-535421741

**Comment by adam-codeberg** [comment]
Created a fork and branch for this issue here https://github.com/adam-codeberg/salt/blob/fix-issue-50679/salt/modules/lxc.py

Works with. 

```
lxc.network_profile:
  lxcbr:
    eth0:
      flags: up
      link: virbr0
      type: veth
      ipv4.address: 192.168.112.1/24
    eth1:
      flags: up
      link: virbr0
      type: veth
      ipv4.address: 10.0.0.1/24
```

Need to spend some more time on it before it will work with IP configs as dicts;

```
lxc.network_profile:
  lxcbr:
    eth0:
      flags: up
      link: virbr0
      type: veth
      ipv4:
          address: 192.168.112.1/24
    eth1:
      flags: up
      link: virbr0
      type: veth
      ipv4:
          address: 10.0.0.1/24
```

Also need to spend some time on gateways.

Its a start.
