### ISSUE TITLE
Scheduler disappear

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#50749]
### Description of Issue
Create a scheduler on 6 minions with:   `salt \* state.sls  minion_ping`

Verify the schedulers with  `salt \* schedule.list`
6 minions show the scheduler.

After 10 minutes repeat the verification, 3 out of 6 minions have lost the schedule.

After more time, all minions loose the scheduler.

This is file /srv/salt/minion_ping.sls
```
minion_ping:
  schedule.present:
    - function: state.sls
    - job_args:
      - test.ping
    - seconds: 2880
    - splay: 2880
    - run_on_start: True
```

### Versions Report

Master 2018.3.3 (Oxygen)
Minions 2016.11.3 (Carbon)
