### ISSUE TITLE
state.http to support POST function.

### ISSUE THREAD

**Issue by cwray** [saltstack/salt#50761]
The state.http function does not currently support the POST function.

It currently looks like the HTTP module has this functionality. 

https://github.com/saltstack/salt/blob/0a6e3d2f8ff9a3406281e70be1bea6eadc0f5ef2/salt/states/http.py
https://github.com/saltstack/salt/blob/0a6e3d2f8ff9a3406281e70be1bea6eadc0f5ef2/salt/modules/http.py

It would be helpful for a state to be able to post data to an external API using HTTP during a run.

**Comment by dwoz** [comment]
@cwray It looks like the state does support POST via the `method` parameter. I ran a simple test with the following state to verify POST is working.

```
query_example:
  http.query:
    - name: 'http://127.0.0.1:5000/'
    - status: 200
    - method: POST
```
