### ISSUE TITLE
How to use Cobbler with Saltstack

### ISSUE THREAD

**Issue by mygithubthrowaway** [saltstack/salt#50789]
### Description of Issue/Question
Hi all,
I'm trying to glue together cobbler and saltstack/salt-cloud.
Reading from this https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.cobbler.html i setup the master like this:
### Setup
```
ext_pillar:
  - nodegroups:
      pillar_name: 'nodegroups'
  - cobbler:
    key: cobbler

cobbler.url: https://someurl.somefqdn.us/cobbler_api
cobbler.user: someuser
cobbler.password: somepw
```

but i don't understand how this works, if i try to get pillar items "cobbler" i dont'have any output.
In general what is the best way to do a salt-cloud vm init with kickstart file?
Thanks

### Versions Report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
