### ISSUE TITLE
[fluorine] windows stops when cannot connect to master

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#50854]
### Description of Issue/Question
When the master is not running and the windows minion attempts to connect to the master the process shutsdown and does not continue to try to connect to the master again.

### Setup
I installed windows like so:

`powershell -file build_env_2.ps1`
`pip install -e .`

### Steps to Reproduce Issue
1. attach a window minion to a master
2. verify you can run commands from the master to windows minion
3. stop both master and minion
4. start minion `salt-minion -ldebug` and wait for about 5 minutes

and you will see it shutdown:

```
[DEBUG   ] SaltReqTimeoutError, retrying. (1/7)
[ERROR   ] Minion unable to successfully connect to a Salt Master.  Exiting.
[INFO    ] Stopping the Salt Minion
[ERROR   ] Minion unable to successfully connect to a Salt Master.  Exiting.
[INFO    ] Shutting down the Salt Minion
The Salt Minion is shutdown.
Minion unable to successfully connect to a Salt Master.  Exiting.
PS C:\salt>
```

### Versions Report

```
PS C:\salt> salt --versions-report
Salt Version:
           Salt: 2018.11.0-166-gc16d0f3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```
