### ISSUE TITLE
netconfig.managed state reports "Configuration changed" when no changes and commit=False

### ISSUE THREAD

**Issue by mngan** [saltstack/salt#50926]
### Description of Issue/Question

When I apply a netconfig.managed state to a device with the commit=False parameter, the state will always report "Configuration changed" even though there are no changes, and the diff is empty. This appears to be caused by the code in salt.modules.napalm_network._config_logic() not handling the case where commit_config=False. 

### Setup
```
junos_common:
    netconfig.managed:
        - template_name: salt://junos/templates/junos.j2
        - debug: True
        - commit: False
        - watch_in:
            - module: junos_commit

junos_commit:
    module.wait:
        - name: net.commit
```

### Steps to Reproduce Issue
Apply the state above that causes a change and see the commit execute. Then re-run the state, the commit should not execute, but it does because the netconfig.managed reports that things have changed. 

```
----------
          ID: junos_common
    Function: netconfig.managed
      Result: True
     Comment: Configuration changed!
     Started: 17:19:27.560236
    Duration: 494.076 ms
     Changes:
              ----------
              diff:
              loaded_config:
                  system { ...
```

I can work around this by inserting this check into the bottom of salt.modules.napalm_network._config_logic() to handle the missing case. 

```
    if not commit_config:
        if not len(loaded_result.get('diff', '')) > 0:
            loaded_result['already_configured'] = True
            loaded_result['comment'] = 'Already configured.'
```

### Versions Report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.13
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-42-generic
         system: Linux
        version: Ubuntu 18.04 bionic
