### ISSUE TITLE
`file.shortcut` state fails to run due to `com_error`

### ISSUE THREAD

**Issue by MasonEdgel** [saltstack/salt#51027]
### Description of Issue/Question
`file.shortcut` fails to run: `com_error: (-2147221008, 'CoInitialize has not been called.', None, None)`

### Setup
- A simple `state.sls`:
```
make-shortcut:
  file.shortcut:
    - name: C:/Users/Public/Desktop/test.lnk
    - target: C:/Windows/System32/cmd.exe
```

### Steps to Reproduce Issue
Apply the above state, be greeted with the following error:
```
[user@master ~]$ sudo salt 'minion' state.apply temp
minion:
----------
          ID: make-shortcut
    Function: file.shortcut
        Name: C:/Users/Public/Desktop/test.lnk
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1913, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1898, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 6757, in shortcut
                  user)
                File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 1200, in _shortcut_check
                  shell = win32com.client.Dispatch("WScript.Shell")
                File "c:\salt\bin\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
                  dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
                File "c:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
                  return (_GetGoodDispatch(IDispatch, clsctx), userName)
                File "c:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
                  IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
              com_error: (-2147221008, 'CoInitialize has not been called.', None, None)
     Started: 13:59:25.268000
    Duration: 78.0 ms
     Changes:

Summary for minion
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  78.000 ms

-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 1
# of minions that did not return: 0
# of minions with errors: 1
-------------------------------------------
```

### Versions Report
`master`:
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```
`minion`:
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```

### Workaround
I was able to get it working as expected by adding `import pythoncom` to the top of `file.py`, as well as calling CoInitialize in the `shortcut` declaration just before it runs `_shortcut_check`:
```
    pythoncom.CoInitialize()
    presult, pcomment, ret['pchanges'] = _shortcut_check(name,
```
```
[user@master ~]$ sudo salt 'minion' state.apply temp
minion:
----------
          ID: make-shortcut
    Function: file.shortcut
        Name: C:/Users/Public/Desktop/test.lnk
      Result: True
     Comment: Created new shortcut C:\Users\Public\Desktop\test.lnk -> C:\Windows\System32\cmd.exe
     Started: 13:56:04.451000
    Duration: 79.0 ms
     Changes:
              ----------
              new:
                  C:\Users\Public\Desktop\test.lnk

Summary for minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  79.000 ms


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 1
# of minions that did not return: 0
# of minions with errors: 0
-------------------------------------------
```
