### ISSUE TITLE
http.wait_for_successful_query state with wait_for and test=true blocks and waits

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#51045]
### Description of Issue/Question
The state waits for the `wait_for` amount of time even when `test=True`

### Setup
`test.sls`
```sls
http://127.0.0.1:8000/:
  http.wait_for_successful_query:
    - wait_for: 120
    - request_interval: 5
    - status: 200
```

### Steps to Reproduce Issue
```bash
salt-call -l debug --local state.sls test test=true
```

### Versions Report
```yaml
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
