### ISSUE TITLE
splay executor: Invalid arguments are being passed to the execution module

### ISSUE THREAD

**Issue by hwoarang** [saltstack/salt#51058]
### Description of Issue/Question
I tried to run the example from https://docs.saltstack.com/en/latest/ref/executors/index.html on my local installation but it failed. It seems that the wrong arguments are being passed down to the requested execution module
```
master:~ # salt -t 40 --module-executors='[splay, direct_call]' --executor-opts='{splaytime: 30}' '*' test.ping
minion:
    Passed invalid arguments to test.ping: unsupported operand type(s) for *: 'int' and 'NoneType'
    
        Used to make sure the minion is up and responding. Not an ICMP ping.
    
        Returns ``True``.
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' test.ping
```

### Setup
openSUSE Leap 15.0
salt-2018.3.0-lp150.3.14.1

### Steps to Reproduce Issue
```
salt -t 40 --module-executors='[splay, direct_call]' --executor-opts='{splaytime: 30}' '*' test.ping
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-lp150.12.25-default
         system: Linux
        version: Not Installed
```
