### ISSUE TITLE
file.blockreplace is not using template when contents are user defined

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#51062]
`file.blockreplace` is not using template when contents are user defined.
this works with `file.managed` and I find it really helpful.

a state like
```
test_content_blockreplace_with_template:
    file.blockreplace:
        - name: /atest.text
        - content: {{'{{vars}}'}}
        - prepend_if_not_found: true
        - show_changes: true
        - template: jinja
        - context:
            vars: 'XXXXXX'
```

will make the file like.
```
### START SALT ###
{{vars}}
### END SALT ###
```

when using `file.managed` you will get the expected result

I think the patch should be around here:

https://github.com/saltstack/salt/blob/6ced9fd63988a5c84c906c0878430356b1ca1bd2/salt/states/file.py#L5204

and add something like:
```
            contents = __salt__['file.apply_template_on_contents'](
                contents,
                template=template,
                context=context,
                defaults=defaults,
                saltenv=__env__)
```

**Comment by steverweber** [comment]
my current hacky workaround
```
test_content_blockreplace_with_template:
    file.blockreplace:
        - name: /atest.text
        - content: {{salt.file.apply_template_on_contents("{{vars}}", template='jinja', context={'vars': 'XXXXXX'}, defaults={}, saltenv='base')|json}}
        - prepend_if_not_found: true
        - show_changes: true
```
