### ISSUE TITLE
Using file_client: remote and local files  at the same time 

### ISSUE THREAD

**Issue by adambarnett52** [saltstack/salt#51075]
### Description of Issue/Question
Hi 

I moving from a masterless setup to using a master
I am going to set 

```
file_client: remote
```
But when i do this i seem to loose the ability to run ```salt-call --local --file-root= .....```
It just complains about not finding the environment

```
   No matching salt environment for environment 'master' found
```

```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

Am i missing something, my config looks like this 

```
default_include: minion.d/*.conf
master: saltmastertest
pillarenv_from_saltenv: True
id: testingmmachine
random_reauth_delay: 270
auth_timeout: 60
recon_default: 1000
recon_max: 59000
recon_randomize: True

file_roots:
  base:
    -/etc/salt-develop/formula

pillar_roots:
  base:
    - /etc/salt-develop/pillar

file_client: remote
environment: master
startup_states: 'sls'
log_level: info
log_level_logfile: info

```

Thanks
