### ISSUE TITLE
postgres_extension.present is not available

### ISSUE THREAD

**Issue by xuhcc** [saltstack/salt#51125]
### Description of Issue

`postgres_extension.present` state fails with error:

```
          ID: myproject_pg_hstore_extension
    Function: postgres_extension.present
        Name: hstore
      Result: False
     Comment: State 'postgres_extension.present' was not found in SLS 'myproject'
              Reason: 'postgres_extension.present' is not available.
     Changes: 
```

### Setup

```
myproject_pg_hstore_extension:
  postgres_extension.present:
    - name: hstore
    - user: myproject
    - maintenance_db: myproject
    - if_not_exists: true
```

### Versions Report

```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.2
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Jun 27 2018, 13:05:28)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.0
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.20.0-arch1-1-ARCH
         system: Linux
        version: Not Installed
 ```
