### ISSUE TITLE
feature-request: salt-ssh does not merge roster_defaults with roster items.

### ISSUE THREAD

**Issue by erenfro** [saltstack/salt#51181]
### Description of Issue/Question
Per https://github.com/saltstack/salt/blob/2018.3/salt/roster/flat.py#L152

This does not use salt.utils.dictupdate to merge the salt-ssh roster_defaults lists with settings provided from the roster itself which would be very handy for allowing override options from defaults merged with roster specifics.

What would be preferred to happen is that roster_defaults merges with the roster item(s) accordingly so over changes can be made rather than re-duplicating everything necessary for each and every roster item.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
master:
```yaml
roster_defaults:
  user: root
  sudo: False
  priv: agent-forwarding
  grains:
    environment: production
    datacenter: somewhere
    roles: []
```

roster:
```yaml
bastion:
  host: bastion.home.ld
  user: root
  sudo: False
  grains:
    roles:
      - bastion
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
With salt-ssh setup accordingly, when overriding just the roles value in the roster, `salt-ssh 'bastion' grains.items` nor `salt-ssh 'bastion' grains.get environment` provide a value for environment which was set in roster_defaults.grains.environment.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 8.9.1
       dateutil: 2.6.1
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: Not Installed

System Versions:
           dist: LinuxMint 19.1 tessa
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-13-generic
         system: Linux
        version: LinuxMint 19.1 tessa
```
