### ISSUE TITLE
Salt 2018.3 fails to parse strings containing "{" or "}" symbols or "?" symbol

### ISSUE THREAD

**Issue by Martin819** [saltstack/salt#51216]
### Description of Issue/Question

If a string containing "{" or "}" symbol or "?" symbol is included in a string in a pillar, Salt fails to parse it correctly and fails with:

```       local:
           Data failed to compile:
       ----------
           Rendering SLS 'base:fluentd.agent' failed: while parsing a flow mapping
         in "<unicode string>", line 49, column 334:
            ... ng': {u'filter': {u'parse_log': {u'tag': u'test.{case}.*', u'typ ... 
                                         ^
       expected ',' or '}', but got '{'
         in "<unicode string>", line 49, column 350:
            ...  {u'parse_log': {u'tag': u'test.{case}.*', u'type': u'parser', u ... 
```
or
```       local:
           Data failed to compile:
       ----------
           Rendering SLS 'base:fluentd.agent' failed: while parsing a flow mapping
         in "<unicode string>", line 49, column 434:
            ... u'key_name': u'log', u'parser': {u'type': u'regexp', u'format':  ... 
                                         ^
       expected ',' or '}', but got '?'
         in "<unicode string>", line 49, column 477:
            ... 'regexp', u'format': u'/^time="(?<time>[^ ]*)" level=(?<severity ... 
```

### Setup
Pillar:
```
    config:
      label:
        monitoring:
          filter:
            parse_log:
              tag: "test.{case}.*"
              type: parser
              reserve_data: true
              key_name: log
              parser:
                type: regexp
                format: >-
                  /^time="(?<time>[^ ]*)" level=(?<severity>[a-zA-Z]*) msg="(?<message>.+?)"/
                time_format: "%FT%TZ"
```

SLS file:
```
{%- for label_name,values in config.get('label', {}).iteritems() %}
{%- if values is not mapping or values.get('enabled', True) %}
label_{{ label_name }}_state:
  file.managed:
    - name: file.conf
    - source:
      - salt://files/file.conf
    - user: root
    - group: root
    - mode: 644
    - template: jinja
    - defaults:
        label_name: {{ label_name }}
  {%- if values is mapping %}
        values: {{ values | yaml }}
  {%- else %}
        values: {}
  {%- endif %}
{%- endif %}
{%- endfor %}
```

Changing `| yaml` to `| json` or `| tojson` didn't help.

### Steps to Reproduce Issue
Use provided files and apply state.

### Versions Report
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by dwoz** [comment]
@Martin819 Thanks for reporting the issue. I have been un-able to reproduce the problem. Here is my pillar file
```
    config:
      label:
        monitoring:
          filter:
            parse_log:
              tag: "test.{case}.*"
              type: parser
              reserve_data: true
              key_name: log
              parser:
                type: regexp
                format: >-
                  /^time="(?<time>[^ ]*)" level=(?<severity>[a-zA-Z]*) msg="(?<message>.+?)"/
                time_format: "%FT%TZ"
```

And the test state file:

```
{%- for label_name,values in pillar['config'].get('label', {}).iteritems() %}
{%- if values is not mapping or values.get('enabled', True) %}
label_{{ label_name }}_state:
  file.managed:
    - name: /home/admin/file.conf
    - source:
      - salt://files/file.conf
    - user: admin
    - group: admin
    - mode: 644
    - template: jinja
    - defaults:
        label_name: {{ label_name }}
  {%- if values is mapping %}
        values: {{ values | yaml }}
  {%- else %}
        values: {}
  {%- endif %}
{%- endif %}
{%- endfor %}
```

Are you able to try these and see if you get the same error? I'm guessing there is something different in your state or pillar.
