### ISSUE TITLE
"TypeError: 'NoneType' object is not iterable" during map assignment

### ISSUE THREAD

**Issue by johnnybubonic** [saltstack/salt#51294]
### Description of Issue/Question
When trying to assign a jinja.map:

```
{#- Set the defaults -#}
{%- load_yaml as default_settings %}
vim:
  pkg: vim
  conf: /etc/vimrc
bash:
  pkg: bash
  conf: /etc/bashrc
borg:
  pkg: borgbackup
  server: afterlife.foxyproxy.io
  port: 2222
netcat:
  pkg: netcat
{%- endload %}
{#- ============================================= -#}
{#- VIM  -#}
{#- Set OS-family-specific values -#}
{#- TODO: Add/confirm more OS support here -#}
{% set os_family_map = salt['grains.filter_by'](
{
    'Arch': {
        'pkg': ['vim', 'vim-plugins'],
    },
    'RedHat': {
        'pkg': 'vim-enhanced',
    },
},
grain="os_family",
merge=salt['pillar.get']('vim:lookup')) %}
{#- now perform the merge and set it to 'vim' #}
{% do default_settings.vim.update(os_family_map) %}
{% set vim = salt['pillar.get'](
    'vim',
    default=default_settings.vim,
    merge=True
)%}
{#- ============================================= -#}
{#- BASH -#}
{#- TODO: Add/confirm more OS support here -#}
{% set os_family_map = salt['grains.filter_by'](
{
    'Arch': {
        'pkg': ['bash', 'bash-completion'],
        'conf': '/etc/bash.bashrc',
    },
},
grain="os_family",
merge=salt['pillar.get']('bash:lookup')) %}
{% do default_settings.bash.update(os_family_map) %}
{% set bash = salt['pillar.get'](
    'bash',
    default=default_settings.bash,
    merge=True
)%}
{#- ============================================= -#}
{#- BORG -#}
{#- TODO: Add/confirm more OS support here -#}
{% set os_family_map = salt['grains.filter_by'](
{
    'Arch': {
        'pkg': 'borg',
    },
},
grain="os_family",
merge=salt['pillar.get']('borg:lookup')) %}
{% do default_settings.borg.update(os_family_map) %}
{% set borg = salt['pillar.get'](
    'borg',
    default=default_settings.borg,
    merge=True
)%}
{#- ============================================= -#}
{#- NETCAT -#}
{#- TODO: Add/confirm more OS support here -#}
{% set os_family_map = salt['grains.filter_by'](
{
    'RedHat': {
        'pkg': 'nc',
    },
    'Arch': {
        'pkg': 'gnu-netcat',
    },
},
grain="os_family",
merge=salt['pillar.get']('netcat:lookup')) %}
{% do default_settings.netcat.update(os_family_map) %}
{% set netcat = salt['pillar.get'](
    'netcat',
    default=default_settings.netcat,
    merge=True
)%}
```

I get the following:

```Python
salttest-fp.kvm.loc:
    Data failed to compile:
----------
    Rendering SLS 'base:roles.common' failed: Jinja error: 'NoneType' object is not iterable
/var/cache/salt/minion/files/base/roles/common/map.jinja(50):
---
[...]
        'conf': '/etc/bash.bashrc',
    },
},
grain="os_family",
merge=salt['pillar.get']('bash:lookup')) %}
{% do default_settings.bash.update(os_family_map) %}    <======================
{% set bash = salt['pillar.get'](
    'bash',
    default=default_settings.bash,
    merge=True
)%}
[...]
---
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/salt/utils/templates.py", line 393, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 1033, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 1090, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/var/cache/salt/minion/files/base/roles/common/map.jinja", line 50, in top-level template code
    {% do default_settings.bash.update(os_family_map) %}
TypeError: 'NoneType' object is not iterable
```
Interestingly, it does not seem to occur to the vim mapping. Is this me doing a dumb?

### Setup
See above.

### Steps to Reproduce Issue
See above.

### Versions Report

master:
```YAML
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.26.8
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.4.9 (default, Aug 14 2018, 21:28:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```
