### ISSUE TITLE
[2019.2.0] salt-key TypeError

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#51369]
When accepting or deleting a key on the head of 2019.2.0.rc1 branch I see the following error:

```
[root@ab52dd2043f2 testing]# salt-key -A -y
The following keys are going to be accepted:
Unaccepted Keys:
ab52dd2043f2
Key for minion ab52dd2043f2 accepted.
Exception TypeError: "'NoneType' object is not callable" in <bound method IPCMessageClient.__del__ of <salt.transport.ipc.IPCMessageClient object at 0x7f5f0bbbd050>> ignored
```

```
[root@ab52dd2043f2 testing]# salt-key -D -y
The following keys are going to be deleted:
Accepted Keys:
ab52dd2043f2
Key for minion ab52dd2043f2 deleted.
Exception TypeError: "'NoneType' object is not callable" in <bound method IPCMessageClient.__del__ of <salt.transport.ipc.IPCMessageClient object at 0x7fc64710bf90>> ignored
[root@ab52dd2043f2 testing]# 
```

It is working functionally just fine, but this error is seen each time.

running `salt-key -L` does not show the error:

```
[root@ab52dd2043f2 testing]# salt-key -L
Accepted Keys:
Denied Keys:
Unaccepted Keys:
Rejected Keys:
[root@ab52dd2043f2 testing]# 
```

Here is a docker container to replicate the issue:

1. `docker run -it -v ~/git/salt/:/testing/ ch3ll/issues:ipc_typeerror /bin/bash` (where ~/git/salt/ is a local cloned git repo)

2. `salt-master -d; salt-minion -d` and then wait for the minion to start up

3. `salt-key -A -y`

**Comment by Ch3LL** [comment]
here is the versions report:

```
[root@73cf60ecabdf /]# salt --versions-report
Salt Version:
           Salt: 2019.2.0rc2-2-g913a349

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: 3.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.6.6
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.16-rt9-MANJARO
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by Ch3LL** [comment]
looks like i was able to bisect the issue to 2c3b1d39739553ba419a76c3b2b96167cdbb2c80 which is this PR: https://github.com/saltstack/salt/pull/50997

ping @s0undt3ch can you take a look here?

to note I was not able to replicate this on this box:

```
➜  salt git:(9b438ef1d9) salt --versions-report
Salt Version:
           Salt: 2019.2.0-182-g62ca3ff

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.5
      docker-py: 3.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Jan 10 2019, 23:20:52)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.18.16-rt9-MANJARO
         system: Linux
        version: Not Installed
```

So it could be a difference in some libraries perhaps
