### ISSUE TITLE
Please resolve DeprecationWarning

### ISSUE THREAD

**Issue by dpizzle** [saltstack/salt#51398]
### Steps to Reproduce Issue
```
/ # salt 'vsrx01' test.ping
[WARNING ] /usr/lib/python3.6/site-packages/salt/transport/ipc.py:287: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  self.unpacker = msgpack.Unpacker(encoding=encoding)

[WARNING ] /usr/lib/python3.6/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

vsrx01:
    True
```

### Versions Report
```
/ # salt --versions-report
Salt Version:
           Salt: 2019.2.0rc1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 24 2018, 05:04:18)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.9.125-linuxkit
         system: Linux
        version: Not Installed
```

**Comment by chenull** [comment]
i think this PR #51262 will do

**Comment by keke8273** [comment]
Same issue here

Salt Version:                                                                                                                                     Salt: 2018.3.3                                                                                                                                                                                                                                                     Dependency Versions:                                                                                                                              cffi: Not Installed                                                                                                                cherrypy: Not Installed                                                                                                                dateutil: Not Installed                                                                                                               docker-py: Not Installed                                                                                                                   gitdb: Not Installed                                                                                                               gitpython: Not Installed                                                                                                                   ioflo: Not Installed                                                                                                                  Jinja2: 2.10                                                                                                                          libgit2: Not Installed                                                                                                                 libnacl: Not Installed                                                                                                                M2Crypto: Not Installed                                                                                                                    Mako: Not Installed                                                                                                            msgpack-pure: Not Installed                                                                                                          msgpack-python: 0.6.1                                                                                                                    mysql-python: Not Installed                                                                                                               pycparser: Not Installed                                                                                                                pycrypto: 2.6.1                                                                                                                    pycryptodome: Not Installed                                                                                                                  pygit2: Not Installed                                                                                                                  Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)                                                                               python-gnupg: Not Installed                                                                                                                  PyYAML: 3.13                                                                                                                            PyZMQ: 17.1.2                                                                                                                           RAET: Not Installed                                                                                                                   smmap: Not Installed                                                                                                                 timelib: Not Installed                                                                                                                 Tornado: 4.5.3                                                                                                                             ZMQ: 4.2.5                                                                                                                                                                                                                                                        System Versions:                                                                                                                                  dist: Ubuntu 18.04 bionic                                                                                                            locale: UTF-8                                                                                                                         machine: x86_64                                                                                                                        release: 4.15.0-1036-azure                                                                                                              system: Linux                                                                                                                         version: Ubuntu 18.04 bionic
--

**Comment by iondulgheru** [comment]
Same issue

```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.4
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.2
         Python: 3.6.8 (default, Jan 24 2019, 16:36:30)
   python-gnupg: Not Installed
         PyYAML: 4.1
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.9.125-linuxkit
         system: Linux
        version: Not Installed
```
