### ISSUE TITLE
Git Pillar data duplicated on minions when edited

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#51391]
### Description of Issue/Question
I have a lot of Pillar data in git_pillar, but this data gets updated regularly, and when this happens, rather than updating the edited items, minions just add the edited versions to the existing items, which causes states that iterate over this data to fail and/or repeat operations, which is really bad and wrong.

### Setup
for example, pillar data might look like this originally:
```
app_config_stuff:
  thing1:
    - name: thing1
      version: 1.2.0
```
a `pillar.items` shows this data just fine from the minion. But then if i update this so that pillar looks like this:
```
app_config_stuff:
  thing1:
    - name: thing1
      version: 1.2.2
```
and then do `pillar.items` again, the minion will return two copies of the `thing1` object, each with a different `version` attribute, instead of just the one that has been edited like they should. Running `saltutil.refresh_pillar` has no effect on the issue on the minion, and just forcibly deleting everything in the master's cache isn't a useful workaround because then minions take 15 years to rebuild their pillar cache and that just doesn't work for me. Also, from the master, `salt-run cache.clear_all` keeps returning False for no discernible reason at all.
