### ISSUE TITLE
Issue with grains virtual in fluorine

### ISSUE THREAD

**Issue by arif-ali** [saltstack/salt#51451]
Hi

I am currently testing flourine in one of our internal formulas, and running into an issue.

I originally thought it may be the underlying operating system of the CI server, but it doesn’t seem like it. The CI servers have been re-installed from CentOS and  are now ubuntu 18.04.1, and are KVM VMs,  (i.e. all identical).

In my formula I have a test `{% if grains['virtual'] == "physical" %}` and this is passing, which is shouldn’t. This test only passes in the centos docker containers and therefore running states that are meant for physical machines. However, this test does not pass in the Ubuntu docker containers, so doesn’t run the states meant for physical machines.

So in my CI pipeline, everything passes except for centos 6/7 with salt flourine.

My setup involves doing CI using kitchen-salt, under GitLab CI. 

Below is a snippet of my .kitchen.yml, with any specifics removed

```
---
driver:
  name: docker

platforms:
  - name: centos-6
    driver_config:
      image: registry.ocf.co.uk/salt/docker/centos-6-kitchen:base
      privileged: True
      run_command: /sbin/init
      use_cache: False
      remove_images: True
    provisioner:
      salt_yum_repo: 'https://repo.saltstack.com/yum/redhat/$releasever/$basearch/%s'
      salt_yum_rpm_key: 'https://repo.saltstack.com/yum/redhat/6/x86_64/latest/SALTSTACK-GPG-KEY.pub'
      salt_install: yum
      pip_bin: pip2.7
      salt_bootstrap_options: "-P -p git -p curl -p sudo -y -x python2.7 git %s"
  - name: centos-7
    driver_config:
      image: registry.ocf.co.uk/salt/docker/centos-7-kitchen:base
      privileged: True
      run_command: /usr/lib/systemd/systemd
      use_cache: False
      remove_images: True
    provisioner:
      salt_yum_repo: 'https://repo.saltstack.com/yum/redhat/$releasever/$basearch/%s'
      salt_yum_rpm_key: 'https://repo.saltstack.com/yum/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub'
      salt_install: yum
  - name: ubuntu-16.04
    driver_config:
      image: registry.ocf.co.uk/salt/docker/ubuntu-16.04-kitchen:base
      privileged: True
      run_command: /lib/systemd/systemd
      use_cache: False
      remove_images: True
    provisioner:
      salt_apt_repo: 'https://repo.saltstack.com/apt/ubuntu/16.04/amd64'
      salt_apt_repo_key: 'https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub'
      salt_install: apt

provisioner:
  name: salt_solo
  formula: <snip>
  salt_install: bootstrap
  salt_version: latest
  salt_bootstrap_options: -P -p git -p curl -p sudo git %s
  vendor_path: srv/salt
<SNIP>

suites:
  - name: nitrogen
    provisioner:
      salt_version: '2017.7'
  - name: carbon
    provisioner:
      salt_version: '2016.11'
  - name: oxygen
    provisioner:
      salt_version: '2018.3'
  - name: flourine
    provisioner:
      salt_version: '2019.2'
      salt_install: bootstrap
  - name: develop
    provisioner:
      salt_version: 'develop'
      salt_install: bootstrap
```

below is an image of my pipeline showing the failures and passes of all my CI jobs for this specific salt formula

![screenshot 2019-01-31 at 10 02 16](https://user-images.githubusercontent.com/628790/52055336-0b17c380-2557-11e9-8749-9bfd091684a0.png)

**Comment by arif-ali** [comment]
Just to update this, here's some diagnostics data from a VM, and running the same stuff without going onto the CI machines itself. Taking GitLab, and it's CI mechanism out of the question

Below is the output from CentOS 7
```
[root@salt-kitchen-06 ~]# kitchen login flourine-centos-7
Last login: Thu Jan 31 17:38:44 2019 from gateway
[kitchen@fca24d9d85ee ~]$ sudo su -
Last login: Thu Jan 31 17:39:04 UTC 2019 on pts/0
[root@fca24d9d85ee ~]# salt-call grains.get virtual  --local
local:
    physical
[root@fca24d9d85ee ~]# salt --version
salt 2019.2.0-n/a-a16461b (Fluorine)
[root@fca24d9d85ee ~]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)
```

And below is the output from Ubuntu

```
[root@salt-kitchen-06 ~]# kitchen login flourine-ubuntu-1604
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 3.10.0-862.11.6.el7.x86_64 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Thu Jan 31 17:45:21 2019 from 172.17.0.1
kitchen@5e22aafd61ed:~$ sudo su - 
root@5e22aafd61ed:~# salt-call grains.get virtual  --local
local:
    kvm
root@5e22aafd61ed:~# salt --version
salt 2019.2.0-n/a-a16461b (Fluorine)
root@5e22aafd61ed:~# cat /etc/issue
Ubuntu 16.04.5 LTS \n \l
```
I would expect to see `kvm` on both

**Comment by thatch45** [comment]
@arif-ali thanks for reporting this. We will look into it.

On these systems do you have the `virt-what` binary installed? We change how we get this value if that is present because it can give us a more accurate reading. If you can let me know if the output changes with this installed of not it will help us a great deal.

As we dive in deeper we will likely also ask you to see if certain files are present.

**Comment by arif-ali** [comment]
@thatch45 thanks for that, ok indeed, by installing `virt-what` it does solve the problem. But we can't expect people to normally install that on all their machines.

Unless you have this as a planned dependency on the RPM/DEB packages when the package is finally available? Obviously, at the moment, I am grabbing fluorine via git

@gtmanfred is it worth having this dependency installed as part of salt_solo in kitchen-salt?

**Comment by thatch45** [comment]
I was mostly asking to help us diagnose the issue, we certainly need to fix it, but this allows us to better zone in on the code with the issue.

**Comment by arif-ali** [comment]
ah, ok, no problems. I thought it was a new dependency :)

Let me know if you need anything else, and I'll happily assist

**Comment by thatch45** [comment]
Will do, thanks!

**Comment by arif-ali** [comment]
So, after adding `virt-what` into all my docker images, and adding it to my internal GitLab registry, I merged my local changes, thinking, that adding this package will temporarily resolve the problem. However, now everything passes, except for Ubuntu 16.04 with carbon, oxygen and nitrogen. Ubuntu 16.04 passes for fluorine though.

Any thoughts?

**Comment by thatch45** [comment]
That makes me wonder if it is a virt-what bug, can you tell us what you see when you run virt-what directly?
But we have very extensive checks around virtualization, and we look for a lot of commands to run for the checks, I am wondering if this is because the container you are is is just too stripped down?
Here is the detection code:
https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L677

**Comment by arif-ali** [comment]
So `virt-what` does give the same information no matter what, but the code that you have linked to is from develop/fluorine, as shown below

```
lxc
kvm
```

So for fluorine, it works fine, I need to figure out what the issues are in oxygen, carbon and nitrogen for the OSs, and look at the corresponding code

**Comment by arif-ali** [comment]
Just going through all the steps of that code

Below are the commands that it uses in the order that it finds it.

1. systemd-virt-detect
2. virt-what -- doesn't exist by default
3. dmidecode
4. lspci -- doesn't exist by default

Below are the outputs of these commands, as the ones available by default
### systemd-virt-detect
```
# for kitchen in `kitchen list | grep nitrogen | awk '{print $1}'`; do kitchen exec $kitchen -c "sudo systemd-detect-virt"; done
-----> Execute command on nitrogen-centos-6.
       sudo: systemd-detect-virt: command not found
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::Transport::SshFailed
>>>>>> Message: SSH exited (1) for command: [sudo systemd-detect-virt]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

-----> Execute command on nitrogen-centos-7.
       docker
-----> Execute command on nitrogen-ubuntu-1604.
       docker
-----> Execute command on nitrogen-ubuntu-1804.
       docker
```
### dmidecode
```
# for kitchen in `kitchen list | grep nitrogen | awk '{print $1}'`; do kitchen exec $kitchen -c "sudo dmidecode | grep Manufacturer"; done
-----> Execute command on nitrogen-centos-6.
       	Manufacturer: QEMU
       	Manufacturer: QEMU
       	Manufacturer: QEMU
       	Manufacturer: QEMU
-----> Execute command on nitrogen-centos-7.
       	Manufacturer: QEMU
       	Manufacturer: QEMU
       	Manufacturer: QEMU
       	Manufacturer: QEMU
-----> Execute command on nitrogen-ubuntu-1604.
       	Manufacturer: QEMU
       	Manufacturer: QEMU
       	Manufacturer: QEMU
       	Manufacturer: QEMU
-----> Execute command on nitrogen-ubuntu-1804.
       sudo: dmidecode: command not found
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::Transport::SshFailed
>>>>>> Message: SSH exited (1) for command: [sudo dmidecode | grep Manufacturer]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

You may want to move the `virt-what` command stuff before the `systemd-virt-detect`, which will ensure that you get the correct results? does that make sense?

I am not saying this is what we need to do, but hopefully the above gives us a bit more info to solve the problem

**Comment by waynew** [comment]
@arif-ali I'm having a heck of a time reproducing this. 

```
# bundle exec kitchen login flourine-centos-7
Last login: Wed Apr  3 21:19:26 2019 from gateway
[kitchen@8fb28780fd13 ~]$ sudo salt-call --local grains.get virtual
local:
    bhyve
```

I'm using this kitchen.yml:

```
---

driver:
  name: docker

platforms:
  - name: centos-7
    driver_config:
      image: registry.ocf.co.uk/salt/docker/centos-7-kitchen:base
      privileged: True
      run_command: /usr/lib/systemd/systemd
      use_cache: False
      remove_images: True
    provisioner:
      salt_yum_repo: 'https://repo.saltstack.com/yum/redhat/$releasever/$basearch/%s'
      salt_yum_rpm_key: 'https://repo.saltstack.com/yum/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub'
      salt_install: yum

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_version: latest
  salt_bootstrap_options: -P -p git -p curl -p sudo git %s
  formula: srv/salt
  log_level: debug
  sudo: true
  require_chef: false
  remote_states:
    name: https://github.com/waynesaltdebugging/stay-t.git
    branch: master
    repo: git
    testingdir: /testing
  salt_copy_filter:
    - __pycache__
    - '*.pyc'
    - .bundle
    - .tox
    - .kitchen
    - artifacts
    - Gemfile.lock
  state_top:
    base:
      '*':
        - boop

suites:
  - name: flourine
    provisioner:
      salt_version: '2019.2'
      salt_install: bootstrap
```

I wonder though - my docker version is: 
```
Docker version 18.09.2, build 6247962
``` using Docker on Mac.

Are you still having this problem at all?
