### ISSUE TITLE
2019.2-rc2 show splay: none for some schedule stats

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#51467]
### Description of Issue/Question
```----------
          ID: smartos.image:cleanup
    Function: schedule.present
      Result: True
     Comment: Modifying job smartos.image:cleanup in schedule
     Started: 14:34:01.351854
    Duration: 36.199 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -4,4 +4,3 @@
                   jid_include:True
                   maxrunning:1
                   name:smartos.image:cleanup
                  -splay:None
```

It shows this every time the state is applied.

The state itself is rather minimal

```
# remove images
smartos.image:cleanup:
  schedule.present:
    - function: imgadm.vacuum
    - hours: 6
```

### Steps to Reproduce Issue
- upgrade to 2019.3-rc2 (rc1 is effect too I think)
- do a state.apply

### Versions Report
```[cronos :: sjorge][/salt/states][master ✗]
[.]$ salt --versions-report
Salt Version:
           Salt: 2019.2.0rc2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.6.6
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Oct 23 2018, 17:11:49)
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed```

**Comment by max-arnold** [comment]
Also it always reports changes in job kwargs:

```
test_schedule:
  schedule.present:
    - function: state.sls_id
    - job_args:
        - test_state
        - {{ sls }}
    - job_kwargs:
        pillar:
          enabled: True
    - cron: '0 * * * *'
```

```
local:
----------
          ID: test_schedule
    Function: schedule.present
      Result: True
     Comment: Modifying job test_schedule in schedule
     Started: 13:39:43.175703
    Duration: 25.937 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -3,7 +3,6 @@
                   enabled:True
                   function:state.sls_id
                   jid_include:True
                  -kwargs:{'pillar': {'enabled': True}}
                  +kwargs:OrderedDict([('pillar', OrderedDict([(enabled', True)]))])
                   maxrunning:1
                   name:test_schedule
                  -splay:None
```
