### ISSUE TITLE
Feature Requests: Windows Software Repository and Windows File Version

### ISSUE THREAD

**Issue by scheste** [saltstack/salt#51474]
Hi,

I have 2 feature requests, which would be very useful under Windows, especially for updating software.

1. In some cases previous versions are unavailable. Google Chrome or for example, there is #only one URL provided for a standalone installation of Google Chrome.

The disadvantage is that even if the version has not changed, the software is reinstalled every time the state is executed. From my point of view, there would be a way how this could be avoided for most installers under Windows.

On many installers, the "File version", "Product version" or "Comments" field contains the correct version, which could be compared with the version displayed under "Program and Files" if the software is installed.

The installer must still be downloaded for comparison, but the software will not be reinstalled every time the state is running. This is not a perfect solution, but still a good improvement.

For this, winrepo functionality would have to be extended by an additional parameter, if `latest` was selected in the version specification.

2. A related topic, because in the first case the file version should be checked as well.

Currently no module or state exists, which can get the file version under windows, comparable to the ansible module win_file_version
https://docs.ansible.com/ansible/latest/modules/win_file_version_module.html
It`s possible to check the file hash or other workarounds for Installers / DLLs, but it is also much more effort intensive. This would also be very helpful under Windows. 

@twangboy - Feature Request is created!

Best,
Stefan

**Comment by damon-atkins** [comment]
From memory this should only happen if you use latest.   What version of salt are you using.
For example just a plan salt server pkg.install chrome will say its already installed.

**Comment by damon-atkins** [comment]
https://github.com/saltstack/salt/pull/47702 fixed an upgrade issue. Best version to check with are
2017.7.6 and 2018.3.1

**Comment by scheste** [comment]
I use the current salt version 2018.3.3.
Shane said that when using latest, instead of a version number, the package is reinstalled each time a state is run.
It's even worse, I've tested it with vs_remotetools_2017 state from https://github.com/saltstack/salt-winrepo-ng/blob/master/vs_remotetools_2017
I installed it on 2 systems, then I ran the state again and it didn't happen. 
The salt feedback was also insufficient for me:

salt 'win*' pkg.install vs_remotetools_2017
win2019:
    ----------
win10-x86:
    ----------

Then I have changed the version in the registry Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{8503049A-527C-3361-AFB9-1A4E5E0AEF55}
to an older version and execute the state again, even then nothing happens.

Therefore I estimate that if the package is found by name, the installation will be suspended. However, this behavior could be improved when using latest as version.

I think it would be helpful, because windows behaves a little different than Linux.
Unfortunately there will be more and more applications which have a unique download link and the version can only be found via the file or product version.

1. better feedback than as in the example above
2. Additional optional parameter which additionally compares the file and / or product version with the registry values. Then an update will also be performed for the version specification latest, if a newer version can be found in the installer as in the registry.

This would help a lot, because otherwise there is only the workaround to uninstall and reinstall the software every time. Even if the version hasn't changed.

I would definitely not change the default behavior, but solve for this more specific topic with an additional parameter. In the future the problem of version and download links will definitely increase further.

**Comment by damon-atkins** [comment]
Current if the software is installed no action is taken unless you specify a version or specify  latest. This is by design.  

The following is the correct and expected behavior on windows.
```
C:\salt>salt-call -l info pkg.version chrome
local:
    71.0.3578.98
```

```
C:\salt>salt-call -l info pkg.install chrome
local:
    ----------

```

```
C:\salt>salt-call -l info pkg.install chrome version=latest
[INFO    ] cmdmod._run Executing command '"C:\WINDOWS\system32\cmd.exe" /s /c ""msiexec" /I "c:\salt\var\cache\salt\minion\extrn_files\base\dl.google.com\edgedl\chrome\install\Goog
leChromeStandaloneEnterprise.msi" ALLUSERS=1 /qn /norestart"' in directory 'c:\salt\var\cache\salt\minion\extrn_files\base\dl.google.com\edgedl\chrome\install'
local:
    ----------
    chrome:
        ----------
        new:
            67.138.32849
        old:
            71.0.3578.98  # I suspect the retail version maybe ahead of the enterprise version.
```
Here is the sls definition
```
chrome:
  latest:
    full_name: 'Google Chrome'
    installer: 'https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi'
    install_flags: '/qn /norestart'
    uninstaller: 'https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
```

**Comment by damon-atkins** [comment]
Current if the software is installed no action is taken unless you specify a version or specify  latest. This is by design.  

The following is the correct and expected behavior on windows.
```
C:\salt>salt-call -l info pkg.version chrome
local:
    71.0.3578.98
```

```
C:\salt>salt-call -l info pkg.install chrome
local:
    ----------

```

```
C:\salt>salt-call -l info pkg.install chrome version=latest
[INFO    ] cmdmod._run Executing command '"C:\WINDOWS\system32\cmd.exe" /s /c ""msiexec" /I "c:\salt\var\cache\salt\minion\extrn_files\base\dl.google.com\edgedl\chrome\install\Goog
leChromeStandaloneEnterprise.msi" ALLUSERS=1 /qn /norestart"' in directory 'c:\salt\var\cache\salt\minion\extrn_files\base\dl.google.com\edgedl\chrome\install'
local:
    ----------
    chrome:
        ----------
        new:
            67.138.32849
        old:
            71.0.3578.98  # I suspect the retail version maybe ahead of the enterprise version.
```
Here is the sls definition
```
chrome:
  latest:
    full_name: 'Google Chrome'
    installer: 'https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi'
    install_flags: '/qn /norestart'
    uninstaller: 'https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
```

**Comment by damon-atkins** [comment]
Current if the software is installed no action is taken unless you specify a version or specify  latest. This is by design.  

The following is the correct and expected behavior on windows.
```
C:\salt>salt-call --version
salt-call 2018.3.2 (Oxygen)
C:\salt>salt-call -l info pkg.version chrome
local:
    71.0.3578.98
```

This is the correct output for No Change. When using **states**, the "pkg state" puts some more words around it. These are direct commands to the pkg module.
```
C:\salt>salt-call -l info pkg.install chrome  # call "module" pkg.install, this is what pkg.installed calls 
local:
    ----------

C:\salt>salt-call -l info state.single pkg.installed name=chrome  # call "state" pkg.installed
[INFO    ] state.call Running state [chrome] at time 03:30:19.833747
[INFO    ] state.call Executing state pkg.installed for [chrome]
[INFO    ] win_pkg.refresh_db Removing all *.sls files under 'c:\salt\var\cache\salt\minion\files\base\win\repo-ng'l
[INFO    ] win_pkg.refresh_db Fetching *.sls files from salt://win/repo-ng/
[INFO    ] fileclient.cache_dir Caching directory 'win/repo-ng/' for environment 'base'
[INFO    ] fileclient.get_file Fetching file from saltenv 'base', ** done ** 'win/repo-ng/chrome.sls'
[INFO    ] fileclient.get_file Fetching file from saltenv 'base', ** done ** 'win/repo-ng/swpd/winscp.sls'
[INFO    ] state.format_log All specified packages are already installed
[INFO    ] state.call Completed state [chrome] at time 03:30:27.438648 (duration_in_ms=7604.901)
local:
----------
          ID: chrome
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
    Duration: 7604.901 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   7.605 s
```

As SLS Pkg definition file contains latest as a version, download and install the software as there is no other way too ensure the latest software is installed. Note until the software (latest) is installed you can not determine its version.
```
C:\salt>salt-call -l info pkg.install chrome version=latest
[INFO    ] cmdmod._run Executing command '"C:\WINDOWS\system32\cmd.exe" /s /c ""msiexec" /I "c:\salt\var\cache\salt\minion\extrn_files\base\dl.google.com\edgedl\chrome\install\Goog
leChromeStandaloneEnterprise.msi" ALLUSERS=1 /qn /norestart"' in directory 'c:\salt\var\cache\salt\minion\extrn_files\base\dl.google.com\edgedl\chrome\install'
local:
    ----------
    chrome:
        ----------
        new:
            67.138.32849
        old:
            71.0.3578.98  # I suspect the retail version maybe ahead of the enterprise version.
```
Here is the sls definition
```
chrome:
  latest:
    full_name: 'Google Chrome'
    installer: 'https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi'
    install_flags: '/qn /norestart'
    uninstaller: 'https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
```
This is design to prevent an endless loop of installs every-time the state is run. Which you can still have by using pkg.latest i.e. `salt-call -l info state.single pkg.latest name=chrome` will download and install on every run. 

So specific to states with the "latest" listed as a available version.
```
C:\salt>salt-call -l info pkg.list_available chrome
local:
    - latest
```
Use "installed" if you want to ensure any version is installed.
Use "latest" if you want latest version downloaded every-time to be installed
