### ISSUE TITLE
Using the salt.runner state in a masterless configuration

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#51480]
### Description of Issue/Question
I'm trying to synchronize the master modules by using `salt-call` in a masterless-type setup (using `--local`). To synchronize the modules, I'm using a state and `salt.runner` to do this. I've tried a couple different combinations of things and yet none of them work unless I switch out of a masterless setup and back to the normal way of doing things.

What happens (when I use the configuration in the next section) is that none of the modules get synchronized. There's no related error messages or anything, and it simply seems as-if the files don't exist. However, if i use `salt-call --local cp.get_file` to try and read the files, they copy/transfer without issue, and `cp.get_dir` even transfers the target directory.

However, one thing that seems interesting is that if I set the saltenv to "base" at the commandline, and place the module files under "/srv/salt" everything seems to work as one would expect (despite the environment and "file root" not even being defined in the masterless configuration). Again, once they're changed back to the configuration below, then none of the module files get listed and thus cached.

Is it possible (or was it intended to be possible) to use this module (`salt.runner`) when in a masterless configuration or do I need to find some different method to accomplish this? Do I need to copy files directly into the extmods directory(?).

### Setup
Drop some python modules into a module directory (`_modules`, `_returners`, `_utils`, etc) in one of the file roots specified in the configuration. This way there's some modules for the runner to synchronize.

State looks like:
```
Synchronize all modules for the master:
    salt.runner:
        - name: saltutil.sync_all
```

Relevent config in /etc/salt/minion is as follows. The issue manifests itself when the default environment is something other than "base", and the paths under the environment for `file_roots` and `pillar_roots` is something other than the default ("/srv/salt").

```
conf_file: /etc/salt/minion
log_level: info
root_dir: /

use_superseded:
    - module.run

saltenv: somename
pillarenv: somename

file_client: local
fileserver_backend:
    - roots

file_roots:
    somename:
        - /srv/notdefault
pillar_roots:
    somename:
        - /srv/notdefault
```

### Steps to Reproduce Issue
`$ salt-call --local state.apply targetstate`

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Oct 15 2018, 15:26:09)
   python-gnupg: Not Installed
         PyYAML: 4.2
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.0.2
            ZMQ: 4.1.6

System Versions:
           dist: fedora 29 Twenty Nine
         locale: UTF-8
        machine: x86_64
        release: 4.14.96-coreos
         system: Linux
        version: Fedora 29 Twenty Nine
```

**Comment by Ch3LL** [comment]
runners are only meant to run on the master.

You can try this;

```
load_my_custom_module:
  module.run:
    - name: saltutil.sync_all
    - refresh: True
```

to note this will not supply idempotent behavior.
