### ISSUE TITLE
Bug in salt.states.archive with windows up- and lowercase letter

### ISSUE THREAD

**Issue by scheste** [saltstack/salt#51486]
I have found an up- and lowercase letter bug in Salt 2018.3.3 with Windows (Server 2016 and Windows 10).

I use the archive.extracted function to extract a zip archive to a specific path.

```
extract_sysinternals:
  archive.extracted:
    - name: 'C:/Tools/Sysinternals/'
    - source: salt://tools/files/SysinternalsSuite_18_12_2018.zip
    - enforce_toplevel: False
    - extract_perms: False
```

The first letter of the Tools and Sysinternals folders should be to a uppercase letter, but salt creates the folder with a lowercase letter.

It`s only a cosmetic bug, but in but in very rare cases problematic.
