### ISSUE TITLE
git execution module cannot be loaded

### ISSUE THREAD

**Issue by gitbrianb** [saltstack/salt#51497]
### Description of Issue/Question
I'm new to using Git, but after following through what I believe should work with current online documentation, I keep getting this error when using the command below:

Not sure if it matters, but I'm attempting to do this work on a Windows minion. Also, do I have to have the Git software installed on the minion for this to work or can I just use the configuration on the Salt Master to push files to the Windows minions? I've attempted both sides to no avail, just curious.

Command:
```
salt '*' git.clone 'C:\temp' ssh://git@github.com/pqdev/PI2-DST-GSK.git
```

Error:
```
'git' __virtual__ returned False: The git execution module cannot be loaded: git unavailable.
```

I have my public key stored in the following location:
```
/root/.ssh/authorized_keys
```
And my private key in this location:
For the SSH client in testing:
```
/root/.ssh/id_rsa
```
But also referenced in the /etc/salt/master configuration as a copy of the private key in this location:
```
/opt/salt/github.key
```

### Setup
Relevant pieces of /etc/salt/master configuration file:
```
fileserver_backend:
  - roots
  - gitfs
gitfs_provider: pygit2
gitfs_pubkey: '/root/.ssh/authorized_keys'
gitfs_privkey: '/opt/salt/github.key'

gitfs_remotes:
  - ssh://git@github.com/pqdev/PI2-DST-GSK.git
  - ssh://git@github.com/pqdev/PI2-PQD-Importer.git
```

Attempted to use Salt state files as well, to no success, with this configuration:
```
clone_gitrepo:
  pkg.installed:
    - name: git
  git.clone:
    - cwd: 'C:\Temp'
    - repository: ssh://git@github.com/pqdev/PI2-DST-GSK.git
```

### Steps to Reproduce Issue
CLI to apply state:
```
salt '*' state.apply web/gitdeploy
```

Fails with this error:
```
          ID: clone_gitrepo
    Function: git.clone
      Result: False
     Comment: State 'git.clone' was not found in SLS 'web/gitdeploy'
              Reason: 'git' __virtual__ returned False
     Changes:
```
CLI to test without state option:
```
salt '*' git.clone 'C:\temp' ssh://git@github.com/pqdev/PI2-DST-GSK.git
```

Fails with this error:
```
    'git' __virtual__ returned False: The git execution module cannot be loaded: git unavailable.
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```
