### ISSUE TITLE
states/boto3_route53.py fails to validate ALIAS (A) records

### ISSUE THREAD

**Issue by martin-paulus** [saltstack/salt#51501]
### Description of Issue/Question
When running a boto3_route53.rr_present state specifying an ALIAS record (A-record referring to an AWS entity), the initial creation of a new record succeeds. However, the validation of an existing ALIAS record fails.

### Setup
SaltStack release 2018.3.2: salt/states/boto3_route53.py

### Steps to Reproduce Issue

```
create custom record for an S3 bucket:
  boto3_route53.rr_present:
    - AliasTarget:
        DNSName: s3-website-eu-west-1.amazonaws.com.
        EvaluateTargetHealth: False
        HostedZoneId: Z1BKCTXD74EZPE
    - DomainName: example.net
    - name: public.example.net
    - region: eu-west-1
    - Type: A
```

**Results in**:

```
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/boto3_route53.py", line 684, in rr_present
                  if ResourceRecords != sorted(rrset.get('ResourceRecords'), key=lambda x: x['Value']):
              TypeError: 'NoneType' object is not iterable
```

Explanation: For an ALIAS (A) record, the ResourceRecords property is absent from the response.

### Versions Report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
