### ISSUE TITLE
Getting State 'Sentinel_install' in SLS 'Install@ is not formed as a list

### ISSUE THREAD

**Issue by dfoley84** [saltstack/salt#51535]
```
Sentinel_Install:
  '2.7.4':
      installer: 'salt://sentinel/SentinelOne-windows-Denali_windows_v2_7_4_6510.exe'
      full_name: SentinelOne  
      install_flags: 'SITE_TOKEN=<KEY> /Q'
      reboot: True
      uninstaller: 'salt://sentinel/SentinelOne-windows-Denali_windows_v2_7_4_6510.exe'
```
