### ISSUE TITLE
smtp.send_msg is returning a false minion 

### ISSUE THREAD

**Issue by juthewiz** [saltstack/salt#51602]
When runring `sudo salt * smtp.send_msg` from the cli and i am getting a false return. on the minion in /etc/salt/minion.d/ i have a smtp.conf file with my smtp profile. so i am not sure what i could be missing here  
```
saltmaster% sudo salt 'saltminion*' smtp.send_msg 'dest@email.com' 'This is an automated message from Netops. Triggered at {{ salt.system.get_system_time() }}' subject='Test' profile='my_smtp_profile'
saltminion1:
    False
```
the only thing i can find when running with -l debug are
`[DEBUG   ] Passing on saltutil error. Key 'u'retcode' missing from client return. This may be an error in the client.`
and
`[DEBUG   ] return event: {u'saltminion1': {u'jid': u'20190212093030619799', u'retcode': 0, u'ret': False}}
`
```
 /etc/salt/minion.d/smtp.conf
my_smtp_profile:
    smtp.sender:  me@email.com
    smtp.server: smtp.office365.com
    smtp.tls: false
    smtp.username: me
    smtp.password: password

```

 salt --versions-report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-124-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by juthewiz** [comment]
when i trigger this behavior via reactor here is what is seen via event bus
the first reactor listed works (slack)
```
reactor:
  - 'salt/engines/hook/sj1-e1-re0_xe-0/0/0_Up':
    - /srv/salt/reactor/react_to_sj1sg1_1_up.sls
    - /srv/salt/reactor/email_sj1sg1primaryvendor.sls
```


```
/srv/salt/reactor/email_sj1sg1primaryvendor.sls
send_email:
  local.smtp.send_msg:
    - tgt: saltminion1
    - arg:
        - 'email@email.com'
        - name: 'This is an automated message from NetOps.'
        -  subject='Test'

```


```
salt/job/20190212101255635419/ret/saltminion   {
    "_stamp": "2019-02-12T18:12:55.760116",
    "cmd": "_return",
    "fun": "smtp.send_msg",
    "fun_args": [
        "email@email.com, email@email.com",
        {
            "name": "This is an automated message from NetOps."
        },
        "subject='Test'"
    ],
    "id": "saltminion1",
    "jid": "20190212101255635419",
    "out": "nested",
    "return": "The minion function caused an exception: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/salt/minion.py\", line 1607, in _thread_return\n    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n  File \"/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py\", line 12, in execute\n    return func(*args, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/salt/modules/smtp.py\", line 101, in send_msg\n    msg = email.mime.text.MIMEText(message)\n  File \"/usr/lib/python2.7/email/mime/text.py\", line 30, in __init__\n    self.set_payload(_text, _charset)\n  File \"/usr/lib/python2.7/email/message.py\", line 226, in set_payload\n    self.set_charset(charset)\n  File \"/usr/lib/python2.7/email/message.py\", line 268, in set_charset\n    cte(self)\n  File \"/usr/lib/python2.7/email/encoders.py\", line 73, in encode_7or8bit\n    orig.encode('ascii')\nAttributeError: 'dict' object has no attribute 'encode'\n",
    "success": false
```

**Comment by Ch3LL** [comment]
this part of your reactor state: `        - name: 'This is an automated message from NetOps.'` is most likely being interpreted as a dictionary instead of an arg. So if you need to include `name:` in your message you will need to quote or escape that so its not interpreted as such

also `       -  subject='Test'` needs to be passed via `args` or `kwargs` not `arg`. See this example from the docs:

```
install_zsh:
  local.state.single:
    - tgt: 'kernel:Linux'
    - tgt_type: grain
    - arg:
      - pkg.installed
      - zsh
    - kwarg:
        fromrepo: updates
```

To comment on your initial issue, it looks like every part of that module where it returns  False it should be logging useful information on the debug level on the minion. Is there any relevant information in the minion debug log when you run the execution module?
