### ISSUE TITLE
nftables returning success when rule not added

### ISSUE THREAD

**Issue by antifob** [saltstack/salt#51641]
### Description of Issue/Question

The nftables state wrongly return success when a rule isn't added.

### Setup

1. On Ubuntu 18.04 LTS, install `nftables` and flush the ruleset: `apt-get install nftables && nft flush ruleset`.
2. Apply the below  state.
3. List the ruleset (`nft list ruleset`) and see that it's empty even though the `nftables` module indicate a change.
4. Execute the following to add the `ipv4` table and `output` chain: `nft add table ip filter && nft add chain ip filter output { type filter hook output priority 0 \; }`.
5. Apply the below state.
6. Confirm the rule is present with `nft list ruleset`
7. Apply the below state.
8. Confirm the rule is duplicated using `nft list ruleset`

```
# top.sls
base:
    '*':
        - nft

# nft.sls
simple:
    nftables.append:
        - family: ip
        - table: filter
        - chain: output
        - proto: tcp
        - dport: 22
        - jump: accept
```

### Versions Report

`2018.3.3`

Note: the above steps also serve to demonstrate #51483
