### ISSUE TITLE
Create cron job every RANDOM minutes from a range of numbers without applying the state with every run

### ISSUE THREAD

**Issue by piersf** [saltstack/salt#51659]
Currently, there's the ability to create a cron job that runs every RANDOM minutes/hours/days/months if you specify `random` in the respective field:
```
/usr/sbin/rhn_check > /dev/null 2>&1:
cron.present:
- user: root
- minute: RANDOM
```

This works fine and it will create a cronjob entry that will run every RANDOM minutes, starting from 1 until 59. The way I understand this, is that the state won't be applied with every run because the `random` functionality checks the cron entry for a numeric value and if it sees one, it won't re-apply the state. So far so good.

However, we have the need to create a cronjob every RANDOM minutes from a range of minutes. I am currently doing this:

```
/usr/sbin/rhn_check > /dev/null 2>&1:
  cron.present:
    - user: root
    - minute: '*/{{ range(10,20) | random }}'
```

This gets applied successfully and a cronjob will be created with the `minute` entry set randomly between 10 and 20. This state, however, gets applied every time. I think that happens because now there's no more a numeric value in the `minute` field since we add the '*/' part to it.

But setting `- minute: '{{ range(10,20) | random }}'` has the same effect and it gets applied with every run. I would think that this would work because there will only be a numeric value.

Is there a way to achieve this? That is, setting the RANDOM cron minute/hour/day/month field from a range of numbers without the state getting applied with every run?

### Versions Report
`salt 2018.3.3 (Oxygen)`

Thanks,

**Comment by dwoz** [comment]
@piersf I am not aware of a way to accomplish this. Maybe @terminalmage has some insight?

**Comment by mgriffin13** [comment]
I actually ran into the same problem question last week, only we were looking to randomize the hour.

Looks like there's an [undocumented feature](https://github.com/saltstack/salt/blob/develop/salt/modules/cron.py#L503) where you can pass a string range like '10:20' that will randomize inside that range.

I think a solution would be to make this a documented feature and to make it behave in a similar fashion to how the ``random`` keyword works.

**Comment by piersf** [comment]
@mgriffin13 thanks for the reply. Unfortunately, the suggestion you made is not working - the state gets re-applied still. Furthermore, by setting `'10:20'` will create a cron entry like :
`17 * * * * /script` and not like `*/17 * * * * /script`

**Comment by mchugh19** [comment]
In running into a similar issue, I created #45709 allowing for generation of random numbers from a seed. You may be running into an issue that the random number is regenerated on every highstate, and thus the cronjob always gets modified with a new random number value. By using a seed you can randomize based on some value (hostname perhaps) which doesn't change.

In our case, it looked something like:
```
{% set cron1 = salt['random.rand_int'](1, 19, seed=datafile) %}
{% set cron2 = cron1 + 20 %}
{% set cron3 = cron1 + 40 %}
{{ datafile }}-cron:
  cron.present:
    - name: {{scripts_dir}}/common/script.pl --sourceName {{ datafile }} > /dev/null 2>&1
    - identifier: {{ datafile }}
    - user: scriptrunner
    - minute: {{ cron1 }},{{ cron2 }},{{ cron3 }}
```

In this case, we generated a cron entry for each datafile. A random number was generated from each datafile name, and thus would always be consistent for that single instance, but allow for a spread of values across the specified range.

**Comment by piersf** [comment]
Thank you @mchugh19 !

This helped me solve the issue.

Since i don't need to declare variables like in the example above, i ended up with the below, for anyone else wanting something similar:

```
my_script:
  cron.present:
    - name: /path/to/script.sh | /usr/bin/logger -t my_script_output
    - user: root
    - comment: Invoke my script
    - identifier: invoke_my_script
    - minute: '*/{{ salt['random.rand_int'](10, 20, seed='/another/state_id/for/file') }}' # this keeps the random generated number fixed between highstate's
    - require:
      - file: /another/state_id/for/file
```
I am closing this issue since the answer above provides a solution.

Thank you
