### ISSUE TITLE
minion.d/_schedule.conf contains outdated keys

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#51653]
### Steps

Save to minion.d/schedule.conf:
```
schedule:
  schedule_heartbeat_conf:
    function: event.send
    job_args:
    - 'heartbeat'
    seconds: 10
    splay:
      start: 5
      end: 15
    return_job: False
    run_on_start: False
    maxrunning: 1
```
Then use minutes instead of seconds, save to minion.d/schedule.conf:
```
schedule:
  schedule_heartbeat_conf:
    function: event.send
    job_args:
    - 'heartbeat'
    minutes: 1
    splay:
      start: 5
      end: 15
    return_job: False
    run_on_start: False
    maxrunning: 1
```

Then save the original (no 1 minute, but 10 seconds)

Still the scheduler was on a 1 minute interval.

I finally realized that you see both minutes and seconds in _schedule.conf 

```
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false}
  schedule_heartbeat_conf:
    args: [heartbeat]
    enabled: true
    function: event.send
    jid_include: false
    job_args: [heartbeat]
    maxrunning: 1
    minutes: 1
    return_job: false
    run_on_start: false
    seconds: 10
    splay: {end: 15, start: 5}

```

The minutes should no longer be there.

In _schedule.conf you also see args, which is no longer  is in schedule.conf
This is the only reason why the event.send worked for me, because it requires args, not job_args.

If you save schedule.conf as above, you will get errors in minion log.

Problem: _schedule.conf collects all historic keys, it contains outdated keys.

Both server and client version 2018.3.3
