### ISSUE TITLE
Inconsistent location of repos in aptpkg module

### ISSUE THREAD

**Issue by onlyanegg** [saltstack/salt#51656]
### Description of Issue/Question

The aptpkg execution module doesn't locate repos consistently. `get_repo()` compares `rstrip('/')`ed versions of the uri, whereas `del_repo()` doesn't. This leads to confusing behavior where `get_repo()` will find a repo, but `del_repo()` wont be able to delete it. It also causes the `pkgrepo.absent` state to fail in certain cases.

### Setup

```yaml
# test.sls
datadog_package_repo_managed:
  pkgrepo.managed:
    - name: deb https://apt.datadoghq.com/ main 6
    - humanname: "Datadog, Inc."
    - keyserver: keyserver.ubuntu.com
    - keyid: 382E94DE

datadog_package_repo_uninstalled:                                                            
  pkgrepo.absent:                                                                            
    - name: deb https://apt.datadoghq.com/ main 6                                             
```

### Steps to Reproduce Issue

```
root@94fba8b9b5d7:/# salt-call state.apply test
[ERROR   ] Repo deb https://apt.datadoghq.com/ stable 6 doesn't exist in the sources.list(s)
local:
----------
          ID: datadog_package_repo_managed
    Function: pkgrepo.managed
        Name: deb https://apt.datadoghq.com/ stable 6
      Result: True
     Comment: Configured package repo 'deb https://apt.datadoghq.com/ stable 6'
     Started: 22:05:02.539044
    Duration: 2059.026 ms
     Changes:
              ----------
              repo:
                  deb https://apt.datadoghq.com stable 6
----------
          ID: datadog_package_repo_uninstalled
    Function: pkgrepo.absent
        Name: deb https://apt.datadoghq.com/ stable 6
      Result: False
     Comment: Repo deb https://apt.datadoghq.com/ stable 6 doesn't exist in the sources.list(s)
     Started: 22:05:04.598347
    Duration: 76.254 ms
     Changes:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
Total run time:   2.135 s
```

### Versions Report

Running in masterless mode

```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.125-linuxkit
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by onlyanegg** [comment]
Here's a small changeset that fixes my issue. I'm not sure if this is how we should fix it, but I'm happy to create a PR if that's what y'all decide.

```diff
$ git diff aptpkg.py
diff --git a/salt/modules/aptpkg.py b/salt/modules/aptpkg.py
index 608ff0f51d..6e1bb23871 100644
--- a/salt/modules/aptpkg.py
+++ b/salt/modules/aptpkg.py
@@ -1753,7 +1753,7 @@ def del_repo(repo, **kwargs):
             )

         for source in repos:
-            if (source.type == repo_type and source.uri == repo_uri and
+            if (source.type == repo_type and source.uri.rstrip('/') == repo_uri.rstrip('/') and
                     source.dist == repo_dist):

                 s_comps = set(source.comps)
@@ -1770,7 +1770,7 @@ def del_repo(repo, **kwargs):
             # doesn't always reflect this.  Lets just cleanup here for good
             # measure
             if (is_ppa and repo_type == 'deb' and source.type == 'deb-src' and
-                    source.uri == repo_uri and source.dist == repo_dist):
+                    source.uri.rstrip('/') == repo_uri.rstrip('/') and source.dist == repo_dist):

                 s_comps = set(source.comps)
                 r_comps = set(repo_comps)
```

**Comment by garethgreenaway** [comment]
@onlyanegg Thanks for the report.  If add_repo is doing an rstrip on the URL, then it probably makes sense for del_repo to do the same.  I'm thinking we should make sure these are consistent, @saltstack/team-core thoughts?

**Comment by terminalmage** [comment]
I agree.

**Comment by javierbertoli** [comment]
I hit this is issue today while working on [the docker-formula](https://github.com/saltstack-formulas/docker-formula/pull/312), using salt version 3004:
```
# salt-call --versions
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: 4.1.0
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-10-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```

Way to reproduce the error:

1. create the repository with the following sls file
```yaml
       docker-software-package-repo-managed:
         pkgrepo.managed:
           - comments: ['installed by salt']
           - enabled: 1
           - file: /etc/apt/sources.list.d/docker.list
           - gpgcheck: 1
           - name: deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg arch=amd64] https://download.docker.com/linux/debian bullseye stable
           - humanname: Debian Bullseye Docker Package Repository
           - refresh: True
```
2. After running the state, the file `/etc/apt/sources.list.d/docker.list` will be created with the following content
```
deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg arch=amd64] https://download.docker.com/linux/debian bullseye stable
```
3. `get_repo` will be able to find it correctly:
```
# salt-call --local pkg.get_repo 'deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg arch=amd64] https://download.docker.com/linux/debian bullseye stable'
local:
    ----------
    architectures:
        - amd64
    comps:
        - stable
    disabled:
        False
    dist:
        bullseye
    file:
        /etc/apt/sources.list.d/docker.list
    line:
        deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg arch=amd64] https://download.docker.com/linux/debian bullseye stable
    type:
        deb
    uri:
        https://download.docker.com/linux/debian
```
4. `del_repo` is unable to find the entry and delete it
```
# salt-call --local pkg.del_repo 'deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg arch=amd64] https://download.docker.com/linux/debian bullseye stable'
Error running 'pkg.del_repo': Repo deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg arch=amd64] https://download.docker.com/linux/debian bullseye stable doesn't exist in the sources.list(s)
```
