### ISSUE TITLE
Execution order of reactors and orchestrates

### ISSUE THREAD

**Issue by dpizzle** [saltstack/salt#51663]
### Description of Issue/Question

In this scenario, I have 3 reactors that should run in sequential order when a `napalm/syslog/junos/OSPF_NEIGHBOR_DOWN/<device>` message is received in the salt event bus. When the next `napalm/syslog/junos/OSPF_NEIGHBOR_DOWN/<device>` message is received from another network device it should run after the first has completed as state is being maintained in a common database, which is being updated. What I've seen is the `salt/run/<jid>/new` jobs go into the salt event bus in a non-sequential order and `/ret` responses also come back in a non-sequential order. When two `napalm/syslog/junos/OSPF_NEIGHBOR_DOWN/<device>` messages are received very close together, the below tasks can get intertwined between the two devices.

### Setup

```yaml
reactor:
  - 'napalm/syslog/junos/*/*':
    - salt://reactor/register_host_in_db.sls
    - salt://reactor/register_event_in_db.sls

  - 'napalm/syslog/junos/OSPF_NEIGHBOR_DOWN/*':
    - salt://reactor/ospf_neighbor_down.sls
```
```yaml
# cat reactor/register_host_in_db.sls
register host in db:
  runner.state.orchestrate:
    - args:
      - mods: orchestrate.register_host_in_db
      - pillar:
          data: {{ data|json }}
```
```yaml
# cat reactor/register_event_in_db.sls
register_event_in_db:
  runner.state.orchestrate:
    - args:
      - mods: orchestrate.register_event_in_db
      - pillar:
          data: {{ data|json }}
```
```yaml
# cat reactor/ospf_neighbor_down.sls
ospf_neighbor_down:
  runner.state.orchestrate:
    - args:
      - mods: orchestrate.ospf_neighbor_down
      - pillar:
          data: {{ data|json }}
```

### Steps to Reproduce Issue

The below filtered output from the salt event bus shows the order in which the orchestrate tasks are run. I ran two test and both have a different order.

```bash
: docker-compose exec master salt-run state.event pretty=true  | grep "napalm/syslog|salt/run|mods"
napalm/syslog/junos/OSPF_NEIGHBOR_DOWN/vsrx01        {
salt/run/20190215112953383079/new       {
            "mods": "orchestrate.register_host_in_db",
salt/run/20190215112953474319/new       {
            "mods": "orchestrate.ospf_neighbor_down",
salt/run/20190215112953535790/new       {
            "mods": "orchestrate.register_event_in_db",
salt/run/20190215112953383079/ret       {
            "mods": "orchestrate.register_host_in_db",
salt/run/20190215112953535790/ret       {
            "mods": "orchestrate.register_event_in_db",
salt/run/20190215112953474319/ret       {
            "mods": "orchestrate.ospf_neighbor_down",

napalm/syslog/junos/OSPF_NEIGHBOR_DOWN/vsrx01        {
salt/run/20190215113044976110/new       {
            "mods": "orchestrate.ospf_neighbor_down",
salt/run/20190215113044991942/new       {
            "mods": "orchestrate.register_host_in_db",
salt/run/20190215113045043574/new       {
            "mods": "orchestrate.register_event_in_db",
salt/run/20190215113045043574/ret       {
            "mods": "orchestrate.register_event_in_db",
salt/run/20190215113044991942/ret       {
            "mods": "orchestrate.register_host_in_db",
salt/run/20190215113044976110/ret       {
            "mods": "orchestrate.ospf_neighbor_down",
```

### Versions Report

```bash
Salt Version:
           Salt: 2019.2.0rc2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 24 2018, 05:04:18)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: Not Installed
```
