### ISSUE TITLE
Help calling runner.queue.insert_runner from a reactor

### ISSUE THREAD

**Issue by dpizzle** [saltstack/salt#51683]
### Description of Issue/Question

I have a reactor that called an orchestrate file. I want to covert that, so the reactor puts that orchestrate file into a queue, to be triggered later using a scheduler. I'm having trouble with the documentation (https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.queue.html).

### Setup

Previous (reactor calling an orchestrate file) -

```
ospf_neighbor_down:
  runner.state.orchestrate:
    - args:
      - mods: orchestrate.ospf_neighbor_down
      - pillar:
          data: {{ data|json }}
```

Current (reactor calling a queue.insert_runner) -

```
ospf_neighbor_down_q:
  runner.queue.insert_runner:
    - fun: state.orchestrate
    - kwargs:
        mods: orchestrate.ospf_neighbor_down
        pillar:
          data: {{ data|json }}
    - queue: runners
    - backend: sqlite
```

### Steps to Reproduce Issue

When I trigger the reactor from a napalm_log event I notice that the `fun` is not visible on the event bus and therefore not added to the sqlite backend. Instead `queue.insert_runner` is added under `fun_args` rather than `state.orchestrate`.

```
salt/run/20190216155303199443/new {
    "_stamp": "2019-02-16T15:53:03.205576",
    "fun": "runner.queue.insert_runner",
    "fun_args": [
        "queue.insert_runner",
        {
            "args": null,
            "backend": "sqlite",
            "kwargs": {
                "mods": "orchestrate.ospf_neighbor_down",
                "pillar": {
                    "data": {
```
```
- {'fun': 'queue.insert_runner', 'args': [], 'kwargs': {'mods': 'orchestrate.ospf_neighbor_down', 'pillar': {'data': {'error': 'OSPF_NEIGHBOR_DOWN ...
```

However, from the master, when I call the `queue.insert_runner` runner, I see it correctly in the event bus and in the sqlite backend.

```
/ # salt-run queue.insert_runner state.orchestrate kwargs='{"mods": "orchestrate.ospf_neighbor_down", "pillar": {"data": {"_stamp": "2019-02-16T15:53:02.197703", "error": "OSPF_NEIGHBOR_DOWN", "facility": 3, "host": "vsrx01", "ip": "1.1.1.1", "message_details": {"date": "Jan 7", "facility": 3, "host": "vsrx01", "hostPrefix": null, "message": "OSPF neighbor 10.1.1.2 (realm ospf-v2 ge-0/0/0.0 area 0.0.0.0) state changed from Full to Down due to KillNbr (event reason: interface went down)", "pri": "29", "processId": "123", "processName": "rpd", "severity": 5, "tag": "RPD_OSPF_NBRDOWN", "time": "13:58:40"}, "os": "junos", "severity": 5, "timestamp": 1546869520, "yang_message": {"network-instances": {"network-instance": {"global": {"protocols": {"protocol": {"ospf": {"ospfv2": {"areas": {"area": {"0.0.0.0": {"interfaces": {"interface": {"ge-0/0/0.0": {"neighbors": {"neighbor": {"10.1.1.2": {"state": {"adjacency-state": "DOWN", "adjacency-state-change-reason": "KILL_NEIGHBOR", "adjacency-state-change-reason-message": "interface went down"}}}}}}}}}}}}}}}}}}, "yang_model": "openconfig-ospf"}}}' queue=runners backend=sqlite
```
```
salt/run/20190216155521356640/new {
    "_stamp": "2019-02-16T15:55:28.561016",
    "fun": "runner.queue.insert_runner",
    "fun_args": [
        "state.orchestrate",
        {
            "backend": "sqlite",
            "kwargs": {
                "mods": "orchestrate.ospf_neighbor_down",
                "pillar": {
                    "data": {
```
```
- {'fun': 'state.orchestrate', 'args': [], 'kwargs': {'mods': 'orchestrate.ospf_neighbor_down', 'pillar': {'data': {'error': 'OSPF_NEIGHBOR_DOWN ...
```
### Versions Report

```
Salt Version:
           Salt: 2019.2.0rc2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 24 2018, 05:04:18)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: Not Installed
```

**Comment by gtmanfred** [comment]
Try with this reactor.

```
ospf_neighbor_down_q:
  runner.queue.insert_runner:
    - args:
        - fun: state.orchestrate
        - kwargs:
            mods: orchestrate.ospf_neighbor_down
            pillar:
              data: {{ data|json }}
        - queue: runners
        - backend: sqlite
```
