### ISSUE TITLE
salt.utils.chocolatey.version fails too hard when an installed package is unavailable (affects salt.states.chocolatey.installed)

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#51700]
### Description of Issue/Question
As of yesterday the Firefox chocolatey package is busted in some way that results in `choco list firefox` not finding anything. Not salt's fault or anything, but this results in `chocolatey.version` throwing an exception when `salt.states.installed` calls `salt.chocolatey.version` to check to see if there's a newer version available.

This is a problem because it results in an error that is only reproducable if the third party repository is busted in some way which prevents the `chocolatey.installed` state from being used.

### Setup
This could be hard to reproduce as you need a chocolatey package installed that is then suddenly not listable. As of right now (2019/02/18T05:21:00), the Firefox package is currently in this state. Specifically you'll need `choco list $PACKAGE` to be unable to list the package, but `choco version $PACKAGE` to be able to list it. (Package installed but either it is deprecated or not available by some other means).

```C:\ProgramData\chocolatey>choco list firefox
Chocolatey v0.10.11
0 packages found.

C:\ProgramData\chocolatey>choco list Firefox
Chocolatey v0.10.11
0 packages found.

C:\ProgramData\chocolatey>choco list | findstr /i firefox
Firefox 65.0.1 [Approved]
...
```
### Steps to Reproduce Issue
Once you get the specific conditions to occur (a package installed that is suddenly not available in the repository), then you can either create a state for `chocolatey.installed` with `name` set to your target package any apply it, or you can call `chocolatey.version` your package name specified directly and `check_remote` set to `true` which simulates the call that salt.states.chocolatey.installed makes to check the version:

```
$ salt $t chocolatey.version 'Firefox' check_remote=true
bX_nxPEVRyWOcIDBECwW:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\chocolatey.py", line 936, in version
        'available': available[pkg]}
    KeyError: u'firefox'
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 8
         system: Windows
        version: 8 6.2.9200 SP0 Multiprocessor Free
```
