### ISSUE TITLE
Can't delete or disable scheduled job from itself

### ISSUE THREAD

**Issue by sotona-** [saltstack/salt#51709]
### Description of Issue/Question
I have a state which schedules a job to a windows minion:
```app-update:
  schedule.present:
    - enabled: True
    - persist: True
    - function: state.sls
    - job_args:
      - install_app
    - minutes: 15
    - until: {{ "+1 week"|strftime("%m/%d/%Y %I:%M%p") }}
    - run_on_start: False
    - maxrunning: 1
    - jid_include: True
```

This state waiting until user closes application and tries to install  update. Last function in this state is 'schedule.absent' with name of scheduled job. But it's not working when state applied from scheduled job. If I apply it manually from master it's working.
I tried to use 'module.run' function with 'schedule.delete' argument, doesn't work. Also I tried to schedule second job wich kills first one, doesn't work too.

### Steps to Reproduce Issue
Create scheduled job which should run 'state.apply' with state which should delete this scheduled job

### Versions Report
master - salt 2018.3.3 py3 on Ubuntu 16.04
minion - salt 2018.3.3 py3 on Win 8.1

**Comment by garethgreenaway** [comment]
@sotona- Thanks for the report.  Can you provide the state file that you're calling from the above scheduled job?  And when you say it's not working, are you receiving any error messages or is the scheduled job simply not removed from the schedule?

**Comment by sotona-** [comment]
@garethgreenaway 
```
install_someapp:
  pkg.installed:
    - pkgs:
      - someapp-release
    - failhard: True

# I tried this
remove_scheduled_job:
  schedule.disabled:
    - name: myjob
# Or this
remove_job_two:
  module.run:
    - schedule.delete:
        - name: myjob
# Or this
remove_job:
  schedule.present:
    - enabled: True
    - function: schedule.delete
    - job_args: 
      - myjob
    - once: {{ "+1 minute"|strftime("%m/%d/%Y %I:%M%p") }}
    - maxrunning: 1
```

> And when you say it's not working, are you receiving any error messages or is the scheduled job simply not removed from the schedule?
Job is simply not removed.  But when I run state manually from master it removes the job.
