### ISSUE TITLE
docker.container_running network_mode does not work with ipv4_address or ipv6_address

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#51723]
### Description of Issue/Question

`docker.container_running state` does not use the supplied `ipv6_address` if a custom `network_mode` is used.

### Setup
```sls
mynet:
  docker_network.present:
    - enable_ipv6: True
    - ipam_pools:
      - subnet: 10.0.20.0/24
        gateway: 10.0.20.1
      - subnet: fe3f:2180:26:1::/64
        gateway: fe3f:2180:26:1::1

test:
  docker_container.running:
    - image: busybox:latest
    - rm: true
    - detach: True
    - command: sleep 60000
    - network_mode: mynet
    - networks:
      - mynet:
        - ipv4_address: 10.0.20.50
        - ipv6_address: fe3f:2180:26:1::50
```

### Steps to Reproduce Issue
Run the above state. Run docker inspect test and notice that the addresses for the mynet connection are not the requested addresses. This fails when specifying both ipv4 and ipv6 or just ipv4 or just ipv6.

If you do not specify `network_mode`, the requested address is assigned, but the container is attached to both `mynet` and the default `bridge` network.

### Versions Report
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 3.7.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 3.7.3
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Jan 10 2019, 23:20:52)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.20.8-arch1-1-ARCH
         system: Linux
        version: Not Installed
```
