### ISSUE TITLE
salt.modules.cloud.get_instance does not return existing instance 

### ISSUE THREAD

**Issue by jorisdejosselin** [saltstack/salt#51751]
### Description of Issue/Question

When using the cloud module for returning instance information from the deployed VM's with the libvirt provider it just returns "NONE". This also counts for salt.modules.cloud.has_instance which returns "False". But for the example I will only show the get_instance.

### Setup
KVM_provider:
```
local-kvm:
  driver: libvirt
  url: qemu:///system
  validate_xml: no
```
KVM_profile:
```
test_vm:
  provider: local-kvm
  base_domain: centos7.0
  ip_source: qemu-agent
  ssh_username: <>
  password: <>
```

### Steps to Reproduce Issue
salt 'master' cloud.profile test_vm test ; returns
```
master:
    ----------
    test:
        ----------
        deployed:
            True
```
salt 'master' cloud.full_query ; returns
```
test:
                ----------
                id:
                    2ebdcde7-8a94-4e08-bde5-99ac46cb96e8
                image:
                private_ips:
                public_ips:
                size:
                state:
                    running
```
salt 'master' cloud.get_instance test ; returns
```
master:
    None
```

### Versions Report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.4
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.4
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.1
         Python: 2.7.15+ (default, Oct  2 2018, 22:12:08)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.0
           RAET: Not Installed
          smmap: 2.0.4
        timelib: Not Installed
        Tornado: 5.0.2
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.10 cosmic
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-15-generic
         system: Linux
        version: Ubuntu 18.10 cosmic
