### ISSUE TITLE
Unable to use salt-formula with saltenvs

### ISSUE THREAD

**Issue by bluemalkin** [saltstack/salt#51755]
### Description of Issue/Question
I'm unable to use salt-formulas in my salt environments.

### Setup
```
cat /etc/salt/master
timeout: 120
autosign_file: /etc/salt/autosign.conf
file_roots:
  base:
    - /srv/salt
  ops:
    - /srv/salt/ops
  dev:
    - /srv/salt/dev
  stg:
    - /srv/salt/stg
  prd:
    - /srv/salt/prd
fileserver_backend:
  - gitfs
  - roots
gitfs_provider: gitpython
#gitfs_update_interval: 60
gitfs_remotes:
  - https://github.com/salt-formulas/salt-formula-nginx.git:
    - all_saltenvs: master

state_verbose: False
auto_accept: False
top_file_merging_strategy: merge_all
```

### Steps to Reproduce Issue
```
salt xx.opsxx' state.apply test=True
xx.ops.xx:
    Data failed to compile:
----------
    Specified SLS nginx in saltenv ops is not available on the salt master or through a configured fileserver
```

### Versions Report
```
 salt --versions-report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 1.10.6
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-78-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
