### ISSUE TITLE
state id reference with state render 

### ISSUE THREAD

**Issue by Maunty** [saltstack/salt#51760]
### Description of Issue/Question
Is there any way to make logical links between salt.state.id and rendering in templates. I try to render several config files  from 1 template for multiple daemon instances on one minion. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

as workaround i use state.environ like this 

----pillar.file ----

```yaml
redis:
  instance:
     - one
     - two
     - three
  config:
     one:
         < some config >
     two:
         < another complex config >
     three:
         < pseudo config >
```

---- state.file ----
```jinja
{% from "redis/map.jinja" import redis with context %}
{% for instance in salt['pillar.get']('redis:instance') %}
{{ redis.pkg }}.{{ instance }}.config:
  environ.setenv:
    - name: redis_instance
    - value: {{ instance }}
    - update_minion: True
  file.managed:
    - name: /etc/redis/{{ instance }}.conf
    - source: 
      - salt://files/redis/{{ salt['grains.get']('id') }}/{{ instance }}.conf # if u allready have an config u can use it 
      - salt://redis/files/default.conf
    - template: jinja
{{ redis.pkg }}.{{ instance }}.remove.environ:
  environ.setenv:
    - name: redis_instance
    - value: False
    - false_unsets: True
    - update_minion: True
{% endfor %}
```

but i dont realy like this way. first of all comand : 
salt '*' state.apply somestate **test=True** 
gives wrong result
