### ISSUE TITLE
salt function output in orchestrate run

### ISSUE THREAD

**Issue by xdkms** [saltstack/salt#51794]
### Description of Issue/Question
**Question:**
I am trying to react to a webhook event by adding a user on a minion. If adding the user failed, I want to send the error message to an external system (this has to happen on the master). I could not find a smart way to do this.

I'm a noob so any input is welcome

### Setup
How I would like it to work:

**reactor/add_user.sls**
```
invoke_orchestrate:
  runner.state.orchestrate:
    - args:
        - mods: orchestrate.add_user
        - pillar:
            event_data: {{ data|json }}
```
**orchestrate/add_user.sls**
```
{% set data = salt.pillar.get('event_data') %}
{% set issue = data['post']['issue'] %}

add_user:
  salt.function:
    - name: user.add
    - tgt: {{ issue['fields']['customfield_10100'] }}
    - kwarg:
        name: {{ issue['fields']['customfield_10103'] }}
        createhome: True
        gid: {{ issue['fields']['customfield_10107'] }}
        groups: {{ issue['fields']['customfield_10108'] }}
        fullname: {{ issue['fields']['customfield_10106'] }} {{ issue['fields']['customfield_10105'] }}
        other: email@test.ch

issue_add_comment:
  salt.runner:
    - name: salt.cmd
    - arg:
      - issue.add_comment
    - kwarg:
        issue: {{ issue['key'] }}
        commentText: error message of add_user    # this is where I'm stuck
    - onfail:
      - salt: add_user
```
**_modules/issue.py**
```
def add_comment(issue, commentText):
    jira.add_comment(issue, commentText)
    jira.transition_issue(issue, '11')
    return True
```
### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 12 2018, 05:31:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.6 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo
```
