### ISSUE TITLE
Slots not being evaluated as a sub-key of context

### ISSUE THREAD

**Issue by crux-capacitor** [saltstack/salt#51798]
### Description of Issue/Question
 
I'm trying to use slots to populate variables passed into the context argument of a file.recurse, but the file is being rendered with the exact text of the slot declaration, rather than the return of the slot.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Example state. The first slot is a test for functionality, and the other 2 are what I really want to achieve.
```
{% set pki_properties_file = '/opt/nifi/pki/' ~ grains['fqdn'] ~ '/nifi.properties' %}

"Manage Config Files":
  file.recurse:
    - name: /opt/nifi/{{ local_nifi_dir }}/conf/
    - source: salt://{{ slspath }}/files/
    - template: jinja
    - include_empty: True
    - file_mode: 660
    - dir_mode: 660
    - require:
      - sls: formula.nifi.tls
    - context:
          keystore_passwd: __slot__:salt:cmd.run(name=echo password)
          key_passwd: __slot__:salt:cmd.run('grep keyPasswd ' ~ pki_properties_file).split('=')[1]
          truststore_passwd: __slot__:salt:cmd.run('grep truststorePasswd ' ~ pki_properties_file).split('=')[1]
```

And the resulting output in the file:
```
nifi.security.keystore=./conf/keystore.jks
nifi.security.keystoreType=jks
nifi.security.keystorePasswd=__slot__:salt:cmd.run(name=echo password)
nifi.security.keyPasswd=__slot__:salt:cmd.run('grep keyPasswd ' ~ pki_properties_file).split('=')[1]
nifi.security.truststore=./conf/truststore.jks
nifi.security.truststoreType=jks
nifi.security.truststorePasswd=__slot__:salt:cmd.run('grep truststorePasswd ' ~ pki_properties_file).split('=')[1]
nifi.security.needClientAuth=
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jul 26 2018, 19:59:38)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.88-88.76.amzn2.x86_64
         system: Linux
        version: Not Installed
