### ISSUE TITLE
salt minion can't start Unexpected COM Error 

### ISSUE THREAD

**Issue by squall2751** [saltstack/salt#51793]
Hello all,

I've use some salt-minion on Windows OS(10 or Server 2012/2016) which connected to salt-master(Ubuntu Docker).

One of the salt-minion(Windows 10) have a connection error,  the debug log error show some Chinese word meaning is 
> 存放裝置空間不足，無法完成此操作。
disk space not enough, can't complete this operation
But this salt-minion have enough space (18.2/99.6 GB), anyone can help me to debug this problem ?

DEBUG LOG
> [DEBUG   ] Reading configuration from c:\salt\conf\minion
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\wmi.py", line 817, in query
    return self._namespace.query (wql, self, fields)
  File "C:\salt\bin\lib\site-packages\wmi.py", line 1009, in query
    return [ _wmi_object (obj, instance_of, fields) for obj in self._raw_query(wql) ]
  File "C:\salt\bin\lib\site-packages\wmi.py", line 1009, in <listcomp>
    return [ _wmi_object (obj, instance_of, fields) for obj in self._raw_query(wql) ]
  File "C:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 252, in __getitem__
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
x_wmi: <x_wmi: Unexpected COM Error (-2147024882, '存放裝置空間不足，無法完成此操作。', None, None)>
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\wmi.py", line 817, in query
    return self._namespace.query (wql, self, fields)
  File "C:\salt\bin\lib\site-packages\wmi.py", line 1009, in query
    return [ _wmi_object (obj, instance_of, fields) for obj in self._raw_query(wql) ]
  File "C:\salt\bin\lib\site-packages\wmi.py", line 1009, in <listcomp>
    return [ _wmi_object (obj, instance_of, fields) for obj in self._raw_query(wql) ]
  File "C:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 252, in __getitem__
    return self._get_good_object_(self._enum_.__getitem__(index))
  File "C:\salt\bin\lib\site-packages\win32com\client\util.py", line 37, in __getitem__
    return self.__GetIndex(index)
  File "C:\salt\bin\lib\site-packages\win32com\client\util.py", line 53, in __GetIndex
    result = self._oleobj_.Next(1)
pywintypes.com_error: (-2147024882, '存放裝置空間不足，無法完成此操作。', None, None)

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 180, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 348, in start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1029, in tune_in
    self._spawn_minions()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 978, in _spawn_minions
    jid_queue=self.jid_queue,
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 959, in _create_minion_object
    jid_queue=jid_queue)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1099, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 737, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 2142, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 1420, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 1049, in interfaces
    return win_interfaces()
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 1005, in win_interfaces
    for iface in c.Win32_NetworkAdapterConfiguration(IPEnabled=1):
  File "C:\salt\bin\lib\site-packages\wmi.py", line 819, in query
    handle_com_error ()
  File "C:\salt\bin\lib\site-packages\wmi.py", line 241, in handle_com_error
    raise klass (com_error=err)
wmi.x_wmi: <x_wmi: Unexpected COM Error (-2147024882, '存放裝置空間不足，無法完成此操作。', None, None)>
    return self._get_good_object_(self._enum_.__getitem__(index))
  File "C:\salt\bin\lib\site-packages\win32com\client\util.py", line 37, in __getitem__
    return self.__GetIndex(index)
  File "C:\salt\bin\lib\site-packages\win32com\client\util.py", line 53, in __GetIndex
    result = self._oleobj_.Next(1)
pywintypes.com_error: (-2147024882, '存放裝置空間不足，無法完成此操作。', None, None)

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 180, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 348, in start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1029, in tune_in
    self._spawn_minions()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 978, in _spawn_minions
    jid_queue=self.jid_queue,
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 959, in _create_minion_object
    jid_queue=jid_queue)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1099, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 737, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 2142, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 1420, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 1049, in interfaces
    return win_interfaces()
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 1005, in win_interfaces
    for iface in c.Win32_NetworkAdapterConfiguration(IPEnabled=1):
  File "C:\salt\bin\lib\site-packages\wmi.py", line 819, in query
    handle_com_error ()
  File "C:\salt\bin\lib\site-packages\wmi.py", line 241, in handle_com_error
    raise klass (com_error=err)
wmi.x_wmi: <x_wmi: Unexpected COM Error (-2147024882, '存放裝置空間不足，無法完成此操作。', None, None)>

Salt-Master version
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.0-45-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

Salt-minion version:
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp950
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.15063 SP0 Multiprocessor Free
```
