### ISSUE TITLE
Saltclass external pillar broken in 2019.2.0

### ISSUE THREAD

**Issue by jkrauz** [saltstack/salt#51817]
### Description of Issue/Question
After upgrading to 2019.2.0 our states are playing weirdly. I believe saltclass external pillar expansion is broken.

### Setup
```
# saltclass/nodes/node1.yml
classes:
    - child
pillars:
    foo:
      id: node1
```
```
# saltclass/classes/child.yml
classes:
    - parent
pillars:
    foo:
      id: child
      list:
        - child1
        - child2
```
```
# saltclass/classes/parent.yml
environment: base
pillars:
    foo:
      id: parent
      list:
        - parent1
        - parent2
```

### Steps to Reproduce Issue
salt-call pillar.get foo
```
local:
    ----------
    id:
        parent
    list:
        - parent1
        - parent2
        - child1
        - child2
        - parent1
        - parent2
        - child1
        - child2
        - parent1
        - parent2
```
The output above doesn't look correct. The expected output is:
```
local:
    ----------
    id:
        node1
    list:
        - child1
        - child2
        - parent1
        - parent2
```

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
