### ISSUE TITLE
elasticsearch.index_template_present state not idempotent in 2019.2.0

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#51822]
This state now applies changes on every run.
```
logstash template:
  elasticsearch.index_template_present:
    - check_definition: true
    - require:
      - service: elasticsearch_service
    - require_in:
      - service: logstash
    - definition:
        index_patterns: [ 'logstash-*' ]
        order: 0
        aliases: {}
        settings:
          index:
            auto_expand_replicas: '0-1'
            number_of_replicas: '0'
            refresh_interval: '5s'
        mappings:
          _default_:
            dynamic_templates:
              - message_field:
                  path_match: message
                  match_mapping_type: string
                  mapping:
                    type: text
                    norms: false
              - string_fields:
                  match: '*'
                  match_mapping_type: string
                  mapping:
                    type: text
                    norms: false
                    fields:
                      keyword:
                        type: keyword
                        ignore_above: 256
            properties:
              '@timestamptype': { type: date }
              '@version': { type: keyword }
              geoip:
                dynamic: true
                properties:
                  ip: { type: ip }
                  location: { type: geo_point }
                  latitude: { type: half_float }
                  longitude: { type: half_float }
```
```
          ID: logstash template
    Function: elasticsearch.index_template_present
      Result: True
     Comment: Successfully updated index template logstash
     Started: 12:27:39.797554
    Duration: 25.539 ms
     Changes:
              ----------
              new:
                  ----------
                  aliases:
                      ----------
```
