### ISSUE TITLE
'comment' is an invalid keyword argument for 'test.fail_without_changes'

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#51821]
Master and minion version 2019.2.0.
> Any parameters in the state return dictionary can be customized by adding the keywords result, comment, and changes.
```
stop state.apply:
  test.fail_without_changes:
    - order: 1
    - comment: Failing highstate to allow minion restart
    - failhard: true
    - watch:
      - service: salt-minion
```
> [ERROR] Unhandled exception running state.apply
 salt.exceptions.SaltInvocationError: 'comment' is an invalid keyword argument for 'test.fail_without_changes'

**Comment by OrangeDog** [comment]
Aside: I realise this example state doesn't do anything useful, as it always fails regardless of whether mod_watch is triggered.

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this and i bisected it to: 1be50abd4deacb63395b412bb9c4506c8304c56b

i also tested on the head of 2019.2 and its broken there as well. 

Heres the state i used to replicate the issue:

```
ntp:
  file.managed:
    - name: /etc/ntp.conf
    - contents: | 
        test

stop state.apply:
  test.fail_without_changes:
    - order: 1
    - comment: Failing highstate to allow minion restart
    - failhard: true
    - watch:
      - file: ntp
```
