### ISSUE TITLE
pillar include stopped working

### ISSUE THREAD

**Issue by nocturo** [saltstack/salt#51832]
### Description of Issue/Question
I have used git for ext_pillar for a while now and when upgrading to 2019.2.0 no pillars get rendered for me. As a quick test I downgraded to 2018.3.4 and everything works as expected.

ext_pillar config:
```yaml
ext_pillar:
  - git:
    - master git@github.com:user/pillar.git:
       - root: pillar
       - privkey: /root/.ssh/id_rsa
       - pubkey: /root/.ssh/id_rsa.pub
```

This straight up doesn't load up the pillar top.sls if I have root: specified. If I remove the option and put top.sls in git "root" it then loads it and I get error that now it can't find the SLS (as expected since the path is not relative anymore to the specified root in the config which I've been using).

### Steps to Reproduce Issue
Configure exit_pillar git pillar with root: and top.sls in the root.

### Versions Report
```Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 3.4.9 (default, Feb  5 2019, 14:36:09)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by Ch3LL** [comment]
im not able to replicate this with:

```
ext_pillar:                                                                                                                                                                                          
  - git:                                                                                                                                                                                             
    - master https://github.com/Ch3LL/Ch3LLScripts.git:                                                                                                                                              
      - root: salt/pillars
```

although i did have to patch mine with https://github.com/saltstack/salt/pull/51304/files but thats because i have a newer pygit version then you do.

Do you see any error's or further information in the debug logs when this occurs?

**Comment by nocturo** [comment]
OK I was vague as it seems more involved than I first thought. I have some `include:`s happening in the pillar and it looks like this: https://github.com/nocturo/pillar

If you put that as your ext_pillar, with root:
```
ext_pillar:
  - git:
    - master https://github.com/nocturo/pillar.git
      - root: pillar
```

and that's the root cause of this. I've just initially assumed since it errored out due to SLS path when trying top.sls directly at top level that it was working, but it doesn't on that repo with or without root when `include:` is called to call a pillar.
