### ISSUE TITLE
Windows reg.present salt-call win_dacl.py 2019.2.0 'LookupAccountSid' Error

### ISSUE THREAD

**Issue by jeremylarose** [saltstack/salt#51868]
### Description of Issue/Question
The reg.present states work, but presents an ugly error when running salt-call from a minion running version 2019.2.0... the error is not present with 2018.3.4 or if running the state from the master... only with a salt-call from the minion.

### Setup
example sls:
```
'HKLM\SOFTWARE\Policies\Microsoft\\Windows\TabletPC\PreventHandwritingDataSharing':
  reg.present:
    - name: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\TabletPC'
    - vname: PreventHandwritingDataSharing
    - vdata: 1
    - vtype: REG_DWORD
```
### Steps to Reproduce Issue
Run salt-call on multiple Windows 10 machines
```
[ERROR   ] Error resolving "S-1-1-1-1111-1111111111111-1111111111-11-111-111111-11111-1111-1111": No mapping between account names and security IDs was done.
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\win_dacl.py", line 1179, in get_name
    return win32security.LookupAccountSid(None, sid_obj)[0]
error: (1332, 'LookupAccountSid', 'No mapping between account names and security IDs was done.')
[ERROR   ] Error resolving "S-1-1-1-1111-1111111111111-1111111111-11-111-111111-11111-1111-1111": No mapping between account names and security IDs was done.
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\win_dacl.py", line 1179, in get_name
    return win32security.LookupAccountSid(None, sid_obj)[0]
error: (1332, 'LookupAccountSid', 'No mapping between account names and security IDs was done.')
```
... but the reg.present state runs and succeeds

### Versions Report

salt 2019.2.0 (Fluorine)
salt-call 2019.2.0 (Fluorine)... ERROR
salt-call 2018.3.4 (Oxygen)... no error

**Comment by twangboy** [comment]
@jeremylarose Thanks for reporting. I'll take a look at this.
That GUID looks suspect though... I wonder where that came from...
That code is trying to match the GUID it received to an Account name.

**Comment by jeremylarose** [comment]
Thanks, yes, i made up that id, it was a proper one

**Comment by twangboy** [comment]
Oh, OK. That makes sense. I'll take a look at it.

**Comment by twangboy** [comment]
@jeremylarose I'm having a hard time reproducing this. So, I have a few questions.

Is this the only thing in the state file you're applying? Are there any other states?
Are you setting `owner` or `perms` that you didn't have above?
What account are you running `salt-call` under? (Local Administrator?)
Is it a domain account?
Is the account a member of the Local Administrators group?

**Comment by jeremylarose** [comment]
It occurs with other states.  But that is the only contents of this particular state that is run and produces the error.  No permissions are attempted to be modified.  Salt-call is run under a domain account with admin rights and through cmd or powershell run as administrator.  The thing is, it doesn't occur with previous versions of salt minion, ex: 2018.3.4 ... just 2019.2.0 using either py2 or py3.

**Comment by twangboy** [comment]
Perhaps the `LookupAccountSID` function is failing because it can't find a name mapping for the Domain Account. Which is strange as you've assumably logged in with that account and are running the command under the same.
Does the same behavior occur with a local (non-domain) admin account?

**Comment by gdsjerry** [comment]
Same problem happens to me. Vagrant running Windows 2019. Salt 2019.2.0 with python 3. Running as normal "vagrant" local user. Setting any value using reg.present seems to throw this error, for example:

```
ssh|set_bash_as_openssh_shell:
  reg.present:
    - name: 'HKLM\SOFTWARE\OpenSSH'
    - vname: 'DefaultShell'
    - vdata: 'C:\Program Files\Git\bin\bash.exe'
```
