### ISSUE TITLE
Question about  returning/output for variable use in state.

### ISSUE THREAD

**Issue by kipje91** [saltstack/salt#51864]
### Description of Issue/Question
Hi guys,
I might be looking in the wrong direction, but is there a way to use the output of, for example win_wua. module to use in the next state? Or to send an event?

I've looked into salt mine and returner modules, but that's not really what I want (I think).

Goal:
Run a scheduled state that check for Windows updates (critical) and does an event.send message with that information (output from win_wua.list severities=['Critical']) or autmatically install only that update using the wua state with KBXXXXX returned by the previous state.

Any suggestion would be appreciated!

### Setup
I know this works, and this is pretty much what im searching for, but than for any module like win_wua?
```
{% set foo = salt['cmd.run']('cat /etc/hosts') %}
test1:
  event.send:
    - name: 'custom/notify'
    - data:
        title: 'testing {{ grains.id }}'
        message: '{{foo}}'
```
```
{% set foo = salt['module.run']('win_wua.list') %}
test2:
  event.send:
    - name: 'custom/notify'
    - data:
        title: 'testing {{ grains.id }}'
        message: '{{foo}}'
```
```
----------
    Rendering SLS 'base:reactor.testing' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'module.run'
```

**Comment by garethgreenaway** [comment]
@saltstack/team-core Anyone have any ideas on this one?

**Comment by kipje91** [comment]
I've found something that works, but now the output is just default "salt" which is nested?
```
{% set foo = salt['win_wua.list'](severities=['Critical']) %}
test2:
  file.append:
    - name: 'C:\Triple\test.txt'
    - makedirs: True
    - text: |
        {{foo}}
```

So this will return to something like 
```
{u'c7484975-8f44-45f4-a6f4-327c161ac722': {u'Severity': u'Critical', u'Title': u'2019-02 Security Monthly Quality Rollup for Windows Server 2012 R2 for x64-based Systems (KB4487000)', u'KBs': [u'KB4487000'], u'guid': u'c7484975-8f44-45f4-a6f4-327c161ac722', u'EULAAccepted': True, u'Mandatory': False, u'Description': u'A security issue has been identified in a Microsoft software product that could affect your system. You can help protect your system by installing this update from Microsoft. For a complete listing of the issues that are included in this update, see the associated Microsoft Knowledge Base article. After you install this update, you may have to restart your system.', u'Type': u'Software', u'RebootBehavior': u'Can Require Reboot', u'Installed': False, u'Downloaded': True, u'UserInput': False, u'NeedsReboot': False, u'Categories': [u'Security Updates', u'Windows Server 2012 R2']}}
```

However, this is just a single value and not yaml or json?
Is there any way to get the default output to something i could use and extract a subkey from?
Would love some examples on in the documentation :)
