### ISSUE TITLE
The INSTALL_LANGUAGE variable in salt.modules.win_lgpo module returns a default value of an incorrect type.

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#51944]
### Description of Issue/Question
Okay, I really don't know why I've been having such horrible luck with salt this past month, but anyways this issue is pretty simple...and away we go:

```
2019-03-02 09:24:33,562 [salt.loader      :1531][ERROR   ][1672] Failed to import module win_lgpo, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 133, in <module>
    windll.GetSystemDefaultUILanguage(), 1033).replace('_', '-')
AttributeError: 'int' object has no attribute 'replace'
```

I haven't tracked down why the kernel32 api call `windll.GetSystemDefaultUILanguage()` is returning a value that isn't available in the `locale.windows_locale` dictionary on this particular system, but nonetheless the line of code is located as follows. This line is trying to determine the default locale and assign it to the `INSTALL_LANGUAGE` variable.

`salt.modules.win_lgpo:127`
```
    # Default to `en-US` (1033)
    windll = ctypes.windll.kernel32
    INSTALL_LANGUAGE = locale.windows_locale.get(
        windll.GetSystemDefaultUILanguage(), 1033).replace('_', '-')
```

The issue here is that when the value returned from `windll.GetSystemDefaultUILanguage()` is not listed in the `locale.windows_locale`, the default integer of `1033` is returned due to the usage of `locale.windows_locale.get`. Unfortunately, the call to `.replace()` that is being done on this result is only available with string-types and so it raises an exception due to `.replace()` being called with an integer.

I'm assuming the author meant to do something like the following which defaults to 1033 (en-US) if the returned locale is not found. This will result in a string always being returned which `.replace()` can work with.
```
res = windll.GetSystemDefaultUILanguage()
INSTALL_LANGUAGE = (locale.windows_locale[res] if res in locale.windows_locale else locale.windows_locale[1033]).replace('_', '-')
```

### Setup
This time it's the salt-minion 2018.3.3 binary installer on an os you guys likely don't support (Windows7). This happens on import of the module during startup of the salt-minion within seconds after a reboot. Nonetheless, this type-o is in the develop branch and the integer type of `1033` is of the completely wrong type as the author assumes it should be a string containing a hyphen or underscore.

To simulate the reproduction of this issue you'll need to make `GetSystemDefaultUILanguage` return a value that isn't in the locale dictionary. You can do this from straight python by monkeypatching the `GetSystemDefaultUILanguage` functon of `ctypes.windll.kernel32` to return a value that isn't in the `locale.windows_locale` dictionary. I chose `None`, and so this can be done like:
```
>>> ctypes.windll.kernel32.GetSystemDefaultUILanguage = lambda : None
```

It's prudent to note that this is just a way of simulating the issue, but does not actually simulate the environment that causes an integer to be returned from the specified line of code.

### Steps to Reproduce Issue
Once you can simulate `Kernel32!GetSystemDefaultUILanguage` returning a non-locale, you can simply import the `win_lgpo` module to trigger the call to `.replace()` with the `1033` integer as its object.

### Versions Report
Seems to be since commit b96186d60dc.

**Comment by garethgreenaway** [comment]
@twangboy FYI.

**Comment by twangboy** [comment]
@arizvisa What does `GetSystemDefaultUILanguage()` return on your system?

**Comment by twangboy** [comment]
@arizvisa How does the above PR affect this issue? Does it continue successfully? Is it able to match the appropriate ADML files?

**Comment by arizvisa** [comment]
Yea, it isn't something that I'd really consider a (blocking) issue. Was mostly just pointing out a bug due to a type-o. I do believe that returning 'en-US' is the correct thing to do however.

What was happening is that apparently on Windows7, there's some sort of race in that `GetSystemDefaultUILanguage()` was returning a bunk value during startup. If I waited for a minute and tried again, the api call would correctly return 1033.

Windows7 isn't something that you guys support, so I don't think it's worth tracking this down to in order t oimprove its reliability. So, you guys are definitely doing this correctly, only that integer being returned was the wrong type.

**Comment by twangboy** [comment]
We're supporting Windows 7 until it's officially EOL... so we still have to support it. I'm surprised nobody has hit this issue before. A lot of people still use Windows 7 /2008 R2

**Comment by arizvisa** [comment]
Ah okay. I didn't see it on your http://get.saltstack.com/rs/304-PHQ-615/images/SaltStack-Supported-Operating-Systems.pdf document which is why I didn't think you guys really supported it

Here's the version info for the box, though, just so you have it on record.
```
Windows 7 Ultimate x64
Microsoft Windows [Version 6.1.7600]
tzres.dll and tzutil.exe [6.1.7600.16385]
```

Salt versions:
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 5.1.1
            ZMQ: 4.2.5
 
System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7600 SP0 Multiprocessor Free
```
