### ISSUE TITLE
net.cli not found but im using napalm proxy

### ISSUE THREAD

**Issue by juthewiz** [saltstack/salt#51948]
tried using net.cli for an event and it returned `"return": "'net.cli' is not available.",` below you will find the event, the proxy state file for sj1-e2, and the state file for net.cli. i also tried to run this from the salt master cli got the same results those are also below 

```
salt/job/20190302092456946837/ret/sj1-e2    {
    "_stamp": "2019-03-02T17:24:57.149858",
    "cmd": "_return",
    "fun": "net.cli",
    "fun_args": [
        {
            "__kwarg__": true,
            "set protocols isis interface xe-0/0/7 passive": null,
            "set protocols rsvp interface xe-0/0/7 disable": null
        }
    ],
    "id": "sj1-e2",
    "jid": "20190302092456946837",
    "out": "nested",
    "retcode": 254,
    "return": "'net.cli' is not available.",
    "success": false

```

```
proxy:
 proxytype: napalm
 driver: junos
 host: 10.10.10.10
 username: SALT
 password: pass
 port: 22

```
```

drain_circuit:
  local.net.cli:
   - tgt: sj1-e2
   - args:
     - set protocols rsvp interface xe-0/0/7 disable
     - set protocols isis interface xe-0/0/7 passive

```

```
saltmaster % sudo salt sj1-e2 net.cli "show version"
sj1-e2:
    'net.cli' is not available.

```

```


 salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-124-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```
