### ISSUE TITLE
Salt-Cloud Map vs VM Profile precedence

### ISSUE THREAD

**Issue by Securitybits-io** [saltstack/salt#51953]
### Description of Issue/Question
Trying to create a VM from a salt-cloud map on a ESXi Cluster. I experience some weird behavior regarding which profile and map should take precedence in creating the file.
The salt-cloud map documentation says the following

`As of Salt 2017.7.0, nested elements are merged, and can can be specified individually without having to repeat the complete definition for each top level data element. In this example a separate MAC is assigned to each VMware instance while inheriting device parameters for for disk and network configuration: <snip>
`
### Setup
Having the following profile configuration
```
telegraf:
  provider: vcenter
  clonefrom: Template_8GB_eldir

  ## Optional arguments
  num_cpus: 1
  memory: 2GB
  devices:
    network:
      Network adapter 1:
        name: vDPG-40-Securitybits.Private
        switch_type: distributed
        connected: true

  cluster: test.cluster
<snip>

```

Together with the salt-cloud map
```
telegraf:
  - sb-telegraf-01:
      devices:
        network:
          Network Adapter 1:
            name: vDPG-40-Securitybits.Private
            switch_type: distributed
            mac: '00:50:56:b9:19:89'
            connected: true
```
One could assume that it will create the VM with the VM Profile, then apply the cloud map configs, setting the network as well as MAC address. Instead it creates two interface, one with the correct MAC Address and another one which is generated by ESXi.

### Use Case
Having a base Image in ESXi as well as the appropriate profile as a default. but if combined with a cloud map script, it would be niftly if there was an option to specify that the cloud map takes precedence if something with the same name is declared in both files. 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.4
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Oct  2 2018, 22:12:08)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.0
           RAET: Not Installed
          smmap: 2.0.4
        timelib: Not Installed
        Tornado: 5.0.2
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.10 cosmic
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-15-generic
         system: Linux
        version: Ubuntu 18.10 cosmic

```

**Comment by garethgreenaway** [comment]
@saltstack/team-cloud Any thoughts on this one?

**Comment by nnsense** [comment]
Hi
I think I'm hitting more or less the same issue on EC2. In my case the whole deployment is failing because the two options are strictly related. I see there aren't updates on this important issue, would it be possible for somebody to check?

In my case the profile is:
```
ds_large:
  provider: ds
[...]
  network_interfaces:
    - DeviceIndex: 0
      SubnetId: subnet-0dd6e907dd9def5a0
      SecurityGroupIds: [sg-05d91b41396193ff4]
[...]
```
While the map file configures the private ip address:
```
ds_large:
  - DS-BOX12:
      network_interfaces:
        - DeviceIndex: 0
          PrivateIpAddresses:
            - Primary: True
              PrivateIpAddress: 172.31.3.12
```

It seems the two `network_interfaces` aren't being merged and the map file takes precedence, the request is eventually stating the private ip and the wrong (the first from the fetched list) subnet ID, resulting in
```
[DEBUG   ] AWS Request: https://ec2.eu-west-1.amazonaws.com/?Action=CreateNetworkInterface&PrivateIpAddresses.0.Primary=true&PrivateIpAddresses.0.PrivateIpAddress=172.31.3.22&SubnetId=subnet-0605ca6a55a938
f1d&Version=2014-10-01
[DEBUG   ] AWS Response Status Code: 400
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': "Address does not fall within the subnet's address range", 'Code': 'InvalidParameterValue
'}}, 'RequestID': 'df4746c8-3efd-4a46-a7b9-e93f2dbad110'}
[ERROR   ] Failed to create VM DS-BOX12. Configuration value 1 needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1252, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2633, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1915, in request_instance
    _new_eni = _create_eni_if_necessary(interface, vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1469, in _create_eni_if_necessary
    eni_desc = result[1]
```

Thanks
