### ISSUE TITLE
Scheduled state.sls Using Random Pillar Env

### ISSUE THREAD

**Issue by ekristen** [saltstack/salt#51950]
### Description of Issue/Question

It could very well be a configuration issue, but I'm not sure were to start. I noticed it happening in the last week or so.

Basically it appears that the scheduled job uses the wrong pillarenv, even worse is that it seems to use a random one?

I've reviewed my minion logs and I cannot find any reference to the incorrect pillar env, but I can most definitely see the wrong config file being generated with incorrect data via the debug logs.

Running the command from `salt-call` reverts everything to their properly value, so this seems to be limited to those that run on a schedule?

#### SLS

```jinja
{%- from "teleport/map.jinja" import teleport with context -%}
{%- set teleport_roles = [] -%}
{%- for role in grains['roles'] -%}
  {%- if role.startswith('teleport-') -%}
  {%- do teleport_roles.append(role.replace('teleport-', '')) -%}
  {%- endif -%}
{%- endfor -%}

include:
  - teleport.install

teleport-data-directory:
  file.directory:
    - name: /var/lib/teleport
    - user: root
    - group: root
    - makedirs: True
    - require:
      - file: teleport-binary-teleport

teleport-config-directory:
  file.directory:
    - name: /etc/teleport
    - user: root
    - group: root
    - makedirs: True
    - require:
      - file: teleport-binary-teleport

{% if grains['lsb_distrib_codename'] == 'Amazon Linux AMI 2014.09' %}
teleport-service-config:
  file.managed:
    - name: /etc/init.d/teleport
    - user: root
    - group: root
    - mode: 755
    - source: salt://teleport/resources/teleport.initd
    - require:
      - file: teleport-binary-teleport

teleport-service-chkconfig:
  cmd.wait:
    - name: chkconfig --add teleport
    - watch:
      - file: teleport-service-config
{% else %}
teleport-service-config:
  file.managed:
    - name: /etc/systemd/system/teleport.service
    - user: root
    - group: root
    - source: salt://teleport/resources/teleport.systemd
    - require:
      - file: teleport-binary-teleport
{% endif %}

teleport-config:
  file.managed:
    - name: /etc/teleport.yaml
    - source: salt://teleport/resources/teleport.yaml.jinja
    - template: jinja
    - user: root
    - group: root
    - require:
      - file: teleport-config-directory

teleport-service:
  service.running:
    - name: teleport
    - enable: True
    - watch:
      - file: teleport-data-directory
      - file: teleport-binary-teleport
      - file: teleport-config
      - file: teleport-service-config

teleport-schedule:
  schedule.present:
    - function: state.sls
    - job_args:
      - teleport
    - job_kwargs:
        saltenv: {{ saltenv }}
    - cron: '30 03 * * *'
    - enabled: true
    - persist: true
    - jid_include: true
    - run_on_start: true
```

#### map.jinja
```
{% import_yaml 'teleport/defaults.yaml' as defaults %}

{% set teleport = salt['pillar.get']('teleport', default=defaults.teleport, merge=True) %}
```

#### defaults.yaml
```
teleport:
  version: v2.3.5
  sha256: 75f21ef8447285a037479bff12da1407d52312ebdee9e4bb0f42ba4253d90261
  data_dir: /var/lib/teleport
  auth_servers:
    - 127.0.0.1:3025
  connection_limits:
    max_connections: 250
    max_users: 25
  storage:
    type: dir
    dynamodb:
      region: us-west-2
      table_name: teleport
  auth:
    token: xxx
    type: local
    second_factor: otp
    tokens:
      - "node,proxy:xx"
      - "node:xx"
      - "auth,node:xx"
      - "trusted_cluster:xx"
  log:
    output: /var/log/teleport.log
    severity: INFO
  node:
    token: xxx
  proxy:
    token: xxx
    common_name: localhost
  trusted_cluster:
    name: localhost
    token: xxx
    tunnel_addr: localhost
    
```

### Steps to Reproduce Issue

Have multiple pillar envs defined via gitfs. Let the schedule run.

### Versions Report

```
Salt Version:
           Salt: 2017.7.8

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1070-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```
