### ISSUE TITLE
Runner state.orchestrate_show_sls is broken in 2019.2

### ISSUE THREAD

**Issue by jan--f** [saltstack/salt#51951]
### Description of Issue/Question
Same as #50556 for version 2019.2

### Setup
nothing special

### Steps to Reproduce Issue
Call `salt-run state.orchestrate_show_sls` with any orchestration sls file

### Versions Report
```
 # salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.5 (default, Apr 05 2018, 13:30:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-31-default
         system: Linux
        version: Not Installed
```
