### ISSUE TITLE
salt-ssh --key-deploy does not deploy salt public ssh keys if combined with --priv

### ISSUE THREAD

**Issue by devurandom** [saltstack/salt#51999]
### Setup
Saltfile:
```yaml
salt-ssh:
  roster_file: salt/roster
  config_dir: salt
  log_file: salt/ssh.log
```

salt/master:
```yaml
root_dir: salt
file_roots:
  base:
    - salt/states
pillar_roots:
  base:
    - salt/pillar
```

salt/roster:
```yaml
NODENAME:
  host: ...
  user: ...
```

### Steps to Reproduce Issue
1. `salt-ssh -i --priv=... --priv-passwd=... --key-deploy '*' test.ping`
2. `salt-ssh '*' test.ping`

### Expected output of 2nd step:
```yaml
NODENAME:
  True
```

### Actual output of 2nd step:
```
Permission denied for host NODENAME, do you want to deploy the salt-ssh key? (password required):
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Oct 15 2018, 15:26:09)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 29 Twenty Nine
         locale: UTF-8
        machine: x86_64
        release: 4.20.13-200.fc29.x86_64
         system: Linux
        version: Fedora 29 Twenty Nine
```
