### ISSUE TITLE
Incompatible kwargs for create_image and find_images in salt.states.boto_ec2.snapshot_created() 

### ISSUE THREAD

**Issue by odhekar** [saltstack/salt#52005]
find_images fails when snapshot_created is called with both wait_until_available and no_reboot.
```
backup_vm:  
  boto_ec2.snapshot_created:
    - name: {{ snapshot_name }}
    - ami_name: {{ ami_name }}
    - instance_name: {{ instance_name }}
    - wait_until_available: True
    - no_reboot: True
```
this block results in
```
myminion:
----------
          ID: backup_vm
    Function: boto_ec2.snapshot_created
        Name: salt-test-snapshot
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/boto_ec2.py", line 574, in snapshot_created
                  images = __salt__['boto_ec2.find_images'](ami_name=ami_name, return_objs=True, **kwargs)
              TypeError: find_images() got an unexpected keyword argument 'no_reboot'
     Started: 20:16:01.748023
    Duration: 424.394 ms
     Changes:
```
https://github.com/saltstack/salt/blob/ae69e87df5598c9810507d921b7da29509fb3d05/salt/states/boto_ec2.py#L574

no_reboot should be a separate argument for snapshot_created.

```
salt 2019.2.0 (Fluorine)
boto 2.49.0
```
