### ISSUE TITLE
Salt-cloud / Proxmox Clone profile error

### ISSUE THREAD

**Issue by valentin2105** [saltstack/salt#52042]
### Description of Issue/Question
Hi,
I try to clone a VM on my Proxmox cluster using Salt-cloud. 

When I launch `salt-cloud -l debug -p stretch myfirsttest`, it launch correctly the VM clone but I got a direct output error : 

```
...
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] Preparing to generate a node using these parameters: {u'vmid': 118, u'name': u'myfirsttest'}
[DEBUG   ] post: https://localhost:8006/api2/json/nodes/alpha/qemu/10000/clone ({u'full': 1, u'newid': 118, u'name': u'test', u'format': u'qcow2'})
Usage: salt-cloud [options] <-m MAP | -p PROFILE> <NAME> [NAME2 ...]

salt-cloud: error: There was a profile error:
```
The exit code is 64. 
The strange thing, is there is not any ERROR logs in all the debug output, but it fail at the end. 

The VM is correcly cloned, but the name (**myfirsttest**) is ignored, it's call "Copy-of-Stretch" instead.  

Here is my config :

**cloud.providers.d/proxmox.conf** 
```
px:
  minion:
    master: localhost

  user: admin@pve
  password: REDACTED

  url: localhost
  driver: proxmox
  verify_ssl: False
  host: REDACTED

```
**cloud.profiles.d/stretch.conf** 
```
stretch:
    provider: px
    clone: True
    clone_from: 10000
    clone_full: 1
    clone_format: qcow2
    technology: qemu
    host: alpha
    image: stretch.iso
    size: ''

```
### Versions Report

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.8
         locale: UTF-8
        machine: x86_64
        release: 4.15.18-11-pve
         system: Linux
        version: debian 9.8
```

Any idea how to fix that ? 
Thanks.
