### ISSUE TITLE
external_auth: ldap anonymous binding doesn't work

### ISSUE THREAD

**Issue by thardie** [saltstack/salt#52067]
### Description of Issue/Question
When setting auth.ldap.anonymous to True, auto process dies with `Authentication module threw u'binddn'`

Documentation says binddn is not required when binding anonymously. The idea behind this is you bind anonymously to get the user's DN, then use that to bind properly.

### Setup
master.conf auth config:
```
        # Use STARTTLS when connecting
        auth.ldap.starttls: False

        # LDAP scope level, almost always 2
        auth.ldap.scope: 2

        # Server specified in URI format
        auth.ldap.uri: 'ldaps://<REDACTED>'    # Overrides .ldap.server, .ldap.port, .ldap.tls above

        # Verify server's TLS certificate
        auth.ldap.no_verify: False

        auth.ldap.basedn: dc=<REDACTED>

        auth.ldap.filter: uid={{ username }}

        # Bind to LDAP anonymously to determine group membership
        # Active Directory does not allow anonymous binds without special configuration
        # In addition, if auth.ldap.anonymous is True, empty bind passwords are not permitted.
        auth.ldap.anonymous: True

        # FOR TESTING ONLY, this is a VERY insecure setting.
        # If this is True, the LDAP bind password will be ignored and
        # access will be determined by group membership alone with
        # the group memberships being retrieved via anonymous bind
        auth.ldap.auth_by_group_membership_only: False

        # Require authenticating user to be part of this Organizational Unit
        # This can be blank if your LDAP schema does not use this kind of OU
        auth.ldap.groupou: 'Groups'

        # Object Class for groups.  An LDAP search will be done to find all groups of this
        # class to which the authenticating user belongs.
        auth.ldap.groupclass: 'posixGroup'

        # Unique ID attribute name for the user
        auth.ldap.accountattributename: 'memberUid'

        # These are only for Active Directory
        auth.ldap.activedirectory: False
        auth.ldap.persontype: 'person'

        auth.ldap.minion_stripdomains: []

        # Redhat Identity Policy Audit
        auth.ldap.freeipa: False

        external_auth:
          ldap:
            SaltMasterAdminUsers%:
              - .*
```

### Steps to Reproduce Issue
Bring up new salt-master (enable debug logging for error messages) with python-ldap installed. Run "salt -a ldap '*' test.ping", provide username/password at the prompts. Check salt log:

```
[DEBUG   ] Authentication module threw u'binddn'
[WARNING ] Authentication failure of type "eauth" occurred.
```

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-141-generic
         system: Linux
        version: Ubuntu 16.04 xenial
