### ISSUE TITLE
Debian 9 / 2019.2 Salt Minion 100% CPU usage every minute.

### ISSUE THREAD

**Issue by r-pufky** [saltstack/salt#52129]
### Description of Issue/Question
I've noticed that *only* on my Debian 9 systems with 2019.2 salt-minions will go into 100% CPU usage every minute. This was not happening on 2018.X installations, even on the same hardware.

### Setup
* All machines patched with latest updates as of 2019-03-10.
* 128GB NVME, 8GB ram, 8th gen intel quad core (1.9 base, 4.2 boost)
* Salt minion has been reinstalled already.

salt (debian 9): salt-master, salt-minion
client (debian 9): salt-minion

relevant top.sls
```yaml
prod:
  'salt.{REMOVED}.com':
    - minion
    - apt.unattended
    - apt.transports.https
    - apt.repositories
    - apps.base_packages
    - system.skeleton.root
    - system.skeleton.skel
    - system.etc.motd
    - account.users.present
    - system.salt.master.permissions
    - fonts
    - openssh.config
    - openssh.auth
```
* Very minimal: adds user accounts, apt repos, base packages, skeleton files, fonts and openssh configs.
* Minion drops minion configuration files onto the minion (/etc/salt/minion.d), below:

_schedule.conf
```yaml
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false}
```

file.conf
```yaml
hash_type: sha512
```

logging.conf
```yaml
log_level: error
```

primary.conf
```yaml
master: salt
source_interface_name: eth0
retry_dns: 120
master_port: 4506
user: root
append_domain: {REMOVED}.com
verify_env: True
acceptance_wait_time: 10
random_startup_delay: 60
master_tries: -1
auth_tries: 10
auth_safemode: True
ping_interval: 2
minion_pillar_cache: False
```

security.conf
```yaml
keysize: 4096
minion_sign_messages: True
permissive_pki_access: False
```

startup.conf
```yaml
startup_states: highstate
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

It happens in a clean state, or purging all packages and resinstalling
* `apt remove --purge salt-minion`
* `rm -rfv /etc/salt/minion.d && rm /etc/salt/minion && rm /etc/salt/pki/minion/*`
* (server) `salt-key -d {REMOVED}`
* (checked for any remaining salt packages), `apt autoremove && apt update && apt upgrade`
* `apt install salt-minion`
* (server) `salt-key -a {REMOVED}`
* `salt-call state.highstate` or just stop/start service (`service salt-minion restart`) or wait a few minutes

-- machines will now peg at 100% every minute or two; even though internvals are not setup that frequently.

#### Top screenshot of salt-minion pegging CPU
![salt-minion-top](https://user-images.githubusercontent.com/4778046/54105158-78f1af00-438f-11e9-9e1d-720d3f03ec13.png)

#### Another top screenshot of salt-minion pegging CPU 
![salt-minion-post-debug-100](https://user-images.githubusercontent.com/4778046/54105164-7d1dcc80-438f-11e9-91a6-27d1ffb39f5d.png)

#### History with original minion installed. Removing minion resolves CPU thrashing.
![salt-minion-removed](https://user-images.githubusercontent.com/4778046/54105095-4051d580-438f-11e9-95a2-e8abb15d5950.png)

#### Minion purged, reinstalled, manual salt-call, then pegging every minute again
This tracks the removal of the current minion, purging it and reinstalling it with a manual run. Notice the manual run gets around 50% at most. All states are successfully applied. Subsequent runs are automatic and peg processor.

Happens on both standalone and minion/master machines. 
![salt-minion-reinstall-highstate-rerun](https://user-images.githubusercontent.com/4778046/54105122-55c6ff80-438f-11e9-8d74-b5bffa47f6f2.png)

#### Auto minion runs, service disable, foreground debug run.
Notice the foreground debug run only hits around 75% usage. Completes, and does not run every minute or two (which is what is expected).
![salt-minion-debug-foreground-run](https://user-images.githubusercontent.com/4778046/54105131-61b2c180-438f-11e9-89b5-f4712e358489.png)

Foreground minion debug log
[debug-log-pruned.txt](https://github.com/saltstack/salt/files/2951052/debug-log-pruned.txt)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

All setups are using the same version.

$ salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.8
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8

Edit: fixed h1 header for graph.

**Comment by Ch3LL** [comment]
when you are refering to minion runs, is the minion running a highstate or another job every minute when its pegging, or is the minion just in standby doing nothing?

Also where you previously using python 3 in the version you were using before 2019.2.0?

**Comment by r-pufky** [comment]
> Also where you previously using python 3 in the version you were using before 2019.2.0?
One was using 2.7 beforehand, the other started on 3. They are both running 3.5.3 now (after a purge / reinstall) of both.

>  when you are refering to minion runs, is the minion running a highstate or another job every minute when its pegging, or is the minion just in standby doing nothing?

I meant that it was automatically running every minutes, which it should not be doing -- I went back to collect more data on this.

* it's automatically triggering every minute, and applying a state.highstate. This shouldn't be happening (mining happens every 60 minutes); highstate is setup to be applied on salt-minion service startup.
* I've enabled debugging for these clients.
* Here's another chart of running it again tonight (hopefully clarified):

![salt-minion-pi-install-call-minion-background-runs](https://user-images.githubusercontent.com/4778046/54255325-d7946580-4514-11e9-8f8c-ed212dfc72dc.png)

I clipped a portion of the log. It looks like there is a SIGTERM that the minion receives, and it automatically restarts the minion service, causing the highstate to be re-applied. Something seems to be causing this during the run in `salt.utils.parsers`

Log attached below, see line 14.

[salt-minion-run-stderr.log](https://github.com/saltstack/salt/files/2959905/salt-minion-run-stderr.log)

Let me know what else I should be poking at :)

**Comment by dmurphy18** [comment]
@r-pufky I would recommend doing the following:

**apt remove --purge salt-common**

**salt-common** is the underlying common code that is used by salt-minion, salt-master, etc.

Suspecting that removing the salt-minion is leaving salt-common behind (as it does when I unit-test packaging changes), and that is affecting your system.

Can you try removing salt-common when completely removing Salt and see if that removes the issues you are encountering.

**Comment by r-pufky** [comment]
Sorry for the delayed update. I dig a bunch of digging through trace logs. Answer to your question first, actual bug below.

> Suspecting that removing the salt-minion is leaving salt-common behind (as it does when I unit-test 
> packaging changes), and that is affecting your system.
>
> Can you try removing salt-common when completely removing Salt and see if that removes the 
> issues you are encountering.

I purged and reinstalled but this did not fix it.

I enabled trace debugging and went through a bunch of minion runs. It looks like the behavior of **watch** changed in 2019.2 versus 2018.3. The minion would startup, and using `watch` would detect that minion files were changed, and then execute a service restart using SIGTERM via service management. This would restart the service, and force a `state.highstate` run on start (delayed by 30-60 seconds). The ``master_alive_interval` fired every 30 seconds, causing additional issues. In short: the salt-minion was running state.highstate every thirty seconds. `watch` would *now* detect and trigger on `file.recurse` regardless of actual file changes, unlike 2018.3.

init.sls (old minion config install, works 2018.3 minion, 2018.3/2019.2 master)
```yaml
copy_minion_configs:
  file.recurse:
    - name: {{ minion.get('path.linux', minion.path.linux) }}
    - source: {{ config.get('source', minion.source) }}
    - dir_mode: 0755
    - file_mode: 0744
    - user: root
    - group: root

minion_service:
  service.running:
    - name: {{ minion.service }}
    - enable: True
    - watch:
      - file: copy_minion_configs
```
* Referenced from here: https://github.com/saltstack/salt/issues/663#issuecomment-302128986

init.sls (updated minion config install 2019.2 fix)
```yaml
copy_minion_configs:
  file.recurse:
    - name: {{ minion.get('path.linux', minion.path.linux) }}
    - source: {{ config.get('source', minion.source) }}
    - dir_mode: 0755
    - file_mode: 0744
    - user: root
    - group: root

minion_service:
  service.running:
    - name: {{ minion.service }}
    - enable: True
    - onchanges:
      - file: copy_minion_configs
```

Summary:
Clearly between 2018.3 and 2019.2 minion, the behavior of `watch` changed (or was fixed, though I did *not* see it in the documentation). I verified this with:
* The current salt-master (as listed here).
* The current salt-minion (as listedt here).
* The previous salt-minion (2018.3.4+ds-1 -- and many previous versions, but not confirmed)

Below is a graph of a debian 9 system, running 2018.3.4+ds-1 salt-minion, with the original `init.sls`. You'll noticed that first salt-call runs highstate, and the second run performs as originally expected (e.g. highstate is *not* triggered).
![2018 3-salt-minion-debian-9-alternative-call](https://user-images.githubusercontent.com/4778046/54411035-19571480-46ab-11e9-9cbb-020f93862567.png)

I believe this to be an actual bug (or a fixed bug?

**Comment by Ch3LL** [comment]
okay my understanding of your issue is that when you used `watch` in conjunction with the `file.recurse` state the salt-minion service is being sent a SIGTERM to the salt-minion even though there where no changes in the `file.recurse` state. Is this the correct understanding of the issue?

i tried replicating with this state with no luck:

```
root@localhost:~# cat /srv/salt/test.sls
copy_minion_configs:
  file.recurse:
    - name: /tmp/test
    - source: salt://test
    - dir_mode: 0755
    - file_mode: 0744
    - user: root
    - group: root

minion_service:
  service.running:
    - name: salt-minion
    - enable: True
    - watch:
      - file: copy_minion_configs
```

I first check to make sure i get the PIDS for the salt-miion service:

```
root@localhost:~# ps uax |grep -i salt-mi
root      4450  0.1  1.4 147824 29488 ?        Ss   14:45   0:00 /usr/bin/python3 /usr/bin/salt-minion
root      4455  2.5  2.9 569716 59500 ?        Sl   14:45   0:04 /usr/bin/python3 /usr/bin/salt-minion
root      4458  0.0  1.4 245176 28944 ?        S    14:45   0:00 /usr/bin/python3 /usr/bin/salt-minion
root      4675  0.0  0.0  12784   924 pts/0    S+   14:48   0:00 grep -i salt-mi
```

Then i run teh state:

```
root@localhost:~# salt '*' state.sls test
23.239.23.239:
----------
          ID: copy_minion_configs
    Function: file.recurse
        Name: /tmp/test
      Result: True
     Comment: The directory /tmp/test is in the correct state
     Started: 14:48:17.054302
    Duration: 41.02 ms
     Changes:   
----------
          ID: minion_service
    Function: service.running
        Name: salt-minion
      Result: True
     Comment: The service salt-minion is already running
     Started: 14:48:18.412473
    Duration: 33.396 ms
     Changes:   

Summary for 23.239.23.239
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time:  74.416 ms
```

And as you can see above it shows both states in teh correct state without changes. and the PIDs are the same:

```
root@localhost:~# ps uax |grep -i salt-mi                                                                                                  
root      4450  0.1  1.4 147824 29488 ?        Ss   14:45   0:00 /usr/bin/python3 /usr/bin/salt-minion                                     
root      4455  1.9  2.9 569972 59504 ?        Sl   14:45   0:04 /usr/bin/python3 /usr/bin/salt-minion                                     
root      4458  0.0  1.4 245176 28944 ?        S    14:45   0:00 /usr/bin/python3 /usr/bin/salt-minion                                     
root      4723  0.0  0.0  12784   928 pts/0    S+   14:49   0:00 grep -i salt-mi                           
```

Am I just understanding the issue incorrectly? Any other help to try to replicate the issue?

Also note I tried this on deb9 python3 machine:

```
root@localhost:~# salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.8
         locale: UTF-8
        machine: x86_64
        release: 4.18.16-x86_64-linode118
         system: Linux
        version: debian 9.8
```

**Comment by r-pufky** [comment]
> okay my understanding of your issue is that when you used watch in conjunction with the file.recurse state the salt-minion service is being sent a SIGTERM to the salt-minion even though there where no changes in the file.recurse state. Is this the correct understanding of the issue?

I believe you are understanding it correctly.

I'll re-run testing this weekend and post detailed reports of minion, server; for both 2018 and 2019 minion versions. I was able to reproduce this twice before posting; so I'm fairly confident I can get it to trigger again.

**Comment by Ch3LL** [comment]
that would be great. I just need to be able to replicate when the watch triggers a restart even though the `file.recurse` state hasn't actually changed. thanks!

**Comment by r-pufky** [comment]
Apologies, I thought I had responded to this. I just re-ran the data (this data is from a singular test instance, running a 2018 test and a 2019 test):

2018.3.4, py2.7: No increase in load:
![debian-9-watch-state-2018 3 4-py2 7 13](https://user-images.githubusercontent.com/4778046/60473812-cedeb100-9c23-11e9-8bf3-f42c78a2b223.png)

2019.2.0, py3.5.3: Increase in load:
![debian-9-watch-state-2019 2 0-py3](https://user-images.githubusercontent.com/4778046/60473887-0baaa800-9c24-11e9-9ca8-7f0a3998729d.png)

I've attached the versions-report for these minions here:
[minion-data.log](https://github.com/saltstack/salt/files/3347748/minion-data.log)

## Note
I will state that moving from `watch` to `onchanges` is an effective workaround which I've been using.

**Comment by Ch3LL** [comment]
If you try my simple example do you see the same behavior?

**Comment by Ch3LL** [comment]
to be clear running this state: 

```
copy_minion_configs:
  file.recurse:
    - name: /tmp/test
    - source: salt://test
    - dir_mode: 0755
    - file_mode: 0744
    - user: root
    - group: root

minion_service:
  service.running:
    - name: salt-minion
    - enable: True
    - watch:
      - file: copy_minion_configs
```
