### ISSUE TITLE
manage multiple files in same state

### ISSUE THREAD

**Issue by wolfpackmars2** [saltstack/salt#52130]
### Edit
Turns out the original issue was caused by a typo :blush:. There may still be an opportunity to improve the docs by including a working example using the names declaration in a file.managed state.

### Description of Issue/Question
According to the docs, it should be possible to manage multiple files in one state using the 'names' parameter. However, the results in an error "Rendering SLS failed: mapping values are not allowed in this context"

Related #4508 - specifically [shorawitz commented on Feb 12, 2016](https://github.com/saltstack/salt/issues/4508#issuecomment-183411996)

The docs may be misleading and may need to be reviewed or a good, working example of managing multiple files using the names parameter should be added to the docs.

Related documentation links:
[https://docs.saltstack.com/en/2019.2/ref/states/all/salt.states.file.html#operations-on-regular-files-special-files-directories-and-symlinks](https://docs.saltstack.com/en/2019.2/ref/states/all/salt.states.file.html#operations-on-regular-files-special-files-directories-and-symlinks)
> The names parameter, which is part of the state compiler, can be used to expand the contents of a single state declaration into multiple, single state declarations. Each item in the names list receives its own individual state name and is converted into its own low-data structure. This is a convenient way to manage several files with similar attributes.
> 
> There is more documentation about this feature in the [Names declaration](https://docs.saltstack.com/en/2019.2/ref/states/highstate.html#names-declaration) section of the Highstate docs.

### Setup
Using either state:
```
salt_master_configuration_files:
  file:
    - managed
    - user: root
    - group: root
    - mode: '0644'
    - names:
      - /etc/salt/master.d/master.conf:
        - source: salt://saltmaster/master.conf
      - /etc/salt/minion.d/minion-99.conf
        - source: salt://saltmaster/minion.conf
```
or
```
salt_master_configuration_files:
  file.managed:
    - user: root
    - group: root
    - mode: '0644'
    - names:
      - /etc/salt/master.d/master.conf:
        - source: salt://saltmaster/master.conf
      - /etc/salt/minion.d/minion-99.conf
        - source: salt://saltmaster/minion.conf
```

### Steps to Reproduce Issue
Use state included in "setup" and run highstate

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-46-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by wolfpackmars2** [comment]
soooo... typos, they'll get you every time.

Managing multiple files in the same state DOES work, if you format the state properly.

Both of the following work:
```
salt_master_configuration_files:
  file:
    - managed
    - user: root
    - group: root
    - mode: '0644'
    - names:
      - /etc/salt/master.d/master.conf:
        - source: salt://saltmaster/master.conf
      - /etc/salt/minion.d/minion-99.conf
        - source: salt://saltmaster/minion.conf
```
and
```
salt_master_configuration_files:
  file.managed:
    - user: root
    - group: root
    - mode: '0644'
    - names:
      - /etc/salt/master.d/master.conf:
        - source: salt://saltmaster/master.conf
      - /etc/salt/minion.d/minion-99.conf
        - source: salt://saltmaster/minion.conf
```

Although this has been resolved, I think that adding an example to the docs will be beneficial.
