### ISSUE TITLE
Include State ID

### ISSUE THREAD

**Issue by grbolli** [saltstack/salt#52154]
### Description of Issue/Question
In one state, I would like to include an ID from another state, not the entire .sls

### Init.sls
```
docker_Package:
  pkg.installed:
    - name: docker-ce
    - version: {{ pillar['docker_version'] }}

docker_Py_package:
  pip.installed:
    - name: docker-py
```
### etcd.sls
```
include:
  - init
    - docker_Package
```
### Versions Report
Salt Version:
                Salt: 2018.3.2

I'm on a private network, can't copy and paste.

**Comment by waynew** [comment]
Hi @grbolli, thanks for reaching out! You might be able to get better/other ideas on the [Salt Users mailing list](https://groups.google.com/forum/#!forum/salt-users), [Salt Community Slack](https://saltstackcommunity.herokuapp.com/), or [#salt on Freenode](http://webchat.freenode.net/?channels=salt&uio=Mj10cnVlJjk9dHJ1ZSYxMD10cnVl83).

I'm pretty sure that what you're asking for is not possible. Practically speaking, you can include an entire state file, or not.

To accomplish the behavior that you're looking for, typically I try to map out my dependencies - in this case you have something like:

etcd -> docker_Package
??? -> docker_Py_package
docker_Py_package -> docker_Package (This may be an implicit dependency, or maybe it's not a dependency for you!)

What I would then do is something like this:

**docker.sls**
```
docker_Package:
  pkg.installed:
    - name: docker-ce
    - version: {{ pillar['docker_version'] }}
```

**etcd.sls**
```
include:
  - docker
```

**docker_py.sls**
```
include:
  - docker

docker_Py_package:
  pip.installed:
    - name: docker-py
```

This clearly spells out your dependencies and gets them where they aught to go. If you wanted, you could also use `exclude` to get the behavior that you want, but... that seems like it would be more fragile. You could do that like this (assuming your docker states were in `docker.sls`):

**etcd.sls**
```
include:
   - docker

exclude:
  - id: docker_Py_package
```

This is more prone to breakage, or installing extra packages, because any time someone adds something to your `init.sls` (or `docker.sls`) they're going to have to know that they need to figure out if they need to exclude it in your `etcd` state file.

If you have one state file that installs docker the app, and then one that installs docker the Python library that does an include on docker the app, you have a lot more granular control.

Does that answer your question?

(Also, from an implementation standpoint it seems unlikely that we'd be able to support including a single ID - that would effectively require redesigning and rewriting our state processing 😝)
