### ISSUE TITLE
salt_proxy.configure_proxy uses hard coded proxyfile path

### ISSUE THREAD

**Issue by awerner** [saltstack/salt#52169]
### Description of Issue/Question

The module `salt_proxy.configure_proxy` uses the hard coded path `/etc/salt/proxy`. This fails on any non-linux system such as *BSD. It would be better if the module would honor the paths defined in `salt.syspaths`, and in the long run a configurable configuration file path with reasonable defaults would be optimal.

### Setup

```yaml
proxy-xyz:
  salt_proxy.configure_proxy:
    - proxyname: xyz
    - start: True
```

### Steps to Reproduce Issue
- Use the provided state on any non-Linux OS
- The reported error:

```
                  Salt Proxy: Error writing proxy file [Errno 2] No such file or directory: '/etc/salt/proxy'
                  Salt Proxy: Error writing proxy file [Errno 2] No such file or directory: '/etc/salt/proxy'
```

### Versions Report

Also applies to all versions up to `develop`.
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.2
         Python: 3.6.6 (default, Dec  8 2018, 01:23:06)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: US-ASCII
        machine: amd64
        release: 12.0-RELEASE
         system: FreeBSD
        version: Not Installed
```
