### ISSUE TITLE
file.directory fails to check directory permissions correctly

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#52173]
### Description of Issue/Question
Running the `file.directory` state with `test=true` always reports changes to be made, even when the directories are in the desired state.

### Setup
```
salt-log-permissions:
  file.directory:
    - name: /var/log/salt
    - recurse:
      - mode
    - dir_mode: '2770'
    - file_mode: '0660'
```

```
# salt-call state.apply salt.logs test=false
local:
----------
          ID: salt-log-permissions
    Function: file.directory
        Name: /var/log/salt
      Result: True
     Comment: Directory /var/log/salt is in the correct state
     Started: 01:49:00.152027
    Duration: 59.972 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  59.972 ms

# salt-call state.apply salt.logs test=true
local:
----------
          ID: salt-log-permissions
    Function: file.directory
        Name: /var/log/salt
      Result: None
     Comment: The following files will be changed:
              /var/log/salt/api: mode - 0660
              /var/log/salt/master: mode - 0660
              /var/log/salt/key: mode - 0660
              /var/log/salt/minion: mode - 0660
              /var/log/salt: mode - 0660
     Started: 01:49:13.021802
    Duration: 33.664 ms
     Changes:   

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:  33.664 ms
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.8
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.6.8 (default, Feb  8 2019, 21:14:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.2-STABLE
         system: FreeBSD
        version: Not Installed
```
