### ISSUE TITLE
artifactory.downloaded downloads archive even "test=true' was set

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#52199]
The `artifactory.downloaded` state downloads the file even though I have `test=true` set.
I have a lot of other states that depend on `artifactory.downloaded` with the `onchanges` requisite. 

This causes problems because when I actually run my states with `test=false`, some states fail to run because the latest file is already downloaded when it was run in test mode.

And I couldn't use `artifactory.downloaded` for `prereq` either.

```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.13
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Feb 11 2019, 00:06:41)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE-p7
         system: FreeBSD
        version: Not Installed
```
