### ISSUE TITLE
beacon.present should merge configs, not overwrite them

### ISSUE THREAD

**Issue by dkfsalt** [saltstack/salt#52198]
### Description of Issue/Question

Enhancement Request:  Multiple State files that use beacon.present on the same type of beacon overwrite each other.  Ideally, the two configs would merge together in the beacons.conf, rather than overwritting them. 

This would give users greater flexibility in their ability to manage beacons on an application basis rather than globally (which increases the complexity of configuration and management of the beacons).

### Setup

```
# Because the inotify beacon relies on the python-inotify
# package, we must install it first
install_python_inotify:
  pkg.installed:
    - name: python-inotify

# Watch infs.conf
inotify_ssh:
  beacon.present:
    - name: inotify
    - save: True
    - enable: True
    - files:
       /etc/infs.conf:
         mask:
           - create
           - attrib
           - delete
           - delete_self
           - modify
           - moved_from
           - moved_to
           - move_self
         recurse: True
         auto_add: True
    - interval: 10
    - disable_during_state_run: True
    - require:
      - pkg: install_python_inotify

---------------
# Because the inotify beacon relies on the python-inotify
# package, we must install it first
install_python_inotify:
  pkg.installed:
    - name: python-inotify

# Watch ntp.conf
inotify_ntp:
  beacon.present:
    - name: inotify
    - save: True
    - enable: True
    - files:
       /etc/ntp.conf:
         mask:
           - create
           - attrib
           - delete
           - delete_self
           - modify
           - moved_from
           - moved_to
           - move_self
         recurse: True
         auto_add: True
    - interval: 10
    - disable_during_state_run: True
    - require:
      - pkg: install_python_inotify
```

The ideal result of running these two states would be an /etc/salt/minion.d/beacons.conf which looks like:

```
beacons:
  inotify:
  - files:
      /etc/ntp.conf:
        auto_add: true
        mask:
        - create
        - attrib
        - delete
        - delete_self
        - modify
        - moved_from
        - moved_to
        - move_self
        recurse: true
       /etc/infs.conf:
         mask:
           - create
           - attrib
           - delete
           - delete_self
           - modify
           - moved_from
           - moved_to
           - move_self
         recurse: True
         auto_add: True
  - disable_during_state_run: true
  - enable: true
  - interval: 10
```

The problem with this is the scoping of the "enable", "interval", "disable_during_state_run" parameters - in order to make this work, they would need to run on a per "files" definition basis and that pattern would need to be applied to other beacon types as well (like services).

Ideally, though, there would be a standard for beacon methods such that the states.beacon module simply calls the corresponding methods of the beacon module.  So that all beacons have the following methods:
 - present
 - enabled
 - disabled
 - validate 

eg:  beacon.present() would simply determine the type of module and call the corresponding present method of the beacon type (eg - "service.present()" or "inotify.present()".

Note:  I suspect the impact of this would be far reaching for the minion itself.

### Steps to Reproduce Issue

Put the two beacon.present configs into separate state files and apply them to a minion; the first config is overwritten by the second.

### Versions Report

Master 2018.3.3, Minion 2018.3.4 / 2019.02

**Comment by garethgreenaway** [comment]
@dkfsalt There is a feature I added to develop which I think might accomplish what you were looking for.  It allows you to specify a beacon_module in the configuration, eg.
```
beacons:
  watch_opt_special:
    - files:
        /opt/special:
          mask:
            - delete
            - close_write
          auto_add: True
    - coalesce: True
    - beacon_type: inotify
```

This would allow you to include multiple instances of the inotify beacon each with a different name.  I need to verify that it works when using beacon.present and properly document it.
