### ISSUE TITLE
pre-required state always runs twice regardless whether changes empty or not

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#52200]
According to the documentation
```
If the "changes" key contains a populated dictionary, it means that the pre-required state expects changes to occur when the state is actually executed, as opposed to the test-run. The pre-requiring state will now actually run. If the pre-requiring state executes successfully, the pre-required state will then execute. If the pre-requiring state fails, the pre-required state will not execute.

If the "changes" key contains an empty dictionary, this means that changes are not expected by the pre-required state. Neither the pre-required state nor the pre-requiring state will run.
```

The fact is that the pre-required state always runs whether there's any change or not.
The pre-requiring state only runs if changes are expected.

Lets make some clarification with the confusing terms used here:

```
test-a:
  salt.function:
    - name: service.stop
    - tgt: minion1
    - arg:
      - myservice
    - prereq:
      - test-b

test-b:
  salt.state:
    - tgt: minion1
    - sls:
      - mystate
```
In this example, `test-a` is the pre-requiring state, `test-b` is the pre-required state.
What happens it that `test-b` always run twice whether changes are expected or not.
Under normal situations, this doesn't hurt anything, but it would cause serious problem if `test-a` fail to generate `changes` in test mode, as in #49753 .

I know that the pchanges issue has already been fixed, but it would be nice to make `prereq` work as expected, or at least update the documentation.

**Comment by garethgreenaway** [comment]
@angeloudy So far I haven't been able to reproduce this one in either 2018.3 or 2019.2, can you provide the output from salt --versions-report so we know what version of Salt you're seeing this error in?  

The `prereq` state, in this case `test-b` will run twice.  Once with test=true and another without.  If there are expected changes during the test=true phase, then `test-a` should run.  If there are not, then `test-a` will not run.  Following that, `test-b` is run without test=True.

**Comment by amendlik** [comment]
I'm not sure what you mean by this:

> I know that the pchanges issue has already been fixed

If you are referring to #45895, it has only been fixed on the develop branch. Those changes have not been released yet.

**Comment by angeloudy** [comment]
@garethgreenaway,

That's exactly what I mean, `test-b` should only run once if there are no changes or if `test-a` fails according to the documentation.

Here's my salt version

```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Feb 11 2019, 00:06:41)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE
         system: FreeBSD
        version: Not Installed
```

**Comment by angeloudy** [comment]
Let me give you a more specific example:

```
test-a:
  salt.function:
    - name: service.stop
    - tgt: minion1
    - arg:
      - httpd
    - prereq:
      - test-b

test-b:
  salt.state:
    - tgt: minion1
    - sls:
      - mystate


mystate.sls:
download_archive:
  artifactory.downloaded:
        - artifact:
           artifactory_url: https://repo.xxx.xxxx.xx/
           repository: 'snapshots'
           artifact_id: client
           group_id: 'ish.test.server'
           packaging: 'zip'
           classifier: 'webstart'
           version: 'SNAPSHOT'
      -   target_file: /tmp/test.zip

```
In this example, `test-a` doesn't run because `artifactory.downloaded` can't generate any changes in test mode.

**Comment by angeloudy** [comment]
@amendlik 
Do you know what release that PR will be merged into?
I can see that it's fixed on October 2018.

**Comment by angeloudy** [comment]
#45895 is irrelevant to this issue.
The problem with this issue is that the pre-required state always runs twice, first time in test mode, second time in real.

Normally this is OK.
However when things goes wrong, when a state is not able to generate changes in test mode, it would be disastrous.

For example, `artifactory.downloaded` was designed to always generate empty changes, which I believe is a bug.

**Comment by angeloudy** [comment]
@garethgreenaway 

Here's the orchestration state I have problem with:
```
haproxy_stop_{{ application }}_{{ backend }}:
  salt.function:
    - tgt: 'role:haproxy'
    - tgt_type: pillar
    - name: haproxy.disable_server
    - arg:
      - {{ backend }}
      - {{ application }}

    - prereq:
      - upgrade_{{application}}_{{backend}}



upgrade_{{application}}_{{backend}}:
   salt.state:
       - tgt: 'role:application'
       - tgt_type: pillar
       - sls:
         - myapp


haproxy_start_{{ application }}_{{ backend }}:
  salt.function:
    - tgt: 'role:haproxy'
    - tgt_type: pillar
    - name: haproxy.enable_server
    - arg:
      - {{ backend }}
      - {{ application }}
    ```

What it suppose to do is that if there's a new version of application available, first stop it in haproxy, then do the upgrade and then start it haproxy.

Because `myapp.sls` uses `artifactory.downloaded` state, the first state never run, which caused huge outages for us.
