### ISSUE TITLE
SALT - No Top file or external nodes data matches found.

### ISSUE THREAD

**Issue by rajkamal31** [saltstack/salt#52231]
I am facing this error 'No Top file or external nodes data matches found.'. We have setup 2 environments base and test. testdir state is to create /tmp/testfile and testfile1 is to create /tmp/testfile1 files. 

/etc/salt/master configuration:

```
file_roots:
  base:
    - /srv/salt/base
  test:
    - /srv/salt/base
    - /srv/salt/test

top_file_merging_strategy: merge_all
```

----------------------------------------------------

```
master:/srv/salt # ls
base  test  top.sls

master:/srv/salt # cat top.sls

base:
  '*':
    - testdir
test:
  'minion1':
    - testfile1
  'minion2':
    - testfile1
master:/srv/salt # cd base/
master:/srv/salt/base # ls
testdir
master:/srv/salt/base # ls -ltr testdir/
total 4
-rw-r--r-- 1 root root 82 Mar 15 13:50 init.sls
master:/srv/salt/base # ls
testdir
master:/srv/salt/base # cat testdir/init.sls
Create a testfile in /tmp for base:
  file:
    - touch
    - name: /tmp/testfile
```

```
master:/srv/salt # ls -ltr test
total 0
drwxr-xr-x 1 root root 16 Mar 15 13:50 testfile1
master:/srv/salt # ls -ltr test/testfile1/
total 4
-rw-r--r-- 1 root root 84 Mar 15 13:50 init.sls
master:/srv/salt # cat test/testfile1/init.sls
Create a testfile1 in /tmp for test:
  file:
    - touch
    - name: /tmp/testfile1
```

```
master:/srv/salt/test # salt 'minion1' state.highstate
minion1:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Changes:

Summary for minion1
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
```

**Comment by Ch3LL** [comment]
your top.sls file needs to be in one of your environment directory paths. So in your example:

```
file_roots:
  base:
    - /srv/salt/base
  test:
    - /srv/salt/base
    - /srv/salt/test
```

it would need to be in /srv/salt/base or /srv/salt/test
