### ISSUE TITLE
mine.get targeting grains doesn't work (anymore)

### ISSUE THREAD

**Issue by JustKiddingCode** [saltstack/salt#52257]
### Description & Setup
In my grains, i have a list of services my host is providing.

With mine.get I can see all grains.
I can see the data is correct in the mine (json Output)

```
{
    "nahum01": {
        "sim-gloin": {
            "services": [
                "salt-master",
                "icinga",
                "apt-dater-server"
            ],
            [...]
    }
}
```
```
{
    "nahum01": {
        "sim-radagast": {
[...]
            "services": [
                "cups-server",
                "syslog-server",
                "apt-cacher-ng",
                "email-server",
                "ispe-qm"
            ],
        }
    }
}
```

I wan't to target on services:icinga.

If i run: 
`salt-call mine.get 'services:email-server' grains.item tgt_type=grain`
its returning as expected
```
# salt-call mine.get 'services:email-server' grains.item tgt_type=grain
local:
    ----------
    sim-radagast:
[...]
        services:
            - cups-server
            - syslog-server
            - apt-cacher-ng
            - email-server
            - ispe-qm
```

But if i run
```
# salt-call mine.get 'services:icinga' grains.item tgt_type=grain
local:
    ----------
```

**edit:** I would expect the grains of sim-gloin here.

### Setup
The minion with the which runs icinga is the salt master.
The data is available on all minions, filtering the "email-server" works on all minions, however filtering "icinga" doesn't work on any of them.
I took a look into both the minion debug log and the master debug log but didn't find any suspicious information.

### Steps to Reproduce Issue
I can't think of a way to reproduce this.

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.8
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8

```

**Comment by garethgreenaway** [comment]
@JustKiddingCode Thanks for the report.  Can you explain what exactly you're trying to accomplish with the above setup?

**Comment by JustKiddingCode** [comment]
I used to dynamically load the Icinga Server Adress in my states files with:
`{%- set server, addrs = (salt['mine.get']('services:icinga','network.ip_addrs',tgt_type='grain').items() | first) -%}`
Used this since 2017, but somehow when I made the last highstate the above command failed, stating that the list was empty. So I tried to make this work on the command line and failed at it.

**Comment by garethgreenaway** [comment]
@JustKiddingCode I was testing this out and the only way I am able to reproduce what you're seeing is if the function, eg. `network.ip_addrs` I am calling is not configured in the mine configuration for the minion.  I see this result in both 2018.3 and 2019.2.  Can you provide what your `mine_functions` configuration looks like for the particular minion where you're seeing the issue?   Thanks!

**Comment by JustKiddingCode** [comment]
Thanks for the reply.
The mine_functions configuration is the same on all minions, it seems like its also correct in the pillar.
I tried further with test.ping. with different data from the grains.
Nothing is working here.
Could it be that **tgt_type=grain** is not working?

```
root@sim-gloin:/var/log/salt# salt-call pillar.get mine_functions
local:
    ----------
    grains.item:
        - osfinger
        - lsb_distrib_description
        - hwaddr_interfaces
        - num_cpus
        - physically_interfaces
        - cpu_model
        - ip4_interfaces
        - mem_total
        - gpus
        - services
        - type
    network.ip_addrs:
    test.ping:
root@sim-gloin:/var/log/salt# salt nahum01 pillar.get mine_functions
nahum01:
    ----------
    grains.item:
        - osfinger
        - lsb_distrib_description
        - hwaddr_interfaces
        - num_cpus
        - physically_interfaces
        - cpu_model
        - ip4_interfaces
        - mem_total
        - gpus
        - services
        - type
    network.ip_addrs:
    test.ping:

```
