### ISSUE TITLE
AttributeError using TCP transport

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#52271]
### Description of Issue/Question
Every invocation of the `salt` command, or `salt-call` (without `--local`) produces the following error:
```
Exception ignored in: <generator object _stream_return at 0x8141f7258>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/transport/tcp.py", line 1057, in _stream_return
AttributeError: 'NoneType' object has no attribute 'StreamClosedError'
```
The symptom appears to be the same as #41407. The commands still complete successfully, so this issue is mostly cosmetic.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.8
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.6.8 (default, Feb  8 2019, 21:14:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.2-STABLE
         system: FreeBSD
        version: Not Installed
```
