### ISSUE TITLE
Can't get ext module (_grains) to be loaded at will

### ISSUE THREAD

**Issue by Xaelias** [saltstack/salt#52280]
### Description of Issue/Question
Hi!
So the setup I have for this is a little weird, which is probably why I'm having so much trouble.
We have a master (let's call it `salt01`), but the minions I'm interested in right now don't run salt-minion as a daemon. Rather it's invoked manually when the need arise.

The minion (let's call it `minion01` (there are actually more than one)), relies on the git repo.
The master is configured to use gitfs with pygit2. See config below.

Now, we have some custom python files to generate custom grains.
Before they were in a bogus repo that only purpose was basically to serve these modules. I'm trying to merge them in that relevant git repo.
 But I can't find a way, either by running a command on the minion to pull these modules, or by having them being automatically pulled when applying states, to make this work.

### Setup
relevant master config:
```
  file_roots:
    base:
      - /mnt/salt/config_management/base
  top_file_merging_strategy: same
  fileserver_backend:
    - git
    - roots
  gitfs_provider: pygit2
  gitfs_remotes:
    - git@git.example.com:dev/salt-formula.git:
      - pubkey: '/root/.ssh/deploy_key_saltmaster.pub'
      - privkey: '/root/.ssh/deploy_key_saltmaster'
      - root: state
      - saltenv:
        - my_environment_name:
          - ref: master
  ext_pillar:
    - git:
      - master git@git.example.com:dev/salt-formula.git:
        - env: my_environment_name
        - root: pillar
        - privkey: /root/.ssh/deploy_key_saltmaster
        - pubkey: /root/.ssh/deploy_key_saltmaster.pub
      - __env__ git@git.example.com:dev/salt-formula.git:
        - root: pillar
        - privkey: /root/.ssh/deploy_key_saltmaster
        - pubkey: /root/.ssh/deploy_key_saltmaster.pub
```

minion config:
```
master:
  - salt01

use_superseded:
  - module.run

master_type: failover
master_shuffle: True
master_alive_interval: 30
auth_tries: 10
master_tries: -1
retry_dns: 0
master_finger: '<fingerprint>'
```

The two modules are currently stored in:  
`/mnt/salt/config_management/my_environment_name/_grains/`

top.sls file:
```
my_environment_name:
  'as*':
    - some_conf
```

### Steps to Reproduce Issue
What I tried to run on minion01:
```
salt-call saltutil.sync_all
salt-call saltutil.sync_all saltenv=my_environment_name
salt-call saltutil.sync_all refresh=True
salt-call saltutil.sync_all refresh=True saltenv=my_environment_name
salt-call state.apply
salt-call state.apply saltenv=my_environment_name
salt-call state.apply some_conf
salt-call state.apply some_conf saltenv=my_environment_name
```
I've tried cleaning the cache on the master too just in case.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.13
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1032-aws
         system: Linux
        version: Ubuntu 18.04 bionic
```

Thank you all for the help!!!

[EDIT] Adding minion config
