### ISSUE TITLE
Issue with opts.pillar_roots in runners

### ISSUE THREAD

**Issue by jochenschreiber** [saltstack/salt#52284]
### Description of Issue/Question
My goal is to render a pillar based of a grain on a minion. I adapted my pillar top file to use that:

```
{%- set pillarpath = opts.pillar_roots[saltenv] %}
{{ saltenv }}:
{%- for path in pillarpath %}
  {%- if salt["file.file_exists"]('{0}/mypillar/{1}.sls'.format(path, grains['mypillar'])) %}
    {{ salt.slsutil.renderer(path ~ '/mypillar/' ~ grains['mypillar'] ~ '.sls') }}
  {%- endif %}
{%- endfor %}
```

This works in case i execute the highstate directly via salt cli. Also `pillar.items` show me the right pillar information but when i execute my runner it directly fails while rendering the pillar top file:

```
[DEBUG   ] Rendered data from file: /var/cache/salt/master/git_pillar/06fe72fa72f4966cdf9ac4a8f1ad5ad193768962653d73a01a200c59d1affce6/pillar/top.sls:

MYENV:
[DEBUG   ] Results of YAML rendering:
OrderedDict([('MYENV', None)])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/master/git_pillar/06fe72fa72f4966cdf9ac4a8f1ad5ad193768962653d73a01a200c59d1affce6/pillar/top.sls' using 'yaml' renderer: 0.0006544589996337891
[CRITICAL] Pillar render error: Error encountered while rendering pillar top file.
```

It seems that `opts.pillar_roots` is not returning the path to the pillars on the minion during the runner exection. Can somebody help me to find my issue?

### Setup
salt 2018.3.4 py3 AMD 64

### Steps to Reproduce Issue
See description

### Versions Report
```
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```
