### ISSUE TITLE
pillar empty with ext_pillar

### ISSUE THREAD

**Issue by x70b1** [saltstack/salt#52319]
I'm trying to use a git repo as a pillar. But it is still empty. This is my master config:

```
ext_pillar:
    - git:
        - master https://example.com/saltstack/pillar.git:
            - env: base
            - user: xxx
            - password: xxx
```

The `master` branch of my repo:
```
.
├── pushover
│   └── init.sls
└── top.sls
```

My top.sls:

```
base:
    '*':
        - pushover
```

I feel a little foolish. Have I forgotten something essential?

```
salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.28.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.0
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.8 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8 
```
