### ISSUE TITLE
Feature Request: xfs_growfs support, either in the xfs module or the disk.resize2fs function.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#52331]
### Description of Issue/Question

Feature request for `xfs_growfs` support,  either as a new item to add to the `xfs` module or as a property of the `disk.resize2fs` function.

**Comment by whytewolf** [comment]
not stale

**Comment by bdrx312** [comment]
Is there any status on this? I have an xfs filesystem on an AWS ebs volume and I would like to use salt to extend the filesystem to always take up the full size of the ebs if we increase the size of the ebs. 
In ansible I use the filesystem module like this:

```yaml
- name: grow filesystem
  filesystem:
    dev: /dev/device1
    fstype: xfs
    resizefs: yes
```
Is there some equivalent state module that supports growing the xfs filesystem in salt?
