### ISSUE TITLE
Rendered Jinja with raw block give valid yaml but Salt crash

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#52336]
Hi,

I have this Jinja template

```
docker:
  use_upstream_repo: true
  proxy: '22.0.53.8:3128'
  pkg:
    name: 'docker-ce'
  daemon_config:
    metrics-addr: '0.0.0.0:9323'
    experimental: true
    registry-mirror: 'https://proxy-docker.ssllab.com:5000'
    live-restore: true
    insecure-registries:
      - harbor.engsec
      - repos.engsec
    log-driver: journald
    log-opts:
      {%- raw %}
      tag: {{.Name}}/{{.ID}}
      {%- endraw %}
  repo:
    url_base: ....
```

If I render it in with Jinja it gives me 
```
---
docker:
  use_upstream_repo: true
  proxy: '22.0.53.8:3128'
  pkg:
    name: 'docker-ce'
  daemon_config:
    metrics-addr: '0.0.0.0:9323'
    experimental: true
    registry-mirror: 'https://proxy-docker.ssllab.com:5000'
    live-restore: true
    insecure-registries:
      - harbor.engsec
      - repos.engsec
    log-driver: journald
    log-opts:
      tag: {{.Name}}/{{.ID}}
  repo:
    url_base: ....
```

But Salt crash with this error

```
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 17, column 7
did not find expected key
  in "<unicode string>", line 17, column 21
```

I also tried with `{{ '}}' }}Name{{ '}}' }}` without success

If anyone have an idea ...

Best regards,

```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.5
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.4.9 (default, Feb  5 2019, 14:36:09)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by Poil** [comment]
got it via

```
docker:
  use_upstream_repo: true
  proxy: '22.0.53.8:3128'
  pkg:
    name: 'docker-ce'
  daemon_config:
    metrics-addr: '0.0.0.0:9323'
    experimental: true
    registry-mirror: 'https://proxy-docker.ssllab.com:5000'
    live-restore: true
    insecure-registries:
      - harbor.engsec
      - repos.engsec
    log-driver: journald
    log-opts:
      tag: >-
        {%- raw %}
        {{.Name}}/{{.ID}}
        {%- endraw %}
  repo: ......
```
