### ISSUE TITLE
Environ.setenv return unicode

### ISSUE THREAD

**Issue by xiaoxiaojushi-ivan** [saltstack/salt#52372]
```
cat Set_ENV.sls
set_env:
  environ.setenv:
    - name: matter
    - value: {{pillar['env']}}
    - update_minion: True
```

```
curl -sSk https://salt-api:8000 \
     -H 'Content-type: application/json; charset=UTF-8' \
     -H 'Accept: application/x-yaml' \
     -H "X-Auth-Token: 48ed68a256a9f5a25ef078f8efce58ca" \
     -d '[{
          "client": "local",
          "tgt": "127.1.33.193",
          "fun": "state.sls",
          "tgt_type": "list",
          "arg": "Set_ENV",
          "kwarg": {"saltenv":"prod","pillar":{"env":{"PROFILE":"prod"}}}
      }]'
return:
- 127.1.33.193:
    environ_|-set_env_|-matter_|-setenv:
      __id__: set_env
      __run_num__: 0
      __sls__: Set_ENV
      changes:
         PROFILE: u'prod'
      comment: Environ values were set
      duration: 0.412
      name: matter
      result: true
      start_time: '03:44:51.501446'
```

```
salt-api -V
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Aug 11 2015, 23:39:10)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.1.10-17.31.amzn1.x86_64
         system: Linux
        version: Not Installed
```
```
salt-minion -V
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb 20 2019, 09:59:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-573.7.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

**Execute the state.sls file through the salt-api interface. Environ.setenv sets the environment variable and the value is unicode. How to solve it?**
