### ISSUE TITLE
onfail_stop is not documented

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#52380]
### Description of Issue/Question
the onfail_stop requisite is not documented.

It seems that it stops the states marked as onfail from being errored if an onfail_stop state succeeds.

**Comment by gtmanfred** [comment]
Also, if that is how it works, then #16291 should be closed.

**Comment by max-arnold** [comment]
Bump

**Comment by OrangeDog** [comment]
If that is what it does then it's a bad name. It sounds like it should stop execution in some way.

Before it's documented (and officially supported) change it to e.g. `onfail_suppress`, or a more composable way of doing it.

**Comment by CrackerJackMack** [comment]
I agree with the shit naming. But this is precisely what I need for functionality. At least documenting it would help.

**Comment by max-arnold** [comment]
I agree it is badly named, the usage is not intuitive, and it is not a requisite but a flag, and the flag is [`true` by default](https://github.com/saltstack/salt/pull/39874/files#diff-397d2335b6eb0721edaac6c17454c98ba80d978a157d7d0d19c4b8cf9d7f43bdR1901):

```yaml
Failing state:
  test.fail_without_changes: []

Failing state handler:
  test.succeed_with_changes:
    - onfail_stop: false
    - onfail:
      - test: Failing state
```

```
salt-call state.apply onfail_stop >/dev/null; echo $?
[ERROR   ] Failure!
0
```

What this does is ensures the resulting retcode is 0. See https://github.com/saltstack/salt/pull/39874
