### ISSUE TITLE
file.line after does not add text

### ISSUE THREAD

**Issue by stratusjerry** [saltstack/salt#52405]
### Description of Issue/Question
file.line after does not add the "content" text if the beginning of the content text to be inserted matches a line preceding the "after" line. My theory is the issue is an improper regex match of text, not taking into account whitespace

### Setup
SLS File:
```
/tmp/filetest:
  file.line:
    - after: "# This is a comment"
    - mode: ensure
    - content: "some  new  text"
```
/tmp/filetest contents:
```
# This is a comment
some  text  with  spaces

```

### Steps to Reproduce Issue
Running the state returns "No changes needed to be made". Removing whitespace from the file.line "content" portion will properly add the text. Example of the removed whitespace SLS that works properly:
```
/tmp/filetest:
  file.line:
    - after: "# This is a comment"
    - mode: ensure
    - content: "somenew  text"
```

### Versions Report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 3.5.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.1
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.13
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-142-generic
         system: Linux
        version: Ubuntu 16.04 xenial
