### ISSUE TITLE
race condition when using user.primary_group in state

### ISSUE THREAD

**Issue by poofyteddy** [saltstack/salt#52430]
Hello,
I try to make a folder who is own by both user UID and GID.
I try do to this with user.primary_group(username) and it work well if the user exist when i run the state. But if i run it from a blank server, where is user isn't yet defined, it will failed.
### Setup
the state i have defined is the following
```
ssh_dir_user_{{ username }}:
  file.directory:
    - name: ~{{ username }}/.ssh
    - user: {{ username }}
    - group: {{ salt['user.primary_group'](username) }}
    - dir_mode: 700
    - require:
      - user: {{ username }}
```
The user should be create before this state run by a `user.present`
but because the state are build before anything run, i'm getting this error
```
 Rendering SLS 'base:users' failed: mapping values are not allowed here; line 48
ssh_dir_user_rmt-script:
  file.directory:
    - name: ~rmt-script/.ssh
    - user: rmt-script
    - group: id: 'rmt-script': no such user    <======================
    - dir_mode: 700
    - require:
      - user: rmt-script
```
Is there any way to force running some state before building the other ?

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.8
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8

**Comment by waheedi** [comment]
You can order your states in different ways, but I think that's not the issue here

`- group: id: 'rmt-script':` I think this line is incorrect what happens if you change it to `- group: rmt-script` ?

**Comment by poofyteddy** [comment]
Thank's for the reply @waheedi.
the line `- group: id: 'rmt-script': no such user` you see is generated by `{{ salt['user.primary_group'](username) }}` in the state.
Because when the sls file is render by Jinja, the users doesn't yet exist, `salt['user.primary_group']("rmt-script")` return an error message : `id: 'rmt-script': no such user`

if i swap `- group: {{ salt['user.primary_group'](username) }}` by `- group: {{ username }}`; effectively what you are asking; it only work if the primary group of the said user is named identically to the user.

This sadly won't work for all user since some of theme have a shared primary group (for example, i have some publish user who's primary group is www-data)

**Comment by waheedi** [comment]
sure @poofyteddy. If the salt['user.primary_group'](username) variable is not yet defined jinja will render whats inside it. 

Can you run `salt minion state.apply create_user_x` before hand?

**Comment by waheedi** [comment]
@poofyteddy also another way would be to have what's inside rmt-script run before the ssh_dir_user_username in the same file. I know these are all workarounds for the issue and I believe I understand the essence of the issue here. Still a valid issue i believe

**Comment by poofyteddy** [comment]
@waheedi This is my entire sls for user management. i know it's quite a mess, but i hop it will help you understand the way i do it : 
```
#####################################
###  This state create the user,  ###
###  the groupe, and manage home  ###
###  and file                     ###
#####################################


{% for username, userconf in pillar.get('user_list', {}).items() %}
manage_user_{{ username }}:
  #User by itself
  user.present:
    - name: {{ username }}
    - fullname: "{{ userconf.get('fullname', username) }}"
    - home: {{ userconf.get('homedir', "/home/" + username) }}
    {% if userconf.get('uid') != None %}
    - uid: {{ userconf.get('uid') }}
    {% endif %}
    {% for groupname, groupconf in userconf.get('groups', {}).items() %}
      {% if groupconf != None %}
        {% if groupconf.get('primary', false) == true %}
    - gid: {{ groupconf.get('gid', groupname) }}
        {% endif %}
      {% endif %}
    {% endfor %}
    - groups:
    {% for groupname, groupconf in userconf.get('groups', {}).items() %}
      {% if groupconf != None %}
        {% if groupconf.get('primary', false) == false %}
      - {{ groupconf.get('gid', groupname) }}
        {% endif %}
      {% else %}
      - {{ groupname }}
      {% endif %}
    {% endfor %}
    {% if userconf.get('system', false) == true %}
    - system: true
    - shell: {{ userconf.get('shell', "/sbin/nologin") }}
    {% else %}
    - shell: {{ userconf.get('shell', "/bin/bash") }}
    {% endif %}
    - enforce_password: false
    {% if userconf.get('password') != None %}
    - password: {{ userconf.get('password') }}
    {% endif %}

  {% if userconf.get('sudo') != None %}
  #Apply Sudo Right
  file.managed:
    - name: /etc/sudoers.d/{{ username }}
    - user: root
    - group: root
    - mode: 440
    - template: jinja
    - source: salt://users/files/sudoers.jinja
    - check_cmd: /usr/sbin/visudo -c -f
    - context:
        username: {{ username }}
        userconf: {{ userconf }}
  {% endif %}

ssh_dir_user_{{ username }}:
  file.directory:
    - name: ~{{ username }}/.ssh
    - user: {{ username }}
#    - group: {{ salt['user.primary_group'](username) }}
    - dir_mode: 700
    - require:
      - user: {{ username }}

#Allow authorized_key
{% if userconf.get('allow_ssh_key') != None %}
ssh_allow_key_{{ username }}:
  ssh_auth:
    - present
    - user: {{ username }}
    - names:
    {% for sshkey in userconf.get('allow_ssh_key', {}) %}
      - {{ sshkey }}
    {% endfor %}
    - require:
      - user: {{ username }}
{% endif %}

{% endfor %}
```
as you can see, i do run the `user.present` before the `file.managed` but the way jinja templating work, it won't respect requirement, those only affect the order of the state.
i can't make it only create the user because it's in the same sls file, but if i create the user by hand, and then run the state who fail, it will work. sadly this isn't compatible with an automated deployment.

**Comment by waheedi** [comment]
It's a chicken or egg case :) I believe many people have been in the same situation as yours. I believe a lazy evaluation of these variables would be a great practice but not sure how that would be implemented in jinja and salt together. It's really intriguing though!

There are several work arounds, but you have to change things on your end.

Keep your user management as it is (not happy to say that :), as its against my engineering principles e.g Single responsibility classes). 
Then create another sls file that holds the `ssh_dir_user_{{ username }}:` config and apply that state after the useradd state.

**Comment by waheedi** [comment]
One other option @poofyteddy  which I think can solve your issue is using a salt slot, more on that here https://docs.saltstack.com/en/latest/topics/slots/index.html

I was looking for a more solid solution, but this one is sufficient i believe.

**Comment by poofyteddy** [comment]
@waheedi Thank's for your input, sadly making another sls file should not work during a highstate for what i understand (i will try it anyway but today was a long day :) ) but i didn't know about salt slots, that's something i really needed for other project and i'm very glad you introduce me to it !

I'll get in touch when i will have try both. i'm kinda surprised that making a folder owned by the primary group of a user isn't a more wide spread issue.

**Comment by poofyteddy** [comment]
Hey ! i'm back and i have test both as promise. Sorry for the delay, you did reply promptly to MY interrogation, and i didn't followed back the same way... sadly we work with salt v 2017.something at work so no way to test slots there.
Anyway, i do confirm that simply spiting the state in 2 sls file, and running first the `user.present` and then the `file.directory` didn't work. Simply because the value was calculated during jija templating, way before the salt run.

But the slots solution worked very well ! This option is for me a game-changer, especially when it come to setting up the network with salt. i am no-longer stuck with value from when i started my highstate :slightly_smiling_face: 

here is the simple edditing i did on my `file.directory` state.
```
ssh_dir_user_{{ username }}:
  file.directory:
    - name: ~{{ username }}/.ssh
    - user: {{ username }}
    - group: __slot__:salt:user.primary_group({{ username }})
    - dir_mode: 700
    - require:
      - user: {{ username }}
```
Jinja render this : 
```
ssh_dir_user_rmt-script:                                                                                                                                                                                           
  file.directory:                                                                                                                                                                                                  
    - name: ~rmt-script/.ssh                                                                                                                                                                                       
    - user: rmt-script                                                                                                                                                                                             
    - group: __slot__:salt:user.primary_group(rmt-script)                                                                                                                                                          
    - dir_mode: 700                                                                                                                                                                                                
    - require:                                                                                                                                                                                                     
      - user: rmt-script    
```
and salt get the value only when the state run.

I don't know if this is really recommended, but it does fit my need and fix more problem than just this one. Thank's !
