### ISSUE TITLE
docker_image.present incorrectly returns success

### ISSUE THREAD

**Issue by fpicot** [saltstack/salt#52444]
### Description of Issue/Question
When using docker_image.present to pull images from a private registry, if the image version is not available on the registry the state will return a success while logging an error in the comments : 
```          ID: docker-failed-pull
    Function: docker_image.present
      Result: True
     Comment: Image 'image_name:bad_version' was pulled
     Started: 17:43:35.183693
    Duration: 2126.195 ms
     Changes:   
              ----------
              Errors:
                  - Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on local_dns_server: server misbehaving
              Time_Elapsed:
                  0.021245956420898438
              retcode:
                  1
```
(Note : the error about dns lookup is because this docker host is isolated and can only pull from our private registry)

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
docker-failed-pull:
  docker_image.present:
    - name: image_name:bad_version
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  1 2018, 03:12:47)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: oracle 7.6
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: Oracle Linux Server 7.6
```

**Comment by Ch3LL** [comment]
@fpicot do you know if this was working on a previous version of salt?

**Comment by fpicot** [comment]
Just tried to downgrade to salt 2017.7.8-1, it seems it was working correctly : 
```
          ID: test-docker
    Function: docker_image.present
      Result: False
     Comment: Encountered error pulling bad_image:bad_version: Pull failed for bad_image:bad_version. Error(s) follow:

              Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on local_dns_server: server misbehaving
     Started: 13:31:14.184092
    Duration: 1015.61 ms
     Changes:
```
