### ISSUE TITLE
rename directory in Windows with state.file.rename

### ISSUE THREAD

**Issue by llmuculusll** [saltstack/salt#52530]
### Description of Issue/Question
When I execute the state, this error encounters:
somenodes:
----------
```
          ID: extract_telegraf
    Function: archive.extracted
        Name: C:\Program Files\
      Result: True
     Comment: salt://telegraf/files/telegraf-1.10.2_windows_amd64.zip extracted to C:\Program Files\, due to absence of one or more files/dirs
     Started: 20:53:18.245888
    Duration: 1515.676 ms
     Changes:

              extracted_files:
                  - telegraf/
                  - telegraf/telegraf.conf
                  - telegraf/telegraf.exe

          ID: rename_telegraf
    Function: file.rename
        Name: C:\Program Files\Telegraf\
      Result: False
     Comment: The target directory C:\Program Files\Telegraf is not present
     Started: 20:53:19.761564
    Duration: 0.0 ms
     Changes:
Summary for somenodes

Succeeded: 1 (changed=1)
Failed:    1

Total states run:     2
Total run time:   1.516 s
ERROR: Minions returned with non-zero exit code
```

### Setup
State File:
```
extract_telegraf:
  archive.extracted:
    - name: "C:\\Program Files\\"
    - source: salt://telegraf/files/telegraf-1.10.2_windows_amd64.zip
  file.rename:
    - name: "C:\\Program Files\\Telegraf\\"
    - source: "C:\\Program Files\\telegraf\\"
    - force: True
```

### Steps to Reproduce Issue
`$ salt "somenodes" state.apply -t 60`

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-20-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
