### ISSUE TITLE
Allow order inheritance in sls or includes

### ISSUE THREAD

**Issue by dlanderson** [saltstack/salt#5255]
It would be handy to be able to define order inheritance for sls and for includes. E.g:

```
# cat top.sls
base:
  'salttest*':
    - core:
      - order: 1
    - firewall
    - locale
...
```

During the loading of core.sls, any functions or sls files included by core.sls that do not already have an explicit order would inherit 'order: 1'. Otherwise the defined orders are honored.

Similarly for includes:

```
# cat core/init.sls
include:
  - core.motd
    - order: 1
  - core.packages
    - order: 2
  - core.shells
    - order: 1
  - locale
    - order: 3
  - repos.default
    - order: 1
```

**Comment by gtmanfred** [comment]
Did this ever happen?

**Comment by basepi** [comment]
Unknown. His fix is definitely in recent releases of salt, so have you seen it working or not, @gtmanfred?

**Comment by basepi** [comment]
In retrospect I do not think this was implemented, I think I was just confused. States are ordered in the order they appear by default since 0.17.0, but we still don't have the ability to give explicit `order: ` requisites from the topfile.

**Comment by alexandr-orlov** [comment]
What about explicit order for includes like:
```
# cat core/init.sls
include:
  - core.motd
    - order: 1
  - core.packages
    - order: 2
  - core.shells
    - order: 1
  - locale
    - order: 3
  - repos.default
    - order: 1
```
Sometimes it can be very useful.
