### ISSUE TITLE
msi installer packaged with Salt took down many Cisco Node Manager services

### ISSUE THREAD

**Issue by LaughHammers** [saltstack/salt#52587]
### Description of Issue/Question

I pushed VMWare Log Insight Agent with packaged with Salt to our production environment and a Cisco communication node's services were killed. 

After what appeared to be a successful deployment, several services were stopped. The logs all cited "**_exited from Ctrl-C or window close_**" as the description.

What could have caused this and how can this be avoided? A simple installer package took down a whole comms server.

### Setup

init.sls

```
loginsight_installer:
  pkg.installed:
    - name: loginsight_pkg

loginsight_conf:
  file.managed:
    - source: salt://binaries/loginsight/liagent.ini
    - name: "C:\\ProgramData\\VMware\\Log Insight Agent\\liagent.ini"
    - require:
      - pkg: loginsight_installer

loginsight_service:
  service.running:
    - name: LogInsightAgentService
    - require:
      - file: loginsight_conf
    - watch:
      - file: "C:\\ProgramData\\VMware\\Log Insight Agent\\liagent.ini"
```

loginsight_pkg.sls

```
loginsight_pkg:
  '4.6.1.8587550':
    full_name: 'VMware vRealize Log Insight Agent'
    installer: 'salt://win/repo-ng/binaries/loginsight/VMware-Log-Insight-Agent-4.6.1-8587550_10.151.50.125.msi'
    cache_dir: True
    install_flags: '/qn /norestart'
    msiexec: True
    uninstaller: 'salt://win/repo-ng/binaries/loginsight/VMware-Log-Insight-Agent-4.6.1-8587550_10.151.50.125.msi'
    uninstall_flags: '/uninstall'
    locale: en_US
    reboot: False
```

### Steps to Reproduce Issue

salt m-server* state.apply loginsight 

### Versions Report

```
Salt Version:
               Salt: 2018.3.4

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```
