### ISSUE TITLE
Salt-minion.service enters a loop with an empty master name in minion config file

### ISSUE THREAD

**Issue by tqre** [saltstack/salt#52626]
### Description of Issue/Question
With a minion config file /etc/salt/minion, empty master address causes 100% cpu consumption. Running Arch Linux, tested on 3 different platforms running Arch. Didn't find any similar references in this or development branch. 

### Setup
```
/etc/salt/minion
master:
id: test
```

### Steps to Reproduce Issue
The above minion config file present
```
# systemctl start salt-minion
huhti 19 11:37:37 tqrearch salt-minion[5450]: [CRITICAL] Unexpected error while connecting to None
huhti 19 11:37:37 tqrearch salt-minion[5450]: Traceback (most recent call last):
huhti 19 11:37:37 tqrearch salt-minion[5450]:   File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1018, in _connect_minion
huhti 19 11:37:37 tqrearch salt-minion[5450]:     yield minion.connect_master(failed=failed)
huhti 19 11:37:37 tqrearch salt-minion[5450]:   File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
huhti 19 11:37:37 tqrearch salt-minion[5450]:     value = future.result()
huhti 19 11:37:37 tqrearch salt-minion[5450]:   File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
huhti 19 11:37:37 tqrearch salt-minion[5450]:     raise_exc_info(self._exc_info)
huhti 19 11:37:37 tqrearch salt-minion[5450]:   File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
huhti 19 11:37:37 tqrearch salt-minion[5450]:     yielded = self.gen.throw(*exc_info)
huhti 19 11:37:37 tqrearch salt-minion[5450]:   File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1215, in connect_master
huhti 19 11:37:37 tqrearch salt-minion[5450]:     master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe, failed)
huhti 19 11:37:37 tqrearch salt-minion[5450]:   File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
huhti 19 11:37:37 tqrearch salt-minion[5450]:     value = future.result()
huhti 19 11:37:37 tqrearch salt-minion[5450]:   File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
huhti 19 11:37:37 tqrearch salt-minion[5450]:     raise_exc_info(self._exc_info)
huhti 19 11:37:37 tqrearch salt-minion[5450]:   File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 326, in wrapper
huhti 19 11:37:37 tqrearch salt-minion[5450]:     yielded = next(result)
huhti 19 11:37:37 tqrearch salt-minion[5450]:   File "/usr/lib/python2.7/site-packages/salt/minion.py", line 693, in eval_master
huhti 19 11:37:37 tqrearch salt-minion[5450]:     opts.update(prep_ip_port(opts))
huhti 19 11:37:37 tqrearch salt-minion[5450]:   File "/usr/lib/python2.7/site-packages/salt/minion.py", line 248, in prep_ip_port
huhti 19 11:37:37 tqrearch salt-minion[5450]:     ip_port = opts['master'].rsplit(':', 1)
huhti 19 11:37:37 tqrearch salt-minion[5450]: AttributeError: 'NoneType' object has no attribute 'rsplit'
```
This message is being generated constantly.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Mar 11 2019, 18:59:25)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 5.0.7-arch1-1-ARCH
         system: Linux
        version: Not Installed
```
Versions differ a bit on the platforms I tested, but the issue is reproducible nevertheless. This is my first issue ever I have opened...
