### ISSUE TITLE
acme.cert state always shows change with renew set (#50310 again)

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#52652]
### Description of Issue/Question
Exactly the same issue as described in #50310 but this was apparently fixed.
But it repeared for me in 2019.2.0

### Setup
The example snippet from #50310 works fine for reproducing it.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.28.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.1
   pycryptodome: 3.8.1
         pygit2: 0.28.0
         Python: 2.7.16 (default, Apr  6 2019, 22:25:52)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: 646
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```

@Ch3LL as mentioned on slack, looks like this bug is back.
