### ISSUE TITLE
show_highstate prints errors to stdout, not stderr

### ISSUE THREAD

**Issue by cboltz** [saltstack/salt#52653]
### Description of Issue/Question

We run CI tests on our salt states, one of them is 
`salt-call --local --retcode-passthrough state.show_highstate > /dev/null`

Today I noticed failures in this test, but without any visible output or error message.

Re-running the test without `> /dev/null` showed

```
local:
    - Detected conflicting IDs, SLS IDs need to be globally unique.
          The conflicting ID is '/etc/sysconfig/apache2' and is found in SLS 'base:profile.countdown.apache' and SLS 'base:profile.wiki.apache'
```

Obviously that highlights a bug in our salt states, but I'd expect that these errors get displayed on `stderr`, not `stdout`.

### Setup

untested ;-) simplified example:

```
/tmp/foo:
  file.managed
/tmp/foo:
  file.managed  
```

### Steps to Reproduce Issue
have conflicting IDs, and run show_highstate

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.12.14-lp150.12.45-default
         system: Linux
        version: Not Installed
```
