### ISSUE TITLE
Different environments using the same pillar and macros

### ISSUE THREAD

**Issue by AmiramMaimon** [saltstack/salt#52677]
Hey,
I have few environments running on my salt-master (master version: 2019.2.0).
Is it possible to unite some of the macros/sls files?

For example, I want to write macros that will ease some of the work and to create pillars that are relevant to all of the different environments.
If there a way to place those files at one place and be able to access them from the different envs?
Is so where (to place them) and How (how to access the macros/sls)?
If not, is there a way to pass that? like create a env that will hold all of the above files/sls and access/import from this env?

Amiram

**Comment by DmitryKuzmenko** [comment]
@AmiramMaimon Try this way:
```yaml
file_roots:
  dev:
    - /srv/salt/dev
    - /srv/salt/common
  qa:
    - /srv/salt/qa
    - /srv/salt/common
  prod:
    - /srv/salt/prod
    - /srv/salt/common
```
Fileserver will check directories in the order they specified in `file_roots`. So in this case first it will try to find file in an environment specific directory then will try the common directory.

Also want to let you know that the best and fastest way to get answers to user experience related questions is to ask them here  https://groups.google.com/forum/#!forum/salt-users
