### ISSUE TITLE
salt-ssh ssh_auth.present add an Unicode string u' <key>' in authorized_keys

### ISSUE THREAD

**Issue by nee2c** [saltstack/salt#52680]
When trying to add ssh key with salt-ssh (don't have issue when using salt) using state.ssh_auth.present the text in authorized_keys is
```
u' ssh-rsa <valiid key> user@pc2'
```

pillar/admins.sls
```
admins:
  user:
    passwd: <valid pw hash>
    ssh:
      - ssh-rsa <valid ssh pub key> user@pc2
```

states/admins.sls
```
install_sudo:
  pkg.installed:
    - name: sudo

install_ssh:
  pkg.installed:
    - name: openssh-server

running_ssh:
  service.running:
    - name: ssh
    - enable: True
    - watch:
      - file: /etc/ssh/sshd_config

{% for user, args in pillar.get('admins',{}).items() %}
add_{{user}}_admin:
  user.present:
    - name: {{user}}
    - groups:
      - {{user}}
      - sudo
    - password: {{args.get('passwd')}}

add_{{user}}_ssh_keys:
  ssh_auth.present:
    - names: {{args['ssh']}}
    - user: {{user}}
{% endfor %}

hardining_ssh:
  file.managed:
    - name: /etc/ssh/sshd_config
    - source:
      - salt://files/sshd_config
```

### Steps to Reproduce Issue
salt-ssh 'pc1' states.apply admins

### Versions Report
`salt --versions-report`
```
Salt Version:                                                                                                                                                                    [8/1854]
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: 3.2.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 25 2018, 20:42:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.11 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.11 
```

minion (but issue with salt-ssh)
Debian9
salt: 2016.11.2

**Comment by DmitryKuzmenko** [comment]
@nee2c could you please check will this change help you?
```
add_{{user}}_ssh_keys:
  ssh_auth.present:
    - names: {{args['ssh'] | tojson}}
    - user: {{user | tojson}}
```

You can find details in the release notes: https://docs.saltstack.com/en/develop/topics/releases/2019.2.0.html#non-backward-compatible-change-to-yaml-renderer
