### ISSUE TITLE
[salt.cloud] parameters to add domain after cloning (vmware)

### ISSUE THREAD

**Issue by diegolaz** [saltstack/salt#52701]
Hello, I'm testing with the following information to clone a windows VM.

I have two main problems. VMs have a registry key that sets a "notice" before login which prevents the initial autologon (I have to manually click ok) and I will probably need to remove the key before cloning if there is no option to force, and the second issue is I cant join the new vm to the domain automatically... I noticed that with the info I'm sending, its creating an answer file and running a sysprep... is there a way to send more info to that answer file (xml)  to add the domain join (and maybe even more customizations)?

Thanks!
```
*profile-clonWin10:
 provider: -PROVIDERNAME-
 clonefrom: 'SOURCEVM'
 memory: 16GB
 num_cpus: 2
 cluster: -SOMECLUSTER-
 datastore: -SOMEDATASTORE-
 datacenter: -SOMEDATACENTER-
 folder: Servers
 dns_servers:
  -DNSIP1
  -DNSIP2
 domain: --somedomain--
 power_on: True
 deploy: False
 win_username: localuser
 win_password: localpassword
 plain_text: True
 devices:
   disk:
     Hard disk 1:
       size: 150
       thin_provision: True
     Hard disk 2:
       size: 80
       thin_provision: True
   network:
     Network adapter 1:
       name: 'VLAN-NAME'
       switch_type: distributed
       ip: --SOME IP --
       subnet_mask: --SOME IP --
       gateway: [--SOME IP --]
       domain: some.domain**
*
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed

```
