### ISSUE TITLE
Unable to install pip packages on Windows due to pip.version not accepting cwd=

### ISSUE THREAD

**Issue by Sxderp** [saltstack/salt#52761]
### Description of Issue/Question
Windows cannot find the `pip` executable in order to determine the version of pip that is running. This is done in [pip.install](https://github.com/saltstack/salt/blob/1a23cb1256baf59f9bfcc5680961da1bcab4f1e5/salt/modules/pip.py#L664) and probably other places too. If I manually add `cwd='C:\\salt\\bin\\Scripts'` to the [cmd.run_all](https://github.com/saltstack/salt/blob/1a23cb1256baf59f9bfcc5680961da1bcab4f1e5/salt/modules/pip.py#L1248) then everything works fine.

### Setup
```
# install_schedule.sls
croniter-pip:
  pip.installed:
    - name: croniter
    - cwd: 'C:\salt\bin\Scripts'
    - bin_env: 'C:\salt\bin\Scripts\pip.exe'

windows-highstate:
  schedule.present:
    - function: state.highstate
    - job_kwargs:
        saltenv: math
        pillarenv: math
    - cron: '0 2 * * *'
    - splay: 10800
    - require:
      - croniter-pip
```

### Steps to Reproduce Issue
`salt-call state.highstate`
```
          ID: croniter-pip
    Function: pip.installed
        Name: croniter
      Result: None
     Comment: Error installing 'croniter': Could not find a `pip` binary
     Started: 08:39:24.842996
    Duration: 19.915 ms
     Changes:   
```
(Include debug logs if possible and relevant.)

### Versions Report
```Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.17763 SP0 Multiprocessor Free
```

**Comment by twangboy** [comment]
If you're working with salt's python installation, as it seems you are, you shouldn't need to specify `cwd` and `bin_env` anymore.

**Comment by Sxderp** [comment]
I was able to successfully install the python module with the following sls. As suggested by @twangboy I removed the `cwd` and `bin_env`.

```
# install_schedule.sls
croniter-pip:
  pip.installed:
    - name: croniter

...
```

While my particular use case has been resolved, I still think the original issue is valid and therefore I'm not going to close the report. However, a documentation update may be required since it [currently recommends including cwd and bin_env](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pip.html).
