### ISSUE TITLE
Feature request- multi-yaml documents as more complex sls structures

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#52776]
So this is not a fully fleshed out Idea I wanted to run it by the greater community before solidifying it. 

Currently, the state system does not work with multi-document yaml files. So while talking with a small group I had an idea. What if that was to change. If multi-documents not only could be used but could be used for the betterment of the structure of sls files. 

What I'm thinking is that in the current setup we would still allow single document files and would treat them as standard sls files, keeping backward compatibility. However, if the yaml parser finds a multi-document yaml file it treats the first document as a header. and then the second and supplemental documents as the sls portion. This could be taken further since rendering would still be run before this section. So the `header` section could change things like which document is considered the sls. allowing multi-document yaml files to be run differently on different operating systems cutting down on the jinja needed for systems that act vastly differently. 

Could also put things like sls version information into this header section. 

```
---
version: 0.0.1
sls_doc: 1
---
testing:
  test.nop:
    - name: This is a test
---
testing:
  test.nop:
    - name: This is also a test
```

So again this is just a random neuron firing so take the idea with a grain of salt.

**Comment by whytewolf** [comment]
I should note. This is not meant to expand the other data structures such as #!py render or json rendered data. Just give a more advanced option for the yaml data render.

**Comment by waynew** [comment]
This is an interesting idea. So in this example case, both of the other "documents" have `testing` state IDs. Would that be a conflict in this case or would it be somehow handled differently?

**Comment by whytewolf** [comment]
I should have explained the example case, I knew I forgot something. My fault. my brain cell decided to go on vacation mid-thought.
 
 in the example sls_doc would be pointing to the 1 document, which would be the first testing sls, the header document being sls_doc: 0. So doc 2 would not be seen by the state system unless you changed the sls_doc manually. or put jinja in to change it based on some other item.

Also Since this would be using yaml the jinja would still be seen before the yaml so the whole thing would still need to render for all of the jinja. which does make it a bit problematic. 

An idea to expand this would be to allow sls_doc to have a list so you could enumerate through the internal docs

**Comment by whytewolf** [comment]
Here is a better dummy example that I think might help. Yes, this is possible today using just jinja. However, the sls file would be a little more difficult to read. 

```
---
version: 0.0.1
{% if salt.grains.get['os'] == 'CentOS' %}
doc_sls: [1,2]
{% elseif salt.grains.get['os'] == 'Debian' %}
doc_sls: [3,1]
{% endif %}
---
install_mysql:
  pkg.install:
    - name: {{pkg_name}}

mysql_service:
  service.running:
    - name: {{servicename}}
    - require:
      - pkg: install_mysql
---
root_password:
  mysql_user:
    - name: root
    - password: {{ salt.pillar.get('mysql_root_password') }}
    - require:
      - service: mysql_service
---
root_password:
  debconf.set:
    - name: mysql-server
    - data:
        'mysql-server/root_password':  {'type': 'string', 'value': '{{ pillar["mysql_root_password"] }}'}
        'mysql-server/root_password_again': {'type': 'string', 'value': '{{ pillar["mysql_root_password"] }}'}
    - require_in:
      - pkg: install_mysql
```
