### ISSUE TITLE
YAML is not default renderer

### ISSUE THREAD

**Issue by BrianSidebotham** [saltstack/salt#52799]
### Description of Issue/Question

It appears as though yaml is no longer the default render. Take for example the following snippet from a simple package ( https://github.com/wanless-systems/salt-formula-tftpd-hpa )

```yaml
{%- from "tftpd_hpa/map.jinja" import server with context %}
{%- if server.enabled %}
tftpd_hpa_package:
  pkg.installed:
  - pkgs: {{ server.pkgs }}
```
where `server.pkgs` is set in the map:

```yaml
RedHat:
  pkgs:
  - tftp-server
  - syslinux
```

When this state is used, there's an error produced:

```
          ID: tftpd_hpa_package
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit run-28404.scope.
                    Loaded plugins: fastestmirror, versionlock
                    Loading mirror speeds from cached hostfile
                     * base: mirrors.clouvider.net
                     * epel: mirrors.coreix.net
                     * extras: mirrors.coreix.net
                     * updates: mirrors.clouvider.net
                    No package u'tftp-server' available.
                    No package u'syslinux' available.
                    Error: Nothing to do
     Started: 15:50:11.862856
```

That's because `u'tftp-server'` is not the package name, `tftp-server` is the package name.

If I change the state to explicitly use the yaml filter here everything works correctly again:

```yaml
{%- from "tftpd_hpa/map.jinja" import server with context %}
{%- if server.enabled %}
tftpd_hpa_package:
  pkg.installed:
  - pkgs: {{ server.pkgs|yaml }}
```

### Versions Report

Latest development branch commit - `ffa430507041e18a783444fc379d67b078b5692f`
