### ISSUE TITLE
pillarenv environments in masterless setup

### ISSUE THREAD

**Issue by DrPyser** [saltstack/salt#52832]
### Description of Issue/Question

I'm using a masterless setup to manage application configuration and deployment on a single machine.

My problem seems similar to #36153 and #30234 , with the difference of a masterless setup, and versions involved. 

I'm trying to use pillar environments to enable multiple deployments of an application with different sets of configurations.

So I have my `pillar_roots` configured like so:
```
pillar_roots:
  base:
    - /srv/pillar
  alpha:
    - /srv/pillar/alpha
  beta:
    - /srv/pillar/beta
```
and my `/srv/pillar/top.sls` looking like this:
```
base:                                                                                                                                                                                                                                                                                                                       
  "*":
    - otherstuff

alpha:
  "*":
    - myapp1
    - myapp2
    
beta:
  "*":
    - myapp1
    - myapp2
```
But testing with e.g. ` salt-call -l info --local pillar.items myapp1 pillarenv=alpha` fails to give the expected results, instead showing the content of `beta`. I understand it's merging the pillar files in the order they are processed(if I add a key in the alpha version, but not in the beta version, It will be present in the output).

I also tested with [`pillar_source_merge_strategy: none`](https://docs.saltstack.com/en/latest/ref/configuration/master.html#pillar-source-merging-strategy) in my masterless config, after finding out about this, to no effect.

### Setup
`/etc/salt/minion.d/masterless.conf`:
```
file_client: local

file_roots:
  base:
    - /srv/salt/
  alpha:
    - /srv/salt/alpha
  beta:
    - /srv/salt/beta
                                                                                                                                                                                                                                                                                  
pillar_roots:
  base:
    - /srv/pillar
  alpha:
    - /srv/pillar/alpha
  beta:
    - /srv/pillar/beta
```

### Steps to Reproduce Issue
`/srv/pillar/alpha/test.sls`:
```
test:                                                                                                                                                                                                                                                                                                                       
  a: 1
  b: 2
  c: 3
```

`/srv/pillar/beta/test.sls`:
```
test:                                                                                                                                                                                                                                                                                                                       
  a: 3
  b: 4
```

```
$ salt-call -l info --local pillar.items test pillarenv=alpha                                                                                                                                                                                                                                     
local:                                                                                                                                                                                                                                                                                                                      
    ----------
    test:
        ----------
        a:
            3
        b:
            4
        c:
            3           
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
# salt-call --version                                                                                                                                                                                                                                                                             
salt-call 2019.2.0 (Fluorine)   
```
```
# uname -a                                                                                                                                                                                                                                                                                        
Linux server-04 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
