### ISSUE TITLE
unable to use repo.saltstack.com

### ISSUE THREAD

**Issue by sceptiq** [saltstack/salt#52847]
### Description of Issue/Question

trying to install https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ on ubuntu 14.04 minion with salt-ssh 2019.2.0 (Fluorine)

### Setup

this:
```
salt-repo:
  pkgrepo.managed:
    - humanname: saltstack
    - name: deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main
    - key_url: https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub
    - file: /etc/apt/sources.list.d/saltstack.list
```

results in:
```
           ID: salt-repo                                                                                                                                                      [0/1885]
    Function: pkgrepo.managed
        Name: deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main
      Result: False
     Comment: Failed to configure repo 'deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main': [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER
_HELLO:sslv3 alert handshake failure
     Started: 19:30:04.245210
    Duration: 175.437 ms
     Changes:
```

a `openssl s_client -connect repo.saltstack.com:443` on the 14.04 minion results in:

```
CONNECTED(00000003)
140555418023584:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:770:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 295 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
``` 

### Versions Report
salt-ssh 2019.2.0 (Fluorine)
