### ISSUE TITLE
Master at 100% cpu and all worker thread with  authenticating 

### ISSUE THREAD

**Issue by ycc2004** [saltstack/salt#52841]
### Description of Issue/Question

When I don't use salt for more than 3 days, the salt-mater will run very slowly. For example, using salt xxx test.ping takes more than 10 minutes. At this time, the CPU usage at 100% ，and ram not used. 
```op - 22:40:57 up 222 days,  1:54, 20 users,  load average: 30.28, 30.31, 30.13
Tasks: 509 total,  31 running, 477 sleeping,   1 stopped,   0 zombie
Cpu(s): 99.8%us,  0.2%sy,  0.0%ni,  0.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  32880332k total, 10348448k used, 22531884k free,   629848k buffers
Swap:  6291440k total,        0k used,  6291440k free,  6184568k cached
```
I use the salt-master -L command find almost do “Authentication request from XXXX”

```
[INFO    ] Authentication request from b-app-ps-108-56
[INFO    ] Authentication accepted from b-app-ps-108-56
[DEBUG   ] Sending event: tag = salt/auth; data = {'id': 'b-app-ps-023-37', '_stamp': '2019-05-05T14:47:41.307114', 'result': True, 'pub': '-----BEGIN PUBLIC KEY-----
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
file_recv: True
default_include: /etc/salt/master.d/*.conf
worker_threads: 30
pidfile: /var/run/salt-master.pid
pki_dir: /etc/salt/pki/master
timeout: 60
auto_accept: True
file_roots:
  base:
    - /wls/saltroot/salt
pillar_roots:
  base:
    - /wls/saltroot/pillar
log_file: /wls/logs/salt/log/master
key_logfile: /wls/logs/salt/key
cachedir: /wls/logs/salt/cache/salt/master
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
```
salt-key -L | wc -l
6417
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
[/wls/programs/dns]:salt --versions-report
```
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.09
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.5 Santiago
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.5 Santiago


```
