### ISSUE TITLE
SaltClientError: Attempt to authenticate with the salt master failed with timeout error

### ISSUE THREAD

**Issue by davegiles** [saltstack/salt#52881]
I could use some help understanding the various reauth/wait minion preferences to find the right combination to reduce/eliminate occurrences of authentication errors when doing a state.apply
 
On our masters with the most minions (100-250), I see a handful of these errors with each job I run (either regularly or async).
 
I’ve tried setting the acceptance_wait preferences a couple different ways, but I’m still seeing authentication errors happening well before the defined time. I’ve also tried using –batch-size, but that appears to ping each minion before starting the batches to check which minions are reachable, which makes me wonder if the timeouts are still happening under the hood and I’m just not seeing them

For context:
  - One server with 8 cores and 64GB of ram, running Ubuntu 18.04
  - Running 65 instances of salt-master in docker containers
  - Approx. 4000 minions connecting to the masters.
    - There are a couple masters with 100-200 minions
    - The median minion count per master is 60 minions

salt-master:
```
salt@b9af34990d51(atos_rw):/$ salt --versions-report
Salt Version:
           Salt: 2018.3.3
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.0-1037-azure
         system: Linux
        version: Ubuntu 18.04 bionic
```
All minions are on Windows Server, most 2012 but some back to 2008 R2.  All run same minion version:
```
Salt Version:
               Salt: 2018.3.2
    
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
    
    System Versions:
               dist:  
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
