### ISSUE TITLE
Salttack return results when multiple minion executes state.sls

### ISSUE THREAD

**Issue by menglong81** [saltstack/salt#52940]
I have a problem, when I use the master api to perform state.sls operations on many minions, how does the returned json information determine whether the state of each minion is executed successfully? Whether to resolve all result fields to judge

`{
	u 'return': [{
		u 'hostA: {
			u 'cmd_|-q-nrpe-service_|-touch /tmp/test.test_|-run': {
				u 'comment': u 'Command "touch /tmp/test.test" run',
				u 'name': u 'touch /tmp/test.test',
				u 'start_time': u '20:07:07.584068',
				u 'result': True,
				u 'duration': 19.93,
				u '__run_num__': 0,
				u 'changes': {
					u 'pid': 22997,
					u 'retcode': 0,
					u 'stderr': u '',
					u 'stdout': u ''
				},
				u '__id__': u 'q-nrpe-service'
			}
		},
		u 'hostB': {
			u 'cmd_|-q-nrpe-service_|-touch /tmp/test.test_|-run': {
				u 'comment': u 'Command "touch /tmp/test.test" run',
				u 'name': u 'touch /tmp/test.test',
				u 'start_time': u '20:07:07.315680',
				u 'result': True,
				u 'duration': 7.973,
				u '__run_num__': 0,
				u 'changes': {
					u 'pid': 6620,
					u 'retcode': 0,
					u 'stderr': u '',
					u 'stdout': u ''
				},
				u '__id__': u 'q-nrpe-service'
			}
		}
	}]
}
`

**Comment by SuperPommeDeTerre** [comment]
Fir each state, you have an attribute indicating the result.
In your example, all state has returned successfully.
Extract (in yaml for better understanding) :
```yaml
return:
  - hostA:
    cmd_|-q-nrpe-service_|-touch /tmp/test.test_|-run:
      result: True
      ...
  - hostB:
    cmd_|-q-nrpe-service_|-touch /tmp/test.test_|-run:
      result: True
      ...
```

Your states executes successfully if all states have their `result` equals to `True`. In your example, only one state is executed.
