### ISSUE TITLE
How to  set roles in pillars and use them as target in orchestration state.

### ISSUE THREAD

**Issue by appi1411** [saltstack/salt#52954]
### Description of Issue/Question
How to  set roles in pillars and use them as target in orchestration state.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
My Orchestration state:

```
Salt_runner_1:
  salt.state:
    - tgt: role: webservers
    - sls:
      - store.echo
```

Note:  webservers will be the name of my list of minions
store.echo  is my state file:

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by appi1411** [comment]
I am trying to use customize list of minions as a target in order to deploy whatever i want using orchestration state.

**Comment by garethgreenaway** [comment]
@appi1411 Thanks for the report.  I believe this page is a good example of what you're trying to do:
https://docs.saltstack.com/en/latest/topics/orchestrate/orchestrate_runner.html

You could adapter your existing state to this:
```
{% set servers = salt['pillar.get']('servers', 'test') %}
Salt_runner_1:
  salt.state:
    - tgt: {{ servers }}
    - sls:
      - store.echo
```

Then at the command line when calling the orchestration runner pass in the servers that you want to deploy to:
```
salt-run state.orch orch.deploy pillar='{"servers": "server1", "server2", "server3"}'
```

You could take a look at the Salt mine, which would allow you to set the role on the minions as a grain then target those minions with that grain:
https://docs.saltstack.com/en/latest/topics/mine/index.html
