### ISSUE TITLE
"invalid arguments" error in boto_ec2 module after 2018.3 upgrade

### ISSUE THREAD

**Issue by cmclaughlin** [saltstack/salt#53096]
Started seeing this after upgrading to 2018.3:

```
# salt-call boto_ec2.get_id name=`hostname -f` region=us-east-1 keyid=XXX key=XXX

Passed invalid arguments: Item in ``from list'' not a string.

Usage:

    Given instance properties, return the instance id if it exists.

    CLI Example:

    .. code-block:: bash

        salt myminion boto_ec2.get_id myinstance
```

After copying `salt/modules/boto_ec2.py` from one of my other minions running Salt 2017.7.8 to my `_modules` directory the problem went away. Any ideas how to troubleshoot this... since there's no stacktrace?

**Comment by garethgreenaway** [comment]
@cmclaughlin So far I haven't been able to reproduce this, can you provide the output from `salt --versions-report` so we can see the versions of the various python libraries you have installed?  Particularly interested in the version of the boto libraries.  @saltstack/team-boto FYI.

**Comment by cmclaughlin** [comment]
yep...

minion:

```
# pip freeze | grep boto
boto==2.40.0
boto3==1.3.1
botocore==1.12.147
```

```
# salt-minion --versions-report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 3.7.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Aug 11 2015, 23:39:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.1.10-17.31.amzn1.x86_64
         system: Linux
        version: Not Installed
```

master:
```
# salt --versions-report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: 3.7.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jul 26 2018, 19:59:38)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 17.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.104-95.84.amzn2.x86_64
         system: Linux
        version: Not Installed
```
