### ISSUE TITLE
file.managed: "content" is allowed, but does nothing

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#53108]
### Setup

```
/etc/sudoers.d/{{ system.name }}:
  file.managed:
    - content: '{{ system.name }} ALL = NOPASSWD: /usr/bin/systemctl restart minio_storage-{{ system.name }}.service'
    - template: jinja
    - mode: 0440
```

### Steps to Reproduce Issue

execute above sls and the file will be empty.

The key needs to be named "contents" not "content".

It would be very nice, if this state would fail, instead of creating an empty file.

### Versions Report
```
salt:/srv # salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.22.0
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.22.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: SuSE 12.3 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.114-42.1-default
         system: Linux
        version: openSUSE  12.3 x86_64
```
