### ISSUE TITLE
Alpine doesn't have useradd utility

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#53121]
### Alpine doesn't come with useradd utility by default

May apply to other busybox based distros

### Setup
Install Alpine from iso image

### Steps to Reproduce Issue
`salt-call state.single user.present name=iggy uid=1000 gid=1000`

Error:
```
salt.exceptions.CommandExecutionError: Unable to run command '['useradd', '-u', 1000, '-g', 1000, '-m', 'test']' with the context '{'cwd': '/root', 'shell': False, 'env': {'MAIL': '/var/mail/root', 'USER': 'root', 'SHLVL': '1', 'HOME': '/root', 'SSH_TTY': '/dev/pts/0', 'PAGER': 'less', 'PS1': '\\h:\\w\\$ ', 'LOGNAME': 'root', 'TERM': 'xterm-256color', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'SHELL': '/bin/ash', 'PWD': '/root', 'CHARSET': 'UTF-8', 'LC_CTYPE': 'C', 'LC_NUMERIC': 'C', 'LC_TIME': 'C', 'LC_COLLATE': 'C', 'LC_MONETARY': 'C', 'LC_MESSAGES': 'C', 'LC_PAPER': 'C', 'LC_NAME': 'C', 'LC_ADDRESS': 'C', 'LC_TELEPHONE': 'C', 'LC_MEASUREMENT': 'C', 'LC_IDENTIFICATION': 'C', 'LANGUAGE': 'C'}, 'stdin': None, 'stdout': -1, 'stderr': -1, 'with_communicate': True, 'timeout': None, 'bg': False, 'close_fds': True}', reason: [Errno 2] No such file or directory: 'useradd': 'useradd': useradd
```
### Versions Report
```
# salt-call --versions-report
/usr/lib/python3.7/site-packages/salt/version.py:632: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  lin_ver = linux_distribution()
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.28.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.1
         Python: 3.7.3 (default, Apr 17 2019, 11:48:37)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.19.41-0-virt
         system: Linux
        version: Not Installed
```
