### ISSUE TITLE
KeyError: u'ssh.set_auth_key

### ISSUE THREAD

**Issue by DavideM78** [saltstack/salt#53124]
### Description of Issue/Question
State fails with this KeyError:
`KeyError: u'ssh.set_auth_key`. It seems as described [here](https://docs.saltstack.com/en/develop/topics/releases/2019.2.0.html) that Jinja will render the unicode string types with a "u" prefix.
Any idea how can I solve?
Thanks to everybody for the support 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

state.sls
```
username:
  group:
    - present
    - gid: 3000
  user:
    - present
    - name: username
    - fullname: A Full Name
    - uid: 3000
    - shell: /bin/bash
    - home: /home/user
    - password: '*'
    - groups:
      - user
      - sudo
    - require:
      - group: groupname
      {#- For the sudo group #}
      - sls: global.sudo
  ssh_auth:
    - present
    - user: username
    - source: salt://path/to/ssh-keys/user.pub
    - require:
       - user: username
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
``` 
# salt-call state.sls global.statename -l info

ID: username
    Function: ssh_auth.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/ssh_auth.py", line 333, in present
                  data = __salt__['ssh.set_auth_key'](
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1196, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 105, in __getitem__
                  return self._dict[key]
              KeyError: u'ssh.set_auth_key'
     Started: 09:07:02.777368
    Duration: 24.168 ms
     Changes:
Summary for local
-------------
Succeeded: 15
Failed:     5
-------------
Total states run:     20
Total run time:  744.002 ms
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb 20 2019, 09:59:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.10 Final
         locale: UTF-8
        machine: x86_64
        release: 4.9.125-linuxkit
         system: Linux
        version: CentOS 6.10 Final
```
