### ISSUE TITLE
salt user target

### ISSUE THREAD

**Issue by halfss** [saltstack/salt#5317]
if i have 4 minions:

```
  abc.test1.com
  abc.test1.com
  def.test2.com
  def.test2.com
```

and my external like this:

``` saltstack
  external_auth:
    pam:
      halfss:
        - '*':
      halfss1:
        - '*test1*':
      halfss2:
        - '*test2*':
```

and i think user target shoule like this:

``` yaml
salt  -a pam '*' test.ping
username: halfss
password: 
abc.test1.com:
    True
abc.test1.com:
    True
def.test2.com:
    True
def.test2.com:
    True
```

``` yaml
salt  -a pam '*' test.ping
username: halfss1
password: 
abc.test1.com:
    True
abc.test1.com:
    True
```

``` yaml
salt  -a pam '*' test.ping
username: halfss2
password: 
def.test2.com:
    True
def.test2.com:
    True
```

and not this:

``` yaml
salt  -a pam '*' test.ping
username: halfss
password: 
abc.test1.com:
    True
abc.test1.com:
    True
def.test2.com:
    True
def.test2.com:
    True
```

``` console
salt  -a pam '*' test.ping
username: halfss2
password: 
Failed to authenticate, is this user permitted to execute commands?
```

but my python is so bad,i do know how to add this feature，is there any one could help me?
