### ISSUE TITLE
mysql_grants failed database returned all privileges specifically instead of `ALL PRIVILEGES`

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#53199]
I am getting the following error when applying a mysql state
```
----------
          ID: mysql_database_test2
    Function: mysql_grants.present
      Result: False
     Comment: Failed to execute: "GRANT all privileges ON angel_test.* TO angel_test@10.29.67.141"
     Started: 14:09:26.951951
    Duration: 42.773 ms
     Changes:
```

When I run `salt-call` in debug mode, I can see why it was failing

```
14:09:26,991 [DEBUG   ] grants mismatch '{'user': 'angel_test', 'database': '`angel\\_test`.*', 'host': '10.29.67.141', 'grant': ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'CREATE', 'DROP', 'REFERENCES', 'INDEX', 'ALTER', 'CREATE TEMPORARY TABLES', 'LOCK TABLES', 'EXECUTE', 'CREATE VIEW', 'SHOW VIEW', 'CREATE ROUTINE', 'ALTER ROUTINE', 'EVENT', 'TRIGGER']}'<>'{'user': 'angel_test', 'host': '10.29.67.141', 'grant': ['ALL PRIVILEGES'], 'database': '`angel\\_test`.*'}'
```

The grants returned from the database was `['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'CREATE',.....]` while salt was expecting `[ALL PRIVILEGES]`, which caused a mismatch.

I believe this was cause by my recent database upgrade(Maridb 10.2.4 to Mariadb 10.3.15).
It seems in Mariadb 10.3, `show grants` query returns every single privilege instead of 'ALL PRIVILEGES'. But can we support this in salt mysql module?

**Comment by twangboy** [comment]
@garethgreenaway You were in here recently. What do you thing?

**Comment by garethgreenaway** [comment]
@angeloudy Can you provide the output from `salt --versions-report` so we know what version of Salt you're using?  This was fixed here, https://github.com/saltstack/salt/pull/51152, but may not be the version that you're using.

**Comment by angeloudy** [comment]
I was running 2018.3.3. But I patched `mysql.py` with the latest from `develop` branch.
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.4.2.post1
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, May 15 2019, 05:26:05)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE-p9
         system: FreeBSD
        version: Not Installed
```

**Comment by garethgreenaway** [comment]
@angeloudy Thanks for the information. Unfortunately, I haven't been able to reproduce this issue. Can you provide a copy of the state file that you're using?

**Comment by angeloudy** [comment]
Here's the state file I used.

```
mysql_database_{{ jailname }}:
  mysql_database.present:
    - name: {{ jail.db.db_name | default('app_' + jailname) }}
    - connection_host: {{ myapp_host.db.host }}
    - connection_user: {{ myapp_host.db.creator_user }}
    - connection_pass: {{ myapp_host.db.creator_pass }}
    - connection_charset: utf8

  mysql_user.present:
    - name: {{ jail.db.user | default('app_' + jailname) }}
    - connection_host: {{ myapp_host.db.host }}
    - connection_user: {{ myapp_host.db.creator_user }}
    - connection_pass: {{ myapp_host.db.creator_pass }}
    - host: {{ myapp_host.ip }}
    - password: {{ jail.db.pass }}
    - require:
      - mysql_database: {{ jail.db.db_name | default('app_' + jailname) }}

  mysql_grants.present:
    - grant: all privileges
    - connection_host: {{ myapp_host.db.host }}
    - connection_user: {{ myapp_host.db.creator_user }}
    - connection_pass: {{ myapp_host.db.creator_pass }}
    - database: {{ jail.db.db_name | default('app_' + jailname) }}.*
    - user: {{ jail.db.user | default('app_' + jailname) }}
    - host: {{ myapp_host.ip }}
    - require:
      - mysql_user: {{ jail.db.user | default('app_' + jailname) }}
```
