### ISSUE TITLE
win_iis.create_cert_binding says its adding a new value but failing/doesn't update

### ISSUE THREAD

**Issue by SteelCtyVitt** [saltstack/salt#53205]
### Description of Issue/Question
Whenever attempting to add a cert_binding via win_iis.create_cert_binding it says it updates the value (which it doesn't) and also fails at the same time).  

```
----------
          ID: VPSVendorApi-sslbinding
    Function: win_iis.create_cert_binding
        Name: xxxxx
      Result: False
     Comment: Created certificate binding: xxxxxx
     Started: 13:12:17.802000
    Duration: 3188.0 ms
     Changes:
              ----------
              new:
                  xxxxxx
              old:
                  None
```

### Setup
part of a larger Jinja template that cycles through sites to create but this is the relevant part
```
{{ site }}-sslbinding:
    win_iis.create_cert_binding:
      - require:
        - {{ site }}-deployed
  {% if 'thumbprint' in pillar ['iis']['sites'][site] %}
      - name: {{ pillar ['iis']['sites'][site]['thumbprint'] }}
      - site: {{ site }}
  {% endif %}
```
pulls pillar data from here
```
#!yaml|gpg
iis:
  sites:
    VPSVendorApi:
      fqdn: xxxx
      port: 443
      protocol: https
      user: |
        -----BEGIN PGP MESSAGE-----

        hQEMA5QuitjM6wSeAQf8DaIVIBACsU78No3dJFl/W87HkbViWj+fz3rh9mSZRrE9
        jHPI8e+j6WFDe+hWWfNujyBU47dLPP+d429n8DL6hb40FITTIPFYF+Tb5Ua/lJGw
        CJDsylIG9fF9Pimjc3n4glxYHtnsEN9hmw5eh3flKoYZhbuY4i20Kt7IhgTSYZHp
        wqPgrk+kGD04Bqjo+SP2UYlcw7ZSHvh5R1zcuHVA34ZUnTjzjg4GW8W55wX+XGZP
        w0ej4431xFQiE3AOYhPFABnY9cCE1OrzsS104WaBycAIsPeuk1EV44l5OwAnDJCz
        3Dmu/yT4V1B6jaDJguuRdqJHNzVqW9Lg8LEm+ZQ6G9JKAYyrOnJOz/bcjy/PkfRk
        7fujPJuL8hM0mLKyY2hQuLESQ7S4Knbmdwn34mhDYmI0G4cMS9xyl1tGmsDhZv6L
        BEewpxHf0lZkYZQ=
        =E97j
        -----END PGP MESSAGE-----

      password: |
        -----BEGIN PGP MESSAGE-----

        hQEMA5QuitjM6wSeAQf+KFH0sF4DU0EplhAfYLvTEdHwrkBVI07Mi1ltA+6E2qBQ
        x3mjJm/i6r1G3r+vM27fV6tzUf3VVlrxBVnln9usKvxtB3PNTiqO5ZWTyZDBQ1Lz
        iFgHdvI8YPxYFOL9VNQ/knq4tDHYijwv15E3NbL8F/NA5OzdcFM6q7UetPpyIFMJ
        lwXJYEWTmJTrDpjsuuZq3rtZll9PfedTxD/WBhsCIlDYEIPijujexasa1rJWJg9J
        0cNjmV8rjjTKCCx7YrKypw/J6rVssKpgm53EZlaumOFsWlshqtELVFlnlXHJcUES
        yPE0QuYCgjDEGjzKqigbONVXLKLamMqfPScx7W7nY9JLAUMvRymDqiK9mhxvj+Sl
        9g30+SNbQXA7i3T7ciOT37E2g9ipiRU8ggFvmfWNRF7Ykmi2BPWNpXXUawf+SFC3
        nh10MGUxPOivJBBP
        =MaIs
        -----END PGP MESSAGE-----

      thumbprint: xxxxx
```
### Steps to Reproduce Issue
Pillar data renders correctly and cycles through Jinja correctly but shows failed like above although showing new value.  IIS also does not update.

### Versions Report
```
root@PROD-MAN-01:~# salt 'PROD-WINAPI-01' test.versions
PROD-WINAPI-01:
    Salt Version:
               Salt: 2017.7.8

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393  Multiprocessor Free
```
