### ISSUE TITLE
Removal of pythonwin directory in Windows Minion package causes import failure for other modules that depend on win32ui

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#53219]
### Description of Issue/Question
pywinauto module depends on win32ui. After installing pywinauto module, any script that uses this module will fail to import win32ui.
### Setup
On Windows minion:
`salt minion pip.install pywinauto`

### Steps to Reproduce Issue
```python
#!env python
from pywinauto import Desktop

...
```

### Versions Report
```
  Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: 1.11.5
           cherrypy: 17.4.1
           dateutil: 2.7.5
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.10
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.3
             PyYAML: 3.13
              PyZMQ: 17.1.2
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.2.5
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.17763 SP0 Multiprocessor Free
```
