### ISSUE TITLE
ldap.managed broken on list entries (group members for example)

### ISSUE THREAD

**Issue by alcane** [saltstack/salt#53232]
### Description of Issue/Question

ldap.managed is returning an error when trying to replace an LDAP entry which contains a list of string.
For example, i'm managing group members as shown below, if a group has more than 1 entry, it always returns an error.
I have made a small change in a script to change the error to a "changes" list, but it does not solve the problem, it just shows a new one :)

### Steps to Reproduce Issue

Setup a state which manages `member` entry of a group:
```
ldap_user_group_{{ group.fqdn }}:
  ldap.managed:
    - connect_spec:
       url: {{ ldap_url }}
       bind:
         method: simple
         dn: {{ ldap_dn }}
         password: {{ ldap_password }}
    - entries:
      - '{{group.fqdn}}':
        - default:
            description: '{{group.name}}'
        - replace:
            member:
      {% for username, user in ldap.users|dictsort %}
              - 'CN={{ username }},{{ ldap_basedn }}'
      {% endfor %}
```

It returns the following error:
```
----------
          ID: ldap_user_group_CN=xxxxx,OU=xxxxx,OU=xxxxx,DC=xxxxx,DC=xxxxx
    Function: ldap.managed
      Result: False
     Comment: failed to modify entry CN=xxxxx,OU=xxxxx,OU=xxxxx,DC=xxxxx,DC=xxxxx(exception in ldap backend: UNWILLING_TO_PERFORM({'info': '00002035: objectclass: modify message must have elements/attributes!', 'desc': 'Server is unwilling to perform'},))
     Started: 09:46:33.377527
    Duration: 16.328 ms
     Changes:
```

I have made a change on my local salt files, to display a "change" instead of the error:
file: `/usr/lib/python2.7/site-packages/salt/modules/ldap3.py`
line: 581
```
    if 'unicodePwd' in after:
        after['unicodePwd'] = [_format_unicode_password(x) for x in after['unicodePwd']]

    modlist = ldap.modlist.modifyModlist(before, after)
+    if not len(modlist):
+        return True

    try:
        l.c.modify_s(dn, modlist)
    except ldap.LDAPError as e:
        _convert_exception(e)
    return True

```

After this change, it always returns a change even if the entry is well set.
It seems to come from the test between the `old` and `new` variables in the `managed` function of the `ldap.py` file.
I suspect the comparison does not compare sub OrderedSet correctly.
line: 298
```
        if old == new:
            ret['comment'] = 'LDAP entries already set'
            ret['result'] = True
            return ret
```

### Versions Report

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 1.10.6-a1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```
