### ISSUE TITLE
Windows pkg.list_pkgs and grain encoding issue

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#53340]
### `®` of death

Somewhere deep in Salt an output of `pkg.list_pkgs` is not decoded properly and passed as a binary string (not unicode)

This binary string gets stored in grain

When Salt tries to read the grain, it expects it to be stored as unicode, and fails miserably while trying to decode it, because the characters are from CP437

### Setup

1. Windows 10
2. Install the Intel driver (msi) https://downloadmirror.intel.com/28688/a08/WiFi_21.0.0_PROSet64.zip (link to the page: https://downloadcenter.intel.com/download/28688/Intel-PROSet-Wireless-Software-and-Drivers-for-IT-Admins)  This also happens with MS Office localization package names that contain diacritics, but this Intel driver is the simplest way to reproduce the problem.

### Steps to Reproduce Issue

1. Apply the following state:

```
{% set pkgs = salt['pkg.list_pkgs']() %}

windows_packages:
   grains.present:
     - value : {{ pkgs }}
     - force: True
```

The output should look like this

```
local:
----------
          ID: windows_packages
    Function: grains.present
...
Intel\xc2\xae PROSet/Wireless WiFi Software:
                      21.0.0.2990

...
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   8.316 ms
```

2. Apply the same state second time. It should fail like this:

```
[WARNING ] Bad syntax in grains file! Skipping.
[ERROR   ] Unable to read existing grains file: unacceptable character #x00ae: invalid start byte
  in "c:\salt\conf\grains", position 548
local:
----------
          ID: windows_packages
    Function: grains.present
      Result: False
     Comment: Unable to read existing grains file: unacceptable character #x00ae: invalid start byte
                in "c:\salt\conf\grains", position 548
     Started: 00:39:02.515980
    Duration: 7.801 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   7.801 ms
```

```
c:\salt>chcp
Active code page: 437
```

### Versions Report

<details><summary>c:\salt>salt-call --versions-report</summary>

```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free
```
</details>

**Comment by cmcmarrow** [comment]
last change: https://github.com/saltstack/salt/pull/50534

**Comment by cmcmarrow** [comment]
This test error might be related to this too. https://github.com/saltstack/salt/issues/53214

**Comment by damon-atkins** [comment]
Hi @max-arnold  why do you feel the need to have the list of packages as a grain, this is something you might do in other configuration management tools, not Salt. What are you trying to solve?

**Comment by damon-atkins** [comment]
You must use python 3 version of salt-minion to work with Unicode. Python 2 WIN API interface is too limiting.

**Comment by max-arnold** [comment]
@damon-atkins 

> You must use python 3.6 version of salt-minion

I used Python 3.5.3 (see the attached versions-report) that is shipped with Salt 2018.3.4. 

> why do you feel the need to have the list of packages as a grain, this is something you might do in other configuration management tools, not Salt. What are you trying to solve?

I need this for state tracking and reporting purposes. What is not shown in the example is a custom event I send when the grain changes (using the `onchanges` requisite). Without a grain the event would be sent each time the state is run.

**Comment by max-arnold** [comment]
My guess is that the grain is not a problem. The problem is that something in salt (`pkg.list_pkgs` maybe?) returns a CP437-encoded binary string and not an unicode one.

**Comment by damon-atkins** [comment]
There are lots of issues with python on windows and Unicode. Which were not fixed until python 3.6
For example a command can work from the salt master on linux and not work on the cmd.exe window.

The software should only change if you have set the version to latest,

The only thing I can think of, is if you wanted to track when someone by hand had changed the software.

**Comment by max-arnold** [comment]
> You must use python 3.6 version of salt-minion

Are there official Salt builds that ship with Python 3.6?  Below is the output of versions-report using the latest `2019.2.0` build:

```
c:\salt>salt-call --local --versions-report
Salt Version:
           Salt: 2019.2.0
...
Dependency Versions:
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
...
System Versions:
        machine: AMD64
        release: 10
         system: Windows
```

I also successfully reproduced the encoding problem with Salt 2019.2.0.

**Comment by max-arnold** [comment]
Upon closer examination, the encoding problem seems to be caused by grains.  See the following code: https://github.com/saltstack/salt/blob/develop/salt/modules/grains.py#L273-L290

Static grains (that are stored in C:\salt\conf\grains) are read first as binary file:

```
        with salt.utils.files.fopen(gfn, 'rb') as fp_:
```

and then saved a few lines later as text file:

```
        with salt.utils.files.fopen(gfn, 'w+') as fp_:
```

So far this is my understanding of what is happening here:

1. `pkg.list_pkgs` is fine and returns an unicode dictionary (both keys and values). I verified this in a debugger
2. When the dictionary gets stored in a grain, it is saved as text (`w+`), so Python uses system encoding (`cp1252` as reported by `salt --versions-report`)
3. When it later gets read, the file is treated as binary, and YAML loader fails to decode it in `grains = salt.utils.yaml.safe_load(fp_)`, producing the `Unable to read existing grains file` message

As far as I can see, it is always been this way:

https://github.com/saltstack/salt/commit/830324898a622c7648bc4c86fbfc6c9d4260586e
https://github.com/saltstack/salt/commit/36e39aead2b628a294fdb057d786ad350bb44d81

```
> print(sys.getdefaultencoding(), sys.getfilesystemencoding(), sys.stdout.encoding)
utf-8 mbcs cp437
```

**Comment by twangboy** [comment]
@saltstack/team-core  What do you think about making grains Unicode-safe?

**Comment by twangboy** [comment]
Could the fix be as simple as changing the `fopen` command on line 290 to `wb`?

https://github.com/saltstack/salt/blob/develop/salt/modules/grains.py#L290

**Comment by twangboy** [comment]
Actually, I applied the following state:
```
z_grain:
  grains.present:
    - value: some text
    - force: True

z_grain_unicode:
  grains.present:
    - value: trademark®
    - force: True
```
with the following result:
```
----------
          ID: z_grain
    Function: grains.present
      Result: True
     Comment: Set grain z_grain to some text
     Started: 16:45:10.097000
    Duration: 27.0 ms
     Changes:
              ----------
              z_grain:
                  some text
----------
          ID: z_grain_unicode
    Function: grains.present
      Result: True
     Comment: Set grain z_grain_unicode to trademark┬«
     Started: 16:45:10.124000
    Duration: 16.0 ms
     Changes:
              ----------
              z_grain_unicode:
                  trademark┬«
```
Looks weird, probably fixed in Python 3.6...

But the `grains` file was created properly, with the trademark symbol inside:
```
z_grain: some text
z_grain_unicode: trademark®
```
`grains.items` returned the following:
```
    z_grain:
        some text
    z_grain_unicode:
        trademark┬«
```
Applying the state a second time:
```
----------
          ID: z_grain
    Function: grains.present
      Result: True
     Comment: Grain is already set
     Started: 16:50:27.963000
    Duration: 16.0 ms
     Changes:
----------
          ID: z_grain_unicode
    Function: grains.present
      Result: True
     Comment: Grain is already set
     Started: 16:50:27.979000
    Duration: 0.0 ms
     Changes:
```
So, then I added a registry entry for software containing the `®` and verified that it showed up in `pkg.list_pkgs`:
```
    Salt┬« Unicode Test:
        2019.2.1
```
Then added your code to my custom grains state and get the following:
```
                  u'Salt\xae Unicode Test':
                      u'2019.2.1'
```
But, I'm noticing that my unicode character (`\xae`) is different from yours (`\xc2\xae`).
