### ISSUE TITLE
service.enabled does not create rc.d symlinks on Debian Stretch if init script has file extension

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt#53376]
### Description of Issue

I wanted to enable some third party (https://www.virtualbox.org/browser/vbox/trunk/src/VBox/Installer/linux/vboxautostart-service.sh?format=raw) init script, but it seems that `service.enabled`  fails to create appropriate symlinks, and service is not started after reboot. It works if I invoke `update-rc.d vboxautostart-service.sh defaults` manually though.

Otherwhise, there's no symlink:
```
ls -laR /etc/rc* | fgrep vbox

```

Meanwhile, `state.apply` reports success:
```
# salt minion state.apply packages.virtualbox.autostart
minion:
----------
          ID: virtualbox_autostart_service
    Function: file.managed
        Name: /etc/init.d/vboxautostart-service.sh
      Result: True
     Comment: File /etc/init.d/vboxautostart-service.sh is in the correct state
     Started: 09:57:51.403062
    Duration: 82.128 ms
     Changes:   
----------
          ID: systemd_reload
    Function: module.wait
      Result: True
     Comment: 
     Started: 09:57:51.485397
    Duration: 0.368 ms
     Changes:   
----------
          ID: virtualbox_autostart_service
    Function: service.enabled
        Name: vboxautostart-service
      Result: True
     Comment: Service vboxautostart-service is already enabled, and is in the desired state
     Started: 09:57:51.486780
    Duration: 49.319 ms
     Changes:   

Summary for minion
------------
Succeeded: 3
Failed:    0
------------
Total states run:     3
Total run time: 131.815 ms
```

Could this be reintroduction of #24012?

### Setup 
`packages.virtualbox.autostart`:
```

include:
    - packages.systemd

virtualbox_autostart_service:
    file.managed:
        - name: /etc/init.d/vboxautostart-service.sh
        - source: salt://{{ slspath }}/files/vboxautostart-service.sh
        - mode: 755
        - watch_in: 
            - module: systemd_reload
    service.enabled:
        - name: vboxautostart-service
        - require:
            - file: virtualbox_autostart_service
```
`packages.systemd`:
```
systemd_reload:
    module.wait:
        - cmd.run:
            - cmd: systemctl daemon-reload
```

### Steps to Reproduce Issue
Execute state provided with downloaded `vboxautostart-service.sh`.

### Versions Report
```
Salt Version:
           Salt: 2017.7.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9 
 ```
