### ISSUE TITLE
pillar.get returning None results in Error

### ISSUE THREAD

**Issue by darkn3rd** [saltstack/salt#53465]
### Description of Issue

Getting errors when pillar does not have dictionary/hash defined for the key.  This blows up:

```jinja
{% import_yaml 'docker/defaults.yaml' as defaults %}
{% set docker = salt['pillar.get'](
    'docker', 
    default=defaults.get('docker'), 
    merge=True) or defaults.get('docker') 
%}
```
 
When the pillar with just `docker:`, salt will error on this message as it gets a `NoneType` back from loading the YAML file.  I wish (whether this is a bug or enhancement request) it to default to `{}` instead of `None`, so that I can use my local defaults in the formula.

The workarounds are to have empty YAML file, use `docker: {}`, or have values.  The alternative to shield from this would be to add `or defaults.get('docker')`, so I would have something like this:

```jinja2
{% import_yaml 'docker/defaults.yaml' as defaults %}
{% set docker = salt['pillar.get'](
    'docker', 
    default=defaults.get('docker'), 
    merge=True) or defaults.get('docker') 
%}
```

This would increase usability especially for new users.

### Expected Results

If user defined the key without values in the YAML file, use an empty dict `{}` and not cause an error.

### Actual Results

```
[ERROR   ] pillar.get: Default ({u'repo': {u'url_base': u'https://download.docker.com/linux/ubuntu', u'key_url': u'https://download.docker.com/linux/ubuntu/gpg', u'name': u'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable', u'file': u'/etc/apt/sources.list.d/docker.list', u'humanname': u'Docker CE'}, u'prereqs': [u'apt-transport-https', u'ca-certificates', u'curl', u'software-properties-common'], u'package': u'docker-ce'}) is a dict, but the returned pillar value (None) is of type 'NoneType'. Merge will be skipped.
```

### Setup

Here's an example formula and pillar that produces the results.

```yaml
# pillar/top.sls
base:
  '*':
    - docker
```

```yaml
# pillar/docker.sls
docker: 
```

```yaml
# salt/top.sls
base:
  '*':
    - docker
```

```jinja2
<!-- salt/docker/map.jinja -->
{% import_yaml 'docker/defaults.yaml' as defaults %}
<!-- ERRORS on this below -->
{% set docker = salt['pillar.get'](
    'docker', 
    default=defaults.get('docker'), 
    merge=True)
%}
```

```yaml
# salt/docker/init.sls
{% from "docker/map.jinja" import docker with context %}

docker-pkg-dep:
  pkg.installed:
    - pkgs:
        {%- for pkgname in docker.prereqs %}
        - {{ pkgname }}
        {%- endfor %}

docker-pkg-repo:
  pkgrepo.managed:
    {% for key, value in docker.repo.items() %}
    - {{ key }}: {{ value }}
    {% endfor %}
    - refresh: True

docker-pkg:
  pkg.installed: 
   - name: {{ docker.package }}
   - require:
      - pkg: docker-pkg-dep

docker:
  group.present:
     - addusers: 
       - vagrant
```

```yaml
# salt/docker/defaults.yaml
docker:
  prereqs:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  package: docker-ce
  repo:
    humanname: Docker CE
    url_base: https://download.docker.com/linux/ubuntu
    key_url: https://download.docker.com/linux/ubuntu/gpg
    file: /etc/apt/sources.list.d/docker.list
    name: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ grains['oscodename'] |lower }} stable
```

### Steps to Reproduce Issue

Currently testing this locally with the above files under `./root/pillar` and `./root/salt` and this `Vagrantfile` below, and running `vagrant up`:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.synced_folder './roots/salt/', '/srv/salt'
  config.vm.synced_folder './roots/pillar', '/srv/pillar'

  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.run_highstate = true
    salt.verbose = true
  end
end
```

### Versions Report

```salt-minion 2019.2.0 (Fluorine)```
