### ISSUE TITLE
load_yaml unicode output not handled correctly with jinja template context

### ISSUE THREAD

**Issue by morgana2313** [saltstack/salt#53468]
### Description of Issue

load_yaml produces unicode which isn't handled properly if passed as a context to a jinja template in a state, causing a kind of double unicode:

```
context_yaml: {u'foo': u'bar'}
context_jinja: {u'foo': u'bar'}
context_load_yaml: {u"u'foo'": u"u'bar'"}      <==== double unicode here!
context_load_yaml_tojson: {u'foo': u'bar'}

context_yaml.foo: bar
context_jinja.foo: bar
context_load_yaml.foo: not defined
context_load_yaml_tojson.foo: bar
```

Work around: filter the jinja variable with tojson 

### Setup
foo.sls:

```
{% load_yaml as ly %}
  foo: bar
{% endload %}

write_file:
  file.managed:
    - name: /tmp/foo
    - source: salt://foo.txt
    - template: jinja
    - context:
        context_yaml:
          foo: bar
        context_load_yaml: {{ ly }}
        context_load_yaml_tojson: {{ ly | tojson}}
        context_jinja: {{ {'foo': 'bar'} }}
```

foo.txt:

```
context_yaml: {{ context_yaml }}
context_jinja: {{ context_jinja }}
context_load_yaml: {{ context_load_yaml }}     <==== double unicode here!
context_load_yaml_tojson: {{ context_load_yaml_tojson }}

context_yaml.foo: {{ context_yaml.foo if 'foo' in context_yaml else 'not defined' }}
context_jinja.foo: {{ context_jinja.foo if 'foo' in context_jinja else 'not defined' }}
context_load_yaml.foo: {{ context_load_yaml.foo if 'foo' in context_load_yaml else 'not defined' }}
context_load_yaml_tojson.foo: {{ context_load_yaml_tojson.foo if 'foo' in context_load_yaml_tojson else 'not defined' }}
```

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Nov 27 2018, 23:36:35)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-50-generic
         system: Linux
        version: Ubuntu 18.04 bionic
