### ISSUE TITLE
ssh_auth absolute instead of homedir

### ISSUE THREAD

**Issue by rgarrigue** [saltstack/salt#53478]
### Description of Issue

This is a feature request.

Currently, as stated in the doc, the ssh_auth state is relative to the user's home dir.

For security reason (read New Vector / Matric post-mortem after their 2019 security break for our inspiration) we are moving all authorized_keys in /etc/ssh/authorized_keys/%u. Hence we can't use this state anymore.

In my humble opinion, this state should allow one to specify an absolute path (and a user / group / mode).

**Comment by Ch3LL** [comment]
are you referring to the `config` option? I just tested setting `- config: '/etc/ssh/authorized_keys/%u'` and it added my pub key at that location. Here was my state:

```
test:                                                                                                                                                     
  ssh_auth.present:                                                                                                                                         
    - user: root                                                                                                                                            
    - source: salt://test.pub
    - config: '/etc/ssh/authorized_keys/%u'
```

And here is the file:

```
(salt-py2) ➜  salt git:(d0cad3e5a3) sudo file /etc/ssh/authorized_keys/root
/etc/ssh/authorized_keys/root: OpenSSH RSA public key
```
