### ISSUE TITLE
Exception running state.apply from scheduler (state.check_result)

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#53502]
### Description of Issue

Scheduled `state.apply` fails with `KeyError: 'state.check_result'`. Possibly related to #43931 or #49160.
 
```
[ERROR   ] Unhandled exception running state.apply
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 762, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 778, in apply_
    return sls(mods, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 1358, in sls
    _set_retcode(ret, high_)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 107, in _set_retcode
    if not __utils__['state.check_result'](ret, highstate=highstate):
KeyError: 'state.check_result'
```

### Steps to Reproduce Issue

1. salt-master 2019.2.0 Py3 on Ubuntu 18.04
2. salt-minion 2019.2.0 Py3 on Windows 10 (run as a foreground process via `salt-minion.bat`). The error is not reproducible if the minion runs on Ubuntu 18.04.
3. Example state:

```
# example_state.sls
always-changes-and-succeeds:
  test.succeed_with_changes:
    - name: example_state
```

4. Schedule
```
# schedule.sls
scheduled_state:
  schedule.present:
    - function: state.apply
    - seconds: 15
    - job_args:
      - example_state
```

5. Apply the schedule:

```
$ sudo salt windows state.apply schedule
windows:
----------
          ID: scheduled_state
    Function: schedule.present
      Result: True
     Comment: Adding new job scheduled_state to schedule
     Started: 02:59:04.416278
    Duration: 46.829 ms
     Changes:

Summary for windows
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  46.829 ms
```

Contents of `C:\salt\conf\minion.d\_schedule.conf`:

```
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, name: __mine_interval, return_job: false, run: true, run_on_start: true,
    splay: null}
  scheduled_state:
    args: [example_state]
    enabled: true
    function: state.apply
    jid_include: true
    maxrunning: 1
    name: scheduled_state
    seconds: 15
```

6. Wait until you see the following traceback in the minion log:

```
[ERROR   ] Unhandled exception running state.apply
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 762, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 778, in apply_
    return sls(mods, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 1358, in sls
    _set_retcode(ret, high_)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 107, in _set_retcode
    if not __utils__['state.check_result'](ret, highstate=highstate):
KeyError: 'state.check_result'
```

`__utils__` dictionary seems to be empty.

### Versions Report

<details>
<summary>master:~$ sudo salt --versions-report</summary>

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Jan 14 2019, 11:02:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-29-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

<details>
<summary>c:\salt>salt-call --versions-report</summary>

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free
```
</details>
