### ISSUE TITLE
Jinja rendering of state .sls fails if pillar data ends with `:`

### ISSUE THREAD

**Issue by r-pufky** [saltstack/salt#53501]
### Description of Issue
When rendering a files.replace, the following error occurs if a trailing : is used in the search pattern:

`Rendering SLS 'base:salt.master' failed: mapping values are not allowed`

### Setup
```
failing_search_replace:
        name: /my/file/with/colon/separated/user/pass
        pattern: 'mysearchpattern:'
        repl: |
          -----BEGIN PGP MESSAGE-----
          <GPG material removed>
          -----END PGP MESSAGE-----
        backup: False
        require:
          - failing_search_replace_file_template_creation
```

### Steps to Reproduce Issue
```
failing_search_replace:
        name: /my/file/with/colon/separated/user/pass
        pattern: 'mysearchpattern:'
        repl: |
          -----BEGIN PGP MESSAGE-----
          <GPG material removed>
          -----END PGP MESSAGE-----
        backup: False
        require:
          - failing_search_replace_file_template_creation
```
During runtime this will fail with the above mentioned error.

Looking into the failure message (essentially reading it as salt is trying to interpret values in search pattern in the wrong context), removing the trailing : fixes the issue.
```
failing_search_replace:
        name: /my/file/with/colon/separated/user/pass
        pattern: 'mysearchpattern'
        repl: |
          -----BEGIN PGP MESSAGE-----
          <GPG material removed>
          -----END PGP MESSAGE-----
        backup: False
        require:
          - failing_search_replace_file_template_creation
```
Works fine.

### Versions Report
```
salt-minion --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.9
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9
```

```
salt-master --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.9
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9
```
