### ISSUE TITLE
Absent documentation for docker healthcheck

### ISSUE THREAD

**Issue by gecube** [saltstack/salt#53511]
Hello!

I begin to adopt docker_container state in my infra. So I was digging through https://docs.saltstack.com/en/latest/ref/states/all/salt.states.docker_container.html and I found that healtcheck keyword is totally omitted. It is very hard to guess how it must look like to work. So I made the set of experiments.

For example, the run of postgres in docker may looks like:
```
postgres:
  docker_container.running:
    - image: postgres:latest
    - restart_policy: unless-stopped
    - environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    - port_bindings:
      - 127.0.0.1:5432:5432
    - binds:
      - postgres_data:/var/lib/postgresql/data
    - healthcheck:
      - test: ["CMD-SHELL", "pg_isready -U postgres"]
      - interval: 10000000000
      - timeout: 5000000000
      - retries: 5
```

the interval and timeout are by default in **ns** (as stated in docker golang library: https://github.com/docker/go-docker/blob/master/api/types/container/config.go ). Unfortunately, I was not able to use more convenient record for interval settings like '5s' and I am not sure where is the problem. So to conclude.

1. There is no reliable Salt documentation how to use docker healtchecks with docker_container state
and
2. There is no understanding how to set the interval in convenient units (like seconds)

**Comment by xeacott** [comment]
Looked into this briefly, looks like we just need to give some information in the docs about this. And as for a setting for a time, milliseconds may be a solution.

**Comment by darkn3rd** [comment]
Verified this is not in the documentation.  I assumed that it was a feature that is not supported.

**Comment by darkn3rd** [comment]
Wondering if this will be fixed in the documentation?

**Comment by akrus** [comment]
Still not fixed.

**Comment by satwell** [comment]
Agree that docs are still missing.  Looks like salt just passes the healthcheck config through to the low-level Docker API, which documents them here:  https://docker-py.readthedocs.io/en/stable/api.html#docker.types.Healthcheck

I've personally found that it's cleanest to specify the times with exponential notation; each second is 1e9 ns.  But the docker API wants ints, and YAML only seems to give you floats with exponential notation, so you can convert it with jinja.  Here's what my healthcheck config looks like:

```
    - healthcheck:
      - test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      - interval: {{ 5e9 | int }}  # 5s
      - timeout: {{ 5e9 | int }}  # 5s
      - retries: 5
```
