### ISSUE TITLE
mkpart and mkpartfs are the same

### ISSUE THREAD

**Issue by arnoldyahad** [saltstack/salt#53569]
### Description of Issue

want to paritition a disk without formatting the partitions ( without choosing fs_type)

### Setup
any salt version it doesnt matter:

```
partition_without_formatting:
  module.run:
    - name: partition.mkpart
    - device: /dev/nvme0n1
    - start: 0%
    - end: 100%
    - part_type: primary
```

asks for fs_type even though there is a module for fs_type called mkpartfs

https://github.com/saltstack/salt/blame/394c4546451851e0fd9a52bdeaa5a2c088136248/salt/modules/parted_partition.py#L472

here is the code for the modules making them both the same.

 
### Versions Report
use any version this hasnt changed in the last 3 years 

please help me to partition a disk without formatting the partitions,
thanks a lot
