### ISSUE TITLE
"Forced unmount because devices don't match" every run for curlftpfs

### ISSUE THREAD

**Issue by uhriap** [saltstack/salt#53561]
### Description of Issue
mount.mounted state always force remount for curlftpfs mount with `Forced unmount because devices don't match.`
I believe this https://github.com/saltstack/salt/blob/8973ed2fd755d6579db6eee04a163c7db5735f36/salt/states/mount.py#L309 assumptions is false and `mount.active` actually returns string with curlftpfs#

Workaround `device_name_regex: ftp://xxx:xxx@example.com/` helps
```
[INFO    ] {u'mount': True, u'umount': u"Forced unmount because devices don't match. Wanted: curlftpfs#ftp://xxx:xxx@example.com/ (ftp://xxx:xxx@example.com/), current: curlftpfs#ftp://xxx:xxx@example.com/, /root/curlftpfs#ftp:/xxx:xxx@example.com"}
```
### Setup
```
# cat test.sls
curlftpfs:
  pkg:
    - installed

curlftpfs mount xxx:
  mount.mounted:
    - name: /opt/xxx
    - device: curlftpfs#ftp://xxx:xxx@example.com/
    - fstype: fuse
    - mount: True
    - mkmnt: True
    - persist: False
    - require:
      - pkg: curlftpfs
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
# salt-call --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.88-42
         system: Linux
        version: Ubuntu 16.04 xenial
```
