### ISSUE TITLE
Winlogbeat fails to Start when deployed using Salt

### ISSUE THREAD

**Issue by dfoley84** [saltstack/salt#53613]
While deployment of Winlogbeat seems fine within Salt, and installed the module within the Windows Servers  it fails to start the service

### Setup
```
copy_files:
  file.recurse:
    - source: salt://sent/winlog/
    - name: C:\Program Files\Winlogbeat\
    - makedirs: true

run_install:
  cmd.run:
    - name: '.\install-service-winlogbeat.ps1'
    - shell: powershell
    - cwd:  C:\Program Files\Winlogbeat

run_install1:
  cmd.run:
    - name: '.\winlogbeat.exe setup'
    - cwd: C:\Program Files\Winlogbeat

Start:
  cmd.run:
    - name: 'Start-Service winlogbeat'
    - shell: powershell
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
root@salt:/srv/salt# salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: 3.7.0
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Nov 27 2018, 23:36:35)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1032-aws
         system: Linux
        version: Ubuntu 18.04 bionic
```
