### ISSUE TITLE
cp.push not working

### ISSUE THREAD

**Issue by shortstack** [saltstack/salt#53630]
### Description of Issue
Trying to get file from minion to master, and nothing gets copied. cp.push or push_dir, same error messages every time.

### Setup
`/etc/salt/master`:
```
file_recv: True
file_recv_max_size: 50000 
```

Master has been restarted several times 

### Steps to Reproduce Issue

On minions, a file resides at `C:\Users\Administrator\Downloads\test.ps1`.

Running these on the master:
```
salt "minion" cp.push "C:\Users\Administrator\Downloads\test.ps1"
```

```
salt "minion" cp.push "C:\Users\Administrator\Downloads\test.ps1" upload_path="files"
```

Both commands return false, every time I run cp.push, any system I try it on (same versions/setup)

Nothing transfers, nothing shows up at `/var/cache/salt/master/minions/{minion-name}`

In minion logs:
```
[ERROR   ][5432] cp.push Failed transfer failed. Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the master.
2019-06-27 15:01:12,963 [salt.loaded.int.module.cp:850 ][ERROR   ][1328] cp.push Failed transfer failed. Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the master.
2019-06-27 15:02:03,273 [salt.loaded.int.module.cp:850 ][ERROR   ][3540] cp.push Failed transfer failed. Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the master.
2019-06-27 15:02:54,265 [salt.loaded.int.module.cp:850 ][ERROR   ][5064] cp.push Failed transfer failed. Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the master.
```

### Versions Report

master:
```
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.10
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.13
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.10
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.13
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: 2.8.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-142-generic
         system: Ubuntu 16.04 xenial
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: 2.8.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-142-generic
         system: Ubuntu 16.04 xenial
```

minions:
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
```
