### ISSUE TITLE
docker_container does not support ipv6 port bindings

### ISSUE THREAD

**Issue by prometheanfire** [saltstack/salt#53709]
Here's the example to reproduce

```yaml
include:
  - sys.docker  # installs and configures docker (enables v6 support)

duo-access-gateway_volume:
  docker_volume.present:
    - name: duo-access-gateway
    - driver: local

duo-container:
  docker_container.running:
    - name: duo-access-gateway
    - image: duosecurity/access-gateway@sha256:ba065e9a04478fc17fd5b61b8c558616b7e9acba105668ef786f084545c32778
    - labels:
      - 'com.duo.access-gateway.builder.version': '62dc4eaf'
      - 'com.duo.access-gateway.code.version': 'v1.5.6'
      - 'com.duo.access-gateway.built': 'Fri, 14 Dec 2018 20:50:35 -0000'
    - restart_policy: always
    - log_driver: json-file
    - log_opt:
      - max-size: '50m'
      - max-file: '20'
    - port_bindings:
      - 'foo:bar:baz::foobar:80:8000'
      - '443:4443'
      - '8443:8443'
    - binds:
      - duo-access-gateway:/data
    - require:
      - docker_volume: duo-access-gateway_volume
```

You'll get an error like

```
local:
----------
          ID: duo-container
    Function: docker_container.running
        Name: duo-access-gateway
      Result: False
     Comment: Failed to translate input. Additional info follows:
              
              invalid:
                  ----------
                  port_bindings:
                      'foo:bar:baz::foobar:80:8000' is an invalid port binding definition (at most 3 components are allowed, found 7)
              
              If you feel this information is incorrect, the skip_translate argument can be used to skip input translation for the argument(s) identified as invalid. See the documentation for details.
```

I've tried the skip_translate option but it didn't help.

https://github.com/docker/docker-py/blob/master/docker/utils/ports.py#L3 is how upstream suports it (crazy regex).

https://github.com/saltstack/salt/blob/develop/salt/utils/docker/translate/container.py#L388 is why it's broken (it does a basic split on ':', which does not work for ipv6...)

**Comment by lenfree** [comment]
Hi @Akm0d, any update on this?

**Comment by HenriWahl** [comment]
Same tragedy here.

**Comment by HenriWahl** [comment]
The problem is apparently not solved yet.

**Comment by venomone** [comment]
Any update here?

**Comment by mitar** [comment]
I can confirm that IPv6 address does still not work with salt 3007.0. :-(

**Comment by mitar** [comment]
It seems the following workaround works:

```yaml
    - skip_translate: port_bindings
    - port_bindings:
        8080/tcp:
        - HostIp: "10.0.0.1"
          HostPort: 443
        - HostIp: "2001:db8::1"
          HostPort: 443
```
