### ISSUE TITLE
Install both 32 and 64 bit of a win_pkg having the same full_name

### ISSUE THREAD

**Issue by boussaffawalid** [saltstack/salt#53741]
### Description of Issue
I'm trying to install two versions of the same software (32 and 64 bit). However this two sofaware have the same **full_name**
So, always one version succeed and the other fails.

Is there any solution for this? 

### Setup
```
squish_x32:
  '6.4.3':
    full_name: 'Squish for Qt'
    installer: https://me.com/squish-6.4.3-qt59x-win32-msvc14.exe
    install_flags: 'unattended=1'
    msiexec: False
    uninstaller: 'C:\Squish\squish-6.4.3-qt59x-win32-msvc14\Uninstall.exe'
    uninstall_flags: 'unattended=1'
    reboot: False

squish_x64:
  '6.4.3':
    full_name: 'Squish for Qt'
    installer: https://me.com/squish-6.4.3-qt59x-win64-msvc14.exe
    install_flags: 'unattended=1'
    msiexec: False
    uninstaller: 'C:\Squish\squish-6.4.3-qt59x-win64-msvc14\Uninstall.exe'
    uninstall_flags: 'unattended=1'
    reboot: False
```

### Steps to Reproduce Issue

I'm trying to use the packages this way

```
squish_x32:
  pkg.installed:
    - pkgs:
      - squish_x32: 6.4.3

squish_x64:
  pkg.installed:
    - pkgs:
      - squish_x64: 6.4.3
```

Here is a sample output:

```
----------
          ID: squish_x32
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: squish_x32=6.4.3
     Started: 11:39:30.937000
    Duration: 94245.0 ms
     Changes:
              ----------
              squish_x32:
                  ----------
                  install status:
                      success
----------
          ID: squish_x64
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed and are at the desired version
     Started: 11:41:05.276000
    Duration: 8811.0 ms
     Changes:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
``` 

### Versions Report
I am using salt local on windows

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```
