### ISSUE TITLE
ssh_auth missing on Windows

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt#53753]
### Description of Issue
While trying to manage SSH authorized_keys on Windows, I found out the hard way that `ssh_auth` isn't available on Windows, because the documentation doesn't mention this little detail.

### Setup
Windows minion running 2018.3.4 (Py3).

### Steps to Reproduce Issue
Run an SLS containing ssh_auth.present on Windows.

### Versions Report
```
salt-call --versions-report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```
There exist multiple choices for installing SSH servers on Windows (incl. Microsoft's own port of OpenSSH), so people need to manage SSH related files there, too. Please make ssh_auth available on Windows, preferably also in a new 2018.3.x release.
