### ISSUE TITLE
Orchestrate pillar injection changes the data type of the dict keys

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#53805]
### Description of Issue
So I have kinda complex scheme where I, sometimes need to inject pillar data into the orchestration. To do so i do a:
1) salt orchestration started with  `pillar="$(cat /tmp/pillars.json)"` which includes some overrides for the pillar.
2) In orchestrate sls I do something like this to pass this override:

```
{% set elasticsearch = pillar.get('elasticsearch', {}) %}

install.elasticsearch:
  salt.state:
    - tgt: 'roles:elasticsearch'
    - tgt_type: 'grain'
    - sls:
      - formula.elasticsearch
    - pillar:
        elasticsearch: {{ elasticsearch }}
```

And I just noticed that this approach changes some data types.

### Steps to Reproduce Issue
Create a dummy orchestrate:
```
$ cat  bug.sls
---
{% set dummy = pillar.get('dummy', {}) %}

dummy.state:
  salt.state:
    - tgt: 'minion'
    - sls:
      - dummy
    - pillar:
        dummy: {{ dummy }}
```

Populate a dummy pillar:
```
$ cat  dummy.yaml
dummy:
  none_var: Null
```

Create a dummy state:
```
$ cat states/dummy.sls
always-passes:
  test.succeed_without_changes:
    - name: foo
```

Now run orchestration with debug:
`salt-run state.orchestrate bug -l debug`

My full log: https://gist.github.com/Oloremo/ca9d2ba7f4bf9c6b8f9b5cc8d49244e6

Main points:
1) Pillar data looks fine in sls:

```
dummy.state:
  salt.state:
    - tgt: 'minion'
    - sls:
      - dummy
    - pillar:
        dummy: {'none_var': None}
```
Yet when it was trasformed to OrderedDict it changes:
```
[DEBUG   ] Results of YAML rendering:
OrderedDict([('dummy.state', OrderedDict([('salt.state', [OrderedDict([('tgt', 'molecule-salt-withmaster-elasticsearch-01')]), OrderedDict([('sls', ['dummy'])]), OrderedDict([('pillar', OrderedDict([('dummy', OrderedDict([('none_var', 'None')]))]))])])]))])
```

Note that `none_var` was `None` object initially and in OrderedDict it's a `string`!

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 13 2018, 18:24:23)
   python-gnupg: 0.4.4
         PyYAML: 5.1.1
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by Oloremo** [comment]
```
dummy.state:
  salt.state:
    - tgt: 'minion'
    - sls:
      - dummy
    - pillar:
        dummy: {{ dummy | tojson }}
```

Fixes the issue. Sorry for the noise.
