### ISSUE TITLE
Unable to rotate the log file "c:\salt\var\log\salt\minion" because it is in use

### ISSUE THREAD

**Issue by marbx** [saltstack/salt#53809]
### Description of Issue
When the salt-minion contains 
 ```
log_level_logfile: debug
log_rotate_max_bytes: 4200
log_rotate_backup_count: 4
```

salt-call cannot write to the log files.

### Setup
Installed `Salt-Minion-2018.3.4-Py3-AMD64-Setup.exe`

### Steps to Reproduce Issue
`net start salt-minion` and  ` \salt\salt-call.bat -l debug test.version`   result in

    [WARNING ] Unable to rotate the log file "c:\salt\var\log\salt\minion" because it is in use

This only happens if the salt-minion service runs (with log rotation).

### Versions Report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

**Comment by cmcmarrow** [comment]
Is "c:\salt\var\log\salt\minion" not being used? Are you saying the warring is not true?

**Comment by markuskramerIgitt** [comment]
I think this warning is distracting.
Could you please set priority to 4?

**Comment by markuskramerIgitt** [comment]
@cmcmarrow, could you please lower the priority?
I see no need for action here.

**Comment by markuskramerIgitt** [comment]
Many of thes warning appears in version 3000

```
C:\>dir c:\salt\var\log\salt\minion*
24.03.2020  21:51             2.553 minion
24.03.2020  21:51            24.942 minion.1
24.03.2020  21:16            24.981 minion.4

 ```
The Minion should be able to rotate its log.

```
C:\>\salt\salt-call --local -V
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.15
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 3.0.1
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.17763 SP0 Multiprocessor Free

```
