### ISSUE TITLE
Ambiguos error message when python-docker is not installed

### ISSUE THREAD

**Issue by gecube** [saltstack/salt#53836]
I've got every time the error message stating:

```Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.```

In fact, the `python-docker` package is not installed. I make `apt install python-docker` (or another option is to install the module via pip manager) and the salt begins to work. It will be nice if the error message will show the root cause of issue, i.e. that the dependency is not installed. It has the value that it lowers the barrier of entering into the salt world for beginners and simplify the debugging.

**Comment by cmcmarrow** [comment]
A PR in the __virtual__ function of docker will add the info you want.

**Comment by gecube** [comment]
Please reopen the ticket, because the issue still exists in 3000.3

```
----------
          ID: cv
    Function: docker_network.present
      Result: False
     Comment: State 'docker_network.present' was not found in SLS 'docker_services_74'
              Reason: 'docker_network' __virtual__ returned False: 'docker.version' is not available.
     Changes:   
----------
```

```
Salt Version:
           Salt: 3000.3
```
