### ISSUE TITLE
zabbix_host module does not process additional host properties

### ISSUE THREAD

**Issue by slivik** [saltstack/salt#53838]
### Description of Issue
I try to create a new Zabbix host with saltstack.
The description of Zabbix_host.present stated this:
`This function accepts all standard host properties: keyword argument names differ depending on your zabbix version, see:https://www.zabbix.com/documentation/2.4/manual/api/reference/host/object#host`
I have added for example  tls keywords to the  Zabbix_host.present  command in the sls file:

### Setup
```
zabbix_create_host:
  zabbix_host.present:
    - host: {{ salt['grains.get']('nodename') }}
    - groups:
      - 20
    - interfaces:
        - default:
            - ip: '0.0.0.0'
            - dns: ''
            - type: 'agent'
            - port: '10050'
    - inventory_mode: 1
    - tls_connect: 2
    - tls_accept: 2
    - tls_psk_identity: PSK_{{ salt['grains.get']('nodename') }}
    - tls_psk: {{ salt['pillar.get']('zabbix:psk') }}
```
### Steps to Reproduce Issue
minion log file:
```
data: {"jsonrpc": "2.0", "params": {"interfaces": [{"ip": "0.0.0.0", "useip": "1", "dns": "", "main": "1", "type": "1", "port": "10050"}], "proxy_hostid": "0", "host": "<hostname>", "groups": [{"groupid": 20}], "inventory": {}}, "id": 0, "auth": "<auth_token>", "method": "host.create"}
```

### Versions Report
All versions affected

**Comment by cmcmarrow** [comment]
Thank for letting us know

**Comment by OrangeDog** [comment]
I've looked at the code and it ignores all properties other than `host`, `groups`, `interfaces`, `inventory`, and `proxy_host`. Even the documented `visible_name` is ignored.

As well as encryption settings, this also locks out `inventory_mode` and `description`.

Also missing, not directly related to this API but logically part of a host, is the ability to configure [host macros](https://www.zabbix.com/documentation/2.4/manual/api/reference/usermacro/object#host_macro).

**Comment by slivik** [comment]
It ignores nothing. It is only preprocessing of all parameters to form them properly (pop them out of the dictionary) for next run of the state module and for passing them properly to zabbix execution module. If this is an issue could you, please, send some output?

**Comment by OrangeDog** [comment]
@slivik it's trivial to demonstrate that they're ignored. Here's one example:
If the host doesn't exist it will be created, but the name not set. If it already exists, then the name will not be changed,

```yaml
test zabbix_host:
  zabbix_host.present:
    - host: {{ grains['id'] }}
    - visible_name: 'test'
```

Show me in [the code](https://github.com/saltstack/salt/blob/v2019.2.2/salt/states/zabbix_host.py#L22) where `kwargs` is passed to the execution module.
