### ISSUE TITLE
ini.options_absent raises AttributeError when more than one key is removed

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#53874]
### Description of Issue
Using the following state and INI file on either Windows or Linux will raise the following exception:

```
          ID: remove_options
    Function: ini.options_absent
        Name: C:/Temp/test.ini
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1919, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1918, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\ini_manage.py", line 215, in options_absent
                  ret['changes'][section].update({key: current_value})
              AttributeError: 'str' object has no attribute 'update'
     Started: 22:37:16.638238
    Duration: 31.708 ms
     Changes:   

Summary for win2019-3
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
Total run time: 249.669 ms
ERROR: Minions returned with non-zero exit code
```

### Setup
A single linux master with a minion and an additional Windows 2019 server minion connected.

### Steps to Reproduce Issue
```
# State file
{% if grains['kernel'] == 'Windows' %}
{% set dest_path = 'C:/Temp/test.ini' %}
{% else %}
{% set dest_path = '/root/test.ini' %}
{% endif %}

copy_ini:
  file.managed:
    - source: salt://{{ slspath }}/test.ini 
    - name: {{ dest_path }}
    - makedirs: True

remove_options:
  ini.options_absent:
    - name: {{ dest_path }}
    - sections:
        Tables:
          - key2
          - key3
    - require:
      - file: copy_ini
```

```
# Test.ini Contents
[Tables]
key1 = 1
key2 = 2
key3 = 3
key4 = 4
```

### Versions Report

```
win2019-3:
    Salt Version:
               Salt: 2018.3.4
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2019Server
             system: Windows
            version: 2019Server 10.0.17763 SP0 Multiprocessor Free

```
