### ISSUE TITLE
Returned to elasticsearch data of state.sls is unreadable in Kibana

### ISSUE THREAD

**Issue by sotona-** [saltstack/salt#53915]
### Description of Issue
I tried to return reports of sheduled on minion 'state.sls' function. But it's almost unreadable in Kibana, if functions has a long names. For example: cmd.run with long command.  It makes keys in ES document very long and Kibana cant display it normally.
![image](https://user-images.githubusercontent.com/9786098/61523672-670fcf00-aa47-11e9-95e4-329773fe5b28.png). 
M.b. it will be better to store function name like a value of different key?

### Steps to Reproduce Issue
Shedule a state.sls with long functions name and return to ES. Find returned documents in Kibana.

### Versions Report
Salt master: 2018.3.4 py3 on Ubuntu 18.04
Salt minion: 2018.3.4 py3 on Win 7sp1/Win 10

**Comment by dwoz** [comment]
@sotona- 
Can you provide an example of the command you are running?

**Comment by sotona-** [comment]
> @sotona-
> Can you provide an example of the command you are running?

For example:
```
start_app:
  cmd.run:
    - name: "schtasks /create /TN StartAPP /TR \"C:\\APP\\{{version}}\\app.exe c:\\auto\\queue.log\" /SC ONCE /ST (get-date).AddMinutes(2).ToString(\"HH:mm\") /V1 /Z /F /IT /RU username"
    - shell: powershell
```
