### ISSUE TITLE
opensuse pkg.installed failed

### ISSUE THREAD

**Issue by gray380** [saltstack/salt#53942]
### Description of Issue
OpenSuse. State pkg.installed has failed.
In the same time zypper on minion can find and install the package:
```
$ zypper search elasticsearch
Building repository 'elastic' cache ..................................................................................................................[done]
Loading repository data...

S | Name                         | Summary                                                 | Type   
--+------------------------------+---------------------------------------------------------+--------
  | elasticsearch                | Distributed RESTful search engine built for the cloud   | package

```

### Setup
```
elastic-public-key:
  cmd.run:
   - name: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

elasticsearch-repo:
    pkgrepo.managed:
        - name: elastic
        - humanname: Elastic repository for {{ version }}.x packages
        - baseurl: https://artifacts.elastic.co/packages/{{ version }}.x/yum
        - gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        - keyid: D27D666CD88E42B4
        - gpgcheck: 1
        - disabled: False

elasticsearch.install:
  pkg.installed:
    - name: elasticsearch
```

### Steps to Reproduce Issue
```
$ salt-ssh 'elk-es-03' state.apply elasticsearch
----------
          ID: elastic-public-key
    Function: cmd.run
        Name: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
      Result: True
     Comment: Command "rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch" run
     Started: 12:47:23.714546
    Duration: 457.36 ms
     Changes:   
              ----------
              pid:
                  23224
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: elasticsearch-repo
    Function: pkgrepo.managed
        Name: elastic
      Result: True
     Comment: Configured package repo 'elastic'
     Started: 12:47:29.975865
    Duration: 508.354 ms
     Changes:   
              ----------
              repo:
                  elastic
----------
          ID: elasticsearch.install
    Function: pkg.installed
        Name: elasticsearch
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'elasticsearch.install'
              Reason: 'pkg' __virtual__ returned False: 'ascii' codec can't decode byte 0xc3 in position 40577: ordinal not in range(128)
     Changes:   

Summary for elk-es-03
------------
Succeeded: 2 (changed=2)
Failed:    1
------------
```

### Versions Report
```
$ salt-ssh --versions-report

Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Jun 24 2019, 04:54:02)
   python-gnupg: Not Installed
         PyYAML: 5.1.1
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: Not Installed
 
System Versions:
           dist: arch Manjaro Linux
         locale: UTF-8
        machine: x86_64
        release: 4.19.59-1-MANJARO
         system: Linux
        version: arch Manjaro Linux

```
