### ISSUE TITLE
salt-ssh pkgrepo claims for already installed package

### ISSUE THREAD

**Issue by gray380** [saltstack/salt#53940]
### Description of Issue
Managing Debian repo list failed with following error: 
`Error: 'python-apt' package not installed`

package 'python-apt' is already installed at the minion:
```
$ dpkg -l | grep python-apt
ii  python-apt                      1.4.0~beta3                    amd64        Python interface to libapt-pkg
ii  python-apt-common               1.4.0~beta3                    all          Python interface to libapt-pkg (locales)

```

### Setup
```
{% set version = salt['pillar.get']('elasticsearch:repo:version', '7') %}

apt-transport-https:
    pkg.installed

elasticsearch-repo:
    pkgrepo.managed:
        - humanname: Elastic repository for {{ version }}.x packages
        - name: deb https://artifacts.elastic.co/packages/{{ version }}.x/apt stable main
        - file: /etc/apt/sources.list.d/elastic-{{ version}}.x.list
        - gpgcheck: 1
        - key_url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        - require:
            - pkg: apt-transport-https  
```       

### Steps to Reproduce Issue
`$ salt-ssh 'elk-es-02' state.apply elasticsearch`
----------
          ID: apt-transport-https
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 08:49:23.419483
    Duration: 119.799 ms
     Changes: 
----------
          ID: elasticsearch-repo
    Function: pkgrepo.managed
        Name: deb https://artifacts.elastic.co/packages/7.x/apt stable main
      Result: False
     Comment: Failed to examine repo 'deb https://artifacts.elastic.co/packages/7.x/apt stable main': Error: 'python-apt' package not installed
     Started: 08:49:23.554640
    Duration: 14.609 ms
     Changes:  
### Versions Report
```
$ salt-ssh --versions-report

Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Jun 24 2019, 04:54:02)
   python-gnupg: Not Installed
         PyYAML: 5.1.1
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: Not Installed
 
System Versions:
           dist: arch Manjaro Linux
         locale: UTF-8
        machine: x86_64
        release: 4.19.59-1-MANJARO
         system: Linux
        version: arch Manjaro Linux
```
