### ISSUE TITLE
django_orm pillar provider using outdated django.db.models.loading

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt#53956]
The django_orm pillar provider makes reference to django.db.models.loading.
This doesn't exist in newer versions of Django.

It was deprecated in 1.7 here: https://docs.djangoproject.com/en/2.2/releases/1.7/#app-loading-refactor.

When dealing with newer Django applications, the salt master will return the following error:
```
2019-07-22 18:03:22,181 [salt.loaded.int.pillar.django_orm:238 ][ERROR   ][32493] Failed to import library: No module named 'django.db.models.loading'
```

Master still appears to be affected, but I am running 2019.2.0.
```
root@salt:~ # salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Jul 11 2019, 01:10:39)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 12.0-RELEASE-p3
         system: FreeBSD
        version: Not Installed
 
root@salt:~ # 
```
