### ISSUE TITLE
webutil.user_exists logs grep error on first run

### ISSUE THREAD

**Issue by amaclean199** [saltstack/salt#53977]
### Description of Issue
The first time this state is executed an error level output is logged on the minion. I believe this is because an attempt is made to grep the file without first checking that the file exists.

### Setup
```
htpasswd_file:
  webutil.user_exists:  # Im really not sure why this is under webutil, not htpasswd as per the docs.
    - name: <user>
    - password: <password>
    - htpasswd_file: /etc/nginx/.htpasswd
    - force: true
    - require:
      - pkg: apache2-utils
```

### Steps to Reproduce Issue
```
[ERROR   ] Command '['grep', '<user>', '/etc/nginx/.htpasswd']' failed with return code: 2
[ERROR   ] stderr: grep: /etc/nginx/.htpasswd: No such file or directory
[ERROR   ] retcode: 2
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-47-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
