### ISSUE TITLE
file.serialize should support check_cmd

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#53982]
Would like for file.serialize to support check_cmd. While check_cmd should give correct json, yaml, etc, output, we can use check_cmd to run configuration validators that make sure the contents are sensible. It may be valid JSON but the names could be all wrong, etc, which we can catch with check_cmd.

Also, I don't get a warning when I pass check_cmd to file.serialize and it's ignored, which seems like a bad practice.

**Comment by dwoz** [comment]
@teran-mckinney Can you please provide a more detailed use case with an example of the desired behavior. Perhaps an example state and the desired output?

**Comment by teran-mckinney** [comment]
I would like to do:

```
hedron_hivemind_base_configuration:
  file.serialize:
    - name: /etc/hivemind.json
    - dataset_pillar: hedron.hivemind
    - mode: 0400
    - formatter: json
    - check_cmd: hivemind get_config --config_file
```

Instead of:

```
hedron_hivemind_base_configuration:
  file.serialize:
    - name: /etc/hivemind.json
    - dataset_pillar: hedron.hivemind
    - mode: 0400
    - formatter: json

hedron_hivemind_base_configuration_verify:
  cmd.run:
    - name: hivemind get_config --config_file /etc/hivemind.json
    - unless: hivemind get_config --config_file /etc/hivemind.json
```
