### ISSUE TITLE
service.running with watch always fail,help me please

### ISSUE THREAD

**Issue by kussatom** [saltstack/salt#54009]
### Description of Issue
I can't do that run a service file whit watch
### Setup

nginx:
  service.running:
    - watch:
      - file: /etc/nginx/conf.d/django.conf

### Steps to Reproduce Issue
run  :   salt '*' state.sls  centos7/nginx
get:   
    testserver:
----------
          ID: nginx
    Function: service.running
      Result: False
     Comment: The following requisites were not found:
                                 watch:
                                     file: /etc/nginx/conf.d/django.conf
     Started: 05:21:54.306208
    Duration: 0.063 ms
the file   /etc/nginx/conf.d/django.conf is real exist in the minion machine,
i do it by document the whole day,but failed , please help~
     Changes:
### Versions Report
 salt 2019.2.0 (Fluorine)

**Comment by hemebond** [comment]
Watching a file requires a state ID, not any file path, e.g.:

```
django_config:
  file.managed:
    - name: /etc/nginx/conf.d/django.conf

nginx:
  service.running:
    - watch:
      - file: django_config
```
