### ISSUE TITLE
[Feature request] Archive.extracted to be able to remove top level directory

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#54012]
### Description of Issue
I have the following workflow in the ansible:

1) Download archive md5 sum file.
2) Check local archive(if exists) against md5 in 1)
3) If it differs(or no old archive) - download the new archive on top of the old one
4) If we downloaded archive in 3) we check for a specific directory(with archive name) and if it exists - we delete it.
5) We unarchive archive, it will have the same name as we deleted at step 4)

The idea here is to release applications with a version like "**master**". It constantly updated and we can't use something like
`onlyif: path/to/file`

Since it can exist but it could be old. So we rely on the md5 sum and if it's changes - we overwrite old directory by deleting it first and unarchive after.

And since slots are not a thing yet in requisites I'm not particularly sure how to implement this logic in the current state of Salt.

What I tried:
`clean: True` argument - it's only removing the diff between current and new files based on file names.
`overwrite: True` - leads to the state to lose idempotency 
`prereq` - with `file.absent` - leads to the state to be run every time

### Versions Report
2019.02

**Comment by waynew** [comment]
So you have an archive, say `master.zip` that you've deployed, and then you want to change that `master.zip` and then deploy it, but only if there are changes from the `master.zip` that exists on the minion?

**Comment by Oloremo** [comment]
@waynew 
The idea here is to be able to deploy a new release with the same name. For example "master". Imagine we deployed it once and now we have a directory called "master" with the contents of this archive.

Now new commit was pushed to the master branch of something and the new artifact was created and we want to deploy it again. But now we have no means to check if the update is actually required since there is no sane version, just "master". So our approach here is to create a md5 sum file for each archive and if this md5 differs from the one we already have on a minion - we do a rollout\extraction.

So basically we use a 
`source_hash_update: True`

But the problem is that current arg `clean: True` is not suitable for that case since it just removes the diff between a local directory and the one that will be unarchived - based on filenames. And in our case filenames could be the same but they're could be very different,

So my proposal is to add the ability for a full cleanup for archive module. Not the diff between, but ensure that extraction will be done in the empty top directory.

**Comment by waynew** [comment]
@Oloremo have you looked into the `onchanges` or `watch` requisites? They might allow you to do what you want without having to add new functionality.

**Comment by Oloremo** [comment]
@waynew I looked at `prereq` with `file.absent` since I need to remove directory before the extraction. This leads to the state to be run every time.

It was something like this:
```
remove:
  file.absent:
    - name: /path/to/dir
    - prereq:
      - archive: extract
extract:
  archive.extracted:
    - source: salt://archive.tar.gz
    - name: /path/to/dir
    - source_hash_update: True
```

**Comment by waynew** [comment]
Try 

```
- onchanges:
  - archive: extract
```

instead

**Comment by Oloremo** [comment]
@waynew what is the point?.. onchanges will be executed after, right?
```
remove:
  file.absent:
    - name: /tmp/delme/master
    - onchanges:
      - archive: extract

extract:
  archive.extracted:
    - name: /tmp/delme/master
    - source: http://s3-proxy:9086/behavox-builds/delme/delme.tar.gz
    - source_hash: http://s3-proxy:9086/behavox-builds/delme/delme.tar.gz.md5
    - source_hash_update: True
    - keep_source: False
    - options: "--strip-components=1"
    - enforce_toplevel: False
    - trim_output: 1
```

```
----------
          ID: extract
    Function: archive.extracted
        Name: /tmp/delme/master
      Result: True
     Comment: http://s3-proxy:9086/behavox-builds/delme/delme.tar.gz extracted to /tmp/delme/master/, due to absence of one or more files/dirs
     Started: 18:15:09.842483
    Duration: 2794.561 ms
     Changes:
              ----------
              extracted_files:
                  no tar output so far
----------
          ID: remove
    Function: file.absent
        Name: /tmp/delme/master
      Result: True
     Comment: Removed directory /tmp/delme/master
     Started: 18:15:12.637463
    Duration: 319.746 ms
     Changes:
              ----------
              removed:
                  /tmp/delme/master
```

**Comment by Oloremo** [comment]
We figure out why `clean: True ` not working for us. We use a lot the `- options: "--strip-components=1"` feature to create our own top dir and this approach breaks the `clean` diff logic.

Obviously now we have 3 choises:
1) Stop using the `--strip-components=1`
2) Implement native support for `--strip-components` tar feature in archive(could be complicated + not cross platform)
3) Implement `clear top dir` logic - proposed in the PR

**Comment by waynew** [comment]
So, what's the problem with removing `--strip-components=1`? That seems like the correct fix to me.

**Comment by Oloremo** [comment]
That's a loaded question.
First of all, I think it's kinda a problem that some tar options break the module\state functionality.

And yes, obviously we could drop the `--strip-components` part but we'll have to re-pack most of our artifacts which we'd like not to do.

**Comment by waynew** [comment]
I'm confused as to why strip components is breaking anything? And why that would require re-packing your artifacts. Can you create a sample set of commands to duplicate the problem that you're seeing?

e.g.

```
cd /tmp
mkdir example
touch example/foo.txt
touch example/bar.txt
tar -cvf example.tar example
...
salt \* state.apply some_state
```

I'm not clear on what part is actually missing here, with what you really want to accomplish. From what I understand, you already have all the pieces available with your existing artifacts and Salt's existing behavior. But if that's not the case, we would like to know.

Can you create that [mcve](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Oloremo** [comment]
@waynew Sorry for the confusion. 
I wrote a simple bash script to prepare a mcve:
```
$ cat ~/54012.sh
#!/bin/bash

rm -rf /tmp/delme/master /tmp/archive1 /tmp/archive2
mkdir -p /tmp/archive1 /tmp/archive2

echo archive1 > /tmp/archive1/archive1only
echo archive1 > /tmp/archive1/both
echo archive2 > /tmp/archive2/archive2only
echo archive2 > /tmp/archive2/both

tar -C /tmp -czf /tmp/archive1_master.tar.gz archive1
mv /tmp/archive1_master.tar.gz /tmp/archive1/master.tar.gz
md5sum /tmp/archive1/master.tar.gz > /tmp/archive1/master.tar.gz.md5

tar -C /tmp -czf /tmp/archive2_master.tar.gz archive2
mv /tmp/archive2_master.tar.gz /tmp/archive2/master.tar.gz
md5sum /tmp/archive2/master.tar.gz > /tmp/archive2/master.tar.gz.md5
```

This script will create 2 directories which represent the deployment approach we're using. Both these directories will be archived into the archive with the name `master.tar.gz` and md5 sum of the archive will be created. So as you can see there is a 1 uniq file in each archive and 1 file with the name which exists in both archives.

Now please create this state:
```
create_top_dir:
  file.directory:
    - name: /tmp/delme/master

extract:
  archive.extracted:
    - name: /tmp/delme/master
    - source: salt://master.tar.gz
    - source_hash: salt://master.tar.gz.md5
    - source_hash_update: True
    - keep_source: False
    - options: "--strip-components=1"
    - enforce_toplevel: False
    - clean: True
```

And now we're ready to test.
Please copy `master.tar.gz` and `master.tar.gz.md5` from **archive1** directory to the fileserver root of your salt installation. Now run this state. It will create a directory `/tmp/delme/master` and extract first archive into it. So far so good. 

Now copy the `master.tar.gz` and `master.tar.gz.md5` from **archive2** directory to the fileserver root of your salt installation, overwriting the old ones. And run the state again.

And now you could see the issue. List the files in the **/tmp/delme/master**, they will look like this:
```
$ ls -1 /tmp/delme/master/
archive1only
archive2only
both
```

What'd I expect:
```
$ ls -1 /tmp/delme/master/
archive2only
both
```
because `clean: True` should revome the **archive1only** file but due to the `- options: "--strip-components=1"` it can't
