### ISSUE TITLE
config ext_pillar to mysql fail

### ISSUE THREAD

**Issue by danttang1987** [saltstack/salt#54044]
### Description of Issue

**Configuration in the Master configuration file:**
```
mysql:
  user: salt
  pass: 123.com
  db: saltdb
  host: 192.168.64.111

ext_pillar:
  - mysql:
    fromdb: 
      query: 'SELECT pillar,value FROM pillar WHERE minion_id = %s'
      depth: 2
      as_list: True
```
mysql select :
```
MariaDB [saltdb]> SELECT pillar,value FROM pillar WHERE minion_id = 'ns01'\G;
*************************** 1. row ***************************
pillar: foo
 value: ber
1 row in set (0.00 sec)

ERROR: No query specified
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Execute the following command:
```
systemctl restart salt-master.service
salt 'ns01' saltutil.refresh_pillar
salt 'ns01' pillar.items
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Finally, there is no corresponding pillar, and the Master log reports the following error.
```
[root@M-salt01 ~]# cat /var/log/salt/master
2019-07-28 19:59:37,207 [salt.pillar      :968 ][CRITICAL][23687] Specified ext_pillar interface fromdb is unavailable
2019-07-28 19:59:40,411 [salt.pillar      :968 ][CRITICAL][23686] Specified ext_pillar interface fromdb is unavailable
2019-07-28 19:59:41,998 [salt.pillar      :968 ][CRITICAL][23685] Specified ext_pillar interface fromdb is unavailable
2019-07-28 19:59:58,105 [salt.pillar      :968 ][CRITICAL][23684] Specified ext_pillar interface fromdb is unavailable
2019-07-28 20:00:03,332 [salt.pillar      :968 ][CRITICAL][23690] Specified ext_pillar interface fromdb is unavailable
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
[root@M-salt01 ~]# salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.12.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by garethgreenaway** [comment]
@danttang1987 Thanks for the report.  Comparing your configuration with the example here, 
https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.mysql.html, I'm wondering if the formatting is incorrect.  Can you try this updated version?

```
mysql:
  user: salt
  pass: 123.com
  db: saltdb
  host: 192.168.64.111

ext_pillar:
  - mysql:
      fromdb: 
        query: 'SELECT pillar,value FROM pillar WHERE minion_id = %s'
        depth: 2
        as_list: True
```
