### ISSUE TITLE
salt executing commands when rendering yaml with jinja code

### ISSUE THREAD

**Issue by sk1234567891** [saltstack/salt#54049]
### Description of Issue
I'm tying to install openjfx and openjre. The state failed to render because I'm inserting cmd.shell stdout to jinja varible and by that I can find the path to extract the tar of the jfx installation but when I'm do state.apply the salt try to render all the states and when he try to render openjfx the cmd.shell module run and can't find java because it's not installed yet. what should I do?

### Setup
```
{%- set os_family = salt['grains.get']('os_family') %}
{% set ver = salt['pillar.get']('openjfx:ver') %}
{% set source = salt['pillar.get']('openjfx:source') %}
################### **THE PROBLEM STARTS HERE** ###################
{% set installpath = salt['cmd.shell']('readlink -f $(which java) | rev | cut -d "/" -f4- | rev') %}
###################
...
openjfx:
  archive.extracted:
    - name: {{ installpath }}/
    - source: {{ source }}/openjfx-{{ ver }}-sdk-overlay-linux-amd64.zip
    - source_hash: {{ source }}/openjfx-{{ ver }}-sdk-overlay-linux-amd64.zip.sha256
    - options: -o
    - use_cmd_unzip: True
    - user: root
    - group: root
    - enforce_toplevel: False
    - if_missing: {{ installpath }}/bin/javafxpackager
```
### Steps to Reproduce Issue
just run this state on minion without java installed

### Versions Report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
