### ISSUE TITLE
salt 2019: regression in mount persistance

### ISSUE THREAD

**Issue by disaster123** [saltstack/salt#54084]
Since upgrading to 2019.2 and to py3 the mount persistance updates fstab on every state.apply. This is because the mount options are in no order and get randomly inserted into fstab.

Ex:
```
# grep cache /etc/fstab 
tmpfs		/home/cache	tmpfs	size=4G,mode=1777,defaults,nofail	0 0

salt-call state.apply
...
          ID: freitext-name mount
    Function: mount.mounted
        Name: /home/cache
      Result: True
     Comment: Target was already mounted. Updated the entry in the fstab.
     Started: 08:17:55.450982
    Duration: 48.521 ms
     Changes:   
              ----------
              persist:
                  update
...

# grep cache /etc/fstab 
tmpfs		/home/cache	tmpfs	defaults,nofail,size=4G,mode=1777	0 0

```

**Comment by disaster123** [comment]
This could be easily fixed by sorting opts:
i added the following lines to mount.py just before the for opt in opts loop starts:
```
392                 if opts:
393                     opts.sort()
```

**Comment by garethgreenaway** [comment]
@disaster123 Thanks for the report.  So far I haven't been able to reproduce this.  Can you provide the state file that you're using to see this issue?  Thanks!

**Comment by disaster123** [comment]
Be sure you use python3.

Example state:
```
mount /home/tmp:
  mount.mounted:
    - name: /home/tmp
    - device: /home/tmp
    - fstype: none
    - opts:
      - bind
      - nodev
      - noexec
      - nosuid
      - rw
    - hidden_opts:
      - nodev
      - noexec
      - nosuid
    - persist: True
    - require:
      - file: create /home/tmp
```
