### ISSUE TITLE
Include behavior changed from 2018.3.4 to 2019.2.0

### ISSUE THREAD

**Issue by rimokhy** [saltstack/salt#54126]
### Description of Issue
The issue is described under this google post : 
https://groups.google.com/forum/#!msg/salt-users/9ay4EfoIpUU/BEvf0tncDgAJ
Downgrading to 2018.3.4 fixed it

### Setup
```
include:
  - api.api:
      key: api
  - api.auth0:
      key: auth0
      defaults:
        - issuer: some_issuer_value
        - audience: some_audience_value
  - api.aws:
      key: aws
  - api.nexus:
      key: nexus
  - api.rabbitmq:
      key: rabbitmq
```

### Steps to Reproduce Issue
Execute pillar.items and see the result
2019.2.0 (unexpected result) :
```
    rabbitmq:
        ----------
        access_key_id:
            access_key_value
        application_id:
            application_id_value
        ... etc
```
2018.3.4 (expected result) : 
```
    rabbitmq:
        ----------
        keyfromrabbit1: value1
        keyfromrabbit2: value2
    nexus:
        ----------
        keyfromnexus: value
  ...etc
```
### Versions Report
[version_report.txt](https://github.com/saltstack/salt/files/3471392/version_report.txt)
