### ISSUE TITLE
Issues with pkgrepo.managed (zypperpkg)

### ISSUE THREAD

**Issue by kbabioch** [saltstack/salt#54137]
### Description of Issue

While trying to manage package repositories with Salt, I've noticed that there are several issues with `pkgrepo.managed` (in case of `zypperpkg`) and some attributes are not being applied and/or are lost.

### Setup

The original [repo file](https://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_15.1) I'm referring to is from a custom repository from the build service. It looks something like this:

```
[server_monitoring]
name=Server Monitoring Software (openSUSE_Leap_15.1)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_15.1/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_15.1/repodata/repomd.xml.key
enabled=1
```

### Steps to Reproduce Issue

I've translated this into the following `pkgrepo.managed` state:

```
pkgrepo.managed:
  - name: server_monitoring
    humanname: Server Monitoring Software
    baseurl: http://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_15.1/ 
    gpgkey: http://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_15.1/repodata/repomd.xml.key
    gpgcheck: 1
    gpgautoimport: True
    refresh: True
```

When applying the state, the resulting repo file in `/etc/zypp/repos.d/server_monitoring.repo` looks like this:

```
[server_monitoring]
enabled=1
autorefresh=1
baseurl=http://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_15.1/
type=rpm-md
gpgcheck=1
```

**There is a couple of issues with this:**

- `humanname` has not been applied and did not end up in the repo file
- `gpgkey` did not end up in the repo file

### Versions Report

```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.26.8
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-lp151.28.10-default
         system: Linux
        version: Not Installed
```

**Comment by twangboy** [comment]
Your state looks strange to me. I think it should be something like this:
```
server_monitoring:
  pkgrepo.managed:
    - name: server_monitoring
    - humanname: Server Monitoring Software
    - baseurl: http://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_15.1/ 
    - gpgkey: http://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_15.1/repodata/repomd.xml.key
    - gpgcheck: 1
    - gpgautoimport: True
    - refresh: True
```
