### ISSUE TITLE
Include issue with absolute and relative path result in conflicting IDs

### ISSUE THREAD

**Issue by gigi206** [saltstack/salt#54179]
### Description of Issue
I think include does not work as expected when include relative and absolute path

### Setup

- File **salt/bug/init.sls** :

```yaml
include:
  - .bug
  - .include
```

- File  **salt/bug/bug.sls**:

```yaml
bug:
  test.succeed_without_changes:
    - name: bug
```

- File  **salt/bug/include.sls**:
```yaml
include:
  - salt/bug/bug

include_bug:
  test.succeed_without_changes:
    - name: include_bug
    - require:
      - id: bug
```

### Steps to Reproduce Issue
```bash
$ salt-call state.apply salt/bug
local:
    Data failed to compile:
----------
    Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is 'bug' and is found in SLS 'base:salt/bug.bug' and SLS 'base:salt/bug/bug'
```

Now if I replace with full path in **salt/bug/init.sls**:
```yaml
include:
  - salt/bug/bug
  - salt/bug/include
```

```bash
$ salt-call state.apply salt/bug
local:
----------
          ID: bug
    Function: test.succeed_without_changes
      Result: True
     Comment: Success!
     Started: 10:20:43.032602
    Duration: 0.0 ms
     Changes:
----------
          ID: include_bug
    Function: test.succeed_without_changes
      Result: True
     Comment: Success!
     Started: 10:20:43.033596
    Duration: 0.0 ms
     Changes:

Summary for local
------------
Succeeded: 2
Failed:    0
------------
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.28.2
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free
```

**Comment by dmurphy18** [comment]
@gigi206 There was a bug in Salt 2019.2.0 where a leading '.' (dot) for an included path failed.  It broke the nightly builds too.  This has been fixed in the current 2019.2 branch and will be released in the upcoming Salt 2019.2.1 which is undergoing final QA.

Thanks for bringing it to SaltStack's attention, and if you would like to close this issue due to the above explanation, or keep it open until after Salt 2019.2.1 is released, and tested against your environment, which ever suits.

**Comment by gigi206** [comment]
Please keep this issue open until the 2019.2.1 release.

**Comment by dmurphy18** [comment]
Waiting to test once 2019.2.1 is released

**Comment by martintamare** [comment]
Any update on this ?
Still not working on 2019.2.2+ds-1

**Comment by thusoy** [comment]
I'm also seeing this on 2019.2.3. My problem is that
```yaml
# salt/state/init.sls
state:
    test.nop: []
```
and
```yaml
# salt/state/foo.sls
include:
    - .
```
Doesn't work alongside a regular `state`: ` The conflicting ID is 'state' and is found in SLS 'base:state' and SLS 'base:state.'` (note the trailing dot).
