### ISSUE TITLE
file.managed  replace: False+ ini.options_present : date change

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#54194]
### Description of Issue
Hi,

ini.options_present doesn't work if the file does not exist
So I use file.managed with ```replace: False``` like that the file is created if not exists and ini.options_present works.
But, when I generate a SystemD unit-file, I can see that the file modification date is changed at each run, but there is no change displayed in my Salt apply.

(note : today the documentation seems to be bad generated https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed parameter and default parameter are a same word `keep_sourceTrue`)

### Setup
```
loki_service_file:
  file.managed:
    - name: /etc/systemd/system/loki.service
    - replace: False
    - user: root
    - group: root
    - mode: '0644'

/etc/systemd/system/loki.service:
  ini.options_present:
    - separator: '='
    - strict: True
    - sections:
        Unit:
          Description: Loki Server
          After: network-online.target
        Service:
          User: loki
          Restart: on-failure
          ExecStart: {{ loki.server.install_dir }}/loki/loki -config.file {{ loki.server.install_dir }}/loki/loki.yml
        Install:
```

* Before run
```
#stat  promtail.service 
  File: 'promtail.service'
  Size: 231       	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 51797762    Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-08-13 14:38:38.511367546 +0200
Modify: 2019-08-13 14:17:50.544676154 +0200
Change: 2019-08-13 14:17:50.544676154 +0200
 Birth: -
```

* After Run
```
# stat  promtail.service 
  File: 'promtail.service'
  Size: 231       	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 51797762    Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-08-13 14:39:35.447674663 +0200
Modify: 2019-08-13 14:39:35.448674669 +0200
Change: 2019-08-13 14:39:35.448674669 +0200
 Birth: -
```

* apply output
```
Summary for tlsdck-p01-std.engsec
--------------
Succeeded: 120
Failed:      0
--------------
Total states run:     120
Total run time:    81.999 s
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.26.8
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.8 (default, Apr 25 2019, 21:02:35)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.21.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

```
