### ISSUE TITLE
[2019.2.0] boto_eblv2 requires both boto and boto3

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#54201]
### Description of Issue
The module boto_elbv2 is requiring both boto and boto3 to be installed to work according to `__virtual__()`. This is contrary to the documentation which claims only boto3 is needed. This looks like a result of relying on default arguments for the `check_boto_reqs` check.

```python
def __virtual__():
    '''
    Only load if boto3 libraries exist.
    '''
    has_boto_reqs = salt.utils.versions.check_boto_reqs()
    if has_boto_reqs is True:
        __utils__['boto3.assign_funcs'](__name__, 'elbv2')
    return has_boto_reqs
```

### Setup
I was doing this via state, here is a sample:
```
boto3:
  pip.installed:
    - reload_modules: True

add_instance:
  boto_elbv2.targets_registered:
    - name: arn:aws:elasticloadbalancing:us-east-1:xxxxxxx:targetgroup/django-app-staging/xxxxxxxxxxxx
    - targets:
      - i-1234xxxxxxxxx
    - profile:
        keyid: xxxxxxxxxxxxxxxx
        key: xxxxxxxxxxxx
    - require:
      - boto3
```
This will not work until boto is installed as well.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: 2.0.3
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.28.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 2.7.15+ (default, Nov 27 2018, 23:36:35)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1044-aws
         system: Linux
        version: Ubuntu 18.04 bionic
```
