### ISSUE TITLE
softwareupdate.list_available stops working on macOS Catalina.

### ISSUE THREAD

**Issue by weswhet** [saltstack/salt#54220]
### Description of Issue
When attempting to list any available software updates on macOS Catalina salt returns an empty list when there are actually available updates. This is due to a change in the output from `softwareupdate` that breaks the regex in the mac_softwareupdate module.

#### output on 10.14 and below.

```
Finding available software
Software Update found the following new or updated software:
   * Command Line Tools (macOS Mojave version 10.14) for Xcode-10.3
    Command Line Tools (macOS Mojave version 10.14) for Xcode (10.3), 199140K [recommended]
```

#### output on 10.15 beta 5

```
Software Update found the following new or updated software:
* Label: Command Line Tools beta 5 for Xcode-11.0
    Title: Command Line Tools beta 5 for Xcode, Version: 11.0, Size: 224804K, Recommended: YES,
```

### Setup

macOS Catalina B5. then run the following.

```
sudo touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
```

### Steps to Reproduce Issue

```
sudo salt-call softwareupdate.list_available
```

returns 
```
local:
    ----------
```
`/usr/sbin/softwareupdate --list` which salt runs.

returns

```
* Label: Command Line Tools beta 5 for Xcode-11.0
    Title: Command Line Tools beta 5 for Xcode, Version: 11.0, Size: 224804K, Recommended: YES,
```
### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.2
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Feb 13 2019, 13:42:12)
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 19.0.0
         system: Darwin
        version: 10.15 x86_64
```
