### ISSUE TITLE
Issues Targeting minions with unspecified grains in external_auth

### ISSUE THREAD

**Issue by scrum-my** [saltstack/salt#54268]
Hi All,

I'm fairly new to Salt and have a problem regarding the targeting with external_auth and the salt-api. My setup consists of a master, with 2 proxys and some testing minions connected to it.
Now if I try and target for the grain it works as designed, but if i try and use a minions name which has not the specified grain configured, salt will also generate output for this minion.
In case any further description is needed, do not hesitate to ask. Thanks in advance.

```
external_auth:
  pam:
    api-user:
      - 'G@os:RedHat':
        - .*
```
```
salt -a pam 'minion1.example.com' grains.item os
username: api-user
password:
minion1.example.com:
    ----------
    os:
        RedHat
```
```
salt -a pam 'minion2.example.com' grains.item os
username: api-user
password:
minion2.example.com:
    ----------
    os:
        SUSE
```
Salt-Master and -Minions running on Salt version 2019.2.0

**Comment by frogunder** [comment]
@scrum-my thank you for reporting this issue.

I am however not able to replicate it, it seems to work correctly for me on 2019.2.0.
Did you restart your master after you made changes to the config file?

My test case:
```
external_auth:
  pam:
    salt:
      - 'G@os:CentOS':
        - .*
```
```
[root@frode1 ~]# salt-key
Accepted Keys:
Debian
centos
Denied Keys:
Unaccepted Keys:
Rejected Keys:

[root@frode1 ~]# salt -a pam centos grains.item os
username: salt
password: 
centos:
    ----------
    os:
        CentOS
[root@frode1 ~]# salt -a pam Debian grains.item os
username: salt
password: 
Authorization error occurred.

[root@frode1 ~]# salt -a pam --username=salt --password=testpass centos grains.item os
centos:
    ----------
    os:
        CentOS
[root@frode1 ~]# salt -a pam --username=salt --password=testpass Debian grains.item os
Authorization error occurred.
 ```

Thanks.

**Comment by scrum-my** [comment]
Hi @frogunder thanks for the fast response,

I have restarted the master and api daemon after i made changes in the config files.
the environment is an old testing system, maybe some old configs have an impact on the changes i made? or maybe the proxys do have an impact on this?

I will check again and let you know, Thanks

**Comment by scrum-my** [comment]
Hello again,

sorry that it took so long to respond.
i set up a new test Environment, and name tagging is working occasionally so far.
```
master:~ # salt -a pam 'minion_node1' grains.item role 
username: api
password:                                              
minion_node1:                                          
    ----------                                         
    role:                                              
        - horst                                        
master:~ # salt -a pam 'syndic_node1' grains.item role 
username: api
password:                                              
Authorization error occurred.                          
master:~ # salt -a pam 'master_node1' grains.item role 
username: api
password:                                              
master_node1:                                          
    ----------                                         
    role:                                              
```
on master node the user is configured, maybe thats why its responding

unfortunately i found another problem with this.
if i try and target only for the desired grain it works as expected
```
master:~ # curl -k https://localhost:8080 -H 'Accept: application/x-yaml' -H 'X-Auth-Token: ee7dbbdbc137f86ecbfa546feaa0608e3a1c81f9' -d client=local -d tgt='G@role:horst' -d tgt_type=compound -d fun=test.ping
return:
- minion_node1: true
```

but using another grain with tgt_type compound it will show me all minions configured
```
master:~ # curl -k https://localhost:8080 -H 'Accept: application/x-yaml' -H 'X-Auth-Token: ee7dbbdbc137f86ecbfa546feaa0608e3a1c81f9' -d client=local -d tgt='G@os:suse' -d tgt_type=compound -d fun=test.ping
return:
- master_node1: true
  minion_node1: true
  syndic_node1: true
```

same with pam authentication
```
master:~ # salt -a pam -G 'os:suse' test.ping
username: api
password:
master_node1:
    True
minion_node1:
    True
syndic_node1:
    True
```
expected behavior would be that only the minion with role:horst would respond

external_auth.conf
```
master:~ # cat /etc/salt/master.d/external_auth.conf
external_auth:
  pam:
    api:
      - 'G@role:horst':
        - .*
```

not sure if this behavior comes from master, syndic and api daemon runnings as root or not. Running master service as root is required, cause pam is only working with root AFAIK.
i did a fresh install and master, syndic, minion, api all versions are at 2019.2
