### ISSUE TITLE
win_lgpo module cannot configure SceNoApplyLegacyAuditPolicy correctly

### ISSUE THREAD

**Issue by Prototyped** [saltstack/salt#54301]
### Description of Issue
win_lgpo sets an incorrect registry setting when applying GPO for SceNoApplyLegacyAuditPolicy aka "Audit: Force audit policy subcategory settings (Windows Vista or later) to override audit policy category settings". Enabling this policy is a pre-requisite for Advance Auditing policies to take effect.

Please see [win_lgpo source](https://github.com/saltstack/salt/blob/8043256/salt/modules/win_lgpo.py#L1802-L1828)&mdash;this appears to be a copy and paste error. Note that the registry value name changed when changing SceNoApplyLegacyAuditPolicy here is the same as (and seems to have been copied and pasted from) the preceding AuditBaseObjects GPO. The correct registry value is listed [here](https://www.stigviewer.com/stig/windows_server_2012_member_server/2014-01-07/finding/V-14230):

 Registry Hive: HKEY_LOCAL_MACHINE
 Registry Path: \System\CurrentControlSet\Control\Lsa\
 Value Name: SCENoApplyLegacyAuditPolicy
 Value Type: REG_DWORD

### Setup
Fragment of the state definition in my SLS:

```yaml
local_gpos_set_up:
  lgpo.set:
    - cumulative_rights_assignments: False
    - computer_policy:
      # [...]
      # Recommended GPOs from Microsoft Security Compliance Toolkit 1.0 baseline for Windows Server 2016 Version 1607.
      'Audit: Force audit policy subcategory settings (Windows Vista or later) to override audit policy category settings': Enabled  
```

### Steps to Reproduce Issue

1. Run Salt to apply the local GPO setting.

```powershell
c:\salt\salt-call.bat --local state.highstate saltenv=dev -l info
```

2. Using gpedit.msc, verify that the GPO for Local Computer Policy &rarr; Computer Configuration &rarr; Windows Settings &rarr; Security Options &rarr; Audit: Force audit policy subcategory settings (Windows Vista or later) to override audit policy category settings is "Not Defined".

3. From the command line, interrogating the correct registry entry shows that it is missing:
```powershell
PS C:\Users\Administrator\downloads> reg query HKLM\SYSTEM\CurrentControlSet\Control\Lsa /v SCENoApplyLegacyAuditPolicy


ERROR: The system was unable to find the specified registry key or value.
```

4. From the command line, interrogating the incorrect registry entry shows that it has been set:
```powershell
PS C:\Users\Administrator\downloads> reg query HKLM\SYSTEM\CurrentControlSet\Control\Lsa /v AuditBaseObjects

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa
    AuditBaseObjects    REG_DWORD    0x1
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```
