### ISSUE TITLE
Generating thin fails with PermissionError

### ISSUE THREAD

**Issue by brejoc** [saltstack/salt#54317]
### Description of Issue

Running `salt-run thin.generate overwrite=1` on openSUSE e.g. in `/root` directory fails with `PermissionError: [Errno 13] Permission denied: '/root'`.

In `thin.py` is a `os.chdir(start_dir)`, where `start_dir` is the the current directory. This is not possible for the user `salt` and that's why the error is happening.

### Setup

You can easily reproduce this with a Salt that is not running as root. Switching to a directory where the user salt is configured to use has no permissions should also work. Now run the command.

### Steps to Reproduce Issue

1. Set the user salt is using to `salt` for example.
2. `cd /root`
3. `salt-run thin.generate overwrite=1`
4. Command fails with PermissionError.

### Versions Report

```
salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 30 2019, 13:27:23) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-197.15-default
         system: Linux
        version: Not Installed
```
