### ISSUE TITLE
Unable to require an SLS if it only includes other ones

### ISSUE THREAD

**Issue by baby-gnu** [saltstack/salt#54310]
### Description of Issue

Updating the [libvirt-formula](https://github.com/saltstack-formulas/libvirt-formula) to [template-formula](https://github.com/saltstack-formulas/template-formula) standard, I figure out an issue with `include` and `require` of SLS files.

When the required SLS only contains a list of includes, salt say `Comment: The following requisites were not found`.

Here is my layout:

```
libvirt/
├── config
│   ├── clean.sls
│   ├── init.sls
│   ├── libvirtd.sls
│   └── service_config.sls
└── service
    ├── clean.sls
    ├── init.sls
    └── running.sls
```

I prefer to have one SLS file per configuration file but the service requires all of them, instead of listing each one as `file: config-file-<NAME>` in the service `require` I wanted to require directly the SLS `libvirt.config` and let the include do the job.

### Setup

Here is a minimal test case:

* `/srv/salt/test.sls`: the entry point
``` sls
include:
  - foo

Test nop:
  test.nop:
    - name: Test SLS
    - require:
      - sls: foo
```
* `/srv/salt/foo.sls`: the requisite only include another SLS
``` sls
include:
  - bar
```
* `/srv/salt/bar.sls`: the included SLS
``` sls
Test nop bar:
  test.nop:
    - name: bar
```

### Steps to Reproduce Issue

Running `salt-call --local --output yaml state.show_sls test` returns in the following:

```
local:
  Test nop:
    test:
    - name: Test SLS
    - require:
      - sls: foo
    - nop
    - order: 10001
    __sls__: test
    __env__: base
  Test nop bar:
    test:
    - name: bar
    - nop
    - order: 10000
    __sls__: bar
    __env__: base
```

But running `salt-call --local state.apply test` returns the following error:

```
local:
----------
          ID: Test nop bar
    Function: test.nop
        Name: bar
      Result: True
     Comment: Success!
     Started: 15:14:43.548259
    Duration: 0.673 ms
     Changes:   
----------
          ID: Test nop
    Function: test.nop
        Name: Test SLS
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     sls: foo
     Started: 15:14:43.549163
    Duration: 0.005 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:   0.678 ms

```

### Versions Report

I checked with current stable and development branch

```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.8 (default, Jan 14 2019, 11:02:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-58-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

``` 
Salt Version:
           Salt: 2019.2.0-n/a-37ceccb
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Jul 19 2019, 23:05:17)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist:   
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 5.0.0-25-generic
         system: Linux
        version: Not Installed
```

Regards.
