### ISSUE TITLE
file.managed conflicts with iptables.insert

### ISSUE THREAD

**Issue by Limanzhang** [saltstack/salt#54318]
### Description of Issue

We have a specific iptables file for server01, then use file.managed to import the ./services/server01/iptables file to /etc/sysconfig/iptables in ../services/server01/init.sls.
And then in the ../base/servergroup/init.sls, we use iptables.insert to insert rules for all of the servers in the servergroup ( including server01 ).

The firewall rules merged so we have specific rules and common rules. It used to work. And recently we had to change two rules from iptables.insert for servergroup. I found that all of the rules from ./services/server01/iptables were deleted and only rules added by iptables.insert were left.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
New added rules:
```
monitor-iptables:
  iptables.insert:
    - position: 1
    - table: filter
    - family: ipv4
    - chain: INPUT
    - jump: ACCEPT
    - match:
        - state
        - comment
    - comment: "Allow monitoring "
    - connstate: NEW
    - dport: 0000
    - proto: tcp
    - source: "XXX.XXX.XX.XX,XXX.XXX.XX.XX"
    - save: True
```

file.managed code:
```
/etc/sysconfig/iptables:
  file.managed:
    - source: salt://server01/iptables
    - mode: 600
    - user: root
    - group: root
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
From the state.log:
```
ID: /etc/sysconfig/iptables
    Function: file.managed
      Result: True
     Comment: File /etc/sysconfig/iptables updated
     Started: 13:28:06.860706
    Duration: 8.843 ms
     Changes:
```
Then it deleted all of the existing rules.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
minion version:
```
           Salt: 2015.5.10
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.5.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

master version:
```
           Salt: 2015.5.10
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```
