### ISSUE TITLE
load_json not working as expected

### ISSUE THREAD

**Issue by gigi206** [saltstack/salt#54375]
#34811 seems to be not solved

Indeed like it's shown in the [documentation](https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.jinja.html) the following code is not working:
```
{%- set json_src = "{'bar': 'for real'}"|load_json %}
```

My code is:
```
{% set npm = salt['cmd.run']('npm list --json --silent --global --depth=0') | load_json %}
```

```
salt-call cmd.run "npm list --json --silent --global --depth=0"
local:
    {
      "dependencies": {
        "eslint": {
          "version": "6.3.0",
          "from": "eslint@6.3.0",
          "resolved": "https://registry.npmjs.org/eslint/-/eslint-6.3.0.tgz"
        }
      }
    }
```

And the code result with and error: 
```
{% set npm = salt['cmd.run']('npm list --json --silent --global --depth=0') | load_json %}    <======================
```

I try this one and it's not working too:
```
{% load_json as install_version %}
  {{ salt['cmd.run']('npm list --json --silent --global --depth=0') | json }}
{% endload %}
```

```
Salt Version:
           Salt: 2019.2.0-n/a-37ceccb

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
         Jinja2: 2.10.1
        libgit2: 0.28.2
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free
```
