### ISSUE TITLE
salt.runner test mode not working

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#54382]
### Description of Issue
If I run an orchestration with `salt.runner` notation and with `test=True` I get the following:
https://gist.github.com/Oloremo/5a1ab1f0dad78a62c920b0d8229cc265

To make it even worse - it has an exit code `0`.

Running the same with `test=False` works as expected. 

### Setup
My orchestration:
```
orch.runner.java:
  salt.runner:
      - name: state.orchestrate
      - parallel: False
      - kwarg:
          mods: orch/services/java
```

`orch/services/java`:
```
orch.java.install:
  salt.state:
    - tgt: '*'
    - sls:
      - formula.java
```

### Steps to Reproduce Issue
Create the orchestration with `salt.runner` and run it with `test=True`.

### Versions Report
Everything is on 2019.2.0

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 13 2018, 18:24:23)
   python-gnupg: 0.4.4
         PyYAML: 5.1.1
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
