### ISSUE TITLE
docker_image.present fails first time when python3-docker module is installed

### ISSUE THREAD

**Issue by golpa** [saltstack/salt#54449]
### Description of Issue
I'm trying to use `docker_image.present` but salt fails to detect the module on first `state.apply` because the required python modules are installed in that run. On second `state.apply` the module is detected and used. This is even the case with `reload_modules: true` set.

On the first run I see:
```
----------
          ID: Docker
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: python3-docker
              The following packages were already installed: docker-ce
     Started: 16:12:02.098635
    Duration: 1403.352 ms
     Changes:   
              ----------
              python3-docker:
                  ----------
                  new:
                      1.9.0-1
                  old:
              python3-websocket:
                  ----------
                  new:
                      0.37.0-2
                  old:
----------
          ID: Kubernetes Dependency Image k8s.gcr.io/pause
    Function: docker_image.present
        Name: k8s.gcr.io/pause
      Result: False
     Comment: State 'docker_image.present' was not found in SLS 'kube-minion'
              Reason: 'docker_image' __virtual__ returned False: 'docker.version' is not available.
     Changes:
```

On the minion itself the `salt-minion` logs have this error:
```
salt-minion[138912]: [ERROR   ] State 'docker_image.present' was not found in SLS 'kube-minion'
salt-minion[138912]: Reason: 'docker_image' __virtual__ returned False: 'docker.version' is not available.
```

However, it works on second run:
```
----------
          ID: Docker
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed and are at the desired version
     Started: 16:29:44.739748
    Duration: 26.875 ms
     Changes:  
----------
          ID: Kubernetes Dependency Image k8s.gcr.io/pause
    Function: docker_image.present
        Name: k8s.gcr.io/pause
      Result: True
     Comment: Image 'k8s.gcr.io/pause:3.1' was pulled
     Started: 16:29:44.859688
    Duration: 1079.729 ms
     Changes:   
              ----------
              Layers:
                  ----------
                  Pulled:
                      - 67ddbfb20a22
              Status:
                  Downloaded newer image for k8s.gcr.io/pause:3.1
              Time_Elapsed:
                  0.4564225673675537
              retcode:
                  0
```
### Setup
I have two state files. docker.sls:
```
Docker:
  pkg.installed:
    - pkgs:
        - docker-ce: 18.06.1~ce~3-0~debian
        - python3-docker
    - install_recommends: False
    - reload_modules: true
```

and kube.sls:
```
include:
  - docker

Kubernetes Dependency Image k8s.gcr.io/pause:
  docker_image.present:
    - name: k8s.gcr.io/pause
    - tag: 3.1
    - reload_modules: True
    - require:
      - pkg: Docker
      - service: Docker
      - pkg: Kubernetes Dependencies
```

This may be related to #54332 but in that case `pip` is the installation method and the error message is different. 

### Steps to Reproduce Issue
1) Run `salt <minion> state.apply`
2) Get Failure
3) Run `salt <minion> state.apply`
Success!

### Versions Report
On Master:
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9 
```

On the Minion (after `python3-docker` has been installed):
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: 1.9.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9 
```

**Comment by xeacott** [comment]
I'm not reproducing this entirely, getting a different error but may be with my sls file...
```
linux:
----------
          ID: Docker
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed and are at the desired version
     Started: 18:51:18.833487
    Duration: 95.318 ms
     Changes:
----------
          ID: Kubernetes Dependency Image k8s.gcr.io/pause
    Function: docker_image.present
        Name: k8s.gcr.io/pause
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     service: Docker
                                     pkg: Kubernetes Dependencies
     Started: 18:51:18.950491
    Duration: 0.179 ms
     Changes:

Summary for linux
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:  95.497 ms
```
I did use the provided states above

**Comment by xeacott** [comment]
I probably am missing some kubernetes package

**Comment by xpicio** [comment]
Hello i'm reporting the same issue using [docker formula](https://github.com/saltstack-formulas/docker-formula) (it seems that in docker formula they use `reload_modules: true`)

Here a snippet of my sls file:
```
include:
  - docker

internal_network:
  docker_network.present:
    - subnet: 172.20.0.0/16

redis service:
  docker_container.running:
    - name: redis
    - image: registry.***.***/***/redis:v1
    - binds:
      - /opt/redis/data:/data
    - ports:
      - 6379
    - networks:
      - internal_network
      - bridge
    - restart_policy: on-failure:3
    - log_driver: syslog
    - log_opt:
      - syslog-facility: daemon
```

The error on first run:
```
----------
          ID: internal_network
    Function: docker_network.present
      Result: False
     Comment: State 'docker_network.present' was not found in SLS 'init-gtw'
              Reason: 'docker_network' __virtual__ returned False: 'docker.version' is not available.
     Changes:
----------
          ID: redis service
    Function: docker_container.running
        Name: redis
      Result: False
     Comment: State 'docker_container.running' was not found in SLS 'init-gtw'
              Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.
     Changes:
----------
```

The result on second run:
```
----------
          ID: internal_network
    Function: docker_network.present
      Result: True
     Comment: Network 'internal_network' created
     Started: 01:48:06.168053
    Duration: 157.235 ms
     Changes:
              ----------
              created:
                  True
----------
          ID: redis service
    Function: docker_container.running
        Name: redis
      Result: True
     Comment: Created container 'redis'
     Started: 01:48:06.453425
    Duration: 12383.978 ms
     Changes:
              ----------
              container:
                  ----------
                  Networks:
                      ----------
                      internal_network:
                          ----------
                          Gateway:
                              ----------
                              new:
                                  172.20.0.1
                              old:
                                  None
                          IPAddress:
                              ----------
                              new:
                                  172.20.0.2
                              old:
                                  None
              container_id:
                  ----------
                  added:
                      128201edd8beb49da5321278b2ae5cf01dd8e36577357a09c0f474cb6936a800
              image:
                  ----------
                  Layers:
                      ----------
                      Pulled:
                          - e42672a2ca6a
                          - 823e4275fef6
                          - 327e62bcfef7
                          - be5997a801f5
                          - dc62338c8c74
                          - 6c40cc604d8e
                          - 79ed9185c842
                          - c2ad7a3b6c3f
                  Status:
                      Downloaded newer image for registry.***.***/***/redis:v1
                  Time_Elapsed:
                      3.1893012523651123
                  retcode:
                      0
              state:
                  ----------
                  new:
                      running
                  old:
                      None
```

Versions on server:
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.3
        libgit2: 0.28.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.9.4
         pygit2: 0.28.2
         Python: 3.7.5 (default, Oct 17 2019, 12:25:15)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.138+
         system: Linux
        version: Not Installed
```

Versions on minion:
```
root@ubuntu-18:/tmp# salt-call --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-29-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by lsh-0** [comment]
I'm getting this too on Salt `2018.3`

```
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 4.1.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-72-generic
         system: Linux
        version: Ubuntu 18.04 bionic
 
```

**Comment by lsh-0** [comment]
FWIW, ensuring the `docker` python library is installed prior to calling `highstate` seems to work. The `python-mysqldb` dependency doesn't seem to fail like this but historically we had problems with upgrading python using salt states as well (`reload_modules: true` never seemed to work for us either) so I think it's just safest to call the Python `docker` a hard prerequisite before running Salt.

**Comment by darkn3rd** [comment]
I run into the same issue with `salt-minion 2019.2.3 (Fluorine)` when running:
```bash
salt-call state.highstate --retcode-passthrough --local --log-level=debug --force-color
```

I install the docker module, but then run  `docker_container.running`, which does a Traceback.

**Comment by supfors** [comment]
Running into the same issue using salt 3000 on ubuntu 18.04. Installing `python3-docker` in advance is working for me. Any chance for a fix in 3000.1 ?

**Comment by 234d** [comment]
Same issue here on `Amazon Linux 2` and `salt-minion 3000`.
Tired setting both `reload_modules` and `force_reinstall` to `True` without sucess.

**Comment by max-arnold** [comment]
This looks like a potential cause: https://github.com/saltstack/salt/issues/56669#issuecomment-614863977

**Comment by richardsimko** [comment]
@max-arnold That seems to be specifically linked to Pip, looking at the PR which is later referenced as a fix (#56867) this only changed so that Pip triggers a reload, however even when installing using `pkg.installed` the Docker state fails.

**Comment by gecube** [comment]
I used the `reload_modules` and it looks like it worked for me. OK. Could you all make more thoroughly tests? I will try to repeat too :-)

**Comment by richardsimko** [comment]
@gecube Are you installing docker using `pkg.installed` or `pip.installed`?

**Comment by b-a-t** [comment]
> @gecube Are you installing docker using `pkg.installed` or `pip.installed`?

I have it with pip.installed.

Even that construction doesn't fix the problem on Salt 3000.3:

```yaml
salt-python-dependencies:
  pip.installed:
    - bin_env: /usr/bin/pip3
    - names:
      - elasticsearch == 7.5.1
      - docker
    - reload_modules: True
    - watch_in:
      - service: salt-minion_svc
```
