### ISSUE TITLE
yumpkg.group_install/group_info "packages" key mismatch

### ISSUE THREAD

**Issue by cvedel** [saltstack/salt#54458]
### Description of Issue
group_info has been updated to use more accurate keys, i.e.:

> The ``mandatory packages``,
>        ``optional packages``, and ``default packages`` keys have been renamed
>        to ``mandatory``, ``optional``, and ``default`` for accuracy ...

However, group_install is still looking for 'mandatory packages' and 'default packages' so it can only install packages explicitly mentioned in include.

### Setup
Master running on CentOS 7.6, minion running on CloudLinux 7.6, based on CentOS.

### Steps to Reproduce Issue

Try to install any package group on yum based system. In our case:
```
# yum groupinfo alt-nodejs11
Modules complémentaires chargés : fastestmirror, langpacks, rhnplugin
This system is receiving updates from CLN.
Aucun fichier de groupe n'est installé.
Maybe run: yum groups mark convert (see man yum)
Loading mirror speeds from cached hostfile
 * cloudlinux-x86_64-server-7: de-proxy.cloudlinux.com

Groupe : alt-nodejs11
 ID du groupe : alt-nodejs11
 Description : nodejs 11.x packages for cloudlinux os nodejs selector
 Paquets par défaut :
   +alt-nodejs11
   +alt-nodejs11-http-parser
   +alt-nodejs11-icu
   +alt-nodejs11-libicu
   +alt-nodejs11-libuv
   +alt-nodejs11-nodejs
   +alt-nodejs11-npm
   +alt-nodejs11-openssl
   +alt-nodejs11-runtime
   +alt-nodejs11-zlib
```
And:
```
# salt-call pkg.group_info alt-nodejs11
local:
    ----------
    conditional:
    default:
        - alt-nodejs11
        - alt-nodejs11-http-parser
        - alt-nodejs11-icu
        - alt-nodejs11-libicu
        - alt-nodejs11-libuv
        - alt-nodejs11-nodejs
        - alt-nodejs11-npm
        - alt-nodejs11-openssl
        - alt-nodejs11-runtime
        - alt-nodejs11-zlib
    description:
        nodejs 11.x packages for cloudlinux os nodejs selector
    group:
        alt-nodejs11
    id:
        alt-nodejs11
    mandatory:
    optional:
    type:
        package group
```
But:
```
# salt-call pkg.group_install alt-nodejs11
local:
    ----------
```

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 24 2019, 08:54:15)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.6 Vladimir Lyakhov
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-714.10.2.lve1.5.19.9.el7.x86_64
         system: Linux
        version: CloudLinux 7.6 Vladimir Lyakhov
