### ISSUE TITLE
Salt-SSH grains.get does not get nested grains

### ISSUE THREAD

**Issue by claudekenni** [saltstack/salt#54461]
### Description of Issue
Doing the following in a state file and running it via salt-ssh it not working correctly
`{% set array = grains.get('dict:array', '') %}`
Changing the line to this works
`{% set array = salt['grains.get']('dict:array', '') %}`

### Setup
Salt SSH with Grains coming from the Roster File

### Steps to Reproduce Issue
```
root@salt:/srv/salt# salt-ssh ssh_minion grains.item dict
ssh_minion:
    ----------
    dict:
        ----------
        array:
            - item1
            - item2
```
```
root@salt:/srv/salt# cat  testissue.sls
{% set array = grains.get('dict:array','') %}
{% set array1 = salt['grains.get']('dict:array','') %}

empty:
  test.configurable_test_state:
    - name: Empty
    - changes: False
    - result: True
    - comment: {{ array | json }}

not_empty:
  test.configurable_test_state:
    - name: Not Empty
    - changes: False
    - result: True
    - comment: {{ array1 | json }}
```
The comment in the first state is empty
```		
root@salt:/srv/salt# salt-ssh ssh_minion state.apply testissue
ssh_minion:
----------
          ID: empty
    Function: test.configurable_test_state
        Name: Empty
      Result: True
     Comment:
     Started: 16:10:51.536755
    Duration: 0.501 ms
     Changes:
----------
          ID: not_empty
    Function: test.configurable_test_state
        Name: Not Empty
      Result: True
     Comment: item1
              item2
     Started: 16:10:51.537396
    Duration: 0.416 ms
     Changes:

Summary for ssh_minion
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time:   0.917 ms
```
Also tried using builtin Grains, same result
```
root@salt:/srv/salt# cat testissue.sls
{% set array = grains.get('dns:ip4_nameservers','') %}
{% set array1 = salt['grains.get']('dns:ip4_nameservers','') %}

empty:
  test.configurable_test_state:
    - name: Empty
    - changes: False
    - result: True
    - comment: {{ array | json }}

not_empty:
  test.configurable_test_state:
    - name: Not Empty
    - changes: False
    - result: True
    - comment: {{ array1 | json }}

root@salt:/srv/salt# salt-ssh ssh_minion state.apply testissue
ssh_minion:
----------
          ID: empty
    Function: test.configurable_test_state
        Name: Empty
      Result: True
     Comment:
     Started: 16:15:42.654207
    Duration: 0.494 ms
     Changes:
----------
          ID: not_empty
    Function: test.configurable_test_state
        Name: Not Empty
      Result: True
     Comment: <SNIP>
              <SNIP>
     Started: 16:15:42.654842
    Duration: 0.44 ms
     Changes:

Summary for ssh_minion
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time:   0.934 ms
```
		
### Versions Report
```
root@salt:~# salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 3.8.0
       dateutil: 2.6.0
      docker-py: 3.7.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.6.0
   mysql-python: 1.3.7
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-142-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
