### ISSUE TITLE
ZFS module and encryption

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt#54462]
### Description of Issue
The current ZFS module does not appear to "properly" support encryption.

In order to create an encrypted dataset you need to issue a command line:
```zfs create -o encryption=on -o keylocation=/dev/shm/mykeyfile -o keyformat=passphrase tank/mydataset```

This can currently be handled using a state like:
```
tank/mydataset:
  zfs.filesystem_present:
    - properties:
        compression: lz4
        encryption: on
        keylocation: /dev/shm/mykeyfile
        keyformat: passphrase
```

Salt dutifully runs a 'zfs create -o encryption=on ... tank/mydataset``` and the dataset is created perfectly.

The problem comes in on the second run--because parameters like ```encryption=on``` are read-only after the dataset is created.

The second run of highstate results in a command being run:
```/usr/sbin/zfs set encryption=on tank/mydataset```

This throws a return code of 1 and spits out ```cannot set property for 'tank/isostore': 'encryption' is readonly```

This causes the state to fail and dependencies to fail.

One possible solution I can see would be to add a second 'properties' dict called 'create_properties' that would apply only on creation of the dataset--but that would probably be best debated by someone with a more intimate knowledge of salt.
