### ISSUE TITLE
Can't apply win_firewall state with ICMP proto

### ISSUE THREAD

**Issue by sotona-** [saltstack/salt#54472]
### Description of Issue
State win_firewall requires 'localport' parameter even in case of ICMP protocols. But netsh binary, which is used by this module, doesn't accept 'localport' argument with ICMP protocol.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
try to use this state with and w/o localport paramater:
```
icmp_firewall_rule:
  win_firewall.add_rule:
    - name: 'ICMP Allow incoming V4 echo request'
    - dir: in
    - protocol: icmp4
    - action: allow
    - localport: 1
```
with 'localport' parameter netsh will answer: a specified protocol value is not valid
without 'localport' parameter minon will say:  Missing parameter localport for state win_firewall.add_rule

### Versions Report
2019.2.0 py3

**Comment by sagetherage** [comment]
reopened to have this issue go through triage @xeacott are you able to triage this issue soon?

**Comment by xeacott** [comment]
@sagetherage Yep! And Thanks @sotona- for reporting this. I'll ping @cmcmarrow to see if he has any input on this.

**Comment by cmcmarrow** [comment]
@soer7022 

```
icmp_firewall_rule:
  win_firewall.add_rule:
    - name: 'ICMP Allow incoming V4 echo request'
    - dir: in
    - protocol: icmpv4
    - action: allow
    - localport: 1
```

 `icmpv4` not `icmp4`
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_firewall.html
