### ISSUE TITLE
salt hides errors when an existing PostgreSQL user could not be removed

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#54470]
Our state description:
```
abc__database_user_absent:
  postgres_user.absent:
    - name: abc
```

The output of salt
```
         ID: abc__database_user_absent
    Function: postgres_user.absent
        Name: abc
      Result: False
     Comment: User abc failed to be removed
     Started: 11:48:15.504545
    Duration: 460.202 ms
     Changes:   
```

The real output
```
postgres=# drop user userx;
ERROR:  role "userx" cannot be dropped because some objects depend on it
DETAIL:  339 objects in database abc

my-host:~ # psql -c 'DROP USER "userx"'
psql: FATAL:  role "root" does not exist
my-host:~ # echo $?
2
```

Our **expectation**:
```
         ID: abc__database_user_absent
    Function: postgres_user.absent
        Name: abc
      Result: False
     Comment: User abc failed to be removed
         Output: ERROR:  role "userx" cannot be dropped because some objects depend on it
                 DETAIL:  339 objects in database abc
     Started: 11:48:15.504545
    Duration: 460.202 ms
     Changes:   
```

Our **expection** in case salt uses the wrong system user
```
         ID: abc__database_user_absent
    Function: postgres_user.absent
        Name: abc
      Result: False
     Comment: User abc failed to be removed
         Output: psql: FATAL:  role "root" does not exist
     Started: 11:48:15.504545
    Duration: 460.202 ms
     Changes:   
```
