### ISSUE TITLE
pillar structure and callable

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#54504]
### Preamble
I am using proxy's pillars for examples because that's what I am mainly working on right now. However, after asking others to give their opinion. They noted this is a fundamental change to how pillars work in salt.

### Issue
Currently, working on adding hundreds of proxy minion's pillar data. I realized that the pillar "states" don't follow the naming convention of descriptor => module.function => key:value parameters you find with regular salt state files (.sls) which can contain multiple states within a single file. Instead the "descriptor" is taken from the file name and the highest level of the pillar state is usually "proxy:"
```yaml
/srv/pillar/$ ls
net-device1.sls top.sls

/srv/pillar/$ cat net-device1.sls
proxy:
  proxytype: networkswitch
  host: 172.23.23.5
  username: root
  passwd: letmein
```

This is okay for smaller salt clusters, however this is unwieldy at scale. If I am adding hundreds of proxy pillars, I'd prefer to segregate pillars by file with a grouping convention rather than each pillar getting its own name.
***
### Solution
I ask that we change the pillar code/convention to reflect what we do in states. If no unique descriptor is given at the top of a state, and its only one state in the file then it defaults to the filename as the descriptor. However, if you add multiple states into the file then each state should have its own descriptor at the top of states and you can refer to these individual states via the descriptor.
***
### Example
```yaml
/srv/pillar/$ ls
top.sls group1.sls group2.sls

/srv/pillar/$ cat group1.sls

net-device1:
  proxy:
    proxytype: networkswitch
    host: 172.23.23.5
    username: root
    passwd: letmein

net-device2:
  proxy:
    proxytype: networkswitch
    host: 172.23.23.6
    username: root
    passwd: letmein

net-device3:
  proxy:
    proxytype: networkswitch
    host: 172.23.23.7
    username: root
    passwd: letmein

/srv/pillar/$ salt-proxy --proxyid=net-device3 -d 
```
