### ISSUE TITLE
user.present add user fail when set gid

### ISSUE THREAD

**Issue by siitao** [saltstack/salt#54507]
### Description of Issue
I want to manually specify uid and gid when creating a user but it fails
But when I remove the gid parameter, everything is fine I want to know what should I do？

this is my sls user.sls
```
testuser:
  user.present:
    - shell: /bin/bash
    - home: /home/testuser
    - uid: 2000
    - gid: 2000
```

this is output
```
[root@salt-test-1-15 user]# salt test-server-2.15 state.sls user.user
test-server-2.15:
          ID: testuser
    Function: user.present
      Result: False
     Comment: Failed to create new user testuser
     Started: 23:51:44.296119
    Duration: 45.328 ms
     Changes:   

Succeeded: 0 (changed=1)
Failed:    1
Total states run:     1
Total run time: 112.391 ms
ERROR: Minions returned with non-zero exit code
```
when I remove the gid
```
testuser:
  user.present:
    - shell: /bin/bash
    - home: /home/testuser
    - uid: 2000
```
```
[root@salt-test-1-15 user]# salt test-server-2.15 state.sls user.user
test-server-3.156:
          ID: testuser
    Function: user.present
      Result: True
     Comment: New user testuser created
     Started: 00:37:28.417136
    Duration: 61.589 ms
     Changes:   
              fullname:
              gid:
                  2000
              groups:
                  - testuser
              home:
                  /home/testuser
              homephone:
              name:
                  testuser
              passwd:
                  x
              roomnumber:
              shell:
                  /bin/bash
              uid:
                  2000
              workphone:

Summary for test-server-2.15
Succeeded: 1 (changed=1)
Failed:    0
Total states run:     1
Total run time:  61.589 ms
```
### Versions Report
salt-master and minion version
salt-master 2017.7.8 (Nitrogen)
salt-minion 2017.7.8 (Nitrogen)
