### ISSUE TITLE
How can i pass cmd.wait along with my artifact.download function

### ISSUE THREAD

**Issue by Nishanth25** [saltstack/salt#54510]
### Description of Issue
I am working on a simple scenario, where i have to stop particular tomcat instance, extract a package,deploy and then start the instance back. I am not able to extract any sort of control over stop and start of instance.

### Setup
```
accounts_intl_stop_instance:
  cmd.run:
    - name: sh {{ pillar['accounts']['intl']['stopscript2x'] }}
    - cwd: {{ pillar['accounts']['intl']['bin_path'] }}
    - runas: {{ pillar['accounts']['intl']['user'] }}
accounts_intl_profile_package2x:
  artifactory.downloaded:
    - artifact:
        artifactory_url: {{ pillar['accounts']['intl']['nexus']['url'] }}
        repository: '{{ pillar['accounts']['intl']['nexus']['repo'] }}/{{ pillar['nexus-policy'] }}'
        group_id: '{{ pillar['accounts']['intl']['groupid'] }}'
        artifact_id: '{{ pillar['accounts']['intl']['profile2x']['artifactid'] }}'
        packaging: '{{ pillar['accounts']['intl']['profile2x']['package']['type'] }}'
        version: '{{ pillar['version'] }}'
    - target_file: {{ pillar['accounts']['intl']['profile2x']['package']['name'] }}
accounts_intl_profile_package_permission2x:
  file.managed:
    - name: {{ pillar['accounts']['intl']['profile2x']['package']['name'] }}
    - user: {{ pillar['accounts']['intl']['user'] }}
    - group: {{ pillar['accounts']['intl']['group'] }}
    - mode: 755
    - replace: False
accounts_intl_start_instance:
  cmd.run:
    - name: sh {{ pillar['accounts']['intl']['startscript2x'] }}
    - cwd: {{ pillar['accounts']['intl']['bin_path'] }}
    - runas: {{ pillar['accounts']['intl']['user'] }}
    - onchanges:
      - accounts_intl_profile_package2x
```
### Versions Report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 11 2019, 14:33:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.7 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.1.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.7 Maipo
