### ISSUE TITLE
scheduler on minions fail to run

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#54517]
### Description of Issue
I have some salt schedulers configured through pillar and they recently stopped working.

```
# salt minion1 pillar.get schedule
    ocsp_update:
        ----------
        _next_fire_time:
        _next_scheduled_fire_time:
        _seconds:
            86400
        _splay:
            None
        args:
            - haproxy.ocsp
        days:
            1
        function:
            state.apply
        name:
            ocsp_update
        range:
            ----------
            end:
                12:00am
            start:
                11:00am
```
if I run `schedule.show_next_fire_time ocsp_update`, it gives me the following output. Note that the `next_fire_time` is yesterday.
```


    ----------
    next_fire_time:
        2019-09-17T12:48:45
    result:
        True
```
And `next_fire_time` changes if I run `saltutil.refresh_pillar`, but is still not between `start` and `end` configured in the pillar.

```
  ----------
    next_fire_time:
        2019-09-19T10:17:27
    result:
        True
```

```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: 1.4.2.post1
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Aug 22 2019, 07:04:57)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE-p10
         system: FreeBSD
        version: Not Installed
```
