### ISSUE TITLE
2019.2.1: Warning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed

### ISSUE THREAD

**Issue by v4nTh3M4n** [saltstack/salt#54759]
### Description of Issue
Warning message: /usr/lib/python3.6/site-packages/salt/transport/zeromq.py:42: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed. Install tornado itself to use zmq with the tornado IOLoop.

### Steps to Reproduce Issue
Run salt-call test.ping.

In the minion log and in the terminal its shows:

[py.warnings      :99  ][WARNING ][6610] /usr/lib/python3.6/site-packages/salt/transport/zeromq.py:42: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  import zmq.eventloop.ioloop

### Versions Report
```
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Jun 12 2019, 01:12:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.3.1
 
System Versions:
           dist: redhat 8.0 Ootpa
         locale: ISO-8859-1
        machine: x86_64
        release: 4.18.0-80.7.2.el8_0.x86_64
         system: Linux
        version: Red Hat Enterprise Linux 8.0 Ootpa


```

**Comment by dwoz** [comment]
duplicate of #54759

**Comment by v4nRutt3n** [comment]
Maybe something went wrong?  #54759 is marked as a diplicate of  #54801, but the other way round as well?

**Comment by dwoz** [comment]
Sorry, I think some wires got crossed. Re-opened this issue.

**Comment by ZacharyDuBois** [comment]
I am also experiencing this issue on a fresh install (both master and minion) of SaltStack. Looks like main difference with configs is mine is on Debian 10.

```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.1 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.1 
```

**Comment by peter-scott** [comment]
I am encountering this too.

```
[WARNING ] /usr/lib/python3/dist-packages/salt/transport/zeromq.py:42: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
```

Looking up the import [zmq.eventloop.ioloop](https://github.com/zeromq/pyzmq/blob/4debf84af833a0e3958591b5d938c967e7bb963f/zmq/eventloop/ioloop.py), the module now has the following note:

> tornado IOLoop API with zmq compatibility
>
> This module is deprecated in pyzmq 17.
> To use zmq with tornado,
> eventloop integration is no longer required
> and tornado itself should be used.

```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: debian 10.1 
         locale: utf-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.1 
```

**Comment by dmurphy18** [comment]
@peter-scott Note in Debian 10, SaltStack only provides salt, all other packages are from the OS (same applies with some other OSs especially with Neon) and hence warnings are coming from those OS supplied packages.  There are some older OSs where SaltStack does provide those packages, for example: python-zmq but there they are only built (contents untouched) hence warnings are as originally supplied by the creators of that code.

**Comment by thusoy** [comment]
Confirming that this is still an issue in Debian 10 on 2019.2.3, but can be fixed by installing `python3-tornado`. This is the relevant depends from the salt-common deb which ends up installing `python3-tornado4`:
`python3-tornado4 (>= 4.2) | python3-tornado (<< 5), python3-tornado4 (>= 4.2) | python3-tornado (>= 4.2)` (no idea why it's duplicated)

**Comment by peter-scott** [comment]
@dmurphy18 the `python3-tornado` maintainers are clearly expecting us to upgrade to `python3-tornado` >5, so it seems like a valid issue that salt doesn't support that yet. 

What are the issues with using `python3-tornado` > 5? 
I have seen statements that there _is_ a compatibility problem but no clear description of _what_ compatibility problem.

**Comment by sharksforarms** [comment]
Getting the same issues on CentOS8, 2019.2.3

**Comment by thusoy** [comment]
Still a problem.

**Comment by emersonposadas** [comment]
Having the problem also on Amazon Linux 2:

```
[WARNING ] /usr/lib/python3.7/site-packages/salt/transport/zeromq.py:42: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  import zmq.eventloop.ioloop`
```

```
Salt Version:
           Salt: 2019.2.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.8 (default, Jul 24 2020, 20:26:49)
   python-gnupg: Not Installed
         PyYAML: 4.2
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.14.186-146.268.amzn2.x86_64
         system: Linux
        version: Not Installed
 ```
