### ISSUE TITLE
git lfs requires identity to perform checkout

### ISSUE THREAD

**Issue by feinu** [saltstack/salt#54789]
### Description of Issue
When attempting to clone a repo containing LFS files with `git.latest`, I'm encountering a `Permission denied` error during the `checkout` step:
```
salt.exceptions.CommandExecutionError: Command 'git checkout --force -b lfs-test origin/lfs-test' failed: Downloading testfile.lfstest (13 B)
Error downloading object: testfile.lfstest (1099f81): Smudge error: Error downloading testfile.lfstest (1099f819239adba18116089276ef35482bfea486a58aa759802eb1e7b7443f15): batch request: Permission denied (publickey).: exit status 255
```

I see the `identity` argument got added to several of the git commands in #51319, but not to `checkout`.  I've managed to fix the issue by adding it in, will submit a PR a bit later.

### Setup
Running the following SLS with `sudo salt-call --local --file-root=/home/vagrant/testsalt -linfo state.apply testgit`:
```
ensure git lfs is installed:
  pkg.installed:
    - name: git-lfs

ensure repo is cloned:
  git.latest:
    - name: <private_repo_uri>
    - target: <target_directory>
    - rev: lfs-test
    - branch: lfs-test
    - identity: <ssh_key_file>
    - force_checkout: True
    - force_fetch: True
    - force_reset: True
    - user: vagrant
    - require:
      - pkg: ensure git lfs is installed
      - cmd: ensure git lfs is configured for root

ensure git lfs is configured for root:
  cmd.run:
    # In 2019.2.1 (the first version with LFS support), it hard checks global user
    # config, and we run as root
    - name: git lfs install
    - unless: grep -q 'git-lfs smudge' /root/.gitconfig
    - require:
      - pkg: ensure git lfs is installed

### Steps to Reproduce Issue
1. Have a private repo with LFS files
2. Apply the state above

### Versions Report
This is reproducable running locally, I haven't tested it in a master-minion setup.
```
$ salt-call --version
salt-call 2019.2.1 (Fluorine)
```
