### ISSUE TITLE
schedule.present not idempotent when scheduler disabled

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#54820]
### Description of Issue
When the scheduler is disabled, the `schedule.present` state always reports changes

```
# salt-call schedule.disable
local:
    ----------
    comment:
        Disabled schedule on minion.
    result:
        True
# salt-call state.apply
local:
  Name: highstate - Function: schedule.present - Result: Changed Started: - 14:33:36.279721 Duration: 32.829 ms

Summary for local
--------------
Succeeded: 177 (changed=1)
Failed:      0
--------------
Total states run:     177
Total run time:    43.255 s
# salt-call state.apply
... etc.
```

### Setup
```
highstate:
  schedule.present:
    - enabled: true
    - function: state.apply
    - job_kwargs:
        saltenv: base
    - minutes: 15
    - splay: 60
    - returner: zabbix
    - run_on_start: true
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: 0.32.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.8 (default, Aug 20 2019, 17:12:48)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ISO-8859-1
        machine: x86_64
        release: 4.15.0-64-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
