### ISSUE TITLE
salt-call schedule.list doesn't work when minion not running

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#54846]
### Description of Issue
This may be expected behaviour?
```
# systemctl stop salt-minion
# salt-call schedule.list
local:
    ----------
    schedule:
        ----------
# systemctl start salt-minion
# salt-call schedule.list
local:
    schedule:
      enabled: true
      highstate:
        enabled: true
        function: state.apply
        jid_include: true
        kwargs:
          saltenv: base
        maxrunning: 1
        minutes: 15
        name: highstate
        returner: zabbix
        run_on_start: true
        splay: 60
```

https://gist.github.com/OrangeDog/fd08470a682752347efd52fe7a5b830d
