### ISSUE TITLE
`manage.bootstrap` gives nonsensical returns when called from orchestration

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#54860]
### Description of Issue

`manage.bootstrap` is a nice convenience method for handling the bootstrapping workflow over `salt-ssh` without actually having to call `salt-ssh` by hand. A natural next-step in the workflow would be `manage.accept` and followed by setting the highstate on the new minions.

It's pretty clear that it would be nice to combine the whole workflow above into an orchestration. Unfortunately, when called from an orchestration runner, `manage.bootstrap` *always* seems to succeed with a "None" result, even under what should ostensibly be error conditions.

```
          ID: vm_bootstrap
    Function: salt.runner
        Name: manage.bootstrap
      Result: True
     Comment: Runner function 'manage.bootstrap' executed.
     Started: 20:32:55.906305
    Duration: 3427.383 ms
     Changes:   
              ----------
              return:
                  None
```

### Setup
You'll need at least one virtual machine for which you know the IP, ssh username, and ssh password.

The bash scripts below implement the following tests:
- Call `manage.bootstrap` correctly
- Call `manage.bootstrap` without any arguments, and no roster 
- Call `manage.bootstrap` with the name of a minion that does not exist in the roster

The outputter reports the same thing each time.

### Steps to Reproduce Issue
(Work in progress)

### Versions Report
```
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug 20 2019, 17:12:48)
   python-gnupg: Not Installed
         PyYAML: 4.2
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-64-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
