### ISSUE TITLE
sysctl.present always shows changes

### ISSUE THREAD

**Issue by Paulo-Nunes** [saltstack/salt#54937]
### Description of Issue
When using `sysctl.present` for `net.ipv4.ip_local_reserved_ports` salt will always report changes have been made.

Changes should only be returned if the value is changed. Instead we see changes every time the state is applied.

### Setup
```
sysctl_net.ipv4.ip_local_reserved_ports:
  sysctl.present:
    - name: net.ipv4.ip_local_reserved_ports
    - value: 1,2-5,10-20
```
```
cat /proc/sys/net/ipv4/ip_local_reserved_ports
1,2-5,10-20
```

### Steps to Reproduce Issue
After state.apply
```
----------
          ID: sysctl_net.ipv4.ip_local_reserved_ports
    Function: sysctl.present
        Name: net.ipv4.ip_local_reserved_ports
      Result: True
     Comment: Updated sysctl value net.ipv4.ip_local_reserved_ports = 1,2-5,10-20
     Started: 15:02:09.444459
    Duration: 50.67 ms
     Changes:   
              ----------
              net.ipv4.ip_local_reserved_ports:
                  1,2-5,10-20
```

### Versions Report
Tested on 2019.2.0 and 2017.7.7
RHEL6/7
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.20.3
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.10 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-754.18.2.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.10 Santiago
```

**Comment by arizvisa** [comment]
This bug seems to exist because the `salt.modules.*_sysctl` modules look in `/etc/sysctl.conf` instead of checking the `sysfs` filesystem or the output of the `sysctl` command. It also doesn't support the `sysctl.d` directories.Then the `sysctl.show` function seems to parse the output of `sysctl -a` and exposes a `config` option to distinguish between showing present state and the configuration file.

I think until these modules' functions are refactored to support specifying the file via a `config` parameter, it'd be beneficial to update their documentation to allow the user distinguish between the ones that update the live state and the ones that update the configuration file (and both).

**Comment by arizvisa** [comment]
This hasn't been triaged yet.

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this, and we def want to ensure this is not showing changes on each run so it will need to get fixed.

**Comment by arizvisa** [comment]
Ftr, the `sysctl` namespace on Linux is directly parallel to `/proc/sys` namespace under procfs. So you can simply split along "." replacing it w/ `os.sep` to convert it to a file path that you can read or write to.

I think only on the BSDs, you'll be forced to either process the output of the `sysctl` binary or to make the system call directly.

**Comment by whytewolf** [comment]
ZD-5673

**Comment by piterpunk** [comment]
This problem still exists in 3003+ ?

I am doing tests with this state:
```
# cat /srv/salt/sysctl_54937.sls
sysctl_net.ipv4.ip_local_reserved_ports:
  sysctl.present:
    - name: net.ipv4.ip_local_reserved_ports
    - value: 1-5,10-20
```
Applying the state at first time, it shows changes:
```
# salt-call state.apply sysctl_54937
local:
----------
          ID: sysctl_net.ipv4.ip_local_reserved_ports
    Function: sysctl.present
        Name: net.ipv4.ip_local_reserved_ports
      Result: True
     Comment: Updated sysctl value net.ipv4.ip_local_reserved_ports = 1-5,10-20
     Started: 23:06:36.309555
    Duration: 51.239 ms
     Changes:   
              ----------
              net.ipv4.ip_local_reserved_ports:
                  1-5,10-20

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  51.239 ms
```
And, at second run, it says it's already at the correct state:
```
# salt-call state.apply sysctl_54937
local:
----------
          ID: sysctl_net.ipv4.ip_local_reserved_ports
    Function: sysctl.present
        Name: net.ipv4.ip_local_reserved_ports
      Result: True
     Comment: Sysctl value net.ipv4.ip_local_reserved_ports = 1-5,10-20 is already set
     Started: 23:07:06.728393
    Duration: 48.142 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  48.142 ms
```
It seems to be working Ok.

As for applying changes for a kernel parameter that is already set in the system, the sysctl state module does not only update the live parameter, but also write the data in `sysctl.conf` (or other named config file). So, if  the parameter is set, but not in the configuration file, the state will update it. This is clearer using `test=True`:
```
# sed -i -e '/ip_local_reserved_ports/d' /etc/sysctl.conf
# cat /proc/sys/net/ipv4/ip_local_reserved_ports 
1-5,10-20
# salt-call state.apply sysctl_54937 test=True
local:
----------
          ID: sysctl_net.ipv4.ip_local_reserved_ports
    Function: sysctl.present
        Name: net.ipv4.ip_local_reserved_ports
      Result: None
     Comment: Sysctl value is currently set on the running system but not in a config file. Sysctl option net.ipv4.ip_local_reserved_ports set to be changed to 1-5,10-20 in config file.
     Started: 23:17:53.593443
    Duration: 48.853 ms
     Changes:   

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:  48.853 ms
```
The current (2021-06-25) documentation describes this as the expected behaviour:
> Ensure that the named sysctl value is set in memory and persisted to the named configuration file. The default sysctl configuration file is /etc/sysctl.conf
