### ISSUE TITLE
pkg.version not returning for some packages

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#54988]
### Issue
`pkg.version` returning empty for mysql

### Context
I installed Mysql on a DigitalOcean Centos 7.6 with `salt \*mysql pkg.install mysql`, which was successful. Then ran `salt \*mysql pkg.version mysql`, which returned empty string. Which according to the docs means salt thinks the package isn't installed. I then ran `salt \*mysql cmd.run 'mysql --version'` and it returned back a proper version number.

### Setup
setup provider file for DigitalOcean:
```
digitalocean:
  driver: digitalocean
  personal_access_token: [INSERT TOKEN FROM DIGITALOCEAN]
  ssh_key_file:          [FULL PATH TO PRIVATE SSH KEY ON YOUR WORKSTATION]
  ssh_key_names:         [NAME OF PUBLIC KEY YOU SAVED ON DIGITALOCEAN ]
```
add hypervisor level information in profiles:
```
do-centos-7-8gb-nyc1:
    provider: digitalocean
    image: centos-7-x64
    size: 8gb
    location: nyc1
    private_networking: True
    backups_enabled: False
    ipv6: False
    create_dns_record: False
```
create an orchestration file to execute:
```
 minion_mysql:
    salt.runner:
    - name: cloud.profile
    - prof: do-centos-7-8gb-nyc1
    - provider: digitalocean
    - instances:
      - minion-mysql
    - opts:
        minion:
          master:
          - [YOUR WORKSTATION'S PUBLIC IPV4 ADDRESS]
```

### Steps to Reproduce Issue
then run the following commands on your host:
```
salt \*mysql pkg.install mysql;
salt \*mysql pkg.version mysql;
salt \*mysql cmd.run 'mysql --version';
```
NOTE: if you successfully spin up a virtual machine but cant get the master and minion to communicate then you need to open ports 4505 & 4506 on your router.

### Versions Report
```
root@CPC:/# salt --versions-report
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Oct  7 2019, 17:39:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-31-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
