### ISSUE TITLE
RegExp not working

### ISSUE THREAD

**Issue by DirkLaurenz** [saltstack/salt#54995]
### Description of Issue

Insert a line before with file.line
```
  file.line:
    - name: /etc/pam.d/su
    - mode: insert
    - before: "^account(.*?)pam_rootok.so"
    - content: "auth      required     pam_tally2.so deny=10 unlock_time=1200"
```
but salt states No changes to be made

This is the file:
```
#%PAM-1.0
auth     sufficient     pam_rootok.so
auth     include        common-auth
account  sufficient     pam_rootok.so                                   (before this it should be inserted)
account  include        common-account
password include        common-password
session  include        common-session
session  optional       pam_xauth.so
```
I tested the regexp on regexr, there it works

### Setup
```
  file.line:
    - name: /etc/pam.d/su
    - mode: insert
    - before: "^account(.*?)pam_rootok.so"
    - content: "auth      required     pam_tally2.so deny=10 unlock_time=1200"
```

### Steps to Reproduce Issue

salt-call state.highstate

### Versions Report

Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.178-94.91-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

Minion:
salt-call 2018.3.0 (Oxygen)
