### ISSUE TITLE
how to add rpm repos to centos?

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#55010]
### Description of Issue
Trying to add MySQL community database to a centos 7.6 VM.

This means adding the community repo link, `yum install https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm -y`, and then installing, `yum install mysql-community-server`.

Relatively easy to do in the terminal, but having trouble state-fully reproducing this in salt.
### working example using cmd.run
```
# File: /srv/salt/state/mysql/init.sls

mysql_repo:
  cmd.run:
    - name: yum install https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm -y

install_mysql:
  pkg.installed:
    - pkgs:
      - mysql-community-server

start_mysql:
  cmd.run:
    - name: systemctl start mysqld; systemctl status mysqld
```

Usually when you use `cmd.run` in salt states, that just means you dont know how to produce the state modules version. So can someone educate me on how to do this?

### Resources I have looked at:
- [salt docs: pkg.download](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.downloaded)
- [salt docs: pkg.installed](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed)
- [salt docs: pkgrepo.managed](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkgrepo.html#salt.states.pkgrepo.managed)
- [stackoverflow post](https://stackoverflow.com/questions/46224090/how-do-you-add-a-package-repo-and-key-to-apt-with-saltstack)
- [salt docs: yumpkg](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.yumpkg.html#salt.modules.yumpkg.install)
### Versions Report
```
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Oct  7 2019, 17:39:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-31-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by garethgreenaway** [comment]
@alan-cugler Thanks for the report.  For both RPMs you can use the pkg.installed state module, for the RPM to add the MySQL report if you use the `sources` argument to pkg.installed then the package will be downloaded.

Something like the following:
```
mysql_repo:
  pkg.installed:
   - sources:
      - mysql80-community-release: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm

install_mysql:
  pkg.installed:
    - pkgs:
      - mysql-community-server

start_mysql:
  cmd.run:
    - name: systemctl start mysqld; systemctl status mysqld
```
