### ISSUE TITLE
There was profile error: list index out of range

### ISSUE THREAD

**Issue by dilanb24** [saltstack/salt#55038]
### Description of Issue
For a testing purpose, I am launching Azure VM's via Salt. When I run the Salt script, I am getting the error related to allocate_public_ip

### Setup
```
azurearm-ubuntu16:
  provider: my-azurearm-config
  image: Canonical|UbuntuServer|16.04-LTS|latest
  size: Standard_B1s
  location: westeurope
  ssh_username: azureuser
  ssh_password: mypassword
  network: VirtualNetwork
  subnet: SubNet
  network_security_group: NSG
  network_interface: SaltNIC
  allocate_public_ip: False
  port: 22

  minion:
    master: master_ip
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
