### ISSUE TITLE
How run GIT provider with SaltStack 2019.2.0 and Python3 on Centos7 ?

### ISSUE THREAD

**Issue by ArthurREGNARD** [saltstack/salt#55037]
### Description of Issue
I'would like to use the gitfs provider to source my salt master. But actualy, that not running. I get this error on Salt-Master `start` :
```bash
[salt.utils.gitfs :2537][ERROR   ][4834] gitfs is configured but could not be loaded, are pygit2 and libgit2 installed?
```

### Steps to Reproduce Issue
  1. Install SaltStack with [bootstrap-salt.sh](https://bootstrap.saltstack.com).
Installing `Salt-Master` with `python3` and the pachage `python-pygit2`
```bash
/bin/bash /tmp/bootstrap_salt.sh -M -N -x python3 -p python-pygit2
```

  2. Configure the Salt-Master.
The `Salt-Master` config file is :
```yaml
interface: 192.168.50.50
master_id : master
auto_accept: False

gitfs_provider: pygit2
gitfs_ssl_verify: False
gitfs_base: base
fileserver_backend:
  - gitfs
gitfs_remotes:
  - git@gitlab.test.fr:infrastructure/states.git
  - git@gitlab.test.fr:infrastructure/formulas.git
gitfs_privkey: /etc/ssh/id_gitlab_test_fr
gitfs_pubkey: /etc/ssh/id_gitlab_test_fr.pub
```

### Questions
  1. Why Salt does not see `libgit2` and `pygit2` dependencies when the libs have been installed ?
  1. If someone has a procedure that works, I'm interested.

### OS Packages
```bash
[root@centos7]# yum list installed | grep git2
libgit2.x86_64                        0.26.6-1.el7                    @extras
python-pygit2.x86_64                  0.26.4-1.el7                    @epel
```

### Python
Python load PyGit2:
```bash
[root@centos7]# python -c "import pygit2, sys; print('python: {}'.format(sys.version)); print('pygit2: {}'.format(pygit2.__version__))"
    python: 2.7.5
    pygit2: 0.26.4
[root@centos7]# python3 -c "import pygit2, sys; print('python: {}'.format(sys.version)); print('pygit2: {}'.format(pygit2.__version__))"
    python: 3.6.8
    pygit2: 0.28.2
```

### Versions Report
```bash
[root@centos7]# salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.21.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```
