### ISSUE TITLE
file.comment refuses to comment the line if a different matching line is already commented out

### ISSUE THREAD

**Issue by jose1711** [saltstack/salt#55085]
### Description of Issue
If a file processed by `file.comment` state contains a line that is matching regex and is already commented out, state is not run.

### Setup
Minion and master are running on the same host. The goal is to have lines starting with "bar" commented out in file with the following contents:
```
bar1
foo1
#bar2
foo2
```
Using `sed` this could be achieved by running `sed -i '/^bar/s/^/#/' /tmp/foofile`. We want `salt` to do the same.

### Steps to Reproduce Issue
```
# cat /tmp/foofile
bar1
foo1
#bar2
foo2

# cat comment.sls 
Comment all lines containing bar:
  file.comment:
    - name: /tmp/foofile
    - regex: '^bar'

# salt localhost state.apply comment
[WARNING ] /usr/lib/python2.7/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

localhost:
----------
          ID: Comment all lines containing bar
    Function: file.comment
        Name: /tmp/foofile
      Result: True
     Comment: Pattern already commented
     Started: 09:19:33.989310
    Duration: 8.244 ms
     Changes:   

Summary for localhost
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   8.244 ms

```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 3.9.0
   pycryptodome: 3.9.0
         pygit2: Not Installed
         Python: 2.7.16 (default, Mar 11 2019, 18:59:25)
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 5.3.7-arch1-1-ARCH
         system: Linux
        version: Not Installed
```
