### ISSUE TITLE
Netmiko auto fetches pillars on failure

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#55107]
### Description of Issue
The netmiko proxy minion receives its pillar data from the master for being able to log into the device its managing. It will attempt to do so after getting that pillar. If the pillar is wrong (credentials arent any good) the netmiko proxy minions default actions is to continually fetch the pillars from master again and try to login to its device again. creating an infinite loop until someone changes the pillar data or kills the proxy.

### Setup
get a master up and put in fake proxy pillar data into the pillar for netmiko.

### Steps to Reproduce Issue
Then run command to initialize the proxy minion. The proxy will initialize successfully because the required key/values for the netmiko pillar are in place. Then the proxy will attempt and fail, and there you go! an infinite loop is born to suck down cpu cycles and bandwidth.

### Versions Report
```
bash-4.4$ salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 2.7.16 (default, May  6 2019, 19:35:26)
   python-gnupg: 0.4.2
         PyYAML: 5.1.1
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: Not Installed
```
