### ISSUE TITLE
vault module doesn't work anymore

### ISSUE THREAD

**Issue by gasmick** [saltstack/salt#55112]
### Description of Issue
Cannot access Hashicorp's Vault using the corresponding module after the upgrade to 2019.2.2 anymore. Worked with 2019.2.1

### Setup
```
cat /etc/salt/master.d/vault.conf
 vault:
   url: http://vault.service.consul:8200
   auth:                                  
       method: token                      
       token: s.XXXXXXXXXXXXXXXXXXXX  
   policies:                              
       - saltstack/minions
```

### Steps to Reproduce Issue

```
# salt 'salt-master*' vault.read_secret 'secret/icinga2/int_pu/icinga2_webadmin'
salt-master-pu-1b:
    None
salt-master-pu-1a:
    None
# vault read secret/icinga2/int_pu/icinga2_webadmin
Key                          Value
---                          -----
refresh_interval             768h
icinga2_webadmin_pwd_hash    $2y$10$2xxxxxxxxxxxxx
icinga2_webadmin_user        admin

# cat /var/log/salt/minion
2019-10-24 10:56:57,277 [salt.loaded.int.module.vault:265 ][ERROR   ][15599] Failed to list secrets! AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()

```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-1062.4.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```
