### ISSUE TITLE
smartos_imgadm cannot deal with orphan images

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#55136]
### Description of Issue
While testing 2019.2.2 I noticed that smartos_imgadm cannot deal with orphaned images due to them not having a 'name' key.

According to the SmartOS folks this should not happend unless you messed up with image creation. I'll try and write a fix for this to go into master.

### Setup
n/a

### Steps to Reproduce Issue
Have a SmartOS node with a broken image, rather hard to do unfortunately.

### Versions Report
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.3.0
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.6.6
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Oct 23 2018, 17:11:49)
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
