### ISSUE TITLE
salt.modules.match.search_by not working 2019.2.2

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#55149]
I have the following pillar setup following instructions 
https://docs.saltstack.com/en/2018.3/ref/modules/all/salt.modules.match.html

It has been working well for two years until I upgrade salt to 2019.2.2 today.
```
{% set region = grains['id'].split('.')[0] %}
region: {{ region }}
{% load_yaml as role_defs %}
web:
  - region1.minion1
  - region1.minion2
zabbix-agent:
  - "G@os:FreeBSD"
{% endload %}
{% set roles = salt.match.search_by(role_defs) or [] %}
role: {{ roles | yaml() }}
rr: [{{ region  }}.{{ roles | join(', ' ~ region ~ '.' ) }}]
```

For example, if I run
`salt region1.minion1 pillar.get role`, it used to give a list 
```
- web
- zabbix-agent
```
but now it gives only one
```
- zabbix-agent
```
This is happening to all my minions. And my highstate is based on `role`, which means everything is broken now.

```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: 1.4.2.post1
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Aug 22 2019, 07:04:57)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE-p10
         system: FreeBSD
        version: Not Installed
```
