### ISSUE TITLE
Module pip.py, grab files also from file-location

### ISSUE THREAD

**Issue by majo83** [saltstack/salt#5519]
Hey there,

I would like to do in my state file something like this:

```
  /path/to/my/virtualenv
    virtualenv.managed:
      - extra_index_url: 'file:///srv/packages/python/simple/'
      - no_site_packages: True
      - requirements: salt://path/to/my/requirements.txt
```

That however does not work, as in the module pip.py there's a check against if the url is valid or not. However there the file-"protocoll" is not recognized (for pip this url would be valid). I think this would be fix very easy to implement.
