### ISSUE TITLE
Bug: python3 version of saltstack omits some python modules

### ISSUE THREAD

**Issue by Heiko-san** [saltstack/salt#55230]
### Description of Issue

* on Amazon Linux 2 I have installed the python3 Version of Saltstack from `https://repo.saltstack.com/py3/amazon/$releasever/$basearch/2019.2`
* custom grains that use boto3 fail after the upgrade due to `-s` switch to interpreter

```
# head /usr/bin/salt-call
#!/usr/bin/python3 -s
'''
Directly call a salt command in the modules, does not require a running salt
...
```

* `-s`: Don't add user site directory to sys.path.
* boto3 package is installed to `/usr/local/lib/python3.7/site-packages/boto3`

```
# python3
Python 3.7.4 (default, Oct  2 2019, 19:30:55) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> 
```
```
# python3 -s
Python 3.7.4 (default, Oct  2 2019, 19:30:55) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'boto3'
```

### Setup

* on Amazon Linux 2 I have installed the python3 Version of Saltstack from `https://repo.saltstack.com/py3/amazon/$releasever/$basearch/2019.2`

#### master

```
salt --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Oct  7 2019, 12:59:55)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-134-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
#### minion

```
salt-call --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.4 (default, Oct  2 2019, 19:30:55)
   python-gnupg: Not Installed
         PyYAML: 4.2
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.14.146-120.181.amzn2.x86_64
         system: Linux
        version: Not Installed
```
