### ISSUE TITLE
startup states give no log feedback

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#55236]
### Setup
I am using the minion configuration option `startup_states` placed in its own file in the `/etc/salt/minion.d/` directory. The startup states pull down a repository and all the required libraries and keys are in place before hand.
***

### Description of Issue
On minion startup the specified states execute. The problem is regardless of a successful or failure execution of the state no feedback is presented in the logs. I can only tell if it succeeds by observing for the changes that those states are suppose to make. On failure the only way to check for errors is to manually run the state again with `salt \* state.sls [startup-state]`.
***

### Steps to Reproduce Issue
1) `nano etc/salt/minion.d/startup.conf`
```
startup_states: sls
sls_list:
  - test
```
2) `nano srv/salt/test.sls`
```
teststate:
  file.touch:
    - name: /root/testfile.txt
```
3) `systemctl restart salt-minion`
4) `ls /root/`
```
testfile.txt
```
5) `cat /var/log/salt/minion`
```
[This will be empty]
```
***

### Closing Remarks
So this feature is quite useful for startup setup, can offload minion spin up or auto update more implicitly. However the lack of log data really makes it difficult to want to use sine it makes investigation difficult when you are expecting it to just work. 

In my case I had it working in my development environment and then pushed to my testing environment. It failed because I forgot to copy over a pillar with the build, and that's whats so bothering about this issue. Without it reliably giving feedback someone could make a change on production, and cause these startup states to not fire and you have no idea why and no trail to follow.
***

### Versions Report
```
bash-4.4# salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 2.7.16 (default, May  6 2019, 19:35:26)
   python-gnupg: 0.4.2
         PyYAML: 5.1.1
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: Not Installed
```
