### ISSUE TITLE
CentOS 7 minion is not firing inotify beacons, even from the perspective of the minion

### ISSUE THREAD

**Issue by SecureshellV2** [saltstack/salt#55241]
### Description of Issue

I have attempted to use an inotify beacon on multiple CentOS 7 based systems and when I test I am unable to get the beacon to fire off at all on the minion. It is worth noting that I have been able to accomplish the same work on several OpenSuse boxes and it works just fine. 

### Setup
```
cat /etc/salt/minion.d/beacons.conf 
beacons:
  inotify:
    - files:
        /test/test.txt:
          mask:
            - create
            - modify
            - attrib
```

salt-call --local beacons.list
local:
    beacons:
      inotify:
      - files:
          /test/test.txt:
            mask:
            - create
            - modify
            - attrib
      pkgset:
        cookie: /var/cache/salt/minion/rpmdb.cookie
        interval: 5

### Steps to Reproduce Issue

Install salt minion and python-inotify, configure the beacon, restart the minion if it is already running and test modify the file. 

Looking at the logs using trace I see the beacon that is configured for pkgset is working, but inotify does not show up at all.

[TRACE   ] Interval counter: 5
[TRACE   ] ==== evaluating schedule now None =====
[TRACE   ] Beacon processing: pkgset
[TRACE   ] Processing interval 5 for beacon mod pkgset
[TRACE   ] Processing interval in map
[TRACE   ] Interval counter: 1
[TRACE   ] Skipping beacon pkgset. Interval not reached.
[TRACE   ] ==== evaluating schedule now None =====
[TRACE   ] Beacon processing: pkgset
[TRACE   ] Processing interval 5 for beacon mod pkgset
[TRACE   ] Processing interval in map
[TRACE   ] Interval counter: 2
[TRACE   ] Skipping beacon pkgset. Interval not reached.
[TRACE   ] ==== evaluating schedule now None =====
[TRACE   ] Beacon processing: pkgset
[TRACE   ] Processing interval 5 for beacon mod pkgset
[TRACE   ] Processing interval in map
[TRACE   ] Interval counter: 3
[TRACE   ] Skipping beacon pkgset. Interval not reached.
[TRACE   ] ==== evaluating schedule now None =====
[TRACE   ] Beacon processing: pkgset
[TRACE   ] Processing interval 5 for beacon mod pkgset
[TRACE   ] Processing interval in map
[TRACE   ] Interval counter: 4
[TRACE   ] Skipping beacon pkgset. Interval not reached.
[TRACE   ] ==== evaluating schedule now None =====

### Versions Report

MINION:

Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.27.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

The master is not in play this point but it is the following:

Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-95.29-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by arizvisa** [comment]
@SecureshellV2: not sure if it's related or if it'll help, but there's an undocumented option "beacons_before_connect" that can result in inotify beacons not being validated which makes salt think that there's no inotify beacons defined. If it does help, then this issue might be related to #48698.

In some cases it can also hide logging errors w/ inotify which is why I mention it.

**Comment by Ch3LL** [comment]
are you seeing the beacon getting lazyloaded in the minion logs? `LazyLoaded inotify.beacon`

**Comment by SecureshellV2** [comment]
I am not seeing the beacon being lazy loaded, I only see the pkgset beacon being loaded as far as beacons are concerned.

**Comment by SecureshellV2** [comment]
> @SecureshellV2: not sure if it's related or if it'll help, but there's an undocumented option "beacons_before_connect" that can result in inotify beacons not being validated which makes salt think that there's no inotify beacons defined. If it does help, then this issue might be related to #48698.
> 
> In some cases it can also hide logging errors w/ inotify which is why I mention it.

That does look somewhat similar, but I seem to be missing what I would want to change to test that out...

**Comment by arizvisa** [comment]
Sorry, try setting "beacons_before_connect" to `true` in your options.

**Comment by SecureshellV2** [comment]
OK, so now in the log I see the following with pyinotify installed via pip:

`2019-11-11 10:16:08,715 [salt.utils.lazy  :107 ][DEBUG   ][4573] Could not LazyLoad inotify.beacon: 'inotify' __virtual__ returned False
2019-11-11 10:16:08,716 [salt.beacons     :123 ][WARNING ][4573] Unable to process beacon inotify
`

Then, if I remove that and install python-inotify with yum (as is documented in the beacon documentation) I see this:

`2019-11-11 10:19:45,490 [salt.utils.lazy  :104 ][DEBUG   ][5372] LazyLoaded inotify.beacon
2019-11-11 10:19:45,504 [salt.minion      :725 ][DEBUG   ][5372] Connecting to master. Attempt 1 of 1
`

So it appears to be loading the beacon, but I still don't see anything with either debug or trace logging when I attempt to trigger the beacon.

**Comment by SecureshellV2** [comment]
@Ch3LL Is there any further testing that I can do, or any other information that you need? I would really like to get this working, as it is super important to keeping a few of our systems under proper control.

**Comment by arizvisa** [comment]
@SecureshellV2, when you test the beacon do you see the event fired on the event bus? It should be `salt/beacon/$id/`. I think you can use `state.event` to see those. If none of those are being fired then it's got to be something with the way inotify's watch is creating the events. If they are, then it's likely the way salt is processing them.

**Comment by SecureshellV2** [comment]
@arizvisa Yeah, I used salt-call --local state.event and I saw nothing happen when I tried to cause the beacon to fire. This is really confusing to me, I have tried to test using python with inotify on some of these boxes and it seemed to be working. I can try it out again, but there certainly seems to be a disconnect here.

**Comment by SecureshellV2** [comment]
Inotify does appear to be working fine, I am still at a loss as to why it is not firing the beacon. Maybe I am missing something?

**Comment by SecureshellV2** [comment]
Here is a pyinotify test that I ran that confirms that it is working without Salt:

`[~]# python -m pyinotify -v /test/
[2019-11-19 12:02:07,950 pyinotify DEBUG] Start monitoring ['/test/'], (press c^c to halt pyinotify)
[2019-11-19 12:02:07,951 pyinotify DEBUG] New <Watch wd=1 path=/test mask=4095 proc_fun=None auto_add=None exclude_filter=<function <lambda> at 0x7f09c88725f0> dir=True >
[2019-11-19 12:02:10,907 pyinotify DEBUG] Event queue size: 96
[2019-11-19 12:02:10,908 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x20 name=test.txt wd=1 >
[2019-11-19 12:02:10,908 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x2 name=test.txt wd=1 >
[2019-11-19 12:02:10,908 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x8 name=test.txt wd=1 >
<Event dir=False mask=0x20 maskname=IN_OPEN name=test.txt path=/test pathname=/test/test.txt wd=1 >
<Event dir=False mask=0x2 maskname=IN_MODIFY name=test.txt path=/test pathname=/test/test.txt wd=1 >
<Event dir=False mask=0x8 maskname=IN_CLOSE_WRITE name=test.txt path=/test pathname=/test/test.txt wd=1 >
[2019-11-19 12:02:10,909 pyinotify DEBUG] Event queue size: 96
[2019-11-19 12:02:10,909 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x20 name=test.txt wd=1 >
[2019-11-19 12:02:10,909 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x1 name=test.txt wd=1 >
[2019-11-19 12:02:10,909 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x10 name=test.txt wd=1 >
<Event dir=False mask=0x20 maskname=IN_OPEN name=test.txt path=/test pathname=/test/test.txt wd=1 >
<Event dir=False mask=0x1 maskname=IN_ACCESS name=test.txt path=/test pathname=/test/test.txt wd=1 >
<Event dir=False mask=0x10 maskname=IN_CLOSE_NOWRITE name=test.txt path=/test pathname=/test/test.txt wd=1 >
[2019-11-19 12:02:10,910 pyinotify DEBUG] Event queue size: 96
[2019-11-19 12:02:10,910 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x20 name=test.txt wd=1 >
[2019-11-19 12:02:10,910 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x1 name=test.txt wd=1 >
[2019-11-19 12:02:10,910 pyinotify DEBUG] <_RawEvent cookie=0 mask=0x10 name=test.txt wd=1 >
<Event dir=False mask=0x20 maskname=IN_OPEN name=test.txt path=/test pathname=/test/test.txt wd=1 >
<Event dir=False mask=0x1 maskname=IN_ACCESS name=test.txt path=/test pathname=/test/test.txt wd=1 >
<Event dir=False mask=0x10 maskname=IN_CLOSE_NOWRITE name=test.txt path=/test pathname=/test/test.txt wd=1 >
`

**Comment by UtahDave** [comment]
@SecureshellV2 I successfully used the inotify beacon on centos 7 in my salt class at saltconf this week. I'll share my working configs when I get into the office tomorrow

**Comment by SecureshellV2** [comment]
@UtahDave I appreciate the assistance, and any information should be helpful. I do feel like it is worth noting that I have this configuration working on Suse boxes, but not on CentOS 7 or 8. I see a beacon that is stored in a pillar, that is for Suse Manager and I am wondering if there is something with that causing a blocker... Other than that I am at a total loss. If there is some place I can look for some breadcrumbs to find my way to a solution, then I would love to know it. I am trying debug and trace logging, but that does not seem to be showing me anything out of the ordinary.

**Comment by UtahDave** [comment]
Here are my working configs:

On my minion:
```
[root@inotify-minion ~]# cat /etc/salt/minion.d/beacons.conf
beacons:
  inotify:
    - files:
        /var/www/html/index.html:
          mask:
            - close_write
```

When I modify my `/var/www/html/index.html` I see this show up in the output of state.event on my salt master

```
[root@inotify webserver]# salt-run state.event pretty=True
salt/beacon/minion01/inotify//var/www/html/index.html   {
    "_stamp": "2019-11-20T21:42:30.041231",
    "change": "IN_IGNORED",
    "id": "minion01",
    "path": "/var/www/html/index.html"
}
```

Here is my reactor config on my Salt Master:

```
[root@inotify ~]# cat /etc/salt/master.d/reactors.conf
reactor:
  - 'salt/beacon/minion01/inotify//var/www/html/index.html':
    - /srv/reactor/web.sls
```

And then here's my reactor:

```
[root@inotify ~]# cat /srv/reactor/web.sls
update_webserver:
  local.state.apply:
    - tgt: 'minion01'
    - args:
      - mods: webserver
```

For completeness, here's my `webserver` state file:

```
[root@inotify ~]# cat /srv/salt/webserver/init.sls
web_server:
  pkg.installed:
    - name: httpd

  service.running:
    - name: httpd
    - enable: True
    - watch:
      - pkg: web_server
      - file: new_web_page

new_web_page:
  file.managed:
    - name: /var/www/html/index.html
    - source: salt://webserver/index.html
    - template: jinja
```

And my html file:

```
[root@inotify ~]# cat /srv/salt/webserver/index.html
<html>
    <head>
        <title>Test web server</title>
    <head>
<body>
    <h1>Welcome to Salt!</h1>
<br />
</body>
</html>
```

here's my versions of my minion. The master is identical:

```
[root@inotify ~]# salt 'minion01' test.versions
minion01:
    Salt Version:
               Salt: 2019.2.2

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.7.1908 Core
             locale: ascii
            machine: x86_64
            release: 4.15.0-70-generic
             system: Linux
            version: CentOS Linux 7.7.1908 Core
```

**Comment by SecureshellV2** [comment]
Here is my beacon config, this looks similar to yours and appears to get loaded.

`# cat /etc/salt/minion.d/beacons.conf 
beacons:
  inotify:
    - files:
        /test:
          mask:
            - create
            - modify
            - attrib
          recurse: True
          auto_add: True
`

When I try to look at it from the master side I get too much output to really see anything. So I try piping to grep and I just see nothing coming from the minion. That being said, on the minion side, I really do not see anything in trace or debug output. I also run `salt-call state.event pretty=True
` and that shows the following only:
`[TRACE   ] _get_event() waited 5 seconds and received nothing
[TRACE   ] Get event. tag: 
[TRACE   ] _get_event() waited 5 seconds and received nothing
[TRACE   ] Get event. tag: `

Not sure what I am missing, I swear this same config works on OpenSuse, but not at all on CentOS.

**Comment by SecureshellV2** [comment]
@UtahDave I copied and pasted your beacon configuration onto one of my systems and tested it by opening the index.html, making a change, and doing a save and close in vi. The beacon did not seem to fire. The following is still all that I see.

```[TRACE   ] _get_event() waited 5 seconds and received nothing
[TRACE   ] Get event. tag: 
[TRACE   ] _get_event() waited 5 seconds and received nothing
[TRACE   ] Get event. tag: 
[TRACE   ] _get_event() waited 5 seconds and received nothing
[TRACE   ] Get event. tag: 
[TRACE   ] _get_event() waited 5 seconds and received nothing
[TRACE   ] Get event. tag: 
[TRACE   ] _get_event() waited 5 seconds and received nothing
[TRACE   ] Get event. tag: 
[TRACE   ] _get_event() waited 5 seconds and received nothing
[TRACE   ] Get event. tag: 
[TRACE   ] _get_event() waited 5 seconds and received nothing
[TRACE   ] Get event. tag: 
[TRACE   ] _get_event() waited 5 seconds and received nothing
[TRACE   ] Get event. tag: 
[TRACE   ] _get_event() waited 5 seconds and received nothing
[TRACE   ] Get event. tag: 
```

**Comment by Ch3LL** [comment]
can you also verify you are not seeing events on the master with: `sudo salt-run state.event pretty=True` ?

**Comment by Destrocamil** [comment]
Hello all,
I am facing the exact same issue as OP.
My master details
`
    Salt Version:
               Salt: 2019.2.2
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: 18.4.0
           dateutil: 2.7.3
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.11
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: 1.4.5
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
       python-gnupg: Not Installed
             PyYAML: 3.13
              PyZMQ: 18.1.0
               RAET: Not Installed
              smmap: 2.0.5
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.3.2
     
    System Versions:
               dist: debian 10.1 
             locale: utf-8
            machine: x86_64
            release: 4.19.0-6-amd64
             system: Linux
            version: debian 10.1 
`
My minion details : 
`Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
          docker-py: Not Installed
              gitdb: 0.6.4
          gitpython: 1.0.1
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.2 (default, Oct  8 2019, 13:06:37)
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist: Ubuntu 16.04 xenial
             locale: UTF-8
            machine: x86_64
            release: 4.15.0-45-generic
             system: Linux
            version: Ubuntu 16.04 xenial `

If i run the inotify on my minion it works like a charm.
Beacons are LazyLoaded but just right after that a "[WARNING ] Unable to process beacon inotify" appears.
I do not see any event while running the salt runner state.event when making changes to the "notified" file.

Anything i can do to help? More info? Need to move further but this beacons things is really the thing i need.
Thanks!

**Comment by SecureshellV2** [comment]
I can confirm that I am not seeing inotify hitting the master at all.

**Comment by Ch3LL** [comment]
thanks for confirming @SecureshellV2 

looking at teh code when this error `Unable to process beacon inotify` pops up it means it cannot find that beacon function in the loader, so im guessing something is wrong with the pyinotify library. what happens when you run this on the minion with inotify installed:

```
python3 -c "import pyinotify; DEFAULT_MASK = pyinotify.IN_CREATE | pyinotify.IN_DELETE | pyinotify.IN_MODIFY"
```


im still not able to replicate this with this config:

```
beacons:
  inotify:
    - files:
        /test/test.txt:
          mask:
            - open
            - create
            - close_write
```

Can anyone test with this config?

**Comment by Destrocamil** [comment]
I did test with that line. The result is :
[ /srv/salt ]
```
 $ python3 -c "import pyinotify; DEFAULT_MASK = pyinotify.IN_CREATE | pyinotify.IN_DELETE | pyinotify.IN_MODIFY"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'pyinotify'
```
Very strange since i was able to watch for file changes with inotify (beaconless).
Did not use that beacon config since i have one pretty similar

**Comment by Destrocamil** [comment]
Ok, so i have been trying lately to make this work. Done so many things that i became so frustrated untill tried this so simple state:
```

install_python:
  pkg.installed:
    - name: python3-pip
    - reload_modules: True

install_inotify:
  pip.installed:
    - name: pyinotify
    - bin_env: /usr/bin/python3.5
```
And guess what? It worked!
I had pip, pyinotify, python-inotify(...) everything installed! And it did not work. As a guess, i think this is all related to the env being used.
Using this state got it working.
@SecureshellV2 can u test this?
