### ISSUE TITLE
pip.installed comments misleading in test mode 

### ISSUE THREAD

**Issue by deborahcai** [saltstack/salt#55251]
### Description of Issue

```
# Install pip modules
deployment_pip_packages_installed:
  pip.installed:
    - pkgs:
      - ansible==2.4.2.0
      - awsebcli
      - boto
      - boto3>=1.4.4
      - jinja2>=2.9.6
      - pyjks>=17.0.0
      - pytz
      - setuptools>=38.4.0
    - proxy: http://proxy:1234
    - require:
      - sls: pip
```

### Steps to Reproduce Issue

1. put the state to a test.sls, and run state.apply in test mode
2. the comments only hint the first pkg name is set to be installed rather than a list of pkgs

----------
          ID: deployment_pip_packages_installed
    Function: pip.installed
      Result: None
     Comment: Python package **ansible==2.4.2.0** is set to be installed
     Started: 09:33:22.538788
    Duration: 364.287 ms
     Changes:
----------
### Versions Report
```
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 4.9.34-29.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
