### ISSUE TITLE
salt-cloud - Only 2 out of many ec2 providers are queried with -Q

### ISSUE THREAD

**Issue by nnsense** [saltstack/salt#55311]
### Description of Issue
I've just started with salt-cloud. I've created a single file with a number of providers (we use subaccounts, every provider is an account, all the account have a role allowing admin privileges to the instance).  `salt-cloud --list-providers` is correctly reporting all the providers. When I try `salt-cloud -Q` only instances from 2 providers, apparently picked randomly among providers, are shown.
I've tried `-l debug` and only 2 (sometimes even 1) endpoints are queried. Interestingly, if I remove one of the provider successfully queried from my list in `/etc/salt/cloud.providers.d`, another provider takes its place and still just 2 (or 1) providers are queried. 

I've tried:
- Splitting the single provider's file into many single files,
- Removing one provider at a time to check if one was causing the issue
- Removing all the profiles (2 very basic profiles, no map files yet)
- Using proper credentials instead of 'use-instance-role-credentials' 

I've found this out because I was trying to delete an instance created with salt-cloud but salt couldn't find it, and it did when I've left only that provider in `/etc/salt/cloud.providers.d/aws.conf `.

### Setup
OS: `CentOS Linux release 7.7.1908 (Core)`
salt-cloud version: `salt-cloud 2019.2.2 (Fluorine)`

Providers in `/etc/salt/cloud.providers.d/aws.conf `:
```
pr1:
  driver: ec2
  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'
  role_arn: arn:aws:iam::3262362363262:role/OrganizationAccountAccessRole
  private_key: /root/.ssh/id_rsa
  keyname: administrator
  ssh_username: root
  location: eu-west-1
  minion:
    master: saltsrv.wallawalla.net

pr2:
  driver: ec2
  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'
  role_arn: arn:aws:iam::552352352353:role/OrganizationAccountAccessRole
  private_key: /root/.ssh/id_rsa
  keyname: administrator
  location: us-east-1
  minion:
    master: saltsrv.wallawalla.net

pr3:
  driver: ec2
  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'
  role_arn: arn:aws:iam::124241241242:role/OrganizationAccountAccessRole
  private_key: /root/.ssh/id_rsa
  keyname: administrator
  ssh_username: root
  location: eu-west-1
  minion:
    master: saltsrv.wallawalla.net

pr4:
  driver: ec2
  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'
  role_arn: arn:aws:iam::1241244124212:role/OrganizationAccountAccessRole
  private_key: /root/.ssh/id_rsa
  keyname: administrator
  ssh_username: root
  location: eu-west-1
  minion:
    master: saltsrv.wallawalla.net

pr5:
  driver: ec2
  location: eu-west-1
  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'
  role_arn: arn:aws:iam::31233123442:role/OrganizationAccountAccessRole
  private_key: /root/.ssh/id_rsa
  keyname: administrator
  ssh_username: root
  minion:
    master: saltsrv.wallawalla.net
```

### Steps to Reproduce Issue
`salt-cloud --list-providers`  to check the providers and
 `salt-cloud -Q` to query all the instances. Expected behaviour is to see all instances from all providers listed. Instead, I get only instances from 2 providers.

### Versions Report
```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```
