### ISSUE TITLE
boto_ec2 documentation and bugs while creating a new instance on AWS

### ISSUE THREAD

**Issue by nnsense** [saltstack/salt#55339]
I wanted to use boto to create a state ensuring an instance was present and I've faced many issues. It wasn't working and I've found in the code that the state was eventually running the module `.run`. I've tried isolating the issue by running the `boto_ec2` from the command line a number of times facing a number of issues as a consequence of the very limited example into the docs:
```
salt myminion boto_ec2.run ami-b80c2b87 name=myinstance
```
The above is lacking of some important arguments I think. We're often not using a default VPC, subnets or security groups. It is definitely missing the type, the key, etc.

Using the private_ip_address option, I've got this back from AWS
```
Network interfaces and an instance-level private IP address may not be specified on the same request
```

Using the security_group_names or security_group_ids options I've got errors due to the lack of passing an array as argument. Since I was passing a single string, python taken the first letter of the security group.
```
<Code>InvalidGroup.NotFound</Code><Message>The security group 'b' does not exist in VPC 'vpc-12345678912345'</Message>
```

I've realized a list of strings was needed. It's quite unusual to require an array into a command line if the security group is just one. Eventually, the following worked:
```
salt myminion boto_ec2.run name=myinstance vpc_id='vpc-12345678912345' image_id='ami-0d0054dd204657e88' key_name='cloudadmin' security_group_names='[default]' subnet_id='subnet-0dd6e907dd9def5a0' instance_type='m5.2xlarge'
```

The last error I've faced has been the instanceType attribute. I've overlooked that the type was also an option, and I've kept using the attribute until I've read the docs again.

Eventually this worked:
```
Ensure myinstance exists:
    boto_ec2.instance_present:
        - name: myinstance
        - instance_name: myinstance 
        - vpc_id: vpc-12345678912345
        - image_id: ami-0d0054dd204657e88
        - key_name: administrator
        - security_group_ids:
            [sg-05d91b41396193ff4]
        - instance_type: m5.2xlarge
        - subnet_id: subnet-0dd6e907dd9def5a0
```

I would advise to update the documentation with a proper example showing more options and how to use them. I'm happy to do it if you can show me how can I change it myself.
