### ISSUE TITLE
user.present SOMETIMES fails to create a password when hash_password is used

### ISSUE THREAD

**Issue by iahim** [saltstack/salt#55478]
### Description of Issue

I create multiple users with salt **user.present** state. The password (plain text) comes from a pillar variable and in the state i use **hash_password** to create the correct hash (which is added to /etc/shadow). My salt-master is ubuntu 18 and the minions are RHEL8. On both i have version 2019.2.2 running. On salt-master i have python2 but on the minions i have python3 - not sure if it matters or not. 
**The problem is that sometimes the user.present state fails to create the password hash for the user. From 12 tests usually 1-3 users have no pass.**

### Setup
I have one test state that adds users to a linux vm: 

```
create_app_folder:
  file.directory:
    - name: /app
    - user: root
    - group: root
    - dir_mode: 755
    - makedirs: True

{% for usr in ['moe','larry','curly', 'moe1','larry1','curly1', 'moe2','larry2','curly2', 'moe3','larry3','curly3', 'moe4','larry4','curly4'] %}

add_user_{{usr}}:
  user.present:
    - name: {{ usr }}
    - shell: /bin/bash
    - home: /app/{{ usr }}
    - createhome: True
    - password: blabla
    - hash_password: True
    - groups:
      - users

{% endfor %}
```

### Steps to Reproduce Issue
My minions are in AWS EC2 - they are all RHEL8 vms:
```
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
```
**After running the state, the output for a CORRECT user is:**

```
----------
          ID: add_user_curly
    Function: user.present
        Name: curly
      Result: True
     Comment: New user curly created
     Started: 01:19:38.327978
    Duration: 642.509 ms
     Changes:
              ----------
              fullname:
              gid:
                  1004
              groups:
                  - curly
                  - users
              home:
                  /app/curly
              homephone:
              name:
                  curly
              other:
              passwd:
                  x
              password:                 <========== this field is missing when the state fails
                  XXX-REDACTED-XXX
              roomnumber:
              shell:
                  /bin/bash
              uid:
                  1004
              workphone:
```

**An user that fails has the following output (please note the missing password field in the output, compared to the above/correct one)**
```

----------
          ID: add_user_larry
    Function: user.present
        Name: larry
      Result: True
     Comment: New user larry created
     Started: 01:19:37.695247
    Duration: 632.48 ms
     Changes:
              ----------
              fullname:
              gid:
                  1003
              groups:
                  - larry
                  - users
              home:
                  /app/larry
              homephone:
              name:
                  larry
              other:
              passwd:            <========== WE do not have here a password field !
                  x
              roomnumber:
              shell:
                  /bin/bash
              uid:
                  1003
              workphone:
```

**Of course in the /etc/shadow there is no hash for the failed user:**
```
moe:$6$N6FoaKyg$PB3KypR0MnGrR2q8rO0Q2CDdzhl/tI00pmUKQeZK/E4zha5WIiu0.Ev3puCuAg5la/5jRJj3UrL5Ov3rMdQS70:18229:0:99999:7:::
larry:!!:18229:0:99999:7:::         <============ ERROR
curly:$6$JbX9qFYU$/vkMMUL1k/VYU5Uh1aub6uWBMY/TB/hq9BAsDiAYBr30ixaMZFqlFkJs8cj/
```

### Versions Report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.15+ (default, Oct  7 2019, 17:39:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-70-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by iahim** [comment]
As a workaround for this issue i am using:

```
{% set pass_hash = salt['cmd.run']("openssl passwd -1 " + clear_text_pass ) %}

add_user_{{usr}}:
  user.present:
    - name: {{ usr }}
    - shell: /bin/bash
    - home: /app/{{ usr }}
    - createhome: True
    - password: {{ pass_hash }}
    - groups:
      - users
```
