### ISSUE TITLE
pip module fails to find pip when bin_env is specified

### ISSUE THREAD

**Issue by haodeon** [saltstack/salt#55507]
### Description of Issue
Since pymssql is no longer included in the windows pkg (Refer #55484) I am writing a state to install pymssql on my Windows minion.

The documentation inside pip.py recommends including "cwd" and "bin_env" options when modifying the salt environment.

When I include these options, I get error

_Could not find a \`pip\` binary_

When I run `salt-call --local -l debug pip.list cwd='C:\salt\bin\Scripts' bin_env='C:\salt\bin\Scripts\pip.exe'` on the minion I get

_Command '['C:\\salt\\bin\\Scripts\\pip.exe', '--version']' failed with return code: 1_

I then troubleshooted further and try to run pip.exe or pip3.exe (no options) from the command line I get error

_Fatal error in launcher: Unable to create process using '"'_

Despite the error, I could upgrade pip. After upgrading everything started working, salt-call and the state file.

### Setup
State file to install pymssql
```
salt_pymssql:
  pip.installed:
    - name: pymssql < 3.0
    - cwd: 'C:\salt\bin\Scripts'
    - bin_env: 'C:\salt\bin\Scripts\pip.exe'
```

### Steps to Reproduce Issue

```
PS C:\salt> .\salt-call.bat --local -l debug pip.list cwd='C:\salt\bin\Scripts' bin_env='C:\salt\bin\Scripts\pip.exe'
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Loading static grains from c:\salt\conf\grains
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pip.list
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command ['C:\\salt\\bin\\Scripts\\pip.exe', '--version'] in directory 'C:\Users\xxxxxxxxx'
[ERROR   ] Command '['C:\\salt\\bin\\Scripts\\pip.exe', '--version']' failed with return code: 1
[ERROR   ] retcode: 1
Command required for 'pip.list' not found: Could not find a `pip` binary
```

```
PS C:\Users\xxxxxxxxx> C:\salt\bin\Scripts\pip3.exe
Fatal error in launcher: Unable to create process using '"'
```

```
PS C:\salt\bin\Scripts> .\pip3.exe install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
    100% |################################| 1.4MB 728kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
```

```
PS C:\salt> .\salt-call.bat --local -l debug pip.list bin_env='C:\salt\bin\Scripts\pip.exe' cwd='C:\salt\bin\Scripts'
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Loading static grains from c:\salt\conf\grains
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pip.list
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command ['C:\\salt\\bin\\Scripts\\pip.exe', '--version'] in directory 'C:\Users\xxxxxxxx'
[DEBUG   ] stdout: pip 19.3.1 from c:\salt\bin\lib\site-packages\pip (python 3.5)
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] key: cmd_blacklist_glob, ret: _|-
[DEBUG   ] key: cmd_whitelist_glob, ret: _|-
[INFO    ] Executing command ['C:\\salt\\bin\\Scripts\\pip.exe', 'freeze', '--all'] in directory 'C:\salt\bin\Scripts'
[DEBUG   ] stdout: argh==0.26.2
asn1crypto==1.1.0
backports-abc==0.5
backports.ssl-match-hostname==3.7.0.1
certifi==2019.9.11
cffi==1.12.2
chardet==3.0.4
cheroot==8.2.0
CherryPy==17.4.1
contextlib2==0.6.0.post1
cryptography==2.6.1
enum34==1.1.6
gitdb==0.6.4
gitdb2==2.0.6
GitPython==2.1.10
idna==2.8
ioloop==0.1a0
ipaddress==1.0.22
jaraco.functools==2.0
Jinja2==2.10.1
libnacl==1.6.1
lxml==4.3.0
Mako==1.0.7
MarkupSafe==1.1.1
more-itertools==7.2.0
msgpack-python==0.5.6
pathtools==0.1.2
pip==19.3.1
portend==2.5
psutil==5.6.1
pyasn1==0.4.5
pycparser==2.19
pycryptodomex==3.8.1
pycurl==7.43.0.2
pymssql==2.1.4
PyMySQL==0.9.3
pyOpenSSL==19.0.0
python-dateutil==2.8.0
python-gnupg==0.4.4
pythonnet==2.3.0
pytz==2019.3
pywin32==224
PyYAML==3.13
pyzmq==18.0.1
requests==2.21.0
salt==2019.2.2
setproctitle==1.1.10
setuptools==38.2.4
singledispatch==3.4.0.3
six==1.12.0
smmap==0.9.0
smmap2==2.0.5
tempora==1.14.1
timelib==0.2.4
tornado==4.5.3
urllib3==1.24.3
watchdog==0.9.0
wheel==0.33.4
WMI==1.4.9
zc.lockfile==2.0
[DEBUG   ] LazyLoaded nested.output
local:
    ----------
    CherryPy:
        17.4.1
    GitPython:
        2.1.10
    Jinja2:
        2.10.1
    Mako:
        1.0.7
    MarkupSafe:
        1.1.1
    PyMySQL:
        0.9.3
    PyYAML:
        3.13
    WMI:
        1.4.9
    argh:
        0.26.2
    asn1crypto:
        1.1.0
    backports-abc:
        0.5
    backports.ssl-match-hostname:
        3.7.0.1
    certifi:
        2019.9.11
    cffi:
        1.12.2
    chardet:
        3.0.4
    cheroot:
        8.2.0
    contextlib2:
        0.6.0.post1
    cryptography:
        2.6.1
    enum34:
        1.1.6
    gitdb:
        0.6.4
    gitdb2:
        2.0.6
    idna:
        2.8
    ioloop:
        0.1a0
    ipaddress:
        1.0.22
    jaraco.functools:
        2.0
    libnacl:
        1.6.1
    lxml:
        4.3.0
    more-itertools:
        7.2.0
    msgpack-python:
        0.5.6
    pathtools:
        0.1.2
    pip:
        19.3.1
    portend:
        2.5
    psutil:
        5.6.1
    pyOpenSSL:
        19.0.0
    pyasn1:
        0.4.5
    pycparser:
        2.19
    pycryptodomex:
        3.8.1
    pycurl:
        7.43.0.2
    pymssql:
        2.1.4
    python-dateutil:
        2.8.0
    python-gnupg:
        0.4.4
    pythonnet:
        2.3.0
    pytz:
        2019.3
    pywin32:
        224
    pyzmq:
        18.0.1
    requests:
        2.21.0
    salt:
        2019.2.2
    setproctitle:
        1.1.10
    setuptools:
        38.2.4
    singledispatch:
        3.4.0.3
    six:
        1.12.0
    smmap:
        0.9.0
    smmap2:
        2.0.5
    tempora:
        1.14.1
    timelib:
        0.2.4
    tornado:
        4.5.3
    urllib3:
        1.24.3
    watchdog:
        0.9.0
    wheel:
        0.33.4
    zc.lockfile:
        2.0
PS C:\salt>
```
### Versions Report
```
PS C:\salt> .\salt-call.bat --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2019Server
         system: Windows
        version: 2019Server 10.0.17763 SP0 Multiprocessor Free
```

**Comment by haodeon** [comment]
I provisioned an entirely new Windows minion.

Using module cmd.run I upgraded pip `sudo salt 'xxxxxxx' cmd.run 'C:\salt\bin\python.exe -m pip install --upgrade pip'`

I then applied the pip.installed state file successfully and pymssql was installed into the salt environment.

**Comment by cmcmarrow** [comment]
https://github.com/saltstack/salt/issues/55484

**Comment by cmcmarrow** [comment]
We are planning to add back pymssql

**Comment by haodeon** [comment]
Even if pymssql is addded back to reqs.txt this issue would still persist whenever someone wanted to add python module to the salt python environment on windows.

**Comment by cmcmarrow** [comment]
@haodeon was just letting you know about `pymssql` I'll start working on a fix

**Comment by cmcmarrow** [comment]
@haodeon I fixed the bug. Just need to write test and get it merged.

**Comment by cmcmarrow** [comment]
I also made this work as well

```
salt_pymssql:
  pip.installed:
    - name: pymssql < 3.0
    - bin_env: 'C:\salt\bin\Scripts\pip.exe'
```
