### ISSUE TITLE
pip system package must be installed for name or pkgs, but not requirements when using bin_env

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#55554]
### Description of Issue
I found rather odd inconsistent behavior and probably some buggy code.  It seems that when using pip.installed, if you give it a requirements file and use bin_env, it doesn't matter that the system has pip installed (apt install python3-pip) when installing in python packages a pyenv.  If you specify pkgs or name, does a bunch of checks on the system pip and then installs using pip from the virtualenv.  If we are doing checks on pip, we should probably do those checks on the same version of pip that we are installing with or else skip them if we are using bin_env.

### Setup
this fails with an error message (note that no system pip is installed, only in the pyenv): `An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.`

```yaml
virtualenv-3.6.8:
  pip.installed:
    - user: svc-user
    - pkgs:
      - virtualenv
    - bin_env: /var/jenkins/.pyenv/versions/3.6.8/bin/pip
```
```yaml
virtualenv-3.6.8:
  pip.installed:
    - user: svc-user
    - name: virtualenv
    - bin_env: /var/jenkins/.pyenv/versions/3.6.8/bin/pip
```
this succeeds with no system pip installed:
```yaml
golden_image_pyenv-deps-3.6.8:
  pip.installed:
    - requirements: https://raw.githubusercontent.com/saltstack/os-imager/ci/requirements/py3.6/base.txt
    - bin_env: /var/jenkins/.pyenv/versions/3.6.8/bin/pip
    - require:
      - python-3.6.8
```

installed via bootstrap script on ubuntu 18.04 using the bootstrap script with `'/tmp/install_salt.sh -qdXU -x python3 stable 2019.2.2'` as args
