### ISSUE TITLE
salt.states.service - Ability To Use Any Option

### ISSUE THREAD

**Issue by knine** [saltstack/salt#5556]
I was talking with thatch45 about adding the ability to do a graceful (not reload) with Apache.  So say:

```
httpd:
  service:
    - running
    - enable: True
    - graceful: True
```

And then it occurred to me, why not in general have the ability for changes to trigger any available option, say for example RHEL 6 SysV httpd service:

Usage: httpd {start|stop|restart|condrestart|try-restart|force-reload|reload|status|fullstatus|graceful|help|configtest}

Thanks,
- knine
