### ISSUE TITLE
Basic beacons.present state is not working

### ISSUE THREAD

**Issue by evenyougreg** [saltstack/salt#55591]
### Description of Issue

Trying to set up just a basic service beacon for a Windows application called Log Insight. I just need the service beacon to be running and enabled, but following the Salt docs exactly is giving me only errors.

I also need to add onchangeonly: True but the documentation doesn't say how to properly include it.

The service is called LogInsightAgentService.

### Setup

/etc/salt/master.d/reactor.conf

```
reactor:
  - 'salt/beacon/*/service/*':
    - /srv/reactor/ez_service_reactor.sls
```

/srv/reactor/ez_service_reactor.sls

```
{% if data[data['service_name']]['running'] == False %}
start_{{data['service_name']}}:
  local.service.start:
  - tgt: {{data['id']}}
  - args:
    - name: {{data['service_name']}}
{% endif %}
```

/srv/salt/loginsight/beacons.sls

```
log_insight_test:
  beacon.present:
    - save: True
    - enable: True
    - services:
        LogInsightAgentService: running
```

### Steps to Reproduce Issue

master debug

```
[DEBUG   ] return event: {u'mvs-minion': {u'jid': u'20191210105640641232', u'retcode': 2, u'ret': {u'beacon_|-log_insight_test_|-log_insight_test_|-present': {u'comment': u'Beacon "log_insight_test" is not available.', u'name': u'log_insight_test', u'start_time': u'10:56:50.595607', u'result': False, u'duration': 93.74, u'__run_num__': 0, u'__sls__': u'loginsight.beacons', u'changes': {}, u'__id__': u'log_insight_test'}}, u'out': u'highstate'}}
[DEBUG   ] LazyLoaded highstate.output
mvs-minion:
----------
          ID: log_insight_test
    Function: beacon.present
      Result: False
     Comment: Beacon "log_insight_test" is not available.
     Started: 10:56:50.595607
    Duration: 93.74 ms
     Changes:

Summary for mvs-minion
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  93.740 ms
```

### Versions Report

salt-master

```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jun 11 2019, 14:33:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.7 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.7 Maipo
```

salt-minion

```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free

```

**Comment by garethgreenaway** [comment]
@evenyougreg Thanks for the report.  Currently in the beacon module and state module you need to specify the name of the beacon in question, in this case the `service` beacon.  You can also include additional arguments for the beacon, such as `onchangeonly` as additional arguments in the state file.  For example, an updated version of your state file from above:
```
service:
  beacon.present:
    - save: True
    - enable: True
    - services:
        LogInsightAgentService: running
    - onchangeonly: True
```

**Comment by evenyougreg** [comment]
Using that code I am now getting:

```
minion:
----------
          ID: service
    Function: beacon.present
      Result: False
     Comment: Beacon service configuration invalid, not adding.
              Configuration for service beacon must be a list of dictionaries.
     Started: 10:33:15.339996
    Duration: 75.856 ms
     Changes:

Summary for minion
```

**Comment by evenyougreg** [comment]
Any further help on this would be great, I'm still stuck.

**Comment by garethgreenaway** [comment]
@evenyougreg Apologies for the delay in responding.   Looks like I might have combined the configuration the ps beacon and the service beacon, the below configuration for the service beacon will work:
```
service:
  beacon.present:
    - save: True
    - enable: True
    - services:
        LogInsightAgentService:
          onchangeonly: True
```
