### ISSUE TITLE
file.file_exists & file.directory_exists won't work

### ISSUE THREAD

**Issue by Cybergenik** [saltstack/salt#55627]
This software called PrinterAgent is installed on a windows minion, all I want to do is add a flag file or directory to the newest version that we roll out and then just if it doesn't exists then it should simply follow through with the install.

State:
(I tried this state on 5 different windows minions, it always seems to not return what I want it to.
Also I tried the same thing with file.file_exists and added the file in the directory and its the same issue.) 
```
{% if not salt['file.directory_exists']('C:\BCFranchise\PrinterAgent\v1.0.0.10') %}
#Check for backed up JPOS
backup-jpos:
  file.copy:
    - name: c:\Confidential\PrinterAgentBackup\jpos.xml
    - source: c:\Confidential\PrinterAgent\jpos.xml
    - force: True
    - makedirs: True
    - skip_verify: True
    - state_output: mixed

delete-printer-agent-directory:
  cmd.run:
    - name: rm -r c:\Confidential\PrinterAgent -Force
    - shell: powershell
    - state_output: mixed

# Install PrinterAgent 
copy_printer_agent_directory:
  file.recurse:
    - name: c:\Confidential\PrinterAgent
    - source: salt://files/printeragent/{{ pillar['printeragent-versions'] }}/PrinterAgent/
    - makedirs: True
    - state_output: mixed
# Restores JPOS
restore-jpos:
  file.copy:
    - name: c:\Confidential\PrinterAgent\jpos.xml
    - source: c:\Confidential\PrinterAgentBackup\jpos.xml
    - force: True
    - skip_verify: True

{% endif %} 
```
Also Yes, I made sure that the path name is correct and the directory/file name, also its good to note that if I run the command from the command line it returns correctly, its only when I put it into a state file within a Jinja template that it errors out.
