### ISSUE TITLE
state pkg.installed not working when version is specified

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#55630]
I have the following state file.
```
mariadb_pkg:
  pkg.installed:
    - name: mariadb103-server
    - version: {{ salt['pillar.get']('mariadb:version', default_db_version) }}
```
It worked fine for two year until I recently upgraded salt to 2019.2.2

When I run it in debug mode, I got the following message:
```
16:02:31,455 [DEBUG   ] Current version ({'origin': 'databases/mariadb103-server', 'version': ['10.3.20']}) did not match desired version specification (10.3.20), adding to installation targets
```
It seems that salt was trying to compare a `dict` with `str` and decided that it didn't match.

### Versions Report

```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.4.2.post1
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov 12 2019, 23:28:35)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 12.1-RELEASE
         system: FreeBSD
        version: Not Installed
```
