### ISSUE TITLE
When targeting 100s of minions, some do not return.

### ISSUE THREAD

**Issue by sindhukothe** [saltstack/salt#55652]
### Description of Issue
When I target 100s of minions for any command, some minions take a bit longer to respond. Meanwhile master returns error for some of the minions without waiting them to be completed.
```
<minon_id>
Minion did not return. [Not connected]
--
```
### Reproduction and Logs:
For example, 
```
salt '<minion_id>' test.sleep 120 -l debug
```
always returning the above error.

Master sends the command to the minion. 
```
{"@timestamp":"2019-12-16T06:15:31", "message":"get_iter_returns for jid 20191216061530532724 sent to set(['<minion_id>']) will timeout at 06:15:36.476641", "lvl":"DEBUG", "op":"Process:MainProcess PyModule:salt.client line:1100", "pid":"25086", "severity_label": "DEBUG" , "severity": "10"}
```
Minion receives the command:
```
salt/job/20191216061530532724/new
{
    "_stamp": "2019-12-16T06:15:30.049766",
    "arg": [
        120
    ],
    "fun": "test.sleep",
    "jid": "20191216061530532724",
    "minions": [
        "<minon_id>"
    ],
    "missing": [],
    "tgt": "",
    "tgt_type": "glob",
    "user": "salt"
}
```
Master waits for about 5 seconds for minion to return. If it does not return, then it checks if the minion is still running the job:
```
{"@timestamp":"2019-12-16T06:15:36", "message":"Checking whether jid 20191216061530532724 is still running", "lvl":"DEBUG", "op":"Process:MainProcess PyModule:salt.client line:236", "pid":"25086", "severity_label": "DEBUG", "severity": "10"}
```
```
salt/job/20191216061536103764/new       {
    "_stamp": "2019-12-16T06:15:36.589880",
    "arg": [
        "20191216061530532724"
    ],
    "fun": "saltutil.find_job",
    "jid": "20191216061536103764",
    "minions": [
        "<minion_id>"
    ],
    "missing": [],
    "tgt": [
        "<minion_id>"
    ],
    "tgt_type": "list",
    "user": "salt"
}
```
Here, the minion always returns empty object even though the job is still running.
```
salt/job/20191216061536103764/ret/<minion_id>     {
    "_stamp": "2019-12-16T06:15:36.859919",
    "cmd": "_return",
    "fun": "saltutil.find_job",
    "fun_args": [
        "20191216061530532724"
    ],
    "id": "<minion_id>",
    "jid": "20191216061536103764",
    "retcode": 0,
    "return": {},
    "success": true
}
```
Eventually master thinks there the minion is not running the job and returns error.
```
{"@timestamp":"2019-12-16T06:16:06", "message":"return event: {'<minion_id>': {u'failed': True}}", "lvl":"DEBUG", "op":"Process:MainProcess PyModule:salt.client line:1531", "pid":"25086", "severity_label": "DEBUG", "severity": "10"}
```

### Versions Report
```
bash-4.4$ salt --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 2.7.16 (default, May  6 2019, 19:35:26)
   python-gnupg: 0.4.2
         PyYAML: 5.1.1
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: Not Installed

```
