### ISSUE TITLE
`saltutil.refresh_grains` not working unless cache is cleared

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#55667]
I have `grains_cache: True` in minion config.
If I run `saltutil.refresh_grains`, it doesn't do anything.
But if I clear the cache by running `saltutil.clear_cache` and then `grains.get` will return the updated grains.

I believe this is a bug, otherwise it's very confusing. 
By default `grains_cache` is set to `False` and in this case, the grains get refreshed every time you run `salt` cmd; if set to `True`, then there's no way to refresh the grains until the cache expires. Then what's `saltutil.refresh_grains` for?

`saltutil.refresh_grains` should be able to refresh grains regardless whether `grains_cache` is enabled or not.

I think this issue is also related to #54331

### Versions Report

```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.4.2.post1
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Dec  8 2019, 23:44:59)
   python-gnupg: Not Installed
         PyYAML: 5.2
          PyZMQ: 18.1.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 12.1-RELEASE-p1
         system: FreeBSD
        version: Not Installed
```
