### ISSUE TITLE
pkg.uptodate updates all packages when none specified

### ISSUE THREAD

**Issue by nachness** [saltstack/salt#55670]
### Description of Issue
Creating a salt `pkg.uptodate` task with only `refresh=True` ends up upgrading the host packages. According to the documentation - pkgs is a list of packages to update. Since I only want to generate a new sources.list and do an `apt update` -> I Specify `pkgs: None`. Salt however seems to ignore this parameter although the default value should also be `None`

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
```
init.sls

/etc/apt/sources.list:
  file.managed:
    - user: root
    - group: root
    - mode: 644
    - template: jinja
    - source: salt://states/teststate/templates/sources.list.j2

Artifactory | apt update:
  pkg.uptodate:
    - refresh: True
    - pkgs: None
```
### Versions Report
```
[root@salt-master-qacore-6b5c48d69c-7bf97 /]# salt --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.14
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.0-7-amd64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```
