### ISSUE TITLE
archive.extracted not setting user/group on extracted files

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt#55826]
### Description of Issue
According to the documentation, `archive.extracted` should set user and/or group on the extracted files, if provided. This isn't done.
 
### Setup
```
nexus:
  group.present:
    - system: True
  user.present:
    - fullname: Nexus Service
    - gid: nexus
    - home: /opt/sonatype/nexus
    - createhome: False
    - shell: /usr/sbin/nologin
    - empty_password: True
    - system: True
    - require:
      - group: nexus
  archive.extracted:
    - name: /opt/sonatype
    - source: http://download.sonatype.com/nexus/3/nexus-3.19.1-01-unix.tar.gz
    - source_hash: sha1=33121c338aa3e232a16156ad8edaa168aeb2f52c
    - user: nexus
    - group: nexus
    - require:
      - user: nexus
```
After applying this state to a Linux minion, all files extracted from the archive are still owned by "root:root" instead of "nexus:nexus". To fix this, I need to add the following:
```
nexus_3.19.1-01:
  file.directory:
    - name: /opt/sonatype/nexus-3.19.1-01
    - user: nexus
    - group: nexus
    - recurse:
      - user
      - group
    - require:
      - archive: nexus

sonatype_work:
  file.directory:
    - name: /opt/sonatype/sonatype-work
    - user: nexus
    - group: nexus
    - recurse:
      - user
      - group
    - require:
      - archive: nexus
```
### Steps to Reproduce Issue
Apply above SLS to a Linux minion.

### Versions Report
Salt versions 2018.3.4 and 2019.2.2.

**Comment by dhs-rec** [comment]
In addition, adding the workaround part seems to break idempotency on 2018.3.4.

**Comment by Ch3LL** [comment]
looks like im able to replicate this. will need to get this fixed up thanks

**Comment by Ch3LL** [comment]
one follow up question, does the idempotency work on 2019.2.2 when using the workaround?

**Comment by dhs-rec** [comment]
I could meanwhile also reproduce this on 2019.2.2, but only with the full-blown state, so here it is:
```
{%- set enable_svc = true %}
nexus:
  group.present:
    - system: True
  user.present:
    - fullname: Nexus Service
    - gid: nexus
    - home: /opt/sonatype/nexus
    - createhome: False
    - shell: /usr/sbin/nologin
    - empty_password: True
    - system: True
    - require:
      - group: nexus
  archive.extracted:
    - name: /opt/sonatype
    - source: http://download.sonatype.com/nexus/3/nexus-3.19.1-01-unix.tar.gz
    - source_hash: sha1=33121c338aa3e232a16156ad8edaa168aeb2f52c
    - user: nexus
    - group: nexus
    - require:
      - user: nexus
  file.symlink:
    - name: /opt/sonatype/nexus
    - target: /opt/sonatype/nexus-3.19.1-01
{%- if enable_svc %}
  service.running:
    - enable: True
    - watch:
      - file: nexus_properties
      - file: nexus_svc
      - archive: nexus
      - pkg: jre8
    - require:
      - file: nexus_3.19.1-01
      - file: sonatype_work

nexus_svc:
  file.managed:
    - name: /lib/systemd/system/nexus.service
    - contents: |
        [Unit]
        Description=Nexus service
        After=network.target

        [Service]
        Type=forking
        Environment=NEXUS_HOME="/opt/sonatype/nexus"
        LimitNOFILE=65536
        ExecStart=/opt/sonatype/nexus/bin/nexus start
        ExecStop=/opt/sonatype/nexus/bin/nexus stop
        User=nexus
        Group=nexus
        Restart=on-abort

        [Install]
        WantedBy=multi-user.target

jre8:
  pkg.installed:
    - name: openjdk-8-jre
{%- endif %}

nexus_3.19.1-01:
  file.directory:
    - name: /opt/sonatype/nexus-3.19.1-01
    - user: nexus
    - group: nexus
    - recurse:
      - user
      - group
    - require:
      - archive: nexus

sonatype_work:
  file.directory:
    - name: /opt/sonatype/sonatype-work
    - user: nexus
    - group: nexus
    - recurse:
      - user
      - group
    - require:
      - archive: nexus

nexus_etc:
  file.directory:
    - name: /opt/sonatype/sonatype-work/nexus3/etc
    - user: nexus
    - group: nexus
    - require:
      - archive: nexus

nexus_properties:
  file.managed:
    - name: /opt/sonatype/sonatype-work/nexus3/etc/nexus.properties
    - contents: application-host=127.0.0.1
    - user: nexus
    - group: nexus
    - require:
      - file: nexus_etc
```
If you apply this state several times, it will allways re-execute these steps:
```
  Name: /opt/sonatype - Function: archive.extracted - Result: Changed Started: - 14:08:06.953391 Duration: 4272.749 ms
  Name: /opt/sonatype/nexus-3.19.1-01 - Function: file.directory - Result: Changed Started: - 14:08:11.245525 Duration: 1079.646 ms
  Name: /opt/sonatype/sonatype-work - Function: file.directory - Result: Changed Started: - 14:08:12.325433 Duration: 1220.516 ms
  Name: nexus - Function: service.running - Result: Changed Started: - 14:08:18.390255 Duration: 3497.671 ms
```
This will change as soon as the state has been run with `enable_svc = false` twice. The second one won't re-execute any steps anymore and `enable_svc` can safely be set back to true.
