### ISSUE TITLE
API external auth not searching ldap group for nodes

### ISSUE THREAD

**Issue by UnknownGnome** [saltstack/salt#55839]
### Description of Issue

Using salt api and eAuth with LDAP, the ldap query to get computers is never seen in a packet trace. 
Receive error "401 Unauthorized"
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
#/etc/salt/master
# Server to auth against
auth.ldap.server: dc.test.local
#auth.ldap.minion_stripdomains: ['.test.local']

# Port to connect via
auth.ldap.port: 389
# Use TLS when connecting
auth.ldap.tls: False
# Use STARTTLS when connecting
auth.ldap.starttls: False
# LDAP scope level, almost always 2
auth.ldap.scope: 2
# Verify server's TLS certificate
auth.ldap.no_verify: False
#Search Base
auth.ldap.basedn: DC=test,DC=local
#Bind User
auth.ldap.binddn: CN=ldap_svc,OU=Users,OU=Company,DC=test,DC=local
auth.ldap.bindpw: Password123

# Bind to LDAP anonymously to determine group membership
# Active Directory does not allow anonymous binds without special configuration
# In addition, if auth.ldap.anonymous is True, empty bind passwords are not permitted.
auth.ldap.anonymous: False

# FOR TESTING ONLY, this is a VERY insecure setting.
# If this is True, the LDAP bind password will be ignored and
# access will be determined by group membership alone with
# the group memberships being retrieved via anonymous bind
auth.ldap.auth_by_group_membership_only: False

# Require authenticating user to be part of this Organizational Unit
# This can be blank if your LDAP schema does not use this kind of OU
auth.ldap.groupou: 'Users'

# Object Class for groups.  An LDAP search will be done to find all groups of this
# class to which the authenticating user belongs.
# These are only for Active Directory
auth.ldap.activedirectory: True
auth.ldap.filter: sAMAccountName={{username}}
auth.ldap.accountattributename: sAMAccountName
auth.ldap.groupclass: group
auth.ldap.persontype: person
rest_cherrypy:
  port: 4507
  disable_ssl: true
#  ssl_crt: /etc/pki/tls/certs/localhost.crt
#  ssl_key: /etc/pki/tls/certs/localhost.key
external_auth:
  ldap:
    Windows-Salt%:
      ldap('OU=Computers,OU=Company,DC=test,DC=local'):
        - '*':
          - '.*'
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
```curl -sSk http://10.195.4.114:4507/ -H 'Accept: application/x-yaml' -H 'X-Auth-Token: 2e51276396973b1ebb3f8e44a1365482b9e1aaff' -d tgt='WIN' -d fun=test.ping -d client=local```

```020-01-10 15:36:16,566 [salt.transport.ipc:35  ][TRACE   ][13805] IPCServer: Handling connection to address:
2020-01-10 15:36:16,567 [salt.master      :35  ][TRACE   ][13821] Clear payload received with command publish
2020-01-10 15:36:16,567 [salt.auth        :35  ][TRACE   ][13821] Compiled auth_list: ["ldap('OU=Computers,OU=Company,DC=test,DC=local')"]
2020-01-10 15:36:16,567 [salt.master      :2108][WARNING ][13821] Authentication failure of type "token" occurred.
````
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1057-aws
         system: Linux
        version: Ubuntu 18.04 bionic

```
