### ISSUE TITLE
cron.present not observing comment or commented

### ISSUE THREAD

**Issue by udf2457** [saltstack/salt#55855]
Debian 10.
Minion & Master version 2019.2.2.

Given a state such as:

```
gitlab_cron:
  cron.present:
    - name: cd /etc; /usr/bin/git push -q -u gitlab master >/dev/null 2>&1
    - minute: 0,30
    - comment: Gitlab push
    - commented: True
    - require:
      - file: /root/.ssh/known_hosts
      - file: /root/.ssh/id_ed25519
      - pkg: debian10_bootstrap
      - git_init
```

The resulting crontab entry when looking at `crontab -u root -l` has neither the preceeding `comment`, nor is the line `commented`.
