### ISSUE TITLE
docker_container.running state - command attribute does not support lists

### ISSUE THREAD

**Issue by cathode911** [saltstack/salt#55881]
### Description of Issue
From description of the docker_container.running state
command (or cmd): Command to run in the container

```
foo:
  docker_container.running:
    - image: bar/baz:latest
    - command: bash
```

In fact in docker Cmd and Args are lists just like, say, Binds:

```
sudo docker inspect 7004486de058 | grep Args
"Args": []
sudo docker inspect 7004486de058 | grep Cmd
"Cmd": []
```

Some containers require to run lots of commands and in this case they must be provided to docker as a list, just like binds or networks, e.g
 
```
foo:
  docker_container.running:
    - binds: /srv/www:/var/www:ro,/etc/foo.conf:/usr/local/etc/foo.conf:rw
    - command: '--config.file=/etc/prometheus/prometheus.yml,--storage.tsdb.path=/prometheus,--web.console.libraries=/usr/share/prometheus/console_libraries'
```

### Setup
rendered state from debug
```
docker-prom/prometheus:v2.15.2-container:
  docker_container.running:
    - name: prometheus
    - image: prom/prometheus:v2.15.2
    - binds: '/opt/monitoring/prometheus/conf:/etc/prometheus/,/var/lib/prometheus:/prometheus'
    - command: '--config.file=/etc/prometheus/prometheus.yml,--storage.tsdb.path=/prometheus,--web.console.libraries=/usr/share/prometheus/console_libraries,--web.console.templates=/usr/share/prometheus/consoles,--web.external-url=https://mon.art-telecom.ru/prometheus/'
    - hostname: prometheus
    - networks:
      - monitoring
    - port_bindings: '9090:9090'
    - restart_policy: always
    - user: 900
    - required:
      - docker_image: docker-prom/prometheus:v2.15.2-image
      - docker_network: docker-monitoring-network
```

result from docker inspect
```
"Args": [
            "--config.file=/etc/prometheus/prometheus.yml,--storage.tsdb.path=/prometheus,--web.console.libraries=/usr/share/prometheus/console_libraries,--web.console.templates=/usr/share/prometheus/consoles,--web.external-url=https://mon.art-telecom.ru/prometheus/"
        ],
"Cmd": [
                "--config.file=/etc/prometheus/prometheus.yml,--storage.tsdb.path=/prometheus,--web.console.libraries=/usr/share/prometheus/console_libraries,--web.console.templates=/usr/share/prometheus/consoles,--web.external-url=https://mon.art-telecom.ru/prometheus/"
            ],
```

Obviously command above is treated like single one and it's ambiguous for application in container

### Steps to Reproduce Issue
Try to treat command: as a list

### Versions Report
Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.9.41-virtual-v1.7
         system: Linux
        version: Ubuntu 16.04 xenial
