### ISSUE TITLE
3000.0.0rc2 pip_state is broken

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#55917]
### Description of Issue
After upgrading to 3000.0.0rc2 I noticed `pip.installed` was not working.

Getting a minimal sls and running in debug mode gave the following error:
```
[DEBUG   ] Failed to import states pip_state:
Traceback (most recent call last):
  File "/opt/local/lib/python2.7/site-packages/salt/loader.py", line 1607, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/opt/local/lib/python2.7/site-packages/salt/states/pip_state.py", line 129, in <module>
    from pip.exceptions import InstallationError  # pylint: disable=E0611,E0401
ImportError: No module named exceptions
```

### Setup
```
progressbar:
  pip.installed
```

Should trigger it, I am running python2.8

### Steps to Reproduce Issue
Running the simple sls from under the setup section triggers the error for me.

### Versions Report
```
Salt Version:
           Salt: 3000.0.0rc2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.6.6
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Oct 23 2018, 17:11:49)
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
