### ISSUE TITLE
3000 release annouced the deprecation of json_decode_dict is not equalivant as tojson

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#55911]
### Description of Issue
With the 3000rc dropping the deprecation of `json_decode_dict` in the next release was announced. The new way to do it is to use `tojson`.

In prepare my states and pillars before upgrading from 2018.2.3 to 3000rc2 I noticed issues when replacing `json_decode_dict` with `tojson`.

json_decode_dict would output an in the order it was received, tojson will output the keys sorted alphabetically!

### Setup
```
{% load_yaml as x %}
z: some
y: text
x: here
{% endload %}
/tmp/tojson.out:
  file.managed:
    - contents: |
        {{ x|tojson }}

/tmp/json_decode_dict.out:
  file.managed:
    - contents: |
        {{ x|json_decode_dict }}
```

### Steps to Reproduce Issue
I provided a basic test state to see it in action, notice the different order between tosjon and json_decode_dict

### Versions Report
```
Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.3.0
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.6.6
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Oct 23 2018, 17:11:49)
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```
