### ISSUE TITLE
Refactoring onlyif/unless - generalized with fallback?

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#55938]
As I was going through the release notes for Neon/3000 I came across a feature that I thought was missing, but it turned out that there were just some issues with the way a [few states](https://github.com/saltstack/salt/pull/51846#issuecomment-497913069) already had onlyif/unless implementations.

This causes some issues with the new functionality to allow states in the `onlyif/unless` declarations.

It would be great if we could figure out a clean way to refactor those so they take advantage of that new functionality, but we don't break backwards compatibility. Though it may be worth breaking that compatibility in favor of having a unified onlyif/unless flow 🤔 

In any case, the current codebase won't support the enhancements for a couple of fairly major states, such as `cmd` and `file`. 

Example:

```
do_a_thing:
  cmd.run:
    - name: echo "what?"
    - onlyif:
      - fun: file.file_exists
        path: /tmp/fnord.txt
```

Fails like this:

```
local:
----------
          ID: do_a_thing
    Function: cmd.run
        Name: echo "what?"
      Result: True
     Comment: onlyif condition is false: OrderedDict([('fun', 'file.file_exists'), ('path', '/tmp/fnord.txt')])
     Started: 16:32:53.827416
    Duration: 157.563 ms
     Changes:   
Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 157.563 ms
```

Where:

``` 
do_a_thing:
  http.query:
    - name: https://correcthorsebatterystaple.waynewerner.com
    - status: 200
    - onlyif:
      - fun: file.file_exists
        path: /tmp/fnord.txt
```

works correctly.
