### ISSUE TITLE
cant get master options into cloud provider vm

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#55943]
### Description of Issue
I am spinning up a vm on digitalocean. The vm is to have a minion and master process running on it upon completed provisioning. The minion options populate but not the master.

I am using Orchestration with a `salt.runner` for the `cloud.profile` module. 
### Setup
- provider file for credentials to digitalocean
- profile file for hypervisor provisioning options for the vm

- orchestration state
```YAML
# File: /srv/salt/orch/digitalocean_startup.sls

master_spinup:
  salt.runner:
    - parallel: True
    - name: cloud.profile
    - prof: do-centos-7-8gb-nyc1
    - provider: digitalocean
    - instances:
      - master-vm
    - kwarg:
        script: bootstrap-salt
        script_args: -M stable 2019.2.3
    - opts:
        minion:
          id: MastersSlave
          master: localhost
        master:
          user: root
          master_id: MasterMan
          order_masters: True
```
### Steps to Reproduce Issue
I run the following command:
```BASH
$ salt-run state.orch digitalocean_startup
```

The orchestration state runs perfectly, I ssh into the vm and the minions config file (/etc/salt/minion) contains the changes, but the masters configuration file (/etc/salt/master) is still the default configuration file. Both processes are running successfully as well.

I have also attempted setting the master option in the orchestration file on `- kwarg:` as well. this resulted the same.

### Versions Report
```YAML
root@CPC:/etc/salt/master.d# salt --versions-report
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.27.0
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Nov  7 2019, 10:07:09)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-37-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
