### ISSUE TITLE
Human-readable expire in user.present

### ISSUE THREAD

**Issue by snago** [saltstack/salt#55983]
According to [user.present documentation](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.user.html#salt.states.user.present) the `expire` property of `user.present` should be specified as an integer as
> Date that account expires, represented in days since epoch (January 1, 1970)

To make it more human-readable I want to be able to specify it as a string with an ISO 8601 date (e.g. "2020-01-27").

Instead of:
```
foo-expires:
  user.present:
    - name: foo
    - expire: 18288
```

I would like to be able to have:
```
foo-expires:
  user.present:
    - name: foo
    - expire: 2020-01-27
```

That would make it much easier to understand when a user expires.
