### ISSUE TITLE
virt.init seeding fails

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#56002]
### Description of Issue

Applying the following state fails only when `seed` is set to `True`:

```yaml
srv01:
  virt.running:
    - name: srv01
    - cpu: 1
    - mem: 512
    - disks:
      - name: system
        model: virtio
        format: qcow2
        image: /var/testsuite-data/disk-image-template.qcow2
        pool: default
        size: 122880
    - interfaces:
      - name: eth0
        type: network
        source: default
    - graphics:
        type: vnc
    - seed: True
```

The reported error is:

> internal error: process exited while connecting to monitor: 2020-01-28T13:48:19.036709Z qemu-system-x86_64: -drive file=/var/lib/libvirt/images/srv01_system.qcow2,format=qcow2,if=none,id=drive-virtio-disk0,cache=none,aio=native: Failed to get "write" lock
>              Is another process using the image [/var/lib/libvirt/images/srv01_system.qcow2]?

### Versions Report

Found in 2019.2.0, but problem also in master
