### ISSUE TITLE
[Feature request] Configure master through environment variables

### ISSUE THREAD

**Issue by vlina** [saltstack/salt#56102]
### Description of Issue
To ease running the master in a container, all [configuration options](https://docs.saltstack.com/en/latest/ref/configuration/master.html) should be configurable through environment variables.

Instead of this:
```yaml
pki_dir: /data/pki
cachedir: /tmp/salt/cache
pidfile: /tmp/salt/master.pid
sock_dir: /tmp/salt/master
log_file: /data/logs/master
conf_file: /config/master
sqlite_queue_dir: /data/queues

file_roots:
  base:
    - /data/states
pillar_roots:
  base:
    - /data/pillars
```

We could do this (example of what it could look like)
```
SALT_PKI_DIR="/data/pki"
SALT_CACHEDIR="/tmp/salt/cache"
SALT_PIDFILE="/tmp/salt/master.pid"
SALT_SOCK_DIR="/tmp/salt/master"
SALT_LOG_FILE="/data/logs/master"
SALT_CONF_FILE="/config/master"
SALT_SQLITE_QUEUE_DIR="/data/queues"
SALT_FILE_ROOTS="base=/data/states"
SALT_PILLAR_ROOTS="base=/data/pillars"
```
