### ISSUE TITLE
Windows reg.present: Error resolving "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681"

### ISSUE THREAD

**Issue by jpsv** [saltstack/salt#56117]
### Description of Issue
When updating registry components for active hours, I'm getting errors on the minion concerning this SID:

`S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681`

This appears to be a capability account in Windows notorious for not having a username: https://nakedsecurity.sophos.com/2019/05/22/dont-break-windows-10-by-deleting-sid-microsoft-warns/

I get 12 errors, presumably two for each attempted regedit.

### Setup
Minion is Windows 10 Pro, up to date. Tested on 2 machines. The edits seem to be set but still generates an error.
```
enable_active_hours:
  reg.present:
    - name: HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate
    - vname: SetActiveHours
    - vdata: "1"
    - vtype: REG_DWORD

set_active_hours_start:
  reg.present:
    - name: HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate
    - vname: ActiveHoursStart
    - vdata: "8"
    - vtype: REG_DWORD

set_active_hours_end:
  reg.present:
    - name: HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate
    - vname: ActiveHoursEnd
    - vdata: "19"
    - vtype: REG_DWORD

disable_automatic_reboot:
  reg.present:
    - name: HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
    - vname: AlwaysAutoRebootAtScheduledTime
    - vdata: "0"
    - vtype: REG_DWORD

auto_download_and_schedule_update_installation:
  reg.present:
    - name: HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
    - vname: AUOptions
    - vdata: "4"
    - vtype: REG_DWORD

do_not_kick_off_users:
  reg.present:
    - name: HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
    - vname: NoAutoRebootWithLoggedOnUsers
    - vdata: "0"
    - vtype: REG_DWORD
{% endif %}
```

### Steps to Reproduce Issue
Minion is running 2019.2.2 and the master is running 2019.2.3
Apply the above state file.

salt.loaded.int.utils.win_dacl:
```
[10508] Error resolving "S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681": No mapping between account names and security IDs was done.
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\utils\win_dacl.py", line 1180, in get_name
    return win32security.LookupAccountSid(None, sid_obj)[0]
pywintypes.error: (1332, 'LookupAccountSid', 'No mapping between account names and security IDs was done.')
```

### Versions Report
Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.11
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.18-11-pve
         system: Linux
        version: debian 9.11
