### ISSUE TITLE
[Feature requests][salt-cloud][AzureARM] support availability zone

### ISSUE THREAD

**Issue by tkykm** [saltstack/salt#56154]
### Description of Issue

Availability zone is important technology for redundancy or SLA and getting necessary for another azure services for example ultra disk.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
vm:
  provider: azure
  availability_zone: 3
  location: westeurope
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
