### ISSUE TITLE
Whole Mac machine hangs during and after salt state.apply

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [saltstack/salt#56165]
### Description of Issue
We're using saltstack for managing debian and mac os boxes.
Seldomly using `salt my.mac state.apply test=True` leads to a total hang of the mac os machine "my.mac".
Usually state.apply takes around 30 - 60 seconds with test=True. If the problem occurs it took ~ 6 minutes and the system cant do anything else. My "ps aux | grep salt" wont be executed for minutes. Starting the "activity monitor" is either not possible (error message) or takes forever.
Running daemons are somewhat working (e. g. a webserver on this Mac still serves HTTP requests, ...)

This problem persists even after state.apply has returned after 6 minutes. The Mac was unresponsive for another 10 - 15 minutes. The reported CPU usage although is low (~ 1 %).

We have ~ 10 mac boxes and it doesnt happen on all of them, just a few and only very sporadic. Restarting the salt-minion does not help. We couldnt try to restart the machine, because these mac servers are used internally by a lot of people.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I cant provide you the SLS, because they have highly sensitive stuff in them. The following states are used:
```
- file.absent
- file.append
- file.directory
- file.managed
- file.recurse
- cmd.run
- user.present
- service.running
``` 
The Mac server is connected to a Mac LDAP-Server, so there may be some overhead for user.present for user & groups?

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Call `salt my.mac state.apply test=True` on the salt-master.
There is an error in the log that a certain user group is not available, although there it certainly exists.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt-Master:
```
/usr/lib/python2.7/dist-packages/salt/scripts.py:102: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.12
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-11-amd64
         system: Linux
        version: debian 9.12
```

Mac OS-Minion:
```
/opt/salt/lib/python2.7/site-packages/salt/scripts.py:198: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Jan  7 2020, 18:15:51)
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 16.7.0
         system: Darwin
        version: 10.12.6 x86_64
```
