### ISSUE TITLE
Are the docs wrong for using git with ext_pillar?

### ISSUE THREAD

**Issue by windowsrefund** [saltstack/salt#56163]
### Description of Issue
I am trying to access my pillar via git_pillar using pygit2 and SSH authentication. [This documentation](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html#git-pillar-configuration) suggests a syntax of:

`- master git@other-git-server:pillardata-ssh.git:`

Of course, that's not a valid URL since there's no user specified as in:

`git@git-server:user/repo.git`

Is the documentation wrong?

Here's a stripped down example of my config which git_pillar can't authenticate to (repo user is fake below)

```
fileserver_backend:
  - gitfs
 
gitfs_remotes:
  - git@bitbucket.org:foobar/lab-salt.git:
     - pubkey: /root/.ssh/id_rsa_lab_salt.pub
     - privkey: /root/.ssh/id_rsa_lab_salt
 
ext_pillar:
  - git:
    - master git@bitbucket.org:foobar/lab-salt.git:
      - root: pillar
      - privkey: /root/.ssh/id_rsa_lab_salt
      - pubkey: /root/.ssh/id_rsa_lab_salt.pub
```

It should be noted that gitfs_remotes can authenticate successfully.
