### ISSUE TITLE
No data from mine.get when targeting with grains

### ISSUE THREAD

**Issue by kschafer2598** [saltstack/salt#56171]
### Description of Issue
Hi,

Trying to do mine.get and it is not returning results when using grain targeting. This is a multimaster setup with etcd for the cache.

Targeting with glob works; Targeting with grains or compound does not work.

Works:
`salt-call mine.get '*' grains.item`

Does not work:
`salt-call mine.get 'cpuarch:x86_64' grains.item grain`
`salt-call mine.get 'G@cpuarch:x86_64' grains.item compound`

### Setup
Minion mine config:
```
mine_interval: 5
mine_functions:
  grains.item: [fqdn, ipv4, fqdn_ip4]
```

### Steps to Reproduce Issue
`salt-call mine.get 'cpuarch:x86_64' grains.item grain`

### Versions Report
Minion:

Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.1.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

Master:

Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 17.4.2
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Nov  7 2019, 10:07:09)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-76-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by DmitryKuzmenko** [comment]
```
2020-02-17 13:54:37 dimm@kuzmenko /home/dimm/projects/salt/git/salt （╯°□°）╯︵ ┻━┻ 64 (HEAD detached at v2019.2.2)
(venv-2.7) $ ./scripts/salt -l critical '*' mine.get 'os:Arch' internal_ip grain
alpha:
    ----------
    alpha:
        - 192.168.48.28
2020-02-17 13:54:41 dimm@kuzmenko /home/dimm/projects/salt/git/salt (⌐■_■) (HEAD detached at v2019.2.2)
(venv-2.7) $ ./scripts/salt-call -l critical mine.get 'os:Arch' internal_ip grain
local:
    ----------
    alpha:
        - 192.168.48.28
2020-02-17 13:54:46 dimm@kuzmenko /home/dimm/projects/salt/git/salt (⌐■_■) (HEAD detached at v2019.2.2)
(venv-2.7) $ ./scripts/salt-call -l critical  mine.get 'G@os:Arch' internal_ip compound
local:
    ----------
    alpha:
        - 192.168.48.28
```

**Comment by DmitryKuzmenko** [comment]
Could you please provide more details about your configuration? Sanitized minion config would be perfect.

**Comment by kschafer2598** [comment]
Here's the minion config

```

**Comment by kschafer2598** [comment]
I am also unable to get mine data using templates:

```
{% for host, data in salt['mine.get']('G@kernel:Linux', 'grains.item', 'compound').items() -%}
{{ data["fqdn"] }}
{% endfor -%}
```

**Comment by kschafer2598** [comment]
I haven't seen any updates; Is this the right place to report an issue like this?

**Comment by kschafer2598** [comment]
Please help; let me know what else is needed to move forward

**Comment by DmitryKuzmenko** [comment]
@kschafer2598 sorry missed that. I'll follow up today.

**Comment by DmitryKuzmenko** [comment]
Still cannot reproduce the issue but I'm working on that. Will try more tomorrow.

**Comment by DmitryKuzmenko** [comment]
No luck. @team-core could someone try to reproduce this?

**Comment by OrangeDog** [comment]
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mine.html#salt.modules.mine.get

> tgt_type (str) -- Default glob. Target type to use with tgt.

If you want to target by grains you need to set `tgt_type=grain`

**Comment by kschafer2598** [comment]
Just tried it, same result

```
root@salthost-01:~# salt-call mine.get 'os:Ubuntu' grains.item tgt_type=grain
local:
    ----------
```

**Comment by kschafer2598** [comment]
I've upgraded minions/masters to 2019.2.5 and have the same issue. 

What else can I try here?

**Comment by DmitryKuzmenko** [comment]
@kschafer2598 I'm getting the empty results if I'm removing cache and run master and never run minion, using the only salt-call command. After I'm starting the minion once everything works good ever if I'm stopping it.

**Comment by DmitryKuzmenko** [comment]
Could you also please check is this the same on both masters?

**Comment by github-abcde** [comment]
Could you try the following:
- verify on all related minions that `salt $minion config.get mine_functions` produces the correct result.
- Flush all previous mine data using `salt $minion mine.flush`
- Forcing an update of the mine data using `salt $minion mine.update`
- Optionally: verify the targeting grain using `salt $minion grains.get cpuarch`
- Then query the salt-mine, using `salt $minion mine.get 'cpuarch:x86_64' grains.item grain`
Of course these could also all be done locally using `salt-call` instead of `salt $minion`.
I'm interested in where things go awry.

**Comment by kschafer2598** [comment]
Thanks, everything works until the end, where it returns nothing for the query.

```
root@salthost-01:~# salt-call grains.get os
local:
    Ubuntu

root@salthost-01:~# salt-call mine.get 'os:Ubuntu' grains.item grain
local:
    ----------
```

**Comment by ikogan** [comment]
I'm also experiencing what I believe to be this behavior, I cannot target with grains but using individual minion IDs works just fine.

```
Salt Version:
           Salt: 3000.4
 
Dependency Versions:
           cffi: 1.14.3
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: 1.1.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.9
         pygit2: 1.4.0
         Python: 3.7.9 (default, Oct 22 2020, 05:22:26)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 5.4.0-72-generic
         system: Linux
        version: Not Installed
```

Minion Version is `3001.7`.
