### ISSUE TITLE
ext_pillar - git checkout error with multiple repos

### ISSUE THREAD

**Issue by clallen** [saltstack/salt#56181]
### Description of Issue
I have an ext_pillar setup in which one repo serves a single pillarenv ("asmt"), and the other serves everything else.
When querying the "asmt" repo, the data is returned as expected, but this error appears in the master log:

```
[salt.utils.gitfs :1185][ERROR   ][35346] Failed to checkout asmt from git_pillar remote '__env__ file:///srv/salt.git': remote ref does not exist
```

### Setup
I have the repos set up with the "asmt" one first, and the "catch-all" one last.  The docs make it sound like these are searched sequentially, but it looks like the second one is being searched even though the result was already found in the first one.

Master config
```
ext_pillar:
  - git:
    - file:///srv/asmt.git:
      - env: asmt
    - __env__ file:///srv/salt.git
```

### Steps to Reproduce Issue
There is a "services" key in the "asmt" repo, and I can look it up:
```
[root] # salt-call pillar.get services saltenv=asmt
local:
    ----------
    icinga:
        ----------
        cmd_socket:
            /opt/apps/asmt/mcp/icinga/var/rw/icinga.cmd
        default_duration:
            3600
```
However the error above appears in the master log, because that branch does not exist in the other repo.
Is there a problem with my config that is causing it to try the lookup in both repos?

### Versions Report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.8.1
      docker-py: 4.1.0
          gitdb: 2.0.6
      gitpython: 2.1.14
          ioflo: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 08:19:52)
   python-gnupg: 0.4.5
         PyYAML: 3.13
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.2

System Versions:
           dist: oracle 7.7
         locale: UTF-8
        machine: x86_64
        release: 4.14.35-1902.6.6.el7uek.x86_64
         system: Linux
        version: Oracle Linux Server 7.7

**Comment by waynew** [comment]
Thanks for the report! Working to reproduce this now.

**Comment by waynew** [comment]
I haven't been able to reproduce this - could you put together a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by clallen** [comment]
Sure thing, I have created an [image](https://hub.docker.com/repository/docker/clallen/salt-mcve-56181) on Docker Hub with everything needed built in (base image saltstack/salt:2019.2.2).

Container run command:
```docker run --name salt --hostname salt -P -e SALT_SHARED_SECRET=waynew --rm -d -p 127.0.0.1:8000:8000/tcp clallen/salt-mcve-56181```

The master config in it is:
```
pillarenv_from_saltenv: True
ext_pillar:
  - git:
    - file:///repo1.git:
      - env: env1
    - __env__ file:///repo2.git
auto_accept: True
```

Pillar data in the Git repos:
repo1
```
sampledata:
  Key1: Val1
```
repo2
```
sampledata:
  Key2: Val2
```

To reproduce, start ```docker logs -f salt``` in another window, and run these curl commands:
```
# API login
curl -Skis https://localhost:8000/login -c /tmp/cookies -H 'Accept: application/x-yaml' -d eauth=sharedsecret -d username=salt -d password=waynew

# saltenv "base" returns repo2 data as expected
curl -Skis https://localhost:8000 -b /tmp/cookies -H 'Accept: application/x-yaml' -d client=local -d tgt=\* -d fun=pillar.get -d arg=sampledata -d arg='saltenv=base'

# saltenv "env1" returns repo1 data but throws error in master log
curl -Skis https://localhost:8000 -b /tmp/cookies -H 'Accept: application/x-yaml' -d client=local -d tgt=\* -d fun=pillar.get -d arg=sampledata -d arg='saltenv=env1'
```
Master log:
```
[ERROR   ] Failed to checkout env1 from git_pillar remote '__env__ file:///repo2.git': remote ref does not exist
```
I would expect that if the specified env was found in the first repo, it would not try the second.  Maybe I'm mistaken about that.
In any case it should probably not throw an error, maybe an info or warning.

**Comment by sagetherage** [comment]
@waynew can you follow up here, please?

**Comment by sagetherage** [comment]
putting this back into triage for follow up

**Comment by waynew** [comment]
@clallen Thanks for the follow up!

When I follow the documentation in https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html and update the config from

```
pillarenv_from_saltenv: True
ext_pillar:
  - git:
    - file:///repo1.git:
      - env: env1
    - __env__ file:///repo2.git
auto_accept: True
```

to

```
pillarenv_from_saltenv: True
ext_pillar:
  - git:
    - file:///repo1.git:
      - env: env1
    - __env__ file:///repo2.git:
       - root: pillar
auto_accept: True
```
I don't get the same error message. Does that change get you the expected behavior?
