### ISSUE TITLE
Windows: cmd.run doesn't honor PATH anymore after update from 2018.3.4 to 2019.2.3

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt#56199]
### Description of Issue
After said update, the follwing SLS doesn't work anymore:
```
{% if grains['os'] == 'Windows' %}
{% set version = salt['pillar.get']('python:crypto:version') %}
{% from "saltstore/map.jinja" import saltstore with context %}
{% set pkg_name = 'pycrypto-' ~ version ~ '.win-amd64-py2.7.exe' %}
{% set current_path = salt['environ.get']('PATH') %}
include:
  - python.install

pycrypto_pkg:
  file.managed:
    - name: {{ saltstore.dir }}/Python/{{ pkg_name }}
    - source: salt://store/Python/{{ pkg_name }}?saltenv=base
    - makedirs: True

pycrypto_install:
  cmd.run:
    - name: easy_install {{ saltstore.dir }}/Python/{{ pkg_name }}
    - creates: C:/Python27/Lib/site-packages/pycrypto-{{ version }}-py2.7-win-amd64.egg
    - env:
      - PATH: {{ ['C:\Python27', 'C:\Python27\Scripts', current_path]|join(';') }}
    - require:
      - file: pycrypto_pkg
      - sls: python.install
    - shell: powershell
{% endif %}
```
The `cmd.run` fails with this error message:
```
easy_install : The term 'easy_install' is not recognized as the name of a cmdlet, function, script file, or operable program.
```
### Setup
See above.

### Steps to Reproduce Issue
Apply this to Windows Minions running 2018.3.4 -> Works
Apply this to Windows Minions running 2019.2.3 -> Fails
