### ISSUE TITLE
modules/virtualenv_mod AttributeError (virtualenv.virtualenv_version)

### ISSUE THREAD

**Issue by willjp** [saltstack/salt#56238]
### Description of Issue
Using salt-state `virtualenv_mod.managed` fails with a python AttributeError because `virtualenv.virtualenv_version` does not exist (but `__version__` does).

The issue on line 170 of `salt.modules.virtualenv_mod`.

``` python
import virtualenv
version = getattr(virtualenv, '__version__',
                  virtualenv.virtualenv_version)
```

Maybe resolve with:
``` python
import virtualenv
version = getattr(virtualenv, '__version__', None) \
          or getattr(virtualenv, 'virtualenv_version')
```

Versions:
```
salt-3000
python-3.5.2
virtualenv-20.0.5
ubuntu-16.04
```

### Setup
``` yaml
#!stateconf
# .../states/myvirtualenv.sls

.create restapi virtualenv:
    virtualenv.managed:
        - name:     /home/restapi/venv
        - venv_bin: /usr/bin/python3-venv
        - user:     tmarestapi
        - cwd:      /home/restapi
```

### Steps to Reproduce Issue
``` bash
sudo salt-call state.apply myvirtualenv
```

### Versions Report
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Oct  8 2019, 13:06:37)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-169-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
