### ISSUE TITLE
How to pipe bash output to package name?

### ISSUE THREAD

**Issue by saurabhnemade** [saltstack/salt#56268]
We are trying to run `yum install kernel-devel-$(uname -r)` via salt state file.
We tried following but it does not resolve the `uname -r` at runtime. Instead it takes its value as it.

```
dependencies:
  pkg.installed:
    - pkgs:
      - kernel-devel-$(uname -r)
      - kernel-header-$(uname -r)
```

How can we handle it correctly in state file?

**Comment by ismail0352** [comment]
Try this to fetch `grains.get kernelrelease`

**Comment by garethgreenaway** [comment]
@saurabhnemade There are a couple approaches to accomplish what you're trying to do.  You can use @ismail0352 's suggestion and pull the information from grains:
```
dependencies:
  pkg.installed:
    - pkgs:
      - kernel-devel-{{ grains['kernelrelease'] }}
      - kernel-header-{{ grains['kernelrelease'] }}
```

If you need to include the output from a command you can call the cmd.run module from the state file:
```
dependencies:
  pkg.installed:
    - pkgs:
      - kernel-devel-{{ salt['cmd.run']('uname -r') }}
      - kernel-header-{{ salt['cmd.run']('uname -r') }}
```
