### ISSUE TITLE
3000 saltversioninfo minion grain seems unorthodox.

### ISSUE THREAD

**Issue by weswhet** [saltstack/salt#56261]
### Description of Issue
Starting in salt 3000 the `saltversioninfo` grain returns info similar to below on a macOS minion.

```
    saltversioninfo:
        - 3000
        - None
        - None
        - 0
```

previously it was something like
```
    saltversioninfo:
        - 2019
        - 2
        - 3
        - 0
```
The combination of `None` and `int` types seems odd.

Clearly not a critical bug :) Just wanted to put it on the radar for the new versioning system.

### Versions Report
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.11
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Feb  1 2020, 17:02:26)
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 19.3.0
         system: Darwin
        version: 10.15.3 x86_64
```
