### ISSUE TITLE
SaltSSH with ssh_ext_alternatives broken in v3000

### ISSUE THREAD

**Issue by kkoppel** [saltstack/salt#56305]
### Description of Issue
After upgrading to SaltStack v3000 I am no longer able to manage a python2.7-based node via SaltSSH from my python3-based master. This worked with SaltStack v2019.2.3.

### Setup
I’m running the Salt master on Debian buster, installed using packages from repo.saltstack.com. I need to also manage a single node via SaltSSH and this node only has python2.7 available. So, I’ve also installed python2.7 versions of all the relevant libraries on the master and installed a python2.7 version of Salt as follows:
```
$ git clone --branch v3000 --depth 2 https://github.com/saltstack/salt.git
$ cd salt/
$ sudo python setup.py install
```

My roster file:
```
gke-prom:
  host: X.X.X.X
  user: kristjan
  sudo: True
```

SaltSSH alternative versions configuration:
```
ssh_ext_alternatives:
    py2:
        py-version: [2, 7]
        path: /usr/local/lib/python2.7/dist-packages/salt-3000-py2.7.egg
        dependencies:
            backports_abc: /usr/lib/python2.7/dist-packages/backports_abc.py
            certifi: /usr/lib/python2.7/dist-packages/certifi
            jinja2: /usr/lib/python2.7/dist-packages/jinja2
            markupsafe: /usr/lib/python2.7/dist-packages/markupsafe
            msgpack: /usr/lib/python2.7/dist-packages/msgpack
            singledispatch: /usr/lib/python2.7/dist-packages/singledispatch.py
            singledispatch_helpers: /usr/lib/python2.7/dist-packages/singledispatch_helpers.py
            tornado: /usr/local/lib/python2.7/dist-packages/salt-3000-py2.7.egg/salt/ext/tornado
            yaml: /usr/lib/python2.7/dist-packages/yaml
```

### Steps to Reproduce Issue
Trying to run anything via salt-ssh results in this error:
```
$ salt-ssh gke-prom grains.get 'kernelrelease'
gke-prom:
    ----------
    _error:
        Failed to return clean data
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.kristjan_1ec649_salt/salt-call", line 26, in <module>
            from salt.scripts import salt_call
        ImportError: No module named salt.scripts
    stdout:
```

This issue may be caused by changes to how SaltStack gets installed via setuptools:
```
# python setup.py install

with v2019.2.3:
$ ls -la /usr/local/lib/python2.7/dist-packages/
total 16
drwxrwsr-x  3 root staff 4096 Mar  4 08:37 .
drwxrwsr-x  4 root staff 4096 Mar  4 08:34 ..
drwxr-sr-x 42 root staff 4096 Mar  4 08:37 salt
-rw-r--r--  1 root staff 3768 Mar  4 08:37 salt-2019.2.3.egg-info

with v3000:
$ ls -la /usr/local/lib/python2.7/dist-packages/
total 20
drwxrwsr-x 1 root staff 4096 Mar  4 09:05 .
drwxrwsr-x 1 root staff 4096 Feb 20 15:07 ..
-rw-r--r-- 1 root staff   22 Feb 20 15:08 easy-install.pth
drwxr-sr-x 5 root staff 4096 Feb 20 15:08 salt-3000-py2.7.egg
```

In order to even get to the above error message, I had to adjust ssh_ext_alternatives after upgrading to v3000. I changed from:
```
ssh_ext_alternatives:
    py2:
        py-version: [2, 7]
        path: /usr/local/lib/python2.7/dist-packages/salt
        dependencies:
            ...
            tornado: /usr/local/lib/python2.7/dist-packages/tornado
```

to:
```
ssh_ext_alternatives:
    py2:
        py-version: [2, 7]
        path: /usr/local/lib/python2.7/dist-packages/salt-3000-py2.7.egg
        dependencies:
            ...
            tornado: /usr/local/lib/python2.7/dist-packages/salt-3000-py2.7.egg/salt/ext/tornado
```

I was able to get SaltSSH working again with v3000 by changing /var/tmp/.kristjan_1ec649_salt/salt-call locally on the node from:
```
syspaths = ["pyall"]
```

to:
```
syspaths = ["pyall", "py2/salt-3000-py2.7.egg"]
```

Probably some part of this whole system is still expecting to find salt/scripts.py under the “salt” directory rather than salt-3000-py2.7.egg?

Currently scripts.py exists in 2 locations on the node:
/var/tmp/.kristjan_1ec649_salt/pyall/salt/scripts.py
/var/tmp/.kristjan_1ec649_salt/py2/py2/salt-3000-py2.7.egg/salt/scripts.py

However, sys.path in salt-call currently looks like this without my manual change:
```
['/var/tmp/.kristjan_1ec649_salt/py2/py2', '/var/tmp/.kristjan_1ec649_salt/py2/pyall', '/var/tmp/.kristjan_1ec649_salt', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages']
```

### Versions Report
Python3 Salt master:
```
$ salt --versions-report
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.3 
         locale: utf-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.3
```

Python2.7 Salt master:
```
$ /usr/local/bin/salt --versions-report
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Oct 10 2019, 22:02:15)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.3 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.3
```
