### ISSUE TITLE
Scheduled highstate on Windows: Unhandled exception running state.highstate

### ISSUE THREAD

**Issue by SDedik** [saltstack/salt#56301]
### Description of Issue
I have Windows minion which needs to apply state.highstate automatically on a regular interval. For that I schedule a job using pillar. Job execution fails with following exception:
`Get-Content -Path C:\salt\var\log\salt\minion`
>2020-03-04 06:31:19,780 [salt.utils.schedule:801 ][ERROR   ][3268] Unhandled exception running state.highstate
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\schedule.py", line 769, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\state.py", line 1095, in highstate
    _set_retcode(ret, highstate=st_.building_highstate)
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\state.py", line 107, in _set_retcode
    if not __utils__['state.check_result'](ret, highstate=highstate):
KeyError: 'state.check_result'

Highstate is not applied.
The exception repeats itself according to job schedule configured. In my case every 2 hours.
Calling `salt-call.bat state.highstate` manually always works.

### Setup
`top.sls`:
```
base:
  'windev-sdedik':
    - roles.test
```
`roles/test/init.sls`:
```
my_file1:
  file.managed:
    - name: C:\Temp\my_file1.txt
    - template: jinja
    - makedirs: true
    - contents:
      - File content I am expecting to see
```
`pillar/top.sls`:
```
base:
  '*':
    - scheduler
```
`pillar/scheduler.sls`:
```
schedule:
  highstate:
    function: state.highstate
    minutes: 120
```

### Versions Report
Server:
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.28.4
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 1.0.3
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```
Minion:
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.10
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2019Server
         system: Windows
        version: 2019Server 10.0.17763 SP0 Multiprocessor Free
```
