### ISSUE TITLE
ldap.managed state and underlying ldap3 module don't work on minions version `2019.2.3` when `dn` to `add` or `replace` doesn't yet exist in the tree

### ISSUE THREAD

**Issue by sticky-note** [saltstack/salt#56366]
### Description of Issue
`ldap.managed` state does not work as expected from the documentation

### Setup
`feed_domain.sls` :
```
feed_domain_skeleton:
  ldap.managed:
    - name: ldap://localhost:389/
    - connect_spec:
        url: ldap://localhost:389/
        bind:
          method:   simple
          dn:       cn=root,example,dc=com
          password: root
    - entries:
      - dc=example,dc=com:
        - replace:
            objectClass:
              - top
              - dcObject
              - organization
            o:
              - example.com
            dc:
              - example
```
### Steps to Reproduce Issue
On ldap server which is a minion do `salt-call state.apply feed_domain`
Result:
```
          ID: feed_domain_skeleton
    Function: ldap.managed
        Name: ldap://localhost:389/
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python3.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python3.7/site-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python3.7/site-packages/salt/states/ldap.py", line 334, in managed
                  __salt__['ldap3.add'](l, dn, n)
                File "/usr/local/lib/python3.7/site-packages/salt/modules/ldap3.py", line 414, in add
                  l.c.add_s(dn, modlist)
                File "/usr/local/lib/python3.7/site-packages/ldap/ldapobject.py", line 430, in add_s
                  return self.add_ext_s(dn,modlist,None,None)
                File "/usr/local/lib/python3.7/site-packages/ldap/ldapobject.py", line 415, in add_ext_s
                  msgid = self.add_ext(dn,modlist,serverctrls,clientctrls)
                File "/usr/local/lib/python3.7/site-packages/ldap/ldapobject.py", line 412, in add_ext
                  return self._ldap_call(self._l.add_ext,dn,modlist,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
                File "/usr/local/lib/python3.7/site-packages/ldap/ldapobject.py", line 315, in _ldap_call
                  result = func(*args,**kwargs)
              TypeError: ('Tuple_to_LDAPMod(): expected a tuple', [('objectClass', [b'top', b'dcObject', b'organization']), ('o', [b'example.com']), ('dc', [b'domain'])])
     Started: 14:32:48.244521
    Duration: 4.342 ms
     Changes:   
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.6 (default, Mar  2 2020, 07:09:25)
   python-gnupg: Not Installed
         PyYAML: 5.2
          PyZMQ: 18.1.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: utf-8
        machine: amd64
        release: 12.1-STABLE
         system: FreeBSD
        version: Not Installed
```

### Notes:

- Note that an array is passed to the failling function of `python3-ldap` module (`Tuple_to_LDAPMod()`) whereas it expects a Tuple. I began to debug of `ldap3` module but I am not such familiar with `Python` and I hope someone have time to dig into. It looks not like a complicated issue
- All with python 3

**Comment by Ch3LL** [comment]
was this working previously?

if you try an older version of python3-ldap does it work?

**Comment by sticky-note** [comment]
@Ch3LL  Seems weird that unit testing is not failing for that ?

**Comment by sticky-note** [comment]
@Ch3LL 
Edit: I tested on `debian Buster` with salt `3000` and `python-ldap` version `3.2.0` ( last version ) and there is no such issue

**Comment by sticky-note** [comment]
@Ch3LL 
Edit: I tested on `debian Buster` with salt `3000` and `python-ldap` version `3.2.0` ( last version ) and there is no such issue

**Comment by sticky-note** [comment]
@Ch3LL 
Edit: I retested on `debian Buster` with salt `3000` and `python-ldap` version `3.2.0` ( last version ) and there is no such issue

**Comment by sticky-note** [comment]
@Ch3LL 
Update: I managed to isolate that this issue occurs only when `dn` to `replace` or to `add` doesn't yet exist in the tree.

**Comment by sticky-note** [comment]
@Ch3LL I managed to reproduce this issue on `Debian Buster` on salt minion version `2019.2.3` and python-ldap `3.2.0` from `pip`
```
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.3 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-8-amd64
         system: Linux
        version: debian 10.3
```
What to do with this issue as it concern an older version of `salt` when we know that `salt` `3000` is not yet present in `FreeBSD` repository

**Comment by sticky-note** [comment]
@Ch3LL Ok, no such issue with `salt` version `3000` from `pip` on FreeBSD 12.1 with `py37-ldap` version `3.2.0` neither
```
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.6 (default, Mar  2 2020, 07:09:25)
   python-gnupg: Not Installed
         PyYAML: 5.2
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: utf-8
        machine: amd64
        release: 12.1-STABLE
         system: FreeBSD
        version: Not Installed
```
`salt` `3000` is not yet available as a `minion` only from official FreeBSD repository. What's next ?
