### ISSUE TITLE
State.event can't JSON serialize datetime in data

### ISSUE THREAD

**Issue by jtraub91** [saltstack/salt#56389]
### Description of Issue
When trying to view the salt minion local event bus with `salt-call state.event`, data returned after issuing `salt-call event.fire '{"func": "list"}' 'manage_schedule'` causes the `state.event` command to exit with the following error:
```
# salt-call state.event
manage_schedule {"func": "list", "where": null, "_stamp": "2020-03-16T17:10:47.596871"}

Passed invalid arguments: Object of type datetime is not JSON serializable.
```

The posted event displays, but I suspect the following data isn't properly serialized by `salt.utils.json.dumps` here: https://github.com/saltstack/salt/blob/master/salt/modules/state.py#L2420

### Setup
Normal salt installation

### Steps to Reproduce Issue
Issue the following commands on a salt minion
```
# salt-call --local state.event pretty=True
```
```
# salt-call --local event.fire '{"func": "list"}' 'manage_schedule'
```
### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.28.2
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.7.5 (default, Oct 17 2019, 12:25:15)
   python-gnupg: 0.4.2
         PyYAML: 5.1.1
          PyZMQ: 18.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: Not Installed

```
