### ISSUE TITLE
SaltRenderError: Could not locate requisite of [files] present in state with name [/etc/sysconfig/raid-check]

### ISSUE THREAD

**Issue by zloyded** [saltstack/salt#56397]
### Description of Issue
```SaltRenderError: Could not locate requisite of [files] present in state with name [/etc/sysconfig/raid-check]

    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1664, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1083, in highstate
        orchestration_jid=orchestration_jid)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 3968, in call_highstate
        return self.state.call_high(high, orchestration_jid)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2789, in call_high
        ret = self.call_chunks(chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2151, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2484, in call_chunk
        status, reqs = self.check_requisite(low, running, chunks, pre=True)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2336, in check_requisite
        req_key, chunk['name']))
    SaltRenderError: Could not locate requisite of [files] present in state with name [/etc/sysconfig/raid-check]


```
### Setup
```raid-check:
  file.replace:
    - name: /etc/sysconfig/raid-check
    - pattern: 'ENABLED=yes'
    - repl: 'ENABLED='
    - ignore_if_missing: True
    - count: 1```

### Steps to Reproduce Issue
`salt 'tgt' state.apply`
Without specify saltenv, have error obove!
And same i have with `cmd.run`:
```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1664, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1083, in highstate
        orchestration_jid=orchestration_jid)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 3968, in call_highstate
        return self.state.call_high(high, orchestration_jid)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2789, in call_high
        ret = self.call_chunks(chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2151, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2484, in call_chunk
        status, reqs = self.check_requisite(low, running, chunks, pre=True)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2336, in check_requisite
        req_key, chunk['name']))
    SaltRenderError: Could not locate requisite of [files] present in state with name [rpm --rebuilddb]
```
And, i ges more others function issued with this in 2019.2.3 version!

### Versions Report
`Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct 19 2016, 15:49:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 4.19.65-1.rambler.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
`
Same configuration are valid with other version:

`Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.13.1
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.19.12-2.rambler.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core`

**Comment by frogunder** [comment]
@zloyded Thank you for reporting this issue.

I am however not able to replicate it.

I have this in my state file
```
test:
  file.replace:
    - name: /etc/sysconfig/raid-check
    - pattern: 'ENABLED=yes'
    - repl: 'ENABLED='
    - ignore_if_missing: True
    - count: 1
```
which gives me this result
```
frode1:
----------
          ID: test
    Function: file.replace
        Name: /etc/sysconfig/raid-check
      Result: True
     Comment: Changes were made
     Started: 18:04:16.301445
    Duration: 19.938 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -50,7 +50,7 @@
                   # /dev/md/root.  The names used in this file must match the names seen in
                   # /proc/mdstat and in /sys/block.
                   
                  -ENABLED=yes
                  +ENABLED=
                   CHECK=check
                   NICE=low
                   # To check devs /dev/md0 and /dev/md3, use "md0 md3"

Summary for frode1
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  19.938 ms
```
```
[root@frode1 ~]# salt --version
salt 2019.2.3 (Fluorine)
```

If you have any other information on how to replicate it, please let me know.

Thanks.

**Comment by zloyded** [comment]
okay, can you present cmd of salt command you call?
You specify `saltenv` when run salt cmd?
When i define `saltenv` witch environ where state is, is ok. But when i run `salt` without `saltenv` i see this: `SaltRenderError: Could not locate requisite of [files] present in state with name [/etc/sysconfig/raid-check]`. 
Ive try already define `master_root`, `file_roots`, with base and production environmet in both environmets, like this:
```
file_roots:
  base:
    - /srv/salt/states/base
  prod:
    - /srv/salt/states/production
    - /srv/salt/states/base < this in any location, this not help to
  __env__:
     (- /srv/salt/states/base) < this here
    - /srv/salt/states/production 
     (- /srv/salt/states/base) < and here, no effect
```
how now files lookup? Difference in 2019.2.2 > 2019.2.3 > 3000?

Once time, i have 2019.2.2 installation, there is fine with same config, file serving work as well!

**Comment by frogunder** [comment]
Running all these commands give me the same result, no errors. I do not specify `saltenv`

```
salt \* state.apply test
salt \* state.apply
salt \* state.sls test
salt \* state.highstate
```

I have not changed anything in my master config file, which means my `file_roots` are set to `/srv/salt`

**Comment by zloyded** [comment]
@frogunder  can you give me full example of `file_roots ` and `master_roots`? 
for multi environments what option correct?
In docs example of `master_roots` is string, but when i define string or list, i see warning:
```[WARNING ] Config option 'master_roots' with value /srv/salt has an invalid type of unicode, a dict is required for this option```

**Comment by zloyded** [comment]
And one more thing, i have state:
```
rpmrebuild:
  cmd.run:
    - name: rpm --rebuilddb
    - bg: True
```
And with this have this issue to!
```SaltRenderError: Could not locate requisite of [files] present in state with name [rpm --rebuilddb]```
How does the module `cmd` work now? Why he looking for a file?

**Comment by zloyded** [comment]
> I have not changed anything in my master config file, which means my `file_roots` are set to `/srv/salt`

With single environment?
Show you full `file_roots` section please1

**Comment by frogunder** [comment]
@zloyded Sorry for not replying sooner, its been a busy last few days.

Regarding my `file_roots` settings in master config file, they have not been changed, they are like this, which means they use `/srv/salt`
```
# file_roots:
#   base:
#     - /srv/salt/
#   dev:
#     - /srv/salt/dev/services
#     - /srv/salt/dev/states
#   prod:
#     - /srv/salt/prod/services
#     - /srv/salt/prod/states
#
#file_roots:
#  base:
#    - /srv/salt
```
 Also checking this sls file:
```
[root@frode2 ~]# cat /srv/salt/test2.sls 
rpmrebuild:
  cmd.run:
    - name: rpm --rebuilddb
    - bg: True
```
give me this result, no errors:
```
[root@frode2 ~]# salt \* state.apply test2
frode2:
----------
          ID: rpmrebuild
    Function: cmd.run
        Name: rpm --rebuilddb
      Result: True
     Comment: Command "rpm --rebuilddb" run
     Started: 14:00:34.112735
    Duration: 22.211 ms
     Changes:   
              ----------
              pid:
                  12232
              retcode:
                  None
              stderr:
              stdout:

Summary for frode2
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  22.211 ms
```
If you do any changes to the master config file, you will need to restart the master for the changes to take effect.

**Comment by zloyded** [comment]
> If you do any changes to the master config file, you will need to restart the master for the changes to take effect.
Sure.

I have different `file_roots` like this, now in productions setup:
```
file_roots:
  base:
     - /srv/salt/states/base
  prod:
     - /srv/salt/states/production
     - /srv/salt/state/base
```
With this setup i have fails described above.
Ive tryed move `top.sls` to `/srv/salt/` with changes in state paths inside, but still have this issue.
Try move your states by environments
```
#/srv/salt/states/base/top.sls:

'base':
  "*":
  - system.test2
'prod':
  "*":
  - system.other_state

#/srv/salt/states/base/system/test2.sls:
rpmrebuild:
  cmd.run:
    - name: rpm --rebuilddb
    - bg: True

#/srv/salt/states/production/system/any_other.sls:

rpmrebuild:
  cmd.run:
    - name: rpm --rebuilddb
    - bg: True
```

**Comment by zloyded** [comment]
So, i found some state, within salt-master went crazy.
```
salt-master:
  service.running:
    - names:
       - salt-master:
          - enabled: True
          - watch:
             - files: /etc/salt/master
       - salt-minion:
          - enabled: True
          - watch:
             - files: /etc/salt/minion
```
Then ive delete it from state, salt works well.
So, Well, can this be considered as issue?
