### ISSUE TITLE
[Feature request] API call to fetch master pubkey

### ISSUE THREAD

**Issue by johnnybubonic** [saltstack/salt#56449]
### Description of Issue
It's more or less impossible, from what I can tell, to get the contents of the master's pubkey. This makes programmatic bootstrapping/pre-seeding minions ***exceedingly*** difficult as it either means writing a lot of workaround code OR hard-coding a master pubkey into your code (which I think can be considered silly). While it's possible to get the fingerprint (for use with e.g. `master_finger`), there is no way that I've found through the python API or, by extension, the `netapi` interfaces, to get the master pubkey itself to place in `/etc/salt/pki/minion/minion_paster.pub`.

### Setup
N/A

### Steps to Reproduce Issue
See above.

### Versions Report
```yaml
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10.3
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.3.12
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```
