### ISSUE TITLE
salt-call hangs when finished on FreeBSD

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt#56447]
### Description of Issue
I have ~25 FreeBSD boxes that I manage with salt.
Running ```salt-call -l info state.highstate``` runs as expected, but they all hang after displaying the summary.

For example:
```# salt-call -l info state.highstate

[INFO    ] Syncing output for environment 'base'
[INFO    ] Loading cache from salt://_output, for base)
<snip>
----------
          ID: ntpd
    Function: service.running
      Result: True
     Comment: The service ntpd is already running
     Started: 00:52:07.770502
    Duration: 323.313 ms
     Changes:   

Summary for local
-------------
Succeeded: 90
Failed:     0
-------------
Total states run:     90
Total run time:   51.355 s
```

Hitting CTRL+T shows:
```load: 0.12  cmd: python3.7 29931 [select] 352.94r 43.77u 2.79s 0% 94872k```

### Steps to Reproduce Issue
```salt-call -l info state.highstate```

### Versions Report
```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
        pygit2: Not Installed
         Python: 3.7.6 (default, Jan 30 2020, 01:18:54)
   python-gnupg: Not Installed
         PyYAML: 5.2
          PyZMQ: 18.1.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 12.0-RELEASE-p12
         system: FreeBSD
        version: Not Installed
```
