### ISSUE TITLE
__salt__['nacl.dec'](...) returns bytes on py36 when using the py renderer for a pillar

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#56517]
### Description of Issue
I was retesting all my modules against py36 to make sure there were no issues.
So I upgrade my salt-master to a py36 version of 3000.1...

I noticed one of my py rendere pillar was broken, it deals with nacl encrypted passwords from a db and encodes them as nthash and shadow has for use by the states.

### Setup
Here is a simplified version of what i do

```
#!py
import os
import hashlib
import binascii
nacl_key = '<cryptkeyhere>'

def nthash(password):
  return binascii.hexlify(
    hashlib.new(
      'md4',
      password.encode('utf-16le')
    ).digest()
  ).upper()

def run():
      # NOTE: salt-call --local nacl.enc data=password sk=nacl_key box_type=secretbox
      password_nacl = '<mynaclencryptedpassword>'
      password_clear = __salt__['nacl.dec'](
        data=user['password'],
        sk=nacl['db'],
        box_type='secretbox',
      )
      password_shadow = __salt__['shadow.gen_password'](password_clear, '<saltforshadow>', 'sha256')
      password_nthash = nthash(password_clear)


      return {
        'pwd_shadow': password_shadow,
        'pwd_nthash': password_nthash,
      }

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
```

Adding `.decode("utf-8")` behind the call to nacl.dec fixes the issue.

### Steps to Reproduce Issue
Create a piller file py rendered pillar that calls `nacl.dec` and then tries to use the result expecting a stirng.

### Versions Report
I had to roll back as I broke about 200 hosts when upgrading to py36... this was one issue... other issue needs more investigation... so can't provide the output.

**Comment by sjorge** [comment]
```
[root@cronos /data]# salt-call --versions-report
Salt Version:
           Salt: 3000.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.6.6
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Oct 23 2018, 17:13:47)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```

Had a bit more time this weekend to look at other issues I am having after switching form py27 -> py36... so here is the versions output.
