### ISSUE TITLE
encoding error with gitfs and files with different encoding from global one

### ISSUE THREAD

**Issue by move-z** [saltstack/salt#56521]
### Description of Issue
with salt 3000 on python 3 and a gitfs source, if you try to use a path from git containing a text file in an encoding different from the system one, but that contains valid utf8 (like ascii) in its first 2k, it fails with an error similar to this one:

```
2020-04-03 19:53:22,663 [salt.master      :1846][ERROR   ][61192] Error in function _serve_file:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 1839, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 650, in serve_file
    return self.servers[fstr](load, fnd)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/gitfs.py", line 170, in serve_file
    return _gitfs().serve_file(load, fnd)
  File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 2861, in serve_file
    data = data.decode(__salt_system_encoding__)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 4193: invalid continuation byte
```

### Versions Report
```
Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.5
         Jinja2: 2.10.3
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: 1.1.0
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.4.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.4.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```

**Comment by DmitryKuzmenko** [comment]
Reproduced.
1. I've created two files in a local git repo with this:
```python
f = open('./test_bad_first_2k_.txt', 'wb')
f.write(b'\xe8')
f.close()
f = open('./test_bad_after_2k_.txt', 'wb')
f.write(b'A'*2048)
f.write(b'\xe8')
f.close()
```
Added and committed the files.
2. Added a gitfs backend to the master config
```yaml
fileserver_backend:
  - gitfs
  - roots

gitfs_remotes:
  - file:///home/dimm/projects/salt/git/test_git
```
3. Added a state file to the local root:
```yaml
# issue_56521.sls

File with bad in first 2k:
  file.managed:
    - name: /tmp/test_bad_first_2k.txt
    - source: salt://test_bad_first_2k.txt

File with bad after first 2k:
  file.managed:
    - name: /tmp/test_bad_after_2k.txt
    - source: salt://test_bad_after_2k.txt
```

4. Run `salt-master` and `salt-call state.apply issue_56521`:
```
local:
----------
          ID: File with bad in first 2k
    Function: file.managed
        Name: /tmp/test_bad_first_2k.txt
      Result: True
     Comment: File /tmp/test_bad_first_2k.txt updated
     Started: 16:30:49.853617
    Duration: 40.556 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: File with bad after first 2k
    Function: file.managed
        Name: /tmp/test_bad_after_2k.txt
      Result: False
     Comment: Source file 'salt://test_bad_after_2k.txt' not found
     Started: 16:30:49.894467
    Duration: 53.436 ms
     Changes:   

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
```

So the file containing the "bad" symbol in the beginning works good because Salt detects it as a binary file. The file having the symbol on 2049th's position fails.
The same files work good from localfs.
