### ISSUE TITLE
Rabbitmq module didn't work

### ISSUE THREAD

**Issue by skob** [saltstack/salt#56564]
### Description of Issue

issue opened after #41458 was accidentally closed.

any userchecks in rabbit fail with error:
```
          ID: rabbit_user_admin_present
    Function: rabbitmq_user.present
        Name: admin
      Result: False
     Comment: Error: RabbitMQ command failed: Error: {undef,
                         [{rabbit_auth_backend_internal,check_user_login,
                              [<<"admin">>,[{password,<<"My_pass">>}]],
                              []},
                          {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,669}]},
                          {rpc,'-handle_call_call/6-fun-0-',5,
                              [{file,"rpc.erl"},{line,206}]}]}
     Started: 19:02:25.308927
    Duration: 2220.047 ms
     Changes:   
```
### Setup
```
rabbitmq-server                 3.8.3-1
```

```
rabbit user {{ env }}:
  rabbitmq_user.present:
    - name: {{ aaa.username }}
    - password: {{ aaa.password }}
    - perms:
      - '{{ aaa.vhost }}':
        - '.*'
        - '.*'
        - '.*'
    - require:
      - rabbitmq_vhost: rabbit user {{ env }}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Oct  8 2019, 13:06:37)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-23-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
