### ISSUE TITLE
Rendering Orchestraion SLS Fails Only When Multiple Files are Rendering

### ISSUE THREAD

**Issue by Daemonslayer2048** [saltstack/salt#56607]
### Description of Issue
When rendering multiple Orchestration SLS files the salt master throws "Jinja error: can not serialize 'StrictUndefined'" error.  

### Setup
Setup is a single master and single minion. 
Multiple beacon modules to monitor separate services are used like so:
```YAML
beacons:
  SSH_Service:
    - services:
        sshd:
          onchangeonly: true
    - beacon_module: service
    - disable_during_state_run: True
  Firewall_Service:
    - services:
        firewalld:
          onchangeonly: true
    - beacon_module: service
    - disable_during_state_run: True
  SNMP_Service:
    - services:
        snmpd:
          onchangeonly: true
    - beacon_module: service
    - disable_during_state_run: True
```
Multiple reactor configs watch for their corresponding service beacons like so:
```YAML
reactor:
  - 'salt/minion/*/start':
    - salt://reactor/start/start.sls
  - 'salt/key':
    - salt://reactor/key/minion-accepted.sls
  - 'salt/beacon/*/SNMP_Service/snmpd':
    - salt://reactor/services/snmpd.sls
  - 'salt/beacon/*/Firewall_Service/firewalld':
    - salt://reactor/services/firewalld.sls
  - 'salt/beacon/*/SSH_Service/sshd':
    - salt://reactor/services/sshd.sls
```
Note: the minion start.sls is relevant here.

These reactor SLS's are structured like so:
```YAML
Notify User of SSHd Down:
  runner.state.orchestrate:
    - args:
        - mods: orchestrate.emails.sshd
        - pillar:
            data: {{ data|json }}
```

Finally each orchestration SLS is structured like so: (Snipped and sanitized)
``` YAML
{% set data = salt.pillar.get('data') %}
{% set all_grains = salt['saltutil.runner']('cache.grains', tgt=data['id']) %}

{% if data['sshd']['running'] == False %}
Email User With sshd Failure:
  smtp.send_msg:
      - profile: Email_Profile
      - recipient: "user@domain.com"
      - subject: "sshd is down on {{ data['id'] }}"
      - name: "
      Debug data: \n
      {{ data }}"
{% elif data['sshd']['running'] == True %}
Email User With sshd Up:
  smtp.send_msg:
      - profile: Email_Profile
      - recipient: "user@domain.com"
      - subject: "sshd is up on {{ data['id'] }}"
      - name: "
      Debug data: \n
      {{ data }}"
{% endif %}
```

Each orchestration file renders correctly if individually fired. This can be tested by starting or stoping any of these services individually on a minion. However when a minion starts all of these beacons get sent to the salt master all at once, this is where the orchestration fails. Any number of these will fail, some times only one properly renders sometimes all but one render. 

### Steps to Reproduce Issue
Create multiple beacons, with reactors for each service, each reactor should fire a corresponding orchestration, when a minion starts and places multiple beacons on the master it should fail to render one or more of the orchestration SLS files.  
Here is the render failure log:
```
salt/run/20200410150824730976/ret       {
    "_stamp": "2020-04-10T15:08:31.893932",
    "fun": "runner.state.orchestrate",
    "fun_args": [
        {
            "mods": "orchestrate.emails.firewalld",
            "pillar": {
                "data": {
                    "_stamp": "2020-04-10T15:08:22.060854",
                    "firewalld": {
                        "running": false
                    },
                    "id": "Users_Laptop",
                    "service_name": "firewalld"
                }
            }
        }
    ],
    "jid": "20200410150824730976",
    "return": {
        "data": {
            "SaltStack_master": [
                "Rendering SLS 'base:orchestrate.emails.firewalld' failed: Jinja error: can not serialize 'StrictUndefined' object\nTraceback (most recent call last):\n  File \"/usr/lib/python3.6/site-packages/salt/utils/templates.py\", line 394, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File \"/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py\", line 76, in render\n    return original_render(self, *args, **kwargs)\n  File \"/usr/lib/python3.6/site-packages/jinja2/environment.py\", line 1008, in render\n    return self.environment.handle_exception(exc_info, True)\n  File \"/usr/lib/python3.6/site-packages/jinja2/environment.py\", line 780, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/usr/lib/python3.6/site-packages/jinja2/_compat.py\", line 37, in reraise\n    raise value.with_traceback(tb)\n  File \"<template>\", line 2, in top-level template code\n  File \"/usr/lib/python3.6/site-packages/salt/modules/saltutil.py\", line 1668, in runner\n    full_return=full_return)\n  File \"/usr/lib/python3.6/site-packages/salt/runner.py\", line 158, in cmd\n    full_return)\n  File \"/usr/lib/python3.6/site-packages/salt/client/mixins.py\", line 241, in cmd\n    return self.low(fun, low, print_event=print_event, full_return=full_return)\n  File \"/usr/lib/python3.6/site-packages/salt/client/mixins.py\", line 407, in low\n    mminion=self.mminion,\n  File \"/usr/lib/python3.6/site-packages/salt/utils/job.py\", line 112, in store_job\n    mminion.returners[fstr](load)\n  File \"/usr/lib/python3.6/site-packages/salt/returners/local_cache.py\", line 172, in returner\n    os.path.join(hn_dir, RETURN_P), 'w+b'\n  File \"/usr/lib/python3.6/site-packages/salt/payload.py\", line 233, in dump\n    fn_.write(self.dumps(msg, use_bin_type=True))\n  File \"/usr/lib/python3.6/site-packages/salt/payload.py\", line 193, in dumps\n    return salt.utils.msgpack.packb(msg, default=ext_type_encoder, use_bin_type=use_bin_type)\n  File \"/usr/lib/python3.6/site-packages/salt/utils/msgpack.py\", line 104, in packb\n    return msgpack.packb(o, **_sanitize_msgpack_kwargs(kwargs))\n  File \"/usr/lib64/python3.6/site-packages/msgpack/__init__.py\", line 46, in packb\n    return Packer(**kwargs).pack(o)\n  File \"msgpack/_packer.pyx\", line 284, in msgpack._cmsgpack.Packer.pack\n  File \"msgpack/_packer.pyx\", line 290, in msgpack._cmsgpack.Packer.pack\n  File \"msgpack/_packer.pyx\", line 287, in msgpack._cmsgpack.Packer.pack\n  File \"msgpack/_packer.pyx\", line 234, in msgpack._cmsgpack.Packer._pack\n  File \"msgpack/_packer.pyx\", line 234, in msgpack._cmsgpack.Packer._pack\n  File \"msgpack/_packer.pyx\", line 263, in msgpack._cmsgpack.Packer._pack\n  File \"msgpack/_packer.pyx\", line 234, in msgpack._cmsgpack.Packer._pack\n  File \"msgpack/_packer.pyx\", line 281, in msgpack._cmsgpack.Packer._pack\nTypeError: can not serialize 'StrictUndefined' object\n\n; line 2\n\n---\n{% set data = salt.pillar.get('data') %}\n{% set all_grains = salt['saltutil.runner']('cache.grains', tgt=data['id']) %}    <======================\n\n{% if data['firewalld']['running'] == False %}\nEmail User With firewalld Failure:\n  smtp.send_msg:\n      - profile: Email_Profile\n[...]\n---"
            ]
        },
        "outputter": "highstate",
        "retcode": 1
    },
    "success": false,
    "user": "Reactor"
}

```

### Versions Report
Salt Master:  
```
Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.99.0
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 1.1.1
         Python: 3.6.8 (default, Nov 21 2019, 19:31:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: centos 8.1.1911 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-147.5.1.el8_1.x86_64
         system: Linux
        version: CentOS Linux 8.1.1911 Core
```
Test Minion:
```
Users_Laptop:
    Salt Version:
               Salt: 3000
     
    Dependency Versions:
               cffi: 1.12.3
           cherrypy: Not Installed
           dateutil: 2.8.0
          docker-py: 4.0.2
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.10.3
            libgit2: 0.28.4
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.1
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
       pycryptodome: 3.9.7
             pygit2: 1.0.3
             Python: 3.7.6 (default, Jan 30 2020, 09:44:41)
       python-gnupg: Not Installed
             PyYAML: 5.3
              PyZMQ: 18.0.2
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.3.2
     
    System Versions:
               dist: fedora 31 Thirty One
             locale: UTF-8
            machine: x86_64
            release: 5.5.9-200.fc31.x86_64
             system: Linux
            version: Fedora 31 Thirty One
```
