### ISSUE TITLE
expected bytes-like object, not str while downloading from Artifactory

### ISSUE THREAD

**Issue by moroienius** [saltstack/salt#56660]
### Description of Issue
Since upgrade of python version to 3.6.8.final [artifactory.downloaded ](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.artifactory.html#salt.states.artifactory.downloaded)state stopped working.  
All requests are throwing this error "expected bytes-like object".  
Same formula on python 2.7.5 was working fine. 

### Setup
Salt minion version: "2019.2.3"
Python version: 3.6.8.final .

### Steps to Reproduce Issue
Sample state to run:
```yaml
Download archive file from artifactory:
  artifactory.downloaded:
    - artifact:
       artifactory_url: "{{pillar['artifactory_url']}}"
       repository: "{{ pillar['artifactory_repository']}}"
       group_id: "{{ pillar['artifactory_group_id'] }}"
       artifact_id: "{{ pillar['artifactory_artifact_id'] }}"
       packaging: "{{pillar['artifactory_artifact_packaging']}}"
       version: "{{pillar['artifactory_artifact_version']}}"
       username: "{{ pillar['artifactory_user']}}"
       password: "{{ pillar['artifactory_api_key']}}"
    - target_file: /tmp/file-{{pillar['artifactory_artifact_version']}}.{{pillar['artifactory_artifact_packaging']}}
```

### Versions Report
salt --versions-report
Salt Version:
           Salt: 2019.2.3
Dependency Versions:
           cffi: 1.13.2
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.5
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.28.2
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.6.8 (default, Jun 11 2019, 15:15:01)
   python-gnupg: 0.4.4
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.7 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.7 Maipo
