### ISSUE TITLE
Recursive requisite found, using - name is treated as equivalent to ID

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#5667]
My requirements are simple: Create a file if it does not already exist, and append a line (if the line does not already exist).

I used the following:

<pre>
/testfile:
  file:
    - touch
    - unless:
      - test -f /testfile

Append /testfile:
  file.append:
    - name: /testfile
    - text:
      - 'some text'
    - require:
      - file: /testfile
</pre>

This gives me a "Recursive requisite found" error. Apparently, the " -name: /testfile" line causes the require to fail. Essentially, - name: _appears_ to be treated as an ID. Maybe that's the way Salt is supposed to work, but then take this example:

<pre>
Touch /testfile:
  file.touch:
    - name: /testfile
    - unless:
      - test -f /testfile

Append /testfile:
  file.append:
    - name: /testfile
    - text:
      - 'some text'
    - require:
      - file: Touch /testfile
</pre>

If - name: is the same as the ID, the above should also fail, yet it works fine. I don't see the logic of this behaviour, nor to my colleagues. If this behaviour can be explained, it should ideally be documented somewhere. Otherwise, I'll consider it a bug.

Cheers,
Adam

**Comment by garrickp** [comment]
Got bitten by this bug today.

For what it's worth, the explanation that requisites target either the name or the ID contradicts the [documentation](http://docs.saltstack.com/en/latest/ref/states/highstate.html#requisite-reference), which indicates that only an ID is used for targeting requisites.

**Comment by timcharper** [comment]
I just got bit by this :(

```
xterm-font:
  file.append:
    - name: /home/{{grains.user}}/.Xresources
    - text: |
        xterm*font:     *-fixed-*-*-*-19-*
    - require:
      - file: /home/{{grains.user}}/.Xresources
    - watch_in:
      - cmd: xrdb
xorg:
  pkg.installed

/home/{{grains.user}}/.Xresources:
  file.managed:
    - user: {{grains.user}}
    - mode: 600
xrdb:
  cmd.watch:
    - user: {{grains.user}}
    - name: xrdb -merge {{grains.user}}/.Xresources
    - require:
      - pkg: xorg
      - file: /home/{{grains.user}}/.Xresources
```

Output:

```
----------
          ID: xorg
    Function: pkg.installed
      Result: True
     Comment: Package xorg is already installed.
     Started: 14:59:03.335396
    Duration: 290.398 ms
     Changes:
----------
          ID: /home/scimmia/.Xresources
    Function: file.managed
      Result: True
     Comment: File /home/scimmia/.Xresources exists with proper permissions. No changes made.
     Started: 14:59:03.627602
    Duration: 2.071 ms
     Changes:
----------
          ID: xterm-font
    Function: file.append
        Name: /home/scimmia/.Xresources
      Result: False
     Comment: Recursive requisite found
     Started:
    Duration:
     Changes:
----------
          ID: xrdb
    Function: cmd.watch
        Name: xrdb -merge scimmia/.Xresources
      Result: False
     Comment: One or more requisite failed: custom.xterm-font
     Started:
    Duration:
     Changes:
```

Looks like my xterm-font requirement is being evaluated to refer to itself :( This behavior makes me sad.

**Comment by timcharper** [comment]
Workaround:

```yaml
user-xresources:
  file.managed:
    - name: /home/{{grains.user}}/.Xresources
    - user: {{grains.user}}
    - mode: 600

xterm-font:
  file.append:
    - name: /home/{{grains.user}}/.Xresources
    - text: |
        xterm*font:     *-fixed-*-*-*-19-*
    - require:
      - file: user-xresources
    - watch_in:
      - cmd: xrdb
```

**Comment by ScoreUnder** [comment]
I've run into this yesterday/today. Took a bit of tribulation to figure out why a seemingly straight line of dependencies was treated as a loop:

```yaml
mysqld_running:
  test.nop:
    - name: mysqld

mysql_root_user:
  test.nop:
    - require:
      - mysqld_running

my.cnf:
  test.nop:
    - require:
      - mysql_root_user

mysqld_restart:
  test.nop:
    - name: mysqld
    - watch:
      - my.cnf
```

In my case, I need to start mysql to set the root password, then I need to drop `my.cnf` in *after* setting the root password (otherwise the mysql client ceases to work correctly). However, the `my.cnf` file contains server settings too, so I then need to restart mysql after changing it.

The above test case has been simplified in the hopes that it makes it easier to see that there is no circular dependency, and easier to test whether a fix works or not without having to play with your local filesystem or mysql instance.

My current workaround is to have the restart only, and the first time you run the state you just let most of it fail and run it a second time.

While debugging this issue I hacked this script together: https://gist.github.com/ScoreUnder/6735d45ed85e2e5fb0bf5c9adc18478f
