### ISSUE TITLE
[BUG] pkg.install failed to install/update but install actually suceeded

### ISSUE THREAD

**Issue by briggsy87** [saltstack/salt#56825]
**Description**
After running my sls file below to install .Net 4.8 I get the following:

```
----------
          ID: dotnet48
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: dotnet48
     Started: 10:37:19.089224
    Duration: 169819.811 ms
     Changes:   
              ----------
              dotnet48:
                  ----------
                  install status:
                      success, reboot required
```

**Setup**
cat /srv/salt/win/repo-ng/salt-winrepo-ng/dotnet48.sls
```
dotnet48:
  '4.8.03761':
    full_name: 'Microsoft .NET Framework 4.8'
    installer: 'https://download.visualstudio.microsoft.com/download/pr/014120d7-d689-4305-befd-3cb711108212/1f81f3962f75eff5d83a60abd3a3ec7b/ndp48-web.exe'
    install_flags: '/q /norestart'
    msiexec: False
    locale: en_US
    reboot: False
```
The relevant logs from the minion are the following, and show that it was successful, but I think the 3010 return code is being propagated, and seen as an error:

```
2020-04-22 10:40:08,737 [salt.loaded.int.module.cmdmod:844 ][ERROR   ][2288] retcode: 3010
2020-04-22 10:40:08,799 [salt.state       :322 ][ERROR   ][2288] {'dotnet48': {'install status': 'success, reboot required'}}
```
**Expected behavior**
Expected the install to succeed, like it did, but not report a failure to the master.

**Versions Report**
<details><summary>salt --versions-report</summary>
Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-1036-azure
         system: Linux
        version: Ubuntu 18.04 bionic
</details>

**Additional context**
As mentioned, I believe this is related to the 3010 return code from the installer, that a reboot is required.
