### ISSUE TITLE
pkgrepo.managed doesn't add GPG key if repo is present in sources.list

### ISSUE THREAD

**Issue by lllamnyp** [saltstack/salt#56828]
**Description**
Essentially the title. When `pkgrepo.managed` has the `key_url` key, it will not necessarily import the gpg key if the entry for the repository is already present in `/etc/apt/sources.list`

**Setup**
```
install_docker:
  pkgrepo.managed:
    - humanname: Docker CE Repository
    - name: deb https://artifactory.company.com/debian-docker-remote/ubuntu/ bionic stable
    - key_url: https://artifactory.company.com/debian-docker-remote/ubuntu/gpg
    - refresh: True
    - require_in:
      - pkg: docker-ce
  pkg.installed:
    - name: docker-ce
    - pkgs:
      - docker-ce: {{ salt['pillar.get']('docker:version', '5:19.03.*') }}
      - docker-ce-cli: {{ salt['pillar.get']('docker:version', '5:19.03.*') }}
    - hold: True
    - refresh: True
```

**Steps to Reproduce the behavior**
Grab a server that didn't have relevant gpg keys imported and do
```
# echo deb https://download.docker.com/linux/ubuntu bionic stable >> /etc/apt/sources.list
```
then apply the above state (you can substitute `artifactory.company.com/debian-docker-remote` for `download.docker.com/linux`).

The minion will report that the repo is already configured.
Docker will not be installed due to the absence of keys for the repo. 

If you then delete the relevant line from `/etc/apt/sources.list` and try again, the key is imported and docker installs.

**Expected behavior**
Salt (somehow) recognizes the absence of the key and imports it into the keyring. The subsequent package installation is then successful.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.3.0-43-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

**Comment by alexey-zhukovin** [comment]
@lllamnyp
Could you provide working `.sls` file, 
I can't reproduce.

**Comment by alexey-zhukovin** [comment]
@lllamnyp thank you!
I tried to reproduce this issue:

1. I created SLS 
install_docker.sls
```
install_docker:
  pkgrepo.managed:
    - humanname: Docker CE Repository
    - name: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    - key_url:  https://download.docker.com/linux/ubuntu/gpg
    - refresh: True
    - require_in:
      - pkg: docker-ce
  pkg.installed:
    - name: docker-ce
    - pkgs:
      - docker-ce: {{ salt['pillar.get']('docker:version', '5:19.03.*') }}
      - docker-ce-cli: {{ salt['pillar.get']('docker:version', '5:19.03.*') }}
    - hold: True
    - refresh: True
```
2. Add `deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable` into /etc/apt.sources
3. Execute state file.
Result:
`installed docker-ce`

```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Oct  7 2019, 17:39:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-55-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

Please correct me if I am wrong.
