### ISSUE TITLE
[BUG] win_pkg.list_pkgs not detecting software

### ISSUE THREAD

**Issue by per-lind** [saltstack/salt#56864]
**Description**
salt.modules.win_pkg.list_pkgs does not detect installed package where the registry value UninstallString is missing but NoRemove is set to 1.

It is expected that UninstallString should be missing when NoRemove is set per https://docs.microsoft.com/en-us/windows/win32/msi/arpnoremove

This will also give problem installing the application as it is never detected as installed.

**Setup**
salt-call pkg.list_pkgs

**Steps to Reproduce the behavior**
Install a software with this behaviour or manually edit the registry to mimic it by removing the UninstallString reg value in Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\"Application" and creating a NoRemove DWORD with value 1

**Expected behavior**
Application should still be detected.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2019Server
         system: Windows
        version: 2019Server 10.0.17763 SP0 Multiprocessor Free
```
</details>

**Additional context**
I have tracked this down to 
```def skip_uninstall_string(hive, key, sub_key, use_32bit_registry):``` https://github.com/saltstack/salt/blob/286fa7650f796a48add91d76266732a2ee8eb626/salt/modules/win_pkg.py#L556
