### ISSUE TITLE
virtual grain on debian buster is "physical" instead of "kvm"

### ISSUE THREAD

**Issue by TimidRobot** [saltstack/salt#56885]
**Description**
Virtual grain on debian buster ami is "physical" instead of "kvm".

Comparison of two EC2 instances:
```shell
sudo salt --out=yaml c\*__stage__\* grains.item osfinger pythonexecutable virtual meta-data:ami-id meta-data:instance-type
```
```yaml
ccengine__stage__us-east-2:
  meta-data:ami-id: ami-05d9978d11a05da49
  meta-data:instance-type: t3.small
  osfinger: Debian-10
  pythonexecutable: /usr/bin/python3
  virtual: physical
chapters__stage__us-east-2:
  meta-data:ami-id: ami-0b8193ae73862dccd
  meta-data:instance-type: t3.medium
  osfinger: Debian-9
  pythonexecutable: /usr/bin/python2
  virtual: kvm
```

**Expected behavior**
Virtual machines should be identified correctly

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.12 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-12-amd64
         system: Linux
        version: debian 9.12
```
</details>

**Additional context**
The State and Pillar files are publicly accessible (secrets are encrypted): [creativecommons/sre-salt-prime](https://github.com/creativecommons/sre-salt-prime)
