### ISSUE TITLE
[BUG] SALT.STATES.NETWORK doesn't allow hwaddr to be managed

### ISSUE THREAD

**Issue by zieba88** [saltstack/salt#56910]
**Description**
SALT.STATES.NETWORK doesn't allow hwaddr to be managed.

**Setup**
```
eth0:
  network.managed:
    - enabled: True
    - type: eth
    - proto: none
    - onboot: yes
    - peerdns: no
    - ipaddr: 192.168.1.100
    - netmask: 255.255.255.0
    - gateway: 192.168.1.1
    - hwaddr: 00:00:00:00:00
```

**Steps to Reproduce the behavior**
running `state.sls` does not add hwaddr.

**Expected behavior**
It should add hwaddr for the interface.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov 21 2019, 19:31:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 8.1.1911 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-147.5.1.el8_1.x86_64
         system: Linux
        version: CentOS Linux 8.1.1911 Core
```
</details>

**Additional context**
