### ISSUE TITLE
How to modify default options in Salt Minion config file from Master

### ISSUE THREAD

**Issue by Mahboubi68** [saltstack/salt#56936]
### Description of Issue

I want to set "grains_cache" variable to "True" from Salt Master on all Minions. This variable is from default options that exist in minion config file and cannot be overridden by pillar data. So how can I set variables (for example "grains_cache", "grains_cache_expiration" or "log_file") from Master?

**Comment by twangboy** [comment]
You could probably do a `file.replace` on the minion config file or a `file.append` if it's something that's not already there. Then restart the minion service.

You could also add a file with the setting to the `minion.d` directory. Those take precedence over the minion config file itself. Then restart the service.

```
update_minion_config:
  file.managed:
    - name: /etc/salt/conf/minion.d/grains.conf
    - contents:
      - grains_cache: False
      - grains_refresh_every: 30
      - log_file: /var/log/salt/minion

restart_minion_on_change:
  service.running:
    - watch:
      - file: /etc/salt/conf/minion.d/grains.conf
```

Maybe something like that ^^^
