### ISSUE TITLE
[BUG] docker_image.present interface does not match docs

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#56956]
**Description**

See https://docs.saltstack.com/en/latest/ref/states/all/salt.states.docker_image.html#salt.states.docker_image.present

Specifically,

> **saltenv**
>
>    Specify the environment from which to retrieve the SLS indicated by the mods parameter.
>
>    New in version 2017.7.0.
>
>    Changed in version 2018.3.0: Now uses the effective saltenv if not explicitly passed. In earlier versions, base was assumed as a default.

and

> **sls**
>
>    Allow for building of image with docker.sls_build by specifying the SLS files with which to build. This can be a list or comma-seperated string.

**Setup**

```yaml
# docker_test.sls

docker.io:
  pkg.installed

my/client:
  docker_image.present:
    - tag: latest
    - base: python:3.7-slim
    - sls:
      - foo
      - bar
    - require:
        - pkg: docker.io

my/server:
  docker_image.present:
    - tag: latest
    - base: python:3.7-slim
    - sls: foo, bar
    - require:
        - pkg: docker.io
```

State `my/client` fails with the below. Documentation says a list should be acceptable.
```
      ID: my/client
    Function: docker_image.present
      Result: False
     Comment: Encountered error using SLS ['foo', 'bar'] for building f0cal/client:latest: 'list' object has no attribute 'split'
     Started: 18:16:09.821914
    Duration: 11112.903 ms
     Changes:   

```

State `my/server` fails with the below. Documentation says the current `saltenv` should be default instead of `base`.

```
[DEBUG   ] stdout: {
    "local": {
        "jid": "20200428214409369175",
        "return": [
            "No matching sls found for 'foo' in env 'base'",
            "No matching sls found for 'bar' in env 'base'"
        ],
        "retcode": 0,
        "out": "highstate",
        "id": "f4c76b8f0f37",
        "fun": "state.pkg",
        "fun_args": [
            "/tmp/salt.docker.e95f8c/salt_state.tgz",
            "e7e00f8ca7b9c69c01325643e5f6cf828565498592f504ce96a2701dc9032b1b",
            "sha256"
        ]
    }
}

```

**Steps to Reproduce the behavior**
`salt-call --local state.sls docker_test saltenv=docker-test-env`

**Expected behavior**
States `my/client` and `my/server` succeed in populating docker images.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
```
Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: 4.2.0
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.7 (default, Apr 18 2020, 02:59:53)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: Ubuntu 20.04 focal
         locale: UTF-8
        machine: x86_64
        release: 5.4.0-26-generic
         system: Linux
        version: Ubuntu 20.04 focal
 
```
</details>

**Additional context**
N/A
