### ISSUE TITLE
[BUG] yum package module looking for wrong versionlock package on RHEL/CentOS 8

### ISSUE THREAD

**Issue by erobeson** [saltstack/salt#56994]
**Description**
When hold or update_holds are used in a pkg.installed state on RHEL/CentOS 8 the state run fails, saying that yum-plugin-versionlock package is not installed. However, RHEL/CentOS 8 use DNF and the package it should be looking for is named python3-dnf-plugin-versionlock, not yum-plugin-versionlock.

**Setup**
Run this state against a RHEL/CentOS 8 system with python3-dnf-plugin-versionlock package installed:

```
salt-minion-pkg:
  pkg.installed:
    - pkgs:
      - salt
      - salt-minion
    - hold: True
    - update_holds: True
```

**Steps to Reproduce the behavior**

```
# salt minion grains.get osfinger
minion:
    CentOS Linux-8

# salt minion cmd.run 'yum versionlock list'
minion:
    salt-minion-0:2019.2.3-1.el8.*
    salt-0:2019.2.3-1.el8.*

# cat pkg.sls 
salt-minion-pkg:
  pkg.installed:
    - pkgs:
      - salt
      - salt-minion
    - hold: True
    - update_holds: True

# salt minion state.apply pkg
minion:
----------
          ID: salt-minion-pkg
    Function: pkg.installed
      Result: False
     Comment: Cannot proceed, yum-plugin-versionlock is not installed.
     Started: 23:19:44.364645
    Duration: 1671.667 ms
     Changes:   

Summary for minion
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   1.672 s
ERROR: Minions returned with non-zero exit code

# salt minion pkg.info_installed python3-dnf-plugin-versionlock
minion:
    ----------
    python3-dnf-plugin-versionlock:
        ----------
        arch:
            noarch
        build_date:
            2019-11-12T15:43:42Z
        build_date_time_t:
            1573573422
        build_host:
            aarch64-02.mbox.centos.org
        description:
            Version lock plugin takes a set of name/versions for packages and excludes all other
            versions of those packages. This allows you to e.g. protect packages from being
            updated by newer versions.
        group:
            Unspecified
        install_date:
            2020-04-29T19:23:18Z
        install_date_time_t:
            1588188198
        license:
            GPLv2+
        packager:
            CentOS Buildsys <bugs@centos.org>
        release:
            3.el8
        relocations:
            (not relocatable)
        signature:
            RSA/SHA256, Thu Dec  5 03:05:29 2019, Key ID 05b555b38483c65d
        size:
            20647
        source:
            dnf-plugins-core-4.0.8-3.el8.src.rpm
        summary:
            Version Lock Plugin for DNF
        url:
            https://github.com/rpm-software-management/dnf-plugins-core
        vendor:
            CentOS
        version:
            4.0.8
```

**Expected behavior**
Since versionlock is installed, state should succeed when hold or update_holds is used.

**Screenshots**

**Versions Report**
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

<details><summary>salt --versions-report</summary>

```
Minion:
    Salt Version:
               Salt: 2019.2.3

    Dependency Versions:
               cffi: 1.11.5
           cherrypy: Not Installed
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.35.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.2
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: Not Installed
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.6.8 (default, Nov 21 2019, 19:31:34)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 17.0.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.2
                ZMQ: 4.3.2
    
    System Versions:
               dist: centos 8.1.1911 Core
             locale: UTF-8
            machine: x86_64
            release: 4.18.0-147.5.1.el8_1.x86_64
             system: Linux
            version: CentOS Linux 8.1.1911 Core

```

</details>

<details><summary>salt --versions-report</summary>

```
Master:
Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: 1.13.2
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.5
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.28.4
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 1.0.3
         Python: 3.6.8 (default, Jun 11 2019, 15:15:01)
   python-gnupg: 0.4.4
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.7 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.7 Maipo
```
</details>

**Additional context**
It looks like the yumpkg module picks the versionlock package name based on the osmajorversion grain value. It has the correct package name set for an osmajorversion that looks like it is used by Fedora, but needs to be updated to use that same package name for RHEL/CentOS 8.
