### ISSUE TITLE
Failed to load function git.envs because its module (git) is not in the whitelist: ['gitfs', 'roots']

### ISSUE THREAD

**Issue by bsoldhogg** [saltstack/salt#57008]
@terminalmage 
**Description**
 Running the fileserver runner produces the following error:

```
# salt-run fileserver.update backend=git
[ERROR   ] Failed to load function git.envs because its module (git) is not in the whitelist: ['gitfs', 'roots']
[ERROR   ] Failed to load function g.envs because its module (g) is not in the whitelist: ['gitfs', 'roots']
True
```

**Setup**

trimmed master config

```
# /etc/salt/master
fileserver_backend:
  - git
  - roots

gitfs_remotes:
  - https://user:token@gitlab.com/config-management/salt-config.git:
    - name: name
    - root: folder
    - mountpoint: folder
- https://user:token@gitlab.com/config-management/salt-config.git:
    - name: name2
    - root: folder2
    - mountpoint: folder2

ext_pillar:
  - git:
    - master https://user:token@gitlab.com/config-management/salt-pillar-shared.git:
      - root: pillar
      - env: __env__
```

**Steps to Reproduce the behavior**
I have tried pygit2 and gitpython, same error. I found others with this issue reporting that manually installing pygit via pip was the way to go so I have run the following but it made no different (and isn't reported as the version installed)

`pip3 install --target=/usr/lib/python3.6/site-packages --ignore-installed pygit2==0.28.0`

Also changed gitfs to git in fileserver_backend.

**Versions Report**

```
Salt Version:
           Salt: 3000.1

Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-96-generic
         system: Linux
        version: Ubuntu 18.04 bionic

```

**Additional context**
In my lab, running the same version of Salt but on py2 this setup **does** work. Here's the version output

```
Salt Version:
           Salt: 3000.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.17 (default, Apr 15 2020, 17:20:14)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-88-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
