### ISSUE TITLE
Create VMs with disks on volume disks

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#57005]
**Is your feature request related to a problem? Please describe.**

When using the `virt.running()` state or the `virt.init()` / `virt.update()` functions to create a VM, the disks are assumed to be files. This is rather file for qcow2 or raw files stored locally or on a mounted share, but this is not enough to use an iSCSI or RBD storage pool for instance.

**Describe the solution you'd like**

A state like the following would create a VM with the `data` disk being on an RBD volume:
```yaml
myvm:
  virt.running:
    - name: mvvm
    - cpu: 1
    - mem: 512
    - disks:
      - name: system
        pool: default 
        image: /var/testsuite-data/disk-image-template.qcow2
        size: 122880
      - name: data
        model: virtio
        format: raw
        pool: test-rbd
        size: 512
```

For this to work, the pool property would have to be an existing libvirt storage pool name. This would not only allow using RBD volumes as disks, but also LVM, disk partitions or iSCSI volumes.

**Describe alternatives you've considered**

Calling `virt.define_xml_str()` with a custom computed XML would do the job, but it's way simpler for users once integrated with the `virt.defined` and `virt.running` states.
