### ISSUE TITLE
[BUG] metadata_server_grains not working with Openstack MultiPartMime/SoftwareConfig user-data

### ISSUE THREAD

**Issue by klippo** [saltstack/salt#57000]
**Description**
metadata_server_grains is not working with Openstack user-data when using `user_data_format: SOFTWARE` config in HOT (Heat Orchestration Template)

**Setup**
Example HOT:
```
  server:
    type: OS::Nova::Server
    properties:
      name: server01
      image: CentOS 7
      flavor: m1.large
      key_name: key
      user_data_format: SOFTWARE_CONFIG
      user_data: { get_resource: server_init }

  server_init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: {get_resource: server_config_one}
        - config: {get_resource: server_config_two}

  server_config_one:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
         echo "one"

  server_config_two:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
         echo "two"
```
minion config:
```
---
master: salt-master01
metadata_server_grains: true
mine_functions:
    grains.item:
    - fqdn
    - fqdn_ip4
    - ipv4
    - roles
...
```
INFO: I've modified `metadata.py` to print which line causes the error.

When running `salt-minion -l debug` and seeing the debug log when fetching metadata grains the followin error occurs
```Content-Type: multipart/mixed; boundary="===============2238913556147678330=="
[CRITICAL] Failed to load grains defined in grain file metadata.metadata in function <function metadata at 0x7f429d865b18>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 780, in grains
    ret = funcs[key]()
  File "/usr/lib/python2.7/site-packages/salt/grains/metadata.py", line 89, in metadata
    return _search()
  File "/usr/lib/python2.7/site-packages/salt/grains/metadata.py", line 67, in _search
    ret[line] = _search(prefix=os.path.join(prefix, line + '/'))
  File "/usr/lib/python2.7/site-packages/salt/grains/metadata.py", line 72, in _search
    key, value = line.split('=')
ValueError: too many values to unpack
```
This causes the metadata grain to never be populated.
***Example Output from metadata api***
`curl 169.254.169.254/latest/user-data`
```
Content-Type: multipart/mixed; boundary="===============5136539826257922680=="
MIME-Version: 1.0
--===============5136539826257922680==
Content-Type: text/cloud-config; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="cloud-config"
```

**Versions Report**
```
 Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 4.2.0
          gitdb: 4.0.4
      gitpython: 3.1.1
         Jinja2: 2.11.1
        libgit2: 0.26.8
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: 3.0.2
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.18.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```
