### ISSUE TITLE
Salt scheduler run_on_start once did not run when the minion is starting

### ISSUE THREAD

**Issue by AmiramMaimon** [saltstack/salt#57064]
Hey,
When using the state schedule.present with run_on_start:True the function does not run when the minion service is starting.

```
schedule-test:
  schedule.present:
    - function: state.sls
    - job_args:
        - test
    - maxrunning: 1
    - run_on_start: True
    - enabled: True
    - persist: True

```

The content of the /etc/salt/minion.d/_schedule.conf file:

```
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false, run_on_start: true}
  schedule-test:
    args: [test]
    enabled: true
    function: state.sls
    jid_include: true
    maxrunning: 1
    name: schedule-test
    run_on_start: true
```

**Minion version:**

> Salt Version:
>            Salt: 3000
> 
> Dependency Versions:
>            cffi: 1.14.0
>        cherrypy: Not Installed
>        dateutil: 2.4.2
>       docker-py: 4.2.0
>           gitdb: Not Installed
>       gitpython: Not Installed
>          Jinja2: 2.8
>         libgit2: Not Installed
>        M2Crypto: Not Installed
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.6.2
>    mysql-python: Not Installed
>       pycparser: 2.20
>        pycrypto: 2.6.1
>    pycryptodome: Not Installed
>          pygit2: Not Installed
>          Python: 3.5.2 (default, Oct  8 2019, 13:06:37)
>    python-gnupg: 0.3.8
>          PyYAML: 3.11
>           PyZMQ: 15.2.0
>           smmap: Not Installed
>         timelib: Not Installed
>         Tornado: 4.5.3
>             ZMQ: 4.1.4
> 
> System Versions:
>            dist: Ubuntu 16.04 xenial
>          locale: UTF-8
>         machine: x86_64
>         release: 4.4.0-176-generic
>          system: Linux
>         version: Ubuntu 16.04 xenial

**Master Version:**

> Salt Version:
>            Salt: 3000
>  
> Dependency Versions:
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: 2.4.2
>       docker-py: Not Installed
>           gitdb: 0.6.4
>       gitpython: 1.0.1
>          Jinja2: 2.8
>         libgit2: Not Installed
>        M2Crypto: Not Installed
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.6.2
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>    pycryptodome: Not Installed
>          pygit2: Not Installed
>          Python: 3.5.2 (default, Oct  8 2019, 13:06:37)
>    python-gnupg: 0.3.8
>          PyYAML: 3.11
>           PyZMQ: 15.2.0
>           smmap: 0.9.0
>         timelib: Not Installed
>         Tornado: 4.5.3
>             ZMQ: 4.1.4
>  
> System Versions:
>            dist: Ubuntu 16.04 xenial
>          locale: UTF-8
>         machine: x86_64
>         release: 4.4.0-176-generic
>          system: Linux
>         version: Ubuntu 16.04 xenial
>

**Comment by waynew** [comment]
How do you know it's not starting?

I'm unable to reproduce this, when I change my log level to debug, I see that my minion does appear to be starting this job...

**Comment by AmiramMaimon** [comment]
I change the log level to `debug`.

looking on the following line:

> [2020-05-13 09:33:41.826] [salt.utils.event] [DEBUG]  Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {'_stamp': '2020-05-13T06:33:41.826645', 'schedule': {'__mine_interval': {'enabled': True, 'jid_include': True, 'return_job': False, 'maxrunning': 2, 'function': 'mine.update', 'minutes': 60, 'run_on_start': True}, 'schedule-test': {'enabled': True, 'jid_include': True, 'name': 'schedule-test', 'maxrunning': 1, 'function': 'state.sls', 'args': ['test'], 'run_on_start': True}}, 'complete': True}

It seems that the sls run, but it didn't.
This is the `test.sls`:
```
echo `date` > /root/test.sls :
  cmd.run: []
```
and this is the `/etc/salt/minion.d/_schedule.conf`:
```
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false, run_on_start: true}
  schedule-test:
    args: [test]
    enabled: true
    function: state.sls
    jid_include: true
    maxrunning: 1
    name: schedule-test
    run_on_start: true
```

After reboot/service restart I search the `/root/` folder for the `test.sls` file with no success:
```
root@Server01:~# service salt-minion restart
root@Server01:~# ls -l
total 0
root@Server01:~#
```

I expected it to work because:
```
root@Server01:~# salt-call state.apply test
local:
----------
          ID: echo `date` > /root/test.sls
    Function: cmd.run
      Result: True
     Comment: Command "echo `date` > /root/test.sls" run
     Started: 09:43:37.328579
    Duration: 6.451 ms
     Changes:
              ----------
              pid:
                  2786
              retcode:
                  0
              stderr:
              stdout:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   6.451 ms
root@Server01:~# ls -l
total 4
-rw-r--r-- 1 root root 30 May 13 09:43 test.sls
root@Server01:~#
```
