### ISSUE TITLE
init.sls alters pkg.installed order [BUG]

### ISSUE THREAD

**Issue by bsoldhogg** [saltstack/salt#57215]
**Description**

I have a state which installs a piece of software in a particular order when the state is applied directly. When included as part of an init.sls, the pkgs order is reversed as far as I can tell.

**Setup**
**tools/software.sls**
```
install_software:
  pkg.installed:
    - pkgs:
      - setup1: {{ tooling['versions']['setup1_version'] }}
      - setup2: {{ tooling['versions']['setup2_version'] }}
      - setup3: {{ tooling['versions']['agent_version'] }}
```

When I run `salt 'minion' state.apply tools.software` the pkgs are installed in order of setup1,2,3

When I use tools/init.sls to include software.sls, the installation order of these pkgs is reversed, which causes it to fail.

**Expected behavior**
I would expect the states included in the init.sls to run in the same order as they do when run independently.

**Versions Report**

```
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.17 (default, Apr 15 2020, 17:20:14)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-88-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

**Comment by garethgreenaway** [comment]
@bsoldhogg Thanks for the report.  Unfortunately behind the scenes we're getting a list from YAML and cannot guarantee the order of the packages that we receive.  Additionally the underlying packaging system will also install things using it's own logic. If you need to guarantee the order that these packages are installed you should definitely use the requisite systems.  Using your provided state as an example, something like this:
```
setup1:
  pkg.installed:
    - version: {{ tooling['versions']['setup1_version'] }}

setup2:
  pkg.installed:
    - version:  {{ tooling['versions']['setup2_version'] }}
    - require:
         - pkg: setup1

setup3:
  pkg.installed:
    - version: {{ tooling['versions']['agent_version'] }}
    - require:
         - pkg: setup1
         - pkg: setup2
```

Here setup3 requires that setup1 and setup1 are installed before Salt attempts to install setup2, and setup2 requires that setup1 is already installed before setup2 is installed.
