### ISSUE TITLE
task.create_task fails on windows when run from orch.[BUG]

### ISSUE THREAD

**Issue by wb529kq** [saltstack/salt#57224]
**Description**
When I run the module task.create_task from the cli it works. When i try to run it using salt-function in an orchestration it fails.

**Setup**
Works ...
`salt -C \*blah* task.create_task salt-migrate user_name=System force=True action_type=Execute cmd='c:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe' arguments='c:\\temp\\migrate.ps1' start_in='c:\\temp'`

Fails ...
`salt-run state.orch orch.minion.create_task pillar='{"target": "blah"}'`
```
# Set Target
{% set target = salt['pillar.get']('target',) %}

# Run a service to delete the master Public Key and restart salt-minion
run_task:
  salt.function:
    - name: task.create_task
    - tgt: {{ target }}
    - arg:
      - salt_migrate
      - user_name: System
      - force: True
    - kwargs:
        action_type: Execute
        cmd: 'c:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe'
        arguments: 'c:\\temp\\migrate.ps1'
        start_in: 'c:\\temp'
```

**Steps to Reproduce the behavior**
run ...
`salt-run state.orch orch.minion.create_task pillar='{"target": "blah"}'`

**Expected behavior**
That it would create the same scheduled task on windows that the module creates on the command line.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Master:
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: 1.13.2
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.5
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.9.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

Minion:
    Salt Version:
               Salt: 3000.2

    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.8.1
             pygit2: Not Installed
             Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 5.1.2
              PyZMQ: 18.0.1
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2019Server
             system: Windows
            version: 2019Server 10.0.17763 SP0 Multiprocessor Free

```
</details>

**Additional context**
```
----------
          ID: run_task
    Function: salt.function
        Name: task.create_task
      Result: False
     Comment: Running function task.create_task failed on minions: dtdeaugas429.md-man.biz Function task.create_task ran on dtdeaugas429.md-man.biz.
     Started: 17:32:03.768148
    Duration: 8353.18 ms
     Changes:
              dtdeaugas429.md-man.biz:
                  The minion function caused an exception: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\minion.py", line 1676, in _thread_return
                  return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\executors\direct_call.py", line 12, in execute
                  return func(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\modules\win_task.py", line 538, in create_task
                  if name in list_tasks(location) and not force:
                File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\modules\win_task.py", line 352, in list_tasks
                  task_folder = task_service.GetFolder(location)
                File "<COMObject Schedule.Service>", line 2, in GetFolder
              pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024773), None)


Summary for saltmaster-open_master
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:   8.353 s
```

**Comment by DmitryKuzmenko** [comment]
@wb529kq could you please try to change your state to this one?
```yaml
run_task:
  salt.function:
    - name: task.create_task
    - tgt: {{ target }}
    - arg:
      - salt_migrate
    - kwarg:
        user_name: System
        force: True
        action_type: Execute
        cmd: 'c:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe'
        arguments: 'c:\\temp\\migrate.ps1'
        start_in: 'c:\\temp'
```
I've moved all keyword arguments to kwargs section and renamed `kwargs` to `kwarg`. This should work.
