### ISSUE TITLE
Shared object not found when run through cmd.run 

### ISSUE THREAD

**Issue by silenius** [saltstack/salt#57223]
**Description**
```
I have a state with a cmd.run command which fail with:
----------                                          
          ID: srv_jetty_module_jndi_ini                
    Function: cmd.run                                                                                                                         
        Name: /usr/local/openjdk8/bin/java -jar start.jar --add-to-start=jndi              
      Result: False                                     
     Comment: Command "/usr/local/openjdk8/bin/java -jar start.jar --add-to-start=jndi" run                    
     Started: 16:50:20.334125                             
    Duration: 148.536 ms                                  
     Changes:                                                     
              ----------                                     
              pid:                                                                                                                            
                  19886                                       
              retcode:                                                                                                                        
                  1
              stderr:                                                                                                                         
                  ld-elf.so.1: Shared object "libjli.so" not found, required by "java"
              stdout:                                    
```

If I'm running the corresponding command by hand in a shell it works. I'm not sure why the shared object is not found through cmd.run...

The state.show_sls of the corresponding state file is:

```yaml
    srv_jetty_module_plus_ini:
        ----------
        __env__:
            base
        __sls__:
            geoserver.jetty.modules
        cmd:
            |_
              ----------
              name:
                  /usr/local/openjdk8/bin/java -jar start.jar --add-to-start=plus
            |_
              ----------
              cwd:
                  /usr/local/geoserver/srv/geoserver-2.16.2
            |_
              ----------
              runas:
                  geoserver
            |_
              ----------
              env:
                  |_
                    ----------
                    JAVA_HOME:
                        /usr/local/openjdk8
                  |_
                    ----------
                    JAVA_OPTS:
                        -server -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Xmx2048m -Xms2048m -Dorg.apache.jasper.compiler.Parser.STRICT_QUOTE_ESCAPING=false
            |_
              ----------
              require:
                  |_
                    ----------
                    file:
                        srv_jetty_module_plus_config
            - run
            |_
              ----------
              order:
                  10024

```

**Setup**

This is with:

```
root@geoserver1:/usr/local/geoserver/srv/geoserver-2.16.2 # pw user show geoserver
geoserver:*:35003:35003::0:0:User &:/nonexistent:/usr/sbin/nologin
```

```
root@geoserver1:/usr/local/geoserver/srv/geoserver-2.16.2 # ldd /usr/local/openjdk8/bin/java
/usr/local/openjdk8/bin/java:
        libjli.so => /usr/local/openjdk8/bin/../lib/amd64/jli/libjli.so (0x800672000)
        libz.so.6 => /lib/libz.so.6 (0x800683000)
        libthr.so.3 => /lib/libthr.so.3 (0x80069d000)
        libc.so.7 => /lib/libc.so.7 (0x80024a000)
```

```sls
{{ instance }}_jetty_module_{{ module }}_ini:
  cmd.run:
    - name: {{ config.jdk_conf.JAVA_HOME | path_join('bin', 'java') }} -jar start.jar --add-to-start={{ module }}
    - cwd: {{ config.GEOSERVER_HOME }}
    - runas: {{ config.user }}
    - env:
      - JAVA_HOME: {{ config.jdk_conf.JAVA_HOME }}
      - JAVA_OPTS: {{ config.jdk_conf.JAVA_OPTS }}
    - require:
      - file: {{ instance }}_jetty_module_{{ module }}_config
```

**Versions Report**
This is with:
```
root@salt1:/data/formulas/geoserver-formula/geoserver # salt --versions-report
Salt Version:
           Salt: 2019.2.4
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.7 (default, Apr  2 2020, 08:11:04)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 12.1-RELEASE-p3
         system: FreeBSD
        version: Not Installed
```
