### ISSUE TITLE
[BUG] git.latest fails with permission error on macOS when using identity file and non-standard user

### ISSUE THREAD

**Issue by taranlu-houzz** [saltstack/salt#57233]
**Description**
When using `git.latest` I get a permission error if using the `user` parameter combined with the `identity` parameter.

```
----:
----------
          ID: states.git.clone_---- - Clone ---- repo or pull latest
    Function: git.latest
        Name: git@github.com:----
      Result: False
     Comment: Failed to check remote refs: Unable to authenticate using identity file:

              git@github.com: Permission denied (publickey).
              fatal: Could not read from remote repository.

              Please make sure you have the correct access rights
              and the repository exists.
     Started: 17:22:17.809552
    Duration: 1664.535 ms
     Changes:
```

**Setup**
sls file that fails:
```yaml
{{ sls }} - Clone ---- repo or pull latest:
  git.latest:
    - name: git@github.com:----
    - target: {{ pillar['minion_home'] }}/git/----
    - user: {{ pillar['minion_user'] }}
    - branch: master
    - identity: salt://data/ssh/----_deploy_key
    - force_checkout: True
    - force_fetch: True
    - force_reset: remote-changes
```

sls file that works (but clones/updates repo as root):
```yaml
{{ sls }} - Clone ---- repo or pull latest:
  git.latest:
    - name: git@github.com:----
    - target: {{ pillar['minion_home'] }}/git/----
    - branch: master
    - identity: salt://data/ssh/----_deploy_key
    - force_checkout: True
    - force_fetch: True
    - force_reset: remote-changes
```
- `minion_user` is just a different user than root in this case
- `minion_home` is the above user's home directory

**Expected behavior**
The repo should be cloned/updated to latest correctly by the user specified using the `user` parameter.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3000.1

Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.15
         Jinja2: 2.10.1
        libgit2: 1.0.0
       M2Crypto: 0.35.2
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.1
   pycryptodome: Not Installed
         pygit2: 1.2.0
         Python: 3.7.7 (default, Mar 10 2020, 15:43:27)
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 3.0.2
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 17.7.0
         system: Darwin
        version: 10.13.6 x86_64
```
</details>

**Additional context**
This seems like it might be related to: #42550
