### ISSUE TITLE
[FEATURE REQUEST] COPR support in pkgrepo

### ISSUE THREAD

**Issue by mymindstorm** [saltstack/salt#57258]
**Describe the solution you'd like**
An option for pkgrepo that can mange COPR repos on RedHat based systems. E.g.

```yaml
hello-copr:
    pkgrepo.managed:
      - copr: mymindstorm/hello
```

It would be a lot nicer to be able to just specify the repo in pkgrepo.managed instead of manually doing things.

**Describe alternatives you've considered**
- Manually downloading the repo file from COPR
- Running `dnf/yum copr enable <repo>`

**Additional context**
Salt already has the same feature for PPAs.

I have already written some code for this, I will submit a PR soon.
