### ISSUE TITLE
[BUG] win_iis state module not redacting passwords

### ISSUE THREAD

**Issue by MadillJ** [saltstack/salt#57285]
**Description**
I am using the `win_iis.container_setting` function to set the identity for app pools and noticed that the output when changed is including the password in plain text.

**Setup**
```
MyAppPool:
  win_iis.create_apppool:
    - name: {{ pillar['website-name'] }}

MyAppPool-Identity:
  win_iis.container_setting:
    - name: {{ pillar['website-name'] }}
    - container: AppPools
    - settings:
        processModel.userName: {{ pillar['user-domain'] }}\{{ pillar['user-name'] }}
        processModel.password: {{ pillar['user-password'] }}
        processModel.identityType: SpecificUser
    - require: 
      - win_iis: MyAppPool
```

I'm not sure if it matters, but in my case the password in the pillar file is encrypted using gpg.

**Steps to Reproduce the behavior**
Ensure app pool either does not exist, or is using a different identity.
Apply the state.
Noticed that the changed output details includes the password.

**Expected behavior**
Password should be redacted in the output.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 1.0.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 1.2.1
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.3.0-1017-aws
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>
