### ISSUE TITLE
[BUG] svn.latest with `user` checks out file with `root` group

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#57304]
**Description**

When using [`svn.latest`](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.svn.html#salt.states.svn.latest) with the `user` kwarg, the files are checked out with a group of `root`.

**Setup**

```sls
issue_repro:
  user.present:
    - name: foo
    - home: /home/foo
    - createhome: True

  svn.latest:
    - name: http://svn.apache.org/repos/asf/spamassassin/trunk
    - target: /home/foo/spamassassin
    - user: foo
```

**Steps to Reproduce the behavior**

Apply the state above.

**Expected behavior**

Files owned by `foo:foo`.

**Screenshots**

```text
[root@master1 /]# salt ubuntu-minion cmd.run 'ls -l /home/foo/spamassassin'
ubuntu-minion:
    total 600
    -rw-r--r--  1 foo root  13190 May 15 12:45 CREDITS
    -rw-r--r--  1 foo root 106589 May 15 12:45 Changes
    -rw-r--r--  1 foo root  14628 May 15 12:45 INSTALL
    -rw-r--r--  1 foo root   1245 May 15 12:45 INSTALL.VMS
[...]
```

```text
[root@master1 /]# salt ubuntu-minion user.primary_group foo
ubuntu-minion:
    foo
```

**Versions Report**

<details><summary>salt --versions-report</summary>

```
[root@master1 /]# salt ubuntu-minion test.versions_report
ubuntu-minion:
    Salt Version:
               Salt: 3000.3
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.17 (default, Apr 15 2020, 17:20:14)
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.2
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.2.5
     
    System Versions:
               dist: Ubuntu 18.04 bionic
             locale: ascii
            machine: x86_64
            release: 5.3.0-51-generic
             system: Linux
            version: Ubuntu 18.04 bionic
```
</details>

**Additional context**

Very much related to #54378.
