### ISSUE TITLE
[BUG] file.directory clean doesn't work on Windows

### ISSUE THREAD

**Issue by SDedik** [saltstack/salt#57300]
**Description**
file.directory module report that "The directory is in the correct state" and doesn't remove files from it.

**Setup**
Consider following directory `tree C:\my /F`
```
C:\my
    file.txt

No subfolders exist
```
and following state file `test.sls`
```
clean directory:
  file.directory:
    - name: 'C:\my'
    - clean: true
```

**Expected behavior**
Expected behavior is that `file.txt` should be removed from the directory as it is not required anywhere in the `test.sls` and `test.sls` itself doesn't import/include any other states.

However, ` C:\salt\salt-call.bat --local state.apply test`
```
local:
----------
          ID: clean directory
    Function: file.directory
        Name: C:\my
      Result: True
     Comment: The directory C:\my is in the correct state
     Started: 12:29:18.267079
    Duration: 0.0 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   0.000 ms
```
File remains and is not removed.

**Versions Report**
```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2019Server
         system: Windows
        version: 2019Server 10.0.17763 SP0 Multiprocessor Free
```
