### ISSUE TITLE
[BUG] "unless" not firing in 3000.3

### ISSUE THREAD

**Issue by udf2457** [saltstack/salt#57336]
No matter the syntax I attempt, it seems that `unless` is being ignored and the state is being run.

I have tried:
```
pg12-dirempty:
  cmd.run:
    - names:
      - rm -rf /var/lib/postgresql/12/main/*
    - require:
      - pg12-shutdown
    - unless:
      - fun: file.file_exists
        path: /var/lib/postgresql/12/main/standby.signal
```

and

```
pg12-dirempty:
  cmd.run:
    - names:
      - rm -rf /var/lib/postgresql/12/main/*
    - require:
      - pg12-shutdown
    - unless: test -f /var/lib/postgresql/12/main/standby.signal
```

and

```
pg12-shutdown:
   service.dead:
    - name: postgresql
    - unless:
      - fun: file.file_exists
        path: /var/lib/postgresql/12/main/standby.signal
    - prereq:
      - pg12-dirempty

pg12-dirempty:
  cmd.run:
    - names:
      - rm -rf /var/lib/postgresql/12/main/*
    - unless:
      - fun: file.file_exists
        path: /var/lib/postgresql/12/main/standby.signal
```

But the result is always the same, the state gets fired:
```
----------                                                                                                                                                 
          ID: pg12-shutdown                                                                                                                                
    Function: service.dead                                                                                                                                 
        Name: postgresql                                                                                                                                   
      Result: True                                                                                                                                         
     Comment: Service postgresql was killed                                                                                                                
     Started: 14:17:07.730268                                                                                                                              
    Duration: 63.738 ms                                                                                                                                    
     Changes:                                                                                                                                              
              ----------                                                                                                                                   
              postgresql:                                                                                                                                  
                  False                                                                                                                                    
----------                                                                                                                                                 
          ID: pg12-dirempty                                                                                                                                
    Function: cmd.run                                                                                                                                      
        Name: rm -rf /var/lib/postgresql/12/main/*                                                                                                         
      Result: True                                                                                                                                         
     Comment: Command "rm -rf /var/lib/postgresql/12/main/*" run                                                                                           
     Started: 14:17:07.795876                                                                                                                              
    Duration: 59.113 ms                                                                                                                                    
     Changes:                                                                                                                                              
              ----------                                                                                                                                   
              pid:                                                                                                                                         
                  793                                                                                                                                      
              retcode:                                                                                                                                     
                  0                                                                                                                                        
              stderr:                                                                                                                                      
              stdout:  
```
