### ISSUE TITLE
[BUG] Proxy logs are not rotated 

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#57353]
**Description**
Salt Proxy logs are not getting rotated, and need an entry in salt-common.logrotate similar to master and minion

**Setup**
Native minion on Juniper, but applicable for any proxy minion usage.

**Steps to Reproduce the behavior**
Reported by Juniper when developing native minion with make use of proxy

**Expected behavior**
Expect proxy logs not to consume all space on a disk but rotate.

**Screenshots**
From email thread:
```
On QFX10002:
/var/log/salt

% ls -lrt
total 948032
-rw-r-----  1 root  wheel          0 Apr  8 04:55 minion
-rw-r-----  1 root  wheel  485228432 May 17 23:47 proxy

% du -sm proxy
463         proxy
% du -sm /var/log
475         /var/log

% df /var/log
Filesystem  512-blocks   Used  Avail Capacity  Mounted on
/dev/ada1p2     973368 972472 -76968   109%    /.mount/var/log
```

**Versions Report**
```
root@Unknown:~# salt junos174RS8 test.versions
junos174RS8:
    Salt Version:
               Salt: 3000.1-12-gf0937a3fe4
     
    Dependency Versions:
               cffi: 1.14.0
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.11.2
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.2
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: Not Installed
       pycryptodome: 3.9.7
             pygit2: Not Installed
             Python: 3.7.7 (default, Apr 13 2020, 03:51:14)
       python-gnupg: Not Installed
             PyYAML: 5.1.2
              PyZMQ: 19.0.1
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.3.1
     
    System Versions:
               dist:   
             locale: utf-8
            machine: amd64
            release: JNPR-11.0-20190825.5ca39af_buil
             system: FreeBSD
            version: Not Installed
```

**Additional context**
