### ISSUE TITLE
[salt-cloud] on azure userdata_file: is not used properly for windows minions

### ISSUE THREAD

**Issue by flavius-iftode** [saltstack/salt#57417]
**Description**
salt-cloud: `userdata_file:` is not used properly if it point's to a local file for `azurearm.py`. I did some debug and and I found out that if `userdata_file:` is a local file, the content of the file will be assigned to the `userdata:`. After this if `userdata:` is not empty, which is not, `settings['commandToExecute']` is set to `userdata:` content, which causes `commandToExecute` to be invalid for Azure VM Extension.

I was able to workaround this by modifying the windows-firewall.ps1 proposed content like this:

- remove <powershell> and </powershell> tags
- merge all cmd's in one line and separate them by ;
- prefix the line with `powershell -ExecutionPolicy Unrestricted -File -command` and put the entire command between double quotes. I also had to escape the double quotes for all cmd's

Final file will look like this:
```
powershell -command " netsh advfirewall firewall add rule name=\"Salt\" dir=in action=allow protocol=TCP localport=4505-4506; New-NetFirewallRule -Name \"SMB445\" -DisplayName \"SMB445\" -Protocol TCP -LocalPort 445; New-NetFirewallRule -Name \"WINRM5986\" -DisplayName \"WINRM5986\" -Protocol TCP -LocalPort 5986; winrm quickconfig -q;  winrm set winrm/config/winrs '@{MaxMemoryPerShellMB=\"300\"}';  winrm set winrm/config '@{MaxTimeoutms=\"1800000\"}';  winrm set winrm/config/service/auth '@{Basic=\"true\"}'; $SourceStoreScope = 'LocalMachine';  $SourceStorename = 'Remote Desktop'; $SourceStore = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Store -ArgumentList $SourceStorename, $SourceStoreScope;  $SourceStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly); $cert = $SourceStore.Certificates | Where-Object -FilterScript {   $_.subject -like '*'  }; $DestStoreScope = 'LocalMachine';  $DestStoreName = 'My'; $DestStore = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Store -ArgumentList $DestStoreName, $DestStoreScope;  $DestStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite);  $DestStore.Add($cert); $SourceStore.Close();  $DestStore.Close(); winrm create winrm/config/listener?Address=*+Transport=HTTPS `@`{CertificateThumbprint=`\"($cert.Thumbprint)`\"`}; Restart-Service winrm; "
```

There is also another solution, to upload the file to storage account and specify a link. That is working, but the problem is with local file so I'm not considering this a solution, just another way to do it, which is not applicable for me.

The problem is in `salt/cloud/clouds/azurearm.py`:
first here:
```
 if userdata_file:
        if os.path.exists(userdata_file):
            with salt.utils.files.fopen(userdata_file, 'r') as fh_:
                userdata = fh_.read()
```
`userdata` get's the content of userdata_file.

second here:
```
settings = {}
            if userdata:
                settings['commandToExecute'] = userdata
            elif userdata_file.startswith('http'):
                settings['fileUris'] = [userdata_file]
                settings['commandToExecute'] = command_prefix + './' + userdata_file[userdata_file.rfind('/')+1:]

```
with these 2 combined if `userdata_file` is a local path, this will not work. because what is in the instructions here: https://docs.saltstack.com/en/master/topics/cloud/windows.html#firewall-settings cannot be executed as a cmd.

**Setup**
cloud profile for win 2016:
```
azure-win2016:
  provider: azure
  image: MicrosoftWindowsServer|WindowsServer|2016-Datacenter|latest
  size: Standard_B2s
  location: eastus
  win_installer: /etc/salt/win_utils/Salt-Minion-3000.3-Py3-AMD64-Setup.exe
  userdata_file: /etc/salt/firewall.ps1
  use_winrm: True
  winrm_port: 5986
  winrm_verify_ssl: False
```

**Expected behavior**
the file  `/etc/salt/firewall.ps1` should be uploaded to windows minion and executed.
when I check the vm extension I should see this `"commandToExecute": "powershell -ExecutionPolicy Unrestricted -file firewall.ps1 "` and not this:
```
"settings": {
      "commandToExecute": "<powershell>\nNew-NetFirewallRule -Name \"SMB445\" -DisplayName \"SMB445\" -Protocol TCP -LocalPort 445\nNew-NetFirewallRule -Name \"WINRM5986\" -DisplayName \"WINRM5986\" -Protocol TCP -LocalPort 5986\n\nwinrm quickconfig -q\nwinrm set winrm/config/winrs '@{MaxMemoryPerShellMB=\"300\"}'\nwinrm set winrm/config '@{MaxTimeoutms=\"1800000\"}'\nwinrm set winrm/config/service/auth '@{Basic=\"true\"}'\n\n$SourceStoreScope = 'LocalMachine'\n$SourceStorename = 'Remote Desktop'\n\n$SourceStore = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Store -ArgumentList $SourceStorename, $SourceStoreScope\n$SourceStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly)\n\n$cert = $SourceStore.Certificates | Where-Object -FilterScript {\n    $_.subject -like '*'\n}\n\n$DestStoreScope = 'LocalMachine'\n$DestStoreName = 'My'\n\n$DestStore = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Store -ArgumentList $DestStoreName, $DestStoreScope\n$DestStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite)\n$DestStore.Add($cert)\n\n$SourceStore.Close()\n$DestStore.Close()\n\nwinrm create winrm/config/listener?Address=*+Transport=HTTPS `@`{CertificateThumbprint=`\"($cert.Thumbprint)`\"`}\n\nRestart-Service winrm\n</powershell>"
    }
```
which is the content of the file.

**Versions Report**

```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.15
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.7 (default, Mar 10 2020, 15:43:33)
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 3.0.4
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 19.4.0
         system: Darwin
        version: 10.15.4 x86_64
```
</details>

**Additional context**
I also had to add this to the firewall rules `netsh advfirewall firewall add rule name="Salt" dir=in action=allow protocol=TCP localport=4505-4506`, otherwise connection to/from master is not possible.

With all these fixes I was able to deploy master ( linux) and minions ( windows 2016 and 2019) on azure.
