### ISSUE TITLE
[BUG] CentOS 8 osrelease grain does not all version numbers

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#57424]
**Steps to Reproduce the behavior**
```yaml
[root@centos8 ~]# salt-call --local grains.items
<snip>
    os:
        CentOS
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        CentOS Linux 8 (Core)
    osfinger:
        CentOS Linux-8
    osfullname:
        CentOS Linux
    osmajorrelease:
        8
    osrelease:
        8
    osrelease_info:
        - 8
<snip>
```

**Expected behavior**
Example for CentOS 7:

```yaml
[root@centos7 ~]# salt-call --local grains.items
<snip>
    os:
        CentOS
    os_family:
        RedHat
    osarch:
        x86_64
    oscodename:
        CentOS Linux 7 (Core)
    osfinger:
        CentOS Linux-7
    osfullname:
        CentOS Linux
    osmajorrelease:
        7
    osrelease:
        7.8.2003
    osrelease_info:
        - 7
        - 8
        - 2003
<snip>
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
# salt-call --versions-report
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov 21 2019, 19:31:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 8.1.1911 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-147.8.1.el8_1.x86_64
         system: Linux
        version: CentOS Linux 8.1.1911 Core

```
</details>
