### ISSUE TITLE
[FEATURE REQUEST] zfs.filesystem_present should support 'mode'

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt#57466]
There currently doesn't appear to be a way to set permissions on a file, folder or zfs dataset without creating it.

For example:

```
/tank/mydataset:
  zfs.filesystem_present: []
```
Will create ```tank/mydataset```.  But if I want to set permissions on it, I need to:
```
set_permissions_on_mydataset:
  file.directory:
    - name: /tank/mydataset
    - owner: root
    - group: whatever
    - mode: 0777
    - require:
      - /tank/mydataset
```

Unfortunately what happens--especially in the ZFS world is that the dataset actually exists, but it hasn't been mounted.  For example with encryption.

This causes salt to create the directory on the root filesystem and assign it permissions which don't actually apply to the dataset.

It can similarly happen when you have a system that manages files and folders outside of salt.  If you want to set permissions on a folder or file, but not create it if it doesn't exist...there really isn't a way to handle it.

I have to hack something up like:
```
set_permissions_on_mydataset:
  cmd.run:
    - name: 'chmod 0777 /tank/mydataset'
    - unless: 'stat -c "%a" /tank/mydataset | grep 0777'
```
Maybe add 'permissions' to the file module?

```
/tank/mydataset:
  file.permissions:
    - mode: 0752
```
