### ISSUE TITLE
Grains refresh/reload failed

### ISSUE THREAD

**Issue by AmiramMaimon** [saltstack/salt#57468]
I'm trying to reload the `minion` grains during a sls run with no success.
I have tried to use:
  * reload_grains: True
  * saltutil.grains_refresh
  * salt service.running restart (using the watch statement)

Using each of the above function I failed to reload the grains during the state run.

Consider the following example:
```
before:
  cmd.run:
    - name: echo "{{ grains['dns'] }}"

echo "domain test" >> /etc/resolv.conf:
  cmd.run: []

after:
  cmd.run:
    - name: echo "{{ grains['dns'] }}"
```

At the `before` id I expect the domain field to be empty while on the `after` id I expect that the domain field would contain`test`
Another example, when i file.managed the grains.conf file I want that the grains change will take affect on the **current run**.

How can I achieve that?

I'm running on `Ubuntu 16.04` with salt-minion and salt-master version `3000.3`

**Comment by sagetherage** [comment]
the Core team will not be able to get to this in `Aluminium` but we will review a PR if anyone in the community wants to submit one, moving to `Silicon`

**Comment by garethgreenaway** [comment]
@AmiramMaimon Apologies for the delay on this one.  The major root of the issue here is that the state file is only rendered once and when it is initially rendered the contents of the grain is empty.  If you try the following state you'll see that the grains are updated following the refresh.

```yaml
before:
  test.nop:
    - name: "{{ grains['dns'] }}"

write_resolv:
  cmd.run:
    - name: 'echo "domain test" >> /etc/resolv.conf'

grains_refresh:
  module.run:
   - saltutil.refresh_grains: []
   - reload_grains: true

grains_read:
  module.run:
   - grains.items: []

after:
  test.nop:
    - name: "{{ grains['dns'] }}"
```

**Comment by AmiramMaimon** [comment]
I have tried the following:
```
grains_refresh:
  module.run:
   - saltutil.refresh_grains: []
   - reload_grains: true
```

The only new part is:
```
grains_read:
  module.run:
   - grains.get:
     - key: dns
```
Why do I need it for?
It will cause a re-rendering of the grains? (I would expect the first part to do it as well)
