### ISSUE TITLE
[BUG] pillarstack opts matching: pillar.items returns nothing

### ISSUE THREAD

**Issue by daks** [saltstack/salt#57580]
Looking at documentation for pillarstack ext_pillar https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html it should be possible to define stack config files depending of grains, pillar or opts, like in the example

```
ext_pillar:
  - stack:
      pillar:environment:
        dev: /path/to/dev/stack.cfg
        prod: /path/to/prod/stack.cfg
      grains:custom:grain:
        value:
          - /path/to/stack1.cfg
          - /path/to/stack2.cfg
      opts:custom:opt:
        value: /path/to/stack0.cfg
```

I tried pillar matching and it works but opts don't.

Here is one basic pillarstack setup that works. Minion has a 'saltenv' setting (it will be used later).
Pillarstack is configured to simply read all yml files in dev or prod directory and only set a corresponding `env` pillar.
```
### salt-master config file
ext_pillar:
  - stack:
      - /srv/pillar/dev/base.cfg

### salt-minion config file
saltenv: prod

### pillar directory
/srv/pillar$ tree .
.
├── dev
│   ├── base.cfg
│   └── env.yml
└── prod
    ├── base.cfg
    └── env.yml

### files content
$ cat */base.cfg
*.yml

$ cat */*.yml
---
env: dev
---
env: prod
```

Results of commands
```
$ salt 'minion1' config.get saltenv
minion1:
    prod

$ salt 'minion1' pillar.items
minion1:
    ----------
    env:
        dev
```

`config.get` returns the `__opts__` salt dictionary which contains `saltenv`.
Now we change pillarstack config to match on this opts saltenv value:
```
ext_pillar:
  - stack:
      opts:saltenv:
        dev: /srv/pillar/dev/base.cfg
        prod: /srv/pillar/prod/base.cfg
```

```
$ salt 'minion1' config.get saltenv
minion1:
    prod

$ salt 'minion1' pillar.items
minion1:
    ----------
```
As you can see, the `saltenv` is set and `pillar.items` returns nothing.
What's weird is that:
```
$ salt 'minion1' pillar.get env
minion1:
    prod
```
A specific `pillar.get` correctly returns the expected value!

Adding some awful `log.debug()` inside `salt/pillar/stack.py` I see that it parses the right /srv/pillar/{dev,prod}/base.cfg and *.yml files depending of the `saltenv` setting

I don't really understand where this bug can be, from inside or outside stack.py (pillarstack) but it seems the module does the job correctly, reading the right files and filling pillar data... but... still `pillar.items` returns nothing.

**Comment by frogunder** [comment]
@daks Thanks for reporting this issue.

I am seeing the same thing.

Thanks.

**Comment by daks** [comment]
More information:

after adding dev and prod to my `pillar_roots` I got rid of this error message but I still see that when running `pillar.items` it does not know about the saltenv and by consequence doesn't parse the expected files and returns nothing.

**Comment by frogunder** [comment]
@saltstack/team-core Can you take a look at this issue and give some input, please?

Thanks.

**Comment by daks** [comment]
Hello, any news about this issue?

**Comment by sagetherage** [comment]
@daks we are reviewing this today in the Triage Community meeting and will have more details soon. Thanks for the reminder!

**Comment by garethgreenaway** [comment]
@daks I wonder if this is a similar issue to another pillar issue that was reported a few days ago when using pillar caching and pillar environments.  Would you be able to try the fix in this PR and see if it resolves the issue that you're seeing?  https://github.com/saltstack/salt/pull/58274

**Comment by daks** [comment]
@garethgreenaway I'm running salt-master 2019.2.5 and tried to replace my `salt/pillar/__init__.py` with the one on this PR and salt-master didn't restart. I then tried to manually apply the patch and this time salt-master was ok to start, but I still see the same problem.

**Comment by daks** [comment]
I upgraded my test setup to 3001.1 (`3001.1+ds-1` exactly) and replaced the file with the one from the PR. It doesn't solve the bug

```
$ salt 'minion1' config.get saltenv
minion1:
    production

[...]

$ salt 'minion1' pillar.items
minion1:
    ----------

[...]

$ salt 'minion1' pillar.get env
minion1:
    prod

[...]

$ salt 'minion1' pillar.raw
minion1:
    ----------
    env:
        prod
```

**Comment by vskubriev** [comment]
I suspect that `pillar:environment:` doesn't work for the same reason. While simple declaration works as expected. I mean the case with example from doc:
```
ext_pillar:
  - stack:
      pillar:environment:
        dev: /path/to/dev/stack.cfg
        prod: /path/to/prod/stack.cfg
```

**Comment by daks** [comment]
> I suspect that `pillar:environment:` doesn't work for the same reason. While simple declaration works as expected. I mean the case with example from doc:
> 
> ```
> ext_pillar:
>   - stack:
>       pillar:environment:
>         dev: /path/to/dev/stack.cfg
>         prod: /path/to/prod/stack.cfg
> ```

In my previous tests using `pillar:environment` worked fine. (see initial bug report). Was tested on 2019.2 not on recent versions

**Comment by vskubriev** [comment]
> > I suspect that `pillar:environment:` doesn't work for the same reason. While simple declaration works as expected. I mean the case with example from doc:
> > ```
> > ext_pillar:
> >   - stack:
> >       pillar:environment:
> >         dev: /path/to/dev/stack.cfg
> >         prod: /path/to/prod/stack.cfg
> > ```
> 
> In my previous tests using `pillar:environment` worked fine. (see initial bug report). Was tested on 2019.2 not on recent versions

Sorry. I'am lost. What kind of bug report are you talking about ?
Can you provide a correspond link ?

**Comment by daks** [comment]
@vskubriev this one! see initial bug report https://github.com/saltstack/salt/issues/57580#issue-634303153, for me using `pillar:environment` works well on 2019.2

**Comment by daks** [comment]
hello, any news about this bug?

**Comment by gbunt** [comment]
@daks fwiw i've been able to get pillarstack working based on `opts:saltenv`, though still seem to have a problem with `pillar_roots` not being picked up properly. This test was a mixed environment where master and it's local minion are on v3002.2 (env: production) and 2 other minions still run v2019.2.5 (env: dev).

- master pillar config:
```
pillar_roots:
  production:
    - /srv/salt/prod/pillar
  dev:
    - /srv/salt/dev/pillar
    
ext_pillar:
  - stack:
      opts:saltenv:
        production:
          - /srv/salt/prod/pillar/stack/pillarstack.cfg
          - /srv/salt/prod/pillar/stack/classstack.cfg
  - stack_fork:
      opts:saltenv:
        dev:
          - /srv/salt/dev/pillar/stack/pillarstack.cfg
          - /srv/salt/dev/pillar/stack/classstack.cfg
```
Note: We just happen to temporarily run a pillarstack for for the dev environment. Without that need, `ext_pillar` would simply look like:
```
ext_pillar:
  - stack:
      opts:saltenv:
        production:
          - /srv/salt/prod/pillar/stack/pillarstack.cfg
          - /srv/salt/prod/pillar/stack/classstack.cfg
        dev:
          - /srv/salt/dev/pillar/stack/pillarstack.cfg
          - /srv/salt/dev/pillar/stack/classstack.cfg
```

- minion config production environment:
```
saltenv: production
lock_saltenv: True
state_top_saltenv: production
pillarenv_from_saltenv: True
```
- minion config dev environment:
```
saltenv: dev
lock_saltenv: True
state_top_saltenv: dev
pillarenv_from_saltenv: True
```

```
$ salt '*' config.get saltenv
0611d599-d9aa-42db-94e5-a51da1011eaf:
    dev
6cd6afb6-0759-403e-9dee-a3db09cfea10:
    dev
c2966744-eb31-461e-8baf-8b9208f5eadf:
    production
```

The following test pillar data is present:
```
# /srv/salt/prod/pillar/test/init.sls:
test:
  env: production
  
# /srv/salt/dev/pillar/test/init.sls:
test:
  env: dev
```

In both environments the pillar `top.sls` refers to the test pillar:
```
production:
  '*':
    - test
```
```
dev:
  '*':
    - test
```

After a refresh_pillar, somehow only the `dev` pillar data is returned for all minions, regardless of their environment:
```
$ salt '*' pillar.items test:env
c2966744-eb31-461e-8baf-8b9208f5eadf:
    ----------
    test:env:
        dev
6cd6afb6-0759-403e-9dee-a3db09cfea10:
    ----------
    test:env:
        dev
0611d599-d9aa-42db-94e5-a51da1011eaf:
    ----------
    test:env:
        dev
```

- Adding pillarstack test data:
```
# /srv/salt/prod/pillar/stack/defaults/test.yml:
test:
  pillarstack:
    env: production

# /srv/salt/dev/pillar/stack/defaults/test.yml:
test:
  pillarstack:
    env: dev
```

Pillar data is successfully picked up from pillarstack:
```
$ salt '*' pillar.items test
6cd6afb6-0759-403e-9dee-a3db09cfea10:
    ----------
    test:
        ----------
        env:
            dev
        pillarstack:
            ----------
            env:
                dev
c2966744-eb31-461e-8baf-8b9208f5eadf:
    ----------
    test:
        ----------
        env:
            dev
        pillarstack:
            ----------
            env:
                production
0611d599-d9aa-42db-94e5-a51da1011eaf:
    ----------
    test:
        ----------
        env:
            dev
        pillarstack:
            ----------
            env:
                dev
```

I don't know why that is, given `pillar_roots` is correctly configured for each environment. One thing i noticed, is that it seems the first environment in alphabetical order seems to be picked when i rename the environments.
Haven't tested v3005.1 yet.
