### ISSUE TITLE
[BUG] pkgrepo.managed doesn't account for architectures in test mode

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#57600]
**Description**
When run in test mode on an apt system, `pkgrepo.managed` incorrectly determines that there would be changes if an architecture is defined.

**Setup**
```yaml
salt-repo:
  pkgrepo.managed:
    - name: deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main
    - file: /etc/apt/sources.list.d/saltstack.list
    - architectures: amd64
    - key_url: https://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest/SALTSTACK-GPG-KEY.pub
```

**Steps to Reproduce the behavior**
```
# salt-call state.apply test=true
local:
----------
          ID: salt-repo
    Function: pkgrepo.managed
        Name: deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main
      Result: None
     Comment: Package repo 'deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main' would be configured. This may cause pkg states to behave differently than stated if this action is repeated without test=True, due to the differences in the configured repositories.
     Started: 13:48:06.339543
    Duration: 93.91 ms
     Changes:
              ----------
              line:
                  ----------
                  new:
                      deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main
                  old:
                      deb [arch=amd64] http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main
----------
```

**Expected behavior**
After first application, no changes should be reported.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: 0.32.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ISO-8859-1
        machine: x86_64
        release: 4.15.0-101-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>
