### ISSUE TITLE
[BUG] Bootstrap fails on SuSe

### ISSUE THREAD

**Issue by juan-acevedo-ntt** [saltstack/salt#57614]
**Description**
Deploying Suse instances on AWS usising a mapfile fails to install the minion.

**Setup**
mapfile:
```
ec2_suse12sp2:
  - jja_minion_suse12sp2
```
profile:
```
ec2_suse12sp2:
  provider: ec2
  image: ami-07cd573b3c20fdc08
  size: t3.small
  ssh_username: ec2-user
  ssh_interface: private_ips
  del_root_vol_on_destroy: True
  rename_on_destroy: True
  script: bootstrap-salt
  script_args: -x python3 stable 2019.2.2
  subnetid: subnet-xxxxxxxxxxxxxx
  securitygroupname: xxxxxxxxxxxxx
  minion:
    grains:
      customer: xxxxxxx
  userdata_file: /etc/salt/cloud.deploy.d/userdata

```

**Steps to Reproduce the behavior**
Error log:
```
          ID: create machines
    Function: salt.runner
        Name: xxxxx.map_run
      Result: True
     Comment: Runner function 'xxxxx.map_run' executed.
     Started: 10:30:12.967878
    Duration: 158572.954 ms
     Changes:   
              ----------
              return:
                  ----------
                  jja_minion_suse12sp2:
                      ----------
                      Error:
                          Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /data/salt-data/etc/salt/cloud.conf.d/salt-key.pem  -p 22 ec2-user@10.158.241.56 'sudo /tmp/.saltcloud-87062631-7254-495b-a1f3-7dc4fec69a08/deploy.sh -c '"'"'/tmp/.saltcloud-87062631-7254-495b-a1f3-7dc4fec69a08'"'"' -x python3 stable 2019.2.2'' failed. Exit code: 1
```

Error when manually ran the command:
```
ERROR: sles_sap does not have major version pegged packages support
```

**Expected behavior**
The process should deply a Suse ec2 instance and install the minion

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: 4.0.5
      gitpython: 3.1.2
          ioflo: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: 0.4.6
         PyYAML: 3.13
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 3.0.4
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core
```
</details>

**Additional context**
