### ISSUE TITLE
[DOCs] NameError: global name '__jid__' is not defined

### ISSUE THREAD

**Issue by ihakh** [saltstack/salt#57687]
**Description**

the `__jid__` is not available in execution module:

```python
def test():
    return __jid__
```
this should be available: https://docs.saltstack.com/en/master/topics/development/modules/developing.html#additional-globals
**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: unknown
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 14 2019, 20:00:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.0.5
```
</details>

**Comment by xeacott** [comment]
Hey @ihakh can you be a little more specific when you say "the jid is not available in execution module"?

It sounds like you're writing or have written a custom execution module, but returning `__jid__` gave you some kind of error? If so, could you post the entire stack trace? Also, what steps did you follow to have salt execute your custom file?

**Comment by ihakh** [comment]
```
cat /srv/salt/_modules/tset.py                                                                            ⚡  1 ↵  0.33 
def test():
    return __jid__
```

```
salt '*' saltutil.sync_all
minion-01-01:
    ----------
    beacons:
    clouds:
    engines:
    executors:
    grains:
    log_handlers:
    matchers:
    modules:
        - modules.tset
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    serializers:
    states:
    thorium:
    utils:

```
```
salt '*' tset.test
minion-01-01:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1676, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/tset.py", line 2, in test
        return __jid__
    NameError: global name '__jid__' is not defined
```
