### ISSUE TITLE
[BUG] postgres_privileges: unable to verify existing privileges on views.

### ISSUE THREAD

**Issue by NotSqrt** [saltstack/salt#57690]
Hello !

`postgres.privileges_list` and similar functions are unable to verify existing privileges on views.

`postgres_privileges.present` says:
> View permissions should specify `object_type: table`.

https://github.com/saltstack/salt/blob/a670b4ae72ec11f5485c216c54059e14223019b8/salt/states/postgres_privileges.py#L118

But `_make_privileges_list_query` is unable to verify existing privileges on views because it filters on ordinary tables only.
https://github.com/saltstack/salt/blob/f41cda17ce6cc0ee54df483f4d5f48cc2b9632e7/salt/modules/postgres.py#L2728

A little update should fix that.
```diff
-                    "AND relkind = 'r'",
+                    "AND relkind in ('r', 'v')",
```

State example : `pg_catalog.pg_shadow` is a view.
```yaml
pgbouncer_auth_user:
    postgres_privileges.present:
        # GRANT SELECT ON pg_catalog.pg_shadow TO pgbouncer_auth_user;
        - prepend: pg_catalog
        - object_name: pg_shadow
        - object_type: table
        - privileges:
            - SELECT
        - maintenance_db: my_db
        - db_port: 5432
```
