### ISSUE TITLE
[DOCS] Missing docs for "requires" requisite in Salt Cloud maps

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#57795]
**Description**
Received report on Slack:

> In salt-cloud source I found that it supports `requires` directive (in the map file), although I cannot find any documentation for it. It seems to be a way to define that one VM requires another to be created (which is what I need), but I don't know how to use that directive.

**Setup**
Snippet of what the reporter found to work:
```
profile:
  - vm1:
      devices:
        ...
  - vm2:
      requires:
        - vm1
      devices:
        ...
```

**Expected behavior**
Need to get the docs updated w/ this info.
