### ISSUE TITLE
[BUG] `file.absent` fails, when targeted file is read-only, but owned by executing user

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#57830]
**Description**
When trying to remove a file using `file.absent`, it will fail if the targeted file is read-only (e.g. `mode: 0440`), but owned by the executing user, which would actually allow to remove the file.
This can be reproduced when executing `salt-call` as a non-root user, e.g. in a build-pipeline.

**Setup**
Create the following files in a temporary directory:
**`Saltfile`**
```yaml
salt-call:
  config_dir: ./salt/config/
```
**`salt/config/minion`**
```yaml
log_level_logfile: quiet
file_client: local
root_dir: .
minion_id_caching: false
```
**`remove.sls`**
```yaml
test-directory:
  file.directory:
    - name: {{ grains['cwd'] }}/test-directory
    - mode: 0770

test-file:
  file.managed:
    - name:    {{ grains['cwd'] }}/test-directory/test-file
    - mode:    0440
    - replace: false
    - require:
      - test-directory

# otherwise `test-file` would fail due to non-existing write
# permissions on `test-directory`, so basically just the same
# problem as demonstrated for `file.absent` for `file.managed`
# as well
test-directory-permissions:
  file.directory:
    - name: {{ grains['cwd'] }}/test-directory
    - mode: 0550
    - require:
      - test-file

test-file-removal:
  file.absent:
    - name: {{ grains['cwd'] }}/test-directory/test-file
    - require:
      - test-directory-permissions
```

**Steps to Reproduce the behavior**
Execute as non-root user:
```bash
salt-call --file-root=${PWD} state.sls remove
```
**Observed behavior**
```
          ID: test-file-removal
    Function: file.absent
        Name: /home/eprobst/tmp/absent-bug/test-directory/test-file
      Result: False
     Comment: Could not remove '/home/eprobst/tmp/absent-bug/test-directory/test-file': [Errno 13] Permission denied: '/home/eprobst/tmp/absent-bug/test-directory/test-file'
     Started: 15:56:34.725920
    Duration: 2.424 ms
     Changes:
```

**Expected behavior**
If a file is fully owned by the executing user or through a corresponding group membership, I'd expect to be able to remove it without having to implement workarounds.

The corresponding code might need some Exception handling, which in this case changes the permissions on a file, then retries to remove it and only fails then if it still doesn't succeed. Alternatively, the approach of the implementation in [`salt/modules/win_file.py`](https://github.com/saltstack/salt/blob/b95213ec903402f25c1e0aeb3990fe8452ab63ce/salt/modules/win_file.py#L1179) could be re-used to first check the permissions of each file, but this might cause some unwanted overhead.

**Versions Report**
<details>

```

Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-101-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

**Additional context**
The same behavior was reported on Windows in #42295 and fixed in #42308
