### ISSUE TITLE
[BUG] Salt 3001: ä and ü are "non-decodable characters" on Windows

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#57901]
**Description**
Letter ä is decoded as `„` (Double Low-9 Quotation Mark, [Unicode letter 201E](https://unicode-table.com/en/search/?q=201E)), 

Letter ü is not decodable (�)

**Setup**
- Install Salt-Minion-3001-Py3-AMD64.msi or
- Install from Git (pip install -e .)

**Steps to Reproduce the behavior**

On Windows, create a file containing the letter ä which occurs in German Datenträger (volume), or set up Windows in German, which will name its volumes "Datenträger".

    mkdir \windows\temp\salt-test
    echo Datenträger> C:\windows\temp\salt-test\Datenträger.txt

On the master execute 

```
salt bob cmd.run 'dir \windows\temp\salt-test'
bob:
     Datentr„ger in Laufwerk C: ist Windows
     Volumeseriennummer: XXXX-XXX

     Verzeichnis von C:\windows\temp\salt-test

    10.07.2020  17:55    <DIR>          .
    10.07.2020  17:55    <DIR>          ..
    10.07.2020  17:51                13 Datentr„ger.txt
                   1 Datei(en),             13 Bytes
                   2 Verzeichnis(se), 328.304.738.304 Bytes frei

```
The letter ä is decoded as double quotation mark in both the file name and the localized word for volume.

On Windows add a file containing the letter ü which occurs in the word ausgeführt (executed), and is therefore often part of the Windows response, e.g. "service is executed":

    echo ausgeführt> C:\windows\temp\salt-test\ausgeführt.txt

On the master execute 

```
salt bob cmd.run 'dir \windows\temp\salt-test'
bob:
     Datentr�ger in Laufwerk C: ist Windows
     Volumeseriennummer: XXXX-XXXX

     Verzeichnis von C:\windows\temp\salt-test

    10.07.2020  17:51    <DIR>          .
    10.07.2020  17:51    <DIR>          ..
    10.07.2020  17:51                12 ausgef�hrt.txt
    10.07.2020  17:51                13 Datentr�ger.txt
                   2 Datei(en),             25 Bytes
                   2 Verzeichnis(se), 328.305.393.664 Bytes frei

```

ä and ü are not decoded

With salt-call on Windows, you get the same output and an error:

```
\salt\salt-call  cmd.run "dir \windows\temp\salt-test"
[ERROR   ] Failed to decode stdout from command chcp 437 > nul & dir \windows\temp\salt-test, non-decodable characters have been replaced
local:
     Datentr�ger in Laufwerk C: ist Windows
     Volumeseriennummer: XXXX-XXXX

     Verzeichnis von C:\windows\temp\salt-test

    10.07.2020  18:05    <DIR>          .
    10.07.2020  18:05    <DIR>          ..
    10.07.2020  18:05                12 ausgef�hrt.txt
    10.07.2020  17:51                13 Datentr�ger.txt
                   2 Datei(en),             25 Bytes
                   2 Verzeichnis(se), 328.303.046.656 Bytes frei

```

This behavior is reproduceable (when you delete ü, ä is represented as quotation mark)

**Expected behavior**

Letters ä and ü are decoded.

**Related issues**
- https://github.com/saltstack/salt/issues/54447
- https://github.com/saltstack/salt/issues/50650

**Versions Report**

<details><summary>salt --versions-report</summary>

Minion
```


\salt\salt-call --versions-report
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.17763 SP0

```

Master
```
salt --versions-report
Salt Version:
           Salt: 2019.2.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core


```

</details>
