### ISSUE TITLE
[BUG] SIGTERM while salt-minion is starting up gets ignored, salt-minion never stops

### ISSUE THREAD

**Issue by danc86** [saltstack/salt#57934]
**Description**
If you start the salt-minion service using `systemctl start salt-minion`, and then shortly afterwards, while it is still in the process of starting up, restart it using `systemctl restart salt-minion` (or send it a SIGTERM in any other way), sometimes the SIGTERM will be ignored and the service will not stop:

    salt-minion[9556]: The Salt Minion is shutdown. Minion received a SIGTERM. Exited.
    salt-minion[9556]: [ERROR   ] Failed to import grains esxi as the module called exit()
    salt-minion[9556]: Traceback (most recent call last):
    salt-minion[9556]:   File "/usr/lib/python3.7/site-packages/salt/loader.py", line 1600, in _load_module
    salt-minion[9556]:     mod = spec.loader.load_module()
    salt-minion[9556]:   File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
    salt-minion[9556]:   File "<frozen importlib._bootstrap_external>", line 907, in load_module
    salt-minion[9556]:   File "<frozen importlib._bootstrap_external>", line 732, in load_module
    salt-minion[9556]:   File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
    salt-minion[9556]:   File "<frozen importlib._bootstrap>", line 696, in _load
    salt-minion[9556]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    salt-minion[9556]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    salt-minion[9556]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    salt-minion[9556]:   File "/usr/lib/python3.7/site-packages/salt/grains/esxi.py", line 16, in <module>
    salt-minion[9556]:     import salt.modules.vsphere
    salt-minion[9556]:   File "/usr/lib/python3.7/site-packages/salt/modules/vsphere.py", line 6506, in <module>
    salt-minion[9556]:     service_instance=None):
    salt-minion[9556]:   File "/usr/lib/python3.7/site-packages/salt/utils/decorators/__init__.py", line 102, in __call__
    salt-minion[9556]:     frame = inspect.stack()[1][0]
    salt-minion[9556]:   File "/usr/lib/python3.7/inspect.py", line 1513, in stack
    salt-minion[9556]:     return getouterframes(sys._getframe(1), context)
    salt-minion[9556]:   File "/usr/lib/python3.7/inspect.py", line 1490, in getouterframes
    salt-minion[9556]:     frameinfo = (frame,) + getframeinfo(frame, context)
    salt-minion[9556]:   File "/usr/lib/python3.7/inspect.py", line 1464, in getframeinfo
    salt-minion[9556]:     lines, lnum = findsource(frame)
    salt-minion[9556]:   File "/usr/lib/python3.7/inspect.py", line 780, in findsource
    salt-minion[9556]:     module = getmodule(object, file)
    salt-minion[9556]:   File "/usr/lib/python3.7/inspect.py", line 733, in getmodule
    salt-minion[9556]:     if ismodule(module) and hasattr(module, '__file__'):
    salt-minion[9556]:   File "/usr/lib/python3.7/site-packages/salt/cli/daemons.py", line 230, in _handle_signals
    salt-minion[9556]:     super(Minion, self)._handle_signals(signum, sigframe)
    salt-minion[9556]:   File "/usr/lib/python3.7/site-packages/salt/utils/parsers.py", line 1083, in _handle_signals
    salt-minion[9556]:     self.shutdown(exitmsg='{0} Exited.'.format(msg))
    salt-minion[9556]:   File "/usr/lib/python3.7/site-packages/salt/cli/daemons.py", line 389, in shutdown
    salt-minion[9556]:     self.__class__.__name__, (exitmsg or '')).strip()))
    salt-minion[9556]:   File "/usr/lib/python3.7/site-packages/salt/utils/parsers.py", line 1086, in shutdown
    salt-minion[9556]:     self.exit(exitcode, exitmsg)
    salt-minion[9556]:   File "/usr/lib/python3.7/site-packages/salt/utils/parsers.py", line 287, in exit
    salt-minion[9556]:     optparse.OptionParser.exit(self, status, msg)
    salt-minion[9556]:   File "/usr/lib/python3.7/optparse.py", line 1559, in exit
    salt-minion[9556]:     sys.exit(status)
    salt-minion[9556]: SystemExit: 0

Note that the message says it "exited" but it didn't. Eventually systemd gives up waiting and forcibly kills it, marking the service as failed:

    systemd[1]: salt-minion.service: State 'stop-sigterm' timed out. Killing.
    systemd[1]: salt-minion.service: Killing process 2395 (python3) with signal SIGKILL.
    systemd[1]: salt-minion.service: Main process exited, code=killed, status=9/KILL
    systemd[1]: salt-minion.service: Failed with result 'timeout'.
    systemd[1]: Stopped The Salt Minion.

**Setup**
The bug is reproducible with a completely empty configuration.

**Steps to Reproduce the behavior**
```
systemctl start salt-minion
sleep 5
systemctl restart salt-minion
```
Note that the window during which SIGTERM is ignored will vary depending on how fast the system is.
The problem is much more noticeable on systems with slower CPUs.
We use salt on an embedded device with low-power CPUs and salt-minion takes over 10 seconds to start up fully, during which time this bug can easily be triggered.

**Expected behavior**
The salt-minion service should shut down cleanly and promptly on SIGTERM.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 3.4.0
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.7 (default, May 26 2020, 01:18:05)
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 17.1.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: utf-8
        machine: x86_64
        release: 5.2.32-og
         system: Linux
        version: Not Installed
```
</details>

**Additional context**
There is some code in loader.py that tries to detect when SIGTERM was raised by examining the stack frames looking for a specific filename and function name:

https://github.com/saltstack/salt/blob/3000.2/salt/loader.py#L1628-L1645

but that doesn't seem to match what actually appears in the stack trace pasted above. Maybe some files got renamed at some point.
