### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#57991]
**Description**

**Setup**
Create the following kickstart file on /tmp/anaconda-ks.cfg:

```
#version=DEVEL
# System authorization information
auth --enableshadow --passalgo=sha512
# Install OS instead of upgrade
install
repo --name="Server-HighAvailability" --baseurl=file:///run/install/repo/addons/HighAvailability
repo --name="Server-ResilientStorage" --baseurl=file:///run/install/repo/addons/ResilientStorage
repo --name="Server-Mysql" --baseurl=file:///run/install/repo/addons/Mysql
# Use CDROM installation media
cdrom
# Use text mode install
text
# Firewall configuration
firewall --disabled
firstboot --disable
ignoredisk --only-use=sda
# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=static --device=link --gateway=192.0.2.249 --ip=192.0.2.253 --nameserver=192.0.2.1 --netmask=255.255.255.248 --ipv6=auto --no-activate
network  --bootproto=dhcp --hostname=host2.example.com
# Reboot after installation
reboot --eject
# Root password
rootpw --iscrypted $6$/lIb80D7DgbjByl1$dfDyvmmSeiT3le5eWNRUb/gNtfE1Y.5X5GfsUIkViV3rsCsidHnanVlnUOhwxrz8JX6GTFzXzCAXg4G.YSAb//
# SELinux configuration
selinux --disabled
# System services
services --enabled="chronyd"
# Do not configure the X Window System
skipx
# System timezone
timezone UTC --isUtc
user --groups=s-em7-core --name=em7admin --password=$6$/lIb80D7DgbjByl1$dfDyvmmSeiT3le5eWNRUb/gNtfE1Y.5X5GfsUIkViV3rsCsidHnanVlnUOhwxrz8JX6GTFzXzCAXg4G.YSAb// --iscrypted --shell=/bin/bash
# System bootloader configuration
bootloader --location=mbr --boot-drive=sda
reqpart
# Clear the Master Boot Record
zerombr
# Partition clearing information
clearpart --all
# Disk partitioning information
part pv.60 --asprimary --fstype="lvmpv" --size=91647
part /boot --asprimary --fstype="xfs" --size=512 --label=/boot
volgroup em7vg --pesize=4096 pv.60
logvol /var/log  --fstype="xfs" --size=5120 --name=var_log --vgname=em7vg
logvol /var/log/audit  --fstype="xfs" --size=2048 --name=var_log_audit --vgname=em7vg
logvol /data.local/db  --fstype="xfs" --grow --size=4096 --fsoptions="noatime" --name=db --vgname=em7vg
logvol /home  --fstype="xfs" --size=512 --fsoptions="nosuid" --name=home --vgname=em7vg
logvol /tmp  --fstype="xfs" --size=4608 --name=tmp --vgname=em7vg
logvol /var  --fstype="xfs" --size=6144 --name=var --vgname=em7vg
logvol /  --fstype="xfs" --grow --maxsize=10240 --size=4096 --name=root --vgname=em7vg
logvol swap  --fstype="swap" --size=6016 --name=swap --vgname=em7vg

%pre
# This script will generate /tmp/kickstart_config.out - included above
/usr/bin/python /mnt/install/repo/scripts/install_wizard.py > /dev/tty1
%end

%post --nochroot
export EM7_ISO_INSTALLATION=1
chroot /mnt/sysimage /bin/bash <<'EOT'
if ! [ -d /data/db/mysql ]; then
  /bin/mv /var/lib/mysql/* /data/db/ || true
  /bin/chown -R mysql:mysql /data/db || true
fi
/opt/em7/share/scripts/em7_install.sh cu
source /opt/em7/share/scripts/environment.sh
EOT
%end

%packages
@base
@core
@em7-core
chrony
em7-local-db
em7-model-cu

%end

%addon com_redhat_kdump --disable --reserve-mb='auto'

%end
```

**Steps to Reproduce the behavior**
master:
```
$ sudo salt host1.example.com genesis.mksls kickstart /tmp/anaconda-ks.cfg
host1.example.com:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20200721001823337461
```

host1:
```
[DEBUG   ] LazyLoaded genesis.mksls
[TRACE   ] Executors list ['direct_call']
usage: salt-minion [-h] [--bootproto {dhcp,bootp,static,ibft}]
                   [--device DEVICE] [--ip IP] [--ipv6 IPV6]
                   [--gateway GATEWAY] [--nodefroute]
                   [--nameserver NAMESERVER] [--nodns] [--netmask NETMASK]
                   [--hostname HOSTNAME] [--ethtool ETHTOOL] [--essid ESSID]
                   [--wepkey WEPKEY] [--wpakey WPAKEY] [--onboot ONBOOT]
                   [--dhcpclass DHCPCLASS] [--mtu MTU] [--noipv4] [--noipv6]
                   [--activate]
salt-minion: error: unrecognized arguments: --no-activate
```

**Expected behavior**
```
host1.example.com:
    UTC:
      timezone:
      - system
    base:
      pkg_group:
      - installed
    chrony:
      pkg:
      - installed
    core:
      pkg_group:
      - installed
    disabled:
      selinux:
      - mode
    em7-core:
      pkg_group:
      - installed
    em7-local-db:
      pkg:
      - installed
    em7-model-cu:
      pkg:
      - installed
    en_US.UTF-8:
      locale:
      - system
    link:
      activate:
        enabled:
        - true
      gateway: 192.0.2.249
      ip: 192.0.2.253
      ipv6: auto
      nameserver: 192.0.2.1
      netmask: 255.255.255.248
      proto: static
    system:
      network.system:
        apply_hostname: true
        enabled: true
        hostname: host2.example.com
    us:
      keyboard:
      - system
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: 0.26.8
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-193.6.3.el8_2.x86_64
         system: Linux
        version: CentOS Linux 8 Core
```
</details>

**Additional context**
Requires manual patching for #57869 and #57990
