### ISSUE TITLE
On Windows, path_join should properly contact `C:` and a path

### ISSUE THREAD

**Issue by baby-gnu** [saltstack/salt#58011]
**Description**

When using `path_join` in windows, there is an issue when joining a drive letter with the rest of arguments.

```
          ID: test-path-join
    Function: file.directory
        Name: C:test-dir\subdir
      Result: False
     Comment: Specified file C:test-dir\subdir is not an absolute path
     Started: 11:32:46.176101
    Duration: 15.648 ms
     Changes:
```

**Setup**

``` sls
{%- set system_drive = salt['environ.get']('SYSTEMDRIVE', 'C:') %}
{%- set test_dir_path_join = system_drive | path_join('test-dir', 'subdir') %}
{%- set test_dir_concat_slash = system_drive ~ '/test-dir/subdir' %}
{%- set test_dir_concat_backslash = system_drive ~ '\test-dir\subdir' %}

test-path-join:
  file.directory:
    - name: '{{ test_dir_path_join }}'

test-concat-with-slash:
  file.directory:
    - name: '{{ test_dir_concat_slash }}'

test-concat-with-backslash:
  file.directory:
    - name: '{{ test_dir_concat_backslash }}'
```

**Steps to Reproduce the behavior**

Here is the output of `state.show_sls` in YAML format:

```
  test-path-join:
    __env__: base
    __sls__: test-path-join
    file:
    - name: C:test-dir\subdir
    - directory
    - order: 10000
  test-concat-with-slash:
    __env__: base
    __sls__: test-path-join
    file:
    - name: C:/test-dir/subdir
    - directory
    - order: 10001
  test-concat-with-backslash:
    __env__: base
    __sls__: test-path-join
    file:
    - name: "C:\test-dir\\subdir"
    - directory
    - order: 10002
```

**Expected behavior**

The variable `test_dir_path_join` should be `C:\test-dir\subdir`.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
    Salt Version:
               Salt: 3001
     
    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.9.7
             pygit2: Not Installed
             Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 5.1.2
              PyZMQ: 18.0.1
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.18362 SP0
```
</details>

**Additional context**
