### ISSUE TITLE
State in SLS is not formed as a list

### ISSUE THREAD

**Issue by Morozzko** [saltstack/salt#58026]
What can be wrong here? It work ok, when i try to hardcode state

State:
```
{% for service, args in pillar.get('xml',{}).items() %}
{{ service }}:
  ensure_value_true:
    xml.value_present:
        - name: {{ args['name'] }}
        - xpath: {{ args['xpath'] }}
        - value: {{ args['value'] }}

{% endfor %}
```

Pillar:
```
xml:
  MqHostName:
    value: 'mq.ext'
    xpath: './/MqHostName'
    name: 'C:\\PFEI\ExternalMqService\Configs\MqSettings.Ext.xml'

  MqPort:
    value: '2911'
    xpath: 'MqPort'
    name: 'C:\\PFEI\ExternalMqService\Configs\MqSettings.Ext.xml'

```

Error:
```
Data failed to compile:
----------
    State 'MqHostName' in SLS 'xml' is not formed as a list

```

**Comment by max-arnold** [comment]
Try the following command to troubleshoot just the Jinja statements without evaluating the resulting Yaml:

`salt MINION slsutil.renderer default_renderer=jinja path=salt://xml.sls`

**Comment by Morozzko** [comment]
> salt MINION slsutil.renderer default_renderer=jinja path=salt://xml.sls


Seems like empty string after minion
```
[root@ ~]# salt '*mq' slsutil.renderer default_renderer=jinja path=salt://xml.sls
minion-mq:
[root@ ~]#
```

**Comment by Morozzko** [comment]
Okey i found error, but got new one:
```
----------
    Rendering SLS 'base:xml' failed: while constructing a mapping
  in "<unicode string>", line 2, column 1
found conflicting ID 'ensure_value_true'
  in "<unicode string>", line 9, column 1

```

State:
```
{% for service, args in pillar.get('xml',{}).items() %}
ensure_value_true:
  xml.value_present:
    - name: {{ args['name'] }}
    - xpath: {{ args['xpath'] }}
    - value: {{ args['value'] }}

{% endfor %}
```
