### ISSUE TITLE
[BUG] trying to enforce user/group ownership, paths were missing

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack/salt#58027]
**Description**

Archive extracted fails to enforce user/group on particular filenames

**Setup**

I was testing java-formula PR on macOS: https://github.com/saltstack-formulas/java-formula/pull/13

**Steps to Reproduce the behavior**

On MacOS: 
Do https://github.com/saltstack/salt/issues/57742#issuecomment-658569444
Test java-formula: https://github.com/saltstack-formulas/java-formula/pull/13

**Expected behavior**

State should succeed.

**Screenshots**

```
          ID: java-package-archive-install
    Function: archive.extracted
        Name: /Library/Java/JavaVirtualMachines/adoptopenjdk-8-8u252-b09/
      Result: False
     Comment: /private/tmp/java_tmp_salt/java-archive.tar.gz extracted to /Library/Java/JavaVirtualMachines/adoptopenjdk-8-8u252-b09/, due to absence of one or more files/dirs. Output was trimmed to 100 number of lines
              
              While trying to enforce user/group ownership, the following paths were missing:
              
              - /Library/Java/JavaVirtualMachines/adoptopenjdk-8-8u252-b09/._jdk8u252-b09
              
              While trying to enforce user/group ownership, Salt was unable to change ownership on the following paths:
              
              - /Library/Java/JavaVirtualMachines/adoptopenjdk-8-8u252-b09/._jdk8u252-b09
     Started: 12:44:39.807768
    Duration: 1989.353 ms
     Changes:   
              ----------
              extracted_files:
                  - x Contents/
                  - x Contents/Home/
                  - x Contents/Info.plist
                  - x Contents/MacOS/
                  - x Contents/MacOS/libjli.dylib
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.15
         Jinja2: 2.10.1
        libgit2: 1.0.1
       M2Crypto: 0.35.2
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: 1.2.1
         Python: 3.7.8 (default, Jul  8 2020, 14:18:28)
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 3.0.4
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: darwin 19.6.0 
         locale: UTF-8
        machine: x86_64
        release: 19.6.0
         system: Darwin
        version: 10.15.6 x86_64
```
</details>

**Additional context**
