### ISSUE TITLE
[BUG] Docker ignores the credentials stored in /root/.docker/config.json

### ISSUE THREAD

**Issue by SantiMunoz** [saltstack/salt#58020]
**Description**
In salt 3000.3 docker ignores the credentials stored in `/root/.docker/config.json` and fails authenticating agains the private registry.

I'm using a masterless setup with salt 3000.3 without any docker registry defined in pillars, instead of that I have created the docker config file `/root/.docker/config.json` with the auth configuration from salt:
```yaml
/root/.docker/config.json:
  file.managed:
    - source: salt://docker/templates/docker-config.json.jinja
    - template: jinja
    - user: root
    - group: root
    - makedirs: True
    - mode: '0600'
```
This file contains a valid authentication credentials for artifactory.

Then when trying to pull an image I get the error `unknown: Authentication is required`

I've also tried to do a `docker.login` but got the same error
```yaml
authenticate-docker:
  module.run:
    - name: docker.login
    - require:
      - file: /root/.docker/config.json
```

From the [documentation](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockermod.html#authentication) I assume that Salt version 3000 should be able to authenticate docker using the config file instead of pillars.

When login to the machine I'm able to pull the image, I guess the user I'm using is correctly using the config file for  authentication.

**Expected behavior**
Docker to use the credentials stored in /root/.docker/config.json

**Versions Report**
Salt 3000.3
