### ISSUE TITLE
salt-cloud deploy script not working

### ISSUE THREAD

**Issue by poliscialex** [saltstack/salt#58081]
### Description of Issue
When deploying a droplet to digitalocean using salt-cloud, the droplet is successfully created, but salt-minion never installs.
First I get a number of messages saying this:
```
Warning: Permanently added '64.225.113.128' (ECDSA) to the list of known hosts.
root@64.225.113.128: Permission denied (publickey).
```
Then finally: `[ERROR   ] Failed to start Salt on host cdo-salt-02`

### Setup
Here is the providers.conf file we use for digital ocean:
```
do:
  driver: digitalocean
  personal_access_token: <REDACTED>
  ssh_key_file: /etc/salt/pki/cloud/do.pem
  ssh_key_names: <REDACTED>
  script: bootstrap-salt
  minion:
    master: <REDACTED>
  start_action: state.apply
```

### Steps to Reproduce Issue
spinning up a droplet using sudo salt-cloud -m path/to/cloud/map

### Versions Report
```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.2 (default, Jul 16 2020, 14:00:26)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-42-generic
         system: Linux
        version: Ubuntu 20.04 focal
```
