### ISSUE TITLE
[BUG] onlyif should run only if ALL commands return true

### ISSUE THREAD

**Issue by ari** [saltstack/salt#58085]
salt 3001.0

When using two onlyif statements, they are ORed rather than ANDed.

```
my_state:
  cmd.run:
    - name: rm -rf important_folder
  onlyif:
    - condition1
    - condition2
```
I would expect both conditions to be true before the state runs. In this case, only one is enough to trigger the state.

Either this should be fixed, or the documentation updated to make clear what happens in this case. Since unless and onlyif accept a list of commands, the behaviour should be well defined and documented.

**Comment by cmcmarrow** [comment]
```
ONLYIF
New in version 2014.7.0.

The onlyif requisite specifies that if each command listed in onlyif returns True, then the state is run. If any of the specified commands return False, the state will not run.
```
https://docs.saltstack.com/en/latest/ref/states/requisites.html

I think the documentation makes it clear that `onlyif` should be ANDed.

Can I get your state to see if a condition is failing?

**Comment by BrianSidebotham** [comment]
I am seeing this bug now - having spent the last hour and a half debugging a complex state.

The documentation clearly states that if ANY of the commands returns false the state will not run. However, that statement is not true. If just ONE of the commands returns true then the command is run.

Actually, it appears that onlyif is merely taking into account the last command in the list, as demonstrated by the contrived example below. Results are the same on 3000.3 and 3001.1:

`init.sls`:
```
mysql_user_present_should_not_be_attempted_1:
  pkg.installed:
    - name: non-existant-1
    - onlyif:
      - /bin/true
      - /bin/false

mysql_user_present_should_not_be_attempted_2:
  pkg.installed:
    - name: non-existant-2
    - onlyif:
      - /bin/false
      - /bin/true

mysql_user_present_should_not_be_attempted_3:
  pkg.installed:
    - name: non-existant-3
    - onlyif:
      - /bin/false
      - /bin/false
```

`state.apply test=true` output:

```
local:
----------
          ID: mysql_user_present_should_not_be_attempted_1
    Function: pkg.installed
        Name: non-existant-1
      Result: True
     Comment: onlyif condition is false
     Started: 22:09:13.681015
    Duration: 2317.67 ms
     Changes:   
----------
          ID: mysql_user_present_should_not_be_attempted_2
    Function: pkg.installed
        Name: non-existant-2
      Result: None
     Comment: The following packages would be installed/updated: non-existant-2
     Started: 22:09:15.999134
    Duration: 521.433 ms
     Changes:   
----------
          ID: mysql_user_present_should_not_be_attempted_3
    Function: pkg.installed
        Name: non-existant-3
      Result: True
     Comment: onlyif condition is false
     Started: 22:09:16.520907
    Duration: 27.124 ms
     Changes:  
```
