### ISSUE TITLE
[BUG] Cannot set highstate returner report_everything to False

### ISSUE THREAD

**Issue by aokiji** [saltstack/salt#58115]
**Description**
Cannot disable success report in highstate returner module

**Setup**

```
# /etc/salt/minion
highstate:
  report_failures: True
  report_everything: False
  report_format: html
  report_delivery: smtp
  smtp_success_subject: 'success minion {id} on host {host}'
  smtp_failure_subject: 'failure minion {id} on host {host}'
  smtp_server: smtp
  smtp_recipients: saltusers@example.com
  smtp_sender: salt@example.com
```

**Steps to Reproduce the behavior**
Configure salt minion highstate returner with report_everything set to False and run

```
salt minion state.highstate --return highstate
```
I have prepared a docker-compose setup to reproduce the problem:

```
git clone https://github.com/aokiji/saltstack-hightstate-returner
cd saltstack-hightstate-returner
docker-compose build
docker-compose up -d smtp
docker-compose run --rm saltstack-py3
```

Then open http://localhost:8025 in the browser to inspect emails sents by the returner

**Expected behavior**
Only send failure reports

**Versions Report**

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
         Jinja2: 2.9.4
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.5.3 (default, Jul  9 2020, 13:00:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9 stretch
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 5.6.13-100.fc30.x86_64
         system: Linux
        version: Debian GNU/Linux 9 stretch
```
