### ISSUE TITLE
[FEATURE REQUEST] Support checking/modifying the return of state.module.run

### ISSUE THREAD

**Issue by Timbus** [saltstack/salt#58114]
**Problem**
Today I was struggling to use the win_service.modify command from state.module.run in a way that would allow for some result-based followup actions. I ended up writing a custom state but I feel like it should have been possible without needing to use python.

**Solution**
If state.module.run offered an interface to allow for checking return values and using them to signal success/change/failure, I could have called win_service.info and checked the values, then chained the state using `onchange`. 
Strangely enough, loop.until_no_eval seems to offer something like this with the compare operator? But it's hardly fit for purpose.

**Alternatives + SEP thoughts**
Guess I'll also mention that exploring through other options like slots (yuck), state.cmd+`stateful`, and most of the requisites, seems to show there is a need for runtime variable-passing and logical operators (yes like registers from ansible), and having such a system would probably simplify a lot of states? Even being able to use thorium + custom events in my state mostly does the job. Dunno, just musing at this point.

**Comment by garethgreenaway** [comment]
@Timbus Thanks for the report.  Can you elaborate a bit more on what exactly you're looking to do?  Do you want to capture the results from state.module.run and run something based on that?  Is this within the same state run or multiple state runs?

**Comment by Timbus** [comment]
Well, this is a bit of an 'XY' problem I guess. 
For my very specific use case, problem 'X', I wanted the ability to manipulate/check the return value from module.run and use that value to possibly trigger an onchange for the next state. In short, it would allow building custom states without needing to write python.
I'm not a big fan of the design of the new `module.run` as it's not very extensible, but I used it as a guide to come up with something along the lines of:
```yaml
      some_id_of_state:
        module.run_with_check:
          - service.get_info:
            - name: salt-minion
          - tests:
            # Return whatever matches first. If none match return Changed, like module.run would
            - unchanged:
                compare_operator: data.subdict_match  # stolen from the 'loop' module
                expected: 'ServiceAccount:SaltyAdmin'
            - changed:
                compare_operator: data.subdict_match
                expected: 'ServiceAccount:LocalAdmin'
            - error:
                compare_operator: data.subdict_match
                expected: 'Startup:None'
```
Though it might be easier to just make a `state`.`function` module for this lower-level stuff.

But the general purpose summary of the bigger problem 'Y' is: States have no runtime variables! If you could just capture, manipulate, and test values, it would probably make a lot of states easier to build. Even existing, working concepts like `onlyif`, and slots, become easier to understand if you model it as passing a result from a required state to the requirer. And if we had vars and simple operators then the above enhancement probably wouldn't be needed.
