### ISSUE TITLE
[BUG] Snap.installed not avalable in 3001

### ISSUE THREAD

**Issue by cwray** [saltstack/salt#58132]
**Description**
State snap.installed is missing from 3001. Ubuntu and many other communities are using snaps more and more. 

This is extremely needed as time goes on. 

Case and point. Some maintainers are moving exclusively to snaps and away from standard repositories and PPA's because they are supported on most platforms.
https://github.com/certbot/certbot/issues/7950

**Certbot.sls**
```
add_certbot_snap:
  snap.installed:
    - name: certbot
```

**Run state**
```
doot@salt-master:~# salt 'salt-min*' state.apply certbot 
salt-min.lxd:
----------
          ID: add_certbot_snap
    Function: snap.installed
        Name: certbot
      Result: False
     Comment: State 'snap.installed' was not found in SLS 'certbot'
              Reason: 'snap.installed' is not available.
     Changes:   
```
**Versions Report**

```
doot@salt-master:~# salt -V
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.2 (default, Jul 16 2020, 14:00:26)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.0.0-32-generic
         system: Linux
        version: Ubuntu 20.04 focal
```
