### ISSUE TITLE
[BUG] On Windows Salt creates warning "AppEnvironmentExtra salt-minion" without description

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#58175]
**Description**
On Windows, Salt uses NSSM/SSM.  NSSM/SSM creates warning 
 `AppEnvironmentExtra salt-minion` without descripton in the Windows event log.

Warnings in the Windows event log sometimes could raise concern.

The Salt-Minion otherwise works, making this a minor issue

**Setup**
Install Salt-Minion 30001 on Windows.

Open Event Viewer, search for nssm Warnings, find 

```
The description for Event ID ### from source nssm cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

AppEnvironmentExtra
salt-minion

The message resource is present but the message was not found in the message table

``` 

**Expected behavior**
- The Salt-Minion should not create warnings when it seems to work fine.
- Warnings should have a description.

**Screenshot**
Salt-Minion 3001
![saltissue2](https://user-images.githubusercontent.com/8489107/90009639-b8b47880-dc9e-11ea-8c69-c659cb1f9b20.PNG)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0
```
</details>
