### ISSUE TITLE
[BUG] YAML rendering fails when passing empty strings

### ISSUE THREAD

**Issue by morsik** [saltstack/salt#58186]
**Description**
YAML rendering fails when passing empty strings. Because not-passing any value in YAML gives us `null` I needed to quote nothing, but quoting nothing gives strange results.

**Setup**
— `telegraf/init.sls`:
```yaml
telegraf-config:
  file.serialize:
  - name: /etc/telegraf/telegraf.conf
  - formatter: toml
  - dataset:
      {{ salt['pillar.get']('telegraf', default=defaults['telegraf'], merge=True)|yaml(False)|indent(6) }}
  - user: root
  - group: root
  - mode: 644
  - require:
    - telegraf-pkg
    - telegraf-python-deps
```

— `telegraf/defaults.yaml`:
```yaml
telegraf:
  global_tags: {}
  agent:
    interval: 60s
    debug: false
    round_interval: true
    flush_interval: 60s
    flush_jitter: 0s
    collection_jitter: 10s
    metric_batch_size: 10000
    metric_buffer_limit: 50000
    quiet: false
    logfile: ''  # <----------- THIS QUOTE CAUSES PROBLEM
    omit_hostname: false
```

**Steps to Reproduce the behavior**
Run something like above and you'll get:
```local:
    Data failed to compile:
----------
    Rendering SLS 'base:telegraf' failed: did not find expected alphabetic or numeric character
```

With `-l debug` you can see quotes changed to entities:
```yaml
telegraf-config:
  file.serialize:
  - name: /etc/telegraf/telegraf.conf
  - formatter: toml
  - dataset:
      agent:
        collection_jitter: 10s
        debug: false
        flush_interval: 60s
        flush_jitter: 0s
        interval: 60s
        logfile: &#39;&#39;        # <----------- broken?!
        metric_batch_size: 10000
        metric_buffer_limit: 50000
        omit_hostname: false
        quiet: false
        round_interval: true
```

This happens on Debian 10 with `python3-yaml=3.13-2` but not on Debian 9 with `python3-yaml=3.12-1` or Debian 8 with `python-yaml=3.11-2`.

**Expected behavior**
YAML rendering should contain quotes here to pass empty string properly, so output should be like this:
```yaml
telegraf-config:
  file.serialize:
  - name: /etc/telegraf/telegraf.conf
  - formatter: toml
  - dataset:
      agent:
        collection_jitter: 10s
        debug: false
        flush_interval: 60s
        flush_jitter: 0s
        interval: 60s
        logfile: ''        # <----------- correct empty string, not html entities
        metric_batch_size: 10000
        metric_buffer_limit: 50000
        omit_hostname: false
        quiet: false
        round_interval: true
```
And that's ↑ exactly that's generated on Debian 8 and Debian 9.

**Versions Report**
<details><summary>salt --versions-report</summary>

Salt Master is in 3001.3 version, not sure why… it's installed on Debian 9 and has newer Salt than Debian 10 (problematic one) while both using official SaltStack repositories?

```
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10 buster
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-9-cloud-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster

```
</details>
