### ISSUE TITLE
[Issue]  Salt does not start module

### ISSUE THREAD

**Issue by Mateo-neo** [saltstack/salt#58183]
I created archive.sls

*cat /srv/salt/salt/base/archive/init.sls*
```
    create-archive:
  module.run:
    - name: archive.cmd_zip
    - zip_file: /srv/salt/salt/base/Backup.zip
    - sources: "/opt/Backups/file"
    - runas: root
```
when i'm run  

```
salt server-SALTMASTER state.sls archive saltenv=base
```

i'm get 

```

server-SALTMASTER:
----------
          ID: create-archive
    Function: module.run
        Name: archive.cmd_zip
      Result: True
     Comment:
     Started: 08:25:23.492125
    Duration: 5.157 ms
     Changes:

Summary for server-SALTMASTER
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   5.157 ms

```
next

*/srv/salt/salt/base/ ls*
```
archive top.sls
```

There is no archive that should have been here. I think salt when executing modules.run does not define archive.cmd_zip as a module

*cat /etc/salt/master*

```
ipv6: False
file_roots:
    base:
      - /srv/salt/salt/base
    win:
      - /srv/salt/salt/windows

fileserver_backend:
         - roots

pillar_roots:
   win:
      - /srv/salt/salt/pillar
   base:
      - /srv/salt/salt/pillar
```

What could be the issue? Why is the archive not being created?
Can anyone help me? =(
