### ISSUE TITLE
how can i run an sls for a windows minion with a jinja variables

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#58209]
I have an a sls (salt/backup/archivecopy/init.sls) that makes an archive.zip and copy to the salt/backup/ folder.
I want to copy this archive on a windows minion.

archive have name:
```
{% set date = salt['cmd.run']('date --date= +%d_%m_%Y') %}
archiv{{ date }}.zip
```
When sls run on windows minion I get a big error that jinja cannot parse the date variable.
```
Rendering SLS 'backup:archivecopy' failed: Problem running salt function in Jinja template: Unable to run command 'date --date= +%d_%m_%Y' with the context 
```
if i use
```
{% set date = salt['cmd.powershell'](Get-Date -Format 'dd_MM_yyyy') %}
archive{{ date }}.sls
```
When sls run she gives output "true" but the file is not copied
sls:
```
copying-archive:
  module.run:
    - name: cp.get_file
    - path: salt://archve{{ date }}.zip
    - dest: Z://archive{{ date }}.zip
```
