### ISSUE TITLE
[BUG] some broken options in debian_eth.jinja for /etc/network/interfaces

### ISSUE THREAD

**Issue by tigpas** [saltstack/salt#58210]
**Description**
This Bug report extend the bug #58195. The last refactor (https://github.com/saltstack/salt/commit/5abe823e22e79f7667c9189fda7135331203358a) of  salt/templates/debian_ip/debian_eth.jinja broke some options, like {,pre,post}_{up,down}_cmds.

**Setup**
```
linux_interface_eno1:
  network.managed:
  - name: eno1
  - enabled: True
  - type: eth
  - proto: manual
  - up_cmds:
    - /bin/up_cmd1
    - /bin/up_cmd2
  - pre_up_cmds:
    - /bin/pre_up_cmd1
    - /bin/pre_up_cmd2
  - post_up_cmds:
    - /bin/post_up_cmd1
    - /bin/post_up_cmd2
  - down_cmds:
    - /bin/down_cmd1
    - /bin/down_cmd2
  - pre_down_cmds:
    - /bin/pre_down_cmd1
    - /bin/pre_down_cmd2
  - post_down_cmds:
    - /bin/post_down_cmd1
    - /bin/post_down_cmd2
```

**Steps to Reproduce the behavior**
`salt-call state.apply test` + `cat /etc/network/interfaces`

```
auto eno1
iface eno1 inet manual
```

**Expected behavior**
`cat /etc/network/interfaces`

```
auto eno1
iface eno1 inet manual
    up /bin/up_cmd1
    up /bin/up_cmd2
    down /bin/down_cmd1
    down /bin/down_cmd2
    pre-up /bin/pre_up_cmd1
    pre-up /bin/pre_up_cmd2
    post-up /bin/post_up_cmd1
    post-up /bin/post_up_cmd2
    pre-down /bin/pre_down_cmd1
    pre-down /bin/pre_down_cmd2
    post-down /bin/post_down_cmd1
    post-down /bin/post_down_cmd2
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10 buster
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-10-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster
```
</details>
