### ISSUE TITLE
[Issue] Unhandled exception running state.apply

### ISSUE THREAD

**Issue by Mateo-neo** [saltstack/salt#58234]
I have 2 .sls

1st copies and run .ps1 .ps2 script on windows - minion
```
1:
  file.managed:
      - source: salt://archive/1.ps1
      - name: C:\\1.ps1
      - template: jinja

2:
  file.managed:
      - source: salt://archive/2.ps1
      - name: C:\\2.ps1
      - template: jinja

3:
    cmd.run:
      - name: C:\\1.ps1
      - shell: powershell

4:
cmd.run:
      - name: C:\\2.ps1
      - shell: powershell
```
2nd  copies archive at windows - minion3 sls have ps command
```
{% set date = salt['cmd.run']('powershell.exe Get-Date -Format "dd_MM_yyyy"') %}

6:
  module.run:
    - name: cp.get_file
    - path: salt://Backup{{ date }}.zip?saltenv=env
    - dest: {{ pillar['Volume'] }}
    - makedirs: True
```
schedule.sls
```
archive:
  schedule.present:
    - function: state.apply
    - job_args:
      -archiv
    - job_kwargs:
        saltenv: env
    - when:
      - Monday 9:00pm
      - Tuesday 9:00am
      - Wednesday 9:00am
      - Thursday 9:00am
      - Friday 9:00am
      - Saturday 9:00am
      - Sunday 9:00am

```
Next - salt "*Minion" state.sls scheduler saltenv=env
```
schedule:
      archive:
        args:
        - archive
        enabled: true
        function: state.apply
        jid_include: true
        kwargs:
          saltenv: env
        maxrunning: 1
        name: archive
        when:
        - Monday 9:00pm
        - Tuesday 9:00am
        - Wednesday 9:00am
        - Thursday 9:00am
        - Friday 9:00am
        - Saturday 9:00am
        - Sunday 9:00am

```
Next - salt "*Minion" schedule.run_job archive. it return:
```
Unhandled exception running state.sls
```
on windows-minion i see 1.ps1 and 2.ps1 
```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: 3.4.1
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: 0.27.7
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 0.27.4
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10 buster
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster
```

**Comment by garethgreenaway** [comment]
@Mateo-neo Thanks for the report.  The state file that you referenced in the scheduler, are you able to run that state file manually and does it work as expected?

**Comment by Mateo-neo** [comment]
> @ Mateo-neo Спасибо за отчет. Файл состояния, на который вы ссылались в планировщике, можете ли вы запустить этот файл состояния вручную и работает ли он должным образом?

ofc. if i run 
```
salt "*MINION" state.apply state saltenv=env
```
or
```
salt "*MINION" schedule.run_job archive
```
It works. I am getting result. Files are copied. Scripts run and perform the required functions

**Comment by Mateo-neo** [comment]
little change.
schedule.sls

```
archive:
  schedule.present:
    - function: state.apply
    - job_kwargs:
        saltenv: env
    - when:
      - Monday 9:00pm
      - Tuesday 9:00am
      - Wednesday 9:00am
      - Thursday 9:00am
      - Friday 9:00am
      - Saturday 9:00am
      - Sunday 9:00am
```
Now
```
salt "*GET" schedule.run_job archive
```
Work
But launching through the scheduler still does not work

**Comment by Mateo-neo** [comment]
Ok i get it. 
If I tell him to be executed through "seconds" he works, and if I tell him the days of the week he does not work

```
Create_archive:
  schedule.present:
    - function: state.apply
    - job_kwargs:
        saltenv: backup
    - seconds: 100
```

**Comment by Mateo-neo** [comment]
I don't know how but it's work!
```
archive:
  schedule.present:
    - function: state.apply
    - job_kwargs:
        saltenv: backup
    - when:
        - Monday 8:00pm
        - Tuesday 8:00pm
        - Wednesday 8:00pm
        - Thursday 8:00pm
        - Friday 8:00pm
```
