### ISSUE TITLE
[BUG] svn.latest does not trigger update on windows

### ISSUE THREAD

**Issue by paul-wie** [saltstack/salt#58329]
**Description**

I am using svn.latest in my project to update/checkout files from svn. The minion is running on a Windows machine, therefore I am using a path like "C:\salt_folder\subfolder" as target path.
With this setup, a svn.update will never be triggered.

I figured out, that https://github.com/saltstack/salt/blob/master/salt/states/svn.py in line 150 is using the target parameter for a svn.info that causes an error, which can bee seen in the log files:

```
2020-08-31 13:40:39,128 [salt.loaded.int.module.cmdmod:854 ][ERROR   ][324024] Command '['svn', '--non-interactive', 'info', 'C:salt_foldersubfolder', '--username', 'username', '--password', 'password']' failed with return code: 1
2020-08-31 13:40:39,129 [salt.loaded.int.module.cmdmod:858 ][ERROR   ][324024] stderr: svn: E155007: 'C:\salt_folder\salt_foldersubfolder' is not a working copy
2020-08-31 13:40:39,129 [salt.loaded.int.module.cmdmod:860 ][ERROR   ][324024] retcode: 1
```

The checkout works because it is using the basename instead of tartget (https://github.com/saltstack/salt/blob/master/salt/states/svn.py , line 188):

```
out = __salt__[svn_cmd](cwd, name, basename, user, username, password, *opts)
```

```
Minion:
----------
          ID: update_or_checkout_svn
    Function: svn.latest
        Name: svn-repo
      Result: True
     Comment: Checked out revision 123.
     Started: 13:40:39.067251
    Duration: 518.717 ms
     Changes:
              ----------
              new:
                  svn-repo
              revision:
                  42280

Summary for Minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 518.717 ms

```

I could fix it by using ``` \\ ``` insted of ``` \``` for the target path. But for me it looks a little bit inconsistent. 
Also when using grains I need to perfom more advanced replace logic.

**Setup**

```
update_or_checkout_svn:
  svn.latest:
    - name: svn_repo
    - username: username
    - password: password
    - target: C:\salt_folder\subfolder
    - trust: True

```

**Expected behavior**
svn.latest should trigger an update

**Versions Report**

Master

```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10 buster
         locale: utf-8
        machine: x86_64
        release: 4.4.121-92.129-default
         system: Linux
        version: Debian GNU/Linux 10 buster
```

Minion

```
    Salt Version:
               Salt: 3001.1

    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.10
             Jinja2: 2.10.1
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 1.0.0
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.9.7
             pygit2: Not Installed
             Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 5.3.1
              PyZMQ: 18.0.1
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.17763 SP0

```
</details>

**Comment by dwoz** [comment]
I think it's pretty common to need to escape the back slashes on windows paths in sls files.

@twangboy @damon-atkins does this seem right?

> 
> I could fix it by using `\\` insted of ` \` for the target path. But for me it looks a little bit inconsistent.
> Also when using grains I need to perfom more advanced replace logic.
> 

Can you please explain what you mean by 'perform more advanced replace logic'?

**Comment by paul-wie** [comment]
I have different target paths for different machines in the machine.configuration:
 
`GRAIN_TARGET_DIR: 'C:\\salt_folder\\subfolder'`

But when I am using this grain in the state I described:

```
update_or_checkout_svn:
  svn.latest:
    - name: svn_repo
    - username: username
    - password: password
    - target: {{ grains['target_dir'] }}
    - trust: True
```
then I will get the error I descriebed above. Somehow, target_dir will be treated as `C:\salt_folder\subfolder` when calling svn.latest and lead to the reported error. Therefore svn.update will never be triggered.

I found a workaround using jinja's replace machanism (what I meant with "advanced" replace logic):

```
update_or_checkout_svn:
{% set target_grain = grains['target_dir'] %}
{% set target_replaced = target_grain.replace('\\', '\\\\') %}
  svn.latest:
    - name: svn-repo
    - username: username
    - password: password
    - target: {{ target_replaced }}
    - trust: True
```

This gives me the expected behavior:
- svn.checkout if repo is not checked out
- svn.update if repo is checked out

But anyway, I have some considerations:
- Is this how svn.latest should be used? Do I misuse svn.latest? For me it doesen't seem very intuitive. 
- Could the interface be adjusted to increase the usability?
