### ISSUE TITLE
[BUG] Creating a Xen Virtual machine shouldn't produce volume disks

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#58333]
**Description**

Since 3001, when creating a Xen fully or para virtualized VM, the disks are defined using libvirt volumes like the following:

```
    <disk type='volume' device='disk'>
      <driver name='qemu' type='qcow2' cache='none' io='native'/>
      <source pool='default' volume='vm03_system'/>
      <target dev='xvda' bus='xen'/>
    </disk>
```

Even if this is valid libvirt XML configuration, the libvirt `libxl` driver doesn't handle volumes. Use file-based disks where possible.

**Setup**

Example state defining a VM with a disk like the above mentioned:

```
domain_define:
    virt.running:
        - name: vm03
        - cpu: 1
        - mem: 512
        - os_type: xen
        - arch: x86_64
        - vm_type: xen
        - disks:
            - name: system
              model: xen
              device: disk
              format: qcow2
              pool: default
              image: /var/testsuite-data/disk-image-template-xenpv.qcow2
        - interfaces:
            - name: eth0
              type: network
              source: default
        - graphics:
            type: vnc
```
