### ISSUE TITLE
[DOCS] salt.states.firewalld.present has no documentation/examples for how to use rich_rules

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#58360]
**Description**
The documentation for salt.states.firewalld.present at https://docs.saltstack.com/en/latest/ref/states/all/salt.states.firewalld.html#salt.states.firewalld.present has no examples/documentation on how to use rich_rules

**Expected behavior**
At least one example of how to use rich_rules would be helpful for the purposes of implementing them:

```
    - rich_rules:
        - rule protocol value="icmp" accept
        - rule protocol value="ipv6-icmp" accept
        - rule service name="snmp" accept
```
along with a note that the rules should exactly match the output of:

`# firewall-cmd --list-rich-rules`

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: 0.26.8
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-193.6.3.el8_2.x86_64
         system: Linux
        version: CentOS Linux 8 Core
```
</details>

**Comment by racooper** [comment]
I definitely agree that firewalld rich_rules docs are lacking.  Is this correct?
```
public:
  firewalld.present:
    - name: public
    - rich rules:
      - family: ipv4
      - source:
        - address: 10.0.0.1/32
      - port:
        - port: 1522
      - protocol: tcp
      - accept: True
    - prune_rich_rules: False
```
Or is this?
```
snmpd-firewall:
  firewalld.present:
    - name: public
    - rich_rules:
      - rule family="ipv4" source address="10.0.0.1" port port="161" protocol="udp" accept
    - prune_rich_rules: False
    - prune_services: False
```
I've seen examples both ways so I'm not sure which is 'correct'.
