### ISSUE TITLE
[BUG] x509.certificate_managed TypeError when using append_certs

### ISSUE THREAD

**Issue by tqre** [saltstack/salt#58481]
**Description**
Creating certificate chains, ie. making one file of multiple certificates fails with x509 module.

**Setup**
Basic localized master/minion setup with the following state:
`cert.sls`
```
key1:
  x509.private_key_managed:
    - name: /home/salt/venv/certs/key.pem

cert1:
  x509.certificate_managed:
    - name: /home/salt/venv/certs/cert.pem
    - signing_private_key: /home/salt/venv/certs/key.pem
    - require:
      - x509: key1

key2:
  x509.private_key_managed:
    - name: /home/salt/venv/certs/key2.pem
  
cert2:
  x509.certificate_managed:
    - name: /home/salt/venv/certs/cert2.pem
    - signing_private_key: /home/salt/venv/certs/key2.pem
    - append_certs: 
      - /home/salt/venv/certs/cert.pem 
    - require:
      - x509: key2
```
**Steps to Reproduce the behavior**
```
$ salt '*' state.apply cert
localminion-dev:
----------
          ID: key1
    Function: x509.private_key_managed
        Name: /home/salt/venv/certs/key.pem
      Result: True
     Comment: File /home/salt/venv/certs/key.pem is in the correct state
     Started: 16:10:58.605159
    Duration: 13.318 ms
     Changes:   
----------
          ID: cert1
    Function: x509.certificate_managed
        Name: /home/salt/venv/certs/cert.pem
      Result: True
     Comment: Certificate /home/salt/venv/certs/cert.pem is valid and up to date
     Started: 16:10:58.618687
    Duration: 5.903 ms
     Changes:   
----------
          ID: key2
    Function: x509.private_key_managed
        Name: /home/salt/venv/certs/key2.pem
      Result: True
     Comment: File /home/salt/venv/certs/key2.pem is in the correct state
     Started: 16:10:58.624656
    Duration: 0.966 ms
     Changes:   
----------
          ID: cert2
    Function: x509.certificate_managed
        Name: /home/salt/venv/certs/cert2.pem
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/home/salt/salt/state.py", line 2157, in call
                  ret = self.states[cdata["full"]](
                File "/home/salt/salt/loader.py", line 2097, in wrapper
                  return f(*args, **kwargs)
                File "/home/salt/salt/states/x509.py", line 718, in certificate_managed
                  contents += append_file_contents
              TypeError: can only concatenate str (not "bytes") to str
     Started: 16:10:58.625773
    Duration: 3.961 ms
     Changes:   

Summary for localminion-dev
------------
Succeeded: 3
Failed:    1
------------
Total states run:     4
Total run time:  24.148 ms
ERROR: Minions returned with non-zero exit code
```
**Expected behavior**
The certificates are appended correctly.

**Versions Report**
<details><summary>salt --versions-report</summary>
```
Salt Version:
           Salt: 3001.1-481-gf534d4de9a
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.36.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.8.5 (default, Sep  5 2020, 10:50:12)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: arch rolling n/a
         locale: utf-8
        machine: x86_64
        release: 5.8.9-arch2-1
         system: Linux
        version: Arch Linux rolling n/a
</details>

**Additional context**
A simple type conversion fixes this, and shouldn't break anything. I'll submit a pull request soon.

**Comment by sagetherage** [comment]
Thank you for the PR! I will try to get this triaged quickly!

**Comment by joachimtingvold** [comment]
Dirty quickfix until patch arrives;

```
bugfix_salt_states_x509:
  file.replace:
    - name: /usr/lib/python3/dist-packages/salt/states/x509.py
    - pattern: 'contents \+\= append_file_contents'
    - repl: |
        contents += str(append_file_contents.decode('utf-8'))
    - backup: false
    - ignore_if_missing: true
```
