### ISSUE TITLE
Source file salt://SQLProvision.sh not found in saltenv 'base'

### ISSUE THREAD

**Issue by ronak2303** [saltstack/salt#58497]
### Description of Issue
i have setup git repository in srv/salt/master.d/gitsetup.conf, i am trying to copy file from gitfs to minion using test1.sls but i am getting error "Source file salt://SQLProvision.sh not found in saltenv 'base'"

i noticed that 1 file i can update it but i am not able to copy new files.

i am able to clone my repo to salt master.

i have checked issue [BUG] pillar.get doesn't respect saltenv minion setting #56624 and Comment: Source file not found in saltenv 'base' #56684, but no usefull info.

### Setup
/etc/salt/master.d/gitsetup.conf
```
gitfs_provider: gitpython

fileserver_backend:
  - gitfs
  - roots

gitfs_update_interval: 300

gitfs_ref_types:
  - branch

gitfs_remotes_sqlautomation:
  - ssh://git@xxxxxxxx/sqlautomation.git:
     - saltenv:
       - base:
         - ref: master
       - dev:
         - ref: develop

gitfs_remotes_gsseng:
  - ssh://git@xxxxxxxx/gsseng.git
     - saltenv:
       - base:
         - ref: develop
       - dev:
         - ref: develop
```
/srt/salt/test1.sls
```
set HOME variable:
 environ.setenv:
   - name: HOME
   - value: /root
   - update_minion: True

copy test:
 file.managed:
   - name: /home/SQLProvision.sh
   - source: salt://SQLProvision.sh
```
### Steps to Reproduce Issue
i am not sure what steps to reproduce this as there is not other steps i have done.

### Versions Report
salt --versions-report
Salt Version:
           Salt: 2019.2.4

Dependency Versions:
           cffi: 1.14.1
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.1.15
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 11 2019, 14:33:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 3.0.4
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.7 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.4.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.7 Maipo
