### ISSUE TITLE
[DOCS] Give some better examples for working with LGPO

### ISSUE THREAD

**Issue by prensing** [saltstack/salt#58521]
**Description**
I am trying to set the Windows LGPO "Minimum PIN length" (aka MSPassport_MinimumPINLength). I get the error:
    The policy "MSPassport_MinimumPINLength" has elements which must be configured

When I look at the policy info, I get:
```
    ----------
    message:
    policy_aliases:
        - Minimum PIN length
        - MSPassport_MinimumPINLength
        - System\PIN Complexity\Minimum PIN length
    policy_class:
        machine
    policy_elements:
        |_
          ----------
          element_aliases:
              - MSPassport_MinimumPINLengthDataType
              - Minimum PIN length
          element_id:
              MSPassport_MinimumPINLengthDataType
    policy_found:
        True
    policy_name:
        MSPassport_MinimumPINLength
    rights_assignment:
        False
```
so there are elements. However, I cannot figure out how to set them. There are no examples in the documentation. "MSPassport_MinimumPINLengthDataType" does not seem to be found anywhere, including a Google search. The element_aliases does seem to be kind of circular.

**Setup**
normal setup. master is Linux.

**Steps to Reproduce the behavior**
salt --timeout 120 host lgpo.set_computer_policy 'System\PIN Complexity\Minimum PIN length' 6

**Expected behavior**
Hope that the value will be set. If something additional needs to be done, need clearer instructions.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 
From the minion:

```
artemis:
    Salt Version:
               Salt: 3001.1
     
    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.10
             Jinja2: 2.10.1
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 1.0.0
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.9.7
             pygit2: Not Installed
             Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 5.3.1
              PyZMQ: 18.0.1
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.18362 SP0
```
</details>

**Additional context**
