### ISSUE TITLE
[BUG] Vault command errors configured locally

### ISSUE THREAD

**Issue by jtraub91** [saltstack/salt#58580]
**Description**
When configuring vault for use with a masterless command, e.g. `salt-call --local`, I am getting an error when running `vault.read_secret`.

**Setup**
_minion.d/vault.conf_
```
vault:
  url: sdb://yaml/vault_url
  verify: False
  auth:
    method: approle
    role_id: sdb://yaml/role_id
    secret_id: sdb://yaml/secret_id
  policies:
    - saltstack/minions
    - saltstack/minions/{minion}
```
_minion.d/sdb.conf_
```
yaml:
  driver: yaml
  files:
    - /etc/salt/vault_token.yaml
```
_/etc/salt/vault_token.yaml_
```
vault_url: https://x.x.x.x:yyyy
role_id: xxxxxxx
secret_id: xxxxxxx
```

**Steps to Reproduce the behavior**
```
salt-call --local vault.read_secret <path> <key>
```

**Expected behavior**
Should return the value of the `<key>` at `<path>`. Instead I am getting the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/modules/vault.py", line 209, in read_secret
    response = __utils__["vault.make_request"]("GET", url)
  File "/usr/lib/python3.6/site-packages/salt/utils/vault.py", line 342, in make_request
    connection["uses"] -= 1
KeyError: 'uses'
```

**Versions Report**
```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.14.1
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 4.2.0
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```
