### ISSUE TITLE
[BUG] unable to use the shell command to switch to powershell 7 which is not the default powershell.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#58598]
**Description**
in windows before the release of powershell 7 the only to official shells were `cmd` which is the default shell and `powershell 5.1` 

And it was ok. However powershell 7 introduced something new into the world and now you can't use powershell 7 as the shell in salt because the shell option for cmd.run ignores everything except `powershell` which uses the system default powershell. 

**Setup**
salt on windows

**Steps to Reproduce the behavior**

```
PS C:\salt\bin\Lib\site-packages\salt-3001.1-py3.7.egg\salt\grains> c:\salt\salt-call cmd.run_all 'Write-Output test' shell='c:\Program Files\PowerShell\7\pwsh.exe'
[ERROR   ] Command 'chcp 437 > nul & Write-Output test' failed with return code: 1
[ERROR   ] stderr: 'Write-Output' is not recognized as an internal or external command,
operable program or batch file.
[ERROR   ] retcode: 1
local:
    ----------
    pid:
        27816
    retcode:
        1
    stderr:
        'Write-Output' is not recognized as an internal or external command,
        operable program or batch file.
    stdout:
PS C:\salt\bin\Lib\site-packages\salt-3001.1-py3.7.egg\salt\grains>
```

The command shown does run fine under either powershell. 

```
PS C:\salt\bin\Lib\site-packages\salt-3001.1-py3.7.egg\salt\grains> chcp 437 > nul & Write-Output test

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
3      Job3            BackgroundJob   Running       True            localhost            Microsoft.PowerShell.Man…
test
```

**Expected behavior**
using shell I would be able to use powershell 7. just as in Linux I can use shell to set the shell that Linux runs the command with.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.3.1
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.19041 SP0

```
</details>

**Additional context**
