### ISSUE TITLE
[BUG] visible_name is ignored by zabbix_host.present

### ISSUE THREAD

**Issue by piterpunk** [saltstack/salt#58602]
**Description**
The optional parameter visible_name is ignored by zabbix_host.present. This happens because it's not passed to host_create in zabbix.py execution module:
```
369         host_create = __salt__["zabbix.host_create"](
370             host,
371             groups,
372             interfaces_formated,
373             proxy_hostid=proxy_hostid,
374             inventory=new_inventory,
375             **connection_args
376         )
```

**Setup**
Slackware machines running Salt 3001 managing hosts in a Zabbix 5.0 server, also running on Slackware. The rendered state being applied is:
```
create-zabbix-host-bat.mylab:
  zabbix_host.present:
    - _connection_user: XXXXXXXXXX
    - _connection_password: XXXXXXXXXX
    - _connection_url: http://XXXXXXXXX/zabbix/api_jsonrpc.php
    - host: bat.mylab
    - visible_name: Cobra BAT
    - require_in:
      - assign-template-host-bat.mylab
    - groups:
      - Linux Desktops
    - interfaces:
      - 127.0.0.1_agent:
        - interface1: None
        - ip: 127.0.0.1
        - dns: bat.mylab
        - useip: False
        - type: agent
        - port: 10050
```

**Steps to Reproduce the behavior**
Write a state that creates a new host on Zabbix with a visible_name. The new host will be created, but the visible_name will be empty.

**Expected behavior**
It's expected to create a host in Zabbix with the "Visible Name" set as specified in state.

**Versions Report**
<details><summary>salt --versions-report</summary>
```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.36.0
           Mako: 1.1.3
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.8.6 (default, Sep 24 2020, 18:13:36)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: slackware 14.2 current
         locale: utf-8
        machine: x86_64
        release: 5.4.66
         system: Linux
        version: Slackware 14.2 current
```
</details>
