### ISSUE TITLE
[BUG] inotifiy beacons erroring 

### ISSUE THREAD

**Issue by ssoto2** [saltstack/salt#58616]
**Description**
When creating a multiple inotify beacons the beaconing system will throw an error

**Setup**
beacon.conf
```
beacons:
  service:
    - services:
        NAMEREMOVED:
          onchangeonly: True
          delay: 60
    - disable_during_state_run: True
  btmp: []
  httpd.inotify:
    - files:
        /etc/httpd/vhost.d:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
        /etc/httpd/conf.d:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
        /etc/httpd/conf:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
    - coalesce: True
    - disable_during_state_run: true
    - beacon_module: inotify
    - interval: 10
  tomcat.inotify:
    - files:
        /etc/tomcat/conf.d:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
        /etc/tomcat/saml:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
        /etc/tomcat/metadata:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
        /etc/tomcat/NAMEREMOVED.xml:
          mask:
            - delete_self
            - modify
    - coalesce: True
    - disable_during_state_run: true
    - beacon_module: inotify
    - interval: 10
```

**Steps to Reproduce the behavior**

When the beacon conf above is filed for a file modification it will throw an error 

```
2020-10-02 14:06:35,564 [salt.minion      :2613][CRITICAL][15933] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2611, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 489, in process_beacons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=no-member
  File "/usr/lib/python2.7/site-packages/salt/beacons/__init__.py", line 117, in process
    raw = self.beacons[fun_str](b_config[mod])
  File "/usr/lib/python2.7/site-packages/salt/beacons/inotify.py", line 245, in beacon
    excludes = _config['files'][path].get('exclude', '')
KeyError: '/'
```
If the config is changed to the following then the beacon works:
```
beacons:
  service:
    - services:
        NAMEREMOVED:
          onchangeonly: True
          delay: 60
    - disable_during_state_run: True
  btmp: []
  inotify:
    - files:
        /etc/httpd/vhost.d:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
        /etc/httpd/conf.d:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
        /etc/httpd/conf:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
        /etc/tomcat/conf.d:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
        /etc/tomcat/saml:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
        /etc/tomcat/metadata:
          mask:
            - delete
            - modify
          recurse: True
          auto_add: True
          exclude:
            - /etc/httpd/vhost.d/.+?\.sw[px]*$|4913|~$:
                regex: True
        /etc/tomcat/NAMEREMOVED.xml:
          mask:
            - delete_self
            - modify
    - coalesce: True
    - disable_during_state_run: true
    - beacon_module: inotify
    - interval: 10
```

**Expected behavior**
Per the documentation https://docs.saltstack.com/en/3000/topics/beacons/ the non working conf should work fine

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

Minion Version Report
```
salt-minion --versions-report
/usr/lib/python2.7/site-packages/salt/scripts.py:212: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  2 2020, 13:16:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.19.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core
```

Master 
```
salt --versions-report
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```
</details>

**Additional context**
