### ISSUE TITLE
[BUG] pecl.installed does not work behind proxy

### ISSUE THREAD

**Issue by crosscodr** [saltstack/salt#58613]
**Description**
The pecl.installed state fails behind a proxy server.
This could be mitigated with different aproaches (see below).

**Setup**
Sample state:

```yaml
install-php-yaz:
  pecl.installed:
    - name: yaz
    - defaults: true
```

**Steps to Reproduce the behavior**
Run a pecl.installed stated on a server behind a proxy-server.
This is a sample log output from _/var/log/salt/minion_:

> 2020-10-02 16:42:50,842 [salt.loaded.int.module.cmdmod:854 ][ERROR   ][2412048] Command 'yes '' | pecl -d preferred_state=stable install yaz' failed with return code: 1
> 2020-10-02 16:42:50,843 [salt.loaded.int.module.cmdmod:856 ][ERROR   ][2412048] stdout: Connection to `ssl://pecl.php.net:443' failed: Connection timed out
> 2020-10-02 16:42:50,843 [salt.loaded.int.module.cmdmod:860 ][ERROR   ][2412048] retcode: 1
> 2020-10-02 16:42:50,844 [salt.loaded.int.module.pecl:55  ][ERROR   ][2412048] Problem running pecl. Is php-pear installed?
> 

**Expected behavior**
It is possible to install pecl packages behind a proxy.

A solution could be to create an option for pecl.installed to pass "-c <config-file>" to pecl.
This config-file could then contain a proxy-server setting.
Another way could be to use _pecl config-set http_proxy <proxy-server>_ just before the _pecl install_ command.

**Workaround**
The following can be used as workaround. Just do it with cmd.run, as pecl.installed would do.
```yaml
pear_proxy_config:
  file.managed:
    - name: /tmp/pearrc
    - contents:
      - '#PEAR_Config 0.9'
      - 'a:2:{s:10:"__channels";a:3:{s:5:"__uri";a:0:{}s:11:"doc.php.net";a:0:{}s:12:"pecl.php.net";a:0:{}}s:10:"http_proxy";s:42:"http://<proxy-server>:<port>";}'

install-php-yaz:
  cmd.run:
    - name: yes "" | pecl -c /tmp/pearrc install yaz
    - unless:
      - "pecl list | grep yaz"
    - require:
      - pear_proxy_config
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.2 (default, Jul 16 2020, 14:00:26)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-48-generic
         system: Linux
        version: Ubuntu 20.04 focal
```
</details>

**Additional context**
