### ISSUE TITLE
[BUG]: zabbix_host.present fails to add a SNMP interface in Zabbix 5.0

### ISSUE THREAD

**Issue by piterpunk** [saltstack/salt#58620]
**Description**
zabbix_host.present fails to create a SNMP interface in Zabbix 5.0 because it requires new mandatory parameters. From [Zabbix documentation](https://www.zabbix.com/documentation/current/manual/api/reference/hostinterface/object):

| Property | Type  | Description                                                             |
|----------|-------|-------------------------------------------------------------------------|
| details  | array | Additional object for interface. *Required* if interface 'type' is SNMP.|

Inside "details"  are other mandatory properties, depending on SNMP version and security level.

**Setup**
Slackware machines running Salt 3001 managing hosts in a Zabbix 5.0 server, also running on Slackware. The rendered state being applied is:
```
create-zabbix-host-longshot:
  zabbix_host.present:
    - _connection_user: XXXXXXXXXX
    - _connection_password: XXXXXXXXXXX
    - _connection_url: http://XXXXXXXXXX/zabbix/api_jsonrpc.php
    - host: longshot.mylab
    - visible_name: "Longshot"
    - description: "Imaginary Friend"
    - groups:
        - "Network Devices"
    - interfaces:
        - interface1:
          - ip: 127.0.0.1
          - dns: longshot.mylab
          - useip: false
          - type: snmp
```
The error is:
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/salt/state.py", line 2153, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib64/python3.8/site-packages/salt/loader.py", line 2087, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/salt/states/zabbix_host.py", line 369, in present
    host_create = __salt__["zabbix.host_create"](
  File "/usr/lib64/python3.8/site-packages/salt/modules/zabbix.py", line 1176, in host_create
    ret = _query(method, params, conn_args["url"], conn_args["auth"])
  File "/usr/lib64/python3.8/site-packages/salt/modules/zabbix.py", line 190, in _query
    raise SaltException(
salt.exceptions.SaltException: Zabbix API: Invalid params. (Incorrect arguments passed to function.)
```

**Steps to Reproduce the behavior**
Try to create or update a host with a SNMP interface in Zabbix 5.0 with zabbix_host.present state.

**Expected behavior**
It's expected to create the SNMP interface without major issues.

**Versions Report**
<details><summary>salt --versions-report</summary>
```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.36.0
           Mako: 1.1.3
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.8.6 (default, Sep 24 2020, 18:13:36)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 19.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: slackware 14.2 current
         locale: utf-8
        machine: x86_64
        release: 5.4.66
         system: Linux
        version: Slackware 14.2 current
```
</details>
