### ISSUE TITLE
[DOCS] Add rstcheck (or equivelant rst verification) to pre-commit

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt#58668]
**Description**

It would be great if we could add `rstcheck` to our pre-commit for docs related changes. We'd need to implement it in the same way we have implemented Python 2 deprecation where it only applies to new .rst file revisions and/or files.

This would be an excellent step to adding automated checks against the rst formatting that otherwise are only verified at Sphinx build, which will still build even when certain rst formatting errors are present.

This is currently being done via the formula templates in the SaltStack Formulas org:

https://github.com/saltstack-formulas/template-formula/blob/46e68213a1203d1d28217481f1b1746fdd43b555/.pre-commit-config.yaml#L50-L55

**Suggested Fix**

Add the following to pre-commit, but with any needed modifications related to "new file" or "on change" so that the test suite doesn't break.

**.pre-commit-config.yml**

```yaml
  - repo: https://github.com/myint/rstcheck
    rev: 3f92957
    hooks:
      - id: rstcheck
        name: Check reST files using rstcheck
        args: [--report=warning]
```
