### ISSUE TITLE
[3002rc1] [Bug] Time increase running commands in 3002rc1 compared to 3001.1.

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#58716]
**Description**

I see on 3002rc1 it takes about 4-5 seconds longer than on 3001.1 to run a state file.

3001.1 is around 6-7 sec while 3002rc1 is around 11-12 sec, roughly when running state multiple times.

3001.1:
```
real	0m7.092s
user	0m0.648s
sys	0m0.048s
[root@li882-151 ~]# salt --version
salt 3001.1
```
3002rc1:
```
real	0m11.835s
user	0m1.249s
sys	0m0.085s
[root@li743-118 ~]# salt --version
salt 3002rc1
```

**Setup**
Install the 3002rc1 and run state file.
Install 3001.1 and compare results.
Make sure both machines are the same OS, with same specs for best comparison.

This is the state file I used:
```
test1:
  cmd.run:
    - name: "echo 'This is a test!'"
test2:
  pkg.removed:
    - name: nano
test3:
  pkg.installed:
    - name: nano
test4:
  user.present:
    - name: test
test5:
  user.absent:
    - name: test
test6:
  file.managed:
    - name: /tmp/test
test7:
  file.absent:
    - name: /tmp/test

```

**Expected behavior**
I expect the time it takes to run the state file to be close to the same on both versions.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3002rc1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 5.8.3-x86_64-linode137
         system: Linux
        version: CentOS Linux 7 Core

```
