### ISSUE TITLE
[BUG] Windows environ.setenv is not passed to cmd.run spawned processes

### ISSUE THREAD

**Issue by Timbus** [saltstack/salt#58774]
**Description**
Windows doesn't pass the current minion environment to any spawned processes using cmd._run
It is instead using a copy of the environment set in nt.env, which is not updated if the minion updates: https://github.com/saltstack/salt/blob/998c382f5f2c3b4cbf7d96aa6913ada6993909b3/salt/modules/cmdmod.py#L601-L604

Either environ.setenv/setval need to update the nt.environ hash (if possible?), or cmd.run needs to build a correct copy of the env before spawning processes, somehow.

Using `permanent` or `update_minion` will not work around this issue, they only fix subsequent runs of the state.

**Setup**
testenv.sls:
```sls
set env:
  environ.setenv:
    - name: TEST_ENV_VAR
    - value: hello there
{%if grains['os'] == 'Windows'%}
spawn a windows test:
  cmd.run:
    - name: $env:TEST_ENV_VAR -eq "hello there"
    - shell: powershell
{%else%}
spawn a linux test:
  cmd.run:
    - name: >-
        [[ $TEST_ENV_VAR == "hello there" ]]
{%endif%}
```

**Steps to Reproduce the behavior**
salt '*' state.apply testenv

It will work as expected on linux, windows will not have the env var in the shell and returns False

**Expected behavior**
Both windows and linux shells have the environment variable set.

**Comment by garethgreenaway** [comment]
@Timbus Thanks for the report.

**Comment by Timbus** [comment]
Just a quick follow up: I also noticed that using `runas` completely bypasses this code path on windows, so setting an env doesn't work at all in that case.. And while I was testing that, noticed setting a CWD with a space also trips up win_runas
 -_-

**Comment by ggiesen** [comment]
I'm seeing something similar.

If I run the execution module directly, it works:

```bash
salt minion cmd.powershell_all 'Write-Output $Env:ZOO $Env:windir' env='{"ZOO": "BAR"}'
minion:
    ----------
    pid:
        15896
    result:
        - BAR
        - C:\Windows
    retcode:
        0
    stderr:
```

If it's called from a state, any existing environment variables are there but not the ones passed to cmd.powershell_all:

_test.sls:_
```yaml
{% set foo = salt['cmd.powershell_all']('Write-Output $Env:ZOO $Env:windir', env='{"ZOO": "BAR"}')  %}
{{ foo }}
```

```bash
salt minion slsutil.renderer salt://test.sls
minion:
    ----------
    pid:
        8232
    result:
        C:\\Windows
    retcode:
        0
    stderr:
```

Minion is Windows Server 2022 running 3005.1 Classic:

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.16 (tags/v3.8.16:1e3d2d5, Jan  6 2023, 17:39:57) [MSC v.1929 64 bit (AMD64)]
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 22.0.3
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2022Server
        system: Windows
       version: 2022Server 10.0.20348 SP0 Multiprocessor Free
```
</details>
