### ISSUE TITLE
[BUG] Duplicate addresses in fqdn_ip4/ip6 since 3002

### ISSUE THREAD

**Issue by mweinelt** [saltstack/salt#58799]
**Description**
The `fqdn_ip4` and `fqdn_ip6` grains contain duplicate addresses since 3002.

```
root@salt:~# salt 'gw01*' grains.get fqdn_ip6
gw01.darmstadt.freifunk.net:
    - 2001:67c:2ed8::40:1
    - 2001:67c:2ed8::40:1
    - 2001:67c:2ed8::40:1
root@salt:~# salt 'gw01*' grains.get fqdn_ip4
gw01.darmstadt.freifunk.net:
    - 82.195.73.40
    - 82.195.73.40
    - 82.195.73.40
```

**Setup**
Standard master/minion setup.

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
1. `salt 'gw01.*' grains.get fqdn_ip6`
2. `salt 'gw01.*' grains.get fqdn_ip4`

**Expected behavior**
Return a list of unique ip addresses.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

Master and minion running on 3002+ds-1.

```
root@salt:~# salt --versions-report
Salt Version:
           Salt: 3002
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10 buster
         locale: UTF-8
        machine: x86_64
        release: 5.8.0-0.bpo.2-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster
 
```
</details>

**Additional context**
```
    fqdn:
        gw01.darmstadt.freifunk.net
    fqdn_ip4:
        - 82.195.73.40
        - 82.195.73.40
        - 82.195.73.40
    fqdn_ip6:
        - 2001:67c:2ed8::40:1
        - 2001:67c:2ed8::40:1
        - 2001:67c:2ed8::40:1
    fqdns:
        - gw01.darmstadt.freifunk.net
        - gw01.dom0.ffda.io
        - gw01.dom1.ffda.io
        - gw01.dom10.ffda.io
        - gw01.dom11.ffda.io
        - gw01.dom12.ffda.io
        - gw01.dom13.ffda.io
        - gw01.dom14.ffda.io
        - gw01.dom15.ffda.io
        - gw01.dom16.ffda.io
        - gw01.dom17.ffda.io
        - gw01.dom2.ffda.io
        - gw01.dom3.ffda.io
        - gw01.dom4.ffda.io
        - gw01.dom5.ffda.io
        - gw01.dom6.ffda.io
        - gw01.dom7.ffda.io
        - gw01.dom8.ffda.io
        - gw01.dom9.ffda.io
        - pool1.users.ffda.io
```

cc @BarbarossaTM @awlx
