### ISSUE TITLE
[BUG] 3002 salt-minion does not restart when upgraded using salt-master 

### ISSUE THREAD

**Issue by wargamez** [saltstack/salt#58795]
```
**Description**
Upgrading salt-minion on Ubuntu using salt-master version 3002  trying to upgrade salt-minion running 3001 to 3002 fails to restart salt-minion.

**Setup**
`{% from "salt-minion/map.jinja" import saltstack with context %}

salt-minion_repo:
  pkgrepo.managed:
    - proxy: {{ pillar['http_proxy']['address'] }}
    - humanname: saltstack
    - name: deb {{ saltstack.repo_url }}
    - file: /etc/apt/sources.list.d/saltstack.list
    - key_url: salt://salt-minion/files/SALTSTACK-GPG-KEY.pub
    - architectures: amd64
    - refresh_db: true
    - refresh: true

salt-minion_packages:
  pkg.installed:
    - name: salt-minion
    - version: {{ pillar['saltstack']['minion-version'] }}
    - require:
       - pkgrepo: salt-minion_repo
`

**Steps to Reproduce the behavior**
salt -v -C ${HOST} pkg.upgrade dist_upgrade=True;
or state.apply on that host

**Expected behavior**
I expect salt-minion to be upgraded and restarted. The upgrades happens, but salt-minion is never restarted. Applying a apt dist-upgrade directly on the host works as expected. 


**Versions Report**
3002

```
</details>

**Additional context**

**Comment by max-arnold** [comment]
Could be related to https://github.com/saltstack/salt/issues/55201

**Comment by leeclemens** [comment]
I'm using CentOS 7 and have observed that it may depend on the `refresh` attribute to `pkg.latest` for my states. I just happen to have two setups with slightly different settings and have seen it fail all of the time (so far) or be successful all of the time (so far), depending.

Restarting as expected:
```
update_salt_minion_pkgs:
  pkg.latest:
    - pkgs:
      - salt
      - salt-minion
```
Not restarting:
```
system_update_salt_minion:
  pkg.latest:
    - pkgs:
      - salt
      - salt-minion
    - refresh: True
```

Both cases have been upgrading from `salt-minion-3001.1-1.el7.noarch` to `salt-minion-3002-1.el7.noarch`

**Comment by leeclemens** [comment]
I was hoping to find something more definitive between these two environments, but unfortunately did not. One interesting bit is that in the environment that was failing, it was able to successfully upgrade from `salt-minion-3001.1.el7.noarch`.

**Comment by golmaal** [comment]
@sagetherage I'm seeing something similar - 
```
 salt-minion.service - The Salt Minion
   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; enabled; vendor preset: disabled)
   Active: deactivating (stop-sigterm) since Mon 2020-11-02 21:19:11 UTC; 4s ago
     Docs: man:salt-minion(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
 Main PID: 8518 (/usr/bin/python)
    Tasks: 3 (limit: 26213)
   Memory: 82.9M
   CGroup: /system.slice/salt-minion.service
           ├─8518 /usr/bin/python3.6 /usr/bin/salt-minion
           ├─8529 /usr/bin/python3.6 /usr/bin/salt-minion KeepAlive MultiMinionProcessManager MinionProcessManager
           └─8707 /usr/bin/python3.6 /usr/bin/salt-minion KeepAlive MultiMinionProcessManager MinionProcessManager Minion._thread_return 20201102211910926918
```
when I run service.restart from salt-master using `salt <minion-id> service.restart salt-minion` the minion service takes 90 seconds to restart (when running as a systemd service, because it kills it after 90 second timeout)... 

This is causing issues in orchestration states where salt-minion needs to be restarted...

**Comment by leeclemens** [comment]
@golmaal the timeout may explain why I was seeing different results in the two environments and corresponding to `refresh` being set. Running some in the failing environment today I've been seeing ~120 seconds for `pkg.latest` to run without `refresh`.

**Comment by boltronics** [comment]
As I mentioned in the SaltSlack Community #general channel yesterday, I encountered this too while upgrading from 3001.1 to 3001.2 (the 3001.2+ds-1 package specifically) on Debian 10 Buster and Ubuntu 16.04 Xenial.

```
salt-minion:
  pkg.installed:
    - require:
      - sls: apt.pinning
      - pkg: lsb-release
      - pkg: salt-deps
      - sls: repositories
    - require_in:
      - file: Secure /var/log/salt contents
  service.running:
    - require:
      - file: /etc/salt/minion
      - pkg: salt-minion
    - watch:
      - file: /etc/salt/minion
```

I tested the upgrade by running `sudo salt-call state.highstate` on a couple of hosts. Since everything looked good, I went to the master and ran `sudo salt '*' state.highstate`. Much to my shock, all minions stopped and never came back up. This is a big problem! I've been upgrading my hosts this way for years without issue, until now.

It took quite a long time to resolve too, as I had to manually SSH into every host in our staging environment to fix this. I also didn't immediately have a solution to solve this in production and, due to the critical nature of the upgrade, ended up SSHing into every single production host and running `sudo salt-call state.highstate` manually too.

Perhaps `sudo salt '*' cmd.run_bg "salt-call state.highstate"` would have worked for production... too bad I didn't think to try that at the time so am not sure.

The last thing in the minion logs as reported bys `sudo systemctl status salt-minion` was this:
```
Nov 04 18:12:05 ip-172-31-16-40 salt-minion[1764]: [INFO    ] Returning information for job: 20201104070926368523
Nov 04 18:12:05 ip-172-31-16-40 salt-minion[1764]: The Salt Minion is shutdown. Minion received a SIGTERM. Exited.
Nov 04 18:12:07 ip-172-31-16-40 salt-minion[16520]: The Salt Minion is shutdown.
Nov 04 18:12:07 ip-172-31-16-40 systemd[1]: salt-minion.service: Main process exited, code=exited, status=1/FAILURE
Nov 04 18:12:07 ip-172-31-16-40 systemd[1]: salt-minion.service: Failed with result 'exit-code'.
```

**Comment by rj-dsl** [comment]
I can confirm that this issue also happens on Ubuntu 16.04 -> 20.04

**Comment by garethgreenaway** [comment]
The major issue here is that when Salt is being used to upgrade Salt the running minion is stopped and the job that is performing the upgrade is still looking for that running minion, because of this we don't recommend using `pkg.installed` or `service.restart` alone to handle upgrades of the Salt minion.  In our frequently asked questions, we have several examples of the best ways to handle these situations, https://docs.saltstack.com/en/latest/faq.html#what-is-the-best-way-to-restart-a-salt-minion-daemon-using-salt-after-upgrade

**Comment by garethgreenaway** [comment]
Closing this out since the original issue was restarting the Salt minion is a way that isn't recommended.  If there are issues using that method please feel free to open additional issues.  Thanks!

**Comment by boltronics** [comment]
Those instructions don't seem to work unfortunately.

```
          ID: Disable starting services
    Function: file.managed
        Name: /usr/sbin/policy-rc.d
      Result: True
     Comment: File /usr/sbin/policy-rc.d updated
     Started: 15:03:56.955267
    Duration: 3.896 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0755
----------
          ID: Upgrade salt-minion
    Function: pkg.latest
        Name: salt-minion
      Result: True
     Comment: The following packages were successfully installed/upgraded: salt-minion
     Started: 15:03:56.961233
    Duration: 7878.648 ms
     Changes:   
              ----------
              salt-common:
                  ----------
                  new:
                      3002.2+ds-1
                  old:
                      3001.2+ds-1
              salt-minion:
                  ----------
                  new:
                      3002.2+ds-1
                  old:
                      3001.2+ds-1
----------
          ID: Enable starting services
    Function: file.absent
        Name: /usr/sbin/policy-rc.d
      Result: True
     Comment: Removed file /usr/sbin/policy-rc.d
     Started: 15:04:04.854482
    Duration: 1.829 ms
     Changes:   
              ----------
              removed:
                  /usr/sbin/policy-rc.d
----------
          ID: Start salt-minion service
    Function: service.running
        Name: salt-minion
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2087, in wrapper
                  )
                File "/usr/lib/python3/dist-packages/salt/states/service.py", line 444, in running
                  if not _available(name, ret):
                File "/usr/lib/python3/dist-packages/salt/states/service.py", line 354, in _available
                  avail = __salt__["service.available"](name)
                File "/usr/lib/python3/dist-packages/salt/modules/systemd_service.py", line 629, in available
                  _check_for_unit_changes(name)
                File "/usr/lib/python3/dist-packages/salt/modules/systemd_service.py", line 142, in _check_for_unit_changes
                  if _untracked_custom_unit_found(name) or _unit_file_changed(name):
                File "/usr/lib/python3/dist-packages/salt/modules/systemd_service.py", line 404, in _unit_file_changed
                  status = _systemctl_status(name)["stdout"].lower()
                File "/usr/lib/python3/dist-packages/salt/modules/systemd_service.py", line 366, in _systemctl_status
                  __context__[contextkey] = __salt__["cmd.run_all"](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1278, in __getitem__
                  def __getitem__(self, item):
                File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
                  raise KeyError(key)
              KeyError: 'cmd.run_all'
     Started: 15:04:04.879808
    Duration: 1025.698 ms
     Changes:   
```

Salt gets into a situation where it is unable to restart itself. Need to SSH in via other means.

Even calling the `service.restart` execution module separately, or alternatively running:
`salt --async 'myhost' cmd.run 'systemctl restart salt-minion'`
similarly has no effect. Probably this is a new issue, where `cmd.run_all` is now incompatible with the previous 3001.x release series and prevents upgrading. Oh well... I need to roll this upgrade out today so I'm back to SSHing into every host on my network again to restart the service. :joy:

**Comment by bensteinberg** [comment]
@garethgreenaway I have two questions about this. First, when `pkg.list_upgrades` reported a new `salt-minion` version, I used to be able to run `salt 'my-debian-minion' pkg.upgrade` and the `salt-minion` package would be upgraded and restarted correctly. What changed?

Second, although I've read the [https://docs.saltstack.com/en/latest/faq.html#what-is-the-best-way-to-restart-a-salt-minion-daemon-using-salt-after-upgrade FAQ], I don't see a complete example. I want a state or an orchestration that I run against an arbitrary minion or minions, something like `salt 'my-debian-minion*' state.apply upgrade-salt` or `salt-run state.orchestrate orch.upgrade-salt pillar='{minions: "my-debian-minion*"}'` -- is there such an example out there? (I started working on an orchestration using `pkg.latest`, then saw the comment by @boltronics just above this one.)

**Comment by boltronics** [comment]
Although I haven't tested (or even had a chance to look into it), I'm guessing the above issue I pointed out is related specifically to upgrading from 3001.x to 3002.x. I'm crossing my fingers that going from 3002.2 to 3002.3 won't result in the same issue.

The state I ran is largely based on the example on that FAQ page. I think the key is the `- order: last` line, which is presumably there because the Salt developers know there is a good chance that other state files won't work after the upgrade. Unfortunately, Salt's ability to restart the service is the one thing that's still needed but is also broken. There should probably be some testing that this is compatible with earlier releases, if packages are no longer going to correctly restart.

FWIW, I believe I had the work-around from the FAQ years ago in place in my environment, but I had long since removed it because it was no longer necessary. There was definitely a regression in the way Salt was packaged.

**Comment by bsoldhogg** [comment]
I'm also seeing this issue in a lab running CentOS 7 and Ubuntu 18.04. These minions are on 3001.6 as around half of my estate are on this version and I'm trying out a reliable upgrade path....

**Comment by emalzer** [comment]
I ran into this issue as well while upgrading from 3001.7 to 3002.6 ... the way from the FAQ does not work, that's what I used before.
I found my way around with this:
* update the APT repository from 3001 to 3002
* ```salt minion cmd.run_bg 'echo "exit 101" > /usr/sbin/policy-rc.d && chmod +x /usr/sbin/policy-rc.d && apt-get update && apt-get install -y --allow-change-held-packages salt-minion salt-common ; rm /usr/sbin/policy-rc.d; sleep 5 && service salt-minion restart; sleep 5 && service salt-minion restart'```

**Comment by boltronics** [comment]
@emalzer The `service.running` state module can't restart the service after an upgrade (despite what the FAQ says) so it makes sense it might work if bypassing that by calling systemd `service` command directly. Thanks for providing that confirmation and complete work-around.

**Comment by gee456** [comment]
I found salt updating itself also problematic even with 3003 for both Linux and windows minions. I opted not to have salt do the update, but have it create a script that had a yum update in it that updates and restarts salt. I then used a cmd.run to run this script in the background. Method works for both Linux and windows minions, though with windows you are downloading the exe or msi and executing. I will share my scripts on github and link later.

**Comment by anitakrueger** [comment]
This has been an issue for us with upgrading from 3002.5 to 3004. Our salt state that manages salt looks like this:
```
{%- set service = pillar.salt %}

{{ service.name }}-dependencies:
  pkg.installed:
    - pkgs: {{ service.dependencies.pkg }}
  pip.installed:
    - names: {{ service.dependencies.pip }}
    - reload_modules: True
    - require:
      - pkg: {{ service.name }}-dependencies

{{ service.name }}-pkg:
  pkg.installed:
    - pkgs:
    {%- for pkg in service.pkg_names %}
      - {{ pkg }}: {{ service.versions.package }}
    {%- endfor %}
    - require:
      - pip: {{ service.name }}-dependencies

{{ service.name }}-service:
  service.running:
    - name: {{ service.name }}
    - enable: True
    - require:
      - file: {{ service.config }}-conf
      - pkg: {{ service.name }}-pkg

{{ service.config }}-conf:
  file.managed:
    - name: {{ service.config }}
    - source: salt://salt/templates/minion
    - template: jinja
    - user: root
    - group: root
    - mode: 640
    - require:
      - pkg: {{ service.name }}-pkg

{{ service.name }}-restart:
  cmd.run:
    - name: 'salt-call service.restart {{ service.name }}'
    - bg: True
    - onchanges:
      - pkg: {{ service.name }}-pkg
      - file: {{ service.config }}-conf
```

I finally found a workaround and that is to use `cmd.run_bg` to initiate the salt state like this:
```
sudo salt 'minion-01' cmd.run_bg "salt-call state.apply salt"
```

This is the only way that the restart will happen. Even installing the 3004 package via yum doesn't start up the minion again. 3004 just exists.

This is on CentOS 7.
