### ISSUE TITLE
Salt 3000 - New module run format

### ISSUE THREAD

**Issue by luizrojo** [saltstack/salt#58826]
**Description**
I am trying to migrate from the old module.run configuration to the salt 3000 version, but I am having issues with the syntax and the documentation is very poor.

The salt state is using **mine.send** module with the **x509.get_pem_entries** funcion

**Setup**
The state I am running on salt 2019.2.0 works fine:

```yaml
CA - Mine publication:
  module.run:
    - name: mine.send
    - func: x509.get_pem_entries
    - kwargs: 
        glob_path: /etc/pki/ca.crt
```

State.apply output:

```yaml
----------
          ID: CA - Mine publication
    Function: module.run
        Name: mine.send
      Result: True
     Comment: Module function mine.send executed
     Started: 16:00:49.109141
    Duration: 502.693 ms
     Changes:
              ----------
              ret:
                  True
```

Running the same state on salt 3000 gives an error output:

```yaml
----------
          ID: CA - Mine publication
    Function: module.run
        Name: mine.send
      Result: False
     Comment: The following arguments are missing: m_name
     Started: 16:03:17.954593
    Duration: 0.72 ms
     Changes:

Summary for local
-------------
Succeeded: 26
Failed:     1
-------------
```

Moving to the new salt 3000 format, the error changes:

```yaml
CA - Mine publication:
  module.run:
  - mine.send:
    - mine_function: x509.get_pem_entries
    - glob_path: /etc/pki/ca.crt
```

```yaml
----------
          ID: CA - Mine publication
    Function: module.run
      Result: False
     Comment: Module function CA - Mine publication is not available
     Started: 15:47:05.136742
    Duration: 1.031 ms
     Changes:
```

**Expected behavior**
Moving to the new format of module.run implemented on SALT 3000 the salt function should be executed and the mine config created

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.10 (default, Dec 19 2019, 15:48:40) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-197.7-default
         system: Linux
        version: Not Installed
```
</details>

**Additional context**

**Comment by sagetherage** [comment]
Salt v3000 is no longer supported and has vulnerabilities, please upgrade to v3000.3 https://github.com/saltstack/salt/releases/tag/v3000.3

**Comment by luizrojo** [comment]
Is this behavior different on v3000.3?

Updating will change the behavior?

**Comment by OrangeDog** [comment]
This was broken in 3000 and has been fixed: #56496

**Comment by sagetherage** [comment]
https://github.com/saltstack/salt/pull/56635/files

**Comment by sagetherage** [comment]
The fix was merged into master and released in Sodium or Salt v3001, and no the above reference to v3000.3 is because the version you reported is considered vulnerable, please upgrade and the fix is in a major release v3001.

**Comment by garethgreenaway** [comment]
@luizrojo Following up on this, were you able to upgrade to the latest 3000 version and has it fixed the issue you were seeing?

**Comment by dgengtek** [comment]
The new format does not work. 

salt v3003

from documentation:

```
show off module.run with args:
  module.run:
    # Note the lack of `name: `, and trailing `:`
    - test.random_hash:
      - size: 42
      - hash_type: sha256
```
results in error:
```
          ID: show off module.run with args
           Function: module.run
             Result: False
            Comment: Module function show off module.run with args is not available
            Started: 16:40:07.536089
           Duration: 1064.636 ms
            Changes:
```
