### ISSUE TITLE
[BUG] OpenBSD - False-failure pkg_add ‘stems with flavors’

### ISSUE THREAD

**Issue by udf2457** [saltstack/salt#58855]
OpenBSD 6.8 with distro package salt-3001.1 minion and 3001.1 master.

OpenBSD has  _‘stems with flavors’_ to cope with dealing with different versions of a package in the repo.

So, for example, the 6.8 packages repo has `gnupg` versions 1 and 2.  So to ensure v2 was installed, you would run `pkg_add gnupg--%gnupg2`

However given the following Salt SLS :
```
openbsd_pkgs:
  pkg.installed:
    - pkgs:
      - gnupg--%gnupg2
```

The OpenBSD minion will give you a false failure:
```
          ID: openbsd_pkgs                                                                                                                                                
    Function: pkg.installed                                                                                                                                                  
      Result: False                                                                                                                                                          
     Comment: The following packages failed to install/update: gnupg--%gnupg2                                                                                                                                                                                 
     Started: 13:08:48.432030                                                                                                                                                
    Duration: 3390.317 ms                                                                                                                                                    
     Changes:  

```

This happens even if you re-run `state.apply`

Meanwhile, if you login to the OpenBSD machine, it is clear that the package installed successfully because:

(1) Nothing new gets installed if you run manually **AND** a return code of 0 is provided:
```
$pkg_add gnupg--%gnupg2                                                                                                                                                                             
quirks-3.439 signed on 2020-10-31T12:23:49Z                                                                                 
$ echo $?                                                                                                               
0    
```
(2) `pkg_info` confirms it is installed ("inst"):
```
$ pkg_info gnupg
Information for inst:gnupg-2.2.23p0
```
(3) The command exists:
```
$ gpg2 --version
gpg (GnuPG) 2.2.23
```

**Comment by krionbsd** [comment]
Could you try this syntax instead?
```
openbsd_pkgs:
  pkg.installed:
    - pkgs:
      - name: gnupg
      - version: 2
```

**Comment by krionbsd** [comment]
I tested it now with this state:
```
openbsd_pkgs:
  pkg.installed:
    - pkgs:
      - vim--gtk2%
```
and it worked, are you sure %gnupg2 is a branch? If I use the state you specified salt installs gnupg but fails on stdout, weird

**Comment by krionbsd** [comment]
@udf2457 any feedback on it?

**Comment by udf2457** [comment]
@krionbsd 

Its been a long time, but looking through my Salt files, it looks like I gave up .... I commented out the use of 'stems with flavors', as you can see:

```
openbsd_wg_pkgs:
  pkg.installed:
    - pkgs:
      - wireguard-tools
      - libqrencode
#      - gnupg--%gnupg2 # Commented due to bug
```

**Comment by sagetherage** [comment]
@krionbsd wasn't able to reproduce this, but will take this to the community to see if we can reproduce it and move it out of blocked as of right now we can't move forward with it if we are unable to reproduce it.

**Comment by TheSemicolons** [comment]
I created a simple state file to test this on `OpenBSD localhost.local.domain. 6.8 GENERIC#5 amd64` (Machine was build, patched, and otherwise unchanged, salt was installed via `pkg_add salt`.)

```
localhostr# cat /srv/salt/gnupg/init.sls
gnupg:
  pkg.installed:
    - pkgs:
      - gnupg--%gnupg2
```

And ran it with:

`localhost# salt '*' state.apply gnupg`

The results weren't happy at first:

```
localhost.local.domain:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20210324013520110639
ERROR: Minions returned with non-zero exit code
localhost# salt-run jobs.lookup_jid 20210324013520110639
localhost#
```

But it just took longer than the default timeout to run, after a couple minutes things worked fine:

```
localhost# salt-run jobs.lookup_jid 20210324013520110639
localhost.local.domain:
    [ERROR   ] Made the following changes:
    'p11-kit' changed from 'absent' to '0.23.22'
    'libgcrypt' changed from 'absent' to '1.8.6'
    'gnutls' changed from 'absent' to '3.6.15'
    'libsecret' changed from 'absent' to '0.20.3'
    'libksba' changed from 'absent' to '1.4.0'
    'glib2' changed from 'absent' to '2.64.5'
    'libusb1' changed from 'absent' to '1.0.23p2'
    'libunbound' changed from 'absent' to '1.11.0'
    'libassuan' changed from 'absent' to '2.5.3'
    'pinentry' changed from 'absent' to '1.1.0p0'
    'gnupg' changed from 'absent' to '2.2.23p0'
    'pcre' changed from 'absent' to '8.41p2'
    'libtasn1' changed from 'absent' to '4.16.0'
    'libgpg-error' changed from 'absent' to '1.39'
    'libnettle' changed from 'absent' to '3.6'
    'npth' changed from 'absent' to '1.6'

localhost# 
```

I'm not sure why it says `[ERROR ]` because all listed packages are installed.

/var/log/messages:

```
localhost# tail -n 16 /var/log/messages
Mar 24 01:35:44 localhost pkg_add: Added libgpg-error-1.39
Mar 24 01:35:45 localhost pkg_add: Added libassuan-2.5.3
Mar 24 01:35:50 localhost pkg_add: Added libgcrypt-1.8.6
Mar 24 01:35:54 localhost pkg_add: Added pcre-8.41p2
Mar 24 01:35:58 localhost pkg_add: Added glib2-2.64.5
Mar 24 01:36:00 localhost pkg_add: Added libsecret-0.20.3
Mar 24 01:36:00 localhost pkg_add: Added pinentry-1.1.0p0
Mar 24 01:36:02 localhost pkg_add: Added libksba-1.4.0
Mar 24 01:36:06 localhost pkg_add: Added libnettle-3.6
Mar 24 01:36:07 localhost pkg_add: Added libtasn1-4.16.0
Mar 24 01:36:10 localhost pkg_add: Added libunbound-1.11.0
Mar 24 01:36:13 localhost pkg_add: Added p11-kit-0.23.22
Mar 24 01:36:22 localhost pkg_add: Added gnutls-3.6.15
Mar 24 01:36:22 localhost pkg_add: Added npth-1.6
Mar 24 01:36:23 localhost pkg_add: Added libusb1-1.0.23p2
Mar 24 01:36:28 localhost pkg_add: Added gnupg-2.2.23p0
```

/etc/salt/master:

```
localhost# grep -Ev '^\s*$|^\s*\#' master
interface: 192.168.0.4
```

/etc/salt/minion:

```
localhost# grep -Ev '^\s*$|^\s*\#' minion
master: 192.168.0.4
master_finger: '<removed>'
```
