### ISSUE TITLE
[BUG] The unless condition for cmd.script is broken when using the runas argument.

### ISSUE THREAD

**Issue by BrianSidebotham** [saltstack/salt#58866]
## Description
The unless condition for `cmd.script` is broken when using the `runas` argument.

## Setup
On a Windows Server machine, there is a separate user setup that is different to the salt user. In this case I've been testing by using the Administrator account. Here are a couple of scripts essentials named success and error

`success.ps1`

```
Exit 0
```

`error.ps1`

```
Exit 1
```

**Steps to Reproduce the behavior**

Given the following `.sls` state file which should have alternating states where 

```
check_powershell_exit_error_in_unless_requisite:
  cmd.script:
    - source: salt://files/powershell_exit_successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://files/powershell_exit_successful.ps1'
         shell: powershell

check_powershell_exit_success_in_unless_requisite:
  cmd.script:
    - source: salt://files/powershell_exit_successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://files/powershell_exit_error.ps1'
         shell: powershell

check_powershell_exit_error_in_unless_requisite_runas:
  cmd.script:
    - source: salt://files/powershell_exit_successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://files/powershell_exit_successful.ps1'
         shell: powershell
         runas: {{ runas_username | yaml_dquote }}
         password: {{ runas_password | yaml_dquote }}

check_powershell_exit_success_in_unless_requisite_runas:
  cmd.script:
    - source: salt://files/powershell_exit_successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://files/powershell_exit_error.ps1'
         shell: powershell
         runas: {{ runas_username | yaml_dquote }}
         password: {{ runas_password | yaml_dquote }}
```

This results in incorrect behaviour in the states.  In particular the `check_powershell_exit_success_in_unless_requisite_runas` says that it would have been executed, but the state should only be executed if a state fails.

```
----------
          ID: check_powershell_exit_error_in_unless_requisite
    Function: cmd.script
      Result: True
     Comment: unless condition is true
     Started: 11:12:13.722582
    Duration: 7156.238 ms
     Changes:   
----------
          ID: check_powershell_exit_success_in_unless_requisite
    Function: cmd.script
      Result: None
     Comment: Command 'check_powershell_exit_success_in_unless_requisite' would have been executed
     Started: 11:12:20.878820
    Duration: 281.233 ms
     Changes:   
----------
          ID: check_powershell_exit_error_in_unless_requisite_runas
    Function: cmd.script
      Result: None
     Comment: Command 'check_powershell_exit_error_in_unless_requisite_runas' would have been executed
     Started: 11:12:21.160053
    Duration: 374.996 ms
     Changes:   
----------
          ID: check_powershell_exit_success_in_unless_requisite_runas
    Function: cmd.script
      Result: None
     Comment: Command 'check_powershell_exit_success_in_unless_requisite_runas' would have been executed
     Started: 11:12:21.535049
    Duration: 328.123 ms
     Changes:   
----------
```

If I swap the first two states around such that the state that runs before the runas states is successful then all of the runas states also say that the `unless condition is true`.

```
check_powershell_exit_success_in_unless_requisite:
  cmd.script:
    - source: salt://files/powershell_exit_successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://files/powershell_exit_error.ps1'
         shell: powershell

check_powershell_exit_error_in_unless_requisite:
  cmd.script:
    - source: salt://files/powershell_exit_successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://files/powershell_exit_successful.ps1'
         shell: powershell

check_powershell_exit_error_in_unless_requisite_runas:
  cmd.script:
    - source: salt://files/powershell_exit_successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://files/powershell_exit_successful.ps1'
         shell: powershell
         runas: {{ runas_username | yaml_dquote }}
         password: {{ runas_password | yaml_dquote }}

check_powershell_exit_success_in_unless_requisite_runas:
  cmd.script:
    - source: salt://files/powershell_exit_successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://files/powershell_exit_error.ps1'
         shell: powershell
         runas: {{ runas_username | yaml_dquote }}
         password: {{ runas_password | yaml_dquote }}
```

Gives the following incorrect behaviour:

```
----------
          ID: check_powershell_exit_success_in_unless_requisite
    Function: cmd.script
      Result: None
     Comment: Command 'check_powershell_exit_success_in_unless_requisite' would have been executed
     Started: 11:39:57.972014
    Duration: 6859.381 ms
     Changes:   
----------
          ID: check_powershell_exit_error_in_unless_requisite
    Function: cmd.script
      Result: True
     Comment: unless condition is true
     Started: 11:40:04.831395
    Duration: 265.619 ms
     Changes:   
----------
          ID: check_powershell_exit_error_in_unless_requisite_runas
    Function: cmd.script
      Result: True
     Comment: unless condition is true
     Started: 11:40:05.097014
    Duration: 359.376 ms
     Changes:   
----------
          ID: check_powershell_exit_success_in_unless_requisite_runas
    Function: cmd.script
      Result: True
     Comment: unless condition is true
     Started: 11:40:05.456390
    Duration: 296.946 ms
     Changes:   
----------
```

## Expected behaviour

For each state that uses `cmd.script` with the `runas` kwarg to be independently evaluated and not linked to a previous states result.

## Versions Report

```
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: 1.14.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.19.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```

</details>

## Additional context

I've only tested this on Windows (Server 2016) and Powershell.

**Comment by max-arnold** [comment]
I'm not 100% sure, but you issue might be fixed in https://github.com/saltstack/salt/pull/57825 (available in Salt >= 3002)

**Comment by BrianSidebotham** [comment]
@max-arnold I don't think that will fix this issue. Sorry, I know the report here is a little verbose/complex. `shell: powershell` is definitely working in the `unless` requisite for this bug report on the `3001.1` version we've currently got installed. Unfortunately I've grown nervous of moving Salt forward a version because generally it results in things breaking and us having to put a lot of work into fixing it all back up.

#57825 is a bit of a mess because of the py2 cleanup from the pre-commit. It makes it hard to see the wood for the trees in the *actual* change. For me, cleanups should not happen as part of bug-fix merges but should instead be a separate PR. But anyway, that's another matter.

**Comment by BrianSidebotham** [comment]
Actually, reading #57825 more carefully it definitely won't fix this issue. That is more of a feature enhancement rather than a bugfix. When using `cmd.run` it will propagate the `cmd.run` options through to the `unless cmd.retcode`.

That makes sense and I wondered why that was not always the case. However, in this example we are using the new functionality of running a module function using the `- fun:` option of the `unless` requisite and configure `cmd.script` with all of the options ourselves. This is generally very repetitive because it's nearly always the same options that get set, but this is not working correctly.

**Comment by xeacott** [comment]
Having been in this file a bit today... going to jump into this now.

**Comment by xeacott** [comment]
Hey @BrianSidebotham can we double check this is still persisting? I copied/pasted the state above as described and have

```
A:
  cmd.script:
    - source: salt://successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://successful.ps1
         shell: powershell
B:
  cmd.script:
    - source: salt://successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://error.ps1
         shell: powershell

C_runas:
  cmd.script:
    - source: salt://successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://successful.ps1
         shell: powershell
         runas: test_user
         password: password

D_runas:
  cmd.script:
    - source: salt://successful.ps1
    - shell: powershell
    - unless:
       - fun: cmd.script
         args:
           - 'salt://exit.ps1
         shell: powershell
         runas: test_user
         password: password
```

and the output is...
```
local:
----------
          ID: check_powershell_exit_error_in_unless_requisite
    Function: cmd.script
      Result: True
     Comment: unless condition is true
     Started: 17:59:07.741551
    Duration: 8589.958 ms
     Changes:   
----------
          ID: check_powershell_exit_success_in_unless_requisite
    Function: cmd.script
      Result: True
     Comment: Command 'check_powershell_exit_success_in_unless_requisite' run
     Started: 17:59:16.331509
    Duration: 635.376 ms
     Changes:   
              ----------
              pid:
                  16864
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: check_powershell_exit_error_in_unless_requisite_runas
    Function: cmd.script
      Result: True
     Comment: unless condition is true
     Started: 17:59:16.966885
    Duration: 4.605 ms
     Changes:   
----------
          ID: check_powershell_exit_success_in_unless_requisite_runas
    Function: cmd.script
      Result: True
     Comment: unless condition is true
     Started: 17:59:16.971490
    Duration: 20.101 ms
     Changes:   

Summary for local
------------
Succeeded: 4 (changed=1)
Failed:    0
------------
Total states run:     4
Total run time:   9.250 s
[DEBUG   ] output: 
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] Using pkg_resources to load entry points
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] Using pkg_resources to load entry points
[DEBUG   ] LazyLoaded nested.output

Process finished with exit code 0

```
