### ISSUE TITLE
[BUG] pkgrepo.managed always reported as "changed" on apt system

### ISSUE THREAD

**Issue by kbaikov** [saltstack/salt#58885]
**Description**
pkgrepo.managed always reported as "changed" on apt system

Possibly related to issues: https://github.com/saltstack/salt/issues/57778 and https://github.com/saltstack/salt/issues/58648

Using salt 3002.1 and salt-ssh 3002.1 installed in virtual environment
and apt system is debian buster (on raspberrypi)

**Setup**
e.g. podman.sls

```yaml
podman_repo:
  pkgrepo.managed:
    - name: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10/ /
    - file: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
    - key_url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10/Release.key

podman_install_package:
  pkg.installed:
    - name: podman
    - refresh: True
```

**Steps to Reproduce the behavior**
```bash
salt-ssh pi state.apply podman
```

**Expected behavior**
No changes if the source file already exists or running the state.apply more than once

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3002.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.9.9
         pygit2: Not Installed
         Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 4.19.128-microsoft-standard
         system: Linux
        version: Ubuntu 20.04 focal
```
</details>

**Additional context**
relevant ssh log debug:

```text
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('podman_repo', OrderedDict([('pkgrepo.managed', [OrderedDict([('name', 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10/ /')]), OrderedDict([('file', '/etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list')]), OrderedDict([('key_url', 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10/Release.key')]), OrderedDict([('require_in', [OrderedDict([('pkg', 'podman')])])])])])), ('podman_install_package', OrderedDict([('pkg.installed', [OrderedDict([('name', 'podman')]), OrderedDict([('refresh', True)])])]))])
```
