### ISSUE TITLE
[FEATURE REQUEST] Allow set headers in archive.extracted state

### ISSUE THREAD

**Issue by ViktorPegy** [saltstack/salt#58888]
**Is your feature request related to a problem? Please describe.**
I want to download GitLab artifacts. GitLab allows the token present in the header or query parameter. I can't use the query parameter because it will be copied to the cached filename on the minion.

**Describe the solution you'd like**
Add 'headers' (dictionary) parameter to state.

**Describe alternatives you've considered**
No alternatives I think.

**Comment by waynew** [comment]
Hi @ViktorPegy thanks for the request! A bit of follow up - Why is the query parameter in the filename undesirable? Due to leaking secrets? Or because the token might change? If you could flesh this out a bit more and describe in more detail (obviously with tokens redacted and sample path names) what you're currently doing, what you *want* to have working, and what Salt is doing instead, that would be fantastic! Thanks again!

**Comment by ViktorPegy** [comment]
Hi @waynew! Thanks for the reply. Query parameter will be copied into the minion cache filename as is, this is dangerous due to leaking secret token. And if we change the secret token, Salt will redownload the file, even it's not changed.

Sample state configuration:
```yaml
archive.extracted:
  - name: /tmp/archive_dir
  - source: https://example.com/path/to/archive.gz?secret_token=secret_token
```
Then, the cache filename will be `<cache_dir>/example.com/path/to/archive.gz?secret_token=secret_token` (URL-encoded)

What I would like:
```yaml
archive.extracted:
  - name: /tmp/archive_dir
  - source: https://example.com/path/to/archive.gz
  - headers:
      X-Secret-Token: secret_token
```
