### ISSUE TITLE
[BUG] 3002.1 file.manage UnicodeDecodeError

### ISSUE THREAD

**Issue by daro1337** [saltstack/salt#58881]
**Description**
In salt 3002.1 when downloading zip file there is **UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 169: invalid start byte** I would like to point that state that downloads zookeper (tar.gz) works fine
i downgraded salt-minion version to 3001.3 and all works fine

```
----------
          ID: download_zookeeper
    Function: file.managed
        Name: /opt/apache-zookeeper-3.5.6-bin.tar.gz
      Result: True
     Comment: File /opt/apache-zookeeper-3.5.6-bin.tar.gz updated
     Started: 13:57:32.133160
    Duration: 721.194 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644

          ID: download_storm
    Function: file.managed
        Name: /opt/apache-storm-2.1.0.zip
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2188, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 3185, in managed
                  source, source_hash = __salt__["file.source_list"](source, source_hash, __env__)
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 4376, in source_list
                  query_res = salt.utils.http.query(single, method="HEAD")
                File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 656, in query
                  result_text = result_text.decode("utf-8")
              UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 169: invalid start byte
     Started: 13:57:32.856475
    Duration: 6269.537 ms
     Changes:   
```

**Setup**
SLS:
```
download_zookeeper:
  file.managed:
    - name: /opt/apache-zookeeper-{{ salt['pillar.get']('packages:zookeeper_version', '3.4.9') }}-bin.tar.gz
    - source:
      - http://archive.apache.org/dist/zookeeper/zookeeper-{{ salt['pillar.get']('packages:zookeeper_version', '3.4.9') }}/apache-zookeeper-{{ salt['pillar.get']('packages:zookeeper_version', '3.4.9') }}-bin.tar.gz
    - source_hash: cc6a1d11129e8330141b756625bfdba0
    - onfail:
      - id: chcek_download_zookeeper

chcek_download_storm:
  file.exists:
    - name: /opt/apache-storm-{{ salt['pillar.get']('packages:storm_version', '2.1.0') }}.zip

download_storm:
  file.managed:
    - name: /opt/apache-storm-{{ salt['pillar.get']('packages:storm_version', '2.1.0') }}.zip
    - source:
      - https://www-eu.apache.org/dist/storm/apache-storm-{{ salt['pillar.get']('packages:storm_version', '2.1.0') }}/apache-storm-{{ salt['pillar.get']('packages:storm_version', '2.1.0') }}.zip
    - source_hash: ae3047bb130aa92dda900b2d851d1cdd
    - onfail:
      - id: chcek_download_storm
```
Pillar:
```
packages:
  zookeeper_version: 3.5.6
  storm_version: 2.1.0
```
**Steps to Reproduce the behavior**
salt-call state.apply

**Expected behavior**
Both files are downloaded and created. Output from version 3001.3:
```
----------
          ID: download_zookeeper
    Function: file.managed
        Name: /opt/apache-zookeeper-3.5.6-bin.tar.gz
      Result: True
     Comment: File /opt/apache-zookeeper-3.5.6-bin.tar.gz updated
     Started: 14:05:30.054014
    Duration: 327.184 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: chcek_download_storm
    Function: file.exists
        Name: /opt/apache-storm-2.1.0.zip
      Result: False
     Comment: Specified path /opt/apache-storm-2.1.0.zip does not exist
     Started: 14:05:30.381339
    Duration: 1.242 ms
     Changes:   
----------
          ID: download_storm
    Function: file.managed
        Name: /opt/apache-storm-2.1.0.zip
      Result: True
     Comment: File /opt/apache-storm-2.1.0.zip updated
     Started: 14:05:30.382959
    Duration: 1509.718 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644
```

**Versions Report**
```
salt-call --versions
Salt Version:
           Salt: 3002.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.6.9 (default, Oct  8 2020, 12:12:24)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-122-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver
```
</details>

**Additional context**
