### ISSUE TITLE
[BUG] Salt inotify beacon fails to trigger and leaves no logs for why

### ISSUE THREAD

**Issue by Daemonslayer2048** [saltstack/salt#58892]
**Description**
Salt inotify beacon fails to trigger and leaves no logs for why

**Setup**
A freshly installed salt-minion on a centos 8 machine and a salt-master for reading the event bus. 

**Steps to Reproduce the behavior**
Create your beacons file like so:
``` yaml
beacons:
  Firewall_Service:
    - services:
        firewalld:
          onchangeonly: true
    - beacon_module: service
    - disable_during_state_run: True
  Beacon_Config:
    - files:
        /etc/salt/minion.d/beacons.conf: {}
    - beacon_module: inotify
    - disable_during_state_run: True
```
This generates no event on the event bus on the master, and no data on the minion log.
This can be somewhat worked around by doing the following:
``` yaml
beacons:
  Firewall_Service:
    - services:
        firewalld:
          onchangeonly: true
    - beacon_module: service
    - disable_during_state_run: True
  inotify:
    - files:
        /etc/salt/minion.d/beacons.conf:
          mask:
            - modify
```
but this only allows for on file to be tracked for changes

**Expected behavior**
The following beacon when placed in a beacon config file should generate an event on the master when changed.
``` yaml
  Beacon_Config:
    - files:
        /etc/salt/minion.d/beacons.conf: {}
    - beacon_module: inotify
    - disable_during_state_run: True
```

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 
Minion:  

```
Salt Version:
          Salt: 3002-n/a-8afbb8e
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.9
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 19.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: centos 8 Core
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-193.el8.x86_64
        system: Linux
       version: CentOS Linux 8 Core

```
Master:
```
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.99.0
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 1.1.1
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.3
 
System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-147.8.1.el8_1.x86_64
         system: Linux
        version: CentOS Linux 8 Core
```

</details>

**Additional context**
N/A

**Comment by Daemonslayer2048** [comment]
Ahh to define inotify beacons as I wanted to the following will work:
``` yaml
beacons:
  Beacon_File:
    - files:
        /etc/salt/minion.d/beacons.conf:
          mask:
            - modify
    - disable_during_state_run: true
    - beacon_module: inotify
```
