### ISSUE TITLE
[BUG] mount.mounted - Missing Space

### ISSUE THREAD

**Issue by udf2457** [saltstack/salt#58906]
Ubuntu 20 minion with Salt version 3002.1

Given the following SLS definition:
```
drbd_mount_primary:
  mount.mounted:
    - name: {{salt['pillar.get']('drbd-mount-point')}}
    - device: UUID={{salt['pillar.get']('drbd-filesystem-uuid')}}
    - fstype: xfs
    - opts: auto,defaults,noexec,nodev,nosuid
    - dump: 0
    - pass_num: 2
    - mkmnt: True
    - persist: True
    - mount: True
    - unless: drbdadm role r0 | fgrep -qi 'secondary'
    - require:
      - drbd_mkfs_xfs
      - drbd_mount_dir
```

The output in fstab is :

`UUID=b8d308ae-e673-4f9e-913c-986b8a84e5f              /srv/foobar       xfs     auto,defaults,nodev,noexec,nosuid0 2`

Note the lack of space between `nosuid` and `0`
