### ISSUE TITLE
Jinja variable is undefined

### ISSUE THREAD

**Issue by EpsilonAlpha** [saltstack/salt#58914]
### Description of Issue
I'm currently stuck in establishing global aliases on a server. I've defined a list of aliases but the jinja variable 'aliasse' should be not defined, but it is. Servername is altered for obvious reasons to _server.company.de_

### Setup
Pillar globalealiasses.sls:
```
globalealiasse:
  cls:
    - aliasse: cls
    - command: clear
```
State aliases\init.sls:
```
{% for aliasses, args in pillar.get('globalealiasse', {}).items() %}

{{ aliasses }}_global_alias:
  file.line:
    - name: {{ aliasse }}
    - content: {{ command }}
    - match: alias {{ aliasse }}=.*
    - mode: replace
    - create: True
    - user: {{pillar['skript']['user']}}
    - group: {{pillar['skript']['group']}}
    - file_mode: {{pillar['file']['mode']}}

{% endfor %}
```

### Steps to Reproduce Issue

Both are Files are ofc listed in their according top.sls files, but if i enter
`root@server ~ # salt 'server*' state.apply aliases test=True`
i get
```
server.company.de:
    Data failed to compile:
----------
    Rendering SLS 'base:aliases' failed: Jinja variable 'aliasse' is undefined

```
---

Also 
```
root@server ~ # salt 'server*' saltutil.refresh_pillar
```
returns:
```
server.company.de:
    True
```
so no issue there. Can someone explain me this or point on something i don't see? I've already broke down the list of aliases to 1 to test if some of the other aliases causing this.

---

Also 
```
root@server ~ # salt 'server*' pillar.get globalealiasse
```
returns:
```
server.company.de:
    ----------
    cls:
        |_
          ----------
          aliasse:
              cls
        |_
          ----------
          command:
              clear
```

---

### Versions Report
```
root@server ~ # salt --versions-report
Salt Version:
           Salt: 3002.1

Dependency Versions:
           cffi: 1.14.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.6.9 (default, Oct  8 2020, 12:12:24)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-37-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by jwolfe-ns** [comment]
`name` and `match` are trying to reference `aliasse`, so that's why there is a Jinja error. I'm a bit confused here though, as you have `aliases`, `aliasse`, and `aliasses`

**Comment by EpsilonAlpha** [comment]
I‘ve had it before on 'alias' and tried different declarations. 

But I wonder: If it’s a Name conflict, why the error is not something like „must be unique“. 

But I will change it to something different to try it out. 🙂

**Comment by EpsilonAlpha** [comment]
Okay, changed the value names:

- 'aliasses' -> 'listentry'
- 'aliasse' -> 'shortcmd'
- 'command' -> 'longcmd'
- 'name' -> pillar of the aliases-script i use in other states

---

The new State aliases/init.sls:
```
{% for listentry, args in pillar.get('globalealiasse', {}).items() %}

{{ listentry }}_global_alias:
  file.line:
    - name: {{ pillar['aliases']['skript'] }}
    - content: {{ longcmd }}
    - match: alias {{ shortcmd }}=.*
    - mode: replace
    - create: True
    - user: {{pillar['skript']['user']}}
    - group: {{pillar['skript']['group']}}
    - file_mode: {{pillar['file']['mode']}}

{% endfor %}
```

New Pillar globalealiasses.sls:
```
globalealiasse:
  cls:
    - shortcmd: cls
    - longcmd: clear
```
--- 

Steps:

1. Pillars refreshed returned `True`
2. `salt 'server*' pillar.get globalealiasse` returned:

```
server.company.de:
    ----------
    cls:
        |_
          ----------
          shortcmd:
              cls
        |_
          ----------
          longcmd:
              clear
```

3. `salt 'server*' state.apply aliases test=True` returned:

```
server.company.de:
    Data failed to compile:
----------
    Rendering SLS 'base:aliases' failed: Jinja variable 'longcmd' is undefined
```

**Comment by EpsilonAlpha** [comment]
I don't get how the (now new renamed) Value `longcmd` can't be "defined" if pillar.get returns me the content `clear`

**Comment by lukasraska** [comment]
The `longcmd` and `shortcmd` are not variables, merely values in `args` variable you extract from pillar. What you most probably want to do is

pillar:
```
globalealiasse:
  cls:
      shortcmd: cls
      longcmd: clear
```

state:
```
{% for listentry, args in pillar.get('globalealiasse', {}).items() %}

{{ listentry }}_global_alias:
  file.line:
    - name: {{ pillar['aliases']['skript'] }}
    - content: {{ args.longcmd }}
    - match: alias {{ args.shortcmd }}=.*
    - mode: replace
    - create: True
    - user: {{pillar['skript']['user']}}
    - group: {{pillar['skript']['group']}}
    - file_mode: {{pillar['file']['mode']}}

{% endfor %}
```

This way it looks up key named `longcmd` and `shortcmd` in `args` variable, which is the value of key `cls` inside `globalealiasse`
