### ISSUE TITLE
Hide errors for file.directory permissions

### ISSUE THREAD

**Issue by trc-af** [saltstack/salt#58921]
### Description of Issue
I have a state that looks like the one in setup below. This is a heavily used server, so the files in the prefix dir, datadir, and log_root dir are frequently changing. If they change in the middle of a salt-call, salt will return an error that it can't change permissions of a file because it doesn't exist. I'd like to know if it's possible to accept all errors for this function, and have it always return an 'all clear'.

### Setup
```
jira-update-dir-permissions:
  file.directory:
    - user: {{ jira.user }}
    - group: {{ jira.group }}
    - recurse:
      - user
      - group
    - names:
      - {{ jira.prefix }}
      - {{ jira.datadir }}
      - {{ jira.log_root }}
    - check_cmd: True
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2019.2.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.19.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core
```
