### ISSUE TITLE
pkgrepo.managed on CentOS doesn't support metalink directive

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#58931]
Currently in Salt 3000.3, setting up a repository with pkgrepo.managed on CentOS requires either a `baseurl` or `mirrorlist` directive.  However, some repositories, including EPEL 7 and 8, are now using `metalink` exclusively. 

Suggested functionality:

```
epel-repo:
    pkgrepo.managed:
      - name: epel
      - humanname: Extra Packages for Enterprise Linux 7 - $basearch
      - metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch&infra=$infra&content=$contentdir
      - enabled: 1
      - gpgcheck: 1
      - failovermethod: priority
      - gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
```

Attempting to apply this state gives:

```
          ID: epel-repo
    Function: pkgrepo.managed
        Name: epel
      Result: False
     Comment: Failed to configure repo 'epel': The repo does not exist and needs to be created, but either a baseurl or a mirrorlist needs to be given
     Started: 12:38:54.523276
    Duration: 5678.068 ms
     Changes:   
```

**Comment by ScriptAutomate** [comment]
`metalink` is currently not a supported param for [pkgrepo.managed](https://docs.saltproject.io/en/master/ref/states/all/salt.states.pkgrepo.html#salt.states.pkgrepo.managed).

Can you provide more information on the use of `metalink`, and what makes those repositories differ? Or link to documentation we can refer to?

**Comment by racooper** [comment]
Documentation from Fedora Project: https://fedoraproject.org/wiki/Features/YumMetalinks

The current EPEL repo for CentOS 7 is:
```
[epel]
name=Extra Packages for Enterprise Linux 7 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch&infra=$infra&content=$contentdir
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
```

**Comment by racooper** [comment]
I just tested and in 3004.3, it's still the same.  This affects any yum/dnf based distros, not just CentOS.
```
          ID: epel-repo
    Function: pkgrepo.managed
        Name: epel
      Result: False
     Comment: Failed to configure repo 'epel': The repo does not exist and needs to be created, but either a baseurl or a mirrorlist needs to be given
     Started: 15:45:58.470450
    Duration: 924.664 ms
     Changes:   

```
The state is configured thus:
```
epel-repo:
  pkgrepo.managed:
    - name: epel
    - humanname: Extra Packages for Enterprise Linux $releasever - $basearch
    - metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
    - enabled: 1
    - gpgcheck: 1
    - countme: 1
    - gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
```

**Comment by davama** [comment]
I dont see this issue on `v3006.2`

With rocky linux 8 though...

```
epel_repo:
  pkgrepo.managed:
    - name: epel
    - humanname: Extra Packages for Enterprise Linux 8 - $basearch
    # this is a dummy url, required by salt but not used by dnf - metalink will be prefered
    - baseurl: https://download.example/pub/epel/8/Everything/$basearch
    - metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch&infra=$infra&content=$contentdir
    - enabled: True
    - gpgcheck: 1
    - countme: 1
    - gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
```

`/etc/yum.repos.d/epel.repo`

```
[epel]
baseurl=https://download.example/pub/epel/8/Everything/$basearch
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch&infra=$infra&content=$contentdir
gpgcheck=1
countme=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
name=Extra Packages for Enterprise Linux 8 - $basearch
enabled=1
```
