### ISSUE TITLE
[BUG] BOTO3 NameError: name '__opts__' is not defined

### ISSUE THREAD

**Issue by kitsushadow** [saltstack/salt#58934]
**Description**
when creating states that use the boto3mod.py the user will get the error:
`NameError: name '__opts__' is not defined`

**Setup**
my sls file

```
elbv2Present:
  boto_elbv2.create_target_group:
    - name: mminaie
    - protocol: https
    - port: 443
    - vpc_id: vpc-6668f802
    - region: us-gov-west-1
```

**Steps to Reproduce the behavior**
Using an IAM profile attempt to make the state

**Expected behavior**
__opts__ needs work like the boto module

**Screenshots**

**Versions Report**
Salt Version:
           Salt: 3002.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
   python-gnupg: Not Installed
         PyYAML: 5.2
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: rhel 7.9 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1160.2.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.9 Maipo
