### ISSUE TITLE
[Question]: Use Jinja variable in the bash script

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#58935]
I am trying to deploy the bash script to minion, I have added variablels in maps.jinja file and I want to call the variable in a bash script which needs to put in the minion. 

#maps. jinja
{% if env == 'prod' %}
        {% set Home_path= "/suser/app/HC_CIFP/ci/nodel" %}
        {% set port = "8409" %}
{% endif %}

In bash I need to call this Home_path and Port. I do not know how to handle this situation, hope someone can shed light on it.

I have seen some where in usage of {% raw %}.But its not working properly

Salt version
3000.3

**Comment by 53845714nF** [comment]
Hello,
You can output the content of the variable.
For this you need {{ Home_path }} and {{ port }}.

**Comment by sooraj2589** [comment]
@53845714nF How I need to import the jinja file in bash file ?

**Comment by 53845714nF** [comment]
Hello, 
I have written a small test state.

maps. jinja
```
{%- set Home_path= "/suser/app/HC_CIFP/ci/nodel" %}
{%- set port = 8068 %}
```

test/init.sls
```
test:
  file.managed:
    - name: /tmp/script
    - source:
      - salt://linux/test/script.sh
    - template: jinja
    - user: root
    - group: root
    - mode: 644
```

test/script.sh
```
{% from "map.jinja" import Home_path, port with context -%}
#!/bin/bash
port="{{ port }}"
Home_path="{{ Home_path }}"

echo $port
echo $Home_path
```

I think this could solve your problem. 
If not even look at the documentary at:
https://docs.saltstack.com/en/3000/topics/jinja/index.html#include-and-import

best regards
