### ISSUE TITLE
[BUG] Salt does not realize a file to be copied on a minion has been changed

### ISSUE THREAD

**Issue by iosonoumberto** [saltstack/salt#58961]
I have this state file
```
/root/ninja.txt:
  file.managed:
    - source: http://10.102.240.125/contrail/ninja.txt
    - user: root
    - group: root
    - mode: 644
    **- skip_verify: True**
    **- keep_source: False**
    - show_changes: True
    - template: jinja
    - defaults:
        subnet: {{ pillar['subnet'] }}
```
that I use to copy ninja.txt to a minion

My file looks like this

[root@salt states]# cat /var/www/html/contrail/ninja.txt
```
cane
{{ subnet }}
```
so i expect fo find on my minion something like
```
cane
255.255.255.0
```
and this is what I get!

at the same time, due to keep_source=False, I expect salt not to keep a cached copy of the file. Is this expectation correct?

Next, i modify my ninja file as follows

[root@salt states]# cat /var/www/html/contrail/ninja.txt
```
cane
SSSfff
{{ subnet }}
```

and i re-apply the state
expecting to fin this on minion

```
cane
SSSfff
255.255.255.0
```

instead, nothing changed...still the old file

here is my version

[root@salt states]# salt --versions-report
Salt Version:
           Salt: 3002.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Oct 13 2020, 16:18:22)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
