### ISSUE TITLE
[Question] Git FS is not fetching files from run time tag.

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#58992]
Git FS is not fetching files form tag. Have mentioned base and ref_type in the conf file, still file is not listing in the server

Is there any other way to handle this?  can I give tag name in Run time?

##master conf
```
fileserver_backend:
 - roots
 - gitfs

gitfs_provider: GitPython

gitfs_remotes:
  - git@github.###.com:sooraj/app.git:
    - name: config_repo
    - root: config/dev
    - mountpoint: salt://config/dev
    - ref_types:
      - tag
    - base: devops-salt-poc
```
Salt --version
3000.3

**Comment by sooraj2589** [comment]
@sagetherage can you please update on this?

**Comment by sagetherage** [comment]
We are terribly behind on triaging issues, i have reassigned and will look to get this triaged.

**Comment by garethgreenaway** [comment]
@sooraj2589 apologies for the delay in responding to this one.  Unfortunately I wasn't able to reproduce the issue.  Just to clarify a few things in your gitfs remote configuration:
```
gitfs_remotes:
  - git@github.###.com:sooraj/app.git:
    - name: config_repo
    - root: config/dev
    - mountpoint: salt://config/dev
    - ref_types:
      - tag
    - base: devops-salt-poc
```
The remote tag that you're expected states are is `devops-salt-poc`, when you attempt to use the state in a call such as state.apply you're prefacing the name of the state with `config.dev`, and in your GIT repository there is a subdirectory called `config/dev` that contains the states you're expecting to see.  Also, any error messages that you're seeing when attempting to run the states.  Thanks!
