### ISSUE TITLE
Multiple requisites not applied in 3002

### ISSUE THREAD

**Issue by TavecchiaG** [saltstack/salt#59026]
Hi, 

We are upgrading Salt from 3000.3 to 3002 and are experiencing unusual behavior under multiple requisites.

Given the following state:
```
A:
  cmd.run:
    - name: echo Hi A

B:
  cmd.run:
    - name: echo Hi B
    - require:
      - cmd: A

C:
  cmd.run:
    - name: echo Hi C
    - onfail:
      - cmd: B
    - onchanges:
      - cmd: A
```
We would expect step C to be executed only if B fails and A successfully executes with changes
That is exactly what we see in 3000.3 but not in 3002

**Salt 3002**
```
local:
----------
          ID: A
    Function: cmd.run
        Name: echo Hi A
      Result: True
     Comment: Command "echo Hi A" run
     Started: 13:44:24.784490
    Duration: 10.008 ms
     Changes:
              ----------
              pid:
                  31900
              retcode:
                  0
              stderr:
              stdout:
                  Hi A
----------
          ID: B
    Function: cmd.run
        Name: echo Hi B
      Result: True
     Comment: Command "echo Hi B" run
     Started: 13:44:24.795096
    Duration: 8.29 ms
     Changes:
              ----------
              pid:
                  31901
              retcode:
                  0
              stderr:
              stdout:
                  Hi B
----------
          ID: C
    Function: cmd.run
        Name: echo Hi C
      Result: True
     Comment: Command "echo Hi C" run
     Started: 13:44:24.804015
    Duration: 7.198 ms
     Changes:
              ----------
              pid:
                  31902
              retcode:
                  0
              stderr:
              stdout:
                  Hi C

Summary for local
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total run time:  25.496 ms
```

**Salt 3000.3**
```
local:
----------
          ID: A
    Function: cmd.run
        Name: echo Hi A
      Result: True
     Comment: Command "echo Hi A" run
     Started: 13:53:13.793835
    Duration: 11.943 ms
     Changes:
              ----------
              pid:
                  12954
              retcode:
                  0
              stderr:
              stdout:
                  Hi A
----------
          ID: B
    Function: cmd.run
        Name: echo Hi B
      Result: True
     Comment: Command "echo Hi B" run
     Started: 13:53:13.806508
    Duration: 9.238 ms
     Changes:
              ----------
              pid:
                  12955
              retcode:
                  0
              stderr:
              stdout:
                  Hi B
----------
          ID: C
    Function: cmd.run
        Name: echo Hi C
      Result: True
     Comment: State was not run because onfail req did not change
     Started: 13:53:13.816423
    Duration: 0.016 ms
     Changes:

Summary for local
------------
Succeeded: 3 (changed=2)
Failed:    0
------------
Total states run:     3
Total run time:  21.197 ms
```

Here the result of `salt --versions-report`
```
Salt Version:
           Salt: 3002

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.9.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core

```

```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist: centos 7.9.2009 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.19.128-microsoft-standard
         system: Linux
        version: CentOS Linux 7.9.2009 Core

```

**Comment by markuskramerIgitt** [comment]
state C also wrongly executes on 3001.
I tried above state and the reverse `_in` logic, which I prefer generally.

 `onfail_in  C` is no applied in combination with a second (reverse) requisite `onchanges_in  C`

I therefore agree with @TavecchiaG multiple requisites are no longer applied.



3000.3 contained different logic regarding the internal variable "onchangesmet".

REVERSE LOGIC

```

A:
  cmd.run:
    - name: echo Hi A
#    - onchanges_in:
#      - cmd: C
    - require_in:
      - cmd: B

B:
  cmd.run:
    - name: echo Hi B
    - onfail_in:
      - cmd: C

C:
  cmd.run:
    - name: echo Hi C

```

RESULT

```

          ID: A
    Function: cmd.run
        Name: echo Hi A
      Result: True
     Comment: Command "echo Hi A" run
     Started: 09:57:52.988914
    Duration: 202.573 ms
     Changes:
              ----------
              pid:
                  18820
              retcode:
                  0
              stderr:
              stdout:
                  Hi A
----------
          ID: B
    Function: cmd.run
        Name: echo Hi B
      Result: True
     Comment: Command "echo Hi B" run
     Started: 09:57:53.193487
    Duration: 184.003 ms
     Changes:
              ----------
              pid:
                  17640
              retcode:
                  0
              stderr:
              stdout:
                  Hi B
----------
          ID: C
    Function: cmd.run
        Name: echo Hi C
      Result: True
     Comment: Command "echo Hi C" run
     Started: 09:57:53.379488
    Duration: 159.118 ms
     Changes:
              ----------
              pid:
                  17832
              retcode:
                  0
              stderr:
              stdout:
                  Hi C

Summary for local
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total run time: 545.694 ms


```
VERSION

```
C:\salt\salt-call.bat --versions-report
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0


```
