### ISSUE TITLE
[BUG] win_lgpo exception during unpack

### ISSUE THREAD

**Issue by prensing** [saltstack/salt#59059]
**Description**
I am trying to set a policy on a Windows 10 machine. Most machines are fine, but 1 particular machine throws an exception on many of the policies. The error is:
```
   File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\modules\win_lgpo.py", line 5675, in _getDataFromRegPolData
        for v in struct.unpack(b"I", value):
    struct.error: unpack requires a buffer of 4 bytes
```
(run with debug is attached)

**Setup**
Win 10 machine, version 
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
Run:
```
  salt <machine> lgpo.set_computer_policy DriverSearchPlaces_DontSearchWindowsUpdate Enabled
```
Currently that policy is not set on that machine.

**Expected behavior**
Most machines enable the policy just fine. 

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Taylor-laptop:
    Salt Version:
              Salt: 3002.2
     
    Dependency Versions:
              cffi: 1.12.2
          cherrypy: 17.4.1
          dateutil: 2.8.0
         docker-py: Not Installed
             gitdb: 2.0.5
         gitpython: Not Installed
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.0.7
           msgpack: 1.0.0
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.19
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
      python-gnupg: 0.4.4
            PyYAML: 5.3.1
             PyZMQ: 18.0.1
             smmap: 2.0.5
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.1
     
    System Versions:
              dist:   
            locale: cp1252
           machine: AMD64
           release: 10
            system: Windows
           version: 10 10.0.19041 SP0

```
[salt-lgpo-crash.txt](https://github.com/saltstack/salt/files/5623619/salt-lgpo-crash.txt)

</details>

**Additional context**
