### ISSUE TITLE
[BUG] Mine top.sls Pillar Matching Does Not Work

### ISSUE THREAD

**Issue by Daemonslayer2048** [saltstack/salt#59052]
**Description**
Mine top.sls does not appear to support pillar based targeting (or it is not working). 

**Setup**
No configs are particularly relevant, use you preferred fs for hosting your config files, I use GitFS but your sls files on the master's local FS should make no difference. 

**Steps to Reproduce the behavior**
Add a mine top.sls like so:
``` yaml
base:
  'I@Client:_id:ClientName':
    - match: compound
    - test
```
then create a test.sls associated with the top file:
``` yaml
mine_functions:
  All_Minion_Roles:
    - mine_function: grains.get
    - Role
    - allow_tgt: 'Role:(Developer|Master)'
    - allow_tgt_type: 'grain_pcre'
```

Make sure to refresh the pillars on the minions targeted by the pillar match we can kill two birds with one stone by making sure our target makes sense and refreshing by running a refresh pillar like so:
```sudo salt -C 'I@Client:_id:ClientName' saltutil.refresh_pillar```  

Your target match here should be the same as what was defined in the top.sls, 
Simply run a ```sudo salt -C 'I@Client:_id:ClientName' pillar.items```
and you will see your mine functions have not been added.

**Expected behavior**
Mine functions should be placed on a minion with pillar matching (at least according to the docs [here](https://docs.saltstack.com/en/latest/topics/mine/#minions-targeting-with-mine))

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 
Salt Master:  

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.99.0
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 1.1.1
        Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist: centos 8 Core
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-193.28.1.el8_2.x86_64
        system: Linux
       version: CentOS Linux 8 Core
```

Salt Minion:  

```
    Salt Version:
               Salt: 3001.3
     
    Dependency Versions:
               cffi: 1.12.3
           cherrypy: Not Installed
           dateutil: 2.8.0
          docker-py: 4.0.2
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.10.3
            libgit2: 0.28.4
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.1
       mysql-python: 0.10.0
          pycparser: 2.14
           pycrypto: 2.6.1
       pycryptodome: 3.9.8
             pygit2: 1.0.3
             Python: 3.7.9 (default, Aug 19 2020, 17:05:11)
       python-gnupg: Not Installed
             PyYAML: 5.3.1
              PyZMQ: 18.0.2
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.3.2
     
    System Versions:
               dist: fedora 31 
             locale: UTF-8
            machine: x86_64
            release: 5.7.15-100.fc31.x86_64
             system: Linux
            version: Fedora 31 

```

</details>

**Additional context**
I have tried the following combinations of pillar targeting:
``` yaml
base:
  'I@Client:_id:ClientName':
    - match: pillar
    - test
```    

``` yaml
base:
  'J@Client:_id:ClientName':
    - match: compound
    - test
```

``` yaml
base:
  'J@Client:_id:ClientName':
    - match: pillar
    - test
```  

``` yaml
base:
  'J@Client:_id:ClientName':
    - test
```  

``` yaml
base:
  'I@Client:_id:ClientName':
    - test
```  

Finally, after all the attempts trying to make a pillar match I have a grain already set that is very similar:  

``` yaml
base:
  'Client:company:ClientName':
    - match: grain
    - test
```  
and now it works.....
Some of the variation of target matching I expected to not work but did them as a sanity check anyways, just in case I was missing something.
