### ISSUE TITLE
[DOCS] firewalld state improve examples

### ISSUE THREAD

**Issue by Cobra1978** [saltstack/salt#59111]
**Description**
The documentation of how to add a Rich Rule could be improved because the examples, INMHO, dosen't give right hint about how to add complex rule like port forwarding based on destination ip 

**Suggested Fix**
Add a complex example of a Rich Rule, something like:

```
myrule:
  firewalld.present:
    - name: public
    - prune_services: False
      rich_rules:
        - rule family="ipv4" destination address="myip" forward-port port="fromport" protocol="tcp" to-port="toport"
```

**Type of documentation**
Salt Modules/States

**Location or format of documentation**
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.firewalld.html

best Regards
