### ISSUE TITLE
[BUG] Official docker image File handler descriptor per process.

### ISSUE THREAD

**Issue by n-holmstedt** [saltstack/salt#59110]
**Description**
Using the saltstack/salt alpine linux-images, proxy or minion-process hang when reaching 80 file handle descriptors, throwing 'OSError: [Errno 24] No file descriptors available'. 

Error does not appear with a RHEL-setup on physical hosts, or on own-built docker image using ubuntu:18.04 with Salt 3002.2

Playing around with ulimit in the container or in docker have no effect on the issue.

**Setup**
* Images used to reproduce error: saltstack/salt:latest, saltstack/salt:3001.3-alpine3.12
* Vanilla master 
* Vanilla minion

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
* Stacking job queue using:
```
/ # for i in $(seq 1 100); do salt --async alpine-minion test.sleep 15; done
```
* On minion: 
```
/ # ls -la /proc/26/fd | wc -l
82
```
<details><summary>Stacktrace</summary>

```
Future <salt.ext.tornado.concurrent.Future object at 0x7fd32b0dbb90> exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/site-packages/salt/minion.py", line 1539, in _handle_decoded_payload
    args=(instance, self.opts, data, self.connected)
  File "/usr/local/lib/python3.7/site-packages/salt/utils/process.py", line 800, in __init__
    self._signal_handled = multiprocessing.Event()
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 92, in Event
    return Event(ctx=self.get_context())
  File "/usr/local/lib/python3.7/multiprocessing/synchronize.py", line 324, in __init__
    self._cond = ctx.Condition(ctx.Lock())
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 77, in Condition
    return Condition(lock, ctx=self.get_context())
  File "/usr/local/lib/python3.7/multiprocessing/synchronize.py", line 214, in __init__
    self._sleeping_count = ctx.Semaphore(0)
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 82, in Semaphore
    return Semaphore(value, ctx=self.get_context())  File "/usr/local/lib/python3.7/multiprocessing/synchronize.py", line 126, in __init__
    SemLock.__init__(self, SEMAPHORE, value, SEM_VALUE_MAX, ctx=ctx)
  File "/usr/local/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
OSError: [Errno 24] No file descriptors available
```
</details>

<details><summary>docker-compose</summary>

```
version: '3.4'

services: 
    master:
        image: saltstack/salt:latest
        hostname: test-master
        container_name: test-master
        networks:
            - salt-test-network
        command: sleep infinity
    minion: 
        image: saltstack/salt:latest
        hostname: test-minion
        container_name: test-minion
        networks:
            - salt-test-network
        command: sleep infinity

networks:
    salt-test-network:
        driver: bridge
```
</details>

**Expected behavior**
As with other builds, it should handle larger job queues without issues?

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.7 (default, Apr 24 2020, 22:09:29)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 5.4.39-linuxkit
         system: Linux
        version: Not Installed
```
</details>

**Additional context**
I noticed this issue while working on a Cisco ACI-APIC proxy minion. In some cases i would need to split up workload into many jobs, since the data output would be too large for returning to our message bus when using one or a few jobs. This resulting in creating a reactor that splits up the workload. This caused the proxy-minon to throw and hang as above, which made me delve a bit deeper into the issue. I'm not that familiar with troubleshooting file handle descriptors so i tried to reach out at network-to-code slack, and the official slack, but didn't get any pointers.

**Comment by s0undt3ch** [comment]
After reading https://stackoverflow.com/questions/24318543/how-to-set-ulimit-file-descriptor-on-docker-container-the-image-tag-is-phusion it looks like there isn't much we can do on the image itself and it also looks like we either have to change the hosts docker config or pass `--ulimit` to `docker run`.

I will actually take your CLI examples for a spin Monday to see if I can reach a different conclusion.

**Comment by n-holmstedt** [comment]
Would be great to have another pair of eyes on it, if i'm missing something. I couldn't see any changes when using ulimit in docker, the settings would affect the global settings on files but wouldn't affect the single process. 

I'll copy your build-pipes and change the distribution for now.

**Comment by s0undt3ch** [comment]
I confirm that not even when setting ulimit's higher will it stop the minion from throwing tracebacks.
```yaml
version: '3.4'

services:
  master:
    image: saltstack/salt:latest
    hostname: test-master
    container_name: test-master
    networks:
      - salt-test-network
    command: sleep infinity
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
  minion:
    image: saltstack/salt:latest
    hostname: test-minion
    container_name: test-minion
    networks:
      - salt-test-network
    command: sleep infinity
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000


networks:
  salt-test-network:
    driver: bridge
```
