### ISSUE TITLE
[BUG] `smb_port` for WinRM is used to check if port is open, but not to connect

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#59153]
**Description**

When choosing a non-default `smb_port` using WinRM for deployment, the non-default port is not actually used to create the connection.

**Setup**

`/etc/salt/cloud.providers.d/zd6108.conf`:

```
zd6108_provider:
  minion:
    master: 192.168.96.2
  driver: saltify
```

`/etc/salt/cloud.profiles.d/zd6108.conf`:

```yaml
salt-vagrant-windows:
  ssh_host: 192.168.96.1
  smb_port: 44445
  provider: zd6108_provider
  winrm_port: 5985
  use_winrm: true
  winrm_use_ssl: false
  win_username: vagrant
  win_password: vagrant
  win_installer: /etc/salt/win_installer/Salt-Minion-3002.2-Py3-AMD64-Setup.exe
```

**Steps to Reproduce the behavior**

```bash
salt-cloud -l debug -p salt-vagrant-windows win-vagrant
```

```log
[DEBUG   ] WinRM session connected...
[DEBUG   ] SMB port 44445 on 192.168.96.1 is available
[DEBUG   ] Logging into 192.168.96.1:44445 as vagrant
[INFO    ] Get connection smbprotocol
[ERROR   ] There was a profile error: Failed to connect to '192.168.96.1:445': [Errno 111] Connection refused
```

**Expected behavior**

Connection should be made using the given port.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-54-generic
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Additional context**

`port` is an available argument for `salt.utils.smb.get_conn`, just needs to be added.  That fixed the problem in local testing.
 
https://github.com/saltstack/salt/blob/a0086b167d9fcd8d0ad9ddc01a1ed03294dc9782/salt/utils/cloud.py#L1254-L1257
