### ISSUE TITLE
virt: efi=True forces update of VM

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#59188]
**Description**

When applying a state like the following, the VM should be defined and started at the first `state.apply`, but the subsequent ones should do nothing.

```yaml
vm01:
  virt.running:
    - name: vm01
    - cpu: 1
    - mem: 512
    - boot:
        efi: True
    - disks:
      - name: system
        pool: default
        image: salt://SLES15-SP2-JeOS.x86_64-15.2-kvm-and-xen-GM.qcow2
    - seed: False
```

**Steps to Reproduce the behavior**

Apply 2 times the above state. The second time, the return states `definition: True` indicating the VM definition has been updated.

**Expected behavior**

The second time, the return should state `definition: False` since the state hasn't changed.
