### ISSUE TITLE
[BUG] Master log tells you to check master log for more details

### ISSUE THREAD

**Issue by jeffWelling** [saltstack/salt#59208]
**Description**
Regularly while troubleshooting, the saltmaster log will tell you to check the saltmaster log for more details. 

It's frustrating when the log that you're reading tells you to check the log that you're reading for more details, surely this message could be improved to actually be helpful to the user in some way? At least in situations when the user is indeed looking at the master log. 

**Setup**
An example situation where I hit this log message is when I'm trying to configure gitfs for files on the saltmaster with a repo that doesn't have a correctly configured top file (not correctly configured because I'm still figuring out the details of specifically what files salt is looking for in the git repo).

Here's my /etc/salt/master.d/local.conf file as it is right now, producing this error:
```
fileserver_backend:
  - gitfs

gitfs_provider: pygit2
gitfs_base: master
gitfs_root: salt
gitfs_pubkey: /root/.ssh/id_rsa.pub
gitfs_privkey: /root/.ssh/id_rsa

gitfs_remotes:
  - git@github.com:jeffWelling/saltmaster-from-git.git

pillar_roots:
  master:
    - pillar/
file_roots:
  master:
    - salt/

ext_pillar:
  - git:
    - main git@github.com:jeffWelling/saltmaster-from-git.git:
      - env: '__env__'

log_level: 'debug'

state_top: state_top.sls

state_top_saltenv: "master"

pillar_raise_on_missing: True
git_pillar_provider: pygit2
git_pillar_pubkey: /root/.ssh/id_rsa.pub
git_pillar_privkey: /root/.ssh/id_rsa
```

tree from a point-in-time snapshot of the git repo:
```
root@saltmaster1:~/Projects/saltmaster-from-git# tree
.
|-- LICENSE
|-- README.md
|-- master_top.sls
|-- pillar
|   `-- all.sls
|-- salt
|   `-- service
|       `-- common
|           `-- base.sls
`-- top.sls
```

**Steps to Reproduce the behavior**
Install saltmaster from bootstrap script.
Configure it to pull pillar files from git.
Try to configure gitfs for files on the saltmaster with a repo that doesn't have a correctly configured top file

**Expected behavior**
Log messages in the master log contain helpful details about what file could not be found at what path within the repo, instead of a cyclical reference to check self (master log) for more details. 

**Screenshots**

**Versions Report**
```
root@saltmaster1:~# salt --version
salt 3002.2
```

I'm happy to provide any extra details that may be helpful, and I apologize in advance if this is somehow the result of a PEBKAC.

Thanks for helping to make Saltstack so awesome, keep up the good work!
