### ISSUE TITLE
[BUG] pkg.installed with sources re-downloads every time

### ISSUE THREAD

**Issue by satwell** [saltstack/salt#59241]
**Description**
Using pkg.installed on Debian with `sources` to install a `.deb` fetches over https results in re-downloading the same file every run.

**Setup**
Reproducible with an empty minion config and basic SLS (as `/tmp/install.sls`):

```
sops_package:
  pkg.installed:
    - sources:
      - sops: https://github.com/mozilla/sops/releases/download/v3.6.1/sops_3.6.1_amd64.deb
```

**Steps to Reproduce the behavior**

The `sops` package is already installed:

```
# salt-call --local pkg.version sops
local:
    3.6.1
```

And the file is already in the cache:

```
 # ls -l /var/cache/salt/minion/extrn_files/github.com/mozilla/sops/releases/download/v3.6.1/sops_3.6.1_amd64.deb 
-rw-r--r-- 1 root root 13135134 Jan  6 16:09 /var/cache/salt/minion/extrn_files/github.com/mozilla/sops/releases/download/v3.6.1/sops_3.6.1_amd64.deb
```

But running the state causes a re-download:

```
# salt-call --local --log-level debug state.template /tmp/install.sls
[...]
[INFO    ] Running state [sops_package] at time 16:38:19.150264
[INFO    ] Executing state pkg.installed for [sops_package]
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}', '-W'] in directory '/home/satwell'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Requesting URL https://github.com/mozilla/sops/releases/download/v3.6.1/sops_3.6.1_amd64.deb using GET method
[DEBUG   ] Using backend: tornado
[INFO    ] Executing command ['dpkg', '-I', '/var/cache/salt/minion/extrn_files/github.com/mozilla/sops/releases/download/v3.6.1/sops_3.6.1_amd64.deb'] in directory '/home/satwell'
[INFO    ] All specified packages are already installed
[INFO    ] Completed state [sops_package] at time 16:38:23.480707 (duration_in_ms=4330.451)
[DEBUG   ] File /var/cache/salt/minion/accumulator/140577000434176 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: sops_package
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 16:38:19.150256
    Duration: 4330.451 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1 
Total run time:   4.330 s
```

**Expected behavior**

Because I've specified the name of a package that's already installed, I wouldn't expect the state do anything.  But even if it does make sense to check the package name/version against the specified `.deb` file, I'd expect salt to use the file already in the cache rather than re-downloading.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:        
          Salt: 3002.2                                                                         
  
Dependency Versions:
          cffi: 1.14.4                                                                         
      cherrypy: Not Installed                                                                  
      dateutil: 2.8.1                          
     docker-py: 4.1.0                          
         gitdb: Not Installed                                                                  
     gitpython: Not Installed                                                                  
        Jinja2: 2.11.2                                                                         
       libgit2: Not Installed                                                                  
      M2Crypto: Not Installed                                                                  
          Mako: 1.1.3
       msgpack: 1.0.0                          
  msgpack-pure: Not Installed                  
  mysql-python: Not Installed                  
     pycparser: 2.20                           
      pycrypto: 2.6.1                          
  pycryptodome: 3.9.7
        pygit2: Not Installed                                                                  
        Python: 3.9.1 (default, Dec  8 2020, 07:51:42)                                         
  python-gnupg: 0.4.6                          
        PyYAML: 5.3.1
         PyZMQ: 20.0.0 
         smmap: Not Installed                  
       timelib: Not Installed                  
       Tornado: 4.5.3
           ZMQ: 4.3.3
            
System Versions:                               
          dist: debian testing bullseye
        locale: utf-8                          
       machine: x86_64                         
       release: 5.9.0-4-amd64      
        system: Linux
       version: Debian GNU/Linux testing bullseye                                              
  
```
</details>

**Comment by frogunder** [comment]
Thank you for reporting this issue. I am seeing the same thing on my end.
Not sure if it is supposed to be like that so will need to get input from the core team on it. 
@saltstack/team-core Can either of you take a look at this when you have time?

Thanks.

**Comment by s0undt3ch** [comment]
I'm 90% sure salt won't parse the version from the filename, at most, `apt` would do that, and since you're providing the `.deb` maybe apt just blindly installs it?
With regards to re-downloading the file, since you don't provide a hash/checksum for the file(don't even know if salt allows that in this scenario), salt will redownload the file, it might have changed since the last run.
I'm leaning towards this not being a bug.

**Comment by s0undt3ch** [comment]
Of you had a step which downloaded the `.deb` file using [`file.managed`](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed), while providing the source hash, salt would only download the file once.
Then you'd make the `.deb` install use `on_changes` for the download step.

This way, the file would be downloaded only once, and it would only install it when changing.

**Comment by satwell** [comment]
Ah, I think I misunderstood the difference between `pkg.installed` and `pkg.latest`.  I was considering `pkg.installed` as meaning "install the package name if it's not already installed', but I see now in that docs actually say, "Ensure that the package is installed, and that it is the correct version (if specified)."  And it makes sense that specifying a package file source means the same thing as specifying a version.

So I agree that this is not a bug.

It would be very useful if there was a way to specify the source hash when using `pkg.installed` with `sources`.  That way you could get proper caching behavior like `file.managed`.  Does it make sense to turn this issue into a feature request, or should a file a new one?

**Comment by waynew** [comment]
@satwell FWIW you can accomplish this with `file.managed` and an `onchanges`. Something like this:

```
download_pkg:
  file.managed:
    - name: /var/cache/sops_3.6.1_amd64.deb  {# Or whatever #}
    - source: https://github.com/mozilla/sops/releases/download/v3.6.1/sops_3.6.1_amd64.deb
    - source_hash: sha256=96febf3c8c2bd1a92b7e3e34d3a2989a604b3eaed6b81e9485295133f8229b0a
sops_package:
  pkg.installed:
    - sources:
      - sops: /var/cache/sops_3.6.1._amd64.deb
    - onchanges:
        - file: download_pkg
```

I might not have that invocation 100% accurate, but basically, something to that effect. I'm pretty sure the onchanges requisite works for `pkg.installed` - you can get more information on requisites here: https://docs.saltstack.com/en/latest/ref/states/requisites.html

**Comment by duhow** [comment]
Faced this same ✌🏻 bug ✌🏻 and trying to research a workaround I am using `unless` ... this seems to work.

```yaml
{% set package = "sops" %}

{{ package }}_package:
  pkg.installed:
    - name: {{ package }}
    - unless:
      - dpkg -l {{ package }}
    - sources:
      - {{ package }}: https://github.com/mozilla/sops/releases/download/v3.6.1/sops_3.6.1_amd64.deb
```
