### ISSUE TITLE
[BUG] x509.certificate_managed rolls certificates every now and then

### ISSUE THREAD

**Issue by stefan-as** [saltstack/salt#59315]
**Description**
Due to a combination of legacy Python2 Salt code and Python3.5 behavior on Debian Stretch, managed certificates are rolled every now and then.

**Setup**

```
sensu_ssl_cert:
  x509.certificate_managed:
    - name: /etc/sensu/ssl/sensu.crt
    - public_key: /etc/sensu/ssl/sensu.key
    - ca_server: {{ ca_server }}
    - signing_policy: {{ signing_policy }}
    - commonName: sensu.{{ grains.fqdn }}
    - days_valid: 90
    - days_remaining: 30
    - group: sensu
    - mode: 0644
    - require:
      - x509: sensu_ssl_key
```

**Steps to Reproduce the behavior**
`salt-call state.apply`
`salt-call x509.read_certificate /etc/sensu/ssl/sensu.crt`

**Expected behavior**
Idempotent behavior, no changes until the cert is out of date.

**Screenshots**

* state.apply leads to `Certificate properties are different: Subject, Subject Hash`.
* x509.read_certificate outputs `Subject: commonName` and `Subject: CN` by random.

**Versions Report**

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.5.3
     docker-py: Not Installed
         gitdb: 2.0.0
     gitpython: 2.1.1
        Jinja2: 2.9.4
       libgit2: Not Installed
      M2Crypto: 0.37.1
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.5.3 (default, Nov 18 2020, 21:09:16)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.1
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.1
 
System Versions:
          dist: debian 9 stretch
        locale: UTF-8
       machine: x86_64
       release: 4.9.0-14-amd64
        system: Linux
       version: Debian GNU/Linux 9 stretch
```

**Additional context**

The issue is caused by a combination of bugs. As far as I see, at least the first bug should be solved, since it concerns all versions of Python3.

1. In https://github.com/saltstack/salt/blob/ea409f0723fd816c81453fd85b7b297ecc4c66c8/salt/states/x509.py#L436 there is a comparison between unmatching types:
```
(Pdb) p k
'Subject Hash'
(Pdb) p v
b'9E:B4:30:22'
(Pdb) p cert_info[k]
'9E:B4:30:22'
```
This way the code path always takes the long way into deep checking, although the involved hashes would be fine. Since there are no Python2 versions for Salt 3002, the compatibility code could be dropped and replaced by a clean check of the hashes.

2. The deep check fails for Python<3.6 every now and then. This is caused by the fact that dictionaries are not stable in Python<3.6. In https://github.com/saltstack/salt/blob/ea409f0723fd816c81453fd85b7b297ecc4c66c8/salt/modules/x509.py#L333-L335 subject nid's are returned in a random manner, while `CN` and `commonName` uses the same `nid_num`. This leads to situations where a subject rendered as `CN` is compared to a subject containing `commonName`, they don't match and the cert is rolled over. This is the situation for at least Debian Stretch and could by solved by sorting `subject.nid.items()` before looping the nids.
