### ISSUE TITLE
[BUG] Networks interfaces names are not consistent on Windows

### ISSUE THREAD

**Issue by ymasson** [saltstack/salt#59352]
**Description**
In grains, the networks interfaces names are the networks adapters names. (like `Intel(R) 82574L Gigabit Network Connection`)
But, the module `win_ip.get_all_interfaces()` return the system name. (like `Ethernet0`)

When i use the state `win_dns_client.dns_exists`, it work with
```
dns_test:
  win_dns_client.dns_exists:
      - name: "Ethernet0"
      - interface: "Ethernet0"
      - replace: True
```
But doesn't work with:
```
dns_test:
  win_dns_client.dns_exists:
      - name: "Intel(R) 82574L Gigabit Network Connection"
      - interface: "Intel(R) 82574L Gigabit Network Connection"
      - replace: True
```

**Expected behavior**
The network interfaces names should be consistent between grains and module.
And, be the system name.

**Versions Report**
```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-13-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>
