### ISSUE TITLE
[ERROR   ][471183] Uncaught exception while updating roots fileserver cache

### ISSUE THREAD

**Issue by yxiaoy6** [saltstack/salt#59363]
### Description of Issue

[salt.master      :464 ][ERROR   ][471183] Uncaught exception while updating roots fileserver cache
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/master.py", line 460, in _do_update
    update_func(*args)
  File "/usr/lib/python3/dist-packages/salt/fileserver/roots.py", line 200, in update
    '{0}:{1}\n'.format(file_path, mtime)
  File "/usr/lib/python3/dist-packages/salt/utils/stringutils.py", line 60, in to_bytes
    raise exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3/dist-packages/salt/utils/stringutils.py", line 53, in to_bytes
    return s.encode(enc, errors)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 107-112: ordinal not in range(128)
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
```
cat init.sls 
include:
  - .jdk_install
  - .zookeeper_install
  - .zk_jmx_monitor
  - .zookeeper_running
cat jdk_install.sls 
extract_jdk:
  archive.extracted:
    - name: /opt/java/jdk
    - source: salt://kafka/zookeeper_install/files/packages/jdk.tar.gz
    - user: root
    - group: root
    - mode: 755
    - enforce_toplevel: False
    - if_missing: /opt/java/jdk

jdk_config:
  file.append:
    - name: /etc/profile
    - text:
      - export JAVA_HOME=/opt/java/jdk
      - export JRE_HOME=$JAVA_HOME/jre
      - export PATH=$JAVA_HOME/bin:$PATH
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2019.2.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Oct  7 2020, 17:19:02)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1103-azure
         system: Linux
        version: Ubuntu 16.04 xenial
