### ISSUE TITLE
[DOCS] transfer files from a proxy minion device to a master?

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#59394]
**Description**
So for a regular minion we can specify a file and send that to the master if we have the appropriate options setup in the master config to allow files from minion. However I am not confident in being able to specify a file on a network device from a proxy minion to send to the master.

because that salt state will try to grab the file from the proxy minions own file system rather than the network device?

```YAML
device_logs:  <-- executed from a proxy minion
  module.run:
    - name: cp.push
    - path: /network/device/logfile.log <-- on the network device
    - upload_path: /var/cache/tmp  <-- on the master
```
Could someone clarify how they would use a proxy to pull a file from the device to the master in a similar manner, or does the above state work with proxies as well?
