### ISSUE TITLE
[BUG] Replica support is missing the replicaSet option in MongoDB pillar 

### ISSUE THREAD

**Issue by lahdekorpi** [saltstack/salt#59402]
**Description**
The mongo_ext support for pillar data claims to support replica sets:

> Supports replica sets by specifying all hosts in the set, comma-delimited.

This doesn't however work if you need (as you do in most cases) specify the replicaSet for the connection.

**Setup**
```yaml
master_tops:
  mongo:
    id_field: id
    collection: salt_tops

ext_pillar:
  - mongo: {collection: salt_pillar, id_field: id}

ext_pillar_first: false

#####   mongodb connection settings  #####
##########################################
mongo.db: salt
mongo.indexes: true
mongo.uri: host1.mongodb.net,host2.mongodb.net,host3.mongodb.net
# no option for replicaSet=atlas-12345-shard-0
mongo.user: salt
mongo.password: secret
```

**Versions Report**
v3002.2

**Additional context**
There is an option for setting a URI in [the "MongoDB future" returner](https://github.com/saltstack/salt/blob/v3002.2/salt/returners/mongo_future_return.py#L25) that would solve the issue here as well.
