### ISSUE TITLE
EndeavourOS not detected as an Arch variant in pkg state

### ISSUE THREAD

**Issue by nergdron** [saltstack/salt#59455]
### Description of Issue
when using salt on EndeavourOS, and using the pkg state, it doesn't detect that this is an arch variant and that salt.modules.pacmanpkg should be used.

### Steps to Reproduce Issue
try to apply any pkg state, see it fail with an error like:

```
          ID: base_pkgs
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'base'
              Reason: 'pkg' __virtual__ returned False: pkg module could not be loaded
     Changes:   
```

### Versions Report
```yaml
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.9
        pygit2: Not Installed
        Python: 3.9.1 (default, Feb  6 2021, 06:49:13)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: endeavouros rolling n/a
        locale: utf-8
       machine: x86_64
       release: 5.10.13-arch1-2
        system: Linux
       version: EndeavourOS rolling n/a
```

reporting this per the note on the pacmanpkg module docs page:
https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.pacmanpkg.html
