### ISSUE TITLE
[BUG] salt fails on templating if lsb variables aren't set

### ISSUE THREAD

**Issue by nergdron** [saltstack/salt#59458]
**Description**
running any state on EndeavourOS fails in the templating stage with the error: `Rendering SLS 'base:docker' failed: Jinja variable 'dict object' has no attribute 'lsb_distrib_codename'`

**Setup**

**Steps to Reproduce the behavior**
apply a state, see it fail.

**Expected behavior**
state succeeds.

**Versions Report**
<details><summary>salt --versions-report</summary>
```yaml
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.9
        pygit2: Not Installed
        Python: 3.9.1 (default, Feb  6 2021, 06:49:13)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: endeavouros rolling n/a
        locale: utf-8
       machine: x86_64
       release: 5.10.13-arch1-2
        system: Linux
       version: EndeavourOS rolling n/a
```
</details>

**Additional context**
it looks like `salt/utils/templates` fails if lsb stuff isn't set, like how codename isn't set on Endeavour. instead, it should continue if there are unset keys, or perhaps present them as an empty string.

```
raceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/salt/utils/templates.py", line 498, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 3, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'lsb_distrib_codename'
```

**Comment by twangboy** [comment]
Please provide the state you are running.

**Comment by nergdron** [comment]
sorry if I wasn't clear, this fails on literally any state. it happens in the grains collection phase, before any state is run. so the state is irrelevant.

**Comment by twangboy** [comment]
I just created a simple state:
```
[shane@endeavouros salt]$ cat /srv/salt/t/cmd/run.sls
run_any_state:
  cmd.run:
    - name: echo "Hello"
```
I was able to run the state successfully:
```
[shane@endeavouros salt]$ sudo salt-call --local state.apply t.cmd.run
local:
----------
          ID: run_any_state
    Function: cmd.run
        Name: echo "Hello"
      Result: True
     Comment: Command "echo "Hello"" run
     Started: 10:46:39.072466
    Duration: 4.632 ms
     Changes:
              ----------
              pid:
                  2229
              retcode:
                  0
              stderr:
              stdout:
                  Hello

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   4.632 ms
```
