### ISSUE TITLE
[BUG] Windows log rotation not working?

### ISSUE THREAD

**Issue by generrosity** [saltstack/salt#59568]
**Description**

Have locally set LOG_ROTATE_MAX_BYTES to a low number appended to end of config file, restarted service, and confirmed with 'C:\salt\salt-call.bat config.get LOG_ROTATE_MAX_BYTES' that the setting has been applied.

Existing log C:\salt\var\log\salt\minion is larger than that value (50meg), file doesn't change after restart. After errors are logged into that log the log file doesn't change size. 

**Setup**
At end of standard minion config file;
LOG_ROTATE_MAX_BYTES: 1024

**Steps to Reproduce the behavior**
n/a

**Expected behavior**
Forums and config seem to indicate that after the agent is restarted, the log would be truncated.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3002

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.3.1
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2019Server
         system: Windows
        version: 2019Server 10.0.17763 SP0
```
</details>

**Additional context**
Master is same version.
