### ISSUE TITLE
[BUG] archive.extracted: Output was trimmed to False number of lines

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#59570]
**Description**
Something's clearly not right in the construction of this message. Nothing was actually trimmed.

```
          ID: /opt/logger-tcp-server
    Function: archive.extracted
      Result: True
     Comment: https://example.com/logger-tcp-server-deploy.tar.bz2 extracted to /opt/logger-tcp-server/, 
              due to source_hash update. Output was trimmed to False number of lines
     Started: 18:08:59.319238
    Duration: 6907.903 ms
     Changes:
              ----------
              extracted_files:
                  - logger-tcp-server.jar
                  - lib/spring-core-5.3.3.jar
                  - lib/jaxb-api-2.3.1.jar
                  - lib/javax.activation-api-1.2.0.jar
                  - lib/HikariCP-3.4.5.jar
                  - lib/slf4j-api-1.7.30.jar
                  - lib/commons-codec-1.15.jar
                  - lib/commons-io-2.8.0.jar
                  - lib/lettuce-core-6.0.2.RELEASE.jar
                  - lib/netty-common-4.1.58.Final.jar
                  - lib/netty-handler-4.1.58.Final.jar
                  - lib/netty-resolver-4.1.58.Final.jar
                  - lib/netty-codec-4.1.58.Final.jar
                  - lib/netty-transport-4.1.58.Final.jar
                  - lib/reactor-core-3.4.2.jar
                  - lib/reactive-streams-1.0.3.jar
                  - lib/apm-agent-api-1.20.0.jar
                  - lib/apm-agent-attach-1.20.0.jar
                  - lib/jna-5.3.1.jar
                  - lib/jna-platform-5.3.1.jar
                  - lib/postgresql-42.2.18.jar
                  - lib/checker-qual-3.5.0.jar
                  - lib/logback-classic-1.2.3.jar
                  - lib/logback-core-1.2.3.jar
                  - lib/jcl-over-slf4j-1.7.30.jar
                  - lib/logstash-logback-encoder-6.6.jar
                  - lib/jackson-databind-2.11.4.jar
                  - lib/jackson-annotations-2.11.4.jar
                  - lib/jackson-core-2.11.4.jar
                  - lib/netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar
                  - lib/netty-buffer-4.1.58.Final.jar
                  - lib/netty-transport-native-unix-common-4.1.58.Final.jar
              updated ownership:
                  True
```

**Setup**
```sls
/opt/logger-tcp-server:
  archive.extracted:
    - source: https://example.com/logger-tcp-server-deploy.tar.bz2
    - source_hash: https://example.com/logger-tcp-server-deploy.tar.bz2.sha1
    - source_hash_update: true
    - overwrite: false
    - enforce_toplevel: false
    - user: root
    - group: root
```

**Steps to Reproduce the behavior**
```sh
salt-call state.apply --state-output=changes
```

**Expected behavior**
Something that makes sense

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-65-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>
