### ISSUE TITLE
[BUG] Salt Minion on ServerCore Windows Container Does not work without modification to files. 

### ISSUE THREAD

**Issue by mxrss2** [saltstack/salt#59611]
**Description**
`osrelease` can not be understood in salt using the windows server core container. It appears that this has history with this error. 

**Setup**
grains:

```
PS C:\salt> .\salt-call.bat --local grains.items
local:
    ----------
    biosversion:
        Hyper-V UEFI Release v4.1
    cpu_model:
        AMD Ryzen 9 4900HS with Radeon Graphics
    cpuarch:
        AMD64
    cwd:
        C:\salt
    disks:
    domain:
    fqdn:
        504121ba27a9
    fqdn_ip4:
        - 172.24.189.3
    fqdn_ip6:
        - fe80::6856:3847:6b02:6f78
    fqdns:
    gpus:
    groupname:
    host:
        504121ba27a9
    hwaddr_interfaces:
        ----------
        Microsoft Hyper-V Network Adapter:
            00:15:5D:D3:18:D5
        Software Loopback Interface 2:
            :::::
    id:
        LAPTOP-8TJI0N7O
    init:
        Windows
    ip4_interfaces:
        ----------
        Microsoft Hyper-V Network Adapter:
            - 172.24.189.3
        Software Loopback Interface 2:
            - 127.0.0.1
    ip6_interfaces:
        ----------
        Microsoft Hyper-V Network Adapter:
            - fe80::6856:3847:6b02:6f78
        Software Loopback Interface 2:
            - ::1
    ip_interfaces:
        ----------
        Microsoft Hyper-V Network Adapter:
            - 172.24.189.3
            - fe80::6856:3847:6b02:6f78
        Software Loopback Interface 2:
            - 127.0.0.1
            - ::1
    ipv4:
        - 127.0.0.1
        - 172.24.189.3
    ipv6:
        - ::1
        - fe80::6856:3847:6b02:6f78
    kernel:
        Windows
    kernelrelease:
        10.0.19042
    kernelversion:
        10.0.19041
    locale_info:
        ----------
        defaultencoding:
            cp65001
        defaultlanguage:
            en_US
        detectedencoding:
            cp65001
        timezone:
            Pacific Standard Time
    localhost:
        504121ba27a9
    manufacturer:
        Microsoft Corporation
    master:
        10.0.0.230
    mem_total:
        1022
    motherboard:
        ----------
        productname:
            Virtual Machine
        serialnumber:
            0176-9922-2162-7726-5173-9514-95
    nodename:
        504121ba27a9
    num_cpus:
        2
    num_gpus:
        0
    os:
        Windows
    os_family:
        Windows
    osfinger:
        Windows-10
    osfullname:
        Microsoft Windows Server Datacenter
    osmanufacturer:
        Microsoft Corporation
    osrelease:
        10
    osrelease_info:
        - 10
    osservicepack:
        None
    osversion:
        10.0.19042
    path:
        C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;c:\salt;C:\Users\ContainerAdministrator\AppData\Local\Microsoft\WindowsA
pps
    pending_reboot:
        False
    pid:
        2424
    productname:
        Virtual Machine
    pythonexecutable:
        C:\salt\bin\python.exe
    pythonpath:
        - C:\salt\bin\lib\site-packages\git\ext\gitdb
        - C:\salt\bin\lib\site-packages\git\ext\gitdb
        - C:\salt\bin\Scripts
        - C:\salt\bin\python37.zip
        - C:\salt\bin\DLLs
        - C:\salt\bin\lib
        - C:\salt\bin
        - C:\salt\bin\lib\site-packages
        - C:\salt\bin\lib\site-packages\win32
        - C:\salt\bin\lib\site-packages\win32\lib
        - C:\salt\bin\lib\site-packages\Pythonwin
        - C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
        - C:\salt\bin\lib\site-packages\gitdb\ext\smmap
    pythonversion:
        - 3
        - 7
        - 4
        - final
        - 0
    saltpath:
        C:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt
    saltversion:
        3002.2
    saltversioninfo:
        - 3002
        - 2
    serialnumber:
        0176-9922-2162-7726-5173-9514-95
    server_id:
        2058295993
    shell:
        C:\Windows\system32\cmd.exe
    ssds:
    systempath:
        - C:\Windows\system32
        - C:\Windows
        - C:\Windows\System32\Wbem
        - C:\Windows\System32\WindowsPowerShell\v1.0\
        - C:\Windows\System32\OpenSSH\
        - c:\salt
        - C:\Users\ContainerAdministrator\AppData\Local\Microsoft\WindowsApps
    timezone:
        (UTC-08:00) Pacific Time (US & Canada)
    username:
        User Manager\ContainerAdministrator
    virtual:
        VirtualPC
    windowsdomain:
        WORKGROUP
    windowsdomaintype:
        Workgroup
    zmqversion:
        4.3.1
```

**Steps to Reproduce the behavior**
Insall the salt minion using the Salt-Bootstrap onto a windows container running server core or nano server. Run the command `salt-call --local test.ping`

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'osreleae'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3002.2', 'salt-call')
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1463, in run_script
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\EGG-INFO\scripts\salt-call", line 10, in <module>
    salt_call()
    client.run()
  File "C:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\cli\call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "C:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\cli\caller.py", line 55, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\cli\caller.py", line 320, in __init__
    super().__init__(opts)
  File "C:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\cli\caller.py", line 80, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "C:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\minion.py", line 926, in __init__
    opts["grains"] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\loader.py", line 819, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\grains\core.py", line 1782, in os_data
    os_release_info = grains["osreleae"]
KeyError: 'osreleae'
```
Was able to get the salt install to work by adding a grains["osrelease"] and setting it to 10 this isnt ideal but I can deal with this till a upstream fix hits the community. 

**Expected behavior**
It should be able to run salt commands against the instance. 

**Screenshots**

**Versions Report**

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.12.2
      cherrypy: 17.4.1
      dateutil: 2.8.0
     docker-py: 4.4.3
         gitdb: 2.0.5
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.7
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.4
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 2.0.5
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp65001
       machine: AMD64
       release: UnknownServer
        system: Windows
       version: UnknownServer 10.0.19041 SP0
```
</details>

**Additional context**
Looks like this has been a recurring issue with osrelease grain.
