### ISSUE TITLE
[BUG] onfail(*without postfix*/_any/_all) does not inform about not list form

### ISSUE THREAD

**Issue by NickVeld** [saltstack/salt#59713]
**Description**

I spent much time trying to figure out why the `state-B` with 'onfail: service: state-A' (with linebreaking, onfail_any and onfail_all were also tried with the same result) works every time regardless of status and changes in `state-A`. Finally, I came up with changing `onfail` on `require` and got `The require statement in state 'state-A' in SLS 'some_sls' needs to be formed as a list`. Only after I had added a dash before 'service', 'onfail' started working as expected.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

`onfail` does not work as expected, state-A is succeeded and not changed, state-B is succeeded and changed (the default cmd.run is always marked "changed"):

```
state-A:
  service.running:
    - enable: True

state-B:
  cmd.run:
    - name: pwd
    - onfail:
      service: state-A
```

`onfail` works as expected, state-A is succeeded and not changed, state-B is skipped with "State was not run because onfail req did not change"

```
state-A:
  service.running:
    - enable: True

state-B:
  cmd.run:
    - name: pwd
    - onfail:
      - service: state-A
```

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

Run the states from the **Setup** section.

**Expected behavior**

If an `onfail` statement is not formed as a list it informs about in the same way as `require` does

**Screenshots**

Not applicable.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.2
```
</details>

**Additional context**

Nothing to add.
