### ISSUE TITLE
[BUG] dmidecode/smbios/virt-what should be called with sudo

### ISSUE THREAD

**Issue by johnnybubonic** [saltstack/salt#59794]
**Description**
As mentioned as a solution in #6746 (https://github.com/saltstack/salt/issues/6746#issuecomment-22801339) but seemingly ignored, `dmidecode`/`smbios` in *`salt/modules/smbios.py`* and `dmidecode`/`virt-what` in *`salt/grains/core.py`* should be invoked with `sudo` (if present on the system) by default.

(_Note:_ in the following cases, I'll refer to `dmidecode` explicitly but the same holds for all three utilites in theory.)

For my use case, I run a master as a non-root user. As a result, e.g. `dmidecode` cannot be invoked (and with good reason, normally).

One can SUID `dmidecode`, but this (as is most times when making a binary SUID root) results in a flaw where data can be harvested from e.g. *`/etc/shadow`* by any user on the system (e.g. `dmidecode -d /etc/shadow`, for starters). Hardly a good idea.

As such, the only alternative is to invoke `dmidecode` with `sudo`. With the following line in a sudoers file:

`<salt user> ALL = NOPASSWD:/usr/sbin/dmidecode <dmidecode args salt calls>`

Salt master can be run as a normal/system user, with no affect to its running as root (sudo, to my knowledge, on every installation includes `root	ALL=(ALL) SETENV: ALL` in the default configuration) and still have access to `dmidecode`.

**Suggested Resolution**

* Have salt call the above tools (`dmidecode`, `smbios`, `virt-what`), which all require root privileges, with sudo (if sudo is found present on the system).
** As such, they will need to be invoked with the absolute path to match the sudo rule and to prevent [another hole](https://www.sudo.ws/pipermail/sudo-users/2003-May/001547.html).
* Document exact commands and arguments that Salt invokes for these programs in particular so a properly restricted sudoers entry can be created (and/or provide an example snippet of the entry).

**Comment by danielrobbins** [comment]
Anything is possible, and this seems like a good idea. I'm going to do a more thorough investigation of this (look at code, get background info) and will follow-up on this issue. (I'm on the Salt core team.)

**Comment by johnnybubonic** [comment]
Much appreciated, thank you!

**Comment by danielrobbins** [comment]
@johnnybubonic would you be able to attach a sanitized version of your master conf, as well as any logs or reproduction steps for situations where you encounter the master attempting to run these commands, if you have them available? 

It would be helpful to have more detail on the specific scenarios where the salt master runs into issues when running as non-root, with some logs or reproduction steps. I could try to make this happen myself, but I figure you may be more familiar with the situations in which this occurs.

**Comment by johnnybubonic** [comment]
@danielrobbins Sure. I use includes for my config, so `/etc/salt/master` is empty:

```Bash
[root@hostname ~]# egrep -Ev '^\s*(#.*)?$' /etc/salt/master
[root@hostname ~]# 
```

But here's a concatenation of `/etc/salt/master.d`:

```YAML
rest_cherrypy:
  port: 8000
  host: 127.0.0.1
  log_access_file: /var/log/salt/api.access.log
  log_error_file: /var/log/salt/api.error.log
  disable_ssl: True
  static: /srv/http/salt_api
external_auth:
  ldap:
    InfraAdmins%:
      - '*'
      - '@wheel'
      - '@runner'
      - '@jobs'
auth.ldap.server: ldapserver.domain.tld
auth.ldap.port: 389
auth.ldap.tls: False
auth.ldap.starttls: True
auth.ldap.scope: 2
auth.ldap.no_verify: False
auth.ldap.anonymous: False
auth.ldap.auth_by_group_membership_only: False
auth.ldap.basedn: 'dc=domain,dc=tld'
auth.ldap.binddn: cn={{ username }},ou=Staff,dc=domain,dc=tld
auth.ldap.groupou: 'Staff'
auth.ldap.groupclass: 'inetOrgPerson'
auth.ldap.groupattribute: 'memberOf'
auth.ldap.accountattributename: 'cn'
extension_modules: /usr/local/lib/tablesalt/lib/pillar
ext_pillar:
  - dyninv: foo
user: saltstack
log_level: debug
module_dirs: ['/usr/local/lib/tablesalt/lib']
extension_modules: /usr/local/lib/salt/lib
mysql:
  user: [REDACTED]
  pass: [REDACTED]
  db: [REDACTED]
interface: '::'
ipv6: True
show_jid: True
strip_colors: False
cli_summary: True
file_roots:
  base:
    - /srv/salt
    - /usr/local/lib/tablesalt/formulas/enabled
fileserver_backend:
  - roots
  - git
pillar_roots:
  base:
    - /srv/pillar
ext_pillar_first: True
keysize: 4096
sign_pub_messages: True
ssl:
  keyfile: /etc/letsencrypt/live/hostname.domain.tld/privkey.pem
  certfile: /etc/letsencrypt/live/hostname.domain.tld/fullchain.pem
  ssl_version: PROTOCOL_TLSv1_2
failhard: True
hash_type: sha512
```


Honestly, the only useful part there is probably line 32, `user: saltstack`.

I don't seem to actually be seeing it in logs (anymore), at least with 3002.5. Previously I was seeing it in the master's log (which I found exceptionally weird, since it was a master and I don't know why it'd even need to call dmidecode) but that doesn't seem to be happening anymore.

It's not a hindrance to me personally; I run my minions as root. But this would allow for more accurate grains on minions that may be restricted to non-root users.

On second thought, this may be a duplicate of https://github.com/saltstack/salt/issues/39184 - and PR https://github.com/saltstack/salt/pull/39504 would explain why I no longer see it in the log as I believe the messages are now suppressed.
