### ISSUE TITLE
[BUG] Master configuration read hundreds of times during normal start up

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#59807]
**Description**

This is not a new issue by any means, but now it feels excessive: I've started looking into Salt 3002.5 and the configuration file is read no less than 646 times. 646 times!!! https://gist.github.com/mirceaulinic/b0fb01eff78ea600c2bf2c205a2525a5 (and that's just during the initial startup - to be clear)

**Setup**

Nothing extraordinary, but here it is the Master config:

<details>
<summary>
 
``/etc/salt/master``
</summary>

```yaml
pillar_roots:
  base:
    - /root/salt/salt/pillar

file_roots:
  base:
    - /root/salt/salt

fileserver_backend:
  - roots
  - git

gitfs_provider: pygit2
gitfs_remotes:
  - 'git@gitlab.example.com:rnd/salt.git':
    - root: salt
    - pubkey: /root/.ssh/id_rsa.pub
    - privkey: /root/.ssh/id_rsa

on_demand_ext_pillar:
  - git

ext_pillar_first: true
ext_pillar:
  - git:
    - 'master git@gitlab.example.com:rnd/salt.git':
      - root: salt/pillar
      - pubkey: /root/.ssh/id_rsa.pub
      - privkey: /root/.ssh/id_rsa
```

</details>

**Steps to Reproduce the behavior**

Put the contents above into `/etc/salt/master`, then run `salt-master -l debug`.

**Expected behavior**

Should probably read the config and the other files only several times not hundreds. Not only it's disingenuous, but now the Master start up is even slower than it used to be, and probably this is one of the main reasons.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: 0.26.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: 1.3.10
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: 0.26.2
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 4.15.0-136-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```
</details>
