### ISSUE TITLE
[BUG] schedule states do not report changes

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#59844]
**Description**
The `schedule.absent` state never reports changes, even if it does or would do something.
The `schedule.present` state only reports changes if it's going to change an existing job.

**Steps to Reproduce the behavior**
```yaml
# salt-call state.single schedule.present job1 function=test.ping seconds=3600 --state-output=full --state-verbose=true
local:
----------
          ID: job1
    Function: schedule.present
      Result: True
     Comment: Adding new job job1 to schedule
     Started: 16:16:22.962856
    Duration: 46.496 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  46.496 ms
# salt-call state.single schedule.absent job1 test=true --state-output=full --state-verbose=true
local:
----------
          ID: job1
    Function: schedule.absent
      Result: True
     Comment: Job: job1 would be deleted from schedule.
     Started: 16:11:27.781563
    Duration: 16.764 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  16.764 ms
#  salt-call state.single schedule.absent job1 --state-output=full --state-verbose=true
local:
----------
          ID: job1
    Function: schedule.absent
      Result: True
     Comment: Removed job job1 from schedule
     Started: 16:12:26.271653
    Duration: 43.652 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  43.652 ms
# salt-call state.single schedule.absent job1 --state-output=full --state-verbose=true
local:
----------
          ID: job1
    Function: schedule.absent
      Result: True
     Comment: Job job1 not present in schedule
     Started: 16:12:40.613183
    Duration: 11.948 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  11.948 ms
```

**Expected behavior**
State should report changes whenever they do (or in test mode, would do) something.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.5

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-67-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**
The documentation for the `schedule.absent` `persist` parameter is also wrong.
