### ISSUE TITLE
[FEATURE REQUEST] Add ability to S3FS to limit to specific directory

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#59890]
**Is your feature request related to a problem? Please describe.**
When using a shared S3 bucket for S3FS within an org it is beneficial to limit the path that is searched/cache by the Salt master. The idea here being that we could use this similar to gitfs where you can specify the file path in the repo as the starting point for the environment.

**Describe the solution you'd like**
The current configuration looks like this:

```
s3.buckets:
  production:
    - bucket1
    - bucket2
  staging:
    - bucket3
    - bucket4
```

It would be nice to be able to specify something like this:

```
s3.buckets:
  production:
    - bucket1:/path/to/start
    - bucket2:/
  staging:
    - bucket3:/path/to/start
    - bucket4:/
```

Or to have an option like [gitfs_root](https://docs.saltproject.io/en/latest/ref/configuration/master.html#gitfs-root).
