### ISSUE TITLE
[BUG] Salt-Cloud: Unable to pass SSH timeout param -oConnectTimeout

### ISSUE THREAD

**Issue by cheburakshu** [saltstack/salt#59901]
**Description**
I am using salsify driver to install a minion on a remote host. When there are issues with the SSH connection, salt-cloud initiated SSH process hangs indefinitely. L1492 sets `timeout` instead of `ssh_timetout` in kwargs, when calling root_cmd in L1504 which expects `ssh_timeout`. So, `ssh_timeout` gets missed even though it is present.

Runner invocation in code:

```
__salt__['cloud.profile'](profile_name, minion_id, ssh_timeout=15, hard_timeout=900, show_deploy_args=False)
```

```
2021-03-25 13:32:26,838 [salt.loaded.int.utils.cloud][DEBUG   ] [11739] SSH command: 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none  -p 22 root@10.196.195.92 /tmp/.saltcloud-84bd4974-0c73-48f6-9783-7fdd3784b0fc/deploy.sh -c '/tmp/.saltcloud-84bd4974-0c73-48f6-9783-7fdd3784b0fc'  -x python3 '
```

```
[root@cava-6-242-186 cloud.providers.d]# cat ssc_saltify_provider.conf 
ssc_saltify_provider:
  driver: saltify
``` 

```
[root@cava-6-242-186 cloud.profiles.d]# cat ssc_10.196.195.92_profile.conf
ssc_10.196.195.92_profile:
  deploy: true
  minion:
    master: cava-6-242-186.eng.vmware.com
  password: xxx
  priv_key: ''
  provider: ssc_saltify_provider
  pub_key: ''
  script_args: ' -x python3 '
  ssh_host: 10.196.195.92
  ssh_timeout: 15
  ssh_username: root
[root@cava-6-242-186 cloud.profiles.d]#
```

https://github.com/saltstack/salt/blob/3f3010415d7e12b9bfad15efa592ed024e314a6a/salt/utils/cloud.py#L1488-L1495

https://github.com/saltstack/salt/blob/3f3010415d7e12b9bfad15efa592ed024e314a6a/salt/utils/cloud.py#L1504-L1510

https://github.com/saltstack/salt/blob/3f3010415d7e12b9bfad15efa592ed024e314a6a/salt/utils/cloud.py#L2427-L2428

```
[root@cava-6-242-186 salt]# salt-master -V
Salt Version:
           Salt: 3001.3
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: 18.5.0
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.6.8 (default, Oct  5 2020, 17:12:01)
   python-gnupg: 0.4.5
         PyYAML: 5.2
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1160.15.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
 
[root@cava-6-242-186 salt]# 

```
