### ISSUE TITLE
[BUG] salt minion broken in Springdale Open Enterprise #59161

### ISSUE THREAD

**Issue by mrc668** [saltstack/salt#59900]
**Description**
salt-minion is unable to verify packages are installed (presumably install the if requried.
This is an identical bug to 
salt minion broken in CentOS Stream #59161

with the "same" fix: Add 
```
"Springdale Open Enterprise": "RedHat",
```
to  
```
/usr/lib/python3.6/site-packages/salt/grains/core.py
```

**Setup**
```
chrony:
  pkg:
    - installed
  service.running:
    - name: chronyd
    - enable: true
    - watch:
      - file: /etc/chrony.conf
  user.present:
    - home: /var/lib/chrony
    - shell: /sbin/nologin
```

**Steps to Reproduce the behavior**
Install Springdale linux 8.3 (clone of Redhat) 
```
 curl -fsSL https://repo.saltproject.io/py3/redhat/8/x86_64/3002.repo | tee /etc/yum.repos.d/salt.repo
 yum install salt salt-minion 
 salt-call state.apply sls/ntp
```

**Expected behavior**
```
          ID: chrony
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 08:27:13.258915
    Duration: 925.871 ms
     Changes:
```

**Screenshots**
```
          ID: chrony
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'sls/ntp'
              Reason: 'pkg' __virtual__ returned False: pkg module could not be loaded
     Changes:
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

Master is 3001.7

```
Salt Version:
          Salt: 3002.6

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 15 2020, 11:45:35)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rhel 8.3 Modena
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-240.15.1.el8_3.x86_64
        system: Linux
       version: Springdale Open Enterprise Linux 8.3 Modena
```
</details>

**Additional context**
I added 
```
 Springdale Open Enterprise 
```
to 
```
 /usr/lib/python3.6/site-packages/salt/grains/core.py
```
on the minion to get expected results.
