### ISSUE TITLE
[DOCS] fips_mode is an undocumented opt for minion and master configs

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt#59910]
**Description**

Docs are missing from #59833

**Suggested Fix**

Minimum needed docs are:

- [`conf/minion`](https://github.com/saltstack/salt/blob/master/conf/minion)
- [`conf/master`](https://github.com/saltstack/salt/blob/master/conf/master)
- [`doc/ref/configuration/minion.rst`](https://github.com/saltstack/salt/blob/master/doc/ref/configuration/minion.rst)
- [`doc/ref/configuration/master.rst`](https://github.com/saltstack/salt/blob/master/doc/ref/configuration/master.rst)

`fips_mode`, if present, should probably be documented in the files that newly reference and use it:

- [`salt/modules/nacl.py`](https://github.com/saltstack/salt/blob/master/salt/modules/nacl.py)
- [`salt/modules/x509.py`](https://github.com/saltstack/salt/blob/master/salt/modules/x509.py)
- [`salt/pillar/nacl.py`](https://github.com/saltstack/salt/blob/master/salt/pillar/nacl.py)
- [`salt/runners/nacl.py`](https://github.com/saltstack/salt/blob/master/salt/runners/nacl.py)
- [`salt/states/x509.py`](https://github.com/saltstack/salt/blob/master/salt/states/x509.py)
- [`salt/utils/nacl.py`](https://github.com/saltstack/salt/blob/master/salt/utils/nacl.py)

**Type of documentation**

Salt documentation, Salt modules

**Additional context**

This is a symptom of a larger problem in our documentation and testing suite:
- #59908
- #58112

**Comment by OrangeDog** [comment]
That PR is just the default PR template with all tasks unchecked. If core devs can't be bothered to put in the minimum effort, how can the community be expected to?

And it's a new feature being merged during the "code freeze"?

**Comment by scriptautomate-bc** [comment]
Some example notes on enabling FIPS

Ref: https://github.com/saltstack/salt/issues/66781#issuecomment-2272222285

### On the master

```yml
# master.d/fips.conf
fips_mode: True
publish_signing_algorithm: PKCS1v15-SHA224
```

### On the minions

```yml
# minion.d/fips.conf
fips_mode: True                                          
encryption_algorithm: OAEP-SHA224
signing_algorithm: PKCS1v15-SHA224
```
