### ISSUE TITLE
[BUG] no data returned from saltutil.running during windows minion state run

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#59996]
**Description**
`saltutil.running` returns no data on a Windows minion during a state run (the `proc` dir is empty)

**Setup**
Windows 2019 Server minion
3001 and 3002 minion tested
master/minion environment

**Steps to Reproduce the behavior**
Execute a state that runs for a few minutes.  Observe the `proc` dir on the minion is empty.  Execute the saltutil.running command on the minion, no data is returned.  

Attempts to run another state concurrently are not met with an error about concurrency, they are either executed as if `concurrent=True` were passed or the "IOLoop already running" error is thrown.

**Expected behavior**
Job data is returned by saltutil.running (this functions as expected on 2019.2, I haven't tested 3000)

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001.6

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.3.1
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2019Server
         system: Windows
        version: 2019Server 10.0.17763 SP0
```
</details>

**Additional context**
saltutil.running functions as expected on linux minions of the same versions....
