### ISSUE TITLE
[BUG] watch does not trigger service restart on freebsd , job idles forever 

### ISSUE THREAD

**Issue by network-shark** [saltstack/salt#60001]
**Description**
Service does not restart if there is a change in the config file. 

**Setup**
```
install_influxdb:
  pkg.installed:
    - pkgs:
      - influxdb

enable-influxd:
  service.enabled:
    - name: influxd

start-influxd:
  service.running:
    - name: influxd
    - full_restart: None
    - watch:
      - file: install_influx_config

install_influx_config:
  file.managed:
    - name: /usr/local/etc/influxd.conf
    - source: salt://influxdb/files/influxd.conf
    - user: root
    - group: wheel
    - mode: 0644
```

**Steps to Reproduce the behavior**
I copied the example from https://docs.saltproject.io/en/latest/ref/states/requisites.html 
and made just made slight modifications ( changed the application name )  . 

First run . Deploy application . Runs fine . 
Someone logs into the server modifies the config . 
Run state.apply again. Minion does not return anything. It idles forever.

I found out that the minion is trying to execute service.full_restart , but it seems this is not implemented.

Minion Log:
```
'service.full_restart' is not available.
```
Nevertheless , if the func is not available it should fail , but even waiting for 5 - 10 minutes the job idles forever ? 

**Expected behavior**
If the /usr/local/etc/influxd.conf is not in the correct state . Change should be applied and the service should be reloaded or restarted , both does not work .

**Versions Report**
```
root@tig_stack:/ # salt --versions-report
Salt Version:
          Salt: 3002.6

Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.9 (default, Mar 27 2021, 01:17:51)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 19.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: freebsd 12.2
        locale: UTF-8
       machine: amd64
       release: 12.2-RELEASE-p4
        system: FreeBSD
       version: FreeBSD 12.2
```

I found two bugs which are old and have never been fixed .

https://github.com/saltstack/salt/issues/55098
https://github.com/saltstack/salt/issues/43922

[minion_failed.log](https://github.com/saltstack/salt/files/6289630/minion_failed.log)
