### ISSUE TITLE
askpass parameter missing in roster

### ISSUE THREAD

**Issue by TZanke** [saltstack/salt#60042]
**Is your feature request related to a problem? Please describe.**
We do have Workstations/Servers we can not access with a ssh key. Instead i use salt-ssh with --askpass parameter. But i would like to have a more convenient solution which i do not have to remember: add the askpass parameter to rosters. Right now it is not supported: https://docs.saltproject.io/en/latest/topics/ssh/roster.html#ssh-roster

**Describe the solution you'd like**
```
setting123:
      host: workstation123
      user: user123
      sudo: True
      askpass: True
```

**Describe alternatives you've considered**
--askpass works, but must be remembered by each user
