### ISSUE TITLE
[BUG] State 'pkg.installed' was not found (on AlmaLinux)

### ISSUE THREAD

**Issue by bwdbethke** [saltstack/salt#60040]
**Description**
trying to install and remove some packages via salt on AlmaLinux 8.3 (which is very similar to Centos8)
but get the errors:
```
----------
         ID: common_packages
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'base_packages'
              Reason: 'pkg' __virtual__ returned False
     Changes:
----------
          ID: remove_packages
    Function: pkg.removed
      Result: False
     Comment: State 'pkg.removed' was not found in SLS 'base_packages'
              Reason: 'pkg' __virtual__ returned False
     Changes:
----------
```

**Setup**
```
$ salt-minion --version
salt-minion 3000.3
```

```
$ salt-call --local grains.get os_family
local:
    AlmaLinux
```

```
$ salt-master --version
salt-master 3001.7
```

##### base_packages\init.sls
```
common_packages:
  pkg.installed:
    - pkgs:
      - iftop
      - screen

remove_packages:
  pkg.removed:
    - pkgs: 
      - cups
```

**Steps to Reproduce the behavior**
```
$ sudo salt-call state.apply base_packages

[ERROR   ] State 'pkg.installed' was not found in SLS 'base_packages'
Reason: 'pkg' __virtual__ returned False

[ERROR   ] State 'pkg.removed' was not found in SLS 'base_packages'
Reason: 'pkg' __virtual__ returned False

local:
----------
          ID: common_packages
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'base_packages'
              Reason: 'pkg' __virtual__ returned False
     Changes:
----------
          ID: remove_packages
    Function: pkg.removed
      Result: False
     Comment: State 'pkg.removed' was not found in SLS 'base_packages'
              Reason: 'pkg' __virtual__ returned False
     Changes:
```

**Versions Report**
```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Mar  9 2021, 11:17:25)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: almalinux 8.3 Purple Manul
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-240.el8.x86_64
         system: Linux
        version: AlmaLinux 8.3 Purple Manul
```

**Additional Info**
This issue seems very similar to #57490 which was same prob for a different OS.
