### ISSUE TITLE
[FEATURE REQUEST] - Per state output condition

### ISSUE THREAD

**Issue by jynolen** [saltstack/salt#60069]
**Is your feature request related to a problem? Please describe.**
I would be able to specify per state output configuration in the following example it could be great to hide the changes from 

**Describe the solution you'd like**
It could be really great to have a state related options (just like the require entry) to specify options to hide the content
Something like

```
# No sensitive info : can be output
deployment_user:
  sqlite3.row_present:
    - db: /etc/salt/sdb.db
    - table: sdb
    - where_sql: key='deployment.user'
    - data:
        key: deployment.user
        value: deployment_user
    - require:
      - sqlite3: sdb
    - _output_ : full

# Sensitive info : can be hide
deployment_password:
  sqlite3.row_present:
    - db: /etc/salt/sdb.db
    - table: sdb
    - where_sql: key='deployment.password'
    - data:
        key: deployment.password
        value: {{ deployment_password }}
    - require:
      - sqlite3: sdb
    - _output_ : hide
```

**Additional context**
Here example where per state output condition could be great
```
# No sensitive info : can be output
deployment_user:
  sqlite3.row_present:
    - db: /etc/salt/sdb.db
    - table: sdb
    - where_sql: key='deployment.user'
    - data:
        key: deployment.user
        value: deployment_user
    - require:
      - sqlite3: sdb

# Sensitive info : can be hide
deployment_password:
  sqlite3.row_present:
    - db: /etc/salt/sdb.db
    - table: sdb
    - where_sql: key='deployment.password'
    - data:
        key: deployment.password
        value: {{ deployment_password }}
    - require:
      - sqlite3: sdb
```
