### ISSUE TITLE
[BUG]Error while bringing up minion for multi-master. Is master at responding?

### ISSUE THREAD

**Issue by tiprogn** [saltstack/salt#60077]
**Description**
I've just commissioned a new SuSE Manager server based on 15SP1 and I'm just moving over my minions from my previous salt-master server. Unfortunately after adding the minion I stumble upon this issue. 

**[ERROR   ] Got a bad pillar from master, type str, expecting dict: 
[ERROR   ] Error while bringing up minion for multi-master. Is master at responding?**

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
I've deleted the minion several times by removing the package completely from the minion and deleted /etc/salt in addition to /var/cache/salt

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.12 (default, Nov 25 2020, 20:33:10) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 5.3.18-24.49-default
         system: Linux
        version: Not Installed

```
</details>

**Additional context**
