### ISSUE TITLE
Rocky Linux OS support

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#60118]
**Is your feature request related to a problem? Please describe.**

This is on Rocky 8 RC1.
```
local:
----------
          ID: selinux_related_pkgs
    Function: pkg.installed
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'test.noselinuxfirewalld'
              Reason: 'pkg' __virtual__ returned False: pkg module could not be loaded
     Changes:
----------

```
**Describe the solution you'd like**
Support Rocky Linux as an additional OS. 

**Describe alternatives you've considered**
Unlike Oracle Linux 8, /etc/redhat-release content is showing Rocky Linux. 
```
[me@rocky8t01 ~]$ cat /etc/redhat-release
Rocky Linux release 8.3
[me@rocky8t01 ~]$
```
**Additional context**

[me@rocky8t01 ~]$ salt-minion -V
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr 12 2021, 07:42:28)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 8
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-240.22.1.el8.x86_64
        system: Linux
       version: Rocky Linux 8

[me@rocky8t01 ~]$

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.
