### ISSUE TITLE
[BUG] Can't use `file.manged` with SLS file on Windows minion (version 3003 only)

### ISSUE THREAD

**Issue by rawmind** [saltstack/salt#60139]
**Description**
Can't use `file.manged` with SLS file 

**Setup**

Create SLS ` /srv/salt/test-write.sls `

```
test write:
  file.managed:
    - source: salt://test.write
    - template: jinja
    - name: C:/salt/.test.write
```
and a test jinja template file `/srv/salt/test.write`
```
check {{ salt["system.get_system_date"]() }} {{ salt["system.get_system_time"]() }}
```

**Steps to Reproduce the behavior**

`sudo salt 'aminion' state.apply test-write`

The output:

```
aminion:
----------
          ID: test write
    Function: file.managed
        Name: C:/salt/.test.write
      Result: False
     Comment: Unable to manage file: name 'urllib' is not defined
     Started: 11:01:18.360777
    Duration: 46.837 ms
     Changes:   

Summary for aminion
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  46.837 ms
```

Detailed stacktrace:

```
      File "C:\salt\bin\lib\site-packages\salt-3003-py3.7.egg\salt\states\file.py", line 3077, in managed
        **kwargs
      File "C:\salt\bin\lib\site-packages\salt-3003-py3.7.egg\salt\loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "C:\salt\bin\lib\site-packages\salt-3003-py3.7.egg\salt\loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "C:\salt\bin\lib\site-packages\salt-3003-py3.7.egg\salt\loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "C:\salt\bin\lib\site-packages\salt-3003-py3.7.egg\salt\modules\file.py", line 4524, in get_managed
        urlparsed_source = urllib.parse.urlparse(source)
    NameError: name 'urllib' is not defined 
```

Import for `C:\salt\bin\lib\site-packages\salt-3003-py3.7.egg\salt\states\file.py` is present:

```
28: import urllib.parse
```

`urllib.parse` is accessible
```
$ sudo salt 'aminion' cmd.run "C:\salt\bin\python.exe -c  \"import urllib.parse; print(urllib.parse.urlparse(''))\""
aminion:
    ParseResult(scheme='', netloc='', path='', params='', query='', fragment='')
```

**Expected behavior**
File has been created on a minion.

**Versions Report**
**Master**
```
Salt Version:
           Salt: 3001.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-1024-aws
         system: Linux
        version: Ubuntu 20.04 focal
```

**Minion**

```
aminion
    Salt Version:
              Salt: 3003
     
    Dependency Versions:
              cffi: 1.14.5
          cherrypy: 18.6.0
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.5
         gitpython: Not Installed
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.4
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.20
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
      python-gnupg: 0.4.6
            PyYAML: 5.3.1
             PyZMQ: 18.0.1
             smmap: 3.0.4
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.1
     
    System Versions:
              dist:   
            locale: cp1252
           machine: AMD64
           release: 10
            system: Windows
           version: 10 10.0.19041 SP0
```

**Additional context**

Tested on different versions: [3001, 3001.1, 3002.1, 3002.2, 3002.5, 3002.6], only 3003 is affected. All machines are Windows-based.
