### ISSUE TITLE
[BUG] slack_notify.post_message requires authentication update

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#60160]
**Description**
Slack has reported that for new applications they no longer allow posting the token as a query parameter. This is the only method we currently allow in the [slack_notify module](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.slack_notify.html#module-salt.modules.slack_notify). 

See [this article from Slack](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.slack_notify.html#module-salt.modules.slack_notify). 

Trying to use the Slack notify as a new application will now log errors like the following:
```2021-05-03 12:23:11,705 [salt.state :321 ][ERROR ][3771] Failed to send message (invalid_auth): notify_slack_secretkey_mismatch
```
**Setup**

* Configure your Slack API key in your minion
* Create a new app in Slack.
* Try to run the following state:

```
orch_start_slack_notify:                                                   
  salt.function:                                                           
    - name: slack.post_message                                             
    - tgt: {{ secure_minion }}                                             
    - kwarg:                                                               
        channel: '#{{ slack_channel }}'                                    
        message: ':white_check_mark: Some really important message.'
        from_name: '{{ slack_from }}'                                      
        api_key: {{ slack_api_key }}                                       
        icon: 'https://a-fun-icon.org/someimage.png'   
```

**Expected behavior**
Expected behavior is that the message gets posted to the specified Slack channel.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003
Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: 3.1.14
        Jinja2: 2.10.3
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
Salt Extensions:
        sseape: 6.4.0+3
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-862.11.6.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Additional context**
