### ISSUE TITLE
[Enahancement] No ssh key roll out with fido2

### ISSUE THREAD

**Issue by 53845714nF** [saltstack/salt#60183]
**Description**
When I try to roll out a public SSH key secured with fidio2 it does not work. With a normal key it works.

**Setup**
`init.sls` File: 
```
ssh-key-foobar:
  ssh_auth.present:
    - user: foobar
    - source: salt://linux/sshd/fidio.pub
```
**Steps to Reproduce the behavior**
A `.pub` file with that started with `sk-ssh-ed25519@openssh.com` does not work. I get the following error message.
```
ID: ssh-key-foobar
Function: ssh_auth.present
Result: False
Comment: No keys detected in salt://linux/sshd/fidio.pub. Is file properly formatted?
```
When I use a normal key it works (ssh-ed25519).

**Expected behavior**
The state should be rolled out normally 

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: utf-8
       machine: x86_64
       release: 5.4.106-1-pve
        system: Linux
       version: Debian GNU/Linux 10 buster

```
</details>

**Additional context**
None

**Comment by dmurphy18** [comment]
@53845714nF Not sure if Salt supports fido2, checking but not finding support for it in the code.

**Comment by dmurphy18** [comment]
@53845714nF Currently Salt does not support fido2 from https://fidoalliance.org/fido-authentication.  You could turn this issue into a Feature Request (Label Feature) if desired, or Salt would be more than happy to accept contributions adding fido2.

Please consider closing this issue or turning it into a Feature Request, given that fido2 is currently unsupported in Salt

**Comment by 53845714nF** [comment]
@dmurphy18 
It is not really a Feature request. It is much more a bug in rolling out SSH public keys. As of SSH 8.2+ fidio2 is supported. 
The fidio2 support does not really concern Salt.

**Comment by dmurphy18** [comment]
@53845714nF 
```
As of SSH 8.2+ fidio2 is supported.
```
Can you point me to where there is a statement in Salt Project doc's that states fido2 is supported - it needs correction if it is there.

If the statement is because SSH 8.2+ supports fido2, then there is an issue in the version SSH that Salt is supporting.  Looking for more context, since I have not been following SSH lately, as focused on other UNIX platforms.

**Comment by 53845714nF** [comment]
I expect to be able to distribute my ssh keys no matter what format they have.
And the key is in a valid ssh format. That is the point.

Where in the documentation are the formats that are not supported?

> Could it be the OS doesn't support fido2 on Debian 10 yet ?

The normal Debian repositories still have an old ssh, it has to be installed from the backports.

Here is a simple state that does it:
```
buster-backports:
  pkgrepo.managed:
    - humanname: Buster backports repository
    - name: deb http://deb.debian.org/debian buster-backports main
    - dist: buster-backports
    - file: /etc/apt/sources.list.d/buster-backports.list

ssh:
  pkg.installed:
    - fromrepo: buster-backports
    - version: 1:8.4p1-2~bpo10+1
  ```

But it doesn't really matter. With some operating systems like Arch and Alpine it is already the standard.
