### ISSUE TITLE
[FEATURE REQUEST] Support postgres_privileges for columns

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#60187]
**Is your feature request related to a problem? Please describe.**
Postgres supports column-level permissions. Salt does not.
```
GRANT { { SELECT | INSERT | UPDATE | REFERENCES } ( column_name [, ...] )
    [, ...] | ALL [ PRIVILEGES ] ( column_name [, ...] ) }
    ON [ TABLE ] table_name [, ...]
    TO role_specification [, ...] [ WITH GRANT OPTION ]
```

**Describe the solution you'd like**
For example, this
```yaml
role:
  postgres_privileges.present:
    - object_name: tbl.col
    - object_type: column
    - privileges: [ INSERT, UPDATE ]
```
would generate
```sql
GRANT INSERT "col", UPDATE "col" ON "tbl" TO "role";
```
A way to do multiple columns at once would be nice, but they have to be in the same table.

**Describe alternatives you've considered**
Manually construct the `GRANT` command, but checking for whether it's necessary is difficult. 
Otherwise only using tale-level privileges.
