### ISSUE TITLE
[BUG] Jinja Debug show_full_context()  broken ?

### ISSUE THREAD

**Issue by network-shark** [saltstack/salt#60195]
**Description**
Trying to debug a jinja template via show_full_context() or straight from the documentation:
Context is: {{ show_full_context()|yaml(False) }}

Should return a dictionary with the a lot of values ....

Example.sls

```
#!jinja|yaml
{% set node = 'unbound' %}
always-passes:
  test.succeed_without_changes:
    - name: {{node}}

Context is: {{ show_full_context()|yaml(False) }}
```
Returns:
```
root@raspberrypi:~# salt 'freebsd_vm' state.apply 'jail.test'
jid: 20210515205812944604
freebsd_vm:
    Data failed to compile:
----------
    Rendering SLS 'base:jail.test' failed: mapping values are not allowed in this context
```

On the Minion:
```
╰─ salt-call state.show_sls 'jail.test'
[CRITICAL] Rendering SLS 'base:jail.test' failed: mapping values are not allowed in this context
local:
    - Rendering SLS 'base:jail.test' failed: mapping values are not allowed in this context
```

Master | show_full_context()
```
╰─ salt-call state.apply 'jail.test'
local:
    Data failed to compile:
----------
    State 'Context is' in SLS 'jail.test' is not formed as a list
----------
    State 'Context is' in SLS 'jail.test' is not formed as a list
----------
    State 'Context is' in SLS 'jail.test' is not formed as a list
----------
    State 'Context is' in SLS 'jail.test' is not formed as a list
----------
    State 'Context is' in SLS 'jail.test' is not formed as a list
----------
    State 'Context is' in SLS 'jail.test' is not formed as a list
----------
    State 'Context is' in SLS 'jail.test' is not formed as a list
----------
```

Minion | show_full_context()
```
local:
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
    - State 'Context is' in SLS 'jail.test' is not formed as a list
```

**Versions Report**
```
MASTER:
root@raspberrypi:~# salt --versions-report
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: 0.27.7
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 0.27.4
        Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: aarch64
       release: 5.10.17-v8+
        system: Linux
       version: Debian GNU/Linux 10 buster
```
```

MINION
╰─ salt --versions-report
Salt Version:
          Salt: 3002.6

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.9 (default, Apr 15 2021, 07:51:28)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 22.0.3
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: freebsd 13.0
        locale: utf-8
       machine: amd64
       release: 13.0-RELEASE
        system: FreeBSD
       version: FreeBSD 13.0
```
