### ISSUE TITLE
[ Feature Request ] block.replace should have an option to remove the whole block 

### ISSUE THREAD

**Issue by network-shark** [saltstack/salt#60191]
Hello Devs , 

stalebot closed https://github.com/saltstack/salt/issues/45370

It was never implemented , but I think it would be a good idea . Can we reopen the old one or should we use this one ? 

Feature Req:

file module should have a absent option for a text block which was created via file.blockreplace. 

```
file.blockreplace_absent:
  - name: etc/resolv.conf
  - pattern_start: # START etc_sudoers_{{ system_name }} -DO-NOT-EDIT-
  - pattern_stop:  # STOP etc_sudoers_{{ system_name }} -DO-NOT-EDIT-
  
```
