### ISSUE TITLE
Saltify - Cloud instance already exists whereas it is newly created

### ISSUE THREAD

**Issue by nkrishnakishor** [saltstack/salt#60212]
**Description**
I have an Windows AWS instance and want to saltify it, configured required conf files and tried to run the command it is throwing error failed to start salt on host windows-server-2019.

Both the master and Windows minion are in same region.

**Setup**
Below are the profile and provider files

```
ubuntu@ip-172-31-34-78:/shared-path$ sudo vim /etc/salt/cloud.profiles.d/win-profile.conf
saltify-windows:
  provider: win-saltify
  ssh_host: <minion-public-IP>
  win_installer: /shared-path/Salt-Minion-3003-Py3-AMD64-Setup.exe
  win_username: Administrator
  win_password: 'M9&az@Hw72C2s3K$QYpdye=*%XZ2VBsq'
  use_winrm: True


ubuntu@ip-172-31-34-78:/shared-path$ sudo vim /etc/salt/cloud.providers.d/win-provider.conf
win-saltify:
  minion:
    master: <master-public-IP>
  driver: saltify
```

**Steps to Reproduce the behavior**
ubuntu@ip-172-31-34-78:/shared-path$ sudo salt-cloud -p saltify-windows Windows-Server-2019 -l debug

```
Enclosed debug 
[error-log.txt](https://github.com/saltstack/salt/files/6507211/error-log.txt)
log file
```

**Expected behavior**
Package should have installed on the windows minion.

**Versions Report**
<details><summary>salt --versions-report</summary>
no version difference in master & minion

```
         Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-1045-aws
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>
