### ISSUE TITLE
[BUG] S3 Module / State Configuration Not Aligned

### ISSUE THREAD

**Issue by rawkode** [saltstack/salt#60222]
**Description**

The S3 module expects the s3 configuration to be:

```yaml
s3.key: key
s3.location: eu-west-1
```

Code: https://github.com/saltstack/salt/blob/master/salt/modules/s3.py

However, when using `s3://` as a file source - `s3_opt` uses `['s3']['key']`

https://github.com/saltstack/salt/blob/4f3cb36955d84c6793efcbeabf53963067922d90/salt/fileclient.py#L547

**Setup**

This means that a backup and restore state like this will never work unless the s3 configuration is duplicated.

```yaml
letsencrypt-create-backup:
  cmd.run:
    - name: tar -cvf /tmp/letsencrypt.tar ./letsencrypt
    - cwd: /etc

letsencrypt-upload-backup:
  module.run:
    - name: s3.put
    - bucket: {{ pillar['s3']['bucketName'] }}
    - local_file: /tmp/letsencrypt.tar
    - path: {{ grains.nodename }}/letsencrypt.tar

teleport-s3-sync-down:
  archive.extracted:
    - name: /etc
    - source: s3://{{ pillar['s3']['bucketName'] }}/{{ grains.nodename }}/letsencrypt.tar
    - skip_verify: True
    - user: root
    - group: root
    - if_missing: /etc/letsencrypt
    
```
