### ISSUE TITLE
[BUG]Jinja rendering result is weird

### ISSUE THREAD

**Issue by fangpsh** [saltstack/salt#60235]
**Description**
When rendering the ifcfg file , the mac address is converted to an integer.

**Setup**
default config.

**Steps to Reproduce the behavior**
`ifcfg-device.jinja`:
```
BOOTPROTO=dhcp
DEVICE={{ device }}
HWADDR={{ mac_addr }}
NM_CONTROLLED=no
ONBOOT=yes
PERSISTENT_DHCLIENT=yes
TYPE=Ethernet
USERCTL=no
```

`network.sls`:
```
/tmp/test.conf:
  file.managed:
    - source: salt://ifcfg-device.jinja
    - mode: 0644
    - template: jinja
    - defaults:
        device: eth0
        mac_addr: 52:54:00:42:25:43
```

**Expected behavior**
I hope to get a conf like the following:
```
BOOTPROTO=dhcp
DEVICE=eth0
HWADDR=52:54:00:42:25:43
NM_CONTROLLED=no
ONBOOT=yes
PERSISTENT_DHCLIENT=yes
TYPE=Ethernet
USERCTL=no
```

**Screenshots**
but I got:

`/tmp/test.conf`:
```
BOOTPROTO=dhcp
DEVICE=eth0
HWADDR=41135192743
NM_CONTROLLED=no
ONBOOT=yes
PERSISTENT_DHCLIENT=yes
TYPE=Ethernet
USERCTL=no
```

Interesting, if you change an a-f character to the mac addr, it will be normal, for example 52:54:00:41:25:4f

```
local:
----------
          ID: /tmp/test.conf
    Function: file.managed
      Result: True
     Comment: File /tmp/test.conf updated
     Started: 12:51:54.428423
    Duration: 100.082 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,6 +1,6 @@
                   BOOTPROTO=dhcp
                   DEVICE=eth0
                  -HWADDR=48911189143
                  +HWADDR=62:54:00:41:25:4f
                   NM_CONTROLLED=no
                   ONBOOT=yes
                   PERSISTENT_DHCLIENT=yes

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 100.082 ms
[DEBUG   ] Closing AsyncZero
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-957.21.3.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Comment by lukasraska** [comment]
@fangpsh This is actually how YAML behaves:
```
$ python -c 'import yaml;print(yaml.load("mac_addr: 52:54:00:42:25:43", Loader=yaml.FullLoader))'
{'mac_addr': 41135192743}
```

I assume the exact behaviour would be defined somewhere in YAML language specification.

The safest thing would be wrapping the value in quotes, which I would do for all values that you expect to be string (the same thing would be false vs "false"), like this:
```
/tmp/test.conf:
  file.managed:
    - source: salt://ifcfg-device.jinja
    - mode: 0644
    - template: jinja
    - defaults:
        device: eth0
        mac_addr: "52:54:00:42:25:43"
```
