### ISSUE TITLE
[BUG] lgpo.set always reports pending changes when applying a list of groups to a policy

### ISSUE THREAD

**Issue by dstoliker** [saltstack/salt#60357]
**Description**
When applying a list of entities to apply to a policy, `lgpo.set` reports pending changes when `test=True` is set, whether changes are required or not.

**Setup**
Verify that the policy "Take ownership of files or other objects" is in its default state - only the Administrators group should be returned.

```
salt-call lgpo.get_policy "Take ownership of files or other objects" machine

local:
    - BUILTIN\Administrators
```
**Steps to Reproduce the behavior**

Create a state file to enforce only the `Administrators` group in this policy:
```
set_administrators_take_ownership_of_files_or_other_objects:
  lgpo.set:
    - computer_policy:
        Take ownership of files or other objects:
          - Administrators
    - cumulative_rights_assignments: False
```

When the state is applied with `test=True`, pending changes are reported:
```
local:
----------
          ID: set_administrators_take_ownership_of_files_or_other_objects
    Function: lgpo.set
      Result: None
     Comment: The following policies are set to change:
              Take ownership of files or other objects
     Started: 09:18:03.523000
    Duration: 15.0 ms
     Changes:
```

When run without `test=True`, salt reports that there are no changes to be made.

```
local:
----------
          ID: set_administrators_take_ownership_of_files_or_other_objects
    Function: lgpo.set
      Result: True
     Comment: The following policies are in the correct state:
              Take ownership of files or other objects
     Started: 09:20:03.921000
    Duration: 26830.0 ms
     Changes:
```

Note that if changes are required, Salt does perform the changes correctly.  It just continues to report pending changes whether they are needed or not.

**Expected behavior**
When this state is applied with `test=True`, no pending changes should be reported.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```
</details>

**Additional context**
