### ISSUE TITLE
[FEATURE REQUEST] Add possibility to assign tags for vSphere VMs via salt-cloud

### ISSUE THREAD

**Issue by cathode911** [saltstack/salt#60404]
**Is your feature request related to a problem? Please describe.**
salt-cloud lacks an important ability to add tags to VMs upon their deployment.

**Describe the solution you'd like**
Adding `tags` list to configuration manifest would do the trick

Something like this:
```
me@myserver:/srv/salt/cloud/maps$ cat vm-manifest
ubuntu18044-template:
  - myvm:
      datastore: mydatastore
      num_cpus: 8
      memory: 16GB
      tags:
        - mytag1
        - mytag2
```

**Describe alternatives you've considered**
Alternatives so far is either setting tags later on manually (perfect field for human error) or use another provisioning solution with tag assignment support.

**Additional context**
None

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.
