### ISSUE TITLE
[FEATURE REQUEST] Create a parameter for cli to overwrite git_branch without affecting the pillarenv

### ISSUE THREAD

**Issue by Nerigal** [saltstack/salt#60410]
Create a parameter for cli to overwrite git_branch without affecting the `pillarenv`

```
ext_pillar:
  - git:
    - __env__ https://gitserver/git-pillar.git:
      - root: pillar
      - env: base
```  

`salt 'newinstance02' pillar.items pillarenv=dev`

Base on the above example, the current behavior is that `pillarenv` defined the branch but also overwrite the `env:` value 
or this is at least the exact behavior i have right now with version 3003 for both master and minion 

and in fact it is kind of strange to have to manipulate the `pillarenv` to target a custom branch 

Expected behavior would be like:

To define both but different value :
`salt 'newinstance02' pillar.items pillarenv=dev git_branch=master`

To define different branch without affecting the `pillarenv`:
`salt 'newinstance02' pillar.items  git_branch=master`

This would allow much better flexibility to develop in parallel when having  pillar / states  on a git repo
