### ISSUE TITLE
[BUG] file.directory 'LookupAccountSid' error on Windows

### ISSUE THREAD

**Issue by ovybach** [saltstack/salt#60458]
**Description**
Salt is throwing en exeption when tries to change the owner of the folder using file.directory state.
`salt.exceptions.CommandExecutionError: Error resolving "PySID:S-1-5-21-1958111064-2302302258-2862197922-1010": No mapping between account names and security IDs was done.`
Issue happens when folder's owner is set to SID that doesn't belong to any existing username (account was removed after folder was created by him).

**Steps to Reproduce the behavior**
Execute the following sls file:
```
create_user:
  user.present:
    - name: testuser
    - password: 'MySuper!Str0ngPassw0rd'
    
create_dir:
  file.directory:
    - name: 'C:\ProgramData\test'
    - makedirs: True
    - user: testuser
    - win_owner: testuser

delete_user:
  user.absent:
    - name: testuser
    - purge: True

change_owner:
  file.directory:
    - name: 'C:\ProgramData\test'
    - makedirs: True
    - win_owner: Administrators
```

**Expected behavior**
Last file.directory state (change_owner) should finish successfully without exception. Owner should be changed as stated in sls file.

**Screenshots**
Debug logs from minion - [debug.log](https://github.com/saltstack/salt/files/6732675/debug.log)
Salt output - [bug.txt](https://github.com/saltstack/salt/files/6732676/bug.txt)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.1

Dependency Versions:
          cffi: 1.14.5
      cherrypy: 18.6.0
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.13
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.6
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: msys_nt-10.0-19042 3.1.7
        locale: cp1251
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.19041 SP0
```
</details>
