### ISSUE TITLE
[BUG] salt-syndic memory leak

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#60453]
**Description**
The salt syndic memory keeps growing.

**Setup**

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
Memory dropping down when the service is idle.

**Screenshots**

**Versions Report**
```
always_verify_signature: True
verify_master_pubkey_sign: True
syndic_master:
-       Master1
-       Master2
-       Master3
-       Master4

 

Salt Version:
           Salt: 3000.9

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 14.7.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
System Versions:
           dist: redhat 7.6 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1160.15.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo</summary>
```
