### ISSUE TITLE
[BUG] mount.fstab_present does not mount the filesystem

### ISSUE THREAD

**Issue by cmonty14** [saltstack/salt#60464]
**Description**
I want to mount a filesystem using a related entry in /etc/fstab.
However, the filesystem is not mounted although the entry in /etc/fstab is created correctly.
This issue is related to #57560, but the PR #57669 seems not working.

**Setup**
```
umount_mnt-backup_lve_db:
  service.dead:
    - name: mnt-backup_lve_db.automount
  mount.unmounted:
    - name: /mnt/backup_lve_db

/mnt/backup_lve_db/DO_NOT_DELETE_THIS_DIRECTORY:
  file.managed:
    -   source: salt://manager_org_1/stc-lve-automnt-backupdb/mnt/backup_lve_db/DO_NOT_DELETE_THIS_DIRECTORY
    -   makedirs: True
    -   user: root
    -   group: root
    -   mode: 644

{% set device = salt['cmd.run']('blkid -o device -t LABEL=backup-db') %}

/mnt/backup_lve_db:
  file.directory:
    - name: /mnt/backup_lve_db
    - user: root
    - group: root
    - mode: 755
  mount.fstab_present:
    - name: {{ device }}
    - fs_file: /mnt/backup_lve_db
    - fs_vfstype: xfs
    - fs_mntops:
      - noauto
      - x-systemd.automount
    - mount_by: uuid
    - mount: True
```

**Steps to Reproduce the behavior**
Run the state with an empty, but formatted disk.
The output is reporting no error:
```
salt 'vlcdbts4.devsys.net.sap' state.apply manager_org_1.stc-lve-automnt-backupdb
vlcdbts4.devsys.net.sap:
----------
          ID: umount_mnt-backup_lve_db
    Function: service.dead
        Name: mnt-backup_lve_db.automount
      Result: True
     Comment: The service mnt-backup_lve_db.automount is already dead
     Started: 10:07:55.812412
    Duration: 353.253 ms
     Changes:
----------
          ID: umount_mnt-backup_lve_db
    Function: mount.unmounted
        Name: /mnt/backup_lve_db
      Result: True
     Comment: Target was already unmounted
     Started: 10:07:56.167519
    Duration: 33.91 ms
     Changes:
----------
          ID: /mnt/backup_lve_db/DO_NOT_DELETE_THIS_DIRECTORY
    Function: file.managed
      Result: True
     Comment: File /mnt/backup_lve_db/DO_NOT_DELETE_THIS_DIRECTORY is in the correct state
     Started: 10:07:56.204708
    Duration: 19.565 ms
     Changes:
----------
          ID: /mnt/backup_lve_db
    Function: file.directory
      Result: True
     Comment: The directory /mnt/backup_lve_db is in the correct state
     Started: 10:07:56.224422
    Duration: 1.125 ms
     Changes:
----------
          ID: /mnt/backup_lve_db
    Function: mount.fstab_present
        Name: /dev/sdc
      Result: True
     Comment: /mnt/backup_lve_db entry added in /etc/fstab.
     Started: 10:07:56.225681
    Duration: 10.242 ms
     Changes:
              ----------
              persist:
                  new

Summary for vlcdbts4.devsys.net.sap
------------
Succeeded: 5 (changed=1)
Failed:    0
------------
Total states run:     5
Total run time: 418.095 ms

```
But the device is not mounted.
See attached screenshot for details.
![2021-06-30_10-23-41](https://user-images.githubusercontent.com/12523591/123928159-e88b6e00-d98d-11eb-8473-7805d188a2ad.png)

**Expected behavior**
If the state runs successfully, the device must be mounted.

**Versions Report**
Both (minion and master) uses the same OS and Salt version.
<details><summary>salt --versions-report</summary>
```
vlcspsumasrv:~ # salt --versions-report
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.28.4
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: 3.9.0
  pycryptodome: Not Installed
        pygit2: 0.28.2
        Python: 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: sles 15.2 n/a
        locale: UTF-8
       machine: x86_64
       release: 5.3.18-24.67-default
        system: Linux
       version: SLES 15.2 n/a

```
