### ISSUE TITLE
Orchestration failed without reporting errors [BUG]

### ISSUE THREAD

**Issue by Pietro737** [saltstack/salt#60466]
Hi,
we have a small orchestration which performs the following steps (among two others managing just e-mails sending):
```
Reset group full-stock-integrator to latest:
  salt.state:
    - sls: rin-salt-orchestrator.orchestrator.kafka_streams.offset_input_topic
    - pillar:
        to: --to-latest
        group: {{ group }}
        topic: {{ topic }}
    - tgt: '{{ cpHost }}'
    - tgt_type: 'list'
    - parallel: True
    - concurrent: True
    - require:
      - salt: Send start mail

{{ send_finish_message('rina-002', 'salt', 'Reset group full-stock-integrator to latest', exec_timestamp) }}

Reset group full-stock-integrator recovery to latest:
  salt.state:
    - sls: rin-salt-orchestrator.orchestrator.kafka_streams.offset_input_topic
    - pillar:
        to: --to-latest
        group: {{ group_recovery }}
        topic: {{ topic }}
    - tgt: '{{ cpHost }}'
    - tgt_type: 'list'
    - parallel: True
    - concurrent: True
    - require:
      - salt: Reset group full-stock-integrator to latest

{{ send_finish_message('rina-003', 'salt', 'Reset group full-stock-integrator recovery to latest', exec_timestamp) }}

Execute full-stock-producer:
  salt.state:
    - sls: rin-salt-orchestrator.orchestrator.kafka_streams.aligner_full_stock_producer
    - tgt: '{{ target_full_producer }}'
    - tgt_type: 'list'
    - parallel: True
    - concurrent: True
    - timeout: 36000
    - require:
      - salt: Reset group full-stock-integrator recovery to latest

{{ send_finish_message('rina-004', 'salt', 'Execute full-stock-producer', exec_timestamp) }}
```
The lines in the code similar to the following one take care of writing a log line to a dedicated file:
```
{{ send_finish_message('rina-004', 'salt', 'Execute full-stock-producer', exec_timestamp) }}
```

The EVENTS logs report that both step 2 and step 3 have been executed correctly, but the log message of step 3 is not written to the dedicated log file and step 4 does not start.
Can you help us?

In addition, for the sake of clarity, send_finish_message is a macro defined by us (on line 36 of the file it is imported {% from 'rin-salt-orchestrator/utils/commons/finish_message.sls' import send_finish_message with context %}) and its definition is as follows:
```
{% macro send_finish_message(step_id, func_name, func_id, exec_timestamp) %}
Step {{ step_id }} is finished:
  cmd.run:
    - name: 'echo $(date +"%Y-%m-%d %H:%M:%S,%3N") - {{ step_id }} - Step {{ func_id }} on minion {{ grains['host'] }} is finished correctly >> /var/log/salt/orchestrator_{{ exec_timestamp }}.log'
    - parallel: True
    - require:
      - {{ func_name }}: {{ func_id }}
{% endmacro %}
```
**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3002
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.9.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```
</details>
