### ISSUE TITLE
[BUG] salt.state.file.managed handles ignores parameter skip_verify when parameter source is a list

### ISSUE THREAD

**Issue by olafurj** [saltstack/salt#60472]
**Description**

salt.state.file.managed handles ignores parameter skip_verify when parameter source is a list 

**Setup**
test.sls
```
/tmp/file:
  file.managed:
    - source:
      - https://example.com/somefile
    - skip_verify: True
    - replace: True
    - keep_source: False
    - makedirs: True
```

**Steps to Reproduce the behavior**
salt '*' state.apply test

**Expected behavior**
Download the file from https://example.com/somefile without verifing hash (no HTTP HEAD request) and store as /tmp/file on the minions

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.6
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: 1.1.0
      M2Crypto: 0.36.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: 3.10.1
  pycryptodome: Not Installed
        pygit2: 1.4.0
        Python: 3.8.10 (default, Jun 14 2021, 10:46:13)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: openbsd 6.9 
        locale: utf-8
       machine: amd64
       release: 6.9
        system: OpenBSD
       version: OpenBSD 6.9 

```
</details>

Same thing works correctly if source is changed to a single string

```
/tmp/file:
  file.managed:
    - source: https://example.com/somefile
    - skip_verify: True
    - replace: True
    - keep_source: False
    - makedirs: True
```
