### ISSUE TITLE
[FEATURE REQUEST] Allow host.absent to delete all hostnames associated with an IP address

### ISSUE THREAD

**Issue by dkacar-oradian** [saltstack/salt#60495]
**Is your feature request related to a problem? Please describe.**
It would be nice if `host.absent` state could delete all entries associated with a given IP address. I need to remove `::1` from `/etc/hosts` because I'm disabling IPv6 completely. `/etc/hosts` entry is generated by the OS installer and I can't know which hostnames will be there.
 
**Describe the solution you'd like**
Something like this should do the trick:
```
remove_ipv6_loopback:
  host.absent:
    - name: null
    - ip: ::1
```

**Describe alternatives you've considered**
This works, but it's ugly:
```
{% set ipv6 = salt.hosts.get_alias('::1') %}
{% if ipv6|length > 0 %}

mktemplate_ipv6_loopback_prepare_removal:
  host.only:
    - name: ::1
    - hostnames: localhost

mktemplate_remove_ipv6_loopback:
  host.absent:
    - name: localhost
    - ip: ::1
    - require:
      - mktemplate_ipv6_loopback_prepare_removal

{% endif %}
```

**Additional context**

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by piterpunk** [comment]
Try this:
```
remove:
  host.only:
    - name: ::1
    - hostnames: []
```
