### ISSUE TITLE
[BUG] manufacturer grain is misspelled for Solaris minions on SPARC

### ISSUE THREAD

**Issue by lukasraska** [saltstack/salt#60511]
**Description**
Existing `manufacturer` grain is misspelled for Solaris minions on SPARC and is set as `manufacture` instead.

**Setup**
Solaris minions on SPARC

**Steps to Reproduce the behavior**
```
[root@master ~]# salt -L solaris-sparc-minion grains.get manufacturer --out=json
{
    "solaris-sparc-minion": ""
}
[root@master ~]# salt -L solaris-sparc-minion grains.get manufacture --out=json
{
    "solaris-sparc-minion": "Oracle Corporation"
}
```

**Expected behavior**
`manufacturer` grain to be populated

**Versions Report**
```
    Salt Version:
               Salt: 3000.1
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: 3.1.2
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
           M2Crypto: 0.21.1
               Mako: 0.4.1
       msgpack-pure: Not Installed
     msgpack-python: 0.6.2
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.9 (default, Jun 23 2016, 08:10:06) [C]
       python-gnupg: 0.4.1
             PyYAML: 3.09
              PyZMQ: 16.0.2
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.3.1
     
    System Versions:
               dist:   
             locale: UTF-8
            machine: sun4v
            release: 5.11
             system: SunOS
            version: Not Installed
```
</details>

**Additional context**
https://github.com/saltstack/salt/blob/v3003.1/salt/grains/core.py#L2933
