### ISSUE TITLE
[BUG] eauth limiting runner module by kwargs does not work

### ISSUE THREAD

**Issue by clallen** [saltstack/salt#60549]
**Description**
I am trying to limit runner module args in the eauth conf, but it still allows anything to be passed in and runs the module as normal.

**Setup**
/etc/salt/master.d/eauth.conf
```
external_auth:
  pam:
    username:
      - '@runner':
        - 'test.arg':
          'kwarg1': 'kval1'
          'kwarg2': 'kval2'
```

**Steps to Reproduce the behavior**
I am trying to get this to work with **state.orch**, but to make things simple I have been testing with the **test.arg** module.
I am using curl and a JSON input file.

curl command
```
curl -Skis https://master:8000/run -H 'Content-type: application/json' -H 'Accept: application/x-yaml' -d "`cat input.json`"
```
input.json
```
[
  {
    "client": "runner",
    "fun": "test.arg",
    "blah": "blah",
    "bloo": "bloo",
    "token": "(eauth token generated on master using auth.mk_token)"
  }
]
```
Return output
```
HTTP/1.1 200 OK
Content-Type: application/x-yaml
Server: CherryPy/18.6.0
Date: Wed, 14 Jul 2021 19:49:50 GMT
Allow: GET, HEAD, POST
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: GET, POST
Access-Control-Allow-Credentials: true
Vary: Accept-Encoding
Content-Length: 59

return:
- args: []
  kwargs:
    blah: blah
    bloo: bloo
```

**Expected behavior**
The API call should fail with "401 Unauthorized".

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: 18.6.0
       dateutil: 2.8.1
      docker-py: 5.0.0
          gitdb: 4.0.7
      gitpython: 3.1.14
         Jinja2: 2.11.3
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.10.1
         pygit2: Not Installed
         Python: 3.6.8 (default, Mar  9 2021, 15:08:44)
   python-gnupg: 0.4.7
         PyYAML: 5.4.1
          PyZMQ: 22.0.3
          smmap: 4.0.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.4

System Versions:
           dist: oracle 7.9 n/a
         locale: UTF-8
        machine: x86_64
        release: 4.14.35-2047.503.1.el7uek.x86_64
         system: Linux
        version: Oracle Linux Server 7.9 n/a
```
</details>

**Additional context**
Each time I have made a change to the eauth.conf file I have restarted both the salt-master and salt-api services, and regenerated the eauth token.

I have tried passing just one kwarg, and none at all, and the API call always works.
