### ISSUE TITLE
[DOCS] External Authentication System documentation incorrect example for runner module args

### ISSUE THREAD

**Issue by clallen** [saltstack/salt#60548]
**Description**
The External Authentication System documentation on limiting by function arguments gives an incorrect example for specifying runner module args:
```
external_auth:
  pam:
      - '@runner':
        - 'runner_mod.*':
            args:
            - 'a.*'
            - 'b.*'
            kwargs:
              'kwa': 'kwa.*'
              'kwb': 'kwb'
```
This is also contradicted by the [rest_cherrypy](https://docs.saltproject.io/en/3001/ref/netapi/all/salt.netapi.rest_cherrypy.html#usage) documentation which states: 
> LocalClient also takes arg (array) and kwarg (dictionary) arguments because these values are sent to the Minions and used to execute the requested function there. RunnerClient and WheelClient are executed directly on the Master and thus do not need or accept those arguments.
> "Runners do not support positional args"

**Suggested Fix**
I have tested this extensively and found that this config will work:
```
external_auth:
  pam:
    - '@runner':
      - 'runner_mod.*':
          'kwa': 'kwa.*'
          'kwb': 'kwb'
```

**Type of documentation**
Salt documentation

**Location or format of documentation**
https://docs.saltproject.io/en/3001/topics/eauth/index.html#limiting-by-function-arguments
