### ISSUE TITLE
Changing existing virtual network from NAT to bridge generates invalid libvirt XML

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#60667]
### Description of Issue

Ensure there is a `default` with a NAT forward mode on the minion

Apply the following state to the minion:

```yaml
network_running:
  virt.network_running:
    - name: default
    - forward: bridge
    - bridge: br0
    - autostart: True
    - bridge: br0
```

The state fails with the following comment from libvirt:

```
unsupported configuration: Unsupported <mac> element in network default with forward mode='bridge'
```

The state should apply cleanly.
