### ISSUE TITLE
[BUG] salt-cloud delete cannot find instnace in different AWS account

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#60734]
**Description**
I created an instance in a different AWS account than my salt master using `salt-cloud -p aws-vp-docker-host dockertest`. When I try to delete that minion via `salt-cloud -d dockertest` it fails to find the minion with following output: `No machines were found to be destroyed`

**Setup**
aws-vp-ec2 provider (the salt master instance is in a different aws account than the role_arn)
```
aws-vp-ec2:
  driver: ec2

  ssh_interface: private_ips

  ebs_optimized: True

  # AWS access keys
  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'
  role_arn: 'arn:aws:iam::xxxxxxxxxx:role/salt'

  # ssh config
  ssh_username: ubuntu
  private_key: /rootkey  
  keyname: devops

  # minion config
  minion:
    master: 172.30.0.153

  del_root_vol_on_destroy: True
  rename_on_destroy: True

  startup_states: highstate
```

profile being used:
```
aws-vp-docker-host:
  provider: aws-vp-ec2

  size: c5.2xlarge

  # ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20210720
  image: ami-06cdbd80022d89537

  subnetname: XXXXXXX

  block_device_mappings:
    # root device
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 250
      Ebs.VolumeType: gp2

  minion:
    grains:
      roles:
        - docker

```

**Steps to Reproduce the behavior**
1. Have salt master in account AWS account nnnnnnnnnn
2. Setup provider with role_arn pointing to another AWS account xxxxxxxxxx
3. Provision a minion in salt-cloud with the provider
4. Try to delete the minion with `salt-cloud -d`

**Expected behavior**
The minion is found and deleted properly.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5

System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-1054-aws
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```
</details>

**Additional context**
I also tried to specify the profile of the original salt-cloud call with `salt-cloud -p aws-vp-docker-host -d dockertest` and that did not work because I believe most other flags are ignored when `-d` is specified.

I also have the salt-cloud grains enabled and it has this in the minion:
```
$ salt dockertest grains.get salt-cloud
dockertest:
    ----------
    driver:
        ec2
    profile:
        aws-vp-docker-host
    provider:
        aws-vp-ec2:ec2
```
