### ISSUE TITLE
[BUG] states.ssh_auth.present behavior is incorrect when using both ssh source files and options 

### ISSUE THREAD

**Issue by mguegan** [saltstack/salt#60769]
**Description**
When providing both `options` and `source` on `ssh_auth.present` state, SaltStack fails to identify the existing keys when doing a test (with `test=True`) but seems to work OK without test (in that case, it will says the keys are existing and do nothing).

**Setup**
Example of SLS configuration:

```
my ssh key:
  ssh_auth.present:
    - user: root
    - options:
      - no-pty
    - source: salt://path/to/ssh.id_rsa.pub
```

Content of the `ssh.id_rsa.pub`:
```
ssh-rsa AAAA[...]== comment
```

Tested on:
- [X] VM running on Exoscale (cloud provider), OpenBSD 6.9 image
  
**Steps to Reproduce the behavior**
* `salt-call state.apply test=True` on a relevant minion
```
----------                                                                                                 
          ID: my ssh key                                                                                      
    Function: ssh_auth.present                                                                             
      Result: None                                                                                         
     Comment: Set to update: AAAA[content skipped]==    
     Started: 12:23:13.734345                        
    Duration: 14.351 ms                                                                                    
     Changes:
----------
```
* On the same minion, without the test:
`salt-call state.apply`
```
----------                                                                                                 
          ID: my ssh key                                
    Function: ssh_auth.present                                                                             
      Result: True                                   
     Comment: The authorized host key my ssh key is already present for user root                             
     Started: 12:25:12.239015                        
    Duration: 21.57 ms
     Changes:
----------                                                                                                 
```

**Expected behavior**
The test should indicates that nothing is to be updated.
* `salt-call state.apply test=True`
```
----------
          ID: my ssh key
    Function: ssh_auth.present
      Result: True
     Comment: The authorized host key my ssh key is already present for user root
     Started: 12:08:00.217767
    Duration: 23.982 ms
     Changes:   
----------
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3002.6
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: Not Installed
      M2Crypto: 0.36.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 3.10.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.8.8 (default, Apr 19 2021, 10:23:47)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: openbsd 6.9 
        locale: utf-8
       machine: amd64
       release: 6.9
        system: OpenBSD
       version: OpenBSD 6.9 
```
</details>
