### ISSUE TITLE
[BUG] win_timezone.get_zone returns Unknown for timezones that begin/end with _/d/s/t/o/f

### ISSUE THREAD

**Issue by lukasraska** [saltstack/salt#60829]
**Description**
#59341 which was merged to fix part of #58379 introduced regression that results in timezone being reported as "Unknown" when the timezone starts or ends with one of following characters - `_`,`d`,`s`,`t`,`o`,`f`.

This happens because `str.strip` function (used in https://github.com/saltstack/salt/blob/v3003/salt/modules/win_timezone.py#L221)  uses the argument passed as list of characters (https://docs.python.org/3/library/stdtypes.html#str.strip), not as a exact string that should be stripped.

This then results in timezones being incorrectly named and not found in `TzMapper`:
```
>>> res = {"stdout": "FLE Standard Time"}
>>> res["stdout"].lower().strip("_dstoff")
'le standard time'
```

**Setup**
Clean Salt installation on Windows.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Install Salt on Windows machine, configure OS to be in `FLE Standard Time` timezone.

**Expected behavior**
`win_timezone.get_zone` should return `Europe/Kiev`, instead it returns `Unknown`

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: 18.6.0
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist:   
        locale: cp1252
       machine: AMD64
       release: 2016Server
        system: Windows
       version: 2016Server 10.0.14393 SP0
```
</details>

**Additional context**
FYI @twangboy
