### ISSUE TITLE
Apache state should have authorization containers capability

### ISSUE THREAD

**Issue by tuaris** [saltstack/salt#60878]
**Is your feature request related to a problem? Please describe.**

Yes, it appears that the Apache salt state does not support authorization containers.  Or I am unable to find documentation on the subject.

**Describe the solution you'd like**

Apache 2.4 configuration has the ability to specify multiple "Require" directives by wrapping then in an [Authorization Container](https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html).  For example:

```
<RequireAll>
  Require valid-user
  Require ip 10.0.0.0/16
</RequireAll>
```

Attempting to do the following results in an error.

```
          Proxy:
            this: "*"
            RequireAll:
              Require:
                - valid-user
                - ip 10.0.0.0/16
```

The error printed is:

```
salt.exceptions.SaltException: Apache section container "<RequireAll>" expects attribute. Specify it using key "this".
```

If I try to use a "this" as requested (with an empty string), it also fails

```
          Proxy:
            this: "*"
            RequireAll:
              this: ""
                Require:
                  - ip valid-user
                  - ip 10.0.0.0/16
```

```
    Data failed to compile:
----------
    Rendering SLS 'base:webserver.apache' failed: while parsing a block mapping
  in "<unicode string>", line 27, column 15
did not find expected key
  in "<unicode string>", line 28, column 17
```

**Describe alternatives you've considered**
I am unable to find an alternative besides just using a managed file instead of the Apache state.

**Comment by waynew** [comment]
This is just a mistake in indentation.

Consider:

```
          Proxy:
            # removed this:  line
            RequireAll:
              Require:
                - valid-user
                - ip 10.0.0.0/16 
```                

The error message is that `<Proxy>` needs this. It's added indented under Proxy *with no other changes*.

Now we're back

```
          Proxy:
            this: "*"
            RequireAll:
              Require:
                - valid-user
                - ip 10.0.0.0/16
```

And the message? RequireAll needs attribute, using `this`. So add it without changing any other indentation:

```
          Proxy:
            this: "*"
            RequireAll:
              this: ''
              Require:
                - valid-user
                - ip 10.0.0.0/16
```

HTH!
