### ISSUE TITLE
[BUG] `iptables.append` state does not pass `name` argument to iptables command

### ISSUE THREAD

**Issue by jbartak** [saltstack/salt#60880]
**Description**
The `iptables.append` state does not pass `-name: SSH` to iptables as `--name SSH`, instead of that `--name DEFAULT` is passed. Looks like the `name` argument is reserved by the state itself. Any other argument like `- foo: bar` is passed as `--foo bar`.

**Setup**
`test.sls`:
```
test iptables state:
  iptables.append:
    - table: filter
    - chain: INPUT
    - name: SSH
    - match:
      - comment
      - state
      - recent
      - tcp
    - comment: "test iptables state"
    - connstate: NEW
    - proto: tcp
    - dport: 22
    - save: True
```

Set-up details:

- [x] VM (Virtualbox, Vagrant, CentOS7)

  
**Steps to Reproduce the behavior**
Execute state above. `sudo salt-call state.apply test`

**Expected behavior**
Define iptables `--name` argument in the `iptables.append` state and pass it to the iptables rule.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
[vagrant@salt ~]$ sudo salt-call --version
salt-call 3003.2
[vagrant@salt ~]$ sudo salt --version
salt 3003.2
```
</details>

**Comment by lukasraska** [comment]
@jbartak Looks like it should be `name_` (https://github.com/saltstack/salt/blob/master/salt/modules/iptables.py#L320 ), although it's not documented anywhere. But it seems to work fine:

```
test iptables state:
  iptables.append:
    - table: filter
    - chain: INPUT
    - name_: SSH
    - match:
      - comment
      - state
      - recent
      - tcp
    - comment: "test iptables state"
    - connstate: NEW
    - proto: tcp
    - dport: 22
    - save: True

```

```
local:
----------
          ID: test iptables state
    Function: iptables.append
      Result: False
     Comment: Failed to set iptables rule for test iptables state.
              Attempted rule was /usr/sbin/iptables --wait -t filter -A INPUT  -p tcp -m comment -m state -m recent --name SSH -m tcp --state NEW --dport 22 --comment "test iptables state" for ipv4
     Started: 10:49:37.566532
    Duration: 49.47 ms
     Changes:   
```
