### ISSUE TITLE
[BUG] Issue when using http.query with requests backend

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#60882]
**Description**
When using http.query with the requests backend to register with ServiceNow I get the following error:

```
Comment: An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/salt/state.py", line 1933, in call
**cdata['kwargs'])
File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1951, in wrapper
return f(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/salt/states/http.py", line 93, in query
data = __salt__['http.query'](name, **kwargs)
File "/usr/lib/python3.6/site-packages/salt/modules/http.py", line 41, in query
return salt.utils.http.query(url=url, opts=opts, **kwargs)
File "/usr/lib/python3.6/site-packages/salt/utils/http.py", line 637, in query
tof.write(result_text)
TypeError: write() argument must be str, not bytes
```

**Setup**
You can use the following sample state to reproduce this error in 3003.1 to reproduce the error. I am including a sample of return data from the endpoint.

```
some-service-register-http-query:                                          
  http.query:                                                              
    - name: {{ some.proxy }}{{ some.ops.registration.endpoint }}           
    - username: '{{ some.some_user }}'                                     
    - password: '{{ some.some_pass }}'                                     
    - header_render: True                                                  
    - verify_ssl: False                                                    
    - backend: requests                                                    
    - text_out: {{ some.tmpdir }}/registration_response.json               
    - method: {{ some.ops.registration.http_method }}                      
    - status: {{ some.ops.registration.http_response }}                    
    - data_file: {{ some.tmpdir }}{{ some.ops.registration.template }}  
    - header_file: {{ some.tmpdir }}sn.header   
```

Sample return data

```
{"import_set":"ISET0000000","staging_table":"some_cloud_table","result":[{"transform_map":"A Cloud","table":"cmdb_ci_server","status":"error","error_message":"API Message Rejected; Target record not found","InvalidValues":"","MissingMandatoryValues":"u_start_date,u_install_date","Status":"Reject"}]}
```

**Steps to Reproduce the behavior**
Run the state provided above to reproduce the error.

**Expected behavior**
I believe that the utils.http module should handle the  bytes conversion before returning in order to avoid this error.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: 1.1.0
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: 1.6.1
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
Salt Extensions:
        sseape: 8.4.2+4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 5.13.13-200.fc34.x86_64
        system: Linux
       version: CentOS Linux 7 Core```
</details>

**Additional context**
Add any other context about the problem here.
