### ISSUE TITLE
[BUG] status.netdev is no longer working on AIX

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#60909]
**Description**
The execution module command is no longer working in Python 3 versions of AIX salt-minion, getting dict handling errors

**Setup**
Run the command
```
salt <minion> status.netdev
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
```
root@p1243-pvm2:/home/cecuser/test_3003.3/salt_3003.3$ salt-call --local status.netdev 

Passed invalid arguments: unsupported operand type(s) for +: 'dict_keys' and 'dict_keys'.

Usage:

    .. versionchanged:: 2016.3.2
        Return the network device stats for this minion

    .. versionchanged:: 2016.11.4
        Added support for AIX

    CLI Example:

    .. code-block:: bash

        salt '*' status.netdev
```
    

**Expected behavior**
Should return information on netdev

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
```
root@p1243-pvm2:/home/cecuser/test_3003.3/salt_3003.3$ salt-call --local test.versions
local:
    Salt Version:
              Salt: 3003.3
     
    Dependency Versions:
              cffi: 1.14.4
          cherrypy: 17.4.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.3
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.17
          pycrypto: 3.10.1
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.7.10 (default, Jun  1 2021, 05:23:20)
      python-gnupg: 0.4.4
            PyYAML: 5.4.1
             PyZMQ: 18.1.1
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: aix 1 
            locale: ISO8859-1
           machine: 00F9C4904C00
           release: 1
            system: AIX
           version: AIX 1 
```
</details>

**Additional context**
This worked in 2016.11.x versions.
root@p1243-pvm2:/home/cecuser/test_2016.11/salt_2016.11.3$ salt-call --local status.netdev
[WARNING ] The tools 'dmidecode' and 'lspci' failed to execute because they do not exist on the system of the user running this instance or the user does not have the necessary permissions to execute them. Grains output might not be accurate.
local:
    This method is unsupported on the current operating system!

Need to find 2016.11.4 to test with
