### ISSUE TITLE
[BUG] `pkgrepo.managed` always trigger changes if url ends with `/`

### ISSUE THREAD

**Issue by marek-obuchowicz** [saltstack/salt#60907]
**Description**
After migrating to py3, I see that salt always wants to update package repos, if their definition contains templated values. Repositories are already setup.

**Setup**

Master/minion running salt 3003.3, Debian 9 VMs in AWS
- [x] VM running on a cloud service, please be explicit and add details
  
**Steps to Reproduce the behavior**
```
php1-repo:
  pkgrepo.managed:
    - humanname: PHP7.1 repository
    - name: deb https://packages.sury.org/php/ {{ grains.lsb_distrib_codename }} main
    - file: /etc/apt/sources.list.d/php1.list
    - key_url: https://packages.sury.org/php/apt.gpg
    - refresh: False

php2-repo:
  pkgrepo.managed:
    - humanname: PHP7.1 repository
    - name: deb https://packages.sury.org/php/ stretch mainXXX # make it unique for this example
    - file: /etc/apt/sources.list.d/php2.list
    - key_url: https://packages.sury.org/php/apt.gpg
    - refresh: False
```

then run `state.apply` twice

**Expected behavior**
First run should add two package repositories. Second run should not detect any changes.

**Screenshots**
After applying state once, second (and each next) run still wants to change php1 repo:
```
local:
  Name: deb https://packages.sury.org/php/ stretch main - Function: pkgrepo.managed - Result: Differs Started: - 14:06:36.967772 Duration: 69.358 ms
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.5.3
     docker-py: Not Installed
         gitdb: 2.0.0
     gitpython: 2.1.1
        Jinja2: 2.9.4
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.5.3 (default, Apr  5 2021, 09:00:41)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.1
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.1

System Versions:
          dist: debian 9 stretch
        locale: UTF-8
       machine: x86_64
       release: 4.9.0-16-amd64
        system: Linux
       version: Debian GNU/Linux 9 stretch

```
</details>
