### ISSUE TITLE
[BUG] AIX support for devinfo.hwinfo is needed

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#60910]
**Description**
Execution module devinfo.hwinfo is needed, currently not working.
Probably needs to recognize platform is AIX and call appropriate utiltiy to return hardware info, similar to that returned in grains.items

**Setup**
salt <minion> devinfo.hwinfo

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
```
root@p1243-pvm2:/home/cecuser/test_3003.3/salt_3003.3$ salt-call --local devinfo.hwinfo
Error running 'devinfo.hwinfo': Unable to run command '['hwinfo', '--bios', '--cpu', '--disk', '--memory', '--network', '--partition', '--short']' with the context '{'cwd': '/', 'shell': False, 'env': {'RES_TIMEOUT': '2', 'SHELL': '/usr/bin/ksh', 'SUDO_GID': '205', 'LC__FASTMSG': 'true', 'ODMDIR': '/etc/objrepos', 'CLCMD_PASSTHRU': '1', 'SUDO_COMMAND': '/usr/bin/su', 'SUDO_USER': 'cecuser', 'PWD': '/home/cecuser/test_3003.3/salt_3003.3', 'LOGNAME': 'root', '_': '/usr/bin/salt-call', 'TZ': 'EST5EDT', 'HOME': '/', 'LANG': 'en_US', 'NSORDER': 'local,bind', 'RES_RETRY': '2', 'TERM': 'xterm', 'USER': 'root', 'LOGIN': 'root', 'SHLVL': '1', 'LOCPATH': '/usr/lib/nls/loc', 'PATH': '/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/usr/java8_64/jre/bin:/usr/java8_64/bin', 'SUDO_UID': '205', 'MAIL': '/var/spool/mail/root', 'OLDPWD': '/home/cecuser/test_3002.1/salt_3002.1', 'NLSPATH': '/usr/lib/nls/msg/%L/%N:/usr/lib/nls/msg/%L/%N.cat:/usr/lib/nls/msg/%l.%c/%N:/usr/lib/nls/msg/%l.%c/%N.cat', 'LIBPATH': '/opt/saltstack/salt/run', 'SSL_CERT_FILE': '/opt/saltstack/salt/run/certifi/cacert.pem', 'LC_CTYPE': 'C', 'LC_NUMERIC': 'C', 'LC_TIME': 'C', 'LC_COLLATE': 'C', 'LC_MONETARY': 'C', 'LC_MESSAGES': 'C', 'LC_PAPER': 'C', 'LC_NAME': 'C', 'LC_ADDRESS': 'C', 'LC_TELEPHONE': 'C', 'LC_MEASUREMENT': 'C', 'LC_IDENTIFICATION': 'C', 'LANGUAGE': 'C'}, 'stdin': None, 'stdout': -1, 'stderr': -1, 'with_communicate': True, 'timeout': None, 'bg': False, 'close_fds': True}', reason: [Errno 2] No such file or directory: 'hwinfo': 'hwinfo'
```

**Expected behavior**
Hardware information about the AIX system would be returned

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
root@p1243-pvm2:/home/cecuser/test_3003.3/salt_3003.3$ salt-call --local test.versions
local:
    Salt Version:
              Salt: 3003.3
     
    Dependency Versions:
              cffi: 1.14.4
          cherrypy: 17.4.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.3
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.17
          pycrypto: 3.10.1
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.7.10 (default, Jun  1 2021, 05:23:20)
      python-gnupg: 0.4.4
            PyYAML: 5.4.1
             PyZMQ: 18.1.1
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: aix 1 
            locale: ISO8859-1
           machine: 00F9C4904C00
           release: 1
            system: AIX
           version: AIX 1 
```
</details>

**Additional context**
