### ISSUE TITLE
[BUG] mount.filesystems is no longer working correctly on AIX

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#60911]
**Description**
Execution module command for mount.filesystems is failing due to some unsupported file options on AIX.
There may have been additional options in later AIX v7.x which we need to account for form AIX v6.x when mount.filesystems was originally created

**Setup**
salt svrsinst5-0.hs.coop.ch mount.filesystems
salt svrsinst5-0.hs.coop.ch mount.set_filesystems /opt /dev/hd10opt jfs2

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
see setup

**Expected behavior**
Mount should occur

**Screenshots**

![Screenshot from 2021-09-21 08-32-10](https://user-images.githubusercontent.com/9943204/134211505-9d8eef6d-2988-494c-9fcb-68f18d0aaf7e.png)

![Screenshot from 2021-09-21 08-30-41](https://user-images.githubusercontent.com/9943204/134211602-0e75396e-385d-4313-aac8-ee064b0a45a1.png)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
root@p1243-pvm2:/home/cecuser/test_3003.3/salt_3003.3$ salt-call --local test.versions
local:
    Salt Version:
              Salt: 3003.3
     
    Dependency Versions:
              cffi: 1.14.4
          cherrypy: 17.4.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.3
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.17
          pycrypto: 3.10.1
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.7.10 (default, Jun  1 2021, 05:23:20)
      python-gnupg: 0.4.4
            PyYAML: 5.4.1
             PyZMQ: 18.1.1
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: aix 1 
            locale: ISO8859-1
           machine: 00F9C4904C00
           release: 1
            system: AIX
           version: AIX 1
```
</details>

**Additional context**
