### ISSUE TITLE
[BUG] Python 3 Tiamat based salt-minion on AIX encountering LVM library issues between v7.1 and v7.2

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#60914]
**Description**
Found an issue with using the library liblvm.a from AIX v7.1 builds on AIX 7.2

Running the command 
```
salt-call --local cmd.run "varyonvg testvg"
[WARNING ] The tools 'dmidecode' and 'lspci' failed to execute because they do not exist on the system of the user running this instance or the user does not have the necessary permissions to execute them. Grains output might not be accurate.
[ERROR   ] Command 'varyonvg testvg' failed with return code: 3
[ERROR   ] output: 0516-316 varyonvg: Unable to find volume group testvg in the Device
        Configuration Database.
local:
    0516-316 varyonvg: Unable to find volume group testvg in the Device
          Configuration Database.
```

But when run on AIX v7.2 this causes an error as described in https://bugzilla.eng.vmware.com/show_bug.cgi?id=2820595#c27

```
[14:19:43 root@r5pvap1093 /srv/salt]# salt a5dvap1033 test.version,cmd.run ,varyonvg
a5dvap1033:
    ----------
    cmd.run:
        Could not load program varyonvg:
        Symbol resolution failed for varyonvg because:
                Symbol lvm_change_vgstate (number 56) is not exported from dependent
                  module /opt/salt/run/liblvm.a(shr.o).
        Examine .loader section symbols with the 'dump -Tv' command.
    test.version:
        3002.1
```

During a customer call to help resolve the issue it was discovered that the version of liblvm.a which is part of bos.rte.lvm is different between the versions of AIX v7.1 and v7.2 which is causing the issue.

**Setup**
salt-call --local cmd.run "varyonvg testvg"
or
salt-call --local cmd.run varyonvg

will generate the issue with the library.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**
Customers AIX v7.2 details

![Screenshot from 2021-09-21 09-48-50](https://user-images.githubusercontent.com/9943204/134216590-14f35f4f-e56f-49e2-a01c-c2b2272f885b.png)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
root@p1243-pvm2:/home/cecuser/test_3003.3/salt_3003.3$ salt-call --local test.versions
local:
    Salt Version:
              Salt: 3003.3
     
    Dependency Versions:
              cffi: 1.14.4
          cherrypy: 17.4.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.3
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.17
          pycrypto: 3.10.1
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.7.10 (default, Jun  1 2021, 05:23:20)
      python-gnupg: 0.4.4
            PyYAML: 5.4.1
             PyZMQ: 18.1.1
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: aix 1 
            locale: ISO8859-1
           machine: 00F9C4904C00
           release: 1
            system: AIX
           version: AIX 1
```
</details>

**Additional context**
IBM provided AIX v.71 system provided to Salt
```
root@p1243-pvm2:/home/cecuser/test_3003.3/salt_3003.3# lslpp -l bos.rte.lvm
  Fileset                      Level  State      Description         
  ----------------------------------------------------------------------------
Path: /usr/lib/objrepos
  bos.rte.lvm               7.1.5.35  COMMITTED  Logical Volume Manager

Path: /etc/objrepos
  bos.rte.lvm               7.1.5.35  COMMITTED  Logical Volume Manager
root@p1243-pvm2:/home/cecuser/test_3003.3/salt_3003.3# oslevel -s
7100-05-07-2037
```
