### ISSUE TITLE
[BUG] Solaris 10 pkagadd occasionally creating the wrong linkage on install

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#60916]
**Description**
After running pkgrm to remove an installation of Salt, and then using pkgadd to install a new version of Salt, wrong linkage is created

```
The issue with the linkage
/opt/saltstack/salt/run/run -> /opt/saltstack/salt/run
```
Work-around has been to utilize zones, or a clean install on a system.

Need to investigate why pkgadd/pkgrm is not cleaning or installing correctly and if there is some post-install action that can be taken to rectify the issue.

**Setup**
pkgrm salt and pkgadd  new install of Salt

Recommend using the Intel Solaris 10 as quicker than the Sparc version

Correct stat for the file
```
root@unknown:/# l /opt/saltstack/salt/run/run
-rwxr-xr-x   1 root     root     16311338 Aug 27 15:48 /opt/saltstack/salt/run/run
root@unknown:/# 
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
see above

**Expected behavior**
/opt/saltstack/salt/run/run is an executable file and not a symbolic link.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
root@unknown:/# salt-call --local test.versions
local:
    Salt Version:
              Salt: 3003.3
     
    Dependency Versions:
              cffi: 1.14.4
          cherrypy: 17.4.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.3
           libgit2: Not Installed
          M2Crypto: 0.38.0
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.17
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.7.10 (default, Aug 27 2021, 15:02:51)
      python-gnupg: 0.4.4
            PyYAML: 5.4.1
             PyZMQ: 18.0.1
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: sunos 5.10 
            locale: UTF-8
           machine: i86pc
           release: 5.10
            system: SunOS
           version: SunOS 5.10
```
</details>

**Additional context**
