### ISSUE TITLE
[BUG] key_url appears to be stripped by expand_repo_info 

### ISSUE THREAD

**Issue by jlitzingerdev** [saltstack/salt#60936]
**Description**
During pkgrepo.managed's processing of the kwargs supplied, a call to expand_repo_info is made on ubuntu (probably all debian) systems.  This call removes the key_url argument.

Tested by updating the key_url to a new key and verifying that, on the minion, no update occurred.  I modified the python file on the minion and verified that the key_url went into expand_repo_info, but didn't come out.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
SLS:
```
docker_test:
  pkgrepo.managed:
    - humanname: Docker
    - name: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    - file: "/etc/apt/sources.list.d/docker.list"
    - key_url: "salt://files/docker-key-2.asc"
```
For the key, an older docker key, obtained from ubuntu's keyserver was used (URL at bottom).  The above key is the new key.
Please be as specific as possible and give set-up details.

Salt tutorial environment used for reproduction

  
**Steps to Reproduce the behavior**
master: Apply above state withkey_url pointed to a legacy key.
Verify on minion with apt-key that the above key is in the apt key list
Update the key_url
master: Apply state again
Check minion key list again, the key will not be updated

**Expected behavior**
The key should be updated.

**Screenshots**

**Versions Report**
3003.3

**Additional context**
Old docker key URL: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2dc31e828e9ba27f
New key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8d81803c0ebfcd88
