### ISSUE TITLE
[FEATURE REQUEST] salt-cloud - proxmox driver - add LXC "feature" activation

### ISSUE THREAD

**Issue by cavepopo** [saltstack/salt#60947]
**Is your feature request related to a problem? Please describe.**
It is not possible AFAIK to activate "features" at LXC creation time.

**Describe the solution you'd like**
In proxmox webUI we can activate some extended feature (NFS, Nesting and more).
It would be good to be able to activate these through a parameter in provider/profile/map files.

**Describe alternatives you've considered**
As of now I must use the proxmox webUI afterwards to activate these "features"

Here is a screenshot of these "features"
![image](https://user-images.githubusercontent.com/16035946/134645207-c04d9461-955b-4c66-8585-d653c9584965.png)

**Comment by mthibaut** [comment]
This functionality is available already, but not documented, for instance:

```
mylxc:
    provider: myproxmox
    image: local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz
    technology: lxc
    storage: local-lvm
    host: myhost
    ip_address: 192.168.1.100
    features: mount=nfs,nesting=1
```
