### ISSUE TITLE
[BUG]salt['grains.filter_by']() not checking grains correctly against grain values with spaces in them

### ISSUE THREAD

**Issue by macmandr197** [saltstack/salt#60976]
**Description**
I'm trying to use the file.managed module, and choosing a specific file based upon the result of a grain using filter_by

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
**init.sls**
```
{% from "path/gpu_models.yaml" import gpu_model_map with context %}
{% set gpu_model = salt['grains.filter_by'](gpu_model_map, grain=salt['grains.get']('gpus:0:model')) %}

{% from "path/gpu_vendors.yaml" import gpu_vendor_map with context %}
{% set gpu_vendor = salt['grains'].filter_by(gpu_vendor_map, grain='gpus:vendor') %}
...
#install the graphics agent
install_teradici:
  pkg.installed:
    - name: {{ gpu_vendor.teradici_agent}}
    - version: {{ gpu_vendor.teradici_agent_version}}
    - require: 
      - teradici_repo #step omitted from snippet

#manage the xorg.conf.d override file pcoip.conf, and only if the graphics agent has been installed.
teradici_xorg_conf:
  file.managed:
    - source: salt://centos76/ghost_vfx/software/teradici/{{ gpu_model.xorg_file }}
    - name: /etc/X11/xorg.conf.d/pcoip.conf
    - user: root
    - group: root
    - mode: '0644'
    - require: 
      - install_teradici
      - pkg: pcoip-agent-graphics
...
```
**GPU map**
```
{% load_yaml as gpu_model_map %}

'GK110GL [Quadro K6000]':
  xorg_file: teradici_k.conf

'GK106GL [Quadro K4000]':
  xorg_file: teradici_k.conf

'GK104GL [Quadro K4200]':
  xorg_file: teradici_k.conf

'Device 1eb1':
  xorg_file: teradici_mp.conf

'GM204GL [Quadro M4000]':
  xorg_file: teradici_mp.conf

'GP104GL [Quadro P4000]':
  xorg_file: teradici_mp.conf

'GM200GL [Quadro M6000]':
  xorg_file: teradici_mp.conf

'GM200GL [Quadro M6000 24GB]':
  xorg_file: teradici_mp.conf

{% endload %}
```
**Vendors Map**
```
{%- load_yaml as gpu_vendor_map %}

nvidia:
  teradici_agent: pcoip-agent-graphics
  teradici_agent_version: 20.04.0-1
unknown:
  teradici_agent: pcoip-agent-standard
  teradici_agent_version: 20.04.0-1

{%- endload %}
```

Please be as specific as possible and give set-up details.
using v 3002.7 on CentOS 7.6.

- [ y] on-prem machine
- [ n] VM (Virtualbox, KVM, etc. please specify)
- [ n] VM running on a cloud service, please be explicit and add details
- [ n] container (Kubernetes, Docker, containerd, etc. please specify)
- [ n] or a combination, please be explicit
- [ n] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
place files in a relevant location on a CentOS Machine with a Graphics card installed. Can be a Quadro, or whatever GPU you have. Just be sure to update the GPU map with the resulting gpus:0:model grain value. after that run the state file.

**Expected behavior**
With a Quadro P4000 (grain value "GP104GL [Quadro P4000]", the jinja variables should render as the following:
`gpu_vendor.teradici_agent` pcoip-agent-graphics

`gpu_vendor.teradici_agent_version` 20.04.0-1

`gpu_model.xorg_model` teradici_mp.conf

However, the `gpu_model.xorg_model` value always ends up as None (which would be the default value of xorg_file) however, I have a matching value in my map file? I literally copy and pasted the grain result into the map file and surrounded it in quotes.
