### ISSUE TITLE
[DOCS] How to do any or two successful minion return in Saltstack orch state?

### ISSUE THREAD

**Issue by zanhsieh** [saltstack/salt#60979]
**Description**
I'm frustrated with salt orch state for converting HBase to HA mode. This required:

- Datanode process has to be up and running on ALL nodes.
- HRegion process has to be up and running on ALL nodes.
- After converting, namenode process has to be up and running on two nodes only.

So I got ALL implicitly for free, e.g.

```
{# If all minions passed, then this will pass #}
2_1_example_pod_is_dn_running:
  salt.function:
    - name: cmd.run
    - tgt: 'G@stype:hbase and G@pod_name:example_pod'
    - tgt_type: compound
    - arg:
      - ps aux | grep datanode
    - failhard: True
```

But how to check any or two?

```
{# Pseduo code. This won't work. #}
2_3_example_pod_is_nn_running:
    - name: cmd.run
    - tgt: 'G@stype:hbase and G@pod_name:example_pod'
    - tgt_type: compound
    - arg:
      - ps aux | grep namenode
    - successful_count: 2   {# <== namenode process has to be running on two minions #}
    - failhard: True
```

**Suggested Fix**
Could we have some example for getting TWO or minions execution successfully example in orch state?

**Type of documentation**
Salt orch state

**Location or format of documentation**
NA
