### ISSUE TITLE
[FEATURE REQUEST] allow setting a message for failhard status

### ISSUE THREAD

**Issue by alias454** [saltstack/salt#60993]
**Describe the solution you'd like**
When using **failhard** on a state, having an option to add descriptive messages would be helpful for many reasons. Some of those reasons might be logging output or an on screen display of what went wrong and what to do about it etc.

**Describe alternatives you've considered**
It's easy enough to make the state name slightly more verbose, which can can help a bit in a pinch.

**Additional context**
Currently an example of the current failhard usage looks like this:
```
test-maint-mode-already-enabled-aborting-updates:
    test.fail_without_changes:
      - failhard: True
      - onfail:
        - cmd: command-check-maint-mode-status
```

Allowing the option to add an additional msg could look like this
```
test-maint-mode-enabled:
    test.fail_without_changes:
      - failhard: 
        - msg: |
            This is a more verbose message that can have detailed information
            That the user can then take actions based on the resulting outputs
            Maybe this will say go read some doc or verify some setting somewhere
      - onfail:
        - cmd: command-check-maint-mode-status
```

Thanks
