### ISSUE TITLE
[BUG] State pkg.removed cannot handle more than one package during uninstall

### ISSUE THREAD

**Issue by afischer-opentext-com** [saltstack/salt#61001]
**Description**

On Windows, assuming you have two versions of a package installed at a same time, the _state_ `pkg.removed` or `pkg.purged` is unable to properly populate the `result` of the states operation. Instead the result is always `false`. 

This is because the method `states/pkg.py/_uninstall()` does not consider the passed versions when computing failures. Because of that it simply assumes that any existence of a pkg is an error. This leads to (high)states reported as errors, while everything is okay.

**Setup**

Package Description: 

```(yaml)
MyApplication:
  "21.3.0.37":
    full_name: "MyApplication"
    installer: "C:/setup_21.3.0.37.exe"
    msiexec: false
    reboot: false
    locale: en_US
  "21.3.0.121":
    full_name: "MyApplication"
    installer: "C:/setup_21.3.0.121.exe"
    msiexec: false
    reboot: false
    locale: en_US
```

State myapplication.installed.sls

```(yaml)
MyApplication 21.3.0.37 installed:
  pkg.installed:
    name: "MyApplication"
    version: "21.3.0.37"
MyApplication 21.3.0.121 installed:
  pkg.installed:
    name: "MyApplication"
    version: "21.3.0.121"
```

State myapplication.outdated_absent.sls

```(yaml)
MyApplication 21.3.0.37 absent:
  pkg.removed:
    name: "MyApplication"
    version: "21.3.0.37"
```

**Steps to Reproduce the behavior**

```(bash)
salt-call state.apply myapplication.installed
salt-call state.apply myapplication.outdated_absent
```

```(yaml)
local:
--------
        ID: MyApplication 21.3.0.37 absent
  Function: pkg.removed
      Name: MyApplication
    Result: False
   Comment: The following packages failed to remove: MyApplication.
   Started: 09:09:39.123456
  Duration: 16160.123 msg
   Changes:
            --------
            MyApplication:
                --------
                new:
                    21.3.0.121
                old:
                    21.3.0.121,21.3.0.37
```

**Expected behavior**

```(bash)
salt-call state.apply myapplication.outdated_absent
```

```(yaml)
local:
--------
        ID: MyApplication 21.3.0.37 absent
  Function: pkg.removed
      Name: MyApplication
    Result: True
   Comment: All targetes packages were removed.
   Started: 10:09:39.123456
  Duration: 16160.123 msg
   Changes:
            --------
            MyApplication:
                --------
                new:
                    21.3.0.121
                old:
                    21.3.0.121,21.3.0.37
```

**Workaround**

Use `module.run` but have no control over success:

```(yaml)
MyApplication 21.3.0.37 absent:
  module.run:
    - pkg.remove:
        name: "MyApplication"
        version: "21.3.0.37"
````

**Screenshots**

![2021-10-05_10h39_33](https://user-images.githubusercontent.com/37439392/135995581-0292e5ec-7121-4815-a091-3dd863c455eb.png)

**Versions Report**

Windows Salt-minion 3003.3 (x64)

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.5
      cherrypy: 18.6.0
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2019Server
        system: Windows
       version: 2019Server 10.0.17763 SP0
```
