### ISSUE TITLE
[BUG]cp.push in state file is not copying the file

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#61024]
**Description**
cp.push in state file is not copying a file from minion. cp.push is working in direct cli.

**Setup**
```
{% from 'test.sls' import file with context %}
pushfile:
  module.run:
    - name: cp.push
    - path: /oracle/{{ file }}

```
  

**Results**
          ID: pushfile
    Function: module.run
        Name: cp.push
      Result: True
     Comment: 
     Started: 06:39:41.038489
    Duration: 0.825 ms
     Changes:   
----------

No file is pushed to minion cache

**Versions Report**
salt 3000.3
