### ISSUE TITLE
[FEATURE REQUEST] Adding (more) logic capabilities to the YAML parser, reducing Jinja

### ISSUE THREAD

**Issue by lowercase00** [saltstack/salt#61057]
**Is your feature request related to a problem? Please describe.**
Coming from Ansible, I'm a bit frustrated on the complexity to understand and write formulas with simple logic (if statements, for example). As I understood from the formulas I've seen so far on the base repo (saltstack-formulas), most of the responsibility to add logic falls to Jinja, instead of the Salt's YAML parser.

**Describe the solution you'd like**
It would be great to add some logic capability to the YAML Parser. That way we could be possible to greatly simplify the formulas, significantly reducing the use of Jinja, increasing readability and making the learning curve for new users a lot simpler. In many ways, I think Ansible does a great job in that aspect (the `when` statement inside a task for example, or even the `loop` capabilities with the `with_items`)

**Describe alternatives you've considered**
I wonder whether it would be possible to add more logic to Salt's YAML parser, so for example:

This code: from the mysql formula
 
```YAML
...
include:
  - .server
{%- if mysql_salt_user %}
  - .salt-user
{%- endif %}
  - .database
  - .user
{%- if mysql_dev %}
  - .dev
{%- endif %}
{%- if (db_states|length() + user_states|length()) > 0 %}
extend:
  mysqld-service-running:
    service:
      - require_in:
        {{ requisites('mysql_database', db_states) }}
        {{ requisites('mysql_user', user_states) }}
{%- endif %}
```

Could become something like this:
```YAML
...
include:
  - name: .server
  - name: .salt-user
    condition: {{ mysql_salt_user == True }}
  - name: .database
  - name: user
  - name: .dev
    condition: {{ mysql_dev == True }}

extend:
  mysqld-service-running:
    condition: {{ (db_states|length() + user_states|length()) > 0 }}
    service:
      - require_in:
        {{ requisites('mysql_database', db_states) }}
        {{ requisites('mysql_user', user_states) }}
     
```

I'm not sure this is the best example, but I think it gives an idea on how an implementation to reduce the weight of Jinja inside a YAML file could look like.

**Additional context**
I'm pretty new to Salt, so I apologise if this is a design decision that has been discussed in the past, I couldn't find any topic related to this, but that maybe be just a symptom of poor search skills. I would be very glad to contribute, but being new to ecosystem, I would probably need some guidance.

I confess I'm frustrated that Ansible is more popular with Salt (I'm using github starts, available tutorials and SO questions as a proxy for popularity). Coming from Ansible and having discovered Salt, this is just way better, more powerful and more flexible, with great APIs, I would love to see Salt growing, and I would think that simplifying things could help with Salt's popularity (that's one of the reasons I think Ansible grew some much so fast).

Coming from a Flask background, as much as I appreciate how powerful Jinja is, it's pretty easy to have an ugly and complex code really fast, with not very friendly indentation and IDE support, so would be great to be able to do more things in YAML.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.
