### ISSUE TITLE
[BUG] 3004 Windows minion fails to open log file

### ISSUE THREAD

**Issue by dafyddj** [saltstack/salt#61113]
**Description**
A fresh install of a Salt minion v3004 on Windows fails to open a log file for logging.
```
PS C:\Users\vagrant> salt-call test.ping
[WARNING ] Failed to open log file, do you have permission to write to C:\ProgramData\Salt Project\Salt\var\log\salt\min
ion?
local:
    True
```
Creating a file in Salt's log directory succeeds so it doesn't seem that permissions themselves are the problem.
```
PS C:\Users\vagrant> New-Item 'C:\ProgramData\Salt Project\Salt\var\log\salt\minion\test.txt' -type file


    Directory: C:\ProgramData\Salt Project\Salt\var\log\salt\minion


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        22/10/2021     17:43          0 test.txt

```

Directory permissions are as follows:
```
icacls.exe 'C:\ProgramData\Salt Project\Salt\var\log\salt\minion'
C:\ProgramData\Salt Project\Salt\var\log\salt\minion BUILTIN\Administrators:(I)(OI)(CI)(F)
                                                     NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
                                                     OWNER RIGHTS:(I)(OI)(CI)(F)

Successfully processed 1 files; Failed processing 0 files
```
Group memberships are:
```
PS C:\Users\vagrant> net localgroup

Aliases for \\WINDOWS-DUD09MH

------------------------------------
*Access Control Assistance Operators
*Administrators
*Backup Operators
*Cryptographic Operators
*Distributed COM Users
*Event Log Readers
*Guests
*Hyper-V Administrators
*IIS_IUSRS
*Network Configuration Operators
*Performance Log Users
*Performance Monitor Users
*Power Users
*Remote Desktop Users
*Remote Management Users
*Replicator
*Users
*WinRMRemoteWMIUsers__
The command completed successfully.
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
* Fresh install in Windows 8.1 (Virtualbox v6.1.26)
* Only config change: `file_client: local`

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

No warning message, and log file created.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: 3.1.18
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 8.1
        system: Windows
       version: 8.1 6.3.9600 SP0 Multiprocessor Free
```
</details>

**Additional context**

Noted elsewhere saltstack/salt-bootstrap#1610

FAO @twangboy
