### ISSUE TITLE
Salt 3004 broke extend [BUG]

### ISSUE THREAD

**Issue by MartinEmrich** [saltstack/salt#61121]
**Description**
A pair of states (One extending another) works with minion up to 3003, but not with 3004. Instead I get:

````
salt-call state.apply rsyslog test=True
local:
    Data failed to compile:
----------
    Cannot extend ID 'rsyslog' in 'base:services.rsyslog'. It is not part of the high state.
This is likely due to a missing include statement or an incorrectly typed ID.
Ensure that a state with an ID of 'rsyslog' is available
in environment 'base' and to SLS 'services.rsyslog'
````

**Setup**

Salt master (happens with both 3000.3 and 3004 tested).
Two states:
packages.rsyslog:
````
rsyslog:
  pkg:
    - latest
````

services.rsyslog:
````
include:
  - packages.rsyslog

extend:
  rsyslog:
    service:
     - running
     - enable: True
     - require:
       - pkg: rsyslog
     - watch:
       - pkg: rsyslog
`````
(could be simplified, but it worked for years now)
  
**Steps to Reproduce the behavior**
run `salt-call state.apply services.rsyslog` (or highstate including it) on salt-minion 3004.
Works fine with older minions.

**Expected behavior**
both pkg.installed and service.running including require and watch should work as before.

**Versions Report**
```
# salt-minion --versions-report
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.4.2
     docker-py: 2.6.1
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.21.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Additional context**

**Comment by nkukard** [comment]
I'm seeing the same issue on ArchLinux after upgrading to 3004

**Comment by pauldalewilliams** [comment]
I ran into a similar error but with a different setup (not using extend).  I suspect it has to do with this change:  https://github.com/saltstack/salt/pull/59943  I can confirm that my now broken watch_in requisite worked prior to 3004.

Mine cropped up when I had this in an SLS (abbreviated but enough to demonstrate the issue):
```
nginx-proxy:
  docker_network.present

Ensure nginx-proxy container is running:
  docker_container.running:
    - name: nginx-proxy
    - image: jwilder/nginx-proxy
    - restart_policy: always
    ...

Turn off server tokens on nginx-proxy:
  file.managed:
    - name: /data/nginx-proxy/conf/custom_settings.conf
    - user: root
    - group: root
    - mode: 644
    - contents: |2
        server_tokens off;
        client_max_body_size 1g;
    - require:
      - docker_volume: nginx-conf
    - watch_in:
      - docker_container: nginx-proxy
```

If I modify the ID for the nginx-proxy docker_container state it works once again:
```
nginx-proxy:
  docker_network.present: []
  docker_container.running:
    - image: jwilder/nginx-proxy
    - restart_policy: always
    ...

Turn off server tokens on nginx-proxy:
  file.managed:
    - name: /data/nginx-proxy/conf/custom_settings.conf
    - user: root
    - group: root
    - mode: 644
    - contents: |2
        server_tokens off;
        client_max_body_size 1g;
    - require:
      - docker_volume: nginx-conf
    - watch_in:
      - docker_container: nginx-proxy
```
