### ISSUE TITLE
Ordered states, full conditional support for `unless`/`onlyif`

### ISSUE THREAD

**Issue by bfrog** [saltstack/salt#6114]
Its difficult to develop salt states due to the require/watch mechanisms.

I'd really like to have a "state" composed instead of ordered states.

say...

```
nginx:
  ordered:
     - pkg.installed
     - file.directory: 
       - name: /etc/nginx/certs
     - service.running
```

Another helpful addition would be the ability to simply require a whole state name as well as allow full conditionals in the require/watch/unless style clauses.

```
source:
   git.latest:
      .... 

deploy:
    cmd.wait:
       - name: deploy.sh
       - condition: {% state['source'] and not mydeployment_exists() %}
```

The two things above would take 90% of the pain away from currently developing salt states
