### ISSUE TITLE
[BUG] failed to execute powershell script using "cmd.script" with "runas" parameter

### ISSUE THREAD

**Issue by ovybach** [saltstack/salt#61166]
**Description**
Failed to execute powershell script using "cmd.script" with "runas" parameter. Step fails with error:
```
^C:\ProgramData\Salt Project\Salt\var\cache\salt\minion\tmpg02cql8w\__salt.tmp.j_yi8_ho.ps1^ : The term
                  '^C:\ProgramData\Salt Project\Salt\var\cache\salt\minion\tmpg02cql8w\__salt.tmp.j_yi8_ho.ps1^' is not recognized as
                  the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
                  included, verify that the path is correct and try again.
                  At line:1 char:1
                  + ^"C:\ProgramData\Salt Project\Salt\var\cache\salt\minion\tmpg02cql8w\ ...
                  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      + CategoryInfo          : ObjectNotFound: (^C:\ProgramData...p.j_yi8_ho.ps1^:String) [], CommandNotFoundException
                      + FullyQualifiedErrorId : CommandNotFoundException
```

**Setup**
Issue is reproducible locally on salt-minion and through salt-master.

OS: Windows Server 2019
PowerShell version: 5.1.17763.2183
Salt: 3004
  
**Steps to Reproduce the behavior**
Execute the following sls file:
```
C:\\ProgramData\\test-script.ps1:
  file.managed:
    - contents:
      - Write-Host "Hello World"
create_user:
  user.present:
    - name: testuser
    - password: 'MySuper!Str0ngPassw0rd'
run_script:
  cmd.script:
    - source: "C:\\ProgramData\\test-script.ps1"
    - shell: powershell
    - runas: testuser
    - password: 'MySuper!Str0ngPassw0rd'
delete_user:
  user.absent:
    - name: testuser
    - purge: True
```
Note: user creation step is not mandatory if you already have some testing user to use for "runas".

**Expected behavior**
Step "run_script" should finish successfully with "Hello World" stdout message

Debug log: [salt-debug-log.txt](https://github.com/saltstack/salt/files/7460748/salt-debug-log.txt)
Salt output: [salt-output.txt](https://github.com/saltstack/salt/files/7460755/salt-output.txt)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2019Server
        system: Windows
       version: 2019Server 10.0.17763 SP0 Multiprocessor Free
```
</details>

**Additional context**
cmd.script works fine if you don't use "runas" parameter.
