### ISSUE TITLE
[BUG] lgpo.set state module fails to set 'Audit Directory Service Access'

### ISSUE THREAD

**Issue by dstoliker** [saltstack/salt#61198]
**Description**
lgpo.set state module fails to set 'Audit Directory Service Access' - instead incorrectly reports that the policy is already in a desired state.

**Setup**
This has been tested on Windows Server 2016 configured as a domain controller.

The policy can be found at Computer Configuration >> Windows Settings >> Security Settings >> Advanced Audit Policy Configuration >> System Audit Policies >> DS Access >> "Audit Directory Service Access".  By default, the policy will be in the state "Not Configured".

Assuming a Not Configured state, the following SLS will provide the appropriate setup.

```
audit_directory_service_access_failure:
  lgpo.set:
    - computer_policy:
        "Audit Directory Service Access": "Failure"
```
  
**Steps to Reproduce the behavior**
If the state above is run in `test=True` mode, the need to apply a change is correctly reported.

```
local:
----------
          ID: audit_directory_service_access_failure
    Function: lgpo.set
      Result: None
     Comment: The following policies are set to change:
              Audit Directory Service Access
     Started: 07:35:12.319868
    Duration: 62.685 ms
     Changes:

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
```
However, when run without `test=True`, the state is incorrectly reported in the specified state.
```
local:
----------
          ID: audit_directory_service_access_failure
    Function: lgpo.set
      Result: True
     Comment: The following policies are in the correct state:
              Audit Directory Service Access
     Started: 07:35:31.664043
    Duration: 530.9 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
```

**Expected behavior**
The lgpo module should correctly identify the need to update the policy and do so when not run with the `test=True` option.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2016Server
        system: Windows
       version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```
</details>

**Additional context**
N/A
