### ISSUE TITLE
[BUG] beacons.disable does not disable beacons set by pillar

### ISSUE THREAD

**Issue by AGirin** [saltstack/salt#61195]
**Description**
I tried disabling beacons that are set by pillar by using beacons.disable command. Salt-minons are running on Windows 2016...Not sure if this is by design or this is a bug... Salt-minons and master are 3004. 

Basically I have beacons that watch services... I wanted to stop services for some time to work on something. Running beacons.disable did not have any affect - services were still restarting by salt... I tried refreshing pillars, then beacons.. I confirmed  that beacons.list showed enable: False... But beacons still worked..

**Comment by jmcmillan89** [comment]
Is this a bug or working as intended? I can't find any documentation to support that pillar beacons cannot be disabled, but that is definitely the behavior:
```
[root@wdc-salt02 beacons]# salt -L vad1dsslapp07.hpg.com beacons.disable_beacon inotify
vad1dsslapp07.hpg.com:
    ----------
    comment:
        Cannot disable beacon item inotify, it is configured in pillar.
    result:
        False
ERROR: Minions returned with non-zero exit code
```
I can however execute `beacons.disable`, which does show all beacons as disabled:
```
[root@wdc-salt02 beacons]# salt -L vad1dsslapp07.hpg.com beacons.list
vad1dsslapp07.hpg.com:
    beacons:
      enabled: false
      inotify:
      - files:
          /etc/httpd:
            auto_add: true
            exclude:
            - /etc/httpd/logs
            recurse: true
      - interval: 60
      - disable_during_state_run: true
```

However, I am still seeing inotify events come across the bus:
```
salt/beacon/vad1dsslapp07.hpg.com/inotify//etc/httpd    {
    "_stamp": "2022-03-03T20:37:28.746673",
    "change": "IN_CREATE",
    "id": "vad1dsslapp07.hpg.com",
    "path": "/etc/httpd/justin.txt"
}
```

I think there is a valid use-case for disabling beacons, mainly when one needs to do some manual configuration and testing without the events/reactors firing and resetting things.
