### ISSUE TITLE
[BUG] Minions in multi-master setup generated hundreds of connections each to the inactive master.

### ISSUE THREAD

**Issue by mariopatov** [saltstack/salt#61218]
**Description**
We have two master servers in multi-master setup. The secondary master server had its salt-master service stopped for a while and we  experienced extremely high number of connections exponentially growing. This was hundreds of connection attempts from some minions making it like a DDoS internal attack.  To resolve the problem, we started back the salt-master service on the secondary node. 

**Setup**

- Virtual machine VMWare both agents and master servers
- Master and some agents on RedHat 7, also agents on Windows 2012, 2016 and 2019
- Minions configuration type 1:
`master:`
`- 1-sstack01`
`- 2-sstack01`
`retry_dns: 0`
`master_type: failover`
`master_alive_interval: 30`
`id: 1-SERVER01`
- Minions configurations type 2:
`master:`
`  - 1-sstack01`
`  - 2-sstack01`
`master_type: failover`
`master_alive_interval: 30`
`master_tries: 30`
`master_failback: True`
`master_failback_interval: 30`
`retry_dns: 0`
`id: 2-SERVER02`
  
**Steps to Reproduce the behavior**
Stop the salt-master service on the secondary server for a while (3 weeks in our case) and  restarted the primary master service several times like during patching.

**Expected behavior**
Minions should be trying to connect to the master in a reasonable time interval (every second minimum) and not hundreds times per second.

**Screenshots**
No screenshots available.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
[root@1-SSTACK01 ~]# salt --versions-report
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: rhel 7.9 Maipo
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.2.2.el7.x86_64
        system: Linux
       version: Red Hat Enterprise Linux Server 7.9 Maipo
```
</details>

**Minion Linux Versions Report**
<details><summary>salt-minion --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
[root@1-LINUX ~]# salt-minion --versions-report
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: rhel 7.9 Maipo
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.42.2.el7.x86_64
        system: Linux
       version: Red Hat Enterprise Linux Server 7.9 Maipo
```
</details>

**Minion Windows Versions Report**
<details><summary>salt-minion --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
C:\salt>salt-minion --versions-report
Salt Version:
          Salt: 3002.5

Dependency Versions:
          cffi: 1.12.2
      cherrypy: 17.4.1
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.7
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.191
6 64 bit (AMD64)]
  python-gnupg: 0.4.4
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 2.0.5
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2012ServerR2
        system: Windows
       version: 2012ServerR2 6.3.9600 SP0


C:\salt>
```
</details>

**Additional context**
Thank you for reviewing this case!
