### ISSUE TITLE
pip.installed can only install to the default location

### ISSUE THREAD

**Issue by 3hhh** [saltstack/salt#61249]
### Description of Issue

With newer versions of `pip3`, `pip.installed` can only install to the default location.

Reason: Pip [changed its behaviour](https://github.com/pypa/pip/issues/9435).

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Example from https://docs.saltproject.io/en/latest/ref/states/all/salt.states.pip_state.html :
```
django:
  pip.installed:
    - name: django
    - bin_env: /usr/bin/pip3
    - install_options:
      - --prefix=/blah
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Execute the aforementioned state. Obtain [this error](https://github.com/pypa/pip/issues/9435).

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
3001.7
