### ISSUE TITLE
SaltStack - Unable to check if file exists on minion using salt['cmd.run']

### ISSUE THREAD

**Issue by sujeetkp** [saltstack/salt#61250]
I am trying to check if a particular file with some extension exists on a centos host using salt stack.

```
create:
   cmd.run:
     - name: touch /tmp/filex

{% set output = salt['cmd.run']("ls /tmp/filex") %}

output:
   cmd.run:
     - name: "echo {{ output }}"
```
     
Even if the file exists, I am getting the error as below:

```
----------
          ID: create
    Function: cmd.run
        Name: echo ls: cannot access /tmp/filex: No such file or directory
      Result: True
     Comment: Command "echo ls: cannot access /tmp/filex: No such file or directory" run
     Started: 08:48:39.335380
    Duration: 13.34 ms
     Changes:
              ----------
              pid:
                  25711
              retcode:
                  0
              stderr:
              stdout:
                  ls: cannot access /tmp/filex: No such file or directory
```
```
root@hostname# salt --version
salt 3003.3
```
