### ISSUE TITLE
[BUG] Strange errors on 3004 Powershell commands

### ISSUE THREAD

**Issue by AGirin** [saltstack/salt#61259]
**Description**
We started seeing issues with 3004 on Windows 2019. All of a sudden we see a lot of errors like this:

> 2021-11-18 02:59:10,583 [salt.loaded.int.module.cmdmod:883 ][ERROR   ][3132] retcode: 4294901760
> 
> 2021-11-18 02:59:10,583 [salt.loaded.int.module.cmdmod:1300][ERROR   ][3132] Command 'powershell' failed with return code: 4294901760
> 
> 2021-11-18 02:59:10,583 [salt.loaded.int.module.cmdmod:1305][ERROR   ][3132] output: Windows Powershell terminated with the folloiwng error: The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.

What happens is that states that use Powershell command fail to run. Script that are scheduled with Salt scheduler fail to run... So far we only saw this on 3004. Servers that use 3003.3 do not show the same behavior. 

**Setup**
salt-master is 3004.
salt-minions is a mix of 3004 and 3003.3

OS is Windows 2016/Windows 2019.

**Comment by OrangeDog** [comment]
Can you add the full minion versions report (`salt-call --versions`).

Do you get the same errors when running the same command with `salt` or `salt-call` instead of the scheduler?

**Comment by AGirin** [comment]
Here is salt-call --versions report: 

Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2019Server
        system: Windows
       version: 2019Server 10.0.17763 SP0 Multiprocessor Free

**Comment by AGirin** [comment]
The scripts are within pillar... So not sure how to run it manually... I run schedule.run_job and it runs OK.. Interesting thing is that the same servers works fine, then stops than works fine again for no reason at all... Still looking at what might be causing it outside salt.

**Comment by OrangeDog** [comment]
What is the scheduled job that is failing?

**Comment by AGirin** [comment]
Yes.... I actually just ran this script with cmd.run... It runs just fine... But.. I ran highstate and got those errors in the log..

**Comment by AGirin** [comment]
Trying to figure out what exactly is going on.

**Comment by AGirin** [comment]
So this is what I see... I isolated one state that has powershell command: 

`{%` if salt['cmd.run']('powershell -NoProfile -NoLogo -NonInteractive -ExecutionPolicy Bypass "if ( Get-Service <service name> -ErrorAction SilentlyContinue) { Write-Output "True" }"') != 'True' %}

I ran this state multiple times on one server... Two times state succeeded... Third time I got error... Basically what happen that PowerShell command returned those errors and state went on to run next step (but it was supposed to skip it as service exists on that server....

PowerShell crashed... State did not get True and tried to apply next step... So why would it succeed two times and not third time.. 

4th, 5th and 6th times state failed... 7th succeeded... I will try on 3003.3 now...

**Comment by AGirin** [comment]
Running same state on Windows 2019 with 3003.3 has no issues. Ran it like 15-20 times.

**Comment by AGirin** [comment]
So what I think is happening - some kind of bug makes powershell fail wen ran from Salt.. And that in turn breaks states or schedules (as they just don't run)...

**Comment by AGirin** [comment]
Will downgrade server that fails now to 3003.3 and will run the same state.

**Comment by AGirin** [comment]
Downgraded. Ran the state many times... No issues. Will let it run for some time (maybe some memory leak?) and will try again.

**Comment by OrangeDog** [comment]
The only results I can see for that error is a Windows stack overflow bug that was fixed in 2016.
Presumably Windows 2019 has that fix...

**Comment by AGirin** [comment]
Well... All Windows 2019 servers that have 3004 show those errors. I downgraded 10 of them yesterday... Errors disappeared.

**Comment by twangboy** [comment]
I have created the following test state named `test.sls`:
```
{% if salt['cmd.run']('powershell -NoProfile -NoLogo -NonInteractive -ExecutionPolicy Bypass "if ( Get-Service -ErrorAction SilentlyContinue) { Write-Output ""True"" }"') != 'True' %}
pass:
  test.succeed_without_changes
{% else %}
fail:
  test.fail_without_changes
{% endif %}
```

And I am applying the state:
```
salt-call --local -l debug state.apply test
```

I cannot get this to fail...

**Comment by AGirin** [comment]
It feels like it is directly related to scheduled tasks we have.. We have two scripts scheduled with pillar to run on a regular basis. I see this Windows Event when those errors in salt minion log appear:

```
Fault bucket 1424768452868643046, type 5
Event Name: PowerShell
Response: Not available
Cab Id: 0

Problem signature:
P1: powershell.exe
P2: 10.0.14393.2339
P3: System.IO.IOException
P4: System.IO.IOException
P5: utomation.Security.SystemPolicy.GetAppLockerPolicy
P6: System.IO.__Error.WinIOError
P7: Consol.. main thread
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5BE5.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Critical_powershell.exe_2b1bba91ee513b5f51fa876dc8a2e4e531a87c9_00000000_e82060b7

Analysis symbol: 
Rechecking for solution: 0
Report Id: a4f7ce75-4c58-11ec-968f-00505681d266
Report Status: 0
Hashed bucket: bf714978a4a1dc9653c5cb5bf06b18e6
```

**Comment by AGirin** [comment]
This is how our scripts are scheduled:

```
<Name>:
        args:
        - powershell -NoProfile -NoLogo -NonInteractive -ExecutionPolicy Bypass -File
          <script name>
        enabled: true
        function: cmd.run
        hours: 1
        jid_include: true
        maxrunning: 1
        metadata:
          name: <name>
        name: <name>
        run_on_start: true
   <name>:
        args:
        - powershell -NoProfile -NoLogo -NonInteractive -ExecutionPolicy Bypass -File
          <name>
        enabled: true
        function: cmd.run
        hours: 1
        jid_include: true
        maxrunning: 1
        metadata:
          name: <name>
        name: <name>
        return_job: false
        run_on_start: true
        splay:
          end: 60
          start: 5
```
