### ISSUE TITLE
Synchronizing the salt directory - salt:// not accepted as file.recurse.source URI

### ISSUE THREAD

**Issue by StyXman** [saltstack/salt#61269]
I'm sorry if this is dupe'd, but trying to find anything with only `salt://` is impossible in GH.

We want to synchronize the whole tree that holds our salt configuration to a standby backup master, which resides in `/opt/salt`. But when we try to write the sync state, we get this:

```yaml
sync_salt_base:
  file.recurse:
    - name: /opt/salt
    - source: salt://
    - file_mode: keep
    # clean removes everything not sync'ed by Salt. Thus, also sync empty directories,
    # or they'll be removed all the time, and re-created by salt-master.
    - clean: True
    - include_empty: True
```

As you can see, `/opt/salt` is listed as one of the fileserver's roots. The problem is that `salt://` is rejected because `source` is first [right stripped of `/`s](https://github.com/saltstack/salt/blob/master/salt/states/file.py#L4148) and then [it's compared against `salt://`](https://github.com/saltstack/salt/blob/master/salt/states/file.py#L4151).

Otherwise, are better ways to achieve this?
