### ISSUE TITLE
Feature: allow salt.states.git.latest.identity to pull from Salt's file server

### ISSUE THREAD

**Issue by Artanicus** [saltstack/salt#6128]
Not sure if this is a bug or working-as-intended, sorry for the noise if it's the latter.

My scenario is deploying a piece of software from a private git+ssh repository. Ideally I wouldn't need to pull and store the deployment identity key on the minion host and could instead use it straight from the file server. However it seems this is not valid usage or broken;

```
    State: - git
    Name:      git+ssh://git@bitbucket.org/Artanicus/hedge-mc.git
    Function:  latest
        Result:    False
        Comment:   Warning: Identity file salt://hedgemc/hedge-mc-deploy not accessible: No such file or directory.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
        Changes:
```

And the relevant parts of the sls that's triggering the error;

```
git+ssh://git@bitbucket.org/Artanicus/hedge-mc.git:
  git.latest:
    - require:
      - user: hedge
    - rev: master
    - target: /srv/hedgemc/hedge
    - runas: hedge
    - identity: salt://hedgemc/hedge-mc-deploy
```

Most likely this is just me hoping for something the file server is not meant to be so any pointers towards a more valid way of solving this would be very welcome. The only way I currently see around this would be to permanently store the deployment key on the minion host or pull it in with every highstate and resort to evil kludges to remove it afterwards. Better ideas?

master versions;

```
v# salt --versions-report
           Salt: 0.16.0
         Python: 2.6.5 (r265:79063, Oct  1 2012, 22:04:36)
         Jinja2: 2.3.1
       M2Crypto: 0.20.1
 msgpack-python: 0.1.9.final
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
         PyYAML: 3.09
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```

minion versions;

```
# salt-call --versions-report
           Salt: 0.16.0
         Python: 2.7.3 (default, Apr 10 2013, 06:20:15)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```
