### ISSUE TITLE
[BUG] salt.utils.win_network.get_interface_info does not return IPv6 prefix length

### ISSUE THREAD

**Issue by recmanj** [saltstack/salt#61316]
**Description**
Prefix length information for IPv6 addresses is missing for Windows OS and its network interfaces.

**Setup**
- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [X ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

No special configuration needed, should be reproducible on any Windows platform.

  
**Steps to Reproduce the behavior**
```
salt.utils.win_network.get_interface_info()
{
    'Software Loopback Interface 1': {
        'hwaddr': ':::::',
        'inet': [{'address': '127.0.0.1',
                    'broadcast': '127.255.255.255',
                    'gateway': '',
                    'label': 'Software Loopback '
                            'Interface 1',
                    'netmask': '255.0.0.0'}],
        'inet6': [{'address': '::1', 'gateway': ''}],
        'up': True},
    'vmxnet3 Ethernet Adapter #2': {
        'hwaddr': '00:50:56:9C:0B:09',
        'inet': [{'address': '192.168.20.80',
                'broadcast': '192.168.20.255',
                'gateway': '',
                'label': 'vmxnet3 Ethernet Adapter '
                        '#2',
                'netmask': '255.255.255.0'}],
        'inet6': [{'address': 'fe80::498b:9ce0:55c9:4ec1',
                'gateway': ''}],
        'up': True},
    'vmxnet3 Ethernet Adapter #3': {
        'hwaddr': '00:50:56:9C:7D:CC',
        'inet': [{'address': '192.168.2.59',
                'broadcast': '192.168.2.255',
                'gateway': '192.168.2.254',
                'label': 'vmxnet3 Ethernet Adapter '
                        '#3',
                'netmask': '255.255.255.0'}],
        'inet6': [{'address': 'fe80::74fe:9b9a:4c74:3b12',
                'gateway': ''}],
        'up': True}
}
```

**Expected behavior**
Prefix length for IPv6 addressess should be returned:
```
 'vmxnet3 Ethernet Adapter #2': {
        'hwaddr': '00:50:56:9C:0B:09',
        'inet': [{'address': '192.168.20.80',
                'broadcast': '192.168.20.255',
                'gateway': '',
                'label': 'vmxnet3 Ethernet Adapter '
                        '#2',
                'netmask': '255.255.255.0'}],
        'inet6': [
                {'address': 'fe80::498b:9ce0:55c9:4ec1',
                'gateway': '',
                'prefixlen': 64}
        ],
        'up': True}
```

**Screenshots**
None

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.5
      cherrypy: 18.6.0
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2016Server
        system: Windows
       version: 2016Server 10.0.14393 SP0
```
</details>

**Additional context**
Looking at the code, my guess is this has never worked even for older OSes (< Windows 7, still using WMI instead of .NET).
