### ISSUE TITLE
[BUG] Duplicate Keys when deploying Windows 10 Enterprise with Salt-cloud

### ISSUE THREAD

**Issue by j-gerding** [saltstack/salt#61328]
**Description**
I am attempting to automate the deployment of a Windows 10 Enterprise machine using Salt-Cloud on my (virtualized) Proxmox instance. The Proxmox VM and salt-minion will succesfully deploy and no error is returned. 

However, when attempting to contact the new minion, it never returns an answer. 

It does however register two keys, one of which automatically gets denied by the salt-master since the minion already exists.

Manually removing this first key and accepting the second key fixes the problem, but is not a viable solution (since I'm trying to automate this process). 

Another workaround is using version 3003.3 for only my Windows 10 Enterprise machines in which the issue does not present itself. Although a decent workaround, it would be preferable to use 3004 or whatever latest version is available for all of my salt-minions.

If there's any other information that could help, please do let me know.

**Setup**
Proxmox Version: 7.1-7
Salt-Version Master: 3004
PywinRM Version: 0.4.2
SMBProtocol Version: 1.8.3
Windows installer found [here](https://repo.saltproject.io/windows/Salt-Minion-3004-2-Py3-AMD64-Setup.exe)

- [ ] on-prem machine
- [X] VM (In Proxmox, on local machine using QEMU)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Using the following setup with `salt-cloud -m /etc/salt/cloud.maps.d/inframap.conf windows.example.com `
The machine is cloned from a template created with Packer. In this template I preinstall Proxmox/Virtio related drivers, the Windows 10 OS, enabling WinRM/SMB, their ports and setting a static ip.

_salt/cloud.providers.d/proxmox.conf_
```
---
proxmox:
  minion:
    master: 192.168.122.250
  user: exampleuser@pam
  password: examplepass
  url: 192.168.122.3
  driver: proxmox
  verify_ssl: False

```

_salt/cloud.profiles.d/proxmox.conf_
```
#Removed other profiles for brevity
proxmox-windows:
  provider: proxmox
  image: local:910/base-910-disk-0.raw

  clone: True

  clone_description: "Windows 10 Enterprise Machine"

  clone_format: qcow2

  clone_full: 1

  clone_from: 910

  technology: qemu

  host: proxmox

  ip_address: 192.168.122.240

  win_username: Administrator
  win_password: examplepass
 #This .exe is not available by default on the salt-master.
  win_installer: /root/Salt-Minion-3004-2-Py3-AMD64-Setup.exe
  use_winrm: True
  winrm_verify_ssl: False

  onboot: 1
  agent: 1
  ostype: win10
```

This inframap isn't strictly neccesary but included for completion's sake. Simply using the profile with salt-cloud generates the same issue.

_salt/cloud.maps.d/inframap.conf_
```
#Removed other machines for brevity
proxmox-windows:
  - window.example.com:
      clone_name: window.example.com
```

**Expected behavior**
The Windows machine deploys and registers the correct key with the designated salt-master. 

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.26.8
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.26.4
        Python: 3.6.8 (default, Nov  9 2021, 14:44:26)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 8.5 Green Obsidian
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-348.2.1.el8_5.x86_64
        system: Linux
       version: Rocky Linux 8.5 Green Obsidian
```

</details>

**Additional context**
When using version 3003.3 for the Windows machine, the issue is not present.
When attempting the above setup using pypsexec and smbprotocol, only the faulty key is registered to the salt-master. Manually removing this key and restarting the salt-minion does create a functioning environment. However, this is also not a viable solution when attempting to automate this process.

I'm attempting to find the code handling this, however since there is no error being thrown I am having a hard time tracking it down.
