### ISSUE TITLE
[BUG] jinja {% if not salt['file.file_exists']('C:\path\to\file) %} both the 'file.direcotry_exists' and 'file.file_exists' do not work for Windows

### ISSUE THREAD

**Issue by sharkbruhaha** [saltstack/salt#61341]
issue from #55627 
the `directory_exists` and `file_exists` do not work properly on Windows paths

- file exists, so should **not** be executed
`{% if not salt['file.file_exists']('/path/to/file') %}`
**this is executed**
`{% endif %}`

- file exists, so should be executed
`{% if salt['file.file_exists']('/path/to/file') %}`
**this is NOT executed**
`{% endif %}`

Same for `file.directory_exists`

Windows files **are** being correctly detected by `creates:` in `cmd.script` though, so it isn't universal that Windows paths are not being detected properly.

**Comment by OrangeDog** [comment]
How exactly are you specifying the paths? In the description you have Unix-style paths, and in the title you have incorrectly-escaped Windows paths.

**Comment by sharkbruhaha** [comment]
ah, sorry about:
`{% if salt['file.file_exists']('C:\path\to\file') %}`
not sure what you mean about incorrectly escaped though. I do not need to escape the path anywhere else in my jinja or salt (and had it bomb when I had tried thinking I did). Is this call different than other times?

Is that `- unless:` something that exists in every state? I do not recognize it in most of the stuff I've been using.

salt-call --versions:
```
Salt Version:
  Salt: 3003

Dependency Versions:
  cffi: 1.14.5
  cherrypy: 18.6.0
  dateutil: 2.8.1
  docker-py: Not Installed
  gitdb: 4.0.5
  gitpython: Not Installed
  Jinja2: 2.10.1
  libgit2: Not Installed
  M2Crypto: Not Installed
  Mako: 1.1.4
  msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
  pycparser: 2.20
  pycrypto: Not Installed
  pycryptodome: 3.9.8
  pygit2: Not Installed
  Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.6
  PyYAML: 5.3.1
  PyZMQ: 18.0.1
  smmap: 3.0.4
  timelib: 0.2.4
  Tornado: 4.5.3
  ZMQ: 4.3.1

System Versions:
  dist:
  locale: cp1252
  machine: AMD64
  release: 2019
  system: Windows
  version: 2019 10.0.17763 SP0
```
