### ISSUE TITLE
[BUG] user.present shell parameter conflicts with unless/onlyif

### ISSUE THREAD

**Issue by DaAwesomeP** [saltstack/salt#61415]
**Description**
`onlyif` and `unless` always return `false` on `user.present` if `shell` is `/sbin/nologin`.

**Setup**
In the following example, `unless` always applies:
```yaml
add_tempt_user:
  user.present:
    - require:
      - sudo
    - name: temp-user
    - createhome: False
    - usergroup: False
    - groups:
      - sudo
    - system: True
    - shell: /sbin/nologin
    - unless: /usr/bin/test -e /this/file/exists
```
In the following example, `onlyif` never applies:
```yaml
add_tempt_user:
  user.present:
    - require:
      - sudo
    - name: temp-user
    - createhome: False
    - usergroup: False
    - groups:
      - sudo
    - system: True
    - shell: /sbin/nologin
    - onlyif: /usr/bin/test ! -e /this/file/exists
```
In the above case, setting `onlyif` to `/bin/true` still does not cause it to apply.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify): **KVM**
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Simply try out applying one of the above states. I was on Debian 11 x64, but this is theoretically the same on any standard Linux.

**Expected behavior**
I specified `shell` to apply to the user being created, not to apply the shell to the `unless` or `onlyif` command being run. Possibly these attributes conflict in this situation.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: 1.4.0
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-10-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**
Google Group discussion: https://groups.google.com/u/3/g/salt-users/c/2_Ji9_edgA8

**Comment by OrangeDog** [comment]
Can you update the title to e.g. "[BUG] user.present shell parameter conflicts with unless/onlyif"

As a workaround, try a module call instead, which should be more efficient anyway:
```yaml
- unless:
  - fun: file.file_exists
    path: /this/file/exists
```
