### ISSUE TITLE
[BUG] Salt runner mine module fails to get mine with ACLs

### ISSUE THREAD

**Issue by BnGx** [saltstack/salt#61411]
**Description**
The Salt Mine Runner module does not returns any results if the salt mines are covered by minion-side ACLs (probably server side too).

**Setup**
Salt 3004 standard configuration running in a container.
  
**Steps to Reproduce the behavior**
Execute the following shell command:
`salt-run mine.get '*' <any_mine_function>` 

**Expected behavior**
Salt Master should be able to read any salt mine stored in its cache.

**Comment by OrangeDog** [comment]
There is no "standard configuration". Please provide sufficient configuration (e.g. including the ACL config) to reproduce this,
Please also include any relevant logs (possibly at debug level) and the output of `salt --versions`.
See the GitHub issue template if in doubt.

**Comment by waynew** [comment]
I'm not positive, but this looks like it's working as intended, even if it may not be well documented or explained. The `salt-run` works by spinning up a local SMinion (If I got that class right), which is treated like a minion for all intents and purposes.

For this to work the way you expect, it looks like some pretty significant changes would need to be made to the flow.

As far as getting stuff done, the approach that I would take with the current state is to not configure a mine ACL on the minion, ensure that the mine data is being correctly set, and then have the Salt Master ask the minions that *do* have access to get the information, e.g. `salt someminion mine.get acl-minion test.ping`

**Comment by waynew** [comment]
Since there's been no activity I'm going to go ahead and close this - if it's still an issue, please provide the full config so we can try and reproduce the issue.

**Comment by mdschmitt** [comment]
Sorry to necro-bump, but I'm running into the exact same issue.

pillar:
```yaml
mine_functions:
  network.ip_addrs:
    - interface: eth0
    - cidr: 10.0.0.0/8
    - allow_tgt: '*.perf.mydomain.com or master1.mydomain.com'
    - allow_tgt_type: 'compound'
```

I have a few of different environments with similar settings (dev.mydomain.com, etc) with similar settings, but when I run 
I see
`2022-05-17 17:46:49,446 [salt.utils.mine  :42  ][DEBUG   ][7752] Salt mine request from master1.mydomain.com_master for function network.ip_addrs on minion node1.perf.mydomain.com denied." in the debug logs`

I tried adding `or master1.mydomain.com_master` to my allow_tgt line, but no luck.

Is there a way to keep my environments' mine data separate from each other, but also available to the Runner?  If not through the Mine ACL, then how?

I was trying to get some prometheus monitoring to auto-populate inside my pillar as part of using the [prometheus formula](https://github.com/saltstack-formulas/prometheus-formula)
```yaml
...
static_configs:
  - targets:
  #- prometheus1.perf.mydomain.com (commented, trying to replace with mine data)
  #- prometheus2.perf.mydomain.com (commented, trying to replace with mine data)

{% set mine_data = salt['saltutil.runner']('mine.get', tgt='prometheus*', fun='network.ip_addrs', tgt_type='glob') %}
{% for host in mine_data %}
    - {{ host }}
{% endfor %}
```
