### ISSUE TITLE
[BUG] file.keyvalue doesn't match key if there's whitespace before separator

### ISSUE THREAD

**Issue by dethmetaljeff** [saltstack/salt#61428]
**Description**
file.keyvalue does not strip whitespace from "key" so it will not match when there is whitespace between the key and the separator.  

**Setup**
The state I'm using:

```
/etc/security/pwquality.conf:
  file.keyvalue:
    - key_values:
        minlen: 10
        dcredit: -1
        ucredit: -1
        lcredit: 1
        ocredit: 1
        minclass: 1
    - separator: '='
    - uncomment: '# '
    - append_if_not_found: true
```

The file (truncated):
```
# Configuration for systemwide password quality limits
# Defaults:
#
# Number of characters in the new password that must not be present in the
# old password.
# difok = 1
#
# Minimum acceptable size for the new password (plus one if
# credits are not disabled which is the default). (See pam_cracklib manual.)
# Cannot be set to lower value than 6.
# minlen = 8
#
# The maximum credit for having digits in the new password. If less than 0
# it is the minimum number of digits in the new password.
# dcredit = 0
#
```

Please be as specific as possible and give set-up details.

**Steps to Reproduce the behavior**
Run the above state against the file snippet provided.

**Expected behavior**
file.keyvalues will match agains the keys even if there is whitespace between the key and the separator

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.26.8
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: 1.4.6
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: 0.26.4
        Python: 3.6.8 (default, Sep 21 2021, 20:17:36)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 8
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-305.19.1.el8_4.x86_64
        system: Linux
       version: CentOS Linux 8


```
</details>

**Additional context**
Seems like it should be safe enough to strip the key (like it already does for the value) after partitioning the string.

**Comment by teizz** [comment]
@dethmetaljeff I guess handling white-space is always a bit tricky, but in this case isn't your separator technically `" = "` instead of `"="`?

**Comment by dethmetaljeff** [comment]
> @dethmetaljeff I guess handling white-space is always a bit tricky, but in this case isn't your separator technically `" = "` instead of `"="`?

Strictly in this scenario, yes the delimiter is `' = '` which is how I'm handling it today, however I think there should be an option to allow for stripping of whitespace around a delimiter.  Since whitespace is stripped from the value already, I think it's a natural assumption that the same thing happens to the key.

**Comment by leader716** [comment]
I am running into a similar situation 
```
/etc/login.defs:
  file.keyvalue:
    - key_values:
        PASS_MIN_DAYS: 1
        PASS_MAX_DAYS: 60
        PASS_MIN_LEN: 15
        FAIL_DELAY: 4
        UMASK: "077"
        ENCRYPT_METHOD: SHA512
        CREATE_HOME: yes
    - separator: " "
    - count: -1
    - uncomment: "#"
    - append_if_not_found: yes
```

```
UMASK           022
UMASK 077
```
