### ISSUE TITLE
[BUG] Syspaths.py does not expand environment vars for root_dir

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#61445]
**Description**
The new installation paradigm places location information in the registry under a REG_EXPAND_SZ registry type. When syspaths.py gets the root_dir it does not resolve the `%ProgramData%` environment variable. This causes other variables based on `root_dir` to become the following for `pki_dir`:

```
C:\WINDOWS\system32>salt-call --local config.get pki_dir
local:
    C:\WINDOWS\system32\%ProgramData%\Salt Project\Salt\conf\pki\minion
```

**Setup**
Use an environment variable in the root_dir registry key:

```
Key: HKLM:\\SOFTWARE\Salt Project\Salt
name: root_dir
value: %ProgramData%\Salt Project\Salt
```
  
**Steps to Reproduce the behavior**
```
salt-call --local config.get pki_dir
```

**Expected behavior**
Should return:
```
C:\WINDOWS\system32>salt-call --local config.get pki_dir
local:
    C:\ProgramData\Salt Project\Salt\conf\pki\minion
```

**Versions Report**
<details><summary>salt-call --versions-report</summary>

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: 3.1.18
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.19041 SP0 Multiprocessor Free
```
</details>
