### ISSUE TITLE
[BUG] Windows 3004 move config not working for EXE

### ISSUE THREAD

**Issue by bsoldhogg** [saltstack/salt#61485]
**Description**
When running the exe installer from the command line with the /move-config switch, Salt is upgraded, the new registry keys are created but they point to the existing C:\salt locations, root_dir and config_dir are not updated.

The GUI, however, works and will move config if instructed.

**Setup**
I used the provided state from the [salt-winrepo-ng](https://github.com/saltstack/salt-winrepo-ng/blob/master/salt-minion-py3.sls) repo and added the /move-config switch

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
A Windows Server 2019 (2012R2 and 2016 also tested) VM running 3003.3 was used to test the above state against which results in Salt being upgrade but the binaries and config are not moved. Moving to running the installer locally without Salt and with the /minion-name and /master switches, alongside /move-config, the same was observed. In both situations, C:\ProgramData\Salt Project\Salt is created, no files are migrated.

#### When running locally without Salt involved

If I remove **all** switches C:\ProgramData\Salt Project\Salt is created but the config is not migrated, the registry keys are created and point to C:\salt. If I **only** specify /move-config then C:\ProgramData\Salt Project\Salt is not created

When attempting to force configuration to remain in C:\salt by using /master /minion-name and /install-dir, the configuration is moved from C:\salt\conf to C:\ProgramData\Salt Project\Salt\conf - including the pki files - but creates new defaults in C:\salt which then causes the minion key to be denied as coming from the same minion_id

**Expected behavior**
The binaries are expected to be moved to C:\Program Files and config to C:\ProgramData with C:\salt removed

**Versions Report**
<details><summary>salt --versions-report</summary>

#### Master
```
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: 0.26.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: 0.26.2
        Python: 3.6.9 (default, Dec  8 2021, 21:08:43)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5

System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 4.15.0-159-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```
#### Minion

```
Salt Version:
              Salt: 3003.3

    Dependency Versions:
              cffi: 1.14.5
          cherrypy: 18.6.0
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.5
         gitpython: Not Installed
            Jinja2: 2.11.3
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.4
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.20
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
      python-gnupg: 0.4.6
            PyYAML: 5.4.1
             PyZMQ: 18.0.1
             smmap: 3.0.4
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.1

    System Versions:
              dist:
            locale: cp1252
           machine: AMD64
           release: 2012ServerR2
            system: Windows
           version: 2012ServerR2 6.3.9600 SP0
```
</details>

**Additional context**
This may just be the nature of the MSI installer but I am unable to use this inplace of the EXE in the state provided as it uninstalls Salt and seems to kill the installer in the process so you are left in an uninstalled state.

However, performing an upgrade with the MSI installer, outside of any salt state and provided the installer is not inside C:\salt, works and will move the config using MOVE_CONF.
