### ISSUE TITLE
Feature request - Optional glob matching in requisites

### ISSUE THREAD

**Issue by udf2457** [saltstack/salt#61492]
Given the below:

```
foo:
  cmd.run:
    - name: bar
    - watch:
      - /foo/bar/*
```

In the present Salt behaviour, `/foo/bar/*` is a hard glob (i.e. if no state ID or name matches, it will result in an error).

It makes a lot of sense to allow optional globbing.  i.e. in pseudo-code...

```
if exists(/foo/bar/*) {
    do it
} else {
    continue
}
```
