### ISSUE TITLE
[BUG] Cannot override gitfs_disable_saltenv_mapping back to False

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#61524]
**Description**
When `gitfs_disable_saltenv_mapping` is set to `True`, it cannot be overridden per-remote back to `False`.

**Setup**
```yaml
gitfs_disable_saltenv_mapping: true
gitfs_remotes:
  - https://github.com/saltstack-formulas/apt-formula:
    - all_saltenvs: b18a1c8  # v0.10.3
  - https://github.com/private/saltstack:
    - root: salt
    - disable_saltenv_mapping: false
```
  
**Steps to Reproduce the behavior**
Config as above. `fileserver.envs` lists only `base`, even though the `private/saltstack` repo contains multiple branches

**Expected behavior**
Per-remote configuration should work as `False` as well as `True`.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 1.3.0
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.7.1
        Python: 3.8.10 (default, Nov 26 2021, 20:14:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-96-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>
