### ISSUE TITLE
[BUG] "latest" and "latest_snapshot" @ artifactory.downloaded stopped working since python3 upgrade

### ISSUE THREAD

**Issue by tomsolpa** [saltstack/salt#61552]
**Description**
Since upgrading from python2 to python3, "latest" and "latest_snapshot" versions stopped working.

The version is resolved in a bytes format and injected as such in the url used to download, obtaining a 404 error.

**Setup**
Salt-minion : 3003.3, 3004
Python 3.7.3, 3.9.2

**Steps to reproduce**

```
Download archive file from artifactory:
  artifactory.downloaded:
    - artifact:
       artifactory_url: "{{pillar['artifactory_url']}}"
       repository: "{{ pillar['artifactory_repository']}}"
       group_id: "{{ pillar['artifactory_group_id'] }}"
       artifact_id: "{{ pillar['artifactory_artifact_id'] }}"
       packaging: "{{pillar['artifactory_packaging']}}"
       version: "latest"
    - target_file: /var/local/share/file-latest.
```

**Versions Report**

Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-9-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
