### ISSUE TITLE
module.run file.find failed: '<' not supported between instances of 'str' and 'list'

### ISSUE THREAD

**Issue by pankajghadge** [saltstack/salt#61572]
**Description**
In my state we are running file.find using module.run.  Here we are checking log files which are older than 10 days and delete them according by passing delete: f as a option. When there are files to delete then it fails with:
'file.find' failed: '<' not supported between instances of 'str' and 'list'

**Setup**
Need some files older than 10 days or change the value in state files, otherwise it will not produce any error 
```
delete test:
  module.run:
    - file.find:
      - path: /tmp/
      - iname: "*_access_log.*.log"
      - delete: f
      - maxdepth: 1
      - mtime: +10d
      - print: path,size,mtime
```
output: 

```
ID: delete test
   Function: module.run
     Result: False
    Comment: 'file.find' failed: '<' not supported between instances of 'str' and 'list'
    Started: 17:10:34.548267
   Duration: 14.472 ms
    Changes:

```

**Expected behavior**
It should return the file path, size, mtime which are deleted using this state as we have specified in print option. 

**Versions Report**
<details><summary>salt --versions-report</summary>
```
 Salt: 3002.6

Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown

System Versions:
          dist: rhel 8.5 Ootpa
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-348.7.1.el8_5.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.5 Ootpa
```
</details>

**Comment by kymikoloco** [comment]
Just hit this for Windows, the path concatenation (at least according to the log) is perhaps not using the correct slash? I am not sure how to get more debug output from the exception.
```
2022-03-30 10:37:05,762 [salt.utils.find  :604 ][ERROR   ][9680] Exception while executing command "echo rmdir /S /Q C:/Jenkins/workspace\feature_branch_name":

[WinError 2] The system cannot find the file specified
2022-03-30 10:37:56,494 [salt.state       :321 ][ERROR   ][9680] 'file.find' failed: '<' not supported between instances of 'list' and 'str'
```

```yaml
Cleanup:
  module.run:
    - file.find:
      - path: 'C:/Jenkins/workspace'
      - type: d
      - maxdepth: 1
      - mtime: +1d
      - print: path,mtime
      - exec: echo rmdir /S /Q {}
```

**Version Report**
Master
```
Salt Version:
          Salt: 3003.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 3.0.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: 1.1.0
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: 1.0.3
        Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
  python-gnupg: 0.4.5
        PyYAML: 5.4.1
         PyZMQ: 22.2.1
         smmap: 2.0.5
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 4.15.0-153-generic
        system: Linux
       version: Ubuntu 20.04 focal
```

Minion
```
C:\Windows\system32>salt-minion  --versions-report
Salt Version:
          Salt: 3003.2

Dependency Versions:
          cffi: 1.14.5
      cherrypy: 18.6.0
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.13
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.6
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.19041 SP0
```
