### ISSUE TITLE
[BUG] Behaviour of user.present usergroup does not match description of doc

### ISSUE THREAD

**Issue by iils-jschmidt** [saltstack/salt#61581]
**Description**
If you try to create a user with usergroup=True according to the docs a new group should be created with the same name as the user. However, this is not the case, user creation fails. A look at the logs reveals that useradd is called correctly but fails since the group for the -g parameter was never created.

Sidenote, what the gid of the new group would be is not documented, probably the same as the uid? A note about that would be appreciated.

**Steps to Reproduce the behavior**
Use this state:
```
bash:
  pkg.installed: []

sudo:
  pkg.installed: []

testuser:
  user.present:
    - require:
      - pkg: bash
      - pkg: sudo
    - uid: 12345
    - gid: 12345
    - password: asdf
    - home: /home/testuser
    - shell: /bin/bash
    - usergroup: True
    - groups:
      - sudo
      - users
```

**Expected behavior**
The user and the initial group are created as specified by the doc.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.12.2
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 5.9.0-0.bpo.5-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster

```

</details>

**Comment by priyank-R** [comment]
@garethgreenaway Since I've recently worked on a bug related to user.present and written necessary tests, I think I'd be able to work on this one as well. If you don't mind, I'd like to be assigned this bug.

**Comment by priyank-R** [comment]
@jensgw One thing I noticed incorrect is that you're specifying both, a gid as well as usergroup =True 
I tried the following without specifying the gid and a user and its group with the same name was created:
```
testuser:
  user.present:
    - uid: 12345
    - password: asdf
    - home: /home/testuser
    - shell: /bin/bash
    - usergroup: True
    - groups:
      - users
```

Here's the output:

```
          ID: lordxyz
    Function: user.present
      Result: True
     Comment: New user lordxyz created
     Started: 10:04:37.243379
    Duration: 325.712 ms
     Changes:
              ----------
              fullname:
              gid:
                  12345
              groups:
                  - lordxyz
                  - users
              home:
                  /home/testuser
              homephone:
              name:
                  lordxyz
              other:
              passwd:
                  x
              password:
                  XXX-REDACTED-XXX
              roomnumber:
              shell:
                  /bin/bash
              uid:
                  12345
              workphone:
```

To put it simply, you cannot specify gid and usergroup together, it should be either one or the other. 
Adding gid adds the following to the command: `-g 12345` and when you check -g in the man page, you get the following:
`The named group must exist, and a numerical group ID must have an existing entry.`

This is why it was failing.
