### ISSUE TITLE
"AttributeError: module 'salt.utils' has no attribute 'json'" when using vault as local sdb module at the master

### ISSUE THREAD

**Issue by uwerler** [saltstack/salt#61627]
**Description**
When configuring vault as a sdb module in the master config the master can't be started and the sdb runner for vault fails with:
AttributeError: module 'salt.utils' has no attribute 'json'

**Setup**
master,d/vault.conf:

```
vault:
  url: https://vault.example.com
  verify: /etc/salt/example.com.pem
  policies:
    - saltstack/minions
    - saltstack/minion/{minion}
  auth:
    method: approle
    role_id: <redacted>
    secret_id: <redacted>
    
myvault:
  driver: vault
```
e.g. ext_pillar.conf

```
foreman.password: sdb://myvault/infrastructure/foreman/password
```
  
**Steps to Reproduce the behavior**
See above.

**Expected behavior**
Getting data from vault to be able to start master or getting data via salt-run:
e.g.:
```
salt-run sdb.get 'sdb://myvault/infrastructure/foreman?password'
<redacted>
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3004
 
Dependency Versions:
           cffi: 1.15.0
       cherrypy: unknown
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: 4.0.5
      gitpython: 3.1.14
         Jinja2: 3.0.3
        libgit2: 1.3.0
       M2Crypto: Not Installed
           Mako: Not Installed
        msgpack: 1.0.3
   msgpack-pure: Not Installed
   mysql-python: Not Installed
      pycparser: 2.21
       pycrypto: Not Installed
   pycryptodome: 3.14.1
         pygit2: 1.7.2
         Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
   python-gnupg: Not Installed
         PyYAML: 6.0
          PyZMQ: 21.0.2
          smmap: 4.0.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.3
 
Salt Extensions:
 saltext.vmware: 21.12.15.0rc1
 
System Versions:
           dist: debian 11 bullseye
         locale: utf-8
        machine: x86_64
        release: 5.10.0-8-amd64
         system: Linux
        version: Debian GNU/Linux 11 bullseye

```
</details>

**Fix**
import salt.utils.json into salt.utils.vault.py
