### ISSUE TITLE
[TECH DEBT] Add ability to use yaml dictionaries instead of arrays in Salt SLS files

### ISSUE THREAD

**Issue by MurzNN** [saltstack/salt#61649]
### Description of the tech debt to be addressed, include links and screenshots
I always got confused when Salt SLS files use lists (arrays) for key-value structures, instead of dictionaries, like this:
```yaml
kubernetes_repo:
  pkgrepo.managed:
    - humanname: kubernetes
    - name: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
    - file: /etc/apt/sources.list.d/kubernetes.list
    - key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
```

I think that using dictionaries should be much easier, here is an example:
```yaml
kubernetes_repo:
  pkgrepo.managed:
    humanname: kubernetes
    name: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
    file: /etc/apt/sources.list.d/kubernetes.list
    key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
```
And this way should automatically get rid of key duplicates in YAML parser side (and even see such errors immediately in YAML editors)! Because now we can got mistakes with duplicates without errors in yaml format, like this:
```yaml
kubernetes_repo:
  pkgrepo.managed:
    - humanname: kubernetes
    - name: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
    - file: /etc/apt/sources.list.d/kubernetes.list
    - key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - name: 'kubernetes_repo'
```

Also it'll be much easier on server side to use native dictionary from YAML, without converting arrays to dictionary in code, so maybe it even simplify the code and slightly improve performance?

So this will make SLS files looks more structured and less confusing for newbies, without deep changing of core logic. Also it makes they looks more similar to Ansible yaml format, so that even can give us additional clients from Ansible country ;-) Puppet Manifests, Chef Recipes use dictionaries instead of arrays in such places too.

To not broke the previous behavior, we can implement this as option and implement support of both formats, and recommend in docs (or in best practices articles) to use new dict format instead of old arrays.

### Versions Report
Salt: 3004

**Comment by MurzNN** [comment]
Even if we must have several values of single dictionary key, we can use it as inner array, like this:
```yaml
/etc/foo.conf:
  file.managed:
    source:
      - salt://foo.conf.{{ grains['fqdn'] }}
      - salt://foo.conf.fallback
    user: foo
    group: users
    mode: 644
    attrs: i
    backup: minion
```
