### ISSUE TITLE
[DOCS]

### ISSUE THREAD

**Issue by pepoluan** [saltstack/salt#61671]
**Description**
`pkgrepo.managed` might refuse to pull key if `keyserver` only specifies domain name; `hkp://` and port must be explicitly mentioned. E.g.:

```yaml
mariadb-repo:
  pkgrepo.managed:
    - humanname: MariaDB Repo
    - name: "deb [arch=amd64,arm64,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu focal main"
    - dist: focal
    - file: /etc/apt/sources.list.d/mariadb.list
    - keyid: "0xF1656F24C74CD1D8"
    - keyserver: keyserver.ubuntu.com
```

👆 The above might result in `gpg: keyserver receive failed: End of file` error.

In such case, try:

```yaml
mariadb-repo:
  pkgrepo.managed:
    - humanname: MariaDB Repo
    - name: "deb [arch=amd64,arm64,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu focal main"
    - dist: focal
    - file: /etc/apt/sources.list.d/mariadb.list
    - keyid: "0xF1656F24C74CD1D8"
    - keyserver: "hkp://keyserver.ubuntu.com:80"
```

**Suggested Fix**
A note in the [documentation for pkgrepo.managed](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.pkgrepo.html) about trying using the `hkp://` syntax.

**Type of documentation**
Salt documentation.

Probably other locations, too?

**Location or format of documentation**
https://docs.saltproject.io/en/latest/ref/states/all/salt.states.pkgrepo.html
