### ISSUE TITLE
[BUG] Failed to authenticate on GitFS using pygit2 when using several Github sources

### ISSUE THREAD

**Issue by albert-cintas-pot** [saltstack/salt#61670]
**Description**
I am able to make GitFS with pygit2 work for one source for both storing the states and pillars in a Github repository, but once I add a second GitHub repository to also use as fileserver I get the following error when Salt is trying to authenticate to the second repo:

```
[ERROR   ] Error occurred fetching gitfs remote 'git@github.com:[REDACTED]/[REDACTED].git': Failed to authenticate SSH session: Callback returned error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1870, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib/python3/dist-packages/pygit2/remote.py", line 405, in fetch
    check_error(err)
  File "/usr/lib/python3/dist-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: Failed to authenticate SSH session: Callback returned error
```
I am able to make it work for many sources using GitPython and a config file inside the `.ssh` folder, but the method doesn't work for pygit2 either.

**Setup**
Error happens in a cloud server (either in EC2 or GCE), running `Ubuntu 18.04`.
The salt master config is the following:
```
################ File and pillar roots ################
state_top_saltenv: base
pillarenv_from_saltenv: True

# GitFS
fileserver_backend:
  - gitfs

gitfs_remotes:
  # Salt states repo
  - git@github.com:[REDACTED]/[REDACTED].git:
    - base: main
    - root: states
    - update_interval: 30
    - pubkey: /root/.ssh/id_rsa.pub
    - privkey: /root/.ssh/id_rsa

  - git@github.com:[REDACTED]/[REDACTED].git:
    - base: main
    - update_interval: 300
    - pubkey: /root/.ssh/whatever_id_rsa.pub
    - privkey: /root/.ssh/whatever_id_rsa

# Git Pillar
git_pillar_update_interval: 30
ext_pillar:
  - git:
    - main git@github.com:[REDACTED]/[REDACTED].git:
      - root: pillars
      - env: base
      - pubkey: /root/.ssh/id_rsa.pub
      - privkey: /root/.ssh/id_rsa
```
  
**Steps to Reproduce the behavior**
Just install a brand new salt-master and try to get it to authenticate using pygit2 to several different Github repositories.

**Expected behavior**
First Github repo authenticates correctly and the fileserver cache updates correctly. For the second one you get above's error.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: 0.26.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: 0.26.2
        Python: 3.6.9 (default, Dec  8 2021, 21:08:43)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-1064-gcp
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```
</details>

**Additional context**
I've tried making this run using latest pip3 install of pygit2 but I have the same problem.
