### ISSUE TITLE
[BUG] module.run doesnt run multiple times in one state

### ISSUE THREAD

**Issue by Dudek-AMS** [saltstack/salt#61688]
**Description**
We try to run two times xml.set_attribute in a state with new module.run style - but only the last is executed

**Setup**
```yaml
'{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }}/apache-tomcat/conf/server.xml-setProxy':
  module.run:
    - xml.set_attribute:
      - file: '{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }}/apache-tomcat/conf/server.xml'
      - element: './/Service[@name="Catalina"]/Connector'
      - key: 'proxyPort'
      - value: '443'
    - xml.set_attribute:
      - file: '{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }}/apache-tomcat/conf/server.xml'
      - element: './/Service[@name="Catalina"]/Connector'
      - key: 'scheme'
      - value: 'https'
```

  
**Steps to Reproduce the behavior**
see sls
     

**Expected behavior**
Setting both xml attributes

**Screenshots**

**Versions Report**
<details><summary>Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: 0.27.7
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 0.27.4
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster</summary>
</details>

**Comment by OrangeDog** [comment]
I'm guessing this is due to the internal structure still being a dict rather than a list.

You can workaround by using two separate states:

```sls
'{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }} proxyPort':
  module.run:
    - xml.set_attribute:
      - file: '{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }}/apache-tomcat/conf/server.xml'
      - element: './/Service[@name="Catalina"]/Connector'
      - key: 'proxyPort'
      - value: '443'

'{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }} scheme':
    - xml.set_attribute:
      - file: '{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }}/apache-tomcat/conf/server.xml'
      - element: './/Service[@name="Catalina"]/Connector'
      - key: 'scheme'
      - value: 'https'
```

Though rather than individually setting each key every run, you should probably use e.g. `file.managed` to template the whole file statefully.

**Comment by Dudek-AMS** [comment]
This is what we had before in legacy style. 
The file is created by a third party product (Atlassian Crowd) and we don't want to maintain the whole file seperatly - so thats why we don't want to use file.managed to template it

**Comment by waynew** [comment]
This is actually how Salt *always* operates.

You can't have two states of the same kind with one ID:

```
❯ cat error.sls
do something:
  test.nop:
    - comment: nope
  test.succeed_without_changes:
    - comment: also nope

~/salt via 🐍 v3.10.2 (salt) on ☁️  (us-west-2)
❯ salt-call state.apply error
local:
    Data failed to compile:
----------
    ID 'do something' in SLS 'error' contains multiple state declarations of the same type
``` 

100% and always this is not how to work with Salt.

There's already an [XML state](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.xml.html) that *should* do what you want. It looks like you've already got the xpath that you want to set, so something like this *should* work:

```
'{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }} proxyPort':
  xml.value_present:
    - name: '{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }}/apache-tomcat/conf/server.xml'
    - xpath: './/Service[@name="Catalina"]/Connector/proxyPort'   # not 100% sure on this xpath
    - value: 443
  
'{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }} scheme':
  xml.value_present:
    - name: '{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }}/apache-tomcat/conf/server.xml'
    - element: './/Service[@name="Catalina"]/Connector/scheme'   # not 100% sure on this xpath
    - value: https
```      

If that doesn't work out of the box, feel free to ask for help on one of our community resources:

- [#salt on libera chat](https://web.libera.chat/#salt)
- [Salt Users email list](https://groups.google.com/forum/#!forum/salt-users)
- [Salt Community Slack](https://saltstackcommunity.slack.com/)
