### ISSUE TITLE
[FEATURE REQUEST] module xml set_attribute(s)

### ISSUE THREAD

**Issue by Dudek-AMS** [saltstack/salt#61700]
**Is your feature request related to a problem? Please describe.**
Regarding this BUG https://github.com/saltstack/salt/issues/61688 - the better solution in this special case (same file to edit) is to extend/add function to allow multiple manipulations of the xml file.

**Describe the solution you'd like**
add another function:
xml.set_attributes
```yaml
manipulate files:
manipulate files:
    module.run:
    - xml.set_attributes:
        - set_port:
            - file: '{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }}/apache-tomcat/conf/server.xml'
            - element: './/Service[@name="Catalina"]/Connector'
            - key: 'proxyPort'
            - value: '443'
        - set_scheme:
            - file: '{{ pillar["crowd"]["installation_path"] }}/{{ pillar["crowd"]["app_name"] }}/apache-tomcat/conf/server.xml'
            - element: './/Service[@name="Catalina"]/Connector'
            - key: 'proxyPort'
            - value: '443'
```

**Describe alternatives you've considered**

**Additional context**
set_port // set_scheme is here just a internal name which increases readability
