### ISSUE TITLE
[BUG] salt runner doesn't store results in job cache

### ISSUE THREAD

**Issue by aaronknister** [saltstack/salt#61729]
**Description**
Salt runners don't appear to store results in the job cache. This worked on older versions of salt (~2015 time frame at least).

Querying the result of a salt runner job shows an Error and it's missing expected attributes such as Function:

```
20220226004548285855:
    ----------
    Error:
        Cannot contact returner or no job with this jid
    Result:
        ----------
        02f3db77ee3b_master:
            ----------
            return:
                ----------
                _stamp:
                    2022-02-26T00:45:48.861710
                fun:
                    runner.jobs.list_jobs
                fun_args:
                jid:
                    20220226004548285855
                return:
                    ----------
                success:
                    True
                user:
                    root
    StartTime:
        2022, Feb 26 00:45:48.285855
```

**Setup**

Observed on the salt 3004rc1 container and the tip of master (run inside a container).

Please be as specific as possible and give set-up details.
  
**Steps to Reproduce the behavior**
 
salt-run -l info jobs.list_jobs 2>&1 | grep 'Runner completed' | awk '{ print $5 }' | xargs --no-run-if-empty -n1 salt-run  jobs.print_job

**Expected behavior**
Output should not contain an Error field and should contain Function attribute (and others) as shown below:
```
20220225164405632844:
    ----------
    Arguments:
    Function:
        runner.jobs.print_job
    Minions:
    Result:
        ----------
        wos-s3-231-node1_master:
            ----------
            return:
                ----------
                _stamp:
                    2022-02-26T00:44:05.987420
                fun:
                    runner.jobs.print_job
                jid:
                    20220225164405632844
                return:
                    ----------
                    1:
                        ----------
                        Arguments:
                        Function:
                            unknown-function
                        Result:
                            ----------
                        StartTime:
                        Target:
                            unknown-target
                        Target-type:
                        User:
                            root
                success:
                    True
                user:
                    root
    StartTime:
        2022, Feb 25 16:44:05.632844
    Target:
        wos-s3-231-node1_master
    Target-type:
    User:
        root
```

**Screenshots**
Console output included above

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3003rc1+1813.gf65f953

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 7 Core
        locale: ANSI_X3.4-1968
       machine: x86_64
       release: 3.10.0-514.21.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Additional context**
None at this time
