### ISSUE TITLE
[BUG] for-loop is fetching string list incorrectly

### ISSUE THREAD

**Issue by cmonty14** [saltstack/salt#61733]
**Description**
I defined a state that should delete a specific file in any mountpoint.
To identify the relevant mountpoints I use this bash-command:
`findmnt -m | grep -E 'autofs|xfs|nfs' | cut -d ' ' -f 1 | sort -u`

However salt does not identify the directory string correctly.

**Setup**
```yaml
{% set mountpoints_list = salt['cmd.shell']("findmnt -m | grep -E 'autofs|xfs|nfs' | grep -v proc | cut -d ' ' -f 1 | sort -u") %}

{% for dir in mountpoints_list %}
{{ dir }}/DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent
{% endfor %}
```
  
**Steps to Reproduce the behavior**
<details><summary>debug-log</summary>

```
[DEBUG   ] stdout: /hana/data
/hana/log
/hana/shared
/mnt/backup_db_lve
/net/sapmnt.dlm.autodelete30days
/net/sapmnt.dlm.autodelete7days
/net/sapmnt.dlm.lve
/net/sapmnt.dlm.production.auto
/net/sapmnt.dlm.services.basis
/net/sapmnt.dlm.services.database
/net/sapmnt.dlm.services.servermgmnt
/sapmnt/C11
/sapmnt/HOME
/sapmnt/av
/sapmnt/depot
/sapmnt/dlm
/sapmnt/imtoolspub
/sapmnt/linuxadmin
/sapmnt/production/newdb/NewDB200
/usr/sap
[DEBUG   ] output: /hana/data
/hana/log
/hana/shared
/mnt/backup_db_lve
/net/sapmnt.dlm.autodelete30days
/net/sapmnt.dlm.autodelete7days
/net/sapmnt.dlm.lve
/net/sapmnt.dlm.production.auto
/net/sapmnt.dlm.services.basis
/net/sapmnt.dlm.services.database
/net/sapmnt.dlm.services.servermgmnt
/sapmnt/C11
/sapmnt/HOME
/sapmnt/av
/sapmnt/depot
/sapmnt/dlm
/sapmnt/imtoolspub
/sapmnt/linuxadmin
/sapmnt/production/newdb/NewDB200
/usr/sap
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/manager_org_1/stc-all-cleanup-DO_NOT_DELETE_THIS_DIRECTORY/init.sls' using 'jinja' renderer: 0.02614903450012207
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/manager_org_1/stc-all-cleanup-DO_NOT_DELETE_THIS_DIRECTORY/init.sls:



//DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent

h/DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent

a/DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent

n/DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent

a/DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent

//DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent

d/DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent

a/DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent

t/DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent

a/DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent


/DO_NOT_DELETE_THIS_DIRECTORY:
  file.absent

```
</details>

**Expected behavior**
The following files should be deleted:
```
/hana/data/DO_NOT_DELETE_THIS_DIRECTORY
/hana/log/DO_NOT_DELETE_THIS_DIRECTORY
/hana/shared/DO_NOT_DELETE_THIS_DIRECTORY
/mnt/backup_db_lve/DO_NOT_DELETE_THIS_DIRECTORY
/net/sapmnt.dlm.autodelete30days/DO_NOT_DELETE_THIS_DIRECTORY
/net/sapmnt.dlm.autodelete7days/DO_NOT_DELETE_THIS_DIRECTORY
/net/sapmnt.dlm.lve/DO_NOT_DELETE_THIS_DIRECTORY
/net/sapmnt.dlm.production.auto/DO_NOT_DELETE_THIS_DIRECTORY
/net/sapmnt.dlm.services.basis/DO_NOT_DELETE_THIS_DIRECTORY
/net/sapmnt.dlm.services.database/DO_NOT_DELETE_THIS_DIRECTORY
/net/sapmnt.dlm.services.servermgmnt/DO_NOT_DELETE_THIS_DIRECTORY
/sapmnt/C11/DO_NOT_DELETE_THIS_DIRECTORY
/sapmnt/HOME/DO_NOT_DELETE_THIS_DIRECTORY
/sapmnt/av/DO_NOT_DELETE_THIS_DIRECTORY
/sapmnt/depot/DO_NOT_DELETE_THIS_DIRECTORY
/sapmnt/dlm/DO_NOT_DELETE_THIS_DIRECTORY
/sapmnt/imtoolspub/DO_NOT_DELETE_THIS_DIRECTORY
/sapmnt/linuxadmin/DO_NOT_DELETE_THIS_DIRECTORY
/sapmnt/production/newdb/NewDB200/DO_NOT_DELETE_THIS_DIRECTORY
/usr/sap/DO_NOT_DELETE_THIS_DIRECTORY

```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.15 (default, Sep 15 2021, 14:20:42) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: sles 15.2 n/a
        locale: UTF-8
       machine: x86_64
       release: 5.3.18-24.99-default
        system: Linux
       version: SLES 15.2 n/a

```
</details>
