### ISSUE TITLE
[BUG] lgpo.set fails to properly update "Debug programs" policy

### ISSUE THREAD

**Issue by buzzdeee** [saltstack/salt#61740]
**Description**
I want to remove the default Administrators group from "Debug Programs", to eventually end up with an empty list there.

This is the policy.sls I apply:
```
client-policy:
  lgpo.set:
    - computer_policy:
        Debug programs: []
```

state.apply works without error/warning, but nothing changes on the client.

```
----------
          ID: client-policy
    Function: lgpo.set
      Result: True
     Comment: All specified policies are properly configured
     Started: 23:44:33.112698
    Duration: 0.0 ms
     Changes:           
----------

```

afterward, running lgpo.get I still get:

```
...
        Debug programs:
            - BUILTIN\Administrators
...
```

And I also can verify that running secpol, the Administrators group is still listed there.

When I manually remove the Administrators group, and run lgpo.get against the client then it looks like:

```
...
        Debug programs:
...

```

just this single line regarding Debug programs.

I tried different things in my policy.sls to try to remove the Administrators, alike:

```
Debug programs:

OR

Debug programs: ''

OR

Debug programs:
   - 

OR

Debug programs:
   - ''

```

but I only ended up with different exceptions from salt, most of the time that the NoneType is not iterable.

**Setup**

- [X] on-prem machine (The client)
- [X ] VM (The server is on KVM)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
After applying the policy, the "Debug programs" should be empty, not containing anything.

**Versions Report**
Salt Master version:

```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Nov 26 2021, 20:14:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-74-generic
        system: Linux
       version: Ubuntu 20.04 focal
```

Salt client version:

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.19041 SP0 Multiprocessor Free
```

</details>

**Additional context**
out of curiosity I tried to change the list to some other user, updated the policy.sls to look alike:

```
client-policy:
  lgpo.set:
    - computer_policy:
        Debug programs:
             - mydomain\user
```

applying this, resulted in:

```
     Changes:   
              ----------
              new:
                  ----------
                  Computer Configuration:
                      ----------
                      Debug programs:
                          - BUILTIN\Administrators
                          - mydomain\user
              old:
                  ----------
                  Computer Configuration:
                      ----------
                      Debug programs:
                          - BUILTIN\Administrators
```

I'd rather have expected to only have the mydomain\user in the list, but not the Administrators
