### ISSUE TITLE
[BUG] MWorkerQueue process at 100% CPU blocking whole setup

### ISSUE THREAD

**Issue by afischer-opentext-com** [saltstack/salt#61742]
**Description**

This morning we had an incident/outage with one of our salt-masters. One of the ZeroMQ workers went on the rampage and consumed a full CPU Core while at the same time blocked the whole salt master setup. It was not possible to pass any further salt command (tested salt, salt-run and salt-api calls). While this happened there were about 450 ESTABLISHED tcp connections for/from the connected minions.

**Setup**

The salt-master (3004) is running on an Amazon Linux 2 within an Alpine 3.15 docker container. 
  
**Steps to Reproduce the behavior**

Unclear.

**Expected behavior**

a ZeroMQ worker ideally does not eat up all CPU and does not block other workers.

**Screenshots**

![2022-03-01_10h26_07](https://user-images.githubusercontent.com/37439392/156175385-a3eb254a-d69c-44ed-a04a-69dc19145286.png)

**Versions Report**
<details>

<summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.8.0
        Python: 3.9.7 (default, Nov 24 2021, 21:15:59)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 21.0.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: alpine 3.15.0
        locale: utf-8
       machine: x86_64
       release: 4.14.225-121.357.amzn1.x86_64
        system: Linux
       version: Alpine Linux 3.15.0
```
</details>

**Config Report**
<details>

<summary>cat /etc/salt/master</summary>

```yaml
---
con_cache: true
gather_job_timeout: 120
pillar_merge_lists: true
pillar_source_merging_strategy: none
pillarenv_from_saltenv: true
recon_max: 30000
recon_randomize: true
rest_cherrypy:
  collect_stats: true
  disable_ssl: true
  port: 8000
  socket_queue_size: 300
  thread_pool: 300
rest_timeout: 7200
sock_pool_size: 16
timeout: 120
worker_threads: 8
```
</details>

**Additional context**

I would like to know what would be needed to further troubleshoot the situation and optionally of course ideally would like to have this fixed. 

It was surprising to see one worker blocking the whole setup. I am somewhat hesitated to enable zeromq_monitor as it might further increase the load and it spams the regular log file, which is not ideal as well. Additionally I am unable to interpret it. 

As we conitnue to see zeromq to be somewhat unstable, what is the status of the tcp transport? Is it considered stable these days?
