### ISSUE TITLE
[BUG] Custom grains not available on minion

### ISSUE THREAD

**Issue by cmonty14** [saltstack/salt#61767]
**Description**
After writing a custom grains located in _/srv/salt/_grains_ and distributing it to a single minion the modules are not available.
There's no error executing commands related to grains, therefore I conclude that the python coding of my custom grains is correct.

```
salt-master:/srv/salt/_grains # salt 'vlccits5.devsys.net.sap' saltutil.sync_all
vlccits5.devsys.net.sap:
    ----------
    beacons:
    clouds:
    engines:
    executors:
    grains:
        - grains.sapinfo
    log_handlers:
    matchers:
    modules:
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    serializers:
    states:
    thorium:
    utils:
salt-master:/srv/salt/_grains # salt 'vlccits5.devsys.net.sap' saltutil.refresh_grains
vlccits5.devsys.net.sap:
    True

```

**Setup**
<details><summary>custom grains 'sapinfo.py'</summary>

```python
import re


def sap_id():
    """
    Returns SAP System ID [sid].
    """
    with open("/usr/sap/sapservices", "rt") as file:
        return re.search("^\s*LD_LIBRARY_PATH.+\s+-u\s*(\w+)adm", file.read(), flags=re.MULTILINE).group(1)


def sap_kernel_release():
    """
    Returns SAP Kernel release.
    """
    SID = sap_id().upper()
    with open(f"/usr/sap/{SID}/SYS/exe/uc/linuxx86_64/sapmanifest.mf", "rt") as file:
        return int(re.search(r"^kernel release:(.+)$", file.read(), flags=re.MULTILINE).group(1))


def sap_kernel_patch_number():
    """
    Returns SAP Kernel patch number.
    """
    SID = sap_id().upper()
    with open(f"/usr/sap/{SID}/SYS/exe/uc/linuxx86_64/sapmanifest.mf", "rt") as file:
        return int(re.search(r"^kernel patch number:(.+)$", file.read(), flags=re.MULTILINE).group(1))

```
</details>

  
**Steps to Reproduce the behavior**

1. Create grains /srv/salt/_grains/sapinfo.py
2. `salt-master:~ #salt 'vlccits5.devsys.net.sap' saltutil.sync_all`
3. `salt-master:~ #salt 'vlccits5.devsys.net.sap' saltutil.refresh_grains`
4. `vlccits5:~ # salt-call --local grains.ls | grep sap`

**Expected behavior**
The output of `salt-call --local grains.ls | grep sap` should list all functions defined with naming _sap_<name>_

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.28.4
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: 3.9.0
  pycryptodome: Not Installed
        pygit2: 0.28.2
        Python: 3.6.15 (default, Sep 15 2021, 14:20:42) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: sles 15.2 n/a
        locale: UTF-8
       machine: x86_64
       release: 5.3.18-24.102-default
        system: Linux
       version: SLES 15.2 n/a

```
</details>
