### ISSUE TITLE
[BUG] pkg.uptodate (state) and pkg.upgrade (module) do not perform actual update on ubuntu (apt) systems.

### ISSUE THREAD

**Issue by kipje91** [saltstack/salt#61776]
**Description**
Running pkg.uptodate state or pkg.upgrade module on Ubuntu (apt) does not update the packages.
Tested on both Ubuntu 20.04 LTS and Ubuntu 18.04 LTS, both have the same result.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
sls:
```
update-packages:
  pkg.uptodate:
    - refresh: True
``` 

output:
```
----------
          ID: update-packages
    Function: pkg.uptodate
      Result: True
     Comment: Upgrade ran successfully
     Started: 13:35:21.008346
    Duration: 8186.694 ms
     Changes:
```
```apt list --upgradable
Listing... Done
fwupd-signed/focal-updates 1.27.1ubuntu5+1.5.11-0ubuntu1~20.04.2 amd64 [upgradable from: 1.27.1ubuntu2+1.3.11-1~focal1]
fwupd/focal-updates 1.5.11-0ubuntu1~20.04.2 amd64 [upgradable from: 1.3.11-1~focal1]
```

Same for doing pkg.upgrade, listing them goes well. Upgrading does not.
salt-call pkg.list_upgrade:
``` 
local:
    ----------
    fwupd:
        1.5.11-0ubuntu1~20.04.2
    fwupd-signed:
        1.27.1ubuntu5+1.5.11-0ubuntu1~20.04.2
```
salt-call pkg.upgrade:

```
local:
    ----------
```
Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify)
- [X] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**

**Expected behavior**
I would like to see all pending packages (seen with apt list --upgradable) be installed.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Nov 26 2021, 20:14:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.11.0-1021-azure
        system: Linux
       version: Ubuntu 20.04 focal

```
</details>

**Additional context**
