### ISSUE TITLE
[BUG] Deltaproxy: Long/Non-linear setup time. 

### ISSUE THREAD

**Issue by n-holmstedt** [saltstack/salt#61805]
**Description**
I'm trying to host 32 proxy-minions in a delta-proxy process. The setup time is more than 10minutes. It seems like the master is re-rendering pillar for all the minions currently connected to to the master from the deltaproxy. 

deltaproxy-1 connects to the master, its pillar is rendered.
rectifier-1 connects to the master, its pillar is rendered plus the pillar of deltaproxy-1
rectifier-2 connects to the master, its pillar is rendered plus the pillar of deltaproxy-1, rectifier 1
rectifier-3 connects to the master, its pillar is rendered plus the pillar of deltaproxy-1, rectifier 1, rectifier 2
The time it takes between two renderings is about 1s. This would be:  Σ i*1s = 561s with 32 minions plus deltaproxy. which is about the setuptime that i'm looking at.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [x] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

Using the official docker image, running on a Redhat 8.2 VM. 
1x Master container
1x Deltaproxy container running 32x proxy-minions with connections to http-interfaces. 

top.sls
```yaml
base:
  'delta*':
    - deltaproxy
  'e*':
    - eltek
```
deltaproxy.sls
```yaml
proxy:
  proxytype: deltaproxy

  ids:
    - eltek-10.128.103.139
    - eltek-10.128.103.166
    - eltek-10.128.98.140
    - eltek-10.128.99.34
    #... 32 minions
``` 
eltek.sls
```yaml
proxy:
  {% set ip = opts.id|replace("eltek-", "") %}
  proxytype: eltek_rectifier
  username: <username>
  password: <password>
  url: http://{{ ip }}/
  proxy_keep_alive_interval: 4
```
**Steps to Reproduce the behavior**

Trimmed debug logs:
```
rect-master  | 2022-03-17T08:12:40.425825791Z [INFO    ] Setting up the Salt Master

rect-master  | 2022-03-17T08:12:43.301623895Z [DEBUG   ] compound_match delta_proxy ? "delta*" => "True"
rect-master  | 2022-03-17T08:12:43.308040417Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/deltaproxy.sls:

rect-master  | 2022-03-17T08:12:44.102964475Z [INFO    ] Authentication request from eltek-10.128.103.139
rect-master  | 2022-03-17T08:12:44.103180831Z [INFO    ] Authentication accepted from eltek-10.128.103.139
rect-master  | 2022-03-17T08:12:44.209308520Z [DEBUG   ] compound_match eltek-10.128.103.139 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:44.213216500Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/eltek.sls:

rect-master  | 2022-03-17T08:12:44.740150444Z [DEBUG   ] compound_match delta_proxy ? "delta*" => "True"
rect-master  | 2022-03-17T08:12:44.753181668Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/deltaproxy.sls:

rect-master  | 2022-03-17T08:12:45.488217634Z [DEBUG   ] compound_match eltek-10.128.103.139 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:45.491816260Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/eltek.sls:

rect-master  | 2022-03-17T08:12:46.558525115Z [INFO    ] Authentication request from eltek-10.128.103.166
rect-master  | 2022-03-17T08:12:46.558541720Z [INFO    ] Authentication accepted from eltek-10.128.103.166
rect-master  | 2022-03-17T08:12:46.656550969Z [DEBUG   ] compound_match eltek-10.128.103.166 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:46.660096019Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/eltek.sls:

rect-master  | 2022-03-17T08:12:47.162810981Z [DEBUG   ] compound_match delta_proxy ? "delta*" => "True"
rect-master  | 2022-03-17T08:12:47.171154101Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/deltaproxy.sls:

rect-master  | 2022-03-17T08:12:47.897208523Z [DEBUG   ] compound_match eltek-10.128.103.139 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:47.900922659Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/eltek.sls:

rect-master  | 2022-03-17T08:12:48.920556018Z [DEBUG   ] compound_match eltek-10.128.103.166 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:48.923023979Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/eltek.sls:

rect-master  | 2022-03-17T08:12:50.028183243Z [INFO    ] Authentication request from eltek-10.128.98.140
rect-master  | 2022-03-17T08:12:50.028296027Z [INFO    ] Authentication accepted from eltek-10.128.98.140
rect-master  | 2022-03-17T08:12:50.119928249Z [DEBUG   ] compound_match eltek-10.128.98.140 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:50.122357794Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/eltek.sls:

rect-master  | 2022-03-17T08:12:50.595144036Z [DEBUG   ] compound_match delta_proxy ? "delta*" => "True"
rect-master  | 2022-03-17T08:12:50.600170244Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/deltaproxy.sls:

rect-master  | 2022-03-17T08:12:51.618493585Z [DEBUG   ] compound_match eltek-10.128.103.139 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:51.620990062Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/eltek.sls:

rect-master  | 2022-03-17T08:12:52.611120420Z [DEBUG   ] compound_match eltek-10.128.103.166 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:52.615123247Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/eltek.sls:

rect-master  | 2022-03-17T08:12:53.613226513Z [DEBUG   ] compound_match eltek-10.128.98.140 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:53.613492877Z [DEBUG   ] compile template: /etc/salt/pillar/eltek.sls

rect-master  | 2022-03-17T08:12:54.540989442Z [INFO    ] Authentication request from eltek-10.128.99.34
rect-master  | 2022-03-17T08:12:54.541006331Z [INFO    ] Authentication accepted from eltek-10.128.99.34
rect-master  | 2022-03-17T08:12:54.633158502Z [DEBUG   ] compound_match eltek-10.128.99.34 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:54.633161843Z [DEBUG   ] compile template: /etc/salt/pillar/eltek.sls

rect-master  | 2022-03-17T08:12:55.197925160Z [DEBUG   ] compound_match delta_proxy ? "delta*" => "True"
rect-master  | 2022-03-17T08:12:55.204295120Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/deltaproxy.sls:

rect-master  | 2022-03-17T08:12:55.954047346Z [DEBUG   ] compound_match eltek-10.128.103.139 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:55.956866932Z [DEBUG   ] Rendered data from file: /etc/salt/pillar/eltek.sls:

rect-master  | 2022-03-17T08:12:56.943289968Z [DEBUG   ] compound_match eltek-10.128.103.166 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:56.943535022Z [DEBUG   ] compile template: /etc/salt/pillar/eltek.sls

rect-master  | 2022-03-17T08:12:57.972278766Z [DEBUG   ] compound_match eltek-10.128.98.140 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:57.972547250Z [DEBUG   ] compile template: /etc/salt/pillar/eltek.sls

rect-master  | 2022-03-17T08:12:58.971021713Z [DEBUG   ] compound_match eltek-10.128.99.34 ? "e*" => "True"
rect-master  | 2022-03-17T08:12:58.971024533Z [DEBUG   ] compile template: /etc/salt/pillar/eltek.sls

rect-master  | 2022-03-17T08:13:00.158145470Z [INFO    ] Authentication request from eltek-10.128.102.125
rect-master  | 2022-03-17T08:13:00.158335418Z [INFO    ] Authentication accepted from eltek-10.128.102.125
rect-master  | 2022-03-17T08:13:00.252251989Z [DEBUG   ] compound_match eltek-10.128.102.125 ? "e*" => "True"
rect-master  | 2022-03-17T08:13:00.252517879Z [DEBUG   ] compile template: /etc/salt/pillar/eltek.sls
```

**Expected behavior**
The master should render each device pillar once. 

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.6.1
        Python: 3.7.12 (default, Sep  8 2021, 01:55:52)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: alpine 3.14.2
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-348.12.2.el8_5.x86_64
        system: Linux
       version: Alpine Linux 3.14.2

```
</details>

**Additional context**
This might also affect https://github.com/saltstack/salt/issues/61153
