### ISSUE TITLE
[BUG] data.items, data.keys and data.values do not return anything

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#61818]
**Description**
The `data.items`, `data.keys`, and `data.values` functions do not return anything, even though there is data present and accessible by other functions.

**Steps to Reproduce the behavior**
```yaml
# salt-call data.dump '{"foo": "bar"}'
local:
    True
# salt-call data.get foo
local:
    bar
# salt-call data.has_key foo
local:
    True
# salt-call data.items
local:
# salt-call data.keys
local:
# salt-call data.values
local:
```

**Expected behavior**
```yaml
# salt-call data.items
local:
    |_
      ----------
      foo:
          bar
# salt-call data.keys
local:
    - foo
# salt-call data.values
local:
    - bar
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 1.3.0
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.7.1
        Python: 3.8.10 (default, Nov 26 2021, 20:14:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-104-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>
