### ISSUE TITLE
[BUG] file.serialize mege_if_exists deserialization exception -> Malformed state return

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#61814]
**Description**
When targeting `file.serialize` with `merge_if_exists=True` to a file that is improperly formatted, instead of displaying the error cause, salt will complain about a malformed state return.

**Setup**
M1 Mac, masterless minion (likely irrelevant)

**Steps to Reproduce the behavior**
```sls
This creates a malformed json file:
  file.managed:
    - name: /tmp/exception.json
    - contents: |
        {
            "foo": "bar",
        }

This throws an exception instead of failing with cause description:
  file.serialize:
    - name: /tmp/exception.json
    - serializer: json
    - merge_if_exists: true
    - dataset:
        baz: true
```

**Expected behavior**
A clear and concise description of what went wrong: `Failed to deserialize existing data: Expecting value: line 1 column 1 (char 0)`

**Screenshots**
```console
           ID: This throws an exception instead of failing with cause description
     Function: file.serialize
         Name: /tmp/exception.json
       Result: False
      Comment: An exception occurred in this state: Malformed state return. Data must be a dictionary type.
      Changes:
```

**Versions Report**

```yaml
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.12
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (default, Oct 12 2021, 12:57:44)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 3.0.2
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: darwin 21.3.0
        locale: UTF-8
       machine: x86_64
       release: 21.3.0
        system: Darwin
       version: 10.16 x86_64
```
</details>

**Additional context**
Already diagnosed and found a fix, PR incoming:

https://github.com/saltstack/salt/blob/1ebaed1ff0e1ccf5fb67050de19ce642ab8d28d2/salt/states/file.py#L7755-L7760s sets `ret` correctly, but still opts to `return False`.
