### ISSUE TITLE
[BUG] salt-ssh to localhost fails due to shared state dir

### ISSUE THREAD

**Issue by Vaelatern** [saltstack/salt#61825]
**Description**
A salt setup works for `salt-ssh` perfectly so long as it is not pointed at localhost.

The same setup details, with only the `host:` in the `roster` changed, works just fine remotely. However, when it is copied to the "target" system, it no longer functions due to permission errors with the state dir (`/var/tmp/.xyz/running_data`).

To make it concrete.

I have a desktop: `Rubeus`. I have a laptop: `Hagrid`. When `Rubeus` runs salt-ssh with `host: Hagrid`, everything works. When I copy the salt directory to `Hagrid` (and set up the PKI again so salt can run commands at all), and set `host: localhost` (or `host: Hagrid`, it doesn't matter), it fails to run.

This is a duplicate of https://github.com/saltstack/salt/issues/46891 with the impact explained, and to track me trying to fix it.

**Setup**
`Saltfile`
```
salt-ssh:
  roster_file: ./roster
  config_dir: .
  ssh_log_file: ./log.txt
```

`master`
```
root_dir: .

cachedir: ./cachedir

file_roots:
  base:
    - ./salt

pillar_roots:
  base:
    - ./pillar

state_output_diff: True
```

`roster`
```
voidhost:
  host: localhost
  user: salt
  sudo: True
  ssh_pre_flight: ./prepare_py3_void.sh
```
<details><summary>`prepare_py3_void.sh`</summary>

```
#!/bin/sh

sudo xbps-install -Syu xbps
sudo xbps-install -y python3
```

</details>

Tried on both:
- [X] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

**Expected behavior**
I'm able to run salt states against localhost.

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.10.3 (main, Mar 17 2022, 15:24:27) [GCC 10.2.1 20201203]
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: void rolling void
        locale: utf-8
       machine: x86_64
       release: 5.15.30_1
        system: Linux
       version: Void rolling void

```
</details>

**Additional context**

This is a *DUPLICATE* of https://github.com/saltstack/salt/issues/46891 but I think this is worth it to get assistance as I try to fix this.
