### ISSUE TITLE
[BUG] salt.states.grains.list_present append already existing values

### ISSUE THREAD

**Issue by dereckson** [saltstack/salt#61869]
**Description**
According the documentation, salt.states.grains.list_present should only add a value to a a grain formatted as a list if it doesn't exist. 

It's possible to pass multiple grains, but then, if one of them isn't present, the full list is added, including already existing items.
 
**Steps to Reproduce the behavior**
A minimal repro case from the salt.states doc and an update:

```
server_roles:
  grains.list_present:
    - value:
      - web
      - dev

server_roles_one_more_time:
  grains.list_present:
    - name: server_roles
    - value:
      - web
      - mail
      - dev
```

**Expected behavior**
grain serve_roles should contain web, dev, mail, only once for web and dev

**Versions Report**
salt 3004.1, repro with salt-call --local
