### ISSUE TITLE
[BUG] Windows minion crashes when the master responds with the key needs to be accepted event.

### ISSUE THREAD

**Issue by aklakina** [saltstack/salt#61887]
**Description**
In salt stack the minion and master authentication as far as I know works as follows:

1. Minion asks the master to join
2. Master responds with a "wait until I accept your key" My windows minion crashes here
3. After master accepts the key it sends the minion their key. My windows client does not get this key since it is already dead when the master sent it.
4. Afterwards they use the negotiated keys to authenticate

This authentication method with this error concludes the following:
My minion tries to authenticate with the master who responds with success and sends their key to which my minion responds with failure.

**Setup**
I have a running AD with DHCP and DNS services. Both the Hyper-V host and guest are connected to the AD. The master is an Ubuntu 18.04 and has every port open. The minion is a windows server 2019 with firewall configured to accept both in- and outbound ports of 4505-4506. On the windows the service is ran through elevated powershell with the command of: `salt-minion -l debug`
On the master the service is running as root with the command of: `salt-master -l debug`
Telnet is able to connect to the specified ports on Ubuntu.

- [ ] on-prem machine
- [x] VM (hyper-V master and the hyper-V host is the client)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**

1. Install and configure salt-master on an ubuntu 18.04 guest OS on Hyper-V
2. Install and configure salt-minion on the host Windows OS which is a 2019 server
3. Run them in debug mode to find out the issue.

Ubuntu (master) log:
https://pastebin.com/t3z4Cgxu

Windows (minion) logs:
https://pastebin.com/pBNbgdYn

**Expected behavior**
Windows minion not crashing and everything works fine.

**Screenshots**

**Versions Report**

<details><summary>salt --versions-report</summary>
(Windows minion version) 

```yaml
PS C:\Windows\system32> salt-minion --versions-report
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1250
       machine: AMD64
       release: 2019Server
        system: Windows
       version: 2019Server 10.0.17763 SP0 Multiprocessor Free
```
</details>

<details><summary>salt --versions-report</summary>
(Windows minion version) 

```yaml
root@saltmaster:/var/log/salt# salt-master --versions-report
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.9 (default, Mar 15 2022, 13:55:28)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-175-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>
