### ISSUE TITLE
[BUG] salt.states.chef.client AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ericham** [saltstack/salt#61891]
**Description**
When calling salt.states.chef.client against minions with Chef Infra Client version 16.17.18 or 17.9.18, the chef command will complete successfully on the minion, but the output on the master will throw "AttributeError: 'NoneType' object has no attribute 'group'". The reason is because of salt/states/chef.py L163
`regex = re.search(r"Chef Client finished, (\d+)", _summary(stdout), re.IGNORECASE)`

Version 16.x Chef Infra Client has the following output line at the end of a successful chef-client run:
`Chef Infra Client finished, 47 resources updated`

Version 17.x Chef Infra Client has the following output line at the end of a successful chef-client run:
`Infra Phase complete, 36 resources updated`

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
```
cat /srv/salt/top.sls
base:
  '*':
    - chef

cat /srv/salt/chef/init.sls
cheffing:
  chef.client: []
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ X ] VM running on a cloud service, AWS EC2, Ubuntu 18.04 and 20.04
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
salt '*' state.apply
...
----------
          ID: cheffing
    Function: chef.client
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2180, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/chef.py", line 92, in client
                  return _run(name, "chef.client", kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/chef.py", line 145, in _run
                  if _has_changes(result["stdout"]):
                File "/usr/lib/python3/dist-packages/salt/states/chef.py", line 164, in _has_changes
                  return int(regex.group(1)) > 0
              AttributeError: 'NoneType' object has no attribute 'group'
     Started: 00:20:04.915861
    Duration: 45899.217 ms
     Changes:

**Expected behavior**
There should be no AttributeError and the stdout output should be displayed since the chef.client completed successfully with a retcode of 0.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
salt -V
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.10 (default, Mar 15 2022, 12:22:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.13.0-1019-aws
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**
Versions 16.x and 17.x of Chef Infra Client are the currently supported versions, any earlier versions are EOL. I plan to open a PR with the suggested fix as follows:
```
diff --git a/salt/states/chef.py b/salt/states/chef.py
index b511a95d5b..f3921dc8a5 100644
--- a/salt/states/chef.py
+++ b/salt/states/chef.py
@@ -160,5 +160,5 @@ def _summary(stdout):
 
 
 def _has_changes(stdout):
-    regex = re.search(r"Chef Client finished, (\d+)", _summary(stdout), re.IGNORECASE)
-    return int(regex.group(1)) > 0
+    regex = re.search(r"Infra \w+ (complete|finished), (\d+)", _summary(stdout), re.IGNORECASE)
+    return int(regex.group(2)) > 0
```
