### ISSUE TITLE
[BUG] ext_tops: foreman-node command not run with minion-id argument

### ISSUE THREAD

**Issue by PeterLannigan** [saltstack/salt#61899]
**Description**
Starting in version 3002.7, /usr/bin/foreman-node command fails with error that it did not get an argument (a minion name).  Version 3002.6 works.  Versions 3002.8 and 3004.1 tested - both fail.  Change of salt/tops/ext_nodes.py seems to be the issue, specifically line 88:

shell=True,   # nosec

When changed to 'shell=False' is works correctly

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- on-prem RHEL 7.9 VM on RHV 4.4
- salt-master 3002.8
- foreman 2.3.5
- /etc/salt/master - master_tops:ext_nodes:/usr/bin/foreman-node
- blank top.sls file

Also tested the following with the same result
- on-prem RHEL 7.9 VM on RHV 4.4
- salt-master 3004.1
- foreman 2.5.4
- /etc/salt/master - master_tops:ext_nodes:/usr/bin/foreman-node
- blank top.sls file

**Steps to Reproduce the behavior**
Check that "foreman-node <minion_id>" works correctly.
Running "salt <minion_id> state.highstate"  with "shell=True" results in "No states found for this minion"
The /var/log/salt/master file has error
[salt.daemons.masterapi:532 ][ERROR   ][11259] Top function ext_nodes failed with error Command '['/usr/bin/foreman-node', 'salt
-foreman-t.gsd.esrl.noaa.gov']' returned non-zero exit status 1. for minion

**Expected behavior**
Running "salt <minion_id> state.highstate"  with "shell=False" runs correctly

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: rhel 7.9 Maipo
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.59.1.el7.x86_64
        system: Linux
       version: Red Hat Enterprise Linux Server 7.9 Maipo
```
</details>

**Additional context**
