### ISSUE TITLE
[BUG] Salt Creating OS Conflicts

### ISSUE THREAD

**Issue by ssoto2** [saltstack/salt#61902]
**Description**
Latest Salt update is causing OS conflicts. Running CentOS7  (CentOS Linux release 7.9.2009 (Core))  in AWS and now have conflicts due to a package is wanting to install from the saltstack repo 

```
Transaction check error:
  file /usr/share/doc/python-libcloud/README.rst from install of python36-libcloud-3.2.0-1.el7.noarch conflicts with file from package python2-libcloud-2.2.1-6.el7.noarch
  file /usr/share/doc/python-libcloud/demos/compute_demo.py from install of python36-libcloud-3.2.0-1.el7.noarch conflicts with file from package python2-libcloud-2.2.1-6.el7.noarch
  file /usr/share/doc/python-libcloud/demos/example_aliyun_oss.py from install of python36-libcloud-3.2.0-1.el7.noarch conflicts with file from package python2-libcloud-2.2.1-6.el7.noarch
  file /usr/share/doc/python-libcloud/demos/example_openstack.py from install of python36-libcloud-3.2.0-1.el7.noarch conflicts with file from package python2-libcloud-2.2.1-6.el7.noarch
  file /usr/share/doc/python-libcloud/demos/gce_demo.py from install of python36-libcloud-3.2.0-1.el7.noarch conflicts with file from package python2-libcloud-2.2.1-6.el7.noarch
```
This looks to be a new add by the saltstack repo based on looking at the package info

```
Installed Packages
Name        : python36-libcloud
Arch        : noarch
Version     : 2.2.1
Release     : 6.el7
Size        : 9.6 M
Repo        : installed
From repo   : epel
Summary     : A Python library to address multiple cloud provider APIs
URL         : http://libcloud.apache.org/
License     : ASL 2.0
Description : libcloud is a client library for interacting with many of
            : the popular cloud server providers.  It was created to make
            : it easy for developers to build products that work between
            : any of the services that it supports.
            : Python 3 version.

Available Packages
Name        : python36-libcloud
Arch        : noarch
Version     : 3.2.0
Release     : 1.el7
Size        : 1.7 M
Repo        : saltstack/x86_64
Summary     : A Python library to address multiple cloud provider APIs
URL         : https://libcloud.apache.org/
License     : ASL 2.0
Description : libcloud is a client library for interacting with many of
            : the popular cloud server providers.  It was created to make
            : it easy for developers to build products that work between
            : any of the services that it supports.
            : Python 3.6 version.

```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ x ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
running 3003.x on CentOS7 and then attempt to upgrade

**Expected behavior**
Salt Repo should not create os package conflicts preventing all yum updates from happening

**Screenshots**
![Selection_794](https://user-images.githubusercontent.com/5123879/161278043-e5e94b42-242b-456a-98b8-643850deed4c.png)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3003.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: 0.6.4
     gitpython: 1.0.1
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: 0.9.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.59.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

```
</details>

**Additional context**
