### ISSUE TITLE
[BUG] file.managed with test=1 (replace: false) reports failure when chown is to be performed

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#61913]
**Description**
When running with `test=1`, a state that ensures a file is existing with correct permissions and ownership (`file.managed` with `replace: false`, ~ touch) will report failure instead of "changes needed" when the file exists, but a user/group change would be performed.

TLDR: expected `ret["result"] == None`, actual `ret["result"] == False`

**Setup**
Masterless minion on MacOS
  
**Steps to Reproduce the behavior**
```bash
$ touch /tmp/filemanaged  # as non-root user
```

```sls
this fails with test=1:
  file.managed:
    - name: /tmp/filemanaged
    - user: root
    - replace: false
```

**Expected behavior**
State reports changes are needed, but does not fail.

**Screenshots**
```console
          ID: this fails with test=1
    Function: file.managed
        Name: /tmp/filemanaged
      Result: False
     Comment: File /tmp/filemanaged not updated
     Started: 11:24:58.038996
    Duration: 5.38 ms
     Changes:
```

**Versions Report**
```yaml
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.12
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.12 (default, Mar 11 2022, 20:48:53)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 3.0.2
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: darwin 21.3.0
        locale: UTF-8
       machine: x86_64
       release: 21.3.0
        system: Darwin
       version: 12.2 x86_64
```
</details>
