### ISSUE TITLE
[BUG] pkgrepo.managed for apt shows a change every highstate

### ISSUE THREAD

**Issue by feld** [saltstack/salt#61923]
**Description**
pkgrepo.managed shows a change every highstate because of salt.utils.pkg.deb.strip_uri

**Setup**
Try setting up a Debian package repo. Let's use this one directly from the docs 😉: https://docs.saltproject.io/en/latest/ref/states/all/salt.states.pkgrepo.html

<img width="712" alt="image" src="https://user-images.githubusercontent.com/40271278/161975916-3a76fc7d-c593-4c27-9a81-ae2495f7b15a.png">
  
**Steps to Reproduce the behavior**
Now every highstate shows a change:

```
----------
          ID: test_repo
    Function: pkgrepo.managed
        Name: deb http://dl.google.com/linux/chrome/deb/ stable main
      Result: True
     Comment: Configured package repo 'deb http://dl.google.com/linux/chrome/deb/ stable main'
     Started: 12:35:28.445649
    Duration: 6575.362 ms
     Changes:
              ----------
              repo:
                  deb http://dl.google.com/linux/chrome/deb stable main
```

**Expected behavior**
It doesn't show changes when there are none.

This happens because the URL `http://dl.google.com/linux/chrome/deb/` ends with a **/** and this is stripped before being written to disk, but Salt is comparing the with the unmodified version.
