### ISSUE TITLE
[BUG] MacOS/Homebrew: pkg.installed erroneously reports failure for formulae with revisions

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#61951]
**Description**
Using `pkg.installed` to install formulae that were revised (same package version, different build) reports failure, even if the installation worked. This is caused by Homebrew reporting the **package version** as the latest version, but the **formula version** as the installed version (suffix if revision > 0).

**Setup**
masterless minion on MacOS Monterey (M1)
  
**Steps to Reproduce the behavior**
Currently, the `tmux` stable formula is on revision 1, so it works as an example:

```sls
This installation reports failure, but works:
  pkg.installed:
    - name: tmux
```

**Expected behavior**
Reports success if the installation worked.

**Screenshots**

```sls
local:
----------
          ID: This installation reports failure, but works
    Function: pkg.installed
        Name: tmux
      Result: False
     Comment: The following packages failed to install/update: tmux=3.2a
     Started: 19:52:08.017293
    Duration: 6782.194 ms
     Changes:
```

```console
$ sudo /opt/salt/bin/salt-call pkg.latest_version tmux
local:
    3.2a
$ sudo /opt/salt/bin/salt-call pkg.version tmux
local:
    3.2a_1
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.12
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.12 (default, Mar 11 2022, 20:48:53)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 3.0.2
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: darwin 21.3.0
        locale: UTF-8
       machine: x86_64
       release: 21.3.0
        system: Darwin
       version: 12.2 x86_64
```
</details>

**Additional context**
I'm not sure if there are implications of including the revision number in the output of `pkg.latest_version`, especially for devel, but it fixes this issue. For example, [around here](https://github.com/saltstack/salt/blob/1568067961d5867f14a3b9dd550d7712aba1b463/salt/modules/mac_brew_pkg.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L259) with something like this (warning, ugly):

```diff
@@ -1,3 +1,6 @@
 def get_version(pkg_info):
+    suffix = ""
+    if pkg_info["revision"] > 0:
+        suffix = "_" + str(pkg_info["revision"])
     # Perhaps this will need an option to pick devel by default
-    return pkg_info["versions"]["stable"] or pkg_info["versions"]["devel"]
+    return (pkg_info["versions"]["stable"] or pkg_info["versions"]["devel"]) + suffix
```
