### ISSUE TITLE
[BUG] LDAP eauth module not compatible with 2FA when `auth.ldap.freeipa` is set to `True`

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#61974]
**Description**
When `auth.ldap.freeipa` is set to `True` when using the LDAP eauth module, every authentication requires 2 separate LDAP binds as the user, even when using a separate binddn. This interferes with the ability to use 2FA, as tokens may only be valid for one auth, or in the case of Duo, it requires the user to approve twice. This is the exact same problem as #42280, except it's in the FreeIPA branch of the code.

I believe the fix is exactly the same, and that the following lines:

https://github.com/saltstack/salt/blob/77f8e4b151268a7823e0b2f6317d226ce9835e3f/salt/auth/ldap.py#L476-L478

can be replaced verbatim with the fix for other branch of the code:

https://github.com/saltstack/salt/blob/77f8e4b151268a7823e0b2f6317d226ce9835e3f/salt/auth/ldap.py#L519-L528

**Setup**
_/etc/salt/master.d/auth.conf:_
```
auth.ldap.uri: 'ldap://[::1]'
auth.ldap.scope: 2
auth.ldap.no_verify: False
auth.ldap.anonymous: False
auth.ldap.auth_by_group_membership_only: False
auth.ldap.binddn: 'uid=ldap_auth,cn=sysaccounts,cn=etc,dc=example,dc=com'
auth.ldap.bindpw: CorrectHorseBatteryStaple
auth.ldap.basedn: 'cn=users,cn=accounts,dc=example,dc=com
auth.ldap.filter: 'uid={{ username }}'
auth.ldap.groupclass: 'posixGroup'

auth.ldap.freeipa: True

# We must use FreeIPA's RFC2307 "compat" tree for group membership
auth.ldap.group_basedn: 'cn=groups,cn=compat,dc=example,dc=com'
auth.ldap.group_filter: '(&(memberUid={{ username }})(objectClass=posixGroup))'
auth.ldap.accountattributename: 'memberUid'
```

**Steps to Reproduce the behavior**
Configure LDAP eauth as above, use

`salt -a ldap salt01 test.ping` and authenticate.

**Expected behavior**
When using a separate binddn, only one bind of the user account should occur.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.26.8
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.26.4
        Python: 3.6.8 (default, Nov 17 2021, 16:10:06)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 8.5 Arctic Sphynx
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-348.20.1.el8_5.x86_64
        system: Linux
       version: AlmaLinux 8.5 Arctic Sphynx
```
</details>
