### ISSUE TITLE
[BUG] Highstate total runtime incorrect for parallel states

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#61999]
**Description**
When running states in parallel the total runtime in the highstate output shows the runtime for all states, which is incorrect because the states will be running in parallel and the actual runtime will be reduced.

**Setup**
```
barrier:
  test.nop
  
{%- for x in [1,2,3] %}
blah-{{x}}:
  cmd.run:
    - name: sleep 10
    - require:
      - barrier
    - parallel: true
    - require_in:
      - barrier2
{% endfor %}

barrier2:
  test.nop
```
  
**Steps to Reproduce the behavior**

```
[adler salt]# time salt-call --local state.apply test.49273

local:
----------
          ID: barrier
    Function: test.nop
      Result: True
     Comment: Success!
     Started: 16:12:37.500109
    Duration: 0.679 ms
     Changes:   
----------
          ID: blah-1
    Function: cmd.run
        Name: sleep 10
      Result: True
     Comment: Command "sleep 10" run
     Started: 16:12:37.539771
    Duration: 10008.38 ms
     Changes:   
              ----------
              pid:
                  546686
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: blah-2
    Function: cmd.run
        Name: sleep 10
      Result: True
     Comment: Command "sleep 10" run
     Started: 16:12:37.583423
    Duration: 10008.589 ms
     Changes:   
              ----------
              pid:
                  546688
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: blah-3
    Function: cmd.run
        Name: sleep 10
      Result: True
     Comment: Command "sleep 10" run
     Started: 16:12:37.628760
    Duration: 10008.808 ms
     Changes:   
              ----------
              pid:
                  546690
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: barrier2
    Function: test.nop
      Result: True
     Comment: Success!
     Started: 16:12:47.682403
    Duration: 2.798 ms
     Changes:   

Summary for local
------------
Succeeded: 5 (changed=3)
Failed:    0
------------
Total states run:     5
Total run time:  30.029 s

real	0m14.752s
user	0m4.237s
sys	0m0.640s
```

(Include debug logs if possible and relevant)

**Expected behavior**
```
[adler salt]# time salt-call --local state.apply test.49273
local:
----------
          ID: barrier
    Function: test.nop
      Result: True
     Comment: Success!
     Started: 16:16:08.774574
    Duration: 0.634 ms
     Changes:   
----------
          ID: blah-1
    Function: cmd.run
        Name: sleep 10
      Result: True
     Comment: Command "sleep 10" run
     Started: 16:16:08.811587
    Duration: 10007.42 ms
     Changes:   
              ----------
              pid:
                  547271
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: blah-2
    Function: cmd.run
        Name: sleep 10
      Result: True
     Comment: Command "sleep 10" run
     Started: 16:16:08.852666
    Duration: 10007.735 ms
     Changes:   
              ----------
              pid:
                  547273
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: blah-3
    Function: cmd.run
        Name: sleep 10
      Result: True
     Comment: Command "sleep 10" run
     Started: 16:16:08.893263
    Duration: 10007.539 ms
     Changes:   
              ----------
              pid:
                  547275
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: barrier2
    Function: test.nop
      Result: True
     Comment: Success!
     Started: 16:16:18.939663
    Duration: 0.866 ms
     Changes:   

Summary for local
------------
Succeeded: 5 (changed=3)
Failed:    0
------------
Total states run:     5
Total run time:  10.009 s

real	0m14.746s
user	0m4.273s
sys	0m0.556s
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml

Salt Version:
          Salt: 3003rc1+1551.g9c7e357d42
 
Dependency Versions:
          cffi: 1.14.2
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.7.7 (default, Sep  4 2020, 16:48:08)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 21.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist: manjaro 21.2.6 Qonos
        locale: UTF-8
       machine: x86_64
       release: 5.15.32-1-MANJARO
        system: Linux
       version: Manjaro Linux 21.2.6 Qonos
```
</details>

**Additional context**
