### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SeanFromIT** [saltstack/salt#62001]
**Description**
Comment: State 'file.comment_line' was not found in SLS 'servers'
              Reason: 'file.comment_line' is not available.

**Setup**
salt-minion:
  Installed: 3004.1+dfsg-2
  Candidate: 3004.1+dfsg-2

on ubuntu 22.04

- [ X ] on-prem machine

**Steps to Reproduce the behavior**
some_comment:
  file.comment_line:
    - path: /path/to/file
    - cmnt: False
    - regex: ^myregex

**Expected behavior**
Line is uncommented.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: 1.1.0
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.11.0
        pygit2: 1.6.1
        Python: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 Jammy Jellyfish
        locale: utf-8
       machine: x86_64
       release: 5.15.0-25-generic
        system: Linux
       version: Ubuntu 22.04 Jammy Jellyfish
```
</details>
