### ISSUE TITLE
get_event_noblock ERROR [BUG]

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#62015]
**Description**
Calling get_event_noblock() from python produces an error.
```
Traceback (most recent call last):
  File "get_events.py", line 11, in <module>
    ret = sevent.get_event_noblock()
  File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 682, in get_event_noblock
    mtag, data = self.unpack(raw, self.serial)
  File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 443, in unpack
    mtag, sep, mdata = raw.partition(
AttributeError: 'Future' object has no attribute 'partition'
```

**Setup**
```
import salt.config
import salt.utils.event

opts = salt.config.client_config("/etc/salt/master")

sevent = salt.utils.event.get_event(
    "master", sock_dir=opts["sock_dir"], transport=opts["transport"], opts=opts
)
while True:
    ret = sevent.get_event_noblock()
    if ret is None:
        continue
    print(ret)
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
run python script to get events 

**Expected behavior**
get the events 

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3003.4

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.6.8 (default, Sep  9 2021, 07:49:02)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4


System Versions:
          dist: rhel 8.5
        locale: UTF-8
       machine: x86_64
       release: 4.87.0
        system: Linux
       version: Red Hat Enterprise Linux 8.5
```
</details>
