### ISSUE TITLE
[BUG] zypperpkg.upgrade does not support name or pkgs parameters

### ISSUE THREAD

**Issue by agraul** [saltstack/salt#62030]
**Description**

`pkg.upgrade name=foo` works with `yumpkg`, but not with `zypperpkg`. Different `pkg` implementations should try to support the same arguments where it makes sense. Passing `name` or `pkgs` to limit the number of packages that will be upgraded makes sense to a Salt user.

**Setup**

One minion with `yum`, e.g. AlmaLinux 8 and another with `zypper` (e.g. openSUSE Leap 15.3). Salt 3004 on the master and the minions.
 
**Steps to Reproduce the behavior**:
`salt '*' pkg.upgrade name=foo` and `salt '*' pkg.upgrade pkgs='["foo", "bar"]'`:
In both cases, the minion running `zypper` ignores the parameter that restricts the packages to be upgraded and upgrades all packages.

**Expected behavior**:

`zypper` only update the packages that are specified, the same way that `yum` does it. If dependencies need to be updated along with the specified packages, they will also be updated. All updated packages are reported in the job return dict and rendered on the CLI.

**Versions Report**
<details><summary>salt --versions-report</summary>
The exact version does not matter, `zypperpkg.upgrade` does not know the parameter in any of them. I reproduced this on a setup using

```yaml
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.28.4
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: 3.9.0
  pycryptodome: Not Installed
        pygit2: 0.28.2
        Python: 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: sles 15.3 2021.05
        locale: UTF-8
       machine: x86_64
       release: 5.3.18-59.27-default
        system: Linux
       version: SLES 15.3 2021.05

```
</details>

**Additional context**
