### ISSUE TITLE
[BUG] `pkg.list_pkgs(attr="all`)` (yum/zypper) calsl `pkg_resource.format_pkg_list()` wrongly

### ISSUE THREAD

**Issue by agraul** [saltstack/salt#62032]
**Description**
`pkg.list_pkgs(attr="all")` turns `"all"` into `["all"]` before passing it to `pkg_resource.format_pkg_list()`. The latter function expects either a list of attributes or the string "all". Upon encountering `["all"]`, it parses it as a list of attributes to include in its return value. As a result, only the default "version" and "arch" attributes are returned.

**Setup**

One minion with `yum`, e.g. AlmaLinux 8 and another with `zypper` (e.g. openSUSE Leap 15.3). Salt 3004 on the master and the minions.
 
**Steps to Reproduce the behavior**:
```
# salt '*'  pkg.list_pkgs attr=all
[...]
    zlib:
        |_
          ----------
          arch:
              x86_64
          version:
              1.2.11
```

**Expected behavior**:
```
# salt '*'  pkg.list_pkgs attr=all
[...]
    zypper:
        |_
          ----------
          arch:
              x86_64
          epoch:
              None
          install_date:
              2022-02-22T18:22:09Z
          install_date_time_t:
              1645554129
          release:
              24.1
          version:
              1.14.51

```

**Versions Report**
<details><summary>salt --versions-report</summary>
The exact version does not matter, `zypperpkg.upgrade` does not know the parameter in any of them. I reproduced this on a setup using

```yaml
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.28.4
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: 3.9.0
  pycryptodome: Not Installed
        pygit2: 0.28.2
        Python: 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: sles 15.3 2021.05
        locale: UTF-8
       machine: x86_64
       release: 5.3.18-59.27-default
        system: Linux
       version: SLES 15.3 2021.05

```
</details>

**Additional context**
