### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#62083]
**Description**

Salt mongodb ext_pillar fails with following error, was working in previous version.

```
Failed to load ext_pillar mongo: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.
```

**Setup**
Running saltstack/salt:3004.1 docker

 
**Steps to Reproduce the behavior**
configure mongodb pillar

**Expected behavior**
a working setup

**Versions Report**

```yaml
/ # salt --versions
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.6.1
        Python: 3.7.13 (default, Mar 18 2022, 17:55:41)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: alpine 3.14.4
        locale: UTF-8
       machine: x86_64
       release: 5.17.6-arch1-1
        system: Linux
       version: Alpine Linux 3.14.4
```
</details>
