### ISSUE TITLE
[BUG] emitatstartup ignored when delay option used in service beacon

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#62095]
**Description**
When the `delay` option is used in the service beacon, then `emitatstartup` options is ignored.

**Setup**
Configure service beacon with onchangeonly, emitatstartup, and delay options enabled.
```
beacons:
  service:
    - services:
        nginx:
          onchangeonly: True
          emitatstartup: False
          delay: 30
```
  
**Steps to Reproduce the behavior**
Configure service beacon and start the Salt minion.

**Expected behavior**
The service beacon should not emit any events when the Salt minion is initially started.
