### ISSUE TITLE
[BUG] file.comment state picks up comments after config in the line

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#62121]
**Description**
Comment from @myii in PR #62045 

This PR has resulted in a regression, when the line matched by the provided `regex` already has a comment at the end of the line.

Identified 764c7699eb98c9b5f4dac43b1b2cba17e4bce34c as the offending commit using `git bisect`:

```console
764c7699eb98c9b5f4dac43b1b2cba17e4bce34c is the first bad commit
commit 764c7699eb98c9b5f4dac43b1b2cba17e4bce34c
...
...

    fixes saltstack/salt#61662 fix file.comment reports changes in test mode

 salt/states/file.py | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)
```
Here's a minimal reproducible example:

```sls
regression_file_comment/init/file.managed:
  file.managed:
    - name: /tmp/regression_file_comment
    - contents: |
        port = 5432                             # (change requires restart)

regression_file_comment/init/file.comment:
  file.comment:
    - name: /tmp/regression_file_comment
    - regex: ^port\s*=.+
    - require:
      - file: regression_file_comment/init/file.managed
```

See further details below that may be useful.

---

Encountered these failures during this week's `master` testing:

* https://gitlab.com/myii/postgres-formula/-/pipelines/551411889

In this case, the default `postgresql.conf` (on Debian and Ubuntu) has a `port` line which is commented like so:

```console
port = 5432                             # (change requires restart)
```

This line is supposed to be commented out if a (different) port has been provided in the config.

https://github.com/saltstack-formulas/postgres-formula/blob/6eecf7f0688744d8cfbdf4b76d938c0a81efdca2/postgres/server/init.sls#L115-L125

```sls
{%- set db_port = salt['config.option']('postgres.port') %}
{%- if db_port %}
postgresql-conf-comment-port:
  file.comment:
    - name: {{ postgres.conf_dir }}/postgresql.conf
    - regex: ^port\s*=.+
    - require:
      - file: postgresql-config-dir
{%- endif %}
```

With the regression being:

```sls
                 ID: postgresql-conf-comment-port
           Function: file.comment
               Name: /etc/postgresql/13/main/postgresql.conf
             Result: False
            Comment: port\s*=.+: Pattern not found
```

_Originally posted by @myii in https://github.com/saltstack/salt/issues/62045#issuecomment-1141485079_

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005+0na.b18281e
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 23.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**
PR inbound.
