### ISSUE TITLE
[BUG] solarispkg current_zone_only: True not appending to list but is trying to add.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#62206]
**Description**
current_zone_only adding `-` and `G` to command instead of `-G`

**Setup**

setup a package to be current_zone_only true and check the debug log. 

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [X] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
try to use solarispkg to install a package into a solaris zone on solaris 10. and use current_zone_only. the resulting command would be something like the following list. 

```
['/usr/sbin/pkgadd', '-n', '-a', '/tmp/salt-xxxx', '-', 'G', ' ', '-d', 'package', 'all']
```

**Expected behavior**
the command generated should be 

```
['/usr/sbin/pkgadd', '-n', '-a', '/tmp/salt-xxxx', '-G', '-d', 'package', 'all']
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
    Salt Version:
              Salt: 3004

    Dependency Versions:
              cffi: 1.14.3
          cherrypy: Not Installed
          dateutil: Not Installed
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.0.2
           libgit2: Not Installed
          M2Crypto: 0.38.0
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.17
          pycrypto: Not Installed
      pycryptodome: 3.11.0
            pygit2: Not Installed
            Python: 3.7.10 (default, Oct 20 2021, 19:27:41)
      python-gnupg: Not Installed
            PyYAML: 6.0
             PyZMQ: 21.0.2
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.3

    System Versions:
              dist: sunos 5.10
            locale: utf-8
           machine: sun4v
           release: 5.10
            system: SunOS
           version: SunOS 5.10
```
</details>
