### ISSUE TITLE
[BUG] service.enabled shows errors for unavailable services in test mode

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#62258]
**Description**
A common workflow is to ensure a service is enabled after a package is installed. When performed in the same run, the service won't be available until the package is installed. In test mode, the absence of the service is currently represented as a failure.
  
**Steps to Reproduce the behavior**

Generic state:

```
# svc.sls
something:
  service.enabled
```

```bash
$ salt-call state.apply svc test=true

[ERROR   ] The named service something is not available
local:
----------
          ID: something
    Function: service.enabled
      Result: False
     Comment: The named service something is not available
     Started: 16:52:31.433661
    Duration: 160748.829 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 160.749 s
```

**Expected behavior**
In test mode, we should not treat the absence of a service as a failure.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
               Salt: 3004.1
 
Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.7.3
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.11
             Jinja2: 2.10
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
            msgpack: 0.5.6
       msgpack-pure: Not Installed
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: 3.6.1
             pygit2: Not Installed
             Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
       python-gnupg: Not Installed
             PyYAML: 3.13
              PyZMQ: 17.1.2
              smmap: 2.0.5
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.3.1
 
Salt Extensions:
 saltext.prometheus: 1.1.1
 
System Versions:
               dist: debian 10 buster
             locale: UTF-8
            machine: x86_64
            release: 4.19.0-20-amd64
             system: Linux
            version: Debian GNU/Linux 10 buster

```
</details>
