### ISSUE TITLE
[BUG] requisite not found in certain scenarios

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#62264]
**Description**
In very specific circumstances, requisites may not be found due to receiving the wrong state module name when not explicitly specified.

**Setup**

This SLS file can used to reproduce the problem.

```yaml
# /srv/salt/req_in_test.sls 

stuff:
  cmd.run:
    - name: echo hello

{% for i in range(0, 5) -%}
thing_{{i}}_test:
  file.directory:
    - name: /tmp/dir{{ i }}
    - makedirs: True
    - require_in:
      - /tmp/dir{{ i }}/*
      - service: service_running

{% endfor -%}

service_running:
  service.running:
    - name: rsyslog
    - require:
      - cmd: stuff
```
  
**Steps to Reproduce the behavior**

A simple `salt-call state.apply req_in_test` will show the following error in the output, wherein Salt seems to think that the `file` module states are `service` module states.

```
          ID: service_running
    Function: service.running
        Name: rsyslog
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     service: thing_0_test
                                     service: thing_1_test
                                     service: thing_2_test
                                     service: thing_3_test
                                     service: thing_4_test
     Started: 15:55:52.007556
    Duration: 0.003 ms
     Changes:
```

**Expected behavior**
The code should properly track the state module used for a given block.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
               Salt: 3004.2
 
Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.7.3
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.11
             Jinja2: 2.10
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
            msgpack: 0.5.6
       msgpack-pure: Not Installed
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: 3.6.1
             pygit2: Not Installed
             Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
       python-gnupg: Not Installed
             PyYAML: 3.13
              PyZMQ: 17.1.2
              smmap: 2.0.5
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.3.1
 
Salt Extensions:
 saltext.prometheus: 1.1.1
 
System Versions:
               dist: debian 10 buster
             locale: UTF-8
            machine: x86_64
            release: 4.19.0-20-amd64
             system: Linux
            version: Debian GNU/Linux 10 buster

```
</details>
