### ISSUE TITLE
[BUG] Unable to connect pusher: Stream is closed

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#62334]
**Description**
For a certain configuration where a master is configured on minion in order to host SLS and other files but the long-running minion service is stopped, the following error is thrown when the `salt-call` command is run on the minion:

```
[ERROR   ] Unable to connect pusher: Stream is closed
```

It seems that this configuration, where `salt-call` is run manually or via scheduled (cron) job, should be valid. Everything seems to work just fine, but the errors cause user confusion and the perception that something critical has failed.

**Setup**
Normal master/minion setup, but stop the `salt-minion` service.
  
**Steps to Reproduce the behavior**
Run any command and view the error message as the minion code spins up.

```
# salt-call cp.list_master
[ERROR   ] Unable to connect pusher: Stream is closed
local:
    - test.sls
```

**Expected behavior**
It would be nice to suppress this error message in certain scenarios where the connection to a master is desired without the configuration of long-running minion service.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005+0na.b18281e
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 23.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-21-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster

```
</details>

**Additional context**
Versions report is from recent pre-3005 master clone, but is reproducible on previous versions.
