### ISSUE TITLE
[BUG] can not mount multiple nfs-targets

### ISSUE THREAD

**Issue by max298** [saltstack/salt#62341]
**Description**
I want to mount two different directories from the same nfs-server. Salt seems to only support one directory per nfs-server.
Salt mounts the same directory from a nfsserver twice, even though the device and mount point differs.

**Setup**
Normal master/minion setup
  
**Steps to Reproduce the behavior**
`nfs.sls`:
```yaml
A is mounted:
  mount.mounted:
    - name: /srv/A
    - device: nfs.internal.domain:/data/A
    - fstype: nfs

B is mounted:
  mount.mounted:
    - name: /srv/B
    - device: nfs.internal.domain:/data/B
    - fstype: nfs
```

```bash
salt 'myminion' state.sls nfs
myminion:
----------
          ID: A is mounted
    Function: mount.mounted
        Name: /srv/A
      Result: True
     Comment: Target was already mounted. Entry already exists in the fstab.
     Started: 09:38:10.888360
    Duration: 78.065 ms
     Changes:
----------
          ID: B is mounted
    Function: mount.mounted
        Name: /srv/B
      Result: True
     Comment: Target was successfully mounted. Added new entry to the fstab.
     Started: 09:38:11.040819
    Duration: 210.83 ms
     Changes:
              ----------
              mount:
                  True
              persist:
                  new

Summary for myminion
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time:  12.784 s
```

**Expected behavior**
I'd expect myminion to mount `nfs:/data/A` to `/srv/A` and `nfs:/data/B` to `/srv/B`. However, the actual behavior when I check myminion is as follows:
```bash
cat /etc/fstab
# …
nfs.internal.domain:/data/A		/srv/A	nfs	defaults	0 0
nfs.internal.domain:/data/B		/srv/B	nfs	defaults	0 0
# looks good. however:
mount
nfs.internal.domain:/data/A on /srv/A type nfs (rw,relatime,vers=3,rsize=262144,wsize=262144,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.5.0.3,mountvers=3,mountport=20048,mountproto=udp,local_lock=none,addr=10.5.0.3)
nfs.internal.domain:/data/A on /srv/B type nfs (rw,relatime,vers=3,rsize=262144,wsize=262144,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.5.0.3,mountvers=3,mountport=20048,mountproto=udp,local_lock=none,addr=10.5.0.3)
```
So salt mounts `nfs:/data/A` to `/srv/A` **and** `/srv/B`.

**Versions Report**

<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.1.0
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: 1.6.1
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: sles 15.3
        locale: UTF-8
       machine: x86_64
       release: 5.3.18-150300.59.63-default
        system: Linux
       version: SLES 15.3
```
</details>

**Additional context**
My workaround as the fstab is written correctly is as follows:
`nfs.sls`:
```yaml
A is mounted:
  mount.mounted:
    - name: /srv/A
    - device: nfs.internal.domain:/data/A
    - fstype: nfs
    - device_name_regex: nfs.internal.domain {# prevent remount #}

B is mounted:
  mount.mounted:
    - name: /srv/B
    - device: nfs.internal.domain:/B
    - fstype: nfs
    - device_name_regex: nfs.internal.domain {# prevent remount #}

Mounts are loaded:
  cmd.run:
    - name: mount -a
    - onchanges:
      - mount: A is mounted
      - mount: B is mounted
```
