### ISSUE TITLE
[BUG] port variable not used in salt/utils/http.py 

### ISSUE THREAD

**Issue by JorisPenningsCM** [saltstack/salt#62348]
**Description**
When passing "port" variable to statefile "http.query" the port variable is ignored by https://github.com/saltstack/salt/blob/master/salt/utils/http.py

**Setup**
Example sls file:
```yaml
example:
  http.query:
    - name: 'http://example.com'
    - status: 200
    - method: 'POST'
    - data:
        ip: '10.125.25.69'
    - header_list:
      - 'accept: */*'
      - 'content-type: application/x-www-form-urlencoded'
    - port: 8080
```
 
- [X] on-prem machine
  
**Steps to Reproduce the behavior**
Run state.sls
Query will use http://example.com:80 as its endpoint.

**Expected behavior**
Run state.sls
Query will use http://example.com:8080 as its endpoint.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
minion:
    Salt Version:
              Salt: 3002.2

    Dependency Versions:
              cffi: Not Installed
          cherrypy: unknown
          dateutil: 2.7.3
         docker-py: Not Installed
             gitdb: 2.0.6
         gitpython: 3.0.7
            Jinja2: 3.0.1
           libgit2: 0.28.3
          M2Crypto: 0.31.0
              Mako: 1.1.0
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: 1.4.4
         pycparser: Not Installed
          pycrypto: Not Installed
      pycryptodome: 3.10.1
            pygit2: 1.0.3
            Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
      python-gnupg: 0.4.5
            PyYAML: 5.4.1
             PyZMQ: 22.1.0
             smmap: 2.0.5
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.4

    System Versions:
              dist: ubuntu 20.04 focal
            locale: utf-8
           machine: x86_64
           release: 5.10.102.1-microsoft-standard-WSL2
            system: Linux
           version: Ubuntu 20.04 focal
```
</details>

**Additional context**
https://github.com/saltstack/salt/blob/master/salt/utils/http.py
Port variable logic is not implemented in this file.
