### ISSUE TITLE
[BUG] Augeas module fails to load on EL9 3005~rc2-1

### ISSUE THREAD

**Issue by imjustvisiting** [saltstack/salt#62444]
**Description**
The augeas module/state does not appear to be getting loaded on EL9 3005~rc2-1.

**Setup**
Installed the RC1~2 RPMs on a baremetal workstation running Rocky 9.0:

```
> rpm -qa | grep salt
salt-3005~rc2-1.el9.x86_64
salt-minion-3005~rc2-1.el9.x86_64
```
  
**Steps to Reproduce the behavior**
The simplest way I've found to verify that the module is loaded is to run the following command and verify that the output is not empty. (This can be run without connecting to the server):

```
> salt-call --local sys.doc | grep augeas
```

**Expected behavior**
If the augeas module is loaded correctly, I'd expect to see the augeas module documentation referenced. Instead, nothing is returned.

For comparison, on an EL8/3004.2 insallation, the following is returned:

```
> salt-call --local sys.doc | grep augeas
    augeas.execute:
                salt '*' augeas.execute /files/etc/redis/redis.conf \
    augeas.get:
            Get a value for a specific augeas path
                salt '*' augeas.get /files/etc/hosts/1/ ipaddr
    augeas.ls:
                salt '*' augeas.ls /files/etc/passwd
    augeas.match:
                salt '*' augeas.match /files/etc/services/service-name ssh
    augeas.remove:
                salt '*' augeas.remove \
    augeas.setvalue:
            Set a value for a specific augeas path
                salt '*' augeas.setvalue /files/etc/hosts/1/canonical localhost
                salt '*' augeas.setvalue /files/etc/hosts/01/ipaddr 192.168.1.1 \
                salt '*' augeas.setvalue prefix=/files/etc/sudoers/ \
    augeas.tree:
                salt '*' augeas.tree /files/etc/
```

**Versions Report**
<details><summary>salt-call --local --versions-report</summary>

```yaml
Salt Version:
          Salt: 3005rc2
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Apr 10 2020, 00:00:00)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 9.0 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-70.17.1.el9_0.x86_64
        system: Linux
       version: Rocky Linux 9.0 Blue Onyx
```
</details>
