### ISSUE TITLE
[BUG] Salt not getting any pillar data for given host

### ISSUE THREAD

**Issue by AdamMir86** [saltstack/salt#62470]
**Description**

With some servers (mostly debian 10/11), got an issue where for running any pillar.get or state.apply of any role (example of zabbix) ends up with:

```
 salt-call pillar.get zabbix
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'Pillar key not found: zabbix'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 33, in <module>
    sys.exit(load_entry_point('salt==3002.6', 'console_scripts', 'salt-call')())
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 112, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 219, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/pillar.py", line 187, in get
    raise KeyError("Pillar key not found: {0}".format(key))
KeyError: 'Pillar key not found: zabbix'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 33, in <module>
    sys.exit(load_entry_point('salt==3002.6', 'console_scripts', 'salt-call')())
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 112, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 219, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/pillar.py", line 187, in get
    raise KeyError("Pillar key not found: {0}".format(key))
KeyError: 'Pillar key not found: zabbix'
```

**Setup**
Salt-master is on almalinux 8.6
Debian 10/11 with salt-minion installed

Please be as specific as possible and give set-up details.

- [ x ] on-prem machine
- [ x ] VM (proxmox hosted machine)
- [ - ] VM running on a cloud service, please be explicit and add details
- [ - ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ - ] or a combination, please be explicit
- [ - ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
- Run from salt master state.apply zabbix (or any role), or pillar.get zabbix
- Run on target host with salt-minion salt-call state.apply zabbix (or any role), or pillar.get zabbix

**Expected behavior**
state.apply produce normal output, or pillar.get shows pillars values for given key

**Screenshots**
not needed

**Versions Report**
<details><summary>salt-master salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr 29 2022, 13:46:02)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: almalinux 8.6 Sky Tiger
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-372.16.1.el8_6.x86_64
        system: Linux
       version: AlmaLinux 8.6 Sky Tiger
```
</details>
<details><summary>salt-minion --versions-report from host with issue (pve01)</summary>

```yaml
Salt Version:
          Salt: 3002.6
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.15.35-1-pve
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>
<details><summary>salt-minion --versions-report from host without issue (hv1)</summary>

```yaml
Salt Version:
          Salt: 3002.6
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.15.39-1-pve
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**
On host with issue same things happens when salt was reinstalled to 3004 version.

**Things that where done/tried already:**

- reinstalled python libs on pve01
- made kernel updated on pve01
- windows solving aproach = restarting whole server
- reinstall salt on pve01 host multiple times
- tried 3004 version of salt on pve01
- straced salt-call => got lot's of errors `Inappropriate ioctl for device`

Example of Inappropriate ioctl for device errors from strace (Currently following those as this is my last clue):

```
[ 257] [00007f2c63cf5767] openat(AT_FDCWD, "/usr/lib/python3.9/encodings/__pycache__/__init__.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 3
[  72] [00007f2c63a73e70] fcntl(3, F_GETFD) = 0x1 (flags FD_CLOEXEC)
[   5] [00007f2c63a6e3f5] fstat(3, {st_mode=S_IFREG|0644, st_size=3895, ...}) = 0
[  16] [00007f2c63a743f6] ioctl(3, TCGETS, 0x7ffc8c8ddd40) = -1 ENOTTY (Inappropriate ioctl for device)
--
[   4] [00007f2c63a6e3a6] stat("/usr/lib/python3.9/codecs.py", {st_mode=S_IFREG|0644, st_size=36673, ...}) = 0
[ 257] [00007f2c63cf5767] openat(AT_FDCWD, "/usr/lib/python3.9/__pycache__/codecs.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 3
[   5] [00007f2c63a6e3f5] fstat(3, {st_mode=S_IFREG|0644, st_size=33886, ...}) = 0
[  16] [00007f2c63a743f6] ioctl(3, TCGETS, 0x7ffc8c8dcf10) = -1 ENOTTY (Inappropriate ioctl for device)
--
[   4] [00007f2c63a6e3a6] stat("/usr/lib/python3.9/encodings/aliases.py", {st_mode=S_IFREG|0644, st_size=15677, ...}) = 0
[ 257] [00007f2c63cf5767] openat(AT_FDCWD, "/usr/lib/python3.9/encodings/__pycache__/aliases.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 3
[   5] [00007f2c63a6e3f5] fstat(3, {st_mode=S_IFREG|0644, st_size=6328, ...}) = 0
[  16] [00007f2c63a743f6] ioctl(3, TCGETS, 0x7ffc8c8dc6f0) = -1 ENOTTY (Inappropriate ioctl for device)
--
[   4] [00007f2c63a6e3a6] stat("/usr/lib/python3.9/encodings/utf_8.py", {st_mode=S_IFREG|0644, st_size=1005, ...}) = 0
[ 257] [00007f2c63cf5767] openat(AT_FDCWD, "/usr/lib/python3.9/encodings/__pycache__/utf_8.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 3
[   5] [00007f2c63a6e3f5] fstat(3, {st_mode=S_IFREG|0644, st_size=1630, ...}) = 0
[  16] [00007f2c63a743f6] ioctl(3, TCGETS, 0x7ffc8c8ddda0) = -1 ENOTTY (Inappropriate ioctl for device)
--
[   4] [00007f2c63a6e3a6] stat("/usr/lib/python3.9/encodings/latin_1.py", {st_mode=S_IFREG|0644, st_size=1264, ...}) = 0
[ 257] [00007f2c63cf5767] openat(AT_FDCWD, "/usr/lib/python3.9/encodings/__pycache__/latin_1.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 3
[   5] [00007f2c63a6e3f5] fstat(3, {st_mode=S_IFREG|0644, st_size=1893, ...}) = 0
[  16] [00007f2c63a743f6] ioctl(3, TCGETS, 0x7ffc8c8dde30) = -1 ENOTTY (Inappropriate ioctl for device)
--
[   4] [00007f2c63a6e3a6] stat("/usr/lib/python3.9/io.py", {st_mode=S_IFREG|0644, st_size=3541, ...}) = 0
[ 257] [00007f2c63cf5767] openat(AT_FDCWD, "/usr/lib/python3.9/__pycache__/io.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 3
[   5] [00007f2c63a6e3f5] fstat(3, {st_mode=S_IFREG|0644, st_size=3406, ...}) = 0
[  16] [00007f2c63a743f6] ioctl(3, TCGETS, 0x7ffc8c8dde30) = -1 ENOTTY (Inappropriate ioctl for device)
--
[   4] [00007f2c63a6e3a6] stat("/usr/lib/python3.9/abc.py", {st_mode=S_IFREG|0644, st_size=4489, ...}) = 0
[ 257] [00007f2c63cf5767] openat(AT_FDCWD, "/usr/lib/python3.9/__pycache__/abc.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 3
[   5] [00007f2c63a6e3f5] fstat(3, {st_mode=S_IFREG|0644, st_size=5336, ...}) = 0
[  16] [00007f2c63a743f6] ioctl(3, TCGETS, 0x7ffc8c8dd000) = -1 ENOTTY (Inappropriate ioctl for device)
```
