### ISSUE TITLE
[BUG] salt-minion uses reverse dns to generate minion_id instead of local hostname/fqdn

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#62478]
**Description**
 salt-minion uses reverse dns to generate minion_id instead of local hostname/fqdn

- 2 x VMs (Vmware), CentOS 7
  
**Steps to Reproduce the behavior**
1. two servers, salt-master and minion
2. minion is a server with ip, which has a reverse DNS record different from the server configured hostname/fqdn
3. start `salt-minion` and look at `/etc/salt/minion_id`

**Expected behavior**
`/etc/salt/minion_id` to contain the server local hostname/fqdn, not whatever reverse DNS query returns for the IP address

**Screenshots**
```bash
[root@host1 ~]# hostname -f
host1.example.com
[root@host1 ~]# rm /etc/salt/minion_id
rm: remove regular file ‘/etc/salt/minion_id’? y
[root@host1 ~]# systemctl restart salt-minion
[root@host1 ~]# cat /etc/salt/minion_id
another-name-from-dns.example.com
[root@host1 ~]#
[root@host1 ~]# host host1.example.com
host1.example.com has address 10.10.10.5
[root@host1 ~]# host 10.10.10.5
5.10.10.10.in-addr.arpa domain name pointer another-name-from-dns.example.com.
[root@host1 ~]# rpm -q salt
salt-3002.2-1.el7.noarch
[root@host1 ~]# cat /etc/hostname
host1.example.com
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.66.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>
