### ISSUE TITLE
[BUG] Broken Jinja import in salt-ssh

### ISSUE THREAD

**Issue by Staon** [saltstack/salt#62472]
**Description**
Jinja imports are broken if salt-ssh is used - the imported template cannot be found.

**Setup**
`top.sls`
```
base:
  '*':
    - datetime.ntp
```

`datetime/ntp.sls`
```
{% from "datetime/map_ntp.jinja" import ntp with context %}

ntp:
  pkg.installed:
    - name: {{ ntp.pkg }}
  service.running:
    - name: {{ ntp.service }}
    - enable: True
    - require:
      - pkg: ntp
```

`datetime/map_ntp.jinja`
```
{% set ntp = salt['grains.filter_by']({
    'RedHat': {
        'pkg': 'ntp',
        'service': 'ntpd',
    },
}) %}
```

Both master and the minion run on CentOS 7.9.2009, Python version 3.6.8.

Salt-ssh version: 3004.2

**Steps to Reproduce the behavior**
```
# salt-ssh '*' state.apply
```
[salt_error_log.log](https://github.com/saltstack/salt/files/9351881/salt_error_log.log)

**Expected behavior**
The template is correctly imported.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed

       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: ANSI_X3.4-1968
       machine: x86_64
       release: 5.15.0-46-generic
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Additional context**
The problem happens in the lazy initialization of the `file_client` here: https://github.com/saltstack/salt/blob/604c955718aa3622236e0c131731a7bb54beb825/salt/utils/jinja.py#L106 The class `SaltCacheLoader` is created several times. First time it's created with `cachedir` pointing directory at the master side, instead of the temporary directory at the minion side. As the created `file_client` is cached in the class object, following constructor invocations with correct cache directory don't fix the issue.
