### ISSUE TITLE
Pillar renders fine, but causes a "flow mapping" error when used.

### ISSUE THREAD

**Issue by WraithCadmus** [saltstack/salt#62471]
Good morning, I have a state that manages the config of a Postgres DB, part of this is having a dict in the machine's pillar with a bunch of options in it. One of these options has a gnarly set of nested quotes, but I've found the right YAML and it renders in the pillar correctly. The value I want to get out of it is `'FIRST 2("barman-wal-archive", server01, server02)'`

### Pillar Example

``` yaml
postgres:
  conf:
    huge_pages: 'on'
    shared_buffers: 75MB
    full_page_writes: 'on'
    synchronous_standby_names: |
      'FIRST 2("barman-wal-archive", server01, server02)'
```

And it does render right here

```
[cadmus@master ~]$ sudo salt 'server01' pillar.item postgres:conf:synchronous_standby_names
[sudo] password for cadmus: 
server01:
    ----------
    postgres:conf:synchronous_standby_names:
        'FIRST 2("barman-wal-archive", server01, server02)'
```

### The problem

The issue is when I try to use it, in our state we pass in the whole pillar for ease of reference in jinja, using the `defaults` method.

```
postgres_main_config:
  file.managed:
    - name: /var/lib/pgsql/{{postgres.version|join('.')}}/data/postgresql.conf
    - source: salt://postgres/files/postgresql.conf.tmpl
    - template: jinja
    - user: postgres
    - group: postgres
    - mode: 600
    - defaults:
        postgres: {{ postgres }}
    - require:
      - pkg: postgres_install_server
    - listen_in:
      - service: postgresql-{{postgres.version|join('.')}}
```

But when I try to run my state, I get an error

```
server01:
    Data failed to compile:
----------
    Rendering SLS 'base:postgres' failed: while parsing a flow mapping
  in "<unicode string>", line 43, column 862
did not find expected ',' or '}'
  in "<unicode string>", line 43, column 1449
```

If I remove the double-quotes around `barman-wal-archive` it works, but it *needs* them due to the dashes and this is hardcoded in barman so I can't rename it. I also can't easily remove that outer layer of single quotes, as some options need them, and some don't.

Do I just need to push on to a newer version of Salt? Or is this a known thing? Is there an easy refactor I'm not seeing here? Forgive me if I've missed something in my report, first issue here.

#### Master
```
Salt Version:
          Salt: 3002.8
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.4.2
     docker-py: Not Installed
         gitdb: 0.6.4
     gitpython: 1.0.1
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.1.0
         smmap: 0.9.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.25.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

#### Minion
```
Salt Version:
          Salt: 3002.8
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.4.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.59.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

**Comment by WraithCadmus** [comment]
I realised I haven't shown how the `{{postgres}}` variable is populated, in case that's relevant. All our states have a map with some defaults, which merges with the pillar.

### postgres/init.sls
```
{%- from 'postgres/map.jinja' import postgres with context %}

postgres_do_thing:
  foo.bar:
    - name: foonly
```

### map.jinja
```
{% set postgres = salt.pillar.get('postgres', {
  'version': [10],
  'postgis': False,
}, merge=True) %}
```

So we get a merged version.
