### ISSUE TITLE
Installing Docker not possible any more due to missing SHA256 from Docker 2.10.0 release [BUG]

### ISSUE THREAD

**Issue by venomone** [saltstack/salt#62522]
**Description**
Installing Docker using SaltStack is currently not working anymore due to a change in docker 2.10

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Basically install docker like described in the official docs using saltstack.
In my case, I have two states for this:

```
docker_repository:
  pkgrepo.managed:
   - humanname: Docker
   - name: deb https://download.docker.com/linux/ubuntu focal stable
   - dist: focal
   - file: /etc/apt/sources.list.d/docker.list
   - gpgcheck: 1
   - key_url: https://download.docker.com/linux/ubuntu/gpg


docker_pkg:
  pkg.installed:
    - pkgs:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - containerd.io
    - require:
      - docker_repository
```

But I'm always running into:

```
----------
          ID: docker-compose-software-binary-install
    Function: file.managed
        Name: /usr/local/docker-compose-latest/bin//docker-compose
      Result: False
     Comment: Attempt 1: Returned a result of "False", with the following comment: "Unable to manage file: Error: HTTP 404: Not Found reading /docker/compose/releases/latest/download/docker-compose-Linux-x86_64.sha256"
              Attempt 2: Returned a result of "False", with the following comment: "Unable to manage file: Error: HTTP 404: Not Found reading /docker/compose/releases/latest/download/docker-compose-Linux-x86_64.sha256"
              Unable to manage file: Error: HTTP 404: Not Found reading /docker/compose/releases/latest/download/docker-compose-Linux-x86_64.sha256
     Started: 20:05:31.340670
    Duration: 131407.553 ms
     Changes:   
----------
          ID: docker-compose-software-binary-install-symlink-docker-compose
    Function: file.symlink
        Name: /usr/local/bin/docker-compose
      Result: False
     Comment: One or more requisite failed: docker.compose.software.binary.install.docker-compose-software-binary-install
     Started: 20:07:42.843606
    Duration: 0.004 ms
     Changes:   
```

**Expected behavior**
Docker should get installed without any kinda problem like before docker version 2.10

**Screenshots**

**Versions Report**
```
root@salt:/srv# salt --versions-report
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.27
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
```

</details>

**Additional context**
My guess is that this problem is coming from the following change in docker: https://github.com/docker/compose/issues/9772
The same issue also applies for Ansible.
