### ISSUE TITLE
[BUG] x509.pem_managed is not available

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#62551]
**Description**
After upgrading from 3004.2 to 3005 (classic package), it now reports that the `x509.pem_managed` state is not available.

**Setup**
```sls
{% for entry in salt['mine.get'](tgt='*', fun='x509.get_pem_entries').values() %}
  {% for path, contents in entry.items() %}
    {% if '/CA/certs/' in path %}
/usr/local/share/ca-certificates/{{ salt['file.basename'](path) }}:
  x509.pem_managed:
    - text: {{ contents | replace('\n', '') }}
    - onchanges_in:
      - cmd: update-ca-certificates
    {% endif %}
  {% endfor %}
{% endfor %}

update-ca-certificates:
  cmd.run:
    - name: /usr/sbin/update-ca-certificates
```
  
**Steps to Reproduce the behavior**
```
# salt-call state.apply
local:
----------
          ID: /usr/local/share/ca-certificates/mine/csrf-internal.crt
    Function: x509.pem_managed
      Result: False
     Comment: State 'x509.pem_managed' was not found in SLS 'cacerts'
              Reason: 'x509.pem_managed' is not available.
     Changes:
----------
          ID: update-ca-certificates
    Function: cmd.run
      Result: False
     Comment: One or more requisite failed: cacerts./usr/local/share/ca-certificates/example-internal.crt
     Started: 16:11:06.034110
    Duration: 0.003 ms
     Changes:

Summary for local
------------
Succeeded: 2
Failed:    2
------------
Total states run:     4
Total run time: 239.399 ms
```

**Expected behavior**
State should be available. M2Crypto is still installed.

**Versions Report**
<details><summary>salt-call --versions</summary>

```yaml
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.5.0
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.10.0
        Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-125-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**
The code for the state module is
```python
def __virtual__():
    """
    only load this module if the corresponding execution module is loaded
    """
    if "x509.get_pem_entry" in __salt__:
        return "x509"
    else:
        return (False, "Could not load x509 state: m2crypto unavailable")
```
And that module function loads just fine:
```
# salt-call x509.get_pem_entry

Passed invalid arguments: get_pem_entry() missing 1 required positional argument: 'text'.
[...]
```
