### ISSUE TITLE
[BUG] pkgrepo.managed sets wrong permissions on keys installed to /etc/apt/keyring

### ISSUE THREAD

**Issue by gvengel** [saltstack/salt#62569]
**Description**

When `pkgrepo.managed:aptkey` is set to `False` (or the `apt-key` command is unavailable) and `pkgrepo.managed:key_url` is pointed at an binary GPG key load via salt://, the key will be installed to /etc/apt/keyrings with the wrong permissions, causing apt to fail to load the key. Specifically, file is written to the minion cache as `0600`, then the permissions are copied to the destination file in /etc/apt/keyrings, but apt requires the keyring to be world readable.

**Setup**

Tested on Ubuntu 20.04 and 22.04 with salt 3005+ds-1.
  
**Steps to Reproduce the behavior**

* Create simple state `/srv/salt/test.sls`:
```
test_pkgrepo_bug:
  pkgrepo.managed:
    - name: deb [signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg arch=amd64] http://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main
    - file: /etc/apt/sources.list.d/salt.list
    - key_url: salt://salt-archive-keyring.gpg
    - aptkey: False
```
* Fetch the binary gpg key
```
wget -O /srv/salt/salt-archive-keyring.gpg https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest/salt-archive-keyring.gpg
```
* Apply the state
```
salt-call state.apply test
```
Will result in the following error:
```
local:
----------
          ID: test_pkgrepo_bug
    Function: pkgrepo.managed
        Name: deb [signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg arch=amd64] http://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main
      Result: False
     Comment: Failed to configure repo 'deb [signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg arch=amd64] http://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main': W: GPG error: https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E08A149DE57BFBE
              E: The repository 'http://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy InRelease' is not signed.
     Started: 22:44:40.685623
    Duration: 4053.726 ms
     Changes:
```

And you can see the file was created `0600`
```
# ls -l /etc/apt/keyrings/salt-archive-keyring.gpg
-rw------- 1 root root 1201 Aug 29 22:00 /etc/apt/keyrings/salt-archive-keyring.gpg
```

**Expected behavior**

/etc/apt/keyrings/salt-archive-keyring.gpg is created with permissions set to `0644`.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:31:15)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-46-generic
        system: Linux
       version: Ubuntu 22.04 jammy
```
</details>
