### ISSUE TITLE
[BUG] pkgrepo.managed creates zero byte gpg files when dearmoring contents to the same filename

### ISSUE THREAD

**Issue by gvengel** [saltstack/salt#62570]
**Description**

When `pkgrepo.managed:aptkey` is set to `False` (or the `apt-key` command is unavailable) and `pkgrepo.managed:key_url` is pointed at an ascii GPG key, where the filename in the `key_url` is the same as the file name in the `signed-by` repository setting (and ends in .gpg), the gpg key will be installed as a zero byte files. Specifically, `gpg --dearmor` is passed the same input and output files, which causes it to truncate the file before it can load the armored data.

**Setup**

Tested on Ubuntu 20.04 and 22.04 with salt 3005+ds-1.
  
**Steps to Reproduce the behavior**

* Create simple state `/srv/salt/test.sls`:
```
test_pkgrepo_bug:
  pkgrepo.managed:
    - name: deb [signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg arch=amd64] https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal main
    - file: /etc/apt/sources.list.d/salt.list
    - key_url: https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest/SALTSTACK-GPG-KEY.pub
    - aptkey: False
```
* Apply the state
```
salt-call state.apply test
```
Will result in the following error:
```
[ERROR   ] Command 'gpg' failed with return code: 2
[ERROR   ] stderr: gpg: no valid OpenPGP data found.
```

And you can see the file is empty:
```
# ls -lha /etc/apt/keyrings/salt-archive-keyring.gpg
-rw-r--r-- 1 root root 0 Aug 29 22:33 /etc/apt/keyrings/salt-archive-keyring.gpg
```

**Expected behavior**

/etc/apt/keyrings/salt-archive-keyring.gpg contains the dearmored key contents.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:31:15)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-46-generic
        system: Linux
       version: Ubuntu 22.04 jammy
```
</details>
