### ISSUE TITLE
[BUG] schedule.job_status output is partially empty

### ISSUE THREAD

**Issue by mdzidic** [saltstack/salt#62574]
**Description**
Command `schedule.job_status` output empty data for `_next_fire_time` and `_next_scheduled_fire_time` keys.

**Setup**

Original job setup:

Schedule Pillar
```yaml
schedule:
  run_state_users:
    function: state.apply
    args: 
      - users
    kwargs:
      test: False
    when: '12:00pm'
```

Test job:

Official CLI example from https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.schedule.html
```shell
salt '*' schedule.add job2 function='cmd.run' job_args="['date >> /tmp/date.log']" seconds=60
```
Minion:
- [x] VM running on a cloud service

Master:
- [x] Docker container

**Steps to Reproduce the behavior**

I first tried with my pillar job definition, then I tried to reproduce this issue with an official example.

1. Add schedule job:
`salt 'minion' schedule.add job2 function='cmd.run' job_args="['date >> /tmp/date.log']" seconds=60`

2. Run schedule.show_next_fire_tim CLI command:
`salt 'minion' schedule.show_next_fire_time job2`

Output:
```yaml
minion:
    ----------
    next_fire_time:
        2022-08-30T12:11:33
    result:
        True
```

3. Run schedule.job_status CLI command:
`salt 'minion' schedule.job_status job2`

Output:
```yaml
minion:
    ----------
    _next_fire_time:
    _next_scheduled_fire_time:
    _seconds:
        60
    _splay:
        None
    args:
        - date >> /tmp/date.log
    enabled:
        True
    function:
        cmd.run
    jid_include:
        True
    maxrunning:
        1
    name:
        job2
    seconds:
        60
    splay:
        None
```

Job is running fine on the minion.

**Expected behavior**
After running **schedule.job_status** command, it should return data for `_next_fire_time` and `_next_scheduled_fire_time` keys.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.26.8
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.26.4
        Python: 3.6.8 (default, Apr 11 2022, 08:25:52)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: oracle 8.6 
        locale: UTF-8
       machine: x86_64
       release: 5.6.14-x86_64-linode135
        system: Linux
       version: Oracle Linux Server 8.6 
```
</details>

**Additional context**
N/A
