### ISSUE TITLE
salt-ssh hangs when using sudo with password

### ISSUE THREAD

**Issue by theheckwr** [saltstack/salt#62603]
**Description**
When using salt-ssh with sudo and password the trace output stops with a line of the sudo prompt.

**Setup**
- simple roster file (with gpg renderer):
```yaml
#!yaml|gpg
host:
  host: <ip>
  user: <user>
  password: <gpg encriypted>
  sudo: True
  sudo_user: root
  tty: True
```
- lxc container on local machine
- passwords encrypted using gpg
  
**Steps to Reproduce the behavior**
run test.ping module (`salt-ssh 'host' test.ping`).
The trace output stops with the following lines:
```
""").decode("utf-8"))
'[salt:sudo:d11bd4221135c33324a6bdc09674146fbfdf519989847491e34a689369bbce23]passwd:'
```
and doesn't continue after several minutes

**Expected behavior**
I expected to receive the ping result:
```
host:
    True
```

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.15.0-46-generic
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**

I managed to get it running using changing the lines 26 and 27 (SUDO_PROMPT and SUDO_PROMPT_RE in the file `/usr/local/lib/python3.9/dist-packages/salt/client/ssh/shell.py` (on Debian 11) to the following:
```python
SUDO_PROMPT = "[salt:sudo:d11bd4221135c33324a6bdc09674146fbfdf519989847491e34a689369bbce23]passwd:"
SUDO_PROMPT_RE = re.compile("\[salt:sudo:d11bd4221135c33324a6bdc09674146fbfdf519989847491e34a689369bbce23\]passwd:", re.M)
```

However I don't have enough time to check if the regex was really the issue. For the two hosts I tested it against it worked like charm.
