### ISSUE TITLE
[BUG] docker_image.present erroring out: docker_image' __virtual__ returned False: 'docker.version' is not available.

### ISSUE THREAD

**Issue by mohaldu** [saltstack/salt#62602]
**Description**
Attempting to make use of docker_image.present fails.

Getting error message below: 
```----------
          ID: create docker images
    Function: docker_image.present
      Result: False
     Comment: State 'docker_image.present' was not found in SLS 'prometheus/prometheus'
              Reason: 'docker_image' __virtual__ returned False: 'docker.version' is not available.
     Changes:
```

**Setup**
Running on ubuntu 20.04 server. Docker and docker python are installed like follows:

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**

To install docker and pip.install the docker:

```
# Install docker

apt-transport-https:
  pkg.installed: []

docker_repository:
  pkgrepo.managed:
    - name: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    - file: /etc/apt/sources.list.d/docker.list
    - key_url: https://download.docker.com/linux/ubuntu/gpg
    - require:
      - pkg: apt-transport-https
    - require_in:
      - pkg: docker


docker:
  pkg.installed:
    - pkgs: [docker-ce, docker-compose-plugin]
  service.running:
    - name: docker
    - enable: true
    - reload: true
  pip.installed:
    - pkgs:
        - "docker"

restart_service:
  service.running:
    - name: salt-minion
    - enable: True
    - watch:
      - pip: docker
```

Then, running docker_image.present: 

```
create docker images:
  docker_image.present:
    - build: /root/test_docker
    - tag: prom_tester
    - force: true
```

**Expected behavior**
The command works, instead we get errors

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: 6.0.0
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.0
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-125-generic
        system: Linux
       version: Ubuntu 20.04 focal```
</details>

**Additional context**
I've tried restarting salt manually, tried reinstalling docker via pip, no success.
