### ISSUE TITLE
[BUG] Parallel salt.state with ssh fails if same minion is targeted

### ISSUE THREAD

**Issue by 808brinks** [saltstack/salt#62612]
**Description**
Parallel salt.state with ssh fails if same minion is targeted. The first minion is successful the other minion fail without a clear error.
 

**Setup**
Version 3005

parallel-same-minion.sls:
```
sleep-one:
  salt.state:
    - parallel: True
    - tgt: 'app1'
    - tgt_type: pcre
    - ssh: True
    - sls:
        - sleep

sleep-two:
  salt.state:
    - parallel: True
    - tgt: 'app1'
    - tgt_type: pcre
    - ssh: True
    - sls:
        - sleep
```

sleep.sls:
```
sleep:
  cmd.run:
    - name: sleep 2
```
  
**Steps to Reproduce the behavior**
Added the 2 sls files above and run: sudo salt-run state.orchestrate parallel-same-minion.

See the following output:

```
----------
          ID: sleep-one
    Function: salt.state
      Result: False
     Comment: Run failed on minions: app1
     Started: 16:01:55.617138
    Duration: 3500.82 ms
     Changes:   
              app1:
              
              Summary for app1
              -----------
              Succeeded: 0
              Failed:   0
              -----------
              Total states run:    0
              Total run time:  0.000 ms
----------
          ID: sleep-twp
    Function: salt.state
      Result: True
     Comment: States ran successfully. Updating app1.
     Started: 16:01:55.621592
    Duration: 5599.432 ms
     Changes:   
              app1:
              ----------
                        ID: sleep
                  Function: cmd.run
                      Name: sleep 2
                    Result: True
                   Comment: Command "sleep 2" run
                   Started: 16:01:58.902050
                  Duration: 2009.44 ms
                   Changes:   
                            ----------
                            pid:
                                1089286
                            retcode:
                                0
                            stderr:
                            stdout:
              
              Summary for app1
              ------------
              Succeeded: 1 (changed=1)
              Failed:    0
              ------------
              Total states run:     1
              Total run time:   2.009 s

```

**Expected behavior**
Either both results successful or some sort of error on one of the results. 
Now it just shows  Total states run:    0 for one of the results

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-16-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**
