### ISSUE TITLE
[BUG] Including Jinja template from absolute path broken

### ISSUE THREAD

**Issue by sabedevops** [saltstack/salt#62611]
**Description**.

Including Jinja template from absolute path broke with #62043 

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
`sudo salt '*' slsutil.renderer salt://jinja/to/render.j2 path_to_include_template=/absolute/path/to/template.j2`

**Expected behavior**
Properly include jinja templates when they are an absolute path. 

**Screenshots**

![image](https://user-images.githubusercontent.com/22971615/188024105-b44a894a-20bf-42c7-a2ab-c4d196afecd5.png)

**Versions Report**

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1013-oracle
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**

The new `if` statement introduced in #62043 fails for absolute paths, and so the old logic that successfully found these in the `for` loop no longer runs:
https://github.com/saltstack/salt/blob/662cfbadfa454c83407216aad1762677348841a1/salt/utils/jinja.py#L200-L203

At this point, there is no early return, and we fall through to the `raise`:
https://github.com/saltstack/salt/blob/662cfbadfa454c83407216aad1762677348841a1/salt/utils/jinja.py#L222
