### ISSUE TITLE
[BUG] cannot use json_query Jinja filter in 3005 onedir

### ISSUE THREAD

**Issue by genaumann** [saltstack/salt#62613]
**Description**
After upgrading from 3004.2 to 3005, the Jinja Filter `json_query` isn't available anymore.
I installed the module like this: `salt-pip install jmespath`
After the successful installation, I restarted the salt-master and salt-minion deamons.
The command `salt-pip list` shows that the pip module `jmespath` is installed.

**Setup**

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
```
Rendering SLS 'base:icinga2.objects' failed: Jinja error: json_query requires jmespath module installed
Traceback (most recent call last):
  File "salt/utils/templates.py", line 469, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 28, in top-level template code
  File "salt/utils/data.py", line 1284, in json_query
    raise RuntimeError(err)
RuntimeError: json_query requires jmespath module installed
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:31:09)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-17-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>
