### ISSUE TITLE
Jinja variable `'salt.utils.templates.AliasedLoader object'` has no attribute `'pkg'` [BUG]

### ISSUE THREAD

**Issue by jbartak** [saltstack/salt#62620]
**Description**
Running highstate with salt-ssh lead to this error.
```
pweb1:
    - Rendering SLS 'base:all' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pkg'; line 1
      
      ---
      /root/.bashrc:    <======================
        file.managed:
          - source: salt://all/conf/bash.bashrc
          - template: jinja
      
      install all needed dependencies:
      [...]
      ---
```

**Setup**

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details (Debian 11 VM on Proxmox)
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Run `salt-ssh <node> state.highstate`

**Expected behavior**
Working highstate with salt-ssh

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
# salt --versions-report
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-17-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**
N/A

**Comment by OrangeDog** [comment]
You haven't shared the contents of bash.bashrc, but this is probably a duplicate of #41794

**Comment by jbartak** [comment]
State:
```
/root/.bashrc:
  file.managed:
    - source: salt://all/conf/bash.bashrc
    - template: jinja
```

Content:
```
[ -z "$PS1" ] && return
PS1='\[\e[0;32m\]|{{ salt['grains.get']('osmajorrelease') }}|\[\e\][m[\u@{{ salt['grains.get']('id') }} \[\W\]: '
shopt -s checkwinsize
```

It is important to note that no matter if I remove state or not. It will always fail with error message pointing to the first state in SLS file.
