### ISSUE TITLE
[BUG] gitfs is suddenly a hassle with onedir package

### ISSUE THREAD

**Issue by hkbakke** [saltstack/salt#62637]
**Description**
I upgraded to the 3005 onedir package on my salt master. The salt-master is configured to use gitfs and git_pillar via pygit2. I expected this critical salt master functionality to "just work" but I actually had to install the pygit2 module using `salt pip install pygit2 --no-deps`. I used no-deps as pip drags in a newer version of cffi conflicting with the included onedir version if I don't. 

However, pygit2 fails during startup of the salt master because ssl setup fails. I only use ssh git urls, but being able to configure ca certificates location seems to be a requirement for the pygit2 module. 

During startup the salt master fails with:
```
2022-09-08 08:34:15,880 [salt.utils.gitfs :148 ][ERROR   ][1607008] Failed to import pygit2
Traceback (most recent call last):
  File "salt/utils/gitfs.py", line 108, in <module>
    import pygit2
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/pygit2/__init__.py", line 230, in <module>
    settings = Settings()
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/pygit2/settings.py", line 55, in __init__
    self._initialize_tls_certificate_locations()
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/pygit2/settings.py", line 61, in _initialize_tls_certificate_l
ocations
    self.set_ssl_cert_locations(
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/pygit2/settings.py", line 191, in set_ssl_cert_locations
    option(_pygit2.GIT_OPT_SET_SSL_CERT_LOCATIONS, cert_file, cert_dir)
_pygit2.GitError: OpenSSL error: failed to load certificates: error:00000000:lib(0):func(0):reason(0)
2022-09-08 08:34:16,151 [salt.master      :2475][INFO    ][1602761] User root Published command test.version with jid 2022090
8063416149168
```

I found that I could solve this by setting the SSL_CERT_FILE environment variable to the os default location which is `/etc/ssl/certs/ca-certificates.crt` in my case. I could not find a way to configure this in the configuration so I have to do it the cumbersome way by making an systemd override file `/etc/systemd/system/salt-master.service.d/override.conf` containing:
```
[Service]
Environment=SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
```
This fixes the master startup error, and minions can connect and execute states afterwards. However, for some reason if I execute salt-call for the local master minion I still get the pygit2 ssl cert error printed to the screen, while the states executes seemingly properly. To fix this I have to ensure the SSL_CERT_FILE env var is set for manual salt-call invokations of the minion on the master itself e.g:
```
sudo SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt salt-call state.apply
```
This is obviously cumbersome, so I would like  a way for this to be configured once only, prefererrably within saltstack, not using linux workarounds like systemd overrides and shell aliases.

* Also: pygit2 version is not reported when printing the version report even though it is available within the salt onedir env.
 
**Steps to Reproduce the behavior**
* Install onedir package
* Install missing pygit2 dependency in salt onedir env: `salt pip install pygit2 --no-deps`
* Install missing libgit2 dependency in OS (apt install libgit2-1.1 in Debian 11)
* Configure gitfs_provider as `pygit2` with valid gitfs configuration and repo
* Try to start salt master

**Expected behavior**
* Minimum: document how to use gitfs properly with onedir
* Expected: pygit2 should be included in onedir package and SSL_CERT_DIR/SSL_CERT_FILE env params should be configurable globally in the salt master config or automatically set to a sane default.

**Versions Report**
```
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:31:09)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-17-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```

```
# sudo salt pip freeze
pygit2==1.10.1
```

**Comment by garethgreenaway** [comment]
Confirmed this is an issue, as a workaround when installing using `salt pip` if you set the `SSL_CERT_DIR` variable when installing then it works as expected.

**Comment by garethgreenaway** [comment]
I did a bit more digging and found this:

Using system version of Python
```root@host-150:~/pygit2-1.4.0# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.get_default_verify_paths
<function get_default_verify_paths at 0x7f885d201940>
>>> ssl.get_default_verify_paths()
DefaultVerifyPaths(cafile=None, capath='/usr/lib/ssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/usr/lib/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/usr/lib/ssl/certs')
>>> quit
Use quit() or Ctrl-D (i.e. EOF) to exit
>>> 

Using Salt onedir version of Python
```
root@host-150:~/pygit2-1.4.0# salt shell
Python 3.9.13 (main, Sep  6 2022, 21:38:11) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import ssl
>>> ssl.get_default_verify_paths()
DefaultVerifyPaths(cafile=None, capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/usr/local/openssl11/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/usr/local/openssl11/certs')
```

When installing pygit2 the above function is used to determine where the SSL certs are located, since we're building the onedir packages on a different system the locations are different than Debian.  In the returned data the two environment variables that can be used to override the values are visible.  This seems like the solution for installing pygit2 using onedir packages and we should document this.

**Comment by garethgreenaway** [comment]
Posted too soon, I had to have the environmental variable `SSL_CERT_DIR` set to the correct path when starting the Salt master or when running the shell command in the onedir environment when loading pygit2 to ensure that I didn't see an error.

**Comment by waynew** [comment]
I wonder if we can adjust the way our onedir is built to ensure that the paths are correct :thinking:

**Comment by hkbakke** [comment]
> Posted too soon, I had to have the environmental variable `SSL_CERT_DIR` set to the correct path when starting the Salt master or when running the shell command in the onedir environment when loading pygit2 to ensure that I didn't see an error.
> 
> I'm not sure building the `onedir` packages with pygit2 included would solve the issue as the path to the SSL certs is still going to be different.

The "include pygit2" part is not really about the SSL cert path working out of the box, but that I, perhaps naively, expect the onedir package to contain the needed dependencies to use what I personally consider core functionality for the salt master, although I know many probably runs without git backing in simpler deployments. I personally can live with configuring the cert path in a salt config file or some other documented location.

**Comment by garethgreenaway** [comment]
As mentioned before including `pygit2` in the `onedir` package wouldn't have completely solved the issue in this particular case.  Since we build the `onedir` portion on the packages, eg. Python and all the requirements, on a CentOS 7 host (to ensure the lowest common denominator for libraries such as GLIBC) the location for the SSL certs will be different than where it ultimately runs.  

To ensure that pygit2 is able to load and the traceback doesn't show up, is to ensure that the SSL_CERT_DIR environment variable is always available, the fix that I've submitted and will be available in the upcoming 3005.1 release is to include some shell code in the helper scripts for running salt commands, eg. salt, salt-call, salt-key, salt-master, and salt-minion, that set the SSL_CERT_DIR environmental variable (if it's not already set) with the output from `openssl version -d`, which is the correct location for the local system where the Salt command is running.

**Comment by garethgreenaway** [comment]
Fixed by https://gitlab.com/saltstack/open/salt-pkg/-/merge_requests/202

**Comment by transistortim** [comment]
The issue still exists with `salt-ssh` in 3005.1. Is there a particular reason why the fix was not applied to salt-ssh? If I manually extend the salt-ssh script with what was added to the other commands, the errors are gone.

<details><summary>Output without applying the fix (same as above)</summary>


```shell
% salt-ssh minion test.ping
[ERROR   ] Failed to import pygit2
Traceback (most recent call last):
  File "salt/utils/gitfs.py", line 108, in <module>
    import pygit2
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/pygit2/__init__.py", line 230, in <module>
    settings = Settings()
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/pygit2/settings.py", line 55, in __init__
    self._initialize_tls_certificate_locations()
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/pygit2/settings.py", line 61, in _initialize_tls_certificate_locations
    self.set_ssl_cert_locations(
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/pygit2/settings.py", line 191, in set_ssl_cert_locations
    option(_pygit2.GIT_OPT_SET_SSL_CERT_LOCATIONS, cert_file, cert_dir)
_pygit2.GitError: OpenSSL error: failed to load certificates: error:00000000:lib(0):func(0):reason(0)
[CRITICAL] No suitable gitfs provider module is installed.
[CRITICAL] No suitable gitfs provider module is installed.
minion:
    <minion summary>
```
</details>

Fixed salt-ssh (lines copied from https://gitlab.com/saltstack/open/salt-pkg/-/blob/11547966959ca2e522862f52268ff6fa1e53f592/pkgs/debian/debian/one-dir-bins/salt):
```shell
% cat /usr/bin/salt-ssh
#!/bin/bash
if [[ -z "${SSL_CERT_DIR}" ]] && command -v openssl &> /dev/null; then
  _DIR=$(openssl version -d)
  export SSL_CERT_DIR=${_DIR:13:-1}"/certs"
  export SSL_CERT_FILE=${_DIR:13:-1}"/cert.pem"
fi
exec /opt/saltstack/salt/run/run ssh "${@:1}"
```

Output with fixed salt-ssh:
```
% salt-ssh minion test.ping
minion:
    <minion summary>
```

<details><summary>Salt version report (onedir)</summary>

```yaml
% salt-ssh --versions-report
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Dec 14 2022, 15:47:34)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian n/a bookworm
        locale: utf-8
       machine: x86_64
       release: 6.0.0-6-amd64
        system: Linux
       version: Debian GNU/Linux n/a bookworm
```
</details>

Despite the version report, pygit2 is installed (as already mentioned above):

```
% salt-pip freeze
pygit2==1.6.1
```

**Comment by rosscdh** [comment]
still happens
```
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.31
        Jinja2: 3.1.0
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.6.1
        Python: 3.7.13 (default, Apr 20 2022, 03:16:50)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: alpine 3.14.6
        locale: UTF-8
       machine: x86_64
       release: 5.15.0-60-generic
        system: Linux
       version: Alpine Linux 3.14.6
       
       
echo $SSL_CERT_DIR
/etc/ssl/certs
```

**Comment by OrangeDog** [comment]
3006-RC is now available. Is there any improvement there?

**Comment by peterbaumert** [comment]
> 3006-RC is now available. Is there any improvement there?

I still have the error with 3006.0 and the netbox external pillar :(

**Comment by MTecknology** [comment]
Why was this closed? The error appears to remain unresolved, and the broader issue persists. Why are we compelled to embrace such a broken and non-standard installation options? Could the onedir format not have undergone some reasonable level of testing before being imposed on users?

**Comment by Darkentik** [comment]
I am still having this issues and cannot understand why this was closed.

**Comment by max-arnold** [comment]
Gitpython installed via salt-pip works like a charm on 3006.5 with the following config:

```yaml
gitfs_provider: gitpython
gitfs_update_interval: 120
gitfs_global_lock: false
file_roots: {}

fileserver_backend:
  - roots
  - gitfs

gitfs_remotes:
  - https://USER:DEPLOY_TOKEN@gitlab.com/ORG/REPO.git:
    - base: main
    - root: states

top_file_merging_strategy: same

# Git Pillar
pillar_roots: {}

git_pillar_provider: gitpython
git_pillar_base: main
git_pillar_branch: main
pillarenv_from_saltenv: true
ext_pillar_first: true
git_pillar_update_interval: 120
git_pillar_global_lock: false

ext_pillar:
  - git:
    - main https://USER:DEPLOY_TOKEN@gitlab.com/ORG/REPO.git:
      - root: pillar
```

`main` (referenced 4 times in the above snippet) is the primary git branch that is mapped to the `base` saltenv, state files are kept in the `states` repo folder, pillars are in the `pillar` folder
