### ISSUE TITLE
[BUG] pip.is_installed doesn't work for capitalised names

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#62640]
**Description**
It appears that `pip.is_installed` always returns `False` if the package name contains any capital letters.

**Setup**
Tested with both 3004.2 and 3005 (classic package).
  
**Steps to Reproduce the behavior**
```yaml
# pip3 freeze
bsddb3==6.2.7
cached-property==1.5.2
certifi==2019.11.28
cffi==1.14.5
chardet==3.0.4
charset-normalizer==2.0.0
command-not-found==0.3
contextvars==2.4
croniter==0.3.29
dbus-python==1.2.16
distro==1.4.0
distro-info===0.23ubuntu1
elasticsearch==7.17.6
gitdb2==2.0.6
GitPython==3.0.7
idna==2.8
immutables==0.14
Jinja2==2.10.1
language-selector==0.1
M2Crypto==0.31.0
MarkupSafe==1.1.0
msgpack==0.6.2
netifaces==0.10.4
psutil==5.5.1
pycparser==2.20
pycryptodomex==3.6.1
pygit2==1.10.1
PyGObject==3.36.0
python-apt==2.0.0+ubuntu0.20.4.8
python-dateutil==2.7.3
python-gnupg==0.4.5
pytz==2019.3
PyYAML==5.3.1
pyzmq==20.0.0
requests==2.28.1
salt==3004.2
setproctitle==1.1.10
six==1.14.0
smmap2==2.0.5
ssh-import-id==5.10
systemd-python==234
ubuntu-advantage-tools==27.10
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
# salt-call --local pip.is_installed salt
local:
    True
# salt-call --local pip.is_installed python-dateutil
local:
    True
# salt-call --local pip.is_installed GitPython
local:
    False
# salt-call --local pip.is_installed Jinja2
local:
    False
# sudo salt-call --local pip.is_installed jinja2
local:
    True
```

**Expected behavior**
Packages that are installed should return `True`. Ideally, names should be case-insensitive, as in `pip`.

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 1.5.0
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.10.1
        Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-125-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>
