### ISSUE TITLE
file.recurse see only last mounted hgfs repository

### ISSUE THREAD

**Issue by AlexanderplUs** [saltstack/salt#62648]
**Description**
When I setup more than one source in hgfs_remotes (with different mountpoints) than `file.recurse` with all these mountpoints except the last gives an error `Recurse failed: none of the specified sources were found` on apply

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

config in **master**:
```
fileserver_backend:
  - roots
  - hgfs
  
hgfs_remotes:
  - file:///repos/service1:
    - mountpoint: service1
  - file:///repos/service2:
    - mountpoint: service2
```

**states/service1.sls**:
```
service1:
  file.recurse:
    - name: /target_dir/service1
    - source: salt://service1
    - makedirs: True
    - clean: True
```

**states/service2.sls**:
```
service2:
  file.recurse:
    - name: /target_dir/service2
    - source: salt://service2
    - makedirs: True
    - clean: True
```
  
**Steps to Reproduce the behavior**
Add more than one source in hgfs_remotes and try to use first of them in `file.recurse`. It is **service1** in my example.
Important to note that `salt '*' cp.list_master_dirs` shows all mountpoints and their content properly:
```
  - service1
  - service1/dir1
  - service1/dir2
  - service2
  - service2/dir1
  - service2/dir2
```

But `salt '*' state.apply service1` fails and `salt '*' state.apply service2`works
If I comment out second `hgfs_remotes` source than after master restart `salt '*' state.apply service1`works.

**Expected behavior**
I expect that all mountpoints are available for usage

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: Not Installed
        Python: 3.7.13 (default, Jul  5 2022, 09:57:23)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: Not Installed
 
System Versions:
          dist: freebsd 13.1 
        locale: UTF-8
       machine: amd64
       release: 13.1-RELEASE
        system: FreeBSD
       version: FreeBSD 13.1 
```
</details>
