### ISSUE TITLE
[BUG] vault ext_pillar does not support KV v2 properly

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#62651]
**Description**
Using KV v2 paths in the Vault ext_pillar results in "data" and "metadata" pillar keys, where "data" contains the expected pillar values.

**Setup**
Essential master configuration:
```
[...]
ext_pillar:
  - vault: path=salt/pillar/path
[...]
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (KVM)

**Expected behavior**
The pillar to contain data.

**Screenshots**
```
$ salt-run pillar.show_pillar minion
[...]
data:
    ----------
    foo:
        bar
metadata:
    ----------
    created_time:
[...]
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.9
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 3.10.1
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.8.12 (default, Sep 26 2021, 13:12:50)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: openbsd 7.0
        locale: utf-8
       machine: amd64
       release: 7.0
        system: OpenBSD
       version: OpenBSD 7.0
```
</details>

**Additional context**
[This part](https://github.com/saltstack/salt/blob/998cb0f951f32f79917109f95edcb5d3cee83cec/salt/pillar/vault.py#L165-L166) does not check for KV v2. PR incoming soon.
