### ISSUE TITLE
[BUG] file.directory_exists on a newly created directory is ignored

### ISSUE THREAD

**Issue by kafosa** [saltstack/salt#62667]
**Description**
Running a simple state with file.directory_exists against a newly created directory is being ignored on Windows.

```
{%- if salt['file.directory_exists']('c:\app\oracle\product\19.0.0\32') %}
check-env:
 cmd.run:
   - name: '[System.Environment]::GetEnvironmentVariable("TNS_ADMIN")'
   - shell: PowerShell
{%- endif %}

Summary for local
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
Total run time:  0.000 ms
```

Escaping the directory path gives the same results as above.

`{%- if salt['file.directory_exists']('c:\\app\\oracle\\product\\19.0.0\\32') %}`

Running from command line yields the expected result.

```
salt-call --local file.directory_exists 'C:\app\oracle\product\19.0.0\32'
local:
    True
```

**Expected Behaviour**
Modifying the state to a folder that already exists works as intended

```
{%- if salt['file.directory_exists']('c:\salt') %}
check-env:
 cmd.run:
   - name: '[System.Environment]::GetEnvironmentVariable("TNS_ADMIN")'
   - shell: PowerShell
{%- endif %}
```

```
salt-call state.apply techone.oracle_odac_tst test=True
local:
----------
          ID: check-env
    Function: cmd.run
        Name: [System.Environment]::GetEnvironmentVariable("TNS_ADMIN")
      Result: None
     Comment: Command "[System.Environment]::GetEnvironmentVariable("TNS_ADMIN")" would have been executed
     Started: 15:03:20.913843
    Duration: 0.0 ms
     Changes:

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:   0.000 ms
```

**Versions Report**
salt-call --versions-report
```
Salt Version:
          Salt: 3002.6

Dependency Versions:
          cffi: 1.12.2
      cherrypy: 17.4.1
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.7
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.4
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 2.0.5
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2016Server
        system: Windows
       version: 2016Server 10.0.14393 SP0
```
