### ISSUE TITLE
[BUG] pdbedit.create fails with cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by mariushoch** [saltstack/salt#62670]
**Description**
When using `pdbedit.create` it fails with `Passed invalid arguments: cannot use a string pattern on a bytes-like object.`.

**Setup**
Can be reproduced using the below Dockerfile:
```
FROM docker.io/rockylinux/rockylinux:8

RUN dnf -y install "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
RUN dnf --setopt=install_weak_deps=False install -y 'dnf-command(config-manager)' sudo samba
RUN dnf -y config-manager --set-enabled powertools
RUN curl -o /root/bootstrap-salt.sh -L https://bootstrap.saltproject.io
RUN bash /root/bootstrap-salt.sh -X
RUN sh -c 'echo "username map = /etc/samba/user_map" > /etc/samba/smb.conf'
RUN adduser foo
```
```
podman build -f Dockerfile --tag salt-pdbedit-test
podman run --rm --security-opt label=disable salt-pdbedit-test salt-call --id "test" --local pdbedit.create foo bar
```
This yields `Passed invalid arguments: cannot use a string pattern on a bytes-like object.`
  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
Samba user should be created/ updated.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov  9 2021, 14:44:26)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 8.5 Green Obsidian
        locale: UTF-8
       machine: x86_64
       release: 5.19.6-200.fc36.x86_64
        system: Linux
       version: Rocky Linux 8.5 Green Obsidian
```
</details>

**Additional context**
