### ISSUE TITLE
[BUG] network.system state - templates/rh_ip/network.jinja missing RES_OPTIONS setting

### ISSUE THREAD

**Issue by dsmoljanovic** [saltstack/salt#62690]
**Description**
Running `network.system` state removes line with `RES_OPTIONS=ndots:2`. Similar to that, trying to set it through state fails and just ignores it. `RES_OPTIONS` is valid setting for the `/etc/sysconfig/network` file.

Further investigation led me to see that settings are hardcoded in file `salt/templates/rh_ip/network.jinja` and `res_options` is missing in this template making the states ignore it or remove it from the file if it has been added by other means.

RHEL8 (Alma 8), Salt 3005, Python 3.6.8.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.
- [ ] on-prem machine
- [x] VM - VMware
- [x] VM running on a EC2, alma 8.6
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
1. add by hand custom line in `/etc/sysconfig/network`. Example:
```
NETWORKING=yes
HOSTNAME=something.example.com
RES_OPTIONS=ndots:2
```

2. create a state that modifies hostname:
```
set-hostname:
  network.system:
    - hostname: something.example.com
    - apply_hostname: True
    - retain_settings: True
```
3. run state and examine output (or test the state; it will show same diff):
```
          ID: set-hostname
    Function: network.system
      Result: None
     Comment: Global network settings are set to be updated:
              ---
              +++
              @@ -1,3 +1,2 @@
               NETWORKING=yes
               HOSTNAME=something.example.com
              -RES_OPTIONS=ndots:2
     Started: 18:39:52.957997
    Duration: 8.201 ms
     Changes:
```

**Expected behavior**
I expected that RES_OPTIONS is supported as it is a valid option.

**Versions Report**
<details><summary>salt --versions-report</summary>

Master is on CentOS7, minion on Alma 8.6. Salt versions are the same.

```yaml
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 4.4.169-1.el7.elrepo.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>
