### ISSUE TITLE
[BUG] Thorium starts flooding LOGs with State '<object>' was not found in SLS <SLS file>

### ISSUE THREAD

**Issue by ddelhoum** [saltstack/salt#62691]
**Description**
 When using a path to thorium files, i.e.

```
thorium_roots:
  base:
     - /srv/salt/master/thorium

```
salt-master flood  LOGs with messages like :

```
salt-master[177189]: [ERROR   ] State '<object>' was not found in SLS '<SLS file>'
salt-master[177189]: Reason: '<object>' is not available.
```

**Setup**

/etc/salt/master

```
##### Primary configuration settings #####
##########################################

default_include: master.d/*.conf

user: root

conf_file: /etc/salt/master

verify_env: False

external_auth:
  pam:
    login:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'

file_recv: True

state_output: mixed

file_roots:
  base:
    - /srv/salt/base

top_file_merging_strategy: same


default_top: base

fileserver_backend:
  - git

gitfs_provider: pygit2

gitfs_global_lock: False
git_pillar_global_lock: False

pillar_roots:
  base:
    - /srv/salt/pillar/base

pillarenv_from_saltenv: True

######        thorium Settings        #####
###########################################
engines:
  - thorium

thorium_roots:
  base:
    - /srv/salt/master/thorium
```

Please be as specific as possible and give set-up details.

- [X] VM running on promox 6.2.4

**Steps to Reproduce the behavior**

Configure a thorium_roots in /etc/salt/master

**Expected behavior**
master found sls file in the base directory and not in thorium directory

**Versions Report**

```
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: 1.5.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: 1.10.1
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```

**Additional context**
In the official doc (and others on the Net) the setting to start thorium engine looks like : 

```
engines:
  - thorium {}
```

With braces, thorium won't start and this message is found in debug mode : 

```
[DEBUG   ] The functions from module 'thorium' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'webhook' are being loaded by dir() on the loaded module
[DEBUG   ] Could not LazyLoad thorium {}.start: 'thorium {}.start' is not available.

```
With salt-master in debug mode, i found :

```
[DEBUG   ] No contents found in top file. If this is not expected, verify that the 'file_roots' specified in 'etc/master' are accessible. 
The 'file_roots' configuration is: {'base': ['/srv/salt/master/thorium']}
```

This is incorrect, the right file_roots is:

```
file_roots:
  base:
    - /srv/salt/base

```

/srv/salt/master/thorium is the thorium_roots path
