### ISSUE TITLE
[BUG] Timeouts when targeting multiple deltraproxy controlled proxies

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#62708]
**Description**
When targeting multiple proxy minions controlled using Deltraproxy, the commands will timeout.

**Setup**
Configure deltaproxy minion with 3+ proxy minions and launch.

**Steps to Reproduce the behavior**
Target multiple proxy minions so that the target result is 3+ proxy minions.  Watch as results slowly return,, checking proxy minion logs should indicate a SaltTimeout exception has occurred.

**Expected behavior**
Result should return in a timely manner.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
$ salt --versions-report
Salt Version:
          Salt: 3005+43.gd4be0e3959
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: Not Installed
        Python: 3.9.12 (main, Jul 20 2022, 11:53:24)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 21.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
```
</details>
