### ISSUE TITLE
[QUESTION] how to append data to a config file using a pillar in salt

### ISSUE THREAD

**Issue by ramcharantibco** [saltstack/salt#62710]
**Description**
i wrote a salt state as below which writes data to config.yaml

```
   file.append: 
    - name: /etc/xentrax/config.yml
    - text: |
       tunnel: xentrax
       credentials-file: /roor/.xentrax/xentrax.json
       logfile: /var/log/xentrax.log
       loglevel: info
```

now i want to append some sensitive data to this config.yaml using a pillar. the data is sensitive data and i want to maintain using a pillar. the data i want to append is below

    ingress:
      - hostname: shop.xentrax.com
      - keyid: xxxxxxxxxxxxxxxxxxx
        originRequest:
          httpHostHeader: shop.xentrax.com
          originServerName: shop.xentrax.com
        service: https://localhost:443
      - service: http_status:404
      
 the final data in the config.yaml after applying pillar would be like below. How to write that pillar? i am pretty new to saltstack. please help me. File attached

```
   tunnel: xentrax
   credentials-file: /roor/.xentrax/xentrax.json
   logfile: /var/log/xentrax.log
   loglevel: info
   ingress:
    - hostname: shop.xentrax.com
    - keyid: xxxxxxxxxxxxxxxxxxx
      originRequest:
       httpHostHeader: shop.xentrax.com
       originServerName: shop.xentrax.com
       service: https://localhost:443
    - service: http_status:404
```

[append.txt](https://github.com/saltstack/salt/files/9599418/append.txt)

**Comment by OrangeDog** [comment]
```yaml
# pillar
xentrax_ingress:
  ingress:
    - hostname: shop.xentrax.com
    - keyid: xxxxxxxxxxxxxxxxxxx
      originRequest:
        httpHostHeader: shop.xentrax.com
        originServerName: shop.xentrax.com
      service: https://localhost:443
    - service: http_status:404
```
Assuming your final output doesn't have to literally be that, only that it is valid YAML:
```yaml
# state
/etc/xentrax/config.yml:
  file.append: 
    - text: |
      tunnel: xentrax
      credentials-file: /roor/.xentrax/xentrax.json
      logfile: /var/log/xentrax.log
      loglevel: info
      {{ pillar["xentrax_ingress"] | tojson }}
```
If you can manage a whole file instead of appending to it, then `file.serialized` would be even better.

For further community help, please see the [Salt Community Slack](https://saltstackcommunity.slack.com/).
