### ISSUE TITLE
[BUG] 3005 salt-cloud 'ascii' codec can't decode byte 0xe2

### ISSUE THREAD

**Issue by zyxep** [saltstack/salt#62727]
**Description**
After upgrading to 3005 (onedir) salt-cloud reports ascii codec error.
`[ERROR   ] There was a query error: 'ascii' codec can't decode byte 0xe2 in position 80: ordinal not in range(128)`

**Setup**

My template/map file
```
vmware:
  server-name-001:
    num_cpus: 1
    memory: 2GB
    dns_servers:
      - 1.1.1.1
    domain: example.tld
    minion:
      grains:
        roles:
          - highstate
    folder: infrastructure
    devices:
     network:
       Network adapter 1:
         name: d1603_PROD
         domain: example.tld
         gateway: [10.0.0.1]
         switch_type: distributed
         subnet_mask: 255.255.0.0
```

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details: **vmware**
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

**Comment by OrangeDog** [comment]
Where is that message seen, and what triggers it?

What is the output of `salt --versions-report`?

**Comment by zyxep** [comment]
It's coming at the command `salt-cloud` right after deploying saltstack to the vm.
no upgrade, my profile is set to have script_args: onedir 3005 for bootstrap.

```
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: 5.0.3
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:31:04)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 20.04 focal
        locale: ascii
       machine: x86_64
       release: 5.4.0-104-generic
        system: Linux
       version: Ubuntu 20.04 focal
```

**Comment by OrangeDog** [comment]
> locale: ascii

Is probably the issue. It's the CLI trying to print the results but there are non-ASCII bytes in it.
Try changing your locale to e.g. `C.UTF-8` or `da_DK.utf8`

**Comment by zyxep** [comment]
This is my locale:
```
➜  ~ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_DK.utf8
LANGUAGE=en_DK.utf8
LC_CTYPE=UTF-8
LC_NUMERIC="en_DK.utf8"
LC_TIME="en_DK.utf8"
LC_COLLATE="en_DK.utf8"
LC_MONETARY="en_DK.utf8"
LC_MESSAGES="en_DK.utf8"
LC_PAPER="en_DK.utf8"
LC_NAME="en_DK.utf8"
LC_ADDRESS="en_DK.utf8"
LC_TELEPHONE="en_DK.utf8"
LC_MEASUREMENT="en_DK.utf8"
LC_IDENTIFICATION="en_DK.utf8"
LC_ALL=
```

**Comment by OrangeDog** [comment]
Something is amiss, as your output from `salt --versions-report` says it's using an ascii locale.
As you can see, you're also getting errors from your `locale` command, I'd look there first.

**Comment by zyxep** [comment]
yup, and i didn't get this error when i was on 3004, it only comes up after switch to 3005 onedir

**Comment by johnbrown-yoti** [comment]
I'm also seeing this issue since upgrading from 3004.1 to 3005 and my locales are set to UTF-8. Removing the "offending" character has resolved the issue but in 2022 we should be able to use UTF-8.

Error...
```
Oct 19 08:49:09 vm0 salt-minion[1271]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6189: ordinal not in range(128)
Oct 19 08:49:09 vm0 salt-minion[1271]: Traceback (most recent call last):
Oct 19 08:49:09 vm0 salt-minion[1271]:   File "/usr/lib/python3/dist-packages/salt/modules/saltutil.py", line 79, in _get_top_file_envs
Oct 19 08:49:09 vm0 salt-minion[1271]:     return __context__["saltutil._top_file_envs"]
Oct 19 08:49:09 vm0 salt-minion[1271]:   File "/usr/lib/python3/dist-packages/salt/loader/context.py", line 78, in __getitem__
Oct 19 08:49:09 vm0 salt-minion[1271]:     return self.value()[item]
```

version report from the minion
```
$ salt-minion --versions-report
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Mar 15 2022, 13:55:28)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5

System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-125-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```

version report from the master
```
$ salt --versions-report
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.14.0
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-125-generic
        system: Linux
       version: Ubuntu 20.04 focal

```

**Comment by OrangeDog** [comment]
@johnbrown-yoti and you're not using onedir?

**Comment by johnbrown-yoti** [comment]
no I am not using onedir. The offending character was in the top file.

Something to note is that first run (triggered by salt reactor) would fail but manually running `state.apply` worked fine.

**Comment by johnbrown-yoti** [comment]
Something to note is that I'm only seeing this when triggering a highstate via cmd.run. For some context we have reactor code that runs a highstate only when a machine is first built.

```
{# When a server connects for the first time run state.apply  #}
highstate_run:
   local.cmd.run:
    - tgt: {{ data['id'] }}
    - args:
      - cmd: if [ ! -f "/etc/salt/saltfirstrun.dontdelete" ] ; then salt-call saltutil.sync_all; salt-call grains.items > /etc/salt/saltgrains.dontdelete; salt-call state.apply > /etc/salt/saltfirstrun.dontdelete ;fi
 ``` 
This fails due to non-ascii characters `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2: ordinal not in range(128)`. However, if I run a highstate from the salt master I don't get any errors. I also don't see any errors if i initiate salt-call locally on the machine.

To be clear there are 3 scenarios here...

1. From the salt master, run a highstate on the minion `vm0` - This works
2. From the minion, use `salt-call state.apply` to run a highstate locally on `vm0` - This works
3. From the salt master, target `vm0` and use `cmd.run "salt-call state.apply"` - This fails with the ASCII error

I'm also seeing different output from `salt-call --versions-report` when running locally vs via `cmd.run`. Specifically `locale` via cmd.run is showing `ANSI_X3.4-1968`, but I have no idea where this is being introduced.


Locally from `vm0`
```
$ salt-call --versions-report
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Mar 15 2022, 13:55:28)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5

System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-125-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```

From the salt master via `cmd.run`...

```
$ sudo salt 'vm0' cmd.run 'salt-call --versions-report'
vm0:
    Salt Version:
              Salt: 3005

    Dependency Versions:
              cffi: Not Installed
          cherrypy: Not Installed
          dateutil: 2.6.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.10
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 0.5.6
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: Not Installed
          pycrypto: Not Installed
      pycryptodome: 3.4.7
            pygit2: Not Installed
            Python: 3.6.9 (default, Mar 15 2022, 13:55:28)
      python-gnupg: 0.4.1
            PyYAML: 3.12
             PyZMQ: 17.1.2
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.2.5

    System Versions:
              dist: ubuntu 18.04 Bionic Beaver
            locale: ANSI_X3.4-1968
           machine: x86_64
           release: 5.4.0-125-generic
            system: Linux
           version: Ubuntu 18.04 Bionic Beaver
```

**Comment by OrangeDog** [comment]
By running it a different way it's using a different environment with different locale variables.

Why this has changed between 3004 and 3005 I don't know, unless that's not the only thing you've changed.

**Comment by johnbrown-yoti** [comment]
> Why this has changed between 3004 and 3005 I don't know, unless that's not the only thing you've changed.

Standard package upgrades, but no config changes. I'll try rolling back only salt to v3004 to confirm that fixes the issue while keeping all else the same.

adding `export LC_CTYPE="C.UTF-8"` seems to force the locale back to UTF-8 but it's not really an ideal solution.

```
{# When a server connects for the first time run state.apply  #}
highstate_run:
   local.cmd.run:
    - tgt: {{ data['id'] }}
    - args:
      - cmd: export LC_CTYPE="C.UTF-8"; if [ ! -f "/etc/salt/saltfirstrun.dontdelete" ] ; then salt-call saltutil.sync_all; salt-call grains.items > /etc/salt/saltgrains.dontdelete; salt-call state.apply > /etc/salt/saltfirstrun.dontdelete ;fi
```
