### ISSUE TITLE
[BUG] The Salt Minion is shutdown

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#62741]
**Description**
A minion named `minion` can't be targeted:

**Setup**

```
root@master:~# salt --version
salt 3005

root@master:~# salt-key
Accepted Keys:
minion
Denied Keys:
Unaccepted Keys:
Rejected Keys:

root@master:~# salt minion test.ping
The Salt Minion is shutdown.

root@master:~# salt -L minion test.ping
minion:
    True
```

- [ x] onedir packaging
- [ x] used bootstrap to install

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:31:04)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-77-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>
