### ISSUE TITLE
[FEATURE REQUEST] Support salt:// sources for pip.installed

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#62758]
**Is your feature request related to a problem? Please describe.**
Distributing python packages to air-gapped systems where pypi is not available.

**Describe the solution you'd like**
To allow using Salt as a repository for python packages, similar to how `pkg.installed` can be used.

```yaml
pygit2:
  pip.installed:
    - name: salt://wheels/pygit2-1.10.1-cp38_amd64.whl
```
or possibly a separate argument.

**Describe alternatives you've considered**
Using a separate file states to first push the packages to the minion.

**Related**
#62751
