### ISSUE TITLE
require_in: - name in 3003.5 works, breaks in 3004.2

### ISSUE THREAD

**Issue by wmellema** [saltstack/salt#62766]
### Description of Issue

Whilst running tests on some of our modules, it appears that a syntax change has happened between version 3003.5 and 3004.2. 
Under 3003.5, we have some states that use the following syntax in order to "inject" state requirements into other states.
```
- require_in:
  - name: state_to_be_injected_with_require
```
In order to keep dynamic dependencies clean, this can be very useful. 
We have since updated some machines to 3004.2, and we're getting the following error:
```
local:
           Data failed to compile:
       ----------
           Cannot extend ID 'test2' in 'base:myformula'. It is not part of the high state.
       This is likely due to a missing include statement or an incorrectly typed ID.
       Ensure that a state with an ID of 'test2' is available
       in environment 'base' and to SLS 'myformula'
```
Not sure if this is a bug, or a feature that has been removed between the versions. 
If it's not a bug, how would I go about rewriting the states without more and more jinja templating?

### Setup
```
test1:
  file.directory:
      - name: /testfile1
      - require_in:
        - name: test2

test2:
  file.directory:
    - name: /testfile2
```

### Steps to Reproduce Issue
Use the above sls. Any 3003 build will succeed, any 3004 version will fail
