### ISSUE TITLE
[BUG] require_in: - name in 3003.5 works, breaks in 3004.2

### ISSUE THREAD

**Issue by wmellema** [saltstack/salt#62767]
### Description of Issue

Whilst running tests on some of our modules, it appears that a syntax change has happened between version 3003.5 and 3004.2. 
Under 3003.5, we have some states that use the following syntax in order to "inject" state requirements into other states.
```
- require_in:
  - name: state_to_be_injected_with_require
```
In order to keep dynamic dependencies clean, this can be very useful. 
We have since updated some machines to 3004.2, and we're getting the following error:
```
local:
           Data failed to compile:
       ----------
           Cannot extend ID 'test2' in 'base:myformula'. It is not part of the high state.
       This is likely due to a missing include statement or an incorrectly typed ID.
       Ensure that a state with an ID of 'test2' is available
       in environment 'base' and to SLS 'myformula'
```
Not sure if this is a bug, or a feature that has been removed between the versions. 
If it's not a bug, how would I go about rewriting the states without more and more jinja templating?

### Setup
```
test1:
  file.directory:
      - name: /testfile1
      - require_in:
        - name: test2

test2:
  file.directory:
    - name: /testfile2
```

### Steps to Reproduce Issue
Use the above sls. Any 3003 build will succeed, any 3004 version will fail

**Comment by OrangeDog** [comment]
This looks like a duplicate of #61121 
Are you able to test whether 3005 resolves the issue?

**Comment by wmellema** [comment]
Just tested it with the `debian` platform in kitchen (installs 3005). Issue still persists

**Comment by OrangeDog** [comment]
On further consideration, I'm surprised that your example ever worked. That is supposed to be referencing a state function in the `name` module (which doesn't exist), with an id of "test2".

If you want to reference states by id without any type, then just omit the type:

```yaml
test1:
  file.directory:
    - name: /testfile1
    - require_in:
      - test2

test2:
  file.directory:
    - name: /testfile2
```

Where did you get the idea of using `name:` from?
