### ISSUE TITLE
[BUG] 3004.2 Docker: salt-master stops polling gitfs remote (MultiprocessingLoggingQueue and 'ProcessManager FileserverUpdate' processes are gone)

### ISSUE THREAD

**Issue by thedude42** [saltstack/salt#62799]
**Description**
When running the salt master in docker (3004.2 DIGEST:sha256:648823860888ff455b3b14a2b73b16788db6ef8ea2ac37a2e1fd472a9a8ff310) after some time (can be up to a week) salt-master stops polling the configured gitfs remote, and on inspection the MultiprocessingLoggingQueue process and ProcessManager FileserverUpdate process appear to have died and neither is restarted. The salt-master polling of ext_pillar is not affected and continues to function as expected.

**Setup**
master config:
```
fileserver_backend:
  - gitfs

file_roots:
  base:
    - /srv/states

default_top: base
state_top_saltenv: base
top_file_merging_strategy: merge_all

pillar_roots:
  base:
    - /srv/pillar

gitfs_provider: pygit2
gitfs_base: master

gitfs_remotes:
  - <states repo url>

ext_pillar:
  - git:
    - master <pillar repo URL>

user: salt

event_return: [postgres]
master_job_cache: postgres
returner.postgres.host: '<postgres server hostname>'
returner.postgres.user: 'salt'
returner.postgres.passwd: 'salt'
returner.postgres.db: 'salt'
returner.postgres.port: 5432
```

Dockerfile:
```
FROM saltstack/salt:3004.2

RUN deluser salt && addgroup -g 450 -S salt && \
    adduser -s /bin/sh -SD -u 450 -G salt salt && \
    chmod -R 2775 /etc/pki /etc/salt /var/cache/salt /var/log/salt /var/run/salt && \
    chgrp -R salt /etc/pki /etc/salt /var/cache/salt /var/log/salt /var/run/salt && \
    echo "starting apk update" && apk update && echo "finished apk update" && apk add postgresql-dev gcc python3-dev musl-dev gnupg && pip3 install psycopg2 pygit2
```

- [ x ] on-prem machine
- [ x ] container (Kubernetes, Docker, containerd, etc. please specify)

**Steps to Reproduce the behavior**
1. prepare bind mount directories for /etc/salt, /var/cache/salt /var/log/salt and /srv
2. create a system user on the execution host for salt with uid:gid 450 
3. Build the container with the above Dockerfile
4. place the above master config in the corresponding host directory of the bind mount for /etc (in the below docker run example it would be /var/dockermounts/saltmaster/etc/)
5. ensure the values in the master config for <states repo url> and <pillar repo URL> are set and the URLs are reachable anonymously from the execution host 
6. execute the docker run like so (assuming the dirpath for the bind mounts start at /var/dockermounts/saltmaster/): `docker run -d --name salt --hostname salt -u 450 --restart always --network host -v /var/dockermounts/saltmaster/etc:/etc/salt -v /var/dockermounts/saltmaster/cache:/var/cache/salt -v /var/dockermounts/saltmaster/logs:/var/log/salt -v /var/dockermounts/saltmaster/srv:/srv <built container name:tag>`
7. observe the request polling for the salt states (from master config `gitfs_provider: pygit2`) from salt-master until it stops
8. notice that the polling for salt pillar (from master config `ext_pillar:`) does not stop

**Expected behavior**
salt-master continues polling the gitfs configured remote, and the MultiprocessingLoggingQueue process and ProcessManager FileserverUpdate are restarted after they die. Additionally, some logging of this event should probably happen regardless of whether the situation can be recovered from.

**Screenshots**
Here is a before and after of the output of `ps` on the execution host running the salt-master. In this case you can see the processes die after about 35 hours of uptime:
```
Tue Sep 27 17:00:01 UTC 2022
salt     3205016 3205014  0 16:22 ?        00:00:05 /usr/local/bin/python /usr/local/bin/salt-master ProcessManager
salt     3205031 3205016  0 16:22 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master MultiprocessingLoggingQueue
salt     3205095 3205016  0 16:23 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master ZeroMQPubServerChannel
salt     3205098 3205016  0 16:23 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master EventPublisher
salt     3205104 3205016  6 16:23 ?        00:02:31 /usr/local/bin/python /usr/local/bin/salt-master Maintenance
salt     3205131 3205016  0 16:23 ?        00:00:01 /usr/local/bin/python /usr/local/bin/salt-master EventReturn
salt     3205132 3205016  0 16:23 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master ReqServer_ProcessManager
salt     3205135 3205132  0 16:23 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master MWorkerQueue
salt     3205143 3205132  0 16:23 ?        00:00:04 /usr/local/bin/python /usr/local/bin/salt-master MWorker-0
salt     3205145 3205132  0 16:23 ?        00:00:04 /usr/local/bin/python /usr/local/bin/salt-master MWorker-1
salt     3205146 3205132  0 16:23 ?        00:00:04 /usr/local/bin/python /usr/local/bin/salt-master MWorker-2
salt     3205147 3205132  0 16:23 ?        00:00:04 /usr/local/bin/python /usr/local/bin/salt-master MWorker-3
salt     3205148 3205132  0 16:23 ?        00:00:04 /usr/local/bin/python /usr/local/bin/salt-master MWorker-4
salt     3210814 3205016 17 16:58 ?        00:00:18 /usr/local/bin/python /usr/local/bin/salt-master ProcessManager FileserverUpdate
```

```
Thu Sep 29 03:00:01 UTC 2022
salt     3205016 3205014  0 Sep27 ?        00:00:41 /usr/local/bin/python /usr/local/bin/salt-master ProcessManager
salt     3205095 3205016  0 Sep27 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master ZeroMQPubServerChannel
salt     3205098 3205016  0 Sep27 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master EventPublisher
salt     3205104 3205016  6 Sep27 ?        02:24:56 /usr/local/bin/python /usr/local/bin/salt-master Maintenance
salt     3205131 3205016  0 Sep27 ?        00:01:03 /usr/local/bin/python /usr/local/bin/salt-master EventReturn
salt     3205132 3205016  0 Sep27 ?        00:00:06 /usr/local/bin/python /usr/local/bin/salt-master ReqServer_ProcessManager
salt     3205135 3205132  0 Sep27 ?        00:00:00 /usr/local/bin/python /usr/local/bin/salt-master MWorkerQueue
salt     3205143 3205132  0 Sep27 ?        00:00:26 /usr/local/bin/python /usr/local/bin/salt-master MWorker-0
salt     3205145 3205132  0 Sep27 ?        00:00:25 /usr/local/bin/python /usr/local/bin/salt-master MWorker-1
salt     3205146 3205132  0 Sep27 ?        00:00:05 /usr/local/bin/python /usr/local/bin/salt-master MWorker-2
salt     3205147 3205132  0 Sep27 ?        00:00:06 /usr/local/bin/python /usr/local/bin/salt-master MWorker-3
salt     3205148 3205132  0 Sep27 ?        00:00:05 /usr/local/bin/python /usr/local/bin/salt-master MWorker-4
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
$ salt --versions-report
Salt Version:
    Salt: 3004.2

Dependency Versions:
    cffi: 1.14.6
    cherrypy: unknown
    dateutil: 2.8.1
    docker-py: Not Installed
    gitdb: Not Installed
    gitpython: Not Installed
    Jinja2: 2.11.3
    libgit2: 1.1.0
    M2Crypto: Not Installed
    Mako: Not Installed
    msgpack: 1.0.2
    msgpack-pure: Not Installed
    mysql-python: Not Installed
    pycparser: 2.17
    pycrypto: Not Installed
    pycryptodome: 3.9.8
    pygit2: 1.6.1
    Python: 3.7.13 (default, Apr 20 2022, 03:16:50)
    python-gnupg: 0.4.4
    PyYAML: 5.4.1
    PyZMQ: 18.0.1
    smmap: Not Installed
    timelib: 0.2.4
    Tornado: 4.5.3
    ZMQ: 4.3.1

System Versions:
    dist: alpine 3.14.6
    locale: UTF-8
    machine: x86_64
    release: 5.4.0-109-generic
    system: Linux
    version: Alpine Linux 3.14.6
```
</details>

**Additional context**
I had been running an older container build of version 3004.2 when I first saw this issue and the gitfs remote polling would stop after about 1 day consistently. I rebuilt it last month when the latest build was published and it seemed to have improved but after 8 days the salt-master stopped polling gitfs for states. In the last week it seems to be dying after about 2 days.

Can't tell if this is memory related but the salt-master does appear to be steadily increasing memory usage over time without any drop until the container is restarted to resolve the polling issue.

What other things can I do to gather data on why the MultiprocessingLoggingQueue and 'ProcessManager FileserverUpdate' appear to be crashing?
