### ISSUE TITLE
[BUG] Presence events are not being fired on 3005+ (TCP transport)

### ISSUE THREAD

**Issue by recmanj** [saltstack/salt#62826]
**Description**
On salt-master 3005+ with TCP transport configured, presence events are not being fired when the status of a connected salt-minion agent changes. It apparently fires event when a minion first connects but never gets fired again (lost nor added).

After a little bit of debugging I discovered the newly created callback for removing presence of a client is never being called.

**Setup**
salt-master on version 3005.1 configured to use TCP transport

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Configure salt-master and salt-minion to use TCP transport and presence events enabled. Check for incoming presents events changes with ```salt-run state.event  "salt/presence/change" pretty=True``` while starting/stopping the salt-minion randomly.

**Expected behavior**
Presence events come as the status of salt-minion agent changes.

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.9.1
      cherrypy: unknown
      dateutil: 2.4.2
     docker-py: Not Installed
         gitdb: 0.6.4
     gitpython: 1.0.2
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: 0.9.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>
