### ISSUE TITLE
[BUG][V3005] Pillar-root doesnt work

### ISSUE THREAD

**Issue by garadar** [saltstack/salt#62847]
**Description**
Related issue: https://github.com/saltstack/salt/issues/16873

The --pillar-root option doesn't  work. Salt is always sourcing the standard pillar-root

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
create a pillar test in `/srv/salt/pillar/config.sls` but not in another pillar-root :

```
(cluster)-[xxxx@admin ~]$ grep -A1 toto: /srv/salt/pillar/config.sls
toto:
  tutu: test
(cluster)-[xxxx@admin ~]$ grep -A1 toto: /opt/another_salt_pillar_dir/config.sls
(cluster)-[xxxx@admin ~]$
```

**Expected behavior**
Run:
This is normal:
```
(cluster)-[xxxx@admin1 ~] $ salt-call pillar.get  toto
local:
    ----------
    tutu:
        test
```
This is not normal and should be return nothing:
```
(cluster)-[xxxx@admin1 ~] $ salt-call --pillar-root=/opt/another_salt_pillar_dir/ pillar.get  toto
local:
    ----------
    tutu:
        test
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.9.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
 

```
</details>

**Additional context**
Nothing to Add
