### ISSUE TITLE
[BUG] Master job scheduler using `when` fails

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#62858]
**Description**
Scheduling jobs on the master using "when" fails. This is caused by https://github.com/saltstack/salt/blob/45ead10a6be567d9dbf05d62708ecf3c518ecded/salt/utils/schedule.py#L1066-L1068 assuming `opts["grains"]` exists, which is only true on a minion.

**Setup**
```yaml
# master config
schedule:
  highstate:
    function: state.orchestrate
    args:
      - orch.sys.salt.highstate
    when:
      - 4:00am
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (KVM)

**Steps to Reproduce the behavior**
1. install python-dateutil
2. set the time appropriately
3. watch the master log

**Expected behavior**
Job is executed.

**Screenshots**
```log
Exception 'grains' occurred in scheduled job
```
(The error description could be much better imho).

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.9
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 3.10.1
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.8.12 (default, Sep 26 2021, 13:12:50)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: openbsd 7.0
        locale: utf-8
       machine: amd64
       release: 7.0
        system: OpenBSD
       version: OpenBSD 7.0
```
</details>

**Additional context**
PR incoming.
