### ISSUE TITLE
[BUG] pkgrepo.managed fails with 'SourceEntry' object has no attribute 'repo_line'

### ISSUE THREAD

**Issue by bio** [saltstack/salt#62860]
**Description**
I tried to install the latest fish shell version from the [official linux repository](https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish) to Debian 11 but got an error below.

`Failed to configure repo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /': 'SourceEntry' object has no attribute 'repo_line'`

```
          ID: repo_opensuse_fish
    Function: pkgrepo.managed
        Name: deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /
      Result: False
     Comment: Failed to configure repo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /': 'SourceEntry' object has no attribute 'repo_line'
     Started: 10:16:00.554523
    Duration: 2171.715 ms
     Changes:
```

**Setup**
```
repo_opensuse_fish:
  pkgrepo.managed:
    - name: "deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /"
    - file: /etc/apt/sources.list.d/shells:fish:release:3.list
    - key_url: https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine

**Steps to Reproduce the behavior**
```
salt-ssh -l trace testhost state.apply testhost

[TRACE   ] STDOUT testhost
/usr/bin/scp
_edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
{
    "local": {
        "jid": "20221011101914864650",
        "return": {
            "pkgrepo_|-repo_opensuse_fish_|-deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /_|-managed": {
                "name": "deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /",
                "changes": {},
                "result": false,
                "comment": "Failed to configure repo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /': 'SourceEntry' object has no attribute 'repo_line'",
                "__sls__": "system.packages",
                "__run_num__": 2,
                "start_time": "10:19:18.081169",
                "duration": 2155.624,
                "__id__": "repo_opensuse_fish"
            },
...
[TRACE   ] data = {'testhost': {'pkgrepo_|-repo_opensuse_fish_|-deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /_|-managed': {'name': 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /', 'changes': {}, 'result': False, 'comment': "Failed to configure repo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /': 'SourceEntry' object has no attribute 'repo_line'", '__sls__': 'system.packages', '__run_num__': 2, 'start_time': '10:19:18.081169', 'duration': '2155.624 ms', '__id__': 'repo_opensuse_fish'}, ...
```

**Expected behavior**
The new deb repo should be added/updated.

**Versions Report**
<details><summary>salt-ssh --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.12
        Jinja2: 3.1.0
       libgit2: 1.5.0
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: 3.15.0
  pycryptodome: 3.9.8
        pygit2: 1.10.0
        Python: 3.10.7 (main, Sep 15 2022, 01:51:29) [Clang 14.0.0 (clang-1400.0.29.102)]
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: 3.0.2
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: darwin 21.6.0
        locale: utf-8
       machine: x86_64
       release: 21.6.0
        system: Darwin
       version: 12.6 x86_64
```
</details>
