### ISSUE TITLE
[FEATURE REQUEST] ship pythonnet==3.0.0 with the Windows minions

### ISSUE THREAD

**Issue by lubyou** [saltstack/salt#62874]
Hi,

**Is your feature request related to a problem? Please describe.**
[pythonnet 3.0](https://github.com/pythonnet/pythonnet/releases/tag/v3.0.0) is finally out, it has a bunch of fixes and improvements, including support for python > 3.8.

**Describe the solution you'd like**
Replace pythonnet==2.5.2 with pythonnet==3.0.0 for the Windows minions

**Describe alternatives you've considered**
Install pythonnet==3.0.0 via pip, it breaks salt.

**Additional context**
```
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: 3.1.18
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist:   
        locale: cp1252
       machine: AMD64
       release: 2012ServerR2
        system: Windows
       version: 2012ServerR2 6.3.9600 SP0 Multiprocessor Free
 ```
