### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by afletch** [saltstack/salt#62872]
**Description**
Error in ipset.set_present module fails to build command correctly for 'family' arg, adding the whole command again to the list of args rather than just the required parameter
https://github.com/saltstack/salt/blob/master/salt/modules/ipset.py#L332

**Setup**
N/A

**Steps to Reproduce the behavior**
```
setname-present:
  ipset.set_present:
    - name: testset
    - family: ipv4
    - set_type: hash:net
    - maxelem: 100000
```

**Expected behavior**
Should look like this:
```
cmd.extend(["family", ipset_family])
```
