### ISSUE TITLE
[BUG] `publish.publish` timeout is not honored

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#62899]
**Description**
Issuing peer commands from a minion with `publish.publish` does not honor timeout and defaults to 5 seconds. This has been mentioned in https://github.com/saltstack/salt/issues/57085#issuecomment-766710670 before.

**Setup**
Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [x] classic packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
~~Note that I currently cannot verify if this demonstration works as expected (this seems to not be the sole reason my command fails).~~ It does not fail and seems to work as expected. The timeout parameter passed to `LocalClient.pub` is still reported as 5s, but I assume this is expected behavior. Closing this.

```yaml
#master.conf
peer:
  .*:
      - test.sleep
```
~~On a minion, run `salt-call publish.publish myminion test.sleep '10' timeout=20`.~~

**Expected behavior**
Timeout honored.

**Screenshots**
```console
$ salt-call publish.publish myminion test.sleep '10' timeout=20
local:
    ----------
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.9
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 3.10.1
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.8.12 (default, Sep 26 2021, 13:12:50)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: openbsd 7.1
        locale: utf-8
       machine: amd64
       release: 7.1
        system: OpenBSD
       version: OpenBSD 7.1
```
</details>

**Additional context**
Timeout is passed to the master: https://github.com/saltstack/salt/blob/b59e7ef86e90c5478cbad34b774cfcae47c68c4d/salt/modules/publish.py#L127-L139
But it is not passed to `cmd_async` in `minion_pub`: https://github.com/saltstack/salt/blob/b59e7ef86e90c5478cbad34b774cfcae47c68c4d/salt/daemons/masterapi.py#L931-L940
Notice that a related function, `minion_publish`, does pass it: https://github.com/saltstack/salt/blob/b59e7ef86e90c5478cbad34b774cfcae47c68c4d/salt/daemons/masterapi.py#L993-L1006
