### ISSUE TITLE
[BUG] Remove outdated gnupg check 

### ISSUE THREAD

**Issue by leifliddy** [saltstack/salt#62895]
**Description**
Remove the following check
```GPG_1_3_1 = _LooseVersion(gnupg.__version__) >= _LooseVersion("1.3.1")```
from the ```gpg.py``` execution module.   

I'm not even sure what version that's referring to. The current release is ```0.5.0```  
It appears that this ```1.3.1``` version never existed. 
https://github.com/vsajip/python-gnupg#050

The oldest version of ```gnupg.py``` on github dates back to 2008
https://github.com/vsajip/python-gnupg/blob/5f3d64b4865d88991bed261798f66aa63c490adc/gnupg.py

And even this version doesn't need to the conditions enforced by that ```GPG_1_3_1``` check. 

**Setup**

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
N/A code maintenance issue

**Expected behavior**
N/A code maintenance issue. 

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.27
        Jinja2: 3.0.3
       libgit2: 1.3.1
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: 1.7.1
        Python: 3.11.0rc2 (main, Sep 13 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)]
  python-gnupg: 0.5.1.dev0
        PyYAML: 6.0
         PyZMQ: 23.2.0
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: fedora 37 Thirty Seven
        locale: utf-8
       machine: x86_64
       release: 5.19.14-300.fc37.x86_64
        system: Linux
       version: Fedora Linux 37 Thirty Seven
```
</details>
