### ISSUE TITLE
[FEATURE REQUEST] rvm deb package support 

### ISSUE THREAD

**Issue by RobHooper** [saltstack/salt#62904]
**Is your feature request related to a problem? Please describe.**
The rvm Salt module cannot find the rvm binary if it was installed as an apt package.
Salt is hard coded to use `/usr/local/rvm/bin/rvm` but the apt package installs rvm into `/usr/share/rvm/bin/rvm`

This causes issues if, for example, RVM was installed from the official rvm PPA https://github.com/rvm/ubuntu_rvm.

You can replicate this by running the following states.
The second state will try to install RVM fresh despite it already being present on the system (https://github.com/saltstack/salt/blob/master/salt/modules/rvm.py#L68)
```
rvm:
  pkgrepo.managed:
    - ppa: rael-gc/rvm
  pkg.installed:
    - name: rvm
    - require:
      - pkgrepo: rvm

ruby-3.1.2:
  rvm.installed
```

**Describe the solution you'd like**
Salt to detect rvm is installed under `/usr/share/rvm/bin/rvm`.

**Describe alternatives you've considered**
I also considered making the rvm binary path a variable you can pass to states however this is a much bigger change.

**Additional context**
