### ISSUE TITLE
[BUG] Event iteration failed with exception: 'list' object has no attribute 'items' in master log

### ISSUE THREAD

**Issue by m0duspwnens** [saltstack/salt#62938]
**Description**
Within the Salt master log file, the entry `[salt.utils.event :912 ][ERROR   ][1842] Event iteration failed with exception: 'list' object has no attribute 'items'` will be seen if the following circumstances are met:

The minion is currently running a highstate.
Another highstate is attempted to be applied while the first highstate is still running 

The minion is currently has a state.apply running.
A highstate is attempted to be applied while the state.apply is still running

**Setup**

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [x] used bootstrap to install

salt/top.sls
```
base:
  '*':
    - test
```

salt/test.sls
```
teststate:
  module.run:
    - test.sleep:
      - length: 30
```

**Steps to Reproduce the behavior**
Run `salt-call state.highstate` or `salt-call state.apply test` on the minion. While the state is still running, run `salt-call state.highstate` on the minion. 

Observe `Event iteration failed with exception: 'list' object has no attribute 'items'` in master log

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.62.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>
