### ISSUE TITLE
[BUG] Salt-call hangs on Windows - version 3005.1

### ISSUE THREAD

**Issue by AGirin** [saltstack/salt#62937]
**Description**
salt-call now hangs on Windows and needs to be killed manually. Observed on many servers that we built with our bootstrap process. Windows 2019 and 2022 were tested.

**Setup**
Any state - salt-call hangs.
**Versions Report**
<details><summary>
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.14 (tags/v3.8.14:f43e767, Sep 30 2022, 10:51:05) [MSC v.1929 64 bit (AMD64)]
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2022Server
        system: Windows
       version: 2022Server 10.0.20348 SP0 Multiprocessor Free
</summary>
</details>

**Comment by AGirin** [comment]
![image](https://user-images.githubusercontent.com/5177657/197283260-d881cbb1-0dd4-4c48-b506-0e9ddfddf4cb.png)

**Comment by OrangeDog** [comment]
Onedir or classic packaging?

**Comment by AGirin** [comment]
Classic I believe.

**Comment by OrangeDog** [comment]
Does it look like the same causes as #62550? But that should be fixed in 3005.1

**Comment by AGirin** [comment]
I saw that one... It looks like it was addressed for Ubuntu.. Not Windows.. We are running 3005.1...

**Comment by AGirin** [comment]
I added kill statement to our bootstrap process in the meantime...

**Comment by whytewolf** [comment]
in your highstate are you using any imports? I'm trying to track this down and think i have a lead but just want to be sure. but I am not sure why it is only happening on windows. 

when i say imports i mean jinja that imports a map.jinja or any other code that does `import <"filename"> as <variable>` or `from <"filename"> import variable [with|without] [context]`

**Comment by twangboy** [comment]
@AGirin Could you post the exact salt-call command you are running? Are you using `--local`?

**Comment by whytewolf** [comment]
@twangboy I was able to replicate this also. 

here is the setup i did to get the fastest replication of the issue

```
root@salt00:/srv/salt/tests# cat test.sls
{% import "map.jinja" as settings%}

always-passes-with-any-kwarg:
  test.nop:
    - name: foo
    - something: else
    - foo: bar

always-passes:
  test.succeed_without_changes:
    - name: foo

always-fails:
  test.fail_without_changes:
    - name: foo

always-changes-and-succeeds:
  test.succeed_with_changes:
    - name: foo

always-changes-and-fails:
  test.fail_with_changes:
    - name: foo

my-custom-combo:
  test.configurable_test_state:
    - name: foo
    - changes: True
    - result: False
    - comment: bar.baz
    - warnings: A warning
```

```
root@salt00:/srv/salt/tests# cat /srv/salt/map.jinja
{% set settings = ["this"] %}
```

and the command i ran on the wndows host was 

```
salt-call slsutil.renderer salt://tests/tests.sls -l all
```
which gave the following output

[windows hang log.txt](https://github.com/saltstack/salt/files/9872843/windows.hang.log.txt)
hanging at that last line.

same hang also happens when run with state.apply instead of the slsutil.renderer
