### ISSUE TITLE
[BUG] pycurl and/or tornado not detected when proxy configured in minion

### ISSUE THREAD

**Issue by Christoph-TKE** [saltstack/salt#62930]
**Description**
When configuring the http proxy in the minon, it fails to execute any http request with this error message:
```
proxy_host and proxy_port has been set. This requires pycurl and tornado, but the libraries does not seem to be installed
```

Removing the http proxy configuration cures the issue, but obviously disconnects the minion from the world wide web.

**Setup**
Out of the box `salt-minion` installation with this file added in `/etc/salt/minion.d/01-local.conf`:
```
proxy_host: x.x.x.x
proxy_port: 80
no_proxy: [ 'localhost', '127.0.0.1', '10.77.0.0/16' ]
```

Salt minion version 3005.1 running on an out-of-the-box installation of Ubuntu 22.04.1.

- [ ] on-prem machine
- [x] VM (on vmware ESXi)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
 1. Ramp up a fresh installation of Ubuntu 22.04.1 server.
 2. Install salt-minion, accept key at the master
 3. Configure proxy settings as mentioned above, restart salt-minion service
 4. Run `sudo salt-call --local http.query https://www.google.com` on that new minion. It throws this error:
```
$ sudo salt-call --local http.query https://www.google.com
[ERROR   ] proxy_host and proxy_port has been set. This requires pycurl and tornado, but the libraries does not seem to be installed
local:
    ----------
    error:
        proxy_host and proxy_port has been set. This requires pycurl and tornado, but the libraries does not seem to be installed

```
 6. Install `python3-pycurl` and `python3-tornado`, as mentioned in the error message (even though tornado 4.5.3 is packaged into saltstack)
 7. Re-run `sudo salt-call --local http.query https://www.google.com`, still the same error.

(I cannot test successfully without a proxy on these minions. The `http.query` call will end in a timeout on these minions.)

```
# without proxy configuration in minion, just for reference
$ sudo salt-call --local http.query https://www.google.com
local:
    ----------
    error:
        HTTP 599: Timeout while connecting
    status:
        599
```

**Expected behavior**
Saltstack (in this special case the minion) should recognize the tornado and pycurl installations and successfully connect to webservers through the configured proxy (i.e. on `http.query`).

**Screenshots**
(No screenshots provided)

**Versions Report**

<details><summary>salt-minion --versions-report</summary>

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.14 (main, Oct  3 2022, 21:22:21)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-48-generic
        system: Linux
       version: Ubuntu 22.04 jammy
```

</details>
<details><summary>pip3 freeze</summary>

```
attrs==21.2.0
Babel==2.8.0
blinker==1.4
certifi==2020.6.20
chardet==4.0.0
click==8.0.3
cloud-init==22.3.4
colorama==0.4.4
configobj==5.0.6
cryptography==3.4.8
dbus-python==1.2.18
distro==1.7.0
distro-info===1.1build1
httplib2==0.20.2
idna==3.3
importlib-metadata==4.6.4
jeepney==0.7.1
Jinja2==3.0.3
jsonpatch==1.32
jsonpointer==2.0
jsonschema==3.2.0
keyring==23.5.0
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
MarkupSafe==2.0.1
more-itertools==8.10.0
netifaces==0.11.0
oauthlib==3.2.0
pycurl==7.44.1
PyGObject==3.42.1
PyJWT==2.3.0
pyparsing==2.4.7
pyrsistent==0.18.1
pyserial==3.5
python-apt==2.3.0+ubuntu2.1
pytz==2022.1
PyYAML==5.4.1
requests==2.25.1
SecretStorage==3.3.1
six==1.16.0
ssh-import-id==5.11
systemd-python==234
tornado==6.1
ubuntu-drivers-common==0.0.0
unattended-upgrades==0.1
urllib3==1.26.5
wadllib==1.3.6
xkit==0.0.0
zipp==1.0.0
```

</details>

**Additional context**
This is only affecting minions on Ubuntu 22.04.1. There are other minions also on salt v3005.1 but on Ubuntu 20.04.x or Debian 10 or 11 and they are not affected by this bug.
