### ISSUE TITLE
[BUG] Installation of pycurl fails in onedir installation

### ISSUE THREAD

**Issue by Christoph-TKE** [saltstack/salt#62949]
**Description**
At a fresh Ubuntu 22.04.1 installation, `salt-pip` fails to install `pycurl`. Normal installation of pycurl with system-default python/pip works as expected.

This only affects the installation of `pycurl` (and probably others) but is not a general issue. For instance, installation of `tornado` package works without any errors.

**Setup**

Default onedir minion installtion (v3005.1) on a fresh Ubuntu 22.04.1 from server installation image. No special configuration for master or minion required.

Environment in salt is the same as in a regular bash except for these values: (`/opt/saltstack/salt/run/run shell` -> examine `os.environ`)
```
_: /opt/saltstack/salt/run/run
LD_LIBRARY_PATH: /opt/saltstack/salt/run
TCL_LIBRARY: /opt/saltstack/salt/run/tcl
TK_LIBRARY: /opt/saltstack/salt/run/tk
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [X] VM (VMware ESXi)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

 1. Install Ubuntu 22.04.1 (minimal server installation, in case it matters)
 2. Install salt-minion from onedir deb repository (tested with v3005 and v3005.1)
 3. `sudo salt-pip install -v --no-cache-dir --no-clean pycurl`

The above sequence triggers this error message:
```
Collecting pycurl
  Downloading pycurl-7.45.1.tar.gz (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.9/233.9 kB 8.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-rwor65_m
```

There is no directory `/tmp/pip-pip-egg-info-xxxxxxx` (tempfile suffix changes with every run). But there are two other directories created by `salt-pip`:
```diff
--- tmp.before-pip      2022-10-24 17:05:27.873782893 +0200
+++ tmp.after-pip       2022-10-24 17:08:27.510012183 +0200
@@ -1,3 +1,5 @@
+pip-ephem-wheel-cache-8xt3qi4q/
+pip-install-s_1fb28u/
 ssh-XXXXLBaO0f/
 systemd-private-647016854e1e4c91b80f5d92d6ec5f06-systemd-logind.service-EDui5Q/
 systemd-private-647016854e1e4c91b80f5d92d6ec5f06-systemd-resolved.service-ypjjU6/
```

**Expected behavior**
`salt-pip` should install `pycurl` like the system-default python/pip does.

**Screenshots**
(no screenshots provided)

**Versions Report**
<details><summary>salt-minion --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.14 (main, Oct  3 2022, 21:22:21)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-48-generic
        system: Linux
       version: Ubuntu 22.04 jammy

```
</details>

**Additional context**
Branched off from issue #62930.
