### ISSUE TITLE
[BUG] file.tidied "age" value ignored

### ISSUE THREAD

**Issue by byoungstrom** [saltstack/salt#62955]
**Description**
It appears the `age` parameter to `file.tidied` is being ignored.

Tested with salt-ssh, master+minion, and salt-call --local.  Consistent behavior across all tested combinations.

**Setup**
/srv/salt/common/tidy.sls:
```
/var/tmp/salt/:
  file.tidied:
    - age: 120
```
Repro:
**Steps to Reproduce the behavior**
```
Create /srv/salt/comon/tidy.sls as above

minion# mkdir -p /var/tmp/salt
minion# touch /var/tmp/salt/file{1..5}
minion# salt-call --local state.apply common.tidy
local:
----------
          ID: /var/tmp/salt/
    Function: file.tidied
      Result: None
     Comment: /var/tmp/salt/ is set for tidy
     Started: 19:23:08.034949
    Duration: 1.25 ms
     Changes:   
              ----------
              removed:
                  - /var/tmp/salt/file1
                  - /var/tmp/salt/file2
                  - /var/tmp/salt/file3
                  - /var/tmp/salt/file4
                  - /var/tmp/salt/file5

Summary for local
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.250 ms
```

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [X] VM: Virtualbox, KVM.  Repro valided in salt-vagrant-demo env.
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [X] classic packaging
- [ ] onedir packaging
- [X] used bootstrap to install

**Expected behavior**
With `age: 120`, I would not expect freshly created files to be deleted.  According to the docs, only files not accessed in the last 120 days would be removed.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

First discovered using 3004.1.

```yaml
salt-call --versions-report
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: 1.0.6
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Sep 13 2022, 09:02:49)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 8.6 Green Obsidian
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-372.26.1.el8_6.x86_64
        system: Linux
       version: Rocky Linux 8.6 Green Obsidian
 ```
</details>

**Additional context**
