### ISSUE TITLE
[BUG] Minion sending duplicate events

### ISSUE THREAD

**Issue by supfors** [saltstack/salt#62959]
**Description**
When running `event.send` in a state executed from the master to a minion, the minion sends duplicate events to the bus. This happens most of the times, but not always.

It does not happen when:
* Running `event.send` from the master using `salt myminion event.send test123`
* Running `event.send` from the minion using `salt-call event.send test123`
* Running `salt-call state.apply test123` from the minion

It looks like the behaviour reported in #53506 but the other way around. It also causes the behaviour reported in #62638 

**Setup**
`/srv/salt/test123.sls`:
```
test123:
  event.send
```

`salt myminion state.apply test123`

`salt-run state.event test123`
```
test123	{"id": "myminion", "cmd": "_minion_event", "pretag": null, "data": {}, "tag": "test123", "_stamp": "2022-10-26T10:05:08.209961"}
test123	{"id": "myminion", "cmd": "_minion_event", "pretag": null, "data": {}, "tag": "test123", "_stamp": "2022-10-26T10:05:17.211189"}
```

**Expected behavior**
I expect events to always be sent once.

**Versions Report**

```yaml
master:
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: 5.0.3
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: 1.5.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.10.1
        Python: 3.9.14 (main, Oct  3 2022, 21:22:21)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-52-generic
        system: Linux
       version: Ubuntu 22.04 jammy


minion:
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.14 (main, Oct  3 2022, 21:22:21)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04 jammy
        locale: ascii
       machine: x86_64
       release: 5.15.0-52-generic
        system: Linux
       version: Ubuntu 22.04 jammy

```
</details>

**Additional context**
I've tested this on Ubuntu20 (both classic and onedir install methods) and ubuntu22.
I did not see this behaviour in previous salt versions (3004.x).
