### ISSUE TITLE
[BUG] Hightstate with custom saltenv fails on includes when using __env__ in file_roots

### ISSUE THREAD

**Issue by danny-smit** [saltstack/salt#62967]
**Description**
Executing the highstate as follows, results in the following error:
```
$ salt mytestmachine state.highstate saltenv=mysaltenv
mytestmachine:
    Data failed to compile:
----------
    Nonexistent saltenv 'mysaltenv' found in include of 'saltenv_include' within SLS 'mysaltenv:saltenv_state'
ERROR: Minions returned with non-zero exit code
```

A state.apply for the same state file runs fine:
```
mytestmachine:  
----------
          ID: included state               
    Function: test.nop                     
      Result: True                         
     Comment: Success!      
     Started: 13:23:45.983607
    Duration: 1.367 ms
     Changes:                              
----------                                 
          ID: main state                   
    Function: test.nop
      Result: True    
     Comment: Success!
     Started: 13:23:45.985818
    Duration: 13.735 ms
     Changes:   

Summary for mytestmachine
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time:  15.102 ms
```

A master-minion setup is used, with `__env__` in the fire_roots. The top.sls then defines multiple salt environments. The error pops up if the state files use the `include:` state to include other state files.

**Setup**
The following is used as a test configuration to reproduce the scenario with a small environment;

master config file:
```yaml
file_roots:
  __env__:
    - /srv/salt
top_file_merging_strategy: same  
```

top.sls:
```yaml
base:
  '*':
    - dummy
mysaltenv:
  '*':
    - saltenv_state
```

saltenv_state.sls:
```yaml
include:
  - saltenv_include

main state:
  test.nop
```

saltenv_include.sls:
```yaml
included state:
  test.nop
```

**Steps to Reproduce the behavior**
Use the config file and state files from the previous **Setup** paragraph and execute the highstate with a custom saltenv:
```
salt mytestmachine state.highstate saltenv=mysaltenv
```

**Expected behavior**
Expected behavior is that the state files are executed, just like it does with the `state.apply` command.

**Versions Report**
<details><summary>salt --versions-report (master)</summary>

```yaml
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: 2.6.1
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

</details>

<details><summary>salt --versions-report (minion)</summary>

```yaml
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: 3.4.1
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-21-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**
Debugging shows that when the code ends up at the following condition: 
```python
                    if env_key not in self.avail:
                        msg = (
                            "Nonexistent saltenv '{}' found in include "
```
Source: https://github.com/saltstack/salt/blob/v3004.2/salt/state.py#L4084

In the code snippet `self.avail` only holds the keys `base` and `__env__`, but not `mysaltenv` as used in my test scenario, which leads to the error message.

This seems to be determined in the [_get_envs()](https://github.com/saltstack/salt/blob/v3004.2/salt/state.py#L3534) method, which doesn't seem to take the scenario of `__env__` in the `file_roots` into account.
