### ISSUE TITLE
[BUG] unable to apply states to hosts named cloud

### ISSUE THREAD

**Issue by tbennett6421** [saltstack/salt#62973]
**Description**
Unable to use salt to target hosts named cloud. When using salt 'cloud' an error message for salt-cloud appears

**Setup**

OS Version
```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

```sh
$ salt-minion --version
salt-minion 3005.1
```
Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify) `ESXi`
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
1. Install fresh ubuntu 22.04 LTS with hostname `cloud`
3. join a salt-master
4. `salt 'cloud' state.apply`

**Expected behavior**
apply highstate on a host named cloud

**Screenshots**
![image](https://user-images.githubusercontent.com/6843296/198805242-072c1376-ce08-4a90-a2c7-705208ee6088.png)

**Versions Report**

***Salt Master:***
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.14 (main, Oct  3 2022, 21:19:17)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 18.04 bionic
        locale: utf-8
       machine: x86_64
       release: 4.15.0-193-generic
        system: Linux
       version: Ubuntu 18.04 bionic
```
</details>

***Salt Minion:***
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.14 (main, Oct  3 2022, 21:19:16)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-126-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**

My setup for the minions involves adding the ubuntu salt-minion package to add the hosts to the salt master, then running a state file to apply the latest salt-minon. This minion was provisioned using the following relevant state files.

```yaml
{% set state_context = "base" %}
{% set state_folder = "apt" %}
{% set state_name = "saltstack" %}
{% set state_id = state_context ~ "@" ~ state_folder ~ "/" ~ state_name ~ ".sls" %}

# variables
{% set hostname = grains.host %}
{% set apt_humanname = "Saltstack Repo" %}
{% set apt_dstfile = "/etc/apt/sources.list.d/saltstack.list" %}

{% if grains['osfinger'] == 'Ubuntu-20.04' %}
  {% set os = "ubuntu" %}
  {% set osnum = "20.04" %}
  {% set codename = "focal" %}
  {% set codename_full = "focal fossa" %}
{% endif %}

{% if grains['osfinger'] == 'Ubuntu-20.04' %}
{{state_id}}//saltstack_pkgrepo_{{osnum}}:
  pkgrepo.managed:
    - humanname: {{apt_humanname}}
    - name: deb https://repo.saltproject.io/salt/py3/{{os}}/{{osnum}}/amd64/latest {{codename}} main
    - file: {{ apt_dstfile }}
    - key_url: https://repo.saltproject.io/salt/py3/{{os}}/{{osnum}}/amd64/latest/salt-archive-keyring.gpg
    - architectures: amd64
    - require_in:
      - pkg: {{state_id}}//salt.minion
{% endif %}

{{state_id}}//salt.minion:
  pkg.latest:
    - name: salt-minion
    - refresh: True
```
