### ISSUE TITLE
[BUG] file.tidied FileNotFoundError

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#62986]
**Description**
`file.tidied` may throw `FileNotFoundError` during iteration over the return of the `os.walk` call if another process moves or deletes a file between when the listing is created and the `getatime` (or similiar) call attempts to determine the file timestamp.

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-nmhughes/pytest-10/test_tidied_filenotfound0/not_found_test/test1/file1'
```

**Expected behavior**
Since the outcome of `file.tidied` would delete a file, we shouldn't get upset if someone else does the job for us.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.15.0
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 24.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-22-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
 
```
</details>
