### ISSUE TITLE
[BUG] module.run new style defintion is identified as legacy

### ISSUE THREAD

**Issue by redbaron4** [saltstack/salt#62988]
**Description**
New style `module.run` is considered legacy Salt version - 3005 leading to failures

**Setup**

Consider a state file that has the following state to invoke a custom module `something.do`

```
some foo:
  module.wait:
    - something.do:
      - config: /etc/foo
      - foo: bar
```

And this state is referenced in another stae file

```
my_pkg:
  pkg.installed:
    - name: mypkg
    - require:
      - pkgrepo: custom_repo_stable
      - pkgrepo: custom_repo_testing
    - watch_in:
      - module: some foo
```

Trying to run the state causes an error `Module function some foo` is not available

**Steps to Reproduce the behavior**

The debug logs are 

```
[INFO    ] Executing state module.mod_watch for [some foo]
[DEBUG   ] Detected legacy module.run syntax: some foo
[ERROR   ] Module function some foo is not available
```

**Expected behavior**

The state should be detected as using new style `module.run` and should run as expected

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:33:26)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 8.6 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 4.18.0-372.16.1.el8_6.0.1.x86_64
        system: Linux
       version: Rocky Linux 8.6 Green Obsidian

```
</details>

**Additional context**

Tinkering with the source in `states/modules.py` to add logging for offending keys that are triggering detection as legacy style gives following logs

```
[INFO    ] Executing state module.mod_watch for [some foo]
[DEBUG   ] ['name', 'something.do', 'sfun', '__reqs__']
[DEBUG   ] Detected legacy module.run syntax: some foo
[ERROR   ] Module function some foo is not available
```

which shows that additional `kwargs` `sfun` and `__reqs__` which are not handled in code maybe triggering the legacy flag. The code ignores the `name` kwarg but does not handle the other two addtional kwargs.
