### ISSUE TITLE
[BUG] Custom grains on Windows minion doesn't work

### ISSUE THREAD

**Issue by kTipSSIoYv** [saltstack/salt#63024]
**Description**
I'm trying to configure newly provisioned  azure VM's with custom grains. It works fine on Linux VM's. But for windows VM's the grains are in the server but it doesn't show when we run the command `salt 'wintest-001' grains.items`.

How do you define custom grains for Windows minions? 

Update: There seems to two location for Grains and Minion config on Windows VM's. The Salt process is looking for configs from  `C:\Program Data\salt-project\`. But the grains defined in profile are written in `c:\salt\grains` and `c:\salt\minion`.  If I move the grains file to `C:\Program Data\salt-project\grains` then it works as expected. 

How can I configure the profile to write grains data under `C:\Program Data\salt-project\` instead of `c:\salt`?

**Steps to Reproduce the behavior**

Create a windows azure profile as shown below.

```
azure-win2019:
  provider: my-azure-config
  image: MicrosoftWindowsServer|WindowsServer|2019-datacenter-gensecond|latest
  size: Standard_B2ms
  location: 'westeurope'
  win_username: azureuser
  win_password: 'Verybadpass'
  use_winrm: True
  winrm_verify_ssl: False
  winrm_port: 5986
  #smb_port: 445
  allocate_public_ip: True
  security_group: saltstack-nsg
  win_installer: /srv/salt/win/files/Salt-Minion-3004.2-1-Py3-AMD64-Setup.exe
  userdata_file: https://raw.githubusercontent.com/xxxxx/Windows-firewall.ps1
  grains:
    environment: production
  sync_after_install: grains

```
Deploy a new VM using the following command.

salt-cloud -p azure-win2019 wintest-001

After the provision is complete, check the grains and the `environment` grain is missing.

`root@salt:/etc/salt/cloud.profiles.d# salt 'wintest-001' grains.items  | grep production`
No matches

If you RDP to the new VM, you can see that grains file exists in the VM.

![image](https://user-images.githubusercontent.com/9666915/200113620-7de95bcc-c3c7-40ad-9ec6-6de5ef1fca30.png)

Here is the content of the minion config:
```
hash_type: sha256
id: wintest-001
ipc_mode: tcp
log_level: info
master: 10.10.10.10
master_finger: 7f:49:b4:86:11:27:7b:30:76:85:2c:2
multiprocessing: false
pki_dir: /conf/pki/minion
root_dir: c:\salt
```

I tried restarting salt services as well. But still its not showing up.

**Expected behavior**
Custom grains should show up just like it does for Linux

**Versions Report**
<details><summary>salt --versions-report</summary>

root@salt:~# salt --versions-report
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.24
        Jinja2: 3.0.3
       libgit2: 1.1.0
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.11.0
        pygit2: 1.6.1
        Python: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 Jammy Jellyfish
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1022-aws
        system: Linux
       version: Ubuntu 22.04 Jammy Jellyfish

</details>
