### ISSUE TITLE
[BUG] broken pymongo authentication

### ISSUE THREAD

**Issue by genaumann** [saltstack/salt#63058]
**Description**
The pymongo authentication in [`salt/pillar/mongo.py`](https://github.com/saltstack/salt/blob/master/salt/pillar/mongo.py) and [`salt/returners/test_mongo_future_return.py`](https://github.com/saltstack/salt/blob/master/salt/returners/mongo_future_return.py) throws the following error:

`TypeError: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.`

Pymongo is not able to access a database.

**Setup**
Salt Minion & Master config:

```yaml
mongo.user: root
mongo.password: pass
mongo.port: 10037
mongo.host: localhost
mongo.db: salt
```

**Steps to Reproduce the behavior**
Using mongo ext_pillar and mongo returner with the settings above.

**Versions Report**
3005.1

**Additional context**
Associated pull request #63053 already open.
