### ISSUE TITLE
[BUG] regression in 3005.x - salt hangs after highstate for windows minion 

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#63061]
**Description**
Since the upgrade to the latest version 3005.x on the master the windows minions no longer send highstate output back to linux master. 

**Setup**
upgrade master to 3005.x from 3004.2 and any previously working test only 
```salt mywinminion state.highstate test=true``` or an actual  ```salt mywinminion1 state.highstate``` times out and only results in a generic:

```
mywinminion1:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20221114161118227117
```

But this job output never gets any data even hours after having been run. 

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
on linux salt master output is:
salt --versions
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Sep 13 2022, 07:19:15)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 22.0.3
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 8.7 Stone Smilodon
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-425.3.1.el8.x86_64
        system: Linux
       version: AlmaLinux 8.7 Stone Smilodon

and windows minion versions output is:

salt-call --versions
C:\Program Files\Salt Project\Salt\bin\lib\site-packages\_distutils_hack\__init_
_.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.15 (tags/v3.8.15:44adf8a, Nov  8 2022, 17:20:07) [MSC v.1929
 64 bit (AMD64)]
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 22.0.3
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2016Server
        system: Windows
       version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
Please fill in the `salt --versions-report` above.

**Comment by TheBigBear** [comment]
> Please fill in the `salt --versions-report` above.

ok, done.

**Comment by OrangeDog** [comment]
This appears to be the same issue as #62937, but you already have the update with PyZMQ 22.0.3.

Has the minion service definitely been restarted after the upgrade?

**Comment by twangboy** [comment]
A similar stacktrace here, but with a syndic: https://github.com/saltstack/salt/issues/62577#issuecomment-1263638236

**Comment by twangboy** [comment]
@TheBigBear Do you happen to be on a Multi-master set up? I'm wondering about your `order_masters` setting. (https://github.com/saltstack/salt/issues/62599#issuecomment-1235919221)

**Comment by TheBigBear** [comment]
> @TheBigBear Do you happen to be on a Multi-master set up? I'm wondering about your `order_masters` setting. ([#62599 (comment)](https://github.com/saltstack/salt/issues/62599#issuecomment-1235919221))

@twangboy, no we have a 'simple' single master setup.

**Comment by twangboy** [comment]
Do you have an example of the states you are running? In #62550 it was exposed by anything that communicated with the master fileserver, for example `file.managed`. Perhaps one of the states you're running are exposing another issue.

**Comment by twangboy** [comment]
These may be the issue:
```
Passed invalid arguments to state.apply: can not serialize 'CommandExecutionError' object
Passed invalid arguments: can not serialize 'CommandExecutionError' object
```

**Comment by TheBigBear** [comment]
OK, I have reverted back to ```3004.2-1``` on a home/test/lab setup and it works, again. 
So it is a ```3005.x``` regression after-all.

Note: now it properly reports the user as 'system' under the windows minion. remember under the 3005.x it reported it as 'root' instead. 

Here is the output of ```salt INT-UR-TEST-1 state.show_sls salt.minion```

```
INT-UR-TEST-1:
    ----------
    permissions-minion-config:
        ----------
        __env__:
            base
        __sls__:
            salt.minion
        file:
            |_
              ----------
              name:
                  C:\ProgramData\Salt Project\Salt\conf\minion
            |_
              ----------
              user:
                  system
            |_
              ----------
              group:
                  root
            |_
              ----------
              replace:
                  False
            - managed
            |_
              ----------
              order:
                  10004
    permissions-minion.pem:
        ----------
        __env__:
            base
        __sls__:
            salt.minion
        file:
            |_
              ----------
              name:
                  C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pem
            |_
              ----------
              user:
                  system
            |_
              ----------
              group:
                  root
            |_
              ----------
              replace:
                  False
            |_
              ----------
              require:
                  |_
                    ----------
                    file:
                        salt-minion-pki-dir
            - managed
            |_
              ----------
              order:
                  10006
    permissions-minion.pub:
        ----------
        __env__:
            base
        __sls__:
            salt.minion
        file:
            |_
              ----------
              name:
                  C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pub
            |_
              ----------
              user:
                  system
            |_
              ----------
              group:
                  root
            |_
              ----------
              replace:
                  False
            |_
              ----------
              require:
                  |_
                    ----------
                    file:
                        salt-minion-pki-dir
            - managed
            |_
              ----------
              order:
                  10007
    remove-old-minion-conf-file:
        ----------
        __env__:
            base
        __sls__:
            salt.minion
        file:
            |_
              ----------
              name:
                  C:\ProgramData\Salt Project\Salt\conf\minion.d\_defaults.conf
            - absent
            |_
              ----------
              order:
                  10003
    salt-minion:
        ----------
        __env__:
            base
        __sls__:
            salt.minion
        cmd:
            |_
              ----------
              name:
                  salt-call.bat --local service.restart salt-minion
            |_
              ----------
              bg:
                  True
            |_
              ----------
              onchanges:
                  |_
                    ----------
                    pkg:
                        salt-minion
                  |_
                    ----------
                    file:
                        salt-minion
                  |_
                    ----------
                    file:
                        remove-old-minion-conf-file
            - run
            |_
              ----------
              order:
                  10002
        file:
            |_
              ----------
              name:
                  C:\ProgramData\Salt Project\Salt\conf\minion.d
            |_
              ----------
              template:
                  jinja
            |_
              ----------
              source:
                  salt://salt/files/minion.d
            |_
              ----------
              context:
                  ----------
                  standalone:
                      False
            |_
              ----------
              clean:
                  True
            |_
              ----------
              exclude_pat:
                  _*
            - recurse
            |_
              ----------
              order:
                  10001
        pkg:
            |_
              ----------
              name:
                  salt-minion-py3
            |_
              ----------
              require_in:
                  |_
                    ----------
                    service:
                        salt-minion
            - installed
            |_
              ----------
              order:
                  10000
        service:
            |_
              ----------
              enable:
                  True
            |_
              ----------
              name:
                  salt-minion
            |_
              ----------
              watch:
                  |_
                    ----------
                    file:
                        remove-old-minion-conf-file
            |_
              ----------
              order:
                  last
            - running
    salt-minion-pki-dir:
        ----------
        __env__:
            base
        __sls__:
            salt.minion
        file:
            |_
              ----------
              name:
                  C:\ProgramData\Salt Project\Salt\conf\pki\minion
            |_
              ----------
              user:
                  system
            |_
              ----------
              group:
                  root
            |_
              ----------
              makedirs:
                  True
            - directory
            |_
              ----------
              order:
                  10005
```

**Comment by TheBigBear** [comment]
@dafyddj or @twangboy what else do I have to capture first while I am still on ```3004.2-1``` ? 
And before I upgrade to ```3005.x``` where it will presumably break again?
Because once I upgraded I can't really easily downgrade the home/test/lab master down to ```3004.2-1``` again to get more logs ...

**Comment by dafyddj** [comment]
`grains.items` and `pillar.items` for my part

**Comment by TheBigBear** [comment]
@dafyddj your wish is my command ;-) 
```
salt INT-UR-TEST-1 grains.items
```

```
INT-UR-TEST-1:
    ----------
    biosversion:
        Default System BIOS
    cpu_model:
        Intel(R) Core(TM) i3 CPU       M 350  @ 2.27GHz
    cpuarch:
        AMD64
    cwd:
        C:\Program Files\Salt Project\Salt\bin
    disks:
        - \\.\PhysicalDrive0
    domain:
    efi:
        False
    efi-secure-boot:
        False
    fqdn:
        INT-UR-TEST-1
    fqdn_ip4:
        - 10.<redacted>
    fqdn_ip6:
        - fe80::a3db:5baf:3bdf:8971
    fqdns:
    gpus:
    groupname:
    host:
        INT-UR-TEST-1
    hwaddr_interfaces:
        ----------
        Ralink RT5390 802.11b/g/n WiFi Adapter:
            90:00:4E:08:0F:23
        Software Loopback Interface 1:
            :::::
    id:
        INT-UR-TEST-1
    init:
        Windows
    ip4_interfaces:
        ----------
        Ralink RT5390 802.11b/g/n WiFi Adapter:
            - 10.<redacted>
        Software Loopback Interface 1:
            - 127.0.0.1
    ip6_interfaces:
        ----------
        Ralink RT5390 802.11b/g/n WiFi Adapter:
            - fe80::a3db:5baf:3bdf:8971
        Software Loopback Interface 1:
            - ::1
    ip_interfaces:
        ----------
        Ralink RT5390 802.11b/g/n WiFi Adapter:
            - 10.<redacted>
            - fe80::a3db:5baf:3bdf:8971
        Software Loopback Interface 1:
            - 127.0.0.1
            - ::1
    ipv4:
        - 10.<redacted>
        - 127.0.0.1
    ipv6:
        - ::1
        - fe80::a3db:5baf:3bdf:8971
    kernel:
        Windows
    kernelrelease:
        10.0.19045
    kernelversion:
        10.0.19041
    locale_info:
        ----------
        defaultencoding:
            cp1252
        defaultlanguage:
            en_GB
        detectedencoding:
            cp1252
        timezone:
            GMT Standard Time
    localhost:
        INT-UR-TEST-1
    manufacturer:
        Hewlett-Packard
    master:
        ur-salt
    mem_total:
        2933
    motherboard:
        ----------
        productname:
            1425
        serialnumber:
            PX11M011ZZX2SF
    nodename:
        INT-UR-TEST-1
    num_cpus:
        4
    num_gpus:
        0
    os:
        Windows
    os_family:
        Windows
    osfinger:
        Windows-10
    osfullname:
        Microsoft Windows 10 Home
    osmanufacturer:
        Microsoft Corporation
    osrelease:
        10
    osrelease_info:
        - 10
    osservicepack:
        None
    osversion:
        10.0.19045
    path:
        C:\ProgramData\Boxstarter;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\tools;C:\Program Files\Salt Project\Salt;C:\Program Files\PowerShell\7\;C:\tools\BCURRAN3;;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
    pending_reboot:
        False
    pid:
        3020
    productname:
        HP G62 Notebook PC
    ps:
        tasklist.exe
    pythonexecutable:
        C:\Program Files\Salt Project\Salt\bin\python.exe
    pythonpath:
        - C:\Program Files\Salt Project\Salt\bin\Scripts
        - C:\Program Files\Salt Project\Salt\bin\lib\site-packages\git\ext\gitdb
        - C:\Program Files\Salt Project\Salt\bin\python38.zip
        - C:\Program Files\Salt Project\Salt\bin\DLLs
        - C:\Program Files\Salt Project\Salt\bin\lib
        - C:\Program Files\Salt Project\Salt\bin
        - C:\Program Files\Salt Project\Salt\bin\lib\site-packages
        - C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004.2-py3.8.egg
        - C:\Program Files\Salt Project\Salt\bin\lib\site-packages\win32
        - C:\Program Files\Salt Project\Salt\bin\lib\site-packages\win32\lib
        - C:\Windows\[Microsoft.NET](http://microsoft.net/)\Framework64\v4.0.30319\
        - C:\Program Files\Salt Project\Salt\bin\lib\site-packages\gitdb\ext\smmap
    pythonversion:
        - 3
        - 8
        - 8
        - final
        - 0
    saltpath:
        C:\Program Files\Salt Project\Salt\bin\Lib\site-packages\salt-3004.2-py3.8.egg\salt
    saltversion:
        3004.2
    saltversioninfo:
        - 3004
        - 2
    serialnumber:
        CNF10235DM
    server_id:
        1504829806
    shell:
        C:\Windows\system32\cmd.exe
    ssds:
    systempath:
        - C:\ProgramData\Boxstarter
        - C:\Windows\system32
        - C:\Windows
        - C:\Windows\System32\Wbem
        - C:\Windows\System32\WindowsPowerShell\v1.0\
        - C:\Windows\System32\OpenSSH\
        - C:\ProgramData\chocolatey\bin
        - C:\Program Files\Git\cmd
        - C:\tools
        - C:\Program Files\Salt Project\Salt
        - C:\Program Files\PowerShell\7\
        - C:\tools\BCURRAN3
        - C:\Program Files (x86)\Gpg4win\..\GnuPG\bin
        - C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
    timezone:
        (UTC+00:00) Dublin, Edinburgh, Lisbon, London
    transactional:
        False
    username:
        SYSTEM
    uuid:
        31464e43-3230-3533-444d-984be1936d78
    virtual:
        physical
    windowsdomain:
        WORKGROUP
    windowsdomaintype:
        Workgroup
```

```
salt INT-UR-TEST-1 pillar.items
```

```
INT-UR-TEST-1:
    ----------
    salt:
        ----------
        config_path:
            C:\ProgramData\Salt Project\Salt\conf
        master:
            ----------
            file_recv:
                True
            file_roots:
                ----------
                base:
                    - /srv/salt
                    - /srv/formulas/salt-formula
            hash_type:
                sha256
            pillar_roots:
                ----------
                base:
                    - /srv/pillar
            show_timeout:
                True
            worker_threads:
                20
        minion:
            ----------
            master:
                ur-salt
            mine_interval:
                60
            state_output:
                changes
            use_superseded:
                - module.run
        py_ver:
            py3
    salt_minion:
        ----------
        salt_minion_id:
            INT-UR-TEST-1
    users:
        ----------
        ansibleur:
            ----------
            fullname:
                ansible service user ur
    users-formula:
        ----------
        lookup:
            ----------
            root_group:
                root
        use_vim_formula:
            True
```

salt master versions:

```
salt --versions
```

```
[root@int-ur-it-salt salt]# salt --versions
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Sep 13 2022, 07:19:15)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 8.6 Sky Tiger
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-372.26.1.el8_6.x86_64
        system: Linux
       version: AlmaLinux 8.6 Sky Tiger
```

salt windows minion versions:

```
salt-call --versions
```

```
C:\Windows\system32>salt-call --versions
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: 3.1.18
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.19041 SP0 Multiprocessor Free
```

and ```state.apply salt.minion``` and ```state.apply salt.minion test=true``` outputs

```
salt INT-UR-TEST-1 state.apply salt.minion test=true
```

```
INT-UR-TEST-1:
----------
          ID: salt-minion
    Function: pkg.installed
        Name: salt-minion-py3
      Result: True
     Comment: All specified packages are already installed
     Started: 18:48:30.956247
    Duration: 1312.489 ms
     Changes:
----------
          ID: salt-minion
    Function: file.recurse
        Name: C:\ProgramData\Salt Project\Salt\conf\minion.d
      Result: None
     Comment: #### C:\ProgramData\Salt Project\Salt\conf\minion.d ####
              The directory "C:\ProgramData\Salt Project\Salt\conf\minion.d" will be changed

              #### C:\ProgramData\Salt Project\Salt\conf\minion.d\reactor.conf ####
              The file C:\ProgramData\Salt Project\Salt\conf\minion.d\reactor.conf is set to be changed
              Note: No changes made, actual changes may
              be different due to other states.

              #### C:\ProgramData\Salt Project\Salt\conf\minion.d\engine.conf ####
              The file C:\ProgramData\Salt Project\Salt\conf\minion.d\engine.conf is set to be changed
              Note: No changes made, actual changes may
              be different due to other states.

              #### C:\ProgramData\Salt Project\Salt\conf\minion.d\beacons.conf ####
              The file C:\ProgramData\Salt Project\Salt\conf\minion.d\beacons.conf is set to be changed
              Note: No changes made, actual changes may
              be different due to other states.

              #### C:\ProgramData\Salt Project\Salt\conf\minion.d\f_defaults.conf ####
              The file C:\ProgramData\Salt Project\Salt\conf\minion.d\f_defaults.conf is set to be changed
              Note: No changes made, actual changes may
              be different due to other states.
     Started: 18:48:32.268736
    Duration: 1015.616 ms
     Changes:
              ----------
              C:\ProgramData\Salt Project\Salt\conf\minion.d:
                  ----------
                  owner:
                      SYSTEM
              C:\ProgramData\Salt Project\Salt\conf\minion.d\beacons.conf:
                  ----------
                  newfile:
                      C:\ProgramData\Salt Project\Salt\conf\minion.d\beacons.conf
              C:\ProgramData\Salt Project\Salt\conf\minion.d\engine.conf:
                  ----------
                  newfile:
                      C:\ProgramData\Salt Project\Salt\conf\minion.d\engine.conf
              C:\ProgramData\Salt Project\Salt\conf\minion.d\f_defaults.conf:
                  ----------
                  newfile:
                      C:\ProgramData\Salt Project\Salt\conf\minion.d\f_defaults.conf
              C:\ProgramData\Salt Project\Salt\conf\minion.d\reactor.conf:
                  ----------
                  newfile:
                      C:\ProgramData\Salt Project\Salt\conf\minion.d\reactor.conf
----------
          ID: remove-old-minion-conf-file
    Function: file.absent
        Name: C:\ProgramData\Salt Project\Salt\conf\minion.d\_defaults.conf
      Result: True
     Comment: File C:\ProgramData\Salt Project\Salt\conf\minion.d\_defaults.conf is not present
     Started: 18:48:33.299975
    Duration: 0.0 ms
     Changes:
----------
          ID: salt-minion
    Function: cmd.run
        Name: salt-call.bat --local service.restart salt-minion
      Result: None
     Comment: Command "salt-call.bat --local service.restart salt-minion" would have been executed
     Started: 18:48:33.299975
    Duration: 0.0 ms
     Changes:
----------
          ID: permissions-minion-config
    Function: file.managed
        Name: C:\ProgramData\Salt Project\Salt\conf\minion
      Result: None
     Comment: File C:\ProgramData\Salt Project\Salt\conf\minion not updated
     Started: 18:48:33.299975
    Duration: 109.374 ms
     Changes:
              ----------
              owner:
                  SYSTEM
----------
          ID: salt-minion-pki-dir
    Function: file.directory
        Name: C:\ProgramData\Salt Project\Salt\conf\pki\minion
      Result: None
     Comment: The directory "C:\ProgramData\Salt Project\Salt\conf\pki\minion" will be changed
     Started: 18:48:33.409349
    Duration: 0.0 ms
     Changes:
              ----------
              owner:
                  SYSTEM
----------
          ID: permissions-minion.pem
    Function: file.managed
        Name: C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pem
      Result: None
     Comment: File C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pem not updated
     Started: 18:48:33.409349
    Duration: 15.625 ms
     Changes:
              ----------
              owner:
                  SYSTEM
----------
          ID: permissions-minion.pub
    Function: file.managed
        Name: C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pub
      Result: None
     Comment: File C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pub not updated
     Started: 18:48:33.424974
    Duration: 0.0 ms
     Changes:
              ----------
              owner:
                  SYSTEM
----------
          ID: salt-minion
    Function: service.running
      Result: True
     Comment: The service salt-minion is already running
     Started: 18:48:33.565602
    Duration: 8249.913 ms
     Changes:

Summary for INT-UR-TEST-1
------------
Succeeded: 9 (unchanged=6, changed=5)
Failed:    0
------------
Total states run:     9
Total run time:  10.703 s
```

```
salt INT-UR-TEST-1 state.apply salt.minion
```

```
[root@int-ur-it-salt salt]# 
INT-UR-TEST-1:
----------
          ID: salt-minion
    Function: pkg.installed
        Name: salt-minion-py3
      Result: True
     Comment: All specified packages are already installed
     Started: 18:50:13.657307
    Duration: 1296.863 ms
     Changes:
----------
          ID: salt-minion
    Function: file.recurse
        Name: C:\ProgramData\Salt Project\Salt\conf\minion.d
      Result: True
     Comment: Recursively updated C:\ProgramData\Salt Project\Salt\conf\minion.d
     Started: 18:50:14.969795
    Duration: 1171.861 ms
     Changes:
              ----------
              C:\ProgramData\Salt Project\Salt\conf\minion.d:
                  ----------
                  owner:
                      SYSTEM
              C:\ProgramData\Salt Project\Salt\conf\minion.d\beacons.conf:
                  ----------
                  diff:
                      New file
              C:\ProgramData\Salt Project\Salt\conf\minion.d\engine.conf:
                  ----------
                  diff:
                      New file
              C:\ProgramData\Salt Project\Salt\conf\minion.d\f_defaults.conf:
                  ----------
                  diff:
                      New file
              C:\ProgramData\Salt Project\Salt\conf\minion.d\reactor.conf:
                  ----------
                  diff:
                      New file
----------
          ID: remove-old-minion-conf-file
    Function: file.absent
        Name: C:\ProgramData\Salt Project\Salt\conf\minion.d\_defaults.conf
      Result: True
     Comment: File C:\ProgramData\Salt Project\Salt\conf\minion.d\_defaults.conf is not present
     Started: 18:50:16.157287
    Duration: 0.0 ms
     Changes:
----------
          ID: salt-minion
    Function: cmd.run
        Name: salt-call.bat --local service.restart salt-minion
      Result: True
     Comment: Command "salt-call.bat --local service.restart salt-minion" run
     Started: 18:50:16.157287
    Duration: 46.871 ms
     Changes:
              ----------
              pid:
                  7152
              retcode:
                  None
              stderr:
              stdout:
----------
          ID: permissions-minion-config
    Function: file.managed
        Name: C:\ProgramData\Salt Project\Salt\conf\minion
      Result: True
     Comment:
     Started: 18:50:16.204158
    Duration: 140.622 ms
     Changes:
              ----------
              owner:
                  SYSTEM
----------
          ID: salt-minion-pki-dir
    Function: file.directory
        Name: C:\ProgramData\Salt Project\Salt\conf\pki\minion
      Result: True
     Comment: Directory C:\ProgramData\Salt Project\Salt\conf\pki\minion updated
     Started: 18:50:16.344780
    Duration: 15.626 ms
     Changes:
              ----------
              owner:
                  SYSTEM
----------
          ID: permissions-minion.pem
    Function: file.managed
        Name: C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pem
      Result: True
     Comment:
     Started: 18:50:16.360406
    Duration: 15.624 ms
     Changes:
              ----------
              owner:
                  SYSTEM
----------
          ID: permissions-minion.pub
    Function: file.managed
        Name: C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pub
      Result: True
     Comment:
     Started: 18:50:16.376030
    Duration: 0.0 ms
     Changes:
              ----------
              owner:
                  SYSTEM
----------
          ID: salt-minion
    Function: service.running
      Result: True
     Comment: The service salt-minion is already running
     Started: 18:50:16.532286
    Duration: 9421.776 ms
     Changes:

Summary for INT-UR-TEST-1
------------
Succeeded: 9 (changed=6)
Failed:    0
------------
Total states run:     9
Total run time:  12.109 s
```

Will that do? Or do I need to capture a higher log-level or diagnostic level output as well do you think?
