### ISSUE TITLE
[BUG] M2Crypto breaks onedir minion connections

### ISSUE THREAD

**Issue by Amorik** [saltstack/salt#63085]
**Description**
M2Crypto breaks salt-minion connections to salt-master under OneDir setup for 3005.1. 

**Setup**
Docker used to build an isolated test environment, see attached  tar which contains the setup/configuration used. Mostly default configurations aside from enabling auto accept for the salt-minion.  Once container is running we manually ran the `salt-master` and `salt-minion` process by opening an interactive shell to the container. The minion should connect successfully.

Docker Salt Setup/Config: [saltstack_m2crypto_debug.tar.gz](https://github.com/saltstack/salt/files/10035848/saltstack_m2crypto_debug.tar.gz)

The base image is rockylinux and Salt was installed using the onedir packaging repository.

No additional changes made or packages added.

**Steps to Reproduce the behavior**
1. stop running services (salt-master, salt-minion)
2. install m2crypto: `salt-pip install m2crypto`
3. start salt-master, wait until ready
4. start salt-minion; will attempt to connect then salt-master will throw following error

```
[ERROR   ] Future <salt.ext.tornado.concurrent.Future object at 0x7fdb68e87c40> exception was never retrieved: Traceback (most recent call last):
  File "salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "salt/transport/zeromq.py", line 426, in handle_message
    reply = yield self.message_handler(payload)
  File "salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "salt/channel/server.py", line 152, in handle_message
    self._auth(payload["load"], sign_messages)
  File "salt/channel/server.py", line 679, in _auth
    ret["aes"] = pub.public_encrypt(aes, RSA.pkcs1_oaep_padding)
AttributeError: 'RsaKey' object has no attribute 'public_encrypt'
```

Salt Master Debug Log: [salt-master.debug.log](https://github.com/saltstack/salt/files/10035991/salt-master.debug.log)
Salt Minion Debug Log: [salt-minon.debug.log](https://github.com/saltstack/salt/files/10035992/salt-minon.debug.log)

**Expected behavior**
Installing M2Crypto, required for the x509 module, should not break minion connections when using onedir packaging.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.15 (main, Nov  8 2022, 03:47:03)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 8.6 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 5.4.72-microsoft-standard-WSL2
        system: Linux
       version: Rocky Linux 8.6 Green Obsidian
```
</details>

**Additional context**
The error was initial noted when upgrading our production environment to the ondir setup. Since we make heavy use of the x509 module we sought to try and reproduce the issue for debugging. While were able to reproduce it under a docker container we are struggling to address the problem.
