### ISSUE TITLE
[BUG] salt-ssh: saltutil.sync_grains removes custom grains modules that have been extracted by ssh_py_shim.py (shimmed command)

### ISSUE THREAD

**Issue by st-voss** [saltstack/salt#63088]
**Description**
When using salt-ssh custom grains modules (usually in <roots_dir>/_grains/) are propagated to the minions my means of so called "shimmed commands". A shimmed command basically runs "ssh <minion> python ssh_py_shim.py".

On the master all custom grains modules are cached in <cachedir>/ext_mods.<hash>.tgz. When running salt-ssh the current <cachedir>/ext_mods.<hash>.tgz archive is copied to the minion (via scp) and extracted to <thin_dir>/running_data/var/cache/salt/minion/extmods by ssh_py_shim.py before the "salt-call --local ..." is made on the minion. The file <thin_dir>/ext_version is used to keep track of the current ext_mods.<hash>.tgz that has been extracted by ssh_py_shim.py.

When running "salt-ssh ... saltutil.sync_grains" sync() in utils/extmods.py is called on the minion.
In sync() all files are removed from <extension_modules>/grains (e.g. /tmp/salt-thin_dir/running_data/var/cache/salt/minion/extmods/grains) that don't have a matching file in <cachedir>/files/base/_grains (e.g. /tmp/salt-thin_dir/running_data/var/cache/salt/minion/files/base/_grains). With default config settings for <extension_modules> this happens to be the same directory into that ssh_py_shim.py has extracted ext_mods.<hash>.tgz.

As a result no custom grains modules are present on the minion and no custom grains can be set on the minion or rendered in state files.

**Setup**
From /etc/salt/master:

```
roster: dir
roster_dir: /etc/salt/roster.d
roster_defaults:
  thin_dir: /tmp/salt-thin_dir

```
Sample minion roster file  /etc/salt/roster.d/ubuntumate-vm:
`host: 192.168.122.29`

Custom grains module /srv/salt/_grains/custom_grain.py:
```
#!/usr/bin/env python

def custom_grain():
    return { 'foo': 'bar' }

if __name__ == "__main__":
   print(custom_grain())

```
Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

Start with clean thin_dir on target minion (ubuntumate-vm)

```
root@ubuntumate-vm:~# rm -rf /tmp/salt-thin_dir/
root@ubuntumate-vm:~# 

```
Execute saltutil.sync_grains on target minion

```
[root@endeavourvm ~]# salt-ssh ubuntumate-vm saltutil.sync_grains
/usr/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
ubuntumate-vm:

```
No extension modules are present on target minion

```
root@ubuntumate-vm:~# find /tmp/salt-thin_dir/running_data/var/cache/salt/minion/extmods/
/tmp/salt-thin_dir/running_data/var/cache/salt/minion/extmods/

```
But <thin_dir>/ext_version exists, so ext_mods.<hash>.tgz has been propagated and extracted:

```
root@ubuntumate-vm:~# ls -l /tmp/salt-thin_dir/ext_version 
-rw-r--r-- 1 root root 40 Nov 20 09:39 /tmp/salt-thin_dir/ext_version

root@ubuntumate-vm:~# cat /tmp/salt-thin_dir/ext_version ; echo
37734a2d439e169db1fb375f77888729019a481b
```
No custom grain "foo" is set

```
[root@endeavourvm ~]# salt-ssh ubuntumate-vm grains.item foo
/usr/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
ubuntumate-vm:
    ----------

```

**Expected behavior**

Custom grains module from /srv/salt/_grains/ should be present on a minion after a "salt-ssh <minion> saltutil.sync_grains".
"salt-ssh <minion> grains.item <custom grain>" should report the proper custom grain value after "salt-ssh <minion> saltutil.sync_grains"

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
root@endeavourvm ~]# salt --versions-report
/usr/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.12.0
        pygit2: Not Installed
        Python: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 24.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: endeavouros rolling rolling
        locale: utf-8
       machine: x86_64
       release: 6.0.9-arch1-1
        system: Linux
       version: EndeavourOS rolling rolling
```
</details>

**Additional context**
