### ISSUE TITLE
[BUG] Single running python.exe process in 3005.1 classic onwards

### ISSUE THREAD

**Issue by bsoldhogg** [saltstack/salt#63111]
**Description**
When installing 3005.1-x classic (via the exe and msi) only one python.exe process is running.

**Setup**
In my on-prem setup I have upgraded a handful of minions from 3004.1 to 3005.1-3 and noticed a single running python.exe process. Downgrading to 3004.2 brought back the second process.

I do not actively manage `multiprocessing` in the minions config.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
I have stripped back setup in a lab to a freshly created windows ec2 instance from an amazon base image, and a freshly created Ubuntu 20.04 acting as master (also running 3005.1) and I am seeing the same issue on the Windows minion. As #62849 prevents me from checking whether `multiprocessing` is actually enabled I have set this value to true manually.

**Expected behavior**
Confirmed with @twangboy that there should be 2 running processes at all times, unless multiprocessing is disabled.

**Screenshots**
![3004.1](https://user-images.githubusercontent.com/52160995/203765197-886b32cc-732e-4bac-95ef-36c67d84b128.png)

![3005.2](https://user-images.githubusercontent.com/52160995/203765227-ed457e08-014b-4158-b072-7e9438a9eea2.png)

**Versions Report**

**master**

```
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1019-aws
        system: Linux
       version: Ubuntu 20.04 focal
```

**minion**  

```
Salt Version:
              Salt: 3005.1

    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.7
         gitpython: Not Installed
            Jinja2: 3.1.0
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.4
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.10.1
            pygit2: Not Installed
            Python: 3.8.14 (tags/v3.8.14:f43e767, Sep 30 2022, 10:51:05) [MSC v.1929 64 bit (AMD64)]
      python-gnupg: 0.4.8
            PyYAML: 5.4.1
             PyZMQ: 19.0.0
             smmap: 4.0.0
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.2

    System Versions:
              dist:
            locale: cp1252
           machine: AMD64
           release: 2016Server
            system: Windows
           version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```
