### ISSUE TITLE
Discussion: separate environment partitioning from state/pillar allocation

### ISSUE THREAD

**Issue by jesusaurus** [saltstack/salt#6313]
I would very much like to see environments detangled from the state and pillar top files, and want to start a discussion about what this.

In my ideal salt master configuration, I would set the pillar environment based on the minion's domain, and the actual pillars based on the minion's hostname. With the current system, I end up with large amounts of nearly duplicate entries in the pillar top file. In each environment, I change the id slightly to match the domain of the environment, then list all the same pillars because its a duplicate entry for the hostname.

``` yaml
base:
  '*':
    - package_names
    - public_keys

dev:
  'web*.dev.example.com':
    - website
  'es*.dev.example.com':
    - elasticsearch
  '*mirror*.dev.example.com':
    - apt.repo
    - pypi.repo
    - gem.repo

prod:
  'web*.prod.example.com':
    - website
  'es*.prod.example.com':
    - elasticsearch
  '*mirror*.prod.example.com':
    - apt.repo
    - pypi.repo
    - gem.repo
```

All the environment is, really, is a different directory to look in.  I think this can and should be abstracted away from what is being looked for in the directory. I would really like to be able to match environments separately from matching pillars. That would let me remove redundancy from the top file, and I also think that it would make it more clear to newcomers how environments can be used in salt.

I don't use state environments, only pillar environments, but I imagine a similar argument could be made there as well.

Thoughts?
