### ISSUE TITLE
[BUG] mount.mounted state on AIX fails with usage output of mount command

### ISSUE THREAD

**Issue by st-voss** [saltstack/salt#63134]
**Description**

When running state.apply on an AIX minion for a states file that features a mount.mounted state without an opts attribute the state.apply fails with an usage message for the AIX mount command.

```
# salt-ssh  aixXXX state.apply states.sample_mount
aixXXX:
----------
          ID: Mount example
    Function: mount.mounted
        Name: /yumrepo
      Result: False
     Comment: Usage: mount [-fipr] [-n node] [-o options] [-t type] [-{v|V} vfs] [-a | all | [[node:]device] [dir]]
     Started: 11:13:18.256082
    Duration: 158.806 ms
     Changes:

Summary for aixXXX
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 158.806 ms

```

**Setup**

No specific AIX minion config is needed. Let's take the following state file as an example: 

```
# cat /srv/salt/states/sample_mount/init.sls

Mount example:
  mount.mounted:
    - name: /yumrepo
    - device: nimmaster:/yumrepo
    - fstype: nfs
    - mkmnt: True
    - persist: False
```

Please note that there is no "opts" attribute in the above state file.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

With the state file above present on the master execute

`# salt-ssh  aixXXX state.apply states.sample_mount`

**Expected behavior**

The salt-ssh aixXXX state.apply states.sample_mount or salt aixXXX state.apply states.sample_mount mounts the filesystem specified in the state file if not already mounted.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
# salt-ssh --versions-report
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.7.12 (default, Dec 15 2021, 03:25:47)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: aix 2
        locale: ISO8859-1
       machine: 00XXXXXXXXXX
       release: 2
        system: AIX
       version: AIX 2

```
</details>

**Additional context**
This is *not* an salt-ssh issue. The error shows up on `salt aixXXX ...` or `salt-call --local ...`, too
