### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bdrx312** [saltstack/salt#63173]
**Description**

Using the pyobjects renderer, specifying a require requisite argument on Sls `require=Sls("requirement")` gives an error

```
[CRITICAL] Rendering SLS test failed, render error: name 'Sls' is not defined
...
NameError: name 'Sls is not defined
```

The equivalent to specify a requirement on a full sls in `jinja|yaml` which works is

```
include:
  - requirement

"/testfile":
   file.managed:
     - owner: "root"
     - group: "root"
     - require:
       - sls: "requirement"
```

**Setup**

  - [ ] ec2 instance running rhel 7.9
  - [ ] classic packaging (yum install salt-minion)
  - [ ] Create `/srv/salt/test.sls`:

    ```
    #!pyobjects
    include("requirement")
    File.managed("/testfile", owner="root", group="root", require=Sls("requirement"))
    ```

  - [] Create `/srv/salt/requirement.sls`:

    ```
    #!pyobjects
    File.managed("/requirement", owner="root", group="root")
    ```

**Steps to Reproduce the behavior**

`salt-call --local state.apply test`

**Expected behavior**
Expected to create a require requisite on the full sls requirement file.

**Versions Report**
<details><summary>salt-call --versions-report</summary>

```yaml
Salt Version:
        Salt: 3004.1

System Versions:
      dist: rhel 7.9 Maipo
    locale: UTF-8
   release: 3.10.0-1160.15.2.el7.x86_64
   system: Linux
```
</details>
