### ISSUE TITLE
[BUG] mount.filesystems on AIX only reports first filesystems entry

### ISSUE THREAD

**Issue by st-voss** [saltstack/salt#63183]
**Description**
`salt-ssh <aixminion> mount.filesystems` or `salt <aixminion> mount.filesystems` on AIX only reports the first entry from /etc/filesystems (or the filesystems file specified by the config parameter) instead of all entries

**Setup**
No specific AIX minion configuration needed. Let's take the folllowing /tmp/filesystems file as example:

```
# cat /tmp/filesystems
/mnt/foo:
        dev             = /dev/bar
        vfs             = jfs2
        mount           = False

/mnt/foo2:
        dev             = /dev/bar2
        vfs             = jfs2
        mount           = False

```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

With the /tmp/filesystems file described above execute the following on an AIX minion:

```
# salt-ssh aixXXX mount.filesystems config=/tmp/filesystems
aixXXX:
    ----------
    /mnt/foo:
        ----------
        dev:
            /dev/bar
        mount:
            False
        vfs:
            jfs2

```

Only the first entry "/mnt/foo" is reported. The second entry "/mnt/foo2" is not reported

**Expected behavior**
All entries from the selected filesystems file are reported.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
# salt-ssh --versions-report
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.7.12 (default, Dec 15 2021, 03:25:47)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: aix 2
        locale: ISO8859-1
       machine: 00XXXXXXXXXX
       release: 2
        system: AIX
       version: AIX 2


```
</details>

**Additional context**
