### ISSUE TITLE
[BUG] Users are not deleted from grafana organization

### ISSUE THREAD

**Issue by keenobi** [saltstack/salt#63198]
**Description**

Using the state grafana4_org, we realized that the users present in the organization on Grafana but not in the `users` argument of the state were still kept in the Grafana org.

**Steps to Reproduce the behavior**

1. Run state with this value : 

```
Ensure TestOrg organization is present:
  grafana4_org.present:
    - name: TestOrg
      users:
          testuser1: Viewer
          testuser2: Viewer
```

2. Run state with this value :

```
Ensure TestOrg organization is present:
  grafana4_org.present:
    - name: TestOrg
      users:
          testuser1: Viewer
```

You can see that `testuser2` is not remove from Grafana `TestOrg` organization

**Expected behavior**

`testuser2` is removed from the Grafana organization.

**Versions Report**

<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
root@salt:~ # salt --versions-report
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
        dist: debian 11 bullseye
        locale: utf-8
       machine: aarch64
       release: 5.10.0-19-cloud-arm64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**

We thought maybe it was on purpose. So we will propose a PR with a `clean_users` boolean with `False` as default value.
