### ISSUE TITLE
ipset module new_set() function broken

### ISSUE THREAD

**Issue by ixs** [saltstack/salt#63224]
It does look like the ipset module has been broken for quite a while in a way, that was not obvious before.

I have a state that has been running fine on CentOS7 in the past but is now broken since the 3005 release.

```
ssh_blacklist:
  ipset.set_present:
    - name: fail2ban-ssh-global
    - set_type: hash:ip
    - family: ipv4
    - comment: true
    - timeout: 43200
 ```

ipset will report the following error:

```
          ID: ssh_blacklist
    Function: ipset.set_present
        Name: fail2ban-ssh-global
      Result: False
     Comment: Failed to create set fail2ban-ssh-global for ipv4: ipset v7.11: Syntax error: unknown inet family ['/usr/sbin/ipset', 'create', 'fail2ban-ssh-global', 'hash:ip', 'timeout', 43200, 'family', [...], 'inet', 'comment']
     Started: 20:23:47.099776
    Duration: 26.852 ms
     Changes:
```
Do note the `[...]` field in the comment. 

This is due to an error in https://github.com/saltstack/salt/blob/5b18e86cda8a5cb71dc20b40b55a04e4c489363c/salt/modules/ipset.py#L331.

Instead of extending the `cmd` with itself (`["family", cmd, ipset_family]`), it should only be extended by the family parameter and the ipset_family parameter.

Removing the superfluous cmd fixes the command:

```
----------
          ID: ssh_blacklist
    Function: ipset.set_present
        Name: fail2ban-ssh-global
      Result: True
     Comment: ipset set fail2ban-ssh-global created successfully for ipv4
     Started: 20:24:49.040701
    Duration: 23.402 ms
     Changes:
              ----------
              locale:
                  fail2ban-ssh-global
```

The error was introduced in https://github.com/saltstack/salt/commit/0e46c14907f1c63c9bd7206ed3a7dd59e59e0800
