### ISSUE TITLE
[BUG] lgpo.set fails when policy is already in desired state

### ISSUE THREAD

**Issue by VitalyMutyev** [saltstack/salt#63296]
**Description**
If the group policy already configured as declared in state file, Salt state.apply execution exits with failure.

Note: This behaviour is not limited to the policy given in example below - there are multiple policies(from ADMX template referenced below) with described bug. 

**Setup**

State file hardening-microsoft-test.sls:
```yaml
'File Type Blocking Excel':
  lgpo.set:
    - user_policy:
         "Microsoft Excel 2016\\Excel Options\\Security\\Trust Center\\File Block Settings\\Dif and Sylk files":
           "L_DifAndSylkFilesDropID": "Open/Save blocked, use open policy"
```

**Steps to Reproduce the behavior**
1. Get Administrative Template files (ADMX/ADML) for Microsoft 365 Apps for enterprise/Office LTSC 2021/Office 2019/Office 2016 and the Office Customization Tool for Office 2016: https://www.microsoft.com/en-us/download/details.aspx?id=49030
2. Copy templates to Windows machine - upload ADMX files to  'C:\Windows\PolicyDefinitions\', restart PC. If applied successfully, you should see Office the policies in Local Group Policy Editor: User Configuration\Microsoft Excel 2016\Excel Options\Security\Trust Center\File Block Settings\Dif and Sylk files
3. Apply the state more than once:
```yaml
$sudo salt 'test-S*' state.apply security.hardening-microsoft-test
test-Surface-cracked:
----------
          ID: File Type Blocking Excel
    Function: lgpo.set
      Result: True
     Comment: The following policies changed:
              Microsoft Excel 2016\Excel Options\Security\Trust Center\File Block Settings\Dif and Sylk files
     Started: 20:08:01.484804
    Duration: 24129.009 ms
     Changes:   
              ----------
              new:
                  ----------
                  User Configuration:
                      ----------
                      Microsoft Excel 2016\Excel Options\Security\Trust Center\File Block Settings\Dif and Sylk files:
                          ----------
                          File block setting:
                              Open/Save blocked, use open policy
              old:
                  ----------
                  User Configuration:
                      ----------
                      Microsoft Excel 2016\Excel Options\Security\Trust Center\File Block Settings\Dif and Sylk files:
                          Not Configured

Summary for test-Surface-cracked
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  24.129 s
```
run second time:
```yaml
$sudo salt 'test-S*' state.apply security.hardening-microsoft-test
test-Surface-cracked:
----------
          ID: File Type Blocking Excel
    Function: lgpo.set
      Result: False
     Comment: Failed to set the following policies:
              Microsoft Excel 2016\Excel Options\Security\Trust Center\File Block Settings\Dif and Sylk files
     Started: 20:16:33.973043
    Duration: 24291.846 ms
     Changes:   

Summary for test-Surface-cracked
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  24.292 s
```

**Expected behavior**
Salt should exit with "Result: True" and notify there are no changes applied in current state of configured GPO.

**Versions Report**
MASTER:
$ salt -V
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Nov 14 2022, 12:59:47)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1023-aws
        system: Linux
       version: Ubuntu 20.04 focal

MINION:
    Salt Minion 3005.1 (Tiamat):
        3005.1
 
   os_name:
        Microsoft Windows 10 Pro
    os_type:
        Work Station
    os_version:
        10.0.19045

</details>
