### ISSUE TITLE
[BUG] When using onedir Salt needs full package version on RedHat family for installing packages via highstate

### ISSUE THREAD

**Issue by sanderc85** [saltstack/salt#63317]
**Description**
When I try to install a package via States and I give a part of the version number of a package and that package is already installed on an dnf/yum based installation, then the state will fail when the Salt minion is installed as a onedir package.

**Setup**
To set it up I've used an `almalinux:8` Docker image. I've installed Salt like described here: https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/rhel.html#install-onedir-packages-of-salt-on-redhat-rhel-8. 

**Steps to Reproduce the behavior**
On the almalinux image the hostname package is already installed, the full package name in rpm is: `hostname-3.20-6.el8.x86_64`. When I created this state-file you should expect a succesfull highstate:

```
install-hostname:
  pkg.installed:
    - name: hostname
    - version: '3.20'
```

Howerver, on running an `state.apply` it failed with this error message:

```
[ERROR   ] The following packages failed to install/update: hostname=3.20
local:
----------
          ID: install-hostname
    Function: pkg.installed
        Name: hostname
      Result: False
     Comment: The following packages failed to install/update: hostname=3.20
     Started: 07:48:19.925783
    Duration: 7150.899 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   7.151 s
```

In de logging the next message is visible:

```
[DEBUG   ] Current version (['3.20-6.el8']) did not match desired version specification (3.20), adding to installation targets
```

**Expected behavior**
It should be expected that the output would be:
```
local:
----------
          ID: install-hostname
    Function: pkg.installed
        Name: hostname
      Result: True
     Comment: All specified packages are already installed and are at the desired version
     Started: 07:09:29.350086
    Duration: 130.694 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 130.694 ms
```

**Versions Report**
<details><summary>salt --versions-report</summary>

I'm currently running this as a local minion. The issue only occures on a Minion installed as onedir package.

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.15 (main, Nov  8 2022, 03:47:03)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 8.7 Stone Smilodon
        locale: utf-8
       machine: x86_64
       release: 5.10.102.1-microsoft-standard-WSL2
        system: Linux
       version: AlmaLinux 8.7 Stone Smilodon
```
</details>

**Additional context**

It works as expected when installing Salt 3005.1 as a classic package. I think when using the onedir package some version comparison is going different and maybe because the Python `rpm` module isn't available in the onedir package and it is available when using the classic Salt package. However, this would have been fixed by #60814. I have also described my findings on Slack: https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1670841608511299

Also, I used in this case Docker to simplify the issue. I have this issue also on virtual machines, it's not dependent on the underlaying platform, as long as it's an RedHat based opering system this seems to occur.

For now I have a workaround for this issue to specify the full version. However it worked on the classic install, that's why I think this is a bug.
