### ISSUE TITLE
[BUG] lgpo.get does not return state of EnableScriptBlockLogging if Enabled

### ISSUE THREAD

**Issue by dstoliker** [saltstack/salt#63312]
**Description**
The `lgpo.get` execution module does not return the state of "Windows Components\Windows PowerShell\Turn on PowerShell Script Block Logging" (aliased to EnableScriptBlockLogging) if the current state is "Enabled" - whether the checkbox included in the policy is checked or not. If the policy is set to "Not Configured" or "Disabled", `lgpo.get` will return as normal.

**Setup**

- [x] VM VMware Fusion

**Steps to Reproduce the behavior**
The policy is provided by the template PowerShellExecutionPolicy.admx/adml included in the Microsoft Windows 10 RTM (Release 1507) Administrative Templates or newer.

The command `lgpo.get_policy_info` confirms its presence.

```
salt-call --local lgpo.get_policy_info EnableScriptBlockLogging machine

local:
    ----------
    message:
    policy_aliases:
        - Turn on PowerShell Script Block Logging
        - EnableScriptBlockLogging
        - Windows Components\Windows PowerShell\Turn on PowerShell Script Block Logging
    policy_class:
        machine
    policy_elements:
        |_
          ----------
          element_aliases:
              - EnableScriptBlockInvocationLogging
              - Log script block invocation start / stop events
          element_id:
              EnableScriptBlockInvocationLogging
    policy_found:
        True
    policy_name:
        EnableScriptBlockLogging
    rights_assignment:
        False
```

If the policy is in a `Not Configured` or `Disabled` state, `lgpo.get` will return as expected.

```
salt-call --local lgpo.get_policy EnableScriptBlockLogging machine

local:
    Not Configured
```

The policy can be Enabled via the `lgpo.set` execution module or state module. For example:

```
enable_powershell_block_logging:
  lgpo.set:
    - computer_policy:
        EnableScriptBlockLogging:
          EnableScriptBlockInvocationLogging: False
```

The state will apply the change correctly and include a changes dictionary:

```
local:
----------
          ID: enable_powershell_block_logging
    Function: lgpo.set
      Result: True
     Comment: The following policies changed:
              EnableScriptBlockLogging
     Started: 08:18:24.042996
    Duration: 813.083 ms
     Changes:
              ----------
              new:
                  ----------
                  Computer Configuration:
                      ----------
                      EnableScriptBlockLogging:
                          ----------
              old:
                  ----------
                  Computer Configuration:
                      ----------
                      EnableScriptBlockLogging:
                          Not Configured
```

However, the `lgpo.get` execution module does not report the current state of the policy.

```
salt-call --local lgpo.get_policy EnableScriptBlockLogging machine

local:
    ----------
```

**Expected behavior**
The `lgpo.get` execution module should report the current state, whether the check is enabled or not. In particular, it should report the status of the policy element "Log script block invocation start / stop events".

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.15 (tags/v3.8.15:44adf8a, Nov  8 2022, 17:20:07) [MSC v.1929 64 bit (AMD64)]
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 22.0.3
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2016Server
        system: Windows
       version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```
</details>

**Additional context**
