### ISSUE TITLE
[BUG] SELinux fcontext can sometimes not be retrieved

### ISSUE THREAD

**Issue by derdeagle** [saltstack/salt#63336]
**Description**
It seems that sometimes the output from `semanage fcontext -l` can contain a trailing whitespace. This leads to erroneous returns when checked if a specific file context exists. If it exists it will return an error like

```
Error adding new rule: {'pid': 5778, 'retcode': 1, 'stdout': '',
'stderr': 'ValueError: File context for /var/log/rsyslog-target(/.*)?
already defined'}
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [x] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Add fcontext via the state - the first time it will succeed and afterwards it will fail, see error above.

**Expected behavior**
It should be noticed it is already there and not tried to add it again.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.6.1
        Python: 3.7.13 (default, Apr 20 2022, 03:16:50)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: alpine 3.14.6 
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-408.el8.x86_64
        system: Linux
       version: Alpine Linux 3.14.6 
```
</details>

**Additional context**
