### ISSUE TITLE
[BUG] zypper repository always re-configured

### ISSUE THREAD

**Issue by tacerus** [saltstack/salt#63402]
**Description**
`pkgrepo.managed` repositories on SLE and openSUSE always return as "configured", albeit no repository information having changed:

```
root@bceea1989b9c /s/salt-git# salt dev-ha-1 pkg.get_repo SLE-Product-HA-UPDATES 
dev-ha-1:
    ----------
    alias:
        SLE-Product-HA-UPDATES
    autorefresh:
        True
    baseurl:
        http://mirror/update
    enabled:
        True
    gpgcheck:
        True

root@bceea1989b9c /s/salt-git# salt dev-ha-1 state.apply profile.suse_ha.repositories
dev-ha-1:
----------
          ID: sle_module_ha
    Function: pkgrepo.managed
        Name: SLE-Product-HA-POOL
      Result: True
     Comment: Configured package repo 'SLE-Product-HA-POOL'
     Started: 15:08:22.378213
    Duration: 951.634 ms
     Changes:   
----------
          ID: sle_module_ha
    Function: pkgrepo.managed
        Name: SLE-Product-HA-UPDATES
      Result: True
     Comment: Configured package repo 'SLE-Product-HA-UPDATES'
     Started: 15:08:23.330296
    Duration: 104.161 ms
     Changes:   

root@bceea1989b9c /s/salt-git# salt dev-ha-1 pkg.get_repo SLE-Product-HA-UPDATES 
dev-ha-1:
    ----------
    alias:
        SLE-Product-HA-UPDATES
    autorefresh:
        True
    baseurl:
        http://download.suse.de/ibs/SUSE/Updates/SLE-Product-HA/15-SP4/x86_64/update
    enabled:
        True
    gpgcheck:
        True

```

**Setup**
```
sle_module_ha:
  pkgrepo.managed:
    - names:
      - 'SLE-Product-HA-POOL':
        - humanname: 'SLE-Product-HA-POOL'
        - refresh: False
        - gpgcheck: 1
        - baseurl: http://mirror/product
        - gpgkey: http://mirror/product/repomd.xml.key
      - 'SLE-Product-HA-UPDATES':
        - refresh: True
        - gpgcheck: 1
        - baseurl: http://mirror/update
        - gpgkey: http://mirror/update/repomd.xml.key

```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (KVM)
- [x] classic packaging

**Steps to Reproduce the behavior**
1. add managed Zypper repository via `pkgrepo.managed`
2. apply the state -> the repository will be added
3. re-apply the state -> ghost-changes are reported

**Expected behavior**
The state module should detect the repository to be already up to date.

**Screenshots**
n/a

**Versions Report**
```
root@bceea1989b9c /s/salt-git# salt --versions
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: sles 15.4 
        locale: UTF-8
       machine: x86_64
       release: 6.0.12-1-default
        system: Linux
       version: SLES 15.4 
```

Note: I tested this behavior with the `pkgrepo` module from the latest master branch at the state of e47e47a7e675280be8925a00766a62e4b2c7fb07.

**Additional context**
I will submit a proposed patch following this report.
