### ISSUE TITLE
[BUG] __opts__["test"] is not True in cross called state module when custom state is prereq target

### ISSUE THREAD

**Issue by bdrx312** [saltstack/salt#63414]
**Description**

When cross calling a state module from custom state module as documented here https://docs.saltproject.io/en/latest/ref/states/writing.html#cross-calling-state-modules, if the custom module is set as target of a prereq the __opts__["test"] value is not correctly also set on the cross called state.

**Setup**

  - [ ] ec2 instance running rhel 7.9
  - [ ] classic packaging (yum install salt-minion)
  - [ ] create a minimum custom state to cross call another state /srv/salt/_states/custom_state.py:
      ```python
      def wrap(*args, **kwargs):
          return __states__["file.managed"](*args, **kwargs)
      ```

  - [ ] create `/srv/salt/test.sls`:

      ```yaml
      "/tmp/trash_dir/trash_file":
        custom_state.wrap:
          - contents: "\n"
       
      "/tmp/trash_dir":
        file.directory:
          - prereq:
            - "/tmp/trash_dir/trash_file"
      ```

**Steps to Reproduce the behavior**

```sh
salt-call -l info --local saltutil.sync_all
salt-call -l info --local state.apply test
```

Output:
```
----------
ID: /tmp/trash_dir
Function: file.directory
Result: False
Comment: One or more requisite failed: test./tmp/trash_dir/trash_file
Started: ...
Duration: 4ms
Changes:
----------
ID: /tmp/trash_dir/trash_file
Function: custom_state.wrap
Result: False
Comment: Parent directory not present
Changes:

Summary for local
------------
Failed: 2
------------
```

**Expected behavior**

"/tmp/trash_dir" and "/tmp/trash_dir/trash_file" should be created; the "/tmp/trash_dir/trash_file" state should be detected as needing changes and the required state which has the prereq "/tmp/trash_dir" should be created. The `__opts__['test']` variable should be set to True in the __states__["file.managed"] state call from the  custom_state.wrap state so that the prereq condition behaves correctly.

**Versions Report**
<details><summary>salt-call --versions-report</summary>

```yaml
Salt Version:
        Salt: 3004.1

Dependency Versions:
    Jinja2: 2.11.1
    Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
    PyYAML: 3.13

System Versions:
      dist: rhel 7.9 Maipo
    locale: UTF-8
   release: 3.10.0-1160.15.2.el7.x86_64
   system: Linux
```
</details>
