### ISSUE TITLE
[BUG] Incorrect template variables in init.sls included as '.'

### ISSUE THREAD

**Issue by rcw-2** [saltstack/salt#63411]
**Description**
Since the upgrade to v3005, when `init.sls` is included from a file in the same directory as ".", template variables in `init.sls` get strange values:
* `sls` has a dot at the end.
* `slspath` and `tpldir` contain the absolute path (starting with `/var/cache/salt/...`) to the directory of `init.sls`.
* `tplfile` contains the absolute path of `init.sls` (same as `tplpath`).

This may lead to a variety of other errors. As a workaround, you can include `init.sls` by its full name (`test` in the example) or as `{{slsdotpath}}`.

**Setup**
`test/sub.sls`:
```yaml
include:
  - .
```

`test/init.sls`:
```yaml
Show Variables:
  cmd.run:
    - name: echo "sls = {{sls}}\nslspath = {{slspath}}\ntplfile = {{tplfile}}\ntpldir = {{tpldir}}\ntplpath = {{tplpath}}"
```

**Steps to Reproduce the behavior**
`salt <minion> state.sls test.sub`

Result:
```
<minion>:
----------
          ID: Show Variables
[...]
              stdout:
                  sls = test.
                  slspath = /var/cache/salt/minion/files/<env>/test
                  tplfile = /var/cache/salt/minion/files/<env>/test/init.sls
                  tpldir = /var/cache/salt/minion/files/<env>/test
                  tplpath = /var/cache/salt/minion/files/<env>/test/init.sls
[...]
```

**Versions Report**
<details><summary>salt-minion --versions-report</summary>
```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: 1.3.10
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Nov 25 2022, 14:10:45)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-135-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```
</details>
