### ISSUE TITLE
[BUG] lgpo.set fails to set bool elements when mixed in with enums in 3005.1

### ISSUE THREAD

**Issue by rudeb0t** [saltstack/salt#63473]
**Description**

When using `lgpo.set` to set a mix of `enum` and `bool` elements only the enum elements are set. This was working properly in Salt 3004.1. For example:

```yaml
configure_automatic_updates:
  lgpo.set:
    - computer_policy:
        'Configure Automatic Updates':
          'Configure automatic updating': 4 - Auto download and schedule the install
          'Install during automatic maintenance': False
          'Scheduled install day': 0 - Every day
          'Scheduled install time': 03:00
          'Install updates for other Microsoft products': False
          'Every week': False
          'First week of the month': False
          'Second week of the month': False
          'Third week of the month': False
          'Fourth week of the month': False
```

Would result in:

```yaml
          ID: configure_automatic_updates                                                                                
    Function: lgpo.set                                                                                                                                                                        
      Result: True                                                                                                                                                                            
     Comment: The following policies changed:                                                                                                                                                 
              Configure Automatic Updates                                                                                                                                                     
     Started: 08:10:59.720845                                                                                                                                                                 
    Duration: 1141.429 ms                                                                                                                                                                     
     Changes:                                                                                                                                                                                 
              ----------                                                                                                                                                                      
              new:                                                                                                                                                                            
                  ----------                                                                                                                                                                  
                  Computer Configuration:                                                                                                                                                     
                      ----------                                                                                                                                                              
                      Configure Automatic Updates:                                                                                                                                            
                          ----------                                                                                                                                                          
                          Configure automatic updating:                                                                                                                                       
                              4 - Auto download and schedule the install                                                                                                                      
                          Scheduled install day:                                                                                                                                              
                              0 - Every day                                                                                                                                                   
                          Scheduled install time:                                                                                                                                             
                              03:00                                                                                                                                                           
              old:                                                                                                                                                                            
                  ----------                                                                                                                                                                  
                  Computer Configuration:                                                                                                                                                     
                      ----------                                                                                                                                                              
                      Configure Automatic Updates:                                                                                                                                            
                          Not Configured                                                                                                                                                      
```

**Setup**
- [ ] Virtualbox Windows Server 2016
- [ ] Salt Version 3005.1

**Steps to Reproduce the behavior**

SLS file `configure_automatic_updates.sls`:
```yaml
configure_automatic_updates:
  lgpo.set:
    - computer_policy:
        'Configure Automatic Updates':
          'Configure automatic updating': 4 - Auto download and schedule the install
          'Install during automatic maintenance': False
          'Scheduled install day': 0 - Every day
          'Scheduled install time': 03:00
          'Install updates for other Microsoft products': False
          'Every week': False
          'First week of the month': False
          'Second week of the month': False
          'Third week of the month': False
          'Fourth week of the month': False
```

`salt 'window-minions.*' state.apply configure_automatic_updates`

**Expected behavior**

`lgpo.set` should set both `enum` and `bool` elements on the policy.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:                                                                                                                   
          Salt: 3005.1                                                                                                          
                                                                                                                                
Dependency Versions:                                                                                                            
          cffi: 1.14.6                                                                                                          
      cherrypy: 18.6.1                                                                                                          
      dateutil: 2.8.1                                                                                                           
     docker-py: Not Installed                                                                                                   
         gitdb: 4.0.7                                                                                                           
     gitpython: Not Installed                                                                                                   
        Jinja2: 3.1.0                                                                                                           
       libgit2: Not Installed                                                                                                   
      M2Crypto: Not Installed                                                                                                   
          Mako: 1.1.4                                                                                                           
       msgpack: 1.0.2                                                                                                           
  msgpack-pure: Not Installed                                                                                                   
  mysql-python: Not Installed                                                                                                   
     pycparser: 2.21                                                                                                            
      pycrypto: Not Installed                                                                                                   
  pycryptodome: 3.10.1                                                                                                          
        pygit2: Not Installed                                                                                                   
        Python: 3.8.15 (tags/v3.8.15:44adf8a, Nov  8 2022, 17:20:07) [MSC v.1929 64 bit (AMD64)]                                
  python-gnupg: 0.4.8                                                                                                           
        PyYAML: 5.4.1                                                                                                           
         PyZMQ: 22.0.3                                                                                                          
         smmap: 4.0.0                                                                                                           
       timelib: 0.2.4                                                                                                           
       Tornado: 4.5.3                                                                                                           
           ZMQ: 4.3.4                                                                                                           
                                                                                                                                
System Versions:                                                                                                                
          dist:                                                                                                                 
        locale: cp1252                                                                                                          
       machine: AMD64                                                                                                           
       release: 2016Server                                                                                                      
        system: Windows                                                                                                         
       version: 2016Server 10.0.14393 SP0 Multiprocessor Free                                                                   
                                                                                                                                
```
</details>

**Additional context**
