### ISSUE TITLE
[BUG] Wheel `key.accept` report success even if it did not accepted anything 

### ISSUE THREAD

**Issue by TeddyAndrieux** [saltstack/salt#63477]
**Description**

When I use wheel `key.accept` module on a minion that does not exists it returns a `success`

**Setup**

Really basic setup

**Steps to Reproduce the behavior**

```console
$ salt-call saltutil.wheel key.accept invalid-minion
local:
    ----------
    _stamp:
        2023-01-13T10:06:04.503984
    fun:
        wheel.key.accept
    fun_args:
        - invalid-minion
    jid:
        20230113100604497168
    return:
        ----------
    success:
        True
    user:
        UNKNOWN
```

**Expected behavior**

Either an exception saying that there is no minion matching it, either the `success` field set to `False`

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3002.9
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov  8 2022, 11:32:15)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 8.7 Green Obsidian
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-372.32.1.el8_6.x86_64
        system: Linux
       version: Rocky Linux 8.7 Green Obsidian
```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
3002.9 is no longer supported (and has multiple security issues). Does the problem still exist in the latest version?

**Comment by TeddyAndrieux** [comment]
Yes same issue on 3004.2

<details><summary>Output details</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
# salt-call saltutil.wheel key.accept invalid-minion
local:
    ----------
    _stamp:
        2023-01-13T17:26:41.216363
    fun:
        wheel.key.accept
    fun_args:
        - invalid-minion
    jid:
        20230113172641210041
    return:
        ----------
    success:
        True
    user:
        UNKNOWN
# salt --versions-report
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Nov 14 2022, 12:59:47)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 6.0.12-arch1-1
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>
