### ISSUE TITLE
Add fire_event requisite for orchestration runner states

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#63516]
**Is your feature request related to a problem? Please describe.**
Would like to use the fire_event requisite described here (https://docs.saltproject.io/en/latest/ref/states/requisites.html), which works great, but does not work for states in orchestration states (salt.function, salt.state, salt.runner and states executed directly by the internal master minion).

**Describe the solution you'd like**
I'd like to be able to use fire_event: True argument in orchestration state to produce similar events as described by the state fire_event requisite here (https://docs.saltproject.io/en/latest/ref/states/requisites.html)
Something like this for an orchestration state:
```
logging_file_absent:
  file.absent:
    - name: {{ logging_file }}
    **- fire_event: True**

task1:
  salt.state:
    - tgt: 'minion' # my minion on the master
    - sls: deployments.task1
    **- fire_event: True**
```

**Describe alternatives you've considered**
Alternative using event.send runner is a bit complex, adding a lot of overhead, for each state in orchestration state it requires adding event.send state using requisite like require or onfail. Also it does not include the JID.
