### ISSUE TITLE
[BUG] grains fqdns field on arm64 reports differently than previous 3005.1

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#63518]
**Description**
The Grains fqdns field reports differently on Ubuntu 22.10 ARM64 platform 

**Setup**
Current 2006 RC1 pre-release code installed on Ubuntu 22.10 ARM64 Raspberry Pi 4
3005.1 amd64 installed on Ubuntu 20.04

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [X] VM (Virtualbox)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
salt-call --local grains.items

**Expected behavior**
Expected FQDNS grain to return similar entries, could be related to Ubuntu 22.10, need to check on Ubuntu 20.04, but wanted to capture the issue.  On 3006 RC1 pre-release wondering why not using **hostname.example.org** as in Salt 3005.1 but using **Unknown.example.org**.

**Screenshots**
**Ubuntu 22.10 arm64 Raspberry Pi 4**
```
    fqdns:
        - Unknown.example.org
        - david-uarm64
    gid:
        0
    gpus:
    groupname:
        root
    host:
        david-uarm64

```

Ubuntu 20.04 amd64 Salt 3005.1 Classic packaging (VirtualBox VM)
```
    fqdns:
        - david-VirtualBox
        - david-VirtualBox.example.org
    gid:
        0
    gpus:
        |_
          ----------
          model:
              SVGA II Adapter
          vendor:
              vmware
    groupname:
        root
    host:
        david-VirtualBox
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
root@Unknown:/usr/bin# salt u22arm64 test.versions
u22arm64:
    Salt Version:
              Salt: 3005.1+1932.g6ba1294bc2
     
    Dependency Versions:
              cffi: Not Installed
          cherrypy: Not Installed
          dateutil: Not Installed
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.1.2
           libgit2: Not Installed
      looseversion: 1.0.3
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.4
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 23.0
         pycparser: Not Installed
          pycrypto: Not Installed
      pycryptodome: 3.16.0
            pygit2: Not Installed
            Python: 3.10.9 (main, Dec 20 2022, 00:16:32) [GCC 11.2.0]
      python-gnupg: Not Installed
            PyYAML: 6.0
             PyZMQ: 20.0.0
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: ubuntu 22.10 Kinetic Kudu
            locale: utf-8
           machine: aarch64
           release: 5.19.0-1011-raspi
            system: Linux
           version: Ubuntu 22.10 Kinetic Kudu
     
root@Unknown:/usr/bin# 

------------------------------------

root@david-VirtualBox:/home/david# salt-call --local test.versions
local:
    Salt Version:
              Salt: 3005.1
     
    Dependency Versions:
              cffi: Not Installed
          cherrypy: Not Installed
          dateutil: 2.7.3
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.0
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: Not Installed
          pycrypto: Not Installed
      pycryptodome: 3.6.1
            pygit2: Not Installed
            Python: 3.8.10 (default, Nov 14 2022, 12:59:47)
      python-gnupg: 0.4.5
            PyYAML: 5.3.1
             PyZMQ: 20.0.0
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.2
     
    System Versions:
              dist: ubuntu 20.04 focal
            locale: utf-8
           machine: x86_64
           release: 5.15.0-57-generic
            system: Linux
           version: Ubuntu 20.04 focal
     
root@david-VirtualBox:/home/david# 
```
</details>

**Additional context**

**Comment by dmurphy18** [comment]
Using 3005.1 onedir on Ubuntu 22.04 also has hostname.example.org
```
    fqdns:
        - david
        - david.example.org
    gid:
        0
    gpus:
        |_
          ----------
          model:
              SVGA II Adapter
          vendor:
              vmware
    groupname:
        root
    host:
        david
```
Will test 3005.1 Debian 11 ARM64 classic support on Ubuntu 22.04 ARM64 (it works), or Ubuntu's own (3004.1) for 22.04

**Comment by dmurphy18** [comment]
This appears to be a ARM64 issue, since Ubuntu's own fork Salt 3004.1 on ARM64 Raspberry Pi 4 has the issue
```
    fqdns:
        - Unknown.example.org
        - david-u2204arm64
    gid:
        0
    gpus:
    groupname:
        root
    host:
        david-u2204arm64
```
```
root@david-u2204arm64:/home/david# salt-call --local test.versions
local:
    Salt Version:
              Salt: 3004.1
     
    Dependency Versions:
              cffi: Not Installed
          cherrypy: Not Installed
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.0.3
           libgit2: Not Installed
          M2Crypto: 0.38.0
              Mako: 1.1.3
           msgpack: 1.0.3
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: Not Installed
          pycrypto: Not Installed
      pycryptodome: 3.11.0
            pygit2: Not Installed
            Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
      python-gnupg: Not Installed
            PyYAML: 5.4.1
             PyZMQ: 22.3.0
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.4
     
    System Versions:
              dist: ubuntu 22.04 Jammy Jellyfish
            locale: utf-8
           machine: aarch64
           release: 5.15.0-1023-raspi
            system: Linux
           version: Ubuntu 22.04 Jammy Jellyfish
     
root@david-u2204arm64:/home/david# 
```

**Comment by dmurphy18** [comment]
With Debian 11 ARM64 Salt 3005.1 classic packaging installed on Ubuntu 22.04 ARM64 (it is a thing that works)
```
root@david-u2204arm64:/home/david# salt-call --local test.versions
local:
    Salt Version:
              Salt: 3005.1
     
    Dependency Versions:
              cffi: Not Installed
          cherrypy: Not Installed
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.0.3
           libgit2: Not Installed
          M2Crypto: 0.38.0
              Mako: 1.1.3
           msgpack: 1.0.3
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: Not Installed
          pycrypto: Not Installed
      pycryptodome: 3.11.0
            pygit2: Not Installed
            Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
      python-gnupg: Not Installed
            PyYAML: 5.4.1
             PyZMQ: 22.3.0
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.4
     
    System Versions:
              dist: ubuntu 22.04 Jammy Jellyfish
            locale: utf-8
           machine: aarch64
           release: 5.15.0-1023-raspi
            system: Linux
           version: Ubuntu 22.04 Jammy Jellyfish
     
root@david-u2204arm64:/home/david#
```
grains section
```    fqdns:
        - Unknown.example.org
        - david-u2204arm64
    gid:
        0
    gpus:
    groupname:
        root
    host:
        david-u2204arm64
```
