### ISSUE TITLE
[BUG] `reactor` config value type should be list or string

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#63579]
**Description**
It should be possible to specify `reactor` as a string to a YAML-formatted file, according to:
https://github.com/saltstack/salt/blob/3ddd7eb6ffe8059e2f889031c67a4e2605da1a4d/salt/utils/reactor.py#L87-L98

This avoids having to reload the master each time the reactor mappings are updated, therefore providing a piece of `top` file functionality for reactors. This behavior is not documented though.

When trying this functionality, one is blocked by the config type validation:
https://github.com/saltstack/salt/blob/3ddd7eb6ffe8059e2f889031c67a4e2605da1a4d/salt/config/__init__.py#L697-L698

**Steps to Reproduce the behavior**
```yaml
# /etc/salt/master
reactor: /etc/salt/master.d/reactor.yaml
```

```yaml
# /etc/salt/master.d/reactor.yaml 
some/event:
  - react.to.some_event
```

**Expected behavior**
Load reactor mappings dynamically

**Screenshots**
```log
[salt.config      :1929][WARNING ][230228] Config option 'reactor' with value /etc/salt/master.d/reactor.yaml has an invalid type of str, a list is required for this option
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.29
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Nov  1 2022, 00:00:00)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 9.1 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-162.6.1.el9_1.0.1.x86_64
        system: Linux
       version: Rocky Linux 9.1 Blue Onyx
```
</details>

**Additional context**
https://github.com/saltstack/salt/issues/8098
https://github.com/saltstack/salt/issues/570
