### ISSUE TITLE
[BUG] Unable to execute salt-ssh commands on centos 8.5 master/minion in 3005.1

### ISSUE THREAD

**Issue by golmaal** [saltstack/salt#63619]
**Description**
I'm running this command from a CentOS 8.5 master/minion -
salt-ssh -ltrace --roster=scan 10.2.1.104 --user root --passwd password test.ping
but it gets stuck as following -
[14:37:04.324] [DEBUG   ] Performing shimmed, blocking command as follows:
test.ping
[14:37:04.333] [DEBUG   ] Executing command: ssh 10.2.1.104 -t -t -o KbdInteractiveAuthentication=no -o PasswordAuthentication=yes -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=root  mkdir -p
[14:37:04.343] [DEBUG   ] Child Forked! PID: 121238  STDOUT_FD: 14  STDERR_FD: 17
[14:37:04.343] [DEBUG   ] Terminal Command: ssh 10.2.1.104 -t -t -o KbdInteractiveAuthentication=no -o PasswordAuthentication=yes -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=root mkdir -p
root@10.2.1.104's ******:
The 10.2.1.104 has python3 installed on it.
The regular ssh connection from the salt master machine to 10.2.1.104 works fine.

**Versions Report**
```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.15.1
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: 1.0.6
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 21 2019, 19:31:34)
  python-gnupg: 0.5.0
        PyYAML: 3.12
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3

System Versions:
          dist: centos 8 Core
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-348.2.1.el8_5.x86_64
        system: Linux
       version: CentOS Linux 8 Core
```
