### ISSUE TITLE
[BUG] minion spams master with events if beacon is enabled and no corresponding windows service

### ISSUE THREAD

**Issue by rawmind** [saltstack/salt#63623]
**Description**

Reproduced on minion version 3004.2

Every minion produces about 3 events/s, So you can imagine what happened if you have X minions.

Master Reactor:
```
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:18.605094"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:18.672100"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:18.738106"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:19.602914"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:19.674663"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:19.742786"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:20.605267"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:20.670224"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:20.733939"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:21.605288"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:21.671390"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:21.740612"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:22.601883"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:22.668086"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:22.732635"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:23.602270"
}
salt/beacon/minion-dev/service/	{
    "_stamp": "2023-02-03T14:08:23.669026"
}
```

**Steps to Reproduce the behavior**

minion config:
```
id: minion-dev
master:
  - salt-master01

random_master: True
master_alive_interval: 30
retry_dns: 0
log_rotate_max_bytes: 5191680
log_rotate_backup_count: 5
log_level: warning
acceptance_wait_time_max: 1
acceptance.
rejected_retry: True
master_tries: -1
master_finger: '<key>'

beacons:
  service:
    - services:
        ThisServiceDoesntExist:
          onchangeonly: True
          delay: 5
    - disable_during_state_run: True
```

1. install salt master
2. install salt minion with config above
3. run `salt-key -a minion-dev` on master

minion log:
```
2023-02-03 14:08:14,932 [salt.beacons     :134 ][ERROR   ][2392] Unable to start service beacon, Failed To Open ThisServiceDoesntExist: The specified service does not exist as an installed service.
2023-02-03 14:08:15,932 [salt.beacons     :134 ][ERROR   ][2392] Unable to start service beacon, Failed To Open ThisServiceDoesntExist: The specified service does not exist as an installed service.
2023-02-03 14:08:16,932 [salt.beacons     :134 ][ERROR   ][2392] Unable to start service beacon, Failed To Open ThisServiceDoesntExist: The specified service does not exist as an installed service.
2023-02-03 14:08:17,932 [salt.beacons     :134 ][ERROR   ][2392] Unable to start service beacon, Failed To Open ThisServiceDoesntExist: The specified service does not exist as an installed service.
2023-02-03 14:08:18,932 [salt.beacons     :134 ][ERROR   ][2392] Unable to start service beacon, Failed To Open ThisServiceDoesntExist: The specified service does not exist as an installed service.
2023-02-03 14:08:19,932 [salt.beacons     :134 ][ERROR   ][2392] Unable to start service beacon, Failed To Open ThisServiceDoesntExist: The specified service does not exist as an installed service.
```

**Expected behavior**
minion shouldn't send events so frequently

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
          Salt: 3003.5
 
Dependency Versions:
          cffi: 1.15.0
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.7.2
       libgit2: 1.4.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.9.2
        Python: 3.7.15 (default, Oct 31 2022, 22:44:31)
  python-gnupg: 0.4.4
        PyYAML: 4.2
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: amzn 2 
        locale: UTF-8
       machine: x86_64
       release: 4.14.275-207.503.amzn2.x86_64
        system: Linux
       version: Amazon Linux 2
```
</details>

<details><summary>salt-minion.bat --versions-report</summary>

```yaml
C:\Program Files\Salt Project\Salt>salt-minion.bat  --versions-report
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: 3.1.18
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2012ServerR2
        system: Windows
       version: 2012ServerR2 6.3.9600 SP0 Multiprocessor Free

```
</details>
