### ISSUE TITLE
[BUG] libnacl missing on RHEL9 Minion 3005 onedir

### ISSUE THREAD

**Issue by Sxderp** [saltstack/salt#63657]
**Description**
The libnacl Python module is not included in the distributed package.

**Setup**
Install Salt.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (RedHat Virtualization)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
```bash
yum install salt-minion
salt-call nacl
'nacl' __virtual__ returned False: libnacl import error, perhaps missing python libnacl package or should update.
```

**Expected behavior**
The module to be available.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Nov  1 2022, 00:00:00)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rhel 9.1 Plow
        locale: utf-8
       machine: x86_64
       release: 5.14.0-162.6.1.el9_1.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 9.1 Plow
```
</details>
