### ISSUE TITLE
[BUG] file.managed utf-16 encoded file treated as binary

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#63651]
**Description**
Similar to https://github.com/saltstack/salt/issues/63650
file.managed with a utf-16-le encoded file is treated as a binary file, instead of text file.
Trying to use it as a template with Jinja values to be replaced by defaults does not work, the file is copied with the existing Jinja lines without doing any replacement, changined the encoding of the file to utf-8 works fine, but the file must be utf-16-le for the application to work.
The XML file trying to be managed is the export file from Windows Task Scheduler

**Setup**
Windows Minion 3004.2

**Steps to Reproduce the behavior**
```
get_xml:
  file.managed:
    - name: 'C:\task.xml'
    - source: salt://win_tasks/some_template.txt
    - template: jinja
    # - encoding: tried with utf16, utf16-le, utf-16-le # not sure what to use if anything works
    - defaults:
        TimeTrigger_StartBoundary: {{ TimeTrigger_StartBoundary }}
        TimeTrigger_StopBoundary: {{ TimeTrigger_StopBoundary }}  



some_template.txt (UTF-16LE encoded):
      <StartBoundary>{{ TimeTrigger_StartBoundary }}</StartBoundary>
      <EndBoundary>{{ TimeTrigger_StopBoundary }}</EndBoundary>
      <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>


minion-win-1:
----------
          ID: get_xml
    Function: file.managed
        Name: C:\task.xml
      Result: True
     Comment: File C:\task.xml updated
     Started: 17:39:38.661603
    Duration: 140.625 ms
     Changes:
              ----------
              diff:
                  Replace text file with binary file
```

**Expected behavior**
Treat the file as a text file or permit Jinja replacement on this type of file with a non utf-8 encoding.
