### ISSUE TITLE
[BUG] `dns_plugin_propagate_seconds` is missing from acme.cert

### ISSUE THREAD

**Issue by Lucianovici** [saltstack/salt#63700]
**Description**

`dns_plugin_propagate_seconds` is missing.

https://github.com/saltstack/salt/blob/master/salt/modules/acme.py#L115

It is present only in the docstrings.

**Setup**

**Steps to Reproduce the behaviour**

Run acme.cert with `dns_plugin_propagate_seconds` param.

**Expected behaviour**

No error, and use the right propagation value in seconds.

**Actual behaviour**

```
minion_id:
    ERROR executing 'state.apply': 'dns_plugin_propagate_seconds' is an invalid keyword argument for 'acme.cert'
```

**Versions Report**
```
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.16.0
        pygit2: 1.7.2
        Python: 3.8.10 (default, Nov 14 2022, 12:59:47)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3

System Versions:
          dist: ubuntu 20.04 Focal Fossa
        locale: utf-8
       machine: x86_64
       release: 5.4.0-105-generic
        system: Linux
       version: Ubuntu 20.04 Focal Fossa
```

```yaml
apps_letsencrypt_cert:
  acme.cert:
    - name: "whatever.example.com"
    - server: https://acme-v02.api.letsencrypt.org/directory
    - keysize: 4096
    - renew: 10
    - dns_plugin: cloudflare
    - dns_plugin_credentials: /path/to/my/auth.ini
    - dns_plugin_propagate_seconds: 60
```
</details>
