### ISSUE TITLE
[BUG] Confusing message: [CRITICAL] Pillar render error: Error encountered while rendering pillar top file.

### ISSUE THREAD

**Issue by andrii-suse** [saltstack/salt#63744]
**Description**
Encountered message below without any hit of where the problem is
```
[CRITICAL] Pillar render error: Error encountered while rendering pillar top file.
```

**Setup**

Create /srv/pillar/top.sls with following content:

```
{% set roles = salt['grains.get']('roles', []) %}

{{ saltenv }}:
  {% for role in roles %}
  'roles:{{ role }}':
    - match: grain
    - ignore_missing: True
    - role.{{ role }}
  {% endfor %}

```

Just having file above should be enough to reproduce the problem when `roles` is empty.

**Steps to Reproduce the behavior**

`salt-call --local grains.setval` will show the error if `roles` is not defined yet.

```
+ salt-call --local grains.setval roles '["mysql"]'
[CRITICAL] Pillar render error: Error encountered while rendering pillar top file.
```

Note that increasing logging level to `all` doesn't bring any usable info and second call doesn't display the error.
```
+ salt-call --local grains.get roles
local:
    - mysql
+ salt-call --local grains.setval roles '["mysql"]'
local:
    ----------
    roles:
        - mysql
  ```

**Expected behavior**
A hint what caused the error. Currently even log level `all` doesn't help with any hint where the problem could be.

**Versions Report**

```yaml
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.3.0
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 1.7.0
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: opensuse-leap 15.4 
        locale: UTF-8
       machine: x86_64
       release: 6.1.12-1-default
        system: Linux
       version: openSUSE Leap 15.4 
```
</details>

**Additional context**
My experiments reveal that salt doesn't like absence of `roles`.
If I wrap content of top.sls with following check - the error is not shown: 
```
{% if (salt['grains.has_value']('roles')) %}
```
Still, the message or increased logging level must provide more context where the problem is.
At least this report may be a good resource for those who see the message. (E.g. it is possible that #52284 was affected by this).
