### ISSUE TITLE
[BUG] Maintenance process leaking memory in 3005.1

### ISSUE THREAD

**Issue by denschub** [saltstack/salt#63747]
**Description**
This appears to be a regression in 3005.1, as I didn't see this before. The "maintenance" process grows relatively quickly, until it eventually gets OOM'ed.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (KVM)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging (via Archlinux repo)
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Nothing special. It's just a master running. Nothing of note in the logs either.

**Expected behavior**
n/a

**Screenshots**
<img width="664" alt="Screenshot 2023-02-21 at 03 06 21" src="https://user-images.githubusercontent.com/344777/220229655-07176293-c5d2-46dc-8b69-86183eb57696.png">

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.29
        Jinja2: 3.1.2
       libgit2: 1.5.0
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.12.0
        pygit2: 1.11.1
        Python: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 24.0.1
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: arch
        locale: utf-8
       machine: x86_64
       release: 6.1.12-1-lts
        system: Linux
       version: Arch Linux
```
</details>

**Additional context**
This appears to be a regression in 3005.1, but I can't 100% verify this right now :/

**Comment by denschub** [comment]
Might be related to #58791, but that one is so old, I felt like it's better to file a new one.

**Comment by OrangeDog** [comment]
More likely related to #62706.

**Comment by whytewolf** [comment]
I have not been able to replicate this. What settings are setup in the master?

**Comment by whytewolf** [comment]
here is a list of items in the maintenance process. that might help with knowing which settings to share.

1. aes key rotation. rotates the aes encryption every 24 hours
2. key_cache evaluation. creates a msgpack file with a list of accepted keys
3. git_pillar fetch. run a fetch remotes on git_pillar systems
4. scheduler, runs the master scheduler. 
5. presence, fires presence events. if presence events are setup. 

This is done on loop_interval.

**Comment by denschub** [comment]
So, there's a couple of things. I'm using `ext_pillar`, where one is a local git repo, and another one is actually a `cmd_json`. I also have three `gitfs_remotes`. It's ahrd to disable any of them because that effectively breaks everything -- but if you want me to disable something to check if the memory issue still happens, I can make that happen.

<details>
<summary>Full master config for reference</summary>

```yaml
default_include: master.d/*.conf
interface: '::'
ipv6: True
state_output: mixed

file_roots:
  base:
    - /srv/salt

fileserver_backend:
  - git
  - roots

gitfs_pubkey: '/root/.ssh/id_ed25519.pub'
gitfs_privkey: '/root/.ssh/id_ed25519'

gitfs_remotes:
  - file:///var/lib/gitolite/repositories/states.git
  - https://github.com/saltstack-formulas/openssh-formula.git
  - https://github.com/saltstack-formulas/sudoers-formula.git

ext_pillar:
  - git:
    - master file:///var/lib/gitolite/repositories/pillar.git
  - cmd_json: /etc/letsencrypt/tools/salty-letsencrypt-pillar %s

git_pillar_pubkey: '/root/.ssh/id_ed25519.pub'
git_pillar_privkey: '/root/.ssh/id_ed25519'

# /etc/salt/master.d/reactor.conf

reactor:
  - 'salt/fileserver/gitfs/update':
    - /srv/reactor/update_fileserver.sls
```
</details>
