### ISSUE TITLE
[BUG] Windows salt-minion update (winrepo definition) using pkg.installed returns False, retcode: 2

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#63767]
**Description**
Updating Windows Salt Minion using winrepo software definition with pkg.installed returns False, retcode 2
The scheduled task is launched and the salt-minion installation is completed succesfully but the state output shows error.

```yaml
update_salt:
  pkg.installed:
    - name: salt-minion-py3
    - version: "3003.5-1"
```

```
ID: update_salt
Function: pkg.installed
    Name: salt-minion-py3
  Result: False
 Comment: The following packages failed to install/update: salt-minion-py3=3003.5-1
 Started: 21:11:32.111568
Duration: 1187.513 ms
 Changes:
          ----------
          salt-minion-py3:
              ----------
              install status:
                  task started
```

```
# Event Bus
pkg.installed	{
    "__id__": "update_salt",
    "__run_num__": 1,
    "__sls__": "salt.minion-pkg_winrepo",
    "_stamp": "2023-02-23T21:11:33.353024",
    "changes": {
        "salt-minion-py3": {
            "install status": "task started"
        }
    },
    "comment": "The following packages failed to install/update: salt-minion-py3=3003.5-1",
    "duration": 1187.513,
    "name": "salt-minion-py3",
    "result": false,
    "retcode": 2,
    "start_time": "21:11:32.111568"
}
```

```
# salt win-lab1 test.version
win-lab1:
    3003.5
```

**Setup**
winrepo: https://raw.githubusercontent.com/saltstack/salt-winrepo-ng/master/salt-minion.sls

Updating from 3002.6 to 3003.5-1 but probably same problem with other versions.
