### ISSUE TITLE
[FEATURE REQUEST] Systemd services --global flag

### ISSUE THREAD

**Issue by DaAwesomeP** [saltstack/salt#63773]
**Is your feature request related to a problem? Please describe.**
It is not currently possible to globally enable Systemd user units. For example:
```bash
systemctl --global enable my-unit.service
```
These services are often installed to `/etc/systemd/user/` or `/usr/lib/systemd/user/` (or equivalent for various distros).

**Describe the solution you'd like**
Adding a `global`  flag to enabled and disabled for Systemd machines would be great:
```yaml
my_unit_enabled:
  service.enabled:
    - name:  my-unit.service
    - global: true
my_unit_disabled:
  service.disabled:
    - name:  my-unit.service
    - global: true
```
This flag should definitely be false by default.

**Describe alternatives you've considered**
While it would be possible to perform a hacky solution with `cmd.run`, this should really be simple.

**Additional context**
More info: https://wiki.archlinux.org/title/systemd/User
