### ISSUE TITLE
[BUG] Windows minion fails to fetch file from git backend

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#63772]
**Description**
WIndows minion using local file client configured with gitfs backend with gitpython module, fails to fetch files from when the gitfs_remotes has the option "root" options set.
The same configuration works fine on a Linux minion
```

# Minion git backend configuration, using "root" option in gitfs_remotes
PS C:\Users\adrian> Get-Content 'C:\ProgramData\Salt Project\Salt\conf\minion.d\git.conf'
gitfs_provider: gitpython
fileserver_backend:
  - gitfs
  - roots
gitfs_remotes:
  - https://amalaguti:REDACTED@github.com/amalaguti/DEMO.git:
    - base: main
    - name: github_salt_states
    - root: salt_states
    #- mountpoint: github

# The git repo files are listed properly
PS C:\Users\adrian> salt-call --local cp.list_master
local:
    - write.sls

# But files can't be fetched
PS C:\Users\adrian> salt-call --local state.sls write
local:
    Data failed to compile:
----------
    No matching sls found for 'write' in env 'base'

PS C:\Users\adrian> salt-call --local state.show_sls write
local:
    - No matching sls found for 'write' in env 'base'


# Tweaking the gitfs_remotes configuration removing the "root" option
PS C:\Users\adrian> Get-Content 'C:\ProgramData\Salt Project\Salt\conf\minion.d\git.conf'
gitfs_provider: gitpython
fileserver_backend:
  - gitfs
  - roots
gitfs_remotes:
  - https://amalaguti:REDACTED@github.com/amalaguti/DEMO.git:
    - base: main
    - name: github_salt_states
    #- root: salt_states
    #- mountpoint: github

# Initially files can't be found (due the removal of root option the path to files needs to be tweaked, next step)
PS C:\Users\adrian> salt-call --local state.show_sls write
local:
    - No matching sls found for 'write' in env 'base'

# The value used for root option is now part of the path
PS C:\Users\adrian> salt-call --local cp.list_master
local:
    - salt_states/write.sls

# Tweaking the path to include the root folder works fine but 
# it means that existing hardcoded (without the root value in the path)
# include, import and similar statements will fail to find the referenced file
PS C:\Users\adrian> salt-call --local state.show_sls salt_states.write
local:
    ----------
    touch-file:
        ----------
        file:
            |_
              ----------
              name:
                  C:\\EVIDENCE.txt
            - managed
            |_
              ----------
              order:
                  10000
        __sls__:
            salt_states.write
        __env__:
            base
```

**Setup**
salt-call 3004.2
Configuration as described above.
