### ISSUE TITLE
[BUG] `file.cached` state downloads file while `test` is `True`

### ISSUE THREAD

**Issue by gluf-technik** [saltstack/salt#63785]
**Description**
We got some states downloading releases/assets from github using `file.cached` like this example:
```
kvm-master:/srv/salt/states.git$ cat file_cached.sls 
/tmp/rustdesk-1.1.9.deb:
  file.cached:
    - name: https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb
    - source_hash: 135e357e175c8681592ada1cecbb528364d3a6cd9863db55c1d10908beebbf47
```
When I run this state via `state.sls` with `test=True` the file gets downloaded even though a state run
with `test=True` isn' t supposed to cause any changes.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

A bunch of KVM instances used for testing with different Linux distributions (Debian 11, CentOS 7, Ubuntu 22.04)
running Salt verion 3005.1 from the official repositories at repo.saltproject.io (thus the Debian based ones are onedir
installations, the CentOS ones are not). The master runs on a KVM instance, too, and also uses Debian 11.
The behavior is the same on all of them.

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Create a state file like the one above and make sure there's no such file on the minion already:
```
kvm-master:~# salt -C "$MINION" cmd.run 'find /var/cache/salt/minion/extrn_files/ -name rustdesk-1.1.9.deb -ls -exec rm -v {} \;'
deb11-kvm-minion:
         1754   6060 -rw-r--r--   1 root     root      6203088 Feb 28 12:36 /var/cache/salt/minion/extrn_files/base/github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb
    removed '/var/cache/salt/minion/extrn_files/base/github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb'
kvm-master:~#
```
Run the state with `test=True` and find the file being downloaded:
```
kvm-master:~# salt -C "$MINION" state.apply file_cached test=True
deb11-kvm-minion:
----------
          ID: /tmp/rustdesk-1.1.9.deb
    Function: file.cached
        Name: https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb
      Result: True
     Comment: File is already cached to /var/cache/salt/minion/extrn_files/base/github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb with hash 135e357e175c8681592ada1cecbb528364d3a6cd9863db55c1d10908beebbf47
     Started: 12:36:22.229664
    Duration: 488.005 ms
     Changes:   
              ----------
              hash:
                  ----------
                  new:
                      135e357e175c8681592ada1cecbb528364d3a6cd9863db55c1d10908beebbf47
                  old:
                      None

Summary for deb11-kvm-minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 488.005 ms
kvm-master:~# salt -C "$MINION" cmd.run 'find /var/cache/salt/minion/extrn_files/ -name rustdesk-1.1.9.deb -ls'
deb11-kvm-minion:
         1754   6060 -rw-r--r--   1 root     root      6203088 Feb 28 12:39 /var/cache/salt/minion/extrn_files/base/github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb
kvm-master:~#
```

**Expected behavior**
A state output telling me if the file is cached (and matching its checksum/`source_hash`?) or has not been downloaded as this is just a test.

**Screenshots**

**Versions Report**
<details><summary>`salt --versions-report`</summary>

```yaml
deb11-kvm-minion:                                                               
    Salt Version:    
              Salt: 3005.1
                      
    Dependency Versions:     
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed 
            Jinja2: 3.1.0
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2                   
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.9.16 (main, Jan  6 2023, 22:49:58)
      python-gnupg: 0.4.8
            PyYAML: 5.4.1
             PyZMQ: 23.2.0
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4
     
    System Versions:
              dist: debian 11 bullseye
            locale: utf-8
           machine: x86_64
           release: 5.10.0-21-amd64
            system: Linux
           version: Debian GNU/Linux 11 bullseye
     
kvm-master:
    Salt Version:
              Salt: 3005.1
     
    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.1.0
           libgit2: 1.5.0
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: 1.11.1
            Python: 3.9.16 (main, Jan  6 2023, 22:49:58)
      python-gnupg: 0.4.8
            PyYAML: 5.4.1
             PyZMQ: 23.2.0
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4
     
    System Versions:
              dist: debian 11 bullseye
            locale: utf-8
           machine: x86_64
           release: 5.10.0-21-amd64
            system: Linux
           version: Debian GNU/Linux 11 bullseye

centos7-kvm-minion:
    Salt Version:
              Salt: 3005.1
     
    Dependency Versions:
              cffi: Not Installed
          cherrypy: Not Installed
          dateutil: 2.4.2
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.1
           libgit2: Not Installed
          M2Crypto: 0.35.2
              Mako: Not Installed
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: Not Installed
          pycrypto: Not Installed
      pycryptodome: Not Installed
            pygit2: Not Installed
            Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
      python-gnupg: Not Installed
            PyYAML: 3.13
             PyZMQ: 18.0.1
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.1.4
     
    System Versions:
              dist: centos 7 Core
            locale: UTF-8
           machine: x86_64
           release: 3.10.0-1160.83.1.el7.x86_64
            system: Linux
           version: CentOS Linux 7 Core
```
</details>

**Additional context**
The original states are a little more involved as GitHub' s REST-API gets called first to get the URL for the asset for a given release/tag and stuff.

~Florian@gluf-technik
