### ISSUE TITLE
[BUG][3006][RC1] Unable to get rest_cherrypy to work in 3006rc1

### ISSUE THREAD

**Issue by PaulChristophel** [saltstack/salt#63815]
**Description**
Attempting to run commands via the salt-api using the rest_cherrypy netapi interface results in 400 errors. I was hoping this was just an issue in our test/dev environment, but I'm running into the same error using the docker images provided at hub.docker.com with no custom configs.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [X] container (Kubernetes, Docker, containerd, etc. please specify) - Docker
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
I am using the docker images provided here to test: https://hub.docker.com/r/saltstack/salt
I am not modifying the default containers in any way. I am simply running the example "start a salt image" on that page:

```bash
$ docker run --name salt --hostname salt -p 4505-4506:4505-4506 -p 8000:8000 -e SALT_SHARED_SECRET=mysecretpassword -d saltstack/salt
```

When I run the container with the "latest" tag and run the following commands:

```bash
TOKEN=$(curl -H "Accept: application/json" \
     -H "Content-Type: application/json" \
     -d '{"eauth": "sharedsecret", "username": "salt", "password": "mysecretpassword"}' \
     -k 'https://localhost:8000/login'| jq -r '.return[0].token')

curl -H "Accept: application/json" \
     -H "Content-Type: application/json" \
     -H "X-Auth-Token: $TOKEN" \
     -d '{"client": "local", "tgt": "*", "fun": "test.ping"}' \
     -k https://localhost:8000/run
```
I am able to authenticate successfully via the login command, and get a 401 Unauthorized error when attempting to run the test.ping (not great, but bear with me).

```html
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>No permission -- see authorization schemes</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 18.6.1</a>
      </span>
    </div>
    </body>
</html>
```

When I run the same exact commands using the rc tag, I am also able to authenticate successfully via the login command; however, I am getting a 400 Bad Request error for the test.ping.

```html
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>400 Bad Request</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>400 Bad Request</h2>
        <p>Bad request syntax or unsupported method</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 18.6.1</a>
      </span>
    </div>
    </body>
</html>
```

**Expected behavior**
I expected to get a 401 Unauthorized error. In my dev/test environment I expected to get 200, which led me down the path of submitting this issue.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
salt --versions-report
Salt Version:
          Salt: 3006.0rc1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: 1.1.0
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.6.1
        Python: 3.7.13 (default, Apr 20 2022, 03:16:50)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: alpine 3.14.6 
        locale: UTF-8
       machine: x86_64
       release: 5.15.49-linuxkit
        system: Linux
       version: Alpine Linux 3.14.6
```

</details>

**Additional context**
