### ISSUE TITLE
[BUG] cmd.run onlyif powershell

### ISSUE THREAD

**Issue by Selected6280** [saltstack/salt#63820]
**Description**
Can't get cmd.run working with onlyif and powershell.
As you can see in the screenshot, the exact same command is executed and returns a False, so it shouldn't have been executed in the first place.
I tried also with " instead of ' and completely without and adding powershell infront. But either it's always True or always False independent of the real status.
And it's also really hard to find examples for Windows at all.

**Expected behavior**
command should only be executed if onlyif is true.

**Screenshots**
![image](https://user-images.githubusercontent.com/124132746/223136019-0a6ebf4f-5299-4308-a7a6-605fbb299037.png)

**Versions Report**
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Nov 14 2022, 12:59:47)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-144-generic
        system: Linux
       version: Ubuntu 20.04 focal

```yaml
  DisableDefenderRTP:
    cmd.run:
      - name: '(Get-MpComputerStatus).RealTimeProtectionEnabled'
      - shell: powershell
      - onlyif: '(Get-MpComputerStatus).RealTimeProtectionEnabled'
```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
`onlyif` with a string is also only looking at the command's `retcode`, not parsing any output (same as `cmd.run`).
To get what you want, use the execution module:
```yaml
  DisableDefenderRTP:
    cmd.run:
      - name: '(Get-MpComputerStatus).RealTimeProtectionEnabled'
      - shell: powershell
      - onlyif: 
        - fun: cmd.powershell
          cmd: '(Get-MpComputerStatus).RealTimeProtectionEnabled'
```

**Comment by Selected6280** [comment]
Thank you! It's working.
I was not able to find an example how to do it.

**Comment by Selected6280** [comment]
Maybe my powershell check is to complex?

Running a normal cmd.run i get a correct retcode now using this
cmd.run:
  - name: powershell -Command "if ((Get-Service ANTIVIRUS) -and ((Get-MpComputerStatus).RealTimeProtectionEnabled) -and -not ((Get-MpComputerStatus).IsTamperProtected) -eq $true) { exit 0 } else { exit 1 }"

If I add same command to onlyif it's not getting the correct retcode:
      - onlyif:
        - fun: cmd.powershell
          cmd: if ((Get-Service CSFalconService) -and ((Get-MpComputerStatus).RealTimeProtectionEnabled) -and -not ((Get-MpComputerStatus).IsTamperProtected) -eq $true) { exit 0 } else { exit 1 }

Also tested with quotes and adding "powershell -command" upfront. doesn't change anything at all. even if i switch the exit codes around, doesn't seem to have any impact.

**Comment by OrangeDog** [comment]
It's the same problem as before:
`cmd.run` looks at the return code.
`cmd.powershell` looks at the output.

**Comment by Selected6280** [comment]
I'm stuck and frustrated :(

Running:
`sudo salt MINION cmd.powershell '(Get-Service ANTIVIRUS) -and ((Get-MpComputerStatus).RealTimeProtectionEnabled) -and -not ((Get-MpComputerStatus).IsTamperProtected)'` returns false

and

`sudo salt MINION cmd.powershell '(Get-Service ANTIVIRUS) -and -not ((Get-MpComputerStatus).RealTimeProtectionEnabled) -and -not ((Get-MpComputerStatus).IsTamperProtected)'` returns true

which would be correct. but using the same in onlyif with `fun: cmd.powershell` always executes the state.

![Image](https://github.com/user-attachments/assets/09218916-bff6-4208-adba-21092c283569)

![Image](https://github.com/user-attachments/assets/796bea1f-b31e-445a-97a0-b4d5df3daf7d)

I have no idea what output is necessary for onlyif and also don't find any example for this. Any help is appreciated.

**Comment by MaBauMeBad** [comment]
I can confirm also, this is no longer working.

```yaml
os-base-swap-windows_system-managed-disable:
  cmd.run:
    - name:  # Fancy shit here
    - shell: powershell
    - runas: SYSTEM
    - onlyif:
      - fun: cmd.powershell
        # cmd: (Get-WmiObject -Class Win32_ComputerSystem).AutomaticManagedPagefile
        cmd: "write-host2 false"
```

With this case, the condition will only prevent me to run this task, if i use a corrupt command on porpuse (to get a returncode 1).
The Get-WMI Command will always run the command, even when it is false.


Tried the following and everytime the task will be run.
- Did a Test case to return a specific return Code
- returned a bollean
- return exit code and bollean as strings (was desperate)
- return with $LASTExitCode
- Command in single and/or Double Quotes

My Setup:
- Windows 10 Minion with 3.6.15
- Master on openSUSE with salt-master-3006.0-150500.4.55.1.x86_64

Please feel free to request more information.

Thank you 👍
