### ISSUE TITLE
Option to enable KbdInteractiveAuthentication for salt-ssh

### ISSUE THREAD

**Issue by Reonaydo** [saltstack/salt#63825]
I have some servers where configured pam_google_authenticator.
It is required to set KbdInteractiveAuthentication=yes
But salt-ssh has it disabled hard in code.

I think if option enabling KbdInteractiveAuthentication for roster exists it will be great

**Comment by OrangeDog** [comment]
How are you planning to do the interaction, in a way that doesn't break Kerberos security?

**Comment by Reonaydo** [comment]
This user and pam_google_authenticator are configured witout 2FA. But pam_google_authenticator.so module in pam.d still requires KbdInteractiveAuthentication and reject without this.

**Comment by Akm0d** [comment]
To enable `KbdInteractiveAuthentication` for `salt-ssh`, you can use the existing functionality to pass custom SSH options. Salt-SSH provides two ways to configure SSH options: through the CLI with the `--ssh-option` flag or by setting `ssh_options` in the roster file.

#### 1. Using the `salt-ssh` CLI

You can enable `KbdInteractiveAuthentication` by using the `--ssh-option` flag, which allows you to pass custom SSH options directly when executing the `salt-ssh` command.

**Example Command:**

```bash
salt-ssh <target_host> state.apply test=true --ssh-option="KbdInteractiveAuthentication=yes"
```

This command will enable `KbdInteractiveAuthentication` for the specified `<target_host>`.

If you need to pass additional SSH options, you can use multiple `--ssh-option` flags. For example:

```bash
salt-ssh <target_host> state.apply test=true --ssh-option="KbdInteractiveAuthentication=yes" --ssh-option="PreferredAuthentications=keyboard-interactive,password"
```

#### 2. Setting `ssh_options` in the Roster File

If you prefer to configure this setting permanently for specific hosts, you can add the `ssh_options` parameter in the roster file. This allows you to specify SSH options for each target host individually.

**Example Roster Configuration:**

```yaml
my_server:
  host: 192.168.1.100
  user: myuser
  passwd: mypassword
  ssh_options:
    - "KbdInteractiveAuthentication=yes"
```

In this example:
- `my_server` is the target's Salt ID.
- `ssh_options` is a list of SSH options passed to the SSH client, enabling `KbdInteractiveAuthentication`.

You can also add multiple options to the `ssh_options` list, like this:

```yaml
my_server:
  host: 192.168.1.100
  user: myuser
  passwd: mypassword
  ssh_options:
    - "KbdInteractiveAuthentication=yes"
    - "PreferredAuthentications=keyboard-interactive,password"
```

#### Summary

You can enable `KbdInteractiveAuthentication` for `salt-ssh` using either of these methods:
- **CLI:** Use the `--ssh-option` flag to pass SSH options directly.
- **Roster File:** Configure `ssh_options` in the roster to set SSH options for individual hosts.

Both approaches will allow you to set `KbdInteractiveAuthentication` without any code changes.

Let me know if you have any further questions or if more details are needed!
