### ISSUE TITLE
[BUG] Install / Upgrade to 3006 RC 1 on Centosstream 8 showing issues

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#63821]
**Description**
Installing 3006 RC 1 on Centosstream 8 is showing issue on install due to HMAC part of the post-install script

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
yum install salt-minion

**Expected behavior**
Clean output with no warning or errors reported

**Screenshots**
```
[root@Unknown yum.repos.d]# yum install salt-minion
Last metadata expiration check: 0:03:51 ago on Mon 06 Mar 2023 11:32:22 AM MST.
Dependencies resolved.
===============================================================================================================================================================================================================================
 Package                                               Architecture                                     Version                                                   Repository                                              Size
===============================================================================================================================================================================================================================
Installing:
 salt-minion                                           x86_64                                           3006.0~rc1-0                                              salt-rc-repo                                            79 k
Installing dependencies:
 salt                                                  x86_64                                           3006.0~rc1-0                                              salt-rc-repo                                            54 M

Transaction Summary
===============================================================================================================================================================================================================================
Install  2 Packages

Total download size: 54 M
Installed size: 162 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): salt-minion-3006.0~rc1-0.x86_64.rpm                                                                                                                                                     142 kB/s |  79 kB     00:00    
(2/2): salt-3006.0~rc1-0.x86_64.rpm                                                                                                                                                            5.3 MB/s |  54 MB     00:10    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                          5.3 MB/s |  54 MB     00:10     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                                       1/1 
  Installing       : salt-3006.0~rc1-0.x86_64                                                                                                                                                                              1/2 
  Running scriptlet: salt-3006.0~rc1-0.x86_64                                                                                                                                                                              1/2 
  Installing       : salt-minion-3006.0~rc1-0.x86_64                                                                                                                                                                       2/2 
  Running scriptlet: salt-minion-3006.0~rc1-0.x86_64                                                                                                                                                                       2/2 
/var/tmp/rpm-tmp.964igm: line 16: /opt/saltstack/salt/run/.libssl.so.1.1.hmac: No such file or directory
/opt/saltstack/salt/run/libssl.so.1.1: No such file or directory
/opt/saltstack/salt/run/libcrypto.so.1.1: No such file or directory
/var/tmp/rpm-tmp.964igm: line 17: /opt/saltstack/salt/run/.libcrypto.so.1.1.hmac: No such file or directory

/sbin/ldconfig: /usr/lib64/llvm14/lib/libclang.so.13 is not a symbolic link


  Verifying        : salt-3006.0~rc1-0.x86_64                                                                                                                                                                              1/2 
  Verifying        : salt-minion-3006.0~rc1-0.x86_64                                                                                                                                                                       2/2 

Installed:
  salt-3006.0~rc1-0.x86_64                                                                                   salt-minion-3006.0~rc1-0.x86_64                                                                                  

Complete!
[root@Unknown yum.repos.d]# 
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
[root@Unknown yum.repos.d]# salt-call --local test.versions
local:
    Salt Version:
              Salt: 3006.0rc1
     
    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.1.2
           libgit2: Not Installed
      looseversion: 1.0.2
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 22.0
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.10.10 (main, Feb 23 2023, 05:21:34) [GCC 11.2.0]
      python-gnupg: 0.4.8
            PyYAML: 5.4.1
             PyZMQ: 23.2.0
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4
     
    System Versions:
              dist: centos 8 
            locale: utf-8
           machine: x86_64
           release: 4.18.0-448.el8.x86_64
            system: Linux
           version: CentOS Stream 8 

```
</details>

**Additional context**
