### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dmulyalin** [saltstack/salt#63824]
**Description**

Pillar fetch timeouts on proxy minion after ~60 seconds

**Setup**

SaltStack 3005.1

Master and Proxy Minion running in containers on RockyLinux VM in a VirtualBox

- [x] VM (Virtualbox, KVM, etc. please specify)
- [x] container (Kubernetes, Docker, containerd, etc. please specify)

**Steps to Reproduce the behavior**

Create external pillar and make it to sit doing nothing for longer then 60 seconds

**Expected behavior**

Being able to configure extrnal pillar timeout as a parameter.

**Versions Report**

<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
bash-4.4# salt --versions-report
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.17
        pygit2: Not Installed
        Python: 3.9.13 (main, Nov 16 2022, 15:31:39)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 20.0.0
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
Salt Extensions:
   salt-nornir: 0.19.0
 
System Versions:
          dist: rocky 8.5 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 4.18.0-425.3.1.el8.x86_64
        system: Linux
       version: Rocky Linux 8.5 Green Obsidian
```
</details>

**Additional context**

I created custom external pillar but it takes longer then 60 seconds to fetch data and while master is in the process of retrieving that data proxy minoion errors out with timeout error constantly sending another pillar refresh request to master.

Getting this traceback on proxy-minion:
```
salt-minion-3005-1  | 14:59:37,425 [salt.pillar                              ][ERROR   ] Exception getting pillar:
salt-minion-3005-1  | Traceback (most recent call last):
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/pillar/__init__.py", line 262, in compile_pillar
salt-minion-3005-1  |     ret_pillar = yield self.channel.crypted_transfer_decode_dictentry(
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1056, in run
salt-minion-3005-1  |     value = future.result()
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
salt-minion-3005-1  |     raise_exc_info(self._exc_info)
salt-minion-3005-1  |   File "<string>", line 4, in raise_exc_info
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1064, in run
salt-minion-3005-1  |     yielded = self.gen.throw(*exc_info)
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/channel/client.py", line 171, in crypted_transfer_decode_dictentry
salt-minion-3005-1  |     ret = yield self.transport.send(
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1056, in run
salt-minion-3005-1  |     value = future.result()
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
salt-minion-3005-1  |     raise_exc_info(self._exc_info)
salt-minion-3005-1  |   File "<string>", line 4, in raise_exc_info
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1064, in run
salt-minion-3005-1  |     yielded = self.gen.throw(*exc_info)
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/transport/zeromq.py", line 914, in send
salt-minion-3005-1  |     ret = yield self.message_client.send(load, timeout=timeout)
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1056, in run
salt-minion-3005-1  |     value = future.result()
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
salt-minion-3005-1  |     raise_exc_info(self._exc_info)
salt-minion-3005-1  |   File "<string>", line 4, in raise_exc_info
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1064, in run
salt-minion-3005-1  |     yielded = self.gen.throw(*exc_info)
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/transport/zeromq.py", line 624, in send
salt-minion-3005-1  |     recv = yield future
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1056, in run
salt-minion-3005-1  |     value = future.result()
salt-minion-3005-1  |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
salt-minion-3005-1  |     raise_exc_info(self._exc_info)
salt-minion-3005-1  |   File "<string>", line 4, in raise_exc_info
salt-minion-3005-1  | salt.exceptions.SaltReqTimeoutError: Message timed out
salt-minion-3005-1  | 14:59:37,432 [salt.minion                              ][ERROR   ] Error while bringing up minion for multi-master. Is master at salt-master responding?
```

Was trying to play with master and proxy minion timeout parameter by setting it to a big value as recommended [here](https://github.com/saltstack/salt/issues/46095) but that does not seems to have any effect. 

Looked at traceback and found [this call](https://github.com/saltstack/salt/blob/7cf39d89923e04796ccb4eba4a216d5f66b6e785/salt/transport/zeromq.py#L913) - it seems timeout value is hardcoded to 60 seconds here and I was not able to figure out the way to influence that value through proxy minon or master settings or command line parameters.

If pillar fetch timeout is not configurable at the moment, having a setting to control that timeout value would be a very useful feature to implement as a workaround for this bahviour.
