### ISSUE TITLE
[DOCS] states.service.running example does not match the documentation

### ISSUE THREAD

**Issue by joshmcorreia** [saltstack/salt#63852]
**Description**
At the top of the page there is the following example which indicates that there is a `reload` parameter:
```
redis:
  service.running:
    - enable: True
    - reload: True
    - watch:
      - pkg: redis
```

Further down the page in the `salt.states.service.running(name, enable=None, sig=None, init_delay=None, **kwargs)` section there is no mention of a `reload` parameter.

**Suggested Fix**
Make the example match the documentation, or add the missing parameter onto the documentation, whichever is correct.

**Type of documentation**
Salt documentation

**Location or format of documentation**
- https://docs.saltproject.io/en/latest/ref/states/all/salt.states.service.html#starting-or-restarting-of-services-and-daemons
- https://docs.saltproject.io/en/latest/ref/states/all/salt.states.service.html#salt.states.service.running
