### ISSUE TITLE
[BUG] cp.cache_file for file:///path is doing nothing

### ISSUE THREAD

**Issue by kiemlicz** [saltstack/salt#63889]
**Description**
When invoking `salt minion cp.cache_file file:///etc/salt/something` the absolute path is returned and nothing is copied to minion

**Setup**
```
file_recv: True
file_roots:
  base:
    - /srv/salt/base
  dev:
    - /srv/salt/dev
    - /srv/salt/base
  server:
    - /srv/salt/server
    - /srv/salt/dev
    - /srv/salt/base
```

salt.fileclient.Client.get_url method from `fileclient.py`
```
...
        if url_scheme in ("file", ""):
            # Local filesystem
            if not os.path.isabs(url_path):
                raise CommandExecutionError(
                    "Path '{}' is not absolute".format(url_path)
                )
            if dest is None:
                with salt.utils.files.fopen(url_path, "rb") as fp_:
                    data = fp_.read()
                return data
            return url_path

        if url_scheme == "salt":
            result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)   # <------------ aren't u missing this in file ?
            if result and dest is None:
                with salt.utils.files.fopen(result, "rb") as fp_:
                    data = fp_.read()
                return data
            return result
...
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
run command from description

**Expected behavior**
file:///specified/here copied to minion

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: 5.0.3
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 3.0.3
       libgit2: 1.3.0
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.17
        pygit2: 1.7.2
        Python: 3.8.10 (default, Nov 14 2022, 12:59:47)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 6.0.0-0.deb11.6-amd64
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>
