### ISSUE TITLE
[3006][RC1][BUG] salt -V , a deprecation warning is shown.

### ISSUE THREAD

**Issue by network-shark** [saltstack/salt#63904]
**Description**

Updated my master to 3006rc1 and got this version report. 

Looks like #50792 
```yaml
root@salt:~/venv/salt3006rc1/bin# ./salt -V
/root/venv/salt3006rc1/lib/python3.9/site-packages/salt/version.py:762: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  lin_ver = linux_distribution()
/root/venv/salt3006rc1/lib/python3.9/site-packages/salt/version.py:826: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  ("dist", " ".join(linux_distribution(full_distribution_name=False))),
Salt Version:
          Salt: 3006.0rc1

Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: 1.5.0
  looseversion: 1.1.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.5
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.17
        pygit2: 1.11.1
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 25.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: aarch64
       release: 5.10.103-v8+
        system: Linux
       version: Debian GNU/Linux 11 bullseye


```
