### ISSUE TITLE
[BUG] saltclass node pillar does not override classes pillar dict

### ISSUE THREAD

**Issue by mtessmer1** [saltstack/salt#63933]
**Description**

I started using saltclass for tops and pillars and I am not sure, how the merging of pillar data works (especially dict merging).

**Setup**
I used a minion test installation (KVM, Debian 11) and a FreeBSD machine for master with a test class and a test node.

**Steps to Reproduce the behavior**

Class definition (`saltclass1`):

```
pillars:
  dict1:
    element: value from class
```

Node definition:

```
classses:
  - saltclass1
pillars:
  dict1:
    element: value from node
```

**Expected behavior**

After updating pillars with `salt 'node' saltutil.refresh_pillar` I expected that node pillar data overrides classes pillar data, like:

```bash
salt 'saltclass*' pillar.items

node:
    ----------
    __saltclass__:
        ----------
        classes:
            - saltclass1
        environment:
            base
        nodename:
            node
        states:
    dict1:
        ----------
        element:
            value from node
```

What I got instead is:

```bash
salt 'saltclass*' pillar.items

node:
    ----------
    __saltclass__:
        ----------
        classes:
            - saltclass1
        environment:
            base
        nodename:
            node
        states:
    dict1:
        ----------
        element:
            value from class    <--- not overriden from node value
```

**Versions Report**
For master: 

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: Not Installed
        Python: 3.9.15 (main, Nov 17 2022, 01:10:49)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: freebsd 13.1 
        locale: utf-8
       machine: amd64
       release: 13.1-RELEASE-p3
        system: FreeBSD
       version: FreeBSD 13.1 
```

Minion is 3002 (Debian package).

**Additional context**

The original reclass comment that is not very precise how the merging is done: "After all classes (and the classes they reference) have been visited, **reclass** finally merges the applications list and parameters defined for the node into what has been accumulated during the processing of the classes, and returns the final result."

Thanks
Meik
