### ISSUE TITLE
Missing python-croniter in 3005.1 onedir/Tiamat install [BUG]

### ISSUE THREAD

**Issue by edlitmus** [saltstack/salt#63954]
**Description**

Missing python-croniter in 3005.1 onedir/Tiamat install results in states using `schedule.present` failing to run with only error messages in the minion logs:

```shell
2023-03-24 18:57:36,498 [salt.utils.schedule:1149][ERROR   ][11916] Missing python-croniter. Ignoring job date_cron.
2023-03-24 18:57:36,498 [salt.utils.schedule:1149][ERROR   ][11916] Missing python-croniter. Ignoring job script_cron.
```

**Setup**

Master and minion are both running on AWS EC2 instances, using Ububtu 20.04 minimal base AMIs.
All instances bootstrap and highstate correctly.

**Steps to Reproduce the behavior**

The minion has these two test states:

```yaml
add_date_cron:
  schedule.present:
    - name: date_cron
    - function: cmd.run
    - job_args:
      - name: date > /tmp/date.txt
      - creates:
        - /tmp/date.txt
    - cron: '* * * * *'

add_script_cron:
  schedule.present:
    - name: script_cron
    - function: cmd.script
    - job_args:
      - salt://{{ slspath }}/files/test.sh
    - cron: '* * * * *'
```

The script in the second state contains this:

```shell
#!/usr/bin/env bash

echo $(date +%s) > /tmp/timestamp.txt

exit
```

**Expected behavior**

The test states should run and create files in `/tmp/` with the date and a timestamp respectively.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
# salt --versions-report
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Jan  6 2023, 22:49:56)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1031-aws
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**

The master and minion are running identical versions. There are no errors when highstating, the states run but the jobs fail to execute.

**Comment by edlitmus** [comment]
My mistake, I always assumed that `croniter` was installed as a dependency, as it's always 'just worked'.

**Comment by Adam-Zvolanek** [comment]
I am currently getting a very similar error where croniter is not able to schedule the jobs I have specified. It is not until I restart the salt-minion that it recognizes croniter's installation however the state I have written doesn't seem to be restarting the salt-minion to do so. Is there a more proper way to both install and restart the salt-minion to allow croniter be present on first highstate?

```yaml
croniter_install:
  pip.installed:
    - name: croniter
    - upgrade: True

  cmd.run:
    - name: "salt-call service.restart salt-minion"
    - bg: True
    - onchanges:
      - pip: croniter
    - order: last
```
