### ISSUE TITLE
[BUG] performance - aptpkg.latest_version calls apt-cache for every pkg

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#63982]
**Description**
The `pkg.latest` state calls the `pkg.latest_version` execution module during the course of operation. When it does that, all `pkgs` are passed to the `pkg.latest_version` module at once. However, on Debian machines, the `aptpkg.latest_version` module which accepts the package list performs a call to `apt-cache policy` on the command line _for every package_.

**Steps to Reproduce the behavior**

```bash
# create a list of all installed packages
dpkg -l | grep ^ii | awk '{print $2}' > all_pkgs

# note that the package list is large
wc -l all_pkgs
415 all_pkgs

# time the operation
time salt-call pkg.latest_version $(paste -sd" " all_pkgs)
...
real    0m9.154s
user    0m6.935s
sys     0m2.196s
```

**Expected behavior**
The `apt-cache policy` call can accept the entire package list at once, then the output can be parsed as a whole.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.0+0na.6c81943
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.0
     pycparser: 2.21
      pycrypto: 2.6.1
  pycryptodome: 3.17
        pygit2: Not Installed
        Python: 3.7.3 (default, Oct 31 2022, 14:04:00)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-23-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>
