### ISSUE TITLE
[BUG] success_stdout not being recognized

### ISSUE THREAD

**Issue by Adam-Zvolanek** [saltstack/salt#64011]
**Description**
I am attempting to use cmd.run with `success_stdout` to verify versions of installed items, notably in this example using k9s. Where I am trying to check what version of k9s are installed, and onfail of matching the specified version, install k9s.

**Setup**
```yaml
check_k9s_install:
  cmd.run:
    - name: /usr/local/bin/k9s version | grep Version | awk '{print $2}'
    - success_stdout: 
        - v0.27.3

download_k9s:
  archive.extracted:
    - name: /tmp/k9s_dir
    - source: https://github.com/derailed/k9s/releases/download/v0.27.3/k9s_Linux_amd64.tar.gz
    - skip_verify: True
    - enforce_toplevel: False
    - makedirs: True
    - user: {{ uid | yaml_encode }}
    - group: {{ group }}
    - onfail:
        - cmd: check_k9s_install
```

Please be as specific as possible and give set-up details.

- [X] onedir packaging

**Steps to Reproduce the behavior**

Include `success_stdout` as a method for `onfail` for a later state. Using `salt-call --local state.apply` to test on my salt-minion Amazon Linux 2 machine.

**Expected behavior**

I expect when `/usr/local/bin/k9s` does not exist, the error below to cause the `check_k9s_install` state to fail and trigger the remaining states.

```bash
stderr:
   /bin/bash: /usr/local/bin/k9s: No such file or directory
```

**Screenshots**

With k9s installed:

```bash
local:
----------
          ID: check_k9s_install
    Function: cmd.run
        Name: /usr/local/bin/k9s version | grep Version | awk '{print $2}'
      Result: True
     Comment: Command "/usr/local/bin/k9s version | grep Version | awk '{print $2}'" run
     Started: 09:38:40.871266
    Duration: 55.73 ms
     Changes:   
              ----------
              pid:
                  11421
              retcode:
                  0
              stderr:
              stdout:
                  v0.27.3
----------
          ID: download_k9s
    Function: archive.extracted
        Name: /tmp/k9s_dir
      Result: True
     Comment: All files in archive are already present
     Started: 09:38:40.935845
    Duration: 1129.084 ms
     Changes:   
```

With k9s not installed:

```bash
local:
----------
          ID: check_k9s_install
    Function: cmd.run
        Name: /usr/local/bin/k9s version | grep Version | awk '{print $2}'
      Result: True
     Comment: Command "/usr/local/bin/k9s version | grep Version | awk '{print $2}'" run
     Started: 10:08:30.733419
    Duration: 27.532 ms
     Changes:   
              ----------
              pid:
                  31575
              retcode:
                  0
              stderr:
                  /bin/bash: /usr/local/bin/k9s: No such file or directory
              stdout:
----------
          ID: download_k9s
    Function: archive.extracted
        Name: /tmp/k9s_dir
      Result: True
     Comment: State was not run because onfail req did not change
     Started: 10:08:30.770761
    Duration: 0.008 ms
     Changes:   
```

**Versions Report**

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Jan  6 2023, 22:54:07)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: amzn 2 Karoo
        locale: utf-8
       machine: x86_64
       release: 5.15.102-61.139.amzn2.x86_64
        system: Linux
       version: Amazon Linux 2 Karoo
```
</details>

**Comment by whytewolf** [comment]
so, the issue is your command returns retcode 0 even when the command doesn't exist.

```
root@salt00:~#  /usr/local/bin/k9s version | grep Version | awk '{print $2}'
-bash: /usr/local/bin/k9s: No such file or directory
root@salt00:~#  echo $?
0
```

the only thing `success_stdout`  does is overwrite the retcode to 0 when the string exists. and it says as much in the documentation for it. all cmd.run is doing is looking for retcode 0 in the return to see if it passed or not. success_stdout does not change a 0 to anything else making a fail state. it also has no logic for a fail or pass. just is item in output, then set retcode 0? but your retcode is always 0 to begin with. 


here is 2 tests. showing this is how it is supposed to work.

test1 
```yaml
root@salt00:~# cat /srv/salt/tests/cmd.sls
test run:
  cmd.run:
    - name: /root/test.sh
    - success_stdout:
      - thing

testnop:
  test.nop:
    - name: fail
    - onfail:
      - cmd: test run
```

test1 output
```
local:
----------
          ID: test run
    Function: cmd.run
        Name: /root/test.sh
      Result: False
     Comment: Command "/root/test.sh" run
     Started: 23:33:27.149179
    Duration: 9.009 ms
     Changes:
              ----------
              pid:
                  547642
              retcode:
                  1
              stderr:
              stdout:
                  this is a test
----------
          ID: testnop
    Function: test.nop
        Name: fail
      Result: True
     Comment: Success!
     Started: 23:33:27.160359
    Duration: 1.424 ms
     Changes:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
Total run time:  10.433 ms
```

test2
```yaml
test run:
  cmd.run:
    - name: /root/test.sh
    - success_stdout:
      - test

testnop:
  test.nop:
    - name: fail
    - onfail:
      - cmd: test run
```

```
local:
----------
          ID: test run
    Function: cmd.run
        Name: /root/test.sh
      Result: True
     Comment: Command "/root/test.sh" run
     Started: 23:36:54.162597
    Duration: 8.208 ms
     Changes:
              ----------
              pid:
                  547814
              retcode:
                  0
              stderr:
              stdout:
                  this is a test
----------
          ID: testnop
    Function: test.nop
        Name: fail
      Result: True
     Comment: State was not run because onfail req did not change
     Started: 23:36:54.172930
    Duration: 0.007 ms
     Changes:

Summary for local
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time:   8.215 ms
```

with how this is supposed to work. try this instead. if the command doesn't run it will return 127 retcode and not have the string. if the output has the value anywhere than even if the command does return it will list retcode 0 and pass. and if the command passes on it's own retcode 0 it will pass.

```yaml
check_k9s_install:
  cmd.run:
    - name: /usr/local/bin/k9s version
    - success_stdout: 
        - v0.27.3

download_k9s:
  archive.extracted:
    - name: /tmp/k9s_dir
    - source: https://github.com/derailed/k9s/releases/download/v0.27.3/k9s_Linux_amd64.tar.gz
    - skip_verify: True
    - enforce_toplevel: False
    - makedirs: True
    - user: {{ uid | yaml_encode }}
    - group: {{ group }}
    - onfail:
        - cmd: check_k9s_install
```
