### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JoeLoco** [saltstack/salt#64035]
**Description**
The **rotate_aes_key** config is not verified in main maintenance method 
I have a scenario with 15k minions, every day this is causing a spike of minions authentication and as consequence a lot of command failures at this moment. 

[click here](https://github.com/saltstack/salt/blob/64fd0cdcb2f9af205dab381df97b9ca79ef2e95c/salt/master.py#L235)

**Setup**
master config:

rotate_aes_key: False

**Steps to Reproduce the behavior**
Just use the configuration above

**Expected behavior**
Do not rotate AES key when the configuration is equals False

**Screenshots**
None

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
           Salt: 2019.2.8

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.2
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Jun 29 2022, 11:45:57)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.4.0-1063-aws
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

**Additional context**
None.
