### ISSUE TITLE
Default attributes for file/directory resources per state file

### ISSUE THREAD

**Issue by gwar9999** [saltstack/salt#6405]
Add a default file/file.directory feature that each file resource derives from, eg.

```
# defaults apply to all file resources unless overridden individually
file.defaults:
  - user: root
  - group: foo
  - mode: 770
  - managed

# defaults apply to each directory resource (even those created implicitly by a file resource) unless overridden individually
file.directory.defaults:
  - user: root
  - group: foo
  - mode 755
  - managed
```

```
/var/foo:
  file:
    - mode: 550

/var/bar:
  file:
    - absent

/etc/foo:
   file:
     - user: mail

/etc/foobar/tmp:
   file.directory:

/etc/foobar/tmp/filename:
   file:
     - group: exim

/opt/foo/bar/path/filename:
   file:
```

In the last example, the filename would be created with root:foo:770 but the directories implicitly created (presumably /opt/foo, /opt/foo/bar, /opt/foo/bar/path) would be created with root:foo:755.
