### ISSUE TITLE
[BUG] Vault SDB driver overwrites whole secret

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#64096]
**Description**
When calling `sdb.set` (or `sdb.get_or_set_hash` when writing) with the Vault SDB driver, there is no way to only update a single secret key.

**Setup**
- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [x] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

* Existing Vault setup
* Existing Vault secret at some path, e.g. `salt/minions/myminion`
```json
{
    "existing": "whatever",
    "important": "data"
}
```
* Vault SDB config
```
sdbvault:
  driver: vault
```

**Steps to Reproduce the behavior**
* `salt-call sdb.set sdb://sdbvault/salt/minions/myminion/new "val"`
* `salt-call vault.read_secret salt/minions/myminion`

**Expected behavior**
```yaml
existing: whatever
important: data
new: val
```

**Screenshots**
```yaml
new: val
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.29
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Nov  1 2022, 00:00:00)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 9.1 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-162.12.1.el9_1.0.1.x86_64
        system: Linux
       version: Rocky Linux 9.1 Blue Onyx
```
</details>
