### ISSUE TITLE
[BUG]Onedir salt_proxy module incorrectly checks for running salt-proxy instances

### ISSUE THREAD

**Issue by rdswett** [saltstack/salt#64100]
**Description**
The salt_proxy module includes a function to check if a proxy process is already running ( _is_proxy_running). This function looks for a process running that includes "salt-proxy" and a passed in proxy-id. When using a onedir version of salt, that check is always going to return false, as onedir versions use a newer syntax where the call to /usr/bin/salt-proxy results in a process that looks like "/opt/saltstack/salt/run/run proxy --proxyid=<id>". If a user defines a state that includes salt_proxy.configure_proxy, then salt will keep starting proxy processes until the host runs out of memory. 

**Setup**
- [X] on-prem machine
- [X] VM (KVM)
- [X] onedir packaging

**Steps to Reproduce the behavior**
Assuming a proxy pillar and module have already been defined and configured: 
Define a state that uses salt_proxy_configure_proxy, ie:

```
salt_proxy.configure_proxy:
  - proxy_name: <some host>
  - start: True

```

Then apply that state on some minion a few times.

**Expected behavior**
On first run, a proxy should have started on the minion. On every subsequent run, the first proxy process should be detected and another process should **not** start

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
local:
    Salt Version:
              Salt: 3005.1
     
    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.1.0
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.9.16 (main, Nov  1 2022, 00:00:00)
      python-gnupg: 0.4.8
            PyYAML: 5.4.1
             PyZMQ: 23.2.0
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4
     
    System Versions:
              dist: rocky 9.1 Blue Onyx
            locale: utf-8
           machine: x86_64
           release: 5.14.0-162.18.1.el9_1.x86_64
            system: Linux
           version: Rocky Linux 9.1 Blue Onyx
```
</details>

**Additional context**
None
