### ISSUE TITLE
[BUG]  got multiple values for keyword argument 'saltenv'

### ISSUE THREAD

**Issue by nvmdd** [saltstack/salt#64118]
**Description**
Getting error TypeError: salt.loaded.int.module.cp.cache_file() got multiple values for keyword argument 'saltenv'
when trying to install an rpm from an outside source using pkgs.installed state.

**Setup**
master and minion both are Rocky 9 on 3006.0

SLS:
```
pg_repository:
  pkg.installed:
    - sources:
      - pgdg-redhat-repo: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
```

Getting error:
----------
          ID: pg_repository
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2385, in call
                  ret = self.states[cdata["full"]](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1280, in wrapper
                  return f(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 1701, in installed
                  result = _find_install_targets(
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 762, in _find_install_targets
                  cached_path = __salt__["cp.cache_file"](
              TypeError: salt.loaded.int.module.cp.cache_file() got multiple values for keyword argument 'saltenv'

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Try to install package from outside source.

**Versions Report**
Salt Version:
          Salt: 3006.0

Python Version:
        Python: 3.10.11 (main, Apr 14 2023, 05:57:16) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.11.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 9.1 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-162.23.1.el9_1.x86_64
        system: Linux
       version: Rocky Linux 9.1 Blue Onyx

</details>

**Additional context**
I also get the same issue with local files like:
```
pgdg-redhat-repo:
  pkg.installed:
    - enable: True
    - sources:
      - pgdg-redhat-repo: salt:///test/pgdg-redhat-repo-latest.noarch.rpm
```

**Comment by OrangeDog** [comment]
Is this an upgrade from an older salt version?
Have you got any custom modules configured or synced?

**Comment by nvmdd** [comment]
I was on salt 3005.1 previously and it worked fine before the upgrade to 3006.
I do have custom modules also.

**Comment by nvmdd** [comment]
Likely related to this? 
https://github.com/saltstack/salt/pull/64110

**Comment by DaAwesomeP** [comment]
Accidentally opened duplicate #64157.

Same issue on Debian 11 amd64 with the following config:
```yaml
mystate:
  pkg.installed:
    - sources:
      - libmypkg1: 'salt:/path/to/libmypkg1_0.1.0-1_amd64.deb'
      - mypkg: 'salt://path/to/mypkg_0.1.0-1_amd64.deb'
```

**Comment by Adam-Zvolanek** [comment]
Same issue running Ubuntu 22.

```yaml
# Install of DrawIO

install_drawio:
  pkg.installed:
     - name: draw.io
     - sources:
       - draw.io: <Location>*.rpm
     - user: ...
     - group: ...
```
