### ISSUE TITLE
[BUG] setup.py does not work with --salt-config-dir and --salt-cache-dir arguments

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#64114]
**Description**
Running `setup.py` with the args `--salt-config-dir` and `--salt-cache-dir` is not working. An `unrecognized arguments` error is returned.

**Steps to Reproduce the behavior**

```
(heist-3.8)  ch3ll@megan-precision5550  ~/git/salt  ➦ 179532f902 <B>  GENERATE_SALT_SYSPATHS=True python setup.py --salt-config-dir=/etc/salt --salt-cache-dir=/var/cache/salt develop             
usage: setup.py [-h] [--next-release] ...
setup.py: error: unrecognized arguments: --salt-config-dir=/etc/salt --salt-cache-dir=/var/cache/salt
```

**Expected behavior**
Runs without error and builds.

**Versions Report**

```yaml
(heist-3.8)  ch3ll@megan-precision5550  ~/git/salt  ➦ 179532f902 <B>  salt --versions
Salt Version:
          Salt: 3006.0+6.g179532f902
 
Python Version:
        Python: 3.8.16 (default, Feb  8 2023, 08:44:06)
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.1.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.5
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.17
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 25.0.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: manjaro 22.0.4 Sikaris
        locale: utf-8
       machine: x86_64
       release: 6.1.12-1-MANJARO
        system: Linux
       version: Manjaro Linux 22.0.4 Sikaris
```
</details>
