### ISSUE TITLE
[BUG] Rendering SLS failed: could not find expected ':' with Vault multi-line secrets

### ISSUE THREAD

**Issue by shubb30** [saltstack/salt#64125]
**Description**
Salt is not able to add Hashicorp Vault secrets by key if the secret value is a multi-line secret.

**Setup**
I have Vault configured in Salt, with the proper policies to allow the minion to access its secrets

**Steps to Reproduce the behavior**
I have the following secret in Vault that the minion has access to read

```
$ sudo salt <NODE> vault.read_secret salt/nodes/<NODE>/test1
<NODE>:
    ----------
    key1:
        value1
    key2:
        value2
    multi_line:
        this a multiline
        secret value
```

I have a state that has the entire secret and just one of the single-line values, then the state works fine.

```
{% set vault_secret = salt['vault'].read_secret("salt/nodes/<NODE>/test1") %}

/test/vault-test-all:
  file.managed:
    - user: root
    - group: root
    - mode: 644
    - contents: |
        {{ vault_secret }}

/test/vault-test-single-line:
  file.managed:
    - user: root
    - group: root
    - mode: 644
    - contents: |
        {{ vault_secret['key1'] }}
```

The files on the minion:

```
$ cat /test/vault-test-all
{'key1': 'value1', 'key2': 'value2', 'multi_line': 'this a multiline\nsecret value'}

$ cat /test/vault-test-single-line
value1
```

But if I add the key for the multi-line secret

```
/test/vault-multi-line:
  file.managed:
    - user: root
    - group: root
    - mode: 644
    - contents: |
        {{ vault_secret['multi_line'] }}
```

Then Salt returns an error that it can't find an expected ':'

```
<NODE>:
    Data failed to compile:
----------
    Rendering SLS 'base:vault.vault-test' failed: could not find expected ':'

```

**Expected behavior**
Salt should be able to write the multi-line secret.

**Versions Report**

```
$ salt --versions-report
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Jan  6 2023, 22:50:07)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-56-generic
        system: Linux
       version: Ubuntu 22.04 jammy
```

**Comment by lkubb** [comment]
That's a YAML parse error because your final sls file will look like this:

```yaml
/test/vault-multi-line:
  file.managed:
    - user: root
    - group: root
    - mode: 644
    - contents: |
        this a multiline
secret value
```

Fix it by encoding the result in json (subspec of yaml):

```yaml
/test/vault-multi-line:
  file.managed:
    - user: root
    - group: root
    - mode: 644
    - contents: {{ vault_secret['key1'] | json }}
```
