### ISSUE TITLE
[BUG] state_queue doesn't allow int

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#64122]
**Description**
Functionality to allow integer values in `state_queue` was introduced in 3006.0, but type checking seems to have been missed to allow it fully.

```
[WARNING ] Config option 'state_queue' with value 2 has an invalid type of int, a bool is required for this option
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.0+0na.da6403b
 
Python Version:
        Python: 3.7.3 (default, Oct 31 2022, 14:04:00)
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.5
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: 2.6.1
  pycryptodome: 3.17
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 25.0.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10.13 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-23-amd64
        system: Linux
       version: Debian GNU/Linux 10.13 buster
```
</details>

**Additional context**
Originally implemented in #63357
