### ISSUE TITLE
[BUG] salt-minion 3006.0 fails to get secret from HashiCorp Vault

### ISSUE THREAD

**Issue by thrashwerk** [saltstack/salt#64128]
**Description**
salt-minion 3006.0 can no longer retrieve secrets from HashiCorp Vault.

Old minions upgraded from 3005.1 and new servers without prior Salt installations experience the same problem on 3006.0.

**Setup**
Salt master Vault config `/etc/salt/master.d/vault.conf`
```yaml
vault:
  url: https://vault.REDACTED:8200
  auth:
    uses: 30
    method: token
    token: REDACTED
  policies:
    - saltstack/minions
```

- [X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Running `vault.read_secret` module from the Salt master on a minion fails with an error `ERROR: Failed to read secret! KeyError: 'vault'`
```bash
root@salt-master ~ # salt 'scrap-k8s-node115' vault.read_secret salt/services/scrap-k8s
scrap-k8s-node115:
    ERROR: Failed to read secret! KeyError: 'vault'
ERROR: Minions returned with non-zero exit code
```

**Expected behavior**
`vault.read_secret` returns the key-value pairs from Vault
```bash
root@salt-master ~ # salt 'scrap-k8s-node114' vault.read_secret salt/services/scrap-k8s
scrap-k8s-node114:
    ----------
    rke2_backup_s3_access_key:
        REDACTED
```

**Versions Report**
<details><summary>salt --versions-report</summary>

Salt master is Debian 11.
Minions are either Debian 11 or Ubuntu 22.04, both OS' experience the same problem.

```yaml
Salt Version:
          Salt: 3006.0
 
Python Version:
        Python: 3.10.11 (main, Apr 14 2023, 05:57:16) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.31
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.11.2
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>
