### ISSUE TITLE
[BUG][3006.0] Missing salt-archive-keyring.gpg on repo.saltproject.io

### ISSUE THREAD

**Issue by bensteinberg** [saltstack/salt#64133]
**Description**

I can't use salt-cloud to spin up a new Debian bullseye EC2 instance; `install_debian_onedir_deps()` fails because `https://repo.saltproject.io/salt/py3/debian/11/amd64/latest/salt-archive-keyring.gpg` is not present.

**Setup**

The salt master is an EC2 instance; it and its minions use onedir packaging. The cloud profile in question uses the current Debian AMI for bullseye on amd64 in us-east-1, `ami-0fec2c2e2017f4e7b`.

**Steps to Reproduce the behavior**

When I run
```
sudo salt-cloud -l debug --out=json -p my_ec2_profile my-new-minion
```
the bootstrap process fails with
```
[DEBUG   ]  * ERROR: https://repo.saltproject.io/salt/py3/debian/11/amd64/latest/salt-archive-keyring.gpg failed to download to /tmp/salt-gpg-4VCcseAA.pub
 * ERROR: Failed to run install_debian_onedir_deps()!!!
 ```

**Expected behavior**

Until a week or so ago, the previous command would result in a new minion, `my-new-minion`, running Debian bullseye.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.27
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Jan  6 2023, 22:49:58)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-21-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**

I see that https://repo.saltproject.io/salt/py3/debian/11/amd64/3005/salt-archive-keyring.gpg is present (`3005` instead of `latest`), but I haven't figured out how to tell the bootstrap script to use that keyring URL.
