### ISSUE TITLE
Error setting schedule on macOS

### ISSUE THREAD

**Issue by cdalvaro** [saltstack/salt#64153]
**Description**

When trying to set or update an schedule with the state `schedule.present` the state fails.

This is my current state:

```sls
periodic_update schedule set:
  schedule.present:
    - name: periodic_update
    - function: state.apply
    - run_on_start: True
    - hours: 2
    - returner: highstate
    - enabled: True
    - persist: True
```

The result of applying the state is the following:

```yml
local:
    ----------
    changes:
        ----------
    comment:
        Failed to add job periodic_update to schedule.
    result:
        False
```

After debugging the _schedule.py_ (module/state/util) I've found that the issue is here:

https://github.com/saltstack/salt/blob/4bbdd653676de8734fabca68adfda023ad0f0e0d/salt/modules/schedule.py#L672-L675

Because no event is recovered.

**Setup**

I'm currently running salt 3005 on an Apple Silicon Mac (macOS 13.3.1) with salt installed via Homebrew. However, the issue also happens on an Intel Mac (macOS 12) running salt 3006 installed via onedir package.

**Steps to Reproduce the behavior**

The issue can be reproduced with the following command too:

```sh
sudo -E salt-call --local schedule.add periodic_update \
  function='state.apply' run_on_start=True hours=2 \
  returner='highstate' enabled=True persist=True

local:
    ----------
    changes:
        ----------
    comment:
        Failed to add job periodic_update to schedule.
    result:
        False
```
