### ISSUE TITLE
[BUG] cmd.run doesn't output changes in test mode

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#64150]
**Description**
Most states will output a changes dictionary in test mode when they would run or make changes in normal operation. The `cmd.run` state is an exception to that rule. This is problematic when inspecting state output programmatically, because one can't reliably use the changes dictionary to determine if commands would be run or changes would be made in normal operation.

**Steps to Reproduce the behavior**

A basic state such as this:

```yaml
echo hello:
  cmd.run
```

...produces this output in test mode.

```
          ID: echo hello
    Function: cmd.run
      Result: None
     Comment: Command "echo hello" would have been executed
     Started: 18:23:03.961085
    Duration: 0.481 ms
     Changes:
```

**Expected behavior**
Expect standardized operation between states.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.0+0na.da6403b
 
Python Version:
        Python: 3.7.3 (default, Oct 31 2022, 14:04:00)
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.5
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: 2.6.1
  pycryptodome: 3.17
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 25.0.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10.13 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-23-amd64
        system: Linux
       version: Debian GNU/Linux 10.13 buster
```
</details>
