### ISSUE TITLE
[BUG] 3006.0 breaks Yubico external authentication

### ISSUE THREAD

**Issue by Sidicer** [saltstack/salt#64185]
**Description**
After updating our Salt to 3006.0 we lost the ability to externally authenticate using yubico. After further testing we confirmed that PAM authentication still works, but yubico gives `Authentication error occurred`

Previously we were able to use our yubikeys to authenticate with salt (Version `3005.1`)

**Setup**
`salt-api` uses saltstack provided `salt/auth/yubico.py`

`/etc/salt/master` config:
```yaml
netapi_enable_clients:
  - local
  - local_async
  - local_subset
  - runner
  - runner_async
  - ssh
  - wheel
  - wheel_async

yubico_users:
  user@email:
    id: 00001
    key: redacted=

external_auth:
  pam:
    localuser:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'

  yubico:
    user@email:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'
```

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
1. On version `3005.1` run `salt -a yubico 'salt-master*' test.version`
2. Enter yubico email when prompted for username
3. Touch yubikey USB Key when prompted for password
4. Wait for it to authenticate
5. Receive salt-master's version number
6. Update salt master server to `3006.0`
7. Enable `netapi_enable_clients` all possible APIs in Master config
8. Reload salt-master and salt-api services
9. On version `3006.0` run `salt -a yubico 'salt-master*' test.version`
10. Enter yubico email when prompted for username
11. Touch yubikey USB Key when prompted for password
12. Receive `Authentication error occurred.`

**Expected behavior**
While using `-a yubico` option with `salt` we expect a successful return after inputting yubico user email and code (touching the yubikey)

**Screenshots**
![image](https://user-images.githubusercontent.com/9251667/235154504-a78ac484-6efa-450d-8027-0c01838f5617.png)

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.0
 
Python Version:
        Python: 3.10.11 (main, Apr 14 2023, 05:57:16) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.31
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.11.2
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```

</details>
