### ISSUE TITLE
[BUG] file.managed and file.symlink both run in test mode by default

### ISSUE THREAD

**Issue by zeddD1abl0** [saltstack/salt#64195]
**Description**
During a basic file.managed or file.symlink, running `salt state.apply` results in "symlink is set for creation" or "The file is set to be changed. Note: No changes have been applied."

Even explicitly setting "test" in the minion configuration to False did not fix the issue. The only fix is to manually intervene and hope that the files line up as expected.

**Setup**

```sls
/opt/netbox:
  file.symlink:
    - target: /opt/netbox-{{ netboxversion }}
    - force: True
    - test: False
    - require:
      - archive: /opt

/opt/netbox/local_requirements.txt:
  file.managed:
    - source: salt://filesets/netbox/local_requirements.txt
    - require:
      - file: /opt/netbox

```

Please be as specific as possible and give set-up details.

- [X] VM (ProxMox)
- [X] onedir packaging

**Steps to Reproduce the behavior**
With the given symlink and managed examples above, simply running `salt state.apply` fails. The same is true of a managed file

**Expected behavior**
Prior to 3006, when running `salt state.apply` the file would be changed or updated as per the SLS definition.

**Screenshots**
![image](https://user-images.githubusercontent.com/8335605/235352359-b5cba8a4-0c79-4dee-8169-8064c3986172.png)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.0
 
Python Version:
        Python: 3.10.11 (main, Apr 14 2023, 05:57:16) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.31
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.11.2
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: almalinux 8.7 Stone Smilodon
        locale: utf-8
       machine: x86_64
       release: 4.18.0-425.19.2.el8_7.x86_64
        system: Linux
       version: AlmaLinux 8.7 Stone Smilodon
```
</details>

**Comment by OrangeDog** [comment]
What is the output of `salt 'minion' config.get test`?

**Comment by zeddD1abl0** [comment]
![image](https://user-images.githubusercontent.com/8335605/235683957-66dbbff7-1542-425f-bd29-db156a69f4a1.png)

As per the screenshot, a value of `False` is returned.

**Comment by OrangeDog** [comment]
Do you have any custom code that might be putting a run into test mode accidentally?

**Comment by zeddD1abl0** [comment]
@OrangeDog I don't think so. There's nothing too spectacular in my configuration really. I'm using a fairly simple Salt install with a simple git repo, etc. if I create the symlink or file by hand, it takes a few refreshes, and then it finally sticks. If I then remove the symlink/file it goes back to "Unchanged". All these snippets are in the same SLS file:

```sls
/opt/netbox:
  file.symlink:
    - target: /opt/netbox-{{ netboxversion }}
    - force: True
    - require:
      - archive: /opt

/opt/netbox/gunicorn.py:
  file.managed:
    - source: salt://filesets/netbox/gunicorn.py
    - require:
      - file: /opt/netbox

/opt/netbox/netbox/media:
  file.directory:
    - user: netbox
    - group: netbox
    - recurse:
      - user
      - group

/opt/netbox/local_requirements.txt:
  file.managed:
    - source: salt://filesets/netbox/local_requirements.txt
    - require:
      - file: /opt/netbox

/opt/netbox/netbox/netbox/configuration.py:
  file.managed:
    - source: salt://filesets/netbox/configuration.py
    - template: jinja
    - require:
      - file: /opt/netbox
```

That's copy paste verbatim from the sls file, with some intervening states, but in the same sequence in the file. I'm fairly sure the sequence doesn't affect it, but just in case.

`/opt/netbox` and `/opt/netbox/netbox/configuration.py` both go to `unchanged`. But, if `/opt/netbox` is manually put in place, the others are successful.

**Comment by OrangeDog** [comment]
You're saying other states in the same run are applying changes, but these two and only these two are in test mode?

**Comment by zeddD1abl0** [comment]
Yup. Everything else in the SLS for these actions applies properly. Creating files, restarting services, etc. The whole thing. It's only those two specific states that appear to be in "Test" mode. And I have NO idea how that works. TBH, I don't bother with Test mode. I just apply state until steady.

**Comment by OrangeDog** [comment]
"it takes a few refreshes, and then it finally sticks", and "until steady" do not make sense to me.

After applying the state once, the system is then in that state. If that is not true then there is something else wrong.

**Comment by OrangeDog** [comment]
This may be related to #55269, if `__opts__["test"]` is not `True`, but the state is incorrectly returning a `None` result now with changes.

**Comment by zeddD1abl0** [comment]
So, I removed the symlink earlier to confirm it's still doing weird stuff, then I re-added the symlink manually. Here is the result:

netbox01:

![image](https://user-images.githubusercontent.com/8335605/235928957-2f47ac6d-331d-4636-989f-b5fa603b640e.png)

salt master:

![image](https://user-images.githubusercontent.com/8335605/235929149-328769d1-f98b-42a1-9613-3074be8f3321.png)

This is what I mean by "it finally sticks". When I first ran it tonight, it told me that the state matches. Of course it matched. The symlink was there from last night. Manually, I go and I remove the symlink, and the state dies. I go and manually create the symlink, and it still thinks there's a problem. Previously, in 3005, if I manually intervened because of something, Salt would simply go "Hey, it's here. Awesome". Now it appears to be caching the state or the files or something and then getting horribly confused when I manually take an action in the SLS file.

In the course of writing this comment, I reran the `state.apply` and got this result 13 minutes later:

![image](https://user-images.githubusercontent.com/8335605/235931634-a38d6ad9-14e3-49dd-a487-a4fcc3e817de.png)

The symlink exists. I took a screenshot. And yet, Salt appears to be confused because it does not want to apply a state that is already in place and functional.

--------------

By "until steady", what I mean is, sometimes I'm a little overzealous with some of my states, and they take a second or a third pass before the are 100% ready. It's because I'm still learning, and I don't want to lean too heavily on the "before","after","require" pieces of Salt. I'm used to this, so I put up with it for some things. I have a whole SLS to deploy ElasticSearch and Kibana from scratch. It works perfectly... after the second or third `state.apply` because it's got too many moving pieces for them to all line up in the first `state.apply`. So, I mash `state.apply`, wait 15 minutes, it tells me it had 14 errors. I reapply `state.apply` and it comes back clean.

**Comment by lkubb** [comment]
> This may be related to #55269, if `__opts__["test"]` is not `True`, but the state is incorrectly returning a `None` result now with changes. @lkubb is that possible?

I had the same intuition, but I don't see how this would be related since that PR only affected failing runs. I think I have seen similar behavior as described in here since including [a patched variant of] the current [3006] `file` modules in my custom modules, but not from only applying this patch before. The behavior is only present during a highstate and does not show itself when applying the same state tree with `state.sls`.

**Comment by zeddD1abl0** [comment]
It has to be a problem with my configuration. I now have the following

![image](https://user-images.githubusercontent.com/8335605/236678299-af152cbf-a4a0-4884-a455-a4a5096fe19d.png)

Which is insane. I can't imagine that Salt would've released 3006 without finding this, but. I can't figure out how or where. Need to figure that out now I guess...

**Comment by ymasson** [comment]
Same problem after 3004.2 to 3006.1 upgrade of salt-minion.

```
Name: /etc/haproxy/ssl/xxxxx.pem - Function: file.managed - Result: Differs - Started: 13:03:39.850351 - Duration: 31.351 ms
Name: haproxy - Function: service.running - Result: Changed - Started: 13:03:40.643770 - Duration: 59.438 ms
```
comment of file.managed :
```
        comment:
            The file /etc/haproxy/ssl/xxxxx.pem is set to be changed
            Note: No changes made, actual changes may
            be different due to other states.
```
The file is not updated. The service reload like it was updated.

the state:
```
haproxy_xxxxx_letsencrypt_certificates:
  file.managed:
    - name: /etc/haproxy/ssl/xxxxx.pem
    - source: https://xxxxx/letsencrypt_xxxxx.pem
    - source_hash: https://xxxxx/letsencrypt_xxxxx.pem.hash
    - user: haproxy
    - group: haproxy
    - mode: '0400'
    - watch_in:
      - haproxy_service
      
haproxy_service:
  service.running:
    - name: haproxy
    - enable: True
    - reload: True
```
salt version: 3006.1

**Comment by ymasson** [comment]
in the same formula, i have few other `file.managed` state.
like
```
haproxy_apt_preference:
  file.managed:
    - name: /etc/apt/preferences.d/haproxy
    - user: root
    - group: root
    - mode: '0644'
    - contents: |
        Package: haproxy*
        Pin: origin haproxy.debian.net
        Pin-Priority: 600
```
or using `- source: salt://xxx`
they are not affected.

it seems affecting only HTTP sources.
