### ISSUE TITLE
[BUG] mac_user.enable_auto_login broken in Python 3

### ISSUE THREAD

**Issue by pjcreath** [saltstack/salt#64226]
**Description**
During salt's migration to Python 3 five years ago, the password hashing function for mac_user.enable_auto_login was changed to treat its output as unicode rather than raw bytes.  That obviously breaks a hash.

Interestingly, it looks like the integration tests caught it, but instead of fixing the issue, f5f03e1 changed the integration test to expect the broken output.  Shortly thereafter, 667b5b9 cemented the change in the hash function.

The user will still be automatically logged in, but the result of the wrong hash is that the user's keychain gets reset upon each boot.

**Setup**
* salt master (hostname "salt") is running in a container on the Proxmox host.
* macOS minion (hostname "macminion") is running on a Mac Mini.

**Steps to Reproduce the behavior**
`salt macminion user.enable_auto_login name=user password=Squarepants`

**Expected behavior**
mac_user.enable_auto_login should produce the correct hash in /etc/kcpassword so that the user's keychain doesn't get wiped out on each boot.

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: 1.0.6
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Feb 21 2023, 05:30:22)
  python-gnupg: 0.4.6
        PyYAML: 3.12
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: oracle 8.7 
        locale: UTF-8
       machine: x86_64
       release: 5.15.102-1-pve
        system: Linux
       version: Oracle Linux Server 8.7 
```
</details>
