### ISSUE TITLE
[BUG] lgpo_reg state does not enforce/report registry changes

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#64222]
**Description**
The `lgpo_reg` state module determines success and failure based solely on the content of the `Registry.pol` file. The execution module also sets the value in the registry. This allows for a scenario where the state will run and set the policy, the user will change the registry value, the state runs again and thinks everything is correct because the `Registry.pol` file is correct, but the registry setting is not correct. The state needs to detect the incorrect registry setting as well. It needs to be displayed in `test=True` and in changes made after a successful run.

**Setup**
Given the following state:
```
# content of lgpo_reg.sls
set_reg_pol_value:
  lgpo_reg.value_present:
    - key: SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    - name: HideFileExt
    - v_data: 0
```

**Steps to Reproduce the Behavior**

Apply the state:
```
salt-call --local state.apply lgpo_reg
```
Change the registry value to something else:
```
salt-call --local reg.set_value HKLM SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced HideFileExt vdata=1
```
Apply the state again:
```
salt-call --local state.apply lgpo_reg
```
Salt thinks everything is fine... but it's not.

**Expected behavior**
The state should detect the registry discrepancy and change it
The changes should be displayed during ``test=True`` and in a successful run

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
3006.x branch
```
</details>
