### ISSUE TITLE
[BUG] test.fail_without_changes throws Event iteration failed with exception: 'user'

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#64231]
**Description**

Running a simple state like:
```
test_state:
  test.fail_without_changes:
    - name: "bla"
```

Throws the exception: `Event iteration failed with exception: 'user'`

**Steps to Reproduce the behavior**
Run the state above: `salt 'myhost*' state.sls test_state test=true saltenv=test_state`

Output from salt-master logfile in debug mode:
```
[ERROR   ] Event iteration failed with exception: 'user'
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/event.py", line 905, in _fire_ret_load_specific_fun
    data["user"] = load["user"]
KeyError: 'user'
```

**Expected behavior**
No exception should be thrown.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.0

Python Version:
        Python: 3.10.11 (main, Apr 14 2023, 05:57:16) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.31
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.11.2
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 20.04.5 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-144-generic
        system: Linux
       version: Ubuntu 20.04.5 focal
```
</details>
