### ISSUE TITLE
Minions lose connection with master after IPTables loaded

### ISSUE THREAD

**Issue by JasonSwindle** [saltstack/salt#6424]
Howdy,

This is an issue that is driving me crazy.  I am using iptables-persistent to load very simple iptables rules on reboot of my Ubuntu 12.04 nodes.  As soon as the rules are loaded; the minions will not talk Salt for about 5 minutes.  This happened in Salt 0.16.0 nd 0.16.1 / Ubuntu 12.04 and 13.04.
#### SLS

```
iptables-persistent_install:
  pkg.installed:
    - name: iptables-persistent
  file.managed:
    - user: root
    - group: root
    - mode: 0640
    - source: salt://packages/iptables/{{ grains.node_type }}/rules.v4
    - name: /etc/iptables/rules.v4
    - require:
      - pkg: iptables-persistent_install
  service.running:
    - name: iptables-persistent
    - enable: True
    - reload: True
    - require:
      - file: iptables-persistent_install
    - watch: 
      - file: /etc/iptables/rules.v4
```
#### rules.v4

```
# Generated by iptables-save v1.4.12 on Wed Jul 24 12:52:31 2013
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 6379 -j ACCEPT
-A INPUT -m state --state new -m tcp -p tcp --dport 4505 -j ACCEPT
-A INPUT -m state --state new -m tcp -p tcp --dport 4506 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on Wed Jul 24 12:52:31 2013
```
#### Salt Master

```
alt --versions-report
           Salt: 0.16.1
         Python: 2.7.3 (default, Apr 20 2012, 22:39:59)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```
#### Salt Minion

```
salt-call --versions-report
           Salt: 0.16.0
         Python: 2.7.3 (default, Apr 10 2013, 06:20:15)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```

~Jason Swindle
