### ISSUE TITLE
[BUG] state to upgrade bundled pip fails after removing pip with a permissions issue leaving no usable pip

### ISSUE THREAD

**Issue by wwimberly** [saltstack/salt#64250]
**Description**

When running a state to upgrade pip, it fails with a permissions issue after uninstalling the bundled pip. This breaks all salt-pip functionality since pip was removed.

```shell
sudo -u salt salt $(hostname -f) state.apply salt-master.setup
```

Relevant section of `setup.sls`:

```saltstack
pip:
  pip.installed:
    - upgrade: True
    - user: salt
``` 

Results:

```
----------
          ID: pip
    Function: pip.installed
      Result: False
     Comment: Failed to install packages: pip. Error: Requirement already satisfied: pip in ./lib/python3.10/site-packages (22.3.1)
              Collecting pip
                Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)
                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 20.5 MB/s eta 0:00:00
              Installing collected packages: pip
                Attempting uninstall: pip
                  Found existing installation: pip 22.3.1
                  Uninstalling pip-22.3.1:
                    Successfully uninstalled pip-22.3.1 ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'base.cpython-310.pyc'
              Consider using the `--user` option or check the permissions.
     Started: 16:21:33.243679
    Duration: 10058.413 ms
     Changes:
----------
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify) vSphere
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Use this state to upgrade the bundled pip.

**Expected behavior**
The bundled pip is upgraded. 

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-71-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy

```
</details>
