### ISSUE TITLE
[BUG] SaltStack constantly goes into stuck state with SaltReqTimeoutError

### ISSUE THREAD

**Issue by dmulyalin** [saltstack/salt#64268]
**Description**

After a few month back Salt-Master and Salt-Proxy-Minions started to run into stuck state with `salt.exceptions.SaltReqTimeoutError: Message timed out` error on minion end indicating failure to contact master, where the only way to recover is to restart the docker process - `systemctl restart docker`. 

<details><summary>Typical traceback when problem happens and master goes into stuck state</summary>

```
salt-minion-nrp1     | 2023-05-10 09:59:23,354 [ERROR   ] Future <salt.ext.tornado.concurrent.Future object at 0x7f26c44554c0> exception was never retrieved: Traceback (most recent call last):
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1064, in run
salt-minion-nrp1     |     yielded = self.gen.throw(*exc_info)
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/minion.py", line 2699, in handle_event
salt-minion-nrp1     |     yield _minion.req_channel.send(
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1056, in run
salt-minion-nrp1     |     value = future.result()
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
salt-minion-nrp1     |     raise_exc_info(self._exc_info)
salt-minion-nrp1     |   File "<string>", line 4, in raise_exc_info
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1064, in run
salt-minion-nrp1     |     yielded = self.gen.throw(*exc_info)
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/channel/client.py", line 295, in send
salt-minion-nrp1     |     ret = yield self._crypted_transfer(load, timeout=timeout, raw=raw)
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1056, in run
salt-minion-nrp1     |     value = future.result()
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
salt-minion-nrp1     |     raise_exc_info(self._exc_info)
salt-minion-nrp1     |   File "<string>", line 4, in raise_exc_info
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1064, in run
salt-minion-nrp1     |     yielded = self.gen.throw(*exc_info)
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/channel/client.py", line 252, in _crypted_transfer
salt-minion-nrp1     |     ret = yield _do_transfer()
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1056, in run
salt-minion-nrp1     |     value = future.result()
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
salt-minion-nrp1     |     raise_exc_info(self._exc_info)
salt-minion-nrp1     |   File "<string>", line 4, in raise_exc_info
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1064, in run
salt-minion-nrp1     |     yielded = self.gen.throw(*exc_info)
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/channel/client.py", line 233, in _do_transfer
salt-minion-nrp1     |     data = yield self.transport.send(
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1056, in run
salt-minion-nrp1     |     value = future.result()
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
salt-minion-nrp1     |     raise_exc_info(self._exc_info)
salt-minion-nrp1     |   File "<string>", line 4, in raise_exc_info
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1064, in run
salt-minion-nrp1     |     yielded = self.gen.throw(*exc_info)
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/transport/zeromq.py", line 916, in send
salt-minion-nrp1     |     ret = yield self.message_client.send(load, timeout=timeout)
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1056, in run
salt-minion-nrp1     |     value = future.result()
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
salt-minion-nrp1     |     raise_exc_info(self._exc_info)
salt-minion-nrp1     |   File "<string>", line 4, in raise_exc_info
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1064, in run
salt-minion-nrp1     |     yielded = self.gen.throw(*exc_info)
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/transport/zeromq.py", line 626, in send
salt-minion-nrp1     |     recv = yield future
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 1056, in run
salt-minion-nrp1     |     value = future.result()
salt-minion-nrp1     |   File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
salt-minion-nrp1     |     raise_exc_info(self._exc_info)
salt-minion-nrp1     |   File "<string>", line 4, in raise_exc_info
salt-minion-nrp1     | salt.exceptions.SaltReqTimeoutError: Message timed out
```
</details>

Container itself is responsive in a way that can access its bash shell and run commands, but if master stuck none of the minion able to contact it, if proxy minion stuck, it is uncontactable by master.

Before about two month back all was working fine.

I was developing custom proxy minion for few years - [salt-nornir](https://github.com/dmulyalin/salt-nornir) - and hitting the problem with this custom proxy minion as I am not using any other Salt built in minion/proxy minions.

**Setup**

Have one master and 3 proxy minions. All running in containers on 8 CPU 16 Gbyte of RAM VM.

Tried various setups using different version of python3.x containers on Ubuntu 22.04 and RockyLinux 8.5 VM as a host.

Dockerfiles:
[master dockerfile](https://github.com/dmulyalin/salt-nornir/blob/master/test/Dockerfile.py39.master)
[minion dockerfile](https://github.com/dmulyalin/salt-nornir/blob/master/test/Dockerfile.py39.minion)
[docker compose](https://github.com/dmulyalin/salt-nornir/blob/master/docker-compose.py39.yaml)

Tried these Debian containers - python:3.7-slim-bullseye, python:3.9-slim-bullseye, python:3.10-slim-bullseye

Tried using onedir installation and pip based installation.

Tried these SaltStack versions: SALT 3002, 3003, 3004, 3005, 3006

Tried versions of docker: 20.10.13, 23.0.6

Again, all was working fine a about two months ago, also tried downgrading the code of the salt-nornir proxy minion back to version dated mid last year, still seeing the issue.

**Steps to Reproduce the behavior**

I have a set of tests to run to test salt-nornir functionality, previously all those tests been running to completion with no issues, now they stuck at various points, like on 1st attempt maybe after 24th test, on another after 50th tests etc. 

Not sure if anybody would be willing to reproduce lab setup but guide is [here](https://github.com/dmulyalin/salt-nornir/blob/master/test/readme.md)

I am happy to run tests myself or gather logs, commands, traces as required.

**Expected behavior**

Master and Proxy Minion run tasks without going into stuck state.

**Versions Report**
<details><summary>salt 3006 --versions-report</summary>

```yaml
root@salt-master:/# salt -V
--
Salt Version:
Salt: 3006.0
 
Python Version:
Python: 3.9.16 (main, Apr 12 2023, 06:58:15)
 
Dependency Versions:
cffi: 1.14.6
cherrypy: unknown
dateutil: 2.8.1
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
Jinja2: 3.1.2
libgit2: Not Installed
looseversion: 1.0.2
M2Crypto: Not Installed
Mako: Not Installed
msgpack: 1.0.2
msgpack-pure: Not Installed
mysql-python: Not Installed
packaging: 22.0
pycparser: 2.21
pycrypto: Not Installed
pycryptodome: 3.9.8
pygit2: Not Installed
python-gnupg: 0.4.8
PyYAML: 5.4.1
PyZMQ: 23.2.0
relenv: Not Installed
smmap: Not Installed
timelib: 0.2.4
Tornado: 4.5.3
ZMQ: 4.3.4
 
Salt Extensions:
salt-nornir: 0.19.1
 
System Versions:
dist: debian 11 bullseye
locale: utf-8
machine: x86_64
release: 5.15.0-71-generic
system: Linux
version: Debian GNU/Linux 11 bullseye
 
root@salt-master:/#
```
</details>

**Additional context**

Was suspecting that where have been some dependency changes that caused this issue, but was rebuilding the environment as far as back to SALT 3002, but still seeing the issue, which obviously was not the case when SALT 3002 was the latest version of Salt few years back.
