### ISSUE TITLE
[BUG] Master cannot serve files to salt minion

### ISSUE THREAD

**Issue by olipinski** [saltstack/salt#64338]
**Description**
Master cannot serve files to minion, if they are set to permissions 644, with ownership of root:root, and symlinked through a 700 directory. 

While the master can see the file, and list it as available to the minion using `salt 'minion' cp.list_master`, attempting to serve it leads to an error.

Previous versions of salt supported this. This may be related to #64037 and #64174. However, the documentation still states as of 3006.1 that this should be possible, as salt should still be ran as root.

```
user

Default: root

The user to run the Salt processes

user: root
```

**Setup**
Files to be served: 
```
drwx------ 2 root      root        4096 May 23 20:57 test
lrwxrwxrwx 1 root      root           9 May 23 21:01 testx -> test/test
```

`ls-al test/`
```
total 8
drwx------ 2 root root 4096 May 23 20:57 .
drwxr-xr-x 8 root root 4096 May 23 21:01 ..
-rw-r--r-- 1 root root    0 May 23 20:57 test 
```

SLS:
test.sls
```yaml
/etc/test:
  file.managed:
    - source:
      - salt://files/testx
    - user: root
    - group: root
    - mode: 755
```

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
`salt 'minion state.apply test`

**Expected behavior**
File being served to the minion.

**Screenshots**
```
          ID: /etc/test
    Function: file.managed
      Result: False
     Comment: Source file salt://files/testx not found in saltenv 'base'
     Started: 21:02:47.397534
    Duration: 80.897 ms
     Changes:  

```

**Versions Report**
<details><summary>salt --versions-report</summary>

Master:
```yaml
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: 1.6.3
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.12.0
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-72-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy
```

Minion:
```yaml
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: 6.1.1
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-72-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy
```
</details>
