### ISSUE TITLE
[BUG] 3006.1 - nacl commands not responding on debian 11 - segfault

### ISSUE THREAD

**Issue by ITJamie** [saltstack/salt#64342]
**Description**
when setting up a new 3006.1 master on debian 11 i noticed nacl decryption/encryption was not working. (fresh install)

**Setup**

- [ ] on-prem machine
- [ X ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
generate nacl keys (assuming you dont already have some, beware as this will override the default path)
`salt-call nacl.keygen sk_file=/etc/salt/pki/master/nacl pk_file=/etc/salt/pki/master/nacl.pub`

attempt to encrypt a string with sealedbox_encrypt (hangs and needs to be killed)
``` bash
root@saltdirector-network:/etc/salt/master.d# salt-call --local nacl.sealedbox_encrypt datatoenc pk_file=/etc/salt/pki/master/nacl.pub
Killed
```

attempt to encrypt a string with secretbox_encrypt (seg faults)
``` bash
salt-call --local nacl.secretbox_encrypt datatoenc sk_file=/etc/salt/pki/master/nacl
Segmentation fault
```

I also attempted to decrypt a string with a known set of keys and secrets, that also segfaulted

docker build example 
``` docker
FROM --platform=amd64 debian:bullseye

run apt-get update
run apt-get install curl -y
run mkdir /etc/apt/keyrings

run curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/debian/11/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
run echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/debian/11/amd64/3006 bullseye main" |  tee /etc/apt/sources.list.d/salt.list
run apt-get update

run apt-get install salt-minion salt-master -y
run salt-pip install libnacl
run apt-get install libsodium23 -y
run salt-call --local nacl.keygen sk_file=/etc/salt/pki/master/nacl pk_file=/etc/salt/pki/master/nacl.pub
run salt-call --local nacl.secretbox_encrypt datatoenc sk_file=/etc/salt/pki/master/nacl
run salt-call --local nacl.sealedbox_encrypt datatoenc pk_file=/etc/salt/pki/master/nacl.pub
```
**Error**
docker build example
```
 => [11/13] RUN salt-call --local nacl.keygen sk_file=/etc/salt/pki/master/nacl pk_file=/etc/salt/pki/master/nacl.pub                              10.2s 
 => ERROR [12/13] RUN salt-call --local nacl.secretbox_encrypt datatoenc sk_file=/etc/salt/pki/master/nacl                                          3.9s 
------                                                                                                                                                   
 > [12/13] RUN salt-call --local nacl.secretbox_encrypt datatoenc sk_file=/etc/salt/pki/master/nacl:                                                     
#15 3.918 qemu: uncaught target signal 11 (Segmentation fault) - core dumped                                                                             
#15 3.926 Segmentation fault  
```

**Expected behavior**
nacl should return an encrypted string or a decyrpted string without segfaulting or hanging

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.1

Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: 1.6.4
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.12.1
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-11-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>
