### ISSUE TITLE
[BUG] salt commands to /etc/salt/roster clients are timing out when enable_ssh_minions is true.

### ISSUE THREAD

**Issue by jude** [saltstack/salt#64426]
**Description**
I have enable_ssh_minions set to true in /etc/salt/master.d/ssh.config, however 'salt' commands to hosts in the /etc/salt/roster file seem to be handled as minions instead of ssh clients.

'salt roster_client' commands will time out, but 'ssh-client roster_client' commands work as expected.

Client globbing like 'salt '*'' finds both the minions and /etc/salt/roster hosts, but the roster hosts time out.

**Setup**
/etc/salt/master.d/ssh.config:
 enable_ssh_minions: True

The master is on-prem, the /etc/salt/roster hosts are VMs running on a variety of cloud platforms.  One of the /etc/salt/roster hosts is a raspberry pi.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [x] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
- Have a ssh client defined /etc/salt/roster
- Verify that 'salt-ssh' is working as expected with the ssh client
- Enable  "enable_ssh_minions: True" in /etc/salt/master if it's not enabled already / restart the salt master if updated the config files.
- Try running the same commands with 'salt' instead of 'salt-ssh' and see the commands time out.
- Try running some "salt '*'" commands and see regular minions respond, but the /etc/salt/roster hosts time out.
- Tail the logs on the roster clients and see no incoming ssh connections during the 'salt' commands.

```
#  cat /etc/salt/master.d/ssh.conf 
enable_ssh_minions: True

# salt-ssh roster_host cmd.run '/bin/echo hello'
roster_host:
    hello

# salt roster_host cmd.run '/bin/echo hello'
roster_host:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20230606135558632906
    
# salt '*' cmd.run '/bin/echo hello'
minion_host:
    hello
roster_host:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20230606141541756908

```

**Expected behavior**
Both the 'salt-ssh' and 'salt' commands should work for hosts from the /etc/salt/roster file when enable_salt_minions is set to True.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
# salt --versions-report

```yaml
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04.6 focal
        locale: utf-8
       machine: x86_64
       release: 6.0.12-76060012-generic
        system: Linux
```
</details>

**Additional context**
This seems to be new 3006.1 behavior.  This was working OK in 3005.1, and I don't remember having to patch anything in the 3005.1 code to get enable_ssh_minions working.
