### ISSUE TITLE
[BUG] Fix 'unable to unmount' failure to return False result instead of None

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#64420]
**Description**
In certain scenarios, NFS unmount can fail but the state result returns `None`

```
[ERROR   ] Command 'umount' failed with return code: 16
[ERROR   ] stderr: umount.nfs: /mnt/cached_binaries: device is busy
[ERROR   ] retcode: 16
local:
----------
          ID: racoon_binaries_add_mount_/mnt/cached_binaries
    Function: mount.mounted
      Result: None
     Comment: Unable to unmount
     Started: 15:34:58.338883
    Duration: 113.737 ms
     Changes:
              ----------
              umount:
                  Forced unmount because devices don't match. Wanted: example1.com:/racoon_binaries, current: example2.com:/racoon_binaries, /root/example2.com:/racoon_binaries

Summary for local
--------------
Succeeded: 148 (unchanged=1, changed=1)
Failed:      0
Success %: 100.0
Failure %: 0.0
--------------
Total states run:     148
Total run time:     6.719 s
```

**Expected behavior**
A failure should... fail... no?

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.0+0na.da6403b
 
Python Version:
        Python: 3.7.3 (default, Oct 31 2022, 14:04:00)
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.5
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: 2.6.1
  pycryptodome: 3.17
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 25.0.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10.13 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-24-amd64
        system: Linux
       version: Debian GNU/Linux 10.13 buster
```
</details>
