### ISSUE TITLE
[BUG] Cannot enroll Ubuntu 22.04 host as minion

### ISSUE THREAD

**Issue by MartijnVerkleij** [saltstack/salt#64445]
**Description**
As part of our infrastructure we are rolling out Ubuntu workstations, which we manage through salt. 

Today we tried to join a blank "minimal" installation of Ubuntu Desktop 22.04 as a minion in the system. To do this, we used the new bootstrap script to install the minion.

After succesful installation, when the minion tries to connect to the salt master, the following error is returned:
`salt-minion[6951]: Protocol not available (bundled/zeromq/src/tcp_connecter.cpp:289)`

**Setup**

The salt-minion is an Ubuntu Desktop 22.04 install, updated with the latest software.

The salt-master is locally hosted on a Debian 10 VM (ESXi host) running version 3005.1.
The salt-master is probably still using classic packaging.

**Steps to Reproduce the behavior**

- Install Ubuntu Desktop 22.04. Run `apt update` and `apt upgrade`.
- Download the bootstrap script from [https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html].
- Install Saltstack as instruction on the previously linked page.
- Set the salt-master's IP address in `/etc/salt/minion` and restart the minion with `systemctl restart salt-minion`
- Observe the error using `journalctl -fu salt-minion`

**Expected behavior**
The minion should be able to be enrolled.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

_The minion on Ubuntu after the failed install:_
```yaml
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.19.0-43-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy
```

_Salt Master:_
```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Oct 31 2022, 14:04:00)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: utf-8
       machine: x86_64
       release: 4.19.0-21-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster

```
</details>
