### ISSUE TITLE
[BUG] file.symlink will not replace/update existing symlink

### ISSUE THREAD

**Issue by onmeac** [saltstack/salt#64477]
**Description**

file.symlink docs:

> If the file already exists and is a symlink pointing to any location other than the specified target, the symlink will be replaced.

However this does not seem to work in version 3006.1

```
local:
----------
          ID: foo
    Function: file.symlink
        Name: /foo
      Result: False
     Comment: Unable to create new symlink /foo -> /baz: Found existing symlink: /foo
     Started: 16:19:03.417405
    Duration: 6.565 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   6.565 ms
```

**Setup**
symlink_test.sls:
```
foo:
  file.symlink:
    - name: /foo
    - target: /baz
```
- [ ] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
- `ln -nfs /bar /foo`
- `salt-call state.apply symlink_test`

**Expected behavior**
```local:
----------
          ID: foo
    Function: file.symlink
        Name: /foo
      Result: True
     Comment: Created new symlink /foo -> /baz
     Started: 16:13:06.093500
    Duration: 7.27 ms
     Changes:   
              ----------
              new:
                  /foo

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   7.270 ms
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: centos 7.9.2009 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.81.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7.9.2009 Core

```
</details>
