### ISSUE TITLE
[BUG] napalm-syslog doesn't start listening port with Salt 3006.1

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#64489]
**Description**
napalm-syslog doesn't start a listening port when started from a minion on Salt 3006.1

**Setup**
```
# salt-pip install napalm-logs
```

_/etc/salt/minion.d/napalm_syslog.conf_ 
```
engines:
  - napalm_syslog:
      transport: zmq
      address: 192.0.2.1
      port: 12345
      disable_security: True
      certificate: None
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Use config supplied above.

```
# salt-minion -l debug
...
[INFO    ] Starting Engine(salt.loaded.int.engines.napalm_syslog)
[DEBUG   ] Started 'Engine(salt.loaded.int.engines.napalm_syslog)' with pid 3046839
...
```

```
ps auwx | grep 3046839
root     3046839  0.3  0.1 453152 81312 pts/1    Sl+  16:32   0:00 /opt/saltstack/salt/bin/python3.10 /bin/salt-minion -l debug MultiMinionProcessManager MinionProcessManager Engine(salt.loaded.int.engines.napalm_syslog)

# netstat -nlp | grep 12345

# netstat -nlp | grep 3046839

```

**Expected behavior**
A syslog listener to start on port 12345

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.1

Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 8.7 Stone Smilodon
        locale: utf-8
       machine: x86_64
       release: 4.18.0-425.3.1.el8.x86_64
        system: Linux
       version: AlmaLinux 8.7 Stone Smilodon
```
</details>

**Comment by ggiesen** [comment]
So this issue was a misunderstanding on my part on the way the engine works. The engine doesn't open a listening socket, it connects to one running on napalm-logs.

Example working configuration:

_/etc/salt/minion.d/napalm_syslog.conf:_
```
engines:
  - napalm_syslog:
      transport: zmq
      address: 127.0.0.1 # Must be an address that napalm-logs listens on with the publish-address setting
      port: 49017 # Must be the same as publish-port option in napalm-logs
      disable_security: True
      certificate: None
```
```
# napalm-logs -a 0.0.0.0 -p 514 --publisher=zmq --publish-address '127.0.0.1' --publish-port 49017 --disable-security
```
