### ISSUE TITLE
Create a general "db" state similar to the "pkg" state

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#6449]
Please add a general "db" state that works similar to the "pkg" state.

This would allow states to be create to manage a database without having to worry about the underlying database. You would indicate in the state somehow that you're using a mysql or sqlite database underneath.

```
proddb:
  db.present:
    - type: mysql
  db_user:
    - name: newuser
    - password: 2uoij23lj2lkj23lj23lkj07s0
```

This might require some discussion and planning on how to properly implement this.
