### ISSUE TITLE
[BUG] Or concatenation in IF condition is not working as exptected

### ISSUE THREAD

**Issue by cmonty14** [saltstack/salt#64513]
**Description**
I have defined an IF condition including an OR concatentation of multiple directories.
However, this IF condition is always TRUE independant if any of the directories exists or not.

**Setup**
```
{% set primaryIP = grains['fqdn_ip4'][0] %}
{% set hostname = grains['host'] %}
{% set fqdn = grains['fqdn'] %}
{% set domain = grains['domain'] %}
{% if hostname is match('^vl(a|c|g).*$') %}
{% set logicalHostname = hostname | regex_replace ('vl(a|c|g)','ld') %}
{% set logicalFqdn = fqdn | regex_replace ('vl(a|c|g)','ld') %}
{% else %}
{% if salt['file.directory_exists']('/hana') or salt['file.directory_exists']('/oracle') or salt['file.directory_exists']('/sapdb') %}
{% set logicalHostname = 'lddb<sid>' %}
{% set logicalFqdn = 'lddb<sid>.<domain>' %}
{% else %}
{% set logicalHostname = 'ldci<sid>' %}
{% set logicalFqdn = 'ldci<sid>.<domain>' %}
{% endif %}
{% endif %}

stc-etc-hosts_hostname_present:
  host.present:
    - ip: {{ primaryIP }}
    - names:
      - {{ fqdn }}
      - {{ hostname }}

stc-etc-hosts_duplicate_line_after_match/etc/hosts:
  cmd.run:
    - name: sed -i '/{{ fqdn }}/ {h;G}' /etc/hosts
    
stc-etc-hosts_replace_fqdn:
  file.replace:
    - name: /etc/hosts
    - pattern: {{ fqdn }}
    - repl: {{ logicalFqdn }}
    - count: 1

stc-etc-hosts_replace_hostname:
  file.replace:
    - name: /etc/hosts
    - pattern: {{ hostname }}
    - repl: {{ logicalHostname }}
    - count: 1
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [X ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Expected behavior**
The intention is to write variable `logicalHostname = 'lddb<sid>` only if any of directory _/hana_ or _/oracle_ or _/sapdb_ exists; if not write variable `logicalHostname = 'ldci<sid>`.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: sles 15.3 n/a
        locale: ISO-8859-1
       machine: x86_64
       release: 5.3.18-150300.59.115-default
        system: Linux
       version: SLES 15.3 n/a

```
</details>

**Additional context**
In case the IF condition is a single directory and not an OR concatenation, the state works as expected.
