### ISSUE TITLE
[FEATURE REQUEST] salt-minion pkg.* tasks fail if only dnf5 is present, not dnf

### ISSUE THREAD

**Issue by limburgher** [saltstack/salt#64532]
**Description**
pkg.* uses dnf with no issues for me on Fedora. However, starting with Fedora 39, dnf is obsoleted by dnf5. The command line options are different, so a simple symlink won't work.

**Setup**
```
install_fedora_packages:
  pkg.installed:
    - pkgs:
      - vim-enhanced
      - nmap
      - dnf-automatic
      - firewalld
```

Please be as specific as possible and give set-up details.
Install salt-minion on Fedora 39 instance, start minion, accept key on master. 

**Steps to Reproduce the behavior**
Apply the above sls.

**Expected behavior**
salt-minion installs packages.

**Screenshots**
----------
          ID: install_fedora_packages
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:
              
              errors:
                  - Unknown argument "--allowerasing" for command "dnf5". Add "--help" for more information about the arguments.
     Started: 19:45:43.710036
    Duration: 1480.451 ms
     Changes:   

**Versions Report**

Minion is Fedora 39 with same salt version.
Master:
```yaml
Master:
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.11.3 (main, May 24 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)]
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.30
        Jinja2: 3.0.3
       libgit2: 1.6.3
  looseversion: 1.2.0
      M2Crypto: 0.38.0
          Mako: 1.2.3
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.0
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.17.0
        pygit2: 1.12.0
  python-gnupg: 0.5.0
        PyYAML: 6.0
         PyZMQ: 24.0.1
        relenv: Not Installed
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: fedora 38 
        locale: utf-8
       machine: x86_64
       release: 6.3.8-200.fc38.x86_64
        system: Linux
       version: Fedora Linux 38 
```
</details>

**Additional context**
With dnf5, the old dnf cannot be installed. This completely breaks any pkg usage on Fedora 39+.
I'm the Fedora Link salt RPM package maintainer.
