### ISSUE TITLE
[BUG] Debian packaging for 3600 is not packaging pymongo

### ISSUE THREAD

**Issue by ekacnet** [saltstack/salt#64543]
**Description**
pymongo is missing from the debian packages leading to non working mongo state / and modules

**Setup**
```
ii  salt-common                         3006.1                                 amd64        shared libraries that salt requires for all packages
ii  salt-master                         3006.1                                 amd64        remote manager to administer servers via salt
ii  salt-minion                         3006.1                                 amd64        client package for salt, the distributed remote execution system
ii  salt-ssh                            3006.1                                 amd64        remote manager to administer servers via Salt SSH
```
And then a state using mongodb_user state:
```
mongouser-admin:                                                                                                                                                           
  mongodb_user.present:                                                                                                                                                    
  - name: admin                                                                                                                                                            
  - passwd: {{ pillar.get('mongo').get('admin_passwd') }}                                                                                                                  
  - database: admin           
```
 
Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Install the packages made for debian with list file like this:
```
deb [arch=amd64 signed-by=/etc/apt/keyrings/salt.gpg] https://repo.saltproject.io/salt/py3/debian/11/amd64/latest bullseye main
``` 
And then a state with 
```
mongouser-admin:                                                                                                                                                           
  mongodb_user.present:                                                                                                                                                    
  - name: admin                                                                                                                                                            
  - passwd: {{ pillar.get('mongo').get('admin_passwd') }}                                                                                                                  
  - database: admin           
```

Upon executing the state:
salt 'mongodbhost' state.apply mongo I get an error:
 
```
          ID: mongouser-admin                                                                                                                                              
    Function: mongodb_user.present                                                                                                                                         
        Name: admin                                                                                                                                                        
      Result: False                                                                                                                                                        
     Comment: State 'mongodb_user.present' was not found in SLS 'mongo'                                                                                                    
              Reason: 'mongodb_user' __virtual__ returned False: mongodb module could not be loaded      

```
It turns out that the state is using the mongodb module that won't load if pymongo is not available.
For 3006 debian packages are using their own python version so salt is not using the one provided by the distrubtion.

**Expected behavior**
The state works 

**Screenshots**

**Versions Report**
<details><summary>Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-19-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
</summary>

```yaml
PASTE HERE
```
</details>

**Additional context**
