### ISSUE TITLE
[BUG] access files on a remote backend 

### ISSUE THREAD

**Issue by danadeweerdx** [saltstack/salt#64566]
**Description**
I am not sure if this is possible, but i can not access the files in the remote repository. I trying to run a script that is placed on a remote location.

**Setup**

The following data is present in the master config file
```
gitfs_remotes:
  - git@github.com:../salt-states.git:
    - name: develop
    - base: temporary-states
    - saltenv:
      - dev:
        - ref: temporary-states
```
The structure of the repository is as follows:

example.sls
scripts
|_ example.sh

The content of the example.sls file:
```
Run example script:
  cmd.run:
    - name: salt://scripts/example.sh?saltenv=dev
```
The content of the example.sh script:
```
#!/bin/bash
echo "Hi, this is a example."
```
When I run 'salt minion0 state.sls example saltenv=dev' I get the following error:
```
minion0:
----------
          ID: Run example script
    Function: cmd.run
        Name: salt://scripts/example.sh?saltenv=dev
      Result: False
     Comment: Command "salt://scripts/example.sh?saltenv=dev" run
     Started: 09:36:02.148394
    Duration: 8.669 ms
     Changes:
              ----------
              pid:
                  4476
              retcode:
                  127
              stderr:
                  /bin/sh: salt://scripts/example.sh?saltenv=dev: No such file or directory
              stdout:

Summary for minion0
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:   8.669 ms
```
