### ISSUE TITLE
[BUG] jobs.list_job gives an error even when it finds a valid job

### ISSUE THREAD

**Issue by b1naryv1k1ng** [saltstack/salt#64570]
**Description**
When looking up a JID using jobs.list_job <jid>, even when it finds the job, it still gives an error saying no matching  job with this JID before giving the results of the job.

```
$ salt-run jobs.list_job 20230628184944012349
Error:
    Cannot contact returner or no job with this jid
Result:
    ----------
    dev-master_master:
        ----------
        return:
            ----------
            _stamp:
                2023-06-28T18:49:45.723151
            fun:
                runner.state.orch
            fun_args:
                |_
                  ----------
                  mods:
                      orch.API.metadata_test
                  pillar:
                      ----------
                      test:
                          Test
            jid:
                20230628184944012349
            return:
                ----------
                data:
                    ----------
                    dev-master_master:
                        ----------
                        salt_|-arbitrary_state_to_test_metadata_|-arbitrary_state_to_test_metadata_|-state:
                            ----------
                            __id__:
                                arbitrary_state_to_test_metadata
[...]
```

**Steps to Reproduce the behavior**
Search for a JID

**Expected behavior**
Not to show an error when it finds a matching Job with the provided JID

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: 1.4.6
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov  8 2022, 11:32:15)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 8.7 Green Obsidian
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-425.10.1.el8_7.x86_64
        system: Linux
       version: Rocky Linux 8.7 Green Obsidian
```
</details>
