### ISSUE TITLE
[BUG] ufw rules not installed on Ubuntu 22.04

### ISSUE THREAD

**Issue by rousku** [saltstack/salt#64572]
**Description**
ufw rules (/etc/ufw/applications.d/salt.ufw) are not being installed on ubuntu 22.04 with salt version 3006.1

**Setup**
Followed [these](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html#install-salt-on-ubuntu-22-04-jammy) instructions to install `Major onedir` version of `salt-master`.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM Virtualbox
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
```
ubuntu@ubuntu:/srv$ sudo ufw allow salt
ERROR: Could not find a profile matching 'salt'
```

**Expected behavior**
`sudo ufw allow salt` should run without errors

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.19.0-45-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy
```
</details>

**Additional context**
```
ubuntu@ubuntu:~$ ls /etc/ufw/applications.d/
cups  openssh-server
```
Maybe related to #57712
