### ISSUE TITLE
[BUG] saltenv seems to be ignored by saltutil.sync_modules while called from state

### ISSUE THREAD

**Issue by naqoyqatsi83** [saltstack/salt#64593]
**Description**
I am trying to setup environment separation and I want to be sure that when I am using `staging` saltenv then `_modules` will be used from that saltenv. 

**Setup**
master configuration:
```
root@ubuntu22-3006:~# cat /etc/salt/master.d/file_roots.conf
file_roots:
  base:
    - /srv/salt/production
  staging:
    - /srv/salt/staging/
```
directory structure
```
root@ubuntu22-3006:~# tree /srv/salt/
/srv/salt/
├── production
│   ├── _modules
│   │   └── my_test.py
│   └── test
│       └── init.sls
└── staging
    ├── _modules
    │   └── my_test.py
    └── test
        └── init.sls

6 directories, 4 files
```
mock of execution modules:
```
root@ubuntu22-3006:~# cat /srv/salt/production/_modules/my_test.py
def version():
            return "1.0"

root@ubuntu22-3006:~# cat /srv/salt/staging/_modules/my_test.py
def version():
            return "2.0"
```

mock of states:
``` 
root@ubuntu22-3006:~# cat /srv/salt/production/test/init.sls
{{ sls }}.sync_modules from {{ saltenv }}:
  module.run:
    - name: saltutil.sync_modules
    - saltenv: {{ saltenv }}
    - refresh: True

{{ sls }}.pkg_download:
  module.run:
    - name: my_test.version
    - kwargs:
        saltenv: {{ saltenv }}

root@ubuntu22-3006:~# cat /srv/salt/staging/test/init.sls
{{ sls }}.sync_modules from {{ saltenv }}:
  module.run:
    - name: saltutil.sync_modules
    - saltenv: {{ saltenv }}
    - refresh: True

{{ sls }}.pkg_download:
  module.run:
    - name: my_test.version
    - kwargs:
        saltenv: {{ saltenv }}
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
```
salt -C '*' state.apply test
salt -C '*' state.apply test saltenv=test
```

**Expected behavior**
```
root@ubuntu22-3006:~# salt -C '*' state.apply test
ubuntu22-3006:
----------
          ID: test.sync_modules from base
    Function: module.run
        Name: saltutil.sync_modules
      Result: True
     Comment: Module function saltutil.sync_modules executed
     Started: 16:05:39.439812
    Duration: 107.976 ms
     Changes:
              ----------
              ret:
                  - modules.my_test
----------
          ID: test.pkg_download
    Function: module.run
        Name: my_test.version
      Result: True
     Comment: Module function my_test.version executed
     Started: 16:05:39.548049
    Duration: 2341.92 ms
     Changes:
              ----------
              ret:
                  1.0

Summary for ubuntu22-3006
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:   2.450 s
root@ubuntu22-3006:~# salt -C '*' state.apply test saltenv=staging
ubuntu22-3006:
----------
          ID: test.sync_modules from staging
    Function: module.run
        Name: saltutil.sync_modules
      Result: True
     Comment: Module function saltutil.sync_modules executed
     Started: 16:05:50.302353
    Duration: 93.378 ms
     Changes:
              ----------
              ret:
                  - modules.my_test
----------
          ID: test.pkg_download
    Function: module.run
        Name: my_test.version
      Result: True
     Comment: Module function my_test.version executed
     Started: 16:05:50.395857
    Duration: 1.029 ms
     Changes:
              ----------
              ret:
                  2.0
```

**Screenshots**

Instead of expected output I am getting always synced `_modules` from production.. 
```
root@ubuntu22-3006:~# salt -C '*' state.apply test
ubuntu22-3006:
----------
          ID: test.sync_modules from base
    Function: module.run
        Name: saltutil.sync_modules
      Result: True
     Comment: Module function saltutil.sync_modules executed
     Started: 16:05:39.439812
    Duration: 107.976 ms
     Changes:
              ----------
              ret:
                  - modules.my_test
----------
          ID: test.pkg_download
    Function: module.run
        Name: my_test.version
      Result: True
     Comment: Module function my_test.version executed
     Started: 16:05:39.548049
    Duration: 2341.92 ms
     Changes:
              ----------
              ret:
                  1.0

Summary for ubuntu22-3006
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:   2.450 s
root@ubuntu22-3006:~# salt -C '*' state.apply test saltenv=staging
ubuntu22-3006:
----------
          ID: test.sync_modules from staging
    Function: module.run
        Name: saltutil.sync_modules
      Result: True
     Comment: Module function saltutil.sync_modules executed
     Started: 16:05:50.302353
    Duration: 93.378 ms
     Changes:
              ----------
              ret:                                      <<<===--- saltenv is ignored and base is used, so _modules are not synced from staging.
----------
          ID: test.pkg_download
    Function: module.run
        Name: my_test.version
      Result: True
     Comment: Module function my_test.version executed
     Started: 16:05:50.395857
    Duration: 1.029 ms
     Changes:
              ----------
              ret:
                  1.0                                <<<===--- because it was not synced.. production version is used instead of staging one.

Summary for ubuntu22-3006
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:  94.407 ms
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```
root@ubuntu22-3006:~# salt --versions-report
Salt Version:
          Salt: 3006.1

Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-73-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy
```

</details>

**Additional context**
This was tested also with `3004.2` classic packaging on Ubuntu 22.04 with same results.. 

Maybe I am just doing it wrong and I am not getting idea of environment separation.. but based on what I read in documentation.. I would expect this behavior to be different.. 

Sorry if I am just messing stuff up.. 

Thanks for your time!

**Comment by s0undt3ch** [comment]
The 3004.x versions are no longer supported.

Can you try this scenario with 3006.1 and see if this situation is still present?

**Comment by naqoyqatsi83** [comment]
This **was** tested on `3006.1`.. you can see that also in version report.. I just put note that I've tested that also in `3004.2` and it was present already in that version.

**Comment by OrangeDog** [comment]
> The 3004.x versions are no longer supported.

That's not what the [install guide](https://docs.saltproject.io/salt/install-guide/en/latest/) says.

**Comment by naqoyqatsi83** [comment]
OK.. problem solved on my side.. I was using wrong syntax.. State supposed to be like:

```
root@ubuntu22-3006:/srv/salt# cat staging/test/init.sls
{{ sls }}.sync_modules from {{ saltenv }}:
  module.run:
    - saltutil.sync_modules:
      - saltenv: {{ saltenv }}
      - refresh: True

{{ sls }}.pkg_download:
  module.run:
    - name: my_test.version
    - kwargs:
        saltenv: {{ saltenv }}
```

and output is then exactly what I've expected:
```
root@ubuntu22-3006:/srv/salt# salt -C '*' state.apply test saltenv=base
ubuntu22-3006:
----------
          ID: test.sync_modules from base
    Function: module.run
      Result: True
     Comment: saltutil.sync_modules: []
     Started: 11:34:08.930211
    Duration: 21.006 ms
     Changes:
              ----------
              saltutil.sync_modules:
----------
          ID: test.pkg_download
    Function: module.run
        Name: my_test.version
      Result: True
     Comment: Module function my_test.version executed
     Started: 11:34:08.951331
    Duration: 1.092 ms
     Changes:
              ----------
              ret:
                  1.0

Summary for ubuntu22-3006
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:  22.098 ms


root@ubuntu22-3006:/srv/salt# salt -C '*' state.apply test saltenv=staging
ubuntu22-3006:
----------
          ID: test.sync_modules from staging
    Function: module.run
      Result: True
     Comment: saltutil.sync_modules: ['modules.my_test']
     Started: 11:34:15.114680
    Duration: 24.169 ms
     Changes:
              ----------
              saltutil.sync_modules:
                  - modules.my_test
----------
          ID: test.pkg_download
    Function: module.run
        Name: my_test.version
      Result: True
     Comment: Module function my_test.version executed
     Started: 11:34:15.138990
    Duration: 1.284 ms
     Changes:
              ----------
              ret:
                  2.0

Summary for ubuntu22-3006
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:  25.453 ms
```

I am closing this issue now.. sorry for disturbing.
