### ISSUE TITLE
[BUG] Regression on "file.recurse" state after Salt 3006.0 when dealing with symlinks: Unable to manage file: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by meaksh** [saltstack/salt#64630]
**Description**

We have identified a regression between Salt 3005.1 and Salt 3006.0 version for `file.recurse` state function when dealing with symlinks, leading to a failing state execution with the following error:

```console
#### /tmp/test-path/symlink ####
              Unable to manage file: [Errno 2] No such file or directory: '/tmp/test-path/real_file'
```

**Steps to Reproduce the behavior**

Given an SLS file like at `/srv/salt/test_symlink.sls`:

```console
test_symlink:
  file.recurse:
    - name: /tmp/test-path/
    - source: salt://test_symlink/
    - file_mode: keep
    - keep_symlinks: True
```

And the following structure as part of Salt "file roots":

```console
/srv/salt/test_symlink/
/srv/salt/test_symlink/real_file
/srv/salt/test_symlink/symlink -> real_file (symlink to real_file)
```

Now, when we apply our SLS file, the state will fail:

```console
# salt salttests state.apply test_symlink
salttests:
----------
          ID: test_symlink
    Function: file.recurse
        Name: /tmp/test-path/
      Result: False
     Comment: #### /tmp/test-path/symlink ####
              Unable to manage file: [Errno 2] No such file or directory: '/tmp/test-path/real_file'
     Started: 12:19:19.137984
    Duration: 271.621 ms
     Changes:   
              ----------
              /tmp/test-path/real_file:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
              /tmp/test-path/symlink:
                  ----------
                  new:
                      /tmp/test-path/symlink

Summary for salttests
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time: 271.621 ms
ERROR: Minions returned with non-zero exit code
```

**Expected behavior**
The state should run fine as it was in Salt versions < 3006.0

```console
salttests:
----------
          ID: test_symlink
    Function: file.recurse
        Name: /tmp/test-path/
      Result: True
     Comment: Recursively updated /tmp/test-path/
     Started: 13:02:39.570411
    Duration: 165.118 ms
     Changes:   
              ----------
              /tmp/test-path/real_file:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
              /tmp/test-path/symlink:
                  ----------
                  new:
                      /tmp/test-path/symlink

Summary for salttests
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 165.118 ms
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 21.3
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.18.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 25.1.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: opensuse-leap 15.5 
        locale: UTF-8
       machine: x86_64
       release: 6.3.7-1-default
        system: Linux
       version: openSUSE Leap 15.5 
```
</details>
