### ISSUE TITLE
[BUG] file.managed should support binary files

### ISSUE THREAD

**Issue by dehnert** [saltstack/salt#64633]
**Description**
Currently when a binary `contents` are passed to `file.managed`, the contents become corrupted. I'm not entirely sure of what's going on, but it looks like the bytes get converted to utf-8 and then back to bytes, which might be a lossy process?

**Setup**

I'm using a snippet like:
```
/path/daemon.keytab:
  file.managed:
    - mode: 600
    - contents: !!binary {{keytab_key.replace('\n', '')}}
```

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
daemon.keytab should contain the base64-decoded contents of the `keytab_key` variable

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.11.0
        pygit2: Not Installed
        Python: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 Jammy Jellyfish
        locale: iso8859-1
       machine: x86_64
       release: 5.15.0-71-generic
        system: Linux
       version: Ubuntu 22.04 Jammy Jellyfish

```

The master is running 3005.1.
</details>

**Additional context**
I think this issue was previously fixed by https://github.com/saltstack/salt/pull/30268, and has regressed.

<details><summary>Based on cursory testing, something like this might work:</summary>

```
commit bb6d0a8262b78a92df6e06fb2d93e53d31198d32 (binary)
Author: Alex Dehnert <adehnert@mit.edu>
Date:   Fri Jul 14 01:05:37 2023 -0400

    let file.managed handle binary files

diff --git a/salt/modules/file.py b/salt/modules/file.py
index e8db4a0336..c143983027 100644
--- a/salt/modules/file.py
+++ b/salt/modules/file.py
@@ -6040,7 +6040,10 @@ def manage_file(
                 prefix=salt.utils.files.TEMPFILE_PREFIX, text=True
             )
             with salt.utils.files.fopen(tmp, "wb") as tmp_:
-                if encoding:
+                log.error("contents type=%s", type(contents))
+                if isinstance(contents, bytes):
+                    tmp_.write(contents)
+                elif encoding:
                     if salt.utils.platform.is_windows():
                         contents = os.linesep.join(
                             _splitlines_preserving_trailing_newline(contents)
diff --git a/salt/states/file.py b/salt/states/file.py
index 75b606ddc2..a998011e2a 100644
--- a/salt/states/file.py
+++ b/salt/states/file.py
@@ -2840,8 +2841,11 @@ def managed(

     else:
         use_contents = None
+    log.error("use_contents=%r (%s)", use_contents, type(use_contents))

-    if use_contents is not None:
+    if isinstance(use_contents, bytes) and use_contents:
+        contents = use_contents
+    elif use_contents is not None:
         if not allow_empty and not use_contents:
             if contents_pillar:
                 contents_id = "contents_pillar {}".format(contents_pillar)
```

But I haven't done significant testing and obviously there's style issues there.

</details>

`file.decode` would be great, except it doesn't support setting permissions, limiting the value for secrets.
