### ISSUE TITLE
[BUG] No way to prevent "DeprecationWarning" messages, even with PYTHONWARNINGS="ignore" 

### ISSUE THREAD

**Issue by meaksh** [saltstack/salt#64660]
**Description**
Currently, there is not way for the user to prevent Salt `DeprecationWarnings` messages to be displayed as part of a `salt-call` execution.

Even when `PYTHONWARNINGS=ignore` is set, or the log level is set to `quiet`, with `salt-call -l quiet`, those warning messages are always shown.

This makes it tricky for the user that wants a clean output without those warnings. I think Salt should have a way to silent those messages to be displayed in stderr/stdout.

Some of our initial ideas are:

- Use an environment variable, like generic `PYTHONWARNINGS` that can be set to ignore those warnings.
- Make log level quiet to also prevent those warning messages.

As mentioned, even if we set `PYTHONWARNINGS=ignore`, Salt is explicitely enabling the `DeprecationWarnings` here:

https://github.com/saltstack/salt/blob/master/salt/__init__.py#L15-L23

So questions:
- Would it make sense we only explicitely enable them when `PYTHONWARNINGS` environment variable is unset?
- What do you think?

Thanks in advance!

----

**Setup**
An easy way to trigger this behavior on Salt 3006.1, having `m2crypto` installed:

Given the following example SLS, that makes use of deprecated `x509` state module (which triggers a `DeprecationWarning` message), something like this:

```
/tmp/foobar:
  x509.foobar:
    - text: "foobar"
```

Now, when executing `PYTHONWARNINGS=ignore salt-call -l quiet` to apply the above SLS, the `DeprecationWarning` is always displayed:

```console
# PYTHONWARNINGS=ignore salt-call --local --out json -l quiet state.apply test_x509
/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/states/x509.py:212: DeprecationWarning: The x509 modules are deprecated. Please migrate to the replacement modules (x509_v2). They are the default from Salt 3008 (Argon) onwards.
  salt.utils.versions.warn_until(
{
    "local": {
        "x509_|-/tmp/foobar_|-/tmp/foobar_|-foobar": {
            "result": false,
            "name": "/tmp/foobar",
            "changes": {},
            "comment": "State 'x509.foobar' was not found in SLS 'test_x509'\nReason: 'x509.foobar' is not available.\n",
            "__run_num__": 0
        }
    }
}
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
# salt --versions-report
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.5
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 21.3
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.18.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0.1
         PyZMQ: 25.1.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: opensuse 15.5 
        locale: UTF-8
       machine: x86_64
       release: 6.3.7-1-default
        system: Linux
       version: openSUSE Leap 15.5 
```
</details>
