### ISSUE TITLE
[BUG] salt-pip does not install executable scripts from pip packages

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#64662]
**Description**
salt-pip does not install executable scripts from pip packages. For example, the salt-pepper package should install the `pepper` script in `/opt/saltstack/salt/extras-3.10/bin`, however it is not installed.

```
$ salt-pip freeze | grep pepper
salt-pepper==0.7.6
$ ls -alh /opt/saltstack/salt/extras-3.10/bin/
total 8.0K
drwxr-xr-x.  2 root root   19 Jun  6 20:30 .
drwxr-xr-x. 60 salt salt 4.0K Jul 17 21:06 ..
-rwxr-xr-x.  1 root root  284 Jun  6 20:30 yappi
```

**Setup**
Install relenv version of Salt (3006.1)
salt-pip install salt-pepper

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Install relenv version of Salt (3006.1)
salt-pip install salt-pepper

**Expected behavior**
`pepper` script should be installed in `/opt/saltstack/salt/extras-3.10/bin`

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
              Salt: 3006.1

Python Version:
            Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]

Dependency Versions:
              cffi: 1.14.6
          cherrypy: unknown
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.1.2
           libgit2: 1.5.0
      looseversion: 1.0.2
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 22.0
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: 1.11.1
      python-gnupg: 0.4.8
            PyYAML: 5.4.1
             PyZMQ: 23.2.0
            relenv: 0.12.3
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4

Salt Extensions:
 saltext.bitwarden: 0.0.1b14
    saltext.vmware: 23.4.4.0rc1

System Versions:
              dist: almalinux 8.7 Stone Smilodon
            locale: utf-8
           machine: x86_64
           release: 4.18.0-425.19.2.el8_7.x86_64
            system: Linux
           version: AlmaLinux 8.7 Stone Smilodon
```
</details>

**Additional context**
Encountering the same issue with the `napalm` package as well.
