### ISSUE TITLE
[E2E Test] Add E2E test for using external pillars

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#64690]
Add E2E test for the following scenario:

1. Setup a master with the following configuration:

```
ext_pillar:
  - cmd_json: 'echo {\"arg\":\"value\"}'
  - http_json:
      url: http://localhost/%s.html
```

2. Setup a webserver (In the test suite you can use the webserver class from tests/support/helpers.py
3. Add an html page with the name of test minion. For example: `minion.html`. And the contents of the html file are:

```
{"minion": "supersecret"}
```

4. Create SLS File with the following contents:

```
{% set minion_id = grains.get("id") %}
{% set password = pillar.get(minion_id) %}
{% set arg = pillar.get("arg") %}

add_secret:
  file.managed:
    - name: /tmp/conf_file
    - contents: |
        target: {{ minion_id }}
        password: {{ password }}
        args: {{ arg }}
```

5. Run the state and ensure the contents of the file are added correctly.

```
(py-3.10)  ch3ll@megan-precision5550  ~/git/salt   add_pillar_docs ±  salt 'poc-minion' state.apply ext_pillar
poc-minion:
----------
          ID: add_secret
    Function: file.managed
        Name: /tmp/conf_file
      Result: True
     Comment: File /tmp/conf_file is in the correct state
     Started: 12:24:46.662342
    Duration: 20.081 ms
     Changes:   

Summary for poc-minion
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  20.081 ms
(py-3.10)  ch3ll@megan-precision5550  ~/git/salt   add_pillar_docs ±  cat /tmp/conf_file 
target: poc-minion
password: supersecret
args: value
```

6. Update the external pillar data by updating the minions.html site with a new password.

```
{"poc-minion": "new-supersecret"}
```

7. Run the state again and ensure the contents of the file have changed correctly.

```
(py-3.10)  ch3ll@megan-precision5550  ~/git/salt   add_pillar_docs ±  salt 'poc-minion' state.apply ext_pillar      
poc-minion:
----------
          ID: add_secret
    Function: file.managed
        Name: /tmp/conf_file
      Result: True
     Comment: File /tmp/conf_file updated
     Started: 12:25:50.439871
    Duration: 22.172 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,3 +1,3 @@
                   target: poc-minion
                  -password: supersecret
                  +password: new-supersecret
                   args: value

Summary for poc-minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  22.172 ms
```

```
(py-3.10)  ch3ll@megan-precision5550  ~/git/salt   add_pillar_docs ±  cat /tmp/conf_file                            
target: poc-minion
password: new-supersecret
args: value
```
