### ISSUE TITLE
[E2E Test] Add E2E test for using orchestration and a reactor

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#64692]
Add E2E test for the following scenario:

1. Add orchestration and normal sls state:

/srv/salt/orch.sls:

```
run_user_state:
  salt.state:
    - tgt: poc-minion 
    - sls:
      - user

orch1_complete:
  salt.runner:
    - name: event.send
    - tag: my_event/orch1/complete
    - data:
        foo: bar
    - require:
      - salt: run_user_state
```

/srv/salt/user.sls

```
testuser:
  user.present
```

2. Add reactor Salt master configuration

/etc/salt/master.d/reactor.conf

```
reactor:
  - "my_event/orch1/complete":
    - /srv/salt/reactor.sls
```

3. Add reactor sls file

/srv/salt/reactor.sls

```
add_file:
  local.state.single:
    - tgt: "*"
    - args:
        - fun: file.managed
        - name: /tmp/path
        - contents: "test content"

add_file2_initial:
  local.file.touch:
    - tgt: "*"
    - args:
      - name: "/tmp/path2"

add_file2:
  local.file.append:
    - tgt: "*"
    - args:
      - path: /tmp/path2
      - args: "test2 content"
```

4. Run the orchestration file

`salt-run state.orchestrate orch`

5. Confirm that both /tmp/path and /tmp/path2 files where created with the correct contents

```
(py-3.10)  ch3ll@megan-precision5550  ~/git/salt   add_pillar_docs  cat /tmp/path2 /tmp/path               
test2 content
test content
```
