### ISSUE TITLE
[BUG] File.symlink doesn't work on salt-minion v3006

### ISSUE THREAD

**Issue by cortex1909** [saltstack/salt#64726]
**Description**
`file.symlink` doesn't work with salt-minion 3006.1-0. Downgrading to salt-minion v3005 works.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x ] VM on vSphere
- [x ] onedir packaging

**Steps to Reproduce the behavior**
Apply salt to a host with salt-minion v3006 with this state:
```
/etc/opt/hpremote/registration:
  file.symlink:
    - target: /tmp/rgregistration
    - force: True
```
It will show you this error
```
ID: /etc/opt/hpremote/registration
    Function: file.symlink
      Result: False
     Comment: Unable to create new symlink /etc/opt/hpremote/registration -> /tmp/rgregistration: [Errno 21] Is a directory: '/etc/opt/hpremote/registration'
     Started: 15:49:08.107263
    Duration: 315.236 ms
     Changes:   
```

**Expected behavior**
On v3005 same salt state gives this output
```
ID: /etc/opt/hpremote/registration
    Function: file.symlink
      Result: True
     Comment: Created new symlink /etc/opt/hpremote/registration -> /tmp/rgregistration
     Started: 16:00:07.377859
    Duration: 5.919 ms
     Changes:   
              ----------
              new:
                  /etc/opt/hpremote/registration
```

**Versions Report**
<details><summary>salt --versions-report</summary>
Working version of v3005:
`Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.9.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
`
Non-working version of v3006
`Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: centos 7.9.2009 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7.9.2009 Core
`</details>
