### ISSUE TITLE
[BUG]  Windows 10 salt-minion installer via pkg.install leaves windows salt-minion service in unusable state

### ISSUE THREAD

**Issue by tysonnorris** [saltstack/salt#64925]
I am trying to upgrade windows 10 salt minions running version 3003.4 to 3005.1 (not using onedir or 3006 yet)
salt-master is 3005.1

I run upgrades using:
salt <minion> pkg.install salt-minion-py3 version=3005.1-5

installer scheduled task completes successfully:
![image](https://github.com/saltstack/salt/assets/1638396/cda8ba64-763c-4790-af6c-795123539bff)

Service is left as "RUNNING" but "startup disabled", and salt-minion is not actually running (no logs, no connection available):
![image](https://github.com/saltstack/salt/assets/1638396/d718eaf1-0094-4c47-a09c-29a2a482c58e)

Restarting service (which is not actually running anyhow) produces an error, then removes the service completely:
![image](https://github.com/saltstack/salt/assets/1638396/b01c3ddd-32a1-432e-9fcf-db4c26af0887)

If I download the same installer (Salt-Minion-3005.1-5-Py3-AMD64-Setup.exe) and run manually:
![image](https://github.com/saltstack/salt/assets/1638396/c64e2f12-76bb-46d4-8d2f-7372ca6e8f1e)

Then the service starts fine and has "startup: automatic"
![image](https://github.com/saltstack/salt/assets/1638396/665e8498-b12b-4bea-9cc2-5b93e95d7f6b)

This version uses the following config for pkg.install: 
```
    install_flags: '/S'
    uninstaller: '{{ install_dir }}\uninst.exe'
    uninstall_flags: '/S'
    msiexec: False
    use_scheduler: True
    reboot: False
```

**Comment by twangboy** [comment]
I installed ``3003.4-1`` on a Windows 10 Machine:
```
(venv) PS C:\src\salt> salt \* test.versions
dev15:
    Salt Version:
              Salt: 3003.4

    Dependency Versions:
              cffi: 1.14.5
          cherrypy: 18.6.0
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.5
         gitpython: 3.1.13
            Jinja2: 2.11.3
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.4
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.20
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
      python-gnupg: 0.4.6
            PyYAML: 5.4.1
             PyZMQ: 18.0.1
             smmap: 3.0.4
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.1

    System Versions:
              dist:
            locale: cp1252
           machine: AMD64
           release: 10
            system: Windows
           version: 10 10.0.19041 SP0
```

I generate the winrepo database:
```
> salt \* pkg.refresh_db
dev15:
    ----------
    failed:
        0
    success:
        307
    total:
        307
```

I upgrade to version 3005.1-5:
```
> salt \* pkg.install salt-minion-py3 version=3005.1-5
dev15:
    ----------
    salt-minion-py3:
        ----------
        install status:
            task started
```

I watch the master log for minion reauth:
```
[DEBUG   ] Sending event: tag = salt/auth; data = {'result': True, 'act': 'accept', 'id': 'dev15', 'pub': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjigV55Fudbgh8uSpJa3K\n86f6d9AvujfyoJQWWkH9HJgf2oqI3QeLFt/YpjoBY8
YirRp+rwcnY1pbbvqxkr3s\nrrD4dXns3ua/vCHDw65UyViVjDPSpBdX9umX+oDvfRs4Lj5i7AlL4kO4q0aU7Paz\nQ+M4RXLVVXXL5AWLiLT5xFCNzaxgzz9huZSpVY2gGhkNYyG0oa0aJp3Tyrjh0Yez\nwNL5xB7AmFltlO4o5v6Gm6uIGYmAuH/t6WqmfY13PyiNnCrzi2YoO+1a156jS/vz\nCCpOi6JkzudDTBy7MFOcN
6Fa249uftLOIAa96zfN3Xj4q0PRlx6Y84x6+z6QVhcK\nQQIDAQAB\n-----END PUBLIC KEY-----', '_stamp': '2023-08-08T20:37:57.260611'}
```

The installation is completed and reconnected to the master. I get the version:
```
(venv) PS C:\src\salt> salt \* test.version
dev15:
    3005.1
```

I install 3006.1:
```
> salt \* pkg.install salt-minion-py3 version=3006.1
dev15:
    ----------
    salt-minion-py3:
        ----------
        install status:
            task started
```

I wait for the reauth to come in... then get the version:
```
> salt \* test.version
dev15:
    3006.1
```

I am unable to reproduce this. The minion process may still be running or doesn't shut down properly, maintaining a lock on some of the files in the installation directory. This would cause the uninstaller to fail to remove everything in the `c:\salt\bin` directory. This would probably conflict with the new installation. I think we're seeing something similar here:

https://github.com/saltstack/salt/issues/64618

But I can't reproduce that either
