### ISSUE TITLE
[BUG] After upgrade to 3005.2, failure to check out branch for gitfs pillar

### ISSUE THREAD

**Issue by anandb-ripencc** [saltstack/salt#64999]
**Description**
A minion is unable to access pillar data from an alternative branch in git. This was working with 3005.1, but broke after upgrade to 3005.2

**Setup**
CentOS 7 salt master, configured with git repos for formulas and pillar data.

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Master config:
```
ext_pillar:
  - git:
    - __env__ https://gitlab/pillar-dns.git
    - master  https://gitlab/ssl-certs.git
  - gitstack:
    - master  https://gitlab/ssl-certs.git:
      - stack: stack.cfg
```

Create a new branch called `testing` in `pillar-dns.git` repo, and add some pillar data to it. On a minion, run `salt-call pillar.data pillarenv=testing`

**Expected behavior**
The new data should be visible in the output of the salt call on the minion.

**Screenshots**
Not applicable.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.2

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.32
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.17 (main, Aug  4 2023, 19:59:44)
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 7 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.92.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Additional context**
