### ISSUE TITLE
[BUG] After upgrading to 3006.2 gitfs states 'remote ref does not exist' for ext_pillar

### ISSUE THREAD

**Issue by jonny08152** [saltstack/salt#65002]
**Description**
After upgrading our salt-masters from 3006.1 to 3006.2 the master is unable to checkout our ext_pillar git with the following error:

~~~
[ERROR   ] Failed to checkout master from git_pillar remote '__env__ https://gitlab.com/my/salt-pillar.git': remote ref does not exist
~~~

Downgrading the salt-master, salt-minion and salt packages back to 3006.1 immediately solves the issue.

**Setup**

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

The masters run on a CentOS 9 Stream machine with the latest patches (see below).

**Steps to Reproduce the behavior**
 
This is the snipped from the master conf regarding the ext_pillar that causes the issue:
~~~yaml
ext_pillar:
  - git:
    - __env__ https://gitlab.com/my/salt-pillar.git:
      - root: .
      - user: gitlab-deploy-token
      - password: **********
      - fallback: master
~~~

Running the master in debug mode prints the following:
~~~
salt-master[691168]: [DEBUG   ] Current fetch URL for git_pillar remote '__env__ https://gitlab.com/my/salt-pillar.git': https://gitlab.com/my/salt-pillar.git (desired: https://gitlab.com/my/salt-pillar.git)
salt-master[691168]: [DEBUG   ] Current refspecs for git_pillar remote '__env__ https://gitlab.com/my/salt-pillar.git': ['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*'] (desired: ['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*'])
salt-master[691168]: [DEBUG   ] Current http.sslVerify for git_pillar remote '__env__ https://gitlab.com/my/salt-pillar.git': true (desired: true)
salt-master[691168]: [ERROR   ] Failed to checkout master from git_pillar remote '__env__ https://gitlab.com/my/salt-pillar.git': remote ref does not exist
~~~

The error message originates from [this line of code](https://github.com/saltstack/salt/blob/8f750fa7ae115c48c16ca03ef3f16e4ba76f921c/salt/utils/gitfs.py#L1799C18-L1799C18). Debugging showed the problem to be that there are no references retrieved at [this point](https://github.com/saltstack/salt/blob/8f750fa7ae115c48c16ca03ef3f16e4ba76f921c/salt/utils/gitfs.py#L1632C11-L1632C11) and such the `refs` list being empty.

We also reference other repositories in the ext_pillar block like this and they work fine.
~~~yaml
  - git:
    - main https://gitlab.com/my-other/salt-pillar.git:
      - root: .
      - user: other-pillars
      - password: *********
      - env: onpremises
~~~

**Expected behavior**
We expect the master to checkout the pillar repository without errors like in version 3006.1

**Versions Report**
<details><summary>salt --versions-report</summary>
Masters and Minions have the same version and also run on similarly configured VMs (same OS).

```yaml
Salt Version:
          Salt: 3006.2

Python Version:
        Python: 3.10.12 (main, Aug  3 2023, 21:47:10) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: 1.6.4
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.12.2
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 9
        locale: utf-8
       machine: x86_64
       release: 5.14.0-331.el9.x86_64
        system: Linux
       version: CentOS Stream 9
```
</details>
