### ISSUE TITLE
[BUG] Accessing vault pillar fails with onedir 3006

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [saltstack/salt#65000]
**Description**
The onedir salt-master package has no access to the system CA bundle.
We're using an on-prem vault instance for pillar data with a custom SSL cert - signed by our own CA.
This CA is trusted in the system... and in the systems python - but not in the bundled python.

**Setup**
The Salt-Master is installed on a VM with a lot of salt-minions around the company.

Sensitive pillar data is loaded from a hashicorp vault instance.

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
`salt machine state.apply`

**Expected behavior**
Highstate should be applied.

**Error**
```
ERROR: Minions returned with non-zero exit code
machine:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Failed to load ext_pillar vault: {'error': "HTTPSConnectionPool(host='vault', port=443): Max retries exceeded with url: /v1/auth/approle/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))"}
----------
    Failed to load ext_pillar vault: {'error': "HTTPSConnectionPool(host='vault', port=443): Max retries exceeded with url: /v1/auth/approle/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))"}
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.2

Python Version:
        Python: 3.10.12 (main, Aug  3 2023, 21:47:10) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-24-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**
Temporary workaround only necessary on the salt-master (confirm pls?):
```bash
rm /opt/saltstack/salt/lib/python3.10/site-packages/certifi/cacert.pem
ln -s /etc/ssl/certs/ca-certificates.crt /opt/saltstack/salt/lib/python3.10/site-packages/certifi/cacert.pem
```
