### ISSUE TITLE
[FEATURE REQUEST] `alwaysunless` and `alwaysif` requisites

### ISSUE THREAD

**Issue by maminson** [saltstack/salt#65022]
**Is your feature request related to a problem? Please describe.**
Requisites that guarantee that a state will run under certain conditions don't exist, in particular with use of the `onchanges` and `prereq` requisites.

**Describe the solution you'd like**
The implementation of `alwaysunless` and `alwaysif` requisites, mutually exclusive with `unless` and `onlyif`:
 - `alwaysunless`: specifies that a state will always run when any of the specified commands return `False`, operating as NAND.
 - `alwaysif`: specifies that if each command listed in `alwaysif` returns `True`, then the state is always run. If any of the specified commands return `False`, the state is not guaranteed to run.

For further clarification, here's a truth table, the left side describing the scenario and the right side showing if a state with the given requisite will run:
| `onchanges`/`prereq` is `True` | Requisite Command is `True` | | `unless` | `onlyif` | `alwaysunless` | `alwaysif` |
| :---: | :---: | --- | :---: | :---: | :---: | :---: |
| ❌ | ❌ | | ❌ | ❌ | ✅ | ❌ |
| ✅ | ❌ | | ✅ | ❌ | ✅ | ✅ |
| ❌ | ✅ | | ❌ | ❌ | ❌ | ✅ |
| ✅ | ✅ | | ❌ | ✅ | ✅ | ✅ |

If implemented, these requisites could be used like so:
```yaml
/path/to/isofiles:
  file.recurse:
    - source: salt://isofiles

mkisofs -rJo /path/to/iso /path/to/isofiles:
  cmd.run:
    - alwaysunless:
      - fun: file.file_exists
        path: /path/to/iso
    - onchanges:
      - /path/to/isofiles
```

**Describe alternatives you've considered**
An existing workaround is the use of additional states:
```yaml
/path/to/isofiles:
  file.recurse:
    - source: salt://isofiles

iso created:
  file.managed:
    - name: /path/to/iso
  cmd.run:
    - name: mkisofs -rJo /path/to/iso /path/to/isofiles
    - onchanges:
      - /path/to/isofiles
      - file: iso created
```
While this could be an argument against the `alwaysunless` and `alwaysif` requisites, similar alternatives exist for `unless` and `onlyif` as well, so their existence suggests that `alwaysunless` and `alwaysif` should exist too.

**Comment by OrangeDog** [comment]
It's not clear what you want your example to do. If you want the ISO to always exist and have the latest contents, and not re-create if it hasn't changed:

```yaml
/path/to/isofiles:
  file.recurse:
    - source: salt://isofiles

mkisofs -rJo /path/to/iso /path/to/isofiles:
  cmd.run:
    - creates: /path/to/iso
    - watch:
      - /path/to/isofiles
```

I'm not sure where the requisite returning `False` comes into it, but `onfail` is what handles that.

Wanting to `always` run the next thing even if a requisite fails is very unlikely, and probably means there shouldn't be a requisite in the first place. You could use `order` if an ordering is still needed in that case, or e.g. suppress the failure of a `cmd.run` with `success_retcodes` etc.

In any case, such semantics are entirely separate from `unless`/`onlyif`. If a feature really is missing, it should not be added in this form.
