### ISSUE TITLE
[BUG] Salt cannot apply schedule with salt-minion off/stopped

### ISSUE THREAD

**Issue by Adam-Zvolanek** [saltstack/salt#65033]
**Description**

Setting up a schedule while the minion is not running gives an error "Failed to add job X to schedule.".

Error logging to be more verbose, specifically stating either in the docs or in the error that the minion needs to be running before a schedule can be added.

**Setup**
Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [X] VM running on a cloud service, please be explicit and add details: Amazon WorkSpaces
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

- Disable salt-minion, `systemctl stop salt-minion`
- Add anything to the schedule, e.g. with `salt-call schedule.add foo`

Or as a state:

```yaml
schedule:
  schedule.present:
    - function: state.highstate
    - job_kwargs:
        saltenv: env1
    - cron: '30 * * * 1-5'
    - splay: 900
```

**Expected behavior**

The schedule should be added, or a descriptive reasoning as to why it couldn't be added should be returned. Configure the schedule (in /etc/salt/minion.d/_schedule.conf) without requiring the minion to be running.

**Versions Report**

```yaml
Salt Version:
          Salt: 3006.2
 
Python Version:
        Python: 3.10.12
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: amzn 2
        locale: utf-8
       machine: x86_64
       release: 5.15.amzn2.x86_64
        system: Linux
       version: Amazon Linux 2
```
</details>
