### ISSUE TITLE
Setting up a highstate schedule at start up

### ISSUE THREAD

**Issue by Ikkyto** [saltstack/salt#65041]
Setting up a highstate schedule at startup.

I have checked the salt state doc, the cron job seems to be running, but the start up schedule is not running. I have tried different ways to get salt to apply to the host at reboot but haven't had any luck. We're currently using 3006.2.

```
schedule:
  highstate:
    function: state.highstate
    cron: '*/15 * * * *'
    startup_states: highstate
```

This is what the sls file looks like.
