### ISSUE TITLE
[BUG] Target ignored in orchestrator state?

### ISSUE THREAD

**Issue by edivita** [saltstack/salt#65043]
**Description**
I have 2 environment defined in my salt system, base (not used) and env-801. When I try to execute a salt orchestrator state from the environment env-801, the state complete its execution only in the salt master node doing nothing (as expected) but do not execute the state in the other minion. 
This is the command I run: 
`salt-run state.orchestrate k3s.install  --state-output=mixed saltenv=env-801 pillarenv=env-801 -l info `

It looks something like this old issue: https://github.com/saltstack/salt/issues/32318 
The workaround proposed in that is not applicable in my case because the orchestrator perform different operation in multiple nodes (which are minions)   

To understand better the problem I added the following lines in the k3s/install.sls file to see what pillar I have: 

 ```
{% set pillar_test = salt['pillar.items']() %}
{% do salt['log.warning'](pillar_test) %}
``` 

and I see all the expected pillar, but for some reason the state are not executed on all nodes. 

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
This is the content of the orchestration file orch/k3s/install.sls
```
{% from "k3s/map.jinja" import k3s_vars, k3s_nodes, use_registry, config %}

{% set pillar_test = salt['pillar.items']() %}
{% do salt['log.warning'](pillar_test) %}

{% if ('k3s' in config.roles) %}

# execute it only in cluster, following the node order
{% if not k3s_vars.is_single_node %}
  {% for node in k3s_nodes %}
keepalived_{{node}}:
  salt.state:
    - tgt: {{node}}
    - sls:
      - orch/k3s/1-keepalived
  {% endfor %}
{% endif %}

k3s_bootstrap_node:
  salt.state:
    - tgt: {{k3s_vars.init_node}}
    - sls:
      - orch/k3s/2-k3s_master_init
    - failhard: True

{% for node in k3s_nodes %}
k3s_all_{{node}}:
  salt.state:
    - tgt: {{node}}
    - sls:
      - orch/k3s/3-k3s_all
    - failhard: True
{% endfor %}

``` 

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (VirtualBox)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 8.7 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 4.18.0-425.3.1.el8.x86_64
        system: Linux
       version: Rocky Linux 8.7 Green Obsidian
 
```
</details>

Could someonw help me understand if this is a bug, a know issue or something else I'm doing wrong?
