### ISSUE TITLE
[BUG][SALT][CLOUD][OPTIONS] There was a query error: list index out of range

### ISSUE THREAD

**Issue by khalid-lemghari** [saltstack/salt#65064]
**Description**
Hello,

I have provisioned the salt-master on Azure using salt-cloud only from my laptop, and I'm trying to provision a windows machine. But I get the error bellow: 
```bash 
There was a query error: list index out of range
```

**Setup**
- Package installed on my laptop : 
```bash
salt-cloud-3006.2
salt-common-3006.2
```

- Package installed on salt-master : 
```bash
salt-common-3006.2
salt-master-3006.2
salt-cloud-3006.2
salt-minion-3006.2
```

**Steps to Reproduce the behavior**

```yaml
---
wazr:
  - w2k19:
      allocate_public_ip: false
      dns_servers:
        - redacted
        - redacted
        - redacted
      grains:
        application: dc
        billing_entity: redacted
        creator: salt
        domain_name: unknown
        domain_join: false
        environment: staging
        eotp: redacted
        host_name: w2k19
        operational_entity: redacted
        referent: unknown
      image: MicrosoftWindowsServer|WindowsServer|2019-Datacenter|latest
      make_master: false
      minion:
        master: 10.0.0.4
        startup_states: highstate
      size: Standard_D2s_v3
      tag:
        application: dc
        billing_entity: redacted
        creator: salt
        domain_name: unknown
        domain_join: "false"
        environment: staging
        eotp: redacted
        host_name: w2k19
        operational_entity: redacted
      use_winrm: false
      volumes:
        - caching: ReadWrite
          disk_size_gb: 20
          managed_disk:
            storage_account_type: Standard_LRS
      win_deploy_auth_retries: 10
      win_deploy_auth_retry_delay: 1
```

**Versions Report**
<details><summary>salt-cloud -V</summary>

```yaml
Salt Version:
            Salt: 3006.2
 
Python Version:
          Python: 3.10.12 (main, Aug  3 2023, 21:47:10) [GCC 11.2.0]
 
Dependency Versions:
 Apache Libcloud: 3.8.0
            cffi: 1.14.6
        cherrypy: 18.6.1
        dateutil: 2.8.1
       docker-py: 1.10.6
           gitdb: 4.0.10
       gitpython: 3.1.32
          Jinja2: 3.1.2
         libgit2: 1.6.4
    looseversion: 1.0.2
        M2Crypto: 0.39.0
            Mako: 1.2.4
         msgpack: 1.0.2
    msgpack-pure: Not Installed
    mysql-python: Not Installed
       packaging: 22.0
       pycparser: 2.21
        pycrypto: 2.6.1
    pycryptodome: 3.9.8
          pygit2: 1.12.2
    python-gnupg: 0.4.8
          PyYAML: 6.0.1
           PyZMQ: 23.2.0
          relenv: 0.13.3
           smmap: 5.0.0
         timelib: 0.2.4
         Tornado: 4.5.3
             ZMQ: 4.3.4
 
System Versions:
            dist: ubuntu 22.04.3 jammy
          locale: utf-8
         machine: x86_64
         release: 6.2.0-32-generic
          system: Linux
         version: Ubuntu 22.04.3 jammy
```
</details>

**Additional context**
<details><summary>/opt/saltstack/salt/salt-pip list</summary>

```bash
Package            Version
------------------ ---------
apache-libcloud    3.8.0
certifi            2023.7.22
cffi               1.14.6
charset-normalizer 3.2.0
cheroot            8.5.2
CherryPy           18.6.1
configparser       6.0.0
contextvars        2.4
cryptography       41.0.3
distro             1.5.0
docker-py          1.10.6
docker-pycreds     0.4.0
gitdb              4.0.10
GitPython          3.1.32
idna               2.8
immutables         0.15
importlib-metadata 6.0.0
jaraco.classes     3.2.1
jaraco.collections 3.4.0
jaraco.functools   2.0
jaraco.text        3.5.1
Jinja2             3.1.2
jmespath           1.0.1
looseversion       1.0.2
M2Crypto           0.39.0
Mako               1.2.4
MarkupSafe         2.1.2
more-itertools     5.0.0
msgpack            1.0.2
msgpack-pure       0.1.3
packaging          22.0
pip                22.3.1
portend            2.4
psutil             5.8.0
pycparser          2.21
pycrypto           2.6.1
pycryptodomex      3.9.8
pygit2             1.12.2
pyOpenSSL          23.2.0
pypsexec           0.3.0
pyspnego           0.9.1
python-dateutil    2.8.1
python-gnupg       0.4.8
pytz               2022.1
PyYAML             6.0.1
pyzmq              23.2.0
relenv             0.13.3
requests           2.31.0
rpm-vercmp         0.1.2
salt               3006.2
setproctitle       1.3.2
setuptools         65.7.0
six                1.16.0
smbprotocol        1.10.1
smmap              5.0.0
tempora            4.1.1
timelib            0.2.5
urllib3            1.26.6
websocket-client   1.6.2
wheel              0.41.1
zc.lockfile        1.4
zipp               3.6.0
```
</details>
