### ISSUE TITLE
[DOCS] Inconsistent documentation of cloud options

### ISSUE THREAD

**Issue by khalid-lemghari** [saltstack/salt#65063]
**Description**
"Salt Cloud Doc" describe **ssh_interface** as option to use public or private IP for deploy script, while "Salt Cloud Code" check **bootstrap_interface** option to create a windows-like VM. Moreover, this option is not documented!

So, what's the difference between **bootstrap_interface**, **ssh_interface**, and **win_interface**?

**Suggested Fix**
Find out the truth and correct them.

**Type of documentation**
Salt documentation

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/cloud
https://github.com/saltstack/salt/blob/3006.x/salt/cloud/clouds/azurearm.py

**Additional context**
```yaml
---
wazr:
  - w2k19:
      allocate_public_ip: false
      dns_servers:
        - redacted
        - redacted
        - redacted
      grains:
        application: dc
        billing_entity: redacted
        creator: salt
        domain_name: unknown
        domain_join: false
        environment: staging
        eotp: redacted
        host_name: w2k19
        operational_entity: redacted
        referent: unknown
      image: MicrosoftWindowsServer|WindowsServer|2019-Datacenter|latest
      make_master: false
      minion:
        master: 10.0.0.4
        startup_states: highstate
      size: Standard_D2s_v3
      tag:
        application: dc
        billing_entity: redacted
        creator: salt
        domain_name: unknown
        domain_join: "false"
        environment: staging
        eotp: redacted
        host_name: w2k19
        operational_entity: redacted
      use_winrm: false
      volumes:
        - caching: ReadWrite
          disk_size_gb: 20
          managed_disk:
            storage_account_type: Standard_LRS
      win_deploy_auth_retries: 10
      win_deploy_auth_retry_delay: 1
```
