### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kamal-shaker** [saltstack/salt#65079]
**Description**
archive.extracted doesn't seem to respect require: when testing.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ x ] on-prem machine

**Steps to Reproduce the behavior**

The below code:

```
node_exporter:
  user.present:
    - system: True

extract_node_exporter:
  archive.extracted:
    - name: '/opt/node_exporter/node_exporter-{{ node_exporter.version_id }}.linux-amd64'
    - source: '{{ node_exporter.source }}'
    - source_hash: '{{ node_exporter.source_hash }}'
    - user: node_exporter
    - group: node_exporter
    - keep_source: True
    - options: --strip-components=1
    - enforce_toplevel: False
    - require:
      - user: node_exporter

/opt/node_exporter:
  file.directory:
    - user: node_exporter
    - mode: "0755"
    - require:
      - user: node_exporter
```

Running running like this: salt-call --force-color   --id="cart-68-54-5a-88-dc-xx" state.apply monitoring.agent test=True 

Give the below error: 

```
----------
          ID: extract_node_exporter
    Function: archive.extracted
        Name: /opt/node_exporter/node_exporter-1.5.0.linux-amd64
      Result: False
     Comment: User node_exporter does not exist
     Started: 04:44:23.395810
    Duration: 8.599 ms
     Changes:

```

The directory works as expected:
```
          ID: /opt/node_exporter
    Function: file.directory
      Result: None
     Comment: The following files will be changed:
              /opt/node_exporter: directory - new
     Started: 04:45:51.035983
    Duration: 2.396 ms
     Changes:
              ----------
              /opt/node_exporter:
                  ----------
                  directory:
                      new

```

**Expected behavior**
The above should pass a run with "test=True" set.  It works fine without the "test=True" and creates the user before the archive is extracted.

**Screenshots**

**Versions Report**

root@srops-bsign-be-dev-salt-client-wwtj:~# salt-call --versions-report
Salt Version:
          Salt: 3005.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, May 26 2023, 14:05:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1038-gcp
        system: Linux
       version: Ubuntu 20.04 focal

```yaml
PASTE HERE
```
</details>

**Additional context**
