### ISSUE TITLE
Expand more path in configuration

### ISSUE THREAD

**Issue by baby-gnu** [saltstack/salt#65094]
**Is your feature request related to a problem? Please describe.**

Sharing my [`salt-ssh` personal configuration](https://gitlab.mim-libre.fr/-/snippets/13) can't be done easily since several configuration path do not support

- tilde (`~`) expansion
- path relative to `root_dir`

[Another scenario](https://github.com/saltstack/salt/issues/14613#issuecomment-413528170) is to use salt as a master-less provisionning for cloud images where I can't use `salt-ssh` (in a chroot for example): I would like to be able to mount a directory in my chroot and make the provisionning working with `salt-call`.

**Describe the solution you'd like**

I would like to be able to define several configuration relative to my home directory using tilde or even path relative to `root_dir`:

<details><summary><code>~/.salt/Saltfile</code></summary>

``` yaml
salt-ssh:
  config_dir: ~/.salt
```

</details>

<details><summary><code>~/.salt/master</code></summary>

```yaml
root_dir: ~/.salt

file_roots:
   base:
     - ~/.salt/srv/salt/

pillar_roots:
  base:
    - ./srv/pillar/ # Is the same as ~/.salt/srv/pillar

ext_pillar:
  # https://docs.saltproject.io/en/latest/ref/pillar/all/salt.pillar.stack.html
  - stack:
    - ~/.salt/srv/pillar/common.cfg
    # `roles.cfg` can use data from `common.cfg` through `stack.get()`
    - ~/.salt/srv/pillar/roles.cfg
```
</details>

**Describe alternatives you've considered**

No real alternative to this, only `sed` the configuration files.

**Additional context**

This is a reopen of #14613 because it was closed for old and python2 reasons but it still apply, so reset age counter ;-)

It's still related to #51192.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.
