### ISSUE TITLE
[BUG] 2019.2.2 salt-minion severe memory leak on centos7.9 after yum-update 

### ISSUE THREAD

**Issue by grishatsuker** [saltstack/salt#65109]
**Description**
I am using a salt-minion version `salt==2019.2.2` and due to some other issues in the VM - we-rebuilt the image with up to date packages and kernel upgrade for centos 7.9. 

Ever since we use the image we saw that for every command the salt-minion receives, the process memory increases over time, which finally triggers OOM Killer and a kernel panic crash.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [x] Running on top of openstack nova

- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
1. Install on a VM salt-minion as a service on centos7.9.
2. From master, run `while true; do salt <monion_id> cmd.run 'echo hello'; sleep2; done`
3. In Minion VM: observe that there's no change in the memory if you monitor it `watch 'top -b -n 1 | grep salt'
4. Run `yum update`
5. Restart salt-minion service
6. Observe, memory consumption is raising.

**Expected behavior**
salt-minion should not have any memory leaks whatsoever. The culprit is probably a third party that salt-minion uses but still severe.

**Screenshots**
Here's a graph that shows the memory consumption over time
![image](https://github.com/saltstack/salt/assets/59887121/95429fa6-108d-4389-95fe-53bccbdc2278)

**Versions Report**
<details><summary>salt --versions-report</summary>
Master: 
```
sh-4.2# salt --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.12
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-1160.76.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

Minion:
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 3.0.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.38.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 23.2.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.4

System Versions:
           dist: centos 7.9.2009 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-1127.el7.x86_64
         system: Linux
        version: CentOS Linux 7.9.2009 Core
```

```yaml
master: 127.0.0.1
startup_states: highstate
master_tries: -1
master_alive_interval: 30
ext_job_cache: rabbit
ping_interval: 1
auth_safemode: True

tcp_keepalive: True
tcp_keepalive_idle: 60
tcp_keepalive_intvl: 10
tcp_keepalive_cnt: 6

returner.rabbit.hostname: 127.0.0.1
returner.rabbit.exchange: service_provisioner_exchange
returner.rabbit.topic: service_provisioner.minion

returner_dirs:
  - /srv/salt/returners

module_dirs:
  - /srv/salt/modules

beacons:
  status:
    - interval: 30
    - time:
      - all

id: a9c16471-6443-48e9-aca3-4587b1cb3153
```
</details>

**Additional context**
related pip3 packages:
futures==3.1.1
Jinja2==3.0.3
M2Crypto==0.39.0
MarkupSafe==2.0.1
msgpack-python==0.5.6
pika==0.11.0
pycrypto==2.6.1
PyYAML==6.0.1
pyzmq==25.1.0
salt==2019.2.2
tornado==4.5.3
zmq==0.0.0
