### ISSUE TITLE
pkgrepo.absent does not remove repos from sources

### ISSUE THREAD

**Issue by maldata** [saltstack/salt#65150]
**Description**
The `pkgrepo.absent` state can correctly identify when a repo is or is not absent, however, it
1. does not remove it if the repo is present
2. considers it a failure if the repo is present

**Setup**
A Raspberry Pi running Debian Bullseye as the minion (salt 3002.6), and a VirtualBox VM running Debian Buster as the master (salt 2018.3.4 (Oxygen)).

**Steps to Reproduce the behavior**
The Raspberry Pi has the following file in `/etc/apt/sources.list.d/mything.list`:
```
deb [signed-by=/usr/share/keyrings/mykey.gpg] http://23.155.74.125/repo /
```

The salt state file looks like:
```
my test repo:
  pkgrepo.absent:
    - name: 'deb [signed-by=/usr/share/keyrings/mykey.gpg] http://23.155.74.125/repo /'
```

When I run a state.apply, the output is a failure. The repo is **_not_** removed from the sources file.

```
ID: dmc test repo
Function: pkgrepo.absent
Name: deb [signed-by=/usr/share/keyrings/mykey.gpg] http://23.155.74.125/repo /
Result: False
Comment: Repo deb [signed-by=/usr/share/keyrings/mykey.gpg] http://23.155.74.125/repo / doesn't exist in the sources.list(s)
Started: 16:38:12.428234
Duration: 235.248 ms
Changes:
```

If the repo is manually removed from the sources file, the state succeeds as expected.

**Expected behavior**
The state should succeed by identifying that the repo **_is_** in the sources, and it should remove it.

**Versions Report**
```yaml
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10.12
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-17-amd64
         system: Linux
        version: debian 10.12
```
