### ISSUE TITLE
mod_watch override prereq

### ISSUE THREAD

**Issue by ranl** [saltstack/salt#6520]
In the following state if the /some/file.txt state will change, the tomcat service will restart it-self but the remove-from-balancer state won't run..
If the /some/file.txt state won't change and the tomcat state will change the remove-from-balancer will run.

``` yaml
remove-from-balancer:
  cmd.run:
    - name: /opt/scripts/removefromlb.sh
    - prereq:
      - service: tomcat

/some/file.txt:
  file.managed:
    - source: salt://file.txt

tomcat:
  service.running:
    - enable: True
    - watch:
      - file: /some/file.txt
```

So it looks like that the mod_watch function is overriding the prereq states
