### ISSUE TITLE
[FEATURE REQUEST] support for contents via function call in file state modules

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#65222]
**Is your feature request related to a problem? Please describe.**
Currently, the ways to insert ad-hoc data from a function call into a file are limited to Jinja templating mechanisms such as:

```
something:
  file.managed:
    - name: /tmp/stuff
    - contents: |
        {% set things = salt.vault.read_secret("secret/my/secret") -%}
        {{ things }}
```

or

```
something:
  file.managed:
    - name: /tmp/stuff
    - template: jinja
    - source: salt://template.jinja
```

```
# /srv/salt/template.jinja
{% set things = salt.vault.read_secret("secret/my/secret") -%}
{{ things }}
```

The first option is problematic because secrets could be shown in `show_sls` output. The second is a pain because you'd need different template files for each set of function calls and parameters in use... or some terrible macro setup.

**Describe the solution you'd like**
It would be great if file state functions such as `file.managed` and `file.serialize` supported an integrated way to insert output from an execution module function call into a file via a `contents_function` parameter.

```yaml
something:
  file.managed:
    - name: /tmp/stuff
    - contents_function:
        - fun: vault.get
          args:
            - secret/my/secret
```

**Describe alternatives you've considered**
Workarounds shown in problem description.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.
