### ISSUE TITLE
[BUG] x509.certificate_managed keeps recreating certificate

### ISSUE THREAD

**Issue by benfiedler** [saltstack/salt#65224]
**Description**
Running x509.certificate_managed with the same arguments (and without changing **overwrite** to False), salt is always regenerating the certificate telling me the X509v3 Extensions have changed.

```
              Status:
                  ----------
                  New:
                      Certificate is valid and up to date
                  Old:
                      Certificate properties are different: X509v3 Extensions
```

**Setup**

_generic_cert.sls:_
```yaml
some_cert:
  x509.certificate_managed:
    - name: /home/user/test.crt
    - signing_private_key: /home/user/test.key
    - ca_server: 'mysaltmaster'
    - signing_policy: mypolicy

```

_/etc/salt/master.d/peer.conf_:
```yaml
peer:
  '.*':
    - x509.sign_remote_certificate

```
_pillar config for mysaltmaster:_
```yaml
x509_signing_policies:
# use the env's intermediate CA to sign systems
  mypolicy:
    - minions: '*'
    - signing_private_key: /etc/pki/myenv/ca.key
    - signing_cert: /etc/pki/myenv/ca.crt
    - basicConstraints: "critical CA:false"
    - subjectKeyIdentifier: hash
    - keyUsage: "critical keyEncipherment"
    - authorityKeyIdentifier: keyid,issuer:always
    # override the intermediate CA and force these properties
    - ST: Colorado
    - L: Denver
    - O: My Group
    - OU: My OU
    - Email: "address@gmail.com"
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (vmWare)
- [x] classic packaging (on master)
- [x] onedir packaging (on minion)
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
Run a state.apply on the _generic_cert.sls_ above with the master configuration provided.

**Expected behavior**
Salt should not recreate the certificate on every state.apply

**Versions Report**

**master salt report:**
```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: 4.1.0
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: 1.1.0
      M2Crypto: 0.37.1
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: 1.4.0
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 4.19.0-11-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```

**minion salt report:**
```yaml
Salt Version:
          Salt: 3006.2

Python Version:
        Python: 3.10.12 (main, Aug  3 2023, 21:47:10) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.32
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: 0.39.0
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.3
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-25-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy
```
</details>

**Additional context**
I see that the m2crypt x509 states/modules are slated for deprecation, so I understand if issue is not prioritized.

I took a dive into this and added some ugly debugging to state x509.py file. I believe I have identified the cause is from the `re.sub`s in this section which is meant to [remove the serial](https://github.com/saltstack/salt/blob/c5936f92ae441bc1cc5acfd81125f5b9c30063b9/salt/states/x509.py#L435) from comparison.

The problem is that the extension+serial data in the specified cert (contained in `v_ext`) ends with a newline, which is not dealt with by the re.sub regex.
This results in a object like:
```
v_ext:
{'authorityKeyIdentifier': 'keyid:SOME:LONG:HEX\n'
                           'Dirname:--\n'
                           'serial:--\n',
 'basicConstraints': 'critical CA:FALSE',
 'keyUsage': 'critical Key Encipherment',
 'subjectKeyIdentifier': 'SOME:LONG:HEX'}
```

compared against an object like:
```
cert_info_ext:
OrderedDict([('basicConstraints', 'critical CA:FALSE'),
             ('keyUsage', 'critical Key Encipherment'),
             ('subjectKeyIdentifier', 'SOME:LONG:HEX'),
             ('authorityKeyIdentifier', 'keyid:SOME:LONG:HEX\n'
              'Dirname:--\n'
              'serial:--')])
```

It's subtle, but you can see it compares `'serial:--'` against `'serial:--\n'`

In testing, I made the following minimal change in _states/x509.py on my master, and this seems to return it to expected behavior:
```
--- x509.py.orig
+++ x509.py     
@@ -419,3 +419,3 @@
                 "serial:--",
-                cert_info["X509v3 Extensions"]["authorityKeyIdentifier"],
+                cert_info["X509v3 Extensions"]["authorityKeyIdentifier"].strip(),
             )
@@ -424,3 +424,3 @@
                 "serial:--",
-                required_cert_info["X509v3 Extensions"]["authorityKeyIdentifier"],
+                required_cert_info["X509v3 Extensions"]["authorityKeyIdentifier"].strip(),
             )
```

I am not certain however if this is an appropriate band-aid fix, or if the underlying issue of why the serial newline is passed in from required_cert_info needs to be addressed.
