### ISSUE TITLE
[BUG] salt-pip fails to run on pip installed saltstack on Amazon Linux 2

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#65246]
**Description**
Attempts to install modules within saltstack onedir that was created with `pip install saltstack` fails to run.
`<path_to_onedir>/bin/python -m pip install modulename` works as expected.

**Setup**
AWS EC2 provisioned instance. Saltstack installed with `pip install saltstack /opt/saltstack`.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
Expect `pip install` to install requested module.

**Backtrace**
```sh
root@bhost ec2-user]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01"
```

```sh
[root@bhost ec2-user]# /opt/saltstack/bin/salt-pip install boto3
Traceback (most recent call last):
  File "/opt/saltstack/bin/salt-pip", line 8, in <module>
    sys.exit(salt_pip())
  File "/opt/saltstack/lib/python3.9/site-packages/salt/scripts.py", line 615, in salt_pip
    extras = str(sys.RELENV / "extras-{}.{}".format(*sys.version_info))
AttributeError: module 'sys' has no attribute 'RELENV'
[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
AttributeError: module 'sys' has no attribute 'RELENV'
Traceback (most recent call last):
  File "/opt/saltstack/bin/salt-pip", line 8, in <module>
    sys.exit(salt_pip())
  File "/opt/saltstack/lib/python3.9/site-packages/salt/scripts.py", line 615, in salt_pip
    extras = str(sys.RELENV / "extras-{}.{}".format(*sys.version_info))
AttributeError: module 'sys' has no attribute 'RELENV'
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.2

Python Version:
        Python: 3.9.16 (main, Feb 23 2023, 00:00:00)

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.32
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.5
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.18.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0.1
         PyZMQ: 25.0.2
        relenv: Not Installed
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: amzn 2023
        locale: utf-8
       machine: aarch64
       release: 6.1.41-63.114.amzn2023.aarch64
        system: Linux
       version: Amazon Linux 2023
```
</details>
