### ISSUE TITLE
[BUG] `prereq`'d state with `onlyif`+ `fun`: onlyif requisite ignored

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#65283]
**Description**
A state that is prerequired and itself has an `onlyif` requisite that calls an execution module will run regardless of outcome of the `onlyif` evaluation.

**Setup**
- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
```yaml
Copy stuff:
  file.copy:
    - name: /tmp/aa
    - source: /tmp/a
    - onlyif:
      - fun: file.file_exists
        path: /tmp/a

Do sth else:
  cmd.run:
    - name: true
    - prereq:
      - Copy stuff
```

**Expected behavior**
```console
local:
----------
          ID: Do sth else
    Function: cmd.run
      Result: True
     Comment: No changes detected
     Started: 06:41:33.485261
    Duration: 0.007 ms
     Changes:
----------
          ID: Copy stuff
    Function: file.copy
        Name: /tmp/aa
      Result: True
     Comment: onlyif condition is false
     Started: 06:41:33.485360
    Duration: 8.103 ms
     Changes:

Summary for local
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time:   8.110 ms
```

**Screenshots**
```console
[WARNING ] no `fun` argument in onlyif: OrderedDict([('path', '/tmp/a')])
[ERROR   ] Source file "/tmp/a" is not present
local:
----------
          ID: Do sth else
    Function: cmd.run
      Result: True
     Comment: No changes detected
     Started: 06:37:15.121723
    Duration: 0.008 ms
     Changes:
----------
          ID: Copy stuff
    Function: file.copy
        Name: /tmp/aa
      Result: False
     Comment: Source file "/tmp/a" is not present
     Started: 06:37:15.121817
    Duration: 80.259 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:  80.267 ms
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.3

Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 9.2 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-284.18.1.el9_2.x86_64
        system: Linux
       version: Rocky Linux 9.2 Blue Onyx
```
</details>

**Additional context**
The `prereq` results in the state to be run twice. During the first run, `fun` (and `args`) is popped from the passed-in lowstate chunk and is thus unavailable for the second (non-test) run:

https://github.com/saltstack/salt/blob/fb717a8d4bea3d48c596ae8dda313b7639c23dc6/salt/state.py#L1028-L1034

**Comment by OrangeDog** [comment]
The lowstate will need to be deep-cloned at an early stage. Hopefully there isn't a feature that relies on being able to change it globally in a state run...

**Comment by Pheric** [comment]
This also occurs when using `unless` instead of `onlyif`. Why is this scheduled for Argon?

**Comment by sticky-note** [comment]
{%- set msater_modules_deps = ['pygit2', 'python-ldap', 'psycopg2-binary'] %}
{%- set msater_modules_deps_run_deps =  [ "git" ] %}
{%- set msater_modules_deps_build_deps = [ "gcc", "libldap2-dev", "libsasl2-dev" ] %} # <- Debian specific

msater_modules_deps_run_deps_pkg_installed:
  pkg.latest:
    - names: {{ msater_modules_deps_run_deps }}
    - update: True

msater_modules_deps_build_deps_pkg_installed:
  pkg.latest:
    - names: {{ msater_modules_deps_build_deps }}
    - update: True

msater_modules_deps_downgrade_pip_workaround_pip_installed:
  pip.installed:
    - name: pip==22.3.1

{%- for msater_modules_dep in msater_modules_deps %}
msater_modules_dep_{{ msater_modules_dep }}_pip_installed:
  pip.installed:
    - name: {{ msater_modules_dep }}
    - upgrade: True
    - unless:  # dep installed and up to date
      - fun: pip.is_installed
        pkgname: {{ msater_modules_dep }}
      - fun: cmd.run
        cmd: ! salt-pip list --outdated | grep {{ msater_modules_dep }}
    - prereq_in:
      - pkg: msater_modules_deps_run_deps_pkg_installed
      - pkg: msater_modules_deps_build_deps_pkg_installed
      - pip: msater_modules_deps_downgrade_pip_workaround_pip_installed
    - require_in:
      - pkg: msater_modules_deps_build_dep_pkg_removed
    - watch_in:
      - service: salt-master
{%- endfor %}

msater_modules_deps_build_dep_pkg_removed:
  pkg.removed:
    - names: {{ msater_modules_deps_build_deps }}

msater_pip_pip_update:
  pip.installed:
    - name: pip
    - upgrade: true
    - onlyif:
      - fun: pip.upgrade_available
        pkg: pip

**Comment by lkubb** [comment]
@sticky-note Are you absolutely certain it's running as expected? The error message is the same as before and is logged just before the instruction is skipped.

**Comment by sticky-note** [comment]
In my case, with this code snippet, all cases are handled correctly, I am running:
```
salt-call --versions
Salt Version:
          Salt: 3006.6
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: 1.7.1
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: 1.14.0
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-17-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```
`prereq_in` and `require_in` are correctly run when they should and the  (`AND`) condition on `unless` also.
The only case when this code snippets does nothing if when all `master_modules_deps` are installed `AND` up to date.

Hope this is useful

**Comment by darkpixel** [comment]
There's definitely something odd with requisites going on in some areas:

This runs 100% of the time even when ```Get-PackageProvider``` returns the NuGet Package Provider info:
```
ensure_nuget:
  module.run:
    - psget.bootstrap: []
    - unless:
        - fun: cmd.powershell
          cmd: 'Get-PackageProvider NuGet'
```

If I switch it to use ```cmd.run``` it appears to work fine:
```
ensure_nuget:
  module.run:
    - psget.bootstrap: []
    - unless:
        - fun: cmd.run
          cmd: 'Get-PackageProvider NuGet'
          shell: powershell

# *or*

ensure_nuget:
  cmd.run:
    - name: 'Get-PackageProvider -Name NuGet -ForceBootstrap'
    - shell: powershell
    - unless:
        - fun: cmd.run
          cmd: 'Get-PackageProvider NuGet'
          shell: powershell
```

Unless seems to break with ```cmd.powershell```.

As I understand it, ```cmd.powershell``` returns a list or dictionary which should evaluate to false if no objects are returned, but also should evaluate to True if any data is returned.  I'm guessing there might be something b0rked, but maybe this is unrelated/user-error.

**Comment by b-a-t** [comment]
Salt 3006.16 is here. Still for the state like(related to [#52256](https://github.com/saltstack/salt/issues/52256)):
```
auditd_rules:
  file.managed:
    - name: "/etc/audit/rules.d/audit.rules"
    - source: salt://{{ slspath }}/files/audit.rules.jinja
    - template: jinja
    - user: root
    - group: root
    - mode: 600
    - makedirs: True
    - listen_in:
      - cmd: auditd_svc

 # Due to special handling of `auditd` in RHEL you can't restart
# it with the `systemctl` and have to use `service` instead.
# See: https://github.com/saltstack/salt/issues/52256
auditd_svc:
  cmd.run:
    - name: "service auditd restart"
    - unless:
      - fun: service.status
        name: auditd.service
```
I see:
```
[WARNING ] no `fun` argument in unless: OrderedDict([('name', 'auditd.service')])
```
Luckily, the state still works.
