### ISSUE TITLE
[BUG] jid_include: False not set by schedule module

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#65302]
**Description**
Noticed while using schedule.present to set a task with the argument **jid_include: False**  that the setting is not applied, the task is saved with jid_include: True.

```
set_salt_sched_task:
  schedule.present:
    - function: state.sls
    - job_args:
      - win_tasks.2_win_task_sched
    - seconds: 36--
    - jid_include: False
    - return_job: False
    - returner: rawfile_json
```

I took a look to the code to modules\schedule.py and found that jid_include is only set to default True if jid_include is not present or it's True, but ignored if jid_include is set to False, there are no lines in the module telling what to do when it's set to False, I guess that's the issue
```
    if "jid_include" not in kwargs or kwargs["jid_include"]:
        schedule[name]["jid_include"] = True

    # THE CODE BELOW IS A SUGGESTION TO SET jid_include: False
    # else:
    #   schedule[name]["jid_include"] = kwargs["jid_include"]
```

That being said, I'm not sure the impact of this change, if it's desired or not or how it may affect the **returner** setting

**Setup**
3006.1
