### ISSUE TITLE
[BUG] selinux.fcontext_policy_present can fail when the filespec is a regex

### ISSUE THREAD

**Issue by ndptech** [saltstack/salt#65340]
**Description**
A change introduced in 3006.3 to the selinux module function `_fcontext_add_or_delete_policy` checks for the presence of an existing matching context, and if one is found changes the action from "add" to "modify".

In certain corner cases, where regex are used for the filespec, this detection can match other contexts - which then changes the action to "modify", however since the policy does not actually exist, the attempt to modify fails.

**Setup**

- [ ] on-prem machine
- [X] VM (KVM)
- [X] Google Cloud
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [X] used bootstrap to install

Use a state file `selinux.sls` containing:

```
context1:
  selinux.fcontext_policy_present:
    - name: /srv/ssl/ldap/.*[.]key
    - sel_type: slapd_cert_t

context2:
  selinux.fcontext_policy_present:
    - name: /srv/ssl/ldap(/.*[.](pem|crt))?
    - sel_type: cert_t
```

**Steps to Reproduce the behavior**

Given the above state file, and neither, fcontext policy already existing, `salt <minion_id> state.sls selinux` will create the first selinux fcontext policy but not the second.

Output will be:

```
minion_id:
----------
          ID: context1
    Function: selinux.fcontext_policy_present
        Name: /srv/ssl/ldap/.*[.]key
      Result: True
     Comment: 
     Started: 09:00:08.369900
    Duration: 1480.618 ms
     Changes:   
              ----------
              new:
                  ----------
                  /srv/ssl/ldap/.*[.]key:
                      ----------
                      filetype:
                          all files
                      sel_type:
                          slapd_cert_t
              old:
                  ----------
----------
          ID: context2
    Function: selinux.fcontext_policy_present
        Name: /srv/ssl/ldap(/.*[.](pem|crt))?
      Result: False
     Comment: Error adding new rule: {'pid': 52772, 'retcode': 1, 'stdout': '', 'stderr': 'ValueError: File context for /srv/ssl/ldap(/.*[.](pem|crt))? is not defined'}
     Started: 09:00:09.850697
    Duration: 946.32 ms
     Changes:   

Summary for minion_id
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
```

**Expected behavior**
Both states should have succeeded.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.3
 
Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 9.2 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-284.25.1.el9_2.x86_64
        system: Linux
       version: Rocky Linux 9.2 Blue Onyx
```
</details>

**Comment by finalduty** [comment]
I have a similar issue relating to the same [change](https://github.com/saltstack/salt/commit/8395ff565c724e2a9fdced8b29fd7a84076e983d#diff-e1d1763b2741ed685145912cfeea8018cd6fbe73e8717b2bfba91876709d0690R620) in code. In my case, the new modify logic doesn't take in to account when a filetype is specified.

For example, RHEL/CentOS Stream 9 has a default fcontext policy for /dev/log which only applies to symlinks:
```
[user@minion ~]$ sudo semanage fcontext -l | grep '^/dev/log '
/dev/log                                           symbolic link      system_u:object_r:devlog_t:s0 
```

Our setup puts a socket file at /dev/log rather than a symlink, so we use the following state to add the correct fcontext, which has been working fine:
```
/dev/log:
  selinux.fcontext_policy_present:
    - filetype: s
    - sel_type: devlog_t
```

Which now results in the following error:
```
local:
----------
          ID: /dev/log
    Function: selinux.fcontext_policy_present
      Result: False
     Comment: Error adding new rule: {'pid': 2047936, 'retcode': 1, 'stdout': '', 'stderr': 'ValueError: File context for /dev/log is not defined'}
     Started: 11:17:35.234723
    Duration: 2185.499 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```
