### ISSUE TITLE
[BUG] Augeas provides actions but not checks

### ISSUE THREAD

**Issue by hramrach** [saltstack/salt#65352]
**Description**

Not sure this is a bug in the docs of if this is deficiency of the augeas plugin.

The docs say https://docs.saltproject.io/en/latest/ref/states/all/salt.states.augeas.html

```
zabbix-service:
  augeas.change:
    - lens: services.lns
    - context: /files/etc/services
    - changes:
      - ins service-name after service-name[last()]
      - set service-name[last()] "zabbix-agent"
      - set "service-name[. = 'zabbix-agent']/port" 10050
      - set "service-name[. = 'zabbix-agent']/protocol" tcp
      - set "service-name[. = 'zabbix-agent']/#comment" "Zabbix Agent service"
      - rm "service-name[. = 'im-obsolete']"
    - unless: grep "zabbix-agent" /etc/services
```

This is not a way to manage the file. The string `zabbix-agent` may be in the file but commented out. There might be a service like `zabbix-agent-ng`. When the file is modified by augeas the check that the modification was applied should also be done by augeas.
