### ISSUE TITLE
[FEATURE REQUEST] Provide not only augeas actions but also augeas checks

### ISSUE THREAD

**Issue by hramrach** [saltstack/salt#65359]
**Is your feature request related to a problem? Please describe.**
The docs say https://docs.saltproject.io/en/latest/ref/states/all/salt.states.augeas.html

```
zabbix-service:
  augeas.change:
    - lens: services.lns
    - context: /files/etc/services
    - changes:
      - ins service-name after service-name[last()]
      - set service-name[last()] "zabbix-agent"
      - set "service-name[. = 'zabbix-agent']/port" 10050
      - set "service-name[. = 'zabbix-agent']/protocol" tcp
      - set "service-name[. = 'zabbix-agent']/#comment" "Zabbix Agent service"
      - rm "service-name[. = 'im-obsolete']"
    - unless: grep "zabbix-agent" /etc/services
```

This is not a way to manage the file. The string `zabbix-agent` may be in the file but commented out. There might be a service like `zabbix-agent-ng`. When the file is modified by augeas the check that the modification was applied should also be done by augeas.
The docs say https://docs.saltproject.io/en/latest/ref/states/all/salt.states.augeas.html

```
zabbix-service:
  augeas.change:
    - lens: services.lns
    - context: /files/etc/services
    - changes:
      - ins service-name after service-name[last()]
      - set service-name[last()] "zabbix-agent"
      - set "service-name[. = 'zabbix-agent']/port" 10050
      - set "service-name[. = 'zabbix-agent']/protocol" tcp
      - set "service-name[. = 'zabbix-agent']/#comment" "Zabbix Agent service"
      - rm "service-name[. = 'im-obsolete']"
    - unless: grep "zabbix-agent" /etc/services
```

This is not a way to manage the file. The string `zabbix-agent` may be in the file but commented out. There might be a service like `zabbix-agent-ng`. 

**Describe the solution you'd like**
Augeas upstream provides both functions to change the file and get data from the file. When the file is modified by augeas the check that the modification was applied should also be done by Augeas.

If I did not use Salt but rather Augeas upstream tools I could write a check that parses the file and looks if "zabbix-agent" service definition is present, and execute the actions to add it when it is not.

Here the check is implemented with 'grep' which has very little idea about the structure of the file rather than with Augeas, the very thing Augeas is supposed to prevent.
