### ISSUE TITLE
[BUG] beacons network_settings unable to pull interface data

### ISSUE THREAD

**Issue by chateaulav** [saltstack/salt#65361]
**Description**
This issue is related current upgrade to pyroute2, although salt made updates to account for implementation of ndb it appears that that main module leveraged for this modules in the pyroute2 project does not properly handle this upgrade. I have submitted an applicable issue and merge request to pyroute2 to address and correct the underlying problem:

- https://github.com/svinota/pyroute2/issues/1132
- https://github.com/svinota/pyroute2/pull/1133

Output from pillar configured beacon (`ipaddr` shows a null value):
```
root@salt-dev:~# salt guacamole* beacons.list
guacamole-4dec2838-7e3c-5047-86d6-e04901ff8041:
    beacons:
      enabled: false
      network_settings:
      - coalesce: true
      - interfaces:
          ens3:
            ipaddr: null
      - disable_during_state_run: true
      - interval: 60
```

Output from salt-minion log:
```
root@salt-dev:~# tail /var/log/salt/minion
2023-10-06 11:05:38,319 [salt.beacons     :143 ][ERROR   ][2121] Unable to start network_settings beacon, 'NoneType' object is not iterable
2023-10-06 11:06:38,318 [salt.beacons     :143 ][ERROR   ][2121] Unable to start network_settings beacon, 'NoneType' object is not iterable
2023-10-06 11:07:38,318 [salt.beacons     :143 ][ERROR   ][2121] Unable to start network_settings beacon, 'NoneType' object is not iterable
2023-10-06 11:08:38,319 [salt.beacons     :143 ][ERROR   ][2121] Unable to start network_settings beacon, 'NoneType' object is not iterable
2023-10-06 11:09:38,318 [salt.beacons     :143 ][ERROR   ][2121] Unable to start network_settings beacon, 'NoneType' object is not iterable
2023-10-06 11:10:38,318 [salt.beacons     :143 ][ERROR   ][2121] Unable to start network_settings beacon, 'NoneType' object is not iterable
2023-10-06 11:11:38,319 [salt.beacons     :143 ][ERROR   ][2121] Unable to start network_settings beacon, 'NoneType' object is not iterable
2023-10-06 11:12:38,320 [salt.beacons     :143 ][ERROR   ][2121] Unable to start network_settings beacon, 'NoneType' object is not iterable
2023-10-06 11:13:38,318 [salt.beacons     :143 ][ERROR   ][2121] Unable to start network_settings beacon, 'NoneType' object is not iterable
2023-10-06 11:14:38,320 [salt.beacons     :143 ][ERROR   ][2121] Unable to start network_settings beacon, 'NoneType' object is not iterable
```

Output from `state.event`:
```
root@salt-dev:~# salt-run state.event pretty=true
salt/beacon/cinder-6aff1fc5-ecb2-5d82-a984-5f441520e1b3/network_settings/	{
    "_stamp": "2023-10-06T15:39:01.489149"
}
salt/beacon/cinder-6d21d35d-c872-5010-afad-301f80901160/network_settings/	{
    "_stamp": "2023-10-06T15:39:02.170035"
}
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

- [X] on-prem machine
- [X] VM running with libvirt
- [X] onedir packaging
- [X] used bootstrap to install

Basic Software packages
```
salt 3006.3
Ubuntu 22.04
Python3.10

pyroute2 == 0.7.9
pyroute2.ndb == 0.6.13
pyroute2.ipdb== 0.6.13
```

grains value being set within `formulas/common/networking.sls` running on each host, along with pyroute2 pip packages
```
ifwatch:
  grains.present:
    - value:
      - ens3
    - force: True
    
pyroute2_pip:
  pip.installed:
    - bin_env: '/usr/bin/pip3'
    - reload_modules: True
    - pkgs:
      - pyroute2
      - pyroute2.ndb
      - pyroute2.ipdb

pyroute2_salt_pip:
  pip.installed:
    - bin_env: '/usr/bin/salt-pip'
    - reload_modules: True
    - pkgs:
      - pyroute2
      - pyroute2.ndb
      - pyroute2.ipdb
    - require:
      - pip: pyroute2_pip
```

beacon config to leverage grains value, being configured in `pillar/environment/beacon_configs/address_notification.sls`
```
beacons:
  network_settings:
    - coalesce: True
    - interfaces:
{% for interface in salt['grains.get']('ifwatch') %}
        {{ interface }}:
          ipaddr:
{% endfor %}
    - disable_during_state_run: True
    - interval: 60
```

reactor config to trigger state run, being configured in `pillar/environment/answers.sls`
```
  reactor: |
    reactor:
      - salt/beacon/*/network_settings/result:
        - salt://reactor/update_mine.sls
        - salt://reactor/highstate_notification.sls
```

reactor sls files to trigger state run, being configured in `reactor/update_mine.sls`
```
update_mine:
  runner.mine.update:
    - args:
      - tgt: {{ data['id'] }}
```

reactor sls files to trigger state run, being configured in `reactor/highstate_notification.sls`
```
highstate_{{ data['id'] }}:
  local.state.highstate:
    - tgt_type: compound
    - tgt: 'E@(*)'
```

**Steps to Reproduce the behavior**
basic configured setup for `network_settings` beacon

**Expected behavior**
proper handling and processing of beacon

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.3
 
Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: 1.7.1
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.13.1
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04.3 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-84-generic
        system: Linux
       version: Ubuntu 20.04.3 jammy
```
</details>
