### ISSUE TITLE
[BUG] Legacy module.run does not work with pkg.refresh_db and failhard=False

### ISSUE THREAD

**Issue by jtraub91** [saltstack/salt#65386]
**Description**
[pkg.refresh_db](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.win_pkg.html#salt.modules.win_pkg.refresh_db) has it's own `failhard` keyword argument, not to be confused with [state failhard](https://docs.saltproject.io/en/latest/ref/states/failhard.html), but does not seem to work with the legacy syntax for [module.run](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.module.html#salt.states.module.run)

**Setup**

My experience with this issue has been on __Windows minions with winrepo__ so it _might_ be specific to that situation. Thus, install salt as normal with at least one Windows minion. Once minion and master is setup, update winrepo

```
salt-run winrepo.update_git_repos
```
Then, go into one of the winrepo files and add something to make the definition file fail, e.g.

_/srv/salt/win/repo-ng/salt-winrepo-ng_git/firefox.sls_
```
...
{%- set lang = salt['config.get']('firefox:pkg:lang', 'en-US') %}

dlsldkasdkladk;sd;kal;

{% load_yaml as versions -%}
- 118.0.1
...
```

**Steps to Reproduce the behavior**

Now we can observe that `pkg.refresh_db` will show a failed package, and that `failhard=False` suppresses the non-zero retcode, however, this is not the case for both versions of module.run syntax.

_working_example.sls_

```
run_pkg_refresh_db:
  module.run:
    - pkg.refresh_db:
      - failhard: False
```

_not_working_example.sls_

```
run_pkg_refresh_db:
  module.run:
    - name: pkg.refresh_db
    - m_failhard: False
```

Output shown below

```
salt -G 'os_family:Windows' state.sls working_example
<minion>:
----------
          ID: run_pkg_refresh_db
    Function: module.run
      Result: True
     Comment: pkg.refresh_db: Success
     Started: 18:01:36.581406
    Duration: 16422.01 ms
     Changes:
              ----------
              pkg.refresh_db:
                  ----------
                  failed:
                      1
                  failed_list:
                      ----------
                      salt-winrepo-ng_git\firefox.sls:
                          - Failed to compile, mapping values are not allowed in this context
                  success:
                      310
                  total:
                      311

Summary for <minion>
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  16.422 s
```
```
# salt -G 'os_family:Windows' state.sls not_working_example
<minion>:
----------
          ID: run_pkg_refresh_db
    Function: module.run
        Name: pkg.refresh_db
      Result: False
     Comment: Module function pkg.refresh_db threw an exception. Exception: Error occurred while generating repo db. Additional info follows:

              failed:
                  1
              failed_list:
                  ----------
                  salt-winrepo-ng_git\firefox.sls:
                      - Failed to compile, mapping values are not allowed in this context
              success:
                  310
              total:
                  311
     Started: 18:02:03.753498
    Duration: 16922.009 ms
     Changes:

Summary for <minion>
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  16.922 s
ERROR: Minions returned with non-zero exit code
```

**Expected behavior**
Both examples should work the same (in that `pkg.refresh_db` may fail but it does not cause the state to fail), or the legacy version should be removed from the codebase/docs, or at least the documentation should be updated / improved to reflect this caveat.

**Versions Report**
master
```
# salt --versions-report
Salt Version:
          Salt: 3006.3

Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-67-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy
```
windows minion
```
# salt -G 'os_family:Windows' cmd.run 'salt-call --versions-report'
<minion>:
    Salt Version:
              Salt: 3006.3

    Python Version:
            Python: 3.10.13 (heads/main:7ee24e6, Sep  6 2023, 02:19:49) [MSC v.1936 64 bit (AMD64)]

    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.7
         gitpython: Not Installed
            Jinja2: 3.1.2
           libgit2: Not Installed
      looseversion: 1.0.2
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 22.0
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.10.1
            pygit2: Not Installed
      python-gnupg: 0.4.8
            PyYAML: 6.0.1
             PyZMQ: 25.0.2
            relenv: 0.13.10
             smmap: 4.0.0
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4

    System Versions:
              dist:
            locale: cp1252
           machine: AMD64
           release: 2022Server
            system: Windows
           version: 2022Server 10.0.20348 SP0 Multiprocessor Free
```
