### ISSUE TITLE
[BUG] Regression caused by PR#62641

### ISSUE THREAD

**Issue by vzhestkov** [saltstack/salt#65406]
**Description**
PR https://github.com/saltstack/salt/pull/62641 caused the regression for some particular cases, and could be also harmful for the other cases.

In case if the password is used for the authentication to remote SSH system and the password is not really complex in case of matching any part of the output from the client side any occurance of the password is replaced with `*******` not just for logging, but also inside the resulting response.

So there are 2 most problematic cases:
1. If the password used for the user on the remote system is `password` or `Password` this word is wiped of of the prompt to enter password in case if jump host is used for ssh and salt-ssh processing got stuck on waiting for extra output from the client as the promt for the password is not detected in this case. On my tests it happens with keyboard interactive authentication for ssh client.
Can be reproduced with such roster file (but it could be default settings on ssh server side):
```
alma8.tf.local:
  host: alma8.tf.local
  user: root
  passwd: Password
  ssh_options: ["PreferredAuthentications=keyboard-interactive"]
```
3. If the password is matching any part of the output, this part will be sanitized. As the result is the broken data or even the broken JSON if the matching part is a part of JSON output. For example in case of having `linux` as a pasword we could have such output:
```
# salt-ssh --roster=flat --roster-file=/tmp/ssh/alma8.sls -i alma8.tf.local grains.item kernelparams
alma8.tf.local:
    ----------
    kernelparams:
        |_
          - BOOT_IMAGE
          - (hd0,msdos1)/vmlinuz-4.18.0-477.10.1.el8_8.x86_64
        |_
          - root
          - /dev/mapper/alma******-root
        |_
          - ro
          - None
        |_
          - crashkernel
          - auto
        |_
          - resume
          - /dev/mapper/alma******-swap
        |_
          - rd.lvm.lv
          - alma******/root
        |_
          - rd.lvm.lv
          - alma******/swap
        |_
          - rhgb
          - None
        |_
          - quiet
          - None
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
Just require remote ssh system with password set to something lilke 'Password', 'password' or even matching any part of the output which can be produced with the specified call.

One of the examples of the roster file used for testing:
```
alma8.tf.local:
  host: alma8.tf.local
  user: root
  passwd: Password
  ssh_options: ["PreferredAuthentications=keyboard-interactive"]
```

**Expected behavior**
No any stucks on processing salt-ssh events and relevant output with no wiping some data which is not really related to the password itself.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.0
 
Python Version:
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.3.0
  looseversion: 1.0.2
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 20.3
     pycparser: 2.17
      pycrypto: 3.9.0
  pycryptodome: Not Installed
        pygit2: 1.7.0
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: opensuse-leap 15.5 
        locale: UTF-8
       machine: x86_64
       release: 5.14.21-150500.55.31-default
        system: Linux
       version: openSUSE Leap 15.5
```
</details>

**Additional context**
The newer versions seems also affected.
