### ISSUE TITLE
Saltstack Pillar for linux and Windows error

### ISSUE THREAD

**Issue by Ayush62** [saltstack/salt#65427]
Hello all,
I am currently creating a pillar for both Red hat and Windows.
The pillar looks like this at the moment:
Top.sls:
```
# top.sls
base:
  '*':
    - redhat
    - windows

# redhat.sls
redhat:
  update_redhat:
    pkg.uptodate:
      - name: '*'

# windows.sls
windows:
  update_windows:
    wua.uptodate:
      - name: '*'
```

When I execute this script, I keep on getting this error:
        - Specified SLS 'windows' in environment 'base' is not available on the salt master
I don’t know how to fix this do any of you have any insight on this?
