### ISSUE TITLE
[BUG] salt-ssh state.* with pillar overrides: pillar dict and pillar in wrappers out of sync

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#65483]
**Description**
When passing complex pillar overrides to `salt-ssh state.sls` etc., there will be a mismatch during template rendering. The `pillar` dict will contain the correct data, while calling the `pillar.get` wrapper module will return data that has not been recursively merged (all wrappers are affected). This is the master-side equivalent of https://github.com/saltstack/salt/issues/59802.

**Setup**
irrelevant

**Steps to Reproduce the behavior**
```yaml
# a pillar targeted to the minion
monty: python
the_meaning:
  of:
    life: 42
    bar: tender
  for: what
```

```yaml
# test.sls
deep_thought:
  test.show_notification:
    - text: '{{ {"raw": {"the_meaning": pillar.get("the_meaning"), "btw": pillar.get("btw")}, "wrapped": {"the_meaning": salt["pillar.get"]("the_meaning"), "btw": salt["pillar.get"]("btw")}} | json }}'
```

`salt-ssh foo state.apply test pillar='{the_meaning: {of: {life: 2.71, foo: lish}}, btw: turtles}'`

**Expected behavior**
```console
foo:
----------
          ID: deep_thought
    Function: test.show_notification
      Result: True
     Comment: {"raw": {"btw": "turtles", "the_meaning": {"of": {"life": 2.71, "foo": "lish", "bar": "tender"}, "for": "what"}}, "wrapped": {"btw": "turtles", "the_meaning": {"of": {"life": 2.71, "foo": "lish", "bar": "tender"}, "for": "what"}}}
     Started: 18:18:36.786042
    Duration: 1.003 ms
     Changes:
```

**Screenshots**
```console
foo:
----------
          ID: deep_thought
    Function: test.show_notification
      Result: True
     Comment: {"raw": {"btw": "turtles", "the_meaning": {"of": {"life": 2.71, "foo": "lish", "bar": "tender"}, "for": "what"}}, "wrapped": {"btw": "turtles", "the_meaning": {"of": {"life": 2.71, "foo": "lish"}}}}
     Started: 18:18:36.786042
    Duration: 1.003 ms
     Changes:
```
Notice the difference of `raw` and `wrapped`, the latter is the initial pillar `.update()`d with the overrides, the former the wanted, recursively merged one.

**Versions Report**
quite recent checkout of 3006.x branch, nothing has changed in master though

**Additional context**
Stumbled upon this while writing tests for a PR.
