### ISSUE TITLE
[BUG] user.list_users not fetching all users on onedir installs

### ISSUE THREAD

**Issue by timwsuqld** [saltstack/salt#65493]
**Description**
On Google GCP VMs that use OSLogin, `user.list_users` no longer returns users that are coming from oslogin. This appears to be a onedir issue as running `pwd.getpwall()` in system python correctly returns the users, while running it in the onedir python does not. This prevents us using users and groups from OS Login in salt states as they give errors like `User admin-timw is not available`.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
```
# /etc/nsswitch.conf
passwd:         files systemd cache_oslogin oslogin
group:          files systemd cache_oslogin oslogin
```

- [x] VM running on a cloud service, please be explicit and add details
- [x] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

Google Cloud VMs. 22.04 and 20.04, running Salt 3005 (upgrade delayed to 3006 for various reasons)

**Steps to Reproduce the behavior**

`user.list_users` on Salt 3005.1 on Ubuntu 20.04 not using onedir, filtering by user coming from Google OS Login. `getent passwd` output also filtered by user coming from Google OS Login
```
$salt-call user.list_users|grep admin-timw
    - admin-timw
$ getent passwd|grep admin-timw
admin-timw:*:10013:10013::/home/admin-timw:/bin/bash

```

`user.list_users` on Salt 3005.3 on Ubuntu 22.04 using onedir, filtering by user coming from Google OS Login. `getent passwd` output also filtered by user coming from Google OS Login
```
$ salt-call user.list_users|grep admin-timw
$ getent passwd|grep admin-timw
admin-timw:*:10013:10013::/home/admin-timw:/bin/bash

```

Running `sudo /opt/saltstack/salt/run/run shell` on the onedir install, then running the below, confirms that the issue is that the onedir python is just reading the /etc/passwd file, and not querying the system database. Running the below in the system python (still on the 22.04 machine) produces the correct results.
```
import pwd
pwd.getpwall()
```

**Expected behavior**
`user.list_users` should be consistent with `getent passwd`, correctly reading the users from all nsswitch databases, and not just `/etc/passwd`

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

Salt config on working legacy 3005.1 machines
```yaml
 salt-call -V
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, May 26 2023, 14:05:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1045-gcp
        system: Linux
       version: Ubuntu 20.04 focal

$ apt policy salt-minion
salt-minion:
  Installed: 3005.1+ds-2
  Candidate: 3005.1+ds-2
  Version table:
     3005.4+ds-1 500
        500 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal/main amd64 Packages
 *** 3005.1+ds-2 1000
        100 /var/lib/dpkg/status

```

Salt config on 3005.3 OneDir Ubuntu 22.04 installs that doesn't work
```yaml
Salt Version:
          Salt: 3005.3
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.18 (main, Sep 18 2023, 18:17:25)
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 6.2.0-1017-gcp
        system: Linux
       version: Ubuntu 22.04 jammy


$ apt policy salt-minion
salt-minion:
  Installed: 3005.3+ds-1
  Candidate: 3005.4+ds-1
  Version table:
     3005.4+ds-1 500
        500 https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/3005 jammy/main amd64 Packages
 *** 3005.3+ds-1 100
        100 /var/lib/dpkg/status

```

</details>

**Additional context**
I don't believe the issue is the we are hitting ` _getpwall` in https://github.com/saltstack/salt/blob/master/salt/modules/useradd.py#L955 as I have tested the plain `pwd` commands in the python shell in onedir. This appears to be something wrong with how the onedir python is setup.
