### ISSUE TITLE
[FEATURE REQUEST] Require Relative SLS

### ISSUE THREAD

**Issue by Pheric** [saltstack/salt#65503]
Repost of closed issue #10838.

I would like to require a relative SLS, in the same fashion as including a relative sls:
```yaml
include:
  - .anothersls

State Requiring Relative SLS:
  test.nop:
    - require:
      - sls: .anothersls
```

A current alternative way to do the above, as mentioned by @mallniya:
```yaml
include:
  - .anothersls

State Requiring Relative SLS:
  test.nop:
    - require:
      - sls: {{ slspath }}.anothersls
```
