### ISSUE TITLE
pkg.installed should mark already installed packages as manually installed

### ISSUE THREAD

**Issue by 4D617276696E** [saltstack/salt#65528]
**Is your feature request related to a problem? Please describe.**
Say state1 install pkg1 which depend on pkg2. Both packages are going to be installed.
Now if state2 ask for pkg2 installation and the state is fired after state1, nothing is going to be done;  pkg2 is already installed and it is not going to be "marked" as "manually installed".
On Debian system if pkg1 is installed and followed by apt install pkg2, the package pkg2 is going to be "marked" as manually installed.
pkg2 is going to be "autoremoved"  if pkg1 is removed.  

**Describe the solution you'd like**
pkg.installed should provide a "platform-specific argument" to allow user to choose to "apt-mark manual" the package.

**Describe alternatives you've considered**
Something like :
```yaml
state2-pkg2-install:
  pkg.installed:
    - name: pkg2
{% if grains['os_family'] == 'Debian' %}
pkg2-apt-mark-manual:
  cmd.run:
    - name: "apt-mark manual pkg2"
    - require:
      - pkg: state2-pkg2-install
{% endif %}
```
