### ISSUE TITLE
[BUG] file.managed: test mode always reports changes

### ISSUE THREAD

**Issue by dead10ck** [saltstack/salt#65589]
**Description**

`file.managed` always reports changes in test mode, even when there are none.

**Setup**

* Salt version 3006
* Fedora server 38
* official package in Fedora with dnf
* AWS EC2 instance

**Steps to Reproduce the behavior**

It is trivially reproducible with a simple text file.

If `foo` is a text file with the contents `bar` and we for copy it to the target machine with:

```yaml
/var/tmp/foo:
  file.managed:
    - source: salt://files/foo
```

After applying, if we do `state.high state test=true`, we see:

```
----------
          ID: /var/tmp/foo
    Function: file.managed
      Result: None
     Comment: The file /var/tmp/foo is set to be changed
              Note: No changes made, actual changes may
              be different due to other states.
     Started: 21:50:33.792008
    Duration: 158.748 ms
     Changes:
              ----------
              diff:
```

**Versions Report**

<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.4

Python Version:
        Python: 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728
(Red Hat 13.2.1-1)]

Dependency Versions:
          cffi: 1.15.1
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.0
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.19.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 24.0.1
smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: fedora 38
        locale: utf-8
       machine: x86_64
       release: 6.5.8-200.fc38.x86_64
        system: Linux
       version: Fedora Linux 38
```
</details>
