### ISSUE TITLE
[BUG] Cannot set file permissions using file.set_mode

### ISSUE THREAD

**Issue by kristophercrawford** [saltstack/salt#65606]
**Description**
When attempting to set file permissions using the file module, I am seeing the following error being reported:

```shell
----------
          ID: set_execute_bit
    Function: file.set_mode
      Result: False
     Comment: State 'file.set_mode' was not found in SLS 'aesEncrypt'
              Reason: 'file.set_mode' is not available.
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [X] used bootstrap to install

**Steps to Reproduce the behavior**
My state file contains the following:

```yaml
# Set the execute bit
set_execute_bit:
  file.set_mode:
    - path: /usr/local/bin/AESEncrypt
    - mode: 0755
```

Applying this state I see the following:

```shell
# salt-call state.apply aesEncrypt -ldebug
...
[DEBUG   ] Could not LazyLoad file.set_mode: 'file.set_mode' is not available.
[INFO    ] Running state [set_execute_bit] at time 17:41:32.525295
[DEBUG   ] Could not LazyLoad file.set_mode: 'file.set_mode' is not available.
[ERROR   ] State 'file.set_mode' was not found in SLS 'aesEncrypt'
Reason: 'file.set_mode' is not available.
...
----------
          ID: set_execute_bit
    Function: file.set_mode
      Result: False
     Comment: State 'file.set_mode' was not found in SLS 'aesEncrypt'
              Reason: 'file.set_mode' is not available.
     Changes:
```

When running this manually: `# salt-call file.set_mode /usr/local/bin/AESEncrypt 0755`, the file permissions are set as expected.

**Expected behavior**
When running the state, the file.mode module should be available and the file permissions should be updated.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

*Master*

```yaml
# salt --versions-report
Salt Version:
          Salt: 3005.4

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.24
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.11.0
        pygit2: Not Installed
        Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 Jammy Jellyfish
        locale: utf-8
       machine: x86_64
       release: 6.2.16-11-pve
        system: Linux
       version: Ubuntu 22.04 Jammy Jellyfish
```

*Minion*

```yaml
# salt-call --versions-report
Salt Version:
          Salt: 3006.4

Python Version:
        Python: 3.10.13 (main, Oct  4 2023, 21:57:51) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.12
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.3 jammy
        locale: utf-8
       machine: aarch64
       release: 5.10.160-rockchip
        system: Linux
       version: Ubuntu 22.04.3 jammy
```
</details>

**Comment by OrangeDog** [comment]
`file.set_mode` is an execution function, not a state function. If you want to write a state that ensures the permissions of a file:

```yaml
/usr/local/bin/AESEncrypt:
  file.managed:
    - mode: '0755'
    - replace: false
```
