### ISSUE TITLE
[BUG] Debian onedir install, salt user home dir ownership

### ISSUE THREAD

**Issue by michaelebroughton** [saltstack/salt#65618]
**Description**
I have my Salt master/syndic installed on Debian 12 hosts using the Deb11 onedir official repo.

So the Deb package puts everything into /opt/saltstack/salt and makes the owner root.

It also creates a salt user and sets its home dir to /opt/saltstack/salt.

The Salt master process runs under the salt user, and for the most part this isn't an issue.

The problem is when the salt user wants to do something with restrictive permissions/ownership like SSH keys.

I can manually create a /opt/saltstack/salt/.ssh/ folder and set ownership to the salt user. This works, except when I run apt update the ownership goes back to root.

**Setup**
Debian 12 VM running on Vmware. Salt is installed from repo.saltproject.io, I'm using the Deb11 package.

**Expected behavior**
I can think of a couple options:
1. Have the package set ownership of /opt/saltstack/salt to the salt user instead of root.
2. Set the salt users home directory to something else that can be owned by salt.

**Versions Report**
<details><summary>salt --versions-report</summary>
```yaml
Salt Version:
          Salt: 3006.4
 
Python Version:
        Python: 3.10.13 (main, Oct  4 2023, 21:54:22) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.12
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-11-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
 
```
</details>
