### ISSUE TITLE
[BUG] schedule states do not report changes in test mode

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#65652]
**Description**
Same as #59844 but with `test=true`.

**Steps to Reproduce the behavior**
```yaml
# salt-call state.single test=true schedule.present job1 function=test.ping seconds=3600 --state-output=full --state-verbose=true
local:
----------
          ID: job1
    Function: schedule.present
      Result: True
     Comment: Job: job1 would be added to schedule.
     Started: 13:19:13.100498
    Duration: 25.665 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  25.665 ms
```

**Expected behavior**
```yaml
local:
----------
          ID: job1
    Function: schedule.present
      Result: None
     Comment: Job: job1 would be added to schedule.
     Started: 13:19:13.100498
    Duration: 25.665 ms
     Changes:
              ----------
              job1:
                  added

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:  25.665 ms
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.4

Python Version:
        Python: 3.10.4 (main, Apr 20 2022, 01:21:48) [GCC 10.3.1 20210424]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: alpine 3.14.6
        locale: utf-8
       machine: x86_64
       release: 5.15.133.1-microsoft-standard-WSL2
        system: Linux
       version: Alpine Linux 3.14.6
```
</details>
