### ISSUE TITLE
virt module (libvirt) broken on EL9

### ISSUE THREAD

**Issue by gandihar** [saltstack/salt#65694]
**Description**
Somehow, the virt (libvirt) module is broken on EL9. It works on EL7-8 but fails with:
```'virt' __virtual__ returned False: Unable to locate or import python libvirt library.```

**Setup**
Using the onedir Salt Minion packages from the official repo (3006.*). Used 'pip.install' as per Documents to install the libvirt-python module. Dependencies (libvirt client, libvirt libs, grep) are pressent. Issuing any 'virt.*' commands returns the error 
```'virt' __virtual__ returned False: Unable to locate or import python libvirt library.``` on any EL9 variant, but works on EL7 and 8.

- [X] on-prem machine
- [X] onedir packaging
- [X] used bootstrap to install

**Steps to Reproduce the behavior**
- Install Salt-minion using the onedir RPMs in the official repo on an EL9 system (Tested OEL9, Alma9, Rocky9).
- Use Salt States to pip.install libvirt-python.
- Issue 'virt.*' commands, or use 'virt.*' States.
  ```'virt' __virtual__ returned False: Unable to locate or import python libvirt library.```
( There are no logs, even using -l debug )

**Expected behavior**
The output of the 'virt.*' command or State that is issued.

**Versions Report**
**Master**
``` yaml
Salt Version:
          Salt: 3006.5
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: centos 7.9.2009 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.102.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7.9.2009 Core
```

**Working Minion (EL7)**
```yaml
Salt Version:
          Salt: 3006.5

Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 7.9.2009 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.102.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7.9.2009 Core
```
``` yaml
local:
    ----------
    libvirt-python:
        9.4.0
```

**Working Minion (EL8)**
```yaml
Salt Version:
          Salt: 3006.5
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: almalinux 8.9 Midnight Oncilla
        locale: utf-8
       machine: x86_64
       release: 4.18.0-513.9.1.el8_9.x86_64
        system: Linux
       version: AlmaLinux 8.9 Midnight Oncilla
```
```yaml
local:
    ----------
    libvirt-python:
        9.4.0
```

Broken Minion (EL9)
```yaml
Salt Version:
          Salt: 3006.5
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: almalinux 9.3 Shamrock Pampas Cat
        locale: utf-8
       machine: x86_64
       release: 5.14.0-362.8.1.el9_3.x86_64
        system: Linux
       version: AlmaLinux 9.3 Shamrock Pampas Cat
```
``` yaml
local:
    ----------
    libvirt-python:
        9.10.0
```
(libvirt-python removed and re-installed as part of troubleshooting)
(the new version, it does nothing)

**Comment by dwoz** [comment]
Did you use `salt-pip` to install libvirt?

`/opt/saltstack/salt/salt-pip install libvirt-python`

**Comment by gandihar** [comment]
'Sup Woz!

> Did you use `salt-pip` to install libvirt?
> 
> `/opt/saltstack/salt/salt-pip install libvirt-python`

The pip install is part of a State that I apply to all my vm hosts:

``` yaml
libvirt-packages:
  pkg.installed:
    - pkgs: {{ vserver.pkgs | yaml }}
    - require:
      - mount: mount-vms
      - mount: mount-imgs

libvirt-pip:
  pip.installed:
    - name: libvirt-python
    - reload_modules: true
    - require:
      - pkg: libvirt-packages

```
_virt.pkgs_ comes from a map file, and varies slightly by osmajorrelease, but includes _all of the following_:
      - libvirt
      - libvirt-client
      - libvirt-daemon
      - qemu-kvm
      - virt-install
      - libvirt-devel

Oh, and also:

`(el9) $ salt-pip install libvirt-python
Requirement already satisfied: libvirt-python in /opt/saltstack/salt/extras-3.10 (9.10.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: /opt/saltstack/salt/bin/python3.10 -m pip install --upgrade pip
`
