### ISSUE TITLE
[BUG] pkgrepo.managed inserts malformed 'signedby' string in generated source file

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#65703]
**Description**
Debian based source.list files have you optionally specify a "signed-by" key in brackets to the absolute path of a gpg key. currently experiencing all of my salt `pkgrepo.managed` that previously worked are now inserting "signedby" text in the brackets. Looking at the `pkgrepo.py` modules it looks like this isnt happening here but in another salt module it uses and most likely a line parsing mistake is happening.

**SLS**
```yaml
# setting official postgres repository
ensure_postgres_repository_present:
  pkgrepo.managed:
    - humanname: Postgresql direct database repo
    - name: |
        deb [signed-by=/etc/apt/keyrings/postgresql_signing.key] 
        https://apt.postgresql.org/pub/repos/apt {{ grains.oscodename }}-pgdg main 
    - file: /etc/apt/sources.list.d/postgresql.list
    - keyurl: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    - aptkey: False
    - disabled: False
    - refresh: True
    - architectures: amd64
```
**state return**
```
          ID: ensure_postgres_repository_present
    Function: pkgrepo.managed
        Name: deb [signed-by=/etc/apt/keyrings/postgresql_signing.key] 
https://apt.postgresql.org/pub/repos/apt jammy-pgdg main 

      Result: False
     Comment: Failed to configure repo 'deb [signed-by=/etc/apt/keyrings/postgresql_signing.key] 
              https://apt.postgresql.org/pub/repos/apt jammy-pgdg main 
              ': E: Malformed entry 1 in list file /etc/apt/sources.list.d/postgresql.list ([option] not assignment)
              E: The list of sources could not be read.
     Started: 16:26:22.904497
    Duration: 58.133 ms
     Changes:   
```
**resulting file**
```
deb [signed-by=/etc/apt/keyrings/postgresql_signing.key signedby] https://apt.postgresql.org/pub/repos/apt jammy-pgdg main
```
The "signedby" in the brackets shouldnt be there. This happens for my nginx, docker, and postgres salt states that have worked for a long time prior to this. 

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
create a `pkgrepo.managed` state not using `aptkey` or `PPA` and set `refresh: True` to trigger apt refresh. 

**Expected behavior**
I expected the repo files to successfully be created resulting in a follow up installation from another salt state.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.5
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.3 jammy
        locale: utf-8
       machine: x86_64
       release: 6.2.0-1012-aws
        system: Linux
       version: Ubuntu 22.04.3 jammy
```
</details>

**Additional context**

**Comment by alan-cugler** [comment]
here is my workaround states for nginx source.list file:
```yaml
ensure_nginx_repo_present:
  file.managed:
    - name: /etc/apt/sources.list.d/nginx.list
    - source: salt://nginx/files/nginx.list
    - template: jinja
    - context:
        CODENAME: {{ grains.oscodename }}

refresh_apt_for_nginx_repo:
   pkg.uptodate:
     - name: force refresh
     - refresh: True
```

**Comment by whytewolf** [comment]
I can't seem to replicate this... 

tried with salt and docker states that already had signed-by in them like you describe. with refresh: True. 

```
docker_repo:
  pkgrepo.managed:
    - humanname: docker
    - name: deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   jammy stable∙
    - file: /etc/apt/sources.list.d/docker.list
    - refresh: True
    - architectures: amd64
    - keyurl: https://download.docker.com/linux/ubuntu/gpg
```
```
root@home:/etc/salt# salt-call state.apply tests.docker
local:
----------
          ID: docker_repo
    Function: pkgrepo.managed
        Name: deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   jammy stable
      Result: True
     Comment: Package repo 'deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   jammy stable' already configured
     Started: 22:36:04.077501
    Duration: 6.94 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   6.940 ms
```

```
root@home:/etc/salt# cat /etc/apt/sources.list.d/docker.list
deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   jammy stable
```


how is salt installed in the minion? just so i have a point of reference when looking at the code.

**Comment by alan-cugler** [comment]
Morning @whytewolf,
I'm still hoping its a problem on my end. so you not being able to reproduce is a point in that direction!

I am following the normal install instructions for ubuntu 22.04 described in the salt manual install directions.
https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html#install-salt-on-ubuntu-22-04-jammy-amd64
```bash
sudo curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main" | sudo tee /etc/apt/sources.list.d/salt.list
sudo apt-get update
sudo apt-get install salt-minion -y
```

one difference i see between your example and mine, is I add the pipe `|` in the value field of `- name: ` so that I can break up the long one line deb command into <80 character increments for easier developer readability. I will try keeping it on one line and see if that results in a successful source.list file provisioning by salt.

**Comment by alan-cugler** [comment]
hmmm I tried a one line `- name: ` version of my pkgrepo.managed state and that didnt work. I also tried stripping out jinja variables and that didnt effect anything.

**Comment by alan-cugler** [comment]
huh @whytewolf I found the culprit, though I dont know why.
adding the `- architectures: amd64` key:value to the state is what is producing the inserted "signedby" text in the brackets.

## with architectures keyword
```yaml
# setting official nginx repository
ensure_nginx_repository_present:
  pkgrepo.managed:
    - humanname: official Nginx stable repository
    - name: |
        deb [signed-by=/etc/apt/keyrings/nginx_signing.key] 
        http://nginx.org/packages/mainline/ubuntu/ {{ grains.oscodename }} nginx
    - file: /etc/apt/sources.list.d/nginx.list
    - keyurl: https://nginx.org/keys/nginx_signing.key
    - aptkey: False
    - disabled: False
    - refresh: True
    - architectures: amd64
```
## with architectures keyword resulting source.list file
```bash
# cat nginx.list
deb [signed-by=/etc/apt/keyrings/nginx_signing.key signedby] http://nginx.org/packages/mainline/ubuntu/ jammy nginx
```

## Without architectures keyword
``` yaml
# setting official nginx repository
ensure_nginx_repository_present:
  pkgrepo.managed:
    - humanname: official Nginx stable repository
    - name: |
        deb [signed-by=/etc/apt/keyrings/nginx_signing.key] 
        http://nginx.org/packages/mainline/ubuntu/ {{ grains.oscodename }} nginx
    - file: /etc/apt/sources.list.d/nginx.list
    - keyurl: https://nginx.org/keys/nginx_signing.key
    - aptkey: False
    - disabled: False
    - refresh: True
```
## resulting sources.list file
```bash
deb [signed-by=/etc/apt/keyrings/nginx_signing.key] http://nginx.org/packages/mainline/ubuntu/ jammy nginx
```

**Comment by whytewolf** [comment]
odd, i don't think it is that either..

I tried that with my salt_repo version. and when salt.list already had arch=amd64 it didn't change. so i tried removing arch=amd64 and this was the result.

```
local:
----------
          ID: salt_repo
    Function: pkgrepo.managed
        Name: deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64]
https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main

      Result: True
     Comment: Configured package repo 'deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64]
              https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main
              '
     Started: 16:00:21.829515
    Duration: 6863.551 ms
     Changes:
              ----------
              architectures:
                  ----------
                  new:
                      - amd64
                  old:
              line:
                  ----------
                  new:
                      deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main
                  old:
                      deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   6.864 s
root@salt00:/etc/apt/sources.list.d# cat salt.list
deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main
```

my salt_repo.sls for comparison. 

```
root@salt00:/srv/salt/tests# cat salt_repo.sls
salt_repo:
  pkgrepo.managed:
    - humanname: salt
    - name: |
        deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64]
        https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/latest jammy main
    - file: /etc/apt/sources.list.d/salt.list
    - refresh: True
    - aptkey: False
    - disabled: False
    - architectures: amd64
    - keyurl: https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
```

as a last resort i even removed my salt.list file and had it build a new one. and it still worked.
