### ISSUE TITLE
[BUG] acme.cert unsupported DNS provider return is unreachable

### ISSUE THREAD

**Issue by leeclemens** [saltstack/salt#65739]
**Description**
The "DNS plugin x is not supported" check and nice error message is unreachable.

**Setup**

test/cert.sls
```yaml
test_cert_acme_dns:
  acme.cert:
    - name: test.example.com
    - dns_plugin: invalid_dns_plugin
```

**Steps to Reproduce the behavior**
Use state above
`salt 'minion' state.sls test.cert`

```
          ID: test_cert_acme_dns
    Function: acme.cert
        Name: test.example.com
      Result: False
     Comment: Certificate test.example.com renewal failed with:
.....
```

**Expected behavior**
Expected `Result: False` with `Comment: DNS plugin 'invalid_dns_plugin' is not supported`

**Screenshots**
N/A

**Versions Report**

<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.5
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: centos 7.9.2009 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.105.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7.9.2009 Core
```
</details>

**Additional context**
N/A
