### ISSUE TITLE
[BUG] salt minion 3006.5 fails to work on customized Ubuntu 20.04.6

### ISSUE THREAD

**Issue by mato22222** [saltstack/salt#65742]
**Description**
After installing salt-minion 3006.5 I am receiving this error when running state file:
salt-minion[7955]: [ERROR   ] State 'pkg.installed' was not found in SLS '_states.install-api-prereq'
salt-minion[7955]: Reason: 'pkg' __virtual__ returned False: pkg module could not be loaded
[salt.state       :323 ][ERROR   ][7955] State 'pkg.installed' was not found in SLS '_states.install-api-prereq'#012Reason: 'pkg' __virtual__ returned False: pkg module could not be loaded

**Setup**
install_prereq.sls

install_dos2unix:
  pkg.installed:
    - name: dos2unix
install_python3_filelock:
  pkg.installed:
    - name: python3-filelock

State file is triggered by reactor, but same result was obtained by running salt state.apply

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
install Ubuntu 20.04 - customized
install salt 3006.5
execute state file
(it works with 3006.4 and older. But after update to 3006.5 it fails as above.
Also works with 3005.x)

(Include debug logs if possible and relevant)

**Expected behavior**
pkg.installed should install ubuntu package

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
Master:
Salt Version:
          Salt: 3006.5
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04.6 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-169-generic
        system: Linux
       version: Ubuntu 20.04.6 focal

Minion:

(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
salt-minion --versions-report
Salt Version:
          Salt: 3006.5
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: 0.40.1
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04.6 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-91-generic
        system: Linux
       version: Custom OS 20.04.6 focal
```
</details>

**Additional context**
Minion is customized Ubuntu:
real name was replaced with Custom in output

cat /etc/os-release 
NAME="Custom OS"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Custom OS"
VERSION_ID="20.04"
HOME_URL="https://www.<tbd>.t-systems.com/"
SUPPORT_URL="https://help.<tbd>.t-systems.com/"
PRIVACY_POLICY_URL="https://www.<tbd>.t-systems.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
