### ISSUE TITLE
[BUG] ssh_auth.present overwrites existing keys that are the same but different options

### ISSUE THREAD

**Issue by driskell** [saltstack/salt#65782]
**Description**

If you are using SSH certificates with differing principals to sign in, then `ssh_auth.present` can't be used in some cases as it only allows a key to exist once, regardless of the options. This prevents you having a modular setup if different parts of your system use the same certificate with differing principals to manage granular access.

**Setup**

Happening on many systems but it happens in a simple case of a masterless salt minion with local SLS files.

```
state1:
  ssh_auth.present:
    - name: PUB_CERT_KEY
    - user: root
    - enc: ssh-rsa
    - options:
      - cert-authority
      - principals="root"
    - comment: root access

state2:
  ssh_auth.present:
    - name: PUB_CERT_KEY
    - user: root
    - enc: ssh-rsa
    - options:
      - cert-authority
      - principals="monitor"
    - comment: monitor access
```

**Steps to Reproduce the behavior**

Use above states and note that only one is written

**Expected behavior**

Key to appear twice with different options

**Screenshots**

N/A

**Versions Report**
salt-call 3002.2

Masterless minion

**Additional context**

N/A

**Comment by Akm0d** [comment]
It looks like the issue you're encountering stems from having separate `ssh_auth.present` states for the same key, differentiated by the `principals` option. 

Rather than defining multiple states for the same key with different principals, you can combine the principals into a single state by grouping them in a comma-separated list.

#### Example:

Instead of:

```yaml
state1:
  ssh_auth.present:
    - name: PUB_CERT_KEY
    - user: root
    - enc: ssh-rsa
    - options:
      - cert-authority
      - principals="root"
    - comment: root access

state2:
  ssh_auth.present:
    - name: PUB_CERT_KEY
    - user: root
    - enc: ssh-rsa
    - options:
      - cert-authority
      - principals="monitor"
    - comment: monitor access
```

You can combine them into a single state like this:

```yaml
ssh_cert_access:
  ssh_auth.present:
    - name: PUB_CERT_KEY
    - user: root
    - enc: ssh-rsa
    - options:
      - cert-authority
      - principals="root,monitor"
    - comment: multi-access cert
```

### Why This Works:
By combining the principals into a single string (`principals="root,monitor"`), you avoid the issue where the same key is only allowed once in the authorized keys file. This allows you to manage multiple access levels using a single certificate more easily.

### Making It More Configurable:

If your use case requires flexibility (for example, managing principals across different environments or systems), you can use **Pillar data** or **Jinja templates** to dynamically generate the list of principals. This approach can help you configure the state based on specific requirements or environments.

#### Example with Jinja:

```yaml
ssh_cert_access:
  ssh_auth.present:
    - name: {{ pillar['pub_cert_key'] }}
    - user: {{ pillar['user'] or 'root' }}
    - enc: ssh-rsa
    - options:
      - cert-authority
      - principals="{{ ','.join(pillar['principals']) }}"
    - comment: {{ pillar['comment'] or 'multi-access cert' }}
```

Here, you can use Pillar data to specify the `pub_cert_key`, `user`, and `principals`. This makes the state more reusable across different systems or environments.

### Conclusion:
By combining the principals into one state, you can resolve the conflict of only one key being written. Additionally, leveraging Pillar or Jinja allows you to make the configuration more dynamic and flexible for varying use cases.

I don't see a reasonable way to manage the same key with different options, because then it would become difficult to manage existing keys without severely overcomplicating the `ssh_auth.present` function.
