### ISSUE TITLE
[BUG] Latest config plugin don't work with 3007.0rc1

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#65836]
**Description**
Latest config plugin don't work with 3007.0rc1.
3006.5 works just fine so something in or with 3007.0rc1 seems to cause this.

**Setup**
Create a raas server.
Create a master and minion machine and install 3007.0rc1.
Install the latest plugin on master

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [X] used bootstrap to install

**Steps to Reproduce the behavior**
Make sure master -> minion communiucation is working
Get latest plugin and install it.
Edit raas.config file (for example)
```
sseapi_server: https://10.206.242.174
id: test_ubu20
sseapi_ssl_validate_cert: False
```

Master key gets accepted to the raas server but the minion key does not.
![Screenshot 2024-01-10 at 11-16-25 Accepted Master Keys - Administration Config](https://github.com/saltstack/salt/assets/6766069/345c14dd-fc97-4489-afd9-9194c96a42c4)
![Screenshot 2024-01-10 at 11-16-45 Accepted - Minion Keys Config](https://github.com/saltstack/salt/assets/6766069/73261c70-cca8-46aa-acc0-f35412bad715)

I am expection a `test_ubu20` key in the minion keys

**Expected behavior**
Expects minion key to get accepted and able to run comands from the ui or cli and it will show up in th ui.

If I run a comand on the cli that works fine
```
root@salt:~# salt \* grains.item os
cava-6-242-173.eng.vmware.com:
    ----------
    os:
        Ubuntu
[WARNING ] Malformed event return: salt/job/20240110181038590782/returning
root@salt:~# 
```
but I see this in the logs
```
minion log
2024-01-10 18:10:39,049 [salt.transport.zeromq:396 ][ERROR   ][20929] Exception while running callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/salt/transport/zeromq.py", line 394, in consume
    await callback(msg)
  File "/usr/local/lib/python3.8/dist-packages/salt/channel/client.py", line 486, in wrap_callback
    await callback(decoded)
TypeError: object NoneType can't be used in 'await' expression
```

```
master log
2024-01-10 18:10:39,220 [salt.client      :1210][WARNING ][28793] Malformed event return: salt/job/20240110181038590782/returning
2024-01-10 18:10:40,456 [sseapiclient.apiclient:309 ][ERROR   ][20288] riq 8: ret.save_load: code 4000: No master was found by the ID: test_ubu20
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
root@salt:~# salt --versions
Salt Version:
          Salt: 3007.0rc1
 
Python Version:
        Python: 3.8.10 (default, Nov 22 2023, 10:22:35)
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.2
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.20.0
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.4
           ZMQ: 4.3.4
 
Salt Extensions:
        SSEAPE: 8.16.0.4
 
Salt Package Information:
  Package Type: Not Installed
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-29-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**
Not sure what is causing this issue, but 3006.5 works fine with no issues or anything in the logs so something seems to be causing this in 3007.0rc1.
