### ISSUE TITLE
[BUG] 3006.5 breaks grains sync - CRITICAL!

### ISSUE THREAD

**Issue by Heiko-san** [saltstack/salt#65901]
**Description**
Since we upgraded the minion from 3006.4 to 3006.5 on Debian minions an issue appeared when using custom grains modules.
It seams it can be enforced to trigger by repeatedly apply a single formula.
Then suddenly the minion "forgets" all of the custom grains modules.
This can then be "fixed" by running `salt '*' saltutil.sync_all` or a highstate apply.

However since forgetting the grains in the first place may lead to wrong configurations, when the error actually occurs, we consider this a very critical bug, that may break production systems!

**Steps to Reproduce the behavior**
* Upgrade minion to 3006.5
* apply any single formula approximately 1-3 times
* then at some point the minion should lose all grain modules
* this can be seen / fixed with `salt '*' saltutil.sync_all` or a highstate apply

**Expected behavior**
The grains should correctly be synced before single formula roll outs as well.

**Versions Report**

salt --versions-report on master

``` yaml
Salt Version:
          Salt: 3006.4
 
Python Version:
        Python: 3.10.13 (main, Oct  4 2023, 21:54:22) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.12
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04.6 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-104.119.4.2.el8uek.x86_64
        system: Linux
       version: Ubuntu 20.04.6 focal
```

salt-call --versions-report on minion
(also happens on other distris like ubuntu, redhat, ...)

``` yaml
Salt Version:
          Salt: 3006.5
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-17-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```
