### ISSUE TITLE
[BUG] NSIS Installer does not move Salt binaries when executed from `pkg.installed`. Behavior differs from manually running the installer.

### ISSUE THREAD

**Issue by holtkampjs** [saltstack/salt#65931]
**Description**
When upgrading from Salt installations in the "classic" location (Windows) to the OneDir directory structure, I've observed that the Salt binaries can be moved when executing the new installer manually, but not when executed from the command line in the manner that a `pkg.installed` Salt state would.

Current version: `Salt Minion 3003.4-1 (Python 3)`
Desired version: `3006.x`

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

The machine I'm trying to upgrade is a laptop running Windows 10. It has Salt version `3003.4-1` installed via the bootstrapper. This Salt Minion is installed with classic packaging and is located in the `C:\Salt` directory.

The Salt master is running Salt version `3006.3` currently.

The desired behavior is to upgrade my Salt Minion on the Windows laptop to `v3006.3` AND change the install location to OneDir packaging.

In applying the update via `pkg.installed`, the observed behavior is that the Salt binaries remain under `C:\Salt` but the `/move-config` flag successfully moves the config files to `C:\ProgramData\Salt Project\Salt`.

This differs from manually upgrading. When upgrading manually, I execute `C:\Salt\uninst.exe` and choose the option to leave the config files under `C:\Salt`. Then I manually run the installer downloaded from [Salt v3006.3 installer](https://repo.saltproject.io/salt/py3/windows/minor/3006.3/Salt-Minion-3006.3-Py3-AMD64-Setup.exe) which displays the default install location for the Salt binaries to be `C:\Program Files\Salt Project\Salt`. The manual installation is successful and behaves as we would like to recreate under `pkg.installed`.

As visible from the command line options on the `.exe` installer, there is an argument for `/install-dir=` but that is ignored on existing systems. The definition of this behavior in the NSIS installer is at: https://github.com/saltstack/salt/blob/master/pkg/windows/nsis/installer/Salt-Minion-Setup.nsi#L1492.

<details><summary>Output of ".\Salt-Minion-3006.3-Py3-AMD64-Setup.exe /?"</summary>

```txt
> .\Salt-Minion-3006.3-Py3-AMD64-Setup.exe /?

Help for Salt Minion installation
===============================================================================

/minion-name=           A string value to set the minion name. Default value is
                        'hostname'. Setting the minion name causes the installer
                        to use the default config or a custom config if defined

/master=                A string value to set the IP address or hostname of the
                        master. Default value is 'salt'. You may pass a single
                        master or a comma-separated list of masters. Setting
                        the master will cause the installer to use the default
                        config or a custom config if defined

/start-minion=          1 will start the minion service, 0 will not.
                        Default is 1

/start-minion-delayed   Set the minion start type to 'Automatic (Delayed Start)'

/default-config         Overwrite the existing config if present with the
                        default config for salt. Default is to use the existing
                        config if present. If /master and/or /minion-name is
                        passed, those values will be used to update the new
                        default config

                        Any existing config will be backed up by appending
                        a timestamp and a .bak extension. That includes
                        the minion file and the minion.d directory

/custom-config=         A string value specifying the name of a custom config
                        file in the same path as the installer or the full path
                        to a custom config file. If /master and/or /minion-name
                        is passed, those values will be used to update the new
                        custom config

                        Any existing config will be backed up by appending
                        a timestamp and a .bak extension. That includes
                        the minion file and the minion.d directory

/install-dir=           Specify the installation location for the Salt binaries.
                        This will be ignored for existing installations.

/move-config            If config is found at C:\salt it will be moved to %ProgramData%

/S                      Install Salt silently

/?                      Display this help screen

-------------------------------------------------------------------------------

Examples:

    Salt-Minion-3006.3-Py3-AMD64-Setup.exe /S

    Salt-Minion-3006.3-Py3-AMD64-Setup.exe /S /minion-name=myminion /master=master.mydomain.com /start-minion-delayed

    Salt-Minion-3006.3-Py3-AMD64-Setup.exe /S /minion-name=myminion /master=master.mydomain.com /install-dir="C:\Software\salt"

===============================================================================
```

</details>
 
<details><summary>Winrepo definition for the Salt v3003.4-1 and v3006.3 packages as rendered by pkg.get_repo_data</summary>

```yaml
salt-minion:
  '3003.4-1':
    full_name: Salt Minion 3003.4-1 (Python 3)
    install_flags: /S
    installer: https://repo.saltstack.com/windows/Salt-Minion-3003.4-1-Py3-AMD64-Setup.exe
    msiexec: false
    refresh: true
    source_hash: sha256=1ff27804e53e5fe4697d6ad32c4fa372ef8e8a5157a925972abea3761e7c0e8a
    uninstall_flags: /S
    uninstaller: C:\\Salt\\uninst.exe
    use_scheduler: true
  '3006.3':
    extra_install_flags: /move-config
    full_name: Salt Minion 3006.3 (Python 3)
    installer: https://repo.saltproject.io/salt/py3/windows/minor/3006.3/Salt-Minion-3006.3-Py3-AMD64-Setup.exe
    msiexec: false
    refresh: true
    source_hash: sha512=4673c0e5c8ac411aac0ca51745064e01382e1910e534e4162e8f50c4998c1702c869f1e440cb4690c528ba66371f577e871f988d894d4ff32fe15e1e1cc4d82f
    uninstall_flags: /S
    uninstaller: C:\\Program Files\\Salt Project\\Salt\\uninst.exe
    use_scheduler: true
```

</details>

**Steps to Reproduce the behavior**

To recreate this, you need a Salt Minion installed with the classic packaging and the desired upgrade defined in your `salt/win/repo-ng/` software definitions. 

<details><summary>Example salt-minion software package definition</summary>

```yaml
salt-minion:
  '3006.3':
    full_name: 'Salt Minion 3006.3 (Python 3)'
    installer: 'https://repo.saltproject.io/salt/py3/windows/minor/3006.3/Salt-Minion-3006.3-Py3-AMD64-Setup.exe'
    extra_install_flags: '/move-config'
    refresh: True
    msiexec: False
    use_scheduler: True
    source_hash: 'sha512=4673c0e5c8ac411aac0ca51745064e01382e1910e534e4162e8f50c4998c1702c869f1e440cb4690c528ba66371f577e871f988d894d4ff32fe15e1e1cc4d82f'
    uninstaller: 'C:\\Program Files\\Salt Project\\Salt\\uninst.exe'
    uninstall_flags: '/S'
  '<previously-installed-version>':
    full_name: 'Salt Minion <previously-installed-version> (Python 3)'
    # ...
    # Any relevant arguments
    # ...
    uninstaller: 'C:\\Salt\\uninst.exe'
```

</details>

Apply the upgrade by running a highstate with version `3006.3` passed as the version argument to `pkg.installed` for the package named `salt-minion` (e.g. `salt-call state.highstate`).

**Expected behavior**
The expected behavior is for Salt to upgrade to `Salt Minion 3006.3 (Python 3)` with `pkg.installed`. During this upgrade it is also expected that:

- Salt binaries: Move from `C:\Salt` to `C:\Program Files\Salt Project\Salt`
- Salt conf files: Move from `C:\Salt` to `C:\ProgramData\Salt Project\Salt`

It would be appreciated if there were a command line argument to reflect the behavior of the installer when run manually for changing from the classic packaging to onedir packaging.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

Master:
```yaml                                                                                                                     Salt Version:                                                                                                                                                         
    Salt: 3006.3                                                                                                                                                                                                                                                                                                  Python Version:                                                                                                                                                     
    Python: 3.10.4 (main, Apr 20 2022, 01:21:48) [GCC 10.3.1 20210424]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: alpine 3.14.6
        locale: utf-8
       machine: x86_64
       release: 5.15.0-91-generic
        system: Linux
       version: Alpine Linux 3.14.6
```

Minion before upgrade:
```yaml
Salt Version:
          Salt: 3003.4

Dependency Versions:
          cffi: 1.14.5
      cherrypy: 18.6.0
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.13
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.6
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.19041 SP0
```

</details>
