### ISSUE TITLE
[BUG] Source file fails when symnlinked.

### ISSUE THREAD

**Issue by Robert-Grundstrom** [saltstack/salt#66052]
**Description**
symlink breaks source path

**Error**
----------
          ID: firewall_conf
    Function: file.managed
        Name: /usr/local/bin/firewall.sh
      Result: False
     Comment: Source file salt://default/files/firewall/mysqlX.<domain>.fw not found in saltenv 'base'
     Started: 09:01:08.251696
    Duration: 3.45 ms
     Changes:   
----------

**Setup**

in my case 'firewall' is a symlink to another folder. This worked in 3006.5
```
root@salt-master:/# ls -larth /srv/saltstack/salt/default/files/firewall
lrwxrwxrwx 1 root root 14 Feb 13 10:37 /srv/saltstack/salt/default/files/firewall -> /srv/fwbuilder
```

```yaml
firewall_conf:
  file.managed:
    - names:
      - '/usr/local/bin/firewall.sh':
        - source: 'salt://{{slspath}}/files/firewall/{{salt['pillar.get']('firewall', "default.<DOMAIN>.fw")}}'
        - mode: 755
    - mode: 644
    - user: root
    - group: root
```

**Steps to Reproduce the behavior**
use a symlink in source path for file.managed.

**Versions Report**

```yaml
root@salt-master:/# salt --versions-report
Salt Version:
          Salt: 3006.6
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-28-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
