### ISSUE TITLE
[BUG] Publisher_ACL's doesn't work like expected in 3006

### ISSUE THREAD

**Issue by david-pulkowski** [saltstack/salt#66067]
**Description**
For simplicity. Create a user and create a simple publisher_acl restriction (see below) and run a command not in the publisher ACL. In a previous salt version 3004 for us. The example below would properly give us an authentication issue if we did anything not defined in the publisher_acl. So if you ran

```
salt '*' test.ping
Authorization error occurred. (the result we would expect)
```

And 
```
salt '*' pillar.items 
```
(and the display would be the pillar values as we would expect).

For testing use a simple setup:
Add proper user.

```
publisher_acl:
  USER-NAME:
	- pillar.items
```

Run a (with user in publisher_acl
```
salt '*' test.ping
```

Expected result:
```
Authorization error occurred.
```

Actual result:
Minions ping back.

**Setup**
create a user & set the publisher_acl to limit the user to be able to run a few salt commands

```
publisher_acl:
  USER-NAME:
	- pillar.items
```

switch to the user created and run a 
```
salt '*' test.ping
```

Then run a 

```
salt '*' pillar.items
```

- [X] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify) 
- KVM
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
When a command is run that is allowed it should run. When a command is not specified to be allowed it should be:

```
Authorization error occurred.
```

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.6

Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.11
     gitpython: 3.1.40
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: 5.0.1
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rhel 9.3 Plow
        locale: utf-8
       machine: x86_64
       release: 5.14.0-362.18.1.el9_3.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 9.3 Plow
```
</details>

**Additional context**

**Comment by d3zorg** [comment]
upgraded 3005.5 onedir to 3006.9 and having this issue

**Comment by b-a-t** [comment]
That, seems, work for me(while there are other issues with the `publisher_acl`):
```
publisher_acl:
  USER_NAME:
    - '*':
      - test.*
      - state.*
      - cmd.run
 ```
Note the extra level of the target scope for the states. I guess it's similar to the `external_auth`, possibly the same code is reused(which would make sense).

**Comment by ggiesen** [comment]
I looked into this on current 3006.x, and the exact simple-form config from the description now enforces correctly. This looks resolved by #69484, which was released in 3006.26.

End-to-end test on 3006.26 with the master running as the default `salt` user and:

```yaml
publisher_acl:
  alice:
    - pillar.items
```

- `alice$ salt '*' test.ping` -> `Authorization error occurred.` (denied, as expected)
- `alice$ salt '*' pillar.items` -> published to minions (allowed)
- `root# salt '*' test.ping` -> published (root bypasses publisher_acl, as expected)

The 3006 regression was not in the ACL logic. In 3006.3 the master switched to running as the `salt` user instead of root. That left `/var/cache/salt/master` and `/var/run/salt/master` owned `salt:salt` and mode 0750, so a non-root caller could no longer traverse them to read its per-user `.<user>_key` file or reach the master's IPC sockets. That surfaced as the connectivity failures tracked in #65317 (`Unable to connect to the salt master publisher` / `Authentication error occurred`). #69484 adds the world-execute (traverse-only) bit to `cachedir` and `sock_dir` when `publisher_acl`/`external_auth` is configured, and that is what restores enforcement here.

Two things to check if you still see commands run that you expect to be blocked:

1. Version: this needs 3006.26 or newer. The reports in this thread are on 3006.6 / 3006.9, before #69484.
2. sudo/root: `publisher_acl` is never applied to root, and it is not applied to a user running `sudo salt ...` unless `sudo_acl: True` is set (default is False; see the `sudo_acl` master config option). If the command was tested via `sudo salt`, it runs regardless of the acl by design.

If you can retest on 3006.26+ as the plain (non-sudo) user, the out-of-acl commands should be denied. Happy to dig further if you still see the bypass on a current build.
