### ISSUE TITLE
[BUG] file.managed and file.serialize default tmp_dir to relative path

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#66098]
**Description**
The `tmp_dir` parameter of these states defaults to `""`, which implies a relative path for the temporary directory. In most cases, this doesn't matter since the temporary directory is created, used, and then cleaned up properly. However, there are some edge cases where temporary directory creation is on a mount with `no_root_squash` and will subsequently fail since root cannot create and use the temporary directory.

The `tmp_dir` parameter is passed to `salt.utils.files.mkstemp()`, which in turn passes to `tempfile.mkstemp()`

```
salt.utils.files.mkstemp(suffix=tmp_ext, dir=tmp_dir)
```

```
In [1]: tempfile.mkstemp()
Out[1]: (11, '/tmp/tmpzm1l5gxi')

In [2]: tempfile.mkstemp(dir="")
Out[2]: (12, '/home/nhughes/tmpwk0f1s6j')
```

`mkstemp` makes an explicit `dir is not None` comparison, so an empty string will create a relative temporary directory path instead of using the system temp as the root.

**Expected behavior**
I would expect all temporary directory and temporary file operations to use the system temp unless explicitly configured otherwise.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
               Salt: 3006.5
 
Python Version:
             Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
               cffi: 1.14.6
           cherrypy: 18.6.1
           dateutil: 2.8.1
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 3.1.2
            libgit2: Not Installed
       looseversion: 1.0.2
           M2Crypto: Not Installed
               Mako: Not Installed
            msgpack: 1.0.2
       msgpack-pure: Not Installed
       mysql-python: Not Installed
          packaging: 22.0
          pycparser: 2.21
           pycrypto: Not Installed
       pycryptodome: 3.9.8
             pygit2: Not Installed
       python-gnupg: 0.4.8
             PyYAML: 6.0.1
              PyZMQ: 23.2.0
             relenv: 0.14.2
              smmap: Not Installed
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.4
 
Salt Extensions:
 saltext.prometheus: 2.0.3
     saltext.vmware: 23.6.29.0rc1
 
System Versions:
               dist: ubuntu 22.04.3 jammy
             locale: utf-8
            machine: x86_64
            release: 5.15.0-91-generic
             system: Linux
            version: Ubuntu 22.04.3 jammy
```
</details>
