### ISSUE TITLE
[BUG] Qyzylorda timezone not recognized by windows timezone module

### ISSUE THREAD

**Issue by vkotarov** [saltstack/salt#66176]
**Description**
A Windows server that has it's timezone set to "Qyzylorda Standard Time" will report it properly as grain but the win_timezone module will not recognize it and timezone.get_zone will return "Unknown".

**Setup**
salt-minion v3004.2 on Windows. The issue exists in most recent versions as well.

**Steps to Reproduce the behavior**
1. Set the timezone of windows minion to "Qyzylorda Standard Time"

2. salt win-minion cmd.run 'tzutil /g'
```yaml
win-minion:
    Qyzylorda Standard Time
```
3. salt win-minion grains.item timezone
```yaml
win-minion:
    ----------
    timezone:
        (UTC+05:00) Qyzylorda
```
4. salt win-minion timezone.get_zone
```yaml
win-minion:
    Unknown
```
**Expected behavior**

salt win-minion timezone.get_zone
```yaml
win-minion:
    Asia/Qyzylorda
```

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
    Salt Version:
              Salt: 3004.2
     
    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.7
         gitpython: Not Installed
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.4
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.20
          pycrypto: Not Installed
      pycryptodome: 3.10.1
            pygit2: Not Installed
            Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
      python-gnupg: 0.4.7
            PyYAML: 5.4.1
             PyZMQ: 19.0.0
             smmap: 4.0.0
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.2
     
    System Versions:
              dist:   
            locale: cp1252
           machine: AMD64
           release: 2019Server
            system: Windows
           version: 2019Server 10.0.17763 SP0 Multiprocessor Free

```
</details>

**Additional context**
