### ISSUE TITLE
[FEATURE REQUEST] allow pre-connection scripts to be run on salt-ssh

### ISSUE THREAD

**Issue by ctrix** [saltstack/salt#66210]
**Is your feature request related to a problem? Please describe.**

In our infrastructure we use to [sign SSH keys with Vault](https://developer.hashicorp.com/vault/docs/secrets/ssh/signed-ssh-certificates) in order to access servers.

The signature is valid only for a few minutes and after this time, the signature expires and login cannot be done anymore.

We need a way to run a script on the origin server in order to sign the ssh public key before salt-ssh actually tries to connect to the remote

**Describe the solution you'd like**

We would appreciate if we can have a pre-ssh connection hook that runs a specific script.

This option should reside in the roster, defaulting to None.
If set, a script should be run before attemting any connection when salt-ssh is invoked

```
test:
    host: 172.25.17.66
    user: ctrix
    grains:
      roles:
        - foo
    priv: ~/.ssh/id_ecdsa -o IdentityFile=~/.ssh/id_ecdsa_admin_signed
    tty: True
    sudo: False
    ssh_pre_hook: /path/to/script param1 param2
``` 

**Describe alternatives you've considered**

Abandoning SaltStack is the only suitable alternative. [troll mode]

**Additional context**

I'm opening a merge request for this feature. Doesn't want to be the final solution but it definitely addresses my concerns.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.
