### ISSUE TITLE
[BUG] state.sls and state.highstate use different saltenv

### ISSUE THREAD

**Issue by genaumann** [saltstack/salt#66244]
**Description**
I have configured several environments with different pillar values in Salt.
When I run `salt '*' state.highstate`, the pillar values of all environments are merged.
But if I run `salt '*' state.sls openssh.config`, the pillar values of the base environment are used (which is the correct behavior).
So I have different configurations when I run a **highstate** and a specific sls.

`salt '*' state.sls openssh.config`
(Uses base environment)
```
File /etc/ssh/sshd_config is in the correct state
```

`salt '*' state.highstate`
(Merges base + dev)
```
-AllowGroups Group1 Group2
+AllowGroups Group1 Group2 Group3
```

In file [state.py](https://github.com/saltstack/salt/blob/master/salt/modules/state.py#L1384) you can see `state.sls` sets the default environment to `base` - the function `state.highstate` does not.

**Setup**
__Master Conf__
```
top_file_merging_strategy: same  # do not merge envs
pillarenv_from_saltenv: True
state_top_saltenv: base
pillar_source_merging_strategy: smart
pillar_merge_lists: True # merge lists

file_roots:
  base:
    - /srv/git/base/suma-salt/states
    - /srv/git/base/suma-salt/formula/*
  test:
    - /srv/git/test/suma-salt/states
    - /srv/git/test/suma-salt/formula/*
  dev:
    - /home/dev/git/suma-salt/states
    - /home/dev/git/suma-salt/formula/*
pillar_roots:
  base:
    - /srv/git/base/suma-salt/pillar
    - /srv/pillar
  test:
    - /srv/git/test/suma-salt/pillar
  dev:
    - /home/dev/git/suma-salt/pillar
```

**Pillar in base**
```
AllowGroups:
  - Group1
  - Group2
```

**Pillar in dev**
```
AllowGroups:
  - Group1
  - Group2
  - Group3
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Expected behavior**
I would except on `state.highstate` the default saltenv is set to **base** like in `state.sls`.

**Versions Report**
Same on 3007.
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.0
 
Python Version:
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.28.4
  looseversion: 1.0.2
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 21.3
     pycparser: 2.17
      pycrypto: 3.9.0
  pycryptodome: Not Installed
        pygit2: 0.28.2
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: sles 15.4 2022.08
        locale: UTF-8
       machine: x86_64
       release: 5.14.21-150400.24.108-default
        system: Linux
       version: SLES 15.4 2022.08
```
</details>
