### ISSUE TITLE
[BUG] pillar.ls doesn't accept kwargs

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#66262]
**Description**
The `pillar.ls` execution module function doesn't accept kwargs even though it just passes off to `pillar.items`... which _does_ accept kwargs.

**Steps to Reproduce the behavior**
```
root@u22-party-01:~# salt-call pillar.ls pillarenv=prod
The following keyword arguments are not valid: pillarenv=prod
```

**Expected behavior**
`pillar.ls` should pass along any args or kwargs to `pillar.items`, which will use any that it supports.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
               Salt: 3007.0
 
Python Version:
             Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
               cffi: 1.16.0
           cherrypy: 18.8.0
           dateutil: 2.8.2
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 3.1.3
            libgit2: Not Installed
       looseversion: 1.3.0
           M2Crypto: Not Installed
               Mako: Not Installed
            msgpack: 1.0.7
       msgpack-pure: Not Installed
       mysql-python: Not Installed
          packaging: 23.1
          pycparser: 2.21
           pycrypto: Not Installed
       pycryptodome: 3.19.1
             pygit2: Not Installed
       python-gnupg: 0.5.2
             PyYAML: 6.0.1
              PyZMQ: 25.1.2
             relenv: 0.15.1
              smmap: Not Installed
            timelib: 0.3.0
            Tornado: 6.3.3
                ZMQ: 4.3.4
 
Salt Extensions:
 saltext.prometheus: 2.0.3
     saltext.vmware: 23.6.29.0rc1
 
Salt Package Information:
       Package Type: onedir
 
System Versions:
               dist: ubuntu 22.04.4 jammy
             locale: utf-8
            machine: x86_64
            release: 5.15.0-100-generic
             system: Linux
            version: Ubuntu 22.04.4 jammy

```
</details>
