### ISSUE TITLE
[BUG] aptpkg.remove "Unable to locate package" for non-existent package

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#66260]
**Description**
Attempting to remove a non-existent package will throw an error. Prior to 3007.0, the behavior was to ignore non-existent packages as they weren't installed. This new behavior is problematic because you can run into scenarios where a once-valid package drops out of cache over time, which introduces errors into state runs.

**Steps to Reproduce the behavior**
```
root@u22-party-01:~# salt-call pkg.remove notthere
[ERROR   ] Command 'systemd-run' failed with return code: 100
[ERROR   ] stdout: Reading package lists...
Building dependency tree...
Reading state information...
[ERROR   ] stderr: Running scope as unit: run-r7503810e867a466c8abc8ca17b7b0b81.scope
E: Unable to locate package notthere
[ERROR   ] retcode: 100
Error running 'pkg.remove': Problem encountered removing package(s). Additional info follows:

changes:
    ----------
errors:
    - Running scope as unit: run-r7503810e867a466c8abc8ca17b7b0b81.scope
      E: Unable to locate package notthere
```

**Expected behavior**
The previous behavior should be restored.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
               Salt: 3007.0
 
Python Version:
             Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
               cffi: 1.16.0
           cherrypy: 18.8.0
           dateutil: 2.8.2
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 3.1.3
            libgit2: Not Installed
       looseversion: 1.3.0
           M2Crypto: Not Installed
               Mako: Not Installed
            msgpack: 1.0.7
       msgpack-pure: Not Installed
       mysql-python: Not Installed
          packaging: 23.1
          pycparser: 2.21
           pycrypto: Not Installed
       pycryptodome: 3.19.1
             pygit2: Not Installed
       python-gnupg: 0.5.2
             PyYAML: 6.0.1
              PyZMQ: 25.1.2
             relenv: 0.15.1
              smmap: Not Installed
            timelib: 0.3.0
            Tornado: 6.3.3
                ZMQ: 4.3.4
 
Salt Extensions:
 saltext.prometheus: 2.0.3
     saltext.vmware: 23.6.29.0rc1
 
Salt Package Information:
       Package Type: onedir
 
System Versions:
               dist: ubuntu 22.04.4 jammy
             locale: utf-8
            machine: x86_64
            release: 5.15.0-100-generic
             system: Linux
            version: Ubuntu 22.04.4 jammy
 
```
</details>
