### ISSUE TITLE
[BUG] Salt Master Cluster Logging - [ERROR   ] Received new key from peer

### ISSUE THREAD

**Issue by clayoster** [saltstack/salt#66266]
**Description**
After setting up a master cluster on 3007.0 I noticed the following errors being logged whenever the salt-master service is restarted. These logs appear to be indicating successful communication between masters on TCP 4520, not errors.

```
2024-03-24T13:10:27.409651-05:00 salt1 salt-master[108565]: [ERROR   ] Received new key from peer 192.168.40.76
2024-03-24T13:10:27.617687-05:00 salt1 salt-master[108565]: [ERROR   ] Received new key from peer 192.168.40.77
```

**Setup**
Three Debian 12 VMs configured as a Salt Master Cluster

- [X] on-prem machine
- [X] VM (KVM)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Tail /var/log/salt/master and restart the salt-master service on one of the cluster nodes

**Expected behavior**
I would expect to only see these messages when the master `log_level` is set to `info`

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3007.0

Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: 1.7.2
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: 1.14.1
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Package Information:
  Package Type: onedir

System Versions:
          dist: debian 12.5 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 12.5 bookworm
```
</details>
