### ISSUE TITLE
[BUG] targeting non-existed minion got return code as 0 

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#66274]
**Description**

salt-master return silently without error code equal to one  if a target minion name doesn't exist.
I think this started with version 3006.x

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ x] onedir packaging
- [x ] used bootstrap to install

**Steps to Reproduce the behavior**
```
# query a connected minion on existence of file not there. we got error code return as expected 1.
me@salt]$sudo salt  minion02  cmd.run "ls /tmp/ttt.txt" ;echo $?
minion02:
    ls: cannot access '/tmp/ttt.txt': No such file or directory


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 1
# of minions that did not return: 0
# of minions with errors: 1
-------------------------------------------
ERROR: Minions returned with non-zero exit code
1
me@salt]


```

**Expected behavior**
Query a not connected minion on existence of file not there. we got error code 0 not  expected 1.
```
 sudo salt  minino02xx  cmd.run "ls /tmp/ttt.txt" ;echo $?

<snipped>
# of minions with errors: 0
-------------------------------------------
0
```

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
```yaml
Salt Version:
          Salt: 3007.0

Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Package Information:
  Package Type: onedir

System Versions:
          dist: rocky 8.9 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 4.18.0-513.18.1.el8_9.x86_64
        system: Linux
       version: Rocky Linux 8.9 Green Obsidian

```
</details>

**Additional context**
