### ISSUE TITLE
[BUG] macOS: cmd.run env variables doesn't work when running with runas argument

### ISSUE THREAD

**Issue by jupe** [saltstack/salt#66285]
**Description**
cmd.run environment variables doesn't work with runas

**Setup**
- [x] on-prem machine

salt master runs on linux machine. minion runs on `macOS 14.3.1` machine and uses minion release `3006.6`. Master probably doesn't matter here.

**Steps to Reproduce the behavior**

```
/home/salt# salt 'mac' cmd.run 'echo $HELLO' env='{"HELLO": "there"}' runas='me'
mac:
/home/salt# salt 'mac' cmd.run 'echo $HELLO' env='{"HELLO": "there"}'           
mac:
    there

/home/salt# salt 'nuc' cmd.run 'echo $HELLO' env='{"HELLO": "there"}'
nuc:
    there
/home/salt# salt 'nuc' cmd.run 'echo $HELLO' env='{"HELLO": "there"}' runas='ubuntu'
nuc:
    there
```

same happens when running with sls file.

**Expected behavior**

cmd.run works same way than in linux regardless `runas` usage.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
# salt --versions-repor
Salt Version:
          Salt: 3006.7
 
Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: 1.7.2
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: 1.14.1
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.3 jammy
        locale: utf-8
       machine: x86_64
       release: 6.5.0-1014-aws
        system: Linux
       version: Ubuntu 22.04.3 jammy
```
</details>
