### ISSUE TITLE
[BUG] `gpg` modules do not respect `GNUPGHOME` from (shell) environment config

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#66313]
**Description**
The `gpg` modules do not respect a process-specific or (when `user` is passed) user-set `GNUPGHOME` env var. The former is always expected, the latter is in contrast to the `cmd` modules, which keep the user environment intact.

**Setup**
Irrelevant

**Steps to Reproduce the behavior**
(for bash, the user issue)
* `echo 'export GNUPGHOME=$HOME/.local/share/gnupg' >> ~/.bashrc`
* `exec $SHELL -l`
* `mkdir -p $GNUPGHOME && chmod 0700 $GNUPGHOME`
* `gpg --receive-key 8ABE4EFCF0F4B24BFF2AAF90D570F2D34EA0793D`
* `sudo salt-call gpg.list_keys user=$(whoami)`

**Expected behavior**
```
local:
    |_
      ----------
      created:
          2014-07-04
      expires:
          2025-03-21
      fingerprint:
          8ABE4EFCF0F4B24BFF2AAF90D570F2D34EA0793D
      keyLength:
          4096
      keyid:
          D570F2D34EA0793D
      ownerTrust:
          Unknown
      trust:
          Unknown
      uids:
          - SaltStack Security Team <security@saltstack.com>
```

**Screenshots**
Lists `~/.gnupg` (or crashes if it does not exist, see https://github.com/saltstack/salt/issues/66312)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.7

Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.11
     gitpython: 3.1.42
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.15.1
         smmap: 5.0.1
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 9.3 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-362.13.1.el9_3.x86_64
        system: Linux
       version: Rocky Linux 9.3 Blue Onyx
```
</details>

**Additional context**
I will submit a PR
