### ISSUE TITLE
[BUG] salt.module.win_task.info wrong execution_time_limit returned when set to False

### ISSUE THREAD

**Issue by JanCle** [saltstack/salt#66347]
**Description**

When creating a Task without an Execution Time Limit with execution_time_limit = False,
the ExecutionTimeLimit is set to "PT0S" as this is the way to disable it.

https://github.com/saltstack/salt/blob/97e9395b7f1ad53c449bf166be33cea01b9f91be/salt/modules/win_task.py#L1123-L1125

This value is not correctly evaluted when running task.info, as the used duration-mapping has no value for PT0S.

https://github.com/saltstack/salt/blob/97e9395b7f1ad53c449bf166be33cea01b9f91be/salt/modules/win_task.py#L95-L117

Since the function "_reverse_lookup" sets value_index = -1 from the getgo, task.info will always return "365 days"  in this case.

https://github.com/saltstack/salt/blob/97e9395b7f1ad53c449bf166be33cea01b9f91be/salt/modules/win_task.py#L235-L256

**Steps to Reproduce the behavior**

Run following state against a Windows-minion.

```yaml
run_some_script:
  module.run:
    - task.create_task:
      - name: run_some_script
      - action_type: Execute
      - arguments: -ExecutionPolicy Bypass -File .\some_script.ps1
      - cmd: PowerShell.exe
      - ac_only: True
      - execution_time_limit: False
      - run_if_idle: False
      - run_if_network: False
      - start_when_available: False
      - allow_demand_start: True
      - delete_after: False
      - force_stop: True
      - multiple_instances: No New Instance
      - restart_interval: False
      - stop_if_on_batteries: True
      - wake_to_run: False
      - force: True
```
Run following command if state was successful:

```bash
salt windows-minion task.info run_some_script
```
**Expected behavior**

The returned value should be "False" or "Indefenitely".

**Versions Report**
<details><summary>salt --versions-report </summary>

from master-of-masters:
```yaml
Salt Version:
          Salt: 3006.4

Python Version:
        Python: 3.10.13 (main, Oct  4 2023, 21:54:22) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.12
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.3 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-101-generic
        system: Linux
       version: Ubuntu 22.04.3 jammy
```

from minion:
```yaml
    Salt Version:
              Salt: 3006.4

    Python Version:
            Python: 3.10.13 (heads/main:7ee24e6, Sep  6 2023, 02:19:49) [MSC v.1936 64 bit (AMD64)]

    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.7
         gitpython: Not Installed
            Jinja2: 3.1.2
           libgit2: Not Installed
      looseversion: 1.0.2
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 22.0
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.10.1
            pygit2: Not Installed
      python-gnupg: 0.4.8
            PyYAML: 6.0.1
             PyZMQ: 25.0.2
            relenv: 0.13.12
             smmap: 4.0.0
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4

    System Versions:
              dist:
            locale: cp1252
           machine: AMD64
           release: 2022Server
            system: Windows
           version: 2022Server 10.0.20348 SP0 Multiprocessor Free
```

</details>

**Additional context**

A simple fix would be to add an option to the duration-mapping with "PT0S", preferabley for the Key "Indefenitely".
Optimally, instead of setting False to disable and to prevent confusion, setting to Indefenitely should be set to PT0S rather than False.
