### ISSUE TITLE
[BUG] nftables.build_rule breaks ipv6 rules by using the wrong syntax for source and destination addresses

### ISSUE THREAD

**Issue by jdelic** [saltstack/salt#66382]
**Description**
Consider the following state:
```yaml
basics-tcp-out22-send-ipv6:
    nftables.append:
        - table: filter
        - chain: output
        - family: ip6
        - jump: accept
        - destination: '::/0'
        - dport: 22
        - match: state
        - connstate: new
        - proto: tcp
        - save: True
```
This state would create a nftables rule that allows the box to connect to port 22 on every IPv6 address out there. However, [nftables.build_rule](https://github.com/saltstack/salt/blob/aad71fdbcfcd7845b11e67f33a1173a22324ce8e/salt/modules/nftables.py#L175) creates the following nft call:
```
nft add rule ip6 filter output ct state { new } ip daddr ::/0 tcp dport { 22 } accept
```
which leads to the following error:
```
Error: conflicting protocols specified: ip6 vs ip
```

**Steps to Reproduce the behavior**
Spin up an ipv6 enabled box and try to apply the above state.

**Expected behavior**
The correct command would read:
```
nft add rule ip6 filter output ct state { new } ip6 daddr ::/0 tcp dport { 22 } accept
```

**Versions Report**
I observed this with 3007.0 (Chlorine)
