### ISSUE TITLE
[BUG] `salt-minion 3007.0 (Chlorine)` cannot seem to use `file.append` in some cases. Throws `AttributeError: 'list' object has no attribute 'decode'`

### ISSUE THREAD

**Issue by ipaqmaster** [saltstack/salt#66404]
**Description**

Trying to `salt-call state.sls someAppendState` causes `AttributeError: 'list' object has no attribute 'decode'`

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
KVM and desktop. All are impacted.
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

An example state in a file on its own which is falling over: 

```
appender:
  file.append:
    - name: /a
    - source:
      - salt://b
```

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.0
 
Python Version:
        Python: 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.9.0
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: 0.40.1
          Mako: 1.3.2
       msgpack: 1.0.5
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.2
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.12.0
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.4
           ZMQ: 4.3.5
 
Salt Package Information:
  Package Type: Not Installed
 
System Versions:
          dist: arch rolling n/a
        locale: utf-8
       machine: x86_64
       release: 6.7.8-arch1-1
        system: Linux
       version: Arch Linux rolling n/a
```
</details>

**Additional context**

Archlinux 6.7.8-arch1-1

**Comment by lkubb** [comment]
Has this worked before? From the documentation, `source` needs to be a single, string-valued source. You can pass a list of files to `sources` instead.

**Comment by ipaqmaster** [comment]
I think it clicked for me this morning coming back to this.

I was using `- sources:` but Salt itself was unhappy with the object being a single `string` rather than a `list` object. This checks out with how the source file was working when I appended it with the other file.append state with the other files as a single invocation.

**Comment by ipaqmaster** [comment]
This also means that when the jinja works out to that single file source - `file.append` spits `No text found to append. Nothing appended` instead of appending that file again anyway.

I had to prepend a source:

`- salt://blank` to prevent this "potential single source situation" and the file also cannot be actually blank otherwise salt says `Failed to read rendered template file /var/cache/salt/minion/extrn_files/base/blank (salt://blank)` because its empty. Aaaaah.

file.append just needs to be OK if it sees a single source whether its a string or a list. Regardless of whether `- source:` or `- sources:` is used.

**Comment by whytewolf** [comment]
> This also means that when the jinja works out to that single file source - `file.append` spits `No text found to append. Nothing appended` instead of appending that file again anyway.
> 
> I had to prepend a source:
> 
> `- salt://blank` to prevent this "potential single source situation" and the file also cannot be actually blank otherwise salt says `Failed to read rendered template file /var/cache/salt/minion/extrn_files/base/blank (salt://blank)` because its empty. Aaaaah.
> 
> file.append just needs to be OK if it sees a single source whether its a string or a list. Regardless of whether `- source:` or `- sources:` is used.

no, `source` and `sources` are two separate things and shall always be separate. source does not take a list sources does. `sources` does work with a single source item when that single source item is passed in as a list of one item. i just tested this

if you don't now if you are going to have multiple sources. use `sources` and pass a list to it. even if that list only has one item. 

if you are always going to use a single source `source` takes a string. 

this is operating as expected.

**Comment by ipaqmaster** [comment]
I know. Neither work.

**Comment by lkubb** [comment]
I can't reproduce it either though.

/srv/salt/file1.txt has `foo`
/srv/salt/file2.txt has `bar`
/srv/salt/append.sls:

```yaml
create:
  file.touch:
    - names:
      - /tmp/foo_source
      - /tmp/foo_sources

/tmp/foo_source:
  file.append:
    - source: salt://file1.txt

/tmp/foo_sources:
  file.append:
    - sources:
      - salt://file1.txt
      - salt://file2.txt

show source:
  module.run:
    - file.read:
      - /tmp/foo_source

show sources:
  module.run:
    - file.read:
      - /tmp/foo_sources
```

Output:
```console
$ salt-call state.apply append
local:
----------
          ID: create
    Function: file.touch
        Name: /tmp/foo_source
      Result: True
     Comment: Created empty file /tmp/foo_source
     Started: 11:16:38.533344
    Duration: 22.842 ms
     Changes:
              ----------
              new:
                  /tmp/foo_source
----------
          ID: create
    Function: file.touch
        Name: /tmp/foo_sources
      Result: True
     Comment: Created empty file /tmp/foo_sources
     Started: 11:16:38.556264
    Duration: 0.358 ms
     Changes:
              ----------
              new:
                  /tmp/foo_sources
----------
          ID: /tmp/foo_source
    Function: file.append
      Result: True
     Comment: Appended 1 lines
     Started: 11:16:38.556656
    Duration: 17.603 ms
     Changes:
              ----------
              diff:
                  ---

                  +++

                  @@ -0,0 +1 @@

                  +foo
----------
          ID: /tmp/foo_sources
    Function: file.append
      Result: True
     Comment: Appended 2 lines
     Started: 11:16:38.574374
    Duration: 10.26 ms
     Changes:
              ----------
              diff:
                  ---

                  +++

                  @@ -0,0 +1,2 @@

                  +foo
                  +bar
----------
          ID: show source
    Function: module.run
      Result: True
     Comment: file.read: foo
     Started: 11:16:38.587198
    Duration: 0.419 ms
     Changes:
              ----------
              file.read:
                  foo
----------
          ID: show sources
    Function: module.run
      Result: True
     Comment: file.read: foo
              bar
     Started: 11:16:38.587663
    Duration: 0.268 ms
     Changes:
              ----------
              file.read:
                  foo
                  bar

Summary for local
------------
Succeeded: 6 (changed=6)
Failed:    0
------------
Total states run:     6
Total run time:  51.750 ms
```
