### ISSUE TITLE
[BUG] Memory leak in salt-master reactor

### ISSUE THREAD

**Issue by gbarreiro** [saltstack/salt#66405]
**Description**
The salt-master reactor process in Salt 3006.2 seems to increase its memory consumption every time an event triggering a reactor is received, without releasing it later.

**Setup**
 Kubernetes container running salt-master 3006.2, with the following reactor config file (`/etc/salt/master.d/reactor.conf`):
```yaml
reactor:
  - 'hello/test':
    - /srv/salt/reactor/dummy.sls
reactor_worker_threads: 20
```

And the following reactor file (`/srv/salt/reactor/dummy.sls`):
```yaml
startup.orchestration:
  runner.test.sleep:
    - s_time: 5
```

**Steps to Reproduce the behavior**
1. Open a shell within the container and run `top`, then click `c` to display the full command for each process and then `Shift + M` to sort the processes by memory consumption.
2. Open another shell within the container and run `while true; do salt-run event.send hello/test; sleep 10; done`
3. Observe the memory consumption for the `salt-master Engine Reactor` process in the `top` window.

**Expected behavior**
The memory consumption for the `Reactor` process should stay stable

**Actual behavior**
The memory consumption for the `Reactor` process grows steadily, and it does not go down once the event sending loop is interrupted. Eventually the container reaches a OOM.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.2

Python Version:
        Python: 3.10.12 (main, Aug  3 2023, 21:47:10) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.15.133+
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Comment by whytewolf** [comment]
as a first test we will require you to try a version that is currently supported. 3006.7 or 3007. to validate that this is an issue that hasn't already been addressed.

**Comment by amalaguti** [comment]
If it helps, I tried to replicate the test in a 3006.4 server, even with a shorter sleep timer of 1 second in the while command, didn't notice any increase on memory consumption

**Comment by whytewolf** [comment]
> If it helps, I tried to replicate the test in a 3006.4 server, even with a shorter sleep timer of 1 second in the while command, didn't notice any increase on memory consumption

humm. I would prefer something newer but that sounds like the issue was already addressed between 3006.2 and 3006.4

**Comment by dwoz** [comment]
There were several issues with cleaning up sockets in those versions. Can this be replicated on 3006.8?

**Comment by twangboy** [comment]
Closing due to lack of response.

**Comment by Sxderp** [comment]
I believe I'm seeing reactor (and maybe netapi) memory leaks too.

```
[root@arcs-msalt01 ~]# salt --versions-report
Salt Version:
          Salt: 3007.7
 
Python Version:
        Python: 3.10.18 (main, Aug 27 2025, 22:35:38) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
  cryptography: 42.0.5
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.6
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.20.5
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.4.2
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: rhel 9.6 Plow
        locale: utf-8
       machine: x86_64
       release: 5.14.0-570.41.1.el9_6.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 9.6 Plow
 ```

Reactor config.

```yaml
reactor:
  - salt/auth:
    - /srv-unit/cos-main-v2/msalt/reactors/paprika.sls
```

```sls
{% if 'act' in data and data['act'] == 'pend' %}

paprika_autoauth:
  runner.paprika.autoauth:
    - args:
      - minion_id: {{ data['id'] }}
      - endpoint: https://pepper.salt.gatech.edu

{% endif %}
```

```python
"""Salt runner for auto-accepting minion keys."""
# Version: 1.5.0

import time
from http import HTTPStatus

from salt.client import LocalClient
from salt.utils import event
from salt.utils import http
from salt.wheel import WheelClient


def _expecting_bind(minion_id, endpoint):
    """
    Check if the minion has been blessed via the Paprika web service.

    Arguments:
        minion_id (str): name of the minion
        endpoint (str): URL of the paprika service

    Returns:
        bool
    """
    path = '/bind/check/{0}'.format(minion_id)
    return http.query(endpoint + path, status=True)['status'] == HTTPStatus.OK


def autoauth(minion_id, endpoint):
    """
    Automatically authenticate a minion to the salt master if conditions are met.

    Arguments:
        minion_id (str): name of the minion to be authenticated
        endpoint (str): URL of the paprika service
    """
    if _expecting_bind(minion_id, endpoint):
        wheel = WheelClient(__opts__)  # noqa: F821
        wheel.cmd('key.accept', [minion_id])
```

**Comment by whytewolf** [comment]
@Sxderp could you have pleased included the memory info. not just what you are running. but the result of running it. 

also as a side node the following. 

```
{% if 'act' in data and data['act'] == 'pend' %}
paprika_autoauth:
  runner.state.orch:
    - args:
      - mods: orch.paprika
      - pillar:
          minion_id: {{ data['id'] }}
          endpoint: https://pepper.salt.gatech.edu

{% endif %}
```

```
{% set minion_id = salt["pillar.get"]("minion_id") %}
{% set url = salt["pillar.get"]("endpoint") ~ '/bind/check/' ~ minion_id %}

{{url}}:
    http.query:
      - status: 200

add {{minion_id}}:
  salt.wheel:
    - name: key.accept
    - match: {{minion_id}}
    - require:
      - http: {{url}}
```
