### ISSUE TITLE
[BUG] x509_v2 ignores keyUsage?

### ISSUE THREAD

**Issue by tomm144** [saltstack/salt#66434]
**Description**
Issued certificate doesn´t fit setting keyUsage in signing policy.

**Setup**

>x509_signing_policies:
  sign_poolicy
    - minions: "*"
    - signing_private_key: /etc/pki/ca..key
    - signing_cert: /etc/pki/ca..crt
    - C: <redacted>
    - ST: <redacted>
    - L: <redacted>
    - basicConstraints: "critical CA:false"
    - keyUsage: "critical Digital Signature, keyEncipherment"
    - subjectKeyIdentifier: hash
    - authorityKeyIdentifier: keyid,issuer:always
    - days_valid: 365
    - days_remaining: 30
    - copypath: /etc/pki/issued_certs/

Issued certificate has keyUsage:

> X509v3 Key Usage: critical
                Key Encipherment

- [ ] on-prem machine
-  VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
run certificate issue with signing policy contains keyUsage mentioned above

**Expected behavior**
Have certificate Usage like this

>  X509v3 Key Usage: critical
                Digital Signature, Key Encipherment

**Versions Report**
<details><summary>

</summary>

```yaml
MASTER
Salt Version:
          Salt: 3006.7
 
Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: 1.3.0
  looseversion: 1.0.2
      M2Crypto: 0.39.0
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: 1.7.0
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.4 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-105-generic
        system: Linux
       version: Ubuntu 22.04.4 jammy
       
MINION

Salt Version:
          Salt: 3006.7
 
Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: 0.39.0
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.1 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-102-generic
        system: Linux
       version: Ubuntu 22.04.1 jammy
       
```
</details>
