### ISSUE TITLE
[BUG] aptpkg: Updating held packages via sources does not work

### ISSUE THREAD

**Issue by krombel** [saltstack/salt#66459]
**Description**
When installing packages via state `pkg.installed` by using the `sources` arg updating of held packages does not work.

**Setup**
```
common-pkgs:
  pkg.installed:
    - sources:
      - pkg1: salt://common/pkg1_{{ pkg1_version }}.deb
      - pkg2: salt://common/pkg2_{{ pkg2_version }}.deb
    - hold: True
    - update_holds: True
```

**Steps to Reproduce the behavior**
```
# salt-call state.apply common
local:
----------
          ID: common-pkgs
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit: run-rc481e0a775024bad8e2077bd25caa6d3.scope
                    E: Held packages were changed and -y was used without --allow-change-held-packages.
     Started: 11:21:49.207895
    Duration: 12991.293 ms
     Changes:
```
**Expected behavior**
update would be working

**Screenshots**

**Versions Report**
3007.0

**Additional context**
In debug logs I see folloging line:
```
[DEBUG   ] Current version (['1.0.8922-1']) did not match desired version specification (salt://common/pkg1_1.0.9457-1.deb), adding to installation targets
```
It seems, that `all_pkgs` [in aptpkg.py](https://github.com/saltstack/salt/blob/v3007.0/salt/modules/aptpkg.py#L1020) does contain the path an not the package name
=> `pkg1` will not be added to the `to_unhold` array so it wont be "unholded" before the install is triggered.

I see 2 possible approaches to fix this:
1. extend targeted_names with the keys of the `sources` dict so this package gets added `to_unhold`
2. pass `--allow-change-held-packages` (introduced in 1.1 as successor for the `--force-yes` param) to apt - e.g. by using `update_holds` which is [documented as working](https://github.com/saltstack/salt/blob/v3007.0/salt/states/pkg.py#L1539-L1552) for apt, yum zypper but is [only implemented for yum](https://github.com/search?q=repo%3Asaltstack%2Fsalt%20update_holds&type=code) atm.

The second approach has the charme, that the implementation around `to_unhold` might be completely be skipped by making this param "responsible" for allowing updates.
