### ISSUE TITLE
[BUG] master_job_cache: postgres causes salt command failures (3007.0)

### ISSUE THREAD

**Issue by ITJamie** [saltstack/salt#66457]
**Description**
running any salt cli commands fails on saltstack 3007.0 if `master_job_cache: postgres` is configured (along with relevant config)

**Setup**
in /etc/salt/master.d/eventdb.conf
```
returner.postgres.host: 'localhost'
returner.postgres.user: 'username'
returner.postgres.passwd: 'password'
returner.postgres.db: 'salt'
returner.postgres.port: 5432
```

**Steps to Reproduce the behavior**
run any salt command. eg. "salt * test.ping"
response comes back of 
```
'str' object has no attribute 'pop'
```

**Expected behavior**
output to happen
**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.0

Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: 1.7.2
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: 1.14.1
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Package Information:
  Package Type: onedir

System Versions:
          dist: ubuntu 20.04.6 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1061-azure
        system: Linux
       version: Ubuntu 20.04.6 focal
```
</details>
