### ISSUE TITLE
[BUG] 3006.8 DeprecationWarning salt.utils.psutil_compat

### ISSUE THREAD

**Issue by RolandRosenfeld** [saltstack/salt#66467]
**Description**
I use salt-minion on Debian 12 (bookworm) from
 `https://repo.saltproject.io/salt/py3/debian/12/amd64/3006 bookworm main`
repository.
Since upgrading from 3006.7 to 3006.8 
 `salt-call state.apply test=true`
reports the following derecation warning on every call:
```
/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/psutil_compat.py:16: DeprecationWarning: Please stop importing 'salt.utils.psutil_compat' and instead import 'psutil' directly as there's no longer a need for a compatability layer. The 'salt.utils.psutil_compat' will go away on Salt 3008.0 (Argon).
  salt.utils.versions.warn_until(
```
Since I use the onedir install, which bundles all python modules in salt-common package, I'd expect that this warning does not appear but is fixed.

I observe this issue on all my Debian 12 servers after the upgrade from 3006.7 to 3006.8.

**Setup**
- [x] VM (Virtualbox, KVM, etc. please specify)
- [x] onedir packaging

**Steps to Reproduce the behavior**
Upgrade from 3006.7 to 3006.8.
 `salt-call state.apply test=true`
(adding any state name results in the same warning)

A remote `salt myhost state.apply test=true` call writes the same message to the journal of salt-minion.

**Expected behavior**
No deprecation warnings on console or log if I use only bundled SaltStack 3006.8 software.

**Versions Report**
<details><summary>salt --versions-report</summary>
```yaml
Salt Version:
          Salt: 3006.8
 
Python Version:
        Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.16.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-20-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```
</details>
Server and minion are identical except that server has `cherrypy: unknown`.
