### ISSUE TITLE
[BUG] Async state.sls does not fail when minion is restarted

### ISSUE THREAD

**Issue by eg-ayoub** [saltstack/salt#66501]
**Description**
When running a long asynchronous `state.sls` on a salt minion, the job does not fail if the minion is restarted

**Setup**
Two docker containers running rockylinux:8 with salt 3007 installed, one minion and one master.
set master in the minion config.
start master and minion.

Please be as specific as possible and give set-up details.

- [x] container (Kubernetes, Docker, containerd, etc. please specify)
- [x] onedir packaging

**Steps to Reproduce the behavior**
on the master, create an example sls: 
```
[root@master /]# cat /srv/salt/test.sls 
Wait 5m:
  module.run:
    - test.sleep:
      - length: 300
```
run the state asynchronously:
```
[root@master /]# salt '*' state.sls test --async
Executed command with job ID: 20240510142416287932
```
interrupt the salt minion (ctrl-C) and start it again,
now on the master:
```
[root@0268155fd85f /]# salt-run jobs.list_job 20240510142416287932
Arguments:
    - test
Function:
    state.sls
Minions:
    - 23f4814c8159
Result:
    ----------
StartTime:
    2024, May 10 14:24:16.287932
Target:
    *
Target-type:
    glob
User:
    root
jid:
    20240510142416287932
[root@0268155fd85f /]# salt-run jobs.active
# nothing ...
[root@0268155fd85f /]# 
```
There is no return for the job.

**Expected behavior**
An error message in the job "Result" that spells out `Minion did not return`

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.0
 
Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: rocky 8.9 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 6.6.30
        system: Linux
       version: Rocky Linux 8.9 Green Obsidian
```
</details>

**Comment by eg-ayoub** [comment]
## Issue Reproduction Update - Salt 3007.9 (Official RPM Installation)

I can confirm this issue still exists in Salt 3007.9 when installed via the official RPM repository.

### Environment
- **Salt Version**: 3007.9 (Chlorine)
- **OS**: Rocky Linux 8
- **Installation Method**: Official Salt RPM repository (3007 STS)

### Setup

<details>
<summary>Docker Compose Configuration</summary>

**docker-compose.yml**:
```yaml
version: '3.8'

services:
  salt-master:
    image: rockylinux:8
    container_name: salt-master
    hostname: salt-master
    networks:
      - saltnet
    volumes:
      - ./master-config:/etc/salt/master.d
      - ./test.sls:/srv/salt/test.sls
    command: >
      bash -c "
      dnf install -y curl procps-ng dnf-plugins-core &&
      curl -fsSL https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.repo -o /etc/yum.repos.d/salt.repo &&
      dnf clean expire-cache &&
      dnf config-manager --set-disable 'salt-repo-*' &&
      dnf config-manager --set-enabled salt-repo-3007-sts &&
      dnf install -y salt-master &&
      mkdir -p /etc/salt/master.d /srv/salt &&
      salt-master -l debug
      "
    stdin_open: true
    tty: true

  salt-minion:
    image: rockylinux:8
    container_name: salt-minion
    hostname: salt-minion
    depends_on:
      - salt-master
    networks:
      - saltnet
    volumes:
      - ./minion-config:/etc/salt/minion.d
    command: >
      bash -c "
      dnf install -y curl procps-ng dnf-plugins-core &&
      curl -fsSL https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.repo -o /etc/yum.repos.d/salt.repo &&
      dnf clean expire-cache &&
      dnf config-manager --set-disable 'salt-repo-*' &&
      dnf config-manager --set-enabled salt-repo-3007-sts &&
      dnf install -y salt-minion &&
      mkdir -p /etc/salt/minion.d &&
      sleep 5 &&
      salt-minion -l debug
      "
    stdin_open: true
    tty: true

networks:
  saltnet:
    driver: bridge
```

**master-config/master.conf**:
```yaml
interface: 0.0.0.0
auto_accept: True
file_roots:
  base:
    - /srv/salt
```

**minion-config/minion.conf**:
```yaml
master: salt-master
id: salt-minion
```

**test.sls**:
```yaml
# Test SLS file with long-running operation
long_running_test:
  cmd.run:
    - name: echo "Starting long operation at $(date)" && sleep 300 && echo "Completed at $(date)"
```

</details>

### Reproduction Steps

To reproduce manually:

```bash
# 1. Start the containers
docker-compose up -d

# 2. Wait for Salt to install and start (~60 seconds)
sleep 60

# 3. Verify minion is connected
docker exec salt-master salt 'salt-minion' test.ping

# 4. Start async state
docker exec salt-master salt 'salt-minion' state.sls test --async
# Note the JID from output, e.g.: 20251125082910523553

# 5. Wait a few seconds, then kill the minion during execution
sleep 3
docker exec salt-minion pkill -9 salt-minion

# 6. Restart the minion
docker exec -d salt-minion salt-minion -l debug
sleep 5

# 7. Check job status (replace JID with your actual job ID)
docker exec salt-master salt-run jobs.list_job <JID>
docker exec salt-master salt-run jobs.lookup_jid <JID>
```

### Results

Checking job status after minion restart:

**`salt-run jobs.list_job 20251125082910523553`**:
```yaml
Arguments:
    - test
Function:
    state.sls
Minions:
    - salt-minion
Result:
    ----------
StartTime:
    2025, Nov 25 08:29:10.523553
Target:
    salt-minion
Target-type:
    glob
User:
    root
jid:
    20251125082910523553
```

**`salt-run jobs.lookup_jid 20251125082910523553`**:
```
(no output)
```

### Issue Confirmed

The `Result` field is empty with no error or status information. There's no indication that:
- The minion was interrupted
- The job failed to complete
- The job is in an incomplete state

This makes it impossible to programmatically detect that an async job was interrupted when a minion restarts.
