### ISSUE TITLE
[BUG] debian packages: bash completion script is installed to wrong place

### ISSUE THREAD

**Issue by dseomn** [saltstack/salt#66560]
**Description**
salt-common from https://repo.saltproject.io/salt/py3/debian/12/amd64/latest includes `/usr/share/bash-completions/completions/salt-common.bash/salt.bash`, which doesn't seem to enable bash completion. From a glance at other bash completion scripts on my system, I think it should probably go in `/usr/share/bash-completion/completions` (no `s` in `bash-completion`) instead, and it looks like the filenames are based on the command names. So maybe it should be installed as `/usr/share/bash-completion/completions/salt` with symlinks `salt-key`, `salt-call`, and `salt-cp` pointing at that?

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
1. Install salt-common from Salt's Debian repos.
2. Use bash.
3. Try to use any of the tab completions in `/usr/share/bash-completions/completions/salt-common.bash/salt.bash`

**Expected behavior**
The tab completions in that file should work.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.0
 
Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: debian n/a trixie
        locale: utf-8
       machine: x86_64
       release: 6.7.12-amd64
        system: Linux
       version: Debian GNU/Linux n/a trixie
```
</details>

**Additional context**
N/A
