### ISSUE TITLE
[BUG] file_roots to relative path seems broken

### ISSUE THREAD

**Issue by dtzampanakis** [saltstack/salt#66588]
**Description**
Upgrading from salt-ssh version 3007.0 (Chlorine)
to 3007.1 (Chlorine), seems to broke the file_roots that i use in my master file. 

```
root_dir: "."
conf_file: ./master
cachedir: /tmp/salt
gpg_keydir: /etc/salt/gpgkeys
file_roots:
  base:
    - ./states
pillar_roots:
  base:
    - ./pillar
```

Pillars are working, but when i try to state.apply i am unable to apply any state with 
```
serverx:
    - No matching sls found for 'ntp' in env 'base'
```
    
Working only if i change the file_roots with  an absolute path.

I installed 3006.8(Sulfur) to make it work again with relative path since i am unable to go back to 3007.0.

**Comment by petrows** [comment]
I have the same issue, all my scripts are broken now after update

**Comment by bendikro** [comment]
[b0e7c62](https://github.com/saltstack/salt/commit/b0e7c62de8dee7e5e113bdb3a0b128d073af1092) by @hurzhurz is what caused this regression. @s0undt3ch

**Comment by hartwork** [comment]
This is crazy, could this be fixed please?

**Comment by hartwork** [comment]
@hurzhurz this is about `salt-ssh`. Have you tried `salt-ssh`?

**Comment by hurzhurz** [comment]
@hartwork Thanks for the hint! I somehow overlooked and also didn't expect that...

**Comment by dwoz** [comment]
@hurzhurz Assigned this to you assuming you are up for the task. :)

**Comment by vincent-olivert-riera** [comment]
I have the same issue using a masterless minion. After updating to 3007.1, `salt-call -c . state.apply` fails because I set the `file_roots` with relative paths.

For instance, this is my directory structure:

```
/home/user/foo/
/home/user/foo/pillar/*.sls
/home/user/foo/salt/*.sls
/home/user/foo/minion
```

And this is the content of the `minion` file:

```
file_client: local
file_roots:
  base:
    - salt/
pillar_roots:
  base:
    - pillar/
```

This was working just fine when running `salt-call -c . state.apply` inside the `foo` directory. After updating to 3007.1, it breaks with the following error:

```
$ salt-call -c . state.apply 
local:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or master_tops data matches found. Please see master log for details.
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
```
