### ISSUE TITLE
[BUG] Error trying to install packages with zypper in AutoYaST process

### ISSUE THREAD

**Issue by argalad** [saltstack/salt#66595]
I am trying to execute some Salt states in the process of an automated SUSE installation using AutoYaST, and in one of the lasts processes of the installation, the [AutoYaST post-configuration scripts](https://documentation.suse.com/sles/15-SP5/html/SLES-all/cha-intro-to-autoyast.html#overviewandconcept), I execute some Salt states that try to perform a zypper installation of packages using _pkg.installed_ or _cmd.run_ execute, but they turn into these errors:
```
[ERROR] Command 'zypper' failed with return code: 7
[ERROR] stderr: System management is locked by the application with pid 3348 (/usr/bin/ruby.ruby2.5).
Close this application before trying again.
```

My .sls files look like this:
```
install_alacritty:
  pkg.installed:
    - skip_verify: True 
    - sources: 
        - Alacritty: /tmp/rpm/Alacritty/alacritty-0.12.0-bp155.1.5.x86_64.rpm
```
I have tried using this other state with the same result:
```
install_alacritty:
  cmd.run:
    - name: zypper --no-gpg-checks install -y /tmp/rpm/Alacritty/alacritty-0.12.0-bp155.1.5.x86_64.rpm
```

It doesn't matter where I execute the states, in VMs or real machines, the outcome is the same. If the system is installed and running and I execute those states, they turn out fine, the problem it's just in this post-configuration script process of AutoYaST.

Anyone has any idea why might this occur?
