### ISSUE TITLE
salt-call --local with gitfs

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#6660]
I would like to propose the gitfs support for salt-call.

This would enable a lot of cool stuff: like easier deployment from saltstack-formulas
using docker.io or packer.io without the overhead of a complete salt-master installation.

Requirements as I think of is that salt-call needs to parse /etc/salt/master.d/ or
/etc/salt/minion.d/ files for correct information about what gitfs remotes there are..

**Comment by aboe76** [comment]
@terminalmage I think this issue can be closed with the release of 2014.7.x

**Comment by terminalmage** [comment]
Good call, thanks for the reminder.

**Comment by bashu** [comment]
still not fixed?

**Comment by mafrosis** [comment]
This is fixed @bashu

**Comment by adityajain21** [comment]
I want to use gitfs in masterless mode.
Any links or threads on that?

**Comment by aboe76** [comment]
@adityajain21 no there isn't any documentation specific for the masterless setup,
but the master config can be used in the minion 

something like:
```
file_client: local

gitfs_provider: gitpython

fileserver_backend:
  - roots
  - git

gitfs_remotes:
  - https://github.com/saltstack-formulas/salt-formula.git

file_roots:
  base:
    - /srv/salt

pillar_roots:
  base:
    - /srv/pillar
```
