### ISSUE TITLE
[BUG] Salt-SSH: Accessing modules in Jinja templates via attributes disables wrappers

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#66600]
**Description**
If - during state template rendering - one accesses execution modules via attributes instead of dict keys, Salt-SSH wrapper modules are ignored.

[This came up in a Discord discussion about performance issues, initiated by @dseomn.]

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
```yaml
# /srv/salt/sshtest.sls

foo:
  test.nop:
    - name: {{ salt.config.option("master") | json }}
```

```console
$ salt-ssh tgt state.show_sls sshtest -l debug
[...]
[DEBUG   ] Performing shimmed, blocking command as follows:
config.option "master"
[...]
```

**Expected behavior**
Use the `config` wrapper module instead of executing on the target (the log line above should be absent then).

**Screenshots**
See above.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.7

Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.11
     gitpython: 3.1.42
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.15.1
         smmap: 5.0.1
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 9.3 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-362.13.1.el9_3.x86_64
        system: Linux
       version: Rocky Linux 9.3 Blue Onyx
```
</details>

This is valid for 3007 as well.

**Additional context**
The following patch solves the issue:

```patch
diff --git a/salt/client/ssh/wrapper/__init__.py b/salt/client/ssh/wrapper/__init__.py
index cfa977be0f..6215e4eb67 100644
--- a/salt/client/ssh/wrapper/__init__.py
+++ b/salt/client/ssh/wrapper/__init__.py
@@ -139,7 +139,7 @@ class FunctionWrapper:
     ):
         super().__init__()
         self.cmd_prefix = cmd_prefix
-        self.wfuncs = wfuncs if isinstance(wfuncs, dict) else {}
+        self.wfuncs = wfuncs if wfuncs is not None else {}
         self.opts = opts
         self.mods = mods if isinstance(mods, dict) else {}
         self.kwargs = {"id_": id_, "host": host}
```

Additionally, it should be documented that the dict syntax (`salt["config.option"]`) for accessing loaded modules is the preferred way for several reasons (if it is not already, unsure).

Somewhat related: https://github.com/saltstack/salt/issues/66376 https://github.com/saltstack/salt/issues/41794
