### ISSUE TITLE
[IMPROVEMENT] reported state changes on new/added zone are confusing

### ISSUE THREAD

**Issue by brevilo** [saltstack/salt#66682]
**Description**
The changes reported when a new zone is created/added are confusing because the `new` key is simply set to the new zone's `name` instead of the existing `zones` with the new zone's `name` added to it (see code reference below). This way one gets the impression that the new zone replaced the existing ones (as in zone-pruning).

**Setup**
Version: Salt: 3006.7

Relevant line of code: [here](https://github.com/saltstack/salt/blob/e4c1da4323f6334c0a14e9a68392a0c12a37e117/salt/states/firewalld.py#L419)

**Steps to Reproduce the behavior**
Create a new zone using `firewalld.present` with (say, two) other zones already existing.

**Expected behavior**
```
     Changes:
              new-zone:
                  ----------
                  new:
                      - existing-zone1
                      - existing-zone2
                      - new-zone
                  old:
                      - existing-zone1
                      - existing-zone2
```

**Actual behavior**
```
     Changes:
              new-zone:
                  ----------
                  new:
                      - new-zone
                  old:
                      - existing-zone1
                      - existing-zone2
```

Thanks
