### ISSUE TITLE
[BUG] Pillars won't update if  /var/cache/salt/master isn't delete and master restart

### ISSUE THREAD

**Issue by matthieu-sgi** [saltstack/salt#66750]
**Description**

Pillars won't update if the cache /var/cache/salt/master isn't delete and the salt-master restart.
I'm using gitfs as fs backend. I pushed a modif on a branch, specified the `saltenv` and `pillarenv`, and ran a `state.apply`.
Pillars aren't updated. The only way to update it is to remove the ` /var/cache/salt/master` dir and to restart salt-master.

I already tried `salt-run git_pillar.update`, `salt-run fileserver.update`, 'salt '*' saltutil.refresh_pillars`. 

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify): AWS EC2
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

When `state.apply`, pillars up to date. 

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.1
 
Python Version:
        Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 4.0.11
     gitpython: 3.1.43
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.16.0
         smmap: 5.0.1
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: debian 12.6 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-23-cloud-amd64
        system: Linux
       version: Debian GNU/Linux 12.6 bookworm
```
</details>

**Additional context**
