### ISSUE TITLE
[BUG] salt version 3006.8 upgrade to 3006.9 grains issue

### ISSUE THREAD

**Issue by david-pulkowski** [saltstack/salt#66774]
**Description**
Salt hub with version 3006.8 will properly target minions based on grain targeting.
e.g.:
```
salt -G 'os:redhat' test.ping
# Returns all redhat minions
```
Salt hub with version 3006.9 will NOT properly target minions based on grain targeting.
e.g.:
```
salt -G 'os:redhat' test.ping
# Returns minons that are windows and macOS and redhat
```
If target for windows or mac, similar results will target other OS as well

**Setup**
Have a salt-master setup with a mac, windows & linux minion (rhel in our case).

Try to test ping minions of a specific OS
```
salt -G 'os:redhat' test.ping
salt -G 'os:windows' test.ping
salt -G 'os:macos' test.ping
```

And some more complex targeting with grains seem to be incorrect as well.

Test compound targeting:
```
salt -C 'G@os:windows or G@os:redhat' test.ping
```
Will return mac minions as well. (only on 3006.9)

Or
```
salt -C 'G@os:macos or G@os:redhat' test.ping
```
Will return windows minions as well. (only on 3006.9)

Please be as specific as possible and give set-up details.
We set a grain called unit
```
unit: 1/1
unit: 1/2
unit: 1/3
unit: 2/2
unit: 2/3
unit: 3/3
```
This is no longer working as well, version os salt on 3006.9 over target.
Say targeting group of server unit:3/3 is returning more minions that are not in that group, and those minions that are incorrectly target fail to respond

- [ X] on-prem machine
- [X ] VM (Virtualbox, KVM, etc. please specify) Nutanix, KVM derivitive
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Have a salt-master setup with a mac, windows & linux minion (rhel in our case).
And run simple test.ping commands and more complex targeting

**Expected behavior**
Expect to only return targeted minions:
```
salt -G 'os:redhat' test.ping
salt -G 'os:windows' test.ping
salt -G 'os:macos' test.ping
```

Test compound targeting:
```
salt -C 'G@os:windows or G@os:redhat' test.ping
```
Should only return windows or rhel minions.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
3006.8 hub:
salt --versions-report
Salt Version:
          Salt: 3006.8

Python Version:
        Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.11
     gitpython: 3.1.43
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.16.0
         smmap: 5.0.1
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rhel 9.4 Plow
        locale: utf-8
       machine: x86_64
       release: 5.14.0-427.26.1.el9_4.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 9.4 Plow
       
3006.9 salt-hub:
salt --versions-report
Salt Version:
          Salt: 3006.9

Python Version:
        Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.11
     gitpython: 3.1.43
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.17.0
         smmap: 5.0.1
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rhel 9.4 Plow
        locale: utf-8
       machine: x86_64
       release: 5.14.0-427.28.1.el9_4.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 9.4 Plow
       

Salt minons:
rhel9:
    Salt Version:
              Salt: 3007.1

    Python Version:
            Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]

    Dependency Versions:
              cffi: 1.16.0
          cherrypy: 18.8.0
          dateutil: 2.8.2
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.1.4
           libgit2: Not Installed
      looseversion: 1.3.0
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.7
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 23.1
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.19.1
            pygit2: Not Installed
      python-gnupg: 0.5.2
            PyYAML: 6.0.1
             PyZMQ: 25.1.2
            relenv: 0.16.0
             smmap: Not Installed
           timelib: 0.3.0
           Tornado: 6.3.3
               ZMQ: 4.3.4

    Salt Package Information:
      Package Type: onedir

    System Versions:
              dist: rhel 9.4 Plow
            locale: utf-8
           machine: x86_64
           release: 5.14.0-427.26.1.el9_4.x86_64
            system: Linux
           version: Red Hat Enterprise Linux 9.4 Plow

Windows:
    Salt Version:
              Salt: 3006.1

    Python Version:
            Python: 3.10.11 (heads/main:408ea86, May  5 2023, 02:40:17) [MSC v.1934 64 bit (AMD64)]

    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.7
         gitpython: Not Installed
            Jinja2: 3.1.2
           libgit2: Not Installed
      looseversion: 1.0.2
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 22.0
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.10.1
            pygit2: Not Installed
      python-gnupg: 0.4.8
            PyYAML: 5.4.1
             PyZMQ: 25.0.2
            relenv: 0.12.3
             smmap: 4.0.0
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4

    System Versions:
              dist:
            locale: cp1252
           machine: AMD64
           release: 2016Server
            system: Windows
           version: 2016Server 10.0.14393 SP0 Multiprocessor Free
           
```
</details>

**Additional context**
