### ISSUE TITLE
[BUG] Git repos are not fetched when using salt-ssh

### ISSUE THREAD

**Issue by mazzy89** [saltstack/salt#66794]
**Description**

Git repos defined under `gitfs_remotes` are not fetched when using salt-ssh

**Setup**

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

**dir struct** of the `myrepo.com/repo/homelab.git`

```
.
├── config
│   ├── log.txt
│   ├── master
│   └── roster
├── Makefile
├── packages.txt
├── pillar
│   ├── top.sls
│   └── users
├── salt
│   ├── top.sls
│   └── users
└── Saltfile
```

**master**

```yaml
cachedir: /tmp/salt

fileserver_backend:
  - gitfs

gitfs_provider: pygit2
gitfs_base: main
gitfs_remotes:
  - git@github.com:saltstack-formulas/users-formula.git:
    - base: v0.48.8
  - https://myrepo.com/repo/homelab.git:
    - root: saltstack/salt

git_pillar_env: base

ext_pillar:
  - git:
      - "main https://myrepo.com/repo/homelab.git":
        - root: saltstack/pillar

log_level: debug
```

*salt-ssh '*' state.apply

```
[DEBUG   ] Could not find file 'salt://top.sls' in saltenv 'base'
```

**Expected behavior**

Salt defined git repos should be pulled and `top.sls` should be placed in the proper mountpoint and the state applied.

**Screenshots**

**Versions Report**

```yaml
$ salt --versions-report
Salt Version:
          Salt: 3006.9

Python Version:
        Python: 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522]

Dependency Versions:
          cffi: 1.17.0
      cherrypy: Not Installed
  cryptography: Not Installed
      dateutil: 2.9.0.post0
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: 1.8.1
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.8
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.1
     pycparser: 2.22
      pycrypto: Not Installed
  pycryptodome: 3.20.0
        pygit2: 1.15.1
  python-gnupg: Not Installed
        PyYAML: 6.0.2
         PyZMQ: 26.1.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: Not Installed
           ZMQ: 4.3.5

System Versions:
          dist: archcraft rolling n/a
        locale: utf-8
       machine: x86_64
       release: 6.10.3-zen1-2-zen
        system: Linux
       version: Archcraft rolling n/a
```

**Additional context**
