### ISSUE TITLE
[BUG] Highstate Returner doesn't take in consideration "report_failure" configuration

### ISSUE THREAD

**Issue by Guillaume-COEUGNET** [saltstack/salt#66816]
**Description**
Highstate returner generating reports every time even if config options are set.

**Setup**
Here is the conf of the returner in /etc/salt/minion.d/ret_highstate.conf
```
highstate.report_failures: True
highstate.report_changes: False
highstate.report_everything: False
highstate.report_format: html
highstate.report_delivery: smtp
highstate.smtp_success_subject: 'succes minion {id} on host {host}'
highstate.smtp_failure_subject: 'failure minion {id} on host {host}'
highstate.smtp_server: **************
highstate.smtp_recipients: *******************
highstate.smtp_sender: salt@noname.com
```

hello.sls :
```
Hello:
  cmd.run:
    - name: 'echo "Hello World"'
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
`# salt-call state.apply hello --return highstate -l debug --out=quiet`

Here we can see that report_failures, report_changes or report_everything options are not processed :

`[DEBUG   ] highstate setup {'report_format': 'html', 'report_delivery': 'smtp', 'smtp_sender': 'salt@myhost.com', 'smtp_recipients': 'ext.guillaume@noname.fr', 'smtp_failure_subject': 'failure minion {id} on host {host}', 'smtp_success_subject': 'succes minion {id} on host {host}', 'smtp_server': 'smtpunix.it.noname.fr'}`

**Expected behavior**
report_failures, report_changes and report_everything should be listed in debug logs and take in consideration.

**Screenshots**
None

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.1

Python Version:
        Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: 18.8.0
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.16.0
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Package Information:
  Package Type: onedir

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-192-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**
Suggested solution :

In /opt/saltstack/salt/lib/python3.10/site-packages/salt/returners/__init__.py line 171, change this :
```
        if value:
             yield option, value
             continue
```

to this :
```
        if value != "":
             yield option, value
             continue
```

This would lead to this log :
`[DEBUG   ] highstate setup {'report_everything': False, 'report_changes': False, 'report_failures': True, 'report_format': 'html', 'report_delivery': 'smtp', 'smtp_sender': 'salt@myhost.com', 'smtp_recipients': 'ext.guillaume@noname.fr', 'smtp_failure_subject': 'failure minion {id} on host {host}', 'smtp_success_subject': 'succes minion {id} on host {host}', 'smtp_server': 'smtpunix.it.noname.fr'}`
