### ISSUE TITLE
[BUG] "No module named 'Crypto'" error when running salt-ssh host schedule.list

### ISSUE THREAD

**Issue by jwezel** [saltstack/salt#66845]
**Description**
When running

```bash
$ salt-ssh host schedule.list
```

I get the error:

```
ModuleNotFoundError: No module named 'Crypto'
```

**Setup**
```
pipx install salt
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
```bash
$ salt-ssh host schedule.list
```

**Expected behavior**
```yaml
host:
    schedule: {}
```
**Versions Report**

```yaml
Salt Version:
          Salt: 3007.1
 
Python Version:
        Python: 3.12.5 (main, Aug  6 2024, 19:08:49) [GCC 11.4.0]
 
Dependency Versions:
          cffi: 1.17.0
      cherrypy: 18.10.0
      dateutil: 2.9.0.post0
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.8
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.1
     pycparser: 2.22
  pycryptodomex: 3.20.0
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.2
         PyZMQ: 26.2.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.4.1
           ZMQ: 4.3.5
 
Salt Package Information:
  Package Type: Not Installed
 
System Versions:
          dist: ubuntu 24.04 noble
        locale: utf-8
       machine: x86_64
       release: 6.8.0-41-generic
        system: Linux
       version: Ubuntu 24.04 noble
 ```
</details>

**Additional context**

I could fix the problem by installing `pycryptodome` (`pipx inject salt PyCryptodome`) and then including it into Thin Salt:

```shell
salt-ssh --thin-extra-modules=Crypto -t host schedule.list
```

but it goes without saying that this needs to be fixed.
