### ISSUE TITLE
[BUG] pkg.installed doesn't show version changes in testmode

### ISSUE THREAD

**Issue by sebastianreloaded** [saltstack/salt#66848]
**Description**
When running salt-master/salt-minion 3002 in testmode the changes would show the exact version that would be installed:
```
----------
          ID: openjdk-17-jdk
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: openjdk-17-jdk-headless=17.0.*
     Started: 18:24:48.328977
    Duration: 42.484 ms
     Changes:
```

But with salt-minion starting at least 3004.2 or currently salt-master/salt-minion 3006.9 it wont show the version:
```
----------
          ID: openjdk-17-jdk
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: openjdk-17-jdk-headless
     Started: 17:29:26.049897
    Duration: 86.968 ms
     Changes:
              ----------
              openjdk-17-jdk-headless:
                  ----------
                  new:
                      installed
                  old:
```

There is an issue related to that but it only mentions new package installs: https://github.com/saltstack/salt/issues/63985

I'm not sure if there was a change between 3002 and 3004. There are a lot of possibilities using different version for minion and master. I'm not able to setup all combinations to narrow it down atm.

What i'm sure of is that there is a regression for pkg.installed in testmode somewhere after release 3002.

So my only questions is: Is this known and does version 3007 fix that?
