### ISSUE TITLE
[BUG] systemd_service: automatic daemon-reload after unit file changes just may happen on first invocation

### ISSUE THREAD

**Issue by hurzhurz** [saltstack/salt#66864]
**Description**
As per the documentation, the systemd_service module can detect if unit files were changed and a daemon-reload is necessary, so there is no need to add service.systemctl_reload if you also already have a service.running.

Though the check if a daemon-reload is needed just happens once (the first time), even if there are multiple occasions for the same service where it could be needed.

For example if you have two SLS files:
**a.sls** changes /etc/systemd/system/dummy.service.d/**a.conf** and does a service.running for "dummy" to activate the change by restart
**b.sls** changes /etc/systemd/system/dummy.service.d/**b.conf** and also does a service.running for "dummy" for the same reason

Both work fine if applied alone.
But if you for example execute them both in a highstate, the daemon-reload is only done after the first change but not after the second change.

Here is the relevant code section:
https://github.com/saltstack/salt/blob/b40833ed15b2c8b1b169560b694e02489de84782/salt/modules/systemd_service.py#L133-L143
It is stores in \_\_context\_\_ that it has already checked if daemon-reload is needed.
If called again for the same service, it doesn't check anymore.

**I don't know the reason for why it is done this way.
But maybe the \_\_context\_\_ part could simply be removed?**

**Setup**
Here is an example SLS for demonstration that include two tasks that could be split in two separate SLS files:
1. creates and starts a dummy service
2. adds additional systemd config and restarts dummy service

```yaml
create-dummy-service:
  file.managed:
    - name: /etc/systemd/system/dummy.service
    - contents: |
        [Unit]
        Description = Dummy
        [Service]
        ExecStart = /bin/bash -c "while [ 1 ]; do sleep 1 ; done"

start-dummy-service:
  service.running:
    - name: dummy

# to show if daemon-reload warning is in status output (visible in stderr) -> will show nothing
test-status-1:
  cmd.run:
    - name: "systemctl status dummy >/dev/null"

# change unit config
/etc/systemd/system/dummy.service.d/restart.conf:
  file.managed:
    - makedirs: True
    - contents: |
        # Timestamp as dummy change: {{ salt.system.get_system_date_time() }}
        [Service]
        Restart=on-failure

# to show if daemon-reload warning is in status output (visible in stderr) -> will show necessary daemon-reload because of change
test-status-2:
  cmd.run:
    - name: "systemctl status dummy >/dev/null"

# restart on change
restart-salt-minion:
  service.running:
    - name: dummy
    - watch:
      - file: /etc/systemd/system/dummy.service.d/restart.conf

# to show if daemon-reload warning is in status output (visible in stderr) -> will still show necessary daemon-reload
test-status-3:
  cmd.run:
    - name: "systemctl status dummy >/dev/null"
```

- [X] VM (Virtualbox, KVM, etc. please specify)
- [X] container (Kubernetes, Docker, containerd, etc. please specify)
- [X] onedir packaging

**Expected behavior**
systemd_service should detect if a daemon-reload is needed on every invocation.

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.9

Python Version:
        Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.17.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.4 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.153.1-microsoft-standard-WSL2
        system: Linux
       version: Ubuntu 22.04.4 jammy
```
</details>
