### ISSUE TITLE
[BUG] `pkg.installed` is very slow with custom pkg provider

### ISSUE THREAD

**Issue by yangskyboxlabs** [saltstack/salt#66875]
**Description**
When using a custom `pkg` provider, `pkg.installed` state function spends a very long time executing code outside of `pkg.list_pkgs`, `pkg.latest_version` et al.

**Setup**
(We are building internal tooling _on top_ of `salt`, so the setup is pretty involved, and may not be practically reproducible in whole. I've isolated the subsystems involved as much as I can for reproduction, but may not be able to easily provide what we have produced locally. All details in **Steps to Reproduce** section.)

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
We are attempting to integrate `winget` with `salt` for some internal tooling, and discovered that it's just _really_ slow.

On a what should be a trivial `state.highstate test=True` check for a package already installed, `pkg.installed` takes upwards of 5 or 6 seconds additional seconds beyond the execution of `winget` itself:

```salt
Ninja Build:
  pkg.installed:
    - name: Ninja-build.Ninja
      provider: winget
```
![image](https://github.com/user-attachments/assets/d8245b7a-2a8c-4c6c-8dc8-8d91b7a3580a)

In attempting to isolate the issue, what I've discovered is that `salt` is loading _all_ functions from _all_ modules due to constructs like:

```python
def _resolve_capabilities(pkgs, refresh=False, **kwargs):
    ....
    if not pkgs or "pkg.resolve_capabilities" not in __salt__:
        return pkgs, refresh
```

Stubbing out the small set of functions checked for in this way almost completely eliminates this "overhead".

```python
def resolve_capabilities(pkgs: Sequence[str], **_) -> Sequence[str]:
    return pkgs


def hold():
    raise NotImplementedError
```

(This is not like-for-like, as some tracing info has been since removed, but performance difference is obvious.)
![image](https://github.com/user-attachments/assets/592283c7-748c-4432-ad80-a7eea5e26e85)

Now that I've seen the underlying implementation, this is mostly likely affecting all `pkg` modules without using `provider`, but the impact is limited only to the first instance.  I've not debugged further to determine to what extent this is true.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
local:
    Salt Version:
              Salt: 3007.1

    Python Version:
            Python: 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]

    Dependency Versions:
              cffi: 1.16.0
          cherrypy: 18.8.0
          dateutil: 2.8.2
         docker-py: Not Installed
             gitdb: 4.0.10
         gitpython: 3.1.43
            Jinja2: 3.1.4
           libgit2: 1.7.2
      looseversion: 1.3.0
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.7
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 23.1
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.19.1
            pygit2: 1.14.1
      python-gnupg: 0.5.2
            PyYAML: 6.0.1
             PyZMQ: 25.1.2
            relenv: Not Installed
             smmap: 5.0.1
           timelib: 0.3.0
           Tornado: 6.3.3
               ZMQ: 4.3.4

    Salt Package Information:
      Package Type: Not Installed

    System Versions:
              dist:
            locale: utf-8
           machine: AMD64
           release: 10
            system: Windows
           version: 10 10.0.19045 SP0 Multiprocessor Free
```
</details>

**Additional context**
