### ISSUE TITLE
[BUG] Create Docker container with a custom MAC address

### ISSUE THREAD

**Issue by hatamiarash7** [saltstack/salt#66882]
**Description**
We can't create a Docker container with a custom MAC address due to the `docker` package problem.

**Setup**

- [ x ] on-prem machine
- [ x ] used bootstrap to install

**Steps to Reproduce the behavior**

- Try to create a docker container with the `mac_address` option.
- The created container does not have any `Network.host.MacAddress` value.

**Expected behavior**

Create Docker container

**Screenshots**

<img width="816" alt="image" src="https://github.com/user-attachments/assets/965893e7-3196-4e32-ae2f-cd255ee14aa9">

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.5

Python Version:
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)

Dependency Versions:
          cffi: 1.16.0
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: 7.1.0
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.2
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.20.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11.11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-30-amd64
        system: Linux
       version: Debian GNU/Linux 11.11 bullseye
```
</details>

**Additional context**

I think there is a problem with the `create_host_config` function in the `docker-py` package as I mentioned [here](https://github.com/docker/docker-py/issues/3283). There isn't any `mac_address` option for this function, therefore we'll see a warning:

```
[WARNING ] The following arguments were ignored because they are not recognized by docker-py: ['mac_address']
```
