### ISSUE TITLE
[BUG] log handlers can no longer override log_level

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#66949]
**Description**
In previous versions (3004) you could configure salt to not log to the console, but to use a different handler.
For example: https://docs.saltproject.io/en/3006/ref/configuration/logging/handlers/salt.log_handlers.logstash_mod.html#log-level

In 3006.9 this no longer works. All the handlers appear to now be constrained by the global `log_level`.

**Setup**
```yaml
log_level: quiet
logstash_udp_handler:
  host: 10.0.1.0
  port: 10500
  log_level: warning
  msg_type: saltstack
  version: 1
```

**Steps to Reproduce the behavior**
`salt minion log.error hello`

**Expected behavior**
Log message sent to logstash, nothing in local minion log.

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.9

Python Version:
        Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.17.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 24.04.1 noble
        locale: utf-8
       machine: x86_64
       release: 6.8.0-45-generic
        system: Linux
       version: Ubuntu 24.04.1 noble
```
</details>

**Comment by bertdawg76** [comment]
@OrangeDog if you change your global log level to warning also, do your messages go through to your logstash server?

**Comment by OrangeDog** [comment]
@bertdawg76 yes, but then also to the console.

**Comment by bertdawg76** [comment]
@OrangeDog Do you have the log_level and the logstash_udp_handler in your master config file or minion config file?
```
log_level: quiet
logstash_udp_handler:
  host: 10.0.1.0
  port: 10500
  log_level: warning
  msg_type: saltstack
  version: 1
```

**Comment by OrangeDog** [comment]
@bertdawg76  both. Why are you asking these questions? Can you not reproduce or something?
Note that `logstash_udp_handler` is just an example. This applies to all logging.

`log_level` changed from being (as documented) the log level for the console to being a global max level, leaving no way to independently configure console logging or to have anything log at a higher level than the console.

**Comment by bertdawg76** [comment]
@OrangeDog I cannot replicate the bug.  I have tried it on my macos work computer and on a ubuntu 24.04 vm.  
I have your logstash_udp_handler code and log_level set to quiet.  It does not log anything in the minion log file, but it does send the log to the logstash server, which is the expected behavior.  I am on the salt 3006.x branch, and I am using python 3.10.14

**Comment by bertdawg76** [comment]
here is my message sent to an output file in the logstash server:
```
{"message":"{\"@version\": 1, \"@timestamp\": \"2025-12-02T23:06:39.684Z\", \"host\": \"bert-coleman-VMware-Virtual-Platform\", \"levelname\": \"ERROR\", \"logger\": \"salt.loaded.int.module.logmod\", \"lineno\": 63, \"pathname\": \"/home/bert-coleman/salt/salt/salt/modules/logmod.py\", \"process\": 34453, \"threadName\": \"MainThread\", \"funcName\": \"error\", \"processName\": \"ProcessPayload(jid=20251202230637000771)\", \"message\": \"test-logstash\", \"tags\": [\"salt\"], \"type\": \"saltstack\", \"stack_info\": null, \"bracketname\": \"[salt.loaded.int.module.logmod]\", \"bracketlevel\": \"[ERROR   ]\", \"bracketprocess\": \"[34453]\", \"colorname\": \"\\u001b[0;1;32m[salt.loaded.int.module.logmod]\\u001b[0;0m\", \"colorlevel\": \"\\u001b[0;1;31m[ERROR   ]\\u001b[0;0m\", \"colorprocess\": \"\\u001b[0;1;34m[34453]\\u001b[0;0m\", \"colormsg\": \"\\u001b[0;31mtest-logstash\\u001b[0;0m\", \"exc_info_on_loglevel\": null, \"jid\": \"[JID: 20251202230637000771]\"}","tags":["_jsonparsefailure"],"@version":"1","@timestamp":"2025-12-02T23:06:39.867808286Z","host":{"ip":"127.0.0.1"}}
```

here is my minion config file:
```
master: localhost
log_level: quiet
logstash_udp_handler:
  host: 127.0.0.1
  port: 9999
  log_level: warning
  version: 1
  msg_type: saltstack
```
I sent a salt "*" log.error test-logstash message to the logstash server 

Here are some of my grains:
```
pythonversion:
        - 3
        - 10
        - 14
        - final
        - 0
    saltpath:
        /home/bert-coleman/salt/salt/salt
    saltversion:
        3006.17+6.g0c5b58baf0
    saltversioninfo:
        - 3006
        - 17
lsb_distrib_codename:
        noble
    lsb_distrib_description:
        Ubuntu 24.04.3 LTS
    lsb_distrib_id:
        Ubuntu
    lsb_distrib_release:
        24.04
```

**Comment by OrangeDog** [comment]
@bertdawg76 you need to format your comments correctly. The whitespace is important.

I've just tested again myself via `salt-call log.warning` and the bug is still as originally described:

```yaml
# logs to console, file, and logstash
log_level: warning
logstash_udp_handler:
  log_level: warning
```

```yaml
# logs nowhere
log_level: quiet
logstash_udp_handler:
  log_level: warning
```

```yaml
# logs nowhere
log_level: quiet
log_level_file: warning
logstash_udp_handler:
  log_level: warning
``` 
**N.B. this was `log_level_file`, not `log_level_logfile`. See further down for correct testing.**

<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.17

Python Version:
        Python: 3.10.19 (main, Oct 30 2025, 04:53:28) [GCC 11.2.0]

Dependency Versions:
          cffi: 2.0.0
      cherrypy: 18.10.0
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.6
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.21.2
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 24.04.3 noble
        locale: utf-8
       machine: x86_64
       release: 6.8.0-88-generic
        system: Linux
       version: Ubuntu 24.04.3 noble
```
</details>

**Comment by twangboy** [comment]
What is the output of `salt-call config.items`

**Comment by OrangeDog** [comment]
> What is the output of `salt-call config.items`

That also includes all my grains and pillar data. Can you be more specific?

**Comment by dwoz** [comment]
> > What is the output of `salt-call config.items`
> 
> That also includes all my grains and pillar data. Can you be more specific?

This should give us all the logging config `salt-call --local  config.option '*log*' wildcard=True`

**Comment by OrangeDog** [comment]
```yaml
local:
    ----------
    log_datefmt:
        %H:%M:%S
    log_datefmt_console:
        %H:%M:%S
    log_datefmt_logfile:
        %Y-%m-%d %H:%M:%S
    log_file:
        /var/log/salt/minion
    log_fmt_console:
        %(colorlevel)s %(colormsg)s
    log_fmt_jid:
        [JID: %(jid)s]
    log_fmt_logfile:
        %(asctime)s,%(msecs)03d %(levelname)-8s (%(thread)d) [%(name)s] %(message)s %(jid)s
    log_granular_levels:
        ----------
    log_level:
        warning
    log_level_logfile:
        warning
    log_rotate_backup_count:
        0
    log_rotate_max_bytes:
        0
    logstash_udp_handler:
        ----------
        host:
            10.0.1.0
        log_level:
            warning
        msg_type:
            saltstack
        port:
            10514
        version:
            1
```

**Comment by dwoz** [comment]
@OrangeDog 
The output shows `log_level` and `log_level_logfile` are set to `warning` for some reason. We expect that it should be set to `quiet` right?

**Comment by OrangeDog** [comment]
@dwoz no, because I have it set to `warning` so that logging actually works. If I set `log_level` to `quiet`, then:

```yaml
local:
    ----------
    log_datefmt:
        %H:%M:%S
    log_datefmt_console:
        %H:%M:%S
    log_datefmt_logfile:
        %Y-%m-%d %H:%M:%S
    log_file:
        /var/log/salt/minion
    log_fmt_console:
        %(colorlevel)s %(colormsg)s
    log_fmt_jid:
        [JID: %(jid)s]
    log_fmt_logfile:
        %(asctime)s,%(msecs)03d %(levelname)-8s (%(thread)d) [%(name)s] %(message)s %(jid)s
    log_granular_levels:
        ----------
    log_level:
        quiet
    log_level_logfile:
        quiet
    log_rotate_backup_count:
        0
    log_rotate_max_bytes:
        0
    logstash_udp_handler:
        ----------
        host:
            csrf-admin-vm
        log_level:
            warning
        msg_type:
            saltstack
        port:
            10514
        version:
            1
```

I've realised that yesterday I tested `log_level_file`, not `log_level_logfile`. New cases:

```yaml
# logs to console, file, and logstash
log_level: warning
logstash_udp_handler:
  log_level: warning
```

```yaml
# logs nowhere
log_level: quiet
logstash_udp_handler:
  log_level: warning
```

```yaml
# logs to file and logstash
log_level: quiet
log_level_logfile: warning
logstash_udp_handler:
  log_level: warning
``` 

Further observation suggests the effect is:
```python
console_level = config['log_level']
file_level = config.get('log_level_logfile', console_level)
handler_log_level = max(
        config.get('handler:log_level', console_level), 
        min(console_level, file_level)
)
```

So there's a workaround if you want one of the "default" loggers <= the handler ; but no solution if you want the external handler to have the most logging.

After fixing this bug, it may also be a good idea to add a `log_level_console` for the old (<3006) behaviour and change `log_level` to have the behaviour that it almost has now as a default.
