### ISSUE TITLE
[BUG] salt-ssh does not log minion output

### ISSUE THREAD

**Issue by dead10ck** [saltstack/salt#66951]
**Description**

When calling salt-ssh, there is no output whatsoever as the `state.pkg` is run on the minion, until it is complete. Even when `--log-level` is set to a more verbose log level, the only logs printed are those of the local client; none of the output on the minion from the state run is shown as it runs.

**Expected behavior**

Minion logs should be shown as if `salt-call --local` were run directly on a shell on the minion. Ideally the log level should match that of salt-ssh.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.1+493.g5252ee77e2
 
Python Version:
        Python: 3.11.10 (main, Sep 22 2024, 17:48:00) [Clang 18.0.2 (https://android.googlesource.com/toolchain/llvm-project d8003a456
 
Dependency Versions:
          cffi: 1.17.1
      cherrypy: 18.10.0
  cryptography: 43.0.1
      dateutil: 2.9.0.post0
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.1.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.1
     pycparser: 2.22
      pycrypto: Not Installed
  pycryptodome: 3.21.0
        pygit2: Not Installed
  python-gnupg: 0.5.3
        PyYAML: 6.0.2
         PyZMQ: Not Installed
        relenv: Not Installed
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.4.1
           ZMQ: Not Installed
 
Salt Package Information:
  Package Type: pip
 
System Versions:
          dist:   
        locale: utf-8
       machine: aarch64
       release: 5.15.137-android14-11-gbc062a78e195-ab12057991
        system: Linux
       version: Not Installed
```
</details>
