### ISSUE TITLE
SecureBoot enabled according to mokutil, but disabled according to salt grain efi-secure-boot

### ISSUE THREAD

**Issue by sscotter** [saltstack/salt#66955]
.**Description**

I have a situation where by on a VMware based virtual machine when I check if Secure Boot is enabled using `mokutil` it says it is, but when I check the `efi-secure-boot` grain it's saying Secure Boot isn't enabled.

When I check the VMs firmware configuration the vCenter it is configured to use EFI (and not BIOS) and Secure Boot is ticked.

This seems to be the case across my entire estate of approx. 20 Debian and Ubuntu based VMs.

**Steps to Reproduce the behavior**

```

root@host:~ # mokutil --sb-state

    SecureBoot enabled

    root@host:~ # sudo salt-call grains.item efi efi-secure-boot

    local:

        ----------

        efi:

            True

        efi-secure-boot:

            False

```

**Expected behavior**

```

root@host:~ # mokutil --sb-state

    SecureBoot enabled

    root@host:~ # sudo salt-call grains.item efi efi-secure-boot

    local:

        ----------

        efi:

            True

        efi-secure-boot:

            True

```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
    Salt: 3007.1

Python Version:
    Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]

Dependency Versions:
    cffi: 1.16.0
    cherrypy: 18.8.0
    dateutil: 2.8.2
    docker-py: Not Installed
    gitdb: Not Installed
    gitpython: Not Installed
    Jinja2: 3.1.4
    libgit2: Not Installed
    looseversion: 1.3.0
    M2Crypto: Not Installed
    Mako: Not Installed
    msgpack: 1.0.7
    msgpack-pure: Not Installed
    mysql-python: Not Installed
    packaging: 23.1
    pycparser: 2.21
    pycrypto: Not Installed
    pycryptodome: 3.19.1
    pygit2: Not Installed
    python-gnupg: 0.5.2
    PyYAML: 6.0.1
    PyZMQ: 25.1.2
    relenv: 0.16.0
    smmap: Not Installed
    timelib: 0.3.0
    Tornado: 6.3.3
    ZMQ: 4.3.4

Salt Package Information:

  Package Type: onedir

System Versions:

       dist: debian 12.7 bookworm
       locale: utf-8
       machine: x86_64
       release: 6.1.0-25-amd64
       system: Linux
       version: Debian GNU/Linux 12.7 bookworm
```
</details>
Apologies if the formatting is incorrect, I'm submitting this from my mobile.
