### ISSUE TITLE
[BUG] pkgrepo.managed does not report changes when it cleans a .list

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#67034]
**Description**
If the given line is already present in the file, but `clean_file` is true, Salt will clean the file but not report any changes.

**Setup**
```yaml
salt repo:
  pkgrepo.managed:
    - name: >
        deb [arch=amd64 signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg]
        http://packages.broadcom.com/artifactory/saltproject-deb/
        stable main
    - file: /etc/apt/sources.list.d/salt.list
    - clean_file: true
    - key_url: https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public
    - aptkey: false
```

**Steps to Reproduce the behavior**
```
# cat /etc/apt/sources.list.d/salt.list
deb [arch=amd64 signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg] http://repo.saltproject.io/salt/py3/ubuntu/24.04/amd64/3006 noble main
deb [arch=amd64 signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg] http://packages.broadcom.com/artifactory/saltproject-deb/ stable main

# salt-call state.apply
local:

Summary for local
--------------
Succeeded: 264
Failed:      0
--------------
Total states run:     264
Total run time:    22.334 s

# cat /etc/apt/sources.list.d/salt.list
deb [arch=amd64 signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg] http://packages.broadcom.com/artifactory/saltproject-deb/ stable main
```

**Expected behavior**
The state should report changes if it changed something.

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.9

Python Version:
        Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.17.1
      cherrypy: unknown
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: 1.7.2
  looseversion: 1.0.2
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: 1.14.1
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.17.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 24.04.1 noble
        locale: utf-8
       machine: x86_64
       release: 6.8.0-48-generic
        system: Linux
       version: Ubuntu 24.04.1 noble
```
</details>

**Comment by darkpixel** [comment]
I'm not sure it's just failing to report changes:

```
backports:
  pkgrepo.managed:
    - humanname: backports
    - name: deb http://deb.debian.org/debian bookworm-backports main
    - dist: bookworm-backports
    - file: /etc/apt/sources.list.d/backports.list
    - refresh: True
```
```
# salt-call -l info state.sls backports
  Name: deb http://deb.debian.org/debian bookworm-backports main - Function: pkgrepo.managed - Result: Clean - Started: 09:25:15.147561 - Duration: 4.676 ms

Summary for local
------------
Succeeded: 5
Failed:    0
------------
Total states run:     5
Total run time:   8.039 ms
# cat /etc/apt/sources.list.d/backports.list 
deb http://deb.debian.org/debian bullseye-backports main
deb http://deb.debian.org/debian bookworm-backports main
#
```

It's not reporting changes and it's not getting rid of the old bullseye-backports line.

**Comment by OrangeDog** [comment]
@darkpixel you didn't set `clean_file: true`...

**Comment by darkpixel** [comment]
Sorry--I was running tests before reporting the bug.
It does it with clean_file: True too.

```
backports:
  pkgrepo.managed:
    - humanname: backports
    - name: deb http://deb.debian.org/debian bookworm-backports main
    - dist: bookworm-backports
    - file: /etc/apt/sources.list.d/backports.list
    - refresh: True
    - clean_file: True
```


```
# salt-call -l info state.sls backports
  Name: deb http://deb.debian.org/debian bookworm-backports main - Function: pkgrepo.managed - Result: Clean - Started: 09:34:15.240589 - Duration: 5.906 ms

Summary for local
------------
Succeeded: 5
Failed:    0
------------
Total states run:     5
Total run time:   9.402 ms
# cat /etc/apt/sources.list.d/backports.list 
deb http://deb.debian.org/debian bullseye-backports main
deb http://deb.debian.org/debian bookworm-backports main
#
```
