### ISSUE TITLE
[BUG] stop warning users when using retry: True with states

### ISSUE THREAD

**Issue by tomdoherty** [saltstack/salt#67048]
**Description**
The [documentation](https://docs.saltproject.io/en/latest/ref/states/requisites.html#retrying-states) clearly suggests using `retry: True` for states to allow retries. However when using this option we're given an annoying warning like so

```
[WARNING ] State is set to retry, but a valid dict for retry configuration was not found.  Using retry defaults
```

**Setup**
```
{{ sls }}_testing:
  cmd.run:
    - name: /bin/false
    - retry: True
```

Please be as specific as possible and give set-up details.

- [X] all installation types

**Steps to Reproduce the behavior**
```
{{ sls }}_testing:
  cmd.run:
    - name: /bin/false
    - retry: True
```

**Expected behavior**
No warning shown when `retry: True`

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
--
Salt: 3007.1+35.g4dbd6bcf9f
 
Python Version:
Python: 3.11.10 (main, Oct 30 2024, 13:43:32) [GCC 13.3.0]
 
Dependency Versions:
cffi: 1.17.1
cherrypy: 18.10.0
dateutil: 2.9.0.post0
docker-py: 6.1.3
gitdb: Not Installed
gitpython: Not Installed
Jinja2: 3.1.4
libgit2: Not Installed
looseversion: 1.3.0
M2Crypto: 0.39.0
Mako: Not Installed
msgpack: 1.1.0
msgpack-pure: Not Installed
mysql-python: Not Installed
packaging: 24.1
pycparser: 2.22
pycrypto: Not Installed
pycryptodome: 3.21.0
pygit2: Not Installed
python-gnupg: 0.4.9
PyYAML: 6.0.2
PyZMQ: 26.2.0
relenv: Not Installed
smmap: Not Installed
timelib: 0.3.0
Tornado: 6.4.1
ZMQ: 4.3.5
 
Salt Extensions:
saltext.prometheus: 2.1.0
 
Salt Package Information:
Package Type: Not Installed
 
System Versions:
dist: debian 11.7 bullseye
locale: utf-8
machine: x86_64
release: 6.1.52
system: Linux
version: Debian GNU/Linux 11.7 bullseye
```
</details>

**Additional context**
