### ISSUE TITLE
[BUG] Salt LTS broken on Fedora 41

### ISSUE THREAD

**Issue by b0inbot** [saltstack/salt#67057]
**Description**

Fedora 41 defaults to dnf5 for /usr/bin/dnf which breaks salt LTS 3006.9 . dnf5 support has already been merged into STS so this only effects LTS users.

**Setup**

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

 1. Install Fedora 41
 2. Install Salt LTS via https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-rpm.html
 3. Run sts with pkg state
 
 ```
 #!pyobjects
# vim: syntax=python expandtab

Pkg.installed("vim")
```
 
 ```
 ----------
          ID: rpmconf
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:

              errors:
                  - Running as unit: run-rcf6ea7737f3e4479b5bc5982e4fd833e.scope; invocation ID: 804cf33a5fd144779b0654ffca743096
                    Unknown argument "--allowerasing" for command "dnf5". Add "--help" for more information about the arguments.
     Started: 19:44:32.590307
    Duration: 24047.666 ms
     Changes:
----------
```

**Expected behavior**

Should install pkg

**Versions Report**
<details><summary>sudo salt-call --local test.versions</summary>

I've already upgraded so this is the output from `sudo salt-call --local test.versions` from before filing. 

```yaml

local:
    Salt Version:
              Salt: 3006.9

    Python Version:
            Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]

    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
      cryptography: 42.0.5
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.1.4
           libgit2: Not Installed
      looseversion: 1.0.2
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 22.0
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.19.1
            pygit2: Not Installed
      python-gnupg: 0.4.8
            PyYAML: 6.0.1
             PyZMQ: 23.2.0
            relenv: 0.17.0
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4

    System Versions:
              dist: fedora 41
            locale: utf-8
           machine: x86_64
           release: 6.11.8-300.fc41.x86_64
            system: Linux
           version: Fedora Linux 41
```
</details>

**Additional context**

I'm running masterless salt. I've also already upgraded to STS so I confirmed this working outside of LTS.
