### ISSUE TITLE
[BUG] Cannot run salt-master without root

### ISSUE THREAD

**Issue by Akm0d** [saltstack/salt#67083]
**Description**
Running salt master in Vscode integrated terminal as a non-root user results in:

```
[Errno 2] No such file or directory: 'dmesg'
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
Master config:
```
user: localuser
root_dir: /home/localuser/salt_config/root
```

Please be as specific as possible and give set-up details.

pip install

**Steps to Reproduce the behavior**
- git clone https://github.com/saltstack/salt.git
- python3.10 -m venv .venv
- source .venv/bin/activate
- .venv/bin/salt-master -c /home/localuser/salt_config

**Expected behavior**
Salt Master runs normally

**Versions Report**
```yaml
Salt Version:
          Salt: 3007.1+450.g9d10d699f3
 
Python Version:
        Python: 3.12.7 (main, Nov 10 2011, 15:00:00) [GCC 14.2.0]
 
Dependency Versions:
          cffi: 1.17.1
      cherrypy: 18.10.0
  cryptography: 44.0.0
      dateutil: 2.9.0.post0
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.1.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.2
     pycparser: 2.22
      pycrypto: Not Installed
  pycryptodome: 3.21.0
        pygit2: Not Installed
  python-gnupg: 0.5.3
        PyYAML: 6.0.2
         PyZMQ: 26.2.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.4.2
           ZMQ: 4.3.5
 
Salt Package Information:
  Package Type: pip
 
System Versions:
          dist: org.freedesktop.platform 24.08 Flatpak runtime
        locale: utf-8
       machine: x86_64
       release: 6.9.3-76060903-generic
        system: Linux
       version: Freedesktop SDK 24.08 Flatpak runtime
```
</details>
