### ISSUE TITLE
[BUG] dictupdate.update silently drops values when merging a list w/ mapping

### ISSUE THREAD

**Issue by tomdoherty** [saltstack/salt#67092]
**Description**
dictupdate.update silently drops values when merging a list with a mapping

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify)
- [X] VM running on a cloud service, please be explicit and add details
- [X] container (Kubernetes, Docker, containerd, etc. please specify)
- [X] or a combination, please be explicit
- [X] jails if it is FreeBSD
- [X] classic packaging
- [X] onedir packaging
- [X] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
               Salt: 3007.1+38.g9dc6ca50a7
 
Python Version:
             Python: 3.11.11 (main, Dec  9 2024, 10:10:57) [GCC 13.3.0]
 
Dependency Versions:
               cffi: 1.17.1
           cherrypy: 18.10.0
           dateutil: 2.9.0.post0
          docker-py: 6.1.3
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 3.1.4
            libgit2: Not Installed
       looseversion: 1.3.0
           M2Crypto: 0.39.0
               Mako: Not Installed
            msgpack: 1.1.0
       msgpack-pure: Not Installed
       mysql-python: Not Installed
          packaging: 24.2
          pycparser: 2.22
           pycrypto: Not Installed
       pycryptodome: 3.21.0
             pygit2: Not Installed
       python-gnupg: 0.4.9
             PyYAML: 6.0.2
              PyZMQ: 26.2.0
             relenv: Not Installed
              smmap: Not Installed
            timelib: 0.3.0
            Tornado: 6.4.2
                ZMQ: 4.3.5
 
Salt Extensions:
 saltext.prometheus: 2.1.0
 
Salt Package Information:
       Package Type: Not Installed
 
System Versions:
               dist: debian 11.7 bullseye
             locale: utf-8
            machine: x86_64
            release: 6.1.84
             system: Linux
            version: Debian GNU/Linux 11.7 bullseye
```
</details>

**Additional context**
