### ISSUE TITLE
[BUG] master doesn't act on commands issued before the minion was up

### ISSUE THREAD

**Issue by pksadiq** [saltstack/salt#67098]
**Description**

If some command is executed on the master and if the minion was not up during the time, salt will endlessly wait until timeout even when the minion was up an running afterwards.

**Setup**

- [x] on-prem machine (on real hardware, but test machines)
- [x] used bootstrap to install

**Steps to Reproduce the behavior**

1. Shutdown the minion, let's say it has the id `my-minion`
2. Issue some command on the master:
```sh
salt 'my-minion' test.ping  -t 120
# or say
salt-run manage.up -t 120
```
3. Turn the minion on

**Current behavior**

The command waits until timeout happens and shows timeout error.

**Expected behavior**

Salt should connect to the machine that is up and run the command successfully.

**Versions Report**
 
Dependency Versions:

<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.9
 
Python Version:
        Python: 3.10.14 (main, Jun 26 2024, 11:46:35) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.17.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: aarch64
       release: 6.6.62+rpt-rpi-v8
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```
</details>
