### ISSUE TITLE
Minion cannot connect to Master when master: 127.0.0.1 is configured but 127.0.0.1 is not in /etc/hosts and DNS in /etc/resolv.conf is unreachable ﻿

### ISSUE THREAD

**Issue by baishuwang** [saltstack/salt#67109]
**Description**
In some cases, when the Salt Minion is configured with master: 127.0.0.1, but the system's /etc/hosts file does not have a resolution for 127.0.0.1 and the DNS addresses in /etc/resolv.conf are unreachable, the Minion cannot connect to the Master. Even though 127.0.0.1 is configured, the system fails to resolve this address, causing the Minion to be unable to connect.

Could you please help explain why this happens?

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [x] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Configure the Salt Minion configuration file  with master: 127.0.0.1.
Ensure that the /etc/hosts file does not contain a resolution for 127.0.0.1.
Ensure that the DNS servers configured in /etc/resolv.conf are unreachable or invalid.
Start the Salt Minion service and check if the Minion is able to connect to the Master.

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Nov 14 2022, 12:59:47)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: aarch64
       release: 4.19.90-52.15.v2207.ky10.aarch64
        system: Linux
       version: Ubuntu 20.04 focal

```
</details>

**Additional context**
