### ISSUE TITLE
[BUG] yumpkg.services_need_restart needlessly fails on recent Fedora

### ISSUE THREAD

**Issue by nf-brentsaner** [saltstack/salt#67177]
**Description**
Fedora 41 uses DNF5.

The `_yum()` function in salt/modules/yumpkg.py returns `dnf5`.

However, the check in `services_need_restart()` only accounts for `dnf`, despite the command working fine in DNF 5 (`dnf5`), and needlessly fails:

```
# sha512sum `which dnf` ; sha512sum `which dnf5`
8ff23f3049841d00dab2861710717bc56a841f2754c469edffad2cd52c8219a75a6bec120cc7d5ce7762f7c407a87ccccdc1e80bc93dc97150d507feba0e942c  /usr/bin/dnf
8ff23f3049841d00dab2861710717bc56a841f2754c469edffad2cd52c8219a75a6bec120cc7d5ce7762f7c407a87ccccdc1e80bc93dc97150d507feba0e942c  /usr/bin/dnf5
# dnf --quiet needs-restarting
No core libraries or services have been updated since boot-up.
Reboot should not be necessary.
# dnf5 --quiet needs-restarting
No core libraries or services have been updated since boot-up.
Reboot should not be necessary.
```

**Setup**
Fedora 41 running Salt Minion 3007.1.

- [X] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
N/A

**Expected behavior**
yumpkg properly detects dnf5 with the same consideration and condition path as dnf in `services_need_restart()` instead of raising `CommandExecutionError("dnf is required to list outdated services.")`.

**Screenshots**
N/A

**Versions Report**
N/A; see above.

**Additional context**
N/A

**Comment by ScriptAutomate** [comment]
Related:
- #67182

**Comment by dmurphy18** [comment]
@nf-brentsaner Please fill out the salt --versions report, it provides more information than just the version of Salt, dependencies installed for example

**Comment by nf-brentsaner** [comment]
I mean. I literally told you [why it fails](https://github.com/saltstack/salt/blob/0ad9b3beee323019044b4044715c0be5090b1011/salt/modules/yumpkg.py#L3533) and why it shouldn't, with a checksum demonstrating the same thing as an ls -l would.

Not sure what you think you're going to gleam from a versions report for an issue that is still present in current master that happens on behavior present on day 0 install of **any** install in the distro and release provided completely divorced of any "dependencies installed for example" given that it's part of the distro core, and visible with the naked human eye, but yeah.

Sure.


```yaml
# salt-call --versions-report
Salt Version:
          Salt: 3007.1
 
Python Version:
        Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: 18.8.0
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.16.0
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: fedora 41 
        locale: utf-8
       machine: x86_64
       release: 6.12.15-200.fc41.x86_64
        system: Linux
       version: Fedora Linux 41
```
