### ISSUE TITLE
[BUG] Upgrade to 3006.9 breaks PowerShell cmd.run/shell commands

### ISSUE THREAD

**Issue by hammondrm** [saltstack/salt#67190]
**Description**
After upgrading from version 2006.8 to 3006.9 running cmd.run or cmd.shell with PowerShell on Windows servers will result in errors. 

**Setup**
Minions are running on Windows 2016, 2019 and 2022 servers.
- [X] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify)
- [X] onedir packaging

**Steps to Reproduce the behavior**
This is one of the commands run that now error:
```
salt * cmd.shell '(Get-Date(Get-Date).ToUniversalTime() -UFormat %s)' shell=PowerShell
```

Here is the error from a minion running version 3006.9:

```
    & : The term '1737567164.15532' is not recognized as the name of a cmdlet, function, script file, or operable program.
    Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    At line:1 char:3
    + & (Get-Date(Get-Date).ToUniversalTime() -UFormat %s)
    +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (1737567164.15532:String) [], CommandNotFoundException
        + FullyQualifiedErrorId : CommandNotFoundException
```
**Expected Behavior**
On minions running with version 3006.8 the same command will return a number:

> 1737568937.15566

**Versions Report Master:**
```
Salt Version:
          Salt: 3006.9
Python Version:
        Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: 1.3.0
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: 1.7.1
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.17.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
System Versions:
          dist: rhel 9.5 Plow
        locale: utf-8
       machine: x86_64
       release: 5.14.0-503.15.1.el9_5.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 9.5 Plow
```
**Versions Report Minion:**
```
Salt Version:
          Salt: 3006.9

Python Version:
        Python: 3.10.14 (heads/main:9f7d197, Jun 26 2024, 11:42:40) [MSC v.1940 64 bit (AMD64)]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 25.0.2
        relenv: 0.17.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist:
        locale: utf-8
       machine: AMD64
       release: 2022Server
        system: Windows
       version: 2022Server 10.0.20348 SP0 Multiprocessor Free
```
