### ISSUE TITLE
[BUG] Executing tests/minionswarm.py fails

### ISSUE THREAD

**Issue by dnessett** [saltstack/salt#67214]
**Description**
Executing "python tests/minionswarm.py" fails. Several test support files have moved in 3007.x (probably even in earlier release branches) and references to them in import and other statements are incorrect. Furthermore, the values in VERS are stale and out of date.

**Setup**
In the salt source directory:
cd tests

Please be as specific as possible and give set-up details.

- [ X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
In the salt source directory:
pyenv activate "virtualenv"
cd tests
python minionswarm.py --help

**Expected behavior**
Help menu should appear:

python minionswarm.py --help
Usage: minionswarm.py [options]

Options:
  -h, --help            show this help message and exit
  -m MINIONS, --minions=MINIONS
                        The number of minions to make
  -M                    Run a local master and tell the minions to connect to
                        it
  --master=MASTER       The location of the salt master that this swarm will
                        serve
  -n NAME, --name=NAME  Give the minions an alternative id prefix, this is
                        used when minions from many systems are being
                        aggregated onto a single master
  --rand-os             Each Minion claims a different os grain
  --rand-ver            Each Minion claims a different version grain
  --rand-machine-id     Each Minion claims a different machine id grain
  --rand-uuid           Each Minion claims a different UUID grain
  -k KEEP, --keep-modules=KEEP
                        A comma delimited list of modules to enable
  -f, --foreground      Run the minions with debug output of the swarm going
                        to the terminal
  --temp-dir=TEMP_DIR   Place temporary files/directories here
  --no-clean            Don't cleanup temporary files/directories
  --root-dir=ROOT_DIR   Override the minion root_dir config
  --transport=TRANSPORT
                        Declare which transport to use, default is zeromq
  --start-delay=START_DELAY
                        Seconds to wait between minion starts
  -c CONFIG_DIR, --config-dir=CONFIG_DIR
                        Pass in a configuration directory containing base
                        configuration.
  -u USER, --user=USER 

**Screenshots**

**Versions Report**

```yaml
Salt Version:
          Salt: 3007.0
 
Python Version:
        Python: 3.10.15 (main, Oct 14 2024, 13:34:24) [GCC 11.4.0]
 
Dependency Versions:
          cffi: 1.17.1
      cherrypy: Not Installed
  cryptography: 43.0.3
      dateutil: 2.9.0.post0
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.1.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.1
     pycparser: 2.22
      pycrypto: Not Installed
  pycryptodome: 3.21.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0.2
         PyZMQ: 26.2.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.5
 
System Versions:
          dist: linuxmint 21.3 virginia
        locale: utf-8
       machine: x86_64
       release: 6.8.0-50-generic
        system: Linux
       version: Linux Mint 21.3 virginia
```
</details>

**Additional context**
