### ISSUE TITLE
[BUG] salt.exceptions.FileserverConfigError: Failed to load git_pillar when git_pillar.update run from saltutil.runner

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#67716]
**Description**
The `git_pillar.update` runner, when called from `saltutil.runner`, returns a FileServerConfigError exception.

**Setup**
```
ext_pillar:
  - git:
     - master ssh://git@hostedgitprovider.com/org/git_salt_pillar.git:
         - pubkey: /etc/salt/pki/master/git_id_rsa.pub
         - privkey: /etc/salt/pki/master/git_id_rsa
         - name: git_salt_pillar
         - root: pillar
 ```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
```
salt salt01 saltutil.runner git_pillar.update
salt01:
    Exception occurred in runner git_pillar.update: Traceback (most recent call last):
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 513, in __init__
        self.new = self.init_remote()
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 2016, in init_remote
        self.repo = pygit2.Repository(self._cachedir)
      File "/opt/saltstack/salt/extras-3.10/pygit2/repository.py", line 1606, in __init__
        path_backend = init_file_backend(path, flags)
    _pygit2.GitError: Repository not found at /var/cache/salt/master/git_pillar/git_salt_pillar/_

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/client/mixins.py", line 388, in low
        data["return"] = func(*args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
        ret = self.loader.run(run_func, *args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
        ret = _func_or_method(*args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/runners/git_pillar.py", line 70, in update
        pillar = salt.utils.gitfs.GitPillar(
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 2557, in __init__
        self.init_remotes(
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 2616, in init_remotes
        repo_obj = self.git_providers[self.provider](
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 1740, in __init__
        super().__init__(
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 521, in __init__
        failhard(self.role)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 229, in failhard
        raise FileserverConfigError(f"Failed to load {role}")
    salt.exceptions.FileserverConfigError: Failed to load git_pillar
```

It works fine if the runner is called directly:
```
salt-run git_pillar.update
master ssh://git@hostedgitprovider.com/org/git_salt_pillar.git:
    None
```

**Expected behavior**
Update git pillar

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
salt --versions-report
Salt Version:
              Salt: 3006.9

Python Version:
            Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]

Dependency Versions:
              cffi: 1.14.6
          cherrypy: unknown
      cryptography: 42.0.5
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.1.4
           libgit2: 1.5.0
      looseversion: 1.0.2
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 22.0
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.19.1
            pygit2: 1.11.1
      python-gnupg: 0.4.8
            PyYAML: 6.0.1
             PyZMQ: 23.2.0
            relenv: 0.17.0
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4

Salt Extensions:
 saltext.bitwarden: 0.0.1b15

System Versions:
              dist: almalinux 8.10 Cerulean Leopard
            locale: utf-8
           machine: x86_64
           release: 4.18.0-553.30.1.el8_10.x86_64
            system: Linux
           version: AlmaLinux 8.10 Cerulean Leopard
```
</details>

**Additional context**
This is used in an orch to update my Salt masters when they receive an event (via webhook) from the hosted git provider that the repo has been updated. Previously worked (although not entirely sure which version broke).

**Comment by ggiesen** [comment]
```
cd /var/cache/salt/master/git_pillar/git_salt_pillar/_ && sudo -u salt git status
On branch master
nothing to commit, working tree clean
```

Although if I run it as root:

```
cd /var/cache/salt/master/git_pillar/git_salt_pillar/_ && git status
fatal: detected dubious ownership in repository at '/var/cache/salt/master/git_pillar/git_salt_pillar/_'
To add an exception for this directory, call:

        git config --global --add safe.directory /var/cache/salt/master/git_pillar/egate_salt_pillar/_
```

I wonder if it could be a result of the change to running master as `salt`, while the minion is running as root.

**Comment by ggiesen** [comment]
Indeed it is:

```
cd /var/cache/salt/master/git_pillar/git_salt_pillar/_ && git config --global --add safe.directory /var/cache/salt/master/git_pillar/git_salt_pillar/_
# salt salt01 saltutil.runner git_pillar.update
salt01:
    ----------
    master ssh://git@hostedgitprovider.com/org/git_salt_pillar.git:
        None

**Comment by ggiesen** [comment]
Unless I misunderstand how the [saltutil.runner](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.runner) execution module is supposed to work, shouldn't this run as the `salt` user rather than `root`?

**Comment by ggiesen** [comment]
> Indeed it is:
> 
> ```
> cd /var/cache/salt/master/git_pillar/git_salt_pillar/_ && git config --global --add safe.directory /var/cache/salt/master/git_pillar/git_salt_pillar/_
> # salt salt01 saltutil.runner git_pillar.update
> salt01:
>     ----------
>     master ssh://git@hostedgitprovider.com/org/git_salt_pillar.git:
>         None

This isn't a fix as you'll end up with a bunch of files in .git owned by root which then prevents the regular runner from running.

**Comment by barneysowood** [comment]
@ggiesen - WRT to the discussion on the community call - can you confirm how you are triggering the update? 

In the info above you are calling runners in two different ways:

1. `salt-run` - that should check the master config and then call setuid() to change to the `salt` user (assuming that's what you have configured.

2. `salt salt01 saltutil.runner` - that doesn't do a setuid() so will execute a runner client as the user the minion runs as (presumably `root`). 

You mentioned that you thought the issue was calling a runner from a reactor - was that calling it via the minion and `saltutil.runner` or directly from a orchestration with `salt.runner`? If it's the latter and it's executing as root that is something we need to look at.

I am wondering now about the behaviour of `saltutil.runner` - I think it might make sense for it to try to setuid() to the user the master is running as. That may be a new issue though.

**Comment by barneysowood** [comment]
@ggiesen - are you able to get back to me on these questions?

**Comment by ggiesen** [comment]
@barneysowood thanks for the follow-up. Still reproducing on 3006.16. Answers below.

**Trigger path:** master-side reactor fires `runner.state.orchestrate`. The orchestration step uses `salt.function` to call `saltutil.runner git_pillar.update` on the master's own minion. So it's the minion-side `saltutil.runner` path, executed as root (minion runs as root, master runs as `salt`). Not a direct `salt.runner` from the orchestration.

That matches your read: `saltutil.runner` doesn't setuid to the master's configured user, so libgit2's owner-validation refuses the `salt`-owned cache when the runner runs as root.

**Minimal reproduction** (no reactor, webhook, private repo, or SSH auth needed):

Master config:
```
user: salt

ext_pillar:
  - git:
      - master https://github.com/saltstack-formulas/users-formula.git
```

Minion runs as root (3006 onedir default). Populate the cache via the master, which works:
```
# salt-run git_pillar.update
master https://github.com/saltstack-formulas/users-formula.git:
    None
```

Then trigger the same runner via the minion, which fails:
```
# salt <master-minion-id> saltutil.runner git_pillar.update
<master-minion-id>:
    Exception occurred in runner git_pillar.update: Traceback (most recent call last):
      ...
      File "/opt/saltstack/salt/extras-3.10/pygit2/repository.py", line 1606, in __init__
        path_backend = init_file_backend(path, flags)
    _pygit2.GitError: /var/cache/salt/master/git_pillar/<name>/_: repository path '/var/cache/salt/master/git_pillar/<name>/_/' is not owned by current user
    ...
    salt.exceptions.FileserverConfigError: Failed to load git_pillar
```

Versions:
```
Salt: 3006.16
libgit2: 1.5.0
pygit2: 1.11.1
```

The error message wording differs slightly from my original 3006.9 trace (older build said "Repository not found"; current build is explicit about ownership), but it's the same libgit2 owner-validation refusal.

**Scope:** the same mechanism applies to any minion-side runner that opens a master-owned git cache. In my deployment I also have `safe.directory` entries for gitfs caches, which suggests fileserver runners hit it via the same path. I haven't isolated those separately here.

**Re: the `safe.directory` workaround:** as I noted earlier in the thread, adding the cache path to root's gitconfig lets the runner succeed once, but git operations performed as root then leave objects in the cache owned by root, which breaks the next master-side `salt-run git_pillar.update`. So it isn't a stable workaround.

If `saltutil.runner` adopting the master's configured `user:` (when the master is configured to drop privileges) is on the table as the fix, that should resolve this cleanly for both git_pillar and gitfs runners, and likely anything else that opens master-owned state from the runner client.

**Comment by ggiesen** [comment]
One more piece of context on why this pattern matters here.

**Polling isn't a substitute.** Gitfs at short polling intervals has a track record of resource leak and stability issues, so I keep both `git_pillar_update_interval` and `gitfs_update_interval` well above the defaults. Setting that aside, short-interval polling is also a poor fit for the actual change rate: pillar and fileserver content changes during an hour or two of active iteration per day, not continuously. 60s polling pays a steady cost in master CPU and git-provider load to cover rare-change windows that aren't there most of the time. The webhook trigger inverts that: long-interval polling as a backstop, immediate refresh when there's actually something to refresh.

**The pattern.** A reactor (master-side) fires a small orchestration. The orch fans out via `salt.function` to all master minions, each of which then invokes the runner:

```yaml
# orch/update_git_pillar.sls
update_git_pillar:
  salt.function:
    - name: saltutil.runner
    - tgt: 'salt[0-9]{2}'
    - tgt_type: pcre
    - arg:
      - git_pillar.update
```

The reason this uses `salt.function` -> `saltutil.runner` (rather than `salt.runner` master-side) is fan-out: the webhook only reaches one master, but every master's cache needs to refresh. Targeting all the master minions via salt's normal addressing decouples external webhook config from internal master topology. Adding a new master is a salt-side change, not a webhook reconfiguration in every upstream system that integrates with us.

I think the right fix is for `saltutil.runner` to drop to the master's configured user before invoking the runner client, so the call behaves identically to running the equivalent `salt-run` directly on the master, irrespective of which runner is being called. That resolves this case and any other runner that touches master-owned state, without forcing operators off the event-driven pattern.
