### ISSUE TITLE
[BUG]  Passed invalid arguments: update() got an unexpected keyword argument '__pub_user' when fileserver.update run from saltutil.runner

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#67717]
**Description**
The `fileserver.update` runner, when called from `saltutil.runner`, returns `Passed invalid arguments: update() got an unexpected keyword argument '__pub_user'`.

**Setup**
```
fileserver_backend:
  - roots
  - gitfs

gitfs_provider: pygit2
gitfs_base: master

gitfs_remotes:
  - ssh://git@hostedgitprovider.com/org/git_salt.git:
      - pubkey: /etc/salt/pki/master/git_id_rsa.pub
      - privkey: /etc/salt/pki/master/git_id_rsa
      - name: git_salt
      - root: salt
      - mountpoint: salt://
      - base: master
      - disable_saltenv_mapping: True
      - update_interval: 3600
 ```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
```
# salt salt01 saltutil.runner fileserver.update
salt01:

    Passed invalid arguments: update() got an unexpected keyword argument '__pub_user'

    Usage:

        Update the fileserver cache. If no backend is provided, then the cache for
        all configured backends will be updated.

        backend
            Narrow fileserver backends to a subset of the enabled ones.

            .. versionchanged:: 2015.5.0
                If all passed backends start with a minus sign (``-``), then these
                backends will be excluded from the enabled backends. However, if
                there is a mix of backends with and without a minus sign (ex:
                ``backend=-roots,git``) then the ones starting with a minus
                sign will be disregarded.

                Additionally, fileserver backends can now be passed as a
                comma-separated list. In earlier versions, they needed to be passed
                as a python list (ex: ``backend="['roots', 'git']"``)

        kwargs
            Pass additional arguments to backend. See example below

        CLI Example:

        .. code-block:: bash

            salt-run fileserver.update
            salt-run fileserver.update backend=roots,git
            salt-run fileserver.update backend=git remotes=myrepo,yourrepo
```

It works fine if the runner is called directly:
```
# salt-run fileserver.update
True
```

**Expected behavior**
```
# salt salt01 saltutil.runner git_pillar.update
salt01:
    ----------
    True
```

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
salt --versions-report
Salt Version:
              Salt: 3006.9

Python Version:
            Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]

Dependency Versions:
              cffi: 1.14.6
          cherrypy: unknown
      cryptography: 42.0.5
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.1.4
           libgit2: 1.5.0
      looseversion: 1.0.2
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 22.0
         pycparser: 2.21
          pycrypto: Not Installed
      pycryptodome: 3.19.1
            pygit2: 1.11.1
      python-gnupg: 0.4.8
            PyYAML: 6.0.1
             PyZMQ: 23.2.0
            relenv: 0.17.0
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.4

Salt Extensions:
 saltext.bitwarden: 0.0.1b15

System Versions:
              dist: almalinux 8.10 Cerulean Leopard
            locale: utf-8
           machine: x86_64
           release: 4.18.0-553.30.1.el8_10.x86_64
            system: Linux
           version: AlmaLinux 8.10 Cerulean Leopard
```
</details>

**Additional context**
This is used in an orch to update my Salt masters when they receive an event (via webhook) from the hosted git provider that the repo has been updated. Previously worked (although not entirely sure which version broke).
