### ISSUE TITLE
[BUG] Wrong parameter passed to dnf5 for list upgrades

### ISSUE THREAD

**Issue by extiop** [saltstack/salt#67743]
**Description**
dnf5 since fedora-41 is linked to `/usr/bin/dnf` (cf. [this issue](https://github.com/saltstack/salt/issues/67057) and it introduces breaking changes, notably for listing upgrades. Latest salt implementation (STS, i.e. 3007.x) uses exactly the same parameters for it in order to do the same things as done with /usr/bin/dnf4, but it does not work well.

**Setup**

- [x] VM (Virtualbox, KVM, etc. please specify)
  - Qubes OS with Xen with salt 3007.1 and Fedora-41

**Steps to Reproduce the behavior**

1. Install Fedora 41
2. Use testing repositories for Qubes OS to get salt 3007.1 
3. Try with qubesctl wrapper (explained below) or directly with dnf to list upgrades:

```bash
sudo qubesctl --show-output --skip-dom0 --templates --targets=fedora-41 state.sls update.qubes-vm
```

Essentially it is a wrapper to `salt-ssh` which passes notably `list upgrades` parameters to dnf on fedora:

```bash
[user@fedora-41 ~]$ /usr/bin/dnf list upgrades
Updating and loading repositories:
Repositories loaded.
No matching packages to list
[user@fedora-41 ~]$ /usr/bin/dnf4 list upgrades
Last metadata expiration check: 0:00:20 ago on Sun Feb 16 18:49:57 2025.
Available Upgrades
c-ares.x86_64                                              1.34.4-3.fc41                                      updates
double-conversion.x86_64                                   3.3.1-1.fc41                                       updates
libaom.x86_64                                              3.11.0-1.fc41                                      updates
tcl.x86_64                                                 1:8.6.14-5.fc41                                    updates
```

**Expected behavior**
`list upgrades` command should list upgrades available via dnf5 on fedora-41.

**Versions Report**
<details><summary>salt-call --local test.versions</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
local:
    Salt Version:
              Salt: 3007.1
     
    Python Version:
            Python: 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 12.3.1 20230508 (Red Hat 12.3.1-1)]
     
    Dependency Versions:
              cffi: 1.15.1
          cherrypy: 18.8.0
          dateutil: 2.8.2
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.0.3
           libgit2: Not Installed
      looseversion: 1.2.0
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.4
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         packaging: 21.3
         pycparser: 2.20
          pycrypto: Not Installed
      pycryptodome: 3.19.0
            pygit2: Not Installed
      python-gnupg: 0.5.0
            PyYAML: 6.0
             PyZMQ: 23.2.0
            relenv: Not Installed
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 6.2
               ZMQ: 4.3.4
     
    Salt Package Information:
      Package Type: Not Installed
     
    System Versions:
              dist: qubes 4.2.4 R4.2
            locale: utf-8
           machine: x86_64
           release: 6.12.11-1.qubes.fc37.x86_64
            system: Linux
           version: Qubes OS 4.2.4 R4.2
```
</details>

**Additional context**

qubesctl is a binary used in Qubes OS and is masterless usage of salt and testing repositories uses salt 3007.1 (cf. [this comment](https://github.com/QubesOS/qubes-issues/issues/9244#issuecomment-2551028438)).

Hence updates with latest salt versions (cf. [this comment](https://github.com/saltstack/salt/pull/64675#issuecomment-2552106241)) is not working fine with fedora-41, notably with Qubes OS latest fedora templates. This is due to [this commit](https://github.com/saltstack/salt/commit/5fa7a865ab376f24b09bbe47157d99b1fe6a0847) from [this PR](https://github.com/saltstack/salt/pull/64675) and [this line exactly](https://github.com/saltstack/salt/commit/5fa7a865ab376f24b09bbe47157d99b1fe6a0847#diff-f5522aab89c593a60a281d5d2951909c938e653205f99f9d651399421f94eb0fR1064) shipped since salt 3007.1.

The fix is to use `--upgrades` instead of `upgrades` on above quoted line:

```bash
[user@fedora-41 ~]$ /usr/bin/dnf list --upgrades
Updating and loading repositories:
Repositories loaded.
Available upgrades
c-ares.x86_64            1.34.4-3.fc41   updates
double-conversion.x86_64 3.3.1-1.fc41    updates
libaom.x86_64            3.11.0-1.fc41   updates
tcl.x86_64               1:8.6.14-5.fc41 updates
```
