### ISSUE TITLE
[BUG] Debian packages are missing init.d scripts

### ISSUE THREAD

**Issue by x12a1f** [saltstack/salt#67765]
**Description**
I am using salt-minion on a few machines running Devuan and Debian without systemd.
These machines do not use systemd

On the older machines where I upgraded to version 3007.1 the file `/etc/init.d/salt-minion` is still available.
However, I did a clean install on a new machine and there `/etc/init.d/salt-minion` is missing.
After investigating, it seems `/etc/init.d/salt-minion` is no longer included in the Debian package. I found them in https://github.com/saltstack/salt/blob/master/pkg/old/deb/salt-minion.init with a note to file a bug report if you use the file.

**Setup**

Manual installation as described in https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-deb.html of salt-minion 3007.1 on a clean installation of Devuan daedalus

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Install salt-minion from the Debian packages and try to start the service by running `/etc/init.d/salt-minion` or `service salt-minion start`

**Expected behavior**
The file `/etc/init.d/salt-minion` is available and salt-minion starts on systems without systemd

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.1
 
Python Version:
        Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: 18.8.0
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.16.0
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: devuan 12.7 daedalus
        locale: utf-8
       machine: x86_64
       release: 6.1.0-31-amd64
        system: Linux
       version: Devuan GNU/Linux 12.7 daedalus
```
</details>

**Additional context**
The same issue is with the other salt services. They are all missing an init.d script.
