### ISSUE TITLE
[BUG] dnf5 installs packages it should download

### ISSUE THREAD

**Issue by Ofenhed** [saltstack/salt#67769]
**Description**
There was a breaking change in [#64675](https://github.com/saltstack/salt/pull/64675):[salt/modules/yumpkg.py#L1711-R1719](https://github.com/saltstack/salt/pull/64675/files#diff-f5522aab89c593a60a281d5d2951909c938e653205f99f9d651399421f94eb0fL1711-R1719) that made it so that `pkg.downloaded` *silently* converts to `pkg.installed`.

This is a very big issue for use cases such as VM:s with a common base image, where packages untrusted for certain domains are still downloaded for all domains and installed in the VM only when needed. This could include packages with automatically executing services, or packages containing files with permission attributes or suid flags set.

<details><summary>

As far as I can tell, dnf5 still supports `--downloadonly` (but has issues with `dnf -C install`, so it has greatly reduced its functionality). Unless there is some interoperability issues with other arguments, I suggest that the change to how `--downloadonly` is handled is reverted.

</summary>

```
[user@disp3441 ~]$ dnf5 install --help
Usage:
  dnf5 [GLOBAL OPTIONS] install [OPTIONS] [ARGUMENTS] 
                                   
Options:                           
  --allowerasing                   Allow removing of installed packages to resol
                                   ve problems
  --skip-broken                    Allow resolving of depsolve problems by skipp
                                   ing packages
  --skip-unavailable               Allow skipping unavailable packages
  --allow-downgrade                Allow downgrade of dependencies for resolve o
                                   f requested operation
  --no-allow-downgrade             Disable downgrade of dependencies for resolve
                                    of requested operation
  --downloadonly                   Only download packages for a transaction
  --offline                        Store the transaction to be performed offline
  --advisories=ADVISORY_NAME,...   Limit to packages in advisories with specifie
                                   d name. List option.
  --advisory-severities=ADVISORY_  Limit to packages in advisories with specifie
  VERITY,...                       d severity. List option. Can be "critical", "
                                   important", "moderate", "low", "none".
  --bzs=BUGZILLA_ID,...            Limit to packages in advisories that fix a Bu
                                   gzilla ID, Eg. 123123. List option.
  --cves=CVE_ID,...                Limit to packages in advisories that fix a CV
                                   E (Common Vulnerabilities and Exposures) ID, 
                                   Eg. CVE-2201-0123. List option.
  --security                       Limit to packages in security advisories.
  --bugfix                         Limit to packages in bugfix advisories.
  --enhancement                    Limit to packages in enhancement advisories.
  --newpackage                     Limit to packages in newpackage advisories.
  --store=STORED_TRANSACTION_PATH  Store the current transaction in a directory 
                                   at the specified path instead of running it.
  --advisory=ADVISORY_NAME,...     Alias for 
--advisories
  --bz=BUGZILLA_ID,...             Alias for --bzs
  --cve=CVE_ID,...                 Alias for --cves
                                   
Arguments:                         
  specs                            List of <package-spec>|@<group-spec>|@<enviro
                                   nment-spec> to install
```
</details>

**Setup**
- [x] VM (Qubes TemplateVM)

**Steps to Reproduce the behavior**
Create a list of packages to download, e.g.:

```yaml
Programs that include suid binaries or automatically start services:
  pkg.downloaded:
    - pkgs:
      - chromium
      - fuse
```

**Expected behavior**
Those packages are downloaded to the dnf cache, or an error is thrown if that transaction fails.

**Actual behavior**
Those packages are installed.

**Versions Report**

<details><summary>salt-minion --verions-report</summary>

```yaml
Python Version:
        Python: 3.13.2 (main, Feb  4 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)]
 
Dependency Versions:
          cffi: 1.17.0
      cherrypy: 18.10.0
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.5
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.2
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.21.0
        pygit2: Not Installed
  python-gnupg: 0.5.0
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.5
 
Salt Package Information:
  Package Type: Not Installed
 
System Versions:
          dist: fedora 41 
        locale: utf-8
       machine: x86_64
       release: 6.6.77-1.qubes.fc37.x86_64
        system: Linux
       version: Fedora Linux 41 
```
</details>

<details><summary>dnf5 --version</summary>

```yaml
dnf5 version 5.2.10.0
dnf5 plugin API version 2.0
libdnf5 version 5.2.10.0
libdnf5 plugin API version 2.1

Loaded dnf5 plugins:
  name: builddep
  version: 1.0.0
  API version: 2.0

  name: changelog
  version: 1.0.0
  API version: 2.0

  name: config-manager
  version: 0.1.0
  API version: 2.0

  name: copr
  version: 0.1.0
  API version: 2.0

  name: needs_restarting
  version: 1.0.0
  API version: 2.0

  name: repoclosure
  version: 1.0.0
  API version: 2.0

  name: reposync
  version: 1.0.0
  API version: 2.0
```
</details>
