### ISSUE TITLE
[BUG] user.present with groups is broken on 3006.9

### ISSUE THREAD

**Issue by MarkoBL** [saltstack/salt#67798]
**Description**
I have updated a VM to Debian 12 and Salt 3006.9 and user.present does not work anymore when using groups.

Calling the module directy works fine:
``salt 'xxx' user.chgroups katba domainusers``

Running a salt sate doesn't work:
``salt 'xxx' state.sls test``

with the following sls file:
```
add_user_katba:
  user.present:
    - name: katba
    - groups:
      - domainusers
```

results in the following error:
```
xxx:
----------
          ID: add_user_katba
    Function: user.present
        Name: katba
      Result: False
     Comment: These values could not be changed: {'groups': ['domainusers']}
     Started: 13:51:35.933437
    Duration: 52.683 ms
     Changes:
```

**Setup**
Minion and Master are both on 3006.9. 

- [x] VM (KVM / Debian 12)

**Steps to Reproduce the behavior**
See above

**Expected behavior**
It worked before with 3006.1, therefore I reverted back
