### ISSUE TITLE
salt-ssh: file.recurse file_mode=keep not working

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#67795]
`salt-ssh minion state.apply` when using state `file.recurse` with `file_mode: keep` is not working..
Is working when using `salt minion state.apply`

**Setup**

sls file like:
```
deploy:
    file.recurse:
        - name: salt://opt
        - source: /opt
        - makedirs: true
        - file_mode: keep   #<<< NOTE using file_mode: keep
        - clean: true
```

or a basic example:
```
# PASS: some files have mode 0755
salt c1\* state.single file.recurse source=salt://_deploy_tpl name=/x file_mode=keep

# FAIL: all files are mode 0600
salt-ssh c1\* state.single file.recurse source=salt://_deploy_tpl name=/x file_mode=keep
```

**Versions Report**
```
salt-ssh --version
salt-ssh 3007.1 (Chlorine)
```
