### ISSUE TITLE
[BUG] Strings in both Pillar and States rendered as decimals, i.e. 3006.10 as 3006.1, if not quoted (in both Pillar and State)

### ISSUE THREAD

**Issue by rjc** [saltstack/salt#67901]
**Description**
`pkg.installed` `version` parameter treats version _3006.10_, i.e. ending with `.10`, like a floating point number, rather than a string - it renders it as _3006.1_. The same goes for _Pillar_. Only when quoted, does this have desired effect.

**Setup**

_Pillar:_

     salt_version: 3006.10

_State:_

```
# cat /var/salt/test.sls
salt-minion:
  pkg.installed:
    - version: {{ pillar['salt_version'] }}
```

Then run:

```
# salt 'foo' pillar.get salt_version
test:
    3006.1
```

and I get `3006.1` instead of the expedcted `3006.10`.

The same goes for state:

```
# salt 'foo' state.show_sls test
foo:
    ----------
    salt-minion:
        ----------
        __env__:
            base
        __sls__:
            test
        pkg:
            |_
              ----------
              version:
                  3006.1
            - installed
            |_
              ----------
              order:
                  10000
```

Again, `3006.1` instead of `3006.10`.

After quoting the Pillar value:

     salt_version: '3006.10'

I eventually get `3006.10`:

```
# salt 'foo' pillar.get salt_version
foo:
    3006.10
```

But, when rendering the _SLS_, I still get `3006.1`:

```
# salt 'foo' state.show_sls test
foo:
    ----------
    salt-minion:
        ----------
        __env__:
            base
        __sls__:
            test
        pkg:
            |_
              ----------
              version:
                  3006.1
            - installed
            |_
              ----------
              order:
                  10000
```

Now, if I quote the Pillar data like so (quote types don't matter - they can be either single or double):

```
salt-minion:
  pkg.installed:
    - version: '{{ pillar['salt_version'] }}'
 ```

I eventually get:

```
# salt 'foo' state.show_sls test
foo:
    ----------
    salt-minion:
        ----------
        __env__:
            base
        __sls__:
            test
        pkg:
            |_
              ----------
              version:
                  3006.10
            - installed
            |_
              ----------
              order:
                  10000
```

BTW, the same thing happens if I don't use _Pillar_ at all:

```
# cat /var/salt/test.sls
salt-minion:
  pkg.installed:
    - version: 3006.10
```

and then render it:

```
# salt 'foo' state.show_sls test
foo:
    ----------
    salt-minion:
        ----------
        __env__:
            base
        __sls__:
            test
        pkg:
            |_
              ----------
              version:
                  3006.1
            - installed
            |_
              ----------
              order:
                  10000
```

Quoting (again, doesn't matter whether single or double), like so:

```
# cat /srv/salt/test.sls
salt-minion:
  pkg.installed:
    - version: '3006.10'
```

obviously solves the issue:

```
# salt 'foo' state.show_sls test
foo:
    ----------
    salt-minion:
        ----------
        __env__:
            base
        __sls__:
            test
        pkg:
            |_
              ----------
              version:
                  3006.10
            - installed
            |_
              ----------
              order:
                  10000
```

- [x] VM (Virtualbox, KVM, etc. please specify)
- [x] onedir packaging

**Steps to Reproduce the behavior**
_Setup_ above already describes the steps required to reproduce the issue.

**Expected behavior**
I'd expect that both the _State_ and _Pillar_ will treat _3006.10_ as _3006.10_, not as _3006.1_, without any additional quoting. In case when _Pillar_ is being used, that's double the quoting - one in the _Pillar_, one in the _State_.

As far as I could see, none of this is documented, so it is a bug either way.

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
# salt --versions-report
Salt Version:
          Salt: 3006.10

Python Version:
        Python: 3.10.16 (main, Mar  6 2025, 02:23:15) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.6
       libgit2: 1.7.2
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: 1.14.1
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.18.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 24.04.2 noble
        locale: utf-8
       machine: x86_64
       release: 6.11.0-19-generic
        system: Linux
       version: Ubuntu 24.04.2 noble
```
</details>

**Comment by dmurphy18** [comment]
@rjc Suggest you read the yaml specification, it is working as normal, not a bug.
If you want a string you need to use single or double quotes.

**Comment by rjc** [comment]
If I was _writing_ something which produces/parses/validates _YAML_, sure.

Do I need to read YAML specification to be able to merely _use_ Salt? No, all I should need is your (Salt's) documentation.

But, if you insist, [the first full length example (Example 2.27 Invoice)](https://yaml.org/spec/1.2.2/#25-full-length-example) uses precisely that:

```
[...]
  price       : 450.00
[...]
  price       : 2392.00
[...]
```

No quoting whatsoever.

Moreover, _your_ (Salt's) documentation, at least somewhat, [hints at it being a string](https://docs.saltproject.io/en/master/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed):

> version ([str](https://docs.python.org/3/library/stdtypes.html#str)) --

And the closest example after that reads:

```
vim-enhanced:
  pkg.installed:
    - version: 2:7.4.160-1.el7
```

No quotes.

You **do** mention, in some places, when one form of quoting, or another, is required, but most examples are unquoted.

An example of quoting being mentioned:

> NOTE: When using comparison operators, the expression must be enclosed in quotes to avoid a YAML render error.

And example when it is **not** mentioned, but shown in a code example:

> ## WILDCARD VERSIONS
> 
> As of the 2017.7.0 release, this state now supports wildcards in package versions for SUSE SLES/Leap/Tumbleweed, Debian/Ubuntu, RHEL/CentOS, Arch Linux, and their derivatives. Using wildcards can be useful for packages where the release name is built into the version in some way, such as for RHEL/CentOS which typically has version numbers like 1.2.34-5.el7. An example of the usage for this would be:

```
mypkg:
  pkg.installed:
    - version: '1.2.34*'
```

So yes, I still maintain that it is a bug in _your_ (Salt's) documentation.

**Comment by dmurphy18** [comment]
@rjc Salt doesn't repeat how to write yaml, and I understand that documnetation for does have some issues but the points you are rising are now an issue
try
```
- just: write some
- yaml: 
  - [here, and]
  - {it: updates, in: real-time}
- dgm:
    key: 3004.10
    key2: 123.45
    key3: "678.9"
```
in this yaml parser https://yaml-online-parser.appspot.com and you will see the json generated is similar to Salt.

So still not a bug and this issue will remain closed.
