### ISSUE TITLE
[BUG] salt-common deb package 3006.10 creates unexpected broken symlinks in filesystem root

### ISSUE THREAD

**Issue by tdobes** [saltstack/salt#67915]
**Description**
The 3006.10 deb package for `salt-common` creates two unexpected symlinks in the root of the filesystem:
```sh
# dpkg-query -W salt-common
salt-common     3006.10
# ls -l / | grep salt-common
lrwxrwxrwx    1 root root   13 Mar 19 04:33 manpage-has-errors-from-man -> /salt-common:
lrwxrwxrwx    1 root root   13 Mar 19 04:33 non-standard-dir-perm -> /salt-common:
# dpkg-query -L salt-common | grep 'manpage-has-errors-from-man\|non-standard-dir-perm'
/manpage-has-errors-from-man
/non-standard-dir-perm
```

It appears that these symlinks might have been included accidentally during the package creation process.  These files do not exist in the previous 3006.9 version, nor do they exist in 3007.1.

**Setup**
Tested with Debian Bookworm and Ubuntu 22.04 LTS.

**Steps to Reproduce the behavior**
- Add Broadcom Salt repo and keys.
- `apt-get install -y salt-common=3006.10`
- `ls -l / | grep salt-common` # to observe unexpected symlinks

**Expected behavior**
`salt-common` package should not include spurious symlinks in root of filesystem.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
# /opt/saltstack/salt/salt --versions-report
Salt Version:
          Salt: 3006.10
 
Python Version:
        Python: 3.10.16 (main, Mar  6 2025, 02:23:15) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.6
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.18.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.4 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-102-generic
        system: Linux
       version: Ubuntu 22.04.4 jammy
```
</details>
