### ISSUE TITLE
[BUG] cannot read shebang line from MultiMinionProcessManager

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [saltstack/salt#67926]
**Description**
When I request status of a salt_minion I receive the following console output:

```
➜  ~ service salt_minion status
/usr/local/etc/rc.d/salt_minion: WARNING: cannot read shebang line from MultiMinionProcessManager
salt_minion is running as pid 8210.
```

**Setup**
```
// /usr/local/etc/salt/master

default_include: master.d/*.conf
ipv6: False
user: root
enable_ssh_minions: False
pidfile: /var/run/salt-master.pid
conf_file: /usr/local/etc/salt/master
pki_dir: /usr/local/etc/salt/pki/master
cachedir: /var/cache/salt/master
verify_env: True
file_roots:
  base:
    - /usr/local/etc/salt/states
```

```
// /usr/local/etc/salt/master.d/network.conf

interface: 192.168.1.7
ret_port: 4506
publish_port: 4505
```

```
// /usr/local/etc/satl/master.d/properties.conf

file_recv: True
```
```
// /usr/local/etc/salt/minion

master_port: 4506
user: root
pidfile: /var/run/salt-minion.pid
conf_file: /usr/local/etc/salt/minion
pki_dir: /usr/local/etc/salt/pki/minion
grains:
  roles:
    - mini
  deployment: eosander
  cabinet: 0
cachedir: /var/cache/salt/minion
verify_env: True
sock_dir: /var/run/salt/minion
enable_fqdns_grains: True
enable_gpu_grains: True
color: True
strip_colors: False
```

```
// /usr/local/etc/salt/minion.d/id.conf
id: minion-192.168.1.7
```

```
// /usr/local/etc/salt/master.conf
master: 192.168.1.7
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
```
➜  ~ service salt_minion status
/usr/local/etc/rc.d/salt_minion: WARNING: cannot read shebang line from MultiMinionProcessManager
salt_minion is running as pid 8210.
```

**Expected behavior**
the `cannot read shebang line from MultiMinionProcessManager` should not occur.

**Screenshots**
none

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```
radius ~ # salt --versions-report
Salt Version:
          Salt: 3006.8

Python Version:
        Python: 3.11.11 (main, Jan  7 2025, 01:12:50) [Clang 18.1.5 (https://github.com/llvm/llvm-project.git llvmorg-18.1.5-0-g617a15

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.1.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.2
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.21.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0.1
         PyZMQ: 25.0.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.5

System Versions:
          dist: freebsd 14.2
        locale: utf-8
       machine: amd64
       release: 14.2-RELEASE-p1
        system: FreeBSD
       version: FreeBSD 14.2
```

```yaml
PASTE HERE
```
</details>

**Additional context**
none.
