### ISSUE TITLE
[BUG] ProxyCommand missing in ssh gateway arguments.

### ISSUE THREAD

**Issue by jrothrock** [saltstack/salt#67934]
**Description**
`ssh: Could not resolve hostname ssh: Temporary failure in name resolution`

It appears that the `-oProxyCommand` argument was accidentally omitted in the following commit: https://github.com/saltstack/salt/commit/7314eb517aea828688e5c02e9bae7560d87323c4

Prior to this:

```
[salt.utils.cloud :2444][DEBUG   ][32115] SSH command: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/saltcloud-us-west-1.key.pem -oConnectTimeout=60 -oProxyCommand="ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -i /etc/salt/saltcloud-us-west-1.key.pem ubuntu@xx.xx.xx.xx -p 22 nc -q0 %h %p" -p 22 ubuntu@zz.zz.zz.zz date'
[salt.utils.vt.Terminal.PID-32191.STDERR:734 ][DEBUG   ][32115] Warning: Permanently added '[xx.xx.xx.xx]:22' (ED25519) to the list of known hosts.
```

Following:
```
[salt.utils.cloud :1182][DEBUG   ][18702] Attempting to authenticate as ubuntu (try 1 of 15)
[salt.utils.cloud :208 ][INFO    ][18702] Using SSH gateway ubuntu@xx.xx.xx.xx:22 nc -q0 %h %p
[salt.utils.cloud :2461][DEBUG   ][18702] SSH command: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /etc/salt/saltcloud-us-west-1.key.pem -oConnectTimeout=60 ssh -oStrictHostKeyChecking=no -oServerAliveInterval=60 -oServerAliveCountMax=3 -oUserKnownHostsFile=/dev/null -oControlPath=none -i /etc/salt/saltcloud-us-west-1.key.pem ubuntu@xx.xx.xx.xx -p 22 nc -q0 %h %p -p 22 ubuntu@zz.zz.zz.zz date'
[salt.utils.vt.Terminal.PID-18751.STDERR:595 ][DEBUG   ][18702] ssh: Could not resolve hostname ssh: Temporary failure in name resolution
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.10

Python Version:
        Python: 3.10.16 (main, Mar  6 2025, 02:23:15) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.17.1
      cherrypy: unknown
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.6
       libgit2: 1.9.0
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: 1.17.0
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.18.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
```
</details>
