### ISSUE TITLE
[BUG] Git state comments formatted twice

### ISSUE THREAD

**Issue by tacerus** [saltstack/salt#67944]
**Description**

Some states return this ugly output:

```
          ID: salt_formula_clone
    Function: git.latest
        Name: https://gitlab.infra.opensuse.org/infra/salt-formulas-git.git
      Result: True
     Comment: Repository /srv/formulas is up-to-date

              Changes made: U. n. c. o. m. m. i. t. t. e. d.  . c. h. a. n. g. e. s.  . w. e. r. e.  . d. i. s. c. a. r. d. e. d. ..  . R. e. p. o. s. i. t. o. r. y.  . w. a.
 s.  . h. a. r. d. -. r. e. s. e. t.  . t. o.  . o. r. i. g. i. n. /. p. r. o. d. u. c. t. i. o. n.  . (. 4. e. d. 6. b. 6. 1. ). ..
     Started: 14:50:13.673535
    Duration: 3066.77 ms
     Changes:
              ----------
              forced update:
                  True
```

**Setup**

https://github.com/openSUSE/salt-formulas/blob/1af03e55ebcae7808e638d8ce1243524d3059489/infrastructure-formula/infrastructure/salt/git/formulas.sls

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

Apply git.latest with branch which is already cloned but requires hard-resetting.

**Expected behavior**

Comment should be a properly formatted join of sentences.

**Screenshots**

n/a

**Versions Report**
<details><summary>salt --versions-report</summary>

Note whilst this is on an old version, the formatting still exists in master.

```yaml
Salt Version:
          Salt: 3006.0

Python Version:
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]

Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
   contextvars: 2.4
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.7.1
  looseversion: 1.0.2
      M2Crypto: 0.44.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 21.3
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 1.14.0
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: opensuse-leap 15.6
        locale: UTF-8
       machine: x86_64
       release: 6.4.0-150600.23.42-default
        system: Linux
       version: openSUSE Leap 15.6
```
</details>

**Additional context**

I will submit a patch shortly.
