### ISSUE TITLE
[BUG] salt schedule does not work masterless, `offline` required

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#67979]
**Description**
Minion configured in masterless, in order to add a job to schedule the `offline: true` argument is required in the state. Despite that, once added, in order to list the job with salt-call `offline=true` is needed but is not possible to run the job on demand, for schedule.run_job `offline` is not a valid argument. 
The job is not found

```
PS C:\Windows\system32> salt-call schedule.list offline=true
local:
    schedule:
      schedule_temp_folder_fix:
        args:
        - myapp.myapp_temp_folder
        enabled: true
        function: state.sls
        jid_include: true
        kwargs:
          queue: true
          saltenv: base
        maxrunning: 1
        name: schedule_temp_folder_fix
        return_job: false
        saved: true
        when:
        - Wednesday 11:55am

PS C:\Windows\system32> salt-call schedule.run_job schedule_temp_folder_fix
local:
    ----------
    comment:
        Job schedule_temp_folder_fix does not exist.
    result:
        False

PS C:\Windows\system32> salt-call schedule.run_job schedule_temp_folder_fix offline=true
The following keyword arguments are not valid: offline=True
```

**Setup**
minion in masterless setup with schedule job
```
file_client: local
use_master_when_local: false
file_roots:
  base:
    - 'G:\\salt\\states'
log_level_logfile: debug
scheduler_before_connect: true
```

**Steps to Reproduce the behavior**
- Configure minion in masterless
- Run state to add job or add it with salt-call, without `offline=true` it fails
```
PS C:\Windows\system32> salt-call schedule.add schedule_temp_folder_fix function='state.sls' args='["myapp.myapp_temp_folder"]' kwargs='{"saltenv": "base", "queue": true}' maxrunning=1 when='Wednesday 11:55am'
local:
    ----------
    changes:
        ----------
    comment:
        Failed to add job schedule_temp_folder_fix to schedule.
    result:
        False
```

```
{%- set schedule_date_time = 'Wednesday 11:55am' %}
{%- set state_file_path = 'myapp.myapp_temp_folder' %}
{%- set job_kwargs = {} %}
{%- do job_kwargs.update({'saltenv': 'base','queue': True}) %}
schedule_temp_folder_fix:
  schedule.present:
    - function: state.sls
    - job_args:
      - {{ state_file_path }}   
    - job_kwargs: {{ job_kwargs }}
    - enabled: true
    - return_job: false
    - offline: true #OFFLINE TRUE
    - when:
      - {{schedule_date_time }}
```

```
salt-call schedule.add schedule_temp_folder_fix function='state.sls' args='["myapp.myapp_temp_folder"]' kwargs='{"saltenv": "base", "queue": true}' maxrunning=1 when='Wednesday 11:55am' offline=true
```

**Expected behavior**
Given the minion is already set in masterless, I would expect offline to not be required. And more important, the schedule job should run on demand, which it seems not possible due schedule.run_job does not accept offline arg.

**Versions Report**
3006.7 at leasst
