### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jblac** [saltstack/salt#68041]
**Description**
The Salt mysql module fails to load on a minion when using the bundled Python 3.10 environment (/opt/saltstack/salt/bin/python3.10) due to an outdated libstdc++.so.6 in /opt/saltstack/salt/lib. The module’s __virtual__ function returns False with "No python mysql client installed," even though mysqlclient 1.4.6 is installed and MySQLdb is importable in the system Python 3.12.

** Steps to Reproduce **
1. Install Salt 3007.2 on Ubuntu 24.04.2 LTS with `/opt/saltstack` as the install path.
2. Install `mysqlclient` 1.4.6 in the system Python (`/usr/bin/python3`).
3. Verify `MySQLdb` imports in system Python:

```
/usr/bin/python3 -c "import MySQLdb"
```
4. Attempt to import `MySQLdb` in Salt's Python:
  ```
  /opt/saltstack/salt/bin/python3.10 -c "import MySQLdb"
```
This fails with:
```
ImportError: /opt/saltstack/salt/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libmysqlclient.so.21)
```
5. Run:
```
salt-call sys.doc mysql --local
```
Returns empty output due to `__virtual__` returning `False`.

** Expected Behavior **

The `mysql` module should load if `MySQLdb` is installed, using the system’s `libstdc++.so.6` (which supports `GLIBCXX_3.4.32`) instead of Salt’s outdated `libstdc++.so.6` (max `GLIBCXX_3.4.29`).

** Actual Behavior **

The `mysql` module fails to load because Salt’s Python environment uses an outdated `libstdc++.so.6`, causing `MySQLdb` import to fail.

** Environment **
* Salt Version: 3007.2
* OS: Ubuntu 24.04.2 LTS
* Python: System Python 3.1.2, Salt bundled Python 3.10.17
* MySQL Client: `mysqlclient` 1.4.6
* MySQL Server: MySQL 8.0
* Install Path: /opt/saltstack

** Workaround **
1. Rename Salt's `libstdc++.so.6`:
    ```
    mv /opt/saltstack/salt/lib/libstdc++.so.6 /opt/saltstack/salt/lib/libstdc++.so.6.bak
    ```
2. Clear cache and restart:
    ```
    rm -rf /var/cache/salt/minion/*
    systemctl restart salt-minion
    ``` 

** Suggested Fix **
* Update the bundled `libstdc++.so.6` in `/opt/saltstack/salt/lib` to support GLIBCXX_3.4.32
* Prioritize system libraries over bundled ones
* Improve `__virtual__` error messages to include import failure details.

** Additional notes
The system's `libstdc++.so.6` supports `GLIBCXX_3.4.32`. This affects states like `mysql_user.present`. A state file automating the workaround is available.

```
python_mysql:
  pip.installed:
    - name: mysqlclient
    - bin_env: '/opt/saltstack/salt/bin/python3.10'
    - env_vars:
        LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu

salt_minion_service:
  file.append:
    - name: /etc/systemd/system/salt-minion.service
    - text: Environment="LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu"
  cmd.run:
    - name: systemctl daemon-reload && systemctl restart salt-minion
    - onchanges:
      - file: salt_minion_service
```
