### ISSUE TITLE
[BUG] Regression in 3006.11 vs. 3006.10

### ISSUE THREAD

**Issue by doc75** [saltstack/salt#68061]
**Description**
When running a state `augeas.change` with salt-minion 3006.11 it fails with this message:

```
ID: <redacted>
Function: augeas.change
Result: False
Comment: State 'augeas.change' was not found in SLS '<redacted>'
Reason: 'augeas.change' is not available.
```

The exact same configuration in working fine with 3006.10 (salt master is still in 3006.11 in this case)
I noticed also that the latest version of 3007 is also having the issue (the first versions of 3007 are working fine).

**Setup**

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

Be sure to install the python augeas module with this command line:
`salt-pip install python-augeas` (with sudo in front of it in my case)

Example of state to reproduce the issue (any augeas.change would reproduce the issue):
```
<redacted>:
  augeas.change:
    - lens: Hosts.lns
    - context: /files/etc/hosts
    - changes: 
      - set 100/ipaddr '192.168.0.44'
      - set 100/canonical 'printer'
    - unless: grep '192.168.0.44' /etc/hosts
```
**Expected behavior**
`augeas.change` should be found and outpout something like: `Name: <redacted> - Function: augeas.change - Result: Clean - Started: 12:20:54.014861 - Duration: 16.048 ms`

**Screenshots**
N/A
 
**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

Version 3006.11 (failing)
```yaml
Salt Version:
          Salt: 3006.11
 
Python Version:
        Python: 3.10.17 (main, May 11 2025, 04:07:13) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.6
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.19.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-37-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```

Version 3006.10 (working fine)
```yaml
Salt Version:
          Salt: 3006.10
 
Python Version:
        Python: 3.10.16 (main, Mar  6 2025, 02:23:15) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.6
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.18.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-37-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```
</details>

**Additional context**
