### ISSUE TITLE
[BUG] 3007.4 has broken cp.push and cp.push_dir

### ISSUE THREAD

**Issue by komanek** [saltstack/salt#68093]
**Description**
After upgrade to salt 3007.4, cp.push and cp.push_dir operations are broken. Operations end up with "False" result or with exception, depending on the minion version, if master is upgraded to 3007.4

**Setup**
scenario 1: master 3007.4, minion 3007.1
scenario 2: master 3007.4, minion 3007.4
both scenarios:
- master on Ubuntu 24.04, minion on Ubuntu 22.04, Proxmox virtual machines (qemu)
- master configured with file_recv: True, size of the pushed files is bellow the default limit 100M
- packages from official SALT repo

**Steps to Reproduce the behavior**

scenario 1: master 3007.4, minion 3007.1
works well: /usr/bin/salt minion cp.push /path/to/file.txt upload_path='testfile.txt'
not working: /usr/bin/salt minion cp.push /path/to/file.txt upload_path='tmp/testfile.txt'
not working: /usr/bin/salt minion cp.push_dir /path/to/dir upload_path='tmp' glob='*.conf'
output on master: "False" as a result of the operation
journalctl on minion: "[ERROR   ] cp.push Failed transfer failed. Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the master." which is not the right description of the problem, see "setup" + worked with master 3007.1 before it was upgraded to 3007.4

solution: 
diff /opt/saltstack/salt/lib/python3.10/site-packages/salt/master.py_orig /opt/saltstack/salt/lib/python3.10/site-packages/salt/master.py
1743c1743
<         if not salt.utils.verify.clean_path(rpath, cpath):
---
>         if not salt.utils.verify.clean_path(rpath, cpath, True):

scenario 2: master 3007.4, minion 3007.4
not working: /usr/bin/salt minion cp.push /path/to/file.txt upload_path='testfile.txt'
not working: /usr/bin/salt minion cp.push /path/to/file.txt upload_path='tmp/testfile.txt'
not working: /usr/bin/salt minion cp.push_dir /path/to/dir upload_path='tmp' glob='*.conf'
output on master (even with already applied solution from scenario 1): reports minion exception

    The minion function caused an exception: Traceback (most recent call last):
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 2022, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1978, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 160, in __call__
        ret = self.loader.run(run_func, *args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1269, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1284, in _run_as
        ret = _func_or_method(*args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 160, in __call__
        ret = self.loader.run(run_func, *args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1269, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1284, in _run_as
        ret = _func_or_method(*args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/cp.py", line 1064, in push_dir
        ret = push(tmpfile, upload_path=tmpupload_path)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/cp.py", line 1004, in push
        ret = channel.send(load)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/asynchronous.py", line 139, in wrap
        raise exc_info[1].with_traceback(exc_info[2])
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/asynchronous.py", line 147, in _target
        result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs))
      File "/opt/saltstack/salt/lib/python3.10/site-packages/tornado/ioloop.py", line 539, in run_sync
        return future_cell[0].result()
      File "/opt/saltstack/salt/lib/python3.10/site-packages/tornado/gen.py", line 779, in run
        yielded = self.gen.throw(exc)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/client.py", line 353, in send
        ret = yield self._crypted_transfer(load, timeout=timeout, raw=raw)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/tornado/gen.py", line 766, in run
        value = future.result()
      File "/opt/saltstack/salt/lib/python3.10/site-packages/tornado/gen.py", line 779, in run
        yielded = self.gen.throw(exc)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/client.py", line 307, in _crypted_transfer
        ret = yield _do_transfer()
      File "/opt/saltstack/salt/lib/python3.10/site-packages/tornado/gen.py", line 766, in run
        value = future.result()
      File "/opt/saltstack/salt/lib/python3.10/site-packages/tornado/gen.py", line 233, in wrapper
        yielded = ctx_run(next, result)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/client.py", line 289, in _do_transfer
        self._package_load(load, nonce),
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/client.py", line 170, in _package_load
        load["tok"] = self.auth.gen_token(b"salt")
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 1112, in gen_token
        return self.get_keys().encrypt(clear_tok)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 1088, in get_keys
        user = self.opts.get("user", "root")
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/context.py", line 88, in get
        return self.value().get(key, default)
    AttributeError: 'NoneType' object has no attribute 'get'
ERROR: Minions returned with non-zero exit code

journalctl on minion:
[WARNING ] The minion function caused an exception

**Expected behavior**
file/directory push works with "True" as the result state for all the previous cases (default upload path, subdirectory of the default upload path, globbing)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.4
 
Python Version:
        Python: 3.10.17 (main, Jun  9 2025, 20:41:48) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
  cryptography: 42.0.5
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.31
        Jinja2: 3.1.6
       libgit2: 1.7.1
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: 1.13.3
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.19.3
         smmap: 5.0.0
       timelib: 0.3.0
       Tornado: 6.4.2
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: ubuntu 24.04.2 noble
        locale: utf-8
       machine: x86_64
       release: 6.8.0-60-generic
        system: Linux
       version: Ubuntu 24.04.2 noble
```
</details>

**Additional context**
There is clearly big difference whether the minion is on lower version than 3007.4 or if equals to master (both 3007.4). The first case seems to be easy to fix (please see the diff above), the second one is more complicated as it involves exceptions on the minion's side - I wasn't able to find a solution to this.
