### ISSUE TITLE
[BUG] cmd.run quotation handling with Windows and Powershell

### ISSUE THREAD

**Issue by Obiron801** [saltstack/salt#68118]
**Description**
Since upgrading to 3006.11, we see quotes being handled improperly when shell=powershell.
Issue is not present in 3006.10

**Setup**
- VM
- classic packaging via EXE installer

**Steps to Reproduce the behavior**
No shell specified - behaves properly 
```
salt 'minion' cmd.run 'echo "This is a test"'
minion:
    "This is a test"
```

Powershell specified - carriage returns are introduced
```
salt 'minion' cmd.run 'echo "This is a test"' shell=powershell
minion:
    This
    is
    a
    test
```

Powershell specified, quotes escaped - behaves properly
```
salt 'minion' cmd.run 'echo \"This is a test\"' shell=powershell
minion:
    This is a test
```

**Expected behavior**
Nested quotes should be handled properly when shell=powershell, without the need to be escaped.

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.11

Python Version:
        Python: 3.10.17 (heads/main:5c7faf2, May 11 2025, 04:07:07) [MSC v.1943 64 bit (AMD64)]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 3.1.6
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 25.0.2
        relenv: 0.19.2
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist:
        locale: utf-8
       machine: AMD64
       release: 2019Server
        system: Windows
       version: 2019Server 10.0.17763 SP0 Multiprocessor Free
```
</details>

**Similar issues**
[68096](https://github.com/saltstack/salt/issues/68096)
