### ISSUE TITLE
ssh_known_hosts should support the "global" /etc/ssh/ssh_known_hosts

### ISSUE THREAD

**Issue by mlebel** [saltstack/salt#6878]
Hi,

I wasn't able to find much information online and after a long while of testing, I boiled my problems down to two issues. (the second issue is not salt related therefore i won't elaborate about it here)

I'm trying to accept the fingerprint of host1 inside host2 in .ssh/known_hosts file.
Through testing, I figured out that I cannot have the same fingerprint with different users on host2.

Since this is needed, I figured out that there is a file called /etc/ssh/ssh_known_hosts. This file does the same thing but on a "global" basis. So it doesn't matter which user ssh into host1, it always works without prompting to accept the key.

Logically thinking, I thought, If I omit the username from the salt config, I figured that the fingerprint entry would show up in /etc/ssh/ssh_known_hosts. But that does not seem to be the case...It throw's me the "Missing parameter user for state ssh_known_hosts.present" error.

```
---
host1:
  ssh_known_hosts:
    - present
#    - user: root
    - fingerprint: 8e:e0:3e:44:c1:b5:3f:70:5e:10:0f:ca:f8:3a:de:38
---
```

Would anyone have a clue?
