### ISSUE TITLE
SaltStreams - Daemonized minion modules and alternative interfaces to salt

### ISSUE THREAD

**Issue by dlanderson** [saltstack/salt#7105]
Currently (as of 0.16.3), for a program running on a minion that needs to access/interact with salt the options are:
- Run salt-call, which loads its own minion object and then passes in the command line arguments to trigger a module execution.
- Be written in Python in order to be able to import the salt libs and add code to interact with the minion object.

Each of these have very obvious drawbacks.

I think salt would benefit greatly from the addition of alternative ways for the minion system to be able to interact with the salt-minion process. E.g., being able to pipe the STDOUT of a process to a "salt-pipe" command that then sends that data over a socket to a daemonized salt module which knows it is listening for output from that command and can trigger something in salt based on that data.

Along the same lines, I think there is also a need to allow salt-minion to spawn persistent daemonized modules that can trigger a salt call when something happens. E.g. a daemonized module can watch specific files/directories for changes/files created and trigger something in salt when that happens.

For lack of a better name, I have created a SaltStreams feature as a proof of concept for solving this problem. At the moment I have implemented a new script, 'salt-stream' which is launched from the cli as its own daemon and then launches any configured SaltStream modules. Each SaltStream module has its own SMinion interface for calling salt commands.

The SaltStream branch is at [dlanderson/salt/tree/saltstream](https://github.com/dlanderson/salt/tree/saltstream)

I have written a simple SocketStream module which listens on TCP/UDP/UNIX sockets and executes a salt function upon socket input. See below for an example config.

Off the top of my head, obvious use cases for new SaltStream modules would be:
- salt-pipe for sending stdout of a process to a SaltStream module - much better than piping to salt-call!
- Watch for udev events
- Watch for upstart dbus events
- Provide a syslog interface
- Watch interesting files/directories
  ...

SocketStream example:

Add to minion config:

``` yaml
streams:
  socketstream_cmd_run:
    type: socketstream.SocketStream
    fun:
        name: cmd.run
        arg: 
          - 'ls -l /tmp'
    sockets:
        - defaults:
            max_message_size: 1024
            backlog: 5
        - unix:///tmp/saltstream.cmd
        - tcp://0.0.0.0:5678:
            buffer_size: 4096
            backlog: 5
        - udp://0.0.0.0:9999:
            buffer_size: 2048
  socketstream_fire_event:
    type: socketstream.SocketStream
    fun:
        name: event.fire_master
        arg:
          - 'something to be fired'
          - 'tag'
    sockets:
        - defaults:
            max_message_size: 1024
            backlog: 5
        - unix:///tmp/saltstream.event
```

Launch `salt-stream` script

Connect to socket: `socat - UNIX-CONNECT:/tmp/saltstream.cmd`

A quick test compared to having to launch salt-call is almost 50x faster since the SaltStream already has the minion loaded:

Calling cmd.run "echo HI" through SocketStream:

```
# time salt-call cmd.run 'echo HI'                                                                                                                     
...
real    0m2.946s
user    0m0.760s
sys     0m0.770s


# time (seq 1 50 | parallel -j 10 'echo {} | socat - UNIX-CONNECT:/tmp/saltstream.cmd')
...
real    0m3.545s
user    0m0.344s
sys     0m0.934s
```

There should not be a significant issue with integrating this feature into the actual salt-minion code, but I am looking for feedback before I do any further work.

Thoughts?
