### ISSUE TITLE
augeas idempotentce

### ISSUE THREAD

**Issue by nvx** [saltstack/salt#7175]
Continuation from issue #6994 - the augeas state is not idempotent, that is if you watch an augeas state for changes it will always trigger.

Example configuration to reproduce issue:

```
postfix:
  pkg.installed:
    - name: postfix
  service.running:
    - enable: True
    - reload: True
    - watch:
      - pkg: postfix
      - augeas: /etc/postfix/main.cf

/etc/postfix/main.cf:
  augeas.setvalue:
    - prefix: /files/etc/postfix/main.cf
    - changes:
      - myhostname {{ grains['fqdn'] }}
```

In this instance postfix will be reloaded every time the state is run.

The way puppet manages idempotence with augeas is via the /augeas/save option as documented http://augeas.net/docs/tree.html instructing augeas to either create a backup file if changes are to be made, or make changes to a new copy of the file. At which point testing if changes need to be made or have been made is as simple as checking for the existence of the new or backup as appropriate and doing a diff similar to the file state to detect exact changes made.

Puppet uses the newfile method but I can't see any particular issue with using the backup method if that's any easier.

**Comment by iavael** [comment]
I'm still interested in this change

**Comment by nhavens** [comment]
I know this is an old issue. I'm only responding, because it's still open, but should probably be closed.

The example sls file has multiple issues.

1. `augeas.setvalue` is an execution module, not a state function. `augeas.change` is the correct state function.
2. `augeas.change` takes a context instead of a prefix.
3. `augeas.change` requires us to specify the augeas `set` command.
4. [Optional] switch the watch requisite to a listen. See [requisite documentation](https://docs.saltstack.com/en/latest/ref/states/requisites.html#listen-listen-in) for the difference between the two.

The modified code is indeed idempotent.

```
postfix:
  pkg.installed:
    - name: postfix
  service.running:
    - enable: True
    - reload: True
    - watch:
      - pkg: postfix
      - augeas: /etc/postfix/main.cf

/etc/postfix/main.cf:
  augeas.change:
    - context: /files/etc/postfix/main.cf
    - changes:
      - set myhostname {{ grains['fqdn'] }}
```
