### ISSUE TITLE
django.loaddata treats fixture list as arguments and prepends "--" for each

### ISSUE THREAD

**Issue by dragozov** [saltstack/salt#7287]
Example config:

```
django.loaddata:
  module.run:
    - cwd: {{ project }}/web
    - user: {{ user_name }}
    - bin_env: {{ venv }}
    - settings_module: settings
    - pythonpath: {{ project }}/web
    - fixtures: {{ project }}/web/fixtures/app_data.json,{{ project }}/web/fixtures/test.json 
```

Example error:

```
/venv/django/bin/django-admin.py: error: no such option: --/my-project/web/fixtures/app_data.json
```
