### ISSUE TITLE
salt '*' grains.items returning inconsistent results

### ISSUE THREAD

**Issue by allanparsons** [saltstack/salt#7334]
I'm currently running  salt v0.16.0-3458-g106cd6a from the develop branch to get halite to work.  My entire infrastructure is in EC2, and I installed the custom EC2 grain from (https://github.com/saltstack/salt-contrib/blob/master/grains/ec2_tags.py).

But, when I run:

    salt '*' grains.items sanitize=True

I'm getting inconsistent result sets:

RUN 1:

```
prod-salts-001:
  cpu_flags: fpu de tsc msr pae cx8 sep cmov pat clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc up rep_good nopl nonstop_tsc pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes avx hypervisor lahf_lm
  cpu_model: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  cpuarch: x86_64
  defaultencoding: None
  defaultlanguage: None
  domain: DOMAINNAME
  fqdn: MINION.DOMAINNAME
  gpus:
  host: MINION
  id: MINION.DOMAINNAME
  ip_interfaces: {'lo': ['127.0.0.1'], 'eth0': ['10.235.7.57']}
  ipv4:
      10.235.7.57
      127.0.0.1
  kernel: Linux
  kernelrelease: 3.2.0-40-virtual
  localhost: MINION
  lsb_distrib_codename: precise
  lsb_distrib_description: Ubuntu 12.04.2 LTS
  lsb_distrib_id: Ubuntu
  lsb_distrib_release: 12.04
  master: salt
  mem_total: 590
  nodename: MINION
  num_cpus: 1
  num_gpus: 0
  os: Ubuntu
  os_family: Debian
  osarch: amd64
  oscodename: precise
  osfinger: Ubuntu-12.04
  osfullname: Ubuntu
  osrelease: 12.04
  path: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
  ps: ps -efH
  pythonpath:
      /usr/bin
      /usr/lib/python2.7
      /usr/lib/python2.7/plat-linux2
      /usr/lib/python2.7/lib-tk
      /usr/lib/python2.7/lib-old
      /usr/lib/python2.7/lib-dynload
      /usr/local/lib/python2.7/dist-packages
      /usr/lib/python2.7/dist-packages
      /usr/lib/pymodules/python2.7
  pythonversion: 2.7.3.final.0
  saltpath: /usr/lib/pymodules/python2.7/salt
  saltversion: 0.16.4
  server_id: 1771887231
  shell: /bin/sh
  virtual: xen
  virtual_subtype: Xen PV DomU
```

RUN 2:

```
prod-salts-001:
  cpu_flags: fpu de tsc msr pae cx8 sep cmov pat clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc up rep_good nopl nonstop_tsc pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes avx hypervisor lahf_lm
  cpu_model: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  cpuarch: x86_64
  defaultencoding: None
  defaultlanguage: None
  domain: DOMAINNAME
  ec2_0=clique: None
  ec2_ami: /dev/sda1
  ec2_ami-id: ami-d0f89fb9
  ec2_ami-launch-index: 0
  ec2_ami-manifest-path: (unknown)
  ec2_availability-zone: us-east-1c
  ec2_device-number: 0
  ec2_ephemeral0: sdb
  ec2_hostname: ip-10-235-7-57.ec2.internal
  ec2_instance-action: none
  ec2_instance-id: i-b89417c5
  ec2_instance-type: t1.micro
  ec2_kernel-id: aki-88aa75e1
  ec2_local-hostname: ip-10-235-7-57.ec2.internal
  ec2_local-ipv4: 10.235.7.57
  ec2_local-ipv4s: 10.235.7.57
  ec2_mac: 22:00:0a:eb:07:39
  ec2_owner-id: 393727298355
  ec2_profile: default-paravirtual
  ec2_public-hostname: ec2-XXX-XXX-XXX-XXX.compute-1.amazonaws.com
  ec2_public-ipv4: XXX-XXX-XXX-XXX
  ec2_public-ipv4s: XXX-XXX-XXX-XXX
  ec2_region: us-east-1
  ec2_reservation-id: r-6c34400c
  ec2_root: /dev/sda1
  ec2_security-groups: ec2-sg-salt
  ec2_tags: {'environment': 'prod', 'Name': 'prod-salts-001'}
  ec2_vhostmd: <?xml version="1.0" encoding="UTF-8"?>
  fqdn: MINION.DOMAINNAME
  gpus:
  host: MINION
  id: MINION.DOMAINNAME
  ip_interfaces: {'lo': ['127.0.0.1'], 'eth0': ['10.235.7.57']}
  ipv4:
      10.235.7.57
      127.0.0.1
  kernel: Linux
  kernelrelease: 3.2.0-40-virtual
  localhost: MINION
  lsb_distrib_codename: precise
  lsb_distrib_description: Ubuntu 12.04.2 LTS
  lsb_distrib_id: Ubuntu
  lsb_distrib_release: 12.04
  master: salt
  mem_total: 590
  nodename: MINION
  num_cpus: 1
  num_gpus: 0
  os: Ubuntu
  os_family: Debian
  osarch: amd64
  oscodename: precise
  osfinger: Ubuntu-12.04
  osfullname: Ubuntu
  osrelease: 12.04
  path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  ps: ps -efH
  pythonpath:
      /usr/bin
      /usr/lib/python2.7
      /usr/lib/python2.7/plat-linux2
      /usr/lib/python2.7/lib-tk
      /usr/lib/python2.7/lib-old
      /usr/lib/python2.7/lib-dynload
      /usr/local/lib/python2.7/dist-packages
      /usr/lib/python2.7/dist-packages
      /usr/lib/pymodules/python2.7
  pythonversion: 2.7.3.final.0
  saltpath: /usr/lib/pymodules/python2.7/salt
  saltversion: 0.16.4
  server_id: 1771887231
  shell: /bin/bash
  virtual: xen
  virtual_subtype: Xen PV DomU
```

Not quite sure if this is a bug or not, but it's incredibly frustrating, as I'd prefer to target my environment based off the EC2 tags I set.

**Comment by maschinetheist** [comment]
I can confirm, I'm seeing similar inconsistency. Salt-master reports different results from salt-minion. In my case salt-master reports correct grains while salt-minion is missing a bunch.

```yaml
         Salt: 2015.5.3
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
         Jinja2: 2.5.5
       M2Crypto: 0.21.1
 msgpack-python: 0.1.12
   msgpack-pure: Not Installed
       pycrypto: 2.3
        libnacl: Not Installed
         PyYAML: 3.08
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
```

I had to manually add the grains to /etc/salt/grains. I tried clearing the cache and restarting/reinstalling salt-minion. I'm digging around my systems since only few of them display this issue.
