### ISSUE TITLE
improve salt file.managed with multiple sources

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#7532]
WIth the new file.append that can use multiple sources, I would like
this same functionality to file.managed:

```
/tmp/foo:
  file.managed:
      - template: jinja
      - sources:
          - salt://foo/part1.tmpl
          - salt://foo/part2.tmpl
          - salt://foo/part3.tmpl
      - defaults:
          custom_var: "default value"
          other_var: '123'
          override_me: 'fail!'

{% if grains['os'] == 'Debian' %}
      - context:
          custom_varx: "override"
          override_me: 'Pass!'
{% endif %}
```

The issue with file.append multiple sources is that if you want to change something,
it won't overwrite it will append the change in the file. If you want to replace the file with the changed one, I think you need file.managed.

see #7296 for more information.

**Comment by ewen-naos-nz** [comment]
This feature, to allow file.managed to install the combination of a set of files (which AFAICT still is not implemented 18 months later), would be an *extremely* useful equivalent to the [Ansible assemble module](http://docs.ansible.com/assemble_module.html) and [Puppet concat](https://forge.puppetlabs.com/puppetlabs/concat).  

At present it appears the only reliable way to do this with Salt is through file.managed to install the individual parts, and then cmd.run to run `cat` on the minion to put them together, along with an `unless` that tests to see if the file needs updating (eg, comparing timestamps) -- somewhat workable for combining two parts, and increasingly for more.   Plus it leaves lots of "temporary" files around on the minion which might otherwise not be needed.  (`file.accumulated` is not a viable replacement as it explicitly notes that it does not maintain order, which is important in many files built from fragments.)

Please consider actually implementing this feature to make Salt much more useful, or something like `file.concat` that is more directly equivalent to Puppet's `concat`.

Ewen

**Comment by ksalman** [comment]
Ohh I was just wanting to do this.

**Comment by lichtamberg** [comment]
+1

Any updates if this will come soon?

**Comment by mbrgm** [comment]
Also interested in this.

**Comment by folkersj** [comment]
Looking forward to use this functionality too!

**Comment by jettero** [comment]
Is there way to vote this up with a cash bounty or something?

I looked at trying to patch it in by giving an option append_mode that defaults to false. The old behavior seems to be to use the first source that works. I'd like it to use all the sources, so a simple boolean option seems to be the right way to go (to me).

Anyway, I looked at patching it in, but the states/file.py .managed and the modules/file.py .manage_file look fairly complicated. More complicated than I was hoping for sure.

**Comment by ppmathis** [comment]
Unfortunately I had some issues with the solution of @dwiest, especially when having text files that contain Jinja tags, as SaltStack would try to parse them when using *import_text*.

I decided to give writing an execution and state module a go and this is what I have ended up with: https://gist.github.com/ppmathis/a78d9000a4ba90e7f6571ce06f6bc209

There are probably more efficient or faster ways to get the job done, but those modules provide an Ansible-like way to assemble plain text files together. You can use all options of *file.managed*, with a few exceptions:

- You must specify *fragments* which should be a valid path to a directory.
- You can use *include_pat* and *exclude_pat* to filter files within that directory.  The same rules as for *file.recurse* apply.
- If you provide *template_src*, that file will be parsed by the template engine specified within *template*. A template variable called *\_\_fragments\_\_* gets passed, containing a list of a dictionaries with the keys *source* (original path to fragment file on minion) and *content*.
- If you do -not- provide *template_src*, all files get concattenated together without any delimiter.
- The keys *source*, *source_hash*, *contents*, *contents_grains* and *contents_pillar* are not supported for obvious reasons.

I successfully use this module for assembling several files/fragments together, which are getting generated before by file.managed states. The linked Gist contains an example state file at the end.

**Comment by lichtamberg** [comment]
@dwiest Your solution looks nice, could you maybe update your post and include also how you configured the crt/key (without posting your private keys xD)?

**Comment by lichtamberg** [comment]
@ppmathis Don't you want to create a PR so we can get work on this issue running?

**Comment by lichtamberg** [comment]
I found a solution now with following code (join newlines in state, split them again in jinja template:

```yaml
# mystate.sls

application_yml:
  file.managed:
    - name: /home/deployer/apps/myadmin/system_config/application.yml
    - source: salt://myadmin/files/application.yml.jinja
    - user: {{ salt["pillar.get"]("base:user")}}
    - group: {{ salt["pillar.get"]("base:group")}}
    - makedirs: True
    - template: jinja
    - context:
        PUSHER_APP_KEY: {{ salt['pillar.get']('slanger:app_key', '') }}
        application_yml:  |
            {{ salt['pillar.get']('application.yml', '') | replace('\n', '\\n') }}
```

```yml
# application.yml.jinja
PUSHER_APP_KEY: {{ PUSHER_APP_KEY }}
{{ application_yml | replace('\\n', '\n') }}
```
