### ISSUE TITLE
pidfile support for services

### ISSUE THREAD

**Issue by hathawsh** [saltstack/salt#761]
I'd like to be able to specify a pidfile for service definitions, e.g.:

```
nagios-nrpe-server:
    service:
        - running
        - sig: /usr/sbin/nrpe
        - pidfile: /var/run/nrpe.pid
```

Specifying the pidfile should make process status detection more robust. I've written versions of the service module and service state that accept a pidfile; are you interested in integrating my versions?
