### ISSUE TITLE
pillar.get('top:sub') won't work

### ISSUE THREAD

**Issue by reinsle** [saltstack/salt#7645]
Hi saltstack,

i'm using salt version 0.17.0 and i've got the Problem getting subvalue of pillar data.

I use following pillar structure:

``` yaml
toplevel:
  key1:
    value1
  key2:
    value2
  key3:
    value3
```

salt '*' pillar.data toplevel shows the data. But using pillar.get(toplevel:key2') as described in https://salt.readthedocs.org/en/latest/ref/modules/all/salt.modules.pillar.html#salt.modules.pillar.get will gives me None instead of value2.

Thanks a lot

Robert
