### ISSUE TITLE
Version support for "sources" arg in pkg.installed states

### ISSUE THREAD

**Issue by Cidan** [saltstack/salt#7772]
Example config:

```
erlang:
  pkg.installed:
    - sources:
      - esl-erlang: salt://files/packages/esl-erlangR15B02.deb
```

If I were to change the above config to use a deb with the version R16B02, salt does not upgrade the package because esl-erlang is already installed, and pkg.latest does not work with a "sources" parameter.
