### ISSUE TITLE
Support tilde-prefixed home directories in salt.states.file

### ISSUE THREAD

**Issue by andrewclegg** [saltstack/salt#7883]
I just tried to copy some files into a bunch of user's home directories, using tilde prefixes:

```
~{{ user }}/.ssh:
    file.recurse:
        - source: salt://conf/common/dotssh
        - dir_mode: 700
        - file_mode: 600
```

Forgetting of course that tilde-expansion is a shell function... So salt.states.file rejected them as not being absolute paths.

But supporting these could be very convenient in some cases. e.g. I may want to give a public key to a list of users, but some of them may be "service" users whose home directories are in /var.

If salt.states.file called os.path.expanduser on any target path before using os.path.isabs to check them, it could support tilde-prefixed home directories easily.

EDIT: Feel free to treat this as lowest priority :-) since after all you can work around it with a custom jinja filter.
