### ISSUE TITLE
Now that we have debconf seeding, on to dpkg-reconfigure!

### ISSUE THREAD

**Issue by blast-hardcheese** [saltstack/salt#796]
I'm not sure what the best way to do this would be, but it would be nice if there were a way to dpkg-reconfigure based on whether or not the file specified by pkg: - debconf: has changed since the last time.

```
libpam-ldapd:
    pkg:
        - installed
        - debconf: salt://debconf/ldap-client.ans
        - reconfigure
```

would be my first guess, but the relationship between debconf and reconfigure is ambiguous. I guess dpkg-reconfiguring every time highstate is run wouldn't be the end of the world, it just seems wasteful.

Another issue here is that debconf is not checked if the package is already installed... so maybe that's the real target here. Thoughts?
