### ISSUE TITLE
prereq infinite recursion with pip

### ISSUE THREAD

**Issue by djs52** [saltstack/salt#8212]
I've been using prereq to stop a service before upgrading a package installed with pip. This worked fine in 0.16.3, but with 0.17.1 I get infinite recursion of 

```
  File "/usr/lib/pymodules/python2.7/salt/state.py", line 1504, in call_chunk
    running = self.call_chunk(low, running, chunks)
```

Small test states:

```
example:
  pip:
    - installed
  service:
    - require:
      - pip: example
    - running
    - enable: true

stop-before-upgrade:
  service:
    - name: example
    - dead
    - prereq:
      - pip: example
```

Note that in the output I also see 

```
[ERROR   ] State pip.installed found in sls test is unavailable
```

even though I've got python-pip installed. I don't know if this is related. It may also be related to #8210
