### ISSUE TITLE
salt-ssh - own pillars don't work in managed files

### ISSUE THREAD

**Issue by grembo** [saltstack/salt#8340]
This fails with "Undefined jinja variable; line xxx in template".

It works ok using using zmq.

salt-ssh '*' pillar.show lists all pillars as expected, --log-level=trace shows that they're found. Using config pillars works, e.g. {{ pillar['master']['user'] }}.

Example:

pillar/top.sls:
```
base:
  '*':
    - test
```
pillar/test.sls:
```
testip:
  hosta: 10.10.10.1
  hostb: 10.10.10.2
```

states/top.sls:
```
base:
  '*':
    - test
```

states/test.sls:
```
/tmp/file:
  file.managed:
    - source: salt://file
    - template: jinja
```

states/file:
```
{{ pillar['testip']['hosta'] }}
```

(alternatively use pillar['testip'][grains['id']], original intent, same result).

master:
```
file_roots:
  base:
    - /usr/local/etc/salt/states/

pillar_roots:
  base:
    - /usr/local/etc/salt/pillar
```
