### ISSUE TITLE
salt-ssh: wrong node id

### ISSUE THREAD

**Issue by oleksiyk** [saltstack/salt#8347]
Looks like salt-ssh is always using hostname of the minion instead of the ID specified in roster file:

I have a roster file:
```
vagrant.test-1:
  host: 10.0.1.10
  user: vagrant
  sudo: true
  priv: ~/.vagrant.d/insecure_private_key
```

and a top.sls file:
```
base:
  'vagrant*':
    - test
```

This doesn't work when I use salt-ssh as:
`salt-ssh -c ./deploy/etc/ --out=key 'vagrant*' state.highstate`

The output is:
```
vagrant.test-1:
    ----------
```

But if I put the hostname of that vagrant box into top.sls it will work.
top.sls:
```
base:
  'test1-box':
    - test
```

Output of salt-ssh:
```
vagrant.test-1:
    ----------
    pkg_|-nginx_|-nginx_|-installed:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            Package nginx is already installed
        name:
            nginx
        result:
            True
```
