### ISSUE TITLE
pip state cannot install packages on Windows minions

### ISSUE THREAD

**Issue by otrempe** [saltstack/salt#8405]
With python/mako.sls file being:
```
mako:
    pip.installed
```
```
salt -G 'os:Windows' state.sls python.mako
```
gives
```
----------
    State: - pip
    Name:      mako
    Function:  install
        Result:    False
        Comment:   State pip.installed found in sls python.mako is unavailable

        Changes:
                   ----------

```

Also,

```
salt -G 'os:Windows' pip.list
```
gives
```
    ----------
    pip:
        1.4.1
    pywin32:
        218
```

I tested all of this on a linux minion and it all works well.

**Comment by tensorproduct** [comment]
Is there any movement on this issue? I'm still seeing the same problem on 2014.1.13 and 2014.7.0

foo.sls
```
devpi:
  pip.install
```

`PS C:\> salt-call state.sls foo`
```
----------
          ID: devpi
    Function: pip.install
      Result: False
     Comment: State 'pip.install' found in SLS 'foo' is unavailable
     Started:
    Duration:
     Changes:
```
