### ISSUE TITLE
Add a Service provider to manage services using custom scripts

### ISSUE THREAD

**Issue by mingfang** [saltstack/salt#8478]
Currently there are service providers for popular service managers like upstart.
However some applications are not designed to be "real" services and has to be started using shell script.  It would be great if there was a Service Provider that allows me to execute any shell command to manage my services.
Here is what it can look like...

```
  service.running:
    -provider: custom
      - start: "/opt/app/myapp&"
      - stop: "kill pid"
      - status: "ps aux|grep myapp|grep -v grep"
```

Puppet has this feature and this is what it looks like

```
service { 'postgresql':
  provider => base,
  ensure   => 'running',
  start    => '/etc/init.d/postgresql start',
  restart  => '/etc/init.d/postgresql restart',
  stop     => '/etc/init.d/postgresql stop',
  status   => "pg_lsclusters -h | awk 'BEGIN {rc=0} {if (\$4 != \"online\") rc=3} END { exit rc }'",
}
```

All of our in house Java based applications will need this feature so please add it. Thanks.
