### ISSUE TITLE
Windows:  file.directory  users and permissions?

### ISSUE THREAD

**Issue by emmellee** [saltstack/salt#8539]
In my masterless windows environment, I would like to not only create directories if they do not exist, but ensure they have the permissions I need.  How might I do that?

```
D:\\tomcats\tomcat-jenkins\work:
  file.directory:
    - makedirs: True
    - user: Jenkins  ????
    - mode: FullControl  ????

D:\\jenkins-jobhome:
  file.directory:
    - makedirs: True
    - group: JenkinsGroup  ????
    - mode: FullControl  ????
```

Thanks.
