### ISSUE TITLE
salt-cloud cannot query ec-2 instances in a map if more than one provider is defined

### ISSUE THREAD

**Issue by sroegner** [saltstack/salt#8574]
This problem occurs using salt-cloud out of salt:develop HEAD.
I reproduced this with both - two providers defined in /etc/salt/cloud or two files in /etc/salt/cloud.providers.d.

There needs to be only one profile defined using one of the providers and a map with a single host in it. As long as it is down the map and host can be queried against and started using the -m switch. As soon as the map was started, any action causes the exception below:

    [INFO    ] salt-cloud starting
    [INFO    ] Applying map from '/etc/salt/bug.map'.
    [ERROR   ] There was an error with a custom map: 'bug-1'
    Traceback (most recent call last):
      File "/home/jenkins/sources/salt.HEAD/salt/cloud/cli.py", line 134, in run
    query=self.selected_query_option
      File "/home/jenkins/sources/salt.HEAD/salt/cloud/__init__.py", line 1052, in interpolated_map
      names.remove(vm_name)
    KeyError: 'bug-1'

To reproduce this, one can simply use an existing provider/profile/map configuration and duplicate the provider under a new name

    Salt: 0.17.0-4613-g954f51e
    Python: 2.6.9 (unknown, Oct 29 2013, 19:58:13)
    Jinja2: 2.7.1
    M2Crypto: 0.21.1
    msgpack-python: 0.4.0
    msgpack-pure: Not Installed
    pycrypto: 2.6.1
    PyYAML: 3.10
    PyZMQ: 14.0.0
    ZMQ: 4.0.1

**Comment by iggy** [comment]
I seem to be hitting this on 2015.5.0. Did anyone ever figure out a workaround? (tried splitting my providers into separate config files, etc.)

**Comment by rallytime** [comment]
@iggy I doesn't look like anyone has tackled this one yet. I don't know of a work around currently. Do you @techhat?

I'll bump up the severity of this issue. Hopefully we can get some more eyes on it.

**Comment by rallytime** [comment]
Hrm. I am unable to reproduce this issue. I tried it both at the HEAD of 2015.8 as well as with 2015.5.0. Perhaps I am misunderstanding how to configure everything to trigger this bug. Here's what I have:

Two Files in `/etc/salt/cloud.providers.d/`:
```
# /etc/salt/cloud.providers.d/ec2.conf
ec2-config:
  minion:
    master: <redacted>
  id: <redacted>
  key: <redacted>
  keyname: nt-cloud
  securitygroup: class
  private_key: /etc/salt/cloud_keys/nt-cloud.pem
  location: us-east-1
  rename_on_destroy: True
  provider: ec2
```
```
# /etc/salt/cloud.providers.d/ec2-copy.conf
ec2-config-copy:
  minion:
    master: <redacted>
  id: <redacted>
  key: <redacted>
  keyname: nt-cloud
  securitygroup: class
  private_key: /etc/salt/cloud_keys/nt-cloud.pem
  location: us-east-1
  rename_on_destroy: True
  provider: ec2
```
A simple profile in `/etc/salt/cloud.profiles.d/`:
```
# /etc/salt/cloud.profiles.d/ec2.conf
ec2-ubuntu-14:
  provider: ec2-config
  image: ami-98aa1cf0
  size: t1.micro
  sh_username: ec2-user
  script_args: '-Z -P git 2015.5'
```
And my map file:
```
# /etc/salt/map
ec2-ubuntu-14:
  - nt-ec2-map-0
```
Both versions I tested completed successfully without any problems with a `salt-cloud -m /etc/salt/map` command.

@iggy or @sroegner - what are you doing differently, or what am I missing, to reproduce this bug?
