### ISSUE TITLE
pip state: proxy not supported when using bin_env

### ISSUE THREAD

**Issue by otrempe** [saltstack/salt#8639]
Installing a pip package behind a proxy works fine. However, when specifying a bin_env, the proxy seems to be ignored.

buildbot/master.sls

```
buildbot_master_venv:
    virtualenv.managed:
        - name: /opt/buildbot/venv

buildbot:
    pip.installed:
        - proxy: {{pillar['http_proxy']}}
        - bin_env: /opt/buildbot/venv/bin/pip
```

Calling state.highstate for a Ubuntu host gives 

```
 ----------
    State: - pip
    Name:      buildbot
    Function:  installed
        Result:    False
        Comment:   Failed to install package buildbot. Error: Downloading/unpacking buildbot
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement buildbot
No distributions at all found for buildbot
Storing complete log in /root/.pip/pip.log
        Changes:
```
