### ISSUE TITLE
salt '*' highstate returns 'minion did not return', salt [minion] highstate works

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#8647]
There's an apparent difference in targeting '*' and a host directly. (0.17.2 all the way now)

I have this state that updates salt to the latest version:
```
salt-minion:
  pkg:
    - latest
    - order: last  #zodat een upgrade niet de states halvewege vernielt
  service.running:
    - require:
      - pkg: salt-minion
    - enable: true
    - watch:
      - file: /etc/salt/minion.d/id.conf
      - file: /etc/salt/minion.d/tcp-keepalive.conf
```
It should be a no-op, since I'm on the latest version (I checked this time :)

It returns with a no-op when targeted directly, but it doesn't return at all when targeted with '*'. It does run, I can see that because I run the minion on the console with `salt-minion -d debug`.

So, to re-iterate:

```
salt '*' state.sls all-salt-minion-config
```
gives me
```
[lots of output]
idd0010:
    Minion did not return
[more output]
```
but 
```
salt idd0010 state.sls all-salt-minion-config
```
gives me
```
root@salt-master:/home/salt/conf# salt idd0010 state.sls all-salt-minion-config
Executing job with jid 20131119222944774230
-------------------------------------------

Execution is still running on idd0010
idd0010:

Summary
-----------
Succeeded: 0
Failed:   0
-----------
Total:    0
```
Complete output from salt-minion -d debug is on http://pastebin.com/10h2YETr
