### ISSUE TITLE
gitfs backend error related to SSH host key checking

### ISSUE THREAD

**Issue by pniederw** [saltstack/salt#8684]
After setting up a gitfs backend for a (private) GitHub repo, the following appeared in the master log:

    [salt.loaded.int.fileserver.gitfs][WARNING ] GitPython exception caught while
    fetching: len(["c179aa10976f1152d37e1deca0736698da8744bd\tnot-for-
    merge\tbranch 'master' of git+ssh://xxx\n"]) != len(["Warning: Permanently added the 
    RSA host key for IP address 'xxx' to the list of known hosts.", '', ' = [up to date]      
    master     -> origin/master'])

Workaround was to add the following to `.ssh/config`:

    Host github.com
    User salt
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null

Salt 0.17.2, Ubuntu Raring

**Comment by c4milo** [comment]
I'm having this same issue. I had to use `gitpython` because getting `pygit2` installed on Ubuntu Trusty is a pain in the butt. 

Here is my config: 

```yaml
auto_accept: True

file_roots:
  base:
    - /srv/salt/formulas

fileserver_backend:
  - git

gitfs_remotes:
  - git+ssh://git@github.com/managedbyq/salt-states.git

gitfs_root: formulas
gitfs_base: stg
```

I have my deploy key under `/root/.ssh/id_rsa`

After adding `StrictHostKeyChecking no` in `/root/.ssh/config` the host warning went away but I'm now getting this error: 


2015-05-06 01:00:25,735 [salt.loaded.int.fileserver.gitfs][ERROR   ] Exception ''Error when fetching: fatal: Could not read from remote repository.' returned exit status 2: None' caught while fetching gitfs remote git+ssh://git@github.com/managedbyq/salt-states.git
