### ISSUE TITLE
The cron state doesn't cleanup after itself

### ISSUE THREAD

**Issue by SaltwaterC** [saltstack/salt#8852]
There's a nice comment into the generated crontab:

```bash
# Lines below here are managed by Salt, do not edit
```

However, that's not the case. I edited the name of a cron by adding an argument to script invoked by it. Ended up with two entries doing almost the same thing.

Example:

```yaml
/usr/bin/foo /path/to/bar:
  cron.present:
    - user: wibble
    - hour: 10
    - minute: 30
    - require:
      - pkg: foo
```

It was changed into:

```yaml
/usr/bin/foo /path/to/bar some-random-argument:
  cron.present:
    - user: wibble
    - hour: 10
    - minute: 30
    - require:
      - pkg: foo
```

Ended up with this crontab:

```bash
# Lines below here are managed by Salt, do not edit
30 10 * * * /usr/bin/foo /path/to/bar
30 10 * * * /usr/bin/foo /path/to/bar some-random-argument
```

For the moment I think that having a managed file and a command that imports the crontab from that file isn't surprise prone.

PS: sorry if this is a dupe. I *did* search for it.
