### ISSUE TITLE
Support relative includes for pillar

### ISSUE THREAD

**Issue by pniederw** [saltstack/salt#8875]
The dot notation that's supported for relative includes in state files  (`include: - .other`) doesn't seem to work for pillar. Would be just as useful there.

**Comment by wuxxin** [comment]
+1 
because this way you can write:
----
something/common.sls
{% load_yaml as common %}
test:
   whatever: true
   another:
      hu: he
{% endload %}
----
something/another.sls
include:
  - .common

{{ common.something }}

**Comment by uvsmtid** [comment]
To complement this issue, this is how to live now with workaround.

## Workaround ##

Push a variable with location of the pillar into the pillar template being included using `defaults` as described in [doc how to include pillar](http://docs.saltstack.com/en/latest/topics/pillar/#including-other-pillars).

#### Example ####

The top file is not used, but it's important to note that it cannot use `include` directly.

All we need to do is to list the first "entry point" pillar which will `include` others.
```
# top.sls
base:
    '*':
        - main
```
Include pillar and tell it where it is located using `this_pillar`.
```
# main.sls
include:
    - deep.inside.directory.structure.pillar_a:
        defaults:
            this_pillar: deep.inside.directory.structure.pillar_a
```
Include other pillars relatively:
```
# deep.inside.directory.structure.pillar_a.sls
include:
    - {{ this_pillar }}.whatever:
    - {{ this_pillar }}.blah_blah_blah:
    - {{ this_pillar }}.last_one:
```

#### Proper complication ####

Because you don't know (or you don't want to keep this in mind) whether any pillar subsequently includes relatively anything else or not, the safest way is to pass `this_pillar` recursively to every other one being included (just in case).
```
# deep.inside.directory.structure.pillar_a.sls
include:
    - {{ this_pillar }}.whatever:
        defaults:
            this_pillar: {{ this_pillar }}.whatever
    - {{ this_pillar }}.blah_blah_blah:
        defaults:
            this_pillar: {{ this_pillar }}.blah_blah_blah
    - {{ this_pillar }}.last_one:
        defaults:
            this_pillar: {{ this_pillar }}.last_one
```
It's ugly, but it works.
