### ISSUE TITLE
Support passing variable bindings when including state SLS files

### ISSUE THREAD

**Issue by pniederw** [saltstack/salt#8878]
It would be very useful to have something like pillar include's `defaults:` attribute (or file.managed's `context:` attribute) for state includes. Essentially, this would give a way to write composite state functions with SLS files alone.

**Comment by puneetk** [comment]
https://github.com/saltstack/salt/issues/1419 and https://github.com/saltstack/salt/pull/3613 is relevant

**Comment by daicoden** [comment]
FWIW - Template support is necessary for managing an SOA, and the macro solution was not obvious from reading the docs. I would pitch a syntax which mirrored file.manage specification.

```
include:
  - docker.docker-template:
    - template: jinja
    - defaults:
        custom_var: "default value"
        other_var: 123
  - docker.docker-template:
    - template: jinja
    - defaults:
        custom_var: "another value"
        other_var: 456
{% if grains['os'] == 'Ubuntu' %}
    - context:
        custom_var: "override"
{% endif %}
```

**Comment by cystek** [comment]
The macro solution also does not appear to work across different environments. That is, if I define the macro in a base environment but need to use it in a separate environment on top of base it will not work, giving an error "Jinja variable 'macro_name' is undefined." This feature, or at least allowing macros to work across environments, would be very helpful.

In case it's useful, the test macro in the base environment is:
`{% macro test_template(file_path, file_source, template=False, file_user='root', file_group='root', file_mode='644') %}
{{file_path}}:
  file.managed:
    - source: salt://{{file_source}}
    {% if template %}
    - template: jinja
    {% endif %}
    - user: {{file_user}}
    - group: {{file_group}}
    - mode: {{file_mode}}
{% endmacro %}

/tmp/foo.txt:
  file.managed:
    - source: salt://test/files/check_ntp.sh
    - user: root
    - group: root
    - mode: 644`

and its attempted usage is: 
`include:
  - base: templates.test-template

{{test_template('/tmp/test.txt', 'templatetest/files/test.txt.jinja', True)}}`

**Comment by anitakrueger** [comment]
I'm wondering if this is on any radar at the moment? I just ran into this because I have 2 states which need to include a common state and the 2 states need to be able to be applied on their own as well as together in a highstate. When running highstate however, I get the `Detected conflicting IDs, SLS IDs need to be globally unique.` error.

If I was able to use includes with parameters, then the highstate should work.

Here is my current code:
At the moment I have this, which produces the conflicting IDs error when both states are applied in the highstate:
**a.sls**
```
{%- from 'common.sls' import common with context %}
{{ common('appA') }}
```
**b.sls**
```
{%- from 'common.sls' import common with context %}
{{ common('appB') }}
```
**common.sls**
```
{%- macro common(app) %}
/opt/software/{{ app }}:
  file.directory:
    - user: root
    - group: root
{%- endmacro %}
```

Here is how I could see this work if includes supported defaults:
**a.sls**
```
include:
  - common:
    - template: jinja
    - defaults:
        app: appA
```
**b.sls**
```
include:
  - common:
    - template: jinja
    - defaults:
        app: appB
```
**common.sls**
```
/opt/software/{{ app }}:
  file.directory:
    - user: root
    - group: root
```

**Comment by max-arnold** [comment]
+1 for parametrizable includes. Jinja macro doesn't work over salt-ssh and needs an `extra_filerefs` setting.

**Comment by jtoops009** [comment]
I'm also interested in passing in variable bindings since I have some templates that are mostly common and I rather not duplicate them.

**Comment by cystek** [comment]
@anitakrueger FYI, here's a possible workaround for your particular case using Jinja2 variables:

**common.sls**
```
{{ app }}-file-in-opt-software:
  file.directory:
    - name: /opt/software/{{ app }}
    - user: root
    - group: root
```
Creating a name out of the variable then defining the path later helps avoid name/state collisions like you are experiencing.

**a.sls**
```
{% set app = appA %}
{% include common.sls %}
```

**b.sls**
```
{% set app = appB %}
{% include common.sls %}
```
