### ISSUE TITLE
file state: unable to use `contents_pillar` with `template: jinja`

### ISSUE THREAD

**Issue by brutasse** [saltstack/salt#8927]
I have the following state.

`states/elasticsearc/init.sls`:

``` yaml
elasticsearch:
  pkg:
    - installed
  service.running:
    - enable: true
  file.managed:
    - contents_pillar: elasticsearch:config
    - template: jinja
    - name: /etc/elasticsearch/elasticsearch.yml
    - watch_in:
      - service: elasticsearch
```

And in `pillar/elasticsearch.sls`:

``` yaml
elasticsearch:
  data: /home/elasticsearch
  config: |  # note that this block is raw text, *not* YAML
    bootstrap.mlockall: true
    cluster.name: logging
    node.master: true
    node.data: true
    index.number_of_shards: 5
    index.number_of_replicas: 0
    network.host: 0.0.0.0
    discovery.zen.ping.multicast.enabled: false
    discovery.zen.ping.unicast.hosts: [ '127.0.0.1' ]
    path.data: {{ pillar['elasticsearch']['data'] }}
```

I'm trying to define the location of elasticsearch data only once and reference it in the config file which comes from `contents_pillar`. This fails with the following error:

```
es-machine:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'elasticsearch' failed, render error:
Undefined jinja variable; line 353 in template
<content of pillar/elasticsearch.sls>
```

Of course salt tries to load the pillar as jinja template which fails because the pillar data is referencing itself. So I tried something else:

`pillar/elasticsearch.sls`:

``` yaml
elasticsearch:
  data: /home/elasticsearch
  config: |
    # etc etc
    path.data: {% raw %}{{ pillar['elasticsearch']['data'] }}{% endraw %}
```

Beautiful :) Here the content isn't evaluated as a template and pillar data loads. However the file state still doesn't treat the content as a jinja template, meaning I get the raw line in my config.

The issue is that the file state treats `content` and `source` differently. Would it be possible to re-render the content against pillar data when `template: jinja` is used with `contents_pillar`?
