### ISSUE TITLE
Recurse is including mode when it shouldn't

### ISSUE THREAD

**Issue by liquidgecka** [saltstack/salt#9037]
Unless I am completely mistaken the following block:

```
/tmp/a:
  file.directory:
    - user: nobody
    - group: nogroup
    - mode: 755
    - recurse:
      - user
      - group
```

Should ensure that /tmp/a is owned by nobody/nogroup and has mode 755, and that the contents of /tmp/a recursively would be owned by nobody/nogroup, however the mode would be left alone.

When I start with this state:
```
-rw-r--r-- 1 nobody nogroup    0 Dec  4 21:55 /tmp/a/c
-rw-r--r-- 1 nobody nogroup    0 Dec  4 21:55 /tmp/a/b
drwxr-xr-x 2 nobody nogroup 4096 Dec  4 21:55 /tmp/a
```

I get this output line:
```
 Name: /tmp/a - Function: file.directory - Result: True
```

And end in this state:
```
-rwxr-xr-x 1 nobody nogroup    0 Dec  4 21:55 /tmp/a/c
-rwxr-xr-x 1 nobody nogroup    0 Dec  4 21:55 /tmp/a/b
drwxr-xr-x 2 nobody nogroup 4096 Dec  4 21:55 /tmp/a
```

I expect that the state would not trigger since its acceptable in the first pass. This is causing salt to restart a bunch of our services every time its run since we deliver files inside of a directory managed this way.
