### ISSUE TITLE
`cmd.script` should support setting a template context (like `file.managed`)

### ISSUE THREAD

**Issue by pniederw** [saltstack/salt#9153]
State functions that support templating (like `cmd.script`) should also support setting a template context (like `file.managed` does). One consequence of not having a context is that template variables defined in the SLS (e.g. loop variables) cannot be made available to the script.

**Comment by anlutro** [comment]
Has anything been done with this?

**Comment by basepi** [comment]
Unfortunately, we haven't had time to implement this yet.

**Comment by lorengordon** [comment]
:+1:

**Comment by ferricoxide** [comment]
As we extend Salt to cover more (vendor) software that doesn't have pre-canned saltstack modules, this is becoming more critical to us. So, tossing in a  :+1:  , here

**Comment by lorengordon** [comment]
@basepi Do you know where to start looking at how to do this? I traced the rendering piece all the way back to `__context__['cp.fileclient']`, but didn't see where I might pass in the `context` dict from the state. I looked at `file.managed` and other `file` functions, but it wasn't super clear. 

Is `context` simply available as a **kwarg in `__context__['cp.fileclient']`? The `file` functions sort of make it look like that is the case. If so, it might be super easy to add `defaults` and `context` as parameters to the `cmd.script` state, merge/update them and pass the `context` through as kwargs to the `cmd.script` module, which would keep passing them on as kwargs until they got to `__context__['cp.fileclient']`...

**Comment by basepi** [comment]
Hrm, I'm not sure off the top of my head. The fileclient parts of salt are one of the parts I haven't spent much time in. However, I do know that `__context__['cp.fileclient']` is just a RemoteClient or LocalClient as defined in `salt/fileclient.py`. A cursory glance tells me they don't support a `context` kwarg to their `get_template` functions, at least not directly. But they do take `**kwargs` and pass those along, so `context` may work....

In fact, yes, I think that might work. We pass `**kwargs` to the `salt.utils.templates.TEMPLATE_REGISTRY[template](sfn, **kwargs)` call. So the template is obviously looking for a specific kwarg for that context, just have to track down which kwarg. You may have to look into the renderers themselves.

Hopefully that's a good starting point. =)

**Comment by lorengordon** [comment]
Ha! Yeah, that was easy. Below is a working diff. Tested with v2015.5.5 on Windows. I can document the params and create the PR, too. What branch would you like it submitted against?

```diff
diff --git a/salt/states/cmd.py b/salt/states/cmd.py
index f4f7aea..caf6ea8 100644
--- a/salt/states/cmd.py
+++ b/salt/states/cmd.py
@@ -746,6 +746,8 @@ def script(name,
            timeout=None,
            use_vt=False,
            output_loglevel='debug',
+           defaults=None,
+           context=None,
            **kwargs):
     '''
     Download a script and execute it with specified arguments.
@@ -860,6 +862,10 @@ def script(name,
     if HAS_GRP:
         pgid = os.getegid()

+    tmpctx = defaults if defaults else {}
+    if context:
+        tmpctx.update(context)
+
     cmd_kwargs = copy.deepcopy(kwargs)
     cmd_kwargs.update({'runas': user,
                        'shell': shell or __grains__['shell'],
@@ -874,6 +880,7 @@ def script(name,
                        'timeout': timeout,
                        'output_loglevel': output_loglevel,
                        'use_vt': use_vt,
+                       'context': tmpctx,
                        'saltenv': __env__})

     run_check_cmd_kwargs = {
```

cmdtest.bat:
```
@echo off
echo foo = {{ foo }}
echo bar = {{ bar }}
echo baz = {{ baz }}
```

cmdtest.sls:
```
{%- set foo = 'imafoo' %}
{%- set bar = 'imabar' %}
{%- set baz = 'imabaz' %}

test defaults:
  cmd.script:
    - name: salt://cmdtest.bat
    - template: jinja
    - defaults:
        foo: {{ foo }}
        bar: {{ bar }}
        baz: {{ baz }}

test context:
  cmd.script:
    - name: salt://cmdtest.bat
    - template: jinja
    - context:
        foo: {{ foo }}
        bar: {{ bar }}
        baz: {{ baz }}

test defaults and context:
  cmd.script:
    - name: salt://cmdtest.bat
    - template: jinja
    - defaults:
        foo: {{ foo }}
        bar: {{ bar }}
        baz: {{ baz }}
    - context:
        foo: {{ bar }}
        bar: {{ baz }}
        baz: {{ foo }}
```

salt-call.bat --local state.sls cmdtest:
```
local:
----------
          ID: test defaults
    Function: cmd.script
        Name: salt://cmdtest.bat
      Result: True
     Comment: Command 'salt://cmdtest.bat' run
     Started: 19:55:34.593000
    Duration: 77.0 ms
     Changes:
              ----------
              pid:
                  23248
              retcode:
                  0
              stderr:
              stdout:
                  foo = imafoo
                  bar = imabar
                  baz = imabaz
----------
          ID: test context
    Function: cmd.script
        Name: salt://cmdtest.bat
      Result: True
     Comment: Command 'salt://cmdtest.bat' run
     Started: 19:55:34.673000
    Duration: 42.0 ms
     Changes:
              ----------
              pid:
                  24996
              retcode:
                  0
              stderr:
              stdout:
                  foo = imafoo
                  bar = imabar
                  baz = imabaz
----------
          ID: test defaults and context
    Function: cmd.script
        Name: salt://cmdtest.bat
      Result: True
     Comment: Command 'salt://cmdtest.bat' run
     Started: 19:55:34.718000
    Duration: 43.0 ms
     Changes:
              ----------
              pid:
                  24180
              retcode:
                  0
              stderr:
              stdout:
                  foo = imabar
                  bar = imabaz
                  baz = imafoo

Summary
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
```
