### ISSUE TITLE
Feature Request: Environments improvements to make them actually usable.

### ISSUE THREAD

**Issue by erenfro** [saltstack/salt#9186]
Currently, Salt's environments are not very usable. When I think of a class of sorts completely isolated or stacked (stacked would be better, but isolated would still work).

The idea I have would make for actually developing states without mass deploying them possible, while still stacking hosts to multiple environments. 

Pillars has an order of pillar states it loads, and if you, for example, have:

```
pillar_roots:
  base:
    - /srv/salt/base/pillars
  dev:
    - /srv/salt/base/pillars
    - /srv/salt/prod/pillars
    - /srv/salt/dev/pillars
  prod:
    - /srv/salt/base/pillars
    - /srv/salt/prod/pillars
```

This allows you to target a host from multiple environments, and the last-matching one overrides the former. So if I have a pillar that's in both prod and dev, and I target a host with both prod environment and dev environment, the dev one wins out in the end because of the ordering and stacking.

Currently, the state system doesn't do this, and merges everything together in what seems to be like `$salt['environment']['state']...`-like order, and if any `$salt[*]['state']` exists in the final results, it conflicts rather than doing the same file_roots order as suggested by http://docs.saltstack.com/ref/file_server/file_roots.html which looks for a file in the order provided, only resulting in one match, not all (course that's for the fileserver).

The way this would benefit is in the case of the following example:

```
file_roots:
  base:
    - /srv/salt/base/states
  dev:
    - /srv/salt/base/states
    - /srv/salt/prod/states
    - /srv/salt/dev/states
  prod:
    - /srv/salt/base/states
    - /srv/salt/prod/states
```

```
top.sls:
base '*': 
    - auth
    - base-install
prod:
  '*':
    - zabbix.agent
    - postfix
    - salt.tag
dev:
  'test-*':
    - auth
    - salt.tag
```

In this example concept, currently it would immediately conflict if I had auth and salt.tag with the exact same state definitions as in base and pro

The idea of this is, I want to update auth and salt.tag in my dev environment I targeted here which is included in the global default normally as well, but I don't want the changes to go out to production servers until I move/copy it into prod to actually "push it to live". Initially it would see that in base, there is auth, and in prod there is salt.tag. But once it stacks up to dev, it sees auth is being re-called again and replacing it with the state from dev, likewise for salt.tag.

This structure allows for targeting and stacked hierarchical environmental structure allowing you to maintain multiple environments, either related to other environments or completely isolated.  But most importantly, stackable modular salt states that you can actually test before you launch.

Otherwise, the only other way to test your stuff is:

A> Be /exact/ on targeting only the systems you want and never target *. This requires you have a dedicated server to do nothing but salt testing on and that's all it really does, in an idea world this is not likely to happen.

B> Test in production.

C> Test in completely segmented salt states, which again requires dedicated servers to test with, but in this case, even more servers, not just a singular one.

Stacked states instead of merged states would allow development, overriding states from other environments, and more complete modularity.
