### ISSUE TITLE
Failed post installation scripts do not return any output to salt

### ISSUE THREAD

**Issue by ruimarinho** [saltstack/salt#9237]
When attempting to install packages, if any error occurs during the post installation script, salt is not able to capture the output and present it in the comment's field. Instead, a simpler message is shown.

Below is an approximation for a reproducible test case. Notice that the '{{ var }}' tokens are not supposed to be rendered by jinja. They should be interpreted as literals so that the elasticsearch postinst script attempts to "addgroup {{ group }}", resulting in this error:

```
addgroup: Please enter a username matching the regular expression configured
via the NAME_REGEX configuration variable.  Use the `--force-badname'
option to relax this check or reconfigure NAME_REGEX.
dpkg: error processing elasticsearch (--install):
```

```
----------
          ID: elasticsearch
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: elasticsearch.
     Changes:
```

```
elasticsearch-init.d-defaults:
  file.managed:
    - name: /etc/default/elasticsearch
    - content: |
       ES_USER={{ user }}
       ES_GROUP={{ group }}

elasticsearch:
   - pkg:
     - installed
  - require:
    - file: elasticsearch-init.d-defaults
```
