### ISSUE TITLE
Reactors share the same yaml namespace

### ISSUE THREAD

**Issue by whiskybar** [saltstack/salt#9277]
master.conf:

```
reactor:
  - 'tag1':
    - file1.sls
    - file2.sls
```

file1.sls:

```
formula1:
  cmd.cmd.run:
    - tgt: server1
    - arg:
      - mkdir /srv
```

file2.sls:

```
formula1:
  cmd.cmd.run:
    - tgt: server1
    - arg:
      - cp /etc/passwd /srv
```

Basically, `mkdir /srv` never gets executed. I believe the reactor formulas should live in their own namespace, just like state formulas do in separate files. 

Both reactors render, but then the formula1 from file2.sls overwrites the formula1 from file1.sls in the reactor space and only this get executed.
