### ISSUE TITLE
file.recurse doesn't support multiple sources like file.managed does

### ISSUE THREAD

**Issue by localfilmmaker** [saltstack/salt#9304]
I expect file.recurse to behave the same as file.managed when providing a source.  Meaning that you could provide a list of sources and it would use the first one that exists.  However, file.recurse doesn't do this; it only takes one source value.

I'd like to do something like this:
```
/etc/skel:
  file.recurse:
    - user: root
    - group: root
    - source:
      - salt://packages/core/files/skel.{{ grains['host'] }}
      - salt://packages/core/files/skel.{{ grains['server_role'] }}
      - salt://packages/core/files/skel
```
Thus having different files and subdirectories for /etc/skel/ for different hosts.  Currently it doesn't work this way and I don't know of any alternate way to do it.
