### ISSUE TITLE
Ability to set environment variable for pkg.installed state

### ISSUE THREAD

**Issue by blackduckx** [saltstack/salt#9332]
Hi all,

I have a few editor rpms that require variable to be exported before rpm installation.

It would be nice if salt could support that.

Regards,
Frédéric

**Comment by fsniper** [comment]
With 2015.5.2 (Lithium) it's not working but once upon a time I could use this like:
``` 
    sudo-ldap:
        pkg.installed:
            - env:
                - SUDO_FORCE_REMOVE: yes
```

**Comment by 2ion** [comment]
Please add this capability to pkg.installed and friends. It is arguably rarely used and can be worked around by using the cmd module, but for example installing sudo-ldap over sudo on Debian/Ubuntu requires an environment variable to be set to for sudo removal; if not set, the package manager will always fail to complete the operation.

**Comment by Omeryl** [comment]
Yeah I need this for a few different things as well.

**Comment by jkramarz** [comment]
In 2015.8.10 it can be done in this way:

```
cassandra.prevent_start.enable:
  environ.setenv:
    - name: RUNLEVEL
    - value: "1"

cassandra.installed:
  pkg.installed:
    - name: cassandra

cassandra.prevent_start.disable:
  environ.setenv:
    - name: RUNLEVEL
    - value: False
    - false_unsets: True
```

If it's too long, you can always define a macro.
It would be nice to have "env" parameter, but it would duplicate existing feature.
