### ISSUE TITLE
Feature: Allow nodegroup matching in client_acl

### ISSUE THREAD

**Issue by TamCore** [saltstack/salt#9665]
Hi!

It would be very helpful, if it would be possible, to use nodegroups instead of minion ids in client_acl.

```
client_acl:
  somedeveloper:
    - '*.dev.location':
      - .*
    - 'some.production.sys':
      - a.bit.more.limited
    - 'another.production.sys':
      - a.bit.more.limited
```

becomes

```
client_acl:
  somedeveloper:
    - '*.dev.location':
      - .*
    - 'production':
      - match: nodegroup
      - a.bit.more.limited
```

In our case some our developers should be allowed to do everything on their development machines, but do only a few restricted tasks on our production environment.

Cheers
