### ISSUE TITLE
Impossible to pass saltenv parameter to saltutil.sync_* functions from state.sls

### ISSUE THREAD

**Issue by mbirtwell** [saltstack/salt#9731]
I was trying to force a grains sync prior to my first highstate by setting my startup_state to a sls file that looked like:

```
------
saltutil.sync_all:
    module.run:
      - saltenv: base

state.highstate:
    module.run:
      - require:
          - module: saltutil.sync_all
------
```

However I noticed that saltenv was not getting passed through to the saltutil.sync_all function because it is a reserved word in the state system.
