### ISSUE TITLE
minion not returning, apt-get defunct

### ISSUE THREAD

**Issue by jakwas** [saltstack/salt#9736]
I am using SaltStack 0.17.4 on Debian 7.3 for master and minion with great success, but have run into a problem.

Running "salt-call -l debug state.highstate" on the minion is successful, but when running "salt 'host' state.highstate" from the master, or using the daemon with "startup_states: highstate" on the minion causes apt-get to become defunct, and I suspect one of the package scripts might be causing this.

I am trying to install Proxmox VE as per http://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Wheezy and have traced the problem to the following section in my state file:

```
pve:
  pkg:
    - installed
    - pkgs:
      - proxmox-ve-2.6.32
      - lvm2
      - postfix
      - ksm-control-daemon
      - vzprocps
      - open-iscsi
      - bootlogd
```

```
salt --versions-report:
Salt: 0.17.4
Python: 2.7.3 (default, Jan  2 2013, 13:56:14)
Jinja2: 2.6
M2Crypto: 0.21.1
msgpack-python: 0.1.10
msgpack-pure: Not Installed
pycrypto: 2.6
PyYAML: 3.10
PyZMQ: 13.1.0
ZMQ: 3.2.3
```

Any thoughts?
