### ISSUE TITLE
salt-ssh pkg.install debconf= broken (module and state)

### ISSUE THREAD

**Issue by leonardinius** [saltstack/salt#9849]
This is what I see running  smth like https://github.com/rentalita/ubuntu-setup/blob/master/salt/gitolite/init.sls#L4-L7 For the sake of readability - will copy it here as well

```
gitolite:
  pkg:
    - latest
    - debconf: salt://gitolite/gitolite.answers
```

**Out**

```
...
  pkg_|-gitolite_|-gitolite_|-latest:
        ----------
        __run_num__:
            18
        changes:
            ----------
        comment:
            An exception occurred in this state: Traceback (most recent call last):
              File "/tmp/.salt/salt/state.py", line 1368, in call
                **cdata['kwargs'])
              File "/tmp/.salt/salt/states/pkg.py", line 701, in latest
                **kwargs)
              File "/tmp/.salt/salt/modules/apt.py", line 378, in install
                __salt__['debconf.set_file'](debconf)
            KeyError: 'debconf.set_file'

        name:
            gitolite
        result:
            False
...
```
## 

Initially I thought this option is not supported, since this option seemed not be state module, but instead salt module (I might misuse terminology, using the terms used in salt documentation pages)

[Salt state module](http://docs.saltstack.com/ref/states/all/salt.states.pkg.html#module-salt.states.pkg) has no mention of it, however seems in might be supported (especially if found online examples it's usage, see above)

[Salt apt module](http://docs.saltstack.com/ref/modules/all/salt.modules.apt.html#salt.modules.apt.install) however lists debconf as supported option.

Initially I asked questions about this on salt-user iirc channel and got initial response I mix salt states and salt-modules. However since I have both found the online example (presumably working) and failed to run salt-module (see below) as documented - I decided to submit my question in the form of github issue. imo, either documentation or code is broken. 

---

**Questions**
- is debconf supported as part of state module option?
- is debconf supported as part of sast system module? e.g. 

```
salt-ssh '*'  pkg.install gitolite 'debconf=salt://gitolite/gitolite.answers'
minion1:
    Traceback (most recent call last):
      File "/tmp/.salt/salt-call", line 4, in <module>
        salt_call()
      File "/tmp/.salt/salt/scripts.py", line 82, in salt_call
        client.run()
      File "/tmp/.salt/salt/cli/__init__.py", line 313, in run
        caller.run()
      File "/tmp/.salt/salt/cli/caller.py", line 137, in run
        ret = self.call()
      File "/tmp/.salt/salt/cli/caller.py", line 78, in call
        ret['return'] = func(*args, **kwargs)
      File "/tmp/.salt/salt/modules/apt.py", line 378, in install
        __salt__['debconf.set_file'](debconf)
    KeyError: 'debconf.set_file'
```
- is debconf just broken with salt-ssh or broken in last/development? _Note_: The way I've installed salt is as documented at saltstack/salt-bootstrap e.g. `curl -L http://bootstrap.saltstack.org | sudo sh -s -- git develop`

**version info**

```
root@salt:/media/sf_provisioning# salt --versions-report
           Salt: 2014.1.0-438-g23eb3a7
         Python: 2.7.3 (default, Sep 26 2013, 20:03:06)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
root@salt:/media/sf_provisioning#
```

**Comment by abcfy2** [comment]
Same issue here:

/srv/salt/java/java8.sls:
```
{% if grains['osrelease'] < '16.04' %}
java8_ppa_proxy:
  pkgrepo.managed:
    - name: "deb http://launchpad.proxy.ustclug.org/webupd8team/java/ubuntu {{grains['oscodename']}} main"
    - file: /etc/apt/sources.list.d/java8.list
    - keyid: EEA14886
    - keyserver: keyserver.ubuntu.com
    - clean_file: True
    - require:
      - pkg: common_pkgs

java8-debconf:
  debconf.set:
    - name: oracle-java8-installer
    - data:
        'shared/accepted-oracle-license-v1-1': {'type': 'select', 'value': 'true'}

oracle-java8-set-default:
  pkg.installed:
    - require:
      - pkgrepo: java8_ppa_proxy
{% else %}
openjdk-8-jdk:
  pkg.installed
{% endif %}
```

salt-ssh '*' state.apply java.java8
```
----------
          ID: java8-debconf
    Function: debconf.set
        Name: oracle-java8-installer
      Result: False
     Comment: State 'debconf.set' was not found in SLS 'java.java8'
              Reason: 'debconf.set' is not available.
     Changes:   
----------
          ID: oracle-java8-set-default
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - 
                    oracle-license-v1-1 license could not be presented
                    try 'dpkg-reconfigure debconf' to select a frontend other than noninteractive
                    
                    dpkg: error processing archive /var/cache/apt/archives/oracle-java8-installer_8u111+8u111arm-1~webupd8~0_all.deb (--unpack):
                     subprocess new pre-installation script returned error exit status 2
                    Errors were encountered while processing:
                     /var/cache/apt/archives/oracle-java8-installer_8u111+8u111arm-1~webupd8~0_all.deb
                    E: Sub-process /usr/bin/dpkg returned an error code (1)
     Started: 15:27:05.576413
    Duration: 7054.683 ms
     Changes:   
```

But salt-minion works very well.
