### ISSUE TITLE
for grant in grants: TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by jeremyBass** [saltstack/salt#9856]
Hello,

I use

```
# Setup the MySQL requirements for WSUMAGE-base
###########################################################
{{ magento['db_name'] }}:
  mysql_user.present:
    - name: {{ magento['db_user'] }}
    - password: {{ magento['db_pass'] }}
    - host: {{ magento['db_host'] }}
    - require:
      - service: mysqld
  mysql_database.present:
    - name: {{ magento['db_name'] }}
    - require:
      - service: mysqld
  mysql_grants.present:
    - grant: all privileges
    - database: {{ magento['db_name'] }}.*
    - user: {{ magento['db_user'] }}
    - require:
      - service: mysqld
```

and get 

```
 Name: wsumage_network - Function: mysql_database.present - Result: True
----------
    State: - mysql_grants
    Name:      wsumage_network
    Function:  present
        Result:    False
        Comment:   An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1305, in call
    *cdata['args'], **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/states/mysql_grants.py", line 122, in present
    grant, database, user, host, grant_option, escape, **connection_args
  File "/usr/lib/python2.6/site-packages/salt/modules/mysql.py", line 1154, in grant_exists
    for grant in grants:
TypeError: 'bool' object is not iterable

        Changes:
```
Looks like a Boolean is being treated as a list?
