### ISSUE TITLE
pkg.removed and version problems on windows minion.

### ISSUE THREAD

**Issue by emmellee** [saltstack/salt#9929]
Issue 4492  was closed about 9 months ago concerning pkg.removed problems on a windows minion; however I am experiencing similar problems.  In my standalone windows environment, I cannot specify a version or get "removed" to work within a state.file.

My version is:

```
C:\salt>salt --versions-report
           Salt: 0.17.2
         Python: 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Inte
l)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.2
```

Each java upgrade is added to the init.sls in the winrepo like so:

```
javasdk:
  1.7.0.510:
    installer: 'D:\\srv\salt\file_roots\winrepo\javasdk\jdk-7u51-windows-i586.exe'
    full_name: 'Java SE Development Kit 7 Update 51'
    reboot: False
    install_flags: ' /s /v"/norestart AUTOUPDATECHECK=0 JAVAUPDATE=0 JU=0 WEBSTARTICON=0 EULA=0 SYSTRAY=0" '
    msiexec: False
    uninstaller: 'msiexec.exe'
    uninstall_flags: ' /X{32A3A4F4-B792-11D6-A78A-00B0D0170510} /qn'
  1.7.0.250:
    installer: 'D:\\srv\salt\file_roots\winrepo\javasdk\jdk-7u25-windows-i586.exe'
    full_name: 'Java SE Development Kit 7 Update 25'
    reboot: False
    install_flags: ' /s /v"/norestart AUTOUPDATECHECK=0 JAVAUPDATE=0 JU=0 WEBSTARTICON=0 EULA=0 SYSTRAY=0" '
    msiexec: False
    uninstaller: 'msiexec.exe'
    uninstall_flags: ' /X{32A3A4F4-B792-11D6-A78A-00B0D0170250} /qn'
```

...which allows me to manually remove or install a specific version of the package from the command line like so:

salt-call pkg.remove javasdk version=1.7.0.510

But, I wish to manage the pkg installations and removals via states rather than command line. Unfortunately, I'm unable to successfully install or remove a specific version of the pkg like so:

```
core-install:
  pkg:
    - installed
    - names:
      - firefox
      - tortoisesvn
      - javasdk: '1.7.0.510'
      - 7zip

core-remove:
  pkg:
    - removed
    - names:
      - javasdk: '1.7.0.250'
```

The state file is never parsed correctly, but chokes on the use of "removed" and the version number.
