### ISSUE TITLE
Salt pip_state -pre_releases option does not allow installing pip packages with pre-release versions

### ISSUE THREAD

**Issue by dan1** [saltstack/salt#9939]
The pip.installed state option '-pre_releases'  should be equivalent to: 
$ pip install --pre some_pip_package.pre-release-version

Currently it does not allow pre-release versions to be installed.

Example sls file:

...

my-python-package:
  pip.installed:
    - name: my-python-package
    - upgrade: True
    - bin_env: /usr/local
    - pre_releases: True

...

pip version is 1.4.1

**Comment by majuscule** [comment]
I found this ticket while debugging a similar (the same?) issue, but am confused as there are not many details here. I am using a similar state, and see the following debug output from my salt run:

```
[DEBUG   ] TRY BLOCK: end of pip.install -- cmd: ['/var/web/myapp/venv/bin/pip', 'install', '--pre', 'myapp[production]'], cmd_kwargs: {'runas': 'myapp', 'use_vt': False, 'saltenv': 'base', 'env': {'VIRTUAL_ENV': '/var/web/myapp/venv'}}
```

Despite the explicit command arguments listed, the prereleases are not installed. When I run the stripped command by hand, i.e.: `/var/web/myapp/venv/bin/pip install --pre myapp[production] `, the prerelease *does* install. What could possibly be going wrong here?

**Comment by majuscule** [comment]
Threatening to close a (high severity tagged) issue because no progress has been made on it in four years is not a good look.

**Comment by wilson** [comment]
This still seems to be broken. The state below doesn't do what you'd expect, and never installs a pre-release:

```
example-install:
  pip.installed:
    - extra_index_url: 'https://{{ pillar['pip']['packagecloud_token']}}:@packagecloud.io/foo/baz/pypi/simple'
    - bin_env: /var/web/example/venv
    - user: example
    - name: example_package[production]
    - upgrade: True
    - pre_releases: {% if 'staging' in grains['id'] %} True {% else %} False {% endif %}
```
