### ISSUE TITLE
Improve documentation of saltify "cloud" provider

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#9969]
I'm trying out saltify in salt-cloud.

The documentation needs improving: 

```
make_salty:
  myinstance:
    ssh_host: 192.168.0.19
    ssh_username: root
    #ssh_passwd: root
    key_filename: /etc/salt/passphrase-less-salt-key.pem
```

ssh_keyfile does not work. and ssh_password doesn't really seem to be implemented (would it use something like sshpass ? )

The documentation should also mention that one needs /etc/salt/cloud.providers.d/saltify.conf with 

```

saltify:
    provider : saltify
```
